### ISSUE TITLE
Google Play Games bundle file not found.

### ISSUE THREAD

**Issue by echeg** [playgameservices/play-games-plugin-for-unity#100]
On Android all works fine. But IOS...

can somebody explain what I'm doing wrong.
1 I download build 9.0.0 and add to Unity
2 Download and unzip to desktop https://developers.google.com/games/services/downloads/ - 5 files
3 GPS setup in unity and compile to xcode
4 In Xcode i add 
      AddressBook
      AssetsLibrary
      CoreData
      CoreLocation
      CoreMotion
      CoreText
      MediaPlayer
      QuartzCore
      Security
      SystemConfiguration
      libc++.dylib
5 Add from desktop. 
      GoogleOpenSource.framework
      GooglePlus.bundle
      GooglePlus.framework
      GooglePlayGames.bundle
      GooglePlayGames.framework
6 Add -ObjC' and -fobjc-arc"
7 Compile build no errors.
8 Authenticate  - works fine
9:
(Filename: /Applications/buildAgent/work/d3d49558e4d408f4/artifacts/iPhonePlayer-armv7Generated/UnityEngineDebug.cpp Line: 53)

-> applicationWillResignActive()
-> applicationDidEnterBackground()
-> applicationWillEnterForeground()
-> applicationDidBecomeActive()
2014-04-08 05:39:13.433 PortalMaze[236/0x3a4a718c] [lvl=3] -[GPGDatabase initWithModelName:modelFileType:storeName:] Google Play Games bundle file not found. Make sure you have added GooglePlayGames.bundle to your project!
2014-04-08 05:39:13.465 PortalMaze[236:60b] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
**\* First throw call stack:
(0x2df1bf4b 0x382ab6af 0x2de557ab 0x2de57e01 0xf50767 0xf4fd91 0xf69e75 0xf6987d 0xf684d9 0xe58638 0xe58f24 0x11081ad 0x1104033 0x11077a5 0xedb899 0xedc61b 0x2e856203 0x2e856147 0x2e856061 0x2db87dfb 0x2db86a0b 0x2dbb82bf 0x2de4f659 0x2db1eb35 0x2db1ea05 0x2db1e899 0x2dee7183 0x2dee6653 0x2dee4e47 0x2de4fc27 0x2de4fa0b 0x32b2e283 0x306f3049 0xecbd0 0x387b3ab7)
libc++abi.dylib: terminating with uncaught exception of type NSException

Do I need to add any of these files is
      GoogleOpenSource.framework
      GooglePlus.bundle
      GooglePlus.framework
      GooglePlayGames.bundle
      GooglePlayGames.framework
To project in Unity Editor? To plugin folder?

**Comment by claywilkinson** [comment]
2014-12-29 11:58:49.106 Core __49-[GPGService     executeOperation:completionHandler:]_block_invoke:[main]
     Server Operation Failed [appstate.states.list]
    Error: The operation couldn’t be completed. (Insufficient Permission)
    Error Full: Error Domain=com.google.GTLJSONRPCErrorDomain Code=403
     "The operation couldn’t be completed. (Insufficient Permission)" 
    UserInfo=0x136d880 {error=Insufficient Permission, GTLStructuredError=GTLErrorObject 0x136bfa0: {message:"Insufficient Permission" code:403 data:[1]}, NSLocalizedFailureReason=(Insufficient Permission)}

This error related to appstate.states.list is because the appstate API has been deprecated and new games cannot be created that use it.  If you use the latest plugin (0.9.11), then you can use the SavedGame API to save the game.
