### ISSUE TITLE
Helpppp!!! Cannot Upgrade from 0.9.26 to 0.9.31a

### ISSUE THREAD

**Issue by simgesimulation** [playgameservices/play-games-plugin-for-unity#1000]
@claywilkinson 
Bro please update the UPGRADING.txt file because I cannot update from 0.9.26 to 0.9.31a. I updated android support repository. I deleted google-play-services_lib folder. Imported 0.9.31a package. What should I do more? It gives me errors while building!!! Three errors on console:

1-) TypeLoadException: Could not load type 'ResolverVer1_1'.
System.Type.GetType (System.String typeName, Boolean throwOnError) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Type.cs:471)
GooglePlayServices.PlayServicesResolver.get_Resolver () (at Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:96)
GooglePlayServices.PlayServicesResolver.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:117)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:26)
UnityEditor.AssetDatabase:Refresh()
GooglePlayGames.Editor.GPGSUpgrader:.cctor() (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:102)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

2-)CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Users\Hakan\AppData\Local\Android\android-sdk\build-tools\22.0.1\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Users/Hakan/AppData/Local/Android/android-sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages

3-)Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Users\Hakan\AppData\Local\Android\android-sdk\build-tools\22.0.1\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Users/Hakan/AppData/Local/Android/android-sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages

**Comment by claywilkinson** [comment]
What version of Unity are you using?  I'll write it up today.

**Comment by simgesimulation** [comment]
I am using 5.1.1p4

**Comment by simgesimulation** [comment]
@claywilkinson I am still waiting you update Upgrade.txt file and to help me:(

**Comment by claywilkinson** [comment]
@simgesimulation  - I got pulled in different direction yesterday.  I am doing this now. please stand by :)

**Comment by claywilkinson** [comment]
Here are the steps I used to upgrade from 0.9.26 to 0.9.31a using Unity 5.1.1f1 (the only 5.1 version on the Unity website).

There is one manual patch you'll need to make (documented at the end).  But I listed my before, during, and after information for reference.

Let me know if you have problems, I will update the plugin shortly, so it does not need to be patch by hand.

Before trying to upgrade here is what my project looked like:
<img width="599" alt="screen shot 2016-02-25 at 11 46 12 am" src="https://cloud.githubusercontent.com/assets/8752378/13332143/7d9779a8-dbb5-11e5-8800-441201002552.png">

Note a couple things:
1. This old project uses google-play-services_lib. 
2. There is no play services resolver folder.


Then I imported version 0.9.31a.  Make sure to click "All" at the bottom, then "Import"
<img width="563" alt="screen shot 2016-02-25 at 11 51 27 am" src="https://cloud.githubusercontent.com/assets/8752378/13332300/34267994-dbb6-11e5-8491-ee188616fc73.png">

I get the alert dialog that version 0.9.31a is installed is now ready to use.

I check the console in Unity - and there are some errors:
* Errors like `Error importing folder ....already mapped to  0a..... but  the meta data wants 0b.... can be ignored.

Warnings like these are handled by the plugin.  It deletes the old file and renames the copy as the original.  
`Created unique file for imported asset as file exists with different GUID (Assets/Plugins/Android/libs/armeabi-v7a/libgpg.so => Assets/Plugins/Android/libs/armeabi-v7a/libgpg 1.so)`

I got an error:
`TypeLoadException: Could not load type 'ResolverVer1_1'.
System.Type.GetType (System.String typeName, Boolean throwOnError) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Type.cs:471)
GooglePlayServices.PlayServicesResolver.get_Resolver () (at Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:96)
GooglePlayServices.PlayServicesResolver.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:117)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:26)
UnityEditor.AssetDatabase:Refresh()
GooglePlayGames.Editor.GPGSUpgrader:.cctor() (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:102)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])
`

This is a bug which happens sometimes (I am still investigating).  A [fix was merged today](https://github.com/googlesamples/unity-jar-resolver/pull/2) for this.  You need to apply it manually to this plugin: 
In file `Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs`
Replace lines 96-98  to be:
` _resolver = Activator.CreateInstance("GooglePlayServices", CurrentResolverName) as IResolver;`

This will fix the error.  Save the file and go back to Unity.  Clear the console output to confirm there are no errors.

The play services resolver should resolve the dependencies needed (deleting google-play-services_lib in the process).  The project should look like:
<img width="638" alt="screen shot 2016-02-25 at 12 10 31 pm" src="https://cloud.githubusercontent.com/assets/8752378/13332883/ee8b6d1a-dbb8-11e5-881f-eea521c0a0e8.png">

Where the play-services-* files are .aar files.

Run  Windows > Google Play Games > Setup > Android Setup again.  Then build and run your app.

**Comment by claywilkinson** [comment]
OK to close this one?
