### ISSUE TITLE
Unable to start a multiplayer game - intermittent

### ISSUE THREAD

**Issue by danspeedy1** [playgameservices/play-games-plugin-for-unity#1001]
Hi,

I'm unable to start a real time multiplayer game. Below are the logs. I've done some debugging and in NativeRealtimeMultiplayerClient.cs on line 933, the response object contains a request status of "ERROR_INTERNAL". I have not been able to figure out what this error actually means. I'm running the latest Unity and version of this plugin. I've been through the setup 3 times to be sure I didn't miss anything.

> 02-25 00:25:05.653: I/Unity(18970):  [Play Games Plugin DLL] 02/25/16 0:25:05 +00:00 DEBUG: Entering state: BeforeRoomCreateStartedState
> 02-25 00:25:05.653: I/Unity(18970):  
> 02-25 00:25:05.653: I/Unity(18970): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 02-25 00:25:05.653: I/Unity(18970):  [Play Games Plugin DLL] 02/25/16 0:25:05 +00:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
> 02-25 00:25:05.653: I/Unity(18970):  
> 02-25 00:25:05.653: I/Unity(18970): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 02-25 00:25:05.654: I/Unity(18970):  [Play Games Plugin DLL] 02/25/16 0:25:05 +00:00 DEBUG: QuickGame: Setting MinPlayersToStart = 1
> 02-25 00:25:05.654: I/Unity(18970):  
> 02-25 00:25:05.654: I/Unity(18970): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 02-25 00:25:05.665: I/Unity(18970):  [Play Games Plugin DLL] 02/25/16 0:25:05 +00:00 DEBUG: OnData Callback has addr: 35
> 02-25 00:25:05.665: I/Unity(18970):  
> 02-25 00:25:05.665: I/Unity(18970): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 02-25 00:25:05.672: I/Unity(18970):  [Play Games Plugin DLL] 02/25/16 0:25:05 +00:00 DEBUG: BeforeRoomCreateStartedState.IsNonPreemptable: Is preemptable by default.
> 02-25 00:25:05.672: I/Unity(18970):  
> 02-25 00:25:05.672: I/Unity(18970): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 02-25 00:25:05.672: I/Unity(18970):  [Play Games Plugin DLL] 02/25/16 0:25:05 +00:00 DEBUG: Entering state: RoomCreationPendingState
> 02-25 00:25:05.672: I/Unity(18970):  
> 02-25 00:25:05.672: I/Unity(18970): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 02-25 00:25:05.673: I/Unity(18970):  [Play Games Plugin DLL] 02/25/16 0:25:05 +00:00 DEBUG: RoomCreationPendingState.OnStateEntered: Defaulting to no-op.
> 02-25 00:25:05.673: I/Unity(18970):  
> 02-25 00:25:05.673: I/Unity(18970): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 02-25 00:25:06.496: I/libjingle(12715): Token type:OAuth2
> 02-25 00:25:06.496: I/libjingle(12715): Final XMPP server hostname talk.google.com port to 5222
> 02-25 00:25:06.736: I/libjingle(12715): OpenSSLAdapter::OnConnectEvent
> 02-25 00:25:06.787: I/libjingle(12715): BeginSSL: talk.google.com
> 02-25 00:25:06.816: W/libjingle(12715): Warning(openssladapter.cc:388): ContinueSSL -- error -1
> 02-25 00:25:06.816: W/libjingle(12715): Warning(openssladapter.cc:397): OpenSSLAdapter::Error(ContinueSSL, -1)
> 02-25 00:25:06.816: I/libjingle(12715): SSL Cleanup
> 02-25 00:25:06.836: I/libjingle(12715): Token type:OAuth2
> 02-25 00:25:06.837: I/libjingle(12715): Final XMPP server hostname talk.google.com port to 5222
> 02-25 00:25:06.862: I/libjingle(12715): OpenSSLAdapter::OnConnectEvent
> 02-25 00:25:06.913: I/libjingle(12715): BeginSSL: talk.google.com
> 02-25 00:25:06.941: W/libjingle(12715): Warning(openssladapter.cc:388): ContinueSSL -- error -1
> 02-25 00:25:06.942: W/libjingle(12715): Warning(openssladapter.cc:397): OpenSSLAdapter::Error(ContinueSSL, -1)
> 02-25 00:25:06.942: I/libjingle(12715): SSL Cleanup
> 02-25 00:25:06.943: W/AppOps(775): Bad call: specified package com.google.android.play.games under uid 10275 but it is really 10067
> 02-25 00:25:06.943: W/AppOps(775): Bad call: specified package com.google.android.play.games under uid 10275 but it is really 10067
> 02-25 00:25:06.946: I/Unity(18970):  [Play Games Plugin DLL] 02/25/16 0:25:06 +00:00 DEBUG: Entering internal callback for RealtimeManager#InternalRealTimeRoomCallback
> 02-25 00:25:06.946: I/Unity(18970):  
> 02-25 00:25:06.946: I/Unity(18970): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 02-25 00:25:06.957: I/Unity(18970):  [Play Games Plugin DLL] 02/25/16 0:25:06 +00:00 DEBUG: Entering state: ShutdownState
> 02-25 00:25:06.957: I/Unity(18970):  
> 02-25 00:25:06.957: I/Unity(18970): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 02-25 00:25:06.957: I/Unity(18970):  [Play Games Plugin DLL] 02/25/16 0:25:06 +00:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
> 02-25 00:25:06.957: I/Unity(18970):  
> 02-25 00:25:06.957: I/Unity(18970): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 02-25 00:25:06.960: D/ChimeraCfgMgr(11031): Loading module com.google.android.gms.games from APK com.google.android.play.games
> 02-25 00:25:06.960: D/ChimeraModuleLdr(11031): Module APK com.google.android.play.games already loaded
> 02-25 00:25:06.967: I/Unity(18970): OnRoomConnected has failed

**Comment by danspeedy1** [comment]
@claywilkinson is this similar to the issue we saw before with RTMP? Strangely enough, once or twice I have seen the waiting room lobby open up with no errors. But 99% of the time I get the above error without changing anything.

**Comment by claywilkinson** [comment]
Can you confirm that RTMP is enabled for your game on the Play Game Console?  Also, can you share the version of play services, and the play games app,  there should be a logcat line that lists all these numbers:
`W/GamesServiceBroker( 1645): Client connected with SDK 8487000, Services 8489238, and Games 35170038`

**Comment by danspeedy1** [comment]
@claywilkinson  Doubled checked and RTMP is enabled in the dev console, as it was before.

Here is the log for version numbers

02-25 18:46:14.660: W/GamesServiceBroker(1028): Client connected with SDK 8487000, Services 8489070, and Games 36250070

**Comment by claywilkinson** [comment]
Thanks, I'll pass this info along.  Do you have an unfiltered log?  That would help expedite getting it looked at.

**Comment by danspeedy1** [comment]
Yesterday it started working again... No changes my side.  Just fired up the app on two devices and everything just worked. I'll keep an eye on this for a few days.

**Comment by claywilkinson** [comment]
OK thanks.  Do you mind sharing where in the world you are?  North America? Europe? Asia?

**Comment by danspeedy1** [comment]
UK, Europe
OK thanks.  Do you mind sharing where in the world you are?  North America? Europe? Asia?

---

**Comment by danspeedy1** [comment]
UK, Europe

**Comment by PEMPE** [comment]
Hello,
This happens to me too. an intermittent failure in creating RTMP room, I thought GPG have implemented a limit, because it happens to me after doing more or less 10 consecutive invites. I dont know if it is just a coincidence but it started happening to me after I have updated my GPG app last week.

**Comment by danspeedy1** [comment]
I'm happy to close this. Must have been something on Google's side. @PEMPE  are you happy to close this or are you still seeing the issue?

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
