### ISSUE TITLE
Apk-File very large

### ISSUE THREAD

**Issue by Droidspirit** [playgameservices/play-games-plugin-for-unity#1002]
Hello,

after upgrading my game to the newest play-games-version my apk-file has 43 mb now. Previously had the file 25 mb. The Plugins/Android Folder has 10 mb and there are some play-services which i not need (gplus, drive, and so one). If I delete some files there will be generated automatically again.

It is possible to prevent the creation of some files  and/or reduce the plugin size?

Thank you and best regards

Andre

**Comment by danspeedy1** [comment]
When you import the package I believe you can select which parts of the package to import.

I have no idea which ones are essential and which ones can be omitted but take a look. It might be obvious.

**Comment by Droidspirit** [comment]
Yes, you're right. But the files in /Plugins/Android/ will be generated automatically after importing the asset. There's no pre-selection, which play-services i want to use.

**Comment by claywilkinson** [comment]
I am curious, what was the size before? We made the switch from using the play_services_lib to using the split aars to dramatically reduce the size. (For example the minimal sample was reduced by almost 50%.

The play-services aar files that are pulled in are needed by Play Game Services.  For example, Drive is used for Saved Games,  GPlus is used for the email and user token.

You can turn off the automatic resolution from Assets/Google Play Services/Settings and try removing them and see what does not work, but "officially" they are all needed.  

If you do experiment, please share your experiences!

**Comment by Droidspirit** [comment]
Oh, I'm so sorry.

I checked it out with a complete new game. The file size of play games is okay. In my game I had changed the compression-format of the sound files for testing (and forgot it to revert) and this is responsible for the file size. 

Also everything is okay with the playgames plugin. It was my fault.

**Comment by danspeedy1** [comment]
Don't worry. We've all been there :)

**Comment by claywilkinson** [comment]
Good to hear you figured it out @Droidspirit and it was easy to fix :+1:
