### ISSUE TITLE
GetServerAuthCode() ERROR: Error loading server auth code: ERROR_INTERNAL

### ISSUE THREAD

**Issue by cmorsucci** [playgameservices/play-games-plugin-for-unity#1003]
I use 0.9.31a version and when i run this code after correct authentication he says: 

> ERROR: Error loading server auth code: ERROR_INTERNAL

`PlayGamesPlatform.Instance.GetServerAuthCode ((authStatus, code) => {
				if (authStatus == CommonStatusCodes.Success) {
					Debug.Log ("authCode: " + code);
				} else {
					Debug.Log ("Error authCode: " + authStatus.ToString () + "Code: " + code);
				}
			});`

**Comment by claywilkinson** [comment]
This could be because the webClientId being passed in is for a an application that is not a web app that is linked to the game configuration on the Play Game Console.  I'd suggest checking that the client id matches (and that it does not have any leading/trailing spaces, etc.)

**Comment by cmorsucci** [comment]
i tried also with an web app linked to the game configuration on the Play Game Console but the result is the same.. :( You have tried to see if it works in your own application?

**Comment by cmorsucci** [comment]
it's working.... 
I think it was a problem connecting with google , now everything works properly , thanks

**Comment by claywilkinson** [comment]
Great! Glad its working and thanks for following up.
