### ISSUE TITLE
PlayGamesPlatform.GetUserEmail is always empty string.

### ISSUE THREAD

**Issue by bobjung** [playgameservices/play-games-plugin-for-unity#1005]
PlayGamesPlatform.Instance.Authenticate is success.
But PlayGamesPlatform.Instance.GetUserEmail is always empty string. (GetToken is empty string too.)

My development env:
 - Unity: 5.3.2f1
 - PlayGames Plugin: 0.9.31a
 - Project: Sample/Minimal
 - Platform: Android

Additional code:

===============
[Minimal/MainGui.cs]
// MainGui.Start()

		PlayGamesClientConfiguration conf = new PlayGamesClientConfiguration.Builder()
				.RequireGooglePlus()
				.Build ();

		GooglePlayGames.PlayGamesPlatform.InitializeInstance (conf);

              // Select the Google Play Games platform as our social platform implementation
             GooglePlayGames.PlayGamesPlatform.Activate();

// Main.OnGui

              Social.localUser.Authenticate((bool success) => {
                    mWaitingForAuth = false;
                    if (success) {
                      mStatusText = "Welcome " + Social.localUser.userName;
                      string token = GooglePlayGames.PlayGamesPlatform.Instance.GetToken();
                      Debug.Log(token);

                      // Test to get user email.
                      string email = GooglePlayGames.PlayGamesPlatform.Instance.GetUserEmail();
                      // Text to print for test
		      mDebugText = "Token: " + token + ", Email: " + email;

                    } else {
                      mStatusText = "Authentication failed.";
                    }
              });

[Plugin/Android/MainLibProj/AndroidManifest.xml] - except "< />"

uses-permission android:name="android.permission.GET_ACCOUNTS"
uses-permission android:name="android.permission.USE_CREDENTIALS"

==================

If it need to call the PlayGamesClientConfiguration.WithPermissionRationale?
If that was how to use this method?

Or any references?

**Comment by claywilkinson** [comment]
can you share the log of when you are getting the email?

**Comment by sorab2142** [comment]
If you put a check in Update() when the email is not empty/null it does show up later (the email and token are fetched asynchronously now, so it takes some time).

**Comment by Agaz5** [comment]
I have the same issue, I get an empty string both for GetUserEmail() and GetAccessToken(). I tried to put them inside Update but they stay empty anyway

**Comment by claywilkinson** [comment]
Is there anything in the log when you call them?

**Comment by Agaz5** [comment]
No I just get empty strings, I tried printing them out both in the log and as a UI text in the app.

**Comment by claywilkinson** [comment]
Can you check logcat?  Are there any errors in the log?

**Comment by Agaz5** [comment]
I just checked on logcat and each time the methods are called it gives an empty string without errors

![code](https://cloud.githubusercontent.com/assets/8259373/13504287/37091fcc-e174-11e5-89bb-1cf12c0ce757.JPG)


![getuseremail](https://cloud.githubusercontent.com/assets/8259373/13504252/057ba790-e174-11e5-950e-72e001fdfc2b.JPG)
![getaccesstoken](https://cloud.githubusercontent.com/assets/8259373/13504257/0caf54d0-e174-11e5-9faa-6fbf7de60e1a.JPG)

**Comment by claywilkinson** [comment]
Can you share the unfiltered log including authenticating?  if there is a problem during authenication, then an empty string will be shown.  The errors are suppressed on the call, so the log does not fill up with an error on every frame.

**Comment by Agaz5** [comment]
I getting authentication problems even if I set up the oauth2 inside the plugin.
![autherror](https://cloud.githubusercontent.com/assets/8259373/13530068/c02fdbd2-e21f-11e5-89c5-6a3e230d0d68.JPG)

and I get as well an error retrieving the token
![token](https://cloud.githubusercontent.com/assets/8259373/13530092/e51a54ea-e21f-11e5-81b5-a5ef42ddac62.JPG)

**Comment by Agaz5** [comment]
I checked logcat as you said and I have fixed some issues, now I can get the authentication code from PlayGamesPlatform.Instance.GetServerAuthCode() but still the GetAccessToken doesn't work and I have this error in the log

![capture](https://cloud.githubusercontent.com/assets/8259373/13533978/2ac92d5a-e233-11e5-9e6c-832d6e931ca6.JPG)

**Comment by bobjung** [comment]
I have the same problem.
PlayGamesPlatform.Instance.GetServerAuthCode() is fine. But PlayGamesPlatform.Instance.GetUserEmail() is always null in Update(). (PlayGamesPlatform.Instance.GetAccessToken() doesn't work too.)

And I send the ServerAuthCode to our backend server. (Ref: https://developers.google.com/identity/sign-in/web/server-side-flow) The server can exchanges ServerAuthCode for AccessToken. But It can't access the email.

I just don't understand what's wrong with me.

**Comment by cmorsucci** [comment]
I have the same issue, the GetUserEmail() return always null.
Also, the token excanged on the server may not return Email if i query UserInfo with google api, there is a problem with scopes in plugin?

**Comment by divad4686** [comment]
I was having the same problem, this is the code that solved it for me. 
`Social.localUser.Authenticate((bool success) => {
			GooglePlayGames.OurUtils.PlayGamesHelperObject.RunOnGameThread(
				() => { 					
					Debug.Log("Local user's email is " + ((PlayGamesLocalUser)Social.localUser).Email);
					
				});
				
		});
`

**Comment by cuixin** [comment]
Have u check the enable option(Google Plus) in Window -> Google Play Games -> Setup -> Android setup

**Comment by Agaz5** [comment]
yes, it is enabled. I tried to put the get token and email in RunOnGameThread as well but still I get empty strings

**Comment by claywilkinson** [comment]
The email address is filled in asynchronously, so in Update() put something like

```
if (my_copy_of_email == null) {
    my_copy_of_email = ((PlayGamesLocalUser)Social.localUser).Email;
}
```

**Comment by lasithalakmal** [comment]
> The email address is filled in asynchronously, so in Update() put something like
> 
> ```
> if (my_copy_of_email == null) {
>     my_copy_of_email = ((PlayGamesLocalUser)Social.localUser).Email;
> }
> ```

It works nicely. thanks man.
