### ISSUE TITLE
Unity keeps deleting the google-play-libs folder in plugins and not working

### ISSUE THREAD

**Issue by 12boulla** [playgameservices/play-games-plugin-for-unity#1006]
I recently installed Unity 5.3.3 on a new computer, and I have set up Google Play Games Services. However, it does not automatically import the google-play-libs folder into assets>plugins>android.

To build successfully, I have to manually import the library and then build, but whenever I close and open Unity again, it keeps getting deleted and I have to continuously import it before every build.

Does anyone know how to fix the issue? I am using the 0.9.31a version of the plugin. One thing to note is that I get the error: Cannot find candidate artifact for com.android.support:appcompat-v7:23.1.0+
I read to fix it I must get the Android Support Repository in the SDK manager, but in mine it is not there, I only have Android Support Library.

Also, signing in with google does not work on the app itself.
I get the following logcat output:

```
I/GamesNativeSDK( 8741): Auth operation started: SIGN IN
I/GamesNativeSDK( 8741): Connecting to Google Play...
E/GamesNativeSDK( 8741): Not authorizing: no client.
I/Unity   ( 8741): AuthState == Unauthenticated calling auth callbacks with fail
ure
I/Unity   ( 8741):
I/Unity   ( 8741): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   ( 8741):
I/Unity   ( 8741): Error sign in
I/Unity   ( 8741):
I/Unity   ( 8741): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   ( 8741):

```
Any help is greatly appreciated, thanks.

**Comment by claywilkinson** [comment]
You'll need to update the Android Support Repository component in the Android SDK Manager to get the updated appcompat library.    We moved away from including the entire google-play-services_lib directory since it makes the application unnecessarily large both in terms of DEX count and just raw bytes.  The plugin now copies in the only the .aar files needed to build.

**Comment by GustJc** [comment]
I got the same problem of not showing Android Support Repository in SDK Manager. ( And breaking the plugin with resolutionException )
But I solved mine error installing `"extra/Local Maven repository for Support Libraries"`.
Maybe they changed the name or added the old repository package to this?

**Comment by 12boulla** [comment]
Well, somehow I managed to fix it. Not really sure how as I tried a lot of things. When I finally opened my game, I had never been so happy to log in with GPGS. Thanks for the help.

**Comment by jurabazz** [comment]
12boulla help me how to fix it

**Comment by 12boulla** [comment]
jurabazz, do you get the same errors as me? I can't help right now but I'll see later. Try creating your own issue so others can help you.

**Comment by jurabazz** [comment]
12boulla, okay

**Comment by claywilkinson** [comment]
OK to close this issue?

**Comment by jurabazz** [comment]
yes

2016-04-06 21:20 GMT+03:00 Clayton Wilkinson <notifications@github.com>:
