### ISSUE TITLE
[IOS] Xcode build failed "Undefined symbols for architecture arm64"

### ISSUE THREAD

**Issue by mrThinBone** [playgameservices/play-games-plugin-for-unity#1007]
I want to use GPGS Leaderboard. I have encountered a lot of error when build iOS project (compiling ok but linking step failed).

image
https://www.dropbox.com/s/kzycrux2rzimuwf/1.png?dl=0

Plugin version: 0.9.31a

**Comment by mrThinBone** [comment]
fixed http://stackoverflow.com/questions/25883153/cant-import-embedded-framework-with-xcode-6-gm

**Comment by claywilkinson** [comment]
Are you still having problems?
This could be that the postprocessing of the pbxproject file did not complete successfully. You can check the Unity console log for this.

Make sure you are:

1. opening the .xcworkspace file.
2. OTHER_LDFLAGS in build settings include $(inherited)
3. HEADER_SEARCH_PATHS in build settings include $(inherited)
4. OTHER_CFLAGS in build settings include $(inherited)
5. ENABLE_BITCODE in build settings is set to NO
6. Libraries/Plugins/iOS/GPGSAppController.mm (or Libraries/GPGSAppController.mm) has compiler flags that include -fobjc-arc
