### ISSUE TITLE
Out of date SSL version in Play Games Plugin

### ISSUE THREAD

**Issue by ryanscottmurphy** [playgameservices/play-games-plugin-for-unity#1008]
Hey guys,

There are instructions on the Internet in various places that discuss checking the version of SSL in your built APK so that you don't conflict with Google's Developer Distribution Agreement. An example of these instructions follows:

> Google Play will block publishing of any new apps and updates that use older, unsupported versions of OpenSSL (see below for details). [...] The vulnerabilities were fixed in OpenSSL versions beginning with 1.0.1h, 1.0.0m, and 0.9.8za. To confirm your OpenSSL version, you can do a grep via:
> 
>`$ unzip -p YourApp.apk | strings | grep "OpenSSL"` [[Source]] (http://stackoverflow.com/questions/30969060/google-play-security-alert-due-to-actionscript-and-openssl)

Following these instructions it's clear that this Play Games Plugin for Unity returns ‘GmsCore_OpenSSL’ from the above grep command and not one of the versions beginning with 1.0.1h, 1.0.0m, and 0.9.8za. 

It definitely appears that this is a problem with the plugin. Can this be fixed or can you please offer an explanation about this?

OpenSSL's documentation about the relevant vulnerability can be found [here] (https://www.openssl.org/news/secadv/20140605.txt).

**Comment by benbritten** [comment]
+1

**Comment by claywilkinson** [comment]
The SSL support is not part of this plugin.  It relies on the play-services client libraries and the native C++ Play Game Services SDK.  If you have questions about SSL, I'd recommend narrowing it down to one of those components and redirect your question to them.
