### ISSUE TITLE
<GoogleSignIn/GIDSignIn.h> added but "GIDSignIn.h file not found" still remain

### ISSUE THREAD

**Issue by mrThinBone** [playgameservices/play-games-plugin-for-unity#1009]
I have experimented all solutions from previous issues but can't solve problem.
Please help!
![error](https://cloud.githubusercontent.com/assets/10541769/13420505/5a2330d6-dfb9-11e5-906e-34e69cb3a047.png)

**Comment by integer222** [comment]
Исправь :) на это и будет тебе счастье

#import <GoogleSignIn/GIDSignIn.h>
#import <GoogleSignIn/GIDGoogleUser.h>
#import <GoogleSignIn/GIDAuthentication.h>
#import <GoogleSignIn/GIDProfileData.h>
#import <gpg/ios_support.h>
#import <gpg/GPGEnums.h>

**Comment by claywilkinson** [comment]
This could be that the postprocessing of the pbxproject file did not complete successfully.  You can check the Unity console log for this.

Make sure you are:

1.  opening the .xcworkspace  file.
2. OTHER_LDFLAGS in build settings include $(inherited)
3. HEADER_SEARCH_PATHS in build settings include $(inherited)
4. OTHER_CFLAGS in build settings include $(inherited)
5. ENABLE_BITCODE in build settings is set to NO
6. Libraries/Plugins/iOS/GPGSAppController.mm (or Libraries/GPGSAppController.mm) has compiler flags that include -fobjc-arc

**Comment by v2k** [comment]
this needs to be a sticky; ran into this again and the checklist fixed it for me.

thanks.

**Comment by v2k** [comment]
This seems to come back every time "append" from the Unity build is no longer an option.   After the checklist failed me, I tried @integer222's fix this time, but got "clang error: unsupported option --ObjC"

**Comment by gnchishti** [comment]
Thanks claywilkinson
your check list worked for me.

**Comment by mochadwi** [comment]
Hello @claywilkinson,

If you don't mind explaining more detail, I'll be much appreciated!

I'm curious about your no. 6 checklist. 

6. Libraries/Plugins/iOS/GPGSAppController.mm (or Libraries/GPGSAppController.mm) has compiler flags that include -fobjc-arc

- Where should I add the flags (-fobjc-arc) actually?
- And, what is actually means (-fobjc-arc)?

Thanks,
