### ISSUE TITLE
Google Play Games Plugin Android Configuration Issue

### ISSUE THREAD

**Issue by over9000bits** [playgameservices/play-games-plugin-for-unity#101]
Hi,

First of all, thanks for developing this great plugin. I am having some problems with the configuration for the Android platform. After setting the bundle Id and the application Id unity says that Google play games plugin have been successfully configured but when I build and run to the mobile I keep getting the following error:

Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details. C:\Program Files\Java\jdk1.8.0\bin\java.exe -Xmx1024M -Dcom.android.sdkmanager.toolsdir="C:/Program Files (x86)/Android/android-sdk\tools" -Dfile.encoding=UTF8 -jar "C:/Program Files (x86)/Unity/Editor/Data/BuildTargetTools/AndroidPlayer\sdktools.jar" -

stderr[

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/cast/Cast$CastApi$a$9;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:685)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:634)
	at com.android.dx.command.dexer.Main.access$600(Main.java:78)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:572)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:596)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:498)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:264)
	at com.android.dx.command.dexer.Main.run(Main.java:230)
	at com.android.dx.command.dexer.Main.main(Main.java:199)
	at com.android.dx.command.Main.main(Main.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at SDKMain.main(SDKMain.java:129)
1 error; aborting
]
stdout[
processing archive bin\classes.jar...
processing com/unity3d/player/a$1.class...
processing com/unity3d/player/a$2.class...
processing com/unity3d/player/a$a.class...
processing com/unity3d/player/a.class...
processing com/unity3d/player/b$1.class...
processing com/unity3d/player/b$2.class...
processing com/unity3d/player/b.class...
processing com/unity3d/player/c.class...
processing com/unity3d/player/d$1.class...
processing com/unity3d/player/d$2.class...
processing com/unity3d/player/d.class...
processing com/unity3d/player/e.class...
processing com/unity3d/player/f.class...
processing com/unity3d/player/g.class...
processing com/unity3d/player/h.class...
processing com/unity3d/player/i.class...
processing com/unity3d/player/j$1.class...
processing com/unity3d/player/j.class...
processing com/unity3d/player/NativeLoader.class...
processing com/unity3d/player/k.class...
processing com/unity3d/player/ReflectionHelper$1.class...
processing com/unity3d/player/ReflectionHelper$a.class...
processing com/unity3d/player/ReflectionHelper.class...
processing com/unity3d/player/l.class...
processing com/unity3d/player/m$1.class...
processing com/unity3d/player/m$2.class...
processing com/unity3d/player/m$3.class...
processing com/unity3d/player/m.class...
processing com/unity3d/player/n.class...
processing com/unity3d/player/o.class...
processing com/unity3d/player/UnityPlayer$1.class...
processing com/unity3d/player/UnityPlayer$2.class...
processing com/unity3d/player/UnityPlayer$4.class...
processing com/unity3d/player/UnityPlayer$5.class...
processing com/unity3d/player/UnityPlayer$6.class...
processing com/unity3d/player/UnityPlayer$7.class...
processing com/unity3d/player/UnityPlayer$8.class...
processing com/unity3d/player/UnityPlayer$9.class...
processing com/unity3d/player/UnityPlayer$10.class...
processing com/unity3d/player/UnityPlayer$11.class...
processing com/unity3d/player/UnityPlayer$12.class...
processing com/unity3d/player/UnityPlayer$13$1.class...
processing com/unity3d/player/UnityPlayer$13.class...
processing com/unity3d/player/UnityPlayer$14.class...
processing com/unity3d/player/UnityPlayer$3.class...
processing com/unity3d/player/UnityPlayer$15.class...
processing com/unity3d/player/UnityPlayer$16.class...
processing com/unity3d/player/UnityPlayer$17.class...
processing com/unity3d/player/UnityPlayer$18.class...
processing com/unity3d/player/UnityPlayer$19.class...
processing com/unity3d/player/UnityPlayer$20.class...
processing com/unity3d/player/UnityPlayer$a.class...
processing com/unity3d/player/UnityPlayer$b.class...
processing com/unity3d/player/UnityPlayer.class...
processing com/unity3d/player/UnityPlayerActivity.class...
processing com/unity3d/player/UnityPlayerNativeActivity.class...
processing com/unity3d/player/UnityPlayerProxyActivity.class...
processing com/unity3d/player/p.class...
processing com/unity3d/player/q$1.class...
processing com/unity3d/player/q.class...
processing com/unity3d/player/WWW.class...
processing org/fmod/FMODAudioDevice$a.class...
processing org/fmod/FMODAudioDevice.class...
processing org/fmod/a.class...
processing bin\classes\.\com\facebook\android\Manifest$permission.class...
processing bin\classes\.\com\facebook\android\Manifest.class...
processing bin\classes\.\com\facebook\android\R$attr.class...
processing bin\classes\.\com\facebook\android\R$color.class...
processing bin\classes\.\com\facebook\android\R$dimen.class...
processing bin\classes\.\com\facebook\android\R$drawable.class...
processing bin\classes\.\com\facebook\android\R$id.class...
processing bin\classes\.\com\facebook\android\R$integer.class...
processing bin\classes\.\com\facebook\android\R$layout.class...
processing bin\classes\.\com\facebook\android\R$string.class...
processing bin\classes\.\com\facebook\android\R$style.class...
processing bin\classes\.\com\facebook\android\R$styleable.class...
processing bin\classes\.\com\facebook\android\R.class...
processing bin\classes\.\com\google\android\gms\Manifest$permission.class...
processing bin\classes\.\com\google\android\gms\Manifest.class...
processing bin\classes\.\com\google\android\gms\R$attr.class...
processing bin\classes\.\com\google\android\gms\R$color.class...
processing bin\classes\.\com\google\android\gms\R$dimen.class...
processing bin\classes\.\com\google\android\gms\R$drawable.class...
processing bin\classes\.\com\google\android\gms\R$id.class...
processing bin\classes\.\com\google\android\gms\R$integer.class...
processing bin\classes\.\com\google\android\gms\R$layout.class...
processing bin\classes\.\com\google\android\gms\R$string.class...
processing bin\classes\.\com\google\android\gms\R$style.class...
processing bin\classes\.\com\google\android\gms\R$styleable.class...
processing bin\classes\.\com\google\android\gms\R.class...
processing bin\classes\.\com\google\example\games\basegameutils\Manifest$permission.class...
processing bin\classes\.\com\google\example\games\basegameutils\Manifest.class...
processing bin\classes\.\com\google\example\games\basegameutils\R$attr.class...
processing bin\classes\.\com\google\example\games\basegameutils\R$color.class...
processing bin\classes\.\com\google\example\games\basegameutils\R$dimen.class...
processing bin\classes\.\com\google\example\games\basegameutils\R$drawable.class...
processing bin\classes\.\com\google\example\games\basegameutils\R$id.class...
processing bin\classes\.\com\google\example\games\basegameutils\R$integer.class...
processing bin\classes\.\com\google\example\games\basegameutils\R$layout.class...
processing bin\classes\.\com\google\example\games\basegameutils\R$string.class...
processing bin\classes\.\com\google\example\games\basegameutils\R$style.class...
processing bin\classes\.\com\google\example\games\basegameutils\R$styleable.class...
processing bin\classes\.\com\google\example\games\basegameutils\R.class...
processing bin\classes\.\com\google\example\games\mainlibproj\Manifest$permission.class...
processing bin\classes\.\com\google\example\games\mainlibproj\Manifest.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$attr.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$color.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$dimen.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$drawable.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$id.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$integer.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$layout.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$string.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$style.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$styleable.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R.class...
processing bin\classes\.\com\thumbstar\SmashITAdventures\Manifest$permission.class...
processing bin\classes\.\com\thumbstar\SmashITAdventures\Manifest.class...
processing bin\classes\.\com\thumbstar\SmashITAdventures\R$attr.class...
processing bin\classes\.\com\thumbstar\SmashITAdventures\R$color.class...
processing bin\classes\.\com\thumbstar\SmashITAdventures\R$dimen.class...
processing bin\classes\.\com\thumbstar\SmashITAdventures\R$drawable.class...
processing bin\classes\.\com\thumbstar\SmashITAdventures\R$id.class...
processing bin\classes\.\com\thumbstar\SmashITAdventures\R$integer.class...
processing bin\classes\.\com\thumbstar\SmashITAdventures\R$layout.class...
processing bin\classes\.\com\thumbstar\SmashITAdventures\R$string.class...
processing bin\classes\.\com\thumbstar\SmashITAdventures\R$style.class...
processing bin\classes\.\com\thumbstar\SmashITAdventures\R$styleable.class...
processing bin\classes\.\com\thumbstar\SmashITAdventures\R.class...
processing archive plugins\.\adcolony.jar...
ignored resource META-INF/MANIFEST.MF
processing com/jirbo/adcolony/ADC$EndCardFinished.class...
processing com/jirbo/adcolony/ADC$V4VCResultsHandler.class...
processing com/jirbo/adcolony/ADC.class...
processing com/jirbo/adcolony/ADCAdManager$1.class...
processing com/jirbo/adcolony/ADCAdManager.class...
processing com/jirbo/adcolony/ADCConfiguration.class...
processing com/jirbo/adcolony/ADCController$1.class...
processing com/jirbo/adcolony/ADCController$2.class...
processing com/jirbo/adcolony/ADCController$3.class...
processing com/jirbo/adcolony/ADCController$4.class...
processing com/jirbo/adcolony/ADCController$5.class...
processing com/jirbo/adcolony/ADCController$6.class...
processing com/jirbo/adcolony/ADCController$7.class...
processing com/jirbo/adcolony/ADCController$8.class...
processing com/jirbo/adcolony/ADCController.class...
processing com/jirbo/adcolony/ADCCustomVideoView$1.class...
processing com/jirbo/adcolony/ADCCustomVideoView$2.class...
processing com/jirbo/adcolony/ADCCustomVideoView$3.class...
processing com/jirbo/adcolony/ADCCustomVideoView$4$1.class...
processing com/jirbo/adcolony/ADCCustomVideoView$4.class...
processing com/jirbo/adcolony/ADCCustomVideoView$5.class...
processing com/jirbo/adcolony/ADCCustomVideoView$6.class...
processing com/jirbo/adcolony/ADCCustomVideoView.class...
processing com/jirbo/adcolony/ADCData$FalseValue.class...
processing com/jirbo/adcolony/ADCData$IntegerValue.class...
processing com/jirbo/adcolony/ADCData$List.class...
processing com/jirbo/adcolony/ADCData$NullValue.class...
processing com/jirbo/adcolony/ADCData$RealValue.class...
processing com/jirbo/adcolony/ADCData$StringValue.class...
processing com/jirbo/adcolony/ADCData$Table.class...
processing com/jirbo/adcolony/ADCData$TrueValue.class...
processing com/jirbo/adcolony/ADCData$Value.class...
processing com/jirbo/adcolony/ADCData.class...
processing com/jirbo/adcolony/ADCDataFile.class...
processing com/jirbo/adcolony/ADCDevice.class...
processing com/jirbo/adcolony/ADCDialog.class...
processing com/jirbo/adcolony/ADCDir.class...
processing com/jirbo/adcolony/ADCDownload$1.class...
processing com/jirbo/adcolony/ADCDownload$DefaultTrustManager.class...
processing com/jirbo/adcolony/ADCDownload$Listener.class...
processing com/jirbo/adcolony/ADCDownload.class...
processing com/jirbo/adcolony/ADCEvent.class...
processing com/jirbo/adcolony/ADCImage.class...
processing com/jirbo/adcolony/ADCJSON.class...
processing com/jirbo/adcolony/ADCLog.class...
processing com/jirbo/adcolony/ADCMRAIDHandler$1.class...
processing com/jirbo/adcolony/ADCMRAIDHandler.class...
processing com/jirbo/adcolony/ADCManifest$Ad.class...
processing com/jirbo/adcolony/ADCManifest$AdTracking.class...
processing com/jirbo/adcolony/ADCManifest$AdV4VC.class...
processing com/jirbo/adcolony/ADCManifest$Ads.class...
processing com/jirbo/adcolony/ADCManifest$App.class...
processing com/jirbo/adcolony/ADCManifest$AppTracking.class...
processing com/jirbo/adcolony/ADCManifest$ButtonInfo.class...
processing com/jirbo/adcolony/ADCManifest$CompanionAd.class...
processing com/jirbo/adcolony/ADCManifest$HTML5CompanionAdInfo.class...
processing com/jirbo/adcolony/ADCManifest$ImageInfo.class...
processing com/jirbo/adcolony/ADCManifest$InAppBrowser.class...
processing com/jirbo/adcolony/ADCManifest$Limits.class...
processing com/jirbo/adcolony/ADCManifest$MRAIDJS.class...
processing com/jirbo/adcolony/ADCManifest$PostPopupDialogInfo.class...
processing com/jirbo/adcolony/ADCManifest$PostPopupInfo.class...
processing com/jirbo/adcolony/ADCManifest$PrePopupDialogInfo.class...
processing com/jirbo/adcolony/ADCManifest$PrePopupInfo.class...
processing com/jirbo/adcolony/ADCManifest$StaticCompanionAdInfo.class...
processing com/jirbo/adcolony/ADCManifest$ThirdPartyAppTracking.class...
processing com/jirbo/adcolony/ADCManifest$ThirdPartyTracking.class...
processing com/jirbo/adcolony/ADCManifest$V4VCLimits.class...
processing com/jirbo/adcolony/ADCManifest$Video.class...
processing com/jirbo/adcolony/ADCManifest$Zone.class...
processing com/jirbo/adcolony/ADCManifest$ZoneTracking.class...
processing com/jirbo/adcolony/ADCManifest$ZoneV4VC.class...
processing com/jirbo/adcolony/ADCManifest$Zones.class...
processing com/jirbo/adcolony/ADCManifest.class...
processing com/jirbo/adcolony/ADCMediaManager$Asset.class...
processing com/jirbo/adcolony/ADCMediaManager.class...
processing com/jirbo/adcolony/ADCMonitor$Pinger.class...
processing com/jirbo/adcolony/ADCMonitor.class...
processing com/jirbo/adcolony/ADCNetwork.class...
processing com/jirbo/adcolony/ADCParseReader.class...
processing com/jirbo/adcolony/ADCPlayHistory$PlayEvent.class...
processing com/jirbo/adcolony/ADCPlayHistory.class...
processing com/jirbo/adcolony/ADCReportingManager$Event.class...
processing com/jirbo/adcolony/ADCReportingManager.class...
processing com/jirbo/adcolony/ADCSessionManager.class...
processing com/jirbo/adcolony/ADCSkipVideoDialog.class...
processing com/jirbo/adcolony/ADCStorage.class...
processing com/jirbo/adcolony/ADCStreamReader.class...
processing com/jirbo/adcolony/ADCStreamWriter.class...
processing com/jirbo/adcolony/ADCStringBuilder.class...
processing com/jirbo/adcolony/ADCThreadPool$ReusableThread.class...
processing com/jirbo/adcolony/ADCThreadPool.class...
processing com/jirbo/adcolony/ADCUtil$Stopwatch.class...
processing com/jirbo/adcolony/ADCUtil$Timer.class...
processing com/jirbo/adcolony/ADCUtil.class...
processing com/jirbo/adcolony/ADCV4VCConfirmationDialog.class...
processing com/jirbo/adcolony/ADCV4VCResultsDialog.class...
processing com/jirbo/adcolony/ADCVideo$1.class...
processing com/jirbo/adcolony/ADCVideo$2.class...
processing com/jirbo/adcolony/ADCVideo$3.class...
processing com/jirbo/adcolony/ADCVideo$LoadingView.class...
processing com/jirbo/adcolony/ADCVideo.class...
processing com/jirbo/adcolony/ADCVideoHUD$1.class...
processing com/jirbo/adcolony/ADCVideoHUD$1JsObject.class...
processing com/jirbo/adcolony/ADCVideoHUD$2.class...
processing com/jirbo/adcolony/ADCVideoHUD$3.class...
processing com/jirbo/adcolony/ADCVideoHUD$4.class...
processing com/jirbo/adcolony/ADCVideoHUD$5.class...
processing com/jirbo/adcolony/ADCVideoHUD$6.class...
processing com/jirbo/adcolony/ADCVideoHUD$7.class...
processing com/jirbo/adcolony/ADCVideoHUD$8.class...
processing com/jirbo/adcolony/ADCVideoHUD$9.class  

I tried moving this line (<meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="false" />) from the AndroidManifest.xml file inside this block with the value true:

<activity android:name="com.unity3d.player.UnityPlayerProxyActivity" android:launchMode="singleTask" android:label="@string/app_name" android:screenOrientation="sensorPortrait" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
<meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />
    </activity>

as I saw in some forum and didn't work. I also tried one "solution" for the ouya platform, I know I am building for Android.., that was commenting this line android.library=true  of the file  ...\Assets\Plugins\Android\facebook\project.properties as I saw here http://forums.ouya.tv/discussion/2926/unable-to-convert-classes-into-dex-format but it also didn't work. I also checked the sdk versions of the AndroidManifest file (	<uses-sdk android:minSdkVersion="10" android:targetSdkVersion="19" />) and its ok..

I don't know what else can I check to solve this problem and I really wanted to use this plugin of play game services for Unity. I am using Visual Studio.

Hope you can help me. Thanks

**Comment by claywilkinson** [comment]
@over9000bits  - I am closing this issue because the plugin was re-architected and your callstack is obsolete.  Can you re-open this issue if you are having the same issue with the latest version of the plugin.  Thanks!
