### ISSUE TITLE
Jar Resolver is failing with Android Support Library 23.2

### ISSUE THREAD

**Issue by RodGreen** [playgameservices/play-games-plugin-for-unity#1010]
Latest version of Android SDK is downloading Android Support Library 23.2 - which doesn't seem to be found by the Jar Resolver.

Specifically it seems the "23.1.0+" version string isn't working. I'm also not able to find 23.1.0 extra package to download in the meantime.

I've tried removing / re downloading 'Android Support Library', 'Google Play Services', 'Google Repository' in SDK manager, didn't seem to help.

`ResolutionException: Cannot find candidate artifact for com.android.support:support-v4:23.1.0+
Google.JarResolver.PlayServicesSupport.LoadDependencies (Boolean allClients)
Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest)
GooglePlayServices.ResolverVer1_1.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation) (at Assets/PlayServicesResolver/Editor/ResolverVer1_1.cs:59)
GooglePlayServices.PlayServicesResolver.MenuResolve () (at Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:145)`

**Comment by RodGreen** [comment]
I found the problem it seems the name for 'Android Support Repository' has changed to 'Local Maven repository for Support Libraries'.

Seems this is required to be installed before resolution will succeed with the new SDK.

**Comment by claywilkinson** [comment]
Updated the readme.  Thanks again for the suggestion.
