### ISSUE TITLE
Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.

### ISSUE THREAD

**Issue by jurabazz** [playgameservices/play-games-plugin-for-unity#1011]
Hello, how to fix it? The problem SDK or plugin or androidManifest?

Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
E:\Android\SDK\build-tools\23.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "E:/Android/SDK\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages com.google.example.games.mainlibproj

stderr[
AndroidManifest.xml:18: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

]

**Comment by claywilkinson** [comment]
What version of Unity and the plugin are you using? You can try to run Windows > Google Play Games > Setup > Android Setup... again which should copy over the client libraries you need.

 google_play_services_version is defined in play-services-basement-8.4.aar - which should be in Assets/Plugins/Android.

**Comment by bar2016** [comment]
Had this problem , for some reason its removes the lib folder,
try to get into sdk folder then>extras>google>google_play_services>libproject
there you will find a folder called "google-play-services_lib" copy it and paste in Assets/Plugins/Android
then try to build.

**Comment by panpanick** [comment]
I'm also having this problem but there isn't `libproject` folder in my `google_play_services`. There is only a `docs` and a `samples` folder. What do I do?

**Comment by bar2016** [comment]
Well, Get into SDK manager and check if it installed properly, look for Extras and then look for Google Play services, check if you have installed it , and try to update it if you can.
