### ISSUE TITLE
Can no longer log in to game after upgrading to Unity 5.3.1 and plugin 0.9.31a

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#1013]
Have spent some hours now Googling with no luck. However I have fount what I think must be the problem: Shouldnt it be gpg 8.4 instead of 8.3 in those files below!? ...and how did they end up there? The plugin doesnt put any files there...

![dsfsdfdffd](https://cloud.githubusercontent.com/assets/10234700/13431749/f11928ae-dfca-11e5-9838-37569bacdc7b.jpg)

Logcat:

I/Unity   (27982):  [Play Games Plugin DLL] 03/01/16 11:21:57 +01:00 DEBUG: Crea
ting Android IPlayGamesClient Client
I/Unity   (27982):
I/Unity   (27982): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (27982):
D/GamesUnitySDK(27982): Performing Android initialization of the GPG SDK
E/GamesNativeSDK(27982): Can't register class com/google/android/gms/games/Games
$GetServerAuthCodeResult: an exception occurred.
I/Unity   (27982): Building GPG services, implicitly attempts silent auth
I/Unity   (27982):
I/Unity   (27982): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (27982):
E/GamesNativeSDK(27982): Could not register one or more required Java classes.
I/Unity   (27982): InvalidOperationException: There was an error creating a Game
Services object. Check for log errors from GamesNativeSDK
I/Unity   (27982):   at GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build
 (GooglePlayGames.Native.PInvoke.PlatformConfiguration configRef) [0x00000] in <
filename unknown>:0
I/Unity   (27982):   at GooglePlayGames.Native.NativeClient.InitializeGameServic
es () [0x00000] in <filename unknown>:0
I/Unity   (27982):   at GooglePlayGames.Native.NativeClient.Authenticate (System
.Action`1 callback, Boolean silent) [0x00000] in <filename unknown>:0

**Comment by claywilkinson** [comment]
Yes, Can't register class com/google/android/gms/games/Games
$GetServerAuthCodeResult: an exception occurred. is caused by not having 8.4.

The file Assets/GooglePlayGames/PluginVersion.cs has the version of the libraries to use. 

The are copied into the project by the plugin automatically.  I'd try to verify the version in the PluginVersion.cs file, then delete the 8.3 files - if everything works as expected, the 8.4 version should show up (presuming you have updated the Google Repository component in the Android SDK manager.

**Comment by Hoffa25** [comment]
Ok good, that means Im on the right track:)! Deleting those files resulted in a build fail. Any ideas?

CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Program Files (x86)/Android/android-sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.facebook:com.facebook.android:com.google.example.games.mainlibproj:com.soomla.SoomlaApp:android.support.v4:com.Testcompany.test5 -S "C:\innanadmob2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res" -S "C:\innanadmob2\Temp\StagingArea\android-libraries\facebook-android-sdk-4.7.0\res" -S "C:\innanadmob2\Temp\StagingArea\android-libraries\facebook-android-wrapper-release\res" -S "C:\innanadmob2\Temp\StagingArea\android-libraries\support-v4-23.1.1\res" -S "C:\innanadmob2\Temp\StagingArea\android-libraries\unity-android-resources\res"

stderr[
C:\innanadmob2\Temp\StagingArea\android-libraries\unity-android-resources\res\drawable\tw_widget_progressbar_holo_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
C:\innanadmob2\Temp\StagingArea\android-libraries\unity-android-resources\res\drawable-mdpi\tw_widget_progressbar_holo_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
C:\innanadmob2\Temp\StagingArea\android-libraries\unity-android-resources\res\drawable-hdpi\tw_widget_progressbar_holo_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
C:\innanadmob2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.widget.ActionBarContainer>
C:\innanadmob2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource com.xxxx.xxxxxx:layout/abc_screen_toolbar for configuration v21.
AndroidManifest.xml:20: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

**Comment by claywilkinson** [comment]
Here is what I have:
<img width="638" alt="screen shot 2016-02-25 at 12 10 31 pm" src="https://cloud.githubusercontent.com/assets/8752378/13468348/0a1514d0-e057-11e5-9c18-eb8bda16f3ba.png">

Could you have some old/duplicate resources in Assets/Plugins/Android/res or in some of the other plugins?

You might need to use process of elimination to figure out what's going on.

**Comment by Hoffa25** [comment]
Solved! I had some weird old stuff in the /res folder messing things up. Thanks again Clay!!

**Comment by claywilkinson** [comment]
Glad to hear it is solved!

**Comment by Hoffa25** [comment]
Sigh.... The build works fine and I get logged in but I keep getting this error message:

NotImplementedException: You must enable saved games before i
t can be used. See PlayGamesClientConfiguration.Builder.EnableSavedGames.

Seems very strange since I havnt touched any code realating to this in a year...
