### ISSUE TITLE
Problems import 0.9.31a to clean project

### ISSUE THREAD

**Issue by 11Sheep** [playgameservices/play-games-plugin-for-unity#1016]
Hi All,

Downloaded the new package (0.9.31a) to a new android unity project, updated the Android SDK to the latest version (google play services, build tools, google repository, etc...) and still get this message in the console:

(My Unity version is 5.3.2f1)

Google.JarResolver.ResolutionException: Cannot find candidate artifact for com.android.support:support-v4:23.1.0+
  at Google.JarResolver.PlayServicesSupport.DependOn (System.String group, System.String artifact, System.String version) [0x00000] in <filename unknown>:0 
  at GooglePlayGames.Editor.GPGSDependencies..cctor () [0x00063] in C:\Users\lior\Documents\UnityProjects\GPTest\Assets\GooglePlayGames\Editor\GPGSDependencies.cs:61 
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

Any idea why?

**Comment by RodGreen** [comment]
I had this issue and it's currently flagged as a bug #1010.

Solution is to make sure to get the 'Local Maven repository for Support Libraries' package in the Android SDK manager.

> To configure your Unity game to run with Google Play Games on Android, first open the Android SDK manager and verify that you have downloaded the following required packages:
> 
> * **Google Play Services**
> * **Android Support Library**
> * **Local Maven repository for Support Libraries**
> 
> The Android SDK manager is usually available in your SDK installation directory, under the "tools" subdirectory, and is called android (or android.bat on Windows). The 'Google Play Services', 'Android Support Library' and 'Local Maven repository for Support Libraries' packages are available under the Extras folder. If any are not installed or are out of date, install or update it before proceeding.

**Comment by 11Sheep** [comment]
Yap, I downloaded the "Local Maven repository for Support Libraries" and that solved it.

Thanks a lot Rod!
