### ISSUE TITLE
Dont known if im being stupid and missing something.

### ISSUE THREAD

**Issue by andrewchumchal** [playgameservices/play-games-plugin-for-unity#1017]
After I import the current build. I do not see the google play games button. Can any one help??

**Comment by claywilkinson** [comment]
It should be under the Window menu item.  It will only show up if you have the platform set to iOS or Android.  This is set under File > Build Settings...

**Comment by andyipod1437** [comment]
so it is only in the Windows menu item. not by it self any more??

**Comment by claywilkinson** [comment]
Correct - Having the top level menu item violated Unity's best practices for a plugin.

**Comment by andyipod1437** [comment]
oh okay because i was looking at this 

> To install the plugin, simply open your game project in Unity and import that file into your project's assets, as you would any other Unity package. This is accomplished through the Assets | Import Package | Custom Package menu item (you can also reach this menu it by right-clicking the Assets folder). After importing, you should see that a new menu item was added to the Window menu: "Google Play Games". If you don't see the new menu items, refresh the assets by clicking Assets | Refresh and try again. from the ReadMe

How would you set it up then? Is there a newer video about it ?

**Comment by claywilkinson** [comment]
No video yet - The [README.MD](https://github.com/playgameservices/play-games-plugin-for-unity) is the best source.  Please as questions if you have problems following the instructions.

**Comment by andyipod1437** [comment]
The ReadME.MD dose not do any good

**Comment by claywilkinson** [comment]
Do you have a specific question?

**Comment by andyipod1437** [comment]
Im really stuck at setting it up. I have read the read me. like 10 time and create projects for it and still not working

**Comment by claywilkinson** [comment]
Closing since it has been a long time.
