### ISSUE TITLE
Jenkins build issue on iOS with NO_GPGS (GPGSPostBuild)

### ISSUE THREAD

**Issue by ktae13** [playgameservices/play-games-plugin-for-unity#1018]
"#if" statement is not working with command line build using Jenkins.

I had to modify GPGSPostBuild class to make OnPostprocessBuild function run in ugly way.

I wonder if anybody had same issue and if there's any better way to fix it.

Thank you.

**Comment by claywilkinson** [comment]
The easiest was I have found is to drop a static class into Assets/Editor during building.  In there have a static method that sets the properties and kicks off the actual build within Unity, passing options in on the command line to Unity.
```
public class BuildAutomation                                                    
{                                                                                                                                     
    static void PerformIOSBuild()                                               
    {                                                                           
        Debug.Log("Performing Automated ios build...");     
   
        // set NO_GPGS
        PlayerSettings.SetScriptingDefineSymbolsForGroup(BuildTargetGroup.iOS, "NO_GPGS");
        
        // set other properties, initialized from the command line
        if (!string.IsNullOrEmpty(bundleId)) {                                                                       
            PlayerSettings.bundleIdentifier = bundleId;                         
        }                                                                        
        PlayerSettings.bundleVersion = versionName;                             
        if (useSimulatorSDK)  {                                                                       
            PlayerSettings.iOS.sdkVersion = iOSSdkVersion.SimulatorSDK;         
        }                                                                       
       
        // finally kick off the build process.                                                                         
        #if UNITY_4_6                                                                   
            BuildPipeline.BuildPlayer(scenes.ToArray(), "xcode",                    
                BuildTarget.iPhone, BuildOptions.None);                             
        #else                                                                           
            BuildPipeline.BuildPlayer(scenes.ToArray(), "xcode",                    
                BuildTarget.iOS, BuildOptions.None);                                
        #endif
}
```
Then invoke this from the command line

`${unity_exe} -buildTarget iOS -batchmode -projectPath ${projectSrc} -executeMethod BuildAutomation.PerformIOSBuild -quit`

where unity_exe is the path to the Unity executable, and projectSrc is the path to the Unity project to build.

**Comment by claywilkinson** [comment]
OK to close this one?

**Comment by badawe** [comment]
I'm having the same issue too, anyone else, have any other solutions then changing Jenkins?

**Comment by claywilkinson** [comment]
The new version of the plugin (0.9.35) integrates the required frameworks into the xcode project, so the xcworkspace is no longer needed.

**Comment by DreamKnightKr** [comment]
Please update 'README.md' that is still for old version.

**(Quotation)**
**Building for iOS**
...
To open and build the project open a terminal window in the project directory, and type open Unity-iPhone.xcworkspace. Alternatively, you can double click the file in Finder.
