### ISSUE TITLE
Quests - Claiming reward occurs crash in unity 4.6.9

### ISSUE THREAD

**Issue by Otd2** [playgameservices/play-games-plugin-for-unity#1019]
Hi,
I am trying to use the quest functionalities of newest google play services plugin (v.0.9.31a) in unity 4.6.9 on Android. Everything is fine with authentication , leaderboard and viewing default quest UI, but when I try to accept a quest or claim a reward game crashes or close the quest window.

I suppose that something wrong occurs when quest callback events triggered. But I couldn't find out what is wrong. 

> I/Unity   (11512): UserRequestsMilestoneClaiming
> I/Unity   (11512):  
> I/Unity   (11512): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
> I/Unity   (11512): 
> W/google-breakpad(11512): ### ### ### ### ### ### ### ### ### ### ### ### ###
> W/google-breakpad(11512): Chrome build fingerprint:
> W/google-breakpad(11512): 4.0
> W/google-breakpad(11512): 13
> W/google-breakpad(11512): 6d6f4589-33a4-4709-9279-1a8b5e855d5c
> W/google-breakpad(11512): ### ### ### ### ### ### ### ### ### ### ### ### ###
> W/InputDispatcher(  721): channel '26cdb719 com.bundleID.example/com.unity3d.player.UnityPlayerProxyActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
> D/ConnectivityService(  721): ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=247, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ], android.os.BinderProxy@14cf537a)
> E/InputDispatcher(  721): channel '26cdb719 com.bundleID.example/com.unity3d.player.UnityPlayerProxyActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
> W/InputDispatcher(  721): channel '3e3c1178 com.bundleID.example/com.unity3d.player.UnityPlayerNativeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
> E/InputDispatcher(  721): channel '3e3c1178 com.bundleID.example/com.unity3d.player.UnityPlayerNativeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
> D/ConnectivityService(  721): releasing NetworkRequest NetworkRequest [ id=247, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
> I/WindowState(  721): WIN DEATH: Window{26cdb719 u0 com.bundleID.example/com.unity3d.player.UnityPlayerProxyActivity}
> W/InputDispatcher(  721): Attempted to unregister already unregistered input channel '26cdb719 com.bundleID.example/com.unity3d.player.UnityPlayerProxyActivity (server)'
> E/ConnectivityService(  721): RemoteException caught trying to send a callback msg for NetworkRequest [ id=247, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
> I/WindowState(  721): WIN DEATH: Window{3e3c1178 u0 com.bundleID.example/com.unity3d.player.UnityPlayerNativeActivity}
> W/InputDispatcher(  721): Attempted to unregister already unregistered input channel '3e3c1178 com.bundleID.example/com.unity3d.player.UnityPlayerNativeActivity (server)'
> W/WindowManager(  721): Force-removing child win Window{3af170b6 u0 SurfaceView} from container Window{3e3c1178 u0 com.bundleID.example/com.unity3d.player.UnityPlayerNativeActivity}
> W/WindowManager(  721): Failed looking up window
> W/WindowManager(  721): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@7b63051 does not exist
> W/WindowManager(  721):   at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8539)
> W/WindowManager(  721):   at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8530)
> W/WindowManager(  721):   at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1142)
> W/WindowManager(  721):   at android.os.BinderProxy.sendDeathNotice(Binder.java:551)
> I/WindowState(  721): WIN DEATH: null
> E/libprocessgroup(  721): failed to kill 1 processes for processgroup 11512
> I/ActivityManager(  721): Process com.bundleID.example (pid 11512) has died
### **Edit:**

I have just seen a new kind of error log in adb logs when accepting a quest. Added below : 

```
W/AppOps  (  721): Bad call: specified package com.google.android.play.games under uid 10107 but it is really 10066
W/AppOps  (  721): Bad call: specified package com.google.android.play.games under uid 10107 but it is really 10066
W/Unity   (22092): *** [Play Games Plugin DLL] 03/03/16 14:23:47 +02:00 ERROR: Error encountered executing QuestManager#QuestUICallback. Smothering to avoid passing exception into Native: System.NullReferenceException: Object reference not set to an instance of an object
W/Unity   (22092):   at GooglePlayGames.Native.NativeQuestClient+<FromQuestUICallback>c__AnonStorey4B.<>m__4B (GooglePlayGames.Native.PInvoke.QuestUIResponse response) [0x00000] in <filename unknown>:0 
W/Unity   (22092):   at GooglePlayGames.Native.PInvoke.Callbacks+<ToIntPtr>c__AnonStorey85`1[GooglePlayGames.Native.PInvoke.QuestManager+QuestUIResponse].<>m__A8 (IntPtr result) [0x00000] in <filename unknown>:0 
W/Unity   (22092):   at GooglePlayGames.Native.PInvoke.Callbacks.PerformInternalCallback (System.String callbackName, Type callbackType, IntPtr response, IntPtr userData) [0x00000] in <filename unknown>:0 
W/Unity   (22092):  
W/Unity   (22092): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
W/Unity   (22092): 
I/Unity   (22092):  [Play Games Plugin DLL] 03/03/16 14:23:47 +02:00 DEBUG: Entering internal callback for QuestManager#AcceptCallback
I/Unity   (22092):  
I/Unity   (22092): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   (22092): 
W/art     (22092): 0x9937ab40
W/art     (22092): 0x9937ab50
W/art     (22092): 0x9937ab10
W/art     (22092): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[43,tid=22622,Native,Thread*=0x8e2d1c00,peer=0x12da40a0,"main_dispatch"]
V/GamesNativeSDK(22092): Detaching from JVM on thread main_dispatch
E/WifiStateMachine(  721): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0,00 rxSuccessRate=0,00 targetRoamBSSID=f4:f2:6d:e0:c9:72 RSSI=-69
E/WifiStateMachine(  721): WifiStateMachine starting scan for "BLINE_TT_Extended"WPA_PSK with 2442
I/ClearcutLoggerApiImpl( 9469): disconnect managed GoogleApiClient
```
## Update :

This problem is not occur on my samsung note 2 phone which has android 4.4.2 but "sometimes" it still happens on Google Nexus 5 (android 5.1.1). I am trying to figure out what the hell is triggering the crash but couldn't find out. So please, I need help.. :(

**Comment by crunchbury** [comment]
Bumping this old post because I'm seeing the same issues. Anyone know what might be going on? When I claim a quest reward, I get these same errors. No crash but the issues in the log are identical to the above.

**Comment by claywilkinson** [comment]
Unfortunately, Quests have been deprecated: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
