### ISSUE TITLE
IOS, GPG, Category 5, Part 2 of the U.S. Export Administration Regulations?

### ISSUE THREAD

**Issue by tagcode** [playgameservices/play-games-plugin-for-unity#102]
"Does your app qualify for any of the exemptions provided in Category 5, Part 2 of the U.S. Export Administration Regulations?
Make sure that your app meets the criteria of the exemption listed here. You are responsible for the proper classification of your product. Incorrectly classifying your app may lead to you being in violation of U.S. export laws and could make you subject to penalties, including your app being removed from the App Store. Read the FAQ thoroughly before answering the questions.
You can select Yes for question #2 if the encryption of your app is:
(a) Specially designed for medical end-use
(b) Limited to intellectual property and copyright protection
(c) Limited to authentication, digital signature, or the decryption of data or files
(d) Specially designed and limited for banking use or "money transactions"; or
(e) Limited to "fixed" data compression or coding techniques
You can also select Yes if your app meets the descriptions provided in Note 4 for Category 5, Part 2 of the U.S. Export Administration Regulations."

What goes on under the bonnet? Does GPG use excryption for data transfers? (And, does IOS IAP use?)

**Comment by zelenko** [comment]
So you can select Yes for the question if ALL of options A-E are true, or if ONE of the options A-E is true?
