### ISSUE TITLE
Error : Attempted to update a stale version of the match

### ISSUE THREAD

**Issue by melayerjohn** [playgameservices/play-games-plugin-for-unity#1022]
i updated my plugin and trying my game.
Now it is not working on Leave call. Previously it was working.I found one warning  ->[Play Games Plugin DLL]  ERROR: Attempted to update a stale version of the match. Expected version was 5 but current version is 6.

How to or what should i do to manage match versions.

Thanks inadvance

**Comment by v2k** [comment]
+1

**Comment by v2k** [comment]
for me, this ended up being a case of not changing/updating the correct TurnBasedMatch object after receiving a OnMatchUpdated event

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
