### ISSUE TITLE
Temperary can't send message to each others after created a quick game(RTMP)

### ISSUE THREAD

**Issue by 61015ian** [playgameservices/play-games-plugin-for-unity#1023]
About 5 hours ago when I tried to start a real-time game using quick match, I found out that players can't send message to each others after a game is started(after OnRoomConnected called), however if I start the game using Invitation, it start working and the players are able to send message to each others. I thought there might be some bugs in my codes and spent almost 5 hours try to figure out what's going wrong. When I almost give up, it work again. I built a new .apk file using the projects I backed up 5 hours ago, and it work fine just as usual. 
Just feeling.....weird.
Is this normal?  Anyone have any idea about what might going wrong?

**Comment by simsis3d** [comment]
Welcome to RTMP world of Google. That is certainly normal if you are using GPGS. My game is even on the market. When I put it on market, everything was working well and believe me I tested it days and days. Nowadays, I take lots of mails from players saying we are not able to play Online Matches.

**Comment by aditya2** [comment]
@simsis3d sir can you pls tell me how to accept the invitation from notification bar ... you can get better understanding of my problem along with the code here #1021 ... i just want that when a user accepts an invitation from notification bar then my app should launch and auto accept that invitation

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
