### ISSUE TITLE
Unable to load library libgpg.so, native render plugin support disabled

### ISSUE THREAD

**Issue by artakino** [playgameservices/play-games-plugin-for-unity#1025]
Hello,
When connecting to Google Play Services I get a bunch of the following error messages in the log:

`D/Unity   (30965): Unable to load library '/data/app/bundleFolderName/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/bundleFolderName/lib/x86/libgpg.so" already opened by ClassLoader 0x12c8a0a0; can't open in ClassLoader 0x0`

I'm using Unity 4.7.0f1, plugin ver 0.9.31a.  What does this really mean and how can I fix it?

**Comment by claywilkinson** [comment]
What device are you running on and which version of Android?  Can you share more of the log?

**Comment by artakino** [comment]
For testing on Nextbook Ares 8 (model no. NXA8QC116) with Android 5.0.
Here is more of the log:
`D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 7416): 
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 7416): 
D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Populating User: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Populating User
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 7416): 
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Found User: [Player: 'Bobby Chin' (id 109949316842001553793)]: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Found User: [Player: 'Bobby Chin' (id 109949316842001553793)]
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 7416): 
D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Maybe finish for User: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Maybe finish for User
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 7416): 
D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Auth not finished. User=[Player: 'Bobby Chin' (id 109949316842001553793)] achievements=: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Auth not finished. User=[Player: 'Bobby Chin' (id 109949316842001553793)] achievements=
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 7416): 
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 7416): 
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Populating Achievements, status = VALID: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Populating Achievements, status = VALID
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 7416): 
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Found 20 Achievements: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Found 20 Achievements
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 7416): 
D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Maybe finish for Achievements: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Maybe finish for Achievements
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 7416): 
D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Auth finished. Proceeding.: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Auth finished. Proceeding.
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 7416): 
D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Invoking Callbacks: System.Action`1[System.Boolean]: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:05 -08:00 DEBUG: Invoking Callbacks: System.Action`1[System.Boolean]
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 7416): 
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): Unloading 23 Unused Serialized files (Serialized files now loaded: 0 / Dirty serialized files: 0)
D/Unity   ( 7416): Unloading 8 Unused Serialized files (Serialized files now loaded: 0 / Dirty serialized files: 0)
D/Unity   ( 7416): Unloading 8 Unused Serialized files (Serialized files now loaded: 0 / Dirty serialized files: 0)
D/Unity   ( 7416): Unloading 8 Unused Serialized files (Serialized files now loaded: 0 / Dirty serialized files: 0)
D/Unity   ( 7416): Unloading 4 Unused Serialized files (Serialized files now loaded: 0 / Dirty serialized files: 0)
D/Unity   ( 7416): highestCompletedLevelID: 1 lastCompletedLevelID: 1: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416): highestCompletedLevelID: 1 lastCompletedLevelID: 1
I/Unity   ( 7416): UnityEngine.Debug:Internal_Log(Int32, String, Object)
I/Unity   ( 7416): UnityEngine.Debug:Log(Object)
I/Unity   ( 7416): LevelMap:Start() (at /Users/Art/Projects/proj1/Assets/Scripts/UI/LevelMap.cs:110)
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/Art/Projects/proj1/Assets/Scripts/UI/LevelMap.cs Line: 110)
I/Unity   ( 7416): 
D/Unity   ( 7416): currentLevelID: 2: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416): currentLevelID: 2
I/Unity   ( 7416): UnityEngine.Debug:Internal_Log(Int32, String, Object)
I/Unity   ( 7416): UnityEngine.Debug:Log(Object)
I/Unity   ( 7416): LevelMap:Start() (at /Users/Art/Projects/proj1/Assets/Scripts/UI/LevelMap.cs:150)
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/Art/Projects/proj1/Assets/Scripts/UI/LevelMap.cs Line: 150)
I/Unity   ( 7416): 
D/Unity   ( 7416): Unable to load library '/data/app/com.company.game-1/lib/x86/libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.company.game-1/lib/x86/libgpg.so" already opened by ClassLoader 0x12c74f60; can't open in ClassLoader 0x0
D/Unity   ( 7416): assigning glowingLine(Clone) movingLineObject ... levelID: 2 currentLevelID: 2 levelCompleted: 0: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416): assigning glowingLine(Clone) movingLineObject ... levelID: 2 currentLevelID: 2 levelCompleted: 0
I/Unity   ( 7416): UnityEngine.Debug:Internal_Log(Int32, String, Object)
I/Unity   ( 7416): UnityEngine.Debug:Log(Object)
I/Unity   ( 7416): LevelMap:Start() (at /Users/Art/Projects/proj1/Assets/Scripts/UI/LevelMap.cs:440)
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/Art/Projects/proj1/Assets/Scripts/UI/LevelMap.cs Line: 440)
I/Unity   ( 7416): 
D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:06 -08:00 DEBUG: Invoking user callback on game thread: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:06 -08:00 DEBUG: Invoking user callback on game thread
I/Unity   ( 7416): UnityEngine.Debug:Internal_Log(Int32, String, Object)
I/Unity   ( 7416): UnityEngine.Debug:Log(Object)
I/Unity   ( 7416): GooglePlayGames.OurUtils.Logger:d(String) (at /Users/Art/Projects/proj1/Assets/GooglePlayGames/OurUtils/Logger.cs:59)
I/Unity   ( 7416): GooglePlayGames.Native.<InvokeCallbackOnGameThread>c__AnonStoreyA7`1:<>m__127() (at /Users/Art/Projects/proj1/Assets/GooglePlayGames/Platforms/Native/NativeClient.cs:162)
I/Unity   ( 7416): GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at /Users/Art/Projects/proj1/Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:136)
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/Art/Projects/proj1/Assets/GooglePlayGames/OurUtils/Logger.cs Line: 59)
I/Unity   ( 7416): 
D/Unity   ( 7416): Authentication successful: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416): Authentication successful
I/Unity   ( 7416): UnityEngine.Debug:Internal_Log(Int32, String, Object)
I/Unity   ( 7416): UnityEngine.Debug:Log(Object)
I/Unity   ( 7416): GameServices:AuthenticateCallback(Boolean) (at /Users/Art/Projects/proj1/Assets/Scripts/Game/GameServices.cs:136)
I/Unity   ( 7416): GooglePlayGames.Native.<InvokeCallbackOnGameThread>c__AnonStoreyA7`1:<>m__127() (at /Users/Art/Projects/proj1/Assets/GooglePlayGames/Platforms/Native/NativeClient.cs:163)
I/Unity   ( 7416): GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at /Users/Art/Projects/proj1/Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:136)
I/Unity   ( 7416):  
I/Unity   ( 7416): (Filename: /Users/Art/Projects/proj1/Assets/Scripts/Game/GameServices.cs Line: 136)
I/Unity   ( 7416): 
D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:06 -08:00 DEBUG: ReportScore: score=3060, board=CgkIx4GolesJEAIQAg: 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:06 -08:00 DEBUG: ReportScore: score=3060, board=CgkIx4GolesJEAIQAg
I/Unity   ( 7416): UnityEngine.Debug:Internal_Log(Int32, String, Object)
I/Unity   ( 7416): UnityEngine.Debug:Log(Object)
I/Unity   ( 7416): GooglePlayGames.OurUtils.Logger:d(String) (at /Users/Art/Projects/proj1/Assets/GooglePlayGames/OurUtils/Logger.cs:59)
I/Unity   ( 7416): GooglePlayGames.PlayGamesPlatform:ReportScore(Int64, String, Action`1) (at /Users/Art/Projects/proj1/Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:892)
I/Unity   ( 7416): UnityEngine.Social:ReportScore(Int64, String, Action`1)
I/Unity   ( 7416): GameServices:SubmitPlayerScore() (at /Users/Art/Projects/proj1/Assets/Scripts/Game/GameServices.cs:777)
I/Unity   ( 7416): GameServices:HandleOnAuthenticate(Boolean) (at /Users/Art/Projects/proj1/Assets/Scripts/Game/GameServices.cs:743)
I/Unity   ( 7416): GameServices:AuthenticateCallback(Boolean) (at /Users/Art/Projects/proj1/Assets/Scripts/Game/GameServices.cs:152)
I/Unity   ( 7416): GooglePlayGames.Native.<InvokeCallbackOnGameThread>c__AnonStoreyA7`1:<>m__127() (at /Users/Art/Projects/proj1/Assets/GooglePlayGames/Platforms/Native/NativeClie
D/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:06 -08:00 DEBUG: Native Submitting score: 3060 for lb CgkIx4GolesJEAIQAg with metadata: : 0 at /Users/builduser/buildslave/unity/build/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp:56 (17408, 0, 0)
I/Unity   ( 7416):  [Play Games Plugin DLL] 03/04/16 11:40:06 -08:00 DEBUG: Native Submitting score: 3060 for lb CgkIx4GolesJEAIQAg with metadata: 
I/Unity   ( 7416): UnityEngine.Debug:Internal_Log(Int32, String, Object)
I/Unity   ( 7416): UnityEngine.Debug:Log(Object)
I/Unity   ( 7416): GooglePlayGames.OurUtils.Logger:d(String) (at /Users/Art/Projects/proj1/Assets/GooglePlayGames/OurUtils/Logger.cs:59)
I/Unity   ( 7416): GooglePlayGames.Native.PInvoke.LeaderboardManager:SubmitScore(String, Int64, String) (at /Users/Art/Projects/proj1/Assets/GooglePlayGames/Platforms/Native/PInvoke/LeaderboardManager.cs:51)
I/Unity   ( 7416): GooglePlayGames.Native.NativeClient:SubmitScore(String, Int64, Action`1) (at /Users/Art/Projects/proj1/Assets/GooglePlayGames/Platforms/Native/NativeClient.cs:1008)
I/Unity   ( 7416): GooglePlayGames.PlayGamesPlatform:ReportScore(Int64, String, Action`1) (at /Users/Art/Projects/proj1/Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:894)
I/Unity   ( 7416): UnityEngine.Social:ReportScore(Int64, String, Action`1)
I/Unity   ( 7416): GameServices:SubmitPlayerScore() (at /Users/Art/Projects/proj1/Assets/Scripts/Game/GameServices.cs:777)`

**Comment by claywilkinson** [comment]
That is very strange (I know not want you want to hear).  The library is being loaded, and the calls are being made successfully (at least from what I see in the log).  Have you checked the Unity support site, maybe something strange about that version of Unity?

**Comment by artakino** [comment]
Like you said, the library does load and the calls do get made successfully.  But I can't identify the source of the errors.  I have checked the Unity support sites and search on google without any success.

**Comment by avvie** [comment]
cant someone upload a static version of the library?

**Comment by claywilkinson** [comment]
You can download the static version of the SDK from https://developers.google.com/games/services/downloads/sdks
