### ISSUE TITLE
Leaderboard always show score 0

### ISSUE THREAD

**Issue by Loony04** [playgameservices/play-games-plugin-for-unity#1026]
I am first using this pluging and I have the problem with showing leaderboard. When I show, the score is 0. But other functions like a achievement work good. I use these codes to submit score and to show leaderboards:

`Social.ReportScore(12345, "my_leaderboard_id", (bool success) => { });`
and in other place:
`Social.ShowLeaderboardUI();`

I tried also above functions with casting (PlayGamesPlatform) and with Active field. Nothing works.

Function ReportScore shows that all is ok. Success is true, earlier authentication is also ok. But in leaderboard score is 0. What's wrong?

In the Play Console the game and play services are not published, but achievements work.

**Comment by claywilkinson** [comment]
Which collection are you checking, and how? The social leaderboard should be populated immediately, and show using the standard leaderboard UI.  The global leaderboard is updated periodically.

**Comment by Loony04** [comment]
I don't know. I use code above as you can see. That code is in this repository in readme.md. I did it as the example.
Moreover, after using Social.ShowLeaderboardUI and selecting leaderboard there is button to change between social and all - results. In each place is score 0.

**Comment by Loony04** [comment]
Ok, I have solved a problem. I haven't read about score formatting and I don't multiplying value by 10000.
https://developers.google.com/games/services/common/concepts/leaderboards#score_formatting

My mistake.
