### ISSUE TITLE
What was the last version to work below Unity 4.6?

### ISSUE THREAD

**Issue by piesay** [playgameservices/play-games-plugin-for-unity#1028]
This is probably the wrong place for this but I am not sure where to ask.

The current version of the plugin doesn't properly support Unity 4.6 or versions below that so I was wondering which one of the older versions does? Specifically Unity 4.5?

I have read the change log but I can't find the info I am looking for.

Thanks.

**Comment by claywilkinson** [comment]
The plugin mostly works in the older versions when running the application.  The parts don't work too well are the Editor parts for running setup and building the project.  Feel free to try it out.  You might want to download a newer version of Unity and build a sample project as a reference so you can see what might not be working.  It is more the case that we have not tried to use an older version vs. we know it won't work.
