### ISSUE TITLE
NullReferenceException error at OnRoomConnected RTM

### ISSUE THREAD

**Issue by gamozome** [playgameservices/play-games-plugin-for-unity#1029]
Hello,
I am using play-games-plugin-for-unity 0.9.32
My SDK is updated.  
When 2 player join room, they both show waiting room. After they connected I get Error.

Error1: 
I/Unity   (12619): NullReferenceException: Object reference not set to an instance of an object

I/Unity   (12619):   at MangerRTM.OnRoomConnected (Boolean success) [0x00000] in <filename unknown>:0 

I/Unity   (12619):   at GooglePlayGames.Native.NativeRealtimeMultiplayerClient+OnGameThreadForwardingListener+<RoomConnected>c__AnonStorey44.<>m__51 () [0x00000] in <filename unknown>:0 

I/Unity   (12619):   at GooglePlayGames.OurUtils.PlayGamesHelperObject.Update () [0x00000] in <filename unknown>:0 

Also in editor I get error
Error 2: 

System.Xml.XmlException: Document element did not appear.  Line 1, position 1.
  at Mono.Xml2.XmlTextReader.Read () [0x00000] in <filename unknown>:0 
  at System.Xml.XmlTextReader.Read () [0x00000] in <filename unknown>:0 
  at Google.JarResolver.PlayServicesSupport.LoadDependencies (Boolean allClients) [0x00000] in <filename unknown>:0 
  at Google.JarResolver.PlayServicesSupport.CreateInstance (System.String clientName, System.String sdkPath, System.String settingsDirectory) [0x00000] in <filename unknown>:0 
  at GooglePlayGames.Editor.GPGSDependencies..cctor () [0x0000a] in E:\Network1.3-23\Assets\GooglePlayGames\Editor\GPGSDependencies.cs:41 
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

Error 3:

FileNotFoundException: Could not load file or assembly 'GooglePlayServices' or one of its dependencies. The system cannot find the file specified.
System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, Boolean refonly) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/AppDomain.cs:746)
System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/AppDomain.cs:733)
(wrapper remoting-invoke-with-check) System.AppDomain:Load (string,System.Security.Policy.Evidence)
System.Reflection.Assembly.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/Assembly.cs:584)
System.Activator.CreateInstance (System.String assemblyName, System.String typeName, Boolean ignoreCase, BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Security.Policy.Evidence securityInfo) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Activator.cs:170)
System.Activator.CreateInstance (System.String assemblyName, System.String typeName, System.Object[] activationAttributes) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Activator.cs:158)
System.Activator.CreateInstance (System.String assemblyName, System.String typeName) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Activator.cs:150)
GooglePlayServices.PlayServicesResolver.get_Resolver () (at Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:96)
GooglePlayServices.PlayServicesResolver.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:115)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:27)
UnityEditor.AssetDatabase:Refresh()
GooglePlayGames.Editor.GPGSUpgrader:.cctor() (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:107)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

**Comment by gamozome** [comment]
Anyone please?

**Comment by claywilkinson** [comment]
Is MangerRTM a class you authored?  I don't think it is part of the plugin, so I'd suggest  looking at what variables you are accessing and determine which one is null?

Errors 2 and 3 are not related. - Can you share the contents of ProjectSettings/GoogleDependencyGooglePlayGames.xml ?  

After you copy the contents, can you exit Unity and delete that file?  It will be regenerated when loading the project again.

**Comment by gamozome** [comment]
Hi, Thanks for reply.

    ManagerRTM is just a class in which I use OnRoomConnected Method. The null is not exactly on any variable. Earlier I had Gameobject so suspecting that as a culprit. But when I changed it to debug, it starts giving null there as well. Actually player gets connected after that OnRoomConnected method throws that null & code stops running after that.

After removing xml, it regenerated. And error 2 - 3 has gone thanks.

**Comment by claywilkinson** [comment]
So is everything working now?

**Comment by gamozome** [comment]
No its not. The same null occurs somewhere in the OnRoomConnected Method. As I mentioned above it is not line or variable specific. Code stops somewhere while running inside OnRoomConnected Method. 
Here is the code:
public void OnRoomConnected(bool success)
	{
		if (success)
		{

			myself = PlayGamesPlatform.Instance.RealTime.GetSelf();
			GameObject player;
			int i = 0;		
			Participant self = PlayGamesPlatform.Instance.RealTime.GetSelf();
			foreach(Participant p in PlayGamesPlatform.Instance.RealTime.GetConnectedParticipants()) 
			{
				if(p.ParticipantId.Equals(myself.ParticipantId))
				{

					myPlayerPrefab = spawnPrefab[PlayerPrefs.GetInt("ElementInUse")];
					player = (GameObject) Instantiate(myPlayerPrefab,spawnPosition[i].transform.position,spawnPosition[i].transform.rotation);

				}

I usually get null at player instantiate line. But I get the value of "ElementInUse" when I debug it.
