### ISSUE TITLE
not able to get user email.

### ISSUE THREAD

**Issue by iamsyedsuhail** [playgameservices/play-games-plugin-for-unity#1032]
unity 5.3.2
ver 0.9.27

`	void Start () {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
            //// enables saving game progress.
            //.EnableSavedGames()
            //// registers a callback to handle game invitations received while the game is not running.
            //.WithInvitationDelegate(< callback method >)
            //// registers a callback for turn based match notifications received while the
            //// game is not running.
            //.WithMatchDelegate(< callback method >)
            //// require access to a player's Google+ social graph to sign in
            .WithPermissionRationale("GET_ACCOUNTS")
            .Build();

        PlayGamesPlatform.InitializeInstance(config);
        // recommended for debugging:
        PlayGamesPlatform.DebugLogEnabled = true;
        // Activate the Google Play Games platform
        PlayGamesPlatform.Activate();

        Invoke("SignIN", 4);
    }`

`void SignIN()
    {
        Social.localUser.Authenticate((bool success) => {
        // handle success or failure
        if (success)
        {
            text.text = "Logged In";
            Social.ReportScore(12345, "CgkIuZfd2I4LEAIQAQ", (bool yes) => {
                // handle success or failure
                if (yes)
                    text.text = "Logged In and Leader";
            });
        }
        if (success)
        {
                
            GooglePlayGames.OurUtils.PlayGamesHelperObject.RunOnGameThread(
    () => {
        fbid = ((PlayGamesLocalUser)UnityEngine.Social.localUser).id;
        fbemail = ((PlayGamesLocalUser)UnityEngine.Social.localUser).Email;
        fbnick = ((PlayGamesLocalUser)UnityEngine.Social.localUser).userName;
        ui[0].text = fbemail;
        ui[1].text = fbid;
        ui[2].text = fbnick;
            // use the email as needed
        });
            ui[3].text = GooglePlayGames.PlayGamesPlatform.Instance.GetUserEmail();
            }
        });
    }`

i tried RequireGooglePlus(), but there is no method in the following class, i am to receive id and username, but i need email, which always returns an empty string.

how do i fix it?

**Comment by claywilkinson** [comment]
The email will be retrieved asynchronously. So, assuming there are no issues in the configuration (you can check the log to see if there are errors when authenticating), you'll need to periodically check for the email, such as in Update().  There is an enhancement request to add a callback for getting the email.

**Comment by claywilkinson** [comment]
Added a method that uses a callback to get the email, so it is easier to use.
