### ISSUE TITLE
Turn Based Multiplayer-How to know if a match is a rematch?

### ISSUE THREAD

**Issue by Glintlabs** [playgameservices/play-games-plugin-for-unity#1034]
Hi, 
I need to difference between an original and a rematch. Is any way to do it?
Thanks in advance

**Comment by claywilkinson** [comment]
You can use the property  `TurnBasedMatch.canRematch` to check.  If it is true for the original match, false for the rematch.

**Comment by Glintlabs** [comment]
Thanks!
