### ISSUE TITLE
Can't login Google play account!!!

### ISSUE THREAD

**Issue by WaDapeng** [playgameservices/play-games-plugin-for-unity#1036]
unity 5.2.3 can't use the current build plugin 0.9.31a ,I use the old builds 0.9.21,but I can't login Google play account,Can you help me!

**Comment by WaDapeng** [comment]
When I set the     "	PlayGamesPlatform.DebugLogEnabled=true; "
unity show that   
[Play Games Plugin DLL] 03/09/16 14:38:56 +08:00 DEBUG: Activating PlayGamesPlatform.
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets/GooglePlayGames/OurUtils/Logger.cs:58)
GooglePlayGames.PlayGamesPlatform:Activate() (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:228)
Logint:Start() (at Assets/Scripts/Logint.cs:16)

 [Play Games Plugin DLL] 03/09/16 14:38:56 +08:00 DEBUG: Instance was not initialized, using default configuration.
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets/GooglePlayGames/OurUtils/Logger.cs:58)
GooglePlayGames.PlayGamesPlatform:get_Instance() (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:94)
GooglePlayGames.PlayGamesPlatform:Activate() (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:229)
Logint:Start() (at Assets/Scripts/Logint.cs:16)


 [Play Games Plugin DLL] 03/09/16 14:38:56 +08:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets/GooglePlayGames/OurUtils/Logger.cs:58)
GooglePlayGames.PlayGamesPlatform:Activate() (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:230)
Logint:Start() (at Assets/Scripts/Logint.cs:16)

**Comment by aditya2** [comment]
i hope that you've activated the PlayGamesPlatform before the login process and your email is in the testers list in game services on play store developer console

**Comment by WaDapeng** [comment]
I have add the test email and active the PlayGamesPlatform   , I can use the in app purchase ,but I can't sign in.

**Comment by claywilkinson** [comment]
Can you share the log of calling Authenticate()?

**Comment by aditya2** [comment]
@claywilkinson Can you pls resolve this too #1037
