### ISSUE TITLE
Can't accept invitation

### ISSUE THREAD

**Issue by aditya2** [playgameservices/play-games-plugin-for-unity#1037]
Basically my problem is when the app is not running on one phone then the user of this phone can't accept the invitation from notification bar ... user getting a notification about the invitation but when he accepts that invitation from notification bar itself, it just launches the game and nothing else, no notification is accepted plus AcceptFromInbox is also empty .... how to make a user to accept an invitation from notification bar when the app is not running ... plus i've also considered the Tic Tac Toss example without any success

**Comment by claywilkinson** [comment]
I'll take another look at this soon.

**Comment by WaDapeng** [comment]
Open the Unity ,Select Window =>GooglePlay Games=>Downloads=>SDK select your platform  and then  there is a sdk named "google play service",install it , because this sdk will import in your project when you click the setup , perhaps this will help you.

**Comment by aditya2** [comment]
okay @claywilkinson  and @WaDapeng there is nothing named google play services, take a look at image [http://imgur.com/zUTzbCt](url)

**Comment by aditya2** [comment]
@claywilkinson  i m still waiting :)

**Comment by claywilkinson** [comment]
From the image - it looks like you are targeting iOS in Unity, correct?  To confirm, you are getting the APNS message showing it is your player's turn, but when you click on it, it just starts the app?  Do you sign in?  

Can you share the log of trying the tic-tac-toss sample?

**Comment by aditya2** [comment]
sorry to say but i m targeting Android and yes whenever player accepting the invitation from notification it just starts app and performs the sign - in  process (same as i programmed it) and then my app is calling the function which enables the user to send invites and not the functions that should run whenever user accepts the invite, this means app is not accepting the invite  from notification bar .... and again sorry to say but the tic tac toss it self not working as it is always asking to sign in even on sign in success ... plus i don't know how to get the log you are tacking about

**Comment by claywilkinson** [comment]
You can get the log from an android device by using [logcat](http://developer.android.com/tools/help/logcat.html).  If you cannot signin successfully, there most likely is a configuration problem.  This will definitely prevent invitations from flowing successfully.

**Comment by aditya2** [comment]
@claywilkinson i can sign in successfully, i can say this because when the ap is running on both the phone then this invitation thing is working all fine, the problem occurs when the app is not running on one phone then this phone is receiving invitation on notification bar, and when user accepts invitation from notification then it only launches the app and performs sign-in (which is going on successfully), but then nothing, no invitation is accepted ... but anyway i m trying to figure out how this logcat thing works and will send you the log

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
