### ISSUE TITLE
RequiresGooglePlus not set, cannot request email!

### ISSUE THREAD

**Issue by DrSpritz1** [playgameservices/play-games-plugin-for-unity#1038]
Hello!
I have some issue with getting user's email.

My test code
```
    void Start()
    {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
            .RequireGooglePlus()
            .Build();

        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.DebugLogEnabled = true;
        PlayGamesPlatform.Activate();

        Social.localUser.Authenticate((bool success) =>
        {
            Debug.Log("Authenticate " + success);

            Debug.Log("Local user's name " + Social.localUser.userName);

            GooglePlayGames.OurUtils.PlayGamesHelperObject.RunOnGameThread(() =>
            {
                Debug.Log("Local user's email is " + ((PlayGamesLocalUser)Social.localUser).Email);
            });
        });
    }
```

I always have the error "RequiresGooglePlus not set, cannot request email!", but as you see from my test code, i has requred Google Plus and also i have all permissions in the AndroidManifest.xml

```
    <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
    <uses-permission android:name="android.permission.USE_CREDENTIALS"/>
```

I decided to look, where is the log and was surprised when found GameInfo.RequireGooglePlus()

Source

```
        public static bool RequireGooglePlus()
        {
            return "false" == "true";
        }
```

What doing this method?) And that must be in this place?)

Plugin version 0.9.32

**Comment by claywilkinson** [comment]
This means that the checkbox in the Setup dialog for RequireGooglePlus was not checked.  Can you re-run setup and confirm it is checked?  (The "false" is the state of the checkbox.).  This code is generated using a template: https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Editor/template-GameInfo.txt

**Comment by DrSpritz1** [comment]
Thank you! I was confused from the code `return "false" == "true"` Now everything is clear to me, reconfigured project and everything works fine!

**Comment by claywilkinson** [comment]
Great! Glad you got it working!
