### ISSUE TITLE
GPGSTurnBasedMatchDelegate crashes in iOS 6.x

### ISSUE THREAD

**Issue by AlessandroLacroce** [playgameservices/play-games-plugin-for-unity#104]
In GPGSTurnBasedMatchDelegate.m it crashes at the following command: 

[match.data base64EncodedStringWithOptions:0]

replace with 

[match.data base64Encoding] 

for pre iOS7 devices

**Comment by ToddKerpelman** [comment]
Closing this one, since we require iOS7 for Play Game Services
