### ISSUE TITLE
Ios build only works with bitcode turned off in "Build options" for both Unity-iPhone and Pods

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#1040]
I have Unity 5.3.3 and Xcode 7.2.1 and latest plugin...

Default settings after build is Unity-Iphone - Bitcode: yes and Pods: No. 

I get this error message on theese default settings:

Ld /Users/agare/Library/Developer/Xcode/DerivedData/Unity-iPhone-ahmkatrmcdfnvceoeftjcjotklsb/Build/Intermediates/Unity-iPhone.build/Debug-iphoneos/Unity-iPhone.build/Objects-normal/arm64/test55 normal arm64
    cd /Users/agare/Desktop/gpgenbart32nygpg
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -L/Users/agare/Library/Developer/Xcode/DerivedData/Unity-iPhone-ahmkatrmcdfnvceoeftjcjotklsb/Build/Products/Debug-iphoneos -L/Users/agare/Desktop/gpgenbart32nygpg/Pods/GoogleAppUtilities/Libraries -L/Users/agare/Desktop/gpgenbart32nygpg/Pods/GoogleAuthUtilities/Libraries -L/Users/agare/Desktop/gpgenbart32nygpg/Pods/GoogleNetworkingUtilities/Libraries -L/Users/agare/Desktop/gpgenbart32nygpg/Pods/GoogleSignIn/Libraries -L/Users/agare/Desktop/gpgenbart32nygpg/Pods/GoogleSymbolUtilities/Libraries -L/Users/agare/Desktop/gpgenbart32nygpg/Pods/GoogleUtilities/Libraries -L/Users/agare/Desktop/gpgenbart32nygpg -L/Users/agare/Desktop/gpgenbart32nygpg/Libraries -F/Users/agare/Library/Developer/Xcode/DerivedData/Unity-iPhone-ahmkatrmcdfnvceoeftjcjotklsb/Build/Products/Debug-iphoneos -F/Users/agare/Desktop/gpgenbart32nygpg/Pods/GooglePlayGames/gpg-cpp-sdk/ios -F/Users/agare/Desktop/gpgenbart32nygpg/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1 -F/Users/agare/Desktop/gpgenbart32nygpg/UnityAds -filelist /Users/agare/Library/Developer/Xcode/DerivedData/Unity-iPhone-ahmkatrmcdfnvceoeftjcjotklsb/Build/Intermediates/Unity-iPhone.build/Debug-iphoneos/Unity-iPhone.build/Objects-normal/arm64/test55.LinkFileList -Xlinker -map -Xlinker /Users/agare/Library/Developer/Xcode/DerivedData/Unity-iPhone-ahmkatrmcdfnvceoeftjcjotklsb/Build/Intermediates/Unity-iPhone.build/Debug-iphoneos/Unity-iPhone.build/test55-LinkMap-normal-arm64.txt -miphoneos-version-min=7.0 -dead_strip -fembed-bitcode-marker -weak_framework CoreMotion -weak-lSystem -ObjC -lGIPNSURL+FIFE -lGSDK_Overload -lGTMOAuth2_external -lGTMOAuth2_internal -lGTMSessionFetcher_core -lGTMSessionFetcher_full -lGTMStackTrace -lGTM_AddressBook -lGTM_DebugUtils -lGTM_GTMURLBuilder -lGTM_KVO -lGTM_NSData+zlib -lGTM_NSDictionary+URLArguments -lGTM_NSScannerJSON -lGTM_NSStringHTML -lGTM_NSStringXML -lGTM_Regex -lGTM_RoundedRectPath -lGTM_StringEncoding -lGTM_SystemVersion -lGTM_UIFont+LineHeight -lGTM_core -lGTM_iPhone -lOpenInChrome -lSignIn -lc++ -lz -framework AddressBook -framework AssetsLibrary -framework CoreData -framework CoreGraphics -framework CoreLocation -framework CoreMotion -framework CoreTelephony -framework CoreText -framework GoogleOpenSource -framework MediaPlayer -framework QuartzCore -framework SafariServices -framework Security -framework StoreKit -framework SystemConfiguration -framework gpg -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -weak_framework iAd -framework MediaPlayer -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -liPhone-lib -framework GameKit -lPods-Unity-iPhone -framework UnityAds -weak_framework AdSupport -framework StoreKit -framework CoreTelephony -Xlinker -dependency_info -Xlinker /Users/agare/Library/Developer/Xcode/DerivedData/Unity-iPhone-ahmkatrmcdfnvceoeftjcjotklsb/Build/Intermediates/Unity-iPhone.build/Debug-iphoneos/Unity-iPhone.build/Objects-normal/arm64/test55_dependency_info.dat -o /Users/agare/Library/Developer/Xcode/DerivedData/Unity-iPhone-ahmkatrmcdfnvceoeftjcjotklsb/Build/Intermediates/Unity-iPhone.build/Debug-iphoneos/Unity-iPhone.build/Objects-normal/arm64/test55

ld: '/Users/agare/Desktop/gpgenbart32nygpg/Pods/GoogleAuthUtilities/Libraries/libGTMOAuth2_external.a(GTMOAuth2Authentication.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by claywilkinson** [comment]
Thanks for the info - I'll make it an enhancement to set ENABLE_BITCODE = NO in GPGSPostBuild.cs

**Comment by claywilkinson** [comment]
Added the ENABLE_BITCODE = NO to the post processing of the xcode project in version 0.9.33
