### ISSUE TITLE
How to specify users in the same device?

### ISSUE THREAD

**Issue by pokekingvn** [playgameservices/play-games-plugin-for-unity#1043]
Hi, i'm going to make a leaderboard in my game with this plugin, but now i don't know how to specify users in the same device.
I test on my phone with 2 google account, so when the 1st acc login and post score, it probably show 1st's score (500 point). Then i log out and login again with 2nd acc (100 point). It should be show 100 point, but it was 500, the same point with 1st acc.
in code, i call:
`private int score;`

and when post score
`Social.ReportScore(score, leaderboard, (bool ok) =>
                                       {
                        if (ok)
                        {
                            ((PlayGamesPlatform)Social.Active).ShowLeaderboardUI(leaderboard);
                            noticeText.text = "You've successfully show";
                        }
                        else
                        {
                            noticeText.text = "You've fail to show";
                        }
                    });`

so are there any ways to make out the user's score in same device?

**Comment by claywilkinson** [comment]
Are you logging out and logging into the game as the new user?  There was a recent change to how authentication works to Play Game Services:  http://android-developers.blogspot.be/2016/01/play-games-permissions-are-changing-in.html, which automatically signs in the player.  

A quick check is to log the localplayer's name when reporting the score.

**Comment by pokekingvn** [comment]
> Are you logging out and logging into the game as the new user? 

i log in with as user A, report score (500), log out user A and log in game with another account => now i'm in game as user B

> There was a recent change to how authentication works to Play Game Services: http://android-developers.blogspot.be/2016/01/play-games-permissions-are-changing-in.html, which automatically signs in the player.

A quick check is to log the localplayer's name when reporting the score.

i search in that post but i still don't know how to check different user in same device when reporting score. I'm pretty new with code, so please help me.

**Comment by pokekingvn** [comment]
> A quick check is to log the localplayer's name when reporting the score.

Please help me, is there any way Game Services can check localplayer's name before reporting score to avoid reporting the same score ?
or i must find someway to check in game by my code? I'm stil can't find way to do it.

**Comment by claywilkinson** [comment]
You can log the name of the current player: 
`Debug.Log("Current player is: " + Social.localUser.userName);`
