### ISSUE TITLE
iOS: NSInvalidArgumentException on auto sign-in on initialize

### ISSUE THREAD

**Issue by colinamuzo** [playgameservices/play-games-plugin-for-unity#1044]
Using Unity 5.3.2f1, plugin 0.9.31a, Xcode 7.0.1.
Not using Cocoapods.
Project builds, installs and runs, but immediately crashes with the following error (in Xcode console).

> NSInvalidArgumentException',
> reason: 
> 'When |allowsSignInWithWebView| is enabled, uiDelegate must either be a |UIViewController| or implement the |signIn:presentViewController:| and |signIn:dismissViewController:| methods from |GIDSignInUIDelegate'

GPGSAppController appears to implement all methods in the GIDSignInUIDelegate interface, including the ones mentioned, and I'm assuming that the GPGSAppController instance is being passed as uiDelegate.

Any idea how I can fix this?

**Comment by colinamuzo** [comment]
[log.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/169383/log.txt)

**Comment by colinamuzo** [comment]
Just tried the very latest Google frameworks:
* Google Open Source (from Google Plus 1.7.1)
* Google Sign In 2.4.0
* gpg 2.1
Issue still present.

**Comment by colinamuzo** [comment]
Just tried a Cocoapods builds, and the issue is still present.

Has anyone got any ideas?

**Comment by claywilkinson** [comment]
From the log it looks like you have not signed in before trying to get the AuthToken?  Did you sign in successfully first?

**Comment by colinamuzo** [comment]
Thanks for the response.

> From the log it looks like you have not signed in before trying to get the AuthToken?

What in the log implies that?

> Did you sign in successfully first?

I thought the crash was _during_ a sign in attempt.  The sign in attempt comes from NativeClient.InitializeGameServices, which is being called by NativeClient.Authenticate, which is ultimately being called by my code.  The only related thing I do prior to calling PlayGamesPlatform.Authenticate, is to call PlayGamesPlatform.Activate.

> Also check the Assets/Plugins/iOS directory to make sure you have the correct AppController code.

GPGSAppController.mm/h are present in the Assets/Plugins/iOS directory.

It doesn't seem relevant, but I'll mention it anyway on the off-chance: as far as I can recall, with all recent versions of the plugin, I've had to amend some include lines in GPGSAppController.mm, by prefixing the file path with "GoogleSignIn/".  Could that be a sign of some set-up issue, which could be causing the crash?

**Comment by colinamuzo** [comment]
I have tried building and running the "minimal" sample app, and I do not get the crash.

While this does imply the problem is in my code/setup, I would still like some help regarding this issue.

**Comment by colinamuzo** [comment]
[Xcode log from running the minimal sample](https://github.com/playgameservices/play-games-plugin-for-unity/files/180087/minimal_log.txt)

I linked all of the frameworks and libraries that my own project links, to try to duplicate the same build environment.  The sample still runs without error.

From the Xcode log I can see that the next line _should_ be:

> VERBOSE: Finished running UI sign in request on main thread.

...but I get a crash instead.

Can anyone offer some assistance with this please?

**Comment by colinamuzo** [comment]
I have been doing iterations of removing things from my project and rebuilding, and I am still getting the crash, but I have noticed something interesting/possibly significant.

In the above-attached Xcode log from the crash in my project (not the log from the minimal app), there are 2 lines in the callstack of the crash, that reference "GTLServicePlus init".  When I have removed systems and run again, those two lines have changed.  They always have the same name, and the rest of the call stack looks identical.

The first time I noticed the change, the name related to the Flurry tracking plugin we're using, so I removed that, and tried again.  Then the name related to Prime31 (the developer of the Flurry plugin), so I removed all other Prime31 plugins.  Then the name related to another plugin developer, so I removed all their plugins.  Then the name related to IL2CPP, which is part of Unity's core tech, so I could not remove that.

I had initially thought that the name we're pointing towards problematic systems (maybe systems which were incompatible with the GPGS plugin), but when IL2CPP came up I thought that that could not be the case.

Could it be the case that the functions/names that appear there are just whatever function is at a certain place in memory at runtime?  Does this shed any light on the issues I'm having?

**Comment by mrm83** [comment]
I am getting the exact same error.  did manual install instead of using cocoapods..  using IL2CPP as well.

**Comment by colinamuzo** [comment]
I'm slowly getting to the bottom of it.  Turns out we are sub-classing UnityAppController just like GPGSAppController does, and I think that is the root cause of the problem.  My only evidence of this is that adding our UnityAppController sub-class to the minimal sample app caused it to crash in the sameway.  I'm still in the process of removing our UnityAppController sub-class from our project, while try to keep the functionality we had implemented in it, so I haven't yet proved that this will completely fix the issue.

**Comment by mrm83** [comment]
Any updates?

**Comment by mrm83** [comment]
Why is this plugin using google plus signin when it is deprecated?

**Comment by mrm83** [comment]
hey op and whoever stumps upon this issue.

upgrade to the latest unity google play plugin will fix this.   
the newest one uses google signin instead of google plus signin which contains this bug.

another issue arise with google siginin though.. it uses webview for signin which apple rejects..  looking for a workaround for that atm..

**Comment by claywilkinson** [comment]
@mrm83 - was your app rejected for the web view?  I know there there many apps that use Google Sign In and have been accepted.  Did you appeal? Can you share their response?  I'd like to pass it along to the team that works on Identity for iOS.

**Comment by mrm83** [comment]
No, I found threads saying apple is rejecting for that reason while searching for a solution for this issue.

Here is the response (copied from the thread https://code.google.com/p/google-plus-platform/issues/detail?id=900)

Reasons

10.6: Apple and our customers place a high value on simple, refined, creative, well thought through interfaces. They take more work but are worth it. Apple sets a high bar. If your user interface is complex or less than very good, it may be rejected
10.6

We found the following issues with the user interface of your app:

The app opens a web page in mobile Safari for logging in to Google plus, then returns the user to the app. The user should be able log in without opening Safari first.

These examples identify types of issues discovered in your app but may not represent all such issues. It would be appropriate to thoroughly evaluate your app to address these types of issues.

**Comment by claywilkinson** [comment]
That is very old information (July 2014).  The specific objection is about opening the Safari app, then switching back, not a web view. The current sign-in uses SafariWebView which is acceptable to Apple.  If you read the most recent issues on that thread, the objections from Apple are not related to Google.

Thanks for contributing to the conversation, but it would be best if you constrained comments to first-hand experiences, or  referencing threads.  Copying old facts as new information is confusing and does not really help anyone.

**Comment by colinamuzo** [comment]
Sorry, I have been away for a week. I resolved my issue by removing our UnityAppController sub-class from our project

Thanks for the responses.

**Comment by ankitak71** [comment]
@colinamuzo Can you please explain in detail how you remove UnityAppController subclass from project. I got the same issue.

**Comment by colinamuzo** [comment]
Search all .m/.mm/.h files in your project for the string "UnityAppController".  If they exist, the files are probably in Plugins/iOS, but might not be.  You should find the GPGSAppController subclass.  If you find any other subclasses, that might be the problem.

**Comment by ankitak71** [comment]
@colinamuzo thank u so much. resolved issue.
