### ISSUE TITLE
My game  Leaderboard all ios user hidden

### ISSUE THREAD

**Issue by ChronicArt** [playgameservices/play-games-plugin-for-unity#1045]
hello my game name is "Run Beach" for android and IOS

IOS user score upload success

but all ios user hidden

is that bug?

please take care ios users. they can not see their rank through leaderboard

**Comment by ChronicArt** [comment]
plugin version 0.31a

**Comment by pokekingvn** [comment]
don't know where to ask, can anyone tell me in iOS, we will log in by Apple ID or Google ID?

**Comment by claywilkinson** [comment]
Yes this is a known issue on iOS: https://developers.google.com/games/services/ios/knownIssues
