### ISSUE TITLE
Cant authorized with Google play services

### ISSUE THREAD

**Issue by bar2016** [playgameservices/play-games-plugin-for-unity#1046]
```
` 03-12 04:36:27.737 7808-7936/? I/GamesNativeSDK: Auth operation started: SIGN IN
03-12 04:36:27.737 7808-7936/? I/GamesNativeSDK: Connecting to Google Play...
03-12 04:36:27.737 7808-7936/? E/GamesNativeSDK: Not authorizing: no client.
03-12 04:36:27.737 7808-7919/? I/Unity:  [Play Games Plugin DLL] 03/12/16 4:36:27 +02:00    
                                                                             DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
                                         
                                        (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
03-12 04:36:27.737 7808-7919/? I/Unity: AuthState == Unauthenticated calling auth callbacks with failure
                                         
                                        (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
03-12 04:36:27.757 7808-7827/? I/Unity:  [Play Games Plugin DLL] 03/12/16 4:36:27 +02:00 DEBUG: Invoking user callback on game thread
                                         
                                        (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
03-12 04:36:27.757 7808-7827/? I/Unity: Login failed for some reason
                                         
                                        (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)`
```

I got this logcat , well i searched for a solution.
things that i did:
1.Checked that i had a tester enabled.
2.Latest version of Google game serveices on SDK Manager which is now 29.
3.I took a project of Shawn who made a tutorial 21:40 min long about this a year ago.
4.double checked resources for the android setup.
5.i found a problem with the plugin, without the lib folder of Google play services which called:
google-play-services_lib , it wont let me build, and every time that i build it removes the folder and i need to add it again.
6.i am ussing a keystore.
7.i am not using the latest version of unity i am using the one before 5.2.2f1
Thats it i re-checked every thing, hope to get help,
the loading circle even wont show up.
Thanks so much!

btw this is the c# code:
`using UnityEngine;
using System.Collections;
using GooglePlayGames;
using UnityEngine.SocialPlatforms;

public class testGPGMenu : MonoBehaviour
{
	
	public GUISkin skin;
	public int incrementalCount = 5;
	
	//leaderboard strings
	private string leaderboard = "CgkI-J6Sno0VEAIQBg";
	//achievement strings
	private string achievement = "CgkI-J6Sno0VEAIQAQ";
	private string incremental = "no need just need to make sure that i can login";
	
	// Use this for initialization
	void Start()
	{
		PlayGamesPlatform.Activate();
		PlayGamesPlatform.DebugLogEnabled = true;
	}
	
	// Update is called once per frame
	public void OnGUI()
	{
		GUI.skin = skin;
		skin.button.fixedWidth = Screen.width - 25;
		skin.textField.fixedWidth = Screen.width - 25;
		GUILayout.BeginArea(new Rect(0, 0, Screen.width, Screen.height));
		
		GUILayout.BeginVertical("box");
		
		GUILayout.Label("Official Google Play Games Services");
		
		GUILayout.Space(20);
		
		//Share Status
		if (GUILayout.Button("Log In"))
		{
			Social.localUser.Authenticate((bool success) =>
			                              {
				if (success)
				{
					Debug.Log("You've successfully logged in");
				}
				else
				{
					Debug.Log("Login failed for some reason");
				}
			});
		}
		
		GUILayout.Space(20);
		
		//Achievement
		if (GUILayout.Button("Unlock Achievement"))
		{
			if (Social.localUser.authenticated)
			{
				Social.ReportProgress(achievement, 100.0f, (bool success) =>
				                      {
					if (success)
					{
						Debug.Log("You've successfully logged in");
					}
					else
					{
						Debug.Log("Login failed for some reason");
					}
				});
			}
		}
		
		GUILayout.Space(20);
		
		//Incremental Achievement
		if (GUILayout.Button("Press " + incrementalCount + "more times to unlock incremental acheivment"))
		{
			if (Social.localUser.authenticated)
			{
				((PlayGamesPlatform)Social.Active).IncrementAchievement(incremental, 5, (bool success) =>
				                                                        {
					//The achievement unlocked successfully
				});
			}
		}
		
		GUILayout.Space(20);
		
		//Leaderboard
		if (GUILayout.Button("Post your 5000 points to the leaderboard"))
		{
			if (Social.localUser.authenticated)
			{
				Social.ReportScore(5000, leaderboard, (bool success) =>
				                   {
					if (success)
					{
						((PlayGamesPlatform)Social.Active).ShowLeaderboardUI(leaderboard);
					}
					else
					{
						//Debug.Log("Login failed for some reason");
					}
				});
			}
		}
		
		GUILayout.Space(20);
		
		// Show Leaderboard
		if (GUILayout.Button("Show Leaderboard"))
		{
			Social.ShowLeaderboardUI();
		}
		
		GUILayout.Space(20);
		
		//Show Specific Leaderboard
		if (GUILayout.Button("Show Specific Leaderboard"))
		{
			((PlayGamesPlatform)Social.Active).ShowLeaderboardUI(leaderboard);
		}
		
		GUILayout.Space(20);
		
		//Show Achievments
		if (GUILayout.Button("Show Achievments"))
		{
			Social.ShowAchievementsUI();
		}
		
		GUILayout.Space(20);
		
		//Sign Out
		if (GUILayout.Button("Sign Out"))
		{
			((PlayGamesPlatform)Social.Active).SignOut();
		}
		
		GUILayout.EndVertical();
		GUILayout.EndArea();
	}
}`

**Comment by skwkddkemf** [comment]
It is an error similar to me.

**Comment by bar2016** [comment]
thats a common one, but o dod exacly as my friend did, and his one works perfect and on mne its still makes the error

**Comment by skwkddkemf** [comment]
In my case it was an error creating an Eclipse project in Unity .

**Comment by bar2016** [comment]
@skwkddkemf 
Well i found a solution, i just changed my sdk , i remove all of it and re-installed,
to be more accurate i just formated my computer , backed up all of my projects and keystores,
after format, i installed everything(Java,JDK,Unity) , and SDK stand-alone,
and i used the same code , from the back up and its worked :)
hope it will help someone!
i think the problem was that i had like three SDKs so.. it could be anything but i think if someone have the same problem as i did, just make sure you completly remove the sdk , and download it stand-alone.

**Comment by claywilkinson** [comment]
We don't support using Eclipse any longer.  I posted a comment documenting how I exported a project out of Unity into Android Studio that should help: https://github.com/playgameservices/play-games-plugin-for-unity/issues/925#issuecomment-175906294
