### ISSUE TITLE
[Emergency]When you run the APK After Export in Unity3D, an error will occur.

### ISSUE THREAD

**Issue by skwkddkemf** [playgameservices/play-games-plugin-for-unity#1047]
1. If the Build And Run in Unity is not an error.
2.  After the problem without any login and leader board, it was confirmed that it is running, to create the Eclipse project of unity. (Export)
3. Export in the project only, an error similar to the following will occur.
   1. Under, is the error log.
   2. I would like to be sure to resolve error.
   3. All of the Android SDK, is the latest version.
4.  I am using the GooglePlayGamesPlugin-0.9.32.
5.  I am using the Unity 5.3.2 p2
6. I made an effort to try to resolve in the following way.
   1. In order to solve the problem
      Code such as the following: Active (); gave the above input.
      PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder (). EnableSavedGames (). Build ();
      PlayGamesPlatform.InitializeInstance (config);
      However, the problem is not resolved in this way.
   2.  Tests were carried out in the version of the old-version in the 0.9.15 and 0.9.21, but had not been resolved.
7. It is a plug-in folder that I have.

![plugins](https://cloud.githubusercontent.com/assets/17810433/13728512/ef5c2a8c-e95e-11e5-8704-3864a2d4adc8.png)
1. Because there is no Google-play-service when you export, an error has occurred, they told me to put the latest version google-play-service folder to Plugins / Android. 
   1. Is this a good idea?
   2. No way, or you can have problems because of this? 
2. Please help anyone you started to know, Plz
3. The following is the entire script.

[Script.zip](https://github.com/playgameservices/play-games-plugin-for-unity/files/170955/Script.zip)

**11. I dont know ....  Importantly, only at the time of the build in Eclipse, such an error will occur. In our game, sure, you need to build Eclipse. Help me.**

12 **Please help me.**

-----------------------------------------Error Log -----------------------------------
03-13 17:12:09.427: I/Unity(28416): Building GPG services, implicitly attempts silent auth 
03-13 17:12:09.427: I/Unity(28416):  
03-13 17:12:09.427: I/Unity(28416): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37) 
03-13 17:12:09.437: I/Unity(28416): InvalidOperationException: There was an err
03-13 17:12:09.437: I/Unity(28416):  at GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build (GooglePlayGames.Native.PInvoke.PlatformConfiguration configRef) [0x00000] in <filename unknown>:0 
03-13 17:12:09.437: I/Unity(28416):  at GooglePlayGames.Native.NativeClient.InitializeGameServices () [0x00000] in <filename unknown>:0 
03-13 17:12:09.437: I/Unity(28416):  at GooglePlayGames.Native.NativeClient.Authenticate (System.Action`1 callback, Boolean silent) [0x00000] in <filename unknown>:0 
03-13 17:12:09.437: I/Unity(28416):  at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`1 callback, Boolean silent) [0x00000] in <filename unknown>:0 
03-13 17:12:09.437: I/Unity(28416):  at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`1 callback) [0x00000] in <filename unknown>:0 
03-13 17:12:09.437: I/Unity(28416):  at GooglePlayGames.PlayGamesLocalUser.Authenticate (System.Action`1 callback) [0x00000] in <filename unknown>:0 
03-13 17:12:09.437: I/Unity(28416):  at GPGSMng.LoginGPGS () [0x00000] in <filename unknown>:0 
03-13 17:12:09.437: I/Unity(28416):  at GPGSBtn2.ClickEvent () [0x00000] in <filename unknown>:

**Comment by claywilkinson** [comment]
There is more info in the log (such as cause of the error).  Can you share that as well?

The c# code that works when you build using Build & Run should not need to be changed if you are building externally.

I have not tried to build in Eclipse in a long time (I use Android Studio).  Some hints might be found in 
https://github.com/playgameservices/play-games-plugin-for-unity/issues/925#issuecomment-175906294.

**Comment by skwkddkemf** [comment]
It all logs that were me up is. So, too stuffy  :'-(

Error log to use GPGS is, it is and all, I'll raised if necessary the entire project.

In your unity, after Export, if progress a build in Import to Android studio, do you go back usually well?

**Comment by claywilkinson** [comment]
@skwkddkemf - I have no idea what you are saying in your response.  The problem will be in the log just before the Unity log message.  You'll need to view the entire log, not just the Unity topic.

**Comment by claywilkinson** [comment]
OK to close this one?
