### ISSUE TITLE
Avoid reporting same score for different user

### ISSUE THREAD

**Issue by CongTung** [playgameservices/play-games-plugin-for-unity#1048]
Hi, i'm going to make a leaderboard in game with Game Services, and i follow tutorial in here: http://shaneobrien.ie/official-google-play-game-services-plugin/
I show successfully like video, but the point is in tutorial, they reported "5000 point" to the leaderboard...
So i created 2 script in other scene to get point to test:
`using UnityEngine;
using System.Collections;

public class Common : MonoBehaviour {
	public static int score = 0;`

and: 
`using UnityEngine;
using System.Collections;
using GooglePlayGames;
using UnityEngine.SocialPlatforms;

public class testGPGMenu : MonoBehaviour
{

  // Update is called once per frame
  public void OnGUI()
  {
    GUI.skin = skin;
    skin.button.fixedWidth = Screen.width - 25;
    skin.textField.fixedWidth = Screen.width - 25;
    GUILayout.BeginArea(new Rect(0, 0, Screen.width, Screen.height));

    GUILayout.BeginVertical("box");

    GUILayout.Label("Official Google Play Games Services");

    GUILayout.Space(20);

    //Share Status
    if (GUILayout.Button("getScore1"))
    {
     Common.score += 100;
    }

    GUILayout.Space(20);

    //Achievement
    if (GUILayout.Button("getScore2"))
    {
 Common.score += 300;
    }

    GUILayout.Space(20);

    if (GUILayout.Button("getScore3"))
    {
 Common.score += 500;
    }

    GUILayout.Space(20);

    if (GUILayout.Button("postScore"))
    {
Application.LoadLevel(1);
    }

    GUILayout.Space(20);`

And here my code:
`using UnityEngine;
using System.Collections;
using GooglePlayGames;
using UnityEngine.SocialPlatforms;

public class testGPGMenu : MonoBehaviour
{

  public GUISkin skin;
private int score;
  //leaderboard strings
  private string leaderboard = "Your unique leaderboard id";

  // Use this for initialization
  void Start()
  {
    PlayGamesPlatform.Activate();
score = Common.score;
  }

  // Update is called once per frame
  public void OnGUI()
  {
    GUI.skin = skin;
    skin.button.fixedWidth = Screen.width - 25;
    skin.textField.fixedWidth = Screen.width - 25;
    GUILayout.BeginArea(new Rect(0, 0, Screen.width, Screen.height));

    GUILayout.BeginVertical("box");

    GUILayout.Label("Official Google Play Games Services");

    GUILayout.Space(20);

    //Share Status
    if (GUILayout.Button("Log In"))
    {
      Social.localUser.Authenticate((bool success) =>
      {
        if (success)
        {
          Debug.Log("You've successfully logged in");
        }
        else
        {
          Debug.Log("Login failed for some reason");
        }
      });
    }

    GUILayout.Space(20);

    if (GUILayout.Button("getScore"))
    {
Application.LoadLevel(1);
    }

    GUILayout.Space(20);

    //Leaderboard
    if (GUILayout.Button("Leaderboard"))
    {
      if (Social.localUser.authenticated)
      {
        Social.ReportScore(score, leaderboard, (bool success) =>
        {
          if (success)
          {
            ((PlayGamesPlatform)Social.Active).ShowLeaderboardUI(leaderboard);
          }
          else
          {
            //Debug.Log("Login failed for some reason");
          }
        });
      }
    }

    GUILayout.Space(20);

    // Show Leaderboard
    if (GUILayout.Button("Show Leaderboard"))
    {
      Social.ShowLeaderboardUI();
    }

    GUILayout.Space(20);

    //Show Specific Leaderboard
    if (GUILayout.Button("Show Specific Leaderboard"))
    {
      ((PlayGamesPlatform)Social.Active).ShowLeaderboardUI(leaderboard);
    }

    GUILayout.Space(20);

    //Show Achievments
    if (GUILayout.Button("Show Achievments"))
    {
      Social.ShowAchievementsUI();
    }

    GUILayout.Space(20);

    //Sign Out
    if (GUILayout.Button("Sign Out"))
    {
      ((PlayGamesPlatform)Social.Active).SignOut();
    }

    GUILayout.EndVertical();
    GUILayout.EndArea();
  }
}
`

When i played, i got score = 500 for account A, and i log out and sign in with account B. After signing in, i press "Show Leaderboard" button, the score off account B is 0, but when i press "Leaderboard" button (to report score), account B's score = 500. It should be 0, right?
So how can i avoid that situation? Or i'm still missing someway to check ID of user?
Please show me how can i fix it.

**Comment by aditya2** [comment]
you can consider this section getting leader board data and can use it to check scores ... https://github.com/playgameservices/play-games-plugin-for-unity#user-content-accessing-leaderboard-data

**Comment by claywilkinson** [comment]
OK to close this one?  The bottom line is the the score is submitted for the currently authenticated player.  If you want to submit a score for a specific player, you need to authenticate as that player.
