### ISSUE TITLE
[iOS] Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by boon2537** [playgameservices/play-games-plugin-for-unity#1049]
Hey, I am encountering this linker errors: 

Undefined symbols for architecture arm64:
 "_OBJC_CLASS_$_GPPURLHandler", referenced from:
      objc-class-ref in GPGSAppController.o
  "__GooglePlayEnableProfileScope", referenced from:
      _IOSClient__GooglePlayEnableProfileScope_m849803398 in Bulk_Assembly-CSharp_2.o
      _IOSClient_CreatePlatformConfiguration_m128452816 in Bulk_Assembly-CSharp_2.o
     (maybe you meant: _IOSClient__GooglePlayEnableProfileScope_m849803398)
  "__GooglePlayGetIdToken", referenced from:
      _IOSTokenClient__GooglePlayGetIdToken_m2363444920 in Bulk_Assembly-CSharp_2.o
     (maybe you meant: _IOSTokenClient__GooglePlayGetIdToken_m2363444920)
  "__GooglePlayGetUserEmail", referenced from:
      _IOSTokenClient__GooglePlayGetUserEmail_m1616690347 in Bulk_Assembly-CSharp_2.o
     (maybe you meant: _IOSTokenClient__GooglePlayGetUserEmail_m1616690347)
  "_UnpauseUnityPlayer", referenced from:
      _NativeClient_HandleAuthTransition_m1148397502 in Bulk_Assembly-CSharp_3.o
      _NativeClient_UnpauseUnityPlayer_m2362960465 in Bulk_Assembly-CSharp_3.o
     (maybe you meant: _NativeClient_UnpauseUnityPlayer_m2362960465)
  "__GooglePlayGetAccessToken", referenced from:
      _IOSTokenClient__GooglePlayGetAccessToken_m2071133647 in Bulk_Assembly-CSharp_2.o
     (maybe you meant: _IOSTokenClient__GooglePlayGetAccessToken_m2071133647)
ld: symbol(s) not found for architecture arm64

The first time I tried to build with Cocoapods, I kept getting GooglePlus/GooglePlus.h file not found. So, I built the project without Cocoapods and disable Bitcode. Then, I'm stuck with the above linker error. Later, I tried to build with Cocoapods again. I fixed the GooglePlus/GooglePlus.h file not found issue by copying GooglePlus.bundle and GooglePlus.framework over to google-plus-ios-sdk-1.7.1 folder in Pods. Then I had to disable Bitcode, and still get the above linker error. I'm at wit's end here; I would really appreciate a solution.

Thanks for hearing me out!

**Comment by sorab2142** [comment]
Are you building the project with IL2CPP enabled, and Architecture set to Universal? 
With the latest version of the plugin, it performs the necessary pod related stuff, so I would suggest trying it with that.

**Comment by claywilkinson** [comment]
It sounds like you have an old GPGSAppController.mm in your project?  GPP* are Google Plus APIs, which are not used any longer.
Your file should look like:
https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/Plugins/iOS/GPGSAppController.mm

**Comment by boon2537** [comment]
Yeah, somehow GPGSAppController.mm was not updated when I updated the plugin. It's working fine how. Thanks for the help!

**Comment by claywilkinson** [comment]
Great! Glad you got it working.

**Comment by dennisgl1** [comment]
![sc](https://user-images.githubusercontent.com/26596060/42370675-90b11b46-8137-11e8-9bd2-af43c08ae323.png)

I have the same issues. I'm using iOSNativeShare plugin and in xcode it shows the same error saying that ShowSocialSharing is undefined in arm64 architecture.

I'm using unity 2018.1.6f1
architecture universal
IL2CPP
