### ISSUE TITLE
What should be done to get latest match object in ios ??

### ISSUE THREAD

**Issue by melayerjohn** [playgameservices/play-games-plugin-for-unity#1052]
Hi I am doing turnbased game , which on android works good ,it means when i took turn , on other device  it is transfered well , i get match in OnGotMatch(). I parse data from it. On android i dont need to go through 'match inbox' to get match.All good.
But on ios i have to go through 'match inbox' i.e.call method 'AcceptFromInbox' and have to select match turn , then only i am getting new match object and data.
Is there any way to avoid 'AcceptFromInbox' method and directly get match in ios ??

Why is this difference in android an ios behaviour ??

**Comment by melayerjohn** [comment]
Let me ask in other way..
match delegate is giving immediate turn data of other player on android on other player turn completion,
but on ios match delegate is not giving other player's match data directly, 
unless i call methed 'AcceptFromInbox' which is on button click on buttton click.

For turn based player is their any way to get response of match delegate directly on ios...??
Please give annnnyy clue on it.....

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
