### ISSUE TITLE
NO_GPGS causes Errors in Xcode

### ISSUE THREAD

**Issue by artakino** [playgameservices/play-games-plugin-for-unity#1054]
I'm using NO_GPGS to exclude gpgs from IOS build and I'm getting errors when building Xcode project.
It seems like even with NO_GPGS it still includes certain files.  Here are couple of screenshots of the error messages and included files.

![screen shot 2016-03-15 at 7 32 55 pm](https://cloud.githubusercontent.com/assets/17559833/13800345/b51293ce-eae5-11e5-9c70-fff3acc86fe5.png)
![screen shot 2016-03-15 at 7 38 44 pm](https://cloud.githubusercontent.com/assets/17559833/13800346/b7de5a7a-eae5-11e5-8c85-a1d9a24d829d.png)

It also creates a Podfile in the project folder although it doesn't show up in the Xcode project.  If I delete these files, I get a lot more errors.  I'm using version 0.9.32.  Any ideas how I could fix this?

**Comment by claywilkinson** [comment]
NO_GPGS only affects the Google Play Game Services (GPGS) plugin files.  The files GAD* are from admob, right?  I'd suggest filing an issue with that project to see if they do something similar.  In the meantime, you could just remove those files from the xcode project if you are not using them.

**Comment by artakino** [comment]
Thanks a lot Clay, I didn't realize those were part of admob.

**Comment by claywilkinson** [comment]
You're welcome!
