### ISSUE TITLE
IOS Offline Login does not work anymore

### ISSUE THREAD

**Issue by sorab2142** [playgameservices/play-games-plugin-for-unity#1055]
Once the player has successfully logged in once, previously (as of 0.9.30) they were able to login even though they were offline. This still works fine on Android but on IOS it is not working anymore. Any ideas why?

**Comment by claywilkinson** [comment]
iOS needs to access the server in order to authenticate the user each time.  Sometimes if the credentials are cached, can implicitly refresh the token, but it always needs a connection to the server.
