### ISSUE TITLE
Google Play Gamer ID support

### ISSUE THREAD

**Issue by SingleMalt** [playgameservices/play-games-plugin-for-unity#1058]
With the announcement that Android now [supports gamer IDs](http://officialandroid.blogspot.com/2016/02/embrace-your-inner-gaming-hero-with.html), can I use this library to get them? If not, I'd like to request it :+1: 

Thanks!

**Comment by claywilkinson** [comment]
Yes, this plugin will work with gamer IDs.  The support is included in the Play Games App - which gets updated independently of the SDK, so it should show up as an update shortly (if you don't already have it).

**Comment by SingleMalt** [comment]
Perfect, thanks!
