### ISSUE TITLE
Saved Games Data Google Play Games Serivces Unity

### ISSUE THREAD

**Issue by jojonitta** [playgameservices/play-games-plugin-for-unity#1060]
Hello; 
i ve successfully logged in with Google Play services in Unity, but i have a proble now that i have a class that contains some data like this:

`using UnityEngine;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

public static class GameData
{
    
    public static Dictionary<string, object> Name_Dic = new Dictionary<string, object>() 
    {
        {"laura",""},
        {"steph ",""},
        {"Ryan",""},      
    };
    public static Dictionary<string, string> Dialogs_Dic = new Dictionary<string, string>() 
    {
        {"A1", "Hello"},
        {"A2", "Nice"},
        {"A3", "Test"},
     };
    public const int nbrTotal_Int = 2;
    public const int TestNumber_Int = 5;
}

I have to save these data to the Google Cloud and after that load them from cloud, but i  m confused i don't understand if i have to convert the dictionary in the GameManager class into String and then in to Bytes[] in order to save them in the Google Cloud or what can i do exactly. and the int variables i should convert them into string then into bytes[]. i ve searched into the internet and i can't found an explanation or tutorial for that and in the official documentation or the samples in the documentation it is not clear what can i do. Can you please help me please. Thanks a lot

**Comment by claywilkinson** [comment]
Saved Games API accepts a byte array.  You don't necessarily need to convert your data to a string then to bytes, you can go directly to bytes.  For example you can you the BinaryFormatter to serialize any object that is a Serializable type. (I believe Dictionary is Serializable).
```
byte[] ToBytes(Dictionary<string, string> data) {
BinaryFormatter bf = new BinaryFormatter();
MemoryStream m = new MemoryStream();
            bf.Serialize(m, data); 
            m.Flush();
            return m.ToArray();
}
```

**Comment by jojonitta** [comment]
Hello, 
Thanks for your answer, i ve written a code that let me save these variables to Google Cloud, here it is a part of the serialization the dictionary and the ints. is it correct like this. thanks for your answer.

`using UnityEngine;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;

public class Connect : MonoBehaviour 
{
	public  Dictionary<string, object> Name_Dic = new Dictionary<string, object>() 
	{
		{"laura",""},
		{"steph ",""},
		{"Ryan",""},      
	};
	public  Dictionary<string, string> Dialogs_Dic = new Dictionary<string, string>() 
	{
		{"A1", "Hello"},
		{"A2", "Nice"},
		{"A3", "Test"},
	};
	public  int nbrTotal_Int = 2;
	public  int TestNumber_Int = 5;


public void WriteFunction() {
        
        ISavedGameMetadata currentGame = null;

      
        Action<SavedGameRequestStatus, ISavedGameMetadata> writeCallback = 
        (SavedGameRequestStatus status, ISavedGameMetadata game) => {
            Debug.Log(" Saved Game Write: " + status.ToString());
        };

        // CALLBACK: Handle the result of a binary read
        Action<SavedGameRequestStatus, byte[]> readBinaryCallback = 
        (SavedGameRequestStatus status, byte[] data) => 
		{
            Debug.Log(" Saved Game Binary Read: " + status.ToString());
            if (status == SavedGameRequestStatus.Success) 
			{
                
                try {
                    BinaryFormatter bf = new BinaryFormatter();
					FileStream file = File.Open(Application.persistentDataPath + "/gameInfo.dat",
												FileMode.Open);
					
					GameData data = new GameData();
					// Two Dictionary 
					data.Name_Dic = Name_Dic;
					data.Dialogs_Dic = Dialogs_Dic;
					// Two Int
					data.nbrTotal_Int = nbrTotal_Int;
					data.TestNumber_Int = TestNumber_Int;

					bf.Serialize(file, data);
					file.Close();
                } catch (Exception e) {
                    Debug.Log(" Saved Game Write: convert exception");
                }
                WriteSavedGame(currentGame, data, writeCallback);
            }
        };
        
    }
	}
	
	[Serializable]
public  class GameData 
{
	public  Dictionary<string, object> Name_Dic = new Dictionary<string, object>() 
	{
		{"laura",""},
		{"steph ",""},
		{"Ryan",""},      
	};
	public  Dictionary<string, string> Dialogs_Dic = new Dictionary<string, string>() 
	{
		{"A1", "Hello"},
		{"A2", "Nice"},
		{"A3", "Test"},
	};
	public  int nbrTotal_Int = 2;
	public  int TestNumber_Int = 5;
}`

**Comment by claywilkinson** [comment]
Great! I'd suggest adding a version key to the saved data that way if you change the data being saved in a newer version of the game, you can detect old saved data and handle it appropriately.

**Comment by jojonitta** [comment]
hello,
Thanks for your answer, i would like to know if the code that i write is correct does it let me save my variables in the class GameData in the Google Cloud and can you please tell me how can i add a version key to the saved data? Thank you

**Comment by claywilkinson** [comment]
File.Open is writing a file to the device - it won't be available on other devices, nor if the game is uninstalled.  You should not need to do that if you are using the Saved Games API.  You can replace the FileStream with a MemoryStream to serialize into a byte array to write out to the SavedGame API.

You can add another property to GameData for the version number (if you want, it is not required).

**Comment by jojonitta** [comment]
Hello,

Thanks again for your answer, here is the new code , i ve changed this line from data to dataGame "GameData data = new GameData();" to this " GameData dataGame = new GameData();" but in this line "WriteSavedGame(currentGame, data, writeCallback);" to this "WriteSavedGame(currentGame, dataGame , writeCallback);". it tells me " Argument `#2' cannot convert `object' expression to type `byte[]'", here is the code. 
Thanks again
``using UnityEngine;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;

public class Connect : MonoBehaviour 
{
public Dictionary Name_Dic = new Dictionary() 
{
{"laura",""},
{"steph ",""},
{"Ryan",""},

};
public Dictionary Dialogs_Dic = new Dictionary() 
{
{"A1", "Hello"},
{"A2", "Nice"},
{"A3", "Test"},
};
public int nbrTotal_Int = 2;
public int TestNumber_Int = 5;

public void WriteFunction() {

    ISavedGameMetadata currentGame = null;


    Action<SavedGameRequestStatus, ISavedGameMetadata> writeCallback = 
    (SavedGameRequestStatus status, ISavedGameMetadata game) => {
        Debug.Log(" Saved Game Write: " + status.ToString());
    };

    // CALLBACK: Handle the result of a binary read
    Action<SavedGameRequestStatus, byte[]> readBinaryCallback = 
    (SavedGameRequestStatus status, byte[] data) => 
    {
        Debug.Log(" Saved Game Binary Read: " + status.ToString());
        if (status == SavedGameRequestStatus.Success) 
        {

            try {
                BinaryFormatter bf = new BinaryFormatter();
                FileStream file = File.Open(Application.persistentDataPath + "/gameInfo.dat",
                                            FileMode.Open);

                GameData dataGame = new GameData();
                // Two Dictionary 
                dataGame.Name_Dic = Name_Dic;
                dataGame.Dialogs_Dic = Dialogs_Dic;
                // Two Int
                dataGame.nbrTotal_Int = nbrTotal_Int;
                dataGame.TestNumber_Int = TestNumber_Int;

                bf.Serialize(file, dataGame);
                file.Close();
            } catch (Exception e) {
                Debug.Log(" Saved Game Write: convert exception");
            }
            WriteSavedGame(currentGame, data, writeCallback);
        }
    };

}
}

[Serializable]
public class GameData 
{
public Dictionary Name_Dic = new Dictionary() 
{
{"laura",""},
{"steph ",""},
{"Ryan",""},

};
public Dictionary Dialogs_Dic = new Dictionary() 
{
{"A1", "Hello"},
{"A2", "Nice"},
{"A3", "Test"},
};
public int nbrTotal_Int = 2;
public int TestNumber_Int = 5;
}``

**Comment by claywilkinson** [comment]
Add this function to your class:
```
byte[] ToBytes(Dictionary<string, string> data) {
BinaryFormatter bf = new BinaryFormatter();
MemoryStream m = new MemoryStream();
            bf.Serialize(m, data); 
            m.Flush();
            return m.ToArray();
}
```
and  then call `WriteSavedGame(currentGame, ToBytes(data), writeCallback);`

**Comment by jojonitta** [comment]
The data in this function i can replace it with for example 
`byte[] ToBytes(Dictionary<string, string> Name_Dic ) {
BinaryFormatter bf = new BinaryFormatter();
MemoryStream m = new MemoryStream();
            bf.Serialize(m, Name_Dic ); 
            m.Flush();
            return m.ToArray();
}` and the call like this: WriteSavedGame(currentGame, ToBytes(data), writeCallback);

i have to add each variable in the serializable class GameData like this function ?

**Comment by claywilkinson** [comment]
The bytes are the entire GameData object.  To read it back from byte[] to Game Data use:

` GameData savedData = FromBytes<GameData>(byteData);`

```
    T FromBytes<T>(byte[] data)
    {
        System.Runtime.Serialization.Formatters.Binary.BinaryFormatter bf =
            new System.Runtime.Serialization.Formatters.Binary.BinaryFormatter();

        System.IO.MemoryStream mem = new System.IO.MemoryStream(data);
        return (T)bf.Deserialize(mem);
    }
```

**Comment by jojonitta** [comment]
Hello,
Thanks again for your answer, but im a little confused, i m using this code in order to Save my Game Data to Cloud, here is the link https://codelabs.developers.google.com/codelabs/playservices_unity/index.html?index=..%2F..%2Fgames#8 
but my problem where can i add the code that you provided to me in order to save my GameData class into Google Cloud and after that where can i put the code in order to load it from Google Cloud. Thanks
