### ISSUE TITLE
Crash on Intel processors

### ISSUE THREAD

**Issue by BloodJohn** [playgameservices/play-games-plugin-for-unity#1061]
My app works with GPGS, we have got stable Crash on all android devices based on Intel.
For example: ASUS MeMO Pad FHD; Asus FonePad 7 FE170CG​.

All crashed on x64.

03-21 12:54:56.938: I/Unity(7957): GooglePlayGames.Native.NativeClient:InitializeGameServices() (at D:\Projects\indikot-vk-and\Assets\GooglePlayGames\Platforms\Native\NativeClient.cs:196)
03-21 12:54:56.938: I/Unity(7957): GooglePlayGames.Native.NativeClient:Authenticate(Action`1, Boolean) (at D:\Projects\indikot-vk-and\Assets\GooglePlayGames\Platforms\Native\NativeClient.cs:130)
03-21 12:54:56.938: I/Unity(7957): GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at D:\Projects\indikot-vk-and\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:368)
03-21 12:54:56.938: I/Unity(7957): GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at D:\Projects\indikot-vk-and\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:337)
03-21 12:54:56.938: I/Unity(7957): GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at D:\Projects\indikot-vk-and\Assets\GooglePlayGames\ISocialPlatform\PlayGamesLocalUser.cs:49)
03-21 12:54:56.938: I/Unity(7957): Main:Start() (at D:\Projects\indikot-vk-and\Assets\Game\Scripts\Game\Scenes\Main\Main.cs:171)
03-21 12:54:56.938: I/Unity(7957):  
03-21 12:54:56.938: I/Unity(7957): (Filen
03-21 12:54:56.938: D/dalvikvm(7957): Trying to load lib /data/app-lib/com.playflock.indianacat-1/libgpg.so 0x43518240
03-21 12:54:56.938: D/dalvikvm(7957): Shared lib '/data/app-lib/com.playflock.indianacat-1/libgpg.so' already loaded in same CL 0x43518240
03-21 12:54:56.938: V/GamesNativeSDK(7957): Using classes from /data/data/com.playflock.indianacat/app_.gpg.classloader/d75c8e1bbeab9e1ddffb9d332585db71.jar.
03-21 12:54:56.948: W/PopupManager(7957): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments

**Comment by claywilkinson** [comment]
Can you share the crash or bugreport?  The log snippet posted does not have the crash in it.

**Comment by BloodJohn** [comment]
[crashReport.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/183657/crashReport.txt)

I hope that this will really help you to fix.

**Comment by claywilkinson** [comment]
I don't see any Play Game Services being called in the log.   It does look like something is up with trialpay?  
```
03-22 10:30:17.097: D/UnityAds(24319): com.unity3d.ads.android.webapp.UnityAdsWebData.a() (line:401) :: Starting next URL loader
03-22 10:30:17.107: I/dalvikvm(24319): Could not find method android.provider.Telephony$Sms.getDefaultSmsPackage, referenced from method **com.trialpay.android.Utils.openSms**
03-22 10:30:17.107: W/dalvikvm(24319): VFY: unable to resolve static method 1267: Landroid/provider/Telephony$Sms;.getDefaultSmsPackage (Landroid/content/Context;)Ljava/lang/String;
03-22 10:30:17.107: D/dalvikvm(24319): VFY: replacing opcode 0x71 at 0x0006
03-22 10:30:17.127: V/Trialpay.GaidResolver(24319): gaid=82d91458-6e73-42a2-b8bd-9c29d5031093
03-22 10:30:17.127: V/Trialpay.GaidResolver(24319): isTrackingEnabled=true
03-22 10:30:17.147: A/chromium_net(24319): external/chromium/base/threading/thread_local_posix.cc:18: [0322/103017:FATAL:thread_local_posix.cc(18)] Check failed: error == 0 (11 vs. 0)
03-22 10:30:17.147: A/libc(24319): **Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 24364 (WebViewCoreThre)**
03-22 10:30:17.157: V/Trialpay.UrlManager(24319): ua=Mozilla/5.0 (Linux; U; Android 4.3; en-gb; ME302C Build/JSS15Q) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
```

**Comment by BloodJohn** [comment]
https://github.com/trialpay

another report with disabled trialpay:

[crashReport2.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/186272/crashReport2.txt)

**Comment by claywilkinson** [comment]
It looks like there definitely is an issue loading libgpg.so.  You can make sure that Assets/Plugins/Android/libs/x86/libgpg.so is being included in your apk.  Are you building directly from Unity?  Make sure you have the correct device filter set - (FAT or x86).

**Comment by BloodJohn** [comment]
I have two libs in my project:
1) Assets\Plugins\Android\libs\armeabi-v7a\libgpg.so 1684372 byte
2) Assets\Plugins\Android\libs\x86\libgpg.so 2634460 byte

I'm building directly from Unity 4.7.0f1

Device filter set on "FAT(ARMv 7+x 86)"

**Comment by BloodJohn** [comment]
I isolated the problem. the fall happens when I use Cloud Save in GPGS:

```
Debug.Log("PlayGamesPlatform.Instance.SavedGame");
ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame;
```

[crashReport3.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/187788/crashReport3.txt)

**Comment by BloodJohn** [comment]
[crashReport5.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/188106/crashReport5.txt)

**Comment by claywilkinson** [comment]
I don't see anything obvious - but you are using Prime31 - did you check with them? 
`Force finishing activity com.playflock.indicatfb/com.prime31.UnityPlayerNativeActivity`

I don't have problems with x86 locally - can you try to build one of the samples from this repo without any additional plugins?

**Comment by claywilkinson** [comment]
Closing this log, since there was no more information in over a year. Please open a new issue including logs of the crash if there is still a problem. Thanks!
