### ISSUE TITLE
IOS only. Invite Google contact to match function built in UI doesnt load contacts anymore.

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#1062]
The built in UI comes up but I can only select autopick or type in the search field (no friends/contacts comes up). Im not sure if this issue started with 0.9.32 or 31 since I havnt tested this function in a while... On Android everything works well.

**Comment by claywilkinson** [comment]
This is a known limitation on iOS in the Game Services SDK, not specific to the plugin. I don't know when it will be fixed, but I will update the thread when I know more.

**Comment by Hoffa25** [comment]
Ok thats bad news:/ Strange since it has been working fine on my ios app for about 6-7 months until now...

**Comment by Hoffa25** [comment]
Not being able to invite opponents anymore is a big problem for my game. I dont think I can launch it without that function :/ . Do you know the last sdk version that still had that function?

**Comment by claywilkinson** [comment]
Unfortunately, it is a server side change related to removing the Google Plus integration with Play Game Services.
