### ISSUE TITLE
Problem for import

### ISSUE THREAD

**Issue by BGolishchev** [playgameservices/play-games-plugin-for-unity#1064]
![i10 cimgpsh_orig](https://cloud.githubusercontent.com/assets/16481969/13951338/6bb4e2ca-f041-11e5-971f-8ced3486ecee.png)

Hello.
I have problem with your plugin. I need add achievements in my project. But immediately after the import, I encounter a problem. No Tabs dialog Window> Google Play Games> Setup ...> Android. How should I proceed?

**Comment by claywilkinson** [comment]
Can you change the target platform to be Android in File > Build Settings...? The menu items only appear if the platform is set to Android (or iOS). This makes it easier for designers/artists to work on assets without needing the plugin code.

**Comment by BGolishchev** [comment]
Thank you. Its work)

**Comment by claywilkinson** [comment]
Great!
