### ISSUE TITLE
play games plugin and soomla plugin 

### ISSUE THREAD

**Issue by WarrenMondeville** [playgameservices/play-games-plugin-for-unity#1066]
When I use play games plugin and soomla plugin in my project , google will change other plugin position if it's belong  to google.this operate will make wrong lead to oher plugin can't work .How can I solve this problem

**Comment by claywilkinson** [comment]
Can you give an example of the problem?  I am not  completely understanding your question.

**Comment by claywilkinson** [comment]
Did you get this resolved?  Is it OK to close this issue?

**Comment by WaDapeng** [comment]
no,I select delete google play games plugin when i publish to ios platform,because it will change other plugins position or delete other file automaticly.

**Comment by claywilkinson** [comment]
OK - you can also set NO_GPGS when you build for ios to exclude it from the build.  If you have time, can you share the issue you are seeing in Xcode with both plugins there?

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
