### ISSUE TITLE
LoadState - different data on different devices

### ISSUE THREAD

**Issue by blackrainbowgames** [playgameservices/play-games-plugin-for-unity#107]
I used cloud save in my app. Now I have state when I receive different data on different devices while cloud loading. Any ideas? I always used slot #0 and have no state conflicts.

UPD: Also I found that I receive the same data on single device when logged in as different accounts. I supposed it might be a cache issue or Social.localUser issue.

**Comment by claywilkinson** [comment]
LoadState is deprecated and being removed soon, so closing as obsolete.
