### ISSUE TITLE
App Crashes when I try to login 

### ISSUE THREAD

**Issue by XblakninjaX** [playgameservices/play-games-plugin-for-unity#1072]
When i put this line of code in `PlayGamesPlatform.Activate();` It crashes the app but when i dont have it in the app doesn't login even thought i have the unity social platform to login with.

`using UnityEngine;
using System.Collections;
using GooglePlayGames;
using UnityEngine.SocialPlatforms;

public class Login : MonoBehaviour {

    // Use this for initialization
    void Start()
    {
        PlayGamesPlatform.DebugLogEnabled = true;
        // Activate the Google Play Games platform
        PlayGamesPlatform.Activate();
        Social.localUser.Authenticate((bool success) =>
        {
            if (success)
            {
                Debug.Log("Login");
            }
            else {
                Debug.Log("No Login");
            }

        });
    }

  

    
}
`

**Comment by claywilkinson** [comment]
Can you share the log of the crash?  That will help a lot in knowing what is wrong.

**Comment by XblakninjaX** [comment]
i fixed it all i had to do was add the client id of the app in to the game

**Comment by claywilkinson** [comment]
Great! Glad you got it working.

**Comment by dotWasim** [comment]
I had same issue, adding client id fixed it. thanks @XblakninjaX

**Comment by SonicDirewolf** [comment]
@XblakninjaX  @dotWasim Can you please tell me how do you add a client id? Please, thank you so much
