### ISSUE TITLE
iOS create quick game not working

### ISSUE THREAD

**Issue by sillyatom** [playgameservices/play-games-plugin-for-unity#1074]
Unity Package - GooglePlayGamesPlugin-0.9.32
Device 1 - iOS 9.3
Device 2 - iOS 9.2
## Log

OnRoomSetupProgress - 20
ERROR: Attempting to get participant for invalid participant id.
ERROR: peer_capabilities must not be null in PeerStateMachine::WaitingForExpectedConnection
Entering internal callback for RealTimeEventListenerHelper#InternalOnRoomStatusChangedCallback
INFO: OP: 2
INFO: CALL_STATE_CHANGED_OP: New state: 2
ERROR: peer_capabilities must not be null in PeerStateMachine::WaitingForConnectionData

**Comment by sillyatom** [comment]
is there a update on this issue?

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
