### ISSUE TITLE
Save/Load game to cloud without SavedGame.ShowSelectSavedGameUI

### ISSUE THREAD

**Issue by koljanich** [playgameservices/play-games-plugin-for-unity#1077]
Hello! In other services, such as Parse, Photon Cloud, Yahoo Cloud and other, saving / loading without the interface provided. I need to save only one file and then read, why show the user to select the file? I have not found an example of load / store without this feature.

**Comment by VisalChhourm** [comment]
Hi!
You don't have to show the UI if you don't want to. I believe the [documentation](https://github.com/playgameservices/play-games-plugin-for-unity) at section **Saving Game State to the Cloud** already show you how to save the game. Just skip the **Displaying saved games UI** and start at **Opening a saved game**
Hope it'll help

**Comment by koljanich** [comment]
Ok, thanks, I try it and so:
` 
void Start()
    {
        PlayGamesPlatform.DebugLogEnabled = true;
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
            .EnableSavedGames()
                .Build();
        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.Activate();
Social.localUser.Authenticate((bool success) => {
            if (success) {
                LogIn = Social.localUser.userName;
                OpenSavedGame("Test"); //Code after not run
                //bla-bla-bla. This code do not run
            }//Debug.Log("Sucess AUTH");
            else
            {
            ErrorPanel.SetActive(true); ErrorPanel.GetComponentInChildren<Text>().text = "Error Enter Google Play";
            }
        });
}
void OpenSavedGame(string filename)
    {
        ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame;
        savedGameClient.OpenWithAutomaticConflictResolution(filename, DataSource.ReadCacheOrNetwork,
            ConflictResolutionStrategy.UseLongestPlaytime, OnSavedGameOpened);
    }

    public void OnSavedGameOpened(SavedGameRequestStatus status, ISavedGameMetadata game)
    {
        if (status == SavedGameRequestStatus.Success)
        {
            ErrorPanel.SetActive(true);   ///This panel not shows
            ErrorPanel.GetComponent<Text>().text = "Sucess save";
            // handle reading or writing of saved game.
        }
        else {
            // handle error
            ErrorPanel.SetActive(true); ///AND this not shows too!!!
            ErrorPanel.GetComponent<Text>().text = "UNSucess save";
        }
    }
`
adb.exe logcat *:E  

> E/Trace   (20463): error opening trace file: No such file or directory (2)
E/dalvikvm(20463): Could not find class 'android.os.UserManager', referenced fro
m method com.google.android.gms.common.zze.zzaq
E/dalvikvm(20463): Could not find class 'android.app.AppOpsManager', referenced
from method com.google.android.gms.common.zze.zzb
E/Trace   (20523): error opening trace file: No such file or directory (2)
E/dalvikvm(20523): Could not find class 'com.google.android.gms.common.permissio
n.PermissionUtils$1', referenced from method com.google.android.gms.chimera.GmsM
oduleInitializer.initializeModuleV0
E/dalvikvm(20523): Could not find class 'android.os.UserManager', referenced fro
m method com.google.android.gms.common.GooglePlayServicesUtilLight.isRestrictedU
serProfile
E/dalvikvm(20523): Could not find class 'android.app.AppOpsManager', referenced
from method com.google.android.gms.common.GooglePlayServicesUtilLight.uidHasPack
ageName
E/dalvikvm(20523): Could not find class 'android.graphics.drawable.RippleDrawabl
e', referenced from method com.google.android.gms.games.ui.util.UiUtils.construc
tButtonBackground
E/dalvikvm(20523): Could not find class 'android.app.usage.UsageStatsManager', r
eferenced from method com.google.android.gms.lockbox.LockboxService.a
E/AuthorizationBluetoothService(13390): Proximity feature is not enabled.
E/dalvikvm(20523): Could not find class 'android.app.AppOpsManager', referenced
from method com.google.android.gms.common.ou.a
E/dalvikvm(20523): Could not find class 'android.os.UserManager', referenced fro
m method com.google.android.gms.common.ou.p
E/dalvikvm(20523): Could not find class 'com.google.android.gms.common.j.c', ref
erenced from method com.google.android.gms.common.j.b.a
E/BaseAppContext(20523): Tried to stop global GMSCore RequestQueue. This is like
ly unintended, so ignoring.
E/Trace   (20566): error opening trace file: No such file or directory (2)
E/dalvikvm(20566): Could not find class 'android.os.UserManager', referenced fro
m method com.google.android.gms.common.GooglePlayServicesUtilLight.isRestrictedU
serProfile
E/dalvikvm(20566): Could not find class 'android.app.AppOpsManager', referenced
from method com.google.android.gms.common.GooglePlayServicesUtilLight.uidHasPack
ageName
E/dalvikvm(20566): Could not find class 'android.transition.Transition', referen
ced from method android.support.v4.app.BackStackRecord.captureExitingViews
E/dalvikvm(20566): Could not find class 'android.transition.Transition', referen
ced from method android.support.v4.app.BackStackRecord.configureTransitions
E/dalvikvm(20566): Could not find class 'android.transition.Transition', referen
ced from method android.support.v4.app.BackStackRecord.configureTransitions
E/dalvikvm(20566): Could not find class 'android.graphics.drawable.RippleDrawabl
e', referenced from method com.google.android.gms.games.ui.util.UiUtils.construc
tButtonBackground
E/ViewRootImpl(20566): Attempting to destroy the window while drawing!
E/ViewRootImpl(20566):   window=ViewRoot{42784058 ,ident = 1}, title=
E/dalvikvm(20566): Could not find class 'android.test.IsolatedContext', referenc
ed from method com.google.android.gms.games.util.PanoUtils.isPano
E/dalvikvm(20523): Could not find class 'android.test.IsolatedContext', referenc
ed from method com.google.android.gms.games.util.PanoUtils.isPano
E/NativeCrypto(19918): ssl=0x565bbdb8 cert_verify_callback x509_store_ctx=0x5647
eae8 arg=0x0
E/NativeCrypto(19918): ssl=0x565bbdb8 cert_verify_callback calling verifyCertifi
cateChain authMethod=ECDHE_RSA
E/DataBuffer(20523): Internal data leak within a DataBuffer object detected!  Be
 sure to explicitly call release() on all DataBuffer extending objects when you
are done with them. (internal object: com.google.android.gms.common.data.DataHol
der@429e6c78)
E/dalvikvm(20523): Could not find class 'com.google.android.gms.common.util.h',
referenced from method com.google.android.gms.common.util.e.a
E/dalvikvm(20523): Could not find class 'com.google.android.gms.common.util.g',
referenced from method com.google.android.gms.common.util.e.a
E/dalvikvm(20523): Could not find class 'android.os.UserManager', referenced fro
m method com.google.android.gms.common.util.a.c
E/dalvikvm(20523): Could not find class 'android.os.UserManager', referenced fro
m method com.google.android.gms.common.util.a.e
E/stp_dump(  128): table == NULL || table->table == NULL
E/stp_dump(  128): table == NULL || table->table == NULL
E/stp_dump(  128): table == NULL || table->table == NULL
E/stp_dump(  128): table == NULL || table->table == NULL
E/wpa_supplicant(  484): Sorted scan results
E/wpa_supplicant(  484): 10:fe:ed:62:12:b7 freq=2457 qual=0 noise=0 level=-65 fl
ags=0x2b
E/wpa_supplicant(  484): 64:70:02:5b:aa:48 freq=2437 qual=0 noise=0 level=-87 fl
ags=0xb
E/wpa_supplicant(  484): c8:3a:35:20:e4:11 freq=2462 qual=0 noise=0 level=-92 fl
ags=0xb
E/dalvikvm(20523): Could not find class 'com.google.android.gms.games.ui.GamesFr
agmentActivity$1', referenced from method com.google.android.gms.games.ui.GamesF
ragmentActivity.onCreate
E/GamesNativeSDK(20463): Exception in com/google/android/gms/games/snapshot/Snap
shots.load: java.lang.IllegalStateException: Cannot use snapshots without enabli
ng the 'Saved Game' feature in the Play console.
E/GamesNativeSDK(20463): Exception in com/google/android/gms/games/achievement/A
chievements.load: java.lang.NullPointerException: null reference.
E/dalvikvm(20523): Could not find class 'android.app.ActivityManager$TaskDescrip
tion', referenced from method com.google.android.gms.games.ui.GamesFragmentActiv
ity.updateTaskDescription
E/dalvikvm(20523): Could not find class 'android.hardware.display.DisplayManager
', referenced from method com.google.android.gms.games.ui.popup.manager.ContextM
anager.getContext

**Comment by VisalChhourm** [comment]
Your code looks fine and I think this might be your problem: "E/GamesNativeSDK(20463): Exception in com/google/android/gms/games/snapshot/Snap
 shots.load: java.lang.IllegalStateException: Cannot use snapshots without enabli
 ng the 'Saved Game' feature in the Play console"
Basically, it's telling you that you can not use saved game feature unless you enable it in Play Console.
So, to fix it just login to your [Play console](https://play.google.com/apps/publish) and go to your api app and enable Saved Game feature and try again.
Hope it help !

**Comment by koljanich** [comment]
![1234](https://cloud.githubusercontent.com/assets/10668288/14225188/496a4618-f8c2-11e5-9ea5-ba7575879b2b.png)
Drive API Enabled for applicaton

**Comment by VisalChhourm** [comment]
Hi,
No not that api console.
It's this one:
![capture](https://cloud.githubusercontent.com/assets/5152641/14225416/7ac1db8e-f8ec-11e5-984d-2b5d1216168a.PNG)

**Comment by koljanich** [comment]
Saved Games are ON too, but Error with ".. Cannot use snapshots without enabli
ng the 'Saved Game' feature in the Play console." is stay in. I do not use snapshots, why the error is stay?

> E/Netdiag (   99): select out for fd=7,i=0
E/Netdiag (   99): commandlistening handle_message
E/Netdiag (   99): close  fd=7,i:0
E/Netdiag (   99): FD_CLR fd=7,i:0
E/Netdiag (   99): commandlistening unlock exit
E/NetworkScheduler.SchedulerReceiver(13390): Invalid parameter app
E/NetworkScheduler.SchedulerReceiver(13390): Invalid package name : Perhaps you
didn't include a PendingIntent in the extras?
E/Trace   (30073): error opening trace file: No such file or directory (2)
E/dalvikvm(29706): Could not find class 'android.os.UserManager', referenced fro
m method com.google.android.gms.common.zze.zzaq
E/dalvikvm(29706): Could not find class 'android.app.AppOpsManager', referenced
from method com.google.android.gms.common.zze.zzb
E/Trace   (30097): error opening trace file: No such file or directory (2)
E/dalvikvm(30097): Could not find class 'android.os.UserManager', referenced fro
m method com.google.android.gms.common.GooglePlayServicesUtilLight.isRestrictedU
serProfile
E/dalvikvm(30097): Could not find class 'android.app.AppOpsManager', referenced
from method com.google.android.gms.common.GooglePlayServicesUtilLight.uidHasPack
ageName
E/dalvikvm(30097): Could not find class 'android.transition.Transition', referen
ced from method android.support.v4.app.BackStackRecord.captureExitingViews
E/dalvikvm(30097): Could not find class 'android.transition.Transition', referen
ced from method android.support.v4.app.BackStackRecord.configureTransitions
E/dalvikvm(30097): Could not find class 'android.transition.Transition', referen
ced from method android.support.v4.app.BackStackRecord.configureTransitions
E/dalvikvm(30097): Could not find class 'android.graphics.drawable.RippleDrawabl
e', referenced from method com.google.android.gms.games.ui.util.UiUtils.construc
tButtonBackground
E/ViewRootImpl(30097): Attempting to destroy the window while drawing!
E/ViewRootImpl(30097):   window=ViewRoot{42784d80 ,ident = 1}, title=
E/dalvikvm(30097): Could not find class 'android.test.IsolatedContext', referenc
ed from method com.google.android.gms.games.util.PanoUtils.isPano
E/NativeCrypto(28815): ssl=0x56dfffd8 cert_verify_callback x509_store_ctx=0x5613
aae8 arg=0x0
E/NativeCrypto(28815): ssl=0x56dfffd8 cert_verify_callback calling verifyCertifi
cateChain authMethod=ECDHE_RSA
E/Trace   (30136): error opening trace file: No such file or directory (2)
E/Trace   (30149): error opening trace file: No such file or directory (2)
E/DataBuffer(25020): Internal data leak within a DataBuffer object detected!  Be
 sure to explicitly call release() on all DataBuffer extending objects when you
are done with them. (internal object: com.google.android.gms.common.data.DataHol
der@42c5a850)
E/dalvikvm(30149): Could not find class 'android.app.AppOpsManager', referenced
from method com.google.android.gms.common.GooglePlayServicesUtil.zza
E/dalvikvm(30149): Could not find class 'android.os.UserManager', referenced fro
m method com.google.android.gms.common.GooglePlayServicesUtil.zzi
E/stp_dump(  128): table == NULL || table->table == NULL
E/stp_dump(  128): table == NULL || table->table == NULL
E/Trace   (30199): error opening trace file: No such file or directory (2)
E/stp_dump(  128): table == NULL || table->table == NULL
E/stp_dump(  128): table == NULL || table->table == NULL
E/wpa_supplicant(  484): Sorted scan results
E/wpa_supplicant(  484): 10:fe:ed:62:12:b7 freq=2457 qual=0 noise=0 level=-52 fl
ags=0x2b
E/wpa_supplicant(  484): 64:70:02:5b:aa:48 freq=2437 qual=0 noise=0 level=-78 fl
ags=0xb
E/wpa_supplicant(  484): ec:23:3d:cb:98:60 freq=2457 qual=0 noise=0 level=-82 fl
ags=0xb
E/Trace   (30229): error opening trace file: No such file or directory (2)
E/GamesNativeSDK(29706): Exception in com/google/android/gms/games/snapshot/Snap
shots.load: java.lang.IllegalStateException: Cannot use snapshots without enabli
ng the 'Saved Game' feature in the Play console.
E/GamesNativeSDK(29706): Exception in com/google/android/gms/games/achievement/A
chievements.load: java.lang.NullPointerException: null reference.
E/stp_dump(  128): table == NULL || table->table == NULL
E/stp_dump(  128): table == NULL || table->table == NULL
E/wpa_supplicant(  484): Sorted scan results
E/wpa_supplicant(  484): 10:fe:ed:62:12:b7 freq=2457 qual=0 noise=0 level=-53 fl
ags=0x2b
E/wpa_supplicant(  484): 64:70:02:5b:aa:48 freq=2437 qual=0 noise=0 level=-79 fl
ags=0xb
E/wpa_supplicant(  484): ec:23:3d:cb:98:60 freq=2457 qual=0 noise=0 level=-81 fl
ags=0xb
E/stp_dump(  128): table == NULL || table->table == NULL
E/stp_dump(  128): table == NULL || table->table == NULL
E/Trace   (30256): error opening trace file: No such file or directory (2)
E/Trace   (30268): error opening trace file: No such file or directory (2)
E/Trace   (30289): error opening trace file: No such file or directory (2)
E/Trace   (30315): error opening trace file: No such file or directory (2)
E/Trace   (30353): error opening trace file: No such file or directory (2)
E/Trace   (30378): error opening trace file: No such file or directory (2)
E/Trace   (30391): error opening trace file: No such file or directory (2)
E/ActivityNetwork_Thread(30391): read thread running
E/Netdiag (   99): commandlistening unlock exit

**Comment by claywilkinson** [comment]
Has that game definition ever been in Published state?  I don't think you can change it once it is published.  Also, try resetting the cache on your device by dragging the "Google Settings" app to the "App Info" target, then reset the cached data. 

Also, at the bottom on the console for your game, make sure Drive API is enabled.  If it is not, you can click on the link for the API console project and enable Drive there.
![screen shot 2016-04-04 at 10 40 42 am](https://cloud.githubusercontent.com/assets/8752378/14257238/b4ba8fbe-fa51-11e5-8bab-058f3ea3f76b.png)
