### ISSUE TITLE
Permission dialog coming up at starting of game

### ISSUE THREAD

**Issue by shohagmist** [playgameservices/play-games-plugin-for-unity#1078]
When i enter the game a dialog comes saying "Allow MyGameName to access your contacts" as in the attached images. When I am building my game without the Play Games Plugin, the dialog is not coming up. I have even seen this dialog in some popular game i.e. PacMan 256, asking for recording voice.

The dialog is showing in my Google Nexus 5. Is it a issue with this plugin?
![screenshot_20160204-180432](https://cloud.githubusercontent.com/assets/5347419/14135273/5ee039ee-f67e-11e5-9ab1-fc5709fdffb7.png)
![screenshot_20160324-215840](https://cloud.githubusercontent.com/assets/5347419/14135272/5e9a5654-f67e-11e5-8b10-2984d0b38e42.png)

**Comment by claywilkinson** [comment]
The permission to access contacts is triggered by trying to access the player's email address or get an id token.  In Android "M" the permissions are requested as needed vs. all at once at installation.  For example, if the email address or id token are not accessed, the permission is never requested.

**Comment by claywilkinson** [comment]
OK to close this one?

**Comment by shohagmist** [comment]
Sure :) Thank you for your response.
