### ISSUE TITLE
Reset Achievements?

### ISSUE THREAD

**Issue by garbagepit** [playgameservices/play-games-plugin-for-unity#108]
Is there a way through the Unity plugin to achieve this? 

As I understand at a minimum this will only work for achievements that are being tested, but is possible with the google play services SDK.

**Comment by enzi96** [comment]
@wolffg could you please look into my problem here - https://github.com/playgameservices/management-tools/issues/20 I'm trying to set it work but I can't seem to understand what it's said there.
