### ISSUE TITLE
Xperia Z2 signin bug

### ISSUE THREAD

**Issue by icaro56** [playgameservices/play-games-plugin-for-unity#1083]
I can not signin on Google Play in my Xperia Z2.

**Comment by icaro56** [comment]
The Google Play Signin hud shows the logged user and his level, but the authenticate failed. No error message appears

**Comment by claywilkinson** [comment]
Why do you think authentication failed even though the player's id and level are shown?

**Comment by icaro56** [comment]
Because I put a debug.Log("Failed") in the callback.

If success it prints Success. Else it prints failed.

Only in this cellphone occurs this problem.

**Comment by claywilkinson** [comment]
Can you share the log of the problem?

**Comment by icaro56** [comment]
I have only a print.

![802609764_76902_4283125212012771981](https://cloud.githubusercontent.com/assets/7433049/14258490/0be85ac4-fa79-11e5-9b6d-39749d217109.jpg)

It is printed "Falha ao logar" (Signin Failed)

**Comment by claywilkinson** [comment]
It looks like there was a problem downloading the achievement definitions.  Can you run logcat without filtering just for Unity?  You can save to a file by using` > log.txt ` at the end of the command (I am presuming you are using windows).

**Comment by icaro56** [comment]
Yes, I am using windows. Do you want I run this command: adb logcat -s Unity?

**Comment by icaro56** [comment]
[log.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/203143/log.txt)

**Comment by icaro56** [comment]
another: 
[log (1).txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/203188/log.1.txt)

**Comment by claywilkinson** [comment]
Thanks.  Is it just this one user?  There may be a permissions issue (such as the first time the player authenticated, they denied permission to the game)?  Can you try another user or reset the permissions for that user on the device?

**Comment by icaro56** [comment]
Only this user (Sergio: developer too) have problem. Any other user works.

This player is listed as a tester in the console.

How do I reset the permissions for that user?

**Comment by icaro56** [comment]
I am listed as a tester too. And the signin works for me.

PS: The app is in production. https://play.google.com/store/apps/details?id=br.com.Gamelancers.Rocket_IX&hl=pt_BR

**Comment by claywilkinson** [comment]
drag the application to the "App Info" target on the top and then there should be a permissions element in the list.  Click that and reset.

**Comment by icaro56** [comment]
do drag the icon app in my celular?

**Comment by claywilkinson** [comment]
The easiest way is to reset every app preference and permission.  In the Settings app, go to the Apps section.  Then click on the 3 vertical dots on the right (which is a menu).   Click Reset app preferences.

This will reset all the apps to the default  properties.

**Comment by icaro56** [comment]
It didn't solve the problem. The issue continues.

**Comment by claywilkinson** [comment]
OK - thanks for trying. I've passed along the issue to see if we can figure out more.

**Comment by icaro56** [comment]
I will try comment this line: PlayGamesPlatform.InitializeInstance(config); and comment all calls to achievements.

**Comment by claywilkinson** [comment]
You need InitializeInstance() -- and this error is happening during authentication, before you can call any Achievement APIs.

**Comment by icaro56** [comment]
The documentation said that InitializeInstance is necessary only to: In order to save game progress, handle multiplayer invitations and turn notifications, or require access to a player's Google+ social graph, the default configuration needs to be replaced with a custom configuration.

If I comment this (and all code that uses these features), then I can do the signin. I will test tonight.

**Comment by icaro56** [comment]
I do the test commenting InitializeInstance() and it does not works too.

**Comment by claywilkinson** [comment]
You can also try resetting the Google Play Services cache by going to Settings > Apps > Google Play Services.  Click clear cache.

**Comment by icaro56** [comment]
I try this and it does not works.

**Comment by icaro56** [comment]
I have installed two other games made by unity and both have the same problem in logging in google play. However, I have several other games not unity-based and I can connect on google play greatly.

**Comment by claywilkinson** [comment]
Please open a new issue including the logs if this is still and issue.
