### ISSUE TITLE
Spend probability not available in Player Statistics

### ISSUE THREAD

**Issue by hex** [playgameservices/play-games-plugin-for-unity#1085]
The **Spend Probability** player data is not available in Player Statistics.

> Spend probability: The approximate probability of the player choosing to spend in this game, given as a decimal value between 0 and 1 (inclusive). Higher values indicate that a player is more likely to spend.

[https://developers.google.com/games/services/android/stats#player_stats_basics](https://developers.google.com/games/services/android/stats#player_stats_basics)

**Comment by claywilkinson** [comment]
Thanks for the feedback!  Spend Probability is currently not in the C++ SDK, which this plugin is based on.  In the mean time, you can use JNI to get this value.  I'll update this issue when I know more about when the C++ SDK will be updated.

**Comment by Thibaudz** [comment]
Hi

Have you an example to use JNI to get this value?

**Comment by hex** [comment]
Yeah, an example would be helpful. I have no idea how to get that value using JNI. I tried opening this project in Android Studio but couldn't get it to work.

**Comment by claywilkinson** [comment]
An older release - 0.9.27 used JNI for the player stats API.  Until the C++ SDK is updated, I'll merge the code from .9.27 into the current plugin and add the SpendProbability.  I hope to have it done in a couple days.

**Comment by claywilkinson** [comment]
This API has been added in 0.9.34 of the plugin.
