### ISSUE TITLE
IOS - Google Play authenticate crash 

### ISSUE THREAD

**Issue by dannychow78** [playgameservices/play-games-plugin-for-unity#1086]
I'm getting this error [__NSDictionaryI gtm_httpArgumentString]: unrecognized selector sent to instance 0x15dff26d0 whenever I tried to use google play authenticate method. This error crash the ios device.

Anyone have any idea what may cause this? Thanks.

**Comment by claywilkinson** [comment]
Can you share the log?  Is there some indication of which method or key is being sent?

**Comment by dannychow78** [comment]
Sorry for the late reply. It's all good now. I re-installed Xcode and problem solved.

**Comment by claywilkinson** [comment]
Great, thanks for the update.
