### ISSUE TITLE
(GTLDateTime.o) does not contain bitcode

### ISSUE THREAD

**Issue by v2k** [playgameservices/play-games-plugin-for-unity#1088]

**Comment by claywilkinson** [comment]
Thanks - yes, this is currently a problem.  We'll have a fix in the next update of the plugin (coming soon!)

**Comment by claywilkinson** [comment]
Tracking the progress of disabling bitcode in #1040

**Comment by vanshikakapoor** [comment]
I am facing the same problem and I am on Xcode 8, so i have to enable Bitcode. Kindly help.
