### ISSUE TITLE
Admob ads are not showing in my Android game

### ISSUE THREAD

**Issue by subzeroz** [playgameservices/play-games-plugin-for-unity#1089]
Hello,

I am trying to build my Unity 5 Android game after integrating Admob.

When I build it I get this error:

Error building Player: CommandInvokationFailure: Failed to re-package resources.
C:\Users\....\AppData\Local\Android\sdk\build-tools\23.0.3\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Users/..../AppData/Local/Android/sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.google.android.gms:com.google.unity:com.google.android.gms.ads:com.google.android.gms:android.support.v4 -S "C:\Unity Projects\ColorSwitch\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res" -S "C:\Unity Projects\ColorSwitch\Temp\StagingArea\android-libraries\google-play-services_lib\res" -S "C:\Unity Projects\ColorSwitch\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\res" -S "C:\Unity Projects\ColorSwitch\Temp\StagingArea\android-libraries\play-services-ads-6.5.87\res" -S "C:\Unity Projects\ColorSwitch\Temp\StagingArea\android-libraries\play-services-base-6.5.87\res" -S "C:\Unity Projects\ColorSwitch\Temp\StagingArea\android-libraries\support-v4-23.1.1\res"

-------------
I searched Google alot and still couldn't fix this.
I added a version xml file in Assets/GoogleMobileAdsPlugin/res/values
And also deleted the InAppPurchase theme line in AndroidManifest.xml
I also have my SDK (API 23) updated.

So how can I fix this ?

**Comment by subzeroz** [comment]
Ok. I fixed this error by deleting the google-play-services_lib folder I had imported.

Now I am not getting any errors in the editor or during the build, but when I try to open the game on my phone, I get the error: **Unfortunately [game Name] has stopped**

I just build one empty scene with a camera and I attached the **GoogleMobileAdsDemoScript.cs** script to the camera.

What could be the problem ?

**Comment by claywilkinson** [comment]
Using the recent plugins for Admob and PlayGameServices, you definitely do not want the google-play-services_lib in your project.  When you add these plugins it will copy a set of .aar files from the Android SDK to your project in Assets/Plugins/Android.  These should have all the resources and classes you need.

Can you share the complete error you are getting?  Also which version of Unity, the version of the plugins, and the contents of Assets/Plugins/Android in your project.

**Comment by subzeroz** [comment]
@claywilkinson Thanks for your comment. As I said in my second post I am no longer getting errors in the editor and also deleted the code inside the Start() method in **GoogleMobileAdsDemoScript.cs** script to fix the **Unfortunately has stopped error** in my phone.

But now I have a new problem, and that is the ads are not showing in my phone. Even though the Ad Unit Id in my script is the same as the one in my Admob account.

The **GoogleMobileAdsDemoScript.cs** script is found [here](https://github.com/googleads/googleads-mobile-unity/blob/master/samples/HelloWorld/Assets/GoogleMobileAdsDemoScript.cs)

What could be the problem ?

**Comment by claywilkinson** [comment]
can you share a log of the problem on the device?

**Comment by subzeroz** [comment]
@claywilkinson how can I see the log on my phone?

**Comment by claywilkinson** [comment]
You can use [logcat](http://developer.android.com/tools/debugging/debugging-log.html) to view the log on the device.  Basically from a command prompt run `adb logcat`.  adb is part of the Android SDK.

If you have Android Studio, you can open it and view the Android Monitor tab at the bottom.

**Comment by subzeroz** [comment]
@claywilkinson
I don't know if this has to do with my problem, but when I opened the app in my phone, this error appeared in logcat in Android Studio:


`04-07 22:27:34.194: I/Unity(23566): AndroidJavaException: java.lang.NoSuchMethodError: no method with name='setRequestAgent' signature='(Ljava/lang/String;)Ljava/lang/Object;' in class Lcom/google/android/gms/ads/AdRequest$Builder;
04-07 22:27:34.194: I/Unity(23566): java.lang.NoSuchMethodError: no method with name='setRequestAgent' signature='(Ljava/lang/String;)Ljava/lang/Object;' in class Lcom/google/android/gms/ads/AdRequest$Builder;
04-07 22:27:34.194: I/Unity(23566): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
04-07 22:27:34.194: I/Unity(23566): 	at com.unity3d.player.UnityPlayer.a(Unknown Source)
04-07 22:27:34.194: I/Unity(23566): 	at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
04-07 22:27:34.194: I/Unity(23566):   at UnityEngine.AndroidJNISafe.CheckException () [0x00085] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs:25 
04-07 22:27:34.194: I/Unity(23566):   at UnityEngine.AndroidJNISafe.GetMethodID (IntPtr obj, System.String name, System.String sig) [0x00013] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs:68 
04-07 22:27:34.194: I/Unity(23566):   at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.String signature, Boolean isStatic) [0x00022] in /Users/bu
`

**Comment by claywilkinson** [comment]
This looks like some sort of issue with the version of the plugin and the version of the jars maybe?  I'd suggest looking at https://github.com/googleads/googleads-mobile-unity/issues or creating a new issue there.   Please link that issue here  to make sure you get a response eventually.

**Comment by subzeroz** [comment]
Ok thanks my friend for your help.

**Comment by claywilkinson** [comment]
You're welcome.  Please update this thread with anything you find out so others can benefit too.

**Comment by subzeroz** [comment]
@claywilkinson Until now I didn't find the solution of the error above, but I noticed that in my Admob account they told me that the ads are not showing because I haven't verified my PIN.
So I am waiting a few days to see if I will recieve my new PIN. Then I will see if the problem persists.

**Comment by claywilkinson** [comment]
Thanks for the update.  Sounds like it is OK to close this issue?

**Comment by subzeroz** [comment]
yea it's ok we can close it :)
