### ISSUE TITLE
login loop with multiple goole+ accounts

### ISSUE THREAD

**Issue by ktrifon** [playgameservices/play-games-plugin-for-unity#109]
I use the Unity 3d plugin (plugin build 0.9.01)  with unity 4.3.3f1 
and I get into a log in loop at devices with multiple accounts...
It asks you to select an account, you select one, it asks you again and so on...

If I delete the second google+ account and keep only one, everything works fine!

My code is simple, I check if Social.localUser.authenticated is false, and in that case
I call 
```
Social.localUser.Authenticate((bool success) =>
                { 
                    if (success)
                    { blah blah
```

Is there a workaround?
any hope for fixing it soon? 

I won't be able to release a game with this behaviour...
Thanks

**Comment by mrggl** [comment]
Note that the plugin only officially supports Android 4.0 (ICS) and above - please see if you can replicate there, and let us know if you still see this behavior.
