### ISSUE TITLE
Can't connect 

### ISSUE THREAD

**Issue by tortora23** [playgameservices/play-games-plugin-for-unity#1091]
Hi, i'm not able to find out where is my mistake, i'm 

this is my logcat  : http://pastebin.com/MgR9BSDk
this is my c# script : http://pastebin.com/qNysPthL

i'm sure the google play sevice is up to date from the sdk manager 
i run the setup and checked if the plugin is up to date
i'm running it on android devices with an email addres invited to alpha test 

no login screen is showing up, and i'm not able to loggin neither with a minimal project.

Help pleasee help ;)

**Comment by claywilkinson** [comment]
Can you look at the unfiltered log (not just the Unity messages).  From this line:
`InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK` I think you have some sort of mis-match between version of the play-services libraries and the plugin.
What version of Unity are you using?  
What version of this plugin are you using?
What version of play-services are being included in Assets/Plugins/Android ?

**Comment by tortora23** [comment]
Unity version is 5.3.4, the plugin is 0.9.32, in the path Assets/Plugin/Android/res/value the xml show version number 8487000

if i run the project on unity environment  the call at Social.localUser.Authenticate return a false (obviously) butif i run on the device it block the program

**Comment by claywilkinson** [comment]
Great! glad you got it working
