### ISSUE TITLE
Sign-in crash

### ISSUE THREAD

**Issue by ggirgin** [playgameservices/play-games-plugin-for-unity#1092]
Hi , 
After updating Unity 5.3.2  to 5.3.4  google play game services start  giving me "sign in crash" . 
I made latest update sdk manager but have not solved yet. 

Thanks,
Gokmen

**Comment by claywilkinson** [comment]
Can you share the log of the problem?  That will help figure out what is going on.

**Comment by ggirgin** [comment]
Hi Clay, 
I just solved.
I deleted plugin completely then i installed again. 
Thanks,
Gokmen

**Comment by claywilkinson** [comment]
Great! I am glad it is working now.
