### ISSUE TITLE
GPGS Upgrader deletes Android/google-play-service_lib used by other SDKs(HeyZap)

### ISSUE THREAD

**Issue by wong-martin** [playgameservices/play-games-plugin-for-unity#1095]
So I'm currently using 

v0.9.32 Google Play Unity
v0.9.4.4  HeyZap Unity Plugin
Unity 5.1.4f

So the Jar Resolver/GPGS Upgrader is deleting the Assets/Plugins/Android/google-play-services_lib which HeyZap and some of the Ad Networks like Chartboost uses. This is crashing the SDK.

https://github.com/playgameservices/play-games-plugin-for-unity/issues/801

I've followed some of the steps that this issue had to delete the GPGS upgrader lines but it looks like it's deleting the Assets/Plugins/Android/google-play-services_lib  when trying to build and it re-adds the AARs in Android folder. Also spits out this console error.

CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:\Program Files\Java\jdk1.8.0_66\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/fryin/AppData/Local/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:/Program Files/Unity/Editor/Data/BuildTargetTools/AndroidPlayer\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzpz;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzpz$zza;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzpz$zzb;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzpz$zzc;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzpz$zzd;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzpz$zze;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzpz$zzf;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqa;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqa$zza;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
	... 9 more
]

Any help with this issue would be greatly appreciated.

**Comment by claywilkinson** [comment]
You really don't want to use google-play-service_lib in your game.  It pulls in a bunch of code for things you are most likely not using in your game such as Android Auto and Android Wear APIs.  The other plugins will work if you add the specific aar files that are needed by the plugins (I am not 100% sure, but I think you need play-services-ads.  

In Assets/GooglePlayGames/Editor/GPGSDependencies.cs around line 63 add
```
            svcSupport.DependOn("com.google.android.gms",
                "play-services-ads",
                PluginVersion.PlayServicesVersionConstraint);
``` 
You might want to delete all the aar files in Assets/Plugins/Android then run Assets > Google Play Services > Resolve Client Jars.


If you are still having issues can you share the contents of Assets/Plugins/Android?

**Comment by wong-martin** [comment]
<img width="1076" alt="pluginsfolder" src="https://cloud.githubusercontent.com/assets/18334406/14365738/48c74f02-fcdd-11e5-8d70-536452afafcf.png">

We've tried adding the dependencies, also tried deleting the AARs and reimporting them, HeyZap is still crashing. Not sure what else to try.

**Comment by wong-martin** [comment]
![image](https://cloud.githubusercontent.com/assets/18334406/14365822/b9b8a7ba-fcdd-11e5-8ec5-7dcb04c8a50d.png)


google-play-services_lib is empty from the GPGS Upgrader deleting it.

**Comment by wong-martin** [comment]
![image](https://cloud.githubusercontent.com/assets/18334406/14365855/dee60032-fcdd-11e5-93bc-358374206e34.png)

google-play-services_lib is empty from the GPGS Upgrader deleting them.

**Comment by claywilkinson** [comment]
I can't see the extensions of all the files - but it looks reasonable. - when you build what is the error you are getting (it might be a lot of out put - best thing would be to copy it to a [Gist](https://gist.github.com/)

**Comment by wong-martin** [comment]
So it builds fine no issues, and the HeyZap SDK looks like it's working as intended for about 5 seconds into the App Launch. Then it crashes. Any calls made to the SDK give this output

I/Unity   (29297): AndroidJavaException: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
I/Unity   (29297):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0
I/Unity   (29297):   at UnityEngine.AndroidJNISafe.CallStaticVoidMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0
I/Unity   (29297):   at UnityEngine.AndroidJavaObject._CallStatic (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0
I/Unity   (29297):   at UnityEngine.AndroidJavaObject.CallStatic (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0
I/Unity   (29297):   at Heyzap.HeyzapAdsAndroid.ShowMediationTestSuite () [0x00000] in <filename unknown>:0
I/Unity   (29297):   at Heyzap.HeyzapAds.ShowMediationTestSuite () [0x00000] in <filename unknown>:0
I/Unity   (29297):   at AdScript.ShowTestSuite () [0x00000] in <filename unknown>:0
I/Unity   (29297):   at UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) [0x00000] in <filename unknown>:0
I/Unity   (29297):   at UnityEngine.Events.InvokableCallList.Invoke (System.Object[]

**Comment by claywilkinson** [comment]
Great! I'm glad you building :).  Hmm. Don't know about that - looks like it is inside some Heyzap code.  Maybe it is not running on the UI thread or something?

**Comment by wong-martin** [comment]
Yeah not sure, been having no luck at this point, also sent in a support ticket to HeyZap to see if there's anything on their side, but I've built using an older version of the google play plugin, and without the google play plugin overall, and HeyZap appears to have no issues. However, using the older google play puts us over the Unity method limit so we need to update or rip out other sdks.

So figured I'd ask around and see if there were any simpler fixes.

**Comment by claywilkinson** [comment]
I hear ya - good luck.  You could try the older versions and replace the google-play-services-lib with the collection of aar files by hand you might get under the limit that way.

Just out of curiosity - how far over the limit are you?

**Comment by wong-martin** [comment]
Just heard from the HeyZap support ticket, apparently one of our SDKs for other ad networks wasn't fully updated. Looks good from here on, we also needed to add the ad dependency for Ad Mob as well.

Thanks for all the help @claywilkinson.

**Comment by claywilkinson** [comment]
You're welcome. Glad you're up and running.
