### ISSUE TITLE
How do I obtain saved game ID using this SDK?

### ISSUE THREAD

**Issue by EternalMelody** [playgameservices/play-games-plugin-for-unity#1100]
According to https://developers.google.com/games/services/common/concepts/savedgames#saved_games_basics ,
ID is one of the metadata associated with a saved game. However, the ISavedGameMetadata interface does not contain ID as a public property or method or field.

How do I obtain the ID? The reason I want the ID is to reuse the same saved game slot.

Thanks!

**Comment by claywilkinson** [comment]
You need to [open the saved game ](https://github.com/playgameservices/play-games-plugin-for-unity#opening-a-saved-game )using a filename (which in your case would match the name used when calling open the first time to save).  The response from open contains the metadata.

The id that really matters in your case is the file name passed into open.

**Comment by claywilkinson** [comment]
OK to close this issue?
