### ISSUE TITLE
Creating new cloud save

### ISSUE THREAD

**Issue by joserocha3** [playgameservices/play-games-plugin-for-unity#1101]
This is probably a dumb question, but for the life of me I cannot figure out how to create a new cloud save game. All the methods and documentation assume the user is selecting an existing save file. Setting ShowSelectSavedGameUI parameter showCreateSaveUI to true reveals a create new save button, but the callback passes in an empty ISavedGameMetadata.

How do we create the original save file? Preferably without the user ever seeing the saved game UI. There will only be one save for my game so the user does not need to manage it. So I would in turn need a method to get back a list of all save files (list would only have one) in case they open the game on a new device.

Thanks!

**Comment by claywilkinson** [comment]
You can open new saved games by passing in a file name that does not exist, set the metadata and commit the update.  There is no need to involve the player in the scenario you describe.

**Comment by claywilkinson** [comment]
OK to close this one?

**Comment by joserocha3** [comment]
Yes thank you
