### ISSUE TITLE
Is it possible to use Google Play Service on a game not published on Google Play?

### ISSUE THREAD

**Issue by aidinzolghadr** [playgameservices/play-games-plugin-for-unity#1103]
Hi,

I'm developing a game for a local Android market but for the leaderboard I'm using Google Play Services. I wanted to know whether it's possible for people to use my leaderboard without publishing on Google Play and just on that local Android market.

Problem is I got Leaderboard up and running with the GPGS but only testers can use it and I think for others be able to use it has to be out of beta and published, please correct me if I'm wrong.

Best, idn

**Comment by aidinzolghadr** [comment]
Thanks. How can I put the game in publish mode? Is it same as publishing my game? I prefer my game not be seen in Google Play store for now.

And to answer your question, because we are soft launching the game in a local market.

**Comment by claywilkinson** [comment]
Thanks for the answer - that makes perfect sense.  You are able to publish the game definition from the Play Developer console.  Select your game services entry and on the top right there is a  drop down widget that probably says, "Ready to Test" - Drop this down and select "Publish Game".  This makes your game services definition live.  You don't need to upload an .apk or anything like that.

**Comment by aidinzolghadr** [comment]
Thanks for quick answers.

Will this publish your game, make it available on Google Play store? I'm asking because I think you said it doesn't but in the store page it says "publish your game" and not something like "enable your game services".

I've uploaded an APK before to solve a problem that I faced earlier.

Thanks.

**Comment by claywilkinson** [comment]
I am 99% sure that publishing the game services does not affect the Play Store publishing. - I know i can just publish the game services without ever uploading an apk.
![screen shot 2016-04-11 at 3 28 48 pm](https://cloud.githubusercontent.com/assets/8752378/14444675/de857c14-fffb-11e5-96ed-4945571251b7.png).

**Comment by claywilkinson** [comment]
OK to close this one?  Can you share your experience of how you handled this situation?

**Comment by aidinzolghadr** [comment]
Yes close it. It worked just fine as you explained to me before. Is there anyway to make it target to lower version of Android in "targetSdkVersion"? Currently is set to 16 via GPGS.

**Comment by claywilkinson** [comment]
The target should be the max version supported, the minSDKVersion sets the minimum requirements.  The min value is set by Unity in the player settings inspector (under Other Settings).
