### ISSUE TITLE
GetServerAuthCode callback not run on main thread

### ISSUE THREAD

**Issue by turnipski** [playgameservices/play-games-plugin-for-unity#1105]
NativeClient.GetServerAuthCode should be using InvokeCallbackOnGameThread to call the callback but it's not

**Comment by claywilkinson** [comment]
I am not completely convinced this is true.  Why do you think it should be on the game thread?

As an immediate work around, you can wrap your callback in GooglePlayGames.OurUtils.PlayGamesHelperObject.RunOnGameThread().

**Comment by turnipski** [comment]
From the documentation of IPlayGamesClient which NativeClient implements:

/// <para>CALLBACKS: all callbacks must be invoked in Unity's main thread.
  /// Implementors of this interface must guarantee that (suggestion: use
  /// <see cref="GooglePlayGames.OurUtils.RunOnGameThread(System.Action action)"/>).</para>
  /// </remarks>

Maybe InvokeCallbackOnGameThread isn't correct method as it only takes one argument, but regardless the callback should be on the game thread.

**Comment by Zophiel** [comment]
Is there another way to get the id_token? Our backend server depends on receiving it to verify the user. Project is blocked right now because of it.

**Comment by claywilkinson** [comment]
Moved this and other callbacks to be on the game thread in version 0.9.33
