### ISSUE TITLE
How to know if I (not opponent) left the game?

### ISSUE THREAD

**Issue by fzdravko** [playgameservices/play-games-plugin-for-unity#1106]
Unity 4.7.1f1, google play games 0.9.32, two players real-time multiplayer.

When I send game to the background (or anything else) opponent get notification that I left the game (OnPeersDisconnected get called).

How to know that I left the game? I think that OnLeftRoom is supposed to be called but it never do. Also IsConnectedToRoom always returns true.

**Comment by v2k** [comment]
RealTimeMultiplayerListener.OnLeftRoom() should be getting hit; I'm not using the same versions as you however.  Both get called for me when I leave.

**Comment by nikoskon2003** [comment]
Did anyone figure this out, because still 3 years later i think this is still an issue!

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
