### ISSUE TITLE
error CS0246: The type or namespace name `GooglePlayGames' could not be found.

### ISSUE THREAD

**Issue by BagelBob** [playgameservices/play-games-plugin-for-unity#1108]
I'm getting an error:
error CS0246: The type or namespace name `GooglePlayGames' could not be found.
when I try to make a PC build for my game. The error triggers on my "using GooglePlayGames;" instruction line.
There are no errors for an android build. Does this plugin support PC builds?

**Comment by sorab2142** [comment]
This plugin does not support non-mobile platforms.

**Comment by claywilkinson** [comment]
More precisely, it supports Android and iOS only.
