### ISSUE TITLE
Access Not Configured

### ISSUE THREAD

**Issue by exeri0n** [playgameservices/play-games-plugin-for-unity#1109]
Unable to login to Google Player Services. Getting this error...

**04-18 11:36:57.219: E/SignInIntentService(20882): Access Not Configured. Google Play Game Services API has not been used in project 608941808256 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/games/overview?project=608941808256 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.**

This is not our app ID **608941808256**  ?

We have previously been using Google Play Services with our app.  We're using 0.9.32. The manifest file looks correct.

Please help :)

**Comment by claywilkinson** [comment]
Can your run setup again and paste in the resource data from the Play developer console and see if that fixes the issue?  If it does not, can you let me know your app Id?

**Comment by exeri0n** [comment]
Thanks I ran setup again an it now works.

The only thing that I can see that changed was in the file **GooglePlayGameSettings.txt**.  On the line that defined **and.ResourceData** it removed these characters from the end **%0d%0a**.

**Comment by quantqqq** [comment]
I also encountered this problem, but run setup again didn't fix it.
Please help!

I'm using GooglePlayGamesPlugin-0.9.34.unitypackage.

**Comment by Sankalp-bst** [comment]
I have same issue while using GooglePlayGamesPlugin-0.9.34.unitypackage. Run setup didn't work.
