### ISSUE TITLE
crach app on nexus 7

### ISSUE THREAD

**Issue by quanvn1206** [playgameservices/play-games-plugin-for-unity#111]
hi.
I am using your plugin. It work fine in many device. But when i test on nexus 7 , my app i crash.

this is my code in Unity Start function
              // recommended for debugging:
		PlayGamesPlatform.DebugLogEnabled = true;
		
		// Activate the Google Play Games platform
		PlayGamesPlatform.Activate();
		
		// authenticate user:
		Social.localUser.Authenticate((bool success) => {
			// handle success or failure
			if(success){
				Debug.Log("success login");
			}
			else{
				Debug.Log("fail login");
			}
		});

And 
04-23 22:17:28.854: I/Unity(29860): [Play Games Plugin DLL] Activating PlayGamesPlatform.

04-23 22:17:28.864: I/Unity(29860): [Play Games Plugin DLL] PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform

04-23 22:17:28.864: I/Unity(29860): [Play Games Plugin DLL] Creating platform-specific Play Games client.

04-23 22:17:28.994: I/Unity(29860): [Play Games Plugin DLL] Making sure PlayGamesHelperObject is ready.

after is crash log 

04-23 22:17:29.034: A/art(29860): art/runtime/check_jni.cc:64] JNI DETECTED ERROR IN APPLICATION: java_array == null
04-23 22:17:29.034: A/art(29860): art/runtime/check_jni.cc:64]     in call to GetArrayLength
04-23 22:17:29.034: A/art(29860): art/runtime/check_jni.cc:64]     from java.lang.Object com.unity3d.player.ReflectionHelper.nativeProxyInvoke(int, java.lang.String, java.lang.Object[])
04-23 22:17:29.034: A/art(29860): art/runtime/check_jni.cc:64] "main" prio=5 tid=1 Runnable
04-23 22:17:29.034: A/art(29860): art/runtime/check_jni.cc:64]   | group="main" sCount=0 dsCount=0 obj=0x6463aac8 self=0x41874928
.....

When i comment out  Authenticate function it work fine.
    comment function Social.localUser.Authenticate
Can you help me fix this bug. 

thanks .

**Comment by claywilkinson** [comment]
Closing this since it looks like the ART support has been fixed.
