### ISSUE TITLE
GetServerAuthCode is not working

### ISSUE THREAD

**Issue by incago** [playgameservices/play-games-plugin-for-unity#1112]
After authenticate, 
run below code. and callback function is not excuted.
Is there anyone have some issue?

---

PlayGamesPlatform.Instance.GetServerAuthCode(TestWithIdToken);

 public void TestWithIdToken(CommonStatusCodes code, string idToken)
    {
        Debug.Log("TestWithIdToken()");
        Debug.Log("code : " + code.ToString());
        Debug.Log("idToken : "+ idToken);
    }

**Comment by claywilkinson** [comment]
Can you share a log of the call?  That might help figure out what is wrong.  One thing to check is that you correctly configured the web client id in the Setup dialog.  The web client id needs to be from the linked web app associated with your game definition.

**Comment by claywilkinson** [comment]
The AuthCode and token processing has been improved in version 0.9.37.

**Comment by incago** [comment]
thank you :-)
