### ISSUE TITLE
Can't find 0.9.25 build?

### ISSUE THREAD

**Issue by vexe** [playgameservices/play-games-plugin-for-unity#1114]
Greetings,

We've used 0.9.25 in our past project and it worked fine. Using the latest build 0.9.31a is causing issues authenticating "There was an error creating a GameServices object" - I can't seem to find 0.9.25 in the old builds folder. I'd like to get it if possible.

Thanks.

**Comment by claywilkinson** [comment]
The best way to get older version is to look at the current-build folder and hit "History".  You can scroll back through the updates to get the version you want. I use the CHANGELOG.txt file with "Blame" turned on to get hints on the dates of the updates.

**Comment by vexe** [comment]
Yes but why all the older version are there except for 0.9.25? (which the only version that worked for us...)

**Comment by claywilkinson** [comment]
We stopped putting the old versions in there primarily for efficiency.  The make the cloning process of the repository bigger than it needs to be, and since there is a Git history of the commits, all the older versions are there for reference as well.

If you have the time, I'd love to  hear what issues and troubles you're having between 0.9.25 and the current version.  The goal is to make each version better.  If you think that goal is not being hit, please let us know.

**Comment by vexe** [comment]
I don't know man, it's just frustrating every time we upgrade _any_ plugin, the new version just screws us up in one way or another. Right now It just crashes. Looking at catlog I only see "There was an error creating a GameServices object" - I looked that up and people seem to have some classes not registered which is causing the error. I didn't see anything regarding failed registration of classes. I could paste the log if it helps.

**Comment by claywilkinson** [comment]
Definitely share the logs, include the complete log, not just the Unity category.

Moving back and forth on versions of the plugin one potential issue you might be having is because there is a shared library included in the plugin from the GPGS C++ SDK.  This library uses some methods out of the Java client libraries via JNI and if those methods are not there, the initialization of the library fails.  Over the last couple versions of the C++ SDK, some methods have been removed (the AppState API for saving games), and some have been added (GetServerAuthCode).  As a result, there is an implicit dependency between the plugin and the version of the play-services being used in the Unity project.

**Comment by vexe** [comment]
I use "adb logcat -s Unity ActivityManager PackageManager dalvikvm DEBUG" - is that that log you want?

Yeah I did figure there's some missing files. I noticed there were fewer files added to the project with the newest version. Which is why I was trying to lookup that older version and see which files it had. 

"The best way to get older version is to look at the current-build folder and hit 'History'..."
Sorry but that is completely absurd. Users should not have to dig through history logs to try to figure out what they need from what they don't. You don't need to include all the releases in the repository, just host them somewhere on a file sharing website or something and provide the link to that here.

**Comment by claywilkinson** [comment]
Thanks for the feedback - We'll look into a better way to get old builds.

adb logcat with no filters seems to be the most expedient since we don't know where the problem is.

**Comment by vexe** [comment]
Here's the log http://pastebin.com/TUK8e9Gg - If you search for "Exception" you'll see the error. Let me know if that gives you any leads as to what's up.

**Comment by claywilkinson** [comment]
I see this line: `I/Unity   (20449): InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK`  but I don't see any log messages with the category: **GamesNativeSDK**.  

Are you setting (or can you) set `PlayGamesPlatform.DebugLogEnabled = true;` just before you call ` PlayGamesPlatform.Activate();` 

I'll make some time to try to reproduce it this afternoon (PDT).  Let me know if you find any more clues before then.

**Comment by vexe** [comment]
Here's the log with GP logging enabled http://pastebin.com/yytAD5GW

**Comment by vexe** [comment]
What does PlayServicesResolver do? - I think the entirety of the issue was that there were tons of files missing somehow. Does this resolver download dependency stuff?

**Comment by claywilkinson** [comment]
Yes, PlayServicesResolver copies the required components of the play-services client (a set of .aar files) to the Unity project.  This replaces copying the entire play-services_lib directory which blows up the dex limit for many games.

**Comment by vexe** [comment]
OK so I guess what happened was, every time I import the plugin I get compile errors from that Resolver and GPGSDependencies, something about JarResolver not found. The only way to have it compile is by deleting the resolver folder and the GPGSDependencies.cs file, which I guess are core to making the thing work in the first place...

**Comment by vexe** [comment]
To be more exact, that's what we're getting: "The type or namespace JarResolver doesn't exist in Google namespace"

**Comment by vexe** [comment]
The weird thing is it's not on all machines, like I have the resolver folder and it's not giving me that error. On our other machines it does...

**Comment by vexe** [comment]
Still with me? Any ideas?

**Comment by claywilkinson** [comment]
So - just to understand the last couple comments, it works on some machines and not on others?  What is the error?  Do all the machines have all the same versions installed (especially the Android SDK components?)

**Comment by vexe** [comment]
Do the machines have to have the same Android SDK for GooglePlayGames plugin to compile in Unity? - Cause that's what the issue is right now, the plugin just doesn't compile on some machines (error mentioned above, about the resolver)

**Comment by vexe** [comment]
I was just messing around with Jar files trying to resolve that dex issue, I removed the GPG resolver folder, when I was done I discarded all the changes so now the GPG resolver files are back, and I got the error "Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs(21,18): error CS0234: The type or namespace name `JarResolver' does not exist in the namespace `Google'. Are you missing an assembly reference?" - On the same machine that had it initially working/not throwing compile errors.

**Comment by Marurban** [comment]
Any ideas how to fix this error? 'JarResolver' does not exist in the namespace Google'
