### ISSUE TITLE
Nearby for ios ?

### ISSUE THREAD

**Issue by jonathanleang** [playgameservices/play-games-plugin-for-unity#1117]
Hi, 

Just a question regarding iOS Nearby support in this plugin.

Nearby Messages API is available for Android and iOS (beta)  https://developers.google.com/nearby/

Why is nearby connections feature is currently only available on Android in this plugin ?

is there a fork working on this already ?

**Comment by claywilkinson** [comment]
There's no support for nearby on iOS yet, it's on the list.  The main issue is the underlying SDK for nearby connections is not available on iOS yet.

Thanks for the question - I'll pass it along to make sure everyone knows there is interest!

**Comment by jonathanleang** [comment]
any ideas on when it will be available ? we are working on a new game similar to our old game Blackmoor. it will be very useful for us to have nearby, it is one of the most asked feature for our games.

<https://play.google.com/store/apps/details?id=com.mooffgames.blackmoor&hl=en>

**Comment by khoatd92** [comment]
@jonathanleang I got the same issue with you. Do you know any services to support to get nearby devices for android and ios? I can not wait until Google support iOS for nearby connection.

**Comment by claywilkinson** [comment]
Unfortunately, support for iOS has been deprecated, so there will be no updates for iOS.
https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
