### ISSUE TITLE
Importing Issues With Google Play Package

### ISSUE THREAD

**Issue by VectorScalar** [playgameservices/play-games-plugin-for-unity#1119]
I seem to be having issues with the google play plugin after I import and set things up. It always gives me the same error either when it gets imported or when I press play in the editor. There seems to be nothing to fix it. At this point I have tried rebuilding the library, updating unity to latest version, Resolving client jars, deleting and re-importing the package and reading pretty much anything I could find on the topic. Any help would be greatly appreciated as Ive been at this for 3-4 days trying to find the issue. I'm using unity 5.3.4f1 and the 0.9.32 google play plugin

This is the error I am getting:

FileNotFoundException: Could not load file or assembly 'GooglePlayServices' or one of its dependencies. The system cannot find the file specified.
System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, Boolean refonly) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/AppDomain.cs:746)
System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/AppDomain.cs:733)
(wrapper remoting-invoke-with-check) System.AppDomain:Load (string,System.Security.Policy.Evidence)
System.Reflection.Assembly.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/Assembly.cs:584)
System.Activator.CreateInstance (System.String assemblyName, System.String typeName, Boolean ignoreCase, BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Security.Policy.Evidence securityInfo) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:170)
System.Activator.CreateInstance (System.String assemblyName, System.String typeName, System.Object[] activationAttributes) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:158)
System.Activator.CreateInstance (System.String assemblyName, System.String typeName) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:150)
GooglePlayServices.PlayServicesResolver.get_Resolver () (at assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:96)
GooglePlayServices.PlayServicesResolver.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[]
movedFromAssetPaths) (at assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:115)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:27)
UnityEditor.AssetDatabase:Refresh()
GooglePlayGames.Editor.GPGSUpgrader:.cctor() (at assets/GooglePlayGames/Editor/GPGSUpgrader.cs:107)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

**Comment by realshobu** [comment]
I have exactly same problem. no solution?

**Comment by claywilkinson** [comment]
It looks like there is a problem loading the PlayServicesResolver dlls?  
A quick workaround might be to disable background resolution of the jars (Assets/Google Play Services/Settings) and then restart Unity.  

If that does not work try deleting the PlayServicesResolver directory and re-importing the plugin.

**Comment by EricUnityGameDev** [comment]
I'm getting the exact same error. I tried both those solutions, the background resolution was already disabled, and reimporting PlayServicesResolver had no effect.

Are there any other things I could try?

**Comment by claywilkinson** [comment]
The jar resolver has been updated multiple times over the last year.  Please open a new issue if you are still experiencing problems with the latest plugin.
