### ISSUE TITLE
Getting invalid token, how to debug it? Maybe its a bug?

### ISSUE THREAD

**Issue by naleksander** [playgameservices/play-games-plugin-for-unity#112]
Hi!

I have setup google game service and google APIs & auth credentials properly. Game also is marked as using google game service.

Now when connecting from Android 4.1.2 with GooglePlayGamesPlugin-0.9.01.unitypackage and Unity 4.2.3, I keep getting:

04-24 19:56:28.468: W/imp(14245): Authentication error: Unable to respond to any of these challenges: {bearer=WWW-Authenticate: Bearer realm="https://accounts.google.com/AuthSubRequest", error=invalid_token}
04-24 19:56:28.473: W/NetworkManagementSocketTagger(14245): untagSocket(64) failed with errno -22
04-24 19:56:28.473: E/Volley(14245): [883] st.a: Unexpected response code 401 for https://www.googleapis.com/games/v1/players/xxxxxx
04-24 19:56:28.568: E/SignInIntentService(14245): There is no linked app associated with this client ID.

It there any chance to see the token so I can't debug it myself with https://www.googleapis.com/oauth2/v1/userinfo?access_token=

Note that game was already published (released first version without google game service support) and game service with leaderboard is also already published and I'm trying to access it from developed next app version with tester account which is different from my google developer console account.

Thanks in advance!

**Comment by claywilkinson** [comment]
@naleksander  - I am closing this issue since it has been a long time and I imagine you have figured out what is wrong.  Please re-open this issue if you are still having this problem with the latest plugin. Thanks!
