### ISSUE TITLE
ERROR: Attempted to update a stale version of the match

### ISSUE THREAD

**Issue by v2k** [playgameservices/play-games-plugin-for-unity#1121]
`Expected version was 11 but current version is 12.` 

This may be an issue on my end, but I have a case where a player is able to take two turns in a row; when he takes the second consecutive turn, I seem to always get this error.

I assume this is because when TakeTurn is called with the same player as the pendingParticipant, the WithMatchDelegate is not getting triggered locally to update the mVersion count.  So the second call to TakeTurn has the mVersion mismatch.

version: 0.9.32

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
