### ISSUE TITLE
java.lang.NoClassDefFoundError: android/os/AsyncTask

### ISSUE THREAD

**Issue by fmmarzoa** [playgameservices/play-games-plugin-for-unity#1124]
I am experienced this crash with a bunch of devices. Seems to be related to Admob/GPGS. Here's the stack trace:

0   java.lang.NoClassDefFoundError: android/os/AsyncTask
1   at android.webkit.WebView.setupPackageListener(WebView.java:1307)
2   at android.webkit.WebView.<init>(WebView.java:1155)
3   at android.webkit.WebView.<init>(WebView.java:1116)
4   at android.webkit.WebView.<init>(WebView.java:1105)
5   at android.webkit.WebView.<init>(WebView.java:1095)
6   at android.webkit.WebView.<init>(WebView.java:1086)
7   at maps.be.f.b(:com.google.android.gms.alldynamite:403)
8   at maps.be.f.a(:com.google.android.gms.alldynamite:386)
9   at maps.bc.c.a(:com.google.android.gms.alldynamite:293)
10  at com.google.android.gms.ads.internal.a.<init>(:com.google.android.gms.alldynamite:143)
11  at com.google.android.gms.ads.internal.b.<init>(:com.google.android.gms.alldynamite:92)
12  at com.google.android.gms.ads.internal.b.<init>(:com.google.android.gms.alldynamite:82)
13  at com.google.android.gms.ads.internal.c.<init>(:com.google.android.gms.alldynamite:49)
14  at com.google.android.gms.ads.internal.f.<init>(:com.google.android.gms.alldynamite:83)
15  at com.google.android.gms.ads.ChimeraAdManagerCreatorImpl.a(:com.google.android.gms.alldynamite:61)
16  at com.google.android.gms.ads.internal.client.t$a.onTransact(:com.google.android.gms.alldynamite:91)
17  at android.os.Binder.transact(Binder.java:297)
18  at com.google.android.gms.ads.internal.client.al.a(:com.google.android.gms:170)
19  at com.google.android.gms.ads.AdManagerCreatorImpl.a(:com.google.android.gms:90)
20  at com.google.android.gms.ads.internal.client.ak.onTransact(:com.google.android.gms:91)
21  at android.os.Binder.transact(Binder.java:297)
!   22  at com.google.android.gms.ads.internal.client.zzv$zza$zza.zza(Unknown Source)
23  at com.google.android.gms.ads.internal.client.zze.zza(Unknown Source)
24  at com.google.android.gms.ads.internal.client.zze.zza(Unknown Source)
25  at com.google.android.gms.ads.internal.client.zzab.zzdh(Unknown Source)
26  at com.google.android.gms.ads.internal.client.zzab.zzdg(Unknown Source)
27  at com.google.android.gms.ads.internal.client.zzab.zza(Unknown Source)
28  at com.google.android.gms.ads.BaseAdView.loadAd(Unknown Source)
29  at com.google.android.gms.ads.AdView.loadAd(Unknown Source)
30  at com.google.unity.ads.Banner$2.run(Banner.java:191)
31  at android.os.Handler.handleCallback(Handler.java:605)
32  at android.os.Handler.dispatchMessage(Handler.java:92)
33  at android.os.Looper.loop(Looper.java:137)
34  at android.app.ActivityThread.main(ActivityThread.java:4476)
35  at java.lang.reflect.Method.invokeNative(Native Method)
36  at java.lang.reflect.Method.invoke(Method.java:511)
37  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
38  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:583)
39  at dalvik.system.NativeStart.main(Native Method)

The version of the plugin we are using right now directly from the version.xml plugin's file:
./Android/google-play-services_lib/res/values/version.xml:    <integer name="google_play_services_version">8487000</integer>

Not sure which version is that since it was updated by my partner and right now hasn't dawn in his timezone so I can't get information from him about that. I guess is 8.4.x

I am not sure whether this is a problem with the plugin itself or it is about something installed on those devices. In any case, I would be very thankfully if someone could help me to address this, since it is the most common crash our game is experiencing right now by far.

Thanks a lot in advance,

**Comment by rsiddub** [comment]
I had a similar issue (not exactly same though). Seems that 8.4.x has a added play-services-basement-*.aar. (i.e some definitions from play-services-base.*.aar are moved to play-services-basement.*.aar) 
So adding play-services-basement-8.4.0.aar solved the issue for me.
