### ISSUE TITLE
GetAccessToken remains null

### ISSUE THREAD

**Issue by VivekDeshpande** [playgameservices/play-games-plugin-for-unity#1126]
I'm trying to integrate this plugin into a test project and require the access token after login in order to link the google account with PlayFab's service.

I have setup everthing on the Google developer console and inside Unity too. However, even in the Minimal demo scene whenever I build and deploy to an Android device, even after a successful login, the Access Token always remains null.

Log below : 

> 04-26 19:50:59.948: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:50:59 +05:30 DEBUG: Activating PlayGamesPlatform.
> 04-26 19:50:59.948: I/Unity(17160):  
> 04-26 19:50:59.948: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:50:59.949: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:50:59 +05:30 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
> 04-26 19:50:59.949: I/Unity(17160):  
> 04-26 19:50:59.949: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:50:59.950: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:50:59 +05:30 DEBUG: Creating platform-specific Play Games client.
> 04-26 19:50:59.950: I/Unity(17160):  
> 04-26 19:50:59.950: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:50:59.950: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:50:59 +05:30 DEBUG: Creating Android IPlayGamesClient Client
> 04-26 19:50:59.950: I/Unity(17160):  
> 04-26 19:50:59.950: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:50:59.957: D/GamesUnitySDK(17160): Performing Android initialization of the GPG SDK
> 04-26 19:51:00.024: I/Unity(17160): Building GPG services, implicitly attempts silent auth
> 04-26 19:51:00.024: I/Unity(17160):  
> 04-26 19:51:00.024: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.180: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:51:00 +05:30 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
> 04-26 19:51:00.180: I/Unity(17160):  
> 04-26 19:51:00.180: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.200: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:51:00 +05:30 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback
> 04-26 19:51:00.200: I/Unity(17160):  
> 04-26 19:51:00.200: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.205: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:51:00 +05:30 DEBUG: Populating User
> 04-26 19:51:00.205: I/Unity(17160):  
> 04-26 19:51:00.205: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.217: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:51:00 +05:30 DEBUG: Found User: [Player: 'hypernovatester' (id g13342985356956362213)]
> 04-26 19:51:00.217: I/Unity(17160):  
> 04-26 19:51:00.217: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.217: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:51:00 +05:30 DEBUG: Maybe finish for User
> 04-26 19:51:00.217: I/Unity(17160):  
> 04-26 19:51:00.217: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.218: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:51:00 +05:30 DEBUG: Auth not finished. User=[Player: 'hypernovatester' (id g13342985356956362213)] achievements=
> 04-26 19:51:00.218: I/Unity(17160):  
> 04-26 19:51:00.218: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.219: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:51:00 +05:30 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback
> 04-26 19:51:00.219: I/Unity(17160):  
> 04-26 19:51:00.219: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.223: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:51:00 +05:30 DEBUG: Populating Achievements, status = VALID
> 04-26 19:51:00.223: I/Unity(17160):  
> 04-26 19:51:00.223: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.242: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:51:00 +05:30 DEBUG: Found 5 Achievements
> 04-26 19:51:00.242: I/Unity(17160):  
> 04-26 19:51:00.242: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.242: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:51:00 +05:30 DEBUG: Maybe finish for Achievements
> 04-26 19:51:00.242: I/Unity(17160):  
> 04-26 19:51:00.242: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.242: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:51:00 +05:30 DEBUG: Auth finished. Proceeding.
> 04-26 19:51:00.242: I/Unity(17160):  
> 04-26 19:51:00.242: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.242: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:51:00 +05:30 DEBUG: Invoking Callbacks: System.Action`1[System.Boolean]
> 04-26 19:51:00.242: I/Unity(17160):  
> 04-26 19:51:00.242: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.376: I/Unity(17160):  [Play Games Plugin DLL] 04/26/16 19:51:00 +05:30 DEBUG: Invoking user callback on game thread
> 04-26 19:51:00.376: I/Unity(17160):  
> 04-26 19:51:00.376: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.376: I/Unity(17160): Successful Android login
> 04-26 19:51:00.376: I/Unity(17160):  
> 04-26 19:51:00.376: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.380: I/Unity(17160): Token is : 
> 04-26 19:51:00.380: I/Unity(17160):  
> 04-26 19:51:00.380: I/Unity(17160): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 04-26 19:51:00.463: I/Unity(17160): ---- [0] -- 500170777

I have followed the FAQ and double checked every step. Not sure exactly what the problem is here.

**Comment by claywilkinson** [comment]
Can you share an unfiltered logcat?  The main thing to check is  that the web client id is configured in the setup dialog, and that web client id is for a web app that is linked to your game definition in the play games dev console.

**Comment by claywilkinson** [comment]
Closing since there has not been activity in close to a year.  Please re-open including logs and configuration information.  Thanks!
