### ISSUE TITLE
(TurnBased) WithMatchDelegate: Android [Yes], iOS [No]

### ISSUE THREAD

**Issue by v2k** [playgameservices/play-games-plugin-for-unity#1130]
On Android WithMatchDelegate works as expected and the delegate gets hit as soon as the match update comes down the pipe.

On iOS, it seems that calling another function can coax it into triggering the delegates.  Otherwise, the delegate never gets called.

i.e. calling PlayGamesPlatform.Instance.TurnBased.AcceptFromInbox() (and just exiting the UI right away)

Anyone else seeing behaviour like this?

**Comment by v2k** [comment]
could this be a build setting to enable threading on iOS?

**Comment by v2k** [comment]
[iOS Only]
With PlayGamesPlatform.DebugLogEnable = true, nothing hits.  It appears as though nothing gets called while the game is running, unless I call AcceptFromInbox.  As soon as AcceptFromInbox is called, the delegate fires.

If the game isn't open or is running in the background, it the iPhone gets the push notification that it's their turn.

Could this be a build setting on Xcode?

**Comment by v2k** [comment]
With more testing, this just seems unreliable period.  Even on Android, sometimes it just never hits.  Not sure if this is an issue with the plugin or google play services.

**Comment by melayerjohn** [comment]
Having same issue.. not found any solution on it yet...

**Comment by seanfcastillo** [comment]
Same issue here. You can even see this issue if you just build and run the TicTacToss demo on iOS. Has anyone found a way to force the WithMatchDelegate to fire without opening the inbox? I would like to implement a periodic check in the background as a workaround, but I don't want the inbox screen popping up.

**Comment by GorkaIllarra** [comment]
We are having same issue here #1636, but we are not even receiving push notificatons on IOS when the game is not running or running in background. Did you find any workaround for this?
Thanks a lot

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
