### ISSUE TITLE
"ERROR_NOT_AUTHORIZED" on my android phone when I try to sign in.

### ISSUE THREAD

**Issue by EricUnityGameDev** [playgameservices/play-games-plugin-for-unity#1131]
I'm getting an error whenever I try to sign in. I'm not getting any errors in the editor. I get this error on my phone when I run the game:
[http://imgur.com/bCLw3AE](http://imgur.com/bCLw3AE)

Without looking at the errors, it looks like it works. The sign in window appears and I can select my gmail account. However, I can't perform any social actions after that. When I try to show the leaderboards, I get a null reference exception.

Can anyone help or tell me when these errors mean? Huge thank you to anyone who can help. I've been on the problem for a few days now.

**Comment by v2k** [comment]
This is often because the app wasn't configured properly (see the steps in the readme regarding 'Configure Your Game') or you haven't given the account you're trying to login with access in the developer console for your app.

**Comment by alectora** [comment]
Hi,

Just want to highlight that I also have the same problem here as displayed on Eric's log. This is my log without Unity filter [log](https://pastebin.com/Md4Ujg8f).

Visually the difference is I don't even have the sign in window appears. I also tried removing my Google account, nothing appears, but the log error is almost exactly the same as you can see in the log.

I have followed many instructions I gathered from the possible same issues in here (including the Configure Your Game). I have:
- created a game app in Google Play Console
- added new Game services and have it linked with the game app, authorized (I have attempted both auto and manual SHA1 key insertion)
- created the keystore from Unity and use it to build the apk and run on the device
- the game SHA1 matched with the one from Google API, using the keytool to check.
- added my gmail account to Google Play console tester, and have it on Game services testing access
- performed the Android Configuration found in Window > Google Play Games > Setup > Android Setup (this includes performing Get resources by creating a leaderboard). I've assured the app_id is number only and matched with the one in Game services
- updated my SDK tools to the latest and added required libraries (Android Support Repository, Google Play services, Google Repository)
- setup the package name correctly on Unity and the one in Game services' linked app.

I'm using JDK 1.8, and Unity 5.5.0f3, with NDK r10e, SDK 4.4.2 (API 19), 6.0 (API 23), and 7.0 (API 24).
My minimum API level for the game is API 19.

Please let me know if I miss something.

**Comment by claywilkinson** [comment]
The plugin attempts a silent authentication when initializing.  It is OK for this to fail.  When Authenticate() is explicitly called, it will display the UI and sign in.  If it is configured correctly, it will succeed, otherwise there should be some indication of the error cause in the log.
