### ISSUE TITLE
Different user id on android and iOS - 0.9.30

### ISSUE THREAD

**Issue by MildaGenius** [playgameservices/play-games-plugin-for-unity#1132]
Hi,
we found problem, that this code return different user id on different platform.

`GooglePlayGames.PlayGamesPlatform.Instance.GetUserId();`

Android: **g004520354...**
iOS: **108586408195...**

So we are not able to link users from iOS on android.

We have gmail account where is user id the same on both platforms, but we found account (1 month old) with different ids.

I read about using Player.Id for identification, but I didnt found where can access this id.

Is this known issue?

**Comment by MildaGenius** [comment]
So, nobody has the same experience?

I investigate it and found, that different id is directly in response from Google.

**Comment by claywilkinson** [comment]
I passed your observation over to the engineering team for the backend services.  I haven't heard anything yet.  Does it happen for all users, or just this one?  Has that user seen the new gamer id on an Android game where they had to select a nickname or does it come up as the real name of person.

**Comment by MildaGenius** [comment]
It looks like is for new users. On old users (over 5 years) are both ids the same.

Today a tested with brand new user with the same result.
1. create new google email account
2. add new account to android device (allow application data sync)
3. started testing app
4. login to new account
5. create gamer id (used prepared - DreadedMagic356)
6. confirmed permissions
7. authorization done with id: g05838155... userName:DreadedMagic356

8. start test app on iPad
9. login to the same account
10. confirmed permissions
11. authorization done with id: 11453719... userName:DreadedMagic356

**Comment by MildaGenius** [comment]
Some progress with this issue?

I can send repro project if it helps.

**Comment by claywilkinson** [comment]
I've passed along the information (thanks for that).  I don't have an update yet, but as soon as I do, I'll update this issue.

**Comment by syedammarzia** [comment]
Any update on this issue? We are planning to release our game in a week's time but this issue is causing the road block.

**Comment by claywilkinson** [comment]
The player IDs will be different in many cases if a player is playing your game both on iOS and Android.  This problem is somewhat minimized since now Gamer profile creation is no longer supported on iOS.  See:  https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html for more information.
