### ISSUE TITLE
Google Play Leaderboard not showing up after trying to post score to leaderboard in Unity3d

### ISSUE THREAD

**Issue by tonyjoseph456** [playgameservices/play-games-plugin-for-unity#1135]
I have enabled google play games plugin in my Unity Project. The Unity version is 5.3.4f1. The google play games plugin version is 0.9.32. I have successfully logged in to the google play games service in my project. After submitting the score,and when I try to view the leaderboard, its showing an error like this in the log:

```
04-29 09:58:53.537: I/Unity(6910):  [Play Games Plugin DLL] 04/29/16 9:58:53 +05:30 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler

04-29 09:58:53.537: I/Unity(6910): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

04-29 09:58:53.575: I/Unity(6910):  [Play Games Plugin DLL] 04/29/16 9:58:53 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

04-29 09:58:53.575: I/Unity(6910): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

04-29 09:58:55.940: D/GamesUnitySDK(6910): Forwarding OnActivityResult

04-29 09:58:55.963: D/GamesUnitySDK(6910): Forwarding OnActivityResult Finished

04-29 09:58:55.999: I/Unity(6910):  [Play Games Plugin DLL] 04/29/16 9:58:55 +05:30 DEBUG: Showing UI Internal callback: ERROR_NOT_AUTHORIZED

04-29 09:58:55.999: I/Unity(6910): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

04-29 09:58:56.077: I/Unity(6910):  [Play Games Plugin DLL] 04/29/16 9:58:56 +05:30 DEBUG: Invoking user callback on game thread

04-29 09:58:56.077: I/Unity(6910): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

04-29 09:58:56.085: I/Unity(6910):  [Play Games Plugin DLL] 04/29/16 9:58:56 +05:30 DEBUG: Received UI callback: ERROR_NOT_AUTHORIZED

04-29 09:58:56.085: I/Unity(6910): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

04-29 09:59:54.185: I/Unity(6910):  [Play Games Plugin DLL] 04/29/16 9:59:54 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

04-29 09:59:54.185: I/Unity(6910): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
```

I'm getting an error like this

> DEBUG: Received UI callback: ERROR_NOT_AUTHORIZED

I have successfully logged in also, but still its showing as Error not authorized. Here is my code.

```
using GooglePlayGames;
using GooglePlayGames.BasicApi;

public class GooglePlayGameService : MonoBehaviour {
void Start()
{
    PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
   .RequireGooglePlus()
   .Build();

    PlayGamesPlatform.InitializeInstance(config);
    PlayGamesPlatform.DebugLogEnabled = true;
    PlayGamesPlatform.Activate();

    Social.localUser.Authenticate((bool Success)=>{
        if(Success)
        {
            mStatusText = "Welcome " + Social.localUser.userName;
            Debug.Log("Success Google Play Games");
        }
    else
    {
        mStatusText = "Authentication failed.";
        //ShowNextScene ();
        Debug.Log("failed Google Play Games");
    }

});
}
}

public void ShowScoreBoard()
{
   Debug.Log("User Authenticated: " + Social.localUser.authenticated); 
   if (Social.localUser.authenticated)
        ((PlayGamesPlatform)Social.Active).ShowLeaderboardUI("leaderboard id here");
}
```

When I check whether the user is authenticated or not, it is returning true, when I debug it. But the leaderboard is not showing up. can some one please help me in solving this error. Thanks in advance.

**Comment by 0xsven** [comment]
Have you replaced "leaderboard id here" with your leaderboard id?

**Comment by claywilkinson** [comment]
Can you share the log of when you are showing the leaderboard? (and you replaced `leaderboard id here` with the actual ID when you tested, right?)

**Comment by tonyjoseph456** [comment]
@claywilkinson I have given my actual leaderboard id in the place `leaderboard id here`. I will paste the full log here below. I have uninstalled the game, disconnected it from the list of connected apps in Google Settings and installed the game again and opened again. From there onwards, I have given the adb log.Initially it login successfully to the google play account, and when I pressed the button to show leaderboard it shows the empty leaderboard. After finishing a level, I try to post the score to the leaderboard using the code given on bottom of the comment, and then try to view the leaderboard after posting the score. Now the leaderboard blue window pops up for a second, and then goes away, without showing the leaderboard. This is what it happens in the adb log. When I press the button to show the leaderboard, the log **Going to show leaderboard for the game** will be shown.This is marked in bold in the log, and after that the error comes. 

05-11 09:49:30.018: D/Unity(14902): GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_sync GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_
05-11 09:49:30.018: D/Unity(14902): texture_sRGB_decode GL_EXT_texture_filter_anisotropic GL_EXT_multisampled_render_to_texture GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_disjoint_timer_query 
05-11 09:49:32.853: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:32 +05:30 DEBUG: Activating PlayGamesPlatform.
05-11 09:49:32.853: I/Unity(14902):  
05-11 09:49:32.853: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:32.858: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:32 +05:30 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
05-11 09:49:32.858: I/Unity(14902):  
05-11 09:49:32.858: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:32.860: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:32 +05:30 DEBUG: Creating platform-specific Play Games client.
05-11 09:49:32.860: I/Unity(14902):  
05-11 09:49:32.860: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:32.862: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:32 +05:30 DEBUG: Creating Android IPlayGamesClient Client
05-11 09:49:32.862: I/Unity(14902):  
05-11 09:49:32.862: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:32.904: D/GamesUnitySDK(14902): Performing Android initialization of the GPG SDK
05-11 09:49:33.063: I/Unity(14902): Building GPG services, implicitly attempts silent auth
05-11 09:49:33.063: I/Unity(14902):  
05-11 09:49:33.063: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:34.062: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:34 +05:30 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
05-11 09:49:34.062: I/Unity(14902):  
05-11 09:49:34.062: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:34.062: I/Unity(14902): Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
05-11 09:49:34.062: I/Unity(14902):  
05-11 09:49:34.062: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:34.064: I/Unity(14902): there are pending auth callbacks - starting AuthUI
05-11 09:49:34.064: I/Unity(14902):  
05-11 09:49:34.064: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:35.786: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:35 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
05-11 09:49:35.786: I/Unity(14902):  
05-11 09:49:35.786: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:47.836: I/Unity(14902): Failed
05-11 09:49:47.836: I/Unity(14902):  
05-11 09:49:47.836: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:48.118: W/Unity(14902): The referenced script on this Behaviour (Game Object 'InMobiAndroidEventListener') is missing!
05-11 09:49:48.118: W/Unity(14902):  
05-11 09:49:48.118: W/Unity(14902): (Filename:  Line: 1655)
05-11 09:49:48.217: I/Unity(14902): Game Level0
05-11 09:49:48.217: I/Unity(14902):  
05-11 09:49:48.217: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:49.795: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:49 +05:30 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
05-11 09:49:49.795: I/Unity(14902):  
05-11 09:49:49.795: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:49.861: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:49 +05:30 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback
05-11 09:49:49.861: I/Unity(14902):  
05-11 09:49:49.861: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:49.871: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:49 +05:30 DEBUG: Populating User
05-11 09:49:49.871: I/Unity(14902):  
05-11 09:49:49.871: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:49.904: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:49 +05:30 DEBUG: Found User: [Player: 'testgamer766' (id 101918423707947037914)]
05-11 09:49:49.904: I/Unity(14902):  
05-11 09:49:49.904: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:49.904: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:49 +05:30 DEBUG: Maybe finish for User
05-11 09:49:49.904: I/Unity(14902):  
05-11 09:49:49.904: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:49.907: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:49 +05:30 DEBUG: Auth not finished. User=[Player: 'testgamer766' (id 101918423707947037914)] achievements=
05-11 09:49:49.907: I/Unity(14902):  
05-11 09:49:49.907: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:52.407: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:52 +05:30 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback
05-11 09:49:52.407: I/Unity(14902):  
05-11 09:49:52.407: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:52.421: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:52 +05:30 DEBUG: Populating Achievements, status = VALID
05-11 09:49:52.421: I/Unity(14902):  
05-11 09:49:52.421: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:52.521: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:52 +05:30 DEBUG: Found 5 Achievements
05-11 09:49:52.521: I/Unity(14902):  
05-11 09:49:52.521: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:52.521: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:52 +05:30 DEBUG: Maybe finish for Achievements
05-11 09:49:52.521: I/Unity(14902):  
05-11 09:49:52.521: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:52.522: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:52 +05:30 DEBUG: Auth finished. Proceeding.
05-11 09:49:52.522: I/Unity(14902):  
05-11 09:49:52.522: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:52.522: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:52 +05:30 DEBUG: Invoking Callbacks: System.Action`1[System.Boolean]
05-11 09:49:52.522: I/Unity(14902):  
05-11 09:49:52.522: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:52.537: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:52 +05:30 DEBUG: Invoking user callback on game thread
05-11 09:49:52.537: I/Unity(14902):  
05-11 09:49:52.537: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:52.543: I/Unity(14902): Success Google Play Games
05-11 09:49:52.543: I/Unity(14902):  
05-11 09:49:52.543: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:58.555: I/Unity(14902): User Authenticated: True
05-11 09:49:58.555: I/Unity(14902):  
05-11 09:49:58.555: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:58.555: I/Unity(14902): Going to show leaderboard for the game
05-11 09:49:58.555: I/Unity(14902):  
05-11 09:49:58.555: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:58.586: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:58 +05:30 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler
05-11 09:49:58.586: I/Unity(14902):  
05-11 09:49:58.586: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:49:58.630: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:49:58 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
05-11 09:49:58.630: I/Unity(14902):  
05-11 09:49:58.630: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:50:59.018: D/GamesUnitySDK(14902): Forwarding OnActivityResult
05-11 09:50:59.019: D/GamesUnitySDK(14902): Forwarding OnActivityResult Finished
05-11 09:50:59.030: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:50:59 +05:30 DEBUG: Showing UI Internal callback: VALID
05-11 09:50:59.030: I/Unity(14902):  
05-11 09:50:59.030: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:50:59.170: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:50:59 +05:30 DEBUG: Invoking user callback on game thread
05-11 09:50:59.170: I/Unity(14902):  
05-11 09:50:59.170: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:50:59.187: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:50:59 +05:30 DEBUG: Received UI callback: VALID
05-11 09:50:59.187: I/Unity(14902):  
05-11 09:50:59.187: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:51:18.402: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:51:18 +05:30 DEBUG: ReportScore: score=59, board=CgkI7u-dwuUdEAIQBw
05-11 09:51:18.402: I/Unity(14902):  
05-11 09:51:18.402: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:51:18.408: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:51:18 +05:30 DEBUG: Native Submitting score: 59 for lb CgkI7u-dwuUdEAIQBw with metadata: 
05-11 09:51:18.408: I/Unity(14902):  
05-11 09:51:18.408: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:51:18.535: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:51:18 +05:30 DEBUG: Invoking user callback on game thread
05-11 09:51:18.535: I/Unity(14902):  
05-11 09:51:18.535: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:51:18.536: I/Unity(14902): Score posted Successfully
05-11 09:51:18.536: I/Unity(14902):  
05-11 09:51:18.536: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:51:22.810: W/Unity(14902): The referenced script on this Behaviour (Game Object 'InMobiAndroidEventListener') is missing!
05-11 09:51:22.810: W/Unity(14902):  
05-11 09:51:22.810: W/Unity(14902): (Filename:  Line: 1655)
05-11 09:51:22.904: I/Unity(14902): Game Level3
05-11 09:51:22.904: I/Unity(14902):  
05-11 09:51:22.904: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:51:59.262: I/Unity(14902): User Authenticated: True
05-11 09:51:59.262: I/Unity(14902):  
05-11 09:51:59.262: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
**05-11 09:51:59.262: I/Unity(14902): Going to show leaderboard for the game**
05-11 09:51:59.262: I/Unity(14902):  
05-11 09:51:59.262: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:51:59.267: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:51:59 +05:30 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler
05-11 09:51:59.267: I/Unity(14902):  
05-11 09:51:59.267: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:51:59.300: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:51:59 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
05-11 09:51:59.300: I/Unity(14902):  
05-11 09:51:59.300: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:52:01.529: D/GamesUnitySDK(14902): Forwarding OnActivityResult
05-11 09:52:01.587: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:52:01 +05:30 DEBUG: Showing UI Internal callback: ERROR_NOT_AUTHORIZED
05-11 09:52:01.587: I/Unity(14902):  
05-11 09:52:01.587: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:52:01.586: D/GamesUnitySDK(14902): Forwarding OnActivityResult Finished
05-11 09:52:01.668: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:52:01 +05:30 DEBUG: Invoking user callback on game thread
05-11 09:52:01.668: I/Unity(14902):  
05-11 09:52:01.668: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-11 09:52:01.669: I/Unity(14902):  [Play Games Plugin DLL] 05/11/16 9:52:01 +05:30 DEBUG: Received UI callback: ERROR_NOT_AUTHORIZED
05-11 09:52:01.669: I/Unity(14902):  
05-11 09:52:01.669: I/Unity(14902): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I have posted the score using this code below:

```
function SendScore(Score:int)
{
    Social.ReportScore(Score,"CgkI7u-duxCdUHKLPg",(function(success:boolean){
		if(success)
		{
		    Debug.Log("Score posted Successfully");
		}
		else
		{
		    Debug.Log("Score posting failed");
		}
	}));
}
```
I hope you have got all the relevant information to look into this issue. Thanks in advance.

**Comment by Hamed1984** [comment]
I have exact same problem.  in my game, save game works correctly but i can't show Leaderboard UI.

please guide me

**Comment by Hamed1984** [comment]
Why you don't answer my question?
please. my game is released and save game works. but i can't show Leaderboard UI.

**Comment by nzmkey** [comment]
I have similar issue except I am using the Leaderboard UI without the id.  The Leaderboards UI show correctly with the two leaderboards I setup.  When I click on either of the leaderboard, the window closed and return to the game.

Below is error from the log that mention auth error.

>08-03 11:11:10.860 16318 17282 E Volley  : [9701] BasicNetwork.performRequest: Unexpected response code 401 for https://www.googleapis.com/games/v1/leaderboards/scores?language=en_NZ
>08-03 11:11:10.860 16318 17283 E Volley  : [9702] BasicNetwork.performRequest: Unexpected response code 401 for https://www.googleapis.com/games/v1/applications/played
>08-03 11:11:10.870 16318  5691 E ErrorUtils: Received generic error from server: 401
>08-03 11:11:10.870 16318 17283 E ErrorUtils: Received generic error from server: 401
>08-03 11:11:10.870 16318 17283 E ErrorUtils: Received generic error from server: 401
>08-03 11:11:10.870 16318  5691 E ErrorUtils: Received generic error from server: 401
>08-03 11:11:10.870 16318  5690 W GameAgent: Volley error when reporting played
>08-03 11:11:10.870 16318  5690 W GameAgent: com.android.volley.AuthFailureError
>08-03 11:11:10.870 16318  5690 W GameAgent:     at com.android.volley.toolbox.BasicNetwork.performRequest(:com.google.android.gms:159)
>08-03 11:11:10.870 16318  5690 W GameAgent:     at iss.performRequest(:com.google.android.gms:64)
>08-03 11:11:10.870 16318  5690 W GameAgent:     at com.android.volley.NetworkDispatcher.run(:com.google.android.gms:113)
>08-03 11:11:10.890 16318  5691 E MultiDataOperation: There is no linked app associated with this client ID.
>08-03 11:11:10.890 16318  5691 E MultiDataOperation: com.google.android.gms.games.server.error.GamesException
>08-03 11:11:10.890 16318  5691 E MultiDataOperation:    at com.google.android.gms.games.server.GamesServer.getResponseBlocking(GamesServer.java:174)
>08-03 11:11:10.890 16318  5691 E MultiDataOperation:    at com.google.android.gms.games.broker.LeaderboardAgent.submitMultipleBlocking(LeaderboardAgent.java:969)
>08-03 11:11:10.890 16318  5691 E MultiDataOperation:    at com.google.android.gms.games.broker.LeaderboardAgent.submitBatchedBlocking(LeaderboardAgent.java:891)
>08-03 11:11:10.890 16318  5691 E MultiDataOperation:    at com.google.android.gms.games.broker.LeaderboardAgent.flushPendingScores(LeaderboardAgent.java:858)
>08-03 11:11:10.890 16318  5691 E MultiDataOperation:    at com.google.android.gms.games.broker.LeaderboardAgent.getRootPage(LeaderboardAgent.java:1053)
>08-03 11:11:10.890 16318  5691 E MultiDataOperation:    at com.google.android.gms.games.broker.DataBroker.getTopScoresPage(DataBroker.java:778)
>08-03 11:11:10.890 16318  5691 E MultiDataOperation:    at com.google.android.gms.games.service.operations.leaderboards.LoadScoresOperation.fetchData$b7c4c52(LoadScoresOperation.java:50)
>08-03 11:11:10.890 16318  5691 E MultiDataOperation:    at com.google.android.gms.games.service.operations.AbstractMultiDataHolderOperation.execute(AbstractMultiDataHolderOperation.java:53)
>08-03 11:11:10.890 16318  5691 E MultiDataOperation:    at com.google.android.gms.games.service.operations.GamesOperationAdapter.execute(GamesOperationAdapter.java:23)
>08-03 11:11:10.890 16318  5691 E MultiDataOperation:    at com.google.android.gms.chimera.BaseAsyncOperationService$OperationTask.run(BaseAsyncOperationService.java:177)
>08-03 11:11:10.890 16318  5691 E MultiDataOperation:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>08-03 11:11:10.890 16318  5691 E MultiDataOperation:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>08-03 11:11:10.890 16318  5691 E MultiDataOperation:    at java.lang.Thread.run(Thread.java:818)


And eventually the same error as tonyjoseph456 got

> 08-03 11:11:11.040  5547  5648 I Unity   :  [Play Games Plugin DLL] 08/03/16 11:11:11 +12:00 DEBUG: Showing UI Internal callback: ERROR_NOT_AUTHORIZED
> 08-03 11:11:11.040  5547  5648 I Unity   :
> 08-03 11:11:11.040  5547  5648 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)


I have tried both:
`Social.ShowLeaderboardUI ();`
and 
`PlayGamesPlatform.Instance.ShowLeaderboardUI();`
which behave the same.

If I change my code to pass in the leaderboard id than I got the exact behavior as tonyjoseph456 

Google play plugin is 0.9.34
Unity version is 5.3.5f1
SDK Manager is up to date with all packages

**Comment by claywilkinson** [comment]
Can you confirm that the players you are testing with are listed as testers in your game configuration on the dev console?

**Comment by nzmkey** [comment]
I can confirm the player is one of the tester in the console and the email matches.
I have also tested another player who is not a tester and got same behavior.

Note, the game services has been published.

**Comment by claywilkinson** [comment]
Thanks I'll pass along the info.

**Comment by ramoliahiten** [comment]
same issue i have... any one found solution? please share it..

**Comment by graviton57** [comment]
same issue i have.

**Comment by ramoliahiten** [comment]
In my case, i was giving achievement id instead of  leaderboard id to get score. ( a silly mistake). Both  ids looks same...

**Comment by seanbajuice** [comment]
Did anyone find a solution to this problem? We are having the same issue. Leader boards popup fine but are empty. When clicking on a leader board after registering a score, it crashes.

**Comment by graviton57** [comment]
my problem is resolved:
[](http://stackoverflow.com/questions/32922103/play-games-services-not-working-after-upgrading-to-gms-services-8-1)

**Comment by seanbajuice** [comment]
@graviton57 how did you solve it?

**Comment by Blinkq** [comment]
Having same issue.

**Comment by gembutterfly** [comment]
same problem here. All fingerprints match, app is connected to play service. This issue happens after submitting the first score.

**Comment by seanbajuice** [comment]
We were able to resolve it by starting over from scratch all google play
integration. It was something to do with setting up the keys in a specific
order in Google Play and no way to resolve once you did it incorrectly.

**Comment by gembutterfly** [comment]
@seanbajuice could you please give me more detail about ". It was something to do with setting up the keys in a specific order in Google Play"? That would be very nice :)

Cheers

**Comment by seanbajuice** [comment]
We just started the tutorials over for google play integration. We even
created a new app and deleted the old one. Something like this.
http://www.theappguruz.com/blog/leaderboard-setup-for-android-in-unity

The problem was we created the app first and already had it in Google play
before we tried to enabled leaderboards.

Sorry I can't be more helpful, this was a year ago now!

**Comment by gembutterfly** [comment]
@seanbajuice Alright, thank you. Had hope to avoid this.

**Comment by gembutterfly** [comment]
Couldn't find a way to solve it either. I did it all again with a new package name, and it worked:

 * new package name
 * new play games service
 * new keystore
 * registered release SHA1 and debug SHA1 with Game Service
 * released new app > everything works fine now

Still looking for a way to repair the original app.

**Comment by satanas** [comment]
I tried regenerating the API Key from the Google APIs Console and it worked! Go to Credentials, select your API key and then click on "Regenerate Key".

**Comment by WILEz75** [comment]
My leaderboars work fine in default google UI. 
But I need to get my leaderboard data (scores and usernames) to put in Unity UI texts. 
How?

**Comment by hippogamesunity** [comment]
Same issue... Tried clear plugin integrations with no luck. Scores can be posted with no errors, but UI doesn't open.

**Comment by supersolid-Justy** [comment]
#1940 might help

**Comment by DevAigina** [comment]
@seanbajuice I can not tell how i feel right now. You just saved me from 1 week headache thank you so much mr.sean !

**Comment by NavidaUB** [comment]
I resolved the problem
check:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/2045#issuecomment-350335234

**Comment by burkard** [comment]
What solved the problem for me was linking the (same) app a second time (it was already published, so I couldn't start over).
I have followed the answer of the user "avianei", here:
https://stackoverflow.com/questions/32922103/play-games-services-not-working-after-upgrading-to-gms-services-8-1
