### ISSUE TITLE
[question] CreateWithInvitationScreen

### ISSUE THREAD

**Issue by v2k** [playgameservices/play-games-plugin-for-unity#1138]
This seems to work fine; however, it seems to be hard to find friends to invite.  I'm not sure this question is within the scope of this SDK, but even after adding someone to mutual Google+ circles, they don't seem to appear on the list right away.  It seems to take a while for them to appear if they appear at all.

Searching by email doesn't find the user.  Other than NearBy, is there going to be an easy way to invite a friend?

**Comment by claywilkinson** [comment]
Eventually, yes.  There is a migration under way to remove the association of the gamer account with Google plus (and the player's identity).  This means that G+ circles are no longer being used for the social network in some cases, as a result the list is empty (or mostly empty).  

Once the migration is complete the list will be better.  I currently do not know when that will be be, so stay tuned!

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
