### ISSUE TITLE
OnPeersDisconnected doesn't trigger when one of the client lose internet connection

### ISSUE THREAD

**Issue by VisalChhourm** [playgameservices/play-games-plugin-for-unity#1140]
Hello,
I have been working on Realtime multiplayer game for a while and almost release it to the store but then I encountered this problem.
Basically, I have two devices A and B. Both devices have join the room and start playing as normal when device B lost internet connection (we turned off wifi and mobile network or use unstable internet connection), device B seems to function as expected (leave the room and move to main menu) but in device A, the character of device B just standing still and `OnPeersDisconnected`on device A never get called and `Realtime.GetConnectedParticipants().Count` still equal 2 (A & B)

Is there anyway to fix or work around this?
Thanks in advance!
sorry about my grammar!

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
