### ISSUE TITLE
iOS admob ads not working

### ISSUE THREAD

**Issue by bilal3387** [playgameservices/play-games-plugin-for-unity#1142]
I'm using the latest plugin for play games and admob framework 7.7. Admob is not working.

**Comment by claywilkinson** [comment]
Did you post an issue with Admob(https://github.com/googleads/googleads-mobile-unity/issues)?  Also, you need to describe what is going wrong and maybe include a log of the problem, otherwise it is difficult to help you.

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
