### ISSUE TITLE
Issue with 100% achievements not unlocking on Android

### ISSUE THREAD

**Issue by adbourdages** [playgameservices/play-games-plugin-for-unity#1143]
In the Google Play achievements UI, there are a couple of incremental (100 steps) achievements marked as 100%, but not counted as unlocked. In code, the IsUnlocked returns false as well.

I've tried both using ReportProgress(100%) as well as SetStepsAtLeast(TotalSteps) to force the unlocking, but they don't change.

It is a bit unclear how I arrived at this state of things, since we are testing the achievements and we keep making changes to the number of steps required and resetting the progress in the dev console. But nonetheless this is unexpected behaviour.

**Comment by v2k** [comment]
Hey adbourdages ;)

I've been using ReportProgress("xyz", 100.0f, ... without issue; however, I haven't tried any incremental achievements.
