### ISSUE TITLE
Undefined symbols for architecture amv7

### ISSUE THREAD

**Issue by zo0m22** [playgameservices/play-games-plugin-for-unity#1145]
Hi,

I tried to import google play games services to a unity game with this plugin, unfortunately i faced many errors. Here is the current error when i try to build the project on Xcode :

"Undefined symbols for architecture arm64 :
"_GPG_Init", referenced from:
      _NerdGPG_GPG_Init_m1533525731 in Bulk_Assembly-CSharp_6.o
     (maybe you meant: _NerdGPG_GPG_Init_m1533525731)
  "_GPG_SetGameObjectName", referenced from:
      _NerdGPG_GPG_SetGameObjectName_m226470353 in Bulk_Assembly-CSharp_6.o
     (maybe you meant: _NerdGPG_GPG_SetGameObjectName_m226470353)
  "_GPG_SignIn", referenced from:
      _NerdGPG_signIn_m1726850236 in Bulk_Assembly-CSharp_6.o
      _NerdGPG_GPG_SignIn_m1393386801 in Bulk_Assembly-CSharp_6.o
     (maybe you meant: _NerdGPG_GPG_SignIn_m1393386801)
  "_GPG_SignOut", referenced from:
      _NerdGPG_signOut_m318808581 in Bulk_Assembly-CSharp_6.o
      _NerdGPG_GPG_SignOut_m251140580 in Bulk_Assembly-CSharp_6.o
     (maybe you meant: _NerdGPG_GPG_SignOut_m251140580)
  "_GPG_TrySilentSignIn", referenced from:
      _NerdGPG_signIn_m1726850236 in Bulk_Assembly-CSharp_6.o
      _NerdGPG_GPG_TrySilentSignIn_m2072957145 in Bulk_Assembly-CSharp_6.o
     (maybe you meant: _NerdGPG_GPG_TrySilentSignIn_m2072957145)
  "_OBJC_CLASS_$_SSReadingList", referenced from:
      objc-class-ref in GoogleSignIn(please_link_SafariServices.framework_.o)"

I made some search on the web, looks like an Apple Match-O errors, here is what i've tried to fix it :
- Disabling / enabling bit code
- Disabling dead code stripping
- Reimport all frameworks

I'm using cocoapods to import frameworks, but i tried to install them manually, the error came back for architecture amv7 :(

Can someone help me pls?

Thanks
![screen shot 2016-05-06 at 16 03 13](https://cloud.githubusercontent.com/assets/19268011/15116213/51bf8472-15fa-11e6-82e9-28b5ce488d04.png)

**Comment by claywilkinson** [comment]
Just to understand what's happening - you can build OK when use cocoapods, but then when you try to re-create the project without cocoapods it does not work?  Did you try rebuilding from Unity?  You can disable the cocoapod use from the plugin by changing Assets/GooglePlayGames/Editor/GPGSPostBuild.cs, line 130 from

`w.UsingCocoaPod = CocoaPodHelper.Update(pathToBuiltProject);`

to be:

`w.UsingCocoaPod = false;`

Then add the frameworks as described in https://developers.google.com/games/services/ios/quickstart#option_2_manual_installation

**Comment by claywilkinson** [comment]
The new version of the plugin (0.9.35) integrates the required frameworks into the XCode project directly, which makes the build process for iOS much easier.
