### ISSUE TITLE
Cannot sign in on Android

### ISSUE THREAD

**Issue by BrochefortParadise** [playgameservices/play-games-plugin-for-unity#1146]
Hello,

I added Google Play Games to an Unity game, it builds well without any problems but when I try to log it starts Google Play Sign In but without any results.
Could you help me please? 
Thanks in advance.
Here's some screen which'll explain the problem better.

![20160508_171253](https://cloud.githubusercontent.com/assets/16759719/15140819/c59d6892-1694-11e6-8276-eab5816e549d.jpg)

![screenshot_2016-05-10-09-43-17](https://cloud.githubusercontent.com/assets/16759719/15140830/d019af24-1694-11e6-9a40-a6af5cea2b55.png)

![screenshot_2016-05-10-09-43-02](https://cloud.githubusercontent.com/assets/16759719/15140831/d254aa50-1694-11e6-88d9-ad953bb42b59.png)

**Comment by claywilkinson** [comment]
Can you share the log of when signing in?  Can you confirm the user is added as a tester (assuming the game is not published).

**Comment by BrochefortParadise** [comment]
Hm sorry to ask that but how can I get the log? Because there's nothing coming out from Unity console. And yes I'm sure that the user is a tester.

**Comment by claywilkinson** [comment]
You'll need to test it on a device (this plugin does not work in the Editor).  When the device is connected to your computer, you can use logcat to capture the log.  The short answer is open a command line window, and run `adb logcat` adb is part of the Android SDK.  For more details see http://developer.android.com/tools/debugging/debugging-log.html

**Comment by BrochefortParadise** [comment]
Thank you, I had no idea how to get log on mobile.
![iutlannion](https://cloud.githubusercontent.com/assets/16759719/15153088/d7aef466-16cf-11e6-92da-c7ed7eea25a9.png)

**Comment by claywilkinson** [comment]
You're welcome - it is very handy 👍 .

The last line of your screenshot looks like there is a configuration problem.  Things to check:

1. make sure you have the bundle id and the SHA1 fingerprint correctly set in an Android linked app from your game in the game console.  
2. Make sure you are signing in as a tester (i know you have checked it, but just to be  complete)
3. Copy the resources from the play games developer console (by clicking Get resources) from the leaderboard or achievement page and paste it into the Window > Google Play Games > Setup > Android Setup.

**Comment by BrochefortParadise** [comment]
The problem was coming from the bundle id, thank you very much for your help!

**Comment by claywilkinson** [comment]
You're welcome!
