### ISSUE TITLE
create  game save without Displaying saved games UI

### ISSUE THREAD

**Issue by AlexWitcher** [playgameservices/play-games-plugin-for-unity#1147]
Hi, Can some help me please?  Can i create  game save without call ShowSelectSavedGameUI (without Displaying saved games UI)?

**Comment by claywilkinson** [comment]
You can call openWithConflictResolution() passing in the name you want to use for the saved game without showing the UI:
```
((PlayGamesPlatform)Social.Active).SavedGame.OpenWithAutomaticConflictResolution(
                     filename,
                     DataSource.ReadCacheOrNetwork,
                     ConflictResolutionStrategy.UseLongestPlaytime,
                     SavedGameOpened);
```
 See #384 for a longer thread on the same issue.

**Comment by AlexWitcher** [comment]
@claywilkinson    thanks a lot))

**Comment by claywilkinson** [comment]
You're welcome!
