### ISSUE TITLE
"Received invalid filename" error

### ISSUE THREAD

**Issue by V0odo0** [playgameservices/play-games-plugin-for-unity#1148]
Hello guys. I have an issue with saving game. The readme [says](https://github.com/playgameservices/play-games-plugin-for-unity#opening-a-saved-game) that saved game needs to be opened before read/write. Following this instruction I want to create new save game for player.

Here is my code after player selecting option to create new save game

```       
 void OnSavedGameSelected(SelectUIStatus status, ISavedGameMetadata game)
        {
            if (status == SelectUIStatus.SavedGameSelected)
                PlayerData.OpenSavedGame(game.Filename);
        }

 void OpenSavedGame(string filename)
        {
            ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame;
            savedGameClient.OpenWithAutomaticConflictResolution(filename, DataSource.ReadCacheOrNetwork, ConflictResolutionStrategy.UseLongestPlaytime, OnSavedGameOpened);
        }
```

The problem is that `OpenWithAutomaticConflictResolution` gives me error "Received invalid filename". What am I doing wrong?

**Comment by claywilkinson** [comment]
What is the value you are passing in for filename? The filename should be alphanumeric, no spaces, special characters etc.

**Comment by V0odo0** [comment]
> What is the value you are passing in for filename? The filename should be alphanumeric, no spaces, special characters etc.

As you can see in my code the value is `Filename` property of `game` object which passed from `OnSavedGameSelected` callback right after player selected option to create new save game.

**Comment by V0odo0** [comment]
Oh, nevermind. I figured it out. If `game.Filename` is empty string then it will be new save game. So we need to name it before opening and then commit update .

**Comment by andrewspalato** [comment]
@V0odo0 How do you name "game.Filename"? Its just a getter.
