### ISSUE TITLE
LoadScores() method summary specifies "Social" when its fetching "Public" in code

### ISSUE THREAD

**Issue by gopejavi** [playgameservices/play-games-plugin-for-unity#1149]
In PlayGamesPlatform.cs:
![image](https://cloud.githubusercontent.com/assets/19295252/15164976/c40fb736-1712-11e6-834a-0308e13f8d3c.png)
It specifies "Social" when it's using Public.

Just for being sure:
![image](https://cloud.githubusercontent.com/assets/19295252/15165005/f99ec810-1712-11e6-9ee2-afcae5255be6.png)

So I guess it's just a typo and "Social" should be "Public" (exactly what I want to use, and I guess the most used) but it generates confussion and time lost when studying the API methods.

Thanks for your great Games Sevices API!

**Comment by claywilkinson** [comment]
Thanks! It is a typo in the summary.
