### ISSUE TITLE
edit process of creating language folders from google play plugin

### ISSUE THREAD

**Issue by AlexWitcher** [playgameservices/play-games-plugin-for-unity#1150]
Hi all again)  I see, after build .apk,  "res" folder in build contains too many folders for languages, which was generated from google play plugin. But publisher say: "Your app should only include language folders for those languages you support in-game".  Can you help me please? How i can edit process of creating language folders from google play plugin during the build process? (before build, I removed in editor all folders for non supported languages from Plugins/Android/res folder, but .apk build contains these folders again )

and sorry please for my bad english)

**Comment by claywilkinson** [comment]
Which version of Unity are you using?  It sounds like it might be 4.x so the client libraries are being expanded into directories in your project.  If that is the case, then once the directories are added, you can turn off the automatic resolution (which is replacing what is being deleted) at Assets/Google Play Services/Settings... and uncheck "Enable background resolution".  Once it is turned off, you can modify the directory contents.

If you are using 5+, then the resources are added as part of an aar file.  To trim down these, you need to build your application in Android Studio and configure the Resource Shrinking.  See: http://tools.android.com/tech-docs/new-build-system/resource-shrinking for details.

**Comment by aditya2** [comment]
@claywilkinson  
This thread means that this plugin is putting some useless data in builds in the form of **LANGUAGES** and you've told us to use android studio to build our projects but how is this possible to build unity projects with android studio, m i missing something **NEW** here coz i've never thought of building unity projects with android studio

**Comment by AlexWitcher** [comment]
ee) thanks) i solved this, i builded "google android project" from Unity, import this to android studio as gradle project, and then i just added next line in build.gradle in "defaultConfig" :   resConfigs "en", "fr","ru","de","es","it","uk","zh-rTW","zh-rHK".
And now folder "res" in .apk archive contains only  folders for languages which included in "resConfigs" line.
 @claywilkinson  Thanks a lot))

**Comment by AlexWitcher** [comment]
@aditya2 .
Unity3d can build google android project (check mark "Google Android Project" in build settings), after this,need to import created project to Android Stuido as Gradle project. This step was quite problem for me, because i am new in Android Studio, but now problem solved. yeah)
