### ISSUE TITLE
WithInvitationDelegate and WithMatchDelegate seem not work

### ISSUE THREAD

**Issue by Liga97** [playgameservices/play-games-plugin-for-unity#1152]
Hi All,
I have followed all instructions on "play-games-plugin-for-unity" but I'm not able to send notifications to the other players I invite during a Turn-Based Multiplayer gam (Android).

That's a part of my code:

```
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
            //.EnableSavedGames()
            .WithInvitationDelegate(OnGotInvitation)

            // registers a callback for turn based match notifications.
            .WithMatchDelegate(OnGotMatch) 

            .Build();
        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.Activate();

....

PlayGamesPlatform.Instance.TurnBased.TakeTurn(mMatch, mMatchData.ToBytes(), pendingParticipantId, (bool success) =>
                               {
                                   Debug.Log("TakeTurn: " + success);
                               });
....
```

As I understood after I call "takeTurn" all the other players should receive a push notification.
I don't have any exception but...push notifications do not appear on invited devices!!

If I open "AcceptFromInbox" I can see that my turn is completed and I'm waiting the other player.

Is there something i forgot?
My account and the invited accuount are configured as testers.

Please let me...I'm going crazy! :-(

Thanks
Liga

**Comment by claywilkinson** [comment]
Is this on iOS or Android?  Can you share a log of when you call takeTurn to see if anything unusual is happening?

**Comment by Liga97** [comment]
Hi,
It's on Android.

here you can find the logcat:

```
I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599):  [Play Games Plugin DLL] 05/14/16 11:31:58 +02:00 DEBUG: ReportScore: score=20339, board=CgkIkbfpquMDEAIQAg

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599):  [Play Games Plugin DLL] 05/14/16 11:31:58 +02:00 DEBUG: Native Submitting score: 20339 for lb CgkIkbfpquMDEAIQAg with metadata: 

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599):  [Play Games Plugin DLL] 05/14/16 11:31:58 +02:00 DEBUG: Invoking user callback on game thread

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599):  [Play Games Plugin DLL] 05/14/16 11:32:26 +02:00 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599):  [Play Games Plugin DLL] 05/14/16 11:32:26 +02:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599):  [Play Games Plugin DLL] 05/14/16 11:32:48 +02:00 DEBUG: Entering internal callback for TurnBasedManager#PlayerSelectUICallback

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599):  [Play Games Plugin DLL] 05/14/16 11:32:50 +02:00 DEBUG: Entering internal callback for TurnBasedManager#InternalTurnBasedMatchCallback

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599):  [Play Games Plugin DLL] 05/14/16 11:32:50 +02:00 DEBUG: Match has no data.

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599):  [Play Games Plugin DLL] 05/14/16 11:32:50 +02:00 DEBUG: Passing converted match to user callback:[TurnBasedMatch: mMatchId=ChEKCQiRt-mq4wMQAhACGAAgARCJ0tqIqKWE-b0B, mData=, mCanRematch=False, mSelfParticipantId=p_1, mParticipants=[Participant: 'XXXXXX' (id p_1), status=Joined, player=[Player: 'XXXXXX' (id g03595338025152105169)], connected=True],[Participant: 'YYYYYY' (id p_2), status=NotInvitedYet, player=[Player: 'YYYYYY' (id g17785375265581215642)], connected=False], mPendingParticipantId=p_1, mTurnStatus=MyTurn, mMatchStatus=Active, mVariant=4294967295, mVersion=1]

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599): OnMatchStarted

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599): GooglePlay_LaunchMatch

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599): Data NULL

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599): pendingParticipantId=p_2

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599):  [Play Games Plugin DLL] 05/14/16 11:32:51 +02:00 DEBUG: Entering internal callback for TurnBasedManager#InternalTurnBasedMatchCallback

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599):  [Play Games Plugin DLL] 05/14/16 11:32:52 +02:00 DEBUG: Entering internal callback for TurnBasedManager#InternalTurnBasedMatchCallback

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

I/Unity   (21599): TakeTurn: True

I/Unity   (21599):  

I/Unity   (21599): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   (21599): 

```

Let me know if you need soomething else.

Thanks
Liga

**Comment by Liga97** [comment]
@claywilkinson 
Question: Do i need to enable or configure "Google Cloud Messaging" in order to allow my game to send/received push notifications?

Thanks
Liga

**Comment by RamGul** [comment]
I have same issue in my case If I open "AcceptFromInbox" I can see that my turn is started few minutes before..but no notification is received on player 2..log cat shows for player 2 status=NotInvitedYet...MY logic is heree.............Whats the Issue ?
void Awake(){
		i = 0;
		PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
			.EnableSavedGames()
			.WithInvitationDelegate(OnInvitationReceived) 
			.WithMatchDelegate(OnGotMatch) 
			.RequireGooglePlus()
			.Build();
		PlayGamesPlatform.InitializeInstance(config);
		PlayGamesPlatform.DebugLogEnabled = true;
		PlayGamesPlatform.Activate();
	}
	void Start () {
		pickParticpant = false;
		urTurn = false;
		if (PlayGamesPlatform.Instance.IsAuthenticated ()) {
			matchesPopUp.SetActive(true);

		} else {
			Social.localUser.Authenticate ((bool success) => {
				if (success) {
					matchesPopUp.SetActive(true);
					PlayGamesPlatform.Instance.TurnBased.RegisterMatchDelegate(OnGotMatch);
					PlayGamesPlatform.Instance.TurnBased.AcceptFromInbox(OnMatchStarted);
				} else {

				}
			});
		}
	}
	void OnGotMatch(TurnBasedMatch match, bool shouldAutoLaunch) {
		if (shouldAutoLaunch) {
			OnMatchStarted(true, match);
		} else {

			Debug.Log ("Match Not null");
			mIncomingMatch = match;
		}
	}
	public void QuickMatch(){
		PlayGamesPlatform.Instance.TurnBased.CreateWithInvitationScreen(MinOpponents, MaxOpponents,Variant, OnMatchStarted);
	}
public void initGame(TurnBasedMatch match) {
		PlayGamesPlatform.Instance.TurnBased.TakeTurn(match, myData,match.SelfParticipantId, (bool success) => {
			if (success) {
				pickParticpant=true;
				urTurn = true;
			} else {
				Debug.Log("I am here erorr   ");
			}
		});
	}
void OnMatchStarted(bool success, TurnBasedMatch match) {
		if (success) {
			// go to the game screen and play!
			myData = Encoding.ASCII.GetBytes ("initialised");
			mIncomingMatch = match;
			if (mIncomingMatch.Data == null) {
				Debug.Log ("initiation......................");
				player.transform.position = new Vector3 (0, 0, 0);
				initGame (mIncomingMatch);
			} 
			bool canPlay = (mIncomingMatch.Status == TurnBasedMatch.MatchStatus.Active &&
				mIncomingMatch.TurnStatus == TurnBasedMatch.MatchTurnStatus.MyTurn);
			if (canPlay) {
				matchesPopUp.SetActive (false);
			//	urTurn = true;
				foreach (Participant p in mIncomingMatch.Participants) {
					i++;
					Opponent=p.ParticipantId;
				}
			} else {
				// show error message
			}
	}
public void OnInvitationReceived(Invitation invitation, bool shouldAutoAccept) {
		if (shouldAutoAccept) {
		PlayGamesPlatform.Instance.TurnBased.AcceptInvitation(invitation.InvitationId, OnMatchStarted);
		} else {
			mIncomingInvitation = invitation;
		}
	}
string DecideNextToPlay()
	{
		if (mIncomingMatch.AvailableAutomatchSlots > 0)
		{
			Debug.Log("avalaible.........................");
			return null;
		}
		else
		{
		Participant opponent = GetOpponent(mIncomingMatch);
			return opponent == null ? null : opponent.ParticipantId;
		}
	}
	public static Participant GetOpponent(TurnBasedMatch match)
	{
		foreach (Participant p in match.Participants)
		{
			if (!p.ParticipantId.Equals(match.SelfParticipantId))
			{
				Debug.Log ("ParticipantID" + p);
				return p;
}
		}
		return null;
	}

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
