### ISSUE TITLE
Google Play Games with Unity, Get ID Token

### ISSUE THREAD

**Issue by FuzzySmurf** [playgameservices/play-games-plugin-for-unity#1153]
Hi, 

I hate to be "that guy" but i have an issue that I been trying to resolve for several days now. 
Stack [Link](http://stackoverflow.com/questions/37214979/google-play-services-with-unity3d-token)

Issue Details to reference instead of going to stack.

I am using google play games services with Unity 3D. Whenever I run the game on my android phone (samsung s7) I am able to login, and authenticate the user, and it returns successfully. the app logs in just like any other released game (like clash of clans). However, I need to get the ID Token. this token ends up being blank on return. I am not sure if i have a settings issues, or a configuration issue, but the token never comes back correctly. What might be the issue?

I have tried variations of this, gone over the docs, and I have google play services set up, android, and web OAuth2 Credentials set up. I have gone to Windows > Google Play Services > Android and set up the configurations to match what is on the git site (https://github.com/playgameservices/play-games-plugin-for-unity)

May or may not be relevant:

The only thing that I DO have setup that i am not actively using (which im not sure where to place this) is a ServiceAccount. but this may be a different issue entirely, because im trying to integrate to amazon too.

NOTE:

> the services say Social.PlayerInfo.... etc. and i have tried variations of this, and PlayGamesPlatform. I know playGamesPlatform works correctly on authentication, it is just not returning the token.

**Google Play Service Version Using** 0.9.32

**Unity Version:** 5.3.1f

Code Snippet:

`public void GoogleAuthenticates(Action callback = null) {`
`    PlayGamesPlatform.Instance.Authenticate((bool success) => {`
`        if(success) { //this works just fine.`
`            Debug.Log("Successfully Logged in!");`
`            PlayGamesPlatform.Instance.GetIdToken((token) => {`
`            //The token is blank :(`
`            CognitoIdentitySync.AddGoogleTokenToCognito(token);`
`            }`
`        } else`
`            Debug.Log("Login Failed!");`
`        _isGoogleLoggedIn = success;`
`        if(callback != null)`
`            callback.Invoke();`
`    });`
`}`

**Comment by claywilkinson** [comment]
Did you check "Enable Google+ " on the setup and add a web app client id? 
  As you may know, the Games login is moving to having IDs and Avatars that are specific to games vs. the player's real identity so soon the getIdToken() method will not work for any games login.

Can you share a log of what is happening when you call GetIdToken?

**Comment by FuzzySmurf** [comment]
Hi,

Yes I have the Google+ Enabled in the google developer console. 
Inside of Unity on the ribbon (Window > Google Play Services > Android) I have the Web Client ID from the google developer console that is attached with my game.

In Unity, under googleplayservices > android i did not have it checked though, because it said not recommended. I just checked it right now before trying to get a log.

It gave me this error which i never got before:
05-13 15:45:31.764: E/AndroidRuntime(16478): 	at com.google.games.bridge.TokenFragment.permissionResolved(TokenFragment.java:209)


Do i need to have the one inside unity checked to get the AccessToken?? Didnt see that anyone in any docs, just said to check the google developer console one.

05-13 15:45:31.654: I/Unity(16478): Unity: Successfully Logged in!
05-13 15:45:31.654: I/Unity(16478): UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
05-13 15:45:31.654: I/Unity(16478): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
05-13 15:45:31.654: I/Unity(16478): UnityEngine.Logger:Log(LogType, Object)
05-13 15:45:31.654: I/Unity(16478): UnityEngine.Debug:Log(Object)
05-13 15:45:31.664: I/Unity(16478): UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
05-13 15:45:31.664: I/Unity(16478): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
05-13 15:45:31.664: I/Unity(16478): UnityEngine.Logger:Log(LogType, Object)
05-13 15:45:31.664: I/Unity(16478): UnityEngine.Debug:Log(Object)
05-13 15:45:31.664: I/Unity(16478): UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
05-13 15:45:31.664: I/Unity(16478): UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator) (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineMonoBehaviourBindings.gen.cs:60)
05-13 15:45:31.684: I/Unity(16478): UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
05-13 15:45:31.684: I/Unity(16478): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
05-13 15:45:31.684: I/Unity(16478): UnityEngine.Logger:Log(LogType, Object)
05-13 15:45:31.684: I/Unity(16478): UnityEngine.Debug:Log(Object)
05-13 15:45:31.764: E/AndroidRuntime(16478): Unity version     : 5.3.1f1
05-13 15:45:31.804: W/ActivityManager(1379):   Force finishing activity com.blazewolf.beargame/com.unity3d.player.UnityPlayerActivity
05-13 15:45:31.834: I/TrayUsageStatesWatcher(27285): notePauseComponent : ComponentInfo{com.blazewolf.beargame/com.unity3d.player.UnityPlayerActivity}
05-13 15:45:32.334: W/ActivityManager(1379): Activity pause timeout for ActivityRecord{901730a u0 com.blazewolf.beargame/com.unity3d.player.UnityPlayerActivity t48 f}



I also got this error after getting Unity3D Google + enabled:
05-13 15:45:31.764: E/AndroidRuntime(16478): 	at com.google.games.bridge.TokenFragment.permissionResolved(TokenFragment.java:209)

that one is new, never got it before.

**Comment by FuzzySmurf** [comment]
Hi,

I just tried it again, and gave full approval to everything, it worked!! :+1: Guess the "not recommended" bit scared me some :x 

This issue can be closed, thank you for your help.

Out of curiosity, when is the switch over to some new ID Token method? I would like to implement it ASAP so i do not have any issues w/ my game.

thanks,
Alex M.

**Comment by claywilkinson** [comment]
I'm glad you got it working!  I don't know of a specific timeframe for the switchover right now.  If you don't already, periodically check http://android-developers.blogspot.com/ That is a typical channel to get information about changes like this one.

**Comment by LinkCore** [comment]
@FuzzySmurf  How did you get the id token? Where is the googleplayservices > android that you mentioned? I am trying to get the id token so I can authenticate with firebase.

**Comment by dhawalbanker** [comment]
@LinkCore Were you able to find the solution? 

I am able to login successfully. But I am not able to fine TokenID.

**Comment by Thaina** [comment]
I use this library along with firebase library

From the document it said it need these `idToken` and `accessToken` for calling

```C#
GoogleAuthProvider.GetCredential(googleIdToken, googleAccessToken);
```

Then when you said we could not have idToken anymore. How can we do this with firebase?

**Comment by Ranttal** [comment]
@dhawalbanker I am not able to login.
I am getting message login failed. Help me getting logged in as I am doing this for server side use.
