### ISSUE TITLE
Switch platform : Android, during installation

### ISSUE THREAD

**Issue by chomi3** [playgameservices/play-games-plugin-for-unity#1154]
Hi guys,

Thanks for making the plugin.
It's not a real Issue, but something I spent over an hour figuring out.

During the installation of the plugin, the Build Platform in Unity HAS to be set to : Android.
Before plugin installation I was building the game for Steam, and could not find the "Window/Google Play Services/..." Menu after installation. It was due to the fact the Platform in Unity was set to PC.

I believe it's something worth mentioning in the DOCs, in case anyone else will have similar issue.

Have a great day,
Bests
Mike

**Comment by claywilkinson** [comment]
Thanks for the feedback!

**Comment by claywilkinson** [comment]
Fixed in 0.9.40
