### ISSUE TITLE
Access Not Configured issue

### ISSUE THREAD

**Issue by JamesMcMahon** [playgameservices/play-games-plugin-for-unity#1157]
So I am sure you are really sick of access issues, but the docs appear to be out of date (there are a lot of screenshots and instructions that don't line up with what I am seeing) and I have no idea what I am doing wrong.

I've been logcatting my app and it looks like the core issue is:

```
05-16 21:59:25.684  14544    14659                 Volley  E  [2884] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/games/v1/players/me?language=en_US
05-16 21:59:25.725  14544    31852    SignInIntentService  E  Access Not Configured. Google Play Game Services API has not been used in project <redacted> before or it is disabled. Enable it by visiting h
                                                            ttps://console.developers.google.com/apis/api/games/overview?project=<redacted> then retry. If you enabled this API recently, wait a few minut
                                                            es for the action to propagate to our systems and retry.
05-16 21:59:25.725  14544    31852    SignInIntentService  E  com.google.android.gms.games.server.error.GamesException
```

What's interesting is that redacted project number doesn't appear to line up with Application Id I see in my dashboard and what I configured the project as.  The like to enable the game services leads me to page not connected to my project and I confirmed that my game services are in fact enabled for my project.

However, I've gone over the configuration for the plugin over and over again and looks like everything is correct. I can't find the SHA1 fingerprint in my dashboard anymore (the steps for configuration appear to have changed since the docs were written).

**Any suggestions about where to look next?** 

Also, It would be great if there was someway to in the editor to confirm that the app is configured properly.

**Comment by JamesMcMahon** [comment]
Ugh nevermind. I missed the part where you need to sign your app, which completely makes sense but I've been in the habit of not signing my test versions.

Makes sense, just wish I hadn't missed that.

**Comment by claywilkinson** [comment]
Thanks for taking the time to explain where it is confusing.  We'll try to make the instructions around signing and configuration more clear.
