### ISSUE TITLE
Old G+ player ID mixed with new Gamer ID

### ISSUE THREAD

**Issue by AliBenba** [playgameservices/play-games-plugin-for-unity#1158]
After succesfully login to play games, I still have my old ID from G+ (eg. 111196299737395567111). The problem is that, when my friend retrieve his friend list, he see me with my new Gamer ID (eg. g222296299737395567222).
Locally I see myself with my old G+ ID, while everyone else see me with my new Gamer ID.

**Comment by claywilkinson** [comment]
Thanks noting this.  Can you share with me what issue this is causing, or is it just a little confusing?

**Comment by InfiniteDreams** [comment]
It's not only confusing, but unfortunatly, it broke one of our features. 
We have implemented a feature that, when a player complete a quest, he gets a reward and all of his friends gets percent of this reward. 
We are doing it by sending to our server, each friend ID and the amount of that reward. 
Local player connect to our server with his ID to check if he has a reward from one of his friends to collect it.

**Comment by MildaGenius** [comment]
The mentioned id looks like ids which we get from different platforms (android vs. iOS).

Check my [issues](https://github.com/playgameservices/play-games-plugin-for-unity/issues/1132).

**Comment by InfiniteDreams** [comment]
According to 
http://android-developers.blogspot.com/2016/01/play-games-permissions-are-changing-in.html 
Users keep old G+ ID for the app / game that have already installed, while get new Gamer ID for the new app / game.

**Comment by MildaGenius** [comment]
In our case, new game and new gmail account.

**Comment by claywilkinson** [comment]
There is a workaround until this gets resolved.  
1. Call GetServerAuthCode() to get the auth code to send to your backend server.
2. Exchange the code for a token
3. Call [player.get](https://developers.google.com/games/services/web/api/players/get) from the REST API.
4. The return value will have the new player ID in the `playerId` field, and the old player ID in 'originalPlayerId' field - if there is an original.

Small disclaimer: I haven't had a chance to try this, so please share your findings!

**Comment by MildaGenius** [comment]
I made test of get user id from server side.

I am able to get user id after get android server auth token, but this is NOT possible on iOS.

xCode console:
`ERROR: FetchServerAuthCode is only implemented for Android with Java Google Play Games Services SDK version of at least 8.4.00.`
`ERROR: Error loading server auth code: ERROR_NOT_AUTHORIZED`

So according to xCode console, this is not workaround for link users over different platforms. This was major reason for implementing GPG.

How to test server workaround:
https://developers.google.com/adwords/api/docs/guides/oauth_playground#step_1_-_get_a_client_id_and_client_secret
https://developers.google.com/games/services/web/api/players/get#request
https://www.googleapis.com/games/v1/players/me

**Comment by claywilkinson** [comment]
You can work around it on iOS by calling `[GIDSignIn sharedInstance].currentUser.serverAuthCode`  after the player has successfully logged in.

It is planned to be part of the C++ SDK in the next release, but I don't have a specific date.

Feel free to submit a pull request if you end up implementing it in a way that works with the plugin.  It might be easier however to get the code and send it to the server all from iOS (assuming you write Objective C code).

**Comment by MildaGenius** [comment]
@claywilkinson 

Tested own implementation of getting server auth code on iOS:
`  const char* _GooglePlayGetServerAuthToken()`
`   {`
`    const char* serverAuthToken = nil;`
`    NSString* user;`
`    GIDGoogleUser* guser = [GIDSignIn sharedInstance].currentUser;`

    if(guser) {
      serverAuthToken = __MakeStringCopy( [guser serverAuthCode] );
      user = [guser userID];

      NSLog(@"\n\tOS: 'iOS',\n\tBundleId: '%@',\n\tUser: '%@',\n\t AccessToken: '%s'",
            [ [NSBundle mainBundle] bundleIdentifier ], user, serverAuthToken);
    } else {
      NSLog(@"Current user is not set");
    }
    return serverAuthToken ? serverAuthToken :  __MakeStringCopy(@"");
`  }`

But its returns null after autorization:
`OS: 'iOS',
BundleId: 'com.blackelement.dronewar',
User: '114537191492791922931',
 AccessToken: '(null)'`

**Comment by mwk888** [comment]
@claywilkinson 

Hi Clay, we also just hit: _ERROR FetchServerAuthCode is only implemented for Android with Java Google Play..._

Any idea when this might be fixed? Kind of hoping not to have to learn Objective C to make this work :)

**Comment by gif-** [comment]
@claywilkinson 
Hi, I also implemented the same as @MildaGenius, MakeStringCopy from [guser serverAuthCode], according to this, it should work: https://developers.google.com/identity/sign-in/ios/api/interface_g_i_d_google_user 
But I get null after authorization. (GetUserDisplayName shows the correct name though)

**Comment by claywilkinson** [comment]
Thanks!
