### ISSUE TITLE
How to avoid unlock achievement redundantly.

### ISSUE THREAD

**Issue by kenglou** [playgameservices/play-games-plugin-for-unity#1159]
Is there a way for getting achievements list directly from google play game services so that we can save it and avoid redundancy call for already unlock achievements?

**Comment by claywilkinson** [comment]
You can get the achievements by calling [PlayGamesPlatform.Instance. LoadAchievements()](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs#L851).

**Comment by kenglou** [comment]
Thanks.
