### ISSUE TITLE
How can I build from source?

### ISSUE THREAD

**Issue by hex** [playgameservices/play-games-plugin-for-unity#1162]
I tried building from source, but I don't have access to the unity-jar-resolver repos
```
sso_jarresolver_repo = 'sso://devrel/libraries/android/unity-jar-resolver'
https_jarresolver_repo = 'https://devrel.googlesource.com/libraries/android/unity-jar-resolver'
```

I also tried to use this repo instead [https://github.com/googlesamples/unity-jar-resolver](https://github.com/googlesamples/unity-jar-resolver). It worked until it gets to the Unity task, where I get this error:
```
-----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/Assembly-CSharp-Editor.dll
Compilation failed: 1 error(s), 0 warnings
-----CompilerOutput:-stderr----------
Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs(111,38): error CS0122: `GooglePlayServices.PlayServicesResolver.Resolver' is inaccessible due to its protection level
Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs(91,13): (Location of the symbol related to previous error)
-----EndCompilerOutput---------------
```

In the `PlayServicesResolver.cs` file from /build/jarrresolver/.. the IResolver interface is private, so I manually edited the file and made `Resolver` and `HandleOverwriteConfirmation` public and managed to build it.

But is this safe? What's the proper way to build from source?

Thanks.

**Comment by claywilkinson** [comment]
Sounds like you are on the correct path.

That is the correct path - There is a pending update to googlesamples/unity-jar-resolver which fixes this.  I'll try to do this today.  I'll update the build script too so you can build from GitHub.

Thanks for the feedback!

**Comment by MildaGenius** [comment]
Thanks to hex I use the same repo for jar resolver.
But after all problems I got the same error.

So it looks, that mentioned pending update, is not still published?

**Comment by hex** [comment]
@MildaGenius you can do what I did, and make the interfaces public and it will build.

**Comment by MildaGenius** [comment]
@hex 

Something still rewriting my changes in:
`build/PluginProject/Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs`

I disabled repo clone and I made changes in different two places, 
`build/jarresolver/exploded/Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs`
`build/jarresolver/plugin/Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs`
but in project is PlayServicesResolver.cs changed back after new build.

**Comment by hex** [comment]
Use this fork https://github.com/draxov/unity-jar-resolver and make sure to delete the source/build folder everytime you start a new build.

**Comment by MildaGenius** [comment]
@hex 
thanks

BUILD SUCCESSFUL

**Comment by hex** [comment]
Glad you solved it! ;)

**Comment by claywilkinson** [comment]
I merged the changes for both the unity-jar-resolver and this plugin so it should built OK now.  Please let me know if that is not the case.
