### ISSUE TITLE
Player objects not spawning on both devices

### ISSUE THREAD

**Issue by JamaalHunte** [playgameservices/play-games-plugin-for-unity#1164]
Hello everyone

I’ve been using the google play plugin and i’ve been having some trouble getting both players to appear on both devices once a room has been created. I have some screenshots to show you what i mean

DEVICE 1
http://i.imgur.com/JjaZ4yI.png?2

DEVICE 2
http://i.imgur.com/nOaOSWg.jpg?1

As you can see, on one device, both players are visible to the user, and on the other device, only one player is visible. I can move the character that is visible on both screens and its movement will be visible on both screens, but the issue is that one of the players will always simply not appear on the other screen. I did a log cat on it and i get this error repeatedly:

05-20 08:35:39.812: I/Unity(3023): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-20 08:35:39.814: I/Unity(3023):  [Play Games Plugin DLL] 05/20/16 8:35:39 -04:00 DEBUG: Entering InternalOnDataReceived: 35
05-20 08:35:39.814: I/Unity(3023):  
05-20 08:35:39.814: I/Unity(3023): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-20 08:35:39.826: I/Unity(3023): NullReferenceException: Object reference not set to an instance of an object
05-20 08:35:39.826: I/Unity(3023):   at PlusNetworkManager.OnRealTimeMessageReceived (Boolean isReliable, System.String senderId, System.Byte[] data) [0x00000] in <filename unknown>:0 
05-20 08:35:39.826: I/Unity(3023):   at GooglePlayGames.Native.NativeRealtimeMultiplayerClient+OnGameThreadForwardingListener+<RealTimeMessageReceived>c__AnonStorey46.<>m__55 () [0x00000] in <filename unknown>:0 
05-20 08:35:39.826: I/Unity(3023):   at GooglePlayGames.OurUtils.PlayGamesHelperObject.Update () [0x00000] in <filename unknown>:0 
05-20 08:35:39.826: I/Unity(3023):  
05-20 08:35:39.826: I/Unity(3023): (Filename:  Line: -1)
05-20 08:35:41.465: I/Unity(3023):  [Play Games Plugin DLL] 05/20/16 8:35:41 -04:00 DEBUG: Entering InternalOnDataReceived: 35
05-20 08:35:41.465: I/Unity(3023):  

The error logcat shows that the problem is from GPGS only ( c__AnonStorey46 ). Currently, I’m using unity 5.3.4f1 (personal) and I’m using the most recent version of plus network from the unity asset store. Where the sdk platform is concerned I’m using android 6.0 and platform tools 23.1. For the JDK I’m using java SE development kit 8u92. Am i missing something? Has something changed on this end? 

I've also attached the unfiltered log
[FullLog.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/274564/FullLog.txt)

thanks

**Comment by JamaalHunte** [comment]
Just one small additional detail. I find that it doesn't always mess up. For every 10 tries, it may work once or twice. But most of the time, both objects fail to spawn as they should. Any idea what the problem is?@claywilkinson

**Comment by claywilkinson** [comment]
I am not familiar with the class PlusNetworkManager?  Is this something you authored? But the line in the log from OnRealtimeMessageReceived:
```
05-20 08:35:39.826: I/Unity(3023): NullReferenceException: Object reference not set to an instance of an object
```
Makes me suspect a variable is not initialized correctly?  I'd suggest finding that and fixing it which might make things work better.

**Comment by JamaalHunte** [comment]
hey @claywilkinson I went back and looked it over and i can't seem to find anything particularly wrong. When i switch to using reliable messages, this doesn't seem to happen, but when i switch to unreliable, i continue to get the issue. PlusNetworkManager is an custom script, yes..which contains all of the networking code. What im curious about though is this line

05-20 08:35:39.826: I/Unity(3023): at GooglePlayGames.Native.NativeRealtimeMultiplayerClient+OnGameThreadForwardingListener+c__AnonStorey46.<>m__55 ()

doesn't that indicate that something has changed on GPGS end?

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
