### ISSUE TITLE
GIDSignIn.h not found

### ISSUE THREAD

**Issue by sorab2142** [playgameservices/play-games-plugin-for-unity#1169]
Clean Project, 
Imported the 0.9.33 Plugin, 
Setup ios, 
No Errors in the Unity Console in Unity 5.3.3, 5.3.4, and 5.3.5, 
Pods are all linked in XCode correctly,
Pod update checks out fine as well,
Still got GIDSignIn not found in Xcode 7.3.1, 7.3 and 7.2

**Comment by Naamani** [comment]
Same here. I followed this:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/701
And had to add it here as well:
`
#import <GoogleSignIn/GIDSignIn.h>
#import <GoogleSignIn/GIDGoogleUser.h>
#import <GoogleSignIn/GIDAuthentication.h>
#import <GoogleSignIn/GIDProfileData.h>
`

Good luck

**Comment by sorab2142** [comment]
Thanks @Naamani, that worked perfectly.
