### ISSUE TITLE
Unfortunately <appname> has stopped,When quiting after PlayGamesPlatform.InitializeNearby

### ISSUE THREAD

**Issue by ArmandCloud** [playgameservices/play-games-plugin-for-unity#1171]
Hello,

I am having a Unfortunately "appname" has stopped error after Application.Quit(); If i dont initialize nearby and quit, there is no problem.

Here is some log, after quit action.

05-21 21:36:01.753 25094-25555/com.guya.dragracingproclutch V/GamesNativeSDK: Attached to JVM on thread nearby_connections
05-21 21:36:04.916 25094-25094/com.guya.dragracingproclutch I/Unity: onPause
05-21 21:36:04.967 25094-25627/com.guya.dragracingproclutch D/Unity: Setting up 1 worker threads for Enlighten.
05-21 21:36:04.967 25094-25628/com.guya.dragracingproclutch D/Unity:   Thread -> id: 84f4ba00 -> priority: 1 
05-21 21:36:05.147 25094-25126/com.guya.dragracingproclutch D/dalvikvm: Unregistering JNI method Lorg/fmod/FMODAudioDevice;.fmodProcess:IL
05-21 21:36:05.147 25094-25126/com.guya.dragracingproclutch D/dalvikvm: Unregistering JNI method Lorg/fmod/FMODAudioDevice;.fmodGetInfo:II
05-21 21:36:05.147 25094-25126/com.guya.dragracingproclutch D/dalvikvm: Unregistering JNI method Lorg/fmod/FMODAudioDevice;.fmodProcessMicData:ILI
05-21 21:36:06.758 25094-25555/com.guya.dragracingproclutch D/dalvikvm: threadid=18: thread exiting, not yet detached (count=0)
05-21 21:36:06.758 25094-25555/com.guya.dragracingproclutch V/GamesNativeSDK: Detaching from JVM on thread nearby_connections
05-21 21:36:08.910 25094-25094/com.guya.dragracingproclutch W/Unity: Timeout while trying to pause the Unity Engine.
05-21 21:36:08.920 25094-25094/com.guya.dragracingproclutch I/Choreographer: Skipped 239 frames!  The application may be doing too much work on its main thread.
05-21 21:36:08.920 25094-25094/com.guya.dragracingproclutch I/Unity: windowFocusChanged: false
05-21 21:36:08.920 25094-25094/com.guya.dragracingproclutch V/GamesNativeSDK: NearbyConnections client disconnected.
05-21 21:36:08.930 25094-25126/com.guya.dragracingproclutch 
A/libc: Fatal signal 11 (SIGSEGV) at 0x88cbcff0 (code=1), thread 25126 (main)

Regards,

**Comment by claywilkinson** [comment]
can you collect a bug report of this and I can pass it along?  To capture a bugreport you can start your app - then when it crashes (or unfortunately stops) - connect it to your computer and from a terminal window run `adb bugreport > bugreport_1171.txt` and after a while, it will finish and there will be a file *bugreport_1171.txt* in the current directory.  That report will help understand what is taking so long.

**Comment by ArmandCloud** [comment]
Thank you for quick tutorial.
[bugreport(filtered).txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/279676/bugreport.filtered.txt)

**Comment by ArmandCloud** [comment]
Do i need a clean up, after initialize nearby before quitting game.

**Comment by claywilkinson** [comment]
I've passed along the bug report - thanks.  It does look like a callback might being called?  Can you try to stop Advertising/Listening before quitting?

**Comment by ArmandCloud** [comment]
Hello Clay,
Thank you for your response.
Let me clear my script flow.
When game launches , i activate playgames platform and silent sign in.
When player wants to play local game, i initialize nearby.
When player wants to host a game i start advertising
When player wants to search local came i start discovering.
------------------------------------------------------------------------------------------
"Can you try to stop Advertising/Listening before quitting?"

I tried them. But actually  i am not starting an advertisement or listening action without a "find opponent" button or host a game button. Just initializing nearby, with sample code you provided, do nothing else.
And if I try something like this
if(PlayGamesPlatform.Nearby!=null) to Stop Advertisement to avoid null reference exception , it automatically Initilizes a nearby client.
------------------------------------------------------------------------------------------

Also I tried to WaitForSecond(5) to see if something happen before OnPause called. Nothing is happening.

You mentioned a callback. It must be fired after Application.Quit() , when Activity's OnPause Method called.
------------------------------------------------------------------------------------------

Did you reproduce this error with your setup? Or its only me. Since  nobody else participating to this thread.

 
Regards,

**Comment by claywilkinson** [comment]
Fixed in 0.9.50
