### ISSUE TITLE
Invalid classname

### ISSUE THREAD

**Issue by saurabhstudio13960** [playgameservices/play-games-plugin-for-unity#1172]
Getting error at setup:
I have given constant class name:  GPGSIds
And copy my resource, but I get this error:

Invalid classname: an exception was thrown by the type initializer for  GooglePlayGame.Editor.GPGSDependence

**Comment by claywilkinson** [comment]
Can you share the call stack of the exception?  Which version of Unity and the plugin are using?

**Comment by saurabhstudio13960** [comment]
Unity 5.3.4
GPGS 0.9.33
I updated SDK. Error has been gone. Thanks @claywilkinson .

**Comment by v2k** [comment]
I'm seeing this as well after trying to update the package. 
v0.9.33 
Unity 5.3.5f1
[screenshot](http://i.imgur.com/akFEAjk.png)

**Comment by v2k** [comment]
I've tried removing all the files from GooglePlayGames ,PlayServicesResolver along with the loose files under Plugins/Android; and reinstalling to no avail.

**Comment by v2k** [comment]
oops, updating *Android* SDK fixed it

**Comment by rossstyants** [comment]
Hmm... i'm getting this too...
v 0.9.34
Unity latest... 5.something...
i think i have installed the latest android sdk with the play services...
i guess what i don't see in my project is any plugin containing the actual play services stuff... 
com.google.android.gms",
                "play-services-games
etc....
should that be in the plugins directory ?
Thanks...

**Comment by BlackPi3** [comment]
@rossstyants i have the same problem ... could u find any solution?

**Comment by 0xsven** [comment]
same here as @rossstyants
