### ISSUE TITLE
GPS support lib conflicts with Facebook SDK

### ISSUE THREAD

**Issue by asarazan** [playgameservices/play-games-plugin-for-unity#1174]
Looks like google and facebook try to include conflicting versions of support-v4, which causes build failure due to duplicate definitions.

The more annoying thing is that I tried to simply delete google's version and it won't stop silently re-creating it every time I build.

I'm not sure there's a good answer for the duplicate support lib problem, so in the mean-time, please turn off this incredibly obnoxious behavior.

**Comment by claywilkinson** [comment]
You can turn it off in your project under Assets/Google Play Services/Settings.
