### ISSUE TITLE
CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.

### ISSUE THREAD

**Issue by rajeev77** [playgameservices/play-games-plugin-for-unity#1176]
I have integrated the plugin in new blank project to test it to make it work for my game, but i am getting this error , not sure what is happening.

Here is my log:

CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/rajeevrajani/Library/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznm;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznn;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzno;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzno$zza;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznp;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznq;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqi;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqi$zza;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqj;
9 errors; aborting
]
stdout[
processing archive /Users/rajeevrajani/Documents/Development/Unity Projects/ADMOB ADS/Temp/StagingArea/android-libraries/MainLibProj/libs/./play-games-plugin-support.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/games/
ignored resource com/google/games/bridge/
processing com/google/games/bridge/BuildConfig.class...
processing com/google/games/bridge/NativeBridgeActivity.class...
processing com/google/games/bridge/TokenFragment.class...
processing com/google/games/bridge/TokenFragment$1.class...
processing com/google/games/bridge/TokenFragment$TokenRequest.class...
processing com/google/games/bridge/TokenPendingResult.class...
processing com/google/games/bridge/TokenResult.class...
processing archive /Users/rajeevrajani/Documents/Development/Unity Projects/ADMOB ADS/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/bin/classes.jar...
ignored resource .readme
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource android/
ignored resource android/support/
ignored resource android/support/v7/
ignored resource android/support/v7/app/
processing android/support/v7/app/ActionBar.class...
processing android/support/v7/app/ActionBar$DisplayOptions.class...
processing android/support/v7/app/ActionBar$LayoutParams.class...
processing android/support/v7/app/ActionBar$NavigationMode.class...
processing android/support/v7/app/ActionBar$OnMenuVisibilityListener.class...
processing android/support/v7/app/ActionBar$OnNavigationListener.class...
processing android/support/v7/app/ActionBar$Tab.class...
processing android/support/v7/app/ActionBar$TabListener.class...
processing android/support/v7/app/ActionBarActivity.class...
processing android/support/v7/app/ActionBarDrawerToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$1.class...
processing android/support/v7/app/ActionBarDrawerToggle$Delegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$DelegateProvider.class...
processing android/support/v7/app/ActionBarDrawerToggle$DrawerArrowDrawableToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$DrawerToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$DummyDelegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$HoneycombDelegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$JellybeanMr2Delegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$ToolbarCompatDelegate.class...
processing android/support/v7/app/ActionBarDrawerToggleHoneycomb.class...
processing android/support/v7/app/ActionBarDrawerToggleHoneycomb$SetIndicatorInfo.class...
processing android/support/v7/app/AlertController.class...
processing android/support/v7/app/AlertController$1.class...
processing android/support/v7/app/AlertController$2.class...
processing android/support/v7/app/AlertController$3.class...
processing android/support/v7/app/AlertController$4.class...
processing android/support/v7/app/AlertController$5.class...
processing android/support/v7/app/AlertController$AlertParams.class...
processing android/support/v7/app/AlertController$AlertParams$1.class...
processing android/support/v7/app/AlertController$AlertParams$2.class...
processing android/support/v7/app/AlertController$AlertParams$3.class...
processing android/support/v7/app/AlertController$AlertParams$4.class...
processing android/support/v7/app/AlertController$AlertParams$OnPrepareListViewListener.class...
processing android/support/v7/app/AlertController$ButtonHandler.class...
processing android/support/v7/app/AlertController$CheckedItemAdapter.class...
processing android/support/v7/app/AlertDialog.class...
processing android/support/v7/app/AlertDialog$Builder.class...
processing android/support/v7/app/AppCompatActivity.class...
processing android/support/v7/app/AppCompatCallback.class...
processing android/support/v7/app/AppCompatDelegate.class...
processing android/support/v7/app/AppCompatDelegateImplBase.class...
processing android/support/v7/app/AppCompatDelegateImplBase$1.class...
processing android/support/v7/app/AppCompatDelegateImplBase$ActionBarDrawableToggleImpl.class...
processing android/support/v7/app/AppCompatDelegateImplBase$AppCompatWindowCallbackBase.class...
processing android/support/v7/app/AppCompatDelegateImplV11.class...
processing android/support/v7/app/AppCompatDelegateImplV14.class...
processing android/support/v7/app/AppCompatDelegateImplV14$AppCompatWindowCallbackV14.class...
processing android/support/v7/app/AppCompatDelegateImplV23.class...
processing android/support/v7/app/AppCompatDelegateImplV23$AppCompatWindowCallbackV23.class...
processing android/support/v7/app/AppCompatDelegateImplV7.class...
processing android/support/v7/app/AppCompatDelegateImplV7$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$2.class...
processing android/support/v7/app/AppCompatDelegateImplV7$3.class...
processing android/support/v7/app/AppCompatDelegateImplV7$4.class...
processing android/support/v7/app/AppCompatDelegateImplV7$5.class...
processing android/support/v7/app/AppCompatDelegateImplV7$5$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$6.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ActionMenuPresenterCallback.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ActionModeCallbackWrapperV7.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ActionModeCallbackWrapperV7$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$ListMenuDecorView.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelFeatureState.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelFeatureState$SavedState.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelFeatureState$SavedState$1.class...
processing android/support/v7/app/AppCompatDelegateImplV7$PanelMenuPresenterCallback.class...
processing android/support/v7/app/AppCompatDialog.class...
processing android/support/v7/app/AppCompatDialogFragment.class...
processing android/support/v7/app/AppCompatViewInflater.class...
processing android/support/v7/app/AppCompatViewInflater$DeclaredOnClickListener.class...
processing android/support/v7/app/NavItemSelectedListener.class...
processing android/support/v7/app/NotificationCompat.class...
processing android/support/v7/app/NotificationCompat$1.class...
processing android/support/v7/app/NotificationCompat$Builder.class...
processing android/support/v7/app/NotificationCompat$IceCreamSandwichExtender.class...
processing android/support/v7/app/NotificationCompat$JellybeanExtender.class...
processing android/support/v7/app/NotificationCompat$LollipopExtender.class...
processing android/support/v7/app/NotificationCompat$MediaStyle.class...
processing android/support/v7/app/NotificationCompatImpl21.class...
processing android/support/v7/app/NotificationCompatImplBase.class...
processing android/support/v7/app/ToolbarActionBar.class...
processing android/support/v7/app/ToolbarActionBar$1.class...
processing android/support/v7/app/ToolbarActionBar$2.class...
processing android/support/v7/app/ToolbarActionBar$ActionMenuPresenterCallback.class...
processing android/support/v7/app/ToolbarActionBar$MenuBuilderCallback.class...
processing android/support/v7/app/ToolbarActionBar$PanelMenuPresenterCallback.class...
processing android/support/v7/app/ToolbarActionBar$ToolbarCallbackWrapper.class...
processing android/support/v7/app/TwilightCalculator.class...
processing android/support/v7/app/TwilightManager.class...
processing android/support/v7/app/TwilightManager$1.class...
processing android/support/v7/app/TwilightManager$TwilightState.class...
processing android/support/v7/app/WindowDecorActionBar.class...
processing android/support/v7/app/WindowDecorActionBar$1.class...
processing android/support/v7/app/WindowDecorActionBar$2.class...
processing android/support/v7/app/WindowDecorActionBar$3.class...
processing android/support/v7/app/WindowDecorActionBar$ActionModeImpl.class...
processing android/support/v7/app/WindowDecorActionBar$TabImpl.class...
ignored resource android/support/v7/appcompat/
processing android/support/v7/appcompat/BuildConfig.class...
ignored resource android/support/v7/graphics/
ignored resource android/support/v7/graphics/drawable/
processing android/support/v7/graphics/drawable/DrawableUtils.class...
processing android/support/v7/graphics/drawable/DrawableWrapper.class...
processing android/support/v7/graphics/drawable/DrawerArrowDrawable.class...
processing android/support/v7/graphics/drawable/DrawerArrowDrawable$ArrowDirection.class...
ignored resource android/support/v7/text/
processing android/support/v7/text/AllCapsTransformationMethod.class...
ignored resource android/support/v7/transition/
processing android/support/v7/transition/ActionBarTransition.class...
ignored resource android/support/v7/view/
processing android/support/v7/view/ActionBarPolicy.class...
processing android/support/v7/view/ActionMode.class...
processing android/support/v7/view/ActionMode$Callback.class...
processing android/support/v7/view/CollapsibleActionView.class...
processing android/support/v7/view/ContextThemeWrapper.class...
processing android/support/v7/view/StandaloneActionMode.class...
processing android/support/v7/view/SupportActionModeWrapper.class...
processing android/support/v7/view/SupportActionModeWrapper$CallbackWrapper.class...
processing android/support/v7/view/SupportMenuInflater.class...
processing android/support/v7/view/SupportMenuInflater$InflatedOnMenuItemClickListener.class...
processing android/support/v7/view/SupportMenuInflater$MenuState.class...
processing android/support/v7/view/ViewPropertyAnimatorCompatSet.class...
processing android/support/v7/view/ViewPropertyAnimatorCompatSet$1.class...
processing android/support/v7/view/WindowCallbackWrapper.class...
ignored resource android/support/v7/view/menu/
processing android/support/v7/view/menu/ActionMenuItem.class...
processing android/support/v7/view/menu/ActionMenuItemView.class...
processing android/support/v7/view/menu/ActionMenuItemView$ActionMenuItemForwardingListener.class...
processing android/support/v7/view/menu/ActionMenuItemView$PopupCallback.class...
processing android/support/v7/view/menu/BaseMenuPresenter.class...
processing android/support/v7/view/menu/BaseMenuWrapper.class...
processing android/support/v7/view/menu/BaseWrapper.class...
processing android/support/v7/view/menu/ExpandedMenuView.class...
processing android/support/v7/view/menu/ListMenuItemView.class...
processing android/support/v7/view/menu/ListMenuPresenter.class...
processing android/support/v7/view/menu/ListMenuPresenter$MenuAdapter.class...
processing android/support/v7/view/menu/MenuBuilder.class...
processing android/support/v7/view/menu/MenuBuilder$Callback.class...
processing android/support/v7/view/menu/MenuBuilder$ItemInvoker.class...
processing android/support/v7/view/menu/MenuDialogHelper.class...
processing android/support/v7/view/menu/MenuItemImpl.class...
processing android/support/v7/view/menu/MenuItemImpl$1.class...
processing android/support/v7/view/menu/MenuItemWrapperICS.class...
processing android/support/v7/view/menu/MenuItemWrapperICS$ActionProviderWrapper.class...
processing android/support/v7/view/menu/MenuItemWrapperICS$CollapsibleActionViewWrapper.class...
processing android/support/v7/view/menu/MenuItemWrapperICS$OnActionExpandListenerWrapper.class...
processing android/support/v7/view/menu/MenuItemWrapperICS$OnMenuItemClickListenerWrapper.class...
processing android/support/v7/view/menu/MenuItemWrapperJB.class...
processing android/support/v7/view/menu/MenuItemWrapperJB$ActionProviderWrapperJB.class...
processing android/support/v7/view/menu/MenuPopupHelper.class...
processing android/support/v7/view/menu/MenuPopupHelper$MenuAdapter.class...
processing android/support/v7/view/menu/MenuPresenter.class...
processing android/support/v7/view/menu/MenuPresenter$Callback.class...
processing android/support/v7/view/menu/MenuView.class...
processing android/support/v7/view/menu/MenuView$ItemView.class...
processing android/support/v7/view/menu/MenuWrapperFactory.class...
processing android/support/v7/view/menu/MenuWrapperICS.class...
processing android/support/v7/view/menu/SubMenuBuilder.class...
processing android/support/v7/view/menu/SubMenuWrapperICS.class...
ignored resource android/support/v7/widget/
processing android/support/v7/widget/AbsActionBarView.class...
processing android/support/v7/widget/AbsActionBarView$1.class...
processing android/support/v7/widget/AbsActionBarView$VisibilityAnimListener.class...
processing android/support/v7/widget/ActionBarBackgroundDrawable.class...
processing android/support/v7/widget/ActionBarBackgroundDrawableV21.class...
processing android/support/v7/widget/ActionBarContainer.class...
processing android/support/v7/widget/ActionBarContextView.class...
processing android/support/v7/widget/ActionBarContextView$1.class...
processing android/support/v7/widget/ActionBarOverlayLayout.class...
processing android/support/v7/widget/ActionBarOverlayLayout$1.class...
processing android/support/v7/widget/ActionBarOverlayLayout$2.class...
processing android/support/v7/widget/ActionBarOverlayLayout$3.class...
processing android/support/v7/widget/ActionBarOverlayLayout$ActionBarVisibilityCallback.class...
processing android/support/v7/widget/ActionBarOverlayLayout$LayoutParams.class...
processing android/support/v7/widget/ActionMenuPresenter.class...
processing android/support/v7/widget/ActionMenuPresenter$1.class...
processing android/support/v7/widget/ActionMenuPresenter$ActionButtonSubmenu.class...
processing android/support/v7/widget/ActionMenuPresenter$ActionMenuPopupCallback.class...
processing android/support/v7/widget/ActionMenuPresenter$OpenOverflowRunnable.class...
processing android/support/v7/widget/ActionMenuPresenter$OverflowMenuButton.class...
processing android/support/v7/widget/ActionMenuPresenter$OverflowMenuButton$1.class...
processing android/support/v7/widget/ActionMenuPresenter$OverflowPopup.class...
processing android/support/v7/widget/ActionMenuPresenter$PopupPresenterCallback.class...
processing android/support/v7/widget/ActionMenuPresenter$SavedState.class...
processing android/support/v7/widget/ActionMenuPresenter$SavedState$1.class...
processing android/support/v7/widget/ActionMenuView.class...
processing android/support/v7/widget/ActionMenuView$1.class...
processing android/support/v7/widget/ActionMenuView$ActionMenuChildView.class...
processing android/support/v7/widget/ActionMenuView$ActionMenuPresenterCallback.class...
processing android/support/v7/widget/ActionMenuView$LayoutParams.class..<message truncated>

Regards

**Comment by claywilkinson** [comment]
This looks like you have two copies of google-play-services aars or including the google_play_services-lib and the aars in your project.  Check Assets/Plugins/Android for these duplicates and remove one of them.

What version of Unity are you using?

**Comment by rajeev77** [comment]
@claywilkinson  No i don't have any duplicates files in the project, i have also deleted the plugin and reimport it for this case ,but didn't worked.

i am using 5.3.4f1.

**Comment by g012** [comment]
There's no duplicate, I also have this error and references to this issue can be found on Unity's forum as well.
Maybe said duplicated classes are found both in basement 9 and drive 8.4 aar.

**Comment by g012** [comment]
Got it to build and run by removing said duplicated classes from drive 8.4 aar and nearby 8.4 aar. Not sure if everything is working though, as I'm not really using much right now.

**Comment by rajeev77** [comment]
Here is my project view:
![screen shot 2016-05-25 at 12 53 43 pm](https://cloud.githubusercontent.com/assets/19554429/15531403/dd686e74-2277-11e6-96c9-9709c58b38fc.png)


These files looks similar ,should it have duplicate files?

**Comment by dogancaufuk** [comment]
When i changed Assets/GooglePlayGames/PluginVersion.cs
**public const string PlayServicesVersionConstraint = "8.4+";**
to
**public const string PlayServicesVersionConstraint = "9.0.0";**

except of play-services-drive is changed to v9.0.0 but i still got same error

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznm;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznn;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzno;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzno$zza;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznp;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznq;
6 errors; aborting
]

![plugins2](https://cloud.githubusercontent.com/assets/1609397/15534537/eca1371e-2271-11e6-91bb-b565a029b626.png)

**Comment by rajeev77** [comment]
i think this is the plugin bug.

**Comment by dogancaufuk** [comment]
Yes i think too and also i cannot use the old version because when i use "Window / Google Play Games / Setup /Android Setup" plugin trying to update to latest version

**Comment by rajeev77** [comment]
i finally build my project without any error like this.
Here is what i have done:

1) select all the file with  **8.4.0**
2) and deselect Andrioid option from **select platforms from plugin** 

and then build and run. 
It build without any errors ,but and game play services doesn't work at all(the functions like login,report progress etc).

and one another problem appears that, when i **export** project for **android studio** it gives me error like this:

CommandInvokationFailure: Failed to re-package resources. See the Console for details.
/Users/rajeevrajani/Library/Android/sdk/build-tools/23.0.3/aapt package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "/Users/rajeevrajani/Library/Android/sdk/platforms/android-23/android.jar" -F bin/resources.ap_ --extra-packages com.google.example.games.mainlibproj:com.texfgh.adspushnoti -S "/Users/rajeevrajani/Documents/Development/Unity Projects/ADMOB ADS/Temp/StagingArea/android-libraries/unity-android-resources/res"

stderr[
AndroidManifest.xml:19: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
  Type values
Including resources from package: /Users/rajeevrajani/Library/Android/sdk/platforms/android-23/android.jar
applyFileOverlay for drawable
trying overlaySet Key=app_banner.png
trying overlaySet Key=app_icon.png
applyFileOverlay for layout
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res/drawable/app_icon.png
Processing image: res/drawable-xhdpi/app_banner.png
    (processed image res/drawable/app_icon.png: 94% size of source)
    (processed image res/drawable-xhdpi/app_banner.png: 93% size of source)
    (new resource id app_banner from xhdpi-v4/drawable/app_banner.png #generated)
    (new resource id app_icon from drawable/app_icon.png #generated)
]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.PostProcessAndroidPlayer.Exec (System.String command, System.String args, System.String workingdir, System.String[] progress_strings, Single progress_value, System.String errorMsg)
UnityEditor.Android.PostProcessAndroidPlayer.CompileResources (System.String stagingArea, System.String packageName, UnityEditor.Android.AndroidLibraries androidLibraries)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcessInternal (System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.HostView:OnGUI()

**Comment by dogancaufuk** [comment]
Assets/PlayServicesResolver/Editor/Admobdependencies.cs
svcSupport.DependOn("com.google.android.gms", "play-services-ads", "9.0.0");

Assets/GooglePlayGames/PluginVersion.cs
public const string PlayServicesVersionConstraint = "9.0.0";

ProjectSettings/GoogleDependencyGooglePlayGames.xml
Change all versions to 9.0.0

If you have Admob Plugin also
ProjectSettings/GoogleDependencyAdMobUnity.xml
Change all versions to 9.0.0

After them "Window / Google Play Games / Setup /Android Setup" and accept all changes

**Compile success without any errors**

But its calling another project id not my id that i was saved maybe it can be my problem with google play account i couldn't find 608941808256 id anywhere its not mine..

Access Not Configured. Google Play Game Services API has not been used in project 608941808256 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/games/overview?project=608941808256 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by rajeev77** [comment]
@dogancaufuk  so basically you solved this and you have working project on your device??

**Comment by Otd2** [comment]
@rajeev77 I did what @dogancaufuk said in my project and yes, it worked for me. Finally, google play services are **working** like a charm. 

But that was a painful workaround, I suppose that should be fixed soon.

**Comment by dogancaufuk** [comment]
Yes its working now the other id problem is because of my SHA-1 problem i solved it too from https://console.developers.google.com with keytool its not relevant with plugin..

So just change all versions to 9.0.0 as described on previous message and have fun ;)
I hope next version is come with this fix..

**Comment by rajeev77** [comment]
@dogancaufuk  i cant find **ProjectSettings/GoogleDependencyAdMobUnity.xml
**

**Comment by dogancaufuk** [comment]
**If you have Admob Plugin also**
ProjectSettings/GoogleDependencyAdMobUnity.xml
Change all versions to 9.0.0
If you dont have Admob you dont need to change that file

**Comment by rajeev77** [comment]
@dogancaufuk  thanks i have complied successfully but my game play service is not logging?
you have mentioned SHA-1 problem how do you fix it? i think i have similar problem.

**Comment by Universalerror** [comment]
Possibly related to this? #1165

**Comment by ergin3d** [comment]
Thanks dogancaufuk, it worked for me too.

**Comment by claywilkinson** [comment]
The version for the plugin has been updated to 9+ in version 0.9.34 so this problem should not occur any longer.  Thanks everyone for the great diagnosis and discussion!

**Comment by AVOlight** [comment]
i'm now getting this with them on play-services-x-10.0.0
i have the latest firebase, facebook and fabric sdks

**Comment by sergioadevita** [comment]
It is happening again between 9.2.0 and 9.4.0, the plugin is trying to use 9.2.0, which is an older version.
