### ISSUE TITLE
Forcing Update!

### ISSUE THREAD

**Issue by dogancaufuk** [playgameservices/play-games-plugin-for-unity#1177]
On Unity Window / Google Play Games / Setup / Android Setup menu when i make setup then asking for updating Play Games if I say YES updating to 0.9.33 but if i say NO its even so updating some files to 0.9.33 so confirmation for update not working for all files..

**Comment by claywilkinson** [comment]
Can you be more specific on which files you are referring to?

**Comment by dogancaufuk** [comment]
Not important now after 0.9.34
