### ISSUE TITLE
play-games-plugin-for-unity

### ISSUE THREAD

**Issue by parth521** [playgameservices/play-games-plugin-for-unity#1178]
Hello,
i am not able to login in ios.in android working properly.
i am using unity 4.6 and play game services version  0.9.32.

getting debugs like below.
Application is pausing. which disconnect the rtmp client. leaving room.

so please tell me where i am wrong.

**Comment by claywilkinson** [comment]
Can you share the log of signing in?  This is not a lot of information to help.

**Comment by claywilkinson** [comment]
please open another issue when you have more information.  Thanks!
