### ISSUE TITLE
Build Unity-iPhone: Failed

### ISSUE THREAD

**Issue by hamar02** [playgameservices/play-games-plugin-for-unity#1183]
Totally new to Xcode.
I get these errors when im trying to build my project:

  "_OBJC_CLASS_$_GSDK_GTMSessionFetcher", referenced from:

  "_OBJC_CLASS_$_GSDK_GTMOAuth2Keychain", referenced from:

  "_OBJC_CLASS_$_GSDK_GTMOAuth2SignIn", referenced from:

  "_OBJC_CLASS_$_GSDK_OpenInChromeController", referenced from:

  "_OBJC_CLASS_$_GSDK_GTMOAuth2Authentication", referenced from:

  "_OBJC_CLASS_$_GSDK_GTMOAuth2ViewControllerTouch", referenced from:

  "_GSDK_NSClassFromString", referenced from:

  "_OBJC_CLASS_$_GSDK_GTMSessionFetcherService", referenced from:

clang: error: linker command failed with exit code 1 (use -v to see invocation)

I've googled them and there is a solution from 1 source, but he doesnt explain well enough for me to understand what/how to do: http://answers.unity3d.com/questions/1190937/ios-build-linking-errors.html

Anyone care to explain?

Cheers

**Comment by claywilkinson** [comment]
Are you using cocoapods?  can you share your Podfile.lock file?

**Comment by hamar02** [comment]
I solved it by copying the text from the podfile found in /Users/username/Downloads/play-games-plugin-for-unity-master/source/PluginDev/Assets/GooglePlayGames/Editor and pasting it into the project folders podfile.

Never heard about cocoapods before i followed the guide.
Thanks for responding.

**Comment by claywilkinson** [comment]
Glad you got it working.  Is it OK to close this issue?

**Comment by hamar02** [comment]
It's.
