### ISSUE TITLE
Social.ShowLeaderboardUI

### ISSUE THREAD

**Issue by rajeev77** [playgameservices/play-games-plugin-for-unity#1185]
I have successfully logged in to the play services, but when i call `Social.ShowLeaderboardUI` it give me error:

V/GamesNativeSDK: Play Games callback indicates connection.
I/GamesNativeSDK: Successfully connected to Google Play.
[Play Games Plugin DLL] 05/26/16 22:10:05 +05:30 DEBUG: Showing UI Internal callback: ERROR_UI_BUSY
E/GamesNativeSDK: Trying to show UI while waiting for a result from an existing UI. Please ensure that OnActivityResult is forwarded to the Games C++ SDK from your Java activity. See android_support.h for more details.

what is wrong with this?

Regards.

**Comment by claywilkinson** [comment]
There can only be one outstanding intent from the Games SDK meaning the leaderboard, achievement UI, etc. must be closed before another can be opened.

The Unity game engine is paused when another activity is started, so usually this error means ShowLeaderboardUI is being called  multiple times quickly (such as in Update)? 

Can you share more of the log?

**Comment by rajeev77** [comment]
@claywilkinson Thanks for your words, how can i fix it if it is calling like an update function?

**Comment by claywilkinson** [comment]
Depends on how you are doing your UI. If you are using the legacy GUI, it should be behind a GUIButton such as in the [SmokeTest sample](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/samples/SmokeTest/Source/Assets/SmokeTest/LeaderboardGUI.cs#L45):
```
if (GUILayout.Button("LB Show UI", GUILayout.Height(height),GUILayout.ExpandWidth(true)))
            {
                DoLeaderboardUI();
            }
```

If you are using the new UI layout - the show leaderboard UI call should be called from a method triggered on the onClick event for a Button.  The [CubicPilot sample](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/samples/CubicPilot/Source/Assets/CubicPilot/Gui/MainMenuEvents.cs#L170) is an example of this.

**Comment by rajeev77** [comment]
@claywilkinson i am calling with new UI system

`public void ShowLeaderboards()
	{
		clickSound.Play ();

		#if UNITY_ANDROID

		PlayGamesPlatform.Instance.ShowLeaderboardUI ();

		#else

		Social.ShowLeaderboardUI ();

		#endif

	}`

Here is my log show when this function is called:

05-27 12:00:40.175 16105-16604/? I/Unity:  [Play Games Plugin DLL] 05/27/16 12:00:40 +05:30 DEBUG: ShowLeaderboardUI with default ID
                                           
                                          (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-27 12:00:40.176 16105-16604/? I/Unity:  [Play Games Plugin DLL] 05/27/16 12:00:40 +05:30 DEBUG: ShowLeaderboardUI, lbId= callback is 
                                           
                                          (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-27 12:00:40.204 31938-4093/? W/GamesServiceBroker: Client connected with SDK 9080000, Services 9083440, and Games 37230040
05-27 12:00:40.222 31938-16880/? E/PopupManager: No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
05-27 12:00:40.237 31938-13826/? W/GamesServiceBroker: Client connected with SDK 8487000, Services 9083440, and Games 37230040
05-27 12:00:40.261 31938-32025/? V/BaseAuthAsyncOperation: All scopes had been granted in the past, skip access token fetching
05-27 12:00:40.268 22669-22669/? I/Auth: [AuthDelegateWrapper] Service intent: Intent { cmp=com.google.android.gms/.auth.account.authenticator.DefaultAuthDelegateService }.
05-27 12:00:40.269 22669-22669/? I/Auth: [AuthDelegateWrapper] Service intent: Intent { cmp=com.google.android.gms/.auth.account.authenticator.DefaultAuthDelegateService }.
                                         
                                         --------- beginning of system
05-27 12:00:40.276 877-3309/? W/AppOps: Bad call: specified package com.google.android.play.games under uid 10131 but it is really 10065
05-27 12:00:40.307 31938-32025/? V/BaseAuthAsyncOperation: access token request successful
05-27 12:00:40.309 31938-16880/? E/PopupManager: No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
05-27 12:00:40.319 31938-13826/? W/GamesServiceBroker: Client connected with SDK 8487000, Services 9083440, and Games 37230040
05-27 12:00:40.328 16105-16105/? V/GamesNativeSDK: Play Games callback indicates connection.
05-27 12:00:40.339 16105-16877/? I/GamesNativeSDK: Successfully connected to Google Play.
05-27 12:00:40.344 16105-16877/? E/GamesNativeSDK: Trying to show UI while waiting for a result from an existing UI. Please ensure that OnActivityResult is forwarded to the Games C++ SDK from your Java activity. See android_support.h for more details.
05-27 12:00:40.344 16105-16699/? I/Unity:  [Play Games Plugin DLL] 05/27/16 12:00:40 +05:30 DEBUG: Showing UI Internal callback: ERROR_UI_BUSY
                                           
                                          (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-27 12:00:40.356 16105-16604/? I/Unity:  [Play Games Plugin DLL] 05/27/16 12:00:40 +05:30 DEBUG: Invoking user callback on game thread
                                           
                                          (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-27 12:00:40.356 16105-16604/? I/Unity:  [Play Games Plugin DLL] 05/27/16 12:00:40 +05:30 DEBUG: Received UI callback: ERROR_UI_BUSY
                                           
                                          (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-27 12:00:41.812 495-597/? I/ThermalEngine: ACTION: LCD - Setting max LCD brightness to 208
05-27 12:00:45.345 16105-16877/? W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[15,tid=16877,Native,Thread*=0xda2e8000,peer=0x12c22100,"main_dispatch"]
05-27 12:00:45.346 16105-16877/? V/GamesNativeSDK: Detaching from JVM on thread main_dispatch
05-27 12:00:45.368 877-13334/? D/NetlinkSocketObserver: NeighborEvent{elapsedMs=653106532, 192.168.0.1, [C4E984A220EE], RTM_NEWNEIGH, NUD_REACHABLE}
05-27 12:00:53.661 877-13334/? D/NetlinkSocketObserver: NeighborEvent{elapsedMs=653114825, 192.168.0.1, [C4E984A220EE], RTM_NEWNEIGH, NUD_STALE}
05-27 12:00:57.961 29157-29157/? I/DownloadManagerWrapper: onReceive() : Charging = true
05-27 12:00:59.290 877-13334/? D/NetlinkSocketObserver: NeighborEvent{elapsedMs=653120454, 192.168.0.1, [C4E984A220EE], RTM_NEWNEIGH, NUD_PROBE}

**Comment by rajeev77** [comment]
i want to ask that when i Build and Run my project, it compile without any errors, but when i export my project to **Google Android Project** it is giving me error like this:

` AndroidManifest.xml:9: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').`

and it failes to compile.

i have searched on the internet and found that i need to include `version.xml` from the sdk location to **Plugins/Android/res/values**.
but i cant find version.xml file in the SDK location.

**Comment by claywilkinson** [comment]
You need more than just that version.xml file.  You need the client libraries for Play Game Services.  These are a series of aar files in Assets/Plugins/Android such as play-services-basement-9.0.0.aar

Make sure you have the latest SDK updates from the Android SDK.

You an update them by running Assets/Google Play Services/Resolve client jars.

**Comment by rajeev77** [comment]
@claywilkinson  i have latest SDK installed. and i have all the jar files you mentioned as **play-services-basement-9.0.0.aar**  and how can i run **Resolve Client Jars**.?  and i don't find any version.xml file in my SDK.

**Comment by claywilkinson** [comment]
Please open a new issue if you are still having problems.
