### ISSUE TITLE
I can't list the scores in the leaderboard

### ISSUE THREAD

**Issue by GuiSiilva** [playgameservices/play-games-plugin-for-unity#1187]
I can login, report score and show the leaderboards, but I can't access the scores.
![testgoogle](https://cloud.githubusercontent.com/assets/5834645/15597716/4d800a0a-23a9-11e6-8fd8-3c0b354f3908.png)

**Comment by claywilkinson** [comment]
The social leaderboard will be empty during the game IDs migration happening(which is removing the requirement for also having a  Google Plus account).  The public leaderboard should display all the public scores.

**Comment by GuiSiilva** [comment]
but I already played the game in 2 smartphones and no score was added on leaderboard

**Comment by Bjakuja** [comment]
I have the same problem, users on Android can see/report their scores but on IOS they can't report their score to the leaderboard at all. It is urgent matter, pls help if somebody knows what can be the problem here

**Comment by muafakul** [comment]
bro still un asjhgkdjhfjsjdfsdf

**Comment by jmottershead94** [comment]
@muafakul @Bjakuja And also for anyone else looking through these, I believe it is something to do with these issues here maybe: #686 #662

**Comment by jmottershead94** [comment]
Also here it is a known issue: https://developers.google.com/games/services/ios/knownIssues

**Comment by claywilkinson** [comment]
Social leaderboards are no longer supported on iOS.  See https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html for more information.
