### ISSUE TITLE
Linux Editor Support

### ISSUE THREAD

**Issue by Kierek** [playgameservices/play-games-plugin-for-unity#1188]
The plugin doesn't seem to be able to find necessary libraries on (still in beta) Unity Editor for Linux. I have everything installed in Android SDK Manager, but it's still not working.

> FileNotFoundException: Could not load file or assembly 'GooglePlayServices' or one of its dependencies. The system cannot find the file specified.
System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity, Boolean refonly) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/AppDomain.cs:746)
System.AppDomain.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/AppDomain.cs:733)
(wrapper remoting-invoke-with-check) System.AppDomain:Load (string,System.Security.Policy.Evidence)
System.Reflection.Assembly.Load (System.String assemblyString, System.Security.Policy.Evidence assemblySecurity) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/Assembly.cs:584)
System.Activator.CreateInstance (System.String assemblyName, System.String typeName, Boolean ignoreCase, BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Security.Policy.Evidence securityInfo) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:170)
System.Activator.CreateInstance (System.String assemblyName, System.String typeName, System.Object[] activationAttributes) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:158)
System.Activator.CreateInstance (System.String assemblyName, System.String typeName) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:150)
GooglePlayServices.PlayServicesResolver.get_Resolver () (at Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:96)
GooglePlayServices.PlayServicesResolver.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:115)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at /home/builduser/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:27)
UnityEditor.AssetDatabase:Refresh()
GooglePlayGames.Editor.GPGSUpgrader:.cctor() (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:107)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

and also

> Assets/_Scripts/CanvasManager.cs(5,7): error CS0246: The type or namespace name `GooglePlayGames' could not be found. Are you missing a using directive or an assembly reference?

The same project works perfectly fine in OSX and Windows Editor.

**Comment by claywilkinson** [comment]
This is an occasional race condition in Unity editor when loading the classes.  I believe it has been fixed in the latest version of the plugin 0.9.34.  Can you try that one on Linux?
