### ISSUE TITLE
Sign in as Lerpz

### ISSUE THREAD

**Issue by sakkel** [playgameservices/play-games-plugin-for-unity#119]
Hi everyone.
Im trying to Sign in, but is signing as Lerpz.
I think its some sort of default player if sign in was failed.
But Unity dont shows any errors.

How can i fix it?

Code:

```
Social.localUser.Authenticate((bool success) => {
            if(!success) 
            {
                signed = false;
                this.GetComponent<TextMesh>().text = "Error";
                this.GetComponent<TextMesh>().color = Color.red;
            }
            else this.GetComponent<TextMesh>().text = Social.localUser.userName;
        });
```

**Comment by Nerosam** [comment]
I too have this issue. I have followed the instructions and create a google play console app for the clientID and added to unity project. It is also linked to my google play app which has just been published as an alpha build but I still struggle to get an actual user returning other than the test user "Lerpz".

Any ideas?
