### ISSUE TITLE
CommandInvokationFailure: Unable to convert classes into dex format

### ISSUE THREAD

**Issue by DigitalGearStudios** [playgameservices/play-games-plugin-for-unity#1190]
Hi!

I'm having a issue when building my game. I'm using latest version of play-games plugin and also admob. 

Full error description:
CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:/Program Files/Java/jdk1.8.0_91\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/Sych/AppData/Local/Android/android-sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznn;
    at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
    at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
    at com.android.dx.command.dexer.Main.processClass(Main.java:685)
    at com.android.dx.command.dexer.Main.processFileBytes(Main.java:634)
    at com.android.dx.command.dexer.Main.access$600(Main.java:78)
    at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:572)
    at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
    at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
    at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
    at com.android.dx.command.dexer.Main.processOne(Main.java:596)
    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:498)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:264)
    at com.android.dx.command.dexer.Main.run(Main.java:230)
    at com.android.dx.command.dexer.Main.main(Main.java:199)
    at com.android.dx.command.Main.main(Main.java:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at SDKMain.main(SDKMain.java:129)

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqj;
    at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
    at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
    at com.android.dx.command.dexer.Main.processClass(Main.java:685)
    at com.android.dx.command.dexer.Main.processFileBytes(Main.java:634)
    at com.android.dx.command.dexer.Main.access$600(Main.java:78)
    at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:572)
    at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
    at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
    at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
    at com.android.dx.command.dexer.Main.processOne(Main.java:596)
    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:498)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:264)
    at com.android.dx.command.dexer.Main.run(Main.java:230)
    at com.android.dx.command.dexer.Main.main(Main.java:199)
    at com.android.dx.command.Main.main(Main.java:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at SDKMain.main(SDKMain.java:129)
2 errors; aborting

**Comment by birdkingz** [comment]
Same here, I've updated to the latest v0.9.34 but still getting this error
(I have latest Admob plugin in the project too)

PS: I dont think [issue#1176](https://github.com/playgameservices/play-games-plugin-for-unity/issues/1176) is solved

**Comment by birdkingz** [comment]
I managed to solve the issue by setting up Google Play Game Services in 
Window > Google Play Games > Setup > Android setup
After key in required information and click on Setup, it will update play-services-drive from v8.4.0 to v9.0.1

Hope it helps.

**Comment by DigitalGearStudios** [comment]
Just deleted and imported both plugins again and it worked... Let's see how much time it'll work until it finds another error...

**Comment by TreSSorGS** [comment]
I have the same problem : i use the lastest admob and google play versions .
play-services-drive-8.4.0
play-services-plus-8.4.0
dont upgrade to 9.0.1

Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:/Program Files/Java/jdk1.8.0_92\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Program Files (x86)/Android/android-sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznm;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznn;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzno;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzno$zza;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznp;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zznq;
6 errors; aborting
]
stdout[
processing archive C:\Developer Unity\Deep Space Invaders\Deep Space Invaders 3.2\Temp\StagingArea\android-libraries\AmazonAppStore\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/unity/
ignored resource com/unity/purchasing/
ignored resource com/unity/purchasing/amazon/
processing com/unity/purchasing/amazon/AmazonPurchasing.class...
processing com/unity/purchasing/amazon/AmazonPurchasing$1.class...
processing com/unity/purchasing/amazon/AmazonPurchasing$2.class...
processing com/unity/purchasing/amazon/AmazonPurchasing$3.class...
processing com/unity/purchasing/amazon/AmazonPurchasing$4.class...
processing com/unity/purchasing/amazon/AmazonPurchasing$LocaleNotFoundException.class...
processing com/unity/purchasing/amazon/AmazonPurchasingService.class...
processing com/unity/purchasing/amazon/BuildConfig.class...
processing com/unity/purchasing/amazon/CurrencyMapper.class...
processing com/unity/purchasing/amazon/IPurchasingService.class...
processing archive C:\Developer Unity\Deep Space Invaders\Deep Space Invaders 3.2\Temp\StagingArea\android-libraries\AmazonAppStore\libs\.\in-app-purchasing-2.0.61.jar...
ignored resource META-INF/MANIFEST.MF
processing com/amazon/device/iap/package-info.class...
processing com/amazon/device/iap/PurchasingListener.class...
processing com/amazon/device/iap/PurchasingService.class...
processing com/amazon/device/iap/ResponseReceiver.class...
processing com/amazon/device/iap/internal/a.class...
processing com/amazon/device/iap/internal/a/a.class...
processing com/amazon/device/iap/internal/a/b.class...
processing com/amazon/device/iap/internal/a/c.class...
processing com/amazon/device/iap/internal/a/c$1.class...
processing com/amazon/device/iap/internal/a/d.class...
processing com/amazon/device/iap/internal/b.class...
processing com/amazon/device/iap/internal/b/a.class...
processing com/amazon/device/iap/internal/b/a/a.class...
processing com/amazon/device/iap/internal/b/a/b.class...
processing com/amazon/device/iap/internal/b/a/c.class...
processing com/amazon/device/iap/internal/b/a/d.class...
processing com/amazon/device/iap/internal/b/b.class...
processing com/amazon/device/iap/internal/b/b/a.class...
processing com/amazon/device/iap/internal/b/b/a$1.class...
processing com/amazon/device/iap/internal/b/b/b.class...
processing com/amazon/device/iap/internal/b/b/c.class...
processing com/amazon/device/iap/internal/b/b/d.class...
processing com/amazon/device/iap/internal/b/c.class...
processing com/amazon/device/iap/internal/b/c/a.class...
processing com/amazon/device/iap/internal/b/c/b.class...
processing com/amazon/device/iap/internal/b/c/c.class...
processing com/amazon/device/iap/internal/b/c/d.class...
processing com/amazon/device/iap/internal/b/d.class...
processing com/amazon/device/iap/internal/b/d/a.class...
processing com/amazon/device/iap/internal/b/d/b.class...
processing com/amazon/device/iap/internal/b/d/c.class...
processing com/amazon/device/iap/internal/b/d/d.class...
processing com/amazon/device/iap/internal/b/e.class...
processing com/amazon/device/iap/internal/b/e/a.class...
processing com/amazon/device/iap/internal/b/e/b.class...
processing com/amazon/device/iap/internal/b/e/c.class...
processing com/amazon/device/iap/internal/b/e/d.class...
processing com/amazon/device/iap/internal/b/e$1.class...
processing com/amazon/device/iap/internal/b/f.class...
processing com/amazon/device/iap/internal/b/f/a.class...
processing com/amazon/device/iap/internal/b/f/b.class...
processing com/amazon/device/iap/internal/b/f/c.class...
processing com/amazon/device/iap/internal/b/g.class...
processing com/amazon/device/iap/internal/b/g/a.class...
processing com/amazon/device/iap/internal/b/g/b.class...
processing com/amazon/device/iap/internal/b/h.class...
processing com/amazon/device/iap/internal/b/h/a.class...
processing com/amazon/device/iap/internal/b/i.class...
processing com/amazon/device/iap/internal/c.class...
processing com/amazon/device/iap/internal/c/a.class...
processing com/amazon/device/iap/internal/c/a$1.class...
processing com/amazon/device/iap/internal/c/b.class...
processing com/amazon/device/iap/internal/c/c.class...
processing com/amazon/device/iap/internal/c/d.class...
processing com/amazon/device/iap/internal/c/e.class...
processing com/amazon/device/iap/internal/d.class...
processing com/amazon/device/iap/internal/e.class...
processing com/amazon/device/iap/internal/model/ProductBuilder.class...
processing com/amazon/device/iap/internal/model/ProductDataResponseBuilder.class...
processing com/amazon/device/iap/internal/model/PurchaseResponseBuilder.class...
processing com/amazon/device/iap/internal/model/PurchaseUpdatesResponseBuilder.class...
processing com/amazon/device/iap/internal/model/ReceiptBuilder.class...
processing com/amazon/device/iap/internal/model/UserDataBuilder.class...
processing com/amazon/device/iap/internal/model/UserDataResponseBuilder.class...
processing com/amazon/device/iap/internal/model/a.class...
processing com/amazon/device/iap/internal/util/MetricsHelper.class...
processing com/amazon/device/iap/internal/util/a.class...
processing com/amazon/device/iap/internal/util/a$1.class...
processing com/amazon/device/iap/internal/util/b.class...
processing com/amazon/device/iap/internal/util/c.class...
processing com/amazon/device/iap/internal/util/d.class...
processing com/amazon/device/iap/internal/util/e.class...
processing com/amazon/device/iap/model/package-info.class...
processing com/amazon/device/iap/model/FulfillmentResult.class...
processing com/amazon/device/iap/model/Product.class...
processing com/amazon/device/iap/model/Product$1.class...
processing com/amazon/device/iap/model/ProductDataResponse.class...
processing com/amazon/device/iap/model/ProductDataResponse$RequestStatus.class...
processing com/amazon/device/iap/model/ProductType.class...
processing com/amazon/device/iap/model/PurchaseResponse.class...
processing com/amazon/device/iap/model/PurchaseResponse$RequestStatus.class...
processing com/amazon/device/iap/model/PurchaseUpdatesResponse.class...
processing com/amazon/device/iap/model/PurchaseUpdatesResponse$RequestStatus.class...
processing com/amazon/device/iap/model/Receipt.class...
processing com/amazon/device/iap/model/RequestId.class...
processing com/amazon/device/iap/model/RequestId$1.class...
processing com/amazon/device/iap/model/UserData.class...
processing com/amazon/device/iap/model/UserData$1.class...
processing com/amazon/device/iap/model/UserDataResponse.class...
processing com/amazon/device/iap/model/UserDataResponse$RequestStatus.class...
processing archive C:\Developer Unity\Deep Space Invaders\Deep Space Invaders 3.2\Temp\StagingArea\android-libraries\GoogleAIDL\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/android/
ignored resource com/android/vending/
ignored resource com/android/vending/billing/
processing com/android/vending/billing/BuildConfig.class...
processing com/android/vending/billing/IInAppBillingService.class...
processing com/android/vending/billing/IInAppBillingService$Stub.class...
processing com/android/vending/billing/IInAppBillingService$Stub$Proxy.class...
ignored resource C:\Developer Unity\Deep Space Invaders\Deep Space Invaders 3.2\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\libs\.\PLUGIN_JAR_GOES_HERE
processing archive C:\Developer Unity\Deep Space Invaders\Deep Space Invaders 3.2\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\libs\.\unity-plugin-library.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/unity/
processing com/google/unity/BuildConfig.class...
ignored resource com/google/unity/ads/
processing com/google/unity/ads/Banner.class...
processing com/google/unity/ads/Banner$1.class...
processing com/google/unity/ads/Banner$1$1.class...
processing com/google/unity/ads/Banner$2.class...
processing com/google/unity/ads/Banner$3.class...
processing com/google/unity/ads/Banner$4.class...
processing com/google/unity/ads/Banner$5.class...
processing com/google/unity/ads/CustomNativeAd.class...
processing com/google/unity/ads/CustomNativeAd$1.class...
processing com/google/unity/ads/CustomNativeAd$2.class...
processing com/google/unity/ads/Interstitial.class...
processing com/google/unity/ads/Interstitial$1.class...
processing com/google/unity/ads/Interstitial$1$1.class...
processing com/google/unity/ads/Interstitial$2.class...
processing com/google/unity/ads/Interstitial$3.class...
processing com/google/unity/ads/Interstitial$4.class...
processing com/google/unity/ads/Interstitial$5.class...
processing com/google/unity/ads/NativeAdLoader.class...
processing com/google/unity/ads/NativeAdLoader$1.class...
processing com/google/unity/ads/NativeAdLoader$2.class...
processing com/google/unity/ads/NativeAdLoader$3.class...
processing com/google/unity/ads/NativeAdLoader$3$1.class...
processing com/google/unity/ads/NativeAdLoader$3$2.class...
processing com/google/unity/ads/NativeAdLoader$3$3.class...
processing com/google/unity/ads/NativeAdLoader$4.class...
processing com/google/unity/ads/PluginUtils.class...
processing com/google/unity/ads/RewardBasedVideo.class...
processing com/google/unity/ads/RewardBasedVideo$1.class...
processing com/google/unity/ads/RewardBasedVideo$1$1.class...
processing com/google/unity/ads/RewardBasedVideo$2.class...
processing com/google/unity/ads/RewardBasedVideo$3.class...
processing com/google/unity/ads/UnityBannerAdListener.class...
processing com/google/unity/ads/UnityCustomNativeAdListener.class...
processing com/google/unity/ads/UnityInterstitialAdListener.class...
processing com/google/unity/ads/UnityRewardBasedVideoAdListener.class...
processing archive C:\Developer Unity\Deep Space Invaders\Deep Space Invaders 3.2\Temp\StagingArea\android-libraries\GooglePlay\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/unity/
ignored resource com/unity/purchasing/
ignored resource com/unity/purchasing/googleplay/
processing com/unity/purchasing/googleplay/ActivityLauncher.class...
processing com/unity/purchasing/googleplay/BillingServiceManager.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$2.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$2.class...
processing com/unity/purchasing/googleplay/BillingServiceProcessor.class...
processing com/unity/purchasing/googleplay/BuildConfig.class...
processing com/unity/purchasing/googleplay/Consts.class...
processing com/unity/purchasing/googleplay/Consts$PurchaseState.class...
processing com/unity/purchasing/googleplay/Consts$ResponseCode.class...
processing com/unity/purchasing/googleplay/GooglePlayBillingUnAvailableException.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$1.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$2.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$3.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$4.class...
processing com/unity/purchasing/googleplay/IActivityLauncher.class...
processing com/unity/purchasing/googleplay/IBillingServiceManager.class...
processing com/unity/purchasing/googleplay/IabException.class...
processing com/unity/purchasing/googleplay/IabHelper.class...
processing com/unity/purchasing/googleplay/IabHelper$1.class...
processing com/unity/purchasing/googleplay/IabHelper$2.class...
processing com/unity/purchasing/googleplay/IabHelper$3.class...
processing com/unity/purchasing/googleplay/IabHelper$4.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeMultiFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabPurchaseFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabSetupFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$QueryInventoryFinishedListener.class...
processing com/unity/purchasing/googleplay/IabResult.class...
processing com/unity/purchasing/googleplay/Inventory.class...
processing com/unity/purchasing/googleplay/Purchase.class...
processing com/unity/purchasing/googleplay/PurchaseActivity.class...
processing com/unity/purchasing/googleplay/PurchaseFailedEvent.class...
processing com/unity/purchasing/googleplay/SkuDetails.class...
processing archive C:\Developer Unity\Deep Space Invaders\Deep Space Invaders 3.2\Temp\StagingArea\android-libraries\MainLibProj\libs\.\play-games-plugin-support.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/games/
ignored resource com/google/games/bridge/
processing com/google/games/bridge/BuildConfig.class...
processing com/google/games/bridge/NativeBridgeActivity.class...
processing com/google/games/bridge/TokenFragment.class...
processing com/google/games/bridge/TokenFragment$1.class...
processing com/google/games/bridge/TokenFragment$TokenRequest.class...
processing com/google/games/bridge/TokenPendingResult.class...
processing com/google/games/bridge/TokenResult.class...
processing archive C:\Developer Unity\Deep Space Invaders\Deep Space Invaders 3.2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\libs\.\classes.jar...
ignored resource .readme
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource android/
ignored resource android/support/
ignored resource android/support/v7/
ignored resource android/support/v7/app/
processing android/support/v7/app/ActionBar.class...
processing android/support/v7/app/ActionBar$DisplayOptions.class...
processing android/support/v7/app/ActionBar$LayoutParams.class...
processing android/support/v7/app/ActionBar$NavigationMode.class...
processing android/support/v7/app/ActionBar$OnMenuVisibilityListener.class...
processing android/support/v7/app/ActionBar$OnNavigationListener.class...
processing android/support/v7/app/ActionBar$Tab.class...
processing android/support/v7/app/ActionBar$TabListener.class...
processing android/support/v7/app/ActionBarActivity.class...
processing android/support/v7/app/ActionBarDrawerToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$1.class...
processing android/support/v7/app/ActionBarDrawerToggle$Delegate.class...
processing android/support/v7/app/ActionBarDrawerToggle$DelegateProvider.class...
processing android/support/v7/app/ActionBarDrawerToggle$DrawerArrowDrawableToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$DrawerToggle.class...
processing android/support/v7/app/ActionBarDrawerToggle$DummyDelegate.class..<message truncated>

**Comment by claywilkinson** [comment]
It is my understanding that admob requires play-services 9+.  The latest version of the Game Services plugin (0.9.34) has been updated to use 9+ also.

**Comment by hirenkacha** [comment]
I tried removing android-support-v13 file and it worked.

**Comment by TreSSorGS** [comment]
Finaly i resolve this deleting all google files and Project version in ( ProjectSettings ) folder and remove all plugins in my game , restart Unity and pull all plugins again .

**Comment by JohnyGQD** [comment]
It seems that you only have to delete GoogleDependencyGoogle.GPGS.xml from ProjectSettings folder as it conflicts with GoogleDependencyGooglePlayGames.xml and forces 8.4 files in. Then setup again, and you should be good to go.

**Comment by TreSSorGS** [comment]
Thx you very much JohnyGQD .

**Comment by Zamaroht** [comment]
Alright, following JohnyGQD suggestion, it upgraded many more of the files from 8.4 to 9.0.2, but I still had a few 8.4 files (more specifically, analytics and ads). I managed to upgrade them by replace them with the ones found in "...\android-sdk\extras\google\m2repository\com\google\android\gms\play-services-[ads/analytics]\9.0.2", after that it successfully compiled
