### ISSUE TITLE
Large lag spike PlayGamesHelperObject.Update, shortly after PlayGamesPlatform.Activate()

### ISSUE THREAD

**Issue by prodigga** [playgameservices/play-games-plugin-for-unity#1191]
Shortly after calling PlayGamesPlatform.Activate(), I see a very large lag spike. 500ms - 1500ms. Half a second is really noticeable. I am not sure what it is. Profiler does not reveal any more information.

**Comment by vaibhavgpt-google** [comment]
Please upgrade to the latest version of Unity Plugin. If there's still any issue related, feel free to re open it.
