### ISSUE TITLE
Can't sign into google play services with a different account

### ISSUE THREAD

**Issue by Jackmac2904** [playgameservices/play-games-plugin-for-unity#1192]
I have set up the google play services and it's for the most part working perfectly but one issue I am having is I can only sign in with the first account I logged in with and I can't sign in with my new account

**Comment by claywilkinson** [comment]
Did you explicitly sign out of your game before signing in with the new account?  Can you share the log of it not working?

**Comment by Jackmac2904** [comment]
Yeah, I definitely signed out as I used the code on the README to change the text of a button if the bool "success" is true and this is the case plus when I sign out I am unable to use the achievements/leaderboards, I'm not sure of what the log is but as I just said I am sure that the initial account is signed out, I also built the game on a different device without my account on and I still couldn't sign in on a different account yet it could log into my account when I added it to the device

**Comment by Jackmac2904** [comment]
Didn't realize I had to add users that could sign in in the unpublished game
