### ISSUE TITLE
Play Games Permissions (seamless sign-in)

### ISSUE THREAD

**Issue by Claytonious** [playgameservices/play-games-plugin-for-unity#1193]
Google says: http://android-developers.blogspot.com/2016/01/play-games-permissions-are-changing-in.html

This plugin seems to use things like `GoogleAuthUtil`, which the article linked above admonishes against. Is complying with this documentation on the roadmap already? How do we get there from here?

Thanks!

**Comment by claywilkinson** [comment]
The getToken() calls that use GoogleAuthUtil are deprecated in this plugin, but will be removed soon.  It's a chance for developers to switch over to getting the server auth code and then using that to exchange for the token on the server.
