### ISSUE TITLE
OnPostprocessAllAssets called before Resolver is registered 

### ISSUE THREAD

**Issue by JamesMcMahon** [playgameservices/play-games-plugin-for-unity#1194]
I'm hitting an issue in my project where the method `OnPostprocessAllAssets` in `PlayServicesResolver` is throwing a NullReferenceException line 104 (first line in snippet):

```csharp
if (!Resolver.ShouldAutoResolve(importedAssets, deletedAssets,
        movedAssets, movedFromAssetPaths))
{
    return;
}
```

I actually can't find this file in the repo but I assume this project is responsible for it. (If not let me know and I'll redirect this issue to right spot).

Looking at the code and my Unity logs, it looks like `RegisterResolver` is getting called after `OnPostprocessAllAssets`.

>NullReferenceException: Object reference not set to an instance of an object
Resolver version is now: 10101
Resolver version is now: 10102
Registering resolver version 1.2.0
Resolver version is now: 10102

Thoughts on how to fix this?

**Comment by claywilkinson** [comment]
There is a separate repository for the resolver - https://github.com/googlesamples/unity-jar-resolver

Can you try the simplistic fix of changing the if to be
 ```
if (Resolver == null || !Resolver.ShouldAutoResolve(importedAssets, deletedAssets,
        movedAssets, movedFromAssetPaths))
```
?

**Comment by JamesMcMahon** [comment]
Yeah a null check will avoid the exception but the problem is that then the rest of the code,

```csharp
Resolver.DoResolution(svcSupport,
    "Assets/Plugins/Android",
    HandleOverwriteConfirmation);

AssetDatabase.Refresh();
Debug.Log("Android Jar Dependencies: Resolution Complete");
```

Never gets executed.

I can open an issue in the other repo but I am hesitate because this issue may be caused by the way the Google Play plugin is calling the resolver. I haven't dived deep enough into the issue to debug it to tell. What are your thoughts?

**Comment by pateras** [comment]
I'm hitting this issue, as well, and would like to see it resolved.

**Comment by djcvijic** [comment]
Same here, please either fix it or provide a workaround as soon as possible. I will post a workaround here if I manage to make one.

**Comment by claywilkinson** [comment]
Unfortunately, I've not been able to find a reliable way to know when all the assets are loaded, or load the resolver code first, so the best workaround I can think of is to not use the background resolution, and just resolve the jars when Setup is run.

As always, we're open to other solutions :)

**Comment by claywilkinson** [comment]
The resolver plugin has been re-designed and updated in version 0.9.35.  It works much better now.
