### ISSUE TITLE
Choose Account UI Open  Problem  

### ISSUE THREAD

**Issue by frogpjn** [playgameservices/play-games-plugin-for-unity#1195]
When GetAccessToken Function Call, Choose Account UI Always opens 
But I want to Don,t Open Select Account UI and Select login Account .
What should I do ??

It was implemented as follows

`Social.localUser.Authenticate( GoogleAuthenticateResult );`

`void GoogleAuthenticateResult( bool result )`
`{`
`if( result == true )`
`{`
`StartCoroutine(GetIdToken());`
`}`
`}`

`IEnumerator GetIdToken()`
`{`
`while (String.IsNullOrEmpty( GooglePlayGames.PlayGamesPlatform.Instance.GetAccessToken()))`
`yield return null;`

`Debug.Log("Local user's idToken is " + (GooglePlayGames.PlayGamesPlatform.Instance.GetAccessToken()));`
`}`

My development env:
Unity: 5.3.3f1
PlayGames Plugin: 0.9.34
Platform: Android

**Comment by mvasiliy7** [comment]
I have the same problem with GetIdToken. Anyone help?

**Comment by mvasiliy7** [comment]
It seems that every time you initialize and activate GPG. This is true?

**Comment by claywilkinson** [comment]
You really should not be using getIdToken(), but rather use GetServerAuthCode() and then send that to your back end server to exchange for a token.   Is there a reason you must use GetIdToken?

**Comment by mvasiliy7** [comment]
@claywilkinson Azure App Service Auth now requires authorization_code and id_token together. But authcode loses relevance after i exchange authcode to id_token. I also have problem always choose account ui. Sorry for my bad english, i use Google Translate.

**Comment by mvasiliy7** [comment]
[This implementation](https://github.com/playgameservices/play-games-plugin-for-unity/issues/10#issuecomment-72830457) GetIdToken function solves this problem.

**Comment by claywilkinson** [comment]
@mvasiliy7  - The one you reference will no longer work in all cases since game player profiles are no longer associated with Google Plus accounts.

**Comment by mvasiliy7** [comment]
@claywilkinson this is bad, whether it is possible to implement any implementation of a function GetIdToken that it does not permanently opened choose account ui?

**Comment by mvasiliy7** [comment]
@claywilkinson I solved the problem with Azure auth as follows:
1. I get server auth code
2. Echange auth code to id token with my server
3. I get NEW auth code and send him with id_token to Azure. 

In this case, the authorization is successful. Thank you for that protected me from using native getIdToken ;)

**Comment by claywilkinson** [comment]
The id token and auth code are now implemented correctly on the client in plugin version 0.9.37.
