### ISSUE TITLE
Invalid classname Issue

### ISSUE THREAD

**Issue by vutrungduc7593** [playgameservices/play-games-plugin-for-unity#1197]
I can not setup android configuration.

Error:
Invalid classname: An exception was thrown by the type initializer for GooglePlayGames.Editor.GPGSDependencies

My env:
Unity: 5.3.5f1
PlayGames Plugin: 0.9.34
Platform: Android

**Comment by frogpjn** [comment]
try the following:

1. Unity Menu -> Window -> Google Play Games -> Downloads -> Google Play Games SDK(Andorid)
2. Unity Menu -> Window -> Google Play Games -> Setup -> Andorid Setup -> Setup

**Comment by vutrungduc7593** [comment]
![123](https://cloud.githubusercontent.com/assets/15082529/15704649/d8df730e-2815-11e6-8996-71f3e46d5ed0.png)

It's still not working.
I installed 'Google Play Services' on SDK Manager.

**Comment by junkiesdevstudio** [comment]
try to update : 
- Android Support Repository
- Google Play Service

**Comment by vutrungduc7593** [comment]
Thanks u @junkiesdevstudio , it's work

**Comment by AdnanNazir** [comment]
worked for me !
Thanks @junkiesdevstudio

**Comment by zapposh** [comment]
Did not work for me. The error still persists Anyone else tried this?

**Comment by MiketoString** [comment]
Make sure there is only one copy of the "play-services-xxx" jar or aar files in your project.  I think the .unitypackage ships with play-services-base-9.4.0, and play-services-games-9.4.0, etc... under Assets/Android/ folder.

If you have an older copy of play-services jars somewhere in your project then you will get this error.  Also, whatever version you do have in your project has to be above v9.

Lastly, any change you make to the jar files (adding or deleting one) requires restarting Unity.

**Comment by zapposh** [comment]
Many thanks Mike for all your support. It now works! Cheers.

**Comment by dzatara** [comment]
> Make sure there is only one copy of the "play-services-xxx" jar or aar files in your project. I think the .unitypackage ships with play-services-base-9.4.0, and play-services-games-9.4.0, etc... under Assets/Android/ folder.

Where would i find the files referred to above? Don't have an "Android" folder in my unity Assets. Tried all the solutions in this thread and still have this error
