### ISSUE TITLE
PlayGamesPlatform.IsAuthenticated() Incorrect Immediately After Calling SignOut()

### ISSUE THREAD

**Issue by kromenak** [playgameservices/play-games-plugin-for-unity#12]
I found that if you call IsAuthenticated() right after calling SignOut(), IsAuthenticated will still return true.  It seems that calling IsAuthenticated maybe one or more frames after calling SignOut will return the correct result.

``` C#
public void SignOut()
{
    PlayGamesPlatform.Instance.SignOut();
    Debug.Log(PlayGamesPlatform.Instance.IsAuthenticated()); // returns true!
}
```

This is a convoluted example, but I have an event that fires in response to signing out and code listening for that event might check for authentication - it seems that the function returns an incorrect value.

I can understand if SignOut is an asynchronous function that might fail for some reason, but the interface for it suggests that you are immediately signed out.

**Comment by WILEz75** [comment]
MMMhhh... no, PlayGamesPlatform.Instance.SignOut() not work fine.

[http://artistic-minds.it/sharingFiles/Screenshot_21.png](url)

Control is also done after many seconds (under a Update function), it is not a matter of waiting for the log out. Username is always the default user "Lerpz".
