### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by subzero911** [playgameservices/play-games-plugin-for-unity#1200]
I imported last version 0.9.33. Pressed Setup. Pasted code from Google Console from "achievements" panel -- it throws the exception.
![error104](https://cloud.githubusercontent.com/assets/12999702/15745741/1c1032aa-28dc-11e6-9952-928e5b512b42.jpg)
Also i can't build my application because of wrong Android manifest in Plugins folder.
![qip shot - screen 103](https://cloud.githubusercontent.com/assets/12999702/15745732/13353f18-28dc-11e6-8ca3-aad32325b52e.jpg)
## Unity 5.3.4.

На всякий случай по-русски: импортнул последнюю версию 0.9.33. Нажал Setup, вставил код из консоли из панели с ачивками - выдаёт ошибку. Сбилдить на даёт из-за кривого андроид-манифеста.
Unity 5.3.4

**Comment by VamppiV** [comment]
"Enter the Constants class name. This is the name of the fully qualified class that will be updated (or created) which contains the IDs of the game resources. The format of the name is .. For example, AwesomeGame.GPGSIds"

**Comment by subzero911** [comment]
@VamppiV Still doesn't work... same errors, can't build.
I watch tutorial on youtube - but they suggest just to enter Application ID (seems like it's an older version of GPGS - because 0.9.33 has not App ID input field)

**Comment by ArmandCloud** [comment]
When it was happened to me, I delete plug in > update android sdk > do the developer console stuff > re install plug-in > sign my application . And its solved this problem. I dont know what happens specific.

**Comment by danielsb** [comment]
Check this:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1215
