### ISSUE TITLE
RTMP OnLeftRoom Not Called When Player Minimizes Application

### ISSUE THREAD

**Issue by glindstr** [playgameservices/play-games-plugin-for-unity#1201]
I'm using API 0.9.34. I have a real time multiplayer game with unity and this plugin. During a real time game when a player hits the home button to minimize the app, the OnLeftRoom() doesn't get called for him. The other player does call OnParticipantLeft which is great. But is it the intended operation to not call OnLeftRoom? 

The player does leave the room when the app is minimized. It would make sense to me that this callback should be called once the user returns to the app. Or is there some other method to work around this?

**Comment by ArmandCloud** [comment]
OnLeftRoom called when you return to application. ver. 9.34

06-25 03:19:23.039 32303-32303/com.guya.dragracingproclutch V/GamesNativeSDK: Received Activity Stop Event.
06-25 03:19:23.039 32303-20986/com.guya.dragracingproclutch V/GamesNativeSDK: Attached to JVM on thread main_dispatch
06-25 03:19:23.039 32303-20986/com.guya.dragracingproclutch V/GamesNativeSDK: Running disconnect operation.
06-25 03:19:28.064 32303-20986/com.guya.dragracingproclutch D/dalvikvm: threadid=16: thread exiting, not yet detached (count=0)
06-25 03:19:28.064 32303-20986/com.guya.dragracingproclutch V/GamesNativeSDK: Detaching from JVM on thread main_dispatch
06-25 03:20:08.974 32303-32303/com.guya.dragracingproclutch I/Ads: Ad is not visible. Not refreshing ad.
06-25 03:20:08.974 32303-32303/com.guya.dragracingproclutch I/Ads: Scheduling ad refresh 60000 milliseconds from now.
06-25 03:20:08.984 32303-32303/com.guya.dragracingproclutch I/Ads: Ad is not visible. Not refreshing ad.
06-25 03:20:08.984 32303-32303/com.guya.dragracingproclutch I/Ads: Scheduling ad refresh 60000 milliseconds from now.
06-25 03:21:08.973 32303-32303/com.guya.dragracingproclutch I/Ads: Ad is not visible. Not refreshing ad.
06-25 03:21:08.973 32303-32303/com.guya.dragracingproclutch I/Ads: Scheduling ad refresh 60000 milliseconds from now.
06-25 03:21:08.993 32303-32303/com.guya.dragracingproclutch I/Ads: Ad is not visible. Not refreshing ad.
06-25 03:21:08.993 32303-32303/com.guya.dragracingproclutch I/Ads: Scheduling ad refresh 60000 milliseconds from now.
06-25 03:22:08.981 32303-32303/com.guya.dragracingproclutch I/Ads: Ad is not visible. Not refreshing ad.
06-25 03:22:08.981 32303-32303/com.guya.dragracingproclutch I/Ads: Scheduling ad refresh 60000 milliseconds from now.
06-25 03:22:09.001 32303-32303/com.guya.dragracingproclutch I/Ads: Ad is not visible. Not refreshing ad.
06-25 03:22:09.001 32303-32303/com.guya.dragracingproclutch I/Ads: Scheduling ad refresh 60000 milliseconds from now.
06-25 03:22:35.827 32303-32303/com.guya.dragracingproclutch V/GamesNativeSDK: Received Activity Start Event.
06-25 03:22:35.827 32303-25153/com.guya.dragracingproclutch V/GamesNativeSDK: Attached to JVM on thread main_dispatch
06-25 03:22:35.827 32303-32303/com.guya.dragracingproclutch V/GamesNativeSDK: Received Activity Resume Event.
06-25 03:22:35.837 32303-32303/com.guya.dragracingproclutch I/Unity: onResume
06-25 03:22:35.857 32303-32333/com.guya.dragracingproclutch D/Unity: Sensor :        Accelerometer ( 1) ; 0.009577 / 0.01s ; BMA254 / BOSCH 
06-25 03:22:35.917 32303-32333/com.guya.dragracingproclutch I/Unity: !!!!!ONLEFTROOM!!!!!
                                                                     UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
                                                                     UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
                                                                     UnityEngine.Logger:Log(LogType, Object)
                                                                     UnityEngine.Debug:Log(Object)
                                                                     OnlineMultiManager:OnLeftRoom() (at C:\Users\Yavuz\Documents\2DCarTest\Assets\Scripts\OnlineMultiManager.cs:218)
                                                                     GooglePlayGames.Native.OnGameThreadForwardingListener:<LeftRoom>m__AF() (at C:\Users\Yavuz\Documents\2DCarTest\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:726)
                                                                     GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at C:\Users\Yavuz\Documents\2DCarTest\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:136)
                                                                      
                                                                     (Filename: C Line: 0)
06-25 03:22:36.148 32303-32303/com.guya.dragracingproclutch V/GamesNativeSDK: Play Games callback indicates connection.
06-25 03:22:36.168 32303-25153/com.guya.dragracingproclutch I/GamesNativeSDK: Successfully connected to Google Play.

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
