### ISSUE TITLE
Google game play services error

### ISSUE THREAD

**Issue by naveenavemuri** [playgameservices/play-games-plugin-for-unity#1205]
HI

 i have dowloaded the google play servicesfrom here https://github.com/playgameservices/play-games-plugin-for-unity. i followed the description i have unity 5.2.0f3 and  android sdk tools rev 25.1.7 and android sdk platform tools 23.1 and android 5.0.1 on java 1.8.0_91. when i tried quizracer sample even then its giving me same conflict. 

 waiting for reply.

CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Program Files (x86)\android-sdk-windows\build-tools\23.0.0\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Program Files (x86)/android-sdk-windows\platforms\android-21\android.jar" -F bin/resources.ap_ --extra-packages com.google.firebase:com.google.example.games.mainlibproj:com.google.android.gms.analytics:com.google.android.gms.analytics:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.tasks:android.support.v4 -S "D:\Training\New MPTEST\Temp\StagingArea\android-libraries\firebase-common-9.0.2\res" -S "D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-analytics-9.0.2\res" -S "D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-analytics-impl-9.0.2\res" -S "D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-auth-base-9.0.2\res" -S "D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res" -S "D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-basement-9.0.2\res" -S "D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-drive-9.0.2\res" -S "D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-games-9.0.2\res" -S "D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-nearby-9.0.2\res" -S "D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-tasks-9.0.2\res" -S "D:\Training\New MPTEST\Temp\StagingArea\android-libraries\support-v4-23.4.0\res"

stderr[
AndroidManifest.xml:13: Tag <provider> attribute authorities has invalid character '$'.
]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: C:\Program Files (x86)\android-sdk-windows\platforms\android-21\android.jar
applyFileOverlay for drawable
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_icon_light.xml
trying overlaySet Key=common_google_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_google_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_light_pressed.9.png
trying overlaySet Key=common_ic_googleplayservices.png
trying overlaySet Key=common_plus_signin_btn_icon_dark.xml
trying overlaySet Key=common_plus_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light.xml
trying overlaySet Key=common_plus_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark.xml
trying overlaySet Key=common_plus_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_light.xml
trying overlaySet Key=common_plus_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_pressed.9.png
trying overlaySet Key=app_banner.png
trying overlaySet Key=app_icon.png
applyFileOverlay for layout
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
trying overlaySet Key=gtm_analytics
applyFileOverlay for color
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_plus_signin_btn_text_dark.xml
trying overlaySet Key=common_plus_signin_btn_text_light.xml
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res\drawable-xhdpi\app_banner.png
Processing image: res\drawable\app_icon.png
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-mdpi-v4\common_full_open_on_phone.png
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-tvdpi-v4\common_full_open_on_phone.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-mdpi-v4\common_full_open_on_phone.png: 136% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-hdpi-v4\common_full_open_on_phone.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-tvdpi-v4\common_full_open_on_phone.png: 105% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xhdpi-v4\common_full_open_on_phone.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-hdpi-v4\common_full_open_on_phone.png: 105% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xxhdpi-v4\common_full_open_on_phone.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xhdpi-v4\common_full_open_on_phone.png: 105% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-mdpi-v4\common_google_signin_btn_icon_dark_disabled.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xxhdpi-v4\common_full_open_on_phone.png: 105% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-tvdpi-v4\common_google_signin_btn_icon_dark_disabled.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-mdpi-v4\common_google_signin_btn_icon_dark_disabled.9.png: 270% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-hdpi-v4\common_google_signin_btn_icon_dark_disabled.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-tvdpi-v4\common_google_signin_btn_icon_dark_disabled.9.png: 242% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xhdpi-v4\common_google_signin_btn_icon_dark_disabled.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-hdpi-v4\common_google_signin_btn_icon_dark_disabled.9.png: 268% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_dark_disabled.9.png
    (processed image res\drawable\app_icon.png: 94% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-mdpi-v4\common_google_signin_btn_icon_dark_focused.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xhdpi-v4\common_google_signin_btn_icon_dark_disabled.9.png: 261% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-tvdpi-v4\common_google_signin_btn_icon_dark_focused.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-mdpi-v4\common_google_signin_btn_icon_dark_focused.9.png: 151% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-hdpi-v4\common_google_signin_btn_icon_dark_focused.9.png
    (processed image res\drawable-xhdpi\app_banner.png: 93% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xhdpi-v4\common_google_signin_btn_icon_dark_focused.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-tvdpi-v4\common_google_signin_btn_icon_dark_focused.9.png: 126% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_dark_focused.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_dark_disabled.9.png: 244% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-mdpi-v4\common_google_signin_btn_icon_dark_normal.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-hdpi-v4\common_google_signin_btn_icon_dark_focused.9.png: 142% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-tvdpi-v4\common_google_signin_btn_icon_dark_normal.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-mdpi-v4\common_google_signin_btn_icon_dark_normal.9.png: 154% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-hdpi-v4\common_google_signin_btn_icon_dark_normal.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xhdpi-v4\common_google_signin_btn_icon_dark_focused.9.png: 134% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xhdpi-v4\common_google_signin_btn_icon_dark_normal.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-tvdpi-v4\common_google_signin_btn_icon_dark_normal.9.png: 132% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_dark_normal.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-hdpi-v4\common_google_signin_btn_icon_dark_normal.9.png: 142% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-mdpi-v4\common_google_signin_btn_icon_dark_pressed.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-mdpi-v4\common_google_signin_btn_icon_dark_pressed.9.png: 149% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-tvdpi-v4\common_google_signin_btn_icon_dark_pressed.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_dark_focused.9.png: 124% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-hdpi-v4\common_google_signin_btn_icon_dark_pressed.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xhdpi-v4\common_google_signin_btn_icon_dark_normal.9.png: 136% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xhdpi-v4\common_google_signin_btn_icon_dark_pressed.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-tvdpi-v4\common_google_signin_btn_icon_dark_pressed.9.png: 130% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_dark_pressed.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-hdpi-v4\common_google_signin_btn_icon_dark_pressed.9.png: 139% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-mdpi-v4\common_google_signin_btn_icon_light_disabled.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-mdpi-v4\common_google_signin_btn_icon_light_disabled.9.png: 218% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-tvdpi-v4\common_google_signin_btn_icon_light_disabled.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_dark_normal.9.png: 126% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-hdpi-v4\common_google_signin_btn_icon_light_disabled.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xhdpi-v4\common_google_signin_btn_icon_dark_pressed.9.png: 133% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xhdpi-v4\common_google_signin_btn_icon_light_disabled.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-tvdpi-v4\common_google_signin_btn_icon_light_disabled.9.png: 193% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_disabled.9.png
    (processed image D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-hdpi-v4\common_google_signin_btn_icon_light_disabled.9.png: 217% size of source)
Processing image: D:\Training\New MPTEST\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res\drawable-mdpi-v4\common_google_signin_btn_icon_light_focused.9.png
    (processed image D:\Training\New MPTEST\Te<message truncated>

**Comment by tomski174** [comment]
Had the same problem last few days. Managed to overcome it by uninstalling current version of SDK Build-tools and installing version 20.
