### ISSUE TITLE
Invalid classname Error when setup pressed

### ISSUE THREAD

**Issue by tomski174** [playgameservices/play-games-plugin-for-unity#1207]
Would anyone be able to help please, I keep on getting this error and cannot figure out what is causing it.
I enter the class name, copy/paste Resources Definition and Clinet ID and press setup.
Thank you.
![error](https://cloud.githubusercontent.com/assets/19754252/15805127/6e83518c-2b63-11e6-9809-5e3a97356949.png)

**Comment by DroidifyDevs** [comment]
I have the exact same issue, Google really needs to fix their buggy stuff.

**Comment by HeavenWu** [comment]
i have no error.
are you sure you have setting your oauth2 ? in the https://console.developers.google.com/apis/

**Comment by tomski174** [comment]
Client ID or not, it still shows the same error. Seems like it is a common issue.

**Comment by DroidifyDevs** [comment]
@tomski174 Try updating your JDK. Didn't help me but might help you.

**Comment by tomski174** [comment]
Updating the JDK and setting up JAVA_HOME variables properly solved the issue. Thank you all for contributing!
