### ISSUE TITLE
Can't log in player with script that worked before

### ISSUE THREAD

**Issue by DroidifyDevs** [playgameservices/play-games-plugin-for-unity#1210]
So I have this script I'm using to log in the player and post a score:
`        using GooglePlayGames;
        using UnityEngine;
        using UnityEngine.UI;
       using System.Collections;
       public class PlayGamesWorksinRT2 : MonoBehaviour {

       public Text StatusText;
    // Use this for initialization
    void Start()
    {
        StatusText.text = "Started script";
        PlayGamesPlatform.Activate();
        StatusText.text = "PlayGamePlatform.Active() Done :)";
        Social.localUser.Authenticate((bool success) =>
        {
            StatusText.text = "Trying to login.";
            if (success)
            {
                StatusText.text = "Social.localUser.Authenticate((bool success) => Done :)";
                GoogleTest();
            }

            else
                Debug.Log("Auth wrong :(");
            StatusText.text = "Login failed :(";
        });

        PlayGamesPlatform.Activate();

        //Social.ReportScore(PlayerPrefs.GetInt("BotKillAmount"), "CgkIyIHOuJcOEAIQBw", (bool success) => {

        Social.ReportScore(123, "CgkIsJqN-OkWEAIQBw", (bool success) => {
        });
    }

    // Update is called once per frame
    void Update () {
    }

    void GoogleTest() //Call GameOver whenever your game is... over, let say .. when your player got N amount of points or N amount of damage...

    {
        Debug.Log("Activated, Auth begins");

        StatusText.text = "Started GoogleTest() :)";

        PlayGamesPlatform.Activate();

        //Social.ReportScore(PlayerPrefs.GetInt("BotKillAmount"), "CgkIyIHOuJcOEAIQBw", (bool success) => {

        Social.ReportScore(123, "CgkIsJqN-OkWEAIQBw", (bool success) => {

            StatusText.text = "Score posted :)";

        });

        PlayGamesPlatform.Activate();

        Social.ShowLeaderboardUI();

        StatusText.text = "Showing Leaderboard :)";

    }

    }``

What's confusing to me is that the script I posted has worked fine in older projects, but in my new project it doesn't work. When it starts, it opens the green tile showing the Google Play Logo, loads a circle for a second then disappears. My custom console (StatusText.text) shows "Login Failed :(", meaning the user wasn't logged in. However it never even shows the user account selection window, because the Google Play Games tile dissapears!

 Anyone know a fix for this issue, or just any ideas to help?

**Comment by claywilkinson** [comment]
Can you check the log to see what messages are being reported when authenticating?  Usually there is some sort of reason in the log.

**Comment by DroidifyDevs** [comment]
@claywilkinson How do I check the log? Thank you

**Comment by Feelnside** [comment]
Hello DroidifyDevs!
Try to add these in your activation code:
```
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;
```
Also I see, that you several times run "PlayGamesPlatform.Activate();". As far as I know we should use this one only one time. So, in your case try to remove each "PlayGamesPlatform.Activate();" lines below the first one.

I can successfully login into my Google Play account and set up any achievements.

**Comment by DroidifyDevs** [comment]
@Feelnside  THANK YOU! It now works perfectly!

Here's the code I used:

`using GooglePlayGames;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;


public class PlayGamesWorksinRT2 : MonoBehaviour {

    public Text StatusText;
    // Use this for initialization
    void Start() 
	{
        StatusText.text = "Started script";
        PlayGamesPlatform.Activate();
        StatusText.text = "PlayGamePlatform.Active() Done :)";
        Social.localUser.Authenticate((bool success) =>
        {
            StatusText.text = "Trying to login.";
            if (success)
            {
                StatusText.text = "Social.localUser.Authenticate((bool success) => Done :)";
                GoogleTest();
            }
            else
                Debug.Log("Auth wrong :(");
            StatusText.text = "Login failed :(";
        });
		//Social.ReportScore(PlayerPrefs.GetInt("BotKillAmount"), "CgkIyIHOuJcOEAIQBw", (bool success) => {
		Social.ReportScore(123, "CgkIsJqN-OkWEAIQBw", (bool success) => {
		});   
	}
	
	// Update is called once per frame
	void Update () {
	
	}

    void GoogleTest() //Call GameOver whenever your game is... over, let say .. when your player got N amount of points or N amount of damage...
    {
        //if (actualScore >= 5000)
        //    winText.text = "Good Job";

        Debug.Log("Activated, Auth begins");
        StatusText.text = "Started GoogleTest() :)";
		//Social.ReportScore(PlayerPrefs.GetInt("BotKillAmount"), "CgkIyIHOuJcOEAIQBw", (bool success) => {
		Social.ReportScore(123, "CgkIsJqN-OkWEAIQBw", (bool success) => {
            StatusText.text = "Score posted :)";
        });
        Social.ShowLeaderboardUI();
        StatusText.text = "Showing Leaderboard :)";
    }
}
`
