### ISSUE TITLE
Errors when build APK in Android Studio (duplicate entry: com/google/android/gms/internal/zzbn.class)

### ISSUE THREAD

**Issue by AlexWitcher** [playgameservices/play-games-plugin-for-unity#1211]
Hi! I just updated Play Services Plugin, and I'm trying to build application from Android Studio, but I get an error:  Execution failed for task ':fairyTiles:transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzbn.class

Unity version: 5.3.2p4

I saw a similar theme: https://github.com/playgameservices/play-games-plugin-for-unity/issues/1206, but unfortunately did not find help.

I'm trying to make a build with enabled multiDex.

dependencies {
    compile project(':firebasecommon902')
    compile project(':mainLibProj')
    compile project(':notifications')
    compile project(':unityandroidresources')
    compile files('libs/androidannotations-api-3.3.1.jar')
    compile files('libs/bolts-applinks-1.3.0.jar')
    compile files('libs/bolts-tasks-1.3.0.jar')
    compile files('libs/com.google.gson.jar')
    compile files('libs/FlurryAnalytics-5.4.0.jar')
    compile files('libs/FuseUnitySDK.jar')
    compile files('libs/jsr311-api-1.1.1.jar')
    compile files('libs/liboffers.jar')
    compile files('libs/libterms.jar')
    compile files('libs/MobileAppTracker-3.11.4.jar')
    compile files('libs/offersunity.jar')
    compile files('libs/org.restlet.ext.gson.jar')
    compile files('libs/org.restlet.jar')
    compile files('libs/support-annotations-23.4.0.jar')
    compile files('libs/termsunity.jar')
    compile files('libs/TUNEUnityUtils.jar')
    compile files('libs/unity-classes.jar')
    compile project(':cardview-v7-23.1.1')
    compile project(':common')
    compile project(':facebook-android-sdk-4.9.0')
    compile project(':facebook-android-wrapper-7.4.0')
    compile project(':FuseSDK')
    compile project(':GoogleAIDL')
    compile project(':GooglePlay')
    compile project(':play-services-ads-8.4.0')
    compile project(':play-services-analytics-8.4.0')
    compile project(':play-services-auth-base-9.0.2')
    compile project(':play-services-base-9.0.2')
    compile project(':play-services-basement-9.0.2')
    compile project(':play-services-drive-9.0.2')
    compile project(':play-services-games-9.0.2')
    compile project(':play-services-nearby-9.0.2')
    compile project(':play-services-plus-8.4.0')
    compile project(':play-services-tasks-9.0.2')
    compile project(':support-v4-23.4.0')
    compile files('libs/play-games-plugin-support.jar')
    compile 'com.android.support:multidex:1.0.0'
}

**Comment by claywilkinson** [comment]
You cannot mix play-services versions. You have some that are 8.4.0 and some are 9.0.2.  Can you make them all 9.0.2 and see if that helps?

**Comment by HeavenWu** [comment]
if you still got other errors , you can try to compile online Google Project rather than use the Google Project which is generated by Unity3D.
example :
change
    compile project(':play-services-ads-9.0.2')
to
    compile 'com.google.android.gms:play-services-ads:9.0.2'
