### ISSUE TITLE
Issue with Unity GPGS setup

### ISSUE THREAD

**Issue by nmndwivedi** [playgameservices/play-games-plugin-for-unity#1215]
I have the latest JDK, SDK and GPG plugin, but when I try to configure the GPG settings I get the following error: 

Invalid classname: An exception was thrown by the type initializer for GooglePlayGames.Editor.GPGSDependencies

Could someone please help with this issue..thank you.

**Comment by Vanleest** [comment]
make sure you have installed following libraries in sdk manager:
- Google Play Services,
- Android Support Library,
- Local Maven repository for Support Libraries (Also known as Android Support Repository), 
- Google Repository ,
- Android 6.0 (API 23).
It helped me with same error

**Comment by nmndwivedi** [comment]
Thank you!!! Its solved!
