### ISSUE TITLE
Android setup error "firebase-common-9.0.2" / Social.localUser.Authenticate crash

### ISSUE THREAD

**Issue by Vanleest** [playgameservices/play-games-plugin-for-unity#1216]
Hello, 
in a last few days i have some serious problems with this plugin. Everything was set and working then out of nowhere published apk started crashing on Social.localUser.Authenticate call. It was 0.9.31a version so i decided to update to latest version 0.9.34. Then another error appears, trying to do Window -> Google Play Games-> Setup -> Android result with this: 
![error](https://cloud.githubusercontent.com/assets/19837137/15930564/e96d5396-2e53-11e6-80cb-345002d71ede.png)

Using PlayServicesResolver-> Resolve Client Jars generate this error:

Win32Exception: ApplicationName='c:\Program Files\Java\jdk1.8.0_92\bin\bin\jar.exe', CommandLine='xvf "D:\Work\Test\TestGooglePlay\Assets\Plugins\Android\firebase-common-9.0.2.aar"', CurrentDirectory='D:\Work\Test\TestGooglePlay\Assets\Plugins\Android\firebase-common-9.0.2'
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
GooglePlayServices.DefaultResolver.ProcessAar (System.String dir, System.String aarFile) (at Assets/PlayServicesResolver/Editor/DefaultResolver.cs:213)

Searching for answers get me nowhere, I already did:
- updated Unity to version 5.3.5f1
- updated jdk/jre to version 1.8.0_92
- check for duplicates .jar and .aar files - nope, only in Temp folder which are created with every build
- changed enviroment variables JAVA_HOME and PATH to correct ones
- reinstalled sdk manager making sure i have required libraries :
                - Google Play Services
                - Android Support Library
                - Local Maven repository for Support Libraries (Also known as Android Support Repository)
                - Google Repository
                - Android 6.0 (API 23) 
- downgraded plugin to versions 0.9.32 and 0.9.33 receiving some other kinds of errors like $ in AndroidManifest.xml, repackaging assets etc
- created brand new empty project just with this plugin making sure there is no other things getting into conflict or wrong AndroidManifest.xml

Anyone have any idea? Thanks in advance.

**Comment by claywilkinson** [comment]
Can you run the command `c:\Program Files\Java\jdk1.8.0_92\bin\bin\jar.exe xvf "D:\Work\Test\TestGooglePlay\Assets\Plugins\Android\firebase-common-9.0.2.aar"` from the command line?
You definitely want to use the latest version of the plugin to avoid the problems with the $ in the manifests.

**Comment by skyboardsoftware** [comment]
Any updates on this.. I am pulling my hair out trying to figure out what went wrong as well.  All was good for a couple months and then Bang!  all of a sudden everything started to go haywire..  I have tried the 0.9.32, 33,.34... all with no success...  The latest version 0.9.34 has issues with the firebase not getting packaged properly... once you block the firebase-common file from getting included in the build the CommandInvokationFailure: Failed to re-package resources error goes away and then I am now faced with the CommandInvokationFailure: Unable to convert classes into dex format.  ahhhhh   I have done everything....

**Comment by claywilkinson** [comment]
This is fixed in 0.9.39 of this plugin.
