### ISSUE TITLE
CreateQuickGame pops default Room UI once

### ISSUE THREAD

**Issue by gtFaTE** [playgameservices/play-games-plugin-for-unity#1218]
When I restart the App on my Real Device, calling  PlayGamesPlatform.Instance.RealTime.CreateQuickGame(MinOpponents, MaxOpponents,
                GameVariant, this);
results in a waiting room ui, while it is documented, that it will not show any ui.
How can I disable it.
Strange thing is, if I leave the room and start another quick match, there is no default room ui shown.
It only appears once.

LogCat:

I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:33:19 +02:00 DEBUG: Showi
ng UI Internal callback: VALID
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:33:19 +02:00 DEBUG: Invok
ing user callback on game thread
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:33:19 +02:00 DEBUG: Recei
ved UI callback: VALID
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:33:35 +02:00 DEBUG: Quick
Game: Setting MinPlayersToStart = 1
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:33:35 +02:00 DEBUG: OnDat
a Callback has addr: 35
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:33:35 +02:00 DEBUG: Befor
eRoomCreateStartedState.IsNonPreemptable: Is preemptable by default.
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:33:35 +02:00 DEBUG: Enter
ing state: RoomCreationPendingState
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:33:35 +02:00 DEBUG: RoomC
reationPendingState.OnStateEntered: Defaulting to no-op.
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:33:37 +02:00 DEBUG: Enter
ing internal callback for RealtimeManager#InternalRealTimeRoomCallback
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:33:37 +02:00 DEBUG: Enter
ing state: ConnectingState
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725): Room Setup Progress: 20
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:33:37 +02:00 DEBUG: Enter
ing internal callback for AndroidPlatformConfiguration#InternalIntentHandler
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:33:37 +02:00 DEBUG: Appli
cation is pausing, which disconnects the RTMP  client.  Leaving room.
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:33:37 +02:00 DEBUG: Not l
eaving room since showing UI
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):

If I press Back from waitingRoomUI

I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:35:31 +02:00 DEBUG: Enter
ing internal callback for RealtimeManager#InternalWaitingRoomUICallback
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725):  [Play Games Plugin DLL] 06/11/16 2:35:31 +02:00 DEBUG: ShowW
aitingRoomUI Response: ERROR_CANCELED
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):
I/Unity   (21725): Room Setup Progress: 20
I/Unity   (21725):
I/Unity   (21725): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (21725):

**Comment by gtFaTE** [comment]
SOLVED IT:
was a silly mistake made by myself:
don't call    PlayGamesPlatform.Instance.RealTime.ShowWaitingRoomUI();
in  OnRoomSetupProgress(float percent)
:+1:

**Comment by SamMcfly** [comment]
Hi, 

I have the same issue, but how do you display the waiting room UI in OnRoomSetupProgress?

Thanks a lot!

**Comment by gonbooster** [comment]
private bool showingWaitingRoom = false; // Used to not repeat waiting UI every progress.
        public void OnRoomSetupProgress(float progress)
        {
            Debug.Log("OnRoomSetupProgress");

            if (!showingWaitingRoom)
            {
                showingWaitingRoom = true;
                PlayGamesPlatform.Instance.RealTime.ShowWaitingRoomUI();
            }
        }

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
