### ISSUE TITLE
How to Disable Push Notification related Settings in Unity iOS Play Game Services

### ISSUE THREAD

**Issue by AdnanNazir** [playgameservices/play-games-plugin-for-unity#1219]
Hi All. I am using Play Game Services for Unity iOS, Everything seems to work the way it should. But When I install the app in iPhone I get an iOS native message that my app wants to send you notifications. Actually I don't want notifications to be enabled, I am just using Leaderboard and achievement. I want to know that if it would be a problem in approval process by Apple for my App? If so how can I get rid of this issue?

**Comment by mattjackson4** [comment]
Agreed, would like to disable push notifcation permission request on iOS.

**Comment by mattjackson4** [comment]
I have had some success doing the following:
http://stackoverflow.com/questions/37816745/how-to-disable-push-notification-permissions-in-google-play-games-services-on-io/37859430#37859430

**Comment by claywilkinson** [comment]
Commenting out the notification code as suggested in the stackoverflow answer is the best way to go I think.   OK to close this issue?

**Comment by AdnanNazir** [comment]
sure Clay :)

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
