### ISSUE TITLE
Android Activity onResume

### ISSUE THREAD

**Issue by simonebg73** [playgameservices/play-games-plugin-for-unity#1220]
Hi, i'm not sure if this is a bug in the system or the way we're handling activities but we're encountering an issue only when the initial Google play dialog comes up during Authentication. 

If you happen to go to the lock screen while the Google popup is just coming up, the lib seems to throw an exception. In logcat in my activity i see Pause ( when the authentication kicks off ) then Restart...but no Start or Resume. The app is then left completely locked and we have to restart the app by hand.

I've tried all kinds of solutions to no avail, anyone provide any other advice?

We extend our activity via  MainActivity extends UnityPlayerActivity

Have all the usual onPause, onResume etc set up to call the super. equivalents.

When i am in a locked state i see this whenever i tap the screen.

06-11 15:26:45.302: E/PlayEventLogger(20214): Failed to get auth token: no such account
06-11 15:26:45.302: E/PlayEventLogger(20214): java.lang.IllegalArgumentException: no such account
06-11 15:26:45.302: E/PlayEventLogger(20214):   at android.os.Parcel.readException(Parcel.java:1435)
06-11 15:26:45.302: E/PlayEventLogger(20214):   at android.os.Parcel.readException(Parcel.java:1385)
06-11 15:26:45.302: E/PlayEventLogger(20214):   at android.accounts.IAccountManager$Stub$Proxy.getAuthToken(IAccountManager.java:929)
06-11 15:26:45.302: E/PlayEventLogger(20214):   at android.accounts.AccountManager$6.doWork(AccountManager.java:1097)
06-11 15:26:45.302: E/PlayEventLogger(20214):   at android.accounts.AccountManager$AmsTask.start(AccountManager.java:1476)
06-11 15:26:45.302: E/PlayEventLogger(20214):   at android.accounts.AccountManager.getAuthToken(AccountManager.java:1095)
06-11 15:26:45.302: E/PlayEventLogger(20214):   at android.accounts.AccountManager.getAuthToken(AccountManager.java:1009)
06-11 15:26:45.302: E/PlayEventLogger(20214):   at android.accounts.AccountManager.blockingGetAuthToken(AccountManager.java:846)
06-11 15:26:45.302: E/PlayEventLogger(20214):   at com.google.android.play.analytics.EventLogger.getAuthToken(EventLogger.java:936)
06-11 15:26:45.302: E/PlayEventLogger(20214):   at com.google.android.play.analytics.EventLogger.uploadLog(EventLogger.java:725)
06-11 15:26:45.302: E/PlayEventLogger(20214):   at com.google.android.play.analytics.EventLogger.uploadEventsImpl(EventLogger.java:681)
06-11 15:26:45.302: E/PlayEventLogger(20214):   at com.google.android.play.analytics.EventLogger.access$000(EventLogger.java:66)
06-11 15:26:45.302: E/PlayEventLogger(20214):   at com.google.android.play.analytics.EventLogger$1.dispatchMessage(EventLogger.java:267)
06-11 15:26:45.302: E/PlayEventLogger(20214):   at android.os.Looper.loop(Looper.java:137)
06-11 15:26:45.302: E/PlayEventLogger(20214):   at android.os.HandlerThread.run(HandlerThread.java:61)

It seems this exception is perhaps stopping Unity from calling its internal resume?

**Comment by simonebg73** [comment]
unity 5.3.4p1, latest GPGS plugin ( 0.9.34)

06-12 13:15:21.742: D/dalvikvm(5890): GC_CONCURRENT freed 2145K, 32% free 17638K/25604K, paused 4ms+4ms, total 51ms
06-12 13:15:21.742: E/Auth(5890): [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:-991823245>, App: com.google.android.gms, Service: oauth2:https://www.googleapis.com/auth/contextcontroller
06-12 13:15:21.742: E/Auth(5890): ejz: Long live credential not available.
06-12 13:15:21.742: E/Auth(5890): 	at eka.a(SourceFile:3099)
06-12 13:15:21.742: E/Auth(5890): 	at ein.a(SourceFile:397)
06-12 13:15:21.742: E/Auth(5890): 	at eim.a(SourceFile:31369)
06-12 13:15:21.742: E/Auth(5890): 	at eim.a(SourceFile:313)
06-12 13:15:21.742: E/Auth(5890): 	at fjx.a(SourceFile:1201)
06-12 13:15:21.742: E/Auth(5890): 	at fjw.a(SourceFile:530)
06-12 13:15:21.742: E/Auth(5890): 	at fjw.a(SourceFile:196)
06-12 13:15:21.742: E/Auth(5890): 	at efm.a(SourceFile:284)
06-12 13:15:21.742: E/Auth(5890): 	at efm.a(SourceFile:204)
06-12 13:15:21.742: E/Auth(5890): 	at bda.onTransact(SourceFile:137)
06-12 13:15:21.742: E/Auth(5890): 	at android.os.Binder.execTransact(Binder.java:388)
06-12 13:15:21.742: E/Auth(5890): 	at dalvik.system.NativeStart.run(Native Method)
06-12 13:15:21.762: I/Auth(5890): [DefaultAuthDelegateChimeraService] Use browser flow? false
06-12 13:15:21.772: W/AuthSessionAuthenticato(5753): Auth related exception is being ignored: BadAuthentication

It seems in this one case, the GPGS package is not sending back a callback or anything to resume...and continue...as a result i am left on the Green Google Play Games local ( which ic an tap and it disappears ) but the game just does nothing.

Subsequent taps to the screen

06-12 13:17:10.312: E/PlayEventLogger(20214): Failed to get auth token: no such account
06-12 13:17:10.312: E/PlayEventLogger(20214): java.lang.IllegalArgumentException: no such account
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at android.os.Parcel.readException(Parcel.java:1435)
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at android.os.Parcel.readException(Parcel.java:1385)
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at android.accounts.IAccountManager$Stub$Proxy.getAuthToken(IAccountManager.java:929)
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at android.accounts.AccountManager$6.doWork(AccountManager.java:1097)
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at android.accounts.AccountManager$AmsTask.start(AccountManager.java:1476)
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at android.accounts.AccountManager.getAuthToken(AccountManager.java:1095)
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at android.accounts.AccountManager.getAuthToken(AccountManager.java:1009)
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at android.accounts.AccountManager.blockingGetAuthToken(AccountManager.java:846)
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at com.google.android.play.analytics.EventLogger.getAuthToken(EventLogger.java:936)
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at com.google.android.play.analytics.EventLogger.uploadLog(EventLogger.java:725)
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at com.google.android.play.analytics.EventLogger.uploadEventsImpl(EventLogger.java:681)
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at com.google.android.play.analytics.EventLogger.access$000(EventLogger.java:66)
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at com.google.android.play.analytics.EventLogger$1.dispatchMessage(EventLogger.java:267)
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at android.os.Looper.loop(Looper.java:137)
06-12 13:17:10.312: E/PlayEventLogger(20214): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by simonebg73** [comment]
Final bit of feedback

Here is the log for when it works, so anytime during our game or actually in the google sign in flow APART from the initial google connecting dialog, i see this when i goto the lock screen and come back

06-12 14:16:15.922: I/Unity(23558):  [Play Games Plugin DLL] 06/12/16 14:16:15 -07:00 DEBUG: Activating PlayGamesPlatform.
06-12 14:16:15.922: I/Unity(23558):  [Play Games Plugin DLL] 06/12/16 14:16:15 -07:00 DEBUG: Instance was not initialized, using default configuration.
06-12 14:16:15.932: I/Unity(23558):  [Play Games Plugin DLL] 06/12/16 14:16:15 -07:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
06-12 14:16:25.642: I/Unity(23558):  [Play Games Plugin DLL] 06/12/16 14:16:25 -07:00 DEBUG: Creating platform-specific Play Games client.
06-12 14:16:25.642: I/Unity(23558):  [Play Games Plugin DLL] 06/12/16 14:16:25 -07:00 DEBUG: Creating Android IPlayGamesClient Client
06-12 14:16:25.762: V/GamesNativeSDK(23558): Play Games callback indicates connection failure.
06-12 14:16:25.792: I/Unity(23558):  [Play Games Plugin DLL] 06/12/16 14:16:25 -07:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
06-12 14:16:25.822: V/GamesNativeSDK(23558): Play Games callback indicates connection failure.
06-12 14:16:25.892: I/Unity(23558):  [Play Games Plugin DLL] 06/12/16 14:16:25 -07:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
06-12 14:16:36.262: V/GamesNativeSDK(23558): Play Games callback indicates connection failure.
06-12 14:16:37.292: V/GamesNativeSDK(23558): Play Games callback indicates connection failure.
06-12 14:16:38.322: V/GamesNativeSDK(23558): Play Games callback indicates connection failure.
06-12 14:16:39.352: V/GamesNativeSDK(23558): Play Games callback indicates connection failure.
06-12 14:16:39.352: I/Unity(23558):  [Play Games Plugin DLL] 06/12/16 14:16:39 -07:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
06-12 14:16:39.362: I/Unity(23558):  [Play Games Plugin DLL] 06/12/16 14:16:39 -07:00 DEBUG: Invoking user callback on game thread


When i do this DURINGthe connect flow for Google, i get this
06-12 14:17:13.782: I/Unity(23821):  [Play Games Plugin DLL] 06/12/16 14:17:13 -07:00 DEBUG: Activating PlayGamesPlatform.
06-12 14:17:13.792: I/Unity(23821):  [Play Games Plugin DLL] 06/12/16 14:17:13 -07:00 DEBUG: Instance was not initialized, using default configuration.
06-12 14:17:13.792: I/Unity(23821):  [Play Games Plugin DLL] 06/12/16 14:17:13 -07:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
06-12 14:17:24.032: I/Unity(23821):  [Play Games Plugin DLL] 06/12/16 14:17:24 -07:00 DEBUG: Creating platform-specific Play Games client.
06-12 14:17:24.032: I/Unity(23821):  [Play Games Plugin DLL] 06/12/16 14:17:24 -07:00 DEBUG: Creating Android IPlayGamesClient Client
06-12 14:17:24.202: V/GamesNativeSDK(23821): Play Games callback indicates connection failure.
06-12 14:17:24.222: I/Unity(23821):  [Play Games Plugin DLL] 06/12/16 14:17:24 -07:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
06-12 14:17:24.282: V/GamesNativeSDK(23821): Play Games callback indicates connection failure.
06-12 14:17:24.362: I/Unity(23821):  [Play Games Plugin DLL] 06/12/16 14:17:24 -07:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

As you can see, it just sits and does nothing after Leaving Room, so something needs to resume somehow and i'm not sure where else to look right now.

**Comment by simonebg73** [comment]
Hi Clay, is there anything else i can provide which will help narrow this down? I am out of ideas this end, there is something funky going on with the google connect initialization as opposed to the rest of the plugin when entering the lock screen - Unity is simply not getting a onResume back, onRestart/onStart are called but the authentication is ignoring the bad authentication exception. 

Are you about to repro this yourself or is it something our end?

thanks

**Comment by claywilkinson** [comment]
The pausing is done when another activity is about to be shown.  In this case it should be the sign-in UI (I think).  The resume would happen when the onActivityResult() is called when the activity finishes.

What version of the client API, play games App, and play-services are you using?  These are printed in the log when the SDK is first loaded.

Have you been able to build one of the samples, for example Minimal, and use your resource info to set it up?  This is a good sanity check.

**Comment by simonebg73** [comment]
Yeah, the problem is the google connect portion at the beginning ( white dialog -> green ) doesn't complete when i go to a lock screen and come back..the child activity is still running but the app sits there in portrait mode, half the title screen is only shown. i never get an onResume back. I'll post the versions soon.  The strange thing is once it gets past this point, the rest of the plugin works absolutely fine.

I'll try the sample later today/tomorrow.
thanks
Simon

**Comment by claywilkinson** [comment]
OK - so the problem is when the flow is:
- start auth activity
- go to lock screen
- unlock
- (now the player is stuck)?

**Comment by simonebg73** [comment]
Yep pretty much. I haven't had chance to set up a basic project+sample yet but will do soon.

Our app is in landscape mode, the sign in switches to portrait. The load screen now only covers half the screen, however every other app we've used that is similar does exactly this. The google auth kicks off and before you get to Existing / New Account dialog, go to the lock screen. Come back. No resume is called.

The google dialog is still up.
I tap it, it disappears, the app has not crashed but it is soft-locked - you can however hit the android back button and the app resumes ok.

As soon as i get beyond the initial authentication, doing the above is absolutely fine.

**Comment by simonebg73** [comment]
We're also deriving from the UnityPlayerActivity for our main activity, i've double-checked all overrides call their base equivalents. There is no issue with this anywhere else in the app at all.

**Comment by claywilkinson** [comment]
Please open a new issue if this is still a problem.
