### ISSUE TITLE
Unable to setup Plugins

### ISSUE THREAD

**Issue by michaeljoshua55555** [playgameservices/play-games-plugin-for-unity#1221]
I copied and pasted the resources in the setup window.
I am building for android.
I am using unity 5.3.5
I gave the constant class name as GPGSIds - just like in the screenshot

I am getting this error after I click on the setup button.
Invalid classname: An exception was thrown by the type initializer foir GooglePlayGames.Editor.GPGSDependencies

What should I do? I Need Help

**Comment by claywilkinson** [comment]
Is this related to your other issue: #1222 ?

**Comment by michaeljoshua55555** [comment]
Yes it is related to #1222
