### ISSUE TITLE
In Unity4 also setup is not working

### ISSUE THREAD

**Issue by michaeljoshua55555** [playgameservices/play-games-plugin-for-unity#1222]
This time two errors
![capture](https://cloud.githubusercontent.com/assets/14315441/16003710/a5faaf5c-317b-11e6-9275-2c3df609e4b9.JPG)

I wrote the constant class name as GPGSIds just like in the screenshot

![setuperror](https://cloud.githubusercontent.com/assets/14315441/16003764/ede8b3e0-317b-11e6-9094-d866fe5611c3.JPG)

**Comment by claywilkinson** [comment]
From the top image - it cannot file play-services-games version 9+ - This means you need to update the google repository component in the Android SDK.

**Comment by michaeljoshua55555** [comment]
Thank you so much, @claywilkinson . I updated my android sdk, and everything is working now.
I was literally going nuts, not knowing what to do.  Thanx to you I am cool now
