### ISSUE TITLE
Nothing in Cubic Pilot Scene

### ISSUE THREAD

**Issue by michaeljoshua55555** [playgameservices/play-games-plugin-for-unity#1224]
I imported the cubit pilot unity package

When I tried opening any of the three available, there seems to be nothing in it.

What to do? Should I checkout a lower version of the package.

**Comment by lijuicsoft** [comment]
Same problem

**Comment by lijuicsoft** [comment]
I was facing same problem  . I was using  Unity 4.7.1 , and sample projects is not working in that version . After that i installed 5.3.5 version , in that version it is working
