### ISSUE TITLE
Missing the Android Setup window (should be under Window > Google Play Games > Setup > Android Setup)

### ISSUE THREAD

**Issue by ToastDispatch** [playgameservices/play-games-plugin-for-unity#1225]
I have every other window for Google Play Games, just not Android Setup.

I have build settings set to Android, updated the Android SDK to the latest version, am using the latest Google Play Games version, updated my JDK, updated Unity. None of that fixed anything.

**Comment by claywilkinson** [comment]
What is your target player platform?  It needs to be Android for the menu to appear.  You can set the player platform under File > Build Settings

**Comment by ToastDispatch** [comment]
As I said, it is set to Android. I tried switching to another platform and then going back, that didn't fix it either.

**Comment by claywilkinson** [comment]
Hmm ok - are there errors in the editor console?  Maybe the plugin did not load correctly?

**Comment by ToastDispatch** [comment]
No errors or warnings, and I thought the same about not loading correctly, tried re-installing the plugin already a couple times and it didn't change anything.

**Comment by ToastDispatch** [comment]
After the window being gone for a couple weeks, it just came back. I have no idea why. It seems to be working fine now.

**Comment by claywilkinson** [comment]
Glad to hear it is back!

**Comment by MuradDasi** [comment]
I am having same problem .. I dont see anything under window called Google Play Games
**Using:** Unity 2017.1.0p4 (64-bit)
can i input sittings manually I cant wait 2 weeks?
