### ISSUE TITLE
Warning: Unreachable code detected

### ISSUE THREAD

**Issue by michaeljoshua55555** [playgameservices/play-games-plugin-for-unity#1228]
Plugin is always warning about unreachable code detected, is there anything i can do to stop that
Will I have issues when I integrate with game.

![unreachablecode](https://cloud.githubusercontent.com/assets/14315441/16035519/3b3446b4-3235-11e6-8703-82f9f690886d.JPG)

**Comment by Mavicus** [comment]
To get rid of the compiler warning, try the fix from this file #1227

**Comment by michaeljoshua55555** [comment]
Just replace this line

if (PluginVersion.VersionKey !=  PluginVersion.VersionKeyJNIStats) {
with this line

if (!PluginVersion.VersionKey.Equals (PluginVersion.VersionKeyJNIStats)) {
and that should fix the compiler warning.
