### ISSUE TITLE
Does Plugin support Inapp purchases

### ISSUE THREAD

**Issue by michaeljoshua55555** [playgameservices/play-games-plugin-for-unity#1229]
Is there any way to implement inapp purchase with plugin

**Comment by Jackmac2904** [comment]
I don't think so, the necessary tools are already in unity if you go into the windows tab and select services you will see all the available services you can offer including inapp purchases, here is the video tutorial I used to set it up

https://www.youtube.com/watch?v=oyZD6b86X1s
