### ISSUE TITLE
LoadFriends() not giving friends list

### ISSUE THREAD

**Issue by hirenkacha** [playgameservices/play-games-plugin-for-unity#1232]
I tried using this call in our existing game. I can check friends in play games for the common game, but not getting list using this.

```
public void LoadSocialFriends()
    {
        Social.localUser.LoadFriends((status) =>
        {
            Debug.Log("#Social :: LoadSocialFriends(): " + status+" "+Social.localUser.userName);            
            if (status)
            {
                Debug.Log("#Social :: LoadSocialFriends(): Social.localUser.friends count :: " + Social.localUser.friends.Length);
                foreach (IUserProfile friend in Social.localUser.friends)
                {
                    Debug.Log("#Social My Friend: " + friend.userName + " id: " + friend.id);                   
                }
            }
            else Debug.LogError("#Social Error loading friends from Social");
        });
    }
```

It gives friends count = 0. Login is working fine, I get my userName in logs correct.

**Comment by CenekStrichel** [comment]
Same for me, 0 friends loaded

**Comment by danCodojo** [comment]
Hi, 
This is the same for me too, using android devices with Unity 5.4.1f1. I get a callback with 0 friends.

If I use google's ui call, below, I am able to view friends and recently played players.

PlayGamesPlatform.Instance.TurnBased.CreateWithInvitationScreen

**Comment by claywilkinson** [comment]
The Play Game Services and Google Plus are in the process of no longer being integrated. As a result, these "social" APIs, will return empty lists. More information is at: https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html
