### ISSUE TITLE
How to completely remove GPG plugin from iOS

### ISSUE THREAD

**Issue by zo0m22** [playgameservices/play-games-plugin-for-unity#1234]
Hi,

I decided to remove GPG plugin from my unity project.
First, I tried to remove the 3 files imported with the GPG plugin, unfortunately my Xcode build still return some GPG error.
Also, i tried to uninstall the GPG unity package with "Package Uninstaller", link 
https://www.assetstore.unity3d.com/en/#!/content/35439

Still have GPG errors during the linking of my Xcode build
Here is my Xcode error :
![screen shot 2016-06-15 at 15 52 24](https://cloud.githubusercontent.com/assets/19268011/16084524/0c45abf4-3311-11e6-9218-28bed31a13b3.png)

Does anyone know how to fix this?

Thanks,
Laouenan

**Comment by Mavicus** [comment]
Follow the instructions on how to disable GPGS on iOS builds

https://github.com/playgameservices/play-games-plugin-for-unity#excluding-all-google-play-game-services-when-building-for-ios

Don't forget to press Enter if you are copy and pasting NO_GPGS in the Editor.

**Comment by zo0m22** [comment]
Hi Malicious, thanks for your help.

First, i tried your solution, i added "NO_GPGS" in the scripting define symbol, and tried to rebuild my project. Didn't change anything. (my project doesn't contains GPG package)

So i tried to re-import GPG package, to add the "NO_GPGS" and to rebuild. Unfortunately, this didn't change anything too>

I think the problem come from my Xcode, indeed in 2 month i was never able to build an Xcode project with GPG plugin.... Im desperate

**Comment by claywilkinson** [comment]
@zo0m22 - It sounds like you have resolved this issue?  The symbols that are in the screenshot that are unresolved don't come directly from the plugin.  Is it possible you have some other code that is part of your game that is being excluded but still referenced?

**Comment by zo0m22** [comment]
No I didn't resoled it, sorry for that misunderstanding. I created an empty project to see if the symbol "NO_GPGS" worked on my computer, but it is still not working on my game project. I am trying to import all the assets from my game project to a new project, i hope it will resolve the issue.

Thanks for your help!

**Comment by zo0m22** [comment]
@claywilkinson ok my new project didn't solved it. As you said, i think that I have some other code that is still referenced, but how can I find it ?

**Comment by zo0m22** [comment]
Once my build is done with the symbol "NO_GPGS", i still can find some files with "GPGS" inside
Here is the result of my search of "GPG" inside my build folder
![screen shot 2016-06-17 at 10 19 28](https://cloud.githubusercontent.com/assets/19268011/16146221/e4b06290-3474-11e6-94d0-1047fd961abc.png)

**Comment by claywilkinson** [comment]
The linker errors in XCode refer to methods like "NerdGPG_Signin" - do you have a class or method named that?  That would be where the reference is.
