### ISSUE TITLE
NO_GPGS doesn't work iOS

### ISSUE THREAD

**Issue by litemesa** [playgameservices/play-games-plugin-for-unity#1236]
Hi, I know, there is a lot of threads about using NO_GPGS, but I cannot find a right solution.

I use NO_GPGS flag for iOS and every time I make build I get error in xcode about ​#import <GoogleSignIn/GIDSignIn.h>

This error comes from ​GPGSAppController.mm / GPGSAppController.h and when I delete them I can build my project as usually.
The problem is, every time I make a new build in Unity (with or without Replace checkbox) this files comes to the xCode, and I have to delete them every time.
This is a bit annoying and I would like to know how could I manage this?

I use
Unity 5.3.4
Google Play Games Plugin 0.9.34 - clean install.

Thanks

**Comment by claywilkinson** [comment]
Set NO_GPGS in the Unity editor under "other settings" in the iOS player properties.

**Comment by litemesa** [comment]
To solve this problem I have modified **GPGSPostBuild.cs** file, I have added

```
"Libraries/Plugins/ios/GPGSAppController.mm",
"Libraries/Plugins/ios/GPGSAppController.h",
```

to the **filesToRemove** array.
Could you please add this paths to the next build?
