### ISSUE TITLE
How to check if player is authenticated

### ISSUE THREAD

**Issue by michaeljoshua55555** [playgameservices/play-games-plugin-for-unity#1237]
// This is sign in code
// authenticate user:
    Social.localUser.Authenticate((bool success) => {
        // handle success or failure
    });

but how to check, if he is signed in so that I can persist his state between scenes

**Comment by claywilkinson** [comment]
You can use the Social.localUser.authenticated property.

**Comment by MIADEV** [comment]
if(success){
//signed in
}else{
//not signed in
}
