### ISSUE TITLE
FAILED to re-package resources! For Unity 5.3.4f on PlayGamesPlugin

### ISSUE THREAD

**Issue by jinwei3000** [playgameservices/play-games-plugin-for-unity#1240]
Hello!

I am using Unity 5.3.4f and Currently the project consist of Facebook SDK for unity as well as this plugin. But after importing this plugin I get this error listed below. Please help!

Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Users\User\AppData\Local\Android\sdk\build-tools\24.0.0\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Users/User/AppData/Local/Android/sdk\platforms\android-24\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.cardview:com.facebook:com.facebook.android:com.google.firebase:com.google.example.games.mainlibproj:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.tasks:android.support.v4:com.pixelongames.ElevatorRush -S "D:\Work\1Pixelon Game Studio\Prototype\ElevatorRush\Temp\StagingArea\android-libraries\cardview-v7-23.4.0\res" -S "D:\Work\1Pixelon Game Studio\Prototype\ElevatorRush\Temp\StagingArea\android-libraries\facebook-android-sdk-4.12.1\res" -S "D:\Work\1Pixelon Game Studio\Prototype\ElevatorRush\Temp\StagingArea\android-libraries\facebook-android-wrapper-7.6.0\res" -S "D:\Work\1Pixelon Game Studio\Prototype\ElevatorRush\Temp\StagingArea\android-libraries\firebase-common-9.0.2\res" -S "D:\Work\1Pixelon Game Studio\Prototype\ElevatorRush\Temp\StagingArea\android-libraries\play-services-auth-base-9.0.2\res" -S "D:\Work\1Pixelon Game Studio\Prototype\ElevatorRush\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res" -S "D:\Work\1Pixelon Game Studio\Prototype\ElevatorRush\Temp\StagingArea\android-libraries\play-services-basement-9.0.2\res" -S "D:\Work\1Pixelon Game Studio\Prototype\ElevatorRush\Temp\StagingArea\android-libraries\play-services-drive-9.0.2\res" -S "D:\Work\1Pixelon Game Studio\Prototype\ElevatorRush\Temp\StagingArea\android-libraries\play-services-games-9.0.2\res" -S "D:\Work\1Pixelon Game Studio\Prototype\ElevatorRush\Temp\StagingArea\android-libraries\play-services-nearby-9.0.2\res" -S "D:\Work\1Pixelon Game Studio\Prototype\ElevatorRush\Temp\StagingArea\android-libraries\play-services-tasks-9.0.2\res" -S "D:\Work\1Pixelon Game Studio\Prototype\ElevatorRush\Temp\StagingArea\android-libraries\support-v4-23.4.0\res" -S "D:\Work\1Pixelon Game Studio\Prototype\ElevatorRush\Temp\StagingArea\android-libraries\unity-android-resources\res"

stderr[

]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
  Type values
Including resources from package: C:\Users\User\AppData\Local\Android\sdk\platforms\android-24\android.jar
applyFileOverlay for drawable
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_icon_light.xml
trying overlaySet Key=common_google_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_google_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_light_pressed.9.png
trying overlaySet Key=common_ic_googleplayservices.png
trying overlaySet Key=common_plus_signin_btn_icon_dark.xml
trying overlaySet Key=common_plus_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light.xml
trying overlaySet Key=common_plus_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark.xml
trying overlaySet Key=common_plus_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_light.xml
trying overlaySet Key=common_plus_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_pressed.9.png
trying overlaySet Key=com_facebook_auth_dialog_background.xml
trying overlaySet Key=com_facebook_auth_dialog_cancel_background.xml
trying overlaySet Key=com_facebook_auth_dialog_header_background.xml
trying overlaySet Key=com_facebook_button_background.xml
trying overlaySet Key=com_facebook_button_icon.xml
trying overlaySet Key=com_facebook_button_icon_blue.png
trying overlaySet Key=com_facebook_button_icon_white.png
trying overlaySet Key=com_facebook_button_like_background.xml
trying overlaySet Key=com_facebook_button_like_icon_selected.png
trying overlaySet Key=com_facebook_button_login_silver_background.xml
trying overlaySet Key=com_facebook_button_send_background.xml
trying overlaySet Key=com_facebook_button_send_icon_blue.png
trying overlaySet Key=com_facebook_button_send_icon_white.png
trying overlaySet Key=com_facebook_close.png
trying overlaySet Key=com_facebook_favicon_white.png
trying overlaySet Key=com_facebook_profile_picture_blank_portrait.png
trying overlaySet Key=
]

**Comment by vitordealmeida** [comment]
Same as #1239, apparently

**Comment by ricky395** [comment]
I had this problem before and it was because of the Android SDK directory. In Unity, go to Edit>Preferences>External tools and browse the Android SDK route. My problem there was that I have this folder "C:\Program Files (x86)\Android\android-sdk" when in my case, the good file directory is "C:\Users\MyUser\Documents\Android\sdk"

**Comment by claywilkinson** [comment]
The Android build tools have been fixed.  Please update to 24.0.1.
