### ISSUE TITLE
Can't Register Class when authenticating!

### ISSUE THREAD

**Issue by jinwei3000** [playgameservices/play-games-plugin-for-unity#1241]
Hello! I have managed to build with this plugin!

However, I have a problem when I try to Authenticate.

![image](https://cloud.githubusercontent.com/assets/7345922/16171289/83df846c-359d-11e6-902a-db1bc23e0d4b.png)

I seem to only have problems with the Nearby class hierarchy? 

Please advice!

**Comment by claywilkinson** [comment]
This means you don't have the the play-services-nearby client library in your project.  Make sure you have updated your Android SDK to the latest version of the Google repository and the Android Support repository and re-run the plugin setup.

**Comment by claywilkinson** [comment]
OK to close this issue?
