### ISSUE TITLE
Google Play Services Menu is not appearing in Unity Version 5.3.4p4

### ISSUE THREAD

**Issue by YogendraChauhan** [playgameservices/play-games-plugin-for-unity#1242]
Hi I have imported the package but it is not showing the Google Play Game menu. 
please help.

**Comment by ridhwandaud** [comment]
Build settings is android? @YogendraChauhan

**Comment by tonyjoseph456** [comment]
Same error is happenig for me in Unity 5.3.4p6.

**Comment by andrewlord1990** [comment]
I have the latest Unity version and the latest Google Play Games plugin and it is showing up fine. It appears under Window -> Google Play Games.

This worked for me in 5.3.4p4 and 5.3.4p6. I now have 5.3..5f1 and it is also working.

Do you have any compile errors in your Unity log? As the Google Play Games Editor scripts need to compile for the menu to show up. So whenever there is a compile error in your code it can result in the menu disappearing until it is fixed.

Just realised the issue title says Google Play Services Menu, but the description says Google Play Games Menu. Google Play Games is in Window -> Google Play Games, whereas Google Play Services is in Assets -> Google Play Services (that is just a menu for the Play Services Resolver behaviour). Both having been showing up fine for me for those versions of Unity and the latest plugin.

**Comment by YogendraChauhan** [comment]
Fixed. Thanks....
