### ISSUE TITLE
iOS CreateWithInvitationScreen callback, boolean false

### ISSUE THREAD

**Issue by flinux** [playgameservices/play-games-plugin-for-unity#1243]
I'm struggling with this problem.
In my game i use **CreateWithInvitationScreen** on Android & iOS (same code), on android it works, but on iOS when my callback is called the success boolean is always false.

Edit 1: i'm authenticated and the leaderbords in my game are working correctly

```
    public void InviteFriend()
    {
        SettingsPopup.SetActive(false);
        const int MinOpponents = 1, MaxOpponents = 1;
        const int GameVariant = 0;
        EventManager.challenge = false;
        PlayGamesPlatform.Instance.TurnBased.CreateWithInvitationScreen(MinOpponents, MaxOpponents,
                                                                        GameVariant, OnMatchStarted);
    }
```

**Log:**

 [Play Games Plugin DLL] 06/20/16 13:12:40 +02:00 DEBUG: Entering internal callback for TurnBasedManager#PlayerSelectUICallback

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

2016-06-20 13:12:41.023 awtest[227:15814] VERBOSE: Request had Apiary Status Code: 5
2016-06-20 13:12:41.024 awtest[227:15814] VERBOSE: Parsed error<http_code: 404, domain: global, reason: notFound>
 [Play Games Plugin DLL] 06/20/16 13:12:41 +02:00 DEBUG: Entering internal callback for TurnBasedManager#InternalTurnBasedMatchCallback

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

There was a problem setting up the match.
Please try again.
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
GPGConfig:OnMatchStarted(Boolean, TurnBasedMatch)
GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

**Comment by claywilkinson** [comment]
Thanks! I've passed along the information to the SDK team.
