### ISSUE TITLE
Screen not completely shown... Android Configuration/Setup.

### ISSUE THREAD

**Issue by bykeat** [playgameservices/play-games-plugin-for-unity#1244]
Running Unity 5.3.2f1. Windows 7. Resolution 1366 x 768. After the phrase "...Example:", it bordered. No "Setup" button or "Cancel" button. The textbox for "Client ID" also not there... seems cropped.

![untitled](https://cloud.githubusercontent.com/assets/13861555/16198291/03b88404-3738-11e6-9cc0-3b5f4e671390.png)

**Comment by claywilkinson** [comment]
Thanks for the feedback.  The window is resizable, but it does make sense to make it sized large enough to see all the controls.

**Comment by bykeat** [comment]
Ah I see thanks. I never thought I could resize coz I can't see the pointer
changes. It just hard to point to the edges I guess.
