### ISSUE TITLE
Implement scoreTag? 

### ISSUE THREAD

**Issue by CipherLab** [playgameservices/play-games-plugin-for-unity#1245]
Could submitting a score with scoreTag get implemented if it's not already? I couldn't find any methods to allow this.

**Comment by claywilkinson** [comment]
You can use [PlayGamesPlatform.Instance.ReportScore(long score, string board, string metadata, Action<bool> callback)](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs#L929)
