### ISSUE TITLE
Failed to repackage ressource 

### ISSUE THREAD

**Issue by blookmaker** [playgameservices/play-games-plugin-for-unity#1246]
i am now working on the inplementation of the GPGS plugin for more than two days now and i am still not able to make it work i faced a lot of issue that i was able to fix but now i am blocked with this one and even if there is a lot of other topics threating the issue none of their solution worked . 

please help me fix my issue .

my unity version : unity 5.3.5 f1 
my android sdk is up to date  . 

the issue : 

Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Users\user1\Documents\Projects\Android-Sdk\android-sdk-windows\build-tools\24.0.0\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Users/user1/Documents/Projects/Android-Sdk/android-sdk-windows\platforms\android-24\android.jar" -F bin/resources.ap_ --extra-packages com.google.firebase:com.google.example.games.mainlibproj:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.tasks:android.support.v4 -S "C:\Users\user1\Documents\Projects\PrizePots\Google play\Temp\StagingArea\android-libraries\firebase-common-9.0.2\res" -S "C:\Users\user1\Documents\Projects\PrizePots\Google play\Temp\StagingArea\android-libraries\play-services-auth-base-9.0.2\res" -S "C:\Users\user1\Documents\Projects\PrizePots\Google play\Temp\StagingArea\android-libraries\play-services-base-9.0.2\res" -S "C:\Users\user1\Documents\Projects\PrizePots\Google play\Temp\StagingArea\android-libraries\play-services-basement-9.0.2\res" -S "C:\Users\user1\Documents\Projects\PrizePots\Google play\Temp\StagingArea\android-libraries\play-services-drive-9.0.2\res" -S "C:\Users\user1\Documents\Projects\PrizePots\Google play\Temp\StagingArea\android-libraries\play-services-games-9.0.2\res" -S "C:\Users\user1\Documents\Projects\PrizePots\Google 
.....

please need your help as soon as possible

**Comment by blookmaker** [comment]
No one to figure out why is this happening ?

**Comment by blookmaker** [comment]
Hello the solution to my problem was in the #1239 issue . i will close this one . 
The solution is to delete the 24 folder under the android-sdk-windows\build-tools in your android sdk location . 
hope that it will help anyone who face the problem

**Comment by claywilkinson** [comment]
@blookmaker - are you running Windows or on a Mac?

**Comment by blookmaker** [comment]
@claywilkinson I faced the issue on windows 8

**Comment by blookmaker** [comment]
Windows10*

**Comment by claywilkinson** [comment]
thanks. I don't have windows handy - but I'll try it soon.
