### ISSUE TITLE
CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.

### ISSUE THREAD

**Issue by ammarvohra** [playgameservices/play-games-plugin-for-unity#1248]
Hello I am using **GPGS library version 0.9.34** and the game uses **admob, chartboost and revmob sdk** along with _google play games services library_. When I build an apk I got the following error..
Someone could please help me **asap**.

**Thank You!!!**

Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:/Program Files/Java/jdk1.8.0_77\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="H:/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoJellyBeanMr2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatJellyBeanMr2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle$1;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
	... 9 more
]
stdout[
processing archive H:\Work\Unity\Chicken Run\Code\Temp\StagingArea\android-libraries\ChartboostSDK\libs\.\chartboost.jar...
ignored resource META-INF/MANIFEST.MF
processing com/chartboost/sdk/CBImpressionActivity.class...
processing com/chartboost/sdk/CBImpressionActivity$1.class...
processing com/chartboost/sdk/CBImpressionActivity$2.class...
processing com/chartboost/sdk/CBLocation.class...
processing com/chartboost/sdk/Chartboost.class...
processing com/chartboost/sdk/Chartboost$1.class...
processing com/chartboost/sdk/Chartboost$10.class...
processing com/chartboost/sdk/Chartboost$11.class...
processing com/chartboost/sdk/Chartboost$12.class...
processing com/chartboost/sdk/Chartboost$13.class...
processing com/chartboost/sdk/Chartboost$14.class...
processing com/chartboost/sdk/Chartboost$15.class...
processing com/chartboost/sdk/Chartboost$16.class...
processing com/chartboost/sdk/Chartboost$17.class...
processing com/chartboost/sdk/Chartboost$18.class...
processing com/chartboost/sdk/Chartboost$19.class...
processing com/chartboost/sdk/Chartboost$2.class...
processing com/chartboost/sdk/Chartboost$20.class...
processing com/chartboost/sdk/Chartboost$21.class...
processing com/chartboost/sdk/Chartboost$22.class...
processing com/chartboost/sdk/Chartboost$23.class...
processing com/chartboost/sdk/Chartboost$24.class...
processing com/chartboost/sdk/Chartboost$25.class...
processing com/chartboost/sdk/Chartboost$26.class...
processing com/chartboost/sdk/Chartboost$27.class...
processing com/chartboost/sdk/Chartboost$28.class...
processing com/chartboost/sdk/Chartboost$29.class...
processing com/chartboost/sdk/Chartboost$3.class...
processing com/chartboost/sdk/Chartboost$30.class...
processing com/chartboost/sdk/Chartboost$31.class...
processing com/chartboost/sdk/Chartboost$32.class...
processing com/chartboost/sdk/Chartboost$33.class...
processing com/chartboost/sdk/Chartboost$34.class...
processing com/chartboost/sdk/Chartboost$35.class...
processing com/chartboost/sdk/Chartboost$4.class...
processing com/chartboost/sdk/Chartboost$5.class...
processing com/chartboost/sdk/Chartboost$6.class...
processing com/chartboost/sdk/Chartboost$7.class...
processing com/chartboost/sdk/Chartboost$8.class...
processing com/chartboost/sdk/Chartboost$9.class...
processing com/chartboost/sdk/Chartboost$CBFramework.class...
processing com/chartboost/sdk/Chartboost$CBMediation.class...
processing com/chartboost/sdk/Chartboost$a.class...
processing com/chartboost/sdk/ChartboostActivity.class...
processing com/chartboost/sdk/ChartboostDelegate.class...
processing com/chartboost/sdk/InPlay/CBInPlay.class...
processing com/chartboost/sdk/InPlay/a.class...
processing com/chartboost/sdk/InPlay/a$1.class...
processing com/chartboost/sdk/InPlay/a$2.class...
processing com/chartboost/sdk/InPlay/a$a.class...
processing com/chartboost/sdk/InPlay/a$b.class...
processing com/chartboost/sdk/Libraries/CBLogging.class...
processing com/chartboost/sdk/Libraries/CBLogging$Level.class...
processing com/chartboost/sdk/Libraries/CBUtility.class...
processing com/chartboost/sdk/Libraries/a.class...
processing com/chartboost/sdk/Libraries/a$1.class...
processing com/chartboost/sdk/Libraries/b.class...
processing com/chartboost/sdk/Libraries/c.class...
processing com/chartboost/sdk/Libraries/c$1.class...
processing com/chartboost/sdk/Libraries/c$a.class...
processing com/chartboost/sdk/Libraries/d.class...
processing com/chartboost/sdk/Libraries/e.class...
processing com/chartboost/sdk/Libraries/e$1.class...
processing com/chartboost/sdk/Libraries/e$a.class...
processing com/chartboost/sdk/Libraries/e$b.class...
processing com/chartboost/sdk/Libraries/f.class...
processing com/chartboost/sdk/Libraries/g.class...
processing com/chartboost/sdk/Libraries/g$1.class...
processing com/chartboost/sdk/Libraries/g$a.class...
processing com/chartboost/sdk/Libraries/g$b.class...
processing com/chartboost/sdk/Libraries/g$c.class...
processing com/chartboost/sdk/Libraries/g$d.class...
processing com/chartboost/sdk/Libraries/g$e.class...
processing com/chartboost/sdk/Libraries/g$f.class...
processing com/chartboost/sdk/Libraries/g$g.class...
processing com/chartboost/sdk/Libraries/g$h.class...
processing com/chartboost/sdk/Libraries/g$i.class...
processing com/chartboost/sdk/Libraries/g$j.class...
processing com/chartboost/sdk/Libraries/g$k.class...
processing com/chartboost/sdk/Libraries/g$l.class...
processing com/chartboost/sdk/Libraries/g$m.class...
processing com/chartboost/sdk/Libraries/g$n.class...
processing com/chartboost/sdk/Libraries/g$o.class...
processing com/chartboost/sdk/Libraries/g$p.class...
processing com/chartboost/sdk/Libraries/g$q.class...
processing com/chartboost/sdk/Libraries/h.class...
processing com/chartboost/sdk/Libraries/h$a.class...
processing com/chartboost/sdk/Libraries/i.class...
processing com/chartboost/sdk/Libraries/j.class...
processing com/chartboost/sdk/Libraries/j$1.class...
processing com/chartboost/sdk/Libraries/j$2.class...
processing com/chartboost/sdk/Libraries/j$a.class...
processing com/chartboost/sdk/Libraries/k.class...
processing com/chartboost/sdk/Model/CBError.class...
processing com/chartboost/sdk/Model/CBError$1.class...
processing com/chartboost/sdk/Model/CBError$CBClickError.class...
processing com/chartboost/sdk/Model/CBError$CBImpressionError.class...
processing com/chartboost/sdk/Model/CBError$a.class...
processing com/chartboost/sdk/Model/a.class...
processing com/chartboost/sdk/Model/a$1.class...
processing com/chartboost/sdk/Model/a$a.class...
processing com/chartboost/sdk/Model/a$b.class...
processing com/chartboost/sdk/Model/a$c.class...
processing com/chartboost/sdk/Model/a$d.class...
processing com/chartboost/sdk/Model/a$e.class...
processing com/chartboost/sdk/Model/b.class...
processing com/chartboost/sdk/Tracking/CBAnalytics.class...
processing com/chartboost/sdk/Tracking/CBAnalytics$1.class...
processing com/chartboost/sdk/Tracking/CBAnalytics$CBIAPPurchaseInfo.class...
processing com/chartboost/sdk/Tracking/CBAnalytics$CBIAPType.class...
processing com/chartboost/sdk/Tracking/CBAnalytics$CBLevelType.class...
processing com/chartboost/sdk/Tracking/a.class...
processing com/chartboost/sdk/a.class...
processing com/chartboost/sdk/b.class...
processing com/chartboost/sdk/b$1.class...
processing com/chartboost/sdk/b$2.class...
processing com/chartboost/sdk/b$3.class...
processing com/chartboost/sdk/b$4.class...
processing com/chartboost/sdk/b$5.class...
processing com/chartboost/sdk/b$a.class...
processing com/chartboost/sdk/b$b.class...
processing com/chartboost/sdk/b$c.class...
processing com/chartboost/sdk/b$d.class...
processing com/chartboost/sdk/b$e.class...
processing com/chartboost/sdk/c.class...
processing com/chartboost/sdk/c$1.class...
processing com/chartboost/sdk/c$a.class...
processing com/chartboost/sdk/d.class...
processing com/chartboost/sdk/d$1.class...
processing com/chartboost/sdk/d$1$1.class...
processing com/chartboost/sdk/d$2.class...
processing com/chartboost/sdk/d$3.class...
processing com/chartboost/sdk/d$4.class...
processing com/chartboost/sdk/d$a.class...
processing com/chartboost/sdk/d$b.class...
processing com/chartboost/sdk/e.class...
processing com/chartboost/sdk/e$1.class...
processing com/chartboost/sdk/e$2.class...
processing com/chartboost/sdk/e$3.class...
processing com/chartboost/sdk/e$4.class...
processing com/chartboost/sdk/e$4$1.class...
processing com/chartboost/sdk/e$4$2.class...
processing com/chartboost/sdk/e$a.class...
processing com/chartboost/sdk/f.class...
processing com/chartboost/sdk/f$1.class...
processing com/chartboost/sdk/f$2.class...
processing com/chartboost/sdk/f$2$1.class...
processing com/chartboost/sdk/f$2$1$1.class...
processing com/chartboost/sdk/f$3.class...
processing com/chartboost/sdk/g.class...
processing com/chartboost/sdk/g$1.class...
processing com/chartboost/sdk/g$a.class...
processing com/chartboost/sdk/g$a$1.class...
processing com/chartboost/sdk/g$b.class...
processing com/chartboost/sdk/h.class...
processing com/chartboost/sdk/h$1.class...
processing com/chartboost/sdk/h$2.class...
processing com/chartboost/sdk/h$3.class...
processing com/chartboost/sdk/h$a.class...
processing com/chartboost/sdk/h$b.class...
processing com/chartboost/sdk/h$c.class...
processing com/chartboost/sdk/impl/a.class...
processing com/chartboost/sdk/impl/aa.class...
processing com/chartboost/sdk/impl/ab.class...
processing com/chartboost/sdk/impl/ac.class...
processing com/chartboost/sdk/impl/ad.class...
processing com/chartboost/sdk/impl/ad$1.class...
processing com/chartboost/sdk/impl/ae.class...
processing com/chartboost/sdk/impl/ae$1.class...
processing com/chartboost/sdk/impl/ae$1$1.class...
processing com/chartboost/sdk/impl/ae$2.class...
processing com/chartboost/sdk/impl/ae$2$1.class...
processing com/chartboost/sdk/impl/ae$3.class...
processing com/chartboost/sdk/impl/af.class...
processing com/chartboost/sdk/impl/af$1.class...
processing com/chartboost/sdk/impl/ag.class...
processing com/chartboost/sdk/impl/ag$a.class...
processing com/chartboost/sdk/impl/ag$a$1.class...
processing com/chartboost/sdk/impl/ag$a$2.class...
processing com/chartboost/sdk/impl/ah.class...
processing com/chartboost/sdk/impl/ah$1.class...
processing com/chartboost/sdk/impl/ah$2.class...
processing com/chartboost/sdk/impl/ah$a.class...
processing com/chartboost/sdk/impl/ah$a$1.class...
processing com/chartboost/sdk/impl/ah$a$2.class...
processing com/chartboost/sdk/impl/ah$a$3.class...
processing com/chartboost/sdk/impl/ah$a$4.class...
processing com/chartboost/sdk/impl/ah$a$5.class...
processing com/chartboost/sdk/impl/ah$b.class...
processing com/chartboost/sdk/impl/ai.class...
processing com/chartboost/sdk/impl/aj.class...
processing com/chartboost/sdk/impl/ak.class...
processing com/chartboost/sdk/impl/ak$1.class...
processing com/chartboost/sdk/impl/al.class...
processing com/chartboost/sdk/impl/al$1.class...
processing com/chartboost/sdk/impl/al$2.class...
processing com/chartboost/sdk/impl/al$a.class...
processing com/chartboost/sdk/impl/am.class...
processing com/chartboost/sdk/impl/an.class...
processing com/chartboost/sdk/impl/an$1.class...
processing com/chartboost/sdk/impl/an$2.class...
processing com/chartboost/sdk/impl/an$3.class...
processing com/chartboost/sdk/impl/an$4.class...
processing com/chartboost/sdk/impl/an$5.class...
processing com/chartboost/sdk/impl/ao.class...
processing com/chartboost/sdk/impl/ap.class...
processing com/chartboost/sdk/impl/aq.class...
processing com/chartboost/sdk/impl/aq$1.class...
processing com/chartboost/sdk/impl/ar.class...
processing com/chartboost/sdk/impl/ar$1.class...
processing com/chartboost/sdk/impl/ar$2.class...
processing com/chartboost/sdk/impl/as.class...
processing com/chartboost/sdk/impl/as$1.class...
processing com/chartboost/sdk/impl/at.class...
processing com/chartboost/sdk/impl/au.class...
processing com/chartboost/sdk/impl/au$1.class...
processing com/chartboost/sdk/impl/av.class...
processing com/chartboost/sdk/impl/av$1.class...
processing com/chartboost/sdk/impl/av$a.class...
processing com/chartboost/sdk/impl/av$a$1.class...
processing com/chartboost/sdk/impl/av$a$a.class...
processing com/chartboost/sdk/impl/av$a$a$1.class...
processing com/chartboost/sdk/impl/av$b.class...
processing com/chartboost/sdk/impl/aw.class...
processing com/chartboost/sdk/impl/aw$1.class...
processing com/chartboost/sdk/impl/ax.class...
processing com/chartboost/sdk/impl/ax$a.class...
processing com/chartboost/sdk/impl/ax$b.class...
processing com/chartboost/sdk/impl/ay.class...
processing com/chartboost/sdk/impl/ay$a.class...
processing com/chartboost/sdk/impl/ay$b.class...
processing com/chartboost/sdk/impl/ay$c.class...
processing com/chartboost/sdk/impl/ay$d.class...
processing com/chartboost/sdk/impl/ay$e.class...
processing com/chartboost/sdk/impl/az.class...
processing com/chartboost/sdk/impl/az$1.class...
processing com/chartboost/sdk/impl/az$a.class...
processing com/chartboost/sdk/impl/az$b.class...
processing com/chartboost/sdk/impl/az$c.class...
processing com/chartboost/sdk/impl/az$d.class...
processing com/chartboost/sdk/impl/az$e.class...
processing com/chartboost/sdk/impl/az$e$a.class...
processing com/chartboost/sdk/impl/b.class...
processing com/chartboost/sdk/impl/b$a.class...
processing com/chartboost/sdk/impl/ba.class...
processing com/chartboost/sdk/impl/ba$1.class...
processing com/chartboost/sdk/impl/ba$1$1.class...
processing com/chartboost/sdk/impl/ba$a.class...
processing com/chartboost/sdk/impl/bb.class...
processing com/chartboost/sdk/impl/bb$a.class...
processing com/chartboost/sdk/impl/bb$a$1.class...
processing com/chartboost/sdk/impl/bb$a$2.class...
processing com/chartboost/sdk/impl/bb$a$3.class...
processing com/chartboost/sdk/impl/bb$b.class...
processing com/chartboost/sdk/impl/bb$c.class...
processing com/chartboost/sdk/impl/bc.class...
processing com/chartboost/sdk/impl/bc$1.class...
processing com/chartboost/sdk/impl/bc$a.class...
processing com/chartboost/sdk/impl/bd.class...
processing com/chartboost/sdk/impl/bd$1.class...
processing com/chartboost/sdk/impl/bd$2.class...
processing com/chartboost/sdk/impl/bd$3.class...
processing com/chartboost/sdk/impl/bd$4.class...
processing com/chartboost/sdk/impl/bd$5.class...
processing com/chartboost/sdk/impl/bd$6.class...
processing com/chartboost/sdk/impl/be.class...
processing com/chartboost/sdk/impl/be$1.class...
processing com/chartboost/sdk/impl/be$2.class...
processing com/chartboost/sdk/impl/be$3.class...
processing com/chartboost/sdk/impl/be$4.clas<message truncated>

**Comment by felipeefb** [comment]
There are duplicated classes on your game
try look for theses classes
`Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoJellyBeanMr2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatJellyBeanMr2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle$1;`

**Comment by ammarvohra** [comment]
Hello thank you for your comment...

Where could I search for this class??

**Comment by AaronDevGame** [comment]
We have the same error.
Are you using **Android SDK Build-tools v24** ?
Mine works fine after downgrading to **Android SDK Build-tools v23.0.3**
![screen shot 2016-07-06 at 8 11 32 pm](https://cloud.githubusercontent.com/assets/17031072/16617456/598da37a-43b6-11e6-92da-7ba81855fe0c.png)

Hope it works.

**Comment by ammarvohra** [comment]
Sorry I forget to post that I solved it myself... Just need to delete androidsupportv4 from pulgins and unchecking android from firebase-common...

Btw thank you all for helping... :)

**Comment by JamesMcMahon** [comment]
I am hitting this issue, with a slightly different stack trace involving duplicate Firebase classes.

@ammarvohra Can you expand upon you answer?

Are you referring to deleting `support-v4-23.4.0` from `Plugins/Android`?

And what do you mean by unchecking Android from firebase-commons?

**Comment by JamesMcMahon** [comment]
I think I figured it out, the command line to search across jars @ http://stackoverflow.com/a/1343026/20774 is super useful.

In my case I needed to delete an out of date `firebase-common-9.0.1` directory that the plugin failed to upgrade when the Google Play package was updated.

It seems like the core issue is that plugin doesn't properly clean up old dependencies post upgrade.
