### ISSUE TITLE
Social.localUser.Authenticate is always a call select Accounts.

### ISSUE THREAD

**Issue by SukO78** [playgameservices/play-games-plugin-for-unity#1249]
My code is 

public void LoginGPGS()
    {
        Social.localUser.Authenticate((bool success) => {
            if (success)
            {
                LoginSever();
            }
            else
            {
                Debug.LogWarning("Failed to sign in with Google Play Games.");
            }
        });
    }

Calling this function always comes out the account selection screen. Log out and then comes the Google game screen. However, simply re-run the app comes a Google account screen. Why is it always comes out the account selection screen. How do you handle when the app re-run after login.

**Comment by claywilkinson** [comment]
Does LoginServer try to get an access token?  Access tokens require the account to be selected.  The preferred method of communicating with a backend server is to call GetServerAuthCode() and pass that to the server.  The web app then exchanges that auth code for a token to call the games APIs.

**Comment by SukO78** [comment]
Thank you. reason is GooglePlayGames.PlayGamesPlatform.Instance.GetUserEmail(); this function.
GooglePlayGames.PlayGamesPlatform.Instance.GetUserEmail();  return value is My email. but,
(GooglePlayGames.PlayGamesPlatform)Social.localUser).GetUserEmail()); this function is return null.

**Comment by SukO78** [comment]
thank you. I used this function. GooglePlayGames.PlayGamesPlatform.Instance.GetServerAuthCode();
this function and member function of GooglePlayGames.PlayGamesPlatform (ex. getUserEmail()) is alwyas called google account window. Social.localUser.Authenticate -> google games account window, member of GooglePlayGames.PlayGamesPlatform -> google account window.. How do I solve this happens.

**Comment by SukO78** [comment]
void Start () {
        // Select the Google Play Games platform as our social platform implementation
        GooglePlayGames.PlayGamesPlatform.Activate();
    }

    void OnGUI() {
        GUI.skin.button.fontSize = (int)(FontSizeMult /2 * Screen.height);
        GUI.skin.label.fontSize = (int)(FontSizeMult / 2 * Screen.height);

        GUI.Label(new Rect(20, 20, Screen.width, Screen.height * 0.25f), mStatusText);

        Rect buttonRect         = new Rect(0.25f * Screen.width, 0.30f * Screen.height, 0.5f * Screen.width, 0.05f * Screen.height);
        Rect secondButtonRect   = new Rect(0.25f * Screen.width, 0.40f * Screen.height, 0.5f * Screen.width, 0.05f * Screen.height);

        Rect imageRect = new Rect(secondButtonRect.x + secondButtonRect.width / 4f,
                                  secondButtonRect.y + secondButtonRect.height * 1.1f,
                                  secondButtonRect.width / 2f, secondButtonRect.width / 2f);

        if (mWaitingForAuth)
        {
            return;
        }

        string buttonLabel;
        string secondButtonLabeL = "EXIT";

        if (Social.localUser.authenticated)
        {
            buttonLabel = "Sign Out";

            if(!isNext)
            {
                isNext = true;
                GetServerAuthCode();
            }

            if (Social.localUser.image != null)
            {
                GUI.DrawTexture(imageRect, Social.localUser.image,
                                ScaleMode.ScaleToFit);
            }
            else {
                GUI.Label(imageRect, "No image available");
            }
        }
        else {
            buttonLabel = "Authenticate";
        }

        if (GUI.Button(secondButtonRect, secondButtonLabeL))
        {
            isNext = false;
            Application.Quit();
        }

        if (GUI.Button(buttonRect, buttonLabel))
        {
            if (!Social.localUser.authenticated)
            {
                // Authenticate
                mWaitingForAuth = true;
                mStatusText = "Authenticating...";
                Social.localUser.Authenticate((bool success) =>
                {
                    mWaitingForAuth = false;
                    if (success)
                    {
                        mStatusText = "Welcome " + Social.localUser.userName;
                    }
                    else {
                        mStatusText = "Authentication failed.";
                    }
                });
            }
            else {
                // Sign out!
                mStatusText = "Signing out.";
                isNext      = false;
                ((GooglePlayGames.PlayGamesPlatform)Social.Active).SignOut();
            }
        }
    }

    private void GetServerAuthCode()
    {

        GooglePlayGames.PlayGamesPlatform.Instance.GetServerAuthCode((status, code) =>
        {
            callCount = 0;
            if (status == CommonStatusCodes.Success)
            {
                mStatusText = "Auth " + code;
                GetIDToken();
            }
            else
            {
                mStatusText = "Failed Auth";
            }
        });
    }

    private void GetIDToken()
    {
        GooglePlayGames.PlayGamesPlatform.Instance.GetIdToken((token) =>
        {
            callCount++;
            mStatusText = callCount.ToString() + " Token " + token ;
        });
    }

    private void GetEmail()
    {
        GooglePlayGames.PlayGamesPlatform.Instance.GetUserEmail((status, email) =>
        {
            if (status == CommonStatusCodes.Success)
            {
                mStatusText = "Email " + email;
            }
            else
            {
                mStatusText = "Failed Email";
            }
        });
    }

this is my all code. 

result :
 GooglePlayGames.PlayGamesPlatform.Instance.GetIdToken() and 
GooglePlayGames.PlayGamesPlatform.Instance.GetUserEmail() 

is google games login after called google account window.

and 

 GooglePlayGames.PlayGamesPlatform.Instance.GetIdToken()

is twice callback.

What is My problem of code?

**Comment by aqrel** [comment]
GooglePlayGames.PlayGamesPlatform.Instance.GetUserEmail() is the problem, if we use this method, android will request for account.

Some fix?

**Comment by aqrel** [comment]
I still have this problema, how do you solve it?

**Comment by aqrel** [comment]
Can you reopen t'he issue?

**Comment by RegalWzh** [comment]
I still have this problema，call you show your solution？

**Comment by RegalWzh** [comment]
I still have this problema，can you show your solution？
