### ISSUE TITLE
Exception "NEED_PERMISSION" on Android

### ISSUE THREAD

**Issue by MrAlt** [playgameservices/play-games-plugin-for-unity#125]
Cannot login on Android. (GooglePlayGamesPlugin-0.9.01)
Some exception "NEED_PERMISSION".

05-20 13:59:15.423: DEBUG/GameHelper(15109): GameHelper: onConnected: connected!
05-20 13:59:15.423: DEBUG/GameHelper(15109): GameHelper: succeedSignIn
05-20 13:59:15.423: DEBUG/GameHelper(15109): GameHelper: Notifying LISTENER of sign-in SUCCESS
05-20 13:59:15.423: INFO/Unity(15109): [Play Games Plugin DLL] GHM/GameHelperListener got onSignInSucceeded, origin 1000, notifying GHM.
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
05-20 13:59:15.423: INFO/Unity(15109): [Play Games Plugin DLL] GHM got onSignInSucceeded, origin 1000, notifying AndroidClient.
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
05-20 13:59:15.428: INFO/Unity(15109): [Play Games Plugin DLL] AndroidClient got OnSignInSucceeded.
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
05-20 13:59:15.428: INFO/Unity(15109): [Play Games Plugin DLL] Attempting to retrieve player info.
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
05-20 13:59:15.463: INFO/Unity(15109): [Play Games Plugin DLL] Player ID: 108805784592842815471
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
05-20 13:59:15.468: INFO/Unity(15109): [Play Games Plugin DLL] Player display name: Sergey Veraksich
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
05-20 13:59:15.468: INFO/Unity(15109): [Play Games Plugin DLL] AUTH: Auth succeeded. Proceeding to achievement loading.
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
05-20 13:59:15.473: INFO/Unity(15109): [Play Games Plugin DLL] AUTH: Now performing initial achievement load...
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
05-20 13:59:15.478: WARN/GLSUser(2454): GoogleAccountDataService.getToken()
05-20 13:59:15.528: INFO/Unity(15109): [Play Games Plugin DLL] AUTH: Initial achievement load call made.
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
05-20 13:59:15.538: INFO/AchievementAgent(21879): Sending achievement batch...
05-20 13:59:15.593: WARN/GLSUser(2454): GoogleAccountDataService.getToken()
05-20 13:59:15.688: DEBUG/dalvikvm(2454): GC_CONCURRENT freed 1331K, 19% free 13511K/16519K, paused 6ms+6ms, total 81ms
05-20 13:59:15.823: DEBUG/STATUSBAR-NetworkController(2253): refreshSignalCluster: data=0 bt=false
05-20 13:59:15.923: DEBUG/dalvikvm(2454): GC_FOR_ALLOC freed 269K, 19% free 13533K/16519K, paused 50ms, total 50ms
05-20 13:59:15.928: WARN/GLSActivity(2454): [apc] Status from wire: NeedPermission status: NEED_PERMISSION
05-20 13:59:15.953: ERROR/DataHolderOperation(21879): Auth error while performing operation, requesting reconnect
        ane: NeedPermission
        at amr.a(SourceFile:411)
        at bmx.b(SourceFile:91)
        at bmi.b(SourceFile:834)
        at dll.b(SourceFile:132)
        at bmi.b(SourceFile:451)
        at bmi.a(SourceFile:421)
        at bmi.a(SourceFile:400)
        at dll.a(SourceFile:146)
        at cuf.a(SourceFile:679)
        at cuf.a(SourceFile:640)
        at cuf.a(SourceFile:1058)
        at cuf.a(SourceFile:983)
        at cun.b(SourceFile:1472)
        at dsh.b(SourceFile:33)
        at dru.a(SourceFile:47)
        at com.google.android.gms.games.service.GamesIntentService.a(SourceFile:649)
        at beq.run(SourceFile:150)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)
05-20 13:59:15.983: DEBUG/dalvikvm(15109): GC_CONCURRENT freed 350K, 15% free 9645K/11335K, paused 2ms+2ms, total 28ms
05-20 13:59:16.003: INFO/Unity(15109): [Play Games Plugin DLL] OnAchievementsLoadedResultProxy invoked
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
05-20 13:59:16.003: INFO/Unity(15109): [Play Games Plugin DLL]     result=UnityEngine.AndroidJavaObject
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
05-20 13:59:16.023: INFO/Unity(15109): [Play Games Plugin DLL] AUTH: Initial achievement load finished.
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
05-20 13:59:16.028: WARN/Unity(15109): !!! [Play Games Plugin DLL]  WARNING: AUTH: Failed to load achievements, status code 2
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
05-20 13:59:16.028: INFO/Unity(15109): [Play Games Plugin DLL] AUTH: Calling auth callback: success=False
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
05-20 13:59:16.038: INFO/Unity(15109): -- GPS login:False
        (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)

**Comment by claywilkinson** [comment]
Hi everyone - I am closing this issue since it has been a while and the plugin has been re-architected so that the GameHelper code in the call stack is no longer used.  If you are still having this issue with the latest plugin, please re-open this issue.  Thanks!
