### ISSUE TITLE
how to use the Video Recording API??

### ISSUE THREAD

**Issue by reyzonk** [playgameservices/play-games-plugin-for-unity#1250]
Google Play Services v9.0 SDK Add Video Recording API

how to use unity?

https://developers.google.com/android/reference/com/google/android/gms/games/video/package-summary

**Comment by claywilkinson** [comment]
The video recording API is not part of the plugin yet.  It will be in the next update - stay tuned!

**Comment by SamMcfly** [comment]
Any Updates about that?
