### ISSUE TITLE
Invalid Clasname when I Set up Google Play Games Plugin

### ISSUE THREAD

**Issue by TTanto** [playgameservices/play-games-plugin-for-unity#1251]
Ok, so here is the problem: when i go to Window>GooglePlayGames>Setup , and in the Constants class name i put the correct stuff, this error jumps on https://gyazo.com/ac1bba4afe31e855e0d3d7bfb887c74b
btw there is no console error so i cant give you for information.
Please help!

**Comment by blookmaker** [comment]
hello , you should update your android sdk by opening sdk manager or by clicking in Unity Editor in the top bar menu on  : 
Window/GooglePlayGames/Downloads/GoogleplaygameSdk for android. and click ok ok .

when the android manager is opened , update the components that need to be updated .

**Comment by blookmaker** [comment]
i had a lot of problem to make it work but now i have another type of problem when i try to build the project , it is giving me Failed to repckage resources . 
I hope you will fix your problem :) good luck

**Comment by TTanto** [comment]
Thank you dude, now i cant try it because im not in home, hopefully is that
😉
El dia 22 juny 2016 12:31 p. m., "Abdellah" <notifications@github.com> va
escriure:

**Comment by blookmaker** [comment]
Hello @TTanto  , 
Note that by updating your android sdk , don't install the API 24 , howhever you will get the error i told you about earlier . if you already installed it then just go to :
android-sdk-windows\build-tools in your android sdk folder and then delete the folder 24 :D . 
i hope that you will not face the same problem as me :) .
Thank you and good luck again . 
if you are able to fix your issue don't forge to close it ...

**Comment by TTanto** [comment]
Yeah man i already solved that thank you
El dia 22 juny 2016 5:27 p. m., "Abdellah" <notifications@github.com> va
escriure:

**Comment by blookmaker** [comment]
Great to hear that :+1:
