### ISSUE TITLE
DataSource.ReadNetworkOnly not working correctly on Android

### ISSUE THREAD

**Issue by TuuttitaR** [playgameservices/play-games-plugin-for-unity#1254]
Hey,

I am capable of reading and writing saves without a network connection on Android even with the DataSource.ReadNetworkOnly property set on OpenWithAutomaticConflictResolution. On iOS, the property seems to be working properly.

**Comment by claywilkinson** [comment]
Thanks for the feedback.  I've passed this along to the SDK team.

**Comment by TuuttitaR** [comment]
Not experiencing this issue anymore, the newest Google Drive update seemed to have fixed the problem!
