### ISSUE TITLE
GooglePlayGames.PlayGamesPlatform.Instance.GetUserEmail() always call select account 

### ISSUE THREAD

**Issue by aqrel** [playgameservices/play-games-plugin-for-unity#1255]
With 0.9.34
Unity 5.3.4f1

When i try to get email (with callback and without callback)
Always apears an ui that ask me for account.

**Comment by felipeefb** [comment]
be more specific please, I think you are saying that appear an dialog with all google account's on your device.
what's the problem on that?

**Comment by aqrel** [comment]
yes, every time you call this function, a dialog will appear.
First time you start app, normal google play dialog appears for select account, and a second dialog will appear when you call getuseremail, Then, users must select two times their account. 
On 0.9.27 works without second dialog.
Maybe is new feature or security update.

**Comment by felipeefb** [comment]
It's different man, you didn't switch the logger account when the player select a diferent email from getEmail, note that it can be null. if you want the current email that's is signed in, its diferent.
from [https://github.com/playgameservices/play-games-plugin-for-unity](url) read this:
> Retrieving player's email or a unique identifier
>  order to access the player's email address, the plugin uses the account picker standard UI from   Android. This API presents an account picker to the player. The account the player selects does   not necessarily correspond to gamer account the user authenticated with. The user can also  select "Cancel" and not select any email. In this case, null is returned as the email address. Note:  This** also means the email address is not a reliable unique identifier.
 If all that is needed is a persistent unique identifier for the player, then you should use the player's id.  This is a unique ID specific to that player and is the same value all the time.

**Comment by aqrel** [comment]
Then i can't get email from current account? 

when i use this code ui from android appear too.

` Debug.Log("Local user's email is " +
        ((PlayGamesLocalUser)Social.localUser).Email);`

Thanks!

**Comment by felipeefb** [comment]
You can get email from current account.
But it's complicated, i'm trying solving this in this moment, first you need ask google plus permission then you must change the implementattion on nativeplugin.
When i finish it, i'll post it ok?

**Comment by aqrel** [comment]
Ok! thank you very much.

**Comment by felipeefb** [comment]
So, first you need "android.permission.GET_ACCOUNTS",if its on android SDk < 23 you don't need to worry, but if you're running on android skd > 23 you'll need ask these kind of dangerous permission during your game execution. try do something like  this post for that:  [android-m-run-time-permission](http://blog.trsquarelab.com/2015/11/android-m-run-time-permission-using.html)
  Then you will need to change the GetUserEmail() method from NativeClient , replace all code for only this: `return mTokenClient.GetEmail();`
this will ask the user the googlePlus profile permission, if the player agree, you will be able to get the email from  current logged account.
Ps: You have to call this at least one time before to get the user email, the first time it's only for ask this permission.
Ps2: If the player declines you only get an empty string, i did not discover a way to know if his accept or declines the permission request.
Ps3: This code asks the permission only one time per session, tobe able to ask again the user has to close and open again the game.
That's it, hope that I have helped `you.

**Comment by aqrel** [comment]
ok, Really thank you, i will try it this night.

**Comment by claywilkinson** [comment]
The email address is retrieved from the account list on the device, and is not directly associated with the identity that is authenticated with Play Game Services.  Doing it this way, there is no need for the permission, but rather select the account from the account list presented when requesting the email address.

As a side note, why do you need the email address?  Not all players have Google Plus accounts any more, so you can't rely on Plus API working at all.  If you just need a unique identifier for the player you can use the playerId property which is unique.
