### ISSUE TITLE
Player Statistics get stat stats.HasDaysSinceLastPlayed() alway return false?

### ISSUE THREAD

**Issue by minhit1805** [playgameservices/play-games-plugin-for-unity#1257]
After authenticating, i call this function but stats.HasDaysSinceLastPlayed() alway return false? what i was wrong here? someone can help me some idea to fix this? thanks
((PlayGamesLocalUser)Social.localUser).GetStats((rc, stats) =>
        {
            // -1 means cached stats, 0 is succeess
            // see  CommonStatusCodes for all values.
            if (rc <= 0 && stats.HasDaysSinceLastPlayed()) {
                Debug.Log("It has been " + stats.DaysSinceLastPlayed + " days");
            }
        });

**Comment by claywilkinson** [comment]
Is this still not returning a value, if not, can you share a log of getting the stats and reopen this issue?  Apparently the stats are updated in a batch, so they are not real time stats.
