### ISSUE TITLE
Authorization Error when signing to google play services 

### ISSUE THREAD

**Issue by itsharshdeep** [playgameservices/play-games-plugin-for-unity#1259]
Hi 

I have integrated google play services 0.9.34 into my project. an I am using unity version 5.3.3f1.

I followed the steps to sign in the product but even then it doesn't seems working.

In the device a window ask me to choose the login email ( from the list of mails id I have logged in), after that activity indicator start loading and after 1-2 second it disappear.

Following link contains the UN-filtered logs from android studio:
http://pastebin.com/WdruJpJx

Please help me out.

Thanks 
Harsh

**Comment by claywilkinson** [comment]
Please open a new issue including the log if you are still having a problem.
