### ISSUE TITLE
Admob Integration issue.

### ISSUE THREAD

**Issue by trueliveagain** [playgameservices/play-games-plugin-for-unity#126]
Hi, smart guy.
You really helped me very much.
I'm very thanks for your this plugin.
Additionally I'm very interesting to integrate Admob with PlayGameService.
When I'm developing on Eclips, it was easy to integrate Admob with PlayGameService library.
Maybe your excellent skill looks easy to generate this Admob plugin with your PlayGameService plugin.
Or if there are any good way you know and let me know kindly, I'll be very thanks again.

Not any opinion or complain about your excellent plugin, In other words, it was the perfect.

I'm only had a small sad with Admob.

Hope your kind reply.
My email address is trueliveagain@gmail.com.
If you visit my email address, I'll be very thanks.

Thank you.

**Comment by claywilkinson** [comment]
Closing this since it seems to be resolved.
