### ISSUE TITLE
Users can't login - Plugin shows: ERROR_INTERNAL

### ISSUE THREAD

**Issue by MobileMonsters** [playgameservices/play-games-plugin-for-unity#1267]
Hi, users of our game (Android/Google Play) that are connected to Google can't open the game anymore. It hangs on loading screen. Most frustrating part - we already lost a couple of thousand users due to this ...
We updated the games-plugin but still the same issue.

UnityLog:Warning, 
"message" : "*** [Play Games Plugin DLL] 06/30/16 14:04:55 +02:00 ERROR: Encountered unknown status: ERROR_INTERNAL"

1. What exactly is ERROR_INTERNAL in this relation? There is no hint anywhere.
2. Why does it freeze the login procedure of the game? Normally, when the Google saved game can't be retrieved it automatically loads the game from the device storage. But not since the last update. 

This issue is going on for two weeks now. We didn't change anything on our side, related to the sign in process. Worked fine before ...

**Comment by claywilkinson** [comment]
Can you share the log?

**Comment by MobileMonsters** [comment]
Hey Clay,

we don't have any log files since the error only appeared on devices of our users.

The only thing I can tell is that in NativeSavedGameClient.AsRequestStatus(Status.SnapshotOpenStatus status) in line 509 the switch-block reaches default and prints the "Encountered unknown status: ERROR_INTERNAL" message.

Is there any way I can get more information about the internal error? Or can I give you some other information you can work with, without being able to get a log-file?

**Comment by pvalium** [comment]
I'm receving this internal error from last 3-4 days too. When I try to open a savegame, I get always 'Encountered unknown status: ERROR_INTERNAL'. I deleted savegame in my drive, but it not solved the problem.

**Comment by pvalium** [comment]
Yesterday i tried to savegame with other account, and runned OK. Then, the problem may be with my main account. It seems to be blocked, but I deleted all data in drive and unlinked the app. I deleted data of my google play games app too, but always get the INTERNAL ERROR when plugin opened a savegame.

**Comment by pvalium** [comment]
Solved deleting data in app google play services

**Comment by MobileMonsters** [comment]
The problems are getting worse! 
We didn't change anything. It worked before. 
Since the update of the Play Games Plugin for Unity, more and more players can't login or save their game. Only log message is ERROR_INTERNAL.

This is ridiculous. Google always pushes to use their services, and then using their service/plugins kills the core user base. 
As the responsible product manager I must say, had I know this before, I would have never pushed to integrate with the GGS. My technicians always voted to build something independent, since they knew being dependent on the GGS plugin will leave us in the dark when something happens.
Now we have no clue what to do and no workaround. Last call would be to kick the cloud save and build something own in connection with the Google sign in.

**Comment by claywilkinson** [comment]
Apparently there was a problem during that time with Saved Games on the server.  The issue should be resolved now.  Please open a new issue if there are still problems.
