### ISSUE TITLE
Successfully signed in even when there is no internet connection.

### ISSUE THREAD

**Issue by Eclmist** [playgameservices/play-games-plugin-for-unity#1269]
Following the documentation, I called Social.localUser.Authenticate() to check if the player is authenticated. For some reason, this method sometimes return true even when there is not active internet connection. Was this intended? 

If this was indeed intended (and the method is checking against a cache of some sort), why is there no method to check if the player has an active connection to google's servers?

**Comment by claywilkinson** [comment]
This is expected.  If the player's identity has been cached on the device for that game, it is much faster (so a better experience) to sign-in locally and only hit the server when needed.  This also is more robust when the connection to the internet may be intermittent or slow.

Other than being surprised that it worked, did something unexpected happen?

**Comment by Eclmist** [comment]
That's good to know. However, is there no way to check if the player has an active connection to google's servers?

**Comment by claywilkinson** [comment]
No, there is no real way, especially if the user is mobile, the connection could be very intermittent or slow.  The play-services client handles the caching and batching of communication with the server so the users can be in these weird semi-connected states and the developer does not need to manage the state.
