### ISSUE TITLE
CommandInvocationFailure IlligalArgumentException

### ISSUE THREAD

**Issue by avvie** [playgameservices/play-games-plugin-for-unity#1271]
Had this problem before, but a google search fixxed it. I had used the solution where u hardcode the version number, since `android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />` wont work.

I get this on 2 files 
`
Error: [Temp\StagingArea\AndroidManifest-main.xml:22, D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\MainLibProj\AndroidManifest.xml:13] Trying to merge incompatible /manifest/application/meta-data[@name=com.google.android.gms.version] element:

UnityEditor.HostView:OnGUI()
`
and 

`
Error: [Temp\StagingArea\AndroidManifest-main.xml:22, D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\play-services-basement-9.2.0\AndroidManifest.xml:5] Trying to merge incompatible /manifest/application/meta-data[@name=com.google.android.gms.version] element:

UnityEditor.HostView:OnGUI()
`

and a commandInvokation error as well due to the conflict. 
I tried going to the same place i got the number last time, but it doesnt exist and no solution i could find on google helped. 
I am using this and the admob plugin for unity 

Thanks in advance

**Comment by avvie** [comment]
So i found the integer i needed to hardcode it and then i go this InvocationError:

`
Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
D:\Devv\Android\SDK\build-tools\24.0.0\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "D:/Devv/Android/SDK/platforms/android-24\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.google.example.games.mainlibproj:com.google.android.gms.ads.impl:com.google.android.gms.ads:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.clearcut:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms:com.google.android.gms.nearby:com.google.android.gms.tasks:android.support.v4 -S "D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res" -S "D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\play-services-ads-9.2.0\res" -S "D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\play-services-ads-lite-9.2.0\res" -S "D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\play-services-base-9.2.0\res" -S "D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\play-services-basement-9.2.0\res" -S "D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\play-services-clearcut-9.2.0\res" -S "D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\play-services-drive-9.2.0\res" -S "D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\play-services-games-9.2.0\res" -S "D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\play-services-gass-9.2.0\res" -S "D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\play-services-nearby-9.2.0\res" -S "D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\play-services-tasks-9.2.0\res" -S "D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\support-v4-23.1.1\res"

stderr[
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <android.support.v7.widget.ButtonBarLayout>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_button_bar_material.xml: note: using v17 attributes; synthesizing resource com.freakout.GoatExterm:layout/abc_alert_dialog_button_bar_material for configuration v17.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.widget.DialogTitle>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource com.freakout.GoatExterm:layout/abc_alert_dialog_material for configuration v17.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_dialog_title_material.xml: note: using v17 attributes; synthesizing resource com.freakout.GoatExterm:layout/abc_dialog_title_material for configuration v17.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.widget.ActionBarContainer>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource com.freakout.GoatExterm:layout/abc_screen_toolbar for configuration v21.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_search_view.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_search_view.xml: note: using v17 attributes; synthesizing resource com.freakout.GoatExterm:layout/abc_search_view for configuration v17.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml: note: using v17 attributes; synthesizing resource com.freakout.GoatExterm:layout/notification_template_big_media for configuration v17.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource com.freakout.GoatExterm:layout/notification_template_big_media_narrow for configuration v17.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:77: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:96: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:64: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml: note: using v17 attributes; synthesizing resource com.freakout.GoatExterm:layout/notification_template_lines for configuration v17.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml:43: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <include>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml:33: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml: note: using v17 attributes; synthesizing resource com.freakout.GoatExterm:layout/notification_template_media for configuration v17.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_chronometer.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <Chronometer>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_chronometer.xml: note: using v17 attributes; synthesizing resource com.freakout.GoatExterm:layout/notification_template_part_chronometer for configuration v17.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_time.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <DateTimeView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_time.xml: note: using v17 attributes; synthesizing resource com.freakout.GoatExterm:layout/notification_template_part_time for configuration v17.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:drawableStart from <CheckedTextView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml: note: using v13 attributes; synthesizing resource com.freakout.GoatExterm:layout/select_dialog_multichoice_material for configuration v13.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:drawableStart from <CheckedTextView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml: note: using v13 attributes; synthesizing resource com.freakout.GoatExterm:layout/select_dialog_singlechoice_material for configuration v13.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable\abc_textfield_search_material.xml:19: note: removing attribute http://schemas.android.com/apk/res/android:state_activated from <item>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable\abc_textfield_search_material.xml: note: using v11 attributes; synthesizing resource com.freakout.GoatExterm:drawable/abc_textfield_search_material for configuration v11.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml: note: using v17 attributes; synthesizing resource com.freakout.GoatExterm:layout/select_dialog_multichoice_material for configuration v17.
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
D:\Devv\Duck Hunt - Copy\Duck\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml: note: using v17 attributes; synthesizing resource com.freakout.GoatExterm:layout/select_dialog_singlechoice_material for configuration v17.
AndroidManifest.xml:20: error: Error: No resource found that matches the given name (at 'theme' with value '@style/UnityThemeSelector').

]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: D:\Devv\Android\SDK\platforms\android-24\android.jar
applyFileOverlay for drawable
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_icon_light.xml
trying overlaySet Key=common_google_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_google_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_light_pressed.9.png
trying overlaySet Key=common_ic_googleplayservices.png
trying overlaySet Key=common_plus_signin_btn_icon_dark.xml
trying overlaySet Key=common_plus_signin_btn_icon_dark_disabled.9.png

`

**Comment by avvie** [comment]
Fixed by removing the services jar :S still now it services work perfectly.

**Comment by claywilkinson** [comment]
Glad it is fixed.
