### ISSUE TITLE
Invalid Class Name - in setup

### ISSUE THREAD

**Issue by rossstyants** [playgameservices/play-games-plugin-for-unity#1274]
I'm getting this error on a totally fresh project (created new project un Unity 5.3.4 and then imported the package 0.9.34) when first switching from iOS to android...
(I have Google Play Services 31 installed - Android sdk is latest)

"Google.JarResolver.ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-games:9+
  at Google.JarResolver.PlayServicesSupport.DependOn (System.String group, System.String artifact, System.String version) [0x00000] in <filename unknown>:0 
  at GooglePlayGames.Editor.GPGSDependencies.RegisterDependencies () [0x00000] in /Users/administrator/Documents/Unity/RiverRun/Test GPGS/Assets/GooglePlayGames/Editor/GPGSDependencies.cs:57 
  at GooglePlayGames.Editor.GPGSDependencies..cctor () [0x00028] in /Users/administrator/Documents/Unity/RiverRun/Test GPGS/Assets/GooglePlayGames/Editor/GPGSDependencies.cs:49 
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])
"

and then when i try to do the Android Setup i get INVALID CLASS NAME....

any help much appreciated ...

**Comment by DanFlannel** [comment]
Using the newest version here, also running into this issue, doubled checked everything and even my JDK and SDK, I can build to my phone normally, I tried naming the class like Assets.GPGConst and simply GPGConst even made a class for it, named it GPGConst.cs, tried a slew of work arounds, no idea what's going on any advice would be helpful and thankyou for creating this thought, I've used it in the past but it seems this recent version has a bug here :(

**Comment by SMillard** [comment]
I got this problem too (Invalid Class Name) when I try to run setup... any ideas anyone?

**Comment by DanFlannel** [comment]
I had it but fixed it here's how. I opened up my sdk manager with android studio, make sure that's running btw. And installed all the packages however the package found under except API 24 unless you're using Unity 5.4 beta I found this out the hard way. So make sure you update your Android Studio sdks no idea which one it is but also don't install the Android version 24 ask only Unity Beta 5.4 supports that.

**Comment by SMillard** [comment]
I don't get it... did you install EVERYTHING in sdk manager? (except for android version 24)...

**Comment by DanFlannel** [comment]
No not everything but a lot, everything with the name google on it for sure.
Here is an image of my sdk manager

![alt text][logo1]
![alt text][logo2]
![alt text][logo3]

[logo1]: https://docs.google.com/uc?export=download&id=0B4fjzCPc3y-bYXdKOHpxMjFBWFk
[logo2]: https://docs.google.com/uc?export=download&id=0B4fjzCPc3y-bWE92aFFyMHV1dDQ
[logo3]: https://docs.google.com/uc?export=download&id=0B4fjzCPc3y-bODlaM0YtZnlPY1k

I hope that this helps

**Comment by SMillard** [comment]
thank you man, that solved my problem :)

**Comment by DanFlannel** [comment]
no problem

**Comment by sorab2142** [comment]
i actually upgraded the SDK to 24 and now it isn't working, any idea how to downgrade?

**Comment by DanFlannel** [comment]
I saw someone comment that they accidentally upgraded to SDK 24 So I'm just doing a post on how to downgrade:

![alt text][logo]

[logo]: https://docs.google.com/uc?export=download&id=0B4fjzCPc3y-bMTFOZkhCb2x3ajg "Built Tools"

Navigate to this folder, I have windows 10 so that for me is navigating to my appdata folder and if you cant find that search or %appdata% in the desktop search bar. Then simply delete the folder marked 24.0.0 and that will downgrade you

**Comment by claywilkinson** [comment]
From what I understand there is a problem with 24 on Windows, so downgrading is the right thing to do.  I believe the issue was fixed in 25, which should be out or soon will be.
