### ISSUE TITLE
sign in Not Authorized

### ISSUE THREAD

**Issue by avvie** [playgameservices/play-games-plugin-for-unity#1275]
Let me know if this is not the place for this question. 
I was trying to get firebase plugin to work. after linked everything properly (i think) suddenly I couldn't log in to play services. I meddled around for a bit and i ended up removing and unlinking firebase completely. 
I reverted my apk to the live one in production, that  until this morning was working perfectly fine, and i see this in the console 
`I/Unity   (27173):  [Play Games Plugin DLL] 07/10/16 13:24:25 +03:00 DEBUG: Play
GamesPlatform activated: GooglePlayGames.PlayGamesPlatform

I/Unity   (27173):
I/Unity   (27173): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDeb
ug.cpp Line: 56)
I/Unity   (27173):

I/Unity   (27173):  [Play Games Plugin DLL] 07/10/16 13:24:26 +03:00 DEBUG: Star
ting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   (27173

I/Unity   (27173): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDeb
ug.cpp Line: 56)
I/Unity   (27173):

I/Unity   (27173): Invoking callbacks, AuthState changed from silentPending to U
nauthenticated.
I/Unity   (27173

I/Unity   (27173): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDeb
ug.cpp Line: 56)
I/Unity   (27173

I/Unity   (27173): there are pending auth callbacks - starting AuthUI
I/Unity   (27173):

I/Unity   (27173): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDeb
ug.cpp Line: 56)
I/Unity   (27173

W/ActivityManager( 1960): mDVFSHelper.acquire()
I/Unity   (27173):  [Play Games Plugin DLL] 07/10/16 13:24:28 +03:00 DEBUG: Appl
ication is pausing, which disconnects the RTMP  client.  Leaving room.
I/Unity   (27173):

I/Unity   (27173): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDeb
ug.cpp Line: 56)
I/Unity   (27173):
W/ActivityManager( 1960): mDVFSHelper.release()
W/ActivityManager( 1960): mDVFSHelper.acquire()
W/ActivityManager( 1960): mDVFSHelper.release()
I/Unity   (27173):  [Play Games Plugin DLL] 07/10/16 13:24:43 +03:00 DEBUG: Star
ting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   (27173):

I/Unity   (27173): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDeb
ug.cpp Line: 56)
I/Unity   (27173):
I/Unity   (27173): AuthState == Unauthenticated calling auth callbacks with fail
ure
I/Unity   (27173):
I/Unity   (27173): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDeb
ug.cpp Line: 56)
I/Unity   (27173):
I/Unity   (27173):  [Play Games Plugin DLL] 07/10/16 13:24:43 +03:00 DEBUG: Invo
king user callback on game thread
I/Unity   (27173):
I/Unity   (27173): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDeb`

As far as i know everything on the dev console is exactly on the same state as it was when everything worked well.
I went to service&apis and removed the firebase link as well as from the firebase console. and resubmited the app. after it went live still wasnt working. Any clues?

**Comment by saurabhstudio13960** [comment]
Getting same error.. 

07-13 20:45:24.651  1358  1438 D Unity   :  GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_sync GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT

07-13 20:45:24.651  1358  1438 D Unity   : _texture_sRGB_decode GL_EXT_texture_filter_anisotropic GL_EXT_multisampled_render_to_texture GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_disjoint_timer_query

07-13 20:45:27.041  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:26 +05:30 DEBUG: Activating PlayGamesPlatform.

07-13 20:45:27.041  1358  1438 I Unity   :  

07-13 20:45:27.041  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:27.041  1358  1438 I Unity   : 

07-13 20:45:27.055  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:27 +05:30 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform

07-13 20:45:27.055  1358  1438 I Unity   :  

07-13 20:45:27.055  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:27.055  1358  1438 I Unity   : 

07-13 20:45:32.022  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:32 +05:30 DEBUG: Creating platform-specific Play Games client.

07-13 20:45:32.022  1358  1438 I Unity   :  

07-13 20:45:32.022  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:32.022  1358  1438 I Unity   : 

07-13 20:45:32.024  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:32 +05:30 DEBUG: Creating Android IPlayGamesClient Client

07-13 20:45:32.024  1358  1438 I Unity   :  

07-13 20:45:32.024  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:32.024  1358  1438 I Unity   : 

07-13 20:45:32.289  1358  1438 I Unity   : Building GPG services, implicitly attempts silent auth

07-13 20:45:32.289  1358  1438 I Unity   :  

07-13 20:45:32.289  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:32.289  1358  1438 I Unity   : 

07-13 20:45:35.573  1358  2070 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:35 +05:30 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED

07-13 20:45:35.573  1358  2070 I Unity   :  

07-13 20:45:35.573  1358  2070 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:35.573  1358  2070 I Unity   : 

07-13 20:45:35.573  1358  2070 I Unity   : Invoking callbacks, AuthState changed from silentPending to Unauthenticated.

07-13 20:45:35.573  1358  2070 I Unity   :  

07-13 20:45:35.573  1358  2070 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:35.573  1358  2070 I Unity   : 

07-13 20:45:35.575  1358  2070 I Unity   : there are pending auth callbacks - starting AuthUI

07-13 20:45:35.575  1358  2070 I Unity   :  

07-13 20:45:35.575  1358  2070 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:35.575  1358  2070 I Unity   : 

07-13 20:45:36.957  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:36 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

07-13 20:45:36.957  1358  1438 I Unity   :  

07-13 20:45:36.957  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:36.957  1358  1438 I Unity   : 

07-13 20:45:51.107  1358  2070 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:51 +05:30 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED

07-13 20:45:51.107  1358  2070 I Unity   :  

07-13 20:45:51.107  1358  2070 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:51.107  1358  2070 I Unity   : 

07-13 20:45:51.111  1358  2070 I Unity   : AuthState == Unauthenticated calling auth callbacks with failure

07-13 20:45:51.111  1358  2070 I Unity   :  

07-13 20:45:51.111  1358  2070 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:51.111  1358  2070 I Unity   : 

07-13 20:45:51.137  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:51 +05:30 DEBUG: Invoking user callback on game thread

07-13 20:45:51.137  1358  1438 I Unity   :  

07-13 20:45:51.137  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:51.137  1358  1438 I Unity   : 

07-13 20:45:51.138  1358  1438 I Unity   : Auth failed!!

07-13 20:45:51.138  1358  1438 I Unity   :  

07-13 20:45:51.138  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:51.138  1358  1438 I Unity   : 

07-13 20:46:15.581  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:46:15 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

07-13 20:46:15.581  1358  1438 I Unity   :  

07-13 20:46:15.581  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:46:15.581  1358  1438 I Unity   : 

07-13 20:46:20.922  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:46:20 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

07-13 20:46:20.922  1358  1438 I Unity   :  

07-13 20:46:20.922  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:46:20.922  1358  1438 I Unity   : 

07-13 21:03:27.020  7734  7788 D Unity   :  GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_sync GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT

07-13 21:03:27.020  7734  7788 D Unity   : _texture_sRGB_decode GL_EXT_texture_filter_anisotropic GL_EXT_multisampled_render_to_texture GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_disjoint_timer_query

07-13 21:03:29.401  7734  7788 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:29 +05:30 DEBUG: Activating PlayGamesPlatform.

07-13 21:03:29.401  7734  7788 I Unity   :  

07-13 21:03:29.401  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:29.401  7734  7788 I Unity   : 

07-13 21:03:29.405  7734  7788 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:29 +05:30 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform

07-13 21:03:29.405  7734  7788 I Unity   :  

07-13 21:03:29.405  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:29.405  7734  7788 I Unity   : 

07-13 21:03:33.067  7734  7788 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:33 +05:30 DEBUG: Creating platform-specific Play Games client.

07-13 21:03:33.067  7734  7788 I Unity   :  

07-13 21:03:33.067  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:33.067  7734  7788 I Unity   : 

07-13 21:03:33.069  7734  7788 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:33 +05:30 DEBUG: Creating Android IPlayGamesClient Client

07-13 21:03:33.069  7734  7788 I Unity   :  

07-13 21:03:33.069  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:33.069  7734  7788 I Unity   : 

07-13 21:03:33.363  7734  7788 I Unity   : Building GPG services, implicitly attempts silent auth

07-13 21:03:33.363  7734  7788 I Unity   :  

07-13 21:03:33.363  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:33.363  7734  7788 I Unity   : 

07-13 21:03:36.343  7734  8273 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:36 +05:30 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED

07-13 21:03:36.343  7734  8273 I Unity   :  

07-13 21:03:36.343  7734  8273 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:36.343  7734  8273 I Unity   : 

07-13 21:03:36.343  7734  8273 I Unity   : Invoking callbacks, AuthState changed from silentPending to Unauthenticated.

07-13 21:03:36.343  7734  8273 I Unity   :  

07-13 21:03:36.343  7734  8273 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:36.343  7734  8273 I Unity   : 

07-13 21:03:36.350  7734  8273 I Unity   : there are pending auth callbacks - starting AuthUI

07-13 21:03:36.350  7734  8273 I Unity   :  

07-13 21:03:36.350  7734  8273 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:36.350  7734  8273 I Unity   : 

07-13 21:03:37.230  7734  7788 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:37 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

07-13 21:03:37.230  7734  7788 I Unity   :  

07-13 21:03:37.230  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:37.230  7734  7788 I Unity   : 

07-13 21:03:52.113  7734  8273 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:52 +05:30 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED

07-13 21:03:52.113  7734  8273 I Unity   :  

07-13 21:03:52.113  7734  8273 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:52.113  7734  8273 I Unity   : 

07-13 21:03:52.118  7734  8273 I Unity   : AuthState == Unauthenticated calling auth callbacks with failure

07-13 21:03:52.118  7734  8273 I Unity   :  

07-13 21:03:52.118  7734  8273 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:52.118  7734  8273 I Unity   : 

07-13 21:03:52.139  7734  7788 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:52 +05:30 DEBUG: Invoking user callback on game thread

07-13 21:03:52.139  7734  7788 I Unity   :  

07-13 21:03:52.139  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:52.139  7734  7788 I Unity   : 

07-13 21:03:52.140  7734  7788 I Unity   : Auth failed!!

07-13 21:03:52.140  7734  7788 I Unity   :  

07-13 21:03:52.140  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:52.140  7734  7788 I Unity   : 

07-13 21:03:56.921  7734  7788 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:56 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

07-13 21:03:56.921  7734  7788 I Unity   :  

07-13 21:03:56.921  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:56.921  7734  7788 I Unity   :

**Comment by claywilkinson** [comment]
Which Firebase plugin are your referring to?

I would double check the configuration of the linked android application on the Play Games Developer Console.  Especially the package name and the SHA1 fingerprint.  Maybe when you configured the Firebase application something changed (like the keystore you sign the app with?).

Also, just to make the list complete, the player needs to be listed as a tester in the game configuration (but it sounds like you had previously handled that OK).

**Comment by saurabhstudio13960** [comment]
i got sloved

**Comment by avvie** [comment]
I used this plugin https://github.com/firebase/Firebase-Unity
The keychain never chainged, nothing changed in the dev console and the package name was correct. 
In the end the only way to make it work was unpublishing the game, creating new key and reuping a new app, with the obvious consequences. But i thought its better to have a working product than a unsuable one. Since the live version broke as well, despite the fact that i was only working from my device.
The game is practically dead now, good thing it was portfolio work
