### ISSUE TITLE
PlayGamesPlatform.Instance.GetIdToken(callback) fires callback twice

### ISSUE THREAD

**Issue by hirenkacha** [playgameservices/play-games-plugin-for-unity#1278]
When I request for accesstoken by 

`PlayGamesPlatform.Instance.GetIdToken(callback);`

 the callback is fired twice.

First one gives IdToken valid, but second callback is sending null string. Which causes failing auth on our server.

![login](https://cloud.githubusercontent.com/assets/5537230/16796501/b871ffb8-4900-11e6-91b6-25e93cb03454.JPG)

Also, every time IdToken is requested, it asks to choose an account.

![permission](https://cloud.githubusercontent.com/assets/5537230/16796493/aa443a78-4900-11e6-8ae7-18c860dae37c.jpg)

**Comment by claywilkinson** [comment]
The account chooser is needed to provide an ID token.  You should really not be using this IDToken API, but rather get call FetchServerAuthCode and then exchange the auth code on your backend server for an ID token.  The Games API is moving away from requiring a Google Plus account, meaning players can play a game without disclosing their email account which is a lot nicer.  The id token API requires the email address of the user, so it is selected each time the token is requested (don't ask for a token :) ).  Also be aware that there is no requirement for the user to select the same account each time (if there is multiple accounts on the device), so it is not guaranteed to be consistent for a player.  If all you need is a unique ID for the player, you can safely use player.playerId.

**Comment by oosoosoo** [comment]
i looked into this issue and found code mistakes in AndroidTokenClient.cs 

line 306
` 
                    Fetch(idTokenScope, false, false, true, (status) =>
                    {
                        fetchingIdToken = false;

                        if (status == CommonStatusCodes.Success)
                        {
                            idTokenCb(null);  //Success inputs null ?
                        }
                        else
                        {
                            idTokenCb(idToken);
                        }
                    });
`

line 145
`
                        if (fetchIdToken && !string.IsNullOrEmpty(id))
                        {
                            idToken = id;
                            idTokenCb(idToken);  //Call a callback here first time.
                        }
                        if (fetchEmail && !string.IsNullOrEmpty(email))
                        {
                            this.accountName = email;
                        }
                        doneCallback(CommonStatusCodes.Success);  //Call a callback here second time.
`

**Comment by mholub** [comment]
Confirm, I has the same behaviour. First time - success and non-null idtoken and just after that callback with null token. I did workaround in my state machine for this case, but it would be nice to fix this.

You even has the code above describing the issue

**Comment by claywilkinson** [comment]
The id token support has been fixed in 0.9.38a.
