### ISSUE TITLE
sign in Not Authorized 

### ISSUE THREAD

**Issue by saurabhstudio13960** [playgameservices/play-games-plugin-for-unity#1279]
Getting error at signIn

07-13 20:45:27.041  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:26 +05:30 DEBUG: Activating PlayGamesPlatform.

07-13 20:45:27.041  1358  1438 I Unity   :  

07-13 20:45:27.041  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:27.041  1358  1438 I Unity   : 

07-13 20:45:27.055  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:27 +05:30 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform

07-13 20:45:27.055  1358  1438 I Unity   :  

07-13 20:45:27.055  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:27.055  1358  1438 I Unity   : 

07-13 20:45:32.022  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:32 +05:30 DEBUG: Creating platform-specific Play Games client.

07-13 20:45:32.022  1358  1438 I Unity   :  

07-13 20:45:32.022  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:32.022  1358  1438 I Unity   : 

07-13 20:45:32.024  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:32 +05:30 DEBUG: Creating Android IPlayGamesClient Client

07-13 20:45:32.024  1358  1438 I Unity   :  

07-13 20:45:32.024  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:32.024  1358  1438 I Unity   : 

07-13 20:45:32.289  1358  1438 I Unity   : Building GPG services, implicitly attempts silent auth

07-13 20:45:32.289  1358  1438 I Unity   :  

07-13 20:45:32.289  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:32.289  1358  1438 I Unity   : 

07-13 20:45:35.573  1358  2070 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:35 +05:30 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED

07-13 20:45:35.573  1358  2070 I Unity   :  

07-13 20:45:35.573  1358  2070 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:35.573  1358  2070 I Unity   : 

07-13 20:45:35.573  1358  2070 I Unity   : Invoking callbacks, AuthState changed from silentPending to Unauthenticated.

07-13 20:45:35.573  1358  2070 I Unity   :  

07-13 20:45:35.573  1358  2070 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:35.573  1358  2070 I Unity   : 

07-13 20:45:35.575  1358  2070 I Unity   : there are pending auth callbacks - starting AuthUI

07-13 20:45:35.575  1358  2070 I Unity   :  

07-13 20:45:35.575  1358  2070 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:35.575  1358  2070 I Unity   : 

07-13 20:45:36.957  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:36 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

07-13 20:45:36.957  1358  1438 I Unity   :  

07-13 20:45:36.957  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:36.957  1358  1438 I Unity   : 

07-13 20:45:51.107  1358  2070 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:51 +05:30 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED

07-13 20:45:51.107  1358  2070 I Unity   :  

07-13 20:45:51.107  1358  2070 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:51.107  1358  2070 I Unity   : 

07-13 20:45:51.111  1358  2070 I Unity   : AuthState == Unauthenticated calling auth callbacks with failure

07-13 20:45:51.111  1358  2070 I Unity   :  

07-13 20:45:51.111  1358  2070 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:51.111  1358  2070 I Unity   : 

07-13 20:45:51.137  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:45:51 +05:30 DEBUG: Invoking user callback on game thread

07-13 20:45:51.137  1358  1438 I Unity   :  

07-13 20:45:51.137  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:51.137  1358  1438 I Unity   : 

07-13 20:45:51.138  1358  1438 I Unity   : Auth failed!!

07-13 20:45:51.138  1358  1438 I Unity   :  

07-13 20:45:51.138  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:45:51.138  1358  1438 I Unity   : 

07-13 20:46:15.581  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:46:15 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

07-13 20:46:15.581  1358  1438 I Unity   :  

07-13 20:46:15.581  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:46:15.581  1358  1438 I Unity   : 

07-13 20:46:20.922  1358  1438 I Unity   :  [Play Games Plugin DLL] 07/13/16 20:46:20 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

07-13 20:46:20.922  1358  1438 I Unity   :  

07-13 20:46:20.922  1358  1438 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 20:46:20.922  1358  1438 I Unity   : 

07-13 21:03:29.401  7734  7788 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:29 +05:30 DEBUG: Activating PlayGamesPlatform.

07-13 21:03:29.401  7734  7788 I Unity   :  

07-13 21:03:29.401  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:29.401  7734  7788 I Unity   : 

07-13 21:03:29.405  7734  7788 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:29 +05:30 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform

07-13 21:03:29.405  7734  7788 I Unity   :  

07-13 21:03:29.405  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:29.405  7734  7788 I Unity   : 

07-13 21:03:33.067  7734  7788 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:33 +05:30 DEBUG: Creating platform-specific Play Games client.

07-13 21:03:33.067  7734  7788 I Unity   :  

07-13 21:03:33.067  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:33.067  7734  7788 I Unity   : 

07-13 21:03:33.069  7734  7788 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:33 +05:30 DEBUG: Creating Android IPlayGamesClient Client

07-13 21:03:33.069  7734  7788 I Unity   :  

07-13 21:03:33.069  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:33.069  7734  7788 I Unity   : 

07-13 21:03:33.363  7734  7788 I Unity   : Building GPG services, implicitly attempts silent auth

07-13 21:03:33.363  7734  7788 I Unity   :  

07-13 21:03:33.363  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:33.363  7734  7788 I Unity   : 

07-13 21:03:36.343  7734  8273 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:36 +05:30 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED

07-13 21:03:36.343  7734  8273 I Unity   :  

07-13 21:03:36.343  7734  8273 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:36.343  7734  8273 I Unity   : 

07-13 21:03:36.343  7734  8273 I Unity   : Invoking callbacks, AuthState changed from silentPending to Unauthenticated.

07-13 21:03:36.343  7734  8273 I Unity   :  

07-13 21:03:36.343  7734  8273 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:36.343  7734  8273 I Unity   : 

07-13 21:03:36.350  7734  8273 I Unity   : there are pending auth callbacks - starting AuthUI

07-13 21:03:36.350  7734  8273 I Unity   :  

07-13 21:03:36.350  7734  8273 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:36.350  7734  8273 I Unity   : 

07-13 21:03:37.230  7734  7788 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:37 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

07-13 21:03:37.230  7734  7788 I Unity   :  

07-13 21:03:37.230  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:37.230  7734  7788 I Unity   : 

07-13 21:03:52.113  7734  8273 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:52 +05:30 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED

07-13 21:03:52.113  7734  8273 I Unity   :  

07-13 21:03:52.113  7734  8273 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:52.113  7734  8273 I Unity   : 

07-13 21:03:52.118  7734  8273 I Unity   : AuthState == Unauthenticated calling auth callbacks with failure

07-13 21:03:52.118  7734  8273 I Unity   :  

07-13 21:03:52.118  7734  8273 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:52.118  7734  8273 I Unity   : 

07-13 21:03:52.139  7734  7788 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:52 +05:30 DEBUG: Invoking user callback on game thread

07-13 21:03:52.139  7734  7788 I Unity   :  

07-13 21:03:52.139  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:52.139  7734  7788 I Unity   : 

07-13 21:03:52.140  7734  7788 I Unity   : Auth failed!!

07-13 21:03:52.140  7734  7788 I Unity   :  

07-13 21:03:52.140  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:52.140  7734  7788 I Unity   : 

07-13 21:03:56.921  7734  7788 I Unity   :  [Play Games Plugin DLL] 07/13/16 21:03:56 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

07-13 21:03:56.921  7734  7788 I Unity   :  

07-13 21:03:56.921  7734  7788 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

07-13 21:03:56.921  7734  7788 I Unity   :

**Comment by StormSabotage** [comment]
Hey, it can be mistake at configuration or account you use not in testers list. but if all is well-configured, one possible thing that you should try and it could help - if your auth code is in static method, move it to instance method, try to not call plugin code from statics

**Comment by saurabhstudio13960** [comment]
I think it may be a mistake at configuration in google play developer console . I will check by making a new app and test it again. thanks

**Comment by saurabhstudio13960** [comment]
yes solved. by making new game in google play developer console. Thanks
