### ISSUE TITLE
ERROR_INTERNAL on realtime

### ISSUE THREAD

**Issue by bakman23** [playgameservices/play-games-plugin-for-unity#1283]
Hello,
When to player join room for a match one of both get ERROR_INTERNAL when they send messag but they are already in same room.
Do you know what can I do?

**Comment by claywilkinson** [comment]
Can you share the log?

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
