### ISSUE TITLE
GetIdToken call shows up with "UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment"

### ISSUE THREAD

**Issue by Rainking80** [playgameservices/play-games-plugin-for-unity#1285]
Hi, is there still a possibility to get the idToken? I see an error (`UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment`) when I call it. 
I understand that the Server Auth Code would be better, but unfortunately for the (AWS) amazon cloud I need the idtoken to authenticate against their Cognito Service. The Server auth code seems not to work at AWS - anyway the server auth code works fine with my code - I have just issues with the idToken. Another point I see in the AWS documentation: the use not the Callback function in GetIdToken, so it seems a bit outdated, what do you think?  (here is a link to AWS doc: [https://docs.aws.amazon.com/cognito/latest/developerguide/google.html#set-up-google-1.unity](https://docs.aws.amazon.com/cognito/latest/developerguide/google.html#set-up-google-1.unity) 

my code snippet: 
`
//run on ui thread
GooglePlayGames.OurUtils.PlayGamesHelperObject.RunOnGameThread( () => {
	
	PlayGamesPlatform.Instance.GetServerAuthCode((CommonStatusCodes status, string code) =>
	{                            
		Debug.Log("Status: " + status.ToString());
		Debug.Log("Code: " + code);
		credentials.AddLogin("accounts.google.com", code);
		authCode = code;
	});

	PlayGamesPlatform.Instance.GetIdToken((string token) => {
		credentials.AddLogin("accounts.google.com", token);
		Debug.Log("Logged in to AWS " + token);
	});

});`

Kind regards, Tino

**Comment by Rainking80** [comment]
Additional Info: I went back to play services version 8.4.0, before I had 9.0.2. Now it is working again. Is there a known issue with the newer play services? Since we should keep play services up to date it would be perfect to hear something about it. I'll also open a ticket at AWS for using serverauthcode instead.
Kind regards.

**Comment by claywilkinson** [comment]
The ID token will not work for all players.  Play Game Services is moving away from requiring a Google Plus account, so you really should use FetchServerAuthCode and exchange that for a token on your backend web app.

**Comment by Rainking80** [comment]
Unfortunately it is not my backend or my choice. Amazon Webservices authenticate with idToken. So if I want to allow google login I am forced to use the token... It seems best practice would be now to make an extra backend service. Just for the ServerAuthCode exchange to the JWT which then will be sent to AWS service. Why easy when i can have ich complicated ;)
