### ISSUE TITLE
Authentication window is not displayed

### ISSUE THREAD

**Issue by AlcantaraRW** [playgameservices/play-games-plugin-for-unity#1289]
I got a problem here. I call the Activate and the Authenticate methods but not even the Google Play Games window is dispayed. I tested it some days ago and the window was showing (not authenticating anyway, but at least the window was displayed).
Anyone here ever faced the same problem? Can someone help me?
Here's some information it must be needed:
- I've already configured Google Play Services in Unity (constant class name, resources, ...);
- My account is added as a tester in Google Play Developer Console;

**Comment by claywilkinson** [comment]
Can you add a log of the problem?  Is the Authenticate callback called? does it indicate success or failure?

**Comment by mostdeep123** [comment]
maybe there something wrong with your customization, check your resources on GPSGId.cs or check Package APP Id and Id Number that you get in Google Developer Console, also you can try to remove .aar file below appcompat and reconfigure with .aar version10.0.2, i hope this wil solve your problem

**Comment by claywilkinson** [comment]
Please open a new issue include the relevant log file if you are still having an issue.
