### ISSUE TITLE
'PlayGamesPlatform' doesn't exist in new Unity version

### ISSUE THREAD

**Issue by EspectroDK** [playgameservices/play-games-plugin-for-unity#1291]
Hi

I just updated Unity to version 5.3.5p7 and the Playgamesplugin doesn't work anymore. For some reason it doesn't recognise the static class and I get:
"The name 'PlayGamesPlatform' does not exist in the current context" everytime I try to use "PlayGamesPlatform.xxx".

I tried reimporting all but with no luck.

Any help appreciated. 
BR
Michael

**Comment by EspectroDK** [comment]
Ok, something is fishy  Unity doesn't recognise that I have the package imported correctly. For some reason I don't have the Window > Google Play Games  menu-item anymore. Even if I delete and import the package once again.

Any thoughts?

**Comment by JesseDotEXE** [comment]
I'm getting the same issue. Haven't found a way to fix it yet.

**Comment by EspectroDK** [comment]
Hi Jesse
I fixed it. After updating, I had to open Build Settings and select Android
as it haf reverted to Webplayer. Hopefully this also helps you.
BR
Michael

Den 25/07/2016 23.37 skrev "Jesse Villagomez" <notifications@github.com>:

**Comment by JesseDotEXE** [comment]
Yep that was the problem. @EspectroDK thanks for the help!

**Comment by claywilkinson** [comment]
Glad you got it resolved!
