### ISSUE TITLE
unable to retrieve application xxxxxxxxxxxx from network

### ISSUE THREAD

**Issue by anil40** [playgameservices/play-games-plugin-for-unity#1292]
Trying to use google play services v- 0.9.34 on unity 5.3 but when I try to sign In google play pop up open and then stop.

Error in log cat :- "Unable to retrieve application xxxxxxxxxxxx from network. Application ID xxxxxxxxxxxx is not associated with package com.company.game. Check the application ID in your manifest."

I already spent a lot time to get any solution, but I didn't found any solution. Any type of help really appreciate

Already checked these:
1. https://github.com/playgameservices/play-games-plugin-for-unity/issues/216
2. [Google Play Game Services - unable to sign in](http://stackoverflow.com/questions/16580885/google-play-game-services-unable-to-sign-in)
3. [Google Play Games login fails](http://stackoverflow.com/questions/16591808/google-play-games-login-fails)

`public class FruitLevelSelect : MonoBehaviour {

private string leaderbord = "xxxxxxxxxxxxxxxxx"; 

void Start()
{
    PlayGamesPlatform.DebugLogEnabled = true;
    GooglePlayGames.PlayGamesPlatform.Activate(); 

```
Social.localUser.Authenticate((bool success) => {
    // handle success or failure
});
```

}

public void Share()
{ 
    if (Social.localUser.authenticated)
    {
        ((PlayGamesPlatform)Social.Active).ShowLeaderboardUI(leaderbord);
    }
    else {
        Social.localUser.Authenticate((bool success) => {
            if (success)
            {
                ((PlayGamesPlatform)Social.Active).ShowLeaderboardUI(leaderbord);
            }
        });
    }
}`

**Comment by claywilkinson** [comment]
This message usually appears when you need to (re-)run setup for the plugin at Window > Google Play Games > Setup > Android Setup...
