### ISSUE TITLE
How to get id_token or user id on server from auth code?

### ISSUE THREAD

**Issue by paulsalameh** [playgameservices/play-games-plugin-for-unity#1293]
Hello,

I'm not able to exchange the client's Auth Code with a id_token or user id on the server:
1. After a successful PlayGamesPlatform.Instance.Authenticate() I call PlayGamesPlatform.Instance.GetServerAuthCode() and send the [AUTH_CODE] to the server.
2. On the server I do a HTTP POST to https://www.googleapis.com/oauth2/v4/token?code=[AUTH_CODE] 
   (other params include client_id, client_secret, redirect_uri and grant_type=authorization_code)
   I receive a json: {"access_token": [ACCESS_TOKEN], "expires_in": 3532, "token_type": "Bearer"}. Note that it's missing an id_token.
3. To see what valid scopes I have for this ACCESS_TOKEN, I do a HTTP GET to https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=[ACCESS_TOKEN]
   I receive a json: {"scope": "https://www.googleapis.com/auth/games_lite", "access_type": "offline", "expires_in": 3567, "issued_to": "123-abc.apps.googleusercontent.com", "audience": "123-abc.apps.googleusercontent.com"}.

It seems here that only the "https://www.googleapis.com/auth/games_lite" scope is being asked by the Unity plugin, and _maybe_ this is why no id_token is returned in step 2 above, and no user_id in step 3.

There is a way to tell the Unity plugin to include more scopes by adding this in NativeClient.cs (line 198):
`builder.AddOauthScope("profile");`
After adding this scope (or any other scope), step 2 would also return an id_token and step 3 would also return the user_id.

So how do I get the id_token or user_id on the server without tweaking NativeClient.cs and adding an unwanted scope? All I want is to uniquely identify the google user on my server. I can't trust PlayGamesPlatform's GetUserId() because it's from the client.

Thanks

**Comment by steven-supersolid** [comment]
I just saw this. Strangely I was able to get an id_token without doing this but not consistently. I had previously and unsuccessfully been calling getIdToken in the client but perhaps that set the scope for subsequent calls?
Will try out your PR tomorrow.

**Comment by paulsalameh** [comment]
getIdToken() is obsolete anyway so it mustn't be used as a workaround. Please do tell if you have more info on this.

**Comment by steven-supersolid** [comment]
Ticking `Enable Google Plus API Access` in the Editor settings window allowed us to get an id_token for an account that was previously not working. I didn't look any further yet but suspect this is modifying the scope to one that includes id_token.

**Comment by paulsalameh** [comment]
OK I can confirm that ticking `Enable Google Plus API Access` adds the following scopes:
https://www.googleapis.com/auth/games 
https://www.googleapis.com/auth/plus.me 
https://www.googleapis.com/auth/userinfo.profile 
https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.profile.language.read https://www.googleapis.com/auth/plus.moments.write https://www.googleapis.com/auth/plus.profile.agerange.read https://www.googleapis.com/auth/plus.circles.members.read

These are WAY too many unnecessary scopes. Also, a consent dialog will show to the user with things like accessing people in circles, profile info, and others. This would likely scare the user.

Using my commits above, you can selectively add the "email" or "profile" scopes to PlayGamesClientConfig that would result in minimal lines in the consent dialog presented to the user, AND enable you to get an id_token from the auth code (on server).

**Comment by Rainking80** [comment]
I have the same problem and opened a question on stackoverflow: [http://stackoverflow.com/questions/38904389/unity-android-serverauthcode-has-no-idtoken-on-backend/38905592#38905592](url). Seems to be the same issue to me. How can I build an own Unity package from your source (GooglePlayGamesPlugin-0.9.34.unitypackage) together with your changes/commits? Unfortunately I never built one... can you please give me a link or something where I can learn to build it on my own? I am missing the idtoken since some days and my investigations brought me here...

**Comment by paulsalameh** [comment]
Sure. After you import the unitypackage, download NativeClient.cs and PlayGamesClientConfig.cs from my commits (#1295 & #1296), and replace them in the correct locations.

**Comment by Rainking80** [comment]
Ah, so easy. Thank you.

**Comment by Rainking80** [comment]
It is working like a charm.

**Comment by paulsalameh** [comment]
Cool, glad to help!

**Comment by steven-supersolid** [comment]
I'm finding I need to add profile & email scopes to get a server auth code that can be exchanged for an id_token. Omitting profile gave no auth code.

**Comment by hippogamesunity** [comment]
Hello from 2024! How to edit scopes to get JWT?
There is no JWT with default scopes
"scope": "https://www.googleapis.com/auth/drive.appdata https://www.googleapis.com/auth/games_lite",
