### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by fromsantorini** [playgameservices/play-games-plugin-for-unity#1294]
unity : 5.3.5f1
google play service rev : 31

error

CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Users\<username>\AppData\Local\Android\sdk\build-tools\24.0.1\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Users/<username>/AppData/Local/Android/sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages com.everyplay.Everyplay:com.facebook:com.facebook.android:com.google.example.games.mainlibproj -S "F:\Work\Temp\StagingArea\android-libraries\everyplay\res" -S "F:\Work\Temp\StagingArea\android-libraries\facebook-android-sdk-4.8.2\res" -S "F:\Work\Temp\StagingArea\android-libraries\facebook-android-wrapper-release\res"

stderr[
AndroidManifest.xml:40: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: C:\Users\<username>\AppData\Local\Android\sdk\platforms\android-23\android.jar
applyFileOverlay for drawable
trying overlaySet Key=com_facebook_button_background.xml
trying overlaySet Key=com_facebook_button_icon.png
trying overlaySet Key=com_facebook_button_like_background.xml
trying overlaySet Key=com_facebook_button_like_icon_selected.png
trying overlaySet Key=com_facebook_button_login_silver_background.xml

**Comment by Guhanesh** [comment]
how to solve this  error?
i have the same error with unity 5.4 too
