### ISSUE TITLE
GamesNativeSDK error with newer than play-services-games-8.4.0.aar

### ISSUE THREAD

**Issue by Rainking80** [playgameservices/play-games-plugin-for-unity#1297]
Hello,
I see this error:
`GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/ParticipantResult: an exception occurred.`
(I know this is sometimes because of old SDK versions)

I see that error with all plugins newer than 8.4.0 (eg. play-services-xxx-9.2.1). If I go gack zu 8.4. it is running correctly, but the Plugin asks to switch back to newer version very often. I have to use build tools "23.0.3" and I cannot switch to 24.0 beause Unity 5 crashes building 24.0.

Unity build error with 24.0 build tools:

> CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\android-sdk\build-tools\24.0.0\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/android-sdk\platforms\android-24\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.everyplay.Everyplay:com.google.example.games.mainlibproj:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.plus:android.support.v4 -S "C:\Workspace\Spacegame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res" -S "C:\Workspace\Spacegame\Temp\StagingArea\android-libraries\everyplay\res" -S "C:\Workspace\Spacegame\Temp\StagingArea\android-libraries\play-services-base-8.4.0\res" -S "C:\Workspace\Spacegame\Temp\StagingArea\android-libraries\play-services-basement-8.4.0\res" -S "C:\Workspace\Spacegame\Temp\StagingArea\android-libraries\play-services-drive-8.4.0\res" -S "C:\Workspace\Spacegame\Temp\StagingArea\android-libraries\play-services-games-8.4.0\res" -S "C:\Workspace\Spacegame\Temp\StagingArea\android-libraries\play-services-nearby-8.4.0\res" -S "C:\Workspace\Spacegame\Temp\StagingArea\android-libraries\play-services-plus-8.4.0\res" -S "C:\Workspace\Spacegame\Temp\StagingArea\android-libraries\support-v4-23.1.1\res"
<message truncated>

Is that problem known? Is there a solution? 

I already updated the google plugin and the SDK. 

Edit: I just upated the SDK to 24.0.1 so the Unity build is working again - but the issue is not solved.

Kind regards, 
Tino

**Comment by claywilkinson** [comment]
Which version of play-services-games are you including in your project when you get the runtime error?  Are there other classes that cannot be registered?

**Comment by Rainking80** [comment]
The are this 3 calsses mising:

> GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/ParticipantResult: an exception occurred.

> GamesNativeSDK: Can't register class com/google/android/gms/nearby/connection/AppIdentifier: an exception occurred.

> GamesNativeSDK: Can't register class com/google/android/gms/nearby/connection/AppMetadata: an exception occurred.

I use play-services-games-8.4.0.aar which works fine. As I said using a new version makes the game crash.

**Comment by claywilkinson** [comment]
The nearby connection classes are in play-services-nearby*.aar  Make sure all the aar files are the same version, e.g. 9.2.1

**Comment by Rainking80** [comment]
Ok I tried that. I replaced all *.aar files by the newest version from my android sdk folder (9.4.0). Unfortunately the google unity plugin tries to switch some of them (not all) back to 8.4.0. And then I get this error again. 
E.g.:
play-services-plus-8.4.0.aar
play-services-drive-8.4.0.aar
and so on.

![image](https://cloud.githubusercontent.com/assets/5574367/17531376/d62eda86-5e7b-11e6-9f59-1a1c6690565f.png)

**Comment by claywilkinson** [comment]
Hmm. that sounds like a bug definitely.  You should keep the 9.4.0 versions.  You can turn off the automatic checking from the menu by going to Assets > Google Play Services > Settings

**Comment by Rainking80** [comment]
Thank you for the hint with disabling the auto checking tool :) 

I guess its the same issue like this one:
[https://github.com/playgameservices/play-games-plugin-for-unity/issues/1281](url)
(I'll give "ffff1111" work around a try)

Kind regards to Mountain View!

**Comment by claywilkinson** [comment]
The resolver has been improved in plugin version 0.9.35 to make this sort of problem less likely.
