### ISSUE TITLE
Messages not being sent over Cellular (4G) network

### ISSUE THREAD

**Issue by thidlay** [playgameservices/play-games-plugin-for-unity#1298]
I'm trying out a demo app that creates a quick match between two participants, and sends a message every second from each device, then measures the latency between them.  When both devices are connected to WiFi, it works perfectly.  When one of the devices is connected through Verizon's 4G LTE network, however, no messages are ever received by either device.  I've tried using both reliable and unreliable messages, with the same result.

The logs in both cases show this line:

``
I/Unity   (19817):  [Play Games Plugin DLL] 07/26/16 17:01:24 -04:00 DEBUG: Updated participant statuses: [Participant: 'foo' (id bar), status=Joined, player=NULL, connected=True],[Participant: 'baz' (id\
 biff), status=Joined, player=[Player: 'baz' (id biff], connected=True]
``

In the case where it works (WiFi), it then shows a bunch of InternalOnDataReceived messages like this one:

``
I/Unity   (19817):  [Play Games Plugin DLL] 07/26/16 17:01:24 -04:00 DEBUG: Entering InternalOnDataReceived: 35
``

In the cell network case, however, it doesn't show anything after the "Updated participant" message.

Has anyone else had trouble with connectivity over Cellular networks?  Is this expected behavior?

**Comment by thidlay** [comment]
A little more information:  I added something to the ``OnRoomSetupProgress`` handler to print the percent setup progress, and it looks like the device connected to the cell network gets stuck at 20%, while the device connected to wifi completes the room setup and the ``OnRoomConnected`` handler is called.

**Comment by thidlay** [comment]
So, for some reason it's magically working now!  Maybe this suggests it's an issue with the cellular network?  The weird thing is that it was able to match to participants up in the same room, and the ```OnRoomConnected``` handler was called with success = true for the WiFi connected device, but the Cellular device's ``OnRoomConnected`` handler was never called.

**Comment by claywilkinson** [comment]
Glad it is working!  Cellular data networks are tricky and can cause this type of weirdness.
