### ISSUE TITLE
Invalid Classname : An exception was thrown by the type initializer for GooglePlayGames.Editor.GPGSDependencies

### ISSUE THREAD

**Issue by TELGAMES** [playgameservices/play-games-plugin-for-unity#1299]
When I try to Step up I got this : 

Invalid Classname : An exception was thrown by the type initializer for GooglePlayGames.Editor.GPGSDependencies

PLEASE HELP !

**Comment by Ahmed-YehiaGPEL** [comment]
It's been 2 days since I'm trying to solve this issue, **not solved yet.**

**Comment by Ahmed-YehiaGPEL** [comment]
**Finally Problem Solved,** I will be posting a detailed guide on how to fix this issue soon.

**Comment by TELGAMES** [comment]
Solved
