### ISSUE TITLE
Game invites and sharing

### ISSUE THREAD

**Issue by DavidoesW** [playgameservices/play-games-plugin-for-unity#1302]
I am aware that this may not be the best place to ask these question but I need these answers as soon as possible. Is this possible to send game invites to friends who hasn't played my game (in Unity3D) yet? And is this possible to share info like on facebook with your plugin? If this issue is unappropriate I won't mind it's deleted just after I get answers. And if they cannot be posted here I would like to get them sent to this email address: wdawid32@gmail.com. Thanks from advance :)

**Comment by claywilkinson** [comment]
Thanks for the question.  There isn't a easy way to invite friends with Play Game Services.  You might want to look at App Invites and use that to invite others to play the game: https://firebase.google.com/docs/invites/
