### ISSUE TITLE
iOS and Android without changing settings

### ISSUE THREAD

**Issue by z3t0** [playgameservices/play-games-plugin-for-unity#1303]
Hi All,

This may be a naive suggestion as I do not know the intricate details of how this plugin is programmed but would it be possible to keep the settings of Android (when using Window->GPG->Setup->Android) and for iOS but only read the necessary settings for the current build.

I ask because it would make it much easier to develop for both android and ios at the same time because you would not need to go window->GPG-> setup for (platform) each time.

Thanks for reading!

**Comment by z3t0** [comment]
Update:

It seems that what I want is already implemented in a fashion, except the Cocoapods dependencies are only set when Setup iOS is pressed, I will see if i can find a solution

**Comment by claywilkinson** [comment]
As along as you are not changing the values in the game configuration (such as adding achievements, etc.) you only need to run Setup once per platform, then you should be able to switch between the two, assuming they both use the same bundle id.
