### ISSUE TITLE
Not authenticated. How to see the debug logs?

### ISSUE THREAD

**Issue by RobertKerbin** [playgameservices/play-games-plugin-for-unity#1305]
Hello, experts.
I am going to add leaderboard on my project.
On launching the game, SignIn dialog appears.
But when click the Leaderboard button, the leaderboard UI never appears.
Here is my code.
void Awake () {
        PlayGamesPlatform.DebugLogEnabled = true;
	PlayGamesPlatform.Activate ();
}

void Start(){
                              Social.localUser.Authenticate ((bool success) => {
						if (success) {
								Debug.Log ("Authenticated, checking achievements");
						} else {
								Debug.Log ("Failed to authenticate");
						}
				});
}

void OnLeaderboard(){
    if (Social.localUser.authenticated) {
	((PlayGamesPlatform)Social.Active).ShowLeaderboardUI();
	}
}
I am working on Mac OS X.
I want to see the debug logs now.
But I don't know how to see it.

And how to solve this problem?

Thank you.

**Comment by claywilkinson** [comment]
With the device connected to your mac, you can run `adb logcat` from the command line to connect to the device and have the log displayed to stdout.  See https://developer.android.com/studio/command-line/logcat.html for more details.
