### ISSUE TITLE
Some users failed to authenticate with (mAuthState == AuthState.SilentPending)

### ISSUE THREAD

**Issue by shwlinux-ap** [playgameservices/play-games-plugin-for-unity#1307]
Hi.

Sometimes my users reported that they can't login with play-game-service.

So I collected their logs and found many of them failed to authenticate in File NativeClient.cs

In the method [HandleAuthTransition] of NativeClient.cs, there is if-statement checking (mAuthState == AuthState.SilentPending).

Their client go into this code and invoke callback with false.

What is this problem?

I'm using Unity 5.3.4 f1 and play-games-plugin-for-unity v0.9.27.

**Comment by claywilkinson** [comment]
Silent authentication can fail for several reasons.  The most common is that the player explicitly signed out at some point on that device.  Other reasons depend on the internal state of the cached data.

**Comment by shwlinux-ap** [comment]
Is there a good solution of cashed data case?

**Comment by drSpritz** [comment]
I have the same problem, which is 1/3 of my users can not log in. Are there any solutions?

**Comment by claywilkinson** [comment]
If silent authentication fails, then use normal (non-silent authentication).
