### ISSUE TITLE
Achievements icon in play market

### ISSUE THREAD

**Issue by Bocharick** [playgameservices/play-games-plugin-for-unity#1311]
Hello. I use this plugin for my game on Android.
Leaderboards and Achievements are enabled and works fine.
But for my game i can see only "Leaderboards" icon in play market, and google play games has only Leaderboards but has no achievements.
What I have:
https://pp.vk.me/c626718/v626718594/22e15/jaj6_ov-euk.jpg
What I want to see:
http://cs623329.vk.me/v623329713/2eab/8zbTAQjz2Bw.jpg

Why play market has no Achievements icon and Google Play games for my game not showing achievements?
https://pp.vk.me/c626718/v626718594/22e1f/9-ptH3E7J98.jpg

**Comment by claywilkinson** [comment]
Thanks for the feedback.  Can you submit this to the play store feedback directly (use the Contact Support link at the bottom of the page)?  It really has nothing to do with this plugin.
