### ISSUE TITLE
GPGSAppController application:didRegisterForRemoteNotificationsWithDeviceToken:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by twyixstudios** [playgameservices/play-games-plugin-for-unity#1313]
Using Unity 5.4.0f3, and GPS 0.9.3.4, app crashes on startup

GPGSAppController application:didRegisterForRemoteNotificationsWithDeviceToken:]: unrecognized selector sent to instance 0x125fd97e0
2016-08-06 13:28:37.120 falldownbattle[431:52469] Uncaught exception: NSInvalidArgumentException: -[GPGSAppController application:didRegisterForRemoteNotificationsWithDeviceToken:]: unrecognized selector sent to instance 0x125fd97e0
(
	0   CoreFoundation                      0x0000000180bf2dc8 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000180257f80 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000180bf9c4c <redacted> + 0
	3   CoreFoundation                      0x0000000180bf6a1c <redacted> + 408
	4   CoreFoundation                      0x0000000180af4c5c _CF_forwarding_prep_0 + 92
	5   falldownbattle                      0x0000000100c1fcd0 -[GPGSAppController application:didRegisterForRemoteNotificationsWithDeviceToken:] + 116
	6   libdispatch.dylib                   0x0000000104251a7c _dispatch_call_block_and_release + 24
	7   libdispatch.dylib                   0x0000000104251a3c _dispatch_client_callout + 16
	8   libdispatch.dylib                   0x00000001042574e4 _dispatch_main_queue_callback_4CF + 2096
	9   CoreFoundation                      0x0000000180ba8d50 <redacted> + 12
	10  CoreFoundation                      0x0000000180ba6bb8 <redacted> + 1628
	11  CoreFoundation                      0x0000000180ad0c50 CFRunLoopRunSpecific + 384
	12  GraphicsServices                    0x00000001823b8088 GSEventRunModal + 180
	13  UIKit                               0x0000000185dba088 UIApplicationMain + 204
	14  falldownbattle                      0x0000000100010b20 main + 208
	15  libdyld.dylib                       0x000000018066e8b8 <redacted> + 4
)
2016-08-06 13:28:37.121 falldownbattle[431:52469] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GPGSAppController application:didRegisterForRemoteNotificationsWithDeviceToken:]: unrecognized selector sent to instance 0x125fd97e0'
*** First throw call stack:
(0x180bf2db0 0x180257f80 0x180bf9c4c 0x180bf6a1c 0x180af4c5c 0x100c1fcd0 0x104251a7c 0x104251a3c 0x1042574e4 0x180ba8d50 0x180ba6bb8 0x180ad0c50 0x1823b8088 0x185dba088 0x100010b20 0x18066e8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by renezuidhof** [comment]
I am having the exact same issue, would love to hear a solution.

**Comment by felipecaldas** [comment]
Exact same issue here as well!! :(

**Comment by felipecaldas** [comment]
I deleted the line:

```
 [super application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
  NSLog(@"Got Token for APNS: %@", deviceToken);
```

from the method ```
- (void)application:(UIApplication *)application
didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
```

And it worked. Just dont know if it's the right thing to do

**Comment by claywilkinson** [comment]
Thanks for the info @felipecaldas 
That's two lines - can you check if the call to the super class or the log statement is causing the issue? Does deviceToken have a value?

**Comment by Activate78** [comment]
Same issue thanks @felipecaldas 
I change it inside unity , Plugin -> iOS -> GPGSAppController.mm

` - (void)application:(UIApplication *)application
didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {

  // [super application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
  // NSLog(@"Got Token for APNS: %@", deviceToken);


  // send the token to GPGS server so invitations can be sent to the local player
  // NOTE: GPGPushNotificationEnvironmentProduction indicates this is
  // using the production APNS service.
  // GPGPushNotificationEnvironmentSandbox indicates that the sandbox
  // service should be used.  This value needs to match the cooresponding
  // certificate registered in the play app console, under linked apps > ios in
  // the section for push notifications.
  gpg::RegisterDeviceToken(deviceToken, GPGPushNotificationEnvironmentProduction);
}
`

**Comment by thoersch** [comment]
Any update on this?

**Comment by payini** [comment]
Having the exact same issue... any solution yet?

**Comment by claywilkinson** [comment]
Deleting the calls to super is the correct fix.

**Comment by claywilkinson** [comment]
The offending line was deleted in 0.9.35
