### ISSUE TITLE
Auth not working

### ISSUE THREAD

**Issue by parkJeongOck** [playgameservices/play-games-plugin-for-unity#1314]
not Working LOG : 

08-08 17:42:08.360: D/StatusBar.NetworkController(5689): refreshViews connected={ wifi } level=4 combinedSignalIconId=0x7f02072a/com.android.systemui:drawable/stat_sys_wifi_signal_4 mobileLabel=LG U+ wifiLabel="wixoss" emergencyOnly=false combinedLabel="wixoss" mAirplaneMode=false mDataActivity=4 mPhoneSignalIconId=0x7f0206a5/com.android.systemui:drawable/stat_sys_signal_4_auto_rotate mQSPhoneSignalIconId=0x7f0201c8/com.android.systemui:drawable/ic_qs_signal_no_signal mDataDirectionIconId=0x0/(null) mDataSignalIconId=0x7f0206a5/com.android.systemui:drawable/stat_sys_signal_4_auto_rotate mDataTypeIconId=0x7f020500/com.android.systemui:drawable/stat_sys_data_connected_lte mQSDataTypeIconId=0x7f0201c7/com.android.systemui:drawable/ic_qs_signal_lte mNoSimIconId=0x0/(null) mWifiIconId=0x7f02072a/com.android.systemui:drawable/stat_sys_wifi_signal_4 mQSWifiIconId=0x7f0203fb/com.android.systemui:drawable/qs_tile_wifi_signal_4 mWifiActivityIconId=0x7f0206e6/com.android.systemui:drawable/stat_sys_signal_out mBluetoothTetherIconId=0x7f020701/com.android.systemui:drawable/stat_sys_tether_bluetooth
08-08 17:42:08.370: D/StatusBar.NetworkController(5689): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
08-08 17:42:08.370: D/StatusBar.NetworkController(5689): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
08-08 17:42:08.370: D/StatusBar.NetworkController(5689): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
08-08 17:42:08.370: D/StatusBar.NetworkController(5689): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
08-08 17:42:08.530: D/InputReader(2258): Input event(10): value=1 when=146217649448000
08-08 17:42:08.530: I/InputReader(2258): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.10642 ] when=146217649448000
08-08 17:42:08.540: D/InputReader(2258): lastThreadEndTime = 146188791376263, currentThreadStartTime = 146188791379075, diff = 0
08-08 17:42:08.540: I/InputDispatcher(2258): Delivering touch to (30577): action: 0x0, toolType: 1
08-08 17:42:08.580: D/PowerManagerService(2258): [s] UserActivityState : 2 -> 1
08-08 17:42:08.690: D/InputReader(2258): Input event(10): value=0 when=146217803541000
08-08 17:42:08.690: I/InputReader(2258): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=146217803541000
08-08 17:42:08.690: I/InputDispatcher(2258): Delivering touch to (30577): action: 0x1, toolType: 1
08-08 17:42:08.750: D/GamesUnitySDK(30577): Performing Android initialization of the GPG SDK
08-08 17:42:08.940: I/dex2oat(30677): /system/bin/dex2oat --dex-file=/data/user/0/com.youlong.Descendant_of_Hero/app_.gpg.classloader/4da25210572e7e07ea67142ded62c42e.jar --oat-file=/data/user/0/com.youlong.Descendant_of_Hero/app_.gpg.classloader/4da25210572e7e07ea67142ded62c42e.dex
08-08 17:42:09.060: I/dex2oat(30677): ----------------------------------------------------
08-08 17:42:09.060: I/dex2oat(30677): <SS>: S T A R T I N G . . .
08-08 17:42:09.060: E/dex2oat(30677): <SS>: oat location is not valid /data/user/0/com.youlong.Descendant_of_Hero/app_.gpg.classloader/4da25210572e7e07ea67142ded62c42e.dex
08-08 17:42:09.060: I/dex2oat(30677): dex2oat took 117.446ms (threads: 4) arena alloc=36KB java alloc=29KB native alloc=1126KB free=921KB
08-08 17:42:09.080: E/GamesNativeSDK(30577): Exception in dalvik/system/DexClassLoader.loadClass: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.NativeSdkEntryPoints" on path: DexPathList[[zip file "/data/user/0/com.youlong.Descendant_of_Hero/app_.gpg.classloader/4da25210572e7e07ea67142ded62c42e.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]].
08-08 17:42:09.100: W/PopupManager(30577): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
08-08 17:42:09.100: I/GamesNativeSDK(30577): Auth operation started: SIGN IN
08-08 17:42:09.100: I/GamesNativeSDK(30577): Connecting to Google Play...
08-08 17:42:09.130: D/NetworkPolicy(2258): isUidForegroundLocked: 10035, mScreenOn: true, uidstate: 2, mProxSensorScreenOff: false
08-08 17:42:09.210: D/AppStateService(24961): client connected with version: 7895000
08-08 17:42:09.230: W/GamesServiceBroker(24961): Client connected with SDK 7895000, Services 9452430, and Games 37220030
08-08 17:42:09.270: I/Auth(25051): [AuthDelegateWrapper] Service intent: Intent { cmp=com.google.android.gms/.auth.account.authenticator.DefaultAuthDelegateService }.
08-08 17:42:09.280: I/Auth(25051): [AuthDelegateWrapper] Service intent: Intent { cmp=com.google.android.gms/.auth.account.authenticator.DefaultAuthDelegateService }.
08-08 17:42:09.290: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:09.340: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:09.350: D/SSRM:n(2258): SIOP:: AP = 480, PST = 482 (W:12), CP = 61, CUR = 450, LCD = 68
08-08 17:42:09.350: D/N(2258): limitCPUFreq:: freq = 1728000
08-08 17:42:09.350: D/CustomFrequencyManagerService(2258): acquireDVFSLockLocked : type : DVFS_MAX_LIMIT  frequency : 1728000  uid : 1000  pid : 2258  pkgName : SIOP_ARM_MAX@25
08-08 17:42:09.350: D/N(2258): limitGPUFreq:: freq = 389000000
08-08 17:42:09.350: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:09.350: D/N(2258): broadcastSiopLevelIntent:: currentSiopLevel = 2
08-08 17:42:09.360: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:09.360: V/BroadcastQueue(2258): [background] Process cur broadcast BroadcastRecord{48a6b9f u-1 android.intent.action.CHECK_SIOP_LEVEL qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{597fdd7 26238:com.sec.android.app.videoplayer/u0a56}
08-08 17:42:09.360: D/ContentApp(7136):  LEVEL : 2
08-08 17:42:09.360: D/ContentApp(7136): stopScan() is called.
08-08 17:42:09.370: E/TranscodeReceiver(26238): onReceive : android.intent.action.CHECK_SIOP_LEVEL
08-08 17:42:09.370: D/TranscodeReceiver(26238):  SIOP_LEVEL: 2
08-08 17:42:09.370: D/StatusBar.NetworkController(5689): refreshViews connected={ wifi } level=4 combinedSignalIconId=0x7f02072a/com.android.systemui:drawable/stat_sys_wifi_signal_4 mobileLabel=LG U+ wifiLabel="wixoss" emergencyOnly=false combinedLabel="wixoss" mAirplaneMode=false mDataActivity=4 mPhoneSignalIconId=0x7f0206a5/com.android.systemui:drawable/stat_sys_signal_4_auto_rotate mQSPhoneSignalIconId=0x7f0201c8/com.android.systemui:drawable/ic_qs_signal_no_signal mDataDirectionIconId=0x0/(null) mDataSignalIconId=0x7f0206a5/com.android.systemui:drawable/stat_sys_signal_4_auto_rotate mDataTypeIconId=0x7f020500/com.android.systemui:drawable/stat_sys_data_connected_lte mQSDataTypeIconId=0x7f0201c7/com.android.systemui:drawable/ic_qs_signal_lte mNoSimIconId=0x0/(null) mWifiIconId=0x7f02072a/com.android.systemui:drawable/stat_sys_wifi_signal_4 mQSWifiIconId=0x7f0203fb/com.android.systemui:drawable/qs_tile_wifi_signal_4 mWifiActivityIconId=0x7f0206db/com.android.systemui:drawable/stat_sys_signal_no_inout mBluetoothTetherIconId=0x7f020701/com.android.systemui:drawable/stat_sys_tether_bluetooth
08-08 17:42:09.370: D/StatusBar.NetworkController(5689): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
08-08 17:42:09.370: D/StatusBar.NetworkController(5689): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
08-08 17:42:09.370: D/StatusBar.NetworkController(5689): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
08-08 17:42:09.370: D/StatusBar.NetworkController(5689): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
08-08 17:42:09.370: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:09.380: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:09.380: D/TranscodeService(26238): onDestroy()
08-08 17:42:09.380: D/TranscodeService(26238): releaseTranscodeThread.
08-08 17:42:09.390: I/Auth(25051): [AuthDelegateWrapper] Service intent: Intent { cmp=com.google.android.gms/.auth.account.authenticator.DefaultAuthDelegateService }.
08-08 17:42:09.400: V/AccountUtils(24961): 0 accounts found with uca feature
08-08 17:42:09.450: I/System.out(25051): (HTTPLog)-Static: isSBSettingEnabled false
08-08 17:42:09.450: I/System.out(25051): (HTTPLog)-Static: isSBSettingEnabled false
08-08 17:42:09.450: D/EnterpriseController(484): netId is 0
08-08 17:42:09.450: D/Netd(484): getNetworkForDns: using netid 553 for uid 10012
08-08 17:42:09.470: D/ConnectivityService(2258): returning getNetworkInfo for network type 1 : [type: WIFI[] - WIFI, state: CONNECTED/CONNECTED, reason: (unspecified), extra: "wixoss", roaming: false, failover: false, isAvailable: true]
08-08 17:42:09.480: I/System.out(25051): (HTTPLog)-Static: isSBSettingEnabled false
08-08 17:42:09.480: I/System.out(25051): (HTTPLog)-Static: isSBSettingEnabled false
08-08 17:42:09.660: E/Watchdog(2258): !@Sync 4840 [08-08 17:42:09.672]
08-08 17:42:09.930: I/System.out(24961): (HTTPLog)-Static: isSBSettingEnabled false
08-08 17:42:09.930: I/System.out(24961): (HTTPLog)-Static: isSBSettingEnabled false
08-08 17:42:09.930: D/EnterpriseController(484): netId is 0
08-08 17:42:09.930: D/Netd(484): getNetworkForDns: using netid 553 for uid 10012
08-08 17:42:10.000: W/GoogleAuthUtil(24961): isUserRecoverableError status: NEED_PERMISSION
08-08 17:42:10.390: D/StatusBar.NetworkController(5689): refreshViews connected={ wifi } level=4 combinedSignalIconId=0x7f02072a/com.android.systemui:drawable/stat_sys_wifi_signal_4 mobileLabel=LG U+ wifiLabel="wixoss" emergencyOnly=false combinedLabel="wixoss" mAirplaneMode=false mDataActivity=4 mPhoneSignalIconId=0x7f0206a5/com.android.systemui:drawable/stat_sys_signal_4_auto_rotate mQSPhoneSignalIconId=0x7f0201c8/com.android.systemui:drawable/ic_qs_signal_no_signal mDataDirectionIconId=0x0/(null) mDataSignalIconId=0x7f0206a5/com.android.systemui:drawable/stat_sys_signal_4_auto_rotate mDataTypeIconId=0x7f020500/com.android.systemui:drawable/stat_sys_data_connected_lte mQSDataTypeIconId=0x7f0201c7/com.android.systemui:drawable/ic_qs_signal_lte mNoSimIconId=0x0/(null) mWifiIconId=0x7f02072a/com.android.systemui:drawable/stat_sys_wifi_signal_4 mQSWifiIconId=0x7f0203fb/com.android.systemui:drawable/qs_tile_wifi_signal_4 mWifiActivityIconId=0x7f0206d8/com.android.systemui:drawable/stat_sys_signal_inout mBluetoothTetherIconId=0x7f020701/com.android.systemui:drawable/stat_sys_tether_bluetooth
08-08 17:42:10.390: D/StatusBar.NetworkController(5689): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
08-08 17:42:10.400: D/StatusBar.NetworkController(5689): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
08-08 17:42:10.400: D/StatusBar.NetworkController(5689): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
08-08 17:42:10.400: D/StatusBar.NetworkController(5689): refreshNwBoosterIndicator - setNWBoosterIndicators(false)
08-08 17:42:10.430: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:10.440: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:10.470: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:10.480: V/GamesNativeSDK(30577): Play Games callback indicates connection failure.
08-08 17:42:10.480: I/GamesNativeSDK(30577): UI interaction required to connect to Google Play.
08-08 17:42:10.480: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:10.510: I/GamesNativeSDK(30577): Auth operation started: SIGN IN
08-08 17:42:10.510: I/GamesNativeSDK(30577): Connecting to Google Play...
08-08 17:42:10.520: D/AppStateService(24961): client connected with version: 7895000
08-08 17:42:10.540: W/GamesServiceBroker(24961): Client connected with SDK 7895000, Services 9452430, and Games 37220030
08-08 17:42:10.550: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:10.560: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:10.570: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:10.580: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:10.580: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:10.580: I/System.out(25051): (HTTPLog)-Static: isSBSettingEnabled false
08-08 17:42:10.580: I/System.out(25051): (HTTPLog)-Static: isSBSettingEnabled false
08-08 17:42:10.590: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:10.600: I/Auth(25051): [AuthDelegateWrapper] Service intent: Intent { cmp=com.google.android.gms/.auth.account.authenticator.DefaultAuthDelegateService }.
08-08 17:42:10.600: V/AccountUtils(24961): 0 accounts found with uca feature
08-08 17:42:10.600: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:10.610: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:10.620: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:10.630: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:10.630: D/BatteryService(2258): !@BatteryListener : batteryPropertiesChanged!
08-08 17:42:10.630: D/BatteryService(2258): level:98, scale:100, status:2, health:2, present:true, voltage: 4213, temperature: 375, technology: Li-ion, AC powered:false, USB powered:true, POGO powered:false, Wireless powered:false, icon:17303557, invalid charger:0, maxChargingCurrent:0
08-08 17:42:10.630: D/BatteryService(2258): online:4, current avg:450, charge type:1, power sharing:false, high voltage charger:false, capacity:280000, batterySWSelfDischarging:false, current_now:450
08-08 17:42:10.630: D/BatteryService(2258): Sending ACTION_BATTERY_CHANGED.
08-08 17:42:10.640: I/MotionRecognitionService(2258): Plugged
08-08 17:42:10.640: D/MotionRecognitionService(2258):   cableConnection= 1
08-08 17:42:10.640: D/MotionRecognitionService(2258): setPowerConnected | current backoff  = 1024 , state =1024
08-08 17:42:10.640: D/MotionRecognitionService(2258): skip setTransmitPower. 
08-08 17:42:10.640: D/KeyguardUpdateMonitor(5689): received broadcast android.intent.action.BATTERY_CHANGED
08-08 17:42:10.640: I/PERF(5689): received broadcast android.intent.action.BATTERY_CHANGED
08-08 17:42:10.640: D/KeyguardUpdateMonitor(5689): handleBatteryUpdate
08-08 17:42:10.640: D/KeyguardFestivalEffect(5689): onReceive: android.intent.action.BATTERY_CHANGED
08-08 17:42:10.650: D/BatteryMeterView(5689): ACTION_BATTERY_CHANGED : level:98 status:2 health:2
08-08 17:42:10.650: I/BusinessExecutor(5880): registered Task#15115 : PowerInfoEventSource$1
08-08 17:42:10.650: I/BusinessExecutor(5880): Task#15115 : #run() called
08-08 17:42:10.650: I/BusinessExecutor(5880): Task#15115 : #run() ended
08-08 17:42:10.650: D/BatteryMeterView(5689): ACTION_BATTERY_CHANGED : level:98 status:2 health:2
08-08 17:42:10.650: D/BatteryMeterView(5689): ACTION_BATTERY_CHANGED : level:98 status:2 health:2
08-08 17:42:10.910: W/GoogleAuthUtil(24961): isUserRecoverableError status: NEED_PERMISSION
08-08 17:42:10.910: V/GamesNativeSDK(30577): Play Games callback indicates connection failure.
08-08 17:42:10.910: I/GamesNativeSDK(30577): UI interaction required to connect to Google Play.
08-08 17:42:10.910: I/GamesNativeSDK(30577): Resolving connection.
08-08 17:42:10.930: D/PowerManagerService(2258): [api] release WakeLock flags=0x1a tag=Unity-ProjectRequestedWakeLock uid=10365 pid=30577 (0x0)
08-08 17:42:10.970: I/Sensors(2258): Acc old sensor_state 8193, new sensor_state : 8192 en : 0
08-08 17:42:11.020: D/OpenIAB-UnityPlugin(30577): onActivityResult(4673607, 0, null
08-08 17:42:11.020: V/GamesNativeSDK(30577): Received Activity Resume Event.
08-08 17:42:11.030: D/PowerManagerService(2258): [api] acquire WakeLock flags=0x1a tag=Unity-ProjectRequestedWakeLock uid=10365 pid=30577
08-08 17:42:11.030: I/Sensors(2258): Acc old sensor_state 8192, new sensor_state : 8193 en : 1
08-08 17:42:11.040: D/StatusBarManagerService(2258): manageDisableList userId=0 what=0x0 pkg=Window{78722c9 u0 d0 com.youlong.Descendant_of_Hero/com.youlong.Descendant_of_Hero.MainActivity}
08-08 17:42:11.040: D/PhoneStatusBar(5689): setSystemUiVisibility vis=9706 mask=ffffffff oldVal=9707 newVal=9706 diff=1
08-08 17:42:11.040: I/AudioSystem(30577): audioHookParam = off 
08-08 17:42:11.040: I/AudioSystem(30577): audioHookParam = off 
08-08 17:42:11.040: I/AudioSystem(30577): audioHookParam = off 
08-08 17:42:11.040: I/AudioTrack(30577): audioHookParam = off 
08-08 17:42:11.050: I/AudioSystem(30577): audioHookParam = off 
08-08 17:42:11.050: I/Sensors(2258): AccSensor setDelay changed to 20 ms
08-08 17:42:11.050: W/AudioPolicyIntefaceImpl(494): Skipped to add effects on session 1495
08-08 17:42:11.050: I/APM::AudioPolicyManager(494): startOutput() output 2, stream 3, session 1495
08-08 17:42:11.060: D/AppStateService(24961): client connected with version: 7895000
08-08 17:42:11.060: I/AudioMixer(494): create resampler src 24000, 2, dst 48000, 2
08-08 17:42:11.060: D/SoundAliveResampler(494): [SoundAliveResampler] Init+++
08-08 17:42:11.060: W/GamesServiceBroker(24961): Client connected with SDK 7895000, Services 9452430, and Games 37220030
08-08 17:42:11.070: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:11.080: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:11.090: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:11.100: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:11.110: D/PanelView(5689): kidsfalse mQsExpansionEnabled:true
08-08 17:42:11.110: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:11.120: D/BatteryMeterView(5689): onDraw batteryColor : -1107296257
08-08 17:42:11.120: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:11.130: I/APM::AudioPolicyManager(494): stopOutput() output 2, stream 3, session 1494
08-08 17:42:11.130: I/Auth(25051): [AuthDelegateWrapper] Service intent: Intent { cmp=com.google.android.gms/.auth.account.authenticator.DefaultAuthDelegateService }.
08-08 17:42:11.130: I/System.out(25051): (HTTPLog)-Static: isSBSettingEnabled false
08-08 17:42:11.130: I/System.out(25051): (HTTPLog)-Static: isSBSettingEnabled false
08-08 17:42:11.140: V/AccountUtils(24961): 0 accounts found with uca feature
08-08 17:42:11.140: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:11.150: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:11.160: E/PopupManager(24961): No content view usable to display popups. Popups will not be displayed in response to this client's calls. Use setViewForPopups() to set your content view.
08-08 17:42:11.160: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030
08-08 17:42:11.440: W/GoogleAuthUtil(24961): isUserRecoverableError status: NEED_PERMISSION
08-08 17:42:11.450: V/GamesNativeSDK(30577): Play Games callback indicates connection failure.
08-08 17:42:11.450: I/GamesNativeSDK(30577): UI interaction required to connect to Google Play.
08-08 17:42:11.530: D/StatusBarManagerService(2258): manageDisableList userId=0 what=0x0 pkg=Window{78722c9 u0 d0 com.youlong.Descendant_of_Hero/com.youlong.Descendant_of_Hero.MainActivity}
08-08 17:42:11.530: D/PhoneStatusBar(5689): setSystemUiVisibility vis=9707 mask=ffffffff oldVal=9706 newVal=9707 diff=1
08-08 17:42:11.530: D/PhoneStatusBar(5689): animateCollapse(): mExpandedVisible=false flags=0
08-08 17:42:11.530: D/StatusBar-Window(5689): fnf=true sanc=false, kni=false, sbf=false
08-08 17:42:11.530: D/CoverUI(5689): applyFocusableFlag() : Remove SAMSUNG_FLAG_SVIEW_COVER
08-08 17:42:11.530: D/CoverUI(5689): applyHeight h = 96, oc = false, ex = false, fa = false, ac = false, sc = false
08-08 17:42:11.560: D/PanelView(5689): kidsfalse mQsExpansionEnabled:true
08-08 17:42:11.570: D/Recents(5689): handleProxyCall type=3
08-08 17:42:11.580: D/Recents(5843): handleProxyCall type=3
08-08 17:42:11.590: D/BatteryMeterView(5689): onDraw batteryColor : -1107296257

Unity Ver : 4.6  
package  : GooglePlayGamesPlugin-0.9.10.unitypackage

please Help me.

**Comment by claywilkinson** [comment]
It looks like you have 2 versions of the client library play-services-games in your app?  
`08-08 17:42:10.440: W/GamesServiceBroker(24961): Client connected with SDK 8487000, Services 9452430, and Games 37220030`
and 
`08-08 17:42:10.540: W/GamesServiceBroker(24961): Client connected with SDK 7895000, Services 9452430, and Games 37220030`

Can you update your Android SDK to the latest versions then update your Unity project to use those libraries?

**Comment by claywilkinson** [comment]
Please open a new issue including an updated log if this is still a problem.
