### ISSUE TITLE
play-services-gcm backwards compatibility

### ISSUE THREAD

**Issue by djcvijic** [playgameservices/play-games-plugin-for-unity#1318]
A previous version of this plugin also included a play-services-gcm (Google Cloud Messaging) library. After a recent update, our application started crashing whenever a push notification is received, because this library is no longer present. I propose that for the sake of backwards compatibility, the following code is added to the GPGSDependencies.RegisterDependencies method:

`svcSupport.DependOn("com.google.android.gms",
"play-services-gcm",
PluginVersion.PlayServicesVersionConstraint);`

**Comment by claywilkinson** [comment]
You can add your own dependencies using the same pattern.  They will be resolved.  I'd rather not add this dependency to the plugin explicitly, since it will negatively impact games that don't use GCM.
