### ISSUE TITLE
DONT WORK!

### ISSUE THREAD

**Issue by blackbearddd** [playgameservices/play-games-plugin-for-unity#132]
i click and dont return nothing o.O

this error: Login failed for some reason
UnityEngine.Debug:Log(Object)
testGPGMenu:<OnGUI>m__3F(Boolean) (at Assets/Scripts/testGPGMenu.cs:49)
GooglePlayGames.BasicApi.DummyClient:Authenticate(Action`1, Boolean) (at Assets/GooglePlayGames/BasicApi/DummyClient.cs:26)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:175)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:147)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesLocalUser.cs:36)
testGPGMenu:OnGUI() (at Assets/Scripts/testGPGMenu.cs:41)

**Comment by claywilkinson** [comment]
The reference to DummyClient in the call stack indicates you are trying to run the plugin in the editor or not on an Android or ios device.
