### ISSUE TITLE
[iOS] Creating match always return false

### ISSUE THREAD

**Issue by phuc149** [playgameservices/play-games-plugin-for-unity#1321]
Hi everybody!
I tried building sample project Tic Tac Toss on iOS device. Logging in is ok but when i choosed Random opponent to create a match, it failed all the time. Debugging show that PlayGamesPlatform.Instance.TurnBased.CreateQuickMatch's callback always return success = false.
`protected void OnMatchStarted(bool success, TurnBasedMatch match) {
// success always false! 
}`
Please let me know if i had something wrong. Here are what i have so far:
![unity](https://cloud.githubusercontent.com/assets/1808431/17613142/350947da-6084-11e6-9d39-55d363094c70.png)
![console](https://cloud.githubusercontent.com/assets/1808431/17613144/3a4ec44a-6084-11e6-8bc1-4b9caae11c63.png)
![login](https://cloud.githubusercontent.com/assets/1808431/17613146/3e1b6e7a-6084-11e6-8548-ad2c7971ca49.png)

Thank you so much!

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
