### ISSUE TITLE
[DOC] Loading friends require Google+ API

### ISSUE THREAD

**Issue by pikatch** [playgameservices/play-games-plugin-for-unity#1322]
When I'm not enabling the Google+ API (PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().**RequireGooglePlus()**.Build(); and **the checkbox in the setup menu**),  Social.localUser.LoadFriends() returns 0 friends without throwing an error. If this is normal behavior I suggest that you add in the documentation that you need to enable it and require it for retrieving friends list.

Regards,

**Comment by claywilkinson** [comment]
Thanks @pikatch for the feedback. Sounds like a good idea.

**Comment by Ravenh0lm** [comment]
With this solution Social.localUser.LoadFriends() also returns 0 for me.
Anybody know how retrieve friends from GP?

**Comment by claywilkinson** [comment]
LoadFriends will currently return an empty list all the time.  https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html

Google+ has now been completely removed from the Games API.
