### ISSUE TITLE
completed game status in TBMP

### ISSUE THREAD

**Issue by orrkislev** [playgameservices/play-games-plugin-for-unity#1324]
Hi
In TBMP, when one player finishes the match, it immediately (using delegate) updates the other player match status as completed, and the turn status as completed..
In [https://developers.google.com/games/services/android/turnbasedMultiplayer](url)  it says the match would apear as 'your turn' to other players, until they acknowledgeFinish the match.

I'm using my own UI for matches, where I dont care for completed or old matches, but I do need the player to see the last move of a match, and comfirm the ending of the match... that's why its bothering me right now...

also - is there a way to remove all inactive (completed/canceled) matches from getAllMatches()? there is 'dismiss' in the API, but I think its only for active matches...

thanks
Orr

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
