### ISSUE TITLE
Unable to merge android manifest (Theme.Translucent)

### ISSUE THREAD

**Issue by Amrojordan** [playgameservices/play-games-plugin-for-unity#1325]
Im getting this while compiling Android in unity. I have checked the player settings and manifests and all suppose to be ok except (Theme.Translucent)

This the is the Error:

 CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/amroabughonmi/Library/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[
Error: [Temp/StagingArea/AndroidManifest-main.xml, /Users/amroabughonmi/Unity Projects/SOP_src/Temp/StagingArea/android-libraries/play-services-ads-8.4.0/AndroidManifest.xml:10] Trying to merge incompatible /manifest/application/activity[@name=com.google.android.gms.ads.AdActivity] element:
  `<activity
--    @android:name="com.google.android.gms.ads.AdActivity">
--</activity>
--(end reached)
  <activity
++    @android:name="com.google.android.gms.ads.AdActivity"
++    @android:theme="@android:style/Theme.Translucent">
++</activity>`
]

stdout[
[Temp/StagingArea/AndroidManifest-main.xml:14, /Users/amroabughonmi/Unity Projects/SOP_src/Temp/StagingArea/android-libraries/ChartboostPlugin/AndroidManifest.xml:11] Skipping identical /manifest/application/activity[@name=com.chartboost.sdk.CBImpressionActivity] element.
[Temp/StagingArea/AndroidManifest-main.xml:14, /Users/amroabughonmi/Unity Projects/SOP_src/Temp/StagingArea/android-libraries/Chartboost_lib/AndroidManifest.xml:5] Skipping identical /manifest/application/activity[@name=com.chartboost.sdk.CBImpressionActivity] element.
[Temp/StagingArea/AndroidManifest-main.xml, /Users/amroabughonmi/Unity Projects/SOP_src/Temp/StagingArea/android-libraries/play-services-basement-8.4.0/AndroidManifest.xml:5] Skipping identical /manifest/application/meta-data[@name=com.google.android.gms.version] element.

**Comment by claywilkinson** [comment]
Check your plugins, it looks like you have duplicates or multiple versions of some client libraries.
