### ISSUE TITLE
Can not Authenticate with .EnableSavedGames

### ISSUE THREAD

**Issue by mbhaskar1** [playgameservices/play-games-plugin-for-unity#1326]
I can authenticate when I am not using any PlayGamesClientConfiguration, but if I use it and put in .EnableSavedGames, then when I run the build the app just crashes. It also seems to start authenticating  as I see the google play games notification on the top when I run the app.

I have enabled SavedGames in the Developer Console, so that isn't the issue.

**Comment by oliver9523** [comment]
I can confirm this. Using EnableSavedGames() now causes crash "Unfortunately, Google Play services has stopped" - I've rolled my unity project back to a previously working version (from 2 days ago, building with the same play-games-plugin and version of unity) the error persists. Server side issue maybe?

Removing...
```
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().EnableSavedGames().Build();
PlayGamesPlatform.InitializeInstance(config);
```
...stops the crashing (the above code was working 2 days ago with exactly the same versions of the plugin and unity)

**Comment by mbhaskar1** [comment]
Knowing someone else is also having the problem is helpful. I spent the last hour checking everything in my developer console and stuff, thinking I was making some stupid mistake.

**Comment by oliver9523** [comment]
I've fixed it by clearing all the data in the Google Play services app - not sure what the root of the problem was yet...

**Comment by mbhaskar1** [comment]
How did you go about doing that exactly?

**Comment by mbhaskar1** [comment]
Like what data are you clearing

**Comment by oliver9523** [comment]
https://developers.google.com/games/services/console/configuring

"To clear the cached data on Android, open Settings > Apps > Google Play services, click on Manage Space, then click on Clear All Data."

**Comment by mbhaskar1** [comment]
Thnx I'll test this now

**Comment by mbhaskar1** [comment]
![image](https://cloud.githubusercontent.com/assets/17301685/17652051/22325d04-6241-11e6-8ac8-a6f8604e227c.png)

Okay I'm probably doing something stupid, but all I see in Settings is this. I don't see anything that says Apps.

**Comment by mbhaskar1** [comment]
ohhhhh.... facepalm. That worked perfectly. Thanks for helping
