### ISSUE TITLE
"gpg/ios_support.h" file not found

### ISSUE THREAD

**Issue by GalaxyAceType0** [playgameservices/play-games-plugin-for-unity#1327]
I am getting this error in my Xcode project. I built it with Unity 4.7.2. Please advise! I use Google Play Games C++ SDK Version 2.1. Thank you.

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
