### ISSUE TITLE
GetServerAuthCode causes GoogleAuthException: INVALID_AUDIENCE

### ISSUE THREAD

**Issue by MixMasterRickyC** [playgameservices/play-games-plugin-for-unity#1328]
So I posted last week about an issue with GoogleAuthException: INVALID_AUDIENCE (https://github.com/playgameservices/play-games-plugin-for-unity/issues/1315)

Which seemed to be fixed by enabling the "Enable Google Plus API Access" in the settings.

Currently we are calling, GetUserId and GetAccessToken to confirm a valid user on our backend but the id returned doesn't match the user id passed from the client and I can't see any other functions that returns a user id.

So the User ID from (GetUserId) is "g10629234184469064241" 
but the server gets a response with a different user ID "110875418744042441117"

following this issue (https://github.com/playgameservices/play-games-plugin-for-unity/issues/1277) we should be using GetServerAuthCode to validate the user.

I've tried to use GetServerAuthCode: but the status code returned ERROR_INTERNAL and the logs had the following exception:

```
GamesServerAuthCodeOp: Failed to retrieve the server auth code
GamesServerAuthCodeOp: com.google.android.gms.auth.GoogleAuthException: INVALID_AUDIENCE
GamesServerAuthCodeOp: 	at com.google.android.gms.auth.GoogleAuthUtilLight$1.exec(GoogleAuthUtilLight.java:498)
GamesServerAuthCodeOp: 	at com.google.android.gms.auth.GoogleAuthUtilLight.connectAndExecute(GoogleAuthUtilLight.java:908)
GamesServerAuthCodeOp: 	at com.google.android.gms.auth.GoogleAuthUtilLight.getToken(GoogleAuthUtilLight.java:450)
GamesServerAuthCodeOp: 	at com.google.android.gms.auth.GoogleAuthUtil.getToken(GoogleAuthUtil.java:586)
GamesServerAuthCodeOp: 	at com.google.android.gms.games.service.operations.GetGamesServerAuthCodeOperation.performOperation(GetGamesServerAuthCodeOperation.java:66)
GamesServerAuthCodeOp: 	at com.google.android.gms.games.service.operations.AbstractStatusReportingOperation.execute(AbstractStatusReportingOperation.java:49)
GamesServerAuthCodeOp: 	at com.google.android.gms.games.service.operations.GamesOperationAdapter.execute(GamesOperationAdapter.java:23)
GamesServerAuthCodeOp: 	at com.google.android.gms.chimera.BaseAsyncOperationService$OperationTask.run(BaseAsyncOperationService.java:177)
GamesServerAuthCodeOp: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
GamesServerAuthCodeOp: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
GamesServerAuthCodeOp: 	at java.lang.Thread.run(Thread.java:818)
```

I also tried using the GetIdToken: which returns an empty string and I see the following exception in the logs

```
TokenFragment: Exception getting access token
TokenFragment: com.google.android.gms.auth.GoogleAuthException: INVALID_AUDIENCE
TokenFragment: 	at com.google.android.gms.auth.zzd$1.zzbr(Unknown Source)
TokenFragment: 	at com.google.android.gms.auth.zzd$1.zzbs(Unknown Source)
TokenFragment: 	at com.google.android.gms.auth.zzd.zza(Unknown Source)
TokenFragment: 	at com.google.android.gms.auth.zzd.zzc(Unknown Source)
TokenFragment: 	at com.google.android.gms.auth.zzd.getToken(Unknown Source)
TokenFragment: 	at com.google.android.gms.auth.zzd.getToken(Unknown Source)
TokenFragment: 	at com.google.android.gms.auth.zzd.getToken(Unknown Source)
TokenFragment: 	at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
TokenFragment: 	at com.google.games.bridge.TokenFragment$1.doInBackground(TokenFragment.java:240)
TokenFragment: 	at com.google.games.bridge.TokenFragment$1.doInBackground(TokenFragment.java:211)
TokenFragment: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
TokenFragment: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
TokenFragment: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
TokenFragment: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
TokenFragment: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
TokenFragment: 	at java.lang.Thread.run(Thread.java:818)
```

It still seems like I'm having problems with the "INVALID_AUDIENCE" exception but can't find any record of the exception in the documentation.

In the previous issue I stated 

> The only thing I can think of is that my Client ID doesn't have a '-' which meant updating the code for the "Google Play Games -> Setup -> Android setup..." so that the "Web Client App ID" would be accepted. Although the example given here (https://developers.google.com/games/services/console/enabling#client_id) doesn't either and the fact it works on some devices leads me to believe this isn't the issue.

but if anyone can help that would be appreciated.
Rick.

**Comment by MixMasterRickyC** [comment]
So after reading through this issue (https://github.com/playgameservices/play-games-plugin-for-unity/issues/10) 

Specifically this section 

> This line gms.StatusHelper Status from wire: INVALID_AUDIENCE status: null means you have not configured the web app client ID in the setup dialog. The steps are:
1. On the Play Console, select your game and make sure you have a linked app which is the type "Web".
2. copy the client id from the web app and paste it into the web client Id field in the setup dialog.
Also make sure you update the two files that need to be patched (GameInfo.cs and template-GameInfo.txt)

I tried Linking a "Web" app so I could generate a web client id, managed to do this but I'm still seeing the InternalError return value. I am not however seeing the exception from logcat. 

```*** [Play Games Plugin DLL] 08/15/16 15:24:34 +01:00 ERROR: Error loading server auth code: ERROR_INTERNAL```

I'm completely out of ideas now so any help would be appreciated.

**Comment by MixMasterRickyC** [comment]
That seemed to have fixed the issue and I can now get both the GetServerAuthCode and GetIdToken. Just working through changes to the backend to handle both types of user id.

**Comment by KCKH** [comment]
I have the same error when I switch client id between dev and production. I use two different client id. I need to wait some time and it work. I don't know what the reason of the server side too. Hope there is more explanation. I just wonder it too.
