### ISSUE TITLE
Android / LoadState Ex (  No such proxy method: GooglePlayGames.Android.OnStateResultProxy.hashCode )

### ISSUE THREAD

**Issue by Cpasjuste** [playgameservices/play-games-plugin-for-unity#133]
Since i updated plugins to latest versions (0.9.02 and gpg services 4.4.52, both in SDK and devices) i got an exception while trying to load a state on Android. 

Note that :

- OnStateLoaded callback does get called but raise the exception immediately even if no manipulation is done
- The exception is raised on a Kindle Fire HDX ( Android 4.2.2 )
- The exception is NOT raised on a Galaxy Note 2 ( Android 4.4 ), all work fine.
- There is no problem to save a state

Please find a log output here : http://pastebin.com/JXkbaudc

Thanks,
David.

**Comment by claywilkinson** [comment]
Closing as obsolete.  please open another issue if this is happening with the latest version of the plugin.
