### ISSUE TITLE
Does it works on Unity 4?

### ISSUE THREAD

**Issue by ivanquirino** [playgameservices/play-games-plugin-for-unity#1332]
I am trying to run this plugin on Unity 4, so far it imports normally. I configured everything as said in this docs but when I make the sign call, the google play games logo comes in, then there is a loading indicator and then it closes with the success parameter of the callback being false. Do I need to put this apk on beta testing to test it? I configured everything on google play, made 1 achievement, put the sha1 hash of my keystore on the developer console.

**Comment by ricky395** [comment]
I have the same issue, please help. I have Unity 5.4.0f3 and the last build of GPG (0.9.34). I tried everything and it still not connecting. Play services just attempts to log-in, but then the logo closes and nothing else happens, as @ivanquirino said. Any solution?

**Comment by ricky395** [comment]
@ivanquirino I solved it!! Thanks to this post: https://github.com/playgameservices/play-games-plugin-for-unity/issues/1326
You just need to clear all data from "google play services" app on your mobile device. Go to "settings > apps > google play services> manage space > clear all data"
That worked for me!

**Comment by ivanquirino** [comment]
@ricky395 going to try this right now! thank you!

**Comment by ivanquirino** [comment]
@ricky395 I tried cleaning, but still no result. Have you logged off from game services?

**Comment by ivanquirino** [comment]
Solved! My testing account was not set as default for new games. Setting it as default did it.

**Comment by ricky395** [comment]
Glad you solved it!
