### ISSUE TITLE
Google Play Service Plugin not working

### ISSUE THREAD

**Issue by Megalithic1990** [playgameservices/play-games-plugin-for-unity#1333]
Hi All, 

I have been using this plugin for a while now. Logging in, seeing achievements, seeing leaderboards etc. 

Two days ago all of a sudden the plugin stopped working. I can't sign into google play services and everytime I started my unity project I used to get this error. 

`NullReferenceException: Object reference not set to an instance of an object
GooglePlayServices.PlayServicesResolver.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:104)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:27)
UnityEditor.AssetDatabase:Refresh()
GooglePlayGames.Editor.GPGSUpgrader:.cctor() (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:107)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])`

But now I can't even import the plugin properly. When I import the plugin I can see the required folders in the assets folder but I cannot find the Google Play Service settings that you had in the window tab. And all my scripts that used codes from the google play services plugin give me the following error. 

`Assets/GPlayTest.cs(46,13): error CS0103: The name `PlayGamesPlatform' does not exist in the current context`

I have no idea why this is happening. Can anyone help me resolve this issue? It is eating into my project time and stressing me out.

**Comment by lawjeremy** [comment]
I am having this same problem. Everything was working properly one day and the next it's broken.

**Comment by Megalithic1990** [comment]
Well I got to solve my problem by Resolving Client Jars. 
Find "PlayServicesResolver" in your assets folder, right click on it and navigate to "Google Play Services" in the drop down menu, then select "Resolve Client Jars". Make sure you restart unity. It works for me.

If you have the same error message like mine then you could give it a shot and it might work.

**Comment by lawjeremy** [comment]
@Megalithic1990 I don't see "Google Play Services" when I right click on "PlayServicesResolver"

**Comment by lawjeremy** [comment]
@Megalithic1990 I couldn't see the menu options that you described, so I checked my build settings. Updating unity had switch my build target back the default. Once I switched it back to android, everything works again.

**Comment by Megalithic1990** [comment]
I see. Glad to know it is working now. Incase you were wondering how to  get the menu options I told you about, here take a look at the picture that might help you.

![resolve client jars](https://cloud.githubusercontent.com/assets/10834853/18072633/9406cf9c-6e57-11e6-95ad-3652f5896bc2.png)

**Comment by lawjeremy** [comment]
@Megalithic1990 Yeah, I couldn't see those menu options because I had the wrong build target selected. As soon as I changed it they appeared. Thanks!

**Comment by claywilkinson** [comment]
The resolver was improved in version 0.9.35 which should make the resolution process better.
