### ISSUE TITLE
Disconnection issue. realtime multiplay.

### ISSUE THREAD

**Issue by taekjun** [playgameservices/play-games-plugin-for-unity#1338]
I use realtime multiplay game service in my game.

Although It's a good service, I have a question.

When Players play game with GPGS,
If a player press home button or hold button,
game is disconnected immediately.

It would be great if GPGS keeps connected instead of being disconnected for about 10 seconds.
Could you give me a solution about this problem?
If there's no solution, I want to ask you a question about a plan to improve.

**Comment by LinkC0re** [comment]
Yes that is the only thing I also find annoying in  GPGS . 

This is already declared as enhancement.
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1166

Someone suggested to overwrite  onPause() method in Unity Android Activity.
In Unity go to build settings and choose "Google Android Project" and then export. Go to the exported project , to the file UnityPlayerActivity.java and overwrite onPause() to not do anything. Then go to an IDE like Android Studio and build the .apk. I tried but it didn't change anything. If you try and works, please let us know.

**Comment by lijuicsoft** [comment]
How to reconnect to a room in Google real time muliplayer with Unity3D ?

**I create a quick game multiplayer connection**

    const int MinOpponents = 1, MaxOpponents = 1;
    const int GameVariant = 0;
    PlayGamesPlatform.Instance.RealTime.CreateQuickGame(MinOpponents,MaxOpponent,GameVariant,listener);

**and Create With Invitation Screen**

     PlayGamesPlatform.Instance.RealTime.CreateWithInvitationScreen(
     minimumOpponents,maximumOpponents,gameVariation, listener);
Connected to a room with one opponent

 **I dissabled my Ethernet connection of one device**

    Control Panel > All Control Panel Items > Network and Sharing Center > Change Adapter Settings > Ethernet >Disable this network device

**I Enabled my Ethernet connection by**

    Control Panel > All Control Panel Items > Network and Sharing Center > Change Adapter Settings > Ethernet >Enable this network device

   

**In my game each player's data is sending to each other .** 

    PlayGamesPlatform.Instance.RealTime.SendMessageToAll (true, messageToSend);

**Before Ethernet disconnect it works perfect** . After ethernet reconnection data is not getting to each other , but if one device left the room , following event will call.

    public void OnPeersDisconnected (string[] participantIds)
      {
          foreach (string participantID in participantIds) {
              ShowMPStatus ("Player " + participantID + " has left.");
              if (updateListener != null) {
                  updateListener.PlayerLeftRoom (participantID);
              }
          }
      }

How to detect , player disconnected from net and how to reconnect to same room properly

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
