### ISSUE TITLE
Double authentication after cancelling

### ISSUE THREAD

**Issue by nicolaslorusso** [playgameservices/play-games-plugin-for-unity#1341]
When i try my first attempt to login and then hit the cancell button, after few seconds another login popup randomly appears. This not allways happens neither in all devices.
I did it on a empty project, just testing plugin functionality.

Tested in unity: 5.4, 5.3.1f1
Google Play Services Unity plugin version: 0.9.34, 0.9.31
Device with most problems: Moto G XT1031

Device Logcat:
08-30 12:19:32.599: I/Unity(24558):  [Play Games Plugin DLL] 08/30/16 12:19:32 -03:00 DEBUG: Activating PlayGamesPlatform.
08-30 12:19:32.599: I/Unity(24558):  
08-30 12:19:32.599: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:32.603: I/Unity(24558):  [Play Games Plugin DLL] 08/30/16 12:19:32 -03:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
08-30 12:19:32.603: I/Unity(24558):  
08-30 12:19:32.603: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:41.517: I/Unity(24558):  [Play Games Plugin DLL] 08/30/16 12:19:41 -03:00 DEBUG: Creating platform-specific Play Games client.
08-30 12:19:41.517: I/Unity(24558):  
08-30 12:19:41.517: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:41.519: I/Unity(24558):  [Play Games Plugin DLL] 08/30/16 12:19:41 -03:00 DEBUG: Creating Android IPlayGamesClient Client
08-30 12:19:41.519: I/Unity(24558):  
08-30 12:19:41.519: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:41.575: D/GamesUnitySDK(24558): Performing Android initialization of the GPG SDK
08-30 12:19:41.716: I/Unity(24558): Building GPG services, implicitly attempts silent auth
08-30 12:19:41.716: I/Unity(24558):  
08-30 12:19:41.716: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:41.888: I/Unity(24558):  [Play Games Plugin DLL] 08/30/16 12:19:41 -03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
08-30 12:19:41.888: I/Unity(24558):  
08-30 12:19:41.888: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:41.888: I/Unity(24558): Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
08-30 12:19:41.888: I/Unity(24558):  
08-30 12:19:41.888: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:41.890: I/Unity(24558): there are pending auth callbacks - starting AuthUI
08-30 12:19:41.890: I/Unity(24558):  
08-30 12:19:41.890: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:42.024: I/Unity(24558):  [Play Games Plugin DLL] 08/30/16 12:19:42 -03:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
08-30 12:19:42.024: I/Unity(24558):  
08-30 12:19:42.024: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:51.138: I/Unity(24558):  [Play Games Plugin DLL] 08/30/16 12:19:51 -03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
08-30 12:19:51.138: I/Unity(24558):  
08-30 12:19:51.138: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:51.139: I/Unity(24558): Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
08-30 12:19:51.139: I/Unity(24558):  
08-30 12:19:51.139: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:51.139: I/Unity(24558): there are pending auth callbacks - starting AuthUI
08-30 12:19:51.139: I/Unity(24558):  
08-30 12:19:51.139: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:51.222: I/Unity(24558):  [Play Games Plugin DLL] 08/30/16 12:19:51 -03:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
08-30 12:19:51.222: I/Unity(24558):  
08-30 12:19:51.222: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:59.861: I/Unity(24558):  [Play Games Plugin DLL] 08/30/16 12:19:59 -03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
08-30 12:19:59.861: I/Unity(24558):  
08-30 12:19:59.861: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:59.868: I/Unity(24558): AuthState == Unauthenticated calling auth callbacks with failure
08-30 12:19:59.868: I/Unity(24558):  
08-30 12:19:59.868: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
08-30 12:19:59.877: I/Unity(24558):  [Play Games Plugin DLL] 08/30/16 12:19:59 -03:00 DEBUG: Invoking user callback on game thread
08-30 12:19:59.877: I/Unity(24558):  
08-30 12:19:59.877: I/Unity(24558): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

**Comment by VladimirKuznetsov** [comment]
I have the same issue since I started using this plugin (since 0.9.27).

**Comment by claywilkinson** [comment]
Fixed in 0.9.39
