### ISSUE TITLE
NullReferenceException on "PlayGamesPlatform.Instance.SavedGame" function

### ISSUE THREAD

**Issue by ricky395** [playgameservices/play-games-plugin-for-unity#1342]
Hi! I added google play services to my game and I'm trying now to save data to cloud. All good until I create an instance of **ISavedGameClient** to be able to call **OpenWithAutomaticConflictResolution** function. (I tried with '((PlayGamesPlatform)Social.Active).SavedGame' instead of **ISavedGameClient** instance, but it returns null anyway). As it is null, the **OpenWithAutomaticConflictResolution** call doesn't work at all and I don't know how to get an **ISavedGameClient** not null instance.

The code (sorry, it doesn't allow me to insert code):

https://drive.google.com/open?id=0B7lxv94XBtDUWm5TbzZ3UURDVFk

**Comment by Fortis9777** [comment]
Try to put Activatation of Play Services lower. Something like that:

    PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
        // enables saving game progress.
        .EnableSavedGames()
        .Build();
    PlayGamesPlatform.InitializeInstance(config);

PlayGamesPlatform.DebugLogEnabled = true;
    // Activate the Google Play Games platform
    PlayGamesPlatform.Activate();

**Comment by Athomield** [comment]
Has this error been solved, I can't seem to get it right. Do I need to deply the app to google play for the error to go ?
