### ISSUE TITLE
Using the Plugin Without Overriding the Default Social Platform

### ISSUE THREAD

**Issue by hippogamesunity** [playgameservices/play-games-plugin-for-unity#1344]
My environment is iOS + native leaderboards & achievements + gpgs cloud. And it does not work(

I build configuration with saved games and they are enabled from developer console.
I don't call PlayGamesPlatform.Activate(); as describetd in [(Advanced) Using the Plugin Without Overriding the Default Social Platform].

So my steps are:

var config = new PlayGamesClientConfiguration.Builder().EnableSavedGames().Build();
PlayGamesPlatform.InitializeInstance(config);
PlayGamesPlatform.DebugLogEnabled = true; // SUCCESS
PlayGamesPlatform.Instance.localUser.Authenticate // SUCCESS
PlayGamesPlatform.Instance.SavedGame.OpenWithAutomaticConflictResolution // ERROR

Here is game log:
GamesServicesClient: initializing gpgs...
!!! [Play Games Plugin DLL] 08/27/16 13:41:35 +03:00 WARNING: PlayGamesPlatform already initialized. Ignoring this call. // STRANGE, WHY?
GamesServicesClient: authentication...
[Play Games Plugin DLL] 08/27/16 13:41:35 +03:00 DEBUG: Creating platform-specific Play Games client.
[Play Games Plugin DLL] 08/27/16 13:41:35 +03:00 DEBUG: Creating IOS IPlayGamesClient
Building GPG services, implicitly attempts silent auth
Assets.Scripts.Common.GamesServicesClient:AuthorizedAction(Action, Boolean)
[Play Games Plugin DLL] 08/27/16 13:42:01 +03:00 DEBUG: Application is pausing, which disconnects the RTMP client. Leaving room.
Play Games Plugin DLL] 08/27/16 13:42:02 +03:00 DEBUG: Invoking user callback on game thread
GamesServicesClient: opening: EU...
NotImplementedException: You must enable saved games before it can be used. See PlayGamesClientConfiguration.Builder.EnableSavedGames.
GooglePlayGames.Native.UnsupportedSavedGamesClient.OpenWithManualConflictResolution (System.String filename, DataSource source, Boolean prefetchDataOnConflict, GooglePlayGames.BasicApi.SavedGame.ConflictCallback conflictCallback, System.Action`2 completedCallback)
GooglePlayGames.OurUtils.PlayGamesHelperObject.Update ()

UPD - cloud works in my Android configuration.

**Comment by Leuthil** [comment]
Things to check while you wait for someone who may have a real answer:
1. Do you have any code anywhere that also calls `InitializeInstance()`?
2. Are Saved Games enabled for your game in the Google Play Developer Console?

**Comment by claywilkinson** [comment]
This message `NotImplementedException: You must enable saved games before it can be used. See PlayGamesClientConfiguration.Builder.EnableSavedGames.` points to Saved Games not being enabled on the developer console.
