### ISSUE TITLE
Check if Play Games is installed?

### ISSUE THREAD

**Issue by alamboley** [playgameservices/play-games-plugin-for-unity#1346]
Hey, I'm aware of this issue #715 

However it doesn't solve mine, I'm looking for a way to determine if this app https://play.google.com/store/apps/details?id=com.google.android.play.games is installed.

Trying the script mentionned it always reported true even when I uninstalled the Google Play Games... :/

I would like to prevent the big popup when starting the game if the app isn't installed.

**Comment by alamboley** [comment]
FIgured it out:
```c#
#if UNITY_ANDROID

AndroidJavaClass up = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
AndroidJavaObject ca = up.GetStatic<AndroidJavaObject>("currentActivity");
AndroidJavaObject packageManager = ca.Call<AndroidJavaObject>("getPackageManager");

AndroidJavaObject launchIntent = null;
//if the app is installed, no errors. Else, doesn't get past next line
try { 
	launchIntent = packageManager.Call<AndroidJavaObject>("getLaunchIntentForPackage", "com.google.android.play.games");
	//        
	//        ca.Call("startActivity",launchIntent);
} catch (Exception ex) {
	//Debug.Log("exception"+ex.Message);
}

Debug.Log("Is Play Games installed: " + launchIntent != null);

#endif
```

Would be nice to have it as a method directly in the package!

**Comment by claywilkinson** [comment]
Nice suggestion.  I think this check is done during authentication, do you want to do it outside that?

Feel free to submit a pull request to add it to the plugin.

**Comment by JamesMcMahon** [comment]
I'm have issues with my users who don't have Play Games installed (see https://github.com/playgameservices/play-games-plugin-for-unity/issues/1368) so I don't think a check is done during authentication, but I could be wrong.

**Comment by JamesMcMahon** [comment]
Started a PR at https://github.com/playgameservices/play-games-plugin-for-unity/pull/1370.

**Comment by claywilkinson** [comment]
This won't stop the popup in all cases.  There are two components to Play Game services.  The first is checked with the one outlined in #715. This is checking for Google Play Services, and will return false for Android devices that don't use the Google Play Store to distribute apps.  As you pointed this usually returns true, or maybe that it needs to be updated to meet the minimum version requirements from the client library.

The second component is that the Play Games App  implements some of the game services APIs on behalf of play services (not exactly a DLL, but similar).  This method you are adding will check that the app is installed, but does not check for the correct version.  As a result, your players could still get a big pop up indicating that Play Games needs to be updated.

Can you expand on what you want to guard against?  It seems like if your game uses Play Game Services, and it is available on the device, why not have the player do the one time update to get the correct version of the app?  For a large proportion of the population, this happens automatically if they have auto-update on for their apps.

**Comment by JamesMcMahon** [comment]
My personal use case was the first scenario you outlined. I want to avoid authenticating to Google Play Services and also log to may backend when someone is running my game without Google Play Services on their phone. Before I implemented the check I was seeing a lot of crashes from users, this helps avoid that.

I think the second scenario is acceptable. Google Play Services are supported, and hence the method is giving the right information, but they may need to be updated. But you have a better handle on what is going to work for a larger user base.

I started a PR based on your comment:

> Nice suggestion. I think this check is done during authentication, do you want to do it outside that?

> Feel free to submit a pull request to add it to the plugin.

**Comment by claywilkinson** [comment]
This is integrated into version 0.9.36

**Comment by rafaelf82** [comment]
For anyone who ends up here, to check if Play Games is installed check this property:

GooglePlayGames.OurUtils.PlatformUtils.Supported

**Comment by tiennguyenlastmile** [comment]
Good job bro :D

**Comment by ALI3NPANDA** [comment]
Hey @rafaelf82,  For me, Even after having the google play game installed, It returns false.

if (!GooglePlayGames.OurUtils.PlatformUtils.Supported)
          {
            Debug.Log("No Play Games Detected");
          }
        else
        {
            Debug.Log("Play Games Detected");
            GoogleSignin();
}

**Comment by rafaelf82** [comment]
> Hey @rafaelf82, For me, Even after having the google play game installed, It returns false.

Seems to be a new bug...

https://github.com/playgameservices/play-games-plugin-for-unity/issues/3106

**Comment by ALI3NPANDA** [comment]
> Android 11 introduced limitations on the packages your app can see. So even if someone has the app installed, it won't appear to be installed unless you explicitly declare that you check for it in your Android manifest.
> This page details how you make the declaration:
> https://developer.android.com/training/basics/intents/package-visibility
> https://developer.android.com/guide/topics/manifest/queries-element


Any idea on how to solve this?

**Comment by smile616** [comment]
@ALI3NPANDA 

could you please try add:
     <queries>
        <package android:name="com.google.android.play.games" />
    </queries>
to the game AndroidManifest.xml
as suggested at https://developer.android.com/training/package-visibility/declaring
and report back?

**Comment by ALI3NPANDA** [comment]
@smile616  I'm sorry. I have no idea where should I add this piece of code. I tried adding them below </intent-filter> and the build failed.

    <application>
        <activity android:name="com.unity3d.player.UnityPlayerActivity"
                  android:theme="@style/UnityThemeSelector">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
        </activity>
    </application>

**Comment by smile616** [comment]
@ALI3NPANDA, add it after `</application>`, something like:
```
<application>
    <activity android:name="com.unity3d.player.UnityPlayerActivity"
              android:theme="@style/UnityThemeSelector">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
    </activity>
</application>
<queries>
  <package android:name="com.google.android.play.games" />
</queries>
```

**Comment by ALI3NPANDA** [comment]
Thank you @smile616 .  It's working perfectly.

**Comment by smile616** [comment]
Glad to hear, @ALI3NPANDA!

**Comment by ariok** [comment]
> <queries>
>   <package android:name="com.google.android.play.games" />
> </queries>

It should be written directly by the plug-in probably

**Comment by ariok** [comment]
> @ALI3NPANDA, add it after `</application>`, something like:
> 
> ```
> <application>
>     <activity android:name="com.unity3d.player.UnityPlayerActivity"
>               android:theme="@style/UnityThemeSelector">
>         <intent-filter>
>             <action android:name="android.intent.action.MAIN" />
>             <category android:name="android.intent.category.LAUNCHER" />
>         </intent-filter>
>         <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
>     </activity>
> </application>
> <queries>
>   <package android:name="com.google.android.play.games" />
> </queries>
> ```

It would be great if the plugin added this directly
