### ISSUE TITLE
RealTimeReliableMessageSentListener for Unity as described for Android?

### ISSUE THREAD

**Issue by ViicEsquivel** [playgameservices/play-games-plugin-for-unity#1348]
Does unity have a RealTimeReliableMessageSentListener? as described on this documentation for Android? 

https://developers.google.com/games/services/android/api/com/google/android/gms/games/multiplayer/realtime/RealTimeReliableMessageSentListener

Something like onRealTimeMessageSent. Or a way to identify which player is having high latency or network problems?

I found the method RealtimeManager.InternalSendReliableMessageCallback, in the RealtimeManager.cs but I am not sure if this is already done somewhere else in a non internal way

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
