### ISSUE TITLE
Realtime Multiplayer - Unreliable messages not received but reliable are

### ISSUE THREAD

**Issue by Leuthil** [playgameservices/play-games-plugin-for-unity#1349]
In summary I am calling:

```
PlayGamesPlatform.Instance.RealTime.SendMessageToAll(false, packetData);
Debug.Log("Sending ball states packet with " + ballStates.Length + " ball states");
```

and I never receive any messages on the other connected clients. As soon as I change it to be sent reliably with:

```
PlayGamesPlatform.Instance.RealTime.SendMessageToAll(true, packetData);
Debug.Log("Sending ball states packet with " + ballStates.Length + " ball states");
```

then I start to receive the messages in the `public void OnRealTimeMessageReceived(bool isReliable, string senderId, byte[] data)` method. I'm not even sure how to debug this. There are no errors or any odd debug statements in the logcat. It almost seems like it is not even attempting to send the messages when it is marked to be sent unreliably.

I'm just wondering if I'm missing something obvious here...

Here is the log when it is successful (using reliable):

> 08-29 23:07:45.960 16122 16230 E GamesNativeSDK: Sending reliable message SUCCEEDED
> 08-29 23:07:45.974  8551 16209 I libjingle: IbbDataTask::ProcessStart() called:
> 08-29 23:07:45.974  8551 16209 I libjingle: Got Xmpp data back: <ibb:data ibb:seq="0" ibb:sid="52" xmlns:ibb="http://jabber.org/protocol/ibb"/>
> 08-29 23:07:45.975  8551 16209 I libjingle: static void gtalk::LibjingleJniHelper::DispatchIbbSendResult(jobject, const string&, const string&, bool): Dispatch ID:52
> 08-29 23:07:45.977  8551 16209 I libjingle: IbbDataTask::ProcessStart() called:
> 08-29 23:07:45.985 16122 16198 I Unity   :  [Play Games Plugin DLL] 08/29/16 23:07:45 -04:00 DEBUG: Entering internal callback for InternalSendReliableMessageCallback VALID
> 08-29 23:07:45.985 16122 16198 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
> 08-29 23:07:45.985 16122 16198 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> 08-29 23:07:45.985 16122 16198 I Unity   : UnityEngine.Logger:Log(LogType, Object)
> 08-29 23:07:45.985 16122 16198 I Unity   : UnityEngine.Debug:Log(Object)
> 08-29 23:07:45.985 16122 16198 I Unity   : GooglePlayGames.OurUtils.Logger:d(String) (at F:\linguinegames\BasketballMultiplayer\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
> 08-29 23:07:45.985 16122 16198 I Unity   : GooglePlayGames.Native.PInvoke.RealtimeManager:InternalSendReliableMessageCallback(MultiplayerStatus, IntPtr) (at F:\linguinegames\BasketballMultiplayer\Assets\GooglePlayGames\Platforms\Native\PInvoke\RealtimeManager.cs:185)
> 08-29 23:07:45.985 16122 16198 I Unity   :  
> 08-29 23:07:45.985 16122 16198 I Unity   : (Filename: F Line: 0)
> 08-29 23:07:45.985 16122 16198 I Unity   : 
> 08-29 23:07:46.010  8551 16209 I libjingle: IbbDataTask::ProcessStart() called:
> 08-29 23:07:46.011  8551 16209 I libjingle: [1/4] Got Xmpp DATA: <ibb:data ibb:seq="0" ibb:sid="53" xmlns:ibb="http://jabber.org/protocol/ibb">AAEAAAD/////AQAAAAAAAAAMAgAAAA9Bc3NlbWJseS1DU2hhcnAFAQAAABBCYWxsU3RhdGVzUGFja2V0AQAAAApiYWxsU3RhdGVzBAtCYWxsU3RhdGVbXQIAAAACAAAACQMAAAAHAwAAAAABAAAAQAAAAAQJQmFsbFN0YXRlAgAAAAkEAAAACQUAAAAJBgAAAAkHAAAACQgAAAAJCQAAAAkKAAAACQsAAAAJDAAAAAkNAAAACQ4AAAAJDwAAAAkQAAAACREAAAAJEgAAAAkTAAAACRQAAAAJFQAAAAkWAAAACRcAAAAJGAAAAAkZAAAACRoAAAAJGwAAAAkcAAAACR0AAAAJHgAAAAkfAAAACSAAAAAJIQAAAAkiAAAACSMAAAAJJAAAAAklAAAACSYAAAAJJwAAAAkoAAAACSkAAAAJKgAAAAkrAAAACSwAAAAJLQAAAAkuAAAACS8AAAAJMAAAAAkxAAAACTIAAAAJMwAAAAk0AAAACTUAAAAJNgAAAAk3AAAACTgAAAAJOQAAAAk6AAAACTsAAAAJPAAAAAk9AAAACT4AAAAJPwAAAAlAAAAACUEAAAAJQgAAAAlDAAAABQQAAAAJQmFsbFN0YXRlBQAAAAhzZXF1ZW5jZQdyZXNwYXduBHBvc1gEcG9zWQhyb3RhdGlvbgAAAAAADwELCwsCAAAANgAAAAC2foFAAACgwAAAAAABBQAAAAQAAAA3AAAAALZ+gUAAAKDAAAAAAAEGAAAABAAAADgAAAAAtn6BQAAAoMAAAAAAAQcAAAAEAAAAOQAAAAC2foFAAACgwAAAAAABCAAAAAQAAAA6AAAAALZ+gUAAAKDAAAAAAAEJAAAABAAAADsAAAA
> 08-29 23:07:46.011  8551 16209 I libjingle: [2/4] Atn6BQAAAoMAAAAAAAQoAAAAEAAAAPAAAAAC2foFAAACgwAAAAAABCwAAAAQAAAA9AAAAALZ+gUAAAKDAAAAAAAEMAAAABAAAAD4AAAAAtn6BQAAAoMAAAAAAAQ0AAAAEAAAAPwAAAAC2foFAAACgwAAAAAABDgAAAAQAAABAAAAAALZ+gUAAAKDAAAAAAAEPAAAABAAAAEEAAAAAtn6BQAAAoMAAAAAAARAAAAAEAAAAQgAAAAC2foFAAACgwAAAAAABEQAAAAQAAABDAAAAALZ+gUAAAKDAAAAAAAESAAAABAAAAEQAAAAAtn6BQAAAoMAAAAAAARMAAAAEAAAARQAAAAC2foFAAACgwAAAAAABFAAAAAQAAABGAAAAALZ+gUAAAKDAAAAAAAEVAAAABAAAAEcAAAAAtn6BQAAAoMAAAAAAARYAAAAEAAAASAAAAAC2foFAAACgwAAAAAABFwAAAAQAAABJAAAAALZ+gUAAAKDAAAAAAAEYAAAABAAAAEoAAAAAtn6BQAAAoMAAAAAAARkAAAAEAAAASwAAAAC2foFAAACgwAAAAAABGgAAAAQAAABMAAAAALZ+gUAAAKDAAAAAAAEbAAAABAAAAE0AAAAAtn6BQAAAoMAAAAAAARwAAAAEAAAATgAAAAC2foFAAACgwAAAAAABHQAAAAQAAABPAAAAALZ+gUAAAKDAAAAAAAEeAAAABAAAAFAAAAAAtn6BQAAAoMAAAAAAAR8AAAAEAAAAUQAAAAC2foFAAACgwAAAAAABIAAAAAQAAABSAAAAALZ+gUAAAKDAAAAAAAEhAAAABAAAAFMAAAAAtn6BQAAAoMAAAAAAASIAAAAEAAAAVAAAAAC2foFAAACgwAAAAAABIwAAAAQAAABVAAAAALZ+gUAAAKDAAAAAAAEkAAAABAAAAFYAAAAAtn6BQAAAoMAAAAAAASUAAAAEAAA
> 08-29 23:07:46.011  8551 16209 I libjingle: [3/4] AVwAAAAC2foFAAACgwAAAAAABJgAAAAQAAABYAAAAALZ+gUAAAKDAAAAAAAEnAAAABAAAAFkAAAAAtn6BQAAAoMAAAAAAASgAAAAEAAAAWgAAAAC2foFAAACgwAAAAAABKQAAAAQAAABbAAAAALZ+gUAAAKDAAAAAAAEqAAAABAAAAFwAAAAAtn6BQAAAoMAAAAAAASsAAAAEAAAAXQAAAAC2foFAAACgwAAAAAABLAAAAAQAAABeAAAAALZ+gUAAAKDAAAAAAAEtAAAABAAAAF8AAAAAtn6BQAAAoMAAAAAAAS4AAAAEAAAAYAAAAAC2foFAAACgwAAAAAABLwAAAAQAAABhAAAAALZ+gUAAAKDAAAAAAAEwAAAABAAAAGIAAAAAtn6BQAAAoMAAAAAAATEAAAAEAAAAYwAAAAC2foFAAACgwAAAAAABMgAAAAQAAABkAAAAALZ+gUAAAKDAAAAAAAEzAAAABAAAAGUAAAAAtn6BQAAAoMAAAAAAATQAAAAEAAAAZgAAAAC2foFAAACgwAAAAAABNQAAAAQAAABnAAAAALZ+gUAAAKDAAAAAAAE2AAAABAAAAGgAAAAAtn6BQAAAoMAAAAAAATcAAAAEAAAAaQAAAAC2foFAAACgwAAAAAABOAAAAAQAAABqAAAAALZ+gUAAAKDAAAAAAAE5AAAABAAAAGsAAAAAtn6BQAAAoMAAAAAAAToAAAAEAAAAbAAAAAC2foFAAACgwAAAAAABOwAAAAQAAABtAAAAALZ+gUAAAKDAAAAAAAE8AAAABAAAAG4AAAAAtn6BQAAAoMAAAAAAAT0AAAAEAAAAbwAAAAC2foFAAACgwAAAAAABPgAAAAQAAABwAAAAALZ+gUAAAKDAAAAAAAE/AAAABAAAAHEAAAAAtn6BQAAAoMAAAAAAAUAAAAAEAAAAcgAAAAC2foFAAACgwAAAAAABQQA
> 08-29 23:07:46.011  8551 16209 I libjingle: [4/4] AAAQAAABzAAAAALZ+gUAAAKDAAAAAAAFCAAAABAAAAHQAAAAAtn6BQAAAoMAAAAAAAUMAAAAEAAAAdQAAAAC2foFAAACgwAAAAAAL/ibb:data
> 08-29 23:07:46.018  8551 16209 I libjingle: IbbDataTask::ProcessStart() called:
> 08-29 23:07:46.024 16122 16198 I Unity   :  [Play Games Plugin DLL] 08/29/16 23:07:46 -04:00 DEBUG: Entering InternalOnDataReceived: 35
> 08-29 23:07:46.024 16122 16198 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
> 08-29 23:07:46.024 16122 16198 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> 08-29 23:07:46.024 16122 16198 I Unity   : UnityEngine.Logger:Log(LogType, Object)
> 08-29 23:07:46.024 16122 16198 I Unity   : UnityEngine.Debug:Log(Object)
> 08-29 23:07:46.024 16122 16198 I Unity   : GooglePlayGames.OurUtils.Logger:d(String) (at F:\linguinegames\BasketballMultiplayer\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
> 08-29 23:07:46.024 16122 16198 I Unity   : GooglePlayGames.Native.PInvoke.RealTimeEventListenerHelper:InternalOnDataReceived(IntPtr, IntPtr, IntPtr, UIntPtr, Boolean, IntPtr) (at F:\linguinegames\BasketballMultiplayer\Assets\GooglePlayGames\Platforms\Native\PInvoke\RealTimeEventListenerHelper.cs:171)
> 08-29 23:07:46.024 16122 16198 I Unity   :  
> 08-29 23:07:46.024 16122 16198 I Unity   : (Filename: F Line: 0)
> 08-29 23:07:46.024 16122 16198 I Unity   : 
> 08-29 23:07:46.036 16122 16230 E GamesNativeSDK: Sending reliable message
> **08-29 23:07:46.038 16122 16141 I Unity   : Sending ball states packet with 64 ball states**
> 08-29 23:07:46.038 16122 16141 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
> 08-29 23:07:46.038 16122 16141 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> 08-29 23:07:46.038 16122 16141 I Unity   : UnityEngine.Logger:Log(LogType, Object)
> 08-29 23:07:46.038 16122 16141 I Unity   : UnityEngine.Debug:Log(Object)
> 08-29 23:07:46.038 16122 16141 I Unity   : GameManager:CreateAndSendBallStatesPacket() (at F:\linguinegames\BasketballMultiplayer\Assets\Scripts\GameManager.cs:469)
> 08-29 23:07:46.038 16122 16141 I Unity   : GameManager:SendPlayerBallUpdates() (at F:\linguinegames\BasketballMultiplayer\Assets\Scripts\GameManager.cs:446)
> 08-29 23:07:46.038 16122 16141 I Unity   : GameManager:OnNetworkTick() (at F:\linguinegames\BasketballMultiplayer\Assets\Scripts\GameManager.cs:419)
> 08-29 23:07:46.038 16122 16141 I Unity   : GameManager:FixedUpdate() (at F:\linguinegames\BasketballMultiplayer\Assets\Scripts\GameManager.cs:94)

And when I try unreliable (and unsuccessful):

> 08-29 21:53:09.725 11000 11018 I Unity   : (Filename: F Line: 0)
> 08-29 21:53:09.725 11000 11018 I Unity   : 
> **08-29 21:53:09.833 11000 11018 I Unity   : Sending ball states packet with 64 ball states**
> 08-29 21:53:09.833 11000 11018 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
> 08-29 21:53:09.833 11000 11018 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> 08-29 21:53:09.833 11000 11018 I Unity   : UnityEngine.Logger:Log(LogType, Object)
> 08-29 21:53:09.833 11000 11018 I Unity   : UnityEngine.Debug:Log(Object)
> 08-29 21:53:09.833 11000 11018 I Unity   : GameManager:CreateAndSendBallStatesPacket() (at F:\linguinegames\BasketballMultiplayer\Assets\Scripts\GameManager.cs:465)
> 08-29 21:53:09.833 11000 11018 I Unity   : GameManager:SendPlayerBallUpdates() (at F:\linguinegames\BasketballMultiplayer\Assets\Scripts\GameManager.cs:442)
> 08-29 21:53:09.833 11000 11018 I Unity   : GameManager:OnNetworkTick() (at F:\linguinegames\BasketballMultiplayer\Assets\Scripts\GameManager.cs:414)
> 08-29 21:53:09.833 11000 11018 I Unity   : GameManager:FixedUpdate() (at F:\linguinegames\BasketballMultiplayer\Assets\Scripts\GameManager.cs:94)
> 08-29 21:53:09.833 11000 11018 I Unity   :  
> 08-29 21:53:09.833 11000 11018 I Unity   : (Filename: F Line: 0)
> 08-29 21:53:09.833 11000 11018 I Unity   : 
> **08-29 21:53:09.932 11000 11018 I Unity   : Sending ball states packet with 64 ball states**
> 08-29 21:53:09.932 11000 11018 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
> 08-29 21:53:09.932 11000 11018 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> 08-29 21:53:09.932 11000 11018 I Unity   : UnityEngine.Logger:Log(LogType, Object)
> 08-29 21:53:09.932 11000 11018 I Unity   : UnityEngine.Debug:Log(Object)
> 08-29 21:53:09.932 11000 11018 I Unity   : GameManager:CreateAndSendBallStatesPacket() (at F:\linguinegames\BasketballMultiplayer\Assets\Scripts\GameManager.cs:465)
> 08-29 21:53:09.932 11000 11018 I Unity   : GameManager:SendPlayerBallUpdates() (at F:\linguinegames\BasketballMultiplayer\Assets\Scripts\GameManager.cs:442)
> 08-29 21:53:09.932 11000 11018 I Unity   : GameManager:OnNetworkTick() (at F:\linguinegames\BasketballMultiplayer\Assets\Scripts\GameManager.cs:414)
> 08-29 21:53:09.932 11000 11018 I Unity   : GameManager:FixedUpdate() (at F:\linguinegames\BasketballMultiplayer\Assets\Scripts\GameManager.cs:94)
> 08-29 21:53:09.932 11000 11018 I Unity   :  
> 08-29 21:53:09.932 11000 11018 I Unity   : (Filename: F Line: 0)
> 08-29 21:53:09.932 11000 11018 I Unity   :

**Comment by Leuthil** [comment]
I just tried the QuizRacers sample scene and it also does not seem to be working for me. I can only assume it is because the Unreliable messages are not sending since I was able to successfully connect to the match with another player but the online gameplay itself was not working.

**Comment by Leuthil** [comment]
I still haven't figured out the true problem but I have a temporary workaround where I use SendMessage instead of SendMessageToAll. For some reason that way works.

**Comment by MadeForThisCommment** [comment]
I have been having what I think is the exact same problem but using your temporary workaround didn't seem to work the same debug of Entering InternalOnDataRecieved 35 happens

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
