### ISSUE TITLE
Error Signing In After Updating to Version 9.02

### ISSUE THREAD

**Issue by rachel-rp** [playgameservices/play-games-plugin-for-unity#135]
I updated to the latest plugin version and I receive the following errors after trying to sign in on an Android device. With plugin version 9.01, I have no issues.

05-28 11:09:01.015: I/Unity(12961): AndroidJavaException: java.lang.NoSuchMethodError: no method with name='setGamesApiOptions' signature='(Lcom.google.android.gms.games.Games$GamesOptions;)V' in class Lcom/google/example/games/basegameutils/GameHelper;
05-28 11:09:01.015: I/Unity(12961):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
05-28 11:09:01.015: I/Unity(12961):   at UnityEngine.AndroidJNISafe.GetMethodID (IntPtr obj, System.String name, System.String sig) [0x00000] in <filename unknown>:0 
05-28 11:09:01.015: I/Unity(12961):   at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0 
05-28 11:09:01.015: I/Unity(12961):   at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr javaClass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0 
05-28 11:09:01.015: I/Unity(12961):   at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.Object[] args, Boolean isStatic) [0x00000] in <filename unknown>:0 
05-28 11:09:01.015: I/Unity(12961):   at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, S

05-28 11:09:01.025: I/Unity(12961): NullReferenceException: Object reference not set to an instance of an object
05-28 11:09:01.025: I/Unity(12961):   at GooglePlayGames.Android.AndroidClient+<Authenticate>c__AnonStoreyB.<>m__1 () [0x00000] in /Users/rachel/Documents/UnityProject/Assets/GooglePlayGames/Platforms/Android/AndroidClient.cs:114 
05-28 11:09:01.025: I/Unity(12961):   at UnityEngine.AndroidJavaRunnableProxy.run () [0x00000] in <filename unknown>:0 
05-28 11:09:01.025: I/Unity(12961):   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
05-28 11:09:01.025: I/Unity(12961): Rethrow as TargetInvocationException: UnityEngine.AndroidJavaRunnableProxy.run()
05-28 11:09:01.025: I/Unity(12961):   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
05-28 11:09:01.025: I/Unity(12961):   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, UnityEngine.AndroidJavaObject[] javaArgs) [0x00000] in <filename unknown>:0 
05-28 11:09:01.025: I/Unity(12961):   at UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy pro

**Comment by claywilkinson** [comment]
This is obsolete since the newer plugin is architected differently.
