### ISSUE TITLE
Something's wrong

### ISSUE THREAD

**Issue by Danwakon** [playgameservices/play-games-plugin-for-unity#1351]
When I build and run my new game on my android phone it is not showing anything when I try to login or
show achievements or leaderboards. I've already made a game with game services and everything worked fine. I did exactly the same with this game but it's not working. The strange thing is that I do receive a request in the API manager. I also compared the files in my other game and the difference with this one  are the files in the Plugin/Android folder. The working game has files ending with 9.0.0 and the new game 9.4.0. That's the only thing I found out. The player settings are all correct. APK is uploaded and connected to the Game Services correctly. Did Resolve Client Jars. Installed everything needed in SDK manager.  I really don't know what to do.  I hope there's someone who does.

**Comment by claywilkinson** [comment]
Can you share a log of when you are calling Authenticate?

**Comment by claywilkinson** [comment]
Please re-open or open a new issue when you have more information such as a log.
