### ISSUE TITLE
Newbie Support 

### ISSUE THREAD

**Issue by ambs** [playgameservices/play-games-plugin-for-unity#1352]
Sorry for using issues to request help, but I am quite lost. As a side suggestion, it might be handy to create a google groups or other chat service for people to discuss this.

In any case, I am trying two simple things.
- First, simple authentication. I question myself if this is working because it always succeeds, even when running under the editor, where no Google account is available.
- Second, every damn time I try to unlock an achievement, it complains that the ID is invalid. It comes from the IDs generated file, so I have no clue on what is going on.

Any help or links of things i might be missing are very welcome.

**Comment by claywilkinson** [comment]
Have you tried to build the samples?  That is a good place to start.  Read the instructions for setting them up and how to configure them.  If you are still having problems when running, use logcat to capture a log of the app running on the device.  The log usually has some valuable messages in it that will point you to where you are going astray.

As far as Authentication always succeeding, what are you looking at to determine that it succeeded?  This plugin does not work in the editor, all the methods should fail.

The Achievement IDs come from the resource file that is copied and pasted from the Play Developer Console for your game.  You should paste it into the Setup dialog for this plugin, and then you can reference the IDs by a variable which is a member of a class that is generated during setup.

**Comment by ambs** [comment]
Let me explain better what I mean, with some code:

`````
using GooglePlayGames;
using UnityEngine.SocialPlatforms;

public class UserData : MonoBehaviour {
  	void Start() {

        Social.localUser.Authenticate((bool success) => {
            Debug.Log("Authentication result was " + success.ToString());
        }
 }
```````
This prints always 'Authentication result was True', both when running in he editor or on genymotion.

For the achievement, as they are automatically generated, i use some Reflection, but it should work...

````
        var field = typeof(GPSLB).GetField(achievement);
        var googlecode = field.GetValue(field).ToString();
        Social.ReportProgress(googlecode, 100.0f, (bool success) => {
            Debug.Log("Achievement " + googlecode + " result was " + success.ToString());
        });
`````
Here, GPSLB is the class generated by pasting the XML into the plugin. The achievement variable has the achievement name `achievement_foo`. The googlecode printed in the Log is correct (is the ID generated by the Google Console). But the `success` variable is always false.

Does this help?

Looking to logcat I didn't see anything weird (well, lot of weird things, but nothing I could relate with google games). I didn't try the samples, sorry, but I will look into them now.

Thanks

**Comment by ambs** [comment]
Probably I am just missing calling `PlayGamesPlatform.Activate();` Will try after lunch.

**Comment by ambs** [comment]
Well, yeah, it helped :-) Will close this issue and call back when I hit another wall.
Thanks for your help.
