### ISSUE TITLE
GIDSignIn.h not found on iOS build with NO_GPGS

### ISSUE THREAD

**Issue by ascmt** [playgameservices/play-games-plugin-for-unity#1353]
The GPGS Unity plugin does not fully respect the NO_GPGS flag, still leaving Google framework references in iOS XCode projects.

Details: I have integrated the Google Play Game Services Unity 0.9.34 plugin into my project in Unity version 5.3.4 for Android only, and am using the NO_GPGS flag for iOS builds.  After upgrading to Unity 5.4, I am now receiving the GIDSignIn.h file-not-found compile error when compiling in XCode for iOS on some (not all) OSX machines.

Is there a workaround or fix available?

**Comment by gurveenk** [comment]
Go to Build Setting and Install Module for IOS. Don't use it you don't want to just Install the module. I had this same issue with version 0.9.21.

**Comment by ascmt** [comment]
This issue Heisenbug'ed on me after having reproduced it a dozen times on clean builds.  The only change was that I accidentally told Unity to build an Android project on the OSX machine, when no Android SDK was installed there, resulting in a failed build.  Perhaps that had some positive side effect, because now the iOS build on that machine does seem to respect NO_GPGS, and there are no more Google framework references in the XCode project.

**Comment by claywilkinson** [comment]
Thanks for the followup.
