### ISSUE TITLE
Leaderboard causing game to crash.

### ISSUE THREAD

**Issue by gurveenk** [playgameservices/play-games-plugin-for-unity#1356]
Hi, I'm using UNITY 5.4.0f3 64bit.

**Leader board is causing application to close**. When I open leaderboard and then close it the game crashes. And when I start the game again, I am already signed in and the game crashes with few seconds unless I start the game again and tap on signout button before it crashes.

I did everything shown on the link - https://codelabs.developers.google.com/codelabs/playservices_unity/index.html#0

And the Lollygagger game worked fine but not mine. Firstly I added everything shown on that tutorial in my game. And the game actually worked. Signing in an out worked, I was able to get achievements and update score to leaderboard.

But then i discovered the BUG. If I signin and open leaderboard and then close the leaderboard, the game crashes. Unless I reopens the game and signout before it crashes again.

**How can I say that leaderboard is the cause?**
I did step by step checking.
First- I checked the normal backup copy of my game without any GooglePlayService and it worked fine.

Second- I added **sign-in and sign-out functionality** and the game worked fine. I was able to sign in and restart the game and everything worked fine.

Third (buggy part)- I added Leaderboard -( **View Leaderboard Option only** not _Updating Leaderboard Part_) and the problem started to show. **Note that I only added signin functionality just as shown in the tutorial and Leaderboard's show leaderboard part only**.

Now when I open the leaderboard and closses it, the game crashes. I restart the game and I am already signed in, the game still crashes within 1 - 2 seconds. No matter how many times I start the game it crashes unless I reopens in and tap on singout button before it crashes.

Please help me out. I read on many forums that 0.9.27 version has trouble with leaderboard but I am using latest 0.9.34. I read that people having issues like this turned back to version 0.9.26 and it worked for them.

I also tries using version 0.9.21 but it shows lots of error in Unity like  - 
`Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs(174,17): error CS0104:`Logger' is an ambiguous reference between `UnityEngine.Logger' and`GooglePlayGames.OurUtils.Logger'` I resolved  this one but still many like which can't be solved as of new version of Google Play Services SDK.

Please help me resolve this **Leaderboard** issue and please tell me from where can I get **version 0.9.26**, can't find it.

Thanks. May God Bless Us All.

**Comment by gurveenk** [comment]
I removed the silent sign-in code - `
        PlayGamesPlatform.Instance.Authenticate(SignInCallback, true);`
And now game does not closes itself as used is signed out by default.

But game still crashes mostly when score report code is called and sometimes crashes randomly.

Please tell me where i can find version 0.9.26?

**Comment by claywilkinson** [comment]
I recommend using the latest version of the plugin: 0.9.36
