### ISSUE TITLE
Update Leaderboard misleading result

### ISSUE THREAD

**Issue by NikitaVr** [playgameservices/play-games-plugin-for-unity#1357]
There is a problem when trying to update a leaderboard with an invalid leaderboard ID.

Here is the code:

```
Social.ReportScore(score, leaderboardCode, (bool result) => {
                Debug.Log("Leaderboard update result:" + result);
                Debug.Log("Finished Updating Leaderboard");
            });
```

The problem is that `result` is returned as true when the leaderboard ID actually does not exist, due to something such as a typo.

For example a leaderboard ID is "abc" and I was using"abc ". This still returns true even though it should not work.

I am not sure if this is an issue with this plugin or with unity built in social api, or maybe even google play services.

Let me know if it is out of the scope of this plugin and I will find where else to notify devs of this.

**Comment by claywilkinson** [comment]
Can you share the log of the reporting of a score to an invalid leaderboard?

**Comment by ozdemir08** [comment]
Closing this bug now. Feel free to reopen it if you still have problems.
