### ISSUE TITLE
Need link to version 0.9.26

### ISSUE THREAD

**Issue by gurveenk** [playgameservices/play-games-plugin-for-unity#1358]
I use UNITY 5x and having game crashing problem while using SignIn and Leaderboard.
I read in many posts that version 0.9.26 works fine with Unity 5.3 and 5.4.
Right now I tries using version 0.9.21, 0.9.33, 0.9.34 but none worked.

Please provide me with link of version 0.9.26. Thanks You.

**Comment by DaveMariner** [comment]
You can find it here: [https://github.com/playgameservices/play-games-plugin-for-unity/blob/af5a4d943d4f72ed9258ce542844201d9a548665/current-build/GooglePlayGamesPlugin-0.9.26.unitypackage](url)

Any other version you want, you can also find by browsing the history of the commits in the folder "play-games-plugin-for-unity/current-build/"

**Comment by DaveMariner** [comment]
Apparently the link 404s if you click on it. Try this instead: commit 443eb1ad644d4cac2af621cd8e93d0dffa43514a

If all else fails, you can find the file you want by browsing back through the commit history and looking for the following: 

**Committing automated building of packages**
Google Automerger committed on Oct 25, 2015

Hope this helps

**Comment by gurveenk** [comment]
I found it. Link is working, there is a download option there. I downloaded it.
Thanks a lot.
