### ISSUE TITLE
Turn off Achievement Banner in Android

### ISSUE THREAD

**Issue by nickersonr** [playgameservices/play-games-plugin-for-unity#1359]
Is it possible to turn off the achievement notification banner programmatically to avoid spamming my users with them and distracting from the game?

Games.setViewForPopups exists but we are not sure how to interfaces in c# vs the native android way of doing it.

This should be possible, but we're not sure how.

**Comment by claywilkinson** [comment]
Thanks for the feedback.  Currently  setViewForPopups is part of the C++ SDK which this plugin is based on.  I'll pass the request along.

**Comment by claywilkinson** [comment]
You can now suppress the popups by calling  [`PlayGamesClientConfiguration.EnableHidePopups ()`](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/BasicApi/PlayGamesClientConfiguration.cs#L279)
