### ISSUE TITLE
Do i need to published it in Google Game Services?

### ISSUE THREAD

**Issue by jaybatalla** [playgameservices/play-games-plugin-for-unity#1363]
Do i need to published it first before i can test it on my android phone? Or will i install it manually on my phone?

**Comment by NikitaVr** [comment]
@jaybatalla You need to just set up the services and link it to your game, and also add the email you are using to the list of testers, but the game and the service does not need to be published, it only needs to say `Ready to test` around the top right.

Source: It Works for me :P

**Comment by muafakul** [comment]
you have to publish the game ,,, the bugs is the leaderboard wont showing public score, cry

**Comment by jaybatalla** [comment]
@NikitaVr  i already published my game in Google Play so i erased all the testers because it is already live,  the problem is the players can't access the leaderboard, i still need to put their name on the testers. How can i make it work for all the players without putting their name in the testers?

**Comment by NikitaVr** [comment]
@muafakul The game does not need to be published for testing. It is working fine for me without publishing

**Comment by NikitaVr** [comment]
@jaybatalla I haven't gotten around to publishing just yet, but I can try and help. Have you published the games services as well? Because publishing the game and the services are two separate actions.

**Comment by claywilkinson** [comment]
Please reopen if this issue is still a problem.
