### ISSUE TITLE
Leaderboard not showing

### ISSUE THREAD

**Issue by bodhish** [playgameservices/play-games-plugin-for-unity#1366]
I have used the code   Social.ShowLeaderboardUI();
its not showing the leaderboad.
help

**Comment by muafakul** [comment]
sameeeeeeeee assssss tooooooooooooooo meeeeeeeeeeeeeee!!!!!!!!!!!!!!!

**Comment by soniyj** [comment]
I'm having the same problem, also reporting the score gives me always false!

**Comment by claywilkinson** [comment]
@bodhish  - Can you share the log of not showing the leaderboard?

@soniyj  - can you open a separate issue about reporting the score being false and include the log ?

**Comment by soniyj** [comment]
Hi @claywilkinson no problem in order to open a new issue, but what log? This plugin doesn't give the error section but just success so what I have to insert as a log?

**Comment by claywilkinson** [comment]
When you run the application on a device, you can use [logcat](https://developer.android.com/studio/command-line/logcat.html) to capture the log messages from the application.

**Comment by soniyj** [comment]
Hi @claywilkinson I will give it a go as soon as I have time, do you have any suggestion how to intercept the log from the game? logcat it's not one of my bestie. thanks.
