### ISSUE TITLE
Confusing built in invite UI.

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#1369]
![screenshot_20160908-1002532](https://cloud.githubusercontent.com/assets/10234700/18354771/1f0aed76-75e7-11e6-8846-7792797c8123.jpg)

A lot of my users get confused when they are trying to use the invite UI. Especially in the following scenario:

Lets say Bennys friend Jim has messed and said he has the Gamer ID "SuperHero123" and they want to play a new fun game together. Benny then open the built in invite UI but uses the wrong search function (marked as "1" in the image). Ofcourse, since they are not Gamer ID friends yet, that results has no matches... Benny gets irritated and they end up playing another game...

A lot of my users have never used google play games before (or at least not the built in UI functions). They often dont have a lot of friends to invite and thats why the other search option (marked as "2") is so important to see and understand.

I think its important to make that search option much more visable and add some text like: "Gamer ID search".  In my opinion it should be at least equally visable as search function "1"

I know this really isnt an issue with this github plugin, but Clay Wilkinson have sent some of my suggestions in the passed to the right people on Google.

//Erik

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
