### ISSUE TITLE
Warning: Unreachable Code Detected in GPGSUpgrader.cs:195

### ISSUE THREAD

**Issue by ascmt** [playgameservices/play-games-plugin-for-unity#1371]
Please fix the following warning present in 0.9.34 of the Unity package:

Warning	CS0162	Unreachable code detected	Assets\GooglePlayGames\Editor\GPGSUpgrader.cs	195	

The offending code is comparing two equivalent const strings from the same source file against each other for some strange reason.

In the future, please refrain from releasing code with compilation warnings.

**Comment by claywilkinson** [comment]
Thanks for the feedback.

**Comment by claywilkinson** [comment]
Fixed in 0.9.35
