### ISSUE TITLE
Get leaderboard data

### ISSUE THREAD

**Issue by jaybatalla** [playgameservices/play-games-plugin-for-unity#1373]
Is there a way to get leaderboard data and display it to the screen while you are playing the game without going to the leaderboarrd UI?

**Comment by muafakul** [comment]
google is error bro ,,bug

**Comment by claywilkinson** [comment]
You can call [PlayGamesPlatform.Instance.LoadScores()](https://github.com/playgameservices/play-games-plugin-for-unity#using-playgamesplatformloadscores) to load scores directly, or use the ISocialLeaderboard interface.
