### ISSUE TITLE
Links in the readme file doesnt work as expected

### ISSUE THREAD

**Issue by wayne2k** [playgameservices/play-games-plugin-for-unity#1374]
on the main page
Under the Overview section for the README.md links to the following dont work
nearby connections
turn-based multiplayer
real-time multiplayer

I have to go to https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/README.md  then the links to those readme files work

**Comment by claywilkinson** [comment]
Thanks for the feedback.  What is the URL that the main page takes you to for nearby connections?  Mine seems to work OK from the main page it takes me to:  https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/NEARBY.md

**Comment by wayne2k** [comment]
It started working a day or so after i added the issue. sorry i didnt send an update on the issue. 
Maybe is was a bug with github or the browser.

**Comment by claywilkinson** [comment]
Thanks for following up! Glad it is working.
