### ISSUE TITLE
Opening cloud save takes a long time on device

### ISSUE THREAD

**Issue by ChrisTrueman** [playgameservices/play-games-plugin-for-unity#1381]
I'm not sure if this is an issue with the plugin or the device. I have a user that has very long loading times on his device. It can take 30 secs or more when offline and even more when online. He has also told me that his device is quite full and has resorted to using an sd card for additional storage, I'm not sure if that is the cause of the issue and could use some clarification. Everything seems to work fine when the app loads the local information that I save separate from the plug in, so it doesn't take long to get information from the device. 

Is this expected behavior on a near full device or is it a bug?

**Comment by Fortis9777** [comment]
The same for me. Opening of SavedGame takes much time

**Comment by ChrisTrueman** [comment]
No one else has reported the issue and on my test devices it works relatively fast. I think it might be a caching issue or something when there isn't much room left on the device. I have seen this happen with near full hard drives. Too much info to go through, not enough room to swap things around, depending on the process it can run really slow. Thinking this is the case here, but I need more people to be using cloud saving to really see if it is an issue or at least people that will report it.

**Comment by SeanLangre** [comment]
We have this issue aswell, or it might be [stuck in server loop](https://github.com/playgameservices/play-games-plugin-for-unity/issues/1262) . Seems to be related to device though. On Nexus 5 it opens fast (1-3 seconds)

**Comment by Fortis9777** [comment]
Actually, sometimes it opens fans. But sometime it takes much time, or, even, callback is never called.
Could it be bug of Android API or GPG plugin?

**Comment by yisharsr** [comment]
Same here, I have a lot of users reporting long loading times when the game saves data to the cloud. On our test device (nexus 7) it happens rarely, but happens.

**Comment by claywilkinson** [comment]
Closing this one, I do believe there was several issues in September.  Please open a new issue including the logfile, and version of Unity if you experience this again.
