### ISSUE TITLE
Could not register one or more required Java classes.

### ISSUE THREAD

**Issue by Fortis9777** [playgameservices/play-games-plugin-for-unity#1382]
Hi! When I`ve updated Unity to 5.4 (last update 5.4.0p4) and Play Games Plugin to 0.9.34, my app can`t connect to Google Play Games. GamesNativeSDK logs:

E/GamesNativeSDK(26739): Can't register class com/google/android/gms/games/multiplayer/ParticipantResult: an exception occurred.

E/GamesNativeSDK(26739): Can't register class com/google/android/gms/nearby/connection/AppIdentifier: an exception occurred.

E/GamesNativeSDK(26739): Can't register class com/google/android/gms/nearby/connection/AppMetadata: an exception occurred.

E/GamesNativeSDK(26739): Could not register one or more required Java classes.

That`s it. I`ve tried everything - removed plugin, updated all libs in Android SDK Manager, removed Android/libs from project, imported plugin to the clean project. But nothing good for me!

All the time console logs this errors, which are above.

Could somebody help me?

**Comment by putyavka** [comment]
Absolutely the same problem. Occures just after PlayGamesPlatform.Instance.Authenticate invokation. I've disassembled jar-file inside play-services-games-9.6.1.aar to check what cause an exception in ParticipantResult. It is a descendent of com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable class that is implemented in play-services-basement-9.6.1.aar but NOT in version 8.4 of basement lib. I tried to replace it with new version in Plugin/Andoird folder but it cause another errors. Besides, GooglePlayGames plugin always ask to restore 8.4v of basement libs before each build.
It all seems like a bug inside the plugin. Probably it worked fine in previous version of 9+

**Comment by putyavka** [comment]
I found it strange that only **play-services-games** & **play-services-nearby** libs were upgraded to 9+ version but not **play-services-base** & **play-services-basement** (they are 8.4). I tried to force their upgrade via manual replacement in Plugin/Android folder. It helped a little and authorization stage was passed but crashed somewhere later. Probably the crash was just specific for my project

**Comment by Qbit86** [comment]
Any clues?

**Comment by Qbit86** [comment]
@putyavka Connected issue: <https://github.com/playgameservices/play-games-plugin-for-unity/issues/1411>

@putyavka Please let me know when you have solution.

@Fortis9777 Consider using apostrophe instead of back-tick, so Markdown won't break formatting of your text.

**Comment by claywilkinson** [comment]
All the .aar files need to be the same version.  The new version of the plugin 0.9.35, contains an updated resolver which will work much better.

**Comment by mohitatray** [comment]
Disable minification in player settings. It worked for me. It is probably a proguard issue. I think some proguard keep rules are needed for this plugin.
