### ISSUE TITLE
FileNotFoundException: Could not find file "MyProject\Temp\StagingArea\AndroidManifest.xml".

### ISSUE THREAD

**Issue by DaniDan23** [playgameservices/play-games-plugin-for-unity#1385]
Hello,

I'm making an Android game with Unity.
I wana use this plugin for the leaderboard. So my game is complete, I import the play-games-plugin into Unity, I setup it, the code is writed. But at the build time the following error appears : 

> FileNotFoundException: Could not find file "MyProject\Temp\StagingArea\AndroidManifest.xml".
> System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileStream.cs:305)
> System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share)
> (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
> System.Xml.XmlUrlResolver.GetEntity (System.Uri absoluteUri, System.String role, System.Type ofObjectToReturn)
> Mono.Xml2.XmlTextReader.GetStreamFromUrl (System.String url, System.String& absoluteUriString)
> Mono.Xml2.XmlTextReader..ctor (System.String url, System.Xml.XmlNameTable nt)
> System.Xml.XmlTextReader..ctor (System.String url, System.Xml.XmlNameTable nt)
> System.Xml.XmlTextReader..ctor (System.String url)
> UnityEditor.AndroidXmlDocument..ctor (System.String path)
> UnityEditor.AndroidManifest..ctor (System.String path)
> UnityEditor.Android.PostProcessor.Tasks.GenerateManifest.PatchManifest (UnityEditor.Android.PostProcessor.PostProcessorContext context, System.String manifest)
> UnityEditor.Android.PostProcessor.Tasks.GenerateManifest.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
> UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
> UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
> UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (BuildPostProcessArgs args)
> UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, System.String downloadWebplayerUrl, System.String manualDownloadWebplayerUrl, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.BuildReporting.BuildReport report) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:176)
> UnityEditor.HostView:OnGUI()

In the temp folder, there is only the AndroidManifest-main.xml who's created.

Versions : 
     Unity : 5.4.1.f1
     play-games-plugin : 0.9.34 (latest)
     Android sdk : 25.2.2 (with all packages installed and updated)

Thank's for your help.

**Comment by claywilkinson** [comment]
This looks like an issue for Unity - I'd suggest filing a bug report with them. I don't see anything related directly to this plugin.  Please re-open if you have more information.
