### ISSUE TITLE
Unable to build with Unity 5.4.1f1-GVR7

### ISSUE THREAD

**Issue by longngo78** [playgameservices/play-games-plugin-for-unity#1387]
ArgumentException: oldValue is the empty string.
System.String.Replace (System.String oldValue, System.String newValue) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/String.cs:1664)
UnityEditor.Android.PostProcessor.Tasks.NativePlugins.StripVersionFromFilename (System.String fileName, System.String ext)
UnityEditor.Android.PostProcessor.Tasks.NativePlugins.ProcessPlugin (UnityEditor.Android.PostProcessor.PostProcessorContext context, System.String pluginPath, System.String pluginTargetCPU)
UnityEditor.Android.PostProcessor.Tasks.NativePlugins.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (BuildPostProcessArgs args)
UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, System.String downloadWebplayerUrl, System.String manualDownloadWebplayerUrl, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.BuildReporting.BuildReport report) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:176)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

**Comment by v2k** [comment]
this looks similar to my issue https://github.com/playgameservices/play-games-plugin-for-unity/issues/1389

have you found a version of Unity that works?

**Comment by longngo78** [comment]
No, not really. I can play fine on Unity editor but fail to build for Android. I'll keep you posted if a solution is found.

**Comment by aykutuludag** [comment]
I have also same problem: http://stackoverflow.com/questions/39682311/commandinvokationfailure-unable-to-convert-classes-into-dex-format-in-unity

**Comment by longngo78** [comment]
Just to clarify, I only got this issue after upgrading from 5.4.1f1 to 5.4.1f1-GVR7 (Unity native support for Google Daydream VR). I don't think the issue you have with dexing above is the same. The main issue that causes the building process to stop is the folder Plugins/Android/MainLibProj/

The good news is that I found a temporary work-around and it works like a charm at the moment for me. If you can't wait for an official fix, do the following:

1. Merge the content in the Plugins/Android/MainLibProj/AndroidManifest.xml into your app's AndroidManifest.xml (Plugins/Android/AndroidManifest.xml)
2. Move the Plugins/Android/MainLibProj/libs/play-games-plugin-support.jar into Plugins/Android/libs/
3. Completely remove folder Plugins/Android/MainLibProj

Good Luck!

**Comment by claywilkinson** [comment]
@longngo78 - Please direct  Daydream issues and questions to the AVRDevelopers group.
