### ISSUE TITLE
last version not working

### ISSUE THREAD

**Issue by matiasruella** [playgameservices/play-games-plugin-for-unity#1390]
Hi,  the last version playgames and unity (5.4.x) not working for me. Could someone implement play games with this versions?

I dont have compile errors or other problem in editor. When i run my game in Android device , the plugin init but the authenticate always is false.

Solutions?

**Comment by claywilkinson** [comment]
Can you share a log of when you are authenticating?

**Comment by claywilkinson** [comment]
Please re-open or open a new issue when you have more information.  Thanks!
