### ISSUE TITLE
Authorization mandatory for saved games?

### ISSUE THREAD

**Issue by kkondarev** [playgameservices/play-games-plugin-for-unity#1392]
Hello, I need some help please.

Possibly it's me misunderstanding the concepts here. Reading about GPGS, it seems so, as the authorization step is mandatory for leaderboards, quests, etc, but optional for saved games, which could be online of offline. So far so good.

However, having in mind the following scenario:
1. The player downloads a game having GPGS integration
2. The player turns internet access off
3. The player starts the game - wants to play offline

My expectation would be, that the player can play really offline and the game can be saved locally without the need to authorize. Is there any way to achieve this?

Code and comments are below, bottom line: saved game metadata is not initialized in OnSavedGameOpened, therefore I cannot trigger save.
```
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
        .EnableSavedGames()
        .Build();
PlayGamesPlatform.InitializeInstance(config);
PlayGamesPlatform.Activate();
Social.localUser.Authenticate((bool success) => {
--> Here success is false
});

later in code, opening a non-existing save game (first time):

void OpenSavedGame(string filename) {
        ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame;
        savedGameClient.OpenWithAutomaticConflictResolution(filename, DataSource.ReadCacheOrNetwork,
            ConflictResolutionStrategy.UseLongestPlaytime, OnSavedGameOpened);
    }

    public void OnSavedGameOpened(SavedGameRequestStatus status, ISavedGameMetadata game) {
--> here the metadata (game) is not initialized and status is NOT_AUTHORIZED        
    }
```

**Comment by kkondarev** [comment]
Guys, really? No answer for a simple question like this?

**Comment by claywilkinson** [comment]
Authorization needs to succeed at least once.  The credentials are cached pretty aggressively, so subsequent calls to authorize when offline usually succeed.  The player must be authorized to call any of the Game services APIs.

**Comment by kkondarev** [comment]
Well, thanks for answering.
