### ISSUE TITLE
Imposible to active save games

### ISSUE THREAD

**Issue by chaky31** [playgameservices/play-games-plugin-for-unity#1395]
Hi, I´m using this plugin, but I´m having problem when I try to activate de savegames. Actually I can login and show leaderboards correctly, but when I add the option of savedGames in the builder my game crash. This is my code to singIn

`private void SingIn(){

		PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
			.EnableSavedGames()
			.Build();

		PlayGamesPlatform.InitializeInstance (config);
		GooglePlayGames.PlayGamesPlatform.Activate();
		PlayGamesPlatform.Instance.localUser.Authenticate((bool success) => {
			if (success) {
				Authenticated = true;
			} else {
				Authenticated = false;
			}
		});

		
	}`

Now it doesn´t work, but if i comment .EnableSavedGames() line, it works again, but I can´t use savedgames evidently.

This is the log when I try to activate the savedgames

`I/Unity   ( 1289):  [Play Games Plugin DLL] 09/26/16 11:39:03 +02:00 DEBUG: Activating PlayGamesPlatform.

I/Unity   ( 1289):  

I/Unity   ( 1289): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   ( 1289): 

I/Unity   ( 1289):  [Play Games Plugin DLL] 09/26/16 11:39:03 +02:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform

I/Unity   ( 1289):  

I/Unity   ( 1289): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   ( 1289): 

I/Unity   ( 1289):  [Play Games Plugin DLL] 09/26/16 11:39:03 +02:00 DEBUG: Creating platform-specific Play Games client.

I/Unity   ( 1289):  

I/Unity   ( 1289): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   ( 1289): 

I/Unity   ( 1289):  [Play Games Plugin DLL] 09/26/16 11:39:03 +02:00 DEBUG: Creating Android IPlayGamesClient Client

I/Unity   ( 1289):  

I/Unity   ( 1289): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   ( 1289): 

I/Unity   ( 1289): Building GPG services, implicitly attempts silent auth

I/Unity   ( 1289):  

I/Unity   ( 1289): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   ( 1289): 

I/Unity   ( 1289): Using Facebook Unity SDK v7.8.0 with FBAndroidSDK/4.14.0

I/Unity   ( 1289):  

I/Unity   ( 1289): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   ( 1289): 

I/Unity   ( 1289):  [Play Games Plugin DLL] 09/26/16 11:39:05 +02:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID

I/Unity   ( 1289):  

I/Unity   ( 1289): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I/Unity   ( 1289): 

I/DEBUG   (  446): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

I/DEBUG   (  446): Build fingerprint: 'Xiaomi/kenzo/kenzo:5.1.1/LMY47V/V8.0.1.0.LHOMIDG:user/release-keys'

I/DEBUG   (  446): Revision: '0'

I/DEBUG   (  446): ABI: 'arm'

I/DEBUG   (  446): pid: 1289, tid: 1359, name: main_dispatch  >>> com.game.mygame <<<

I/DEBUG   (  446): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8

I/DEBUG   (  446): Abort message: 'art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: obj == null'

I/DEBUG   (  446):     r0 de7c4878  r1 ac0c57f8  r2 00001002  r3 00000000

I/DEBUG   (  446):     r4 ac0c57f8  r5 00000000  r6 ac0c5830  r7 f56608a1

I/DEBUG   (  446):     r8 f586f7f4  r9 aac6cbe0  sl 00000001  fp 00000000

I/DEBUG   (  446):     ip ac0c57fc  sp de7c4848  lr f57ed5a5  pc f57ed506  cpsr a00d0030

I/DEBUG   (  446): 

I/DEBUG   (  446): backtrace:

I/DEBUG   (  446):     #00 pc 00230506  /system/lib/libart.so (_ZN3art10ThreadList10DumpLockedERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+101)

I/DEBUG   (  446):     #01 pc 0021777d  /system/lib/libart.so (_ZN3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+236)

I/DEBUG   (  446):     #02 pc 002179c9  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+72)

I/DEBUG   (  446):     #03 pc 000a644b  /system/lib/libart.so (_ZN3art10LogMessageD1Ev+1322)

I/DEBUG   (  446):     #04 pc 000b0159  /system/lib/libart.so (_ZN3artL8JniAbortEPKcS1_+1076)

I/DEBUG   (  446):     #05 pc 000b06b1  /system/lib/libart.so (_ZN3art9JniAbortFEPKcS1_z+60)

I/DEBUG   (  446):     #06 pc 0019fe23  /system/lib/libart.so (_ZN3art3JNI15CallVoidMethodVEP7_JNIEnvP8_jobjectP10_jmethodIDSt9__va_list+566)

I/DEBUG   (  446):     #07 pc 000a922b  /data/app/com.game.mygame-1/lib/arm/libgpg.so

I/DEBUG   (  446):     #08 pc 00090105  /data/app/com.game.mygame-1/lib/arm/libgpg.so

I/DEBUG   (  446):     #09 pc 00069bd7  /data/app/com.game.mygame-1/lib/arm/libgpg.so

I/DEBUG   (  446):     #10 pc 0006a73f  /data/app/com.game.mygame-1/lib/arm/libgpg.so

I/DEBUG   (  446):     #11 pc 000719c9  /data/app/com.game.mygame-1/lib/arm/libgpg.so

I/DEBUG   (  446):     #12 pc 000b3d3f  /data/app/com.game.mygame-1/lib/arm/libgpg.so

I/DEBUG   (  446):     #13 pc 00071e9b  /data/app/com.game.mygame-1/lib/arm/libgpg.so

I/DEBUG   (  446):     #14 pc 0007245b  /data/app/com.game.mygame-1/lib/arm/libgpg.so

I/DEBUG   (  446):     #15 pc 0001333f  /system/lib/libc.so (_ZL15__pthread_startPv+30)

I/DEBUG   (  446):     #16 pc 00011357  /system/lib/libc.so (__start_thread+6)

I/DEBUG   (  446): 

I/DEBUG   (  446): Tombstone written to: /data/tombstones/tombstone_08

W/ActivityManager( 1374):   Force finishing activity 1 com.game.mygame/com.unity3d.player.UnityPlayerActivity`

**Comment by claywilkinson** [comment]
Can you confirm that saved games is enabled for your game in the Play Game developer console?

**Comment by chaky31** [comment]
Yes, it´s enable.

**Comment by claywilkinson** [comment]
Thanks for checking.  Which version of the plugin are you using?  Is it the latest?  Which version of google-player-games.aar are you including in your project?  Usually exceptions like this are because of a mismatch between the native library and the java library version.

**Comment by chaky31** [comment]
I´m using the last version of te plugin (0.9.34), this version had play-services-games-9.4.0.aar file, so I think it´s using this file.

**Comment by chaky31** [comment]
Well it works now, it´s my fault, I enabled save games in console, but due to an other error it wasn´t confirm.
Thanks and sorry.

**Comment by claywilkinson** [comment]
Glad you got it working!
