### ISSUE TITLE
"Invalid classname" error when setting up Android

### ISSUE THREAD

**Issue by TinyTitanAli** [playgameservices/play-games-plugin-for-unity#1398]
I get "Invalid classname: An exception was thrown by the type initializer for GooglePlayGames.Editor.GPGSDependencies" when we try to do the Android setup. I tried to see what's happening in the code but for some reason I can't step-in inside "PerformSetup" which is where the exception seems to be coming from, as soon as I hit F11 it just jumps straight to the 'catch' code where it displays the error.

Image: http://i.imgur.com/dYg6foP.png

**Comment by TinyTitanAli** [comment]
No matter what the class name I choose, it still complains. Was testing from Unity 5.4.1

**Comment by atysonwoods** [comment]
I am running into the same problem with 0.9.34 and unity 5.4.1. I just installed the 0.9.32 version and it at least gets past set up.

**Comment by claywilkinson** [comment]
0.9.35 contains new resolver implementation which will work much better.

**Comment by badawe** [comment]
Still the same issue to me on 0.9.36
