### ISSUE TITLE
Really frustrating "The type or namespace name `JarResolver' does not exist in the namespace `Google'"

### ISSUE THREAD

**Issue by vexe** [playgameservices/play-games-plugin-for-unity#1399]
We use the plugin across multiple machines, when I imported it in my machine it worked fine, I pushed to github and then when my coworkers pull, they started getting this error. Only way to fix it is to re-import the plugin on their machine, which makes other files dirty to commit to Github, a redundant commit just to get the thing working, really frustrating experience.

**Comment by claywilkinson** [comment]
Version 0.9.35 of the plugin (just added) includes a re-designed jar resolver which will work much better.
