### ISSUE TITLE
AndroidJavaException: ... no method with name='setGamesApiOptions' ...

### ISSUE THREAD

**Issue by sebastianmonroy** [playgameservices/play-games-plugin-for-unity#140]
Hi everyone, I'm trying to Authenticate using the provided Minimal sample project, but no matter what I try I always get the same error. I'm certain I have the project set up properly. Here's what the relevant part of my adb log looks like when I click the "Authenticate" button, after which the screen just says "Authenticating..." forever:

I/Unity   (10447): AndroidJavaException: java.lang.NoSuchMethodError: no method
with name='setGamesApiOptions' signature='(Lcom.google.android.gms.games.Games$G
amesOptions;)V' in class Lcom/google/example/games/basegameutils/GameHelper;
I/Unity   (10447):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] i
n <filename unknown>:0
I/Unity   (10447):   at UnityEngine.AndroidJNISafe.GetMethodID (IntPtr obj, Syst
em.String name, System.String sig) [0x00000] in <filename unknown>:0
I/Unity   (10447):   at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass
, System.String methodName, System.String signature, Boolean isStatic) [0x00000]
 in <filename unknown>:0
I/Unity   (10447):   at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr javaCla
ss, System.String methodName, System.String signature, Boolean isStatic) [0x0000
0] in <filename unknown>:0
I/Unity   (10447):   at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass
, System.String methodName, System.Object[] args, Boolean isStatic) [0x00000] in
 <filename unknown>:0
I/Unity   (10447):   at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr jclass,
 System.String methodName, S
I/Unity   (10447): NullReferenceException: Object reference not set to an instan
ce of an object
I/Unity   (10447):   at GooglePlayGames.Android.AndroidClient+<Authenticate>c__A
nonStorey0.<>m__1 () [0x00000] in <filename unknown>:0
I/Unity   (10447):   at UnityEngine.AndroidJavaRunnableProxy.run () [0x00000] in
 <filename unknown>:0
I/Unity   (10447):   at System.Reflection.MonoMethod.Invoke (System.Object obj,
BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parame
ters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:
0
I/Unity   (10447): Rethrow as TargetInvocationException: UnityEngine.AndroidJava
RunnableProxy.run()
I/Unity   (10447):   at UnityEngine.AndroidJavaProxy.Invoke (System.String metho
dName, System.Object[] args) [0x00000] in <filename unknown>:0
I/Unity   (10447):   at UnityEngine.AndroidJavaProxy.Invoke (System.String metho
dName, UnityEngine.AndroidJavaObject[] javaArgs) [0x00000] in <filename unknown>
:0
I/Unity   (10447):   at UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (Uni
tyEngine.AndroidJavaProxy proxy, IntPtr jmethodName, IntPtr jargs) [0x00000] in
<filename unknown>:0

I tried the solutions in Issue #81 to the best of my ability and was not able to resolve this issue. Can anyone else provide any information about how to fix this? I really didn't expect to be having bugs this early on using this promising plugin.

Thanks!

**Comment by claywilkinson** [comment]
This is obsolete since the newer plugin is architected differently.
