### ISSUE TITLE
Users silently signed in

### ISSUE THREAD

**Issue by freseco** [playgameservices/play-games-plugin-for-unity#1400]
silently signed in doesn't work.

PlayGamesPlatform.Instance.Authenticate(SignInCallback,true);

but with normal signed in, it works
PlayGamesPlatform.Instance.Authenticate(SignInCallback,false); 

Does this happen because I have two mobile users?

**Comment by claywilkinson** [comment]
Could be.  Also, if the player explicitly logs out by calling Signout(), then that user will never be signed in silently again.
