### ISSUE TITLE
error: Attribute "imageAspectRatioAdjust" already defined with incompatible

### ISSUE THREAD

**Issue by a574490399** [playgameservices/play-games-plugin-for-unity#1401]
when i build apk,i receve this error: Attribute "imageAspectRatioAdjust" already defined with incompatible.

**Comment by claywilkinson** [comment]
You have multiple copies of aar or jar files such as the support-v4 aar.  Please remove the duplicate and try to rebuild.  If you are still having trouble, please re-open this issue and add the log message from Unity.
