### ISSUE TITLE
Unable to convert classes into dex format

### ISSUE THREAD

**Issue by BochicaCodeNode** [playgameservices/play-games-plugin-for-unity#1402]
Are play-services-*-9.0.0 & play-services-*-9.6.1 compatible or please point me in the right direction?

CommandInvokationFailure: dex format FirebaseApiNotAvailableException
processing archive C:\Source\Workspaces\ProjX\Dev\Source\GameX\Temp\StagingArea\android-libraries\MainLibProj\libs\.\play-games-plugin-support.jar...
processing archive C:\Source\Workspaces\ProjX\Dev\Source\GameX\Temp\StagingArea\android-libraries\firebase-common-9.0.0\libs\.\classes.jar...
processing archive C:\Source\Workspaces\ProjX\Dev\Source\GameX\Temp\StagingArea\android-libraries\play-services-auth-base-9.0.0\libs\.\classes.jar...
processing archive C:\Source\Workspaces\ProjX\Dev\Source\GameX\Temp\StagingArea\android-libraries\play-services-base-9.6.1\libs\.\classes.jar...

CommandInvokationFailure: Unable to convert classes into dex format.
C:\Program Files\Java\jdk1.8.0_102\bin\java.exe
 -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/Dev35/AppData/Local/Android/sdk\tools"
 -Dfile.encoding=UTF8
 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar"
 -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/FirebaseApiNotAvailableException;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/FirebaseException;
2 errors; aborting
]
stdout[
processing archive C:\Source\Workspaces\ProjX\Dev\Source\GameX\Temp\StagingArea\android-libraries\MainLibProj\libs\.\play-games-plugin-support.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/games/
ignored resource com/google/games/bridge/
processing com/google/games/bridge/BuildConfig.class...
processing com/google/games/bridge/NativeBridgeActivity.class...
processing com/google/games/bridge/TokenFragment.class...
processing com/google/games/bridge/TokenFragment$1.class...
processing com/google/games/bridge/TokenFragment$TokenRequest.class...
processing com/google/games/bridge/TokenPendingResult.class...
processing com/google/games/bridge/TokenResult.class...
processing archive C:\Source\Workspaces\ProjX\Dev\Source\GameX\Temp\StagingArea\android-libraries\firebase-common-9.0.0\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/internal/
processing com/google/android/gms/internal/zzaiy.class...
processing com/google/android/gms/internal/zzaiz.class...
processing com/google/android/gms/internal/zzaja.class...
processing com/google/android/gms/internal/zzajb.class...
ignored resource com/google/firebase/
processing com/google/firebase/FirebaseApiNotAvailableException.class...
processing com/google/firebase/FirebaseApp.class...
processing com/google/firebase/FirebaseApp$zza.class...
processing com/google/firebase/FirebaseApp$zzb.class...
processing com/google/firebase/FirebaseException.class...
processing com/google/firebase/FirebaseNetworkException.class...
processing com/google/firebase/FirebaseOptions.class...
processing com/google/firebase/FirebaseOptions$1.class...
processing com/google/firebase/FirebaseOptions$Builder.class...
processing com/google/firebase/FirebaseTooManyRequestsException.class...
ignored resource com/google/firebase/auth/
processing com/google/firebase/auth/AuthCredential.class...
processing com/google/firebase/auth/AuthResult.class...
processing com/google/firebase/auth/FirebaseAuthException.class...
processing com/google/firebase/auth/FirebaseUser.class...
processing com/google/firebase/auth/GetTokenResult.class...
processing com/google/firebase/auth/UserInfo.class...
processing com/google/firebase/auth/UserProfileChangeRequest.class...
processing com/google/firebase/auth/UserProfileChangeRequest$Builder.class...
processing com/google/firebase/auth/zza.class...
ignored resource com/google/firebase/provider/
processing com/google/firebase/provider/FirebaseInitProvider.class...
processing archive C:\Source\Workspaces\ProjX\Dev\Source\GameX\Temp\StagingArea\android-libraries\play-services-auth-base-9.0.0\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/auth/
processing com/google/android/gms/auth/AccountChangeEvent.class...
processing com/google/android/gms/auth/AccountChangeEventsRequest.class...
processing com/google/android/gms/auth/AccountChangeEventsResponse.class...
processing com/google/android/gms/auth/GoogleAuthException.class...
processing com/google/android/gms/auth/GoogleAuthUtil.class...
processing com/google/android/gms/auth/GooglePlayServicesAvailabilityException.class...
processing com/google/android/gms/auth/TokenData.class...
processing com/google/android/gms/auth/UserRecoverableAuthException.class...
processing com/google/android/gms/auth/UserRecoverableNotifiedException.class...
processing com/google/android/gms/auth/zza.class...
processing com/google/android/gms/auth/zzb.class...
processing com/google/android/gms/auth/zzc.class...
processing com/google/android/gms/auth/zzd.class...
processing com/google/android/gms/auth/zzd$1.class...
processing com/google/android/gms/auth/zzd$2.class...
processing com/google/android/gms/auth/zzd$3.class...
processing com/google/android/gms/auth/zzd$4.class...
processing com/google/android/gms/auth/zzd$zza.class...
processing com/google/android/gms/auth/zze.class...
ignored resource com/google/android/gms/internal/
processing com/google/android/gms/internal/zzbn.class...
processing com/google/android/gms/internal/zzbn$zza.class...
processing com/google/android/gms/internal/zzbn$zza$zza.class...
processing com/google/android/gms/internal/zzmx.class...
processing archive C:\Source\Workspaces\ProjX\Dev\Source\GameX\Temp\StagingArea\android-libraries\play-services-base-9.6.1\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/auth/
ignored resource com/google/android/gms/auth/api/
ignored resource com/google/android/gms/auth/api/signin/
processing com/google/android/gms/auth/api/signin/GoogleSignInAccount.class...
processing com/google/android/gms/auth/api/signin/GoogleSignInAccount$1.class...
processing com/google/android/gms/auth/api/signin/GoogleSignInOptions.class...
processing com/google/android/gms/auth/api/signin/GoogleSignInOptions$1.class...
processing com/google/android/gms/auth/api/signin/GoogleSignInOptions$Builder.class...
ignored resource com/google/android/gms/auth/api/signin/internal/
processing com/google/android/gms/auth/api/signin/internal/zze.class...
processing com/google/android/gms/auth/api/signin/internal/zzk.class...
processing com/google/android/gms/auth/api/signin/zza.class...
processing com/google/android/gms/auth/api/signin/zzb.class...
ignored resource com/google/android/gms/common/
processing com/google/android/gms/common/ErrorDialogFragment.class...
processing com/google/android/gms/common/GoogleApiAvailability.class...
processing com/google/android/gms/common/GooglePlayServicesUtil.class...
processing com/google/android/gms/common/GooglePlayServicesUtil$zza.class...
processing com/google/android/gms/common/SignInButton.class...
processing com/google/android/gms/common/SignInButton$ButtonSize.class...
processing com/google/android/gms/common/SignInButton$ColorScheme.class...
processing com/google/android/gms/common/SupportErrorDialogFragment.class...
ignored resource com/google/android/gms/common/api/
processing com/google/android/gms/common/api/Api.class...
processing com/google/android/gms/common/api/Api$ApiOptions.class...
processing com/google/android/gms/common/api/Api$ApiOptions$HasOptions.class...
processing com/google/android/gms/common/api/Api$ApiOptions$NoOptions.class...
processing com/google/android/gms/common/api/Api$ApiOptions$NotRequiredOptions.class...
processing com/google/android/gms/common/api/Api$ApiOptions$Optional.class...
processing com/google/android/gms/common/api/Api$zza.class...
processing com/google/android/gms/common/api/Api$zzb.class...
processing com/google/android/gms/common/api/Api$zzc.class...
processing com/google/android/gms/common/api/Api$zzd.class...
processing com/google/android/gms/common/api/Api$zze.class...
processing com/google/android/gms/common/api/Api$zzf.class...
processing com/google/android/gms/common/api/Api$zzg.class...
processing com/google/android/gms/common/api/Api$zzh.class...
processing com/google/android/gms/common/api/Api$zzi.class...
processing com/google/android/gms/common/api/Batch.class...
processing com/google/android/gms/common/api/Batch$1.class...
processing com/google/android/gms/common/api/Batch$Builder.class...
processing com/google/android/gms/common/api/BatchResult.class...
processing com/google/android/gms/common/api/BatchResultToken.class...
processing com/google/android/gms/common/api/BooleanResult.class...
processing com/google/android/gms/common/api/GoogleApiActivity.class...
processing com/google/android/gms/common/api/GoogleApiClient.class...
processing com/google/android/gms/common/api/GoogleApiClient$Builder.class...
processing com/google/android/gms/common/api/GoogleApiClient$ConnectionCallbacks.class...
processing com/google/android/gms/common/api/GoogleApiClient$OnConnectionFailedListener.class...
processing com/google/android/gms/common/api/OptionalPendingResult.class...
processing com/google/android/gms/common/api/PendingResult.class...
processing com/google/android/gms/common/api/PendingResult$zza.class...
processing com/google/android/gms/common/api/PendingResults.class...
processing com/google/android/gms/common/api/PendingResults$zza.class...
processing com/google/android/gms/common/api/PendingResults$zzb.class...
processing com/google/android/gms/common/api/PendingResults$zzc.class...
processing com/google/android/gms/common/api/ResultTransform.class...
processing com/google/android/gms/common/api/TransformedResult.class...
processing com/google/android/gms/common/api/zzb.class...
processing com/google/android/gms/common/api/zzc.class...
processing com/google/android/gms/common/api/zzd.class...
processing com/google/android/gms/common/api/zzf.class...
ignored resource com/google/android/gms/common/data/
processing com/google/android/gms/common/data/AbstractDataBuffer.class...
processing com/google/android/gms/common/data/BitmapTeleporter.class...
processing com/google/android/gms/common/data/DataBuffer.class...
processing com/google/android/gms/common/data/DataBufferObserver.class...
processing com/google/android/gms/common/data/DataBufferObserver$Observable.class...
processing com/google/android/gms/common/data/DataBufferObserverSet.class...
processing com/google/android/gms/common/data/DataBufferUtils.class...
processing com/google/android/gms/common/data/DataHolder.class...
processing com/google/android/gms/common/data/DataHolder$1.class...
processing com/google/android/gms/common/data/DataHolder$zza.class...
processing com/google/android/gms/common/data/DataHolder$zzb.class...
processing com/google/android/gms/common/data/Freezable.class...
processing com/google/android/gms/common/data/FreezableUtils.class...
processing com/google/android/gms/common/data/zza.class...
processing com/google/android/gms/common/data/zzb.class...
processing com/google/android/gms/common/data/zzc.class...
processing com/google/android/gms/common/data/zzd.class...
processing com/google/android/gms/common/data/zze.class...
processing com/google/android/gms/common/data/zzf.class...
processing com/google/android/gms/common/data/zzg.class...
ignored resource com/google/android/gms/common/images/
processing com/google/android/gms/common/images/ImageManager.class...
processing com/google/android/gms/common/images/ImageManager$ImageReceiver.class...
processing com/google/android/gms/common/images/ImageManager$OnImageLoadedListener.class...
processing com/google/android/gms/common/images/ImageManager$zza.class...
processing com/google/android/gms/common/images/ImageManager$zzb.class...
processing com/google/android/gms/common/images/ImageManager$zzc.class...
processing com/google/android/gms/common/images/ImageManager$zzd.class...
processing com/google/android/gms/common/images/ImageManager$zze.class...
processing com/google/android/gms/common/images/ImageManager$zzf.class...
processing com/google/android/gms/common/images/Size.class...
processing com/google/android/gms/common/images/WebImage.class...
processing com/google/android/gms/common/images/zza.class...
processing com/google/android/gms/common/images/zza$zza.class...
processing com/google/android/gms/common/images/zza$zzb.class...
processing com/google/android/gms/common/images/zza$zzc.class...
processing com/google/android/gms/common/images/zzb.class...
ignored resource com/google/android/gms/common/internal/
processing com/google/android/gms/common/internal/AuthAccountRequest.class...
processing com/google/android/gms/common/internal/ResolveAccountRequest.class...
processing com/google/android/gms/common/internal/ResolveAccountResponse.class...
processing com/google/android/gms/common/internal/SignInButtonConfig.class...
processing com/google/android/gms/common/internal/zzad.class...
processing com/google/android/gms/common/internal/zzae.class...
processing com/google/android/gms/common/internal/zzaf.class...
processing com/google/android/gms/common/internal/zzag.class...
processing com/google/android/gms/common/internal/zzah.class...
processing com/google/android/gms/common/internal/zzai.class...
processing com/google/android/gms/common/internal/zzb.class...
processing com/google/android/gms/common/internal/zzd.class...
processing com/google/android/gms/common/internal/zzh.class...
processing com/google/android/gms/common/internal/zzh$zza.class...
processing com/google/android/gms/common/internal/zzi.class...
processing com/google/android/gms/common/internal/zzj.class...
processing com/google/android/gms/common/internal/zzj$1.class...
processing com/google/android/gms/common/internal/zzj$2.class...
processing com/google/android/gms/common/internal/zzj$3.class...
processing com/google/android/gms/common/internal/zzl.class...
processing com/google/android/gms/common/internal/zzl$1.class...
processing com/google/android/gms/common/internal/zzl$2.class...
processing com/google/android/gms/common/internal/zzm.class...
processing com/google/android/gms/common/internal/zzm$zza.class...
processing com/google/android/gms/common/internal/zzx.class...
processing com/google/android/gms/common/internal/zzx$zza.class...
processing com/google/android/gms/common/internal/zzx$zza$zza.class...
processing com/google/android/gms/common/internal/zzy.class...
processing com/google/android/gms/common/internal/zzy$zza.class...
processing com/google/android/gms/common/internal/zzy$zza$zza.class...
ignored resource com/google/android/gms/dynamic/
processing com/google/android/gms/dynamic/zza.class...
processing com/google/android/gms/dynamic/zza$1.class...
processing com/google/android/gms/dynamic/zza$2.class...
processing com/google/android/gms/dynamic/zza$3.class...
processing com/google/android/gms/dynamic/zza$4.class...
processing com/google/android/gms/dynamic/zza$5.class...
processing com/google/android/gms/dynamic/zza$6.class...
processing com/google/android/gms/dynamic/zza$7.class...
processing com/google/android/gms/dynamic/zza$zza.class...
ignored resource com/google/android/gms/internal/
processing com/google/android/gms/internal/zzpy.class...
processing com/google/android/gms/internal/zzpy$zza.class...
processing com/google/android/gms/internal/zzpy$zzb.class...
processing com/google/android/gms/internal/zzpy$zzc.class...
processing com/google/android/gms/internal/zzpy$zzd.class...
processing com/google/android/gms/internal/zzpy$zze.class...
processing com/google/android/gms/internal/zzpz.class...
processing com/google/android/gms/internal/zzqa.class...
processing com/google/android/gms/internal/zzqa$zza.class...
processing com/google/android/gms/internal/zzqb.class...
processing com/google/android/gms/internal/zzqc.class...
processing com/google/android/gms/internal/zzqc$zza.class...
processing com/google/android/gms/internal/zzqc$zzb.class...
processing com/google/android/gms/internal/zzqd.class...
processing com/google/android/gms/internal/zzqd$1.class...
processing com/google/android/gms/internal/zzqd$zza.class...
processing com/google/android/gms/internal/zzqd$zza$1.class...
processing com/google/android/gms/internal/zzqe.class...
processing <message truncated>

**Comment by kkondarev** [comment]
looks like you have duplicate files. check imported libraries and remove outdated ones.

**Comment by BochicaCodeNode** [comment]
Thank that was it.

**Comment by victorofrank** [comment]
I'm having precisely the same issue. Where can I find the files to delete?
