### ISSUE TITLE
Initial authentication always failing

### ISSUE THREAD

**Issue by kkondarev** [playgameservices/play-games-plugin-for-unity#1403]
Hi, following the code snippets, I am integrating Play Games Services into our games.

However, I am facing few issues:
Issue Nr 1: on game loading the authentication is always failing. The device has internet and everything, the code execution is waiting for the callbacks, etc.

Impact: game starts without user authentication, saved games are not available.
Any idea why the initial authentication fails? This happens every time!

> 10-03 13:35:30.294: E/Unity(13871): [EGL] eglChooseConfig(m_EGLDisplay, configAttribs, NULL, 0, &eglConfigCount): EGL_BAD_ATTRIBUTE: An unrecognized attribute or attribute value was passed in the attribute list.
> 10-03 13:35:30.294: E/Unity(13871):  
> 10-03 13:35:30.294: E/Unity(13871): (Filename: ./Runtime/GfxDevice/egl/ConfigEGL.cpp Line: 374)
> 10-03 13:35:30.304: E/Unity(13871): [EGL] eglChooseConfig(m_EGLDisplay, configAttribs, NULL, 0, &eglConfigCount): EGL_BAD_ATTRIBUTE: An unrecognized attribute or attribute value was passed in the attribute list.
> 10-03 13:35:30.304: E/Unity(13871):  
> 10-03 13:35:30.304: E/Unity(13871): (Filename: ./Runtime/GfxDevice/egl/ConfigEGL.cpp Line: 374)
> 10-03 13:35:31.389: D/Unity(13871): GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map 
> 10-03 13:35:44.239: I/Unity(13871):  [Play Games Plugin DLL] 10/03/16 13:35:44 +02:00 DEBUG: Activating PlayGamesPlatform.
> 10-03 13:35:44.239: I/Unity(13871):  
> 10-03 13:35:44.239: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 10-03 13:35:44.244: I/Unity(13871):  [Play Games Plugin DLL] 10/03/16 13:35:44 +02:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
> 10-03 13:35:44.244: I/Unity(13871):  
> 10-03 13:35:44.244: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 10-03 13:35:44.264: I/Unity(13871):  [Play Games Plugin DLL] 10/03/16 13:35:44 +02:00 DEBUG: Creating platform-specific Play Games client.
> 10-03 13:35:44.264: I/Unity(13871):  
> 10-03 13:35:44.264: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 10-03 13:35:44.264: I/Unity(13871):  [Play Games Plugin DLL] 10/03/16 13:35:44 +02:00 DEBUG: Creating Android IPlayGamesClient Client
> 10-03 13:35:44.264: I/Unity(13871):  
> 10-03 13:35:44.264: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 10-03 13:35:44.389: D/GamesUnitySDK(13871): Performing Android initialization of the GPG SDK
> 10-03 13:35:44.759: I/Unity(13871): Building GPG services, implicitly attempts silent auth
> 10-03 13:35:44.759: I/Unity(13871):  
> 10-03 13:35:44.759: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 10-03 13:35:48.819: I/Unity(13871):  [Play Games Plugin DLL] 10/03/16 13:35:48 +02:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
> 10-03 13:35:48.819: I/Unity(13871):  
> 10-03 13:35:48.819: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 10-03 13:35:48.819: I/Unity(13871): Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
> 10-03 13:35:48.819: I/Unity(13871):  
> 10-03 13:35:48.819: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 10-03 13:35:48.824: I/Unity(13871): there are pending auth callbacks - starting AuthUI
> 10-03 13:35:48.824: I/Unity(13871):  
> 10-03 13:35:48.824: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 10-03 13:36:04.024: I/Unity(13871):  [Play Games Plugin DLL] 10/03/16 13:36:03 +02:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_TIMEOUT
> 10-03 13:36:04.024: I/Unity(13871):  
> 10-03 13:36:04.024: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 10-03 13:36:04.179: I/Unity(13871): AuthState == Unauthenticated calling auth callbacks with failure
> 10-03 13:36:04.179: I/Unity(13871):  
> 10-03 13:36:04.179: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 10-03 13:36:04.224: I/Unity(13871):  [Play Games Plugin DLL] 10/03/16 13:36:04 +02:00 DEBUG: Invoking user callback on game thread
> 10-03 13:36:04.224: I/Unity(13871):  
> 10-03 13:36:04.224: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 10-03 13:36:05.689: I/UnityIAP(13871): IAB helper created.
> 10-03 13:36:05.804: I/Unity(13871): OPEN SAVED GAME triggered: DefaultGame
> 10-03 13:36:05.804: I/Unity(13871):  
> 10-03 13:36:05.804: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 10-03 13:36:05.804: I/Unity(13871): GPGS Authenticated: False
> 10-03 13:36:05.804: I/Unity(13871):  
> 10-03 13:36:05.804: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 10-03 13:36:06.169: I/Unity(13871):  [Play Games Plugin DLL] 10/03/16 13:36:06 +02:00 DEBUG: Entering internal callback for SnapshotManager#OpenCallback
> 10-03 13:36:06.169: I/Unity(13871):  
> 10-03 13:36:06.169: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
> 10-03 13:36:06.224: I/Unity(13871): OPENED SAVED GAME, status: AuthenticationError, game data is null: True
> 10-03 13:36:06.224: I/Unity(13871):  
> 10-03 13:36:06.224: I/Unity(13871): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

**Comment by analripper** [comment]
I expirienced exact same issue. I use plugin version 0.9.35 and Unity 5.3.2f1.
Then after I tried out all that internet can suggest to me, regarding my issue, I installed Unity 5.4.3 f1 and get my working authentication.
Hope it helps.

**Comment by kkondarev** [comment]
Oh! The authentication callback is working in 5.4.3? I saw no pointer to that fix in the notes?
