### ISSUE TITLE
Automated savegames?

### ISSUE THREAD

**Issue by Edgarborras94** [playgameservices/play-games-plugin-for-unity#1406]
Can i know if there is any saved game on the cloud? I want to know if there is a way to check if there is a savegame and if there isnt any, create a new one

**Comment by claywilkinson** [comment]
You can call open with a valid file name, and then read the data.  If the file is empty, it is a new file, otherwise it was an existing file.  You can write to it using the same logic regardless if was existing or new.

**Comment by kkondarev** [comment]
What is "valid file name"? Just letters/numbers/underscore? Or full Unicode? Is point necessary?
I was looking for requirement/restrictions, but found nothing.

**Comment by Edgarborras94** [comment]
@claywilkinson  how can i call open with a file name? I was trying to, but the only source code I found uses the select save game UI and i'm trying to avoid this UI. This is the code i'm referring ```
((PlayGamesPlatform)Social.Active).SavedGame.ShowSelectSavedGameUI("Select saved game to load",
            4, false, false, SavedGameSelected);
```

**Comment by claywilkinson** [comment]
I haven't tried the full UTF-8 charset, but I do know that variable name characters work  great (alphanumeric, underscore).  I would venture a guess that non-whitespace filename characters will work OK too ( dash, period, exclamation, etc.) If you experiment with others, please share your findings.

You can specify the filename to open with code like this (from the README):
```
void OpenSavedGame(string filename) {
        ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame;
        savedGameClient.OpenWithAutomaticConflictResolution(filename, DataSource.ReadCacheOrNetwork,
            ConflictResolutionStrategy.UseLongestPlaytime, OnSavedGameOpened);
    }
```

**Comment by kkondarev** [comment]
Lately I am only getting ERROR_INTERNAL. Was thinking it might be because of the file name, but on second thought I am using nothing exotic. Created several issues, but no one is looking at them...

**Comment by claywilkinson** [comment]
Can you share the log?  Are you Authenticating successfully?  Is Saved Games API enabled on the Play Developer Console for your game?

**Comment by kkondarev** [comment]
Yes, saved games is enabled, authentication is first unsuccessful (every time, separate issue opened for this), but then even with successful authenticated (is always successful when triggered again) - saving a game fails with ERROR_INTERNAL.

Here are the logs: 

Saving issue (with successful authentication): https://github.com/playgameservices/play-games-plugin-for-unity/issues/1404

Authentication failing first try: https://github.com/playgameservices/play-games-plugin-for-unity/issues/1403

**Comment by claywilkinson** [comment]
Thanks - Can you share the full log, not just the Unity category?

**Comment by kkondarev** [comment]
Oh! Sure, will be quite a lot, but ofc. For which of the cases?

**Comment by claywilkinson** [comment]
When opening the saved game fails when authenticated - thanks.

**Comment by kkondarev** [comment]
Done, full log is in last comment in https://github.com/playgameservices/play-games-plugin-for-unity/issues/1404

**Comment by claywilkinson** [comment]
I believe an updated version of play-services-games corrects this issue.  Please re-open if it is still not working with play-services-games-10.0.1 or greater.
