### ISSUE TITLE
TurnBased.CreateQuickMatch starting match with no opponents

### ISSUE THREAD

**Issue by leonardok** [playgameservices/play-games-plugin-for-unity#1408]
This can be me misunderstanding the documentation, but when I do:
`// 1, 1, 1`
`PlayGamesPlatform.Instance.TurnBased.CreateQuickMatch(MinOpponents, MaxOpponents, Variant, OnMatchStarted);`

It calls the callback OnMatchStarted with no opponents. When running on two devices I can see that each player enters a different match. In the log I also can see there is only one:

`[TurnBasedMatch: mMatchId=xxxxxxxxx____________ARChsYD_nvmEgoEB, mData=, mCanRematch=False, mSelfParticipantId=p_1, mParticipants=[Participant: 'xxxxxx' (id p_1), status=Joined, player=[Player: 'xxxxxx' (id xxxxxxx)], connected=True], mPendingParticipantId=p_1, mTurnStatus=MyTurn, mMatchStatus=Active, mVariant=1, mVersion=1]`

Am I missing something? By the looks of the documentation I though the `OnMatchStarted` callback should be called when the game is ready to start i.e. there is a room with the player plus one opponent.

Thanks!

**Comment by lightray1** [comment]
I've the same problem, looks like I'm the only player in the match.

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
