### ISSUE TITLE
Video Recording API does not appear to be exposed

### ISSUE THREAD

**Issue by epsmarkh** [playgameservices/play-games-plugin-for-unity#1409]
We would like to get access to the Video Recording API as documented here:

https://developers.google.com/games/services/android/videoRecording
https://developers.google.com/android/reference/com/google/android/gms/games/video/package-summary

The current plugin does not seem to expose this API

**Comment by claywilkinson** [comment]
Thanks for the feedback.  It is planned for an upcoming update.

**Comment by reyzonk** [comment]
When will it be update?? T.T  I was waiting for June...

**Comment by alohner** [comment]
Hi,
I would be very interested in implementing that feature in my game. Do you have any date for this upcoming update ?
Thanks.

**Comment by luizjunior** [comment]
I'm interested also.

**Comment by claywilkinson** [comment]
This is part of version 0.9.37.
