### ISSUE TITLE
RTMP OnLeftRoom being called when a peer disconnects

### ISSUE THREAD

**Issue by designzoo-glenn** [playgameservices/play-games-plugin-for-unity#141]
According to the docs OnLeftRoom gets called when PlayGamesPlatform.Instance.RealTime.LeaveRoom(); is called on the user's device. However when I have a room, OnLeftRoom gets called when the other player leaves the room instead of calling OnPeerDisconnect. 

I have pasted the stack trace for the OnleftRoom call if that helps
```
06-03 12:10:53.742: I/Unity(14418): left Game: 
06-03 12:10:53.742: I/Unity(14418):    at System.Environment.get_StackTrace()
06-03 12:10:53.742: I/Unity(14418):    at MyMultiplayer.OnLeftRoom()
06-03 12:10:53.742: I/Unity(14418):    at GooglePlayGames.Android.AndroidRtmpClient+<Clear>c__AnonStorey19.<>m__22()
06-03 12:10:53.742: I/Unity(14418):    at GooglePlayGames.OurUtils.PlayGamesHelperObject.Update()
```

No where on the user's device do I disconnect using the LeaveRoom() method.This bug was recreated by pressing the home button on the peer device to leave the room in a 1v1 game (a room with 2 players).

I am using v4.4.52 of the plugin, where both clients are android devices (OS versions 4.1.2 and 4.4.2).

Thanks

**Comment by claywilkinson** [comment]
Closing since https://github.com/playgameservices/play-games-plugin-for-unity/issues/215 is closed.  Please open another issue if you are still experiencing this issue.
