### ISSUE TITLE
Choose account Shows Twice in different dialogues

### ISSUE THREAD

**Issue by royalcrown28** [playgameservices/play-games-plugin-for-unity#1410]
I am getting two different "choose an account" prompts that whenever I call authenticate on android.

The first looks much like this [IMG](http://i.imgur.com/Zc6uFq9.jpg)

The second looks exactly like this [IMG](http://i.stack.imgur.com/RWFec.png)

The second prompt has no effect and just serves to confuse the user. It also pops up every single launch while the first does not (because I believe that one is cached).

What is this second prompt a part of and how can I prevent it from showing?

**Comment by claywilkinson** [comment]
The second one is shown when getting the email or a token.  Are you getting one of these?

**Comment by claywilkinson** [comment]
This has been addressed by using GoogleSignIn in version 0.9.37
