### ISSUE TITLE
Update to 0.9.34: Can't register class

### ISSUE THREAD

**Issue by Qbit86** [playgameservices/play-games-plugin-for-unity#1411]
Hi!

I'm running into failure during authentication/initialization after updating from 0.9.33 to 0.9.34:
```
10-10 16:02:58.837: E/GamesNativeSDK(4013): Can't register class com/google/android/gms/games/multiplayer/ParticipantResult: an exception occurred.
10-10 16:02:58.847: W/dalvikvm(4013): Unable to resolve superclass of Lcom/google/android/gms/nearby/connection/AppIdentifier; (5459)
10-10 16:02:58.847: W/dalvikvm(4013): Link of class 'Lcom/google/android/gms/nearby/connection/AppIdentifier;' failed
10-10 16:02:58.847: E/GamesNativeSDK(4013): Can't register class com/google/android/gms/nearby/connection/AppIdentifier: an exception occurred.
10-10 16:02:58.847: W/dalvikvm(4013): Unable to resolve superclass of Lcom/google/android/gms/nearby/connection/AppMetadata; (5459)
10-10 16:02:58.847: W/dalvikvm(4013): Link of class 'Lcom/google/android/gms/nearby/connection/AppMetadata;' failed
10-10 16:02:58.847: E/GamesNativeSDK(4013): Can't register class com/google/android/gms/nearby/connection/AppMetadata: an exception occurred.
10-10 16:02:58.887: I/Unity(4013): Building GPG services, implicitly attempts silent auth
10-10 16:02:58.887: I/Unity(4013):  
10-10 16:02:58.887: I/Unity(4013): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
10-10 16:02:58.887: E/GamesNativeSDK(4013): Could not register one or more required Java classes.
```
```
10-10 16:02:58.927: I/Unity(4013): InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK
10-10 16:02:58.927: I/Unity(4013):   at GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build (GooglePlayGames.Native.PInvoke.PlatformConfiguration configRef) [0x00000] in <filename unknown>:0 
10-10 16:02:58.927: I/Unity(4013):   at GooglePlayGames.Native.NativeClient.InitializeGameServices () [0x00000] in <filename unknown>:0 
10-10 16:02:58.927: I/Unity(4013):   at GooglePlayGames.Native.NativeClient.Authenticate (System.Action`1 callback, Boolean silent) [0x00000] in <filename unknown>:0 
10-10 16:02:58.927: I/Unity(4013):   at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`1 callback, Boolean silent) [0x00000] in <filename unknown>:0 
10-10 16:02:58.927: I/Unity(4013):   at ...
```

I've checked Android SDK Manager (after reading about similar issues), Google Play services: Rev. 33; other components are also up to date.

Jar Resolver has not updated all of the `aar`s to 9.6.1:
+ `play-services-measurement-8.4.0/` (folder, “exploded” by resolver)
+ `play-services-ads-8.4.0.aar`
+ `play-services-base-8.4.0.aar`
+ `play-services-basement-8.4.0.aar`
+ `play-services-drive-8.4.0.aar`
+ `play-services-gcm-8.4.0.aar`
+ `play-services-plus-8.4.0.aar`
+ `play-services-games-9.6.1.aar`
+ `play-services-nearby-9.6.1.aar`

If I replace some of `aar`s explicitly from `8.4.0` to `9.6.1`, then Editor script suggests restoring them back. And there is no `play-services-measurement-9.6.1.aar` in `extras/` folder of Android SDK.

Looks like this upgrade is required for integrating Prime31 Flurry plugin, since it depends on `play-services-basement` version `9+`, and DEX build fails due to some unclear conflict.

Please help, I cannot move on with this issue unresolved.

----

Unity 5.3.6p6, Windows 10 Pro, targeting Android, Android SDK r24.4.1 with updated components.

**Comment by Qbit86** [comment]
@claywilkinson Why running “Setup” restores `8.4.0` version of libraries in case when I manually remove all `play-services-*-8.4.0.aar`s? How can I make Editor resolve `9.6.1` version?

**Comment by Qbit86** [comment]
@claywilkinson I cannot upgrade GPG plugin, because of this issue. But I also cannot refuse upgrading, because I need to integrate Flurry plugin which depends on `9+` version of one of the libraries: `svcSupport.DependOn("com.google.android.gms", "play-services-basement", "9+");`

What should I do?

**Comment by Qbit86** [comment]
Not sure, but does really GitHub not support notification for the user, when you type “@” with username?

**Comment by claywilkinson** [comment]
All the aars need to be the same version.  The latest version of this plugin 0.9.35 requires version 9+, so it should be compatible with the other plugins.
