### ISSUE TITLE
iOS NO_GPGS build

### ISSUE THREAD

**Issue by soniyj** [playgameservices/play-games-plugin-for-unity#1412]
iOS build fails with the string NO_GPG.

Without the string the application crashes due to this error:

libc++abi.dylib: terminating with uncaught exception of type NSException.

**Comment by heyalistair** [comment]
You do mean NO_GPGS (with an S at the end), right?

**Comment by leodluz** [comment]
I had the same problem

**Comment by soniyj** [comment]
Hi @heyalistair yeah of course, sorry copy/paste didn't do it's job. Anyway yeah the problem is that one how it's reported into the section "Excluding all Google Play Game Services when building for iOS".

**Comment by claywilkinson** [comment]
By defining NO_GPGS in Unity when building for iOS, it will exclude all code from this plugin in the XCode project, so I doubt the crash is related to this plugin.  Can you share the log of the crash?  That will help confirm it is unrelated.

**Comment by soniyj** [comment]
Hi @claywilkinson, I'm facing other problems related to the achievements ui in iOS and reportscrore on Android.

Basically on iOS I'm able to login, set the score and see the leaderboard UI, but when I try to call the banner for an achievement it doesn't show anything. I tested it on the simulator and both the achievement and leaderboard are not published yet.

On Android, I'm able to login, but report score returns false always, but I do not know why, do I need to publish the game also for testing? I have my email as a tester but I didn't publish the game yet.

Any idea?

**Comment by hippogamesunity** [comment]
Use NO_GPGS, but have Google libraries included to my xcode project(

**Comment by claywilkinson** [comment]
This is fixed in version 0.9.36 of the plugin.
