### ISSUE TITLE
Conflict with Google Mobile Ads plugin

### ISSUE THREAD

**Issue by heyalistair** [playgameservices/play-games-plugin-for-unity#1413]
To reproduce:
1) Create a new project (I'm using Unity 5.4.1p3)
2) Switch to Android build platform
3) Double click the GooglePlayGamesPlugin 0.9.34 package to install the plugin
4) Double click the Google Mobile Ads 3.0.7 package to install the plugin 

First, we have an error that says
`Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs(113,47): error CS1501: No overload for method 'DoResolution' takes '3' arguments`
This can be fixed by looking into:
https://github.com/googleads/googleads-mobile-unity/issues/272

Next, we have an error:
```
FileNotFoundException: Could not find file "/Users/XXX/YYY/ZZZ/UnityGooglePluginTest/support-v4-.pom".
System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileStream.cs:305)
System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share)
(wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
System.IO.File.OpenRead (System.String path) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/File.cs:363)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/StreamReader.cs:167)
System.IO.StreamReader..ctor (System.String path)
(wrapper remoting-invoke-with-check) System.IO.StreamReader:.ctor (string)
Google.JarResolver.PlayServicesSupport.GetDependencies (Google.JarResolver.Dependency dep)
Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest)
GooglePlayServices.ResolverVer1_1.DoResolutionNoAndroidPackageChecks (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation) (at Assets/PlayServicesResolver/Editor/ResolverVer1_1.cs:551)
GooglePlayServices.ResolverVer1_1+<DoResolution>c__AnonStorey5.<>m__9 () (at Assets/PlayServicesResolver/Editor/ResolverVer1_1.cs:328)
GooglePlayServices.ResolverVer1_1.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation, System.Action resolutionComplete) (at Assets/PlayServicesResolver/Editor/ResolverVer1_1.cs:377)
GooglePlayServices.PlayServicesResolver.Resolve (System.Action resolutionComplete) (at Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:221)
GooglePlayServices.PlayServicesResolver.AutoResolve () (at Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs:158)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:222)
```

(Edited: Forgot to mention the 'DoResolution' Error)

**Comment by SilkyPantsDan** [comment]
Was having the same problem, seem to have cleared up the error by simply changing this line in GPGSDependencies.cs

`// Marshmallow permissions requires app-compat`
`svcSupport.DependOn("com.android.support",  "support-v4",  "23.1+");`

to read the following (really just adding .0 to match the definitions in AdMobDepenencies)

`// Marshmallow permissions requires app-compat`
`svcSupport.DependOn("com.android.support",  "support-v4",  "23.1.0+");`

**Comment by heyalistair** [comment]
Oh that's smarter. I actually just commented that line out and let AdMobDependencies.cs totally handle that DependOn.

And then I had another (final) error at runtime when I tried to get the access token, identical to #1339. The solution they provided there worked for me but I think its cleaner if you use the `svcSupport`, like above.

So I added to GPGSDependencies.cs
```
svcSupport.DependOn("com.google.android.gms", "play-services-auth", PluginVersion.PlayServicesVersionConstraint);
```

I'm not sure that everyone encounters this error though. Your mileage may vary.

**Comment by heyalistair** [comment]
I also had a final bonus conflict with the Facebook SDK plugin for Unity, which packs it's own support-v4 library. Probably outside the scope of this GitHub repository, I know.

I had to navigate to /Assets/FacebookSDK/Plugins/Android/libs/support-v4-23.4.0.aar and remove it from the Android build Unity's "Import Settings" inspector panel.

**Comment by claywilkinson** [comment]
0.9.35 syncs up the resolver code with admob.  In the case of other plugins including the support library, you'll have to delete the older one.  You might also want to let the other plugin provider not to include the support library, or consider using the [Unity Jar Resolver](https://github.com/googlesamples/unity-jar-resolver).
