### ISSUE TITLE
Always 0 Google Plus Friends

### ISSUE THREAD

**Issue by ZenithCode** [playgameservices/play-games-plugin-for-unity#1415]
I'm trying to load Google Plus friends but this always returns 0 even though I have several '_followers_' and '_following_' in Google Plus account.

`Social.localUser.LoadFriends((success) =>
            {
                Debug.Log("Friends loaded OK: " + success + " count: " + Social.localUser.friends.Length);
            });
`
Is this still supported?
Thanks.

**Comment by danCodojo** [comment]
Hi, 
I have the exact same issue, using android devices with Unity 5.4.1f1. I get a callback with 0 friends. This is an essential part of a social platform 

If I use google's ui call, below, I am able to view friends and recently played players but I'd prefer to use my own customised UI. There must be something broken with the call if I am able to view players using google's ui.

PlayGamesPlatform.Instance.TurnBased.CreateWithInvitationScreen

**Comment by hevey** [comment]
Hey, Same issue here however other people that run the same codebase don't have the same problem.

**Comment by GDelkos** [comment]
Any luck on this one i am facing the same problem!

**Comment by GDelkos** [comment]
Bump on this one please still getting list 0 :(

**Comment by skikklesman** [comment]
I am also having the same issue.  I am using `PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
        .RequireGooglePlus()
        .Build();` to create the configuration and have checked the "Enable Google+ API Access" checkbox in the Google Play Games Android configuration window in the editor.  Both of my test gmail accounts are following each other on Google+.  My LoadFriends call is returning successful but always with an empty list.  Is there some setting I'm missing?  I feel there must, if it works for some people.

**Comment by ZenithCode** [comment]
@skikklesman  it used to work before so I'm thinking its a GPG server issue.

**Comment by vws0213** [comment]
Same issue here. Can you fix it?

**Comment by GDelkos** [comment]
any updates here? @ZenithCode  are u able to load friends now?

**Comment by ZenithCode** [comment]
No @GDelkos - its from Google's backend. They are the ones that need to fix this.

**Comment by vws0213** [comment]
Somebody should contact Google to fix this. It's a blocker issue.

**Comment by GDelkos** [comment]
@ZenithCode did u  or anyone else try to contact them?

**Comment by ZenithCode** [comment]
@claywilkinson is the Google guy taking care of this plugin! My recommendation would be to switch to other plugins if you still can as support here is very slow if any.

**Comment by GDelkos** [comment]
@ZenithCode any recommendations would be much loved! thank you in advance

**Comment by claywilkinson** [comment]
The Play Game Services and Google Plus are in the process of no longer being integrated.  As a result, these "social" APIs, will return empty lists.  More information is at: https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html
