### ISSUE TITLE
GPGS concept question

### ISSUE THREAD

**Issue by kkondarev** [playgameservices/play-games-plugin-for-unity#1419]
hi, I saw it is possible to write to GPGS in offline mode - e.g. authenticated to GPGS, but device is offline - I can call GPGS APIs and get a Success response.
Does GPGS sync on it's own when device goes online, or this should be triggered somehow?

**Comment by claywilkinson** [comment]
The syncing is done automatically in the background.

**Comment by kkondarev** [comment]
Thank you! 👍
