### ISSUE TITLE
Cant Get friends list to work

### ISSUE THREAD

**Issue by GDelkos** [playgameservices/play-games-plugin-for-unity#1421]
Hi there after struggling to make my app log in and setup my devs console i am facing a weird problem
i cant get the friends list from the google account that i am using.
On my google account i am following a bunch of people!

Code that i am using.

`public void GetFriends()
    {
        if (Social.localUser.authenticated) {
            Social.localUser.LoadFriends((ok) =>  {
                text.text = "Friends Loaded" + Social.localUser.friends.Length.ToString();
                foreach(IUserProfile p in Social.localUser.friends) {
                    googleFriendList.Add(p.userName);
                }
                flist = FriendsList (prefab, googleFriendList,parent);
                text.text = googleFriendList [0];
            });
        }
    }`

It was not working at all, adding 

`PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().RequireGooglePlus().Build();
        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.DebugLogEnabled = true;
        PlayGamesPlatform.Activate();`
Did the trick but now i am also getting a 0 for return.
Can anyone help on this?
Are the friends (on friendslist) people you follow?

thank you in advance

**Comment by claywilkinson** [comment]
The Play Game Services and Google Plus are in the process of no longer being integrated. As a result, these "social" APIs, will return empty lists. More information is at: https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html
