### ISSUE TITLE
Cannot delete `play-services-*-8.4.0.aar`

### ISSUE THREAD

**Issue by Qbit86** [playgameservices/play-games-plugin-for-unity#1422]
Cannot delete `play-services-*-8.4.0.aar`s from my project — they are instantly restored.

----

Unity 5.3.6p6 on Windows 10 Pro targeting Android. Latest Android SDK installed with all components updated via Android SDK Manager.

**Comment by claywilkinson** [comment]
The latest version of the plugin (0.9.35) fixes this.
