### ISSUE TITLE
Resolver expands `play-services-measurement-8.4.0` and it causes dex error

### ISSUE THREAD

**Issue by Qbit86** [playgameservices/play-games-plugin-for-unity#1423]
This set of `play-services-*-9.6.1.aar`s (resolved from Android SDK `extras/`) compiles and runs (so far?) with no errors:
+ play-services-ads-9.6.1
+ play-services-base-9.6.1
+ play-services-basement-9.6.1
+ play-services-drive-9.6.1
+ play-services-games-9.6.1
+ play-services-gcm-9.6.1
+ play-services-nearby-9.6.1
+ play-services-plus-9.6.1
+ play-services-tasks-9.6.1

But when I press “Resolve Client Jars” menu item, Resolver additionally restores `play-services-measurement-8.4.0/` (probably due to some another plugin), and this breaks the build:

```
CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
...
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzpz;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqa;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqa$zza;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqb;
4 errors; aborting
```

How can I find out which plugin makes Resolver to restore conflicting `play-services-measurement-8.4.0`?

----

Unity 5.3.6p6 on Windows 10 Pro targeting Android. Latest Android SDK installed with all components updated via Android SDK Manager.

**Comment by claywilkinson** [comment]
This should be fixed now in the latest version (0.9.35) - it contains a new version of the jar resolver.
