### ISSUE TITLE
Conflict: play-services-base-9.6.1 vs. play-services-measurement-8.4.0

### ISSUE THREAD

**Issue by Qbit86** [playgameservices/play-games-plugin-for-unity#1424]
When Jar Resolver resolves both `play-services-base-9.6.1.aar` and `play-services-measurement-8.4.0/` (`aar` exploded as folder), then build fails with conflict:
```
CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
...
stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzpz;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqa;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqa$zza;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqb;
4 errors; aborting
]
```

----

Unity 5.3.6p6 on Windows 10 Pro targeting Android. Latest Android SDK installed with all components updated via Android SDK Manager.

**Comment by claywilkinson** [comment]
We've updated the jar resolver, if you use the latest version of the plugin (0.9.35) it will update everything correctly.  All the aar files should be the same version (in your case 9.6.1).  If it does not work the first time, close Unity, delete all the .aar files, and re-open Unity.

**Comment by Qbit86** [comment]
@claywilkinson, it doesn't work.

I've removed old `play-services-*-8.4.0.aar`s, restarted Unity. Manually invoked menu item Assets > Play Services Resolver > Android Resolver > Resolve Client Jars. No `play-services-*-9.6.1.aar`s appeared. Got
```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.HashSet`1[System.String]].get_Item (System.String key) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:150)
Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest)
GooglePlayServices.ResolverVer1_1.DoResolutionNoAndroidPackageChecks (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation)
GooglePlayServices.ResolverVer1_1+<DoResolution>c__AnonStorey1.<>m__0 ()
GooglePlayServices.ResolverVer1_1.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation, System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.Resolve (System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.MenuResolve ()
```

**Comment by claywilkinson** [comment]
You can delete ProjectSettings/GoogleDependencyGooglePlayGames.xml and rerun the resolution.  It seems to happen sometimes when upgrading, and should not happen again.

**Comment by Qbit86** [comment]
@claywilkinson Looks like issue inside `PlayServicesSupport`: <https://github.com/playgameservices/play-games-plugin-for-unity/issues/1428>

**Comment by claywilkinson** [comment]
OK to close this issue and track resolution in #1428?
