### ISSUE TITLE
App Crashes when closing after auth

### ISSUE THREAD

**Issue by mmeister1203** [playgameservices/play-games-plugin-for-unity#1426]
Hello,

If I login using Social.localUser.Authenticate then close my app in the future, it always crashes with error in the link below...All the functionality of Google Game Services works fine, except when I call Application.Quit() after calling Social.localUser.Authenticate then this occurs. If I don't login the problem doesn't occur.

https://gist.github.com/mmeister1203/cd8718f3b7053b8298427351129b58d1

Some additional notes: I'm using the most recent build 0.9.34. I've tried it on multiple android versions ranging from 2.3 - 7 and this occurs.

**Comment by claywilkinson** [comment]
It looks like the problem happens before the start of your gist - the first few lines are the app shutting down.  Can you share a log that includes the authenticate call and the application.quit call?

Which version of Unity are you using?  I know they have been fixing issues related to calling Quit on Android.

**Comment by claywilkinson** [comment]
Please re-open including the complete log if the problem is still happening.  Thanks!
