### ISSUE TITLE
Unity game crashes on Android when i hit play button 

### ISSUE THREAD

**Issue by gizeh21** [playgameservices/play-games-plugin-for-unity#1429]
Hi, my problem is that i made a game for Android and i have tested it on 3 different devices, but i get the same bug : when i hit play button the game crashes and the device shows a pop up saying : "app name" has stopped working. On unity console i only have one warning that ill attach here, im using the google play games services plugin from Github ,thanks for the help. 
<img width="818" alt="screen shot 2016-10-12 at 12 17 42" src="https://cloud.githubusercontent.com/assets/22664654/19323708/ad48f9fa-9083-11e6-9ebb-00dbb84bb055.png">

**Comment by BicubicStudios** [comment]
Hi, I don't think its an issue related to GPGS. Have you tried to Google the error which is showing to you on Unity Console?

You probably found an issue in your code for app crash, it might be causing because you are using OnMouseDown/OnMouse somewhere in your code.

**Comment by gizeh21** [comment]
Hi, yes i have searched the error on google but i cant get a solution for it, what could i use instead of OnMouseDown ?

**Comment by claywilkinson** [comment]
Mobile devices don't have mice, so you should use the [Input](https://docs.unity3d.com/ScriptReference/Input.html) object to get the touches in your Update loop.
