### ISSUE TITLE
App crashes in iOS 10 when click for invite friend

### ISSUE THREAD

**Issue by NikhilKhoda** [playgameservices/play-games-plugin-for-unity#1430]
Hello, I am having iOS 10 specific issue in my game. App is crashes on iPad with iOS 10 when I try to click on button for Inviting friends.

I have tested this game on Android and it works like charm. Even in iPad when I click on invitation, its showing me the received invitation and I can play the game perfectly after accepting invitation. Its just crashes when I try to invite someone. I don't know why the invite friend is causing App Crash in iOS 10.

Here are my Logs:

You're already signed in.
MultiplayerController:SignInAndStartMultiplayerGameWithFriend()
PanelVSModeSelection:OnButtonFriendsModeClick()
UnityEngine.Events.InvokableCallList:Invoke(Object[])
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.StandaloneInputModule:Process()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

2016-10-13 18:55:14.777134 battlefrogs[1674:294466] Uncaught exception: NSRangeException: **\* -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
(
    0   CoreFoundation                      0x00000001880d41d8 <redacted> + 148
    1   libobjc.A.dylib                     0x0000000186b0c55c objc_exception_throw + 56
    2   CoreFoundation                      0x0000000187fb04ac <redacted> + 0
    3   battlefrogs                         0x0000000100c1bec8 -[NSBundle(GPGAddition) gpg_bundleIconImage] + 176
    4   battlefrogs                         0x0000000100bdab60 -[GPGPeoplePickerFooterView initWithFrame:] + 384
    5   battlefrogs                         0x0000000100bddf0c -[GPGPlayerPickerViewController init] + 356
    6   battlefrogs                         0x0000000100bbb110 -[GPGLauncherController presentPlayerPicker] + 220
    7   battlefrogs                         0x0000000100843bd4 _ZN3gpg14DEFAULT_ON_LOGENS_8LogLevelERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 38792
    8   libdispatch.dylib                   0x0000000103d7125c _dispatch_call_block_and_release + 24
    9
2016-10-13 18:55:14.777449 battlefrogs[1674:294466] **\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
**\* First throw call stack:
(0x1880d41c0 0x186b0c55c 0x187fb04ac 0x100c1bec8 0x100bdab60 0x100bddf0c 0x100bbb110 0x100843bd4 0x103d7125c 0x103d7121c 0x103d76284 0x188081f2c 0x18807fb18 0x187fae048 0x189a31198 0x18df81628 0x18df7c360 0x10008b96c 0x186f905b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by claywilkinson** [comment]
Thanks for the report.

**Comment by BicubicStudios** [comment]
Could you please assist me how can I resolve this OS specific issue? So that I can solve the problem and proceed ahead.

**Comment by tnavadiya** [comment]
Hello Nikhil, Looks like you are not checking if array size is less then or equal to the index you are trying to access OR may be array will be blank and you are trying to access index 0. Please debug more.

**Comment by NikhilKhoda** [comment]
Hi Tushar, actaully we are not dealing with any kind of array in our code. Its actually happening because of GPGS plugin. Because if its an issue of our code then it must create problem on Android version of the game too. But thanks for your suggestion and could you please provide me a code snippet which I can use as an reference in debugging, so that I can debug my game in depth.

Thank you...

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
