### ISSUE TITLE
Conflicts with Admob plugin

### ISSUE THREAD

**Issue by macpatel** [playgameservices/play-games-plugin-for-unity#1431]
I had installed Admob plugin earlier and now wanted to integrate Play Game Plugin.

After installing got below errors 

`
Error	1	The type 'Google.JarResolver.PlayServicesSupport' exists in both 'E:\Game Development\Projects\crane-and-turtle\Assets\AdsAssets\PlayServicesResolver\Editor\JarResolverLib.dll' and 'E:\Game Development\Projects\crane-and-turtle\Assets\PlayServicesResolver\Editor\Google.JarResolver.dll'	E:\Game Development\Projects\crane-and-turtle\Assets\AdsAssets\PlayServicesResolver\Editor\IResolver.cs	74	27	crane-and-turtle.CSharp.Editor
`

The issue seems to be related with compatibility between both the plugins.

Any resolution other than hacking around ?

-Mahesh

**Comment by claywilkinson** [comment]
Are you using the latest version of both plugins?  Can you share the link to the  admob plugin?

As a short term fix, can you delete the PlayServicesResolver inside AdsAssets and keep the top level PlayServicesResolver and see if that works?

**Comment by macpatel** [comment]
@claywilkinson i dont think that would work, because both the jar files have different sizes..

Link to Admob plugin https://github.com/googleads/googleads-mobile-unity

**Comment by claywilkinson** [comment]
are you using version 3.1 of that plugin?
The correct Play Services resolver is 1.2.1.0 - you can see the version number in Google.JarResolver.dll.meta  - there will be a label like gvh_v1.2.1.0

**Comment by claywilkinson** [comment]
@macpatel  - I confirmed with developers of the admob plugin - you can safely delete the Assets/AdsAssets/PlayServicesResolver and use Assets/PlayServicesResolver.

**Comment by macpatel** [comment]
Thanks @claywilkinson .

I may try it in future. but for now i have decided to not integrate this plugin. 

Thank you for your support!

**Comment by claywilkinson** [comment]
Thanks for the response @macpatel  - best of luck with your game!

**Comment by KhubaibQaiser** [comment]
Also facing the same issue.

**Comment by claywilkinson** [comment]
@KhubaibQaiser  - you can delete the Assets/AdAssets/PlayServicesResolver folder.  Does it work then?  Also, you probably want to open another issue that is specific to your situation since this one is closed.
