### ISSUE TITLE
Minimum Android API to work with Google Cloud Saved Games feature

### ISSUE THREAD

**Issue by inessa-aks** [playgameservices/play-games-plugin-for-unity#1434]
**Can you tell me what is the minimum Android API to work with Google Cloud Saved Games feature?**

I am targeting my game to work on Android 4.0.3+ API versions (minimum API level 15).

When I am trying to run CubicPilot test project on my Android 4.2.1 device, Google Cloud Saved Games UI dialog box is not shown when I am selecting save/load progress.

Logcat output shows that there is an error:

Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.internal.zzro.zzg

I am using Android version 4.2.1 that is installed on my mobile device.

API level 15 for Android 4.0.3 is used in my Unity's settings.

When I've searched throught the internet to find the reason of the error, I found that AppOpsManager is operating using API 19.

The error is raised when I am trying to call method given bellow.

((PlayGamesPlatform)Social.Active).SavedGame.ShowSelectSavedGameUI("Save game progress", 4, true, true, SavedGameSelected);

This method has no return argument with error code and I can't found out what is the exact reason of the error.

**Can you tell me does described error mean that Google Cloud Saved Service is not working with Android version bellow Android 4.4.2 (API 19)?**

It's strange, but some of the games on Google Play Store are targeted on Android 4.0+ and allow to use Google Cloud Saved Games.

**So, if there any way to use play-games-plugin-for-unity to run on 4.0+ platforms with Google Cloud Saved Games feature?**

**Comment by claywilkinson** [comment]
Thanks for the feedback.  I'll look into your questions.  In the meantime, you can consult 
https://developer.android.com/about/dashboards/index.html
to see the percentages of devices running each OS version.  By targeting less than 4.4, you are gaining less than 17% of the total Android market since many of the older devices do not have the graphics support needed to run a Unity game.

**Comment by inessa-aks** [comment]
OK. I just wanted to know is there any way to keep these 17% of potential users? Thanks.

**Comment by claywilkinson** [comment]
Understood :)  - I'll let you know what I find out.

**Comment by claywilkinson** [comment]
The minimum version is API 14
