### ISSUE TITLE
Unable to find jar in the system path. 0.9.35

### ISSUE THREAD

**Issue by Kaldarash** [playgameservices/play-games-plugin-for-unity#1435]
After following the update advice for updating to 0.9.35 (from 0.9.34), I now get an error when setting up the plugin. (Android) 

Screenshot:
![jarpath](https://cloud.githubusercontent.com/assets/1312434/19387963/f459ae0e-9225-11e6-96e8-24374add03c0.png)

Unity console errors: 
```
WARNING: No compatible versions of com.android.support:support-v4 required by (com.android.support:appcompat-v7:23.1.0+, com.google.android.gms:play-services-basement:9.6.1), will try using the latest version 24.0.0
UnityEngine.Debug:Log(Object)

WARNING: No compatible versions of com.android.support:support-annotations required by (com.android.support:support-v4:23.1+, com.android.support:support-v4:24.0.0), will try using the latest version 24.0.0
UnityEngine.Debug:Log(Object)

Exception: jar not found.
GooglePlayServices.DefaultResolver.FindJavaTool (System.String javaTool)
GooglePlayServices.DefaultResolver.ExtractAar (System.String aarFile, System.String[] extractFilenames, System.String outputDirectory)

Unable to examine AAR file Assets/Plugins/Android\appcompat-v7-23.1.1.aar, err: System.Exception: jar not found.
```

JDK's path is properly linked in Unity, it was working fine with 0.9.34, Unity says it's the right path:
![jdkpath](https://cloud.githubusercontent.com/assets/1312434/19388080/79c65826-9226-11e6-90a9-d1ddd90e0512.png)

In fact, it was working fine with every version of the plugin before this one, so I'm not sure why it's doing this now. Googling the issue, I found one relevant post on stackexchange and someone said that they fixed the issue for themselves by updating the SDK. I believe I'm up-to-date there. Android 7.0 (API 24) SDK Platform 24 rev 2. To be honest, I've never been 100% sure which things from the SDK manager to install, but my games function properly with what I have. Maybe there's an issue there somewhere?

Screenshot of installed stuff:
![sdkmanager](https://cloud.githubusercontent.com/assets/1312434/19388329/b5bcf1d6-9227-11e6-8a5d-af9e564ef113.png)

**Comment by Qbit86** [comment]
@Kaldarash 
Win+R “cmd”
`echo %JAVA_HOME%`
?

**Comment by Kaldarash** [comment]
C:\Users\kaldo>echo %JAVA_HOME%
%JAVA_HOME%

**Comment by Qbit86** [comment]
The message dialog from the first picture in your post suggests: “Either set JAVA_HOME or...”

**Comment by Qbit86** [comment]
@Kaldarash 
> so I'm not sure why it's doing this now. 

Plugin authors just started using `jar` util from JDK.

**Comment by Kaldarash** [comment]
I did read that yeah, but I thought Unity handled that already. I thought by linking it in Unity, it assigned the thing for you. That made sense to me since it always worked fine in the past without ever having to deal with environmental variables. 

Setting JAVA_HOME manually did fix it, but I wonder why the person on stackexchange had the problem fixed simply by updating the SDK, when they had the same error. 

I'm still getting the "no compatible versions of ~" console errors, though.

**Comment by Qbit86** [comment]
> I thought by linking it in Unity, it assigned the thing for you.

(I'm not plugin developer, just passerby lurking in issue tracker searching for solutions for own problems connected with update.) Probably that setting is available for Unity, but not available for plugin authors.

**Comment by Kaldarash** [comment]
Thank you for your help!  Do you know why I'd be getting these errors?
```
WARNING: No compatible versions of com.android.support:support-v4 required by (com.android.support:appcompat-v7:23.1.0+, com.google.android.gms:play-services-basement:9.6.1), will try using the latest version 24.0.0
UnityEngine.Debug:Log(Object)

WARNING: No compatible versions of com.android.support:support-annotations required by (com.android.support:support-v4:23.1+, com.android.support:support-v4:24.0.0), will try using the latest version 24.0.0
UnityEngine.Debug:Log(Object)
```

and do you see anything else I should have for everything to work well? Is it fine to only have the latest versions of the tools?

**Comment by Qbit86** [comment]
> Do you know why I'd be getting these errors?

They are harmless, see discussion here: <https://github.com/playgameservices/play-games-plugin-for-unity/issues/1428>

**Comment by Kaldarash** [comment]
Awesome, thank you again!

**Comment by Ziaxp** [comment]
I faced the same problem. And now got rid of it via follow these basic steps. For Windows Users

Right click on 'My Computers' and open 'Properties'.
In Windows Vista, Win7, Go to "Advanced System Settings". ...
Go to 'Advanced Tab' and click on Environment Variables button.
Select 'Path' under the list of 'System Variables', and press Edit and add C:\Program Files\java\jdk\bin after a semicolon. (only in In Windows Vista, Win7) and Win8 and Win10, just Add New and put this path.

Note that the path given is my path sample, you please go to C:\ and check your jdk\bin path in Program Files\Java, and then copy the path and follow the above steps. Enjoy.
