### ISSUE TITLE
WARNING: No compatible versions of com.android.support:support-annotations

### ISSUE THREAD

**Issue by BloodJohn** [playgameservices/play-games-plugin-for-unity#1439]
So I've tried implementing Google Play Services in my Unity project. The problem is, that these two warnings always appear Warnings in Unity

http://stackoverflow.com/questions/40040566/googleplaygamesplugin-0-9-35-and-unity-5-4-2f1-warning-no-compatible-versions

**Comment by BloodJohn** [comment]
WARNING: No compatible versions of com.android.support:support-v4 required by (com.google.android.gms:play-services-basement:9.6.1), will try using the latest version 24.0.0
UnityEngine.Debug:Log(Object)
Google.JarResolver.PlayServicesSupport:Log(String, Boolean)
Google.JarResolver.PlayServicesSupport:ResolveDependencies(Boolean)
GooglePlayServices.ResolverVer1_1:DoResolutionNoAndroidPackageChecks(PlayServicesSupport, String, OverwriteConfirmation)
GooglePlayServices.<DoResolution>c__AnonStorey1:<>m__0()
GooglePlayServices.ResolverVer1_1:DoResolution(PlayServicesSupport, String, OverwriteConfirmation, Action)
GooglePlayServices.PlayServicesResolver:Resolve(Action)
GooglePlayServices.PlayServicesResolver:AutoResolve()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by BloodJohn** [comment]
WARNING: No compatible versions of com.android.support:support-annotations required by (com.android.support:support-v4:23.1+, com.android.support:support-v4:24.0.0), will try using the latest version 24.0.0
UnityEngine.Debug:Log(Object)
Google.JarResolver.PlayServicesSupport:Log(String, Boolean)
Google.JarResolver.PlayServicesSupport:ResolveDependencies(Boolean)
GooglePlayServices.ResolverVer1_1:DoResolutionNoAndroidPackageChecks(PlayServicesSupport, String, OverwriteConfirmation)
GooglePlayServices.<DoResolution>c__AnonStorey1:<>m__0()
GooglePlayServices.ResolverVer1_1:DoResolution(PlayServicesSupport, String, OverwriteConfirmation, Action)
GooglePlayServices.PlayServicesResolver:Resolve(Action)
GooglePlayServices.PlayServicesResolver:AutoResolve()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by Qbit86** [comment]
This warnings are harmless: <https://github.com/playgameservices/play-games-plugin-for-unity/issues/1428#issuecomment-253532049>

**Comment by BloodJohn** [comment]
Failed to compile resources with the following parameters:
-bootclasspath "D:/Android/sdk\platforms\android-24\android.jar" -d "D:\Projects\Unity\PROJECT\Temp\StagingArea\bin\classes" -source 1.6 -target 1.6 -encoding UTF-8 "android\support\v4\R.java" "com\google\android\gms\R.java" "com\google\android\gms\analytics\R.java" "com\google\android\gms\auth\R.java" "com\google\android\gms\auth\api\R.java" "com\google\android\gms\base\R.java" "com\google\android\gms\drive\R.java" "com\google\android\gms\games\R.java" "com\google\android\gms\nearby\R.java" "com\google\android\gms\tasks\R.java" "com\google\example\games\mainlibproj\R.java" "com\google\firebase\R.java" "com\StarAge\IceLand\R.java"
warning: D:\Android\sdk\platforms\android-24\android.jar(java/lang/Object.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: D:\Android\sdk\platforms\android-24\android.jar(java/lang/AutoCloseable.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
2 warnings

UnityEditor.HostView:OnGUI()

**Comment by BloodJohn** [comment]
The path you specified does not look like a valid JDK installation. Android development requres at least JDK 7 (1.7),
having JRE only is not enough. Please make sure you are selecting a suitable JDK home directory, or download and install latest JDK:
http://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by BloodJohn** [comment]
http://stackoverflow.com/questions/24945837/why-unity3d-can-not-find-java-for-android-sdk

**Comment by BloodJohn** [comment]
CommandInvokationFailure: Unable to convert classes into dex format.
D:/Program Files/Java/jdk1.8.0_102\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="D:/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "D:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/FirebaseApiNotAvailableException;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/FirebaseException;
2 errors; aborting
]
stdout[
processing archive D:\Projects\Unity\AncientTech_LD36\Temp\StagingArea\android-libraries\MainLibProj\libs\.\play-games-plugin-support.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/games/
ignored resource com/google/games/bridge/
processing com/google/games/bridge/BuildConfig.class...
processing com/google/games/bridge/NativeBridgeActivity.class...
processing com/google/games/bridge/TokenFragment.class...
processing com/google/games/bridge/TokenFragment$1.class...
processing com/google/games/bridge/TokenFragment$TokenRequest.class...
processing com/google/games/bridge/TokenPendingResult.class...
processing com/google/games/bridge/TokenResult.class...
processing archive D:\Projects\Unity\AncientTech_LD36\Temp\StagingArea\android-libraries\firebase-common-9.0.2\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/internal/
processing com/google/android/gms/internal/zzaiy.class...
processing com/google/android/gms/internal/zzaiz.class...
processing com/google/android/gms/internal/zzaja.class...
processing com/google/android/gms/internal/zzajb.class...
ignored resource com/google/firebase/
processing com/google/firebase/FirebaseApiNotAvailableException.class...
processing com/google/firebase/FirebaseApp.class...
processing com/google/firebase/FirebaseApp$zza.class...
processing com/google/firebase/FirebaseApp$zzb.class...
processing com/google/firebase/FirebaseException.class...
processing com/google/firebase/FirebaseNetworkException.class...
processing com/google/firebase/FirebaseOptions.class...
processing com/google/firebase/FirebaseOptions$1.class...
processing com/google/firebase/FirebaseOptions$Builder.class...
processing com/google/firebase/FirebaseTooManyRequestsException.class...
ignored resource com/google/firebase/auth/
processing com/google/firebase/auth/AuthCredential.class...
processing com/google/firebase/auth/AuthResult.class...
processing com/google/firebase/auth/FirebaseAuthException.class...
processing com/google/firebase/auth/FirebaseUser.class...
processing com/google/firebase/auth/GetTokenResult.class...
processing com/google/firebase/auth/UserInfo.class...
processing com/google/firebase/auth/UserProfileChangeRequest.class...
processing com/google/firebase/auth/UserProfileChangeRequest$Builder.class...
processing com/google/firebase/auth/zza.class...
ignored resource com/google/firebase/provider/
processing com/google/firebase/provider/FirebaseInitProvider.class...
processing archive D:\Projects\Unity\AncientTech_LD36\Temp\StagingArea\android-libraries\play-services-analytics-9.6.1\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/analytics/
processing com/google/android/gms/analytics/AnalyticsReceiver.class...
processing com/google/android/gms/analytics/AnalyticsService.class...
processing archive D:\Projects\Unity\AncientTech_LD36\Temp\StagingArea\android-libraries\play-services-auth-9.6.1\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/auth/
ignored resource com/google/android/gms/auth/api/
processing com/google/android/gms/auth/api/Auth.class...
processing com/google/android/gms/auth/api/Auth$1.class...
processing com/google/android/gms/auth/api/Auth$2.class...
processing com/google/android/gms/auth/api/Auth$3.class...
processing com/google/android/gms/auth/api/Auth$AuthCredentialsOptions.class...
processing com/google/android/gms/auth/api/Auth$AuthCredentialsOptions$Builder.class...
ignored resource com/google/android/gms/auth/api/credentials/
processing com/google/android/gms/auth/api/credentials/Credential.class...
processing com/google/android/gms/auth/api/credentials/Credential$Builder.class...
processing com/google/android/gms/auth/api/credentials/CredentialPickerConfig.class...
processing com/google/android/gms/auth/api/credentials/CredentialPickerConfig$1.class...
processing com/google/android/gms/auth/api/credentials/CredentialPickerConfig$Builder.class...
processing com/google/android/gms/auth/api/credentials/CredentialPickerConfig$Prompt.class...
processing com/google/android/gms/auth/api/credentials/CredentialRequest.class...
processing com/google/android/gms/auth/api/credentials/CredentialRequest$1.class...
processing com/google/android/gms/auth/api/credentials/CredentialRequest$Builder.class...
processing com/google/android/gms/auth/api/credentials/CredentialRequestResult.class...
processing com/google/android/gms/auth/api/credentials/CredentialsApi.class...
processing com/google/android/gms/auth/api/credentials/HintRequest.class...
processing com/google/android/gms/auth/api/credentials/HintRequest$1.class...
processing com/google/android/gms/auth/api/credentials/HintRequest$Builder.class...
processing com/google/android/gms/auth/api/credentials/IdToken.class...
processing com/google/android/gms/auth/api/credentials/IdentityProviders.class...
processing com/google/android/gms/auth/api/credentials/PasswordSpecification.class...
processing com/google/android/gms/auth/api/credentials/PasswordSpecification$zza.class...
processing com/google/android/gms/auth/api/credentials/PasswordSpecification$zzb.class...
ignored resource com/google/android/gms/auth/api/credentials/internal/
processing com/google/android/gms/auth/api/credentials/internal/DeleteRequest.class...
processing com/google/android/gms/auth/api/credentials/internal/GeneratePasswordRequest.class...
processing com/google/android/gms/auth/api/credentials/internal/SaveRequest.class...
processing com/google/android/gms/auth/api/credentials/internal/zza.class...
processing com/google/android/gms/auth/api/credentials/internal/zzb.class...
processing com/google/android/gms/auth/api/credentials/internal/zzc.class...
processing com/google/android/gms/auth/api/credentials/internal/zzd.class...
processing com/google/android/gms/auth/api/credentials/internal/zze.class...
processing com/google/android/gms/auth/api/credentials/internal/zze$1.class...
processing com/google/android/gms/auth/api/credentials/internal/zze$1$1.class...
processing com/google/android/gms/auth/api/credentials/internal/zze$2.class...
processing com/google/android/gms/auth/api/credentials/internal/zze$3.class...
processing com/google/android/gms/auth/api/credentials/internal/zze$4.class...
processing com/google/android/gms/auth/api/credentials/internal/zze$zza.class...
processing com/google/android/gms/auth/api/credentials/internal/zzf.class...
processing com/google/android/gms/auth/api/credentials/internal/zzg.class...
processing com/google/android/gms/auth/api/credentials/internal/zzh.class...
processing com/google/android/gms/auth/api/credentials/internal/zzi.class...
processing com/google/android/gms/auth/api/credentials/internal/zzj.class...
processing com/google/android/gms/auth/api/credentials/internal/zzj$zza.class...
processing com/google/android/gms/auth/api/credentials/internal/zzj$zza$zza.class...
processing com/google/android/gms/auth/api/credentials/internal/zzk.class...
processing com/google/android/gms/auth/api/credentials/internal/zzk$zza.class...
processing com/google/android/gms/auth/api/credentials/internal/zzk$zza$zza.class...
processing com/google/android/gms/auth/api/credentials/internal/zzl.class...
processing com/google/android/gms/auth/api/credentials/zza.class...
processing com/google/android/gms/auth/api/credentials/zzb.class...
processing com/google/android/gms/auth/api/credentials/zzc.class...
processing com/google/android/gms/auth/api/credentials/zzd.class...
processing com/google/android/gms/auth/api/credentials/zze.class...
processing com/google/android/gms/auth/api/credentials/zzf.class...
ignored resource com/google/android/gms/auth/api/signin/
processing com/google/android/gms/auth/api/signin/GoogleSignInApi.class...
processing com/google/android/gms/auth/api/signin/GoogleSignInResult.class...
processing com/google/android/gms/auth/api/signin/GoogleSignInStatusCodes.class...
processing com/google/android/gms/auth/api/signin/RevocationBoundService.class...
processing com/google/android/gms/auth/api/signin/SignInAccount.class...
ignored resource com/google/android/gms/auth/api/signin/internal/
processing com/google/android/gms/auth/api/signin/internal/SignInConfiguration.class...
processing com/google/android/gms/auth/api/signin/internal/SignInHubActivity.class...
processing com/google/android/gms/auth/api/signin/internal/SignInHubActivity$1.class...
processing com/google/android/gms/auth/api/signin/internal/SignInHubActivity$zza.class...
processing com/google/android/gms/auth/api/signin/internal/zza.class...
processing com/google/android/gms/auth/api/signin/internal/zzb.class...
processing com/google/android/gms/auth/api/signin/internal/zzc.class...
processing com/google/android/gms/auth/api/signin/internal/zzc$1.class...
processing com/google/android/gms/auth/api/signin/internal/zzc$1$1.class...
processing com/google/android/gms/auth/api/signin/internal/zzc$2.class...
processing com/google/android/gms/auth/api/signin/internal/zzc$2$1.class...
processing com/google/android/gms/auth/api/signin/internal/zzc$3.class...
processing com/google/android/gms/auth/api/signin/internal/zzc$3$1.class...
processing com/google/android/gms/auth/api/signin/internal/zzc$zza.class...
processing com/google/android/gms/auth/api/signin/internal/zzd.class...
processing com/google/android/gms/auth/api/signin/internal/zzf.class...
processing com/google/android/gms/auth/api/signin/internal/zzf$zza.class...
processing com/google/android/gms/auth/api/signin/internal/zzg.class...
processing com/google/android/gms/auth/api/signin/internal/zzg$zza.class...
processing com/google/android/gms/auth/api/signin/internal/zzg$zza$zza.class...
processing com/google/android/gms/auth/api/signin/internal/zzh.class...
processing com/google/android/gms/auth/api/signin/internal/zzh$zza.class...
processing com/google/android/gms/auth/api/signin/internal/zzh$zza$zza.class...
processing com/google/android/gms/auth/api/signin/internal/zzi.class...
processing com/google/android/gms/auth/api/signin/internal/zzj.class...
processing com/google/android/gms/auth/api/signin/zzc.class...
ignored resource com/google/android/gms/internal/
processing com/google/android/gms/internal/zzni.class...
processing com/google/android/gms/internal/zznj.class...
processing com/google/android/gms/internal/zznk.class...
processing com/google/android/gms/internal/zznl.class...
processing com/google/android/gms/internal/zznl$zza.class...
processing com/google/android/gms/internal/zznl$zza$zza.class...
processing com/google/android/gms/internal/zznm.class...
processing com/google/android/gms/internal/zznm$zza.class...
processing com/google/android/gms/internal/zznm$zza$zza.class...
processing archive D:\Projects\Unity\AncientTech_LD36\Temp\StagingArea\android-libraries\play-services-auth-base-9.6.1\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/auth/
processing com/google/android/gms/auth/AccountChangeEvent.class...
processing com/google/android/gms/auth/AccountChangeEventsRequest.class...
processing com/google/android/gms/auth/AccountChangeEventsResponse.class...
processing com/google/android/gms/auth/GoogleAuthException.class...
processing com/google/android/gms/auth/GoogleAuthUtil.class...
processing com/google/android/gms/auth/GooglePlayServicesAvailabilityException.class...
processing com/google/android/gms/auth/TokenData.class...
processing com/google/android/gms/auth/UserRecoverableAuthException.class...
processing com/google/android/gms/auth/UserRecoverableNotifiedException.class...
ignored resource com/google/android/gms/auth/account/
processing com/google/android/gms/auth/account/WorkAccount.class...
processing com/google/android/gms/auth/account/WorkAccount$1.class...
processing com/google/android/gms/auth/account/WorkAccountApi.class...
processing com/google/android/gms/auth/account/WorkAccountApi$AddAccountResult.class...
processing com/google/android/gms/auth/account/zza.class...
processing com/google/android/gms/auth/account/zza$zza.class...
processing com/google/android/gms/auth/account/zza$zza$zza.class...
processing com/google/android/gms/auth/account/zzb.class...
processing com/google/android/gms/auth/account/zzb$zza.class...
processing com/google/android/gms/auth/account/zzb$zza$zza.class...
ignored resource com/google/android/gms/auth/api/
ignored resource com/google/android/gms/auth/api/proxy/
processing com/google/android/gms/auth/api/proxy/AuthApiStatusCodes.class...
processing com/google/android/gms/auth/api/proxy/ProxyApi.class...
processing com/google/android/gms/auth/api/proxy/ProxyApi$ProxyResult.class...
processing com/google/android/gms/auth/api/proxy/ProxyGrpcRequest.class...
processing com/google/android/gms/auth/api/proxy/ProxyRequest.class...
processing com/google/android/gms/auth/api/proxy/ProxyRequest$Builder.class...
processing com/google/android/gms/auth/api/proxy/ProxyResponse.class...
processing com/google/android/gms/auth/api/proxy/zza.class...
processing com/google/android/gms/auth/api/proxy/zzb.class...
processing com/google/android/gms/auth/api/proxy/zzc.class...
processing com/google/android/gms/auth/api/zza.class...
processing com/google/android/gms/auth/api/zza$1.class...
processing com/google/android/gms/auth/api/zzb.class...
processing com/google/android/gms/auth/zza.class...
processing com/google/android/gms/auth/zzb.class...
processing com/google/android/gms/auth/zzc.class...
processing com/google/android/gms/auth/zzd.class...
processing com/google/android/gms/auth/zze.class...
processing com/google/android/gms/auth/zze$1.class...
processing com/google/android/gms/auth/zze$2.class...
processing com/google/android/gms/auth/zze$3.class...
processing com/google/android/gms/auth/zze$4.class...
processing com/google/android/gms/auth/zze$zza.class...
processing com/google/android/gms/auth/zzf.class...
ignored resource com/google/android/gms/internal/
processing com/google/android/gms/internal/zzbw.class...
processing com/google/android/gms/internal/zzbw$zza.class...
processing com/google/android/gms/internal/zzbw$zza$zza.class...
processing com/google/android/gms/internal/zzng.class...
processing com/google/android/gms/internal/zzng$1.class...
processing com/google/android/gms/internal/zzng$2.class...
processing com/google/android/gms/internal/zzng$2$1.class...
processing com/google/android/gms/internal/zzng$3.class...
processing com/google/android/gms/internal/zzng$3$1.class...
processing com/google/android/gms/internal/zzng$zza.class...
processing com/google/android/gms/internal/zzng$zzb.class...
processing com/google/android/gms/internal/zzng$zzc.class...
processing com/google/android/gms/internal/zznh.class...
processing com/google/android/gms/internal/zznn.class...
processing com/google/android/gms/internal/zzno.class...
processing com/google/android/gms/internal/zznp.class...
processing com/google/android/gms/internal/zznp$zza.class...
p<message truncated>

**Comment by BloodJohn** [comment]
After removing play-services-analytics (and firebase-common) it's working !!!
it's been a hectic weekend for me.
fixed.

**Comment by AustinRau** [comment]
@BloodJohn Same here, been a long week trying to get GPGS to play nice with my other plugins! 😂

**Comment by NipunJain10** [comment]
From where do we remove this play-services-analytics (and firebase-common)?

**Comment by attmaxess** [comment]
In my case, I have to delete the GoogleDependencyGooglePlayGames.xml file in Project Setting folder 😭 my head exploded already

**Comment by jayswebworks** [comment]
How did you delete firebase-common and play-services -analytics? For me they keep getting recreated perhaps by the firebase plugin or play services resolver?

**Comment by jayswebworks** [comment]
Ah, yes after deleting some editor extensions I was able to delete them too. Still doesn't let me build for android however :(

**Comment by satyagames** [comment]
WARNING: No compatible versions of com.android.support:support-v4 required by (com.google.android.gms:play-services-basement:9.8.0), will try using the latest version 24.0.0

Someone please reply me with soluation... 
![googleplayservices warning](https://cloud.githubusercontent.com/assets/7609853/20420118/4a327c2c-ad81-11e6-8110-167e090f734f.png)

**Comment by satyagames** [comment]
WARNING: No compatible versions of com.android.support:support-v4 required by (com.google.android.gms:play-services-basement:9.8.0), will try using the latest version 24.0.0

Please someone slove this problem...

![googleplayservices warning](https://cloud.githubusercontent.com/assets/7609853/20421112/f6032e38-ad87-11e6-9683-32b1b309659b.png)

**Comment by claywilkinson** [comment]
That warning is annoying, but harmless.  Version 24.0.0 will work.  Is it OK to close this issue?

**Comment by satyagames** [comment]
No, Still i am facing the same Issue and now "Google Play Login". also doesn't seem to be 
working because of the warning. Kindly check the screenshot for better insight.

![failedtosignin](https://cloud.githubusercontent.com/assets/7609853/21476580/b4300a58-cb5f-11e6-8a04-3b7cfda3842d.PNG)

# Failed to sign in with Google Play Games.

**Comment by claywilkinson** [comment]
@satyagames - The warning is harmless - if it was a problem, you would not be able to create an APK.  Can you open a new issue including your log of trying to authenticate?  Also, things to double check:

1. You pasted in the Android resources from the Play Developer console for your game in the Android Setup for this plugin.
2. That the SHA1 fingerprint of the keystore you are using in Unity matches what is entered for the Android linked app in the Play Developer console.
3. That the account you are using on the device is added as a tester to your game in the Play Developer console.

**Comment by claywilkinson** [comment]
Great!

**Comment by phonoks** [comment]
What fixed this issue for me is to put minimum android build to 4.0 in unity build settings

**Comment by Hyperkettu** [comment]
I have the same issue Google Play login crashes/restarts the app. Help me? How to check that the SHA1 fingerprint of the keystore I am using in Unity matches what is entered for the Android linked app in the Play Developer console?

**Comment by qbit86** [comment]
> How to check that the SHA1 fingerprint of the keystore

@Hyperkettu Find `keytool` application somewhere in JDK install directory, and change current dir to that path in command prompt. For example in Windows:
`cd C:\Users\MyUsername\Bin\jdk1.8.0_45\bin\`

Then run it with some parameters (substitute with your own):
`keytool -exportcert -alias "alias for my key" -keystore "c:\path\to\my.keystore" -list -v`

It will print MD5, SHA1 and SHA256 fingerprints in format of colon separated bytes in hex.

**Comment by Hyperkettu** [comment]
ok I got the keystore SHA1 fingerprint, where can I find the other in Play Console? And what to do if they don't match?
