### ISSUE TITLE
Freezing used Google Play version in Resolver configuration

### ISSUE THREAD

**Issue by inessa-aks** [playgameservices/play-games-plugin-for-unity#1441]
Hi,

I need to keep specific Google Play version in my Unity project since I am using different plugins which are compatible with specific version of Google Play libraries.

I've updated last version of Google Play libraries in Android SDK Manager when I was installing new Android API version on my computer.

Now every time when I open my Unity project with play-games-plugin-for-unity, I am getting warning from Resolver that Google Play libraries are needed to be updated.

I want to keep my current version of Google Play libraries in my Unity project.

So, I check option in dialog box to keep current version of Google Play libraries in my Unity project.

But when I reopen the project this dialog box is opened agian with the same warning.

Can you tell me how can I congfigure Resolver to get rid of this warning by selecting and "freezing" specific version of Google Play libraries that has to be used in my Unity project?

Thanks and Regards,

**Comment by claywilkinson** [comment]
In the Unity menu under Assets/Play Services Resolver/Android Resolver/Settings you can disable background resolution.
