### ISSUE TITLE
No compatible versions of com.android.support:support-v4

### ISSUE THREAD

**Issue by gizeh21** [playgameservices/play-games-plugin-for-unity#1443]
Hi there i just updated the plugin to the last versión and unity its showing me this warning : 
<img width="826" alt="screen shot 2016-10-17 at 13 34 02" src="https://cloud.githubusercontent.com/assets/22664654/19450234/3cb096a0-946e-11e6-86ef-32aabd09cd2e.png">
may i wait for a next update to the plugin ? , what could i do ? , thank you very much.

**Comment by cmorsucci** [comment]
Same problem with 0.9.35 version of the plugin

**Comment by satyagames** [comment]
Same Warning... Some one reply plzzzz....

**Comment by theotto38** [comment]
Same Problem :(

**Comment by claywilkinson** [comment]
The warning is annoying, but harmless, we're working on fixing the dependency versions so this warning does not appear.
