### ISSUE TITLE
ambiguous reference between `UnityEngine.Logger' and `GooglePlayGames.OurUtils.Logger'

### ISSUE THREAD

**Issue by Kshopper93** [playgameservices/play-games-plugin-for-unity#1444]
![image](https://cloud.githubusercontent.com/assets/7681603/19451844/aac24ec8-94ae-11e6-9d04-a3a98f99ba7e.png)

**Comment by claywilkinson** [comment]
Please update to the latest version of the plugin. This issue has been fixed.
