### ISSUE TITLE
Conflicts with Admob plugin

### ISSUE THREAD

**Issue by KhubaibQaiser** [playgameservices/play-games-plugin-for-unity#1445]
I am developing a 2D game in unity and using admob plugin (https://github.com/googleads/googleads-mobile-unity). The problem is when I import the play services plugin and try to build the project the build crashes and gives the error shown in the image. Can you guide me what should I do?
![err](https://cloud.githubusercontent.com/assets/6773396/19465140/1e0f3956-951b-11e6-9690-c981e7dfdec2.png)

**Comment by claywilkinson** [comment]
Does it still conflict if you update both plugins to the latest version?

**Comment by KhubaibQaiser** [comment]
No, it has been resolved in the latest versions.

**Comment by claywilkinson** [comment]
thanks.
