### ISSUE TITLE
Can not generate .xcworkspace file

### ISSUE THREAD

**Issue by beefw** [playgameservices/play-games-plugin-for-unity#1446]
I have integrated Google Admob and Google play service , but it can not generate xcworkspace file 

Podfile

```
source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :integrate_targets => false
platform :ios, '7.0'

target 'Unity-iPhone' do
pod 'GooglePlayGames', '~> 5.0'
end
```

**Comment by hantengx** [comment]
same issue, i upgrade play-games-plugin  v0.9.35

**Comment by mizdler** [comment]
It's because "integrate_targets" is set to false change it to true and it will generate xcworkspace file

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
