### ISSUE TITLE
App crashes with 'JNI DETECTED ERROR IN APPLICATION: obj == null'

### ISSUE THREAD

**Issue by porohkun** [playgameservices/play-games-plugin-for-unity#1447]
Trying to add play games plugin in my app, but it crashes on startup.
Time ago it crashes with other error, but i set savegames in dev console to on and now receive this.

plz help, what may be wrong?

Code:

```
    PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
        .EnableSavedGames()
        .Build();
    PlayGamesPlatform.InitializeInstance(config);
    PlayGamesPlatform.DebugLogEnabled = true;
    PlayGamesPlatform.Activate();
    Social.localUser.Authenticate((bool success) =>
    {
        Debug.Log("++==++== auth: " + success);
        LayersManager.Push<MainMenuLayer>();
        LayersManager.Push<MessageBoxLayer>().Init("Authentification", success ? "done" : "failed");
    });
```

`

Log:

> 10-18 19:37:03.532   197   197 F DEBUG   : **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
> 10-18 19:37:03.532   197   197 F DEBUG   : Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/MOB31E/3142026:user/release-keys'
> 10-18 19:37:03.532   197   197 F DEBUG   : Revision: '11'
> 10-18 19:37:03.532   197   197 F DEBUG   : ABI: 'arm'
> 10-18 19:37:03.533   197   197 F DEBUG   : pid: 10880, tid: 11002, name: main_dispatch  >>> com.owlstudio.lilight <<<
> 10-18 19:37:03.533   197   197 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
> 10-18 19:37:03.556   197   197 F DEBUG   : Abort message: 'art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: obj == null'
> 10-18 19:37:03.556   197   197 F DEBUG   :     r0 00000000  r1 00002afa  r2 00000006  r3 91c5a978
> 10-18 19:37:03.556   197   197 F DEBUG   :     r4 91c5a980  r5 91c5a930  r6 00000001  r7 0000010c
> 10-18 19:37:03.556   197   197 F DEBUG   :     r8 b4c3f378  r9 b4cea800  sl 00000001  fp 00000001
> 10-18 19:37:03.556   197   197 F DEBUG   :     ip 00000006  sp 91c5a480  lr b6c83b61  pc b6c85f50  cpsr 40070010
> 10-18 19:37:03.575   197   197 F DEBUG   : 
> 10-18 19:37:03.575   197   197 F DEBUG   : backtrace:
> 10-18 19:37:03.575   197   197 F DEBUG   :     #00 pc 00041f50  /system/lib/libc.so (tgkill+12)
> 10-18 19:37:03.575   197   197 F DEBUG   :     #01 pc 0003fb5d  /system/lib/libc.so (pthread_kill+32)
> 10-18 19:37:03.575   197   197 F DEBUG   :     #02 pc 0001c30f  /system/lib/libc.so (raise+10)
> 10-18 19:37:03.575   197   197 F DEBUG   :     #03 pc 000194c1  /system/lib/libc.so (__libc_android_abort+34)
> 10-18 19:37:03.575   197   197 F DEBUG   :     #04 pc 000174ac  /system/lib/libc.so (abort+4)
> 10-18 19:37:03.575   197   197 F DEBUG   :     #05 pc 00333971  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+228)
> 10-18 19:37:03.575   197   197 F DEBUG   :     #06 pc 000f45fb  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2226)
> 10-18 19:37:03.575   197   197 F DEBUG   :     #07 pc 0025aa4f  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1550)
> 10-18 19:37:03.575   197   197 F DEBUG   :     #08 pc 0025ae7b  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+74)
> 10-18 19:37:03.575   197   197 F DEBUG   :     #09 pc 00278697  /system/lib/libart.so (_ZN3art3JNI15CallVoidMethodVEP7_JNIEnvP8_jobjectP10_jmethodIDSt9__va_list+470)
> 10-18 19:37:03.575   197   197 F DEBUG   :     #10 pc 000942db  /data/app/com.owlstudio.lilight-2/lib/arm/libgpg.so
> 10-18 19:37:03.575   197   197 F DEBUG   :     #11 pc 0007e44f  /data/app/com.owlstudio.lilight-2/lib/arm/libgpg.so
> 10-18 19:37:03.575   197   197 F DEBUG   :     #12 pc 0005b043  /data/app/com.owlstudio.lilight-2/lib/arm/libgpg.so
> 10-18 19:37:03.576   197   197 F DEBUG   :     #13 pc 0005c041  /data/app/com.owlstudio.lilight-2/lib/arm/libgpg.so
> 10-18 19:37:03.576   197   197 F DEBUG   :     #14 pc 00061f57  /data/app/com.owlstudio.lilight-2/lib/arm/libgpg.so
> 10-18 19:37:03.576   197   197 F DEBUG   :     #15 pc 0009efbd  /data/app/com.owlstudio.lilight-2/lib/arm/libgpg.so
> 10-18 19:37:03.576   197   197 F DEBUG   :     #16 pc 0006233b  /data/app/com.owlstudio.lilight-2/lib/arm/libgpg.so
> 10-18 19:37:03.576   197   197 F DEBUG   :     #17 pc 0006274f  /data/app/com.owlstudio.lilight-2/lib/arm/libgpg.so (_ZNSt6thread5_ImplISt12_Bind_simpleIFSt7_Mem_fnIMN3gpg14OperationQueue4ImplEFvNS3_16InternalCallbackIINS3_8LogLevelERKSsEEEEEPS5_SA_EEE6_M_runEv+42)
> 10-18 19:37:03.576   197   197 F DEBUG   :     #18 pc 000f3123  /data/app/com.owlstudio.lilight-2/lib/arm/libgpg.so
> 10-18 19:37:03.576   197   197 F DEBUG   :     #19 pc 0003f45f  /system/lib/libc.so (_ZL15__pthread_startPv+30)
> 10-18 19:37:03.576   197   197 F DEBUG   :     #20 pc 00019b43  /system/lib/libc.so (__start_thread+6)
> 10-18 19:37:04.773   197   197 F DEBUG   : 
> 10-18 19:37:04.773   197   197 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_01
> 10-18 19:37:04.773   197   197 E DEBUG   : AM write failed: Broken pipe
> 10-18 19:37:04.887   776  1079 I ActivityManager: Process com.owlstudio.lilight (pid 10880) has died
> 10-18 19:37:04.889   776  1079 W ActivityManager: Force removing ActivityRecord{9024c77 u0 com.owlstudio.lilight/com.unity3d.player.UnityPlayerActivity t10361}: app died, no saved state
> 10-18 19:37:04.911   776  1079 I ActivityManager: Config changes=480 {1.0 250mcc99mnc ru_RU ldltr sw360dp w360dp h568dp 480dpi nrml port finger -keyb/v/h -nav/h s.181}

**Comment by claywilkinson** [comment]
I've passed along the stacktrace, can you share the complete log?

**Comment by claywilkinson** [comment]
Please reopen including a complete log if this is still a problem.  Thanks!

**Comment by TrueRaider** [comment]
Perhaps, You need to configure services in google console
