### ISSUE TITLE
REST Api and/or WebGL support

### ISSUE THREAD

**Issue by Noqomo** [playgameservices/play-games-plugin-for-unity#1448]
Hi,

With Unity now supporting publishing to WebGL, can we see this plugin support this build platform.

Also, for many of us who would like to publish to PC & Mac desktop, are you able to please implement REST API?

Thank you.

**Comment by claywilkinson** [comment]
There is a web API: https://developers.google.com/games/services/web/gettingstarted.  At this time, implementing it in the plugin is not a priority.  If you are eager to add it to the plugin, please feel free to submit pull requests to add support.
