### ISSUE TITLE
Building iOS with NO_GPGS

### ISSUE THREAD

**Issue by hippogamesunity** [playgameservices/play-games-plugin-for-unity#1449]
After upgrading to version 35 with NO_GPGS have wrong plugin behaviour:
- pod command executes for iOS build
- some Google libraries are included to xcode project

**Comment by kamend** [comment]
Same problem here too: Unity 5.4.2

**Comment by hippogamesunity** [comment]
@kamend You have to remove this before building (till bugfix):
Assets/GooglePlayGames, Assets/PlayServicesResolver, Assets/Plugins/iOS/GPGSAppController

**Comment by DennisATA** [comment]
What worked for me was changing
`#elif UNITY_IOS`
to
`#elif UNITY_IOS && !NO_GPGS`
on line 96 of GPGSDependencies.cs.

This removes the addition of GooglePlayGames dependency to the build while still allowing other packages to use the resolver.

**Comment by hippogamesunity** [comment]
@DennisATA, cool fix, thanks!

**Comment by claywilkinson** [comment]
This is merged into the unitypackage, version 0.9.36
