### ISSUE TITLE
Cloud save data not propagating(instantly)  5 min delay

### ISSUE THREAD

**Issue by JEOptimal** [playgameservices/play-games-plugin-for-unity#145]
I have two devices setup, using the same account.

I'm using the following for loading
((PlayGamesPlatform)Social.Active).LoadState(0, caller);

and this for saving.
((PlayGamesPlatform)Social.Active).UpdateState(slot,
            cSaveState, caller);

Everything is saved and loaded correctly. It reports that all goes well. But when I load the data on one device it loads the local cached version of the data and not the one saved by the other device.

It can take up to 5 minutes before changes are detected between devices. So everything is working it's just taking so much time!

Anything I can do to force a real check of the cloud data?

**Comment by claywilkinson** [comment]
Closing as obsolete since the app state API is deprecated, please use SavedGames API instead.
