### ISSUE TITLE
BackgroundResolution.cs not found

### ISSUE THREAD

**Issue by KhubaibQaiser** [playgameservices/play-games-plugin-for-unity#1451]
I am using latest package 0.9.35. When I import it there is no BackgroundResolution.cs present in it. I am using Admob plugin and was getting error and decided to do as said in this post (https://github.com/playgameservices/play-games-plugin-for-unity/issues/832) to resolve the issue but I cannot find BackgroundResolution.cs anywhere.

**Comment by Jasper76** [comment]
It looks like in version 0.9.35 you have to edit the GooglePlayGames/Editor/GPGSDependencies.cs file. At least, that worked for me.

**Comment by KhubaibQaiser** [comment]
Solved! The latest version 0.9.35 is working fine with the admob plugin. Thanks.
