### ISSUE TITLE
RTMP Get other player id

### ISSUE THREAD

**Issue by ugurdmrl67** [playgameservices/play-games-plugin-for-unity#1453]
Hi. I have own username, score etc. system. I want get other player's id (not participantid, Social.localuser.id) for authenticate user from my web server. Everythink has been normal so far. I'm sending id in bytes but other player can't acces correct id. For example if my id is : 12345678, other player is getting 000012. How can I fix that ? Sorry for my bad english :)

This is ID sending part of script
```
public void SendID(string id)
	{
		DataList.Clear ();
		DataList.Add ((byte)'I');
		string temp;
		temp= id.Substring(1, 19); // I used substring because player id like "g1234", this method converting id for "1234" 
		float number;
		number= float.Parse (temp);
		DataList.AddRange (System.BitConverter.GetBytes (number));
		byte[] messageToSend= DataList.ToArray ();
		PlayGamesPlatform.Instance.RealTime.SendMessageToAll (false, messageToSend);
	}
```

```
public void OnRealTimeMessageReceived (bool isReliable, string senderId, byte[] data)
{
	char messageType= (char)data [0];
	if (messageType== 'I') {
		if (senderId != PlayGamesPlatform.Instance.RealTime.GetSelf ().ParticipantId) {
			float idFloat = System.BitConverter.ToSingle(data,1);
			OtherPlayerID.SendMessage("Check" , idFloat); //send id for other script 
		}
	}
}
```
Other Script
```
function Check (PlayerID : float) 
{
	var IdInt: int = Mathf.RoundToInt(PlayerID); // I'm using this convertion because PlayerID is incoming from float type, this is causing "123.00" so  I'm converting float to int "123"
	var CheckAccount: WWW = new WWW("myserver.com/CheckUsers.php?id=g" +WWW.EscapeURL(IdInt.ToString("D")));
	yield CheckAccount;
}
```

**Comment by SamMcfly** [comment]
any news about that?

I'm looking for the participant id.

**Comment by ugurdmrl67** [comment]
I fixed the issue. I wanted to get Social.localUser.id and send to other
player.

15 Tem 2017 12:49 tarihinde "SamMcfly" <notifications@github.com> yazdı:

any news about that?

I'm looking for the participant id.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/playgameservices/play-games-plugin-for-unity/issues/1453#issuecomment-315523317>,
or mute the thread

**Comment by SamMcfly** [comment]
Do you know how could i get the opponent user name?

**Comment by ugurdmrl67** [comment]
You need to get social.localuser.name (or username i forget this method :))
on first player. You need to convert string to bytes[]. After converting
bytes, you will send other player. Other player needs to convert bytes[] to
string

15 Tem 2017 19:01 tarihinde "SamMcfly" <notifications@github.com> yazdı:

Do you know how could i get the opponent user name?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/playgameservices/play-games-plugin-for-unity/issues/1453#issuecomment-315543798>,
or mute the thread

**Comment by SamMcfly** [comment]
Is it the only way? a simpler solution must exist.

Because when i receive an invitation from another player, i create a pop up notification in game that shows the opponent Username with this:

`string opponentUserName = mIncomingInvitation.Inviter.DisplayName;`

**Comment by ugurdmrl67** [comment]
I searched so many sources but it looks like this is the only way

16 Tem 2017 11:28 tarihinde "SamMcfly" <notifications@github.com> yazdı:

Is it the only way? a simpler solution must exist.

Because when i receive an invitation from another player, i create a pop up
notification in game that shows the opponent Username with this:

string opponentUserName = mIncomingInvitation.Inviter.DisplayName;

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/playgameservices/play-games-plugin-for-unity/issues/1453#issuecomment-315593928>,
or mute the thread

**Comment by SamMcfly** [comment]
Okay, thanks!

So i came to this for sending the user name to the other player:

`PlayerUserName = PlayGamesPlatform.Instance.RealTime.GetSelf().DisplayName;
var PlayerUserNameBytes = System.Text.Encoding.UTF8.GetBytes(PlayerUserName);
bool reliable = true;
PlayGamesPlatform.Instance.RealTime.SendMessageToAll(reliable, PlayerUserNameBytes);
`

But after how could i receive the other opponent message?

**Comment by ugurdmrl67** [comment]
You need to use getstring method like getbytes

16 Tem 2017 18:20 tarihinde "SamMcfly" <notifications@github.com> yazdı:

**Comment by SamMcfly** [comment]
Do you have a sample of code to achieve that? because i'm trying but nothing worked. :/

Thanks a lot!

**Comment by ugurdmrl67** [comment]
private List<byte> usernameBytes;

/* Send Username*/

public void SendUsername(string username)
{
usernameBytes.Clear ();
char[] characters = username.ToCharArray();
usernameBytes.AddRange(Encoding.GetEncoding ("UTF-8").GetBytes (characters
));
byte[] messageToSend= usernameBytes.ToArray ();
PlayGamesPlatform.Instance.RealTime.SendMessageToAll (true, messageToSend);
}


/* Get Username */
public void OnRealTimeMessageReceived (bool isReliable, string senderId,
byte[] data)
{
if (senderId != PlayGamesPlatform.Instance.RealTime.GetSelf
().ParticipantId) {
string username = System.Text.Encoding.UTF8.GetString (data);
}
}

i hope it helps

2017-07-17 12:17 GMT+03:00 SamMcfly <notifications@github.com>:

**Comment by SamMcfly** [comment]
Thank you for sharing your code!

But i've got an error at this line:

`usernameBytes.AddRange(Encoding.GetEncoding ("UTF-8").GetBytes (characters));`

Errors are : 

- error CS0103: The name `Encoding' does not exist in the current context

- error CS1502: The best overloaded method match for `System.Collections.Generic.List<byte>.AddRange(System.Collections.Generic.IEnumerable<byte>)' has some invalid arguments

- error CS1503: Argument `#1' cannot convert `object' expression to type `System.Collections.Generic.IEnumerable<byte>'

How could i fix that?

**Comment by ugurdmrl67** [comment]
I don't know :D try to add this lines but if it is not work, I don't know
any solution

using System.Collections.Generic;
using System.Text;
using System.Collections;

2017-07-19 17:38 GMT+03:00 SamMcfly <notifications@github.com>:

**Comment by SamMcfly** [comment]
Thank you! i miss the `using System.Text;` assembly!
