### ISSUE TITLE
Friends List?

### ISSUE THREAD

**Issue by GDelkos** [playgameservices/play-games-plugin-for-unity#1457]
Hi there again and sorry for almost re-posting it but did anyone had some luck with the friend list always returning 0 even if you have followers?

**Comment by vws0213** [comment]
I have the same issue here.

**Comment by GDelkos** [comment]
still no update on that?thats a very needed issue here!
bump

**Comment by claywilkinson** [comment]
The APIs that return the lists of players are deprecated now: https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html

So getting an empty list back is expected behavior now.

Is this an already published game, or one under development?
