### ISSUE TITLE
Crash on Android 6.0/7.0 at automated login - Cloud Save Related? "Cannot use snapshots"

### ISSUE THREAD

**Issue by TinRobotStudios** [playgameservices/play-games-plugin-for-unity#1458]
My App is live but I am considering withdrawing it because of crashes on newer Android devices.

At the point where the google play login drop down appears the game crashes. Crash log here....(very verbose)

[crashlog.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/550796/crashlog.txt)

It looks like it fails because the Save Game feature isn't set up - line 34. But it is and has been working for weeks. Out in the wild it works on most devices, but a significant number on Android 6/7 crash like this.

I am using unity 5.4.1.p4, latest google play game services and CloudOnce for saving.

Any advice appreciated before I pull from play store :-(

**Comment by TinRobotStudios** [comment]
@claywilkinson
I have some more details regarding this. Repro is easier than I thought (given the right device) and NOT related to cloud once. I can repro with GooglePlayGamesPlugin-0.9.35 and Minimal example project.

Once again I am using Unity 5.4.2.p1

I followed the instructions to setup the GooglePlayService project and then the Minimal Project and pointed it to my google play app via 'Get Resources' as described.
I am using a project which has been in testing for weeks and out in the wild for 1 week now, so definitely no problem with 'Save Game' setting in console.

Run the vanilla minimal and all is well.

change the initialisation in start from 

GooglePlayGames.PlayGamesPlatform.Activate();

to

PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
// enables saving game progress.
.EnableSavedGames()
.Build();

And BOOM!
(Without the EnableSavedGames it continues to work as before but as soon as that is added in it crashes 100%)

Fresh Crash log attached (from around where I press Authenticate button)
It implies I have failed to setup save games on console, but this isn't the case and is fine on 99% of Beta test devices and my trusty....
LG Nexus 4. Android 5.1.1 Play Games v. 3.7.24 (3051774-036)

It does break on....
Sony Xperia E56 (F3311) Android 6.0 Play Games v3.7.24 (3051774-036)
[MinimalCRASH.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/557188/MinimalCRASH.txt)

Crash log says....
 java.lang.IllegalStateException: Cannot use snapshots without enabling the 'Saved Game' feature in the Play console
But I need to stress that this same APK works on Nexus 4. I have included the Nexus 4 log showing the same APK working in case that helps.
[MinimalOK.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/557192/MinimalOK.txt)

Any help would be appreciated as I am out of ideas! :-(

**Comment by TinRobotStudios** [comment]
*Bump* @claywilkinson any thoughts?

**Comment by TinRobotStudios** [comment]
Oooops! Confession time.
This WAS because of the save status of the game. Despite having the save game enabled there were unpublished changes, which are found on a separate screen. For anyone else who gets tripped up by this you are looking for.....
![savegamesettings](https://cloud.githubusercontent.com/assets/23054264/19835115/4e37ebac-9e74-11e6-8248-6df04e748742.png)
In short the button option to toggle the save game should NOT be there in a published app - ignore the lock icon - red herring.

@claywilkinson feel free to remove this from your list - apologies for that.

**Comment by claywilkinson** [comment]
No problem, thanks for taking the time to add your troubleshooting steps!
