### ISSUE TITLE
Build Unity project in Xcode

### ISSUE THREAD

**Issue by DannyAtSaladbowl** [playgameservices/play-games-plugin-for-unity#1459]
Hello, all.

I recently have problems related play-games-plugin in xCode.
It used to work in last week but it suddenly causes following problems and fails to complile.

Here are my project stauts.

xCode version 8
Unity version 5.3.4p5
Google play game unity for Unity version 0.9.31
Cocoapods applied for xCode project with following settings.

platform :ios, '7.0'

target 'Unity-iPhone' do
pod 'GooglePlayGames', '~> 5.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

1st, if I try to build, xCode complains with following message
**...../XXX_iOS/Pods/GTMOAuth2/Source/Touch/GTMOAuth2ViewControllerTouch.m:331:41: Use of undeclared identifier 'GTMOAuth2ErrorTokenUnavailable'; did you mean 'kGTMOAuth2ErrorTokenUnavailable'?**

I choose to auto fix in xCode which changes GTMOAuth2ErrorTokenUnavailable to kGTMOAuth2ErrorTokenUnavailable in GooglePlusOneSource.....

2nd, after I finish the auto fix for 1st, then I got following error at the end of compilation.
**Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GSDK_GTMSessionFetcher", referenced from:
      objc-class-ref in gpg(GPGClearcutLogger.o)
  "_OBJC_CLASS_$_GSDK_GTMSessionFetcherService", referenced from:
      objc-class-ref in gpg(GIPNetworkImage.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

To fix this, I tried many other ways such as add GoogleOpenSource.framework, add Google sign in, and etc, but no lucks so far.

Any other ideas will be very helpful!!

Thank you in advance.

Danny

**Comment by leandro-zanardi** [comment]
Same to me with xcode 8, play services 0.9.35

**Comment by DavidCow** [comment]
Same here too! the pods 'GooglePlayGames' suddenly started to import Auth libs and since then it's not working. -_-

**Comment by gnchishti** [comment]
Same problem with me.... Any solution to this?

**Comment by Ugobyte** [comment]
Same problem here.

**Comment by DannyAtSaladbowl** [comment]
Hi, there.

Some how, I figured out this problem.
I tried many other ways by adding other libraries to the xCode project generated by Unity, 
however there were no lucks. And then I started checking Cocoapods usages and realized 
, of course, it keeps updating the latest library versions.

Since last week(2016/10/15 or around. Not sure..), GooglePlayGames has been updated higher than
version 5.1. The update also changed dependencies and added GTMOAuth2, GTMSessionFetcher, and
others..

How I solved this is following.

A. When you try to resolve with existed xCode project>>
1. "pod deintegrate" to the xCode project
2. Open Podfile and fix like following. **pod 'GooglePlayGames', '~> 5.0'  -change to-> pod 'GooglePlayGames', ‘5.1’** This change will enforce to update GooglePlayGames for version 5.1.
3. "pod update" to the xCode project and DONE!

B. From Unity project>>
1. Find and open "project/Assets/GooglePlayGames/Editor/Podfile.txt"
2. Fix like A-2.

I think my project's GooglePlayGames needed to be updated, but I am not in condition to do that.

Hope, this helps. Cheers!

Danny

**Comment by Ugobyte** [comment]
@DannyAtSaladbowl I don't see the "Podfile.txt"

**Comment by Ugobyte** [comment]
@DannyAtSaladbowl Doesn't work. I'm getting the same error.

By the way, i updated my Google Play services. Now When i do an iOS build, Unity builds an xcode project. It used to build an xcode workspace. Did something change here?

**Comment by DannyAtSaladbowl** [comment]
@Ugobyte Oh, I am sorry that I confused you. 

The fact is my received GooglePlayGames plugin with other SDKs from the publisher I worked with.
Seems, they might modify GPGSPostBuild.cs and add  Podfile.txt.

Don't mind for Step B.

**Comment by gnchishti** [comment]
@Ugobyte I experienced this too.
@DannyAtSaladbowl I will try you edited steps.

**Comment by Ugobyte** [comment]
Why is this closed? We still don't have a solution.

**Comment by asadmehmoodlogicon** [comment]
The Hell is Wrong and why is this closed without solving the issue
Same things Pod started to installing Auth from no where

**Comment by gnchishti** [comment]
My next verision build is stuck for last 5 days in facing these problems

**Comment by DavidCow** [comment]
Yeah mine too. Hope there is a fix soon.

**Comment by Ugobyte** [comment]
https://github.com/DannyAtSaladbowl Please reopen this issues until we get a better solution or understanding as to what is going on.

**Comment by asadmehmoodlogicon** [comment]
same things happened today is the deadline and this things is so annoying

**Comment by asadmehmoodlogicon** [comment]
i re created the issue

**Comment by DavidCow** [comment]
Have you guys tried out what dannyatsaladbowl suggested?

**Comment by asadmehmoodlogicon** [comment]
I tried to comment the error code of this authentication error, cuz i think it will just print log or show the error cuz above there was check that if error happen.
so after that when i run the build its now started showing the this error.
GTMSesssionFilter unable to reference (from another crappy things )

**Comment by GabLeRoux** [comment]
Google Play Services is a pain in the ass for ios with cocoa. It's not compatible with its other libraries and is blocking me for my first release. Anyway, It was complaining about `GTMOAuth2ErrorTokenUnavailable` being missing.

> Pods/GTMOAuth2/Source/Touch/GTMOAuth2ViewControllerTouch.m:331:41: Use of undeclared identifier 'GTMOAuth2ErrorTokenUnavailable'; did you mean 'kGTMOAuth2ErrorTokenUnavailable'?

So even tho it's not my lib, I tried changing `GTMOAuth2ErrorTokenUnavailable` for `kGTMOAuth2ErrorTokenUnavailable` directly on the library (yes, I know it sucks), then build again. After a while, failed somewhere else.

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GSDK_GTMSessionFetcher", referenced from:
      objc-class-ref in gpg(GPGClearcutLogger.o)
  "_OBJC_CLASS_$_GSDK_GTMSessionFetcherService", referenced from:
      objc-class-ref in gpg(GIPNetworkImage.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I did update Play Services plugin, but I think I won't do that again ever. I think the solution here woud be to find a way to freeze version in the podfile manually so these commands doesn't install these broken deps;

I'll try to update here if I find something.

**Comment by gnchishti** [comment]
I have played enough with pod files too... but no sccess..

**Comment by DannyAtSaladbowl** [comment]
@Ugobyte I reopened this case. @GabLeRoux Wow, you summarized very detailed solution!

The thing is we have to find proper versions for libraries we are using. If you had succeeded before,
then you have more chance to pin point the working version by date or version you succeeded to
make build before.

My project is with Mopub Unity plugin with mediation networks those are AdMob, Chartboost, and UnityAds. But for those mediation networks, I manually inserted those network's iOS SDKs manually.
So, only library managed by Cocoapods is Google play games.

**Comment by asadmehmoodlogicon** [comment]
Yeah that's the working solution @GabLeRoux 
 Finally Solved 

Finally I Solved this issue by changing the pod file to this
platform :ios, ‘8.0’

target 'Unity-iPhone' do
pod 'GooglePlayGames', ‘5.1’
pod 'Google'
end
target 'Unity-iPhone Tests' do
pod 'GooglePlayGames', ‘5.1	’
pod 'Google'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end


then install the pod file and its done no error

**Comment by DavidCow** [comment]
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, :deployment_target => '9.0'

target 'Unity-iPhone' do
  pod 'Google-Mobile-Ads-SDK', '~> 7.8'
  pod 'GooglePlayGames', '~> 5.1'
  pod 'UnityAds', '~> 1.5.6'
end

target 'Unity-iPhone Tests' do
  pod 'Google-Mobile-Ads-SDK', '~> 7.8'
  pod 'GooglePlayGames', '~> 5.1'
  pod 'UnityAds', '~> 1.5.6'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
 

This is my podfile. I still get errors. The GTMSessionFetcher thingy. :( Does anybody know what's wrong?

**Comment by gnchishti** [comment]
Hi,

My project was not creating xcworkspace
I removed pods using terminal and installed again to get latest.

I removed all plugins (even removed plugin folder) from my project I was using 
google analytics
game play services
google ads

- Commented the code that was causing errors for these libraries.
- Then I exported the package of my complete project and saved **game.unitypackage**
- Then started a  fresh unity project and imported this package did all player settings.
- Then imported my **game.unitypackage** 
- Added my 3 plugins
It started creating xcworkspace

my pod file is

`
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'Unity-iPhone' do
  pod 'Google-Mobile-Ads-SDK', '7.8'
  pod 'GooglePlayGames', '5.1'
  pod 'GoogleAnalytics'
end
`

Every thing is complied I get following link error

ld: '/Projects/XCode/iOSBuild1/Pods/GoogleSignIn/Libraries/libGIDExShared.a(GIDSignInExtensionRequest.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


If I remove GoogleSignIn Folder from my pods project I get same error.

Any suggestion for me?

**Comment by Activate78** [comment]
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1460

my pod file:

platform :ios, '8.0'

target 'Unity-iPhone' do
pod 'GooglePlayGames', '5.1'
pod 'Google-Mobile-Ads-SDK', '~> 7.8'

end

terminal
pod install
pod update

In xCode remove GoogleSignIn.framework  in Build Phases -> Libraries and in the references 

build success...

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
