### ISSUE TITLE
Unity poor performance because of jar resolver?

### ISSUE THREAD

**Issue by Jasper76** [playgameservices/play-games-plugin-for-unity#1462]
Each time I edit my c# code in MonoDevelop and I return to Unity, the following messages are printed to the Console window:

Resolver version is now: 10101
WARNING: No compatible versions of com.android.support:support-v4 required by (com.google.android.gms:play-services-basement:9.6.1), will try using the latest version 24.0.0
WARNING: No compatible versions of com.android.support:support-annotations required by (com.android.support:support-v4:23.1+, com.android.support:support-v4:24.0.0), will try using the latest version 24.0.0

I understand from another issue that these warnings can be safely ignored. However, when the Unity program gets focus it freezes and it takes about 10 seconds before it 'unfreezes'. This happens every time I change some code, so this gets very annoying.

What is causing the above resolver lines to execute every time Unity gets focus, and is there a way to fix this problem?

I'm using a Mac, Unity 5.3.6 and the latest version of the plugin.

**Comment by claywilkinson** [comment]
The latest version of the plugin 0.9.36 includes an updated jar resolver, which resolves your issue.

The other option is also to turn off background resolution under Assets/Play Services/Resolver
