### ISSUE TITLE
Saved Game, InternalError

### ISSUE THREAD

**Issue by Yewoon** [playgameservices/play-games-plugin-for-unity#1463]
Hello,

Saved Game is not working some users. One of them request to fix his issue.

1. He always fails to save the data.
2. He are able to save the progress twice by creating a new Gamer ID after deleting the Play Games profile.
3. Now he fails every time again.

**ErrorType: InternalError**

How can I help him? Please refer the log.

// Custom Log
[10/31/2016 22:32:53][at PlayScene][TrySave][ClickButton]
[10/31/2016 22:32:53][at PlayScene][TrySave][AuthenSuccess]
[10/31/2016 22:32:53][at Platform][TryAuthen][rc : Success,stats : GooglePlayGames.BasicApi.PlayerStats,valid : True]
[10/31/2016 22:32:53][at Platform][SuccessAuthen][2|0|1|0|560|1|0 ]
**[10/31/2016 22:34:16][at PlayScene][TrySave][AuthenFail][InternalError]**

[Development Environment]
// Unity, 4.6.9f1

// Play Games, PluginVersion.cs
 18 namespace GooglePlayGames {
 19     public class PluginVersion {
 20         // older versions, used when upgrading to other versions
 21         public const string VersionKeyCPP = "00911";
 22         public const string VersionKeyU5 = "00915";
 23         // patched 0.9.27 version for Unity 5.3 changes.
 24         public const string VersionKey27Patch = "00927a";
 25 
 26         public const string VersionKeyJarResolver = "00928";
 27         public const string VersionKeyNativeCRM = "00930";
 28         public const int VersionInt = 0x0931;
 29         public const string VersionString = "0.9.31a";
 30         public const string VersionKey = "00931";
 31 
 32         // used to check for the correct min version or play services.
 33         public const int MinGmsCoreVersionCode = 8487000;
 34 
 35         // used to get the right version of dependencies.
 36         public const string PlayServicesVersionConstraint = "8.4+";
 37     }
 38 }
 39 #endif

**Comment by claywilkinson** [comment]
Can you share the log of the failure?

**Comment by claywilkinson** [comment]
Please reopen and include the log if this is still an issue.
