### ISSUE TITLE
Social.localUser.id does not match on different platforms

### ISSUE THREAD

**Issue by kukoss** [playgameservices/play-games-plugin-for-unity#1465]
Hi, 

i found a bug/issue with Social.localUser.id values. I built a unity multiplatform game for ios and android. When I login as the same user on these platforms, on each of them, "Social.localUser.id" returns different value for the same user. 
When I sign up as same user on two different devices on the same platform, everything works correctly.

**Comment by claywilkinson** [comment]
This is an unfortunate side effect of removing the Google+ integration: https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html

iOS players must use a Google Plus based user account, but Games is no longer supporting Google Plus based accounts.
