### ISSUE TITLE
Load the SavedGame always return fail with Internal Error

### ISSUE THREAD

**Issue by kenglou** [playgameservices/play-games-plugin-for-unity#1466]
Hi,

Recently I'm integrating the Google Play Game Service with the latest version of Google Play Game Service 0.9.35 and found that I always get an internal error when I'm doing the open and read saved game function. Here i attached 2 error logs that comes from my HTC Nexus 9 and hope that someone can answer my questions. Try to search **returnReadData : InternalError** and you shall see the error occured.

Thank you.
[playservice_savedgame_error_log.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/565853/playservice_savedgame_error_log.txt)
[playservice_savedgame_error_log2.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/565852/playservice_savedgame_error_log2.txt)

**Comment by claywilkinson** [comment]
This looks like a bug in the version of the play-services client library that you are using.   The bug causes it to look like there is a conflict in the saved games data when there is not one. Can you update to the latest version of play-services SDK and try again?
