### ISSUE TITLE
How to user Social.localUser?

### ISSUE THREAD

**Issue by truonguit2010** [playgameservices/play-games-plugin-for-unity#1467]
Hi,
On my iOS game, user login by Game Center, but after that I want to login Google Game Service after. But I see 2 of them use Social.localUser. How about if I call Social.localUser again with Google game service?

```
Social.localUser.Authenticate (success => {
});
```

**Comment by claywilkinson** [comment]
You can't login using Game Center then use Google Play Game Services, you'll need to sign into both.  However, new players of your game may not have Google Play Game profiles, and they are not able to create them on iOS: https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html, so I don't think you want to intermingle  Game Center and Play Game Services.

But to answer your technical question, you can directly access the GPGS objects by using PlayGamesPlatform.localUser
