### ISSUE TITLE
LoadUser doesn't work

### ISSUE THREAD

**Issue by Tobiti** [playgameservices/play-games-plugin-for-unity#1468]
I'm using the tutorial code to get my leaderboard, but I don't get any callback from the function loadUser.
Can someone help me?

I'm using the current build.

Code:
` 
internal void LoadUsersAndDisplay(ILeaderboard lb)
    {
        // get the user ids
        List<string> userIds = new List<string>();

        foreach (IScore score in lb.scores)
        {
            userIds.Add(score.userID);
        }
        // load the profiles and display (or in this case, log)
        PlayGamesPlatform.Instance.LoadUsers(userIds.ToArray(), (users) =>
        {
            string status = "Leaderboard loading: " + lb.title + " count = " +
                lb.scores.Length;
            foreach (IScore score in lb.scores)
            {
                IUserProfile user = users.FirstOrDefault(x => x.id == score.userID);
                status += "\n" + score.formattedValue + " by " +
                    (string)(
                        (user != null) ? user.userName : "**unk_" + score.userID + "**");
            }
            Text.text = status;
            Debug.Log(status);
        });
    }
`

**Comment by claywilkinson** [comment]
This can happen if the userIds array is empty.  Can you confirm it is non-empty?

**Comment by claywilkinson** [comment]
Please re-open if the issue is still happening and include a log of loading the leaderboard.
