### ISSUE TITLE
Google Cloud Save/Load Issue

### ISSUE THREAD

**Issue by jkgood** [playgameservices/play-games-plugin-for-unity#1469]
Good day,

I'm wondering what is going wrong in my script to load and save to google cloud.

Note that I have successfully saved and loaded locally.

This is my code;

`    
private bool isSaving;
    private bool hasBeenWarnedLocalSave;

    public void LoadCloud()
    {
        isSaving = false;
        ((PlayGamesPlatform)Social.Active).SavedGame.OpenWithAutomaticConflictResolution
        ("CTPSave", GooglePlayGames.BasicApi.DataSource.ReadCacheOrNetwork, ConflictResolutionStrategy.UseLongestPlaytime, SavedGameOpened);
    }

    public void SaveCloud()
    {
        if (Social.localUser.authenticated)
        {
            isSaving = true;
            hasBeenWarnedLocalSave = false;
            ((PlayGamesPlatform)Social.Active).SavedGame.OpenWithAutomaticConflictResolution
            ("CTPSave", GooglePlayGames.BasicApi.DataSource.ReadCacheOrNetwork, ConflictResolutionStrategy.UseLongestPlaytime, SavedGameOpened);
            PopupManager.Instance.ShowPopup("Saved", "We just saved this shit");
        }
        else
        {
            if (!hasBeenWarnedLocalSave)
            {
                PopupManager.Instance.ShowPopup("Save Cloud Error", "Not Connected");
                Debug.Log("Unable to save to cloud");
                hasBeenWarnedLocalSave = true;
                SaveLocal();
            }
        }
        PopupManager.Instance.ShowPopup("Button Pressed", "Nothing happened.");
    }
    public void SavedGameOpened(SavedGameRequestStatus status, ISavedGameMetadata game)
    {
        if (status == SavedGameRequestStatus.Success)
        {
            if(isSaving) // Writing Data
            {
                byte[] data = System.Text.ASCIIEncoding.ASCII.GetBytes(GetSaveString());
                TimeSpan playedTime = TimeSpan.FromSeconds(TotalPlayTime);
                SavedGameMetadataUpdate.Builder builder = new SavedGameMetadataUpdate.Builder()
                    .WithUpdatedPlayedTime(playedTime)
                    .WithUpdatedDescription("Saved Game at" + DateTime.Now);

                SavedGameMetadataUpdate update = builder.Build();
                ((PlayGamesPlatform)Social.Active).SavedGame.CommitUpdate(game, update, data, SavedGameWritten);
            }
            else // Reading Data
            {
                ((PlayGamesPlatform)Social.Active).SavedGame.ReadBinaryData(game, SavedGameLoaded);
            }
        }
        else
        {
            Debug.Log("Not even connected");
            PopupManager.Instance.ShowPopup("Save State", "Error" + status);
        }
    }
    public void SavedGameLoaded(SavedGameRequestStatus status, byte[] data)
    {
        if(status == SavedGameRequestStatus.Success)
        {
            LoadFromString(System.Text.ASCIIEncoding.ASCII.GetString(data));
        }
        else
        {
            Debug.Log("Error reading game:" + status);
            PopupManager.Instance.ShowPopup("Error", "Error reading game :" + status);
        }
    }
    public void SavedGameWritten(SavedGameRequestStatus status, ISavedGameMetadata game)
    {
        Debug.Log(status);
    }
`

**Comment by claywilkinson** [comment]
What is the symptom?  Can you share a log of the problem?

**Comment by ahmedessid** [comment]
me too same problem .. Have you found a solution to this problem?
