### ISSUE TITLE
SendMessageToAll connects to API call ok but recipients don't receive message

### ISSUE THREAD

**Issue by designzoo-peter** [playgameservices/play-games-plugin-for-unity#147]
I have a project created here https://github.com/designzoo-peter/rtmpManager where I am creating a manager to handle joining and leaving rooms.

In MPManager.cs I am handling joining a room and leaving a room, where people joining and leaving send messages to each other.

The 1st time 2 players play a game it works, but when the room is left and a new game is found, all of the messages the clients send to each other in the new room don't get received (apart from the 1st greeting message).

In LogCat I can see the service successfully makes the API call (using PlayGamesPlatform.DebugLogEnabled = true;). It doesn't give any hints as to why the message would be getting lost.

I am using v4.4.52 of the plugin, where both clients are android devices (OS versions 4.1.2 and 4.4.2).

Thanks.

**Comment by claywilkinson** [comment]
@designzoo-peter  - Are you still having this issue with the latest version of the plugin?  The implementation of the plugin was changed in 0.9.11, which may have addressed your issue.  If you are still having problems with the latest plugin, please re-open this issue.  Thanks!
