### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'UnityEditor.iOS.Extensions.Xcode

### ISSUE THREAD

**Issue by SeanLangre** [playgameservices/play-games-plugin-for-unity#1470]
Hi, 

We updated the plugin and every time we build we get:
`FileNotFoundException: Could not load file or assembly 'UnityEditor.iOS.Extensions.Xcode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.`

It still runs but it's an annoyance.

We also get:
`WARNING: No compatible versions of com.android.support:support-v4 required by (com.google.android.gms:play-services-basement:9.4.0), will try using the latest version 23.4.0`

Any help how to remove either of these would be appreciated.

**Comment by Kimsanggu** [comment]
Hi,
I have same issue.
if you solve it, help me.

**Comment by claywilkinson** [comment]
The warning about support-v4 is still being worked on, but it is a harmless (but annoying) warning message.

The Xcode error should be fixed in the latest version of the plugin, 0.9.36.
