### ISSUE TITLE
Unity Cloud warnings

### ISSUE THREAD

**Issue by dzamani** [playgameservices/play-games-plugin-for-unity#1473]
Hi,

I just updated from v8.4 to the latest version and I'm working with UCB, while it's only warnings, theses issues slow the whole process and make reading the logs kind of hard.

It's related to the JarResolver.
Here is an example of these warnings :

`[Unity] ResolutionException: Android SDK path not set.  Set the Android SDK property using the Unity "Edit > Preferences > External Tools" menu option on Windows or the "Unity > Preferences > External Tools" menu option on OSX. Alternatively, set the ANDROID_HOME environment variable`

Any idea ? Thanks!

**Comment by MiketoString** [comment]
In the upgrade doc for v0.9.35 it mentions that the Jar Resolver changed to be a DLL and has some instructions that might help with your issue:

https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/UPGRADING.txt

**Comment by dzamani** [comment]
It's not related, the problem was that the jarresolver was running for Unit Cloud Build which we don't want.
Using the define UNITY_CLOUD_BUILD I've disabled "RegisterDependencies" in GPGSDependencies which made my warnings disappear.
