### ISSUE TITLE
Installed 0.9.35 now getting KeyNotFoundException, what does this mean?

### ISSUE THREAD

**Issue by timmmeh** [playgameservices/play-games-plugin-for-unity#1474]
I'm running Unity 5.4.2f2, my platform is Android. I removed the old Play services before installing the new package. I have restarted Unity. Is my Android SDK out of date maybe?

KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.HashSet`1[System.String]].get_Item (System.String key) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:150)
Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest)
GooglePlayServices.ResolverVer1_1.DoResolutionNoAndroidPackageChecks (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation)
GooglePlayServices.ResolverVer1_1+<DoResolution>c__AnonStorey1.<>m__0 ()
GooglePlayServices.ResolverVer1_1.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation, System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.Resolve (System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.MenuResolve ()

**Comment by timmmeh** [comment]
So I android sdk to the latest rev - no changes.
I disabled Auto Resolver and made a build I saw I log then that says "Resolver version is now: 10101"
Still cant auto resolve in the editor though

**Comment by v2k** [comment]
+1

**Comment by timmmeh** [comment]
I did go and delete all plugins and any google play scripts, then re-imported all my different plugins and packages and setup things seems to be working as far as this issue is concerned. However GPGS has continued to be a thorn in the side.

**Comment by owenmills** [comment]
I was having the same issue.  I had to delete the following old config file:
ProjectSettings/GoogleDependencyGoogle.GPGS.xml
after that, I restarted Unity and all was good.

**Comment by claywilkinson** [comment]
This has been fixed in version 0.9.36 which includes an updated jar resolver library.
