### ISSUE TITLE
Import Plugin Fatal Error! Unity Crash

### ISSUE THREAD

**Issue by Ezberan** [playgameservices/play-games-plugin-for-unity#1476]
Hi, I'm sure there must be something obvious I'm missing here so forgive me if that's the case, but I can't find anything on this error.

When I import the plugin into Unity the program just crashes instantly, giving me the error seen below. I've tried importing it into blank projects as well and get the same result. I assume there must be a problem with my Unity settings or something else entirely but I'm stumped. If there's anything anyone could tell me that would be great, thanks.

The error message:

Fatal error! 

No valid name for platform: 35 
UnityEditor.PluginImporterGetCompatibleWithPlatform(BuildTarget) Google.FileMetadataByVersion:EnableMostRecentPlugins() Google.FileMetadataSet:EnableMostRecentPlugins() Google.VersionHandler:UpdateVersionedAssets(Boolean)
Google.VersionHandler:.cctor()
UnityEditorEditorAssemblies:SetLoadedEditorAssemblies(Assembly[]) 

![unityerror](https://cloud.githubusercontent.com/assets/23292298/20037510/6a6341ec-a418-11e6-80c6-f68728725755.png)

**[SOLVED]
In the end I solved this error by uninstalling all the related software (Unity, Android Studio, JDK), and then redownloading the newest versions and installing them. I believe the culprit may have been having the incorrect Java Kit chosen as default by Unity but couldn't be sure at this point.**

**Comment by Avala-Games** [comment]
Hello Ezberan,

Can't seem to find what is causing this error.

When I import the latest version (current build) it also giving me the this error.
Try using a the previous version like (GooglePlayGamesPlugin-0.9.21).

It's the only solution I can think of right now.

**Comment by grosalex** [comment]
Hi I got the same issu and I can't reopen my project anymore without this how can I solved it?
regards,

**Comment by Avala-Games** [comment]
Dear Grosalex,

Go to the root of your project folder and delete all files / folders related to Google Play Services. This worked for me.

Hope it helps.

**Comment by tonio1206** [comment]
But by deleting all the folders related to Google Play Services, you're deleting the plugin. 
How would you resolve this problem but while keeping the Google Play Services into Unity?

Regards,

**Comment by AdamAndAnne** [comment]
hello everybody,
when i import the plugins googleadmob.unitypackage into my project.i get the same errors,My unity is 5.0.1.If i redownloading the newest versions and installing them is all right,but my project has more errors.
Hope it helps.
Regards,

**Comment by claywilkinson** [comment]
I believe the latest plugins resolve this issue.
