### ISSUE TITLE
GPGSAppController Error when calling PlayGamesPlatform:Activate() in iOS

### ISSUE THREAD

**Issue by colender** [playgameservices/play-games-plugin-for-unity#1478]
Hello when launching the app in iOS once the PlayGamesPlatform:Activate() I get the following error 
`2016-11-10 19:28:51.407 FivePlay1[216:3650] -[GPGSAppController application:didRegisterForRemoteNotificationsWithDeviceToken:]: unrecognized selector sent to instance 0x156556e00
2016-11-10 19:28:51.564 FivePlay1[216:3650] Uncaught exception: NSInvalidArgumentException: -[GPGSAppController application:didRegisterForRemoteNotificationsWithDeviceToken:]: unrecognized selector sent to instance 0x156556e00
(
	0   CoreFoundation                      0x00000001818e9918 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000180f57f80 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001818f061c <redacted> + 0
	3   CoreFoundation                      0x00000001818ed3e8 <redacted> + 408
	4   CoreFoundation                      0x00000001817f168c _CF_forwarding_prep_0 + 92
	5   FivePlay1                           0x00000001005b9fdc -[GPGSAppController application:didRegisterForRemoteNotificationsWithDeviceToken:] + 92
	6   libdispatch.dylib                   0x000000018133d630 <redacted> + 24
	7   libdispatch.dylib                   0x000000018133d5f0 <redacted> + 16
	8   libdispatch.dylib                   0x0000000181342cf8 _dispatch_main_queue_callback_4CF + 1844
	9   CoreFoundation                      0x00000001818a0bb0 <redacted> + 12
	10  CoreFoundation                      0x000000018189ea18 <redacted> + 1628
	11  CoreFoundation                      0x00000001817cd680 CFRunLoopRunSpecific + 384
	12  GraphicsServices                    0x0000000182cdc088 GSEventRunModal + 180
	13  UIKit                               0x0000000186644d90 UIApplicationMain + 204
	14  FivePlay1                           0x00000001000284ac main + 156
	15  libdyld.dylib                       0x000000018136e8b8 <redacted> + 4
)
2016-11-10 19:28:51.565 FivePlay1[216:3650] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GPGSAppController application:didRegisterForRemoteNotificationsWithDeviceToken:]: unrecognized selector sent to instance 0x156556e00'
*** First throw call stack:
(0x1818e9900 0x180f57f80 0x1818f061c 0x1818ed3e8 0x1817f168c 0x1005b9fdc 0x18133d630 0x18133d5f0 0x181342cf8 0x1818a0bb0 0x18189ea18 0x1817cd680 0x182cdc088 0x186644d90 0x1000284ac 0x18136e8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException`

I have been trying to get this to work but I cannot figure out what is going on.

**Comment by claywilkinson** [comment]
This is fixed in the latest plugin 0.9.36.  Please re-open if your experience is different.
