### ISSUE TITLE
Error getting server auth code

### ISSUE THREAD

**Issue by brianjkd** [playgameservices/play-games-plugin-for-unity#1479]
Hi,

I am having trouble using the GPG to get a server auth code which I can then use to do auth with with my own server.  I am able to authenticate, and get the user's google id. However, I am unable to get a server auth code which I really need.

Every post I have read suggests that my web client id is not configured properly. In the Google Play console I have linked my android app ( project credentials created in Google Developer Console) to my game's services. The OAuth2 client id that is displayed in the Play console is that of my android client id (and I cannot change that. should I also link a web app?). In the Google Developer Console, I added a web client id to the credentials for the android project, so I have both android and web id. I use the web client id in the setup for Unity.

This is the error message I get back. I have a strong feeling my setup is incorrect. Any suggestions?
Thank you. Also I have put the Unity c# code I use to ask for server auth code.

`11-11 11:49:45.996 29668-29699/? W/Unity: *** [Play Games Plugin DLL] 11/11/16 11:49:45 -05:00 ERROR: Error loading server auth code: ERROR_NOT_AUTHORIZED`

```

 public IEnumerator getAuthCode()
    {
        bool gotAuthCode = false;
        while (!gotAuthCode)
        {
            yield return new WaitForSeconds(5);
            Debug.Log("Trying to get server auth code.");
            PlayGamesPlatform.Instance.GetServerAuthCode((authStatus, code) =>{
                if (authStatus == CommonStatusCodes.Success){
                    Debug.Log("Got server authCode: " + code);
                    gotAuthCode = true;
                }
                else {
                    Debug.Log("Error authStatus: " + authStatus.ToString() + "Code: " + code);}
            });
        }
    }
```

**Comment by DennisATA** [comment]
In the Google Play Developer Console, go to the Google Play Games section, and in your app listing check the testing stage that your Google Play account is listed (note this is separate from the Play Store testers).

And I guess check that your client ID in the API console is actually a "Web application" type, and not something like "Bare".

**Comment by brianjkd** [comment]
Thanks for your reply. Both of those suggestions look correct on my end.

In Google Play Developer Console, I select my app, then I got to the link apps tab. I select Android, and then I select my package name and it successfully links to the project API in the API console. In Play Developer console, it lists the OAuth2 client id as the credential from the Android type client id signed with the debug key sha1, created when I made the project in the API console. I am also signing my unity project when I build it with the debug key. I then add a web application type in the API Console, and I copy that client iD into Unity and paste it into the web client id.

Does that sound correct for you. I appreciate your help.

**Comment by DennisATA** [comment]
That sounds fine to me, although I've been using our "production" keystore, instead of the debug keystore.  We have uploaded apks of our app to the Play Store alpha/beta stages (no published production apk yet), I'm not sure if it makes a difference.

Besides that, I can't remember anything else off the top of my head.  Sorry.

**Comment by brianjkd** [comment]
It works now. This post helped me: https://github.com/playgameservices/play-games-plugin-for-unity/issues/1153

Thanks for your help. I checked the Enable Google + API access in Unity under Android setup and now it works (when I authenticated on launching the app it asked to use my google plus account) and now I can get the serverAuthCode. I did not realize this was required for getting serverAuthCode.

**Comment by brianjkd** [comment]
As a follow up. Is there a reason Google+ access is required for getting auth codes and tokens, I thought Google Play Games moved away from requiring this?

**Comment by DennisATA** [comment]
I don't think it's required.  I don't have Google+ access enabled in my app.

**Comment by brianjkd** [comment]
Interesting, good to hear that you did not need to enable it. I'll try to see what is wrong  with my setup requiring me to include it.

**Comment by claywilkinson** [comment]
Requiring google plus depends on which APIs you are using on the back-end.  The good news is that Google Plus integration with Games is going away, making this process much less confusing: https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html.
