### ISSUE TITLE
Rejected by App Review Board for Signin through Safari

### ISSUE THREAD

**Issue by Neogohan1** [playgameservices/play-games-plugin-for-unity#148]
So I've submitted the app for review and got rejected with this back in response:

The app opens a web page in mobile Safari for logging in, then returns the user to the app. The user should be able log in without opening Safari first. 

Is there any way to signin using this plugin on iOS without first opening safari?

**Comment by claywilkinson** [comment]
Might want to take a look at #359  - it appears that the app get approved upon appeal.

**Comment by ekiyanov** [comment]
rejected in second time. appeal doesn't help

**Comment by claywilkinson** [comment]
That's disappointing.  We use Safari to sign in  if Google+ is not installed, so one workaround is to detect if Google+ is installed or not, and if is not, you could potentially prompt the user to install Google+ to complete the sign-in when it’s not present.  The Google+ app can be viewed on the app store by opening this URL: https://itunes.apple.com/app/id447119634?mt=8.

Remove the Google Sign-in button for users who do not have the Google+ app (which effectively disables GPGS for that user)

Detection of Google+ being present can be done using this line of code:

        BOOL isGooglePlusInstalled = [[UIApplication sharedApplication] canOpenURL: [NSURL
                URLWithString:@"gplus://"]];

**Comment by MofoMan2000** [comment]
This is complicated by the fact that Apple's stupid app review process seems to be wildly inconsistent in what is considered "acceptable". Ideally, we'd need a more streamlined process for the sign-in, but I'm sure Apple's app reviewers must have come across this before, since EVERY game using Google Games Services probably has the same thing going on.

**Comment by mohammad19991** [comment]
that's just a stupid thing from apple...

**Comment by arkayapps** [comment]
my app also reject because of open safari on Google+ sign and force to say : 

It would be appropriate to revise your app to provide a Google+ web view or native login to authenticate users within your app.

i have also see that Google game service doc not provide step for webview sign in. can any one help me.

**Comment by sorab2142** [comment]
Try this http://forum.unity3d.com/threads/google-play-games-login-guide.320187/

**Comment by claywilkinson** [comment]
@arkayapps  - please keep us posted of the outcome.  I will pass along your unfortunate news.

**Comment by MofoMan2000** [comment]
Has anyone has any luck using the directions at the link sorab2142 posted? Are those changes something that can be included with the plugin?

**Comment by claywilkinson** [comment]
@MofoMan2000  - did you see the discussion in https://github.com/playgameservices/play-games-plugin-for-unity/issues/570?  It looks like they had some traction getting approved.  As far as enhancing the plugin, I haven't had a chance to look at was sorab2142 did, but coming up with a solution is definitely on the list.

**Comment by MofoMan2000** [comment]
Yeah, that issue thread contains no new information. Apple is inconsistent in their review process, sometimes apps get through with a browser login, sometimes they don't. I've had both happen.

It looks like the steps in that Unity Forums thread involve adding a couple source files (which could go in Plugins/iOS, right?) and modifying a couple of Unity's generated ObjC source, specifically UnityViewBaseController.h and UnityViewBaseController.mm. I'm not sure how that second part could be added into the plugin but it could be used as part of a readme I guess.

**Comment by chetanisinanand** [comment]
I believe Google added built-in WebView support in the iOS plugin for sign-in, 
Please let me know how to get built-in WebView from Unity plugin ?

**Comment by claywilkinson** [comment]
@chetanisinanand  - can you point me to what you are referring to?  There are a lot of APIs and SDKs from Google -  I don't believe the Games SDK supports webview yet, but I agree, it should.  Stay tuned!

**Comment by chetanisinanand** [comment]
I'm referring to Google + sign-in  according to thread : https://code.google.com/p/google-plus-platform/issues/detail?id=900#c109
Just wanted to know if this sign-in Process can be implemented in Google Play Game service for Unity ?

**Comment by claywilkinson** [comment]
Thanks @chetanisinanand! Yes, I believe these changes are being looked into for the Google Play Games Services C++ SDK (which is what the plugin is based on).  I don't have any specific timeline information, but I know everyone thinks it is important.  Stay Tuned!

**Comment by nikescar1** [comment]
Would something like this iOS WebView plugin be able to be retrofitted to the GPGS plugin somehow? https://github.com/gree/unity-webview

**Comment by claywilkinson** [comment]
Version 0.9.25 uses the Google Sign In API which has been used by others and approved for the AppStore.

**Comment by ZenithCode** [comment]
This creates a new problem unfortunately.  Anyone with Google+ app installed on their iOS device is no longer able to login to the app like before.  

1. Try to authenticate, 
2. Google+ app opens, 
3. Chose account, 
4. Agree to permissions. 
5. Return to app 
6. Still not singed in.

Can anyone recommend a way of fixing this please?
