### ISSUE TITLE
FindUser doesn´t exist

### ISSUE THREAD

**Issue by HDK101** [playgameservices/play-games-plugin-for-unity#1480]
Assets/Manager.cs(1115,61): error CS0103: The name `FindUser' does not exist in the current context

> 
 internal void LoadUsersAndDisplay(ILeaderboard lb)
    {
        // get the user ids
        List<string> userIds = new List<string>();

        foreach(IScore score in lb.scores) {
            userIds.Add(score.userID);
        }
        // load the profiles and display (or in this case, log)
        Social.LoadUsers(userIds.ToArray(), (users) =>
            {
                string status = "Leaderboard loading: " + lb.title + " count = " +
                    lb.scores.Length;
                foreach(IScore score in lb.scores) {
					IUserProfile user = FindUser(users, score.userID);
                    status += "\n" + score.formattedValue + " by " +
                        (string)(
                            (user != null) ? user.userName : "**unk_" + score.userID + "**");
                }
                Debug.log(status);
            });
    }
> 

Can someone help me?

**Comment by claywilkinson** [comment]
You can get that method from https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/samples/SmokeTest/Source/Assets/SmokeTest/LeaderboardGUI.cs#L178
