### ISSUE TITLE
Error with Play Service Dependencies

### ISSUE THREAD

**Issue by trunghieu11** [playgameservices/play-games-plugin-for-unity#1481]
Hi, I get this error when trying to install, can you give me an advise
![error](https://cloud.githubusercontent.com/assets/2252876/20239257/0fd9bc44-a92f-11e6-96fc-96e4ceac4cce.png)

**Comment by brianjkd** [comment]
Do you have the Google Play Services and Android Support libraries installed? You can do this via the Android SDK Manager.

**Comment by trunghieu11** [comment]
Yes, I do. I rollback to version 0.9.32 and my game work perfect now.
