### ISSUE TITLE
"Invalid classname exception - target of an invocation" on setup

### ISSUE THREAD

**Issue by Rainking80** [playgameservices/play-games-plugin-for-unity#1482]
I updated from google play services plugin 0.9.32 to 0.9.35 and on doing setup I see this error:

![google setup](https://cloud.githubusercontent.com/assets/5574367/20240139/4ca0021e-a911-11e6-8603-733777fb41da.PNG)

I updated all JDKs, SDKs - but no fix. Switching back and it works again. Unfortunately, I can not switch back because of a collision problem with the unity firebase plugin (some namespace issues with the play service resolver - both google)

**Comment by trunghieu11** [comment]
Have you solved this problems? I stuck with this too.

**Comment by kumar-priyanshu** [comment]
Is there a solution for this problem yet? Im stuck too.
Unity 5.5.0f3
gpg plugin 0.9.35
Android SDK:
Android Support repository 41
Google Play Services 38
Google Repository 41

**Comment by claywilkinson** [comment]
Thanks for the update, some improvements were made in 0.9.36 to help identify when the Android SDK needs to be updated.  In short, if you run into this error, delete the PlayServicesResolver (and PlayServicesResolver.meta) and reimport 0.9.36 of the plugin.

**Comment by Lestat** [comment]
I have this error in latest version, I have deleted resolver and reimported, still get the error
