### ISSUE TITLE
PlayGamesPlatform.Instance.GetServerAuthCode()

### ISSUE THREAD

**Issue by zh312ww** [playgameservices/play-games-plugin-for-unity#1483]
PlayGamesPlatform.Instance.GetServerAuthCode((CommonStatusCodes code, string str)=>{
					Debug.Log("======================== GetServerAuthCode code "+code.ToString()+" token "+str);
				});

  [Play Games Plugin DLL] 11/14/16 12:45:11 +08:00 ERROR: Error loading server auth code: ERROR_INTERNAL

**Comment by brianjkd** [comment]
In Unity, under the Android setup for the plugin, are you using an actual web client id, or the android client id? Make sure it is web client which you can create in the Google developer console

**Comment by zh312ww** [comment]
11-16 11:27:02.194: W/GamesServerAuthCodeOp(24566): Failed to retrieve the server auth code
11-16 11:27:02.194: W/GamesServerAuthCodeOp(24566): com.google.android.gms.auth.GoogleAuthException: INVALID_AUDIENCE
11-16 11:27:02.194: W/GamesServerAuthCodeOp(24566): 	at com.google.android.gms.auth.GoogleAuthUtilLight$1.exec(GoogleAuthUtilLight.java:498)
11-16 11:27:02.194: W/GamesServerAuthCodeOp(24566): 	at com.google.android.gms.auth.GoogleAuthUtilLight.connectAndExecute(GoogleAuthUtilLight.java:908)
11-16 11:27:02.194: W/GamesServerAuthCodeOp(24566): 	at com.google.android.gms.auth.GoogleAuthUtilLight.getToken(GoogleAuthUtilLight.java:450)
11-16 11:27:02.194: W/GamesServerAuthCodeOp(24566): 	at com.google.android.gms.auth.GoogleAuthUtil.getToken(GoogleAuthUtil.java:586)
11-16 11:27:02.194: W/GamesServerAuthCodeOp(24566): 	at com.google.android.gms.games.service.operations.GetGamesServerAuthCodeOperation.performOperation(GetGamesServerAuthCodeOperation.java:66)
11-16 11:27:02.194: W/GamesServerAuthCodeOp(24566): 	at com.google.android.gms.games.service.operations.AbstractStatusReportingOperation.execute(AbstractStatusReportingOperation.java:49)
11-16 11:27:02.194: W/GamesServerAuthCodeOp(24566): 	at com.google.android.gms.games.service.operations.GamesOperationAdapter.execute(GamesOperationAdapter.java:23)
11-16 11:27:02.194: W/GamesServerAuthCodeOp(24566): 	at com.google.android.gms.chimera.BaseAsyncOperationService$OperationTask.run(BaseAsyncOperationService.java:177)
11-16 11:27:02.194: W/GamesServerAuthCodeOp(24566): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-16 11:27:02.194: W/GamesServerAuthCodeOp(24566): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-16 11:27:02.194: W/GamesServerAuthCodeOp(24566): 	at java.lang.Thread.run(Thread.java:818)
