### ISSUE TITLE
GPGS permission

### ISSUE THREAD

**Issue by ShadoVv91** [playgameservices/play-games-plugin-for-unity#1484]
Hey

When we login into GPGS it is asking to grant permissions to application to access some data associated with our account. 

It is asking us about: 
- access to information about age range and language
- sharing on Google+ profile and displaying activities in games
- displaying basic information about your profile
- unregistered Android application (this one is obvious because we installing it directly form unity or from apk) 

And our problem is, that we didn't add any of these in code. In Android documentation and in read me you mentioned that, it is possible to add permissions in code by adding it to PlayGamesClientConfiguration with a AddOauthScope method. Actually we are not adding there anything, because there is no need, but application still asking about them (using only Achievements and Leaderboards). 

Our configuration of GPGS:
`            config = new PlayGamesClientConfiguration.Builder().Build();
            PlayGamesPlatform.InitializeInstance(config);`

Is there any way to manage these scopes (e.g. like android permissions changing manifest) or they are obligatory to use GPGS?

**Comment by n-zakharchenko** [comment]
The same problem for me. I think that in deep of plugin requests GET_ACCOUNTS permission, but it is not necessary for basic Play Games Services.

**Comment by claywilkinson** [comment]
This sounds like you have requireGooglePlus enabled.  (or an old version of the client libraries for play-services).  If you remove that it should reduce the consents needed.

As far as scopes, there is a way on the Configuration builder to set the requested scopes.
