### ISSUE TITLE
How to avoid embedded useragent when signing in on IOS 9+?

### ISSUE THREAD

**Issue by Dod2** [playgameservices/play-games-plugin-for-unity#1485]
Hi guys. 

I've been having this problem on IOS where I can successfully sign in with google on IOS 8, but when trying the very same build on IOS 9+ I'm gracefully greeted with this message.

 
![15049596_10157665200845524_1243414799_n](https://cloud.githubusercontent.com/assets/7491545/20323984/822146ca-ab44-11e6-8a30-2d46bed6ed53.jpg)

After googling for a while I found that IOS 9+ needs to use an in-app browser tab pattern due to security reasons instead of the embedded UIWebView. (basically I read this readme https://github.com/openid/AppAuth-iOS) But I don't really know if this keeps being true for this plugin in particular.

So, does anyone know a way to force the plugin to use a web browser-based login prompt? Or should the embedded view work properly on IOS 9 and I'm doing something wrong?

I'm using the 0.9.35 version of the playgames plugin, Unity 5.3.6f1, Xcode 8.

Also using the pod GooglePlayGames 5.1 and removing the GoogleSignIn.framework from build phases on Xcode in order to successfully compile because of #1461 and #1460 

Any hint on the right direction would be greatly appreciated!

**Comment by kiwiwalks** [comment]
Same for me. Please somebody help...T.T

**Comment by stylixpro** [comment]
same here...

**Comment by Naderino** [comment]
Same for me. When did google update this embedded webview constaint? Seems like it was very recent. using Google Search is leading me to results with issues same issues dated only a week ago or so.

**Comment by Naderino** [comment]
Seems the devs have to update their plugin... Looks like we will be stuck with this issue for a little while

**Comment by Dod2** [comment]
Yeah, basically. Only way to build successfully is with the pod GooglePlayGames 5.1, which implements a very outdated GoogleSignIn dependency (2.2.0). Funny thing is that the very next version of GoogleSignIn is the one that starts using the correct web browser pattern.

Some people actually can login with the embedded view with just a warning, like https://github.com/playgameservices/play-games-plugin-for-unity/issues/1461#issuecomment-261152628 but I've tried everything I could with no luck.  Right now the only thing we've got left is to wait for our Google overlords to update the plugin.

**Comment by Dod2** [comment]
Hey guys, today i was able to successfully login with just a warning on ios 9 and 10.

Maybe Google did something, so you might want to test it out again.

**Comment by andrewio** [comment]
@Dod2 i still have disallowed_useragent

**Comment by santiandrade** [comment]
Same "disallowed_useragent" problem here... =(

**Comment by claywilkinson** [comment]
iOS build changes have been made 0.9.36.  Using that version and the instructions for building in the readme, you should be able to sign-in if you have an existing games lite account.  iOS does not support new game lite account creation.  See: https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html for more details.
