### ISSUE TITLE
Strip leaderboard, multiplayer, quest, snapshot, video from aar

### ISSUE THREAD

**Issue by nhatnd** [playgameservices/play-games-plugin-for-unity#1487]
Hi,
We are reaching the 65k limit method references in our unity android game. Now we want to remove those folder (leaderboard, multiplayer, quest, snapshot, video) in the file play-services-games-9.8.0.aar. But after removing, there error appear even if we didn't use these function:

`GamesUnitySDK: Performing Android initialization of the GPG SDK
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/Leaderboard: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/LeaderboardBuffer: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/Leaderboards: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/LeaderboardScore: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/LeaderboardScoreBuffer: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/LeaderboardVariant: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/Leaderboards$LeaderboardMetadataResult: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/Leaderboards$LoadScoresResult: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Invitation: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/InvitationBuffer: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Invitations: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Invitations$LoadInvitationsResult: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Multiplayer: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Participant: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/ParticipantResult: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/LoadMatchesResponse: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatch: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchBuffer: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchConfig: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchConfig$Builder: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$CancelMatchResult: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$InitiateMatchResult: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LeaveMatchResult: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LoadMatchesResult: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LoadMatchResult: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$UpdateMatchResult: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quest: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/QuestBuffer: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quests: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Milestone: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quests$LoadQuestsResult: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quests$AcceptQuestResult: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quests$ClaimMilestoneResult: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMessageReceivedListener: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMultiplayer: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMessage: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/Room: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RoomConfig: an exception occurred.
11-16 14:57:50.701 24463 24477 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RoomConfig$Builder: an exception occurred.
`

Is there any safe way to remove them ?

Thanks.

**Comment by robinDesBits** [comment]
Same problem here, I'm just using the leaderboard, don't need other things...

**Comment by khld85** [comment]
Same Problem, I only need Saved Game... anyone with a suggestions?

**Comment by claywilkinson** [comment]
I've passed along the request to the C++ SDK team (the plugin uses the C++ SDK).  But at this time there is no way to remove these references.  The only work around (and it might be a substantial amount of work) is to use JNI to your own java library and bypass the C++ SDK in the plugin.

**Comment by VusalJalilov** [comment]
Any update on this? A safe way to remove unused features from the plug-in is so needed.

**Comment by claywilkinson** [comment]
Not at this time.  I have re-iterated with the C++ SDK team that it would be very nice to have a more modular structure.
