### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by wolfsmash** [playgameservices/play-games-plugin-for-unity#1489]
Here is my code, Login popups, press allow and then disappears and gives no:

`using GooglePlayGames;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;

public class GPSetup : MonoBehaviour {

	public GameObject box;

	void Start () {

		PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().EnableSavedGames().RequireGooglePlus().Build();
		PlayGamesPlatform.InitializeInstance(config);
		PlayGamesPlatform.DebugLogEnabled = true;
		PlayGamesPlatform.Activate();

		login ();
	}

	void Update() {
		
	}

	void login() {
		Social.localUser.Authenticate((bool success) =>
			{
				box.GetComponent<TextMesh>().text = "trying?";
				if (success == true)
				{
					box.GetComponent<TextMesh>().text = "YOURE IN!";
				}
				else {
					box.GetComponent<TextMesh>().text = "NOPE!";
				}
		});
	}
}`

**Comment by imranNamalian** [comment]
Same issue is here. Error code is 100004.

**Comment by wolfsmash** [comment]
Okay so I copied the minimal sample script and everything worked fine...

**Comment by imranNamalian** [comment]
Bro we are facing this problem that's why we post it here. Would you like to explain a little bit. If you can make a tutorial this will be great. :)

**Comment by wolfsmash** [comment]
Look at the Minimal project code

**Comment by sorab2142** [comment]
@imranNamalian Check if you're signing the app with your own keystore and not the debug keystore. Ref: http://stackoverflow.com/questions/25617715/google-play-games-application-in-alpha-beta-test-error-10004-at-sign-in-resu
