### ISSUE TITLE
Check network message keeps popping up

### ISSUE THREAD

**Issue by Subliminalman** [playgameservices/play-games-plugin-for-unity#149]
So I was having an issue where I would have a looping login screen as described [here](https://github.com/playgameservices/play-games-plugin-for-unity/issues/109).

I'm running Android 2.3.4 on my LG G2x and I also tried on my friends Samsung Galaxy S5.

When I try to run Social.localUser.Authenticate in my game to login a user on it will show the startup of Google Play services do a loading image then popup an error message "Failed to sign in. Please check your network connection and try again." each time even though I'm connected via wi-fi and can connect to Google Play via other games.

In my logcat I do notice this error the first time I try logging in and I suspect it has to do with it.
```
Failed resolving Lcom/google/android/gms/games/internal/PopupManager$PopupManagerHCMR1; interface 908 'Landroid/view/View$OnAttachStateChangeListener;'
W/dalvikvm( 6386): Link of class 'Lcom/google/android/gms/games/internal/PopupManager$PopupManagerHCMR1;' failed
E/dalvikvm( 6386): Could not find class 'com.google.android.gms.games.internal.PopupManager$PopupManagerHCMR1', referenced from method com.google.android.gms.games.internal.PopupManager.a
W/dalvikvm( 6386): VFY: unable to resolve new-instance 2337 (Lcom/google/android/gms/games/internal/PopupManager$PopupManagerHCMR1;) in Lcom/google/android/gms/games/internal/PopupManager; 
```

Any idea what could be causing this?

**Comment by claywilkinson** [comment]
@Subliminalman  - I am closing this issue since the plug in has been re-architected in version 0.9.11 and I believe your issue is obsolete.  If you are having this issue with the latest version of the plugin, please re-open this issue.  Thanks!
