### ISSUE TITLE
WARNING: No compatible versions of com.android.support:support-v4 required by (com.google.android.gms:play-services-basement:9.8.0), will try using the latest version 24.0.0

### ISSUE THREAD

**Issue by satyagames** [playgameservices/play-games-plugin-for-unity#1490]
Can some one slove this issue......

WARNING: No compatible versions of com.android.support:support-v4 required by (com.google.android.gms:play-services-basement:9.8.0), will try using the latest version 24.0.0
UnityEngine.Debug:Log(Object)
Google.JarResolver.PlayServicesSupport:Log(String, Boolean)
Google.JarResolver.PlayServicesSupport:ResolveDependencies(Boolean)
GooglePlayServices.ResolverVer1_1:DoResolutionNoAndroidPackageChecks(PlayServicesSupport, String, OverwriteConfirmation)
GooglePlayServices.<DoResolution>c__AnonStorey1:<>m__0()
GooglePlayServices.ResolverVer1_1:DoResolution(PlayServicesSupport, String, OverwriteConfirmation, Action)
GooglePlayServices.PlayServicesResolver:Resolve(Action)
GooglePlayServices.PlayServicesResolver:AutoResolve()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

WARNING: No compatible versions of com.android.support:support-annotations required by (com.android.support:support-v4:23.1+, com.android.support:support-v4:24.0.0), will try using the latest version 24.0.0
UnityEngine.Debug:Log(Object)
Google.JarResolver.PlayServicesSupport:Log(String, Boolean)
Google.JarResolver.PlayServicesSupport:ResolveDependencies(Boolean)
GooglePlayServices.ResolverVer1_1:DoResolutionNoAndroidPackageChecks(PlayServicesSupport, String, OverwriteConfirmation)
GooglePlayServices.<DoResolution>c__AnonStorey1:<>m__0()
GooglePlayServices.ResolverVer1_1:DoResolution(PlayServicesSupport, String, OverwriteConfirmation, Action)
GooglePlayServices.PlayServicesResolver:Resolve(Action)
GooglePlayServices.PlayServicesResolver:AutoResolve()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

![googleplayservices warning](https://cloud.githubusercontent.com/assets/7609853/20421415/b3000c12-ad89-11e6-88a7-cdb56a906974.png)

**Comment by czater** [comment]
i have the same issue :/

**Comment by wolfsmash** [comment]
From what I can tell, everyone has this warning. I'm pretty sure that it has something to do with the plugin in itself. It's nothing you can fix, really. I have the same thing, and all aspects of the plugin seem to work properly. For now, ignore and move on until the plugin is updated.

Good luck,
Bryce

**Comment by ofreyre** [comment]
Before updating Android SDK I had no problem. The issue appeared after updating SDK. Sadly, I didn't checked the previous state of my SDK.

**Comment by claywilkinson** [comment]
The warning is harmless - it is from some inconsistencies in the metadata - we're working on resolving the situation, but it is safe to ignore the warning.
