### ISSUE TITLE
No valid name for platform: 37

### ISSUE THREAD

**Issue by tonio1206** [playgameservices/play-games-plugin-for-unity#1491]
When I import the Google Play Service to Unity, I get this error message:
https://drive.google.com/open?id=0B7JcBeBehMJ-ZG5ocWN5MFE3YTQ

When I get this error, I can't do anything but delete all the files related to the Play Servcies in my Assets folder.

Hope you can help,
regards

**Comment by Yalfoosh** [comment]
Update your Unity to the latest version. I've had this problem on 5.2.3, it vanished once I updated my Unity to 5.4.3 64-bit.

**Comment by tonio1206** [comment]
I resolved everything by updating all softwares,
