### ISSUE TITLE
Connecting UI when automatically login

### ISSUE THREAD

**Issue by coolguji** [playgameservices/play-games-plugin-for-unity#1492]
In "Quality Checklist for Google Play Games Services"
https://developers.google.com/games/services/checklist
1.9	Good-to-have	Display the 'Connecting' pop-up appropriately during sign-in.
But when I call Authenticate(), There is no 'Connecting' pop-up. Why?
Anyway, I can call sign out before Authenticate(), It will have 'Connecting' pop-up, but every time it will let play choose the account. How can i disable the choose account?

**Comment by claywilkinson** [comment]
I'd recommend going with just calling Authenticate and only call sign-out when the player explicitly calls sign out.  There was a change in 2016 that is known as Games "Lite" and this changed the sign-in flow to be less annoying.  One of the changes is that the connecting screen is only shown if the cached credentials fail an internal test of validity and a round trip to the server is needed.

Signing-out clears the credential, so it is always shown.
