### ISSUE TITLE
Play Services and Analytics conflict

### ISSUE THREAD

**Issue by stigmawall** [playgameservices/play-games-plugin-for-unity#1493]
Hi, I'm using this plugin for a mobile game project, and realize that I need some demographic data, so I decided to use Google Analytics plugin for Unity. Unfortunately, when I finish the Import they show two errors that I could'n find any solution.

Assets/PlayServicesResolver/Editor/IResolver.cs(74,27): error CS0433: The imported type `Google.JarResolver.PlayServicesSupport' is defined multiple times

Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs(146,56): error CS0433: The imported type `Google.JarResolver.Dependency' is defined multiple times

It's probably something simple to solve, but I didn't find what it is. Someone here know about it? Thank you for the help.

**Comment by kiberzauras** [comment]
Try to reimport analytics, then reimport google play services - after that go to `Assets` -> `Play Services Resolver` -> `Version Handler` -> `Update`, after update errors should disappear.
Thought this doesnt compile if you also have GoogleMobileAds package, so kind of admob and analytics conflic...
