### ISSUE TITLE
"Unable to find jar in the system path" - 100% Sure it's in the path already...

### ISSUE THREAD

**Issue by TinyTitanAli** [playgameservices/play-games-plugin-for-unity#1494]
This plugin never sees to amaze me of how consistent and stubborn it is every time I install or update it with the right-off-the-bat errors and frustrations. With all respect to the author, but this is the most broken thing I've ever used in my life of programming...

Here's the latest and greatest:

![the fuck](https://cloud.githubusercontent.com/assets/16493154/20582074/b001aa68-b1ab-11e6-902b-5931df9e4cf2.png)

All the paths are there, yet I'm still getting the error. I never had this issue in the previous version I was using.

Any ideas?

**Comment by wfowler1** [comment]
If you look in the path "C:\Program Files\Java\jdk1.8.0_111\bin" is there a "jar.exe" in there? I ask because there isn't one in my Program Files, but there IS one in my Program Files (x86).

**Comment by claywilkinson** [comment]
@wfowler1 is correct  - the plugin needs  jar.exe in some cases.  Can you share where jar.exe is located?  Does it work if you add that path to your path environment variable?

I agree that there are a lot of moving parts to making Play Game Services work in Unity.  Things like, JDK paths, Unity versions and plugin management, dependency on the Android SDK, and external configuration make it tricky.  Please share your ideas to make it better.
