### ISSUE TITLE
Global Leaderboard

### ISSUE THREAD

**Issue by Boowman** [playgameservices/play-games-plugin-for-unity#1495]
Not sure why but when I made my own not all the players are showing up, when I click open the default leaderboard I can see all the players. I can see all of them but very rarely and idk why it showed up.

`void Start()
    {
            if (NetworkManager.Instance.Authenticated())
            {
                    SpawnGlobalUsers();
             }
    }

    public void SpawnGlobalUsers()
    {
        List<string> globalUserIds = new List<string>();

        PlayGamesPlatform.Instance.LoadScores(GPS.leaderboard_pulse_leaderboard, LeaderboardStart.TopScores, 50, LeaderboardCollection.Public, LeaderboardTimeSpan.AllTime,
            (data) =>
            {
                for (int i = 0; i < data.Scores.Length; i++)
                {
                    globalUserIds.Add(data.Scores[i].userID);
                }

                Social.LoadUsers(globalUserIds.ToArray(), (users) =>
                {
                    for (int i = 0; i < users.Length; i++)
                    {
                        if (globalUserIds[i] == users[i].id)
                        {
                            Transform tempBar = (Transform)Instantiate(leaderboardBarPrefab, Vector3.zero, Quaternion.identity);
                            tempBar.SetParent(leaderboardList);
                            tempBar.localScale = new Vector3(1f, 1f, 1f);

                            tempBar.GetComponent<UILeaderboardButton>().UpdateBar(data.Scores[i].rank, users[i].userName, (int)data.Scores[i].value);
                        }
                    }
                });
            }
        );
    }`

**Comment by claywilkinson** [comment]
Is it hitting the limit of players returned of 50?

**Comment by ozdemir08** [comment]
Closing this issue, feel free to reopen it if you still have problems with this.
