### ISSUE TITLE
NO_GPGS still messes with xcode project.

### ISSUE THREAD

**Issue by Disar** [playgameservices/play-games-plugin-for-unity#1496]
When setting NO_GPGS frameworks and build settings are still adjusted.
In return the error : " Unityads.h " can't be found.

Which seems completely unrelated. The unityads framework is present but can't be found.

We fortunately can delete the whole plugin ( we are using Social api from unity for ios ) without issues and the xcode project is fine.

Any reason what might be causing this?

**Comment by justinkmai** [comment]
The "Unityads.h" can't be found seems to be a problem related to the UnityAds plugin. You have to remove the reference to it, and then reimport the framework and that should fix it.

**Comment by Disar** [comment]
The error is caused by whatever NO_GPGS isn't excluding and the adjustments that are made in the xcode project. After removing the whole plugin ( only for ios ) my project was fine.

I can't test the fix #1498 right now but it seems fairly what had to be done to fix the issue im facing.
