### ISSUE TITLE
NO_GPGS is adding all kinds of libraries to the xcode project

### ISSUE THREAD

**Issue by adbourdages** [playgameservices/play-games-plugin-for-unity#1501]
GoogleAppUtilties
gpg
GoogleOpenSource
GoogleSignin
GoogleSymbolUtilities

What who knows what else. I upgrade to 0.9.35 and I can't build the darn iOS project anymore. I'll have to downgrade but since it worked on Android, I now have multiple commits in between. Grrrrrr.

**Comment by Spavacz** [comment]
try solution from this PR https://github.com/playgameservices/play-games-plugin-for-unity/pull/1498

**Comment by claywilkinson** [comment]
Closing as a duplicate of #1496
