### ISSUE TITLE
API Changes in Unity3d 5.5

### ISSUE THREAD

**Issue by kenglou** [playgameservices/play-games-plugin-for-unity#1502]
There are some API Changes that breaks the play game service plugin and we need to fix some of them. Is there any plan on releasing a newer version on this?

Thank you.

**Comment by SebastianPiet** [comment]
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1432
this Issue from October 13th might help you.

👍

**Comment by Ddfh** [comment]
#1432
I tried that. It's not working.
After fixed the code like Kidel's code ( I have no errros) . But when I start my game and do ReportScore() and then ShowLeaderboardUI() no score is listed.
I'm using Unity 5.4.3.

**Comment by MuadDibAtreides** [comment]
same problem here, plz fix

**Comment by ScreennameTaken** [comment]
A Unity representative said in the forums that this is a google-side issue and they are working on it, but she had no ETA on the solution.
Seems odd to me since it should be easy for google to fix it?

**Comment by MuadDibAtreides** [comment]
patiently waiting here, I hope they t it soon

**Comment by at-longnv** [comment]
Waitting...

**Comment by at-daidd** [comment]
Waitting...

**Comment by VicEsquivel** [comment]
Waiting...

**Comment by tommyzat** [comment]
Almost same problems, after the custom fix I can't authenticate and my app crashes after exiting

**Comment by ScreennameTaken** [comment]
I used these scripts today, and when i did a build on my tablet i could see the achievements and times i did previously in my game that was built with Unity 5.4
https://github.com/playgameservices/play-games-plugin-for-unity/pull/1500/commits/670024bf6cb6c211a6214f57f76609aca13814ed

**Comment by seanny** [comment]
Would this issue be related to the fact that I cannot login to the Play Services on Android? (Mines stalls on Social.localUser.Authenticate)

**Comment by ScreennameTaken** [comment]
The 0.9.35 plugin has errors with Unity 5.5
If you are using Unity 5.4 then it's fine.
With Unity 5.5 it won't even compile.

**Comment by seanny** [comment]
@ScreennameTaken It compiles for me on 5.5, but when I attempt to login with the Unity Social API, it fails to get past the Social.localUser.Authenticate. :/

**Comment by ScreennameTaken** [comment]
Did you try the scripts from https://github.com/playgameservices/play-games-plugin-for-unity/pull/1500/commits/670024bf6cb6c211a6214f57f76609aca13814ed ?
Those worked for me and i'm able to see the level times and achievements which probably means it's authenticating.

**Comment by hippogamesunity** [comment]
+1! Please update the plugin to be compatible with Unity 5.5! Thought it is very easy to make changes myself)

**Comment by claywilkinson** [comment]
The plugin is updated to version 0.9.36 and works with Unity 5.5
