### ISSUE TITLE
No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

### ISSUE THREAD

**Issue by kgooble** [playgameservices/play-games-plugin-for-unity#1503]
Hi, I'm upgrading from version 0.9.32 of this plugin to 0.9.35 (latest as of this post). After doing the Android set up and trying to build, I'm finding that I get the following error:

```
:MainLibProj:processReleaseResources
/.../AndroidBuild/MainLibProj/build/intermediates/bundles/release/aapt/AndroidManifest.xml:31:28-65: AAPT: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

:MainLibProj:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':MainLibProj:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/local/Cellar/android-sdk/24.4.1_1/build-tools/23.0.3/aapt'' finished with non-zero exit value 1
```

Does anyone have any advice? I've already tried several things to no avail:
- Running "Resolve Client Jars" from the menu (Assets > Play Services Resolver > Android Resolver > Resolve Client Jars)
- I have the `play-services-basement-9.0.2.aar` file in my plugins directory
- Tried copying `google-play-services_lib` from my Android SDK folder to Plugins/Android, but Unity just deletes it
- Updating Google Play services, Android SDK tools for my SDK

**Comment by kgooble** [comment]
The following steps fixed the above problem:

- Add a version.xml to Assets/Plugins/Android/MainLibProj/res/values/
- Manually set the google_play_services_version to 10084000 in that xml file

**Comment by claywilkinson** [comment]
You need several play-services-*.aar files in Assets/Plugins/Android.  They should all be the same version e.g. 9.0.2.  There was a problem that did not clean up old version of the aar files, so that may have been the cause.

Hacking up the version.xml or the AndroidManifest.xml will get you past this problem, but if you are missing the client libraries, you will run into problems at runtime.
