### ISSUE TITLE
Apple Mach-O Linker (ld) Error Group

### ISSUE THREAD

**Issue by Akke** [playgameservices/play-games-plugin-for-unity#1506]
I keep getting this error below in Xcode when building for iOS. I'm using GGPS Plugin version: 0.9.35 and Xcode version 8.0 and I've tried both compiling with cocoapods and without from Unity, checked if the "Other Linker Flags" has the $(inherited) property (a solution that worked for others) as well as the "-ObjC" linker flag.

I've got the plugin to work in the past with multiple projects (even the one I'm working on now) but for some reason I keep getting this error now. Any help is much appreciated!

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GTMSessionFetcherService", referenced from:
      objc-class-ref in GoogleSignIn(GIDSignIn.o)
  "_OBJC_CLASS_$_GTMSessionFetcher", referenced from:
      objc-class-ref in GoogleSignIn(GIDRuntimeConfigFetcher.o)
      objc-class-ref in GoogleSignIn(GIDSignIn.o)
  "_OBJC_CLASS_$_GSDK_GTMSessionFetcher", referenced from:
      objc-class-ref in gpg(GPGClearcutLogger.o)
  "_OBJC_CLASS_$_GSDK_GTMSessionFetcherService", referenced from:
      objc-class-ref in gpg(GIPNetworkImage.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Dod2** [comment]
Have you tried removing the GoogleSignIn.framework from the build phases yet?

**Comment by corefire** [comment]
I'm seeing similar issue.

Unity Version: 		5.5.0f3
GGPS Plugin version: 	0.9.35
Xcode Version:		8.1

Under Capabilities:
Enabled Game Center
Enabled Associated Domains

Under Build Phases -> Link Binary With Libraries:
Removed GoogleSignIn.framework
```

podfile (Compiles)
---------------------------------
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Unity-iPhone' do
pod 'GooglePlayGames', '5.1'
end
---------------------------------

```
With the above settings and podfile I can compile the code but when you run the game it won't sign in.
I get the following error "disallowed_useragent" which has a link to this Blog Post:
https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

It would appear the old authentication method is outdated with pod 'GooglePlayGames', '5.1'

If I use the following podfile: (Recommended setup according to most recent google docs for ios integration)

```
podfile (Error)
---------------------------------
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Unity-iPhone' do
pod 'GooglePlayGames'
end
---------------------------------

```
I get an immidiate error:
Use of undeclared identifier 'GTMOAuth2ErrorTokenUnavailable'; did you mean 'kGTMOAuth2ErrorTokenUnavailable'?

I do the suggested fix then get the similar error as Akke during linking phase

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_GSDK_GTMSessionFetcher", referenced from:
      objc-class-ref in gpg(GPGClearcutLogger.o)
  "_OBJC_CLASS_$_GSDK_GTMSessionFetcherService", referenced from:
      objc-class-ref in gpg(GIPNetworkImage.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)


I've been digging around a bit but I'm not well versed in xcode compilation or pods.  Any help would be greatly appriciated.

Thanks!

**Comment by corefire** [comment]
To get the Unity project to compile I also had to do the following:

PlayGamesPlatform.cs (Add Function)

```
        public void Authenticate(ILocalUser unused, Action<bool,string> callback)
        {
            Action<bool> c = (bool a) => callback(a, "");
            Authenticate(c, false);
        }
```


PlayGamesLocalUser.cs  (Add Function)

```
        public void Authenticate(Action<bool,string> callback)
        {
            Action<bool> c = (bool a) => callback(a, "");
            mPlatform.Authenticate(c);
        }
```

**Comment by andrewio** [comment]
have the same problem. Any Progress ? 

> I've been digging around a bit but I'm not well versed in xcode compilation or pods. Any help would be greatly appriciated.
> 
> Thanks!

@corefire

**Comment by claywilkinson** [comment]
There is an updated version of the podspec for GooglePlayGames: version 5.1.2.  Please see the README file in this plugin for details.

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
