### ISSUE TITLE
CommandInvokationFailure: Failed to re-package resources.

### ISSUE THREAD

**Issue by tommyzat** [playgameservices/play-games-plugin-for-unity#1508]
Getting this error whenever I try to build:

CommandInvokationFailure: Failed to re-package resources.
D:\Android\sdk\build-tools\25.0.1\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "D:/Android/sdk\platforms\android-25\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.unity.purchasing:com.android.vending.billing:com.unity.purchasing.googleplay:com.google.example.games.mainlibproj:com.google.android.gms.ads.impl:com.google.android.gms.ads:com.google.android.gms.auth.api:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms.base:com.google.android.gms:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.tasks:android.support.v4:android.support.v4:com.unity3d.ads -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\common\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\GoogleAIDL\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\GooglePlay\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-ads-9.4.0\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-ads-lite-9.4.0\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-auth-10.0.1\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-auth-base-10.0.1\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-base-10.0.1\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-base-9.4.0\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-basement-10.0.1\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-basement-9.4.0\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-drive-10.0.1\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-games-10.0.1\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-nearby-10.0.1\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-tasks-10.0.1\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\support-v4-23.0.0\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\support-v4-24.0.0\res" -S "D:\projects\Circle Spin\Temp\StagingArea\android-libraries\unity-ads\res"

stderr[
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_alert_dialog_material.xml:111: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.internal.widget.DialogTitle>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource com.mellowlemon.circlespin:layout/abc_alert_dialog_material for configuration v17.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_dialog_title_material.xml: note: using v17 attributes; synthesizing resource com.mellowlemon.circlespin:layout/abc_dialog_title_material for configuration v17.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.internal.widget.ActionBarContainer>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource com.mellowlemon.circlespin:layout/abc_screen_toolbar for configuration v21.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_search_view.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_search_view.xml: note: using v17 attributes; synthesizing resource com.mellowlemon.circlespin:layout/abc_search_view for configuration v17.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media.xml: note: using v17 attributes; synthesizing resource com.mellowlemon.circlespin:layout/notification_template_big_media for configuration v17.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource com.mellowlemon.circlespin:layout/notification_template_big_media_narrow for configuration v17.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_lines.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_lines.xml:77: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_lines.xml:96: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_lines.xml:64: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_lines.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_lines.xml: note: using v17 attributes; synthesizing resource com.mellowlemon.circlespin:layout/notification_template_lines for configuration v17.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_media.xml:43: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <include>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_media.xml:33: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_media.xml: note: using v17 attributes; synthesizing resource com.mellowlemon.circlespin:layout/notification_template_media for configuration v17.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_part_chronometer.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <Chronometer>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_part_chronometer.xml: note: using v17 attributes; synthesizing resource com.mellowlemon.circlespin:layout/notification_template_part_chronometer for configuration v17.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_part_time.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <DateTimeView>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_part_time.xml: note: using v17 attributes; synthesizing resource com.mellowlemon.circlespin:layout/notification_template_part_time for configuration v17.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\drawable\abc_textfield_search_material.xml:19: note: removing attribute http://schemas.android.com/apk/res/android:state_activated from <item>
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\drawable\abc_textfield_search_material.xml: note: using v11 attributes; synthesizing resource com.mellowlemon.circlespin:drawable/abc_textfield_search_material for configuration v11.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-base-10.0.1\res\values\values.xml:33: error: Attribute "imageAspectRatioAdjust" already defined with incompatible format.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-basement-9.4.0\res\values\values.xml:3: Original attribute defined here.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-base-10.0.1\res\values\values.xml:46: error: Attribute "buttonSize" already defined with incompatible format.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-base-9.4.0\res\values\values.xml:21: Original attribute defined here.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-base-10.0.1\res\values\values.xml:54: error: Attribute "colorScheme" already defined with incompatible format.
D:\projects\Circle Spin\Temp\StagingArea\android-libraries\play-services-base-9.4.0\res\values\values.xml:21: Original attribute defined here.
]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: D:\Android\sdk\platforms\android-25\android.jar
applyFileOverlay for drawable
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_icon_light.xml
trying overlaySet Key=common_google_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_google_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_light_pressed.9.png
trying overlaySet Key=common_ic_googleplayservices.png
trying overlaySet Key=common_plus_signin_btn_icon_dark.xml
trying overlaySet Key=common_plus_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light.xml
trying overlaySet Key=common_plus_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark.xml
trying overlaySet Key=common_plus_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_light.xml
trying overlaySet Key=common_plus_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_pressed.9.png
trying overlaySet Key=common_full_open_on_phone.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor tvdpi-v4
baseFile 2 has flavor hdpi-v4
baseFile 3 has flavor xhdpi-v4
baseFile 4 has flavor xxhdpi-v4
overlayFile 0 has flavor hdpi-v4
overlayFile 1 has flavor xhdpi-v4
found a match (2) for overlay file common_full_open_on_phone.png, for flavor hdpi-v4
found a match (3) for overlay file common_full_open_on_phone.png, for flavor xhdpi-v4
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file common_google_signin_btn_icon_dark.xml, for flavor 
trying overlaySet Key=common_google_signin_btn_icon_dark_disabled.9.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor tvdpi-v4
baseFile 2 has flavor hdpi-v4
baseFile 3 has flavor xhdpi-v4
baseFile 4 has flavor xxhdpi-v4
overlayFile 0 has flavor mdpi-v4
overlayFile 1 has flavor hdpi-v4
overlayFile 2 has flavor xhdpi-v4
overlayFile 3 has flavor xxhdpi-v4
found a match (0) for overlay file common_google_signin_btn_icon_dark_disabled.9.png, for flavor mdpi-v4
found a match (2) for overlay file common_google_signin_btn_icon_dark_disabled.9.png, for flavor hdpi-v4
found <message truncated>

Happens since I installed google play services

**Comment by tommyzat** [comment]
UPDATE
Found out this happens only when I use this admob: https://github.com/unity-plugins/Unity-Admob

How do I fix?

**Comment by tommyzat** [comment]
Fixed. Used the official google issued admob

**Comment by Capace** [comment]
ty
