### ISSUE TITLE
ArgumentNullException: Argument cannot be null

### ISSUE THREAD

**Issue by boywithstick** [playgameservices/play-games-plugin-for-unity#1509]
I am having an issue when building my game on iOS. Here is what I am using:
Google Play Games Plugin: Version 0.9.35
Unity: 5.4.2f2

Here is the error:

ArgumentNullException: Argument cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[System.String,UnityEditor.iOS.Xcode.PBX.PBXBuildFileData].ContainsKey (System.String key) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:458)
UnityEditor.iOS.Xcode.PBXProjectData.BuildFilesGetForSourceFile (System.String targetGuid, System.String fileGuid) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProjectData.cs:93)
UnityEditor.iOS.Xcode.PBXProject.BuildFilesGetForSourceFile (System.String targetGuid, System.String fileGuid) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProject.cs:62)
UnityEditor.iOS.Xcode.PBXProject.SetCompileFlagsForFile (System.String targetGuid, System.String fileGuid, System.Collections.Generic.List`1 compileFlags) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProject.cs:212)
GooglePlayGames.Editor.GPGSPostBuild.UpdateGeneratedPbxproj (System.String pbxprojPath) (at Assets/GooglePlayGames/Editor/GPGSPostBuild.cs:242)
GooglePlayGames.Editor.GPGSPostBuild.OnPostprocessBuild (BuildTarget target, System.String pathToBuiltProject) (at Assets/GooglePlayGames/Editor/GPGSPostBuild.cs:115)
UnityEditor.HostView:OnGUI()

Anyone else run into this before?

**Comment by kshankin** [comment]
I am also having this issue.

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html

**Comment by Ghufranullah** [comment]
Hi all.
I have this type of error any one have the solution.
ArgumentNullException: Argument cannot be null.
Parameter name: collection
System.Collections.Generic.List`1[Google.JarResolver.Dependency].CheckCollection (IEnumerable`1 collection) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:435)
System.Collections.Generic.List`1[Google.JarResolver.Dependency]..ctor (IEnumerable`1 collection) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:58)
Google.JarResolver.ResolutionException..ctor (System.String msg, IEnumerable`1 missingDependencies)
Google.JarResolver.PlayServicesSupport.FindCandidate (Google.JarResolver.Dependency dep, System.Collections.Generic.List`1 repoPaths, Boolean logMissing)
Google.JarResolver.PlayServicesSupport.LoadDependencies (System.Collections.Generic.Dictionary`2 dependencies, System.Collections.Generic.List`1 repoPaths, Boolean keepMissing, Boolean findCandidates)
Google.JarResolver.PlayServicesSupport.LoadDependencies (Boolean allClients, Boolean keepMissing, Boolean findCandidates)
Google.JarResolver.PlayServicesSupport.FindMissingDependencyPaths (System.String destinationDirectory, System.Collections.Generic.Dictionary`2& dependencyPaths, Google.JarResolver.ExplodeAar explodeAar)
GooglePlayServices.ResolverVer1_1.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation, System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.Resolve (System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.AutoResolve ()
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:249)
