### ISSUE TITLE
InvalidOperationException: Attempted to use object after it was cleaned up

### ISSUE THREAD

**Issue by Jwwhite** [playgameservices/play-games-plugin-for-unity#1510]
Hi,
I have a game that I'm developing and I'm getting an error that occasionally prevents one or both of the room participants from completing the pre-match setup. (Preventing them from ever reaching the game screen.) The error that I'm getting is:

I/Unity   (17831): InvalidOperationException: Attempted to use object after it was cleaned up
I/Unity   (17831):   at GooglePlayGames.Native.PInvoke.BaseReferenceHolder.SelfPtr () [0x00000] in <filename unknown>:0 
I/Unity   (17831):   at GooglePlayGames.Native.PInvoke.BaseReferenceHolder.AsPointer () [0x00000] in <filename unknown>:0 
I/Unity   (17831):   at GooglePlayGames.Native.PInvoke.RealtimeManager.SendReliableMessage (GooglePlayGames.Native.PInvoke.NativeRealTimeRoom room, GooglePlayGames.Native.PInvoke.MultiplayerParticipant participant, System.Byte[] data, System.Action`1 callback) [0x00000] in <filename unknown>:0 
I/Unity   (17831):   at GooglePlayGames.Native.NativeRealtimeMultiplayerClient+MessagingEnabledState.SendToSpecificRecipient (System.String recipientId, System.Byte[] data, Int32 offset, Int32 length, Boolean isReliable) [0x00000] in <filename unknown>:0 
I/Unity   (17831):   at GooglePlayGames.Native.NativeRealtimeMultiplayerClient+MessagingEnabledState.SendToAll (System.Byte[] data, Int32 offset, Int32 length, Boolean isReliable) [0x00000] in <filename unknown>:0 
I/Unity   (17831):   at GooglePlayGames.Native.Nati

(The last log gets cut off for some reason.)

The pre-match setup is just sending two messages, one with the build version and the other with the name of the opponents equipped items. I send the first message and wait until receiving the version from the opponent before sending the second one. After the item message is received the match starts.

I believe that the error is occurring on the first message containing the version number but after about a week, I can't for the life of me figure out why its happening. For both the version and items, I'm using reliable messages.

Any help would be greatly appreciated.

- Jesse

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
