### ISSUE TITLE
GetAccessToken() or GetIdToken() with no extra email prompt

### ISSUE THREAD

**Issue by AVOlight** [playgameservices/play-games-plugin-for-unity#1511]
was forward here [from ](https://groups.google.com/forum/#!topic/firebase-talk/bKL3Nbesi24)

using only .AddOauthScope("profile") still prompts email selection

seems odd to me that sign-in providers don't permit developers to use them with no permissions
don't most users prefer using the provider that requires the least access?

**Comment by AVOlight** [comment]
sorry i was using GetAccessToken() directly in the Social.localUser.Authenticate(callback)
didn't realize i had to run it on the game thread

i'm only using a token for sign-in and was wondering if there's a way to avoid the extra email permission prompt

**Comment by MoinTom** [comment]
No you are not the only one. I am also looking for a solution for this behaviour.

**Comment by MoinTom** [comment]
I looked a bit deeper into it. There is an Option in the TokenClient implementation called _fetchEmail_. I followed the implementation (see below) but is seems like it doesn't seem to be relevant beside one small Code snippet where the Account-Result is fetched. Of course it's also possible that i overlook something here.

[AndroidTokenClient.cs:265](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Platforms/Android/AndroidTokenClient.cs#L265)
```c#
public string GetAccessToken() {
  if (string.IsNullOrEmpty(accessToken)) {
    if (!fetchingAccessToken) {
      fetchingAccessToken = true;
      Fetch(idTokenScope, false, true, false, (rc) => fetchingAccessToken = false);
    }
  }
  return accessToken;
}
```
Notice that _fetchEmail_ is set to **false**
[AndroidTokenClient.cs:94](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Platforms/Android/AndroidTokenClient.cs#L94)
```c#
internal void Fetch(string scope,
                            bool fetchEmail,
                            bool fetchAccessToken,
                            bool fetchIdToken,
                            Action<CommonStatusCodes> doneCallback) {
    // ...
    // Java needs to be called from the game thread.
    PlayGamesHelperObject.RunOnGameThread(() =>
    FetchToken(scope, playerId, rationale, fetchEmail, fetchAccessToken, fetchIdToken, (rc, access, id, email) => {
        // ...
        doneCallback(CommonStatusCodes.Success);
    }));
  }
```
[AndroidTokenClient.cs:159](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Platforms/Android/AndroidTokenClient.cs#L159) here we will call the native implementation (_FetchTokenMethod_ = **"fetchToken"**).
```c#
private const string FetchTokenMethod = "fetchToken";
// ...
internal static void FetchToken(string scope, string playerId, string rationale, bool fetchEmail,
                                        bool fetchAccessToken, bool fetchIdToken, Action<int, string, string, string> callback) {
            object[] objectArray = new object[7];
            jvalue[] jArgs = AndroidJNIHelper.CreateJNIArgArray(objectArray);
            try {
                using (var bridgeClass = new AndroidJavaClass(TokenFragmentClass)) {
                    using (var currentActivity = AndroidTokenClient.GetActivity()) {
                        // Unity no longer supports constructing an AndroidJavaObject using an IntPtr,
                        // so I have to manually munge with JNI here.
                        IntPtr methodId = AndroidJNI.GetStaticMethodID(bridgeClass.GetRawClass(),
                                              FetchTokenMethod,
                                              FetchTokenSignature);
                        jArgs[0].l = currentActivity.GetRawObject();
                        jArgs[1].l = AndroidJNI.NewStringUTF(playerId);
                        jArgs[2].l = AndroidJNI.NewStringUTF(rationale);
                        jArgs[3].z = fetchEmail;
                        jArgs[4].z = fetchAccessToken;
                        jArgs[5].z = fetchIdToken;
                        jArgs[6].l = AndroidJNI.NewStringUTF(scope);

                        IntPtr ptr =
                            AndroidJNI.CallStaticObjectMethod(bridgeClass.GetRawClass(), methodId, jArgs);

                        PendingResult<TokenResult> pr = new PendingResult<TokenResult>(ptr);
                        pr.setResultCallback(new TokenResultCallback(callback));
                    }
                }
            } catch (Exception e) {
                GooglePlayGames.OurUtils.Logger.e("Exception launching token request: " + e.Message);
                GooglePlayGames.OurUtils.Logger.e(e.ToString());
            } finally {
                AndroidJNIHelper.DeleteJNIArgArray(objectArray, jArgs);
            }
        }
```
[TokenFragment.java:72](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/SupportLib/PlayGamesPluginSupport/src/main/java/com/google/games/bridge/TokenFragment.java#L72)
```java
public static PendingResult fetchToken(Activity parentActivity,
                                           String playerId,
                                           String rationale, boolean fetchEmail,
                                           boolean fetchAccessToken, boolean fetchIdToken, String scope) {
  TokenRequest request = new TokenRequest(fetchEmail, fetchAccessToken, fetchIdToken, scope);
  request.setRationale(rationale);

  synchronized (pendingTokenRequests) {
    if (playerId == null || !playerId.equals(currentPlayerId)) {
      currentPlayerId = playerId;
      selectedAccountName = null;
    }

    // see if we can short circuit this process if the player already selected an account.
    if (selectedAccountName != null && fetchEmail && !fetchAccessToken && !fetchIdToken) {
      Log.i(TAG, "Returning accountName: " + selectedAccountName);
      request.setEmail(selectedAccountName);
      request.setResult(CommonStatusCodes.SUCCESS);
      return request.getPendingResponse();
    } else {
      pendingTokenRequests.add(request);
    }
 } 

 TokenFragment fragment = (TokenFragment) parentActivity.getFragmentManager().findFragmentByTag(FRAGMENT_TAG);

 if (fragment == null) {
   try {
     Log.d(TAG, "Creating fragment");
     fragment = new TokenFragment();
     FragmentTransaction trans = parentActivity.getFragmentManager().beginTransaction();
     trans.add(fragment, FRAGMENT_TAG);
     trans.commit();
   } catch (Throwable th) {
     Log.e(TAG, "Cannot launch token fragment:" + th.getMessage(), th);
     request.setResult(CommonStatusCodes.ERROR);
     synchronized (pendingTokenRequests) {
       pendingTokenRequests.remove(request);
     }
   }
 } else {
   synchronized (pendingTokenRequests) {
     if (!mIsSelecting) {
       Log.d(TAG, "Fragment exists.. and not selecting calling processRequests");
       fragment.processRequests(CommonStatusCodes.SUCCESS);
     }
   }
 }

  return request.getPendingResponse();
}
```
The class [FetchToken](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/SupportLib/PlayGamesPluginSupport/src/main/java/com/google/games/bridge/TokenFragment.java#L356) doesn't use the _fetchEmail_ later.
```java
//...
public TokenRequest(boolean fetchEmail, boolean fetchAccessToken, boolean fetchIdToken, String scope) {
   pendingResponse = new TokenPendingResult();
   doEmail = fetchEmail;
   doAccessToken = fetchAccessToken;
   doIdToken = fetchIdToken;
   this.scope = scope;
}
//...
```

**Comment by AVOlight** [comment]
Thanks for looking into this; i don't see anything sticking out. It would be nice if there were docs on this.

Wonder if someones created a independent Google Sign-In wrapper based off this source.

**Comment by MoinTom** [comment]
Yeah never mind. It seems like it is necessary to know the account name in order to get an access token through the GoogleAPI. 

**Here the flow:**

1. [TokenFragment.java:172](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/SupportLib/PlayGamesPluginSupport/src/main/java/com/google/games/bridge/TokenFragment.java#L172) | Start the _AccountPicker.newChooseAccountIntent_ for getting the right account/email
```java
// ...
if (acctName == null) {
  // set the flag so we don't prompt twice in a row.
  synchronized (pendingTokenRequests) {
    mIsSelecting = true;
  }

  // build the intent to get the account
  Intent intent = AccountPicker.newChooseAccountIntent(null, null, new String[]{"com.google"},
    true, request.getRationale(), null, null, null);
  startActivityForResult(intent, RC_ACCT);
} else {
// ...
```
2. [TokenFragment.java:322](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/SupportLib/PlayGamesPluginSupport/src/main/java/com/google/games/bridge/TokenFragment.java#L322) | Process the Activity result and take the account name 
```java
public void onActivityResult(int requestCode, int resultCode, Intent data) {
  Log.d(TAG, "onActivityResult: " + requestCode + ": " + resultCode);

  if (requestCode == RC_ACCT) {
    int status = resultCode;
    String accountName = selectedAccountName;
    if (resultCode == Activity.RESULT_OK) {
      status = CommonStatusCodes.SUCCESS;
      accountName = data.getStringExtra(AccountManager.KEY_ACCOUNT_NAME);
    } else if (resultCode == Activity.RESULT_CANCELED) {
      status = CommonStatusCodes.CANCELED;
    }

    // always clear the flag - even if it is an error.
    synchronized (pendingTokenRequests) {
      selectedAccountName = accountName;
      mIsSelecting = false;
   }
   //...
}
```
3. [TokenFragment.java:227](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/SupportLib/PlayGamesPluginSupport/src/main/java/com/google/games/bridge/TokenFragment.java#L227) | Request the accessToken through [_GoogleAuthUtil.getToken_](https://developers.google.com/android/reference/com/google/android/gms/auth/GoogleAuthUtil.html)
```java
// ...
try {
  Log.d(TAG, "getting accessToken for " + accountName);
  accessToken = GoogleAuthUtil.getToken(theActivity, accountName, accessScope);
  tokenRequest.setAccessToken(accessToken);
} catch (Throwable th) {
  Log.e(TAG, "Exception getting access token", th);
  statusCode = CommonStatusCodes.INTERNAL_ERROR;
}
// ...
```

There is no other promising Signature of  _GoogleAuthUtil.getToken_ that may select an default account or something like that. So we are basically stuck by knowing the account name.

I am not sure when [this line](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/SupportLib/PlayGamesPluginSupport/src/main/java/com/google/games/bridge/TokenFragment.java#L165) can ever be false...
```java 
// ...
// If the accountName is null, then prompt the user to select one.
if (acctName == null) {
// ...
```

**Comment by claywilkinson** [comment]
These methods are deprecated and should not be used.  The recommended way is to call GetServerAuthCode(), then pass that code to your backend server.  The server can then exchange the code for an access token.
