### ISSUE TITLE
FileNotFoundException: Xcode

### ISSUE THREAD

**Issue by Jaudatus** [playgameservices/play-games-plugin-for-unity#1512]
![unbenannt](https://cloud.githubusercontent.com/assets/24485399/21068310/6ff6fbbc-be71-11e6-9e41-b454c001352c.png)

I imported the newest version of the plugin and i get these errors when i build the game. I already searched here for a solution but they weren't useful for me. Did anyone else recognized these errors?

Would be great to find a solution because i have seen other devs with the same issue and i guess they still haven't fixed it yet or did not write down how they fixed them.

Greets :)

**Comment by claywilkinson** [comment]
The latest version of the plugin (0.9.36) fixes these problems.
