### ISSUE TITLE
[0.9.36][Google/SignIn][iOS] always getting false from Social.localUser.Authenticate

### ISSUE THREAD

**Issue by AVOlight** [playgameservices/play-games-plugin-for-unity#1515]
can build with 0.9.36

but after selecting Allow in the sign-in flow i get this
NSInvalidArgumentException: *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
ok so that was a Unity 5.5 bug
[fix here](http://answers.unity3d.com/questions/1252223/unity-55-and-facebook-sdk-not-working-well-togethe.html)

now after Allow in the sign-in flow i'm always getting false from Social.localUser.Authenticate
the iOS version also asks for a lot more permissions than the Android one
and i'm only adding one scope .AddOauthScope("email")

INFO: Auth operation started: SIGN IN
VERBOSE: Running UI sign in request on main thread.
VERBOSE: Finished running UI sign in request on main thread.
signInWillDispatch: (null)
-> applicationWillResignActive()
-> applicationDidBecomeActive()
VERBOSE: Signed in user; extracting credential.
INFO: Auth operation started: SIGN OUT
ERROR: Out of box error detected; the user must reauthenticate through the UIflow.
INFO: Auth operation started: SIGN OUT 

that SIGN OUT line shows up a lot after that

variation before user allows app

INFO: Auth operation started: SIGN IN
VERBOSE: Running UI sign in request on main thread.
VERBOSE: Finished running UI sign in request on main thread.
signInWillDispatch: (null)
-> applicationWillResignActive()
-> applicationDidBecomeActive()
VERBOSE: Signed in user; extracting credential.
WARNING: Error fetching local player for Welcome Back UI
INFO: Auth operation started: SIGN OUT
ERROR: Error retrieving user, signing out

**Comment by AVOlight** [comment]
I missed this:

"After building the XCode project, the Play Games postprocessor will run to configure the Info.plist settings on your project. You will see a log of the operation, which if successful, will give you additional instructions to finish configuring your XCode project."

I'm not getting the additional instructions

last log is
"Adding URL Types for authentication using PlistBuddy."
it's the last line in the only function tagged with [PostProcessBuild] that i could find in GPG

**Comment by AVOlight** [comment]
got it to build by ignoring the pod file and just manually importing the latest Google Sign-In SDK

but after selecting Allow in the sign-in flow i get this

`

	-> applicationWillResignActive()

	2016-12-20 11:40:27.884 GrowToRise[8371:16520492] Uncaught exception: NSInvalidArgumentException: *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil

	(

	0   CoreFoundation                      0x24993933 <redacted> + 150

	1   libobjc.A.dylib                     0x2412ee17 objc_exception_throw + 38

	2   CoreFoundation                      0x248a8d5f <redacted> + 622

	3   GrowToRise                          0x00119529 -[UnityAppController application:openURL:sourceApplication:annotation:] + 352

	4   GrowToRise                          0x00831817 -[GPGSAppController application:openURL:sourceApplication:annotation:] + 170

	5   GrowToRise                          0x010a4d8b -[FIRAAppDelegateProxy application:openURL:sourceApplication:annotation:] + 370

	6   UIKit                               0x291b6187 <redacted> + 906

	7   UIKit                               0x291b5c59 <redacted> + 544

	8   UIKit                               0x291bdeb5 <redacted> + 3660

	9   UIKit                               0x291c29ab <redacted> + 174

	10  UIKit                               0x291c28bf <redacted> + 398

	11  UIKit                               0x291ae4b3 <redacted> + 134

	12  UIKit                               0x291ae1a1 <redacted> + 644

	13  FrontBoardServices                  0x2601bcf5 <redacted> + 40

	14  FrontBoardServices                  0x26036c07 <redacted> + 18

	15  FrontBoardServices                  0x26036ab9 <redacted> + 224

	16  FrontBoardServices                  0x26036db9 <redacted> + 48

	17  CoreFoundation                      0x24955dff <redacted> + 14

	18  CoreFoundation                      0x249559ed <redacted> + 452

	19  CoreFoundation                      0x24953d5b <redacted> + 794

	20  CoreFoundation                      0x248a3229 CFRunLoopRunSpecific + 520

	21  CoreFoundation                      0x248a3015 CFRunLoopRunInMode + 108

	22  GraphicsServices                    0x25e93ac9 GSEventRunModal + 160

	23  UIKit                               0x28f77189 UIApplicationMain + 144

	24  GrowToRise                          0x000ffe3b main + 202

	25  libdyld.dylib                       0x2454b873 <redacted> + 2

	)
`

**Comment by claywilkinson** [comment]
You may be running into the fact that on iOS Games "Lite" accounts cannot be created.  This was recently announced here: https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html.

As a result, you will be stuck in an infinite loop of signing in, being presented the consent list, and then failing, and usually going back to the consent screen.

**Comment by AVOlight** [comment]
Hi Clayton, yes i get the consent screen again even if it's already allowed. 

Managed to get the scope changed by editing the GPGSAppController.mm
_GooglePlayEnableProfileScope method and calling it after 
mServices = builder.Build(config); in the InitializeGameServices method

GIDSignIn *signIn = [GIDSignIn sharedInstance];
signIn.serverClientID = @"my Web client ID attached to Firebase and Game Services";
signIn.shouldFetchBasicProfile = NO;
signIn.scopes = @[ @"email" ];

but unfortunately i'm still in the loop

**Comment by claywilkinson** [comment]
In this case there is no way out of the loop. What it means is that the user you signing in as does not have a games "lite" account associated with it.  This is a known limitation and is not expected to be fixed in the near future.  https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html.

**Comment by AVOlight** [comment]
Thanks for the info Clayton
