### ISSUE TITLE
Updated Build?

### ISSUE THREAD

**Issue by manofspirit** [playgameservices/play-games-plugin-for-unity#1516]
Hi there,
Current build is quite old and i see some fixes for 5.5 in recent commits.
When can we expect a updated build? or can i just copy/paste code from following location and use in my project?
https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/source/PluginDev/Assets

Please advise

**Comment by claywilkinson** [comment]
In the short term, copying from the source here on GitHub is the best solution.  I'll work on getting an updated Unity package posted in the next few days.

**Comment by manofspirit** [comment]
Thank you for your reply, 
So which folder should i use? the one i shared above?

**Comment by claywilkinson** [comment]
yes that is the correct path.

**Comment by claywilkinson** [comment]
The unitypackage has been updated to 0.9.36 and includes these fixes.
