### ISSUE TITLE
Metadata Property missing in PlayGamesScore?

### ISSUE THREAD

**Issue by Mukikaizoku** [playgameservices/play-games-plugin-for-unity#1518]
I was trying to load a Leaderboard score's metadata tag (scoreTag) and couldn't figure out how to do it.

Digging through the source files, it appears to me that the retrieval of the metadata string is implemented (when PlayGamesScore is created in NativeScore.cs).

However, although a metadata field is present in the PlayGamesScore class, there's no corresponding property written to allow retrieval. So I think this property just needs to be added? Let me know, thank you!

**Comment by Mukikaizoku** [comment]
Alright, adding the property to PlayGamesScore does the trick. I was able to send a metadata tag using the appropriate ReportScore method overload and retrieve it with the LoadScores method. The code I added to PlayGamesScore.cs was:

```
/// <summary>  
/// Gets the metaData (scoreTag).  
/// </summary>  
/// <returns>  
/// The metaData.  
/// </returns>  
public string metaData  
{  
	get   
	{  
		return mMetadata;  
	}  
}
```

I'll commit the change and make a pull request when I figure out the proper way of doing so.. :)

**Comment by claywilkinson** [comment]
The code looks correct. That would be awesome if you could submit a pull request!  Thanks!

**Comment by Mukikaizoku** [comment]
Pull request submitted! (#1527) Was a good opportunity to learn some basic git-skills :)
