### ISSUE TITLE
CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 

### ISSUE THREAD

**Issue by YoungthSky** [playgameservices/play-games-plugin-for-unity#1519]
When I build the demo to Android apk there is a error,can you fixed it as soon as possible?

CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
C:/Program Files/Java/jdk1.8.0_101\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="G:/SDK\tools" -Dfile.encoding=UTF8 -jar "D:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[

]
stdout[
Warning: [Temp\StagingArea\AndroidManifest-main.xml:14, E:\UnityTestProject\Gvr1208\Temp\StagingArea\android-libraries\gvr-permissionsupport-release\AndroidManifest.xml:3] Main manifest has <uses-sdk android:targetSdkVersion='22'> but library uses targetSdkVersion='24'
]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.HostView:OnGUI()

**Comment by claywilkinson** [comment]
What minSDK are you using in the Unity Android player player properties?  GVR needs min of 24.  This message usually means that there is a library or plugin using a minSDK value greater than the one in the player.

**Comment by claywilkinson** [comment]
Please re-open if setting the min version to 24 did not help.
