### ISSUE TITLE
XCODE, building for iOS - undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by wolodo** [playgameservices/play-games-plugin-for-unity#1520]
every time, I try to build the application for iOS, I get this errors (xcode build):

`Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_GSDK_GTMSessionFetcher", referenced from:
      objc-class-ref in gpg(GPGClearcutLogger.o)
  "_OBJC_CLASS_$_GSDK_GTMSessionFetcherService", referenced from:
      objc-class-ref in gpg(GIPNetworkImage.o)
  "_GTMMethodCheckMethodChecker", referenced from:
      +[NSDictionary(GTMNSDictionaryURLArgumentsAdditions) xxGTMMethodCheckMethodNSString32] in libGoogleToolboxForMac.a(GTMNSDictionary+URLArguments.o)
      +[NSDictionary(GTMNSDictionaryURLArgumentsAdditions) xxGTMMethodCheckMethodNSString33] in libGoogleToolboxForMac.a(GTMNSDictionary+URLArguments.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

i have cocoapods installed and gpg services properly configured. am I missing something or is this a plugin issue?

I use unity 5.3.6f1 and xcode 8.1

**Comment by wolodo** [comment]
I managed to solve it by myself. The key is to edit the pod file like this (tested with the unity 5.3.6f1, GPG games plugin 0.9.34 and xcode 8.1):

    platform :ios, '8.0'
    
    target 'Unity-iPhone' do
    pod 'GooglePlayGames', '5.1'
    end

then you need to run `pod install` and it works!

**Comment by claywilkinson** [comment]
Thanks for the debugging.
I updated the README with instructions and a Podfile example.  I confirmed this works when using version 0.9.36 of the plugin.
