### ISSUE TITLE
Crash when using Saved Games

### ISSUE THREAD

**Issue by tommyzat** [playgameservices/play-games-plugin-for-unity#1521]
Hello!

Calling this on Awake crashes my game:

`    private void Awake()
    {
        PlayGamesClientConfiguration config = new   PlayGamesClientConfiguration.Builder().EnableSavedGames().Build();
        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.Activate();
        connect();
    }

    public void connect()
    {
        Social.localUser.Authenticate((bool success) =>
        {
        });
    }`

**Comment by claywilkinson** [comment]
Can you share the log?

**Comment by korea-doko** [comment]
my problem is too,

i check saved game in google console,

**Comment by claywilkinson** [comment]
@korea-doko - can you start a new issue and share your log?  I don't want to confuse these situations if they are different.  Thanks!

**Comment by korea-doko** [comment]
t
