### ISSUE TITLE
Appears to sign in but doesnt

### ISSUE THREAD

**Issue by 12boulla** [playgameservices/play-games-plugin-for-unity#1523]
I have recently been rattling my brains out trying to implement Google Play Games Services into my unity game (I always have incredible difficulties). I have finally got it working (ish) to the extent that I can open the sign in dialog. However, when the user signs in, it doesnt sign in correctly. It appears to sign in, and the username and icon at the top appears:
![image](https://cloud.githubusercontent.com/assets/16444027/21293531/5e0cc27e-c51f-11e6-950d-86b930a9a26d.png)

But every time the user clicks the leaderboards button, or closes and reopens the app, they are asked to sign in again. It appears as though the user is not being authenticated each time. This is my sign in code:

`using UnityEngine;
using System.Collections;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;

public class SignIn : MonoBehaviour {

	// Use this for initialization
	void Start () {
		PlayGamesPlatform.Activate();
		Social.localUser.Authenticate((bool success) => {
			// handle success or failure
			if(success)
				Debug.Log("SUccess");
			else
				Debug.Log("Fail");
		});
	
	}
	
	// Update is called once per frame
	void Update () {
	
	}
}`

I am using Unity 4.6.9, however I don't know if this is the issue. I have made games before where it has worked successfully, however, none of them work now and all have the same problem. I have no idea what to do at this point, any help is greatly appreciated.
Thanks.

EDIT:
I'll add a sample of the logcat output that seemed to contain an error of sorts, not sure if its relevant:

`I/Auth    (  929): [DefaultAuthDelegateChimeraService] Use browser flow? false
E/DataHolderOperation( 2122): Auth error while performing operation, requesting
reconnect
E/DataHolderOperation( 2122): com.google.android.gms.auth.UserRecoverableAuthExc
eption: NeedPermission
E/DataHolderOperation( 2122):   at com.google.android.gms.auth.GoogleAuthUtilLig
ht$1.exec(GoogleAuthUtilLight.java:498)
E/DataHolderOperation( 2122):   at com.google.android.gms.auth.GoogleAuthUtilLig
ht.connectAndExecute(GoogleAuthUtilLight.java:908)
E/DataHolderOperation( 2122):   at com.google.android.gms.auth.GoogleAuthUtilLig
ht.getToken(GoogleAuthUtilLight.java:450)
E/DataHolderOperation( 2122):   at com.google.android.gms.auth.GoogleAuthUtil.ge
tToken(GoogleAuthUtil.java:586)
E/DataHolderOperation( 2122):   at com.google.android.gms.common.server.auth.Aut
hSessionAuthenticator.getOrThrow(AuthSessionAuthenticator.java:98)
E/DataHolderOperation( 2122):   at com.google.android.gms.common.server.Abstract
Server.getAuthTokenOrThrow(AbstractServer.java:109)
E/DataHolderOperation( 2122):   at com.google.android.gms.common.server.BaseApia
ryServer.getAuthTokenOrThrow(BaseApiaryServer.java:31)
E/DataHolderOperation( 2122):   at com.google.android.gms.games.server.GamesServ
er.getAuthTokenOrThrow(GamesServer.java:156)
E/DataHolderOperation( 2122):   at com.google.android.gms.common.server.BaseApia
ryServer.getResponseBlockingInternal(BaseApiaryServer.java:378)
E/DataHolderOperation( 2122):   at com.google.android.gms.common.server.BaseApia
ryServer.getResponseBlocking$fdbd10f(BaseApiaryServer.java:348)
E/DataHolderOperation( 2122):   at com.google.android.gms.common.server.BaseApia
ryServer.getResponseBlocking(BaseApiaryServer.java:327)
E/DataHolderOperation( 2122):   at com.google.android.gms.games.server.GamesServ
er.getResponseBlocking(GamesServer.java:170)
E/DataHolderOperation( 2122):   at com.google.android.gms.games.broker.Achieveme
ntAgent.flushPendingOp(AchievementAgent.java:758)
E/DataHolderOperation( 2122):   at com.google.android.gms.games.broker.Achieveme
ntAgent.flushPendingOps(AchievementAgent.java:719)
E/DataHolderOperation( 2122):   at com.google.android.gms.games.broker.Achieveme
ntAgent.fetchAchievements(AchievementAgent.java:1110)
E/DataHolderOperation( 2122):   at com.google.android.gms.games.broker.DataBroke
r.getAchievements(DataBroker.java:2342)
E/DataHolderOperation( 2122):   at com.google.android.gms.games.service.operatio
ns.achievements.LoadAchievementsOperation.fetchData(LoadAchievementsOperation.ja
va:33)`

**Comment by claywilkinson** [comment]
It looks like the re-authentication is what is causing the user to sign in again.  Are you using the latest version of the play-services libraries?  That would be an easy thing to try to see if the underlying cause of the re-authentication is fixed.

**Comment by 12boulla** [comment]
Hmm. I am using the latest version - 0.9.35 and I only downloaded it from the GitHub page this week. The strange thing about this is that it appears to work just fine on my other device, so maybe it is a device specific issue. All my Unity games on one device with GPGS has this problem, however another game with GPGS on the same device works fine. And all my games on another device work fine too, so I'm quite confused with what is happening.

**Comment by claywilkinson** [comment]
On the "troubled" device, can you make sure that you have updated Google Play Services and the Google Play Games App?  What versions of those apps are you running on each device?  Are they both running the same version of Android?  Can you share the versions?

**Comment by 12boulla** [comment]
On the troubled device which is Android 4.4.2 the Google Play Games version is 3.9.08(3448271-032), and the Google Play Services is version 10.0.84(032-137749526). On the other device which is Android 4.2.2, the versions of the Google Play Games and Play Services are the same.

**Comment by claywilkinson** [comment]
Are you using the same user account on both devices? 
I doubt  the version of Unity would make a difference.
So it definitely sounds like it is device specific - could it be something like having anti-piracy enabled on the game and the troubled device is rooted? (I am not sure that makes any difference, just trying to think what else could be different).

**Comment by 12boulla** [comment]
I am indeed using the same user on both devices. I tried adding another google account and logging in, and it seemed to work as it should do, and signs in correctly allowing me to access the leaderboards. When I tried to sign out and log in with the other account again, it persisted with the issue. So maybe it is an issue with using the same account on the same game on multiple devices, although I never used to have this problem. And the troubled device is not rooted.

**Comment by claywilkinson** [comment]
That is very strange.  Thanks for the info.  So it seems to be one account on one device that is having problems?  Maybe the cached data is in a weird state for that user?  I know this is an extreme suggestion, but can you remove and re-add that user to the device?

**Comment by 12boulla** [comment]
I just gave it a shot and after adding the account the problem is still there. Do you think it would be worth trying the same on my other device?

**Comment by claywilkinson** [comment]
I guess it can't hurt to try other things. Can you share the full log of the troubled log in?  Ideally including the startup, the first authentication and then click the leaderboard and capture the authentication flow again?

**Comment by claywilkinson** [comment]
Another long-shot question - does the trouble device have available storage space?

**Comment by claywilkinson** [comment]
Any other contributions to this, or is it OK to close this as it seems like a device specific issue?
