### ISSUE TITLE
Plugins is not longer working in Unity 5.5

### ISSUE THREAD

**Issue by kiranmaya** [playgameservices/play-games-plugin-for-unity#1524]
Unity changed their social platform api ,and this plugin is not compatible with the new scocial authentical api.

**Comment by jsaade** [comment]
Unity added callbacks to iLocalUser and ISocialPlatform that take an optional string.

you can just put empty wrappers and it might work

**Comment by kiranmaya** [comment]
Thanks  jsaade  ,Everything is good now .i can able post scores and showing the leaderboard ui  .
