### ISSUE TITLE
About the upcoming changes - Multiplayer Status

### ISSUE THREAD

**Issue by sorab2142** [playgameservices/play-games-plugin-for-unity#1525]
https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html
states that G+ integration will be dropped entirely so...

Does this mean that we can no longer invite friends to a multiplayer game? because that is from their google+ circles. Or is the entire multiplayer platform being dropped/revamped? As It mentions the Invite UI (and other G+ graph related stuff) will not work beyond Feb 2017 and just return an empty screen. 

How do we go about inviting another player after Feb 2017?

**Comment by claywilkinson** [comment]
You are correct, the Google+ is being removed from Play Game Services.  I don't have any specific information for plans after the Feb. target date. I'll be sure to promptly update everyone as I find out more.

Can you share a little about how you are or planning to use multiplayer?  It is a currently published game?  Is it turn-based or realtime?  Feel free to share here, or if you have a Business Dev. contact from Google via them if you want to communicate privately.

**Comment by sorab2142** [comment]
We have one published real-time multiplayer title, in which we use both the Quick Match (auto-find) and Invite a Friend feature. Going forward will the Quick Match be functional or is that also going to be removed?

**Comment by claywilkinson** [comment]
I'll pass along the question and update the thread when I know more.

**Comment by zory** [comment]
Is there any news about all matchmaking, quick match, google+ in multiplayer, and multiplayer at all?
Or maybe at least some one, who have already published game with these features, knows how everything is working right now after google+ disappearing from GPGS?

**Comment by NanaDada** [comment]
Any news so far about how to handle friend invites for multiplayer games?

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
