### ISSUE TITLE
xCode Build error GoogleSignIn/GIDSignIn.h file not found 

### ISSUE THREAD

**Issue by colender** [playgameservices/play-games-plugin-for-unity#1526]
Hello I updated the unity plugin to 0.9.36 when I tried to build in xcode for it to run on the iphone I get build failed that I am missing `<GoogleSignIn/GIDSignIn.h>` file not found .

I followed the new steps which we have to create the Podfile. 

I am using 
Unity 5.4.1 
Google Play Services : 5.1.2 
Xcode : 8.1 
ios: 8.0 

![screen shot 2016-12-20 at 5 36 38 pm](https://cloud.githubusercontent.com/assets/185928/21374562/76edef48-c6dc-11e6-94e6-1a36030c6ff4.png)
![screen shot 2016-12-20 at 5 38 35 pm](https://cloud.githubusercontent.com/assets/185928/21374565/7c023e3a-c6dc-11e6-868a-32fb45248a62.png)

**Comment by claywilkinson** [comment]
Did you open the .xcworkspace or the xcproject?  You'll need to make sure you create the Podfile and run `pod install` (which it looks like you did) and then open the .xcworkspace to build.

Also, if there are warnings about adding $(inherited) to some values, you should do that.

**Comment by colender** [comment]
I did get those warnings I'll try them out thanks for the replay.

**Comment by colender** [comment]
how would you add the $(inherited) value 
![screen shot 2016-12-21 at 10 55 43 am](https://cloud.githubusercontent.com/assets/185928/21402164/1bf382f2-c76c-11e6-8627-f7ccc0462efa.png)

**Comment by claywilkinson** [comment]
Expand each of Debug and Release for the key you want to change, then it will show the list of values.  Add $(inherited) to the front of the list.
![screen shot 2016-12-21 at 11 02 03 am](https://cloud.githubusercontent.com/assets/8752378/21402403/1c6cc148-c76d-11e6-9788-00f34cbcb549.png)

**Comment by boywithstick** [comment]
Adding $(inherited) didn't work for me when I had this issue. I had to change the flag from non-recursive to recursive for the $(inherited) values. I also changed $(PROJECT_DIR)/Frameworks to recursive under the Framework Search Path. Additionally, I added the $(PROJECT_DIR)/Frameworks value to the Header Search Paths and set it to recursive.

**Comment by boywithstick** [comment]
Here's the post I found that lead me this is:
[http://stackoverflow.com/questions/18704334/xcode-cant-find-header-files-in-unity3d-project](url)

> Unity iOS supports automated plugin integration in a limited way. All files with extensions .a,.m,.mm,.c,.cpp located in the Assets/Plugins/iOS folder will be merged into the generated Xcode project automatically. However, merging is done by symlinking files from Assets/Plugins/iOS to the final destination, which might affect some workflows. The .h files are not included in the Xcode project tree, but they appear on the destination file system, thus allowing compilation of .m/.mm/.c/.cpp files.
Note: subfolders are currently not supported.

**Comment by boywithstick** [comment]
Sorry, I deleted previous posts because it was in regards to another issue I was having. My bad. Just ignore me. I'm tired.

**Comment by colender** [comment]
still get the same error. I added the flags but doesn't seam to build 
![screen shot 2016-12-21 at 11 30 32 am](https://cloud.githubusercontent.com/assets/185928/21403283/02b39520-c771-11e6-9bb6-3691a46170c1.png)

**Comment by boywithstick** [comment]
Try adding $(PROJECT_DIR)/Frameworks value to Header Search Paths and set it to recursive.

**Comment by colender** [comment]
@boywithstick  I tried it also didn't work I wonder if I am the only with this error

**Comment by colender** [comment]
After playing around with it I finally got it to build. Here is what I did in case someone else also has a similar problem. 

I added the $(inherited) as @claywilkinson mentioned After adding in the other linker flags I added $(inherited) to **Framework Search Paths** **Header Search Paths** and **Library Search Path** 

![screen shot 2016-12-21 at 5 03 33 pm](https://cloud.githubusercontent.com/assets/185928/21411844/656d9704-c7a0-11e6-8507-c644739c7b7c.png)

After adding those flags it finally passed compiling section, but I got a linker Bitcode error I just changed the Enable **Bitcode** to **no** 
![screen shot 2016-12-21 at 5 04 51 pm](https://cloud.githubusercontent.com/assets/185928/21411873/b380c8e4-c7a0-11e6-88c2-b5fcef0d8c8d.png)

After all this it finally build successfully and was loaded to the phone everything works. Hope this helps

**Comment by claywilkinson** [comment]
Glad you got it working!  Thanks for sharing what it took to make it work.

**Comment by vanshikakapoor** [comment]
![screen shot 2017-02-23 at 5 33 28 pm](https://cloud.githubusercontent.com/assets/17190546/23258454/56db7a8c-f9ee-11e6-8aa4-a8120eb09dce.png)
 Getting the same problem. Tried everything. still stuck.

**Comment by colender** [comment]
Did you try to add the $(inherited) flag in Framework Search Paths and Library Search Paths.

**Comment by vanshikakapoor** [comment]
yes! I did

**Comment by vanshikakapoor** [comment]
![screen shot 2017-02-24 at 2 48 20 pm](https://cloud.githubusercontent.com/assets/17190546/23297662/587a7232-faa0-11e6-854f-9492c4b42b1a.png)
I am getting this error now. Any help

**Comment by colender** [comment]
Make sure you add it also on other linker files because it looks like it isn't added

**Comment by colender** [comment]
Bitcode has to be switched to no

**Comment by vanshikakapoor** [comment]
Added As well.. 
![screen shot 2017-02-24 at 2 51 11 pm](https://cloud.githubusercontent.com/assets/17190546/23297757/bf8841d4-faa0-11e6-8d99-214f969922c3.png)

**Comment by colender** [comment]
You should expand it and add it there too. You should a path to your game after adding it

**Comment by vanshikakapoor** [comment]
if I make Bitcode "No". I get following errors.

**Comment by marcosrampinelli** [comment]
I downloaded Google Sign-In SDK for iOS and put the GoogleSignIn.framework manually in Framework folder on Xcode and worked very well. Here's the link https://developers.google.com/identity/sign-in/ios/sdk/

**Comment by aammfii** [comment]
![screen shot 2017-03-02 at 11 51 49 pm](https://cloud.githubusercontent.com/assets/23666774/23522191/e1671584-ffa3-11e6-8a4b-4d1e889f78d4.png)
Eror limit exceeded
show first 200 eror only
200 eror occurs when i build project on ios tell me what can i do beacuse i am stuck on it.

**Comment by colender** [comment]
@aammfii Did you build it using Pods, Also did you make sure you have the current version of the SDK

**Comment by aammfii** [comment]
yes i am using pods files

**Comment by aammfii** [comment]
@colender  tell me solution.

**Comment by atotheroh** [comment]
For the record, @colender mentioned many places where he added the $(inherited) flag.  I wanted to know which place was the one actually fixing the issue.  For me, just adding `$(inherited)` to `Header Search Paths` fixed the issue.  This makes sense since the original error message is complaining about how it cannot find `GoogleSignIn/GIDSignIn.h`, a header file.

**Comment by aammfii** [comment]
@atotheroh   $(inherited)  just added in search path now get GoogleSignIn/GIDSignIn.h file not found

**Comment by DerBernie** [comment]
Thank you all, that's a really helpful guide! Just in case someone made the same mistake like me: check which run configuration is selected. I fixed everything in "Debug" and "Release", but xcode was actually (per default) set to "ReleaseForRunning".

**Comment by asmCode** [comment]
Here is the simplest and the fastes solution:

1. Select those 2 files in unity
<img width="242" alt="screen shot 2017-06-05 at 1 38 02 am" src="https://cloud.githubusercontent.com/assets/1872774/26776814/adc56858-498f-11e7-9e0f-2bfa948120c7.png">

2. Exclude them from the iOS
<img width="477" alt="screen shot 2017-06-05 at 1 38 06 am" src="https://cloud.githubusercontent.com/assets/1872774/26776817/afa273c8-498f-11e7-80b5-e528cae4064b.png">

3. Profit
