### ISSUE TITLE
Getting list of installed android packages

### ISSUE THREAD

**Issue by Aldian1** [playgameservices/play-games-plugin-for-unity#1529]
Window consistently pops up every time the project compiles

**Comment by claywilkinson** [comment]
Which window are you referring to?  Can you describe your issue a little more completely?

**Comment by lb4business** [comment]
Have same issue. Unity 5.5
Screens below. It recursivly checking and installing android packages, then retrieving licenses, then asking if i agree with license agreement. Then it starts again.
This windows appears on every compile and every Play button pressing in editor.
![scr2](https://cloud.githubusercontent.com/assets/5908603/21434849/5d5c6182-c898-11e6-9aa9-75a6e94fc964.png)
![scr3](https://cloud.githubusercontent.com/assets/5908603/21434851/5d5f8218-c898-11e6-8abb-b81c94239ad1.png)
![scr1](https://cloud.githubusercontent.com/assets/5908603/21434850/5d5d1b68-c898-11e6-8e3c-56160feb5a19.png)

**Comment by claywilkinson** [comment]
It sounds like there is a problem updating the Android SDK.  Do you accept the license agreements?
Is there any errors listed in the window?  Can you try updating it manually from Window > Google Play Games > Downloads > Google Play Games SDK.

You can also turn off the automatic resolution of the required client jars from Assets > Play Services Resolver > Settings

**Comment by lb4business** [comment]
Yes, i press accept, after it there is Retrieving licenses and installing Android SDK packages. For some reason it it istalling only Google Repository revision 41
I updated it via Android SDK Manager and problem seems to be solved.
@claywilkinson thank you!

**Comment by claywilkinson** [comment]
Glad you got it resolved!
