### ISSUE TITLE
Question on room setuping up

### ISSUE THREAD

**Issue by tsoiisaiah** [playgameservices/play-games-plugin-for-unity#153]
HI, i am trying out this awesome plugin with a really simple 1 vs 1 game,
and i got some problems and hope someone could help me out, Thanks!

public void OnRoomSetupProgress(float percent) {
	Debug.Log ("room setting up..." + percent + "%");
}

1) the percent before opponent join is all the way 20%, is that correct?

2) everything work great with wifi connection on both device, but if both of them use a 3G connection, it may have a chance that the room is never setup and the percent is all the way 20%
what should i do to make it work better with a 3G or slow connection?

Thanks a lot!

Isaiah

**Comment by claywilkinson** [comment]
@tsoiisaiah  - thanks for the question.  I am closing this issue right now for a couple reasons.  First, the plugin has been re-implemented in version 0.9.11 which changed how the the multi-player game setup behaves.  And second, the questions about performance and things are better suited to StackOverflow, so you will reach a wider audience with broader experience.

Please re-open this issue if you are still having this issue on the latest version of the plugin.  Thanks!
