### ISSUE TITLE
Google Play Games menu is not available

### ISSUE THREAD

**Issue by nagyv** [playgameservices/play-games-plugin-for-unity#1535]
Hi,

I've just installed the plugin under Unity Version 5.5.0xp1Linux (59c25c92588f) Personal (yes, it's the beta linux version), and can not find the Google Play Games menu. I've looked already all-round.

There are two compilation errors in the console:
    Assets/GooglePlayGames/Platforms/Android/Gms/Games/Stats/LoadPlayerStatsResultObject.cs(28,100): error CS1721: `Com.Google.Android.Gms.Games.Stats.Stats_LoadPlayerStatsResultObject': Classes cannot have multiple base classes (`JavaObjWrapper' and `Result')

    Assets/GooglePlayGames/Platforms/Android/Gms/Games/Stats/Stats.cs(30,52): error CS0527: Type `Result' in interface list is not an interface

Do you have any ideas what the problem might be?

**Comment by nagyv** [comment]
When I installed the plugin parts one by one, then (not surprisingly) I've managed to get to a point when the menus were working, but still had some less annoying console errors. When I installed the "Platforms" folder of the package, where the above files are shown, then everything stopped to work.

Right now, I'm convinced that this is a basic compilation error, but don't know why it might happen. Could it be related to Linux's Mono I have?

I'm running the above on Ubuntu 16.04 with pretty basic settings.

**Comment by nagyv** [comment]
I've realised that for some reason the "Result" interface is not recognised as an interface, but as a class, but don't know how to debug it as I'm a C# newbie.

I've managed to get it working by modifying some generated codes. Changing the pure `Result` references to  `Com.Google.Android.Gms.Common.Api.Result` solved the issue. But obviously, this is not a fix. :(

**Comment by claywilkinson** [comment]
This sounds like some C# bugs in Unity.  I have not tried the linux version, but can you change the Android player settings to use mono or IL2CPP?  Do you get the same result with each engine?

Please share a Pull request when you get it working.  If it helps, we can create a separate Linux branch if your not completely happy with the hacks for Linux.

**Comment by nagyv** [comment]
I can change the "scripting backend" under the "other settings" of "player settings". The two possible choices are Mono2.x and IL2CPP. IL2CPP gives the same error.

**Comment by timendez** [comment]
I have this same issue using OSX El Capitan for Unity 5.6.1f1

**Comment by timendez** [comment]
@claywilkinson can you please link me to the resolving PR? I'm curious as to the fix, thanks

**Comment by claywilkinson** [comment]
https://github.com/playgameservices/play-games-plugin-for-unity/commit/b9724e1ee868959a87b316fc97e7d1e807aa0e1b

I use the linux beta of Unity 2017.3 and I have tested  on OSx Sierra with Unity 5.4.1.f1

**Comment by timendez** [comment]
@claywilkinson thanks! 👍
