### ISSUE TITLE
Whatever i send real-time or turnbased invitation the invitated client get invitation with Invitation.InvType.TurnBased

### ISSUE THREAD

**Issue by BuKuSiShen** [playgameservices/play-games-plugin-for-unity#1537]
Below is my code, the invitation.InvitationType always be Invitation.InvType.TurnBased
//要先满足回合制才处理
		if (invitation.InvitationType == Invitation.InvType.RealTime) {
			Debug.Log ("实时游戏");
			// wrong type of invitation!
			return;
		} else if(invitation.InvitationType == Invitation.InvType.TurnBased)
		{
			Debug.Log ("回合制游戏");
		}

**Comment by BuKuSiShen** [comment]
Can't distinguish the match is Real-Time or Turn-based when receive invitation.Need help,thanks!

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
