### ISSUE TITLE
Fatal error on Linux

### ISSUE THREAD

**Issue by idarous** [playgameservices/play-games-plugin-for-unity#1538]
Hi,

I tried this plugin either on Linux and on Windows with Unity3d 5.5, java 1.8.0_111. On Windows it seems to work fine but on Linux after importing this plugin on Unity3d I get this error popup.

![capture du 2016-12-30 21 32 38](https://cloud.githubusercontent.com/assets/15747854/21572298/be3e115e-ced7-11e6-9883-9b65807dd9b4.png)

Does this plugin has been tested on Linux ?

Any idea about the problem ?

**Comment by claywilkinson** [comment]
I've tested this plugin successfully on Linux 2017.3.0f1
