### ISSUE TITLE
Invitation is not sent using turn based multiplayer

### ISSUE THREAD

**Issue by RamGul** [playgameservices/play-games-plugin-for-unity#1539]
I call CreateWithInvitationScreen...Invitation Screen comes on testing device I select 2nd player to send invitation. ..On Debug it shows 2 participants..P_1, and P_2..but for p_2 it shows not invited yet...and no notification appears on player 2 device..Although I have submit my turn usinh TakeTurn()..I have implemented AcceptFromInbox() ...It shows Your turn has started...Is it right to show ? Or it should show Ur Turn finished? How to finish my Turn..? As i know invitation will appear after my turn submission..? Where is issue Kindly guide me..?

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
