### ISSUE TITLE
disable IOS support

### ISSUE THREAD

**Issue by FrankDaze** [playgameservices/play-games-plugin-for-unity#1540]
Is it possible to disable IOS support for export etc.? Because under IOS I'm using the IOS Game Center.

**Comment by claywilkinson** [comment]
Yes, you can define the constant NO_GPGS in the ios player settings in Unity, and that will exclude all the GPGS code. See the [README](https://github.com/playgameservices/play-games-plugin-for-unity#excluding-all-google-play-game-services-when-building-for-ios) for more info.
