### ISSUE TITLE
Google Plus and Server Auth Code issues

### ISSUE THREAD

**Issue by brianjkd** [playgameservices/play-games-plugin-for-unity#1541]
I would like to use this plugin to handle sign on for an android app.  I will need an id token or auth code which I can use on my backend server. I have two issues. When I authenticate with this plugin I get the googleId as the id which looks something like g0123456789123456 which is great. Then, I ask for and get the id token. When I verify the token at https://www.googleapis.com/oauth2/v2/tokeninfo?id_token= the id I get back is the deprecated google plus id, not the googleId which I get from authenticating. Anyone know why this is?

My second issue is I am unable to get the server auth code without enabling the Google Plus API even though I am not using any of the Google Plus APIs in my developer console for this project. As soon as I enable that checkbox in this plugin, I am able to get the server auth code.

Here is a log from me trying to get auth code. I authenticate first, get the googleId, and then call a repeating co routine that attempts to get the auth code.

```
(Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-02 11:26:52.907 19907-19924/? I/Unity: Trying to get server auth code.
                                           
                                          (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-02 11:26:52.923 19907-19924/? I/Unity:  [Play Games Plugin DLL] 01/02/17 11:26:52 -05:00 DEBUG: Entering internal callback for GameServices#InternalFetchServerAuthCodeCallback
                                           
                                          (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-02 11:26:52.924 19907-19924/? W/Unity: *** [Play Games Plugin DLL] 01/02/17 11:26:52 -05:00 ERROR: Error loading server auth code: ERROR_NOT_AUTHORIZED
                                           
                                          (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-02 11:26:52.925 19907-19924/? I/Unity: Error authStatus: AuthApiAccessForbiddenCode: 
                                           
                                          (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-02 11:26:53.610 19907-19924/? I/Unity:  [Play Games Plugin DLL] 01/02/17 11:26:53 -05:00 DEBUG: Starting Auth Transition. Op: SIGN_OUT status: ERROR_NOT_AUTHORIZED
                                           
                                          (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-02 11:26:53.611 19907-19924/? I/Unity:  [Play Games Plugin DLL] 01/02/17 11:26:53 -05:00 DEBUG: Entering internal callback for GameServices#InternalFetchServerAuthCodeCallback
                                           
                                          (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-02 11:26:53.611 19907-19924/? W/Unity: *** [Play Games Plugin DLL] 01/02/17 11:26:53 -05:00 ERROR: Error loading server auth code: ERROR_NOT_AUTHORIZED
                                           
                                          (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-02 11:26:53.612 19907-19924/? I/Unity: Error authStatus: AuthApiAccessForbiddenCode: 
                                           
                                          (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-02 11:26:54.951 19907-19924/? I/Unity: -72.47722 41.75946
                                           
                                          (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-02 11:26:57.911 19907-19924/? I/Unity: Trying to get server auth code.
                                           
                                          (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-02 11:26:57.912 19907-19924/? I/Unity: Error authStatus: SignInRequiredCode: 
                                           
                                          (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-02 11:26:57.926 19907-19924/? W/Unity: *** [Play Games Plugin DLL] 01/02/17 11:26:57 -05:00 ERROR: GetServerAuthCode can only be called after authentication.
```

Thank you for any help.

**Comment by MarcoWilliamsPF** [comment]
+1 having the same issue

**Comment by claywilkinson** [comment]
I just tried with the SmokeTest sample, and did not require GooglePlus and I was able to get an authcode, and exchange it for an access token on the server backend.

Did you set the web client ID in the setup dialog?  This needs to be the client ID of the web app that is associated with your game in the Play Developer Console.

**Comment by brianjkd** [comment]
I did set the web client ID in the setup dialog to the web client ID I created in the Google Developer Console. However, in my Play Developer Console, I have linked the Android app, not the web app. In the Google Developer Console, my project has the Android client IDs ( signed and unsigned) and a web client ID. Should I link the web client ID instead of or in addition to the Android app in the Play Developer Console? Thanks for your help!

**Comment by claywilkinson** [comment]
Yes, you need to associate the web app with the game in addition to the android app.  Then use the client id of the web app when you call getServerAuthCode.

**Comment by brianjkd** [comment]
Thank you, that clears up a lot!

**Comment by claywilkinson** [comment]
You're welcome!

**Comment by djock** [comment]
Hey, I'm having @brianjkd second issue but I already have the Web Client ID ( created in https://console.cloud.google.com ) added to my Android Setup and still can't get the server auth code without activating Google+ API.

`
 15:19:28.224 18201-18229/com.company.product W/Unity: TRY G CONNECT SocialAuthenticate
 15:19:28.253 18201-18229/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:28 +03:00 DEBUG: Activating PlayGamesPlatform.                         
 15:19:28.279 18201-18229/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:28 +03:00 DEBUG: Instance was not initialized, using default configuration. 
 15:19:28.322 18201-18229/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:28 +03:00 DEBUG: Creating platform-specific Play Games client.                     
 15:19:28.339 18201-18229/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:28 +03:00 DEBUG: Creating Android IPlayGamesClient Client                       
 15:19:28.445 18201-18229/com.company.product D/GamesUnitySDK: Performing Android initialization of the GPG SDK
 15:19:28.672 18201-18229/com.company.product I/Unity: Building GPG services, implicitly attempts silent auth
 15:19:28.938 18201-18229/com.company.product W/PopupManager: You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
 15:19:29.012 18201-19488/com.company.product I/GamesNativeSDK: Auth operation started: SIGN IN
 15:19:29.012 18201-19488/com.company.product I/GamesNativeSDK: Connecting to Google Play...
 15:19:29.476 18201-18201/com.company.product V/GamesNativeSDK: Play Games callback indicates connection failure.
 15:19:29.476 18201-19488/com.company.product I/GamesNativeSDK: UI interaction required to connect to Google Play.
 15:19:29.532 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:29 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
 15:19:29.537 18201-19517/com.company.product I/Unity: Invoking callbacks, AuthState changed from silentPending to Unauthenticated.                 
 15:19:29.546 18201-19517/com.company.product I/Unity: there are pending auth callbacks - starting AuthUI     
 15:19:29.546 18201-19488/com.company.product I/GamesNativeSDK: Auth operation started: SIGN IN
 15:19:29.546 18201-19488/com.company.product I/GamesNativeSDK: Connecting to Google Play...
 15:19:29.602 18201-18201/com.company.product V/GamesNativeSDK: Play Games callback indicates connection failure.
 15:19:29.602 18201-19488/com.company.product I/GamesNativeSDK: UI interaction required to connect to Google Play.
 15:19:29.602 18201-19488/com.company.product I/GamesNativeSDK: Resolving connection.
 15:19:29.780 18201-18229/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:29 +03:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
 15:19:42.596 18201-18201/com.company.product V/GamesNativeSDK: Received Activity Resume Event.
 15:19:42.979 18201-18229/com.company.product I/Unity: --------------->>>>> application PAUSE BEFORE
 15:19:43.070 18201-18201/com.company.product V/GamesNativeSDK: Play Games callback indicates connection.
 15:19:43.110 18201-19488/com.company.product I/GamesNativeSDK: Successfully connected to Google Play.
 15:19:43.119 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:43 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID      
 15:19:43.195 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:43 +03:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback        
 15:19:43.218 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:43 +03:00 DEBUG: Populating User                               
 15:19:43.287 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:43 +03:00 DEBUG: Found User: [Player: 'xxxxxx' (id xxxxxxxx)]
 15:19:43.300 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:43 +03:00 DEBUG: Maybe finish for User                                      
 15:19:43.312 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:43 +03:00 DEBUG: Auth not finished. User=[Player: 'xxxxxx' (id xxxxxxxx)] achievements=                 
 15:19:44.713 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:44 +03:00 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback
 15:19:44.745 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:44 +03:00 DEBUG: Populating Achievements, status = VALID              
 15:19:44.843 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:44 +03:00 DEBUG: Found 10 Achievements                                     
 15:19:44.855 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:44 +03:00 DEBUG: Maybe finish for Achievements                                          
 15:19:44.866 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:44 +03:00 DEBUG: Auth finished. Proceeding.
 15:19:45.085 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:44 +03:00 DEBUG: Invoking Callbacks: System.Action`1[System.Boolean]                                              
 15:19:45.123 18201-18229/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:19:45 +03:00 DEBUG: Invoking user callback on game thread                        
 15:19:45.160 18201-18229/com.company.product I/Unity: <color=grey>[»]</color> [GPGS] Social Authenticate
 15:19:45.786 18201-18201/com.company.product I/GamesNativeSDK: Auth operation started: SIGN OUT
 15:19:45.786 18201-18201/com.company.product E/GamesNativeSDK: Out of box error detected; the user must reauthenticate through the UIflow.
 15:19:50.382 18201-19488/com.company.product V/GamesNativeSDK: Detaching from JVM on thread main_dispatch
 15:20:00.905 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:20:00 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_OUT status: ERROR_NOT_AUTHORIZED 
 15:20:00.919 18201-19517/com.company.product I/Unity:  [Play Games Plugin DLL] 04/28/17 15:20:00 +03:00 DEBUG: Entering internal callback for GameServices#InternalFetchServerAuthCodeCallback
 15:20:00.990 18201-19517/com.company.product W/Unity: *** [Play Games Plugin DLL] 04/28/17 15:20:00 +03:00 ERROR: Error loading server auth code: ERROR_NOT_AUTHORIZED          
 15:20:01.015 18201-18229/com.company.product E/Unity: Cant get Google Play token`

Still can't figure out what's wrong in my setup.

**Comment by claywilkinson** [comment]
@djock - It looks like you are using an old version of the plugin.  Can you update to the latest?  It addresses a lot of issues around getting auth codes correctly.  Also, I think your issue is different from this one, can you open a new one just so we're not confusing a closed thread?

**Comment by djock** [comment]
@claywilkinson Yes, sorry. I've opened a [new one](https://github.com/playgameservices/play-games-plugin-for-unity/issues/1732):
