### ISSUE TITLE
PlayGamesPlatform.Instance.RealTime.CreateWithInvitationScreen Fails when create realtime match many times

### ISSUE THREAD

**Issue by BuKuSiShen** [playgameservices/play-games-plugin-for-unity#1542]
when i create realTime Match many times, the creating fails with error about Enteringstate:ShutdownState.
![0cff100d-a32e-4abb-9c92-83bb17fdb102](https://cloud.githubusercontent.com/assets/12295354/21598783/8d057834-d19d-11e6-99ba-02867c79fa52.png)

**Comment by BuKuSiShen** [comment]
I found one device has limit invitation times one day.I'm not sure.

**Comment by claywilkinson** [comment]
I believe that message is just a side effect of initializing the room.  When the room is created, it is in "shutdown", then as the callbacks are called, the room is moved to different states.

Can you share more of the log?

**Comment by BuKuSiShen** [comment]
@claywilkinson The log is above.The issue happens only when after one device create real-time room many times.

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
