### ISSUE TITLE
Google analytics 3.0.4 Is not working in latest Ti Sdk 6.0.0

### ISSUE THREAD

**Issue by rahugoyal** [playgameservices/play-games-plugin-for-unity#1543]
Version Details are below - 

Appcelerator studio  version - 4.8.0.201611121409
Titanium Sdk version- 6.0.0
Appcelerator CLI version - 6.0.0
Node js version - 6.9.2
Mac  os version - 10.12.2

Google analytics module , I have downloaded from Gittio 

Google analytics version - 3.0.4

May be some methods and classes are missing.
If anybody have some ideas regarding this google analytics things.

Please help us.

Thanks in advance.

**Comment by rahugoyal** [comment]
Please suggest me if anybody have some knowledge.

**Comment by claywilkinson** [comment]
I think your issue would be more appropriate for the plugins you are having problems with.  This is for the Google Play Game Services plugin for Unity - which I don't see in your list.
