### ISSUE TITLE
CommandInvokationFailure: Unable to convert classes into dex format. with GPG 0.9.36 and admob v3.1.3

### ISSUE THREAD

**Issue by GabLeRoux** [playgameservices/play-games-plugin-for-unity#1546]
Using [Google Mobile Ads Unity Plugin v3.1.3](https://github.com/googleads/googleads-mobile-unity/releases/tag/3.1.3) and [GooglePlayGamesPlugin-0.9.36](https://github.com/playgameservices/play-games-plugin-for-unity/blob/ebfd0424cad376b20aeaf612c83a241aa814f17d/current-build/GooglePlayGamesPlugin-0.9.36.unitypackage). Having troubles with aar files again.

```
CommandInvokationFailure: Unable to convert classes into dex format.
/usr/lib/jvm/java-8-openjdk/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/home/gableroux/Android/Sdk/tools" -Dfile.encoding=UTF8 -jar "/opt/Unity/Editor/Data/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqv;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqw;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqx;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqy;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzqz;
5 errors; aborting
]
```

Unity version `5.5.0xp1Linux`

I tired matching versions in 
`Assets/GooglePlayGames/PluginVersion.cs:46`
    
    public const string PlayServicesVersionConstraint = "9+";

and
 `Assets/GoogleMobileAds/Editor/AdMobDependencies.cs:46`

    "9+" },

Deleted `Assets/Plugins/Android/play-services-*aar*` to download them again. Always the same issue.

Similar to https://github.com/playgameservices/play-games-plugin-for-unity/issues/1301#issuecomment-238339372

Everytime I upgrade Play games services and or google admob (due to a unity upgrade) I get troubles with these aar files :(

**Comment by GabLeRoux** [comment]
I just tried in an empty project and wasn't able to reproduce so problem is probably with an other file laying around.
Side note: I had to delete `Assets/PlayServicesResolver/Editor/Google.VersionHandler_v1.2.6.0.dll` and accepted a few popups but I managed to create a build in empty project.

**Comment by vanshikakapoor** [comment]
Below is my log:-

After adding google play and updating SDK, everything stop working.


CommandInvokationFailure: Failed to re-package resources.
/Users/vanshika/Documents/androidSDK/build-tools/25.0.2/aapt package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "/Users/vanshika/Documents/androidSDK/platforms/android-25/android.jar" -F bin/resources.ap_ --extra-packages com.chartboost.sdk.unity:com.google.unity:com.google.example.games.mainlibproj:com.facebook:com.facebook.android:com.google.android.gms.auth.api:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.tasks:android.support.v4 -S "/Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res" -S "/Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-wrapper-release/res" -S "/Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/play-services-auth-10.0.1/res" -S "/Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/play-services-auth-base-10.0.1/res" -S "/Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/play-services-base-10.0.1/res" -S "/Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/play-services-basement-10.0.1/res" -S "/Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/play-services-drive-10.0.1/res" -S "/Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/play-services-games-10.0.1/res" -S "/Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/play-services-nearby-10.0.1/res" -S "/Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/play-services-tasks-10.0.1/res" -S "/Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/support-v4-24.0.0/res"

stderr[
AndroidManifest.xml:30: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.IAPTheme').

]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: /Users/vanshika/Documents/androidSDK/platforms/android-25/android.jar
applyFileOverlay for drawable
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_icon_light.xml
trying overlaySet Key=common_google_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_focused.xml
trying overlaySet Key=common_google_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_focused.xml
trying overlaySet Key=common_google_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_google_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_light_focused.xml
trying overlaySet Key=common_google_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_light_pressed.9.png
trying overlaySet Key=com_facebook_button_background.xml
trying overlaySet Key=com_facebook_button_icon.png
trying overlaySet Key=com_facebook_button_like_background.xml
trying overlaySet Key=com_facebook_button_like_icon_selected.png
trying overlaySet Key=com_facebook_button_login_silver_background.xml
trying overlaySet Key=com_facebook_button_send_background.xml
trying overlaySet Key=com_facebook_button_send_icon.png
trying overlaySet Key=com_facebook_close.png
trying overlaySet Key=com_facebook_profile_picture_blank_portrait.png
trying overlaySet Key=com_facebook_profile_picture_blank_square.png
trying overlaySet Key=com_facebook_tooltip_black_background.9.png
trying overlaySet Key=com_facebook_tooltip_black_bottomnub.png
trying overlaySet Key=com_facebook_tooltip_black_topnub.png
trying overlaySet Key=com_facebook_tooltip_black_xout.png
trying overlaySet Key=com_facebook_tooltip_blue_background.9.png
trying overlaySet Key=com_facebook_tooltip_blue_bottomnub.png
trying overlaySet Key=com_facebook_tooltip_blue_topnub.png
trying overlaySet Key=com_facebook_tooltip_blue_xout.png
trying overlaySet Key=messenger_bubble_large_blue.png
trying overlaySet Key=messenger_bubble_large_white.png
trying overlaySet Key=messenger_bubble_small_blue.png
trying overlaySet Key=messenger_bubble_small_white.png
trying overlaySet Key=messenger_button_blue_bg_round.xml
trying overlaySet Key=messenger_button_blue_bg_selector.xml
trying overlaySet Key=messenger_button_send_round_shadow.png
trying overlaySet Key=messenger_button_white_bg_round.xml
trying overlaySet Key=messenger_button_white_bg_selector.xml
trying overlaySet Key=app_banner.png
trying overlaySet Key=app_icon.png
applyFileOverlay for layout
trying overlaySet Key=com_facebook_activity_layout.xml
trying overlaySet Key=com_facebook_login_fragment.xml
trying overlaySet Key=com_facebook_tooltip_bubble.xml
trying overlaySet Key=messenger_button_send_blue_large.xml
trying overlaySet Key=messenger_button_send_blue_round.xml
trying overlaySet Key=messenger_button_send_blue_small.xml
trying overlaySet Key=messenger_button_send_white_large.xml
trying overlaySet Key=messenger_button_send_white_round.xml
trying overlaySet Key=messenger_button_send_white_small.xml
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_light.xml
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res/drawable-xhdpi/app_banner.png
Processing image: res/drawable-mdpi/app_icon.png
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_button_icon.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_button_icon.png: 161% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-hdpi/com_facebook_button_icon.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-hdpi/com_facebook_button_icon.png: 157% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xhdpi/com_facebook_button_icon.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xhdpi/com_facebook_button_icon.png: 162% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xxhdpi/com_facebook_button_icon.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xxhdpi/com_facebook_button_icon.png: 157% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_button_like_icon_selected.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_button_like_icon_selected.png: 147% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-hdpi/com_facebook_button_like_icon_selected.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-hdpi/com_facebook_button_like_icon_selected.png: 132% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xhdpi/com_facebook_button_like_icon_selected.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xhdpi/com_facebook_button_like_icon_selected.png: 125% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xxhdpi/com_facebook_button_like_icon_selected.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xxhdpi/com_facebook_button_like_icon_selected.png: 114% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_button_send_icon.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_button_send_icon.png: 75% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-hdpi/com_facebook_button_send_icon.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-hdpi/com_facebook_button_send_icon.png: 136% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xhdpi/com_facebook_button_send_icon.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xhdpi/com_facebook_button_send_icon.png: 128% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xxhdpi/com_facebook_button_send_icon.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xxhdpi/com_facebook_button_send_icon.png: 109% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_close.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_close.png: 118% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-hdpi/com_facebook_close.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-hdpi/com_facebook_close.png: 106% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xhdpi/com_facebook_close.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xhdpi/com_facebook_close.png: 128% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_profile_picture_blank_portrait.png
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_profile_picture_blank_square.png
    (processed image res/drawable-mdpi/app_icon.png: 90% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_tooltip_black_background.9.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_profile_picture_blank_square.png: 109% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-hdpi/com_facebook_tooltip_black_background.9.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_profile_picture_blank_portrait.png: 109% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xhdpi/com_facebook_tooltip_black_background.9.png
    (processed image res/drawable-xhdpi/app_banner.png: 93% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_tooltip_black_bottomnub.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_tooltip_black_bottomnub.png: 160% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-hdpi/com_facebook_tooltip_black_bottomnub.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-hdpi/com_facebook_tooltip_black_bottomnub.png: 172% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xhdpi/com_facebook_tooltip_black_bottomnub.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xhdpi/com_facebook_tooltip_black_bottomnub.png: 167% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_tooltip_black_topnub.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_tooltip_black_topnub.png: 130% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-hdpi/com_facebook_tooltip_black_topnub.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-hdpi/com_facebook_tooltip_black_topnub.png: 133% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xhdpi/com_facebook_tooltip_black_topnub.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-xhdpi/com_facebook_tooltip_black_topnub.png: 137% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_tooltip_black_xout.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-mdpi/com_facebook_tooltip_black_xout.png: 101% size of source)
Processing image: /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/facebook-android-sdk-4.6.0/res/drawable-hdpi/com_facebook_tooltip_black_xout.png
    (processed image /Users/vanshika/Documents/fishing-game/Temp/StagingArea/android-libraries/fa<message truncated>

**Comment by HasnLal** [comment]
Fuck you dumb google mobile ad developers, overdoing things every-fucking-time. (just came here to say this)
