### ISSUE TITLE
doesn't work with unity purchase

### ISSUE THREAD

**Issue by Honikou** [playgameservices/play-games-plugin-for-unity#1547]
Hi,

There is a conflict with GoogleAIDL who is from unity purchase. 

CommandInvokationFailure: Unable to convert classes into dex format.
C:/Program Files/Java/jdk1.8.0_77\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="E:/androidSDK\tools" -Dfile.encoding=UTF8 -jar "C:\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/games/bridge/BuildConfig;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/games/bridge/NativeBridgeActivity;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/games/bridge/TokenFragment;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/games/bridge/TokenFragment$1;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/games/bridge/TokenFragment$TokenRequest;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/games/bridge/TokenPendingResult;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/games/bridge/TokenResult;
7 errors; aborting
]
stdout[
processing archive C:\Jeux\Fight Kub\Temp\StagingArea\android-libraries\GoogleAIDL\libs\.\classes.jar...

**Comment by claywilkinson** [comment]
This looks like you have two copies of the play-games-plugin-support.jar - Look in Assets/Plugins/Android/MainLibProj/libs

**Comment by Suvitruf** [comment]
Had similar issue with 0.9.50.

I've renamed package name in **Assets\Plugins\Android\com.google.games.gpgs-plugin-support-0.9.50\AndroidManifest.xml**

So, this file now looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.google.games.bridge.app"
    android:versionCode="1"
    android:versionName="0.9.50" >
```

The problem disappeared.
