### ISSUE TITLE
Xcode Build Error 'GoogleSignIn/GIDSignIn.h' file not found

### ISSUE THREAD

**Issue by st0326s** [playgameservices/play-games-plugin-for-unity#1549]
With the implementation of the GameCenter function,
When setting up GoogleGameService on the Android side,
I am troubled because I can not build Xcode of iOS.
Please tell me if you have some knowledge.

■ What I tried
　● Android side
　· Implemented and tested GameCenter function
　URL of plugin used
　https://github.com/playgameserv.../play-games-plugin-for-unity
　● iOS side
　· Editor extension Window -> GooglePlayGames -> Setup -> iOS Setup
　· Confirm SetUp success dialog
　· Download the Google Sign-In iOS SDK
　Add GoogleSignIn.framework and GoogleSignIn.bundle

■ Error contents
Libraries/Plugins/iOS/GPGSAppController.mm: 20: 9: 'GoogleSignIn / GIDSignIn.h' file not found

■ Environment
Unity 5.4.3 p 2
Xcode 8.1
OSX10.11.6

**Comment by VivekDeshpande** [comment]
Am having the exact same problem. I tried removing GPGSAppController.mm from compile sources (since I am not using it for my iOS build) but that just leads to more errors during compilation.

Is there any way to exclude this plugin for iOS builds (without removing the plugin from project).

**Comment by claywilkinson** [comment]
you can specify NO_GPGS in the ios player settings in Unity. Add it to Scripting define symbols in the other settings section.  More info: https://github.com/playgameservices/play-games-plugin-for-unity#excluding-all-google-play-game-services-when-building-for-ios

There are some manual steps to build for iOS:
1. Make sure you are using the latest version of the plugin (0.9.36) - It has some important fixes.
2. Follow the instructions to use CocoaPods to build: https://github.com/playgameservices/play-games-plugin-for-unity#building-for-ios
