### ISSUE TITLE
Error when LoadState() is called

### ISSUE THREAD

**Issue by sanmn19** [playgameservices/play-games-plugin-for-unity#155]
In my game, I successfully sign in and then call  PlayGamesPlatform.Instance.LoadState(0, this); This causes the game to crash. So, I enabled debug and went through the logs but could not think of a solution. Is this a bug or am I doing something wrong?

Error Log:
I/Unity   (10264): [Play Games Plugin DLL] Creating platform-specific Play Games client.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] Making sure PlayGamesHelperObject is ready.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] Initializing Android Client.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] Creating GameHelperManager to manage GameHelper.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] Setting up GameHelperManager.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] GHM creating GameHelper.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] PlayGamesHelperObject created.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AUTH: starting auth process, silent=False
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] GHM calling GameHelper constructor with flags=7
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] GHM setting up GameHelper.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] GHM Setting GameHelper options.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] GHM calling GameHelper.setup
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] GHM: GameHelper setup done.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] GHM Setting up lifecycle.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] GHM calling GameHelper.onStart to try initial auth.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): Loading Data: Not yet signed in
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] PlayGamesHelperObject.OnApplicationFocus True
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AUTH: connection in progress; auth now pending.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] GHM/GameHelperListener got onSignInSucceeded, origin 1000, notifying GHM.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] GHM got onSignInSucceeded, origin 1000, notifying AndroidClient.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AndroidClient got OnSignInSucceeded.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] Attempting to retrieve player info.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] Player ID: xxxxxxxxxxxxxxxxxxxxx
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] Player display name: xxxxxxx xxxxxxxx
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AUTH: Auth succeeded. Proceeding to achievement loading.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AUTH: Now performing initial achievement load...
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AUTH: Initial achievement load call made.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] OnAchievementsLoadedResultProxy invoked
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL]     result=UnityEngine.AndroidJavaObject
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AUTH: Initial achievement load finished.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] Processing achievement buffer.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AchievementBank: processing achievement buffer given as Java object.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AchievementBank: buffer contains 2 achievements.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AchievementBank: processing achievement #0
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AchievementBank: processed: [Achievement] id=CgkIyfmY3ZYYEAIQAg, name=Signed in!, desc=Congrats! You just signed in!, type=STANDARD,  revealed=True, unlocked=True, steps=0/0
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AchievementBank: processing achievement #1
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AchievementBank: processed: [Achievement] id=CgkIyfmY3ZYYEAIQAQ, name=Partially Perfect Game!, desc=You have achieved 3 stars on 10 levels!, type=STANDARD,  revealed=True, unlocked=False, steps=0/0
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AchievementBank: bank now contains 2 entries.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] Closing achievement buffer.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AUTH: Auth process complete!
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AUTH: Calling auth callback: success=True
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AndroidClient: CheckInvitationFromNotification.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AndroidClient: looking for invitation in our GameHelper.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] GHM clearing invitation and turn-based match on GameHelper.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] No invitation in our GameHelper. Trying SignInHelperManager.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] No invitation in SignInHelperManager either.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] No match in our GameHelper. Trying SignInHelperManager.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] No match in SignInHelperManager either.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AndroidTbmpClient.OnSignInSucceeded
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] Querying for max match data size...
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] Max match data size: 131072
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): Signed In
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): Loading Data: Authenticating done with success: True
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): Loading data: Already Signed in for slot: 0
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): Loading state for slot: 0
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] AndroidClient.LoadState, slot=0
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] Requesting API call: load state slot=0
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] Connected! Calling API: load state slot=0
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): (Filename:  Line: -1)
I/Unity   (10264): [Play Games Plugin DLL] OnStateResultProxy.onResult, result=UnityEngine.AndroidJavaObject
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] OnStateResultProxy: status code is 0
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] OnstateResultProxy: retrieving result objects...
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] Got result objects.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] loadedResult = UnityEngine.AndroidJavaObject
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] conflictResult =
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): [Play Games Plugin DLL] OnStateResultProxy: processing normal load.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): ConvertByteArray.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10264): Calling java.lang.reflect.Array.getLength.
I/Unity   (10264): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)

**Comment by claywilkinson** [comment]
closing this thread since it is old and refers to app state API which is no longer supported in favor of SavedGames API.
