### ISSUE TITLE
Usage of Regex includes System.dll

### ISSUE THREAD

**Issue by lordcodes** [playgameservices/play-games-plugin-for-unity#1550]
There is a single usage of the Regex class within the library. This means any game that uses the play games package will have System.dll includes into it. This adds some bloat to the APK size.

From looking, there is only a single usage and so it seems like it could easily be written in a different way so that the Regex class wasn't needed.

It is in `NativeSavedGameClient`

```
private static readonly Regex ValidFilenameRegex = new Regex(@"\A[a-zA-Z0-9-._~]{1,100}\Z");

...

return ValidFilenameRegex.IsMatch(filename);
```

I am happy to have a look at this, but was just wondering what exactly this regular expression was needed for?

**Comment by claywilkinson** [comment]
It is used to validate the name passed in when using the SaveGameAPI.

I believe it is just checking that the file name is alphanumeric, period, dash, underscore and tilde with a length of 1-100  characters.  Which sounds like it could be converted.

Is this really the only place that would pull in system.dll?   That is amazing! (and a good find!)

**Comment by andrewlord1990** [comment]
Okay thanks. I will have a look at writing something to replace it.
