### ISSUE TITLE
Authentication succeed but plugin reports that it's failed.

### ISSUE THREAD

**Issue by AntonVasiliev** [playgameservices/play-games-plugin-for-unity#1551]
We have an issue with Google Play Games plugin for Unity on Android devices.
Plugin version: 0.9.36. Unity version: 5.4.3p2.

There is a case when Google Play Games authentication **succeed** but Google Play Games plugin for Unity **reports that authentication is failed**.

**Steps to reproduce:**
1. Make sure you have Google account signed in on device.
2. Run an app that uses Google Play Games plugin for Unity.
3. Make sure you are not logged in Google Play Games inside application.
4. Restart application.
5. Start log in process (make call to Social.localUser.Authenticate(callback))
6. When Native UI window appears (user selection window), don't do anything for 6 minutes.
7. Select your user.

**Expected results:**
User will be authenticated.

**What happens:**
Application will resume, but user will not be authenticated.

```
Log messages from unity log:
[Play Games Plugin DLL] 01/11/17 13:59:31 +03:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
[Play Games Plugin DLL] 01/11/17 13:59:31 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
[Play Games Plugin DLL] 01/11/17 13:59:31 +03:00 DEBUG: AuthState == Unauthenticated calling auth callbacks with failure
```

Now if we call Social.localUser.Authenticate(callback) we will be instantly authenticated (no native UI appears).

Log messages after this action:
```
[Play Games Plugin DLL] 01/11/17 13:52:23 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
[Play Games Plugin DLL] 01/11/17 13:52:23 +03:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback
[Play Games Plugin DLL] 01/11/17 13:52:23 +03:00 DEBUG: Populating User
[Play Games Plugin DLL] 01/11/17 13:52:23 +03:00 DEBUG: Found User: [Player: 'HappyCow10000u' (id g00000000000000000000)] // NOTE: id is hidden,
[Play Games Plugin DLL] 01/11/17 13:52:23 +03:00 DEBUG: Maybe finish for User
[Play Games Plugin DLL] 01/11/17 13:52:23 +03:00 DEBUG: Auth not finished. User=[Player: 'HappyCow10000u' (id g00000000000000000000)] achievements=
[Play Games Plugin DLL] 01/11/17 13:52:24 +03:00 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback
[Play Games Plugin DLL] 01/11/17 13:52:24 +03:00 DEBUG: Populating Achievements, status = VALID
[Play Games Plugin DLL] 01/11/17 13:52:24 +03:00 DEBUG: Found 31 Achievements
[Play Games Plugin DLL] 01/11/17 13:52:24 +03:00 DEBUG: Maybe finish for Achievements
[Play Games Plugin DLL] 01/11/17 13:52:24 +03:00 DEBUG: Auth finished. Proceeding.
[Play Games Plugin DLL] 01/11/17 13:52:24 +03:00 DEBUG: Invoking Callbacks: System.Action`2[System.Boolean,System.String]
[Play Games Plugin DLL] 01/11/17 13:52:24 +03:00 DEBUG: Invoking user callback on game thread
[Play Games Plugin DLL] 01/11/17 13:52:25 +03:00 DEBUG: Entering internal callback for GameServices#InternalFetchServerAuthCodeCallback
```

Our guess that the root of the problem is in the _Play Games Services for C++_ library but we have no idea how to report bug to this product maintainers.

--------------------

**Also, same incorrect behavior can be achieved with different steps:**
1. Make sure you have no Google account signed in on device.
2. Run an app that uses Google Play Games plugin for Unity.
3. Start log in process (make call to Social.localUser.Authenticate(callback))
4. When Native Ui window appears, choose "Create new account".
5. Spend more than 6 minutes creating new Google Account.
6. Finish registration in Play Games and proceed to game.

**Expected results:**
User will be authenticated.

**What happens:**
Application will resume, but user will not be authenticated.

**Comment by claywilkinson** [comment]
Thanks for the detailed report!  6 minutes is definitely and edge case beyond the  timeout for waiting for the user to be selected, so this is expected behavior.

**Comment by AntonVasiliev** [comment]
Thank you for your answer.

If you confirm that this is intended behavior, could you add to documentation that the only correct way of handling failed callback from Social.localUser.Authenticate() is to immediately try silent authentication, otherwise Google Play Games plugin for Unity and Play Games Services can be in different states (GPGS4U - not authenticated, GPGS - authenticated).

**Comment by selimcolakoglu** [comment]
Did you find the solution?

**Comment by DataGreed** [comment]
Same problem here
