### ISSUE TITLE
ERROR_NOT_AUTHORIZED for some users

### ISSUE THREAD

**Issue by DruidV1** [playgameservices/play-games-plugin-for-unity#1556]
I'm having this issue where I get ERROR_NOT_AUTHORIZED for some users when I call the code below. This is a production app and it works fine for some users, but not others for some reason.

`PlayGamesPlatform.Instance.Authenticate(CallBack, true); 

void CallBack (bool success)
{
	if (success)
	{
		AuthCallbackGoogle(true);
	}
	else
	{
		Social.localUser.Authenticate(AuthCallbackGoogle);
	}
}
`
The problem is that the callback is returning false. I found other topics on this and tried the following and had no change:
Confirmed my sha1 is set to the same one as my keystore
Tried removing .EnableSavedGames() from my config and adding it back. Is there a way to confirm that this is actually being turned off?

Here is the log:
`
I/Unity   (17841): Building GPG services, implicitly attempts silent auth
I/Unity   (17841):
I/Unity   (17841): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity   (17841):
I/Unity   (17841):  [Play Games Plugin DLL] 01/16/17 19:48:11 -08:00 DEBUG: Activating PlayGamesPlatform.
I/Unity   (17841):
I/Unity   (17841): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity   (17841):
I/Unity   (17841):  [Play Games Plugin DLL] 01/16/17 19:48:11 -08:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
I/Unity   (17841):
I/Unity   (17841): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity   (17841):
I/Unity   (17841):  [Play Games Plugin DLL] 01/16/17 19:48:11 -08:00 DEBUG: Creating platform-specific Play Games client.
I/Unity   (17841):
I/Unity   (17841): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity   (17841):
I/Unity   (17841):  [Play Games Plugin DLL] 01/16/17 19:48:11 -08:00 DEBUG: Creating Android IPlayGamesClient Client
I/Unity   (17841):
I/Unity   (17841): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity   (17841):
I/Unity   (17841):  [Play Games Plugin DLL] 01/16/17 19:48:14 -08:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   (17841):
I/Unity   (17841): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity   (17841):
I/Unity   (17841):  [Play Games Plugin DLL] 01/16/17 19:48:14 -08:00 DEBUG: Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
E/Unity   (17841):
E/Unity   (17841): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
E/Unity   (17841):
I/Unity   (17841):  [Play Games Plugin DLL] 01/16/17 19:48:14 -08:00 DEBUG: Invoking user callback on game thread
I/Unity   (17841):
I/Unity   (17841): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity   (17841):
I/Unity   (17841):  [Play Games Plugin DLL] 01/16/17 19:48:21 -08:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
I/Unity   (17841):
I/Unity   (17841): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity   (17841):
I/Unity   (17841):  [Play Games Plugin DLL] 01/16/17 19:48:26 -08:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   (17841):
I/Unity   (17841): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity   (17841):
I/Unity   (17841):  [Play Games Plugin DLL] 01/16/17 19:48:26 -08:00 DEBUG: AuthState == Unauthenticated calling auth callbacks with failure
I/Unity   (17841):
I/Unity   (17841): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity   (17841):
I/Unity   (17841):  [Play Games Plugin DLL] 01/16/17 19:48:26 -08:00 DEBUG: Invoking user callback on game thread
I/Unity   (17841):
I/Unity   (17841): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity   (17841):

`

**Comment by claywilkinson** [comment]
Can you re-confirm that the game configuration in the Play Developer Console is in the Published state?  This is separate from publishing an APK.
Also, can you share the complete log, not filtering on Unity?

**Comment by DruidV1** [comment]
Yeah they are both in the published state. I gathered some more info and the users that are complaining, the rights are different.

For example these are the rights on my account which works fine:
as access to:	
	Google Play
Share your Google+ profile information and view and manage your game activity
	Google+
Know your age range and language
	Basic account info
View your basic profile info
Additional access
View your approximate age
View your language preferences

The account that does not work has the following:
has access to:

Google Play
Manage your game activity for this game

**Comment by claywilkinson** [comment]
Does your game require Google Plus?  It could be that the account that is failing does not have a G+ account.

**Comment by DruidV1** [comment]
I think this was a problem on the device, it worked fine after using a different device. I currently use the google+ id to verify the users account on the back end.
