### ISSUE TITLE
Changes to GooglePlayGames in February. Issues to be expected?

### ISSUE THREAD

**Issue by MenesApps** [playgameservices/play-games-plugin-for-unity#1557]
Hi, 
Don't know if it is the place to ask, but I've read that Google+ is being decoupled from Google Play Games. I'm guessing this plugin will be updated (if it hasn't already) but I'm wondering if the transition will affect its users. For example: my game uses real-time multiplayer (matchmaking and play against friends or recent users). Will these features require a rewrite of the existing code? Same for leaderboards I guess? 
I plan on releasing Feb 1st, so I'd like to know if half my features will stop working a few days after launch :) 
Thanks in advance and sorry if it is not the place to ask!

**Comment by claywilkinson** [comment]
Hi @MenesApps - I think this is a fine place to ask.  I don't know the exact timing of the complete deprecation, but the new game profiles that have a gamer tag and avatar, do not necessarily have a Google Plus account, so for these players, Quick match making is the only option.  I believe the recent players will be populated using quick-matched opponents, provided they have a public gamer profile -- but let me confirm this and get back to you when I have more information.

**Comment by MenesApps** [comment]
Great. Thank you very much!
