### ISSUE TITLE
symbol(s) not found for architecture armv7

### ISSUE THREAD

**Issue by hyunzlife** [playgameservices/play-games-plugin-for-unity#1558]
Hi, I carefully read manual how to build minimal sample for iOS, but still need help.

I'm using
Unity 5.5.0f4
xCode 8.2
Play Games Plugin 0.9.36
Cocoapod 1.1.1

**1.I've created next Podfile:**

=======================================

platform :ios, ‘9.2’

target 'Unity-iPhone' do
    pod 'GooglePlayGames'
end

target 'Unity-iPhone Tests' do
    pod 'GooglePlayGames'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

**2.pod install log:**

Analyzing dependencies
Downloading dependencies
Installing GoogleAppUtilities (1.1.2)
Installing GoogleAuthUtilities (1.0.1)
Installing GoogleNetworkingUtilities (1.2.2)
Installing GooglePlayGames (5.1.2)
Installing GooglePlusOpenSource (1.7.1)
Installing GoogleSignIn (2.4.0)
Installing GoogleSymbolUtilities (1.1.2)
Installing GoogleUtilities (1.3.2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 8 total pods installed.

[!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

[!] The `Unity-iPhone Tests [Release]` target overrides the `LIBRARY_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Unity-iPhone Tests/Pods-Unity-iPhone Tests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Unity-iPhone Tests [ReleaseForProfiling]` target overrides the `LIBRARY_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Unity-iPhone Tests/Pods-Unity-iPhone Tests.releaseforprofiling.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Unity-iPhone Tests [ReleaseForRunning]` target overrides the `LIBRARY_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Unity-iPhone Tests/Pods-Unity-iPhone Tests.releaseforrunning.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Unity-iPhone Tests [Debug]` target overrides the `LIBRARY_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Unity-iPhone Tests/Pods-Unity-iPhone Tests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

==========================================

![xcode1](https://cloud.githubusercontent.com/assets/25191024/22053086/ce9328aa-dd91-11e6-9661-b33f1799a0f1.png)
![pod1](https://cloud.githubusercontent.com/assets/25191024/22053087/d055e5f6-dd91-11e6-980c-20cf09b56965.png)

**3.After this changes Build finishes**

![2017-01-18 3 25 51](https://cloud.githubusercontent.com/assets/25191024/22053199/7ce54136-dd92-11e6-9be8-197f11c6b5f9.png)
![2017-01-18 3 26 05](https://cloud.githubusercontent.com/assets/25191024/22053202/80f44dd0-dd92-11e6-9a71-bf509647ba76.png)

**4.i added $(inherited) to**

Other C Flags
Other linker flags
Header Search Paths
Then disabled bitcode.

I want to know how to fix it.

**Comment by VivekDeshpande** [comment]
These are Firebase symbols. You will need to add pod 'Firebase' to your podfile.

**Comment by hyunzlife** [comment]
Thank you for answer.

Your answer is correct.

I installed pod 'firebase' so that the error was gone.

However, another error has occurred and I can not find a solution for this.

**1. add pod 'Firebase'**

platform :ios, ‘9.2’

target 'Unity-iPhone' do
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'GooglePlayGames'

end

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['ENABLE_BITCODE'] = 'NO'
end
end
end


**2.The following error occurred when building with xcode.**

Showing All Messages
Ld /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/lottoday normal arm64
cd /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B
export IPHONEOS_DEPLOYMENT_TARGET=9.2
export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -L/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos -L/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B -L/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Libraries -L/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Libraries/Plugins/iOS/Firebase -L/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Libraries/Plugins/iOS -L/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GTMSessionFetcher -L/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GooglePlayGames -L/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac -L/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GoogleAuthUtilities/Libraries -L/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GoogleSignIn/Libraries -F/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/FirebaseAnalytics/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/FirebaseAuth/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/FirebaseCore/Frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/FirebaseInstanceID/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/FirebaseMessaging/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GoogleAppUtilities/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GoogleInterchangeUtilities/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GoogleNetworkingUtilities/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlayGames/gpg-cpp-sdk/ios -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1 -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GoogleSymbolUtilities/Frameworks/frameworks -F/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GoogleUtilities/Frameworks/frameworks -filelist /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/lottoday.LinkFileList -Xlinker -map -Xlinker /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/lottoday-LinkMap-normal-arm64.txt -miphoneos-version-min=9.2 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/lottoday_lto.o -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -lc++ -weak_framework CoreMotion -weak-lSystem -ObjC -std=gnu++11 -lGIPNSURL+FIFE -lGTMOAuth2_external -lGTMOAuth2_internal -lGTMSessionFetcher -lGooglePlayGames -lGoogleToolboxForMac -lSignIn -lc++ -lsqlite3 -lz -framework AddressBook -framework AssetsLibrary -framework CoreData -framework CoreGraphics -framework CoreLocation -framework CoreMotion -framework CoreTelephony -framework CoreText -framework FirebaseAnalytics -framework FirebaseAuth -framework FirebaseCore -framework FirebaseInstanceID -framework FirebaseMessaging -framework GoogleAppUtilities -framework GoogleInterchangeUtilities -framework GoogleNetworkingUtilities -framework GoogleOpenSource -framework GoogleSymbolUtilities -framework GoogleUtilities -framework MediaPlayer -framework QuartzCore -framework SafariServices -framework Security -framework StoreKit -framework SystemConfiguration -framework gpg -framework Security -liPhone-lib -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework MediaPlayer -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lAuth -lAnalytics -lVuforia -lMessaging -lApp -lVuforiaUnityPlayer -framework StoreKit -framework GameKit -weak_framework Metal -lPods-Unity-iPhone -Xlinker -dependency_info -Xlinker /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/lottoday_dependency_info.dat -o /Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/lottoday

ld: warning: arm64 function not 4-byte aligned: ltmp0 from /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
duplicate symbol __Z18RegisterAllClassesv in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/RegisterMonoModules.o
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/UnityClassRegistration.o
duplicate symbol __Z43InvokeRegisterStaticallyLinkedModuleClassesv in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/RegisterMonoModules.o
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/UnityClassRegistration.o
duplicate symbol __Z39RegisterStaticallyLinkedModulesGranularv in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/RegisterMonoModules.o
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/UnityClassRegistration.o
duplicate symbol __Z32RegisterAllStrippedInternalCallsv in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/RegisterMonoModules.o
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Intermediates/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/UnityICallRegistration.o
duplicate symbol OBJC_IVAR$GTMLogger.formatter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_IVAR$GTMLogger.filter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_IVAR$GTMLogger.writer in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_IVAR$GTMLogStandardFormatter.dateFormatter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_IVAR$GTMLogStandardFormatter.pname in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_IVAR$GTMLogStandardFormatter.pid in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_IVAR$GTMLogAllowedLevelFilter.allowedLevels in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_CLASS$_GTMLogStandardFormatter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_METACLASS$_GTMLogStandardFormatter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_CLASS$_GTMLogBasicFormatter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_CLASS$_GTMLogLevelFilter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_METACLASS$_GTMLogLevelFilter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_METACLASS$_GTMLogBasicFormatter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_CLASS$_GTMLogMaximumLevelFilter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_METACLASS$_GTMLogMaximumLevelFilter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_CLASS$_GTMLogAllowedLevelFilter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_CLASS$_GTMLogMininumLevelFilter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_METACLASS$_GTMLogMininumLevelFilter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_CLASS$_GTMLogNoFilter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_METACLASS$_GTMLogNoFilter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_CLASS$_GTMLogger in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_METACLASS$_GTMLogger in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
duplicate symbol OBJC_METACLASS$_GTMLogAllowedLevelFilter in:
/Users/HyunzLife/Library/Developer/Xcode/DerivedData/Unity-iPhone-gagxgbnstyhdxlbdajmpyqcifqth/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac/libGoogleToolboxForMac.a(GTMLogger.o)
/Users/HyunzLife/private/LottoDay/IPHONE_LOTTODAY_0119B/Pods/GooglePlusOpenSource/google-plus-ios-sdk-1.7.1/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
ld: 27 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**3.I need help how to solve it**

**Comment by hyunzlife** [comment]
Removing GTMLogger has been fixed.
