### ISSUE TITLE
CommandInvokationFailure: Failed to re-package resources when added GooglePlayGames plugin

### ISSUE THREAD

**Issue by Ravenh0lm** [playgameservices/play-games-plugin-for-unity#1559]
Good day. I use deltaDNA Analytics unity plugin and all works fine. But when i adding GooglePlayGames plugin i keep on getting re-package failure errors. Part of error message below:

>  CommandInvokationFailure: Failed to re-package resources.
 C:\Androidsdk\build-tools\25.0.1\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Androidsdk\platforms\android-25\android.jar" -F bin/resources.ap_ --extra-packages com.deltadna.android.sdk.notifications:com.google.example.games.mainlibproj:com.google.android.gms.auth.api:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.gcm:com.google.android.gms.nearby:com.google.android.gms.tasks:android.support.v4:android.support.v4 -S "D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\deltadna-sdk-notifications-4.2.3\res" -S "D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\play-services-auth-10.0.1\res" -S "D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\play-services-auth-base-10.0.1\res" -S "D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\play-services-base-10.0.1\res" -S "D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\play-services-base-7.8.0\res" -S "D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\play-services-basement-10.0.1\res" -S "D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\play-services-drive-10.0.1\res" -S "D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\play-services-games-10.0.1\res" -S "D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\play-services-gcm-7.8.0\res" -S "D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\play-services-nearby-10.0.1\res" -S "D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\play-services-tasks-10.0.1\res" -S "D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\support-v4-23.1.1\res" -S "D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\support-v4-24.0.0\res" 
 stderr[
 D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\play-services-base-10.0.1\res\values\values.xml:33: error: Attribute "imageAspectRatioAdjust" already defined with incompatible format.
 D:\D\Unity\Projects\AllPlugin1\Temp\StagingArea\android-libraries\play-services-base-7.8.0\res\values\common_attrs.xml:13: Original attribute defined here.
 AndroidManifest.xml:34: error: Error: No resource found that matches the given name (at 'resource' with value '@string/sender_id'). 
 ]
 stdout[
 Configurations:
  (default) 
 Files:
   AndroidManifest.xml
     Src: () AndroidManifest.xml 
 Resource Dirs:
 Including resources from package: C:\Androidsdk\platforms\android-25\android.jar

I think this is conflict between "play-services-base-10.0.1" used by GP and "play-services-base-7.8.0" used DeltaDNA SDK but i dont know how to fix this issue. Both plugins work correctly separated from each other

**Comment by claywilkinson** [comment]
You should remove all the older versions of play-services-* from your project.  For the most part (unless a deprecated method has finally been removed) the play-services libraries are backward compatible.

**Comment by Ravenh0lm** [comment]
Thanks for quick reply. Yes, i solve it by deleting old version

**Comment by cherucole** [comment]
same here
CommandInvokationFailure: Failed to re-package resources.
/Users/cherucole/Library/Android/sdk/build-tools/28.0.3/aapt package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "/Users/cherucole/Library/Android/sdk/platforms/android-28/android.jar" -F bin/resources.ap_ --extra-packages com.soomla.SoomlaApp:com.android.vending.billing:com.google.unity:com.unity.purchasing.googleplay:com.google.example.games.mainlibproj:com.soomla.SoomlaApp:android.support.v7.cardview:android.support.compat:android.support.coreui:android.support.coreutils:android.support.fragment:android.support.mediacompat:android.support.v4:com.google.android.gms.auth.api:com.google.android.gms.auth.api:com.google.android.gms.auth.api.phone.license:com.google.android.gms.auth:com.google.android.gms.auth.license:com.google.android.gms.base:com.google.android.gms.base.license:com.google.android.gms:com.google.android.gms.common.license:com.google.android.gms.drive:com.google.android.gms.drive.license:com.google.android.gms.games:com.google.android.gms.games.license:com.google.android.gms.nearby:com.google.android.gms.nearby.license:com.google.android.gms.tasks:com.google.android.gms.tasks.license:com.google.games.bridge:com.unity.purchasing:com.facebook:com.facebook.android:com.google.android.gms:android.support.v4:com.unity3d.ads -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/GoogleAIDL/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/GooglePlay/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/cardview-v7-23.1.1/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.android.support.support-compat-25.2.0/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.android.support.support-core-ui-25.2.0/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.android.support.support-core-utils-25.2.0/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.android.support.support-fragment-25.2.0/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.android.support.support-media-compat-25.2.0/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.android.support.support-v4-25.2.0/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-auth-11.6.2/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-auth-api-phone-11.6.2/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-auth-base-11.6.2/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-base-11.6.2/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-basement-11.6.2/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-drive-11.6.2/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-games-11.6.2/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-nearby-11.6.2/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-tasks-11.6.2/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.google.games.gpgs-plugin-support-0.9.50/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/common/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/facebook-android-sdk-4.9.0/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/facebook-android-wrapper-7.4.0/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/google-play-services_lib/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/support-v4-23.1.1/res" -S "/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/unity-ads/res"

stderr[
/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-base-11.6.2/res/values/values.xml:33: error: Attribute "imageAspectRatioAdjust" already defined with incompatible format.
/Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/google-play-services_lib/res/values/common_attrs.xml:13: Original attribute defined here.
]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: /Users/cherucole/Library/Android/sdk/platforms/android-28/android.jar
applyFileOverlay for drawable
trying overlaySet Key=cast_ic_notification_0.png
trying overlaySet Key=cast_ic_notification_1.png
trying overlaySet Key=cast_ic_notification_2.png
trying overlaySet Key=cast_ic_notification_connecting.xml
trying overlaySet Key=cast_ic_notification_on.png
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_ic_googleplayservices.png
trying overlaySet Key=common_signin_btn_icon_dark.xml
trying overlaySet Key=common_signin_btn_icon_disabled_dark.9.png
trying overlaySet Key=common_signin_btn_icon_disabled_focus_dark.9.png
trying overlaySet Key=common_signin_btn_icon_disabled_focus_light.9.png
trying overlaySet Key=common_signin_btn_icon_disabled_light.9.png
trying overlaySet Key=common_signin_btn_icon_focus_dark.9.png
trying overlaySet Key=common_signin_btn_icon_focus_light.9.png
trying overlaySet Key=common_signin_btn_icon_light.xml
trying overlaySet Key=common_signin_btn_icon_normal_dark.9.png
trying overlaySet Key=common_signin_btn_icon_normal_light.9.png
trying overlaySet Key=common_signin_btn_icon_pressed_dark.9.png
trying overlaySet Key=common_signin_btn_icon_pressed_light.9.png
trying overlaySet Key=common_signin_btn_text_dark.xml
trying overlaySet Key=common_signin_btn_text_disabled_dark.9.png
trying overlaySet Key=common_signin_btn_text_disabled_focus_dark.9.png
trying overlaySet Key=common_signin_btn_text_disabled_focus_light.9.png
trying overlaySet Key=common_signin_btn_text_disabled_light.9.png
trying overlaySet Key=common_signin_btn_text_focus_dark.9.png
trying overlaySet Key=common_signin_btn_text_focus_light.9.png
trying overlaySet Key=common_signin_btn_text_light.xml
trying overlaySet Key=common_signin_btn_text_normal_dark.9.png
trying overlaySet Key=common_signin_btn_text_normal_light.9.png
trying overlaySet Key=common_signin_btn_text_pressed_dark.9.png
trying overlaySet Key=common_signin_btn_text_pressed_light.9.png
trying overlaySet Key=ic_plusone_medium_off_client.png
trying overlaySet Key=ic_plusone_small_off_client.png
trying overlaySet Key=ic_plusone_standard_off_client.png
trying overlaySet Key=ic_plusone_tall_off_client.png
trying overlaySet Key=powered_by_google_dark.png
trying overlaySet Key=powered_by_google_light.png
trying overlaySet Key=com_facebook_auth_dialog_background.xml
trying overlaySet Key=com_facebook_auth_dialog_cancel_background.xml
trying overlaySet Key=com_facebook_auth_dialog_header_background.xml
trying overlaySet Key=com_facebook_button_background.xml
trying overlaySet Key=com_facebook_button_icon.xml
trying overlaySet Key=com_facebook_button_icon_blue.png
trying overlaySet Key=com_facebook_button_icon_white.png
trying overlaySet Key=com_facebook_button_like_background.xml
trying overlaySet Key=com_facebook_button_like_icon_selected.png
trying overlaySet Key=com_facebook_button_login_silver_background.xml
trying overlaySet Key=com_facebook_button_send_background.xml
trying overlaySet Key=com_facebook_button_send_icon_blue.png
trying overlaySet Key=com_facebook_button_send_icon_white.png
trying overlaySet Key=com_facebook_close.png
trying overlaySet Key=com_facebook_favicon_white.png
trying overlaySet Key=com_facebook_profile_picture_blank_portrait.png
trying overlaySet Key=com_facebook_profile_picture_blank_square.png
trying overlaySet Key=com_facebook_send_button_icon.xml
trying overlaySet Key=com_facebook_tooltip_black_background.9.png
trying overlaySet Key=com_facebook_tooltip_black_bottomnub.png
trying overlaySet Key=com_facebook_tooltip_black_topnub.png
trying overlaySet Key=com_facebook_tooltip_black_xout.png
trying overlaySet Key=com_facebook_tooltip_blue_background.9.png
trying overlaySet Key=com_facebook_tooltip_blue_bottomnub.png
trying overlaySet Key=com_facebook_tooltip_blue_topnub.png
trying overlaySet Key=com_facebook_tooltip_blue_xout.png
trying overlaySet Key=messenger_bubble_large_blue.png
trying overlaySet Key=messenger_bubble_large_white.png
trying overlaySet Key=messenger_bubble_small_blue.png
trying overlaySet Key=messenger_bubble_small_white.png
trying overlaySet Key=messenger_button_blue_bg_round.xml
trying overlaySet Key=messenger_button_blue_bg_selector.xml
trying overlaySet Key=messenger_button_send_round_shadow.png
trying overlaySet Key=messenger_button_white_bg_round.xml
trying overlaySet Key=messenger_button_white_bg_selector.xml
trying overlaySet Key=ic_launcher.png
trying overlaySet Key=common_full_open_on_phone.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor tvdpi-v4
baseFile 2 has flavor hdpi-v4
baseFile 3 has flavor xhdpi-v4
baseFile 4 has flavor xxhdpi-v4
overlayFile 0 has flavor hdpi-v4
overlayFile 1 has flavor xhdpi-v4
found a match (2) for overlay file common_full_open_on_phone.png, for flavor hdpi-v4
found a match (3) for overlay file common_full_open_on_phone.png, for flavor xhdpi-v4
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_normal_background.9.png
trying overlaySet Key=common_google_signin_btn_icon_disabled.xml
trying overlaySet Key=common_google_signin_btn_icon_light.xml
trying overlaySet Key=common_google_signin_btn_icon_light_focused.xml
trying overlaySet Key=common_google_signin_btn_icon_light_normal.xml
trying overlaySet Key=common_google_signin_btn_icon_light_normal_background.9.png
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_dark_focused.xml
trying overlaySet Key=common_google_signin_btn_text_dark_normal.xml
trying overlaySet Key=common_google_signin_btn_text_dark_normal_background.9.png
trying overlaySet Key=common_google_signin_btn_text_disabled.xml
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_google_signin_btn_text_light_focused.xml
trying overlaySet Key=common_google_signin_btn_text_light_normal.xml
trying overlaySet Key=common_google_signin_btn_text_light_normal_background.9.png
trying overlaySet Key=googleg_disabled_color_18.png
trying overlaySet Key=googleg_standard_color_18.png
trying overlaySet Key=common_google_signin_btn_text_dark_normal.xml
baseFile 0 has flavor 
overlayFile 0 has flavor watch-v20
nothing matches overlay file common_google_signin_btn_text_dark_normal.xml, for flavor watch-v20
trying overlaySet Key=common_google_signin_btn_text_disabled.xml
baseFile 0 has flavor 
overlayFile 0 has flavor watch-v20
nothing matches overlay file common_google_signin_btn_text_disabled.xml, for flavor watch-v20
trying overlaySet Key=common_google_signin_btn_text_light_normal.xml
baseFile 0 has flavor 
overlayFile 0 has flavor watch-v20
nothing matches overlay file common_google_signin_btn_text_light_normal.xml, for flavor watch-v20
trying overlaySet Key=app_banner.png
trying overlaySet Key=app_icon.png
applyFileOverlay for layout
trying overlaySet Key=com_facebook_activity_layout.xml
trying overlaySet Key=com_facebook_device_auth_dialog_fragment.xml
trying overlaySet Key=com_facebook_login_fragment.xml
trying overlaySet Key=com_facebook_tooltip_bubble.xml
trying overlaySet Key=messenger_button_send_blue_large.xml
trying overlaySet Key=messenger_button_send_blue_round.xml
trying overlaySet Key=messenger_button_send_blue_small.xml
trying overlaySet Key=messenger_button_send_white_large.xml
trying overlaySet Key=messenger_button_send_white_round.xml
trying overlaySet Key=messenger_button_send_white_small.xml
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
trying overlaySet Key=gtm_analytics
applyFileOverlay for color
trying overlaySet Key=common_signin_btn_text_dark.xml
trying overlaySet Key=common_signin_btn_text_light.xml
trying overlaySet Key=wallet_primary_text_holo_light.xml
trying overlaySet Key=wallet_secondary_text_holo_dark.xml
trying overlaySet Key=com_facebook_button_text_color.xml
trying overlaySet Key=com_facebook_send_button_text_color.xml
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_google_signin_btn_tint.xml
applyFileOverlay for menu
applyFileOverlay for font
applyFileOverlay for mipmap
Processing image: res/drawable-xhdpi/app_banner.png
Processing image: res/drawable-ldpi/app_icon.png
Processing image: res/drawable-mdpi/app_icon.png
Processing image: res/drawable-hdpi/app_icon.png
    (processed image res/drawable-ldpi/app_icon.png: 99% size of source)
Processing image: res/drawable-xhdpi/app_icon.png
    (processed image res/drawable-mdpi/app_icon.png: 99% size of source)
Processing image: res/drawable-xxhdpi/app_icon.png
    (processed image res/drawable-hdpi/app_icon.png: 100% size of source)
Processing image: res/drawable-xxxhdpi/app_icon.png
    (processed image res/drawable-xhdpi/app_icon.png: 100% size of source)
Processing image: /Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/google-play-services_lib/res/drawable-mdpi/cast_ic_notification_0.png
    (processed image /Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/google-play-services_lib/res/drawable-mdpi/cast_ic_notification_0.png: 155% size of source)
Processing image: /Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/google-play-services_lib/res/drawable-hdpi/cast_ic_notification_0.png
    (processed image /Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/google-play-services_lib/res/drawable-hdpi/cast_ic_notification_0.png: 141% size of source)
Processing image: /Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/google-play-services_lib/res/drawable-xhdpi/cast_ic_notification_0.png
    (processed image /Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/google-play-services_lib/res/drawable-xhdpi/cast_ic_notification_0.png: 136% size of source)
Processing image: /Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/google-play-services_lib/res/drawable-xxhdpi/cast_ic_notification_0.png
    (processed image /Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/google-play-services_lib/res/drawable-xxhdpi/cast_ic_notification_0.png: 125% size of source)
Processing image: /Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/google-play-services_lib/res/drawable-mdpi/cast_ic_notification_1.png
    (processed image /Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingArea/android-libraries/google-play-services_lib/res/drawable-mdpi/cast_ic_notification_1.png: 156% size of source)
Processing image: /Volumes/Stuff/Drive Live/Live with Policy/Lollipop/Temp/StagingAr<message truncated>
