### ISSUE TITLE
Google Play service Authentication issue

### ISSUE THREAD

**Issue by stblue** [playgameservices/play-games-plugin-for-unity#156]
I have downloaded the google play service form https://github.com/playgameservices/play-games-plugin-for-unity, to implement leaderboard feature into my game. i have followed the tutorial on github and implemented it, here is the code

    using UnityEngine;
    using System.Collections;
    using GooglePlayGames;
    using UnityEngine.SocialPlatforms;
     
    public class testGPGMenu : MonoBehaviour
    {
     
    public GUISkin skin;
    public int incrementalCount = 5;
     
    //leaderboard strings
    private string leaderboard = "CgkI1LWPssgUEAIQAg";
   
     
    // Use this for initialization
    void Start()
    {
    PlayGamesPlatform.Activate();
    }
     
    // Update is called once per frame
    public void OnGUI()
    {
     
    GUILayout.BeginArea(new Rect(0, 0, Screen.width, Screen.height));
     
    GUILayout.BeginVertical("box");
     
    GUILayout.Label("Official Google Play Games Services");
     
    GUILayout.Space(20);
     
    //Share Status
    if (GUILayout.Button("Log In"))
    {
    Social.localUser.Authenticate((bool success) =>
    {
    if (success)
    {
    Debug.Log("You've successfully logged in");
    }
    else
    {
    Debug.Log("Login failed for some reason");
    }
    });
    }
     
 
    GUILayout.Space(20);
     
    //Leaderboard
    if (GUILayout.Button("Post your 5000 points to the leaderboard"))
    {
    if (Social.localUser.authenticated)
    {
    Social.ReportScore(5000, leaderboard, (bool success) =>
    {
    if (success)
    {
    ((PlayGamesPlatform)Social.Active).ShowLeaderboardUI(leaderboard);
    }
    else
    {
    //Debug.Log("Login failed for some reason");
    }
    });
    }
    }
     
    GUILayout.Space(20);
     
    // Show Leaderboard
    if (GUILayout.Button("Show Leaderboard"))
    {
    Social.ShowLeaderboardUI();
    }
     

     
    GUILayout.EndVertical();
    GUILayout.EndArea();
    }
    }

Here is what i get in logcat
    I/Unity ( 3222): NullReferenceException: Object reference not set to an instan
    ce of an object
    I/Unity ( 3222): at GooglePlayGames.Android.AndroidClient+<Authenticate>c__A
    nonStorey0.<>m__1 () [0x00000] in <filename unknown>:0
    I/Unity ( 3222): at UnityEngine.AndroidJavaRunnableProxy.run () [0x00000] in
    <filename unknown>:0
    I/Unity ( 3222): at System.Reflection.MonoMethod.Invoke (System.Object obj,
    BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parame
    ters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:
    0
    I/Unity ( 3222): Rethrow as TargetInvocationException: UnityEngine.AndroidJava
    RunnableProxy.run()
    I/Unity ( 3222): at UnityEngine.AndroidJavaProxy.Invoke (System.String metho
    dName, System.Object[] args) [0x00000] in <filename unknown>:0
    I/Unity ( 3222): at UnityEngine.AndroidJavaProxy.Invoke (System.String metho
    dName, UnityEngine.AndroidJavaObject[] javaArgs) [0x00000] in <filename unknown>
    :0
    I/Unity ( 3222): at UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (Uni
    tyEngine.AndroidJavaProxy proxy, IntPtr jmethodName, IntPtr jargs) [0x00000] in
    <filename unknown>:0

Also i have imported google play service package into unity and provided application id into android setup. But as soon as i press "Log In" button nothing will happen. Iam expecting some pop up for user to show its mail id. How to do that or i am doing something wrong above

**Comment by claywilkinson** [comment]
Closing this  - and the implementation of the plugin has changed so the callstack is obsolete as well.  If there are still problems, please open another issue.
