### ISSUE TITLE
Silent login on first launch doesn't work

### ISSUE THREAD

**Issue by mholub** [playgameservices/play-games-plugin-for-unity#1560]
I am trying to implement first launch logic similar to Clash of Clans.

When you launch Clash of Clans first time, if you have one and only one google play account on the device, it silently logs you in and automatically connects game account to the google play account. It doesn't show you dialog "Choose an account", which allows you, for example, create the new one.

Unity Plugin has "silent" flag but it works differently:
1. If I set it to true, then authorization simply fails. So I can't set it to true.
2. If I set it to false, then it shows this "Choose an account" dialog which I want to avoid in the case if there is only one account. And if there is no logged user on the device, then it still shows the dialog and I want to avoid this situation. 

So how can I achieve the behavior similar to Clash of clans with this plugin?

**Comment by claywilkinson** [comment]
Silent login works provided a couple requirements are satisfied.  First, the player needs to sign into a game.  Second, the player settings found in the Play Games App, need to have the "Sign into games automatically" set.  Also, it might help to have "Use this account to sign in" enabled.

The other thing is that if you call signout to signout of the game, it will prompt you to select an account, even if there is only one.

**Comment by mholub** [comment]
Thank you. I have no previous experience with Android platform from user and developer side so I was confused. I looked at popular games and now I understand what to do. So thank you again
