### ISSUE TITLE
Connect to both Play Services and Game Center at the same time?

### ISSUE THREAD

**Issue by dnaultjb** [playgameservices/play-games-plugin-for-unity#1561]
Hi guys,

we are trying to use the Saved Games cloud feature from the Play Services on iOS, but we'd like to keep the achievements and leaderboards connected to Game Center, both through Unity's Social class (basically, stay connected to both services at the same time).

Are we allowed to do this or only one service can be connected at a time?

Because it seems to be working when the user manually login from our game's setting page, but afterward, when he gets silently signed in when the game starts, he seems to be disconnected from Game Center for some reason.

Thanks,

**Comment by claywilkinson** [comment]
I am not aware of any code in this plugin that would cause Game Center to be disconnected.  If all you are using is saved games, you might want to look into using the [Drive API] (https://developers.google.com/drive/ios/quickstart)  directly vs. through Play Game Services.

You might also  want to check the [Unity community](http://answers.unity3d.com/) to see if someone else has more Game Center experience.

**Comment by Dod2** [comment]
Are you sure you're not calling PlayGamesPlatform.Activate at any time? 
You should be able to talk to Game Center through the Social class and Play Games through the PlayGamesPlatform class simultaneously with no conflict at all on IOS.

**Comment by dnaultjb** [comment]
Thanks for your replies. We are indeed calling "_PlayGamesPlatform.Activate_", but only when the player wants to use the cloud save feature (he is then automatically signed in every time the game starts).

Seems like our current workaround is to re-authenticate to the current service each time we need to talk to it. Not an ideal solution, but we'll keep looking for what we did wrong.

**Comment by claywilkinson** [comment]
@Dod2 is correct.  I believe you never should call PlayGamesPlatform.Activate.  Calling PlayGamesPlatform.Activate will make the active Social implementation be Play Game Services, which is probably causing the problem.

**Comment by claywilkinson** [comment]
iOS is no longer supported by this plugin: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
