### ISSUE TITLE
iOS Play Game profile problem

### ISSUE THREAD

**Issue by jeffyuio1129** [playgameservices/play-games-plugin-for-unity#1562]
Hi

I found problems with iOS.
If you do not have a Play Game profile when you sign in with your Google account, "Social.localUser.Authenticate ()" return false.

Profile creation screen does not appear.

Let me know how to solve this problem.

Thanks.

**Comment by claywilkinson** [comment]
Thanks for the issue!

Profile creation is not supported on iOS: https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html
