### ISSUE TITLE
Cancel matchmaking search

### ISSUE THREAD

**Issue by Incradiator** [playgameservices/play-games-plugin-for-unity#1564]
Is there a way to cancel the matchmaking call after it has been initiated? Perhaps I'm not understanding how it works after all.

**Comment by claywilkinson** [comment]
You can call LeaveRoom() to leave matchmaking.

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
