### ISSUE TITLE
Leaderboards don't function on iOS

### ISSUE THREAD

**Issue by dreamwagon** [playgameservices/play-games-plugin-for-unity#1567]
I have implemented google play save games and leaderboards in my unity game and it works great on android, but when porting to iOs the leaderboards are not working (Save game and post to leaderboard does work fine). I can open the default leaderboard selection screen, but it does not have the top bar with the back arrow. I see the error "Failed to find string for leaderboards_title" in bundle "null"

If I tap either of the leaderboards to view them, the game crashes on the device
NSInvalidArgumentException 
Failed to find string for [leaderboard_time_scope_all_time] in bundle

I setup the google play sdk manual instead of using cocoapods but everything else seems to be working fine. I am trying to determine if this is a bug or if I have setup something incorrectly in xcode.

Development OS 10.2
Device: IPad OS 9.1
Unity 5.4.1
xcode 8.2.1
gpg sdk 4.0

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
