### ISSUE TITLE
iOS - How to remove unused OAuth scope?

### ISSUE THREAD

**Issue by bullet-tooth** [playgameservices/play-games-plugin-for-unity#1568]
Hi,
I got an issue with unused permissions in OAuth scope.
I have next code and expect to see "View user email address" and "Manage your Youtube account" permissions for user allowing.

```C#
PlayGamesClientConfiguration configuration = new PlayGamesClientConfiguration.Builder ()
              .AddOauthScope("https://www.googleapis.com/auth/userinfo.email")
              .AddOauthScope("https://www.googleapis.com/auth/youtube")
              .Build();		
PlayGamesPlatform.InitializeInstance (configuration);	
PlayGamesPlatform.Activate ();
Social.localUser.Authenticate ((bool success) => {
				Debug.Log("Google login, success = " + success);
			});
```

But actually I got next:
![access](https://cloud.githubusercontent.com/assets/5055052/22288354/3b3a298c-e2ff-11e6-8eee-8d90b3c7465b.png)

So, how to remove from scope permissions that I didn't define?

**Comment by claywilkinson** [comment]
Did you check the "require Google+" in the setup dialog for the plugin?

**Comment by bullet-tooth** [comment]
No, if you mean that:
![1](https://cloud.githubusercontent.com/assets/5055052/22381358/fca03514-e4c9-11e6-8cbe-a0c6fe2c4c73.PNG)

**Comment by bullet-tooth** [comment]
Forgot to say that the issue is related to iOS platform.

**Comment by claywilkinson** [comment]
Unfortunately,  GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
