### ISSUE TITLE
How do I get the email addres after login

### ISSUE THREAD

**Issue by akira32** [playgameservices/play-games-plugin-for-unity#1570]
I run the code as below, it will appear the error code about "InvalidCastException: Cannot cast from source type to destination type." Does somebody know how to get the user mail after logining?

`			Social.localUser.Authenticate((bool success) =>
			{
				if (success)
				{
					print("login success!!");
					print("id=" + Social.localUser.id);
					print("name=" + Social.localUser.userName);

					string email = ((PlayGamesLocalUser)Social.localUser).Email;
					print("email=" + email);

					myText.text = email;
				}
			});`

**Comment by enriqif** [comment]
hey akira32!! I have the same problem. What did you do?

**Comment by claywilkinson** [comment]
The email access has been updated to be aligned with Google Sign-In in version 0.9.37 of the plugin.  The steps are:
1. call `requestEmail()` when building the ClientConfiguration object.
2. Authenticate as usual, then you can access the email property of the user immediately (no need to poll).
