### ISSUE TITLE
Assets/GPGSIds.cs(28,29): error CS0102: The type `GPGSIds' already contains a definition for `achievement__'

### ISSUE THREAD

**Issue by prophys** [playgameservices/play-games-plugin-for-unity#1571]
showed up setup complete message but, compile error.

Assets/GPGSIds.cs(28,29): error CS0102: The type `GPGSIds' already contains a definition for `achievement__'

public static class GPGSIds
{
        public const string achievement__ = "CggI_ce......."; // <GPGSID>
        public const string achievement__ = "CggI_cen....."; // <GPGSID>

}

**Comment by claywilkinson** [comment]
This looks like you defined achievements that did not have names in the developer console that could not be used as variable names.  Can you rename the achievements?

**Comment by prophys** [comment]
thank you for your reply. i've solved this problem. only english name work.

**Comment by claywilkinson** [comment]
Great! I passed along a suggestion to the dev-console team to handle non-english better :)
