### ISSUE TITLE
Not Authenticating 2

### ISSUE THREAD

**Issue by BaterieCZ** [playgameservices/play-games-plugin-for-unity#1573]
I have similar problem what already was here, but any fix from older posts not working for me.
I have all set ok: app is signed, testing email in console, plugin and setup inside unity,...

But i still have ERROR_NOT_AUTHORIZED. Nothing work. What can i do? Using unity 5.5.0f3

EDIT: Even minimal example project not work :/

**Comment by BaterieCZ** [comment]
Even minimal example project not work :/

**Comment by BaterieCZ** [comment]
closed by mistake

**Comment by claywilkinson** [comment]
Can you share the log?

**Comment by BaterieCZ** [comment]
![screenshot_20170127-225413 1](https://cloud.githubusercontent.com/assets/3463591/22389066/13c23b2e-e4e4-11e6-85f7-a6cf1adc6a75.png)

**Comment by BaterieCZ** [comment]
FINALLY! It was problem of Google API!
https://console.developers.google.com/apis/credentials
Somehow the fingerprint was different on API and on APP!
**CHECK THIS BEFORE WASTING DAYS ON FORUMS! :D**
