### ISSUE TITLE
DeveloperError trying to get the GetServerAuthCode

### ISSUE THREAD

**Issue by Ralstlin** [playgameservices/play-games-plugin-for-unity#1574]
this return DeveloperError as authStatus:

```        PlayGamesPlatform.Instance.GetServerAuthCode((Action<CommonStatusCodes, string>)((authStatus, code) =>
        {
            if (authStatus == CommonStatusCodes.Success)
            {
```
I could not run this code for a while but before it was working fine.

This is my configuration:

```            PlayGamesClientConfiguration config = new PlayGamesClientConfiguration
                .Builder()
                .AddOauthScope("profile")
                .AddOauthScope("email")
                .AddOauthScope("https://www.googleapis.com/auth/games")
                .Build();
```

and the user is authenticated correctly, anyone knows the reason?

**Comment by claywilkinson** [comment]
Can you share the log?

**Comment by Ralstlin** [comment]
Omw to home, i will paste the log as soon as i replicate it again.

**Comment by Ralstlin** [comment]
`01-27 20:55:05.765: W/Unity(30284): *** [Play Games Plugin DLL] 01/27/17 20:55:05 +00:00 ERROR: GetServerAuthCode requires a webClientId.`

Sigh, I was working on the backend for sometime so when I come back to work in the client, I updated unity and this package to latest.. seems someone forgot to click the setup button on **Google play games > Setup > Android setup** 😃 🌴 

Its working now :D now I will try to work on that another issue I raised to force get a new refresh token 🗡 🐉

**Comment by claywilkinson** [comment]
The plugin has been updated to 0.9.37 which includes a flag to force the refreshing of the auth code.  This causes a re-consent flow for the user to agree to, but it does reset the server so the next time your exchange an auth code for an access token, you'll also get a refresh token.
