### ISSUE TITLE
Can't  login to Gpgs

### ISSUE THREAD

**Issue by flynetstudios** [playgameservices/play-games-plugin-for-unity#1575]
We have a game already published version 103. We uploaded version 104 as alpha, and installed in our device too, both using same key and SH1. We already registered our achivementes and leaderboards in google play developer console, and testers are registered too. We just can't get any gpgs window for login succes or fail, or anything. Any tips ?? We are using this code: 

```
	public void MostrarAchievements()
	{
		if(Social.localUser.authenticated)
		{
			Social.ShowAchievementsUI();
		}

   	}
	public void MostrarLeaderboards()
	{
//		if(Social.localUser.authenticated)
//		{
			//Social.ShowLeaderboardUI();
//		}
		Social.localUser.Authenticate((bool success) => {
		if(success)
		{
			Debug.Log("YES!!!");
		}
		else
		{
			Debug.Log("Nooo");
		}
        // handle success or failure
   		 });
   	}
}

```

**Comment by claywilkinson** [comment]
Can you share a log of trying to authenticate?

**Comment by flynetstudios** [comment]
Sorry, how can i get the log ?? i Just use adb command, that work ?? I just see conection attempt, but no answer. Any other way for get log ?? 

![mwsnap12_07_51](https://cloud.githubusercontent.com/assets/25381918/22381943/3ea102ea-e489-11e6-8433-496354d1b3fb.jpg)

**Comment by seanfcastillo** [comment]
Just a wild guess, maybe try not using the Social class, does it work if you just use
`PlayGamesPlatform.Instance.Authenticate(authCallback)`
instead of `Social.localUser.Authenticate`

and if you really want to use the Social class you have to call `PlayGamesPlatform.Activate();` somewhere before doing so

**Comment by flynetstudios** [comment]
Thanks for your reply. Yes `PlayGamesPlatform.Activate();` is called before in our code, i fogot inlude that part. Unfortunaly `PlayGamesPlatform.Instance. Authenticate` didn't work.

Doing tests I found something interesting ... when I use a new signature, other than the one in the store, I can see a window attempt to connect to Gpgs, which is rejected. When I use the correct signature, the same one that is currently in the store, I can not see anything at all, not even a login attempt. Any theory ??

**Comment by wfowler1** [comment]
I'm not able to log in either. The first time I tried, the window comes up and asks which Google account to use, asks me if I wish to authorize the app (I answer yes), then it just fails.

Here's what I'm getting from logcat, from the beginning of the login flow up until the callback is called.
`02-14 22:52:22.238 30026 30082 I Unity   : Building GPG services, implicitly attempts silent auth
02-14 22:52:22.238 30026 30082 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
02-14 22:52:22.238 30026 30082 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
02-14 22:52:22.238 30026 30082 I Unity   : UnityEngine.Logger:Log(LogType, Object)
02-14 22:52:22.238 30026 30082 I Unity   : UnityEngine.Debug:Log(Object)
02-14 22:52:22.238 30026 30082 I Unity   : GooglePlayGames.Native.NativeClient:InitializeGameServices() (at <snip>\Assets\Plugins\GooglePlayGames\Platforms\Native\NativeClient.cs:199)
02-14 22:52:22.238 30026 30082 I Unity   : GooglePlayGames.Native.NativeClient:Authenticate(Action`1, Boolean) (at <snip>\Assets\Plugins\GooglePlayGames\Platforms\Native\NativeClient.cs:132)
02-14 22:52:22.238 30026 30082 I Unity   : GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at <snip>\Assets\Plugins\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:368)
02-14 22:52:22.238 30026 30082 I Unity   : GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at <snip>\Assets\Plugins\GooglePlayGames\ISocialPlatform\PlayGames
02-14 22:52:22.448 30026 30082 I Unity   :  [Play Games Plugin DLL] 02/14/17 22:52:22 -07:00 DEBUG: Activating PlayGamesPlatform.
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.Logger:Log(LogType, Object)
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.Debug:Log(Object)
02-14 22:52:22.448 30026 30082 I Unity   : GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\Logger.cs:59)
02-14 22:52:22.448 30026 30082 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
02-14 22:52:22.448 30026 30082 I Unity   :
02-14 22:52:22.448 30026 30082 I Unity   : (Filename: E Line: 0)
02-14 22:52:22.448 30026 30082 I Unity   :
02-14 22:52:22.448 30026 30082 I Unity   :  [Play Games Plugin DLL] 02/14/17 22:52:22 -07:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.Logger:Log(LogType, Object)
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.Debug:Log(Object)
02-14 22:52:22.448 30026 30082 I Unity   : GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\Logger.cs:59)
02-14 22:52:22.448 30026 30082 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
02-14 22:52:22.448 30026 30082 I Unity   :
02-14 22:52:22.448 30026 30082 I Unity   : (Filename: E Line: 0)
02-14 22:52:22.448 30026 30082 I Unity   :
02-14 22:52:22.448 30026 30082 I Unity   :  [Play Games Plugin DLL] 02/14/17 22:52:22 -07:00 DEBUG: Creating platform-specific Play Games client.
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.Logger:Log(LogType, Object)
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.Debug:Log(Object)
02-14 22:52:22.448 30026 30082 I Unity   : GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\Logger.cs:59)
02-14 22:52:22.448 30026 30082 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
02-14 22:52:22.448 30026 30082 I Unity   :
02-14 22:52:22.448 30026 30082 I Unity   : (Filename: E Line: 0)
02-14 22:52:22.448 30026 30082 I Unity   :
02-14 22:52:22.448 30026 30082 I Unity   :  [Play Games Plugin DLL] 02/14/17 22:52:22 -07:00 DEBUG: Creating Android IPlayGamesClient Client
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.Logger:Log(LogType, Object)
02-14 22:52:22.448 30026 30082 I Unity   : UnityEngine.Debug:Log(Object)
02-14 22:52:22.448 30026 30082 I Unity   : GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\Logger.cs:59)
02-14 22:52:22.448 30026 30082 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
02-14 22:52:22.448 30026 30082 I Unity   :
02-14 22:52:22.448 30026 30082 I Unity   : (Filename: E Line: 0)
02-14 22:52:22.448 30026 30082 I Unity   :
02-14 22:52:23.508 30026 30082 I Unity   :  [Play Games Plugin DLL] 02/14/17 22:52:23 -07:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
02-14 22:52:23.508 30026 30082 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
02-14 22:52:23.508 30026 30082 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
02-14 22:52:23.508 30026 30082 I Unity   : UnityEngine.Logger:Log(LogType, Object)
02-14 22:52:23.508 30026 30082 I Unity   : UnityEngine.Debug:Log(Object)
02-14 22:52:23.508 30026 30082 I Unity   : GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\Logger.cs:59)
02-14 22:52:23.508 30026 30082 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
02-14 22:52:23.508 30026 30082 I Unity   :
02-14 22:52:23.508 30026 30082 I Unity   : (Filename: E Line: 0)
02-14 22:52:23.508 30026 30082 I Unity   :
02-14 22:52:23.508 30026 30082 I Unity   :  [Play Games Plugin DLL] 02/14/17 22:52:23 -07:00 DEBUG: Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
02-14 22:52:23.508 30026 30082 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
02-14 22:52:23.508 30026 30082 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
02-14 22:52:23.508 30026 30082 I Unity   : UnityEngine.Logger:Log(LogType, Object)
02-14 22:52:23.508 30026 30082 I Unity   : UnityEngine.Debug:Log(Object)
02-14 22:52:23.508 30026 30082 I Unity   : GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\Logger.cs:59)
02-14 22:52:23.508 30026 30082 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
02-14 22:52:23.508 30026 30082 I Unity   :
02-14 22:52:23.508 30026 30082 I Unity   : (Filename: E Line: 0)
02-14 22:52:23.508 30026 30082 I Unity   :
02-14 22:52:23.508 30026 30082 I Unity   :  [Play Games Plugin DLL] 02/14/17 22:52:23 -07:00 DEBUG: there are pending auth callbacks - starting AuthUI
02-14 22:52:23.508 30026 30082 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
02-14 22:52:23.508 30026 30082 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
02-14 22:52:23.508 30026 30082 I Unity   : UnityEngine.Logger:Log(LogType, Object)
02-14 22:52:23.508 30026 30082 I Unity   : UnityEngine.Debug:Log(Object)
02-14 22:52:23.508 30026 30082 I Unity   : GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\Logger.cs:59)
02-14 22:52:23.508 30026 30082 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
02-14 22:52:23.508 30026 30082 I Unity   :
02-14 22:52:23.508 30026 30082 I Unity   : (Filename: E Line: 0)
02-14 22:52:23.508 30026 30082 I Unity   :
02-14 22:52:23.918 30026 30082 I Unity   :  [Play Games Plugin DLL] 02/14/17 22:52:23 -07:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
02-14 22:52:23.918 30026 30082 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
02-14 22:52:23.918 30026 30082 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
02-14 22:52:23.918 30026 30082 I Unity   : UnityEngine.Logger:Log(LogType, Object)
02-14 22:52:23.918 30026 30082 I Unity   : UnityEngine.Debug:Log(Object)
02-14 22:52:23.918 30026 30082 I Unity   : GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\Logger.cs:59)
02-14 22:52:23.918 30026 30082 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
02-14 22:52:23.918 30026 30082 I Unity   :
02-14 22:52:23.918 30026 30082 I Unity   : (Filename: E Line: 0)
02-14 22:52:23.918 30026 30082 I Unity   :
02-14 22:52:23.918 30026 30082 I Unity   :  [Play Games Plugin DLL] 02/14/17 22:52:23 -07:00 DEBUG: AuthState == Unauthenticated calling auth callbacks with failure
02-14 22:52:23.918 30026 30082 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
02-14 22:52:23.918 30026 30082 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
02-14 22:52:23.918 30026 30082 I Unity   : UnityEngine.Logger:Log(LogType, Object)
02-14 22:52:23.918 30026 30082 I Unity   : UnityEngine.Debug:Log(Object)
02-14 22:52:23.918 30026 30082 I Unity   : GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\Logger.cs:59)
02-14 22:52:23.918 30026 30082 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at <snip>\Assets\Plugins\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
02-14 22:52:23.918 30026 30082 I Unity   :
02-14 22:52:23.918 30026 30082 I Unity   : (Filename: E Line: 0)`

We need help with this, it's the last thing blocking our game from launching on Google Play! I've made sure I followed all the steps for setup (twice), made sure the app is published for Alpha testing on the Google Play Developer Console, and all Alpha testers are authorized to use the Games Services. I'm at a complete loss at this point.

**Comment by flynetstudios** [comment]
Try publishing the game services, meaby can help. We can solve our login problem publishing the game srevices. Check your Android manifest files too.

**Comment by wfowler1** [comment]
Game Services is published as well.

**Comment by flynetstudios** [comment]
Inside plugins\android\ look for this files, i had problems with login because some files here was missing.

![mwsnap12_12_07](https://cloud.githubusercontent.com/assets/25381918/23034358/30954414-f441-11e6-9f84-e1672e123284.jpg)

**Comment by wfowler1** [comment]
Which files were missing? The only things I'm missing I think are the Admob stuff (we're using UnityAds instead).
![image](https://cloud.githubusercontent.com/assets/5846565/23090241/946f6e2c-f556-11e6-928d-48f1b6428983.png)

**Comment by claywilkinson** [comment]
OK to close this issue?
