### ISSUE TITLE
<GoogleSignIn/GIDSignIn.h> File not found

### ISSUE THREAD

**Issue by kshankin** [playgameservices/play-games-plugin-for-unity#1578]
Greetings,

I'm getting a _Lexical or Preprocessor Issue_ file not found error for GIDSignIn.h. I have tried the steps suggested in issue [#1009](https://github.com/playgameservices/play-games-plugin-for-unity/issues/1009) as well as other potential solutions in other posts, but I have run into some problems. 

Most of the posts suggest that xcode should be opened using the .xcworkspace file instead of the .xcodeproject file, however, I do not have a .xcworkspace file. Other suggestions include altering and updating the Podfile, but I do not have one of those either. It also appears that the Google libraries are also missing from the project.

I'm going to build my own Podfile and attempt to bring the libraries in that way, but is there something else that should be tried as well?

**Comment by v2k** [comment]
make sure you've gone through these steps:
[building-for-ios](https://github.com/playgameservices/play-games-plugin-for-unity#building-for-ios)

**Comment by kshankin** [comment]
Thanks for the reply @v2k. I followed the steps, however, after running `pod install`, I do not have the .xcworkspace file and the error persists.

**Comment by kshankin** [comment]
After further review, I found that when running `pod install`, I was receiving the error 'Abort trap: 6'. The solution in this [stackoverflow post](http://stackoverflow.com/questions/39980096/xcode8-cocoapods-abort-trap6) allowed the install command to complete successfully and I am now able to build. Thank you for the help 👍
