### ISSUE TITLE
TurnBased Callbacks missing (Android only)

### ISSUE THREAD

**Issue by William-Barry** [playgameservices/play-games-plugin-for-unity#158]
I'm implementing a Turn based game right now and it is working great but there are a few things missing.

After calling TakeTurn the TurnBasedMatch is not updated. It seems like the OnTurnBasedMatchUpdateReceivedListener is not implemented or the UpdateMatchResult (see https://developers.google.com/games/services/android/turnbasedMultiplayer section Taking a Turn). I cannot find the hooks to these in the current release. Are they implemented or are they coming?

This causes an issue; when a player returns to the Lobby and the TurnBasedMatch is not updated it says it is still the same players turn. It also poses a problem when the game is still running after a TakeTurn (and sitting around in the Lobby). Once all other players complete their turn the user will not be notified (in the App) that it is his/her turn (TurnBasedMatch has not been updated or there is no delegate).

Can we please have the following implemented:
- Ability to have an update when a Turn has been made: OnTurnBasedMatchUpdateReceivedListener
- the UpdateMatchResult delegate

These will help develop a better experience for gamers playing a game where they do not have to leave a game.

(If this is already implemented please point me in the right direction so I can implement this in my game).

**Comment by JustinSchneider** [comment]
I've been bashing my head against these OnMatch and OnInvitation delegates for a while, and I keep finding my way back to several threads including this one.

I'm testing on two iOS devices and never receive TB OnMatch or OnInvitation callbacks. Was this issue only fixed for Android? Are other people experiencing problems with these delegates never being called on iOS?

**Comment by Yecats** [comment]
The delegates are being called for me but the match information is not being updated properly. TakeTurn doesn't pass the turn to the next player and the SelfParticipantId is blank. I opened two issues:

https://github.com/playgameservices/play-games-plugin-for-unity/issues/628

https://github.com/playgameservices/play-games-plugin-for-unity/issues/627

**Comment by ariefannur** [comment]
I get same problem can't trigger OnMatch or OnInvitation callbacks. in Android. Do you have any suggestion. ?
