### ISSUE TITLE
Supporting Latest GoogleSignIn for iOS

### ISSUE THREAD

**Issue by sourabhverma** [playgameservices/play-games-plugin-for-unity#1584]
It seems like latest version depends on fairly old GoogleSignIn. Can someone help with using latest google sign in 

Pod installationLine
`Installing GoogleSignIn 2.4.0 (was 4.0.1)`

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html

**Comment by MyOwnClone** [comment]
Will older apps still work when GPGS is being deprecated on iOS? I did not find anything related to old apps in that article.
