### ISSUE TITLE
Quests and Rewards

### ISSUE THREAD

**Issue by OriginalsByToto** [playgameservices/play-games-plugin-for-unity#1586]
Hello,

I'm using this Google Play Games Services plugin, but I can find the methods to accept quests and update events, so that is my question: Where I can use Quests and Rewards?

Thank you in advance

**Comment by claywilkinson** [comment]
Unfortunately, Rewards (Gifts) were never part of this plugin.  Quests are, but it was just announced that Quests are deprecated. https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
