### ISSUE TITLE
.RequireGooglePlus()

### ISSUE THREAD

**Issue by enriqif** [playgameservices/play-games-plugin-for-unity#1588]
Hello.. anyone can tell me what features enable .RequireGooglePlus().?

I want to get the real name and picture from profile data of the users and I wonder wheter this plugin allow me do this.

thanks..

**Comment by claywilkinson** [comment]
[RequireGooglePlus](https://developers.google.com/android/reference/com/google/android/gms/games/Games.GamesOptions.Builder.html#setRequireGooglePlus(boolean)) is used to access the social graph of the player stored in Google+.  The Games API no longer requires players to have a Google+ account, so use of this method is deprecated.

To get the "real" name and picture of the player, you'll need to use the [Google Sign-In API](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInApi), which this plugin does not use.
