### ISSUE TITLE
GoogleSignIn

### ISSUE THREAD

**Issue by abcnm123456** [playgameservices/play-games-plugin-for-unity#1589]
Now, the GoogleSignIn is not support WebView
How i Can Solve it?

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

![whatsapp image 2017-02-02 at 16 59 47](https://cloud.githubusercontent.com/assets/25501502/22542974/5cb6abf6-e969-11e6-9d87-a7f47dc36fd0.jpeg)

**Comment by claywilkinson** [comment]
You need to use the API to sign in, is this an old app?

**Comment by apponepenny** [comment]
what is old app mean?

**Comment by claywilkinson** [comment]
Unfortunately iOS is no longer supported by this plugin: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
