### ISSUE TITLE
Info.plist not configured properly by Play Games postprocessor

### ISSUE THREAD

**Issue by GuillaumZ** [playgameservices/play-games-plugin-for-unity#1590]
When I'm building the Xcode in Unity3D on windows, I get that error : 

```
InvalidOperationException: Could not locate an installation of PlistBuddy!
GooglePlayGames.Editor.PlistBuddyHelper.ForPlistFile (System.String filepath) (at Assets/GooglePlayGames/Editor/PlistBuddyHelper.cs:44)
GooglePlayGames.Editor.GPGSPostBuild.UpdateGeneratedInfoPlistFile (System.String pathToPlist) (at Assets/GooglePlayGames/Editor/GPGSPostBuild.cs:139)
GooglePlayGames.Editor.GPGSPostBuild.OnPostprocessBuild (BuildTarget target, System.String pathToBuiltProject) (at Assets/GooglePlayGames/Editor/GPGSPostBuild.cs:118)
UnityEditor.HostView:OnGUI()
```

Exactly like it is said in this closed issue :  
[Issue 394](https://github.com/playgameservices/play-games-plugin-for-unity/issues/394)
I add at the end of the info.plist generated in the Xcode build :

```
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleURLTypes</key>
    <string>Editor</string>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>com.company.${PRODUCT_NAME}</string>
    </array>
    <key>CFBundleURLName</key>
    <string>com.company.${PRODUCT_NAME}</string>
  </dict>
</array>
```

But wasn't this "play game processor" supposed to fill these paths too ? :  
 ${PRODUCT_NAME} 
${EXECUTABLE_NAME}

I suppose it should, and here comes the real problem : 

I'm filling "product name" myself but I don't know what to fill at "executable_name"
That executable thing is the CFBundleExecutable key and I've got PLENTY OF PROBLEM with that hideous thing when I want to validate my build in Xcode.
example : XCode tells me there's a problem with it, so I tried to delete it (following advices on stackoverflow) but after that, Xcode tells me that the bundle identifier is missing (which is wrong) and some other adventures I won't write here, cause it's too long : it seems like a NEVER ENDING PROBLEM.

So ....
To (possibly) avoid all this mess, how can we make the Play Games postprocessor configure the info.plist properly ?

if that path (wirtten in plistBuddyHelper.cs ) : 
` private const string PlistBuddyPath = "/usr/libexec/PlistBuddy";`
if it isn't right, what can we put here to make the Unity's Xcode build works ?

**Comment by claywilkinson** [comment]
Thanks for information, but unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html.
