### ISSUE TITLE
Social.localUser.id  : different between platforms.

### ISSUE THREAD

**Issue by mind2on** [playgameservices/play-games-plugin-for-unity#1593]
Hi, 

I built a unity multiplatform game for ios and android. 

"Social.localUser.id" returns different value for the same user.

But "Social.localUser.userName" is the same.

Please tell me how to get the same id.

Please help me please...

**Comment by mind2on** [comment]
Please tell me how to get the same ID...

**Comment by claywilkinson** [comment]
I believe you cannot get the same ID.  This is a side-effect of removing the Google+ dependency from Play Game Services.  On iOS, the sign-in process still relies on G+, so in some cases, users will have a different ID.  

If it is really important to you, you can get a server auth code after authenticating, send it to a back-end server application you've written and then use the Web API to get an access token.  If you verify that access token via the web, both ids will be returned.
