### ISSUE TITLE
The type or namespace name `IOSResolver' does not exist in the namespace `Google'

### ISSUE THREAD

**Issue by gnchishti** [playgameservices/play-games-plugin-for-unity#1596]
Hi,

I just updated my google play services plugin to GooglePlayGamesPlugin-0.9.36 and got this error.

Assets/GooglePlayGames/Editor/GPGSDependencies.cs(108,20): error CS0234: The type or namespace name `IOSResolver' does not exist in the namespace `Google'. Are you missing an assembly reference?

any suggestion?

**Comment by gif-** [comment]
hi, I've got the same here, no resolution yet.

**Comment by gnchishti** [comment]
I just commented the line for now

But waiting for solution

**Comment by DJAB1978** [comment]
Same error in Unity (last version) on OSX Sierra here.

After commented out got another errors.

**Comment by makkuzu** [comment]
Restarting Unity solved my problem!

**Comment by gif-** [comment]
this might be related to:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1604#issuecomment-280850233

**Comment by claywilkinson** [comment]
These problems are fixed in 0.9.37 of the plugin.  It contains a newer version of the PlayServicesResolver and is compatible with Firebase plugins. (and also play services 10.2+).
