### ISSUE TITLE
Row count 100 but 25 results

### ISSUE THREAD

**Issue by DutchGuerrillia** [playgameservices/play-games-plugin-for-unity#1597]
Hello fellow developers,

I'm using this code snippet (almost exactly from the front page):

    PlayGamesPlatform.Instance.LoadScores(
            GPGSIds.leaderboard_leaders_in_smoketesting,
            LeaderboardStart.TopScores,
            100,
            LeaderboardCollection.Public,
            LeaderboardTimeSpan.AllTime,
            (data) =>
            {
                mStatus = "Leaderboard data valid: " + data.Valid;
                mStatus += "\n approx:" +data.ApproximateCount + " have " + data.Scores.Length;
            });

I say almost because I changed TopScores instead of PlayerCentered. The default of 100 rows is the same, but at most it returns me 25 score rows. I want to present the 100 on one screen. Do I misunderstand here something or is something goingwrong?

Thanks,
Maarten

**Comment by claywilkinson** [comment]
Even if you ask for 100, the results can be limited by the server, apparently it is limiting to 25.  You can get the next page of scores with something like:
``` void GetNextPage(LeaderboardScoreData data)
    {
        PlayGamesPlatform.Instance.LoadMoreScores(data.NextPageToken, 10,
            (results) =>
            {
                mStatus = "Leaderboard data valid: " + data.Valid;
                mStatus += "\n approx:" +data.ApproximateCount + " have " + data.Scores.Length;
            });
    }
```
Then call that in a loop to get the 100 you want.
