### ISSUE TITLE
unable to resolve virtual method 2551

### ISSUE THREAD

**Issue by nipundavid** [playgameservices/play-games-plugin-for-unity#160]
I had tested the app few days ago now the same app is showing following log in the log
I have tried including androidv4 in baseGameUtil, changed the game play services jar many times ...but nothing ....

07-08 12:23:04.320: I/Unity(25471): [Play Games Plugin DLL] Activating PlayGamesPlatform.
07-08 12:23:04.320: I/Unity(25471):  
07-08 12:23:04.320: I/Unity(25471): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
07-08 12:23:04.460: I/Unity(25471): [Play Games Plugin DLL] PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
07-08 12:23:04.460: I/Unity(25471):  
07-08 12:23:04.460: I/Unity(25471): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
07-08 12:23:04.460: I/Unity(25471): [Play Games Plugin DLL] SetDefaultLeaderboardForUI: CgkIrdm39YMUEAIQAA
07-08 12:23:04.460: I/Unity(25471):  
07-08 12:23:04.460: I/Unity(25471): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
07-08 12:23:04.480: I/Unity(25471): [Play Games Plugin DLL] Creating platform-specific Play Games client.
07-08 12:23:04.480: I/Unity(25471):  
07-08 12:23:04.480: I/Unity(25471): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
07-08 12:23:04.660: I/Unity(25471): [Play Games Plugin DLL] Making sure PlayGamesHelperObject is ready.
07-08 12:23:04.660: I/Unity(25471):  
07-08 12:23:04.660: I/Unity(25471): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
07-08 12:23:04.760: I/Unity(25471): [Play Games Plugin DLL] Initializing Android Client.
07-08 12:23:04.760: I/Unity(25471):  
07-08 12:23:04.760: I/Unity(25471): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
07-08 12:23:04.770: I/Unity(25471): [Play Games Plugin DLL] Creating GameHelperManager to manage GameHelper.
07-08 12:23:04.770: I/Unity(25471):  
07-08 12:23:04.770: I/Unity(25471): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
07-08 12:23:04.790: I/Unity(25471): [Play Games Plugin DLL] Setting up GameHelperManager.
07-08 12:23:04.790: I/Unity(25471):  
07-08 12:23:04.790: I/Unity(25471): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
07-08 12:23:04.800: I/Unity(25471): [Play Games Plugin DLL] GHM creating GameHelper.
07-08 12:23:04.800: I/Unity(25471):  
07-08 12:23:04.800: I/Unity(25471): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
07-08 12:23:04.930: I/Unity(25471): [Play Games Plugin DLL] PlayGamesHelperObject created.
07-08 12:23:04.930: I/Unity(25471):  
07-08 12:23:04.930: I/Unity(25471): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
07-08 12:23:04.930: I/Unity(25471): [Play Games Plugin DLL] GHM calling GameHelper constructor with flags=7
07-08 12:23:04.930: I/Unity(25471):  
07-08 12:23:04.930: I/Unity(25471): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
07-08 12:23:04.940: I/Unity(25471): [Play Games Plugin DLL] AUTH: starting auth process, silent=False
07-08 12:23:04.940: I/Unity(25471):  
07-08 12:23:04.940: I/Unity(25471): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
07-08 12:23:04.960: I/dalvikvm(25471): Could not find method com.google.android.gms.common.api.GoogleApiClient$Builder.addApi, referenced from method com.google.example.games.basegameutils.GameHelper.createApiClientBuilder
07-08 12:23:04.960: W/dalvikvm(25471): VFY: unable to resolve virtual method 2551: Lcom/google/android/gms/common/api/GoogleApiClient$Builder;.addApi (Lcom/google/android/gms/common/api/Api;Lcom/google/android/gms/common/api/GoogleApiClient$ApiOptions;)Lcom/google/android/gms/common/api/GoogleApiClient$Builder;
07-08 12:23:04.960: D/dalvikvm(25471): VFY: replacing opcode 0x6e at 0x0020
07-08 12:23:04.960: I/dalvikvm(25471): Could not find method com.google.android.gms.common.api.GoogleApiClient$Builder.addApi, referenced from method com.google.example.games.basegameutils.GameHelper.createApiClientBuilder
07-08 12:23:04.960: W/dalvikvm(25471): VFY: unable to resolve virtual method 2551: Lcom/google/android/gms/common/api/GoogleApiClient$Builder;.addApi (Lcom/google/android/gms/common/api/Api;Lcom/google/android/gms/common/api/GoogleApiClient$ApiOptions;)Lcom/google/android/gms/common/api/GoogleApiClient$Builder;
07-08 12:23:04.960: D/dalvikvm(25471): VFY: replacing opcode 0x6e at 0x0032
07-08 12:23:04.960: I/dalvikvm(25471): Could not find method com.google.android.gms.common.api.GoogleApiClient$Builder.addApi, referenced from method com.google.example.games.basegameutils.GameHelper.createApiClientBuilder
07-08 12:23:04.960: W/dalvikvm(25471): VFY: unable to resolve virtual method 2551: Lcom/google/android/gms/common/api/GoogleApiClient$Builder;.addApi (Lcom/google/android/gms/common/api/Api;Lcom/google/android/gms/common/api/GoogleApiClient$ApiOptions;)Lcom/google/android/gms/common/api/GoogleApiClient$Builder;
07-08 12:23:04.960: D/dalvikvm(25471): VFY: replacing opcode 0x6e at 0x0044
07-08 12:23:05.120: I/Unity(25471): [Play Games Plugin DLL] GHM setting up GameHelper.
07-08 12:23:05.120: I/Unity(25471):  
07-08 12:23:05.120: I/Unity(25471): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
07-08 12:23:05.130: W/dalvikvm(25471): Unable to match class for part: 'Lcom/google/android/gms/common/api/GoogleApiClient$ApiOptions;)V'
07-08 12:23:05.150: D/GameHelper(25471): GameHelper: Debug log enabled.
07-08 12:23:05.160: I/Unity(25471): [Play Games Plugin DLL] GHM Setting GameHelper options.
07-08 12:23:05.160: I/Unity(25471):  
07-08 12:23:05.160: I/Unity(25471): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
07-08 12:23:05.160: W/dalvikvm(25471): Unable to match class for part: 'Lcom/google/android/gms/common/api/GoogleApiClient$ApiOptions;)V'
07-08 12:23:05.220: W/dalvikvm(25471): Unable to match class for part: 'Lcom/google/android/gms/common/api/GoogleApiClient$ApiOptions;)V'
07-08 12:23:05.470: W/SignalStrength(717): getGsmLevel. this.mGsmSignalBar=4, getGsmSignalStrength()== 12
07-08 12:23:05.470: W/SignalStrength(717): getGsmLevel=4
07-08 12:23:05.470: W/SignalStrength(717): getLevel=4 (SignalStrength: 12 255 -120 -160 -120 -1 -1 99 2147483647 -32767 2147483647 -32767 gsm|lte 4)

**Comment by rudy-munkyfun** [comment]
I am also having this issue

**Comment by nipundavid** [comment]
Hey Sorry, It took me while.

Well all I did was updated the play_game_services lib, and then added in assets.
