### ISSUE TITLE
Build failed using Unity Cloud Build

### ISSUE THREAD

**Issue by Cernji** [playgameservices/play-games-plugin-for-unity#1602]
I'm using Unity Cloud Build for building an iOS version of a game but getting the following error. 

Can't see a way to follow the Cocoapods instructions on Windows.

Building for Android works fine.

![image](https://cloud.githubusercontent.com/assets/17239989/22968309/fc03b7c2-f3bd-11e6-8741-8459cdf2b38a.png)

**Comment by KumoKairo** [comment]
This is the same GIDSignIn.h thing, there are a lot of issues opened (and closed) with this (https://github.com/playgameservices/play-games-plugin-for-unity/issues/745 for one). I'm currently also struggling to make it compile. Completely disabling it on iOS will do for me, but it gives me errors anyways on different stages on the build

**Comment by KumoKairo** [comment]
Trying this https://github.com/playgameservices/play-games-plugin-for-unity/issues/1438

**Comment by Cernji** [comment]
Oh good find. I'll have a look and report my findings. 
Will this still allow Google Play features to work on its?

**Comment by KumoKairo** [comment]
No, it's all about disabling it completely. I tried that and it didn't work btw. What helped though is disabling and re-adding a "NO_GPGS" compiler option, somehow it worked after a few times.

I don't really know about cocoa pods on Unity Cloud - tried searching that with little luck. https://forum.unity3d.com/threads/build-failed-cocoapods.421286/ even says that unity cloud doesn't support pods yet. I think the only way is to try reverting back to some older version of google play games pluging, there was a different way of handling dependencies

**Comment by Cernji** [comment]
Ah nuts.

I'm looking for a way to use Google Play Game Services with Android and iOS using Unity Cloud Build, as I don't have access to a Mac. Have done much of the same Googling as you it seems.

Another option is installing a macOS VM on my PC just for the xcode part and building manually.

**Comment by claywilkinson** [comment]
Unfortunately, GPGS is now deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
