### ISSUE TITLE
Invalid classname: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by kinoke43** [playgameservices/play-games-plugin-for-unity#1603]

**Comment by ESG-Steven** [comment]
I am getting the same thing when using the "Window/Google Play Games/Android/Setup" window. I've filled out all the information correctly and it looks like GPGSDependencies.svcSupport is null during the GPGSAndroidSetupUI.cs

**Comment by c301** [comment]
same problem

**Comment by claywilkinson** [comment]
@c301 - Can you share the log from the console?  What version of the plugin are you using?

**Comment by ESG-Steven** [comment]
@c301 - I solved this issue by letting the Google resolver update the package. I'm in unity and used a right click in the project view. There were menu items that were clearly from Google Play and within them, I eventually found some update functions.

**Comment by claywilkinson** [comment]
Thanks for the update!
