### ISSUE TITLE
Is there a limit to the number of unreliable messages that can be received?

### ISSUE THREAD

**Issue by thidlay** [playgameservices/play-games-plugin-for-unity#1605]
Hello,

I'm working on a realtime multiplayer app that uses unreliable messaging.  It can have up to four players, each of them sending about 60 messages per second to each other.  This means, a single player may receive up to 60*3=180 messages per second.  

Does this sound like a reasonable number? or could there be a slowdown in processing this many messages?

I've seen in some of my games that there are periodic lag spikes, but it could just be network latency.  I just want to make sure it's not due to a slowdown in my app related to processing incoming messages.

Thanks!

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
