### ISSUE TITLE
Crash at authentication, please help me.

### ISSUE THREAD

**Issue by FehrHassan** [playgameservices/play-games-plugin-for-unity#1606]
The Game crashes immediately while executing this line
"PlayGamesPlatform.Instance.localUser.Authenticate((bool success) =>
        {
            if (success) UnityEngine.Debug.Log("signed_in");
            else UnityEngine.Debug.Log("failed");
        });"
this is the error in logcat:

02-20 00:26:28.777: E/Unity(12482): Unable to find AudioPluginMsHRTF
02-20 00:26:28.777: E/Unity(12482): Unable to find AudioPluginOculusSpatializer
02-20 00:26:28.793: D/Unity(12482):  GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shade
02-20 00:26:28.793: D/Unity(12482): r_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_color_buffer_half_float GL_EXT_color_buffer_floa
02-20 00:26:28.793: D/Unity(12482): t GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture
02-20 00:26:31.411: I/Unity(12482): Started
02-20 00:26:31.411: I/Unity(12482):  
02-20 00:26:31.411: I/Unity(12482): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-20 00:26:31.413: I/Unity(12482): Builded
02-20 00:26:31.413: I/Unity(12482):  
02-20 00:26:31.413: I/Unity(12482): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-20 00:26:31.416: I/Unity(12482): Initialized
02-20 00:26:31.416: I/Unity(12482):  
02-20 00:26:31.416: I/Unity(12482): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-20 00:26:31.417: I/Unity(12482): Log Enabled
02-20 00:26:31.417: I/Unity(12482):  
02-20 00:26:31.417: I/Unity(12482): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-20 00:26:31.424: I/Unity(12482): Activated
02-20 00:26:31.424: I/Unity(12482):  
02-20 00:26:31.424: I/Unity(12482): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-20 00:26:31.443: D/GamesUnitySDK(12482): Performing Android initialization of the GPG SDK
02-20 00:26:31.537: I/Unity(12482): Building GPG services, implicitly attempts silent auth
02-20 00:26:31.537: I/Unity(12482):  
02-20 00:26:31.537: I/Unity(12482): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

this is my code:

        Debug.Log("Started");
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().EnableSavedGames().Build();
        Debug.Log("Builded");
        PlayGamesPlatform.InitializeInstance(config);
        Debug.Log("Initialized");
        PlayGamesPlatform.DebugLogEnabled = true;
        Debug.Log("Log Enabled");
        PlayGamesPlatform.Activate();
        Debug.Log("Activated");
        PlayGamesPlatform.Instance.localUser.Authenticate((bool success) =>
        {
            if (success) UnityEngine.Debug.Log("signed_in");
            else UnityEngine.Debug.Log("failed");
        });
        Debug.Log("Authenticated");

The Game is crashing even if there isn't internet connection. so the game is crashing before connecting to the google's server and before authincating with the server.
So please help me.

**Comment by FehrHassan** [comment]
I tried this work around solution, and it works
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1604#issuecomment-280850233

**Comment by abramovks** [comment]
This helped me.

https://github.com/playgameservices/play-games-plugin-for-unity/issues/2217#issuecomment-417619382

Can confirm this works:
open template-AndroidManifest.txt
"\ APP_ID" to "\u003__APP_ID__"
setup GPGS from Unity (press Window/Google Play Services/Setup)



True, after the correction, I received the error "Authentification failed". But it was a problem with SHA-1. It was decided when I did
keytool -exportcert -keystore user.keystore -list -v
And put the correct SHA-1 in https://console.developers.google.com/apis/credentials in the application settings.
