### ISSUE TITLE
Crash on sign in.

### ISSUE THREAD

**Issue by NikolaBo** [playgameservices/play-games-plugin-for-unity#1607]
My game crashes as soon as I try to authenticate the user. I have warnings about com.android.support:support-annotations and com.android.support:support-v4 but in other issues it seems to say this doesn't matter. I have no idea why it crashes or how to check. What could it be?

**Comment by Fragh** [comment]
I had your problem and found this thread, @tolgau got a solution. I did it and worked for me.

https://github.com/playgameservices/play-games-plugin-for-unity/issues/1604

Hope it helps you.

**Comment by enriqif** [comment]
maybe you could use Catlog of Android Studio to get more information what happend inside your app

**Comment by NikolaBo** [comment]
I love you @Fragh and @tolgau. It works. I've been absolutely confused for days but it works now.

**Comment by mcneproj** [comment]
If anyone who see this has this error with Unity you can get needed 10.0.1 aar files from the shared drive folder linked below. You will also see a .unitypackage in there. you just need to delete 10.2.0 play services aar files from Assets/Plugins/Android and then import the package with the 10.0.1 aar files into Unity.
I hope this helps someone save the hours upon hours of trying to find a solution I spent. 
Thank goodness @tolgau gave us a solution.

https://drive.google.com/folderview?id=0B-w9u2zDKrHGUmtjMmk2VDhhSjA
.

**Comment by malisasmaz** [comment]
thanks Fragh tolgau's solution work for me

**Comment by keyserjaya** [comment]
Thank you so much everyone!!! it works. I've confused 48 hours because this..
1 MORE THANK  YOU!!!! \^_^/ \^_^/ \^_^/ \^_^/

**Comment by 3583Bytes** [comment]
Thank you so much, worked for me

**Comment by kostasandre** [comment]
Hello i followed the above steps and now i dont have the app crashing...Although when i try to sign in and the google play console pop up shows while it loads it suddendly closes...Anyone knows the issue?

**Comment by malisasmaz** [comment]
@kostasandre 1.did you attach your android setup 
2. Did you add your e-mail to tester from gpgs panel
3. Did you publish your game servicea from developer panel 
4. If you use main playstore account(which acc you use for developer)  it will be easy for you

**Comment by kostasandre** [comment]
@malisasmaz Can u explain please 1), 3)?
the other two yes

**Comment by malisasmaz** [comment]
1. In Google Play Developer Console-Game Services-Your app- Testing add your phone's playstore account to tester mail
3. In Google Play Developer Console-Game Services-Your app after you define your achievements or leaderboard click resources and copy to unity Window>Google Play Games>Setup>Android Setup copy to resources and click setup

**Comment by powerdrive** [comment]
Hello!
Thanks to mcneproj, but I still can not sign in.
Now app does not crach, but just can't login...
What could it be?

**Comment by kostasandre** [comment]
@malisasmaz  Thanks for you reply.Yes i have rechecked everything,as i said before the app was playing well but when i updated the SDKs it stopped...i followed the solution #1604 and the app was opening again but when the google games pop-up shows it suddenly closes...i have also reset google play games and services on my phone in case that was the problem...

**Comment by kostasandre** [comment]
@powerdrive  i have the same problem did you solve it?

**Comment by powerdrive** [comment]
@kostasandre no

**Comment by powerdrive** [comment]
@kostasandre What version of the unity are you using?

**Comment by germafica** [comment]
I followed the steps from @tolgau, now, my problem is that i can't select the google accounts to sign in! Anyone know the solution?

**Comment by germafica** [comment]
@powerdrive @kostasandre The same problem, I tried with Unity 5.5.2f1 and Unity 5.0.0f4 but there is not functionality difference. When I authenticated, the google games pop-up suddenly closes, just can't login

**Comment by germafica** [comment]
I solved this with #1608 and #1604. My problem was that my OAuth 2.0 had different SHA-1 in my api console. When I changed it with my real SHA-1 from .keystore, i could log in with my google account :D tell me if you solved it like this

**Comment by kostasandre** [comment]
@germafica Thanks for yor reply can u explain please the steps? So i take my SHA1 key from the console as explained on post #1608 then how did you do it?where you make the change from OAuth 2.0 to keystore SHA1(sorry for the noob question i have recently tried on unity).Also because i didnt know what to do, i have deleted my first keystore and the app from the developer console and tried to do it from the beggining but i had the same issues.

**Comment by germafica** [comment]
@kostasandre we don't need to remove anything from anything (Except the steps from @tolgau issu #1604).

Make sure this steps:
1. Make change as @tolgau issu #1604.
2. Go to File > Build Settings > Player Settings from Unity Editor.
3. Go to Publishing Settings > Keystore from Inspector.
4. Create New Keystore. To create it complete 'Keystore password' and 'Confirm password' field. After that, save it with 'Browse Keystore' button on your project folder.
5. Use Existing Keystore. Load keystore file with 'Browse Keystore' button. Complete the available fields.
6. Create an Alias. To create it go to 'Unsigned (debug)' click them and press on 'Create a new key'.
7. Complete Key Creation fields and create key.
8. Select Alias and put own password.
9. Follow the steps @mcneproj from #1608. This is my personal steps:
 - Press SHIFT + Right Click into Unity Project Folder from explorer (not unity editor).
 - Open new command 
 - In cmd type: keytool -list -v -keystore yourkeystorename.keystore.
 - Enter your password.
 - Copy your SHA1.
10. Now we need to paste own SHA1 keystore file to API Console Project.
11. Sign in to your Google Play Developer Console.
12. Click Games services > Select the project. > At the bottom of the Game Details page, click the link to go to the API Console Project. Example: This game is linked to the API console project called "yourprojectname". In the API Console Project, on the left menu, click Credentials.
13. Edit own client OAuth 2.0.
14. And finally paste here own SHA1 keystore file.
15. Ok, save it and now you are available to login :)

**Note:** Let me know if there is something that you don't understand.

**Comment by powerdrive** [comment]
@germafica , I solved this! Thank you very much! I adore you!

**Comment by kostasandre** [comment]
@germafica Thanks man..!!! you re the best...finally it worked..!! thanks for the detailes response, much appreciated.
For those who did the above steps and have issues finding the SHA1 via command window  go to this path C:\Program Files (x86)\Java\jre1.8.0_121\bin and then run command.exe and type:
keytool -list -v -keystore yourprojectpath\mykey.keystore

In addition because i had made a new one i had to rebuilt the project.Unity ->Player Setting-> Publishing settings

**Comment by redi87** [comment]
I confirm that app doesn't crash when I use google play service 11.0.4 and plugin 0.9.39a. I noticed that in newest version 0.9.50 Android Resolver imported 11.0.6 aar files which i couldn't find in gms folder. 

After install 0.9.39a go setup project and build app.

**Comment by SaadAli2016** [comment]
**APP CRASH 2019 FIXED​**
After trying everything turns out its the plugin compatibility problem here is the perfect fix for it.
[https://youtu.be/L-N7Tsw6Jf4](url)
