### ISSUE TITLE
About Keystore

### ISSUE THREAD

**Issue by Fragh** [playgameservices/play-games-plugin-for-unity#1608]
Do i need to set a Keystore, for Google Play Services to work?

**Comment by aamiryatoo** [comment]
Yes its very important to set Keystore  for Android app.

**Comment by mcneproj** [comment]
Also dont forget you will need to get your SHA1 finger print to link your app. 

To do this go to the folder that contains your .keystore file.

Click File>Open New Command Window

In cmd type:
 keytool -list -v -keystore <yourkeystorename>.keystore

That should list your SHA1 fingerprint in the command window. You will need this when linking your app to google play services.

**Comment by JasperDre** [comment]
Also don't forget to save the password and credentials of the .keystore file. If you forget the password or try to create a new keystore the SHA1 fingerprint changes and you won't be able to update the apk in the Google Play store.
