### ISSUE TITLE
Please show the Google Play Games Unity 'Window' menu entry even when not on iOS or Android as build plattform 

### ISSUE THREAD

**Issue by FrankUrbainsky** [playgameservices/play-games-plugin-for-unity#1610]
I changed my unity version and thought that the plugin was no longer working anymore because I did not check if the build target was reset because of the version change. 
Spent way too much time looking to get gpgs working again, when i just should have gotten the information that i need to change the build target to actually access it.

**Comment by claywilkinson** [comment]
Thanks for the suggestion.  Please feel free to create a Pull Request making the change.

**Comment by claywilkinson** [comment]
Fixed in 0.9.40
