### ISSUE TITLE
GetServerAuthCode returns AuthApiAccessForbidden after user reset their google account password.

### ISSUE THREAD

**Issue by OndrishD** [playgameservices/play-games-plugin-for-unity#1611]
Hello,

I am using GetServerAuthCode to verify users when they log in into our application. The flow worked with no problems and as such we proceed to release our game. It went trough google editorial team and they didn't find any issues either. So it seemed that everything is OK. However very soon after the launch SOME users started complain that they cannot use GPGS as login. I found out that issue might be when user changes a password as google revoke all issued tokens. So I tried it myself and indeed right now I am clueless.

After resetting my google account password here is what I get:
1)I had to re-sign in to google play and google games
2)Open the game. Sign up flow work until GetServerAuthCode is called
3)GetServerAuthCode return AuthApiAccessForbidden and null in code parameter

I've tired to 
1)reset all cache in all google apps and remove all data
2)remove account from the phone and add it again
3)restart the phone several times
4)removing/revoking app authorization from the google account and clearing all cache again

Nothing helps, I just cannot get that GetServerAuthCode again.

PLEASE!!!! Does anybody know what can be done or where the problem is? I am running out of options and ideas....

**Comment by alboliv** [comment]
I kinda experienced this like 2 days ago, I am not sure if we have the same situation but what I did is add the 'profile' and 'email' scope in the config like this :

`PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
            .AddOauthScope("profile")
            .AddOauthScope("email")
            .Build();

            PlayGamesPlatform.InitializeInstance(config);

            PlayGamesPlatform.Activate();`

Make sure to add the additional config to your configs, before activating. (if you don't have any config, just place them before you activate).

Anyways.. A little bit of side infos, a few days before I encountered this issue, when I do the Sign in, I could see in my Google Profile the 'scopes' that are allowed was the profile and email stuffs (even without doing the .AddOauthScope thing). but then all of a sudden, after clearing cache and 'allowed apps' in my Google Profile, the scope was just Googe Play, not the email/profile anymore. That's why I had to add the .AddOauthScope.
I am not sure, but there might be some changes happened at Google in the past few days.

**Comment by OndrishD** [comment]
> I kinda experienced this like 2 days ago, I am not sure if we have the same situation but what I did is add the 'profile' and 'email' scope in the config like this :
`PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
.AddOauthScope("profile")
.AddOauthScope("email")
.Build();

@alboliv I did the same thing yesterday after few hours of experimenting. And it worked for me as well. I wanted to be sure that it fixes the problem. So I deleted the fixed version, installed our production app and again it failed. Then after swapping back fixed version with "profile" scope it did succeed. Then I reset my password on google account again. Got back to google play, resign in and go back to the game and it worked . So I would say it is a successful solution BUT I wonder if this is bug in GOOGLE api or it is intended behavior. If it's intended THIS MUST BE MENTIONED in documentation of this plugin:

> If you using server authentication with google play be sure you add "profile" scope otherwise it will fail for some users as AuthServerCode will not be issued and result with "AuthApiAccessForbidden"

I hope this will help some people for now. I had to experience this problem in the worst possible way and time during worldwide featuring on GP.

**Comment by icchoi** [comment]
Settings -> Google -> Play Games -> Sign in to games automatically -> Check

**Comment by OndrishD** [comment]
@icchoi you are actually right! That works as well, although I don't like it as a solution as it requires telling user to go and tick something. It is breaking a flow what should be a smooth and non-problematic login. Asking for such operation might for certain people sounds like a rocket science and they will not bother.

Is there any explanation why does it work ? Is it intended behavior? If yes I would expect some follow up method from google that if we can ask user explicitly to sign in with our app even though he/she has not tick that option. Something like when you asking for email.

What we ultimately did right now is that we signing users up with basic permissions. If that fails and AuthApiAccessForbidden is received we tell them that we just have to restart the game and everything is going to be all right. After next run we enable profile permission before authentication call and it works. It does require more permissions on second run but at least we don't have to instruct them in different languages how to go to the settings and tick that box.

I really hope this will be fixed in the future.

**Comment by claywilkinson** [comment]
The plugin has been updated to work with GoogleSign-In to get the id token, auth code and email.  Rather than adding the scopes directly, you should call requestAuthCode(), or requestIdToken() to get these data items when authenticating.
