### ISSUE TITLE
How can I save the players name to a string? (Unity 5.5.0f3)

### ISSUE THREAD

**Issue by mcneproj** [playgameservices/play-games-plugin-for-unity#1612]
I am wanting to get the players name and save it to a string to display a welcome message. I do not know where to find the information on how to do this. Also if theres a way to display the players avatar that would be good to know. Oh and this is for an android build. If you have any knowledge to share about this it would be much appreciated.

**Comment by Dod2** [comment]
Once logged in, you can just call _PlayGamesPlatform.Instance.localUser.userName_
Check out the functions inside _PlayGamesPlatform.Instance.localUser_, most probably you can get the avatar from there.

**Comment by mcneproj** [comment]
I wrote this and it grabs the players name if they are authenticated, if not it reverts to the default name of Guest. I haven't tested grabbing players avatar though, so idk if it works or not. BUt grabbing the name works fine.

GPGUserProfile.cs

`using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using GooglePlayGames;
using UnityEngine.SocialPlatforms;
using GooglePlayGames.BasicApi;
public class GPGUserProfile : MonoBehaviour {
	public string username;
	public string welcomeMsg;
	public Text nameBox;
	public string userID;
	//public Texture2D profilePic;
	//public Texture2D defaultImage;
	
	void Start () {
		if (PlayGamesPlatform.Instance.localUser.authenticated)
		{
			username = Social.localUser.userName;
            userID = Social.localUser.id;
           // profilePic = Social.localUser.image;
			welcomeMsg = "Welcome " + username + "!";
			nameBox.text = welcomeMsg;
		} else {
			username = "Guest";
			welcomeMsg = "Welcome " + username + "!";
			//profilePic = defaultImage;
			nameBox.text = welcomeMsg;
		}
	}
	
	void Update () {
		if (PlayGamesPlatform.Instance.localUser.authenticated)
		{
			username = Social.localUser.userName;
            userID = Social.localUser.id;
           // profilePic = Social.localUser.image;
			welcomeMsg = "Welcome " + username + "!";
			nameBox.text = welcomeMsg;
		} else {
			username = "Guest";
			welcomeMsg = "Welcome " + username + "!";
			//profilePic = defaultImage;
			nameBox.text = welcomeMsg;
		}
	}
}`
