### ISSUE TITLE
Invitation delegate weird behavior

### ISSUE THREAD

**Issue by Dod2** [playgameservices/play-games-plugin-for-unity#1613]
Hi. 

I've been having trouble with some invitation functionality. I know things are subject to change due to the changes being made to the Play Games system, but I'm still finding different behaviors between different Google Play accounts in my game. 

I have 3 phones with 3 different Google Play accounts.

p1: phone with project owner account
p2: phone with project admin account
p3: phone with some user account

I do register the invitation delegate (.WithInvitationDelegate(OnInvitationReceived)) but only the account on p3 receives the OnInvitationRecieved callback. If I swap the accounts between phone 2 & phone 3, now p2 will receive the callback, but p3 won't. Also if I log in with another normal user account on p1, p1 still won't receive the callback when the invitation arrives but will be able to see the invitation on the invitations UI.

Why does my admin accounts (and some other accounts) do not receive the callback, but this specific account used on p3 does receive the callback regardless of the phone it's signed in?

Other tests include:

p1 & p2 send an invitation to p3.
p3 will always receive the invitations, either it being on the invitations UI (which auto updates with incoming invitations) or in the game view (where it receives the callback)

p3 & p1 send an invitation to p2 while p2 is on the invitations UI. p2 comes back to the game view after the invitations were sent. now, p2 has to wait 10-20 secs on the game view for the invitations to appear on the invitations UI, sometimes the invitations will never arrive.

p3 & p1 send an invitation to p2 while p2 is on the game view.
p2 only has to wait 1-3 secs after invitations were sent for them to appear on its invitations UI, but if p2 opens the invitations UI too quickly and the invitations are not there, p2 will have to wait 10-20 secs on the game view for them to appear in the invitations UI. Again, sometimes the invitation will never arrive if this happens.

p1 will behave just like p2 in the previous cases.
If I swap the google play accounts between p2 & p3, p2 will behave like p3 and vice versa.
If I log in with yet another user account on p1, p1 will still behave just like p2 & previous p1

I have no idea what's going on with this functionality dependant on who is signed.

As of now in order to homogenize the UX, I'm thinking of removing the delegate callback and  InvokeRepeating GetAllInvitations every 5-10 secs while the user is on the versus menu, but this is obviously far from ideal.

Does anyone have any clue on what's going on? Suggestions always welcome. =D

Unity 5.3.6f1, GPG 0.9.36.

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
