### ISSUE TITLE
Leaderboard not updating new high score?

### ISSUE THREAD

**Issue by mcneproj** [playgameservices/play-games-plugin-for-unity#1614]
Hi i have set a high score on my leaderboard, but when trying to update my new highscore the old high score shows on leader board and the new high score is never added. Do i have to delete the old leaderboard score to be able to update with newest high score?

**Comment by AdnanSayyed** [comment]
> Hi i have set a high score on my leaderboard, but when trying to update my new highscore the old high score shows on leader board and the new high score is never added. Do i have to delete the old leaderboard score to be able to update with newest high score?

How did you solve this . I am facing this issue currently
Thanks
