### ISSUE TITLE
Send Message To All at the same time on Reatime Multiplayer

### ISSUE THREAD

**Issue by kostasandre** [playgameservices/play-games-plugin-for-unity#1616]
Hello,
I am making a real-time multiplayer game. 
As i know and have read, you cant send message to all including yourself. So if i want in a room everyone to receive an event like a pop-up message at the same time, whats the best way to do that? 

I have already made one of the participants as host device which should be responsible for the game logic. So,while in game i want to load a question for all the players to see and be able to answer but i have to be sure that everyone will get the question at the same time(internet speed doesn't matter).
Thanks

**Comment by mostdeep123** [comment]
Try Firebase Api on Firebase Analytics, also Unity analytics

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
