### ISSUE TITLE
Message from Google about "Voided Purchases API"?

### ISSUE THREAD

**Issue by TinyTitanAli** [playgameservices/play-games-plugin-for-unity#1618]
We got a message from Google about an updating policy regarding refunds. I'm not sure how to go about using that API.

> Hello Google Play Developer,
> 
> In order to keep Play fair for users and developers, and bring Play in line with the majority of app and game stores in the industry, we are making a change to our developer policy regarding refunds. We will subtract all refunds from developer payouts, not just those made within 48 hours of purchase. The Google Play Developer Distribution Agreement ("DDA") will be updated to reflect this change in the coming months.
> 
> With the same goal in mind, we’ve just launched the Voided Purchases API to help you maintain a fair ecosystem in your app or game.
> 
> With the new API, you can check which users have refunded or charged back in-app purchases in order to claw back those items for that user in your app or game. This change helps to deter abusive behavior and will make the ecosystem fairer for all users.
> 
> We updated the Google Play Developer API terms of service to include the terms governing the use of this new API. By using the new API, you indicate your agreement to these terms.

Should we wait till the author of this plugin to implement the API, or what needs to be done exactly?

**Comment by claywilkinson** [comment]
There are no plans to support the [Void Purchases API](https://developers.google.com/android-publisher/voided-purchases) in the Play Games Services plugin.  This API isn't really designed for being used by a game, correct?

**Comment by zhangleipku** [comment]
I think this API is target at in-app-purchase. And it doesn't matter whether target is games or app. 
And I believe this API is supposed to be used on Server, not client.
