### ISSUE TITLE
How to get real username?

### ISSUE THREAD

**Issue by akira32** [playgameservices/play-games-plugin-for-unity#1619]
I deploy unity project to my android phone. But I see the username always is Lerpz, not the real username.
Does anybody know how to get real data?

My output windows has some warning as below:

Found dependencies:
com.android.support:support-v4 required by (this app)

WARNING: No compatible versions of com.android.support:support-v4 required by (com.google.android.gms:play-services-basement:10.2.0), will try using the latest version 24.0.0
UnityEngine.Debug:Log(Object)

Found dependencies:
com.android.support:support-annotations required by (this app)

WARNING: No compatible versions of com.android.support:support-annotations required by (com.android.support:support-v4:23.1+, com.android.support:support-v4:24.0.0), will try using the latest version 24.0.0

My SDK Manager is the newest:
Android SDK Tools:25.2.5
Android SDK Platform-tools:25.0.3
Android SDK Build-tools:25.0.2
Google Play Services: 39

**Comment by Genoux** [comment]
Are you collecting the `Social.localUser.userName` ?
```
        if (success)
        {
            Debug.Log("Social.localUser.userName"); //User name
        }
```

**Comment by akira32** [comment]
But I add some code as below, I still cannot get username and email.

`            PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
                            .EnableSavedGames()
                                    .Build();

            PlayGamesPlatform.InitializeInstance(config);

            PlayGamesPlatform.Activate();

            Social.localUser.Authenticate((bool success) =>
        {
            if (success)
            {
                print("login success!!");
                print("id=" + Social.localUser.id);
                print("name=" + Social.localUser.userName);

                string email = ((PlayGamesLocalUser)Social.localUser).Email;
                print("email=" + email);

                myText.text = Social.localUser.userName;
            }
        });`

**Comment by Genoux** [comment]
What's the result of Social.localUser.id ?
Any error or something ?

**Comment by akira32** [comment]
the result is "Lerpz"

**Comment by claywilkinson** [comment]
The GPGS plugin only returns the gamer identity, not the real identity.  If you need the real user name, you'll need to integrate Google Sign-In into your application as well.  Note, this is already used by this plugin to get the server auth code and id token.   You could work with that to expose the real user identity.

Feel free to submit a pull request to integrate your changes when they are ready.

**Comment by Nuuk69** [comment]
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.UI;
using UnityEngine.SocialPlatforms;
using UnityEngine.SceneManagement;

public class GoogleUserManager : MonoBehaviour
{
	public Image img;
	public Text displayName;
	
	void Start()
	{
		DoAuthenticate();
	}
	
	
	internal void DoAuthenticate()
    {
        PlayGamesPlatform.Activate();
        PlayGamesPlatform.Instance.ManuallyAuthenticate(OnSignInResult);
    }

    private void OnSignInResult(SignInStatus signInStatus)
    {
        if (signInStatus == SignInStatus.Success)
        {
           	displayName.text = "" + Social.localUser.userName;			
			StartCoroutine(localImage());
        }
        else
        {
            displayName.text = "*** Failed to authenticate with " + signInStatus;
        }

    }
	
		
	IEnumerator localImage()
	{
		Texture2D tex;
		while(Social.localUser.image == null)
		{
			Debug.Log("IMAGE NOT FOUND!");
			yield return null;
		}
	
		tex = Social.localUser.image;
		img.sprite = Sprite.Create(tex, new Rect(0.0f,0.0f,tex.width, tex.height), new Vector2(0f,0f));
		
	}
	 
}

**Comment by Nuuk69** [comment]
not sure if this helps but I get the user image and user name this way works

**Comment by thisisabdullah** [comment]
in my username log it says "Uninitialised" this not my username hot to fix it?

**Comment by Nuuk69** [comment]
it should autofix after 2nd game

**Comment by Nuuk69** [comment]
or they deleted my account... i'm not working on that game anymore sorry,
you should still be able to play x
