### ISSUE TITLE
NOT_AUTHORIZED error when skipping the user selection popup

### ISSUE THREAD

**Issue by Santorayo2** [playgameservices/play-games-plugin-for-unity#1620]
Reproduction steps:
-Login with google play
-Sign Out
-Login again but close the user-selection popup without selecting a user
-Try to signin again

No user selection popup appears but I get the "NOT_AUTHORIZED" error. From this moment on it's not possible to connect to the play services in any way unless you delete the app data. That fixes the problem but is obviously not a real solution. I'd guess that the plugin still tries to login with the first user but has no right to do so after the signout or it's trying to login with a null user when you don't select any.

PS: As the login/signin process normally works I'd expect the app to be configured correctly.

**Comment by claywilkinson** [comment]
Fixed in 0.9.39
