### ISSUE TITLE
Crash with Firebase + play-games-plugin-for-unity

### ISSUE THREAD

**Issue by HoiMinJeong** [playgameservices/play-games-plugin-for-unity#1621]
Hello.

I installed two Plugin.

1st - play-games-plugin-for-unity

2nd - FirebaseMessaging.unitypackage

Here is my Assets\Plugins\Android

![111](https://cloud.githubusercontent.com/assets/26072030/23409709/dd024bd4-fe0f-11e6-83a9-e0a9fd1da9cf.jpg)

if i run and build it , app be crash.

Here is Log.

![22](https://cloud.githubusercontent.com/assets/26072030/23409738/fbde72f8-fe0f-11e6-97fe-90ee1ba64340.jpg)

Please help me.... please.

**Comment by hue1992** [comment]
Update firebase new version

**Comment by HoiMinJeong** [comment]
Thank you. But my Firebase verison is newest. (  firebase_unity_sdk_1.1.0.zip )
