### ISSUE TITLE
Problems with Authentication

### ISSUE THREAD

**Issue by GurosoftGames** [playgameservices/play-games-plugin-for-unity#1622]
Hello!
I Have been problems about google play services.
I have to tried with differents solutions of forum, but don't work.

1r: I 'm using Unity 5.3.4
2n: I 'm using Google Play services 0.9.36

When I import all in my unity empty project. I do the same steps of this link:

http://stackoverflow.com/questions/42457572/unity-google-play-service-plugin-social-localuser-authenticate-app-crash

Because I have problems to run google plays with version 10.2 and I changed all from version 10.0.1

Ok.

When I start my application and I press the button to login.
`using UnityEngine;
using System.Collections;
using UnityEngine.UI;
using GooglePlayGames;
using UnityEngine.SocialPlatforms;
using GooglePlayGames.BasicApi;
//Calse para manipular los Google Play Game Services en Unity
public class GoogleScript : MonoBehaviour {

	//leaderboard strings
	private string idPuntajes = "CgkIoszkg4sHEAIQBA";
	private string idLogro = "idLogro";
	private string idIncremental = "idIncremental";

	// Use this for initialization
	void Start()
	{
		PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder ().Build ();
		PlayGamesPlatform.InitializeInstance(config);
		GooglePlayGames.PlayGamesPlatform.DebugLogEnabled = true;
		PlayGamesPlatform.Activate();
	}

	//Retorna si esta autenticado o no
	public bool Autenticado()
	{
		if (Social.localUser.authenticated)
			return true;
		else
			return false;
	}
	public void Logear()
	{
		Autenticar ();
	}
	//Autentica la usuario
	public bool Autenticar()
	{
		bool exito = false;
		Social.localUser.Authenticate((bool success) =>
			{
				if (success)
				{
					exito = true;
					textL.text = "LOGEADO";
				}
				else
				{
					exito = false;
					textL.text = "ERROR";
				}
			});
		return exito;
	}

Always I get Error and don't login into Google Play. WHY?

I Have an applicacion into google store.

But this applicaion isn't a published. Only "test" aplicacion.

I did all of this link:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1551

But I don't undestand how work the tester email.

I must put the tester email in my devices to test the applicacion with google play? or what?

And if i published the applicacion about "alpha" o "beta" then I could work with  google play services? or What can i do?
thanks

**Comment by yhchun1992** [comment]
Hi, I have the same problem. The play services should work even in alpha or beta, I have mine in beta but it doesn't work. When I try to sign in, the green modal with "<AppName> Connecting to..." "GooglePlay Games" text comes up, then disappears and the callback returns a false. I tried with 2 other people's android phones but they too get the same error. One of them have multiple google accounts and it allows them to pick an account, but still no difference and just keeps failing and I'm not sure why.

**Comment by GurosoftGames** [comment]
Solved!
When the application is in test mode you have to use your "tester gmail" in your devices. Then you can login in google play devices without problems!

**Comment by germafica** [comment]
@GurosoftGames Would you say how are the steps to follow? Becase, when I tried to execute my game into android device, automatically the
application closes. I'm using GooglePlayGamesPlugin-0.9.36 and this is my code:

```c#
using GooglePlayGames;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SocialPlatforms;
using GooglePlayGames.BasicApi;

public class MainGui: MonoBehaviour {
 void Start() {
  PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();
  PlayGamesPlatform.InitializeInstance(config);
  GooglePlayGames.PlayGamesPlatform.DebugLogEnabled = true;
  PlayGamesPlatform.Activate();
 }

 public void Authentication() {
  Social.localUser.Authenticate((bool success) => {
   if (success) {
    Debug.Log("Welcome " + Social.localUser.userName);
   } else {
    Debug.Log("Authentication failed.");
   }
  });
 }

 public void ShowAchievments() {
  Social.ShowAchievementsUI();
 }

 public void Signout() {
  ((PlayGamesPlatform) Social.Active).SignOut();
 }
}
```

**Comment by GurosoftGames** [comment]
you have to remplace all field from Android/puglin/ google-services.
Are an error with version 10.2 you have to remplace from version 10.01 and
then it's solved.
Here are the steps:
http://stackoverflow.com/questions/42457572/unity-google-play-service-plugin-social-localuser-authenticate-app-crash

2017-03-07 22:38 GMT+01:00 germafica <notifications@github.com>:

**Comment by claywilkinson** [comment]
The plugin has been updated to 0.9.37 which works with 10.2.
