### ISSUE TITLE
Crash GooglePlayService & Firebase 

### ISSUE THREAD

**Issue by HoiMinJeong** [playgameservices/play-games-plugin-for-unity#1624]
Hi.

I want sign-in by google account , and FCM.

So I setup GPSP, and Firebase SDK 

GPSP : https://github.com/playgameservices/play-games-plugin-for-unity
Firebase SDK : https://firebase.google.com/docs/unity/setup 

I did set-up GPSP and test sign-in , it was success.

but i set-up Firebase SDK after success to sign-in , 

then my app be crashed on app start.

Here is error log.

I need help. Please help.

-----------------------------------------------------------------------------------
E/GamesNativeSDK: Exception in dalvik/system/DexClassLoader.loadClass: java.lang.IncompatibleClassChangeError: Class com.google.android.gms.games.NativeSdkCallbacks implements non-interface class com.google.android.gms.nearby.connection.Connections$ConnectionRequestListener (declaration of 'com.google.android.gms.games.NativeSdkCallbacks' appears in /data/data/com.test.testapp/app_.gpg.classloader/d75c8e1bbeab9e1ddffb9d332585db71.jar).

A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: RegisterNatives received null jclass

A/art: art/runtime/check_jni.cc:65]     in call to RegisterNatives

A/art: art/runtime/check_jni.cc:65]     from boolean com.unity3d.player.UnityPlayer.nativeRender()

-----------------------------------------------------------------------------------

**Comment by LipeDuoli** [comment]
I have the exact same problem after update to Firebase SDK 10.2.
when execute the code `PlayGamesPlatform.Activate()` the game crash with this same error.

If I not activate the PlayGamesPlataform, the game open with no problem

**Comment by TrentPierce** [comment]
Also having this problem

**Comment by akil-ajax** [comment]
Same problem here.

**Comment by brzostek** [comment]
Same problem here. After updating Firebase to 3.0.0 (SDK 10.2).

**Comment by arcrus** [comment]
Same here.

**Comment by hippogamesunity** [comment]
Same here! My game crashes after update 35 > 36.

**Comment by hippogamesunity** [comment]
As a workaround - revert gpgs to *10.0.1.aar

**Comment by brzostek** [comment]
@hippogamesunity how you revert to 10.0.1? I tired to do so, but project automatically pull 10.2.0 to project. I tried to change gpgs resolver but sill it pull 10.2.0 :(

**Comment by HoiMinJeong** [comment]
@brzostek 

if you want revert , see this.

(But, It still remains some problem)

https://github.com/playgameservices/play-games-plugin-for-unity/issues/1604

1. Menu > Assets > Play Service Resolver > Android Resolver >Setting

2. Turn Off 'Enable Background resolution'

3. Delete all files, name like  'Assets\Plugins\Android\play-services-???.arr'

4. Copy 10.1 arr files to that folder
( You can download files at https://drive.google.com/folderview?id=0B-w9u2zDKrHGUmtjMmk2VDhhSjA )

**Comment by brzostek** [comment]
@hippogamesunity thx. I know i've got files in sdk folder, just missing JAR resolution disabling option. Anyway we need to wait for fix from gpgs plugin team though.

**Comment by HoiMinJeong** [comment]
@brzostek Yes. We need to wait ...

Is there any way we can contact the GPSP team?

**Comment by hippogamesunity** [comment]
@HoiMinJeong, you need https://github.com/claywilkinson

**Comment by fabrantes** [comment]
Same here. The fact that GPG is incompatible with 10.2.0 makes it incompatible with the latest Firebase plugin. Would be nice to get an acknowledgment from the authors and know whether a fix is planned.

**Comment by daFelix** [comment]
@fabrantes Hey fabrantes, thanks for telling that is not compatible with Firebase right now, did you found any temporal solution to that problem? I have the same problem at the moment :(

**Comment by germafica** [comment]
Same problem. When I tried to execute my game into android device, automatically the
application closes. II'm using GooglePlayGamesPlugin-0.9.36 and this is my code:

`void Start() {
 Debug.Log("Welcome to M2");
 PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();
 PlayGamesPlatform.InitializeInstance(config);
 GooglePlayGames.PlayGamesPlatform.DebugLogEnabled = true;
 PlayGamesPlatform.Activate();
}

public void Authentication() {
 Social.localUser.Authenticate((bool success) => {
  if (success) {
   Debug.Log("Welcome " + Social.localUser.userName);
  } else {
   Debug.Log("Authentication failed.");
  }
 });
}

public void ShowAchievments() {
 Social.ShowAchievementsUI();
}

public void Signout() {
 ((PlayGamesPlatform) Social.Active).SignOut();
}`

**Comment by fabrantes** [comment]
@daFelix I think GPS 10.1.0 works so you can downgrade to that, but the authors said that a fix is in the works.

**Comment by daFelix** [comment]
@fabrantes Yea, I managed to login successfully with GPS 10.1.0, but can't manage to authenticate with Firebase plugin, I was referring to if you found any solution to authenticate with firebase. (Sorry for my english)

**Comment by a3dline** [comment]
When about to wait for the plugin update?

**Comment by eklebanski** [comment]
The same here, when is the fix approximate date release?

**Comment by JamhammerRob** [comment]
So glad I found this, have been going nuts the past few days trying to figure this out.

**Comment by felipemmax** [comment]
I am getting crazy too, I can't fix this problem

**Comment by felipemmax** [comment]
the GPS 10.1.0 fixes the GPS, but the firebase dont work

**Comment by HoiMinJeong** [comment]
Me too....

**Comment by mattmeyer** [comment]
I'm also having this issue.

**Comment by jungyunwoo** [comment]
crach here too..

**Comment by alteredgenedev** [comment]
same issue, anybody got a better work around for this that still have both GPGS and firebase work at the same time?

**Comment by gfaraj** [comment]
Ditto, any feedback from plugin authors?

**Comment by claywilkinson** [comment]
This has been fixed in plugin 0.9.37 and confirmed to work with Firebase.

**Comment by gfaraj** [comment]
Awesome, thank you Clay!

**Comment by stolk** [comment]
I'm seeing the same crash, but without using unity and without using firebase:
https://github.com/playgameservices/cpp-android-basic-samples/issues/47
