### ISSUE TITLE
Exclude Play Game Plugins when building to Amazon

### ISSUE THREAD

**Issue by khld85** [playgameservices/play-games-plugin-for-unity#1627]
Hello,

Is there a way to exclude all libraries when building APK for Amazon, something similar to NO_GPGS?

Thanks.

**Comment by claywilkinson** [comment]
Sounds reasonable - Feel free to change the guard check to  
`#if ((UNITY_ANDROID || UNITY_IPHONE) && !NO_GPGS)` and submit a pull request.

**Comment by Deathwing** [comment]
Hey @claywilkinson 
sorry for posting on this old issue, but we have also some problems with it on our App. We use Gradle Build System and on a normal android device everything is fine, but we can't get it done to disable GPGS for Amazon. We tried to change the #if checks everywhere, removed the libGPG's and play-games-support.aar, the dependencies..but still, the app says on start 'this app can't run without play services' (it runs, even after pressing ok, but well the message is still shownn'. Can you tell me what to do exactly to disable PlayServices on Amazon Devices?
Cheers!

**Comment by Deathwing** [comment]
Nevermind...it was because we also integrated firebase....
