### ISSUE TITLE
Disable "Choose an Account" picker after successful authentication

### ISSUE THREAD

**Issue by klodha** [playgameservices/play-games-plugin-for-unity#1628]
Hi all,

After several hours of struggle to run both play services and google analytics plugin together in my game (really painful, specially both services are owned by Google / Android and they can't be compatible to each other :/ ).

Anyways using Social.localUser method to authenticate player and it works properly now. However, right after Google Game Service authentication dialog, I am getting Choose an Account prompt too to pick email address (in each run). While I am not accessing Social.localUser.Email anywhere in my code.

Is there a way to get rid of that dialog?

**Comment by Genoux** [comment]
Maybe try to authenticate in silence, so the login prompt wont show up ?

`PlayGamesPlatform.Instance.Authenticate(ProcessAuthentication, true);`

true for silence mode, false for loud(prompt)

**Comment by klodha** [comment]
I tried the silent method. This hide the dialog of *Google Play Games* (green background dialog and followup of Games account picker). But I still see a black themed dialog similar to one shown in this image https://i.stack.imgur.com/Dvwwl.png (this image is from some StackOverflow post, and I am sharing link just as reference here). The dialog which I am getting is same.

**Comment by claywilkinson** [comment]
The updated plugin 0.9.37 removes the additional account picker when trying to get email or auth tokens.
