### ISSUE TITLE
GoogleSign/GIDsignin.h file not found 

### ISSUE THREAD

**Issue by aammfii** [playgameservices/play-games-plugin-for-unity#1631]
when i build project on ios
GoogleSign/GIDsignin.h file not found  this eror occurs 
i am also add google sign in framework with pod 
how to solve this eror?
![screen shot 2017-03-05 at 1 02 44 am](https://cloud.githubusercontent.com/assets/23666774/23581863/8e880f6a-013f-11e7-98b5-88c6fbee235c.png)

**Comment by yruizw** [comment]
Hi, the steps to solve this issue are documented here https://github.com/playgameservices/play-games-plugin-for-unity/issues/1526
Hope it helps
Yuri

**Comment by claywilkinson** [comment]
Unfortunately GPGS has been deprecated for iOS:https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
