### ISSUE TITLE
`Google.IOSResolver.Enabled' cannot be assigned to (it is read-only)

### ISSUE THREAD

**Issue by yusufyildiz86** [playgameservices/play-games-plugin-for-unity#1632]
Assets/GooglePlayGames/Editor/GPGSDependencies.cs(108,32): error CS0200: Property or indexer `Google.IOSResolver.Enabled' cannot be assigned to (it is read-only)

**Comment by maxxrafen** [comment]
Having the same issue after installing unity Firebase package and the Google Play Games Package. Resolver being used is from the Firebase Package.

**Comment by yusufyildiz86** [comment]
I solved and overcame this issue by commenting out related line and then it worked. This is my solution and it is not official. But my app works very well and it is on the Google Play and Apple Store.

**Comment by claywilkinson** [comment]
Thanks for the tip! The plugin has been updated to 0.9.37 and is confirmed to work with Firebase.

**Comment by yusufyildiz86** [comment]
Thank you very much for information.
