### ISSUE TITLE
EnableSavedGames() blocks the SignIn()

### ISSUE THREAD

**Issue by Boowman** [playgameservices/play-games-plugin-for-unity#1633]
Basically if I have EnabledSavedGames() into the config the sign in fails.

```
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().EnableSavedGames().RequireGooglePlus().Build();
PlayGamesPlatform.InitializeInstance(config);
PlayGamesPlatform.DebugLogEnabled = true;
PlayGamesPlatform.Activate();

Social.localUser.Authenticate((bool success) => 
{
    if (success)
    {
        Debug.Log("Login Successful");
    }
    else
        Debug.Log("Login Failed");
});
```

**RESULT**
Login Failed

**Comment by upln** [comment]
Same problem for me ???? 
without .EnableSavedGames() =>Login succesfull 
With .EnableSavedGames() =>Login Failed

Why ? That is the question !!!!

**Comment by julianosaless** [comment]
@upln and @Boowman You guys can use this workaround to fix this problem!!!

https://github.com/playgameservices/play-games-plugin-for-unity/issues/2429#issuecomment-467866362
