### ISSUE TITLE
IOS crash creating RTMP room.

### ISSUE THREAD

**Issue by Dod2** [playgameservices/play-games-plugin-for-unity#1634]
Hi. Every time i start a real time multiplayer quick match on IOS, ten seconds or so after requesting a match, the game crashes with a SIGABRT signal 6 error. 

This has happened to me like one or two months back, but after some days the error magically disappeared in the very same app installation that was crashing one day before, so went back to Android and forgot about the problem.

Today i returned to IOS to test the changes, and the error reappeared. 

Img of the error with the thread stack:
https://drive.google.com/open?id=0B9psel607qvPWFE1X2RpNTY3bGs

Just in case also the stack with all of the threads (error in thread 69):
https://drive.google.com/open?id=0B9psel607qvPSkxFVjhIR29SQnc

Any idea of what might cause this issue?
Unity 5.4.4f1 
Xcode 8
Play games plugin 0.9.36

**Comment by Dod2** [comment]
Symbolicated exception:

SIGABRT
    /usr/lib/system/libsystem_kernel.dylib ___pthread_kill
    /usr/lib/system/libsystem_pthread.dylib pthread_kill
    /usr/lib/system/libsystem_c.dylib abort
    baikoh gpg::AchievementManager::ShowAllUI(std::__1::function<void (gpg::UIStatus const&)>)
    baikoh Event_Name
    baikoh Event_Name
    baikoh Event_Name
    baikoh gpg::ScoreSummary::CurrentPlayerScore() const
    baikoh buzz::XmlBuilder::~XmlBuilder()
    /usr/lib/system/libsystem_pthread.dylib __pthread_body
    /usr/lib/system/libsystem_pthread.dylib __pthread_start

**Comment by claywilkinson** [comment]
Unfortunately GPGS is deprecated for iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
