### ISSUE TITLE
Not receiving callbacks on IOS

### ISSUE THREAD

**Issue by GorkaIllarra** [playgameservices/play-games-plugin-for-unity#1636]
Hi!
We are having problems using this plugin for a turn based game on IOS. It works perfectly on Android... logs in, sends turns and invitations and receives them from other players. When ported to IOS we can log in and send turns and invitations but match and invitation delegates dont seem to work, they're never launched. We have allowed push notifications and created certificates for them but we could not solve the problem. We can see turns and invitations when using AcceptFromInbox but they are not received ingame nor on our IOS devices (as a notification) when the game is not running. This all works perfectly on Android without changing a single line of code.

We also have tried to do a workaround by periodically retrieving the match list using GetAllMatches... This match list is always out of date and even its our turn (it can be checked on inbox) MatchStatus is always TheirTurn. It seems that instance is never updated since we create it, when we get an updated match list. If we could even update the match list it would be enough to fix this problem...

Anybody has any clue? Any help will be very welcome.

Thanks in advance.

**Comment by GorkaIllarra** [comment]
Still working in a workaround but we are not able to find any fix... we can´t even retrieve an updated match list without doing it through inbox. Do actually match and invitation delegates work on IOS for TBMP?  Maybe is IOS somehow blocking sync with google play services? We are searching for topics referring this issue but seems nobody has achieved to make it work on IOS, at least in turnbased mode.

**Comment by claywilkinson** [comment]
Unfortunately GPGS is deprecated for iOS.
https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
