### ISSUE TITLE
GetServerAuthCode() status InternalError when app is un-pausing; unpause race condition?

### ISSUE THREAD

**Issue by mwk888** [playgameservices/play-games-plugin-for-unity#1637]
We have an intermittent auth error on Android (plugin 0.9.36), it appears to occur when we call GetServerAuthCode() quickly after app un-pauses. Here's a sample log where the GetServerAuthCode() call is 81 ms after Unity's OnApplicationPause(false):

```
17:11:12.155 DEBUG OnApplicationPause False : GveGameController
17:11:12.236 DEBUG MkGoogle.RefreshAccessToken IsAuthenticated True : GveGoogle
 [Play Games Plugin DLL] 03/05/17 12:11:28 -05:00 DEBUG: Invoking user callback on game thread
 [Play Games Plugin DLL] 03/05/17 12:11:28 -05:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
 [Play Games Plugin DLL] 03/05/17 12:11:28 -05:00 DEBUG: Entering internal callback for GameServices#InternalFetchServerAuthCodeCallback
*** [Play Games Plugin DLL] 03/05/17 12:11:28 -05:00 ERROR: Error loading server auth code: ERROR_INTERNAL
```
I've noticed that InternalError occurs only when the log includes the DLL message "Application is pausing..." as above (note that the app is actually unpausing, not pausing). When we call GetServerAuthCode() at other times we do not see that log message and the call succeeds.

My personal guess is that GetServerAuthCode() fails if called when the app is paused, so the call above fails because we are calling before the plugin's unpause code has run. Just a guess though!

Q1: Should  GetServerAuthCode() work when app is paused?

Q2: If not, is it possible to make it work? We've tried workarounds to defer these calls to when app is unpaused but it's unreliable because android sometimes does transient unpause/pause cycles due to device sleep behavior.

Being able to call GetServerAuthCode() while paused would be the cleanest solution for us as this usually happens when we are refreshing expired auth, so the ideal pattern to is to refresh the auth on a background thread and re-try to the server, regardless of whether app is paused.

**Comment by claywilkinson** [comment]
Plugin version 0.9.37 has improved handling of getting authentication tokens and auth codes.  Now the auth code is returned during the authentication flow, so no polling is required.

**Comment by mwk888** [comment]
I'm updating to 0.9.37, API seems nice and clean, thanks!

Q: what is the best way to get a refreshed auth token after initial Authenticate e.g. due to expiration?
- I noticed the forceRefresh flag on builder.RequestServerAuthCode() but I assume it is not right to re- InitializeInstance()
- will another call to Authenticate() with the silent flag refresh the auth token?
- some other approach?

**Comment by claywilkinson** [comment]
The best practice is to pass the auth code to the backendserver, which exchanges the code for an access token and a refresh token.  The server should persist the refresh token so when the access token expires, the refresh token can be used to get a new token.

The force flag on RequestServerAuthCode is used when the server loses the refresh token.  This flag causes the player to re-consent to the token, so its use is discouraged.

You can get a new server auth code every time the player signs in, the only difference is that when it is exchanged for an access token, there will be no refresh token associated with the access token.

**Comment by johnou** [comment]
@claywilkinson what about the case where Google is used as a primary authentication provider and the client passes the google id and one-time use auth code to the server for login? If the client is required to reauthenticate with the server eg. the client to server TCP connection drops what is the best practice / solution? I don't see how exchanging the access token for a refresh token would help the server authenticate a client if they resend the same one-time use auth code, persisting the auth code feels like an awful work-around / hack.

**Comment by johnou** [comment]
@claywilkinson ping

**Comment by johnou** [comment]
@claywilkinson created new issue for tracking my question regarding re-authentication here https://github.com/playgameservices/play-games-plugin-for-unity/issues/1804
