### ISSUE TITLE
Report score and showing a special leaderboard is not working

### ISSUE THREAD

**Issue by powerdrive** [playgameservices/play-games-plugin-for-unity#1638]
Hi all,
After using Social.ReportScore I receive that all is ok. 
But if I use Social.ShowLeaderboardUI() and select my leaderboard than I don't see any results...

If I use ((PlayGamesPlatform)Social.Active).ShowLeaderboardUI(leaderboard) or PlayGamesPlatform.Instance.ShowLeaderboardUI(leaderboard) than it endlessly loads

**Comment by Genoux** [comment]
Can you show the Logcat you get when trying to reach the leaderboard ?

**Comment by powerdrive** [comment]
@Genoux , this?
`03-10 02:31:25.815  1322  2521 I ActivityManager: START u0 {cmp=com.chegames.run
cubicrun/com.google.games.bridge.NativeBridgeActivity (has extras)} from uid 101
88 on display 0
03-10 02:31:25.917  1322  1766 I ActivityManager: START u0 {act=com.google.andro
id.gms.games.VIEW_LEADERBOARD_SCORES dat=version:9877000 flg=0x4000000 pkg=com.g
oogle.android.play.games cmp=com.google.android.play.games/com.google.android.gm
s.games.ui.client.leaderboards.ClientLeaderboardScoreActivity (has extras)} from
 uid 10188 on display 0
03-10 02:31:26.063  1322  1455 I ActivityManager: Displayed com.google.android.p
lay.games/com.google.android.gms.games.ui.client.leaderboards.ClientLeaderboardS
coreActivity: +135ms (total +158ms)`

**Comment by Genoux** [comment]
Do you see the Google leaderboard UI loading, or nothing show at all ?
Try adding some Debug to see where the code run,
Show me a sample of your code, that could help !

Maybe try to check if the player is correctly logged ?

`        if (PlayGamesPlatform.Instance.IsAuthenticated())
        {
//logged, show the leaderboard
            PlayGamesPlatform.Instance.ShowLeaderboardUI("LeaderboardID");
        }
        else
        {
//Not logged
        }`

**Comment by powerdrive** [comment]
I see, that this is trying to load leaderboard UI and that is all...

	public void leaderboardsClick () {
		if (PlayGamesPlatform.Instance.IsAuthenticated())
				PlayGamesPlatform.Instance.ShowLeaderboardUI ("CgkIys2zg60GEAIQCw");
	}

**Comment by Genoux** [comment]
Does the player is logged in ? Did you setup the account in the google play dev console as Beta tester ?

**Comment by powerdrive** [comment]
@Genoux , yes, i see that player is logged in. 
Yes, I tried to setup as Beta tester and Alpha tester, and it did not help.

**Comment by powerdrive** [comment]
I solved this.
I recreated Game Service in dev console, google api and sha1.
But now after sending scores showing leaderboard ui and immediately closes...

**Comment by Genoux** [comment]
If you created a new game service api and sha1, i think you have to create a new Keystore.
the new sha1 doesnt match the old keystore, i think

**Comment by Genoux** [comment]
upload a new APK too, to be sure !

**Comment by powerdrive** [comment]
Also i created a new keystore.
And I uploaded a new APK to dev console

**Comment by powerdrive** [comment]
I made a mistake, I don't solved this... 
After installing the application - a special leaderboard can be opened.
But after sending a record - does not open.

**Comment by powerdrive** [comment]
I solved this.
Just waited and it worked.

**Comment by ankittanwar456** [comment]
hey powerdrive how did you solve it?
