### ISSUE TITLE
Game Crashes When Authenticating

### ISSUE THREAD

**Issue by ekhaled314** [playgameservices/play-games-plugin-for-unity#1639]
The game crashes whenever the user logins in.

Here is the code I use:
`PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();
		PlayGamesPlatform.InitializeInstance(config);
		PlayGamesPlatform.Activate();
		Social.localUser.Authenticate((bool success) => {
			if(success) {
				Social.ReportScore((PlayerPrefs.GetInt("level", 0) * 200) + PlayerPrefs.GetInt("exp", 0), GPGSIds.leaderboard_top_players, (bool successs) => {
					if(successs) {
						PlayGamesPlatform.Instance.ShowLeaderboardUI(GPGSIds.leaderboard_top_players);
					}
					else {
					}
				});
			}
			else {
			}
		});`

**Comment by eklebanski** [comment]
Probably the same issue as #1629

**Comment by ekhaled314** [comment]
OK, thank you.

Checking it now.

Will update soon.

**Comment by claywilkinson** [comment]
There will be an update to the plugin this week to fix the problems working with play-services 10.2.  Closing this issue as a duplication of #1604
