### ISSUE TITLE
NullReferenceException due to null room in UpdateRoom

### ISSUE THREAD

**Issue by tcossairt** [playgameservices/play-games-plugin-for-unity#164]
Happens randomly -- two clients connecting to setup a match.   Both hang for about 15 secs and one spits out this:

I/Unity   (14489): NullReferenceException: Object reference not set to an instance of an object
I/Unity   (14489):   at GooglePlayGames.Android.AndroidRtmpClient.UpdateRoom () [0x00010] in c:\myUnityProj\Assets\GooglePlayGames\Platforms\Android\AndroidRtmpClient.cs:446
I/Unity   (14489):   at GooglePlayGames.Android.AndroidRtmpClient.OnRoomCreated (Int32 statusCode, UnityEngine.AndroidJavaObject room) [0x0005b] in c:\myUnityProj\Assets\GooglePlayGames\Platforms\Android\AndroidRtmpClient.cs:630
I/Unity   (14489):   at GooglePlayGames.Android.AndroidRtmpClient+RoomUpdateProxy.onRoomCreated (Int32 statusCode, UnityEngine.AndroidJavaObject room) [0x00000] in c:\myUnityProj\Assets\GooglePlayGames\Platforms\Android\AndroidRtmpClient.cs:938
I/Unity   (14489):   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000d0] in /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/Mon
oMethod.cs:222

**Comment by claywilkinson** [comment]
This is obsolete since the newer plugin is architected differently.
