### ISSUE TITLE
Can not suppress window: Android Jar Dependencies: 'Replace *.aar* 10.0.1 with version 10.2.0'

### ISSUE THREAD

**Issue by krso92** [playgameservices/play-games-plugin-for-unity#1640]
I can not use [this](http://answers.unity3d.com/questions/1123260/android-jar-dependencies-popup.html) solution because there is no **Assets > Play Services Resolver > Android Resolver** folder in my project. How can I suppress this popup window(s). It appears on every build/reimport and when I start game in play mode. It is really annoying, please help.

I am using version 0.9.36

**Comment by QuentinGaspard** [comment]
Right click in Assets folder -> Play Services Resolver -> Android Resolver:

Uncheck "Enable Background resolution".

**Comment by krso92** [comment]
It solves it. I can not beleive i have not found that. Thanks
