### ISSUE TITLE
Leader Board Not showing

### ISSUE THREAD

**Issue by seifeddine** [playgameservices/play-games-plugin-for-unity#1642]
hi ,

at first i had the issue of 10.2.0 version and i couldn't login then i fixed it by downgrading to version 10.1.0 .
I can login but when i hit the Leaderboard GUI button who's supposed to execute : ((PlayGamesPlatform)Social.Active).ShowLeaderboardUI (leaderboardID);  Nothing happens !! 
I have configured the googleplay service console and added a beta tester e mail etc . 
i don't know why it isn't working ! any suggestions please ?

**Comment by Boowman** [comment]
Do you get any errors what so ever?
Also make sure you are logged in properly, do you get the notification that shows your name and level when you star the app?

**Comment by seifeddine** [comment]
Well , i have checked with android debug and I'm getting connection failed log message so the problem that I'm not able to connect ( I don't get notification with name and level )

**Comment by Boowman** [comment]
Then you are probably not logging in and that's why you can't see that. Where you initialise/activate google plays and you sign it, do you have EnableSavedGames?

**Comment by seifeddine** [comment]
I'm not using EnableSavedGames here is my code of on start and Login functions : 

`#region PUBLIC_VAR
       //Leader board id
	public string leaderboard; 
	#endregion
	#region DEFAULT_UNITY_CALLBACKS
	void Start ()
	{
		//  for debugging:
		PlayGamesPlatform.DebugLogEnabled = true;

		// Activate the Google Play Games platform
		PlayGamesPlatform.Activate ();
	}
	#endregion
	#region BUTTON_CALLBACKS

	/// Login In Into Your Google+ Account
	public void LogIn ()
	{
		     if(PlayGamesPlatform.Instance.IsAuthenticated())
			Debug.Log ("Already Logged");
		
		else
			PlayGamesPlatform.Instance.Authenticate((bool success)=>{
				
				if (success) {
					Debug.Log ("Login Sucess");
				} else {
					Debug.Log ("Login failed");
				}
			});
		}`

**Comment by Boowman** [comment]
Try this

`    private void Awake ()
    {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();
        PlayGamesPlatform.DebugLogEnabled = true;
        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.Activate();

        SigningIn();
    }

    private void SigningIn()
    {
        Social.localUser.Authenticate((bool success) =>
        {
            if (success)
            {
                Debug.Log("LoadMenu: Login Successful");
            }
            else
            {
                Debug.Log("LoadMenu: Login unsuccessful");
            }
        });
    }`

**Comment by seifeddine** [comment]
Okey thanks i will try it and get back with results

**Comment by seifeddine** [comment]
Same Thing man XD "LoadMenu: Login unsuccessful" .. this is driving me crazy "--

**Comment by Boowman** [comment]
Are you running it in the editor or do you have a console that you use on your phone?

**Comment by seifeddine** [comment]
I have noticed this message also : [Play games Plugin DLL] ... Starting Auth Transition, Op Sign In Status :ERROR Not Authorized

**Comment by seifeddine** [comment]
i'm using my phone with android device manager for debug

**Comment by Boowman** [comment]
Oh ok, did you add yourself as tester, if yes make sure you installed it on the right account in case you have multiple on your phone.

**Comment by seifeddine** [comment]
Yes i did it :'(((

**Comment by Boowman** [comment]
Did you set it up Window -> Google Play Games -> Setup -> Android Setup ?

**Comment by Boowman** [comment]
Also is your app publishes, double check in case you forgot to publish it after saving or something like that.

**Comment by seifeddine** [comment]
i'm going to delete the app from google play service console and create a new one some people fixed it by doing that ..

**Comment by seifeddine** [comment]
FINAAAALLLLYYYYY it works now ... after deleting the old googleplayservice app in the console and adding a new app .. idk why but it works .. thanks man for your time :D
