### ISSUE TITLE
RealTimeMultiplayer - ShowWaitingRoomUI() causes Invalidoperationexception: Attempted to use object

### ISSUE THREAD

**Issue by fighder** [playgameservices/play-games-plugin-for-unity#1645]
This error pops up maybe every three or five times I try to start a multiplayer game, and the error points to started from ShowWaitingRoomUI(). The error occurs after the room connected successfully.

I connect the game with a quick match with the code from the documentation, then I show the waiting room just like the documentation. After, upon successful room connection, I will use my first sendmessagetoall(). I suspect this might be have something to do with it but I am not sure. This similar issue occurred here as well:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1510

Please respond with at least the explanation of what this error means, there is no comment in the code.
Thanks

**Comment by claywilkinson** [comment]
Can you share a log?

**Comment by fighder** [comment]
It hasn't happened recently, and it is not something I can reproduce.

**Comment by BuKuSiShen** [comment]
@claywilkinson I these two days have also met this question when i first call RealTime.SendMessageToAll(reliable, message); # InvalidOperationException: Attempted to use object after it was cleaned up #

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
