### ISSUE TITLE
Configuring New Projects with GPGS

### ISSUE THREAD

**Issue by stigmawall** [playgameservices/play-games-plugin-for-unity#1646]
Hi everyone, I'm trying to achieve a solution to a configuration problem (not a bug).

I have a default project where I use a GPGS library and a GPGS Controller class. When I open the project in a new PC I know I need to configure GPGS in the menu bar. BUT my GPGS Controller class gives me an error in the LeaderboardScoreData class. I understand that error occurs because GPGS was not properly configured yet, but with this error the config menu does not appear, and I can't configure until I comment my class. There is something I could do to ignore these errors until the project are ready to be configured? Something like that unity global vars like "if UNITY_ANDROID"?

Thanks.

**Comment by claywilkinson** [comment]
What is the error?  There should be #if UNITY_ANDROID guarding all the classes in this plugin

**Comment by stigmawall** [comment]
Indeed, that's what I did and works. Actually, I used #if UNITY_ANDROID || UNITY_IOS inside all methods in my class. Thanks
