### ISSUE TITLE
After Social.localUser.Authenticate, GetAccessToken return empty

### ISSUE THREAD

**Issue by DengyiLai** [playgameservices/play-games-plugin-for-unity#1648]
My unity version is 4.7.2. After I call 

Social.localUser.Authenticate((bool success) =>
{
	if (success)
	{
		_getAccessTokenFlag = true;
		PlayGamesPlatform.Instance.GetAccessToken();
		PlayGamesPlatform.Instance.GetUserEmail();
	}
	else
	{
		if (_currentCallback != null)
		{
			_currentCallback(null);
		}
		Destroy(_googleInstance);
	}
});

There's nothing happen anymore. Neither true nor false. How to fix this problem?

I have set testing email in google play developer console.

I find a message in log : GoogleApiClient must be connected.

**Comment by claywilkinson** [comment]
Can you share a log?

**Comment by DengyiLai** [comment]
I'm sorry. I fix some error code in my project. The problem now is I can't get any user information except userId. I need accessToken and userEmail.

**Comment by claywilkinson** [comment]
The accessToken is no longer available from GoogleSign-In.  You'll need to use an authcode to send to your backend server to exchange for an accessToken, or use an id token for the user.

The updated plugin 0.9.37 handles getting these values correctly.
