### ISSUE TITLE
Supporting play services 10.2.0

### ISSUE THREAD

**Issue by fabrantes** [playgameservices/play-games-plugin-for-unity#1662]
Can we get any news on when 10.2.0 is going to be supported so we can adjust our launch plans? At this point this is blocking us so it would be nice to know what is the timeline for the fix.

**Comment by eklebanski** [comment]
Thumbs up for that one. How many weeks do we still have to wait? No approximate date, no estimation, no feedback.. seriously?

**Comment by buckbim** [comment]
I'm totally disappointed about how work of Google Team with this plugins.We really need fix version 10.2.0 but don't have anything feedback.

**Comment by claywilkinson** [comment]
Fix is coming this week.  Closing this one as a dup of #1604.
