### ISSUE TITLE
Sign In Not Working Since Full Release

### ISSUE THREAD

**Issue by IndiEire** [playgameservices/play-games-plugin-for-unity#1664]
The Game was working fine signing in and cloud saving until the game was published yesterday.. as soon as it published the sign in stopped working.

**Comment by claywilkinson** [comment]
Can you get a log from not being able to sign in?  Did you change the game configuration on the Play Developer Console to published also?  Did you sign the published APK with a different key?  If so, you need to add the new key's SHA1 and the package id to the API credentials for the app.

**Comment by IndiEire** [comment]
Hey I'm really sorry I got it fixed there was something wrong with the
signature on the developer console but I got it fixed. It wasn't using the
release key it was still on the beta..

I was meant to post and say I sorted it sorry.
