### ISSUE TITLE
Why multiplayer automatch never adds more than 2 players ?

### ISSUE THREAD

**Issue by vivek-code** [playgameservices/play-games-plugin-for-unity#1665]
When I set min opponents to 2 it always starts match with 2 players,
When I set min opponents to 3 it shows opponents in waiting room only when the users available are 3, if two users are available it doesn't even add them to the waiting room.
And Onpeerconnected is never called.

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
