### ISSUE TITLE
Move from waitingroom into gameroom through code?

### ISSUE THREAD

**Issue by n00ben** [playgameservices/play-games-plugin-for-unity#1667]
Hello all,

Not so much of an issue but a question:

I'm having trouble with getting a 3 player game going. When I set max players to 3 but minimum to 2, the game will always start once the minimum is reached.

How would I control the logic through code and start the game manually? Lets say I set minimum players to 3 so that the game does not auto start with 2 players, is there a built in method to move players from the waitingroom into the game room?

Also how would I disallow future connections to this room?

I would need to control this in case a 3rd player is never found and I have to move on with a 2 player game.

Thank you.

**Comment by cjbonn** [comment]
It will always proceed with the minimum number of players, based on what a developer said a while ago. This, plus the extreme lack of unity integration against the actual features of the service/api is what led me to drop Google Play altogether in lieu of GameSparks. Best switch I've made.

**Comment by htsoft** [comment]
@cjbonn thank you, I will also check GameSparks for my next game, actually I'm having big troubles with the Google Play Games Services plugin and I'm looking for a cross platform framework.

**Comment by claywilkinson** [comment]
OK to close this issue?  @cjbonn  - I'd love to hear more about your experiences with respect to switching. Thanks!
