### ISSUE TITLE
crash when i call Authenticate method

### ISSUE THREAD

**Issue by green4you** [playgameservices/play-games-plugin-for-unity#1668]
in unity 5.5.0f3, Authenticate is crash

**Comment by siadark** [comment]
same here

**Comment by mfburn** [comment]
same after update to 5.6

**Comment by claywilkinson** [comment]
Not much to go on, can you share a log ?

**Comment by siadark** [comment]
found a workaround for this issue (tested already):
#1604

**Comment by claywilkinson** [comment]
Thanks for responding.  There will be an updated version of the plugin to work with 10.2 this week.  Closing this issue as a dupe of #1604.
