### ISSUE TITLE
App is crashing @ PlayGamesPlatform.Instance.localUser.Authenticate(mAuthCallBack);

### ISSUE THREAD

**Issue by AbhayaAgrawal1** [playgameservices/play-games-plugin-for-unity#1669]
my code is this:

 void Start()
    {
       
        mAuthCallback = (bool success) =>
        { 
            Debug.Log("inside m auth callback");
            EndStandBy();
            if (success && !mInMatch)
            {
                SwitchToMain();
            }
            else
            {
                Debug.Log("Failed to auth");
            }
        };

        Debug.Log("Not Died @ 33");
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
                                          .WithInvitationDelegate(OnGotInvitation)
                                            .WithMatchDelegate(OnGotMatch)
                                             .RequireGooglePlus()
                                            .Build(); 
        Debug.Log("not Died @ 45");
        PlayGamesPlatform.InitializeInstance(config);

        PlayGamesPlatform.DebugLogEnabled = true;

        // make Play Games the default social implementation
        Debug.Log("not Died @ 48");
        PlayGamesPlatform.Activate();
        Debug.Log("not Died @ 50");

        if (mAuthOnStart)
        { 
            Debug.Log("not Died @ 54");
            SetStandBy("Please wait...");
            Debug.Log("not Died @ 56: " + mAuthCallback);

            //Social.localUser.Authenticate(mAuthCallback);

            PlayGamesPlatform.Instance.localUser.Authenticate(mAuthCallback);
            Debug.Log("not Died @ 58");
        }
    }

Here are the logs:

I/Unity   (23516): Not Died @ 33
I/Unity   (23516):  
I/Unity   (23516): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
I/Unity   (23516): 
I/Unity   (23516): not Died @ 45
I/Unity   (23516):  
I/Unity   (23516): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
I/Unity   (23516): 
I/Unity   (23516): not Died @ 48
I/Unity   (23516):  
I/Unity   (23516): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
I/Unity   (23516): 
I/Unity   (23516): not Died @ 50
I/Unity   (23516):  
I/Unity   (23516): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
I/Unity   (23516): 
I/Unity   (23516): not Died @ 54
I/Unity   (23516):  
I/Unity   (23516): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
I/Unity   (23516): 
I/Unity   (23516): opening text
I/Unity   (23516):  
I/Unity   (23516): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
I/Unity   (23516): 
I/Unity   (23516): not Died @ 56: System.Action`1[System.Boolean]
I/Unity   (23516):  
I/Unity   (23516): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
I/Unity   (23516): 
I/Unity   (23516): Building GPG services, implicitly attempts silent auth
I/Unity   (23516):  
I/Unity   (23516): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
I/Unity   (23516): 
I/ActivityManager(  864): Process com.juegostudios.testIAP (pid 23516) has died
W/ActivityManager(  864): Force removing ActivityRecord{14786498 u0 com.juegostudios.testIAP/com.unity3d.player.UnityPlayerActivity t2742}: app died, no saved state
V/ActivityManager(  864): Display changed displayId=0
I/ActivityManager(  864): Config changes=480 {1.0 ?mcc?mnc en_IN ?layoutDir sw360dp w360dp h566dp 240dpi nrml port finger -keyb/v/h -nav/h s.176?spn}
I/ActivityManager(  864): Start proc 23669:com.android.vending/u0a34 for service com.android.vending/com.google.android.finsky.services.ContentSyncService
I/ActivityManager(  864): Start proc 23704:com.google.process.gapps/u0a16 for content provider com.google.android.gsf/.gservices.GservicesProvider
I/ActivityManager(  864): Killing 23400:com.google.android.apps.photos/u0a100 (adj 15): empty #7
I/ActivityManager(  864): Killing 23184:com.google.android.googlequicksearchbox:search/u0a43 (adj 15): empty #7

**Comment by green4you** [comment]
yes it is
this is a stupid bug I think
and never fixed it in 1 month

**Comment by claywilkinson** [comment]
Can you share the full log?  It looks there are errors missing?

**Comment by AbhayaAgrawal1** [comment]
04-04 17:17:00.615  1430  2438 W ActivityManager: Sending non-protected broadcast com.android.action.NETWORK_POLICY_UPDATE from system 3204:com.miui.networkassistant.deamon/1000 pkg com.miui.securitycenter. Callers=
04-04 17:17:00.875  1430 27442 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.svizzera.candycube cmp=com.svizzera.candycube/com.unity3d.player.UnityPlayerActivity} from uid 10026 on display 0
04-04 17:17:00.977  1430  2613 I ActivityManager: Start proc 14229:com.svizzera.candycube/u0a365 for activity com.svizzera.candycube/com.unity3d.player.UnityPlayerActivity
04-04 17:17:00.978  1430  2613 E ActivityManager: Invalid thumbnail dimensions: 0x0
04-04 17:17:00.988  1430  1535 W ActivityManager: Unable to start service Intent { act=android.intent.action.PACKAGE_FIRST_LAUNCH pkg=com.xiaomi.market (has extras) } U=0: not found
04-04 17:17:01.287  1430  2477 I ActivityManager: Config changes=480 {1.0 405mcc861mnc [en_IN] ldltr sw360dp w640dp h340dp 480dpi nrml long land finger -keyb/v/h -nav/h s.68 themeChanged=0 themeChangedFlags=0}
04-04 17:17:02.057  1430  1511 I ActivityManager: Displayed com.svizzera.candycube/com.unity3d.player.UnityPlayerActivity: +1s109ms
04-04 17:17:02.064  1430  1482 I ActivityManager: Killing 13821:com.android.printspooler/u0a85 (adj 906): empty #17
04-04 17:17:02.350  1430  2616 D ActivityManager: cleanUpApplicationRecord -- 13821
04-04 17:17:02.359 14229 14247 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_multisampled_render_to_texture GL_OES_sha
04-04 17:17:02.359 14229 14247 D Unity   : der_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_i
04-04 17:17:02.359 14229 14247 D Unity   : nitializers
04-04 17:17:08.305 14229 14247 I Unity   : Not Died @ 33
04-04 17:17:08.305 14229 14247 I Unity   : 
04-04 17:17:08.305 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.305 14229 14247 I Unity   :
04-04 17:17:08.309 14229 14247 I Unity   : not Died @ 45
04-04 17:17:08.309 14229 14247 I Unity   : 
04-04 17:17:08.309 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.309 14229 14247 I Unity   :
04-04 17:17:08.314 14229 14247 I Unity   : not Died @ 48
04-04 17:17:08.314 14229 14247 I Unity   : 
04-04 17:17:08.314 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.314 14229 14247 I Unity   :
04-04 17:17:08.327 14229 14247 I Unity   : not Died @ 50
04-04 17:17:08.327 14229 14247 I Unity   : 
04-04 17:17:08.327 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.327 14229 14247 I Unity   :
04-04 17:17:08.327 14229 14247 I Unity   : not Died @ 54
04-04 17:17:08.327 14229 14247 I Unity   : 
04-04 17:17:08.327 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.327 14229 14247 I Unity   :
04-04 17:17:08.328 14229 14247 I Unity   : opening text
04-04 17:17:08.328 14229 14247 I Unity   : 
04-04 17:17:08.328 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.328 14229 14247 I Unity   :
04-04 17:17:08.331 14229 14247 I Unity   : not Died @ 56: System.Action`1[System.Boolean]
04-04 17:17:08.331 14229 14247 I Unity   : 
04-04 17:17:08.331 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.331 14229 14247 I Unity   :
04-04 17:17:08.517 14229 14247 I Unity   : Building GPG services, implicitly attempts silent auth
04-04 17:17:08.517 14229 14247 I Unity   : 
04-04 17:17:08.517 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.517 14229 14247 I Unity   :
04-04 17:17:08.978 14310 14310 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-04 17:17:08.979 14310 14310 F DEBUG   : Build fingerprint: 'Xiaomi/gemini/gemini:7.0/NRD90M/V8.2.1.0.NAAMIEB:user/release-keys'
04-04 17:17:08.979 14310 14310 F DEBUG   : Revision: '0'
04-04 17:17:08.979 14310 14310 F DEBUG   : ABI: 'arm'
04-04 17:17:08.979 14310 14310 F DEBUG   : pid: 14229, tid: 14247, name: main  >>> com.svizzera.candycube <<<
04-04 17:17:08.979 14310 14310 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
04-04 17:17:08.986 14310 14310 F DEBUG   : Abort message: 'art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: java_class == null'
04-04 17:17:08.986 14310 14310 F DEBUG   :     r0 00000000  r1 000037a7  r2 00000006  r3 00000008
04-04 17:17:08.987 14310 14310 F DEBUG   :     r4 eba00978  r5 00000006  r6 eba00920  r7 0000010c
04-04 17:17:08.987 14310 14310 F DEBUG   :     r8 00000000  r9 f2dea56c  sl 000008e6  fp f2dafeef
04-04 17:17:08.987 14310 14310 F DEBUG   :     ip 0000000b  sp eb9fe998  lr f47512c7  pc f4753b48  cpsr 200f0010
04-04 17:17:09.005 14310 14310 F DEBUG   :
04-04 17:17:09.005 14310 14310 F DEBUG   : backtrace:
04-04 17:17:09.010 14310 14310 F DEBUG   :     #00 pc 00049b48  /system/lib/libc.so (tgkill+12)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #01 pc 000472c3  /system/lib/libc.so (pthread_kill+34)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #02 pc 0001d565  /system/lib/libc.so (raise+10)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #03 pc 000190b1  /system/lib/libc.so (__libc_android_abort+34)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #04 pc 00017114  /system/lib/libc.so (abort+4)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #05 pc 00317a35  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+252)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #06 pc 000b46f9  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+864)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #07 pc 002378d5  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1664)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #08 pc 00237b3b  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+66)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #09 pc 0025de05  /system/lib/libart.so (_ZN3art3JNI21RegisterNativeMethodsEP7_JNIEnvP7_jclassPK15JNINativeMethodib+2208)
04-04 17:17:09.012 14310 14310 F DEBUG   :     #10 pc 0027b191  /system/lib/libart.so (_ZN3art3JNI15RegisterNativesEP7_JNIEnvP7_jclassPK15JNINativeMethodi+12)
04-04 17:17:09.012 14310 14310 F DEBUG   :     #11 pc 0009221b  /data/app/com.svizzera.candycube-1/lib/arm/libgpg.so
04-04 17:17:09.012 14310 14310 F DEBUG   :     #12 pc 00092e37  /data/app/com.svizzera.candycube-1/lib/arm/libgpg.so
04-04 17:17:09.012 14310 14310 F DEBUG   :     #13 pc 000933dd  /data/app/com.svizzera.candycube-1/lib/arm/libgpg.so
04-04 17:17:09.012 14310 14310 F DEBUG   :     #14 pc 0008dc69  /data/app/com.svizzera.candycube-1/lib/arm/libgpg.so (_ZNK3gpg28AndroidPlatformConfiguration5ValidEv+76)
04-04 17:17:09.013 14310 14310 F DEBUG   :     #15 pc 00053441  /data/app/com.svizzera.candycube-1/lib/arm/libgpg.so (_ZN3gpg12GameServices7Builder6CreateERKNS_28AndroidPlatformConfigurationE+40)
04-04 17:17:09.014 14310 14310 F DEBUG   :     #16 pc 000c73dd  /data/app/com.svizzera.candycube-1/lib/arm/libgpg.so (GameServices_Builder_Create+16)
04-04 17:17:09.014 14310 14310 F DEBUG   :     #17 pc 0000fbbc  <anonymous:d2370000>
04-04 17:17:10.426  1430 14311 W ActivityManager:   Force finishing activity com.svizzera.candycube/com.unity3d.player.UnityPlayerActivity
04-04 17:17:10.449  1430 14311 W ActivityManager:   Force finishing activity com.svizzera.candycube/com.unity3d.player.UnityPlayerActivity
04-04 17:17:10.449  1430 14311 W ActivityManager: Duplicate finish request for ActivityRecord{54ca88b u0 com.svizzera.candycube/com.unity3d.player.UnityPlayerActivity t654 f}
04-04 17:17:10.638  1430  2475 I ActivityManager: Process com.svizzera.candycube (pid 14229) has died
04-04 17:17:10.638  1430  2475 D ActivityManager: cleanUpApplicationRecord -- 14229
04-04 17:17:10.669  1430  2475 I ActivityManager: Killing 13840:com.xiaomi.account/u0a99 (adj 901): empty #17
04-04 17:17:10.691  1430  2475 I ActivityManager: Config changes=480 {1.0 405mcc861mnc [en_IN] ldltr sw360dp w360dp h620dp 480dpi nrml long port finger -keyb/v/h -nav/h s.69 themeChanged=0 themeChangedFlags=0}
04-04 17:17:10.881  1430 27442 D ActivityManager: cleanUpApplicationRecord -- 13840
04-04 17:17:10.890  1430 27442 W ActivityManager: Scheduling restart of crashed service com.xiaomi.account/.XiaomiAccountService in 1000ms
04-04 17:17:11.942  1430  1482 I ActivityManager: Start proc 14319:com.xiaomi.account/u0a99 for service com.xiaomi.account/.XiaomiAccountService
04-04 17:17:12.350  1430 18671 I ActivityManager: Killing 14026:com.google.process.gapps/u0a13 (adj 906): empty #17
04-04 17:17:12.378  1430  1968 D ActivityManager: cleanUpApplicationRecord -- 14026
04-04 17:17:12.382  1430 14311 W ActivityManager: Ignoring remove of inactive process: ProcessRecord{546abda 0:com.svizzera.candycube/u0a365}

**Comment by AbhayaAgrawal1** [comment]
04-04 17:17:00.615  1430  2438 W ActivityManager: Sending non-protected broadcast com.android.action.NETWORK_POLICY_UPDATE from system 3204:com.miui.networkassistant.deamon/1000 pkg com.miui.securitycenter. Callers=
04-04 17:17:00.875  1430 27442 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.juegostudios.testIAP cmp=com.juegostudios.testIAP/com.unity3d.player.UnityPlayerActivity} from uid 10026 on display 0
04-04 17:17:00.977  1430  2613 I ActivityManager: Start proc 14229:com.juegostudios.testIAP/u0a365 for activity com.juegostudios.testIAP/com.unity3d.player.UnityPlayerActivity
04-04 17:17:00.978  1430  2613 E ActivityManager: Invalid thumbnail dimensions: 0x0
04-04 17:17:00.988  1430  1535 W ActivityManager: Unable to start service Intent { act=android.intent.action.PACKAGE_FIRST_LAUNCH pkg=com.xiaomi.market (has extras) } U=0: not found
04-04 17:17:01.287  1430  2477 I ActivityManager: Config changes=480 {1.0 405mcc861mnc [en_IN] ldltr sw360dp w640dp h340dp 480dpi nrml long land finger -keyb/v/h -nav/h s.68 themeChanged=0 themeChangedFlags=0}
04-04 17:17:02.057  1430  1511 I ActivityManager: Displayed com.juegostudios.testIAP/com.unity3d.player.UnityPlayerActivity: +1s109ms
04-04 17:17:02.064  1430  1482 I ActivityManager: Killing 13821:com.android.printspooler/u0a85 (adj 906): empty #17
04-04 17:17:02.350  1430  2616 D ActivityManager: cleanUpApplicationRecord -- 13821
04-04 17:17:02.359 14229 14247 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_multisampled_render_to_texture GL_OES_sha
04-04 17:17:02.359 14229 14247 D Unity   : der_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_i
04-04 17:17:02.359 14229 14247 D Unity   : nitializers
04-04 17:17:08.305 14229 14247 I Unity   : Not Died @ 33
04-04 17:17:08.305 14229 14247 I Unity   :  
04-04 17:17:08.305 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.305 14229 14247 I Unity   : 
04-04 17:17:08.309 14229 14247 I Unity   : not Died @ 45
04-04 17:17:08.309 14229 14247 I Unity   :  
04-04 17:17:08.309 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.309 14229 14247 I Unity   : 
04-04 17:17:08.314 14229 14247 I Unity   : not Died @ 48
04-04 17:17:08.314 14229 14247 I Unity   :  
04-04 17:17:08.314 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.314 14229 14247 I Unity   : 
04-04 17:17:08.327 14229 14247 I Unity   : not Died @ 50
04-04 17:17:08.327 14229 14247 I Unity   :  
04-04 17:17:08.327 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.327 14229 14247 I Unity   : 
04-04 17:17:08.327 14229 14247 I Unity   : not Died @ 54
04-04 17:17:08.327 14229 14247 I Unity   :  
04-04 17:17:08.327 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.327 14229 14247 I Unity   : 
04-04 17:17:08.328 14229 14247 I Unity   : opening text
04-04 17:17:08.328 14229 14247 I Unity   :  
04-04 17:17:08.328 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.328 14229 14247 I Unity   : 
04-04 17:17:08.331 14229 14247 I Unity   : not Died @ 56: System.Action`1[System.Boolean]
04-04 17:17:08.331 14229 14247 I Unity   :  
04-04 17:17:08.331 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.331 14229 14247 I Unity   : 
04-04 17:17:08.517 14229 14247 I Unity   : Building GPG services, implicitly attempts silent auth
04-04 17:17:08.517 14229 14247 I Unity   :  
04-04 17:17:08.517 14229 14247 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-04 17:17:08.517 14229 14247 I Unity   : 
04-04 17:17:08.978 14310 14310 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-04 17:17:08.979 14310 14310 F DEBUG   : Build fingerprint: 'Xiaomi/gemini/gemini:7.0/NRD90M/V8.2.1.0.NAAMIEB:user/release-keys'
04-04 17:17:08.979 14310 14310 F DEBUG   : Revision: '0'
04-04 17:17:08.979 14310 14310 F DEBUG   : ABI: 'arm'
04-04 17:17:08.979 14310 14310 F DEBUG   : pid: 14229, tid: 14247, name: main  >>> com.juegostudios.testIAP <<<
04-04 17:17:08.979 14310 14310 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
04-04 17:17:08.986 14310 14310 F DEBUG   : Abort message: 'art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: java_class == null'
04-04 17:17:08.986 14310 14310 F DEBUG   :     r0 00000000  r1 000037a7  r2 00000006  r3 00000008
04-04 17:17:08.987 14310 14310 F DEBUG   :     r4 eba00978  r5 00000006  r6 eba00920  r7 0000010c
04-04 17:17:08.987 14310 14310 F DEBUG   :     r8 00000000  r9 f2dea56c  sl 000008e6  fp f2dafeef
04-04 17:17:08.987 14310 14310 F DEBUG   :     ip 0000000b  sp eb9fe998  lr f47512c7  pc f4753b48  cpsr 200f0010
04-04 17:17:09.005 14310 14310 F DEBUG   : 
04-04 17:17:09.005 14310 14310 F DEBUG   : backtrace:
04-04 17:17:09.010 14310 14310 F DEBUG   :     #00 pc 00049b48  /system/lib/libc.so (tgkill+12)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #01 pc 000472c3  /system/lib/libc.so (pthread_kill+34)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #02 pc 0001d565  /system/lib/libc.so (raise+10)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #03 pc 000190b1  /system/lib/libc.so (__libc_android_abort+34)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #04 pc 00017114  /system/lib/libc.so (abort+4)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #05 pc 00317a35  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+252)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #06 pc 000b46f9  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+864)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #07 pc 002378d5  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1664)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #08 pc 00237b3b  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+66)
04-04 17:17:09.011 14310 14310 F DEBUG   :     #09 pc 0025de05  /system/lib/libart.so (_ZN3art3JNI21RegisterNativeMethodsEP7_JNIEnvP7_jclassPK15JNINativeMethodib+2208)
04-04 17:17:09.012 14310 14310 F DEBUG   :     #10 pc 0027b191  /system/lib/libart.so (_ZN3art3JNI15RegisterNativesEP7_JNIEnvP7_jclassPK15JNINativeMethodi+12)
04-04 17:17:09.012 14310 14310 F DEBUG   :     #11 pc 0009221b  /data/app/com.juegostudios.testIAP-1/lib/arm/libgpg.so
04-04 17:17:09.012 14310 14310 F DEBUG   :     #12 pc 00092e37  /data/app/com.juegostudios.testIAP-1/lib/arm/libgpg.so
04-04 17:17:09.012 14310 14310 F DEBUG   :     #13 pc 000933dd  /data/app/com.juegostudios.testIAP-1/lib/arm/libgpg.so
04-04 17:17:09.012 14310 14310 F DEBUG   :     #14 pc 0008dc69  /data/app/com.juegostudios.testIAP-1/lib/arm/libgpg.so (_ZNK3gpg28AndroidPlatformConfiguration5ValidEv+76)
04-04 17:17:09.013 14310 14310 F DEBUG   :     #15 pc 00053441  /data/app/com.juegostudios.testIAP-1/lib/arm/libgpg.so (_ZN3gpg12GameServices7Builder6CreateERKNS_28AndroidPlatformConfigurationE+40)
04-04 17:17:09.014 14310 14310 F DEBUG   :     #16 pc 000c73dd  /data/app/com.juegostudios.testIAP-1/lib/arm/libgpg.so (GameServices_Builder_Create+16)
04-04 17:17:09.014 14310 14310 F DEBUG   :     #17 pc 0000fbbc  <anonymous:d2370000>
04-04 17:17:10.426  1430 14311 W ActivityManager:   Force finishing activity com.juegostudios.testIAP/com.unity3d.player.UnityPlayerActivity
04-04 17:17:10.449  1430 14311 W ActivityManager:   Force finishing activity com.juegostudios.testIAP/com.unity3d.player.UnityPlayerActivity
04-04 17:17:10.449  1430 14311 W ActivityManager: Duplicate finish request for ActivityRecord{54ca88b u0 com.juegostudios.testIAP/com.unity3d.player.UnityPlayerActivity t654 f}
04-04 17:17:10.638  1430  2475 I ActivityManager: Process com.juegostudios.testIAP (pid 14229) has died
04-04 17:17:10.638  1430  2475 D ActivityManager: cleanUpApplicationRecord -- 14229
04-04 17:17:10.669  1430  2475 I ActivityManager: Killing 13840:com.xiaomi.account/u0a99 (adj 901): empty #17
04-04 17:17:10.691  1430  2475 I ActivityManager: Config changes=480 {1.0 405mcc861mnc [en_IN] ldltr sw360dp w360dp h620dp 480dpi nrml long port finger -keyb/v/h -nav/h s.69 themeChanged=0 themeChangedFlags=0}
04-04 17:17:10.881  1430 27442 D ActivityManager: cleanUpApplicationRecord -- 13840
04-04 17:17:10.890  1430 27442 W ActivityManager: Scheduling restart of crashed service com.xiaomi.account/.XiaomiAccountService in 1000ms
04-04 17:17:11.942  1430  1482 I ActivityManager: Start proc 14319:com.xiaomi.account/u0a99 for service com.xiaomi.account/.XiaomiAccountService
04-04 17:17:12.350  1430 18671 I ActivityManager: Killing 14026:com.google.process.gapps/u0a13 (adj 906): empty #17
04-04 17:17:12.378  1430  1968 D ActivityManager: cleanUpApplicationRecord -- 14026
04-04 17:17:12.382  1430 14311 W ActivityManager: Ignoring remove of inactive process: ProcessRecord{546abda 0:com.juegostudios.testIAP/u0a365}

**Comment by claywilkinson** [comment]
Looks like there is still some filtering of the log, but I think it is one of two things:
1. You are using play-services 10.2 or 10.2.1 and 0.9.36 of the plugin.  There was a known issue and with 0.9.36 and 10.2, so upgrading the plugin to 0.9.37 will address that.

2. You are missing the play-services aars in Assets/Plugins/Android.  In that case you need to run the plugin setup again (Window > Google Play Games  > Setup > Android Setup...

**Comment by AbhayaAgrawal1** [comment]
@claywilkinson  
Thank you! it started working now. I updated the plugin.
