### ISSUE TITLE
Opening Leaderboard UI or Score UI disables screen orientation

### ISSUE THREAD

**Issue by christophe-h-mary** [playgameservices/play-games-plugin-for-unity#1670]
My game is authorized to rotate to landscape right or landscape left.
But if I open one of the UIs, and rotate to portrait, it works.
When closing the UI, the game keeps the portrait orientation.

Is there any way to prevent that ?
Cheers !

**Comment by claywilkinson** [comment]
Let me repeat the question to make sure I understand:
1. Start your game in landscape.
2. Open the Leaderboard UI
3. Rotate to portrait, the leaderboard UI redraws correctly.
4. Exit leaderboards - the game is resumed in portrait (which is wrong).

If so, you need to add a callback to the ShowLeaderboardUI() call that checks the screen orientation and correct it (by forcing landscape).
