### ISSUE TITLE
Android crash when try to fetch event

### ISSUE THREAD

**Issue by nguyentiencuongvaicut** [playgameservices/play-games-plugin-for-unity#1674]
Hello there, i got an issue on my android game.
I can fetch event in unity 5.5.2f1 , not in 5.6.
In 5.6 the command PlayGamesPlatform.Instance.Events.FetchEvent crash my game. 
Both use same plugin version 0.9.36 and google play services arr files 10.0.1.
in 5.6, process user data involved achievement, leaderboard, savegame, everything work fine, except the Events.
My device can't connect by USB to my PC so i can't get the logcat, so i use onscreen text to debug.Please help teach me use other methods to get log if you know.
Thank you for your time !

**Comment by nguyentiencuongvaicut** [comment]
btw Authenticate and save /load data in unity 5.6 is much much slower than 5.5.2f1.
I don't understand, unity upgrade affect that much google play services ?

**Comment by claywilkinson** [comment]
Why can't you connect your device to your PC via USB?  How do you deploy your build to test?
I strongly recommend fixing that, then getting a log - you will be *much* more productive and effective when developing.

**Comment by nguyentiencuongvaicut** [comment]
I don't know, my device just can't, it's levono 7000. I think the device's USB port is broken.

**Comment by claywilkinson** [comment]
Without a log, there is not much that can be done to diagnose your issue.  Maybe use another device?

**Comment by nguyentiencuongvaicut** [comment]
I think i will close this issue now because my game can run without the events stuff , i mainly use achievement and save game and leaderboard that run just fine. Thanks claywilkinson
