### ISSUE TITLE
in 0.9.37 version and in Unity 5.5.2f GetServerAuthCode or GetIdToken returns empty string

### ISSUE THREAD

**Issue by Server12** [playgameservices/play-games-plugin-for-unity#1676]
I'm starting from this:

```
               PlayGamesPlatform.DebugLogEnabled = true;
               PlayGamesClientConfiguration config = new PlayGamesClientConfiguration
                        .Builder()
                        .RequestIdToken()
                        .RequestServerAuthCode(false)
                    .Build();

                PlayGamesPlatform.InitializeInstance(config);
                PlayGamesPlatform.Activate();
   PlayGamesPlatform.Instance.Authenticate((success, result) =>
                    {
                        if (success)
                        {
//this auth code and token are empty!
                            string authCode = PlayGamesPlatform.Instance.GetServerAuthCode();
                            string token = PlayGamesPlatform.Instance.GetIdToken();

                            Debug.LogFormat("authcode :{0}, token: {1}",authCode,token);
                        }

},false);

```
On device when 
>     .RequestIdToken().RequestServerAuthCode(false)
shows popup with "Google Play Games service stopped!" But app not crash.
In Google Dev Console all things setted right.(using web OAuth client id)
Please help, I'm really stuck on this.

**Comment by claywilkinson** [comment]
Can you share the log?

**Comment by mkorotetsky** [comment]
Hi, I saw that crash too. You should make "Android Setup" to fix it.
Another problem: sometimes after starting google play services I see semi transparent black screen on top of my application. After tapping back button it is hides and shows again with select google play account dialog.

**Comment by Server12** [comment]
04-09 11:37:01.586 23619 23637 D GamesUnitySDK: Performing Android initialization of the GPG SDK

04-09 11:37:01.636 23619 23637 I Unity   : Building GPG services, implicitly attempts silent auth

04-09 11:37:01.636 23619 23637 I Unity   :  

04-09 11:37:01.636 23619 23637 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

04-09 11:37:01.636 23619 23637 I Unity   : 

04-09 11:37:01.646 23619 23637 I GamesNativeSDK: Using existing jar.

04-09 11:37:01.646 23619 23637 I GamesNativeSDK: Writing 1941 bytes to jar file

04-09 11:37:01.656 23619 23637 I GamesNativeSDK: Using existing jar.

04-09 11:37:01.656 23619 23637 I GamesNativeSDK: Writing 1066 bytes to jar file

04-09 11:37:01.696 23619 23637 W PopupManager: You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments

04-09 11:37:01.696 23619 23931 I GamesNativeSDK: Auth operation started: SIGN IN

04-09 11:37:01.696 23619 23931 I GamesNativeSDK: Connecting to Google Play...

04-09 11:37:01.716 23619 23637 I Unity   : Using AuthHelper to sign in

04-09 11:37:01.716 23619 23637 I Unity   :  

04-09 11:37:01.716 23619 23637 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

04-09 11:37:01.716 23619 23637 I Unity   : 

04-09 11:37:01.726 16932 16932 W ResourcesManager: getTopLevelResources: /data/app/com.google.android.play.games-2/base.apk / 1.0 running in com.google.android.gms rsrc of package null

04-09 11:37:01.726 16932 16932 W ResourcesManager: getTopLevelResources: /data/app/com.google.android.play.games-2/base.apk / 1.0 running in com.google.android.gms rsrc of package null

04-09 11:37:01.776 23619 23637 W Unity   : !!! [Play Games Plugin DLL] 04/09/17 11:37:01 +03:00 WARNING: Creating new PlayGamesPlatform

04-09 11:37:01.776 23619 23637 W Unity   :  

04-09 11:37:01.776 23619 23637 W Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

04-09 11:37:01.776 23619 23637 W Unity   : 

04-09 11:37:01.776 23619 23637 I Unity   :  [Play Games Plugin DLL] 04/09/17 11:37:01 +03:00 DEBUG: Activating PlayGamesPlatform.

04-09 11:37:01.776 23619 23637 I Unity   :  

04-09 11:37:01.776 23619 23637 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

04-09 11:37:01.776 23619 23637 I Unity   : 

04-09 11:37:01.776 23619 23637 I Unity   :  [Play Games Plugin DLL] 04/09/17 11:37:01 +03:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform

04-09 11:37:01.776 23619 23637 I Unity   :  

04-09 11:37:01.776 23619 23637 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

04-09 11:37:01.776 23619 23637 I Unity   : 

04-09 11:37:01.776 23619 23637 I Unity   :  [Play Games Plugin DLL] 04/09/17 11:37:01 +03:00 DEBUG: Creating platform-specific Play Games client.

04-09 11:37:01.776 23619 23637 I Unity   :  

04-09 11:37:01.776 23619 23637 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

04-09 11:37:01.776 23619 23637 I Unity   : 

04-09 11:37:01.776 23619 23637 I Unity   :  [Play Games Plugin DLL] 04/09/17 11:37:01 +03:00 DEBUG: Creating Android IPlayGamesClient Client

04-09 11:37:01.776 23619 23637 I Unity   :  

04-09 11:37:01.776 23619 23637 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

04-09 11:37:01.776 23619 23637 I Unity   : 

04-09 11:37:01.786 16932  2922 W GamesServiceBroker: Client connected with SDK 10298000, Services 10298438, and Games 39080038

04-09 11:37:01.796 16932 16932 W ResourcesManager: getTopLevelResources: /data/app/com.google.android.play.games-2/base.apk / 1.0 running in com.google.android.gms rsrc of package null

04-09 11:37:01.796 23619 23637 D TokenFragment: Creating fragment

04-09 11:37:01.816 23619 23619 D TokenFragment: onStart()

04-09 11:37:01.816 23619 23619 D TokenFragment: onResume called

04-09 11:37:01.816 23619 23619 W PopupManager: You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments

04-09 11:37:01.816  1173  7357 D SSRM:n  : SIOP:: AP = 290, PST = 264, CUR = 450, LCD = 120

04-09 11:37:01.826 23619 23637 I Unity   : ---- [0] -- 2097181

04-09 11:37:01.826 23619 23637 I Unity   :  

04-09 11:37:01.826 23619 23637 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

04-09 11:37:01.826 23619 23637 I Unity   : 

04-09 11:37:01.836 23619 23637 E TokenFragment: Already a pending token request!

04-09 11:37:01.836 23619 23637 D TokenFragment: Fragment exists.. calling processRequests

04-09 11:37:01.876 23619 23637 I Timeline: Timeline: Activity_launch_request id:com.stdforland.hockeybattle time:62774210

04-09 11:37:01.876 23619 23619 I Timeline: Timeline: Activity_launch_request id:com.stdforland.hockeybattle time:62774210

04-09 11:37:01.906  1173  4690 E Parcel  : Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration

04-09 11:37:01.906  1173  4690 E Parcel  : java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration

04-09 11:37:01.906  1173  4690 E Parcel  : 	at java.lang.Class.classForName(Native Method)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at java.lang.Class.forName(Class.java:324)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:2404)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at android.os.Parcel.readParcelable(Parcel.java:2358)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at android.os.Parcel.readValue(Parcel.java:2264)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at android.os.BaseBundle.getString(BaseBundle.java:920)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at android.content.Intent.getStringExtra(Intent.java:6183)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2695)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2157)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6335)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6113)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3985)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at android.os.Binder.execTransact(Binder.java:453)

04-09 11:37:01.906  1173  4690 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration

04-09 11:37:01.906  1173  4690 E Parcel  : 	at java.lang.Class.classForName(Native Method)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at java.lang.BootClassLoader.findClass(ClassLoader.java:781)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)

04-09 11:37:01.906  1173  4690 E Parcel  : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

04-09 11:37:01.906  1173  4690 E Parcel  : 	... 16 more

04-09 11:37:01.906  1173  4690 E Parcel  : Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

04-09 11:37:01.906  1173  4690 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1958400  uid : 1000  pid : 1173  pkgName : ACTIVITY_RESUME_BOOSTER@10

04-09 11:37:01.916  1173  4690 D ActivityManager: mDVFSHelper.acquire()

04-09 11:37:01.916  1173  4690 V WindowManager: addAppToken: AppWindowToken{38661b5 token=Token{dfa59ec ActivityRecord{454c49f u0 com.stdforland.hockeybattle/com.google.android.gms.auth.api.signin.internal.SignInHubActivity t214}}} to stack=1 task=214 at 1

04-09 11:37:01.926  1173  4690 D InputDispatcher: Focused application set to: xxxx

04-09 11:37:01.926  1173  4311 E Parcel  : Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration

04-09 11:37:01.926  1173  4311 E Parcel  : java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration

04-09 11:37:01.926  1173  4311 E Parcel  : 	at java.lang.Class.classForName(Native Method)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at java.lang.Class.forName(Class.java:324)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:2404)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at android.os.Parcel.readParcelable(Parcel.java:2358)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at android.os.Parcel.readValue(Parcel.java:2264)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at android.os.BaseBundle.getString(BaseBundle.java:920)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at android.content.Intent.getStringExtra(Intent.java:6183)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2695)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2157)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6335)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6113)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3985)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at android.os.Binder.execTransact(Binder.java:453)

04-09 11:37:01.926  1173  4311 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration

04-09 11:37:01.926  1173  4311 E Parcel  : 	at java.lang.Class.classForName(Native Method)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at java.lang.BootClassLoader.findClass(ClassLoader.java:781)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)

04-09 11:37:01.926  1173  4311 E Parcel  : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

04-09 11:37:01.926  1173  4311 E Parcel  : 	... 16 more

04-09 11:37:01.926  1173  4311 E Parcel  : Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by Server12** [comment]
>  Hi, I saw that problem too. You should make "Android Setup" to fix it.

Hi, what i need todo ?

> Another problem: sometimes after starting google play services I see semi transparent black screen on top of my application. 

Exaxctly, i always see this.

**Comment by mkorotetsky** [comment]
> Hi, what i need todo ?
Go to Window -> Google Play Games -> Setup -> Android setup
Ensure you have valid Web App Client Id. Click Setup. You should always click setup after library update.
"Google Play Games service stopped!" should be fixed.

**Comment by Server12** [comment]
It did not help, I installed the web client id as needed.

**Comment by claywilkinson** [comment]
Great to hear!

**Comment by ramioooz** [comment]
Hello : Server12
Quote : "Now all fixed, my problem in wrong sha1 fingerprints for android apps."

How did you fix it, did you upload an updated apk to your developer console ?

thank you.
