### ISSUE TITLE
Login to firebase, use GPGS

### ISSUE THREAD

**Issue by gazialankus** [playgameservices/play-games-plugin-for-unity#1677]
I understand that the user can login to GPGS and get an access token for Firebase from it. 

Is it possible to do the opposite? The user will log in to Firebase, and somehow will be considered authenticated with GPGS?

Here is the use case: the game's backend will be Firebase and it will work fine without GPGS. However, the user will optionally enable GPGS to keep track of achievements, etc. It would be nice if enabling GPGS like this will not require the user to authenticate explicitly to GPGS.

**Comment by claywilkinson** [comment]
Unfortunately, no. In order to Play Games Services you need to be authenticated using Google-In.
