### ISSUE TITLE
Google choose account window not appearing!

### ISSUE THREAD

**Issue by Logystone** [playgameservices/play-games-plugin-for-unity#1679]
Hello guys ..
I faced a problem that when i press a "Connect" Button it only appears 
1. Connecting to "Game Name" (1~2 Sec)
2. Google Play Services window (1~2 Sec)
3. Load bar (1~3 Sec)
but it doesn't show me the username is connected or not connected! and in which level I am...
this is my code :

`using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;
public class Gsetup : MonoBehaviour 
{
	public Text test1;
	void Awake()
	{
		
	}
	void Start()

	{
		
		PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder ().Build ();

		PlayGamesPlatform.InitializeInstance(config);
		// recommended for debugging:
		PlayGamesPlatform.DebugLogEnabled = false;
		// Activate the Google Play Games platform
		PlayGamesPlatform.Activate();

	}
	public void OnConnect()
	{
		Social.localUser.Authenticate((bool success) => 
			{
				if(success)
				{
					string userInfo = "ID: " + Social.localUser.userName;
					Debug.Log("Connected!");
					test1.text = "Connected";

				}
				else
				{
					Debug.Log("Failed to connect!");
					

					test1.text = "Not Connected";

				}
			});
	}
	public void OnShowingLeaderBoard()
	{
		if (Social.localUser.authenticated) 
		{
			Social.ShowAchievementsUI ();
		} 
	

	}
	public void OnShowingAchievments()
	{
		if (Social.localUser.authenticated) 
		{
			Social.ShowLeaderboardUI ();
		}
	
	}

}`

-------
My Google Console Settings:
- The game on alpha release  (old build... The new build not uploaded)
- The game is published as open alpha for testers
- The google play services is not published yet 
[http://i.imgur.com/Tqc7Wat.png](url)
---------
Installed plugins On My Unity game :
- Admob
- Unity Purchasing

**Comment by Logystone** [comment]
What is the solution please ?
why the windows doesn't appear that i'm log-in ?
Also i've tested it on my phone without updating to google console 
and i've added a UI text to the scene..
When the login in success it will says "Connected"
and when failed it says : "Not Connected"
So it's always failed!

**Comment by Logystone** [comment]
Please answer!

**Comment by Warhammer4000** [comment]
I'm having the same problem. So I tried to put the email address to the testers after that. nothing happens.Even that connecting screen stops coming and it fails.

**Comment by Logystone** [comment]
sooo what is the solution ?

**Comment by Warhammer4000** [comment]
Not sure. but I'm guessing it has to do something with publishing the app. And the console ... Not this plugin. Because hardly anyone complaining about this.

**Comment by mkorotetsky** [comment]
Hi, I have something similar, I wrote about it in different issue: #1676 
> sometimes after starting google play services I see semi transparent black screen on top of my application. After tapping back button it is hides and shows again with select google play account dialog.

**Comment by Warhammer4000** [comment]
Tried just now with android setup. Didn't work.

**Comment by Logystone** [comment]
maybe when it's come to release and i publish my game play services will it works?

**Comment by claywilkinson** [comment]
Can you share the log of trying to authenticate?

**Comment by Logystone** [comment]
how can i get the log ?

**Comment by mostdeep123** [comment]
i have the same issue since i has Google Play Service Plugin and Unity Admob Plugin at the same application, it seems the Google Play Service plugin overwrite the Android Manifest.xml
i dont know for sure, i stack with this issue for 1 week, and didn't find any correct plugin except when i used only the Admob Plugin not both of the,

**Comment by Warhammer4000** [comment]
Problem Resolved. I did a set of changes. Don't know which one fixed it.
1)put the login functions and stuff into a singleton
2)installed latest Unity.

Well I can confirm one thing tho. The issue isn't with the plugin. Somewhere in the implementation or Unity itself.
