### ISSUE TITLE
Crash on trying to sign in with no google accounts already on device

### ISSUE THREAD

**Issue by tenpn** [playgameservices/play-games-plugin-for-unity#168]
...the game brought up the dialog to allow me to add an account, but then crashed. 

I wasn't able to repro this on subsequent attempts on the same device, even after clean installs of the game, or signing into different accounts, and could subsequently sign in fine. I *have* however experienced it on multiple devices. So it seems to be a device-level bug.

Here's the dump from the device: https://www.dropbox.com/s/whcoux53qbl3he6/bugreport-2014-07-22-19-54-55_GGSCrashed.txt (wtf github doesn't allow text attachments?)

**Comment by claywilkinson** [comment]
@tenpn  - I am closing this issue since it appears the dump you are referring to is gone, so I am assuming this is no longer an issue.  If you are having this issue with the latest version of the plugin, please re-open this issue.  Thanks!
