### ISSUE TITLE
in 0.9.37 version and in Unity 5.5.1f. Sign_in login Has failed to return！！

### ISSUE THREAD

**Issue by Heartlikesea** [playgameservices/play-games-plugin-for-unity#1680]
void Start()
    {
        PlayGamesPlatform.Activate();
    }
     if (GUI.Button(new Rect(0, 150, 110, 75), "Login"))
     {
            
         Social.localUser.Authenticate(HandleAuthenticated);
     }
    private void HandleAuthenticated(bool success)
    {
        gameCenterState = success;
        Debug.Log("*** HandleAuthenticated: success = " + success);
        if (success)
        {
            gcState = true;

            userid = Social.localUser.id;
            userInfo = "Username: " + Social.localUser.userName +
                "\nUser ID: " + Social.localUser.id +
                "\nIsUnderage: " + Social.localUser.underage;
            Debug.Log(userInfo);
        }
        else
        {
            Debug.Log("---- HandleAuthenticated: failed ---" );
            gcState = false;
        }
    }

log Tips:
04-10 17:17:56.350: I/OAM(2802): [check_file_size:402]/data/hwlogdir/wifi_log/wifi_log_1 log file beyond size=10240Byte, creat new file
04-10 17:17:56.350: I/OAM(2802): [rename_old_file:107]rename_old_file
04-10 17:17:56.770: I/System.out(14539): [CDS]rx timeout:100
04-10 17:17:56.770: I/System.out(14539): [CDS]rx timeout:100
04-10 17:17:56.770: I/System.out(14539): [CDS]rx timeout:100
04-10 17:17:56.770: I/System.out(14539): [CDS]rx timeout:30000
04-10 17:17:56.770: W/Auth(14539): [GetToken] GetToken failed with status code: UNREGISTERED_ON_API_CONSOLE
04-10 17:17:56.770: E/TokenRequestor(17468): You have wrong OAuth2 related configurations, please check. Detailed error: UNREGISTERED_ON_API_CONSOLE
04-10 17:17:56.780: W/GamesServiceBroker(17468): Client connected with SDK 8487000, Services 10298036, and Games 39080036
04-10 17:17:56.790: I/GamesNativeSDK(7363): UI interaction required to connect to Google Play.
04-10 17:17:56.790: W/GamesServiceBroker(17468): Client connected with SDK 8487000, Services 10298036, and Games 39080036
04-10 17:17:56.810: I/Unity(7363): *** HandleAuthenticated: success = False
04-10 17:17:56.810: I/Unity(7363):  
04-10 17:17:56.810: I/Unity(7363): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
04-10 17:17:56.810: I/Unity(7363): ---- HandleAuthenticated: failed ---
04-10 17:17:56.810: I/Unity(7363):  
04-10 17:17:56.810: I/Unity(7363): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
04-10 17:17:56.840: I/GoLog(6895): DEBUG fronted: cache.go:63 Caching vetted masquerade for cloudfront.net (54.182.4.244)
04-10 17:17:58.940: I/GoLog(6895): 2017/04/10 09:17:58 [ERR] socks: Failed to handle request: Connect to 104.131.55.227:14443 failed: Unable to connect socket to 104.131.55.227:14443: connect timeout
04-10 17:17:58.940: I/System.out(6991): [CDS]close[44110]

The APIs in the API Manager are already started.
Tester account also added.

**Comment by Heartlikesea** [comment]
The problem is that the SHA1 of the game service does not match the SHA1 of the application. So the game service SHA1 will be changed to the application of SHA1 on it.

**Comment by nahidulnibir** [comment]
in you application check your app signing certificates under release management . there are two certificates . 1. app signing certificate 2. upload certificate . in google api console for your app the sha1 certificate is by default set to the upload sha1 certificate . which you need to change with your app signing sha1 certificate. hope this will help you.
