### ISSUE TITLE
If Google Play Games app is not installed, the callback is returning false

### ISSUE THREAD

**Issue by natasha1403** [playgameservices/play-games-plugin-for-unity#1681]
Hi 

I am using GPGS api for authentication. However, most of the users do not have Google Play Games installed on their device. So, it is redirecting users to the play store and call back is returning false. However, I want that if the user has allowed to install the app, then callback should wait and return true if it was successful. Is there a way I can achieve this?

**Comment by claywilkinson** [comment]
The authentication should wait for some time, but it definitely could timeout if it takes a long time to install the app, or the user does not hit the back arrow once it is installed.  If you want to have a more precise error message, you could use PlatformUtils.Supported to check if the play games app is installed.
