### ISSUE TITLE
DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

### ISSUE THREAD

**Issue by AbhayaAgrawal1** [playgameservices/play-games-plugin-for-unity#1683]
I am getting these logs when i am choosing the player. I am not able to connect with it. I am working on turn base multiplayer.
i am using Unity 5.4.1 and GooglePlayServices 0.9.37

Here are the Unity Logs:

04-10 17:43:32.028  9226  9245 I Unity   : ButtonClicked: Button-Ok (UnityEngine.UI.Button)
04-10 17:43:32.028  9226  9245 I Unity   :  
04-10 17:43:32.028  9226  9245 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-10 17:43:32.028  9226  9245 I Unity   : 
04-10 17:43:32.988  9226  9245 I Unity   : ButtonClicked: Button-Invite (UnityEngine.UI.Button)
04-10 17:43:32.988  9226  9245 I Unity   :  
04-10 17:43:32.988  9226  9245 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-10 17:43:32.988  9226  9245 I Unity   : 
04-10 17:43:32.988  9226  9245 I Unity   : opening text
04-10 17:43:32.988  9226  9245 I Unity   :  
04-10 17:43:32.988  9226  9245 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-10 17:43:32.988  9226  9245 I Unity   : 
04-10 17:43:33.008  9226  9245 I Unity   :  [Play Games Plugin DLL] 04/10/17 17:43:33 +05:30 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler
04-10 17:43:33.008  9226  9245 I Unity   :  
04-10 17:43:33.008  9226  9245 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-10 17:43:33.008  9226  9245 I Unity   : 
04-10 17:43:33.018  1393  1413 D ActivityManager: mDVFSHelper.acquire()
04-10 17:43:33.118  1393  1413 D ActivityManager: mDVFSHelper.acquire()
04-10 17:43:33.128  1393  3018 D ActivityManager: post active user change for 0 fullscreen false isFloatingActivity() false isHomeActivity() false
04-10 17:43:33.158  1393  3008 D ActivityManager:  Launching com.google.android.play.games, updated priority
04-10 17:43:33.348  1393  3018 D ActivityManager: post active user change for 0 fullscreen false isFloatingActivity() false isHomeActivity() false
04-10 17:43:33.478  1393  1703 I ActivityManager: Displayed com.google.android.play.games/com.google.android.gms.games.ui.client.matches.SelectOpponentsActivity: +320ms (total +16s436ms)
04-10 17:43:33.738  1393  1703 D ActivityManager: mDVFSHelper.release()
04-10 17:43:39.618  1393  3730 D ActivityManager: mDVFSHelper.acquire()
04-10 17:43:39.878  1393  3813 D ActivityManager: post active user change for 0 fullscreen false isFloatingActivity() false isHomeActivity() false
04-10 17:43:40.038  1393  1703 I ActivityManager: Displayed com.google.android.play.games/com.google.android.gms.games.ui.client.players.ClientPlayerSearchActivity: +404ms
04-10 17:43:40.278  1393  1703 D ActivityManager: mDVFSHelper.release()
04-10 17:43:49.188  1393  3813 D ActivityManager: mDVFSHelper.acquire()
04-10 17:43:49.218  1393  3008 D ActivityManager: post active user change for 0 fullscreen false isFloatingActivity() false isHomeActivity() false
04-10 17:43:52.188  1393  1599 D ActivityManager: mDVFSHelper.release()
04-10 17:43:52.548  1393  3781 D ActivityManager: mDVFSHelper.acquire()
04-10 17:43:52.548  1393  3781 D ActivityManager:  Launching com.juegostudio.testIAP, updated priority
04-10 17:43:52.598  1393  2988 D ActivityManager: post active user change for 0 fullscreen false isFloatingActivity() false isHomeActivity() false
04-10 17:43:52.638  1393  3784 D ActivityManager: post active user change for 0 fullscreen true isFloatingActivity() false isHomeActivity() false
**04-10 17:43:52.678  9226  9245 I Unity   :  [Play Games Plugin DLL] 04/10/17 17:43:52 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.**
04-10 17:43:52.678  9226  9245 I Unity   :  
04-10 17:43:52.678  9226  9245 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-10 17:43:52.678  9226  9245 I Unity   : 
04-10 17:43:52.678  9226  9245 I Unity   :  [Play Games Plugin DLL] 04/10/17 17:43:52 +05:30 DEBUG: Entering internal callback for TurnBasedManager#PlayerSelectUICallback
04-10 17:43:52.678  9226  9245 I Unity   :  
04-10 17:43:52.678  9226  9245 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-10 17:43:52.678  9226  9245 I Unity   : 
04-10 17:43:53.158  9226  9245 I Unity   :  [Play Games Plugin DLL] 04/10/17 17:43:53 +05:30 DEBUG: Entering internal callback for TurnBasedManager#InternalTurnBasedMatchCallback
04-10 17:43:53.158  9226  9245 I Unity   :  
04-10 17:43:53.158  9226  9245 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-10 17:43:53.158  9226  9245 I Unity   : 
04-10 17:43:53.158  9226  9245 I Unity   : closing text
04-10 17:43:53.158  9226  9245 I Unity   :  
04-10 17:43:53.158  9226  9245 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-10 17:43:53.158  9226  9245 I Unity   : 
04-10 17:43:55.548  1393  1599 D ActivityManager: mDVFSHelper.release()

**Comment by idurvesh** [comment]
Having same issue, any solutions? I am on 0.9.39a
