### ISSUE TITLE
TypeLoadException: Could not load type 'GooglePlayServices.UnityCompat' from assembly 'Firebase.Editor'.

### ISSUE THREAD

**Issue by DuweMichael** [playgameservices/play-games-plugin-for-unity#1685]
I installed the latest version of Firebase messaging + analytics today in my Unity project. That lead me to error: https://github.com/playgameservices/play-games-plugin-for-unity/issues/1624

Followed guidelines there to update play games plugin. Now my game builds and runs ( as far as I can tell, I did not actually check any firebase related logic to ensure that is definitely triggering ), but I am getting spammed in my console regardless of editor or runtime;

TypeLoadException: Could not load type 'GooglePlayServices.UnityCompat' from assembly 'Firebase.Editor'.
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:197)

It's pretty clear I'm missing something I guess, but .. what? I got all of the files for messaging + analytics firebase, and did a clean install over the play games plugin version.

![firebase](https://cloud.githubusercontent.com/assets/13882463/24915998/bba94fe6-1ed0-11e7-99d4-20b3a5d89790.png)
![errorlog](https://cloud.githubusercontent.com/assets/13882463/24916036/e553f472-1ed0-11e7-8ad2-95c73a17ba61.png)

**Comment by Dod2** [comment]
I was having the same problem today. Solved it by deleting the editor folder inside the PlayServicesResolver folder and then reimporting it from any of the firebase unitypackages. 

Basically, use the firebase resolver. Haven't compiled and tested though.

**Comment by DuweMichael** [comment]
Thanks for the reply;

It seems you are right. Yesterday I ended up just clearing out all firebase and google play games references out once more, imported GPGS plugin first, and then pulled the firebase plugins in, ensuring the latest play services resolver version was used. Errors stopped and build runs again, but I'm not sure if the firebase stuff is working, as that part isn't tested yet. I'll make sure to update this later if I have some more information.

**Comment by EmYeuCoGiao** [comment]
I have same issue

**Comment by DuweMichael** [comment]
If you have the issue, I recommend just trying what I did:

1: Remove all of your firebase references. Make sure you get all files, as not all of them are grouped together afaik ( easiest way would be to import custom package on firebase package, and note all files in there )
2: do the same thing with google play games references, get rid of them everything.
3: just for safety reasons, restart your unity at this point. Make sure you're error free ( apart from potentially some firebase and GPG references you have in your project and stub them out for now )
4: Import your google play plugin. Take note of the resolver versions that is in the package
5: Import any relevant firebase package. Take note, it will have resolver files in there as well. Whatever is the oldest resolver package, ignore it.

Hopefully this will resolve it for you at this point.

**Comment by claywilkinson** [comment]
Thanks for the detailed instructions.  If you happen to have a the versions of the plugins that caused the problem, that would be helpful.  The goal is for the PlayServicesResolver to only be updated to the latest version.  If there is a bug in that logic, it would be nice to fix it.

**Comment by SrirachaSource** [comment]
I have this issue too, firebase sdk version is 4.0.1
It seems like play services or firebase updated some things on Mac, then I synced to windows and... bam

MissingMethodException: Method not found: 'GooglePlayServices.UnityCompat.get_InBatchMode'.
Firebase.Editor.GenerateXmlFromGoogleServicesJson.CheckConfiguration ()
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:249)

**Comment by YuliyF** [comment]
System.MissingMethodException: string GooglePlayServices.UnityCompat.GetApplicationId(UnityEditor.BuildTarget)
  at Firebase.Editor.GenerateXmlFromGoogleServicesJson.CheckConfiguration () [0x00040] in Z:\tmp\tmp.N3HX5mrT3b\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:229 
  at Firebase.Editor.GenerateXmlFromGoogleServicesJson..cctor () [0x00156] in Z:\tmp\tmp.N3HX5mrT3b\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:83 
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()
----
I even haven't disk Z

**Comment by monishchenko** [comment]
holy shi this is fresh as 4 years ago still !
