### ISSUE TITLE
After upgrade to 0.9.37 only see semi-transparent black screen

### ISSUE THREAD

**Issue by ipoppi** [playgameservices/play-games-plugin-for-unity#1692]
Hi guys,I encountered a strange question…
Sometimes, I only see semi transparent black screen on top of my application when I call Social.localUser.Authenticate() method, but not appear Connecting to "Game Name" and Google Play Services window. After tapping back button, it will show select google play account dialog. 
But sometimes it works ok.How to fix it? 

Unity v5.4.3f1
GPGS plugin 0.9.37

======================

04-13 16:34:02.971: W/Unity(17370): !!! [Play Games Plugin DLL] 04/13/17 16:34:02 +08:00 WARNING: Creating new PlayGamesPlatform
04-13 16:34:02.971: W/Unity(17370):  
04-13 16:34:02.971: W/Unity(17370): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-13 16:34:02.971: I/Unity(17370):  [Play Games Plugin DLL] 04/13/17 16:34:02 +08:00 DEBUG: Activating PlayGamesPlatform.
04-13 16:34:02.971: I/Unity(17370):  
04-13 16:34:02.971: I/Unity(17370): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-13 16:34:02.971: I/Unity(17370):  [Play Games Plugin DLL] 04/13/17 16:34:02 +08:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
04-13 16:34:02.971: I/Unity(17370):  
04-13 16:34:02.971: I/Unity(17370): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-13 16:34:02.971: I/Unity(17370):  [Play Games Plugin DLL] 04/13/17 16:34:02 +08:00 DEBUG: Creating platform-specific Play Games client.
04-13 16:34:02.971: I/Unity(17370):  
04-13 16:34:02.971: I/Unity(17370): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-13 16:34:02.971: I/Unity(17370):  [Play Games Plugin DLL] 04/13/17 16:34:02 +08:00 DEBUG: Creating Android IPlayGamesClient Client
04-13 16:34:02.971: I/Unity(17370):  
04-13 16:34:02.971: I/Unity(17370): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-13 16:34:02.971: W/GamesServiceBroker(8972): Client connected with SDK 10298000, Services 10298440, and Games 39080040
04-13 16:34:02.981: D/TokenFragment(17370): Creating fragment
04-13 16:34:02.981: D/TokenFragment(17370): onStart()
04-13 16:34:02.981: D/TokenFragment(17370): onResume called
04-13 16:34:02.981: W/PopupManager(17370): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
04-13 16:34:02.981: I/PersonaManager(3955): mKnoxInfo is empty
04-13 16:34:02.981: I/Unity(17370): ---- [0] -- 2097181
04-13 16:34:02.981: I/Unity(17370):  
04-13 16:34:02.981: I/Unity(17370): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
04-13 16:34:02.981: E/TokenFragment(17370): Already a pending token request!
04-13 16:34:02.981: D/TokenFragment(17370): Fragment exists.. calling processRequests
04-13 16:34:02.981: I/Timeline(17370): Timeline: Activity_launch_request id:com.XXXXXXX.XXXXXXXXXX time:38129798
04-13 16:34:02.991: I/Timeline(17370): Timeline: Activity_launch_request id:com.XXXXXXX.XXXXXXXXXX time:38129800
04-13 16:34:02.991: I/PersonaManager(3955): mKnoxInfo is empty
04-13 16:34:02.991: I/PersonaManager(3955): mKnoxInfo is empty
04-13 16:34:02.991: I/PersonaManager(3955): mKnoxInfo is empty
04-13 16:34:03.001: W/ResourcesManager(8972): getTopLevelResources: /data/app/com.google.android.play.games-1/base.apk / 1.0 running in com.google.android.gms rsrc of package com.google.android.play.games
04-13 16:34:03.011: E/Parcel(3955): Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
04-13 16:34:03.011: E/Parcel(3955): java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
04-13 16:34:03.011: E/Parcel(3955): 	at java.lang.Class.classForName(Native Method)
04-13 16:34:03.011: E/Parcel(3955): 	at java.lang.Class.forName(Class.java:324)
04-13 16:34:03.011: E/Parcel(3955): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
04-13 16:34:03.011: E/Parcel(3955): 	at android.os.Parcel.readParcelable(Parcel.java:2358)
04-13 16:34:03.011: E/Parcel(3955): 	at android.os.Parcel.readValue(Parcel.java:2264)
04-13 16:34:03.011: E/Parcel(3955): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
04-13 16:34:03.011: E/Parcel(3955): 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
04-13 16:34:03.011: E/Parcel(3955): 	at android.os.BaseBundle.getString(BaseBundle.java:920)
04-13 16:34:03.011: E/Parcel(3955): 	at android.content.Intent.getStringExtra(Intent.java:6183)
04-13 16:34:03.011: E/Parcel(3955): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2715)
04-13 16:34:03.011: E/Parcel(3955): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2180)
04-13 16:34:03.011: E/Parcel(3955): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6348)
04-13 16:34:03.011: E/Parcel(3955): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6119)
04-13 16:34:03.011: E/Parcel(3955): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170)
04-13 16:34:03.011: E/Parcel(3955): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3997)
04-13 16:34:03.011: E/Parcel(3955): 	at android.os.Binder.execTransact(Binder.java:453)
04-13 16:34:03.011: E/Parcel(3955): Caused by: java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
04-13 16:34:03.011: E/Parcel(3955): 	at java.lang.Class.classForName(Native Method)
04-13 16:34:03.011: E/Parcel(3955): 	at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-13 16:34:03.011: E/Parcel(3955): 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-13 16:34:03.011: E/Parcel(3955): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-13 16:34:03.011: E/Parcel(3955): 	... 16 more
04-13 16:34:03.011: E/Parcel(3955): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
04-13 16:34:03.011: D/ActivityManager(3955): AppLocked getMultiWindowStyle:null
04-13 16:34:03.011: D/ActivityManager(3955): AppLocked isLaunchedFromRecents:false hasMultiWindowStyle:false not normal : false

**Comment by MukeshMM** [comment]
i have same problem. Any solution?

**Comment by MukeshMM** [comment]
same error for me. If I get semi transparent black,press back then user login but unable to get Email of user.

**Comment by maynezhou** [comment]
I also ran into the same problem. Can someone solve it?
@claywilkinson help!

**Comment by maynezhou** [comment]
I also ran into the same problem. Can someone solve it?
@claywilkinson help!

**Comment by oneleaff** [comment]
I also encountered the same problem.How to solve the problem?

**Comment by MukeshMM** [comment]
Clearing app data may temporarily fix it. Also I was working with Firebase Cloud Messaging and notification are not shown when semi-transparent black exist even if Firebase FCM Server Send me success message in my server.If I clean app data and login then notification that is notification were not lost.

May be this problem occurs when app is closed by pressing Recent Apps button and closing (removing) app from Recent App List  in android.

**Comment by oneleaff** [comment]
@claywilkinson  help!

**Comment by claywilkinson** [comment]
Yep, I see it too.  I'll update the plugin shortly.

**Comment by oneleaff** [comment]
great

**Comment by claywilkinson** [comment]
The plugin has been updated to 0.9.38 and it fixes this issue.  There is no more flashing, etc.
