### ISSUE TITLE
crash after update to v0.9.37

### ISSUE THREAD

**Issue by nhatnd** [playgameservices/play-games-plugin-for-unity#1694]
I am using Unity 5.5.1f1 and I have updated plugin to v0.9.37.
The play-services version is 10.2.1.
When we authenticate to sign in a google account, we get this error and the game crashes:
`uth    : [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:-1429059290>, App: com.google.android.gms, Service: oauth2:https://www.googleapis.com/auth/games
04-14 10:13:34.021 11417 11626 E Auth    : dyp: Long live credential not available.
04-14 10:13:34.021 11417 11626 E Auth    : 	at dyq.b(:com.google.android.gms:3117)
04-14 10:13:34.021 11417 11626 E Auth    : 	at dyq.a(:com.google.android.gms:121)
04-14 10:13:34.021 11417 11626 E Auth    : 	at dww.a(:com.google.android.gms:451)
04-14 10:13:34.021 11417 11626 E Auth    : 	at dwv.a(:com.google.android.gms:31423)
04-14 10:13:34.021 11417 11626 E Auth    : 	at dwv.a(:com.google.android.gms:313)
04-14 10:13:34.021 11417 11626 E Auth    : 	at fcg.a(:com.google.android.gms:1200)
04-14 10:13:34.021 11417 11626 E Auth    : 	at fcf.a(:com.google.android.gms:569)
04-14 10:13:34.021 11417 11626 E Auth    : 	at fcf.a(:com.google.android.gms:195)
04-14 10:13:34.021 11417 11626 E Auth    : 	at dte.a(:com.google.android.gms:383)
04-14 10:13:34.021 11417 11626 E Auth    : 	at dte.a(:com.google.android.gms:232)
04-14 10:13:34.021 11417 11626 E Auth    : 	at dtn.a(:com.google.android.gms:1508)
04-14 10:13:34.021 11417 11626 E Auth    : 	at dtm.a(:com.google.android.gms:936)
04-14 10:13:34.021 11417 11626 E Auth    : 	at dtm.e(:com.google.android.gms:533)
04-14 10:13:34.021 11417 11626 E Auth    : 	at dtl.a(:com.google.android.gms:37)
04-14 10:13:34.021 11417 11626 E Auth    : 	at dvd.getAuthToken(:com.google.android.gms:196)
04-14 10:13:34.021 11417 11626 E Auth    : 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:214)
04-14 10:13:34.021 11417 11626 E Auth    : 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:113)
04-14 10:13:34.021 11417 11626 E Auth    : 	at android.os.Binder.execTransact(Binder.java:453)
04-14 10:13:34.061 11417 11626 W Auth    : [GoogleAuthUtil] GoogleAuthUtil
04-14 10:13:34.071 11417 11626 W GLSActivity: dug: BadAuthentication
04-14 10:13:34.071 11417 11626 W GLSActivity: 	at dtn.a(:com.google.android.gms:1525)
04-14 10:13:34.071 11417 11626 W GLSActivity: 	at dtm.a(:com.google.android.gms:936)
04-14 10:13:34.071 11417 11626 W GLSActivity: 	at dtm.e(:com.google.android.gms:533)
04-14 10:13:34.071 11417 11626 W GLSActivity: 	at dtl.a(:com.google.android.gms:37)
04-14 10:13:34.071 11417 11626 W GLSActivity: 	at dvd.getAuthToken(:com.google.android.gms:196)
04-14 10:13:34.071 11417 11626 W GLSActivity: 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:214)
04-14 10:13:34.071 11417 11626 W GLSActivity: 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:113)
04-14 10:13:34.071 11417 11626 W GLSActivity: 	at android.os.Binder.execTransact(Binder.java:453)
04-14 10:13:34.071  4640 18698 W PlayEventLogger: deferring log upload because couldn't retrieve auth token
04-14 10:13:34.091 11417 11626 E Auth    : [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:-2021391466>, App: com.google.android.gms, Service: oauth2:https://www.googleapis.com/auth/games
04-14 10:13:34.091 11417 11626 E Auth    : dyp: Long live credential not available.
04-14 10:13:34.091 11417 11626 E Auth    : 	at dyq.b(:com.google.android.gms:3117)
04-14 10:13:34.091 11417 11626 E Auth    : 	at dyq.a(:com.google.android.gms:121)
04-14 10:13:34.091 11417 11626 E Auth    : 	at dww.a(:com.google.android.gms:451)
04-14 10:13:34.091 11417 11626 E Auth    : 	at dwv.a(:com.google.android.gms:31423)
04-14 10:13:34.091 11417 11626 E Auth    : 	at dwv.a(:com.google.android.gms:313)
04-14 10:13:34.091 11417 11626 E Auth    : 	at fcg.a(:com.google.android.gms:1200)
04-14 10:13:34.091 11417 11626 E Auth    : 	at fcf.a(:com.google.android.gms:569)
04-14 10:13:34.091 11417 11626 E Auth    : 	at fcf.a(:com.google.android.gms:195)
04-14 10:13:34.091 11417 11626 E Auth    : 	at dte.a(:com.google.android.gms:383)
04-14 10:13:34.091 11417 11626 E Auth    : 	at dte.a(:com.google.android.gms:232)
04-14 10:13:34.091 11417 11626 E Auth    : 	at dtn.a(:com.google.android.gms:1508)
04-14 10:13:34.091 11417 11626 E Auth    : 	at dtm.a(:com.google.android.gms:936)
04-14 10:13:34.091 11417 11626 E Auth    : 	at dtm.e(:com.google.android.gms:533)
04-14 10:13:34.091 11417 11626 E Auth    : 	at dtl.a(:com.google.android.gms:37)
04-14 10:13:34.091 11417 11626 E Auth    : 	at dvd.getAuthToken(:com.google.android.gms:196)
04-14 10:13:34.091 11417 11626 E Auth    : 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:214)
04-14 10:13:34.091 11417 11626 E Auth    : 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:113)
04-14 10:13:34.091 11417 11626 E Auth    : 	at android.os.Binder.execTransact(Binder.java:453)
04-14 10:13:34.121 11417 11626 W Auth    : [GoogleAuthUtil] GoogleAuthUtil
04-14 10:13:34.131 11417 11626 W GLSActivity: dug: BadAuthentication
04-14 10:13:34.131 11417 11626 W GLSActivity: 	at dtn.a(:com.google.android.gms:1525)
04-14 10:13:34.131 11417 11626 W GLSActivity: 	at dtm.a(:com.google.android.gms:936)
04-14 10:13:34.131 11417 11626 W GLSActivity: 	at dtm.e(:com.google.android.gms:533)
04-14 10:13:34.131 11417 11626 W GLSActivity: 	at dtl.a(:com.google.android.gms:37)
04-14 10:13:34.131 11417 11626 W GLSActivity: 	at dvd.getAuthToken(:com.google.android.gms:196)
04-14 10:13:34.131 11417 11626 W GLSActivity: 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:214)
04-14 10:13:34.131 11417 11626 W GLSActivity: 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:113)
04-14 10:13:34.131 11417 11626 W GLSActivity: 	at android.os.Binder.execTransact(Binder.java:453)
04-14 10:13:34.131  4640 18699 W PlayEventLogger: deferring log upload because couldn't retrieve auth token
`
Do you have any idea what happen with our app ?

Thanks.

**Comment by VusalJalilov** [comment]
Same issue.

**Comment by claywilkinson** [comment]
Did you try re-running the setup for the plugin?  Maybe when you updated the plugin the configuration was overwritten.

If it still happens, please share a full log.

**Comment by claywilkinson** [comment]
Closing this one since it has been a while with no update. Please open another issue if you are still having problems.  Thanks!
