### ISSUE TITLE
failed to re-package resources

### ISSUE THREAD

**Issue by MobileGameArt** [playgameservices/play-games-plugin-for-unity#1695]
Hi all,

I need some help guys,
im using "Unity-Admob" plugin. Its builds and works fine. After i import "GooglePlayGamesPlugin-0.9.37" i cant build my project.  here the error. Sorry for my bad english =)

CommandInvokationFailure: Failed to re-package resources.
C:\Program Files (x86)\Android\android-sdk\build-tools\25.0.2\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "C:/Program Files (x86)/Android/android-sdk\platforms\android-25\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.google.example.games.mainlibproj:com.google.android.gms.ads.impl:com.google.android.gms.ads:com.google.android.gms.auth.api:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms.base:com.google.android.gms:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.gass:com.google.android.gms.nearby:com.google.android.gms.tasks:com.google.android.gms.tasks:android.support.v4:com.unity3d.ads -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-ads-10.2.0\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-ads-lite-10.2.0\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-auth-10.2.1\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-auth-base-10.2.1\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-base-10.2.0\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-base-10.2.1\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-basement-10.2.0\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-basement-10.2.1\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-drive-10.2.1\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-games-10.2.1\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-gass-10.2.0\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-nearby-10.2.1\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-tasks-10.2.0\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-tasks-10.2.1\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\support-v4-24.0.0\res" -S "C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\unity-ads\res"

stderr[
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <android.support.v7.widget.ButtonBarLayout>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_alert_dialog_button_bar_material.xml: note: using v17 attributes; synthesizing resource com.MGAstudio.JustTap:layout/abc_alert_dialog_button_bar_material for configuration v17.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.widget.DialogTitle>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource com.MGAstudio.JustTap:layout/abc_alert_dialog_material for configuration v17.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_dialog_title_material.xml: note: using v17 attributes; synthesizing resource com.MGAstudio.JustTap:layout/abc_dialog_title_material for configuration v17.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.widget.ActionBarContainer>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource com.MGAstudio.JustTap:layout/abc_screen_toolbar for configuration v21.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_search_view.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_search_view.xml: note: using v17 attributes; synthesizing resource com.MGAstudio.JustTap:layout/abc_search_view for configuration v17.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media.xml: note: using v17 attributes; synthesizing resource com.MGAstudio.JustTap:layout/notification_template_big_media for configuration v17.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource com.MGAstudio.JustTap:layout/notification_template_big_media_narrow for configuration v17.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_lines.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_lines.xml:77: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_lines.xml:96: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_lines.xml:64: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_lines.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_lines.xml: note: using v17 attributes; synthesizing resource com.MGAstudio.JustTap:layout/notification_template_lines for configuration v17.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_media.xml:43: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <include>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_media.xml:33: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_media.xml: note: using v17 attributes; synthesizing resource com.MGAstudio.JustTap:layout/notification_template_media for configuration v17.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_part_chronometer.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <Chronometer>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_part_chronometer.xml: note: using v17 attributes; synthesizing resource com.MGAstudio.JustTap:layout/notification_template_part_chronometer for configuration v17.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_part_time.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <DateTimeView>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_part_time.xml: note: using v17 attributes; synthesizing resource com.MGAstudio.JustTap:layout/notification_template_part_time for configuration v17.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\select_dialog_multichoice_material.xml: note: using v17 attributes; synthesizing resource com.MGAstudio.JustTap:layout/select_dialog_multichoice_material for configuration v17.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\select_dialog_singlechoice_material.xml: note: using v17 attributes; synthesizing resource com.MGAstudio.JustTap:layout/select_dialog_singlechoice_material for configuration v17.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\drawable\abc_ratingbar_indicator_material.xml:23: note: removing attribute http://schemas.android.com/apk/res/android:tileModeX from <bitmap>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\drawable\abc_ratingbar_indicator_material.xml: note: using v21 attributes; synthesizing resource com.MGAstudio.JustTap:drawable/abc_ratingbar_indicator_material for configuration v21.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\drawable\abc_ratingbar_small_material.xml:23: note: removing attribute http://schemas.android.com/apk/res/android:tileModeX from <bitmap>
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\drawable\abc_ratingbar_small_material.xml: note: using v21 attributes; synthesizing resource com.MGAstudio.JustTap:drawable/abc_ratingbar_small_material for configuration v21.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-base-10.2.0\res\values\values.xml:33: error: Attribute "imageAspectRatioAdjust" already defined with incompatible format.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-base-10.2.1\res\values\values.xml:34: Original attribute defined here.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-base-10.2.0\res\values\values.xml:46: error: Attribute "buttonSize" already defined with incompatible format.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-base-10.2.1\res\values\values.xml:47: Original attribute defined here.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-base-10.2.0\res\values\values.xml:54: error: Attribute "colorScheme" already defined with incompatible format.
C:\Users\Mert AYBAKIŞ\Documents\JustTap\Temp\StagingArea\android-libraries\play-services-base-10.2.1\res\values\values.xml:55: Original attribute defined here.
]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: C:\Program Files (x86)\Android\android-sdk\platforms\android-25\android.jar
applyFileOverlay for drawable
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_normal_background.9.png
trying overlaySet Key=common_google_signin_btn_icon_disabled.xml
trying overlaySet Key=common_google_signin_btn_icon_light.xml
trying overlaySet Key=common_google_signin_btn_icon_light_focused.xml
trying overlaySet Key=common_google_signin_btn_icon_light_normal.xml
trying overlaySet Key=common_google_signin_btn_icon_light_normal_background.9.png
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_dark_focused.xm<message truncated>

**Comment by sunal** [comment]
Mert Merhaba Pc Dosya Uzantılarından Anladım Türk olduğunu o yüzden türkçe cevap vereceğim bir çok kez karşılaştığımız bir sıkıntı. 
Genelde şu şekilde çözüyoruz android manifest dosyasını birleştirerek veya silip baştan yükleyerek sana bir link vereceğim orada arkadaş bahsetmiş yardımcı olmuş kolay gelsin.

link: http://answers.unity3d.com/questions/1074000/unity-5-android-build-failed-to-re-package-resourc.html

**Comment by MobileGameArt** [comment]
Selam Sunal,

Bu ablamızın anlattığı gibi Android Sdk nın içerisinde "google-play-service_lib" yok. Bundan dolayı res/values/version.xml i de kopyalayamıyorum.
![image](https://cloud.githubusercontent.com/assets/12517671/25040680/8ca6c2c4-2113-11e7-81ab-9aad8cd5c908.png)

Manifest i kontrol ettiğimde ise 2 adet manifest mevcut.
Assets/Plugin/Android altında bir adet, (bunu sildim)
Assets/Plugin/Android/MainLibProj altında bir tane mevcut.

Sonuç aynı. Build de hata alıyorum

**Comment by sunal** [comment]
Sdk Linkini paylaşır mısın bakıp geri dönüş yapayım.

**Comment by MobileGameArt** [comment]
@sunal Sdk yı Android Studio ile birlikte kendi sitesinden indiridm.
https://developer.android.com/studio/index.html#downloads

![image](https://cloud.githubusercontent.com/assets/12517671/25041761/eaaf9f1a-211a-11e7-9990-706baee59d5d.png)

SDK manager da da silip tekrar yükledim. Versionu yazıyor.

**Comment by sunal** [comment]
:) Hayır @MobileGameArt  Unity için kullandığını soruyorum admob Sdk sı

**Comment by MobileGameArt** [comment]
@sunal https://github.com/unity-plugins/Unity-Admob

**Comment by sunal** [comment]
@MobileGameArt  Sendeki Plugin yerine bunu kullanırsan daha stabil olur .

https://github.com/googleads/googleads-mobile-unity
Google Orjinali bu bi bunu indirip denersen Daha mantıklı olur bende sana bir örnek hazırlıyorum yollayacağım kolay gelsin .

**Comment by MobileGameArt** [comment]
@sunal Saolasın Sunal. Bu sdk yı kullanınca build sorunum kalmadı. Teşekkürler.
