### ISSUE TITLE
How to get banner height?

### ISSUE THREAD

**Issue by nikita-bosenko** [playgameservices/play-games-plugin-for-unity#1696]
I am trying to position all the elements on the page relatively to an AdMob banner so it does not cover important parts. But I don't quite get how to get exact height of the banner after it has been loaded and showed. Could you help with that please?

Thank you and sorry for a nooby question.

**Comment by mostdeep123** [comment]
custom size of the banner you can use : new AdSize (width banner, height banner) with integer type , doesn't use float. and now you can use it for custom size

**Comment by mostdeep123** [comment]
custom size of the banner you can use : new AdSize (width banner, height banner) with integer type , doesn't use float. and now you can use it for custom size

**Comment by claywilkinson** [comment]
If there is still an issue, please follow up by opening an issue with the admob plugin
