### ISSUE TITLE
GetServerAuthCode causes "invalid_grant: Code was already redeemed" error on serverside

### ISSUE THREAD

**Issue by sergeysychov** [playgameservices/play-games-plugin-for-unity#1699]
Hello gpgs developers! Thank you for this plugin, we re successfully using it for a year in a big project.

Although we encountered an issue after upgrading it from 9.4 to 10.2.1.
Currently "GetServerAuthCode" method returns authentication code and caches it therefore it always returns the same string until application is completely closed and started again. It causes google authentication web services return to our servers (wich is multiple and independent) an error "invalid_grant: Code was already redeemed.".

And looks like there's no options to request another token, because gpgs and it's internals are singleton and caches authCode. It looks like internally authCode changes nowhere even in case of player account is changed.

**Comment by claywilkinson** [comment]
Yes, it is a bug.  The  auth code should be cleared out on Signout.  I'll update the plugin shortly.  In the meantime add 
```
			authCode = null;
			email = null;
			idToken = null;
```
to AndroidTokenClient.Signout()
