### ISSUE TITLE
Couldn't make version v0.9.37 work on my project

### ISSUE THREAD

**Issue by alvinsartor** [playgameservices/play-games-plugin-for-unity#1700]
I tried in every possible way to run the 9.37 version on my phone: it was always crashing at the login, when I was calling

Social.localUser.Authenticate((bool success) => ...

Initially I thought about the the 10.0.1 vs 10.2.1 version problem of the libraries, but changing them couldn't fix anything. I tried the process at least 10 times, update every updatable thing, had a look at the manifests, redone the setup but nothing could fix it.

At the end, just before of giving up with GPGS I did the last trial moving back to the 9.36 with the 10.0.1 libraries and it solved everything. Luckly I could find the old version here in the commits of github but if you need it I'll attach the old version to this post.

[GooglePlayGamesPlugin-0.9.36.unitypackage.zip](https://github.com/playgameservices/play-games-plugin-for-unity/files/922729/GooglePlayGamesPlugin-0.9.36.unitypackage.zip)

Cheers.

**Comment by VusalJalilov** [comment]
I have exactly the same issue.

Switched back to 0.9.36 and no crashes now, but Login keeps failing...

**Comment by VusalJalilov** [comment]
I seem to be unable to keep 10.0.1 libraries. GPGS keeps on crashing even if built with v 0.9.36.

**Comment by haydin20** [comment]
who solved this problem ?
I have exactly the same issue !

**Comment by claywilkinson** [comment]
Can you share the  log of the crash when using 0.9.37?

**Comment by vexe** [comment]
@claywilkinson I have it right here

https://github.com/playgameservices/play-games-plugin-for-unity/issues/1720

**Comment by ricna** [comment]
Same problem here :/ Any solution?

**Comment by vexe** [comment]
@ricna I managed to work around it, see if this works for you: https://github.com/playgameservices/play-games-plugin-for-unity/issues/1690

**Comment by pradeepkulasekaran** [comment]
Check out #1723

**Comment by claywilkinson** [comment]
I recommend using 0.9.38  - which requires play-services-10.2+

If you really want to downgrade below 0.9.36 you must use play-services-10.1 or lower.

**Comment by ricna** [comment]
@vexe Thanks for attention, but I already tried it before... Going yo test with the 0.9.38 commited some hours ago. I don't want to downgrade (seems weird, does not works to me - also I'm using the Unity 5.6.0f3). Thanks @claywilkinson  for advice :)

**Comment by ricna** [comment]
Finally SOLVED!!! 
Upgrade your plugin to 0.9.38 and that's all folks :)
