### ISSUE TITLE
Play Service for iOS not compile

### ISSUE THREAD

**Issue by c00piser** [playgameservices/play-games-plugin-for-unity#1701]
When using the plugin with Android everything works great but when I change from Windows to macOS environment, the two files IOSClient.cs and IOSTokenClient.cs does not compile because of error CS0535. What I found out is that these two files did not implement all the interface members contains in TokenClient and IClientImpl. For now I just implement all the missing methods and it seems to work out fine. It's there any official fix that I'm not know about ?

**Comment by lightray1** [comment]
I have the same problem, how did you implement the interfaces?

**Comment by c00piser** [comment]
Since play service stopped supporting iOS,, i just disable it when developing for iOS. You can find the way to disable it here 
https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/README.md#excluding-all-google-play-game-services-when-building-for-ios

**Comment by ethan-tqa** [comment]
Honestly, if iOS is no longer supported, the relevant code should be removed to avoid further problems. Or at least add proper version check preprocessors to allow people on older Unity versions to keep using it while not causing troubles on newer Unity

**Comment by claywilkinson** [comment]
The updated plugin 0.9.38 compiles with iOS.  The iOS specific code is planned to be removed sometime in Q3 of 2017.

**Comment by NonaKovaleva** [comment]
I've imported 0.9.39a plugin and switched project to iOS, it's giving me folloing error.

Error	17	`GooglePlayGames.IOS.IOSClient' does not implement interface member `GooglePlayGames.IClientImpl.SetGravityForPopups(System.IntPtr, GooglePlayGames.BasicApi.Gravity)' and the best implementing candidate `GooglePlayGames.IOS.IOSClient.CreatePlatformConfiguration(GooglePlayGames.BasicApi.PlayGamesClientConfiguration)' return type `GooglePlayGames.Native.PInvoke.PlatformConfiguration' does not match interface member return type `void'	Assets/GooglePlayGames/Platforms/IOS/IOSClient.cs

How to solve this problem?

**Comment by Tehnorg** [comment]
NonaKovaleva i have that problem too on 0.9.39a
