### ISSUE TITLE
Multiplayer game ending abruptly right after starting

### ISSUE THREAD

**Issue by anujbora** [playgameservices/play-games-plugin-for-unity#1702]
* Unity 5.5.1f1
* All play services libraries are 10.0.1

I have a multiplayer game. I am testing it right now but after playing few matches, the game ends abruptly (only for one user at a time) and the user is sent back to main menu of the game. The issue occurs after few matches are played.

Below is the android log :
```04-15 01:28:51.479 556-3434/? W/ActivityManager: getRunningAppProcesses: caller 10104 does not hold REAL_GET_TASKS; limiting output
04-15 01:28:51.483 556-947/? W/ActivityManager: getRunningAppProcesses: caller 10130 does not hold REAL_GET_TASKS; limiting output
04-15 01:28:51.566 18826-16934/? I/libjingle: worker_thread:0xb84113b8 initialized=1
04-15 01:28:51.567 18826-16959/? I/libjingle: Channel disabled
04-15 01:28:51.567 18826-16959/? I/libjingle: Changing data state, recv=0 send=0
04-15 01:28:51.569 18826-16959/? I/libjingle: Destroyed channel
04-15 01:28:51.570 18826-18853/? I/RoomServiceStateMachine: Attempting to reconnect to: p_CIiW_eady7qb-ABCDE
```

**Comment by claywilkinson** [comment]
Can you share more of the log?

**Comment by anujbora** [comment]
The problem was fixed automatically once we released the app on the play store!

**Comment by anujbora** [comment]
Offtopic: We used google play games api and now as its deprecated for iOS, do you know any otheroptions which we can use so that Andorid and iOS users can compete against each other? Thanks!

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
