### ISSUE TITLE
Official Unity Plugin for the Google Mobile Ads SDK 

### ISSUE THREAD

**Issue by anil4040** [playgameservices/play-games-plugin-for-unity#1703]
Hi, Using Google Play Services v 0.9.37 Unity 5.5 I already tried to google it but didn't get any anything related to it. Problem is Google play services plugin not working properly even not showing any error except this in console

"Project GPM data does not exist. Creating new object. UnityEngine.Debug:Log(Object) Google.PackageManager.LoggingController:Log(String) Google.PackageManager.ProjectManagerController:InflateProjectRecord(String) Google.PackageManager.ProjectManagerController:.cctor() UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes() "

thanks in Advance. Really need help :)

**Comment by mostdeep123** [comment]
maybe you dont delete the .aar files below the appcompat file ?

**Comment by anil4040** [comment]
I didn't get it ?

**Comment by anil4040** [comment]
Answer 👍 
Unity not support network connection show this shows this warning and don't forget to add testers in developer console.
