### ISSUE TITLE
PlayGamesPlatform.Instance.GetAccessToken()

### ISSUE THREAD

**Issue by McRain** [playgameservices/play-games-plugin-for-unity#1704]
Hey.
For authentication in Firebase, it is recommended to use "googleIdToken" and "googleAccessToken":

[https://firebase.google.com/docs/auth/unity/google-signin#authenticate_with_firebase](https://firebase.google.com/docs/auth/unity/google-signin#authenticate_with_firebase)

But in the latest version of the plugin "Google Play Games plugin for Unity" removed the method
"PlayGamesPlatform.Instance.GetAccessToken ()"

Please, tell me, how I can get "AccessToken" by other methods.
Thanks

**Comment by Dod2** [comment]
Already solved in #1686
