### ISSUE TITLE
Callback on close "waiting room UI"

### ISSUE THREAD

**Issue by KrasovskyVictor** [playgameservices/play-games-plugin-for-unity#1708]
Hi!

Please pay a little bit attention to me.

How handle case, when user close "Waiting room UI" and then exit from matching game?

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
