### ISSUE TITLE
"OnPeersDisconnected" firing 2 times when participant left the game

### ISSUE THREAD

**Issue by KrasovskyVictor** [playgameservices/play-games-plugin-for-unity#1709]
In RTM, this event firing twice on leaving 1 player.

How can I fix it?

**Comment by rico345100** [comment]
Yes, have same issue here. Jeez, it's July 5th 2017, still didn't fixed?

**Comment by shefich** [comment]
I have the same issue. 
Sep.19 2018

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
