### ISSUE TITLE
IOSClient Error does not implement interface member

### ISSUE THREAD

**Issue by w2schmitt** [playgameservices/play-games-plugin-for-unity#1711]
Creating a fresh project and switching Unity for IOS Platform I got the following errors:
`Assets/GooglePlayGames/Platforms/IOS/IOSClient.cs(26,20): error CS0535: `GooglePlayGames.IOS.IOSClient' does not implement interface member `GooglePlayGames.IClientImpl.CreatePlatformConfiguration(GooglePlayGames.BasicApi.PlayGamesClientConfiguration)'`

and
`Assets/GooglePlayGames/Platforms/IOS/IOSClient.cs(26,20): error CS0535: `GooglePlayGames.IOS.IOSClient' does not implement interface member `GooglePlayGames.IClientImpl.CreateTokenClient(bool)'`

I saw the deprecation message, but I should at least be able to include the plugin in my project to use with android and build to iOS as well without having to remove the plugin.

**Comment by lightray1** [comment]
Maybe this can help you: 
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1701#issuecomment-296288515

**Comment by claywilkinson** [comment]
Agreed, it should at least build.  I'll update the plugin shortly.
