### ISSUE TITLE
Service Login-failed & App crashed when starting

### ISSUE THREAD

**Issue by haydin20** [playgameservices/play-games-plugin-for-unity#1716]
Hi, 

i am trying with examples in empty project. (Unity 5.5.2 and 5.6.0) 

Which version tried 0.9.37  can't login 0.9.36 crash when starting 

im tried all on empty project whats the problem ?

**Comment by claywilkinson** [comment]
Can you share the log of the crash?

**Comment by haydin20** [comment]
@claywilkinson i sent now 

`  --------- beginning of /dev/log/system
04-27 11:53:16.635 1820-2326/system_process I/ActivityManager: START u0 {act=com.google.android.gms.games.SIGN_IN flg=0x4000000 pkg=com.google.android.play.games cmp=com.google.android.play.games/com.google.android.gms.games.ui.signin.SignInActivity (has extras)} from pid -1
04-27 11:53:16.635 1820-2326/system_process D/ActivityManager: TopActivityInfo, pkgName: com.google.android.play.games activityName: com.google.android.gms.games.ui.signin.SignInActivity callingPackage: com.google.android.gms  bstSpecialAppKeyboardHandlingEnabled = false
04-27 11:53:16.635 1820-2326/system_process D/ActivityManager: Showing guidance for pkgName: com.google.android.play.games
04-27 11:53:16.645 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: event === app_launch
04-27 11:53:16.645 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: hiding guidance
04-27 11:53:16.645 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: hardKeyboard = 1
04-27 11:53:16.645 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: controllerType === Keyboard
04-27 11:53:16.655 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: appName: Google Play Oyunlar, currentPkg: com.google.android.play.games, event: app_launch, controller: Keyboard
04-27 11:53:16.655 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: appName: Google Play Oyunlar
04-27 11:53:16.655 4830-4830/? D/com.uncube.accountMyAccountAppLaunchReceiver: onReceive
04-27 11:53:16.655 4830-4830/? D/com.uncube.accountMyAccountAppLaunchReceiver: launchedPackage is com.google.android.play.games
04-27 11:53:16.655 4830-4830/? D/com.uncube.accountMyAccountAppLaunchReceiver: return
04-27 11:53:16.655 2306-2306/com.bluestacks.home D/Home.AppLaunchReceiver: *************************Received app launch broadcast
04-27 11:53:16.665 1820-2326/system_process E/SeNsOr-acc: Host sensor port is 2866
04-27 11:53:16.675 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: showing guidance for Google Play Oyunlar as not recommended ad found
04-27 11:53:16.675 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: no guidance for com.google.android.play.games.
04-27 11:53:16.695 2234-15275/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: command: ping
04-27 11:53:16.695 2234-15275/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: response: {"result":"ok"}
04-27 11:53:16.695 2234-15278/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: command: getdefaultlauncher
04-27 11:53:16.705 1820-2183/system_process D/dalvikvm: GC_FOR_ALLOC freed 1550K, 50% free 6714K/13356K, paused 18ms, total 18ms
04-27 11:53:16.725 1820-2183/system_process D/dalvikvm: GC_FOR_ALLOC freed 1540K, 50% free 6716K/13356K, paused 11ms, total 11ms
04-27 11:53:16.745 1820-2183/system_process D/dalvikvm: GC_FOR_ALLOC freed 1554K, 50% free 6717K/13356K, paused 10ms, total 10ms
04-27 11:53:16.745 1820-2743/system_process D/ActivityManager: TopActivityInfo, pkgName: com.google.android.play.games activityName: com.google.android.play.games/com.google.android.gms.games.ui.signin.SignInActivity callingPackage:   bstSpecialAppKeyboardHandlingEnabled = false
04-27 11:53:16.745 2306-2306/com.bluestacks.home D/Home.AppLaunchReceiver: APP LAUNCH com.google.android.play.games
04-27 11:53:16.765 1820-2273/system_process D/dalvikvm: GC_FOR_ALLOC freed 1560K, 50% free 6712K/13356K, paused 10ms, total 10ms
04-27 11:53:16.765 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: mBstOemFeatures === 2107393
04-27 11:53:16.765 1820-2743/system_process D/ActivityManager: Showing guidance for pkgName: com.google.android.play.games
04-27 11:53:16.765 1820-2743/system_process D/WindowManager: in computeScreenConfigurationLocked() -- hardKeyboardAvailable :true  mHardKeyboardAvailable :true   mHardKeyboardEnabled :true
04-27 11:53:16.795 1820-2273/system_process D/dalvikvm: GC_FOR_ALLOC freed 1521K, 50% free 6740K/13356K, paused 12ms, total 12ms
04-27 11:53:16.805 2234-15280/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: command: ping
04-27 11:53:16.805 2234-15280/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: response: {"result":"ok"}
04-27 11:53:16.805 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: event === app_launch
04-27 11:53:16.805 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: hiding guidance
04-27 11:53:16.805 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: hardKeyboard = 1
04-27 11:53:16.805 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: controllerType === Keyboard
04-27 11:53:16.805 2306-2306/com.bluestacks.home I/AdScreen: Starting AppClickUtil for com.google.android.play.games
04-27 11:53:16.805 2306-2306/com.bluestacks.home I/AdScreen: Starting intent for com.google.android.play.games
04-27 11:53:16.805 1820-2183/system_process D/WindowManager: in computeScreenConfigurationLocked() -- hardKeyboardAvailable :true  mHardKeyboardAvailable :true   mHardKeyboardEnabled :true
04-27 11:53:16.815 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: appName: Google Play Oyunlar, currentPkg: com.google.android.play.games, event: app_launch, controller: Keyboard
04-27 11:53:16.815 2234-15278/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: response: {"defaultLauncher":"com.bluestacks.gamepophome","result":"ok"}
04-27 11:53:16.815 2234-15281/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: command: getdefaultlauncher
04-27 11:53:16.815 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: appName: Google Play Oyunlar
04-27 11:53:16.815 2234-15282/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: command: ping
04-27 11:53:16.815 2234-15282/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: response: {"result":"ok"}
04-27 11:53:16.835 1820-2323/system_process D/dalvikvm: GC_FOR_ALLOC freed 1535K, 50% free 6767K/13356K, paused 14ms, total 14ms
04-27 11:53:16.835 4830-4830/? D/com.uncube.accountMyAccountAppLaunchReceiver: onReceive
04-27 11:53:16.835 4830-4830/? D/com.uncube.accountMyAccountAppLaunchReceiver: launchedPackage is com.google.android.play.games
04-27 11:53:16.835 4830-4830/? D/com.uncube.accountMyAccountAppLaunchReceiver: return
04-27 11:53:16.835 2234-15283/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: command: getlaunchactivityname com.google.android.play.games
04-27 11:53:16.835 2234-15283/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: response: {"value":"Play Oyunlar","result":"ok"}
04-27 11:53:16.845 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: showing guidance for Google Play Oyunlar as not recommended ad found
04-27 11:53:16.845 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: no guidance for com.google.android.play.games.
04-27 11:53:16.875 1820-4244/system_process D/dalvikvm: GC_FOR_ALLOC freed 1607K, 50% free 6725K/13356K, paused 16ms, total 16ms
04-27 11:53:16.875 5008-5008/com.google.android.play.games.ui I/SignInActivity: Transition from -1 to 0
04-27 11:53:16.885 1820-2743/system_process D/InputMethodManagerService: ime_enabled = false is same as last value, no change
04-27 11:53:16.915 1820-4244/system_process D/dalvikvm: GC_FOR_ALLOC freed 1549K, 50% free 6722K/13356K, paused 27ms, total 27ms
04-27 11:53:16.915 2306-2306/com.bluestacks.home D/Home.AppLaunchReceiver: *************************Received app launch broadcast
04-27 11:53:16.915 1820-1833/system_process D/WindowManager: topDisplayedActivityInfo, appToken: Token{4e988ac0 ActivityRecord{4e8592fc u0 com.google.android.play.games/com.google.android.gms.games.ui.signin.SignInActivity t5}}
04-27 11:53:16.915 1820-1838/system_process D/WindowManager: Sending appClickStats request with data: [package=com.google.android.play.games, appname=Google Play Oyunlar, appver=3.9.08 (3448271-070), clickloc=system_server]
04-27 11:53:16.925 1820-1833/system_process I/ActivityManager: Displayed com.google.android.play.games/com.google.android.gms.games.ui.signin.SignInActivity: +161ms
04-27 11:53:16.925 2234-15281/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: response: {"defaultLauncher":"com.bluestacks.gamepophome","result":"ok"}
04-27 11:53:16.945 1820-2658/system_process D/dalvikvm: GC_FOR_ALLOC freed 1544K, 50% free 6728K/13356K, paused 14ms, total 14ms
04-27 11:53:16.975 1820-2658/system_process D/dalvikvm: GC_FOR_ALLOC freed 1548K, 50% free 6726K/13356K, paused 12ms, total 12ms
04-27 11:53:17.025 1820-2658/system_process D/dalvikvm: GC_FOR_ALLOC freed 1545K, 50% free 6726K/13356K, paused 40ms, total 40ms
04-27 11:53:17.025 1820-1831/system_process D/InputMethodManagerService: ime_enabled = false is same as last value, no change
04-27 11:53:17.035 2372-2558/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:17.035 2306-2306/com.bluestacks.home D/Home.AppLaunchReceiver: APP LAUNCH com.google.android.play.games
04-27 11:53:17.045 2306-2306/com.bluestacks.home I/AdScreen: Starting AppClickUtil for com.google.android.play.games
04-27 11:53:20.555 5008-5008/com.google.android.play.games.ui E/ViewRootImpl: Attempting to destroy the window while drawing!
                                                                                window=android.view.ViewRootImpl@4e835450, title=
04-27 11:53:20.585 5008-5008/com.google.android.play.games.ui I/SignInActivity: Transition from 0 to 1
04-27 11:53:20.585 1820-2323/system_process V/WindowManager: isVisibleLw false for win : Window{4eb769b4 u0 com.google.android.play.games EXITING}
04-27 11:53:20.595 5008-5008/com.google.android.play.games.ui I/SignInActivity: Transition from 1 to 3
04-27 11:53:20.595 1820-4247/system_process D/InputMethodManagerService: ime_enabled = false is same as last value, no change
04-27 11:53:20.605 2372-3156/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:20.615 2372-15348/com.google.android.gms V/AccountUtils: 0 accounts found with uca feature
04-27 11:53:20.635 5008-5008/com.google.android.play.games.ui I/SignInActivity: Transition from 3 to 4
04-27 11:53:20.635 2372-2661/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:20.645 2372-15348/com.google.android.gms W/DataBroker: No player ID found when refreshing
04-27 11:53:20.665 1820-2042/system_process D/dalvikvm: GC_FOR_ALLOC freed 1547K, 50% free 6734K/13356K, paused 15ms, total 15ms
04-27 11:53:20.675 2372-3157/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:20.705 2327-2666/? W/GLSUser: [DeviceKeyStore] Cannot load key: Device key file not found.
04-27 11:53:20.705 2327-2666/? W/GLSUser: [DeviceKeyStore] Cannot load key: Device key file not found.
04-27 11:53:20.895 5008-5008/com.google.android.play.games.ui I/SignInActivity: Transition from 4 to 5
04-27 11:53:20.915 5008-5008/com.google.android.play.games.ui I/SignInActivity: Transition from 5 to 6
04-27 11:53:20.925 2372-2558/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:20.925 2372-3157/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:21.125 2327-2985/? W/Auth: [GetToken] GetToken failed with status code: UNREGISTERED_ON_API_CONSOLE
04-27 11:53:21.125 2372-2742/com.google.android.gms E/TokenRequestor: You have wrong OAuth2 related configurations, please check. Detailed error: UNREGISTERED_ON_API_CONSOLE
04-27 11:53:21.145 5008-5008/com.google.android.play.games.ui I/SignInActivity: Transition from 6 to 11
04-27 11:53:21.145 5008-5008/com.google.android.play.games.ui W/SignInActivity: onSignInFailed()...
04-27 11:53:21.145 5008-5008/com.google.android.play.games.ui W/SignInActivity: Sign in failed during 6
04-27 11:53:21.145 5008-5008/com.google.android.play.games.ui W/SignInActivity: ==> Returning non-OK result: 10002
04-27 11:53:21.155 1820-2657/system_process D/ActivityManager: TopActivityInfo, pkgName: com.RoosterGames.Racinghorizon activityName: com.RoosterGames.Racinghorizon/com.unity3d.player.UnityPlayerActivity callingPackage:   bstSpecialAppKeyboardHandlingEnabled = false
04-27 11:53:21.155 1820-2657/system_process D/ActivityManager: Showing guidance for pkgName: com.RoosterGames.Racinghorizon
04-27 11:53:21.165 2372-3157/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:21.165 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: mBstOemFeatures === 2107393
04-27 11:53:21.165 1820-2657/system_process D/WindowManager: in computeScreenConfigurationLocked() -- hardKeyboardAvailable :true  mHardKeyboardAvailable :true   mHardKeyboardEnabled :true
04-27 11:53:21.175 1820-2657/system_process D/WindowManager: topDisplayedActivityInfo, appToken: Token{4eb5b538 ActivityRecord{4e7f6a4c u0 com.RoosterGames.Racinghorizon/com.unity3d.player.UnityPlayerActivity t5}}
04-27 11:53:21.175 2234-15365/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: command: ping
04-27 11:53:21.175 2234-15365/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: response: {"result":"ok"}
04-27 11:53:21.175 1820-2657/system_process V/WindowManager: isVisibleLw false for win : Window{4e9225c0 u0 com.google.android.play.games/com.google.android.gms.games.ui.signin.SignInActivity}
04-27 11:53:21.185 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: event === app_launch
04-27 11:53:21.185 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: hiding guidance
04-27 11:53:21.185 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: hardKeyboard = 1
04-27 11:53:21.185 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: controllerType === Keyboard
04-27 11:53:21.185 2234-15366/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: command: getdefaultlauncher
04-27 11:53:21.195 2234-15367/com.bluestacks.BstCommandProcessor D/dalvikvm: GC_FOR_ALLOC freed 1140K, 25% free 5098K/6772K, paused 4ms, total 4ms
04-27 11:53:21.195 2234-15367/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: command: ping
04-27 11:53:21.195 2234-15367/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: response: {"result":"ok"}
04-27 11:53:21.205 2234-15368/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: command: getlaunchactivityname com.RoosterGames.Racinghorizon
04-27 11:53:21.205 2234-15368/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: response: {"value":"New Unity Project","result":"ok"}
04-27 11:53:21.205 1820-2184/system_process D/dalvikvm: GC_FOR_ALLOC freed 1516K, 50% free 6778K/13356K, paused 18ms, total 19ms
04-27 11:53:21.205 4820-4820/? V/GamesNativeSDK: Received Activity Resume Event.
04-27 11:53:21.205 2234-2234/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-Service: startService called with arg: GIAPPurchaseData
04-27 11:53:21.215 1820-2805/system_process E/SeNsOr-acc: Host sensor port is 2866
04-27 11:53:21.215 1820-1832/system_process D/SeNsOr-acc: Returning after resetting pending flag
04-27 11:53:21.215 1820-1832/system_process D/SeNsOr-acc: Returning after resetting pending flag
04-27 11:53:21.215 1820-2183/system_process D/InputMethodManagerService: ime_enabled = false is same as last value, no change
04-27 11:53:21.245 1820-2272/system_process D/dalvikvm: GC_FOR_ALLOC freed 1618K, 50% free 6729K/13356K, paused 12ms, total 12ms
04-27 11:53:21.265 1820-2272/system_process D/dalvikvm: GC_FOR_ALLOC freed 1560K, 50% free 6726K/13356K, paused 12ms, total 13ms
04-27 11:53:21.275 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: appName: New Unity Project, currentPkg: com.RoosterGames.Racinghorizon, event: app_launch, controller: Keyboard
04-27 11:53:21.275 2372-2661/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:21.285 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: appName: New Unity Project
04-27 11:53:21.295 4830-4830/? D/com.uncube.accountMyAccountAppLaunchReceiver: onReceive
04-27 11:53:21.295 4830-4830/? D/com.uncube.accountMyAccountAppLaunchReceiver: launchedPackage is com.RoosterGames.Racinghorizon
04-27 11:53:21.305 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: showing guidance for New Unity Project as not recommended ad found
04-27 11:53:21.305 2249-2249/com.bluestacks.appguidance D/GuidanceScreen: no guidance for com.RoosterGames.Racinghorizon.
04-27 11:53:21.305 2372-3157/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 10298000, Services 10298070, and Games 39080070
04-27 11:53:21.305 2306-2306/com.bluestacks.home D/Home.AppLaunchReceiver: *************************Received app launch broadcast
04-27 11:53:21.315 4820-4848/? I/Unity:  [Play Games Plugin DLL] 04/27/17 11:53:21 +03:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
                                         
                                        (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
04-27 11:53:21.325 2234-15366/com.bluestacks.BstCommandProcessor D/BstCommandProcessor-httpd: response: {"defaultLauncher":"com.bluestacks.gamepophome","result":"ok"}
04-27 11:53:21.345 1820-4244/system_process D/dalvikvm: GC_FOR_ALLOC freed 1537K, 50% free 6735K/13356K, paused 24ms, total 25ms
04-27 11:53:21.385 1820-4244/system_process D/dalvikvm: GC_FOR_ALLOC freed 1561K, 50% free 6734K/13356K, paused 23ms, total 23ms
04-27 11:53:21.415 1820-4244/system_process D/dalvikvm: GC_FOR_ALLOC freed 1556K, 50% free 6734K/13356K, paused 12ms, total 12ms
04-27 11:53:21.425 1466-1800/? D/audio_hw_primary: found out /dev/snd/pcmC0D0p
04-27 11:53:21.425 2306-2306/com.bluestacks.home D/Home.AppLaunchReceiver: APP LAUNCH com.RoosterGames.Racinghorizon
04-27 11:53:21.425 2306-2306/com.bluestacks.home I/AdScreen: Starting AppClickUtil for com.RoosterGames.Racinghorizon
04-27 11:53:21.425 1466-1800/? W/audio_hw_primary: out_write() limiting sleep time 69659 to 46439
04-27 11:53:21.425 2306-2306/com.bluestacks.home I/AdScreen: Starting intent for com.RoosterGames.Racinghorizon
04-27 11:53:21.445 2372-4272/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:21.445 2372-4267/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:21.455 2372-4272/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:21.455 2372-15349/com.google.android.gms V/AccountUtils: 0 accounts found with uca feature
04-27 11:53:21.465 2372-15349/com.google.android.gms W/DataBroker: No player ID found when refreshing
04-27 11:53:21.475 1820-2657/system_process D/dalvikvm: GC_FOR_ALLOC freed 1552K, 50% free 6734K/13356K, paused 13ms, total 13ms
04-27 11:53:21.475 4820-4820/? V/GamesNativeSDK: Play Games callback indicates connection failure.
04-27 11:53:21.475 4820-15271/? I/GamesNativeSDK: UI interaction required to connect to Google Play.
04-27 11:53:21.485 2372-4272/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:21.485 2372-4267/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:21.515 1466-1800/? W/audio_hw_primary: out_write() limiting sleep time 51518 to 46439
04-27 11:53:22.085 2221-3129/com.bluestacks.bstfolder D/dalvikvm: GC_FOR_ALLOC freed 647K, 25% free 2764K/3668K, paused 3ms, total 3ms
04-27 11:53:22.485 2372-2700/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 10298000, Services 10298070, and Games 39080070
04-27 11:53:22.495 2372-4272/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:22.505 2372-4272/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:22.515 2372-15395/com.google.android.gms V/AccountUtils: 0 accounts found with uca feature
04-27 11:53:22.515 2372-4272/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:22.515 2372-15395/com.google.android.gms W/DataBroker: No player ID found when refreshing
04-27 11:53:22.535 2372-4272/com.google.android.gms D/dalvikvm: GC_FOR_ALLOC freed 2507K, 25% free 7987K/10556K, paused 17ms, total 17ms
04-27 11:53:22.545 2372-4272/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:22.545 2372-2381/com.google.android.gms E/DataBuffer: Internal data leak within a DataBuffer object detected!  Be sure to explicitly call release() on all DataBuffer extending objects when you are done with them. (internal object: com.google.android.gms.common.data.DataHolder@4eac56b0)
04-27 11:53:22.555 2372-4267/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:22.555 4820-4820/? V/GamesNativeSDK: Play Games callback indicates connection failure.
04-27 11:53:22.555 4820-15271/? I/GamesNativeSDK: UI interaction required to connect to Google Play.
04-27 11:53:22.565 1820-2323/system_process D/dalvikvm: GC_FOR_ALLOC freed 1566K, 50% free 6729K/13356K, paused 12ms, total 12ms
04-27 11:53:23.565 2372-2558/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 10298000, Services 10298070, and Games 39080070
04-27 11:53:23.565 2372-4272/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:23.575 2372-4272/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:23.585 2372-4272/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:23.585 2372-15413/com.google.android.gms V/AccountUtils: 0 accounts found with uca feature
04-27 11:53:23.585 2372-15413/com.google.android.gms W/DataBroker: No player ID found when refreshing
04-27 11:53:23.585 2372-4272/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:23.595 2372-4267/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:23.595 4820-4820/? V/GamesNativeSDK: Play Games callback indicates connection failure.
04-27 11:53:23.595 4820-15271/? I/GamesNativeSDK: UI interaction required to connect to Google Play.
04-27 11:53:23.625 1820-3077/system_process D/dalvikvm: GC_FOR_ALLOC freed 1563K, 50% free 6723K/13356K, paused 12ms, total 12ms
04-27 11:53:24.605 2372-2661/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 10298000, Services 10298070, and Games 39080070
04-27 11:53:24.615 2372-4272/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:24.615 2372-4272/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:24.625 2372-4267/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:24.625 2372-15431/com.google.android.gms V/AccountUtils: 0 accounts found with uca feature
04-27 11:53:24.635 2372-15431/com.google.android.gms W/DataBroker: No player ID found when refreshing
04-27 11:53:24.635 2372-4272/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:24.635 2372-4267/com.google.android.gms W/GamesServiceBroker: Client connected with SDK 8487000, Services 10298070, and Games 39080070
04-27 11:53:24.635 4820-4820/? V/GamesNativeSDK: Play Games callback indicates connection failure.
04-27 11:53:24.635 4820-15271/? I/GamesNativeSDK: UI interaction required to connect to Google Play.
04-27 11:53:24.645 4820-4848/? I/Unity:  [Play Games Plugin DLL] 04/27/17 11:53:24 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
                                         
                                        (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
04-27 11:53:24.645 4820-4848/? I/Unity:  [Play Games Plugin DLL] 04/27/17 11:53:24 +03:00 DEBUG: AuthState == Unauthenticated calling auth callbacks with failure
                                         
                                        (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
04-27 11:53:24.645 4820-4848/? I/Unity: UpdateButtonVisibility:signedIn:False
                                         
                                        (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
04-27 11:53:24.655 4820-4848/? I/Unity:  [Play Games Plugin DLL] 04/27/17 11:53:24 +03:00 DEBUG: Invoking user callback on game thread
                                         
                                        (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
04-27 11:53:29.635 4820-15271/? D/dalvikvm: threadid=12: thread exiting, not yet detached (count=0)
04-27 11:53:29.635 4820-15271/? V/GamesNativeSDK: Detaching from JVM on thread main_dispatch
04-27 11:53:41.795 4820-4823/? D/dalvikvm: GC_CONCURRENT freed 765K, 21% free 3108K/3912K, paused 0ms+1ms, total 6ms
04-27 11:54:12.085 2221-3129/com.bluestacks.bstfolder D/dalvikvm: GC_FOR_ALLOC freed 646K, 25% free 2764K/3668K, paused 3ms, total 4ms
04-27 11:54:21.015 4932-5063/com.android.vending I/PlayCommon: [301] com.google.android.play.a.g.e(940): Preparing logs for uploading
04-27 11:54:21.015 4932-5063/com.android.vending I/PlayCommon: [301] com.google.android.play.a.g.e(942): No file ready to send
04-27 11:54:21.195 4932-4946/com.android.vending I/PlayCommon: [274] com.google.android.play.a.g.e(940): Preparing logs for uploading
04-27 11:54:21.195 4932-4946/com.android.vending I/PlayCommon: [274] com.google.android.play.a.g.e(942): No file ready to send`

**Comment by pradeepkulasekaran** [comment]
Refer #1723

**Comment by claywilkinson** [comment]
This is fixed.  Please try using 0.9.39a.
