### ISSUE TITLE
LeaderboardCollection.Social only returns own user

### ISSUE THREAD

**Issue by pasier** [playgameservices/play-games-plugin-for-unity#1719]
Im using this call and `data` only contains my score when the scope is `LeaderboardCollection.Social`

```
PlayGamesPlatform.Instance.LoadScores(
                    GooglePlayGamesHelper.LEADERBOARD_TAG,
                    LeaderboardStart.TopScores,
                    25,
                    LeaderboardCollection.Social,
                    LeaderboardTimeSpan.AllTime, (data) =>
                    {
```

If I use the `LeaderboardCollection.Global` scope it seems to work well.

**Comment by artur-pinheiro** [comment]
It is happening to me as well.
Any luck?

**Comment by claywilkinson** [comment]
This is expected behavior.  Since Google Plus is no longer used by Play Game Services, there are no social players other than yourself.  See https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html for more information.
