### ISSUE TITLE
0.9.37 Hard crash "JNI DETECTED ERROR IN APPLICATION: java_class == null'"

### ISSUE THREAD

**Issue by vexe** [playgameservices/play-games-plugin-for-unity#1720]
The same thing happened couple of weeks ago and we updated to 0.9.37 and it fixed it. Now it's happening again, we're updated to the latest version. 

What's the reason behind this? How can it just start crashing on its own if the version is still the same? is it some sort of Google/auth code that they update and screw up or something?

I reimported 0.9.37 just to make sure I'm not missing any files, and re-ran the Google Play/Android setup in Unity, it told me it resolved some stuff, still the same issue.

> 04-28 22:46:04.145   978   995 D Unity   : GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_t
> 04-28 22:46:04.145   978   995 D Unity   : o_texture GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image 
> 04-28 22:46:04.145   978   995 D Unity   : GL_OES_copy_image GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures 
> 04-28 22:46:06.854   978   995 I Unity   : [Time] Starting session
> 04-28 22:46:06.854   978   995 I Unity   :  
> 04-28 22:46:06.854   978   995 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 04-28 22:46:06.854   978   995 I Unity   : 
> 04-28 22:46:07.079   978   995 I Unity   : Building GPG services, implicitly attempts silent auth
> 04-28 22:46:07.079   978   995 I Unity   :  
> 04-28 22:46:07.079   978   995 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 04-28 22:46:07.079   978   995 I Unity   : 
> 04-28 22:46:07.176   978   978 D Unity   : CBPlugin: Plugin Initialized
> 04-28 22:46:07.386  1088  1088 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 04-28 22:46:07.387  1088  1088 F DEBUG   : Build fingerprint: 'samsung/heroltebmc/heroltebmc:7.0/NRD90M/G930W8VLU2BQB6:user/release-keys'
> 04-28 22:46:07.387  1088  1088 F DEBUG   : Revision: '8'
> 04-28 22:46:07.388  1088  1088 F DEBUG   : ABI: 'arm'
> 04-28 22:46:07.388  1088  1088 F DEBUG   : pid: 978, tid: 995, name: main  >>> com.tinytitanstudios.TrainChu <<<
> 04-28 22:46:07.389  1088  1088 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
> 04-28 22:46:07.403  1088  1088 F DEBUG   : Abort message: 'art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: java_class == null'
> 04-28 22:46:07.403  1088  1088 F DEBUG   :     r0 00000000  r1 000003e3  r2 00000006  r3 00000008
> 04-28 22:46:07.403  1088  1088 F DEBUG   :     r4 db981978  r5 00000006  r6 db981920  r7 0000010c
> 04-28 22:46:07.403  1088  1088 F DEBUG   :     r8 e577d464  r9 00000000  sl db97f72c  fp e5769754
> 04-28 22:46:07.403  1088  1088 F DEBUG   :     ip 0000000b  sp db97f638  lr e7b99957  pc e7b9c1c0  cpsr 600d0010
> 04-28 22:46:07.433  1088  1088 F DEBUG   : 
> 04-28 22:46:07.433  1088  1088 F DEBUG   : backtrace:
> 04-28 22:46:07.433  1088  1088 F DEBUG   :     #00 pc 0004a1c0  /system/lib/libc.so (tgkill+12)
> 04-28 22:46:07.434  1088  1088 F DEBUG   :     #01 pc 00047953  /system/lib/libc.so (pthread_kill+34)
> 04-28 22:46:07.434  1088  1088 F DEBUG   :     #02 pc 0001d955  /system/lib/libc.so (raise+10)
> 04-28 22:46:07.434  1088  1088 F DEBUG   :     #03 pc 000194a1  /system/lib/libc.so (__libc_android_abort+34)
> 04-28 22:46:07.434  1088  1088 F DEBUG   :     #04 pc 000170e8  /system/lib/libc.so (abort+4)
> 04-28 22:46:07.434  1088  1088 F DEBUG   :     #05 pc 0031ada5  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+252)
> 04-28 22:46:07.434  1088  1088 F DEBUG   :     #06 pc 000b4ac7  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+866)
> 04-28 22:46:07.434  1088  1088 F DEBUG   :     #07 pc 00239b55  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1584)
> 04-28 22:46:07.434  1088  1088 F DEBUG   :     #08 pc 00239e1f  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+66)
> 04-28 22:46:07.434  1088  1088 F DEBUG   :     #09 pc 0026053f  /system/lib/libart.so (_ZN3art3JNI21RegisterNativeMethodsEP7_JNIEnvP7_jclassPK15JNINativeMethodib+2214)
> 04-28 22:46:07.434  1088  1088 F DEBUG   :     #10 pc 0027da29  /system/lib/libart.so (_ZN3art3JNI15RegisterNativesEP7_JNIEnvP7_jclassPK15JNINativeMethodi+12)
> 04-28 22:46:07.434  1088  1088 F DEBUG   :     #11 pc 001193ab  /data/app/com.tinytitanstudios.TrainChu-1/lib/arm/libgpg.so (_ZN3gpg9JavaClass23FinishClassRegistrationEP7_JNIEnvP7_jclass+62)
> 04-28 22:46:07.435  1088  1088 F DEBUG   :     #12 pc 00119f4f  /data/app/com.tinytitanstudios.TrainChu-1/lib/arm/libgpg.so (_ZN3gpg9JavaClass8RegisterEP7_JNIEnvRKNS_13JavaReferenceE+222)
> 04-28 22:46:07.435  1088  1088 F DEBUG   :     #13 pc 0011a3f3  /data/app/com.tinytitanstudios.TrainChu-1/lib/arm/libgpg.so (_ZN3gpg9JavaClass34RegisterEmbeddedDexClassesInternalERKNS_13JavaReferenceEPbPKcS6_RKSsRKSt6vectorIPS0_SaISA_EE+666)
> 04-28 22:46:07.435  1088  1088 F DEBUG   :     #14 pc 0011a55f  /data/app/com.tinytitanstudios.TrainChu-1/lib/arm/libgpg.so (_ZN3gpg9JavaClass32RegisterEmbeddedNearbyDexClassesERKNS_13JavaReferenceE+58)
> 04-28 22:46:07.435  1088  1088 F DEBUG   :     #15 pc 001154ad  /data/app/com.tinytitanstudios.TrainChu-1/lib/arm/libgpg.so (_ZNK3gpg28AndroidPlatformConfiguration5ValidEv+92)
> 04-28 22:46:07.435  1088  1088 F DEBUG   :     #16 pc 0013dfcd  /data/app/com.tinytitanstudios.TrainChu-1/lib/arm/libgpg.so (_ZN3gpg12GameServices7Builder6CreateERKNS_28AndroidPlatformConfigurationE+52)
> 04-28 22:46:07.435  1088  1088 F DEBUG   :     #17 pc 00160363  /data/app/com.tinytitanstudios.TrainChu-1/lib/arm/libgpg.so (GameServices_Builder_Create+14)
> 04-28 22:46:07.435  1088  1088 F DEBUG   :     #18 pc 0000aadc  <anonymous:c22f2000>
> 04-28 22:46:10.963  3653  3781 I ActivityManager: Start proc 1094:com.samsung.android.scloud:autobackupmgr/5009 for service com.samsung.android.scloud/.backup.auto.AutoBackupManagerService
> 04-28 22:46:10.977  3653  4978 I ActivityManager: DSS on for com.samsung.android.scloud and scale is 1.0
> 04-28 22:46:14.948  3653  3781 I ActivityManager: Waited long enough for: ServiceRecord{c1dd400 u0 com.sec.android.daemonapp/.appservice.WeatherService}
> 04-28 22:46:19.508  3653  1604 W ActivityManager:   Force finishing activity com.tinytitanstudios.TrainChu/com.unity3d.player.UnityPlayerNativeActivity
> 04-28 22:46:19.510  3653  1604 D ActivityManager: moveToFront() : reason=finishActivity adjustFocus setFocusedActivity isAttached=true TaskRecord{6a3e805d0 #2 A=com.sec.android.app.launcher U=0 StackId=0 sz=1}
> 04-28 22:46:19.511  3653  1604 D ActivityManager: setFocusStackUnchecked: reason=finishActivity adjustFocus setFocusedActivity focusCandidate=ActivityStack{4f7cbc4d0 stackId=0, 2 tasks} caller=com.android.server.am.ActivityStack.moveToFront:873 com.android.server.am.ActivityStackSupervisor.moveActivityStackToFront:1983 
> 04-28 22:46:19.649  3653  4644 I ActivityManager: Process com.tinytitanstudios.TrainChu (pid 978) has died(153,821)
> 04-28 22:46:19.649  3653  4644 D ActivityManager: cleanUpApplicationRecord -- 978
> 04-28 22:46:19.698  3653  4644 D ActivityManager: resumeTopActivityInnerLocked() : #0 prevTask=null next=ActivityRecord{3b9049d0 u0 com.sec.android.app.launcher/.activities.LauncherActivity t2} mFocusedStack=ActivityStack{4f7cbc4d0 stackId=0, 2 tasks}
> 04-28 22:46:19.712  3653  4644 D ActivityManager: mActivityResumeBooster.acquire()
> 04-28 22:46:19.750  3653  4644 I ActivityManager: Config changes=480 {0 1.0 themeSeq = 0 showBtnBg = 0 302mcc220mnc [en_CA] ldltr sw360dp w360dp h616dp 480dpi nrml long port finger -keyb/v/h -nav/h mkbd/h s.179}
> 04-28 22:46:20.073  3653  3917 D ActivityManager: post active user change for 0 fullscreen true isHomeActivity() true
> 04-28 22:46:20.206  3653  3781 D ActivityManager: mActivityResumeBooster.release()
> 04-28 22:46:20.206  3653  3781 D ActivityManager: mActivityResumeBoosterTail.acquire()

**Comment by vexe** [comment]
Had to downgrade to 0.9.21... This is just gross.

How do I find 0.9.36, why isn't it in the old-builds folder?

**Comment by VusalJalilov** [comment]
https://github.com/playgameservices/play-games-plugin-for-unity/releases

**Comment by vexe** [comment]
@claywilkinson any thoughts on those errors?

**Comment by VusalJalilov** [comment]
I gave up on 0.9.37...

**Comment by bbb0x** [comment]
Getting this error in 0.9.36 after I downgraded from 0.9.37 to avoid another error...lol

**Comment by VusalJalilov** [comment]
Delete the extra folder in your Android SDK pack. Then run SDK Manager and re-install it.

**Comment by vexe** [comment]
Guys, I managed to solve my problem. I don't know if it helps you...

https://github.com/playgameservices/play-games-plugin-for-unity/issues/1690

**Comment by pradeepkulasekaran** [comment]
Check out #1723
