### ISSUE TITLE
ERROR: Unable to find dependency com.google.android.gms play-services-base [10.2.4]

### ISSUE THREAD

**Issue by ulterr** [playgameservices/play-games-plugin-for-unity#1721]
Hi I got into a trouble with google play games plug in. So I already have newest build tool, repository, support repository, and the play services in sdk manager

But i still got these error in unity

` Google.JarResolver.ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-base:[10.2.4]
   at Google.JarResolver.PlayServicesSupport.GetDependencies (Google.JarResolver.Dependency dep) [0x00000] in <filename unknown>:0
   at Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest, System.String destDirectory) [0x00000] in <filename unknown>:0
   at GooglePlayServices.ResolverVer1_1.DoResolutionNoAndroidPackageChecks (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation) [0x00000] in <filename unknown>:0
UnityEngine.Debug:LogError(Object)
GooglePlayServices.ResolverVer1_1:DoResolutionNoAndroidPackageChecks(PlayServicesSupport, String, OverwriteConfirmation)
GooglePlayServices.<DoResolution>c__AnonStorey5:<>m__8()
GooglePlayServices.ResolverVer1_1:DoResolution(PlayServicesSupport, String, OverwriteConfirmation, Action)
GooglePlayServices.PlayServicesResolver:Resolve(Action)
GooglePlayServices.PlayServicesResolver:MenuResolve()`

and 

`ERROR: Unable to find dependency com.google.android.gms play-services-base [10.2.4] in ($SDK\extras\android\m2repository, $SDK\extras\google\m2repository, $SDK\extras\android\m2repository, $SDK\extras\google\m2repository)
UnityEngine.Debug:Log(Object)
Google.JarResolver.PlayServicesSupport:Log(String, Boolean)
Google.JarResolver.PlayServicesSupport:FindCandidate(Dependency)
Google.JarResolver.PlayServicesSupport:GetDependencies(Dependency)
Google.JarResolver.PlayServicesSupport:ResolveDependencies(Boolean, String)
GooglePlayServices.ResolverVer1_1:DoResolutionNoAndroidPackageChecks(PlayServicesSupport, String, OverwriteConfirmation)
GooglePlayServices.<DoResolution>c__AnonStorey5:<>m__8()
GooglePlayServices.ResolverVer1_1:DoResolution(PlayServicesSupport, String, OverwriteConfirmation, Action)
GooglePlayServices.PlayServicesResolver:Resolve(Action)
GooglePlayServices.PlayServicesResolver:AutoResolve()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()`

I already upgraded my play services, repository and repository support to newest version and found 10.2.4 base files deep inside google repository folder :(

**Comment by DiegoHerreraRomero** [comment]
i have the same problem :(

**Comment by DiegoHerreraRomero** [comment]
I think i resolve it.
-Go to the file in your project Assets/GooglePlayGames/PluginVersion.cs, inside change the PlayServicesVersionConstraint to "10.2.1" (the default value is "10+"). Save and go to unity.
-In the menu go to Assets > Play Services Resolver > Android Resolver > Resolve Clients Jar. If the program ask you about change of the version press ok.
And the app should it work.

PS: Sorry for my English, is too bad :( .

**Comment by ulterr** [comment]
Thanks a lot for the help
The error did disappear but there's still this message when i try to run it
`
Google.JarResolver.PlayServicesSupport:ResolveDependencies(Boolean, String)
GooglePlayServices.ResolverVer1_1:DoResolutionNoAndroidPackageChecks(PlayServicesSupport, String, OverwriteConfirmation)
GooglePlayServices.<DoResolution>c__AnonStorey5:<>m__8()
GooglePlayServices.ResolverVer1_1:DoResolution(PlayServicesSupport, String, OverwriteConfirmation, Action)
GooglePlayServices.PlayServicesResolver:Resolve(Action)
GooglePlayServices.PlayServicesResolver:AutoResolve()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()`

**Comment by DiegoHerreraRomero** [comment]
Try to build and test, maybe don't affect 'cause is a warning

**Comment by rjeike** [comment]
Thanks Diego, that solved the problem for me.

**Comment by ramioooz** [comment]
Thank you @DiegoHerreraRomero

this problem has something to do with Unity compatability with the latest Android SDK 
I hate it when new SDK releases broke everything else. It took me the whole day tring to solve it.

thanks to you now I can continue from where I left off.
Wishing you happy developing,
Cheers

**Comment by 304andres** [comment]
I have the same problem but whit play-service-ad-lite, and the Diego´s method doesnt solved it.

**Comment by DianaCaro** [comment]
@DiegoHerreraRomero GRACIAS!! llevaba 5 días buscando una solución, GRACIAS! no sabes la frustración que tenía, gracias por compartir <3

**Comment by guilhermeouriques** [comment]
I tried Diego's solution and apparently it worked, no more error in Unity console. But when I tested in my tablet, google api crashes when trying to login and I can't test the leaderboard because the login doesn't work. :/

**Comment by rmasarovic** [comment]
@DiegoHerreraRomero pls which sdk tools and google service revisiou you use i have still error

**Comment by MarcoWilliamsPF** [comment]
http://www.hashbanggames.com/blog/android-sdk-tools-update-breaks-unity-android-builds

**Comment by DozeX** [comment]
MarcoWilliamsPF: good if the links work. shitty site.

**Comment by ASDFD12** [comment]
Some details for method by @DiegoHerreraRomero.
I try method @DiegoHerreraRomero but it dont work. I change PlayServicesVersionConstraint to "10.2.4" - latest at this time and resolved was fail. Cause in : When I import Google play services (latest)  - it use library  play-services-basement-10.2.1.aar in Plugins/Android folder but Jar resolver try use latest version from sdk folder. I remove  play-services-basement-10.2.1.aar in Plugins/Android folder and resolved Completed after call Assets > Play Services Resolver > Android Resolver > Resolve Clients Jar. Sorry for my language)

**Comment by 304andres** [comment]
Well guys i upload a package whit the rev39, is only the extras folder, copy and replace the one in your sdk, it work for me! I hope it work for you all.
https://drive.google.com/file/d/0BwxP9r-K0LCOQjU0ZjRMQ3pTLVk/view?usp=sharing

**Comment by jaroslaw-weber** [comment]
@DiegoHerreraRomero cant use this since i dont use google play plugin. tried to change versions in other plugins but not working (missed something?).

Anyway it broke after upgrading from rev38 to rev39, also there are dependencies no not sure why jar resolver cant find them. Directory changed?

**Comment by fliperamma** [comment]
Got it working by downloading the latest package [here](https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/current-build) and following these instructions on GPGS repo, before importing the new version to Unity ... I also had to restart Unity some times:

> The Play Services Jar Resolver has changed to be a DLL, in order to import this
> correctly, you need to delete the Assets/PlayServicesResolver folder in your
> project ***BEFORE*** importing this plugin.  You may also need to restart Unity
> to correctly initialize the DLLs in the editor.
> 
> IF YOU STILL HAVE PROBLEMS:
> 
> If you have already integrated the plugin and want to upgrade it to a newer version,
> you must delete the Assets/GooglePlayGames folder, then import the new package.
> 
> 
> After upgrading, redo setup (click "Google Play Games | Android Setup" and/or
> "Google Play Games | iOS Setup" on the menu). Do this even if you had already done
> this before on this project.

Not sure if its also your case, but I've also updated my Android SDK when facing another problem. If you don't know how to do it, you can follow the thread on how to update the Android SDK [here](https://github.com/playgameservices/play-games-plugin-for-unity/issues/1684#issuecomment-297817961).

**Comment by jaroslaw-weber** [comment]
actually problem disappeared when i updated google jar resolver plugin.

**Comment by claywilkinson** [comment]
This is a bug in the jar resolver.  If you update the jar resolver to the latest, or update this plugin to 0.9.38a you'll get the fix.

**Comment by hawkzey** [comment]
I have done both @claywilkinson and i am still not able to connect to the playstore >.<

**Comment by NickPax** [comment]
Thank you, Diego!
