### ISSUE TITLE
Game Crashed at Sign In

### ISSUE THREAD

**Issue by siddharth3322** [playgameservices/play-games-plugin-for-unity#1724]
At Sign Up time my app get crashed using this plugin.
Here are error log that I was getting.

![screen shot 2017-05-03 at 11 32 39 pm](https://cloud.githubusercontent.com/assets/3082151/25674647/4541a976-3059-11e7-87aa-e16aa3dbdd58.png)

Here are Plugins/Android folder structure:
![screen shot 2017-05-03 at 11 34 45 pm](https://cloud.githubusercontent.com/assets/3082151/25674685/6e9dd600-3059-11e7-99c3-d569271031d5.png)

Please reply me for this, what I require to do for solving this error.

**Comment by drSpritz** [comment]
I have similar issue but not of all devices, some devices work fine.

**Comment by pradeepkulasekaran** [comment]
Refer #1723

**Comment by siddharth3322** [comment]
@drSpritz But how in this way I can publish my game!!! if even my device not working properly with Google Play services.

@pradeepkulasekaran  My issue and that other thread point is complete different.
As per my past experience I have correct .aar files in Android folder. So I become confuse more.

Please reply me someone regarding this.

**Comment by pradeepkulasekaran** [comment]
I request you to update to the latest plugin as i mentioned since it will resolve the error with .aar files and hopefully run on all devices which are greater than android 4.4.

**Comment by siddharth3322** [comment]
For Google Play Games already I was using GooglePlayGamesPlugin-0.9.37
So what I require to update?

**Comment by pradeepkulasekaran** [comment]
Are you using NearBy Connections in your game? Both Android and IOS?

**Comment by gametrainee** [comment]
Same Issue With me i update play service version and its crashed on login

**Comment by gametrainee** [comment]
i am no using near By Connection and it crashed in android

**Comment by pradeepkulasekaran** [comment]
show me ur log..

**Comment by gametrainee** [comment]
![image](https://cloud.githubusercontent.com/assets/19944132/25697828/1e117b84-30da-11e7-9842-e56a399a12e8.png)

**Comment by gametrainee** [comment]
![image](https://cloud.githubusercontent.com/assets/19944132/25697847/2e277e88-30da-11e7-8147-69abdecbfa90.png)

**Comment by gametrainee** [comment]
@pradeepkulasekaran  Got it What is issue?

**Comment by pradeepkulasekaran** [comment]
What version of plugin u are using and what version is the arr files..

**Comment by gametrainee** [comment]
Plugin version GooglePlayGamesPlugin-0.9.37 
arr Version 10.0.1

**Comment by gametrainee** [comment]
How can i update arr files ?
"For latest version 0.9.37 the arr files should be updated to 10.2.1"

**Comment by pradeepkulasekaran** [comment]
Do a fresh install.. Refer #1723
The plugin will automatically update arr files to 10.2.1

**Comment by siddharth3322** [comment]
Even I got .aar file 10.0.1 when I install new plugin in Unity project rather than 10.2.1 version.

**Comment by pradeepkulasekaran** [comment]
i update the steps
Close and Reopen Unity to delete the temp cache created by old plugin

**Comment by siddharth3322** [comment]
But I have created new project so its first time google play plugin install for me.

**Comment by pradeepkulasekaran** [comment]
Close Unity and browse to the Android folder delete 10.0.1 if there is any and Reopen Unity. Make sure 10.0.1 arr is not present while updating the plugin.

Sorry missed few while documenting.

**Comment by siddharth3322** [comment]
Then at where I can find new .aar files to replace??

**Comment by pradeepkulasekaran** [comment]
The plugin will automatically download the files to the project..

**Comment by siddharth3322** [comment]
Okay after deleting old aar files, I will see what happen when I open Unity project.
I will get back to you here with results :)

**Comment by AlvaroFalcon** [comment]
Hi, I'm having a similar issue, already deleted all the 10.0.1 files, reopened Unity and tried to setup Androi again but I'm having an error "Invalid classname: Exception has been thrown by the target of an invocation"
Also, in the console when I opened Unity got another error:

ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-base:[10.2.4]
Google.JarResolver.PlayServicesSupport.GetDependencies (Google.JarResolver.Dependency dep, System.Collections.Generic.List`1 repoPaths)
Google.JarResolver.PlayServicesSupport.GetTransitiveDependencies (System.Collections.Generic.Dictionary`2 dependencies, System.Collections.Generic.List`1 repoPaths)
Google.JarResolver.PlayServicesSupport.FindMissingDependencyPaths (System.String destinationDirectory, System.Collections.Generic.Dictionary`2& dependencyPaths, Google.JarResolver.ExplodeAar explodeAar)
GooglePlayServices.ResolverVer1_1.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation, System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.Resolve (System.Action resolutionComplete)
GooglePlayServices.PlayServicesResolver.AutoResolve ()
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:249)

What should I do?

**Comment by gametrainee** [comment]
Here is issue after Updating and fresh install of plugin


NullReferenceException: Object reference not set to an instance of an object
Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest, System.String destDirectory, Google.JarResolver.ExplodeAar explodeAar)
GooglePlayServices.ResolverVer1_1.DoResolutionNoAndroidPackageChecks (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation)
GooglePlayServices.ResolverVer1_1+<DoResolution>c__AnonStorey5.<>m__8 ()
GooglePlayServices.ResolverVer1_1+<DoResolution>c__AnonStorey5.<>m__9 (System.Collections.Generic.Dictionary`2 packageInfo)
GooglePlayServices.ResolverVer1_1+<GetAvailablePackages>c__AnonStorey4.<>m__7 (GooglePlayServices.Result result)
GooglePlayServices.CommandLineDialog+ProgressReporter.Update (GooglePlayServices.CommandLineDialog window)
GooglePlayServices.CommandLineDialog.Update ()
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:262)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:255)
UnityEditor.HostView.SendUpdate () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:330)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:249)

**Comment by pradeepkulasekaran** [comment]
@AlvaroFalcon
**Changes in Code**
If you got the error **Cannot find candidate artifact for com.google.android.gms:play-services-base:[10.2.4]**
Go to the file in your project Assets/GooglePlayGames/PluginVersion.cs, inside change the PlayServicesVersionConstraint to "10.2.1" (the default value is "10+"). Save and go to unity.

**Comment by AlvaroFalcon** [comment]
Ok, I thought I alredy did that, now I got no error on that, I'll try it and tell you. Can I now install the OneSignal plugin without problems? Or I have to follow some steps

**Comment by pradeepkulasekaran** [comment]
Even i have to install one signal but i haven't tried.. Will try after couple of days . Let me know if u tried it..

**Comment by gametrainee** [comment]
I have no any other plugin

**Comment by AlvaroFalcon** [comment]
@pradeepkulasekaran Ok, im building now the app to try the login, if it works ill backup it and try installing onesignal

**Comment by pradeepkulasekaran** [comment]
@gametrainee  U got the 10.2.1 arr files?

**Comment by AlvaroFalcon** [comment]
My god, I could login, you are my hero @pradeepkulasekaran, I'll backup right now and try installing OneSignal. Thanks a lot really

**Comment by gametrainee** [comment]
not i not getting arr files now i will try now with version .36

**Comment by pradeepkulasekaran** [comment]
@gametrainee  if you don't mind try reinstalling as steps provided in #1723
I guess u are missing some... For others its working fine...

**Comment by gametrainee** [comment]
Now this issue arise 

Google.JarResolver.ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-base:[10.2.4]
  at Google.JarResolver.PlayServicesSupport.GetDependencies (Google.JarResolver.Dependency dep) [0x00000] in <filename unknown>:0 
  at Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest, System.String destDirectory) [0x00000] in <filename unknown>:0 
  at GooglePlayServices.ResolverVer1_1.DoResolutionNoAndroidPackageChecks (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation) [0x00000] in <filename unknown>:0 
UnityEngine.Debug:LogError(Object)
GooglePlayServices.ResolverVer1_1:DoResolutionNoAndroidPackageChecks(PlayServicesSupport, String, OverwriteConfirmation)
GooglePlayServices.<DoResolution>c__AnonStorey5:<>m__8()
GooglePlayServices.ResolverVer1_1:DoResolution(PlayServicesSupport, String, OverwriteConfirmation, Action)
GooglePlayServices.PlayServicesResolver:Resolve(Action)
GooglePlayServices.PlayServicesResolver:AutoResolve()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by pradeepkulasekaran** [comment]
@gametrainee 

Changes in Code
If you got the error Cannot find candidate artifact for com.google.android.gms:play-services-base:[10.2.4]
Go to the file in your project Assets/GooglePlayGames/PluginVersion.cs, inside change the PlayServicesVersionConstraint to "10.2.1" (the default value is "10+"). Save and go to unity.

@gametrainee You have any other plugin or other Jar resolver ?

**Comment by AlvaroFalcon** [comment]
Already tried OneSignal and its not working, It says again the problem "ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-base:[10.2.4]" So I think I'm removing OneSignal

**Comment by pradeepkulasekaran** [comment]
Did u remove play Jar resolver while importing one signal plugin? 
We can use it from the Google play services plugin...

**Comment by AlvaroFalcon** [comment]
Huh, I'll try it and tell you

**Comment by AlvaroFalcon** [comment]
I Imported it again removing the resolver and getting the same error

**Comment by pradeepkulasekaran** [comment]
@AlvaroFalcon  Will update u in a day...

**Comment by AlvaroFalcon** [comment]
Sure, thanks ^^

**Comment by pradeepkulasekaran** [comment]
@AlvaroFalcon  If that the same error then  u have to change version some where in their files.
PlayServicesVersionConstraint to "10.2.1" (the default value is "10+")
I haven't tested it..

**Comment by AlvaroFalcon** [comment]
Will look for them later, I'm actually so happy implementing achievements haha, thanks!

**Comment by gametrainee** [comment]
Changes in Code
If you got the error Cannot find candidate artifact for com.google.android.gms:play-services-base:[10.2.4]
Go to the file in your project Assets/GooglePlayGames/PluginVersion.cs, inside change the PlayServicesVersionConstraint to "10.2.1" (the default value is "10+"). Save and go to unity.


i did this steps. its work fine but apllication crash on login

**Comment by gametrainee** [comment]
Hey Thanks! now Crash issue is was solved but now i not signed in account here is logcat

![image](https://cloud.githubusercontent.com/assets/19944132/25701491/46e7b504-30ea-11e7-98e7-949a519b0d8c.png)

**Comment by DozeX** [comment]
gametrainee: Assets/GooglePlayGames/PluginVersion.cs, inside change the PlayServicesVersionConstraint to "10.2.1" (the default value is "10+"). Save and go to unity. 

i cant location this map "googleplaygames" dosnt folder with this name in googlemobileads

**Comment by pradeepkulasekaran** [comment]
@gametrainee  Add the email to the tester list..

@DozeX Not sure with Google mobile ads.. I checked this for Google Play Services..

**Comment by siddharth3322** [comment]
I removed aar files from project but still I got generated 10.0.1 version.

Now what I require to do?? and still same sign up process closed whole game.

**Comment by pradeepkulasekaran** [comment]
@siddharth3322  
For PlayServices Plugin

Uninstall the google play services plugin

Remove all Android based plugins (one signal , ad mob etc.,)
Close Unity and browse to the Android folder delete 10.0.1 if there is any and Reopen Unity. Make sure 10.0.1 arr is not present while updating the plugin.

Download and install the latest google play services plugin (0.9.37)

**Comment by siddharth3322** [comment]
May it be possible that I have older version of android sdk affecting here?

because still same thing 10.0.1 aar files get generated.

**Comment by pradeepkulasekaran** [comment]
Its better to do a fresh import as mention in  #1723

**Comment by siddharth3322** [comment]
Here is a link for Minimal project
Google Drive Link
https://drive.google.com/open?id=0B6CFlS0aZDPiUC1seXlfZ1B4OWc

Please check this at your and reply back to me.

**Comment by gametrainee** [comment]
Hey Hi!
@pradeepkulasekaran 

i used another leaderboard id and pakage name which is live game but still not signin in play service please help

**Comment by siddharth3322** [comment]
can anybody share new aar files (10.2.1) ?
So I can replace those with my older aar files because my mac always generating 10.0.1 aar files.
For me always its crash at sign in time still.

**Comment by pradeepkulasekaran** [comment]
@gametrainee  Did u reconfigure ur Google play while setting up in unity?

@siddharth3322  Delete the temp folder and delete the 10.0.1 arr files from the explorer and reimport.

**Comment by siddharth3322** [comment]
After deleting Temp folder and old aar files, started Unity but it again already loaded with 10.0.1
Just on start up of project all files created again.

**Comment by drSpritz** [comment]
I solved this problem by returning to GooglePlayGamesPlugin-0.9.36 and use 10.0.1 aars for Unity 5.6.0f3

**Comment by pradeepkulasekaran** [comment]
@siddharth3322 Delete all the files regarding the old plugin before opening Unity..

**Comment by ricna** [comment]
@siddharth3322 Use this last version: 0.9.38
That's all! Downgrading are a waste of time and did not work.
