### ISSUE TITLE
Change profile visibility

### ISSUE THREAD

**Issue by zory** [playgameservices/play-games-plugin-for-unity#1726]
Is there a way to change PlayGames account visibility from hidden to public directly from code (or at least send user directly to GooglePlay settings page)?
Right now I am opening PlayGames app like this:  [link](https://github.com/playgameservices/play-games-plugin-for-unity/issues/1346). But I can't take user directly to settings, just the app itself.

Also is it possible to check account visibility? Right now I am checking if UserCentered downloaded scores contains user score, but this approach isn't very good.

Do you have any ideas?

**Comment by claywilkinson** [comment]
There is no way to programmatically change the user's profile visibility.  You should explain why they should make it public, and then launch the Play Games App intent.

Your game should not rely on profile visibility, why do you want to change it?

**Comment by zory** [comment]
Ok, thanks, understood. I am redirecting to Play Games App, but maybe there is the way to redirect it directly to settings page of that user (there might be selected other user at a time in Play Games App)?

TL;TR:
I have leaderboards with custom UI. Downloaded leaderboards entries doesn't contain hidden profiles (even if that user is local user). From user perspective he doesn't see himself in scores and it feels like a bug.

Longer Version:
If I am loading UserCentered scores, I am given TopScores scope, because there is no public user with that request. I could add that user, because I know his score and all required localUser data, but I can't load page of scores where he should be on (e.g. I cannot load 7 scores, which contains scores from and 1001 - 1003). So I am left with option of not showing UserCentered scores if profile is hidden and show message instead to turn it on.

**Comment by claywilkinson** [comment]
I understand.  If you are downloading the scores then presenting them, you could always insert the current player's score even if it is not in the data.  The standard leaderboard UI on the other hand can't be poked in this way.

I'll pass along the suggestion that the leaderboard data should include the local player - that seems weird it is not included (my personal opinion).
