### ISSUE TITLE
Any near term plans to update to the latest GMS package?

### ISSUE THREAD

**Issue by tcossairt** [playgameservices/play-games-plugin-for-unity#173]
Current version is using GMS 4.4.52, which is not the latest (i.e. 5.0.77).  Any plans to update this plugin? 

(I'm hoping this might solve the # of random disconnects we're seeing, as well as a situation where it gets in a state where it will not find anyone to do a match with in RTMP until you power-off and restart the devices.)

**Comment by claywilkinson** [comment]
closing as obsolete
