### ISSUE TITLE
ReportScore (Leaderboard update) isn't working on v0.9.38 

### ISSUE THREAD

**Issue by ricna** [playgameservices/play-games-plugin-for-unity#1730]
Here is my code to try both methods:

```
     public void ReportScore(int score) {
        PlayGamesPlatform.Instance.ReportScore(score, GPGSIds.leaderboard_high_level, (bool success) => {
            if (success) {
                txtStatus.text += "\n[Leaderboard updated]";
            } else {
                Social.ReportScore(score, GPGSIds.leaderboard_high_level, (bool success2) => {
                    if (success2) {
                        txtStatus.text += "\n[Score updated]";
                    } else {
                        txtStatus.text += "\n[Failed to update the score]";
                    }
                });
            }
        });
    }
```

The biggest problem is that I'm not receiving any of these messages/results. In other words, no "success == true" or "success2 == true" and the most important: Not receiving even the last option: "[Failed to update the score]" (?)
Any ideia?

Thanks,
Ricardo Nascimento

**Comment by ricna** [comment]
At least now appears the [Failed to update the score] :/

**Comment by Gokuofuin** [comment]
Mine works and I did the following:

`
public void LeaderboardPost(long score, string leaderboard)
	{
		isLoading = true;

		Social.ReportScore(score, leaderboard, (bool success) => 
			{
				if(success)
				{
					isLoading = false;
					Debug.Log("Leaderboard Posted Successfully");
				}
				else if(!success)
				{
					isLoading = false;
					Debug.Log("Leaderboard Not Posted Successfully");
				}
			});
	}
`

Of course I am not using the latest version of the plugin and I am importing the following packages:
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;

Hope that helps!

**Comment by claywilkinson** [comment]
@ricna  - can you share a log of the submission?

**Comment by ricna** [comment]
Well, I didn't change nothing and now is working... Weird. Thanks for attention @claywilkinson  and @Gokuofuin.

I think that was some issue in Google service side. I tried the LogCat while having the issue but nothing appeared that too :/

PS: @Gokuofuin  I'm using the latest version (0.9.38) because the 0.9.37 don't connect. Only shows the popup with "Loggin Google" and the result is false. I'm glad with the 0.9.38, except because that issue with the username in some oriental language.. I don't know which because even the Google Translator detect as English (very weird too). But probably is Chinese.
