### ISSUE TITLE
Question about efficiency

### ISSUE THREAD

**Issue by gfaraj** [playgameservices/play-games-plugin-for-unity#1731]
What is the recommended way to call the ReportProgress/ReportScore social methods? Currently, I'm noticing slow-downs / hiccups in my game's UI / physics when I call these methods. I was wondering if there was a way to make the calls more asynchronous or maybe I should be calling them in a specific moment in the game loop.

**Comment by Firemaw** [comment]
ReportProgress and ReportScore are already async calls so they shouldn't have a significant hit unless you are calling too many of them too often.

Refer to Google's **Quality Checklist for Google Play Games Services**: https://developers.google.com/games/services/checklist#3_leaderboards

> 3.4	Best practice	Keep the frequency of score submissions appropriate.
> Submit scores after critical transitions in the game, such as at the end of a level or when a player's game character dies. For games without critical transitions (for example, an "endless runner" type game), use good judgment on how frequently to submit scores. Scores should not be submitted continuously or every second.

**Comment by gfaraj** [comment]
Thank you Firemaw, it might have been something with my device, because I don't see the slow-down any more.
