### ISSUE TITLE
Unable to locate achievement

### ISSUE THREAD

**Issue by MikGames** [playgameservices/play-games-plugin-for-unity#1733]
Hello,

I'm working with the newest version of the GPG plugin.
I can't increment or unlock achievements.
In the debug log the following is written down:
`Could not increment, no achievement with ID ***********`

Using this code:
`PlayGamesPlatform.Instance.IncrementAchievement("*************", 1, (bool success) => { `

But the achievement exist's in the Play Console?!

**Comment by xrapa** [comment]
And with Social.ReportProgress error.

**Comment by CalebChalmers** [comment]
I'm getting a similar error here using `Social.ReportProgress`:

`!!! [Play Games Plugin DLL] 05/09/17 16:34:07 -04:00 WARNING: Unable to locate achievement <achievementid>`

from logcat

**Comment by claywilkinson** [comment]
Can you try the 0.9.38a ?  There was a nasty string marshaling bug in 0.9.38 which may be causing your issue?

**Comment by CalebChalmers** [comment]
I just tried the new version and it works!
Thanks a lot!

**Comment by claywilkinson** [comment]
Great! Thanks for following up.

**Comment by schilbiz** [comment]
Upgrading to 0.9.38a resolved the achievement issue for me as well! I was on base 0.9.38.

Thanks!

**Comment by MikGames** [comment]
Too

**Comment by VusalJalilov** [comment]
Me too
