### ISSUE TITLE
CommandInvokationFailure: Failed to re-package resources.

### ISSUE THREAD

**Issue by TheYur4uk** [playgameservices/play-games-plugin-for-unity#1734]
I am making a game where I want to include Admob and Google Play services like Leaderboards and Achievements.
So far I've successfully implemented Admob, but when I try to add this plugin I get this error below. 
How can i fix that?

```
CommandInvokationFailure: Failed to re-package resources.
C:\Users\Yur4uk\AppData\Local\Android\Sdk\build-tools\23.0.3\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "C:/Users/Yur4uk/AppData/Local/Android/Sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages
```

**Comment by n00ben** [comment]
I have been struggling with this problem for 2 days also. I made sure I only have 1 android sdk installed.

**Comment by claywilkinson** [comment]
Can you share the error message from the console?  If you click on one of the messages, it will have a long error that you can copy and then paste here.

**Comment by n00ben** [comment]
I am getting 2 of these errors upon building APK:

Win32Exception: ApplicationName='C:/Android\tools\aapt.exe', CommandLine='package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "C:/Android\platforms\android-25\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.google.example.games.mainlibproj:com.google.android.gms.auth.api:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.tasks:android.support.v4 -S "C:\Users\Ruben new\Desktop\google play services game corrupt\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res" -S "C:\Users\Ruben new\Desktop\google play services game corrupt\Temp\StagingArea\android-libraries\play-services-auth-10.2.1\res" -S "C:\Users\Ruben new\Desktop\google play services game corrupt\Temp\StagingArea\android-libraries\play-services-auth-base-10.2.1\res" -S "C:\Users\Ruben new\Desktop\google play services game corrupt\Temp\StagingArea\android-libraries\play-services-base-10.2.1\res" -S "C:\Users\Ruben new\Desktop\google play services game corrupt\Temp\StagingArea\android-libraries\play-services-basement-10.2.1\res" -S "C:\Users\Ruben new\Desktop\google play services game corrupt\Temp\StagingArea\android-libraries\play-services-drive-10.2.1\res" -S "C:\Users\Ruben new\Desktop\google play services game corrupt\Temp\StagingArea\android-libraries\play-services-games-10.2.1\res" -S "C:\Users\Ruben new\Desktop\google play services game corrupt\Temp\StagingArea\android-libraries\play-services-nearby-10.2.1\res" -S "C:\Users\Ruben new\Desktop\google play services game corrupt\Temp\StagingArea\android-libraries\play-services-tasks-10.2.1\res" -S "C:\Users\Ruben new\Desktop\google play services game corrupt\Temp\StagingArea\android-libraries\support-v4-24.0.0\res"', CurrentDirectory='Temp/StagingArea'
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
UnityEditor.Utils.Program.Start () (at C:/buildslave/unity/build/Editor/Mono/Utils/Program.cs:33)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.PostProcessor.Tasks.TasksCommon.Exec (System.String command, System.String args, System.String workingdir, System.String errorMsg, Int32 retriesOnFailure)
UnityEditor.Android.PostProcessor.Tasks.BuildResources.CompileResources (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.Tasks.BuildResources.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (BuildPostProcessArgs args)
UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, System.String downloadWebplayerUrl, System.String manualDownloadWebplayerUrl, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.BuildReporting.BuildReport report) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:186)
UnityEditor.HostView:OnGUI()

**Comment by TheYur4uk** [comment]
I have this kind of error:

CommandInvokationFailure: Failed to re-package resources.
C:\Users\Yur4uk\AppData\Local\Android\Sdk\build-tools\23.0.3\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "C:/Users/Yur4uk/AppData/Local/Android/Sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.google.android.gms.measurement:com.google.android.gms.measurement.impl:com.google.firebase:com.google.firebase.remoteconfig:com.google.firebase.crash:com.google.firebase.iid:com.YuriyVovchuk.Merge3_2187:com.google.android.gms.ads.impl:com.google.android.gms.ads:com.google.android.gms.auth.api:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms.base:com.google.android.gms:com.google.android.gms:com.google.android.gms.clearcut:com.google.android.gms.drive:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.games:com.google.android.gms.gass:com.google.android.gms.nearby:com.google.android.gms.tasks:com.google.android.gms.tasks:android.support.v4:com.YuriyVovchuk.Merge3_2187 -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\firebase-analytics-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\firebase-analytics-impl-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\firebase-common-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\firebase-config-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\firebase-crash-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\firebase-iid-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-ads-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-ads-lite-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-auth-10.2.4\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-auth-base-10.2.4\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-base-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-base-10.2.4\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-basement-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-basement-10.2.4\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-clearcut-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-drive-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-drive-10.2.4\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-games-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-games-10.2.4\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-gass-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-nearby-10.2.4\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-tasks-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-tasks-10.2.4\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\support-v4-24.0.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\unity-android-resources\res"

stderr[
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <android.support.v7.widget.ButtonBarLayout>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_alert_dialog_button_bar_material.xml: note: using v17 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:layout/abc_alert_dialog_button_bar_material for configuration v17.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.widget.DialogTitle>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:layout/abc_alert_dialog_material for configuration v17.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_dialog_title_material.xml: note: using v17 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:layout/abc_dialog_title_material for configuration v17.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.widget.ActionBarContainer>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:layout/abc_screen_toolbar for configuration v21.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_search_view.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\abc_search_view.xml: note: using v17 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:layout/abc_search_view for configuration v17.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media.xml: note: using v17 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:layout/notification_template_big_media for configuration v17.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:layout/notification_template_big_media_narrow for configuration v17.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_lines.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_lines.xml:77: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_lines.xml:96: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_lines.xml:64: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_lines.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_lines.xml: note: using v17 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:layout/notification_template_lines for configuration v17.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_media.xml:43: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <include>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_media.xml:33: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_media.xml: note: using v17 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:layout/notification_template_media for configuration v17.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_part_chronometer.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <Chronometer>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_part_chronometer.xml: note: using v17 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:layout/notification_template_part_chronometer for configuration v17.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_part_time.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <DateTimeView>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\notification_template_part_time.xml: note: using v17 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:layout/notification_template_part_time for configuration v17.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\select_dialog_multichoice_material.xml: note: using v17 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:layout/select_dialog_multichoice_material for configuration v17.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\layout\select_dialog_singlechoice_material.xml: note: using v17 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:layout/select_dialog_singlechoice_material for configuration v17.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\drawable\abc_ratingbar_indicator_material.xml:23: note: removing attribute http://schemas.android.com/apk/res/android:tileModeX from <bitmap>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\drawable\abc_ratingbar_indicator_material.xml: note: using v21 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:drawable/abc_ratingbar_indicator_material for configuration v21.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\drawable\abc_ratingbar_small_material.xml:23: note: removing attribute http://schemas.android.com/apk/res/android:tileModeX from <bitmap>
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\appcompat-v7-23.4.0\res\drawable\abc_ratingbar_small_material.xml: note: using v21 attributes; synthesizing resource com.YuriyVovchuk.Merge3_2187:drawable/abc_ratingbar_small_material for configuration v21.
D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-base-10.2.0\res\values\values.xml:33: error: Attribute "imageAspectRatioAdjust" has already been defined

D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-base-10.2.0\res\values\values.xml:42: error: Attribute "imageAspectRatio" has already been defined

D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-base-10.2.0\res\values\values.xml:44: error: Attribute "circleCrop" has already been defined

D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-base-10.2.0\res\values\values.xml:46: error: Attribute "buttonSize" has already been defined

D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-base-10.2.0\res\values\values.xml:54: error: Attribute "colorScheme" has already been defined

D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-base-10.2.0\res\values\values.xml:63: error: Attribute "scopeUris" has already been defined

]
stdout[
Configurations:
 (default)

Files:
  values\ids.xml
    Src: () D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\unity-android-resources\res\values\ids.xml
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
  Type values
    values\ids.xml
      Src: () D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\unity-android-resources\res\values\ids.xml
Including resources from package: C:\Users\Yur4uk\AppData\Local\Android\Sdk\platforms\android-23\android.jar
applyFileOverlay for drawable
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_normal_background.9.png
trying overlaySet Key=common_google_signin_btn_icon_disabled.xml
trying overlaySet Key=common_google_signin_btn_icon_light.xml
trying overlaySet Key=common_google_signin_btn_icon_light_focused.xml
trying overlaySet Key=common_google_si<message truncated>

**Comment by claywilkinson** [comment]
The line `D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-base-10.2.0\res\values\values.xml:44: error: Attribute "circleCrop" has already been defined`
indicates to me that you have multiple versions or multiple copies of the play-services-*.aar files in your project.

If you look at the command line fragment:
`D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-base-10.2.0\res" -S "D:\GameDev\Unity\2187\Temp\StagingArea\android-libraries\play-services-base-10.2.4\res"`

you have both 10.2.0 and 10.2.4 libraries in your project.  you should remove 10.2.0 and only use the latest version.
