### ISSUE TITLE
Detected incorrect implementation Achievements & game center

### ISSUE THREAD

**Issue by WestFR** [playgameservices/play-games-plugin-for-unity#1735]
Hello everybody, 

I'm use v0.9.36 with v10.0.1 AARs (ads, auth, base, drive, games, nearby, tasks)
support-annotations-24.0.0
support-v4-24.0.0
google-mobile-ads (master). 

So, my game works perfectly, however :

- when i post a production version on Google Play Developer, i obtain this message : ''Bad implementation of achievements un your game''

- when i play my game after downloaded this, i can observ that GameCenter doesn't display ''Achievements'' tab. On my game, my achievements can be unlock but nothing happens on GameCenter and my Player never get experience on GameCenter.... 

It's a unknow issue or not ? 
The problem can come from to GoogleMobileAds and Admob ? Who resolve this ? 

Thanks you very much and apologize me for my english 

![screenshot_20170509-230206](https://cloud.githubusercontent.com/assets/21226632/25884792/055853f4-3555-11e7-8178-ec1a27470220.png)
![screenshot_20170509-230423](https://cloud.githubusercontent.com/assets/21226632/25884808/254d084e-3555-11e7-918e-19beb95aa5ac.png)
![screenshot_20170509-230432](https://cloud.githubusercontent.com/assets/21226632/25884813/2c2bcf24-3555-11e7-9707-43878e1ce320.png)
![screenshot_20170509-230543](https://cloud.githubusercontent.com/assets/21226632/25884818/32a6aa18-3555-11e7-9f08-d5e3bf6b7326.png)

**Comment by WestFR** [comment]
Hello everybody,

I'm using Unity 5.5.2f1
I'm upgrade to v0.9.38a 
I'm delete Admob Plugin for this test !

But, doesn't seem to work !
Below, I attach my code.

Thanks for your help !

![code1](https://cloud.githubusercontent.com/assets/21226632/25915942/4b48bb2e-35c3-11e7-82be-b15a25e5a240.jpg)
![code2](https://cloud.githubusercontent.com/assets/21226632/25915943/4b5695e6-35c3-11e7-93ce-e41bec44b8cf.jpg)

**Comment by Firemaw** [comment]
You shouldn't be posting scores or progress in your Update function. This is will be attempting to perform async Internet call X times/sec depending on your frame rate and will eventually be blocked by Game Centre or Google Play due to the frequency of requests. Try taking those out of Update and only sending them at the end of a level or on death.

**Comment by WestFR** [comment]
Thanks for your response ! 

I have learn AsyncTasks method on Native Android Development but i don't know i'ts need applicable to unity and GPG. 

So, i understand your message. 
For work this project, i just do the UnlockAchievements and ReportScore methods out of Update method. 

But what's is the better solution for realize this ? Such as a coroutine or a simple method call when the player are dead ? 

Thanks you for this response. 
2 months of project rage and today i begin to understand this ''simple'' problem ^^

**Comment by Firemaw** [comment]
Rename your method:

`void Update () {..,}`

to 

`public void ReportLevelProgress () {...}`

Then call that method from another class on a game over event or an end of level event.

If you want to take it one step further (optional) - to be more efficient - check if the achievement is already complete, and if so, don't ReportProgress on it again, because it's redundant and a waste of resources to do so. You can track this manually with your own code or use Social.LoadAchievements on startup to cache the progress of all achievements to date.

**Comment by Firemaw** [comment]
You should also make sure you are updating the value of your HighScore variable inside the Social.ReportScore callback. Maybe you are doing it elsewhere in code, but I can't see that the value ever changes here.

**Comment by WestFR** [comment]
So, if i understand what's you says :

- it's better to check of achievements is already complete for code and network request efficience. But i'ts not critic for unlock and get experience on Google play games if this check is not implement ? 

- and, i'ts better and required to make sure we have uploading HighScore variable for leaderboard ?

**Comment by Firemaw** [comment]
1. Yes
2. No. Do this:

```
if (HighScore < ScoreInt) {
    Social.ReportScore (ScoreInt, "CgkI79__388GEAIQFw", (bool success) => {
        HighScore = ScoreInt;
    });
}
```

**Comment by WestFR** [comment]
Ok, thanks for your help ! 

I test this tonight and i report my result to you soon ! 

Thanks !

**Comment by WestFR** [comment]
Hello, i have test more manipulations.
And, i seem it's doesn't work...

I attach my code below.
You can see, i call just one time my check achievements : 
- One time on start function (for check levels)
- One time on update function for report HighScore to leaderboard (then call just one time thanks to Sucess variable).

My scripts combines C# and JS. So, it's the reason why i can't call achievements methos to Death or EndLevel events.
Now, my achievements are all reachabled !

- But, it's don't understand why my user logged never get experience of achievements to her account on "Google Play Games" app ?
- And, why my leaderboard stay empty and no highscore (my highscore) are displayed than my function it's ok ?

Thanks for your help and sorry for my disappointed

**Comment by Firemaw** [comment]
You need to authenticate on startup. Also you should have:

> Success = success;

**Comment by WestFR** [comment]
Hello, i already have authenticate methods on startup in other scene. 

I check soon for ''Success = success'' on all unlock achievements. 

If after this, If my user not get experience of achievements on Google Play Game application, i'm very lost..

**Comment by WestFR** [comment]
👍

**Comment by claywilkinson** [comment]
@WestFR  - I take the thumbs up meaning you have resolved the issue?  Please reopen if you are still having problems.  Thanks!
