### ISSUE TITLE
ResolutionException: Cannot find candidate artifact for com.android.support:support-v4:24.0.0

### ISSUE THREAD

**Issue by kevinfoley** [playgameservices/play-games-plugin-for-unity#1736]
My Unity project has the latest version of GoogleMobileAds (3.5.0) and GooglePlayGames (0.9.38a) installed. I am getting the error `ResolutionException: Cannot find candidate artifact for com.android.support:support-v4:24.0.0` when I open or run the project.

I have the following packages installed in the Android SDK manager:

    Android 7.1.1
    Android 7.0
    Android SDK Build-Tools
    Android SDK Platform-Tools
    Android SDK Tools
    Android Support Repository 47.0.0
    Google Repository 47

**Comment by claywilkinson** [comment]
Can you double check you have updated the Android SDK components to the latest?  The file it is looking for should be in ${ANDROID_SDK}/extras/android/m2repository/com/android/support/support-v4/24.0.0/support-v4-24.0.0.aar

**Comment by kevinfoley** [comment]
Everything is updated to the latest. `support-v4-24.0.0.aar` is present in the directory you indicated. I have the Android SDK installed to c:\android\sdk instead of in my user directory (because my user directory includes a space) in case that makes any difference, but I set the install location using the Android SDK manager so presumably it should still be able to find it.

**Comment by claywilkinson** [comment]
Did you change the SDK path in Unity as well?  I don't have a Windows box handy, but I believe there is an option for setting the external tools.

**Comment by kevinfoley** [comment]
Ah, I forgot that was a setting. I haven't changed that for a couple of years, and it was pointed at the wrong install path. Thanks!
