### ISSUE TITLE
*fixed*CommandInvokationFailure: Unable to list target platforms.

### ISSUE THREAD

**Issue by n00ben** [playgameservices/play-games-plugin-for-unity#1737]
Installed brand new Android Studio with latest API. SDK is installed and Path is set correctly in Unity.
I have Build-Tools, Platform-Tools, and Tools installed, android and google repository.

Now I'm getting this annoying error.

CommandInvokationFailure: Unable to list target platforms. Please make sure the android sdk path is correct. See the Console for more details. 
C:/Program Files (x86)/Java/jdk1.8.0_111\bin\java.exe -Xmx1024M -Dcom.android.sdkmanager.toolsdir="C:/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error:Invalid command android
]
stdout[

]
exit code: 64
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.HostView:OnGUI()

**Comment by claywilkinson** [comment]
There was a change to the Android SDK tools that broke Unity.  There is a patch available from Unity at https://unity3d.com/unity/qa/patch-releases

**Comment by n00ben** [comment]
Thank you! Fixed with 5.6.0f3 and latest version of this plugin.

**Comment by claywilkinson** [comment]
Great! Thanks for confirming!
