### ISSUE TITLE
URGENT HELP NEEDED - Sign-In stopped working after update

### ISSUE THREAD

**Issue by rajatsinghal** [playgameservices/play-games-plugin-for-unity#1739]
Updating from 0.9.36 to 0.9.38a. Also tried 0.9.38..

```
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().RequestEmail().RequestServerAuthCode(false).Build();
PlayGamesPlatform.InitializeInstance(config);
PlayGamesPlatform.Activate();
Social.localUser.Authenticate((bool success) => {
	if (success) {
		string access_token = PlayGamesPlatform.Instance.GetServerAuthCode();
		Debug.Log("access_token : "+access_token);
	}
});
```

Access token is always null..

Logs:

D/GamesUnitySDK(11113): Performing Android initialization of the GPG SDK
I/Unity   (11113): Building GPG services, implicitly attempts silent auth
I/GamesNativeSDK(11113): Writing 1941 bytes to jar file
I/dex2oat (11410): /system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm --instruction-set-features=div --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --dex-file=/data/data/com.hitwicket.unity/app_.gpg.classloader/a67d5dc2a1b2b8b1fab5e8f920120ade_games.jar --oat-fd=48 --oat-location=/data/data/com.hitwicket.unity/app_.gpg.classloader/a67d5dc2a1b2b8b1fab5e8f920120ade_games.dex --runtime-arg -Xms64m --runtime-arg -Xmx512m
I/dex2oat (11410): dex2oat took 107.163ms (threads: 4) arena alloc=49KB java alloc=13KB native alloc=613KB free=22KB
I/GamesNativeSDK(11113): Writing 1066 bytes to jar file
I/dex2oat (11415): /system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm --instruction-set-features=div --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --dex-file=/data/data/com.hitwicket.unity/app_.gpg.classloader/9fc5eaac3813d9502e2c301f2645e6da_nearby.jar --oat-fd=48 --oat-location=/data/data/com.hitwicket.unity/app_.gpg.classloader/9fc5eaac3813d9502e2c301f2645e6da_nearby.dex --runtime-arg -Xms64m --runtime-arg -Xmx512m
I/dex2oat (11415): dex2oat took 27.116ms (threads: 4) arena alloc=74KB java alloc=12KB native alloc=870KB free=29KB
W/PopupManager(11113): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
I/GamesNativeSDK(11113): Auth operation started: SIGN IN
I/GamesNativeSDK(11113): Connecting to Google Play...
I/Unity   (11113): Using AuthHelper to sign in
W/GamesServiceBroker( 4280): Client connected with SDK 10240000, Services 10298236, and Games 39080036
I/SFPerfTracer(  296):       trigger: frame rate (-50.002%)	(29.999 fps)	(33.335 ms) 	(14 drops)	(28 frames)
I/SFPerfTracer(  296):      triggers: (rate: 1332:91588) (compose: 0:10) (post: 0:4) (render: 235:6195) (28:399890 frames) (29:452892)
D/SFPerfTracer(  296):        layers: (1:10) (FocusedStackFrame (0xb8022350): 0:1688)* (DimLayer (0xb8039700): 0:54)* (DimLayer (0xb803bb08): 0:88)* (StatusBar (0xb80d7020): 1:34909)* (com.android.systemui.ImageWallpaper (0xb80a7568): 0:1994)* (DimLayer (0xb803f268): 0:1297)* (DimLayer (0xb80a5838): 0:349)* (NavigationBar (0xb80dd620): 0:49)* (com.hitwicket.unity/com.google.firebase.MessagingUnityPlayerActivity (0xb80d1de0): 0:29)* (SurfaceView (0xb80b3c48): 28:1280) 
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
V/GamesNativeSDK(11113): Play Games callback indicates connection failure.
I/GamesNativeSDK(11113): UI interaction required to connect to Google Play.
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
I/GamesNativeSDK(11113): Auth operation started: SIGN IN
I/GamesNativeSDK(11113): Connecting to Google Play...
W/GamesServiceBroker( 4280): Client connected with SDK 10240000, Services 10298236, and Games 39080036
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
V/AccountUtils( 4280): 0 accounts found with uca feature
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
W/Unity   (11113): !!! [Play Games Plugin DLL] 05/12/17 1:47:25 +05:30 WARNING: Creating new PlayGamesPlatform
W/Unity   (11113):  
W/Unity   (11113): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
W/Unity   (11113): 
D/TokenFragment(11113): Creating fragment
D/TokenFragment(11113): onStart()
D/TokenFragment(11113): onResume called
W/PopupManager(11113): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
D/TokenFragment(11113): Done with processRequest!
W/GamesServiceBroker( 4280): Client connected with SDK 10240000, Services 10298236, and Games 39080036
I/Unity   (11113): ---- [0] -- 2097177
E/TokenFragment(11113): Already a pending token request!
D/TokenFragment(11113): Fragment exists.. calling processRequests
D/TokenFragment(11113): Done with processRequest!
I/Unity   (11113): ---- [0] -- 53
W/Conscrypt( 1941): Could not set socket write timeout: null
W/Conscrypt( 1941): Could not set socket write timeout: null
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
W/AppOps  (  916): Bad call: specified package com.google.android.play.games under uid 10367 but it is really 10087
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
W/AppOps  (  916): Bad call: specified package com.google.android.play.games under uid 10367 but it is really 10087
V/GamesNativeSDK(11113): Play Games callback indicates connection.
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
I/GamesNativeSDK(11113): Successfully connected to Google Play.
W/AppOps  (  916): Bad call: specified package com.google.android.play.games under uid 10367 but it is really 10087
W/AppOps  (  916): Bad call: specified package com.google.android.play.games under uid 10367 but it is really 10087
W/AppOps  (  916): Bad call: specified package com.google.android.play.games under uid 10367 but it is really 10087
W/AppOps  (  916): Bad call: specified package com.google.android.play.games under uid 10367 but it is really 10087
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
W/AppOps  (  916): Bad call: specified package com.google.android.play.games under uid 10367 but it is really 10087
W/AppOps  (  916): Bad call: specified package com.google.android.play.games under uid 10367 but it is really 10087
V/WindowManager(  916): Adding window Window{1e5bcce4 u0 com.google.android.gms} at 6 of 12 (after Window{3812069c u0 com.hitwicket.unity/com.google.firebase.MessagingUnityPlayerActivity})
V/WindowManager(  916): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  916): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
I/SFPerfTracer(  296):       trigger: frame rate (-49.148%)	(30.511 fps)	(32.775 ms) 	(29 drops)	(59 frames)
I/SFPerfTracer(  296):      triggers: (rate: 1333:91617) (compose: 0:10) (post: 0:4) (render: 235:6195) (59:399949 frames) (60:452953)
D/SFPerfTracer(  296):        layers: (1:10) (FocusedStackFrame (0xb8022350): 0:1688)* (DimLayer (0xb8039700): 0:54)* (DimLayer (0xb803bb08): 0:88)* (StatusBar (0xb80d7020): 1:34910)* (com.android.systemui.ImageWallpaper (0xb80a7568): 0:1994)* (DimLayer (0xb803f268): 0:1297)* (DimLayer (0xb80a5838): 0:349)* (NavigationBar (0xb80dd620): 0:49)* (com.hitwicket.unity/com.google.firebase.MessagingUnityPlayerActivity (0xb80d1de0): 0:29)* (SurfaceView (0xb80b3c48): 59:1340) 
V/WindowManager(  916): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  916): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  916): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  916): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  916): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  916): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
V/WindowManager(  916): IKSWL-6868 finishPostLayoutPolicyLw: mHideKeyguard=false mDismissKeyguard=0
V/WindowManager(  916): IKSWL-6868 setKeyguardOccludedLw isOccluded=false wasOccluded=false showing=false
W/AppOps  (  916): Bad call: specified package com.google.android.play.games under uid 10367 but it is really 10087
W/GamesServiceBroker( 4280): Client connected with SDK 8487000, Services 10298236, and Games 39080036
I/art     ( 4280): Background sticky concurrent mark sweep GC freed 63702(4MB) AllocSpace objects, 16(256KB) LOS objects, 19% free, 19MB/24MB, paused 4.288ms total 115.792ms
W/Auth    ( 1941): [GetToken] GetToken failed with status code: INVALID_AUDIENCE
**E/TokenRequestor( 4280): You have wrong OAuth2 related configurations, please check. Detailed error: INVALID_AUDIENCE**
E/TokenFragment(11113): Error with silentSignIn: Status{statusCode=DEVELOPER_ERROR, resolution=null}
D/TokenPendingResult(11113):  Calling onResult for callback: GooglePlayGames.Android.TokenResultCallback result: Status: Status{statusCode=DEVELOPER_ERROR, resolution=null} email: <null> id:<null> access: <null>

**Comment by Firemaw** [comment]
#1732

**Comment by ponichWKing** [comment]
+
Got the same problem. All configurations done by leading instructions.

**Comment by claywilkinson** [comment]
Can you check your configuration on the Play Console?  A couple things to check are that the web client ID you are using when setting up the plugin is  from a web app that is linked to your game configuration.

Also confirm that the SHA-1 fingerprint for your linked Android App matches the one from the keystore you are signing the app with.

**Comment by claywilkinson** [comment]
There was a race condition sometimes between a silent signin attempt from the C++ library and the java library.  It should work now using 0.9.39a.

**Comment by playablegraphs** [comment]
> Can you check your configuration on the Play Console? A couple things to check are that the web client ID you are using when setting up the plugin is from a web app that is linked to your game configuration.
> 
> Also confirm that the SHA-1 fingerprint for your linked Android App matches the one from the keystore you are signing the app with.

Thx for the advice. Worked for me.
