### ISSUE TITLE
GetServerAuthCode() return empty string the first time the app is launch

### ISSUE THREAD

**Issue by vianneylancon** [playgameservices/play-games-plugin-for-unity#1741]
I use plugin verssion 0.9.38a.
I configure the PlayGamesPlatform with

            PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
           .AddOauthScope("https://www.googleapis.com/auth/games_lite") 
           .RequestEmail()
           .RequestServerAuthCode(false)
           .RequestIdToken()
           .Build();
                PlayGamesPlatform.InitializeInstance(config);
                PlayGamesPlatform.DebugLogEnabled = true;
                GooglePlayGames.OurUtils.Logger.WarningLogEnabled = true;
            PlayGamesPlatform.Activate();

After having been successfully authenticate by PlayGamesPlatform.Instance.Authenticate(

I call GetServerAuthCode() and it return always an empty string the first time the app is launch, but the other time it works.

A Debug.Log  In the callback AndroidTokenClient.cs

 pr.setResultCallback(new TokenResultCallback((rc, authCode, email, idToken) =>

Indicate that the field are received empty

**Comment by djock** [comment]
#1732

**Comment by claywilkinson** [comment]
This is fixed in 0.9.39

**Comment by asotelo94** [comment]
Well I am getting the same error on 0.9.42 servercode and token id are always empty.

**Comment by Suvitruf** [comment]
https://github.com/playgameservices/play-games-plugin-for-unity/issues/2053
