### ISSUE TITLE
Project not compiling on iOS: The type or namespace name IOSResolver does not exist in the namespace Google

### ISSUE THREAD

**Issue by kkondarev** [playgameservices/play-games-plugin-for-unity#1742]
Hi, I have updated to version 0.9.38a and now iOS cannot compile, I get:

[Unity] Assets/GooglePlayGames/Editor/GPGSDependencies.cs(90,20): error CS0234: The type or namespace name `IOSResolver' does not exist in the namespace `Google'. Are you missing an assembly reference?

In the project Assets folder I do have PlayServicesResolver/Editor folder with Google.IOSResolver.dll in it.

Any idea what might be wrong? Already tried to cleanup, re-import packages, restart, etc...
Issue appears with iOS only, Android complies and works fine.
Thanks!

**Comment by claywilkinson** [comment]
Unfortunately, Play Games services announced it is no longer supporting the iOS platform: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
