### ISSUE TITLE
Can I change achievement unlock pop up window position on screen?

### ISSUE THREAD

**Issue by TheYur4uk** [playgameservices/play-games-plugin-for-unity#1743]
In my game I have a banner ad on top of the screen and when any achievement is unlocked this message is hidden behind ad.
Can i somehow change the position of this popup window?

**Comment by TheYur4uk** [comment]
Any ideas?

**Comment by claywilkinson** [comment]
You can set the gravity of the popup.  I am making a pull request and will post it shortly.

**Comment by claywilkinson** [comment]
It will be in the next version of the plugin, but you can  look at Pull request https://github.com/playgameservices/play-games-plugin-for-unity/pull/1767

For how to merge it in until then.

**Comment by claywilkinson** [comment]
Added to the plugin version 0.9.39.
