### ISSUE TITLE
BasicApi.Multiplayer.Participant. Player property always null 

### ISSUE THREAD

**Issue by KrasovskyVictor** [playgameservices/play-games-plugin-for-unity#1744]
I just trying to show names and avatars of player, but "Player" property for external players always null (only local participant have not null value of it).

I get them by method "PlayGamesPlatform.Instance.RealTime.GetConnectedParticipants()"

Any suggestions?

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
