### ISSUE TITLE
ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-base:[10.2.4] 

### ISSUE THREAD

**Issue by vrfurl** [playgameservices/play-games-plugin-for-unity#1747]
Not sure if this issue is isolated to my specific configuration or not but wanted to share in case someone else runs into this.

I was getting the error above: **ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-base:[10.2.4]** 

while trying to resolve client jars on the **Assets > Play Services Resolver > Android Resolver > Resolve client Jars** menu.

I'm running:
**Unity: 5.6
Android SDK: 6.0 (23) Revision 3
Google Play Services: Rev 40**

This began to occur after downloading the latest version of Android Studio and SDK, and updating to the latest version of the Google Play Services.

For whatever reason it appears that the dependency resolution doesn't want to work when using the following in the **Assets > GooglePlayGames > PluginVerison.cs file:**

**Issue:**
    // used to get the right version of dependencies.
    public const string PlayServicesVersionConstraint = "10+";

After I changed it to this:

**Fix:**
    // used to get the right version of dependencies.
    public const string PlayServicesVersionConstraint = "10.2.1";

It began working.  It seems the latest version of the SDK doesn't like the "+" operator.

Well hope that helps someone.

Thanks!

**Comment by claywilkinson** [comment]
Thanks for the detailed work around!

The updated plugin, 0.9.38a contains a new version of the Play Services Jar Resolver which fixes the issue.  You fix does work, the only downside is it locks at 10.2.1 so any bug fixes or updates in the play-services library may not be picked up.

**Comment by Shrykar** [comment]
Saved me a ton of time, thanks for work around directions.

**Comment by timendez** [comment]
still experiencing this issue. Running Unity Plugin version: 0.9.39a (0x0000939A)
Unity version 2017.1.0f3

**Comment by ayushvora** [comment]
The workaround above doesn't work for me either. What a mess.

**Comment by Shrykar** [comment]
Can you downgrade Unity? This resolves my issue and I I’m on 5.6.2f1

Sent from Mail for Windows 10
