### ISSUE TITLE
App crash when authenticating.

### ISSUE THREAD

**Issue by JimmyDeemo** [playgameservices/play-games-plugin-for-unity#1748]
Plugin version: 0.9.38a
Unity version: 5.4.5f1

Crash happens when trying to authenticate; seems similar to #1604 but I am unable to match the error to anyone elses issue.

> 05-18 15:53:00.026 14635 14648 W Unity   : !!! [Play Games Plugin DLL] 05/18/17 15:53:00 +01:00 WARNING: Creating new PlayGamesPlatform
> 05-18 15:53:00.026 14635 14648 W Unity   :
> 05-18 15:53:00.026 14635 14648 W Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 05-18 15:53:00.026 14635 14648 W Unity   :
> 05-18 15:53:00.028 14635 14648 I Unity   :  [Play Games Plugin DLL] 05/18/17 15:53:00 +01:00 DEBUG: Activating PlayGamesPlatform.
> 05-18 15:53:00.028 14635 14648 I Unity   :
> 05-18 15:53:00.028 14635 14648 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 05-18 15:53:00.028 14635 14648 I Unity   :
> 05-18 15:53:00.028 14635 14648 I Unity   :  [Play Games Plugin DLL] 05/18/17 15:53:00 +01:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
> 05-18 15:53:00.028 14635 14648 I Unity   :
> 05-18 15:53:00.028 14635 14648 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 05-18 15:53:00.028 14635 14648 I Unity   :
> 05-18 15:53:00.028 14635 14648 I Unity   :  [Play Games Plugin DLL] 05/18/17 15:53:00 +01:00 DEBUG: Creating platform-specific Play Games client.
> 05-18 15:53:00.028 14635 14648 I Unity   :
> 05-18 15:53:00.028 14635 14648 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 05-18 15:53:00.028 14635 14648 I Unity   :
> 05-18 15:53:00.028 14635 14648 I Unity   :  [Play Games Plugin DLL] 05/18/17 15:53:00 +01:00 DEBUG: Creating Android IPlayGamesClient Client
> 05-18 15:53:00.028 14635 14648 I Unity   :
> 05-18 15:53:00.028 14635 14648 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 05-18 15:53:00.028 14635 14648 I Unity   :
> 05-18 15:53:00.046 14635 14648 F art     : art/runtime/thread.cc:1321] No pending exception expected: java.lang.NoSuchMethodError: no static method "Lcom/google/games/bridge/TokenFragment;.fetchToken(Landroid/app/Activity;ZZZLjava/lang/String;Z[Ljava/lang/String;ZLjava/lang/String;)Lcom/google/android/gms/common/api/PendingResult;"
> 05-18 15:53:00.046 14635 14648 F art     : art/runtime/thread.cc:1321]   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
> 05-18 15:53:00.046 14635 14648 F art     : art/runtime/thread.cc:1321]   at boolean com.unity3d.player.UnityPlayer.a(com.unity3d.player.UnityPlayer) ((null):-1)
> 05-18 15:53:00.046 14635 14648 F art     : art/runtime/thread.cc:1321]   at boolean com.unity3d.player.UnityPlayer$c$1.handleMessage(android.os.Message) ((null):-1)
> 05-18 15:53:00.046 14635 14648 F art     : art/runtime/thread.cc:1321]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:100)
> 05-18 15:53:00.046 14635 14648 F art     : art/runtime/thread.cc:1321]   at void android.os.Looper.loop() (Looper.java:148)
> 05-18 15:53:00.046 14635 14648 F art     : art/runtime/thread.cc:1321]   at void com.unity3d.player.UnityPlayer$c.run() ((null):-1)
> 05-18 15:53:00.046 14635 14648 F art     : art/runtime/thread.cc:1321]

Our code base builds the project via gradle as we have reached dex limit. Could this be related to dependencies?

**Comment by claywilkinson** [comment]
This method `expected: java.lang.NoSuchMethodError: no static method "Lcom/google/games/bridge/TokenFragment;.fetchToken(Landroid/app/Activity;ZZZLjava/lang/String;Z[Ljava/lang/String;ZLjava/lang/String;)Lcom/google/android/gms/common/api/PendingResult;"`

Is in Assets/Plugins/Android/MainLibProj/libs/play-games-plugin-support.jar.  Make sure you have this and it is version of the file in the 0.9.38a package.

**Comment by JimmyDeemo** [comment]
Thank you for the tip off @claywilkinson. Indeed the place our build process was calling pulling this file in from was out of date. I updated it to the one in the location you specified and it worked.
