### ISSUE TITLE
library not found for -lGoogleToolboxForMac

### ISSUE THREAD

**Issue by huhund** [playgameservices/play-games-plugin-for-unity#1749]
Issue:
Integrating firebase-analytics and google-play-games causes unity build to fail with "library not found for -lGoogleToolboxForMac" . Integrating only firebase ore only google-play doesn't fail, you need to have both of them.

Unity 5.6.0p1.
MacOS X 10.12.4
firebase ver: 15 mar 2017
google play games ver: 9 may 2017

**Comment by claywilkinson** [comment]
Unfortunately, Play Games services announced it is no longer supporting the iOS platform: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html

**Comment by huhund** [comment]
Thank you. Sorry for being unclear, the app is multiplatform. Google play games is enabled on Android but disabled on iOS. I apply the flag NO_GPGS on iOS build. Let me change the issue to following.

"Google Play Games integration breaks multiplatform building when using together with firebase".

**Comment by AndreaSkyMarchetti** [comment]
... So now that I have implemented Firebase I can't use it on iOS?

**Comment by claywilkinson** [comment]
@AndreaSkyMarchetti  - Firebase will continue to be cross platform.  Unfortunately this plugin for Play Game Services is dropping support for iOS.  We're working on a cross platform plugin for sign-in, so you'll be able to continue to use Google sign-in on both Android and iOS.

**Comment by claywilkinson** [comment]
@huhund  - Thanks for the clarification.  Yes. the NO_GPGS flag is what you are looking for.  The latest plugin I believe fixes your issue and it should compile for iOS.  If it doesn't please feel free to submit a pull request including what you did to fix it.
