### ISSUE TITLE
auto-resolver settings are not project specific

### ISSUE THREAD

**Issue by huhund** [playgameservices/play-games-plugin-for-unity#1751]
Settings for auto-resolving jars should either be default false or then project specific so that settings can be commited to source control.

Currently they are user specific and users who have not disabled them will get conflicting jars downloaded occasionally. This happens even if the user presses the "keep" in the dialogue.

The auto-downloaded jars conflicts with firebase jars and causes failed builds when building for android device.

**Comment by claywilkinson** [comment]
The Jar resolver project is handled out of a different repository.  I suggest logging your issues/suggestions there:  https://github.com/googlesamples/unity-jar-resolver/issues
