### ISSUE TITLE
Not able to get top Score or Player Score from Leaderboard through "PlayGamesPlatform.Instance.LoadScores"

### ISSUE THREAD

**Issue by ani051092** [playgameservices/play-games-plugin-for-unity#1753]
I am using following code to get top score:

        PlayGamesPlatform.Instance.LoadScores ("Leaderboard_id", 
        LeaderboardStart.TopScores,1, LeaderboardCollection.Public , 
        LeaderboardTimeSpan.AllTime, (LeaderboardScoreData data) => {   

				if(data.Valid){
					hScore = (int)data.Scores[0].value;
					HScore.text = hScore.ToString();
				} else{				
				}
			});

This returns me 0. Please help me if i am doing anything wrong or missing on anything.

**Comment by ani051092** [comment]
Any update? Am i the only one facing this issue now? 
I am using this plugin for android app just for information. Please help if anyone has implemented it already.

**Comment by claywilkinson** [comment]
To test, can you add showing the Leaderboard to confirm the data you are expecting is displayed?

Also, can you share a log to getting the data?

**Comment by ani051092** [comment]
@claywilkinson  Thanks for response but i have figured out this. Actually some .arr file were missing so i used dependencies resolver thorough play service resolver and it worked for me. Closing this issue now.
