### ISSUE TITLE
After signing out, you will not be able to retrieve mail or tokens when you reconnect.

### ISSUE THREAD

**Issue by YeonggwangYU** [playgameservices/play-games-plugin-for-unity#1756]
you worked hard. I am using Unity 5.6.0f3 version and latest plugin version (0.9.38a). If you log in after running the game for the first time, you will normally get mail and tokens, but after you log out, you will be able to log in again when you try to log in to Google and log in, but you will not be able to retrieve your mail or token information.

After that, if you play the game again, it will be received normally. Sorry for posting you using a translator.

**Comment by play-game** [comment]
Thanks for information. I will soon developing unity game for this [game site](http://twixgame.com). I will need it.

**Comment by ramioooz** [comment]
This might be related https://github.com/playgameservices/play-games-plugin-for-unity/issues/1712

**Comment by claywilkinson** [comment]
I have reproduced the issue with signing out and in again, and not having the tokens updated correct.  I'll update the thread when I have a fix.

**Comment by claywilkinson** [comment]
Fixed in 0.9.39
