### ISSUE TITLE
Not compiling in on iOS?

### ISSUE THREAD

**Issue by lordmortis** [playgameservices/play-games-plugin-for-unity#1758]
Is there a way we can just not compile this in for iOS builds? (Given that GPS is deprecated there?)

**Comment by lordmortis** [comment]
Aha, I see the `NO_GPGS` define flag - I'm assuming if i have that set on Android it will cause the services to also not be compiled there?

**Comment by claywilkinson** [comment]
NO_GPGS only affects iOS. https://github.com/playgameservices/play-games-plugin-for-unity#excluding-all-google-play-game-services-when-building-for-ios

There is no way to disable the plugin for Android (other than removing it from your project).
