### ISSUE TITLE
Can't get setup to work

### ISSUE THREAD

**Issue by PetroRandy** [playgameservices/play-games-plugin-for-unity#1759]
Unity version: 5.6.1f1
I'm upgrading to the latest version of the plugin. I've deleted my Assets/GooglePlayGames folder and Assets/PlayServicesResolver folder. I'm getting this error whenever I hit accept to the terms of service:

NullReferenceException: Object reference not set to an instance of an object
Google.JarResolver.Dependency..ctor (Google.JarResolver.Dependency dependency)
Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest, System.Collections.Generic.Dictionary`2 dependencyMap, System.String destDirectory, Google.JarResolver.ExplodeAar explodeAar)
Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest, System.String destDirectory, Google.JarResolver.ExplodeAar explodeAar)
GooglePlayServices.ResolverVer1_1.DoResolutionNoAndroidPackageChecks (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation)
GooglePlayServices.ResolverVer1_1+<DoResolution>c__AnonStorey8.<>m__10 ()
GooglePlayServices.ResolverVer1_1+<DoResolution>c__AnonStorey8+<DoResolution>c__AnonStorey9.<>m__16 (GooglePlayServices.Result updateResult)
GooglePlayServices.CommandLineDialog+ProgressReporter.Update (GooglePlayServices.CommandLineDialog window)
GooglePlayServices.CommandLineDialog.Update ()
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:262)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:255)
UnityEditor.HostView.SendUpdate () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:330)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:249)

I'm completely stuck on what to do. I've tried deleting my library and temp folders in unity, restarting several times, cleaning out the plugins folder, etc.

**Comment by XiveStudio** [comment]
@PetroRandy
hi,
to me it looks like SDK related problem.
This might help :- 

1. Check if you have set up SDK properly 
Edit -> preferences -> External tools -> both SDK and JDK are setup properly.

2. Check if you updated SDK Extras
Your Android SDK folder-> Open Sdk Manager -> wait till it checks for updates -> make sure this things are updated : Android Support Repository , Google Play Services , Google Repository

3. If you did both above steps, Save **(Even Backup)** and close Unity , Open Unity again , now it will ask you replace new Google Play dll files, click replace.

4. if still errors , **back up you full project** and delete these folders : GooglePlayGames , PlayServicesResolver (and also Plugin , if you are using **only** GooglePlayGames plugin or GoogleAds, to completely remove this folder unity need 2 restarts). Then Restart Unity and Install the Plugin again.

hope this will solve the issue.

**Comment by claywilkinson** [comment]
Please reopen this issue if @XiveStudio's suggestions did not work.

**Comment by PetroRandy** [comment]
I followed all those steps @XiveStudio pointed out and it was still having the same error. I ended up running Unity in administrator mode and it had no errors. I've been able to make progress.

**Comment by fierysquirrel** [comment]
I confirm that running Unity in administrator mode works, @PetroRandy thanks!
