### ISSUE TITLE
Unable to authenticate to GPGS

### ISSUE THREAD

**Issue by alectora** [playgameservices/play-games-plugin-for-unity#1760]
Hi,

I have a problem authenticating to GPGS. I know this has been addressed by some people here, and I have checked the possible same issues, but this still occurs to me. [This is my log without Unity filter](https://pastebin.com/Md4Ujg8f).

Visually I don't even have any Google-related window appears. it just returns false.

Here's my simple code to test it:
```
	GameObject text = GameObject.Find ("Canvas/Text");

	PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();

	PlayGamesPlatform.InitializeInstance(config);

	PlayGamesPlatform.DebugLogEnabled = true;

	PlayGamesPlatform.Activate();

	Social.localUser.Authenticate((bool success) => {
		text.GetComponent<Text>().text = "Success: " + success;

		if (success) {
			// Start doing things.
		}
	});
```

I have followed many instructions I gathered from the possible same issues in here (including the Configure Your Game). I have:
- created a game app in Google Play Console
- added new Game services and have it linked with the game app, authorized (I have attempted both auto and manual SHA1 key insertion)
- created the keystore from Unity and use it to build the apk and run on the device
- the game SHA1 matched with the one from Google API, using the keytool to check
- added my gmail account to Google Play console tester, and have it on Game services testing access
- performed the Android Configuration found in Window > Google Play Games > Setup > Android Setup (this includes performing Get resources by creating a leaderboard). I've assured the app_id is number only and matched with the one in Game services
- updated my SDK tools to the latest and added required libraries (Android Support Repository, Google Play services, Google Repository)
- setup the package name correctly on Unity (Bundle Identifier) and the one in Game services' linked app.
- tried using PlayGamesPlatform.Instance.Authenticate instead of Social.localUser.Authenticate and still not working
- tried to re-add game and game services
- run it on device and not the editor
- Game services status Ready to Test

I'm using JDK 1.8, and Unity 5.5.0f3, with NDK r10e, SDK 4.4.2 (API 19), 6.0 (API 23), and 7.0 (API 24).
My minimum API level for the game is API 19.

Please let me know if I miss something.

Just in case people insist this is because I don't put my account to tester, and I might probably put it in a wrong way:
![alt text](http://i.imgur.com/PUx0nW2.jpg "test1")
![alt text](http://i.imgur.com/mp6ZcAu.jpg "test2")

**Comment by XiveStudio** [comment]
hi,
hope this will help, it solved my problem.
check out :- https://stackoverflow.com/questions/44153675/google-play-games-service-error-not-authorized-when-rollout-for-beta-unity3/44235859#44235859

**Comment by alectora** [comment]
hi xive thanks for the response.

I haven't enabled the Google App Signing, I need to make sure, is Google App Signing requirement so my app can connect to Play services? I do not want to enroll to it unless I have to (in relation to this problem).

**Comment by XiveStudio** [comment]
Hi, 
Google App Signing is not required for play game services to work i guess.
You don't have to publish Game services if you are  only testing it locally.

( if you are using save games then make sure you add it to PlayGameClientConfig...  Code)

If you are getting error is when Build and run (assuming you are using correct keystore to sign apk) check out this video and see you if you did all steps correctly : https://youtu.be/5Ae8GeRmdH0 
. 

If you are getting error when you rollout for beta or production,  make sure you did all the steps mentioned in question and answer : https://stackoverflow.com/questions/44153675/google-play-games-service-error-not-authorized-when-rollout-for-beta-unity3/44235859#44235859

**Comment by alectora** [comment]
Hi xive,

I have no save games enabled (as mentioned in my simple code). I also tested what happens if I enabled saved games, and (obviously) not working as well.

I have checked and matched the SHA1 many times, still doesn't work.

I've done tried all the steps for GPGS in the video, still doesn't work.

Speaking of keystore, I created the keystore using Unity's Android Other settings. That's the key that I should be using right? I uploaded the APK, and use it to link with the Game services which is found in Package name for linked apps, so I don't really see the problem here.

**Comment by XiveStudio** [comment]
hi,
Sorry its very hard for me to figure out whats going wrong.

Quick Tips : - 
1. make sure before exporting (building apk) that your keystore is selected and Key Alias set to you alias and not debug.

2. test your app on some other device (i had an issue while using Admob, i tested it on other device and it worked fine. And to make it work on my device i had to clear data of play game services)

3. if none of these help, please contact googleplay-developer-support. They also offer chat support,
 to access chat : Google Play Console -> help and feedbacks -> Contact us -> Chat (Monday through Friday, 6 a.m. to 6 p.m. Eastern Time).

**Comment by alectora** [comment]
It's alright xive I got more information to solve this thanks to you.
I haven't attempted the 2nd option, I'll get back here after trying that.

**Comment by alectora** [comment]
Hi,

According to Xive Quick Tips, I've tested on ASUS ZenFone 2 (Z00AD) Android 5.0 and it worked. The sign in window shows up, the success callback returns true.

My previous test device was Samsung Galaxy S3, Android 4.4.2. I still have no idea why the problem persists in that device. This should show that this relates to device problem. Whether it's the plugin, Unity, or the device itself I still can't tell yet.

**Comment by alectora** [comment]
Hi,

Finally found the culprit. **The Google Play Games is not enabled** on the device.

So the solution if all the above still won't work, make sure that Google Play Games is enabled. It can be easily found in Play Store. In this device case, it can also be found in Application manager in DISABLED tab.

Hope this helps.
