### ISSUE TITLE
Google.IOSResolver.Enabled cannot be assigned to 

### ISSUE THREAD

**Issue by matthewlkey** [playgameservices/play-games-plugin-for-unity#1761]
After installing Google Play Games Plugin and setup for IOS, I receive the error message:

Assets/GooglePlayGames/Editor/GPGSDependencies.cs(90,32): error CS0200: Property or indexer `Google.IOSResolver.Enabled' cannot be assigned to (it is read-only)

To replicate, download the "Minimal" sample, install the plugin and setup for IOS. Seems to be the only true error I've been getting with the plugin so far. Thanks!

Matt

**Comment by claywilkinson** [comment]
Thanks for the feedback.  You can safely delete that line.   Also, please keep in mind that iOS support for this plugin has been deprecated:  https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html

**Comment by matthewlkey** [comment]
Ok thanks Clay! How will we authenticate into Google after the plugin is gone?

Any information is appreciated! I've been trying to setup google authentication in with Firebase for weeks now!

I guess the best option right now is to check if the user is signed into google play, get their ID and authenticate into firebase with that. Do you have any thoughts on that?

Thanks again!!

Matt Key

**Comment by claywilkinson** [comment]
I think the best route is to use Google Sign-In and call it from Unity.  It will take some refactoring, but I think it is not too bad and will allow Firebase Auth to be used both in Android and iOS.  I'll keep this thread posted with any progress I make...

**Comment by claywilkinson** [comment]
Fixed in 0.9.39
