### ISSUE TITLE
Project GPM data does not exist. Creating new object.

### ISSUE THREAD

**Issue by SpesialK** [playgameservices/play-games-plugin-for-unity#1762]
I keep getting this error code on my unity project while trying to implement a leader board. I am very new to unity so if there is an explanation for this please may you try and keep it as simple as possible. Anyway, here is the full error message.

 Project GPM data does not exist. Creating new object.
UnityEngine.Debug:Log(Object)
Google.PackageManager.LoggingController:Log(String)
Google.PackageManager.ProjectManagerController:InflateProjectRecord(String)
Google.PackageManager.ProjectManagerController:.cctor()
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()

I hope that someone can work out what is the problem here as I have tries googling it and got no where.

Thank you in advance.

**Comment by claywilkinson** [comment]
This is a harmless message that has to do with the [Jar Resolver](https://github.com/googlesamples/unity-jar-resolver) which is an editor-only component used to help make sure your Unity project contains the correct libraries for Android.

Is there something going wrong (other than seeing the message) when you are trying to use the leaderboard?

**Comment by SpesialK** [comment]
claywilkinson No everything else is fine. Thanks a lot for you help.
