### ISSUE TITLE
jar resolver conflicts with jar resolver from firebase

### ISSUE THREAD

**Issue by huhund** [playgameservices/play-games-plugin-for-unity#1764]
How to repro:
* Create a simple Unity test project and setup both firebase-analytics and google-play-games.

You will notice that both plugins wants to install jar-resolver. If you use the jar-resolver from firebase you can't setup google play. If you use the jar resolver from google play the iOS build won't compile.

**Comment by ikitae** [comment]
https://github.com/googlesamples/unity-jar-resolver

**Comment by huhund** [comment]
Thanks for the tip but unfortunately multiplatform builds still fails with:

Showing All Messages
ld: warning: directory not found for option '-

L/Users/huhund/Library/Developer/Xcode/DerivedData/Unity-iPhone-hbwmlwdshjyvzwcjdttwzxepwgbc/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac'

**Comment by ikitae** [comment]
Open iOS project with 'Unity-iPhone.xcworkspace'
Not 'Unity-iPhone.xcodeproj'
.xcworkspace  include pod frameworks.

**Comment by claywilkinson** [comment]
Which versions of the plugins are you using?  They should be  compatible if they are both the latest and should contain the same version of the resolver plugin.  

If you have to choose and need iOS support, always install the games plugin then the Firebase plugin last.

What is the error when trying to setup the Games plugin?

**Comment by huhund** [comment]
MacOS X 10.12.5
Unity 5.6.1f1
GPGS 0.9.39
Firebase 3.0.3.

ld: warning: directory not found for option '-L/Users/huhund/Library/Developer/Xcode/DerivedData/Unity-iPhone-dhkyszthckcsvafaqwtbolisuann/Build/Products/ReleaseForRunning-iphoneos/GoogleToolboxForMac'
ld: library not found for -lGoogleToolboxForMac
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by huhund** [comment]
Actually the latest firebase now have this issue on it's own - it was working previously. Forwarding this bug to firebase now.

**Comment by Mathling** [comment]
[!] Please close any current Xcode sessions and use MyApp.xcworkspace for this project from now on.

**Comment by crunchbury** [comment]
Still having this problem with GPGS 0.9.39a and Firebase 4.0.3. @huhund Did you manage to resolve the issue?

**Comment by claywilkinson** [comment]
The best workaround is to not import the PlayServicesResolver from this plugin if you already have the Firebase plugin added to your project.

There will be an updated plugin published soon that re-sync with Firebase plugin.  Stay Tuned!

**Comment by claywilkinson** [comment]
The jar resolved has been synced up with Firebase in 0.9.40
