### ISSUE TITLE
Error encountered executing VideoManager#IsCaptureAvailableCallback

### ISSUE THREAD

**Issue by defic** [playgameservices/play-games-plugin-for-unity#1766]
I'm trying to implement play games video capture into our game, but it is throwing error:

`I Unity   :  [Play Games Plugin DLL] 05/31/17 15:54:17 +03:00 DEBUG: Entering internal callback for VideoManager#IsCaptureAvailableCallback
I Unity   :  
I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I Unity   : 
W Unity   : *** [Play Games Plugin DLL] 05/31/17 15:54:17 +03:00 ERROR: Error encountered executing VideoManager#IsCaptureAvailableCallback. Smothering to avoid passing exception into Native: System.EntryPointNotFoundException: VideoManager_IsCaptureAvailableResponse_GetIscaptureavailable
W Unity   :   at (wrapper managed-to-native) GooglePlayGames.Native.Cwrapper.VideoManager:VideoManager_IsCaptureAvailableResponse_GetIscaptureavailable (System.Runtime.InteropServices.HandleRef)
W Unity   :   at GooglePlayGames.Native.PInvoke.IsCaptureAvailableResponse.IsCaptureAvailable () [0x00000] in <filename unknown>:0 
W Unity   :   at GooglePlayGames.Native.NativeVideoClient+<IsCaptureAvailable>c__AnonStorey2.<>m__0 (GooglePlayGames.Native.PInvoke.IsCaptureAvailableResponse response) [0x00000] in <filename unknown>:0 
W Unity   :   at GooglePlayGames.Native.PInvoke.Callbacks+<ToIntPtr>c__AnonStorey0`1[GooglePlayGames.Native.PInvoke.IsCaptureAvailableResponse].<>m__0 (IntPtr result) [0x00000] in <filename unknown>:0 
W Unity   :   at GooglePlayGames.Native.PInvoke.Callbacks.PerformInterna`

The code is like in the README example. Also calling for videoCaptureCapabilities gives a similiar error. Google play saved games and achievements seem to work fine.

Versions:
Unity 5.5.2p4
play-services-auth-10.2.6.aar
play-services-auth-base-10.2.6.aar
play-services-base-10.2.6.aar
play-services-basement-10.2.6.aar
play-services-drive-10.2.6.aar
play-services-games-10.2.6.aar
play-services-nearby-10.2.6.aar
play-services-tasks-10.2.6.aar
firebase libraries, same version 10.2.6

**Comment by claywilkinson** [comment]
Which version of this plugin are you using?  Since a callback is part of the process, can you try wrapping the code in the callback with [`GameHelperObject.RunOnGameThread()`](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs#L95)?

Did you try to build and run the SmokeTest sample?  I just tried that and it appeared to work OK.

Are you building using mono or IL2CPP runtime?

**Comment by Hellfim** [comment]
@claywilkinson, hello!
Unfortunately I have the same problem with plain SmokeTest sample (clear project). I tried to build it with both Mono and IL2CPP.
My plugin version is 0.9.38a, with 10.2.6 libraries and Unity 5.6.1f1

**Comment by claywilkinson** [comment]
I'm downloading 5.6.1 right now to try.  Can you share the full log?

**Comment by claywilkinson** [comment]
OK  - I found the issue (I am updating the plugin this week and it will include the fix).  In the mean time, there is a typo in the name of the method:
In Assets/GooglePlayGames/Platforms/Native/Cwrapper/VideoManager.cs

Change:
* VideoManager_GetCaptureCapabilitiesResponse_GetVideocapabilities to be __`VideoManager_GetCaptureCapabilitiesResponse_GetVideoCapabilities`__

* VideoManager_GetCaptureStateResponse_GetVideocapturestate to be
__`VideoManager_GetCaptureStateResponse_GetVideoCaptureState`__

* VideoManager_IsCaptureAvailableResponse_GetIscaptureavailable to be
__`VideoManager_IsCaptureAvailableResponse_GetIsCaptureAvailable`__

**Comment by Hellfim** [comment]
@claywilkinson thank you, your fix worked for me!

**Comment by claywilkinson** [comment]
Fixed in 0.9.39
