### ISSUE TITLE
Unable to upgrade plugin under Perforce.

### ISSUE THREAD

**Issue by JimmyDeemo** [playgameservices/play-games-plugin-for-unity#1773]
I am having problems perfoming the upgrade procedure for the plugin with a project under Perforce version control. When performing this under Subversion I recieved the popup notification when loading Unity (i.e GPG has been updated to 0.98a etc) but this does not happen when upgrading another project. I also note that the setup window is not present in under the Window tab.

I suspect that this is because certain parts of the project need to be made writable in order for the plugin to initialise/upgrade correctly. Please could you advise if this is the case?

I am aware of #585, but this doesn't look like it would stop the upgrade.

**Comment by claywilkinson** [comment]
The other things to check are is the project in Perforce set for building for Android?  The plugin only works when running for Android (or iOS) build targets.

Also, are there any errors in the console?  This should help identify if there is a file access issue.

The plugin writes to ProjectSettings/GooglePlayGameSettings.txt

**Comment by JimmyDeemo** [comment]
You were indeed correct on both accounts; after changing to Android platform and making GooglePlayGameSettings.txt writable I was able to upgrade successfully.

**Comment by claywilkinson** [comment]
Great! I'm glad you got it working!
