### ISSUE TITLE
Reset Achievements for tester accounts

### ISSUE THREAD

**Issue by 7Ds7** [playgameservices/play-games-plugin-for-unity#1775]
Do not know if the plugin is meant to use the management API as well.

But is it possible to call 
https://developers.google.com/games/services/management/api/achievements/resetAll

From within the plugin ?

**Comment by claywilkinson** [comment]
This plugin is just the runtime APIs for the play-game services.  The management API is not intended to be used by users on the device.  It is intended for an internal developer web site or command line.
