### ISSUE TITLE
[0.9.39] Trouble authenticating when signing in.

### ISSUE THREAD

**Issue by JimmyDeemo** [playgameservices/play-games-plugin-for-unity#1776]
After having problems with 0.9.38 I decided to try 0.9.39. Initially I was able to login to the game I am working on fine, but after this I struggle to get the auth token I need.

The attached log should probide a flow for what is happening. At line 346 we see the following;

> [Play Games Plugin DLL] 06/06/17 11:20:12 +01:00 DEBUG: AuthState == Unauthenticated calling auth callbacks with failure

Which causes the games login code to fail, see lines 364 and 380. However then shortly after we see;

> [Play Games Plugin DLL] 06/06/17 11:20:12 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID

Which suggests that sign in is still in progress and callbacks are being fires early? Please let me know if you need more information.

[Sign In Attempt.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/1054706/Sign.In.Attempt.txt)

**Comment by JimmyDeemo** [comment]
Possibly linked to #1778.

**Comment by claywilkinson** [comment]
Thanks for the log - let me take a look today.

**Comment by claywilkinson** [comment]
There was a race condition between signing in to get the auth token and a silent sign in attempt from the C++ library.  This is fixed in 0.9.39a.

**Comment by JimmyDeemo** [comment]
Fix looks good. Thanks for the quick turn around.

**Comment by claywilkinson** [comment]
@JimmyDeemo  - Great! thanks for the confirmation
