### ISSUE TITLE
Requesting ID token Error

### ISSUE THREAD

**Issue by ScareCrow95** [playgameservices/play-games-plugin-for-unity#1778]
Hello, I was using 0.9.38 and I was having problems getting the ID token, sometimes I received it other times it was null, so had to run the app couple of times till it returned the token ID. But with 0.9.39 I am not receiving the token at all.

Attaching the logcat as well, and on line 72 it says : [Play Games Plugin DLL] 06/06/17 17:23:23 +05:30 DEBUG: Auth finished. Proceeding.
On line 105 I am still getting a null token.

[0.9.39 Logcat.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/1055011/0.9.39.Logcat.txt)

0.9.38 Token Received :
![0 9 38 token received](https://cloud.githubusercontent.com/assets/18271051/26828847/d5c5e4b6-4ae0-11e7-9b86-9c61a6994b3d.png)

0.9.38 Null Token:
![0 9 39 no token](https://cloud.githubusercontent.com/assets/18271051/26828853/d9bf0052-4ae0-11e7-8c8a-1565417bb125.png)

0.9.39 Always Null token :
![0 9 38 no token](https://cloud.githubusercontent.com/assets/18271051/26828850/d7bff7de-4ae0-11e7-8826-e4438cf0ce6e.png)

**Comment by ScareCrow95** [comment]
[0.9.39 Logcat.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/1055733/0.9.39.Logcat.txt)
[0.9.38 (Working).txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/1055735/0.9.38.Working.txt)

**Comment by claywilkinson** [comment]
Thanks @ScareCrow95  - but these logs are only showing the Unity category.  Can you share the log with no filter? There should be categories like "GamesServiceBroker" and "TokenFragment" and "GamesNativeSDK" among others.

**Comment by ScareCrow95** [comment]
Ah I see,  give me a moment I have to revert back to the latest version and generate it again

**Comment by claywilkinson** [comment]
Thanks - I appreciate the effort :)

**Comment by ScareCrow95** [comment]
[log.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/1057826/log.txt)

Hope this is what you need, if you need anything else please feel free to ask. I really need that token ^^

**Comment by claywilkinson** [comment]
@ScareCrow95 - This line in your log.txt file
`*** [Play Games Plugin DLL] 06/07/17 17:07:51 +05:30 ERROR: Server Auth Code and ID Token require web clientId to configured.`

Means the web client id is not configured.  You'll need a web app linked to your game in the Play Console and then copy its client id and paste it into the [setup dialog](https://github.com/playgameservices/play-games-plugin-for-unity#paste-the-game-resources-into-the-plugin-setup-dialog) for the plugin.

**Comment by ScareCrow95** [comment]
It is there as you can see, and it does work in the previous version. Do I need to do something differently with this update in plugin?

![image](https://user-images.githubusercontent.com/18271051/26889900-4cd54e7e-4bcd-11e7-81ef-f761bef23065.png)

![image](https://user-images.githubusercontent.com/18271051/26889955-730d5c30-4bcd-11e7-904d-b983e75b5649.png)

**Comment by claywilkinson** [comment]
Did you click setup again?  That generates Assets/GooglePlayGames/GameInfo.cs - maybe in all the updating and moving around it got cleaned up?

**Comment by ScareCrow95** [comment]
Actually you were right, the GameInfo.cs was not updated as I did not press the setup button, I did now but still it does not work. Attaching the logcat :
[log.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/1058787/log.txt)

**Comment by claywilkinson** [comment]
OK I think I see the problem - let me debug it - This line looks like something is not right: `TokenFragment: No connected Games API,!!!!  Hoping for connection!`

**Comment by ScareCrow95** [comment]
Thanks man, appreciate all the help! :)

**Comment by mkorotetsky** [comment]
Hi, I have excactly same issue. Something goes wrong with the first signin in new google play account (or old with removed permissions for the application).

**Comment by claywilkinson** [comment]
This is fixed in 0.9.39a.

**Comment by ScareCrow95** [comment]
Just tested it and works perfectly, thank you so much!

**Comment by KevinTan1** [comment]
@claywilkinson 
Hello, I have same problem here, I have already create the client ID for the web app client, but whenever Im starting the game, it always forced close
Here is my logcat : 


I/Unity   (13970): Starting Auth with token client.

I/Unity   (13970):  

I/Unity   (13970): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (13970): 

V/AudioPolicyService(  272): stopOutput()

V/AudioPolicyService(  272): inserting command: 5 at index 0, num commands 0

V/AudioPolicyService(  272): AudioCommandThread() adding stop output 2

V/AudioPolicyService(  272): releaseOutput()

V/AudioPolicyService(  272): AudioCommandThread() waking up

V/AudioPolicyService(  272): AudioCommandThread() processing stop output 2

V/AudioPolicyService(  272): doStopOutput from tid 938

V/AudioPolicyManagerBase(  272): stopOutput() output 2, stream 3, session 283

V/AudioPolicyManagerBase(  272): changeRefCount() stream 3, count 1

V/AudioPolicyService(  272): inserting command: 6 at index 0, num commands 0

V/AudioPolicyService(  272): AudioCommandThread() adding release output 2

V/AudioFlinger(  272): PlaybackThread::Track destructor

V/AudioPolicyService(  272): AudioCommandThread() processing release output 2

V/AudioPolicyService(  272): doReleaseOutput from tid 938

V/AudioPolicyManagerBase(  272): releaseOutput() 2

V/AudioPolicyService(  272): AudioCommandThread() going to sleep

D/NotificationService(  983): updateLightListLocked :r=NotificationRecord(0x43b2b870: pkg=com.internet.speed.meter.lite user=UserHandle{0} id=1 tag=null score=10: Notification(pri=1 contentView=com.internet.speed.meter.lite/0x7f030009 vibrate=null sound=null defaults=0x0 flags=0x62 kind=[null])), action=2

D/NotificationService(  983): notification=Notification(pri=1 contentView=com.internet.speed.meter.lite/0x7f030009 vibrate=null sound=null defaults=0x0 flags=0x62 kind=[null])

W/Unity   (13970): !!! [Play Games Plugin DLL] 06/14/17 10:26:57 +07:00 WARNING: Creating new PlayGamesPlatform

W/Unity   (13970):  

W/Unity   (13970): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

W/Unity   (13970): 

I/Unity   (13970):  [Play Games Plugin DLL] 06/14/17 10:26:57 +07:00 DEBUG: Activating PlayGamesPlatform.

I/Unity   (13970):  

I/Unity   (13970): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (13970): 

I/Unity   (13970):  [Play Games Plugin DLL] 06/14/17 10:26:57 +07:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform

I/Unity   (13970):  

I/Unity   (13970): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (13970): 

I/Unity   (13970):  [Play Games Plugin DLL] 06/14/17 10:26:57 +07:00 DEBUG: SetDefaultLeaderboardForUI: PLACEHOLDER

I/Unity   (13970):  

I/Unity   (13970): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (13970): 

I/Unity   (13970):  [Play Games Plugin DLL] 06/14/17 10:26:57 +07:00 DEBUG: Creating platform-specific Play Games client.

I/Unity   (13970):  

I/Unity   (13970): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (13970): 

I/Unity   (13970):  [Play Games Plugin DLL] 06/14/17 10:26:57 +07:00 DEBUG: Creating Android IPlayGamesClient Client

I/Unity   (13970):  

I/Unity   (13970): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (13970): 

D/TokenFragment(13970): Creating fragment

D/TokenFragment(13970): onStart()

D/TokenFragment(13970): onResume called

D/TokenFragment(13970): Building client for: 42a07d20 (a:false e:false i:true wc: 45179159993-i3lof8ni5bpbqg835irseik8tv6fepik.apps.googleusercontent.com f: false)

I/dalvikvm(13970): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.zzo.zzy

W/dalvikvm(13970): VFY: unable to resolve virtual method 446: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;

D/dalvikvm(13970): VFY: replacing opcode 0x6e at 0x0012

V/WifiServiceExtension(  983): checkPollTimer Cnt= 0 rssi =-65 threshold=-100

I/Unity   (13970): ---- [0] -- 542113885

I/Unity   (13970):  

I/Unity   (13970): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (13970): 

W/PopupManager(13970): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments

I/Vold    (  261): [LGE][VOLD][NetlinkHandler.cpp][onEvent()] subsys:cpu, action:0

D/TokenFragment(13970): No connected Games API,!!!!  Hoping for connection!

D/TokenFragment(13970): Done with processRequest!

W/GamesServiceBroker(30824): Client connected with SDK 11010000, Services 11055038, and Games 39080038

W/GamesServiceBroker(30824): Client connected with SDK 8487000, Services 11055038, and Games 39080038

V/AudioFlinger(  272): releaseWakeLock_l() AudioOut_3

V/AudioFlinger(  272): thread 0xb253c008 type 0 TID 1022 going to sleep

W/GamesServiceBroker(30824): Client connected with SDK 8487000, Services 11055038, and Games 39080038

W/GamesServiceBroker(30824): Client connected with SDK 8487000, Services 11055038, and Games 39080038

V/AccountUtils(30824): 0 accounts found with uca feature

W/GamesServiceBroker(30824): Client connected with SDK 8487000, Services 11055038, and Games 39080038

W/GamesServiceBroker(30824): Client connected with SDK 8487000, Services 11055038, and Games 39080038

I/Vold    (  261): [LGE][VOLD][NetlinkHandler.cpp][onEvent()] subsys:cpu, action:0

W/GamesServiceBroker(30824): Client connected with SDK 8487000, Services 11055038, and Games 39080038

W/GamesServiceBroker(30824): Client connected with SDK 8487000, Services 11055038, and Games 39080038

W/GamesServiceBroker(30824): Client connected with SDK 8487000, Services 11055038, and Games 39080038

I/Vold    (  261): [LGE][VOLD][NetlinkHandler.cpp][onEvent()] subsys:cpu, action:0

D/dalvikvm(21811): GC_EXPLICIT freed 1486K, 23% free 19365K/24876K, paused 2ms+3ms, total 36ms

D/libc    (  266): _dns_getaddrinfo: iptype =1

D/libc    (  266): _dns_getaddrinfo: query_ipv4=1, query_ipv6=0

W/GamesServiceBroker(30824): Client connected with SDK 8487000, Services 11055038, and Games 39080038

W/GamesServiceBroker(30824): Client connected with SDK 8487000, Services 11055038, and Games 39080038

W/AppOps  (  983): Bad call: specified package com.google.android.play.games under uid 10323 but it is really 10110

W/GamesServiceBroker(30824): Client connected with SDK 8487000, Services 11055038, and Games 39080038

W/AppOps  (  983): Bad call: specified package com.google.android.play.games under uid 10323 but it is really 10110

D/BubblePopupHelper( 1183): isShowingBubblePopup : false

W/GamesServiceBroker(30824): Client connected with SDK 8487000, Services 11055038, and Games 39080038

D/TokenPendingResult(13970):  Calling onResult for callback: GooglePlayGames.Android.TokenResultCallback result: Status: Status{statusCode=SUCCESS, resolution=null} email: <null> id:eyJhbGciOiJSUzI1NiIsImtpZCI6IjJkMDY3ZGRiZTgxMTA0Y2VmYzIwOGI1NjAxNDJjMTdmMTMyNGI2MjUifQ.eyJhenAiOiI0NTE3OTE1OTk5My03MGR1bHI4dDR0MnZhZjEya2xvZjlyYTkzdmNqNGZzNi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImF1ZCI6IjQ1MTc5MTU5OTkzLWkzbG9mOG5pNWJwYnFnODM1aXJzZWlrOHR2NmZlcGlrLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTA1ODkwODA5Nzk0NzY3ODUxMDc4IiwiaXNzIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tIiwiaWF0IjoxNDk3NDA5OTA2LCJleHAiOjE0OTc0MTM1MDYsIm5hbWUiOiJLZXZpbiBUYW4iLCJnaXZlbl9uYW1lIjoiS2V2aW4iLCJmYW1pbHlfbmFtZSI6IlRhbiJ9.YnY6DzKbVVCnuZbJbQ6RWDOxP3UQnTsTYdMGMcfjC8aUXjipq_w-iptDF3wDaVgLe_u28--RYCYBtqNkGaIE-8NMWMLcO9jN3dqDNt_N4VK2YrEWPjsK_-YxSiaI0A99xA1ecFvs5E-fp_3_VOo2j5vtG1-zBpBYX7TYlDVgrC7lMp78-qTBWu4RU2WU4FtmFecUXLOPO10wUwl5z6y2luy6mS411TDSjx6jhSJRqR9YSMEm-32kXnmwhMU8nHFZmbTPOdZWUs6LTOq_XoHosagBKoxz6_OxDENsphxBcSZ9GCVB4_buxgE1wCAg7PhoG-_utUVtgyNdnSP_JcGUtg access: <null>

D/dalvikvm(13970): Trying to load lib /data/app-lib/com.Satu.CubicPilot-1/libgpg.so 0x428c1c10

D/dalvikvm(30824): GC_CONCURRENT freed 2440K, 23% free 24053K/31064K, paused 3ms+7ms, total 63ms

D/dalvikvm(30824): WAIT_FOR_CONCURRENT_GC blocked 47ms

D/dalvikvm(30824): WAIT_FOR_CONCURRENT_GC blocked 50ms

D/dalvikvm(13970): Added shared lib /data/app-lib/com.Satu.CubicPilot-1/libgpg.so 0x428c1c10

D/GamesUnitySDK(13970): Performing Android initialization of the GPG SDK

I/Unity   (13970): Building GPG services, implicitly attempts silent auth

I/Unity   (13970):  

I/Unity   (13970): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (13970): 

I/GamesNativeSDK(13970): Using existing jar.

I/GamesNativeSDK(13970): Writing 1941 bytes to jar file

I/GamesNativeSDK(13970): Using existing jar.

I/GamesNativeSDK(13970): Writing 1066 bytes to jar file

W/PopupManager(13970): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments

I/GamesNativeSDK(13970): Auth operation started: SIGN IN

I/GamesNativeSDK(13970): Connecting to Google Play...

D/dalvikvm(30824): GC_FOR_ALLOC freed 94K, 22% free 24510K/31064K, paused 64ms, total 64ms

I/dalvikvm-heap(30824): Grow heap (frag case) to 26.676MB for 518416-byte allocation

D/NotificationService(  983): updateLightListLocked :r=NotificationRecord(0x43a04d58: pkg=com.internet.speed.meter.lite user=UserHandle{0} id=1 tag=null score=10: Notification(pri=1 contentView=com.internet.speed.meter.lite/0x7f030009 vibrate=null sound=null defaults=0x0 flags=0x62 kind=[null])), action=2

D/NotificationService(  983): notification=Notification(pri=1 contentView=com.internet.speed.meter.lite/0x7f030009 vibrate=null sound=null defaults=0x0 flags=0x62 kind=[null])

W/GamesServiceBroker(30824): Client connected with SDK 11010000, Services 11055038, and Games 39080038

W/GamesServiceBroker(30824): Client connected with SDK 8487000, Services 11055038, and Games 39080038

W/AppOps  (  983): Bad call: specified package com.google.android.play.games under uid 10323 but it is really 10110

W/GamesServiceBroker(30824): Client connected with SDK 8487000, Services 11055038, and Games 39080038

V/GamesNativeSDK(13970): Play Games callback indicates connection.

I/GamesNativeSDK(13970): Successfully connected to Google Play.

E/GamesNativeSDK(13970): Exception in com/google/android/gms/games/snapshot/Snapshots.load: java.lang.IllegalStateException: Cannot use snapshots without enabling the 'Saved Game' feature in the Play console.

D/AccountUtils(30824): Clearing selected account for com.Satu.CubicPilot

W/AppOps  (  983): Bad call: specified package com.google.android.play.games under uid 10323 but it is really 10110

W/AppOps  (  983): Bad call: specified package com.google.android.play.games under uid 10323 but it is really 10110

W/AppOps  (  983): Bad call: specified package com.google.android.play.games under uid 10323 but it is really 10110

W/AppOps  (  983): Bad call: specified package com.google.android.play.games under uid 10323 but it is really 10110

E/GamesNativeSDK(13970): Exception in com/google/android/gms/games/achievement/Achievements.load: java.lang.SecurityException: Not signed in when calling API.

F/libc    (13970): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 14095 (main_dispatch)

W/GamesNativeSDK(13970): Could not automatically seed snapshot cache.

I/Unity   (13970):  [Play Games Plugin DLL] 06/14/17 10:26:58 +07:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID

I/Unity   (13970):  

I/Unity   (13970): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (13970): 

I/DEBUG   (  267): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

I/DEBUG   (  267): Build fingerprint: 'lge/g2_open_com/g2:4.4.2/KOT49I.D80220b/D80220b.1398699625:user/release-keys'

I/DEBUG   (  267): Revision: '10'

I/DEBUG   (  267): pid: 13970, tid: 14095, name: main_dispatch  >>> com.Satu.CubicPilot <<<

I/DEBUG   (  267): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000

I/Vold    (  261): [LGE][VOLD][NetlinkHandler.cpp][onEvent()] subsys:power_supply, action:3

**Comment by KevinTan1** [comment]
Hello @claywilkinson 
I have sampe problem here, i just want to get the token ID
but whenever i tried to start the game, it will crashed when the game is signing in
here is my logcat

[error.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/1073455/error.txt)

**Comment by ScareCrow95** [comment]
It happens (at-least in my case) when I have a few .aar files missing in the plugins\Android directory or if there is a version mismatch, try it out in a new project and it should work and then you can figure out what's wrong in your original project

**Comment by KevinTan1** [comment]
oh okay @ScareCrow95  let me try, thank for the suggestion

**Comment by KevinTan1** [comment]
Its still error 
I notice something like this

W/AppOps  (  983): Bad call: specified package com.google.android.play.games under uid 10324 but it is really 10110

what is that mean?
this is the logcat :
[logcat2.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/1073506/logcat2.txt)

**Comment by KevinTan1** [comment]
hi @ScareCrow95 @claywilkinson 
actually i found the problem

so this line is appear :
W/Unity   (18040): *** [Play Games Plugin DLL] 06/14/17 11:47:10 +07:00 ERROR: Server Auth Code and ID Token require web clientId to configured.

i don't know about that but how to create a web clientId?
is it created from the google play console? or from console.developer.google?

**Comment by ScareCrow95** [comment]
@KevinTan1  in game services > linked apps > link a web app - add your website url and authorize it, then paste the web client ID inside unity play games setup

**Comment by KevinTan1** [comment]
@ScareCrow95  
Thank you bro, 
I'll try it (y)
