### ISSUE TITLE
[Play Games Plugin DLL]  ERROR: ReportProgress can only be called after authentication.

### ISSUE THREAD

**Issue by LecsoBKW** [playgameservices/play-games-plugin-for-unity#178]
Hello!
When I test my game in Unity, I have warnings

*** [Play Games Plugin DLL]  ERROR: ReportProgress can only be called after authentication.
*** [Play Games Plugin DLL]  ERROR: ReportScore can only be called after authentication.

My script:
	void Awake() {
		PlayGamesPlatform.DebugLogEnabled = true;
		PlayGamesPlatform.Activate();
	}
	void Start() {
		Social.localUser.Authenticate((bool success) => {
		});
                .........bestscore declared, Ach50Id declared, etc........
		Social.ReportScore (bestscore,
		"HERE IS MY LEADERBOARD ID",
		 (bool success) => { 
		});
		if (bestscore >= 50) {
			Social.ReportProgress (
				Ach50Id, 100.0f,
				(bool success) => {
		        });
		}
        }

Why have warnings?
And I have an second answer. When I complete an Achievements, I get xp. When I have new record, the leaderboard show that. But I don't see my friends's score and public leaderboard too. I am the first and that is all, friends leaderboard and public leaderboard too, because I know any people have better score than me. And they don't see my and other people's score in leaderboard, just own every people. Why? :S

**Comment by claywilkinson** [comment]
Closing this issue since it has a great answer.  If you are still having this issue with the latest plugin, please re-open this issue.  Thanks!
