### ISSUE TITLE
How can I keep only login, remove all un-use libs?

### ISSUE THREAD

**Issue by truonguit2010** [playgameservices/play-games-plugin-for-unity#1783]
Hi,

I only want to use login. How can I remove others libs? Please give me a hand.

Thanks.

**Comment by claywilkinson** [comment]
This plugin is for Game Services, so it includes play-services-games and its dependencies.  It is not easy to refactor out just sign-in.  If you want to try. Here are the steps I recommend:

1.  Fork this repo.
2. Create a new branch called signin-only
2. Build the plugin from the source/ directory.  This way you have a baseline of it building correctly.
3. In the SupportLib project (which is java) remove the dependency on play-services-games, and carefully remove the code that won't compile without it.
4. In the C# part of the project, remove the Assets/GooglePlayGames/Platform/Native directory, fix any problems.
5. Using the new support jar, you should be able to sign in using the AndroidTokenClient class.
6. Create a pull request to share your changes :)
