### ISSUE TITLE
Call for email doesn't work the first time, only the second time

### ISSUE THREAD

**Issue by Gokuofuin** [playgameservices/play-games-plugin-for-unity#1784]
So this is a bit strange, however it could be one of three things:
**1)** Google Play is not working properly
**2)** Unity Social call is not working properly
**3)** My programming is not working properly

So what happens is like this: 
I start the game, the game requests I select the account I want to login as, then the backend authenticates fine and then requests three things one after the other, the first being the user ID, the second being the user email and the last being the user name.

Now the user ID and the user name work just fine, however the user email does not get a value. No matter how many times I call it or wait for it. 

So I then close the game and reopen it, since it now remembers who is logged in the authentication goes just fine and then the three calls for ID, email and name all happen just fine.

So any thoughts on this strange issue?

CODE:
```
if(userID == "" || userID == null)
{
	Debug.Log("Assigning user id");
	userID = Social.localUser.id;
}
if(userEmail == "" || userEmail == null)
{
	Debug.Log("Assigning user email");
	userEmail = ((PlayGamesLocalUser)Social.localUser).Email;
}
if(username == "" || username == null)
{
	Debug.Log("Assigning username");
	username = Social.localUser.userName;
}
```

**Comment by claywilkinson** [comment]
Which version of the plugin are you using?  There has been a couple versions that did not work very well.  Can you try with the latest version, 0.9.39a and share the log of signing in?

When you create the configuration, do you call RequestEmail()?  See https://github.com/playgameservices/play-games-plugin-for-unity#configuration--initialization-play-game-services for an example.

**Comment by Gokuofuin** [comment]
Alright I have tested the new version, it works perfectly.

So to re-cap the version 0.9.38a had an issue which didn't allow you to get the email address of the person who signed in until you restarted the application. 

Thanks Clay! :)
