### ISSUE TITLE
Don't use shared Plugins folder

### ISSUE THREAD

**Issue by kevinfoley** [playgameservices/play-games-plugin-for-unity#1785]
The Play Games plugin for Unity stores iOS- and Android-specific files in the shared "Plugins" folder in the project root. Since other plugins, including other Google plugins, also write files into the shared "Plugins" folder, it becomes a nightmare to manage and remove any plugins that write to this folder.

All platform-specific files should be stored in a "Plugins" folder _inside_ the GooglePlayGames folder. See for example the Facebook Unity SDK

**Comment by JimmyDeemo** [comment]
This would actually be really useful. I had to be careful with this folder when performing recent updates.

**Comment by claywilkinson** [comment]
Thanks for the feedback.  Which files are you proposing to move?  Please feel free to submit a pull request.

**Comment by kevinfoley** [comment]
@claywilkinson  All files that the Play Games plugin writes into `Assets/Plugins` should be moved to `Assets/GooglePlayGames/Plugins`

**Comment by claywilkinson** [comment]
Done
