### ISSUE TITLE
Can't Auth with GPGS

### ISSUE THREAD

**Issue by elluard** [playgameservices/play-games-plugin-for-unity#1786]
Hello, 

I have some problem about GPGS Unity.

When I sign in with GPGS Unity, Server returns two kind of result 

1. login failed ( message :  Authentication failed)
2. login succeeded 
  -> but, I cannot get Auth code or idToken, both return value is always null
  -> I tried to use GetIdToken and PlayGamesPlatform.Instance.GetServerAuthCode() function 

I am using 0.9.39a 

How can I fix it? 

And which version is stable? 
(When I use 0.9.37, I cannot Android setup with exception) 

Please help me

Thank you

[fullLog.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/1066417/fullLog.txt)

**Comment by elluard** [comment]
Unity version is 5.5.4f1

**Comment by JimmyDeemo** [comment]
I had similar issues. Have you read, and implemented the following section of the guide; https://github.com/playgameservices/play-games-plugin-for-unity#configuration--initialization-play-game-services.

**Comment by elluard** [comment]
@JimmyDeemo I used the code below 

PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().RequestServerAuthCode(false).RequestIdToken().Build();
			
and get IdToken and ServerAuthCode 

PlayGamesLocalUser user = ((PlayGamesLocalUser)Social.localUser);
		string idToken = user.GetIdToken ();
		Debug.Log("Local user's idToken is " + idToken);
		string authCode = PlayGamesPlatform.Instance.GetServerAuthCode ();
		Debug.Log("Local user's authCode is " + authCode);

Sometimes, Auth Fail, and idToken/authCode is null when Auth Succeeded

**Comment by elluard** [comment]
I have a solution, not bug... 
I misunderstand about oAuth step.

Thank you for your help

**Comment by JimmyDeemo** [comment]
Np. Please close the issue if that is the case to clean up the issue list.

**Comment by elluard** [comment]
I little confused... 
when I use android oauth2 Client ID, getIdToken returns null
but I use web app oauth2 Client ID, getIdToken returns the value... 

both are built by unity, I change the oauth2 Client ID (Android -> web App)
