### ISSUE TITLE
Occasionally, after being disconnected from a RTMP, user can no longer login

### ISSUE THREAD

**Issue by tcossairt** [playgameservices/play-games-plugin-for-unity#179]
After disconnecting or being disconnected from a RTMP during testing, a device make be unable to log back into Google Play.  It sits at the authentication Android login white scrim, or stuck at the spinning circle for a minute, before reporitng a network error.  A full reboot of the device (Galaxy S4) fixes it.   (NOTE: When it  gets in this state, it can't even log in via the Google Play games app until reboot either.)

**Comment by claywilkinson** [comment]
The new plugin implementation should have addressed this.  Let us know if there are still problems.
