### ISSUE TITLE
Authentication is working but creating a room is not working

### ISSUE THREAD

**Issue by atahan-git** [playgameservices/play-games-plugin-for-unity#1797]
When I try to run to game on my device Social.localUser.Authenticate((bool success)  returns true (but no google play overlay shows up). Then when I try to CreateQuickGame or anything else using PlayGamesPlatform.Instance.RealTime, it throws an error. I couldn't find how to see error messages on android so I can't post the exact error message.

**Comment by alpsaltera** [comment]
same with me.

Authenticate is true. but.. PlayGamesPlatform.Instance.RealTime.CreateQuickGame( MinOpponents , MaxOpponents , GameVariant , this );

==> OnRoomConnected() : Fail....

all consol setting is ok, other setting is ok....
also multiplay option is on...


one day struggled this problem......... what's solotion.

**Comment by AlexGames73** [comment]
when they already solve this problem?

Do not even launch OnRoomSetupProgress, immediately OnRoomConnected: fail...

**Comment by alpsaltera** [comment]
i can't solve this problem.

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
