### ISSUE TITLE
Please update Nearby Connections API to the latest changes from Google Play services version 11.x

### ISSUE THREAD

**Issue by NanaDada** [playgameservices/play-games-plugin-for-unity#1808]
A lot of changes have been made to the Nearby Connections API in version 11 of Google Play services:
[https://developers.google.com/android/guides/releases#june_2017_-_version_110](https://developers.google.com/android/guides/releases#june_2017_-_version_110)
Especially full offline support and support to simultaneously advertise and discover nearby connections are two very useful features **that would be very nice to have in the unity plugin**.

Thank you.

**Comment by claywilkinson** [comment]
The plugin has been updated to use the latest nearby connections libraries.
