### ISSUE TITLE
Random match back button problem

### ISSUE THREAD

**Issue by SamihElsakhawi** [playgameservices/play-games-plugin-for-unity#1817]
Hi guys,

I've got a weird problem with the Random Match.

My gam app is a air hockey game (1 vs 1), and for the multiplayer part, i create 3 buttons:

- Random Match,
- Send invitation,
- Show invitations.

When i log in, and i use these three buttons, it displays the GPGs UI as expected. 

For "Send Invitation", and "Show invitations", when i'm in the UI and i go back, i can access to the other button as normal. 

But for the random match, when i'm in the UI (waiting room), and i use the back button on the UI or on the device, i can't access to the other button, it displays the error message i put when OnRoomConnected(success) isn't true. 

How can i fix that?

[By the way, for my game, it's a 1 vs 1, so i put const int MinOpponents = 1, MaxOpponents = 1, am i correct?]

Thanks a lot for the support.

Regards, Sam.

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
