### ISSUE TITLE
Response to Submit Score or Load Scores

### ISSUE THREAD

**Issue by Santorayo2** [playgameservices/play-games-plugin-for-unity#182]
Hi,
I'd really like to display (anything) when a player beats a highscore on the leaderboard. But as far as I know you don't get a score report or anything after submitting.

A workaround could be to load scores and do the comparision myself but that feature also isn't implemented yet.

Are there any plans to do either? I really don't get the point of a leaderboard implementation without any feedback on highscores. Any effort appreciated!

**Comment by claywilkinson** [comment]
The callbacks have been added in 0.9.25
