### ISSUE TITLE
Error on Switching Platform to iOS

### ISSUE THREAD

**Issue by ScareCrow95** [playgameservices/play-games-plugin-for-unity#1822]
Hello, I had my app build for android and it works fine, now I am trying to build for iOS , and as I switch the platform to iOS this error pops up : 

Assets/GooglePlayGames/Platforms/IOS/IOSClient.cs(26,20): error CS0738: `GooglePlayGames.IOS.IOSClient' does not implement interface member `GooglePlayGames.IClientImpl.SetGravityForPopups(System.IntPtr, GooglePlayGames.BasicApi.Gravity)' and the best implementing candidate `GooglePlayGames.IOS.IOSClient.CreatePlatformConfiguration(GooglePlayGames.BasicApi.PlayGamesClientConfiguration)' return type `GooglePlayGames.Native.PInvoke.PlatformConfiguration' does not match interface member return type `void'

I am using the latest 9.39a build

**Comment by lsmsc** [comment]
Hi. I have a similar problem. I have an App that works fine on Android, but will not build on iOS. 
I'm using 0.9.39a as well.

I got 2 Errors, the first is the same:
Assets/GooglePlayGames/Platforms/IOS/IOSClient.cs(26,20): error CS0535: `GooglePlayGames.IOS.IOSClient' does not implement interface member `GooglePlayGames.IClientImpl.SetGravityForPopups(System.IntPtr, GooglePlayGames.BasicApi.Gravity)'

And the Second Error:Assets/GooglePlayGames/Platforms/IOS/IOSTokenClient.cs(32,20): error CS0535: `GooglePlayGames.IOS.IOSTokenClient' does not implement interface member `GooglePlayGames.TokenClient.FetchTokens(System.Action<int>)'

Any Ideas?

**Comment by IonRift** [comment]
Same issues

Assets/GooglePlayGames/Platforms/IOS/IOSClient.cs(26,20): error CS0535: `GooglePlayGames.IOS.IOSClient' does not implement interface member `GooglePlayGames.IClientImpl.SetGravityForPopups(System.IntPtr, GooglePlayGames.BasicApi.Gravity)'
(Filename: Assets/GooglePlayGames/Platforms/IOS/IOSClient.cs Line: 26)

Assets/GooglePlayGames/Platforms/IOS/IOSTokenClient.cs(32,20): error CS0535: `GooglePlayGames.IOS.IOSTokenClient' does not implement interface member `GooglePlayGames.TokenClient.FetchTokens(System.Action<int>)'

**Comment by claywilkinson** [comment]
Thanks for the feedback.  As you know we are deprecating Play Game Services for iOS.  I'd suggest not using this plugin for iOS since the backend services will stop working sometime in mid 2018.

In the meantime, you can implement the methods (or surround them with #If !UNITY_IOS) in the the interface.

These two functions don't work on iOS currently, so don't call them.

**Comment by rthery** [comment]
If you encounter this error, just add NO_GPGS in Scripting Define Symbols (Player Settings > iOS > Other Settings), this will just prevent this lib to be compiled with your iOS builds. It will still perfectly work fine with your Android builds.

**Comment by quangnguyen11** [comment]
@rthery thank, work fine xD

**Comment by claywilkinson** [comment]
Version 0.9.40 fixed this as well.
