### ISSUE TITLE
unable to authentication

### ISSUE THREAD

**Issue by BureQ71** [playgameservices/play-games-plugin-for-unity#1828]
Please help :( i use 0.9.39a google play services version
and 4.1 api in unity http://screenshot.sh/m3BnLNBLB8qDJ

Video: https://youtu.be/FXLC8Q9cCSw
Script in unity: http://imgur.com/a/h4ulz
Log:

```

I/WindowManager( 1516): Losing focus: Window{42d93988 u0 com.evlgames.birdz/com.unity3d.player.UnityPlayerActivity}

W/Unity   (25744): !!! [Play Games Plugin DLL] 07/14/17 17:55:28 +02:00 WARNING: Creating new PlayGamesPlatform

W/Unity   (25744):  

W/Unity   (25744): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

W/Unity   (25744): 

I/Unity   (25744):  [Play Games Plugin DLL] 07/14/17 17:55:28 +02:00 DEBUG: Activating PlayGamesPlatform.

I/Unity   (25744):  

I/Unity   (25744): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (25744): 

I/Unity   (25744):  [Play Games Plugin DLL] 07/14/17 17:55:28 +02:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform

I/Unity   (25744):  

I/Unity   (25744): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (25744): 

I/Unity   (25744):  [Play Games Plugin DLL] 07/14/17 17:55:28 +02:00 DEBUG: Creating platform-specific Play Games client.

I/Unity   (25744):  

I/Unity   (25744): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (25744): 

I/Unity   (25744):  [Play Games Plugin DLL] 07/14/17 17:55:28 +02:00 DEBUG: Creating Android IPlayGamesClient Client

I/Unity   (25744):  

I/Unity   (25744): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (25744): 

I/Unity   (25744):  [Play Games Plugin DLL] 07/14/17 17:55:28 +02:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED

I/Unity   (25744):  

I/Unity   (25744): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (25744): 

I/Unity   (25744):  [Play Games Plugin DLL] 07/14/17 17:55:28 +02:00 DEBUG: Invoking callbacks, AuthState changed from silentPending to Unauthenticated.

I/Unity   (25744):  

I/Unity   (25744): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (25744): 

I/Unity   (25744):  [Play Games Plugin DLL] 07/14/17 17:55:28 +02:00 DEBUG: there are pending auth callbacks - starting AuthUI

I/Unity   (25744):  

I/Unity   (25744): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I/Unity   (25744): 
```

Plugins folder in unity: http://screenshot.sh/mGVQjFdRzPkkD

**Comment by BureQ71** [comment]
Video 2: https://youtu.be/9eOEH-Q4L6c please help :( source code: https://pastebin.com/BL65sevx

**Comment by Royy212** [comment]
I have the exact same problems for 5 days now, I don't know how to fix this.

**Comment by Royy212** [comment]
Dude I FIXED IT!!!!!!!!!!!!!!!! 

You have to make sure you have enrolled app signing in the google play console and have your game linked in the game services (also in the google play console).

Then after that, you have to go app signing and COPY your SHA1 upload certificate (You find this in google play console > App Signing.)
Then you have to go to this site: https://console.developers.google.com
Open up your project > go to credentials > then find your OAuth 2.0 client IDs (this is linked to your APK you uploaded.) 
Then you have to click on edit OAuth client.
Here you will need to paste your copied SHA-1 certificate with the existing SHA-1 cerfitcate.
After that save it and you should be able to login to the google play services!.

Here are some images to guide you through: http://imgur.com/a/zw0Os

**Comment by BureQ71** [comment]
nope :( http://screenshot.sh/ofrzQvpXSRIx3  im editing this post and add new informations

**Comment by BureQ71** [comment]
New Video: https://youtu.be/FXLC8Q9cCSw
New Log: http://www.mediafire.com/file/4jhta2ox8zg21uu/log.txt

**Comment by BureQ71** [comment]
maybe i must have game in production status? because now i have in alfa http://screenshot.sh/ov6Tvaun69YG5

**Comment by Royy212** [comment]
Have you uploaded an APK to your app releases?
And have you enrolled app signing?

**Comment by BureQ71** [comment]
i have keystore in unity and in google play console http://screenshot.sh/m9gMXn1LWZyqr

**Comment by Royy212** [comment]
You need to go to alpha App releases > Alpha, click Enroll and upload your APK first.

**Comment by BureQ71** [comment]
i have this
http://screenshot.sh/mKVnOiNAySL4v

**Comment by Royy212** [comment]
Do you have this: https://gyazo.com/ecc06ee5ebae3c24e4926b34c637bb1d
If you don't have this, you need to delete everything and go to App Release >Alpha > Enroll > Upload new APK.

**Comment by BureQ71** [comment]
I have this http://screenshot.sh/ou1vdGCtD7oLt

i must to invent new game name and create new project because i messed up a bit in this project :/ but i have not idea for game name

**Comment by Royy212** [comment]
Just delete your current project on both sites.
https://play.google.com/apps and https://console.developers.google.com

**Comment by BureQ71** [comment]
i cant delete LOL :O I have a lot of non-current applications and can not delete them :( at most undo publishing

**Comment by BureQ71** [comment]
well, do not spam anymore, unless you have an idea how to fix it xD until tomorrow i will try to make new name for the game and create new projekt then can will think about what is going on

**Comment by eyho** [comment]
Problem is, you copied your application's SHA-1 key tto your API credentials. You need the upload certification SHA-1 key.

**Comment by BureQ71** [comment]
YEAH WORK! MAN :D Thanks for helping ;) I am creating new project with new name Buddy Bird and this work only if is public :) https://play.google.com/store/apps/details?id=com.evlgames.buddybird

**Comment by BureQ71** [comment]
Anyone can close this issue? Thanks :)
