### ISSUE TITLE
Error in code after importing the last version

### ISSUE THREAD

**Issue by michelebonapace** [playgameservices/play-games-plugin-for-unity#1830]
I've just downloaded the latest version, and i get 3 errors in a file:
Assets/GooglePlayGames/Platforms/Android/Gms/Common/Api/ResultCallbackProxy.cs(43,93): error CS0029: Cannot implicitly convert type `System.Type' to `Type'
Assets/GooglePlayGames/Platforms/Android/Gms/Common/Api/ResultCallbackProxy.cs(43,61): error CS0122: `System.Type.GetConstructor(System.Reflection.ConstructorInfo)' is inaccessible due to its protection level
Assets/GooglePlayGames/Platforms/Android/Gms/Common/Api/ResultCallbackProxy.cs(51,66): error CS0122: `System.Type.GetConstructor(System.Reflection.ConstructorInfo)' is inaccessible due to its protection level
how can i fix it?

**Comment by claywilkinson** [comment]
Which version of Unity are you using?

**Comment by michelebonapace** [comment]
5.6.0f3

**Comment by mariobrioschi** [comment]
Hi! I got the same issue, @claywilkinson shall I be using a different version?

**Comment by timendez** [comment]
I have the same issue. Using Unity 5.6.1f1

**Comment by michelebonapace** [comment]
@timendez I've figured out where the problem was

**Comment by Devdood** [comment]
@michelebonapace Could you share the solution please?

**Comment by michelebonapace** [comment]
Look in all your scripts if you defined Type and rename it with something like MyType, because google service uses it

**Comment by Devdood** [comment]
Found it, thanks!

**Comment by timendez** [comment]
@michelebonapace thanks bud, I had since used another solution (renaming the type in Google Play Services itself, d'oh) but I appreciate the tag!
