### ISSUE TITLE
IOS does not compile.

### ISSUE THREAD

**Issue by sorab2142** [playgameservices/play-games-plugin-for-unity#1839]
1. What is last supported version for ios is it 0.9.38a or 0.9.39a?
2. If it is 0.9.39a how is one supposed to make it work when it gives 3 errors on a clean project after importing the plugin. 

Error 1: SetGravityForPopups missing in IOSClient.cs, add this to solve for now.

```
public void SetGravityForPopups(IntPtr apiClient, Gravity gravity)
        {
            throw new NotImplementedException();
        }
```

Error 2: IOSTokenClient missing implementation for FetchToken, just add `<int>` after `Action` to the function parameter for FetchToken

Error 3: IOSResolver.Enabled is readonly but you are setting it to False in GPGSDependencies.cs at line 90.  Remove this line entirely.

3. Trying to make a build with just the minimal sample, and the xcode project fails with Mach linker error: GTMOAuthentication2 does not support bitcode. Tried disabling bitcode and rebuilding but still get the same error. How is this even possible????

4. Noticed that pod install is using these versions 
Using GoogleAppUtilities (1.1.2)
Using GoogleAuthUtilities (1.0.1)
Using GoogleNetworkingUtilities (1.2.2)
Using GooglePlayGames (5.1.2)
Using GooglePlusOpenSource (1.7.1)
Using GoogleSignIn (2.4.0)
Using GoogleSymbolUtilities (1.1.2)
Using GoogleUtilities (1.3.2)

when in fact Google Sign In should be at least greater than 3 (since that version says bitcode supported) and is actually currently at version 4

Please provide a way for at-least sign in to work in a clean project with exact package version, Unity version and Xcode version.

My setup:
Google Play Games version 0.9.39a
Unity version 5.6.2
Xcode version 8.3.3

**Comment by GuillaumZ** [comment]
Hi, You should better not use Google Play Games for iOS, it's full of bugs (I've lost on it, weeks of useless work) and it's officially deprecated since not so long : 

https://github.com/playgameservices/play-games-plugin-for-unity

> NOTICE: Google Play games services for iOS is deprecated, and is not likely to function as expected. Do not use Google Play games services for iOS in new apps. 

But you can use Gamecenter on apple !

**Comment by sorab2142** [comment]
@claywilkinson In another issue, you mentioned 0.9.38 was the last for IOS but even that isn't working. Could you please comment?
