### ISSUE TITLE
Silent Authentification

### ISSUE THREAD

**Issue by Nickbe67** [playgameservices/play-games-plugin-for-unity#1845]
Hello,
i am really struggeling to implement a silent Authentification request. I think i have tracked down the method to ask in the PlayGamesLocalUser class 
_public void Authenticate(Action<bool> callback, bool silent)_
,but i am not really  strong when it comes to lambda expressions. 

The classic authentification is handelt with _public void Authenticate(Action<bool> callback)_ and calld by 
_Action<bool> callback = (bool sucess) => Debug.Log(sucess);
Social.localUser.Authenticate(callback);_

adding an boolean after callback doest seem to work :/

Am i missing something? Thank you for your time.

**Comment by GuillaumZ** [comment]
Hi, have you  read the "Sign in" chapter here : https://github.com/playgameservices/play-games-plugin-for-unity ?
You have to :  
- you must have uploaded once your game to the store (in beta version at least) in the google play console
- create a play game service in the google play console 
- you attach /link this new Game service to your game (by selecting the good Unity.company.gameName), in the Google Play console
- install the plugin Google Play Games for Unity from the Git, into your Unity project
- implement the code to authenticate
- run the game, and it should work

Now there is a trick, if you accepted google "App signing" feature.
I you accepted this, then the keystore you're using when you build the game directly to your phone is not the finale one that will be used when the game will be online. So it silently fails. 
This problem hasn't been handled by Google or Unity yet, so the only way to successfuly connect to Google Play Games, when this feature is on, is to upload the game to the store (in Beta version) and download it from there.

**Comment by Nickbe67** [comment]
I dont want to be rude, but have you even read my question? 
Authentification works fine for me, it is just that i personally dislike it when new users directly get greetet with the sign in dialog upon first installing the app. This is why i would like to implement a silent Authenification there, and a normal authentification later.

**Comment by GuillaumZ** [comment]
Ok I see. 
What is confusing here is that in the chapter I'm talking about it's written : 
Authentication will show the required consent dialogs. If the user has already signed into the game in the past, **this process will be silent** and the user will not have to interact with any dialogs.

So you want it "really silent" with no notification and that does not appear in your text that I now have read twice.
Oh and yes I find you very inappropriately rude.

**Comment by Nickbe67** [comment]
I am sorry to hear that, but as i said that really wasnt my intention. Please excuse me, it just sounded like another pasted in standart reply. Turns out it wasnt, and i am happy to hear that. 
Now that we are agreed on the topic, i would like to ask you again how you would tacle the problem? On the part of it being permitted by google: I think the standart practice really is the unsilent one, but in the method discription of void Authenticate(Action callback, bool silent) in the in the PlayGamesLocalUser class it suggests its usecase to be exactly what i am looking for ... i just dont seem to be able calling it. Do you think it being not permitted could be the reason? But why would it even exist then? 
 And i wasnt able to find anything about this subject in googles documentation.
I am looking forward to your suggestions.
~Nick

**Comment by olehkuznetsov** [comment]
There is a silent authentication in Cubic Pilot sample.
Look for the 
PlayGamesPlatform.Instance.Authenticate(mAuthCallback, true);
line.
