### ISSUE TITLE
Another google_play_services_version not working issue

### ISSUE THREAD

**Issue by crener** [playgameservices/play-games-plugin-for-unity#1847]
Plugin Version: 0.9.39a
Unity Version: 5.6.1f1
Play Games SDK Version: 11.0.2

What Have I tried:
 - Resolve Client Jars (found it mentioned in many places)
 - Downloaded lastest SDK packages
 - Extracted the version file from play-services-basement-11.0.2.aar and placed it in the Plugins/Android folder

What can I do to fix this?

CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_131\bin\java.exe -classpath "D:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-2.14.jar" org.gradle.launcher.GradleMain "assembleDebug"

stderr[
C:\Users\Public\Documents\Unity Projects\PlanetHopper - Extreame changes 2\Temp\gradleOut\MainLibProj\build\intermediates\bundles\release\aapt\AndroidManifest.xml:31:28-65: AAPT: No resource found that matches the given name (at 'value' with value 'integer/google_play_services_version').
    

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':MainLibProj:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Android\android-sdk\build-tools\25.0.3\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
]
stdout[
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:MainLibProj:preBuild UP-TO-DATE
:MainLibProj:preReleaseBuild UP-TO-DATE
:MainLibProj:compileReleaseNdk UP-TO-DATE
:MainLibProj:compileLint
:MainLibProj:copyReleaseLint UP-TO-DATE
:MainLibProj:mergeReleaseProguardFiles UP-TO-DATE
:MainLibProj:packageReleaseRenderscript UP-TO-DATE
:MainLibProj:checkReleaseManifest
:MainLibProj:prepareReleaseDependencies
:MainLibProj:compileReleaseRenderscript
:MainLibProj:generateReleaseResValues UP-TO-DATE
:MainLibProj:generateReleaseResources
:MainLibProj:packageReleaseResources
:MainLibProj:compileReleaseAidl
:MainLibProj:generateReleaseBuildConfig
:MainLibProj:mergeReleaseShaders
:MainLibProj:compileReleaseShaders
:MainLibProj:generateReleaseAssets
:MainLibProj:mergeReleaseAssets
:MainLibProj:processReleaseManifest
:MainLibProj:processReleaseResources FAILED

BUILD FAILED

Total time: 18.063 secs
]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.GradleWrapper.RunJava (System.String args, System.String workingdir, UnityEditor.Android.Progress progress)
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, UnityEditor.Android.Progress progress)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.HostView:OnGUI()

**Comment by Dirly** [comment]
did you find a solution to this?   its the exact same issue I'm currently having and its driving me nuts.

**Comment by crener** [comment]
I never found a solution to the gradle issue I ended up just building with the "Internal" option. I still get the error if i build with gradle! I really wish that someone developing this would look at it and point out what is going on. 

Extremely frustrating :(

**Comment by claywilkinson** [comment]
Gradle support in Unity is still evolving.  Starting in Unity 5.5.1p1 you can override the build.gradle by placing your own gradle template in Assets/Plugins/Android/mainTemplate.gradle    More details are in this from  the Unity support site: http://answers.unity3d.com/questions/1308071/use-android-plugin-with-android-support-library-de.html

There is also a libTemplate.gradle which might allow just the overriding of the plugin.

You can also delete that manifest entry, just make sure you include the play-services libraries.

If you are generating the project and then building with Gradle, you can add the dependencies in MainLibProj/build.gradle:
```
dependencies {
    compile 'com.google.android.gms:play-services-games:11.0.2'
}
```

**Comment by Dirly** [comment]
@crener Just wanted to share.... this is what fixed it for my end:

https://forum.unity3d.com/threads/an-old-new-problem-google-play-services-and-gradle-build-com-google-android-gms-version-meta.453698/

post #4.

**Comment by victor871129** [comment]
GameAnalytics can trigger that error in AndroidManifest.xml
https://gameanalytics.com/docs/item/unity-sdk#android

**Comment by alamboley** [comment]
@victor871129 I've this issue, but didn't manage to solve it. Did you succeed?

**Comment by victor871129** [comment]
https://github.com/playgameservices/play-games-plugin-for-unity/issues/2019#issuecomment-531926400
