### ISSUE TITLE
[0.9.39a] GetIdToken() GetUserEmail() return null

### ISSUE THREAD

**Issue by DevilMaker** [playgameservices/play-games-plugin-for-unity#1851]
Hi,
I have tried all I can find.
Here are my code
`
                    PlayGamesPlatform.DebugLogEnabled = DawnLib.ConsoleHelper.EnableLog;
                    //Init config
                    PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
                        //.EnableSavedGames()
                            .RequestEmail()
                            .RequestServerAuthCode(false)
                            .RequestIdToken()
                            .Build();

                    PlayGamesPlatform.InitializeInstance(config);

                    PlayGamesPlatform.Activate(); Social.Active.localUser.Authenticate((bool success) =>
                    {
                        m_bIsWaitingForRespone = false;
                        if (success)
                        {
                            Debug.Log("<LoginSucceedCallback> Email:" + PlayGamesPlatform.Instance.GetUserEmail());//Emailis null

                            Debug.Log("<LoginSucceedCallback>Token:" + PlayGamesPlatform.Instance.GetIdToken());//Token is null

                        }
                    });`

And in AndroidTokenClient.cs line:166

` PendingResult<TokenResult> pr = new PendingResult<TokenResult>(ptr);
                        pr.setResultCallback(new TokenResultCallback((rc, authCode, email, idToken) =>
                        {
                            Debug.LogWarning("<DoFetchToken>>>>>>>>>>>>>2");
                            this.authCode = authCode;
                            this.email = email;
                            this.idToken = idToken;
                            callback(rc);
                            }));`
line:166 executed to but not the callback below, also does not have capture to the error.
wo dont know why

**Comment by DevilMaker** [comment]
And the log:

Log:Starting Auth with token client. 
Warning:!!! [Play Games Plugin DLL] 07/28/17 9:45:49 +08:00 WARNING: Creating new PlayGamesPlatform 
Log: [Play Games Plugin DLL] 07/28/17 9:45:49 +08:00 DEBUG: Activating PlayGamesPlatform. 
Log: [Play Games Plugin DLL] 07/28/17 9:45:49 +08:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform 
Log: [Play Games Plugin DLL] 07/28/17 9:45:49 +08:00 DEBUG: Creating platform-specific Play Games client. 
Log: [Play Games Plugin DLL] 07/28/17 9:45:49 +08:00 DEBUG: Creating Android IPlayGamesClient Client 
Warning:*** [Play Games Plugin DLL] 07/28/17 9:45:49 +08:00 ERROR: Server Auth Code and ID Token require web clientId to configured. 
Log:---- [0] -- 1048613 
Warning:userName:NeedyBuccaneer73012 
Warning:Email: 
Warning:Token: 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: 8 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Invoking callbacks, AuthState changed from silentPending to Unauthenticated. 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: there are pending auth callbacks - starting AuthUI 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Populating User 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Found User: [Player: 'NeedyBuccaneer73012' (id g12559956115325243832)] 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Maybe finish for User 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Auth not finished. User=[Player: 'NeedyBuccaneer73012' (id g12559956115325243832)] achievements= 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Populating Achievements, status = VALID 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Found 1 Achievements 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Maybe finish for Achievements 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Auth finished. Proceeding. 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Invoking Callbacks: System.Action`2[System.Boolean,System.String] 
Warning:O(∩_∩)O~~Google 登录成功 
Warning:<LoginSucceedCallback> Email: 
Warning:<LoginSucceedCallback>Token: 
Log: [Play Games Plugin DLL] 07/28/17 9:45:57 +08:00 DEBUG: Invoking user callback on game thread

**Comment by creatio-ua** [comment]
You got the error:

> Server Auth Code and ID Token require web clientId to configured.
Seems like you haven't configured the client ID in the setup dialog, or it is not a web-application client id

**Comment by DevilMaker** [comment]
Oh~~~~
I always thought “Client ID” is my game's  client id.
Sorry for my stupid and thank you

**Comment by DevilMaker** [comment]
The ID token is keeping null.
i have set the web-application client id. 
Log:
`Log:Starting Auth with token client. 
Warning:!!! [Play Games Plugin DLL] 07/29/17 11:00:05 +08:00 WARNING: Creating new PlayGamesPlatform 
Log: [Play Games Plugin DLL] 07/29/17 11:00:05 +08:00 DEBUG: Activating PlayGamesPlatform. 
Log: [Play Games Plugin DLL] 07/29/17 11:00:05 +08:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform 
Log: [Play Games Plugin DLL] 07/29/17 11:00:05 +08:00 DEBUG: Creating platform-specific Play Games client. 
Log: [Play Games Plugin DLL] 07/29/17 11:00:05 +08:00 DEBUG: Creating Android IPlayGamesClient Client 
Warning:<DoFetchToken> pr.setResultCallback(new TokenResultCallback((rc, authCode, email, idToken) => 
Log:---- [0] -- 1048613 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: 4 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: Invoking callbacks, AuthState changed from silentPending to Unauthenticated. 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: there are pending auth callbacks - starting AuthUI 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: Populating User 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: Found User: [Player: 'NomadicProfessor6317' (id g13680086733114317396)] 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: Maybe finish for User 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: Auth not finished. User=[Player: 'NomadicProfessor6317' (id g13680086733114317396)] achievements= 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: Populating Achievements, status = VALID 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: Found 1 Achievements 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: Maybe finish for Achievements 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: Auth finished. Proceeding. 
Log: [Play Games Plugin DLL] 07/29/17 11:00:07 +08:00 DEBUG: Invoking Callbacks: System.Action`2[System.Boolean,System.String] 
Warning:O(  _  )O~~Google   ¼ ɹ  
Warning:<LoginSucceedCallback> Email: 
Warning:<LoginSucceedCallback>Token: 
Warning:<LoginSucceedCallback> Email: 
Warning:<LoginSucceedCallback>Token: `
