### ISSUE TITLE
Resource '@integer/google_play_services_version' not found in AndroidManifest.xml:32

### ISSUE THREAD

**Issue by pickOneName** [playgameservices/play-games-plugin-for-unity#1853]
I failed build project with gradle(new) and is says Resource '@integer/google_play_services_version' not found in AndroidManifest.xml:32. How can I resolve it?(using GooglePlayGamesPlugin-0.9.39a and 11.0.2 libs)

**Comment by TheSLAP** [comment]
I'm having the same issue. I was able to resolve this error by moving the line:

`<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />` 

from AndroidManifest.xml in "Plugins/Android/MainLibProj" to "Plugins/Android/AndroidManifest.xml". The project now builds with Gradle however the app is crashing at Google Play Games popup. I'm curious if yours will build and NOT crash at authentication. Keep me posted.

Using Unity 2017.1.0f3 and play-services 11.0.2 by the way.

**Comment by pickOneName** [comment]
@TheSLAP I never had crash at authentication, what the crash log shows?

**Comment by TheSLAP** [comment]
It was something unrelated. I have it solved now. Did you get yours to build by doing what I said above?

**Comment by pickOneName** [comment]
@TheSLAP Yes, I can export an run-well android studio project now.Thx~

**Comment by Hagrida** [comment]
Instead of moving it, you can actually just comment it. Its not needed.

**Comment by AndreyPostelzhuk** [comment]
@TheSLAP thanks for solution

**Comment by bilal1993arikan** [comment]
install Google Play Service from SDK Manager

**Comment by PlanetVaster** [comment]
I had the same error, used the same solution.

**Comment by Vladimitrius** [comment]
@Hagrida solution worked for me . thks!

**Comment by jadapa** [comment]
Hello, I dont know how to solve it, can you please desribe it better for me ?
I cant find any "MainLibProj"

**Comment by jadapa** [comment]
I found it

**Comment by kiwipxl** [comment]
Took me a while to find. MainLibProj was renamed to GooglePlayGamesManifest. Can find the plugin at Assets/GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin. Just for future reference.

**Comment by srcsameer** [comment]
> ith Gradle however the app is crashing at Google Play Games popup. I'm curious if yours will build and NOT crash at authentication. Keep me posted.

It's building successfully but when i am installing it on  a device and trying to run it's getting crash after opening the app menu.

**Comment by srcsameer** [comment]
> ith Gradle however the app is crashing at Google Play Games popup. I'm curious if yours will build and NOT crash at authentication. Keep me posted.

It's building successfully but when i am installing it on  a device and trying to run, it's getting crash after opening the app menu. can anyone tell me what's wrong?

**Comment by najafloo** [comment]
I had the same problem, add this 2 line in your build.gradle the problem will be resolved probably ;)

dependencies {
.
.
implementation 'com.google.android.gms:play-services:12.0.1'
implementation 'com.google.android.gms:play-services-vision:10.0.0'
}

**Comment by redneksii** [comment]
I'm having the same issue. I was able to resolve this error by moving the line:

<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />

from AndroidManifest.xml in "Plugins/Android/MainLibProj" to "Plugins/Android/AndroidManifest.xml". The project now builds with Gradle however the app is crashing at Google Play Games popup. I'm curious if yours will build and NOT crash at authentication. Keep me posted.

Using Unity 2017.1.0f3 and play-services 11.0.2 by the way.

This worked
