### ISSUE TITLE
Google Play Services packages found with incompatible versions.

### ISSUE THREAD

**Issue by pickOneName** [playgameservices/play-games-plugin-for-unity#1854]
My unity project using both google games plugin(GooglePlayGamesPlugin-0.9.39a) and google firebase analytics(latest version) that I got a warning below : 
---------------------------------------------
Google Play Services packages found with incompatible versions.

All packages in Google Play Services must be at the same version.
Attempting to resolve the problem by using the most recent version (11.0.2) of all packages.

Found the following package references:
com.google.firebase:firebase-analytics:11.0.0
com.google.firebase:firebase-core:11.0.0
com.google.android.gms:play-services-base:11.0.0
com.google.firebase:firebase-common:11.0.0
com.google.android.gms:play-services-games:10+
com.google.android.gms:play-services-nearby:10+
com.google.android.gms:play-services-auth:10+
com.google.firebase:firebase-analytics-impl:11.0.0
com.google.android.gms:play-services-basement:11.0.0
com.google.android.gms:play-services-tasks:11.0.0
com.google.android.gms:play-services-base:11.0.2
com.google.android.gms:play-services-basement:11.0.2
com.google.android.gms:play-services-drive:11.0.2
com.google.android.gms:play-services-tasks:11.0.2
com.google.android.gms:play-services-auth-base:11.0.2
com.google.firebase:firebase-iid:11.0.0
---------------------------------------------
But I cannot find anyway to modify the lib-version that import. How can I resolve this?

**Comment by creatio-ua** [comment]
Having the same issue.

**Comment by Tanek81** [comment]
Same here but I think it's related to your Google Play Services version in the Android SDK: I started having this warning after I updated the Google Play Services version from 41 to 43. I did this on purpose while testing this plugin as I wanted to avoid issues on this side (and having the latest version available), unfortunately the result was this warning.

**Comment by claywilkinson** [comment]
You can also disable the automatic resolution and update the aar file yourself.  You want to consult with the Firebase plugin project to make sure it is OK to use a greater version.  Sometimes there are API changes that may not be backwards compatible (even if the signature of the methods are the same) which can have unintended side-effects.
