### ISSUE TITLE
GetIdToken  is Empty (plugin v. 0.9.39a)

### ISSUE THREAD

**Issue by Qualcuno** [playgameservices/play-games-plugin-for-unity#1855]
I'm trying to use Firebase Auth but the Google Token id is always empty.

Google player manager script

        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
        .RequestEmail()
        .RequestIdToken()
        .RequestServerAuthCode(false)
        .WithInvitationDelegate(InvitationDelegate)
        .WithMatchDelegate(MatchDelegate)
        .Build();

        PlayGamesPlatform.InitializeInstance(config);

        PlayGamesPlatform.DebugLogEnabled = true;

        PlayGamesPlatform.Activate();

	PlayGamesPlatform.Instance.Authenticate((success) => {
            if (success)
            {
                Debug.Log("Google Play Services auth : succes");
	    }
	});

i try to get ( after authenticated ) idtoken and same other informations in different way
       if (Social.localUser.authenticated)
        {
            Debug.Log("mPlatform.GetIdToken " + ((PlayGamesLocalUser)Social.localUser).mPlatform.GetIdToken());
            Debug.Log("Player....GetIdToken " + google_idToken);
            Debug.Log("Social.localUser...GetIdToken " + ((PlayGamesLocalUser)Social.localUser).GetIdToken());
            Debug.Log("PlayGamesPlatform...GetServerAuthCode " + PlayGamesPlatform.Instance.GetServerAuthCode());
            Debug.Log("PlayGamesPlatform...GetIdToken " + PlayGamesPlatform.Instance.GetIdToken());
            Debug.Log("PlayGamesPlatform...GetUserDisplayName " + google_username);
            Debug.Log("PlayGamesPlatform...GetUserImageUrl " + google_userimage);

	...

I've also copied the client id from the web app and pasted it into the setup dialog in unity
(it should be like this? 123456789101-abcd...........xyz.apps.googleusercontent.com ) I found it at field "ID client OAuth2" under Linked Apllications in Developer Console 

this is the log

07-31 09:54:02.594: I/Unity(1466): Starting Auth with token client. 
07-31 09:54:02.684: W/Unity(1466): !!! [Play Games Plugin DLL] 07/31/17 9:54:02 +02:00 WARNING: Creating new PlayGamesPlatform
07-31 09:54:02.694: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:02 +02:00 DEBUG: Activating PlayGamesPlatform. 
07-31 09:54:02.694: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:02 +02:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
07-31 09:54:02.694: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:02 +02:00 DEBUG: Creating platform-specific Play Games client.  
07-31 09:54:02.694: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:02 +02:00 DEBUG: Creating Android IPlayGamesClient Client
07-31 09:54:02.784: I/Unity(1466): ---- [0] -- 1048601
07-31 09:54:04.614: D/GamesUnitySDK(1466): Performing Android initialization of the GPG SDK
07-31 09:54:04.714: I/Unity(1466): Building GPG services, implicitly attempts silent auth 
07-31 09:54:05.064: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:05 +02:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: 10  
07-31 09:54:05.064: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:05 +02:00 DEBUG: Invoking callbacks, AuthState changed from silentPending to Unauthenticated. 
07-31 09:54:05.064: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:05 +02:00 DEBUG: there are pending auth callbacks - starting AuthUI 
07-31 09:54:05.474: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:05 +02:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
07-31 09:54:05.514: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:05 +02:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback
07-31 09:54:05.514: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:05 +02:00 DEBUG: Populating User
07-31 09:54:05.544: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:05 +02:00 DEBUG: Found User: [Player: 'XXXX' (id XXXXXX)]
07-31 09:54:05.544: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:05 +02:00 DEBUG: Maybe finish for User
07-31 09:54:05.564: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:05 +02:00 DEBUG: Auth not finished. User=[Player: 'XXXX' (id XXXXXXX)] achievements=
07-31 09:54:06.844: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:06 +02:00 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback
07-31 09:54:06.844: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:06 +02:00 DEBUG: Populating Achievements, status = VALID
07-31 09:54:06.884: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:06 +02:00 DEBUG: Found 6 Achievements
07-31 09:54:06.884: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:06 +02:00 DEBUG: Maybe finish for Achievements
07-31 09:54:06.884: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:06 +02:00 DEBUG: Auth finished. Proceeding.
07-31 09:54:06.884: I/Unity(1466):  [Play Games Plugin DLL] 07/31/17 9:54:06 +02:00 DEBUG: Invoking Callbacks: System.Action`2[System.Boolean,System.String]
07-31 09:54:06.884: I/Unity(1466): Google Play Services auth : succes 

07-31 09:54:12.224: I/Unity(1466): mPlatform.GetIdToken 
07-31 09:54:12.224: I/Unity(1466): Player....GetIdToken   
07-31 09:54:12.224: I/Unity(1466): Social.localUser...GetIdToken 
07-31 09:54:12.224: I/Unity(1466): PlayGamesPlatform...GetServerAuthCode   
07-31 09:54:12.224: I/Unity(1466): PlayGamesPlatform...GetIdToken 
07-31 09:54:12.224: I/Unity(1466): PlayGamesPlatform...GetUserDisplayName XXXXX
07-31 09:54:12.224: I/Unity(1466): PlayGamesPlatform...GetUserImageUrl http://lh3.googleusercontent.com/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
07-31 09:54:12.614: I/Unity(1466): Firebase App initializing app com.xxxx.xxxxxxxx(default 1).
07-31 09:54:12.644: I/Unity(1466): Firebase Analytics API Initializing 
07-31 09:54:12.644: I/Unity(1466): Firebase Analytics API Initialized
07-31 09:54:13.474: E/Unity(1466): SignInWithCredentialAsync encountered an error: System.AggregateException: Exception of type 'System.AggregateException' was thrown.
07-31 09:54:13.474: E/Unity(1466): -----------------
07-31 09:54:13.474: E/Unity(1466): Firebase.FirebaseException: Invalid credential

As you can see, i able to get Username and UserImage but i not able to get the IdToken and server auth code ( they are empty )

I'm on Unity 2017.1 and using google play games plugin 0.9.39a

**Comment by creatio-ua** [comment]
I also did the same. In some moment everything worked just fine, but several days ago it just broke. After that, both auth code and token id are empty and no error adequate messages from the plugin.
Using plugin 0.9.39a
Firebase Invites
Unity 5.6.2f1

P.S. I'm using auto created (by Firebase) Web App in console (I don't need to launch my app from browser). I linked the Web App in Developer Console to the Web App in the Games Services linked applications screen.
![consolesconfigs](https://user-images.githubusercontent.com/9407246/28776800-ed5579fc-7600-11e7-871d-9cddfc187ca7.png)

P.P.S. It's still unclear for me, why do I have to configure Web Application to add authentication to Android application (as Android application is marked as a OAuth 2.0 client and have it's own unused client id).

**Comment by Qualcuno** [comment]
OK thanks for your answer. The Web application wasn't properly configurated. Now i added a Web Application in Developer console and i'm waiting for publishing. The doubt that has remained to me is : which ID client i need to set in plugin unity3d panel setting??? the Android IDclient or Web-Application IDclient?

**Comment by creatio-ua** [comment]
Manuals say that it should be a Web-Application client ID.

**Comment by Qualcuno** [comment]
Ok it work. Thanks for help.

**Comment by raikk** [comment]
someone please help i have doubt using web client id on my unity.
i used OAuth2 Client ID from play console Linked app that is application id and pasted the id in Android setup in unity editor.
<img width="386" alt="12345" src="https://user-images.githubusercontent.com/12422925/31211576-d1d57c8c-a9b7-11e7-8681-41b79d099e28.png">

i used the same code for getting user email of this question but i have not got the user email its empty.
Also i tried this code too 
`string email = GooglePlayGames.PlayGamesPlatform.Instance.GetUserEmail();`
not work.

Then i tried using web application id, creating in google developer console, i linked with my application of google play service to google developer console. 

The web client id looks like this 
8567376646536-6djjltttkifmv2s962kamnobz5qbfsuli.apps.googleusercontent.com

when i pasted this to Android setup in unity editor. 
Its give me this "Web app Client ID not associated with this game!"


How do i use web client ID in unity android set up??

**Comment by creatio-ua** [comment]
It seems to me that you have several apps and are using app_id and client_id from different apps.
This part of your client_id 8567376646536 should be equal to your app_id
