### ISSUE TITLE
Quick Match waiting room pops one time and leave

### ISSUE THREAD

**Issue by SamihElsakhawi** [playgameservices/play-games-plugin-for-unity#1857]
Hi,

I have a weird behavior with the GPG plugin.

After i add my code to send and receive realtime messages, the UI for waiting room before a game, pops one time and leave. Before i add my code, everything worked fine (the screen stays until an opponent is find). 

I don't know why this issue appears.

Here is the log when i click to get a Quick Match (random match):

I/Unity   ( 6389): UnityEngine.Logger:Log(LogType, Object)
I/Unity   ( 6389): UnityEngine.Debug:Log(Object)
I/Unity   ( 6389): GooglePlayGames.OurUtils.<d>c__AnonStorey15:<>m__D() (at E:\A
pplication\R Hockey\Assets\GooglePlayGames\OurUtils\Logger.cs:59)
I/Unity   ( 6389): GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at E
:\Application\R Hockey\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:
135)
I/Unity   ( 6389):
I/Unity   ( 6389): (Filename: E Line: 0)
I/Unity   ( 6389):
I/Unity   ( 6389):  [Play Games Plugin DLL] 08/01/17 13:19:21 +02:00 DEBUG: Not
leaving room since showing UI
I/Unity   ( 6389): UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Obj
ect)
I/Unity   ( 6389): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String
, Object[])
I/Unity   ( 6389): UnityEngine.Logger:Log(LogType, Object)
I/Unity   ( 6389): UnityEngine.Debug:Log(Object)
I/Unity   ( 6389): GooglePlayGames.OurUtils.<d>c__AnonStorey15:<>m__D() (at E:\A
pplication\R Hockey\Assets\GooglePlayGames\OurUtils\Logger.cs:59)
I/Unity   ( 6389): GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at E
:\Application\R Hockey\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:
135)
I/Unity   ( 6389):
I/Unity   ( 6389): (Filename: E Line: 0)
I/Unity   ( 6389):
I/Unity   ( 6389):  [Play Games Plugin DLL] 08/01/17 13:19:21 +02:00 DEBUG: Ente
ring internal callback for RealtimeManager#InternalWaitingRoomUICallback
I/Unity   ( 6389): UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Obj
ect)
I/Unity   ( 6389): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String
, Object[])
I/Unity   ( 6389): UnityEngine.Logger:Log(LogType, Object)
I/Unity   ( 6389): UnityEngine.Debug:Log(Object)
I/Unity   ( 6389): GooglePlayGames.OurUtils.<d>c__AnonStorey15:<>m__D() (at E:\A
pplication\R Hockey\Assets\GooglePlayGames\OurUtils\Logger.cs:59)
I/Unity   ( 6389): GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at E
:\Application\R Hockey\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:
135)
I/Unity   ( 6389):
I/Unity   ( 6389): (Filename: E Line: 0)
I/Unity   ( 6389):
I/Unity   ( 6389):  [Play Games Plugin DLL] 08/01/17 13:19:21 +02:00 DEBUG: Show
WaitingRoomUI Response: VALID
I/Unity   ( 6389): UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Obj
ect)
I/Unity   ( 6389): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String
, Object[])
I/Unity   ( 6389): UnityEngine.Logger:Log(LogType, Object)
I/Unity   ( 6389): UnityEngine.Debug:Log(Object)
I/Unity   ( 6389): GooglePlayGames.OurUtils.<d>c__AnonStorey15:<>m__D() (at E:\A
pplication\R Hockey\Assets\GooglePlayGames\OurUtils\Logger.cs:59)
I/Unity   ( 6389): GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at E
:\Application\R Hockey\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:
135)
I/Unity   ( 6389):
I/Unity   ( 6389): (Filename: E Line: 0)
I/Unity   ( 6389):
I/Unity   ( 6389):  [Play Games Plugin DLL] 08/01/17 13:19:21 +02:00 DEBUG: Conn
ecting state ShowWaitingRoomUI: room pcount:1 status: AUTO_MATCHING
I/Unity   ( 6389): UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Obj
ect)
I/Unity   ( 6389): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String
, Object[])
I/Unity   ( 6389): UnityEngine.Logger:Log(LogType, Object)
I/Unity   ( 6389): UnityEngine.Debug:Log(Object)
I/Unity   ( 6389): GooglePlayGames.OurUtils.<d>c__AnonStorey15:<>m__D() (at E:\A
pplication\R Hockey\Assets\GooglePlayGames\OurUtils\Logger.cs:59)
I/Unity   ( 6389): GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at E
:\Application\R Hockey\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:
135)
I/Unity   ( 6389):
I/Unity   ( 6389): (Filename: E Line: 0)
I/Unity   ( 6389):
D/dalvikvm( 3322): GC_CONCURRENT freed 3216K, 31% free 17725K/25376K, paused 6ms
+7ms, total 95ms
W/ActivityManager( 2461): `mDVFSHelper.release()

Any help?

**Comment by SamMcfly** [comment]
I find the problem but i don't know why i had this.

So, tue problem appears when i'm using this line to send message to the other player:

`PlayGamesPlatform.Instance.RealTime.SendMessageToAll (false, bytedata);`

Why is this line causing the pop of the UI?

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
