### ISSUE TITLE
Return Leaderboard Rank?

### ISSUE THREAD

**Issue by RZR666** [playgameservices/play-games-plugin-for-unity#186]
Hi,

Nice work on the plugin but will it be updated with the option the show the players current leaderboard rank? or are there any tutorials to add it myself?

Thanks

**Comment by claywilkinson** [comment]
tracking internally as 19126838

**Comment by Naphier** [comment]
Could really use this so that we can tell the user their rank!
We also need a way to pull achievement progress :+1:

**Comment by habitoti** [comment]
Any update on the progress on this one? This would be really sooooo important before AppState API is switched off (or to r/o)....
Has anymone manged to add this on his own? I tried, but won't get it working :-(

**Comment by Dod2** [comment]
has anyone managed to retrieve the leaderboard data? 
I only need to show a custom leaderboard UI. is the unimplemented Social.LoadScores function the only way?

**Comment by ArmandCloud** [comment]
Up +1

**Comment by claywilkinson** [comment]
Stay tuned! working on this.  I am hoping to get it out soon.

**Comment by mikest34** [comment]
+1 on this from also!

**Comment by claywilkinson** [comment]
The leaderboard data APIs are in version 0.9.25
