### ISSUE TITLE
How can I find out the version I have?

### ISSUE THREAD

**Issue by DianaCaro** [playgameservices/play-games-plugin-for-unity#1866]
![captura](https://user-images.githubusercontent.com/6827352/29100922-78cc2e76-7c74-11e7-9ee7-92a587fb1fd8.JPG)

**Comment by waltran** [comment]
VersionString is the version of GooglePlayGames Unity Plugin. Do you ask for this or something else?

**Comment by claywilkinson** [comment]
This is the version of google-play-services that this plugin requires.  For example,  this states that version 10.0 or greater is needed.  This means if you look in Assets/Plugins/Android you should see several aar files with names like:

play-services-auth-11.0.2.aar
play-services-games-11.0.2.aar

They should be all the same version.
