### ISSUE TITLE
Nearby Connection Crashed

### ISSUE THREAD

**Issue by katerichka** [playgameservices/play-games-plugin-for-unity#1872]
Test project NearbyDroids is not working. App crashed after attempt to create room or join to multiplayer.
(Nearby Connection on device was active during test)
Unity version : 5.6.2p4
Plugin version: GooglePlayGamesPlugin-0.9.40

LOG:

/GamesNativeSDK( 2778): Can't find com/google/android/gms/nearby/connection/Connections.getLocalDeviceId: java.lang.NoSuchMethodError: no non-static method "Lcom/google/android/gms/nearby/connection/Connections;.getLocalDeviceId(Lcom/google/android/gms/common/api/GoogleApiClient;)Ljava/lang/String;".
F/art     ( 2778): sart/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: jmethodID was NULL
F/art     ( 2778): sart/runtime/check_jni.cc:65]     in call to CallObjectMethodV
F/art     ( 2778): sart/runtime/check_jni.cc:65]     from boolean com.unity3d.player.UnityPlayer.nativeRender()
F/art     ( 2778): sart/runtime/check_jni.cc:65] "UnityMain" prio=5 tid=11 Runnable
F/art     ( 2778): sart/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x12c01fd0 self=0xaed7f000
F/art     ( 2778): sart/runtime/check_jni.cc:65]   | sysTid=2800 nice=-11 cgrp=apps sched=0/0 handle=0xaed54e80
F/art     ( 2778): sart/runtime/check_jni.cc:65]   | state=R schedstat=( 22985246051 1699487924 19148 ) utm=2130 stm=168 core=1 HZ=100
F/art     ( 2778): sart/runtime/check_jni.cc:65]   | stack=0xafbd1000-0xafbd3000 stackSize=1036KB
F/art     ( 2778): sart/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #00 pc 00004bec  /system/lib/libbacktrace_libc++.so (_ZN13UnwindCurrent6UnwindEjP8ucontext+23)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #01 pc 00003489  /system/lib/libbacktrace_libc++.so (_ZN9Backtrace6UnwindEjP8ucontext+8)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #02 pc 0025aff5  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_6mirror9ArtMethodE+84)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #03 pc 0023e223  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+162)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #04 pc 000b310d  /system/lib/libart.so (_ZN3artL8JniAbortEPKcS1_+620)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #05 pc 000b383d  /system/lib/libart.so (_ZN3art9JniAbortFEPKcS1_z+68)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #06 pc 000b42b1  /system/lib/libart.so (_ZN3art11ScopedCheck8CheckSigEP10_jmethodIDPKcb.constprop.130+372)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #07 pc 000bb909  /system/lib/libart.so (_ZN3art8CheckJNI17CallObjectMethodVEP7_JNIEnvP8_jobjectP10_jmethodIDSt9__va_list+72)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #08 pc 0011aea5  /data/app/com.test.nearby-1/lib/arm/libgpg.so (???)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #09 pc 0011b43d  /data/app/com.test.nearby-1/lib/arm/libgpg.so (_ZNK3gpg13JavaReference10CallHelperIP8_jobjectEET_P7_JNIEnvMS5_FS4_S3_P10_jmethodIDSt9__va_listEPKcSD_S9_+68)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #10 pc 0011b499  /data/app/com.test.nearby-1/lib/arm/libgpg.so (_ZNK3gpg13JavaReference22CallStringWithDefaultVEPKcS2_S2_St9__va_list+56)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #11 pc 0011b567  /data/app/com.test.nearby-1/lib/arm/libgpg.so (_ZNK3gpg13JavaReference21CallStringWithDefaultEPKcS2_S2_z+22)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #12 pc 00114d47  /data/app/com.test.nearby-1/lib/arm/libgpg.so (_ZN3gpg28AndroidNearbyConnectionsImpl16GetLocalDeviceIdEv+70)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #13 pc 001497cd  /data/app/com.test.nearby-1/lib/arm/libgpg.so (_ZN3gpg17NearbyConnections16GetLocalDeviceIdEv+16)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #14 pc 0016268b  /data/app/com.test.nearby-1/lib/arm/libgpg.so (NearbyConnections_GetLocalDeviceId+14)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   native: #15 pc 000041b4   (???)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   at com.unity3d.player.UnityPlayer.nativeRender(Native method)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   at com.unity3d.player.UnityPlayer.c(unavailable:-1)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   at com.unity3d.player.UnityPlayer$c$1.handleMessage(unavailable:-1)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   at android.os.Handler.dispatchMessage(Handler.java:98)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   at android.os.Looper.loop(Looper.java:145)
F/art     ( 2778): sart/runtime/check_jni.cc:65]   at com.unity3d.player.UnityPlayer$c.run(unavailable:-1)

**Comment by claywilkinson** [comment]
This will be fixed in the next release (within a couple days). See #2005
