### ISSUE TITLE
Google Play Connecting Prompt On Resume

### ISSUE THREAD

**Issue by PetroDawson** [playgameservices/play-games-plugin-for-unity#1874]
We have integrated version 0.9.39a of the Unity plugin into our game and can authenticate users and use the play services without issue. However, our publisher's QA team has called us out on a Google Standards violation for unauthenticated users. 

If a user elects not to sign into a play account our game still works and the user can login later from our Setting screen, but whenever the user backgrounds the game and returns to it they are greeted with a GPGS connecting screen followed by a Google Play logo (not a sign-in prompt mind you). The QA team is stating that this is a violation of Google Standards if the player has elected to not sign-in. 

In an attempt to resolve this issue, I created a dummy test application with only the Google Play Games plugin that just attempts to sign-in, cancelled the sign-in and I can duplicate the issue. My only thought is that the problem stems from the real-time multiplayer integration in the plugin as I can see the RTMP client disconnect message when the game is backgrounded. 

Is this truly a violation of Google Standards? Is the issue due to the real-time multiplayer portion of the plugin? We don't use any of the real-time multiplayer functionality in our game. Is there a setting to stop this attempted connection from happening? How can I fix this?

**Comment by fknr** [comment]
This seems to be connected to the SocialPlatform implementation of Unity. I noticed the same behavior with Game Center on iOS.

**Comment by JimmyDeemo** [comment]
I too am having this issue; it is a pretty annoying bug if not a violation of the Google Standards. This is related to #1884 in that there isn't any callback to suggets why the authentication didn't process.

**Comment by mindstormUmar** [comment]
I was having almost same issue. When you press login button and don't give permission to login and go to background and on resuming GP sign in will automatically start,  This issue is solved for us by going with the default PlayGamesClientConfiguration. Due to this sometimes it becomes an infinite sign in loop.
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
