### ISSUE TITLE
Google play services stopped working after publishing

### ISSUE THREAD

**Issue by maor91** [playgameservices/play-games-plugin-for-unity#1882]
Hello,
I was able to sign in to google play services on my alpha testing version, but now after i published the game it wont sign in to my google user.
I verified that "Saved Games" is enabled and that the SHA1 at the credentials section of API and Services matches the SHA1 of my game.

Thanks in advance!  :)

**Comment by maor91** [comment]
Actually, if i install the apk directly from google play store i cant sign in, otherwise it works fine.
Also i forget to mention that the SHA1 at the Upload Certificate matches with the 2 SHA1 i mentioned before.

**Comment by dalvaren** [comment]
I m also experiencing this behaviour. Does anyone solved that?

**Comment by Villfuk02** [comment]
Same issue, any updates or how you fixed it?
