### ISSUE TITLE
Auth failed or canceled?

### ISSUE THREAD

**Issue by saiichihashimoto** [playgameservices/play-games-plugin-for-unity#1884]
In the [
Quality Checklist for Google Play Games Services](https://developers.google.com/games/services/checklist#1_5), we're told to "Remember if players declined signing-in." In the [readme](https://github.com/playgameservices/play-games-plugin-for-unity#sign-in), we're shown the code for authentication:

```csharp
    using GooglePlayGames;
    using UnityEngine.SocialPlatforms;
    ...
    // authenticate user:
    Social.localUser.Authenticate((bool success) => {
        // handle success or failure
    });
```

So how do I differentiate between the Authentication failing for some reason or the user declining to sign in? There's no error in the callback so I'm not sure whether I should assume failure (and ask the user next time they open the app) or assume rejection (and not ask again).

**Comment by TimberXiao** [comment]
`Social.localUser.Authenticate((bool success) => {
        // handle success or failure
        if(success)
        {
            // handle success
        }
        else
        {
            //handle failure
        }
    });`

**Comment by saiichihashimoto** [comment]
@TimberXiao I'm not asking how to differentiate between success and failure. I'm asking how to differentiate between failure because they denied to authenticate and failure because of other reasons (an actual error).

**Comment by JimmyDeemo** [comment]
Intrestingly enough, Unity 2017 has another Authenticate function that takes a callback action that has an error string. I wonder if this is what is needed here; https://docs.unity3d.com/ScriptReference/SocialPlatforms.ILocalUser.Authenticate.html.

**Comment by saiichihashimoto** [comment]
Interesting @JimmyDeemo! I'm curious if this string only gets set on error or if it also gets set when denied (or neither or just on denial...).

**Comment by saiichihashimoto** [comment]
Ping

**Comment by dmitrykurteanu** [comment]
The error message is the same, whether I cancel (by pressing the back button) or if there is no internet connection.
In both cases it just says: "Authentication canceled"
Makes no sense

**Comment by ZOSDanBatson** [comment]
Bump.  My experience is the same as dmitrykurteanu.  I'm trying to account for the cert requirement "Remember if players declined signing-in" as well, and the only thing I have to go on with the Unity plugin is (bool success, string message) where message says "Authentication canceled" even in the event of an unrelated auth failure.  So my only option seems to be look for the "Authentication canceled" regardless of why it happened and never automatically try it again.  Which doesn't seem right.

**Comment by birdkingz** [comment]
Bump! I need this to be solved!
It was requested by Google Play team in order to be featured on Play Store!
Please let us know whether authentication failed due to User Cancelled or Network Error
