### ISSUE TITLE
Participant IsConnectedToRoom status

### ISSUE THREAD

**Issue by SamihElsakhawi** [playgameservices/play-games-plugin-for-unity#1887]
Hi,

I'm having trouble to check if a participant is still connected to a room.

I wrote this:

`bool status = GooglePlayGames.Native.PInvoke.MultiplayerParticipant.AutomatchingSentinel ().IsConnectedToRoom();

		if (status = true) 
		{
			this.gameObject.GetComponent<Text> ().text = "participant is connected";
		}

		if (status = false) 
		{
			this.gameObject.GetComponent<Text> ().text = "participant left";
		}`

When players are connected, "participant is connected" is displayed.

But when a player press the home button, and go back to the screen, the participant had OnPeersDisconnected called. But for the actual player, "participant is connected" is still displayed.

How can i know when the IsConnectedToRoom() is false?

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
