### ISSUE TITLE
Get the user's score value from Leaderboard

### ISSUE THREAD

**Issue by xeraphone** [playgameservices/play-games-plugin-for-unity#189]
Hi, this is an awesome plugin! my question is probably already asked by someone else but I have to ask anyway, is there a way to get the value of the score from Leaderboard?
I know for posting is : 

------------------------------------------------------------------------------
Social.ReportScore(MyHighestScore, "Leaderboard_ID", (bool success) => {
        // handle success or failure
    });

------------------------------------------------------------------------------
but how do I get that value back to be displayed within the game ? is it not implemented yet?
thx again

**Comment by claywilkinson** [comment]
Consolidating this into #186 to track  the enhancement.

**Comment by IYourSunshineI** [comment]
If anyone is still searching for a solution:

`Social.LoadScores(GPGSIds.leaderboard_leaderboard, scores =>
            { 
                if(scores.Length > 0)
                {
                    Debug.Log("Got scores");
                    foreach (IScore score in scores)
                    {
                        if(score.userID == Social.localUser.id)
                        {
                            FindObjectOfType<ScreenManager>().ScoreTextGameOverScreen.text = score.value.ToString();
                        }
                    }
                }
                else
                {
                    Debug.Log("No scores");
                }
            });'
            
           
this did it for me.
Printed out the highscore from the leaderboard into a TmpText
