### ISSUE TITLE
Cannot restart auth after signout

### ISSUE THREAD

**Issue by leeseiyoun** [playgameservices/play-games-plugin-for-unity#1890]
->OnApplicationStart
`PlayGamesPlatform.InitializeInstance(config01);`
`PlayGamesPlatform.Activate();`
`PlayGamesPlatform.Instance.Authenticate(); // SUCCESS!`
-~~~
->After a few minutes, if player touches 'change account button'
`PlayGamesPlatform.Instance.SignOut();`
`PlayGamesPlatform.InitializeInstance(config02);`
`PlayGamesPlatform.Instance.Authenticate(); //FAIL!`
-~~~
->Logcat
`GamesNativeSDK : Can only create one instance of GameServices at a time.`
`InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK`
`TokenFragment : Google SignIn Result is null?`

1. Do i have to wait sign out completely before authentication? How can i do that?
2. How can i change PlayGamesClientConfiguration? Seems like calling PlayGamesPlatform.InitializeInstance second ignores the new config settings.

**Comment by claywilkinson** [comment]
Unfortunately, the C++ SDK (which is the implementation of this plugin) does not support re-configuration.  What fields are you trying to reconfigure?

**Comment by leeseiyoun** [comment]
I want to reconfigure 'SetAccountName' when player change account.

**Comment by mobeenk** [comment]
How did you manage your game to sign in with an account because mine keeps trying to connect then disappears without allowing to connect to an account ?

**Comment by leeseiyoun** [comment]
Try sign in when app starts. When Player try to change account, i do sign out, then call sign in again
