### ISSUE TITLE
Unable to merge android manifests

### ISSUE THREAD

**Issue by SiERRAeStudio** [playgameservices/play-games-plugin-for-unity#1894]
Hi,

I using Unity v5.4.1f1, when I want to build the APK file the following error occurs:

CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/Jaime/android-sdks/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[

]
stdout[
Warning: [Temp/StagingArea/AndroidManifest-main.xml:12, /Users/Jaime/Documents/PROY_DIES/ProyectosUnity/Mars 9 ver Android TAPPX 1.25B/Temp/StagingArea/android-libraries/GooglePlay/AndroidManifest.xml:3] Main manifest has <uses-sdk android:targetSdkVersion='23'> but library uses targetSdkVersion='24'
[Temp/StagingArea/AndroidManifest-main.xml, /Users/Jaime/Documents/PROY_DIES/ProyectosUnity/Mars 9 ver Android TAPPX 1.25B/Temp/StagingArea/android-libraries/play-services-basement-11.0.4/AndroidManifest.xml:5] Skipping identical /manifest/application/meta-data[@name=com.google.android.gms.version] element.
]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.HostView:OnGUI()

Please help me!!!

Regards,

Jaime

**Comment by claywilkinson** [comment]
You need to change the min SDK in Unity Android Player Settings to be 24.  The min value needs to be the largest min value of all the aars you are including.

**Comment by SiERRAeStudio** [comment]
Hi claywilkinson,
Thanks, but I using Unity version 5.4.1f1 and can't change min SDK to 24, only 22. But I found the following solution for me:
1) Download Android SDK Tools:
    If your computer is Windows: http://dl-ssl.google.com/android/repository/tools_r25.2.5-windows.zip
    If your computer is MAC: https://dl.google.com/android/repository/tools_r26.0.2-macosx.zip
2) Go to your Android SDK Folder. There may be 2 folders of Android SDK, you must go the one in Unity Preferences.
3) Rename the old Android sdk "Tool" folder : [Your Android SDK root]/tools -> toolsXXXX
4) Extract that to Android SDK root folder.
5) Check the platforms folder, you must have the versions that you have in conflict, but you must upgrade with Android Studio or Android SDK Manager. These can be in another folder, if so the copies and paste in the platforms folder of the Android SDK that Unity uses.
6) In Unity go to Edit>Preferences>External Tools and check again, that the path for Android SDK points to the correct folder. (The correct path is the SDK root folder, not the tools folder which is inside the root folder!)
7) Build your project.

Excuse my English, I'm Chilean.

**Comment by claywilkinson** [comment]
Thanks @SiERRAeStudio .  As you pointed out there was a problem with how Unity and the Android SDK interacted and your workaround is OK.

(English was very good  :))
