### ISSUE TITLE
Login prompts a second time when user choses not to login

### ISSUE THREAD

**Issue by eifelgamedev** [playgameservices/play-games-plugin-for-unity#1895]
The first time a user starts our app he gets prompted to login, iff he choses not to, it pops up again 2 seconds after they close the login prompt.
This only happens once per Session.

I dont get any logs that indicate an error or a double method call.
Is this the expected behavior and is there any way to change this?

**Comment by claywilkinson** [comment]
Which version of the plugin are you using?  This was a problem in older versions, I think 0.9.40 took care of this.  Are you requesting email, id token, or auth code?

**Comment by eifelgamedev** [comment]
I used 9.38 until 2 days ago. After I updated to 9.40 it still happened though. Im using e-mail authentication.
I would share a log but theres nothing happening in logcat when this occurs.

I just did some testing on a clean project and it doesnt occur there so i guess something went wrong when updating?
Anyways im gonna try to update again and see if that fixes it, thanks for the answer!

**Comment by eifelgamedev** [comment]
Update: 
Adding `.RequestEmail()` to my config fixed the bug.
