### ISSUE TITLE
GooglePlayGames could not be found

### ISSUE THREAD

**Issue by LadIQe** [playgameservices/play-games-plugin-for-unity#1896]
Hi, i imported official plugin for google play games and i have problem to make it work

I did every step in guide but when i add 
using GooglePlayGames

i get error:
Assets/Standard Assets/Scripts/Banner_Int.cs(1,7): error CS0246: The type or namespace name `GooglePlayGames' could not be found. Are you missing an assembly reference?

And i dont know what to do. I re-imported it 3x but nothing, also i updated everything, still nothing

**Comment by claywilkinson** [comment]
I would suggest following the instructions to build one of the samples first, then you probably will see what is going wrong.  The instructions for the samples are here: https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/samples/README.md.
