### ISSUE TITLE
Firebase 4.1.0 PlayServicesResolver conflicts with Play Games 0.9.40

### ISSUE THREAD

**Issue by ramioooz** [playgameservices/play-games-plugin-for-unity#1900]
Hello Everyone,

I have just updated to the latest firebase sdk for unity v 4.1.0
there are some new features and bug fixes in the package worth updating.

the problem is, that as soon as I installed the plugin into unity - it went ahead and removed old Jar Resolver installed with Play Games 0.9.40 and considered it as obsolete. I don't have problem with that, but now with the new Jar Resolver came with the firebase - unity can't resolve needed jars correctly.

I noticed there is a new sub-menu called "Force Resolve Client Jars" now added. every time I try it It open SDK tools panel and asks me to install Android SDK 26.0.2 and m2repositories. I confirm it but It always fail.

I am not an expert but I think the new Jar Resolver came with Firebase 4.1.0 can't pull or recognize needed jars from Android SDK.

I think Play Games should release and update with new Jar Resolver that could fix this conflict caused by Firebase 4.1.0. I think this is not the first time for this to happen, I suggest that you guys should work together or make a unified plugin that include play games with Firebase.

In the mean time I think I will roll back to old Firebase 4.0.3 that worked fine with Play Games 0.9.40 and wait for Play Games new update.

Thank You,
Rami

**Comment by ramioooz** [comment]
Hey @claywilkinson 

I managed to update Android SDK to version 26.0.2 using Android Studio.
but still I am getting this error whenever I try to 'Force Resolve Client Jars' using PlayServicesResolver that came with latest Firebase : 
```
Gradle failed to fetch dependencies.

Failed to run 'Temp\PlayServicesResolverGradle\gradlew.bat -b Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle "-PANDROID_HOME=D:/Android/sdk" "-PTARGET_DIR=C:\Users\Rami\Google Drive\Game_Development\Unity_Projects\TheEgg\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///C:/Users/Rami/Google Drive/Game_Development/Unity_Projects/TheEgg/Assets/Firebase/m2repository" "-PPACKAGES_TO_COPY=com.google.firebase:firebase-analytics:11.2.0;com.google.firebase:firebase-core:11.2.0;com.google.firebase:firebase-analytics-unity:4.1.0;com.google.android.gms:play-services-base:11.2.0;com.google.firebase:firebase-common:11.2.0;com.google.firebase:firebase-app-unity:4.1.0;com.google.android.gms:play-services-appinvite:11.2.0;com.google.firebase:firebase-dynamic-links-unity:4.1.0;com.google.firebase:firebase-messaging:11.2.0;com.google.firebase:firebase-messaging-unity:4.1.0;com.google.firebase:firebase-config:11.2.0;com.google.firebase:firebase-config-unity:4.1.0;com.google.android.gms:play-services-games:11+;com.google.android.gms:play-services-nearby:11+;com.google.android.gms:play-services-auth:11+"'
stdout:

BUILD FAILED

Total time: 1.962 secs

stderr:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Rami\Google Drive\Game_Development\Unity_Projects\TheEgg\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle' line: 129

* What went wrong:
A problem occurred evaluating root project 'PlayServicesResolverGradle'.
> Illegal character in path at index 28: file:///C:/Users/Rami/Google Drive/Game_Development/Unity_Projects/TheEgg/Assets/Firebase/m2repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

exit code: 1
```

I hope this help.
Thank You

**Comment by JimmyDeemo** [comment]
Is this a duplucate of #1892?

**Comment by ramioooz** [comment]
Hey @JimmyDeemo 

No it not the same error as you can see

**Comment by ramioooz** [comment]
Problem Sloved.
credit goes to @lostin
found here : 
[https://github.com/firebase/quickstart-unity/issues/110](url)
----------------
I have the same problem. The problem is that there is a space in the string.
Google[space]Drive.

see =>
[SomeUnityProject]/Temp/PlayServicesResolver.scripts.download_artifacts.gradle

line: 129 => mavenUris.push(new URI(it))

The URI does not seem to support spaces.

**for the time being** : consider chaning your development directory for your unity project to directory without spaces in the name

hey @claywilkinson 
we will wait for next SDK update to have this solution included please.

Thank You

**Comment by lostsin** [comment]
you're welcome!

**Comment by stewartmiles** [comment]
The latest Play Services Resolver (1.2.53) handles references to conflicting versions of Google Play Services.  We rolled this up in the 4.2.0 release of the Firebase Unity SDK.  https://firebase.google.com/support/release-notes/unity#4.2.0
