### ISSUE TITLE
Not working with FragmentActivity (ArgumentException: Can only use lower 16 bits for requestCode)

### ISSUE THREAD

**Issue by xy2041** [playgameservices/play-games-plugin-for-unity#1901]
For some reason, I use my own _MyUnityPlayerActivity_ that extends _FragmentActivity_. Unfortunately, in this case, login not working with error:
_E GamesNativeSDK: Exception in android/app/Activity.startIntentSenderForResult: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode._

It's happening because of this:
BaseFragmentActivityGingerbread.java, startActivityForResult implementation:
```
[...]
if ((requestCode & 0xffff0000) != 0) {
    throw new IllegalArgumentException("Can only use lower 16 bits for requestCode");
}
```
Somewhere inside libgpg.so requestCode param for startActivityForResult call hardcoded as 0x475047, that not fit requirements of FragmentActivity.

I think that 0x475047 constant should be changed to avoid the problem.

**Comment by vaibhavgpt-google** [comment]
Closing this issues as it's not related to Unity Plugin
