### ISSUE TITLE
Better realtime multiplayer support: exclusiveBitMask on creating rooms and Reliable Message callback

### ISSUE THREAD

**Issue by ivanquirino** [playgameservices/play-games-plugin-for-unity#1903]
I see that the exclusiveBitMask for room creation is missing from the Unity API, any chance that this could be implemented? It would be really nice to have. The Reliable Message callback is another feature that I would like to see in Unity's plugin so I can explore more of realtime multiplayer. 
I'm currently making a 1v1 game that I would like to use the exclusive bitmask to not allow repeated heroes in the match. And sending an ACK to a reliable has really high latency.

Anyway, thank you for providing this plugin, it is enabling our new project to turn into a game easier.

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
