### ISSUE TITLE
Account Picker displayed after backgrounding/foregrounding app

### ISSUE THREAD

**Issue by supersolid-Justy** [playgameservices/play-games-plugin-for-unity#1909]
Hi!

I recently changed from 0.9.36 to 0.9.40 of the plugin.
If you are signed in - everything works fine so far. 
However, if the game starts and shows the Account Picker for a google play account on startup and you decline it (click around it), then the account picker prompt will be displayed every time the app gets backgrounded/foregrounded.
Does anyone else experience the same issue?
I have got .RequestServerAuthCode(false) at start of the game as I need the auth code, the moment its set, it will cause this issue. 
Is there a flag i have to set somewhere? The app was not displaying this account picker on users decline every single time in 0.9.36, so it might be a setting somewhere I could be missing?
Thanks in advance

**Comment by supersolid-Justy** [comment]
Probably a duplicate from the following:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1874
but did not get answered nor resolved

**Comment by supersolid-Justy** [comment]
Duplicate #1811

**Comment by claywilkinson** [comment]
Merged into 0.9.42.   Thanks again!

**Comment by supersolid-Justy** [comment]
Thanks Clay for accepting it :)!
