### ISSUE TITLE
 GetToken failed with status code: INVALID_AUDIENCE

### ISSUE THREAD

**Issue by iMemento** [playgameservices/play-games-plugin-for-unity#1911]
```
09-11 13:09:28.449: W/Auth(23241): [GetToken] GetToken failed with status code: INVALID_AUDIENCE
09-11 13:09:28.454: E/TokenRequestor(23004): You have wrong OAuth2 related configurations, please check. Detailed error: INVALID_AUDIENCE
```

This drive me crazy now. I run exactly the same sdk code  and  same configurations(bundle id, version number, .keystore file), the demo runs fine, but  my game always report the error above.

**Comment by claywilkinson** [comment]
Invalid audience usually means the web client id is incorrect.  It needs to be the  client id of a linked app to your game and it needs to be a "web" app.  Maybe re-run the configuration to make sure it is set up correctly?

**Comment by iMemento** [comment]
@claywilkinson Thanks! My game linked "android app" not a "web" app! Thanks man!  You save my life!

**Comment by claywilkinson** [comment]
Glad I could help!  Best of luck with your game!

**Comment by gitgukE** [comment]
thank you!
