### ISSUE TITLE
ShowLeaderboardUI not showing at all

### ISSUE THREAD

**Issue by lolmourne** [playgameservices/play-games-plugin-for-unity#1914]
I have problem to showing leaderboard UI. The login process is running smoothly and I can see the user who logged in. And submitting new score is also running. I tried to find solution on the internet but nothing is working.

here are the logcats

09-18 10:48:30.292 7971-8011/? I/Unity:  [Play Games Plugin DLL] 09/18/17 10:48:30 +07:00 DEBUG: Invoking user callback on game thread
                                         
                                        (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
09-18 10:48:30.292 7971-8011/? I/Unity:  [Play Games Plugin DLL] 09/18/17 10:48:30 +07:00 DEBUG: Received UI callback: ERROR_UI_BUSY
                                         
                                        (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by rsodre** [comment]
Same.
Leaderboards and Achievement screens do not load.
Using 0.9.4 with play-services version 11.2.2 for Firebase compatibility.

The first time I try to open leaderboards I see this:

D/NativeBridgeActivity(14023): Launching bridge activity: parent:com.unity3d.player.UnityPlayerActivity@369854b3 intent Intent { act=com.google.android.gms.games.VIEW_LEADERBOARDS dat=version:11220000 flg=0x4000000 pkg=com.google.android.play.games (has extras) }

Subsequent times I see this:

I/Unity   (14023):  [Play Games Plugin DLL] 09/18/17 1:58:09 -03:00 DEBUG: ShowLeaderboardUI, lbId= callback is System.Action`1[GooglePlayGames.BasicApi.UIStatus]
I/Unity   (14023):  [Play Games Plugin DLL] 09/18/17 1:58:10 -03:00 DEBUG: Showing UI Internal callback: ERROR_UI_BUSY
I/Unity   (14023):  [Play Games Plugin DLL] 09/18/17 1:58:10 -03:00 DEBUG: Invoking user callback on game thread

**Comment by rsodre** [comment]
My problem was in the manifest. I'm using another distribution of this plugin that apparently is not configuring it properly. Created an empty project with version 0.9.40 and got what was missing:

```
		<!--- Google Play Services -->
		<meta-data android:name="com.google.android.gms.games.APP_ID"
		    android:value="\ 1234567890123" />
        <meta-data android:name="com.google.android.gms.games.unityVersion"
            android:value="\ 0.9.40" />
        <meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
        <activity android:name="com.google.games.bridge.NativeBridgeActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
        <!-- Required for Nearby Connections API -->
		<meta-data android:name="com.google.android.gms.nearby.connection.SERVICE_ID"
            android:value="" />

```

**Comment by AmalinaSukina** [comment]
Hello , i already fix this , u can try add this to your androidmanifest.xml at the end of file

( Assets/GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin/androidmanifest.xml )

Add this : 

 <activity android:name="com.google.games.bridge.NativeBridgeActivity"
  android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />

this is original

<?xml version="1.0" encoding="utf-8"?>

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.google.example.games.mainlibproj"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk android:minSdkVersion="8" android:targetSdkVersion="16" />

    <application>

     
        <meta-data android:name="com.google.android.gms.nearby.connection.SERVICE_ID"
            android:value="" />

        
        <meta-data android:name="com.google.android.gms.games.APP_ID"
            android:value="\ 106247102254" />

        
        <meta-data android:name="com.google.android.gms.games.unityVersion"
            android:value="\ 0.9.41" />

        
        <meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />


            <activity android:name="com.google.games.bridge.NativeBridgeActivity"
        android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
    </application>
</manifest>


i found this by others user , i just re-write this , hope this help u !
