### ISSUE TITLE
Can't Showleaderboard, Achivement

### ISSUE THREAD

**Issue by Kimjungjin87** [playgameservices/play-games-plugin-for-unity#1921]
use ver: GooglePlayGamesPlugin-0.9.41
use platform : unity

problem
Can't Showleaderboard, Achivement

The log that is output in this situation
<img width="341" alt="2017-09-21 9 51 28" src="https://user-images.githubusercontent.com/31198425/30674080-82aa8496-9eb2-11e7-84f3-59d9b5a4d9f7.png">

Suspicious part
unity project - plugin version ... row??

my plugin

![2017-09-21 9 36 40](https://user-images.githubusercontent.com/31198425/30674010-17641cec-9eb2-11e7-9ab6-d68c58b6ce09.png)

This version seems to be used too low. Is there any way to get the version up?
Of course, sdk was updated to the latest.

**Comment by Hauki** [comment]
We have the same issue. Worked fine in 039a. 

![image](https://user-images.githubusercontent.com/1457715/30690677-4dbd64b6-9ec5-11e7-865a-c81633d50020.png)

**Comment by supersolid-Justy** [comment]
Same here, can post logs later if needed.
The manifest change as described in #1914 doesnt fix it either.

**Comment by Kimjungjin87** [comment]
hi! Thanks for helping us.
@supersolid-Justy 
# 1941, I checked the issue, but I am well known as 9.4.1.

@Hauki 
Does it have to be identical with mine?
Can you tell me how to set up the settings?

11.2.2 after
This log is output.

<img width="354" alt="2017-09-21 7 16 49" src="https://user-images.githubusercontent.com/31198425/30691181-e1e83e5e-9f01-11e7-8dde-88391479c6be.png">

This is the last test plug-in.
![2017-09-21 7 20 53](https://user-images.githubusercontent.com/31198425/30691219-0814a0a4-9f02-11e7-98d1-8dc62620d8a8.png)

**Comment by Hauki** [comment]
Hi, 

@Kimjungjin87 What has to be identical and which settings?

**Comment by Kimjungjin87** [comment]
@Hauki 
I set the same pattern.

Well, I've got this sort of thing, so I've stopped that part of the equation.
![2017-09-21 7 31 19](https://user-images.githubusercontent.com/31198425/30691687-82ac2098-9f03-11e7-83c7-a8c625eb6483.png)

And I added this part.
![2017-09-21 7 32 09](https://user-images.githubusercontent.com/31198425/30691722-9ebfbb46-9f03-11e7-9b44-b9a68351b57c.png)

**Comment by Hauki** [comment]
@Kimjungjin87 

So I've removed 
![image](https://user-images.githubusercontent.com/1457715/30691785-27ef32ce-9ec9-11e7-94ed-63a71b81ecdd.png)
as it causes issue with gradle for us, merging of manifest files. It is defined in our main AndroidManifest file. 

Then I just added the other part and then it started working for us. If you copied my file then remember to put you own key as value for APP_ID.

**Comment by Kimjungjin87** [comment]
@Hauki 
Wow! 
If you were there, I would ask you to drink beer together today!

I'm so happy!

I've had a hard time doing this for a week!

Thanks so much. Thanks to you !!

<img width="365" alt="2017-09-21 7 33 27" src="https://user-images.githubusercontent.com/31198425/30691820-fda2cf90-9f03-11e7-941f-2e1bb5e26730.png">

<img width="364" alt="2017-09-21 7 33 43" src="https://user-images.githubusercontent.com/31198425/30691828-068fdf6c-9f04-11e7-8b28-1379bf527903.png">

**Comment by Kimjungjin87** [comment]
@Hauki 
There's another problem!

If you send a score to the leader board, the leader board screen won't open again ......

Of course, you can exit the app and reopen it.
Is my sauce a problem?

Can I have a look at this part?

public void _ShowLeader()
	{

        if (Social.localUser.authenticated == false)
		{
            Social.localUser.Authenticate((bool success) =>
 
		{
		if (success)
		{           
                    Social.ShowLeaderboardUI();
		          return;
		      }
		      else
		      {
		          // Sign In 실패 처리
		          return;
		      }
		  });
		}
		Social.ShowLeaderboardUI();
	}

PlayGamesPlatform.Instance.ReportScore(score, GPGSIds.leaderboardID, (bool success) =>
        {
            if (success)
            {

            }
            else
            {

            }
        });

**Comment by Kimjungjin87** [comment]
@Hauki 
Ah! This seems to be a problem for my project.
I think I need to rewrite it.

Once again, thank you so much and don't know whether it's daytime or night, but have a nice day!
