### ISSUE TITLE
No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version'). Note: This error happens regardless of whether I'm using the internal building option or the gradle building option

### ISSUE THREAD

**Issue by mbhaskar1** [playgameservices/play-games-plugin-for-unity#1922]
I am using version 9.41 and whenever I try to build my game I get this error. I even tried completely removing everything the plugin added and adding it again, and I got the same error. Do I need to use an older version or something?

**Comment by waltran** [comment]
This error occurs when i try to build with GRADLE option.

solution: Delete this lines from the androidmanifest also the template-androidmanifest too or simply build with Internal option.

`
        <meta-data android:name="com.google.android.gms.version"
android:value="@integer/google_play_services_version" />`

**Comment by mbhaskar1** [comment]
I get this error when building using the internal option. I'm not using the gradle option.

**Comment by mbhaskar1** [comment]
![image](https://user-images.githubusercontent.com/17301685/30774680-8bc0dc6c-a054-11e7-9295-098c934fad4f.png)

**Comment by mbhaskar1** [comment]
This is probably obvious, but I'm also getting the same error while using the Gradle build method.

**Comment by stewartmiles** [comment]
@claywilkinson I'm seeing this as well.  It looks like the `GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin` gets exported as a subproject without a dependency upon `play-services-basement`.

**Comment by mbhaskar1** [comment]
@claywilkinson please look into this. I am unable to build my project right now, so progress is really slow.

**Comment by PlanetVaster** [comment]
I am also getting this error, with Unity 2017.2 and GPGS 0.9.40. And gradle (haven't tested internal).

**Comment by brisa0730** [comment]
Also getting the same error. 

Just to check, I opened an empty project, installed GPGS 0.9.41. Same error.

This problem has a long history. I solved it by putting a version.xml file in "Plugins/Android/MainLibProj/res/values" directory. But after GPGS upgrade to 0.9.41, this workaround doesn't work anymore. It's been years and still developers has to do some adjustments to make this asset work properly.

**Comment by Dod2** [comment]
Had this problem today when upgrading to 0.9.41. 
I just hardcoded its value by adding the following metadata to my main manifest (the one in plugins/android)
`<meta-data android:name="com.google.android.gms.version" tools:node="replace" android:value="11400000" />`
Also had to add `xmlns:tools="http://schemas.android.com/tools"` in the main manifest declaration to 
use enable the tools and avoid merge conflicts.
Now every time I update my dependencies, I open the values.xml inside the new Play Games basement aar and copy the version number from there.

Ugly solution, but at least it compiles. Hope to see a proper solution to this recurring problem soon.

**Comment by claywilkinson** [comment]
This is fixed in 0.9.50.  Building with Gradle now works without modifying files.
