### ISSUE TITLE
Problem with AchievementsUI 0.9.41 

### ISSUE THREAD

**Issue by cthulhu2duo** [playgameservices/play-games-plugin-for-unity#1926]
I have integrated plugin in my project. Autentification completes successfully. Achievement unlocking is working. But AchievementsUI and SaveGameUI are not working. Tried to downgrade to previous version - everything works fine.

Here is some log:
```
I/GamesNativeSDK: Successfully connected to Google Play.
E/GamesNativeSDK: Trying to show UI while waiting for a result from an existing UI. Please ensure that OnActivityResult is forwarded to the Games C++ SDK from your Java activity. See android_support.h for more details.
I/Unity:  [Play Games Plugin DLL] 09/23/17 1:29:22 +06:00 DEBUG: Showing UI Internal callback: ERROR_UI_BUSY (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity:  [Play Games Plugin DLL] 09/23/17 1:29:22 +06:00 DEBUG: Invoking user callback on game thread (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity:  [Play Games Plugin DLL] 09/23/17 1:29:22 +06:00 DEBUG: Received UI callback: ERROR_UI_BUSY (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
I/Unity:  [Play Games Plugin DLL] 09/23/17 1:29:22 +06:00 DEBUG: ShowAchievementsUI callback is (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```

**Comment by rogersteve97** [comment]
I have the same issue. Please help!

**Comment by renanrider** [comment]
@cthulhu2duo @rogersteve97 Look [this](https://github.com/playgameservices/play-games-plugin-for-unity/issues/1931)

**Comment by rogersteve97** [comment]
How do I downgrade to 0.9.40?

**Comment by renanrider** [comment]
@rogersteve97 Remove the plugin -> https://github.com/playgameservices/play-games-plugin-for-unity/issues/1932#issuecomment-332004889    and download the version v0.9.40, select the branch or tag for v0.9.40, and config it.

**Comment by rogersteve97** [comment]
It's not in the old-builds folder.

**Comment by rogersteve97** [comment]
Disregard that. I'm sorry for my incompetence.

**Comment by rogersteve97** [comment]
Oh, thanks!

**Comment by dibakarjana** [comment]
Downgrading to v0.9.40 worked for me.

**Comment by supersolid-Justy** [comment]
Adding 
```
         <activity android:name="com.google.games.bridge.NativeBridgeActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
```
to the AndroidManifest.xml of the plugin will make it work.

**Comment by kshankin** [comment]
@supersolid-Justy, your suggestion worked for me. Thanks so much! That was many days of pulling my hair out.

**Comment by eintopf** [comment]
Any other idea what I could do to get this running? I have this NativeBridgeActivity in there, but it still comes up with the ui busy error. I assume it is a conflict with the Facebook SDK, which also adds some activites to the manifest.

**Comment by PHARTGAMES** [comment]
@supersolid-Justy, Thanks for the post this fixed it for me also.

**Comment by ettore3091** [comment]
@eintopf So did you solve the issue? I also am using the Facebook SDK and I'm getting the same error.

**Comment by cthulhu2duo** [comment]
@supersolid-Justy Thank you. It worked for me.
