### ISSUE TITLE
Version 0.9.41 - Trying to show UI while waiting for a result from an existing UI.

### ISSUE THREAD

**Issue by renanrider** [playgameservices/play-games-plugin-for-unity#1931]
After SignIn I'm trying to show Achievement, but don't it displayed, and the message bellow is displayed on logcat.

Trying to show UI while waiting for a result from an existing UI. Please ensure that OnActivityResulty is forwarded to the Games C++ SDK from your Java activity. See android.suport.h for more details.

Thanks.

**Comment by Spyispie120** [comment]
Version 0.9.41 seem to not working for me either. However, downgrading to 0.9.40 seem to does the trick. My guess is that 0.9.41 still have bugs, or is not fully develop yet.

**Comment by renanrider** [comment]
I'll try to make the downgrading, thank.

**Comment by renanrider** [comment]
@Spyispie120 I made Downgrade to version 0.9.40 and it really works perfectly! Thanks

**Comment by Spyispie120** [comment]
@renanrider Glad I could help!

**Comment by emeahonen** [comment]
Add This Line: 
        <activity android:name="com.google.games.bridge.NativeBridgeActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
to your AndroidManifest.xml . Anywhere inside <application> I have it below:
         <meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
