### ISSUE TITLE
Upgraded to 0.9.41 and won't build

### ISSUE THREAD

**Issue by terids** [playgameservices/play-games-plugin-for-unity#1932]
Just upgraded the plugin to try and solve this "false authentication" issue i've been having.

Unity fails to build a package, showing the following 2 errors. I have tried deleting the Temp folder. I have setup Android in Unity, it was complaining about no manifest.xml file, but i copied one over to the project and it fixed that issue at least...

https://pastebin.com/31Ffs7hC
https://pastebin.com/XAe30i7w

Help please!

**Comment by renanrider** [comment]
Try to completely remove the plugin and delete these folders:

Assets / GPGIds.cs
Assets / GPGIds.cs.meta
Assets / GooglePlayGames
Assets / GooglePlayGames.meta
Assets / PlayServicesResolver
Active / PlayServicesResolver.meta
Active / Plugins
Active / Plugins.meta
ProjectSettings / AndroidResolverDependencies.xml
ProjectSettings / GooglePlayGameSettings.txt
ProjectSettings / GvhProjectSettings.xml

Then follow the [steps](https://github.com/playgameservices/play-games-plugin-for-unity#configure-your-game) to install and try to build.

I have this problem and after these steps I was able to build

**Comment by terids** [comment]
Thanks for the reply.

I tried this but it's still not building. I keep getting "Failed to re-package resources" :/

**Comment by Spyispie120** [comment]
Based on your log, it seem like you have multiple duplicated play-services files; make sure to only have 1 version of each, and all of them need to be in the same version.

play-services-base-10.2.6
play-services-base-8.3.0

play-services-basement-10.2.6
play-services-basement-8.3.0

play-services-drive-10.2.6
play-services-drive-8.3.0

play-services-games-10.2.6
play-services-games-8.3.0

play-services-nearby-10.2.6
play-services-nearby-8.3.0

**Comment by terids** [comment]
I delete all the duplicates inside the Plugin folder, delete GooglePlayGames folder and the PlayServicesResolver folder. Re-installed plugin 0.9.40. Now I'm getting a new error: CommandInvokationFailure: Unable to convert classes into dex format.

https://pastebin.com/wgnrExGr

I can't see any of those error files listed anywhere on my hard-drive after a thorough search. Completely stumped!

**Comment by Spyispie120** [comment]
Alright good, we are getting somewhere, can you upload a picture of what you have in your Pluggin/Android folder. This is what i have (it might be a little bit different since i have other pluggin installed)
![pluggin screen shot](https://user-images.githubusercontent.com/12041033/30836548-ce0135e8-a213-11e7-8010-4ca98f905b17.png)

**Comment by terids** [comment]
Yep.. I have tried checking for duplicate .jar files in here but there doesn't seem to be any.

![explorer_2017-09-26_01-38-10](https://user-images.githubusercontent.com/10546876/30837232-5b8dc20e-a25b-11e7-879e-a9746554ef39.png)

**Comment by Spyispie120** [comment]
play-services-plus is not the same version as the other play-services.

**Comment by terids** [comment]
I just noticed that myself. I'll see if I can find the later version!

**Comment by terids** [comment]
Sadly it has not fixed it. No change.

**Comment by Spyispie120** [comment]
Hmm because from my experience the error "CommandInvokationFailure: Unable to convert classes into dex format." mean that some file is duplicated. Can you double check to make sure no ".aar" file in your **Plugin folder** is duplicated.

**Comment by terids** [comment]
100% there are no duplicate files in that folder. I might have to just create a new project and start over.

**Comment by terids** [comment]
Tried rolling back to 0.39a, nuking my plugins folder and adding this plugin again from scratch. I am STILL getting this DEX error. Completely out of ideas.

**Comment by terids** [comment]
Finally got it to build again. I didn't realise a .aar and .jar would conflict with each other.

In this instance my problem files were:
Assets\Plugins\Android\play-games-plugin-support.aar
Assets\Plugins\Android\MainLibProj\libs

I deleted the former.

Thanks for all the assistance, it's appreciated! :)
