### ISSUE TITLE
Leaderboard dont shows up [ Bad call - error log ].

### ISSUE THREAD

**Issue by genaray** [playgameservices/play-games-plugin-for-unity#1933]
So... after some struggle to implement appodeals and google play games services, i managed to sucessfull connect to the google play servers. My next step is to show the leaderboard. But somehow it gives me an error when i try to excecute the following :

 `     public void showLeaderBoard() {

        if (PlayGamesPlatform.Instance.IsAuthenticated())
        {
            PlayGamesPlatform.Instance.ShowLeaderboardUI("CgkI7_WoqMcIEAIQAg");
        }
        else {

            // Not logged in...

        }

    }`

Normally everything should be alright. I saw it in dozens of videos, that this is execatly the away to call one specific leaderboard. No matter, this is what i get ...

`GamesServiceBroker: Client connected with SDK 11411000, Services 11673438, and Games 52250038
GamesNativeSDK: Play Games callback indicates connection.
GamesNativeSDK: Successfully connected to Google Play.
GamesNativeSDK: Trying to show UI while waiting for a result from an existing UI. Please ensure that OnActivityResult is forwarded to the Games C++ SDK from your Java activity. See android_support.h for more details.
GamesServiceBroker: Client connected with SDK 10260000, Services 11673438, and Games 52250038
GamesServiceBroker: Client connected with SDK 11411000, Services 11673438, and Games 52250038
AppOps  : Bad call: specified package com.google.android.play.games under uid 10335 but it is really 10129
AppOps  : java.lang.RuntimeException: here
AppOps  :      at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1257)
AppOps  :      at com.android.server.AppOpsService.checkPackage(AppOpsService.java:976)
AppOps  :      at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
AppOps  :      at android.os.Binder.execTransact(Binder.java:565)
ConnectivityManager: isActiveNetworkMetered() returns:false`

Any idea what that means and how to avoid it ? Already reinstalled the whole plugin for about 5 times... wont to it again >.<.

**Comment by renanrider** [comment]
@genaray Use the previous version of the plugin, look -> https://github.com/playgameservices/play-games-plugin-for-unity/issues/1931

**Comment by genaray** [comment]
Just fixed it, found this by an other user : 

Hello , i already fix this , u can try add some lines to your androidmanifest.xml at the end of file

( Assets/GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin/androidmanifest.xml )

<uses-sdk android:minSdkVersion="8" android:targetSdkVersion="16" />

<application>

 
    <meta-data android:name="com.google.android.gms.nearby.connection.SERVICE_ID"
        android:value="" />

    
    <meta-data android:name="com.google.android.gms.games.APP_ID"
        android:value="\ 106247102254" />

    
    <meta-data android:name="com.google.android.gms.games.unityVersion"
        android:value="\ 0.9.41" />

    
    <meta-data android:name="com.google.android.gms.version"
        android:value="@integer/google_play_services_version" />


        <activity android:name="com.google.games.bridge.NativeBridgeActivity"
    android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
</application>
i found this by others user , i just re-write this , hope this help u !
