### ISSUE TITLE
CommandInvokationFailure: Unable to convert classes into dex format.

### ISSUE THREAD

**Issue by eklebanski** [playgameservices/play-games-plugin-for-unity#1937]
There is an error when compiling Unity's (5.5.4p3) project with:
- Admob plugin 3.7.1
- Firebase plugin 4.1.0
- Google Play Games 0.9.41

The log is as follows: 
CommandInvokationFailure: Unable to convert classes into dex format.
C:/Program Files/Java/jdk1.8.0_101\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/xxx/AppData/Local/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzdil;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzdim;

[...]

Any ideas, fixes, workarounds? It's been over a month right now and nobody is looking into the issue...

**Comment by Spyispie120** [comment]
Look at these issues close #1932 close #1931 , it should give you some ideas of how to fix it.

**Comment by eklebanski** [comment]
Hi Spyispie120, Checked those issues and unfortunately the solutions didn't help

**Comment by Spyispie120** [comment]
Hmmm, the error: "CommandInvokationFailure: Unable to convert classes into dex format." usually means something is conflicted, and in the stderr [ ... ], it even said the 2 files already added. 

Double check your Asset/Plugins folder again, you might have missed something. Also .aar, and .jar could also be conflicted with each other, as issue #1932 mentioned.

**Comment by eklebanski** [comment]
After forcing jar resolver the files I'm getting are as follows (maybe it will shed some light on the issue):

firebase-analytics-11.2.0.aar
firebase-analytics-impl-11.2.0.aar
firebase-analytics-unity-4.1.0.aar
firebase-app-unity-4.1.0.aar
firebase-common-11.2.0.aar
firebase-config-11.2.0.aar
firebase-config-unity-4.1.0.aar
firebase-core-11.2.0.aar
firebase-dynamic-links-11.2.0.aar
firebase-iid-11.2.0.aar
firebase-invites-unity-4.1.0.aar
play-services-ads-11.2.2.aar
play-services-ads-lite-11.2.2.aar
play-services-appinvite-11.2.0.aar
play-services-auth-10.2.6.aar
play-services-auth-base-10.2.6.aar
play-services-base-11.2.0.aar
play-services-basement-11.2.2.aar
play-services-drive-10.2.6.aar
play-services-games-10.2.6.aar
play-services-gass-11.2.2.aar
play-services-nearby-10.2.6.aar
play-services-tasks-11.2.0.aar
support-annotations-25.2.0.jar
support-compat-25.2.0.aar
support-core-ui-25.2.0.aar
support-core-utils-25.2.0.aar
support-fragment-25.2.0.aar
support-media-compat-25.2.0.aar
support-v4-25.2.0.aar

**Comment by supersolid-Justy** [comment]
Check also for the 
play-games-plugin-support existing twice in the project, clay moved it around between 0.9.40 and 0.9.41

**Comment by eklebanski** [comment]
Even when I remove play-games-plugin-support.arr from the project I'm getting the same error

**Comment by eklebanski** [comment]
Removing Google Play Games 0.9.41/40 and it's arr's in /Plugins/Android and getting back to 0.9.39a version did the trick (play-services-* properly resoluted to 11.2.2 versions).

The question is how it's possible that this kind of major drawback is pushed into repository?? Good job developers!
