### ISSUE TITLE
Suppress UI popups during VR?

### ISSUE THREAD

**Issue by JimmyDeemo** [playgameservices/play-games-plugin-for-unity#1943]
Is there a way to supress achievement popups, or other UI elements from GPG, without signing out? We have a problem when using cardboard VR and this feature would be handy.

**Comment by supersolid-Justy** [comment]
Never tried, but:
```
	PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
		  **.EnableHidePopups()**
		  .Build();
```
might be what you need

**Comment by JimmyDeemo** [comment]
That does seems useful, but that is during initialisation right? Can you change configuration of GPG during a session? I guess I will have to try it.

**Comment by supersolid-Justy** [comment]
From what I can say, I do not see it being possible to enable/disable them during the session, but I might be wrong.

With some enum modifications (for Gravity) could might be able to use *PlayGamesPlatform.Instance.SetGravityForPopups()** to do the trick? It seems to specify where the popup is being displayed (so maybe you can modify it to be shown outside the screen if you want to "hide" it, or not)?

**Comment by JimmyDeemo** [comment]
Closing this as duplicate of #1941.

**Comment by Dirly** [comment]
@JimmyDeemo Did the Gravity fix actually work for you??

and any chance you can share how you did it?
