### ISSUE TITLE
Duplicate file(s) in apk: '....\Temp\StagingArea\android-libraries\play-games-plugin-support\libs'

### ISSUE THREAD

**Issue by edscodeblenders** [playgameservices/play-games-plugin-for-unity#1944]
Hi guys,

For my Unity game I was previously using Google Mobile Ads SDK 3.6.3, and Google Play Games Plugin 0.9.40. Now I just upgraded to Google Mobile Ads SDK 3.7.1, and Google Play Games Plugin 0.9.41, and since then I can't build my project for Android anymore. I'm getting the error:
Duplicate file(s) in apk: '....\Temp\StagingArea\android-libraries\play-games-plugin-support\libs'

I checked many threads with similar issues at no avail. It's been 2 days now fighting against this issue, and I'm running out of ideas...

Anyone knows what could be happening here? And how to fix the issue?

Thanks.

**Comment by edscodeblenders** [comment]
I resolved this by deleting the file play-games-plugin-support.jar from the "Assets\Plugins\Android" folder. Now my game builds, however after authentication, I can't show the Leaderboards. This was working properly in version 0.9.40, but in version 0.9.41 nothing happens...

Any idea?

**Comment by bigmack11011** [comment]
Same here. No solution so far

**Comment by supersolid-Justy** [comment]
Please go to https://github.com/playgameservices/play-games-plugin-for-unity/issues/1940 to find out how to resolve the leaderboard issue

**Comment by bigmack11011** [comment]
@supersolid-Justy Thanks! Worked for me

**Comment by creatio-ua** [comment]
Hey guys!
I'm having the same issue, but in my case, I don't have a 
play-games-plugin-support.**jar** 
but only the play-games-plugin-support.**aar**
Removing this file leads to the successful build but results in a crashes, where my game attempts to use GPGS authorization. Am I missing something obvious?

P.S. Had no such problems with previous version and Android SDK is updated.

Please help.

**Comment by creatio-ua** [comment]
I've managed to solve the problem by removing the folder with files:
libgpg.so that were accidentally left from the previous version of the plugin.

**Comment by sigono-chao3** [comment]
Had the same issue like @creatio-ua 
But it was included by another plugin which has reference to GPGS

**Comment by claywilkinson** [comment]
Sounds like this is resolved.  Closing.

**Comment by thelucre** [comment]
Solved with `0.9.42` based on @creatio-ua's comment.

`0.9.42` added the folder `/Plugins/Android/gpgs-plugin-support/libs` 

Had to remove the `/Plugins/Android/libs` folder that carried over from `0.9.40`

**Comment by GnRSlash** [comment]
> I've managed to solve the problem by removing the folder with files:
> libgpg.so that were accidentally left from the previous version of the plugin.

PERFECT!
