### ISSUE TITLE
Crash app during authorization

### ISSUE THREAD

**Issue by OnionFan** [playgameservices/play-games-plugin-for-unity#1950]
Hi!
The app crashes when trying to login.

I'm using the 0.9.41 version of the plugin. I use this code to create for initialization Google Play Games:
```
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().RequestEmail().RequestIdToken().RequestServerAuthCode(false).Build ();
PlayGamesPlatform.InitializeInstance(config);
PlayGamesPlatform.DebugLogEnabled = true;
PlayGamesPlatform.Activate();
```

After I try to authorize the player in the following way:
```

PlayGamesLocalUser user =(PlayGamesLocalUser)Social.localUser;

Debug.Log("Start GooglePlayGame login");
// In This moment app is crashes
user.Authenticate((bool isAuth) => {
	if (isAuth)
	{
		_googlePlayLogined = true;
		Debug.LogFormat("GPG authentication success! Name:" +
			user.userName);
		Debug.Log("Server Auth code is:" + PlayGamesPlatform.Instance.GetServerAuthCode());
		/*some code*/
	}
	else
	{
		/*some code*/
	}
}
```

"Soft" log:

> E/Unity   (20206): Unable to find libc
> I/Unity   (20206): Start GooglePlayGame login
> I/Unity   (20206):  
> I/Unity   (20206): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (20206): 
> I/Unity   (20206): Starting Auth with token client.
> I/Unity   (20206):  
> I/Unity   (20206): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (20206): 
> I/Unity   (20206): Authentication type setted: GooglePlayGames
> I/Unity   (20206):  
> I/Unity   (20206): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (20206): 
> W/Unity   (20206): !!! [Play Games Plugin DLL] 10/01/17 19:10:15 +03:00 WARNING: Creating new PlayGamesPlatform
> W/Unity   (20206):  
> W/Unity   (20206): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> W/Unity   (20206): 
> I/Unity   (20206):  [Play Games Plugin DLL] 10/01/17 19:10:15 +03:00 DEBUG: Activating PlayGamesPlatform.
> I/Unity   (20206):  
> I/Unity   (20206): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (20206): 
> I/Unity   (20206):  [Play Games Plugin DLL] 10/01/17 19:10:15 +03:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
> I/Unity   (20206):  
> I/Unity   (20206): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (20206): 
> I/Unity   (20206):  [Play Games Plugin DLL] 10/01/17 19:10:15 +03:00 DEBUG: Creating platform-specific Play Games client.
> I/Unity   (20206):  
> I/Unity   (20206): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (20206): 
> I/Unity   (20206):  [Play Games Plugin DLL] 10/01/17 19:10:15 +03:00 DEBUG: Creating Android IPlayGamesClient Client
> I/Unity   (20206):  
> I/Unity   (20206): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (20206): 
> I/Unity   (20206): ---- [0] -- 12582937
> I/Unity   (20206):  
> I/Unity   (20206): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Detailed log:
> E/Unity   (22207): Unable to find libc
> V/ActivityManager(  630): Broadcast sticky: Intent { act=android.intent.action.SIG_STR flg=0x20000010 (has extras) } ordered=false userid=-1 callerApp=ProcessRecord{2fdfa4df 630:system/1000}
> V/ActivityManager(  630): Broadcast sticky: Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } ordered=false userid=-1 callerApp=ProcessRecord{2fdfa4df 630:system/1000}
> V/ActivityManager(  630): Broadcast: Intent { act=com.google.android.gms.gcm.HEARTBEAT_ALARM flg=0x114 (has extras) } ordered=true userid=0 callerApp=null
> I/Unity   (22207): Start GooglePlayGame login
> I/Unity   (22207):  
> I/Unity   (22207): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (22207): 
> I/Unity   (22207): Starting Auth with token client.
> I/Unity   (22207):  
> I/Unity   (22207): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (22207): 
> I/Unity   (22207): Authentication type setted: GooglePlayGames
> I/Unity   (22207):  
> I/Unity   (22207): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (22207): 
> V/ActivityManager(  630): Broadcast sticky: Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } ordered=false userid=-1 callerApp=ProcessRecord{2fdfa4df 630:system/1000}
> W/Unity   (22207): !!! [Play Games Plugin DLL] 10/01/17 19:33:08 +03:00 WARNING: Creating new PlayGamesPlatform
> W/Unity   (22207):  
> W/Unity   (22207): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> W/Unity   (22207): 
> I/Unity   (22207):  [Play Games Plugin DLL] 10/01/17 19:33:08 +03:00 DEBUG: Activating PlayGamesPlatform.
> I/Unity   (22207):  
> I/Unity   (22207): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (22207): 
> I/Unity   (22207):  [Play Games Plugin DLL] 10/01/17 19:33:08 +03:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
> I/Unity   (22207):  
> I/Unity   (22207): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (22207): 
> I/Unity   (22207):  [Play Games Plugin DLL] 10/01/17 19:33:08 +03:00 DEBUG: Creating platform-specific Play Games client.
> I/Unity   (22207):  
> I/Unity   (22207): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (22207): 
> I/Unity   (22207):  [Play Games Plugin DLL] 10/01/17 19:33:08 +03:00 DEBUG: Creating Android IPlayGamesClient Client
> I/Unity   (22207):  
> I/Unity   (22207): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (22207): 
> I/Unity   (22207): ---- [0] -- 12582937
> I/Unity   (22207):  
> I/Unity   (22207): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> I/Unity   (22207): 
> W/ActivityManager(  630): getRunningAppProcesses: caller 10122 does not hold REAL_GET_TASKS; limiting output
> V/ActivityManager(  630): Broadcast sticky: Intent { act=android.intent.action.BATTERY_CHANGED flg=0x60000010 (has extras) } ordered=false userid=-1 callerApp=null
> W/ActivityManager(  630):   Force finishing activity com.stdforland.hockeybattle/com.unity3d.player.UnityPlayerActivity
> V/ActivityManager(  630): Broadcast: Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } ordered=false userid=0 callerApp=ProcessRecord{2fdfa4df 630:system/1000}
> I/DEBUG   (22330): [OnPurpose Redunant in void preset_info(aed_report_record*, int, int)] pid: 22207, tid: -1361051648, name: UNKNOWN  >>> com.stdforland.hockeybattle <<<
> W/ActivityManager(  630): Activity pause timeout for ActivityRecord{1f201926 u0 com.stdforland.hockeybattle/com.unity3d.player.UnityPlayerActivity t157 f}
> D/ActivityManager(  630): ACT-IDLE_NOW_MSG from windowsVisible() for idle: ActivityRecord{13793609 u0 com.android.launcher3/.Launcher t145}
> V/ActivityManager(  630): Broadcast sticky: Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } ordered=false userid=-1 callerApp=ProcessRecord{2fdfa4df 630:system/1000}

Are there any solutions to this problem?

**Comment by mobeenk** [comment]
get the version 9.33 from branches instead 
I did that because it seems there is no work around this
yet I ran into another issue that it wont connect to google account

**Comment by OnionFan** [comment]
Found the cause and solution of this problem. In the latest version of the plugin (0.9.41) the system does not work correctly with the creation of the file manifest, it simply does not merge with the current manifest files that are present in the project, so it was necessary to register manually.

**Comment by AlecNep** [comment]
Ax x = ~E~x
