### ISSUE TITLE
No additional instructions on completing iOS build.

### ISSUE THREAD

**Issue by jtink** [playgameservices/play-games-plugin-for-unity#1956]
As written in the guide, I built my iOS project in Unity and expected additional instructions but never received any.

> To build and run on iOS, click File > Build Settings, select the iOS platform, then Switch to Platform, then Build. This will export an XCode project and _will display additional instructions on completing the build._

My XCode project was created successfully but I did not see instructions in the Unity Console. Where should I be looking for the additional instructions?

**Comment by claywilkinson** [comment]
Unfortunately, iOS support is deprecated for Play Games Services.
https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html

**Comment by jtink** [comment]
Ok that explains it. Thank you for the link.
