### ISSUE TITLE
Proguard File rules?

### ISSUE THREAD

**Issue by kenglou** [playgameservices/play-games-plugin-for-unity#1963]
Does anyone can provide the content of the proguard-user.txt file they use if they wanted to use the Gradle + Proguard in Unity3d? I'm not sure what I should keep if I'm using proguard-user.txt file in this plugin.

**Comment by qbit86** [comment]
@claywilkinson ?

**Comment by claywilkinson** [comment]
The proguard rules for the play-services aars are included in the aar files.  You can unzip the aar and copy the rules file `proguard.txt`.

**Comment by kenglou** [comment]
Nope it isn't. At the end i put the below as the proguard rules. Hope if it is helps others. If possible please help me put this in the readme to benefit others.

#GameService Rules
-keep class com.google.android.gms.** { *; }
-keep class com.google.games.bridge.** { *; }

# Don't obfuscate. We only need dead code striping.
-dontobfuscate

#GameService Rules
-keep class com.google.android.gms.** { *; }
-keep class com.google.games.bridge.** { *; }

# Don't obfuscate. We only need dead code striping.
-dontobfuscate

# For enumeration classes, see http://proguard.sourceforge.net/manual/examples.html#enumerations
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

**Comment by nnobinelo** [comment]
> The proguard rules for the play-services aars are included in the aar files. You can unzip the aar and copy the rules file `proguard.txt`.

I know this is an old thread, but how would you go about finding these files?

**Comment by nnobinelo** [comment]
> Nope it isn't. At the end i put the below as the proguard rules. Hope if it is helps others. If possible please help me put this in the readme to benefit others.
> 
> ```
> #GameService Rules
> -keep class com.google.android.gms.** { *; }
> -keep class com.google.games.bridge.** { *; }
> 
> #Don't obfuscate. We only need dead code striping.
> -dontobfuscate
> 
> #GameService Rules
> -keep class com.google.android.gms.** { *; }
> -keep class com.google.games.bridge.** { *; }
> 
> #Don't obfuscate. We only need dead code striping.
> -dontobfuscate
> 
> #For enumeration classes, see http://proguard.sourceforge.net/manual/examples.html#enumerations
> -keepclassmembers enum * {
>     public static **[] values();
>     public static ** valueOf(java.lang.String);
> }
> ```

Thank you for these rules, however due to the keep rule for enum classes I encountered some errors with other unity plugins I was using. I adjusted your slightly and found that just these work fine for GPGS. Just in case anyone else it having trouble.

`#GameService Rules
-keep class com.google.android.gms.** { *; }
-keep class com.google.games.bridge.** { *; }

#Don't obfuscate. We only need dead code striping.
-dontobfuscate`

**Comment by studentutu** [comment]
Also, in addition to them : 
-keep class com.google.unity.** { *; }

It uses some of the interfaces in the Admob Plug-in, which is why it is required
