### ISSUE TITLE
Can't show leaderboard

### ISSUE THREAD

**Issue by saywow95** [playgameservices/play-games-plugin-for-unity#1964]
Hi, I have followed this tutorial : https://codelabs.developers.google.com/codelabs/playservices_unity to add your plugin to my game (I have tried several ones before it but none of them worked). I'm able to log in, but not to show the leaderboard, here is the logs I get after I try to open leaderboard : 

> (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-06 20:33:57.547 4629-4647/? I/Unity: [Play Games Plugin DLL] 10/06/17 19:33:57 +00:00 DEBUG: ShowLeaderboardUI with default ID
> 
> (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-06 20:33:57.547 4629-4647/? I/Unity: [Play Games Plugin DLL] 10/06/17 19:33:57 +00:00 DEBUG: ShowLeaderboardUI, lbId= callback is 
> 
> (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-06 20:33:57.547 4629-4647/? I/Unity: [Play Games Plugin DLL] 10/06/17 19:33:57 +00:00 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler
> 
> (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-06 20:33:57.557 4629-4647/? D/NativeBridgeActivity: Launching bridge activity: parent:com.unity3d.player.UnityPlayerActivity@2e0a1b56 intent Intent { act=com.google.android.gms.games.VIEW_LEADERBOARDS dat=version:10260000 flg=0x4000000 pkg=com.google.android.play.games (has extras) }
> 10-06 20:33:57.557 4629-4647/? I/Timeline: Timeline: Activity_launch_request id:mypackageteste.test.test time:13991204
> 10-06 20:33:57.557 1004-1276/? E/PersonaManagerService: inState(): stateMachine is null !!
> 10-06 20:33:57.557 1004-1276/? I/PersonaManagerService: Failed to execute isKioskModeEnabled. java.lang.SecurityException: You need MANAGE_USERS permission to: query user
> 10-06 20:33:57.557 1004-1276/? I/ActivityManager: do not start freezing screen for locked container getKeyguardshowstate = false

(If i retry to open the leaderboard after that, it says that the ui is busy)
Can you help me please?

Thank you

**Comment by supersolid-Justy** [comment]
please seee #1940 for a possible solution :)

**Comment by saywow95** [comment]
I love you, thanks a lot !
