### ISSUE TITLE
Manifest is missing since 0.9.41

### ISSUE THREAD

**Issue by ScreennameTaken** [playgameservices/play-games-plugin-for-unity#1966]
System.IO.DirectoryNotFoundException: Could not find a part of the path "C:\Users\panay\Desktop\Unity Projects\The Adventures Of a RubberBall\Assets\GooglePlayGames\Plugins\Android\GooglePlayGamesManifest.plugin\AndroidManifest.xml".
This is the error i get ever since i updated the plugin from 0.9.40, to 0.9.41.
And i do think that it's important to update the damn plugin because last time i didn't and google had updated stuff on their end, i had issues.

**Comment by supersolid-Justy** [comment]
The AndroidManifest moved from Plugins/Android/MainLibs to the path displayed above. Check if your AndroidManifest is in there.

**Comment by ScreennameTaken** [comment]
Nope. Don't have any of those folders. Guess i'll try to restore the GPGS manifest from a previous backup and manually make the folder it wants and put it there.

**Comment by saiichihashimoto** [comment]
@ScreennameTaken I had the same problem upgrading from 0.9.40 to 0.9.41. I then imported the package for a second time and it went away. It might solve your problem, though there's still definitely a problem with the package so the issue should stay open.

**Comment by ScreennameTaken** [comment]
@saiichihashimoto i ended up removing the package and then importing it a second time, and that solved it.

**Comment by qbit86** [comment]
Why is this closed? The issue still reproduces in 0.9.61. Exception is thrown from `GenerateAndroidManifest()` on attempt to create manifest in `WriteFile()`, because specified parent directory `Assets/GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin/` may be missing.

You should create this directory first (safe to do so if directory already exists):
```csharp
public static void WriteFile(string file, string body)
{
    ...
    DirectoryInfo dir = Directory.GetParent(file);
    dir.Create();
    ...
}
```

Fixed in #2463

**Comment by qbit86** [comment]
Marked as fixed in [CHANGELOG.txt](https://github.com/playgameservices/play-games-plugin-for-unity/blob/0ddc13141d0fca2e671943c81d70db26272d8641/CHANGELOG.txt#L8) for version 0.9.62, but actual `GooglePlayGamesPlugin-0.9.62.unitypackage` doesn't seems to have `GPGSUtil.cs` updated.

**Comment by olehkuznetsov** [comment]
Yes, you are right. I've updated CHANGELOG.txt. Will be in v0.9.63.
