### ISSUE TITLE
How can i download Android Support Library?

### ISSUE THREAD

**Issue by sangh518** [playgameservices/play-games-plugin-for-unity#1968]
Last night, I upgrade android studio to 2.3 version, and I try to redownload android sdk for google play service,
but when I open the android sdk manager, there is no Android Support Library.
How can I download it? Or Couldn't I have to download it?
Please help me...!
![Uploading 캡처.JPG…]()

**Comment by sangh518** [comment]
![default](https://user-images.githubusercontent.com/32636616/31373956-fed1eaf4-add6-11e7-9244-bdcdd8c71187.JPG)

this is the capture image of SDK manager

**Comment by claywilkinson** [comment]
See https://developer.android.com/topic/libraries/support-library/setup.html - The support library is available via maven repository.  This should be handled using the latest [Unity Jar Resolver](https://github.com/googlesamples/unity-jar-resolver) which is also part of the latest plugin.
