### ISSUE TITLE
play game services 0.9.41 doesn't allow separate x86 and ARMv7 builds anymore because both libraries are included in the .aar file

### ISSUE THREAD

**Issue by cataHHH** [playgameservices/play-games-plugin-for-unity#1971]
If you try to make separate apks now for x86 and ARMv7, google play will see either one as supporting both CPU architectures, because unity can't separate them anymore when you select target CPU.
Honestly last update messed up everything, anyone know where I can find previous updates e.g 0.9.39 ?

**Comment by claywilkinson** [comment]
You can get the previous versions by selecting a release  on the [Releases](https://github.com/playgameservices/play-games-plugin-for-unity/releases) link.

To make sure I understand your goal:
You are trying to do 2 separate builds from Unity.  The first one is setting the device filter to ARMv7 and then build again changing the filter to x86?

This is causing a problem because the .aar file contains both native libraries which are being included regardless of the device filter?

**Comment by cataHHH** [comment]
@claywilkinson Yes that is the issue. Google play sees an apk as supporting both cpu architectures if it includes a single library for either one, as the libraries are now included in the .aar unity can't separate them anymore.
To test you can try to create an app in the play console, upload an apk which includes the play services and choose unity to target either x86 or ARMv7, if you click info it will show you it supports both, it won't even allow you to upload 2 apks (one which you select in unity to target x86 and another to target ARMv7), because it sees them as identical although unity includes the correct libs.

**Comment by stewartmiles** [comment]
@claywilkinson if you moved the AAR into a maven repo the Android Resolver will process it for you stripping the ABIs that aren't required by the developer's project.

**Comment by cataHHH** [comment]
@stewartmiles then you would need to run the resolver each time you change the target ? (maybe better as was before)

**Comment by stewartmiles** [comment]
@cataHHH nope, we monitor the target architecture, when it changes auto-resolution is triggered.  I guess if you're running a continuous build then you'll need to disable auto resolution and run force resolution using the Android Resolver's C# API.

**Comment by claywilkinson** [comment]
The library has been moved to a local repository as @stewartmiles  suggested in 0.9.42.

**Comment by Praveen2106** [comment]
@claywilkinson Is this fix available in 0.9.42? The final APK still includes both the ABIs. This makes the Device Filter option useless in Unity.

**Comment by chrisclark99** [comment]
@cataHHH worked for me thanks

**Comment by cataHHH** [comment]
0.9.42 works ok

**Comment by chrisclark99** [comment]
Yes I have that version but it did not work until I clicked force resolve

**Comment by phonggenix** [comment]
I'm using Play Games Service v0.9.50 and see that it doesn't work. Device filter is ARMv7 but the final APK has both architecture.

(I'm using Unity 2017.4.4f1)
