### ISSUE TITLE
GamesNativeSDK - Can't register class com/google/android/gms...

### ISSUE THREAD

**Issue by ErikJungnickel** [playgameservices/play-games-plugin-for-unity#1972]
Hi, 
I am using the current build of the plugin (0.9.4.1) and I am pretty sure that I installed all needed libs through the android sdk manager. They also got the newest versions since I installed them 2 days ago just for this plugin.

But I can't get around the "Can't register class" errors.

Screenshot from SDK Manager
![image](https://user-images.githubusercontent.com/18282958/31408457-ee3e47aa-ae08-11e7-8ab2-bf028a8454bd.png)

Screenshot from /Plugins/Android

![image](https://user-images.githubusercontent.com/18282958/31408480-07af18f4-ae09-11e7-9619-920715f9d75f.png)

I had to manually set the com.google.android.gms.version in the android manifest to get around some other error.

![image](https://user-images.githubusercontent.com/18282958/31408514-27ab49f2-ae09-11e7-97c5-3f828d63bf45.png)

Any ideas? I'm struggling with this for 3 or 4 days now.

Full error log:

10-10 22:03:17.697: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/common/ConnectionResult: an exception occurred.
10-10 22:03:17.697: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/common/GooglePlayServicesUtil: an exception occurred.
10-10 22:03:17.698: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/common/api/Api: an exception occurred.
10-10 22:03:17.698: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/common/api/Api$ApiOptions: an exception occurred.
10-10 22:03:17.698: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/common/api/Api$ApiOptions$HasOptions: an exception occurred.
10-10 22:03:17.698: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/common/api/GoogleApiClient: an exception occurred.
10-10 22:03:17.699: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/common/api/GoogleApiClient$Builder: an exception occurred.
10-10 22:03:17.699: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/common/api/PendingResult: an exception occurred.
10-10 22:03:17.699: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/common/api/Result: an exception occurred.
10-10 22:03:17.699: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/common/api/ResultCallback: an exception occurred.
10-10 22:03:17.700: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/common/data/DataBufferUtils: an exception occurred.
10-10 22:03:17.700: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/Games: an exception occurred.
10-10 22:03:17.700: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/Games$GamesOptions: an exception occurred.
10-10 22:03:17.701: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/Games$GamesOptions$Builder: an exception occurred.
10-10 22:03:17.701: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/Player: an exception occurred.
10-10 22:03:17.701: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/PlayerBuffer: an exception occurred.
10-10 22:03:17.701: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/PlayerLevel: an exception occurred.
10-10 22:03:17.702: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/PlayerLevelInfo: an exception occurred.
10-10 22:03:17.702: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/Players: an exception occurred.
10-10 22:03:17.702: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/Players$LoadPlayersResult: an exception occurred.
10-10 22:03:17.702: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/achievement/Achievement: an exception occurred.
10-10 22:03:17.703: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/achievement/Achievements$LoadAchievementsResult: an exception occurred.
10-10 22:03:17.703: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/event/Event: an exception occurred.
10-10 22:03:17.703: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/event/EventBuffer: an exception occurred.
10-10 22:03:17.703: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/event/Events: an exception occurred.
10-10 22:03:17.704: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/event/Events$LoadEventsResult: an exception occurred.
10-10 22:03:17.704: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/achievement/AchievementBuffer: an exception occurred.
10-10 22:03:17.704: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/achievement/Achievements: an exception occurred.
10-10 22:03:17.705: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/leaderboard/Leaderboard: an exception occurred.
10-10 22:03:17.705: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/leaderboard/LeaderboardBuffer: an exception occurred.
10-10 22:03:17.705: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/leaderboard/Leaderboards: an exception occurred.
10-10 22:03:17.705: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/leaderboard/LeaderboardScore: an exception occurred.
10-10 22:03:17.706: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/leaderboard/LeaderboardScoreBuffer: an exception occurred.
10-10 22:03:17.706: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/leaderboard/LeaderboardVariant: an exception occurred.
10-10 22:03:17.706: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/leaderboard/Leaderboards$LeaderboardMetadataResult: an exception occurred.
10-10 22:03:17.706: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/leaderboard/Leaderboards$LoadScoresResult: an exception occurred.
10-10 22:03:17.707: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/Invitation: an exception occurred.
10-10 22:03:17.707: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/InvitationBuffer: an exception occurred.
10-10 22:03:17.707: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/Invitations: an exception occurred.
10-10 22:03:17.707: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/Invitations$LoadInvitationsResult: an exception occurred.
10-10 22:03:17.708: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/Multiplayer: an exception occurred.
10-10 22:03:17.708: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/Participant: an exception occurred.
10-10 22:03:17.708: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/ParticipantResult: an exception occurred.
10-10 22:03:17.708: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/turnbased/LoadMatchesResponse: an exception occurred.
10-10 22:03:17.709: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatch: an exception occurred.
10-10 22:03:17.709: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchBuffer: an exception occurred.
10-10 22:03:17.709: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchConfig: an exception occurred.
10-10 22:03:17.710: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchConfig$Builder: an exception occurred.
10-10 22:03:17.710: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer: an exception occurred.
10-10 22:03:17.710: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$CancelMatchResult: an exception occurred.
10-10 22:03:17.710: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$InitiateMatchResult: an exception occurred.
10-10 22:03:17.711: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LeaveMatchResult: an exception occurred.
10-10 22:03:17.711: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LoadMatchesResult: an exception occurred.
10-10 22:03:17.711: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LoadMatchResult: an exception occurred.
10-10 22:03:17.711: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$UpdateMatchResult: an exception occurred.
10-10 22:03:17.712: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/quest/Quest: an exception occurred.
10-10 22:03:17.712: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/quest/QuestBuffer: an exception occurred.
10-10 22:03:17.712: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/quest/Quests: an exception occurred.
10-10 22:03:17.712: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/quest/Milestone: an exception occurred.
10-10 22:03:17.713: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/quest/Quests$LoadQuestsResult: an exception occurred.
10-10 22:03:17.713: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/quest/Quests$AcceptQuestResult: an exception occurred.
10-10 22:03:17.713: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/quest/Quests$ClaimMilestoneResult: an exception occurred.
10-10 22:03:17.714: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/snapshot/Snapshot: an exception occurred.
10-10 22:03:17.714: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/snapshot/SnapshotContents: an exception occurred.
10-10 22:03:17.714: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadata: an exception occurred.
10-10 22:03:17.714: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataBuffer: an exception occurred.
10-10 22:03:17.715: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/snapshot/Snapshots: an exception occurred.
10-10 22:03:17.715: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/snapshot/Snapshots$CommitSnapshotResult: an exception occurred.
10-10 22:03:17.715: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/snapshot/Snapshots$LoadSnapshotsResult: an exception occurred.
10-10 22:03:17.715: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/snapshot/Snapshots$OpenSnapshotResult: an exception occurred.
10-10 22:03:17.716: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataChange: an exception occurred.
10-10 22:03:17.716: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataChange$Builder: an exception occurred.
10-10 22:03:17.716: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/stats/PlayerStats: an exception occurred.
10-10 22:03:17.716: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/stats/Stats: an exception occurred.
10-10 22:03:17.717: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/stats/Stats$LoadPlayerStatsResult: an exception occurred.
10-10 22:03:17.717: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMessageReceivedListener: an exception occurred.
10-10 22:03:17.717: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMultiplayer: an exception occurred.
10-10 22:03:17.717: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMessage: an exception occurred.
10-10 22:03:17.718: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/realtime/Room: an exception occurred.
10-10 22:03:17.718: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/realtime/RoomConfig: an exception occurred.
10-10 22:03:17.718: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/multiplayer/realtime/RoomConfig$Builder: an exception occurred.
10-10 22:03:17.718: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/nearby/Nearby: an exception occurred.
10-10 22:03:17.719: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/nearby/connection/AppIdentifier: an exception occurred.
10-10 22:03:17.719: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/nearby/connection/AppMetadata: an exception occurred.
10-10 22:03:17.719: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/nearby/connection/Connections: an exception occurred.
10-10 22:03:17.719: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/nearby/connection/Connections$StartAdvertisingResult: an exception occurred.
10-10 22:03:17.720: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/video/CaptureState: an exception occurred.
10-10 22:03:17.720: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/video/VideoCapabilities: an exception occurred.
10-10 22:03:17.720: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/video/Videos: an exception occurred.
10-10 22:03:17.720: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/video/Videos$CaptureAvailableResult: an exception occurred.
10-10 22:03:17.721: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/video/Videos$CaptureCapabilitiesResult: an exception occurred.
10-10 22:03:17.721: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/video/Videos$CaptureStateResult: an exception occurred.
10-10 22:03:17.721: E/GamesNativeSDK(30446): Can't register class com/google/android/gms/games/video/Videos$CaptureOverlayStateListener: an exception occurred.
10-10 22:03:17.754: E/GamesNativeSDK(30446): Could not register one or more required Java classes.

**Comment by claywilkinson** [comment]
It looks like some class is not being included in the build.  A couple questions:
1. Are you building with Gradle from the Editor?  Can you try to use the Internal build system?  If the internal system works, then it is an issue with getting the dependencies into gradle.
2. You can delete the `com.google.android.gms.version` metadata line from manifest if it is causing problems (This usually happens when you are building with Gradle and the lib dependencies are not set correctly).
3. Can you share an unfiltered log?  There is usually more information from other categories when the classes can't be registered that have a more precise exception.

**Comment by ErikJungnickel** [comment]
Since today the error message I see changed for some reason (both for internal and gradle). This is what I am getting now:

10-12 20:49:33.131: I/Unity(28649): DllNotFoundException: gpg
10-12 20:49:33.131: I/Unity(28649):   at (wrapper managed-to-native) GooglePlayGames.Native.Cwrapper.Builder:GameServices_Builder_Construct ()
10-12 20:49:33.131: I/Unity(28649):   at GooglePlayGames.Native.PInvoke.GameServicesBuilder.Create () [0x00000] in <filename unknown>:0 
10-12 20:49:33.131: I/Unity(28649):   at GooglePlayGames.Native.NativeClient.InitializeGameServices () [0x00000] in <filename unknown>:0 
10-12 20:49:33.131: I/Unity(28649):   at GooglePlayGames.Native.NativeClient.Authenticate (System.Action`2 callback, Boolean silent) [0x00000] in <filename unknown>:0 
10-12 20:49:33.131: I/Unity(28649):   at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`2 callback, Boolean silent) [0x00000] in <filename unknown>:0 
10-12 20:49:33.131: I/Unity(28649):   at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`2 callback) [0x00000] in <filename unknown>:0 
10-12 20:49:33.131: I/Unity(28649):   at GooglePlayGames.PlayGamesLocalUser.Authenticate (System.Action`2 callback) [0x00000] in <filename unknown>:0 
10-12 20:49:33.131: I/Unity(28649):   at MainMenu.Auth () [0x00000] in <filename unknown>:0 
10-12 20:49:33.131: I/Unity(28649):   at UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) [0x00000] in <filename unknown>:0 
10-12 20:49:33.131: I/Unity(28649):   at UnityEngine.Events.InvokableCal
10-12 20:49:33.132: I/Unity(28649):  [Play Games Plugin DLL] 10/12/17 20:49:33 +02:00 DEBUG: Activating PlayGamesPlatform.
10-12 20:49:33.132: I/Unity(28649):  
10-12 20:49:33.132: I/Unity(28649): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
10-12 20:49:33.132: I/Unity(28649):  [Play Games Plugin DLL] 10/12/17 20:49:33 +02:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
10-12 20:49:33.132: I/Unity(28649):  
10-12 20:49:33.132: I/Unity(28649): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by ErikJungnickel** [comment]
Using the internal build works. I can authenticate now. 

I am somewhat shocked that I didnt try this myself.

Thank you very much!

**Comment by claywilkinson** [comment]
Thanks for the response - I'll try to spend some time to make the gradle build process less painful :)

**Comment by VanoPetrov** [comment]
I have this problem
build with gradle - internal build dont work (dex - 64K reference limit)
my log:

12-12 13:17:36.936 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/common/api/GoogleApiClient: an excepti
on occurred.
12-12 13:17:36.936 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/common/api/GoogleApiClient$Builder: an
 exception occurred.
12-12 13:17:36.936 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/common/api/PendingResult: an exception
 occurred.
12-12 13:17:36.936 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/common/api/Result: an exception occurr
ed.
12-12 13:17:36.937 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/common/api/ResultCallback: an exceptio
n occurred.
12-12 13:17:36.937 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/common/data/DataBufferUtils: an except
ion occurred.
12-12 13:17:36.937 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/Games: an exception occurred.
12-12 13:17:36.938 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/Games$GamesOptions: an exception
 occurred.
12-12 13:17:36.938 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/Games$GamesOptions$Builder: an e
xception occurred.
12-12 13:17:36.938 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/Games$GetServerAuthCodeResult: a
n exception occurred.
12-12 13:17:36.938 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/Player: an exception occurred.
12-12 13:17:36.938 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/PlayerBuffer: an exception occur
red.
12-12 13:17:36.938 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/PlayerLevel: an exception occurr
ed.
12-12 13:17:36.939 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/PlayerLevelInfo: an exception oc
curred.
12-12 13:17:36.939 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/Players: an exception occurred.
12-12 13:17:36.939 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/Players$LoadPlayersResult: an ex
ception occurred.
12-12 13:17:36.939 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/achievement/Achievement: an exce
ption occurred.
12-12 13:17:36.939 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/achievement/Achievements$LoadAch
ievementsResult: an exception occurred.
12-12 13:17:36.939 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/event/Event: an exception occurr
ed.
12-12 13:17:36.940 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/event/EventBuffer: an exception 
occurred.
12-12 13:17:36.940 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/event/Events: an exception occur
red.
12-12 13:17:36.940 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/event/Events$LoadEventsResult: a
n exception occurred.
12-12 13:17:36.940 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/achievement/AchievementBuffer: a
n exception occurred.
12-12 13:17:36.940 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/achievement/Achievements: an exc
eption occurred.
12-12 13:17:36.940 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/Leaderboard: an exce
ption occurred.
12-12 13:17:36.941 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/LeaderboardBuffer: a
n exception occurred.
12-12 13:17:36.941 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/Leaderboards: an exc
eption occurred.
12-12 13:17:36.941 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/LeaderboardScore: an
 exception occurred.
12-12 13:17:36.941 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/LeaderboardScoreBuff
er: an exception occurred.
12-12 13:17:36.941 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/LeaderboardVariant: 
an exception occurred.
12-12 13:17:36.941 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/Leaderboards$Leaderb
oardMetadataResult: an exception occurred.
12-12 13:17:36.942 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/Leaderboards$LoadSco
resResult: an exception occurred.
12-12 13:17:36.942 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Invitation: an excep
tion occurred.
12-12 13:17:36.942 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/InvitationBuffer: an
 exception occurred.
12-12 13:17:36.942 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Invitations: an exce
ption occurred.
12-12 13:17:36.942 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Invitations$LoadInvi
tationsResult: an exception occurred.
12-12 13:17:36.942 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Multiplayer: an exce
ption occurred.
12-12 13:17:36.943 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Participant: an exce
ption occurred.
12-12 13:17:36.943 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/ParticipantResult: a
n exception occurred.
12-12 13:17:36.943 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/LoadMatche
sResponse: an exception occurred.
12-12 13:17:36.943 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedM
atch: an exception occurred.
12-12 13:17:36.943 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedM
atchBuffer: an exception occurred.
12-12 13:17:36.943 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedM
atchConfig: an exception occurred.
12-12 13:17:36.944 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedM
atchConfig$Builder: an exception occurred.
12-12 13:17:36.944 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedM
ultiplayer: an exception occurred.
12-12 13:17:36.944 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedM
ultiplayer$CancelMatchResult: an exception occurred.
12-12 13:17:36.944 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedM
ultiplayer$InitiateMatchResult: an exception occurred.
12-12 13:17:36.944 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedM
ultiplayer$LeaveMatchResult: an exception occurred.
12-12 13:17:36.944 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedM
ultiplayer$LoadMatchesResult: an exception occurred.
12-12 13:17:36.944 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedM
ultiplayer$LoadMatchResult: an exception occurred.
12-12 13:17:36.945 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedM
ultiplayer$UpdateMatchResult: an exception occurred.
12-12 13:17:36.945 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quest: an exception occurr
ed.
12-12 13:17:36.945 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/QuestBuffer: an exception 
occurred.
12-12 13:17:36.945 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quests: an exception occur
red.
12-12 13:17:36.945 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Milestone: an exception oc
curred.
12-12 13:17:36.945 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quests$LoadQuestsResult: a
n exception occurred.
12-12 13:17:36.946 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quests$AcceptQuestResult: 
an exception occurred.
12-12 13:17:36.946 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quests$ClaimMilestoneResul
t: an exception occurred.
12-12 13:17:36.946 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/Snapshot: an exception 
occurred.
12-12 13:17:36.946 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/SnapshotContents: an ex
ception occurred.
12-12 13:17:36.946 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/SnapshotMetadata: an ex
ception occurred.
12-12 13:17:36.946 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataBuffer:
 an exception occurred.
12-12 13:17:36.946 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/Snapshots: an exception
 occurred.
12-12 13:17:36.947 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/Snapshots$CommitSnapsho
tResult: an exception occurred.
12-12 13:17:36.947 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/Snapshots$LoadSnapshots
Result: an exception occurred.
12-12 13:17:36.947 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/Snapshots$OpenSnapshotR
esult: an exception occurred.
12-12 13:17:36.947 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataChange:
 an exception occurred.
12-12 13:17:36.947 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataChange$
Builder: an exception occurred.
12-12 13:17:36.947 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/stats/PlayerStats: an exception 
occurred.
12-12 13:17:36.948 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/stats/Stats: an exception occurr
ed.
12-12 13:17:36.948 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/stats/Stats$LoadPlayerStatsResul
t: an exception occurred.
12-12 13:17:36.948 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMes
sageReceivedListener: an exception occurred.
12-12 13:17:36.948 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMul
tiplayer: an exception occurred.
12-12 13:17:36.948 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMes
sage: an exception occurred.
12-12 13:17:36.948 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/Room: an ex
ception occurred.
12-12 13:17:36.948 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RoomConfig:
 an exception occurred.
12-12 13:17:36.949 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RoomConfig$
Builder: an exception occurred.
12-12 13:17:36.949 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/nearby/Nearby: an exception occurred.
12-12 13:17:36.949 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/nearby/connection/AppIdentifier: an ex
ception occurred.
12-12 13:17:36.949 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/nearby/connection/AppMetadata: an exce
ption occurred.
12-12 13:17:36.949 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/nearby/connection/Connections: an exce
ption occurred.
12-12 13:17:36.949 21967 21988 E GamesNativeSDK: Can't register class com/google/android/gms/nearby/connection/Connections$StartAdv
ertisingResult: an exception occurred.
12-12 13:17:37.023 21967 21988 I Unity   : Building GPG services, implicitly attempts silent auth
12-12 13:17:37.023 21967 21988 I Unity   :  
12-12 13:17:37.023 21967 21988 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
12-12 13:17:37.023 21967 21988 I Unity   : 
12-12 13:17:37.025 21967 21988 E GamesNativeSDK: Could not register one or more required Java classes.
12-12 13:17:37.069 21988 21988 W main    : type=1400 audit(0.0:692): avc: denied { read } for name="cpuinfo_max_freq" dev="sysfs" i
no=33674 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
12-12 13:17:37.069 21988 21988 W main    : type=1400 audit(0.0:693): avc: denied { read } for name="cpuinfo_max_freq" dev="sysfs" i
no=33674 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0

**Comment by Rdqrdqq** [comment]
@VanoPetrov same problem, did you solve it?

**Comment by KOSSOKO** [comment]
@Rdqrdqq did you solve it ?
