### ISSUE TITLE
Leaderboard not showing up and AndroidManifest doesn't merge properly

### ISSUE THREAD

**Issue by robbitara** [playgameservices/play-games-plugin-for-unity#1973]
As I already wrote in another issues here, the LeaderBoard aren't showing up.
I tried to modify the AndroidManifest.xml file placed in Assets/GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin

```
<?xml version="1.0" encoding="utf-8"?>
<!-- This file was automatically generated by the Google Play Games plugin for Unity
     Do not edit. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.google.example.games.mainlibproj"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk android:minSdkVersion="8" android:targetSdkVersion="16" />

    <application>
     <!-- Required for Nearby Connections API -->
        <meta-data android:name="com.google.android.gms.nearby.connection.SERVICE_ID"
            android:value="" />

        <!-- The space in these forces it to be interpreted as a string vs. int -->
        <meta-data android:name="com.google.android.gms.games.APP_ID"
            android:value="\ 24875721256" />

        <!-- Keep track of which plugin is being used -->
        <meta-data android:name="com.google.android.gms.games.unityVersion"
            android:value="\ 0.9.41" />

        <!-- Build time check to make sure play-services libraries are present -->
        <meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
			
	<activity
                android:name="com.google.games.bridge.NativeBridgeActivity"
		android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
    </application>
</manifest>
```
But in the final AndroidManifest.xml the last activity of the previous manifest changes to this:

```
<activity
    android:theme="@ref/0x01030011"
    android:name="com.google.games.bridge.NativeBridgeActivity" />
```

It seems that manifests are not merging as expected.

**Comment by saywow95** [comment]
Are you able to show the leaderboard after posting a score to it? because I can't :/

**Comment by sunderam1996** [comment]
Today I uploaded my game.

I have checked that these keys are same =

- In the keystore used with my game (SHA-1 obtained from keytool.exe)
- In Google Play Developer Console (the SHA-1 obtained from "Upload certificate")
- In the API Manager (https://console.developers.google.com - Credentials)

And, "Sign-In" is not working properly.

**Comment by xenonsin** [comment]
@robbitara what is step 3 for?

**Comment by sunderam1996** [comment]
I suppose we have copy and paste SHA-1 fingerprint to the Google API Console.
But, now the issue is solved.
Sign-In and Leaderboard is appearing properly in my published game.
Thanks 👍
