### ISSUE TITLE
iOS build problem

### ISSUE THREAD

**Issue by blackwitch** [playgameservices/play-games-plugin-for-unity#1975]
I have Unity 2017.1.2f1 and Xcode 9.0 and 0.9.41 plugin.

Before linked this plugin, there was no problem. But after linked this plugin, I got a  build error as below.

-----------------------------------------------------------------------------------------------
ld: '/Users/myproject/build_ios/Pods/GoogleAuthUtilities/Libraries/libGTMOAuth2_external.a(GTMOAuth2Authentication.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/myproject/build_ios/Pods/GoogleAuthUtilities/Libraries/libGTMOAuth2_external.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
-----------------------------------------------------------------------------------------------

The building option "Bitcode" is "Yes" now. 

Before I google about this problem and I found this(https://github.com/playgameservices/play-games-plugin-for-unity/issues/1040)

But it didn't work for me.

Could you let me know how I solve this problem?

**Comment by jonnyn** [comment]
I got the same issue and this works for me.
change this Unity-iPhone >> Build Settings >> Enable Bitcode == "No"

**Comment by claywilkinson** [comment]
Just a reminder that iOS support for this plugin is going away soon: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
