### ISSUE TITLE
ERROR_NOT_AUTHORIZED if EnableSavedGames is used

### ISSUE THREAD

**Issue by Hondune** [playgameservices/play-games-plugin-for-unity#1978]
I have been banging my head against a wall for over a week now because of this. I can not log in if i have saved games enabled, everything works perfectly if i remove it. Extremely frustrating considering thats the only reason i would like to implement google play in the first place. My sha-1 keys are all correct (i'm using google app signing and testing by uploading to beta, as such im using the app signing sha-1 shown in the play console, i have downloaded the apk after uploading and verified with the keytool that the sha-1 is correct in all locations), my linked apps and auth credentials are all correct(ive tried deleting the entire play services entry and making a new one, deleting and relinking the app multiple times, ect), i have several accounts properly set up in the testers area and non of them make a difference. I have tried everything i can find online, i have tried every version of the plugin i could get working, i have tried every version of play games jars/aars all the way back to 10.0.1. All of my sdks and tools are completely up to date using android studio (i even went as far as to completely delete all of them and re download everything). I have tried updating unity, building using gradle as well as the standard internal build system.Ive made sure the final generated AndroidManifest has all the correct information, app id, package name, ect. Nothing changes, ERROR_NOT_AUTHORIZED every time. Unless i remove saved games, and then it logs in just fine every time. The log produces absolutely nothing useful, no missing dlls or jars or anything like ive seen other people have, no errors or issues during setup. I am not using any other plugins other than the unity in app purchases plugin. Play games services get created succesfully, and like i said if i remove EnablSavedGames from the builder i can sign in without any issues. After the standard play games creation and activation messages(all successful, and the same as when log in works when i remove saved games), this all i get in the log

DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
DEBUG: Invoking callbacks, AuthState changed from silentPending to Unauthenticated
DEBUG: there are pending auth callbakcs - starting AuthUI
DEBUG: AuthState == Unauthenticated calling auth callbacks with failure
sign in failed...

I have never had anything just blatantly not work like this before no matter how many things i change or fix or work on. Its been over a week, im starting to go slightly mad. Hoping someone has some sort of input on this issue...

**Comment by Hondune** [comment]
So I FINALLY figured this out, and it had absolutely nothing to do with the plugin, my setup, or the google play console after all. All i had to do, was simply clear all data from the play services app on my phone and like magic everything started working like it should. I have no idea why, i have no idea how that should even be related seeing as this app didnt have any play services or plugins before starting this, i dont know why that would cause only saved games to break and nothing else but... well there you go.

**Comment by ocarre** [comment]
Thank you so much for your answer, i just spend half a week on this issue and not more thanks to you !
I think the problem was caused by a change in my app signature that caused an issue in the google play service to fetch some data required for authentication. Clearing these data make it works again, thanks again :)
