### ISSUE TITLE
Why DummyClient Don't logging in editor ?

### ISSUE THREAD

**Issue by martasp** [playgameservices/play-games-plugin-for-unity#1979]
In android phone  everything is a success but then trying in the editor authentification returns false and  I don't get any dummy debug logs. With dummy logs, it's easier to debug without compiling in phone 

    void Start()
    {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();

        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.DebugLogEnabled = true;
        PlayGamesPlatform.Activate();
        Debug.Log("start");

        Login();
    }

**Comment by claywilkinson** [comment]
This plugin only works in on a device.  It requires Google client libraries only found on Android (and iOS for a little longer).
