### ISSUE TITLE
Moving Failed when exporting to Android Device

### ISSUE THREAD

**Issue by emilmirzaian** [playgameservices/play-games-plugin-for-unity#1981]
Moving Temp/StagingArea/android-libraries/play-services-ads-license-11.4.2/classes.jar to Temp/StagingArea/android-libraries/play-services-ads-license-11.4.2/libs/classes.jar: No such file or directory

I'm currently trying to port from iOS to android, i installed play game services plugin and getting this strange error upon build. Any tips? the android-libraries folder within temp currently has 2 "play-services-ads_license-11.4.2" folders with different contents. Any Advice?

**Comment by kujo87** [comment]
Did you close this because you found a fix, or a newer version of the SDK fixed it?

**Comment by emilmirzaian** [comment]
kujo87 I think i just downloaded earlier android sdks. It was a version issue iirc.
