### ISSUE TITLE
No Leaderboard UI once the app is published on Play Store (UPDATED AND FIXED)

### ISSUE THREAD

**Issue by robbitara** [playgameservices/play-games-plugin-for-unity#1985]
Hi everyone. 
As the title say, the leaderboard are not showing now that my app is on the Play Store.
The exact same apk on my hard drive works perfectly. Once I upload it to the Play Store, it doesn't show up anything anymore.
I downloaded everything from the SDK Manager on Android Studio.

![image](https://user-images.githubusercontent.com/19875982/31744396-e3677bf6-b45e-11e7-94f9-6e1c779625c5.png)

![image](https://user-images.githubusercontent.com/19875982/31744449-18802040-b45f-11e7-87f1-e1844b74b403.png)

I added the 2 famous lines of code to the AndroidManifest, but nothing happens.
Can someone tell me why Unity natively integrate GameCenter for iOS but doesn't support GPS at all?
I think that this is an absurd situation.

# UPDATE
## How I finally published my app with working Leaderboard

After 2 days of struggling, I finally managed to publish the app on the Play Store and now everything is working fine.
The only things you have to do are:

Read this issue I opened days ago --> #1973 

### Modify your AndroidManifest.xml
Add the two lines of code in the AndroidManifest.xml placed in Assets/GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin:

`<activity android:name="com.google.games.bridge.NativeBridgeActivity"
           android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />`

### Update your SDK
Yes, update everything you find in the SDK Manager Tool, just as I did in the images I posted before.

### Correctly sign your application
This is a **CRUCIAL** step in the process, because if Google can't prove your identity through the sign certificate of your app, GPS won't work.
I'm not an expert when it comes to signatures and certificates, so I decided to do not enroll the "Google Play App Signing" service and to sign the app on my own.
So, once you decided to publish, sign the app with your keystore and then export the SHA-1 relative to your certificate. You can do that with this line of code on a terminal:

`keytool.exe -exportcert -keystore path-to-your-keystore -list -v`

After you enter the password, it will show the SHA-1 code. Copy it, because this is the SHA-1 you have to enter in the Developer Console when you create a "Linked Application".

***Do not lose the password of your keystore, otherwise you won't be able to build your app anymore. Once you put the SHA-1 in the Linked Application section, GPS will search for requests coming from an app with the SAME SHA-1 certificate. Building an app with a different keystore would mean to create a new project in the Developer Console.***

Unless you're completely sure about what you're doing, remember to  **DO NOT ENROLL** the "Google Play App Signing" service. Signin your app just with your keystore keeps things easier.

That's all. I suggest you to put your app in a Beta stage before publishing it. If your app works on Beta, you're ready to go. Obviously, remember to publish the Play Services linked to your app in Developer Console.

This is my app, in case you want to verify with your eyes that this method works.
https://play.google.com/store/apps/details?id=com.tavernminds.apong

I wish this will work for you.

**Comment by claywilkinson** [comment]
This has been fixed in 0.9.42
