### ISSUE TITLE
IOS Build Fails

### ISSUE THREAD

**Issue by avasilivich** [playgameservices/play-games-plugin-for-unity#1990]
Hello,
I use unity 5.6.2 and 0.9.41 plugin. IOS build fails and give some bunch of video manager related errors.
What can I do to resolve this issue.
![gh](https://user-images.githubusercontent.com/22602516/31862672-58dbf180-b74a-11e7-9161-444fcf623da8.jpg)

**Comment by claywilkinson** [comment]
Unfortunately, iOS support for this plugin is deprecated and should not be used: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
