### ISSUE TITLE
Where i can find the 0.9.38a version?

### ISSUE THREAD

**Issue by lMasc** [playgameservices/play-games-plugin-for-unity#1991]
As the title said, i need the version 0.9.38a , but i cant find it in the "old builds" folder of the plugin.

Thanks in advance.

**Comment by avasilivich** [comment]
You can checkout to version 0.9.38a commit

**Comment by Gerald123** [comment]
https://github.com/playgameservices/play-games-plugin-for-unity/tree/v0.9.38a
