### ISSUE TITLE
AndroidTokenClient.cs(333,23): warning CS0114

### ISSUE THREAD

**Issue by xolittlebunny** [playgameservices/play-games-plugin-for-unity#1999]
Assets/GooglePlayGames/Platforms/Android/AndroidTokenClient.cs(333,23): warning CS0114: `GooglePlayGames.Android.TokenResultCallback.toString()' hides inherited member `UnityEngine.AndroidJavaProxy.toString()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword

HELP, i'm new here :c

**Comment by claywilkinson** [comment]
Hi @xolittlebunny - Welcome!  This is a warning about a method in the generated C# code.  It is a little annoying, but harmless.  If you are having a specific problem, I'd suggest searching the closed issues for your problem first.  If you can't find a solution,  please create a new issue and describe your problem and including a log usually helps in asking for help.
