### ISSUE TITLE
Why getToken, getAvatar and getEmailAddress methods are not exposed?

### ISSUE THREAD

**Issue by ImranZahid** [playgameservices/play-games-plugin-for-unity#200]
I was looking for getToken required to implement signin+ api, I can see method inside java lib but why not its exposed to AndroidClient? same for Image and email address! I tried to implement my own function that could return token and other fields to c# code but unfortunately its hanging, not sure whats the problem. Could you add these methods in upcoming release? it would be very beneficial.

**Comment by JohnTube** [comment]
Is there any chance this will be implemented ? I can't find a good cross platform workaround to implement a Google+ sign-in with Unity.

**Comment by claywilkinson** [comment]
It has been logged as an enhancement (so thanks for your +1!).  There is a good discussion going on in thread #10 , which has an approach, (I have not looked at it in terms of being cross platform).

**Comment by claywilkinson** [comment]
These are all implemented now.
