### ISSUE TITLE
App crash on Google Play Games login

### ISSUE THREAD

**Issue by lightray1** [playgameservices/play-games-plugin-for-unity#2000]
I've made a new Unity project, imported GooglePlayGamesPlugin-0.9.41.unitypackage and play-services-resolver-1.2.59.0.unitypackage, then I've made a forced resolution. 
I've also created and configured the Google Play Games project, and the resources in Unity (Google Play Games -> Setup -> Android setup).
Now, when I compile the project with internal compiler, the compilation is successful but the app crashes on GPG login.
Instead, if i try to build with Gradle, the compilation fails with this error:

`[project path]\Temp\gradleOut\GooglePlayGamesManifest.plugin\build\intermediates\bundles\release\aapt\AndroidManifest.xml:35:28-65: AAPT: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').`

If I remove this block from manifest.xml the result is the same as for the internal compilation (compilation ok, app crash on GPG login).

I'm using Unity 2017.1.1f1, with the updated Android SDK.

Thank you in advance for your time.

**Comment by claywilkinson** [comment]
google_play_services_version is optional;  the latest plugin, 0.9.42 removes it from the template, so gradle should build the project OK.  Can you share the log of the crash?  Usually the log file contains the reason for the crash.

**Comment by lightray1** [comment]
Sorry for the delay.
Only after your reply I realized that version 0.9.42 had been released, after the upgrade and some tweaking to manifest.xml it seems that everything works.
Thank you!

**Comment by claywilkinson** [comment]
Great! I'm glad it is working!

**Comment by zaferyy** [comment]
Hi,

I have GooglePlayGamesPlugin-0.9.42 and it doesn't work with Gradle build
it says:"Resource '@integer/google_play_services_version' not found in AndroidManifest.xml:35"

when I delete the below line from GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin/AndroidManifest.xml
        <meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
it is working but can not login to google play games platform. if this line is not needed anymore why don't you delete it. if I don't use Gradle it is working but I need Gradle for adding firebase (with a lot of unnecessary plugins excepting analytics).

thanks.
