### ISSUE TITLE
AUTHENTICAION FAILED

### ISSUE THREAD

**Issue by hhogwood** [playgameservices/play-games-plugin-for-unity#2001]
I can't seem to get my project to authenticate with GPGS. I'm using Google Play App Signing. Plugin version .9.40 and Unity 2017.2.0.3f.

I've made sure my Google account is added as a tester
I've copied my upload SHA1 key to the API console

I feel like I'm just missing something silly but I cannot for the life of me figure out what it is.

> 10-31 19:55:15.367 23802 23829 I Unity   : Starting Auth with token client.
> 10-31 19:55:15.367 23802 23829 I Unity   :
> 10-31 19:55:15.367 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:15.367 23802 23829 I Unity   :
> 10-31 19:55:15.394 23802 23829 W Unity   : !!! [Play Games Plugin DLL] 11/01/17 2:55:15 +00:00 WARNING: Creating new PlayGamesPlatform
> 10-31 19:55:15.394 23802 23829 W Unity   :
> 10-31 19:55:15.394 23802 23829 W Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:15.394 23802 23829 W Unity   :
> 10-31 19:55:15.394 23802 23829 I Unity   :  [Play Games Plugin DLL] 11/01/17 2:55:15 +00:00 DEBUG: Activating PlayGamesPlatform.
> 10-31 19:55:15.394 23802 23829 I Unity   :
> 10-31 19:55:15.394 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:15.394 23802 23829 I Unity   :
> 10-31 19:55:15.394 23802 23829 I Unity   :  [Play Games Plugin DLL] 11/01/17 2:55:15 +00:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
> 10-31 19:55:15.394 23802 23829 I Unity   :
> 10-31 19:55:15.394 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:15.394 23802 23829 I Unity   :
> 10-31 19:55:15.394 23802 23829 I Unity   :  [Play Games Plugin DLL] 11/01/17 2:55:15 +00:00 DEBUG: Creating platform-specific Play Games client.
> 10-31 19:55:15.394 23802 23829 I Unity   :
> 10-31 19:55:15.394 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:15.394 23802 23829 I Unity   :
> 10-31 19:55:15.395 23802 23829 I Unity   :  [Play Games Plugin DLL] 11/01/17 2:55:15 +00:00 DEBUG: Creating Android IPlayGamesClient Client
> 10-31 19:55:15.395 23802 23829 I Unity   :
> 10-31 19:55:15.395 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:15.395 23802 23829 I Unity   :
> 10-31 19:55:15.424 23802 23829 I Unity   : ---- [0] -- 29
> 10-31 19:55:15.424 23802 23829 I Unity   :
> 10-31 19:55:15.424 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:15.424 23802 23829 I Unity   :
> 10-31 19:55:53.432 23802 23829 I Unity   : Starting Auth with token client.
> 10-31 19:55:53.432 23802 23829 I Unity   :
> 10-31 19:55:53.432 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:53.432 23802 23829 I Unity   :
> 10-31 19:55:53.434 23802 23829 W Unity   : !!! [Play Games Plugin DLL] 11/01/17 2:55:53 +00:00 WARNING: PlayGamesPlatform already initialized. Ignoring this call.
> 10-31 19:55:53.434 23802 23829 W Unity   :
> 10-31 19:55:53.434 23802 23829 W Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:53.434 23802 23829 W Unity   :
> 10-31 19:55:53.435 23802 23829 I Unity   :  [Play Games Plugin DLL] 11/01/17 2:55:53 +00:00 DEBUG: Activating PlayGamesPlatform.
> 10-31 19:55:53.435 23802 23829 I Unity   :
> 10-31 19:55:53.435 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:53.435 23802 23829 I Unity   :
> 10-31 19:55:53.435 23802 23829 I Unity   :  [Play Games Plugin DLL] 11/01/17 2:55:53 +00:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
> 10-31 19:55:53.435 23802 23829 I Unity   :
> 10-31 19:55:53.435 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:53.435 23802 23829 I Unity   :
> 10-31 19:55:53.440 23802 23829 I Unity   : ---- [0] -- 2097177
> 10-31 19:55:53.440 23802 23829 I Unity   :
> 10-31 19:55:53.440 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:53.440 23802 23829 I Unity   :
> 10-31 19:55:53.581 23802 23829 I Unity   : Building GPG services, implicitly attempts silent auth
> 10-31 19:55:53.581 23802 23829 I Unity   :
> 10-31 19:55:53.581 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:53.581 23802 23829 I Unity   :
> 10-31 19:55:53.652 23802 23829 I Unity   :  [Play Games Plugin DLL] 11/01/17 2:55:53 +00:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: 10
> 10-31 19:55:53.652 23802 23829 I Unity   :
> 10-31 19:55:53.652 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:53.652 23802 23829 I Unity   :
> 10-31 19:55:53.652 23802 23829 I Unity   :  [Play Games Plugin DLL] 11/01/17 2:55:53 +00:00 DEBUG: Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
> 10-31 19:55:53.652 23802 23829 I Unity   :
> 10-31 19:55:53.652 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:53.652 23802 23829 I Unity   :
> 10-31 19:55:53.653 23802 23829 I Unity   :  [Play Games Plugin DLL] 11/01/17 2:55:53 +00:00 DEBUG: there are pending auth callbacks - starting AuthUI
> 10-31 19:55:53.653 23802 23829 I Unity   :
> 10-31 19:55:53.653 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:53.653 23802 23829 I Unity   :
> 10-31 19:55:53.715 23802 23829 I Unity   :  [Play Games Plugin DLL] 11/01/17 2:55:53 +00:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
> 10-31 19:55:53.715 23802 23829 I Unity   :
> 10-31 19:55:53.715 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:53.715 23802 23829 I Unity   :
> 10-31 19:55:53.715 23802 23829 I Unity   :  [Play Games Plugin DLL] 11/01/17 2:55:53 +00:00 DEBUG: AuthState == Unauthenticated calling auth callbacks with failure
> 10-31 19:55:53.715 23802 23829 I Unity   :
> 10-31 19:55:53.715 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:53.715 23802 23829 I Unity   :
> 10-31 19:55:53.719 23802 23829 I Unity   : False Authentication failed
> 10-31 19:55:53.719 23802 23829 I Unity   :
> 10-31 19:55:53.719 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:53.719 23802 23829 I Unity   :
> 10-31 19:55:53.719 23802 23829 I Unity   : False Authentication failed
> 10-31 19:55:53.719 23802 23829 I Unity   :
> 10-31 19:55:53.719 23802 23829 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
> 10-31 19:55:53.719 23802 23829 I Unity   :
> 10-31 19:55:53.766 23802 23829 I Unity   :  [Play Games Plugin DLL] 11/01/17 2:55:53 +00:00 DEBUG: Invoking user callback on game thread

**Comment by avasilivich** [comment]
@hhogwood How do you install apk to your device? Do you install apk directly to your device or upload it to alpha/beta than download it to your device?

**Comment by hhogwood** [comment]
So far I’ve only pushed it over add to the device.

**Comment by avasilivich** [comment]
You mentioned earlier that you are using Google Play App Signing and you copied your upload SHA1 fingerprint to the API console. 
You should copy your app signing fingerprint to API console instead of your upload fingerprint. Check out [Google Play App Signing](https://support.google.com/googleplay/android-developer/answer/7384423)
