### ISSUE TITLE
Dozens of unwanted logs on project open

### ISSUE THREAD

**Issue by AdriaandeJongh** [playgameservices/play-games-plugin-for-unity#2009]
Hi,

I am unable to disable the following logs:

<img width="690" alt="screen shot 2017-11-06 at 14 09 42" src="https://user-images.githubusercontent.com/5611323/32442669-79f91a9c-c2fc-11e7-8c7d-3e32ca818e00.png">

No settings in the Assets > Play Services Resolver can disable these logs. 

For a multiplatform game, they are annoying, unwanted, and I would like an option to disable this behaviour.

Adriaan

**Comment by alexeyshevchnko** [comment]
The same problem, plus the whole editor hangs when you switch focus to the Windows. and the game load when adding a project increased by 10 seconds. although I do not use anything just dubavil project = (
