### ISSUE TITLE
OnStateLoaded dosen't work with a byte array bigger than 150 bytes?

### ISSUE THREAD

**Issue by BDCJR** [playgameservices/play-games-plugin-for-unity#201]
After I serialize my object the method returns me a byte array with a length of 1024 bytes. When I try to save it on cloud everything works fine, but when I'm trying to load gives me some DEBUGS. I play with the length of the array and I discover that if the length is less than 150 it works, otherwise no.
A little help will be highly appreciated. :)

P.S. After the log cat gets this debugs the app crashes!!!

"08-18 14:17:10.207: I/DEBUG(177):     #00  pc 00021f90  /system/lib/libc.so (tgkill+12)
08-18 14:17:10.207: I/DEBUG(177):     #01  pc 00012fe1  /system/lib/libc.so (pthread_kill+48)
08-18 14:17:10.207: I/DEBUG(177):     #02  pc 000131f5  /system/lib/libc.so (raise+10)
08-18 14:17:10.207: I/DEBUG(177):     #03  pc 00011f2b  /system/lib/libc.so
08-18 14:17:10.207: I/DEBUG(177):     #04  pc 00021844  /system/lib/libc.so (abort+4)
08-18 14:17:10.207: I/DEBUG(177):     #05  pc 001959cd  /system/lib/libart.so (art::Runtime::Abort()+168)
08-18 14:17:10.207: I/DEBUG(177):     #06  pc 0004293b  /system/lib/libart.so (art::LogMessage::~LogMessage()+506)
08-18 14:17:10.207: I/DEBUG(177):     #07  pc 000c0987  /system/lib/libart.so (art::IndirectReferenceTable::Add(unsigned int, art::mirror::Object const*)+498)
08-18 14:17:10.207: I/DEBUG(177):     #08  pc 00138f1b  /system/lib/libart.so
08-18 14:17:10.207: I/DEBUG(177):     #12  pc 004b62f8  /data/app-lib/com.quadom.ggstest-1/libunity.so (AndroidJNI_CUSTOM_FromReflectedMethod(void*)+180)
08-18 14:17:10.207: I/DEBUG(177):     #13  pc 00006bd4  <unknown>
08-18 14:17:10.207: I/DEBUG(177):     #00  bed15de8  00000006  
08-18 14:17:10.207: I/DEBUG(177):     #01  bed15e00  00000006  
08-18 14:17:10.207: I/DEBUG(177):     #02  bed15e10  bed15e1c  [stack]"

**Comment by claywilkinson** [comment]
closing this because is it really old.  Please open a new issue if you are still having problems.
