### ISSUE TITLE
CommandInvokationFailure: Failed to re-package resources. Unity 2017.2.0f3, GPGS 0.9.42

### ISSUE THREAD

**Issue by sprawls** [playgameservices/play-games-plugin-for-unity#2015]
I'm tried a lot of the solution for similar issues but nothing seems to work. I'm getting the error below when I try to build. I only have Google Play Games Service in the project Facebook or AdMod.
I've upgraded my sdks to the latests version, reinstalled the gpgs plugin and did the Google Play Games android setup. I am attempting to build in Internal Mode (Not Gradle).

I have 2 android manifests :
In GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin/ (autogenerated by the plugin)

> <?xml version="1.0" encoding="utf-8"?>
> 
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="com.google.example.games.mainlibproj"
>     android:versionCode="1"
>     android:versionName="1.0" >
> 
>     <uses-sdk android:minSdkVersion="8" android:targetSdkVersion="16" />
> 
>     <application>
> 
>      
>         <meta-data android:name="com.google.android.gms.nearby.connection.SERVICE_ID"
>             android:value="" />
> 
>         
>         <meta-data android:name="com.google.android.gms.games.APP_ID"
>             android:value="\ 642885502486" />
> 
>         
>         <meta-data android:name="com.google.android.gms.games.unityVersion"
>             android:value="\ 0.9.42" />
> 
>         
>         <meta-data android:name="com.google.android.gms.version"
>             android:value="@integer/google_play_services_version" />
> 
>         <activity android:name="com.google.games.bridge.NativeBridgeActivity"
>             android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
>     </application>
> </manifest>
> 

In Plugins/Android/gpgs-plugin-support-0.9.42/ (Without this file I'm getting a android manifest missing when building).

> <?xml version="1.0" encoding="utf-8"?>
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="com.google.example.games.mainlibproj"
>     android:versionCode="1"
>     android:versionName="1.0" >
> 
>     <application />
> 
> </manifest>

The Error I am getting : 

>  CommandInvokationFailure: Failed to re-package resources.
>  C:\Users\Alexis\AppData\Local\Android\sdk\build-tools\27.0.1\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "C:/Users/Alexis/AppData/Local/Android/sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages com.google.example.games.mainlibproj:com.google.example.games.mainlibproj:com.google.android.gms.auth.api:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.tasks:android.support.compat:android.support.coreui:android.support.coreutils:android.support.fragment:android.support.mediacompat:android.support.v4 -S "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\gpgs-plugin-support-0.9.42\res" -S "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\play-services-auth-10.2.6\res" -S 
>  "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\play-services-auth-base-10.2.6\res" -S "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\play-services-base-10.2.6\res" -S "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\play-services-basement-10.2.6\res" -S "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\play-services-drive-10.2.6\res" -S "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\play-services-games-10.2.6\res" -S "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\play-services-nearby-10.2.6\res" -S "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\play-services-tasks-10.2.6\res" -S "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\support-compat-25.2.0\res" -S "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\support-core-ui-25.2.0\res" -S "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\support-core-utils-25.2.0\res" -S "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\support-fragment-25.2.0\res" -S "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\support-media-compat-25.2.0\res" -S "C:\Users\Alexis\Documents\github\InversionGame\somos\Temp\StagingArea\android-libraries\support-v4-25.2.0\res"
>  
> stderr[
>  AndroidManifest.xml:10: error: Error: String types not allowed (at 'configChanges' with value 'mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize|fontScale|layoutDirection|density').
>  
>  ]
>  stdout[
>  Configurations:
>  (default)
> 
>  Files:
>  AndroidManifest.xml
>    Src: () AndroidManifest.xml

Here's my plugins Android Folder :
![image](https://user-images.githubusercontent.com/6887506/32641872-65873360-c59e-11e7-9eac-e47f2f338720.png)

**Comment by sprawls** [comment]
Just wanted to add that GPGS was working well about a month ago. I'm not sure what broke it, but I upgraded GPGS version inbetween.

**Comment by deathsaber92** [comment]
The problem is that in the libs folder you most likely have 11.2 versions (or some other then 10.2.6) of the aar files and the conflict resolver is not working. I am currently on the same problem..... I lost already 2 days trying to find a fix.... someone please help with those aar files. The plugins admob and googple play games for unity are simply a mess right now. They work ok separately but conflict when used together...

**Comment by sprawls** [comment]
Those are the only two files I have in Assets/Plugins/Android/Libs subfolders

![image](https://user-images.githubusercontent.com/6887506/32657846-48f734ba-c5e5-11e7-98ed-992636323f32.png)


I don't seem to have multiple versions of the .aar files, but from what I've read elsewhere you should only keep the .aar with the higher version. Here are all my play-services .aar files. The one thing I notice is that the resolver isn't the same version but that seems normal.

![image](https://user-images.githubusercontent.com/6887506/32657960-cb6e2df4-c5e5-11e7-94b9-6d914c8fcc55.png)

**Comment by sprawls** [comment]
I managed to fix the problem. Turns out it was unity's version causing the issue with Android Target Version 24 and lower. Currently the only version of Unity that fixes it is the beta 2017.3b8.

For 2017.2 it's going to be fixed in 2017.2p2 which isn't out yet.

**Comment by junaidshad** [comment]
i'm having same issue in unity3d 5.6.4
:/ anyone having precise fix?
