### ISSUE TITLE
GPGS + AdMob = Crash on start

### ISSUE THREAD

**Issue by IgnatevSV** [playgameservices/play-games-plugin-for-unity#2023]
I'm using Unity 5.5.2f1 and GPGS 0.9.36 (because other versions work incorrect). I tried to use AdMob plugin (https://github.com/googleads/googleads-mobile-unity) 3.0.5, 3.3.0 and 3.8.0 versions, but app always crashed at start.
What i can do?

Assets\Plugins\Android\MainLibProj\AndroidManifest.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- This file was automatically generated by the Google Play Games plugin for Unity
     Do not edit. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.google.example.games.mainlibproj"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk android:minSdkVersion="8" android:targetSdkVersion="16" />

    <application>

     <!-- Required for Nearby Connections API -->
        <meta-data android:name="com.google.android.gms.nearby.connection.SERVICE_ID"
            android:value="" />

        <!-- the space in these forces it to be interpreted as a string vs. int -->
        <meta-data android:name="com.google.android.gms.games.APP_ID"
            android:value="\ 56**********" />
        <meta-data android:name="com.google.android.gms.games.unityVersion"
            android:value="\ 0.9.36" />
        <meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

        <activity android:name="com.google.games.bridge.NativeBridgeActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
    </application>
</manifest>
```

Assets\Plugins\Android\GoogleMobileAdsPlugin\AndroidManifest.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<!--
This Google Mobile Ads plugin library manifest will get merged with your
application's manifest, adding the necessary activity and permissions
required for displaying ads.
-->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.google.unity"
    android:versionName="1.0"
    android:versionCode="1">
  <uses-sdk android:minSdkVersion="14"
      android:targetSdkVersion="19" />
  <application>
  </application>
</manifest>
```

**Comment by eirikost** [comment]
Hi, I got it working with the setup shown below and also with older versions of Unity. When I import the AdMob plugin I skip the PlayServicesResolver and use the one in GPGS.

- GPGS 0.9.36
- GoogleMobileAds 3.1.3
- Unity 2017.1.1.f1
- Android SDK Build-Tools 27.0.1
- platform-tools_r25.0.3
- tools_r25.2.5
- jdk1.8.0_144

I haven't got it working with the newest versions of GPGS though.

**Comment by brt94** [comment]
problem can be solved by deleting "GoogleMobileAds\Editor" folder 
and pasting into gpgs-plugin-support-0.9.50.pom
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.google.games</groupId>
  <artifactId>gpgs-plugin-support</artifactId>
  <version>0.9.50</version>
  <packaging>srcaar</packaging>
  <dependencies>
    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-games</artifactId>
      <version>11.6+</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-auth</artifactId>
      <version>11.6+</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-nearby</artifactId>
      <version>11.6+</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
    <groupId>com.google.android.gms</groupId>
    <artifactId>play-services-ads</artifactId>
    <version>15.1+</version>
    <scope>compile</scope>
    </dependency>
    <dependency>
    <groupId>com.google.android.gms</groupId>
    <artifactId>play-services-location</artifactId>
    <version>11.6+</version>
    <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
