### ISSUE TITLE
NO_GPGS Does not work on Unity IOS 

### ISSUE THREAD

**Issue by temresen** [playgameservices/play-games-plugin-for-unity#2027]
Since, GPGS will not be supporting on IOS soon, I decided to use NO_GPGS on my IOS build. 

I add NO_GPGS under Scripting Define Symbols but still in Xcode I have GooglePlayServices which causes #1459 

Am I doing something wrong with NO_GPGS? Or is there a problem :( 

I am using Unity 2017.1.1f

<img width="335" alt="ekran resmi 2017-11-14 23 03 57" src="https://user-images.githubusercontent.com/16319223/32802394-f65e9fc2-c990-11e7-9c20-ea18d3179f7f.png">

**Comment by siddharth3322** [comment]
Any solution for this ?? Because me too stuck into the same problem.

**Comment by siddharth3322** [comment]
This change worked for me. For both GPG files exist in iOS folder change their folder to Android only. Then after it will not create any barrier in xCode project compilation.
Here is reference image for more clearance of others:

![gpg_only_enable_android_flag](https://user-images.githubusercontent.com/3082151/33239825-89461688-d2d0-11e7-8b0f-d1105e4eb6ff.png)

So two steps to perform 1) NO_GPGS flag in scripting defined symbols and 2) Un-tick iOS platform for GPG files exist in Plugin->iOS folder.

**Comment by Gerald123** [comment]
In your project search for "GPGSDependencies". Open it and remove this part below and than save it. It should work.

`<!-- iOS Cocoapod dependencies can be specified by each iosPod element. -->   <iosPods>     <!-- iosPod supports the following attributes:          * "name" (required)            Name of the Cocoapod.          * "version" (optional)            Cocoapod version specification for the named pod.            If this is not specified the latest version is used.          * "bitcodeEnabled" (optional)            Whether this Cocoapod requires bitcode to be enabled in Unity's            generated Xcode project.  This is "true" by default.          * "minTargetSdk" (optional)            The minimum iOS SDK required by this Cocoapod. -->     <iosPod name="GooglePlayGames" version="5.1.2" bitcodeEnabled="false"             minTargetSdk="6.0">       <!-- Set of source URIs to search for this Cocoapod spec.            By default Cocoapods will attempt to fetch the pod specs from:            * $HOME/.cocoapods/repos            * https://github.com/CocoaPods/Specs            -->       <sources>         <source>https://github.com/CocoaPods/Specs</source>       </sources>     </iosPod>   </iosPods> `

**Comment by temresen** [comment]
@siddharth3322 
@Gerald123 

Both solutions work! Thank you guys.
