### ISSUE TITLE
Getting user info ( BirthDay .. ) 

### ISSUE THREAD

**Issue by Opeth001** [playgameservices/play-games-plugin-for-unity#2035]
Hello,
everything is working for me but i dont understand why there is no any api that gives the User Basic info like ( Birthday , Language , Country , ....  ) im calling .AddOauthScope("profile") .RequestEmail()
but it's giving me juste the Email ,User ID and the Username.

can anyone tell me if it's possible to get the Real Basic infos ??
Thank you in Advance.

**Comment by claywilkinson** [comment]
The profile information is documented as part of Google Sign-in: https://developers.google.com/identity/sign-in/android/people.  The Games Services API does not add any additional information.
