### ISSUE TITLE
App crashes on Social.localUser.Authenticate

### ISSUE THREAD

**Issue by SonicDirewolf** [playgameservices/play-games-plugin-for-unity#2037]
I am using Unity 5.5.1 and as soon as I try to sign in using Social.localUser.Authenticate the app closes/crashes. It works fine until I call this function. 
This is the function.
`  Social.localUser.Authenticate ((bool success) => {
	if(success){
Debug.Log("YESSS");
			}
else{
	Debug.Log("NOOOOOOO");
			}
});
`
The Noo part gives this in the console

> NOOOOOOO
UnityEngine.Debug:Log(Object)
googleplay:<Login>m__0(Boolean) (at Assets/googleplay.cs:47)
GooglePlayGames.<Authenticate>c__AnonStorey0:<>m__0(Boolean, String) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:395)
GooglePlayGames.BasicApi.DummyClient:Authenticate(Action`2, Boolean) (at Assets/GooglePlayGames/BasicApi/DummyClient.cs:50)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`2, Boolean) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:426)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:395)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:360)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesLocalUser.cs:49)
googleplay:Login() (at Assets/googleplay.cs:35)
UnityEngine.EventSystems.EventSystem:Update()

PLEASE HELP!

**Comment by Killo0o** [comment]
Had the same problem, after 2 days of trying everything the thing that fixed it was updating my unity to 2017.1. After that when you Force Resolve android it works fine
