### ISSUE TITLE
NullReferenceException After importing the plugin  GooglePlayGamesPlugin-0.9.42

### ISSUE THREAD

**Issue by JrPro1** [playgameservices/play-games-plugin-for-unity#2040]
I created a new project in Unity 2017.2.of3 and imported the plugin( GooglePlayGamesPlugin-0.9.42), but i am getting the below errors,
even if it tried to Android Resolver => Force resolve, but its still not fixing the issue

**# Gradle failed to fetch dependencies.**
Failed to run 'F:\Unity\UnityAndroidBaseProject\UnityAndroidBaseProject\Temp\PlayServicesResolverGradle\gradlew.bat -b "F:\Unity\UnityAndroidBaseProject\UnityAndroidBaseProject\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" --no-daemon "-PANDROID_HOME=C:\Users\MYComp\AppData\Local\Android\Sdk" "-PTARGET_DIR=F:\Unity\UnityAndroidBaseProject\UnityAndroidBaseProject\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///F:/Unity/UnityAndroidBaseProject/UnityAndroidBaseProject/Assets/GooglePlayGames/Editor/m2repository;https://maven.google.com" "-PPACKAGES_TO_COPY=com.google.games:gpgs-plugin-support:0+;com.google.android.gms:play-services-games:10+;com.google.android.gms:play-services-nearby:10+;com.google.android.gms:play-services-auth:10+"'
stdout:

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

stderr:

exit code: 1

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__1F(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__28()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
 
**And Another  One**

NullReferenceException: Object reference not set to an instance of an object
GooglePlayServices.AndroidSdkManager+<Create>c__AnonStoreyA.<>m__C (GooglePlayServices.AndroidSdkPackageCollection packages)
GooglePlayServices.SdkManager+<QueryPackages>c__AnonStorey9.<>m__B (GooglePlayServices.Result result)
GooglePlayServices.SdkManagerUtil+<QueryPackages>c__AnonStorey4.<>m__4 (GooglePlayServices.Result result)
GooglePlayServices.CommandLineDialog+ProgressReporter.Update (GooglePlayServices.CommandLineDialog window)
GooglePlayServices.CommandLineDialog.Update ()
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:285)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:278)
UnityEditor.HostView.SendUpdate () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:354)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:127)

**Comment by PathToLife** [comment]
Hmm I'll provide some screenshots of some windows for you to compare, in return can you capture the same windows and show us?

_Google greenshot for a lovely screenshot program._

![image](https://user-images.githubusercontent.com/12622625/33231198-0528c9e2-d256-11e7-9506-3fd15b923694.png)

![image](https://user-images.githubusercontent.com/12622625/33231213-5e5ea162-d256-11e7-8fc2-d1ca70333939.png)

![image](https://user-images.githubusercontent.com/12622625/33231232-a483474c-d256-11e7-9f7a-a01e445c32ac.png)

**Comment by JrPro1** [comment]
Thanks! it worked like a charm!
