### ISSUE TITLE
Can't login if apk isn't dowloaded from play store

### ISSUE THREAD

**Issue by michelebonapace** [playgameservices/play-games-plugin-for-unity#2049]
Even if I disabled anti piracy in the play games page, if I don't dowload the apk from the store (alpha beta or release) i can't access to play games service.
If I install it from the store, it works, but if I install it from my builded apk or directly from unity, it can't access it.

**Comment by sreerajrr** [comment]
If you have used google app signing, then you should copy the sha1 in the 'upload certificate' from app signing menu and paste it in the developer console credentials (sha1),

**Comment by michelebonapace** [comment]
thank you very much @sreerajrr, i'd have never figured it out myself!
