### ISSUE TITLE
Messages cease to be accepted after any delay

### ISSUE THREAD

**Issue by NikitaNikita1** [playgameservices/play-games-plugin-for-unity#2055]
Hello
I use google multiplayer in the game (Unity).
Immediately after connecting, the messages are sent without problems, but once the game freezes for 1-2 seconds, the messages are no longer accepted.
I can not completely get rid of hangs, on weak devices do not save even coroutines.
```
       PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();
        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.Activate();
...
 Social.localUser.Authenticate((bool success) 
...
        const int MinO = 1,MaxO = 1;
        const int GameType = 0;
        PlayGamesPlatform.Instance.RealTime.CreateQuickGame(MinO,MaxO,GameType,this);
...
 PlayGamesPlatform.Instance.RealTime.SendMessageToAll
...
```

Is there any way to fix this?

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
