### ISSUE TITLE
Google Sign-in is not working on IOS Build. Error : NotImplementedException: The requested feature is not implemented at GooglePlayGames.IOS.IOSTokenClient.SetAccountName

### ISSUE THREAD

**Issue by defianasulaeman** [playgameservices/play-games-plugin-for-unity#2059]
I tried to run the sample (Minimal) and it's not working. I clicked on the "Authenticate" Button and I got following error on XCode console : 

 

> NotImplementedException: The requested feature is not implemented.
>   at GooglePlayGames.IOS.IOSTokenClient.SetAccountName (System.String accountName) [0x00000] in <filename unknown>:0 
>   at GooglePlayGames.Native.NativeClient.InitializeTokenClient () [0x00000] in <filename unknown>:0 
>   at GooglePlayGames.Native.NativeClient.Authenticate (System.Action`2 callback, Boolean silent) [0x00000] in <filename unknown>:0 
>   at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`2 callback, Boolean silent) [0x00000] in <filename unknown>:0 
>   at MainGui.OnGUI () [0x00000] in <filename unknown>:0 

> 

> (Filename: currently not available on il2cpp Line: -1)
> 
> !!! [Play Games Plugin DLL] 12/19/17 10:57:53 +07:00 WARNING: Creating new PlayGamesPlatform
> UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> UnityEngine.Logger:Log(LogType, Object)
> UnityEngine.Debug:LogWarning(Object)
> GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
>  
> (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Can anyone help me. Thanks....

**Comment by claywilkinson** [comment]
Unfortunately Google Play Games Services no longer supports iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
