### ISSUE TITLE
Quick play

### ISSUE THREAD

**Issue by IsnaniWidhiHidayat** [playgameservices/play-games-plugin-for-unity#2064]
Hey guys i have an issue when using realtime service. i have set minimum opponent 1 an maximum opponent to 3, when 2 player quick play they can join same room but when third player try quick match, it not join previous room but create new one.

<img src="https://preview.ibb.co/nyDfPm/problem.png" alt="problem">

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
