### ISSUE TITLE
GPGS Cocoapods getting added despite not using GPGS for iOS

### ISSUE THREAD

**Issue by infernova** [playgameservices/play-games-plugin-for-unity#2067]
This is more an annoyance than an actual bug but whenever build a Unity iOS project with cocoapods (for the other Google services I use), the GPGS pod also gets added as a dependency despite adding the NO_GPGS flag into my build settings. This would have been fine if it didn't interfere with the build cycle but the GoogleAuth pod does not have bitcode so building my project with bitcode enabled will cause the build process to fail.

So far I've been circumventing this by removing GooglePlayGames from my podfile every time I make an iOS build and removing the iOS Pod dependency entirely from GPGSDependencies.xml entirely but it is somewhat annoying to have to repeat this entire process all over every time I update my Unity GPGS plugin. Hopefully the Google team can do something about this, especially since GPGS is getting deprecated for the iOS ecosystem.

**Comment by claywilkinson** [comment]
Thanks for the feedback.  The next release will remove the iOS support completely.  Please feel free to submit a pull request for any changes that you propose (or end up re-applying whenever you update).

**Comment by claywilkinson** [comment]
Fixed in 0.9.50
