### ISSUE TITLE
Unable to test/debug from editor

### ISSUE THREAD

**Issue by javilumbrales** [playgameservices/play-games-plugin-for-unity#2069]
Hi,

So, after a lot of research I've been unable to get google play services to work from Unity editor while playing. I have to compile and deploy to a mobile device each time I want to test something. Is there any way to debug/test getting scores/leaderboard etc. from editor that I'm not aware of?

Thanks!

**Comment by claywilkinson** [comment]
At this time there is no way to test in the editor.
