### ISSUE TITLE
How to refresh IDToken without "Sign-out".

### ISSUE THREAD

**Issue by lflflfong** [playgameservices/play-games-plugin-for-unity#2071]
how to refresh IDToken without "Sign-out".

I mentioned #1946.

I need  IDToken Refresh function like to "GetAnotherServerAuthCode(bool reAuthenticateIfNeeded,  Action<string> callback)" in the latest version.

I use IdToken Refresh temporarily.  
sample code : `
public void GetIdToken(Action<CommonStatusCodes, string> callback)
        {
            PlayGamesHelperObject.RunOnGameThread(() =>
            mTokenClient.FetchTokens((rc) =>
            {
                if (callback != null)
                {
                    string idToken = mTokenClient.GetIdToken();
                    PlayGamesHelperObject.RunOnGameThread(() =>
                    callback(CommonStatusCodes.Success, idToken));
                }
            }));
        }
`

Thanks for reading my issue.

**Comment by ulgerang** [comment]
Is that work? which version do you use?

**Comment by lflflfong** [comment]
@ulgerang 

I use GooglePlayGamesPlugin-0.9.42.unitypackage.
sample code is part of it.

I use getIdToken func (modify func) by referring to #1917  And it works well.

**Comment by ulgerang** [comment]
@lflflfong  
Thank you for reply. 

I used 0.9.38a. but the code didn't work.
But when I use the lastest version(0.9.42), It works.

**Comment by lflflfong** [comment]
@ulgerang 

When I modified that code, it was version 0.9.36.

**Comment by ulgerang** [comment]
@lflflfong 
When I ran the code at the previous version, it didn't refresh.
It just fetched same token ,whether  it was expired or not 
I don't know some part might be wrong.but what I see was it.

but now It works fine,  it refresh the token.

**Comment by lflflfong** [comment]
@ulgerang 

Oh, I See.
I thought you had to use 0.9.38a.

I`m glad that it works well. :D
