### ISSUE TITLE
Signing in Fails, ERROR_NOT_AUTHORIZED

### ISSUE THREAD

**Issue by K4ds3** [playgameservices/play-games-plugin-for-unity#2076]
Hey everyone, whenever I try to sign into the Play Games Services I'm getting a `ERROR_NOT_AUTHORIZED`.

I've linked my App signing certificate (6F:12:3B....) & my Upload certificate (82:2E:87....) with the Play Games Services.
  
## App Signing Page:
![a](https://user-images.githubusercontent.com/5180118/34900887-2bb05c32-f804-11e7-9346-84c0d4b0effe.png)
  
## App signing cert at the developer console:
![c](https://user-images.githubusercontent.com/5180118/34900933-a2ee0c4a-f804-11e7-9cde-353ae282da86.png)
  
## Upload cert at the developer console:
![b](https://user-images.githubusercontent.com/5180118/34900918-81f99572-f804-11e7-9bca-9c8d1ccb7d03.png)
  
 
## Testers
My accounts are added as Testers at the Play Games Settings, also I've already published the Play Games Services entry.
![d](https://user-images.githubusercontent.com/5180118/34901016-62873bbc-f805-11e7-84f3-6115a1d33561.png)
![e](https://user-images.githubusercontent.com/5180118/34901037-95dc5fa6-f805-11e7-94ba-9865fd80df49.png)
  
## Keys
The keys should also be right, since the Upload cert key in the console is the same as the one I get through the keytool. The google support reset my google play keystore this month, since my old key was only 1024 Bit.
![f](https://user-images.githubusercontent.com/5180118/34901087-13b10850-f806-11e7-8de6-5371ad11845d.png)

  
## Code:
``` 
protected void Awake() {
....
if (Application.platform == RuntimePlatform.Android) {
                PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
                    // requests a server auth code be generated so it can be passed to an
                    //  associated back end server application and exchanged for an OAuth token.
                    .RequestServerAuthCode(false)
                    // requests an ID token be generated.  This OAuth token can be used to
                    //  identify the player to other services such as Firebase.
                    .RequestIdToken()
                    .Build();

                PlayGamesPlatform.InitializeInstance(config);
                // recommended for debugging:
                PlayGamesPlatform.DebugLogEnabled = true;
                // Activate the Google Play Games platform
                PlayGamesPlatform.Activate();
            }
...
}

protected void Start() {
...
PlayGamesPlatform.Instance.Authenticate(success => {
                    if (!success)
                        Debug.LogError("Couldn't sign into Google Play Services");
                });
...
}
```

## Log:
```01-13 01:46:20.711 18768 18785 I Unity   : Starting Auth with token client.
01-13 01:46:20.711 18768 18785 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-13 01:46:21.181 18768 18785 W Unity   : !!! [Play Games Plugin DLL] 01/13/18 1:46:21 +01:00 WARNING: Creating new PlayGamesPlatform
01-13 01:46:21.181 18768 18785 W Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-13 01:46:21.181 18768 18785 I Unity   :  [Play Games Plugin DLL] 01/13/18 1:46:21 +01:00 DEBUG: Activating PlayGamesPlatform.
01-13 01:46:21.181 18768 18785 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-13 01:46:21.181 18768 18785 I Unity   :  [Play Games Plugin DLL] 01/13/18 1:46:21 +01:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
01-13 01:46:21.181 18768 18785 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-13 01:46:21.181 18768 18785 I Unity   :  [Play Games Plugin DLL] 01/13/18 1:46:21 +01:00 DEBUG: Creating platform-specific Play Games client.
01-13 01:46:21.181 18768 18785 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-13 01:46:21.181 18768 18785 I Unity   :  [Play Games Plugin DLL] 01/13/18 1:46:21 +01:00 DEBUG: Creating Android IPlayGamesClient Client
01-13 01:46:21.181 18768 18785 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-13 01:46:21.211 18768 18785 I Unity   : ---- [0] -- 25
01-13 01:46:21.211 18768 18785 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-13 01:46:43.881 18768 18768 I Unity   : Building GPG services, implicitly attempts silent auth
01-13 01:46:43.881 18768 18768 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-13 01:46:44.191 18768 18785 I Unity   :  [Play Games Plugin DLL] 01/13/18 1:46:44 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: 16
01-13 01:46:44.191 18768 18785 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-13 01:46:44.191 18768 18785 I Unity   :  [Play Games Plugin DLL] 01/13/18 1:46:44 +01:00 DEBUG: Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
01-13 01:46:44.191 18768 18785 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-13 01:46:44.191 18768 18785 I Unity   :  [Play Games Plugin DLL] 01/13/18 1:46:44 +01:00 DEBUG: there are pending auth callbacks - starting AuthUI
01-13 01:46:44.191 18768 18785 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-13 01:46:44.271 18768 18785 I Unity   :  [Play Games Plugin DLL] 01/13/18 1:46:44 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
01-13 01:46:44.271 18768 18785 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-13 01:46:44.271 18768 18785 I Unity   :  [Play Games Plugin DLL] 01/13/18 1:46:44 +01:00 DEBUG: AuthState == Unauthenticated calling auth callbacks with failure
01-13 01:46:44.271 18768 18785 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-13 01:46:44.271 18768 18785 E Unity   : Couldn't sign into Google Play Services
01-13 01:46:44.271 18768 18785 E Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-13 01:46:44.291 18768 18785 I Unity   :  [Play Games Plugin DLL] 01/13/18 1:46:44 +01:00 DEBUG: Invoking user callback on game thread
01-13 01:46:44.291 18768 18785 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```
  
Plugin Version: 0.9.42  
Unity Version: 2017.3.0f3
  
I really hope someone can help me with this bug, I'm messing around with it for 4 days now and couldn't find a working solution.

**Comment by alleluso** [comment]
I'm getting the exact same error.

Log:
`01-18 12:10:43.239: I/Unity(7700):  [Play Games Plugin DLL] 01/18/18 12:10:43 +01:00 DEBUG: Activating PlayGamesPlatform.
01-18 12:10:43.239: I/Unity(7700):  
01-18 12:10:43.239: I/Unity(7700): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-18 12:10:43.239: I/Unity(7700):  [Play Games Plugin DLL] 01/18/18 12:10:43 +01:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
01-18 12:10:43.239: I/Unity(7700):  
01-18 12:10:43.239: I/Unity(7700): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-18 12:10:43.239: I/Unity(7700):  [Play Games Plugin DLL] 01/18/18 12:10:43 +01:00 DEBUG: Creating platform-specific Play Games client.
01-18 12:10:43.239: I/Unity(7700):  
01-18 12:10:43.239: I/Unity(7700): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-18 12:10:43.239: I/Unity(7700):  [Play Games Plugin DLL] 01/18/18 12:10:43 +01:00 DEBUG: Creating Android IPlayGamesClient Client
01-18 12:10:43.239: I/Unity(7700):  
01-18 12:10:43.239: I/Unity(7700): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-18 12:10:43.250: I/UnityAds(7700): com.unity3d.ads.api.Sdk.logInfo() (line:70) :: Requesting ad plan from https://auction.unityads.unity3d.com.....
01-18 12:10:43.255: I/Unity(7700): ---- [0] -- 113
01-18 12:10:43.255: I/Unity(7700):  
01-18 12:10:43.255: I/Unity(7700): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-18 12:10:43.289: I/Unity(7700): OnInitialized: PASS
01-18 12:10:43.289: I/Unity(7700):  
01-18 12:10:43.289: I/Unity(7700): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-18 12:10:43.369: D/GamesUnitySDK(7700): Performing Android initialization of the GPG SDK
01-18 12:10:43.412: I/Unity(7700): Building GPG services, implicitly attempts silent auth
01-18 12:10:43.412: I/Unity(7700):  
01-18 12:10:43.412: I/Unity(7700): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-18 12:10:43.698: D/AdsUnity(7700): Calling loadAd() on Android
01-18 12:10:44.230: I/Unity(7700):  [Play Games Plugin DLL] 01/18/18 12:10:44 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: 13
01-18 12:10:44.230: I/Unity(7700):  
01-18 12:10:44.230: I/Unity(7700): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-18 12:10:44.230: I/Unity(7700):  [Play Games Plugin DLL] 01/18/18 12:10:44 +01:00 DEBUG: Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
01-18 12:10:44.230: I/Unity(7700):  
01-18 12:10:44.230: I/Unity(7700): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-18 12:10:44.230: I/Unity(7700):  [Play Games Plugin DLL] 01/18/18 12:10:44 +01:00 DEBUG: there are pending auth callbacks - starting AuthUI
01-18 12:10:44.230: I/Unity(7700):  
01-18 12:10:44.230: I/Unity(7700): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-18 12:10:44.230: I/Unity(7700):  [Play Games Plugin DLL] 01/18/18 12:10:44 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
01-18 12:10:44.230: I/Unity(7700):  
01-18 12:10:44.230: I/Unity(7700): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-18 12:10:44.230: I/Unity(7700):  [Play Games Plugin DLL] 01/18/18 12:10:44 +01:00 DEBUG: AuthState == Unauthenticated calling auth callbacks with failure
01-18 12:10:44.230: I/Unity(7700):  
01-18 12:10:44.230: I/Unity(7700): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-18 12:10:44.238: I/Unity(7700):  [Play Games Plugin DLL] 01/18/18 12:10:44 +01:00 DEBUG: Invoking user callback on game thread
01-18 12:10:44.238: I/Unity(7700):  
01-18 12:10:44.238: I/Unity(7700): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-18 12:10:44.505: I/UnityAds(7700): com.unity3d.ads.api.Sdk.logInfo() (line:70) :: Unity Ads placement video status set to READY
01-18 12:10:44.506: I/UnityAds(7700): com.unity3d.ads.api.Sdk.logInfo() (line:70) :: Unity Ads placement rewardedVideo status set to READY
`
Plugin Version: 0.9.42
Unity Version: 5.6.1f1 Personal

It worked two months ago, then I left my project until a week ago... It doesn't log in anymore unless I delete the data of Google Play Services from my phone... But if I log out and try to log back in it does not work... nothing happens.

**Comment by Kadse1337** [comment]
Any updates on this? Can someone help? :/

**Comment by iamfaraz** [comment]
i am having the same problem. Unable to sign In with "success" always returning false.

**Comment by dus3d** [comment]
I am having exactly the same problem for a few weeks now. I could not even find answers to this anywhere. 

The first error is "DEBUG: Starting Auth Transition. Op: SIGN_IN status: 16"

then the next is "DEBUG: AuthState == Unauthenticated calling auth callbacks with failure"

then "success = false" always. I tried to login for a few hours just keep logging in until I get a crash report on google play and it somehow gets fixed when I run the app again. Until the next time I get the same bug. No know fix at all, just waiting for the crash to happen but I could not replicate the crash as I want. I just keep on logging in hoping that google play will crash to fix the problem.

**Comment by Reizoe** [comment]
Logcat showed me a No Client error, which was resolved by importing android-support-v4.jar into the project - I can login now. Perhaps this works for your case as well?

**Comment by iamfaraz** [comment]
I solved this by using Easy Mobile Plugin ... I don't whats the difference between the initialization process but it's working fine for me now.

**Comment by avvie** [comment]
I am getting the same problem as well, it feels like i have done this process a few times already successfully and suddenly it wont work.
Any pointers on what is wrong are appreciated

**Comment by ThanhWilliamLe** [comment]
I have the same problem, I even tried both App signing certificate and Upload certificate in Credentials, none work.

**Comment by dominicdev** [comment]
same here any? I have 2 app tested..one was working and the other one is not.. not sure why

**Comment by doronn** [comment]
The same for me too.
anyone was able to find a solution?
I even put my app in open beta just to be sure.
@Reizoe from where did you download the support library? (I can see logs as opposed to what you described but it may be the last resort?)
@iamfaraz Can you post a link to that plugin?

**Comment by iamfaraz** [comment]
@doronn here you go [Easy Mobile Pro - $59](https://assetstore.unity.com/packages/tools/integration/easy-mobile-pro-75476)

**Comment by bhallionOhbibi** [comment]
Hello there,

Are you using firebase in your project ? (you can tell in your Game Services page on the Google Play console. There is a firebase logo aside the project's name)

In my case, this error was related to a missing firebase configuration.

**Comment by SturgeonDu** [comment]
is someone knows how to fix this problem,i have same problem.
please help!!

**Comment by dominicdev** [comment]
I already solve and understand this problem in App signing cert at the developer console..under Credentials.. 
1st API keys - make use you add App Signing..both upload and app signing in google dev console..in my understanding upload signing is when you build it locally that make authorize to login in gplay service.. and app signing was one in the store(beta/alpa testers).. 
2nd - OAuth 2.0 client IDs.. make sure ur using the Web application.. that was the same in the google dev console.. 
and that make work in may part.. sometime you need to do it manually

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
