### ISSUE TITLE
setting menus are not selected.

### ISSUE THREAD

**Issue by machroad** [playgameservices/play-games-plugin-for-unity#2077]
After upgrading Unity, the setting menus are not selected.
Please help me.

![2018-01-13](https://user-images.githubusercontent.com/7057178/34902431-72ae3d52-f85e-11e7-8cfe-402a3b789d6c.png)

**Comment by claywilkinson** [comment]
They are disabled because you are building for PC,Mac & Linux Standalone <DX11>.  Change the player type to Android and they menu will be enabled.
