### ISSUE TITLE
google play services not signing after game is publish on google store

### ISSUE THREAD

**Issue by kylerts** [playgameservices/play-games-plugin-for-unity#209]
Right so i have created and tested my app many many times with this plugin implemented and Everything works incredibly. However when i publish it through the google play store, the game  says, failed to sign in. My guess is it might be something on the developers console that im missing or something i left out or didnt do cuz the game is working fine with the google play services when i build it straight to my phone. so i am wondering if anyone else has experience this. any help appreciated

**Comment by claywilkinson** [comment]
@kylerts - please reopen if you are still having issues.
