### ISSUE TITLE
Friends are not loaded in iOS

### ISSUE THREAD

**Issue by sliterod** [playgameservices/play-games-plugin-for-unity#210]
Hello.
I have a problem with the plugin in iOS.

I need to list all my friends from g+, so I'm using PlayGamesPlatform.Instance.localUser.LoadFriends.
In Android it works just fine, but in iOS it always return false (I even tried Social.Active.localUser.LoadFriends and Social.localUser.LoadFriends).

I wish to know what can I do in this case. Thanks in advance!

**Comment by claywilkinson** [comment]
This has been implemented in version 0.9.25 of the plugin.
