### ISSUE TITLE
Impossible to perform authentication. Can't register class exception

### ISSUE THREAD

**Issue by cyberfox213** [playgameservices/play-games-plugin-for-unity#2100]
I get all this when the app tries to authenticate the user to play games.
I have to add and modify some files in the android project before building the apk because of some requirements my client asked me. So, in Unity, I have to build with Gradle and export the project.
I've seen other people getting this issue and solving it by building the apk right from Unity, but as I said, I can't.
This is what I get from Android Studio's logcat:

02-06 23:21:20.604 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/common/ConnectionResult: an exception occurred.
02-06 23:21:20.604 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/common/GooglePlayServicesUtil: an exception occurred.
02-06 23:21:20.604 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/common/api/Api: an exception occurred.
02-06 23:21:20.604 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/common/api/Api$ApiOptions: an exception occurred.
02-06 23:21:20.604 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/common/api/Api$ApiOptions$HasOptions: an exception occurred.
02-06 23:21:20.605 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/common/api/GoogleApiClient: an exception occurred.
02-06 23:21:20.605 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/common/api/GoogleApiClient$Builder: an exception occurred.
02-06 23:21:20.605 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/common/api/PendingResult: an exception occurred.
02-06 23:21:20.605 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/common/api/Result: an exception occurred.
02-06 23:21:20.605 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/common/api/ResultCallback: an exception occurred.
02-06 23:21:20.606 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/common/data/DataBufferUtils: an exception occurred.
02-06 23:21:20.606 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/Games: an exception occurred.
02-06 23:21:20.607 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/Games$GamesOptions: an exception occurred.
02-06 23:21:20.607 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/Games$GamesOptions$Builder: an exception occurred.
02-06 23:21:20.607 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/Player: an exception occurred.
02-06 23:21:20.607 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/PlayerBuffer: an exception occurred.
02-06 23:21:20.607 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/PlayerLevel: an exception occurred.
02-06 23:21:20.607 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/PlayerLevelInfo: an exception occurred.
02-06 23:21:20.608 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/Players: an exception occurred.
02-06 23:21:20.608 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/Players$LoadPlayersResult: an exception occurred.
02-06 23:21:20.608 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/achievement/Achievement: an exception occurred.
02-06 23:21:20.608 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/achievement/Achievements$LoadAchievementsResult: an exception occurred.
02-06 23:21:20.608 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/event/Event: an exception occurred.
02-06 23:21:20.608 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/event/EventBuffer: an exception occurred.
02-06 23:21:20.609 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/event/Events: an exception occurred.
02-06 23:21:20.609 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/event/Events$LoadEventsResult: an exception occurred.
02-06 23:21:20.609 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/achievement/AchievementBuffer: an exception occurred.
02-06 23:21:20.609 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/achievement/Achievements: an exception occurred.
02-06 23:21:20.609 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/Leaderboard: an exception occurred.
02-06 23:21:20.609 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/LeaderboardBuffer: an exception occurred.
02-06 23:21:20.610 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/Leaderboards: an exception occurred.
02-06 23:21:20.610 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/LeaderboardScore: an exception occurred.
02-06 23:21:20.610 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/LeaderboardScoreBuffer: an exception occurred.
02-06 23:21:20.610 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/LeaderboardVariant: an exception occurred.
02-06 23:21:20.610 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/Leaderboards$LeaderboardMetadataResult: an exception occurred.
02-06 23:21:20.611 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/Leaderboards$LoadScoresResult: an exception occurred.
02-06 23:21:20.611 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Invitation: an exception occurred.
02-06 23:21:20.611 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/InvitationBuffer: an exception occurred.
02-06 23:21:20.611 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Invitations: an exception occurred.
02-06 23:21:20.611 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Invitations$LoadInvitationsResult: an exception occurred.
02-06 23:21:20.611 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Multiplayer: an exception occurred.
02-06 23:21:20.612 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/Participant: an exception occurred.
02-06 23:21:20.612 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/ParticipantResult: an exception occurred.
02-06 23:21:20.612 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/LoadMatchesResponse: an exception occurred.
02-06 23:21:20.612 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatch: an exception occurred.
02-06 23:21:20.612 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchBuffer: an exception occurred.
02-06 23:21:20.612 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchConfig: an exception occurred.
02-06 23:21:20.613 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchConfig$Builder: an exception occurred.
02-06 23:21:20.613 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer: an exception occurred.
02-06 23:21:20.613 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$CancelMatchResult: an exception occurred.
02-06 23:21:20.613 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$InitiateMatchResult: an exception occurred.
02-06 23:21:20.613 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LeaveMatchResult: an exception occurred.
02-06 23:21:20.613 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LoadMatchesResult: an exception occurred.
02-06 23:21:20.613 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LoadMatchResult: an exception occurred.
02-06 23:21:20.614 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$UpdateMatchResult: an exception occurred.
02-06 23:21:20.614 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quest: an exception occurred.
02-06 23:21:20.614 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/quest/QuestBuffer: an exception occurred.
02-06 23:21:20.614 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quests: an exception occurred.
02-06 23:21:20.614 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Milestone: an exception occurred.
02-06 23:21:20.614 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quests$LoadQuestsResult: an exception occurred.
02-06 23:21:20.615 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quests$AcceptQuestResult: an exception occurred.
02-06 23:21:20.615 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/quest/Quests$ClaimMilestoneResult: an exception occurred.
02-06 23:21:20.615 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/Snapshot: an exception occurred.
02-06 23:21:20.616 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/SnapshotContents: an exception occurred.
02-06 23:21:20.616 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/SnapshotMetadata: an exception occurred.
02-06 23:21:20.616 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataBuffer: an exception occurred.
02-06 23:21:20.617 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/Snapshots: an exception occurred.
02-06 23:21:20.617 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/Snapshots$CommitSnapshotResult: an exception occurred.
02-06 23:21:20.617 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/Snapshots$LoadSnapshotsResult: an exception occurred.
02-06 23:21:20.617 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/Snapshots$OpenSnapshotResult: an exception occurred.
02-06 23:21:20.617 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataChange: an exception occurred.
02-06 23:21:20.617 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataChange$Builder: an exception occurred.
02-06 23:21:20.618 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/stats/PlayerStats: an exception occurred.
02-06 23:21:20.618 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/stats/Stats: an exception occurred.
02-06 23:21:20.618 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/stats/Stats$LoadPlayerStatsResult: an exception occurred.
02-06 23:21:20.618 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMessageReceivedListener: an exception occurred.
02-06 23:21:20.618 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMultiplayer: an exception occurred.
02-06 23:21:20.618 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMessage: an exception occurred.
02-06 23:21:20.619 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/Room: an exception occurred.
02-06 23:21:20.619 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RoomConfig: an exception occurred.
02-06 23:21:20.619 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/realtime/RoomConfig$Builder: an exception occurred.
02-06 23:21:20.619 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/nearby/Nearby: an exception occurred.
02-06 23:21:20.619 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/nearby/connection/AppIdentifier: an exception occurred.
02-06 23:21:20.620 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/nearby/connection/AppMetadata: an exception occurred.
02-06 23:21:20.620 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/nearby/connection/Connections: an exception occurred.
02-06 23:21:20.620 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/nearby/connection/Connections$StartAdvertisingResult: an exception occurred.
02-06 23:21:20.620 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/video/CaptureState: an exception occurred.
02-06 23:21:20.620 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/video/VideoCapabilities: an exception occurred.
02-06 23:21:20.620 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/video/Videos: an exception occurred.
02-06 23:21:20.621 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/video/Videos$CaptureAvailableResult: an exception occurred.
02-06 23:21:20.621 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/video/Videos$CaptureCapabilitiesResult: an exception occurred.
02-06 23:21:20.621 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/video/Videos$CaptureStateResult: an exception occurred.
02-06 23:21:20.621 9545-9560/? E/GamesNativeSDK: Can't register class com/google/android/gms/games/video/Videos$CaptureOverlayStateListener: an exception occurred.
02-06 23:21:20.716 9545-9560/? I/Unity: Building GPG services, implicitly attempts silent auth
                                         
                                        (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-06 23:21:20.719 9545-9560/? E/GamesNativeSDK: Could not register one or more required Java classes.
02-06 23:21:20.727 9545-9560/? E/Unity: InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK
                                          at GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build (GooglePlayGames.Native.PInvoke.PlatformConfiguration configRef) [0x00000] in <filename unknown>:0 
                                          at GooglePlayGames.Native.NativeClient.InitializeGameServices () [0x00000] in <filename unknown>:0 
                                          at GooglePlayGames.Native.NativeClient.Authenticate (System.Action`2 callback, Boolean silent) [0x00000] in <filename unknown>:0 
                                          at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`2 callback, Boolean silent) [0x00000] in <filename unknown>:0 
                                          at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`1 callback, Boolean silent) [0x00000] in <filename unknown>:0 
                                          at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`1 callback) [0x00000] in <filename unknown>:0 
                                          at GooglePlayGames.PlayGamesLocalUser.Authenticate (System.Action`1 callback) [0x00000] in <filename unknown>:0 
                                          at SocialAPI.Aute
02-06 23:21:20.813 9545-9579/? E/mono: Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object
                                         at UnityEngine.AndroidJavaObject.Dispose (Boolean disposing) [0x00000] in <filename unknown>:0 
                                         at UnityEngine.AndroidJavaObject.Finalize () [0x00000] in <filename unknown>:0 
02-06 23:21:21.035 9545-9560/? W/Unity: !!! [Play Games Plugin DLL] 02/06/18 23:21:21 +01:00 WARNING: Creating new PlayGamesPlatform
                                         
                                        (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-06 23:21:21.035 9545-9560/? I/Unity:  [Play Games Plugin DLL] 02/06/18 23:21:21 +01:00 DEBUG: Activating PlayGamesPlatform.
                                         
                                        (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-06 23:21:21.035 9545-9560/? I/Unity:  [Play Games Plugin DLL] 02/06/18 23:21:21 +01:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
                                         
                                        (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-06 23:21:21.035 9545-9560/? I/Unity:  [Play Games Plugin DLL] 02/06/18 23:21:21 +01:00 DEBUG: Creating platform-specific Play Games client.
                                         
                                        (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-06 23:21:21.035 9545-9560/? I/Unity:  [Play Games Plugin DLL] 02/06/18 23:21:21 +01:00 DEBUG: Creating Android IPlayGamesClient Client
                                         
                                        (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by cyberfox213** [comment]
I tried adding rules to proguard to keep the classes that GamesNativeSDK can't register, just in case they may be removed by proguard, I tried including the aar com.google.games.gpgs-plugin-support-0.9.50 into the GooglePlayManifest.plugin module, tried forcing resolve into Unity, I also deleted and reimported again the package, forced resolve again, but nothing worked. 
I'm all out of ideas.
Just in case you need this, here are the dependencies added by Unity into the build.gradle file: 
compile fileTree(dir: 'libs', include: ['*.jar'])
	compile(name: 'com.android.support.animated-vector-drawable-25.3.1', ext:'aar')
	compile(name: 'com.android.support.appcompat-v7-25.3.1', ext:'aar')
	compile(name: 'com.android.support.cardview-v7-25.3.1', ext:'aar')
	compile(name: 'com.android.support.customtabs-25.3.1', ext:'aar')
	compile(name: 'com.android.support.support-compat-25.3.1', ext:'aar')
	compile(name: 'com.android.support.support-core-ui-25.3.1', ext:'aar')
	compile(name: 'com.android.support.support-core-utils-25.3.1', ext:'aar')
	compile(name: 'com.android.support.support-fragment-25.3.1', ext:'aar')
	compile(name: 'com.android.support.support-media-compat-25.3.1', ext:'aar')
	compile(name: 'com.android.support.support-v4-25.3.1', ext:'aar')
	compile(name: 'com.android.support.support-vector-drawable-25.3.1', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-auth-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-auth-api-phone-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-auth-api-phone-license-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-auth-base-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-auth-base-license-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-base-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-base-license-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-basement-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-basement-license-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-drive-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-drive-license-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-games-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-games-license-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-nearby-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-nearby-license-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-tasks-11.6.2', ext:'aar')
	compile(name: 'com.google.android.gms.play-services-tasks-license-11.6.2', ext:'aar')
	compile(name: 'com.google.games.gpgs-plugin-support-0.9.50', ext:'aar')
	compile(name: 'facebook-android-sdk-4.23.0', ext:'aar')
	compile(name: 'facebook-android-wrapper-7.10.1', ext:'aar')
	compile project(':GooglePlayGamesManifest.plugin')

Also, I'm using Unity 2017.3.p3.

**Comment by cometa93** [comment]
Same situation here...

**Comment by shimiu** [comment]
I disabled proguard minification then solved this error.
Set `Minify` of Player Settings to `None` or set `minifyEnabled` of gradle template to `false`.

**Comment by andersemil** [comment]
Any resolution? I have minify set to None but the exception still happens here.

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
