### ISSUE TITLE
RealTime Multiplayer Waiting room UI

### ISSUE THREAD

**Issue by sohail003** [playgameservices/play-games-plugin-for-unity#2123]
plz help me how can i implement custom waiting room ui .. is it possible... i want to made my own VS Screen UI and assign Profile pics of both players to Images in Canvas.. how can i do that...  thanks in advance :)

**Comment by justinkmai** [comment]
@sohail003 Sorry for the delay! I didn't receive a notification for your response. To answer your question, this is how I get information for Player 2:

```
// Get self ID
_myParticipantId = GooglePlayMP.Instance.GetMyParticipantId();
// Get all player IDs
List<Participant> playerIDs = GooglePlayMP.Instance.GetAllPlayers();

if(_myParticipantId == playerIDs[0].ParticipantId)
{
     StartCoroutine (LoadImage1 (playerIDs[1].Player.AvatarURL));
}

else
{
     StartCoroutine (LoadImage1 (playerIDs[0].Player.AvatarURL));
}
```

**Comment by srcsameer** [comment]
Did it work? and where should i put this code? inside OnRoomConnected(bool success) returns success?

**Comment by justinkmai** [comment]
Yes, put it in inside if(success){}. LoadImage1 is a function that I took from your code example. To apply it to a GameObject, you would need a reference to it's Image or SpriteRenderer component. So something like this:

Public Image playerAvatar;
playerAvatar.sprite = playerIDs[1].Player.AvatarURL;

I have not tried this so you'll have to test it to see if AvatarURL returns a sprite.

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
