### ISSUE TITLE
libgpg.so for both x86 and arm build

### ISSUE THREAD

**Issue by trsquarelab** [playgameservices/play-games-plugin-for-unity#2124]
Even if I select native platform as ARM I see that libgpg.so is present in lib/x86 build. The same happens when I select platform as X86.

Due to this I am not able to upload two apks in Google Play console. Is there a workaround for this issue?

**Comment by trsquarelab** [comment]
Looks like latest version has the support

**Comment by siadark** [comment]
I have the same problem. where can I disable the x86 support?
