### ISSUE TITLE
Sign in on Android Devide isn't working.

### ISSUE THREAD

**Issue by bekiryanik** [playgameservices/play-games-plugin-for-unity#213]
Hello, 

I have installed the plugin into my game. Something is wrong about singing in. I've added tester account. I am trying to sign in my game but everytime it say, "Failed to sign in. Please check your connection and try again." What could be the problem? I couldn't find the solution.

Regards
Bekir

**Comment by claywilkinson** [comment]
Closing this since the plugin has been re-architected and the call stack is no longer relevant.
