### ISSUE TITLE
RequestIdToken() prompts for user consent every time game is launched.

### ISSUE THREAD

**Issue by aprithul** [playgameservices/play-games-plugin-for-unity#2135]
We are trying to use GPG with Amazon AWS in a Unity game. Our sign code looks like this:

        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
          .RequestEmail()
          .RequestServerAuthCode(false)
          .RequestIdToken()
          .Build();
        PlayGamesPlatform.InitializeInstance(config);

        PlayGamesPlatform.DebugLogEnabled = true;

        PlayGamesPlatform.Activate();

        if (!Social.localUser.authenticated)
        {
            Social.localUser.Authenticate(GoogleLoginCallback);
        }

There are two issues:
1. The game prompts the user with the following consent window everytime the game is launched even when the user has already allowed access:
![20180311_173334](https://user-images.githubusercontent.com/8151229/37252827-8155b6c0-2552-11e8-9f6a-6e26fbadbdc8.png)

2. The other issue is that the ID Token obtained by calling `PlayGamesPlatform.Instance.GetIdToken()` only returns a non-zero length Token on the first call after signing in. Any subsequent call returns a token of length zero. The only way to fix this behaviour is to force the user to log out and then log in again.

**Comment by SantiagoMenelao** [comment]
you can get the token id? @aprithul  ? 
i use unity3d 2017.3 gpgs 0.9.50 and GetTokenID GetUserEmail return empty string y use this code

	public void Login(){
		Social.localUser.Authenticate ((bool success) => {
			if(success){
				Debug.Log("----->>> LOGING SUCCESS!!!");

				string token = PlayGamesPlatform.Instance.GetIdToken();

				string servertoken = PlayGamesPlatform.Instance.GetServerAuthCode();
				statusLog.text = "TOKEN IS: "+token+"\n" +
					"TOKEN AUTH SERVER IS: " + servertoken+ "\n"+
					"USER MAIL"+ PlayGamesPlatform.Instance.GetUserEmail()+"\n"+
					"USER ID: "+PlayGamesPlatform.Instance.GetUserId()+"\n"+
					"USER NAME: "+ Social.localUser.userName ;
					;					
				
				Debug.Log("----->>> /END LOGING SUCCESS!!!");

			}else{
				Debug.Log("----->>> LOGING FAIL MADAFAKA!!!!");

			}
		});
	}

**Comment by aprithul** [comment]
@SantiagoMenelao yes I we get the token ID. Make sure you have added the web client id in the android setup menu. Also I believe there are some requirements, like the apk has to be signed and such; I don’t recall exactly. However we are working on an update to a released app, so those requirements are already met in our case. 

And we have solved the issue by removing the request for server auth code. Although the documentation for AWS mentions that it is required, we’ve found out that the issue gets solved if we do not include the line of code.

**Comment by SantiagoMenelao** [comment]
@aprithul yes i put the client id from api console, and use the apk  signed from play store, the process is very tedious, i need upload the apk in store, and download this to can test, because the api console dont take my signed keystore, take the keystore put by play.....

look 
![image](https://user-images.githubusercontent.com/14896681/37372749-a3ccb0ea-26f2-11e8-8383-20cd5d2e0840.png)
![image](https://user-images.githubusercontent.com/14896681/37372838-fd533b20-26f2-11e8-86f7-bd7254d7a29b.png)

but in true words in play service the app linked to this project have a diferent client id but same app id

![image](https://user-images.githubusercontent.com/14896681/37372898-4217d6a8-26f3-11e8-839a-3b9d13a667d9.png)

other solution than cry? ahahaa

**Comment by SantiagoMenelao** [comment]
the silent login with gpgs run , i can login and the last code i share before, get me the user name and de user id, but nothing about tokens

**Comment by aprithul** [comment]
@SantiagoMenelao You are putting in the Android client ID. You have to create a web client ID for the app and put it in the setup window.

**Comment by SantiagoMenelao** [comment]
@aprithul yes dude! i can resolve it yesterday , now all are running very well! thx for you attention dude!

**Comment by YuliyF** [comment]
In my case : var authCode = PlayGamesPlatform.Instance.GetServerAuthCode(); is still empty...(( I did all it.
Which permissions did you use in your game for getting email and AuthCode ? maybe problem in permissions of manifest
