### ISSUE TITLE
Play Games Services only works if the app is downloaded from the google play

### ISSUE THREAD

**Issue by DevGeroll** [playgameservices/play-games-plugin-for-unity#2146]
Hi everyone.
This is not an issue, but maybe somebody knows how to change this. GPS Authorization works only when app has been uploaded from Google Play. It works fine, but it takes to much time for testing something new. How to optimize this process?

**Comment by JeffersonFerreira** [comment]
Your game crashes if you install locally?

**Comment by DevGeroll** [comment]
No, just can't finish authorizing. 
![image](https://user-images.githubusercontent.com/9340022/37815463-9bca3124-2e77-11e8-8dc3-61bceed0a957.png)

**Comment by fallendos** [comment]
If you use app signing, when apk is uploaded to google play, app signing key is changed.(check GooglePlayConsole - target application - Publish management - app signing).
So you need to make OAuth 2.0 client id with your upload keystore SHA-1.

**Comment by DevGeroll** [comment]
How can i change keystore SHA-1?

**Comment by fallendos** [comment]
No need to change keystore. Just make additional OAuth 2.0 client id.
(https://console.developers.google.com/apis)

**Comment by fallendos** [comment]
Step 2. Unity Google Play Games Setup is option for web app.
If you want to login at google play service without publishing, make OAuth 2.0 client ID with your key at https://console.developers.google.com/apis

**Comment by STENKYGAMES** [comment]
Try to add yourself as a tester in google play services. It works for me.

**Comment by DevGeroll** [comment]
Oh guys, thank you so much!
I used keytool command to get right SHA-1
`keytool -list -printcert -jarfile game.apk`
Then i changed my client identifier SHA-1 to apk SHA-1 and it works fine!
