### ISSUE TITLE
OnLeftRoom() is getting called instead of OnPeersDisconnected(string[] participantIds) 

### ISSUE THREAD

**Issue by ajaybirla** [playgameservices/play-games-plugin-for-unity#215]
My System:

Unity3D Version: 4.5.2f1
Google Play Game Services Plugin Version: 0.9.02 (Package Name: GooglePlayGamesPlugin-0.9.04)

My Issue:

In my game, we have 2 player real time multiplayer game. If any player gets disconnected by clicking on "Abort" button / locks screen / disable WiFi or disconnected by any way then "OnLeftRoom()" is getting called for disconnected player. It is perfectly fine but the problem is for another player, instead of "OnPeersDisconnected(string[] participantIds)", "OnLeftRoom()" is getting called. This is not correct.

Anyone here, who is facing same problem ?

Any response will be greatly appreciated.

**Comment by ajaybirla** [comment]
@ToddKerpelman Please close issue #141 too. it is the same issue.

**Comment by Bulbul108** [comment]
Although @Ipzkl ensure that new version (0.9.11) has fixed the problem, in my case OnPeersDisconnected(string[] participantIds) is not working. But i used version(0.9.02) and worked just fine. 

I has implemented a multiplayer game. When a player disconnected i use a virtual player to take his place until only one player left. This is done by identifying a players disconnection through OnPeersDisconnected(string[] participantIds). It seems like OnPeersDisconnected(string[] participantIds) not called when one or two player disconnected. But if there's only one player left then the game quits as desired. Version (0.9.02) worked according to those conditions. 

Any response will be greatly appreciated.
@ToddKerpelman
