### ISSUE TITLE
How to get non-cached achievement info with this plugin?

### ISSUE THREAD

**Issue by ishidyus** [playgameservices/play-games-plugin-for-unity#2156]
I created a 5 steps incremental achievement in play console, and got it by unity sample game with this plugin.

https://github.com/playgameservices/management-tools

In this web tool, I reset the achievement and the steps column shows 0/5, it is correct.

But with this plugin and show achievement info by using Social.ShowAchievementsUI(), it showed 5/5.
When some time passed, it was reset and showed 0/5, and I think there is something cache.

I want to get the newest, non-cached, achievement info after reset it.

Though I don't know this is an issue or not, I was wondering if anyone could tell me any solutions.

Environment
OS:Windows10 64bit
plugin version: 0.9.50
Unity version:2017.3.1f1

**Comment by hak** [comment]
Checked the issue and verified that rebooting a device would initiate a sync to the latest status.
I would admit this wouldn't be a sophisticated way to sync a status but please go with that for now.
