### ISSUE TITLE
Where to download Andorid Support Library 

### ISSUE THREAD

**Issue by francescomaiolani** [playgameservices/play-games-plugin-for-unity#2158]
Sorry guys if it's a dumb question but i've already implemented the play services system and discovered that it didn't work because i forgot the Android Support Library part.
But after serching in the issues and googling for some quick answers i couldn't understand where i can download the Android Support Library and how to insert it in my unity game. Sorry for the dumb question.

**Comment by Noah1911** [comment]
This should be done automatically via Unity Jar Resolver. Try to click on "Assets>Play Games Resolver>Android Resolver>Resolve/Force Resolve" in the menu bar.
