### ISSUE TITLE
Sign in problem Android

### ISSUE THREAD

**Issue by sliterod** [playgameservices/play-games-plugin-for-unity#216]
Hello. Lately I have some problems when I want to sign in on any Android device.
Even after upgrading the plugin, the error is still there. This is what it says: 
"Unable to retrieve application xxxxxxxxxxxx from network.
Application ID xxxxxxxxxxxx is not associated with package com.company.game. Check the application ID in your manifest."

And the console output says:
09-03 17:57:17.980: I/Unity(9048): [Play Games Plugin DLL] GHM/GameHelperListener got onSignInFailed, origin 1001, notifying GHM.
09-03 17:57:17.980: I/Unity(9048):  
09-03 17:57:17.980: I/Unity(9048): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
09-03 17:57:17.980: I/Unity(9048): [Play Games Plugin DLL] GHM got onSignInFailed, origin 1001, notifying AndroidClient.
09-03 17:57:17.980: I/Unity(9048):  
09-03 17:57:17.980: I/Unity(9048): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
09-03 17:57:17.980: I/Unity(9048): [Play Games Plugin DLL] GHM got onSignInFailed from Sign In Helper. Showing error message.
09-03 17:57:17.980: I/Unity(9048):  
09-03 17:57:17.980: I/Unity(9048): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
09-03 17:57:18.097: I/Unity(9048): [Play Games Plugin DLL] Error message shown.
09-03 17:57:18.097: I/Unity(9048):  
09-03 17:57:18.097: I/Unity(9048): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
09-03 17:57:18.097: I/Unity(9048): [Play Games Plugin DLL] AndroidClient got OnSignInFailed.
09-03 17:57:18.097: I/Unity(9048):  
09-03 17:57:18.097: I/Unity(9048): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
09-03 17:57:18.097: I/Unity(9048): [Play Games Plugin DLL] AUTH: FAILED!
09-03 17:57:18.097: I/Unity(9048):  
09-03 17:57:18.097: I/Unity(9048): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
09-03 17:57:18.097: I/Unity(9048): [Play Games Plugin DLL] AUTH: Calling auth callback: success=False
09-03 17:57:18.097: I/Unity(9048):  
09-03 17:57:18.097: I/Unity(9048): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)

09-03 17:57:30.363: I/Unity(9048): [Play Games Plugin DLL] GHM/GameHelperListener got onSignInFailed, origin 1000, notifying GHM.
09-03 17:57:30.363: I/Unity(9048): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
09-03 17:57:30.378: I/Unity(9048): [Play Games Plugin DLL] GHM got onSignInFailed, origin 1000, notifying AndroidClient.
09-03 17:57:30.378: I/Unity(9048): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
09-03 17:57:30.378: I/Unity(9048): [Play Games Plugin DLL] AndroidClient got OnSignInFailed.
09-03 17:57:30.378: I/Unity(9048): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
09-03 17:57:30.378: I/Unity(9048): [Play Games Plugin DLL] Normal OnSignInFailed received.

I know that the tester accounts are not the problem, because in iOS I can sign in without problems.

Any idea of what can I do? Thanks in advance.

**Comment by claywilkinson** [comment]
Closing.  Please open a new issue if this is unresolved.

**Comment by karthikeyan001** [comment]
Remove all account in Gmail except one account for testing purpose then check that working
