### ISSUE TITLE
( 0.95, unity2017.3  and 2017.4 , Net4.6 ) RealtimeMultiplayer OnConnectedRoom() Always Fail.

### ISSUE THREAD

**Issue by alpsaltera** [playgameservices/play-games-plugin-for-unity#2161]
i'have all settings in DeveloperConsol.

Authenticate is Success.

And i Call CreateQuickGame() same with samplecode.

but OnCreateRoom() always return Fail.

thanks.

**Comment by Huyaki** [comment]
same problem here

**Comment by oxoxocheck** [comment]
Same problem i have

**Comment by Huyaki** [comment]
someone should write email to google

**Comment by oxoxocheck** [comment]
Lets do it everybody.Realy,i tryed just all,what possible.More,i created a new project and add new game at developer console.All is working,but multipleet not.It is 100% google play games services problem

**Comment by oxoxocheck** [comment]
Early multipleel worked,after it worked only by mobile internet,after just noo

**Comment by Huyaki** [comment]
i ll leave them message too

**Comment by alpsaltera** [comment]
// oxoxocheck  // what is mean? you can OnConnectRoom()? i was tested on mobile. In mobile also FAIL.

**Comment by oxoxocheck** [comment]
@alpsaltera No. Some 15 days ago everything worked fine. After multiplayer worked only on a mobile network (I do not know why). And about 5 days ago, multiplayer stopped working. OnRoomConnected instantly returns false, OnRoomSetup (float percent) is not called at all. In general, all like everyone else.

**Comment by oxoxocheck** [comment]
//alpsaltera //No. Some 15 days ago everything worked fine. After multiplayer worked only on a mobile network (I do not know why). And about 5 days ago, multiplayer stopped working. OnRoomConnected instantly returns false, OnRoomSetup (float percent) is not called at all. In general, all like everyone else.

**Comment by Huyaki** [comment]
i am from latvia

**Comment by oxoxocheck** [comment]
Ooooo!!I dont know what happened,but now in is working!!!!!!

**Comment by oxoxocheck** [comment]
With out vpn!!!

**Comment by oxoxocheck** [comment]
What about you,guys?

**Comment by Huyaki** [comment]
yeah looks like it works now. спасибо за хорошие новости, охохочек ;)

**Comment by oxoxocheck** [comment]
Yeah,thanks

**Comment by alpsaltera** [comment]
VPN? what's mean? 

is it android phone VPN application?

**Comment by alpsaltera** [comment]
i'm also fail. but i will try to more at night. thanks.

**Comment by oxoxocheck** [comment]
Not phone application.I downloaded VPN application from Play Market

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
