### ISSUE TITLE
Real Time Multiplayer doesn't work! Do not create a room!

### ISSUE THREAD

**Issue by AlexGames73** [playgameservices/play-games-plugin-for-unity#2163]
Hello!

I had a problem: I decided to write multiplayer for my game through Google services, I already wrote the authentication, it passes successfully, wrote the creation of the room through `CreateQuickGame()`, inherited the current class from `RealTimeMultiplayerListener` implemented `OnRoomSetupProgress`, `OnRoomConnected` functions. So, after successful authentication, the room is not created, but immediately tries to connect and calls `OnRoomConnected (false)` ignoring `OnRoomSetupProgress ()`. All services are configured, the version is embedded in the alpha, the services are published. Google services includes the Realtime Multiplayer feature. The rest of the services all work, already wrote the save to the cloud. Tell me what to do, I will be very grateful to you.

> This is a test scene and there is nothing except this script and Google services on it.

![image](https://user-images.githubusercontent.com/12066736/38172334-99b8f21c-35bb-11e8-8ec6-380773d4476e.png)

> Added the current time from the computer during the command call, so you understand that the function `CreateQuickGame()` does not even try to create a room.

![image](https://user-images.githubusercontent.com/12066736/38172220-29665a92-35b9-11e8-8931-15dd15a7c8c2.png)

> The game along with the services are published in the alpha version.

![image](https://user-images.githubusercontent.com/12066736/38172271-3bbc3e9a-35ba-11e8-958f-2cafa423b709.png)

## play-games-plugin-for-unity 0.9.50

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
