### ISSUE TITLE
Real-Time Multiplayer connection issues

### ISSUE THREAD

**Issue by justinkmai** [playgameservices/play-games-plugin-for-unity#2166]
I'm not sure what is causing this since it seemed to work fine just a few weeks ago, but lately my players have been unable to connect to an online multiplayer match. When CreateQuickGame is called, there should be a callback to OnRoomSetupProgress followed by OnRoomConnected, but for some reason it will enter ShutdownState instead of ConnectingState. As a result, OnRoomSetupProgress is never called. I have occasionally experienced this on my end as well and usually restarting the phone will resolve the issue but it has not worked for my players. Below are two screens where one connection is successful but not the other:

Connection is successful
![screenshot_20180404-112429](https://user-images.githubusercontent.com/12648475/38335933-f6d6a42a-3814-11e8-8a0f-ff8a178f0ccd.png)
Connection fails
![screenshot_20180404-112018](https://user-images.githubusercontent.com/12648475/38335932-f6bbf2ec-3814-11e8-9ae9-50d0c9afc0d2.png)

Plugin version: 0.9.40
Unity version: 2017.3.1p3

**Comment by oxoxocheck** [comment]
I have same problem!! I find a questions above 5 days and! Many same asked on GitHub,but nooo questions!!!Whyy??

**Comment by jojays** [comment]
Yeah I have exactly the same problem. Everything worked fine until yesterday. Now roomcreation always fails

**Comment by Huyaki** [comment]
same problem here

**Comment by WilianZilv** [comment]
Same! =/

**Comment by WindyKeeper** [comment]
Likewise. It's very frustrating.

**Comment by deboshir2** [comment]
same error on : galaxy S6, Mi5S;
normal : nexus 7, lg x power;

**Comment by olehkuznetsov** [comment]
deboshir2, your issue could be similar to [#2226](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2226)
