### ISSUE TITLE
Op: SIGN_IN status: ERROR_NOT_AUTHORIZED on Android 8.0

### ISSUE THREAD

**Issue by wenderRondonia** [playgameservices/play-games-plugin-for-unity#2167]
Stopped working after I updated some days ago GPGS plugin, Android 8 devices can't login raising the error. I checked the certificates and everything seems right.  What directions should I take to solve this issue?

I am using :
GooglePlayGamesPlugin-0.9.50
play-services-resolver_v1.2.61.0
facebook-unity-sdk-7.11.1
GoogleMobileAds
Unity-2017.3.1f1

**Comment by wenderRondonia** [comment]
Here is the log before the signing fails, all other versions of android works, only api 26 fails to authorize using silent login.

4-10 14:54:04.662 I/Unity   (2438): Building GPG services, implicitly attempts silent auth
04-10 14:54:04.662 I/Unity   (2438):  
04-10 14:54:04.662 I/Unity   (2438): (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
04-10 14:54:04.662 I/Unity   (2438): 
04-10 14:54:04.664 E/AudioStreamOutSink(326): Error while writing data to HAL: -32
04-10 14:54:04.670 I/GamesNativeSDK(2438): Using existing jar.
04-10 14:54:04.670 I/GamesNativeSDK(2438): Writing 1941 bytes to jar file
04-10 14:54:04.672 I/chromium(2438): [INFO:library_loader_hooks.cc(140)] Chromium logging enabled: level = 0, default verbosity = 0
04-10 14:54:04.672 I/cr_LibraryLoader(2438): Expected native library version number "58.0.3029.125", actual native library version number "58.0.3029.125"
04-10 14:54:04.679 W/zygote  (2438): Skipping duplicate class check due to unrecognized classloader
04-10 14:54:04.700 I/GamesNativeSDK(2438): Using existing jar.
04-10 14:54:04.700 I/GamesNativeSDK(2438): Writing 1066 bytes to jar file
04-10 14:54:04.713 W/zygote  (2438): Skipping duplicate class check due to unrecognized classloader
04-10 14:54:04.717 E/AudioStreamOutSink(326): Error while writing data to HAL: -32
04-10 14:54:04.724 E/GamesNativeSDK(2438): Exception in com/google/android/gms/common/api/GoogleApiClient$Builder.build: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference.
04-10 14:54:04.724 E/GamesNativeSDK(2438): Failed to create GoogleApiClient from builder.
04-10 14:54:04.724 I/GamesNativeSDK(2438): Auth operation started: SIGN IN
04-10 14:54:04.724 I/GamesNativeSDK(2438): Connecting to Google Play...
04-10 14:54:04.724 E/GamesNativeSDK(2438): Not authorizing: no client.

**Comment by wenderRondonia** [comment]
Found the issue related to EnablePopUps and silent login #2078 
Commenting the line EnablePopUps solves the issue!

**Comment by drallcom3** [comment]
Can confirm. Spent the whole day looking for a solution.

This DOESN'T work on Android 8+9, but it does work on 7:
`.EnableHidePopups()`

Removing it makes the app work on all Android versions, including 8+9.

**Comment by olehkuznetsov** [comment]
Should be fixed in 0.9.55
