### ISSUE TITLE
Crash GooglePlayService & Firebase

### ISSUE THREAD

**Issue by Jacuos** [playgameservices/play-games-plugin-for-unity#2168]
It's a fresh duplicate of issue "Crash GooglePlayService & Firebase #1624". Calling PlayGamesPlatform.Instance.Authenticate() causes immediate crash.

The crash came back with gpgs 11.8.0 and Firebase SDK 4.5.0 (.aars like : com.google.firebase.firebase-analytics-11.8.0.aar)
![crash2](https://user-images.githubusercontent.com/9453259/38419082-4f8878b0-399f-11e8-82c6-eb4c7a74a4f3.png)

**Comment by defic** [comment]
What plugin files were those exactly? I am having similar issues with the latest Firebase and Google Play Games.
