### ISSUE TITLE
realtime multiplayer quickmatch always fails

### ISSUE THREAD

**Issue by Huyaki** [playgameservices/play-games-plugin-for-unity#2169]
GPS version 0.9.50, tried on Unity versions 2017.2, 5.6.4, 5.0.0;

QuickMatch fails - OnRoomConnected always returns false with error code -2 (INTERNAL_ERROR).
Tried on device and Android emulator multiple instances, same problem everywhere.
Realtime multiplayer is enabled in Google Play Console. Game application is "Ready for testing".
Sometimes when app is launched for the first time, quickmatch succeeds, but next attempt (on second device) fails, and then first device on retry fails too.

Seems many people are having this issue last week(s). Maybe something happened with google's backend?

Anyone have ideas?

**Comment by WilianZilv** [comment]
Same here! Also, is your invitation system working? I'm having a problem with invitations too, OnInvitationReceived callback isn't being called when a invitation is sent.

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
