### ISSUE TITLE
GPGS real-time multipleer dont work in my region.

### ISSUE THREAD

**Issue by oxoxocheck** [playgameservices/play-games-plugin-for-unity#2170]
Hello.I using gpgs in my game and last time when i try to create quick room it return me false(created failed).But when i use vpn and connect to Germany server   
room created succsesfull!!

What i must do that real-time multipleer works in all regions??include my region?

Pls!!Any ideas?

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
