### ISSUE TITLE
Resolver replaces .aar with a folder on macOS

### ISSUE THREAD

**Issue by AdriaandeJongh** [playgameservices/play-games-plugin-for-unity#2173]
On MacOS 10.13.4 in Unity 2017.4.1f1, the resolver doesn't copy gpgs-plugin-support-0.9.42.aar from the cache but instead creates a folder named 'gpgs-plugin-support-0.9.42' with a bunch of files in it. My builds are failing with unknown errors (while compiling with IL2CPP) and I'm thinking it's probably because of this. 

Any ideas?

**Comment by LoungeKatt** [comment]
If you have the aar in the Plugin/Android folder as well, you could always try deleting the folder. I have never really trusted the automated install processes from these scripts. On Mac, they have always been buggy at best. 
I use an older version of Google Play Games (as required by my own plugins) and the automated process attempted to install new versions of GPSG and support right alongside the existing ones with no warning or cleanup.

**Comment by AdriaandeJongh** [comment]
The moment I put the original .aar file back in the plugin folder, the resolver deletes it again, so.... that’s not a solution unfortunately.

**Comment by AdriaandeJongh** [comment]
Still seeing this issue on mac. Fingers 🤞 crossed Google will look at this issue.
