### ISSUE TITLE
Multiplayer and Invitation system not working!

### ISSUE THREAD

**Issue by WilianZilv** [playgameservices/play-games-plugin-for-unity#2177]
OnRoomSetupProgress() and OnInvitationReceived() is never called.
What is happening? It's been like 15 days and nothing.

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
