### ISSUE TITLE
iOS 8 welcome back banner

### ISSUE THREAD

**Issue by sliterod** [playgameservices/play-games-plugin-for-unity#219]
Hello, I'm testing now a game in iOS 8.
The game is always landscape and while in iOS 7 the welcome banner after sign in shows landscape as the game is, in iOS 8 the banner shows as if the game was portrait.

Do you have a fix for this? Thanks in advance.

**Comment by claywilkinson** [comment]
This is fixed in version 0.9.20 with C++ SDK 1.4.1
