### ISSUE TITLE
Do I have to be worried about GDPR using Play Games service?

### ISSUE THREAD

**Issue by aratn0n** [playgameservices/play-games-plugin-for-unity#2193]
Hi, I've been searching about GDPR for the Play Games service, but I couldn't find any information about it. 

Do I have to request users consent before asking them to sign in to the Play Games service?

**Comment by SeanLangre** [comment]
I want to know this aswell.

**Comment by litemesa** [comment]
I would like to know this too.

**Comment by crobengames** [comment]
I got question about this too. How can I delete user data if a user from EU requested it?

**Comment by olehkuznetsov** [comment]
Thank you for your question.


Google Play Games Services (GPGS) complies with GDPR, and we inform users when they create or modify a Gamer ID that we share gameplay data with developers so they can provide and improve their games. As a game developer, you’re responsible for ensuring your own GDPR compliance, especially if you use or save data for purposes other than providing or improving the game. You may also wish to review the GPGS Terms of Service, which includes other restrictions and requirements around your use of GPGS.

Users can view and delete their data for an individual game in the Play Games App (Android Settings -> Google -> Play Games -> Your Data -> Delete Play Games account & data -> Delete individual game data).
