### ISSUE TITLE
post score after google leaderboard not open.some game working.all plugin up to date.

### ISSUE THREAD

**Issue by karanvariya** [playgameservices/play-games-plugin-for-unity#2197]
i try this soluation but not working.
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1135

See my full Logcat Step by step 

///********Game Service Login ***************//

05-12 17:59:28.637 17146-17173/? D/GamesUnitySDK: Performing Android initialization of the GPG SDK
05-12 17:59:28.683 17146-17173/? I/Unity: Building GPG services, implicitly attempts silent auth
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:29.151 17146-17173/? I/Unity: Failed to fetch IAP catalog due to unexpected http status code, attempting to use cache
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:29.182 17146-17173/? I/UnityIAP: Starting in-app billing setup.
05-12 17:59:29.209 17146-17146/? I/UnityIAP: Billing service connected.
05-12 17:59:29.211 17146-17407/? I/UnityIAP: invoking callback
    Checking for in-app billing 3 support.
05-12 17:59:29.222 17146-17407/? I/UnityIAP: In-app billing version 3 supported for com.phoenixgames.boomduetdots
05-12 17:59:29.236 17146-17407/? I/UnityIAP: Subscriptions AVAILABLE.
05-12 17:59:29.244 17146-17173/? W/Unity: !!! [Play Games Plugin DLL] 05/12/18 17:59:29 +05:30 WARNING: Creating new PlayGamesPlatform
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:29.244 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:29 +05:30 DEBUG: Creating platform-specific Play Games client.
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
     [Play Games Plugin DLL] 05/12/18 17:59:29 +05:30 DEBUG: Creating Android IPlayGamesClient Client
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:29.246 17146-17407/? I/UnityIAP: VR supported.
05-12 17:59:29.247 17146-17407/? I/UnityIAP: onIabSetupFinished: 0
    Requesting 1 products
05-12 17:59:29.248 17146-17407/? I/UnityIAP: QueryInventory: 1
    invoking callback
    Querying owned items, item type: inapp
    Package name: com.phoenixgames.boomduetdots
05-12 17:59:29.249 17146-17407/? I/UnityIAP: Calling getPurchases with continuation token: null
05-12 17:59:29.261 17146-17407/? I/UnityIAP: Owned items response: 0
    Continuation token: null
    Querying SKU details.
05-12 17:59:29.284 17146-17407/? I/UnityIAP: Querying owned items, item type: subs
    Package name: com.phoenixgames.boomduetdots
    Calling getPurchases with continuation token: null
05-12 17:59:29.477 17146-17407/? I/UnityIAP: Owned items response: 0
    Continuation token: null
    Querying SKU details.
05-12 17:59:29.496 17146-17407/? I/UnityIAP: onQueryInventoryFinished: true
    Inventory refresh successful. (response: 0:OK)
05-12 17:59:29.550 17146-17173/? I/Unity: UnityIAP: Promo is ready
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:31.692 17146-17146/? D/AdsUnity: Calling show() on Android
05-12 17:59:31.895 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:31 +05:30 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:31.946 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:31 +05:30 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
     [Play Games Plugin DLL] 05/12/18 17:59:31 +05:30 DEBUG: Populating User
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:31.982 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:31 +05:30 DEBUG: Found User: [Player: 'LavenderWarrior90836' (id g04663690153194664182)]
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:31.983 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:31 +05:30 DEBUG: Maybe finish for User
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:31.984 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:31 +05:30 DEBUG: Auth not finished. User=[Player: 'LavenderWarrior90836' (id g04663690153194664182)] achievements=
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:32.002 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:32 +05:30 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:32.014 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:32 +05:30 DEBUG: Populating Achievements, status = VALID
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:32.029 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:32 +05:30 DEBUG: Found 0 Achievements
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:32.030 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:32 +05:30 DEBUG: Maybe finish for Achievements
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
     [Play Games Plugin DLL] 05/12/18 17:59:32 +05:30 DEBUG: Auth finished. Proceeding.
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
     [Play Games Plugin DLL] 05/12/18 17:59:32 +05:30 DEBUG: Invoking Callbacks: System.Action`2[System.Boolean,System.String]
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:32.072 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:32 +05:30 DEBUG: Invoking user callback on game thread
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
     [Play Games Plugin DLL] 05/12/18 17:59:32 +05:30 DEBUG: LoadScores, board=GooglePlayGames.PlayGamesLeaderboard callback is System.Action`1[System.Boolean]
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:33.802 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:33 +05:30 DEBUG: Entering internal callback for LeaderboardManager#InternalFetchCallback
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:34.451 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:34 +05:30 DEBUG: Entering internal callback for LeaderboardManager#InternalFetchSummaryCallback
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:35.238 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:35 +05:30 DEBUG: Entering internal callback for LeaderboardManager#InternalFetchScorePage
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:35.260 17146-17173/? I/Unity: Setting leaderboard from: [LeaderboardScoreData: mId=CgkIr9ejyJoEEAIQAQ,  mStatus=Success, mApproxCount=0, mTitle=High Score]
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 17:59:35.270 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 17:59:35 +05:30 DEBUG: Invoking user callback on game thread
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

///********Show Achivement UI ***************//

05-12 18:01:06.588 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 18:01:06 +05:30 DEBUG: ShowAchievementsUI callback is 
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 18:01:06.594 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 18:01:06 +05:30 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 18:01:06.599 17146-17173/? D/NativeBridgeActivity: Launching bridge activity: parent:net.sanukin.OverrideUnityActivity@354e5da intent Intent { act=com.google.android.gms.games.VIEW_ACHIEVEMENTS dat=version:12211000 flg=0x4000000 pkg=com.google.android.play.games (has extras) }

///********Show Leaderboard UI ***************//

05-12 18:01:45.205 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 18:01:45 +05:30 DEBUG: ShowLeaderboardUI with default ID
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 18:01:45.206 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 18:01:45 +05:30 DEBUG: ShowLeaderboardUI, lbId= callback is 
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 18:01:45.216 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 18:01:45 +05:30 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 18:01:45.217 17146-17173/? D/NativeBridgeActivity: Launching bridge activity: parent:net.sanukin.OverrideUnityActivity@354e5da intent Intent { act=com.google.android.gms.games.VIEW_LEADERBOARDS dat=version:12211000 flg=0x4000000 pkg=com.google.android.play.games (has extras) }

///********Post Leaderboard Score ***************//

05-12 18:02:27.080 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 18:02:27 +05:30 DEBUG: ReportScore: score=3, board=CgkIr9ejyJoEEAIQAQ
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
     [Play Games Plugin DLL] 05/12/18 18:02:27 +05:30 DEBUG: Native Submitting score: 3 for lb CgkIr9ejyJoEEAIQAQ with metadata: 
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 18:02:27.092 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 18:02:27 +05:30 DEBUG: Invoking user callback on game thread
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

///********Show Again Leaderboard UI But this time not show leaderboard ***************//

05-12 18:03:19.174 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 18:03:19 +05:30 DEBUG: ShowLeaderboardUI with default ID
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 18:03:19.175 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 18:03:19 +05:30 DEBUG: ShowLeaderboardUI, lbId= callback is 
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 18:03:19.190 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 18:03:19 +05:30 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 18:03:19.191 17146-17173/? D/NativeBridgeActivity: Launching bridge activity: parent:net.sanukin.OverrideUnityActivity@354e5da intent Intent { act=com.google.android.gms.games.VIEW_LEADERBOARDS dat=version:12211000 flg=0x4000000 pkg=com.google.android.play.games (has extras) }
05-12 18:03:23.686 17146-17146/? D/GamesUnitySDK: Forwarding OnActivityResult
05-12 18:03:23.710 17146-17146/? D/GamesUnitySDK: Forwarding OnActivityResult Finished
05-12 18:03:23.827 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 18:03:23 +05:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 18:03:23.828 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 18:03:23 +05:30 DEBUG: Showing UI Internal callback: ERROR_NOT_AUTHORIZED
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-12 18:03:23.837 17146-17173/? I/Unity:  [Play Games Plugin DLL] 05/12/18 18:03:23 +05:30 DEBUG: Invoking user callback on game thread
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
     [Play Games Plugin DLL] 05/12/18 18:03:23 +05:30 DEBUG: Received UI callback: ERROR_NOT_AUTHORIZED
     
    (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

I hope you have got all the relevant information to look into this issue. Thanks in advance. :D :D

**Comment by karanvariya** [comment]
I don't know.why my leaderboard not working.but again 2 or more time Game Service create then this working.Please below step follow.

Please Follow Step to Connection Between  GameService And Google Console.

Step 1 >>>>>
Google Console App Create

Step 2 >>>>>>
Release Apk Save In Draft(no need to publish.just save as draft)

Step 3 >>>>>>
Game Service App Create

Step 4 >>>>>>
Connection Between Game Service And Google Console
-Linked App 

![capture](https://user-images.githubusercontent.com/36916495/39992318-05174d24-5790-11e8-86e1-2eccd768763f.PNG)

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::Please Note :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
For Testing Purpose >>>>
use Upload SHA-1 certificate fingerprint

For Realse Purpose >>>>>
use App signing SHA-1 certificate fingerprint
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Step 5 >>>>>>
Create Achievement And Leaderboard

Step 6 >>>>>>
Add tester In Testing App

Step 7 >>>>>>
Publish Game Service

**Comment by brt94** [comment]
If helps anyone my problem was the pause menu

Time.timescale must be 1 or more 

` public void ReloadScene()
    {
        Time.timeScale = 1;
        GooglePlayGames.PlayGamesPlatform.Activate();
        PlayGamesPlatform.Instance.ReportScore(Convert.ToInt64(GetComponent<ColisionManager>().score), playgames.leaderboard_world_leader_board, (bool success) => {

            if (success)
            {
                UnityEngine.SceneManagement.SceneManager.LoadScene(1);
            }
            else
            {
                Application.Quit();
            }
        });

    }`
