### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by shay4545** [playgameservices/play-games-plugin-for-unity#220]
I keep getting this error when buiding for android:
Error building Player: Win32Exception: ApplicationName='C:\Program Files (x86)\Java\jre7\bin\javac.exe', CommandLine='-bootclasspath "C:/Program Files (x86)/Android SDK/adt-bundle-windows-x86_64-20140702/sdk/platforms/android-20\android.jar" -d "C:\Users\Shay\Documents\FlappyBirdTest\Temp\StagingArea\bin\classes" -source 1.6 -target 1.6 -encoding UTF-8 "com\google\example\games\basegameutils\R.java" "com\google\example\games\mainlibproj\R.java" "com\google\services\gms\R.java" "com\ShadowKingdomStudios\ChickenWings\R.java"', CurrentDirectory='C:\Users\Shay\Documents\FlappyBirdTest\Temp\StagingArea\gen'

That is the full error. I have been searching for days on how to fix them and nothing has worked. Hopefully someone here knows how to fix it.

**Comment by claywilkinson** [comment]
Thanks for the details -- I'll pass along the request for the statue :)
