### ISSUE TITLE
App crashes on Social.localUser.Authenticate Unity 2018.2.0b4

### ISSUE THREAD

**Issue by phuongle0205** [playgameservices/play-games-plugin-for-unity#2208]
Hi,
my app crashes on Android when i try to authenticate a user.

public void Start () {

	PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder ()
		.Build ();

	PlayGamesPlatform.DebugLogEnabled = true;

	PlayGamesPlatform.InitializeInstance (config);
	PlayGamesPlatform.Activate ();

	SignIn ();

}
	

public void SignIn()
{
	PlayGamesPlatform.Instance.localUser.Authenticate ((bool success) =>
		{
			if(success)
			{
				Debug.Log("Signed In");
			}else{
				Debug.Log("Sign in failed");
			}
	});
}
}

Play Games Plugin 0.9.50
Unity 2918.2.0b4

Thanks in advance for any help in advance to resolve this issue!

**Comment by Neecko** [comment]
Having the same issue. Losing my mind trying to figure it out.

**Comment by phuongle0205** [comment]
installing another version

**Comment by alaukikharsh** [comment]
same here losing my patience. Tell if anyone gets the solution

**Comment by Fim1am** [comment]
Unity 2018.2.5f1 same issue :( help pls

**Comment by Saltiyx** [comment]
I have the same issue

**Comment by Mikecoon** [comment]
Faced this trouble as well. Didn't find any solution.

**Comment by rohan31f** [comment]
I had the same problem, however this issue is solved in the plugin ver 0.9.52.

As per changelog :: 

> Version 0.9.52
    Bug Fixes:
      #2319 Not Working with Unity 2018.2

**Comment by Nameelee** [comment]
Wow. I should have search this keyword earlier! 
I got same trouble. And I fixed. 

Mine was like this. 
Unity version: 2018.2.13f1
GooglePlayGames plug-in version:0.9.61

then, I read this page and I changed GoogolePlayGames plug-in version into  0.9.53. 

Now it works!

Thank you.

**Comment by DimoNline** [comment]
Same trouble, 2019.1.8, not works with GoogolePlayGames 0.9.53.
