### ISSUE TITLE
Resolving Android Dependencies Freezes and Fails

### ISSUE THREAD

**Issue by Sorgon** [playgameservices/play-games-plugin-for-unity#2218]
After fresh installation of playgameservices I got stuck with the Android Dependency resolving screen:
![image](https://user-images.githubusercontent.com/20240351/41024618-06e6656c-6970-11e8-9ec5-c962ef497d53.png)

When I close it and start again from Assets->Resolver... ->Force Resolve, I end up with Resolution failure:

`e:11.6.2
com.google.android.gms:play-services-auth-base-license:11.6.2
com.google.android.gms:play-services-auth-base:11.6.2
com.google.android.gms:play-services-auth:11.6.2
com.google.android.gms:play-services-base-license:11.6.2
com.google.android.gms:play-services-base:11.6.2
com.google.android.gms:play-services-basement-license:11.6.2
com.google.android.gms:play-services-basement:11.6.2
com.google.android.gms:play-services-drive-license:11.6.2
com.google.android.gms:play-services-drive:11.6.2
com.google.android.gms:play-services-games-license:11.6.2
com.google.android.gms:play-services-games:11.6.2
com.google.android.gms:play-services-nearby-license:11.6.2
com.google.android.gms:play-services-nearby:11.6.2
com.google.android.gms:play-services-tasks-license:11.6.2
com.google.android.gms:play-services-tasks:11.6.2
com.google.games:gpgs-plugin-support:0.9.50@srcaar

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.ResolverVer1_1:LogMissingDependenciesError(List`1)
GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey18:<>m__26(List`1)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__1F(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__28()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()`

**Comment by Sorgon** [comment]
Solution:
Delete folders: GooglePlayGames, PlayServicesResolver, Plugins/Android
Create folder: Plugins/Android
If you have opened Visual Studio click reload solution in the new window
check if deleted folders have not renewed and delete them and go to visual studio reload
import googleplayservices package
Window -> Google Play Games -> Setup -> Android Setup -> Setup
Assets -> Play Services Resolver -> Android Resolver -> Force Resolve

**Comment by nikunjkareliya** [comment]
This problem still persists. 
I'm facing a problem after google admob plugin is imported.

Resolving Android Dependencies - dialog doesn't disappear.

I tried with - Assets -> Play Services Resolver -> Android Resolver -> Force Resolve

but this is not working in my case

**Comment by AbbasNarimani** [comment]
If you want to use Google play services and Firebase and you have problem with Android resolver, you can change the build type to Gradle and it would solve your problem. For building in Gradle build sytem, you need to be Connected to the internet for the first time. For those who might be restricted by Google it could be resolved by using a VPN during building proccess. This solved my problem. hope it could be helpful.

**Comment by deepanshu9549** [comment]
Here's the solution that worked for me 
![Capture](https://user-images.githubusercontent.com/78678321/109931015-511f5280-7cee-11eb-9af4-97b94ec59ad7.PNG)

check both the checkboxes I checked under Build Tab.

**Comment by M-Ansley** [comment]
> Here's the solution that worked for me ![Capture](https://user-images.githubusercontent.com/78678321/109931015-511f5280-7cee-11eb-9af4-97b94ec59ad7.PNG)
> 
> check both the checkboxes I checked under Build Tab.

Thank you @deepanshu9549! This helped me too with some AppsFlyer and EDM4U compilation errors I was getting on Android. A little more specifically, I was getting some warnings like: 

`PlayServicesResolver.cs(line 989): Failed to fetch the following dependencies`

and 

`PlayServicesResolver.cs(line 989): Failed to parse previous resolution state, running resolution... `
