### ISSUE TITLE
2 and 3 opponents cannot join the same room in RealTime CreateQuickGame at min/maxOpponents=1/3

### ISSUE THREAD

**Issue by deboshir2** [playgameservices/play-games-plugin-for-unity#2222]
Settings for all players:
`MinOpponents = 1; MaxOpponents = 3; GameVariant = 0;`

1. Player CreateQuickGame;
2. First opponent CreateQuickGame;
3. They are in the same room (OnRoomConnected called)(I understand that the room is marked as "filled");
4. Second opponent CreateQuickGame;
5. He is in another room;

It is not yet known whether there will be a second or third opponent.
How to add a second or third opponent to the same room?

This is stated in https://developers.google.com/games/services/common/concepts/realtimeMultiplayer#gameplay

Thanks

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
