### ISSUE TITLE
GPGS & Firebase : GamesNativeSDK Can't Register class Error

### ISSUE THREAD

**Issue by LiztyStalker** [playgameservices/play-games-plugin-for-unity#2230]
Hello!

There is currently a problem with my project.

During GPGS and firebase integration, GPGS does not work with the following message.

The current version is as follows.
- GPGS 0.9.50
- Firebase 5.1.0
- Unity 2018.1.1f1
- Facebook SDK 7.12.2

This project has been successfully integrated with Facebook and Firebase. After that, I successfully erased both SDKs and tested GPGS only. However, if the Firebase is linked, GPGS
GamesNativeSDK fails. I tried to resolve a number of issues, but I could not find a solution.

How do I resolve this issue at this time? It's time to release. Please help me.

################ Error Logcat ######################

06-26 15:31:32.135 13252 13312 W Unity   : FacebookApi.FacebookManager:InitCallback() (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/Scripts/Account/API/Facebook/FacebookManager.cs:41)
06-26 15:31:32.135 13252 13312 W Unity   : Facebook.Unity.FacebookBase:<OnInitComplete>b__35_0(ILoginResult)
06-26 15:31:32.135 13252 13312 W Unity   : Facebook.Unity.CallbackManager:TryCallCallback(Object, IResult)
06-26 15:31:32.135 13252 13312 W Unity   : Facebook.Unity.CallbackManager:CallCallback(Object, IResult)
06-26 15:31:32.135 13252 13312 W Unity   : Facebook.Unity.CallbackManager:OnFacebookResponse(IInternalResult)
06-26 15:31:32.135 13252 13312 W Unity   : Facebook.Unity.FacebookBase:OnAuthResponse(LoginResult)
06-26 15:31:32.135 13252 13312 W Unity   : Facebook.Unity.Mobile.MobileFacebook:OnLoginComplete(ResultContainer)
06-26 15:31:32.135 13252 13312 W Unity   : Faceb
06-26 15:31:34.468 13252 13312 I Unity   : [Msg ] ##### Sign Start UIMgr
06-26 15:31:34.468 13252 13312 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
06-26 15:31:34.468 13252 13312 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
06-26 15:31:34.468 13252 13312 I Unity   : UnityEngine.Logger:LogFormat(LogType, String, Object[])
06-26 15:31:34.468 13252 13312 I Unity   : UnityEngine.Debug:LogFormat(String, Object[])
06-26 15:31:34.468 13252 13312 I Unity   : Prep:Log(String, String, Type) (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/Scripts/Prep.cs:14)
06-26 15:31:34.468 13252 13312 I Unity   : UIMgr:MsgCallback(String) (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/Script/Manager/UIMgr.cs:786)
06-26 15:31:34.468 13252 13312 I Unity   : GoogleAPI.GoogleApi:LogInGoogle(Action`1, Action`1) (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/Scripts/Account/API/Google/GoogleApi.cs:72)
06-26 15:31:34.468 13252 13312 I Unity   : <GoogleLogInCoroutine>c__Iterator1:MoveNext() (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/Script/Manager/UIMgr.cs:948)
06-26 15:31:34.468 13252 13312 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /Users/builduser/buildslave/unity/build/Runtime/Export/C
06-26 15:31:34.471 13252 13312 I Unity   : [Msg ] ##### Sign Out... UIMgr
06-26 15:31:34.471 13252 13312 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
06-26 15:31:34.471 13252 13312 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
06-26 15:31:34.471 13252 13312 I Unity   : UnityEngine.Logger:LogFormat(LogType, String, Object[])
06-26 15:31:34.471 13252 13312 I Unity   : UnityEngine.Debug:LogFormat(String, Object[])
06-26 15:31:34.471 13252 13312 I Unity   : Prep:Log(String, String, Type) (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/Scripts/Prep.cs:14)
06-26 15:31:34.471 13252 13312 I Unity   : UIMgr:MsgCallback(String) (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/Script/Manager/UIMgr.cs:786)
06-26 15:31:34.471 13252 13312 I Unity   : GoogleAPI.GoogleApi:LogInGoogle(Action`1, Action`1) (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/Scripts/Account/API/Google/GoogleApi.cs:78)
06-26 15:31:34.471 13252 13312 I Unity   : <GoogleLogInCoroutine>c__Iterator1:MoveNext() (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/Script/Manager/UIMgr.cs:948)
06-26 15:31:34.471 13252 13312 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /Users/builduser/buildslave/unity/build/Runtime/Export/
**06-26 15:31:34.525 13252 13312 E GamesNativeSDK: Can't register class com/google/android/gms/games/PlayerLevel: an exception occurred.
06-26 15:31:34.526 13252 13312 E GamesNativeSDK: Can't register class com/google/android/gms/games/PlayerLevelInfo: an exception occurred.
06-26 15:31:34.528 13252 13312 E GamesNativeSDK: Can't register class com/google/android/gms/games/leaderboard/LeaderboardBuffer: an exception occurred.
06-26 15:31:34.530 13252 13312 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/InvitationBuffer: an exception occurred.
06-26 15:31:34.531 13252 13312 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/ParticipantResult: an exception occurred.
06-26 15:31:34.532 13252 13312 E GamesNativeSDK: Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchBuffer: an exception occurred.
06-26 15:31:34.534 13252 13312 E GamesNativeSDK: Can't register class com/google/android/gms/games/quest/QuestBuffer: an exception occurred.
06-26 15:31:34.536 13252 13312 E GamesNativeSDK: Can't register class com/google/android/gms/nearby/connection/AppIdentifier: an exception occurred.
06-26 15:31:34.537 13252 13312 E GamesNativeSDK: Can't register class com/google/android/gms/nearby/connection/AppMetadata: an exception occurred.
06-26 15:31:34.538 13252 13312 E GamesNativeSDK: Can't register class com/google/android/gms/games/video/VideoCapabilities: an exception occurred.
06-26 15:31:34.580 13252 13312 I Unity   : Building GPG services, implicitly attempts silent auth
06-26 15:31:34.580 13252 13312 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
06-26 15:31:34.580 13252 13312 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
06-26 15:31:34.580 13252 13312 I Unity   : UnityEngine.Logger:Log(LogType, Object)
06-26 15:31:34.580 13252 13312 I Unity   : UnityEngine.Debug:Log(Object)
06-26 15:31:34.580 13252 13312 I Unity   : GooglePlayGames.Native.NativeClient:InitializeGameServices() (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/Platforms/Native/NativeClient.cs:222)
06-26 15:31:34.580 13252 13312 I Unity   : GooglePlayGames.Native.NativeClient:Authenticate(Action`2, Boolean) (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/Platforms/Native/NativeClient.cs:139)
06-26 15:31:34.580 13252 13312 I Unity   : GooglePlayGames.PlayGamesPlatform:Authenticate(Action`2, Boolean) (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:414)
06-26 15:31:34.580 13252 13312 I Unity   : GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_
06-26 15:31:34.584 13252 13312 E GamesNativeSDK: Could not register one or more required Java classes.
06-26 15:31:34.603 13252 13312 E Unity   : InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK
06-26 15:31:34.603 13252 13312 E Unity   :   at GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build (GooglePlayGames.Native.PInvoke.PlatformConfiguration configRef) [0x0004c] in /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/Platforms/Native/PInvoke/GameServicesBuilder.cs:197 
06-26 15:31:34.603 13252 13312 E Unity   :   at GooglePlayGames.Native.NativeClient.InitializeGameServices () [0x0010a] in /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/Platforms/Native/NativeClient.cs:229 
06-26 15:31:34.603 13252 13312 E Unity   :   at GooglePlayGames.Native.NativeClient.Authenticate (System.Action`2 callback, Boolean silent) [0x000f7] in /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/Platforms/Native/NativeClient.cs:139 
06-26 15:31:34.603 13252 13312 E Unity   :   at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`2 callback, Boolean silent) [0x00031] in /Users/gambridzy_imac_1/Documents/MyP**
06-26 15:31:34.647 13252 13312 W Unity   : !!! [Play Games Plugin DLL] 06/26/18 15:31:34 +09:00 WARNING: Creating new PlayGamesPlatform
06-26 15:31:34.647 13252 13312 W Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
06-26 15:31:34.647 13252 13312 W Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
06-26 15:31:34.647 13252 13312 W Unity   : UnityEngine.Logger:Log(LogType, Object)
06-26 15:31:34.647 13252 13312 W Unity   : UnityEngine.Debug:LogWarning(Object)
06-26 15:31:34.647 13252 13312 W Unity   : GooglePlayGames.OurUtils.<w>c__AnonStorey1:<>m__0() (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/Logger.cs:68)
06-26 15:31:34.647 13252 13312 W Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:135)
06-26 15:31:34.647 13252 13312 W Unity   :  
06-26 15:31:34.647 13252 13312 W Unity   : (Filename: /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/Logger.cs Line: 68)
06-26 15:31:34.647 13252 13312 W Unity   : 
06-26 15:31:34.649 13252 13312 I Unity   :  [Play Games Plugin DLL] 06/26/18 15:31:34 +09:00 DEBUG: Activating PlayGamesPlatform.
06-26 15:31:34.649 13252 13312 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
06-26 15:31:34.649 13252 13312 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
06-26 15:31:34.649 13252 13312 I Unity   : UnityEngine.Logger:Log(LogType, Object)
06-26 15:31:34.649 13252 13312 I Unity   : UnityEngine.Debug:Log(Object)
06-26 15:31:34.649 13252 13312 I Unity   : GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/Logger.cs:59)
06-26 15:31:34.649 13252 13312 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:135)
06-26 15:31:34.649 13252 13312 I Unity   :  
06-26 15:31:34.649 13252 13312 I Unity   : (Filename: /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/Logger.cs Line: 59)
06-26 15:31:34.649 13252 13312 I Unity   : 
06-26 15:31:34.650 13252 13312 I Unity   :  [Play Games Plugin DLL] 06/26/18 15:31:34 +09:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
06-26 15:31:34.650 13252 13312 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
06-26 15:31:34.650 13252 13312 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
06-26 15:31:34.650 13252 13312 I Unity   : UnityEngine.Logger:Log(LogType, Object)
06-26 15:31:34.650 13252 13312 I Unity   : UnityEngine.Debug:Log(Object)
06-26 15:31:34.650 13252 13312 I Unity   : GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/Logger.cs:59)
06-26 15:31:34.650 13252 13312 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:135)
06-26 15:31:34.650 13252 13312 I Unity   :  
06-26 15:31:34.650 13252 13312 I Unity   : (Filename: /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/Logger.cs Line: 59)
06-26 15:31:34.650 13252 13312 I Unity   : 
06-26 15:31:34.651 13252 13312 I Unity   :  [Play Games Plugin DLL] 06/26/18 15:31:34 +09:00 DEBUG: Creating platform-specific Play Games client.
06-26 15:31:34.651 13252 13312 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
06-26 15:31:34.651 13252 13312 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
06-26 15:31:34.651 13252 13312 I Unity   : UnityEngine.Logger:Log(LogType, Object)
06-26 15:31:34.651 13252 13312 I Unity   : UnityEngine.Debug:Log(Object)
06-26 15:31:34.651 13252 13312 I Unity   : GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/Logger.cs:59)
06-26 15:31:34.651 13252 13312 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:135)
06-26 15:31:34.651 13252 13312 I Unity   :  
06-26 15:31:34.651 13252 13312 I Unity   : (Filename: /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/Logger.cs Line: 59)
06-26 15:31:34.651 13252 13312 I Unity   : 
06-26 15:31:34.651 13252 13312 I Unity   :  [Play Games Plugin DLL] 06/26/18 15:31:34 +09:00 DEBUG: Creating Android IPlayGamesClient Client
06-26 15:31:34.651 13252 13312 I Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
06-26 15:31:34.651 13252 13312 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
06-26 15:31:34.651 13252 13312 I Unity   : UnityEngine.Logger:Log(LogType, Object)
06-26 15:31:34.651 13252 13312 I Unity   : UnityEngine.Debug:Log(Object)
06-26 15:31:34.651 13252 13312 I Unity   : GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/Logger.cs:59)
06-26 15:31:34.651 13252 13312 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:135)
06-26 15:31:34.651 13252 13312 I Unity   :  
06-26 15:31:34.651 13252 13312 I Unity   : (Filename: /Users/gambridzy_imac_1/Documents/MyProject/AshaRun2018/AshaRun_R 2018.1.1f1/Assets/GooglePlayGames/OurUtils/Logger.cs Line: 59)

############ Directory : Assets/Plugins/Android ##############

android.arch.core.common-1.0.0
android.arch.lifecycle.common-1.0.0
android.arch.lifecycle.runtime-1.0.0
AndroidManifest
com.android.support.animated-vector-drawable-26.1.0
com.android.support.appcompat-v7-26.1.0
com.android.support.cardview-v7-26.1.0
com.android.support.customtabs-26.1.0
com.android.support.support-annotations-26.1.0
com.android.support.support-compat-26.1.0
com.android.support.support-core-ui-26.1.0
com.android.support.support-core-utils-26.1.0
com.android.support.support-fragment-26.1.0
com.android.support.support-media-compat-26.1.0
com.android.support.support-v4-26.1.0
com.android.support.support-vector-drawable-26.1.0
com.google.android.gms.play-services-ads-identifier-15.0.1
com.google.android.gms.play-services-auth-11.6.2
com.google.android.gms.play-services-auth-api-phone-11.6.2
com.google.android.gms.play-services-auth-api-phone-license-11.6.2
com.google.android.gms.play-services-auth-base-11.6.2
com.google.android.gms.play-services-auth-base-license-11.6.2
com.google.android.gms.play-services-base-15.0.1
com.google.android.gms.play-services-basement-15.0.1
com.google.android.gms.play-services-drive-11.6.2
com.google.android.gms.play-services-drive-license-11.6.2
com.google.android.gms.play-services-flags-15.0.1
com.google.android.gms.play-services-games-11.6.2
com.google.android.gms.play-services-games-license-11.6.2
com.google.android.gms.play-services-measurement-base-16.0.0
com.google.android.gms.play-services-nearby-11.6.2
com.google.android.gms.play-services-nearby-license-11.6.2
com.google.android.gms.play-services-stats-15.0.1
com.google.android.gms.play-services-tasks-15.0.1
com.google.firebase.firebase-analytics-16.0.1
com.google.firebase.firebase-analytics-impl-16.1.1
com.google.firebase.firebase-app-unity-5.1.0
com.google.firebase.firebase-auth-16.0.2
com.google.firebase.firebase-auth-interop-16.0.0
com.google.firebase.firebase-auth-unity-5.1.0
com.google.firebase.firebase-common-16.0.0
com.google.firebase.firebase-core-16.0.1
com.google.firebase.firebase-database-16.0.1
com.google.firebase.firebase-database-collection-15.0.1
com.google.firebase.firebase-database-connection-16.0.1
com.google.firebase.firebase-database-unity-5.1.0
com.google.firebase.firebase-iid-16.0.0
com.google.firebase.firebase-iid-interop-16.0.0
com.google.firebase.firebase-measurement-connector-17.0.0
com.google.firebase.firebase-measurement-connector-impl-16.0.1
com.google.games.gpgs-plugin-support-0.9.50
Firebase(Directory), AndroidManifest, project, res(Directory), values(Directory), google-services

**Comment by defic** [comment]
I think I had the same problem. Google play resolver downloads incompatible (too old) play service libraries.

We use firebase messaging and analytics. I disabled auto resolver and replaced the old versions with these manually to get it working:

play-services-auth-15.0.1.aar
play-services-auth-api-phone-15.0.1.aar
play-services-auth-api-phone-license-12.0.1.aar
play-services-auth-base-15.0.1.aar
play-services-auth-base-license-12.0.1.aar
play-services-drive-15.0.1.aar
play-services-drive-license-12.0.1.aar
play-services-games-15.0.1.aar
play-services-games-license-12.0.1.aar
play-services-nearby-15.0.1.aar
play-services-nearby-license-12.0.1.aar

This is a not very good solution, as running the google play resolver will break the project.

Maybe they fixed this with the newest google jar resolver ( https://github.com/googlesamples/unity-jar-resolver/issues/127 ) but I haven't tried it yet.

**Comment by LiztyStalker** [comment]
Thank you for writing. I solved this problem. Getting the old library was a problem. After deleting all plugins, re-running Firebase 5.1.0 and launching Android Resolver, the 15.0.1 version came in. Firebase 5.1.0 unityPackage has version 1.2.75 of PlayServicesResolver, and it is guessed that a new version was introduced by this version.
