### ISSUE TITLE
[Resolved] InvalidOperationException: There was an error creating a GameServices object

### ISSUE THREAD

**Issue by nol0gic** [playgameservices/play-games-plugin-for-unity#2232]
I'me using GPS 9.50 and Unity 2017. All the things was working fine, until I decided to rename a project,
 I've set up new project in google console, 
changed package name in Unity, reimport/setup GPS and make alpha release.

The first error I've got was "unable to find gpg". After reimporting gps again and apply Force Resolve this error gone but apears a new one:

> Unity(26603): InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK
> Unity(26603):   at GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build (GooglePlayGames.Native.PInvoke.PlatformConfiguration configRef) [0x00000] in <filename unknown>:0 
> Unity(26603):   at GooglePlayGames.Native.NativeClient.InitializeGameServices () [0x00000] in <filename unknown>:0 
> Unity(26603):   at GooglePlayGames.Native.NativeClient.Authenticate (System.Action`2 callback, Boolean silent) [0x00000] in <filename unknown>:0 
> Unity(26603):  
> Unity(26603): (Filename: currently not available on il2cpp Line: -1)
> Unity(26603): !!! [Play Games Plugin DLL] 06/27/18 21:38:35 +04:00 WARNING: Creating new PlayGamesPlatform
> Unity(26603):  
> Unity(26603): (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
-----------------------------------------------------------

> 06-27 22:28:01.864: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/common/ConnectionResult: an exception occurred.
> 06-27 22:28:01.864: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/common/GooglePlayServicesUtil: an exception occurred.
> 06-27 22:28:01.865: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/common/api/Api: an exception occurred.
> 06-27 22:28:01.865: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/common/api/Api$ApiOptions: an exception occurred.
> 06-27 22:28:01.866: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/common/api/Api$ApiOptions$HasOptions: an exception occurred.
> 06-27 22:28:01.866: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/common/api/GoogleApiClient: an exception occurred.
> 06-27 22:28:01.866: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/common/api/GoogleApiClient$Builder: an exception occurred.
> 06-27 22:28:01.866: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/common/api/PendingResult: an exception occurred.
> 06-27 22:28:01.866: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/common/api/Result: an exception occurred.
> 06-27 22:28:01.867: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/common/api/ResultCallback: an exception occurred.
> 06-27 22:28:01.867: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/common/api/Scope: an exception occurred.
> 06-27 22:28:01.867: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/common/api/Status: an exception occurred.
> 06-27 22:28:01.867: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/common/data/DataBufferUtils: an exception occurred.
> 06-27 22:28:01.867: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/Games: an exception occurred.
> 06-27 22:28:01.867: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/Games$GamesOptions: an exception occurred.
> 06-27 22:28:01.868: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/Games$GamesOptions$Builder: an exception occurred.
> 06-27 22:28:01.868: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/Player: an exception occurred.
> 06-27 22:28:01.868: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/PlayerBuffer: an exception occurred.
> 06-27 22:28:01.868: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/PlayerLevel: an exception occurred.
> 06-27 22:28:01.869: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/PlayerLevelInfo: an exception occurred.
> 06-27 22:28:01.869: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/Players: an exception occurred.
> 06-27 22:28:01.869: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/Players$LoadPlayersResult: an exception occurred.
> 06-27 22:28:01.869: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/achievement/Achievement: an exception occurred.
> 06-27 22:28:01.869: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/achievement/Achievements$LoadAchievementsResult: an exception occurred.
> 06-27 22:28:01.870: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/event/Event: an exception occurred.
> 06-27 22:28:01.870: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/event/EventBuffer: an exception occurred.
> 06-27 22:28:01.870: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/event/Events: an exception occurred.
> 06-27 22:28:01.870: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/event/Events$LoadEventsResult: an exception occurred.
> 06-27 22:28:01.870: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/achievement/AchievementBuffer: an exception occurred.
> 06-27 22:28:01.871: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/achievement/Achievements: an exception occurred.
> 06-27 22:28:01.871: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/leaderboard/Leaderboard: an exception occurred.
> 06-27 22:28:01.871: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/leaderboard/LeaderboardBuffer: an exception occurred.
> 06-27 22:28:01.871: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/leaderboard/Leaderboards: an exception occurred.
> 06-27 22:28:01.871: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/leaderboard/LeaderboardScore: an exception occurred.
> 06-27 22:28:01.872: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/leaderboard/LeaderboardScoreBuffer: an exception occurred.
> 06-27 22:28:01.872: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/leaderboard/LeaderboardVariant: an exception occurred.
> 06-27 22:28:01.872: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/leaderboard/Leaderboards$LeaderboardMetadataResult: an exception occurred.
> 06-27 22:28:01.872: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/leaderboard/Leaderboards$LoadScoresResult: an exception occurred.
> 06-27 22:28:01.872: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/Invitation: an exception occurred.
> 06-27 22:28:01.873: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/InvitationBuffer: an exception occurred.
> 06-27 22:28:01.873: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/Invitations: an exception occurred.
> 06-27 22:28:01.873: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/Invitations$LoadInvitationsResult: an exception occurred.
> 06-27 22:28:01.873: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/Multiplayer: an exception occurred.
> 06-27 22:28:01.873: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/Participant: an exception occurred.
> 06-27 22:28:01.874: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/ParticipantResult: an exception occurred.
> 06-27 22:28:01.874: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/turnbased/LoadMatchesResponse: an exception occurred.
> 06-27 22:28:01.874: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatch: an exception occurred.
> 06-27 22:28:01.874: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchBuffer: an exception occurred.
> 06-27 22:28:01.874: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchConfig: an exception occurred.
> 06-27 22:28:01.874: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchConfig$Builder: an exception occurred.
> 06-27 22:28:01.874: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer: an exception occurred.
> 06-27 22:28:01.875: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$CancelMatchResult: an exception occurred.
> 06-27 22:28:01.875: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$InitiateMatchResult: an exception occurred.
> 06-27 22:28:01.875: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LeaveMatchResult: an exception occurred.
> 06-27 22:28:01.875: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LoadMatchesResult: an exception occurred.
> 06-27 22:28:01.875: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LoadMatchResult: an exception occurred.
> 06-27 22:28:01.876: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$UpdateMatchResult: an exception occurred.
> 06-27 22:28:01.876: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/quest/Quest: an exception occurred.
> 06-27 22:28:01.876: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/quest/QuestBuffer: an exception occurred.
> 06-27 22:28:01.876: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/quest/Quests: an exception occurred.
> 06-27 22:28:01.876: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/quest/Milestone: an exception occurred.
> 06-27 22:28:01.877: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/quest/Quests$LoadQuestsResult: an exception occurred.
> 06-27 22:28:01.877: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/quest/Quests$AcceptQuestResult: an exception occurred.
> 06-27 22:28:01.877: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/quest/Quests$ClaimMilestoneResult: an exception occurred.
> 06-27 22:28:01.877: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/snapshot/Snapshot: an exception occurred.
> 06-27 22:28:01.877: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/snapshot/SnapshotContents: an exception occurred.
> 06-27 22:28:01.880: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadata: an exception occurred.
> 06-27 22:28:01.880: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataBuffer: an exception occurred.
> 06-27 22:28:01.880: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/snapshot/Snapshots: an exception occurred.
> 06-27 22:28:01.880: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/snapshot/Snapshots$CommitSnapshotResult: an exception occurred.
> 06-27 22:28:01.880: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/snapshot/Snapshots$LoadSnapshotsResult: an exception occurred.
> 06-27 22:28:01.880: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/snapshot/Snapshots$OpenSnapshotResult: an exception occurred.
> 06-27 22:28:01.881: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataChange: an exception occurred.
> 06-27 22:28:01.881: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataChange$Builder: an exception occurred.
> 06-27 22:28:01.881: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/stats/PlayerStats: an exception occurred.
> 06-27 22:28:01.881: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/stats/Stats: an exception occurred.
> 06-27 22:28:01.881: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/stats/Stats$LoadPlayerStatsResult: an exception occurred.
> 06-27 22:28:01.882: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMessageReceivedListener: an exception occurred.
> 06-27 22:28:01.882: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMultiplayer: an exception occurred.
> 06-27 22:28:01.882: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMessage: an exception occurred.
> 06-27 22:28:01.882: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/realtime/Room: an exception occurred.
> 06-27 22:28:01.882: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/realtime/RoomConfig: an exception occurred.
> 06-27 22:28:01.882: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/multiplayer/realtime/RoomConfig$Builder: an exception occurred.
> 06-27 22:28:01.884: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/nearby/Nearby: an exception occurred.
> 06-27 22:28:01.895: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/nearby/connection/AppIdentifier: an exception occurred.
> 06-27 22:28:01.897: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/nearby/connection/AppMetadata: an exception occurred.
> 06-27 22:28:01.897: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/nearby/connection/Connections: an exception occurred.
> 06-27 22:28:01.897: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/nearby/connection/Connections$StartAdvertisingResult: an exception occurred.
> 06-27 22:28:01.897: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/video/CaptureState: an exception occurred.
> 06-27 22:28:01.905: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/video/VideoCapabilities: an exception occurred.
> 06-27 22:28:01.905: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/video/Videos: an exception occurred.
> 06-27 22:28:01.905: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/video/Videos$CaptureAvailableResult: an exception occurred.
> 06-27 22:28:01.905: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/video/Videos$CaptureCapabilitiesResult: an exception occurred.
> 06-27 22:28:01.906: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/video/Videos$CaptureStateResult: an exception occurred.
> 06-27 22:28:01.907: E/GamesNativeSDK(27477): Can't register class com/google/android/gms/games/video/Videos$CaptureOverlayStateListener: an exception occurred.
> 06-27 22:28:01.923: E/GamesNativeSDK(27477): Could not register one or more required Java classes.
> 
> 

Any idea why this happens?

**Comment by nol0gic** [comment]
Ok, after doing Resolve, Force Resolve and resetup project few times the build size grows and things become working, but now, this issue happens again, for no reason, and those steps wont help anymore, I'm almost done with it, unbelievable, one of the world's biggest corporation cant make stable sdk for popular engine...

**Comment by nol0gic** [comment]
I've found the problem, while resolving process is running, gpg is loading classes from google servers and if you dont have permision to acces those servers, like in my case (due to the sanctions, be damned fucking politicians) you will never get those files... So, solution is to use VPN. Some one should add debug messages for this kind of situations...

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
