### ISSUE TITLE
Upgraded to Unity 2018.2.0f2 from 2018.1.8f1, game crashes on authenticate.

### ISSUE THREAD

**Issue by brentbartlett** [playgameservices/play-games-plugin-for-unity#2242]
Game using play games plugin crashes on call to authenticate.

Worked last week on version 2018.1.8f1; upgraded to version 2018.2.0f2.

Rolling back to version 2018.1.8f1 is not an option as the prefab formats between the two versions have changed.

Seems that this happens frequently due to conflicts with Unity and the playgamesplugin at a library level.

Is there any fix for this?
Could there be a version selection in the resolver to force a specific version of the various libraries added to the Resolver?

Any  help would be appreciated.

**Comment by hytka81** [comment]
I have exactly the same problem and after spending some time to roll back to previous Unity version I found out that it's not possible at least from prefabs point of view :(

I hope there will be a fix for this soon.

**Comment by Neecko** [comment]
So 2018.1 works? Im not using nested prefabs, but having this same issue.

**Comment by FodderMK** [comment]
The fix recommended in this thread worked for us:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/2013

**Comment by brentbartlett** [comment]
The work around FodderMK pointed to is spot on and worked for me.

The crash is being caused by the space, the generated AndroidManifest.xml should be updated to do this automatically to resolve the issue.

Thanks for the help!

**Comment by olehkuznetsov** [comment]
Should be fixed in 0.9.52
