### ISSUE TITLE
Failed Integrate with Firebase for Unity v5.1.1

### ISSUE THREAD

**Issue by antlaw** [playgameservices/play-games-plugin-for-unity#2243]
When we try to use Firebase unity SDK 5.1.1 with Play Games Plugin for Unity 0.9.5, the app can be built, but it will crash with you try to call login of Google Play Game. I suspect that it is because the plugin is still pointing to the library of gms version 11.62. Please upgrade it to support gms 15.0.1. Or  Google Play Games connect will not be functioned  probably. Much appreciated if the developer can help fix the problem.

**Comment by olehkuznetsov** [comment]
Should be fixed in 0.9.51.
