### ISSUE TITLE
Fail Authenticating

### ISSUE THREAD

**Issue by aguerrem** [playgameservices/play-games-plugin-for-unity#2244]
Hi, I am developing a game and got uploaded in the play store in alpha version, when authenticate with my mobile got a authentication fail but i got 5 testers and in his mobiles doesn't have this problem.

I didn't have this problem always, in previews versions works fine but i didn't change any code of the authentication process.

`07-16 13:46:31.472: I/Unity(1986): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
07-16 13:46:31.485: I/Unity(1986):  [Play Games Plugin DLL] 07/16/18 13:46:31 +02:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: 10
07-16 13:46:31.485: I/Unity(1986):  
07-16 13:46:31.485: I/Unity(1986): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
07-16 13:46:31.485: I/Unity(1986):  [Play Games Plugin DLL] 07/16/18 13:46:31 +02:00 DEBUG: AuthState == Unauthenticated calling auth callbacks with failure
07-16 13:46:31.485: I/Unity(1986):  
07-16 13:46:31.485: I/Unity(1986): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
07-16 13:46:31.486: I/Unity(1986): Fail authenticating user
07-16 13:46:31.486: I/Unity(1986):  
07-16 13:46:31.486: I/Unity(1986): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
07-16 13:46:31.501: I/Unity(1986):  [Play Games Plugin DLL] 07/16/18 13:46:31 +02:00 DEBUG: Invoking user callback on game thread
`

Thank you

**Comment by AssetKid** [comment]
Did you enable App Signing when you uploaded it to the console?

**Comment by aguerrem** [comment]
I don´t know where enable signing but it work in some mobiles.

**Comment by AssetKid** [comment]
![capture](https://user-images.githubusercontent.com/40426812/42807402-5fd2c846-89b9-11e8-9e14-1b202ab165bb.PNG)

What does it say?

**Comment by aguerrem** [comment]
Yes it´s enabled

**Comment by aguerrem** [comment]
"Se ha habilitado Firma de Apps en Google Play para esta aplicación. Más información" 

The same but in spanish.


![2018-07-17 11_20_04-firma de aplicaciones - rocket jam - google play console](https://user-images.githubusercontent.com/39050959/42808471-b23a2152-89b3-11e8-9c0c-142e3c01adaf.png)

**Comment by AssetKid** [comment]
That must be the issue.

Google will resign your application with a new certificate. The old Unity certificate you generated is no longer used for authentication.

See a workaround I posted here a few weeks ago - https://github.com/playgameservices/play-games-plugin-for-unity/issues/2226#issuecomment-400423572

The Google Play version **WILL STOP WORKING** if you change the SHA-1 key. You can manually send an APK file to your testers if needed.

**DO NOT FORGET TO CHANGE THE SHA-1 KEY TO THE GOOGLE PLAY ONE (App signing certificate) ONCE YOU ARE READY TO GO LIVE. **

I hope this helps.

**Comment by aguerrem** [comment]
Thanks but I always use the google signing and download the version from PlayStore. Some mobiles got a authentication fail and in some mobiles work correctly. Its strange...

**Comment by AssetKid** [comment]
Make sure all your testers emails have been added to your testers list.

**Comment by aguerrem** [comment]
I got six testers, GooglePlayGames doesn´t work in my personal mobile and in another mobile and all are in the alpha users.

**Comment by aguerrem** [comment]
I don´t why but i fixed changing startup configuration like last comment of #2214.
I change documentation configuration for:
 ` PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();`
Thanks for the help.
