### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by CabInTheCity** [playgameservices/play-games-plugin-for-unity#225]
When I try to authenticate the user I always get a message saying "Failed to sign in. Please check your network connection and try again."
There's nothing wrong with my internet connection and I followed everything mentioned in the instructions, what could be the problem here.

**Comment by Renato-Malachite** [comment]
Hello guys, Im having an issue on authentication as well.

I triple checked and my email is on tester but Im getting the following error:

[Play Games Plugin DLL] 10/25/15 21:38:17 -02:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED

I 'published' the game services some hours ago, maybe it takes some time to get up an running?

**Comment by analripper** [comment]
I expirienced exact same issue. I use plugin version 0.9.35 and Unity 5.3.2f1.
Then after I tried out all that internet can suggest to me, regarding my issue, I installed Unity 5.4.3 f1 and get my working authentication.
Hope it helps.
