### ISSUE TITLE
how many player can join a room?

### ISSUE THREAD

**Issue by green4you** [playgameservices/play-games-plugin-for-unity#2268]
i find 8 player can join at one room from "https://developers.google.com/games/services/common/concepts/realtimeMultiplayer"

but this sdk readme tell "4 player " is the max.

how many player can join a room?

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
