### ISSUE TITLE
Turn Based Multiplayer CanRematch always false

### ISSUE THREAD

**Issue by megasoft78** [playgameservices/play-games-plugin-for-unity#2271]
Hi,
I'm using latest version of Google Play Games on Unity 2017.4.8f1 and the property CanRematch is always false.
Could you please help me?

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
