### ISSUE TITLE
Incremental Achievements are increment just once 

### ISSUE THREAD

**Issue by DimoNline** [playgameservices/play-games-plugin-for-unity#2273]
Social.ReportProgress("SOMEID", 100d, (bool sucess) =>{});  //it works

Social.ReportProgress("SOMEID", 20d, (bool sucess) =>{});  //it works just once and progress is always 20%

**Comment by exzizt** [comment]
It's almost as if the documentation states this. 😉 

https://github.com/playgameservices/play-games-plugin-for-unity
> If your achievement is incremental, the Play Games implementation of Social.ReportProgress will try to behave as closely as possible to the expected behavior according to Unity's social API, but may not be exact. For this reason, we recommend that you do not use Social.ReportProgress for incremental achievements. Instead, use the PlayGamesPlatform.IncrementAchievement method, which is a Play Games extension.

**Comment by RomainBitard** [comment]
it's a shame unity still didn't make it work as intended, I had the same problem :(
