### ISSUE TITLE
Social.localUser.Authenticate TRUE even without internet connection.

### ISSUE THREAD

**Issue by ricardoianelli** [playgameservices/play-games-plugin-for-unity#2284]
Social.localUser.Authenticate is returning TRUE even without internet connection on my device!
The login code is like that:

```
void Start ()
    {
        Debug.Log("Start playservices");
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
            .Build();


        PlayGamesPlatform.InitializeInstance(config);
        //GooglePlayGames.PlayGamesPlatform.DebugLogEnabled = true;
        PlayGamesPlatform.Activate();

        PlayerPrefs.SetInt("offlineGame", 0); // Quantas questões já joguei. 10 questões = 1 round/partida.
        SignIn();
    }

public static void SignIn()
    {
        Social.localUser.Authenticate(success => {
              if (success)
              {
                  Debug.Log("logged in!");
                  FisiqzManager.IntroLoadingPercent = 5;
                  SendScoresToGoogle();
              }
              else
              {
                  Debug.Log("login failed!");
                  FisiqzManager.IntroLoadingPercent = 100;
              }
                  });
    }
```

It always print "Debug.Log("logged in!");".

**Comment by dyfer08** [comment]
It is the intended behavior as GooglePlayGames let you access leaderboards and game saves stored locally. You can still send new scores and update your game saves and GooglePlayGames will push it automatically when the phone can access the network.

**Comment by ricardoianelli** [comment]
> It is the intended behavior as GooglePlayGames let you access leaderboards and game saves stored locally. You can still send new scores and update your game saves and GooglePlayGames will push it automatically when the phone can access the network.

That's useful. Thank you very much!
