### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by UncleJey** [playgameservices/play-games-plugin-for-unity#229]
Player in AndroidRtmpClient and JavaUtil
(GooglePlayGames.BasicApi.Multiplayer.Player)
conflict with our Player script.

Please use namespaces

in javaUtil
line 155
GooglePlayGames.BasicApi.Multiplayer.Player player = null;

line 186
            AndroidJavaObject playerObj = JavaUtil.CallNullSafeObjectMethod(participant, "getPlayer");
            if (playerObj != null) {
				player = new GooglePlayGames.BasicApi.Multiplayer.Player(playerObj.Call<string>("getDisplayName"),
                                    playerObj.Call<string>("getPlayerId"));
                playerObj.Dispose();
                playerObj = null;
            }

in AndroidRtmpClient 
line 490
                mSelf = new Participant("?", myPartId, Participant.ParticipantStatus.Unknown, 
                            new GooglePlayGames.BasicApi.Multiplayer.Player("?", playerId), false);

**Comment by claywilkinson** [comment]
The new plugin has the Player in the GooglePlayGames.BasicApi.Multiplayer namespace.

**Comment by ajaybirla** [comment]
I am having the same issue with GooglePlayGames/Platforms/Native/NativeClient.cs. It is conflicting with mine Player script.

**Comment by claywilkinson** [comment]
Hmm. What is the namespace that your Player class is in?

**Comment by ajaybirla** [comment]
Hello @claywilkinson , Sorry for the trouble but this problem is solved by encapsulating mine Player class to a namespace. This problem was coming because i generally don't use namespaces. Please ignore this.

**Comment by claywilkinson** [comment]
Thanks for the response. Glad everything is working out!
