### ISSUE TITLE
Sign in not working on app store APK

### ISSUE THREAD

**Issue by Musaka96** [playgameservices/play-games-plugin-for-unity#2290]
When i uploaded the APK for internal testing on the play store, the log in won't work. It connects and asks me to chose an account, then just spins for a sec or two and nothing. The APK that i uploaded works, but when i download it from the app store it doesn't.

Here is the log:
`09-05 14:20:10.907 6174-6184/? W/Auth: [GetToken] GetToken failed with status code: INVALID_AUDIENCE
09-05 14:20:10.908 31721-32504/? E/TokenRequestor: You have wrong OAuth2 related configurations, please check. Detailed error: INVALID_AUDIENCE
09-05 14:20:10.917 25893-25893/? I/SignInActivity: Transition from 6 to 11
09-05 14:20:10.917 25893-25893/? W/SignInActivity: onSignInFailed()...
09-05 14:20:10.917 25893-25893/? W/SignInActivity: Sign in failed during 6
09-05 14:20:10.917 25893-25893/? W/SignInActivity: ==> Returning non-OK result: 10002`

The game service is published, and has been tested and everything works so far.

More info:
I have the same Debug and Release key.
Google auto created an OAuth 2.0 cliend ID for android in the developer console when the APK was uploaded.
I added the App signing and the Upload SHA-1/SHA-256 certificate fingerprints on Firebase.

**Comment by olehkuznetsov** [comment]
You need also add additional entry to 'Linked apps' in 'Google Play Console' with release apk SHA-1 key.
