### ISSUE TITLE
SIGN_IN status: ERROR_NOT_AUTHORIZED on Gradle build

### ISSUE THREAD

**Issue by mtemnikov** [playgameservices/play-games-plugin-for-unity#2292]
Unity ver. Unity 2017.4.6f1
GPGS ver. 0.9.50

Problem:
I am getting this error on trying to sign in. However, it is only on gradle Unity build. If i choose internal type, everything is working fine.

What have i done int tries to solve it:
- Checked keystore in google console
- Checked androidmanifest.xml as it is mentioned in troubleshooting page in gpgs
- Dobule checked the keys and password in build settings
- Checked that minify flags are disabled
- And again, created a internal build. Everything is working fine.

What should i do?

**Comment by mtemnikov** [comment]
I resolved it finally!

The thing was that switched on development flag in build settings. In that case build.gradle doesn’t include signing block by default. Therefore auth is failed. 

So, either you should remove development flag, or you should modify gradle file so it could sign the app.

**Comment by sonpt** [comment]
@mtemnikov Thanks for update!

Can you elaborate on how we should modify the gradle file?

**Comment by atadeu** [comment]
> I resolved it finally!
> 
> The thing was that switched on development flag in build settings. In that case build.gradle doesn’t include signing block by default. Therefore auth is failed.
> 
> So, either you should remove development flag, or you should modify gradle file so it could sign the app.

You have a solution ?

**Comment by olehkuznetsov** [comment]
Probably you need to link addition Android app in 'Google Play Console' with your release apk SHA1 key.
