### ISSUE TITLE
java.lang.IllegalStateException : Unity android app is crashing after activating the play game services plugin

### ISSUE THREAD

**Issue by ajayaradhya** [playgameservices/play-games-plugin-for-unity#2299]
**Unity Version:** 2018.2.4f1 personal

**Play services plugin version** : 0.9.50

Trying to add google play services to the game :
Here is the code where I'm activating the services :

    using UnityEngine;
    using GooglePlayGames;
    using GooglePlayGames.BasicApi;
    using System;
    
    public class PlayGamesController : MonoBehaviour
    {
        private bool isAuthenticated = false;
    
        // Use this for initialization
        void Start()
        {
            DontDestroyOnLoad(this);
    
            try
            {
                PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();
                PlayGamesPlatform.InitializeInstance(config);
                PlayGamesPlatform.DebugLogEnabled = true;
                PlayGamesPlatform.Activate();
                GameObject.FindGameObjectWithTag("LoginStatus").GetComponent<TMPro.TextMeshProUGUI>().text = "not connected";
                SignIn();
            }
            catch(Exception ex)
            {
                Debug.Log("ajay : unable to setup google play acc " + ex.InnerException);
            }
        }
    
        private void SignIn()
        {
            Debug.Log("Sign in called..");
            Social.localUser.Authenticate((bool success) => {
                isAuthenticated = success;
                GameObject.FindGameObjectWithTag("LoginStatus").GetComponent<TMPro.TextMeshProUGUI>().text = "success";
            });
        }
    
        public void AddScoreToLeaderBoard(string leaderBoard, int score)
        {
            if(isAuthenticated)
            {
                Social.ReportScore(score, leaderBoard, success => { });
            }
            else
            {
                Debug.Log("ajay : to connect to services");
            }
            
        }
    
        public void ShowLeaderBoard()
        {
            if (isAuthenticated)
            {
                Social.ShowLeaderboardUI();
            }
            else
            {
                Debug.Log("ajay : to connect to services");
            }
            
        }
    }

I have added this script to the gameobject which is available in the start scene. App is crashing.

I'm getting this error when starting the app :

    09-15 09:46:02.271 23508-23508/? I/art: Late-enabling -Xcheck:jni
    09-15 09:46:02.280 23508-23508/? D/TidaProvider: TidaProvider()
    09-15 09:46:02.286 23508-23508/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@64201ab
    09-15 09:46:02.307 23508-23508/com.namelessstudios.lazeradventures W/ActivityThread: Application com.namelessstudios.lazeradventures is waiting for the debugger on port 8100...
    09-15 09:46:02.308 23508-23508/com.namelessstudios.lazeradventures I/System.out: Sending WAIT chunk
    09-15 09:46:16.137 23508-23515/com.namelessstudios.lazeradventures I/art: Debugger is active
    09-15 09:46:16.319 23508-23508/com.namelessstudios.lazeradventures I/System.out: Debugger has connected
    waiting for debugger to settle...
    09-15 09:46:16.520 23508-23508/com.namelessstudios.lazeradventures I/System.out: waiting for debugger to settle...
    09-15 09:46:16.721 23508-23508/com.namelessstudios.lazeradventures I/System.out: waiting for debugger to settle...
    09-15 09:46:16.922 23508-23508/com.namelessstudios.lazeradventures I/System.out: waiting for debugger to settle...
    09-15 09:46:17.122 23508-23508/com.namelessstudios.lazeradventures I/System.out: waiting for debugger to settle...
    09-15 09:46:17.323 23508-23508/com.namelessstudios.lazeradventures I/System.out: waiting for debugger to settle...
    09-15 09:46:17.523 23508-23508/com.namelessstudios.lazeradventures I/System.out: waiting for debugger to settle...
    09-15 09:46:17.724 23508-23508/com.namelessstudios.lazeradventures I/System.out: debugger has settled (1390)
    09-15 09:46:18.632 23508-23508/com.namelessstudios.lazeradventures D/AccessibilityManager: current package=com.namelessstudios.lazeradventures, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=true, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
    09-15 09:46:19.656 23508-23508/com.namelessstudios.lazeradventures I/Unity: onResume
    09-15 09:46:19.737 23508-23760/com.namelessstudios.lazeradventures D/Unity: SetWindow 0 0xe7dc5508
    SetWindow 0 0xe7dc5508
    09-15 09:46:19.773 23508-23508/com.namelessstudios.lazeradventures E/HAL: PATH3 /odm/lib/hw/gralloc.qcom.so
    PATH2 /vendor/lib/hw/gralloc.qcom.so
    PATH1 /system/lib/hw/gralloc.qcom.so
    PATH3 /odm/lib/hw/gralloc.msm8953.so
    PATH2 /vendor/lib/hw/gralloc.msm8953.so
    PATH1 /system/lib/hw/gralloc.msm8953.so
    09-15 09:46:19.797 23508-23508/com.namelessstudios.lazeradventures I/Unity: windowFocusChanged: true
    09-15 09:46:19.831 23508-23760/com.namelessstudios.lazeradventures D/Unity: [VFS] Mount /data/app/com.namelessstudios.lazeradventures-1/base.apk
    09-15 09:46:19.861 23508-23760/com.namelessstudios.lazeradventures I/Unity: SystemInfo CPU = ARMv7 VFPv3 NEON, Cores = 8, Memory = 3598mb
    SystemInfo ARM big.LITTLE configuration: 8 big (mask: 0xff), 0 little (mask: 0x0)
    09-15 09:46:19.862 23508-23760/com.namelessstudios.lazeradventures I/Unity: ApplicationInfo com.namelessstudios.lazeradventures version 0.8 build d35f8069-d0db-4398-8df6-18418a4e0fe1
    Built from '2018.2/release' branch, Version '2018.2.4f1 (cb262d9ddeaf)', Build type 'Development', Scripting Backend 'mono'
    09-15 09:46:19.862 23508-23760/com.namelessstudios.lazeradventures D/Unity: [EGL] Attaching window :0xe7dc5508
    09-15 09:46:19.866 23508-23760/com.namelessstudios.lazeradventures D/Unity: Unable to find library path for 'monobdwgc-2.0'.
    09-15 09:46:20.224 23508-23760/com.namelessstudios.lazeradventures D/Unity: Mono path[0] = '/data/app/com.namelessstudios.lazeradventures-1/base.apk/assets/bin/Data/Managed'
    Mono config path = 'assets/bin/Data/Managed/etc'
    PlayerConnection initialized from /data/app/com.namelessstudios.lazeradventures-1/base.apk/assets/bin/Data (debug = 0)
    09-15 09:46:20.225 23508-23760/com.namelessstudios.lazeradventures D/Unity: PlayerConnection initialized network socket : 0.0.0.0 55049
    09-15 09:46:20.226 23508-23760/com.namelessstudios.lazeradventures D/Unity: PlayerConnection initialized unix socket : Unity-com.namelessstudios.lazeradventures
    09-15 09:46:20.229 23508-23760/com.namelessstudios.lazeradventures D/Unity: Multi-casting "[IP] 100.106.90.76 [Port] 55049 [Flags] 2 [Guid] 147100426 [EditorId] 2030289264 [Version] 1048832 [Id] AndroidPlayer(Xiaomi_Redmi_Note_4@100.106.90.76) [Debug] 0 [PackageName] AndroidPlayer" to [225.0.0.222:54997]...
    Started listening to [0.0.0.0:55049]
    09-15 09:46:20.232 23508-23519/com.namelessstudios.lazeradventures I/art: Background sticky concurrent mark sweep GC freed 36177(2MB) AllocSpace objects, 2(40KB) LOS objects, 36% free, 13MB/20MB, paused 269us total 379.616ms
    09-15 09:46:20.352 23508-23760/com.namelessstudios.lazeradventures D/Unity: InitializeScriptEngine OK (0xe04bfee0)
    PlayerConnection already initialized - listening to [0.0.0.0:55049]
    09-15 09:46:20.395 23508-23760/com.namelessstudios.lazeradventures D/Unity: PlayerInitEngineNoGraphics OK
    AndroidGraphics::Startup window =  0xe7dc5508
    [EGL] Attaching window :0xe7dc5508
    09-15 09:46:20.398 23508-23760/com.namelessstudios.lazeradventures I/Adreno: QUALCOMM build                   : 01d2d27, I3d52eaf367
    Build Date                       : 12/10/16
    OpenGL ES Shader Compiler Version: XE031.09.00.03
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
    09-15 09:46:20.403 23508-23760/com.namelessstudios.lazeradventures D/Unity: [EGL] Request: ES 3.1+AEP RGB0 000 0/0
    09-15 09:46:20.404 23508-23760/com.namelessstudios.lazeradventures D/Unity: [EGL] Checking ES 3.1 support...
    09-15 09:46:20.418 23508-23760/com.namelessstudios.lazeradventures D/Unity: [EGL] ES 3.1 support detected
    [EGL] Found: ID[1] ES 3.1+AEP RGB16 565 0/0
    GfxDevice: creating device client; threaded=1
    09-15 09:46:20.419 23508-23760/com.namelessstudios.lazeradventures D/Unity: [EGL] Request: ES 3.1+AEP RGB0 000 0/0
    09-15 09:46:20.420 23508-23760/com.namelessstudios.lazeradventures D/Unity: [EGL] Found: ID[1] ES 3.1+AEP RGB16 565 0/0
    [EGL] Request: ES 3.0 RGBA32 8888 0/0
    09-15 09:46:20.425 23508-23760/com.namelessstudios.lazeradventures D/Unity: [EGL] Found: ID[9] ES 3.0 RGBA32 8888 0/0 AFBT
    09-15 09:46:20.431 23508-23760/com.namelessstudios.lazeradventures D/Unity: ANativeWindow: (1080/1920) RequestedResolution: (0/0) RenderingResolution: (0/0) EGLSurface: (1080/1920)
    09-15 09:46:20.438 23508-23760/com.namelessstudios.lazeradventures D/Unity: Renderer: Adreno (TM) 506
    Vendor:   Qualcomm
    Version:  OpenGL ES 3.2 V@145.0 (GIT@I3d52eaf367)
    GLES:     3
     GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_multisampled_render_to_texture GL_OES_sha
    der_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_i
    nitializers
    09-15 09:46:20.448 23508-23760/com.namelessstudios.lazeradventures D/Unity: OPENGL LOG: Creating OpenGL ES 3.2 graphics device ; Context level  <OpenGL ES 3.1 AEP> ; Context handle -964190848
    09-15 09:46:20.450 23508-23760/com.namelessstudios.lazeradventures D/Unity: [EGL] Attaching window :0xe7dc5508
    09-15 09:46:20.452 23508-23760/com.namelessstudios.lazeradventures D/Unity: Requested framebuffer: resolution[1080x1920], rgba[8/8/8/8], depth+stencil[on], samples[1]
    Created framebuffer: resolution[1080x1920], rgba[8/8/8/8], depth+stencil[24/8], samples[0] 
    [EGL] Attaching window :0xe7dc5508
    09-15 09:46:20.453 23508-23760/com.namelessstudios.lazeradventures D/Unity: Initialize engine version: 2018.2.4f1 (cb262d9ddeaf)
    09-15 09:46:20.482 23508-23760/com.namelessstudios.lazeradventures D/Unity: Begin MonoManager ReloadAssembly
    09-15 09:46:20.491 23508-23802/com.namelessstudios.lazeradventures D/AudioTrack: Client defaulted notificationFrames to 1365 for frameCount 4096
    09-15 09:46:21.174 23508-23760/com.namelessstudios.lazeradventures D/Unity: - Completed reload, in  0.691 seconds
    09-15 09:46:21.312 23508-23760/com.namelessstudios.lazeradventures D/Unity: PlayerInitEngineGraphics OK
    09-15 09:46:21.314 23508-23760/com.namelessstudios.lazeradventures D/Unity: Found 40 native sensors
    09-15 09:46:21.316 23508-23760/com.namelessstudios.lazeradventures D/Unity: Sensor :        Accelerometer ( 1) ; 0.002396 / 0.00s ; BMI160 Accelerometer / BOSCH 
    09-15 09:46:21.326 23508-23760/com.namelessstudios.lazeradventures D/Unity: Sensor :        Accelerometer ( 1) ; 0.002396 / 0.00s ; BMI160 Accelerometer / BOSCH 
    09-15 09:46:21.352 23508-23760/com.namelessstudios.lazeradventures V/MediaRouter: Adding route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=null types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
    09-15 09:46:21.358 23508-23760/com.namelessstudios.lazeradventures V/MediaRouter: Updating audio routes: AudioRoutesInfo{ type=SPEAKER }
    09-15 09:46:21.363 23508-23760/com.namelessstudios.lazeradventures V/MediaRouter: Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=null types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
    09-15 09:46:23.407 23508-23760/com.namelessstudios.lazeradventures D/Unity: UnloadTime: 3.160000 ms
    09-15 09:46:23.412 23508-23760/com.namelessstudios.lazeradventures D/Unity: UUID: 6a346c9f25c95150 => ea77e95b4c608cc3c783300d91fc4c89
    09-15 09:46:23.637 23508-23760/com.namelessstudios.lazeradventures D/Unity: Sensor :        Accelerometer ( 1) ; 0.002396 / 0.00s ; BMI160 Accelerometer / BOSCH 
    09-15 09:46:23.653 23508-23760/com.namelessstudios.lazeradventures D/Unity: Choreographer available: Enabling VSYNC timing
    09-15 09:46:23.659 23508-23852/com.namelessstudios.lazeradventures D/AudioTrack: Client defaulted notificationFrames to 1365 for frameCount 4096
    09-15 09:46:23.682 23508-23788/com.namelessstudios.lazeradventures D/NetworkSecurityConfig: No Network Security Config specified, using platform default
    09-15 09:46:23.750 23508-23760/com.namelessstudios.lazeradventures I/Unity: Sign in called..
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:Log(Object)
    PlayGamesController:SignIn() (at D:\Projects\LazerDefender\Assets\Scripts\PlayGamesController.cs:32)
    PlayGamesController:Start() (at D:\Projects\LazerDefender\Assets\Scripts\PlayGamesController.cs:22)
     
    (Filename: D Line: 0)
    09-15 09:46:24.255 23508-23760/com.namelessstudios.lazeradventures D/GamesUnitySDK: Performing Android initialization of the GPG SDK
    09-15 09:46:24.394 23508-23760/com.namelessstudios.lazeradventures I/Unity: Building GPG services, implicitly attempts silent auth
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:Log(Object)
    GooglePlayGames.Native.NativeClient:InitializeGameServices() (at D:\Projects\LazerDefender\Assets\GooglePlayGames\Platforms\Native\NativeClient.cs:222)
    GooglePlayGames.Native.NativeClient:Authenticate(Action`2, Boolean) (at D:\Projects\LazerDefender\Assets\GooglePlayGames\Platforms\Native\NativeClient.cs:139)
    GooglePlayGames.PlayGamesPlatform:Authenticate(Action`2, Boolean) (at D:\Projects\LazerDefender\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:414)
    GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at D:\Projects\LazerDefender\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:383)
    GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at D:\Projects\LazerDefender\Assets\GooglePlayGames\ISocialPlatform\
    09-15 09:46:24.398 23508-23760/com.namelessstudios.lazeradventures I/GamesNativeSDK: Using existing jar.
    Writing 1941 bytes to jar file
    09-15 09:46:26.791 23508-23852/com.namelessstudios.lazeradventures W/AudioTrack: releaseBuffer() track 0xc22f6900 disabled due to previous underrun, restarting
    09-15 09:46:26.798 23508-23760/com.namelessstudios.lazeradventures I/GamesNativeSDK: Using existing jar.
    Writing 1066 bytes to jar file
    09-15 09:46:28.171 23508-23854/com.namelessstudios.lazeradventures I/Choreographer: Skipped 74 frames!  The application may be doing too much work on its main thread.
    09-15 09:46:28.181 23508-23760/com.namelessstudios.lazeradventures W/PopupManager: You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
    09-15 09:46:28.185 23508-23915/com.namelessstudios.lazeradventures I/GamesNativeSDK: Auth operation started: SIGN IN
    Connecting to Google Play...
    09-15 09:46:28.244 23508-23513/com.namelessstudios.lazeradventures I/art: Do partial code cache collection, code=29KB, data=29KB
    09-15 09:46:28.245 23508-23513/com.namelessstudios.lazeradventures I/art: After code cache collection, code=27KB, data=28KB
    Increasing code cache capacity to 128KB
    09-15 09:46:28.255 23508-23508/com.namelessstudios.lazeradventures D/AndroidRuntime: Shutting down VM
    09-15 09:46:28.258 23508-23508/com.namelessstudios.lazeradventures E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.namelessstudios.lazeradventures, PID: 23508
    java.lang.IllegalStateException: A fatal developer error has occurred. Check the logs for further information.
        at com.google.android.gms.common.internal.zze.zzv(Unknown Source)
        at com.google.android.gms.common.internal.zzi.zzakg(Unknown Source)
        at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6365)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
    09-15 09:46:28.305 23508-23760/com.namelessstudios.lazeradventures W/Unity: !!! [Play Games Plugin DLL] 09/15/18 9:46:28 +05:30 WARNING: Creating new PlayGamesPlatform
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:LogWarning(Object)
    GooglePlayGames.OurUtils.<w>c__AnonStorey1:<>m__0() (at D:\Projects\LazerDefender\Assets\GooglePlayGames\OurUtils\Logger.cs:68)
    GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at D:\Projects\LazerDefender\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
     
    (Filename: D Line: 0)
    09-15 09:46:28.306 23508-23760/com.namelessstudios.lazeradventures I/Unity:  [Play Games Plugin DLL] 09/15/18 9:46:28 +05:30 DEBUG: Activating PlayGamesPlatform.
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:Log(Object)
    GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at D:\Projects\LazerDefender\Assets\GooglePlayGames\OurUtils\Logger.cs:59)
    GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at D:\Projects\LazerDefender\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
     
    (Filename: D Line: 0)
    09-15 09:46:28.308 23508-23760/com.namelessstudios.lazeradventures I/Unity:  [Play Games Plugin DLL] 09/15/18 9:46:28 +05:30 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:Log(Object)
    GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at D:\Projects\LazerDefender\Assets\GooglePlayGames\OurUtils\Logger.cs:59)
    GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at D:\Projects\LazerDefender\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
     
    (Filename: D Line: 0)
    09-15 09:46:28.309 23508-23760/com.namelessstudios.lazeradventures I/Unity:  [Play Games Plugin DLL] 09/15/18 9:46:28 +05:30 DEBUG: Creating platform-specific Play Games client.
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:Log(Object)
    GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at D:\Projects\LazerDefender\Assets\GooglePlayGames\OurUtils\Logger.cs:59)
    GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at D:\Projects\LazerDefender\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
     
    (Filename: D Line: 0)
    09-15 09:46:28.310 23508-23760/com.namelessstudios.lazeradventures I/Unity:  [Play Games Plugin DLL] 09/15/18 9:46:28 +05:30 DEBUG: Creating Android IPlayGamesClient Client
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:Log(Object)
    GooglePlayGames.OurUtils.<d>c__AnonStorey0:<>m__0() (at D:\Projects\LazerDefender\Assets\GooglePlayGames\OurUtils\Logger.cs:59)
    GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at D:\Projects\LazerDefender\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
     
    (Filename: D Line: 0)
    09-15 09:46:28.669 23508-23760/com.namelessstudios.lazeradventures D/Unity: ANativeWindow: (1080/1920) RequestedResolution: (0/0) RenderingResolution: (0/0) EGLSurface: (1080/1920)

**Comment by ajayaradhya** [comment]
https://stackoverflow.com/questions/52341549/java-lang-illegalstateexception-unity-android-app-is-crashing-after-activating

**Comment by olehkuznetsov** [comment]
Should be fixed in 0.9.52.
