### ISSUE TITLE
Google login will appear repeatedly and will not progress.

### ISSUE THREAD

**Issue by pa01xhzvksbf** [playgameservices/play-games-plugin-for-unity#2303]
There is a problem with the released application.
Google login will be repeated and will not proceed.

The reproducibility is low, even the development team has reproduced only once.
However, users still have problems reporting.

It appears to occur when you have multiple Google accounts on your device.

Looking at the log, it looks like the following flow.

1. CommonStatusCodes.SIGN_IN_REQUIRED error occurs during initial Google authentication (error code = 4)
2. If you try to authentication again, the sign-in activity becomes active many times

`
D/ActivityTrigger(1776): activityResumeTrigger: The activity in ApplicationInfo{99b07ff com.google.android.gms} is now in focus and seems to be in full-screen mode
E/ActivityTrigger(1776): activityResumeTrigger: not whiteListedcom.google.android.gms/com.google.android.gms.auth.api.signin.ui.SignInActivity/13280021
D/ActivityTrigger(1776): activityResumeTrigger: The activity in ApplicationInfo{99b07ff com.google.android.gms} is now in focus and seems to be in full-screen mode
E/ActivityTrigger(1776): activityResumeTrigger: not whiteListedcom.google.android.gms/com.google.android.gms.auth.api.signin.ui.SignInActivity/13280021
…
`

There are also users who can improve by deleting the access right of the application from the following URL.
Some users do not improve.
https://myaccount.google.com/permissions

In version 0.9.34 there was no problem.
There is a problem in version 0.9.41 or later.

Is there a way to solve it?

Thanks.

**Comment by pa01xhzvksbf** [comment]
・Log when problem occurred

> 09-12 11:02:29.997: I/Unity(20025): Starting Auth with token client.
> 09-12 11:02:30.020: W/Unity(20025): !!! [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 WARNING: Creating new PlayGamesPlatform
> 09-12 11:02:30.020: W/Unity(20025):  
> 09-12 11:02:30.020: W/Unity(20025): (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
> 09-12 11:02:30.020: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Activating PlayGamesPlatform.
> 09-12 11:02:30.020: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
> 09-12 11:02:30.020: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Creating platform-specific Play Games client.
> 09-12 11:02:30.020: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Creating Android IPlayGamesClient Client
> 09-12 11:02:30.021: D/TokenFragment(20025): Creating fragment
> 09-12 11:02:30.022: I/Unity(20025): ---- [0] -- 117
> 09-12 11:02:30.042: D/TokenFragment(20025): onStart()
> 09-12 11:02:30.043: D/TokenFragment(20025): onResume called
> 09-12 11:02:30.043: D/TokenFragment(20025): Building client for: 1aeb02c (a:true e:false i:true wc: 165982058050-684s0q79j28ujn0bpph9fpf62jbevphm.apps.googleusercontent.com f: false)
> 09-12 11:02:30.050: W/PopupManager(20025): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
> 09-12 11:02:30.053: D/TokenFragment(20025): No connected Games API, waiting for onConnected
> 09-12 11:02:30.053: D/TokenFragment(20025): Done with processRequest, result is pending.
> 09-12 11:02:30.058: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:30.058: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:30.058: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:30.061: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:30.061: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:30.061: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:30.071: W/GamesServiceBroker(11248): Client connected with SDK 11910000, Services 13280021, and Games 65510048
> 09-12 11:02:30.072: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:30.072: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:30.072: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:30.087: W/GamesServiceBroker(11248): Client connected with SDK 13589000, Services 13280021, and Games 65510048
> 09-12 11:02:30.099: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:30.099: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:30.099: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:30.114: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:30.114: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:30.114: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:30.122: W/AppOps(1776): Bad call: specified package com.google.android.play.games under uid 10554 but it is really 10305
> 09-12 11:02:30.122: W/AppOps(1776): java.lang.RuntimeException: here
> 09-12 11:02:30.122: W/AppOps(1776): 	at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1364)
> 09-12 11:02:30.122: W/AppOps(1776): 	at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1071)
> 09-12 11:02:30.122: W/AppOps(1776): 	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
> 09-12 11:02:30.122: W/AppOps(1776): 	at android.os.Binder.execTransact(Binder.java:674)
> 09-12 11:02:30.153: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:30.153: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:30.153: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:30.156: W/ChimeraUtils(11152): Non Chimera context
> 09-12 11:02:30.156: W/ChimeraUtils(11152): Non Chimera context
> 09-12 11:02:30.167: W/GamesServiceBroker(11248): Client connected with SDK 13589000, Services 13280021, and Games 65510048
> 09-12 11:02:30.179: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:30.179: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:30.179: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:30.200: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:30.200: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:30.200: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:30.223: W/GamesServiceBroker(11248): Client connected with SDK 13589000, Services 13280021, and Games 65510048
> 09-12 11:02:30.231: I/TokenFragment(20025): onConnected called
> 09-12 11:02:30.245: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:30.245: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:30.245: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:30.282: W/GamesServiceBroker(11248): Client connected with SDK 13280000, Services 13280021, and Games 65510048
> 09-12 11:02:30.309: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:30.309: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:30.309: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:30.315: W/GamesServiceBroker(11248): Client connected with SDK 13589000, Services 13280021, and Games 65510048
> 09-12 11:02:30.499: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:30.499: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:30.499: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:30.549: W/GamesServiceBroker(11248): Client connected with SDK 13589000, Services 13280021, and Games 65510048
> 09-12 11:02:30.550: E/TokenFragment(20025): Error with silentSignIn when connected: Status{statusCode=4: , resolution=PendingIntent{646621d: android.os.BinderProxy@d4acc92}}
> 09-12 11:02:30.550: E/TokenFragment(20025): Setting result error code to: 4
> 09-12 11:02:30.584: D/TokenPendingResult(20025):  Calling onResult for callback: GooglePlayGames.Android.TokenResultCallback result: Status: Status{statusCode=SIGN_IN_REQUIRED, resolution=null} email: <null> id:<null> access: <null>
> 09-12 11:02:30.592: D/GamesUnitySDK(20025): Performing Android initialization of the GPG SDK
> 09-12 11:02:30.608: I/Unity(20025): Building GPG services, implicitly attempts silent auth
> 09-12 11:02:30.609: I/GamesNativeSDK(20025): Using existing jar.
> 09-12 11:02:30.609: I/GamesNativeSDK(20025): Writing 1941 bytes to jar file
> 09-12 11:02:30.612: W/zygote(20025): Skipping duplicate class check due to unrecognized classloader
> 09-12 11:02:30.619: I/GamesNativeSDK(20025): Using existing jar.
> 09-12 11:02:30.619: I/GamesNativeSDK(20025): Writing 1066 bytes to jar file
> 09-12 11:02:30.620: W/zygote(20025): Skipping duplicate class check due to unrecognized classloader
> 09-12 11:02:30.625: W/PopupManager(20025): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
> 09-12 11:02:30.626: I/GamesNativeSDK(20025): Auth operation started: SIGN IN
> 09-12 11:02:30.626: I/GamesNativeSDK(20025): Connecting to Google Play...
> 09-12 11:02:30.633: W/GamesServiceBroker(11248): Client connected with SDK 11910000, Services 13280021, and Games 65510048
> 09-12 11:02:30.647: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: 4
> 09-12 11:02:30.647: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
> 09-12 11:02:30.647: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: there are pending auth callbacks - starting AuthUI
> 09-12 11:02:30.657: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:30.657: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:30.657: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:30.667: W/GamesServiceBroker(11248): Client connected with SDK 13589000, Services 13280021, and Games 65510048
> 09-12 11:02:30.696: W/AppOps(1776): Bad call: specified package com.google.android.play.games under uid 10554 but it is really 10305
> 09-12 11:02:30.696: W/AppOps(1776): java.lang.RuntimeException: here
> 09-12 11:02:30.696: W/AppOps(1776): 	at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1364)
> 09-12 11:02:30.696: W/AppOps(1776): 	at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1071)
> 09-12 11:02:30.696: W/AppOps(1776): 	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
> 09-12 11:02:30.696: W/AppOps(1776): 	at android.os.Binder.execTransact(Binder.java:674)
> 09-12 11:02:30.744: W/GamesServiceBroker(11248): Client connected with SDK 13589000, Services 13280021, and Games 65510048
> 09-12 11:02:30.769: V/GamesNativeSDK(20025): Play Games callback indicates connection.
> 09-12 11:02:30.792: I/GamesNativeSDK(20025): Successfully connected to Google Play.
> 09-12 11:02:30.813: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
> 09-12 11:02:30.828: W/AppOps(1776): Bad call: specified package com.google.android.play.games under uid 10554 but it is really 10305
> 09-12 11:02:30.828: W/AppOps(1776): java.lang.RuntimeException: here
> 09-12 11:02:30.828: W/AppOps(1776): 	at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1364)
> 09-12 11:02:30.828: W/AppOps(1776): 	at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1071)
> 09-12 11:02:30.828: W/AppOps(1776): 	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
> 09-12 11:02:30.828: W/AppOps(1776): 	at android.os.Binder.execTransact(Binder.java:674)
> 09-12 11:02:30.829: I/chatty(1776): uid=1000(system) Binder:1776_2 identical 1 line
> 09-12 11:02:30.838: W/AppOps(1776): Bad call: specified package com.google.android.play.games under uid 10554 but it is really 10305
> 09-12 11:02:30.838: W/AppOps(1776): java.lang.RuntimeException: here
> 09-12 11:02:30.838: W/AppOps(1776): 	at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1364)
> 09-12 11:02:30.838: W/AppOps(1776): 	at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1071)
> 09-12 11:02:30.838: W/AppOps(1776): 	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
> 09-12 11:02:30.838: W/AppOps(1776): 	at android.os.Binder.execTransact(Binder.java:674)
> 09-12 11:02:30.839: W/AppOps(1776): Bad call: specified package com.google.android.play.games under uid 10554 but it is really 10305
> 09-12 11:02:30.839: W/AppOps(1776): java.lang.RuntimeException: here
> 09-12 11:02:30.839: W/AppOps(1776): 	at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1364)
> 09-12 11:02:30.839: W/AppOps(1776): 	at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1071)
> 09-12 11:02:30.839: W/AppOps(1776): 	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
> 09-12 11:02:30.839: W/AppOps(1776): 	at android.os.Binder.execTransact(Binder.java:674)
> 09-12 11:02:30.880: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback
> 09-12 11:02:30.881: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Populating User
> 09-12 11:02:30.881: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Found User: [Player: 'XXXXXX' (id gXXXXXXXXXX)]
> 09-12 11:02:30.881: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Maybe finish for User
> 09-12 11:02:30.881: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Auth not finished. User=[Player: 'XXXXXX' (id gXXXXXXXXXX)] achievements=
> 09-12 11:02:30.881: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback
> 09-12 11:02:30.881: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Populating Achievements, status = VALID
> 09-12 11:02:30.913: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Found 14 Achievements
> 09-12 11:02:30.913: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Maybe finish for Achievements
> 09-12 11:02:30.913: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Auth finished. Proceeding.
> 09-12 11:02:30.913: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Invoking Callbacks: System.Action`2[System.Boolean,System.String]
> 09-12 11:02:30.946: I/Unity(20025):  [Play Games Plugin DLL] 09/12/18 11:02:30 +09:00 DEBUG: Invoking user callback on game thread
> 09-12 11:02:31.974: W/memtrack@1.0-se(874): type=1400 audit(0.0:2728): avc: denied { search } for name="proc" dev="debugfs" ino=17258 scontext=u:r:hal_memtrack_default:s0 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0 ppid=1 pcomm="init" pgid=1 pgcomm="init"
> 09-12 11:02:32.074: I/chatty(874): uid=1000(system) memtrack@1.0-se identical 2 lines
> 09-12 11:02:32.074: W/memtrack@1.0-se(874): type=1400 audit(0.0:2731): avc: denied { search } for name="proc" dev="debugfs" ino=17258 scontext=u:r:hal_memtrack_default:s0 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0 ppid=1 pcomm="init" pgid=1 pgcomm="init"
> 09-12 11:02:32.939: E/SurfaceFlinger(925): Failed to find layer (#0) in layer parent (no-parent).
> 09-12 11:02:33.309: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:33.309: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:33.309: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:33.942: W/Unity(20025): GoogleAuthCode is Empty.
> 09-12 11:02:33.942: W/Unity(20025):  
> 09-12 11:02:33.942: W/Unity(20025): (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
> 09-12 11:02:35.851: V/GamesNativeSDK(20025): Detaching from JVM on thread main_dispatch
> 09-12 11:02:38.007: I/Unity(20025): ---- [0] -- 73
> 09-12 11:02:38.028: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:38.028: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.028: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.044: W/GamesServiceBroker(11248): Client connected with SDK 13280000, Services 13280021, and Games 65510048
> 09-12 11:02:38.049: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:38.049: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.049: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.065: W/GamesServiceBroker(11248): Client connected with SDK 13589000, Services 13280021, and Games 65510048
> 09-12 11:02:38.077: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:38.077: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.077: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.096: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:38.096: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.096: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.126: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:38.126: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.126: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.320: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:38.320: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.320: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.343: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:38.343: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.343: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.375: W/GamesServiceBroker(11248): Client connected with SDK 13589000, Services 13280021, and Games 65510048
> 09-12 11:02:38.383: I/ActivityManager(1776): START u0 {act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.xxx.yyy cmp=com.xxx.yyy/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (has extras)} from uid 10554
> 09-12 11:02:38.389: D/ActivityTrigger(1776): activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{7c9d9af com.xxx.yyy}
> 09-12 11:02:38.389: E/ActivityTrigger(1776): activityStartTrigger: not whiteListedcom.xxx.yyy/com.google.android.gms.auth.api.signin.internal.SignInHubActivity/179
> 09-12 11:02:38.390: D/CompatibilityInfo(1776): mCompatibilityFlags - 0
> 09-12 11:02:38.390: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.390: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.390: D/ActivityTrigger(1776): activityResumeTrigger: The activity in ApplicationInfo{7c9d9af com.xxx.yyy} is now in focus and seems to be in full-screen mode
> 09-12 11:02:38.384: W/memtrack@1.0-se(874): type=1400 audit(0.0:2734): avc: denied { search } for name="proc" dev="debugfs" ino=17258 scontext=u:r:hal_memtrack_default:s0 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0 ppid=1 pcomm="init" pgid=1 pgcomm="init"
> 09-12 11:02:38.390: E/ActivityTrigger(1776): activityResumeTrigger: not whiteListedcom.xxx.yyy/com.google.android.gms.auth.api.signin.internal.SignInHubActivity/179
> 09-12 11:02:38.390: D/ActivityTrigger(1776): ActivityTrigger activityPauseTrigger 
> 09-12 11:02:38.384: W/memtrack@1.0-se(874): type=1400 audit(0.0:2735): avc: denied { search } for name="proc" dev="debugfs" ino=17258 scontext=u:r:hal_memtrack_default:s0 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0 ppid=1 pcomm="init" pgid=1 pgcomm="init"
> 09-12 11:02:38.393: I/ArPresto(20025): ArCoreUnity_onUnityPlayerPause
> 09-12 11:02:38.393: I/ArPresto(20025): ArPresto_handleActivityPause
> 09-12 11:02:38.411: D/AudioTrack(20025): stop() called with 772032 frames delivered
> 09-12 11:02:38.411: D/(20025): PlayerBase::stop() from IPlayer
> 09-12 11:02:38.417: D/ActivityTrigger(1776): activityResumeTrigger: The activity in ApplicationInfo{7c9d9af com.xxx.yyy} is now in focus and seems to be in full-screen mode
> 09-12 11:02:38.417: E/ActivityTrigger(1776): activityResumeTrigger: not whiteListedcom.xxx.yyy/com.google.android.gms.auth.api.signin.internal.SignInHubActivity/179
> 09-12 11:02:38.418: D/CompatibilityInfo(1776): mCompatibilityFlags - 0
> 09-12 11:02:38.418: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.418: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.423: I/ActivityManager(1776): START u0 {act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.google.android.gms cmp=com.google.android.gms/.auth.api.signin.ui.SignInActivity (has extras)} from uid 10554
> 09-12 11:02:38.426: D/ActivityTrigger(1776): activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{99b07ff com.google.android.gms}
> 09-12 11:02:38.426: E/ActivityTrigger(1776): activityStartTrigger: not whiteListedcom.google.android.gms/com.google.android.gms.auth.api.signin.ui.SignInActivity/13280021
> 09-12 11:02:38.426: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:38.426: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.426: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.427: D/ActivityTrigger(1776): activityResumeTrigger: The activity in ApplicationInfo{99b07ff com.google.android.gms} is now in focus and seems to be in full-screen mode
> 09-12 11:02:38.427: E/ActivityTrigger(1776): activityResumeTrigger: not whiteListedcom.google.android.gms/com.google.android.gms.auth.api.signin.ui.SignInActivity/13280021
> 09-12 11:02:38.427: D/ActivityTrigger(1776): ActivityTrigger activityPauseTrigger 
> 09-12 11:02:38.432: D/OpenGLRenderer(20025): HWUI GL Pipeline
> 09-12 11:02:38.436: D/ActivityTrigger(1776): activityResumeTrigger: The activity in ApplicationInfo{99b07ff com.google.android.gms} is now in focus and seems to be in full-screen mode
> 09-12 11:02:38.437: E/ActivityTrigger(1776): activityResumeTrigger: not whiteListedcom.google.android.gms/com.google.android.gms.auth.api.signin.ui.SignInActivity/13280021
> 09-12 11:02:38.440: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:38.440: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.440: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.447: I/OpenGLRenderer(20025): Initialized EGL, version 1.4
> 09-12 11:02:38.447: D/OpenGLRenderer(20025): Swap behavior 2
> 09-12 11:02:38.462: I/InputDispatcher(1776): Focus entered window: Window{1a61c93 u0 com.google.android.gms/com.google.android.gms.auth.api.signin.ui.SignInActivity}
> 09-12 11:02:38.468: W/GamesServiceBroker(11248): Client connected with SDK 13280000, Services 13280021, and Games 65510048
> 09-12 11:02:38.471: W/GamesServiceBroker(11248): Client connected with SDK 13589000, Services 13280021, and Games 65510048
> 09-12 11:02:38.475: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:38.475: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.475: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.480: I/ActivityManager(1776): Displayed com.google.android.gms/.auth.api.signin.ui.SignInActivity: +40ms (total +60ms)
> 09-12 11:02:38.483: I/Timeline(1776): Timeline: Activity_windows_visible id: ActivityRecord{8a9265d u0 com.xxx.yyy/com.google.android.gms.auth.api.signin.internal.SignInHubActivity t2309} time:1762480 diff:91 start:lukewarm|top-activity batt:94|2 mw:off|1 mem:1553788|0|74|21|23 cpu:[1900800, 1900800, 1900800, 1900800, 2361600, 2361600, 2361600, 2361600]
> 09-12 11:02:38.600: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:38.600: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.600: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.611: W/GamesServiceBroker(11248): Client connected with SDK 13589000, Services 13280021, and Games 65510048
> 09-12 11:02:38.614: I/ActivityManager(1776): START u0 {cmp=com.google.android.gms/.common.api.GoogleApiActivity (has extras)} from uid 10077
> 09-12 11:02:38.619: D/ActivityTrigger(1776): activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{a5f5083 com.google.android.gms}
> 09-12 11:02:38.619: E/ActivityTrigger(1776): activityStartTrigger: not whiteListedcom.google.android.gms/com.google.android.gms.common.api.GoogleApiActivity/13280021
> 09-12 11:02:38.619: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:38.619: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.619: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.621: D/ActivityTrigger(1776): activityResumeTrigger: The activity in ApplicationInfo{a5f5083 com.google.android.gms} is now in focus and seems to be in full-screen mode
> 09-12 11:02:38.621: E/ActivityTrigger(1776): activityResumeTrigger: not whiteListedcom.google.android.gms/com.google.android.gms.common.api.GoogleApiActivity/13280021
> 09-12 11:02:38.621: D/ActivityTrigger(1776): ActivityTrigger activityPauseTrigger 
> 09-12 11:02:38.639: D/ActivityTrigger(1776): activityResumeTrigger: The activity in ApplicationInfo{a5f5083 com.google.android.gms} is now in focus and seems to be in full-screen mode
> 09-12 11:02:38.639: E/ActivityTrigger(1776): activityResumeTrigger: not whiteListedcom.google.android.gms/com.google.android.gms.common.api.GoogleApiActivity/13280021
> 09-12 11:02:38.641: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:38.641: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.641: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.657: I/ActivityManager(1776): START u0 {act=com.google.android.gms.games.SIGN_IN flg=0x4000000 pkg=com.google.android.play.games cmp=com.google.android.play.games/com.google.android.gms.games.ui.signin.SignInActivity (has extras)} from uid 10077
> 09-12 11:02:38.661: D/ActivityTrigger(1776): activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{ce26148 com.google.android.play.games}
> 09-12 11:02:38.661: E/ActivityTrigger(1776): activityStartTrigger: not whiteListedcom.google.android.play.games/com.google.android.gms.games.ui.signin.SignInActivity/65510048
> 09-12 11:02:38.661: D/CompatibilityInfo(1776): mCompatibilityFlags - 0
> 09-12 11:02:38.661: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.661: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.662: D/ActivityTrigger(1776): activityResumeTrigger: The activity in ApplicationInfo{ce26148 com.google.android.play.games} is now in focus and seems to be in full-screen mode
> 09-12 11:02:38.662: E/ActivityTrigger(1776): activityResumeTrigger: not whiteListedcom.google.android.play.games/com.google.android.gms.games.ui.signin.SignInActivity/65510048
> 09-12 11:02:38.662: D/ActivityTrigger(1776): ActivityTrigger activityPauseTrigger 
> 09-12 11:02:38.680: D/ActivityTrigger(1776): activityResumeTrigger: The activity in ApplicationInfo{ce26148 com.google.android.play.games} is now in focus and seems to be in full-screen mode
> 09-12 11:02:38.680: E/ActivityTrigger(1776): activityResumeTrigger: not whiteListedcom.google.android.play.games/com.google.android.gms.games.ui.signin.SignInActivity/65510048
> 09-12 11:02:38.684: D/CompatibilityInfo(1776): mCompatibilityFlags - 0
> 09-12 11:02:38.684: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.684: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.690: I/AppLifecycleTracker(19887): onActivityCreated: 
> 09-12 11:02:38.724: I/AppLifecycleTracker(19887): onActivityStarted: 
> 09-12 11:02:38.727: D/CompatibilityInfo(1776): mCompatibilityFlags - 10
> 09-12 11:02:38.727: D/CompatibilityInfo(1776): applicationDensity - 480
> 09-12 11:02:38.727: D/CompatibilityInfo(1776): applicationScale - 1.0
> 09-12 11:02:38.729: I/AppLifecycleTracker(19887): onActivityResumed: 
> 
>

**Comment by tenpn** [comment]
is this the same as https://github.com/playgameservices/play-games-plugin-for-unity/issues/2298 or subtly different?

**Comment by pa01xhzvksbf** [comment]
My problem is that the rendering of authentication will be forever repeated and unable to proceed, which is different from the problem of # 2298.

However, I guess that the cause of my problem is inconsistency of access authority.
Just trying to add ".AddOauthScope (" profile ")".

When .AddOauthScope ("profile") is done, the authentication dialog will be displayed again after several hours as in # 2298.
Since this problem could not be avoided by setting etc., we made the following response.

1. When the authentication succeeds, the success flag is saved in the terminal
2. If the success flag is present, do not do ". AddOauthScope (" profile ")"

**Comment by olehkuznetsov** [comment]
Should be fixed already in Play Games application. Feel free to reopen if still reproduces for you.
