### ISSUE TITLE
Can't report score to leaderboard 

### ISSUE THREAD

**Issue by JustinCraver** [playgameservices/play-games-plugin-for-unity#2305]
using Unity 2018.2.7f1
GPG plugin 0.9.50

after finally getting player Authentication and login working using this plugin now I have run into a problem where I can't report scores to the leaderboard 
I can report Achievements and I can view the leaderboard UI and everything else but I cannot report a score to the leaderboard.
here is the code im using to try to report the score 
`Social.ReportScore(score, leaderBoardID, success =>
                {
                    Debug.Log(success ? ("Reported score successfully" + leaderBoardID) : ("Failed to report score" + leaderBoardID));
                });`

also this code using the Unity Social API works perfectly on ios
but on android I get this error 

java.lang.IllegalStateException: Leaderboard ID must not be null or empty.

but I know the string is not empty i can print the string and it does indeed contain the leaderboard ID
so i'm not sure why i'm getting a error saying its empty 
any help would be greatly appreciated.

**Comment by waqasbhattii** [comment]
i cant see Google Services login screen when i use this package. I updated my game after integrating this plugin but every time the logcat says "Failed to sign in into google". I am not using google play store app signing method rather i am just opting out to google app signing. Please tell whether your are able to sign in. If yes, what did you to successfully login. Thanks

**Comment by olehkuznetsov** [comment]
It seems leaderBoardID value is null or empty.
You can add Debug.Log ("leaderBoardID=" + leaderBoardID); before Social.ReportScore call to check that.
