### ISSUE TITLE
Using Game Analytics, Audience Network and Google Play Services

### ISSUE THREAD

**Issue by pranavt07** [playgameservices/play-games-plugin-for-unity#2306]
I am currently trying to use all 3 APIs in the same project and I am getting a "Multiple Dex Files" Error while trying to make a build for Android.

I approached Game Analytics for a solution and they suggested me the following - 
two different versions of play services are being used at this moment in your project; 11.6.2 and 15.0.1. In order to use GA plugin successfully alongside other plug in's, the other plugin must match our version of 15.0.1. You can contact the makers of the other plugin, and request for the plugin to updated to this version.

Even if I delete the older version files, Unity starts recompiling after it is done and restores them.

The following is the error I am getting in Unity -
<img width="791" alt="screen shot 2018-09-21 at 9 07 17 am" src="https://user-images.githubusercontent.com/43460823/45859022-cd6f8680-bd7d-11e8-9674-17fd260b6252.png">

**Comment by olehkuznetsov** [comment]
Fixed in 0.9.51.
