### ISSUE TITLE
Real-time multiplayer "Create with invitation screen" issue when pressing back button or calling PlayGamesPlatform.Instance.RealTime.AcceptFromInbox(this);.

### ISSUE THREAD

**Issue by srcsameer** [playgameservices/play-games-plugin-for-unity#2309]
Hi! everyone i need some help on real-time multiplayer implementation. Whenever i am trying to call:

`PlayGamesPlatform.Instance.RealTime.AcceptFromInbox(this);`

OR trying to call play with a friend with

`
   const int MinOpponents = 1, MaxOpponents = 3;
    const int GameVariant = 0;
    PlayGamesPlatform.Instance.RealTime.CreateWithInvitationScreen(MinOpponents, MaxOpponents,
                GameVariant, this);`

and all the time when i am pressing back button createquickmatch is getting called by it self can anyone help me what's actually wrong here?

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
