### ISSUE TITLE
cannot get this plugin to work with my admob interstitial plugin(not VNITS)

### ISSUE THREAD

**Issue by siliconic001** [playgameservices/play-games-plugin-for-unity#231]
this is the plugin im using http://fastegggames.com/s/PlayAdsExample2.unitypackage
when i import this playads plugin the playgamesplugin stops working.
how can i get these plugins to work together?

**Comment by claywilkinson** [comment]
@siliconic001  - did that thread help you out?  Please reopen and add some specifics to your problem if you are still having issues.
