### ISSUE TITLE
Crash on initialization

### ISSUE THREAD

**Issue by femoreti** [playgameservices/play-games-plugin-for-unity#2320]
Hey guys, I'm currently working with admob, but when I tried to integrate playgameservices i couldn't run my app anymore.

On LogCat i didn't get any errors, only this:

> 0-08 22:02:49.020  3663  5179 I ActivityManager: Start proc 7500:com.FMGames.HiddenTargets/u0a331 for activity com.FMGames.HiddenTargets/com.unity3d.player.UnityPlayerActivity
10-08 22:02:49.057  3663  6586 I ActivityManager: DSS on for com.FMGames.HiddenTargets and scale is 1.0
10-08 22:02:49.107  3663  3673 W ActivityManager: crash : com.FMGames.HiddenTargets,0
10-08 22:02:49.108  3663  3673 W ActivityManager:   Force finishing activity com.FMGames.HiddenTargets/com.unity3d.player.UnityPlayerActivity
10-08 22:02:49.119  3663  3686 I ActivityManager: Showing crash dialog for package com.FMGames.HiddenTargets u0
10-08 22:02:49.236  3663  5179 D PackageManager: getSelectedMetaData : packageName(com.FMGames.HiddenTargets) or Metadata strings {[Ljava.lang.String;@f7da0a3}
10-08 22:02:49.611  3663  3685 W ActivityManager: Activity pause timeout for ActivityRecord{6696d0a u0 com.FMGames.HiddenTargets/com.unity3d.player.UnityPlayerActivity t342 f}

This could be a problem with Unity version? I'm using 2018.2.11f1, already tried with Gradle and Internal. And replace \ for \u003 on manifest.xml file.

**Comment by stefanandy** [comment]
I have the exact same problem, i use unity 2018.2.10f1, anyone have any ideea hot to fix it ?

**Comment by femoreti** [comment]
Hey stefan, I solved the problem doing these steps:

Remove both plugins from your project then do this.
1- remove from ProjectSettings the file AndroidResolverDependencies.xml (Only if you are removing the plugins)
2- Import first GPGS plugin
3- Copy the content from AndroidResolverDependencies.xml
4- Import AdMob plugin, unckeck PlayServicesResolver folder from import
5- Edit AndroidResolverDependencies.xml and paste the old content that we copy in step 3
6- Unity will import the correct dependencies.

Doing that I was capable to run my app.

Best,
Felipe.

**Comment by femoreti** [comment]
Hey, I just figure out that you can resolve many conflicts with other plugins (Like Mobile Ads and Firebase) just updating yourself the POM file (Assets/GooglePlayGames/Editor/m2repository/com/google/games/gpgs-plugin-support/0.9.50/gpgs-plugin-support-0.9.50.pom) with this gpgs-plugin-support-0.9.50.pom.zip.

This file updates the gpgs to the version 15+

Hope this helps.

**Comment by femoreti** [comment]
#https://github.com/googlesamples/unity-jar-resolver/issues/157
