### ISSUE TITLE
how to get the player's displaye name whom i have invited using Invitation screen?

### ISSUE THREAD

**Issue by srcsameer** [playgameservices/play-games-plugin-for-unity#2321]
Hi! for QuickMatch i have used List<Participant> playerIDs = PlayGamesPlatform.Instance.RealTime.GetConnectedParticipants (); to get the players detail and stored it to string like oppoUsarname = playerIDs [0].DisplayName.ToString (); after getting connected to the room now i want to get the same but inviting through Invitation screen so how can i get the other player's username to a string even when i am not connected to the room? because i already have that user's details to my play games buddy list?

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
