### ISSUE TITLE
Please update the plugin to support new version of gms！！！please！！！！

### ISSUE THREAD

**Issue by wawo00** [playgameservices/play-games-plugin-for-unity#2324]
As  developers,we noticed that google haven't updte this tool for a long time,and there are many crashes and anr errors in android.We all think that if we use the newer verison of gms that we can avoid thoses bugs and errors.As we know,the newest version of gms is 16, and play-game-plugin-for-unity just support v11 of gms.In a word ,please update this plugin to support newer gms.

**Comment by femoreti** [comment]
Hey, I just figure out that you can resolve many conflicts with other plugins (Like Mobile Ads and Firebase) just updating yourself the POM file `(Assets/GooglePlayGames/Editor/m2repository/com/google/games/gpgs-plugin-support/0.9.50/gpgs-plugin-support-0.9.50.pom)` with this [gpgs-plugin-support-0.9.50.pom.zip](https://github.com/firebase/quickstart-unity/files/2411960/gpgs-plugin-support-0.9.50.pom.zip).

Hope this helps.

**Comment by wawo00** [comment]
thx guys！you help me so much！！

**Comment by olehkuznetsov** [comment]
Updated in 0.9.51

**Comment by prisonbrk** [comment]
(Assets/GooglePlayGames/Editor/m2repository/com/google/games/gpgs-plugin-support/0.9.50/gpgs-plugin-support-0.9.50.pom)

I copied the file but got this error again.


Resolution failed

Failed to fetch the following dependencies:
com.google.android.gms:play-services-ads:15.0.1
com.google.games:gpgs-plugin-support:0.9.53

**Comment by olehkuznetsov** [comment]
Try to import latest plugin as custom asset and run force resolve.

**Comment by prisonbrk** [comment]
AdmobAds version 3.15.1
Playservice 9.57
latest versions, still the same error.

**Comment by olehkuznetsov** [comment]
Can you try to create a new project and just add AdmobAds and PlayGamesServices plugins to check if it is an issue with some existing files/settings of your project, please?

**Comment by prisonbrk** [comment]
Yes, he worked on an empty project. Why is he failing in my project?

**Comment by olehkuznetsov** [comment]
Try to delete all related to plugin files from your project assets and re-import them. Also try to delete Plugins/Android section - it should be filled automatically during resolve phase.

**Comment by prisonbrk** [comment]
I packed my project. I transferred it to the new project. Thank you for your help.
