### ISSUE TITLE
google play services sdk and facebook sdk creating build issues

### ISSUE THREAD

**Issue by 9837081251** [playgameservices/play-games-plugin-for-unity#2325]
i am unable to implement both google play services and facebook sdk in the same project.
both sdks are working fine in separate projects but when i try to combine them in single one i get errors on build. i think the error is with resolver...
Please help me with this

**Comment by olehkuznetsov** [comment]
Can you try the 0.9.51 version, please?

**Comment by Preeth-ic-unity** [comment]
still getting an issue here with the latest v0.11.01 google play services SDK and v14.1.0 face-book SDK. Seems like the same resolver issue ??
(either the build keeps crashing or it builds and the game itself crashes once you try to open it)
is there any solution for this,
thanks and regards.
