### ISSUE TITLE
Assets/Script/GPGS.cs(575,41): error CS1501: No overload for method `DeclineInvitation' takes `2' arguments

### ISSUE THREAD

**Issue by srcsameer** [playgameservices/play-games-plugin-for-unity#2326]
Hi! Working with Realtime multiplayer, when implemented a method to show a popup on receiving an invitation. i did just the same as shown in [the guide](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/RTMP.md)
 `void OnGUI() {
		if (mIncomingInvitation != null) {
			// show the popup
			string who = (mIncomingInvitation.Inviter != null && 
				mIncomingInvitation.Inviter.DisplayName != null) ?
				mIncomingInvitation.Inviter.DisplayName : "Someone";
			GUI.Label(new Rect(240,10,400,70), who + " is challenging you to a race!");
			if (GUI.Button(new Rect(280,40,60,30), "Accept!")) {
				// user wants to accept the invitation!
				PlayGamesPlatform.Instance.RealTime.ShowWaitingRoomUI();
				PlayGamesPlatform.Instance.RealTime.AcceptInvitation(
					mIncomingInvitation.InvitationId, this);
			}
			if (GUI.Button(new Rect(320,40,60,30), "Decline")) {
				// user wants to decline the invitation
				PlayGamesPlatform.Instance.RealTime.DeclineInvitation(
					mIncomingInvitation.InvitationId, this);
			}
		}
	}`

now getting an error :Assets/Script/GPGS.cs(575,41): error CS1501: No overload for method `DeclineInvitation' takes `2' arguments

if i am removing the line
if (GUI.Button(new Rect(320,40,60,30), "Decline")) {
				// user wants to decline the invitation
				PlayGamesPlatform.Instance.RealTime.DeclineInvitation(
					mIncomingInvitation.InvitationId, this);
			}
not getting any error, but that's not correct, i want to know what's wrong here can anyone help me? so that i can keep the decline button without any issue.

Thanks

**Comment by olehkuznetsov** [comment]
I've fixed the guide you mentioned. For DeclineInvitation there should be just one parameter.
In your case it should be like this:
PlayGamesPlatform.Instance.RealTime.DeclineInvitation(mIncomingInvitation.InvitationId);
