### ISSUE TITLE
MiniJSON & InvariantCulture

### ISSUE THREAD

**Issue by TheOddler** [playgameservices/play-games-plugin-for-unity#233]
I'm trying out both Unity ads and the Play Game Services, and when I imported both I got a conflict since both contain MiniJSON. So I [checked the difference](http://www.diffnow.com/?report=osw4e) and the only difference was when using TryParse and ToString on numbers the MiniJSON of Unity Ads used the extra parameter: "System.Globalization.CultureInfo.InvariantCulture" to make sure it works everywhere consistently.

Perhaps something to look at? Which is better, of doesn't it make any difference?

Note: There was one other difference, at the top of the Play Service MiniJSON there was a piece of example code. It was commented so I didn't count it as a real difference.

**Comment by claywilkinson** [comment]
Closing this as obsolete - I don't see MiniJSON in the plug in source code
