### ISSUE TITLE
play-games-plugin-for-unity vs google-play-services.jar

### ISSUE THREAD

**Issue by b3da** [playgameservices/play-games-plugin-for-unity#2330]
Hi, I have a question and don't know where I can ask it, so I posted a new issue.
What is the difference between this plugin and google-play-services.jar?
When should we use google-play-services and when should we use this plugin?

Some plugins like Flurry needs google-play-services.jar. I have google admob plugin in my project. When I install play-games-plugin the project compiles perfectly but when I add Flurry plugin, because it have google-play-services.jar I have conflict error(of course with admob plugin).
So the question is can I use play-games-plugin and remove google-play-services.jar?
thanks.

**Comment by olehkuznetsov** [comment]
Should be fixed in Google-Play-Game-Unity-0.9.51. Can you try it, please?
