### ISSUE TITLE
LeaveRoom() does not work in realtime, room stays connected

### ISSUE THREAD

**Issue by pandadrivers** [playgameservices/play-games-plugin-for-unity#2331]
When I call the code:
PlayGamesPlatform.Instance.RealTime.LeaveRoom();

Nothing happens, the player stays connected with the room and is not able to open a new invitation screen.

I am using Unity 2018.2.13f1

**Comment by olehkuznetsov** [comment]
Can you try the same with SmokeTest sample, please?

**Comment by ozdemir08** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
