### ISSUE TITLE
Forced Resolution Failed for plugin 0.9.50

### ISSUE THREAD

**Issue by JamieHands1989** [playgameservices/play-games-plugin-for-unity#2334]
Hi all,

There appears to be an issue with the Google-Play-Game-Unity-0.9.50 plugin. I have tried this on my project and on a blank project to be sure but no avail on either. 

On the face of it, it appears that it has imported successfully, and the project builds and runs fine, however, if you delve into the logs, there is an entry that says that LibGPG.so could not be found, by researching some more, it appears the resolver is not resolving com.google.games:gpgs-plugin-support:0.9.50.

I've seen that there are quite a few people with this issue, but I'm yet to find one with a solution.

Does anybody have a fix for this please?

Thanks

**Comment by olehkuznetsov** [comment]
Can you try  Google-Play-Game-Unity-0.9.51, please?

**Comment by JamieHands1989** [comment]
Appologies,This is fixed by creating a new project, seemed to work after that.ThanksOn 29 October 2018 at 10:35 olehkuznetsov <notifications@github.com> wrote:  Closed #2334.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.Jamie HandsDeveloperMobile: +447969 202 827Web: http://www.jamiehands.co.uk
