### ISSUE TITLE
0.9.52 error

### ISSUE THREAD

**Issue by nikoskon2003** [playgameservices/play-games-plugin-for-unity#2337]
When i updated to 0.9.52, i got this error when building.
how to fix it?

https://imgur.com/a/Czi1Zh1

**Comment by olehkuznetsov** [comment]
Which version of unity do you have and from which version of plugin have you updated?

**Comment by olehkuznetsov** [comment]
You can also try Force Resolver option in Play Services Resolver menu. And if that doesn't help then you can try to manually remove those files from Assets/Plugins/Android folder.

**Comment by nikoskon2003** [comment]
Ok thanks, ill try it as soon as possible!

**Comment by nikoskon2003** [comment]
ok https://github.com/playgameservices/play-games-plugin-for-unity/issues/2085 this helped me!
