### ISSUE TITLE
Does a fresh connect to GPGS every session

### ISSUE THREAD

**Issue by clipwirecam** [playgameservices/play-games-plugin-for-unity#2338]
Using version 9.5 and at the start of every session the user get the "Connecting to... Google Play Games" popup.
It used to stay connected between sessions and would have the "Welcome GPGS User" drop down from the top. Is this a bug that it needs to reconnect every time. 

I'm attaching the logcat from when GPGS is initializing. 

<details><summary>LOGCAT</summary>
<p>
10-29 17:11:07.793: I/Unity(29443): Building GPG services, implicitly attempts silent auth
10-29 17:11:07.793: I/Unity(29443):  
10-29 17:11:07.793: I/Unity(29443): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
10-29 17:11:07.796: I/GamesNativeSDK(29443): Using existing jar.
10-29 17:11:07.796: I/GamesNativeSDK(29443): Writing 1941 bytes to jar file
10-29 17:11:07.798: W/zygote(29443): Skipping duplicate class check due to unrecognized classloader
10-29 17:11:07.805: I/GamesNativeSDK(29443): Using existing jar.
10-29 17:11:07.805: I/GamesNativeSDK(29443): Writing 1066 bytes to jar file
10-29 17:11:07.807: W/zygote(29443): Skipping duplicate class check due to unrecognized classloader
10-29 17:11:07.817: W/PopupManager(29443): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
10-29 17:11:07.826: I/GamesNativeSDK(29443): Auth operation started: SIGN IN
10-29 17:11:07.826: I/GamesNativeSDK(29443): Connecting to Google Play...
10-29 17:11:07.835: I/Unity(29443): Authentication for AuthenticationDeviceID
10-29 17:11:07.835: I/Unity(29443):  
10-29 17:11:07.835: I/Unity(29443): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
10-29 17:11:07.838: I/Unity(29443): Done authentication step
10-29 17:11:07.838: I/Unity(29443):  
10-29 17:11:07.838: I/Unity(29443): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
10-29 17:11:07.870: W/GamesServiceBroker(4338): Client connected with SDK 12451000, Services 14366021, and Games 70890048
10-29 17:11:07.886: W/Unity(29443): !!! [Play Games Plugin DLL] 10/29/18 17:11:07 -04:00 WARNING: Creating new PlayGamesPlatform
10-29 17:11:07.886: W/Unity(29443):  
10-29 17:11:07.886: W/Unity(29443): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
10-29 17:11:07.893: W/GamesServiceBroker(4338): Client connected with SDK 14536000, Services 14366021, and Games 70890048
10-29 17:11:07.899: W/GamesServiceBroker(4338): Client connected with SDK 14536000, Services 14366021, and Games 70890048

10-29 17:11:07.914: E/rs$DefaultThreadFactory(4338): ===== Detect pool-thread leak =====
10-29 17:11:07.914: E/rs$DefaultThreadFactory(4338): dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-29 17:11:07.914: E/rs$DefaultThreadFactory(4338): java.lang.Thread.getStackTrace(Thread.java:1536)
10-29 17:11:07.914: E/rs$DefaultThreadFactory(4338): java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:568)
10-29 17:11:07.914: E/rs$DefaultThreadFactory(4338): qpt.newThread(Unknown Source:9)
10-29 17:11:07.914: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:631)
10-29 17:11:07.915: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945)
10-29 17:11:07.915: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1388)
10-29 17:11:07.915: E/rs$DefaultThreadFactory(4338): ghu.execute(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):11)
10-29 17:11:07.915: E/rs$DefaultThreadFactory(4338): gah.a(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):2)
10-29 17:11:07.915: E/rs$DefaultThreadFactory(4338): fyz.a(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):24)
10-29 17:11:07.915: E/rs$DefaultThreadFactory(4338): fzf.a(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):72)
10-29 17:11:07.915: E/rs$DefaultThreadFactory(4338): ftm.a(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):10)
10-29 17:11:07.915: E/rs$DefaultThreadFactory(4338): ftq.run(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):8)
10-29 17:11:07.915: E/rs$DefaultThreadFactory(4338): java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
10-29 17:11:07.915: E/rs$DefaultThreadFactory(4338): java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-29 17:11:07.915: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-29 17:11:07.915: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-29 17:11:07.915: E/rs$DefaultThreadFactory(4338): gkh.run(Unknown Source:7)
10-29 17:11:07.915: E/rs$DefaultThreadFactory(4338): java.lang.Thread.run(Thread.java:764)
10-29 17:11:07.919: W/GamesServiceBroker(4338): Client connected with SDK 14536000, Services 14366021, and Games 70890048

10-29 17:11:07.937: E/rs$DefaultThreadFactory(4338): ===== Detect pool-thread leak =====
10-29 17:11:07.937: E/rs$DefaultThreadFactory(4338): dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-29 17:11:07.937: E/rs$DefaultThreadFactory(4338): java.lang.Thread.getStackTrace(Thread.java:1536)
10-29 17:11:07.937: E/rs$DefaultThreadFactory(4338): java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:568)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): qpt.newThread(Unknown Source:9)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:631)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1388)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): ghu.execute(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):11)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): gah.a(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):2)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): fyz.a(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):24)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): fzf.a(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):72)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): ftm.a(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):10)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): ftq.run(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):8)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): gkh.run(Unknown Source:7)
10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): java.lang.Thread.run(Thread.java:764)

10-29 17:11:07.938: E/rs$DefaultThreadFactory(4338): ===== Detect pool-thread leak =====
10-29 17:11:07.939: E/rs$DefaultThreadFactory(4338): dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-29 17:11:07.939: E/rs$DefaultThreadFactory(4338): java.lang.Thread.getStackTrace(Thread.java:1536)
10-29 17:11:07.939: E/rs$DefaultThreadFactory(4338): java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:568)
10-29 17:11:07.939: E/rs$DefaultThreadFactory(4338): qpt.newThread(Unknown Source:9)
10-29 17:11:07.939: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:631)
10-29 17:11:07.939: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945)
10-29 17:11:07.939: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1388)
10-29 17:11:07.939: E/rs$DefaultThreadFactory(4338): qjs.execute(:com.google.android.gms@14366021@14.3.66 (040408-213742215):11)
10-29 17:11:07.939: E/rs$DefaultThreadFactory(4338): pve.a(:com.google.android.gms@14366021@14.3.66 (040408-213742215):2)
10-29 17:11:07.940: E/rs$DefaultThreadFactory(4338): ptn.a(:com.google.android.gms@14366021@14.3.66 (040408-213742215):27)
10-29 17:11:07.940: E/rs$DefaultThreadFactory(4338): pwk.onTransact(:com.google.android.gms@14366021@14.3.66 (040408-213742215):17)
10-29 17:11:07.940: E/rs$DefaultThreadFactory(4338): android.os.Binder.transact(Binder.java:612)
10-29 17:11:07.940: E/rs$DefaultThreadFactory(4338): dly.onTransact(:com.google.android.gms@14366021@14.3.66 (040408-213742215):3)
10-29 17:11:07.940: E/rs$DefaultThreadFactory(4338): android.os.Binder.execTransact(Binder.java:682)
10-29 17:11:07.940: W/GamesServiceBroker(4338): Client connected with SDK 14536000, Services 14366021, and Games 70890048
10-29 17:11:07.954: W/GamesServiceBroker(4338): Client connected with SDK 14536000, Services 14366021, and Games 70890048
10-29 17:11:08.003: I/System.out(2839): (HTTPLog)-Static: isSBSettingEnabled false
10-29 17:11:08.003: I/System.out(2839): (HTTPLog)-Static: isSBSettingEnabled false
10-29 17:11:08.037: W/Conscrypt(2839): Could not set socket write timeout: java.net.SocketException: Socket closed
10-29 17:11:08.037: W/Conscrypt(2839): 	at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@14366021@14.3.66 (040408-213742215):2)
10-29 17:11:08.037: W/Conscrypt(2839): 	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@14366021@14.3.66 (040408-213742215):2)
10-29 17:11:08.115: W/Conscrypt(2839): Could not set socket write timeout: java.net.SocketException: Socket closed
10-29 17:11:08.116: W/Conscrypt(2839): 	at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@14366021@14.3.66 (040408-213742215):2)
10-29 17:11:08.116: W/Conscrypt(2839): 	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@14366021@14.3.66 (040408-213742215):2)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): ===== Detect pool-thread leak =====
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): java.lang.Thread.getStackTrace(Thread.java:1536)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:568)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): qpt.newThread(Unknown Source:9)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:631)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1388)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): qjs.execute(:com.google.android.gms@14366021@14.3.66 (040408-213742215):11)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): xey.run(:com.google.android.gms@14366021@14.3.66 (040408-213742215):33)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): bdrz.run(:com.google.android.gms@14366021@14.3.66 (040408-213742215):2)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): qjt.run(:com.google.android.gms@14366021@14.3.66 (040408-213742215):35)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): qpu.run(Unknown Source:7)
10-29 17:11:08.227: E/rs$DefaultThreadFactory(4338): java.lang.Thread.run(Thread.java:764)
10-29 17:11:08.235: E/rs$DefaultThreadFactory(4338): ===== Detect pool-thread leak =====
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): java.lang.Thread.getStackTrace(Thread.java:1536)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:568)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): qpt.newThread(Unknown Source:9)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:631)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1388)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): ghu.execute(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):11)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): gah.a(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):2)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): fyz.a(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):24)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): fzf.a(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):72)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): ftm.a(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):10)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): ftq.run(:com.google.android.play.games@70890048@5.12.7089 (213806423.213806423-000408):8)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): gkh.run(Unknown Source:7)
10-29 17:11:08.236: E/rs$DefaultThreadFactory(4338): java.lang.Thread.run(Thread.java:764)
10-29 17:11:08.236: W/GamesServiceBroker(4338): Client connected with SDK 14536000, Services 14366021, and Games 70890048
10-29 17:11:08.239: V/GamesNativeSDK(29443): Play Games callback indicates connection failure.
10-29 17:11:08.239: I/GamesNativeSDK(29443): UI interaction required to connect to Google Play.
10-29 17:11:08.240: W/GamesServiceBroker(4338): Client connected with SDK 14536000, Services 14366021, and Games 70890048
10-29 17:11:08.251: I/GamesNativeSDK(29443): Auth operation started: SIGN IN
10-29 17:11:08.251: I/GamesNativeSDK(29443): Connecting to Google Play...
10-29 17:11:08.258: W/GamesServiceBroker(4338): Client connected with SDK 12451000, Services 14366021, and Games 70890048
10-29 17:11:08.273: W/GamesServiceBroker(4338): Client connected with SDK 14536000, Services 14366021, and Games 70890048
10-29 17:11:08.276: W/GamesServiceBroker(4338): Client connected with SDK 14536000, Services 14366021, and Games 70890048
10-29 17:11:08.281: W/GamesServiceBroker(4338): Client connected with SDK 14536000, Services 14366021, and Games 70890048
10-29 17:11:08.299: W/GamesServiceBroker(4338): Client connected with SDK 14536000, Services 14366021, and Games 70890048
10-29 17:11:08.302: W/GamesServiceBroker(4338): Client connected with SDK 14536000, Services 14366021, and Games 70890048
10-29 17:11:08.332: I/System.out(2839): (HTTPLog)-Static: isSBSettingEnabled false
10-29 17:11:08.332: I/System.out(2839): (HTTPLog)-Static: isSBSettingEnabled false
10-29 17:11:08.467: V/GamesNativeSDK(29443): Play Games callback indicates connection failure.
10-29 17:11:08.467: I/GamesNativeSDK(29443): UI interaction required to connect to Google Play.
10-29 17:11:08.467: I/GamesNativeSDK(29443): Resolving connection.
10-29 17:11:08.468: W/GamesServiceBroker(4338): Client connected with SDK 14536000, Services 14366021, and Games 70890048
10-29 17:11:08.469: W/GamesServiceBroker(4338): Client connected with SDK 14536000, Services 14366021, and Games 70890048
10-29 17:11:08.474: I/ActivityManager(1450): START u0 {act=com.google.android.gms.games.SIGN_IN typ=null flg=0x4000000 cmp=ComponentInfo{com.google.android.play.games/com.google.android.gms.games.ui.signin.SignInActivity}} from uid 10019
10-29 17:11:08.481: E/ANDR-PERF-MPCTL(732): Invalid profile no. 0, total profiles 0 only
10-29 17:11:08.482: D/CustomFrequencyManagerService(1450): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1555200  uid : 1000  pid : 1450  pkgName : AMS_APP_SWITCH@CPU_MIN@81
10-29 17:11:08.482: D/ActivityManagerPerformance(1450): AMP_acquire() APP_SWITCH
10-29 17:11:08.482: D/ActivityManagerPerformance(1450): Received MSG_CFMS_HINT_AMS_SWITCH pkgName: com.google.android.play.games

</p>

**Comment by olehkuznetsov** [comment]
>10-29 17:11:08.239: I/GamesNativeSDK(29443): UI interaction required to connect to Google Play.
If you see this each time then it is a bug.

**Comment by clipwirecam** [comment]
Okay any idea how I could go about a fix for this?

**Comment by clipwirecam** [comment]
> > 10-29 17:11:08.239: I/GamesNativeSDK(29443): UI interaction required to connect to Google Play.
> 
> If you see this each time then it is a bug.

I do see this every launch. Do you have any idea what might be causing it / a possible solution?

**Comment by olehkuznetsov** [comment]
Do you ask for ServerAuthToken or TokenId? Can you try to remove 'PlayGamesPlatform.InitializeInstance' if you have it and check if sign-in would be asked again, please?

**Comment by clipwirecam** [comment]
We actually solved this issue thank you. It ended up being a mismatch of the SHA key from the keystore to our GPGS console.

**Comment by olehkuznetsov** [comment]
Actually this is the most common sign-in issues reason.
