### ISSUE TITLE
GetAnotherServerAuthCode Nothing Happens

### ISSUE THREAD

**Issue by Fiercy** [playgameservices/play-games-plugin-for-unity#2339]
I am able to get AuthToken just fine the first time I login. 
The moment I minimize my app I need another token for PlayFab login and the callback from this function just doesn't execute. 

It's not throwing any errors that I can see. 

Any solutions?

**Comment by olehkuznetsov** [comment]
Just checked SmokeTest 'User Info->New Auth Code' and it works fine. Can you check if it works in SmokeTest for you, please?

**Comment by olehkuznetsov** [comment]
Check if you have set 'Google Play Games->Setup->Android Setup->Web App Client ID->Client ID' field.

**Comment by Fiercy** [comment]
So I did lots of tinkering and I've come to the conclusion that in your example if works because its tied to the press of the button. 

But if you do it as a function call (nothing happens) 

When I made this couroutine and inserted a delay in there then it works. Is this something that can be fixed by the devs?

**Comment by olehkuznetsov** [comment]
So, may be your caller/callback is dying before callback is called?

**Comment by olehkuznetsov** [comment]
Should be fixed in v0.9.54
