### ISSUE TITLE
BIILING

### ISSUE THREAD

**Issue by Miscellaneous** [playgameservices/play-games-plugin-for-unity#2340]
How to add Billing to APK?

Documentation says:
Android - In App Purchase - you need to add the BILLING permission to your APK

<uses-permission android:name="com.android.vending.BILLING" />

But in your manifest files you say:

!-- This file is automatically generated by Google Play Games plugin for Unity Do not edit. --

Confusing?!?

**Comment by olehkuznetsov** [comment]
Try the way described in the ['Overriding the Android Manifest'](https://docs.unity3d.com/Manual/android-manifest.html).
