### ISSUE TITLE
How to start game with less number of players than max opponents

### ISSUE THREAD

**Issue by itsdikey** [playgameservices/play-games-plugin-for-unity#2345]
I have a game that uses GPG Realtime multiplayer. The min number of opponents is 1, max number is 7. How to start the game when sufficient amount of players are connected(**less than 7**).
I know that I can send message to all players to start the game, but how I prevent other players from joining this room(being auto matched) as I cannot find any way to tell GPG Realtime that my game is started, and no other player can be matched to this room.

Thanks in advance,
Garegin.

**Comment by olehkuznetsov** [comment]
I can't find such functionality too. Marked as an enhancement.

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
