### ISSUE TITLE
Issue with login when there is no Google account set up

### ISSUE THREAD

**Issue by pedmuitor** [playgameservices/play-games-plugin-for-unity#235]
We found an issue easily reproducible in the Minimal test under Android devices.

If there is no user account set up on the device, after completing the login steps inside the app, the login callback returns false and the flag Social.localUser.authenticated remains false even when if user is successfully logged. If you try to authenticate again it works with a silent login. 

This is the log from the first login try:

I/Unity   (25059): [Play Games Plugin DLL] Activating PlayGamesPlatform.
I/Unity   (25059): [Play Games Plugin DLL] PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
I/Unity   (25059): [Play Games Plugin DLL] Creating platform-specific Play Games client.
I/Unity   (25059): [Play Games Plugin DLL] Making sure PlayGamesHelperObject is ready.
I/Unity   (25059): [Play Games Plugin DLL] Initializing Android Client.
I/Unity   (25059): [Play Games Plugin DLL] Creating GameHelperManager to manage GameHelper.
I/Unity   (25059): [Play Games Plugin DLL] Setting up GameHelperManager.
I/Unity   (25059): [Play Games Plugin DLL] GHM creating GameHelper.
I/Unity   (25059): [Play Games Plugin DLL] GHM calling GameHelper constructor with flags=7
I/Unity   (25059): [Play Games Plugin DLL] GHM setting up GameHelper.
I/Unity   (25059): [Play Games Plugin DLL] GHM Setting GameHelper options.
I/Unity   (25059): [Play Games Plugin DLL] GHM calling GameHelper.setup
I/Unity   (25059): [Play Games Plugin DLL] PlayGamesHelperObject created.
I/Unity   (25059): [Play Games Plugin DLL] AUTH: starting auth process, silent=False
I/Unity   (25059): [Play Games Plugin DLL] GHM: GameHelper setup done.
I/Unity   (25059): [Play Games Plugin DLL] GHM Setting up lifecycle.
I/Unity   (25059): [Play Games Plugin DLL] GHM calling GameHelper.onStart to try initial auth.
I/Unity   (25059): [Play Games Plugin DLL] AUTH: connection in progress; auth now pending.
I/Unity   (25059): [Play Games Plugin DLL] GHM/GameHelperListener got onSignInFailed, origin 1000, notifying GHM.
I/Unity   (25059): [Play Games Plugin DLL] GHM got onSignInFailed, origin 1000, notifying AndroidClient.
I/Unity   (25059): [Play Games Plugin DLL] AndroidClient got OnSignInFailed.
I/Unity   (25059): [Play Games Plugin DLL] AUTH: Auth flow was pending and silent=false, so doing noisy auth.
I/Unity   (25059): [Play Games Plugin DLL] GHM Starting user-initiated sign in.
I/Unity   (25059): [Play Games Plugin DLL] Forcing GameHelper's connect-on-start flag to true.
I/Unity   (25059): [Play Games Plugin DLL] GHM launching sign-in Activity via SignInHelperManager.launchSignIn
I/Unity   (25059): [Play Games Plugin DLL] PlayGamesHelperObject.OnApplicationPause True
I/Unity   (25059): [Play Games Plugin DLL] GHM got OnPause, relaying to GameHelper
I/Unity   (25059): [Play Games Plugin DLL] RtmpClear: clearing RTMP (reason: leaving room because game is stopping.).
I/Unity   (25059): [Play Games Plugin DLL] RtmpClear: no room active.
I/Unity   (25059): [Play Games Plugin DLL] RtmpClear: no need to call OnLeftRoom() callback.
I/Unity   (25059): [Play Games Plugin DLL] RtmpClear: RTMP cleared.
I/Unity   (25059): [Play Games Plugin DLL] PlayGamesHelperObject.OnApplicationFocus False
I/Unity   (25059): [Play Games Plugin DLL] GHM/GameHelperListener got onSignInFailed, origin 1001, notifying GHM.
I/Unity   (25059): [Play Games Plugin DLL] GHM got onSignInFailed, origin 1001, notifying AndroidClient.
I/Unity   (25059): [Play Games Plugin DLL] GHM got onSignInFailed from Sign In Helper. Showing error message.
I/Unity   (25059): [Play Games Plugin DLL] Error message shown.
I/Unity   (25059): [Play Games Plugin DLL] AndroidClient got OnSignInFailed.
I/Unity   (25059): [Play Games Plugin DLL] AUTH: FAILED!
I/Unity   (25059): [Play Games Plugin DLL] AUTH: Calling auth callback: success=False
I/Unity   (25059): [Play Games Plugin DLL] PlayGamesHelperObject.OnApplicationFocus True
I/Unity   (25059): [Play Games Plugin DLL] PlayGamesHelperObject.OnApplicationPause False
I/Unity   (25059): [Play Games Plugin DLL] GHM got OnResume, relaying to GameHelper
I/Unity   (25059): [Play Games Plugin DLL] GHM/GameHelperListener got onSignInSucceeded, origin 1000, notifying GHM.
I/Unity   (25059): [Play Games Plugin DLL] GHM got onSignInSucceeded, origin 1000, notifying AndroidClient.
I/Unity   (25059): [Play Games Plugin DLL] AndroidClient got OnSignInSucceeded.
I/Unity   (25059): [Play Games Plugin DLL] Attempting to retrieve player info.
I/Unity   (25059): [Play Games Plugin DLL] Player ID: *********************
I/Unity   (25059): [Play Games Plugin DLL] Player display name: ****** *******
I/Unity   (25059): [Play Games Plugin DLL] Normal lifecycle OnSignInSucceeded received.
I/Unity   (25059): [Play Games Plugin DLL] No pending actions to run on UI thread.
I/Unity   (25059): [Play Games Plugin DLL] AndroidClient: CheckInvitationFromNotification.
I/Unity   (25059): [Play Games Plugin DLL] AndroidClient: looking for invitation in our GameHelper.
I/Unity   (25059): [Play Games Plugin DLL] GHM clearing invitation and turn-based match on GameHelper.
I/Unity   (25059): [Play Games Plugin DLL] No invitation in our GameHelper. Trying SignInHelperManager.
I/Unity   (25059): [Play Games Plugin DLL] No invitation in SignInHelperManager either.
I/Unity   (25059): [Play Games Plugin DLL] No match in our GameHelper. Trying SignInHelperManager.
I/Unity   (25059): [Play Games Plugin DLL] No match in SignInHelperManager either.
I/Unity   (25059): [Play Games Plugin DLL] AndroidTbmpClient.OnSignInSucceeded
I/Unity   (25059): [Play Games Plugin DLL] Querying for max match data size...
I/Unity   (25059): [Play Games Plugin DLL] Max match data size: 131072

Thanks in advance!

**Comment by claywilkinson** [comment]
@pedmuitor  - Are you still having this issue?  The plugin has be massively updated since you posted this and the call stack is no longer valid.  Please open another issue if you are having problems.  Thanks!

**Comment by ahsanzaman34** [comment]
i have an issue with my plugin when i press login button it loads and then disappear no account option . please help
