### ISSUE TITLE
ver 0.9.53 (unity2018.2.14f1) Didn't find class ....GooglePlayServicesUtilLight, ....Releasable

### ISSUE THREAD

**Issue by ShockWave2048** [playgameservices/play-games-plugin-for-unity#2351]
Hi all!
Can't start Google Play Services from app.
It throw exception - java.lang.ClassNotFoundException

> 11-04 10:14:36.668: I/art(5706): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.GooglePlayServicesUtilLight" on path: DexPathList[[zip file "/data/app/com.gamedev.lsd-1/base.apk"],nativeLibraryDirectories=[/data/app/com.gamedev.lsd-1/lib/arm, /data/app/com.gamedev.lsd-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
> 11-04 10:14:36.669: I/art(5706): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Releasable" on path: DexPathList[[zip file "/data/app/com.gamedev.lsd-1/base.apk"],nativeLibraryDirectories=[/data/app/com.gamedev.lsd-1/lib/arm, /data/app/com.gamedev.lsd-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
> 11-04 10:14:36.671: I/art(5706): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable" on path: DexPathList[[zip file "/data/app/com.gamedev.lsd-1/base.apk"],nativeLibraryDirectories=[/data/app/com.gamedev.lsd-1/lib/arm, /data/app/com.gamedev.lsd-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
> 11-04 10:14:36.671: I/art(5706): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable" on path: DexPathList[[zip file "/data/app/com.gamedev.lsd-1/base.apk"],nativeLibraryDirectories=[/data/app/com.gamedev.lsd-1/lib/arm, /data/app/com.gamedev.lsd-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
> 11-04 10:14:36.672: I/art(5706): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable" on path: DexPathList[[zip file "/data/app/com.gamedev.lsd-1/base.apk"],nativeLibraryDirectories=[/data/app/com.gamedev.lsd-1/lib/arm, /data/app/com.gamedev.lsd-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]

call only -```
 PlayGamesPlatform.DebugLogEnabled = true;
        PlayGamesPlatform.Activate();

```

**Comment by olehkuznetsov** [comment]
Have you tried the 'Force Resolve' option in 'Play Services Resolver' menu?

**Comment by ShockWave2048** [comment]
Yes, before every build.

**Comment by olehkuznetsov** [comment]
Do you have proguard enabled for your build?

**Comment by ShockWave2048** [comment]
I am try proguard in enable/disable state (with key  -keep class com.google.android.gms.** { *; })

**Comment by olehkuznetsov** [comment]
Can you try to create a new project based on the Minimal sample and to check if the error persists, please?

**Comment by ShockWave2048** [comment]
Yes, i can try with 20 hours. Sorry.

**Comment by migellal** [comment]
Is there any news?

**Comment by ShockWave2048** [comment]
No, shifted to next time.

**Comment by migellal** [comment]
> 	implementation "com.google.android.gms:play-services-base:x.y.z"
> 	implementation "com.google.android.gms:play-services-basement:x.y.z"
> 	implementation "com.google.android.gms:play-services-tasks:x.y.z"

This should help.

**Comment by ShockWave2048** [comment]
Big thanks!

**Comment by ShockWave2048** [comment]
migellal - where it placed? (command @implementation@)

**Comment by migellal** [comment]
In 'mainTemplate.gradle' file in dependencies
