### ISSUE TITLE
Systematic GamesNativeSDK: Error connecting to Google Play: code 8.

### ISSUE THREAD

**Issue by pierreserin** [playgameservices/play-games-plugin-for-unity#2355]
Unity Version : 2018.2.15f1
Using SRP Lightweight pipeline 3.0.0
Version of the package : 0.9.53
Build Method, runtime, API : Graddle / IL2CPP - .Net 4.x Equivalent - .NET 4.x equivalent
Target : ARMv7, ARM64, x86
Tested on : Nexus 5x on Android 8.1.0 (OPM7.181005.003)
 
- Added the package to my project
- Created the Project in Game services
- Created Leaderboards and achievements
- Created linked application for Dev, Upload and Application certificate (using Google App Signing) with the 3 SHA1 fingerprints (double checked)
- Copied the ressources from my Game services to the Setup
- Resolved all the .aar files needed (I guess)
- Build (Dev or Production)
 
No matter what I do (Developpement build, Production Build, even through Google Play Internal tests) I always get an ERROR_NOT_AUTHORIZED width a error code 8. I can even ask for a token and it will work, I also happen to see the "Welcome" pop-in in my game on first login.
 
What I've tried : 
- build in arm64 or armv7 same error
- using .NET4 or .NET3.5 Equivalent
- using Mono or IL2CPP
- Switched from Graddle to Internal for testing
- Uninstalled / Reinstalled the Google Play Games Package
- Changing the SHA1 fingerprints on the API console
- Checked the application ID in the manitest
- Unzipped my apk to check the SHA1 fingerprints (upload key is OK)

 I don't know what else to do really ...
 
Logs : 

> 11-13 17:24:59.598 2460-2624/com.gmfp.cthulhuhalloween I/GamesNativeSDK: Auth operation started: SIGN IN
>     Connecting to Google Play...
> 11-13 17:24:59.987 2460-2486/com.gmfp.cthulhuhalloween W/Unity: !!! [Play Games Plugin DLL] 11/13/18 17:24:59 +01:00 WARNING: Creating new PlayGamesPlatform
>     UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
>     UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
>     UnityEngine.Logger:Log(LogType, Object)
>     UnityEngine.Debug:LogWarning(Object)
>     GooglePlayGames.OurUtils.<w>c__AnonStorey1:<>m__0() (at E:\UnityProject\CthulhuHaloweenParty\Assets\GooglePlayGames\OurUtils\Logger.cs:68)
>     GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at E:\UnityProject\CthulhuHaloweenParty\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
>      
>     (Filename: E Line: 0)
> 11-13 17:24:59.988 2460-2486/com.gmfp.cthulhuhalloween I/Unity:  [Play Games Plugin DLL] 11/13/18 17:24:59 +01:00 DEBUG: Activating PlayGamesPlatform.
>      [Play Games Plugin DLL] 11/13/18 17:24:59 +01:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
> 11-13 17:24:59.989 2460-2486/com.gmfp.cthulhuhalloween I/Unity:  [Play Games Plugin DLL] 11/13/18 17:24:59 +01:00 DEBUG: Creating platform-specific Play Games client.
>      [Play Games Plugin DLL] 11/13/18 17:24:59 +01:00 DEBUG: Creating Android IPlayGamesClient Client
> 11-13 17:25:01.518 2460-2460/com.gmfp.cthulhuhalloween V/GamesNativeSDK: Play Games callback indicates connection failure.
> 11-13 17:25:01.518 2460-2624/com.gmfp.cthulhuhalloween I/GamesNativeSDK: Error connecting to Google Play: code 8.
> 11-13 17:25:01.551 2460-2624/com.gmfp.cthulhuhalloween I/GamesNativeSDK: Auth operation started: SIGN IN
>     Connecting to Google Play...
> 11-13 17:25:01.582 2460-2486/com.gmfp.cthulhuhalloween I/Unity:  [Play Games Plugin DLL] 11/13/18 17:25:01 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
>      [Play Games Plugin DLL] 11/13/18 17:25:01 +01:00 DEBUG: Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
>      [Play Games Plugin DLL] 11/13/18 17:25:01 +01:00 DEBUG: there are pending auth callbacks - starting AuthUI
> 11-13 17:25:01.816 2460-2460/com.gmfp.cthulhuhalloween V/GamesNativeSDK: Play Games callback indicates connection failure.
> 11-13 17:25:01.816 2460-2624/com.gmfp.cthulhuhalloween I/GamesNativeSDK: Error connecting to Google Play: code 8.
> 11-13 17:25:01.847 2460-2486/com.gmfp.cthulhuhalloween I/Unity:  [Play Games Plugin DLL] 11/13/18 17:25:01 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
> 11-13 17:25:01.848 2460-2486/com.gmfp.cthulhuhalloween I/Unity:  [Play Games Plugin DLL] 11/13/18 17:25:01 +01:00 DEBUG: AuthState == Unauthenticated calling auth callbacks with failure
> 11-13 17:25:01.852 2460-2486/com.gmfp.cthulhuhalloween I/Unity: Authentication status : False

**Comment by olehkuznetsov** [comment]
Have you added the account you are using to the testers list? Or have you published your Play Games console changes?

**Comment by pierreserin** [comment]
I've added all my gmail accounts tonthe tester list, and I've tried publishing. Neither works.

**Comment by olehkuznetsov** [comment]
Can you provide your app_id, please?

**Comment by pierreserin** [comment]
app_id : 168791220569

**Comment by olehkuznetsov** [comment]
Have you set web client_id field in Play Games setup dialog or is it empty?
Can you show your code for 'PlayGamesClientConfiguration ClientConfiguration' builder?

**Comment by pierreserin** [comment]
I've tried both filed and empty for good mesure and none works.

For the PlayGamesClientconfiguration builder here is the code :

```
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
// enables saving game progress.
.EnableSavedGames()
// registers a callback to handle game invitations received while the game is not running.
//.WithInvitationDelegate(< callback method >)
// registers a callback for turn based match notifications received while the
// game is not running.
//.WithMatchDelegate(< callback method >)
// requests the email address of the player be available.
// Will bring up a prompt for consent.
//.RequestEmail()
// requests a server auth code be generated so it can be passed to an
//  associated back end server application and exchanged for an OAuth token.
//.RequestServerAuthCode(false)
// requests an ID token be generated.  This OAuth token can be used to
//  identify the player to other services such as Firebase.
//.RequestIdToken()
.Build();

 PlayGamesPlatform.InitializeInstance(config);
 // recommended for debugging:
 PlayGamesPlatform.DebugLogEnabled = true;
 // Activate the Google Play Games platform
 PlayGamesPlatform.Activate();
```

I took the code from this github's guide, but just commented out what I don't use (Multiplayer, Auth codes and Tokens). For now I just need Achievements, Leaderboards and Cloud saves.

**Comment by pierreserin** [comment]
I feel so stupid it was deactivated !!!!!!!

 Thanks a lot for the help, and sorry I made you waste your time :/ ...

**Comment by pierreserin** [comment]
If I may, If it is possible it should maybe output a more explicit error or at least a warning. Thanks again and have a nice day !
