### ISSUE TITLE
Achievements Google Play Services not working

### ISSUE THREAD

**Issue by villa16x** [playgameservices/play-games-plugin-for-unity#2358]
Hello all,

I'm trying to implement Google Achievements into my Android game, but I'm unable to make it works. When I press the "Show Achievement" button it doesn't show anything. No login window, no achievements, no nothing. Just I press and nothing happens.

I'm going to start for the very first. I have a menu with two buttons: "login" and "show achievements".

This two buttons call the methods "LogIn()" and "ShowAchievements()" of this script:

*Using last version of Unity 2018.2.5f1

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;

public class AchievementManager : MonoBehaviour {

    public static AchievementManager instance;

	// Use this for initialization
	void Awake () {
		if (instance == null)
        {
            instance = this;
        }
	}

    void Start()
    {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();

        PlayGamesPlatform.InitializeInstance(config);
        // recommended for debugging:
        PlayGamesPlatform.DebugLogEnabled = true;
        // Activate the Google Play Games platform
        PlayGamesPlatform.Activate();
    }

    public void Login()
    {
        Social.localUser.Authenticate((bool success) => {});
    }

    public void ShowAchievements()
    {
        Social.ShowAchievementsUI();
    }
}
```

I would need to know if the scripts are ok or I'm missing something.

Ok, let's think that this script is correct. Let's go to my Developer Account:
- I've done 5 achievements (with icons too).
- In linked apps and the google API, I've placed my SHA1 from my unity keystore (that thing of command promt > keytool, etc.). So, my linked app has the correct SHA1.
- I have filled all the information.
- I have my game in Alpha Test (and yes, with the correct e-mail for the user).
- Also, I have in testing allowed the "Testers".
- I have published my game services correctly.
- I have restarted the process a lot of times. I have payed a plugin from asset store which says "Easy Achievements" (which clearly isn't for me).
- I tested with "official" "test scenes".
- I have not activated the anti-cheats options from linked apps.
- In Window > Google Play > Android Settings, I've correctly added all the information and the "Get resources" from achievements.

Here I let you some screens of my google developer, so if you can see some error or something, I've becoming crazy with this:
https://gyazo.com/fa71b079db08d813d18c13947223d4f6 
https://gyazo.com/746732513b4ca0f6c30a6a29767f120f
https://gyazo.com/ca332f00770824ba7d6c3f7c76f8c045
https://gyazo.com/bba0a7850582be7247b5de08bf7d515a
https://gyazo.com/3f6a43e67475816060891ba802d90415
https://gyazo.com/d22af172133a8005c1fd7fd459e5b0ec
https://gyazo.com/41ce9cb5230ce4f8d89cdb822ab5e9ef

Thank you, and I hope someone can help me with this T_T

**Comment by olehkuznetsov** [comment]
>I've placed my SHA1 from my unity keystore (that thing of command promt > keytool, etc.). So, my linked app has the correct SHA1.

I'm not sure your app in alpha test still uses the unity SHA1 key. 
Can you, please, download your installed apk from the phone and check it SHA1 key?
Check 'Check the certificate fingerprint' on the [troubleshooting](http://developers.google.com/games/services/android/troubleshooting)  page

**Comment by olehkuznetsov** [comment]
[How to download apk from an Android device](https://stackoverflow.com/questions/4032960/how-do-i-get-an-apk-file-from-an-android-device)

**Comment by Dunman44** [comment]
Same problem. Also get this errors in my Logcat. Tried re-importing plugin and all the other solutions out there.
![unknown](https://user-images.githubusercontent.com/23479174/48658789-5dfdd680-ea50-11e8-9630-890d70c0a306.png)

**Comment by olehkuznetsov** [comment]
"Unable to find gpg" seems as a critical one.
Can you check in your built apk do you have libgpg.so in all lib/cpu folders, please?

**Comment by olehkuznetsov** [comment]
Thanks for sharing it
