### ISSUE TITLE
Google Play Games crash  going back from profile to game

### ISSUE THREAD

**Issue by chekaaa** [playgameservices/play-games-plugin-for-unity#2360]
When I display the leaderboard in-game > tap a player name > open profile > tap the back button to the game,  Google Play Games crashes 

`11-15 00:58:40.809: E/AndroidRuntime(6326): Process: com.google.android.play.games.ui, PID: 6326
11-15 00:58:40.809: E/AndroidRuntime(6326): java.lang.RuntimeException: Unable to stop activity {com.google.android.play.games/com.google.android.gms.games.ui.clientv2.leaderboards.LeaderboardsActivity}: java.lang.NullPointerException: Attempt to read from field 'gdx kaz.a' on a null object reference
`
Edit: I noticed It only happens when the Profile UI is on portrait but works well when It's on landscape (My game is locked on landscape)

**Comment by chekaaa** [comment]
I noticed It only happens when the Profile UI is on portrait but works well when It's on landscape (My game is locked on landscape)

**Comment by olehkuznetsov** [comment]
Thank you,
This one should be fixed in next Play Games release.
