### ISSUE TITLE
Save Games crash when Resolving conflict

### ISSUE THREAD

**Issue by irina88** [playgameservices/play-games-plugin-for-unity#2365]
I am getting a crash every time I call the ChooseMetadata function from the IConflictResolver interface that comes as a parameter for the manual conflict resolution delegate.
Here is the log:

"_at libgpg.00156c5e(Native Method)
at libgpg.gpg::SnapshotManager::ResolveConflict(gpg::SnapshotMetadata const&, gpg::SnapshotMetadataChange const&, std::string const&, std::function<void (gpg::SnapshotManager::CommitResponse const&)>)(SnapshotManager:92)
at libgpg.SnapshotManager_ResolveConflict(SnapshotManager_ResolveConflict:128)
at Unknown.00007eb0(Unknown Source:0)
at SnapshotManager.SnapshotManager_ResolveConflict(Native Method)
at SnapshotManager.Resolve(<0x001e8>:488)
at NativeConflictResolver.ChooseMetadata(<0x0012f>:303)
at AndroidCloudSaveService.ConflictResolver(<0x00097>:151)
at <ToOnGameThread>c__AnonStorey2.<>m__0(<0x0005b>:91)
at PlayGamesHelperObject.Update(<0x000ef>:239)
at Object.runtime_invoke_void__this__(Native Method)
at libmono.000222bb(Native Method)
at libmono.mono_runtime_invoke(mono_runtime_invoke:136)
at libunity.00527774(Native Method)
at libunity.0050acf4(Native Method)
at libunity.00203120(Native Method)
at libunity.0034db34(Native Method)
at libunity.0063545c(Native Method)
at libunity.0063796c(Native Method)
at base.0006d0e3(Native Method)_
"

**Comment by olehkuznetsov** [comment]
Does it happen in v0.9.53 plugin?

**Comment by irina88** [comment]
> Does it happen in v0.9.53 plugin?

Yes.

**Comment by olehkuznetsov** [comment]
Can you check it, please, with automatic conflict resolution mode? It still uses 'manual' resolution inside, so, it should show if it general issue or could be related to your code.

**Comment by irina88** [comment]
> Can you check it, please, with automatic conflict resolution mode? It still uses 'manual' resolution inside, so, it should show if it general issue or could be related to your code.

The game doesn't crash when using : " savedGameClient.OpenWithAutomaticConflictResolution(saveName, DataSource.ReadCacheOrNetwork, ConflictResolutionStrategy.UseOriginal, OnSavedGameOpened);" instead of : "OpenWithManualConflictResolution(saveName, DataSource.ReadCacheOrNetwork, true, ConflictResolver, OnSavedGameOpened);".  But when using it like this: "OpenWithAutomaticConflictResolution(saveName, DataSource.ReadCacheOrNetwork, ConflictResolutionStrategy.UseManual, OnSavedGameOpened);"  it yields this error " *** [Play Games Plugin DLL] 11/23/18 14:11:12 +02:00 ERROR: Unhandled strategy UseManual" .

**Comment by olehkuznetsov** [comment]
This is the  implementation for 'OpenWithAutomaticConflictResolution'
As you can see it uses inside resolver.ChooseMetadata too.
Can you check if it crashes with 'ConflictResolutionStrategy.UseUnmerged', please? 
If it doens't work it means we have an bug in the plugin.
And if it works it, probably, means there is something in your code and we can try to figure out the issue if you post the code which calls resolver.ChooseMetadata.
```
        public void OpenWithAutomaticConflictResolution(string filename, DataSource source,
            ConflictResolutionStrategy resolutionStrategy,
            bool prefetchDataOnConflict, ConflictCallback conflictCallback,
            Action<SavedGameRequestStatus, ISavedGameMetadata> completedCallback)
        {
            Misc.CheckNotNull(filename);
            Misc.CheckNotNull(completedCallback);
            completedCallback = ToOnGameThread(completedCallback);

            if (conflictCallback == null) {
                conflictCallback =
                    (resolver, original, originalData, unmerged, unmergedData) => {
                    switch (resolutionStrategy) {
                    case ConflictResolutionStrategy.UseOriginal:
                        resolver.ChooseMetadata (original);
                        return;
                    case ConflictResolutionStrategy.UseUnmerged:
                        resolver.ChooseMetadata (unmerged);
                        return;
                    case ConflictResolutionStrategy.UseLongestPlaytime:
                        if (original.TotalTimePlayed >= unmerged.TotalTimePlayed) {
                            resolver.ChooseMetadata (original);
                        } else {
                            resolver.ChooseMetadata (unmerged);
                        }
                        return;
                    default:
                        Logger.e ("Unhandled strategy " + resolutionStrategy);
                        completedCallback (SavedGameRequestStatus.InternalError, null);
                        return;
                    }
                };
            }

             conflictCallback = ToOnGameThread(conflictCallback);

            if (!IsValidFilename(filename))
            {
                Logger.e("Received invalid filename: " + filename);
                completedCallback(SavedGameRequestStatus.BadInputError, null);
                return;
            }

            InternalOpen(filename, source, resolutionStrategy, prefetchDataOnConflict, conflictCallback,
                completedCallback);
        }

```

**Comment by irina88** [comment]
> ConflictResolutionStrategy.UseUnmerged

Unfortunately I am not able to reproduce the crash anymore, even with the original code "OpenWithManualConflictResolution(saveName, DataSource.ReadCacheOrNetwork, true, ConflictResolver, OnSavedGameOpened);".

I will keep trying to reproduce it and let you know if the ConflictResolutionStrategy.UseUnmerged fixes the problem.

**Comment by olehkuznetsov** [comment]
To generate a conflict you need:
1. Login on two devices with the same user 
2. Open the same save game
3. Save game on one device
4. Save game on another device
6. Open same save game on both devices.

**Comment by olehkuznetsov** [comment]
If you don't plan to merge save games you can just use 'ConflictResolutionStrategy.UseLongestPlaytime' strategy.

**Comment by olehkuznetsov** [comment]
Can't reproduce
