### ISSUE TITLE
Cant log in

### ISSUE THREAD

**Issue by nikoskon2003** [playgameservices/play-games-plugin-for-unity#2373]
Cant log in in unity 2018.2

**Comment by olehkuznetsov** [comment]
Check the troubleshooting section, please.
https://developers.google.com/games/services/android/troubleshooting

Also check if you request serverSuthCode or tokenId - in this case make sure you provide **web** client id and not **android** client id.

**Comment by nikoskon2003** [comment]
Everything is well configured and i even updated to v0.9.55 and unity 2018.2.18

**Comment by nikoskon2003** [comment]
I made a new app on google play, new api tokens, new app id, new everything, but still, the login popup does not appear!!! Why???

**Comment by olehkuznetsov** [comment]
Can you try the Minimal sample, please?

**Comment by nikoskon2003** [comment]
You mean import the plugin and have basic stuff?? Like a button saying sign in and a small script??

**Comment by olehkuznetsov** [comment]
I mean the one from this folder:
https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/samples

Just follow the steps from  the readme.txt file.

**Comment by nikoskon2003** [comment]
Ok ill test it as soon as i can!

**Comment by tqtran7** [comment]
I am seeing a similar issue. Currently using unity 2018.3 and deploying the Minimal project to a samsung device. I followed the set up instructions in the readme and was able to deploy it successfully to the device. I even see the game center window pop up. However, I still get authentication failure.

I then modified the MainGui script so that i can see the status by adding the status parameter and printing it when failing:
`                Social.localUser.Authenticate((bool success, string status) =>
                {
                    mWaitingForAuth = false;
                    if (success)
                    {
                        mStatusText = "Welcome " + Social.localUser.userName;
                    }
                    else {
                        Debug.Log(status);
                        mStatusText = "Authentication failed.";
                    }
                });`

This is what I see in the console.
`AndroidPlayer(samsung_SM-G950U1@192.168.86.193) Authentication canceled`

So I head over to the troubleshooting page, and noticed that
`<meta-data android:name="com.google.android.gms.games.APP_ID"
    android:value="@string/app_id" />` is missing. It seems like Unity builds the manifest each time I deploy. Is this even a valid check for Unity builds?
 
Anyway, I spend an entire day trying to figure it out, and its gotten frustrating enough for me to scan the bug list and post something. Hopefully someone can help!

**Comment by tqtran7** [comment]
Upon closer inspection, I am noticing that the SHA1 is different. The one is packed in the APK is different than the one in the keystore. The one in the keystore is the same as the one in the Developer Console. So for whatever reason, it looks like Unity is building its own thing and not taking it from the key specified in the player settings. Compound this with the missing tag in the manifest, this could be the reason why? Any pointer would be appreciated. Thanks

**Comment by tqtran7** [comment]
OK, more updates. If you enable developer build, apparently, unity will use "Android debug" and this causes the SHA1 to be different. However, the build still fails with the same error message "Authentication canceled".

**Comment by nikoskon2003** [comment]
I never used Developer Build, and my keys were always the same!

**Comment by tqtran7** [comment]
I just created a brand new project and redid all of the steps, same issue. Also tried different Build system (such as Internal vs Gradle), and nothing seems to work. Would be great if someone else can also verify this so it is not something that we are doing wrong.

**Comment by nikoskon2003** [comment]
I have my game in beta, but it still doesn't work!!! Before an update, in June, it worked fine in beta!

**Comment by olehkuznetsov** [comment]
Also check if the account you are using is added in Testers section

**Comment by nikoskon2003** [comment]
Yep, alpha and beta users are allowed

**Comment by nikoskon2003** [comment]
Everything is 100% configured, but no sign in action! If you would like me to send you data, please tell me and ill send screenshots as soon as i can!!!

**Comment by olehkuznetsov** [comment]
Sure, let's check it.

**Comment by nikoskon2003** [comment]
![image](https://user-images.githubusercontent.com/29357627/49964413-18cfa600-ff23-11e8-8995-a47300cb2490.png)
this is correct, right?

**Comment by nikoskon2003** [comment]
![image](https://user-images.githubusercontent.com/29357627/49964522-621ff580-ff23-11e8-9c30-db2b15da2954.png)
and this

**Comment by nikoskon2003** [comment]
FINALLY I GOT IT TO WORK!!! For anyone that has the same problem, i uninstalled and reinstalled unity, i updated the android sdk and i reimported the plugin. One of this things got it to work (or all of them together). [So it was 'configuration' error after all]
