### ISSUE TITLE
Crash when saving database file

### ISSUE THREAD

**Issue by jquentin** [playgameservices/play-games-plugin-for-unity#2375]
My local game progress is saved in a .db file, so I am trying to save this file to Cloud Save, using File.ReadAllBytes, but the app is crashing at:

` [Play Games Plugin DLL] 11/26/18 16:57:20 +01:00 DEBUG: Entering internal callback for SnapshotManager#OpenCallback`

It's a ~3MB file, maybe that is the problem, but I couldn't find any statement about a size limit for the data to save, so that's not clear. I tested saving a tiny jpeg instead, and it didn't crash.
Is there a size limit? File formats that are not accepted?

**Comment by olehkuznetsov** [comment]
File format isn't matter, but the size is.
Max save size is 3 * 1024 * 1024 bytes and max save cover image size is 800 * 1024 bytes.

**Comment by jquentin** [comment]
Thanks @olehkuznetsov !
I think I'm like a few kb over... Can you compress a db file??
Is there any documentation about this file size limit?

**Comment by olehkuznetsov** [comment]
Db should compress very good.
[Here](https://developers.google.com/games/services/common/concepts/savedgames) is a section named Limits.

**Comment by jquentin** [comment]
Thank you!
