### ISSUE TITLE
The type or namespace name `Native' does not exist in the namespace `GooglePlayGames'. 

### ISSUE THREAD

**Issue by siddharth3322** [playgameservices/play-games-plugin-for-unity#2376]
Up to now, I have built Unity game project for the Android platform and it worked properly. Now I have switched towards iOS platform but on the spot, I got this error in console.

![gpg_error](https://user-images.githubusercontent.com/3082151/49214104-e59dfa80-f3eb-11e8-8bdd-e521dceda76e.png)

Now, what should I require to do to solve this error?
If again I switch my game project platform to Android then it does not appear.

**Comment by olehkuznetsov** [comment]
Should be already fixed. Update plugin to v0.9.55, please.
