### ISSUE TITLE
ReportScore Success but no score visible in Leaderboard

### ISSUE THREAD

**Issue by CloudDeLuna** [playgameservices/play-games-plugin-for-unity#2377]
I use the following code to report a player score to a leaderboard

`   public void ReportPlayerScore(int playerScore)`
   ` {`
`        PlayGamesPlatform.Instance.ReportScore(playerScore, GPGSIds.leaderboard_battle_top, GPGSIds.leaderboard_battle_top, OnReportScoreDone);`
 `   }`

`public void OnReportScoreDone(bool success)`
   ` {`
`        Debug.Log("OnReportScoreDone success : " + success);`
   ` }`

My user is authenticated and logged in, the report seems successfull (has I got the Log "OnReportScoreDone success true") and I can see the leaderboard I created properly. 
I even can use the SavedGames service! BUT the leaderboard is always showing the "No score" message and remains empty!

I have no errors in logcat, and my player has his GooglePlay Profile set to public. 
Edit:
I use the latest version of the plugin (0.9.55), and my game is not in production but in Alpha
Does anyone have a clue of what is happenning here ?

**Comment by CloudDeLuna** [comment]
Yes I did :/ 
I created 3 different Leaderboards to test too

**Comment by olehkuznetsov** [comment]
Can you give me your app_id, please, I will check if there is something I can see.

**Comment by nikoskon2003** [comment]
You are lucky that you can even log in, for me thats a no :(

**Comment by CloudDeLuna** [comment]
I manually added the second one in Google Cloud Plateform.

I just linked it to the application with the same package name, maybe the modification take some time to propagate, but for now I still got the same behaviour.

But if this was the source of the problem would'nt it affect also the signing and save part ?

**Comment by olehkuznetsov** [comment]
For sign-in it is enough to have project in Google Cloud Platform, but for PGS api you need to link it in Play Console. If you link it in Play console - it creates Google Cloud Platform entry automatically.

**Comment by CloudDeLuna** [comment]
Good to know!

Still no change in the behaviour, I tried clearing my app datas and Google Play Games datas too

**Comment by olehkuznetsov** [comment]
Have you resubmit scores after fix?

**Comment by CloudDeLuna** [comment]
Yes I did, I tried multiple times to report score after updating

**Comment by olehkuznetsov** [comment]
Have you tried to sign-out/sign-in before sending the scores?

**Comment by CloudDeLuna** [comment]
Yes I did too! But now it has begin to work! Maybe it was the time for it to propagate the changes I made earlier?

**Comment by olehkuznetsov** [comment]
You've also 'published' linked app changes, may be this is related too.

**Comment by CloudDeLuna** [comment]
Maybe, anyway thank you olehkuznetsov !
