### ISSUE TITLE
Issues with Leaderboards after Posting Score

### ISSUE THREAD

**Issue by JamieHands1989** [playgameservices/play-games-plugin-for-unity#2380]
Hi All,

Hoping to get some assistance. I have a rather strange error occurring. Sign in works correctly, I can view the leaderboards as long as I have not posted and I get the 'Looks like your the first person' message, and I can see all of the achievements list and they get unlocked correctly.

So far so good.

After posting a score however, the leaderboards starts showing 'An error has occurred with Google Play Games Services', everything else continues to work as expected.

There is no details in the logs as to any indication of an error, and although the API console shows errors as recorded, I cannot see any logs to say what is going on. I do a check to make sure the user is authenticated before logging on, as the user may not want to be signed into Google Play Games. 

Any ideas?

Thanks

**Comment by nikoskon2003** [comment]
What version of unity are you using. Because i cannot even log in!!!

**Comment by JamieHands1989** [comment]
Hi nikoskon2003,

I'm using the lastest version with a Plus subscription of Unity 2018.2.18f1.
What errors do you get?

**Comment by nikoskon2003** [comment]
The funny thing is that im getting no errors. The game builds correctly, and i have configured everything correctly, from the unity config to tge api keys, but i dont get any popup in my game about the login!
Im also using 2018.2.18f1 with v0.9.55 of the google play services aaaet.

**Comment by JamieHands1989** [comment]
I am currently thinking of omitting it out for the moment and adding it in via an update later on.

I had issues with an older plugin a few versions ago but the plugin update fixed it

**Comment by nikoskon2003** [comment]
That may work. Also, how did you update the plugin? I deleted all the plugin's files and i reimported it.

**Comment by JamieHands1989** [comment]
Pretty much the same thing, deleted the Google Play Games folder and reimported the new plugin.

**Comment by nikoskon2003** [comment]
*and reconfigured the android settings.
Well, i think this plugin just hates me

**Comment by JamieHands1989** [comment]
Just looking through the logs and it appears it wont publish the score to the scoreboard because of background tasks not being allowed in Android 9

**Comment by JamieHands1989** [comment]
After unlinking and relinking the app happy to say things are now working.

**Comment by nikoskon2003** [comment]
What did you do?

**Comment by JamieHands1989** [comment]
If you go to Google Play Games Services on the Google Play Developer Console and under linked apps, delete the links and re-add the link. It reconfigures the app I'd to make sure they all match.

**Comment by olehkuznetsov** [comment]
Thanks for update.
