### ISSUE TITLE
Game crash when using LoadScores()? 

### ISSUE THREAD

**Issue by mntcarp** [playgameservices/play-games-plugin-for-unity#2383]
Hey guys!
I'm having an issue trying to get some data from the leaderboards to display on a UI text in my scene (I really don't know if I'm doing it correctly either).
What I want is to show on some UI Texts the top 1 score and user name from the global leadeboards, so somewhere in my game this function is called:

```
public void RetrieveLeaderboardsData()
{
	int topScore = 0;
	string playerName = string.Empty;
	string[] playerId = new string[1];
	
	PlayGamesPlatform.Instance.LoadScores(
		GPGSIds.leaderboard_top_scores, 
		LeaderboardStart.TopScores, 
		1, 
		LeaderboardCollection.Public, 
		LeaderboardTimeSpan.AllTime,
		(data) =>
		{
			if (data.Valid)
			{
				if (data.Scores[0].value > 0)
				{
					topScore = (int)data.Scores[0].value;
					playerId[0] = data.Scores[0].userID;
				}
				else
					Debug.Log("Player score <= 0");
			}
			else
				Debug.Log("Not valid Data");
		});

	Social.LoadUsers(
		playerId, 
		(user) =>
		{
			if (user != null)
				playerName = user[0].userName;
			else
				Debug.Log("No user");
		});
	OnHardScoreFound(playerName, topScore);
}
```
`OnHardScoreFound(playerName, topScore);`
Is listened by the UI Text scripts to update themselves and show name and score. 
When `RetrieveLeaderboardsData()` is called, the game immediately closes and the logcat doesn't even show those Debug.Log messages. What I'm doing wrong? Thanks!

**Comment by mntcarp** [comment]
**Update**: I've commented the `Social.LoadUsers()` function and add a Debug.Log on LoadScores, the data is retrieved and is shown in the logcat (and the game doesn't crash), but the `OnHardScoreFound()` is not called.

**Comment by olehkuznetsov** [comment]
Callback is called asynchronously after result is ready.
And this line:
playerName = user[0].userName;
is executed after this line:
OnHardScoreFound(playerName, topScore);

As a simple fix just move it inside LoadUsers collback, like:
if (user != null)
{
      playerName = user[0].userName;
      Debug.Log("Name: " + playerName);
      OnHardScoreFound(playerName, topScore);
      OnScoresFound();
}
