### ISSUE TITLE
Signin and leaderboard not working anymore

### ISSUE THREAD

**Issue by Bertjuhh** [playgameservices/play-games-plugin-for-unity#2385]
A few weeks ago, I published my app, where users can sign in and post their highscores to a leaderboard.
So far, there are 12 entries by different people.
But, some people could not signin at all, mostly new Android version users.
And since this morning, I cannot sign in myself suddenly.
I didn't update the app since a week, how come this suddenly happened?

Do I have to change Unity/this package to the latest version?
Did Google update something?

I'm totally lost here :(

Anyone has an idea?

**Comment by olehkuznetsov** [comment]
Have you linked your release package/sha1 key combination in Play console?

**Comment by Bertjuhh** [comment]
I have an app SHA-1 and a upload SHA-1.
In Cloud Platform i have an API key and OAuth 2.0.
The API key has the app-SHA! and the OAuth 2.0 has the upload SHA-1.

**Comment by olehkuznetsov** [comment]
what is your app_id?

**Comment by Bertjuhh** [comment]
package name you mean? its com.bertjuhh.flyingdutchman

**Comment by olehkuznetsov** [comment]
Can sign-in to it without any issues. And leaderboard works too for me.
Can you check if you can sign-in to Play Games app, please?
Can you provide logcat for the app during your sign-in attempt, please?

**Comment by Bertjuhh** [comment]
Thanks for testing.
I've switched the oauth and api sha-1 codes and now it works. Still strange it worked before.
Has it to do with going from open beta to release?
