### ISSUE TITLE
Since the new GPGs UI kicked in, saved games UI selector won't load and will instead crash

### ISSUE THREAD

**Issue by blitzcloud** [playgameservices/play-games-plugin-for-unity#2386]
I updated to the latest version of the GPGS unity plugin, but that doesn't fix it either.

It simply says "Google Play Games keeps stopping"  Open app, close app, feedback options. 

Happens on all the devices I own that use the new GPGs UI.

![image](https://user-images.githubusercontent.com/12730469/49527239-cacafa80-f8b1-11e8-8e4a-930d7b5dfb48.png)

**Comment by olehkuznetsov** [comment]
One known bug for new saves UI - it crashes if save description is null.
It is already fixed but not sure about exact release date yet.

**Comment by blitzcloud** [comment]
Thanks for your answer. I guess in the meantime I will add a description to the saved game.

**Comment by blitzcloud** [comment]
Fixed it after doing the description properly.
