### ISSUE TITLE
IVideoClient not in package

### ISSUE THREAD

**Issue by dashanddot** [playgameservices/play-games-plugin-for-unity#2388]
IVideoClient.cs not in package (GooglePlayGames\BasicApi\Video)

**Comment by olehkuznetsov** [comment]
try to delete plugin and to re-import it.

**Comment by olehkuznetsov** [comment]
Reproduced this after upgrading from 0.9.51 to 0.9.56.

**Comment by olehkuznetsov** [comment]
Fixed in 0.9.57

**Comment by twomedia** [comment]
@olehkuznetsov This same issue seems to be happening after upgrading to the latest release (v0.9.64)

**Comment by olehkuznetsov** [comment]
From which version have you updated?
Try to delete Assets->GooglePlayGames and reimport the plugin, please.

**Comment by ciftciMert** [comment]
> From which version have you updated?
> Try to delete Assets->GooglePlayGames and reimport the plugin, please.

How to delete plugin?
