### ISSUE TITLE
ShowSelectSavedGameUI exception in 0.9.55

### ISSUE THREAD

**Issue by Firemaw** [playgameservices/play-games-plugin-for-unity#2390]
After signing in with EnableSavedGames config, then calling:

`PlayGamesPlatform.Instance.SavedGame.ShowSelectSavedGameUI ("Select saved game", 1, true, false, OnSavedGameSelected);`

Opens and closes the savegame window without allowing the user to interact, then causes an exception. An Android window pops up saying "Play Games has stopped working" with options "Report" or "OK".

Only workaround I could find was to bypass the ShowSelectSavedGameUI altogether and only use OpenWithAutomaticConflictResolution since I am only using a single savegame.

Using 0.9.55 with Unity 2017.4.13f1. AARs 15.0.1 and 26.0.1. Reproduced on Android 7 tablet and Android 4.4 phone. Using same code that worked in 0.9.37. Debug log below:

> 2018-12-07 23:46:41.427 22277-22351/com.comp.proj D/NativeBridgeActivity: Launching bridge activity: parent:com.unity3d.player.UnityPlayerActivity@cee5154 intent Intent { act=com.google.android.gms.games.SHOW_SELECT_SNAPSHOT_V2 dat=version:12451000 flg=0x4000000 pkg=com.google.android.play.games launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }
> 2018-12-07 23:46:41.458 22277-22277/com.comp.proj D/ViewRootImpl@617359f[UnityPlayerActivity]: MSG_WINDOW_FOCUS_CHANGED 0
> 2018-12-07 23:46:41.458 22277-22277/com.comp.proj I/Unity: windowFocusChanged: false
> 2018-12-07 23:46:41.466 22277-22277/com.comp.proj I/Unity: onPause
> 2018-12-07 23:46:41.537 22277-22351/com.comp.proj D/Unity: Sensor :        Accelerometer ( 1) ; 0.001196 / 0.01s ; LSM6DS3 Accelerometer Sensor / STMicroelectronics 
> 2018-12-07 23:46:42.574 22277-22277/com.comp.proj D/ViewRootImpl@617359f[UnityPlayerActivity]: MSG_RESIZED: frame=Rect(0, 0 - 1536, 2048) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 48 - 0, 0) or=1
> 2018-12-07 23:46:42.614 22277-22277/com.comp.proj D/ViewRootImpl@617359f[UnityPlayerActivity]: Relayout returned: oldFrame=[0,0][1536,2048] newFrame=[0,0][1536,2048] result=0x1 surface={isValid=true -1694142464} surfaceGenerationChanged=false
> 2018-12-07 23:46:43.373 22277-22277/com.comp.proj D/ViewRootImpl@617359f[UnityPlayerActivity]: MSG_RESIZED: frame=Rect(0, 0 - 1536, 2048) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
> 2018-12-07 23:46:43.412 22277-22277/com.comp.proj D/ViewRootImpl@617359f[UnityPlayerActivity]: MSG_WINDOW_FOCUS_CHANGED 1
> 2018-12-07 23:46:43.412 22277-22277/com.comp.proj I/Unity: windowFocusChanged: true
> 2018-12-07 23:46:43.432 22277-22277/com.comp.proj D/ViewRootImpl@617359f[UnityPlayerActivity]: Relayout returned: oldFrame=[0,0][1536,2048] newFrame=[0,0][1536,2048] result=0x1 surface={isValid=true -1694142464} surfaceGenerationChanged=false
> 2018-12-07 23:46:43.526 22277-22277/com.comp.proj D/ViewRootImpl@617359f[UnityPlayerActivity]: Relayout returned: oldFrame=[0,0][1536,2048] newFrame=[0,0][1536,2048] result=0x1 surface={isValid=true -1694142464} surfaceGenerationChanged=false
> 2018-12-07 23:46:43.563 22277-22277/com.comp.proj D/ViewRootImpl@617359f[UnityPlayerActivity]: MSG_WINDOW_FOCUS_CHANGED 0
> 2018-12-07 23:46:43.564 22277-22277/com.comp.proj I/Unity: windowFocusChanged: false
> 2018-12-07 23:46:43.595 22277-22277/com.comp.proj D/ViewRootImpl@617359f[UnityPlayerActivity]: Relayout returned: oldFrame=[0,0][1536,2048] newFrame=[0,0][1536,2048] result=0x1 surface={isValid=true -1694142464} surfaceGenerationChanged=false
> 2018-12-07 23:46:43.912 22277-22277/com.comp.proj I/Unity: onResume
> 2018-12-07 23:46:43.918 22277-22277/com.comp.proj D/GamesUnitySDK: Forwarding OnActivityResult
> 2018-12-07 23:46:43.918 22277-22277/com.comp.proj D/GamesUnitySDK: Forwarding OnActivityResult Finished
> 2018-12-07 23:46:52.171 22277-22277/com.comp.proj D/ViewRootImpl@617359f[UnityPlayerActivity]: MSG_WINDOW_FOCUS_CHANGED 1
> 2018-12-07 23:46:52.171 22277-22277/com.comp.proj I/Unity: windowFocusChanged: true
> 2018-12-07 23:46:52.181 22277-22351/com.comp.proj D/Unity: Sensor :        Accelerometer ( 1) ; 0.001196 / 0.01s ; LSM6DS3 Accelerometer Sensor / STMicroelectronics 
> 2018-12-07 23:46:52.187 22277-22351/com.comp.proj D/Unity: Choreographer available: Enabling VSYNC timing

**Comment by blitzcloud** [comment]
This one is a known bug. Give the saved game a description, because the savedgames UI crashes when it has a null description. It's apparently fixed already, but not deployed yet.

https://github.com/playgameservices/play-games-plugin-for-unity/issues/2386

**Comment by Firemaw** [comment]
Ok great, thank you
