### ISSUE TITLE
Cloud Save API Deprecated

### ISSUE THREAD

**Issue by toxikman** [playgameservices/play-games-plugin-for-unity#2394]
[https://developers.google.com/drive/android/deprecation](https://developers.google.com/drive/android/deprecation)
It looks like the Cloud Save system will have to be switched to the REST API instead of the Google Play services Google Drive Android API.

**Comment by olehkuznetsov** [comment]
Play Games services will migrate from drive before deprecation. API will be unchanged.

**Comment by toxikman** [comment]
> Play Games services will migrate from drive before deprecation. API will be unchanged.

You're saying Cloud Save data will no longer be stored on User's Google Drive and will be automatically migrated to a separate Play Game Services cloud store?

**Comment by olehkuznetsov** [comment]
Our intention is to make this drive android API deprecation not noticed by developers using PGS cloud saves, old released games still should continue work with cloud saves without rebuilt.
