### ISSUE TITLE
Message "Install Google Play Games" doesn't show up.

### ISSUE THREAD

**Issue by kesada7** [playgameservices/play-games-plugin-for-unity#2398]
I have a game where I use the Google Play Games leaderboard, everything works ok but in case the user doesn't have Google Play Games installed I know that a message letting him know like the one in this picture should https://i.stack.imgur.com/hJS3Tm.png show up. For some reason, in my game when the user press the Ranking button nothing happens and is confusing for the user, like the button is not working at all, what I want is that the message shows up and tell the user he needs to install Google Play Games when the user presses the button. Any idea? I would put my game here if anyone would be interested to test it but I don't know if that would be considered spam and is again the rules. I appreciate any help thanks.

**Comment by olehkuznetsov** [comment]
How do you Authenticate user to Google Play Games. Is it silent authentication only?

**Comment by kesada7** [comment]
> Games

Hi olehkuznetsov, thanks for answering.

I use in the start method:
 `    Social.localUser.Authenticate((bool success) => {
        // handle success or failure
    });`
 which make a silent authentification if you already signed in the past, that works fine if you have Google Play Games already installed. And then I have a button which checks if the user is logged, if true shows the leaderboard, if false then I call again the same line
 `    Social.localUser.Authenticate((bool success) => {
        // handle success or failure
    });`
 to try log in. Maybe that's the problem since this is trying to make a silent login when you press the button, but according to the documentation, I can not find any other way to authenticate, here a screenshot: https://gyazo.com/66cc331719bdba3c3b96915438894cbd

 Am I missing something? Maybe there is another way to sign in to and force don't to do it silenced that I cannot find.

**Comment by olehkuznetsov** [comment]
Are you using 0.9.57 plugin? This should be fixed there.

**Comment by kesada7** [comment]
> Are you using 0.9.57 plugin? This should be fixed there.

So is it a known bug? I am using 0.9.54 so I will see if I can update it easy to the last version you mentioned and see if that fix the problem.

**Comment by kesada7** [comment]
I tried to update to the last version, but always I do it the game doesn't work. Also, I notice that on some device when you press the ranking button actually the message "Google Play Games needed" appears sometimes. I start to suspect that the problem is maybe caused because of the Appodeal SDK some conflict with the GPG plugin.

**Comment by AlwaysOnlinezzz** [comment]
I have same question.when i installed Google play Games,everything is ok.When i uninstall Google Play Games,there is no message box ,there is some log below:
![image](https://user-images.githubusercontent.com/27004603/50587928-ca2a8180-0eba-11e9-93ef-2261be7aa667.png)

**Comment by olehkuznetsov** [comment]
AlwaysOnlinezzz, what version of the plugin it is?

**Comment by olehkuznetsov** [comment]
Should be fixed in v0.9.58.
