### ISSUE TITLE
Many crash in Unity 2018.3.0f2

### ISSUE THREAD

**Issue by UnityKR** [playgameservices/play-games-plugin-for-unity#2400]
(wrapper unknown) System.IntPtr.PtrToStructure(intptr,object)
Google.Developers.JavaObjWrapper.InvokeObjectCall[T] (System.String name, System.String sig, System.Object[] theArgs) (at <478776940a1649cfbaf03f958737f952>:0)
Google.Developers.JavaObjWrapper.InvokeCall[T] (System.String name, System.String sig, System.Object[] args) (at <478776940a1649cfbaf03f958737f952>:0)
Com.Google.Android.Gms.Games.Stats.StatsObject.loadPlayerStats (Com.Google.Android.Gms.Common.Api.GoogleApiClient arg_GoogleApiClient_1, System.Boolean arg_bool_2) (at <478776940a1649cfbaf03f958737f952>:0)
GooglePlayGames.Native.Android.AndroidClient.GetPlayerStats (System.IntPtr apiClient, System.Action`2[T1,T2] callback) (at <478776940a1649cfbaf03f958737f952>:0)
GooglePlayGames.Native.NativeClient+<>c__DisplayClass46_0.<GetPlayerStats>b__0 () (at <478776940a1649cfbaf03f958737f952>:0)
GooglePlayGames.OurUtils.PlayGamesHelperObject.Update () (at <478776940a1649cfbaf03f958737f952>:0)

**Comment by UnityKR** [comment]
'Managed Stripping Level' Disabled.

**Comment by olehkuznetsov** [comment]
Should be fixed in v0.9.58.
