### ISSUE TITLE
Seperating login errors like authenticate or deny button.

### ISSUE THREAD

**Issue by fatihbulutzula** [playgameservices/play-games-plugin-for-unity#2405]
I'm trying to seperate login sequance errors. I'm trying to seperate login sequance errors, user has denied google login or something else go wrong like authentication error. First of all how can i catch to user denied to google login?

**Comment by olehkuznetsov** [comment]
Currently you can only check the status string in callback.
```
                    if (result == 16 /* CommonStatusCodes.CANCELED */) {
                        InvokeCallbackOnGameThread(localCallback, false, "Authentication canceled");
                    } else if (result == 8 /* CommonStatusCodes.DEVELOPER_ERROR */) {
                        InvokeCallbackOnGameThread(localCallback, false, "Authentication failed - developer error");
                    } else {
                        InvokeCallbackOnGameThread(localCallback, false, "Authentication failed");
                    }
```

**Comment by fatihbulutzula** [comment]
Thank you for your responce @olehkuznetsov . How are you calling CommonStatusCodes ? I need to access it after Social.localUser.Authenticate action returning false.

**Comment by olehkuznetsov** [comment]
Currently you can't access CommonStatusCode you can only use those strings:
`"Authentication canceled", "Authentication failed - developer error", "Authentication failed"`

You can get them in message parameter in your callback like this:
`PlayGamesPlatform.Instance.Authenticate((success, message) => {});`

**Comment by ZOSDanBatson** [comment]
@olehkuznetsov Is there any plan to add the ability to differentiate the errors?  Because the string currently says "Authentication canceled" even if it was because of some other error. Which means we can just kind of have to assume cancellation and never ask again, even when it was an error we might want to retry from next time.  Re: #1884

**Comment by olehkuznetsov** [comment]
Yes, we have such plans to add some error codes after we finish testing/fixing v10 plugin.

**Comment by Ghetaldus** [comment]
Any update on this?
