### ISSUE TITLE
Invisible leaderboards and achievements UI

### ISSUE THREAD

**Issue by m4ff** [playgameservices/play-games-plugin-for-unity#2410]
Plugin version: 0.9.57
Unity version: 2018.3.0f2

Problem: the leaderboards and achievements UIs show up correctly most of the times, but sometimes only an invisible panel seems to overlay the game and block all user input. The game will look like it's frozen, but a swipe down gesture will close the invisible panel.

How to reproduce: reproducing this bug can be quite tricky and require a few attempts, as it seems to be quite random. To increase the probability of reproducing the bug build the game in release mode (no development build) and follow these steps:

1. open the leaderboards UI
2. open a leaderboard
3. click on a username
4. click the overflow button in the top right corner
5. click settings
6. move back clicking the arrow icon in the top left corner two times
7. swipe down to return to the game
8. try to open the leaderboards UI again. You should see the bug, otherwise start again from step 1 until it happens

**Comment by olehkuznetsov** [comment]
Can you check on which Android OS version it happens for you, please?

**Comment by m4ff** [comment]
Version 9. I can't test on other versions at the moment.

**Comment by olehkuznetsov** [comment]
Currently, we are thinking it can be an issue with Android 9 only.

**Comment by olehkuznetsov** [comment]
Should be fixed in v0.10.06. Feel free to reopen if it still reproduces for you with latest plugin version.
