### ISSUE TITLE
App Crash On Load.

### ISSUE THREAD

**Issue by ThePumpel** [playgameservices/play-games-plugin-for-unity#2414]
I an error on loading the app on my device.
This started after I went through the process of adding this plugin to my app (0.9.57).
Maybe it has some sort of conflict with the Google Mobile Ads plugin I use?
When I delete the GooglePlayGames folder the app loads fine. But if I add this plugin it makes the game crash.

I am using:
-Unity 2018.3.1f1.
-The embedded JDK in the Unity version based on OpenJDK 1.8.0_152.
-Android-ndk-r16b.

On Android Device Monitor I get this error, hope it helps!
Thank you in advance.

`01-15` 11:55:23.256: E/AndroidRuntime(14461): java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
01-15 11:55:23.256: E/AndroidRuntime(14461): ******************************************************************************
01-15 11:55:23.256: E/AndroidRuntime(14461): * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
01-15 11:55:23.256: E/AndroidRuntime(14461): * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
01-15 11:55:23.256: E/AndroidRuntime(14461): * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
01-15 11:55:23.256: E/AndroidRuntime(14461): * follow instructions here: https://goo.gl/h17b6x.                           *
01-15 11:55:23.256: E/AndroidRuntime(14461): ******************************************************************************``

**Comment by ThePumpel** [comment]
So I uninstalled and reinstalled android sdk  and plugins. And installed first the google play game services plugin and it worked. After that I installed the Google Mobile Ads plugin and after I made a build the build didn't load and it crashed.

I am guessing I am doing something wrong when importing these two plugins or maybe there is something incompatible that I should remove or modify?

**Comment by CriticalForce** [comment]
I think the answer lies in your logs:

_The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers should follow the instructions here: https://goo.gl/fQ2neu to add a valid App ID inside the AndroidManifest. Google Ad Manager publishers should follow instructions here: https://goo.gl/h17b6x_

> ******************************************************************************
> 01-15 11:55:23.256: E/AndroidRuntime(14461): * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers *
> 01-15 11:55:23.256: E/AndroidRuntime(14461): * should follow the instructions here: https://goo.gl/fQ2neu to add a valid *
> 01-15 11:55:23.256: E/AndroidRuntime(14461): * App ID inside the AndroidManifest. Google Ad Manager publishers should *
> 01-15 11:55:23.256: E/AndroidRuntime(14461): * follow instructions here: https://goo.gl/h17b6x. *
> 01-15 11:55:23.256: E/AndroidRuntime(14461): ******************************************************************************``

**Comment by ThePumpel** [comment]
yeah... I opened the Plugins/Android/GoogleMobileAdsPlugin/AndroidManifest and added these two lines and now it works... 
  <meta-data android:name = "com.google.android.gms.ads.AD_MANAGER_APP" android:value = "true" />
  <meta-data android:name = "com.google.android.gms.ads.APPLICATION_ID" android:value = "ca-app-pub-XXXXXXXXXXXXXXXXXXXXX" />

I thought this was something the plugin did by itself when importing it for some reason.
Anyways thanks!
