### ISSUE TITLE
Huge performance impact from 'unity-jar-resolver'

### ISSUE THREAD

**Issue by nipunasudha** [playgameservices/play-games-plugin-for-unity#2415]
As mentioned in the issue [Resolver causing 0.8-0.9 MB of GC Allocations per frame in Editor](https://github.com/googlesamples/unity-jar-resolver/issues/146) from the 'unity-jar-resolver' repo, **a major fix has been done recently (Dec 18th 2018)** which can drastically improve the unity editor & player performace. To quote the contributor in [his commit](https://github.com/googlesamples/unity-jar-resolver/commit/9911e09ca74d8aa11fefc1fb331391c056a10d66):

> VersionHandler.FindClass() is called a lot throughout the plugin so this commit changes the method to memoize the result of each query to remove any allocation from future searches for the same class.
> Some searches would allocate ~500kb, this eliminates this allocation entirely.
> Issue #146
> Bug: 121162585

This issue has bothered many of us so far. Is there anyway I can get this fix to work with 'play-games-plugin-for-unity'?

**Comment by Noah1911** [comment]
As jar resolver is standalone package you can download it directly from git repository you mentioned and extract it, it should work without any changes to this repository if not, post the error here.

**Comment by nipunasudha** [comment]
I tried replacing the Assets/PlayServicesResolver but it keeps deleting the files I put there! Is this intentional?

**Comment by olehkuznetsov** [comment]
Should be fixed in v0.9.58.
