### ISSUE TITLE
No releases after v0.9.50

### ISSUE THREAD

**Issue by IliyaNovikov** [playgameservices/play-games-plugin-for-unity#2419]
If you check the [Releases](https://github.com/playgameservices/play-games-plugin-for-unity/releases) tab then the latest version you can see is v0.9.50. At the same time the [current-build](https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/current-build) folder offers GooglePlayGamesPlugin-0.9.58.unitypackage. Is there any reason why? Does that mean that any version newer than v0.9.50 is considered development and potentially unsafe?

**Comment by olehkuznetsov** [comment]
Just added v0.9.58 release.
