### ISSUE TITLE
Authorizing failure with cloud save 

### ISSUE THREAD

**Issue by Jamespark0923** [playgameservices/play-games-plugin-for-unity#2421]
When I add a line "EnableSavedGames()", Authorizing always gives failure

PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
                .EnableSavedGames()
                .Build();
->
Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
AuthState == Unauthenticated calling auth callbacks with failure

If I remove "EnableSavedGames()", There are no problems
My gpgs  works very fine with archievements and leaderboards without the saving feature.

I tried 0.9.58 and 0.9.57 both but not working.
My console settings and OAuth sttings are also fine.
- Turned On "Saved Game" of gpgs console
- Added WebApp OAuth 2.0

+Google Drive API has 404 errors on api dashboard when authorizing is failed.

**Comment by olehkuznetsov** [comment]
Before using the Saved Games service, you must first enable it from the Google Play Console:

In the Google Play Console, open the Games services tab, then select your game from the list.
Turn the Saved Games option to ON and agree to the terms of service.
Click Save.
Publish your game changes.
