### ISSUE TITLE
ERROR: Exception launching auth code request: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment

### ISSUE THREAD

**Issue by tinkingli** [playgameservices/play-games-plugin-for-unity#2426]
I have the same problem“ERROR: Exception launching auth code request: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment”
unity version 2017.4.1
On the phone, click on the login will appear this error

**Comment by tinkingli** [comment]
v0.9.58 running is no problem but，When I put it in our project, it will be error

**Comment by Noah1911** [comment]
Post the whole error block with stacktrace, meanwhile you can try _Jar Resolver->Force Resolve_ in menu and see if it helps.
