### ISSUE TITLE
Can't sing in on xiaomi device

### ISSUE THREAD

**Issue by 2rusbekov** [playgameservices/play-games-plugin-for-unity#2430]
Hi. Can't make authentication work on xiaomi device. But everything works on sony xperia. Identical apk. Plugin version 0.9.58. Unity version 2018.3.2.f. Notice that there is exeption on sony device, but not on xiaomi. May be it's silently crashed?

logs from both devices:

[logs.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/2799839/logs.txt)

Code if needed

`
        void Start()
        {
            Debug.Log("Start");
            PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
            .RequestIdToken()
            .Build();

            PlayGamesPlatform.InitializeInstance(config);
            // recommended for debugging:
            PlayGamesPlatform.DebugLogEnabled = true;
            // Activate the Google Play Games platform
            PlayGamesPlatform.Activate();

            //Invoke("StartAuth", 3);
            StartAuth();
        }

        void StartAuth()
        {
            Debug.Log("StartAuth");
            Social.localUser.Authenticate(GameServicesAuthCallback);
        }

        void GameServicesAuthCallback(bool result, string _error)
        {
            Debug.Log("[BI] GameServicesAuthCallback result: " + result + " _error: " + _error);
            if (!result || !string.IsNullOrEmpty(_error))
            {

            }
            else
            {
                Debug.Log("GameServices Authorized");
                OnTokentsGenerated(PlayGamesPlatform.Instance.GetIdToken());
            }
        }
`

**Comment by olehkuznetsov** [comment]
Can you check if it is fixed in v0.9.59, please?

**Comment by 2rusbekov** [comment]
@olehkuznetsov Works perfectly, thanks for so fast response!
