### ISSUE TITLE
TurnBasedGame: CreateWithInvitationScreen & Variant issue

### ISSUE THREAD

**Issue by habitoti** [playgameservices/play-games-plugin-for-unity#2431]
I call 
`void CreateWithInvitationScreen(uint minOpponents, uint maxOpponents, uint variant,
                                        Action<bool, TurnBasedMatch> callback)`

with variant "0", which is denoted in the header comments as "default".
However log produces following error:
`Exception in com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchConfig$Builder.setVariant: java.lang.IllegalArgumentException: Variant must be a positive integer or TurnBasedMatch.MATCH_VARIANT_ANY`

Const. MATCH_VARIANT_ANY isn't available at all (I suppose this would be -1), however that error is produced in _setVariant_ in _TurnBasedMatchConfig.java_:
`public Builder setVariant(int i)
        {
            boolean flag;
            if(i == -1 || i > 0)
                flag = true;
            else
                flag = false;
            er.b(flag, "Variant must be a positive integer or TurnBasedMatch.MATCH_VARIANT_ANY");
            Jv = i;
            return this;
        }`

which fails exactly for variant being 0. Since Variant is an uint in the API, I can't provide -1.

Am I getting something wrong? Maybe I am just somehow confusing sth., because nobody else seems to have an issue here...

Regards, Hans

**Comment by habitoti** [comment]
Tracing this further down, I think the TurnBasedMatch config builder misses a variant "converter" like the realtime match invitation handler has:

`        internal RealtimeRoomConfigBuilder SetVariant(uint variantValue)
        {
            uint variant;
            unchecked {
                variant = variantValue == 0 ? (uint)-1 : variantValue;
            }
            C.RealTimeRoomConfig_Builder_SetVariant(SelfPtr(), variant);
            return this;
        }`

Here the "0" is converted to "-1" (but still casted to a uint -- honestly I don't quite get why this is not pushed through end to end as just int, using the same data structures that the playgames plugin uses?)

**Comment by kaninhot004** [comment]
Set varaint to 1 or more than 1.
I read it from logcat value cannot be lower than 1.

Anddd... 
Did you found this bug like me?

`03-04 23:15:48.149: E/Volley(2744): [188] BasicNetwork.performRequest: Unexpected response code 401 for https://www.googleapis.com/games/v1/turnbasedmatches/create?language=en-GB`


Thanks!

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.

**Comment by habitoti** [comment]
Great answer after > 1 year 👎
