### ISSUE TITLE
Google+ APIs are deprecated. Is this plugin still using them?

### ISSUE THREAD

**Issue by supersolid-federico** [playgameservices/play-games-plugin-for-unity#2433]
Hi all,
we removed Google+ API calls from our project but Google APIs library is still reporting few calls to "plus.people.get" from our game. 
Has this plugin being updated to remove completely Google+ APIs calls?

**Comment by adbourdages** [comment]
I was wondering the same. According to the latest email from Google the game is requesting "plus.login, plus.me, plus.profile.language.read, plus.moments.write, plus.circles.members.read, plus.profile.agerange.read, plus.circles.members".

I was wondering if that is just older version of the game however?

**Comment by SozapBo** [comment]
I just also got the same email as @adbourdages reporting the same requests being made from the plugin. We'll need a fix for it before 7th of Mars.

**Comment by adocwang** [comment]
i just got the same email. Shows i'am using plus.me scope. I'm using almost the latest version of this project. What should i do?

**Comment by olehkuznetsov** [comment]
You can check in the cloud project console if you are using G+ API. 
The plugin before v9.0.10 was used G+ API.

**Comment by ttermeer-reboundcg** [comment]
This is a very important matter and we need an answer asap.

**Comment by ttermeer-reboundcg** [comment]
In Cloud Console, it doesn't show any use of "plus.me" , yet this what the email says we are using.
Is the OAuth Scope "profile" regarded as "plus.me" ?

**Comment by olehkuznetsov** [comment]
'profile' scope is a different to "plus.me" scope. So, if you don't use any explicit plus scopes and plus API you should be safe.

**Comment by SozapBo** [comment]
![bild](https://user-images.githubusercontent.com/22320868/51984769-6933a080-249c-11e9-8ead-0d789cb11f6c.png)

**Comment by SozapBo** [comment]
Got a new email this morning. So, the question still is if this plugin is making any of these calls to the Google+ API?

> Dear Developer,
> 
> Earlier this week we sent you an email related to your projects that will be impacted by the Google+ API shutdown, which also affects requests for Google+ OAuth scopes.
> 
> The email listed that one or more of your projects are requesting the “plus.me” scope, and would thus be affected. We would like to clarify that only projects directly requesting the “plus.me” scope are affected. This scope may have been listed in some emails, even if not directly requested by your project. We apologize for any confusion caused.
> 
> If you are directly requesting the “plus.me” scope, any other Google+ OAuth scopes, or making any Google+ API calls, please ensure that you remove these requests from your project before March 7, 2019.
> 
> To see if your project is directly requesting the “plus.me” or any other Google+ OAuth scopes:
> 
>     If your project is written in Google Apps Script, you can view which scopes your project is requesting by reviewing your project properties in App Script Editor.
>     If your project is not written in Google Apps Script, please check your code for references to “plus.me” in OAuth scope requests. We recommend that you review projects using any 3rd-party libraries that support sign-in or social functionality, as these may also be affected by the shutdown.
> 
> Thanks for being a valued Google+ Developer.
> 
> Sincerely,
> The Google+ API team

**Comment by olehkuznetsov** [comment]
Plugin had dependency on the plus scope in early days. Which plugin version do you use?

**Comment by SozapBo** [comment]
I'm using 0.9.56.

**Comment by olehkuznetsov** [comment]
v0.9.56 isn't using any PLUS scopes for sign-in and doesn't call any PLUS APIs.

**Comment by SozapBo** [comment]
@olehkuznetsov Thanks!

**Comment by Mokalipilou** [comment]
Note that on the email from Google, in the table listing your project(s), you can click on the project name to see a log of the actual calls to the APIs for the last 30 days.
While my Unity project using PlayGames (0.9.50) is listed as using "plus.me" in the warning email, the API usage on google console shows "0" access to "Google+ API". So we should be fine.

**Comment by smithmj5** [comment]
I'm using v0.9.50, having a hard time checking if that version uses PLUS scopes or PLUS APIs - is there somewhere in the code that I can check to figure that out?

**Comment by smithmj5** [comment]
Does anyone know which version of the plugin was the last one that used plus scopes?

Thanks!

**Comment by olehkuznetsov** [comment]
All plugin versions should be compatible with G+ deprecation.

**Comment by supersolid-federico** [comment]
Thanks Olehkuznetsov.
Could you be more precise? "Should be" compatible or "is" compatible?

**Comment by olehkuznetsov** [comment]
All versions are compatible.
