### ISSUE TITLE
Authentication fails with message: "Not implemented on this platform"

### ISSUE THREAD

**Issue by jasrei** [playgameservices/play-games-plugin-for-unity#2434]
I've verified that my SHA1 thumbprint is correct in all 3 places, but I still get a login failure as soon as I try to sign in:

        public void OnSignInButton()
        {
            Social.localUser.Authenticate((bool success, string message) =>
            {
                if (success)
                {
                    Debug.Log("Login Sucess");
                    this.LeaderboardButtonComponent.enabled = true;

                }
                else
                {
                    Debug.Log("Login failed - " + message);
                    Debug.Log(Social.localUser.ToString());
                }
            });
        }

This code produces this output in the console:
Login failed - Not implemented on this platform
UnityEngine.Debug:Log(Object)
[Player: 'localUser' (id )]
UnityEngine.Debug:Log(Object)

Every post I can find about this suggests that my SHA1 thumbprint is wrong somewhere, but I've verified it multiple times now. If anyone can help, I'd really appreciate it. I've been pulling my hair out for hours.

**Comment by Noah1911** [comment]
What platform do you use? Only Android is supported.

**Comment by jasrei** [comment]
I think it was because I was running in the Unity editor.  I guess I have to run on the actual device for it to work?  That makes troubleshooting... interesting.
