### ISSUE TITLE
Strange login situation

### ISSUE THREAD

**Issue by abdulmeLINK** [playgameservices/play-games-plugin-for-unity#2443]
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SocialPlatforms;
using GooglePlayGames;
using GooglePlayGames.BasicApi;

public class PlayGames : MonoBehaviour
{
    public Text a;
    // Start is called before the first frame update
    void Start()
    {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();
        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.Activate();
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    public void SignIn()
    {

       Social.localUser.Authenticate((success) => { 
            if (success)
            {

                a.text = "success";

            }
            else
            {

                a.text = "fail";
            }
        });

    }
    public void sign()
    {
       
        
    }
    public void SignInCallback(bool success)
    {
        if (success)
        {

            a.text = "success";

        }
        else
        {
            
            a.text = "fail";
        }
    }
}
-------------------------------------------------------------------------------------------------------
When I use way of login social.LocalUser with PlayGamesPlatform doesn't react but when I doesn't write about PlayGames it is succes but no UI or react just succes text giving succes react. I tried with PlayGamesPlatform.LoacalUser with Start() function this code didn't worked. I need to help.

**Comment by abdulmeLINK** [comment]
I took a error after android>resolve.
exit code: 1
  at UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) [0x00031] in <e1c3953b4cf040ddb1400046b1c34897>:0 
  at UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) [0x00015] in <e1c3953b4cf040ddb1400046b1c34897>:0 
  at UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, System.String errorMsg) [0x0000a] in <e1c3953b4cf040ddb1400046b1c34897>:0 
  at UnityEditor.Android.PostProcessor.Tasks.BuildResources.CompileResources (UnityEditor.Android.PostProcessor.PostProcessorContext context) [0x001a9] in <e1c3953b4cf040ddb1400046b1c34897>:0 
  at UnityEditor.Android.PostProcessor.Tasks.BuildResources.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) [0x0006c] in <e1c3953b4cf040ddb1400046b1c34897>:0 
  at UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) [0x00074] in <e1c3953b4cf040ddb1400046b1c34897>:0 
UnityEditor.BuildPipeline:BuildPlayerInternalNoCheck()
UnityEditor.DefaultBuildMethods:BuildPlayer(BuildPlayerOptions) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:172)
UnityEditor.BuildPlayerWindow:CallBuildMethods(Boolean, BuildOptions) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:96)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun(Boolean) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:173)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun() (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:167)
 
(Filename: <e1c3953b4cf040ddb1400046b1c34897> Line: 0)

Unloading 4 Unused Serialized files (Serialized files now loaded: 0)
System memory in use before: 203.7 MB.
System memory in use after: 203.8 MB.

Unloading 5 unused Assets to reduce memory usage. Loaded Objects now: 1743.
Total: 18.273900 ms (FindLiveObjects: 0.401200 ms CreateObjectMapping: 0.030400 ms MarkObjects: 17.800100 ms  DeleteObjects: 0.041000 ms)

Load scene 'Temp/__Backupscenes/0.backup' time: 0.024800 ms 
LightmapEditorSettings: switching bake backend from 1 to 0.
Unloading 13 Unused Serialized files (Serialized files now loaded: 0)
System memory in use before: 206.4 MB.
System memory in use after: 206.5 MB.

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 2009.
Total: 17.354100 ms (FindLiveObjects: 0.411400 ms CreateObjectMapping: 0.034600 ms MarkObjects: 16.894200 ms  DeleteObjects: 0.012600 ms)

Assets\GooglePlayGames\ISocialPlatform\PlayGamesAchievement.cs(45,17): warning CS0618: 'WWW' is obsolete: 'Use UnityWebRequest, a fully featured replacement which is more efficient and has additional features'
 
(Filename: Assets\GooglePlayGames\ISocialPlatform\PlayGamesAchievement.cs Line: 45)

Assets\EnemyMover.cs(130,8): warning CS0618: 'Application.LoadLevel(int)' is obsolete: 'Use SceneManager.LoadScene'
 
(Filename: Assets\EnemyMover.cs Line: 130)

Assets\GooglePlayGames\ISocialPlatform\PlayGamesAchievement.cs(126,41): warning CS0618: 'WWW' is obsolete: 'Use UnityWebRequest, a fully featured replacement which is more efficient and has additional features'
 
(Filename: Assets\GooglePlayGames\ISocialPlatform\PlayGamesAchievement.cs Line: 126)

Assets\GooglePlayGames\ISocialPlatform\PlayGamesUserProfile.cs(134,17): warning CS0618: 'WWW' is obsolete: 'Use UnityWebRequest, a fully featured replacement which is more efficient and has additional features'
 
(Filename: Assets\GooglePlayGames\ISocialPlatform\PlayGamesUserProfile.cs Line: 134)

Assets\GooglePlayGames\ISocialPlatform\PlayGamesUserProfile.cs(134,31): warning CS0618: 'WWW' is obsolete: 'Use UnityWebRequest, a fully featured replacement which is more efficient and has additional features'
 
(Filename: Assets\GooglePlayGames\ISocialPlatform\PlayGamesUserProfile.cs Line: 134)

Assets\PauseBtnandRestart.cs(47,9): warning CS0618: 'Application.LoadLevel(int)' is obsolete: 'Use SceneManager.LoadScene'
 
(Filename: Assets\PauseBtnandRestart.cs Line: 47)

Assets\PauseBtnandRestart.cs(57,9): warning CS0618: 'Application.LoadLevel(int)' is obsolete: 'Use SceneManager.LoadScene'
 
(Filename: Assets\PauseBtnandRestart.cs Line: 57)

Assets\reklam.cs(31,17): warning CS0618: 'GameObject.active' is obsolete: 'GameObject.active is obsolete. Use GameObject.SetActive(), GameObject.activeSelf or GameObject.activeInHierarchy.'
 
(Filename: Assets\reklam.cs Line: 31)

Assets\SpawnerPositionCollector.cs(29,13): warning CS0618: 'GameObject.active' is obsolete: 'GameObject.active is obsolete. Use GameObject.SetActive(), GameObject.activeSelf or GameObject.activeInHierarchy.'
 
(Filename: Assets\SpawnerPositionCollector.cs Line: 29)

Assets\SpawnerPositionCollector.cs(42,16): warning CS0618: 'GameObject.active' is obsolete: 'GameObject.active is obsolete. Use GameObject.SetActive(), GameObject.activeSelf or GameObject.activeInHierarchy.'
 
(Filename: Assets\SpawnerPositionCollector.cs Line: 42)

Assets\SpawnerPositionCollector.cs(46,18): warning CS0618: 'GameObject.active' is obsolete: 'GameObject.active is obsolete. Use GameObject.SetActive(), GameObject.activeSelf or GameObject.activeInHierarchy.'
 
(Filename: Assets\SpawnerPositionCollector.cs Line: 46)

Assets\SpawnerPositionCollector.cs(48,18): warning CS0618: 'GameObject.active' is obsolete: 'GameObject.active is obsolete. Use GameObject.SetActive(), GameObject.activeSelf or GameObject.activeInHierarchy.'
 
(Filename: Assets\SpawnerPositionCollector.cs Line: 48)

Assets\SpawnerPositionCollector.cs(50,18): warning CS0618: 'GameObject.active' is obsolete: 'GameObject.active is obsolete. Use GameObject.SetActive(), GameObject.activeSelf or GameObject.activeInHierarchy.'
 
(Filename: Assets\SpawnerPositionCollector.cs Line: 50)

Assets\SpawnerPositionCollector.cs(52,18): warning CS0618: 'GameObject.active' is obsolete: 'GameObject.active is obsolete. Use GameObject.SetActive(), GameObject.activeSelf or GameObject.activeInHierarchy.'
 
(Filename: Assets\SpawnerPositionCollector.cs Line: 52)

Assets\SpawnerPositionCollector.cs(54,18): warning CS0618: 'GameObject.active' is obsolete: 'GameObject.active is obsolete. Use GameObject.SetActive(), GameObject.activeSelf or GameObject.activeInHierarchy.'
 
(Filename: Assets\SpawnerPositionCollector.cs Line: 54)

Assets\GooglePlayGames\Editor\GPGSProjectSettings.cs(100,24): warning CS0618: 'WWW' is obsolete: 'Use UnityWebRequest, a fully featured replacement which is more efficient and has additional features'
 
(Filename: Assets\GooglePlayGames\Editor\GPGSProjectSettings.cs Line: 100)

Assets\GooglePlayGames\Editor\GPGSProjectSettings.cs(112,30): warning CS0618: 'WWW' is obsolete: 'Use UnityWebRequest, a fully featured replacement which is more efficient and has additional features'
 
(Filename: Assets\GooglePlayGames\Editor\GPGSProjectSettings.cs Line: 112)

Assets\GooglePlayGames\Editor\GPGSProjectSettings.cs(138,30): warning CS0618: 'WWW' is obsolete: 'Use UnityWebRequest, a fully featured replacement which is more efficient and has additional features'
 
(Filename: Assets\GooglePlayGames\Editor\GPGSProjectSettings.cs Line: 138)

Build completed with a result of 'Failed'
UnityEngine.DebugLogHandler:Internal_Log()
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UnityEditor.DefaultBuildMethods:BuildPlayer(BuildPlayerOptions) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:189)
UnityEditor.BuildPlayerWindow:CallBuildMethods(Boolean, BuildOptions) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:96)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun(Boolean) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:173)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun() (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:167)
 
(Filename: C:/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs Line: 189)

UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x00234] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:190 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x0007f] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:96 
UnityEngine.DebugLogHandler:Internal_Log()
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UnityEditor.BuildPlayerWindow:CallBuildMethods(Boolean, BuildOptions) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:101)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun(Boolean) (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:173)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun() (at C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindow.cs:167)
 
(Filename: C:/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs Line: 101)

**Comment by olehkuznetsov** [comment]
Which plugin version do you use?

**Comment by abdulmeLINK** [comment]
9.60 i tried 9.58 same error occured. I changed JAVA_HOME path was program files(x86) i changed program files and play services resolving error solved but I took a failed to re-packing
`CommandInvokationFailure: Failed to re-package resources.
C:\Android\Sdk\build-tools\28.0.3\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "C:/Android/Sdk\platforms\android-26\android.jar" -F bin/resources.ap_ --extra-packages com.admob.plugin:android.arch.lifecycle:android.support.compat:android.support.coreui:android.support.coreutils:android.support.fragment:android.support.mediacompat:android.support.v4:com.google.android.gms.auth.api:com.google.android.gms.auth.api.phone:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms.common:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.tasks:com.google.games.bridge:android.support.customtabs:com.google.example.games.mainlibproj:com.google.android.gms.ads.impl:com.google.android.gms.ads_base:com.google.android.gms.ads_identifier:com.google.android.gms.ads:com.google.android.gms.common:com.google.android.gms.gass:com.google.android.gms.measurement_base:com.google.android.gms.measurement.sdk.api:android.arch.lifecycle:android.support.compat:android.support.coreui:android.support.coreutils:android.support.fragment:android.support.mediacompat:android.support.v4:com.unity3d.ads -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\admoblib-release\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\android.arch.lifecycle.runtime-1.0.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\com.android.support.support-compat-26.1.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\com.android.support.support-core-ui-26.1.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\com.android.support.support-core-utils-26.1.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\com.android.support.support-fragment-26.1.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-26.1.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\com.android.support.support-v4-26.1.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-auth-16.0.1\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-base-16.0.1\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-basement-16.0.1\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\com.google.games.gpgs-plugin-support-0.9.58\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\customtabs-26.1.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\play-services-ads-17.0.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\play-services-ads-lite-17.0.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\play-services-basement-16.0.1\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\runtime-1.0.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\support-compat-26.1.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\support-core-ui-26.1.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\support-core-utils-26.1.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\support-fragment-26.1.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\support-media-compat-26.1.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\support-v4-26.1.0\res" -S "C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\UnityAds\res"

stderr[
C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\com.android.support.support-compat-26.1.0\res\values\values.xml:7: error: Attribute "fontProviderFetchStrategy" already defined with incompatible format.
C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\support-compat-26.1.0\res\values\values.xml:9: Original attribute defined here.
C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\com.android.support.support-compat-26.1.0\res\values\values.xml:12: error: Attribute "fontProviderFetchTimeout" already defined with incompatible format.
C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\support-compat-26.1.0\res\values\values.xml:14: Original attribute defined here.
C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\com.android.support.support-compat-26.1.0\res\values\values.xml:16: error: Attribute "fontStyle" already defined with incompatible format.
C:\Users\CYBER_SHOOT\Desktop\unity projesi\2Dandroid\Temp\StagingArea\android-libraries\support-compat-26.1.0\res\values\values.xml:17: Original attribute defined here.
]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: C:\Android\Sdk\platforms\android-26\android.jar
applyFileOverlay for drawable
trying overlaySet Key=notification_action_background.xml
trying overlaySet Key=notification_bg.xml
trying overlaySet Key=notification_bg_low.xml
trying overlaySet Key=notification_bg_low_normal.9.png
trying overlaySet Key=notification_bg_low_pressed.9.png
trying overlaySet Key=notification_bg_normal.9.png
trying overlaySet Key=notification_bg_normal_pressed.9.png
trying overlaySet Key=notification_icon_background.xml
trying overlaySet Key=notification_tile_bg.xml
trying overlaySet Key=notify_panel_notification_icon_bg.png
trying overlaySet Key=ic_launcher.png
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_normal_background.9.png
trying overlaySet Key=common_google_signin_btn_icon_disabled.xml
trying overlaySet Key=common_google_signin_btn_icon_light.xml
trying overlaySet Key=common_google_signin_btn_icon_light_focused.xml
trying overlaySet Key=common_google_signin_btn_icon_light_normal.xml
trying overlaySet Key=common_google_signin_btn_icon_light_normal_background.9.png
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_dark_focused.xml
trying overlaySet Key=common_google_signin_btn_text_dark_normal.xml
trying overlaySet Key=common_google_signin_btn_text_dark_normal_background.9.png
trying overlaySet Key=common_google_signin_btn_text_disabled.xml
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_google_signin_btn_text_light_focused.xml
trying overlaySet Key=common_google_signin_btn_text_light_normal.xml
trying overlaySet Key=common_google_signin_btn_text_light_normal_background.9.png
trying overlaySet Key=googleg_disabled_color_18.png
trying overlaySet Key=googleg_standard_color_18.png
trying overlaySet Key=common_google_signin_btn_text_dark_normal.xml
baseFile 0 has flavor 
overlayFile 0 has flavor watch-v20
nothing matches overlay file common_google_signin_btn_text_dark_normal.xml, for flavor watch-v20
trying overlaySet Key=common_google_signin_btn_text_disabled.xml
baseFile 0 has flavor 
overlayFile 0 has flavor watch-v20
nothing matches overlay file common_google_signin_btn_text_disabled.xml, for flavor watch-v20
trying overlaySet Key=common_google_signin_btn_text_light_normal.xml
baseFile 0 has flavor 
overlayFile 0 has flavor watch-v20
nothing matches overlay file common_google_signin_btn_text_light_normal.xml, for flavor watch-v20
trying overlaySet Key=notification_action_background.xml
baseFile 0 has flavor v21
overlayFile 0 has flavor v21
found a match (0) for overlay file notification_action_background.xml, for flavor v21
trying overlaySet Key=notification_bg.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file notification_bg.xml, for flavor 
trying overlaySet Key=notification_bg_low.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file notification_bg_low.xml, for flavor 
trying overlaySet Key=notification_bg_low_normal.9.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor hdpi-v4
baseFile 2 has flavor xhdpi-v4
overlayFile 0 has flavor mdpi-v4
overlayFile 1 has flavor hdpi-v4
overlayFile 2 has flavor xhdpi-v4
found a match (0) for overlay file notification_bg_low_normal.9.png, for flavor mdpi-v4
found a match (1) for overlay file notification_bg_low_normal.9.png, for flavor hdpi-v4
found a match (2) for overlay file notification_bg_low_normal.9.png, for flavor xhdpi-v4
trying overlaySet Key=notification_bg_low_pressed.9.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor hdpi-v4
baseFile 2 has flavor xhdpi-v4
overlayFile 0 has flavor mdpi-v4
overlayFile 1 has flavor hdpi-v4
overlayFile 2 has flavor xhdpi-v4
found a match (0) for overlay file notification_bg_low_pressed.9.png, for flavor mdpi-v4
found a match (1) for overlay file notification_bg_low_pressed.9.png, for flavor hdpi-v4
found a match (2) for overlay file notification_bg_low_pressed.9.png, for flavor xhdpi-v4
trying overlaySet Key=notification_bg_normal.9.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor hdpi-v4
baseFile 2 has flavor xhdpi-v4
overlayFile 0 has flavor mdpi-v4
overlayFile 1 has flavor hdpi-v4
overlayFile 2 has flavor xhdpi-v4
found a match (0) for overlay file notification_bg_normal.9.png, for flavor mdpi-v4
found a match (1) for overlay file notification_bg_normal.9.png, for flavor hdpi-v4
found a match (2) for overlay file notification_bg_normal.9.png, for flavor xhdpi-v4
trying overlaySet Key=notification_bg_normal_pressed.9.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor hdpi-v4
baseFile 2 has flavor xhdpi-v4
overlayFile 0 has flavor mdpi-v4
overlayFile 1 has flavor hdpi-v4
overlayFile 2 has flavor xhdpi-v4
found a match (0) for overlay file notification_bg_normal_pressed.9.png, for flavor mdpi-v4
found a match (1) for overlay file notification_bg_normal_pressed.9.png, for flavor hdpi-v4
found a match (2) for overlay file notification_bg_normal_pressed.9.png, for flavor xhdpi-v4
trying overlaySet Key=notification_icon_background.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file notification_icon_background.xml, for flavor 
trying overlaySet Key=notification_tile_bg.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file notification_tile_bg.xml, for flavor 
trying overlaySet Key=notify_panel_notification_icon_bg.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor hdpi-v4
baseFile 2 has flavor xhdpi-v4
overlayFile 0 has flavor mdpi-v4
overlayFile 1 has flavor hdpi-v4
overlayFile 2 has flavor xhdpi-v4
found a match (0) for overlay file notify_panel_notification_icon_bg.png, for flavor mdpi-v4
found a match (1) for overlay file notify_panel_notification_icon_bg.png, for flavor hdpi-v4
found a match (2) for overlay file notify_panel_notification_icon_bg.png, for flavor xhdpi-v4
trying overlaySet Key=app_banner.png
applyFileOverlay for layout
trying overlaySet Key=notification_media_action.xml
trying overlaySet Key=notification_media_cancel_action.xml
trying overlaySet Key=notification_template_big_media.xml
trying overlaySet Key=notification_template_big_media_custom.xml
trying overlaySet Key=notification_template_big_media_narrow.xml
trying overlaySet Key=notification_template_big_media_narrow_custom.xml
trying overlaySet Key=notification_template_lines_media.xml
trying overlaySet Key=notification_template_media.xml
trying overlaySet Key=notification_template_media_custom.xml
trying overlaySet Key=notification_action.xml
trying overlaySet Key=notification_action_tombstone.xml
trying overlaySet Key=notification_template_custom_big.xml
trying overlaySet Key=notification_template_icon_group.xml
trying overlaySet Key=notification_template_part_chronometer.xml
trying overlaySet Key=notification_template_part_time.xml
trying overlaySet Key=notification_media_action.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file notification_media_action.xml, for flavor 
trying overlaySet Key=notification_media_cancel_action.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file notification_media_cancel_action.xml, for flavor 
trying overlaySet Key=notification_template_big_media.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file notification_template_big_media.xml, for flavor 
trying overlaySet Key=notification_template_big_media_custom.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file notification_template_big_media_custom.xml, for flavor 
trying overlaySet Key=notification_template_big_media_narrow.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file notification_template_big_media_narrow.xml, for flavor 
trying overlaySet Key=notification_template_big_media_narrow_custom.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file notification_template_big_media_narrow_custom.xml, for flavor 
trying overlaySet Key=notification_template_lines_media.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file notification_template_lines_media.xml, for flavor 
trying overlaySet Key=notification_template_media.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file notification_template_media.xml, for flavor 
trying overlaySet Key=notification_template_media_custom.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file notification_template_media_custom.xml, for flavor 
trying overlaySet Key=notification_action.xml
baseFile 0 has flavor 
baseFile 1 has flavor v21
overlayFile 0 has flavor 
overlayFile 1 has flavor v21
found a match (0) for overlay file notification_action.xml, for flavor 
found a match (1) for overlay file notification_action.xml, for flavor v21
trying overlaySet Key=notification_action_tombstone.xml
baseFile 0 has flavor 
baseFile 1 has flavor v21
overlayFile 0 has flavor 
overlayFile 1 has flavor v21
found a match (0) for overlay file notification_action_tombstone.xml, for flavor 
found a match (1) for overlay file notification_action_tombstone.xml, for flavor v21
trying overlaySet Key=notification_template_custom_big.xml
baseFile 0 has flavor 
baseFile 1 has flavor v16
baseFile 2 has flavor v21
overlayFile 0 has flavor 
overlayFile 1 has flavor v16
overlayFile 2 has flavor v21
found a match (0) for overlay file notification_template_custom_big.xml, for flavor 
found a match (1) for overlay file notification_template_custom_big.xml, for flavor v16
found a match (2) for overlay file notification_template_custom_big.xml, for flavor v21
trying overlaySet Key=notification_template_icon_group.xml
baseFile 0 has flavor 
baseFile 1 has flavor v21
overlayFile 0 has flavor 
overlayFile 1 has flavor v21
found a match (0) for overlay file notification_template_icon_group.xml, for flavor 
found a match (1) for overlay file notification_template_icon_group.xml, for flavor v21
trying overlaySet Key=notification_template_part_chronometer.xml
baseFile 0 has flavor 
overlayFile 0 has flavor 
found a match (0) for overlay file notification_template_part_chronometer.xml, for flavor 
trying ove<message truncated>`

**Comment by abdulmeLINK** [comment]
> Which plugin version do you use?

**Comment by abdulmeLINK** [comment]
I tested without Admob and it is builded but when i test with in admob build give failed to re-packing error.
I don't know which one is toxic. one by one working but together don't working.
please help me.
