### ISSUE TITLE
Login Failed on Debug Log

### ISSUE THREAD

**Issue by rigby00** [playgameservices/play-games-plugin-for-unity#2447]
Hi, 

I'm using Unity 2018.3.5 and Google Play Services 9.60 everything is normal. But when i start app to connect google play services it says "Login Failed". I checked everyting sha1 etc etc nothing solved my problem. Can you help please.

Thanks.

**Comment by kreesty** [comment]
Same. I tried 9.60 and 9.53 and it happens with both.

**Comment by rigby00** [comment]
> Same. I tried 9.60 and 9.53 and it happens with both.

**Yes but i didn't found any solution can you help us guys please. Thanks.**

**Comment by vaibhavgpt-google** [comment]
The issue is not comprehensive enough. Closing the issue as of now, please re-open it, if you are still facing it.
Thanks
