### ISSUE TITLE
Simple Question, what about different app versions?

### ISSUE THREAD

**Issue by Lestat** [playgameservices/play-games-plugin-for-unity#2451]
Lets suppose player A has version 1.0 of my game with 10 units available to build.
And player B has version 2.0, with 11 units available to build.

How do I prevent them from entering a match together? or is it automatic in the library? Does it already check product version and filters rooms accordingly?

**Comment by olehkuznetsov** [comment]
Good question, I think there is no automatic support for this.

**Comment by Lestat** [comment]
ait seems i have tobuse room variants for this. but then k cannot use them for game modes. that was the intended use i guess. It would be simpler if there were string instead of int type. I could "v1.0freeforall" "v2.0captheflag" etc. my current game has only one game mode so its not a problem for me yet :p

**Comment by olehkuznetsov** [comment]
Yes, using room variant is a great idea.
For different versions/modes you can just combine them in one integer like 
variant = mode * 100000 + version;
or the same idea using bit operations.
