### ISSUE TITLE
RealtimeMultiplayer exception crash my game

### ISSUE THREAD

**Issue by tietagio** [playgameservices/play-games-plugin-for-unity#2453]
i have integrated and implemented this plugin but i got this log please help

NullReferenceException: Object reference not set to an instance of an object
GooglePlayGames.PlayGamesPlatform.get_RealTime () (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:155)
GameplayManager.<SignIn>m__0 (Boolean success) (at Assets/Gameplay/GameplayManager.cs:45)
UnityEngine.SocialPlatforms.Local.UnityEngine.SocialPlatforms.ISocialPlatform.Authenticate (ILocalUser user, System.Action`1 callback) (at /Users/builduser/buildslave/unity/build/Modules/GameCenter/Managed/LocalService.cs:430)
UnityEngine.SocialPlatforms.Impl.LocalUser.Authenticate (System.Action`1 callback) (at /Users/builduser/buildslave/unity/build/Modules/GameCenter/Managed/LocalService.cs:21)
GameplayManager.SignIn () (at Assets/Gameplay/GameplayManager.cs:40)
GameplayManager.Start () (at Assets/Gameplay/GameplayManager.cs:30)

**Comment by olehkuznetsov** [comment]
What plugin version do you use? Can you provide more logcat entries, please?

**Comment by tietagio** [comment]
i used latest version i just downloaded yesterday and what happen is
when i test that on device
login  --> success popup and login
after i call function to create multiplayer room
// authenticate user:
        Social.localUser.Authenticate((bool success) => {
            PlayGamesPlatform.Instance.RealTime.CreateQuickGame(1, 6, 0, this);
            if(success){
                PlayGamesPlatform.Instance.RealTime.CreateQuickGame(1, 6, 0, this);
                CanvasOnSuccess.gameObject.SetActive(false);
            }
        });

but this generate exception NULL on "RealTime" Object
![snip20190213_2](https://user-images.githubusercontent.com/29239571/52712316-e3841a80-2f9c-11e9-915e-d617f3c505f5.png)

**Comment by olehkuznetsov** [comment]
Is it possible you've directly created instance entry in Google Cloud project instead linking the Android app in Play Console?

**Comment by tietagio** [comment]
my app was linked successfully
![snip20190213_3](https://user-images.githubusercontent.com/29239571/52715771-f6e7b380-2fa5-11e9-986b-764b24de4812.png)

i just asking how to fix that ?

**Comment by tietagio** [comment]
yes of course

**Comment by olehkuznetsov** [comment]
Can you try SmokeTest sample, please? You can just import it to a new project and just use your game data from Play Console. I mean you don't need to create new project and set it up, just reuse already created.
Also comment those lines in MainGui.cs:
.RequestServerAuthCode(false)
.RequestIdToken()

This sample contains Multiplayer sample code.

**Comment by tietagio** [comment]
i need realtime so can i try QuizeRacer instead?

**Comment by tietagio** [comment]
not auth in editor but instance of realtime is null instead of rise exception
![snip20190213_9](https://user-images.githubusercontent.com/29239571/52718845-17673c00-2fad-11e9-8fb1-7e810ad2635d.png)

mean it will SET if i am authenticated ,, now problem clear in my implementation i will build that to see how its look like on device

**Comment by tietagio** [comment]
on device failed to authenticate after popup showing

**Comment by olehkuznetsov** [comment]
Have you checked logcat? In some cases it can give some clues why authentication has failed.

**Comment by bbekec** [comment]
try this, 
define global play services variables in Start method.
for example, 

Participant participant;

private void Start()
{
        participant = PlayGamesPlatform.Instance.RealTime.GetSelf();
}

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
