### ISSUE TITLE
Users Can't Login Google Play

### ISSUE THREAD

**Issue by rigby00** [playgameservices/play-games-plugin-for-unity#2458]
Hi,

I published my game. I can login but users can't login google play. How can i fix it?

Version 9.60

Thanks. @olehkuznetsov 

Here is my code;
`
public string leaderboard;
    void Start()
    {
        
            PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();
            PlayGamesPlatform.InitializeInstance(config);
            PlayGamesPlatform.Activate();

            LogIn();
        
    }

    public void LogIn()
    {
        if (Application.internetReachability != NetworkReachability.NotReachable)
        {
            Social.localUser.Authenticate((bool success) =>
            {
                if (success)
                {
                    Debug.Log("Login Sucess");
                }
                else
                {
                    Debug.Log("Login failed");
                }
            });
        }
    }
`

**Comment by Salranax** [comment]
Can you post the log?

**Comment by sptkjs** [comment]
I have same issue too on Version 9.61. 
Logs :
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-21 10:12:17.074 21310 21342 I Unity   :
02-21 10:12:17.109 21310 21342 W Unity   : !!! [Play Games Plugin DLL] 02/21/19 10:12:17 +09:00 WARNING: Creating new PlayGamesPlatform
02-21 10:12:17.109 21310 21342 W Unity   :
02-21 10:12:17.109 21310 21342 W Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-21 10:12:17.109 21310 21342 W Unity   :
02-21 10:12:17.109 21310 21342 I Unity   :  [Play Games Plugin DLL] 02/21/19 10:12:17 +09:00 DEBUG: Creating platform-specific Play Games client.
02-21 10:12:17.109 21310 21342 I Unity   :
02-21 10:12:17.109 21310 21342 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-21 10:12:17.109 21310 21342 I Unity   :
02-21 10:12:17.109 21310 21342 I Unity   :  [Play Games Plugin DLL] 02/21/19 10:12:17 +09:00 DEBUG: Creating Android IPlayGamesClient Client
02-21 10:12:17.109 21310 21342 I Unity   :
02-21 10:12:17.109 21310 21342 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-21 10:12:17.109 21310 21342 I Unity   :
02-21 10:12:19.156 21310 21342 I Unity   :  [Play Games Plugin DLL] 02/21/19 10:12:19 +09:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
02-21 10:12:19.156 21310 21342 I Unity   :
02-21 10:12:19.156 21310 21342 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-21 10:12:19.156 21310 21342 I Unity   :
02-21 10:12:19.156 21310 21342 I Unity   :  [Play Games Plugin DLL] 02/21/19 10:12:19 +09:00 DEBUG: Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
02-21 10:12:19.156 21310 21342 I Unity   :
02-21 10:12:19.156 21310 21342 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-21 10:12:19.156 21310 21342 I Unity   :
02-21 10:12:19.156 21310 21342 I Unity   :  [Play Games Plugin DLL] 02/21/19 10:12:19 +09:00 DEBUG: there are pending auth callbacks - starting AuthUI
02-21 10:12:19.156 21310 21342 I Unity   :
02-21 10:12:19.156 21310 21342 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-21 10:12:19.156 21310 21342 I Unity   :
02-21 10:12:19.745 21310 21342 I Unity   :  [Play Games Plugin DLL] 02/21/19 10:12:19 +09:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
02-21 10:12:19.745 21310 21342 I Unity   :
02-21 10:12:19.745 21310 21342 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-21 10:12:19.745 21310 21342 I Unity   :
02-21 10:12:19.746 21310 21342 I Unity   :  [Play Games Plugin DLL] 02/21/19 10:12:19 +09:00 DEBUG: AuthState == Unauthenticated calling auth callbacks with failure

**Comment by Salranax** [comment]
@sptkjs  can you remove EnableSavedGames() method from 
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().EnableSavedGames().Build(); and try it again?

**Comment by sptkjs** [comment]
@Salranax I removed EnableSavedGames() method But i do not login google play service. So i checked google api console, confirmed google play service and drive are occurring errors.

**Comment by upln** [comment]
Same problem, i wait 24h like the documentation says !
But on 20h it's not working for me !!!
I don't undersand ? without .EnableSavedGames() the login is successfuly ?

**Comment by olehkuznetsov** [comment]
Should be already fixed server side. Try again, please.
