### ISSUE TITLE
Can't sign in after updating to version 0.9.61

### ISSUE THREAD

**Issue by babak-ss** [playgameservices/play-games-plugin-for-unity#2459]
I've updated my GPGS from version 0.9.56 to 0.9.61 and I'm getting this error on logcat:

`*** [Play Games Plugin DLL] 02/16/19 20:04:29 +03:30 ERROR: UnityEngine.AndroidJavaException: java.lang.NoSuchMethodError: no static method with name='fetchToken' signature='(Lcom.unity3d.player.UnityPlayerActivity;ZZZZLjava/lang/String;Z[Ljava/lang/String;ZLjava/lang/Object;)Ljava/lang/Object;' in class Lcom.google.games.bridge.TokenFragment;
java.lang.NoSuchMethodError: no static method with name='fetchToken' signature='(Lcom.unity3d.player.UnityPlayerActivity;ZZZZLjava/lang/String;Z[Ljava/lang/String;ZLjava/lang/Object;)Ljava/lang/Object;' in class Lcom.google.games.bridge.TokenFragment;
	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:49)
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
	at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
	at android.os.MessageQueue.next(MessageQueue.java:394)
	at android.os.Looper.loop(Looper.java:142)
	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
  at Uni`

I've deleted Assets/GooglePlayGames and Assets/PlayServicesResolver directories before importing the new package and then from Assets>Play Services Resolver>Android I clicked on "Force Resolve".  There were no editor errors and everything else was fine.

After that, I've accorded to some gradle build errors saying some of my libraries can't be found (for example error said can't find com.google.android.gms.play-services-ads-17.1.2.aar while I had 17.1.3) so I rolled back all of my libraries in Assets/Plugin/Android folder to older versions for this specific libraries and the error was gone.

Then, I build my game to my device but I couldn't sign In to Google Play Services and above is the logcat.

I appreciate any kind of help...
Thanks in advance

**Comment by 88san88** [comment]
same issue I couldn't sign in into Google Play services (sign-in-failed error) after upgrading from version 0.9.50 to 0.9.61 (0.9.50 work fine). I tried with deleting GooglePlayGames and PlayServicesResolver still same issue. The resolver seems to work fine and unity didn't recognize any issue.

**Comment by babak-ss** [comment]
the error was because of some specific libraries have been add to dependencies section in /Assets/Plugins/Android/mainTemplate.gradle
for example I had `implementation(name: 'com.google.games.gpgs-plugin-support-0.9.50', ext:'aar')` in dependencies but in /Assets/Plugins/Android/ I had 0.9.61 version
so I changed that line to `implementation(name: 'com.google.games.gpgs-plugin-support-0.9.61', ext:'aar')` and no errors accured when building and everything with Play Games worked fine I was able to sign in to my Google Play Games account.

**Comment by 88san88** [comment]
Thanks for reply, I don't know if  I should comment here after the issue closed or open new issue. I use unity 2017 and there is no gradle file in that directory , so I exported the project into gradle project and fine the line you mentioned in your comment  in build.gradle `compile(name: 'com.google.games.gpgs-plugin-support-0.9.61', ext:'aar')`
and it looks the right version  (0.9.61).
So your solution wasn't working for me, should I open new Issue?
