### ISSUE TITLE
GetStats callback should be on game thread

### ISSUE THREAD

**Issue by vandelpal** [playgameservices/play-games-plugin-for-unity#2462]
GetStats should be using InvokeCallbackOnGameThread to call the callback but it's not
From the documentation of IPlayGamesClient :
/// CALLBACKS: all callbacks must be invoked in Unity's main thread.

**Comment by olehkuznetsov** [comment]
Should be fixed already in v0.10.06. Feel free to reopen if it reproduces with latest plugin version.
