### ISSUE TITLE
OnRealTimeMessageReceived doesnt get datas

### ISSUE THREAD

**Issue by bbekec** [playgameservices/play-games-plugin-for-unity#2464]
Hello, 
I m working on a card game. The users are successfully connected each other and they are joining the gameplay room. But the message is not sent to each other.
I created a UI Button and Text to check datas are received but nothing happens.
On Unity, I m not able to get debug.log. Just i can try codes on virtual devices and on mobile phone.
Can anyone help me?
thanks.
![ss2](https://user-images.githubusercontent.com/6454799/53117998-2fb2fa00-355d-11e9-9603-54f01f5d91bf.png)
![ss1](https://user-images.githubusercontent.com/6454799/53117999-2fb2fa00-355d-11e9-9ed5-cf5b4107afb5.png)

**Comment by olehkuznetsov** [comment]
Can you recheck the same in SmokeTest sample, please?

**Comment by bbekec** [comment]
I solved the problem by adding a tag to the object.
I added a tag to gameobject, then i searched the  gameobject by tag in script. It solved the problem.
But Searching by name or adding gameobject manually is not worked for me while data transfer .

**Comment by bbekec** [comment]
Hello again,
I supposed that I solved problem but tagging a gameobject and calling it is not a clear solution. 
I have a card game and dealing cards to other gamers on realtime messaging. I have a for loop which creates card names as data string.

Begin Class:
        for (int i = 0; i < cardNames.Count; i++)
        {
           playServiceConnect.sendData("A", cardNames[i].gameObject.name);
           Destroy(cardnames.transform.GetChild(i).gameObject);
        }
            The cards have to be sorted as the dealers deck but cards are shuffling while the datas are arrived and each decks sort is different from each other.
any help?
thanks

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
