### ISSUE TITLE
Authentication canceled

### ISSUE THREAD

**Issue by kreesty** [playgameservices/play-games-plugin-for-unity#2467]
After adding ".EnableSavedGames()", it refuses to log in, with the error always being "Authentication canceled".
No errors in the console whatsoever.
Saved games is enabled in the game services so that's not the problem.

**Comment by M-allaham** [comment]
I have the same issue , did you find a solution?

**Comment by olehkuznetsov** [comment]
Should be already fixed server side. Try again, please.
