### ISSUE TITLE
Authentication fails when PlayGamesClientConfiguration is built- Unity 2018 3.5f1 and playgames api v 0.9.61

### ISSUE THREAD

**Issue by Sailendrakc** [playgameservices/play-games-plugin-for-unity#2470]
In order to read and write data in cloud, I have to enable the saved games and thus build a PlayGamesClientConfiguration. But as i build it and run, my authentication fails to authenticate.
The bool "Success" of line 85 returns false in this case.
 The code is this:
![send1](https://user-images.githubusercontent.com/46669902/53300540-bc68fb00-3870-11e9-9d26-55fee9399f7b.PNG)

 If i just test authentication and not build the configuration, authentication succeeds. But I cannot save data to cloud as savedgames is not enabled and I have to build a configuration for it resulting above failure.
The bool "Success" of line 85 returns true in this case.
The code is this:
![send2](https://user-images.githubusercontent.com/46669902/53300544-d0146180-3870-11e9-8c73-0294c3c3c50e.PNG)

Ive enabled saved games in google play console too and cleared the cache of google play store app in my test device as mentioned in another issue, but it does not seem to be working!
Thank You!

**Comment by sptkjs** [comment]
I have same issue too.
Authentication fails when PlayGamesClientConfiguration with EnableSaveGames() is built- Unity 2018 3.6f1 and playgames api v 0.9.61.

**Comment by 0c0de** [comment]
It's because cloud savegames, it's a little bit bugged

**Comment by olehkuznetsov** [comment]
Should be already fixed server side. Try again, please.
