### ISSUE TITLE
Op: SIGN_IN status: ERROR_NOT_AUTHORIZED for accounts outisde testers list

### ISSUE THREAD

**Issue by elvismd** [playgameservices/play-games-plugin-for-unity#2472]
Hi, I'm facing a problem with login on my app, I'm NOT using Google Play App Signing feature of Google Play Console, i'm signing it with the keystore i created in unity, and the linked apps also has the same fingerprint as the keystore I already checked it, but the ERROR_NOT_AUTHORIZED happens ONLY with accounts that ARE NOT in the alpha/internal test list of testers, so if the account is on the list of testers it can make login without errors, but if it isnt, this error happens... any idea of what it is?

**Comment by olehkuznetsov** [comment]
Have you publish changes in Play console?

**Comment by elvismd** [comment]
Yes, it is published, configured, etc

**Comment by olehkuznetsov** [comment]
Do you call EnableSavedGames() for PlayGamesClientConfiguration.Builder()?
There is a known issue for EnableSavedGames and new projects.

**Comment by elvismd** [comment]
No, I already noticed that, but no we dont use EnableSavedGames

**Comment by olehkuznetsov** [comment]
Can you provide me with package name or APP_ID, please?

**Comment by elvismd** [comment]
package name is br.com.flux.oswaldo, i'm not sure it is available in all countries

**Comment by olehkuznetsov** [comment]
It doesn't look to me as published in  Game Services Play Console.
Go to Play Console->Game Services->Your Game->Publishing and check if you have some unpublished changes, please.

**Comment by elvismd** [comment]
So, I'm a developer that participates in the project, TO ME it doenst look as published in game services console as well, but one of the admin of the account says its because i dont have the credentials to see, but it is published (look picture attached)
![afafs](https://user-images.githubusercontent.com/9807602/53504202-46db7580-3a90-11e9-83d3-270037aca345.PNG)

**Comment by elvismd** [comment]
how do you know isnt published? where can I find it (besides the console) ?

**Comment by olehkuznetsov** [comment]
I see some changes marked as a draft in the internal admin console.

**Comment by elvismd** [comment]
I understand, but how do you know not being member of the project in the console?

**Comment by olehkuznetsov** [comment]
Because I'm a member of Play Games services team and used internal admin console to help you figure out the issue.

**Comment by elvismd** [comment]
Oh i see! Thank you! I will report to my team, and check if there are drafts there yet, but is thats the case, that would explain why only people allowed on internal tests and alpha tests can login?

**Comment by olehkuznetsov** [comment]
Yes, because draft changes are available only to testers. Linked app change is currently in draft state too. And linked app information is required for sign-in.

**Comment by elvismd** [comment]
I will check this out and test and will go back here to say if it worked or not, thank you very much for your attention!

**Comment by vaibhavgpt-google** [comment]
It seems like this issue is resolved. As there are no follow ups, we are closing this issue.
Thanks
