### ISSUE TITLE
GetAnotherServerAuthCode email scope not granted

### ISSUE THREAD

**Issue by jgersindemir** [playgameservices/play-games-plugin-for-unity#2473]
First of all we are using authCode for Server side verification.
When I call "PlayGamesPlatform.Instance.Authenticate" function, "https://www.googleapis.com/auth/userinfo.email" scope is granted and  I can get "email" from Server side using authcode . 

After I call "PlayGamesPlatform.Instance.GetAnotherServerAuthCode" , "https://www.googleapis.com/auth/userinfo.email" scope is not granted. and email is "null" . I think GetAnotherServerAuthCode is not using PlayGamesClientConfiguration correctly.

`PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
                    .RequestEmail()
                    .RequestServerAuthCode(false)
                    .RequestIdToken()
                    .AddOauthScope("https://www.googleapis.com/auth/userinfo.profile")
                    .Build();`

Google Play Game Service v: 0.9.61
Unity v. : 2018.2.20f1

**Comment by olehkuznetsov** [comment]
Should be fixed in v0.9.62
