### ISSUE TITLE
Google Play Games 2019.02.8704 throws exception when trying to invoke recording overlay.

### ISSUE THREAD

**Issue by JimmyDeemo** [playgameservices/play-games-plugin-for-unity#2480]
I have found that a new version of Google Play Games app causes a crash when you try to call `PlayGamesPlatform.Instance.Video.ShowCaptureOverlay()` to show video recording overlay.

Here is the exception;

> 03-04 13:19:22.306 29757 29757 E AndroidRuntime: FATAL EXCEPTION: main
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime: Process: com.google.android.play.games.ui, PID: 29757
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime: android.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class android.support.design.button.MaterialButton
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class android.support.design.button.MaterialButton
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at nqm.a(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):1)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at nqr.c(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):7)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at llx.c(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):61)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at nqj.a(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):1)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at pz.b(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):7)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at qp.a(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):398)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at qp.c(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):26)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at qp.a(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):200)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at pt.e(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):46)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at qp.a(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):125)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at qp.a(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):76)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at qp.h(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):7)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at qq.run(Unknown Source:2)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:789)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:98)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6938)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at il.a(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):17)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at il.b(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):9)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at il.a(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):11)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at android.support.design.button.MaterialButton.<init>(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):5)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        at android.support.design.button.MaterialButton.<init>(:com.google.android.play.games@87040040@2019.02.8704 (234222928.234222928-000400):2)
> 03-04 13:19:22.306 29757 29757 E AndroidRuntime:        ... 29 more

This happens when using 2019.02.8704 of the Play Games app, it does *not* happen with previous version 2019.01.8450.

I found the following information about the error; https://stackoverflow.com/questions/51841451/android-support-design-button-materialbutton-throws-inflateexception. But this seems to talk about the style for the Play Games app itself, is there anyway to make our project, that implements the Play Game Plugins, compatible with this version of the Play Games app?

Integrated plugin versinon; v0.9.62.
Unity version: 2017.4.18f1 LTS

**Comment by olehkuznetsov** [comment]
It is an issue in Play Games app and should be fixed soon in next Play Games App release candidate.

**Comment by JimmyDeemo** [comment]
Thanks for the update @olehkuznetsov. Please can you tell me if there is a public facing issue report for tracking purposes?
