### ISSUE TITLE
Can't authenticate (No cloud save games)

### ISSUE THREAD

**Issue by PITR-DEV** [playgameservices/play-games-plugin-for-unity#2494]
Hi,
I have an issue with play games services. I can't authenticate no matter what I do.
```PlayGamesClientConfiguration conf = new PlayGamesClientConfiguration.Builder().Build();
PlayGamesPlatform.InitializeInstance(conf);
PlayGamesPlatform.DebugLogEnabled = true;
PlayGamesPlatform.Activate();

Debug.Log("Authenticating...");
Social.localUser.Authenticate((bool success) =>
{
    if (success)
    {
        Debug.Log("Welcome " + Social.localUser.userName);
    }
    else
    {
        Debug.Log("Authentication failed.");
    }
});
```
Please keep in mind that it doesn't work with a build signed by the play store and with a directly installed apk and I have both of the sha1 added as linked apps.
If I run this code snipped as a apk with unity development mode enabled the google play games popup will appear and shortly disappear leaving me with a "Authentication failed." message but when I use a apk without the developer mode nothing happens and I get an instant "Authentication failed." message.
I've checked if the sha1 codes are correct many times, I'm on the testers list and the service is published.
Can somebody help me please?

**Comment by julianosaless** [comment]
@Pitrr, You verified the log ?

Do you can use Android Studio + Debug APK to get all application log :)

The errors more common about authorization is when you do not insert SHA1, do you need to use the same key of your app.

![SHA1](https://user-images.githubusercontent.com/1616798/54073887-13a49d80-426b-11e9-948e-97494a464527.PNG)

**How to get your SHA1**

https://stackoverflow.com/questions/11331469/how-do-i-find-out-which-keystore-was-used-to-sign-an-app

Another error is when you not defined developer to test your game when your game was not released:
![test](https://user-images.githubusercontent.com/1616798/54073918-60887400-426b-11e9-8381-672019e4ce56.PNG)

**Comment by Pitrr** [comment]
@julianosaless I did check the logs few days ago and they didn't say anything that could be the cause for the error. and yes my keys are proper and I'm a tester

**Comment by DorianMazur** [comment]
i have the same issue

**Comment by Pitrr** [comment]
I still can't fix it

**Comment by julianosaless** [comment]
@Pitrr  and @DorianMazur I am using this configuration bellow, for me is working well.

![config](https://user-images.githubusercontent.com/1616798/54637204-d4dec680-4a66-11e9-9f93-96a2d0b80019.PNG)

**Comment by Pitrr** [comment]
@julianosaless Compiling that part will result in what I have

**Comment by DorianMazur** [comment]
I had deleted "Library" and that helped

**Comment by Pitrr** [comment]
@DorianMazur Didn't fix it for me

**Comment by frungillo** [comment]
Finally I've fix it! I had same problem here. After millions tries, I go on "console.developers.google.com" and edited the OAuth client generated from games console, changing SHA-1 fingerprint present with the discovered one from keytools command as described in the tool.
![Schermata 2019-11-23 alle 12 34 02](https://user-images.githubusercontent.com/4841028/69478095-9916b080-0dee-11ea-9d65-d8c43916abd1.png)

**Comment by frungillo** [comment]
` void SignIn()
    {
        Social.localUser.Authenticate(success => {
            showToast("Stato connessione:" + success.ToString(), 2); //this alway return false
            Debug.Log("Connesso a PLAY");
            PlayGamesPlatform.Instance.Authenticate(suc => {
                showToast("Stato Play auth:" + suc.ToString(), 2); //THIS RETURN TRUE!!!!!! I WIN 👍 

            });
        });
    }`
