### ISSUE TITLE
Turn based multiplayer - always my turn

### ISSUE THREAD

**Issue by rafacsordas** [playgameservices/play-games-plugin-for-unity#2503]
I've implemented TBM in my game but it doesn't change whose turn it is. I start the match, persist the game data for the first player and pass the turn with null string for the next participant using taketurn. The other player receives the data and is able to ready it. At this moment a call for turnstatus returns MyTurn for player two. But also a call turnstatus in player's one device is returning MyTurn. I keep an UI text on the screen just to show me whose turn it is. I used the Update() function to keep checking the status and write a text on the UI ("my turn", if it gets MyTurn response and "their turn" if it returns something else). In order to make this check I have a TurnBasedMatch variable globalMatch that I assign when the match starts if creatematch is successful. I also check on Update() if globalMatch is not null before checking the turn status. Another thing that I tried was checking the turn inside the taketurn() callback. If the turn is passed successfully then I check turnstatus but it still MyTurn.

**Comment by kaninhot004** [comment]
Use real time maybe easier to scripts. (Create you own turn scripts)

First I think turn based in Google is type that turn based game should be used but not. It's take long time to response.

**Comment by rafacsordas** [comment]
Thanks for replying! I have thought about it, but my game will be for 3 to 4 players. I should create some sort of server-client with one of the players being the server and sending the order of play to the others, however all the players join the game together. I can't figure a good way of deciding who will be the server. Do you have any idea?

**Comment by kaninhot004** [comment]
```
 public string GetParticipantHostData()
    {
        var sum = PlayGamesPlatform.Instance.RealTime.GetConnectedParticipants();
        if (sum.Count > 0)
            return sum[0].ParticipantId;
        else
            return null;
    }
```

This will be host ( I already test on [this ](https://play.google.com/store/apps/details?id=com.KTGames.ZARTs))

**Comment by rafacsordas** [comment]
I'll try that and let you know. But does it return the same participant in all devices? Also does the array that is returned will have the same order in all devices? Just asking because if that works then I can also use this to make the order of play

**Comment by kaninhot004** [comment]
As I said I already test it on my apps that live.

**Comment by rafacsordas** [comment]
Okay thanks for the help!

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
