### ISSUE TITLE
Support for non-mobile platforms

### ISSUE THREAD

**Issue by salmonmoose** [playgameservices/play-games-plugin-for-unity#251]
Is it possible to extend support to desktop / web releases?

It would be nice to be able to use the same backend for all editions.

**Comment by claywilkinson** [comment]
Tracking the enhancement internally as 19127787

**Comment by MofoMan2000** [comment]
Ideally this could also enable support for Android devices that don't use Google Play Services (like the OUYA).

**Comment by claywilkinson** [comment]
Unfortunately, I don't think other platforms besides Android will be supported in the foreseeable future.
