### ISSUE TITLE
Inviting a player when a disconnection on realtime game

### ISSUE THREAD

**Issue by bbekec** [playgameservices/play-games-plugin-for-unity#2513]
Hello, I am developing an online card game. There are some problems with disconnection.
The game has actively 4 players. If one changes screen then player disconnects. I couldnt find any solution for this. So do i have chance to create a lobby which can be seen by players are not in the current game? Can any player join the game later if one disconnects?
Additional Question, 
In this condition, can i send an invitation to a single player (among the participants) to continue the game? 
Thanks

**Comment by kaninhot004** [comment]
OnParticipantsLeft(){
//one changes screen then player disconnects   >> Will run this scripts in 3 players left.
}

//

Can any player join the game later if one disconnects?

If this can be that should be great. I didn't try it yet. (That will create the re-connect after screen changes)

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
