### ISSUE TITLE
Play Games Services aren't working when building Gradle

### ISSUE THREAD

**Issue by Jorge255Games** [playgameservices/play-games-plugin-for-unity#2516]
I don't know why, but when I build my project in Gradle build suddenly Play Games Services aren't working. With apk I haven't any problems. I'm using Unity 2018.3.8, and Play Games Services version is 0.9.62

**Comment by kaninhot004** [comment]
Paste error log for more infomation.

**Comment by Jorge255Games** [comment]
I don't get any error log. It is built properly, but when I test it on my phone it just doesn't work. I guess I should connect my phone with Unity to be able to see what error doest it get right? I tried, but it doesn't connect

**Comment by kaninhot004** [comment]
You can see log of your phone by connect USB and enable debug mode of phone.

Then go to Android Monitor that will show log.

**Comment by Jorge255Games** [comment]
I finally solved it, thanks a lot!! I found that in Minify/Release options, I had actived Proguard instead of None. That was the reason of the issue. Thanks again. Cheers.
