### ISSUE TITLE
Google Play Games service "Queries per 100 seconds per user" quota hit

### ISSUE THREAD

**Issue by Tanek81** [playgameservices/play-games-plugin-for-unity#2519]
Hi,
after a huge increase in our daily players, we started seeing reports of players who are shown the GPG Login popup but are unable to log on GPG in our game.

While investigating this issue, we saw on our Google Cloud API dashboard that it seems we have hit the 500 limit for the "Queries per 100 seconds per user". It seems that the most called API are games.achievementDefinitions.list and games.achievements.list , calls that of course masked inside the GPG Unity Plugin (version 0.9.50). We double checked our code and we surely don't call the list of the achievement so many times, from our side it is called only linked with a "showAchievementsUI" request.

Is it possible that these calls are connected with caching (or not caching) from your plugin?
Or that these are connected with other calls? For example games.achievements.unlock or games.achievements.updateMultiple which of course we call more often in the game but that are not an issue looking at our dashboard data (there are a lot less calls to these methods).

An update to the latest version of the plugin is scheduled, it would be helpful to know if you had issues on this topic, so that we can consider it as an higher priority.

Thanks.

**Comment by Tanek81** [comment]
Small addendum: is there any way in the plugin to enforce a limit on the user? This is the GPG documentation: https://cloud.google.com/apis/docs/capping-api-usage#limiting_requests_per_second_per_user

**Comment by olehkuznetsov** [comment]
Probably you call achievement increment operation a lot. Can you check if you can call it not so frequently, please? 

Plan to will fix this in v0.9.63 release.

**Comment by Tanek81** [comment]
Hi @olehkuznetsov , first of all thank you for your support.

Do you mean `PlayGamesPlatform.Instance.IncrementAchievement` ?
We use it on incremental achievements, we group increments for each in-game week which, depending on the player level, can be called every 2-5 minutes, repeated for each incremental achievement (10 in total). We also check and exclude <=0 steps (but checking the code your plugin does it too) and automatically check and exclude already unlocked achievements, so the total gets smaller early in the game as a couple of them are easy to unlock.

It does not seem a huge number of calls, with these numbers and double checking the code I see no points of optimization for our code right now.
You mention a fix, does that mean that there is a bug on this?

I also requested an increase for the quota to the Google Cloud API team (through their form) before knowing there could be an issue with the plugin (but mentioning that we are using it, as we are on Unity), is there any possibility of a "short circuit" with the Google Cloud API team for, even temporarily,  raising the quota as this it's happening in production and we are starting to see bad reviews because of it?
Thank you.

**Comment by olehkuznetsov** [comment]
Per-user quota for your project is increased.

Currently plugin allows to take information about achievement synchronously and to achieve this it updates achievement information after any achievement modification call. I plan to remove synchronous achievement get method and this allows to not call extra updates.

**Comment by Tanek81** [comment]
Ok that is surely wise.
Thank you for your help and for the speedy quota increase, I'll contact the players that reported this issue to see if it's now solved.
