### ISSUE TITLE
Multiplayer Waiting room UI issue

### ISSUE THREAD

**Issue by BenQ12345** [playgameservices/play-games-plugin-for-unity#2522]
Hi,
   I am developing the multiplayer game in flash using the game Services. If I click the quick game function it is showing Player UI, for me no need to display a Player UI window or customize window. please help me with this issue.

startQuickGame()
function startQuickGame():void
{
	var minAutoMatch:int = 1;
	var maxAutoMatch:int = 1;
	var exclusiveBitMask:int = 0;
	var variant:int = -1;
	
	Games.realtime.createRoom(minAutoMatch, maxAutoMatch, exclusiveBitMask, variant, null);
}

**Comment by olehkuznetsov** [comment]
Does it shows waiting room UI?

**Comment by BenQ12345** [comment]
yes, it is showing the Waiting room UI panel without showing UI window want to search for the player

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
