### ISSUE TITLE
Google Play sign-in account in Unity Editor

### ISSUE THREAD

**Issue by bbekec** [playgameservices/play-games-plugin-for-unity#2536]
Hello, I m using GPS in my game. Is there any option to sign in GPS account in Unity Editor? So this way, I can test the game by running in the editor. Currently, all the time I have to build APK file, install on emulator then test. It takes too long time to do like this and i cant get debug logs. Any Idea? thanks.

**Comment by Noah1911** [comment]
#2434

No, currently there is no way to test it in editor. Hovewer you can somehow automatize it to automatically build and upload to emulator which speeds debugging process (maybe this can be done if you try "Build and run" in Unity and let ADB pick your emulated device or real device if connected). As for debugging process (getting debug logs) ADB logcat can see your debug log in emulated device and on real device if connected too.

**Comment by bbekec** [comment]
Thanks for the reply, I made a research for your suggestion. Succesfully connected real device and run ADB but ADB debug gets all the logs of  phone not just the game I work on. Thanks for your suggestion.
