### ISSUE TITLE
Authentication returns nothing

### ISSUE THREAD

**Issue by SarahAlazab** [playgameservices/play-games-plugin-for-unity#254]
Social.localUser.Authenticate Never return true (or false for that matter). I have the latest update of the plugin (0.9.07). I tried everything please help.

if(GUI.Button(new Rect (50, 20, 100, 50), "Sign In"))
		{
			// recommended for debugging:
			PlayGamesPlatform.DebugLogEnabled = true;
			
			// Activate the Google Play Games platform
			PlayGamesPlatform.Activate();
			
			// authenticate user:
			Social.localUser.Authenticate((bool success) => {
				// handle success or failure
				if(success)
				{
					userName =  Social.localUser.userName;
					Debug.Log("True");
				}
				else
				{
					userName = "unavailable";
				}
			});
		}

GUI.TextArea(new Rect (60, 80, 200, 70), userName, 100);

**Comment by claywilkinson** [comment]
Can you check the log for any interesting messages ?
