### ISSUE TITLE
Social.localUser.Authenticate always returns false

### ISSUE THREAD

**Issue by AndersonChilling** [playgameservices/play-games-plugin-for-unity#2540]
1. My game was working fine and testers (including myself) could sign in to Play Games in the app.
2. The game was removed from Play Store due to a policy violation (Issue: Violation of Usage of Android Advertising ID policy and section 4.8 of the Developer Distribution Agreement).
3. Shortly after, existing users (testers) could no longer sign in to Play Games in the app.
4. A privacy policy for the game was made and submitted in Play Store and also placed in the app and a new apk was uploaded to Play Store.
5. The game is once again published (closed alpha).
6. Users (testers) still can not sign in to Play Games in the app (this is the problem). Social.localUser.Authenticate((bool success) returns false every time even though it worked before the app was removed. Also an old installation on one of my test devices that was working before the whole app removal thing has stopped working too.

Im stuck now and don't know what to do. From another issue here on GitHub (https://github.com/playgameservices/play-games-plugin-for-unity/issues/2429) I get the feeling that it is a Google bug. Is this still the case and should I just wait and the issue will be resolved?

Any help is much appreciated.

**Comment by olehkuznetsov** [comment]
check #2534 for a current solution.
