### ISSUE TITLE
Social.ReportScore or ShowLeaderboardUI is not working

### ISSUE THREAD

**Issue by tam334** [playgameservices/play-games-plugin-for-unity#2542]
Hi,
Social.ReportScore is not working.
When app show LeaderboardUI after report score, score is not listed.

My Play Games Service settings,
・8 leaderboards.
・Enable tamper protection is off.
・Saved game is off.
・No events and achievements.
・Enable anti-piracy is off.
・Status is Ready to publish (because I will delete tester's scores)
・App is now internal tracking.
・Tester's mail address is added to list, and Testers on track 'internal' for (App name) is checked.

App is installed from google play internal channel.

Minimum API Level is 4.1, and Target API Level is 8.0.

Logcat output is,

04-17 18:50:35.102 2140-2152/? I/Unity:  [Play Games Plugin DLL] 04/17/19 18:50:35 +09:00 DEBUG: ReportScore: score=80, board=(Id)
                                        UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
                                        UnityEngine.Logger:Log(LogType, Object)
                                        GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
                                         
                                        (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
04-17 18:50:35.112 2140-2152/? I/Unity:  [Play Games Plugin DLL] 04/17/19 18:50:35 +09:00 DEBUG: Native Submitting score: 80 for lb (Id) with metadata: 
                                        UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
                                        UnityEngine.Logger:Log(LogType, Object)
                                        GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
                                         
                                        (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
04-17 18:50:35.132 2140-2152/? I/Unity:  [Play Games Plugin DLL] 04/17/19 18:50:35 +09:00 DEBUG: Invoking user callback on game thread
                                        UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
                                        UnityEngine.Logger:Log(LogType, Object)
                                        GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
                                         
                                        (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
04-17 18:50:35.162 2140-2152/? I/Unity:  [Play Games Plugin DLL] 04/17/19 18:50:35 +09:00 DEBUG: LoadScores, board=GooglePlayGames.PlayGamesLeaderboard callback is System.Action`1[System.Boolean]
                                        UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
                                        UnityEngine.Logger:Log(LogType, Object)
                                        GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()

04-17 19:33:41.572 1503-2497/? W/AppOps: Bad call: specified package com.google.android.play.games under uid 10265 but it is really 10171

Initialization codes,
``
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();
PlayGamesPlatform.InitializeInstance(config);
PlayGamesPlatform.DebugLogEnabled = true;
PlayGamesPlatform.Activate();
RankingWrapper.Authenticate ((bool success) => {
			mLoginEnded = true;
			mLoginSuccess = success;
		});

...
public class RankingWrapper{
	public static void Authenticate(Action<bool> callback)
	{
		#if UNITY_EDITOR
		callback(true);
		#else
		Social.localUser.Authenticate(callback);
		#endif
	}
``

And report score codes,
mLeaderBoardIds = new string[]{
			GPGSIds.leaderboard_scorestage1,
			GPGSIds.leaderboard_scorestage2,
			GPGSIds.leaderboard_scorestage3,
			GPGSIds.leaderboard_scorestage4,
			GPGSIds.leaderboard_scorestage5,
			GPGSIds.leaderboard_scorestage6,
			GPGSIds.leaderboard_scorestage7,
			GPGSIds.leaderboard_scorestage8,
		};
...
mReportScoreEnded = false;
		string id;
		#if UNITY_IOS
		id = "ScoreStage" + stage;
		#else
		id = mLeaderBoardIds[stage - 1];
		#endif
		RankingWrapper.ReportScore ((long)score, id,
			(bool success) => {
				mReportScoreEnded = true;
				mReportScoreSuccess = success; // success is true
			});
...
public class RankingWrapper {
...
	public static void ReportScore(long score, string boardID, Action<bool> callback)
	{
		#if UNITY_EDITOR
		callback(true);
		#else
		Social.ReportScore (score, boardID, callback);
		#endif
	}

Regards,

**Comment by tam334** [comment]
Unity version is 2017.4.12f1 Personal.

**Comment by profmicrop** [comment]
I have same problem (Social.ReportScore is not working). it is not working. Help please

**Comment by igormoreira96** [comment]
Hello. I have the same problem. The sign in and achievements are working fine. I can see the leaderboard but I can't post scores. I'm using Unity 2018.3.11f1.

**Comment by DiDiOrange** [comment]
Hello. I have the same problem. Unity 2018.2.13f1 (64-bit) 
Social.ReportScore is not working

I broke my mind looking for a reason, but this topic looks very fresh

Please, Help...

**Comment by tam334** [comment]
After that, I viewed Leaderboards on google play console, "scores" column was 1. So, this problem may be not Social.ReportScore but Social.ShowLeaderboards and PlayGamesLeaderboard.LoadScore().

**Comment by darkcodes777** [comment]
Hello, i have the same problem. Unity 2019.1.0f2 Personal (64 bit)
Latest plugin version
Login does work but game doesn't show the google play games "welcome back" badge.

**Comment by DiDiOrange** [comment]
> After that, I viewed Leaderboards on google play console, "scores" column was 1. So, this problem may be not Social.ReportScore but Social.ShowLeaderboards and PlayGamesLeaderboard.LoadScore().

Hello, you pushed me to the solution of the problem
as I have <"scores" column with 1> too
I have found option in google games, something like <Show my scores to everybody>, which was tured off in my accout... 
I'm pissed of and happy...

**Comment by tam334** [comment]
I'm sorry for the trouble, my test device's Google Play Games account setting, "Let others see your game activity", was also turned off...
When it is turned on, my test device's score is available by PlayGamesLearboard.LoadScore().

**Comment by igormoreira96** [comment]
Hello. It works... Thank you!

**Comment by MrKnubbles** [comment]
I can't believe all I had to do was allow my own scores to be visible. I feel so foolish...
