### ISSUE TITLE
IOS Build on PC with GPGS

### ISSUE THREAD

**Issue by bbekec** [playgameservices/play-games-plugin-for-unity#2544]
Hello, I am using GPGS on PC and developing a realtime game. I can build the game for PC there is no problem. 
So, I dont want to buy a MAC just for building the game for IOS. So I made a research and there are some options to able to build the game without buying a MAC. One of these options is a plug-in can build games for IOS and i think to try it but I have a doupt that I am getting errors If I switch unity platform to IOS in unity as below.

"The type or namespace name 'RealTimeMultiplayerListener' could not be found (are you missing a using directive or an assembly reference?)"

"The type or namespace name 'Participant' could not be found (are you missing a using directive or an assembly reference?)"

These errors probably prevent to build.

So can I find a solution for these errors before compiling with the plug-in for IOS?
Thanks.

**Comment by Noah1911** [comment]
Unfortunately IOS support for GPGS has been deprecated and bindings removed ("Google Play games services for iOS is deprecated, and is not likely to function as expected. Do not use Google Play games services for iOS in new apps."), to fix IOS build (but without GPGS) use #ifdefs.

**Comment by bbekec** [comment]
Thanks for the reply. It is not good. There are lots of IOS users and I cannot puplish the game for them.

**Comment by ozdemir08** [comment]
Thanks for your question. As mentioned, GPGS does not support IOS. You can use Game Center to provide similar functions on IOS. Also, Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
