### ISSUE TITLE
Showing Number of Total Participants

### ISSUE THREAD

**Issue by bbekec** [playgameservices/play-games-plugin-for-unity#2546]
Hello, I want to get total number of players who connected to GPS by my game. I couldnt find any source for this. I want this because I will inform players about how many players are online at the moment. Even, It is better to get their display names or their playgames ids so i can give the player a chance to choose other players and then create a room together. Is this possible?
Thanks

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
