### ISSUE TITLE
Saved games and invitations problem.

### ISSUE THREAD

**Issue by jaimecasalsc** [playgameservices/play-games-plugin-for-unity#2547]
Hi all! I've been stuck with this for more than two weeks with no avail. I'm developing a game that uses this plugin and I had no problems for two months. Sign-in, Leaderboards, Multiplayer, Savedgames and Invitations. I use those things. And well, this is my first time with the plugin I know, but while slowly, I was able to make everything work, and at some point, everything was working at the same time.

But like three weeks ago, (I believe I made no changes in that part of the code at all), saved games stopped working, and later (like two days) I noticed invitations neither, and then signing-in. 

I was able to recover signing-in (updating the plugin helped), but saved games or invitations... 

I'm having an exception trying to open the save game that says that I have not enabled saved games in the builder, but this is how I'm invoking the builder:

```
    private void Initialization()
    {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
           .EnableSavedGames()
           .WithInvitationDelegate(OnInvitationReceived)
           .Build();

        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.DebugLogEnabled = debugLogEnabled;
        PlayGamesPlatform.Activate();

        DebugUI.instance.Log("GooglePlay activation");
        DebugUI.instance.Log("Trying silent authentication");
        PlayGamesPlatform.Instance.Authenticate(SignInCallback, true);
    }
```
And yes, I've it activated in the Google Play Console, and still does:

![2019-04-24 12_31_59-Window](https://user-images.githubusercontent.com/35527183/56653054-1e858700-668d-11e9-9ade-1f9366cd3106.png)

About the APIs statuses:

![2019-04-24 12_33_42-Window2](https://user-images.githubusercontent.com/35527183/56653218-7d4b0080-668d-11e9-96f7-0c5a43712824.png)

About the open saved game code... this is the part:

```
    private void SaveGameRead(string filename)
    {
        DebugUI.instance.Log("SaveGameRead(" + filename + ")");
        try
        {
            ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame;
            savedGameClient.OpenWithAutomaticConflictResolution(
                filename,
                DataSource.ReadCacheOrNetwork,
                ConflictResolutionStrategy.UseLongestPlaytime,
                SaveGameReadCallback);
        }
        catch (Exception ex)
        {
            DebugUI.instance.Log("SaveGameRead exception:\n" + ex.Message);
        }
    }
```
Yep, pretty generic stuff, I tried to use the instructions by the letter (more than less I hope).

And invitations are not working anymore either, as I commented before... but I'm even unable to capture exceptions or problems... simply, they are not send/received anymore (I even use the default Google GUI for invitations). No idea if they are related to the saved game problem, but removing the '.EnableSavedGames()' when setting up the builder doesn't help.

I tried to update the plugin, twice (to v0.96.2 and to v0.96.3), even with the recommendation of removing it completely, restarting Unity, and resintalling the plugin as new. And yes, apply the setup from the Tool bar (Window->Google Play Games->Setup->Android setup...)

![2019-04-24 12_43_11-Google Play Games - Android Configuration2](https://user-images.githubusercontent.com/35527183/56653804-c9e30b80-668e-11e9-9629-4b83c90bfdb8.png)

But my game, published as alpha for now, only is able to sign-in/authenticate, use the leaderboards (reading leaderboards and sending new scores working good) and the real time multiplayer (random matching and messaging working good).

As I said, everything from the above was working last month. Maybe there is something I had to do from an update from Google or from the plugin, or I just started to do things completely wrong. I'm really sorry if all this is not helpful at all to find a solution, or the problem is extremely obvious, but I'm unable to find a solution for it.  

Thanks to anyone willing to help and for your time.

Best regards,
Jaime.

**Comment by olehkuznetsov** [comment]
Can you provide you app_id, please?

**Comment by jaimecasalsc** [comment]
Hello, thanks for the reply.

I think that you refer to the number on the Google Console url, 

4973055904618337265

**Comment by olehkuznetsov** [comment]
You can find app id in Google Play Console->Game Services->Your project. You will see it just under the title.

**Comment by jaimecasalsc** [comment]
Ok, then this is the one:

265664246652

**Comment by olehkuznetsov** [comment]
It seems you've activated Save Games in Google Play Console, but haven't published this change there.

**Comment by jaimecasalsc** [comment]
The thing is that all changes haven published for some time.

![2019-04-29 16_44_24-Publishing - Cube_Destroyer - Google Play Console](https://user-images.githubusercontent.com/35527183/56904342-5aaa5480-6a9e-11e9-9c2e-05e4c0498c8f.png)

And I have nothing on test right now.

The only thing special I could comment is that at some moment I removed some leaderboards and created new ones, and I pasted the Android Resources in the Setup window too as I suppose it must be done. 

I cannot chage the status of the SavedGame service (turn it off to then try to turn it on), so in a desperate move I changed the description in the 'Game Details' section, and saved changes... I don't believe it may help, knowing that that change itits not modifying services availability, but I don't know what to do at the moment.

May the 'Unpublish your game' action be of any help? Can then be restored by re-publishing?
Thanks in advance.

**Comment by jaimecasalsc** [comment]
Tried to unpublish and republish these days. No luck with that. No changes in the behaviour I commented in the first post. I can sign-in and play in realtime with random matching. Leaderboards working too. But saved games and invitations aren't working yet (the Google GUI for invitations is launched without problems though).

**Comment by olehkuznetsov** [comment]
Can you add test.oneup180@gmail.com as a tester to your app, please?

**Comment by jaimecasalsc** [comment]
There you go:

[https://play.google.com/apps/testing/com.Cimetia.Cube_Destroyer](https://play.google.com/apps/testing/com.Cimetia.Cube_Destroyer
)

Hope it helps.

I can always try to revert to a previous version of the plugin, for testing at least. But I'll wait until you can check this one first.

Thanks for your time.

**Comment by olehkuznetsov** [comment]
How can I save/continue game?

**Comment by olehkuznetsov** [comment]
In current version it seems 'save games' scope is not added during sign-in flow.

**Comment by jaimecasalsc** [comment]
> How can I save/continue game?

Saved games are only used to store player's personal scores. Aside of scores sent to leaderboards. There is no 'continue game' feature at the moment.


> In current version it seems 'save games' scope is not added during sign-in flow.

I'll recheck all the code around it anyway. Yes, I find strange that, now, even setting saved games when declaring the builder, all the exceptions I'm getting is that I've not enabled it. 

In few words, I set save games in builder configuration and when signing-in I try to open/load the stored saved game (in case of no finding one, works with a new one). In the actual situation, I'm storing player scores correctly (can be seen working) using a JSON in the background, that keeps updated with the savedgames feature, well, or kept, a month ago.  

What I find even more strange is the Invitations issue. I'm able to set it in the builder configuration, and I'm able to launch the GooglePlay Invitation UI (with no exceptions), but invitations are received no more.

I'll recheck again anyway. Probably I'll try a plugin downgrade too.
Thanks in any case.

PS. May be a solution to remove and make a complete new game service? Starting anew?

**Comment by olehkuznetsov** [comment]
>PS. May be a solution to remove and make a complete new game service? Starting anew?
For save games it definitely wouldn't help. It seems you have some code which doesn't set 

For multiplayer - can you add test.oneup172@gmail.com as a tester too, please?

**Comment by olehkuznetsov** [comment]
I was able to start one game with invitation. Are you sure your invitation listener is set correctly?

**Comment by olehkuznetsov** [comment]
Are you initializing PlayGamesClientConfiguration.Builder with .WithInvitationDelegate?

**Comment by jaimecasalsc** [comment]
> Are you initializing PlayGamesClientConfiguration.Builder with .WithInvitationDelegate?

I think so. I've put the code I use for initializing in the first post.

```
    private void Initialization()
    {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
           .EnableSavedGames()
           .WithInvitationDelegate(OnInvitationReceived)
           .Build();

        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.DebugLogEnabled = debugLogEnabled;
        PlayGamesPlatform.Activate();

        DebugUI.instance.Log("GooglePlay activation");
        DebugUI.instance.Log("Trying silent authentication");
        PlayGamesPlatform.Instance.Authenticate(SignInCallback, true);
    }
```

The code I have to control entering invitations is pretty simple:

```
    public void OnInvitationReceived(Invitation invitation, bool shouldAutoAccept)
    {
        if (shouldAutoAccept)
        {
            incomingInvitation = invitation;
            GameManager.instance.modalWindows.ShowInvitationWindow();
        }
        else
        {
            incomingInvitation = invitation;
            if (GameManager.instance.playingGame)
            {
                DeclineInvitation();
            }
            else
            {
                GameManager.instance.modalWindows.ShowInvitationWindow();
            }
        }
    }
```
I store the invitation in a variable, and show a little screen depending of the auto accept parameter (The little screen is just little invitation info area with buttons for accepting or declining ).

Maybe I'm forgetting something... 


> I was able to start one game with invitation. Are you sure your invitation listener is set correctly?

Do you mean room initialization? The room is initialized from one end, yes... but in my case, the other player doesn't receive the invitation, or I cannot notice it anymore.

Just curiosity: How were you able to play the game using invitations when I'm unable at the moment?

 Is it possible that invitations sent time ago, while the app was not running can be stored somewhere and not allowing to make new ones until those are accepted/declined? (desperate thinking, I know) 

> For multiplayer - can you add [test.oneup172@gmail.com](mailto:test.oneup172@gmail.com) as a tester too, please?

Done

Thanks for your time.

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
