### ISSUE TITLE
GPS Send Invitation and Custom Waiting Room

### ISSUE THREAD

**Issue by bbekec** [playgameservices/play-games-plugin-for-unity#2548]
Hello, I am developing a realtime card game by using GPS. I completed the game and publish on PlayStore with critical problems caused by Google Play Services. One of these problems is inviting players.
At first and currently, I use the method "CreateWithInvitationScreen" which is presented by Google. 
It's functionality is good but not enough. I need more specific Invitation room. 
So, I got the players google ID and saved them to SQL by using UnityWebRequest. Now I have a list of players who download my game with their GoogleIDs. Then, I prepared a custom Invitation room and get player id's from SQL. It works perfectly but the problem is, Invitation method of GPS. I couldnt find a command that will send Invitation to the other selected players. So please advice me a way to solve this problem. Thanks

**Comment by olehkuznetsov** [comment]
We have such functionality in Java API but not in the Unity plugin yet.

**Comment by bbekec** [comment]
Hello, thanks for the reply.
Is there any way to reach the java function? So I believe that I can edit the java function and link each other maybe?

**Comment by olehkuznetsov** [comment]
Currently it would require a lot of work to do that. We are working on refactored plugin version which would do almost all required work for this task. But multiplayer is not yet implemented there. It will take around two weeks to have a new plugin version which you will be able to  modify to add required functionality.

**Comment by bbekec** [comment]
Thanks, this is very good news. 2 weeks is not too long. I will be waiting for it. 
This is irrelevant in this subject i know but I hope you can find a solution to disconnection when a player send the app to background.  This is also a very big problem. While 4 players are in a room if one changes screen, whole game and users disconnect. Users remove my app from their device because of this situtation.
Thanks again.

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
