### ISSUE TITLE
 UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment

### ISSUE THREAD

**Issue by Junaid9768** [playgameservices/play-games-plugin-for-unity#2556]
04-30 17:43:24.556 23378 23395 W Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
04-30 17:43:24.556 23378 23395 W Unity   :
04-30 17:43:24.556 23378 23395 I Unity   :  [Play Games Plugin DLL] 04/30/19 17:43:24 +05:30 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
04-30 17:43:24.556 23378 23395 I Unity   :
04-30 17:43:24.556 23378 23395 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
04-30 17:43:24.556 23378 23395 I Unity   :
04-30 17:43:24.556 23378 23395 I Unity   :  [Play Games Plugin DLL] 04/30/19 17:43:24 +05:30 DEBUG: Creating platform-specific Play Games client.
04-30 17:43:24.556 23378 23395 I Unity   :
04-30 17:43:24.556 23378 23395 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
04-30 17:43:24.556 23378 23395 I Unity   :
04-30 17:43:24.556 23378 23395 I Unity   :  [Play Games Plugin DLL] 04/30/19 17:43:24 +05:30 DEBUG: Creating Android IPlayGamesClient Client
04-30 17:43:24.556 23378 23395 I Unity   :
04-30 17:43:24.556 23378 23395 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
04-30 17:43:24.556 23378 23395 I Unity   :
04-30 17:43:24.679 23378 23395 W Unity   : *** [Play Games Plugin DLL] 04/30/19 17:43:24 +05:30 ERROR: Exception launching token request: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
04-30 17:43:24.679 23378 23395 W Unity   :
04-30 17:43:24.679 23378 23395 W Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
04-30 17:43:24.679 23378 23395 W Unity   :
04-30 17:43:24.679 23378 23395 W Unity   : *** [Play Games Plugin DLL] 04/30/19 17:43:24 +05:30 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
04-30 17:43:24.679 23378 23395 W Unity   : java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
04-30 17:43:24.679 23378 23395 W Unity   :      at java.lang.Class.classForName(Native Method)
04-30 17:43:24.679 23378 23395 W Unity   :      at java.lang.Class.forName(Class.java:453)
04-30 17:43:24.679 23378 23395 W Unity   :      at java.lang.Class.forName(Class.java:378)
04-30 17:43:24.679 23378 23395 W Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
04-30 17:43:24.679 23378 23395 W Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
04-30 17:43:24.679 23378 23395 W Unity   :      at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
04-30 17:43:24.679 23378 23395 W Unity   :      at android.os.MessageQueue.next(MessageQueue.java:394)
04-30 17:43:24.679 23378 23395 W Unity   :      at android.os.Looper.loop(Looper.java:159)
04-30 17:43:24.679 23378 23395 W Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
04-30 17:43:24.679 23378 23395 W Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.games.bridge.TokenFragment" on path: DexPathList[[zip file "/data/app/com.jPlay.DeathEdge-suWitvwrjL1ZfXQJ_g0j2A==/base.apk"],nativeLibraryDirectories=[/data/app/com.jPlay.DeathEdge-suWitvwrjL1ZfXQJ_g0j2A==/lib/arm, /data/app/co
04-30 17:43:25.195 23378 23640 I Unity   : HandleAdLoaded event received
04-30 17:43:25.195 23378 23640 I Unity   :
04-30 17:43:25.195 23378 23640 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

**Comment by olehkuznetsov** [comment]
Try Assets->Play Services Resolver->Android->Force Refresh, please.

**Comment by masandcomm** [comment]
I have the same problem. Resolver not solve dependencies. 
Cause of problems: mainTemplate.gradle in Assets/Plugins/Android. I needed it for solving multiDex (i have more than 64 methods) problem. When I removed it, Resolver did his job. New solution for multiDex is to change template without copying in Assets/Plugins/Android folder. Instead, you must directly change mainTemplate.gradle in current Unity editor folder ( something like /Applications/Unity/Hub/Editor/2019.1.1f1/PlaybackEngines/AndroidPlayer/Tools/GradleTemplates/mainTemplate.gradle).

**Comment by jama07** [comment]
I have the same problem, and I can't find a solution.

I have Unity 2019.1.2f1, macOS 10.14, play-games-plugin-for-unity v0.9.64.

I get the error:

05-15 12:38:28.378 12909 12931 W Unity   : *** [Play Games Plugin DLL] 05/15/19 12:38:28 +02:00 ERROR: Exception launching token request: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
05-15 12:38:28.378 12909 12931 W Unity   : System.Action:Invoke()
05-15 12:38:28.378 12909 12931 W Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
05-15 12:38:28.378 12909 12931 W Unity   :  
05-15 12:38:28.378 12909 12931 W Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
05-15 12:38:28.378 12909 12931 W Unity   : 
05-15 12:38:28.380 12909 12963 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
05-15 12:38:28.382 12909 12931 W Unity   : *** [Play Games Plugin DLL] 05/15/19 12:38:28 +02:00 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
05-15 12:38:28.382 12909 12931 W Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
05-15 12:38:28.382 12909 12931 W Unity   :   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <00000000000000000000000000000000>:0 
05-15 12:38:28.382 12909 12931 W Unity   :   at UnityEngine.AndroidJavaObject._CallStatic[ReturnType] (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0 
05-15 12:38:28.382 12909 12931 W Unity   :   at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00000] in <00000000000000000000000000000000>:0 
05-15 12:38:28.382 12909 12931 W Unity   :   at GooglePlayGames.Android.AndroidTokenClient.DoFetchToken (System.Boolean silent, System.Action`1[T] callback) [0x00000] in <00000000000000000000000000000000>:0 
05-15 12:38:28.382 12909 12931 W Unity   :   at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
05-15 12:38:28.382 12909 12931 W Unity   :   at GooglePlayGames.OurUtils.PlayGamesHelpe

I have reinstalled Unity, used unity-jar-resolver 1.2.111 and all that I have found googling the error, but there is no change.

With Unity 2018 using internal build I had no problem.

Any ideas would be greatly appreciated.

**Comment by olehkuznetsov** [comment]
Do you have file Assets/Plugins/Android/com.google.games.gpgs-plugin-support-0.9.64.aar after using Assets->Play Services Resolver->Android Resolver->Force Resolve?

**Comment by jama07** [comment]
Yes, it's there

**Comment by Junaid9768** [comment]
I'll tell you what worked for me.

1. Delete the Google play games Folder and Ads folder (if you are using it)

2. Make sure in Android resolve setting auto resolving is turned off .Now
Install the Google Play game plugin ,import all file and resolve
dependencies manually from the tab.

3. If you are using Ads then import ads plugin and make sure you do not
import AndroidResolver(if version is different) from that plugin.

4. Check in Dependencies file if android version mentioned matches your
version in Android studio (Installed)

5. Again Resolve Android Dependencies manually from the tab.

Hope this helps.

Regards.

**Comment by olehkuznetsov** [comment]
@jama07, in this case it can also be stripped by proguard if it is enabled. Can you check if with disabled proguard you have the same issue, please?

**Comment by jama07** [comment]
I have never checked "User Proguard File" in the Build section of Publishing Settings, is that what you mean or could it be enabled anywhere else?

**Comment by jama07** [comment]
Thanks Junaid9768 for your help, I'll check as soon as I can what you say

**Comment by olehkuznetsov** [comment]
It can be disabled in Player Settings->Publishing Settings->Minify->Release,Debug to None

**Comment by jama07** [comment]
@olehkuznetsov, thanks a lot, it works again now! Before it was checked Gradle (experimental), I put None and it connected again.

**Comment by mushdevstudio** [comment]
> It can be disabled in Player Settings->Publishing Settings->Minify->Release,Debug to None

Thank you so much olehkuznetsov
