### ISSUE TITLE
OnRealTimeMessageReceived() problem with receiving data

### ISSUE THREAD

**Issue by Sensej** [playgameservices/play-games-plugin-for-unity#2557]
Hi.

I'm using GPS real time multiplayer for my turn based game(2 players) in Unity. I want to decide who start the game at the begining by random and for that, I choose a number from 0 to 100 at the start of the game using Random(). and then sending this to the second player. And the player with higher number starts first.

Problem starts when I want to compare them.
When i call a function "whoStarts()" in "OnRealTimeMessageReceived" I have access to number I just received but not for my local number(Photo 1). And when i call this function in "addScore" i have access to my local number but not for the received number(Photo 2). Which is weird  for me, beacuse I'm using the same variables. So when at the start I'm sending my local number to the other player, and he's receving it. Why I don't have access to the same variable when i want to compare them, after I receive number from the second player?

![1](https://user-images.githubusercontent.com/9114589/56973719-b2fc5780-6b6d-11e9-869c-d258054ae574.png)
![2](https://user-images.githubusercontent.com/9114589/56973752-c4456400-6b6d-11e9-92d5-383e76190268.png)

Here's my code
`
public class StartGame : MonoBehaviour, RealTimeMultiplayerListener
{
    static StartGame listener = null;
    private static bool showingWaitingRoom = false;
    const int MinOpponents = 1;
    const int MaxOpponents = 1;
    const int GameVariant = 0;  // default

    private int playerATurn = 0;
    private int playerBTurn = 0;

    private int randomNumberA;
    private int randomNumberB;

    public Text counter;
    private int counterInt;
    private string counterString;

    public void RandomMatch()
    {
        listener = new StartGame();//Here Your Listener Instance 
        PlayGamesPlatform.Instance.RealTime.CreateQuickGame(MinOpponents, MaxOpponents, GameVariant, listener);
    }
    public void OnRoomSetupProgress(float percent)
    {
        if (!showingWaitingRoom)
        {
            showingWaitingRoom = true;
            PlayGamesPlatform.Instance.RealTime.ShowWaitingRoomUI();
        }
    }

    public void OnRoomConnected(bool success)
    {
        if (success)
        {
            SceneManager.LoadScene("TestScene");
        }
        else
        {
            //Room Connection failed 
            //you can put your code After the Room connection failed
        }
    }

    void Start()
    {
        System.Random rnd = new System.Random();
        randomNumberA = rnd.Next(0, 100);

        counterInt = 0;
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
        .EnableSavedGames()
        .Build();

        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.DebugLogEnabled = true;
        PlayGamesPlatform.Activate();

        Social.localUser.Authenticate((bool success) =>
        {
            if (!success)
            {
                //SSTools.ShowMessage("Failed to login!", SSTools.Position.bottom, SSTools.Time.twoSecond);
            }
        });
    }

    public void OnLeftRoom()
    {
        throw new NotImplementedException();
    }

    public void OnParticipantLeft(Participant participant)
    {
        throw new NotImplementedException();
    }

    public void OnPeersConnected(string[] participantIds)
    {
        throw new NotImplementedException();
    }

    public void OnPeersDisconnected(string[] participantIds)
    {
        throw new NotImplementedException();
    }

    public void addScore()
    {
        GameObject textScore = GameObject.FindGameObjectWithTag("text");
        textScore.GetComponent<Text>().text = "Score: " + counterInt;

        if (counterInt == 0)
        {
            SendMyUpdate(1, randomNumberA, 0, 0, 0);
        }
        else if (counterInt > 2)
        {
            whoStarts();
        }

        counterInt++;
    }

    public void SendMyUpdate(int decideWhoStarts, int randomNumber, int playerATurn, int playerBTurn, int counter)
    {
        string data = decideWhoStarts + ":" + randomNumber + ":" + playerATurn + ":" + playerBTurn + ":" + counter;
        byte[] bytedata = System.Text.ASCIIEncoding.Default.GetBytes(data);

        PlayGamesPlatform.Instance.RealTime.SendMessageToAll(false, bytedata);
    }

    public void OnRealTimeMessageReceived(bool isReliable, string senderId, byte[] myData)
    {
        string rawdata = System.Text.ASCIIEncoding.Default.GetString(myData);
        string[] cut = rawdata.Split(new string[] { ":" }, System.StringSplitOptions.RemoveEmptyEntries);
        int counterValue = Convert.ToInt32(cut[1]);

        randomNumberB = Convert.ToInt32(cut[1]);

        whoStarts();
    }

    private void whoStarts()
    {
        SSTools.ShowMessage("PlyaerB: " + randomNumberB, SSTools.Position.top, SSTools.Time.twoSecond);
        SSTools.ShowMessage("PlyaerA: " + randomNumberA, SSTools.Position.bottom, SSTools.Time.twoSecond);

        if (randomNumberA > randomNumberB)
        {
            playerATurn = 1;
            playerBTurn = 0;
        }
        else
        {
            playerATurn = 0;
            playerBTurn = 1;
        }
    }
}

`

**Comment by bbekec** [comment]
There is a bug i think. I had problem with receiving data. So if I find objects with tag and i can take data out of method. Create a class and attach it an object (for example empty Text object.). Define variable (randomNumberB ) in that class. Then find object with tag and try to reach the variable (randomNumberB ) by that object.

**Comment by Sensej** [comment]
@bbekec Thank you so much, it solved my problem.
