### ISSUE TITLE
Question: Google Play API version?

### ISSUE THREAD

**Issue by PeeGee85Spil** [playgameservices/play-games-plugin-for-unity#2558]
Dear maintainers,

We recently received an e-mail from Google warning us to update any of our plugins/libraries that use the Google Play Developer API to version 3. I was wondering, does the play-games-plugin-for-unity depend on the Google Play Developer API and if so, which version is it using? Original e-mail from google about updating included below. Thanks!

-------- Original e-mail --------
Hello Google Play Developer,StartingDecember 1, 2019, versions 1 and 2 of theGoogle Play Developer APIwill no longer be available. We’re reaching out because you are currently using one of these versions, and we wanted to make sure you are aware that if you do not migrate to version 3 by this date, API calls will result in errors.At last year’s Google I/O, we introduced version 3 of the Google Play Developer API. In addition to all the features offered in versions 1 and 2, version 3 allows you to transactionally start, manage and halt staged releases on all tracks, including production, open testing, closed testing (including the new additional testing tracks) and internal testing.Action requiredIf you use the Google Play API client libraries, please upgrade to the latest versions, which already support version 3 of the API. In many cases, changing the version of the client library should be all that you need to do.If you currently use version 1 of the API, you will also need to link your API project to the Google Play Console before converting to version 3. You can learn more about this processhere. Note that code changes may also be required.For more information, please reference our blog post.We hope you enjoy the new features of the Google Play Developer API, and we look forward to your continued feedback to help us improve the developer experience on Google Play.

**Comment by olehkuznetsov** [comment]
Google Play Developer API is for:
- The Subscriptions and In-App Purchases API lets you manage in-app purchases and subscriptions.
- The Publishing API lets you upload and publish apps, and perform other publishing-related tasks.

In Google Play Games plugin this API isn't used.
