### ISSUE TITLE
Is there any way to get all invitations?

### ISSUE THREAD

**Issue by PeroPrepper** [playgameservices/play-games-plugin-for-unity#256]
Hello,

When user enters my game,  I would like to check if there are any (and how many)
invitations waiting for real-time multiplayer game. I can't use onInvitationReceived callback, because it only reports notifications that come in when the game is running. 

I need function something like "getInvitations" but I cant find it anywhere. Is there any
way to achieve that?

I am sorry If this is the wrong place to post this question.

Thanks!

Pero

**Comment by claywilkinson** [comment]
tracking internally as 18319104

**Comment by amirlatif** [comment]
I added this function to NativeTurnBasedMultiplayerClient.cs, works for me:

    public void GetAllTBInvitations(Action<Invitation> callback)
    {
        mTurnBasedManager.GetAllTurnbasedMatches(allMatches =>
        {
            foreach (var invitation in allMatches.Invitations())
            {
                var converted = invitation.AsInvitation();
                Logger.d("Passing converted invitation to user callback:" + converted);
                callback(converted);
            }
        
            callback(null);
        });
    }

**Comment by claywilkinson** [comment]
This API has been implemented in version 0.9.25 of the plugin.
