### ISSUE TITLE
Automatch inconsistency

### ISSUE THREAD

**Issue by habitoti** [playgameservices/play-games-plugin-for-unity#2560]
Not sure this is strictly related to this plugin or the play games services in general: A player creates an invitation with just one automatch slot. For some reason he is anyway automatched into a match with 4 players (3 open slots). So far, so good (NOT!), BUT: when trying to take a turn, it produces an error -6004 (STATUS_MULTIPLAYER_ERROR_INVALID_OPERATION) for him, with no other more specific information in the logs. 
I am a bit poking in the fog here. What could be the reason? Why would the match algorithm match someone into a 4-slot game when he created an invitation for two (game allows for 2-4 players).

It seems like passing to another automatch slot by providing null for the next participant does not work in this case. I assume because the invited set of two players would be full now with two matches, while the actual chosen match (4 slots) still has two automatch slots. Not sure where the first information would reside, as the game is launched with a match object for 4 players.

**Comment by olehkuznetsov** [comment]
Can you try to reproduce it in SmokeTest sample, please?

**Comment by habitoti** [comment]
Hi,
I think after some more research I now believe that this is even part of the concept, though I believe it makes it ultra hard for devs to cope with all situations that can occur.
After tons of testing and forcing different situations, it seems like setting up a quick match (which initially produces 3 automatch slots if you are not matched into a running game) doesn‘t actually guarantee eventually a match with 4 players (unlike explicitly inviting 3 players or automatches). Even if I already had the first turn produced in such a game, someone inviting explicitly just one automatch slot can be matched into the 4-seat game, and the number of remaining slots is simply reduced by 2. But this can only work under the assumption that any turn can be taken agnostically to the number of players, which is often not the case. My first players has a certain amount of resources (e.g. cards) that differs for a 2, 3 or 4 person game, so the first move needs to fix the number of seats. If it‘s now reduced after a first turn has been taken, I am in trouble. I believe this needs to be at least configurable („initial quick match changeable“) to allow to cover such type of games.
But then this is probably not a plugin topic, but rather the PGS API business. But mabye you are in contact with those guys?

**Comment by olehkuznetsov** [comment]
>But mabye you are in contact with those guys?
We are the same guys now =)

I've tried to create game with 3 auto slots on one device and game with 1 auto slot on another device and they are not connected.
Is it the case if only 1 auto slot should be open on first device and two other already occupied?

**Comment by habitoti** [comment]
The initial match has to be created with the quick match fct. (2-4 players allowed). If not matched immediately elsewhere, it will create a 4-seat match with me and three automatch slots. Now another players creates a normal invitation with one automatch slot, so intending to play a match of two. He will be matched into the 4-seat game, however the number of automatch slots will now be 0. 
For my game, depending on randomness it could have been already my first turn after quick matching, and all resources are distributed according to number of seats. So starting with 4 seats, I did my turn with according number of cards. Now the two-seat match player is matched in, and the number of overall slots is reduced to me and him, no more automatch slots. Of course, the resource distribution is no longer valid, and the first player (me) would actually have to redo his initial move with different set of cards, chips, etc. -- but I took and sent my turn already.

**Comment by olehkuznetsov** [comment]
Probably, you need to implement first non game turn. Like pressing ready button or it can be just auto-turn. 
And each joined player will do the same 'handshake' turn. After turn is returned to first player you know exact number of players and can give cards and chips.

**Comment by habitoti** [comment]
Maybe this is what I need to do now (which is a different procedure than for other platforms, which I would have liked to avoid).
It would have been great to have a bit more control. At least implicitly, I think a match that had at least one turn commited should not be subject to change of seats any longer (and would then be no target for e.g. a two-seat seeker). This is usually a problem else. 
Or quick match could optionally just produce randomly fixed size games within the provided margins, so let's say 2, 3 and 4 game matches in case I am not matched in elsewhere. For certain types of games this would produce the necessary control over the process.

**Comment by olehkuznetsov** [comment]
Is on other platforms there is no first turn before players joined?

Probably you can try another approach:
Try to create game first with 4 players if there is no game yet with real player then with 3 and if no game with 2 players then just create one.
In this case most of auto created games will be with two players but if someone creates game with 4 players it still will be filled.

**Comment by habitoti** [comment]
On other platforms there is not that quick match like „surprise“ match.  Actually I like that idea of getting a „best fit“ that let‘s me instantly play, and for my setup it doesn‘t matter in what kind of game you‘re initially matched into. It‘s just the fact that an already created match (where I committed already a turn) is unexpectedly changed later on that makes my life hard ;-)

I could try your suggestion of creating my own „quick match“ functionality to make sure that so created matches stay with their initial size. It might be comparably slow doing it client side, I am afraid, but it could be a viable workaround.

**Comment by olehkuznetsov** [comment]
Basically you need to create quick match like you do now with 2-4 allowed but if in created match you are only one player with all other auto-matchers then leave that match and create a new one for only 2 allowed players.

**Comment by habitoti** [comment]
I worked around that behavior for my game now (which was quite some effort ;-) ), but in the end I didn‘t want to sacrifice the quick match “wisdom” in the backend to come up with the best matches possible (which I hope it does...). 
@olehkuznetsov : I am closing this now, as it probably works as expected from your perspective. I would still prefer either some parametrization to generally prevent changing of initially set up seats in an automatch (so if you‘re not matched in elsewhere), or at least lock it when the first turn was committed to prevent further changes then.
