### ISSUE TITLE
Google Play services and support arm64

### ISSUE THREAD

**Issue by denis22718** [playgameservices/play-games-plugin-for-unity#2564]
Hello, I have this question: Do Google Play services work if arm64 support is enabled? How much I did not try to force them to function, nothing happens to me (even the animated green login window does not appear), although if I turn off the support for arm64 everything works correctly. Is it worth trying to do something further?
Unity 2019.1.1f1
![Screenshot_1](https://user-images.githubusercontent.com/32695950/57173063-4ed6dd80-6e64-11e9-8685-16649222fe70.png)

**Comment by OriginalsByToto** [comment]
Normally this SDK should support arm64, at least it's working for me and some other people...

Can you open your generated .apk file and check the /lib folder: there should be one sub-folder per architecture. These sub-folders contains some .so files: can you check if libgpg.so is present in /lib/arm64-v8a?

**Comment by dashanddot** [comment]
> 
> 
> Normally this SDK should support arm64, at least it's working for me and some other people...
> 
> Can you open your generated .apk file and check the /lib folder: there should be one sub-folder per architecture. These sub-folders contains some .so files: can you check if libgpg.so is present in /lib/arm64-v8a?

How to find out that SDK supports arm64? What sdk do you use?

**Comment by OriginalsByToto** [comment]
Maybe I used a wrong word, sorry, I'm talking about this plugin.
I would say that this unity plugin is normally compatible with arm64.
According to the changelog, it's compatible since version 0.9.51.

**Comment by muzaffaraka** [comment]
I have same issue with the plugin. libgpg.so is not included in resulting build:

![image](https://user-images.githubusercontent.com/3406998/57386593-57f5e080-71bd-11e9-86c5-197a9c2b685e.png)

Plugin version: 0.9.62

**Comment by dashanddot** [comment]
> 
> 
> I have same issue with the plugin. libgpg.so is not included in resulting build:


**I found solution!**

You need to enable arm64? and after - force resolve in Play Service Resolver!

**Comment by TakingAway** [comment]
@denis22718 Did the force resolve help you? i'm not sure. but i have same trouble, and force resolve don't help me.

**Comment by itsOgden** [comment]
I'm having the same issue. Force resolve didn't seem to fix it for me either.

**Comment by FancisLuo** [comment]
We find the libgpg.so integrated in the .srcaar, as the picture below.
![image](https://user-images.githubusercontent.com/10607925/60939040-dcbdc180-a308-11e9-8709-50751ca9cb50.png)

but, my question is, how to replace the com.google.games.gpgs-plugin-support-0.9.64.aar with gpgs-plugin-support-0.9.64.srcaar, then we could get the arm64-v8a/libgpg.so.

**Comment by FancisLuo** [comment]
I think I've get the solution(version: 0.9.64). Here's the steps:
1. Check the ARM64 item on Target Architectures, checking other two items will be better, but is optional,
2. Remove original integrated SDK of GPG, and re-import the SDK,
3. Quit unity, and restart
4. force resolve in Play Service Resolver

that's the solution from @dashanddot

**Comment by maggiechen** [comment]
I followed steps 1-4 and it still didn't add libgpg.so to the arm64-v8a folder.

**Comment by macagu** [comment]
Note that the **libgpg.so** is located inside the **JNI** folder (not on root)

**Comment by olehkuznetsov** [comment]
Already supported
