### ISSUE TITLE
Show pop up "Warning ! Google Play Games was not configured" while build game

### ISSUE THREAD

**Issue by yoga4094** [playgameservices/play-games-plugin-for-unity#2572]
I install latest play games plugin version 0.9.63 in my game. Show pop up window 
"Warning ! Google Play Games was not configured, Game Services will not worked correctly" 
while build my game, It's still installed and run the game in my Android device but Google Play Login not working in the game even i already set up my Game Service in Google Play Console and already publish it in beta version. any ideas ? Thanks

**Comment by olehkuznetsov** [comment]
You need to fill 'Window->Google Play Games->Setup->Android Setup'

**Comment by Stephie-SGS** [comment]
I had the same issue and @olehkuznetsov solution worked for me. I had the GPGSIds script in my asset folder but it hadn't configured correctly so I wasn't able to figure it out to begin with.
This thread helped a lot. Thanks

**Comment by Shadowing1983** [comment]
> You need to fill 'Window->Google Play Games->Setup->Android Setup'
Window->Google Play Games->Setup->Android Setup'

Setup doesn't even exist for me.
