### ISSUE TITLE
OmniSharp : Error talking to http://localhost:53905/checkreadystatus, Line 19,  Column 1

### ISSUE THREAD

**Issue by srcsameer** [playgameservices/play-games-plugin-for-unity#2581]
Hi! i am trying to use sublime text 3 (build  3176)  with unity 2018.3.1f1 i did all the setup following [this video ](https://www.youtube.com/watch?v=z7na1MuMDRg) but when i am  running sublime text it's throwing an error 

> OmniSharp : Error talking to http://localhost:53905/checkreadystatus, Line 19,  Column 1

in the console i am  getting this log:

> DPI mode: system
DPI scale: 1
startup, version: 3176 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/SKF
packages path: /C/Users/Sameer/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Sameer/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Sameer/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.0862895
startup time: 0.11929
first paint time: 0.120289
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin OmniSharp.OmniSharpSublime
plugins loaded
omnisharp plugin_loaded
solution_path:C:\SKF\Assets\Script
omni_port:53905
"C:/Users/Sameer/AppData/Roaming/Sublime Text 3/Packages/OmniSharp/prebuilt-omnisharp-roslyn/omnisharp.cmd" -s "C:\SKF\Assets\Script" -p 53905 --hostPID 3332
already_bound_solution:C:\SKF\Assets\Script
solution path: C:\SKF\Assets\Script
======== request ======== 
 Url: http://localhost:53905/checkreadystatus 
 Data: {"line": "19", "column": "1", "buffer": "using System.Collections;\nusing System.Collections.Generic;\nusing UnityEngine;\n\npublic class NewBehaviourScript : MonoBehaviour\n{\n    // Start is called before the first frame update\n    void Start()\n    {\n        \n    }\n\n    // Update is called once per frame\n    void Update()\n    {\n        \n    }\n}\n", "filename": "C:\\SKF\\Assets\\Script\\NewBehaviourScript.cs"}
Package Control: No updated packages
HTTPConnectionPool(host='localhost', port=53905): Max retries exceeded with url: /checkreadystatus (Caused by ProtocolError('Connection aborted.', ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061)))
already_bound_solution:C:\SKF\Assets\Script
solution path: C:\SKF\Assets\Script
======== request ======== 
 Url: http://localhost:53905/checkreadystatus 
 Data: {"line": "19", "column": "1", "buffer": "using System.Collections;\nusing System.Collections.Generic;\nusing UnityEngine;\n\npublic class NewBehaviourScript : MonoBehaviour\n{\n    // Start is called before the first frame update\n    void Start()\n    {\n        \n    }\n\n    // Update is called once per frame\n    void Update()\n    {\n        \n    }\n}\n", "filename": "C:\\SKF\\Assets\\Script\\NewBehaviourScript.cs"}
already_bound_solution:C:\SKF\Assets\Script
HTTPConnectionPool(host='localhost', port=53905): Max retries exceeded with url: /checkreadystatus (Caused by ProtocolError('Connection aborted.', ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061)))
solution path: C:\SKF\Assets\Script
======== request ======== 
 Url: http://localhost:53905/checkreadystatus 
 Data: {"line": "19", "column": "1", "buffer": "using System.Collections;\nusing System.Collections.Generic;\nusing UnityEngine;\n\npublic class NewBehaviourScript : MonoBehaviour\n{\n    // Start is called before the first frame update\n    void Start()\n    {\n        \n    }\n\n    // Update is called once per frame\n    void Update()\n    {\n        \n    }\n}\n", "filename": "C:\\SKF\\Assets\\Script\\NewBehaviourScript.cs"}
HTTPConnectionPool(host='localhost', port=53905): Max retries exceeded with url: /checkreadystatus (Caused by ProtocolError('Connection aborted.', ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061)))
solution path: C:\SKF\Assets\Script
======== request ======== 
 Url: http://localhost:53905/checkreadystatus 
 Data: {"line": "19", "column": "1", "buffer": "using System.Collections;\nusing System.Collections.Generic;\nusing UnityEngine;\n\npublic class NewBehaviourScript : MonoBehaviour\n{\n    // Start is called before the first frame update\n    void Start()\n    {\n        \n    }\n\n    // Update is called once per frame\n    void Update()\n    {\n        \n    }\n}\n", "filename": "C:\\SKF\\Assets\\Script\\NewBehaviourScript.cs"}
HTTPConnectionPool(host='localhost', port=53905): Max retries exceeded with url: /checkreadystatus (Caused by ProtocolError('Connection aborted.', ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061)))
solution path: C:\SKF\Assets\Script
======== request ======== 
 Url: http://localhost:53905/checkreadystatus 
 Data: {"line": "19", "column": "1", "buffer": "using System.Collections;\nusing System.Collections.Generic;\nusing UnityEngine;\n\npublic class NewBehaviourScript : MonoBehaviour\n{\n    // Start is called before the first frame update\n    void Start()\n    {\n        \n    }\n\n    // Update is called once per frame\n    void Update()\n    {\n        \n    }\n}\n", "filename": "C:\\SKF\\Assets\\Script\\NewBehaviourScript.cs"}
HTTPConnectionPool(host='localhost', port=53905): Max retries exceeded with url: /checkreadystatus (Caused by ProtocolError('Connection aborted.', ConnectionRefusedError(10061, 'No connection could be made because the target machine actively refused it', None, 10061)))
already_bound_solution:C:\SKF\Assets\Script

**Comment by Noah1911** [comment]
Is this somehow related to this plugin?
