### ISSUE TITLE
Проблема с мултиплеером на сервере. Перестаёт функционировать. Entering internalOnDataReceive : 35  ERROR_INTERNAL  VALID 

### ISSUE THREAD

**Issue by maxcre** [playgameservices/play-games-plugin-for-unity#2585]
После запуска сервера с игроками в консоль постоянно прибавляются эти 3 ошибки если их так можно назвать, а именно: 
1. Entering internalOnDataReceive : 35 
2. Entering internal callback for internal SendReliableMessageCallback ERROR_INTERNAL 
3. Entering internal callback for internal SendReliableMessageCallback VALID 

Как это решить ? Ведь спустя какое то время всё перестаёт функционировать...

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
