### ISSUE TITLE
Remove the maximum value of 10,000 for incremental achievements.

### ISSUE THREAD

**Issue by exzizt** [playgameservices/play-games-plugin-for-unity#2588]
Remove the maximum value of 10,000 for incremental achievements.

Example: What if I want the user to collect 25,000 gold to unlock an achievement but still show their progress?

**Comment by JSBmanD** [comment]
As a workaround to that I suggest you to use divided number for achievement. And it will be like 25k.

**Comment by vaibhavgpt-google** [comment]
Closing this issue, as it is not related to Unity Plugin
