### ISSUE TITLE
LoadAchisvements and LoadAchievementDescriptions not loading anything

### ISSUE THREAD

**Issue by dcaso** [playgameservices/play-games-plugin-for-unity#259]
Hello,

I'm developping a 3D game with Unity for Android. Your pluggin is perfectly matching with my expectations. Nevertheless, I'm wondering if LoadAchivements and LoadAchievementDescriptions are implemented. I would like to check out the list of the succeeded achievements in order to conduct a specific logic in the game. For that purpose I would need at least to load the complete list of the previously achieved achievement: this is what LoadAchivements is supposed to do...
My code seems to work correctly since I can login in and I can display the Achievements UI, but when I call LoadAchievements I get a null size table in the callback even if one achievement is achieved!

Do you have any idea?

**Comment by claywilkinson** [comment]
tracking internally as 18317640

**Comment by zabkwak** [comment]
Hi guys, 

is there any progress?

**Comment by ArmandCloud** [comment]
Up+1

**Comment by claywilkinson** [comment]
This has been implemented in the version 0.9.25 of the plugin
