### ISSUE TITLE
Is data transfer between google play game server and client local android device encryped?

### ISSUE THREAD

**Issue by Sailendrakc** [playgameservices/play-games-plugin-for-unity#2607]
My android game app requires some very very important data to be stored in google drive of my client. That folder cannot be acessed except by my application so the stored data is safe. But at the time of Data transfer (retreving and updating that data), is the data encrypted by something like public-private key or any symetric keys?

**Comment by olehkuznetsov** [comment]
I think if user has root access to the phone then data can be get during transfer, so, if you worry about this case you can additionally encrypt it, but still if it is on device side - it still can be accessed.
