### ISSUE TITLE
ReportProgress error in IOS

### ISSUE THREAD

**Issue by Toranyan** [playgameservices/play-games-plugin-for-unity#261]
Calling ReportProgress() in IOS results in an error in line 80 of GPGSInterface.m :
*outIsIncremental = ([aMetadata type] == GPGAchievementTypeIncremental);

It appears that [aMetadata type] is being called before the callback for GPGAchievementMetadata metadataForAchievementId. 

Quick fix by moving lines 79-98 to within callback. Seems to work, however not sure if this would cause some synchro problems.

**Comment by claywilkinson** [comment]
Closing this one since it is obsolete as of 0.9.10 which uses the C++ library to access games services.
