### ISSUE TITLE
Crash on Authenticate: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArraySet;

### ISSUE THREAD

**Issue by Kirk-C** [playgameservices/play-games-plugin-for-unity#2611]
Calling PlayGamesPlatform.Instance.Authenticate will cause a fatal crash on my device. 

`Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArraySet"`

I've tried downgrading, re-importing the plugin, making sure all my SDKs/Tools/Extras are up to date in SDK Manager. Everything is fine until a window is attempted to be made to login. 

The device is running Android 8.0 and I'm on Unity 2019.1.7f1

The other plugins I'm using in Unity are UnityIAP and Google Mobile Ads.

**Comment by JakeMatthewsBelcher** [comment]
I am experiencing the same issue.

**Comment by Kirk-C** [comment]
Discovered the cause:

The latest version of the Google Mobile Ads Unity Plugin is causing it, downgrading prevents the issue.

I have had success with this version: https://github.com/googleads/googleads-mobile-unity/releases/tag/3.17.0

Although, you lose the nice toggle for preventing data logging before admob initialization, I'm sure there is a workaround.

**Comment by VishalParab902920** [comment]
I was facing the same issue so i removed admob plugin version 3.18 and and added version 3.17. The app still crashed with crash report saying admob plugin not initialized correctly.
So what i did was again added version 3.18 and setup up admob stuff and copied the manifest file onto notepad.Then i removed version 3.18 and added 3.17 again and in the manifest i pasted the xml I copied in notepad earlier.
and everything worked fine for me : )
