### ISSUE TITLE
ERROR_INTERNAL opening save game

### ISSUE THREAD

**Issue by ABe138** [playgameservices/play-games-plugin-for-unity#2614]
Hi there,

As it is said in the title, using **PlayGamesPlatform.Instance.SavedGame.OpenWithAutomaticConflictResolution**
on some devices consistently leads to a crash returning "unknown status: ERROR_INTERNAL" with plugin version 0.9.64.

I've noticed some similar topics opened as of 2016, they are currently closed with issues claimed resolved in updated version of the plugin, however it cannot be the case.

Some of our users report they are no longer able to launch the app. Their crash logs vaguely indicate that it has something to do with reading save data from GPGS on startup. The problem seems to be kind of rare, and for a decent time we were unable to reproduce it on any of our test devices. Luckily I have one right now, and the problem seems to be somehow account-device pair related, as switching device OR user account gets rid of the issue and makes my app run as it should.

**"Unity" LogCat:**
06-24 00:16:11.635: I/Unity(23285): Initializing GPGS.
06-24 00:16:11.635: I/Unity(23285):  
06-24 00:16:11.635: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:11.661: I/Unity(23285): Authenticating...
06-24 00:16:11.661: I/Unity(23285):  
06-24 00:16:11.661: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:11.690: I/Unity(23285): Starting Auth with token client.
06-24 00:16:11.690: I/Unity(23285):  
06-24 00:16:11.690: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:11.825: W/Unity(23285): !!! [Play Games Plugin DLL] 06/24/19 0:16:11 +03:00 WARNING: Creating new PlayGamesPlatform
06-24 00:16:11.825: W/Unity(23285):  
06-24 00:16:11.825: W/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:11.826: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:11 +03:00 DEBUG: Activating PlayGamesPlatform.
06-24 00:16:11.826: I/Unity(23285):  
06-24 00:16:11.826: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:11.826: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:11 +03:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
06-24 00:16:11.826: I/Unity(23285):  
06-24 00:16:11.826: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:11.826: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:11 +03:00 DEBUG: Creating platform-specific Play Games client.
06-24 00:16:11.826: I/Unity(23285):  
06-24 00:16:11.826: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:11.826: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:11 +03:00 DEBUG: Creating Android IPlayGamesClient Client
06-24 00:16:11.826: I/Unity(23285):  
06-24 00:16:11.826: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:21.984: D/GamesUnitySDK(23285): Performing Android initialization of the GPG SDK
06-24 00:16:22.055: I/Unity(23285): Building GPG services, implicitly attempts silent auth
06-24 00:16:22.055: I/Unity(23285):  
06-24 00:16:22.055: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:22.345: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:22 +03:00 DEBUG: Invoking user callback on game thread
06-24 00:16:22.345: I/Unity(23285):  
06-24 00:16:22.345: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:22.665: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:22 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
06-24 00:16:22.665: I/Unity(23285):  
06-24 00:16:22.665: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:22.684: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:22 +03:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback
06-24 00:16:22.684: I/Unity(23285):  
06-24 00:16:22.684: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:22.684: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:22 +03:00 DEBUG: Populating User
06-24 00:16:22.684: I/Unity(23285):  
06-24 00:16:22.684: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:22.732: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:22 +03:00 DEBUG: Found User: [Player: 'user0' (id g*************)]
06-24 00:16:22.732: I/Unity(23285):  
06-24 00:16:22.732: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:22.732: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:22 +03:00 DEBUG: Maybe finish for User
06-24 00:16:22.732: I/Unity(23285):  
06-24 00:16:22.732: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:22.732: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:22 +03:00 DEBUG: Auth finished. Proceeding.
06-24 00:16:22.732: I/Unity(23285):  
06-24 00:16:22.732: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:22.733: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:22 +03:00 DEBUG: Invoking Callbacks: System.Action`2[System.Boolean,System.String]
06-24 00:16:22.733: I/Unity(23285):  
06-24 00:16:22.733: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:22.734: I/Unity(23285): Authentication complete.
06-24 00:16:22.734: I/Unity(23285):  
06-24 00:16:22.734: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:22.736: I/Unity(23285): Trying to read save data...
06-24 00:16:22.736: I/Unity(23285):  
06-24 00:16:22.736: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:22.737: I/Unity(23285): Trying to open save data...
06-24 00:16:22.737: I/Unity(23285):  
06-24 00:16:22.737: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:22.796: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:22 +03:00 DEBUG: Invoking user callback on game thread
06-24 00:16:22.796: I/Unity(23285):  
06-24 00:16:22.796: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:37.844: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:37 +03:00 DEBUG: Entering internal callback for SnapshotManager#OpenCallback
06-24 00:16:37.844: I/Unity(23285):  
06-24 00:16:37.844: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:37.859: W/Unity(23285): *** [Play Games Plugin DLL] 06/24/19 0:16:37 +03:00 ERROR: Encountered unknown status: ERROR_INTERNAL
06-24 00:16:37.859: W/Unity(23285):  
06-24 00:16:37.859: W/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:37.876: I/Unity(23285):  [Play Games Plugin DLL] 06/24/19 0:16:37 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_OUT status: ERROR_NOT_AUTHORIZED
06-24 00:16:37.876: I/Unity(23285):  
06-24 00:16:37.876: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
06-24 00:16:37.892: I/Unity(23285): Calling Signout in token client
06-24 00:16:37.892: I/Unity(23285):  
06-24 00:16:37.892: I/Unity(23285): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)

**Comment by olehkuznetsov** [comment]
Should be fixed in v0.10.06. Feel free to reopen if it reproduces there.
