### ISSUE TITLE
Authentication is a success but Social.localUser.id is empty ?

### ISSUE THREAD

**Issue by AlexKhundar** [playgameservices/play-games-plugin-for-unity#2621]
Hello there.
The game is already live. We store in our database player information. For Android players, the "final" player ID (stored in out database) is made like that :

`void OnAuthenticated(bool success, string errorInfo)
	{
if  (success)
	id = "android_" + Social.localUser.id;
	}`

And, surprisingly, our database contains a player which final ID is just "android_". And when final ID is made, we are in the success case. Which means even in success case, Social.localUser.id is null or empty.
So, how did that happen ? Fake account ? What should we do in this case ? To fallback in a fail authentication case ?

Thanks for your help

**Comment by olehkuznetsov** [comment]
Should be fixed in v0.10.06. Feel free to reopen if it reproduces there.
