### ISSUE TITLE
CRASH on open app,java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf

### ISSUE THREAD

**Issue by SturgeonDu** [playgameservices/play-games-plugin-for-unity#2624]
**I used play games plugin for unity version 0.9.64** 
Unity 2017.3

First i have a same problem like 
java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment

then 
1.delete the mainTemplate.gradle in my project, 
2.delete all the resolved lib.
3.force resolver lib and build a new apk.
4.create a same mainTemplate.gradle.
5.set multiDexEnabled true
build apk success !!
but..

when i click the apk on my phone and CRASH!!!!

When i  import the package resolve all lib and build a empty apk, it work well.
my project used google AdMob,FireBase,FB,and other plugin. 
Before that, my projects were working normally.

God bless you,give me some help.
thinks.

this is my log:

`07-04 20:02:58.991 E/AndroidRuntime(31406): FATAL EXCEPTION: main
07-04 20:02:58.991 E/AndroidRuntime(31406): Process: com.test.GooglePlayTest, PID: 31406
07-04 20:02:58.991 E/AndroidRuntime(31406): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at com.google.android.gms.auth.api.Auth.<clinit>(Unknown Source:0)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at com.google.games.bridge.TokenFragment.buildClient(TokenFragment.java:382)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at com.google.games.bridge.TokenFragment.processRequest(TokenFragment.java:279)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at com.google.games.bridge.TokenFragment.onResume(TokenFragment.java:506)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at android.app.Fragment.performResume(Fragment.java:2590)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1643)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2222)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2168)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2069)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:739)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at android.os.Handler.handleCallback(Handler.java:891)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at android.os.Looper.loop(Looper.java:207)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at android.app.ActivityThread.main(ActivityThread.java:7539)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at java.lang.reflect.Method.invoke(Native Method)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
07-04 20:02:58.991 E/AndroidRuntime(31406): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.Chessia.AlchemyWar-EHgFyi9O5LlQpXtTGoUzpw==/base.apk"],nativeLibraryDirectories=[/data/app/com.Chessia.AlchemyWar-EHgFyi9O5LlQpXtTGoUzpw==/lib/arm64, /data/app/com.Chessia.AlchemyWar-EHgFyi9O5LlQpXtTGoUzpw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-04 20:02:58.991 E/AndroidRuntime(31406): 	... 19 more`

**Comment by blahti** [comment]
I have been trying to get my apps ready to be meet the August deadline for 64-bit compliance on Google Play. In doing that for my second game, I encountered the TokenFragment problem again. I thought for sure I had already taken steps that would avoid this by converting to 0.9.64 of the Play Games plugin, setting up Gradle build and Proguard. Turns out I was mistaken. I still needed to update the unity-jar-resolver: https://github.com/googlesamples/unity-jar-resolver
I updated to 1.2.117 and then did  resolve (or Force Resolve). 

So if you are using Gradle build and Proguard, try that.

**Comment by SturgeonDu** [comment]
> I have been trying to get my apps ready to be meet the August deadline for 64-bit compliance on Google Play. In doing that for my second game, I encountered the TokenFragment problem again. I thought for sure I had already taken steps that would avoid this by converting to 0.9.64 of the Play Games plugin, setting up Gradle build and Proguard. Turns out I was mistaken. I still needed to update the unity-jar-resolver: https://github.com/googlesamples/unity-jar-resolver
> I updated to 1.2.117 and then did resolve (or Force Resolve).
> 
> So if you are using Gradle build and Proguard, try that.

Thanks replay
I fixed this issue in this week. also because of dealing with Google Play 64-bit !!
update Unity to 2018.3 and unity-jar-resolver to 1.2.122 and ForceResolver!!
