### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'gpg': The specified module could not be found.

### ISSUE THREAD

**Issue by SteliosDaVitzi** [playgameservices/play-games-plugin-for-unity#2625]
Hi!Recently we upgraded our project from unity 2017.2.1f1 to 2019.1.8, we solved the most of the problems, but when we build with arm64 selected, we cannot login in google play services.Arm7 works fine with no errors.I found some other answers about this issue, but none of them worked for us.Is there any official solution for this yet?

**Comment by FancisLuo** [comment]
We worked out a workaround. (using 0.9.64) We found that the gpgs-plugin-support-0.9.64.srcaar has the arm64-v8a/libgpg.so, which is under the GooglePlayGames/Editor/m2repository/com/google/games/gpgs-plugin-support/0.9.64/ when unzip it. So, we copy it to the com.google.games.gpgs-plugin-support-0.9.64.aar. Then we can find the libgpg.so in the folder of lib/arm64-v8a/. But, we need an normal solution for this.

**Comment by FancisLuo** [comment]
I think I've get the solution(version: 0.9.64). Here's the steps:
1. Check the ARM64 item on Target Architectures, checking other two items will be better, but is optional,
2. Remove original integrated SDK of GPG, and re-import the SDK,
3. Quit unity, and restart
4. force resolve in Play Service Resolver

that's the solution from @dashanddot

hope this will help.

**Comment by silengdog** [comment]
> I think I've get the solution(version: 0.9.64). Here's the steps:
> 
> 1. Check the ARM64 item on Target Architectures, checking other two items will be better, but is optional,
> 2. Remove original integrated SDK of GPG, and re-import the SDK,
> 3. Quit unity, and restart
> 4. force resolve in Play Service Resolver
> 
> that's the solution from @dashanddot
> 
> hope this will help.

Encountered the same problem.
What do you mean by "Check the ARM64 item", don't know how to do this step

**Comment by hippogamesunity** [comment]
+1 here, tried 0.9.50 and 0.9.64 with Unity 2019.2.4.

**Comment by FancisLuo** [comment]
> > I think I've get the solution(version: 0.9.64). Here's the steps:
> > 
> > 1. Check the ARM64 item on Target Architectures, checking other two items will be better, but is optional,
> > 2. Remove original integrated SDK of GPG, and re-import the SDK,
> > 3. Quit unity, and restart
> > 4. force resolve in Play Service Resolver
> > 
> > that's the solution from @dashanddot
> > hope this will help.
> 
> Encountered the same problem.
> What do you mean by "Check the ARM64 item", don't know how to do this step

so sorry to reply this so late. "Check the ARM64 item" step, in the Configuration of Player setting (Project settings), as the screenshot as below:

![image](https://user-images.githubusercontent.com/10607925/69532779-826c8700-0fb1-11ea-950b-6d3ce481f4ea.png)

**Comment by hippogamesunity** [comment]
@FancisLuo I can confirm this works with 0.9.64 + Unity 2019.2.4.

**Comment by FancisLuo** [comment]
> @FancisLuo I can confirm this works with 0.9.64 + Unity 2019.2.4.

Thank you! :)
