### ISSUE TITLE
Wrong behavior for ILeaderboard.SetUserFilter?

### ISSUE THREAD

**Issue by IterativeInteractive** [playgameservices/play-games-plugin-for-unity#2629]
Hello,

According to [Unity's documentation for ILeaderboard.SetUserFilter](https://docs.unity3d.com/ScriptReference/SocialPlatforms.ILeaderboard.SetUserFilter.html), making this call should "only search for these user IDs."

From PlayGamesLeaderboard.AddScore, it seems however that these user ids are instead getting filtered out? That's the exact opposite behavior!

`        
internal int AddScore(PlayGamesScore score)
        {
            if (mFilteredUserIds == null || mFilteredUserIds.Length == 0)
            {
                mScoreList.Add(score);
            }
            else
            {
                foreach (string fid in mFilteredUserIds)
                {
                    if (fid.Equals(score.userID))
                    {
                        return mScoreList.Count;
                    }
                }
                mScoreList.Add(score);
            }
            return mScoreList.Count;
        }
`

**Comment by ozdemir08** [comment]
Looks like it's solved in [this issue](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2876) and we are planning to include this in the next release. In the meantime, feel free to use the code in that issue.
