### ISSUE TITLE
The LastModifiedTimestamp have ping inaccuracy

### ISSUE THREAD

**Issue by Kerwis** [playgameservices/play-games-plugin-for-unity#2631]
When i save data, on success, I get, from delivered in callback meta,  LastModifiedTimestamp and save it on device. On next lunch I fetch save, and compare meta i get to saved one, and there are not equal (difference were 580000 (58ms) next time it were 740000 (74ms) I assume that is ping).

**Comment by olehkuznetsov** [comment]
It stores server time as last modified timestamp.
