### ISSUE TITLE
Crash on Social.localUser.Authenticate()

### ISSUE THREAD

**Issue by DimoNline** [playgameservices/play-games-plugin-for-unity#2633]
Unity switched build from internal to gradle, in gradle mode the game crashes on lines

1. `Social.localUser.Authenticate((bool success) => { if (!success) { } });`

2. `if (Social.localUser.authenticated)`

When I remove this lines, app doesn't crash.

Here is some logs:
`20:47:31.330  5784  5817 W Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
07-12 20:47:31.330  5784  5817 W Unity   : 
07-12 20:47:31.351  5784  5817 W Unity   : *** [Play Games Plugin DLL] 07/12/19 20:47:31 +03:00 ERROR: Exception launching token request: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
07-12 20:47:31.351  5784  5817 W Unity   :  
07-12 20:47:31.351  5784  5817 W Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
07-12 20:47:31.351  5784  5817 W Unity   : 
07-12 20:47:31.351  5784  5817 W Unity   : *** [Play Games Plugin DLL] 07/12/19 20:47:31 +03:00 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
07-12 20:47:31.351  5784  5817 W Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
07-12 20:47:31.351  5784  5817 W Unity   :   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <00000000000000000000000000000000>:0 
07-12 20:47:31.351  5784  5817 W Unity   :   at UnityEngine.AndroidJavaObject._CallStatic[ReturnType] (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0 
07-12 20:47:31.351  5784  5817 W Unity   :   at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00000] in <00000000000000000000000000000000>:0 
07-12 20:47:31.351  5784  5817 W Unity   :   at GooglePlayGames.Android.AndroidTokenClient.DoFetchToken (System.Boolean silent, System.Action`1[T] callback) [0x00000] in <00000000000000000000000000000000>:0 
07-12 20:47:31.351  5784  5817 W Unity   :   at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
07-12 20:47:31.351  5784  5817 W Unity   :   at GooglePlayGames.OurUtils.PlayGamesHelpe
07-12 20:47:31.357   596  1186 D asd_primary_out: L[3]-80.766574db, R[4]-78.267799db
07-12 20:47:31.397   684   684 I aptouch_daemon: filter_touch_detect, all_touch_up
07-12 20:47:31.400  1423  1559 D fingerTest: event.x=:1329.4319 event.y=:550.4903
07-12 20:47:31.400  1423  1559 D fingerTest: MotionEvent.ACTION_UP
07-12 20:47:31.405   684   684 I aptouch_daemon: filter_touch_detect, down, in: 1, out: 1
07-12 20:47:31.406  1423  1559 D fingerTest: event.x=:1079.5387 event.y=:550.4903
07-12 20:47:31.406  1423  1559 D fingerTest: MotionEvent.ACTION_DOWN
07-12 20:47:31.438   684   684 I aptouch_daemon: filter_touch_detect, all_touch_up
07-12 20:47:31.439  1423  1559 D fingerTest: event.x=:1079.5387 event.y=:550.4903
07-12 20:47:31.439  1423  1559 D fingerTest: MotionEvent.ACTION_UP
07-12 20:47:31.451  5784  5817 I Unity   : Starting Auth with token client.
07-12 20:47:31.463  5784  5817 W Unity   : *** [Play Games Plugin DLL] 07/12/19 20:47:31 +03:00 ERROR: ShowAchievementsUI can only be called after authentication.
07-12 20:47:31.463  5784  5817 W Unity   :  
07-12 20:47:31.463  5784  5817 W Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
07-12 20:47:31.463  5784  5817 W Unity   : 
07-12 20:47:31.476   596  1186 D asd_primary_out: L[4]-78.267799db, R[2]-84.288399db
07-12 20:47:31.484  5784  5817 I Unity   : Starting Auth with token client.
07-12 20:47:31.485  5784  5817 W Unity   : *** [Play Games Plugin DLL] 07/12/19 20:47:31 +03:00 ERROR: Exception launching token request: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
07-12 20:47:31.485  5784  5817 W Unity   :  
07-12 20:47:31.485  5784  5817 W Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
07-12 20:47:31.485  5784  5817 W Unity   : 
07-12 20:47:31.485  5784  5817 W Unity   : *** [Play Games Plugin DLL] 07/12/19 20:47:31 +03:00 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
07-12 20:47:31.485  5784  5817 W Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
07-12 20:47:31.485  5784  5817 W Unity   :   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <00000000000000000000000000000000>:0 
07-12 20:47:31.485  5784  5817 W Unity   :   at UnityEngine.AndroidJavaObject._CallStatic[ReturnType] (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0 
07-12 20:47:31.485  5784  5817 W Unity   :   at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00000] in <00000000000000000000000000000000>:0 
07-12 20:47:31.485  5784  5817 W Unity   :   at GooglePlayGames.Android.AndroidTokenClient.DoFetchToken (System.Boolean silent, System.Action`1[T] callback) [0x00000] in <00000000000000000000000000000000>:0 
07-12 20:47:31.485  5784  5817 W Unity   :   at System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
07-12 20:47:31.485  5784  5817 W Unity   :   at GooglePlayGames.OurUtils.PlayGamesHelpe
07-12 20:47:31.497  5784  5817 W Unity   : *** [Play Games Plugin DLL] 07/12/19 20:47:31 +03:00 ERROR: ShowLeaderboardUI can only be called after authentication.`

**Comment by legas1** [comment]
Did steps mentioned in #2634 helped here too?

**Comment by olehkuznetsov** [comment]
Should be fixed in v0.10.06. Feel free to reopen if it reproduces there.
