### ISSUE TITLE
Social.localUser.Authenticate Crash (logs)

### ISSUE THREAD

**Issue by DimoNline** [playgameservices/play-games-plugin-for-unity#2634]
The android Unity game crashes on line `Social.localUser.Authenticate((bool success) => {});`

**Logs:**
07-13 13:54:38.583  1423  1392 W DropBoxManagerService: Dropping: data_app_crash (10 > 0 bytes)
07-13 13:54:38.586  1933  1933 E HwModemCapability: isCapabilitySupport java.lang.StringIndexOutOfBoundsException: length=7; index=7
07-13 13:54:38.586  1423  1676 E ActivityManager: The same pid with last one, do not add dropbox and clear mLastCrashedPid. mLastAppCrashedPid==1167
07-13 13:54:38.587  1423  1676 W ActivityManager:   finishTopCrashedActivityLocked Force finishing activity com.LightGameStudio.Pirates/com.unity3d.player.UnityPlayerActivity

07-13 13:54:38.665  1853  3330 D WorkSource: Insert in WorkSource{} @ 0 uid 10021 name com.google.android.gms
07-13 13:54:38.673  1853  3330 D WorkSource: Insert in WorkSource{} @ 0 uid 10021 name com.google.android.gms
07-13 13:54:38.688  1953 27157 D HwRecentsTaskUtils: refreshToCache
07-13 13:54:38.688  1953 27157 D HwRecentsTaskUtils: searchFromDate
07-13 13:54:38.689  1853  3330 D WorkSource: Insert in WorkSource{} @ 0 uid 10021 name com.google.android.gms
07-13 13:54:38.699  1825  1839 E HsmCoreServiceImpl: onTransact in code is: 103
07-13 13:54:38.699  1825  1839 I MediaProcessHandler: playingUids: 
07-13 13:54:38.703  1853  3330 D WorkSource: Insert in WorkSource{} @ 0 uid 10021 name com.google.android.gms
07-13 13:54:38.704  1953 27157 I RecentsTaskLoadPlan: to show tasks size is 1
07-13 13:54:38.734  1741  1741 I PhoneStatusBarView: mDelayedGetViewPositionOnScreen getLocationInWindow 90 0
07-13 13:54:38.734  1741  1741 I PhoneStatusBarView: mDelayedGetViewPositionOnScreen getLocationOnScreen 90 0
07-13 13:54:38.746  1423  1558 W InputDispatcher: channel '5089c3f com.LightGameStudio.Pirates/com.unity3d.player.UnityPlayerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-13 13:54:38.746  1423  1558 E InputDispatcher: channel '5089c3f com.LightGameStudio.Pirates/com.unity3d.player.UnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-13 13:54:38.747  1423  6693 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=768, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10329] ], android.os.BinderProxy@15b230b)
07-13 13:54:38.747  1423  4298 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=769, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND Uid: 10329] ], android.os.BinderProxy@dfd75e8)
07-13 13:54:38.747  1423  2333 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=766, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10329] ], android.os.BinderProxy@8481401)
07-13 13:54:38.747  1423  4298 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=767, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND Uid: 10329] ], android.os.BinderProxy@68f02a6)
07-13 13:54:38.747  1423  2333 D MediaRouterService: Client com.LightGameStudio.Pirates (pid 1167): Died!
07-13 13:54:38.748  1423  2333 I ActivityManager: Process com.LightGameStudio.Pirates (pid 1167) has died: vis  +99TOP

**Comment by DimoNline** [comment]
Tried to use this method https://github.com/playgameservices/play-games-plugin-for-unity/issues/1604#issuecomment-280850233, but there appeared 792 errors.
![image](https://user-images.githubusercontent.com/19239834/61171701-12baaa00-a584-11e9-9b72-79d5e37cb7a2.png)
![image](https://user-images.githubusercontent.com/19239834/61171702-2534e380-a584-11e9-8bfb-8668fbae1e32.png)

**Comment by DimoNline** [comment]
The earlier GPG versions are incompatible with Unity 2019.1.8

**Comment by legas1** [comment]
Hello, please try following steps:
1. Delete every .aar file in Plugins/Android.
2. In menu: Assets -> Play Services Resolver -> Android Resolver -> Force resolve.

Then try to build your game and post results here.

**Comment by DimoNline** [comment]
@legas1 
Still crashes, here is logs of this part:


Shutting down VM
 E AndroidRuntime: FATAL EXCEPTION: main
 E AndroidRuntime: Process: com.LightGameStudio.Pirates, PID: 15273
 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArraySet;
 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.GoogleApiManager.<init>(Unknown Source:29)
E AndroidRuntime: 	at com.google.android.gms.common.api.internal.GoogleApiManager.zab(Unknown Source:8)
 E AndroidRuntime: 	at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source:27)
 E AndroidRuntime: 	at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source:51)
 E AndroidRuntime: 	at com.google.android.gms.auth.api.signin.GoogleSignInClient.<init>(Unknown Source:3)
 E AndroidRuntime: 	at com.google.android.gms.auth.api.signin.GoogleSignIn.getClient(Unknown Source:3)
3 E AndroidRuntime: 	at com.google.games.bridge.TokenFragment.buildClient(TokenFragment.java:326)
E AndroidRuntime: 	at com.google.games.bridge.TokenFragment.processRequest(TokenFragment.java:271)
 E AndroidRuntime: 	at com.google.games.bridge.TokenFragment.onResume(TokenFragment.java:400)
...
**Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArraySet" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.LightGameStudio.Pirates-B5wE0R3-F4UtbJE2aB81fg==/base.apk", zip file "/data/app/com.LightGameStudio.Pirates-B5wE0R3-F4UtbJE2aB81fg==/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/com.LightGameStudio.Pirates-B5wE0R3-F4UtbJE2aB81fg==/lib/arm64, /data/app/com.LightGameStudio.Pirates-B5wE0R3-F4UtbJE2aB81fg==/base.apk!/lib/arm64-v8a, /data/app/com.LightGameStudio.Pirates-B5wE0R3-F4UtbJE2aB81fg==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]**

**Comment by legas1** [comment]
This error is probably related to recent AndroidX support. There are two options:

1. Renew every plugin to support AndroidX and enable Jetifier in Resolver.
2. Rollback Resolver dependencies (Dependency XML files) of GPGS to older version (pre-Jetifier).

I will try to post solution ASAP if you don't figure it yourself in meantime.

**Comment by DimoNline** [comment]
@legas1 Thanks a lot, it helped!

**Comment by legas1** [comment]
I'm glad it helped!

For further reference: https://github.com/googlesamples/unity-jar-resolver/issues/241#issuecomment-505036511
