### ISSUE TITLE
Play services giving this error on Android device

### ISSUE THREAD

**Issue by Roy97** [playgameservices/play-games-plugin-for-unity#2643]
[Play Games Plugin DLL] 07/21/19 12:06:19 +05:30 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment 07-21 12:06:19.325 23287 23314 W Unity :

at
UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 07-21 12:06:19.325 23287 23314 W Unity :

at
UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <00000000000000000000000000000000>:0 07-21 12:06:19.325 23287 23314 W Unity :

at
UnityEngine.AndroidJavaObject._CallStatic[ReturnType] (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0 07-21 12:06:19.325 23287 23314 W Unity :

at
UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00000] in <00000000000000000000000000000000>:0 07-21 12:06:19.325 23287 23314 W Unity :

at
GooglePlayGames.Android.AndroidTokenClient.DoFetchToken (System.Boolean silent, System.Action`1[T] callback) [0x00000] in <00000000000000000000000000000000>:0 07-21 12:06:19.325 23287 23314 W Unity :

at
System.Action.Invoke () [0x00000] in <00000000000000000000000000000000>:0 07-21 12:06:19.325 23287 23314 W Unity :

at
GooglePlayGames.OurUtils.PlayGamesHelpe

**Comment by olehkuznetsov** [comment]
Seems as a proguard issue. Should be fixed in v0.10.06 and also check [README.md proguard section](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/README.md#play-games-services-proguard-configuration), please.
