### ISSUE TITLE
Crash on Social.localUser.Authenticate on Unity project

### ISSUE THREAD

**Issue by Giobar97** [playgameservices/play-games-plugin-for-unity#2644]
Two days ago I implemented (or at least I tried to) Google Play Game Services in my Unity Project.
When I run my project in the editor, everything "works fine" (I mean, Social.localUser.Authenticate retrieves false, but that's how it's supposed to work on Unity's editor).
When I run my project in my smartphone (after waiting for hours for Google to publish my update from the Play Console), the game crashes on Social.localUser.Authenticate.

It's been two days, and during this two days I tried EVERYTHING (And I mean really everything) that is recommended in every other post in every site in the whole internet.
I totally can't get it to work properly.

I've read that I had to manually copy inside my Plugins/Android folder the *.aar file needed. I tried and nothing was solved.
I installed a lot of gradle versions. Nothing solved too.
I've read that I had to use Play Services Resolver, but I tried many versions, plugins, unitypackages, and I always the error "Resolution Failed".
In the Unity debugger this is what is logged:

```
Gradle failed to fetch dependencies.

Failed to run 'C:\Users\Giovanni\Documents\Unity Projects\Unity2DLessons\SpaceShooter\Temp\PlayServicesResolverGradle\gradlew.bat -b "C:\Users\Giovanni\Documents\Unity Projects\Unity2DLessons\SpaceShooter\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" --no-daemon "-PANDROID_HOME=C:\Users\Giovanni\AppData\Local\Android\SDK\" "-PTARGET_DIR=C:\Users\Giovanni\Documents\Unity Projects\Unity2DLessons\SpaceShooter\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///C:/Users/Giovanni/Documents/Unity%20Projects/Unity2DLessons/SpaceShooter/Assets/GooglePlayGames/Editor/m2repository" "-PPACKAGES_TO_COPY=com.google.games:gpgs-plugin-support:0.9.64"'
stdout:

> Configure project :
ANDROID_HOME: C:\Users\Giovanni\AppData\Local\Android\SDK" -PTARGET_DIR=C:\Users\Giovanni\Documents\Unity
MAVEN_REPOS: name=maven url=file:/C:/Users/Giovanni/Documents/Unity%20Projects/Unity2DLessons/SpaceShooter/Assets/GooglePlayGames/Editor/m2repository/
MAVEN_REPOS: name=maven2 url=https://maven.google.com
MAVEN_REPOS: name=MavenLocal url=file:/C:/Users/Giovanni/.m2/repository
MAVEN_REPOS: name=BintrayJCenter url=https://jcenter.bintray.com/
MAVEN_REPOS: name=MavenRepo url=https://repo.maven.apache.org/maven2/
PACKAGES_TO_COPY: com.google.games:gpgs-plugin-support:0.9.64
TARGET_DIR: C:\Users\Giovanni\Documents\Unity\ Projects\Unity2DLessons\SpaceShooter\Assets\Plugins\Android
Resolution attempt 1: packages [com.google.games:gpgs-plugin-support:0.9.64]
Resolution attempt: 1, conflicts detected: false, updated packages: false
Resolution attempt 2: packages [com.google.games:gpgs-plugin-support:0.9.64]
version locked packages: [com.android.support:support-annotations:26.1.0, com.android.support:support-compat:26.1.0, com.android.support:support-core-ui:26.1.0, com.android.support:support-core-utils:26.1.0, com.android.support:support-fragment:26.1.0, com.android.support:support-media-compat:26.1.0, com.android.support:support-v4:26.1.0]
non-version locked packages: [com.google.games:gpgs-plugin-support:0.9.64]

stderr:

FAILURE: Build failed with an exception.

* What went wrong:
Project 'Projects\Unity2DLessons\SpaceShooter\Assets\Plugins\Android -PMAVEN_REPOS=file' not found in root project 'PlayServicesResolverGradle'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

exit code: 1

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.<GradleResolution>c__AnonStorey1A:<>m__33(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey1C:<>m__3E()
Google.RunOnMainThread:ExecuteNext()
Google.RunOnMainThread:<ExecuteAll>m__16()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAll()
Google.RunOnMainThread:Run(Action, Boolean)
GooglePlayServices.<GradleResolution>c__AnonStorey1A:<>m__34(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey1A:<>m__35(Result)
GooglePlayServices.ProgressReporter:SignalComplete()
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result)
GooglePlayServices.<RunAsync>c__AnonStorey2:<>m__4()
Google.RunOnMainThread:ExecuteNext()
Google.RunOnMainThread:<ExecuteAll>m__16()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAll()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

And this too:
```
Resolution failed

Failed to fetch the following dependencies:
com.google.games:gpgs-plugin-support:0.9.64


UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.ResolverVer1_1:LogMissingDependenciesError(List`1)
GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey1F:<>m__3A(List`1)
GooglePlayServices.<GradleResolution>c__AnonStorey1A:<>m__33(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey1C:<>m__3E()
Google.RunOnMainThread:ExecuteNext()
Google.RunOnMainThread:<ExecuteAll>m__16()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAll()
Google.RunOnMainThread:Run(Action, Boolean)
GooglePlayServices.<GradleResolution>c__AnonStorey1A:<>m__34(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey1A:<>m__35(Result)
GooglePlayServices.ProgressReporter:SignalComplete()
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result)
GooglePlayServices.<RunAsync>c__AnonStorey2:<>m__4()
Google.RunOnMainThread:ExecuteNext()
Google.RunOnMainThread:<ExecuteAll>m__16()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAll()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

Other things I have implemented in my project are UnityIAP and Unity Advertisements.
I tried to change so many settings I can't even remember how many of them I tried to change.

I've checked out on every google page it came out when I searched each one of the errors I get, I've tried everything, and I think the only thing I haven't still tried is to punch my PC right on the CPU while it's running.
So please, tell me someone has a working solution, I'd rather avoid destroying my PC or get fried by the CPU.

**Comment by legas1** [comment]
Hi, firstly delete all .aar files in Android/Plugin directory and try Force Resolve in Resolver menu. Do you still have this "can't copy plugin aar" error?

**Comment by Giobar97** [comment]
Hi, yes, I keep getting the same error.

**Comment by legas1** [comment]
Do you have this plugin's .srcaar file in "C:/Users/Giovanni/Documents/Unity%20Projects/Unity2DLessons/SpaceShooter/Assets/GooglePlayGames/Editor/m2repository" ? If yes, then I will try to repoduce asap on my local machine. Also it's worth to get latest Resolver from official repo and reimport(+setup via menu) this package again.

**Comment by Giobar97** [comment]
![screen](https://user-images.githubusercontent.com/53182569/61672655-c17d8980-acec-11e9-923c-9c9d80f2b9b3.png)

That's what I have in my folder.

> Also it's worth to get latest Resolver from official repo and reimport(+setup via menu) this package again.

I've alraedy tried that too, as I noticed that the Resolver automatically imported by this plugin wasn't the latest one.
Nothing resolved, neither..

**Comment by legas1** [comment]
Use the latest one. So you have the .srcaar present for 0.9.54?

**Comment by Giobar97** [comment]
I'm sorry, I was just trying with an older version of the plugin and messed up with the screenshot.
Anyway yes, if I use 0.9.53 I have aar files for 0.9.53, if I import 0.9.64 plugin I get 0.9.64 files

**Comment by Giobar97** [comment]
I guess I'll just hit the wall with my head many and many times.

I found the issue, and it's still about space chars in directories.
My Unity projects folder was called "Unity Project", and, as you can see from my first post,
MAVEN_REPOS: name=maven url=file:/C:/Users/Giovanni/Documents/Unity%20Projects/Unity2DLessons/SpaceShooter/Assets/GooglePlayGames/Editor/m2repository/
line is codified correctly with %20 instead of space.

Some lines down the log says 
TARGET_DIR: C:\Users\Giovanni\Documents\Unity\ Projects\Unity2DLessons\SpaceShooter\Assets\Plugins\Android

which is incorrect, as "Unity\ Projects" should have been "Unity Projects" instead.

I solved renaming my folder "UnityProjects", without the space to be sure, and going to my project's folder, then "Temp\PlayServicesResolverGradle", I opened with Block Note gradle.properties and deleted the "%20" in MAVEN_REPOS line and correcting "Unity\ Projects" with "UnityProjects" in TARGET_DIR line.

**Comment by olehkuznetsov** [comment]
Probably, should be fixed in v0.10.06. Feel free to reopen if it crashes there.

**Comment by MartinRouterKing64** [comment]
I am still having this issue

**Comment by Giobar97** [comment]
> 
> 
> I am still having this issue

Honestly, when I had this problem I've completely abandoned Google Play Services and wrote my own sign up/log in system + online savegame system for my game.
I did it in php + MySQL, it's not that hard, so if you still have this issue delete every reference to Google Play Services in your assets folder and write your own system.
People won't be able to log in with their google play games account, but they'll just have to sign up for another account. Anyway you'll learn something new and usefull, and you'll prevent from banging your head against a brick wall for weeks, as I did a year ago when I've had this problem.

**Comment by MartinRouterKing64** [comment]
> > I am still having this issue
> 
> Honestly, when I had this problem I've completely abandoned Google Play Services and wrote my own sign up/log in system + online savegame system for my game.
> I did it in php + MySQL, it's not that hard, so if you still have this issue delete every reference to Google Play Services in your assets folder and write your own system.
> People won't be able to log in with their google play games account, but they'll just have to sign up for another account. Anyway you'll learn something new and useful, and you'll prevent from banging your head against a brick wall for weeks, as I did a year ago when I've had this problem.

Sounds like a good idea, but I really need the silent login with Play Games. I am just doing a simple jump and run game and I think it would kill the game if the users would need to create an account and give their E-mail address just for playing a little game, but it's also important for the game to have a cloud save system and user authentication...

**Comment by olehkuznetsov** [comment]
Can you provide logcat logs for that crash, please?

**Comment by MartinRouterKing64** [comment]
Here is the Log:
[log.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/4918491/log.txt)

Interesting:
-this line in the log: `2020-07-14 13:19:14.164 4630-5425/? W/GLSUser: [DeviceKeyStore] Cannot load key: Device key file not found.` (but maybe it's just an emulator thing and nothing with my game)

-it also says in the log that the authentication succeeded but afterwards the app is crashing.

**Comment by olehkuznetsov** [comment]
It seems authentication succeeds. But Google play services restarts, probably, due crash. Are you running it in emulator?

**Comment by MartinRouterKing64** [comment]
> It seems authentication succeeds. But Google play services restarts, probably, due crash. Are you running it in emulator?
Yes

**Comment by olehkuznetsov** [comment]
It seems as a lot of apps are killed because low memory on device.
Have you tried to use another device emulator with more memory?

2020-07-14 13:19:43.479 232-232/? I/lowmemorykiller: Kill 'com.google.android.configupdater' (6110), uid 10095, oom_adj 955 to free 4588kB; reason: low watermark is breached and thrashing (154%)
2020-07-14 13:19:43.486 232-232/? I/lowmemorykiller: Kill 'com.google.android.setupwizard' (6121), uid 10098, oom_adj 945 to free 4588kB; reason: min watermark is breached even after kill

**Comment by MartinRouterKing64** [comment]
> It seems as a lot of apps are killed because low memory on device.
> Have you tried to use another device emulator with more memory?
> 
> 2020-07-14 13:19:43.479 232-232/? I/lowmemorykiller: Kill 'com.google.android.configupdater' (6110), uid 10095, oom_adj 955 to free 4588kB; reason: low watermark is breached and thrashing (154%)
> 2020-07-14 13:19:43.486 232-232/? I/lowmemorykiller: Kill 'com.google.android.setupwizard' (6121), uid 10098, oom_adj 945 to free 4588kB; reason: min watermark is breached even after kill

I tried two devices with 11GB and 10GB storage and also checked the device settings and it says more than 5GB left.
For some reason I can't create devices with more space.

**Comment by legas1** [comment]
> I tried two devices with 11GB and 10GB storage and also checked the device settings and it says more than 5GB left.
> For some reason I can't create devices with more space.

What about RAM?

**Comment by MartinRouterKing64** [comment]
> > I tried two devices with 11GB and 10GB storage and also checked the device settings and it says more than 5GB left.
> > For some reason I can't create devices with more space.
> 
> What about RAM?

All of the devices that Android studio provides which are able to connect to the google play store (and this is necessary) have 1536MB RAM and looks like there is no way to change this...

**Comment by olehkuznetsov** [comment]
Try this way, please https://stackoverflow.com/questions/40068344/how-can-i-change-the-ram-amount-that-the-android-emulator-is-using

**Comment by MartinRouterKing64** [comment]
That is what I tried before, I cannot edit the RAM size in the advanced settings...

**Comment by olehkuznetsov** [comment]
Here is more ways to modify that setting https://stackoverflow.com/questions/45517553/cant-change-the-ram-size-in-avd-manager-android-studio/45587768

**Comment by MartinRouterKing64** [comment]
This way I can modify the settings of a device but when I don't use the recommended image I am not able to use google play on the device either...
