### ISSUE TITLE
plugin no longer compatible with other google plugins (admob/analytics)

### ISSUE THREAD

**Issue by cataHHH** [playgameservices/play-games-plugin-for-unity#2648]
all other plugins have updated to androidx, this one still uses support libraries, you can't use it anymore if you are planning to have ads or analytics in your project

**Comment by legas1** [comment]
Next release will contain AndroidX support as a workaround you can use older version of their plugins or build from master.

**Comment by cataHHH** [comment]
> Next release will contain AndroidX support, as a workaround you can use older version of their plugins or you can build directly from master.

Any idea when this will be updated ?

**Comment by muhammadadnan0075** [comment]
Hi There, any idea when will be the next release?

**Comment by olehkuznetsov** [comment]
Should be fixed in v0.10.06
