### ISSUE TITLE
Get errors when connecting to Google Play SaveGame

### ISSUE THREAD

**Issue by SuperChest** [playgameservices/play-games-plugin-for-unity#2654]
Hello, In my Unity project I keep getting the same error, even when I try new scripts, or when I re-import Google Play. I hope you can help me

Errors:

GooglePlayGames.OurUtils.Misc.CheckNotNull[T] (.T value) [0x00000] in <filename unknown>:0 

GooglePlayGames.Native.NativeSavedGameClient.ReadBinaryData (ISavedGameMetadata metadata, System.Action`2 completedCallback) [0x00000] in <filename unknown>:0 

GooglePlay.SaveGameOpened (SavedGameRequestStatus status, ISavedGameMetadata meta) [0x00000] in <filename unknown>:0 

GooglePlayGames.OurUtils.PlayGamesHelperObject.Update () [0x00000] in <filename unknown>:0

**Comment by olehkuznetsov** [comment]
It should be fixed in v0.10.06. Can you try it, please. Feel free to reopen if encounter it in that version.
