### ISSUE TITLE
java.net.UnknownHostException: Unable to resolve host "config.uca.cloud.unity3d.com": No address associated with hostname

### ISSUE THREAD

**Issue by samrat2825** [playgameservices/play-games-plugin-for-unity#2656]
07-28 17:55:10.796 24224 24247 E Unity   : java.net.UnknownHostException: Unable to resolve host "config.uca.cloud.unity3d.com": No address associated with hostname
07-28 17:55:10.796 24224 24247 E Unity   :  #0 0xcbc78674 (libunity.so) ? 0x46a674
07-28 17:55:10.796 24224 24247 E Unity   :  #1 0xcc211ab4 (libunity.so) ? 0xa03ab4
07-28 17:55:10.796 24224 24247 E Unity   :  #2 0xcc14dbcc (libunity.so) ? 0x93fbcc
07-28 17:55:10.796 24224 24247 E Unity   :
07-28 17:55:10.796 24224 24247 E Unity   : (Filename:  Line: 451)
07-28 17:55:10.796 24224 24247 E Unity   :
07-28 17:55:10.868 24224 24239 I Unity   : Starting Auth with token client.
07-28 17:55:10.868 24224 24239 I Unity   :  #0 0xcbc78674 (libunity.so) ? 0x46a674
07-28 17:55:10.868 24224 24239 I Unity   :  #1 0xcc211ab4 (libunity.so) ? 0xa03ab4
07-28 17:55:10.868 24224 24239 I Unity   :  #2 0xcbef5b98 (libunity.so) ? 0x6e7b98
07-28 17:55:10.868 24224 24239 I Unity   :  #3 0xcbef5aa0 (libunity.so) ? 0x6e7aa0
07-28 17:55:10.868 24224 24239 I Unity   :
07-28 17:55:10.868 24224 24239 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
07-28 17:55:10.868 24224 24239 I Unity   :
07-28 17:55:10.872 24224 24239 I Unity   : Starting Auth with token client.
07-28 17:55:10.872 24224 24239 I Unity   :  #0 0xcbc78674 (libunity.so) ? 0x46a674
07-28 17:55:10.872 24224 24239 I Unity   :  #1 0xcc211ab4 (libunity.so) ? 0xa03ab4
07-28 17:55:10.872 24224 24239 I Unity   :  #2 0xcbef5b98 (libunity.so) ? 0x6e7b98
07-28 17:55:10.872 24224 24239 I Unity   :  #3 0xcbef5aa0 (libunity.so) ? 0x6e7aa0
07-28 17:55:10.872 24224 24239 I Unity   :
07-28 17:55:10.872 24224 24239 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
07-28 17:55:10.872 24224 24239 I Unity   :
07-28 17:55:11.015 24224 24239 W Unity   : !!! [Play Games Plugin DLL] 07/28/19 17:55:10 +05:30 WARNING: Creating new PlayGamesPlatform
07-28 17:55:11.015 24224 24239 W Unity   :  #0 0xcbc78674 (libunity.so) ? 0x46a674
07-28 17:55:11.015 24224 24239 W Unity   :  #1 0xcc211ab4 (libunity.so) ? 0xa03ab4
07-28 17:55:11.015 24224 24239 W Unity   :  #2 0xcbef5b98 (libunity.so) ? 0x6e7b98
07-28 17:55:11.015 24224 24239 W Unity   :  #3 0xcbef5aa0 (libunity.so) ? 0x6e7aa0
07-28 17:55:11.015 24224 24239 W Unity   :
07-28 17:55:11.015 24224 24239 W Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
07-28 17:55:11.015 24224 24239 W Unity   :
07-28 17:55:11.016 24224 24239 I Unity   :  [Play Games Plugin DLL] 07/28/19 17:55:11 +05:30 DEBUG: Activating PlayGamesPlatform.
07-28 17:55:11.016 24224 24239 I Unity   :  #0 0xcbc78674 (libunity.so) ? 0x46a674
07-28 17:55:11.016 24224 24239 I Unity   :  #1 0xcc211ab4 (libunity.so) ? 0xa03ab4
07-28 17:55:11.016 24224 24239 I Unity   :  #2 0xcbef5b98 (libunity.so) ? 0x6e7b98
07-28 17:55:11.016 24224 24239 I Unity   :  #3 0xcbef5aa0 (libunity.so) ? 0x6e7aa0
07-28 17:55:11.016 24224 24239 I Unity   :
07-28 17:55:11.016 24224 24239 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
07-28 17:55:11.016 24224 24239 I Unity   :
07-28 17:55:11.016 24224 24239 I Unity   :  [Play Games Plugin DLL] 07/28/19 17:55:11 +05:30 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
07-28 17:55:11.016 24224 24239 I Unity   :  #0 0xcbc78674 (libunity.so) ? 0x46a674
07-28 17:55:11.016 24224 24239 I Unity   :  #1 0xcc211ab4 (libunity.so) ? 0xa03ab4
07-28 17:55:11.016 24224 24239 I Unity   :  #2 0xcbef5b98 (libunity.so) ? 0x6e7b98
07-28 17:55:11.016 24224 24239 I Unity   :  #3 0xcbef5aa0 (libunity.so) ? 0x6e7aa0
07-28 17:55:11.016 24224 24239 I Unity   :
07-28 17:55:11.016 24224 24239 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
07-28 17:55:11.016 24224 24239 I Unity   :
07-28 17:55:11.016 24224 24239 I Unity   :  [Play Games Plugin DLL] 07/28/19 17:55:11 +05:30 DEBUG: Creating platform-specific Play Games client.
07-28 17:55:11.016 24224 24239 I Unity   :  #0 0xcbc78674 (libunity.so) ? 0x46a674
07-28 17:55:11.016 24224 24239 I Unity   :  #1 0xcc211ab4 (libunity.so) ? 0xa03ab4
07-28 17:55:11.016 24224 24239 I Unity   :  #2 0xcbef5b98 (libunity.so) ? 0x6e7b98
07-28 17:55:11.016 24224 24239 I Unity   :  #3 0xcbef5aa0 (libunity.so) ? 0x6e7aa0
07-28 17:55:11.016 24224 24239 I Unity   :
07-28 17:55:11.016 24224 24239 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
07-28 17:55:11.016 24224 24239 I Unity   :
07-28 17:55:11.017 24224 24239 I Unity   :  [Play Games Plugin DLL] 07/28/19 17:55:11 +05:30 DEBUG: Creating Android IPlayGamesClient Client
07-28 17:55:11.017 24224 24239 I Unity   :  #0 0xcbc78674 (libunity.so) ? 0x46a674
07-28 17:55:11.017 24224 24239 I Unity   :  #1 0xcc211ab4 (libunity.so) ? 0xa03ab4
07-28 17:55:11.017 24224 24239 I Unity   :  #2 0xcbef5b98 (libunity.so) ? 0x6e7b98
07-28 17:55:11.017 24224 24239 I Unity   :  #3 0xcbef5aa0 (libunity.so) ? 0x6e7aa0
07-28 17:55:11.017 24224 24239 I Unity   :
07-28 17:55:11.017 24224 24239 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
07-28 17:55:11.017 24224 24239 I Unity   :
07-28 17:55:11.753 24224 24239 W Unity   : *** [Play Games Plugin DLL] 07/28/19 17:55:11 +05:30 ERROR: Exception launching token request: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
07-28 17:55:11.753 24224 24239 W Unity   :  #0 0xcbc78674 (libunity.so) ? 0x46a674
07-28 17:55:11.753 24224 24239 W Unity   :  #1 0xcc211ab4 (libunity.so) ? 0xa03ab4
07-28 17:55:11.753 24224 24239 W Unity   :  #2 0xcbef5b98 (libunity.so) ? 0x6e7b98
07-28 17:55:11.753 24224 24239 W Unity   :  #3 0xcbef5aa0 (libunity.so) ? 0x6e7aa0
07-28 17:55:11.753 24224 24239 W Unity   :
07-28 17:55:11.753 24224 24239 W Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
07-28 17:55:11.753 24224 24239 W Unity   :
07-28 17:55:11.753 24224 24239 W Unity   : *** [Play Games Plugin DLL] 07/28/19 17:55:11 +05:30 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
07-28 17:55:11.753 24224 24239 W Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00091] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-28 17:55:11.753 24224 24239 W Unity   :   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00011] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-28 17:55:11.753 24224 24239 W Unity   :   at UnityEngine.AndroidJavaObject._CallStatic[ReturnType] (System.String methodName, System.Object[] args) [0x002d6] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-28 17:55:11.753 24224 24239 W Unity   :   at UnityEngine.AndroidJavaObject.CallStatic[ReturnType] (System.String methodName, System.Object[] args) [0x00001] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-28 17:55:11.753 24224 24239 W Unity   :   at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x0001d] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-28 17:55:11.753 24224 24239 W Unity   :   at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00012] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-28 17:55:11.753 24224 24239 W Unity   :   at UnityEngi
07-28 17:55:11.753 24224 24239 W Unity   : *** [Play Games Plugin DLL] 07/28/19 17:55:11 +05:30 ERROR: Exception launching token request: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
07-28 17:55:11.753 24224 24239 W Unity   :  #0 0xcbc78674 (libunity.so) ? 0x46a674
07-28 17:55:11.753 24224 24239 W Unity   :  #1 0xcc211ab4 (libunity.so) ? 0xa03ab4
07-28 17:55:11.753 24224 24239 W Unity   :  #2 0xcbef5b98 (libunity.so) ? 0x6e7b98
07-28 17:55:11.753 24224 24239 W Unity   :  #3 0xcbef5aa0 (libunity.so) ? 0x6e7aa0
07-28 17:55:11.753 24224 24239 W Unity   :
07-28 17:55:11.753 24224 24239 W Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
07-28 17:55:11.753 24224 24239 W Unity   :
07-28 17:55:11.754 24224 24239 W Unity   : *** [Play Games Plugin DLL] 07/28/19 17:55:11 +05:30 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
07-28 17:55:11.754 24224 24239 W Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00091] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-28 17:55:11.754 24224 24239 W Unity   :   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00011] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-28 17:55:11.754 24224 24239 W Unity   :   at UnityEngine.AndroidJavaObject._CallStatic[ReturnType] (System.String methodName, System.Object[] args) [0x002d6] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-28 17:55:11.754 24224 24239 W Unity   :   at UnityEngine.AndroidJavaObject.CallStatic[ReturnType] (System.String methodName, System.Object[] args) [0x00001] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-28 17:55:11.754 24224 24239 W Unity   :   at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x0001d] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-28 17:55:11.754 24224 24239 W Unity   :   at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00012] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-28 17:55:11.754 24224 24239 W Unity   :   at UnityEngi
07-28 17:55:11.766 24224 24248 E Unity   : java.net.UnknownHostException: Unable to resolve host "cdp.cloud.unity3d.com": No address associated with hostname
07-28 17:55:11.766 24224 24248 E Unity   :  #0 0xcbc78674 (libunity.so) ? 0x46a674
07-28 17:55:11.766 24224 24248 E Unity   :  #1 0xcc211ab4 (libunity.so) ? 0xa03ab4
07-28 17:55:11.766 24224 24248 E Unity   :  #2 0xcc14dbcc (libunity.so) ? 0x93fbcc
07-28 17:55:11.766 24224 24248 E Unity   :
07-28 17:55:11.766 24224 24248 E Unity   : (Filename:  Line: 451)
07-28 17:55:11.766 24224 24248 E Unity   :
07-28 17:55:11.882 24224 24250 E Unity   : java.net.UnknownHostException: Unable to resolve host "cdp.cloud.unity3d.com": No address associated with hostname
07-28 17:55:11.882 24224 24250 E Unity   :  #0 0xcbc78674 (libunity.so) ? 0x46a674
07-28 17:55:11.882 24224 24250 E Unity   :  #1 0xcc211ab4 (libunity.so) ? 0xa03ab4
07-28 17:55:11.882 24224 24250 E Unity   :  #2 0xcc14dbcc (libunity.so) ? 0x93fbcc
07-28 17:55:11.882 24224 24250 E Unity   :
07-28 17:55:11.882 24224 24250 E Unity   : (Filename:  Line: 451)
07-28 17:55:11.882 24224 24250 E Unity   :
07-28 17:55:13.888 24224 24251 E Unity   : java.net.UnknownHostException: Unable to resolve host "cdp.cloud.unity3d.com": No address associated with hostname
07-28 17:55:13.888 24224 24251 E Unity   :  #0 0xcbc78674 (libunity.so) ? 0x46a674
07-28 17:55:13.888 24224 24251 E Unity   :  #1 0xcc211ab4 (libunity.so) ? 0xa03ab4
07-28 17:55:13.888 24224 24251 E Unity   :  #2 0xcc14dbcc (libunity.so) ? 0x93fbcc

This is my logcat. And the code of my c# file is under below.

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;

public class playconsole : MonoBehaviour
{
    public static playconsole play; 

    void Awake()
    {
        play = this;
        DontDestroyOnLoad(gameObject);
    }

    private void Start()
    {
        Debug.Log("In Play Console");
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();

        PlayGamesPlatform.InitializeInstance(config);
        // recommended for debugging:
        PlayGamesPlatform.DebugLogEnabled = true;
        // Activate the Google Play Games platform
        PlayGamesPlatform.Activate();
         
        PlayGamesPlatform.Instance.Authenticate(SignInCallback, true);

        SignIn();
    }

    private void SignIn()
    {
        if (!PlayGamesPlatform.Instance.localUser.authenticated)
        {
            PlayGamesPlatform.Instance.Authenticate(SignInCallback, false);
        }
        else
        {
            // Sign out of play games
            PlayGamesPlatform.Instance.SignOut();
        }
    }

    public void SignInCallback(bool success)
    {
        if (success)
        {
            Debug.Log("(Lollygagger) Signed in!");
        }
        else
        {
            Debug.Log("(Lollygagger) Sign-in failed...");
        }
    }

    #region Achievements

    public void UnlockAchievement(string Id)
    {
        Social.ReportProgress(Id, 30.0f, (bool success) => {

        });

        Social.ReportProgress(Id, 60.0f, (bool success) => {

        });

        Social.ReportProgress(Id, 90.0f, (bool success) => {

        });
    }

    #endregion
    
    #region Leaderboard

    public void AddScoreTotheLeaderboard(long score, string leaderboardId)
    {
        Social.ReportScore(score, leaderboardId, (bool success) =>
        {

        });
    }

    #endregion 
    
}
`

**Comment by samrat2825** [comment]
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;

public class playconsole : MonoBehaviour
{
    public static playconsole play; 

    void Awake()
    {
        play = this;
        DontDestroyOnLoad(gameObject);
    }

    private void Start()
    {
        Debug.Log("In Play Console");
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();

        PlayGamesPlatform.InitializeInstance(config);
        // recommended for debugging:
        PlayGamesPlatform.DebugLogEnabled = true;
        // Activate the Google Play Games platform
        PlayGamesPlatform.Activate();
         
        PlayGamesPlatform.Instance.Authenticate(SignInCallback, true);

        SignIn();
    }

    private void SignIn()
    {
        if (!PlayGamesPlatform.Instance.localUser.authenticated)
        {
            PlayGamesPlatform.Instance.Authenticate(SignInCallback, false);
        }
        else
        {
            // Sign out of play games
            PlayGamesPlatform.Instance.SignOut();
        }
    }

    public void SignInCallback(bool success)
    {
        if (success)
        {
            Debug.Log("(Lollygagger) Signed in!");
        }
        else
        {
            Debug.Log("(Lollygagger) Sign-in failed...");
        }
    }


    #region Achievements

    public void UnlockAchievement(string Id)
    {
        Social.ReportProgress(Id, 30.0f, (bool success) => {

        });

        Social.ReportProgress(Id, 60.0f, (bool success) => {

        });

        Social.ReportProgress(Id, 90.0f, (bool success) => {

        });
    }

    #endregion
    
    #region Leaderboard

    public void AddScoreTotheLeaderboard(long score, string leaderboardId)
    {
        Social.ReportScore(score, leaderboardId, (bool success) =>
        {

        });
    }

    #endregion 
    
}
`

**Comment by legas1** [comment]
#2647

**Comment by samrat2825** [comment]
I have found many .aar files in the plugin folder. Specifically,C:\Users\name\UNITY\gameName\Assets\Plugins\Android

Should I delete all of them?
