### ISSUE TITLE
ERROR: UnityEngine.AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/signin/GoogleSignInAccount;

### ISSUE THREAD

**Issue by samrat2825** [playgameservices/play-games-plugin-for-unity#2661]
07-31 14:48:45.520 23416 23438 W Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
07-31 14:48:45.520 23416 23438 W Unity   :
07-31 14:48:45.521 23416 23438 W Unity   : *** [Play Games Plugin DLL] 07/31/19 14:48:45 +05:30 ERROR: UnityEngine.AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/signin/GoogleSignInAccount;
07-31 14:48:45.521 23416 23438 W Unity   :   at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00041] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-31 14:48:45.521 23416 23438 W Unity   :   at UnityEngine.AndroidJNIHelper.GetMethodID (System.IntPtr javaClass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00001] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-31 14:48:45.521 23416 23438 W Unity   :   at UnityEngine._AndroidJNIHelper.GetMethodID[ReturnType] (System.IntPtr jclass, System.String methodName, System.Object[] args, System.Boolean isStatic) [0x00009] in <f87863d3d6d8426eb49e406f337e22e4>:0
07-31 14:48:45.521 23416 23438 W Unity   :   at UnityEngine.AndroidJNIHelper.GetMethodID[ReturnType] (System.IntPtr jclass, System.String methodName, System.Object[] args, System.Boolean isStatic) [0x00001] in <f87863d3d6d8426eb49e406f337e22e4>:0

**Comment by olehkuznetsov** [comment]
Seems as a proguard configuration issue. You can try to disable proguard to verify it.
