### ISSUE TITLE
API Update every start.

### ISSUE THREAD

**Issue by cyraid** [playgameservices/play-games-plugin-for-unity#2663]
Am I the only one experiencing with 2019.2.0f1, that it shows the api update windows and a "I made a backup" button? (every time I re-open the editor, and open the project)

**Comment by cyraid** [comment]
This still shows up even after I changed those 2 spots for the AndroidJNI.

**Comment by olehkuznetsov** [comment]
Fill free to reopen if it is still an issue with v0.10.06
