### ISSUE TITLE
getting 3 errors on import.  error CS1502: The best overloaded method match for `GooglePlayGames.Native.IClientImpl.SetGravityForPopups(System.IntPtr, Gravity)' has some invalid arguments

### ISSUE THREAD

**Issue by Agent215** [playgameservices/play-games-plugin-for-unity#2672]
The following error messages are thrown after importing to unity 2018.3.11

It works in other projects and in a brand new empty project so it is something else in my project.
I do have the Google VR sdk as well could this be the cause?

Assets/GooglePlayGames/Platforms/Native/NativeClient.cs(587,25): error CS1502: The best overloaded method match for `GooglePlayGames.Native.IClientImpl.SetGravityForPopups(System.IntPtr, Gravity)' has some invalid arguments

Assets/GooglePlayGames/Platforms/Native/NativeClient.cs(587,61): error CS1503: Argument #2' cannot convert GooglePlayGames.BasicApi.Gravity' expression to type `Gravity'

Assets/GooglePlayGames/Platforms/Native/Platforms/Android/AndroidClient.cs(31,20): error CS0535: GooglePlayGames.Native.Android.AndroidClient' does not implement interface member GooglePlayGames.Native.IClientImpl.SetGravityForPopups(System.IntPtr, Gravity)'

**Comment by Agent215** [comment]
The following error messages are thrown after importing to unity 2018.3.11

It works in other projects and in a brand new empty project so it is something else in my project.
I do have the Google VR sdk as well could this be the cause?


Assets/GooglePlayGames/Platforms/Native/NativeClient.cs(587,25): error CS1502: The best overloaded method match for `GooglePlayGames.Native.IClientImpl.SetGravityForPopups(System.IntPtr, Gravity)' has some invalid arguments




Assets/GooglePlayGames/Platforms/Native/NativeClient.cs(587,61): error CS1503: Argument `#2' cannot convert `GooglePlayGames.BasicApi.Gravity' expression to type `Gravity'


Assets/GooglePlayGames/Platforms/Native/Platforms/Android/AndroidClient.cs(31,20): error CS0535: `GooglePlayGames.Native.Android.AndroidClient' does not implement interface member `GooglePlayGames.Native.IClientImpl.SetGravityForPopups(System.IntPtr, Gravity)'

**Comment by alpsaltera** [comment]
The Same Problem. May I question How you solve this problem?

**Comment by Agent215** [comment]
I didn't solve it.

**Comment by alpsaltera** [comment]
> I didn't solve it.

I solved this problem.
It is because another asset has the same class name. my example, Gravity class has been used at the other package so i implicit the class like Google.Basicapi.Gravity( may not be exact name but you will be understood what i say ).  Then the error has gone. ^^*

sorry.  I'm short in english.

But, and Last. however my answer is [ GooglePlayGames.BasicApi.Gravity ]. This is all.

**Comment by olehkuznetsov** [comment]
Thanks for an update.
