### ISSUE TITLE
[v. 0.9.64] GPGS crash on auth on mono backend

### ISSUE THREAD

**Issue by Deepscorn** [playgameservices/play-games-plugin-for-unity#2673]
Game crashes on auth. As it looks from crash stacktrace, error happens in gpg::ScopedLogger::~ScopedLogger(). It reproduced on Samsung Note 3 Android 4.3 and didn't reproduce on Samsung Note 2 Android 4.4.2. Switching from mono backend to il2cpp fixed the problem. So it is only problem with mono. Please, tell me, guys if we can do something about that because we are using mono for testing purposes.

Unity 2018.2.20f1
build.gradle and logs attached

[reproduced.log](https://github.com/playgameservices/play-games-plugin-for-unity/files/3464691/reproduced.log)

[il2cpp_no_repro.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/3464693/il2cpp_no_repro.txt)

[build.gradle.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/3464694/build.gradle.txt)

**Comment by olehkuznetsov** [comment]
Probably already fixed in v0.10.06
