### ISSUE TITLE
Occasional error when trying to login to a Google Play Games

### ISSUE THREAD

**Issue by DeveloperSon** [playgameservices/play-games-plugin-for-unity#2675]
Hello, I am currently serving games in the Google App Store. An error that has not occurred before is detected and interrogated in the recent update.

My users say the game ends abnormally at the start of the game, which is when they request certification for Google Play games. 

I'll attach the detected error statement. Please help me.

+)We are using the latest version of SDK 29 and the Google Play game version is 0.9.64. And the Unity version is 2019.1.12.
---------------------------------------------------------------------------------
InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK

GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build (GooglePlayGames.Native.PInvoke.PlatformConfiguration configRef)
GooglePlayGames.Native.NativeClient.InitializeGameServices ()
GooglePlayGames.Native.NativeClient+<Authenticate>c__AnonStorey0.<>m__0 (Int32 result)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args)
UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, IntPtr jmethodName, IntPtr jargs)
Rethrow as TargetInvocationException: GooglePlayGames.Android.AndroidTokenClient+ResultCallbackProxy.onResult(UnityEngine.AndroidJavaObject)
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args)
UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, IntPtr jmethodName, IntPtr jargs)

**Comment by dvillaseca** [comment]
Bump, same issue using  0.9.64, Unity 2018.4.3f1, SDK 26, scripting backend IL2CPP and .net 3.5

**Comment by DeveloperSon** [comment]
after write, i tryed it. http://lancekun.com/blog/?p=599
but still i be doing take error mail from user... :-(

**Comment by olehkuznetsov** [comment]
Should be fixed in v0.10.06
