### ISSUE TITLE
Cannot sign in to Google Play Games with  PlayGamesPlatform.Instance.Authenticate or Social.localUser.Authenticate

### ISSUE THREAD

**Issue by soccerbob97** [playgameservices/play-games-plugin-for-unity#2678]
![image](https://user-images.githubusercontent.com/46753790/62652331-26f68a80-b929-11e9-9d44-d8b27cba31d7.png)

![image](https://user-images.githubusercontent.com/46753790/62652291-0e867000-b929-11e9-90cc-75759c5e7b71.png)

When I press the sign in button, the signin method gets called and "I am going to signinCallback" get printed but the method signInCallBack does not called. I created credentials for the app and pasted the Upload Certificate SHA-1 code. I ran the project on my phone and nothing happened. What is the next step after pasting the SHA-1 code? Do you have to complete the Oauth consent screen? 
![image](https://user-images.githubusercontent.com/46753790/62653266-3080f200-b92b-11e9-9910-27249fd4d20c.png)

**Comment by soccerbob97** [comment]
The apk from Unity does not let me sign in.

**Comment by soccerbob97** [comment]
![image](https://user-images.githubusercontent.com/46753790/62791722-bde35400-ba9b-11e9-92ff-1b34bfeca3f9.png)
When I try this "start signing in" and "why you no work" does not get printed. Unity basically ignores this Social.localUser.Authenticate. Please someone help!!!!!!!! I am lost!

**Comment by soccerbob97** [comment]
I am getting this error when I connect to google play games. I get a java,lang.ClassNotFoundException: com.google.games.bridge.TokenFragment. PLease HELP!!

**Comment by vipulpatel808** [comment]
Same error, Stuck from last 3 days. No solution found on google. Can someone please help me?

![image](https://user-images.githubusercontent.com/37298782/64100394-5928bb80-cd20-11e9-8e20-cc85508d4d5c.png)

**Comment by olehkuznetsov** [comment]
Seems as a proguard issue, can you try to disable it in you project and try again, please?

**Comment by ozdemir08** [comment]
Closing this issue now. Feel free to reopen it if you still have the issue.
