### ISSUE TITLE
GooglePlayGames sign in don't work on some devices

### ISSUE THREAD

**Issue by ritro** [playgameservices/play-games-plugin-for-unity#2679]
Recently our game got many reviews claiming they can't sign in with Google Play Games. We couldn't understand the origin of the issue until last week my own device got the same error too.
What can be related to the issue:
- I am using OnePlus 5T and last week it received some OS update claiming they applied "Android security patch to 2019.08"
- Google play games received new updated and I installed it (I didn't update for a month due to being abroad so I don't know how many of them were applied at once).

We used **v0.9.64** for a long time now and didn't have any issues so far. Also game on other devices in my office (Pocofone and Huaway Honor 9) still work as expected. I can sign in with google in other games made with Unity from playstore (although I don't know what solution they are using for that) just fine. 

What happens:
When I try to sign in with google the usual window for select google account appears. I can choose the account and animated bar with my avatar appears on top of the phone claiming successful sign in. It is also trying to get the my current avatar from the store with correct link as I see from ADB and then ... in few seconds something occurs and I am not signed in anymore. In ADB I can see this error:
```
ActivityManager: Unable to start service Intent { act=com.google.android.gms.auth.api.signin.RevocationBoundService.clearClientState cmp=com.<i_concealed_bundlename>/bui } U=0: not found
ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@266f18
Unity   : Calling Signout in token client
```
when I try to check authentication with  `PlayGamesPlatform.Instance.IsAuthenticated();`
everything hangs up for a few seconds and the game crash window appears (although I can dismiss it continue playing) with ADB log:
`Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 2.  Wait queue head age: 5866.2ms.)`

I can try to repeat the sign in and every time the same thing happens.
I also saw that for my account achievements are not loaded in GPGs application itself. But I am being able to sign in with google in other games. After clearing caches, reinstalling current version of GPGs app and other google services, clearing data of application etc. I tried to install older version of GPGs app on the phone (from **16.07.2019**) and now everything works again, I can sign in with google in our game too.

**Comment by olehkuznetsov** [comment]
Thanks for reporting. Is it still an issue with current Google Play Services and Google Play Games?

**Comment by ritro** [comment]
Thank you, no. Everything is ok now.
