### ISSUE TITLE
ReportProgress is assuming progress in the range [0..1] while a progress in the range from [0..100] is documented

### ISSUE THREAD

**Issue by beschulz** [playgameservices/play-games-plugin-for-unity#268]
According to http://docs.unity3d.com/ScriptReference/Social.ReportProgress.html progress percentages shall be in the [0..100] range.
Also PlayGamesPlatform.cs talks about percentages in the range [0..100]

But the way the calculations are done assumes, that the percentages are in the range [0..1]:
int targetSteps = (int)(progress * totalSteps);
int numSteps = targetSteps - curSteps;

while it should read:
int targetSteps = (int)(progress/100.0 * totalSteps);
int numSteps = targetSteps - curSteps;

Steps to reproduce:
1.) create an incremental achievement with 1000 steps
2.) setup a unity project with google play for games as the social API
3.) call ReportProgress(..., 50.0, ...)
4.) Notice, that the achievement is unlocked, even though it should be only 50% completed (500 steps).

Solution:
divide the progress parameter by 100.0 the the calculation of targetSteps (PlayGamesPlatform.cs:316)

Workaround:
In the client code, detect if the play games platform is active ( ((PlayGamesPlatform) Social.Active) != null ) and divide the progress by 100.0 before passing it to ReportProgress.

Oh Boy, this one caused me some grief.

**Comment by claywilkinson** [comment]
The latest version of the plugin - 0.9.11 - addresses this.
