### ISSUE TITLE
GetServerAuthCode get null

### ISSUE THREAD

**Issue by hiennm0406** [playgameservices/play-games-plugin-for-unity#2681]
Hi guys,
I have troubles getting the server auth code from Google: GetServerAuthCode() returns null. 

Play Games Plugin version : v0.9.64
Unity: 2019.1.0f2

```
Social.localUser.Authenticate((bool success) =>
 {
       GoogleStatusText.text = "Google Signed In";
       var serverAuthenCode = PlayGamesPlatform.Instance.GetServerAuthCode();
       Test.text = "Server Auth Code: " + serverAuthenCode;
 });
```

p/s. How i can debug on device :P

**Comment by olehkuznetsov** [comment]
Do you have a RequestServerAuthCode(false) PlayGamesClientConfiguration setup?

**Comment by hiennm0406** [comment]
> 
> 
> Do you have a RequestServerAuthCode(false) in a PlayGamesClientConfiguration setup?

yes i hav

PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
.AddOauthScope("profile")
.RequestServerAuthCode(false)
.Build();
PlayGamesPlatform.InitializeInstance(config);

PlayGamesPlatform.DebugLogEnabled = true;
PlayGamesPlatform.Activate();

**Comment by olehkuznetsov** [comment]
Have you specified web auth client id in the plugin setup window? Can you show your logs, please during sign-in?
