### ISSUE TITLE
Exception when loading achievements fails

### ISSUE THREAD

**Issue by smarty-concrete** [playgameservices/play-games-plugin-for-unity#2683]
I've seen this crash come in through Crashlytics

`Non-fatal Exception: java.lang.Exception
NullReferenceException : Object reference not set to an instance of an object.
GooglePlayGames.PlayGamesPlatform+<>c__DisplayClass57_0.<LoadAchievementDescriptions>b__0 (GooglePlayGames.PlayGamesPlatform+<>c__DisplayClass57_0)
System.Action`1[T].Invoke (System.Action`1[T])
System.Action.Invoke (System.Action)
GooglePlayGames.OurUtils.PlayGamesHelperObject.Update (GooglePlayGames.OurUtils.PlayGamesHelperObject)`

I assume this is due to a failure in NativeClient.LoadAchievements:
`if (response.Status() != Status.ResponseStatus.VALID &&
                        response.Status() != Status.ResponseStatus.VALID_BUT_STALE)
                    {
                        GooglePlayGames.OurUtils.Logger.e("Error retrieving achievements - check the log for more information. ");
                        callback(null);
                        return;
                    }`

This calls the callback with null, and the callback in PlayGamesPlatform.LoadAchievementDescriptions does not check for `ach == null` before this: `IAchievementDescription[] data = new IAchievementDescription[ach.Length];`

Unfortunately, I cannot check the log for more information to see _why_ it failed, because Crashlytics does not include all logcat data.

So two issues:
Achievement loading is failing but I can't tell why.
Achievement loading failure causes a null reference exception.

**Comment by olehkuznetsov** [comment]
Please try v0.10.06 it should be fixed there. Also check if you have linked you app correctly in play console.
