### ISSUE TITLE
The plugins is doing nothing

### ISSUE THREAD

**Issue by Electroblade** [playgameservices/play-games-plugin-for-unity#2689]
When I ran the game on my emulator the google play store sign in box showed up, indicating that the authenticate worked, but nothing else worked. I added buttons to call up the leaderboards and achievements with: Social.ShowAchievementsUI(); and Social.ShowLeaderboardUI(); respectively. They didn't do anything. 

I went through everything and double checked everything and saw that the Java Environmental variables was not setup in windows. I added them and rebooted. Now nothing is showing not even the google authenticate. 

I removed the Plugin and imported it again. I even updated to the new version. I know I must be missing something, but don't know what.

_Originally posted by @Electroblade in https://github.com/playgameservices/play-games-plugin-for-unity/issues/2589#issuecomment-523200413_

**Comment by olehkuznetsov** [comment]
Have you tried to build and run samples?
