### ISSUE TITLE
Unsuccessful case process for Google+ Login on iOS

### ISSUE THREAD

**Issue by yacmh** [playgameservices/play-games-plugin-for-unity#269]
Hello,

I am currently working on implementing Google+ Login via the Unity3D engine.

I used the “Social.localUser.Authenticate” method but the result is different on Android and iOS. On Android, I get the expected result for login success, failure, and cancellation.
On iOS, I get the expected result for login success but not for failure and cancellation.

Consequently, I’m unable to show an appropriate message to the user when login has failed or was cancelled.

Does anyone else have this issue? If it’s coming from Google, is there a plan for resolving it?

Thank you.

**Comment by mrggl** [comment]
Are you still seeing this with the latest plugin version (i.e. >= 0.9.10)?

**Comment by claywilkinson** [comment]
Can you post what's being captured in the log when you sign on unsuccessfully in iOS?

**Comment by Eomono** [comment]
Just tried with the latest plugin version, the issue has been fixed :) Thank you!

**Comment by claywilkinson** [comment]
Great News! Thanks for the update!
