### ISSUE TITLE
aar file Not generated. or Crash

### ISSUE THREAD

**Issue by tonaos** [playgameservices/play-games-plugin-for-unity#2692]
GooglePlayGamePlugins_unity 0.9.64
Firebase_unity 6.2.2
GoogleMobileAds_unity 3.18.3

play-services-resolver = v1.2.124.0

![image](https://user-images.githubusercontent.com/54434992/63578775-1d794d80-c5cc-11e9-982f-f3bbc86c6619.png)
->
![image](https://user-images.githubusercontent.com/54434992/63578729-0aff1400-c5cc-11e9-8d4e-e6a8e31a8fa9.png)
->
![image](https://user-images.githubusercontent.com/54434992/63578635-dbe8a280-c5cb-11e9-9802-00c69763975a.png)
->
aar file Not generated.

![image](https://user-images.githubusercontent.com/54434992/63578792-28cc7900-c5cc-11e9-9173-0ea213170d55.png)
->
![image](https://user-images.githubusercontent.com/54434992/63578729-0aff1400-c5cc-11e9-8d4e-e6a8e31a8fa9.png)
->
aar file generated.
->
android build
->
![image](https://user-images.githubusercontent.com/54434992/63580114-0e47cf00-c5cf-11e9-8d49-448d6b46cf82.png)
crash

**Comment by ceceomer** [comment]
I have same issue! Did you find solution? @tonaos

**Comment by tonaos** [comment]
> I have same issue! Did you find solution? @tonaos

not yet

**Comment by tonaos** [comment]
> I have same issue! Did you find solution? @tonaos

Android 6.0 (API 23) (this does not affect the min SDK version).

**Comment by tonaos** [comment]
> I have same issue! Did you find solution? @ceceomer

Android 6.0 (API 23) (this does not affect the min SDK version).

**Comment by PetrKarbula** [comment]
I am having the same issue. App is crashing on start with:
`java.lang.ClassNotFoundException: Didn't find class com.google.android.gms.auth.api.signin.GoogleSignIn`

my dependencies:
![image](https://user-images.githubusercontent.com/1983580/65518673-f40e5300-dee4-11e9-8e6c-dd03757a555a.png)

no custom gradle template

Unity 2018.4.9f1
GPGS 0.9.64

**Comment by olehkuznetsov** [comment]
Should be fixed in v0.10.06 as we updated Play Resolver version as well.
