### ISSUE TITLE
Problem with authorization and saved games

### ISSUE THREAD

**Issue by frolky** [playgameservices/play-games-plugin-for-unity#2697]
After updating the application, some players encounter an error connecting to Google Play or an error loading a saved game, or these actions are performed indefinitely. The reason is unknown. There are options why this could happen? There are definitely no mistakes on my part.

**Comment by olehkuznetsov** [comment]
Which plugin version do you use?

**Comment by frolky** [comment]
> Which plugin version do you use?
0.9.64

**Comment by olehkuznetsov** [comment]
Is it still an issue? Feel free to reopen if it happens for new plugin v0.10.06, please.
