### ISSUE TITLE
How to check if player is first time logged.

### ISSUE THREAD

**Issue by ZdravPrav** [playgameservices/play-games-plugin-for-unity#2699]
It is possible to know if user is the first time using google play account on my application?
**I am not using local save** in case of swapping accounts.

**Comment by olehkuznetsov** [comment]
Why do you need to detect it?

**Comment by ZdravPrav** [comment]
> Why do you need to detect it?

To initialize new game, obviously something must happen when there is no load data(e.g when swapping from one account to account that have no data, it will need to detect it and create "default"

**Comment by ZdravPrav** [comment]
> Yes! It can be found in the documentation.
> See here: https://github.com/playgameservices/play-games-plugin-for-unity#player-statistics
> That then says to go here: https://developers.google.com/games/services/android/stats
> Where you can access a stat called "number of sessions".

Actually I made mistake in explanation...
The real question Is it possible to detect there is no save data in that account.
And I tried if(saveBytes==null||saveBytes.Lenght==0) and it is working (I hope it's properly way)

**Comment by exzizt** [comment]
> > Yes! It can be found in the documentation.
> > See here: https://github.com/playgameservices/play-games-plugin-for-unity#player-statistics
> > That then says to go here: https://developers.google.com/games/services/android/stats
> > Where you can access a stat called "number of sessions".
> 
> Actually I made mistake in explanation...
> The real question Is it possible to detect there is no save data in that account.
> And I tried if(saveBytes==null||saveBytes.Lenght==0) and it is working (I hope it's properly way)

Great! Perhaps close the issue then if it is solved.
