### ISSUE TITLE
InvalidCastException on (PlayGamesLocalUser)Social.localUser

### ISSUE THREAD

**Issue by LeoAlmeida-CF** [playgameservices/play-games-plugin-for-unity#2700]
Hello everyone!

I'm trying to use the Google Play Games Plugin for Unity and followed all instructions, I even looked for several tutorials on the web, and also updated to the latest version (actually 0.10.01). But my problem persists.
I can't get a unique UserId.

According to the instructions, all we need to do is: `PlayGamesClientConfiguration.Builder.RequestIdToken();`
and
`((PlayGamesLocalUser) Social.localUser).GetIdToken();`

My problem is, the sample code just doesn't work! The cast fail with the following error in this line: **InvalidCastException: Specified cast is not valid.**

Here's my actual code:
```
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().RequestIdToken().Build();
PlayGamesPlatform.InitializeInstance(config);
 
PlayGamesPlatform.DebugLogEnabled = true;
PlayGamesPlatform.Activate();
```
And I authenticate with:
```
Social.localUser.Authenticate(SignedIn);
 
private void SignedIn(bool sucess)
{
    if (sucess)
    {
        Debug.Log("Sucess on Sign in!");
    }
}
```
Authentication returns success but does not display that Google Play login popup during gameplay (testing on my phone), installed by Google Play (actually in closed tests).

Since I can't cast as in the manual, I tried several other ways, but nothing works! Already tryed:

```
Social.localUser.id
Social.Active.localUser.id
PlayGamesPlatform.Instance.localUser.id
PlayGamesPlatform.Instance.GetUserId()
```
All i got is a "default id 1000" if i checked Social.localUser.id instantly, and null if i try to consult this variable further.
I simply cannot get the authenticated user ID. And there are no errors in logcat...

My Unity Version is 2019.2.1f1.
Can anybody help me?

**Comment by olehkuznetsov** [comment]
Have you tried minimal sample?
Social.localUser.id should be fine to get unique user id.

**Comment by nmtoan91** [comment]
I got the same error today just by using the sample code
