### ISSUE TITLE
Posting a Score to a Leaderboard problem (Social.ReportScore)

### ISSUE THREAD

**Issue by DrVallo** [playgameservices/play-games-plugin-for-unity#2711]
I'm having trouble sending a score to the leaderboard.
I can tell you that I connected correctly to PlayGames because the achievements are unlocked correctly. The "Social.ShowLeaderboardUI" function also works perfectly.
This is my actual code:

public class PlayGames : MonoBehaviour :
```
public static void AddScoreLeaderboard(string id, long score)
    {
        Social.ReportScore(score, id, (bool success) => { });
    }
    public static void ShowLeaderboardUI()
    {
        PlayGamesPlatform.Instance.ShowLeaderboardUI(GPGSIds.leaderboard_game);
    }
```
This is the command I use to send the code to the leaderboard:
```PlayGames.AddScoreLeaderboard(GPGSIds.leaderboard_game, MenuController.gameScore);```

Each time I submit the score, the leaderboard is always empty.
I use the latest version of the PlayGames plugin.

**Comment by JokePenny** [comment]
@DrVallo  how you solved it?
