### ISSUE TITLE
Unable to load 'gpg': The specified module could not found

### ISSUE THREAD

**Issue by brijesh-brk** [playgameservices/play-games-plugin-for-unity#2713]
Editor: Unity 2019.2.3f1  and Unity-2018.3.0f2
Scriptiong backend: IL2CPP
Target Architecure:    ARMv7, ARM64
Target Plateform: Android

**Comment by olehkuznetsov** [comment]
Try to use v0.10 plugin from [here](https://github.com/playgameservices/play-games-plugin-for-unity/blob/android-java-client/current-build/)

**Comment by brijesh-brk** [comment]
I dont know the above solution is the solution of my issues or not but
I follow the below step to resolve it

Step 1: First of all I remove all content from my project's Assest Folder
Step 2: Import gpgs plugin v0.10
Step 3: Resolve dependencies form Assest>Play Service Resolver> Android > Resolve , it include all required .aar file in my project
Step 4: Build and Run work smothly.

And then I put all content that i were removed.
Now my project work smothly.
Thanks.
