### ISSUE TITLE
App Crash when load from cloud UI is triggered

### ISSUE THREAD

**Issue by salvobunetto** [playgameservices/play-games-plugin-for-unity#2716]
Hello, my game crashes and closes when I try to download a cloud save via the Native UI of Google Play Games and many times crash even at startup

Plugin Version: 10.03

I attach the full logcat.

[2019-09-06-11-29-00.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/3583402/2019-09-06-11-29-00.txt)

**Comment by ozdemir08** [comment]
Have you tried v10.01 and v10.02 before? Did it happen for the first time in 10.03?

**Comment by salvobunetto** [comment]
@ozdemir08 Yes, i tried from 0.9.64 to 10.03 One by one version

Another oddity is that it does not ask me to install play games when it is not installed on the device. ( app exit with crash: no package founded )

I also use the latest OneSignal plugin with the fix they indicated on the custom gradle if this can help

**Comment by ozdemir08** [comment]
I think things are a bit tricky as you're using android Kindle Fire HDX. Looking at the logcat, your device not having Play Games app, was detected but apparently it can't force you to install it. Do you have Play Store installed on your device? Another question, does using an older version also result in not forcing to install Play Games app?

**Comment by salvobunetto** [comment]
@ozdemir08 it's been several years that I use this device to do the tests (I always installed play games with the dedicated apk and it always worked), also I also use HTC One S to do tests with rom Stock, both have the same error (they do not ask to install play games  when it is not installed ), with the version published on play store ( Unity 5 ) on both devices everything works correctly, after switching to Unity 2019.1.14 and updating the plugins ( OneSignal and Play Games ) ie up with these issues, at the beginning the popup appeared when I was using 10.01 but on some devices I found errors, so I updated at 10.03 (because I saw that it had a bug that was readily fixed precisely with this last version ) after which nothing more worked

I tried to delete the plugin, to import the various versions, to use the custom gradle template or to download the libraries (which seem to be downloaded all, AndroidX included ) with the play resolve ( also force resolve ) but nothing.
When I sign in on HTC One S I can't sign in, while on the Kindle you (with customRom Android Stock ), but on both when I don't play games installed crash when I open the UI to save/load the game.

**Comment by ozdemir08** [comment]
1. In order the plugin to be able to ask you to install Play Games app, you need to have "Google Play Services" installed on your device. Can you verify that it is installed? 

2. Do you see any logs from [this code block](https://github.com/playgameservices/play-games-plugin-for-unity/blob/android-java-client/source/PluginDev/Assets/GooglePlayGames/Platforms/Android/AndroidSavedGameClient.cs#L239-L291)? Also, using **Debug.Log("message")**, can you check what line is causing the error in PlayGamesHelperObject.Update method?

**Comment by salvobunetto** [comment]
1 - With my main ( Tester ) device HTC One S Play Service is version installed with version 19.2.74 (000304-265167076), my testers confirm play service work with other game on other devices ( Kindle, Moto G4 )

2 - Error is after commitAndClose.succeed I think he follows [this call](https://github.com/playgameservices/play-games-plugin-for-unity/blob/f7404f83b626f628326ad898755930e53d3274bf/source/PluginDev/Assets/GooglePlayGames/Platforms/Android/AndroidSavedGameClient.cs#L279-L280)

**Comment by ozdemir08** [comment]
> 2 - Error is after commitAndClose.succeed I think he follows this call

This one is previously mentioned [in this comment](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2687#issuecomment-525856249). I managed to reproduce it, please check out [this commit ](https://github.com/ozdemir08/play-games-plugin-for-unity/commit/a5acb995e8700850505b1d78e2667b114040e48f) and let me know if it solves that issue.



> [Play Games Plugin DLL] 09/10/19 23:55:49 +02:00 ERROR: Exception launching token request: java.lang.ClassNotFoundException: com.google.games.bridge.HelperFragment

This is a totally different thing and it's unrelated to the previous one. If HelperFragment is not found, then you cannot sign in, see any ui or make any calls. But in the previous one, being able to sign in and seeing saved games ui before crash means you have HelperFragment. I guess you tried something about proguard configs while getting this error. 



> EDIT 3: Tried with Mono and with Android Studio SDK ( Without Proguard ), I can reproduce one bug by selecting (+) icon when i save a game

I checked this log. This is aligned with the first one. `09-11 08:32:32.783 E/Unity   (5878): NullReferenceException: Object reference not set to an instance of an object.
09-11 08:32:32.783 E/Unity   (5878):   at GooglePlayGamesManager.SavedGameSelected (GooglePlayGames.BasicApi.SavedGame.SelectUIStatus status, GooglePlayGames.BasicApi.SavedGame.ISavedGameMetadata game) [0x00000] in <00000000000000000000000000000000>:0 
`.

**Comment by salvobunetto** [comment]
> This one is previously mentioned [in this comment](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2687#issuecomment-525856249). I managed to reproduce it, please check out [this commit ](https://github.com/ozdemir08/play-games-plugin-for-unity/commit/a5acb995e8700850505b1d78e2667b114040e48f) and let me know if it solves that issue.

I tried but nothing has changed

**Comment by salvobunetto** [comment]
After days I found the problem, the old version returns game with null filename while the new version returns a null game directly.

PS. Thanks for OneSignal fix
