### ISSUE TITLE
Resolution failed while Resolving Android Dependencies

### ISSUE THREAD

**Issue by jaybatalla** [playgameservices/play-games-plugin-for-unity#2719]
How can I fixed this error while resolving android dependencies in Unity3D, I am using Unity 2019.2.1? 

"Resolution failed

Failed to fetch the following dependencies:

com.google.games:gpgs-plugin-support:0.9.64 "

**Comment by Eugen1344** [comment]
We have a similar issue. Has anybody found a solution yet?

**Comment by olehkuznetsov** [comment]
It should be fixed in v0.10.06. Can you check it, please?
