### ISSUE TITLE
Looping choose account screen

### ISSUE THREAD

**Issue by SarahAlazab** [playgameservices/play-games-plugin-for-unity#272]
When I login from a mobile that have one google account it log in fine but when there is more than one account it displays the choose account screen and when I choose an account it shows the same screen again and again and doesn't log in at all. In my search I found the same issue with others but no body could solve it. Any body can help me with this?

**Comment by mrggl** [comment]
Is this still occurring with the newer versions of the plugin?

**Comment by claywilkinson** [comment]
Closing as a duplication of #109  - please update that thread if there are still issues.
