### ISSUE TITLE
Error NOT_AUTHORIZED and sha1 fingerprints

### ISSUE THREAD

**Issue by 2rusbekov** [playgameservices/play-games-plugin-for-unity#2720]
Hi. I noticed that many issues with this error, and I got same. I'am using google app singing + app bundles. So i checked sha1 fingerprints at google console and from downloaded app from play market: they are was different. 

what I made: I added 2 additional OAuth ids, 1 with sha1 from downloaded app, and second with sha1 of my upload key. And now I'm able to authorize within apps from play market and my local "run" builds. 

Is this good? Or may I encounter some problems in future?

ps: v0.9.64 and unity 2019.2

**Comment by eirikost** [comment]
I think that sounds good as long as you created the client ids from google play console with linked apps and [not from the api console](https://developers.google.com/games/services/console/enabling). Alternatively you could change the fingerprint on your existing client id in the api console, but then the service wouldn't work for old installs.

**Comment by 2rusbekov** [comment]
First id was created from google play console, I left it unchanged. Other 2 I created manualy at google api console.

**Comment by eirikost** [comment]
> Warning: Do not create new client IDs for your game from the Google API Console. If you do so, Google Play games services will not associate your game settings with the client ID, and this could cause errors during gameplay.

I don't know if there will be any problem because of this, but the documentation from Google seems pretty clear that you shouldn't. It's not too late to change if you want to change though.

**Comment by 2rusbekov** [comment]
But authorization doesn't work without them. What I shoul do? Ok with my local build, because they signed with my upload key, but app (from appbundle) downloaded from google play also has NOT_AUTHORIZED  issue.

**Comment by eirikost** [comment]
Can't you create a new link from in Google play console under "Linked apps" so that it makes a client ID automatically? And then you make sure that the upload certificate SHA-1 fingerprint in Google API console is the same as in Google play console for the ones that was just created. I just did it with my application when changing to app bundle.
