### ISSUE TITLE
Can't implement play games

### ISSUE THREAD

**Issue by Joshi234** [playgameservices/play-games-plugin-for-unity#2721]
Hi,
I have a problem:
I tried to implement play games, but when I add the ressources, I just get an error that says that it can't parse the xml data(I'm sure that I copied it from the play console) and that it can't find sdk  Tools(I have the standard Unity android Installation). When I build my app i get an dialog who says. Warning,Google Play Games isn't conifgured correctly, but the game works just when I try to login nothing happens

**Comment by salvobunetto** [comment]
Make sure that the xml file looks like this

```
<?xml version="1.0" encoding="utf-8"?>
<!--
Google Play game services IDs.
Save this file as res/values/games-ids.xml in your project.
-->
<resources>
  <!-- app_id -->
  <string name="app_id" translatable="false">YOUR_APP_ID</string>
  <!-- package_name -->
  <string name="package_name" translatable="false">YOUR_PACKAGE_NAME</string>
  <!-- achievement NAME-->
  <string name="achievement_NAME" translatable="false">ACHIEVEMENT_UNIQUE_ID</string>
</resources>
```

**Comment by Joshi234** [comment]
It looks exactly like this

**Comment by salvobunetto** [comment]
Try to change Constants class name for example " YOUR_GAME_NAME_GPGSIds"

**Comment by Joshi234** [comment]
Thanks for your reply but I think it has something to do with the standard sdk tools from unity

**Comment by Joshi234** [comment]
Finally I found the problem by myself: The Unity SDK has a bug so it isn't possible to use it for play games, you need just to install android studio and locate it
