### ISSUE TITLE
AndroidX Dependency Still Remain in Version 10.03

### ISSUE THREAD

**Issue by sadegh021** [playgameservices/play-games-plugin-for-unity#2723]
Hi,
I Update my google play game plugin from 10.01 to version 10.03 and after Delete old resolved dependencies and exe force resolve, all androidX..-.aar file back to my plugins folder but you wrote in changelist of version 10.02: Removed AndroidX Dependencies.

**Comment by ozdemir08** [comment]
Yeah, [this commit ](https://github.com/playgameservices/play-games-plugin-for-unity/commit/7341ac667983368377749e0b75139b09404d5653) actually removed this plugin code's dependency on AndroidX but apparently `play-services-auth` depends on AndroidX. Does it cause any problems to you?

**Comment by sadegh021** [comment]
yes, i develop a light app and i only want to use google play game for saving/restoring app data for clients.
My app size is less than 30 MB but currently 12 MB of that is for gpg plugins which is very high for me.
I also use proguard for release, Is there a way to reduce size of included plugins in my final build?

**Comment by ozdemir08** [comment]
12MB is too much for Play Games Services plugin size. I made some tests on plugin size with **IL2CPP** as **script language**, **High** as **the stripping level** and using Proguard. The size contribution of the plugin v10 was less than 0.4MB. 

But I still think that the way you calculate size contribution could be wrong. Even v9.64 does not cause that much size increase. When I built [Smoketest](https://github.com/playgameservices/play-games-plugin-for-unity/tree/android-java-client/samples/SmokeTest) with the configuration above, the size of the apk was less than 10MB even without Proguard.
