### ISSUE TITLE
Game crashing since updating to 0.10

### ISSUE THREAD

**Issue by mkrzaczek** [playgameservices/play-games-plugin-for-unity#2726]
Since updating the plugin, game crashes randomly (on production) with the following callstack (provided by Firebase):
`Caused by java.lang.IllegalStateException
Task is already complete
com.google.android.gms.common.internal.Preconditions.checkState (Unknown Source:29)
com.google.android.gms.tasks.zzu.zzc (Unknown Source:123)
com.google.android.gms.tasks.zzu.setResult (Unknown Source:82)
com.google.android.gms.tasks.TaskCompletionSource.setResult (Unknown Source:8)
com.google.games.bridge.SignInRequest.setSuccess (SignInRequest.java:242)
com.google.games.bridge.SignInRequest.access$000 (SignInRequest.java:28)
com.google.games.bridge.SignInRequest$1.onComplete (SignInRequest.java:117)
com.google.android.gms.tasks.zzj.run (Unknown Source:4)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7050)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:964)`

This is a major problem for us, affecting thousands of users.

**Comment by ozdemir08** [comment]
Have you managed to reproduce it?

**Comment by ozdemir08** [comment]
Also, what game is this?

**Comment by PrieDayThor** [comment]
We also got this issue. 
It appears random. Sometimes everything works sometimes not.

**Comment by mkrzaczek** [comment]
The issue was solved by upgrading few plugins.
`com.google.android.gms:play-services-base` to 17.1.0
`com.google.android.gms:play-services-basement` to 17.1.0
`gpgs-plugin-support` to 0.10.04
