### ISSUE TITLE
[0.9.64] error: resource android:attr/fontVariationSettings not found.

### ISSUE THREAD

**Issue by Diamonds0a** [playgameservices/play-games-plugin-for-unity#2729]
Getting this error when trying to build with 0.9.64
```
Execution failed for task ':bundleReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  C:\chrisstuff\clicker_game\Temp\gradleOut\build\intermediates\incremental\mergeReleaseResources\merged.dir\values\values.xml:355: error: resource android:attr/fontVariationSettings not found.
  C:\chrisstuff\clicker_game\Temp\gradleOut\build\intermediates\incremental\mergeReleaseResources\merged.dir\values\values.xml:355: error: resource android:attr/ttcIndex not found.1
```

The internet is saying that I should use API level 28. However, none of the other plugins that I'm using support API 28. I thought that 9.64 doesn't use androidX??

**Comment by olehkuznetsov** [comment]
Have you tried to remove Play Games services plugin? Not sure if this issue is related to this plugin.

**Comment by Diamonds0a** [comment]
FYI I was able to fix this by using a newer version of https://github.com/googlesamples/unity-jar-resolver. The version that comes with 0.9.64 does not have Jetty.
