### ISSUE TITLE
Autentication Succes but string in Social.localUser.userName is always "Lerpz"

### ISSUE THREAD

**Issue by WILEz75** [playgameservices/play-games-plugin-for-unity#2730]
Hi, as the title suggests, I log in correctly. The icon with the avatar in it appears in the circle above... etc.
But the Social.localUser.userName string always returns me "Lerpz". Why?

**Comment by exzizt** [comment]
Perhaps because that is the user you are logged in as. That property returns the name of the currently signed in/authenticated user, that user happens to be named "Lerpz".

**Comment by Nuuk69** [comment]
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.UI;
using UnityEngine.SocialPlatforms;
using UnityEngine.SceneManagement;

public class GoogleUserManager : MonoBehaviour
{
	public Image img;
	public Text displayName;
	
	void Start()
	{
		DoAuthenticate();
	}
	
	
	internal void DoAuthenticate()
    {
        PlayGamesPlatform.Activate();
        PlayGamesPlatform.Instance.ManuallyAuthenticate(OnSignInResult);
    }

    private void OnSignInResult(SignInStatus signInStatus)
    {
        if (signInStatus == SignInStatus.Success)
        {
           	displayName.text = "" + Social.localUser.userName;			
			StartCoroutine(localImage());
        }
        else
        {
            displayName.text = "*** Failed to authenticate with " + signInStatus;
        }

    }
	
		
	IEnumerator localImage()
	{
		Texture2D tex;
		while(Social.localUser.image == null)
		{
			Debug.Log("IMAGE NOT FOUND!");
			yield return null;
		}
	
		tex = Social.localUser.image;
		img.sprite = Sprite.Create(tex, new Rect(0.0f,0.0f,tex.width, tex.height), new Vector2(0f,0f));
		
	}
	 
}

**Comment by Nuuk69** [comment]
that got it working for me once I updated the oath2 on google play store
