### ISSUE TITLE
Game Services work only for downloaded apps from the store?

### ISSUE THREAD

**Issue by WILEz75** [playgameservices/play-games-plugin-for-unity#2731]
Is it possible to test google services without having to upload and download from the store?

I create the build and open it with an emulator (Nox or Bluestack) but if the app doesn't come from the store it doesn't work as it should.
Obviously I'm connected to the network and I log on the emulator with my google credentials.

Doing a build every time, uploading, downloading ... every single code change to test ... it's really frustrating!

**Comment by olehkuznetsov** [comment]
It can work for directly installed apk. You need to check if you've linked debug SHA1 in play console.

**Comment by WILEz75** [comment]
I do not understand. At what linked my SHA1?

**Comment by exzizt** [comment]
> I do not understand. At what linked my SHA1?

I recommend checking out this link: https://codelabs.developers.google.com/codelabs/playservices_unity/index.html?index=..%2F..index#0

**Comment by tictacf12** [comment]
I have the same problem,
When i was working with the 9.64 version of the plugin, google play services was able to login from directly installed apk. But since i upgraded to 10.04 i couldn't sign in unless the app is downloaded from the store

**Comment by firegate666** [comment]
Make sure you have disabled cheat protection in the game service in the play console. Then you can install the APK directly and use it as long as the signing key is the same as you use for store deployment
