### ISSUE TITLE
Unable to show Video recording overlay on Android 10 (Q)

### ISSUE THREAD

**Issue by JimmyDeemo** [playgameservices/play-games-plugin-for-unity#2733]
I am having a problem loading the Video recording overlay on Android 10. In the project I am working on the video overlay was integrated previously and is working on Android 9 and lower. Upon trying to launch the Video overlay the 'Record your gameplay' screen is shown, offering the quality setting. Upon selecting a quality and selecting 'Launch' there is a dialogue shown that is titled 'Exposing sensitive info during casting/recording', this is shown repeatedly despite pressing 'start now' and the overlay isn't displayed. In the console the following error is spammed:

> 09-20 15:19:18.522  7949  8009 I Unity   :  [Play Games Plugin DLL] 09/20/19 15:19:18 +01:00 DEBUG: Entering internal callback for VideoManager#CaptureStateCallback

I have tried this with the minimal example, adding in the recording test functions on the main github page and get the same result. I am trying to put together a repro project that aunthenitcates without using my companies app details.

Reproduced using 0.9.64 on both Unity 2017.4.26f1 and 2018.4.7.

Please can anyone tell me if they have experienced similar issues?

**Comment by olehkuznetsov** [comment]
Thanks for reporting. I've reproduced it. Not related to Unity plugin, but we will fix.

**Comment by JimmyDeemo** [comment]
Thank you. Is there a workaround at all? Where does the problem lie, with a play services dependency?

**Comment by olehkuznetsov** [comment]
Should be fixed with next Google Play Games update in the middle of October.

**Comment by olehkuznetsov** [comment]
Fixed in Play Games application version 13205

**Comment by JimmyDeemo** [comment]
So I need to instruct anyone to update the Google Play Games app on their device?

**Comment by olehkuznetsov** [comment]
Yes, if it is not auto updated already.

**Comment by andrewio** [comment]
> Yes, if it is not auto updated already.

Hi, I want to start/stop video rec immediately without additional clicks on Capture Overlay UI. Is this possible? So how to hide capture overlay?

**Comment by olehkuznetsov** [comment]
No this is not possible - only user can initiate recording
