### ISSUE TITLE
Does this uses the Google Play Developer API?

### ISSUE THREAD

**Issue by rafaelf82** [playgameservices/play-games-plugin-for-unity#2736]
I'm getting those messages on Google Play.

"We’ve detected that your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available. Update to version 3 before this date."

The only things my project uses are Unity and this plugin, I use the plugin for achievements and save games on cloud.

I cannot figure out what API Google is complaining about, the people at Unity already told me they don't use this API.

edit: I'm using this version: https://github.com/playgameservices/play-games-plugin-for-unity/tree/android-java-client

**Comment by amorato** [comment]
I have the same issue, what will happens with Saved Games? Seems like deprecation because Cloud Firestore... API v3 isn't the solution? what API version have play games actually?

**Comment by manelizzard** [comment]
Same here. Would like to know if this plugin uses the above mentioned deprecated API.

**Comment by frolky** [comment]
The Google Play Developer API is in no way associated with this plugin. It uses the Google Play Game Services API

**Comment by real-mikhail** [comment]
Same issue. And that's also the only plugin I'm using in my unity project. The only service I'm using on backend is "G Suite Marketplace SDK" because Saved Games were not working without that. (and that was suggested workaround: https://github.com/playgameservices/play-games-plugin-for-unity/issues/2429)

**Comment by amorato** [comment]
> The Google Play Developer API is in no way associated with this plugin. It uses the Google Play Game Services API

https://developers.google.com/games/services/android/savedgames

In "Specifying the Drive scope"

**Comment by frolky** [comment]
> > The Google Play Developer API is in no way associated with this plugin. It uses the Google Play Game Services API
> 
> https://developers.google.com/games/services/android/savedgames
> 
> In "Specifying the Drive scope"

Google Drive API != Google Play Developer API

**Comment by ChaosHelme** [comment]
Can someone please clarify this? We're also seeing the message in Google Play Console and need to find out which plugin is causing it.

**Comment by frolky** [comment]
> Can someone please clarify this? We're also seeing the message in Google Play Console and need to find out which plugin is causing it.

Just remove this API from the console. I did it, everything works fine.

**Comment by olehkuznetsov** [comment]
This plugin doesn't use Google Play Developer API, so, as mentioned in [previous comment](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2736#issuecomment-542546591) you can just remove this API from console.
