### ISSUE TITLE
What does this bit from the documentation mean? "Note: the play game services API only supports paging, so retrieving using a high 'from' position will have a performance impact." 

### ISSUE THREAD

**Issue by exzizt** [playgameservices/play-games-plugin-for-unity#2737]
https://github.com/playgameservices/play-games-plugin-for-unity#accessing-leaderboard-data
"Note: the play game services API only supports paging, so retrieving using a high 'from' position will have a performance impact."

What is the performance impact?

**Comment by olehkuznetsov** [comment]
Good question. Seems as deprecated note - now removed.

**Comment by exzizt** [comment]
> Good question. Seems as deprecated note - now removed.

But, it still does only support paging correct? So isn't the note still somewhat valid?

**Comment by olehkuznetsov** [comment]
You can select top or player centered - they are equal in terms of performance. Probably in the past it was possible to specify 'from' as a number.
