### ISSUE TITLE
Didn't find class "com/google/android/gms/games/Games"

### ISSUE THREAD

**Issue by Indovers** [playgameservices/play-games-plugin-for-unity#2739]
I've got this error with some devices (look like it works fine on my phone, but some devices trigger this error):

java.lang.ClassNotFoundException: Didn't find class "com/google/android/gms/games/Games" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/androidx.test.tools.crawler-sIKA2_QdtCfAvwW3PXLmpA==/base.apk", zip file "/data/app/com.indovers.snapball-nYnEcOEv_98zf1Jk5-dHbQ==/base.apk", zip file "/data/app/com.indovers.snapball-nYnEcOEv_98zf1Jk5-dHbQ==/split_config.armeabi_v7a.apk"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-sIKA2_QdtCfAvwW3PXLmpA==/lib/arm, /data/app/com.indovers.snapball-nYnEcOEv_98zf1Jk5-dHbQ==/lib/arm, /data/app/androidx.test.tools.crawler-sIKA2_QdtCfAvwW3PXLmpA==/base.apk!/lib/armeabi-v7a, /data/app/com.indovers.snapball-nYnEcOEv_98zf1Jk5-dHbQ==/base.apk!/lib/armeabi-v7a, /data/app/com.indovers.snapball-nYnEcOEv_98zf1Jk5-dHbQ==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.c(Unknown Source:0)
com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:88)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:164)
com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.indovers.snapball-nYnEcOEv_98zf1Jk5-dHbQ==/split_config.armeabi_v7a.apk
dalvik.system.DexFile.openDexFileNative(Native Method)
dalvik.system.DexFile.openDexFile(DexFile.java:353)
dalvik.system.DexFile.<init>(DexFile.java:100)
dalvik.system.DexFile.<init>(DexFile.java:74)
dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
dalvik.system.DexPathList.<init>(DexPathList.java:157)
dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:693)
android.app.LoadedApk.getClassLoader(LoadedApk.java:727)
android.app.LoadedApk.getResources(LoadedApk.java:954)
android.app.ContextImpl.createAppContext(ContextImpl.java:2271)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5666)
android.app.ActivityThread.-wrap1(Unknown Source:0)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loop(Looper.java:164)
android.app.ActivityThread.main(ActivityThread.java:6523)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJNISafe.FindClass (System.String name) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) (at <00000000000000000000000000000000>:0)
GooglePlayGames.Android.AndroidClient..ctor (GooglePlayGames.BasicApi.PlayGamesClientConfiguration configuration) (at <00000000000000000000000000000000>:0)
GooglePlayGames.PlayGamesClientFactory.GetPlatformPlayGamesClient (GooglePlayGames.BasicApi.PlayGamesClientConfiguration config) (at <00000000000000000000000000000000>:0)
GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`2[T1,T2] callback, System.Boolean silent) (at <00000000000000000000000000000000>:0)

**Comment by exzizt** [comment]
Are you stripping any code from your builds? If so, stop doing that and see if you get those errors.

**Comment by Indovers** [comment]
> Are you stripping any code from your builds? If so, stop doing that and see if you get those errors.

Do you mean "strip engine code" in Player Settings?

**Comment by exzizt** [comment]
> > Are you stripping any code from your builds? If so, stop doing that and see if you get those errors.
> 
> Do you mean "strip engine code" in Player Settings?

Yes, and any other ways you may be stripping/removing assemblies or code that you don't want to remove.

**Comment by Indovers** [comment]
@exzizt OK, I unchecked "strip engine code" and "Managed Stripping Level" was set to low and it can not be changed to none. I'll test this build, hope it works

**Comment by Indovers** [comment]
@exzizt I tried it, but it still happens, and for some reason now it happens for me

**Comment by elizarskik** [comment]
I have the same nightmare

**Comment by exzizt** [comment]
Try re-running the resolver (and make sure it's the latest version). If that doesn't work, try re-installing any other plugins you may be using. If you are using the new v10 of GPGS, don't. It is really buggy still.

**Comment by Indovers** [comment]
@exzizt yeah, maybe I should try older version, thanks

**Comment by exzizt** [comment]
Yeah... Don't use the new version yet. Nothing in it is different except its ability to remove some of its files that you aren't using when you build. To save what, a couple of KB of build size? Give me a break!
My entire Google Play Games folder in my Unity project is only 3.9MB!

**Comment by Indovers** [comment]
@exzizt yes, thanks a lot, that helped me!

**Comment by exzizt** [comment]
> @exzizt yes, thanks a lot, that helped me!

You're welcome! Happy you fixed your problem.

**Comment by josephsipos** [comment]
I ran into this same problem with v10... Just so you know.

**Comment by steknika** [comment]
how can i downgrade my google play service? i have the same issue and i cant find the older one.
