### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by Voresh** [playgameservices/play-games-plugin-for-unity#2741]
Sometimes I get this error in builds and users can't login via gpgs. Plugin version is 0.9.64, Unity version is 2019.1.13f1. What I can do with this?

InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK

GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build (GooglePlayGames.Native.PInvoke.PlatformConfiguration configRef) (at <00000000000000000000000000000000>:0)
GooglePlayGames.Native.NativeClient.InitializeGameServices () (at <00000000000000000000000000000000>:0)
GooglePlayGames.Native.NativeClient+<>c__DisplayClass21_0.<Authenticate>b__0 (System.Int32 result) (at <00000000000000000000000000000000>:0)
System.Action1[T].Invoke (T obj) (at <00000000000000000000000000000000>:0)
System.Action1[T].Invoke (T obj) (at <00000000000000000000000000000000>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, System.IntPtr jmethodName, System.IntPtr jargs) (at <00000000000000000000000000000000>:0)
Rethrow as TargetInvocationException: GooglePlayGames.Android.AndroidTokenClient+ResultCallbackProxy.onResult(UnityEngine.AndroidJavaObject)
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, System.IntPtr jmethodName, System.IntPtr jargs) (at <00000000000000000000000000000000>:0)

**Comment by exzizt** [comment]
Make sure you aren't stripping any engine code or assemblies in your build. Check your project settings.

**Comment by Voresh** [comment]
> 
> 
> Make sure you aren't stripping any engine code or assemblies in your build. Check your project settings.

No stripping enabled in project settings, but I use Il2cpp

**Comment by exzizt** [comment]
> > Make sure you aren't stripping any engine code or assemblies in your build. Check your project settings.
> 
> No stripping enabled in project settings, but I use Il2cpp

Try re-running the resolver (and make sure it's the latest version). If that doesn't work, try re-installing any other plugins you may be using. If you are using the new v10 of GPGS, don't. It is really buggy still.

**Comment by Voresh** [comment]
> Try re-running the resolver

I am using jetifier and it resolves dependencies automatically when project builds and my gpgs version 0.9.64. Maybe re-installing other plugins should help me

**Comment by olehkuznetsov** [comment]
Can you try a new v0.10.04 plugin, please? It should be fixed there.
