### ISSUE TITLE
Invalid classname: Root element is missing or Ambiguous match found

### ISSUE THREAD

**Issue by wookieio** [playgameservices/play-games-plugin-for-unity#2745]
Hi,
Can anyone help? I have this problem when I want to set up Android configuration.
I am using Unity 2019.2.8f1; GPG plugin 0.9.64 (also tried 0.9.41 and 0.10.04).
Tried to update everything as this is the solution in every other topic about similar problem but nothing helped.
![image](https://user-images.githubusercontent.com/56512963/66718062-da737380-eddf-11e9-9167-aaefa0208f89.png)

**Comment by wookieio** [comment]
The error message sometimes changes (without any changes in plugins or updates.). It is Root element is missing or Ambiguous match found
![image](https://user-images.githubusercontent.com/56512963/66718137-c54b1480-ede0-11e9-97f5-4759d3802044.png)

**Comment by cygnusprojects** [comment]
Facing the same issue with Unity 2019.2.9f1.

**Comment by wookieio** [comment]
I've just found a solution and it was... preatty dumb.
You need to delete ALL COMMENTS from the xml from google play console...

**Comment by SH42913** [comment]
Solve this trouble with re-import latest 0.10.06

**Comment by mgb-pmg** [comment]
Having the same issue trying to configure a project that only uses cloud saves in 0.10.08?

**Comment by hinakawa** [comment]
> Having the same issue trying to configure a project that only uses cloud saves in 0.10.08?

yes, have it on unity 2019.4.3f1

**Comment by HiagoWal** [comment]
i'm havin the same problem
