### ISSUE TITLE
Side loading an APK with Google Play Services

### ISSUE THREAD

**Issue by cyberangel67** [playgameservices/play-games-plugin-for-unity#2756]
This may have already been asked, but I didn't find anything similar to this.

Ok, I have an app in development and I recently implemented the sign in and leaderboard stuff, if I push to APK to my console and push it out to my closed track this all works. But if I send the APK from Unity to my phone, it doesn't work.

Do I have to do something special to test this way or is the only option to continually push up to the store and re download from there. This is a productivity workflow nightmare so hoping someone can help here.

**Comment by olehkuznetsov** [comment]
Probably you need to link another Android app in play console with different SHA-1 key.
