### ISSUE TITLE
I'm forced to compile Google Play Games libraries on iOS when I want to use Game Center for iOS

### ISSUE THREAD

**Issue by iameugenejo** [playgameservices/play-games-plugin-for-unity#276]
I planned to use Google Play Games for Android and Game Center for iOS but this plugin unnecessarily makes XCode to compile Google Play Games related libraries even when those are not used.

Only workaround I have is to remove Google Play Games related iOS libraries from the Plugin folder and Editor folder. then from the generated XCode project, I have to remove every line that starts with "GPG" from RegisterMonoModules.cpp.

I'm not sure how to make the unity build to exclude those lines from RegisterMonoModules.cpp, but

it would be the best if there's an option in the editor menu to exclude iOS support.

**Comment by acceleroto** [comment]
+1.  It would really help me if I could easily remove GPGS completely for iOS builds.

**Comment by TinyMobGraham** [comment]
Is there any update on this issue? We have the same problem, we use this plugin for Android but not iOS.  However we can not build for iOS now.  Simply removing all the "#if UNITY_IPHONE" references does not fix the issue.

**Comment by claywilkinson** [comment]
Specifically what is the issue when building for iOS after removing all the #if UNITY_IPHONE sections?

**Comment by TinyMobGraham** [comment]
If I remove all the #if UNITY_IPHONE sections and build, I get the post build process error: "*** FATAL ERROR: Failed to read GPGSParams.h". However, it looks like the XCode project is still successfully created.

If I then load that resulting XCode project in XCode and try to build it I get the following build error: "...GPGSAppController.mm:20:9: 'GooglePlus/GooglePlus.h' file not found".

If I delete the file Editor/PostprocessBuildPlayer_PlayGames I can do a build that doesn't give me the first post build error.  But if I load that resulting XCode project into XCode and try to build it I get the same XCode error about GooglePlus.h not being found.

**Comment by spacetraveller** [comment]
Hear hear, we really need a solution to this, it's a bit rich that we are forced into incorporating all these Google API's for IOS builds when they're not wanted in that build, there should be a way to make a selection.. @TinyMobGraham did you manage to get it to work ? We're having the exact same problem and if removing all the 
#IF UNITY_IPHONE sections still results in that same error, then I'm going to be wasting time trying to do this.

Has anyone actually got any working solutions ? My knowledge of how plugins get incorporated into a build is a little limited at the moment unfortunately and there doesn't appear to be good solutions other than creating an entirely different project, which isn't very conveniant as I'm sure many developers will attest. Working solution needed please!

**Comment by TinyMobGraham** [comment]
The only thing that managed to work for me was to fully delete the plugin when doing iOS builds. This is especially frustrating because the plugin is not contained within a single subdirectory, there are files spread out in various places with different names. Luckily I had a GIT commit with the original install so I could find all the files and delete them.

**Comment by spacetraveller** [comment]
@TinyMobGraham seems that I'll need to do the same every time we run an IOS build. Our project is in development, so that means we'll be needing to do frequent builds which adds to the steps and wastes our time. If we can collaborate on a list of folders to be deleted to minimize the time spent that'll be a little help too, if it's not entirely necessary to remove every file and folder added by the plugin.

One of our developers mentioned another plugin that handles Google Play services, but it's not administrated by google. It at least separates IOS and the Android plugin.

**Comment by GrayedFox** [comment]
Hey there,

I worked around this by poking around the code and looking at the params.h file was generated. If you look at the menu option to generate a params.h you will notice that the code has certain checks in place - I ended up just rewriting it to allow a 'bogus' params.h file to be generated. 

Sounds dangerous, but so long as you are 100% sure you are not going to use GPG for iOS, you can have whatever params.h file you want. I'm no longer at the company where I was experiencing this problem, but I'll download the plug in again and have a look, will post the modified script here later if needed.

**Comment by spacetraveller** [comment]
Thanks @GrayedFox , that would be very helpful.

To be honest I thought that Google portrayed itself as an open standard company, that encourages using 3'rd parties but it's seeming more and more than they're trying to direct everything to google and give sloppy thirds to other companies and providers. 

Why would I want to use google play store on my iphone when there is already apple's own store? Ok sure the high score things and such would be useful to maintain in one space but I am also sure a lot of developers wish to host the game logic on their own hosting services and apply their own raw programming expertise on the logic. Most of the gimmicks that these sites offer are just that, gimmicks, and all of these things are implementable with basic logic on a basic server setup. 

The idea of trying to be overly "smart" and filling the developer panels with overt encouragement to use their gimmick tools for the developer confuses things and feels like they are offering using a hydrogen bomb to kill a fly..

My point is it's disappointing that google supports openness and customization but offers this plugin that will force it's code into the binary even if you don't wish to publish it in a certain device. 

Perhaps somebody is able to write up some code to circumvent any of the plugin from being compiled into the project when it is not required depending on a condition. :)

**Comment by yamanyar** [comment]
Here is what I did:

I executed following script to wrap all files with ANDROID directive: https://gist.github.com/yamanyar/3157b791726a3795dfee

Then later on I applied these:

	deleted:   Assets/Editor/GPGSPostBuild.cs 
	reset:   Assets/Editor/mod_pbxproj.pyc
	reset:   Assets/Editor/plistlib.pyc
	deleted:    Assets/Plugins/iOS/GPGSAppController.h
	deleted:    Assets/Plugins/iOS/GPGSAppController.mm

(reset means reset it to prior to what it was before installing google play services).

That's all

Cheers

**Comment by DeepakPant** [comment]
Is it ever going to be solved? I am sure easy official workaround could be done in a week. Its Frustrating that we need to rework when we want to switch between android and iOS build.
Unity has very complicated folder structure , files are spread within different folders so its hard to search each and every file to delete.

**Comment by kreso22** [comment]
Still nothing? Wow..

**Comment by claywilkinson** [comment]
Version 0.9.15 allows excluding the play game services from the iOS player by adding the symbol NO_GPGS.  Of course and calls your game is making to Google Play Game Services need to be excluded by you still.

**Comment by JamesMcMahon** [comment]
Where exactly do you add the NO_GPGS symbol to make this work?

**Comment by Hoagie572** [comment]
Thanks. It's great to have Devs who listen.

Is there any way to put the answer up at the top of the page?
