### ISSUE TITLE
android: Problem when a player decline invitation

### ISSUE THREAD

**Issue by avilco** [playgameservices/play-games-plugin-for-unity#277]
When a player decline an invitation the other player don't receive the cancelation because a problem on 
AndroidRtmpClient.cs 
private void DeliverRoomSetupProgressUpdate() {
...
if (mRtmpListener != null) {
Logger.d("Delivering progress to callback.");
                PlayGamesHelperObject.RunOnGameThread(() => {
					mRtmpListener.OnRoomSetupProgress(progress);  //logs reports null for mRtmpListener
                });
}
}

Solution founded on other functions of the file: 
RealTimeMultiplayerListener listener = mRtmpListener;
if (listener != null) {
         Logger.d("Delivering progress to callback.");
          PlayGamesHelperObject.RunOnGameThread(() => {
			if (listener != null) listener.OnRoomSetupProgress(progress);
          });
}

**Comment by claywilkinson** [comment]
the 0.9.10 update changed how this is implemented, so i believe this is obsolete.
