### ISSUE TITLE
Error CS0117: 'BuildPipeline' does not contain a definition for 'GetPlaybackEngineDirectory'

### ISSUE THREAD

**Issue by easycg** [playgameservices/play-games-plugin-for-unity#2772]
Hi!

I've just installed the plugin and I get an error:

`Assets/GooglePlayGames/Editor/GPGSUtil.cs(452,57): error CS0117: 'BuildPipeline' does not contain a definition for 'GetPlaybackEngineDirectory'`

I've looked for error but I haven't found anything. It's a known error and it will be solved in the next update? Can someone help me with this issue, please?

Thanks!

**Comment by mukhinid** [comment]
Hi! It's looked like you're using Unity 2018.x version. This error already mentioned in issue #2766. I've created PR #2768, that fixes it, but while it isn't merged. So far you can use older plugin version (e.g. v10.04) or go to Assets/GooglePlayGames/Editor/GPGSUtil.cs file and wrap strings from 448 to 461 into `#if UNITY_2019` macros.

**Comment by mukhinid** [comment]
@olehkuznetsov I think this issue might to be closed via #2768

**Comment by easycg** [comment]
@mukhinid Thank you for your answer!
