### ISSUE TITLE
Crashing on GPGS Authentication

### ISSUE THREAD

**Issue by mauricin** [playgameservices/play-games-plugin-for-unity#2778]
So I first installed GPGS, implemented everything except authentication, obviously nothing would happen as GPGS needs to authenticate in order to work at all, at least the game was working normally, no unexpected behavior.

But when I built it with authenticating, the game crashes instantly when opening, sometimes I can see a black screen before crashing, sometimes it simply crashes.

Authentication process: 

`void Awake() {
        if (instance != null) {
            Destroy(gameObject);
            print("Duplicate music player destroyed");
        }
        else {
            instance = this;
            GameObject.DontDestroyOnLoad(gameObject);
        }      
    }
    void Start()
    {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();
        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.Activate();
 
        SignIn();
 
    }
 
    void SignIn() {
 
        Social.localUser.Authenticate(success => { });
    }`

Unity version is 2018.3.6f1, GPGS is 0.96.4
Attached logcat but not sure if anything useful is showing up.
[logcat RocketJ.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/3806250/logcat.RocketJ.txt)

**Comment by olehkuznetsov** [comment]
Seems as crash is related to this line:
2019-11-03 21:34:30.493 24330-24354/? E/Unity: NullReferenceException: A null value was found where an object instance was required.
at LevelManager.Start () [0x00000] in <filename unknown>:0

**Comment by mauricin** [comment]
> Seems as crash is related to this line:
> 2019-11-03 21:34:30.493 24330-24354/? E/Unity: NullReferenceException: A null value was found where an object instance was required.
> at LevelManager.Start () [0x00000] in :0

Ok, thanks for the reply!
I had a look into the code and changed some stuff, it seems that I fixed this NullReferenceException, but the game still crashing, the difference is that it takes longer to crash, the game works for some seconds before crashing, which didn't happen before, attached new logcat.
[logcat2.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/3823037/logcat2.txt)

**Comment by olehkuznetsov** [comment]
Can't see anything related to PGS plugin in new logcat2.txt as well
You can try to comment PGS integration to check if it is related.
