### ISSUE TITLE
Android Back Button Loop During Authentication if No Google Account

### ISSUE THREAD

**Issue by hvs-clark** [playgameservices/play-games-plugin-for-unity#278]
Noticed this when testing Google Play login with our game. We call "authenticate" shortly after app startup so the player can take advantage of Google Play features.

It seems to work fine if there's one or more accounts on the device. With one account, that account is automatically chosen for login. With multiple accounts, we see an account picker.

If there are no accounts on the device, the authentication procedure goes directly to an "Add a Google Account" page, with the options "New" or "Existing". We find that if you press the back button on this page, it will appear to go back to the game, but will quickly switch back to the "Add a Google Account" page. The only way that you can sometimes get out of this loop is to double tap the back button (like a CD player). But sometimes we've found that this actually causes a soft crash where the game gets stuck on a black screen until you force quit.

Not sure what's causing it, but thought you'd like to know!

**Comment by claywilkinson** [comment]
Tracking internally as 18945848

**Comment by claywilkinson** [comment]
I believe this is fixed now.  Please open a new issue if it is still happening.
