### ISSUE TITLE
Warning CS0642: Possible mistaken empty statement

### ISSUE THREAD

**Issue by easycg** [playgameservices/play-games-plugin-for-unity#2781]
Hi! I get this error when I tried to build my app.

There are different files where it occurs.

![Captura de pantalla 2019-11-11 a les 23 47 54](https://user-images.githubusercontent.com/57129982/68627297-b9d13300-04dd-11ea-8370-e48ce144be57.jpg)

**Comment by olehkuznetsov** [comment]
Thank you for notifying us. Will fix in next plugin release.

**Comment by easycg** [comment]
Hi! Just to know. Any news about this?

**Comment by olehkuznetsov** [comment]
Will be in next plugin release.

**Comment by ozdemir08** [comment]
[This commit](https://github.com/playgameservices/play-games-plugin-for-unity/commit/7db8ac5720c86f4b81ac61a0db46834b2d0822c8) disables those warnings. We'll make a new release next week (probably Monday).

**Comment by TheOneVries** [comment]
errors still there/back in GooglePlayGamesPlugin-0.10.06

**Comment by Azbouby** [comment]
Yes still present in GooglePlayGamesPlugin-0.10.06, and because of this warning I can't connect with my phone to google play services

**Comment by olehkuznetsov** [comment]
I don't think those warnings affect anything. Check you SHA1 key and if in cloud console you've setup auth screen properly.

**Comment by shadoath** [comment]
Still seeing these warnings.
