### ISSUE TITLE
What are valid cases for success to be false in Social.localUser.Authenticate((bool success) => {

### ISSUE THREAD

**Issue by Diamonds0a** [playgameservices/play-games-plugin-for-unity#2785]
Hi,

Per the documentation, we should call
``` 
   Social.localUser.Authenticate((bool success) => {
        // handle success or failure
    });
```

Could the documentation be updated what scenarios would return success ==  false?

Also, is there a way to get a 'reason' within that framework? For stats / debugging?

**Comment by olehkuznetsov** [comment]
You can call this one 
void Authenticate(Action<bool, string> callback, bool silent);
like PlayGamesPlatform.Instance.Authenticate(...)
It has a reason string in the callback.

And currently we are working on a new API which will have result code for an error.
