### ISSUE TITLE
Google drive API precondition failed

### ISSUE THREAD

**Issue by andrex903** [playgameservices/play-games-plugin-for-unity#2786]
Hi, I have developed a game for android using Unity 3d , and I've implemented the Google play services to save data online. In particular I'm using the Saved Games Service.

Everything was fine in the very first days but suddenly the users have experienced a problem with the save data. Many users aren't able to save the data anymore (the problem is in the update of the save data to the server).

Everything started on 11th November but it stopped on 15th November. It starts again on 18th November (after about 3 days with no report of the issue from the users). I have analyzed the metrics on Google drive API and I have noticed that an error "412" (precondition failed) is present in the exact days of the saving data issue. Someone know what can be the meaning of this error and where it could came from?

**Comment by olehkuznetsov** [comment]
Thanks for flagging this issues. Currently it seems to be resolved. Please let us know if it happens again.

**Comment by andrex903** [comment]
hello, thanks for the reply. So if I log in and then exit the app (without
logging out), when I re-enter if I don't have a connection, can't I stay
authenticated?

Il giorno ven 22 nov 2019 alle ore 12:55 olehkuznetsov <
notifications@github.com> ha scritto:

**Comment by olehkuznetsov** [comment]
You will stay authenticated without internet connection if was before. Authenticate will silently work in this case without internet connection.
