### ISSUE TITLE
No achievements visible in Play Games app: Invalid applicationId?

### ISSUE THREAD

**Issue by mvaivre** [playgameservices/play-games-plugin-for-unity#2788]
So I have GPG working well in my game: achievement popups are shown properly, game progression is saved etc.
BUT, when I use the Google Play Games app to see the achievement list, the page is blank.
Looking at the logs, here's what I've found:

`11-23 19:10:26.202 30864 32475 W AchievementAgent: {"code":400,"errors":[{"reason":"invalid","domain":"global","message":"Invalid applicationId with value com.xxx.xxx."}]}`

It seems like the package name is used instead of the applicationId? I've double checked the plugin setup, everything looks fine. And again, everything works perfectly in game, it's really just when using the GPG app.

Any idea why this would happen? Thanks in advance for your help!

**Comment by olehkuznetsov** [comment]
Is the game already published on play store? Are those achievements published or for testers only?

**Comment by mvaivre** [comment]
The games is not yet published, achievements are for testers only, but they used to be visible in the Google Play Games app, even in "test mode".

**Comment by mvaivre** [comment]
I would really appreciate any indication regarding this. I've been investigating for days now, and this is the only blocker I have left.
Is anyone able to reproduce this with Unity 2019.3, Play Games Plugin 10.06?

Also, something really weird: I've attempted to try calling the failing API endpoint manually with a random application ID:
`https://www.googleapis.com/games/v1/applications/123456789012`

and here is the response:

```
{
    "error": {
        "errors": [
            {
                "domain": "global",
                "reason": "notFound",
                "message": "The requested application with ID 407408718192 was not found."
            }
        ],
        "code": 404,
        "message": "The requested application with ID 407408718192 was not found."
    }
}
```

Look at the ID, it doesn't match. I can put any value for the ApplicationID, I would always get that response. You can try it by yourself easily here: https://developers.google.com/games/services/web/api/applications/get

I don't know if it's somehow related, but this behaviour is definitely not expected.

**Comment by olehkuznetsov** [comment]
Probably it should be fixed if you publish your Play Games services changes in Play Developer console.

**Comment by mvaivre** [comment]
Thanks for your quick answer! It seems to work, indeed! Weird that it was working before in test mode.

**Comment by olehkuznetsov** [comment]
Thanks for update
