### ISSUE TITLE
Incrementing Events Delayed?

### ISSUE THREAD

**Issue by KaloaGames** [playgameservices/play-games-plugin-for-unity#2789]
Hey,

we are sending Events via PlayGamesPlatform.Instance.Events.IncrementEvent(eventName, incrementInt);  -> is it common that the Events are showing up at the Google Play Console only after 2-4 days? Thats a pretty long time to debug/react

Is that caused by the Plugin or by Google or because of an error in the code?

Greez

**Comment by ozdemir08** [comment]
We've checked our server side and everything seems to be running as it usually has been. But if you are able to see your events on Console, then I don't think it's an error in plugin or your code. 

Can you check your events again and let us know if you consistently see your events showing up on Console with 2-4 days delay?

**Comment by ozdemir08** [comment]
Closing this issue for now, feel free to reopen it in case you have further questions.
