### ISSUE TITLE
'PlayGamesLocalUser' does not implement interface member 'IUserProfile.gameId'

### ISSUE THREAD

**Issue by gambikules** [playgameservices/play-games-plugin-for-unity#2791]
Hello
Unity 2020.1  
'PlayGamesLocalUser' does not implement interface member 'IUserProfile.gameId'

How implement  gameId?

**Comment by olehkuznetsov** [comment]
We have IUserProfile.id only for now. Will fix this in next release.

**Comment by Thaina** [comment]
> We have IUserProfile.id only for now. Will fix this in next release.

Still not released?

**Comment by olehkuznetsov** [comment]
Fixed in 0.10.07
