### ISSUE TITLE
Exception class not found com.google.android.gms.games.Games on Authenticate, v0.10.06.

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [playgameservices/play-games-plugin-for-unity#2796]
I'm trying to run the following code as part of an initialization function in my game:
```C#
      PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
                                            // enables saving game progress.
                                           .EnableSavedGames()
                   // requests a server auth code be generated so it can be passed to an
                   //  associated back end server application and exchanged for an OAuth token.
                  .RequestServerAuthCode(false)
                   // requests an ID token be generated.  This OAuth token can be used to
                   //  identify the player to other services such as Firebase.
                  .RequestIdToken()
                  .Build();
      
      
      Debug.Log( $"GoogleGameManager, init: 1." );
      PlayGamesPlatform.InitializeInstance(config);
      // recommended for debugging:
      Debug.Log( $"GoogleGameManager, init: 2." );
      PlayGamesPlatform.DebugLogEnabled = true;
      // Activate the Google Play Games platform
      Debug.Log( $"GoogleGameManager, init: 3." );
      PlayGamesPlatform.Activate();
      
      
      Debug.Log( $"GoogleGameManager, init: 4." );
      Social.localUser.Authenticate( (bool success) => {
                                        // handle success or failure
                                        Debug.Log( $"Social.localUser.Authenticate, success: {success}." );
                                        if ( success )
                                        {
                                            ((PlayGamesLocalUser)Social.localUser).GetStats((rc, stats) =>
                                                                                            {
                                                                                                // -1 means cached stats, 0 is succeess
                                                                                                // see  CommonStatusCodes for all values.
                                                                                                if (rc <= 0 && stats.HasDaysSinceLastPlayed()) {
                                                                                                    Debug.Log("It has been " + stats.DaysSinceLastPlayed + " days");
                                                                                                }
                                                                                            });
                                        }
                                     });
      Debug.Log( $"GoogleGameManager, init: 5." );
```

The log showing the following results:
```log
2019-12-02 16:57:53.969 8017-8694/? I/Unity: GoogleGameManager, init: 1.
    GoogleGameManager:init()
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2019-12-02 16:57:53.969 8017-8772/? I/UnityAds: com.unity3d.services.core.configuration.InitializeThread$InitializeStateLoadCache.execute() (line:245) :: Unity Ads init: webapp loaded from local cache
2019-12-02 16:57:53.973 8017-8694/? I/Unity: GoogleGameManager, init: 2.
    GoogleGameManager:init()
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2019-12-02 16:57:53.975 8017-8694/? I/Unity: GoogleGameManager, init: 3.
    GoogleGameManager:init()
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2019-12-02 16:57:53.978 8017-8694/? I/Unity: GoogleGameManager, init: 4.
    GoogleGameManager:init()
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2019-12-02 16:57:53.988 8017-8694/? E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.games.Games
    java.lang.ClassNotFoundException: com.google.android.gms.games.Games
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.Games" on path: DexPathList[[zip file "/data/app/com.sdfsdfsdfsd.jfgjfghjfgjfg-SEDFSDFGSDGSDGSDF-lA==/base.apk", zip file "/data/app/com.sdfsdfsdfsd.jfgjfghjfgjfg-SEDFSDFGSDGSDGSDF-lA==/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/com.sdfsdfsdfsd.jfgjfghjfgjfg-SEDFSDFGSDGSDGSDF
2019-12-02 16:57:53.997 8017-8017/? W/ResourceType: Found multiple library tables, ignoring...
2019-12-02 16:57:53.999 8017-8017/? I/WebViewFactory: Loading com.android.chrome version 78.0.3904.108 (code 390410837)
2019-12-02 16:57:54.001 8017-8694/? I/Unity: Initializing UnityPurchasing via Codeless IAP
    UnityEngine.Purchasing.CodelessIAPStoreListener:CreateCodelessIAPStoreListenerInstance()
    UnityEngine.Purchasing.CodelessIAPStoreListener:get_Instance()
    UnityEngine.Purchasing.IAPListener:OnEnable()
```
It seems that Social.localUser.Authenticate causing the exception, and login to Google Games never appears. Everything else in my game works fine. I'm also using IAP and Ads packages by Unity.  
I'm using PGPfU for the first time, so I'm not sure if I'm doing something wrong, or is it a bug.
Versions: PGPfU 0.10.06 from today, Unity 2019.2.14f, on Ubuntu 19.10 Linux  5.3.0-23-generic.

Any suggestions?

**Comment by a-l-e-x-d-s-9** [comment]
I downgraded to GPGfU v0.9.64, and running the same code, but exception disappeared.
So It looks more like a bug(runtime or setup) in GPGfU v10.6 and not that I am doing something wrong.

**Comment by olehkuznetsov** [comment]
There are a lot of fixes from v9 to v10, it is better to upgrade to it. Force resolve should help with this issue.

**Comment by DuckMcQu4ck** [comment]
If force resolve didn't help, how can i fix it?

**Comment by olehkuznetsov** [comment]
Check if minify setting is set up correctly. Check this [README.md section](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/README.md#decreasing-apk-size), please.

**Comment by gtzpower** [comment]
For whatever reason, that link took me to entirely the wrong section.  Just so anyone having that issue doesn't have to inspect the link, it should go to [Decreasing APK Size](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/README.md#decreasing-apk-size)

Having said that, I just upgraded from 10.05 to 10.06 to try and resolve the ClassNotFoundException. 

Managed Stripping Level: Disabled
Minify Release: None
Minify Debug: None

Re-ran Android Setup which said "Resolution Succeeded".

Tried running a Force Resolve (which is in Assets menu -> Play Services Resolver -> Android Resolver, if you are wondering like I was), and that didn't work when doing my normal procedure.  

**I did get it working though!**
When I was running Force Resolve, I would get a Jetifier prompt asking to upgrade to API level 28 (from 27).  I did not wish to make any significant changes, so I was saying no to this.  However, after I said yes, this error went away.  I am having a new issue now, but got past this one, and the Google Play Games connection dialog is showing up at least.

**Comment by Dongurea** [comment]
> Check if minify setting is set up correctly. Check this [README.md section](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/README.md#decreasing-apk-size), please.

It works for me. Unity version: 2019.2.21f1 , gpgs version: 10.06, firebase sdk version: 6.11.0, admob version: 4.2.1.  I spend all the time to solve this problem(Class not found : com.google.android.gms.games). You saved my life. Follow the minify setting (player setting > publishing settings > minify release : proguard, minify debug : proguard, Check 'user proguard file' enable, Copy and paste the text(in link) into the file(Assets\Plugins\Android\proguard-user.txt)). Hope my case help some one like me.

**Comment by zuluonezero** [comment]
> Hope my case helps some one like me.

OMG I could kiss you right now!

**Comment by TheVClyfe** [comment]
> > Check if minify setting is set up correctly. Check this [README.md section](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/README.md#decreasing-apk-size), please.
> 
> It works for me. Unity version: 2019.2.21f1 , Gpgs version: 10.06, Firebase sdk version: 6.11.0, Admob version: 4.2.1. I spend all the time to solve this problem(Class not found : com.google.android.gms.games). You saved my life. Follow the minify setting.
> (player setting > publishing settings >
> 
> 1. minify release : proguard,
> 2. minify debug : proguard,
> 3. Check 'user proguard file' enable,
> 4. Copy and paste the text(in the link on the top) into the file(Assets\Plugins\Android\proguard-user.txt)).
> 
> Hope my case helps some one like me.

Thanks a lot, mate! This really, really helped! 👍

**Comment by nathansisler** [comment]
I'm running into this problem. I've tried the proguard update and it's not helping. Any new updates?

**Comment by concubicycle** [comment]
Getting this after upgrading to 2020.2.2f1.

**Comment by concubicycle** [comment]
I (obviously) got this error when I forgot to Resove after having to reinstall Unity and re-clone my project.

**Comment by AnderX003** [comment]
> > Check if minify setting is set up correctly. Check this [README.md section](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/README.md#decreasing-apk-size), please.
> 
> It works for me. Unity version: 2019.2.21f1 , Gpgs version: 10.06, Firebase sdk version: 6.11.0, Admob version: 4.2.1. I spend all the time to solve this problem(Class not found : com.google.android.gms.games). You saved my life. Follow the minify setting.
> (player setting > publishing settings >
> 
> 1. minify release : proguard,
> 2. minify debug : proguard,
> 3. Check 'user proguard file' enable,
> 4. Copy and paste the text(in the link on the top) into the file(Assets\Plugins\Android\proguard-user.txt)).
> 
> Hope my case helps some one like me.
 
I did everything that was written above and did resolve but that didn't help me.
Then I did **Force Resolve** and unity generated needed files.


> 1. minify release : proguard,
> 2. minify debug : proguard,
> 3. Check 'user proguard file' enable,
> 4. Copy and paste the text(in the link on the top) into the file(Assets\Plugins\Android\proguard-user.txt)).
5. Go Assets > External Dependency Manager > Android Resolver > Force Resolve

**Comment by KyrXtz** [comment]
In the latest version the proguard-user.txt is removed from the master branch, but this page stills show if you google search this error. I'm posting here the contents of the proguard-user.txt if anyone from google ended up here.

`-keep class com.google.android.gms.games.leaderboard.** { *; }
-keep class com.google.android.gms.games.snapshot.** { *; }
-keep class com.google.android.gms.games.achievement.** { *; }
-keep class com.google.android.gms.games.event.** { *; }
-keep class com.google.android.gms.games.stats.** { *; }
-keep class com.google.android.gms.games.video.** { *; }
-keep class com.google.android.gms.games.* { *; }
-keep class com.google.android.gms.common.api.ResultCallback { *; }
-keep class com.google.android.gms.signin.** { *; }
-keep class com.google.android.gms.dynamic.** { *; }
-keep class com.google.android.gms.dynamite.** { *; }
-keep class com.google.android.gms.tasks.** { *; }
-keep class com.google.android.gms.security.** { *; }
-keep class com.google.android.gms.base.** { *; }
-keep class com.google.android.gms.actions.** { *; }
-keep class com.google.games.bridge.** { *; }
-keep class com.google.android.gms.common.ConnectionResult { *; }
-keep class com.google.android.gms.common.GooglePlayServicesUtil { *; }
-keep class com.google.android.gms.common.api.** { *; }
-keep class com.google.android.gms.common.data.DataBufferUtils { *; }
-keep class com.google.android.gms.games.quest.** { *; }
-keep class com.google.android.gms.nearby.** { *; }`

**Comment by tonito992** [comment]
> In the latest version the proguard-user.txt is removed from the master branch, but this page stills show if you google search this error. I'm posting here the contents of the proguard-user.txt if anyone from google ended up here.
> 
> > -keep class com.google.android.gms.games.leaderboard.** { _; }
> > -keep class com.google.android.gms.games.snapshot._* { _; }
> > -keep class com.google.android.gms.games.achievement._* { _; }
> > -keep class com.google.android.gms.games.event._* { _; }
> > -keep class com.google.android.gms.games.stats._* { _; }
> > -keep class com.google.android.gms.games.video._* { _; }
> > -keep class com.google.android.gms.games._ { _; }
> > -keep class com.google.android.gms.common.api.ResultCallback { _; }
> > -keep class com.google.android.gms.signin.__ { _; }
> > -keep class com.google.android.gms.dynamic._* { _; }
> > -keep class com.google.android.gms.dynamite._* { _; }
> > -keep class com.google.android.gms.tasks._* { _; }
> > -keep class com.google.android.gms.security._* { _; }
> > -keep class com.google.android.gms.base._* { _; }
> > -keep class com.google.android.gms.actions._* { _; }
> > -keep class com.google.games.bridge._* { _; }
> > -keep class com.google.android.gms.common.ConnectionResult { _; }
> > -keep class com.google.android.gms.common.GooglePlayServicesUtil { _; }
> > -keep class com.google.android.gms.common.api.__ { _; }
> > -keep class com.google.android.gms.common.data.DataBufferUtils { _; }
> > -keep class com.google.android.gms.games.quest.__ { _; }
> > -keep class com.google.android.gms.nearby.__ { *; }

Thank you very much, I searched the whole internet for this.
Only one digression, It won't build with { ; } or { *;} you have to replace it with just { }

**Comment by userqt** [comment]
This issue is still happening, though the PlayGamesClientConfiguration is not used anymore.

Simply calling PlayGamesPlatform.Activate(); would be enough of triggering 

> ClassNotFoundException: com.google.android.gms.games.PlayGames

Please reopen the issue.

**Comment by jvrieling** [comment]
I can second that this issue persists. My external dependency manager is having issues resolving, could that be part of the problem?

I use Unity 2020.3.25f1, Google Play Games 0.11.01, and Firebase 9.1

**Comment by kustomphaq** [comment]
> I can second that this issue persists. My external dependency manager is having issues resolving, could that be part of the problem?
> 
> I use Unity 2020.3.25f1, Google Play Games 0.11.01, and Firebase 9.1

same to me... in my case it is on Unity 2021.3.4f1 version

**Comment by jvrieling** [comment]
![image](https://user-images.githubusercontent.com/32886119/175335659-cb90b5c5-a399-4881-8dd7-8d709075a7f9.png)

Maybe this auto-conflict resolution has something to do with it? I can't find where to stop conflict resolution...

I've been trying to get this to work. I still have the issue in an empty URP project in a freshly-downloaded Unity 2020.3.36f1. (The project is empty except for the default URP project and Google Play Games / Firebase)

**Comment by kustomphaq** [comment]
> ![image](https://user-images.githubusercontent.com/32886119/175335659-cb90b5c5-a399-4881-8dd7-8d709075a7f9.png)
> 
> Maybe this auto-conflict resolution has something to do with it? I can't find where to stop conflict resolution...
> 
> I've been trying to get this to work. I still have the issue in an empty URP project in a freshly-downloaded Unity 2020.3.36f1. (The project is empty except for the default URP project and Google Play Games / Firebase)

Mate, could be... I am NOW working all this messy bug, feel free to contact me on Skype so we can share info. @kustomphaq

**Comment by kustomphaq** [comment]
In my case seems like Play Games app on Android device register my game is connected very recently, but SDK tell me no Authentication was canceled.

**Comment by PolluxDevelopersTeam** [comment]
I use GPGS v0.11.01 and was same error `java.lang.ClassNotFoundException: com.google.android.gms.games.PlayGames`. 
Android Force Resolve failed with an error `Failed to fetch the following dependencies: com.google.games:gpgs-plugin-support:+`.
How did I fix it:
- open the file Assets/GooglePlayGames/com.google.play.games/Editor/GooglePlayGamesPluginDependencies.xml
- change line `Packages/com.google.play.games/Editor/m2repository` to `Assets/GooglePlayGames/com.google.play.games/Editor/m2repository`
- run Android Force Resolve

**Comment by jvrieling** [comment]
> I use GPGS v0.11.01 and was same error `java.lang.ClassNotFoundException: com.google.android.gms.games.PlayGames`. Android Force Resolve failed with an error `Failed to fetch the following dependencies: com.google.games:gpgs-plugin-support:+`. How did I fix it:
> 
>     * open the file Assets/GooglePlayGames/com.google.play.games/Editor/GooglePlayGamesPluginDependencies.xml
> 
>     * change line `Packages/com.google.play.games/Editor/m2repository` to `Assets/GooglePlayGames/com.google.play.games/Editor/m2repository`
> 
>     * run Android Force Resolve

Thank you @PolluxDevelopersTeam !! This solved my issue. The line in my GooglePlayGamesPluginDependencies.xml was pointing to the wrong directory.

**Comment by tecdungeon** [comment]
![image](https://user-images.githubusercontent.com/101531692/180611982-f03b6f50-5b37-45aa-9a36-0f14e9fac267.png)

If you look in the GooglePlayGames asset in your unity project, you will find the games file, which contains the required entries for the progaurd-user.txt file.

**Comment by luyang950** [comment]
I met the same problem on Unity 2021.3.5f1, GPG plugin version 0.10.14, and finally solved it by checking "Custom Proguard File" on, and copy&paste the content from [https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/Assets/Public/GooglePlayGames/com.google.play.games/Proguard/games.txt](url) into proguard-user.txt.
You can find "Custom Proguard File" in Unity-PorjectSettings-PublishingSettings.
Hope it could be helpful.

**Comment by Ragethunder** [comment]
For me this was resolved by copying those lines into proguard-user.txt and editing dependencies file (GooglePlayGamesPluginDependencies.xml) so it points to
```
<repository>Assets/GooglePlayGames/Editor/m2repository</repository>
```

**Comment by shadowzaky** [comment]
In my case it was because my folder name had a "!" in it and Android Resolver does not support having special characters in your unity folder name

**Comment by nndwn** [comment]
for fix this download another package google for unity https://developers.google.com/unity/packages , sample im add play_in-app_review, google can fix error automatic with resolver
