### ISSUE TITLE
Updated to latest version tons of errors

### ISSUE THREAD

**Issue by deathsaber92** [playgameservices/play-games-plugin-for-unity#2798]
Hey after updating to Release v10.06, I have a lot of errors in console in unity 2019.3.0f1:

- Assets\GooglePlayGames\Platforms\Native\Platforms\Android\AndroidClient.cs(44,54): error CS0117: 'AndroidTokenClient' does not contain a definition for 'GetActivity'

- Assets\GooglePlayGames\Platforms\Native\Platforms\Android\AndroidClient.cs(71,72): error CS0117: 'AndroidTokenClient' does not contain a definition for 'CreateInvisibleView'

- Assets\GooglePlayGames\Platforms\Native\Platforms\Android\AndroidClient.cs(102,69): error CS0117: 'AndroidTokenClient' does not contain a definition for 'GetActivity'

- Assets\GooglePlayGames\Platforms\Native\Platforms\Android\AndroidClient.cs(150,35): error CS1061: 'PlayerStats' does not contain a definition for 'AvgSessonLength' and no accessible extension method 'AvgSessonLength' accepting a first argument of type 'PlayerStats' could be found (are you missing a using directive or an assembly reference?)

- Assets\GooglePlayGames\Platforms\Native\Platforms\Android\AndroidClient.cs(151,33): error CS0200: Property or indexer 'PlayerStats.DaysSinceLastPlayed' cannot be assigned to -- it is read only

and the list keeps going to 28 errors.... 

What is the cause of this? Is the plugin or something i did wrong? I used it before with no problems, I decided to update it because suddenly Socual.localUser.Authenticate was not showing any callback at all..... not a fail, not a success, just freezing there...

**Comment by olehkuznetsov** [comment]
You need to delete GooglePlayGames folder if you update from version 9 to version 10. Or to do force resolve and agree to remove all unused files.
