### ISSUE TITLE
How to detect if Google Play Games app installed on user's device or not?

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [playgameservices/play-games-plugin-for-unity#2799]
Is there a way to detect if Google Play Games app installed on user's device, and if not, only then request user to install it or let user refuse the installation, so my game would not ask it again?

**Comment by ozdemir08** [comment]
You can use [PlatformUtils.Supported](https://github.com/playgameservices/play-games-plugin-for-unity/blob/219fb2c4835b3ab9f26ed938a5df15b9fd6852d3/source/PluginDev/Assets/GooglePlayGames/OurUtils/PlatformUtils.cs#L29).
