### ISSUE TITLE
could not load library "libc++_shared.so" needed by "libgpg.so"

### ISSUE THREAD

**Issue by lpzkl** [playgameservices/play-games-plugin-for-unity#280]
After updating to new version GooglePlayGamesPlugin-0.9.10, I'm facing a problem.

I have two test devices: one of them is Samsung Galaxy S4 Mini, other is Galaxy Tab 4 7.0 (T230).

My game on S4 Mini has problems with new native libraries. T230 works fine.

S4Mini logcat:

D/dalvikvm( 4785): Trying to load lib /mnt/asec/com.aaaa.bbb-1/lib/libgpg.so 0x419aea38

I/LSS-II: (  780): proc wait in:com.sec.android.Kies,adj=11LRU num=89,i=65

E/dalvikvm( 4785): dlopen("/mnt/asec/com.aaaa.bbb-1/lib/libgpg.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1636): could not load library "libc++_shared.so" needed by "libgpg.so"; caused by load_library(linker.cpp:746): library "libc++_shared.so" not found

D/dalvikvm( 4785): Trying to load lib /mnt/asec/com.aaaa.bbb-1/lib/libgpg.so 0x419aea38

E/dalvikvm( 4785): dlopen("/mnt/asec/com.aaaa.bbb-1/lib/libgpg.so") failed: Cannot load library: find_library(linker.cpp:890): "/mnt/asec/com.aaaa.bbb-1/lib/libgpg.so" failed to load previously

E/Unity   ( 4785): Unable to find gpg

---

T230 logcat:

D/dalvikvm( 8011): Trying to load lib /data/app-lib/com.aaaa.bbb-27/libgpg.so 0x41dc5268

D/dalvikvm( 8011): Shared lib '/data/app-lib/com.aaaa.bbb-27/libgpg.so' already loaded in same CL 0x41dc5268

D/dalvikvm( 8011): Trying to load lib /data/app-lib/com.aaaa.bbb-27/libgpg.so 0x41dc5268

D/dalvikvm( 8011): Shared lib '/data/app-lib/com.aaaa.bbb-27/libgpg.so' already loaded in same CL 0x41dc5268

D/dalvikvm( 8011): Trying to load lib /data/app-lib/com.aaaa.bbb-27/libgpg.so 0x41dc5268

D/dalvikvm( 8011): Shared lib '/data/app-lib/com.aaaa.bbb-27/libgpg.so' already loaded in same CL 0x41dc5268

**Comment by nonaxanon** [comment]
i know this is way old, but have been searching for a compiled libgpg.so file around and the one was uploaded is not available anymore, would anyone please upload one compiled as per instructions above, been trying to compile it but no luck

**Comment by nosmirck** [comment]
@nonaxanon the plugin now has the compiled library embedded. Download it again from the repository

**Comment by nonaxanon** [comment]
then something is wrong on my end cause for the life of me, it wont connect, on editor it states some errors cause its editor, and on android device it simply does nothing

**Comment by nonaxanon** [comment]
after the Performing Android initialization of the GPG SDK, i get a bunch of errors similar to this one
Can't register class com/google/android/gms/common/ConnectionResult:

any ideas ?

**Comment by avvie** [comment]
same here, and I have been trying to recompile the lib.
It seems that ./build_plugin.sh does not exist anywhere .. I have the libgpg in my projects.. and 2 weeks ago everything worked perfectly. I have updated everything in the sdk and I have the latest plugin  from here

**Comment by Aupuma** [comment]
I have the problem DllNotFoundException: gpg, but how could I make this solution work if the build_plugin.sh does not exist in the current version?

**Comment by darker89** [comment]
its not working. Anyone solve this?

**Comment by sinmaplewing** [comment]
My jar resolver keep removing the Assets/Plugins/Android/gpgs-plugin-support-0.9.42.aar file.
And after removing it and rebuilding it, I got the same error: Unable to find gpg.

But after I put the Assets/Plugins/Android/gpgs-plugin-support-0.9.42.aar back, the build is all fine with gpgs......

**Comment by plasticblock** [comment]
@mrggl is it still actual?
Could you create new link to that lib? Because i see 404 when I open 
[https://github.com/playgameservices/play-games-plugin-for-unity/tree/debug_libgpg/debug](it).

@sinmaplewing Is that how I can fix it? :D
