### ISSUE TITLE
java.lang.NullPointerException: GoogleSignInAccount must not be null

### ISSUE THREAD

**Issue by thekingofpsycho** [playgameservices/play-games-plugin-for-unity#2800]
Unity 2018.4.11f
GPGS 0.10.04
---------
Build Architecture
arm64 , armv7 
---------
Affected Device Models
samsung/SM-A305N/a30...23%
samsung/SM-J330L/j3y...22%
LGE/LM-X420N/mmh4...20%
LGE/LM-X415K/cv3n...17%
LGE/LM-X410S/cv3n...16%
---------
3 Days Total
CRASHES 1.29k
USERS AFFECTED 1144
---------
Affected OS Names
Android OS 9...40%
Android OS 8.1.0...18%
Android OS 8.0.0...16%
Android OS 7.0...14%
Android OS 6.0.1...9%
---------
Managed Stack Trace:

**java.lang.NullPointerException: GoogleSignInAccount must not be null**
com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source)
com.google.android.gms.games.Games.getPlayersClient(com.google.android.gms:play-services-games@@18.0.1:70)
com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
com.unity3d.player.ReflectionHelper.a(Unknown Source)
com.unity3d.player.ReflectionHelper$1.invoke(Unknown Source)
java.lang.reflect.Proxy.invoke(Proxy.java:813)
$Proxy13.onResult(Unknown Source)
com.google.games.bridge.TokenPendingResult.setStatus(TokenPendingResult.java:135)
com.google.games.bridge.SignInRequest.setSuccess(SignInRequest.java:244)
com.google.games.bridge.SignInRequest.access$000(SignInRequest.java:28)
com.google.games.bridge.SignInRequest$1.onComplete(SignInRequest.java:117)
com.google.android.gms.tasks.zzj.run(Unknown Source)
android.os.Handler.handleCallback(Handler.java:751)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:154)
android.app.ActivityThread.main(ActivityThread.java:6776)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._CallStatic[ReturnType] (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
GooglePlayGames.Android.AndroidClient+<>c__DisplayClass18_0.<Authenticate>b__0 (System.Int32 result) (at <00000000000000000000000000000000>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <00000000000000000000000000000000>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, System.IntPtr jmethodName, System.IntPtr jargs) (at <00000000000000000000000000000000>:0)
Rethrow as TargetInvocationException: GooglePlayGames.Android.AndroidTokenClient+ResultCallbackProxy.onResult(UnityEngine.AndroidJavaObject)
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, System.IntPtr jmethodName, System.IntPtr jargs) (at <00000000000000000000000000000000>:0)

**Comment by thekingofpsycho** [comment]
There was no such bug before building to 64-bit.

**Comment by olehkuznetsov** [comment]
Is it possible signOut is called during sign-in? Can it be something like double tap on sign-in button?

**Comment by thekingofpsycho** [comment]
> Is it possible signOut is called during sign-in? Can it be something like double tap on sign-in button?

no. This is not a bug originally. It only happens on certain devices after building in 64-bit.

**Comment by orbitalnine** [comment]
Have you made any progress on this? I'm getting this when using 10.06 on my pixel device (64bit).

**Comment by ritro** [comment]
Happened to me too (the unity version is different here, but the bug is the same):

![image](https://user-images.githubusercontent.com/3658820/70889535-e3f1a580-1ff3-11ea-8550-6aa3e5a3b050.png)

The same with Samsung's SM-A***

**Comment by laloix** [comment]
Having same issue on a samsung s7 edge. I also tried on a samsung s9 but it was working fine there.
Any way to fix this?

**Comment by ozdemir08** [comment]
We encountered a bug affecting sign-in and have pushed out a fix with Play Games. Thank you to everyone that brought it to our attention and we apologize for any inconvenience caused.
