### ISSUE TITLE
Google Play Games leaderboard error after uploading score

### ISSUE THREAD

**Issue by ShadowMuffin** [playgameservices/play-games-plugin-for-unity#2802]
I have a problem with google play games which is probably because I messed with the console too much: 

I am implementing a simple leaderboard in my game (it's not on unity by the way, but I don't think it really matters since the code is from the google api docs), and for some reason, whenever I open the leaderboard before submitting a score it shows that it is empty, but after I upload something to it, and enter it again, it says that there is an error in google play games.

**Comment by olehkuznetsov** [comment]
Have you tried our samples using leaderboards?
