### ISSUE TITLE
Upgrading to 0.10.6: Timestamps 0/empty

### ISSUE THREAD

**Issue by habitoti** [playgameservices/play-games-plugin-for-unity#2804]
Hi,

the match and invitation creation timestamps and match modification timestamp (introduced with 0.9.63) deliver only 0 with 0.10.6. Still worked with 0.9.64.

Regards, habitoti

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
