### ISSUE TITLE
Save game not worked!!

### ISSUE THREAD

**Issue by dksviolin** [playgameservices/play-games-plugin-for-unity#2806]
The Google api console captures requests well.

But nothing happens on the device.

![image](https://user-images.githubusercontent.com/24646389/70412255-b195f480-1a97-11ea-8bd7-df590f961d87.png)

**Comment by olehkuznetsov** [comment]
Can you check if your game has enabled save games in play console, please?

**Comment by ozdemir08** [comment]
Feel free to reopen it if you are still having this issue.
