### ISSUE TITLE
Popup does not display when unlocking Achievements

### ISSUE THREAD

**Issue by orbitalnine** [playgameservices/play-games-plugin-for-unity#2811]
I'm using 0.9.64 and Unity 2019.1.14.

I'm able to sign in to Google Play Games, view the Achievements overlay, increment, and unlock achievements ok, but the little popup that displays when a new achievement is unlocked doesn't display.

Has anyone else ran into this problem?

I do see some exceptions immediately after the achievement is unlocked, but I haven't been able to figure out the cause yet.

"
12-11 22:11:27.162: I/Unity(17717): Achievement  (CgkI3drRh70OEAIQBA) was successfully unlocked.
12-11 22:11:27.162: I/Unity(17717): Achievement.Unlock result = True
12-11 22:11:27.166: E/StatusOperation(11464): Killing (on development devices) due to RuntimeException
12-11 22:11:27.166: E/StatusOperation(11464): java.lang.NullPointerException: Null uri
12-11 22:11:27.166: E/StatusOperation(11464): 	at bfb.<init>(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):2)
12-11 22:11:27.166: E/StatusOperation(11464): 	at bfd.a(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):1)
12-11 22:11:27.166: E/StatusOperation(11464): 	at ekv.a(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):92)
12-11 22:11:27.166: E/StatusOperation(11464): 	at cwv.a(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):261)
12-11 22:11:27.166: E/StatusOperation(11464): 	at eal.b(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):5)
12-11 22:11:27.166: E/StatusOperation(11464): 	at dzo.a(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):2)
12-11 22:11:27.166: E/StatusOperation(11464): 	at bkf.a(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):8)
12-11 22:11:27.166: E/StatusOperation(11464): 	at bkc.run(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):1)
12-11 22:11:27.166: E/StatusOperation(11464): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-11 22:11:27.166: E/StatusOperation(11464): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-11 22:11:27.166: E/StatusOperation(11464): 	at java.lang.Thread.run(Thread.java:919)
12-11 22:11:27.170: I/DropBoxManagerService(905): add tag=system_app_wtf isTagEnabled=true flags=0x2
12-11 22:11:27.166: E/StatusOperation(11464): Killing (on development devices) due to RuntimeException
12-11 22:11:27.166: E/StatusOperation(11464): java.lang.NullPointerException: Null uri
12-11 22:11:27.166: E/StatusOperation(11464): 	at bfb.<init>(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):2)
12-11 22:11:27.166: E/StatusOperation(11464): 	at bfd.a(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):1)
12-11 22:11:27.166: E/StatusOperation(11464): 	at ekv.a(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):92)
12-11 22:11:27.166: E/StatusOperation(11464): 	at cwv.a(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):261)
12-11 22:11:27.166: E/StatusOperation(11464): 	at eal.b(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):5)
12-11 22:11:27.166: E/StatusOperation(11464): 	at dzo.a(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):2)
12-11 22:11:27.166: E/StatusOperation(11464): 	at bkf.a(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):8)
12-11 22:11:27.166: E/StatusOperation(11464): 	at bkc.run(:com.google.android.play.games.services@138330040@2019.10.13833 (278694777.278694777-000400):1)
12-11 22:11:27.166: E/StatusOperation(11464): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-11 22:11:27.166: E/StatusOperation(11464): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-11 22:11:27.166: E/StatusOperation(11464): 	at java.lang.Thread.run(Thread.java:919)
"

**Comment by ozdemir08** [comment]
Do you have the same issue with v10.06?

**Comment by orbitalnine** [comment]
I've been having trouble upgrading to v10.06, so I can't confirm yet.

First I got an error stating that I have duplicate classes in androidx.core.core and com.android.support.support-compact. Removing com.android.support.spport-compact seemed to fix this and allow me to build, but i don't know for certain this isn't causing any problems.

Next, when I try to sign into Google Play Games using v10.06 I get:

12-13 15:38:20.570: I/Unity(13747):  [Play Games Plugin DLL] 12/13/19 15:38:20 -08:00 DEBUG: Attempting to sign in to Google Play Game Services.
12-13 15:38:20.570: I/Unity(13747):  [Play Games Plugin DLL] 12/13/19 15:38:20 -08:00 DEBUG: Creating platform-specific Play Games client.
12-13 15:38:20.570: I/Unity(13747):  [Play Games Plugin DLL] 12/13/19 15:38:20 -08:00 DEBUG: Creating Android IPlayGamesClient Client
12-13 15:38:20.676: W/GamesServiceBroker(2671): Client connected with SDK 12451000, Services 19831037, and Games 144480048
12-13 15:38:20.731: E/AbstractServiceBroker(2671): Getting service failed
12-13 15:38:20.731: E/AbstractServiceBroker(2671): java.lang.NullPointerException: Account cannot be null.
12-13 15:38:20.731: E/AbstractServiceBroker(2671): 	at byh.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):2)
12-13 15:38:20.731: E/AbstractServiceBroker(2671): 	at dzi.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):23)
12-13 15:38:20.731: E/AbstractServiceBroker(2671): 	at bvk.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):32)
12-13 15:38:20.731: E/AbstractServiceBroker(2671): 	at bwb.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):55)
12-13 15:38:20.731: E/AbstractServiceBroker(2671): 	at bqg.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):7)
12-13 15:38:20.731: E/AbstractServiceBroker(2671): 	at bqk.run(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):4)
12-13 15:38:20.731: E/AbstractServiceBroker(2671): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
12-13 15:38:20.731: E/AbstractServiceBroker(2671): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-13 15:38:20.731: E/AbstractServiceBroker(2671): 	at cdz.b(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):15)
12-13 15:38:20.731: E/AbstractServiceBroker(2671): 	at cdz.run(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):10)
12-13 15:38:20.731: E/AbstractServiceBroker(2671): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-13 15:38:20.731: E/AbstractServiceBroker(2671): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-13 15:38:20.731: E/AbstractServiceBroker(2671): 	at tej.run(Unknown Source:7)
12-13 15:38:20.731: E/AbstractServiceBroker(2671): 	at java.lang.Thread.run(Thread.java:919)
12-13 15:38:20.732: W/GmsClient(2671): IGmsServiceBroker.getService failed
12-13 15:38:20.732: W/GmsClient(2671): java.lang.NullPointerException: Account cannot be null.
12-13 15:38:20.732: W/GmsClient(2671): 	at byh.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):2)
12-13 15:38:20.732: W/GmsClient(2671): 	at dzi.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):23)
12-13 15:38:20.732: W/GmsClient(2671): 	at bvk.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):32)
12-13 15:38:20.732: W/GmsClient(2671): 	at bwb.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):55)
12-13 15:38:20.732: W/GmsClient(2671): 	at bqg.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):7)
12-13 15:38:20.732: W/GmsClient(2671): 	at bqk.run(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):4)
12-13 15:38:20.732: W/GmsClient(2671): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
12-13 15:38:20.732: W/GmsClient(2671): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-13 15:38:20.732: W/GmsClient(2671): 	at cdz.b(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):15)
12-13 15:38:20.732: W/GmsClient(2671): 	at cdz.run(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):10)
12-13 15:38:20.732: W/GmsClient(2671): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-13 15:38:20.732: W/GmsClient(2671): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-13 15:38:20.732: W/GmsClient(2671): 	at tej.run(Unknown Source:7)
12-13 15:38:20.732: W/GmsClient(2671): 	at java.lang.Thread.run(Thread.java:919)
12-13 15:38:20.732: W/GamesLogHelper(2671): Failed to log event: bmo{statusCode=INTERNAL_ERROR, resolution=null, message=null}

**Comment by orbitalnine** [comment]
I was able to work out my duplicate class problem by updating some ad sdks that were pre androidx. I still get the above error many times, and then finally this one kills the game:

12-13 19:25:37.917: E/AndroidRuntime(29025): FATAL EXCEPTION: lowpool[12]
12-13 19:25:37.917: E/AndroidRuntime(29025): Process: com.google.android.gms, PID: 29025
12-13 19:25:37.917: E/AndroidRuntime(29025): java.lang.IllegalArgumentException: Upsert affected multiple rows
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at bzx.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):25)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at bzx.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):19)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at com.google.android.gms.games.provider.PlayGamesContentProvider.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):538)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at bzx.insert(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):4)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at qtp.insert(:com.google.android.gms@19831037@19.8.31 (120400-284611645):4)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at android.content.ContentProviderOperation.applyInternal(ContentProviderOperation.java:321)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:309)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at bzx.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):14)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at bzx.applyBatch(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):3)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at duv.applyBatch(:com.google.android.gms@19831037@19.8.31 (120400-284611645):3)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at android.content.ContentProvider.applyBatch(ContentProvider.java:2117)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:371)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at android.content.ContentResolver.applyBatch(ContentResolver.java:1875)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at cxs.b(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):29)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at czv.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):279)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at czv.b(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):22)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at cxy.c(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):2)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at dzo.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):7)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at dzr.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):4)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at bkv.run(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):1)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at cdz.b(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):15)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at cdz.run(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):10)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at tej.run(Unknown Source:7)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	at java.lang.Thread.run(Thread.java:919)
12-13 19:25:37.917: E/AndroidRuntime(29025): 	Suppressed: gmi: 
12-13 19:25:37.917: E/AndroidRuntime(29025): 		at tk_trace.games-PlayGamesSignInIntentService_onStartCommand(Unknown Source:0)

**Comment by orbitalnine** [comment]
An update on this. I'm back to using 0.9.64 for now. I still receive several "Account cannot be null" null pointer exceptions when unlocking an achievement. But the popups are now displaying correctly. The problem seemed to be that I hadn't set the achievements icons yet (in the game services console), so they could be unlocked and would show in the Achievements Overlay, but the popup required that the achievement be fully defined I guess, which requires the icon graphic. An undocumented requirement, or maybe a bug on Google's part as they do have a default icon. Anyway this is probably not a bug for this library, so I'll close this issue.
