### ISSUE TITLE
GPGS Suddenly Stopped Working

### ISSUE THREAD

**Issue by nashmia-riaz** [playgameservices/play-games-plugin-for-unity#2813]
Hello! I've been developing and testing a small game that's integrated with this plugin for little over a year. My game has leaderboards and real-time multiplayer that works with GPGS.

Today, all the services related to this API stopped working. The game fails to sign in with one of my accounts and shows 'blank' errors in the log. It signs in with the other account but fails to retrieve the leaderboard giving the error attached below.

Keep in mind that both my accounts have been working with GPGS before, they're added to the testers list and I've been using them for almost a year. 

I tried to re-add the accounts to the testers list, delete my app's cache and storage, updated the plugin and set it up again. None of it has helped me resolve the issue.

Any help will be appreciated, thank you!

**Comment by Bluecat52** [comment]
It seems that Google Play has discontinued the Real-Time multiplayer entirely... Unfortunately I'm unaware of a alternative at this time. :/

**Comment by nashmia-riaz** [comment]
Hello, @Bluecat52 . Thanks for the reply. Can you link me to any source on this? Also, why would this cause issues on login?

**Comment by wbigoljr** [comment]
Have you tried updating Play Games app? It has a bug that prevents some games from logging in.

**Comment by nashmia-riaz** [comment]
@wbigoljr, as of today, my app managed to log in but the game would freeze after login after the Play Games update.

**Comment by wbigoljr** [comment]
Have you tried re-installing your game? Play games data may be corrupted.

**Comment by olehkuznetsov** [comment]
> the leaderboard giving the error attached below.

I can't see any error attached. Can you add it, please?

**Comment by nashmia-riaz** [comment]
@wbigoljr, I tried my app after deleting it's storage, Play Games storage, did a fresh reinstall and it just simply no longer works.

@olehkuznetsov sorry for not attaching the screenshot! I no longer have anything in the debugger for when my app logs in but freezes. It just simply stops working, and I've not changed anything in the code. The only variable so far has been the issue with Play Games plugin, coming forward since the login issue.

**Comment by nashmia-riaz** [comment]
Thanks for the time and help, everyone! After 2 days of debugging, I finally figured out what was causing my game to suddenly freeze. The game gets stuck trying to retrieve leaderboard data. Hence, I will be closing this issue and opening up a new one that's more appropriately titled.
