### ISSUE TITLE
Can not Authenticate

### ISSUE THREAD

**Issue by cosmicmosmic** [playgameservices/play-games-plugin-for-unity#2814]
The issue has suddenly occurred two days ago.

Failed Reason : Authentication canceled
I am using GPGS 0.9.64
When i try GPGS 10.06, it occur same issue.

12-15 01:10:31.462: E/AbstractServiceBroker(25470): Getting service failed
12-15 01:10:31.462: E/AbstractServiceBroker(25470): java.lang.NullPointerException: Account cannot be null.
12-15 01:10:31.462: E/AbstractServiceBroker(25470): 	at byh.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):2)
12-15 01:10:31.462: E/AbstractServiceBroker(25470): 	at dzi.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):23)
12-15 01:10:31.462: E/AbstractServiceBroker(25470): 	at bvk.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):32)
12-15 01:10:31.462: E/AbstractServiceBroker(25470): 	at bwb.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):55)
12-15 01:10:31.462: E/AbstractServiceBroker(25470): 	at bqg.a(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):7)
12-15 01:10:31.462: E/AbstractServiceBroker(25470): 	at bqk.run(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):4)
12-15 01:10:31.462: E/AbstractServiceBroker(25470): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
12-15 01:10:31.462: E/AbstractServiceBroker(25470): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-15 01:10:31.462: E/AbstractServiceBroker(25470): 	at cdz.b(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):15)
12-15 01:10:31.462: E/AbstractServiceBroker(25470): 	at cdz.run(:com.google.android.play.games.services@144480040@2019.11.14448 (284081242.284081242-000400):10)
12-15 01:10:31.462: E/AbstractServiceBroker(25470): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-15 01:10:31.462: E/AbstractServiceBroker(25470): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-15 01:10:31.462: E/AbstractServiceBroker(25470): 	at tfn.run(Unknown Source:7)
12-15 01:10:31.462: E/AbstractServiceBroker(25470): 	at java.lang.Thread.run(Thread.java:764)

**Comment by wbigoljr** [comment]
Google play games app just got updated. Can you please see if it fixed the problem?

**Comment by orbitalnine** [comment]
I'm seeing the the same problem with 0.9.64 and 10.06. It started yesterday and was working the day before that. One other point to mention is that it's only on my main developer account, when I try using another account that I just added into my Game Services Testing section it can login ok. Seems like something might be going on with a change on the server side?

**Comment by orbitalnine** [comment]
Tried updating the Google Play Games app with the update released on Dec 13, and now I can login using the account that previously had trouble. I still see a lot of "java.lang.NullPointerException: Account cannot be null" errors in the log during sign on, but now at least I can login.

**Comment by wbigoljr** [comment]
It was updated just an hour ago with note that says:" Fixed a bug which was causing sign-in issues". Google have been very lazy testing their software these days.

**Comment by cosmicmosmic** [comment]
Thank you for your answer!
My google play account is working well now.
but some our game's users have same issue.
But I think it will be solved soon. 
I'll let you know again in 1~2 day
