### ISSUE TITLE
login not show 

### ISSUE THREAD

**Issue by ikfir** [playgameservices/play-games-plugin-for-unity#2817]
``

    public void load()
    {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();
            PlayGamesPlatform.InitializeInstance(config);
            PlayGamesPlatform.DebugLogEnabled = true;
            PlayGamesPlatform.Activate();

            Social.localUser.Authenticate(success =>
        {
            if (success)
            {
                SceneManager.LoadScene("Main menu");
                maintext.text = "Welcome " + Social.localUser.userName;
                maintext2.text = "Welcome " + Social.localUser.userName;

            }
            else
            {
                maintext2.text = "Could not login to Google Play Games Services";
                maintext.text = "Could not login to Google Play Games Services";
                maintext.color = new Color(0.82f, 0.09f, 0f);
            }
        });

    }
``
Every time I open the app it does not show me that I have to log in with an account of why it is and how I arrange because even for the first time it does not show. 
How i fix this.

 thanks for the help

**Comment by ikfir** [comment]
i find the how to fix it

**Comment by nashmia-riaz** [comment]
Hey how did you manage to fix this?

**Comment by ikfir** [comment]
ok first Go to unity [Edit -> Project Settings -> Publishing Settings -> Minify -> Release: NONE,Debug:NONE]
this how i fix it try it if you need help tell me. 

kfir botnik ☺

**Comment by nashmia-riaz** [comment]
Thanks for the help! Unfortunately I already had that set and it didn't work for me :(

**Comment by ikfir** [comment]
try
        {
            PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();
            PlayGamesPlatform.InitializeInstance(config);
            PlayGamesPlatform.Activate();
            Social.localUser.Authenticate(success =>
            {
                if (success)
                {
                    SceneManager.LoadScene("Main menu");
                    Debug.Log("Welcome "+ Social.localUser.userName);

                }
                else
                {
                     Debug.Log("Could not login to Google Play Games Services");
                }
            });
        }
        catch (Exception e)
        {
             Debug.Log("Error: "+e.Message);
        }
this is my code for GPGS Authentication try to use this.
try it on your phone please.

**Comment by nashmia-riaz** [comment]
Thanks for the snippet! I tried it and it doesn't work for me. I have an app that was working fine up until the recent Play Games update. I guess it's either a bug in my setup or something on the plugin's side. Thanks for your time, though! :)

**Comment by Blaxor** [comment]
> ok first Go to unity [Edit -> Project Settings -> Publishing Settings -> Minify -> Release: NONE,Debug:NONE]
> this how i fix it try it if you need help tell me.
> 
> kfir botnik ☺

Worked for me thx

**Comment by ikfir** [comment]
you welcome

**Comment by olehkuznetsov** [comment]
If you want to use minification just check this [README.md section](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/README.md#decreasing-apk-size)
