### ISSUE TITLE
FetchAllSavedGames()  LastModifiedTimestamp & TotalTimePlayed empty/incorrect

### ISSUE THREAD

**Issue by akasurreal** [playgameservices/play-games-plugin-for-unity#2819]
FetchAllSavedGames() is returning incorrect/blank data for LastModifiedTimestamp and TotalTimePlayed in 0.10.06.  

TotalTimePlayed is always 0 and LastModifiedTimestamp is always 01/01/1970 00:00:00

I went back to 0.9.64 and it still works as expected.

**Comment by ZombossKP** [comment]
LastModifiedTimestamp returns 01/01/1970 00:00:00 even in single save for me.

**Comment by ozdemir08** [comment]
It should be fixed in v10.07. If you still have a problem with it, feel free to open this issue again, this time including your code using FetchAllSavedGames.

**Comment by murat303** [comment]
this still continues v10.07
