### ISSUE TITLE
RTMP not connecting, destroying my app's store ranking

### ISSUE THREAD

**Issue by famishedmammal** [playgameservices/play-games-plugin-for-unity#2820]
Hi, I know RTMP is being shut down March 30th 2020, but I updated my play-games-plugin to the most recent version last week, and now none of my users can connect to RTMP matches whatsoever. I didn't change the implementation at all, just updated play-games-plugin, which now makes my app unusable. We were planning on slowly switching our networking system by March, but since we've updated and everything broke, our players are FURIOUS and it's destroying our app's rating. Not to mention the crash rate is through the roof with the new GPGS-plugin update. We can't change anything over December (christmas holiday), so I guess our Google Play Store ranking is permanently ruined

**Comment by nashmia-riaz** [comment]
Hello! I don't know if this is related, but I've been seeing issues with login to begin with, leading up to RTMP. It feels like the whole plugin is broken. Perhaps, your users are having similar problems, starting with the login? It really stinks to see the play games plugin in this state.

**Comment by famishedmammal** [comment]
Hello, we are removing Google Play Services from our project permanently. Not going to let shoddy plugin updates ruin our store ranking

**Comment by olehkuznetsov** [comment]
Sorry to hear this. There is no RTMP related visible changes on our charts. One known issue during last days was with sign-in for some users which is already fixed in latest PGA. 
But we will recheck RTMP in our samples with latest plugin anyway. Thanks for reporting.
