### ISSUE TITLE
Previously working game now freezes on LoadScores

### ISSUE THREAD

**Issue by nashmia-riaz** [playgameservices/play-games-plugin-for-unity#2822]
Hello, everyone! 

Ever since the PGA update, I've been struggling trying to get my app back on track. It's something I'd been working on for a year and was near release. 

Now, my app freezes on trying to get leaderboard data for top players in my leaderboard. This is something that was previously working and just simply broke a couple of days ago.

My exact line of code is:
```
if (PlayGamesPlatform.Instance.IsAuthenticated())
{
            PlayGamesPlatform.Instance.LoadScores(
            ID,
            LeaderboardStart.TopScores,
            7,
            LeaderboardCollection.Public,
            LeaderboardTimeSpan.AllTime,
            (data) =>
            {
               . . .
            });
}
```

Here, ID is retrieved from the GPGSIds script that's created upon set up and is passed to the function that contains this snippet of code.

I really want to emphasize the fact that this had been working up until the PGA update. I have not made any changes to my code and it follows the tutorial for set up given on this repository very closely.

Any help will be greatly appreciated. Thank you!

**Comment by olehkuznetsov** [comment]
Can you copy/paste corresponding logcat parts, please?
Also can you just try to do nothing in your callback 
```
            (data) =>
            {
               . . .
            }
```
to be sure it is not the callback code issues, please?

**Comment by nashmia-riaz** [comment]
Thank you for getting back to me!

I did as you said and took out any code in my callback. The logcat shows me this and the game still freezes:
![image](https://user-images.githubusercontent.com/13387692/71723039-0f152b00-2e23-11ea-96d1-623afcaf6a28.png)

"Displaying scores for x" is a line I print for debugging purposes after scores are retrieved and passed to a function that shows them in GUI. I have a check in LoadScores that sees if data.Valid, but that check returns true (i.e. data is valid) and goes on to the next function.

I would also like to mention that I've noticed the same issue when I try to report scores. My code for that is as follows:

```
PlayGamesPlatform.Instance.ReportScore(score, leaderboardID, (bool success) => {    
        if (success)
        {
            Debug.Log("Posted Score of " + score);
        }
        else
        {
            Debug.Log("Failed to post score");
        }
 });
```

The log here again shows me no errors, and is similar to the one I attached above

**Comment by nashmia-riaz** [comment]
I have yet to hear back on this and am wondering if it's fixed. My project and a year's worth of hardwork is left hanging because of this bug. If anyone can read this, can you please update me on the progress?

**Comment by olehkuznetsov** [comment]
Why do you load scores yourself are you replacing default provided leaderboard UI?

**Comment by nashmia-riaz** [comment]
Yes, of course!

**Comment by olehkuznetsov** [comment]
It's not clear to me which moment does it freeze? Is it only 4 entries in log and after that freeze?

**Comment by nashmia-riaz** [comment]
Yes, right after. It freezes on the call for leaderboards, so the function call for either ReportScore or LoadScores causes the game to freeze. Having an empty call function does not help either, as we've discussed earlier.

**Comment by olehkuznetsov** [comment]
Can you try to load just top 3 players instead of 7 will it help?

**Comment by nashmia-riaz** [comment]
Still freezes :(
Is there any update to the code I should consider?

**Comment by olehkuznetsov** [comment]
if you are using v0.10.06 there is no updates after that to leaderboard code on the plugin side.

Can you show more logcat lines for this freeze, please? Or just create a bugreport it should contain missing logcat lines as well.

**Comment by nashmia-riaz** [comment]
I will try to generate a bug report and get back to you today

**Comment by frolky** [comment]
There seems to be a server-side problem, because the scores are not loaded in any way. All plugin versions, requests in the Playground API, GPG application - everything causes a freeze. Scores stop loading after sending a score on this day. The percentage of ANR in my game has already exceeded the allowable threshold.

**Comment by nashmia-riaz** [comment]
[Here's](https://drive.google.com/open?id=1kDB7B1utrUin9NvwDchR1WWo1aQ9kKyg) the bug report @olehkuznetsov. Line 161038 is where you can see the first instance of my "displaying scores" debug line.

@frolky, maybe I'm doing something wrong but I never get the LoadScore failed error. It just freeezes for me and causes my phone to be unresponsive for a good few seconds. Nonetheless, I appreciate your help and would love to get this fixed so my app can be back on track.

**Comment by ozdemir08** [comment]
@frolky The #2829 issue that you opened had started with a different issue and then steered towards this one. Let's leave the "LoadScores API in v10.06 returning returning scores for all time issue" to that one and discuss ANRs and LoadScore failures here. Just to be clear about where we are now: 

1. You have a game in prod right now and the percentage of ANR has exceeded the allowable threshold. Can you verify that the ANR number has started increasing after Play Games sign in issue? Also what plugin version is the game in prod using? 

2. You mentioned [here](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2829#issuecomment-573532301) that ReportScore breaks the leaderboard. Can you clarify this? Does it cause the app freezing, does it crash or anything else? Also, can you verify that sign in happens without any problems?

3. Based on your comment here, you look to have tried different plugin versions and got problems with each of them. Can we say that using v9 versions is causing freezes and using v10 causes "LoadScore failed" errors? 

4. You might have already tried this. But when you use a different account, do you get the same problems? 
 
5. Can you create a bug report and share it with us? 

6. Also can you explicitly right here the steps that consistently produce these issues?

**Comment by ozdemir08** [comment]
@nashmia-riaz Can you answer the following questions that could help us investigate the issue? 

1. What plugin version are you using? Can you try v9.64 and v10.06 and let us know the outcomes? 

2. Can you verify that authentication finishes successfully? 

3. Can you try if the default leaderboard UI is working fine or not? Please see [this](147397911). 

4. What happens when you try a different account? 

5. Can you reproduce the issue with the Smoke test sample app? You can download it [here](https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/samples/SmokeTest) and update [this line](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/samples/SmokeTest/Source/Assets/SmokeTest/LeaderboardGUI.cs#L184) to try it.

**Comment by ozdemir08** [comment]
@nashmia-riaz also I cannot see an ANR in this bug report. Can you capture another bug report, please?

**Comment by frolky** [comment]
> @frolky The #2829 issue that you opened had started with a different issue and then steered towards this one. Let's leave the "LoadScores API in v10.06 returning returning scores for all time issue" to that one and discuss ANRs and LoadScore failures here. Just to be clear about where we are now:
> 
> 1. You have a game in prod right now and the percentage of ANR has exceeded the allowable threshold. Can you verify that the ANR number has started increasing after Play Games sign in issue? Also what plugin version is the game in prod using?
> 2. You mentioned [here](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2829#issuecomment-573532301) that ReportScore breaks the leaderboard. Can you clarify this? Does it cause the app freezing, does it crash or anything else? Also, can you verify that sign in happens without any problems?
> 3. Based on your comment here, you look to have tried different plugin versions and got problems with each of them. Can we say that using v9 versions is causing freezes and using v10 causes "LoadScore failed" errors?
> 4. You might have already tried this. But when you use a different account, do you get the same problems?
> 5. Can you create a bug report and share it with us?
> 6. Also can you explicitly right here the steps that consistently produce these issues?

Sorry for my poor English, translated through google.
1. The percentage of ANR began to increase in mid-December and at that moment there were no updates to the game on my part. The maximum percentage was 2% (0.47% is acceptable). The plugin version was 9.64.
2. The leaderboard loads normally until the first ReportScore call, and then gives an error. On version 9.64, an error and ANR occur in the LeaderboardManager.FetchScoreSummary method (C++). On version 10.06, an error occurs in the loadMoreScores method (Java).
3. 9th version causes both error and ANR, and 10th version only error.
4. Yes, I used three accounts.
5. ANR
`"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x765148b0 self=0x7f81440a00
  | sysTid=29123 nice=-10 cgrp=default sched=0/0 handle=0x7f8531aaa0
  | state=S schedstat=( 6941072865 9384900811 15441 ) utm=461 stm=233 core=2 HZ=100
  | stack=0x7fc926b000-0x7fc926d000 stackSize=8MB
  | held mutexes=
  #00  pc 000000000001bf30  /system/lib64/libc.so (syscall+32)
  #01  pc 0000000000067a1c  /system/lib64/libc.so (pthread_cond_timedwait+152)
  #02  pc 000000000024e798  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (std::__ndk1::condition_variable::__do_timed_wait(std::__ndk1::unique_lock<std::__ndk1::mutex>&, std::__ndk1::chrono::time_point<std::__ndk1::chrono::system_clock, std::__ndk1::chrono::duration<long long, std::__ndk1::ratio<1l, 1000000000l> > >)+108)
  #03  pc 000000000019a224  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (std::__ndk1::cv_status std::__ndk1::condition_variable::wait_for<long long, std::__ndk1::ratio<1l, 1000000000l> >(std::__ndk1::unique_lock<std::__ndk1::mutex>&, std::__ndk1::chrono::duration<long long, std::__ndk1::ratio<1l, 1000000000l> > const&)+156)
  #04  pc 000000000019a164  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (std::__ndk1::cv_status std::__ndk1::condition_variable::wait_until<std::__ndk1::chrono::steady_clock, std::__ndk1::chrono::duration<long long, std::__ndk1::ratio<1l, 1000000000l> > >(std::__ndk1::unique_lock<std::__ndk1::mutex>&, std::__ndk1::chrono::time_point<std::__ndk1::chrono::steady_clock, std::__ndk1::chrono::duration<long long, std::__ndk1::ratio<1l, 1000000000l> > > const&)+52)
  #05  pc 000000000019a0fc  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (???)
  #06  pc 0000000000195450  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (???)
  #07  pc 000000000019529c  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (gpg::AndroidGameServicesImpl::PerformSignOut(bool)+432)
  #08  pc 00000000001f3d38  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (gpg::GameServicesImpl::HandleForcedSignOut()+116)
  #09  pc 00000000001c16a8  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (???)
  #10  pc 00000000001c1258  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (???)
  #11  pc 00000000001c0e0c  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (gpg::AndroidGameServicesImpl::LeaderboardFetchScoreSummaryOperation::Translate(gpg::JavaReference&&)+40)
  #12  pc 00000000001c1648  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (???)
  #13  pc 00000000001c15c4  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (???)
  #14  pc 00000000001c1590  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (???)
  #15  pc 000000000018fe7c  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (???)
  #16  pc 00000000001b6558  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (???)
  #17  pc 00000000001b4928  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (???)
  #18  pc 00000000001b443c  /data/app/com.fkgames.minitruckergame-2/lib/arm64/libgpg.so (gpg::NativeOnResult(_JNIEnv*, _jobject*, _jobject*)+60)
  #19  pc 00000000000001cc  /data/data/com.fkgames.minitruckergame/app_.gpg.classloader/2e190de0913242cfb3e30a895073c67e_games.dex (Java_com_google_android_gms_games_NativeSdkCallbacks_onResult__Lcom_google_android_gms_common_api_Result_2+152)
  at com.google.android.gms.games.NativeSdkCallbacks.onResult (Native method)
  at com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler.handleMessage (unavailable:10)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:163)
  at android.app.ActivityThread.main (ActivityThread.java:6393)
  at java.lang.reflect.Method.invoke! (Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:933)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:823)`
6.
- call LoadScores (success)
- ReportScore call (failure)
- call LoadScores (failure)

**Comment by nashmia-riaz** [comment]
> @nashmia-riaz Can you answer the following questions that could help us investigate the issue?
> 
> 1. What plugin version are you using? Can you try v9.64 and v10.06 and let us know the outcomes?
> 2. Can you verify that authentication finishes successfully?
> 3. Can you try if the default leaderboard UI is working fine or not? Please see [this](147397911).
> 4. What happens when you try a different account?
> 5. Can you reproduce the issue with the Smoke test sample app? You can download it [here](https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/samples/SmokeTest) and update [this line](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/samples/SmokeTest/Source/Assets/SmokeTest/LeaderboardGUI.cs#L184) to try it.

@ozdemir08 I generated a new report but do not see any ANR still. My phone does freeze to the point where the game is entirely not reponding (any background animations freeze as they are), but no ANR in the report.

1. I'm using v10.06, but I can confirm the same error on v9.64.
2. As far as I know, I'm being logged in. It notifies me on my phone, and here's my corrsponding debug log 
![image](https://user-images.githubusercontent.com/13387692/72684298-4c421400-3ad7-11ea-8560-40c9b8d89588.png)
3. The link gave me a 404, but I can confirm Leaderboard UI works.
4. Other accounts freeze as well
5. Smoketest freezes as well for me in a similar manner. DoLoadLeaderboard works but DoPublicLoadScores (which reflects what I'm trying to do) freezes.

**Comment by ozdemir08** [comment]
Thanks both of you for the answers. We are looking into them. 

@frolky can you also let me know on what devices and what Android versions you see the issue most?

**Comment by frolky** [comment]
@ozdemir08 according to Google Play Console statistics and player reviews, the problem appears on devices running Android 8-9, but it also appeared on my device running Android 7.
![image](https://user-images.githubusercontent.com/50167505/72866497-120e8780-3d0e-11ea-9b01-df0e3df292bb.png)

**Comment by nashmia-riaz** [comment]
I hate to be that person, but I'm awaiting any updates on this.

**Comment by olehkuznetsov** [comment]
If that freeze is still reproduces for you can you check your Google Play Games installed version, please? And to check if updating to latest version helps?

**Comment by ozdemir08** [comment]
Latest version of Play Games should be fixing this issue. Feel free to reopen it if you still have the same issue.

**Comment by frolky** [comment]
The problem returned on version 12
