### ISSUE TITLE
unity gpgs report score not upload how to fix

### ISSUE THREAD

**Issue by ikfir** [playgameservices/play-games-plugin-for-unity#2826]
This is my code:

         Social.ReportScore (score, GPGSIds.leaderboard_best_score, success =>
         {
             Debug.Log (success? "Reported score successfully:" + SavingData.bestscore (): "Failed to 
              report score");
 
         });

But it does not cost Google's servers I think!

**Comment by nashmia-riaz** [comment]
Hello! Does your game freeze on anything related to leaderboards? I have somewhat of a similar issue

**Comment by olehkuznetsov** [comment]
Can you attach a copy/paste of corresponding logcat part, please?

**Comment by olehkuznetsov** [comment]
Can you clarify is your callback called with success == false or not called at all?

**Comment by ozdemir08** [comment]
Feel free to reopen it, if you are still having the same issue.

**Comment by ikfir** [comment]
For fix it you need to do this:
Project Settings -> Player -> Publishing settings -> Minify -> Release = none and Debug = none
