### ISSUE TITLE
Social.localUser.userName sometimes empty

### ISSUE THREAD

**Issue by Voresh** [playgameservices/play-games-plugin-for-unity#2831]
Sometimes after login in gpgs username is empty. I use this property in Social.localUser.Authenticate callback or at the next frame after it.
Unity version 2019.1.13f1, gpgs version is 0.10.06

**Comment by Voresh** [comment]
Social.localUser.id is empty too.
If it is important it fails on second sign in in session

**Comment by Voresh** [comment]
if I wait for it in coroutine it appears after some time

**Comment by inanoglu** [comment]
You can return it like this;

public string GetUsername()
    {      
            if (Social.localUser.authenticated)
                return Social.localUser.userName;
    }
