### ISSUE TITLE
Some devices get stuck trying to sign in 

### ISSUE THREAD

**Issue by liranjulia** [playgameservices/play-games-plugin-for-unity#2834]
We have a significant number of players complaining that they get stuck trying to connect to the play services (it works fine for most players though). According to some players, the connecting circle just spins infinitely and they can't pass the loading screen. One or two stated that if you press the back button it continues into the game without ever connecting to Google Play Services. We haven't been able to reproduce it ourselves so we have no logs. It happens mostly on devices with Android 10, but I think there was one or two Android 9s. Pasting some of the comments we got:

![image](https://user-images.githubusercontent.com/17096360/72831663-949e3500-3c83-11ea-8647-a5457df9dfe4.png)

![image](https://user-images.githubusercontent.com/17096360/72832058-5c4b2680-3c84-11ea-9944-02c508f9a9c0.png)

![image](https://user-images.githubusercontent.com/17096360/72832085-75ec6e00-3c84-11ea-8a15-7ab0b6111ea3.png)

![image](https://user-images.githubusercontent.com/17096360/72832177-ab915700-3c84-11ea-83c8-04ac681f9ef5.png)

![image](https://user-images.githubusercontent.com/17096360/72832244-ca8fe900-3c84-11ea-82dc-97ddc3ab52a3.png)

**Comment by spacepluk** [comment]
Let me know if there's anything we can do to help debug this.

**Comment by ozdemir08** [comment]
If you can reproduce the bug, it would be great to have a bug report.

**Comment by spacepluk** [comment]
We've tried, but unfortunately we can't reproduce it in any of our devices :/

**Comment by paraboxx** [comment]
Which version of the plugin are you using?

**Comment by spacepluk** [comment]
We were using the latest release v0.10.06, but we have now reverted to v0.9.64 and we are waiting for feedback.

**Comment by zorro-dev** [comment]
У меня такая же проблема на 10 андроиде вот какие логи кидает, позже скину полностью 
E/AbstractServiceBroker: Getting service failed
    java.lang.NullPointerException: Account cannot be null.
И вот это 
W/GmsClient: IGmsServiceBroker.getService failed
    java.lang.NullPointerException: Account cannot be null.

**Comment by liranjulia** [comment]
We are still getting complaints from users with Android 10 that they can't sign into Google Play on v0.9.64. Any updates?

**Comment by zorro-dev** [comment]
Я вернулся на 0.9.64 и у меня все работает на 10 андроиде

**Comment by drallcom3** [comment]
I'm having the same issue with 0.10.06. Basically all Android 9 & 10 devices can't log in with GPG. No idea about 8. It always works on 7 (meaning it's not a config issue).

_Social.localUser.Authenticate() simply always returns false on 10._ Sometimes on Android 9. My Android 7 devices return true on any build.
https://pastebin.com/u7uXKYDn (Android 10)

When I swap back to **0.9.64** everything suddenly works fine. The 0.10.x version are just not useful right now...

**Comment by ozdemir08** [comment]
We encountered a bug affecting sign-in and have pushed out a fix with Play Games. Thank you to everyone that brought it to our attention and we apologize for any inconvenience caused.

**Comment by skolwind** [comment]
> We encountered a bug affecting sign-in and have pushed out a fix with Play Games. Thank you to everyone that brought it to our attention and we apologize for any inconvenience caused.

@ozdemir08 can you clarify how I can the fix? Do I need to update something?

**Comment by ozdemir08** [comment]
You don't need to update anything. As your users update their Play Games, they will be able to sign in without any issues.

**Comment by rico345100** [comment]
Yes, same issue here. Recently got loads of bad reviews to cause this.

**Comment by murilobast** [comment]
Same here, this issue still persists. Can't reproduce it on any of my devices but still get some reviews of people having the issue on Android 10-11. Anyone managed to find a solution?
