### ISSUE TITLE
Auth crashes the game on startup

### ISSUE THREAD

**Issue by dbidwell94** [playgameservices/play-games-plugin-for-unity#2837]
I have the auth method in the Awake() (and I have tried in Start() as well)

No matter what I try: the game not only hangs in the editor on Auth (so in the beginning of the startup) but crashes on any phone i test it on.

I have tried using Social auth() AND PlayGamesPlatform auth() they both crash the device. My game relies on Firebase storage for level sharing and I need auth to work (it was working before I updated the plugin). 

			PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
			.RequestServerAuthCode(false)
			.Build();
			PlayGamesPlatform.InitializeInstance(config);
			PlayGamesPlatform.Activate();
			Debug.LogError("Activated PlayGamesPlatform");
			PlayGamesPlatform.Instance.Authenticate((bool success) => {
			if (success)
			{
			FirebaseManager.GoogleConfigDone = true;
			FirebaseManager.FirebaseLogin();
			}
			});

That's my login code and firebase is handled in a different class. Unfortunately that code is never reached because bool success is ALWAYS false in editor and crashes on android build.

**Comment by olehkuznetsov** [comment]
Can you add related logcat entries, please?
