### ISSUE TITLE
Can't load leaderboard users images from google play game service

### ISSUE THREAD

**Issue by hansschaa** [playgameservices/play-games-plugin-for-unity#2838]
this is my code, but never load the avatar, thanks people.

https://pastebin.com/GHkt6fmN?fbclid=IwAR1WuP-ajU2zcztrIKumPLVh114dLgawTNlKzJKYYWHMNWd3nZC76s71SXg

**Comment by DoofahSoftware** [comment]
I'm also having an issue with user profile images not loading, but it only affects some devices. For example, it works okay on a Galaxy S6, but the same app fails to load user avatars on a Galaxy S10. PlayGamesUserProfile.LoadImage returns an unknown error on the S10.

**Comment by Fellhuhn** [comment]
Make sure to replace the avatar's URL from http to https. Otherwise it won't load.

**Comment by olehkuznetsov** [comment]
Probably it should help if you replace http:// by https:// in returned avatar url

**Comment by DoofahSoftware** [comment]
I tried that, didn't seem to make any difference in my case.

**Comment by techGuyAj** [comment]
Is this issue is Solved??

Thank you.

**Comment by olehkuznetsov** [comment]
Yes, service should return only https links now. Do you have similar issue?

**Comment by techGuyAj** [comment]
> Yes, service should return only https links now. Do you have similar issue?

Thank you for the reply.
Yes.
 I am implementing Leaderboards for my unity game. So in my game i made custom ui to show the leaderboard list . When i tried to get the list ,i am getting the list .I am getting scores ,usernames. But the image is getting null. In my game i am getting null reference exception.

so my question is can we really  get the avatar photo of the list of people from leaderboard?

If yes .How can i implement it?


Thank you.

**Comment by olehkuznetsov** [comment]
How do you get images for leaderboard users?
Do you use LoadUsers?

**Comment by techGuyAj** [comment]
> How do you get images for leaderboard users?
> Do you use LoadUsers?


Yes.
I am using the method load users.

Is there any method I can use??

Thank you

**Comment by hansschaa** [comment]
> 
> 
> How do you get images for leaderboard users?
> Do you use LoadUsers?

Yes i can, but i dont remember how specifically,  I think the problem was due to the fact that the loading of images must be done asynchronously, so when loading them you will receive null if you don't wait for them. Maybe I can find the code, give me a few hours. Attached capture that if you can. 
![145432482_419037259347310_8824060589441157252_n](https://user-images.githubusercontent.com/13873346/106620876-4ef09980-6572-11eb-8380-26de572de88e.jpg)

**Comment by hansschaa** [comment]
This is the complete code for load users of my game, its ugly but works!

[Code](https://pastebin.pl/view/e8e9a084)

**Comment by techGuyAj** [comment]
> This is the complete code for load users of my game, its ugly but works!
> 
> [Code](https://pastebin.pl/view/e8e9a084)

Thank you so much bro .
I will try it .
I will get back you with the result.
Thank you ☺️

**Comment by techGuyAj** [comment]
> This is the complete code for load users of my game, its ugly but works!
> 
> [Code](https://pastebin.pl/view/e8e9a084)

Thank you so much bro.
It worked.
