### ISSUE TITLE
Send Unreliable Message to Self??

### ISSUE THREAD

**Issue by lagzda** [playgameservices/play-games-plugin-for-unity#284]
Hello. So I had this great idea to erase any possibilities for lag. Each player would send the input from their controllers to himself and to others so everyone receives the same data and everything is in sync. 
The problem is that it's written that you can't actually send a message to yourself, but some options that are written in the API reference make me believe otherwise. Please tell me why is that not supported and how would I go differently about this... 
Thanks.

**Comment by claywilkinson** [comment]
Tracking internally as 19128967

**Comment by claywilkinson** [comment]
Upon further review, this does not really make sense during multi-player games, there are messages between the players, there is not a server involved.  See https://developers.google.com/games/services/common/concepts/realtimeMultiplayer for details. So sending messages to your self will always have a latency of 0.  I think what you are looking would need to be done by sending a message to all the  other players, then they respond with a message indicating when they got it.  This way you would have 3 times:
1. the time you sent the message
2. the time the other player received the message
3. the time you received the message from the other player

Then you can calculate the latency between all players and adjust your logic accordingly.
