### ISSUE TITLE
[Discussion] Are there actually any problem to use playservice in other platform aside from android?

### ISSUE THREAD

**Issue by Thaina** [playgameservices/play-games-plugin-for-unity#2840]
While android natively support play service by default, play service still have REST api to be called from any platform anyway. So are there really a problem at all to just use REST api on other platform such as IOS, desktop and webgl ? Is it any limitation or prohibition from google?

If not I think I would like to try implement the REST client into this plugin, will there be any problem?

**Comment by olehkuznetsov** [comment]
The problem will be if user haven't game profile and it need to be created. As currently it can be done only on Android.
