### ISSUE TITLE
*Possible mitaken empty statement* - Android Unity Game

### ISSUE THREAD

**Issue by Azbouby** [playgameservices/play-games-plugin-for-unity#2841]
Hello,
I'm working on a Android game and I implemented the google play service 2months ago (worked fine). And then I update the plugin package with the last version up to date, I have deleted the folder GamePlayStore before and make the setup android, reboot my pc etc..

And this error/warning appear
![Capture](https://user-images.githubusercontent.com/5004597/74476649-11e74f00-4eaa-11ea-831d-7f8e21f3356c.PNG)

Do I am the only one having this issue ?
On this post https://github.com/playgameservices/play-games-plugin-for-unity/issues/2687 they said that the update fix the issue but not for me

Any suggestion ?

Thanks

**Comment by olehkuznetsov** [comment]
It will be fixed in 0.10.07 release
