### ISSUE TITLE
[0.10.07] Social.localUser.Authenticate() fails

### ISSUE THREAD

**Issue by drallcom3** [playgameservices/play-games-plugin-for-unity#2844]
All my Android 9 & 10 devices can't log in with Google Play. No idea about 8. It always works on 7 (meaning it's not a config issue).

Social.localUser.Authenticate() simply always returns false on  Android 10. My Android 7 devices return true on any build and can log in fine.
https://pastebin.com/u7uXKYDn (The log was from 0.10.06, but the issue is exactly the same)

When I swap back to 0.9.64 everything suddenly works fine.
0.10.06 has the same issue.

**Comment by olehkuznetsov** [comment]
>02/10 15:02:26.616 26972 27016 Error Unity: Authentication Failed: Make sure you add your account to testers.
Have you checked if account you are using is in testers list?

**Comment by drallcom3** [comment]
It's set to public (and the accounts are in the tester list). Also if I simply switch the version to 0.9.64 I can log in with that same account, meaning accounts are not to blame.
To me it looks like it's **not** a configuration issue.

**Comment by nashmia-riaz** [comment]
@drallcom3 I had similar issue. I just couldn't manage to log in. I noticed that my client IDs did not match. But despite linking my console app properly, it would still return the error code "canceled". 

I eventually had to add a new game under "game services" and link a new console app instance to get it to work again.

**Comment by jordygarcias** [comment]
I got a similar error. It says the authentication was cancelled but it does not say why.

`DEBUG: Authentication canceled`

Is what I get in the logcat.

**Comment by firtinapd** [comment]
I get a similar issue, it says authentication canceled, but it does actually eventually authenticate, if I call it again after a few seconds it succeeds... I think there are bad timeouts somewhere.

I tested by creating a scene with a button:
```
public void ButtonPress()
    {
        text.text += "Logging in...";
        
        Social.localUser.Authenticate((b, s) => { text.text += $@"
Authenticate result: result({b}) message({s}).
"; });
    }
```

When I first press the button, the Google Play Services popup appears on the screen, and it's connecting. Then a few seconds later I get the callback with failure. The popup is still there though. Eventually the popup shows me my username and level. After that if I press the button again, the callback gets called with success.

**Comment by firtinapd** [comment]
Also confirming 0.9.64 works but 0.10.06 has the issue

**Comment by drallcom3** [comment]
0.10.08 still has that issue.

Reminder: It's not a config issue, since simply swapping the folder for 0.9.64 makes it work.

**Comment by TheLLspectre** [comment]
I already have the same issue, i'm running on Unity 2019.2.10f and 0.10.08 Google Play Services plugin. The popup appear and try to log me and then disappear....

I check my certificate and it's good.
I check the client ID and it's good.
So i'm thinking it's coming from the internal version and not public one but according from the top of issue it's not ! 

And i've this error appear in my logcat:
```
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator ****
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator **** APP NOT CORRECTLY CONFIGURED TO USE GOOGLE PLAY GAME SERVICES
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator **** This is usually caused by one of these reasons:
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator **** (1) Your package name and certificate fingerprint do not match
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator ****     the client ID you registered in Developer Console.
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator **** (2) Your App ID was incorrectly entered.
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator **** (3) Your game settings have not been published and you are 
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator ****     trying to log in with an account that is not listed as
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator ****     a test account.
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator ****
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator **** To help you debug, here is the information about this app
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator **** Package name         : com.TheRed**********
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator **** Cert SHA1 fingerprint: 3D:2D:***********************************************************
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator **** App ID from manifest : 7358*********
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator ****
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator **** Check that the above information matches your setup in 
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator **** Developer Console. Also, check that you're logging in with the
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator **** right account (it should be listed in the Testers section if
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator **** your project is not yet published).
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator ****
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator **** For more information, refer to the troubleshooting guide:
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator ****   http://developers.google.com/games/services/android/troubleshooting
2020/04/23 17:40:04.030 24143 5418 Error SignInAuthenticator ****
```

And that's quit funny because everything is ok !

So now i'm going to try to downgrade the plugin version and i tell you ;)

**Comment by olehkuznetsov** [comment]
Have you checked play console and there is that package name/sha1 pair application linked like shown in log?
