### ISSUE TITLE
Leaderboard report score breaks leaderboard (0.10.07, 2019.3.2f1)

### ISSUE THREAD

**Issue by TheOneVries** [playgameservices/play-games-plugin-for-unity#2847]
Testing leaderboards with minimal prototype (buttons to set score, submit score, call leaderboard, and similar simple direct functions).
Oddly enough this prototype worked fine until today. Today the following happens:
- Starting up game and showing leaderboard works as expected.
- Submit new score (using either Social.Report or PlayGamesPlatform.Instance.ReportScore) seems to work (I get a successful callback)
- Trying to to show leaderboards after score submission results in a **"Hmm, something went wrong in play games".**

This is only the case with leaderboards I tried to update. Other boards still show up.
Restarting the game doesn't fix the issue, nor does clearing cache. Clearing cache _and_ uninstalling the game helps (I can show leaderboards again), but leaderboards display old highscores, not the submitted one that caused the leaderboard to malfunction.

I didn't actually change any code between the prototype working and stopping to work. Originally I was using 0.10.06 (both when leaderboards worked and stopped working). Upgraded to 0.10.07 to see if this resolved it, but the issue persisted.

Feels like a Play Games issue rather than something with the plugin honestly...

[edit] App is "draft" in Google Play console, apk uploaded in internal test track release, without testers assigned.

probably dupe:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/2827

**Comment by TheOneVries** [comment]
After snooping around I decided to try a downvoted solution from stackoverflow, and it actually seemed to work; re-linking the app in the google play console (and updating the clientID in unity with the new code generated by this linking) got the leaderboards to be responsive again.

**Comment by itthingsyt** [comment]
ENG: Thanks for the solution? Can you say me how i can re-link the app?
RU: У тебя скрин на русском(предыдущее обсуждение), поэтому если удобнее, то можно по-русски)

**Comment by TheOneVries** [comment]
In google play Game services, go to linked apps, and do "link another app". Link it to the same package you did before (and possibly authorize it). You'll get a new client ID. This new Client ID you use in your unity configuration (windows > google play games > setup > android setup). You can then delete the old linked app entry from your google play services. For me this relinking solved the issue.

**Comment by itthingsyt** [comment]
> In google play Game services, go to linked apps, and do "link another app". Link it to the same package you did before (and possibly authorize it). You'll get a new client ID. This new Client ID you use in your unity configuration (windows > google play games > setup > android setup). You can then delete the old linked app entry from your google play services. For me this relinking solved the issue.

I cant delete the old linked app( Can i miss it?

**Comment by TheOneVries** [comment]
If you click on the linked app, there is a remove button at the bottom

**Comment by itthingsyt** [comment]
![image](https://user-images.githubusercontent.com/58787859/76113764-c41bbd80-5ff5-11ea-89b5-e5fe3810db72.png)

**Comment by itthingsyt** [comment]
> If you click on the linked app, there is a remove button at the bottom

Thanks, it helped. But it works localy(testing api on the phone), and in google play it works in the old state(leaderboards dont work). Did you collide with such problem?

**Comment by TheOneVries** [comment]
Sorry, for me these stepped solved all leaderboard issues. Before leaderboards did not update for me either, but they do now.

**Comment by itthingsyt** [comment]
OK. How many clients do you have in Google api dashboard? 1 or 2?
7 мар 2020 г. 1:05 пользователь "TheOneVries" <notifications@github.com>
написал:

**Comment by TheOneVries** [comment]
Clients? You mean linked apps? Just 1. But honestly I don't think I can be of much more help here. If this is a persisting issue for you, you should consider posting it as an issue (although I think the issue os with google play services, not this plugin).

**Comment by itthingsyt** [comment]
Oh, sorry, I was mistaken in the explanation. Credentials, where we put
sha1 and package of the app.
7 мар 2020 г. 1:51 пользователь "TheOneVries" <notifications@github.com>
написал:
