### ISSUE TITLE
Can't Sign In

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [playgameservices/play-games-plugin-for-unity#2851]
Unable to sign in when         Social.localUser.Authenticate (ProcessAuthentication);
called.
After calling this line "Connecting to play services" appears then processing circle and then nothing.
And Doesn't sign in.
Play game services version - Latest
Admob Unity Version - Latest
unity 2019.20f1
Help

**Comment by Fellhuhn** [comment]
There are two usual things to consider:
- Do you have a @googlemail address? Those don't work anymore (switch to @gmail)
- Do you have mutliple accounts registered on your device? Remove those and keep one.

**Comment by jordygarcias** [comment]
> There are two usual things to consider:
> 
> * Do you have a @googlemail address? Those don't work anymore (switch to @gmail)
> * Do you have mutliple accounts registered on your device? Remove those and keep one.

So It does not work anymore with multiple accounst? You need to have only one account registered to make this work?

**Comment by olehkuznetsov** [comment]
Does it happen on Android 10 device? Can you check which version of Play Games app do you have installed, please?

**Comment by jordygarcias** [comment]
In my case it happens in Play Games version 2020.02.16549. In an Android version 7.0, with the 0.10.07 version of the plugin

**Comment by olehkuznetsov** [comment]
Is it infinity spinner for you? Can you share your logcat during sign-in process, please?

**Comment by jordygarcias** [comment]
Is not infinity, it show the "Establishing connection" message, then nothing.

The logcat only says "Authentication cancelled"

![image](https://user-images.githubusercontent.com/58491711/76098625-6a80a800-5f8f-11ea-95ac-c7df83b80298.png)

**Comment by olehkuznetsov** [comment]
In this case it seems as configuration issue. You need to check if Auth Screen is set up properly in cloud console. And if SHA1/package_name pair was added correctly in play console

**Comment by MuhammadWaqasOfficial** [comment]
Sorry Guys my bad. I forget to publish the game in game services at developer console.
Its working.
