### ISSUE TITLE
can't sign in, game stuck.

### ISSUE THREAD

**Issue by NehaDomadiya** [playgameservices/play-games-plugin-for-unity#2852]
Unable to sign in.

`PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
                .EnableSavedGames()
                .RequestEmail()
                .Build();
            PlayGamesPlatform.InitializeInstance(config);
            PlayGamesPlatform.DebugLogEnabled = true;
            PlayGamesPlatform.Activate();`

When try to sign in it shows a pop up for permission. Create edit and delete your google play games activity. I clicked on Deny. 
![Screenshot_20200309-123058](https://user-images.githubusercontent.com/61960676/76192989-0d902680-6209-11ea-8657-5d6cf5a3e703.png)
Next pop up shows view and manage its own configuration data in your Google Drive
![Screenshot_20200309-123105](https://user-images.githubusercontent.com/61960676/76193007-1aad1580-6209-11ea-8a19-11fc3d2ecdb8.png)

Showed for confirm your choice
![Screenshot_20200309-123125](https://user-images.githubusercontent.com/61960676/76193041-2bf62200-6209-11ea-96a9-ba231dcfc05e.png)

it showed only allow and cancel option.

![Screenshot_20200309-123137](https://user-images.githubusercontent.com/61960676/76193236-9018e600-6209-11ea-9b94-46f247b75719.png)

Clicked on allow.
The game stuck.
[Stuck_log.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/4305266/Stuck_log.txt)

**Comment by ozdemir08** [comment]
Thanks for raising this issue. We have identified the problem and are working on a fix. It shouldn't require any updates to your code and you shouldn't need to update the Unity plugin We'll update this issue when the fix becomes available. In the meantime, PGS sign-in should continue to work as long as you grant access to "Create edit and delete your google play games activity" and, if you use PGS Cloud Save, "View and manage its own configuration data in Google Drive".

**Comment by NehaDomadiya** [comment]
thank you for the update.

**Comment by ozdemir08** [comment]
It should be fixed now. Can you try it again and let us know if you still have the same issue?

**Comment by NehaDomadiya** [comment]
Thank you! it is fixed.
