### ISSUE TITLE
Authenticate callback can be invoked on the wrong thread

### ISSUE THREAD

**Issue by JPerryOddGames** [playgameservices/play-games-plugin-for-unity#2853]
Problem occurs in the `AndroidClient.Authenticate(bool silent, Action<SignInStatus> callback)` method. There are 5 references to the callback parameter, 4 of which wrap the invocation with the `InvokeCallbackOnGameThread` method.

The callback is invoked with SignInStatus.Success at line 166 inside a closure lambda method that is executed as a task continuation. This needs to ensure the callback runs on the game thread much like other invocations.

Plugin version: 0.10.07 (current latest)
Unity version: 2018.4.12f1

**Comment by ozdemir08** [comment]
Thanks for flagging this. I'll fix it today and make a new release.

**Comment by AbstractLee** [comment]
"Invoking user callback on game thread" Is this bug caused？

**Comment by Diamonds0a** [comment]
> Thanks for flagging this. I'll fix it today and make a new release.

Was this a new bug with the 10 version? or does it backdate to the 9.x versions?

Also will the fix be in 10.8 ?

**Comment by ozdemir08** [comment]
It's a new bug with v0.10.07. It's actually a one line change. [This line](https://github.com/playgameservices/play-games-plugin-for-unity/blob/1c2d294ef8eeb2aeb77ce3e88a9eb2cee5b292e4/source/PluginDev/Assets/GooglePlayGames/Platforms/Android/AndroidClient.cs#L166) should be exactly like [this](https://github.com/playgameservices/play-games-plugin-for-unity/blob/1c2d294ef8eeb2aeb77ce3e88a9eb2cee5b292e4/source/PluginDev/Assets/GooglePlayGames/Platforms/Android/AndroidClient.cs#L80). I couldn't made the release yet but now you can use the v.0.10.07 doing this one line change.

**Comment by ozdemir08** [comment]
v0.10.08 is released now.
