### ISSUE TITLE
Authentication still works after deleting the game data from Google Play app.

### ISSUE THREAD

**Issue by drotat** [playgameservices/play-games-plugin-for-unity#2855]
Hello,

So the problem is that the user is getting authenticated after manually deleting game data from Google Play app.
If the user delete's the data from Google Play app, but he keeps the game, than he still be able to authenticate successfully, but only on the first use.

How to reproduce.
1. Authenticate user and save progress on cloud using play games plugin.
2. Open Google Play app and delete game data of the authenticated app.
3. Reopen the game, and it will be authenticated successfuly, but trying to load the saved game from cloud using `OpenWithAutomaticConflictResolution  ` will return "internal_error".
4. Reopen the app and try to sign in again, but this time it will trigger google signin popup and user will be asked for permissions to authenticate, as it should be happen i guess.

Plugin version v0.10.07.
Android 10 on Samsung Galaxy s9.
Unity 2019.3.2.

**Comment by ozdemir08** [comment]
This should be fixed with the latest version. Now any server call at 3 will return SIGN_IN_REQUIRED and sign the user out. The next sign in attempt at 4 will be as the first sign-in attempt. Please let us know if the issue persists.
