### ISSUE TITLE
Stuck in infinite loading after un-checking permission "create edit and delete your google play games activity" 

### ISSUE THREAD

**Issue by Alon-Katz** [playgameservices/play-games-plugin-for-unity#2858]
Hey,

I had the play games authentication working for a while now, but I noticed that every time I tried to authenticate the popup was showing me an option to un-check a permission the was called: "create edit and delete your google play games activity". After I un-checked the permission, the app is stuck in a continuous loading. There are no errors or any debug logs printed.

The code I used:
```
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().RequestEmail().RequestServerAuthCode(false).Build();

PlayGamesPlatform.DebugLogEnabled = true;
PlayGamesPlatform.InitializeInstance(config);
PlayGamesPlatform.Activate();
```

And then to authenticate:
```
Social.localUser.Authenticate((bool success) =>
                    {
                        return success; // This is never called anymore
                    });
```
I upgraded my plugin to latest GooglePlayGamesPlugin-0.10.07 and I tried both disconnecting and deleting my play games profile but nothing helps, its always stuck when logging with the user that removed the permission.
Trying to login with a different user works great and for the user that removed the permission it was working great before..

What should I do?

Thanks!

**Comment by ozdemir08** [comment]
Probably the same issue with [this](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2852). We're looking into it.

**Comment by NehaDomadiya** [comment]
Do you see same popup while login?

**Comment by Alon-Katz** [comment]
> Do you see same popup mention in link from ozdemir08 while login?
> @ozdemir08 can you please provide more details?

I do see the option "create edit and delete your google play games activity" anymore.

This is what I see:
![Screenshot_2020-03-18-12-24-40-209_com google android (1)](https://user-images.githubusercontent.com/7746785/76951317-2e94fd80-6914-11ea-930a-fe6c931c4d17.png)


Pressing allow will result in the endless loading screen

**Comment by ozdemir08** [comment]
Thanks for raising this issue.  We have identified the problem and are working on a fix. It shouldn't require any updates to your code and you shouldn't need to update the Unity plugin  We'll update this issue when the fix becomes available. In the meantime, PGS sign-in should continue to work as long as you grant access to "Create edit and delete your google play games activity" and, if you use PGS Cloud Save, "View and manage its own configuration data in Google Drive".

**Comment by ozdemir08** [comment]
It should be fixed now. Can you try it again and let us know if you still have the same issue?

**Comment by Alon-Katz** [comment]
Hey, its working great now. Thanks!

**Comment by ozdemir08** [comment]
Great! Closing this issue then!

**Comment by fsilvestrim** [comment]
Hello @ozdemir08, was this bug closed on the Google end or via an update? I'm implementing Play Games SignIn natively (Android/Java) and I'm still having this problem with requestIdToken and if the user unchecked the permission grant checkbox and clicked "Allow". I keep getting this infinite loading screen and my app is stuck. Not even revoking the permissions or cleaning the Play Games cache fixes it. Sorry if this isn't the right place to ask this but here is the only place where I found something related to my problem. Thanks in advance.
