### ISSUE TITLE
The leaderboard is not showing up at all Unity

### ISSUE THREAD

**Issue by Cinemato** [playgameservices/play-games-plugin-for-unity#2859]
I have been trying for weeks now but nothing works. It refuses to show anything. Nothing happens when I press the button. Here are my scripts: 

This is the controller:
    ` public class PlayGamesController : MonoBehaviour
     {
     void Start()
     {
         AuthenticateUser();
     }

    void AuthenticateUser()
    {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();
        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.Activate();
        Social.localUser.Authenticate((success) =>
        {
            if (success == true)
            {
                Debug.Log("Logged in");
            }

            else
            {
                Debug.LogError("Failed to log in");
            }
        });
       }

    public static void PostToLeaderboard(long newScore, string leaderboard)
    {
        Social.ReportScore(newScore, leaderboard, (bool success) => { });       
    }
            
    public void showLeaderboardUI()
    {
        Social.ShowLeaderboardUI();
    }

 
}
`

I use this one for the button:
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class UIController : MonoBehaviour
{
    public void showLeaderboard()
    {
        Debug.Log("Showing Leaderboard");
    }
} 
`

and I have this code for when the player losses to add the high score: it is in a lose collider script
`PlayGamesController.PostToLeaderboard(PlayerPrefs.GetInt("High Score"), GPGSIds.leaderboard_leaderboard);`

Anyone has any idea on how to fix this? This is the only thing keeping me from releasing my game

**Comment by Cinemato** [comment]
As this is my first post i'm kinda having trouble putting in the code.. sorry for that

**Comment by olehkuznetsov** [comment]
Have you linked your Andorid app in play console? I mean adding proper SHA1/package pair? It's not enough to do that only in cloud console. Also, can you check if you've added your account as a tester in play console, please?
