### ISSUE TITLE
New Sign-in Best Practices APIs

### ISSUE THREAD

**Issue by ozdemir08** [playgameservices/play-games-plugin-for-unity#2867]
Google Play Game Services announces new APIs that help you follow best sign-in practices. Using them will help your users have a seamless sign-in experience, understand what you are asking permission for, and help you have a better understanding of sign-in failures with variety of failure enums rather than a boolean of false. 

Initialize Play Games Platform only with GAMES_LITE scope. 
```csharp
PlayGamesPlatform.InitializeInstance(new PlayGamesClientConfiguration.Builder().Build());
PlayGamesPlatform.Activate();
```

Whenever you start your game, use Authenticate method with **CanPromptOnce**. This will silently sign your user in if possible and will prompt once for ui sign-in if silent sign-in isn’t available. So, if your user wants to be signed in, they will easily stay signed in and do not want to sign in, then they won’t be bothered by sign-in dialogs. 
```csharp
    using GooglePlayGames;
    using UnityEngine.SocialPlatforms;
    ...
    // authenticate user:
    PlayGamesPlatform.Instance.Authenticate(SignInInteractivity.CanPromptOnce, (result) =>{
        // handle results
    });
```

You should still have a sign-in button for your not-yet-signed-in users to sign them in if they want to sign in later. This button should trigger the code below. This can prompt interactive sign-in.

```csharp
    // authenticate user:
    PlayGamesPlatform.Instance.Authenticate(SignInInteractivity.CanPromptAlways, (result) =>{
        // handle results
    });
```

We have started only with **GAMES_LITE** scope. If you need more scopes for your users to use a feature, you can ask them when you need them. This will help your users understand what you are asking permission for and they will be more likely to give you permission.  It will also allow silent sign-in to succeed, because silent sign-in will always fail if you ask for more than GAMES_LITE and, if you use Saved Games, DRIVE.APP_DATA.

```csharp
If (PlayGamesPlatform.Instance.HasPermission("email"))
{
	UseFeature(...);
}
else
{
	PlayGamesPlatform.Instance.RequestPermission("email", result => {
   		// handle results
 	});
}
```

Note that even if you don’t want to follow the best practices, you can still use new authentication method to learn more about sign-in failures. To use only silent sign-in, use **SignInInteractivity.NoPrompt** and to use interactive sign-in, use  **SignInInteractivity.CanPromptAlways** and handle the result enum in the callback.

Please help us improving the plugin by trying this out and reporting us any bugs you find.

**Comment by drallcom3** [comment]
What about Social.localUser.Authenticate()?
There's no PlayGamesPlatform.Instance.Authenticate() used in my project.

**Comment by habitoti** [comment]
Same here -- hope this automagically implements best practice behaviour ;-)

**Comment by ozdemir08** [comment]
> What about Social.localUser.Authenticate()?
> There's no PlayGamesPlatform.Instance.Authenticate() used in my project.

You can still use it and it will work as it was before. But it will not be the best practices behavior. 

> Same here -- hope this automagically implements best practice behaviour ;-)

It doesn't but switching to the best sign-in practices API is actually easy :)

**Comment by firtinapd** [comment]
Hello, the new signing flow works better for manual signin :) However when I try to `RequestPermission("DRIVE.APP_DATA")`  I don't get any popups for permission, and it fails.

I'm trying with different variations of the string (lowercase, or `drive.appdata`, and so on) but I feel like I'm blind coding.

I have two questions:
- Is there a list of the permission strings to use?
- How does the flow work for the user? Do they get a popup for "this app requires this permission, press OK to allow"?

**Comment by ozdemir08** [comment]
Yes, **https://www.googleapis.com/auth/drive.appdata** is the right one for drive. You don't have to consider what scopes this plugin needs as they are automatically included. 

> Is there a list of the permission strings to use?

For now no. We expect you to find the right ones for you [here](https://developers.google.com/identity/protocols/oauth2/scopes). If we see in the future that many developers are using some same extra scopes, then we can create a file and put them there for the ease of use.  

> How does the flow work for the user? Do they get a popup for "this app requires this permission, press OK to allow"?

What happens here is pretty similar to the initial sign-in screen. If a user hasn't given a permission that you are asking for, then they will see a consent screen describing the permission and if they have already given that, then they won't see a ui again and the request will succeed silently.

**Comment by firtinapd** [comment]
Thank you, these work for me now for signing in and getting the right permissions.
