### ISSUE TITLE
Saved Game not working in tutorial

### ISSUE THREAD

**Issue by bazcat** [playgameservices/play-games-plugin-for-unity#2868]
I've been following the tutorial and everything works up to [Saved Games](https://codelabs.developers.google.com/codelabs/playservices_unity/index.html?index=..%2F..index#9), which doesn't and just returns "internal error" in 

```
0001/01/01 00:00:00.000 -1 -1 Info  --------- beginning of main
2020/04/05 18:05:27.439 10895 10909 Info Unity ApplicationInfo com.UniqueCompany756.Lollygagger version 0.1 build e7788f31-6ec5-4054-abb7-9a48e211c325
2020/04/05 18:05:27.660 10895 10909 Debug vulkan searching for layers in '/data/app/com.UniqueCompany756.Lollygagger-1/lib/arm'
2020/04/05 18:05:27.660 10895 10909 Debug vulkan searching for layers in '/data/app/com.UniqueCompany756.Lollygagger-1/base.apk!/lib/armeabi-v7a'
2020/04/05 18:05:32.319 10895 10909 Info Unity (Lollygagger) Signed in!
2020/04/05 18:05:32.319 10895 10909 Info Unity  
2020/04/05 18:05:32.319 10895 10909 Info Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
2020/04/05 18:05:32.319 10895 10909 Info Unity 
2020/04/05 18:06:02.122 10895 10909 Info Unity (Lollygagger) Sharpshooter Increment: True
2020/04/05 18:06:02.122 10895 10909 Info Unity  
2020/04/05 18:06:02.122 10895 10909 Info Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
2020/04/05 18:06:02.122 10895 10909 Info Unity 
2020/04/05 18:06:02.211 10895 10909 Info Unity (Lollygagger) Welcome Unlock: True
2020/04/05 18:06:02.211 10895 10909 Info Unity  
2020/04/05 18:06:02.211 10895 10909 Info Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
2020/04/05 18:06:02.211 10895 10909 Info Unity 
2020/04/05 18:06:58.792 10895 10909 Info Unity (Lollygagger) Saved Game: Reading
2020/04/05 18:06:58.792 10895 10909 Info Unity  
2020/04/05 18:06:58.792 10895 10909 Info Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
2020/04/05 18:06:58.792 10895 10909 Info Unity 
2020/04/05 18:06:58.907 10895 10909 Info Unity (Lollygagger) Leaderboard update success: True
2020/04/05 18:06:58.907 10895 10909 Info Unity  
2020/04/05 18:06:58.907 10895 10909 Info Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
2020/04/05 18:06:58.907 10895 10909 Info Unity 
2020/04/05 18:06:59.161 10895 10909 Info Unity (Lollygagger) Saved Game Read: InternalError
2020/04/05 18:06:59.161 10895 10909 Info Unity  
2020/04/05 18:06:59.161 10895 10909 Info Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
2020/04/05 18:06:59.161 10895 10909 Info Unity 
2020/04/05 18:07:12.061 10895 10909 Info Unity (Lollygagger) Signed in!
2020/04/05 18:07:12.061 10895 10909 Info Unity  
2020/04/05 18:07:12.061 10895 10909 Info Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
2020/04/05 18:07:12.061 10895 10909 Info Unity 
```

This is on Android 7.1.1, and Saved Games is ON in the Developer Console.

**Comment by ThePartyPinguin** [comment]
I would like to add some more to this, seen as I have the same issue

---
I just updated from 0.10.07 to 0.10.08

Before the update everything worked fine except when the user would click on the + icon to create a new save game in the default SavedGameUI, the callback from ShowSelectSavedGameUI() would always return **Null** for the **ISavedGameMetadata** with a status of **SavedGameSelected**.

So by updating the plugin I had hoped to resolve this issue. But now when requesting to show the SavedGameUI I get an **InternalError** as status from the callback.

Yes, the savegames option is enabled in the play console

Below is (I think), all the information needed about the process of creating a new save game in my project. I there is anything else needed please let me know an I provide it asap.

---

Here is the output from logcat when I initialize the playgames platform

    04-06 12:57:02.218: I/Unity(4510): Starting Auth with token client.
    04-06 12:57:02.218: I/Unity(4510):  
    04-06 12:57:02.218: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:02.275: W/Unity(4510): !!! [Play Games Plugin DLL] 04/06/20 12:57:02 +02:00 WARNING: Creating new PlayGamesPlatform
    04-06 12:57:02.275: W/Unity(4510):  
    04-06 12:57:02.275: W/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:02.275: I/Unity(4510):  [Play Games Plugin DLL] 04/06/20 12:57:02 +02:00 DEBUG: Creating platform-specific Play Games client.
    04-06 12:57:02.275: I/Unity(4510):  
    04-06 12:57:02.275: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:02.275: I/Unity(4510):  [Play Games Plugin DLL] 04/06/20 12:57:02 +02:00 DEBUG: Creating Android IPlayGamesClient Client
    04-06 12:57:02.275: I/Unity(4510):  
    04-06 12:57:02.275: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:02.769: I/Unity(4510): Success
    04-06 12:57:02.769: I/Unity(4510):  
    04-06 12:57:02.769: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:02.772: I/Unity(4510): authentication: True
    04-06 12:57:02.772: I/Unity(4510):  
    04-06 12:57:02.772: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:02.802: I/Unity(4510):  [Play Games Plugin DLL] 04/06/20 12:57:02 +02:00 DEBUG: Authentication succeeded
    04-06 12:57:02.802: I/Unity(4510):  
    04-06 12:57:02.802: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:02.802: I/Unity(4510): [ 04-06 12:57:02.805  4510: 4549 D/         ]
    04-06 12:57:02.802: I/Unity(4510): PlayerBase::stop() from IPlayer
    04-06 12:57:03.132: I/Unity(4510):  [Play Games Plugin DLL] 04/06/20 12:57:03 +02:00 DEBUG: Invoking user callback on game thread
    04-06 12:57:03.132: I/Unity(4510):  
    04-06 12:57:03.132: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:03.134: I/Unity(4510): Save games permission requested: Success
    04-06 12:57:03.134: I/Unity(4510):  
    04-06 12:57:03.134: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:03.135: I/Unity(4510): Has permission for, //www.googleapis.com/auth/drive.file
    04-06 12:57:03.138: I/Unity(4510):  
    04-06 12:57:03.138: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:03.436: I/Unity(4510): Initialized
    04-06 12:57:03.436: I/Unity(4510):  
    04-06 12:57:03.436: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:03.447: I/Unity(4510):  [Play Games Plugin DLL] 04/06/20 12:57:03 +02:00 DEBUG: Invoking user callback on game thread
    04-06 12:57:03.447: I/Unity(4510):  
    04-06 12:57:03.447: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:03.447: I/Unity(4510):  [Play Games Plugin DLL] 04/06/20 12:57:03 +02:00 DEBUG: Invoking user callback on game thread
    04-06 12:57:03.447: I/Unity(4510):  
    04-06 12:57:03.447: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:03.569: I/Unity(4510): LoadAchievements failed
    04-06 12:57:03.569: I/Unity(4510):  
    04-06 12:57:03.569: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:03.610: I/Unity(4510):  [Play Games Plugin DLL] 04/06/20 12:57:03 +02:00 DEBUG: Invoking user callback on game thread
    04-06 12:57:03.610: I/Unity(4510):  
    04-06 12:57:03.610: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:06.384: I/Unity(4510): ShowSelectSnapshotUI failed with exception
    04-06 12:57:06.384: I/Unity(4510):  
    04-06 12:57:06.384: I/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

    04-06 12:57:06.393: E/Unity(4510): Creating saveGame failed with status: InternalError
    04-06 12:57:06.393: E/Unity(4510):  
    04-06 12:57:06.393: E/Unity(4510): (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

---

This is how I initialize the play games plugin:

    private void InitPlayGamesPlatform()
    {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
            .EnableSavedGames()
            .AddOauthScope("https://www.googleapis.com/auth/games")
            .AddOauthScope("https://www.googleapis.com/auth/drive.file")
            .Build();

        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.DebugLogEnabled = true;
    }

---
Authentication:

    public void Authenticate(Action<bool> authenticated)
    {
        PlayGamesPlatform.Instance.Authenticate(SignInInteractivity.CanPromptAlways, (result) =>
        {
            Debug.Log(result);

            if (result == SignInStatus.Success)
            {
                PlayGamesPlatform.Instance.SetGravityForPopups(Gravity.TOP);
                authenticated?.Invoke(true);
            }
            else
            {
                Debug.LogError("Authentication failed: " + result);
            }
        });
    }

---
This where I request the required permissions from the user, for the **games** and **drive** scopes:

    private void RequestPermissions(Action callback)
    {
        RequestGamesAccess(() =>
        {
            RequestDriveAccess(callback);
        });
    }

    private void RequestGamesAccess(Action callback)
    {
        if (!PlayGamesPlatform.Instance.HasPermission("https://www.googleapis.com/auth/games"))
        {
            PlayGamesPlatform.Instance.RequestPermission("https://www.googleapis.com/auth/games", (status) =>
            {
                Debug.Log("Save games permission requested: " + status);

                callback?.Invoke();
            });
        }
        else
        {
            Debug.Log("Has permission for, https://www.googleapis.com/auth/games");
            callback?.Invoke();
        }
    }

    private void RequestDriveAccess(Action callback)
    {
        if (!PlayGamesPlatform.Instance.HasPermission("https://www.googleapis.com/auth/drive.file"))
        {
            PlayGamesPlatform.Instance.RequestPermission("https://www.googleapis.com/auth/drive.file", (status) =>
            {
                Debug.Log("Drive permission requested: " + status);

                callback?.Invoke();
            });
        }
        else
        {
            Debug.Log("Has permission for, //www.googleapis.com/auth/drive.file");
            callback?.Invoke();
        }
    }

---
This is what I do when the user wants to create a new savegame:

    public void CreateNewSaveGameMetaData(Action<ICloudSaveGameMetaData, SocialServicesCallbackStatus> onCreated)
    {
        if (PlayGamesPlatform.Instance.IsAuthenticated())
        {
            PlayGamesPlatform.Instance.SavedGame.ShowSelectSavedGameUI("Create a new save game", 15, true, true,
                (status, meta) =>
                {
                    OnSaveGameCreate(status, meta, onCreated);
                });
        }
    }

    private void OnSaveGameCreate(SelectUIStatus status, ISavedGameMetadata saveGameMeta, Action<ICloudSaveGameMetaData, SocialServicesCallbackStatus> onCreated)
    {
        switch (status)
        {
            case SelectUIStatus.SavedGameSelected:
                OpenSaveGameMetaData(saveGameMeta, onCreated);
                break;

            case SelectUIStatus.AuthenticationError:
                onCreated?.Invoke(null, SocialServicesCallbackStatus.NotAuthenticated);
                break;

            case SelectUIStatus.TimeoutError:
                onCreated?.Invoke(null, SocialServicesCallbackStatus.TimedOut);
                break;

            default:
                Debug.LogError("Creating saveGame failed with status: " + status);
                onCreated?.Invoke(null, SocialServicesCallbackStatus.Error);
                break;
        }
    }

**Comment by bazcat** [comment]
Turns out this was a mistake on my side.
@ThePartyPinguin I suggest to open a new bug if yours is a legit issue.
