### ISSUE TITLE
Leaderboard doesn't work

### ISSUE THREAD

**Issue by Laele** [playgameservices/play-games-plugin-for-unity#2869]
hello, i've been trying to use the play services into my mobile game, i only use the leaderboard, i did all  steps but i don't know why i have this issue:

- I tested the leadeboard installing externally the apk and it worked fine, it can log in to play games and show the leaderboard.
- The problem is when i install the apk from the Play store, it only log in to play games, but when i press the button to show the leadeboard, it opens the play games with the title of my leadeboard but it only is loading and nothing appers

- Im confused because i added the 2 SHA-1(in developers console) for testing and publish, in both i can log in succesfully to play games but it only shows the leaderboard with the apk installed externally

Hope anyone can help me
![92333488_587004431902705_519700929830715392_n](https://user-images.githubusercontent.com/49929267/78507471-c46abe00-7745-11ea-8dca-8df9b5c80ad1.jpg)

**Comment by olehkuznetsov** [comment]
Have you added in play console or cloud console? You should link Android app in play console with new SHA1 key.

**Comment by Laele** [comment]
I solved this, thank you for you comment, but i don't know why i had to add twice my game in linked apps, i only have 1 SHA-1 key for publish in console developers -> credentials

**Comment by princlia** [comment]
> I solved this, thank you for you comment, but i don't know why i had to add twice my game in linked apps, i only have 1 SHA-1 key for publish in console developers -> credentials

Add twice game in linked apps also work for me ,Thank you .
