### ISSUE TITLE
InvalidOperationException: There was an error creating a GameServices object

### ISSUE THREAD

**Issue by DeveloperSon** [playgameservices/play-games-plugin-for-unity#2882]
Hello, I'm releasing a game using "GooglePlayGamesPlugin_v0.9.64."
However, the following error is reported intermittently in Unity Error Report.

===========================================================
### InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK
Managed Stack Trace:

GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build (GooglePlayGames.Native.PInvoke.PlatformConfiguration configRef)
GooglePlayGames.Native.NativeClient.InitializeGameServices ()
GooglePlayGames.Native.NativeClient+<Authenticate>c__AnonStorey0.<>m__0 (Int32 result)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args)
UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, IntPtr jmethodName, IntPtr jargs)
Rethrow as TargetInvocationException: GooglePlayGames.Android.AndroidTokenClient+ResultCallbackProxy.onResult(UnityEngine.AndroidJavaObject)
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args)
UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, IntPtr jmethodName, IntPtr jargs)
=============================================================

Unfortunately, we are not being reproduced. :(
However, sometimes (in many cases) users are reporting that cloud data is not normal.

I wonder if the above error report can also affect the load/save of cloud data, and how to fix that problem.

Please help me if anyone has solved the problem.

**Comment by DeveloperSon** [comment]
+ The most frequently occurring version is [Android os 10]. Will updating to the latest version work?

**Comment by olehkuznetsov** [comment]
Yes, update to v0.10.09 should fix it.
