### ISSUE TITLE
Post Guard items required for login

### ISSUE THREAD

**Issue by gnchishti** [playgameservices/play-games-plugin-for-unity#2889]
Hi, I am working on an android project. 

I wish to use Login, Leaderboard and Achievements from plugin so to reduce size of my game I used postguard-user.txt file with 

`
-keep class com.google.android.gms.signin.** { *; }
-keep class com.google.android.gms.common.api.ResultCallback { *; }
-keep class com.google.android.gms.games.achievement.** { *; }
-keep class com.google.android.gms.games.leaderboard.** { *; }
`

But I am getting error 

There was an error creating a GameServices object. Check for log errors from GamesNativeSDK.

Any thing I am doing wrong and  what are items that I need to use from following list for my requirement?

[https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/scripts/proguard.txt](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/scripts/proguard.txt)

**Comment by ozdemir08** [comment]
You should keep all of them. Removing codes for other APIs that you don't use, won't help you gain much. The size difference is negligible. Also if you are still using v9.xx, you can easily migrate to the latest version. As v10s do not depend on C++ SDK, there is a significant size difference. 
If you still see have an error after using all proguard rules, then please share the error logs so we can look into it.

**Comment by gnchishti** [comment]
Actually I’m using google play services along with Facebook sdk and when I build I get dex format error due that I am making gradle build and willing to use required functionality from google play services. I am stuck about a week on this issue and unable to build my game and upload.

Currently I am using 9.50 of google play services I will update to latest and will share results.

I will share log cat if see any error.

**Comment by gnchishti** [comment]
If a google play services version and a Facebook sdk version work together without dex format error that will be good help for me.

**Comment by gnchishti** [comment]
I used lates version of google play services (0.10.09) it did not give dex error but I got this error


`
CommandInvokationFailure: Failed to re-package resources.
/Users/MyUser/Library/Android/sdk/build-tools/29.0.0/aapt package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "/Users/MyUser/Library/Android/sdk/platforms/android-29/android.jar" -F bin/resources.ap_ --extra-packages com.android.vending.billing:com.unity.purchasing.googleplay:com.google.example.games.mainlibproj:android.arch.lifecycle:androidx.arch.core:androidx.asynclayoutinflater:androidx.coordinatorlayout:androidx.core:androidx.cursoradapter:androidx.customview:androidx.documentfile:androidx.drawerlayout:androidx.fragment:androidx.interpolator:androidx.legacy.coreui:androidx.legacy.coreutils:androidx.lifecycle.livedata:androidx.lifecycle.livedata.core:androidx.lifecycle:androidx.lifecycle.viewmodel:androidx.loader:androidx.localbroadcastmanager:androidx.print:androidx.slidingpanelayout:androidx.swiperefreshlayout:androidx.versionedparcelable:androidx.viewpager:com.android.installreferrer:android.support.graphics.drawable.animated:android.support.v7.appcompat:android.support.v7.cardview:android.support.customtabs:android.support.compat:android.support.coreui:android.support.coreutils:android.support.fragment:android.support.mediacompat:android.support.v4:android.support.graphics.drawable:com.facebook.applinks:com.facebook.common:com.facebook.core:com.facebook.login:com.facebook.share:com.google.android.gms.auth.api:com.google.android.gms.auth.api.phone:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms.common:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.tasks:com.google.games.bridge:com.unity.purchasing:com.facebook.android:com.unity3d.ads -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/GoogleAIDL/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/GooglePlay/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/android.arch.lifecycle.runtime-1.0.3/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/androidx.coordinatorlayout.coordinatorlayout-1.0.0/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/androidx.core.core-1.0.0/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.installreferrer.installreferrer-1.0/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.animated-vector-drawable-27.0.2/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.cardview-v7-27.0.2/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.customtabs-27.0.2/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.support-compat-27.0.2/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.support-core-ui-27.0.2/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.support-core-utils-27.0.2/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.support-fragment-27.0.2/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.support-media-compat-27.0.2/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.support-v4-27.0.2/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.support-vector-drawable-27.0.2/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.facebook.android.facebook-common-5.15.3/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.facebook.android.facebook-login-5.15.3/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.facebook.android.facebook-share-5.15.3/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-auth-18.0.0/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-base-17.1.0/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-basement-17.1.1/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.google.games.gpgs-plugin-support-0.10.09/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/common/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/facebook-android-wrapper-7.18.0/res" -S "/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/unity-ads/res"

stderr[
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_action_mode_close_item_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <ImageView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_action_mode_close_item_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <ImageView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_action_mode_close_item_material.xml: note: using v17 attributes; synthesizing resource com.gameTorque.tow:layout/abc_action_mode_close_item_material for configuration v17.
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:scrollIndicators from <ScrollView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_alert_dialog_button_bar_material.xml:26: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <android.support.v7.widget.ButtonBarLayout>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_alert_dialog_button_bar_material.xml: note: using v17 attributes; synthesizing resource com.gameTorque.tow:layout/abc_alert_dialog_button_bar_material for configuration v17.
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_alert_dialog_title_material.xml:45: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.widget.DialogTitle>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_alert_dialog_title_material.xml:36: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <ImageView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_alert_dialog_title_material.xml: note: using v17 attributes; synthesizing resource com.gameTorque.tow:layout/abc_alert_dialog_title_material for configuration v17.
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_dialog_title_material.xml: note: using v17 attributes; synthesizing resource com.gameTorque.tow:layout/abc_dialog_title_material for configuration v17.
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_popup_menu_header_item_layout.xml:24: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_popup_menu_header_item_layout.xml: note: using v17 attributes; synthesizing resource com.gameTorque.tow:layout/abc_popup_menu_header_item_layout for configuration v17.
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_popup_menu_item_layout.xml:59: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <ImageView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_popup_menu_item_layout.xml: note: using v17 attributes; synthesizing resource com.gameTorque.tow:layout/abc_popup_menu_item_layout for configuration v17.
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.widget.ActionBarContainer>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource com.gameTorque.tow:layout/abc_screen_toolbar for configuration v21.
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_search_view.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_search_view.xml: note: using v17 attributes; synthesizing resource com.gameTorque.tow:layout/abc_search_view for configuration v17.
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_select_dialog_material.xml:23: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <view>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.appcompat-v7-27.0.2/res/layout/abc_select_dialog_material.xml: note: using v17 attributes; synthesizing resource com.gameTorque.tow:layout/abc_select_dialog_material for configuration v17.
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.facebook.android.facebook-common-5.15.3/res/layout/com_facebook_device_auth_dialog_fragment.xml:80: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <TextView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.facebook.android.facebook-common-5.15.3/res/layout/com_facebook_device_auth_dialog_fragment.xml:80: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.facebook.android.facebook-common-5.15.3/res/layout/com_facebook_device_auth_dialog_fragment.xml: note: using v17 attributes; synthesizing resource com.gameTorque.tow:layout/com_facebook_device_auth_dialog_fragment for configuration v17.
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.facebook.android.facebook-common-5.15.3/res/layout/com_facebook_smart_device_dialog_fragment.xml:94: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.facebook.android.facebook-common-5.15.3/res/layout/com_facebook_smart_device_dialog_fragment.xml:94: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <TextView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.facebook.android.facebook-common-5.15.3/res/layout/com_facebook_smart_device_dialog_fragment.xml:83: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.facebook.android.facebook-common-5.15.3/res/layout/com_facebook_smart_device_dialog_fragment.xml:83: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <TextView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.facebook.android.facebook-common-5.15.3/res/layout/com_facebook_smart_device_dialog_fragment.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <android.support.v7.widget.AppCompatImageView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.facebook.android.facebook-common-5.15.3/res/layout/com_facebook_smart_device_dialog_fragment.xml: note: using v17 attributes; synthesizing resource com.gameTorque.tow:layout/com_facebook_smart_device_dialog_fragment for configuration v17.
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/androidx.core.core-1.0.0/res/layout/notification_action.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <LinearLayout>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/androidx.core.core-1.0.0/res/layout/notification_action.xml:32: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/androidx.core.core-1.0.0/res/layout/notification_action.xml: note: using v17 attributes; synthesizing resource com.gameTorque.tow:layout/notification_action for configuration v17.
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/androidx.core.core-1.0.0/res/layout/notification_action_tombstone.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <LinearLayout>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/androidx.core.core-1.0.0/res/layout/notification_action_tombstone.xml:37: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/androidx.core.core-1.0.0/res/layout/notification_action_tombstone.xml: note: using v17 attributes; synthesizing resource com.gameTorque.tow:layout/notification_action_tombstone for configuration v17.
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.support-media-compat-27.0.2/res/layout/notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.support-media-compat-27.0.2/res/layout/notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.support-media-compat-27.0.2/res/layout/notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
/Users/MyUser/Projects/Unity/MyProject/Temp/StagingArea/android-libraries/com.android.support.support-media-compat-27.0.2/res/layout/notification_template_big_media.xml:27: note: removing attribute http://s<message truncated>
`

**Comment by gnchishti** [comment]
Here are my findings now

I could not find some solution for above error so I wished to try some more different facebook sdk version. So after trying a lot of older and new facebook sdk versions along with 10.09 google play services.. it kept giving me dex error and whenever I used to remove "android-support-v4" file from facebook sdk it built successful but it gave following exception while initialising facebook at runtime 

`05-15 11:34:16.446 13870-13888/? E/Unity: AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/FacebookActivity;
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/FacebookActivity;
at com.facebook.internal.Validate.hasFacebookActivity(Validate.java:175)
at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:198)
at com.facebook.unity.FB.Init(FB.java:80)
at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
at com.unity3d.player.UnityPlayer.c(Unknown Source)
at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
at android.os.MessageQueue.next(MessageQueue.java:392)
at android.os.Looper.loop(Looper.java:143)
at com.unity3d.player.UnityPlayer$e.run(Unknown Source)` 

so for now rather than wasting time on it... temporarily I left facebook share and uploaded my game but I am waiting for best solution to work these plugins together.

**Comment by ozdemir08** [comment]
I think the Facebook SDK will eventually migrate from android support libraries to androidx, as [new developments](https://developer.android.com/topic/libraries/support-library) will be in the Androidx library. When that happens, I think it will be easier to use them together.
