### ISSUE TITLE
 ERROR: Authentication failed - java.util.concurrent.ExecutionException: 5 out of 5 underlying tasks failed

### ISSUE THREAD

**Issue by bhansalideepika** [playgameservices/play-games-plugin-for-unity#2892]
ERROR: Authentication failed - java.util.concurrent.ExecutionException: 5 out of 5 underlying tasks failed
![image](https://user-images.githubusercontent.com/29816762/82139990-eb8ad400-9849-11ea-9dbf-c3f5757a3bb0.png)

please resolve this getting issue in google play services login
It worked once but now I am not able to login back

**Comment by olehkuznetsov** [comment]
Should be already fixed in 0.10.09

**Comment by gladieweb** [comment]
I have the same issue, I am using 0.12
