### ISSUE TITLE
Load friends still supported?

### ISSUE THREAD

**Issue by matthewmck92** [playgameservices/play-games-plugin-for-unity#2896]
Hello,

I have recently implemented google play games sign in and have started looking at getting friends list. I have copied the code snippet from "Loading Friends" part of the read me and am getting a successful return but an empty friends list. I have read that the social api was removed some years ago but was unsure if this was still the case or if I am doing something wrong? 

Cheers.

**Comment by kilicbatuhan1205** [comment]
LoadFriends will always return an empty list until your publish your game on Google Play.

**Comment by ozdemir08** [comment]
Friends API is available since v10.10. Check out the updated README file to see how to use it.
