### ISSUE TITLE
Stop asking delete the obsolete files.

### ISSUE THREAD

**Issue by rico345100** [playgameservices/play-games-plugin-for-unity#2897]
From some point, this plugin keeps show me to ask to delete the obsolete files.

I had an experience that removing these files causes critical error after build APK, so I just want to keep them exists.

However, even I choose to not gonna delete them, this dialog keeps showing up after each compile and it's very very annoying.

How do I stop asking this dialog?

**Comment by olehkuznetsov** [comment]
Currently it is not possible. You can try to save you project and delete obsolete files.

**Comment by rico345100** [comment]
@olehkuznetsov May I ask why it's not possible? Then what's the point of asking delete?

**Comment by rico345100** [comment]
I had an experience that deletes those obsolete files caused errors after building the game and that's why I'm asking here. What if back up my project and delete obsolete files but cause the problem? Have no idea why you are not any answers.

**Comment by olehkuznetsov** [comment]
It's done by another plugin and old non removed files can cause building errors as well.
