### ISSUE TITLE
what is problem?

### ISSUE THREAD

**Issue by darkofmarin** [playgameservices/play-games-plugin-for-unity#29]
what is problem?

android build and run and error 

if (!Social.localUser.authenticated) {
				// Authenticate
				Social.localUser.Authenticate((bool success) => {
					Debug.Log(success ? "Successfully authenticated" : "Authentication failed.");
				} );
	     }

02-27 22:16:11.131: I/Unity(6153): Exception: No such proxy method: UnityEngine.AndroidJavaRunnableProxy.run()
02-27 22:16:11.131: I/Unity(6153):   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
02-27 22:16:11.131: I/Unity(6153):   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, UnityEngine.AndroidJavaObject[] javaArgs) [0x00000] in <filename unknown>:0 
02-27 22:16:11.131: I/Unity(6153):   at UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, IntPtr jmethodName, IntPtr jargs) [0x00000] in <filename unknown>:0 
02-27 22:16:11.131: I/Unity(6153):  
02-27 22:16:11.131: I/Unity(6153): (Filename:  Line: -1)
02-27 22:16:11.131: I/Unity(6153): Exception: No such proxy method: UnityEngine.AndroidJavaRunnableProxy.run()
02-27 22:16:11.131: I/Unity(6153):   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
02-27 22:16:11.131: I/Unity(6153):   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, UnityEngine.AndroidJavaObject[] javaArgs) [0x00000] in <filename unknown>:0 
02-27 22:16:11.131: I/Unity(6153):   at UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, IntPtr jmethodName, IntPtr jargs) [0x00000] in <filename unknown>:0

**Comment by claywilkinson** [comment]
closing because it is so old.
