### ISSUE TITLE
Google Play Sign In Not Working after using Proguard in Unity

### ISSUE THREAD

**Issue by ademakyazici** [playgameservices/play-games-plugin-for-unity#2901]
My google play services was working just fine before using Proguard. After adding some necessary libraries, my app exceeded 64k dex limit. So i tried to find a way to overcome this issue, so i decided to use Proguard. Yet, even after i place the necessary rules to user-proguard.txt file, google play sign in is still not working. What might cause this issue? Any suggestions?

**Comment by ozdemir08** [comment]
Have you followed instructions [here](https://github.com/playgameservices/play-games-plugin-for-unity#decreasing-apk-size)? If yes, then can you share a bug report?
