### ISSUE TITLE
firebase and play-games-plugin-for-unity duplicate dependencies

### ISSUE THREAD

**Issue by mgrogin** [playgameservices/play-games-plugin-for-unity#2904]
### Please fill in the following fields:
Unity editor version: 2019.2.17f1
Firebase Unity SDK version: 6.15.0
Source you installed the SDK (.unitypackage or Unity Package Manager): Unity Package Manager
Firebase plugins in use (Auth, Database, etc.): App (core), Authentication, Cloud Messaging, Crashlytics, Dynamic Links, Realtime Database, Remote Config, Analytics for firebase
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, IronSource, play-games-plugin-for-unity, External Dependency Manager for Unity 1.2.155
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android, Ios
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
Since I installed the ironsource sdk which uses the External Dependency Manager for Unity I installed Firebase the same way with the latest version 1.2.155.
I was having trouble building for android due to duplicates with different versions of com.google.firebase:firebase-analytics and androidPackage spec="com.google.firebase:firebase-messaging:20.1.7

the way I was able to solve it was by changing the firebase  dependencies xml in /Library/PackageCache/

changed `<androidPackage spec="com.google.firebase:firebase-analytics:17.4.1"> `to `<androidPackage spec="com.google.firebase:firebase-analytics:17.4.3">`

in:
/Library/PackageCache/com.google.firebase.remote-config@6.15.0/Firebase/Editor/RemoteConfigDependencies.xml
/Library/PackageCache/com.google.firebase.dynamic-links@6.15.0/Firebase/Editor/DynamicLinksDependencies.xml
/Library/PackageCache/com.google.firebase.messaging@6.15.0/Firebase/Editor/MessagingDependencies.xml
/Library/PackageCache/com.google.firebase.database@6.15.0/Firebase/Editor/DatabaseDependencies.xml
/Library/PackageCache/com.google.firebase.app@6.15.0/Firebase/Editor/AppDependencies.xml
/Library/PackageCache/com.google.firebase.crashlytics@6.15.0/Firebase/Editor/CrashlyticsDependencies.xml
/Library/PackageCache/com.google.firebase.analytics@6.15.0/Firebase/Editor/AnalyticsDependencies.xml
/Library/PackageCache/com.google.firebase.auth@6.15.0/Firebase/Editor/AuthDependencies.xml

changed `<androidPackage spec="com.google.firebase:firebase-messaging:20.1.7">` to `<androidPackage spec="com.google.firebase:firebase-messaging:20.2.0">`
in:
/Library/PackageCache/com.google.firebase.messaging@6.15.0/Firebase/Editor/MessagingDependencies.xml

I think the conflict was coming from 
`<androidPackage spec="com.google.games:gpgs-plugin-support:0.10.06">`
in Assets/GooglePlayGames/Editor/GooglePlayGamesPluginDependencies.xml
but Im not sure...

Is there a better way to address this? It feels wrong to change something in a cache folder...
Thanks.

**Comment by ozdemir08** [comment]
Does it reproduce with v10.09 too? You may try to upgrade it and try to force resolve dependencies.

**Comment by ozdemir08** [comment]
Feel free to reopen this if the issue persists.
