### ISSUE TITLE
Google Sign-In compatible?

### ISSUE THREAD

**Issue by Nyankoo** [playgameservices/play-games-plugin-for-unity#2906]
I'm currently trying to implement Google Sign-In together with Firebase Auth in a new project, but can't get it working correctly.
In another project, I successfully use this plugin (GPG) for other purposes, so I was wondering if I can use GPG to get an idToken and authCode for Firebase Auth instead of from the Google Sign-In plugin?

**Comment by olehkuznetsov** [comment]
It should be possible to sign-in with PGS in Firebase Auth.
