### ISSUE TITLE
Failed to create folder FileUtils.CreateFolder() at /Users/chkuang/ (I'm not chkuang)

### ISSUE THREAD

**Issue by sfjohansson** [playgameservices/play-games-plugin-for-unity#2912]
Hi.
  I've upgraded to latest plugin and it fails to resolve, it looks like a hardcoded user path that has been left in the code by mistake or can I change this?

I'm running unity on Ubuntu..

**Comment by olehkuznetsov** [comment]
Are you using firebase plugin as well?

**Comment by sfjohansson** [comment]
No, just the services. I got it working in the end by downloading and upgrading the latest resolver....when I did that I also saw that one of the contributors in that repo is called "chkuang-g"
