### ISSUE TITLE
ERROR: Authentication failed - java.util.concurrent.ExecutionException: 5 out of 5 underlying tasks failed

### ISSUE THREAD

**Issue by sehwan** [playgameservices/play-games-plugin-for-unity#2913]
*** [Play Games Plugin 0.10.09] -DateTime- ERROR: Authentication failed - java.util.concurrent.ExecutionException: 5 out of 5 underlying tasks failed
System.Action:Invoke()
GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()

What's this error?
I have operate the game for about 3 months.
A certain user said that he is inaccessible to GPGS suddenly.
He was played the game for 2 months.
He couldn't authenticate since a few days ago.
I couldn't find things about this error in some other place.

**Comment by olehkuznetsov** [comment]
what is you game package name?

**Comment by sehwan** [comment]
@olehkuznetsov 
com.alchemists.guild
This is playable in Rep of Korea only.
The man who reported said that he is available to access in other device.
Thank you
