### ISSUE TITLE
I,m having problems with my android build :(

### ISSUE THREAD

**Issue by ElALeKs242** [playgameservices/play-games-plugin-for-unity#2914]
this is the message error
can someone help me what to do?
Win32Exception: ApplicationName='C:\Program Files\Unity\Hub\Editor\2019.4.3f1\Editor\Data\il2cpp/build/deploy/net471/il2cpp.exe', CommandLine='--convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARMv7" --configuration="Release" --outputpath="C:\Users\Emanuel\OneDrive\Escritorio\Exportación sin título\Photoshop\Sprites and atlas\JUEGOS UNITY\Marselo Pocket\Temp\StagingArea\assets\bin\Data\Native\armeabi-v7a\libil2cpp.so" --cachedirectory="C:\Users\Emanuel\OneDrive\Escritorio\Exportación sin título\Photoshop\Sprites and atlas\JUEGOS UNITY\Marselo Pocket\Assets\..\Library\il2cpp_android_armeabi-v7a/il2cpp_cache" --additional-include-directories="C:/Program Files/Unity/Hub/Editor/2019.4.3f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\bdwgc/include" --additional-include-directories="C:/Program Files/Unity/Hub/Editor/2019.4.3f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\libil2cpp/include" --tool-chain-path="C:/Program Files/Unity/Hub/Editor/2019.4.3f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK" --profiler-report --map-file-parser="C:/Program Files/Unity/Hub/Editor/2019.4.3f1/Editor/Data/Tools/MapFileParser/MapFileParser.exe" --directory="C:/Users/Emanuel/OneDrive/Escritorio/Exportación sin título/Photoshop/Sprites and atlas/JUEGOS UNITY/Marselo Pocket/Temp/StagingArea/assets/bin/Data/Managed" --generatedcppdir="C:/Users/Emanuel/OneDrive/Escritorio/Exportación sin título/Photoshop/Sprites and atlas/JUEGOS UNITY/Marselo Pocket/Temp/StagingArea/Il2Cpp/il2cppOutput" ', CurrentDirectory='C:\Users\Emanuel\OneDrive\Escritorio\Exportación sin título\Photoshop\Sprites and atlas\JUEGOS UNITY\Marselo Pocket\Temp\StagingArea\assets\bin\Data\Managed', Native error= La operación solicitada requiere elevación.

System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) (at <14e3453b740b4bd690e8d4e5a013a715>:0)
System.Diagnostics.Process.Start () (at <14e3453b740b4bd690e8d4e5a013a715>:0)
(wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
UnityEditor.Utils.Program.Start (System.EventHandler exitCallback) (at <bccb16a88ec4456dbf07978c418f407b>:0)

**Comment by olehkuznetsov** [comment]
"C:\Users\Emanuel\OneDrive\Escritorio\Exportación sin título\Photoshop\Sprites and atlas"? may be try to move project to another folder?
