### ISSUE TITLE
 'GooglePlayGames' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by bfaf** [playgameservices/play-games-plugin-for-unity#2915]
Unity version: 2019.4.1f
Play Games plugin version: 0.10.09
Admobs version: 5.2.0
Platform in Build Settings screen: Android

Error in unity console:

Assets/Scripts/Ads/MyCloudManager.cs(4,7): error CS0246: The type or namespace name 'GooglePlayGames' could not be found (are you missing a using directive or an assembly reference?)

Content of Assets/Scripts/Ads/MyCloudManager.cs:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;

public class MyCloudManager : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        InitializeGooglePlay();
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private void InitializeGooglePlay()
    {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
        // enables saving game progress.
        .EnableSavedGames()
        // requests the email address of the player be available.
        // Will bring up a prompt for consent.
        .RequestEmail()
        // requests a server auth code be generated so it can be passed to an
        //  associated back end server application and exchanged for an OAuth token.
        .RequestServerAuthCode(false)
        .Build();

        PlayGamesPlatform.InitializeInstance(config);
        // recommended for debugging:
        PlayGamesPlatform.DebugLogEnabled = true;
        // Activate the Google Play Games platform
        PlayGamesPlatform.Activate();

        PlayGamesPlatform.Instance.Authenticate(SignInInteractivity.CanPromptOnce, (result) =>{
            // handle results
            Debug.Log(result);
        });
    }

}

```

Every reference of PlayGamesClientConfiguration is underlined and it says it confilcts with same namespace in GoogleMobileAds.

I cannot generate build for Android. Please help.

Also the menu Window > Google Play Games is gone for some reason. I did the setup though.

Kind Regards,
Krasimir Chonov

**Comment by bfaf** [comment]
Fixed it by removing Assembly Deffinition in my Scripts directory.

**Comment by turh2019** [comment]
> Fixed it by removing Assembly Deffinition in my Scripts directory.

hey man how do you do it  exactly, can you explain

**Comment by gruffdavies** [comment]
@turh2019 For me the fix was to switch the project settings to Android. See: https://github.com/playgameservices/play-games-plugin-for-unity/issues/1291
