### ISSUE TITLE
The score on the leaderboard is not visible to anyone other than yourself

### ISSUE THREAD

**Issue by sspark27** [playgameservices/play-games-plugin-for-unity#2917]
The score on the leaderboard is not visible to anyone other than yourself. 
You can only share it with other people in the Google Play Services app.
Previously, if you increased the score, the scores of other people were shared even 
if you did not change the settings.
Is this normal? Or what settings should you set?
I hope there is a solution.

**Comment by sspark27** [comment]
> The score on the leaderboard is not visible to anyone other than yourself.
> You can only share it with other people in the Google Play Services app.
> Previously, if you increased the score, the scores of other people were shared even
> if you did not change the settings.
> Is this normal? Or what settings should you set?
> I hope there is a solution.

**Comment by olehkuznetsov** [comment]
Currently by default sharing option is turned off during profile creation and player needs to turn it on on profile creation step or later in settings.

**Comment by sspark27** [comment]
If the default is set to not share, few people will be displayed on the leaderboard.

Their policy might not be the smart choice for us to use this leaderboard.

Also, when a user who has not registered a score calls the leaderboard's score through the API, they are automatically logged out. In v10.09 release.

Thanks for the answer.

**Comment by olehkuznetsov** [comment]
> Also, when a user who has not registered a score calls the leaderboard's score through the API, they are automatically logged out. In v10.09 release.
Can you provide a repro steps for that case, please?

**Comment by sspark27** [comment]
Unity 2019.4.3f1
firebase.analytics 6.15.2
firebase.auth 6.15.2
firebase.database 6.15.2
Android 10.
Unity googleplay plugin 10.09

1. Log in to Google Play through the plugin.
2. When the user agrees to the authority and selects an account, they are logged in.
3. Get the Google authentication code and log in to Firebase.
4. Get the value of the leaderboard through the plugin (LoadScores).
5. Automatically logged out.
6. If you are a first-time user, check the error and put the score on the leaderboard with 0 points. However, the login is not released and there is no reaction.

Google is set as web authentication to get the authentication code.

After we received your comment, we couldn't use Google Play's leaderboard, so we discarded it all and changed it to a different leaderboard. So, it seems difficult to provide more information. Please understand this.

Thank you for your efforts to solve our problems.

**Comment by olehkuznetsov** [comment]
Thanks for update
