### ISSUE TITLE
How to prompt for new account creation during authentication?

### ISSUE THREAD

**Issue by dogmahtagram** [playgameservices/play-games-plugin-for-unity#292]
When I have either multiple or no Google accounts added in the device settings, calling Social.localUser.Authenticate() prompts the user to either choose one of the existing accounts or create a new one. 

When I have a single Google account added in the device settings, calling Social.localUser.Authenticate() will log into that account instead without giving me the option of creating a new Google account.

In the case that there is only a single Google account on the device, is there a way that I can trigger the authentication dialog that gives the user the option to sign in with a different account?

If not, is it possible to query the number of Google accounts that have been added to the device through the existing plugin?

Thanks for any insight.

**Comment by claywilkinson** [comment]
The short answer is no.  The longer answer is that there are best practices outlined for games: https://developers.google.com/games/services/checklist#improving_the_sign_in_experience_for_games and keeping the user signed in is usually a pleasurable experience.

Usually the user profile is set when unlocking the lock screen, so all the applications have a consistent view of the user.
