### ISSUE TITLE
Exception: Authentication failed  in v0.10.09

### ISSUE THREAD

**Issue by amatveev** [playgameservices/play-games-plugin-for-unity#2921]
[Play Games Plugin 0.10.09] 08/02/20 22:34:27 +03:00 ERROR: Authentication failed - java.util.concurrent.ExecutionException: 5 out of 5 underlying tasks failed

1. Google Play Games app not install
2. In dialog about install app Google Play Games press "Cancel"
3. Auth callback not be called
How this handle?

**Comment by KOshh77** [comment]
Catch_22_?_C.O.D.E.=$:¢

**Comment by ozdemir08** [comment]
Please try this out with the latest plugin and make sure you follow the configuration instructions in [README](https://developers.google.com/games/services/console/enabling). Feel free to reopen this, if the issue persists.
