### ISSUE TITLE
Google Play Services v0.10.09 not working after implementing GoogleMobileAds v5.2.0

### ISSUE THREAD

**Issue by sogonleong** [playgameservices/play-games-plugin-for-unity#2922]
Which version of these 2 is compatible? Help, please.

**Comment by CodeWithJeff** [comment]
Yeah same issue here im trying to fix it for days

**Comment by sogonleong** [comment]
I hate it that their own SDKs always doesn't work or in conflict. Firebase, Google Mobile Ads, and Google Play Services. 
I used another ads service and thought maybe give Google Mobile Ads a try again and it failed me again and again.

**Comment by sogonleong** [comment]
> Yeah same issue here im trying to fix it for days

Are you using ProGuard? I found out it seems like ProGuard is removing the necessary files and adding a user proguard file seems to fix it.

**Comment by CodeWithJeff** [comment]
> > Yeah same issue here im trying to fix it for days
> 
> Are you using ProGuard? I found out it seems like ProGuard is removing the necessary files and adding a user proguard file seems to fix it.

No im not using pro guard i fixed it too when i import new version of admob and GPGS it always ask me to import registry from package manager i clicked disable and it worked :D After importing registry it breaks project
