### ISSUE TITLE
Why is it an accepted answer/practice to disable minification?

### ISSUE THREAD

**Issue by schwindyboo** [playgameservices/play-games-plugin-for-unity#2924]
I ran into a `java.lang.ClassNotFoundException:com.google.android.gms.games.Games` issue when adding this plugin to my game

Even when following the steps [here in the readme](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/README.md#decreasing-apk-size) so my `proguard-user.txt` looks like it does below I still get the error when minifying

```
-keep class com.google.android.gms.games.achievement.** { *; }
-keep class com.google.android.gms.common.api.ResultCallback { *; }
-keep class com.google.android.gms.signin.** { *; }
-keep class com.google.android.gms.common.ConnectionResult { *; }
-keep class com.google.android.gms.common.GooglePlayServicesUtil { *; }
-keep class com.google.android.gms.common.api.** { *; }
-keep class com.google.android.gms.common.data.DataBufferUtils { *; }
```

It looks like alot of accepted answers just advise the disabling of minification which doesn't feel right to me and is not an actual fix

Is there any planned work on the plug in to address this?

**Comment by legas1** [comment]
The proguard file mentioned in README (https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/scripts/proguard.txt) already contains `-keep class com.google.android.gms.games.* { *; }`.

**Comment by schwindyboo** [comment]
I swear I tried that file. Seems to work fine now. Thanks @legas1
