### ISSUE TITLE
What is the lifetime of ID token and how can we set it to custom time like 10 minutes?

### ISSUE THREAD

**Issue by Sailendrakc** [playgameservices/play-games-plugin-for-unity#2925]
Hello,
`        
       PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()

        // requests the email address of the player be available.
        // Will bring up a prompt for consent.
        .RequestEmail()

        // requests an ID token be generated.  This OAuth token can be used to
        //  identify the player to other services such as Firebase.
        .RequestIdToken()
        
        .Build();

         PlayGamesPlatform.InitializeInstance(config);

         // recommended for debugging
         PlayGamesPlatform.DebugLogEnabled = true;

         // Activate the Google Play Games platform
         PlayGamesPlatform.Activate();`

when requesting id token like above, is there any way to set the lifetime of the ID token we get. In the[ auth0 website ](https://auth0.com/docs/tokens/concepts/id-tokens), it says default time of token is 10 hours, is this standard and applies here or what is that number? 
Thanks!

**Comment by ozdemir08** [comment]
There is no way to set the lifetime of the ID token. Feel free to reopen it, if you would like to discuss more around your case.
