### ISSUE TITLE
Proguard - what should I keep?

### ISSUE THREAD

**Issue by Luciano-Bercini** [playgameservices/play-games-plugin-for-unity#2928]
Hi,

Following the guide, it mentions we can reduce the size of the game by using proguard.
But what was I wondering is, which of these classes should I keep if I use **sign in**, **saved games,** **achievements** and **leaderboards**?
I successfully managed to remove a few (the most obvious ones, such as video, nearby etc...) but I would prefer a more official reply on this, perhaps it should be added on the guide as well.

Here's the full list:

-keep class com.google.android.gms.games.multiplayer.** { *; }
-keep class com.google.android.gms.games.leaderboard.** { *; }
-keep class com.google.android.gms.games.snapshot.** { *; }
-keep class com.google.android.gms.games.achievement.** { *; }
-keep class com.google.android.gms.games.event.** { *; }
-keep class com.google.android.gms.games.stats.** { *; }
-keep class com.google.android.gms.games.video.** { *; }
-keep class com.google.android.gms.games.* { *; }
-keep class com.google.android.gms.common.api.ResultCallback { *; }
-keep class com.google.android.gms.signin.** { *; }
-keep class com.google.android.gms.dynamic.** { *; }
-keep class com.google.android.gms.dynamite.** { *; }
-keep class com.google.android.gms.tasks.** { *; }
-keep class com.google.android.gms.security.** { *; }
-keep class com.google.android.gms.base.** { *; }
-keep class com.google.android.gms.actions.** { *; }
-keep class com.google.games.bridge.** { *; }
-keep class com.google.android.gms.common.ConnectionResult { *; }
-keep class com.google.android.gms.common.GooglePlayServicesUtil { *; }
-keep class com.google.android.gms.common.api.** { *; }
-keep class com.google.android.gms.common.data.DataBufferUtils { *; }
-keep class com.google.android.gms.games.quest.** { *; }
-keep class com.google.android.gms.nearby.** { *; }

**Comment by ozdemir08** [comment]
You should basically keep all of them. While we were working on this, we saw that this set of rules significantly decrease the apk size and any further break-down of rules do not help much to decrease it even further. And you mention that you use **sign in, saved games, achievements, leaderboards** and the other APIs we have do not take up much space.
