### ISSUE TITLE
Play unity plugins integrity

### ISSUE THREAD

**Issue by radmikulka** [playgameservices/play-games-plugin-for-unity#2929]
As soon as I import play asset delivery to project (https://github.com/google/play-unity-plugins - thrue package manager) than google play games services - stops working (unsuccessfull authorization). Is it known issue or is it only my local problem? Spec: Unity 2019.4.4 - proguard minify enabled - newest google play games and play asset delivery plugins

**Comment by ozdemir08** [comment]
Could you disable proguard and see whether it works?

**Comment by ozdemir08** [comment]
Feel to reopen this if the issue still persists.
