### ISSUE TITLE
Play Games Services Unity Plugin v0.10.10

### ISSUE THREAD

**Issue by redls** [playgameservices/play-games-plugin-for-unity#2930]
We are pleased to announce the release of Play Games Services Unity plugin v0.10.10.  

This release contains the following updates:

1. NEW Play Games Services - Friends APIs: Play Games now has a cross-game Friends list. Request access to your players cross-game PGS friends list and integrate it with your in-game system to help players play with a set of high-quality gaming friends, and help people find their friends within your game. Learn more about Play Games Services - Friends [here](https://developers.google.com/games/services/common/concepts/friends), and learn how to implement the APIs [here](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/README.md#friends).
2. Multiplayer cleanup - multiplayer APIs have been removed from the plugin and the sample games

Important note: To use the Friends feature, you will also need to update your PGS SDK to v20.

Please help us to continue to improve the Plugin by reporting bugs in this version of the plugin.

**Comment by diegosilvaxx** [comment]
my score crashes when opened a second time

**Comment by ozdemir08** [comment]
Could you share the crash report and also your code?
