### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by mrintoxx** [playgameservices/play-games-plugin-for-unity#2932]
Hi guys,
I know that issue has been opened multiple times but the solution i've found doesn't work for me.

I've installed the GPS into my unity project following the readme.md. But when i want to test it using the minimal scene, i never could have the authentication sucess. 

I have signed my apk using the keystore of unity and then uploaded in the play console to have the app signed by google.
I've also replaced the SHA-1 in the OAuth with the signin SHA-1.

My personal account (wich i use in my phone), is assigned as a tester.

I don't knoww what to try now for make it working, if somebody have an idea :)

By the way i'm using Unity : 2019.4.0f and using the GPS : 0.10.09

Thanks for the help, if need any precision please tell me :)

**Comment by itsMohammedThaier** [comment]
There is something called "**monitor**" in the SDK< tools
connect your phone and open the **"monitor"** and see whats errors, debugg...etc you get when you call sign-in function
and sometimes when you open "**monitor** you get some problems and the application don't work. don't worry this is regular you have just to open it alot of times lol XD
hope this help

**Comment by mrintoxx** [comment]
Done today,

I've created an emulated android because my phone has a hardware problem and i can't connect it trough usb to pc.

So, i've launched the android monitor without problems, ther's the logs with unity tags :
[https://pastebin.com/RgyD12eB](url)

**Comment by itsMohammedThaier** [comment]
Oh you are using GPS 0.10.9
This version has alot of bugs and didn't work with me
Install [GPS 0.10.10](https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v0.10.10) & it should work

**Comment by mrintoxx** [comment]
I'm trying it, update is ok.
But i can't build the app now, i think i've not fully deleted the GSP 0.10.09 i've error logs telling me ther's duplicates : 
`  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.google.android.gms.auth.api.Auth found in modules classes.jar (:com.google.android.gms.play-services-auth-18.0.0:) and classes.jar (:com.google.android.gms.play-services-auth-18.1.0:)

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

**Comment by itsMohammedThaier** [comment]
In your **project<Asset**  Delete Folders**Plug-in, Play Services Resolver and GooglePlayGames** 
![toGitHub](https://user-images.githubusercontent.com/70210166/91470018-d556d000-e89c-11ea-9139-03be85845978.png)
then Import the GPS 0.10.10 to your project

**Comment by mrintoxx** [comment]
Forgot last comment i've fixed it. And it shows me my error it was about the SJA1 was not correctly configured.
I've tried both but with version 10.09 maybe it was that the problem.
Thanks for your help man, have a nice day :)
