### ISSUE TITLE
Unity 2020.1 minSdk

### ISSUE THREAD

**Issue by Swipeu** [playgameservices/play-games-plugin-for-unity#2933]
I cant get this plugin to work in a clean Unity 2020.1 project.

When I try to build i get this gradle error:
![image](https://user-images.githubusercontent.com/68690314/91140326-e68eb980-e6af-11ea-8ae8-9b3fa2a86f27.png)

The plugin regenerates the AndroidManifest so I don't really know what to do about it.

**Comment by diegosilvaxx** [comment]
é só remover o MinSdk do AndroidManifest.xml

**Comment by ntmohammad** [comment]
same here

**Comment by diegosilvaxx** [comment]
> same here

just remove MinSdk from AndroidManifest.xml

**Comment by ntmohammad** [comment]
> just remove MinSdk from AndroidManifest.xml
there is no androidmanifest.xml , only template-AndroidManifest.xml. removing minsdk from that file wont solve the problem

**Comment by Swipeu** [comment]
The one I'm referring to is the AndroidManifest.xml inside GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin.
I guess the solution for now is to remove `<uses-sdk android:minSdkVersion="14" />` every time the plugin regenerates the file.

**Comment by ozdemir08** [comment]
We'll fix it with the next release.

**Comment by ozdemir08** [comment]
[This commit](https://github.com/playgameservices/play-games-plugin-for-unity/commit/83042116d7302efd19096e30def368f9865a51d1) should fix the issue. We're going to make a new release soon. Thanks for the comments.
