### ISSUE TITLE
No valid GUID?

### ISSUE THREAD

**Issue by Tydence** [playgameservices/play-games-plugin-for-unity#2936]
I'm getting the following error:
"The .meta file Assets/GooglePlayGames/Editor/GooglePlayGamesPlugin_v0.10.10.txt.meta does not have a valid GUID and its corresponding Asset file will be ignored."

and 4 more errors all involving the GUID.

No mention of this in the documentation? Looks like I'm not the only one with this error.

**Comment by ozdemir08** [comment]
We actually don't have a file called GooglePlayGamesPlugin_v0.10.10. What are the other 4 errors you get?

**Comment by AnatolySnegovskiy** [comment]
The same thing
![image](https://user-images.githubusercontent.com/11618162/91643504-d88cc000-ea44-11ea-859b-4302bda48cb5.png)

**Comment by JigsawClub** [comment]
Same here

**Comment by Aze22** [comment]
I have it too in latest version of Unity. Then, the editor freezes :-(

**Comment by Swipeu** [comment]
What I do is open up the folder in file explorer and delete the meta file. Unity will generate a new one that works

**Comment by ozdemir08** [comment]
It's fixed in the latest release.
