### ISSUE TITLE
Question: is Google Cloud Platform token grant rate limit / quota applicable?

### ISSUE THREAD

**Issue by whitepyjamas** [playgameservices/play-games-plugin-for-unity#2938]
Hi,

Thank you for the awesome plugin!

We have implemented this plugin for a Google Play Games authentication-only setup where a client Android device is configured to authenticate with `RequestIdToken()` configuration parameter. Our app currently has status of `Verification in progress` for **OAuth consent screen** and our team is struggling to find out whether quotas from **OAuth consent screen** section in Google Cloud Platform -> **APIs & Services** are applicable to us.

It says only 100 grants per minute / 10,000 grants per day are allowed which is a limit that is highly likely to be overpassed by our user base when we release the Google Play Games functionality. However despite the fact that our setup works only **No data is available for the selected time frame** is shown constantly for **Your token grant rate** section in **OAuth consent screen**. It would be also very helpful to understand what a `grant` actually is.

The only issue which seems to be somewhat related is this https://github.com/playgameservices/play-games-plugin-for-unity/issues/2519 however it seems to be referring to the other type of quota.

We would really love users to avoid seeing an error [like this](https://support.google.com/cloud/answer/9028764?hl=en) or similar and to understand the potential caveats for a smooth release. Any help would be much appreciated.

**Comment by olehkuznetsov** [comment]
I don't think this quota is applicable to our service. 
Why do you need RequestIdToken? How do you plan to use that token in your game?

**Comment by whitepyjamas** [comment]
OK, thank you! I don't know actually how it's used but I believe it's given to the server.

**Comment by olehkuznetsov** [comment]
It's better to not use it as this one will require additional consent from user. If you need to check PGS user is on server side then getServerAuthCode is enough
