### ISSUE TITLE
The authentication is cancelled

### ISSUE THREAD

**Issue by beginner-lang** [playgameservices/play-games-plugin-for-unity#2940]
When I run my game, Google Play Games Services showing over the game but it just close after a few seconds. Note that my game is published as an internal test and connected with Google Play App which also published.

First, Here's I tried to solve my problem:

Checked Signing certifications and SHA-1 certificate
Checked tester email is valid (Google Play testers have confirmed that it exists)
Saved Games are enabled.
Removing EnableSavedGames() doesn't affect at all

But none of them worked.

Here's the code I'm trying:

```
if (!PlayGamesPlatform.Instance.localUser.authenticated)
            {
                PlayGamesPlatform.Instance.Authenticate((bool success, string message) =>
                {
                    if (success)
                    {
                        Debug.Log("++++++++++++Login Successful++++++++++++");
                    }
                    else
                    {
                        Debug.LogError(m_mark + "google login fail, error message :" + message);
                    }

                });
            }
```
When I run Social.localUser.Authenticate, it always returns false. Here's the message from Logcat（I'm sorry I didn't filter, because I don't know what might be helpful to you）:
[Error Message.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/5207255/Error.Message.txt)

**Comment by olehkuznetsov** [comment]
Can you run on your test device
adb shell setprop log.tag.Games VERBOSE
and take logcat again, please?

**Comment by gzh1265321614** [comment]
I'm sorry, I don't know what this command means, but when I run it on CMD, I test it again and get a log log that doesn't look different.But still upload it.
[Error2.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/5215600/Error2.txt)

**Comment by olehkuznetsov** [comment]
You need to connect mobile phone with usb cable to your pc and enable USB debugging before executing that adb command

**Comment by gzh1265321614** [comment]
> 您需要先使用USB电缆将手机连接到PC并启用USB调试，然后才能执行该adb命令

Yes, I did, as you said。Thank you for your continued attention！

**Comment by Afmj22** [comment]
I am also having this issue, the device monitor doesn't show much (only "Authentication canceled"), is there a way to show a more descriptive error message?

**Comment by BhavanathP** [comment]
Even i'm facing the same issue, has anyone found a fix?

**Comment by olehkuznetsov** [comment]
Check if you have at least title specified for your project here:
https://console.developers.google.com/apis/credentials/consent

**Comment by Afmj22** [comment]
What version of unity are you using? if its the latest and you are using and an android emulator keep in mind that in oct 2019 the x86 build has been deprecated and on the android device manager as far as i know there are no images with ARM available that have google play for emulators, i download unity version 2019.2 that had the x86 build option still and then it worked on an android emulator. Also remember that you have to use the scripting backend IL2CPP.
https://blogs.unity3d.com/2019/03/05/android-support-update-64-bit-and-app-bundles-backported-to-2017-4-lts/#:~:text=Limited%20x86%20Android%20devices%20were,remainder%20of%20their%20life%20cycle.

**Comment by Afmj22** [comment]
On your sdk location go to tools  and then open the monitor.bat are there any error or crashes? dont just look at the unity logs but all in general. You can do this by using the android AVD or by connecting your phone via USB.
