### ISSUE TITLE
account selector?

### ISSUE THREAD

**Issue by shlifedev** [playgameservices/play-games-plugin-for-unity#2943]
I do not want to auto-login special cases. 
How do display the profile select ui like this :)?

![image](https://user-images.githubusercontent.com/49047211/93283407-71745700-f80b-11ea-8ee3-df177650fe17.png)

**Comment by olehkuznetsov** [comment]
What is your user case here? Currently it is not possible as auto-login attempted first and if it fails then such dialog is shown. Or if user signed out perviously then this dialog is shown as well.
