### ISSUE TITLE
How to Download These Packages?

### ISSUE THREAD

**Issue by Only4Gamers** [playgameservices/play-games-plugin-for-unity#2944]
How to download following Packages:
Android Support Library
Local Maven repository for Support Libraries (Also known as Android Support Repository)
Google Repository

As these packages are no longer available in Android Studio, How I can download these Packages?

Also consider updating Tutorial.

**Comment by Afmj22** [comment]
Have you tried to clone https://github.com/playgameservices/play-games-plugin-for-unity#plugin-installation

**Comment by Only4Gamers** [comment]
> Have you tried to clone? https://github.com/playgameservices/play-games-plugin-for-unity#plugin-installation

These packages are not included in Plugin. So no benefit of cloning. Did you used this plugin?

**Comment by Afmj22** [comment]
Yes, i cloned the project and on the current-build folders thers the unity package.

**Comment by Afmj22** [comment]
I just added the package and made sure the android jdk, ndk, sdk on the preferences was set up correctly, you might have to select them manually since i had some problems with the automatic configuration.

**Comment by Only4Gamers** [comment]
> I just added the package and made sure the android jdk, ndk, sdk on the preferences was set up correctly, you might have to select them manually since i had some problems with the automatic configuration.

Sorry, but it's looking like some kind of confusion.
I am looking for these 3 packages:
1. Android Support Library
2. Local Maven repository for Support Libraries (Also known as Android Support Repository)
3. Google Repository

Are they necessary? Are they included?

I already got UnityPackage of this plugin in Current-Build Folder and setup everything correctly. Everything is working, except some errors I mentioned here:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/2945

So main problem is errors I mentioned in above link. Please go to above link and help me on this.
Thank you so much.

**Comment by Afmj22** [comment]
Well as far as im aware and from experience since i just added a game to goople play yesterday, i did not need any of the packages you mentioned. If you are using a database you have to pass a token for validation so that might be the problem.

**Comment by DobySLC** [comment]
You can either go to your JDK directory bin folder (the one you've chosen for your unity project in settings) and open the batch file where you can add these libraries or download Android Studio, again, choose the JDK that you are using for your Unity project, and add the libraries directly in Android studio. Android Studio is a little bit more user friendly so I recommend that.
