### ISSUE TITLE
why these two lines creating errors?

### ISSUE THREAD

**Issue by Only4Gamers** [playgameservices/play-games-plugin-for-unity#2945]
Hello everyone,
These two lines are creating 6 errors:

`PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.Activate();`

And these are errors:
Invalid token '(' in class, struct, or interface member declaration
Tuple must contain at least two elements.
Invalid token ';' in class, struct, or interface member declaration
Invalid token '(' in class, struct, or interface member declaration
Tuple must contain at least two elements.
 Invalid token ';' in class, struct, or interface member declaration

Please help.

**Comment by ozdemir08** [comment]
Is it possible that you accidentally modified PlayGamesPlatform? If not, then can you share your full script and full errors?

**Comment by olehkuznetsov** [comment]
How do you create config here?

**Comment by Only4Gamers** [comment]
> Is it possible that you accidentally modified PlayGamesPlatform? If not, then can you share your full script and full errors?

Actually problem is solved now. I was doing a mistake. Thanks for respons.

**Comment by ozdemir08** [comment]
Glad to hear that your problem is solved. Closing this issue now.
