### ISSUE TITLE
Google Play Games Cloud Saving

### ISSUE THREAD

**Issue by DobySLC** [playgameservices/play-games-plugin-for-unity#2946]
I basically have exactly the plugin instructions and code labs  code to establish cloud saving with a loadedString.Split() function for saving. It is working fundamentally, however, if I save NEW information I cannot load for like 20 minutes. Once I can load I can spam load no issues, reinstall load no issues, and even save and load no issues as long as no actual new information (aside from .WithUpdatedPlayTime which is not in my actual saved byte array) is in the save. If I actually play my game, save (which is successfully occurring) and try to load I cannot load until I wait some arbitrary amount of time. Whether I leave the game installed and reboot, try to load in the same game session, or completely uninstall the app and reinstall. I still have to wait some unknown time before I can access. I have debugged and see that I don't even get to my first callback function from opening a saved game. If I log out of Google Services while trying to access them it will cancel implying it is still attempting to complete the initial OpenSavedGame function. I assume it is some issue with conflict resolution but I am finding very little on the internet that seems to coincide with my issue. Wondering if maybe you guys know any similar issues. I have tried DataSource. ReadNetworkOnly & Cached options as I have a manual resolution anyway after cause I prefer it. I am currently using UseLongestPlayTime but I honestly just want whichever network save is most recent but UseMostRecent (I think) was giving me the same issues.

**Comment by olehkuznetsov** [comment]
Are you testing it on real device or emulator? Can you check if ISavedGameClient method ShowSelectSavedGameUI shows your new save game sooner?

**Comment by ozdemir08** [comment]
Feel free to reopen this, if your issue persists or you have further questions.
