### ISSUE TITLE
Google Play Games SDK path not found.

### ISSUE THREAD

**Issue by HaciEnda99** [playgameservices/play-games-plugin-for-unity#2947]
when i try to setup up google play games with this plugin the arror pops up... Any ideas??

![image](https://user-images.githubusercontent.com/71556267/93668616-b7405200-fa8d-11ea-91d7-981ceb906bc8.png)
![Unbenannt](https://user-images.githubusercontent.com/71556267/93668554-439e4500-fa8d-11ea-8d15-13d80d59a5bb.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/71556267/93668555-45680880-fa8d-11ea-914e-11880a4528d6.PNG)

**Comment by AndrewLevada** [comment]
Same. Unity 2020.1.4f1

**Comment by AndrewLevada** [comment]
Fixed! Simply change line 448 in file Assets/GooglePlayGames/Editor/GPGSUtil.cs 
from `#if UNITY_2019` 
to `#if UNITY_2019 || UNITY_2020`

**Comment by HaciEnda99** [comment]
Thanks so mutch man! Fixed too :D

**Comment by ozdemir08** [comment]
Thanks for the fix! We will include the fix in the next release.

**Comment by moosesnWoop** [comment]
Wow thanks, having the same issue right now.  Got it working again, thanks for the fix.

**Comment by raphaelbg** [comment]
The exact same problem is now back with Unity 2021 !
I had to change the code to:
`#if UNITY_2019 || UNITY_2020 || UNITY_2021`

**Comment by phuocmenhudn** [comment]
Vào 00:23, T.2, 17 Th5, 2021 raphaelbg ***@***.***> đã viết:

**Comment by mukhinid** [comment]
Hi @raphaelbg and others who faced this issue on Unity 2021. I think it's more correct to replace entire directive to
`#if UNITY_2019_1_OR_NEWER`
PR #2997 with this edit is waiting for merge.

**Comment by lirio22** [comment]
I'm having this issue in Unity 2019

**Comment by kimmy3697** [comment]
Thank you~

**Comment by R4J4S** [comment]
> Hi @raphaelbg and others who faced this issue on Unity 2021. I think it's more correct to replace entire directive to `#if UNITY_2019_1_OR_NEWER` PR #2997 with this edit is waiting for merge.

Thank you.

**Comment by mukhinid** [comment]
Fixed in v0.10.13 via 25a0551

**Comment by Zurigan** [comment]
Same warning happened for me when upgrading an old project. GPGSUtil.cs line 447 `string sdkPath = EditorPrefs.GetString("AndroidSdkRoot");` was returning an invalid path. Fixed by hacking in a SetString to "". 

Plugin could check if the 'AndroidSdkRoot' path was valid before trusting it, perhaps.
