### ISSUE TITLE
Firebase.Auth does not exist...

### ISSUE THREAD

**Issue by HaciEnda99** [playgameservices/play-games-plugin-for-unity#2948]
Can anyone explain why this errors are there?? I actually install everthing and so but it doesnt find Firebase.Auth...

![image](https://user-images.githubusercontent.com/71556267/93722404-cbbc4180-fb96-11ea-9e01-67b9c3c4412e.png)
![image](https://user-images.githubusercontent.com/71556267/93722411-d70f6d00-fb96-11ea-92d4-e98cb297b251.png)

**Comment by AndrewLevada** [comment]
FIrebase.Auth is not a part of GooglePlayGames, you have to install Firebase plugin separately. More about Firebase https://firebase.google.com/docs/unity/setup. If you already installed Firebase Auth plugin notice that you do not have _using_ for it.
