### ISSUE TITLE
Is SIGNIN_HINTS possible in GPGS for unity?

### ISSUE THREAD

**Issue by Thaina** [playgameservices/play-games-plugin-for-unity#2949]
Sometimes user might using oauth account signin to account that already exist in google play, using same email for example, and might not match the account that currently active as main account of the device

So I wish I could provide a hint email to GPGS plugins. But I can't find data in the document or this repo. Is it possible? If it not implement then is it possible to have in next version?

**Comment by ozdemir08** [comment]
Could you tell us what the use case is?

**Comment by Thaina** [comment]
@ozdemir08 Should the use case be seriously obvious?

In android device, one device could have multiple email account and even more so to the facebook and twitter that user might be able to switch between, each could have their own play service statistics and achievement linked differently and so it should not be load and set the wrong statistics to the wrong account or it would cause confusion

That's why if user have login with google or facebook, and that account already linked with google play account, I could provide `SIGNIN_HINTS` to sign in the play service linked with that account instead of current active account that might not match the account user are using to logged in to my app

And to require play service popup everytime user logged in is tedious. User would annoyed and they could also pick wrong account because they wouldn't remember with account was linked to the account they are signing in anyway. If we could provide `SIGNIN_HINTS` and user have been logged in with that account in the device it could just switching account silently and smoothly

What are you confused?

**Comment by ozdemir08** [comment]
Thanks for the explanation. I will pass this to our product manager. Having said that, I am not expecting us doing such a change soon. So, I am closing this issue now and will comment here if we have any update.

**Comment by Thaina** [comment]
@ozdemir08 Is this really completed?
