### ISSUE TITLE
'BasicApi' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by SrijanGods** [playgameservices/play-games-plugin-for-unity#2953]
Cannot use BasicApi feature to integrate login in my game using the latest version of package.
only Utils namespace is available.
![image](https://user-images.githubusercontent.com/30956325/94139158-cefd4900-fe86-11ea-8e78-924418674512.png)

**Comment by ozdemir08** [comment]
Could it be just an auto-complete issue?

**Comment by SrijanGods** [comment]
No, I have tested it by saving it and running unity.
It gave the error that I copy pasted.

**Comment by ozdemir08** [comment]
Could you try out some some older versions of the plugin and see if you still have this issue?

**Comment by SrijanGods** [comment]
I tried but it gave other issues, v9 gave undefined scripts errors.
Older play games version didn't even had GooglePlayGames class.
Please try SDK in Unity 2020.1.1f1 and see if it works or not or whats wrong....

**Comment by ozdemir08** [comment]
I tried it out with that version and it works fine for me. Any chance you figured this out?

**Comment by ozdemir08** [comment]
Closing this one. Feel free to reopen it if the issue persists.
