### ISSUE TITLE
Sign in box not showing at all: ("Authentication Failed - Developer Error")

### ISSUE THREAD

**Issue by TheTobias1** [playgameservices/play-games-plugin-for-unity#2957]
I've been struggling with this for a while and I can't seem to find a solution that works for me.

I've triple checked my SHA1. I've tried using the App signing cert when downloading from Google play and using the Upload cert when installing from Unity. Neither have worked atm.
My resources are copied exactly.
I've tried Force Resolving.
I've set my environment variables.
My IDs are all consistent.
Downloaded pretty much everything from the SDK manager in Android studio.

My Login Code, runs on start (if it hasn't been run previously)
```
Debug.Log("Logging in");
PlayGamesClientConfiguration clientConig = new PlayGamesClientConfiguration.Builder().RequestIdToken().Build();
PlayGamesPlatform.InitializeInstance(clientConig);
PlayGamesPlatform.Activate();
PlayGamesPlatform.DebugLogEnabled = true;

Social.localUser.Authenticate((bool success) =>
{
       if (success)
       {
             login = true;
             Debug.Log("Login complete");
             if (LoginComplete != null)
             {
                   LoginComplete(true);
             }
        }
        else
        {
              Debug.Log("Login fail");
              if (LoginComplete != null)
              {
                   LoginComplete(false);
              }
        }
});
```

I really don't know what the problem is.

Unity Version: 2020.1.6f

Any help is appreciated

**Comment by ozdemir08** [comment]
Could you share the logs that you see in logcat?

**Comment by TheTobias1** [comment]
Hey, thanks for the reply. I will be able to soon (projects recompiling atm).
The Log stated Sign in failed with Error code 10, which confuses me because my SHA1s are consistent (I've tried with both upload and signing certs in the console). 
The only thing that come to mind are that my projects currently in rejected state (due to screenshots), but surely I should be able to test, or that maybe I'm getting errors due to SDK, but I've installed almost every component available in Android studio.

**Comment by TheTobias1** [comment]
![image](https://user-images.githubusercontent.com/28479985/94812115-328af780-03ee-11eb-8385-94e3668ccdd1.png)

Here are the Sign in request messages

![image](https://user-images.githubusercontent.com/28479985/94812363-885f9f80-03ee-11eb-934e-ea0085166232.png)

And here's the full log

**Comment by Only4Gamers** [comment]
> I've been struggling with this for a while and I can't seem to find a solution that works for me.
> 
> I've triple checked my SHA1. I've tried using the App signing cert when downloading from Google play and using the Upload cert when installing from Unity. Neither have worked atm.
> My resources are copied exactly.
> I've tried Force Resolving.
> I've set my environment variables.
> My IDs are all consistent.
> Downloaded pretty much everything from the SDK manager in Android studio.
> 
> My Login Code, runs on start (if it hasn't been run previously)
> 
> ```
> Debug.Log("Logging in");
> PlayGamesClientConfiguration clientConig = new PlayGamesClientConfiguration.Builder().RequestIdToken().Build();
> PlayGamesPlatform.InitializeInstance(clientConig);
> PlayGamesPlatform.Activate();
> PlayGamesPlatform.DebugLogEnabled = true;
> 
> Social.localUser.Authenticate((bool success) =>
> {
>        if (success)
>        {
>              login = true;
>              Debug.Log("Login complete");
>              if (LoginComplete != null)
>              {
>                    LoginComplete(true);
>              }
>         }
>         else
>         {
>               Debug.Log("Login fail");
>               if (LoginComplete != null)
>               {
>                    LoginComplete(false);
>               }
>         }
> });
> ```
> 
> I really don't know what the problem is.
> 
> Unity Version: 2020.1.6f
> 
> Any help is appreciated

Are you uploading it first to Google Play or directly installing it on your device? If you are installing directly on your device then it not gonna work.

**Comment by TheTobias1** [comment]
I've tried both (and I've tried each using both SHA1 keys) and so far neither have worked

**Comment by antonitor** [comment]
I am stuck with the same problem, in my case I am trying to get the authcode, but I have tried to get the tokenId and the result is the same. 
Right now I am investigating if checking the consent screen of oauth apis is a requirement to obtain the authcode or tokenId.  If anyone knows, I will appreciate it.  
Otherwise, I will continue investigating in this line and I will say it if I get any results.

**Comment by TheTobias1** [comment]
So, I managed to solve the issue for me. My Android manifest had a space in the ID causing it to go haywire. For reference this is how my manifest looks now:
![image](https://user-images.githubusercontent.com/28479985/94994086-559fdd80-058d-11eb-8b03-e3a7db13d406.png)

**Comment by ErcinDedeoglu** [comment]
I have same problem
