### ISSUE TITLE
when building for iOS - Xcode error `'GPGSAppController.h' file not found`

### ISSUE THREAD

**Issue by corbinyo** [playgameservices/play-games-plugin-for-unity#2959]
`'GPGSAppController.h' file not found` With no solution being able to resolve this issue.

**Comment by olehkuznetsov** [comment]
Which version of plugin do you use?

**Comment by corbinyo** [comment]
I ended up removing the plugin to fix the issue, unfortunately. I would have been using the most recent version of the plugin.
