### ISSUE TITLE
How to get a server build if google play is configrued in the project?

### ISSUE THREAD

**Issue by Afmj22** [playgameservices/play-games-plugin-for-unity#2961]
I have this project with google play configured, the game has multiplayer and i need a separate server and client build to run. If i switch the platform to PC to build for the server get this error:

Assets\Scripts\Google Play\GooglePlayAuthentication.cs(35,68): error CS0246: The type or namespace name 'PlayGamesClientConfiguration' could not be found (are you missing a using directive or an assembly reference?)

I know that to fix this error i just need to  switch  back to the Android platform but i need a server build so how to i create a server build with google play configured?

(Note: i already tested the game on my local machine with multiple decives, i just need to know how to create a build to run as the server)

**Comment by olehkuznetsov** [comment]
You need to enclose Play Games services code in your game by 
#if UNITY_ANDROID
// Play Games services code
#endif
