### ISSUE TITLE
Leaderboard button signs out Google play game

### ISSUE THREAD

**Issue by jabirmayar** [playgameservices/play-games-plugin-for-unity#2962]
Ok so my login, score updation and achievements are working fine. When I click the leaderboard button it shows Leaderboard Ui but when i again click the leaderboard button it logs out.  I check everything, I don't have any sign out code on leaderboardUi button.  It's working fine with the achievements button. 
LeaderBoard button code: 
```
 public static void ShowLeaderboardUI()
        {
            if (PlayGamesPlatform.Instance.localUser.authenticated)
                Social.ShowLeaderboardUI();
            else
            {
                Debug.Log("Couldn't show leaderboard UI: user is not logged in.");
            }
        }

```

**Comment by itsproinc** [comment]
Yeah I'm having a similar issue, whereupon opening the leaderboard it logged me out from the Google Play upon checking the logcat it shows a message "ShowAllLeaderboardsUI result -3" this is the only message that is available on the logcat

**Comment by jabirmayar** [comment]
> Yeah I'm having a similar issue, whereupon opening the leaderboard it logged me out from the Google Play upon checking the logcat it shows a message "ShowAllLeaderboardsUI result -3" this is the only message that is available on the logcat

Yeah same. It's working fine when opening AchievementsUi but as soon as I click on LeaderBoardUi button it logs me out.

**Comment by AustinHey** [comment]
yes i have the same bug... so I'm not the only one...

**Comment by jabirmayar** [comment]
> yes i have the same bug... so I'm not the only one...

which version are you using?

**Comment by 251745** [comment]
I have the exact same issue too. Achievements are working perfectly fine but when I call Social.ShowLeaderboardUI() for the second time it logs out. (I'm using the latest version: 0.10.11)

**Comment by taekjun** [comment]
i tried many things for two weeks to fix this.
finally it works well by downgrading firebase version.

**Comment by inanoglu** [comment]
I've had this problem before. The solution is;
PlayGamesPlatform.Instance.ShowLeaderboardUI("YourLeaderboardId");

The problem is solved when I use it this way. You can try it.

**Comment by ozdemir08** [comment]
Is it happening only with the certain versions of firebase?
