### ISSUE TITLE
How to determine User cancelled or Authentication Failed

### ISSUE THREAD

**Issue by birdkingz** [playgameservices/play-games-plugin-for-unity#2964]
As per title, I would like to know is there any way that we can know whether the user canceled the sign-in process?

I tried to check whether the authentication returned failed message is "Authentication canceled" but it's not working as intended.

**Comment by olehkuznetsov** [comment]
You can use this version of Authenticate:
```
    // authenticate user:
    PlayGamesPlatform.Instance.Authenticate(SignInInteractivity.CanPromptOnce, (result) =>{
    });
```
For user canceled - result will be SignInStatus.Canceled.
See [SignInStatus](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/BasicApi/SignInStatus.cs) and [SignInInteractivity](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/BasicApi/SignInInteractivity.cs) for more options.
