### ISSUE TITLE
0.10.11 - Unity Android App crash on authenticate - No interface method getSkinTempLevel()  in class Lcom/samsung/android/gamesdk/IGameSDKService;

### ISSUE THREAD

**Issue by danoli3** [playgameservices/play-games-plugin-for-unity#2965]
`2020/10/21 14:38:56.698 31841 31841 Info chatty uid=10029(com.google.android.gms) identical 6 lines
2020/10/21 14:38:56.715 31841 31841 Debug ViewRootImpl@826f935[] Relayout returned: old=[0,0][0,0] new=[0,0][0,0] result=0x0 surface={valid=false 0} changed=false
2020/10/21 14:38:56.720 31841 7453 Error Volley [2811] BasicNetwork.performRequest: Unexpected response code 401 for https://www.googleapis.com/games/v1/applications/played
2020/10/21 14:38:56.722 31841 9577 Warn PlayGamesServices[GameAgent] Volley error when reporting played
2020/10/21 14:38:56.722 31841 9577 Warn PlayGamesServices[GameAgent] com.android.volley.AuthFailureError
2020/10/21 14:38:56.722 31841 9577 Warn PlayGamesServices[GameAgent] 	at com.android.volley.toolbox.BasicNetwork.performRequest(:com.google.android.gms@203915028@20.39.15 (100400-335085812):34)
2020/10/21 14:38:56.722 31841 9577 Warn PlayGamesServices[GameAgent] 	at cfx.performRequest(:com.google.android.play.games.services@213800040@2020.09.21380 (332058963.332058963-000400):18)
2020/10/21 14:38:56.722 31841 9577 Warn PlayGamesServices[GameAgent] 	at com.android.volley.NetworkDispatcher.processRequest(:com.google.android.gms@203915028@20.39.15 (100400-335085812):5)
2020/10/21 14:38:56.722 31841 9577 Warn PlayGamesServices[GameAgent] 	at com.android.volley.GmsAbstractNetworkDispatcher.processRequest(:com.google.android.gms@203915028@20.39.15 (100400-335085812):0)
2020/10/21 14:38:56.722 31841 9577 Warn PlayGamesServices[GameAgent] 	at dye.a(:com.google.android.play.games.services@213800040@2020.09.21380 (332058963.332058963-000400):0)
2020/10/21 14:38:56.722 31841 9577 Warn PlayGamesServices[GameAgent] 	at dyk.run(:com.google.android.play.games.services@213800040@2020.09.21380 (332058963.332058963-000400):0)
2020/10/21 14:38:56.722 31841 9577 Warn PlayGamesServices[GameAgent] 	at cja.b(:com.google.android.play.games.services@213800040@2020.09.21380 (332058963.332058963-000400):12)
2020/10/21 14:38:56.722 31841 9577 Warn PlayGamesServices[GameAgent] 	at cja.run(:com.google.android.play.games.services@213800040@2020.09.21380 (332058963.332058963-000400):7)
2020/10/21 14:38:56.722 31841 9577 Warn PlayGamesServices[GameAgent] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020/10/21 14:38:56.722 31841 9577 Warn PlayGamesServices[GameAgent] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020/10/21 14:38:56.722 31841 9577 Warn PlayGamesServices[GameAgent] 	at syp.run(:com.google.android.gms@203915028@20.39.15 (100400-335085812):0)
2020/10/21 14:38:56.722 31841 9577 Warn PlayGamesServices[GameAgent] 	at java.lang.Thread.run(Thread.java:764)
2020/10/21 14:38:56.731 31841 31841 Debug ViewRootImpl@826f935[] Relayout returned: old=[0,0][0,0] new=[0,0][0,0] result=0x0 surface={valid=false 0} changed=false
`

`2020/10/21 14:38:57.390 3904 9479 Debug GameManagerService identifyGamePackage. com.sec.android.app.launcher
2020/10/21 14:38:57.390 3904 9479 Debug GamePkgDataHelper getGamePkgData(). com.sec.android.app.launcher
2020/10/21 14:38:57.421 31929 32300 Info NearbySharing FastInitiation warming period has ended [CONTEXT service_id=194 ]
2020/10/21 14:38:57.483 3372 6665 Error NativeSemDvfsGpuManager release:: Start
2020/10/21 14:38:57.483 3372 6665 Error NativeSemDvfsGpuManager release():: mIsAcquired = 1 , mName = GPU  , mTagName : SurfaceFlinger 
2020/10/21 14:38:57.486 3372 6665 Error NativeCustomFrequencyManager [NativeCFMS] BpCustomFrequencyManager::releaseGPU() 
2020/10/21 14:38:57.486 3372 6665 Error NativeSemDvfsGpuManager release:: End
2020/10/21 14:38:57.624 31841 9582 Error PlayGamesServices[DataHolderOperation] When providing result 
2020/10/21 14:38:57.624 31841 9582 Error PlayGamesServices[DataHolderOperation] android.os.DeadObjectException
2020/10/21 14:38:57.624 31841 9582 Error PlayGamesServices[DataHolderOperation] 	at android.os.BinderProxy.transactNative(Native Method)
2020/10/21 14:38:57.624 31841 9582 Error PlayGamesServices[DataHolderOperation] 	at android.os.BinderProxy.transact(Binder.java:1145)
2020/10/21 14:38:57.624 31841 9582 Error PlayGamesServices[DataHolderOperation] 	at bdj.b(:com.google.android.play.games.services@213800040@2020.09.21380 (332058963.332058963-000400):2)
2020/10/21 14:38:57.624 31841 9582 Error PlayGamesServices[DataHolderOperation] 	at dfc.a(:com.google.android.play.games.services@213800040@2020.09.21380 (332058963.332058963-000400):9)
2020/10/21 14:38:57.624 31841 9582 Error PlayGamesServices[DataHolderOperation] 	at don.a(:com.google.android.play.games.services@213800040@2020.09.21380 (332058963.332058963-000400):2)
2020/10/21 14:38:57.624 31841 9582 Error PlayGamesServices[DataHolderOperation] 	at dnq.a(:com.google.android.play.games.services@213800040@2020.09.21380 (332058963.332058963-000400):9)
2020/10/21 14:38:57.624 31841 9582 Error PlayGamesServices[DataHolderOperation] 	at bqo.a(:com.google.android.play.games.services@213800040@2020.09.21380 (332058963.332058963-000400):0)
2020/10/21 14:38:57.624 31841 9582 Error PlayGamesServices[DataHolderOperation] 	at bql.run(:com.google.android.play.games.services@213800040@2020.09.21380 (332058963.332058963-000400):1)
2020/10/21 14:38:57.624 31841 9582 Error PlayGamesServices[DataHolderOperation] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020/10/21 14:38:57.624 31841 9582 Error PlayGamesServices[DataHolderOperation] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020/10/21 14:38:57.624 31841 9582 Error PlayGamesServices[DataHolderOperation] 	at java.lang.Thread.run(Thread.java:764)
`

`2020/10/21 14:43:00.013 9785 9929 Error AndroidRuntime FATAL EXCEPTION: Thread-15
2020/10/21 14:43:00.013 9785 9929 Error AndroidRuntime Process: com.game.id, PID: 9785
2020/10/21 14:43:00.013 9785 9929 Error AndroidRuntime java.lang.NoSuchMethodError: No interface method getSkinTempLevel()I in class Lcom/samsung/android/gamesdk/IGameSDKService; or its super classes (declaration of 'com.samsung.android.gamesdk.IGameSDKService' appears in /system/framework/framework.jar!classes3.dex)
2020/10/21 14:43:00.013 9785 9929 Error AndroidRuntime 	at com.samsung.android.gamesdk.GameSDKManager.getSkinTempLevel(GameSDKManager.java:200)
2020/10/21 14:43:00.016 4253 4253 Info StackScroller ADJUST STACK.TRANSLATION
2020/10/21 14:43:00.016 3904 5521 Debug Debug !@DumpState : SHIP
2020/10/21 14:43:00.017 3904 5521 Debug Debug !@DumpState : debug level:0x4f4c
2020/10/21 14:43:00.017 3904 5521 Debug Debug !@Dumpstate : Finally, system will skip dumpstate
2020/10/21 14:43:00.017 3904 5521 Warn ActivityManager crash : com.game.id,0
2020/10/21 14:43:00.017 4253 4253 Info StackScroller ADJUST STACK.TRANSLATION
2020/10/21 14:43:00.018 3904 5521 Warn ActivityManager   Force finishing activity com.game.id/com.unity3d.player.UnityPlayerActivity
2020/10/21 14:43:00.018 3904 3904 Debug Telecom:SamsungPrebindingServiceImpl onTopActivityChanged : ComponentInfo{com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity}
`

**Comment by danoli3** [comment]
`2020/10/21 13:35:33.937 4676 4964 Error AndroidRuntime FATAL EXCEPTION: Thread-15
2020/10/21 13:35:33.937 4676 4964 Error AndroidRuntime Process: com.game.id, PID: 4676
2020/10/21 13:35:33.937 4676 4964 Error AndroidRuntime java.lang.NoSuchMethodError: No interface method getSkinTempLevel()I in class Lcom/samsung/android/gamesdk/IGameSDKService; or its super classes (declaration of 'com.samsung.android.gamesdk.IGameSDKService' appears in /system/framework/framework.jar!classes3.dex)
2020/10/21 13:35:33.937 4676 4964 Error AndroidRuntime 	at com.samsung.android.gamesdk.GameSDKManager.getSkinTempLevel(GameSDKManager.java:200)
2020/10/21 13:36:05.072 5125 5244 Error AndroidRuntime FATAL EXCEPTION: Thread-15
2020/10/21 13:36:05.072 5125 5244 Error AndroidRuntime Process:  com.game.id, PID: 5125
2020/10/21 13:36:05.072 5125 5244 Error AndroidRuntime java.lang.NoSuchMethodError: No interface method getSkinTempLevel()I in class Lcom/samsung/android/gamesdk/IGameSDKService; or its super classes (declaration of 'com.samsung.android.gamesdk.IGameSDKService' appears in /system/framework/framework.jar!classes3.dex)
2020/10/21 13:36:05.072 5125 5244 Error AndroidRuntime 	at com.samsung.android.gamesdk.GameSDKManager.getSkinTempLevel(GameSDKManager.java:200)
2020/10/21 13:36:44.434 5456 5603 Error AndroidRuntime FATAL EXCEPTION: Thread-15
2020/10/21 13:36:44.434 5456 5603 Error AndroidRuntime Process:  com.game.id, PID: 5456
2020/10/21 13:36:44.434 5456 5603 Error AndroidRuntime java.lang.NoSuchMethodError: No interface method getSkinTempLevel()I in class Lcom/samsung/android/gamesdk/IGameSDKService; or its super classes (declaration of 'com.samsung.android.gamesdk.IGameSDKService' appears in /system/framework/framework.jar!classes3.dex)
2020/10/21 13:36:44.434 5456 5603 Error AndroidRuntime 	at com.samsung.android.gamesdk.GameSDKManager.getSkinTempLevel(GameSDKManager.java:200)
2020/10/21 13:58:05.935 6767 6913 Error AndroidRuntime FATAL EXCEPTION: Thread-15
2020/10/21 13:58:05.935 6767 6913 Error AndroidRuntime Process:  com.game.id, PID: 6767
2020/10/21 13:58:05.935 6767 6913 Error AndroidRuntime java.lang.NoSuchMethodError: No interface method getSkinTempLevel()I in class Lcom/samsung/android/gamesdk/IGameSDKService; or its super classes (declaration of 'com.samsung.android.gamesdk.IGameSDKService' appears in /system/framework/framework.jar!classes3.dex)
2020/10/21 13:58:05.935 6767 6913 Error AndroidRuntime 	at com.samsung.android.gamesdk.GameSDKManager.getSkinTempLevel(GameSDKManager.java:200)
2020/10/21 14:15:59.076 7678 7820 Error AndroidRuntime FATAL EXCEPTION: Thread-15
2020/10/21 14:15:59.076 7678 7820 Error AndroidRuntime Process:  com.game.id, PID: 7678
2020/10/21 14:15:59.076 7678 7820 Error AndroidRuntime java.lang.NoSuchMethodError: No interface method getSkinTempLevel()I in class Lcom/samsung/android/gamesdk/IGameSDKService; or its super classes (declaration of 'com.samsung.android.gamesdk.IGameSDKService' appears in /system/framework/framework.jar!classes3.dex)
2020/10/21 14:15:59.076 7678 7820 Error AndroidRuntime 	at com.samsung.android.gamesdk.GameSDKManager.getSkinTempLevel(GameSDKManager.java:200)
2020/10/21 14:27:06.657 8249 8390 Error AndroidRuntime FATAL EXCEPTION: Thread-15
2020/10/21 14:27:06.657 8249 8390 Error AndroidRuntime Process:  com.game.id, PID: 8249
2020/10/21 14:27:06.657 8249 8390 Error AndroidRuntime java.lang.NoSuchMethodError: No interface method getSkinTempLevel()I in class Lcom/samsung/android/gamesdk/IGameSDKService; or its super classes (declaration of 'com.samsung.android.gamesdk.IGameSDKService' appears in /system/framework/framework.jar!classes3.dex)
2020/10/21 14:27:06.657 8249 8390 Error AndroidRuntime 	at com.samsung.android.gamesdk.GameSDKManager.getSkinTempLevel(GameSDKManager.java:200)
2020/10/21 14:27:56.791 8485 8638 Error AndroidRuntime FATAL EXCEPTION: Thread-15
2020/10/21 14:27:56.791 8485 8638 Error AndroidRuntime Process:  com.game.id, PID: 8485
2020/10/21 14:27:56.791 8485 8638 Error AndroidRuntime java.lang.NoSuchMethodError: No interface method getSkinTempLevel()I in class Lcom/samsung/android/gamesdk/IGameSDKService; or its super classes (declaration of 'com.samsung.android.gamesdk.IGameSDKService' appears in /system/framework/framework.jar!classes3.dex)
2020/10/21 14:27:56.791 8485 8638 Error AndroidRuntime 	at com.samsung.android.gamesdk.GameSDKManager.getSkinTempLevel(GameSDKManager.java:200)
2020/10/21 14:28:05.625 8690 8818 Error AndroidRuntime FATAL EXCEPTION: Thread-15
2020/10/21 14:28:05.625 8690 8818 Error AndroidRuntime Process:  com.game.id, PID: 8690
2020/10/21 14:28:05.625 8690 8818 Error AndroidRuntime java.lang.NoSuchMethodError: No interface method getSkinTempLevel()I in class Lcom/samsung/android/gamesdk/IGameSDKService; or its super classes (declaration of 'com.samsung.android.gamesdk.IGameSDKService' appears in /system/framework/framework.jar!classes3.dex)
2020/10/21 14:28:05.625 8690 8818 Error AndroidRuntime 	at com.samsung.android.gamesdk.GameSDKManager.getSkinTempLevel(GameSDKManager.java:200)
2020/10/21 14:28:44.169 8866 9012 Error AndroidRuntime FATAL EXCEPTION: Thread-15
2020/10/21 14:28:44.169 8866 9012 Error AndroidRuntime Process:  com.game.id, PID: 8866
2020/10/21 14:28:44.169 8866 9012 Error AndroidRuntime java.lang.NoSuchMethodError: No interface method getSkinTempLevel()I in class Lcom/samsung/android/gamesdk/IGameSDKService; or its super classes (declaration of 'com.samsung.android.gamesdk.IGameSDKService' appears in /system/framework/framework.jar!classes3.dex)
2020/10/21 14:28:44.169 8866 9012 Error AndroidRuntime 	at com.samsung.android.gamesdk.GameSDKManager.getSkinTempLevel(GameSDKManager.java:200)
2020/10/21 14:38:55.924 9419 9563 Error AndroidRuntime FATAL EXCEPTION: Thread-15
2020/10/21 14:38:55.924 9419 9563 Error AndroidRuntime Process:  com.game.id, PID: 9419
2020/10/21 14:38:55.924 9419 9563 Error AndroidRuntime java.lang.NoSuchMethodError: No interface method getSkinTempLevel()I in class Lcom/samsung/android/gamesdk/IGameSDKService; or its super classes (declaration of 'com.samsung.android.gamesdk.IGameSDKService' appears in /system/framework/framework.jar!classes3.dex)
2020/10/21 14:38:55.924 9419 9563 Error AndroidRuntime 	at com.samsung.android.gamesdk.GameSDKManager.getSkinTempLevel(GameSDKManager.java:200)
2020/10/21 14:43:00.013 9785 9929 Error AndroidRuntime FATAL EXCEPTION: Thread-15
2020/10/21 14:43:00.013 9785 9929 Error AndroidRuntime Process:  com.game.id, PID: 9785
2020/10/21 14:43:00.013 9785 9929 Error AndroidRuntime java.lang.NoSuchMethodError: No interface method getSkinTempLevel()I in class Lcom/samsung/android/gamesdk/IGameSDKService; or its super classes (declaration of 'com.samsung.android.gamesdk.IGameSDKService' appears in /system/framework/framework.jar!classes3.dex)
2020/10/21 14:43:00.013 9785 9929 Error AndroidRuntime 	at com.samsung.android.gamesdk.GameSDKManager.getSkinTempLevel(GameSDKManager.java:200)
2020/10/21 16:26:19.725 15948 16136 Error AndroidRuntime FATAL EXCEPTION: Thread-15
2020/10/21 16:26:19.725 15948 16136 Error AndroidRuntime Process:  com.game.id, PID: 15948
2020/10/21 16:26:19.725 15948 16136 Error AndroidRuntime java.lang.NoSuchMethodError: No interface method getSkinTempLevel()I in class Lcom/samsung/android/gamesdk/IGameSDKService; or its super classes (declaration of 'com.samsung.android.gamesdk.IGameSDKService' appears in /system/framework/framework.jar!classes3.dex)
2020/10/21 16:26:19.725 15948 16136 Error AndroidRuntime 	at com.samsung.android.gamesdk.GameSDKManager.getSkinTempLevel(GameSDKManager.java:200)
2020/10/21 16:26:53.457 16230 16349 Error AndroidRuntime FATAL EXCEPTION: Thread-15
2020/10/21 16:26:53.457 16230 16349 Error AndroidRuntime Process:  com.game.id, PID: 16230
2020/10/21 16:26:53.457 16230 16349 Error AndroidRuntime java.lang.NoSuchMethodError: No interface method getSkinTempLevel()I in class Lcom/samsung/android/gamesdk/IGameSDKService; or its super classes (declaration of 'com.samsung.android.gamesdk.IGameSDKService' appears in /system/framework/framework.jar!classes3.dex)
2020/10/21 16:26:53.457 16230 16349 Error AndroidRuntime 	at com.samsung.android.gamesdk.GameSDKManager.getSkinTempLevel(GameSDKManager.java:200)
0001/01/01 00:00:00.000 -1 -1 Info  --------- beginning of main
2020/10/21 16:29:00.177 2345 2381 Error AccessibilityManager semUpdateAssitantMenu invoking from manager:
2020/10/21 16:29:00.177 3904 5935 Debug InputTransport Input channel constructed: fd=538
2020/10/21 16:29:00.178 2345 2381 Error AccessibilityManager semUpdateAssitantMenu invoking from manager:
2020/10/21 16:29:00.178 2345 13864 Debug InputTransport Input channel constructed: fd=99
2020/10/21 16:29:00.178 2345 2381 Error AccessibilityManager semUpdateAssitantMenu invoking from manager:
`
ARMV7... What this is with 10.10. Anyone have any ideas? Same code and build works on another game

**Comment by danoli3** [comment]
Samsung Galaxy Note8 
Android 9
Security Patch September 2020

**Comment by pelegk11** [comment]
Hey, i got the same issue, for me it was Samsung Adapative Performance which caused it, i removed the package from the Package manager and the problem stopped!
good luck, hope it helps!

**Comment by danoli3** [comment]
@pelegk11 Omg Yes Thank you!! For All that follow this path! The Solution for Samsung Devices is remove the Performance Package from Unity even if you are not yet using it.
It seems to conflict with the Google Play Games Plugin in some way when authenticating
