### ISSUE TITLE
The .meta file Assets/GooglePlayGames/Editor/GooglePlayGamesPlugin_v0.10.11.txt.meta does not have a valid GUID and its corresponding Asset file will be ignored

### ISSUE THREAD

**Issue by danoli3** [playgameservices/play-games-plugin-for-unity#2967]
**Can we please fix this in future Releases!** 

`The .meta file Assets/GooglePlayGames/Editor/GooglePlayGamesPlugin_v0.10.11.txt.meta does not have a valid GUID and its corresponding Asset file will be ignored. If this file is not malformed, please add a GUID, or delete the .meta file and it will be recreated correctly`

`The .meta file Assets/GooglePlayGames/Editor/GooglePlayGamesPlugin_v0.10.10.txt.meta does not have a valid GUID and its corresponding Asset file will be ignored. If this file is not malformed, please add a GUID, or delete the .meta file and it will be recreated correctly`

**Comment by aryanshdev** [comment]
Just go the the Directory mentioned, `Assets/GooglePlayGames/Editor/` then find the file **GooglePlayGamesPlugin_v0.10.11.txt.meta** and Delete it. It will be fine again<br><br>Then you may also repeat the steps of Android Setup (pasting xml and all).

**Comment by ozdemir08** [comment]
Thanks for bringing this up. Fixed with the latest version!

**Comment by danoli3** [comment]
Nice one thank you
