### ISSUE TITLE
Changing who can see leaderboards

### ISSUE THREAD

**Issue by Adiefallguy** [playgameservices/play-games-plugin-for-unity#2968]
I am wondering if there is anyway to change who can see a players leaderboard within my game without needing to load the generic ShowLeaderboardUI() call.

I have created a custom leaderboard screen within my game and it return results fine, my problem is that as default google account dont show leaderboards to public, when you use the showleaderboardui() call and it brings up the panel there is a toggle to change from friends to public and this is what I would like to do on my custom screen but cannot find a way.

**Comment by olehkuznetsov** [comment]
Currently there is no way to do that. We will think how to add that possibility.
