### ISSUE TITLE
Google Play Games Integration Doing Nothing Except a Pop-up

### ISSUE THREAD

**Issue by aryanshdev** [playgameservices/play-games-plugin-for-unity#2969]
I am using **Unity 2020.2** and **Google Play Services Plugin Version 0.10.11 (latest)**<br>
When Ever I Build and run the app on Android Device,  It just shows a Simple Pop-up saying - *"Connecting To Google Play Games"* and then nothing happens at all. Neither it connects to Play Games, nor it shows any error...<br>
**I tried checking all things in Play Console and Developer Console but everything seems fine, tried many solutions but nothing works.** Please Help, I am really Tired..<br><br>
Script Used -->
```csharp
void Start()
        {
            Authenticate(); 
        }

public void Authenticate()
        {
            try {
                Debug.Log("Starting");
                PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().Build();
                Debug.Log("config made");
    
                PlayGamesPlatform.InitializeInstance(config);
                Debug.Log("Activated Instance");
                PlayGamesPlatform.Activate();
                Debug.Log("Activated Platform");
                PlayGamesPlatform.Instance.Authenticate((bool success) =>
                {
                    Debug.Log("Inside Authentication, Success = "+success);
                    if (success)
                    {
                        Debug.Log("Authenticated");
    
                    }
                    else
                    {
                        Debug.Log("Failed");
                    }
                }
                );
    
            }
            catch(Exception e)
            {
                Debug.Log("Error :---");
                Debug.Log(e);
            }
        }
```
Here is the Log : (adb logcat):

    11-02 14:40:42.499 19664 19679 I Unity   : Starting
    11-02 14:40:42.499 19664 19679 I Unity   : UnityEngine.Logger:Log(LogType, Object)
    11-02 14:40:42.499 19664 19679 I Unity   : GPGSManager:Authenticate()
    11-02 14:40:42.499 19664 19679 I Unity   : UnityEngine.Events.UnityAction:Invoke()
    11-02 14:40:42.499 19664 19679 I Unity   : UnityEngine.Events.UnityEvent:Invoke()
    11-02 14:40:42.499 19664 19679 I Unity   : UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
    11-02 14:40:42.499 19664 19679 I Unity   : UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
    11-02 14:40:42.499 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
    11-02 14:40:42.499 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
    11-02 14:40:42.499 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:Process()
    11-02 14:40:42.499 19664 19679 I Unity   :
    11-02 14:40:42.500 19664 19679 I Unity   : config made
    11-02 14:40:42.500 19664 19679 I Unity   : UnityEngine.Logger:Log(LogType, Object)
    11-02 14:40:42.500 19664 19679 I Unity   : GPGSManager:Authenticate()
    11-02 14:40:42.500 19664 19679 I Unity   : UnityEngine.Events.UnityAction:Invoke()
    11-02 14:40:42.500 19664 19679 I Unity   : UnityEngine.Events.UnityEvent:Invoke()
    11-02 14:40:42.500 19664 19679 I Unity   : UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
    11-02 14:40:42.500 19664 19679 I Unity   : UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
    11-02 14:40:42.500 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
    11-02 14:40:42.500 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
    11-02 14:40:42.500 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:Process()
    11-02 14:40:42.500 19664 19679 I Unity   :
    11-02 14:40:42.501 19664 19679 I Unity   : Activated Instance
    11-02 14:40:42.501 19664 19679 I Unity   : UnityEngine.Logger:Log(LogType, Object)
    11-02 14:40:42.501 19664 19679 I Unity   : GPGSManager:Authenticate()
    11-02 14:40:42.501 19664 19679 I Unity   : UnityEngine.Events.UnityAction:Invoke()
    11-02 14:40:42.501 19664 19679 I Unity   : UnityEngine.Events.UnityEvent:Invoke()
    11-02 14:40:42.501 19664 19679 I Unity   : UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
    11-02 14:40:42.501 19664 19679 I Unity   : UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
    11-02 14:40:42.501 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
    11-02 14:40:42.501 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
    11-02 14:40:42.501 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:Process()
    11-02 14:40:42.501 19664 19679 I Unity   :
    11-02 14:40:42.502 19664 19679 I Unity   : Activated Platform
    11-02 14:40:42.502 19664 19679 I Unity   : UnityEngine.Logger:Log(LogType, Object)
    11-02 14:40:42.502 19664 19679 I Unity   : GPGSManager:Authenticate()
    11-02 14:40:42.502 19664 19679 I Unity   : UnityEngine.Events.UnityAction:Invoke()
    11-02 14:40:42.502 19664 19679 I Unity   : UnityEngine.Events.UnityEvent:Invoke()
    11-02 14:40:42.502 19664 19679 I Unity   : UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
    11-02 14:40:42.502 19664 19679 I Unity   : UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
    11-02 14:40:42.502 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
    11-02 14:40:42.502 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
    11-02 14:40:42.502 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:Process()
    11-02 14:40:42.502 19664 19679 I Unity   :
    11-02 14:40:42.503 19664 19679 I Unity   : Starting Auth with token client.
    11-02 14:40:42.503 19664 19679 I Unity   : UnityEngine.Logger:Log(LogType, Object)
    11-02 14:40:42.503 19664 19679 I Unity   : GooglePlayGames.Android.AndroidClient:Authenticate(Boolean, Action`1)
    11-02 14:40:42.503 19664 19679 I Unity   : GPGSManager:Authenticate()
    11-02 14:40:42.503 19664 19679 I Unity   : UnityEngine.Events.UnityAction:Invoke()
    11-02 14:40:42.503 19664 19679 I Unity   : UnityEngine.Events.UnityEvent:Invoke()
    11-02 14:40:42.503 19664 19679 I Unity   : UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
    11-02 14:40:42.503 19664 19679 I Unity   : UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
    11-02 14:40:42.503 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
    11-02 14:40:42.503 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
    11-02 14:40:42.503 19664 19679 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:Process()
    11-02 14:40:42.503 19664 19679 I Unity   :
    11-02 14:40:42.504 19664 19679 W Unity   : !!! [Play Games Plugin 0.10.11] 11-02-20 14:40:42 +05:30 WARNING: PlayGamesPlatform already initialized. Ignoring this call.
    11-02 14:40:42.504 19664 19679 W Unity   : UnityEngine.Logger:Log(LogType, Object)
    11-02 14:40:42.504 19664 19679 W Unity   : System.Action:Invoke()
    11-02 14:40:42.504 19664 19679 W Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
    11-02 14:40:42.504 19664 19679 W Unity   :
    11-02 14:40:42.698 19664 19679 W Unity   : Internal: JobTempAlloc has allocations that are more than 4 frames old - this is not allowed and likely a leak
    11-02 14:40:42.698 19664 19679 W Unity   :
    11-02 14:40:42.885 19664 19664 I Unity   : windowFocusChanged: false
    11-02 14:40:42.885 19664 19664 I Unity   : onPause
    11-02 14:40:42.919 19664 19679 D Unity   : Sensor :        Accelerometer ( 1) ; 0.019150 / 0.00s ; BMA255 Accelerometer/Temperature/Double-tap / BOSCH
    11-02 14:40:48.213 19664 19664 I Unity   : windowFocusChanged: true
    11-02 14:40:48.244 19664 19664 I Unity   : Returning an error code.
    11-02 14:40:48.244 19664 19664 I Unity   : UnityEngine.Logger:Log(LogType, Object)
    11-02 14:40:48.244 19664 19664 I Unity   : GooglePlayGames.Android.<>c__DisplayClass18_0:<Authenticate>b__0(Int32)
    11-02 14:40:48.244 19664 19664 I Unity   : System.Action`1:Invoke(T)
    11-02 14:40:48.244 19664 19664 I Unity   : System.Action`1:Invoke(T)
    11-02 14:40:48.244 19664 19664 I Unity   : System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
    11-02 14:40:48.244 19664 19664 I Unity   : System.Reflection.MethodBase:Invoke(Object, Object[])
    11-02 14:40:48.244 19664 19664 I Unity   : UnityEngine.AndroidJavaProxy:Invoke(String, Object[])
    11-02 14:40:48.244 19664 19664 I Unity   : UnityEngine._AndroidJNIHelper:InvokeJavaProxyMethod(AndroidJavaProxy, IntPtr, IntPtr)
    11-02 14:40:48.244 19664 19664 I Unity   :
    11-02 14:40:48.247 19664 19664 I Unity   : onResume
    11-02 14:40:48.257 19664 19679 D Unity   : Sensor :        Accelerometer ( 1) ; 0.019150 / 0.00s ; BMA255 Accelerometer/Temperature/Double-tap / BOSCH
    11-02 14:40:48.280 19664 19679 D Unity   : Choreographer available: Enabling VSYNC timing
    11-02 14:40:48.284 19664 19679 I Unity   : Inside Authentication, Success = False
    11-02 14:40:48.284 19664 19679 I Unity   : UnityEngine.Logger:Log(LogType, Object)
    11-02 14:40:48.284 19664 19679 I Unity   : GPGSManager:<Authenticate>b__5_0(Boolean)
    11-02 14:40:48.284 19664 19679 I Unity   : System.Action`1:Invoke(T)
    11-02 14:40:48.284 19664 19679 I Unity   : System.Action`2:Invoke(T1, T2)
    11-02 14:40:48.284 19664 19679 I Unity   : GooglePlayGames.<>c__DisplayClass33_0:<Authenticate>b__0(SignInStatus)11-02 14:40:48.284 19664 19679 I Unity   : System.Action`1:Invoke(T)
    11-02 14:40:48.284 19664 19679 I Unity   : System.Action`1:Invoke(T)
    11-02 14:40:48.284 19664 19679 I Unity   : System.Action:Invoke()
    11-02 14:40:48.284 19664 19679 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
    11-02 14:40:48.284 19664 19679 I Unity   :
    11-02 14:40:48.286 19664 19679 I Unity   : Failed
    11-02 14:40:48.286 19664 19679 I Unity   : UnityEngine.Logger:Log(LogType, Object)
    11-02 14:40:48.286 19664 19679 I Unity   : GPGSManager:<Authenticate>b__5_0(Boolean)
    11-02 14:40:48.286 19664 19679 I Unity   : System.Action`1:Invoke(T)
    11-02 14:40:48.286 19664 19679 I Unity   : System.Action`2:Invoke(T1, T2)
    11-02 14:40:48.286 19664 19679 I Unity   : GooglePlayGames.<>c__DisplayClass33_0:<Authenticate>b__0(SignInStatus)11-02 14:40:48.286 19664 19679 I Unity   : System.Action`1:Invoke(T)
    11-02 14:40:48.286 19664 19679 I Unity   : System.Action`1:Invoke(T)
    11-02 14:40:48.286 19664 19679 I Unity   : System.Action:Invoke()
    11-02 14:40:48.286 19664 19679 I Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
<br>
This is what is shows Ingame on Android device :

![Screenshot](https://answers.unity.com/storage/attachments/170273-screenshot-2020-11-01-21-38-32-820.jpeg)

**Comment by SebastianMitea** [comment]
I'm having the same problem. On Unity 2019.2.15f and Google Play Services Plugin Version 0.10.11 (latest). I looked up the error code and it's code 16 (SignInStatus.Canceled). 
.

**Comment by aryanshdev** [comment]
I found the Problem.<br>
**Google Had different SHA1 Key as compared to SHA1 Key of my Keystore**<br>
***I added both key to Authentication and now It's Working Fine***

**Comment by SebastianMitea** [comment]
It looks like I have 2 as well,  can you tell me where to use them both. Do I need to have 2 credentials in the Google Console or it's something in the unity project?
