### ISSUE TITLE
I can't sign in google play when user click button

### ISSUE THREAD

**Issue by quyendk98** [playgameservices/play-games-plugin-for-unity#2971]
i created a button in my game, if user click to it then it will sign in google, but while I test I have encountered this error on monitor tools of unity
my error got:
java.lang.ClassNotFoundException: Didn't find class "com/google/android/gms/games/Games"

I fixed it in a few ways on google but it still can't be fixed, why?
i change minify release and debug from none -> proguard, enable "proguard file"
this is all lines in my file proguard
-keep class com.google.android.gms.games.leaderboard.** { *; }
-keep class com.google.android.gms.games.snapshot.** { *; }
-keep class com.google.android.gms.games.achievement.** { *; }
-keep class com.google.android.gms.games.event.** { *; }
-keep class com.google.android.gms.games.stats.** { *; }
-keep class com.google.android.gms.games.video.** { *; }
-keep class com.google.android.gms.games.* { *; }
-keep class com.google.android.gms.common.api.ResultCallback { *; }
-keep class com.google.android.gms.signin.** { *; }
-keep class com.google.android.gms.dynamic.** { *; }
-keep class com.google.android.gms.dynamite.** { *; }
-keep class com.google.android.gms.tasks.** { *; }
-keep class com.google.android.gms.security.** { *; }
-keep class com.google.android.gms.base.** { *; }
-keep class com.google.android.gms.actions.** { *; }
-keep class com.google.games.bridge.** { *; }
-keep class com.google.android.gms.common.ConnectionResult { *; }
-keep class com.google.android.gms.common.GooglePlayServicesUtil { *; }
-keep class com.google.android.gms.common.api.** { *; }
-keep class com.google.android.gms.common.data.DataBufferUtils { *; }
-keep class com.google.android.gms.games.quest.** { *; }
-keep class com.google.android.gms.nearby.** { *; }

I am using:
- Unity 2019.4.2f1
- Google play services 0.10.11

PLEASE HELP ME :( I REALLY NEED HELP, THANK YOU FOR READING, HAVE A NICE DAY

**Comment by rizqirizqi** [comment]
I got that error yesterday after upgrading Unity to 2019.4.15f1. Several hours of trying different configurations but still stuck with that error. Then, when I check git status, I found out that Unity deleted some files in `/Assets/Plugins/Android/*`. Just recover the deleted files and it runs fine.

**Comment by quyendk98** [comment]
oh thank you so much bro

Vào CN, 22 thg 11, 2020 vào lúc 13:45 Mgs. M. Rizqi Fadhlurrahman <
notifications@github.com> đã viết:
