### ISSUE TITLE
Login Result Cancelled + Google Play Console configuration

### ISSUE THREAD

**Issue by rizqirizqi** [playgameservices/play-games-plugin-for-unity#2974]
Hi, I got this error but still stuck for several days. Been going through almost every link in google to search for a clue. But I couldn't find one. I don't know if it's an error with `play-games-plugin-for-unity` or something wrong with my configuration in Google Play Console.

<img src="https://user-images.githubusercontent.com/6806365/99897449-2293e380-2ccc-11eb-86b8-3ddd3311498b.jpg" width="70%"/>

After some trial and error, I've followed [this guide](https://diegogiacomelli.com.br/google-play-games-plugin-for-unity-tips-and-tricks/) for the SHA-1 App Signing config, and I'm pretty sure that it's the correct configuration. But still don't know whether I missed the other config.

In the log, it said "Returning an error code", where can I find what error is it?

**Comment by ozdemir08** [comment]
Did you follow [this guide](https://developers.google.com/games/services/console/enabling)? It is very likely that there is a mistake in creating the keystore file.

**Comment by ozdemir08** [comment]
You may also want to check out [this issue](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2940)

**Comment by ozdemir08** [comment]
Probably [this issue](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2878) will solve your problems. I'm closing this bug. Feel free to reopen it if the issue persists.
