### ISSUE TITLE
Auth, account picker not displayed

### ISSUE THREAD

**Issue by ClemMahe** [playgameservices/play-games-plugin-for-unity#2975]
Hello,
I am bit bothered about a behavior in my app and I would like to know if someone have any idea what could cause this behavior.
Thank you !  (Unity 2019.4.13 + GooglePlayGamesPlugin-0.10.11.unitypackage).

When lauching the app for the first time & calling Authentication with RequestEmail+EnableSavedGames, the app displays the popup for granting authorization (create, modify, delete activity) before the "account picker". If I press back or if I press outside the popup, I see the account picker popup. 
**-> My hypothesis is that the Authentication is selecting automatically an account.**

Unfortunately, even after calling **Signout**, this does change the behavior.
What I tried : 
-> I have another application with same signin code which behaves correctly (picker first)
-> Having two google accounts on the phone -> Same behavior
-> Granting everything, removing app + removing rights from https://myaccount.google.com/permissions, then try reinstall. Same.

So I am wondering if there a setting somewhere on the playstore developer console / google console or on the phone that is causing this account default selection that I am trying to avoid. 
If something wasn't clear enough, please let me clarify / I didn't find similar issues which weren't resolved by Signout.

Thanks a lot.

<img src="https://user-images.githubusercontent.com/3418335/99972596-014ff780-2d9f-11eb-816c-ab8ae8bb2b65.jpg"  width="200"  />

**Comment by ozdemir08** [comment]
It is true that there is a default account based on the previous activities on the device. This default account allows users to see one less screen and do one less click in most cases. However, as you mentioned, clicking back will take users to the account picker. 
Currently, developers can not disable the default account selection. However, your users can do so by using settings in `Play Games > Settings > Profile and Privacy`.
