### ISSUE TITLE
Authentication never happens!

### ISSUE THREAD

**Issue by faisal007** [playgameservices/play-games-plugin-for-unity#298]
Hello,

I m using this plugin in my android project but seems like i m stuck in start and authentication not working:

Social.localUser.Authenticate((bool success) =>
			{
				if(success)
					print ("Logged in");
				else
					print ("Not logged in");
			});

In editor is shows "no logged in ", On device its do nothing, no sign in popup shows, i have also logged out from google play store. But not working at all. I have connected debugger and think its going in fail condition.

**Comment by claywilkinson** [comment]
passing along the issue tracking internally as 19129145

**Comment by claywilkinson** [comment]
Can you confirm that your project has Assets/Plugins/Android/android-support-v4.jar and  Assets/Plugins/Android/MainLibProj/libs/play-games-plugin-support.jar?

If not, you should try re-adding the latest plugin to your project.

**Comment by ShadoVv91** [comment]
Sorry for late answer, I was busy lately.

These file are attached to project. I will try to check if it is working with last version for a moment, because I see there is new one.

**Comment by Nidre** [comment]
I have the same problem with GooglePlayGamesPlugin-0.9.12 any solutions so far ? I have mentioned files attached and Google Play Services is updated to latest version.

**Comment by Nidre** [comment]
Here is the cat log;

02-15 20:55:54.488    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Trying to load lib /data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so 0x41ec0f50
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Added shared lib /data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so 0x41ec0f50
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 D/GamesUnitySDK﹕ Performing Android initialization of the GPG SDK
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/common/ConnectionResult: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/common/GooglePlayServicesUtil: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/common/api/Api: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/common/api/Api$ApiOptions: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/common/api/Api$ApiOptions$HasOptions: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/common/api/GoogleApiClient: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/common/api/GoogleApiClient$Builder: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/common/api/PendingResult: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/common/api/Result: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/common/api/ResultCallback: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/common/api/Scope: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/common/api/Status: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/common/data/DataBufferUtils: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/Games: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/Games$GamesOptions: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/Games$GamesOptions$Builder: an exception occurred.
02-15 20:55:54.493    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/Player: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/PlayerBuffer: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/PlayerLevel: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/PlayerLevelInfo: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/Players: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/Players$LoadPlayersResult: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/achievement/Achievement: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/achievement/Achievements$LoadAchievementsResult: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/event/Event: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/event/EventBuffer: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/event/Events: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/event/Events$LoadEventsResult: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/achievement/AchievementBuffer: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/achievement/Achievements: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/leaderboard/Leaderboard: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/leaderboard/LeaderboardBuffer: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/leaderboard/Leaderboards: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/leaderboard/LeaderboardScore: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/leaderboard/LeaderboardScoreBuffer: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/leaderboard/LeaderboardVariant: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/leaderboard/Leaderboards$LeaderboardMetadataResult: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/leaderboard/Leaderboards$LoadScoresResult: an exception occurred.
02-15 20:55:54.498    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/Invitation: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/InvitationBuffer: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/Invitations: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/Invitations$LoadInvitationsResult: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/Multiplayer: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/Participant: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/ParticipantResult: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/turnbased/LoadMatchesResponse: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatch: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchBuffer: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchConfig: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchConfig$Builder: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$CancelMatchResult: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$InitiateMatchResult: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LeaveMatchResult: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LoadMatchesResult: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LoadMatchResult: an exception occurred.
02-15 20:55:54.503    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$UpdateMatchResult: an exception occurred.
02-15 20:55:54.508    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/quest/Quest: an exception occurred.
02-15 20:55:54.508    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/quest/QuestBuffer: an exception occurred.
02-15 20:55:54.508    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/quest/Quests: an exception occurred.
02-15 20:55:54.508    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/quest/Milestone: an exception occurred.
02-15 20:55:54.508    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/quest/Quests$LoadQuestsResult: an exception occurred.
02-15 20:55:54.508    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/quest/Quests$AcceptQuestResult: an exception occurred.
02-15 20:55:54.508    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/quest/Quests$ClaimMilestoneResult: an exception occurred.
02-15 20:55:54.508    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/snapshot/Snapshot: an exception occurred.
02-15 20:55:54.513    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/snapshot/SnapshotContents: an exception occurred.
02-15 20:55:54.513    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/snapshot/SnapshotMetadata: an exception occurred.
02-15 20:55:54.513    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataBuffer: an exception occurred.
02-15 20:55:54.513    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/snapshot/Snapshots: an exception occurred.
02-15 20:55:54.513    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/snapshot/Snapshots$CommitSnapshotResult: an exception occurred.
02-15 20:55:54.513    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/snapshot/Snapshots$LoadSnapshotsResult: an exception occurred.
02-15 20:55:54.513    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/snapshot/Snapshots$OpenSnapshotResult: an exception occurred.
02-15 20:55:54.513    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataChange: an exception occurred.
02-15 20:55:54.513    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataChange$Builder: an exception occurred.
02-15 20:55:54.513    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMessageReceivedListener: an exception occurred.
02-15 20:55:54.513    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMultiplayer: an exception occurred.
02-15 20:55:54.513    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMessage: an exception occurred.
02-15 20:55:54.518    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/realtime/Room: an exception occurred.
02-15 20:55:54.518    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/realtime/RoomConfig: an exception occurred.
02-15 20:55:54.518    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/games/multiplayer/realtime/RoomConfig$Builder: an exception occurred.
02-15 20:55:54.518    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Can't register class com/google/android/gms/appstate/AppStateManager: an exception occurred.
02-15 20:55:54.518    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Trying to load lib /data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so 0x41ec0f50
02-15 20:55:54.518    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Shared lib '/data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so' already loaded in same CL 0x41ec0f50
02-15 20:55:54.528    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Trying to load lib /data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so 0x41ec0f50
02-15 20:55:54.528    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Shared lib '/data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so' already loaded in same CL 0x41ec0f50
02-15 20:55:54.528    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Trying to load lib /data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so 0x41ec0f50
02-15 20:55:54.528    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Shared lib '/data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so' already loaded in same CL 0x41ec0f50
02-15 20:55:54.533    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Trying to load lib /data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so 0x41ec0f50
02-15 20:55:54.533    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Shared lib '/data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so' already loaded in same CL 0x41ec0f50
02-15 20:55:54.533    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Trying to load lib /data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so 0x41ec0f50
02-15 20:55:54.533    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Shared lib '/data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so' already loaded in same CL 0x41ec0f50
02-15 20:55:54.548    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Trying to load lib /data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so 0x41ec0f50
02-15 20:55:54.548    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Shared lib '/data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so' already loaded in same CL 0x41ec0f50
02-15 20:55:54.553    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Trying to load lib /data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so 0x41ec0f50
02-15 20:55:54.553    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Shared lib '/data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so' already loaded in same CL 0x41ec0f50
02-15 20:55:54.553    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Trying to load lib /data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so 0x41ec0f50
02-15 20:55:54.553    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Shared lib '/data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so' already loaded in same CL 0x41ec0f50
02-15 20:55:54.558    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Trying to load lib /data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so 0x41ec0f50
02-15 20:55:54.558    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Shared lib '/data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so' already loaded in same CL 0x41ec0f50
02-15 20:55:54.558    7978-7996/com.MogaMecha.SaveTheComet1 E/GamesNativeSDK﹕ Could not register one or more required Java classes.
02-15 20:55:54.563    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Trying to load lib /data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so 0x41ec0f50
02-15 20:55:54.563    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Shared lib '/data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so' already loaded in same CL 0x41ec0f50
02-15 20:55:54.563    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Trying to load lib /data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so 0x41ec0f50
02-15 20:55:54.563    7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Shared lib '/data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so' already loaded in same CL 0x41ec0f50
02-15 20:55:54.598    7978-7996/com.MogaMecha.SaveTheComet1 I/Unity﹕ InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK
            at GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build (GooglePlayGames.Native.PInvoke.PlatformConfiguration configRef) [0x0002d] in C:\Users\Erdin\Desktop\Ewerything\Creative Stuff\Development\Repositories\save-the-comet\Assets\GooglePlayGames\Platforms\Native\PInvoke\GameServicesBuilder.cs:146
            at GooglePlayGames.Native.NativeClient.InitializeGameServices () [0x0008f] in C:\Users\Erdin\Desktop\Ewerything\Creative Stuff\Development\Repositories\save-the-comet\Assets\GooglePlayGames\Platforms\Native\NativeClient.cs:147
            at GooglePlayGames.Native.NativeClient.Authenticate (System.Action`1 callback, Boolean silent) [0x00099] in C:\Users\Erdin\Desktop\Ewerything\Creative Stuff\Development\Repositories\save-the-comet\Assets\GooglePlayGames\Platforms\Native\NativeClient.cs:100
            at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`1 callback, Boolean silent) [0x00026] in C

**Comment by Nidre** [comment]
Not sure if this is the reason but i have seen something odd with the log files;

02-15 20:55:54.488 7978-7996/com.MogaMecha.SaveTheComet1 D/dalvikvm﹕ Trying to load lib /data/app-lib/com.MogaMecha.SaveTheComet1-1/libgpg.so 0x41ec0f50

Our bundle identifier is com.MogaMecha.SaveTheComet1 not com.MogaMecha.SaveTheComet1-1.

**Comment by claywilkinson** [comment]
@Nidre  - can confirm what files are in your project under 
Assets/Plugins/Android/google-play-services_lib, and what the versions are, also can you confirm these files are in the generated APK?

**Comment by Nidre** [comment]
Files locations are as following;
Plugins/Android/android-support-v4
Plugins/Android/google-play-services_lib/libs/google-play-services.jar

How can i confirm if they are in the generated APK? Is there way to see them inside the APK?

**Comment by claywilkinson** [comment]
Thanks  APK files are actually zipped, so rename the the apk to end in .zip and then you can unzip it.

**Comment by Nidre** [comment]
If i am not mistaken they are not in the apk file. Any suggestions on how to fix it? I would expect them to be compiled in to the apk since they are in appropriate folders in Unity.

**Comment by Nidre** [comment]
Now as i am checking some of our older builds i am not able to find the .jar files inside the .apk too. But they were working without any problems, so i am guessing i am looking at the wrong place. Can you tell where exactly should i see the .jar files in .apk file?

Other plugins with jar files seems to be working without problems by the way.

**Comment by boricuamobile** [comment]
any news on this ? ive got exact same issue, wont sign in, will throw all those errors above, using latest plug in version and latest google play game services jar.

**Comment by wensixing** [comment]
I have the same proble.
[code]
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/PlayerLevel: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/PlayerLevelInfo: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/event/Event: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/event/EventBuffer: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/event/Events: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/event/Events$LoadEventsResult: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/quest/Quest: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/quest/QuestBuffer: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/quest/Quests: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/quest/Milestone: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/quest/Quests$LoadQuestsResult: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/quest/Quests$AcceptQuestResult: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/quest/Quests$ClaimMilestoneResult: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/snapshot/Snapshot: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/snapshot/SnapshotContents: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadata: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataBuffer: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/snapshot/Snapshots: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/snapshot/Snapshots$CommitSnapshotResult: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/snapshot/Snapshots$LoadSnapshotsResult: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/snapshot/Snapshots$OpenSnapshotResult: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataChange: an exception occurred.
E/GamesNativeSDK( 5586): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataChange$Builder: an exception occurred.
E/GamesNativeSDK( 5586): Could not register one or more required Java classes.
[/code]

**Comment by samtstern** [comment]
@wensixing are you generating an Android project with Unity and running it manually (from Eclipse or similar) or are you running the Android app directly from Unity?

**Comment by wensixing** [comment]
@samtstern 
Just build & run. Running the Android app directly from Unity.

**Comment by claywilkinson** [comment]
@faisal007  are you still having problems building the samples or can I close this issue?

**Comment by Nidre** [comment]
@claywilkinson This issue still persists for me.

**Comment by ShadoVv91** [comment]
I have just tried to set up plugin on another machine with new project, and newest version of plugin (Unity 5, win 8.1, Xperia Sony Z2) and i still getting exactly same error. Before I get this error, I get error about missing AndroidManifest.xml in Plugins/Android/MainLibProj, so I've copied it from template (GooglePlayGames/Editor/template-AndroidMannifest), then was the problem with value  '@integer/google_play_services_version' so i copied version.xml from sdk files to res folder and now i stack on this problem again.

**Comment by ShadoVv91** [comment]
I've resolve it but it's hard to explain. What I did:
1. Removed and import plugin again 
2. Make sure that you set up your APP idd and android-support-v4 was generateg !!!
3. Copied file "google-play-services.jar" from android sdk to Plugins/Android/libs but after initializing google play games services with app id, it was duplicated so I removed it. 
4. Build and enjoy

I gusess that I trying to do it at my last project and it did't work. I will try again when I get back home and let you know about the results.

**Comment by claywilkinson** [comment]
This can also happen when you don't have the play services SDK in the "extras" section.  Check the Android SDK manager to make sure you have the latest version of "Google Play services" .
Instructions for the SDK  manager  can be found at https://developer.android.com/tools/help/sdk-manager.html

**Comment by claywilkinson** [comment]
There was an update to Google Play Services, can you post a log file and which version of Google Play Services you are using? (The play services app is also called "Google Settings").
Thanks!

**Comment by ShadoVv91** [comment]
I have just tried to integrate plugin with my old project for which one bug was firstly reported and this time everything works fine. I've just download fresh version, provide app id and initialize project. Google play services revision is 22 (ther is available update to rev. 24)

**Comment by claywilkinson** [comment]
Great news! thanks for the response.
