### ISSUE TITLE
Play games services are not initializing

### ISSUE THREAD

**Issue by rohitck007** [playgameservices/play-games-plugin-for-unity#2982]
Leaderboards were working fine in my games but recently I updated my games and leaderboard stopped working! I see there are some changes related to play game services in developer console. I need to add OAuth2.0 credentials which I did by following instructions given in following link 
https://developers.google.com/games/services/console/enabling
But still play games services are not initializing when I launch my game. Is there any other documentation related to this which can help me in sort out this issue?

**Comment by djmuhlestein** [comment]
Have you added debugging to your PlayGamesPlatform?

        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.DebugLogEnabled = true;
        PlayGamesPlatform.Activate();   

That may give more information in your logging if you haven't already done it.

**Comment by rohitck007** [comment]
Sorry I spent almost more than one month on this & finally I created my own leaderboard on server which I can use across multiple platforms. I am closing this issue.
