### ISSUE TITLE
What is the best way to test?

### ISSUE THREAD

**Issue by FunnerSoft** [playgameservices/play-games-plugin-for-unity#2985]
Hello,

Google Play Console is managing my app signing key.

Does this mean I have to upload and release my build to an Internal Testing Track within the Google Play Console, and then download that same build onto a test device .... in order to actually test my code?

Any help with this would be greatly appreciated.

**Comment by FunnerSoft** [comment]
If, like me, you came here because you are having issues with long iteration time while testing Google Play Games Services code .... 

My issue involved:

- Google Play Console controls my app signing key
- Unity's keystore is applied to my Unity builds
- Therefore I can't test Google Play Games Services code without fully uploading and publishing my builds through the Google Play Console

This thread is how I finally got that fixed.

https://github.com/playgameservices/play-games-plugin-for-unity/issues/2981

**Comment by CryptoCashCashoo** [comment]
> If, like me, you came here because you are having issues with long iteration time while testing Google Play Games Services code ....
> 
> My issue involved:
> 
> * Google Play Console controls my app signing key
> * Unity's keystore is applied to my Unity builds
> * Therefore I can't test Google Play Games Services code without fully uploading and publishing my builds through the Google Play Console
> 
> This thread is how I finally got that fixed.
> 
> #2981
The thread you linked is about connecting two Oauth keys (one in production and another for testing) but doesn't focus on the slow iteration build/test ( code + build + upload to google + uninstall latest + install beta + Test)

**Comment by FunnerSoft** [comment]
@CryptoCashCashoo , using the technique described I am able to do the following:

- Build from Unity
- Deploy to phone from Unity
- Don't upload to google
- Run game on phone and successfully log in and test Google Play Game Services

Personally, that significantly sped up my testing process.
