### ISSUE TITLE
What Scopes I needed to Add in OAuth Consent Screen?

### ISSUE THREAD

**Issue by Only4Gamers** [playgameservices/play-games-plugin-for-unity#2987]
I am using Google Play Games Plugin for Leaderboard in my Game and nothing else. What Scopes I needed to Add in OAuth Consent Screen Page (Update selected scopes)?
![Capture](https://user-images.githubusercontent.com/71321023/104410327-1b7fa800-558e-11eb-9116-fd81ec765b32.PNG)

**Comment by ozdemir08** [comment]
Just the **games_lite** scope must be enough.

**Comment by ozdemir08** [comment]
Closing this issue now. Feel free to reopen it for the further questions.
