### ISSUE TITLE
Users can't easily change accounts

### ISSUE THREAD

**Issue by FunnerSoft** [playgameservices/play-games-plugin-for-unity#2988]
Hi all,

I am having issues with users that have multiple Google Play Games Services (GPGS) accounts.

I am using the 'CanPromptAlways' sign in flow, however users are not getting any prompts. It is still doing an automatic sign in with one of their GPGS accounts. Below is a description of what my users are encountering:

1) User has 2 GPGS accounts. Referred to as Account A and Account B for now.
2) User launches my game, and my code calls authenticate with CanPromptAlways.
3) The user sees the 'oval dialog' at the top of the screen, letting them know they are signed in with Account A. The user is never prompted to pick an account or verify anything.
4) The user force closes the game.
5) User launches the Play Games app from Google on their device.
6) User makes the following settings changes within the Play Games app.
- Account A: Automatically sign in to supported games: off
- Account A: Sign in to games with this account: off
- Account B: Automatically sign in to supported games: on
- Account B: Sign in to games with this account: on
7) User launches my game again
8) User is still automatically signed in with Account A. Seeing the same 'oval dialog'.
9) Wait 24 hours
10) User launches my game again
11) User is now automatically signed in with Account B, but still is never prompted with any dialogs or choices to make.

Any help or insight into this would be greatly appreciated.

**Comment by ozdemir08** [comment]
Providing a sign-out button might help your users.

**Comment by FunnerSoft** [comment]
Hi ozdemir08,

I was under the impression that calling authenticate, again, but with CanPromptAlways was the way to offer a 'sign out and sign in with different account' solution.

However, I went digging more, after reading your suggestion, and found that there is an actual, proper SignOut call.

I will try that route. Thanks

**Comment by ozdemir08** [comment]
Great, give it a try and let us know if you need anything else :)
