### ISSUE TITLE
Assets\GooglePlayGames\ISocialPlatform\PlayGamesLocalUser.cs(24,57): error CS0535: 'PlayGamesLocalUser' does not implement interface member 'ILocalUser.Authenticate(Action<bool, string>)'

### ISSUE THREAD

**Issue by xiaokang69** [playgameservices/play-games-plugin-for-unity#2991]
Assets\GooglePlayGames\ISocialPlatform\PlayGamesLocalUser.cs(24,57): error CS0535: 'PlayGamesLocalUser' does not implement interface member 'ILocalUser.Authenticate(Action<bool, string>)'

**Comment by ozdemir08** [comment]
This must have been addressed in one of the latest releases. Check out the latest release and let us know if the issue persists.
