### ISSUE TITLE
Error building Player

### ISSUE THREAD

**Issue by Cpasjuste** [playgameservices/play-games-plugin-for-unity#3]
Hi,

i'm having a problem when building the Android player. I did follow the documentation (readme), have the latest sdk with latest play services library installed and did the "Android Setup". I was using my own GPG package before without any problem (didn't used unity social so wanted to update to have a clean code). I'm using latest unity (4.3.1f1). Here is the error message :

Error building Player: Win32Exception: ApplicationName='C:\Program Files (x86)\Java\jre7\bin\javac.exe', CommandLine='-bootclasspath "I:/dev/android-sdk/adt-bundle-windows-x86_64-20130917/sdk/platforms/android-19\android.jar" -d "I:\dev\unity3d\projects\Hidden\Temp\StagingArea\bin\classes" -source 1.6 -target 1.6 -encoding ascii "com\google\android\gms\R.java" "com\google\example\games\basegameutils\R.java" "com\google\example\games\mainlibproj\R.java" "com\malothetoad\hidden\R.java"', CurrentDirectory='I:\dev\unity3d\projects\Hidden\Temp\StagingArea\gen'

**Comment by ElALeKs242** [comment]
Right now i,m having problem when I try to build an APK
this is the message error
Win32Exception: ApplicationName='C:\Program Files\Unity\Hub\Editor\2019.4.3f1\Editor\Data\il2cpp/build/deploy/net471/il2cpp.exe', CommandLine='--convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARMv7" --configuration="Release" --outputpath="C:\Users\Emanuel\OneDrive\Escritorio\Exportación sin título\Photoshop\Sprites and atlas\JUEGOS UNITY\Marselo Pocket\Temp\StagingArea\assets\bin\Data\Native\armeabi-v7a\libil2cpp.so" --cachedirectory="C:\Users\Emanuel\OneDrive\Escritorio\Exportación sin título\Photoshop\Sprites and atlas\JUEGOS UNITY\Marselo Pocket\Assets\..\Library\il2cpp_android_armeabi-v7a/il2cpp_cache" --additional-include-directories="C:/Program Files/Unity/Hub/Editor/2019.4.3f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\bdwgc/include" --additional-include-directories="C:/Program Files/Unity/Hub/Editor/2019.4.3f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\libil2cpp/include" --tool-chain-path="C:/Program Files/Unity/Hub/Editor/2019.4.3f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK" --profiler-report --map-file-parser="C:/Program Files/Unity/Hub/Editor/2019.4.3f1/Editor/Data/Tools/MapFileParser/MapFileParser.exe" --directory="C:/Users/Emanuel/OneDrive/Escritorio/Exportación sin título/Photoshop/Sprites and atlas/JUEGOS UNITY/Marselo Pocket/Temp/StagingArea/assets/bin/Data/Managed" --generatedcppdir="C:/Users/Emanuel/OneDrive/Escritorio/Exportación sin título/Photoshop/Sprites and atlas/JUEGOS UNITY/Marselo Pocket/Temp/StagingArea/Il2Cpp/il2cppOutput" ', CurrentDirectory='C:\Users\Emanuel\OneDrive\Escritorio\Exportación sin título\Photoshop\Sprites and atlas\JUEGOS UNITY\Marselo Pocket\Temp\StagingArea\assets\bin\Data\Managed', Native error= La operación solicitada requiere elevación.

System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) (at <14e3453b740b4bd690e8d4e5a013a715>:0)
System.Diagnostics.Process.Start () (at <14e3453b740b4bd690e8d4e5a013a715>:0)
(wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
UnityEditor.Utils.Program.Start (System.EventHandler exitCallback) (at <bccb16a88ec4456dbf07978c418f407b>:0)
UnityEditor.Utils.Program.Start () (at <bccb16a88ec4456dbf07978c418f407b>:0)
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at <bccb16a88ec4456dbf07978c418f407b>:0)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at <bccb16a88ec4456dbf07978c418f407b>:0)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo, System.String workingDirectory) (at <bccb16a88ec4456dbf07978c418f407b>:0)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data, System.String outputDirectory, System.String workingDirectory, System.Boolean platformSupportsManagedDebugging) (at <bccb16a88ec4456dbf07978c418f407b>:0)
UnityEditorInternal.IL2CPPBuilder.Run () (at <bccb16a88ec4456dbf07978c418f407b>:0)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at <bccb16a88ec4456dbf07978c418f407b>:0)
UnityEditor.Android.PostProcessor.Tasks.RunIl2Cpp.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <d7067458867d436a825598eb5e44cdf0>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <d7067458867d436a825598eb5e44cdf0>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <d7067458867d436a825598eb5e44cdf0>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <d7067458867d436a825598eb5e44cdf0>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <bccb16a88ec4456dbf07978c418f407b>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
