### ISSUE TITLE
ios_platform_configuration.h errors

### ISSUE THREAD

**Issue by SillanStudios** [playgameservices/play-games-plugin-for-unity#301]
Hey guys, 
I'm really stuck with some errors for this header file. The errors are:
No. 1 - No type named 'unique_ptr' in namespace 'std'
Here's what it says
friend class GameServicesImpl;
  std::unique_ptr<IosPlatformConfigurationImpl> impl_;
};

No.2 - Expected member name or ';' after declarations specifiers.
This is where the error is:
#include <chrono>

I would appreciate your help so so much as I really need to add this plugin.
Thanks!

**Comment by claywilkinson** [comment]
This sounds like some sort of configuration issue in the build environment.  Stackoverflow would be a better site to ask for help, since this does not seem to be very specific to the play games plugin for unity.
