### ISSUE TITLE
Xcode Error

### ISSUE THREAD

**Issue by davidc02** [playgameservices/play-games-plugin-for-unity#302]
Hi,

I'm getting this error when using Google Play Games iOS SDK v3.1.1
use of undeclared identifier GPGModelLocalPlayerKey 
ApplicationModel deprecated

I read this https://github.com/playgameservices/play-games-plugin-for-unity/issues/271 but GPGAchievementControllerDelegate is not there, it's a fresh build so there were no previous files.

I tried 3.0 but then I get this error instead:
Apple Mach-O Linker Error
"OBJC_CLASS_$_GPGSAchOrLb Delegate",  referenced from objc-class-ref in GPGSInterface.o ... not found for architecture arm7.

Can't build, do you have any suggestions?

**Comment by mrggl** [comment]
I believe you're being affected by the issue I address here: 

https://github.com/playgameservices/play-games-plugin-for-unity/issues/320

**Comment by claywilkinson** [comment]
@davidc02  -  is there still an issue here, or did #320 address it?

**Comment by davidc02** [comment]
Deleting the entire iOS folder Google PlayGames/Platforms/iOS and adding a directive to address this was the only solution.
#elif UNITY_IPHONE
return new GooglePlayGames.BasicApi.DummyClient();
#else

I hope they make this more smooth in the future.
