### ISSUE TITLE
Achievements issue after updating Google Play Services

### ISSUE THREAD

**Issue by kordsl** [playgameservices/play-games-plugin-for-unity#303]
Hi.

I implemented the plugin and it worked fine.
After some time my google play services were updated from 6.1.88 036 to a later version (I've tried several and all of them had this issue, the latest one = 6.5.87 036 too).
The issue is when I call showAchievementsUI the game starts to load it and right after the background appears it goes to the android desktop. The application doesn't crash, it's still working and most of the times when I reopen the app - it has the achievements loaded.
I've tried downloading a random app with achievements made with this plugin and I encountered the same issue so it doesn't seem to be connected to my implementation.
I've tried removing cache, data, etc. from both gps and my game, it didn't help. Reinstalling them didn't help either.
Has anyone else encountered this issue?

Just to let you know - I tested this on Xiaomi redmi 1S.

EDIT:
It seems like it might be connected to this:
http://www.reddit.com/r/androiddev/comments/2nmhlz/google_play_services_6587_crashing_my_game/

**Comment by YashpalJavia** [comment]
I have a same problem. It happens only sometime. when I open Achievements app crash and cast following logs

W/dalvikvm(3807): threadid=1: thread exiting with uncaught exception (group=0x415abba8)
E/AndroidRuntime(3807): FATAL EXCEPTION: main
E/AndroidRuntime(3807): Process: com.google.android.gms.ui, PID: 3807
E/AndroidRuntime(3807): java.lang.NullPointerException
E/AndroidRuntime(3807): 	at com.google.android.play.a.a.a(SourceFile:128)
E/AndroidRuntime(3807): 	at com.google.android.gms.games.ui.cp.run(SourceFile:45)
E/AndroidRuntime(3807): 	at com.google.android.gms.games.ui.co.a(SourceFile:51)
E/AndroidRuntime(3807): 	at android.support.v7.widget.br.run(SourceFile:248)
E/AndroidRuntime(3807): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
E/AndroidRuntime(3807): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
E/AndroidRuntime(3807): 	at android.view.Choreographer.doFrame(Choreographer.java:543)
E/AndroidRuntime(3807): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
E/AndroidRuntime(3807): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(3807): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(3807): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(3807): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(3807): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(3807): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(3807): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(3807): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(3807): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(571):   Force finishing activity com.google.android.gms/.games.ui.client.achievements.ClientAchievementListActivity
W/ActivityManager(571):   Force finishing activity com.elluminati.tictactoe/biz.zimm.unity.bluetoothmediator.player.BluetoothUnityPlayerNativeActivity

Did you find any solution?

**Comment by ToddKerpelman** [comment]
Sorry for the delay, folks. We're looking into it; this probably an issue with GMSCore and not the Unity plugin itself. Tracking internally as 18899108

**Comment by ToddKerpelman** [comment]
Hey, all. Okay, I've confirmed this is an issue with GMSCore and the team has a fix that will go out with the next Play Services update. No action will be required on your end.

**Comment by tivee** [comment]
Thank you for the info, do you know when the new version of Play Services will be released?

**Comment by alexlung** [comment]
Same here. Mostly on first try after starting app oder install. This happens also after 4-6 times one after another call of ShowAchievementsUI(). 


02-13 10:50:28.164  21822-21822/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.google.android.gms.ui, PID: 21822
    java.lang.NullPointerException
            at com.google.android.play.a.a.a(SourceFile:128)
            at com.google.android.gms.games.ui.cp.run(SourceFile:45)
            at com.google.android.gms.games.ui.co.a(SourceFile:51)
            at android.support.v7.widget.br.run(SourceFile:248)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:543)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5105)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
            at dalvik.system.NativeStart.main(Native Method)
02-13 10:50:30.544     940-1263/? W/InputMethodManagerService﹕ Got RemoteException sending setActive(false) notification to pid 21698 uid 10190
02-13 10:50:30.554   1374-29535/? W/Binder﹕ Caught a RuntimeException from the binder stub implementation.
    java.lang.NullPointerException
            at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
            at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
            at android.os.Binder.execTransact(Binder.java:407)
            at dalvik.system.NativeStart.run(Native Method)

**Comment by kordsl** [comment]
It seems to be working in 6.7.74.
Thanks GPS team.

**Comment by gguuss** [comment]
Closing as fixed in update to GMS
