### ISSUE TITLE
Authentication flow stalls on white popup with infinite loader after 'Choose An Account' Unity 2020.3.6f1

### ISSUE THREAD

**Issue by cephaswilco** [playgameservices/play-games-plugin-for-unity#3036]
Authentication flow stalls on white popup with infinite loader after 'Choose An Account' Unity 2020.3.6f1.

![Screenshot_20210516-132516_Google Play services](https://user-images.githubusercontent.com/10524248/118406819-8d0a5880-b64b-11eb-93c1-b9d2f5c6a943.jpg)
![Screenshot_20210516-132526_Google Play services](https://user-images.githubusercontent.com/10524248/118406821-8ed41c00-b64b-11eb-9938-96fdda9cd404.jpg)

This all works when I don't have  .AddOauthScope("profile") or .RequestEmail() in the builder, but then I never receive a IdToken.
Others pointed out that I have to add a scope in order to receive a token.  

Anyways, when I finally add these calls I get to the Choose an Account page, and then when I choose an account I just end up at a white pop up with an infinite spinner.... I am attempting to use playgameservices with playfab. I think this is the last hurdle. I believe I have all of my credentials set up properly in playfab/google play console/ google cloud etc.

Any ideas why this is happening? Is this a version issue?

Thanks.

**Comment by RocksteadyDog** [comment]
Hello 
The same problem
It works for me only with auto login google play games, without auto login infinite loader after 'Choose An Account'

**Comment by cephaswilco** [comment]
Glad I am not the only one. I am 99.99% sure all my credentials are set properly...

**Comment by RocksteadyDog** [comment]
Hello again
I solved the problem
I think the problem is OAuth consent screen
I created a new project Play Games(not app) in Play Console
Next: Oauth consent screen -> Empty Logo -> Publis App -> AND DONE!

Worst experience ever)

![Screenshot_4](https://user-images.githubusercontent.com/29661837/118490593-4f3f2a00-b748-11eb-8444-317afaffa2dd.png)
![Screenshot_5](https://user-images.githubusercontent.com/29661837/118490601-5108ed80-b748-11eb-8d11-dc36e0b0ef45.png)

**Comment by cephaswilco** [comment]
Sorry, how do you get to the Oauth consent screen to see the app logo and also the App Doman etc.. Also are you making all of those empty or adding links to them? Thank you.

**Comment by cephaswilco** [comment]
Ok - Yep over the weekend I wasn't able to publish the game service because it wouldn't let me upload a log.  And now I can see you can also publish the OAuth consent. I went through multiple tutorials and never saw that step. Great find! will close this ticket  but hopefully other people are able to find it incase they have same issue.
