### ISSUE TITLE
Removing plugin files issues

### ISSUE THREAD

**Issue by horseone** [playgameservices/play-games-plugin-for-unity#304]
![removeissue](https://cloud.githubusercontent.com/assets/10104243/5330474/b1e10e98-7e39-11e4-8ab5-614847d28a5b.png)

I'm working with some co-workers by using svn.
And my co-workers' files are ordinarily worked on build.
but my files are automatically deleted and doesn't work.
I don't know the asset that -'asset' does not exist-
And I want a solution

**Comment by mrggl** [comment]
Mofoman is correct.

Thanks!
