### ISSUE TITLE
Upgrade Unity 2018 To 2021 And playgameplugin upgrade 1.2.95.0 To 1.2.162

### ISSUE THREAD

**Issue by jungsu-kim-archipin** [playgameservices/play-games-plugin-for-unity#3047]
I read upgrade txt( https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/UPGRADING.txt ).
However, I am getting an error due to changes in the code. 

`Assets\GooglePlayGames\Platforms\Native\NativeClient.cs(1138,48): error CS0246: The type or namespace name 'InvitationReceivedDelegate' could not be found (are you missing a using directive or an assembly reference?)

Assets\GooglePlayGames\Platforms\Native\NativeClient.cs(36,33): error CS0535: 'NativeClient' does not implement interface member 'IPlayGamesClient.Authenticate(bool, Action<SignInStatus>)'

Assets\GooglePlayGames\Platforms\Native\NativeClient.cs(36,33): error CS0535: 'NativeClient' does not implement interface member 'IPlayGamesClient.LoadFriends(int, bool, Action<LoadFriendsStatus>)'

Assets\GooglePlayGames\Platforms\Native\NativeClient.cs(36,33): error CS0535: 'NativeClient' does not implement interface member 'IPlayGamesClient.AskForLoadFriendsResolution(Action<UIStatus>)'

Assets\GooglePlayGames\Platforms\Native\NativeClient.cs(36,33): error CS0535: 'NativeClient' does not implement interface member 'IPlayGamesClient.GetLastLoadFriendsStatus()'

Assets\GooglePlayGames\Platforms\Native\NativeClient.cs(36,33): error CS0535: 'NativeClient' does not implement interface member 'IPlayGamesClient.ShowCompareProfileWithAlternativeNameHintsUI(string, string, string, Action<UIStatus>)'

Assets\GooglePlayGames\Platforms\Native\NativeClient.cs(36,33): error CS0535: 'NativeClient' does not implement interface member 'IPlayGamesClient.GetFriendsListVisibility(bool, Action<FriendsListVisibilityStatus>)'

Assets\GooglePlayGames\Platforms\Native\NativeClient.cs(36,33): error CS0535: 'NativeClient' does not implement interface member 'IPlayGamesClient.LoadMoreFriends(int, Action<LoadFriendsStatus>)'

Assets\GooglePlayGames\Platforms\Native\NativeClient.cs(36,33): error CS0535: 'NativeClient' does not implement interface member 'IPlayGamesClient.RequestPermissions(string[], Action<SignInStatus>)'

Assets\GooglePlayGames\Platforms\Native\NativeClient.cs(36,33): error CS0535: 'NativeClient' does not implement interface member 'IPlayGamesClient.HasPermissions(string[])'

Assets\GooglePlayGames\Platforms\Native\NativeClient.cs(61,26): error CS0104: 'Player' is an ambiguous reference between 'GooglePlayGames.BasicApi.Player' and 'GooglePlayGames.BasicApi.Multiplayer.Player'

Assets\GooglePlayGames\Platforms\Native\NativeClient.cs(62,31): error CS0104: 'Player' is an ambiguous reference between 'GooglePlayGames.BasicApi.Player' and 'GooglePlayGames.BasicApi.Multiplayer.Player'

`

Do you have a page with content that needs to be fixed with a previous update? Or can I get some advice?

**Comment by mgrogin** [comment]
Try deleting the GooglePlayGames folder first

**Comment by jungsu-kim-archipin** [comment]
Thank you, I delete GooglePlayGames folder and reinstalled it. But a new problem arose.

`Temp\gradleOut\launcher\src\main\AndroidManifest.xml:127:13-41 Error:
	Attribute meta-data#com.google.android.gms.games.unityVersion@value value=(\u0030.9.39a) from [:unityLibrary] AndroidManifest.xml:127:13-41
	is also present at [:unityLibrary:GooglePlayGamesManifest.plugin] AndroidManifest.xml:23:13-40 value=(\u0030.9.53).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:125:9-127:44 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#com.google.android.gms.games.unityVersion@value value=(\u0030.9.39a) from [:unityLibrary] AndroidManifest.xml:127:13-41
  	is also present at [:unityLibrary:GooglePlayGamesManifest.plugin] AndroidManifest.xml:23:13-40 value=(\u0030.9.53).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:125:9-127:44 to override.`

so, i removed that line from the AndroidManifest. ( "<meta-data android:name="com.google.android.gms.games.unityVersion" android:value="\u0030.9.39a" /> )

After that, the build started, but there was a problem that the application ended as soon as it was launched.
Please help me get out of this desperate situation

**Comment by jungsu-kim-archipin** [comment]
Thank you!
