### ISSUE TITLE
Unable to load library 'libgpg.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: unknown failure

### ISSUE THREAD

**Issue by sorab2142** [playgameservices/play-games-plugin-for-unity#305]
Still get this with the latest version of the plugin and a fully updated Play Services from SDK too.

**Comment by mrggl** [comment]
In my experience, this error is annoying, but benign - you should be able to ignore it.

**Comment by javiercornejo** [comment]
Benign? Really? It cause apps crashes!

**Comment by giangqaz** [comment]
i have same problem, but my apps not crashes!
