### ISSUE TITLE
[Action Required] Drive API requires updates to your code before Sep 13, 2021

### ISSUE THREAD

**Issue by TheOneVries** [playgameservices/play-games-plugin-for-unity#3055]
I just got an email from google with this title, with reference to a project that allegedly makes use of the Drive API. The only way it does that is via this plugin though (by storing save-games), so will this plugin be updated to reflect these required changes?

**Comment by TheOneVries** [comment]
Yes indeed, except I don't have any file sharing via the Drive API. Unfortunately that email doesn't specify how my app seems to be accessing the API, so I'm just guessing it is this plugin (which is the only code that does anything remotely Drive related)

**Comment by Firemaw** [comment]
I also received this email and use the savegames feature of Play Games Services. I am curious if this will affect my game, or if the plugin needs an update to keep it working. Reply from a dev would be appreciated.

**Comment by smile616** [comment]
Hi everyone, 

I can confirm that as long as:
* you enabled the Saved Games API in Play console https://developers.google.com/games/services/console/configuring#enabling_saved_games
* your game access the Drive only via the play-games-plugin-for-unity or using Play Games services SDK
no changes needed on your side and the published games will continue to work without any changes.

Sorry for the confusion with wording in the email in question.

**Comment by Firemaw** [comment]
Thank you @smile616 !

**Comment by dannykay1** [comment]
I got the same email.  Only thing that I could be using drive api for is the plugin for saved games.
