### ISSUE TITLE
[Question] Is user authentication required for the saving/loading features?

### ISSUE THREAD

**Issue by ChibiPhoenixGithub** [playgameservices/play-games-plugin-for-unity#3067]
Hello,

I could not find this mentioned in the docs (or I might've missed it), but just in case:
Does the user have to be authenticated to be able to make saves and load them?

Or will the feature work regardless of login status (assuming the user has the GooglePlayServices installed)?

**Comment by smile616** [comment]
yes, the user have to be authenticated.
