### ISSUE TITLE
PlayGamePlatform.GetUserId() issues

### ISSUE THREAD

**Issue by cosmicmosmic** [playgameservices/play-games-plugin-for-unity#3068]
Plugin Version : 0.10.12
Unity Version : 2019.4.26f

Hello, our game is currently in its 5th year of service and 
have been constantly using GPGS for Unity.

When GetUserId() method is called, we are getting two different results as below. 

Some IDs are returned in only numbered format such as "104183295622761800000" (We will call them Group A).
Other IDs are returned in letter 'g' + numbered format such as "g02000658613745100000" (We will call them Group B).

Starting mid-August (first reported in August 16th), we are getting increasing reports from Group A users that their
accounts have been missing or corrupted. 

Upon internal investigation, a portion of users that fell under Group A's ID format started to change in to 
Group B's ID format when GetUserId() method is called. 

We are urgently asking for a way to solve this issue or inquire whether migration would be an option.

Thank you for your assistance in advance.

**Comment by minka27** [comment]
Hello @cosmicmosmic, we are also experiencing this issue with Unity2020.3.15. 
Did you manage to figure something out in the meantime?

**Comment by cosmicmosmic** [comment]
@minka27 We managed unique users based on GetUserId().
So we are accessing DB and manually matching the IDs of customers who have problems.

**Comment by minka27** [comment]
@cosmicmosmic 
Thanks for the reply!
Did you find the root cause of the problem?
Did you maybe update AdMob or similar prior to problem starting to occur?

**Comment by cosmicmosmic** [comment]
@minka27 
Did you find the root cause of the problem? : I didn't find yet
Did you maybe update AdMob or similar prior to problem starting to occur? : no

**Comment by minka27** [comment]
Thank you!

**Comment by zhangjianshuai** [comment]
> Thank you!

we are also happening with 2017.4.30f1, Most of samsung mobile phone....

 Maybe the problem of Google?

**Comment by smile616** [comment]
Hi @cosmicmosmic, thank you for the report.

While format of the GetUserId() could change time to time, the result returned by GetUserId() should be stable for the given Play Games services profile (until user delete the profile or clean data for the game).


> Upon internal investigation, a portion of users that fell under Group A's ID format started to change in to
> Group B's ID format when GetUserId() method is called.

Could you confirm that the affected users didn't remove their Games service profile?
Were you able to reproduce the issue on your test/dev devices?

Thanks!

**Comment by minka27** [comment]
We have confirmed that users that had the old id (without prefix "g") started sending new id to our backend (with prefix "g"). Same problem as @cosmicmosmic.
A lot of users are complaining, with this change their progress is lost, we doubt that all of them removed GPG profiles.
We suspect it has to do with GooglePlayGames update, but not sure.

**Comment by smile616** [comment]
(internal issue id: b/198643920)

**Comment by smile616** [comment]
@minka27 , @cosmicmosmic, @zhangjianshuai,
We identified what's likely causing the issue on the Play Games services side. We are actively fixing the issue.
No changes is required on your side.
You should see reduction in number of the reports in few hours time. 
Current recommendation for the end users is to check internet connection and reboot their device after that (not guarantied that this would fix the issue).

**Comment by zhangjianshuai** [comment]
@smile616  thanks , Hope to solve it soon

**Comment by minka27** [comment]
Thank you @smile616 !
Please inform us when the possible fix is released so we can confirm it helped us with the issue.

**Comment by zhangjianshuai** [comment]
When will it be resolved,  More and more players are complaining about this problem,Please let us know if the problem is solved, thank you.

**Comment by minka27** [comment]
Hello @smile616
Do you maybe have any update on this issue?
Also, once it's resolved, will the affected users get back their old ids?
Thanks!

**Comment by smile616** [comment]
@minka27 / @zhangjianshuai 
We applied some mitigation to prevent further spread of the issue.
We are working on the fix that will recover the affected users. 
Yes,  the affected users will get back their old ids.

**Comment by bumiya** [comment]
Hello @smile616

Our game has been experiencing the same issue since the end of August.
Could you please let us know how the update is going?

And when the revised version is applied, it would also be nice if you could tell us what end users should do to restore the original ID data.

thank you.

**Comment by smile616** [comment]
@minka27 / @zhangjianshuai / @bumiya 

Fix have been pushed to the prod.

The affected end users should install the latest version of Play Games app available in the Play store, after that they will get the the original ID restored.

**Comment by bumiya** [comment]
Thank you for answer @smile616.

Then, can we guide end users as follows?
1. Install the latest version of "Play Games app".
2. If you access the game after installation, you will be connected with the original ID.

**Comment by minka27** [comment]
@smile616 Thank you very much!

**Comment by bumiya** [comment]
@smile616  Thank you!!
Users are sending emails saying that the problem has been resolved.

**Comment by smile616** [comment]
> Users are sending emails saying that the problem has been resolved.

Great to hear! Thank you for the confirmation.
