### ISSUE TITLE
Game never signs in

### ISSUE THREAD

**Issue by zdenda809** [playgameservices/play-games-plugin-for-unity#3071]
Hi, I did everything as said in the documentation, but in the game Google play services never signs in

**Comment by ShenaniganzStudio** [comment]
any luck with your project?  I can't get it to work either.

**Comment by ozdemir08** [comment]
I can suggest you to start with searching for `NOT CORRECTLY CONFIGURED` in your logs. It is the most common error. After that you can search for [closed configuration issues](https://github.com/playgameservices/play-games-plugin-for-unity/issues?q=is%3Aissue+label%3Aconfiguration+) and find similar problems and solutions. If it still does not work, then capture a bug report, tell us what you did and what you observed, then we will look into that.
