### ISSUE TITLE
Forced Google Drive API usage

### ISSUE THREAD

**Issue by Rugnor** [playgameservices/play-games-plugin-for-unity#3073]
Hello,

I've been using this GPG plugin for years, but after the last update it started failing to complete authentication.
I found this was causing it:

`
Unexpected response code 403 for https://www.googleapis.com/drive/v2beta/apps/self?prettyPrint=false&fields=id
StatusCode:403 Reason:[accessNotConfigured] Location:[]
`

After some research, I found enabling the Google Drive API in the Cloud project "solved" the problem and lets users in again.
The problem is there's no apparent reason why it started asking for this API after the update:
- Saved Games is disabled in the console
- the game includes a backup rules XML file excluding the whole game
- other games we have with similar setup and GPG not updated work fine without Drive API

(Tried 0.10.12 and 0.10.09, same result)

Thank you :)

**Comment by ozdemir08** [comment]
We have a similar issue [here](https://github.com/playgameservices/play-games-plugin-for-unity/issues/3063). This could be about our latest changes. No action needed from your side for now.

**Comment by ozdemir08** [comment]
The bug must be fixed by now. Let us know if the issue persists.
