### ISSUE TITLE
The new user interface of googleplay console has NO export resources.

### ISSUE THREAD

**Issue by eanjo7** [playgameservices/play-games-plugin-for-unity#3074]
Hi, I try to follow the tutorial but where can I find the script of Get resources?
![Screen Shot 2021-09-13 at 8 52 57 PM](https://user-images.githubusercontent.com/8068263/133087163-20d1c1f6-1bb4-447b-adf5-9de06fb7f1f9.png)

Hope you can help me where is the location of it on googleplay console so i can paste the code here:
![Screen Shot 2021-09-13 at 8 53 05 PM](https://user-images.githubusercontent.com/8068263/133087318-e95165b2-eab0-4bd8-9715-79f3e688ced7.png)

Hope someone can help me Im stock for 2 weeks

**Comment by RocksteadyDog** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/29661837/133100023-7846bcf8-ae24-49d4-aaed-c9c17d727622.png)

**Comment by eanjo7** [comment]
lol sorry didnt see that, thank you!
