### ISSUE TITLE
Sign in works via APK, but doesn't work via Google Play AAB

### ISSUE THREAD

**Issue by vladgalay** [playgameservices/play-games-plugin-for-unity#3078]
Hello, I encounter the following problem with login into Play Games - when I build the game as an APK and install it on my device, the login works, but when the game is distributed through Google Play via AAB (the AAB is built within Unity), the login doesn't work. The green rotating loading circle lasts about a second, and then login fails. What may be causing this issue? Unity version - 2018.4.36f1, plugin version - 0.9.62

**Comment by karliss** [comment]
Did you create credentials for each signing key used ? As described in https://developers.google.com/games/services/console/enabling#b_create_a_credential 

When using AAB in Google Play it creates final APKs using different signing key than the one you use locally. So you need to create second credentials using that. Fingerprint of the key used by  Play App Signing  can be found in Google Play console.

**Comment by vladgalay** [comment]
> Did you create credentials for each signing key used ? As described in https://developers.google.com/games/services/console/enabling#b_create_a_credential
> 
> When using AAB in Google Play it creates final APKs using different signing key than the one you use locally. So you need to create second credentials using that. Fingerprint of the key used by Play App Signing can be found in Google Play console.

Thank you! Creating new credentials with the App key solves the issue
