### ISSUE TITLE
Nearby Droids and Smoke Test doesn't work

### ISSUE THREAD

**Issue by federyuk91** [playgameservices/play-games-plugin-for-unity#3085]
Is nearby connection still supported?
I followed the entire readme, but found no way to get it to work.
In nearby droid sample the createRoom and JoinRoom functions are missing (script missing reference).
In smoke test there are no apparent errors, but no devices are detected, some help here?

**Comment by ozdemir08** [comment]
The nearby api is still supported. You may need to get some Android permissions for that. Please check out the logs. As this is not a widely used API, we do not actively look into that. 

We do our manual tests with Smoke Test. So everything must be working there. Nearby Droids was working as well, when I tried it a few months ago.
