### ISSUE TITLE
i want to hire someone to make custom leaderboard and achievment ?

### ISSUE THREAD

**Issue by stickylabdev** [playgameservices/play-games-plugin-for-unity#3089]
unity 2020 . i need help

**Comment by smahalgavaiya** [comment]
https://www.upwork.com/freelancers/~012f6500772cd5cb2b

**Comment by stickylabdev** [comment]
Are u sure that you can do it? Without playfab and other... Only play game
services

Pada tanggal Min, 14 Nov 2021 23.15, smahalgavaiya ***@***.***>
menulis:

**Comment by smahalgavaiya** [comment]
https://youtu.be/Cg8byoTopYE

Here is tutorial link even you can do it as well

**Comment by stickylabdev** [comment]
I might forget about.. What i mean is ui... Not only just leaderboarf
achievment..... Ineed custom ui of play  game services

Pada tanggal Sen, 15 Nov 2021 18.41, smahalgavaiya ***@***.***>
menulis:

**Comment by smahalgavaiya** [comment]
I can help you with coding and implementation part you need get your ui design with ui/ux and i will add them in project

**Comment by stickylabdev** [comment]
I can do it leaderboarf acivement.. I can not do the custom ui. The things
is.. I want to customize that boring default ui

Pada tanggal Sen, 15 Nov 2021 22.25, smahalgavaiya ***@***.***>
menulis:

**Comment by smahalgavaiya** [comment]
You need graphic designer/ ui artist for that

**Comment by stickylabdev** [comment]
itis not what i mean ,,,,,,,,,,imean ,,,,,,,,,,,,,,,,,,,,,,,custom default ,there is no tutorial about this

**Comment by stickylabdev** [comment]
not about ui design ,,its about the scripting of how to custom that default ui of playgame services

**Comment by stickylabdev** [comment]
You dont know what i mean

Pada tanggal Sen, 15 Nov 2021 23.44, smahalgavaiya ***@***.***>
menulis:

**Comment by stickylabdev** [comment]
I mean custom ui is part of te programming it self... Thats what i mean...
I don't mentiok about ui or design

Pada tanggal Sel, 16 Nov 2021 12.44, Muafakul Khoir ***@***.***>
menulis:

**Comment by smahalgavaiya** [comment]
if you have all buttons arts for custom UI is ready with you it's actually quite straightforward to add them on unity and sync with google leaderboard

**Comment by stickylabdev** [comment]
My purpose is to costumize this boring ui... So far I don't find any
tutorial about this

Pada tanggal Sel, 16 Nov 2021 13.43, smahalgavaiya ***@***.***>
menulis:

**Comment by stickylabdev** [comment]
https://www.google.com/search?q=play+game+service+leaderboard&client=ms-android-xiaomi-rvo2&prmd=nivx&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiDvenyhp30AhUUXSsKHWFIDVwQ_AUoAnoECAIQAg&biw=393&bih=737&dpr=2.75



Take a look at this image

Pada tanggal Sel, 16 Nov 2021 21.07, Muafakul Khoir ***@***.***>
menulis:

**Comment by smahalgavaiya** [comment]
https://stackoverflow.com/questions/44067850/google-play-game-services-leaderboard-with-custom-ui-using-unity3d-plugin-of-goo

**Comment by stickylabdev** [comment]
still so hard for me

**Comment by smahalgavaiya** [comment]
okay let's connect over discord for faster communication sanket.gamedev#7846
