### ISSUE TITLE
Error In LogCat - com.google.games.bridge.HelperFragment

### ISSUE THREAD

**Issue by AndrewCooper69** [playgameservices/play-games-plugin-for-unity#3092]
I am using CloudOnce v2.7.1.  When I run my project on an Android device, I get the following error in logcat: 

"*** [Play Games Plugin 0.10.10] 11-24-21 15:40:41 -05:00 ERROR: Exception launching token request: java.lang.ClassNotFoundException: com.google.games.bridge.HelperFragment"

The plugin doesn't log in to cloud services because of this error.  I have 3 questions:
1) Are you familiar with this error, and know any fixes?
2) Would updating my CloudOnce to V2.7.4 fix this, or updating my GPGS?
3) If yes, how would one install an updated package?  Do you just go to Import Package > Custom Package > CloudOnce V2.7.4.unitypackage > Add all files it suggests?  Do you have to remove the older 2.7.1 version somehow?  

Thank you!

**Comment by ozdemir08** [comment]
HelperFragment is a java class, which is a part of this plugin that talks with the Java SDK. As it is a part of this plugin, just importing this plugin into your project must be sufficient to have that class. The exception is `ClassNotFoundException`, so when building your project, it somehow gets stripped out of your build. 

The likely scenario is that `minify` is enabled in the project settings and you do not have custom proguard rules or are missing some important ones. Please take a look at [here](https://github.com/playgameservices/play-games-plugin-for-unity#decreasing-apk-size).

**Comment by AndrewCooper69** [comment]
That is incredibly helpful, thank you very much!  However, I did not have Minify active.  I tried to add a custom proguard file with the contents listed [here](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/scripts/proguard.txt), but unfortunately the issue still persists:

11-30 15:13:53.396 W Unity   : *** [Play Games Plugin 0.10.10] 11-30-21 15:13:53 -05:00 ERROR: Exception launching token request: java.lang.ClassNotFoundException: com.google.games.bridge.HelperFragment

Do I need to enable minify for the proguard file to work?  Do I need to add another element to the proguard file which is not listed in the link above?

Thank you!

**Comment by AndrewCooper69** [comment]
One more thing to note - when I try to build the Google Play Bundle version of the app (not .apk, but .aab) with Minify active, the build fails and says the following:

java.io.IOException:
java.lang.IllegalArgumentException: Can't find common super class of (com/google/android/gms/common/a) (with 4 known super classes) and (com/google/android/gms/common/e) (with 1 known super classes) See console for details.

It does not happen when I deselect Minify.

Perhaps the issue is that my version of Play Games Services does not match the proguard information listed in that link above?

Thank you for the help!

**Comment by ozdemir08** [comment]
> `keep class com.google.games.bridge.** { *; }`
See [line 16](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/scripts/proguard.txt#L16)

I would first go with trying out building the plugin as .apk and check if it works. Then if it works I would continue with whether you can build it as .aab . 

You should not need adding extra proguard rules actually. However, if your project also includes other android libraries, then the rules in that list would not be enough. The way proguard works is starting from the classes that match with the keep rules, it keeps all used classes and strips out the rest. So, if you need other libraries and are getting `ClassNotFound` or similar errors, then you can go ahead with adding a new rule for each missing class.

**Comment by AndrewCooper69** [comment]
Thank you for all your help.  When I build the .apk it does build but still get the same error in logcat, and it does not build the .aab if Minify is enabled.  

I am starting to think there will be no solution here, as I have added the proguard file with those lines, but still am getting the same error.  Perhaps it is a weird combination of the CloudOnce plugin and my version of Unity, or something like that.

If anyone is able to help me via Discord, or if it would help to post a video, let me know!  Thank you!

**Comment by haritonstefan** [comment]
Hi @AndrewCooper69 did you find a solution to your issue?

**Comment by AndrewCooper69** [comment]
> Hi @AndrewCooper69 did you find a solution to your issue?

I have not found a solution no.  If you have any ideas on how to help, I would appreciate it!

The game is currently released on the Google Play Store under the name [Rhythm Royale](https://play.google.com/store/apps/details?id=com.AreYouSeriousGamesInc.RhythmRoyale).  If you would like to check it out, you may be able to see the logcat output from the game itself if you have developer mode enabled.  We decided to switch the leaderboards to a scoreboard saved internally on a phone, but obviously a shared leaderboard would be preferable.

Andrew Cooper

**Comment by AndrewCooper69** [comment]
> Yep, that is exactly my problem and still searching for a solution.

Unfortunately I was never able to find a solution.  We ended up releasing the game and closing out development without Leaderboards.  It sucks, because we really wanted them in there, but no solution was found!

**Comment by aeaktepe** [comment]
Thank you Andrew, fortunately for me I just find a solution?

In my proguard file, below line was already there.
`-keep class com.google.games.bridge.** { *; }`

But apparently that was not enough, so in one of my tries I saw a post about adding below lines and it did work for me. So in case anyone sees this, they may try this solution.
```
-keep class com.google.games.** { *; }
-keep interface com.google.games.** { *; }
```

**Comment by RomainBitard** [comment]
I don't have proguard but unchecking minify worked for me. Which is a shame I want it to work with minify 😩

**Comment by danniboy1234** [comment]
Having the same issue, adding
 -keep class com.google.games.** { *; }
-keep interface com.google.games.** { *; }
has not worked for me, neither has removing minify options. Not sure what to do.

**Comment by cdr9042** [comment]
raziel619's solution was not suitable for me since it leads to other build errors related to many other 3rd party SDK. I'll copy it over here anyway for preservation purpose.

## Solution
To solve this, we need to tell the android build system to keep all of the classes needed by both GPG and GMA. This can be done by providing a custom proguard-user.txt file. First, the proguard-user.txt file in the Assets/Plugins/Android. Copy and paste the content below into this new file.
```
-dontwarn com.google.vr.ndk.base.DaydreamApi
-keep class com.facebook.** {
   *;
}
-keep class com.google.unity.** {
   *;
}
-keep public class com.google.android.gms.ads.**{
   public *;
}
-keep class com.google.android.gms.games.leaderboard.** { *; }
-keep class com.google.android.gms.games.snapshot.** { *; }
-keep class com.google.android.gms.games.achievement.** { *; }
-keep class com.google.android.gms.games.event.** { *; }
-keep class com.google.android.gms.games.stats.** { *; }
-keep class com.google.android.gms.games.video.** { *; }
-keep class com.google.android.gms.games.* { *; }
-keep class com.google.android.gms.common.api.ResultCallback { *; }
-keep class com.google.android.gms.signin.** { *; }
-keep class com.google.android.gms.dynamic.** { *; }
-keep class com.google.android.gms.dynamite.** { *; }
-keep class com.google.android.gms.tasks.** { *; }
-keep class com.google.android.gms.security.** { *; }
-keep class com.google.android.gms.base.** { *; }
-keep class com.google.android.gms.actions.** { *; }
-keep class com.google.games.bridge.** { *; }
-keep class com.google.android.gms.common.ConnectionResult { *; }
-keep class com.google.android.gms.common.GooglePlayServicesUtil { *; }
-keep class com.google.android.gms.common.api.** { *; }
-keep class com.google.android.gms.common.data.DataBufferUtils { *; }
-keep class com.google.android.gms.games.quest.** { *; }
-keep class com.google.android.gms.nearby.** { *; }
-keep public class com.google.ads.**{
   public *;
}
-keepattributes *Annotation*
-dontobfuscate
Next, enable Custom Gradle Properties Template and Custom Proguard File in Unity’s Player Settings as shown in the image below.
```

Ensure that unity is pointing to your newly created proguard text file. (Note the Custom Gradle Properties Template option may be unnecessary).

**Comment by cdr9042** [comment]
I got it working. The Select save UI displayed successfully.

Edit this file: Assets/GooglePlayGames/com.google.play.games/Editor/GooglePlayGamesPluginDependencies.xml
Change the line `<repository>Packages/com.google.play.games/Editor/m2repository</repository>` to:
`<repository>Assets/GooglePlayGames/com.google.play.games/Editor/m2repository</repository>`

Make EDM4U Resolve or Force resolve.

If the resolver worked correctly, there should be plugin files in `Assets/GeneratedLocalRepo/GooglePlayGames/com.google.play.games/Editor/m2repository/com/google/games/gpgs-plugin-support/0.11.01/gpgs-plugin-support-0.11.01.aar and gpgs-plugin-support-0.11.01.pom`

If resolver didn't work, try manually copying files from `Assets/GooglePlayGames/com.google.play.games/Editor/m2repository/com/google/games/gpgs-plugin-support/0.11.01` and rename .srcaar to .aar

The mainTemplate.gradle should have this line:
```
maven {
            url (unityProjectPath + "/Assets/GeneratedLocalRepo/GooglePlayGames/com.google.play.games/Editor/m2repository") // Assets/GooglePlayGames/com.google.play.games/Editor/GooglePlayGamesPluginDependencies.xml:11
        }
```

The file ProjectSettings\AndroidResolverDependencies.xml should have these lines:
```
<file>Assets/GeneratedLocalRepo/GooglePlayGames/com.google.play.games/Editor/m2repository/com/google/games/gpgs-plugin-support/0.11.01/gpgs-plugin-support-0.11.01.aar</file
<file>Assets/GeneratedLocalRepo/GooglePlayGames/com.google.play.games/Editor/m2repository/com/google/games/gpgs-plugin-support/0.11.01/gpgs-plugin-support-0.11.01.pom</file>
```

**Comment by vaibhavgpt-google** [comment]
It seems that the issue is resolve. As there are no follow ups, closing the issue.
Thanks

**Comment by cdr9042** [comment]
would be great if the project is updated to fix the issue so developers don't have to make a workaround to fix by themselves

**Comment by frazerbw** [comment]
Exact same issue, and with the looming November deadline to upgrade to SDK34, this is quite urgent.. tried many things. I'll report back if I have any luck.. but hopefully someone can help us soon.

**Comment by Jazz1122k** [comment]
i tried all the solutions mentioned above but still couldnt fix the issue. I can successfully build my apk with no errors but
leaderboard wont show up. I even tried with a blank project but ended up on the same error. I even tried changing and updating the unity version but still no help.

I can successfully login as you can see in the below log that successfully authenticated but not matter what i do this error wont go away, should i try using older google play plugin?

![WhatsApp Image 2024-10-22 at 3 48 35 PM](https://github.com/user-attachments/assets/cb64cb93-6918-45f1-8098-ef0562e9cb07)

if anyone has any intel on this please help

**Comment by AoiMinato** [comment]
I've been struggling with this issue for a very, very long time, but as described in [this issue](https://github.com/playgameservices/play-games-plugin-for-unity/issues/3249), changing the URL in "/Assets/Plugins/Android/settingsTemplate.gradle" to "/Assets/GeneratedLocalRepo/GooglePlayGames/Editor/m2repository" finally resolved the problem. It seems like I can sleep without nightmares tonight!

**Comment by Jazz1122k** [comment]
4 sleepless nights but changing the URL finally worked, thank you so much!!!!!!!

**Comment by DmitriyYukhanov** [comment]
For me, the solution was to enable the Android platform at the gpgs-plugin-support Plugin:
![image](https://github.com/user-attachments/assets/b4a4ba5b-f4ed-433b-ba3d-2a7abf6dd9ee)
![image](https://github.com/user-attachments/assets/66a406b4-190d-48a2-9adf-71a7aaad479f)

**Comment by amirkhavari99** [comment]
I see this error when I try to open the achievements UI in the game. For some reason, the classes are ripped out of the build and they are not available at runtime even though the build is successful.

**Comment by momentumrick** [comment]
Solution! 

With V2.0 I ran into this issue. I tried everything... and you know what the problem was? YOU KNOW WHAT THE PROBLEM WAS!!!!???? a stupid checkbox... The .aar that gets made is actually in the Assets\GeneratedLocalRepo\GooglePlayGames\com.google.play.games\Editor\m2repository\com\google\games\gpgs-plugin-support\2.0.0\gpgs-plugin-support-2.0.0.aar. that .aar for me didn't have android checked. Here is an image of what to check:

![Image](https://github.com/user-attachments/assets/9cf101b9-3630-4303-b9ac-fb199c754278)

**Comment by MiktatMertCento** [comment]
> Solution!
> 
> With V2.0 I ran into this issue. I tried everything... and you know what the problem was? YOU KNOW WHAT THE PROBLEM WAS!!!!???? a stupid checkbox... The .aar that gets made is actually in the Assets\GeneratedLocalRepo\GooglePlayGames\com.google.play.games\Editor\m2repository\com\google\games\gpgs-plugin-support\2.0.0\gpgs-plugin-support-2.0.0.aar. that .aar for me didn't have android checked. Here is an image of what to check:
> 
> ![Image](https://github.com/user-attachments/assets/9cf101b9-3630-4303-b9ac-fb199c754278)

You are so good man soooo goood! you saved my day!

**Comment by gravyday** [comment]
> changing the URL in "/Assets/Plugins/Android/settingsTemplate.gradle" to "/Assets/GeneratedLocalRepo/GooglePlayGames/Editor/m2repository" finally resolved the problem.

This worked for me (using Google Play v2.0) except the file path was "/Assets/GeneratedLocalRepo/GooglePlayGames/com.google.play.games/Editor/m2repository"

Here is a snippet from my (finally!) working settingsTemplate.gradle:

`        maven {
            url (unityProjectPath + "/Assets/GeneratedLocalRepo/GooglePlayGames/com.google.play.games/Editor/m2repository")
        }
`

**Comment by nitroy2k** [comment]
The issue is really problematc, for me it solved 2 things not sure which one worked with 2.1 



First proguard I had to update it to full 
`# ----------------------------
# Unity
# ----------------------------
-keep class com.unity.** { *; }

# ----------------------------
# Android Notifications
# ----------------------------
-keep class com.unity.androidnotifications.** { *; }
-keepclassmembers class com.unity.androidnotifications.** { *; }
-keepnames class com.unity.androidnotifications.** { *; }
-keepclassmembernames class com.unity.androidnotifications.** { *; }

# ----------------------------
# Google Play Games Services
# ----------------------------
-keep class com.google.games.bridge.** { *; }
-dontwarn com.google.games.bridge.**
-keep class com.google.games.** { *; }
-keep interface com.google.games.** { *; }

# Core Google Play Games and related services
-keep class com.google.android.gms.games.** { *; }
-keep class com.google.android.gms.auth.** { *; }
-keep class com.google.android.gms.signin.** { *; }
-keep class com.google.android.gms.dynamic.** { *; }
-keep class com.google.android.gms.dynamite.** { *; }
-keep class com.google.android.gms.tasks.** { *; }
-keep class com.google.android.gms.security.** { *; }
-keep class com.google.android.gms.base.** { *; }
-keep class com.google.android.gms.actions.** { *; }

# Specific GPGS modules
-keep class com.google.android.gms.games.PlayGames { *; }
-keep class com.google.android.gms.games.leaderboard.** { *; }
-keep class com.google.android.gms.games.snapshot.** { *; }
-keep class com.google.android.gms.games.achievement.** { *; }
-keep class com.google.android.gms.games.event.** { *; }
-keep class com.google.android.gms.games.stats.** { *; }
-keep class com.google.android.gms.games.video.** { *; }
-keep class com.google.android.gms.games.quest.** { *; }
-keep class com.google.android.gms.nearby.** { *; }

# Common Google Play API classes
-keep class com.google.android.gms.common.ConnectionResult { *; }
-keep class com.google.android.gms.common.GooglePlayServicesUtil { *; }
-keep class com.google.android.gms.common.api.** { *; }
-keep class com.google.android.gms.common.data.DataBufferUtils { *; }
-keep class com.google.android.gms.common.api.ResultCallback { *; }
`

Second cahnge of settingstemplate url for project
       maven { url (unityProjectPath + "/Assets/GeneratedLocalRepo/GooglePlayGames/com.google.play.games/Editor/m2repository") }

This finally resolved my build
I didn't have to thick Android in my case

**Comment by jimuskin** [comment]
> Solution!
> 
> With V2.0 I ran into this issue. I tried everything... and you know what the problem was? YOU KNOW WHAT THE PROBLEM WAS!!!!???? a stupid checkbox... The .aar that gets made is actually in the Assets\GeneratedLocalRepo\GooglePlayGames\com.google.play.games\Editor\m2repository\com\google\games\gpgs-plugin-support\2.0.0\gpgs-plugin-support-2.0.0.aar. that .aar for me didn't have android checked. Here is an image of what to check:
> 
> ![Image](https://github.com/user-attachments/assets/9cf101b9-3630-4303-b9ac-fb199c754278)

It seems that every time I build the project, the `.aar` file is being re-generated and reverting back to it's original state and ignoring my overrides.

I have attempted to disable everything related to auto-resolution under `Assets/External Dependency Manager/Android Resolver/Settings`,  including; `Enable Auto-Resolution`, `Enable Resolution On Build`, `Install Android Packages`, and `Explode AARs`:

<img width="418" height="193" alt="Image" src="https://github.com/user-attachments/assets/77d431ef-286b-4c59-b826-a9c2c4cc4ca8" />

[Full settings](https://github.com/user-attachments/assets/34d1d517-6065-4c11-91e5-771372ad35a7)

Does anyone know if there are any additional settings which need to be disabled to prevent the file from being overridden every build? 

**EDIT:**
After finding [this link](https://discussions.unity.com/t/build-failures-after-importing-gpgs-google-iap-and-google-ads-into-unity-2022-3-50f1/1534862/8), I was able to edit `Assets/GooglePlayGames/com.google.play.games/Editor/GooglePlayGamesPluginDependencies.xml` to below, and now it works:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<dependencies>
<!-- Internal library dependency generated at build time. 
    It also defines the transitive dependencies on play-services
-->
  <androidPackages>
    <androidPackage spec="com.google.games:gpgs-plugin-support:2.1.0">
      <repositories>
          <repository>Assets/GeneratedLocalRepo/GooglePlayGames/com.google.play.games/Editor/m2repository</repository>
          <repository>Assets/GooglePlayGames/com.google.play.games/Editor/m2repository</repository>
      </repositories>
    </androidPackage>
  </androidPackages>
</dependencies>

```

**Comment by lmymeow11** [comment]
> Solution!
> 
> With V2.0 I ran into this issue. I tried everything... and you know what the problem was? YOU KNOW WHAT THE PROBLEM WAS!!!!???? a stupid checkbox... The .aar that gets made is actually in the Assets\GeneratedLocalRepo\GooglePlayGames\com.google.play.games\Editor\m2repository\com\google\games\gpgs-plugin-support\2.0.0\gpgs-plugin-support-2.0.0.aar. that .aar for me didn't have android checked. Here is an image of what to check:
> 
> ![Image](https://github.com/user-attachments/assets/9cf101b9-3630-4303-b9ac-fb199c754278)

Only this solution works!
