### ISSUE TITLE
play-games-plugin-for-unity - build problems after plugin installation under different OS

### ISSUE THREAD

**Issue by rdcm** [playgameservices/play-games-plugin-for-unity#3093]
Hi,

Problem use-case looks like this:

- install the plugin on macOS
- setup plugin, building for android, code testing 
- commit project changes
- checkout git changes on Windows

ER: Successful android build on windows
AR: Broken android build on windows

Absolutely same behavior for win -> mac case.

In my mind for different platforms required different dependencies for a successful cross-compilation process. But explicit dependencies resolve not to solve a problem.  We get different errors on the build stage after git checkout:
- failed to setup GPG
- failed to force resolve GPG
- failed to android build with `Android SDK not found` error
- other different errors...

Full plugin reinstallation with full project reimport may solve the issue (but not always).

What is the correct way to manage GPG with git? At this point for me, it looks impossible.

**Comment by rdcm** [comment]
Something similar: https://github.com/playgameservices/play-games-plugin-for-unity/issues/2682

**Comment by ozdemir08** [comment]
It looks not particularly about this plugin, but the way Unity builds the project for Android and manage dependencies. Perhaps [External Dependency Manager](https://github.com/googlesamples/unity-jar-resolver) could be a better repo to address this. If you'd like to attract more people for discussion for the best practices for development in different OSes, feel free to reopen this or another issue with a more clear title.
