### ISSUE TITLE
I can not receive an email

### ISSUE THREAD

**Issue by ZICKFREED** [playgameservices/play-games-plugin-for-unity#3097]
I can not receive an email after the player is authorized, the line is empty

if you log in to the site, then I get by standard PHP methods all the data name, email, avatar

but what about Unity, I need to save the user data if he deleted the game, and after a while returned to it - so that all his progress is saved

**Comment by smile616** [comment]
Hi @ZICKFREED, can you use player id instead of the email as the user identifier?

**Comment by ZICKFREED** [comment]
> Hi @ZICKFREED, can you use player id instead of the email as the user identifier?

no, the identifier is also empty, I don't know how to solve this anymore

**Comment by ozdemir08** [comment]
PlayGamesPlatform.Instance.localUser.id must contain a non-null player id. You can also use our saved game api for this. Feel free to reopen it if you have more questions.

**Comment by ZICKFREED** [comment]
> PlayGamesPlatform.Instance.localUser.id must contain a non-null player id. You can also use our saved game api for this. Feel free to reopen it if you have more questions.

i was only able to get the username
