### ISSUE TITLE
GooglePlayGames.OurUtils.PlatformUtils.Supported

### ISSUE THREAD

**Issue by barissmutluuu** [playgameservices/play-games-plugin-for-unity#3106]
GooglePlayGames.OurUtils.PlatformUtils.Supported doesn't works well. Some devices has app returns false. that's my code:

#if UNITY_ANDROID

                if (GooglePlayGames.OurUtils.PlatformUtils.Supported)
                {
                    Debug.Log("PLAY SERVICE AVAILABLE !!!");

                    PlayGamesPlugin.Init();
                }

#endif

**Comment by ozdemir08** [comment]
Hi Baris, thanks for filing this issue. Could you take a look at the referenced issue and reopen this bug, if it does not solve it for you?

**Comment by barissmutluuu** [comment]
Hi Mehmet, I fixed my issue by adding this in AndroidManifest:

<queries>
   <package android:name="com.google.android.play.games" />
</queries>

 Some android devices needs this for using GooglePlayGames.OurUtils.PlatformUtils.Supported, maybe adding this in tutorial document helps some coders face the problem.

iyi çalışmalar trden selamlar :D
