### ISSUE TITLE
Save game not working!

### ISSUE THREAD

**Issue by Linux1230** [playgameservices/play-games-plugin-for-unity#3107]
Save game feature not working.
I have enabled cloud save on the configuration page.
I have configured the OAuth stuff in the cloud platform. I linked the application keys...
![image](https://user-images.githubusercontent.com/25261683/149190880-f3850ad9-72f6-400d-b868-fb28e3b3eeb1.png)
I have a green checkmark in the Google Play Games Configuration Menu
![image](https://user-images.githubusercontent.com/25261683/149188158-d4dc6585-94dd-4d21-b05b-43b3ac7dd5e0.png)
(Please ignore the language)

Google Play Games login is working correctly!

Code for initialization:
```
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
                                                        .EnableSavedGames()
                                                        .Build();
PlayGamesPlatform.InitializeInstance(config);
PlayGamesPlatform.DebugLogEnabled = true;
PlayGamesPlatform.Activate();
```

I have found this in my adb logcat:
Successfully found game: displayName [], applicationId [], packageName []
Game does not cloud save APIs. Skipping creation and connection to Internal Drive API

I deleted the application name from the log!

Code for Cloud save:
```
public override void SetGameProgress(GameProgress gameProgress, Action<SavingManagerResponseStatus> callback)
        {
            if (GPGSAuthentication.IsAuthenticated)
            {
                gameProgress.time = DateTime.Now;

                //local save without callback
                SetLocalValue(SavingManagerType.GameProgress, gameProgress.ToJson());

                PlayGamesPlatform.Instance.SavedGame.OpenWithAutomaticConflictResolution(fileName, DataSource.ReadCacheOrNetwork,
                    ConflictResolutionStrategy.UseLongestPlaytime, (status, metaData) => StartSaveGameProgress(status, metaData, gameProgress, callback));
            }
            else
                base.SetGameProgress(gameProgress, callback);
        }

        private void StartSaveGameProgress(SavedGameRequestStatus status, ISavedGameMetadata metaData, 
            GameProgress gameProgress, Action<SavingManagerResponseStatus> callback)
        {
            if (status == SavedGameRequestStatus.Success)
            {
                byte[] data = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(gameProgress));
                var updateMeta = new SavedGameMetadataUpdate.Builder().Build();
                PlayGamesPlatform.Instance.SavedGame.CommitUpdate(metaData, updateMeta, data, (status, metaData) => EndGameProgress(status, metaData, callback));
            }
            else
                callback(SavingManagerResponseStatus.NetworkError);
        }

        private void EndGameProgress(SavedGameRequestStatus status, ISavedGameMetadata metaData, Action<SavingManagerResponseStatus> callback)
        {
            if (status == SavedGameRequestStatus.Success)
                callback(SavingManagerResponseStatus.Success);
            else
                callback(SavingManagerResponseStatus.NetworkError);
        }
```

Can someone please help me figure out what went wrong. Why the cloud save not working? 
It would be helpful to know if my code is bad or I missed something while configuring the play game project.

Additional info:
Unity version: 2020.3.22f
Plugin version: 0.10.13

**Comment by Linux1230** [comment]
Hi, thanks for your help! Here is the the link for the [bug report](https://drive.google.com/file/d/16caCYUmyhuIhrXXvJyChGtvc0FkC7gYE/view?usp=sharing)

**Comment by Linux1230** [comment]
I tried the 0.10.14 version and cloud save still not works, I see the same error in my logcat.

**Comment by ozdemir08** [comment]
Thanks for the bug report. I can't see the relevant logs unfortunately. Could you capture another bug report right after you go through the same steps in your game? You can check if your logs have `SignInPerformer` or `SignInManager` first.

**Comment by Linux1230** [comment]
Hi, thanks for the quick reply, here is a new [bugreport](https://drive.google.com/file/d/1tecGky8ZHXWk7HlFrlJSW5Ly0XatMm5o/view?usp=sharing) in this I can see some lines with SignInPerformer-27 or SignInManagerV2.

**Comment by Linux1230** [comment]
Hi, @ozdemir08 are there any news about this bug?

**Comment by Xardas0327** [comment]
Hi @ozdemir08,
We would like to release our game, and this is only, which is missing.
Have you checked, which Linux1230 enclosed?

**Comment by Linux1230** [comment]
Hi @ozdemir08, we created a new project and tested our configuration there as well, and we figured it out we have an ```PlayGamesPlatform.Instance``` call before our initialization in an ```if``` statement ```if (PlayGamesPlatform.Instance != null)```. And we found out this will initialize the instance with the Default Configuration and can't be overwriten with our one. We figured this out via viewing the plugin source code. This problem was not clear for us in the documentation, i think you can maybe add this as a warning.

**Comment by olehkuznetsov** [comment]
From plugin sources:

public static void InitializeInstance(PlayGamesClientConfiguration configuration)
{
    if (sInstance == null || sInstance.mConfiguration != configuration)
    {
        sInstance = new PlayGamesPlatform(configuration);
        return;
    }

    GooglePlayGames.OurUtils.Logger.w(
        "PlayGamesPlatform already initialized. Ignoring this call.");
}

It seems if configuration is different it still should reinitialize. Can you check if you see in log "PlayGamesPlatform already initialized. Ignoring this call.", pease?

**Comment by Xardas0327** [comment]
In the 0.10.14:
``` public static PlayGamesPlatform Instance
        {
            get
            {
                if (sInstance == null)
                {
                    GooglePlayGames.OurUtils.Logger.d(
                        "Instance was not initialized, using default configuration.");
                    InitializeInstance(PlayGamesClientConfiguration.DefaultConfiguration);
                }

                return sInstance;
            }
        }
```

**Comment by Linux1230** [comment]
We used this code and ```PlayGamesPlatform.DebugLogEnabled = true;``` was never called so we can't even saw all logs. So we defenitly writed a wrong code. And first of all it would be great if I post the hole class where the init code is.
Sorry for wasting your time! And thanks for all the response we got!
