### ISSUE TITLE
Building Ios App too large!

### ISSUE THREAD

**Issue by ghostinov** [playgameservices/play-games-plugin-for-unity#311]
when i build the app for ios with play games plugin its too large, 327mbs, when i try to build it for ios it gets even larger to reach 500mbs ! can someone tell me what am i doing wrong ? ..
i guessed it was from the gpg.framework file.

**Comment by mrggl** [comment]
Our sample apps on iOS end up significantly below 100 megs as well (~60 mb).

The gpg.framework is large when it's downloaded for our site, but the linker throws away most of it during compilation.

Make sure you're doing a release build, not a debug build.

If you want to see where the .app size is coming from you can examine its contents via commandline etc.

**Comment by claywilkinson** [comment]
@ghostinov  - Its been a couple months since there were any comments on this thread.  Please re-open it if you still have questions.
