### ISSUE TITLE
How to get user Email in the latest plugin version?

### ISSUE THREAD

**Issue by hippogamesunity** [playgameservices/play-games-plugin-for-unity#3126]
PlayGamesLocalUser now misses Email property.

**Comment by Sardoneix** [comment]
Indeed, by applying README's SignIn step there is no more the PlayGamesClientConfiguration.Builder().RequestEmail() function.
Is this some kind of new GRPD compliance?

Thanks

**Comment by eantaev** [comment]
Hey, thanks for asking!
Indeed, in the new major update of the Unity plugin v11 there is no way to request emails or any other OAuth2.0 scopes.
Note that this functionality is still present in v10 branch - https://github.com/playgameservices/play-games-plugin-for-unity/tree/v10

**Comment by hippogamesunity** [comment]
@eantaev What is the reason this feature is removed? Do you plan to add this to v11? How long can we use v10?
