### ISSUE TITLE
How to sign-in user again if the user declined sign-in request on the app start in 0.11.01?

### ISSUE THREAD

**Issue by hippogamesunity** [playgameservices/play-games-plugin-for-unity#3127]
As mentioned here https://developers.google.com/games/services/android/signin
There should be `GamesSignInClient.signIn()` call.
![image](https://user-images.githubusercontent.com/7318172/159897559-49747984-aadf-4b41-a32d-d52a79437b9a.png)

**Comment by ozdemir08** [comment]
Hi @hippogamesunity thanks for checking out the new plugin. Please see [the sign-in section](https://github.com/playgameservices/play-games-plugin-for-unity#sign-in) of the documentation. You can use `PlayGamesPlatform.Instance.ManuallyAuthenticate` for the manual sign-in attempt.

**Comment by hippogamesunity** [comment]
Thanks for the info!
