### ISSUE TITLE
Need Signout Feature

### ISSUE THREAD

**Issue by AliasgarBohra** [playgameservices/play-games-plugin-for-unity#3138]
Why signout feature got removed?
Is there any way to sign out a user from play games now?

**Comment by olehkuznetsov** [comment]
Now users can sign out from any game using Play Games settings. 
They can be found in Play Games app or in phone settings->Google->Settings for Google apps->Play Games->Sign in accounts

**Comment by smile616** [comment]
@AliasgarBohra, user can sign-out using Play Games app or using Google settings in the Android system settings.

**Comment by maxkcy** [comment]
I believe Google requires an explicit sign-out option for the user that's built into the app.

**Comment by maxkcy** [comment]
> Now users can sign out from any game using Play Games settings. They can be found in Play Games app or in phone settings->Google->Settings for Google apps->Play Games->Sign in accounts

I believe Google requires an explicit sign-out option for the user that's built into the app.

**Comment by smile616** [comment]
@maxkcy could you please provide a reference where have you seen that? There is a possibility that the page haven't been updated according to the SDK changes. Thank you!
