### ISSUE TITLE
Can't Authenticate. ApplicationException: server_auth_code.

### ISSUE THREAD

**Issue by EXOUST** [playgameservices/play-games-plugin-for-unity#3164]
I have an experience with google auth and anything firebase (and google play) related. Its just something went wrong in this project. Maybe I'm confused where to write what sha. Firstly I just got SignInStatus.Canceled without any understandable error. But now I see the issue. My authCode is somehow null. 

So right here Im getting this authCode after calling PlayGamesPlatform.Instance.Authenticate
![image](https://user-images.githubusercontent.com/77357158/172107271-2da18ec2-87fb-4c2a-81cf-b704a29b051b.png)

And after downloading build from google play Im getting this error.
![Screenshot_7](https://user-images.githubusercontent.com/77357158/172107496-bda3d61b-25ea-4088-a7f5-287ea3696214.png)

Google play plugin initializing successfully:
![image](https://user-images.githubusercontent.com/77357158/172107668-2818f39c-ef08-4e57-8421-8872128a2dbf.png)

In firebase console I have providers registered:
![image](https://user-images.githubusercontent.com/77357158/172107742-9e910527-0f02-475c-af3e-ac6f023a76da.png)

My app signing certificates from google play:
![image](https://user-images.githubusercontent.com/77357158/172107955-dce12988-3bb1-4a22-92da-2f7a062ab6aa.png)

My certificates from keystore:
![image](https://user-images.githubusercontent.com/77357158/172108026-5d04a343-94ca-44c8-8273-e5d63d429139.png)

In console.cloud.google.com I have this:
![image](https://user-images.githubusercontent.com/77357158/172108105-cb4484fb-4d1a-4fcf-a30b-d59b693c5cc6.png)

And this configured in Firebase:
![image](https://user-images.githubusercontent.com/77357158/172108243-0cbdd206-d3f5-4e68-a993-7ac9c9c2aeaf.png)

- Unity version: 2022.1.1 - 2022.1.3
- Google Play Games Plugin for Unity version: v0.10.14 - v0.11.01

**Additional context**
Actually I even dont have an idea what could went wrong.

**Comment by EXOUST** [comment]
Update.

Now getting auth code but still the same error.
![image](https://user-images.githubusercontent.com/77357158/172226914-1b89ddf3-f351-4b86-ae05-15c31b291fc6.png)

I got this by disabling forceRefreshToken right here
![image](https://user-images.githubusercontent.com/77357158/172227097-54b88371-60ef-45da-853d-3beb7f3118f2.png)

Any ideas?

**Comment by smile616** [comment]
@EXOUST,

`PlayGamesPlatform.Instance.RequestServerSideAccess` is asynchronous, the lambda you passed into the method will be called sometime after the `RequestServerSideAccess` method call.

Note: the auth code returned by `RequestServerSideAccess`  is meant to be used on game server, see
https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/README.md#retrieving-server-authentication-codes

**Comment by EXOUST** [comment]
> RequestServerSideAccess is asynchronous

Got it. Maybe it is the issue. Thanks!


> RequestServerSideAccess is meant to be used on game server

How am I supposed to auth then? How to get creditional? Or I dont need to use Firebase Auth solution at all?

**Comment by smile616** [comment]
Sorry, I cannot help with the Firebase related questions. You can try to use the auth token from the RequestServerSideAccess, but I don't know if that would work/wouldn't work.

**Comment by EXOUST** [comment]
I just need to know how to get Player ID from Google Play and make sure it wont change after relogin/reinstall/deleting data.
