### ISSUE TITLE
Can't login to the google play games when using .RequestIdToken() with PlayGamesClientConfiguration

### ISSUE THREAD

**Issue by APTEM591** [playgameservices/play-games-plugin-for-unity#3172]
**Describe the bug**
Authentication fails when i add .RequestIdToken to the PlayGamesClientConfiguration. Logs return an error "authentication failed - developer error".

**To Reproduce**
```
var config = new PlayGamesClientConfiguration.Builder()
                .RequestEmail()
                // this line causes fail: .RequestIdToken() 
                .Build();

            PlayGamesPlatform.InitializeInstance(config);
            PlayGamesPlatform.DebugLogEnabled = true;
            PlayGamesPlatform.Activate();
            Social.localUser.Authenticate(AuthResult);
```

**Versions**
- Unity version: 2021.3.4f
- Google Play Games Plugin for Unity version: 0.10.14

**Comment by EAdemov** [comment]
Having the same issue. Any suggestions?

**Comment by APTEM591** [comment]
> Having the same issue. Any suggestions?

Already fixed. Forgot about this issue.
Solution: Adding **Web Application**  (Not Android!) client id in the console cloud credentials.

**Comment by EAdemov** [comment]
Worked! Thanks a lot!

**Comment by PokerNinja** [comment]
I'm lost

> > Having the same issue. Any suggestions?
> 
> Already fixed. Forgot about this issue. Solution: Adding **Web Application** (Not Android!) client id in the console cloud credentials.

I can't understand in which console

**Comment by PokerNinja** [comment]
> I'm lost
> 
> > > Having the same issue. Any suggestions?
> > 
> > 
> > Already fixed. Forgot about this issue. Solution: Adding **Web Application** (Not Android!) client id in the console cloud credentials.
> 
> I can't understand in which console

Ok in console cloud google. Make sense. Thank you!
