### ISSUE TITLE
Plugins collide on Unity 5

### ISSUE THREAD

**Issue by friendlymonster** [playgameservices/play-games-plugin-for-unity#318]
When trying to build with Unity 5 (5.0.0b18) I get an error with plugins colliding.

"Found plugins with same names and architectures, Assets/Plugins/Android/libs/armeabi-v7a/libgpg.so (ARMv7) and Assets/Plugins/Android/libs/armeabi/libgpg.so (ARMv7). Assign different architectures or delete the duplicate.
UnityEditor.AndroidPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at C:/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEditor.HostView:OnGUI()"

Is this a Unity issue or an issue with this plugin?

**Comment by claywilkinson** [comment]
I'd vote for unity 5 issue - did you ask on the Unity site also?

**Comment by gguuss** [comment]
From the Project Tab -> Libs folder, remove one of the `arm-eabi` libs and it will build.

![screen shot 2015-02-04 at 3 54 28 pm](https://cloud.githubusercontent.com/assets/3494394/6052417/85cc5778-ac87-11e4-97d5-68ab39c94436.png)

**Comment by Eomono** [comment]
I got this issue too. Is removing arm-eabi safe?

**Comment by claywilkinson** [comment]
yes - I believe so.  Unity actually requires ARMv7 (http://unity3d.com/unity/system-requirements).  We'll update the plugin shortly with armeabi removed.

**Comment by Eomono** [comment]
Awesome. Thank you!

**Comment by claywilkinson** [comment]
Fixed in Version 0.9.15

**Comment by wahengchang** [comment]
fix
