### ISSUE TITLE
No response when authenticate

### ISSUE THREAD

**Issue by PokerNinja** [playgameservices/play-games-plugin-for-unity#3196]
Hi.
Trying to authenticate with version 11.01 and 10.14.
When apply this:

"PlayGamesPlatform.Activate();
    Social.localUser.Authenticate(ProcessAuthentication);"

nothing is happened when check it over my phone.

What might be the problem?

Ty

**Comment by warrenjayv** [comment]
this code doesn't work for me either, because for some reason this function requires an _Action<bool>_ delegate. 

https://docs.unity3d.com/ScriptReference/SocialPlatforms.ILocalUser.Authenticate.html

**Comment by warrenjayv** [comment]
this might work
https://github.com/playgameservices/play-games-plugin-for-unity/issues/2730#issuecomment-1175161463

**Comment by warrenjayv** [comment]
11.01 didn't work with mine. testing 10.14.  the syntax is different for 10.14 however and requires additional lines. see readme file:
```csharp
    using GooglePlayGames;
    using GooglePlayGames.BasicApi;
    using UnityEngine.SocialPlatforms;

    PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
        // enables saving game progress.
        .EnableSavedGames()
        // requests the email address of the player be available.
        // Will bring up a prompt for consent.
        .RequestEmail()
        // requests a server auth code be generated so it can be passed to an
        //  associated back end server application and exchanged for an OAuth token.
        .RequestServerAuthCode(false)
        // requests an ID token be generated.  This OAuth token can be used to
        //  identify the player to other services such as Firebase.
        .RequestIdToken()
        .Build();

    PlayGamesPlatform.InitializeInstance(config);
    // recommended for debugging:
    PlayGamesPlatform.DebugLogEnabled = true;
    // Activate the Google Play Games platform
    PlayGamesPlatform.Activate();
```

**Comment by poorva-google** [comment]
There are major differences between v1(10.14) and v2(11.01) plugin. Hence the implementation is also different. Please go through the documentation carefully - https://developer.android.com/games/engines/unity/build-in-unity and implement all the steps. We are closing this now, feel free to reopen if issue persists.
