### ISSUE TITLE
Failing to Build on Xcode 

### ISSUE THREAD

**Issue by davidc02** [playgameservices/play-games-plugin-for-unity#320]
I'm running into this issue when trying to Build in Xcode:
/Libraries/GPGSAchOrLbDelegate.h:19:9: 'GooglePlayGames/GooglePlayGames.h' file not found

I tried both solutions suggested here https://github.com/playgameservices/play-games-plugin-for-unity/issues/241#issuecomment-58402398 but that didn't work, instead it created this issue:

clang: error: no such file or directory: '/Users/3davenue/Documents/Builds/Nanomites/Libraries/GPGSAchOrLbDelegate.m'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

What should I do? Thanks for your help.

**Comment by davidc02** [comment]
Well we ended up removing everything Google Play Game Services related on the iOS build, and rolling back the plugin version so Android would work.

Google Ads worked. We'll have to maintain a separate branch for this.

**Comment by mrggl** [comment]
Were you still seeing the same error?

The file in your error "GPGSAchOrLbDelegate.h" was deleting from the unity plugin in the 0.9.10 release.

I suspect that you have stale files hanging around in your Assets/Plugins/iOS directory, which are being reimported every time you generate the xcode project. The only play games related files that should be there are GPGSAppController.{h|cc} - delete everything else beginning with GPGS and it should work.

**Comment by davidc02** [comment]
Yes I was.

Deleting GPGSAchOrLbDelegate from the XCode project did not solve the issue.

**Comment by mrggl** [comment]
I'm not referring to your xcode project, I'm referring to your unity project - the contents of Assets/Plugins/iOS are copied every time you regenerate the xcode project via unity build.

You can also just do a file search for GPGSAchOrLbDelegate.h - that should turn up where the file is coming from.

**Comment by davidc02** [comment]
Well, we deleted the entire thing, so sadly I can't test it anymore. Hope this issue helps someone, but right but it seems like GPGS has a lot to work on. They should work more closely with the Unity guys to make this much more smooth.

Or at least try to have stuff well organized on their site, I mean, there is documentation discrepacy between languages, version upgrades seem to mess things up, it wasn't a smooth process for us.

**Comment by erikblue88** [comment]
Hi, somebody have a solution for the gpg/ios_support.h file not found?, Can anybody help me please?

**Comment by ZenithCode** [comment]
Make a fresh build with Unity (Replace) and follow the instructions in here: https://github.com/playgameservices/play-games-plugin-for-unity 

Look for 'Building for iOS'.

Make sure you add all the frameworks, bundles and add the ObjC.

When you build from Unity use 'Append' not 'Replace' as you'd have to do all of this from scratch.

**Comment by erikblue88** [comment]
Thank you for the response.

I did the steps as it, i make sure the target was 7.0 or above and the error continues.

I have a question, the framework available to downlod is called GooglePlayGame.framework, I replace tha by gpg.framework, is this correct? or the gpg.framework is other an where can i download it?

**Comment by ToddKerpelman** [comment]
Are you saying you're renaming the `GooglePlayGames.framework` to `gpg.framework`? If so, that would definitely be the source of the problem. Although, to be fair, it's a bit confusing.

`GooglePlayGames.framework` is part of the Objective-C iOS library. The plug-in used to use this library, but now it no longer does.

`gpg.framework` is part of the C++ library. This is the one you should be downloading, and you can find the frameworks as part of the "ios" folder in the zip file you download. It's on the [downloads page](https://developers.google.com/games/services/downloads/) as the last entry. It's labeled as "Play Games C++ SDK Version 1.3"

**Comment by erikblue88** [comment]
Oh, you are right!

I had not downloaded that framework, now the project run!

Thank you very much guys.
