### ISSUE TITLE
Not working link to the proguard file in the README.md

### ISSUE THREAD

**Issue by 256p** [playgameservices/play-games-plugin-for-unity#3208]
In README.md in Play Games Sevices Proguard configuration (https://github.com/playgameservices/play-games-plugin-for-unity#play-games-services-proguard-configuration) link to the Proguard file doesn't exist anymore (https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/scripts/proguard.txt

**Expected behavior**
Working link

**Observed behavior**
404

**Comment by olehkuznetsov** [comment]
Fixed. Thank you.
