### ISSUE TITLE
how to know if leaderboard ui or achivemenet closed ?

### ISSUE THREAD

**Issue by stickylab** [playgameservices/play-games-plugin-for-unity#3213]
how

**Comment by smile616** [comment]
you call startActivityForResult first (for example, [startActivityForResult(android.content.Intent, int)]( https://developer.android.com/reference/android/app/Activity#startActivityForResult(android.content.Intent,%20int)))
then you wait until onActivityResult was called (see [onActivityResult](https://developer.android.com/reference/android/app/Activity#onActivityResult(int,%20int,%20android.content.Intent))). 

The moment when onActivityResult is the moment you can use as indication that the leaderboard ui or achievement was closed.
