### ISSUE TITLE
ClassNotFoundException: com.google.android.gms.games.PlayGames

### ISSUE THREAD

**Issue by pajgla** [playgameservices/play-games-plugin-for-unity#3222]
Hi,
2 weeks ago my game and google play services were working fine. I think all went down when I implemented Ironsource plugin. Everytime I open my game on my phone, I get this error:

Error Unity AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.games.PlayGames

![image](https://user-images.githubusercontent.com/3383181/219539043-e3772357-9558-45d4-868e-ee6e38f0f698.png)

**Versions**
- Unity version: 2021.3.18f1
- Google Play Games Plugin for Unity version: 11.01

I've tried various fixes from around the web but nothing helped me.

**Comment by rohitvishwakarma1819** [comment]
@pajgla Did you find the solution ?

**Comment by pajgla** [comment]
Hi @rohitvishwakarma1819 

I did not, kinda. I deleted google play services package from my project, resolved dependencies, reimported the package, resolved dependencies, then I got an error, force resolved the dependencies and I it worked after that. Not sure if that fixed the issue but the important part is that it works now

**Comment by rohitvishwakarma1819** [comment]
@pajgla 
This helped me 
https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/UPGRADING.txt

**Comment by EdgarGomez** [comment]
Hi guys, sorry to come back here but I'm kind of desperate. I've opened this as a bug https://github.com/playgameservices/play-games-plugin-for-unity/issues/3269 I tried everything and the error still persists. Any help is appreciated
