### ISSUE TITLE
GPG 6.5 support

### ISSUE THREAD

**Issue by realworld666** [playgameservices/play-games-plugin-for-unity#323]
We're having some problems with the DEX size. Is there a way we can do modify the gradle file for play-games-plugin-for-unity to only include the libraries we need in our game and reduce the number of functions referenced? http://android-developers.blogspot.it/2014/12/google-play-services-and-dex-method.html

**Comment by mrggl** [comment]
The Unity plugin contains almost no code that impacts the DEV size of your game (though it relies on the android support library and google API client). 

Generic advice for dealing with DEX size would be to look at Proguard (though pro-guarding the libraries I referenced above will break the plugin, which expects unmangled symbols).

We'll try to see if there's anything else that can be done too.

**Comment by realworld666** [comment]
Yeah it's the Android libraries not the plugin itself but the methods suggested in the link in the OP can't be used with the plugin and Unity as things stand. Proguard isn't an option as far as I can tell. This is a major issue for our title.

**Comment by claywilkinson** [comment]
There is a thread on Unity's site that might be more relevant. http://answers.unity3d.com/questions/153065/file-size-is-far-too-big.html
I'd suggest looking there and maybe even posing this question there (or http://stackoverflow.com) since it will hit a wider audience.

**Comment by realworld666** [comment]
This has nothing to do with APK filesize. Its regarding the amount of methods used by 3rd party plugins such as this one. My link in the original post explains the problem and what Google have done about it but its not something I can do with this version of the plugin

**Comment by samtstern** [comment]
Looking into this.

**Comment by mcraiha** [comment]
Any news? Adding this plugin to our game took the number to over 75k, and since it seems Unity doesn't support multidex, we cannot really continue our work with this until there is some kind of solution.

**Comment by samtstern** [comment]
@mcraiha unfortunately the way the project builds now it does not use the gradle build system, so we can't use the split client aar's as dependencies.  We are brainstorming a way to get there, but it may be more under Unity's control than ours.

**Comment by tyrmullen** [comment]
Referencing that article initially linked to, I believe the specific "splits" that you'd need from the Android libraries for GPGS to work would be:
base, games, nearby (this one's new and only used in the very latest plug-in version), drive, and appstate.

If you just take those individual jars and mash them together to get a (much thinner) Google Play Services jar which you can replace your current "google-play-services.jar" with, I would imagine that could solve your problem (or at least move the dex size a good step in the right direction).  I have not yet tried this out myself on Unity though.

**Comment by tyrmullen** [comment]
Just to add to my previous comment, if you don't want to mess with building Android libraries (and are only using the google-play-services.jar for the Unity plug-in), you can actually just take the .jar file itself and cut out a bunch of the unused class folders.

I have a more detailed response with a minimal (I believe) list of folders to keep: https://github.com/playgameservices/play-games-plugin-for-unity/issues/508

This should help alleviate the dex-limit issue while waiting for a more permanent solution.

**Comment by mcraiha** [comment]
Is there any static analysis tool for figuring out the unneeded parts? I would like to future proof the process since it seems that Google Play services is getting bigger and bigger. (It would also help with android-support-v4)

**Comment by claywilkinson** [comment]
The plugin has been updated in version 0.9.27 to use the aar libraries vs. the client lib project. This will result in much smaller apk file sizes and a substantial reduction in the number of dex entries.
