### ISSUE TITLE
iOS Sign/in callback not working

### ISSUE THREAD

**Issue by ShikiGami** [playgameservices/play-games-plugin-for-unity#324]
I've been trying to figure out what's going on with the plug in, and why I cannot sign in on an IOS device, and finally I know why.

When I try to sign in there is absolutely no callback at all after I accept on safari. It just returns to the application, and then after a while it just drops to the Social.Active.localUser.Authenticate((bool success) => { when success is false.

The reason is that all the overwrites at GPGSAppController.m are not called at all never. The login is using the standard application:(UIApplication *)application openURL:(NSURL *)url method.

I've been trying for a while now, but I just don't understand why GPGSAppController.m is never called.

**Comment by mrggl** [comment]
What version of the plugin are you using?

I would make that your app is appropriately configured per https://developers.google.com/+/mobile/ios/getting-started#step_3_add_a_url_type

This should be automatically configured by the plugin, but there might be something clobbering the correct behavior.

**Comment by ShikiGami** [comment]
The application is properly configured. It does kind of work, it goes to the authentication page and comes back, but after it comes back there is no callback on the application.

I'm using version 0.9.10.

**Comment by mrggl** [comment]
It's possible some other code in your project is swallowing the callback - I would check to see if there are any places that this could be happening.
