### ISSUE TITLE
Signing in, but not getting Achievement or Leaderboard UIs

### ISSUE THREAD

**Issue by Otawo** [playgameservices/play-games-plugin-for-unity#325]
I was able to log in and get the Achievement and Leaderboard UIs to display properly last week in my game, however since Monday I have been unable to get them to load up in the game I am working on. I have the latest version of Unity, all the Android SDK options installed and updated according to the SDK Manager, and I have tried calling the UIs both with and without the Active keyword. We are able to log into Google Play Game Services still, and the game is currently Published as a Beta test. It was working before we published the Beta test, however we felt that might have been one of the issues causing conflicts. I and my boss are also logged into accounts that are flagged as testers, and nothing was changed which should have affected this. We are using uUI so we can't step back to 4.5.x and I just downloaded 4.6.1 to see if that would fix the issue, it did not.

**Comment by claywilkinson** [comment]
@Otawo  - did you resolve your issue?  If not, can you post what you are seeing in the log during this time?  Usually there are messages that give a good indication of what is going on.

**Comment by Otawo** [comment]
I did fix the issue, however I am not sure exactly what fixed it.
