### ISSUE TITLE
I write check saved game is exist code but it's print NullReferenceException

### ISSUE THREAD

**Issue by hwibaek** [playgameservices/play-games-plugin-for-unity#3253]
private bool IsSavedGameHasExist(string fileName)
    {
        bool isSaving = false;
        SavedGame.OpenWithAutomaticConflictResolution(fileName, DataSource.ReadCacheOrNetwork,
            ConflictResolutionStrategy.UseLongestPlaytime,
            (status, metadata) =>
            {
                if (status == SavedGameRequestStatus.Success)
                {
                    Debug.Log(metadata == null ? "No exist!" : "Exist!");
                    isSaving = metadata != null;
                }
                else
                {
                    Debug.Log("Fail to check saved game has exist!");
                }
            });
        return isSaving;
    }

i wrote this code and calling it. but this code print NullReferenceException!

**Comment by smile616** [comment]
@hwibaek , could you provide the stack trace for the NullReferenceException?

**Comment by hwibaek** [comment]
@smile616 here is stack trace.

  at GPGSBinder.IsSavedGameHasExist (System.String fileName) [0x0000d] in C:\Projects\Unity_Projects\NumCombination\Assets\GPGSBinder.cs:41 
UnityEngine.Debug:LogError (object)
GPGSBinder:IsSavedGameHasExist (string) (at Assets/GPGSBinder.cs:58)
GPGSBinder:LoadCloud (string,System.Action`2<bool, string>) (at Assets/GPGSBinder.cs:85)
Lobby.LobbyManager:Start () (at Assets/scripts/Lobby/LobbyManager.cs:22)

and LobbyManager called LoadCloud function at Start(), LoadCloud function called IsSavedGameHasExist

**Comment by smile616** [comment]
what's on line 41 in GPGSBinder.cs? If it is `Debug.Log`, could you comment all calls to `Debug.Log` in the file and run again?

**Comment by smile616** [comment]
I think I got what's the main issue here:

SavedGame.OpenWithAutomaticConflictResolution will perform work asynchronously. So in the following code: 

```
SavedGame.OpenWithAutomaticConflictResolution(fileName, DataSource.ReadCacheOrNetwork,
                ConflictResolutionStrategy.UseLongestPlaytime,
                (status, metadata) =>
                {
                    isSaving = metadata != null;
                });
```

the part `isSaving = metadata != null;` will be called sometimes after SavedGame.OpenWithAutomaticConflictResolution method call competed.

To refactor the code I'd suggest you read the following article at https://developer.android.com/games/pgs/unity/saved-games
