### ISSUE TITLE
Not always receiving invitation message

### ISSUE THREAD

**Issue by ZenithCode** [playgameservices/play-games-plugin-for-unity#326]
I am having a problem when sending out invitations to G+ friends.  My current game supports 4 players in total.  When I send out 3 invitations, more often than not only 2 people out of these 3 get the invitations.  The order is not consistent so 1 device might get it on my first attempt but does not receive it the second time round.

Is anyone else having these issues?
Is there anything I can do to fix this?

**Comment by mrggl** [comment]
Looks like the question is getting some traction on SO. Closing this issue to centralize discussion.

**Comment by ZenithCode** [comment]
Can we please re-open this here as support is needed from you guys - no one from SO can help with this problem?  Thanks

**Comment by claywilkinson** [comment]
re-opening, tracking internally as 19138744

**Comment by claywilkinson** [comment]
@ZenithCode  - I think this was a problem on the server side, can you confirm that it is working now?

**Comment by ZenithCode** [comment]
@claywilkinson - I can get invitations on Android all the time now :-)  

But still can't get any invitations on iOS. :-(

Is this the same problem or do you want me to open a separate ticket specifically for iOS?

**Comment by claywilkinson** [comment]
Thanks for the update!  Let me pass along that there still is an issue on iOS.

**Comment by ZenithCode** [comment]
Thanks @claywilkinson

**Comment by ZenithCode** [comment]
Problem is still there after upgrading 0.9.15

**Comment by claywilkinson** [comment]
This should be fixed in the current version 0.9.20 of the plugin and the latest C++ SDK (version 1.4.1).

**Comment by claywilkinson** [comment]
I believe this is resolved.  Please reopen if there are still problems.
