### ISSUE TITLE
[Resolved] Sign-in request getting auto canceled.

### ISSUE THREAD

**Issue by HexdogStudio** [playgameservices/play-games-plugin-for-unity#3266]
I have succesfuly integrated the API inside my project, which seems working about 2 days, then without any modification both in the Console and the Editor side, It started canceling the authentication. I'm using Unity's built-in Social libray for authentication:
```
public static void SignIn(Action<bool> callback)
{
     PlayGamesPlatform.Activate();
     Social.localUser.Authenticate(callback);
}
```
I'm assuming everything was well setuped, becasue it worked for the first 2 days without any issue:
- Package name matching
- Fingerprint and keysotre matching
- Anti-piracy turned off
- Save games enabled
- Testers added both Cloud and Console side
- Resource xml matching
- Also I have force resolved the Andriod dependencies (doing it regularly before every build)
 
I'm getting this message:
```
09-12 21:31:12.534  7920  7944 W Unity   : *** [Play Games Plugin 0.11.01] 09. 12. 23 21:31:12 +02:00 ERROR: Returning an error code.
```

Also the game and all it's achievement is recognized by **Google Play Games App**, just the Authentication getting canceled for some reason, any idea?

Note: the game is in "Draft" stage at the Play Console, I don't think it's  have any impact on the result.

Unity version: 2021.3.28f1
GPGS Plugin version: 0.11.01

**Comment by skylorbeck** [comment]
I'm having the same issue. Would be very happy if anyone has any info at all.

**Comment by HexdogStudio** [comment]
Back after a few days and I'm finally manage to solve the problem, there is how I done it:
1. Create a new **Cloud** and **Play Console project** based on a different package name (otherwise I'm not sure its gona work with the old one)
2. Create both a **Web** and **Android** client at the creditians on **Google Cloud**
3. Add both clients to your GPGS creditians
4. Add Unity's **Authentication** package from the Package Manager (current version is 2.6.1)
5. In the Unity Editor menu, go to Edit > Project Settings…, then select Services > Authentication from the navigation menu.
- Set ID Providers to Google Play Services, then click Add.
- Enter the Web App client ID in the Client ID text field.
- Enter the Web App client secret in the Client Secret text field, then select Save. (more about it [here](https://docs.unity.com/ugs/en-us/manual/authentication/manual/platform-signin-google-play-games))
6. Copy the Resoure xml and use It to setup your project
7. Insert the Web client's id to the input field
8. Finaly force resolve your project and you can build and test It
I'm using the following script to authentication:
```
public static void SignIn(Action<SignInStatus> callback)
{
    PlayGamesPlatform.Activate();
    PlayGamesPlatform.Instance.Authenticate(callback);
}
```
I have tested in the last 4 days and It's still working, Cloud Saving and Achievements as well.
Hope It would help to someone else as well.

P.S: I'm moving from Unity after all of these mess around It's business plans, cheers.

**Comment by skylorbeck** [comment]
Thank you very much for the update. I was afraid it would be a "start over" scenario.
