### ISSUE TITLE
Setup correctly but still not working

### ISSUE THREAD

**Issue by Nixarn** [playgameservices/play-games-plugin-for-unity#3267]
I've tired everything, can't get it to work. I'm gonna revert to the older SDK for now. I've tried the simples of unity project to narrow down the issue and I've gone over all settings multiple times, tried starting over to make sure I've done it all correctly, but no luck.

The log keeps saying:

`09-28 16:08:40.226  6936 14541 E PlayGamesServices[SignInAuthenticator]: **** APP NOT CORRECTLY CONFIGURED TO USE GOOGLE PLAY GAME SERVICES`

and it lists up the package name, sha1, and app id and these are correct on the play & google cloud console side.

The problem is we're not getting decent error codes what exactly is wrong just "make sure everything is setup correctly".

**Comment by poorva-google** [comment]
Could you please try - "Force Resolve" after doing Windows -> GooglePlayPlugin -> Setup Android and provide the .xml file from your play console and reopen if it doesnt work
