### ISSUE TITLE
Game crashes with 0.9.10 and 0.9.11

### ISSUE THREAD

**Issue by sanmn19** [playgameservices/play-games-plugin-for-unity#328]
Hi. I have tested my game with every version up to 0.9.07 and it works well but with 0.9.10 and 0.9.11 it crashes. I see the initial google play screen asking me to log in but after logging in it crashes.
Device: Moto X(2013) running android 4.4
Unity version: 4.6.1
Google Play services: rev 22

Edit: I am overriding main activity of Unity.

 Here are the logs:

I/Unity   (10214):  [Play Games Plugin DLL] 12/19/14 18:45:57 +05:30 DEBUG: Creating platform-specific Play Games client.
I/Unity   (10214): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10214):  [Play Games Plugin DLL] 12/19/14 18:45:57 +05:30 DEBUG: Creating real IPlayGamesClient
I/Unity   (10214): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10214):  [Play Games Plugin DLL] 12/19/14 18:45:57 +05:30 DEBUG: Entering state: BeforeRoomCreateStartedState
I/Unity   (10214): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10214):  [Play Games Plugin DLL] 12/19/14 18:45:57 +05:30 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
I/Unity   (10214): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10214):  [Play Games Plugin DLL] 12/19/14 18:45:57 +05:30 DEBUG: Entering state: ShutdownState
I/Unity   (10214): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10214):  [Play Games Plugin DLL] 12/19/14 18:45:57 +05:30 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
I/Unity   (10214): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10214): Invalid levelID format levelID: -1
I/Unity   (10214): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10214):  [Play Games Plugin DLL] 12/19/14 18:45:58 +05:30 DEBUG: PlayGamesHelperObject.OnApplicationFocus True
I/Unity   (10214): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)
I/Unity   (10214):  [Play Games Plugin DLL] 12/19/14 18:45:59 +05:30 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID

Using GamesNativeSDK tag:

E/GamesNativeSDK(10214): Exception in dalvik/system/DexClassLoader.loadClass: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.NativeSdkEntryPoints" on path: DexPathList[[zip file "/data/data/com.hidden.hiddenGameName/app_.gpg.classloader/4da25210572e7e07ea67142ded62c42e.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]].
I/GamesNativeSDK(10214): Auth operation started: SIGN IN
I/GamesNativeSDK(10214): Connecting to Google Play...
V/GamesNativeSDK(10214): Play Games callback indicates connection.
I/GamesNativeSDK(10214): Successfully connected to Google Play.

**Comment by sanmn19** [comment]
My mobile has 4.4.4 and I am using ART and its running. I am trying to solve this by getting rid of the overriden activity.

**Comment by claywilkinson** [comment]
java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.NativeSdkEntryPoints
This is a harmless warning.

Sounds like it was an issue about overriding the activity.
