### ISSUE TITLE
When will the version with the recall API be distributed?

### ISSUE THREAD

**Issue by nm-cambria96** [playgameservices/play-games-plugin-for-unity#3280]
At this page(https://developer.android.com/games/pgs/recall/recall-setup?hl=ko#unity-sdk), Call RecallAccess to use the Recall API, but it's not in 11.01. When will it be distributed?

**Comment by vaibhavgpt-google** [comment]
Hi @nm-cambria96 , we'll be launching a new Unity Plugin version very soon with Recall Implementation.
Thanks
