### ISSUE TITLE
Remove Plugin Completely

### ISSUE THREAD

**Issue by fullheartgames** [playgameservices/play-games-plugin-for-unity#3286]
I have decided not to use Google Play Games and wish to remove it from my project. I am not sure the best way to do this and or the files that were added from Google Play Games. Can we get a list of all the files created on importing the package?

**Comment by Thaina** [comment]
First, Remove some file that you sure is from GPGS package
Then try to import GPGS unity package again, but not really import it. It will show the list of file that was already in your project

**Comment by poorva-google** [comment]
Remove these from assets:
1. External Dependency manager
2. GooglePlayGames plugin 
3. Smoketest if you have any. 

Closing this for now.. please reopen if it doesnt get resolved.
