### ISSUE TITLE
No login callback on Android 4.1.2

### ISSUE THREAD

**Issue by sanmn19** [playgameservices/play-games-plugin-for-unity#329]
I am using plugin version 0.9.07 and on my android 4.4 device it run perfectly but with android 4.1.2 device, I never get a login callback. I am using a third party plugin which overrides the default UnityPlayerActivity. The activity name that is overriding the main activity is 'AndroidNativeBridge'

Here are the logs:

I/Unity   ( 4530): AndroidJavaException: java.lang.NoSuchMethodError: no method with name='getClass' signature='()Ljava/lang/Object;' in class Lcom/androidnative/AndroidNativeBridge;
I/Unity   ( 4530):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
I/Unity   ( 4530):   at UnityEngine.AndroidJNISafe.GetMethodID (IntPtr obj, System.String name, System.String sig) [0x00000] in <filename unknown>:0
I/Unity   ( 4530):   at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0 
I/Unity   ( 4530):   at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr javaClass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0 
I/Unity   ( 4530):   at UnityEngine._AndroidJNIHelper.GetMethodID[AndroidJavaObject] (IntPtr jclass, System.String methodName, System.Object[] args, Boolean isStatic) [0x00000] in <filename unknown>:0 
I/Unity   ( 4530):   at UnityEngine.AndroidJNIHelper.GetMethodID[AndroidJavaObject] (IntPtr jclass, System.String methodName, System.Object[] a
I/Unity   ( 4530): [Play Games Plugin DLL] Creating platform-specific Play Games client.
I/Unity   ( 4530): [Play Games Plugin DLL] Making sure PlayGamesHelperObject is ready.
I/Unity   ( 4530): [Play Games Plugin DLL] PlayGamesHelperObject created.
I/Unity   ( 4530): [Play Games Plugin DLL] AUTH: starting auth process, silent=False
I/Unity   ( 4530): [Play Games Plugin DLL] Initializing Android Client.
I/Unity   ( 4530): [Play Games Plugin DLL] Creating GameHelperManager to manage GameHelper.
I/Unity   ( 4530): [Play Games Plugin DLL] Setting up GameHelperManager.
I/Unity   ( 4530): [Play Games Plugin DLL] GHM creating GameHelper.
I/Unity   ( 4530): [Play Games Plugin DLL] GHM calling GameHelper constructor with flags=7
I/Unity   ( 4530): AndroidJavaException: java.lang.NoSuchMethodError: no method with name='getClass' signature='()Ljava/lang/Object;' in class Lcom/androidnative/AndroidNativeBridge;
I/Unity   ( 4530):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
I/Unity   ( 4530):   at UnityEngine.AndroidJNISafe.GetMethodID (IntPtr obj, System.String name, System.String sig) [0x00000] in <filename unknown>:0 
I/Unity   ( 4530):   at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0 
I/Unity   ( 4530):   at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr javaClass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0 
I/Unity   ( 4530):   at UnityEngine._AndroidJNIHelper.GetMethodID[AndroidJavaObject] (IntPtr jclass, System.String methodName, System.Object[] args, Boolean isStatic) [0x00000] in <filename unknown>:0 
I/Unity   ( 4530):   at UnityEngine.AndroidJNIHelper.GetMethodID[AndroidJavaObject] (IntPtr jclass, System.String methodName, System.Object[] a
I/Unity   ( 4530): NullReferenceException: Object reference not set to an instance of an object
I/Unity   ( 4530):   at GooglePlayGames.Android.AndroidClient+<Authenticate>c__AnonStorey73.<>m__37 () [0x00000] in <filename unknown>:0 
I/Unity   ( 4530):   at UnityEngine.AndroidJavaRunnableProxy.run () [0x00000] in <filename unknown>:0 
I/Unity   ( 4530):   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
I/Unity   ( 4530): Rethrow as TargetInvocationException: UnityEngine.AndroidJavaRunnableProxy.run()
I/Unity   ( 4530):   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
I/Unity   ( 4530):   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, UnityEngine.AndroidJavaObject[] javaArgs) [0x00000] in <filename unknown>:0 
I/Unity   ( 4530):   at UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, IntPtr jmethodName, IntPtr jargs) [0x00000] in <filename unknown>:0 
I/Unity   ( 4530): [Play Games Plugin DLL] PlayGamesHelperObject.OnApplicationFocus True
I/Unity   ( 4530): FB.Init completed: Is user logged in? False
I/Unity   ( 4530): [Play Games Plugin DLL] PlayGamesHelperObject.OnApplicationPause True
I/Unity   ( 4530): [Play Games Plugin DLL] PlayGamesHelperObject.OnApplicationPause False
I/Unity   ( 4530): [Play Games Plugin DLL] PlayGamesHelperObject.OnApplicationPause True
I/Unity   ( 4530): [Play Games Plugin DLL] PlayGamesHelperObject.OnApplicationFocus False

**Comment by mrggl** [comment]
Do you see this issue with the new version of the plugin? (i.e. > 0.9.10)

The old versions of the plugin are deprecated and are not supported.
