### ISSUE TITLE
Unity splash Auto Login

### ISSUE THREAD

**Issue by meding09** [playgameservices/play-games-plugin-for-unity#3290]
This form is for reporting Unity Plugin issues only. To report an issue with the Play Games Service (non-SDK related), check [Google Play Games Services Support](https://developers.google.com/games/services/support).
*Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.*

**Describe the bug**

**To Reproduce**

I didn't call it from the GPGS code.

Is the GPGS login part of the Unity splash image itself to run the game?

I want to go to login and log in to GPGS.

**Expected behavior**

**Observed behavior**
A clear and concise description of what you observed.

**Bug Report**
[Capture](https://developer.android.com/studio/debug/bug-report) a bug report and share the Google Drive link. If the bug report contains sensitive information, then make it private and only give access to requests from `...@google.com` accounts.

**Screenshots**

**Versions**
- Unity version: ___2022.3.4f1
- Google Play Games Plugin for Unity version: ___0.11.01

**Additional context**

![test](https://github.com/playgameservices/play-games-plugin-for-unity/assets/148415014/4163e03d-8299-40be-967d-67bca16b9d43)

**Comment by poorva-google** [comment]
This is part of silent login feature we provide in v11 plugin. This is enabled by default. Closing this issue, please reopen it if necessary
