### ISSUE TITLE
0.9.11 Update: Play Game Bug

### ISSUE THREAD

**Issue by AJStyles** [playgameservices/play-games-plugin-for-unity#330]
After the 0.9.11 update have been Unable to play the game after logging in but works fine when not logged in.

**Comment by sanmn19** [comment]
I have the same issue. My game keeps restarting if its logged in but if I go to google settings , disconnect the app and then press cancel on login request my game runs fine. Here is the log:

I/Unity   (18758):  [Play Games Plugin DLL] 01/04/15 21:11:07 +05:30 DEBUG: Instance was not initialized, using default configuration.

I/Unity   (18758): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (18758): UnityEngine.Debug:Log(Object)

I/Unity   (18758): GooglePlayGames.OurUtils.Logger:d(String) (at I:\Idea2\Assets\GooglePlayGames\OurUtils\Logger.cs:46)

I/Unity   (18758): GooglePlayGames.PlayGamesPlatform:get_Instance() (at I:\Idea2\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:79)

I/Unity   (18758): CloudDataStore:authenticate() (at I:\Idea2\Assets\Resources\Scripts\ManagerScripts\CloudDataStore.cs:80)

I/Unity   (18758): <login>c__Iterator1C:MoveNext() (at I:\Idea2\Assets\Resources\Scripts\ManagerScripts\CloudDataStore.cs:51)

I/Unity   (18758): UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)

I/Unity   (18758): UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)

I/Unity   (18758): CloudDataStore:Awake() (at I:\Idea2\Assets\Resources\Scripts\ManagerScripts\CloudDataStore.cs:46)

I/Unity   (18758):  [Play Games Plugin DLL] 01/04/15 21:11:07 +05:30 DEBUG: Creating platform-specific Play Games client.

I/Unity   (18758): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (18758): UnityEngine.Debug:Log(Object)

I/Unity   (18758): GooglePlayGames.OurUtils.Logger:d(String) (at I:\Idea2\Assets\GooglePlayGames\OurUtils\Logger.cs:46)

I/Unity   (18758): GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at I:\Idea2\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:193)

I/Unity   (18758): GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at I:\Idea2\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:170)

I/Unity   (18758): GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at I:\Idea2\Assets\GooglePlayGames\ISocialPlatform\PlayGamesLocalUser.cs:44)

I/Unity   (18758): CloudDataStore:authenticate() (at I:\Idea2\Assets\Resources\Scripts\ManagerScripts\CloudDataStore.cs:80)

I/Unity   (18758): <login>c__Iterator1C:MoveNext() (at I:\Idea2\Assets\Resources\Scripts\ManagerScripts\CloudDataStore.cs:51)

I/Unity   (18758): UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)

I/Unity   (18758): UnityEngine.MonoBehaviour:StartCoroutine(IEnumera

I/Unity   (18758):  [Play Games Plugin DLL] 01/04/15 21:11:07 +05:30 DEBUG: Creating real IPlayGamesClient

I/Unity   (18758): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (18758): UnityEngine.Debug:Log(Object)

I/Unity   (18758): GooglePlayGames.OurUtils.Logger:d(String) (at I:\Idea2\Assets\GooglePlayGames\OurUtils\Logger.cs:46)

I/Unity   (18758): GooglePlayGames.PlayGamesClientFactory:GetPlatformPlayGamesClient(PlayGamesClientConfiguration) (at I:\Idea2\Assets\GooglePlayGames\Platforms\PlayGamesClientFactory.cs:32)

I/Unity   (18758): GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at I:\Idea2\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:194)

I/Unity   (18758): GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at I:\Idea2\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:170)

I/Unity   (18758): GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at I:\Idea2\Assets\GooglePlayGames\ISocialPlatform\PlayGamesLocalUser.cs:44)

I/Unity   (18758): CloudDataStore:authenticate() (at I:\Idea2\Assets\Resources\Scripts\ManagerScripts\CloudDataStore.cs:80)

I/Unity   (18758): <login>c__Iterator1C:MoveNext() (at I:\Idea2\Assets\Resour

V/AlarmManager(  856): sending alarm Alarm{66350b08 type 3 com.domobile.applock}

D/GamesUnitySDK(18758): Performing Android initialization of the GPG SDK

E/GamesNativeSDK(18758): Exception in dalvik/system/DexClassLoader.loadClass: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.NativeSdkEntryPoints" on path: DexPathList[[zip file "/data/data/com.xxxx.yyyyyy/app_.gpg.classloader/4da25210572e7e07ea67142ded62c42e.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]].

W/PopupManager(18758): You have not specified a View to use as content view for popups. Falling back to the Activity content view which may not work properly in future versions of the API. Use setViewForPopups() to set your content view.

I/GamesNativeSDK(18758): Auth operation started: SIGN IN

I/GamesNativeSDK(18758): Connecting to Google Play...

I/Unity   (18758):  [Play Games Plugin DLL] 01/04/15 21:11:07 +05:30 DEBUG: Entering state: BeforeRoomCreateStartedState

I/Unity   (18758): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (18758): UnityEngine.Debug:Log(Object)

I/Unity   (18758): GooglePlayGames.OurUtils.Logger:d(String) (at I:\Idea2\Assets\GooglePlayGames\OurUtils\Logger.cs:46)

I/Unity   (18758): GooglePlayGames.Native.RoomSession:EnterState(State) (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:333)

I/Unity   (18758): GooglePlayGames.Native.RoomSession:.ctor(RealtimeManager, RealTimeMultiplayerListener) (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:304)

I/Unity   (18758): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:GetTerminatedSession() (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:42)

I/Unity   (18758): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:.ctor(NativeClient, RealtimeManager) (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:38)

I/Unity   (18758): GooglePlayGames.Native.NativeClient:InitializeGameServic

I/Unity   (18758):  [Play Games Plugin DLL] 01/04/15 21:11:07 +05:30 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.

I/Unity   (18758): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (18758): UnityEngine.Debug:Log(Object)

I/Unity   (18758): GooglePlayGames.OurUtils.Logger:d(String) (at I:\Idea2\Assets\GooglePlayGames\OurUtils\Logger.cs:46)

I/Unity   (18758): GooglePlayGames.Native.State:OnStateEntered() (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:500)

I/Unity   (18758): GooglePlayGames.Native.RoomSession:EnterState(State) (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:334)

I/Unity   (18758): GooglePlayGames.Native.RoomSession:.ctor(RealtimeManager, RealTimeMultiplayerListener) (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:304)

I/Unity   (18758): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:GetTerminatedSession() (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:42)

I/Unity   (18758): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:.ctor(NativeClient, Realt

D/AppStateService(14534): client connected with version: 6587000

I/Unity   (18758):  [Play Games Plugin DLL] 01/04/15 21:11:07 +05:30 DEBUG: Entering state: ShutdownState

I/Unity   (18758): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (18758): UnityEngine.Debug:Log(Object)

I/Unity   (18758): GooglePlayGames.OurUtils.Logger:d(String) (at I:\Idea2\Assets\GooglePlayGames\OurUtils\Logger.cs:46)

I/Unity   (18758): GooglePlayGames.Native.RoomSession:EnterState(State) (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:333)

I/Unity   (18758): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:GetTerminatedSession() (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:43)

I/Unity   (18758): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:.ctor(NativeClient, RealtimeManager) (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:38)

I/Unity   (18758): GooglePlayGames.Native.NativeClient:InitializeGameServices() (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeClient.cs:153)

I/Unity   (18758): GooglePlayGames.Native.NativeClient:Authenticate(Action`1, Boolean) (at I:\Idea2\Assets\GooglePlayGames\Platforms\Na

I/Unity   (18758):  [Play Games Plugin DLL] 01/04/15 21:11:07 +05:30 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.

I/Unity   (18758): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (18758): UnityEngine.Debug:Log(Object)

I/Unity   (18758): GooglePlayGames.OurUtils.Logger:d(String) (at I:\Idea2\Assets\GooglePlayGames\OurUtils\Logger.cs:46)

I/Unity   (18758): GooglePlayGames.Native.State:OnStateEntered() (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:500)

I/Unity   (18758): GooglePlayGames.Native.RoomSession:EnterState(State) (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:334)

I/Unity   (18758): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:GetTerminatedSession() (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:43)

I/Unity   (18758): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:.ctor(NativeClient, RealtimeManager) (at I:\Idea2\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:38)

I/Unity   (18758): GooglePlayGames.Native.NativeClient:InitializeGameServices() (at I:\Idea2\Assets\GooglePlay

V/GamesNativeSDK(18758): Play Games callback indicates connection.

I/GamesNativeSDK(18758): Successfully connected to Google Play.

I/Unity   (18758):  [Play Games Plugin DLL] 01/04/15 21:11:07 +05:30 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID

I/Unity   (18758): (Filename: /Applications/buildAgent/work/d63dfc6385190b60/artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 49)

W/art     (18758): Thread[21,tid=18842,Native,Thread*=0x52509190,peer=0x65434628,"Thread-3793"] attached without supplying a name

I/SFPerfTracer(  231):      triggers: (rate: 0:23) (47926 sw vsyncs) (0 skipped) (163:359003 vsyncs) (165:447415)

I/WindowState(  856): WIN DEATH: Window{65f511a0 u0 com.xxxxx.yyyyyy/com.unity3d.player.UnityPlayerProxyActivity}

I/ActivityManager(  856): Process com.xxxxx.yyyyyy (pid 18758) has died.

**Comment by gguuss** [comment]
A few questions:

1. Does your app still work if you use an older version of the plugin?
2. What version of the Play Games SDK are you using? You might want to update from here to make sure you have the right matching SDK. https://developers.google.com/games/services/downloads/

**Comment by claywilkinson** [comment]
@sanmn19 / @AJStyles  - I am going to close this issue, since it has been a couple months with no comments - please re-open if you are still having issues.

**Comment by Mariamas4** [comment]
Yes it's Not working, I tried a lot with no hope, then it worked on 4.5 when I configured the same project with that older version
