### ISSUE TITLE
Is it possible to do a silent login with play games platform?

### ISSUE THREAD

**Issue by mjs9513** [playgameservices/play-games-plugin-for-unity#3301]
Hey, just wondering if it is possible to do a silent login to Google Play Games where the welcome banner does not pop up showing the username and level. If it is, would someone mind sharing an example?

**Comment by Thaina** [comment]
This repo has been neglected. The new version of GPGS always do silent signIn

I have forked and do all upgrading https://github.com/Thaina/play-games-plugin-for-unity/tree/master

You can compare the change here https://github.com/playgameservices/play-games-plugin-for-unity/pull/3304

**Comment by Thaina** [comment]
I don't think it possible

How about separate init function into RuntimeInitializeOnloadMethod so it show banner while loading the game in black screen ,instead of at the scene
