### ISSUE TITLE
Issue getting Saved Games to work on device

### ISSUE THREAD

**Issue by lucasecardoso** [playgameservices/play-games-plugin-for-unity#3305]
I've been attempting to make the Saved Games feature work on Android devices. However, despite having enabled and published the Saved Games feature on the play console:

![image](https://github.com/playgameservices/play-games-plugin-for-unity/assets/12672911/f9febcda-dae5-4d7c-9c3c-b800204ddd7d)

even after 48 hours have passed, I keep getting this message on the device:

`DEBUG: InternalOpen has failed: java.lang.IllegalStateException: Cannot use snapshots without enabling the 'Saved Game' feature in the Play console`

This is how I'm signing in client side:

```
PlayGamesPlatform.DebugLogEnabled = true;
PlayGamesPlatform.InitializeInstance(new PlayGamesClientConfiguration.Builder().EnableSavedGames().Build());
PlayGamesPlatform.Activate();
PlayGamesPlatform.Instance.Authenticate(SignInInteractivity.CanPromptAlways, ProcessAuthentication);
```

This is the debug output

```
2024/06/20 11:43:52.854 17634 17656 Info Unity  [Play Games Plugin 0.10.14] 06-20-24 11:43:52 -07:00 DEBUG: Authentication succeeded
2024/06/20 11:43:52.854 17634 17656 Info Unity GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
2024/06/20 11:43:52.854 17634 17656 Info Unity 
2024/06/20 11:43:52.880 17634 17656 Info Unity  [Play Games Plugin 0.10.14] 06-20-24 11:43:52 -07:00 DEBUG: InternalOpen has failed: java.lang.IllegalStateException: Cannot use snapshots without enabling the 'Saved Game' feature in the Play console
2024/06/20 11:43:52.880 17634 17656 Info Unity GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
```

The way I'm testing this is by doing a debug, signed AppBundle build on the editor and installing it on the device directly.

Am I missing something? Is it just a situation where I need to wait for longer for the Google services to pick up the change?

Thanks in advance.

**Comment by smile616** [comment]
what's your game  Play Games app id or package name?

**Comment by lucasecardoso** [comment]
> what's your game Play Games app id or package name?

com.RedNexusGamesInc.Peglin

**Comment by smile616** [comment]
@lucasecardoso qq: have you increased the app version after you published the Saved Games feature on the play console?
If not, try increasing the app version, build, install and keep the device up for 24 hours.

**Comment by lucasecardoso** [comment]
> @lucasecardoso qq: have you increased the app version after you published the Saved Games feature on the play console? If not, try increasing the app version, build, install and keep the device up for 24 hours.

@smile616 

Sorry for the long necro, but I've been off of this for a few months now since we had to shift into other things. I'm revisiting this issue now, and I'm finding the same problem as before. 

App version has been updated. Both version number and app bundle version code. We've had multiple production updates since I was testing this out in the testing branch, and the branch's been updated with the production code.

I'm a bit at a loss at what is happening here.

**Comment by lucasecardoso** [comment]
Okay. I managed to fix this.

For anyone having similar issues, I think the problem might have been that we had a test track that existed prior to this change in features. Deleting the internal testing track from the **Play Games Services Testers** and recreating it seems to have fixed the issue.
