### ISSUE TITLE
When uploading to google play get message (Update your Play Core Maven dependency to an Android 14 compatible version! )

### ISSUE THREAD

**Issue by marcozakaria** [playgameservices/play-games-plugin-for-unity#3308]
I am using Unity 2021.3.21f and play games plugin 0.11.01
i have sdk installed from unity and plugins are up to date version and project builds in unity with no errors, but when i upload build to playstore i get this warning and i dont know what to do, please help 

Google Play Core (com.google.android.play:core) has added this note for SDK version 1.10.0:Update your Play Core Maven dependency to an Android 14 compatible version! Your current Play Core library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers to improve user security. As a reminder, from August 31, Google Play requires all new app releases to target Android 14. Update to the latest Play Core library version dependency to avoid app crashes: https://developer.android.com/guide/playcore#playcore-migration To release new versions containing this SDK version to production or open testing, upgrade to a newer version by 18 September 2024 00:00 (UTC).

**Comment by JoseGarcia1415** [comment]
Did they already fix it?

**Comment by JoseGarcia1415** [comment]
maybe using  a new play core version could help.

https://github.com/google-unity/google-play-core

**Comment by AloloL0** [comment]
Hi, this is a very important issue for us since we want to release a new game in one month and I need a version that complies with google's guidelines tomorrow - also: we have to push some updates in a rather short time-frame. Does anybody know what we will have to do to comply with google's guidelines?

**Comment by smile616** [comment]
@marcozakaria 
Are you sure that the com.google.android.play:core dependency is coming from the games plugin? 

@marcozakaria / @AloloL0 
Could you check if your games have explicit dependence on the "com.google.play.core" and updates them following https://github.com/google-unity/google-play-core?tab=readme-ov-file#how-to-install ?

**Comment by marcozakaria** [comment]
Updating to Unity 2021.3.41f solved this issue and the warning disappeared from play console 
from Unity Support : if i use split app binaries in aab it will automatically at PAD to it , needed to update unity to have latest version of PAD that needed for new play story requirements

**Comment by rico345100** [comment]
Updated unity to 2021.3.43f1 and 2022.3.45f1, no split app binaries, did force resolve, still gradle contains Play Core 1.10.3.

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
// Android Resolver Dependencies Start
    implementation 'com.google.android.play:core:1.10.3' // Assets/GooglePlayPlugins/com.google.play.core/Editor/PlayCoreDependencies.xml:3
    implementation 'com.google.games:gpgs-plugin-support:0.10.14' // Assets/GooglePlayGames/Editor/GooglePlayGamesPluginDependencies.xml:11
// Android Resolver Dependencies End
**DEPS**}
```

Deleting all custom gradle files and creating them again doesn't work, either. Google still refusing my app bundle.
```
Update your com.google.android.play:core:1.10.3 Maven dependency to an Android 14 compatible version! Your current com.google.android.play:core:1.10.3 library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers. As a reminder, from August 31, 2024, Google Play requires all new app releases to target Android 14. Update to the latest library version dependency to avoid app crashes.
```
