### ISSUE TITLE
No Google Play Games Resources for application

### ISSUE THREAD

**Issue by CeleDKo** [playgameservices/play-games-plugin-for-unity#3312]
Tell me how I can get and configure in the Unity resource when I want to make authorization for the application, and in the console, as I understand it, game services are available only for games, I don’t even see lines with Google services in the console.

**Comment by vaibhavgpt-google** [comment]
Hi, you can go through the documentation for setting up Google Play games plugin for Unity.
[Documentation](https://developer.android.com/games/pgs/unity/unity-start)
