### ISSUE TITLE
Authenticate failure without popup to sign into Google Play Games.

### ISSUE THREAD

**Issue by kevinfish356** [playgameservices/play-games-plugin-for-unity#3319]
**Describe the bug**
If a phone is not signed into Google Play Games, `Authenticate()` will just fail with message `[PlayGamesPlatform.Instance.Authenticate failed! status: [Canceled]]`. I would expect a popup for user to sign in or redirect them to Google Play Games. 

**To Reproduce**
1. Clear sign in status of Google Play Games by clicking `Clear Storage` in the settings. 
2. Restart your phone. (This will make sure the login status is cleared)
3. Enter your game and try to authenticate with Google Play Games.

**Expected behavior**
A popup to log into Google Play Games, or redirect to Google Play Games App. Or at least an error message telling the user is not logged into Google Play Games.

**Observed behavior**
Function failed with status "Cancelled"
`[PlayGamesPlatform.Instance.Authenticate failed! status: [Canceled]]`

**Bug Report**
[Capture](https://developer.android.com/studio/debug/bug-report) a bug report and share the Google Drive link. If the bug report contains sensitive information, then make it private and only give access to requests from `...@google.com` accounts.

TBD

**Screenshots**

**Versions**
- Unity version: 2022.3.28f1
- Google Play Games Plugin for Unity version: 0.11.01

**Additional context**

**Comment by vaibhavgpt-google** [comment]
Hi @kevinfish356, Google Play Games would only show pop up in case of success. You could have your custom pop up in case needed.
Thanks.
