### ISSUE TITLE
I got a warning before update the plugin

### ISSUE THREAD

**Issue by abalta** [playgameservices/play-games-plugin-for-unity#332]
I have a warning after import updated plugin and locate sdk path. When I redo android setup I got a warning.

![warn](https://cloud.githubusercontent.com/assets/8448805/5516536/85066db8-88ad-11e4-8f43-a479f3c4dc50.PNG)

**Comment by mrggl** [comment]
Duplicate of https://github.com/playgameservices/play-games-plugin-for-unity/issues/331, closing this to centralize discussion.
