### ISSUE TITLE
Sign in working but Leaderboard not being displayed

### ISSUE THREAD

**Issue by Jazz1122k** [playgameservices/play-games-plugin-for-unity#3320]
This form is for reporting Unity Plugin issues only. To report an issue with the Play Games Service (non-SDK related), check [Google Play Games Services Support](https://developers.google.com/games/services/support).
*Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.*

**Describe the bug**
The google play sign in works because i can see my account name when i launch the game but the leaderboard is not being displayed, the scores are not being posted either. 

**To Reproduce**
1. Installing the latest google play plugin (0.11.01)
2. Resolving dependencies using the latest external dependency manager
3. Building the apk with highest API level set to 33

**Expected behavior**
The leaderboard UI to be displayed

**Observed behavior**
I get the classNotFoundException: google.games.bridge.HelperFragment in the android logcat 

**Bug Report**
[Capture](https://developer.android.com/studio/debug/bug-report) a bug report and share the Google Drive link. If the bug report contains sensitive information, then make it private and only give access to requests from `...@google.com` accounts.

**Screenshots**
![WhatsApp Image 2024-10-22 at 3 48 35 PM](https://github.com/user-attachments/assets/39e01e0d-dc70-4d30-aa2c-8d59596e2eee)
.

**Versions**
- Unity version: 2022.3.12f1
- Google Play Games Plugin for Unity version: 0.11.01

**Additional context**

**Comment by karthikeyan9952** [comment]
I have the same issue. Any solution?

**Comment by Jazz1122k** [comment]
I finally fixed it by changing the maven URL in the settingsTemplate.gradle 

from 

`  maven {
            url (unityProjectPath + "/Assets/GooglePlayGames/com.google.play.games/Editor/m2repository") // Assets/GooglePlayGames/com.google.play.games/Editor/GooglePlayGamesPluginDependencies.xml:11
        }`

to 

`maven {
            url (unityProjectPath + "/Assets/GeneratedLocalRepo/GooglePlayGames/com.google.play.games/Editor/m2repository") // Assets/GooglePlayGames/com.google.play.games/Editor/GooglePlayGamesPluginDependencies.xml:11
        }`
        
        hope this helps, also dont resolve dependencies after making the change, just build, if you resolve you will have to replace the line once again

**Comment by karthikeyan9952** [comment]
> I finally fixed it by changing the maven URL in the settingsTemplate.gradle. you can get more info here [https://github.com/playgameservices/play-games-plugin-for-unity/issues/3249](url)
> 
> from
> 
> ` maven { url (unityProjectPath + "/Assets/GooglePlayGames/com.google.play.games/Editor/m2repository") // Assets/GooglePlayGames/com.google.play.games/Editor/GooglePlayGamesPluginDependencies.xml:11 }`
> 
> to
> 
> ` maven { url (unityProjectPath + "/Assets/GeneratedLocalRepo/GooglePlayGames/com.google.play.games/Editor/m2repository") // Assets/GooglePlayGames/com.google.play.games/Editor/GooglePlayGamesPluginDependencies.xml:11 }`

Thanks. It worked
