### ISSUE TITLE
Google Play Plugins 2.0 releasing soon !!

### ISSUE THREAD

**Issue by poorva-google** [playgameservices/play-games-plugin-for-unity#3323]

**Comment by poulgray63** [comment]
Great! Are there any approximate dates?

**Comment by poorva-google** [comment]
just released, [please check ](https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.0.0)

**Comment by Gerjo** [comment]
Why was the update pulled? It seemingly functioned better than the "old plugin" in unity 6000. The old plugin does not work at all.

**Comment by poorva-google** [comment]
Hi, uploaded again.. :)

**Comment by poulgray63** [comment]
Thank you! I really appreciate your work.
