### ISSUE TITLE
[2.0.0] The file “GooglePlayGamesManifest.androidlib” in the folder “Plugins/Android” is not generated

### ISSUE THREAD

**Issue by RocksteadyDog** [playgameservices/play-games-plugin-for-unity#3327]
**Describe the bug**
After adding the plugin to the project, the file “GooglePlayGamesManifest.androidlib” in the folder “Plugins/Android” is not generated, is this the way it should be?

**To Reproduce**
I've attached a video

**Expected behavior**
file “GooglePlayGamesManifest.androidlib” is generated

**Observed behavior**
"GooglePlayGamesManifest.androidlib" file is not generated.

**Screenshots**

https://github.com/user-attachments/assets/77d428a5-8ddd-489b-980f-5e21dde3716a

<img width="404" alt="Снимок экрана 2024-11-22 в 16 42 11" src="https://github.com/user-attachments/assets/7545b13a-0b6c-4052-9a90-2ae12c13a9b6">

**Versions**
- Unity version:2022.3.53f1
- Google Play Games Plugin for Unity version: 2.0.0

**Comment by poorva-google** [comment]
The behaviour of EDM4U is changed, you wont see all the dependencies exploded in folder. Now, those are resolved at runtime. Could you pls try Force resolve and try to see if your apk/aab file builds and runs fine.

**Comment by RocksteadyDog** [comment]
> The behaviour of EDM4U is changed, you wont see all the dependencies exploded in folder. Now, those are resolved at runtime. Could you pls try Force resolve and try to see if your apk/aab file builds and runs fine.

ok, i'll write when i test it

**Comment by RocksteadyDog** [comment]
> The behaviour of EDM4U is changed, you wont see all the dependencies exploded in folder. Now, those are resolved at runtime. Could you pls try Force resolve and try to see if your apk/aab file builds and runs fine.

Hello! I've tested

Hello! I've tested

1) If the plugin is in “Packages”, “GooglePlayGamesManifest.androidlib”, “GeneratedLocalRepo” folder the folder and dependencies are not generated. I added the project folder to google drive.
https://drive.google.com/drive/folders/1EkIvfy402FCu-55jQenEKf9epR8b7yhc?usp=share_link
1a) For the example if I add the firebase package from here -.
https://developers.google.com/unity/archive?hl=en#play_asset_delivery. 
“GeneratedLocalRepo” folder and dependencies are generated normally.
2) If the plugin is in the “Assets” folder everything works fine

**Comment by RocksteadyDog** [comment]
> yes the plugin is not compatible with OpenUPM therefore cant be applied in "packages", it should be imported as custom package only

Got it😀 Then everything works fine. Closed.
