### ISSUE TITLE
This plugin have Getting Friend List feature~??

### ISSUE THREAD

**Issue by Zyngie** [playgameservices/play-games-plugin-for-unity#333]
I want to know this plugin have load friend feature or not, cause when I call LoadFriend function in Unity always is fail~!><""""And I cant find any script in plugin is about load friend~!><"

**Comment by claywilkinson** [comment]
tracking internally as 19134942

**Comment by claywilkinson** [comment]
This has been implemented in the version 0.9.25 of the plugin
