### ISSUE TITLE
Can't connect more than 2 players on IOS (The 3rd & 4th player NEVER get OnRoomConnected Called back)

### ISSUE THREAD

**Issue by nixvalentine** [playgameservices/play-games-plugin-for-unity#335]
Dear All,

THIS IS REAL TIME MULTIPLAYER ISSUE on IOS, Android doesn't have this error.

I found out that Whenever we connect 3 players (never test with 4 players), by Accepting invitation or Quick Match, the 3rd player will never connect though the other two connect just fine. With invitation, the last player accepts will be the one left out T!T.

Please note that when I use Participant List to get the list of connected participant, in the first 2 players, it returns 3, which mean it recognized that the 3rd connected.

After debugging, I found out that on the 3rd player, the OnRoomConnected never get call back. Don't know why. To my limited knowledge, OnRoomConnect fires when ALL players required are connected so if 2 first players can connect that means to them the 3rd player connect successfully too. However, the 3rd player only stays at waiting screen since its OnRoomConnect just....dead.

I even tried to force to setup the game without OnRoomConnected in the 3rd player by OnPeerConnected to see if (number of peer connect == number of connected participant). But OnPeerConnected don't get call back either (even in the other two). Then I tried to let other two send message to 3rd player by sendmessagetoAll to let the 3rd player know when to start setup without OnRoomConnected...game crashed... So now I'm stuck and spend 15' to sign up the github account. You know the rest =)).

Furthermore, this issue exists even in google play sample, QUIZ RACE, (also 4.6 version).

Any support from you guys are super appreciated and hope this help others have same problem too.

Regards.
Nix

**Comment by claywilkinson** [comment]
Thanks for the details Nix.  Tracking internally as 18932589.

**Comment by gclaret** [comment]
Same is happening to me... I have a button to Auto-match a game... (With a room of max 3 opponents).

The first 2 go in just fine, and when I try to connect to a 3rd player, he never gets the callback that he connected succesfuly.

**Comment by claywilkinson** [comment]
I believe that this is fixed in 0.9.20 with C++ SDK 1.4.1.  I tested with 3 players and everything was OK on iOS and Android.  Please reopen this issue if you still have questions.
