### ISSUE TITLE
Setting GPG SignIn/Achievement Message Orientation

### ISSUE THREAD

**Issue by mburton89** [playgameservices/play-games-plugin-for-unity#336]
Hi Guys,

I've integrated my iOS game with the unity plugin. My game uses the services correctly but the sign-in popup and the achievement popups in the game are displaying in portrait mode, while my game is viewed in landscape mode. There IS a way to set the orientation using the 'validOrientationFlags' property of the GPGManager, but the GPGManger exists only in the GooglePlayGames.framework (To see implementation... https://developers.google.com/games/services/ios/achievements) However, it seems this plugin uses the gpg.framework as an alternative to GooglePlayGames.framework.

Is there a way to support different orientations using the gpg.framework, or will I have to integrate both the GooglePlayGames.framework AND gpg.framework?

Thanks for any insight on the matter!

**Comment by claywilkinson** [comment]
tracking internally 19142461

**Comment by mburton89** [comment]
Thanks for the update

On Mon, Jan 26, 2015 at 10:39 AM, Clayton Wilkinson <
notifications@github.com> wrote:

> tracking internally 19142461
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/336#issuecomment-71490994>
> .
>



-- 
Matthew Burton
314 280 3498

**Comment by dakikifr** [comment]
Hi,

any news on this issue?

**Comment by mburton89** [comment]
Hi! And no I have not seen or heard of any update. I switched to game
center and am still very satisfied :)

**Comment by dakikifr** [comment]
That's a shame.
iOS8 has been out for 6 months now and that bug is really annoying.
If google wants us to support and promote GameServices, then it should fix bugs like this more quickly. It's very very bad for the gameplay to have to rotate your device everytime you login or get an achievement.

**Comment by mburton89** [comment]
I completely agree. Google Game Services is almost impossible to implement
on iOS now because of the lack of support and all the additional custom
configurations devs need to do to enable GGS.

I wish you luck on finding a solution!

On Tue, Mar 3, 2015 at 3:50 AM, dakikifr <notifications@github.com> wrote:

> That's a shame.
> iOS8 has been out for 6 months now and that bug is really annoying.
> If google wants us to support and promote GameServices, then it should fix
> bugs like this more quickly. It's very very bad for the gameplay to have to
> rotate your device everytime you login or get an achievement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/336#issuecomment-76916004>
> .
>



-- 
Matthew Burton
314 280 3498

**Comment by mburton89** [comment]
But also, the people at GitHub are pretty awesome for letting us use their
plugins :) My android version works well!

On Tue, Mar 3, 2015 at 10:01 AM, Matthew Burton <matthewwburton@gmail.com>
wrote:

> I completely agree. Google Game Services is almost impossible to implement
> on iOS now because of the lack of support and all the additional custom
> configurations devs need to do to enable GGS.
>
> I wish you luck on finding a solution!
>
> On Tue, Mar 3, 2015 at 3:50 AM, dakikifr <notifications@github.com> wrote:
>
>> That's a shame.
>> iOS8 has been out for 6 months now and that bug is really annoying.
>> If google wants us to support and promote GameServices, then it should
>> fix bugs like this more quickly. It's very very bad for the gameplay to
>> have to rotate your device everytime you login or get an achievement.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/336#issuecomment-76916004>
>> .
>>
>
>
>
> --
> Matthew Burton
> 314 280 3498
>



-- 
Matthew Burton
314 280 3498

**Comment by dakikifr** [comment]
Hi,

still no ETA for a fix on this very annoying bug?
I'm pretty sure my game will be rejected by Apple for that.

(I'm directly using the c++ sdk by the way, but the bug should be the same)

**Comment by claywilkinson** [comment]
This is fixed in  version 1.4 of the Google Play Game Services C++ SDK.  You can download it from
https://developers.google.com/games/services/downloads/

Please re-open if you are still having issues.

**Comment by dakikifr** [comment]
Hi,
I can't link with the new version of the sdk on android, I'm having duplicate symbols during link phase:
ld: error: libcurl.a(md5_dgst.o): multiple definition of 'md5_block_data_order'
gpg-cpp-sdk/android/lib/gnustl/armeabi/libgpg.a: previous definition here

But I successfully tested the sdk on iOS and the bug is fixed, thanks!

**Comment by claywilkinson** [comment]
You're welcome!  Your linker error is when building a native project?  You might want to track that in the native sample repo: https://github.com/playgameservices/cpp-android-basic-samples
Did this project used to link OK?

**Comment by dakikifr** [comment]
It's when using a native project yes.
With sdk 1.3, it was linking just fine on both iOS and Android
With sdk 1.4, it linked fine on iOS, but I've that error on Android

I'll try the native repo, but I'm a little worried I won't get an answer, there is not much activity there :)

I've another issue I didn't talk about yet (and it should have it own "issue id"), but I don't know if it's because the game is in dev mode or not. On iOS the achievement points are never shown (neither when an ach is locked, nor when unlocked, nor in the default achievement UI listing). On Android it works just fine. I tested with both sdk 1.3 and 1.4, same issue.

**Comment by mburton89** [comment]
Thanks!

On Sat, Apr 4, 2015 at 4:46 AM, dakikifr <notifications@github.com> wrote:

> It's when using a native project yes.
> With sdk 1.3, it was linking just fine on both iOS and Android
> With sdk 1.4, it linked fine on iOS, but I've that error on Android
>
> I'll try the native repo, but I'm a little worried I won't get an answer,
> there is not much activity there :)
>
> I've another issue I didn't talk about yet (and it should have it own
> "issue id"), but I don't know if it's because the game is in dev mode or
> not. On iOS the achievement points are never shown (neither when an ach is
> locked, nor when unlocked, nor in the default achievement UI listing). On
> Android it works just fine. I tested with both sdk 1.3 and 1.4, same issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/336#issuecomment-89540298>
> .
>



-- 
Matthew Burton
314 280 3498
