### ISSUE TITLE
Problem with the new cloud save system

### ISSUE THREAD

**Issue by Glintlabs** [playgameservices/play-games-plugin-for-unity#339]
Hello, I'm trying to use the new cloud save system but I've a problem. I have the following errors wich I can't solve:

Assets/saux.cs(126,35): error CS0246: The type or namespace name `SavedGameRequestStatus' could not be found. Are you missing a using directive or an assembly reference?

The same happen with ISavedGameMetadata, SavedGameRequestStatus and TimeSpan
 
Do you know what how can I solve this problem?

**Comment by Glintlabs** [comment]
Solved

**Comment by aunymoons** [comment]
Could you Specify how you did it? i'm having the same issue

**Comment by aunymoons** [comment]
Solved it as well! in case anyone is wondering, you just have to add this line at the top of your script:

using GooglePlayGames.BasicApi.SavedGame;
