### ISSUE TITLE
"Cannot use snapshots without enabling the 'Saved Game' feature in the Play console."

### ISSUE THREAD

**Issue by NaxIonz** [playgameservices/play-games-plugin-for-unity#342]
We have enabled "Saved Games" in the developer console (you really should add that to your documentation, by the way), however, we now get the following issue: 

```
Exception in com/google/android/gms/games/snapshot/Snapshots.getSelectSnapshotIntent: java.lang.IllegalStateException: Cannot use snapshots without enabling the 'Saved Game' feature in the Play console.
12-31 13:35:04.360: E/GamesNativeSDK(7598): Unable to show snapshot UI: skipping.
```

Which makes **zero** sense since that option was just toggled!
Clearly there is more that needs to be done that is completely missing from the documentation?

**Comment by ToddKerpelman** [comment]
Hey, @NaxIonz  are you still seeing this? According to bug #343 , this worked after a 24-hour delay.

**Comment by NaxIonz** [comment]
Yes, it appears that after an extended period of time, you have full permission to save. I would encourage that the documentation be updated with this so others don't waste countless hours debugging.

The extra frustrating part, was that that toggle resolved the authentication issue, but still blocked snapshots. So, it seems that **some** the effects/gates of that toggle go through immediately; while other systems are blocked for an undisclosed period of time.

**Comment by claywilkinson** [comment]
Thanks for the feedback on the documentation.  The documentation has been updated https://developers.google.com/games/services/common/concepts/savedgames.

**Comment by JesseScott** [comment]
I am getting this issue on an app that was updated in September !

**Comment by claywilkinson** [comment]
I am not sure what you mean - Do you mean that the app has lost its saved game configuration?
Is it published or draft?  If so, Can you share the app_id?
