### ISSUE TITLE
Share Game From Leaderboard

### ISSUE THREAD

**Issue by salmonmoose** [playgameservices/play-games-plugin-for-unity#345]
I've noticed newer games have a link at the bottom of leaderboards saying "Tell your friends how much you like this game" with a share link - they appear to be standard leaderboards - are we able to access this feature?

I've tried with a recent build (0.9.11) but have had no luck.

**Comment by mrggl** [comment]
This is a new feature from Play Services 6.5+

It appears on near-empty social or public leaderboards, you might not seeing it because of the number of scores in your leaderboard (or because your device doesn't have the play services 6.5+).

**Comment by salmonmoose** [comment]
Are these the only qualifiers? I'm seeing them for vastly more populated boards on the same devices as they appear unavailable for me.

Mostly it would be nice to have the hook to the share intent exposed.
