### ISSUE TITLE
Connection failure.

### ISSUE THREAD

**Issue by faisal007** [playgameservices/play-games-plugin-for-unity#347]
Hi,

I m using latest version of google play games i.e. 0.9.11 and Android SDK 21.0, i m getting this error while authenticating.

"UI interaction required to connect to game play".

Here is my code in Awake function:

PlayGamesClientConfiguration configconfig = new PlayGamesClientConfiguration.Builder().EnableSavedGames() .Build();

PlayGamesPlatform.InitializeInstance (config);
PlayGamesPlatform.DebugLogEnabled = true;
PlayGamesPlatform.Activate();

And on button i m calling authenticate function like this:

Social.localUser.Authenticate((bool success) =>
	{
		if(success)
		{
			print ("Logged in");
			//ReportScore();
		}
		else
		{
			print ("Not logged in");
		}

        }

**Comment by claywilkinson** [comment]
I believe you want to log in from the Start() method, not Awake, since there could be components that are not initialized yet when Awake is called.  Start is just before Update is called the first time.

**Comment by faisal007** [comment]
In awake function i m just activating playgames and enabling logs, than on gui button i m calling authenticate function, so whats wrong in this ? should i need to wait some secs on start screen before hitting start button to authenticate from google plae games ?

**Comment by claywilkinson** [comment]
Is there a callstack associated with the error message?  That will help track down where the issue is

**Comment by galkon** [comment]
I too am having this issue. From what I have read you can't do auto logins with out first having UI interaction with the google play sign in but the API does not seem to cover this case.

**Comment by MofoMan2000** [comment]
The API will do what you tell it to do, regardless of any use interaction beforehand. The restriction on auto-logins is a stylistic thing and a "best practice" suggestion by Google. I don't think your app will be pulled from GPlay if you have an auto-login, but they don't like it. At least, that's how it was the last time I checked.

**Comment by galkon** [comment]
Turns out that was not the actual problem. The problem was a mis match of sha1 keys between my apk and the game I had set up in game services all is working for me now.

**Comment by claywilkinson** [comment]
Glad to hear it's working. Thanks for the update!

**Comment by asadmehmoodlogicon** [comment]
@treacher  Well Pointed I got the same problem but solved it using your way (Y)
