### ISSUE TITLE
Callbacks don't work for Turn Based Games on Android

### ISSUE THREAD

**Issue by adepase** [playgameservices/play-games-plugin-for-unity#348]
I commented this on another (closed) issue, but I think that could be lost.
I cannot get callbacks work in a turn based game even in version 0.9.11, both using 
PlayGamesPlatform.Instance.TurnBased.RegisterMatchDelegate(OnGotMatch);
and/or
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
			.WithInvitationDelegate(OnGotInvitation)
			.WithMatchDelegate(OnGotMatch).Build();
PlayGamesPlatform.InitializeInstance(config);

as for the new documentation.
I even tried them both together (the documentation is not so clear and the sample game implements the old documentation).
I'm working on Android.
I got some callbacks, seldom and random, but I cannot understand the conditions in which they work or not. Just got them worked (seldom and random, as told before), if I received the notification AFTER the logon, never if the app was not running before or if I was logged with another user.

To be more precise: I think this works when the bool parameter is true, because selecting the notification brings me to play the match, but I cannot get the notification directly in the game, with the bool parameter = false, in a consistent way (maybe I cannot understand how this should work: I expect to receive both the notification in android - parameter = true if clicked - and also in the game - parameter = false, without clicking anything)

**Comment by mrggl** [comment]
What you're describing sounds like intended behavior.

In order to deliver an in-game notification for a user we must be able to identify that the current player is the intended recipient of the notification - this requires that the user is logged in and the logged in user is the recipient of the notification.

Updates that happen when the correct user is not logged in can be retrieved at a later time through the normal turn based APIs.

Can you clarify what behavior you expect?

**Comment by adepase** [comment]
I expect:
1. When I'm logged in with the intended recipient, to receive the in-game notifications always, not just sometimes (I don't have a precise statistic, but let's say,  1 time on 10 seems to me too few)
2. When I'm not logged in (or logged with another user) I expect to be notified outside the game and,  when I log with the intended recipient,  to receive again in-game notifications. 

I expect point 2 because:
a. I searched the documentation to find out how to retrieve updates through the normal turn based APIs, as you suggest,  but I can't find them.
b. I read on another forum an answer to a similar issue,  even if related to iOS and real time games (http://stackoverflow.com/questions/27587975/not-getting-invitation-notifications-on-google-play-game-services-in-unity) which said that "There was a problem being called when the game is not running which as been addressed in the latest plugin version. This allows the registration of the delegate before calling activate, so the delegate is callable during the sign-in flow.". So I expected that I cold get updates after sign-in also in turn based.
c. The change log of version 0.9.11 says "The PlayGamesPlatform must be configured before it can be used. See PlayGamesClientConfiguration, PlayGamesPlatform.InitializeInstance, and PlayGamesClientFactory.GetPlatformPlayGamesClient." and the documentation for turn based games changed accordingly,  so I expected this reinforced what I mentioned at point b. 

At the very end,  what I really need is to have a correctly updated situation of logged user games,  even on different devices. If there are ways,  I could not find,  to retrieve updates through normal torn based APIs,  as you suggest,  please show me what they are and how to use them.
I hoped to find somewhere a method such as TurnBasedMultiplayer.loadMatchesByStatus() or a class such as LoadMatchesResponse available also in unity plugin as you can use it when programming directly in android,  but I could not find it and a similar alternative also in unity plugin would be very appreciated

**Comment by adepase** [comment]
I should add that a similar issue happens also for invitations, not only for updates to matches.

**Comment by shah0664** [comment]
i have a similar issue, i am using the sample of TicTacToss, when i invite someone sometimes its invited sometimes its not, in case when a user is invited next thing happen is; after taking turn the other player can't get any update on his/her turn, callbacks are not working.

I am new to unity and thats my first game, i am currently stuck here, kindly help me on this, thanks in advance.

**Comment by mrggl** [comment]
@shah0664, are you using the sample verbatim, or have you made changes?

In general when you invite someone, they won't actually be invited until you take a turn - that might be throwing you off.

@adepase, in internal testing we see the tictactoe sample consistently receive in-game notifications - I wonder if there's some additional issues going on with the generic sync on your device in question.

Do you see anything suspicious in the log that would indicate an issue? Is there a code-path that would allow the in-game notification to be received without running the code you expect? I'm guessing you've already put a logging statement as the first line of the callback - but worth checking if you haven't. Do your devices have a good internet connection?

@claywilkinson - have you seen anything like this while working on the samples?

**Comment by adepase** [comment]
@mrggl : I'm not using tictactoe sample directly, but I'll make test with it. 
This answer is already interesting because tictactoe sample does not strictly follow the last documentation: it is not using PlayGamesClientConfiguration, but only PlayGamesPlatform.Instance.TurnBased.RegisterMatchDelegate. However, as I told you before,  I already tried both ways, alone and combined,  without consistent success. 
Before testing tictactoe I can give you first answers:
- nothing suspicious in the log, just no life signal
- sure, I put logs on the first line of the callback, it doesn't appear in the log when it doesn't work
- Internet connection ok.  However, to eliminate  this doubt I already told I receive notifications in android,  but not in-games ones...
- the "code-path that would allow the in-game notification to be received without running the code you expect" seems to me the last thing to check and I'll do it trying the tictactoe example.

Last time you told me about "normal turn based API" to retrieve the match status, can you tell me more about this,  while I'm testing tictactoe? I already asked this to you last time,  with much more detail,  they would be very useful. 
Thank you in advance

**Comment by shah0664** [comment]
@mrggl thanks for your help, yeah i am now working on my own project and i found that after taking turn i receive the notification. So first step is done for me, thanks for your help.

**Comment by mrggl** [comment]
@adepase It seems like there might be a transient backend bug that could be causing some issues with notifications - our server team is looking into it. In the meantime, can you try this with new users (especially helpful if they're the only user on the device)? The issue might be restricted to particular accounts.

The APIs I was referring to where the UI-based ones, but those seem unlikely to help you in this case.

**Comment by adepase** [comment]
@mrggl I'll try for sure. I'm sorry I didn't follow up yet on your previous request to try with the sample tictactoss app,  but I'm working hard on a big project (not a mobile app one,  I develop mobile apps and games as an hobby), which is consuming all my day and night time (at least until end of January). Then I'll try both your hints. 
@claywilkinson why have you closed this issue? Can you please open it again?

**Comment by n8stowell82** [comment]
Are there any updates to this issue? I am unable to get any callbacks to fire on either iOS nor android.  Everything is configured but I never get a notification that it a new players turn. However if I open the invitation/current matches view, it does show the proper players turn.  I have apns cert for iOS, and logging everywhere.  Also on iOS it seems I can only select auto match, while on android I can invite any Google+ friend.

**Comment by adepase** [comment]
Sorry for the late coming back on this topic, but I could not try it any more since now for working and other life related reasons (and I write games for hobby, as I told before). I hope all of you are yet interested. (no, sorry, I hope you are no more interested, but because you already have a definitive answer, which you'll be so glad to share also with me ;) ).
I tried the TicTacToss demo app and I found it working (more or less) like mine, being the code very similar. The TicTacToss demo app, however, seemed to me a little bit more consistent and I understood why: it is also a little bit simpler than mine, working on a single scene, while I have to work with many.
So, why was it more consistent? Because the logic behind the demo code works well if you have a one-scene game. If you have many scenes, you have to remember:
1. Configuration and activation can happen just once for every run of the game, for example when starting the game.
2. Callback registration have to happen at least once for every start of every scene where you need the callback to work (pretty clear and obvious, but I had a bug and I missed a couple of point where I had to re-registrate the callbacks, according to the navigation between scenes). So, please, it's better that you all with the same issue try again to see if you also miss them.

So, it is everything well, now? NO.
Now it seems to me to have understood the working of the plugin and of the notifications, and the whole thing seems to me yet insufficient.
Starting with the understanding of the working of plugin and notifications:
1. you receive notifications in game if you are on a scene on which callbacks have been registered (see above), after correct authentication
2. if this is not the case, it is possible that:
    2a. you miss notifications: the platform send them to the game, but the game miss them (for example: not correctly registered callbacks). Let's suppose we debugged point 2a and we don't have this point
   2b: you receive notifications only in the smartphone, but not in game: this can happen, for example, if your game is not running or even if the scene has been put in pause (for example: you run the game, then you receive a phone call or switch temporary on another app or other notification and, when you are not on the scene of your game, a notification arrives; same if you play with two different login on the same device and a notification arrives for player1 when you are logged as player2).

Point 2b it's pretty common, so let's consider what can happen.
After you received the notification on the smartphone, (but not on the game), you can:
a. click the notification: in this case the platform runs the game and you can manage it to align your list of matches status and/or run the match itself. Ok, it works.
b. cancel the notification(s): in this case you have a completely unaligned list of matches status and I cannot see how to recover from this situation.
c. continue with your game without considering the notifications: in this case you have a completely unaligned list of matches status in the game, at least until you don't come back to points a or b.

I understand that this could be the intended behavior of the Unity plugin, but it's also clear that this is not the intended behavior of the Google Play Games platform itself (I'll come back on this in a while) and, given that this can lead to uncontrollable (definitive or temporary, it doesn't matter, they are not understandable for the player) inconsistencies in self developed list of matches status, in my personal point of view this should be changed, because it is a serious lack in the definition of the plugin with respect to the platform itself.

In fact, as I mentioned before, this could be corrected, for example, by implementing also in the plugin the method TurnBasedMultiplayer.loadMatchesByStatus() we can find, for example, in Android API. Using this method you can workaround the callbacks, the notifications and all this stuff and always have a coherent list of matches status.

Obviously, this can change the issue from a bug notification to a nice to have request, because these are not inconsistencies in the backend server, nor are bugs in the current development status, but it is also pretty clear that these are inconsistencies in the plugin design, with respect to the overall platform design, if I understood them correctly.

However, as always, I kindly ask you if there are workarounds I could not find that I can follow to overcome the fragility of the current plugin implementation (at least if I understood it correctly and completely).
But please, it would very much better if you could also develop in the plugin the loadMatchesByStatus method.

Thank you again

**Comment by adepase** [comment]
@claywilkinson : resolved in #414, so I close this, even if the solution is not yet in the official code (hoping it will be soon)

**Comment by AmitApolloBarman** [comment]
Okay I have a slight problem with the Plugin now. The Match Delegate works perfectly, except when you're outside of said app in the iOS Springboard. You can click on the notification it's fine and processes the match delegate callback, that does work! However when you DON'T click on the notification and go back to the app via task manager or clicking on your app icon it gets lost until you click the notification.  This is problematic when you're outside of the app, and simply try to go back into the same scene and are expecting data. I'm going to have to boot user to a different scene when scene goes to background.
