### ISSUE TITLE
FR: provide way to inhibit achievement popups

### ISSUE THREAD

**Issue by noolness** [playgameservices/play-games-plugin-for-unity#35]
I have my own custom achievement dialogs that come up, and I want to disable the ones this library pops up. If I can't do that, I would want to be able to use something like setGravityForPopups, so they can be shown on the bottom of the screen. I don't want them to be shown at the top of the screen because that would negatively impact gameplay. Is there any way that could be done or any way it could be added?

**Comment by claywilkinson** [comment]
This feature was added in 0.9.37
