### ISSUE TITLE
Can only invite 'recent players' on iOS 

### ISSUE THREAD

**Issue by ZenithCode** [playgameservices/play-games-plugin-for-unity#353]
When you create a game with invitation screen on iOS you only get to see the people who recently played your game.  Is there anyway we can get to see all the people in your circles like in Android builds?

Thanks.

**Comment by ZenithCode** [comment]
On Android you get:
1. Recently played
2. Active players
3. Anyone in your circles
![android](https://cloud.githubusercontent.com/assets/1938034/5683769/e82fdd66-982a-11e4-8024-d47160d91dfe.png)

On iOS you just get the recent users.
![ios](https://cloud.githubusercontent.com/assets/1938034/5683770/e831a5c4-982a-11e4-89ef-ba0b741eb63b.jpg)

**Comment by claywilkinson** [comment]
tracking internally as 19143526

**Comment by claywilkinson** [comment]
@ZenithCode  - I posted a response on the http://stackoverflow.com/questions/27843608/google-play-services-unity-can-only-invite-recent-players-on-ios posting  since it is a more general question vs. and issue with the plugin.

**Comment by ZenithCode** [comment]
Thank you @claywilkinson
