### ISSUE TITLE
0.9.11 build errors out of the box

### ISSUE THREAD

**Issue by syeager** [playgameservices/play-games-plugin-for-unity#354]
I tried updating to the newest build and got these errors.

- Assets/GooglePlayGames/Platforms/Android/AndroidClient.cs(560,44): error CS0246: The type or namespace name `BufferEncrypter' could not be found. Are you missing a using directive or an assembly reference?
- Assets/GooglePlayGames/Platforms/Android/AndroidClient.cs(27,18): error CS0738: `GooglePlayGames.Android.AndroidClient' does not implement interface member `GooglePlayGames.BasicApi.IPlayGamesClient.GetUserImageUrl()' and the best implementing candidate `GooglePlayGames.Android.AndroidClient.Authenticate(System.Action<bool>, bool)' return type `void' does not match interface member return type `string'
- Assets/GooglePlayGames/Platforms/Android/AndroidClient.cs(27,18): error CS0738: `GooglePlayGames.Android.AndroidClient' does not implement interface member `GooglePlayGames.BasicApi.IPlayGamesClient.GetSavedGameClient()' and the best implementing candidate `GooglePlayGames.Android.AndroidClient.IsAuthenticated()' return type `bool' does not match interface member return type `GooglePlayGames.BasicApi.SavedGame.ISavedGameClient'

**Comment by ZenithCode** [comment]
I think you need to clean up some of the files from the previous version.  0.9.11 does not include an 'AndroidClient.cs' file so I think you can safely remove all references to that one.

**Comment by syeager** [comment]
You are correct. Thank you for your help.
