### ISSUE TITLE
XCode Build Error: GooglePlayGames.h

### ISSUE THREAD

**Issue by miracle7** [playgameservices/play-games-plugin-for-unity#355]
Hello,

I have repeatedly and carefully followed all the steps listed to setup XCode to compile my project, but it seems no matter what I do I get this error :(

![screen shot 2015-01-10 at 2 44 13 pm](https://cloud.githubusercontent.com/assets/5317556/5690347/40716a38-98d7-11e4-8ee5-db7aecedbaf4.png)

I have tried restarting computer many times, fresh installs of Unity, fresh installs of the play games plugin, redownloading sdks but with no luck.

Please help, I am really stuck and would love to get this working so I can continue development.

**Comment by abalta** [comment]
You try add header files for plugin directory in your project. In Build Settings -> Header Search Path add header files directory.

**Comment by miracle7** [comment]
Thanks for your help, while investigating what you told me to do I realised that it was a bit strange that it was looking for GooglePlayGames rather than the more modern GPG stuff.

I deleted all folders that the .unitypackage adds then reimported the .unitypackage and it seems to stop complaining about this. So must have left behind some files during upgrade or something...

Unfortunately since I delete the shared plugin folders and stuff some other stuff has now died, but at least  GPG seems to be working :)
