### ISSUE TITLE
Sign in issue with 0.9.11 on Android

### ISSUE THREAD

**Issue by vanustwo** [playgameservices/play-games-plugin-for-unity#357]
The callback for Authenticate return straight away when the user is presented with selecting a Google play account.

Social.localUser.Authenticate((bool success) =>
{
 Debug.Log("ANDROID  SignIn " + success);				
});

Steps.
1. Have multiple Google Play account on device.
2. Call Social.localUser.Authenticate.
3. Notice that the debug log is called straight away even if the user does not select any button on the Google Play Games prompt screen.

**Comment by rahdical** [comment]
I was having the same issue. Did you add the email(s) to your tester's list in the google play developer console? Under  - Game Services > Your Game > Testing

**Comment by vanustwo** [comment]
Yes, all my Google play accounts are test users. Older version of the plugin is working fine

**Comment by claywilkinson** [comment]
Can you provide the log contents? Maybe that will help figure out what is going on.

**Comment by kyubuns** [comment]
I have the same issue.
I tried 0.9.11 only, please tell me a version that has no problems.

**Comment by domino1011** [comment]
I have the same issue. Android 5.0.1, unity 4.6. Plugin version 0.9.11 The logs:
```
I/GamesNativeSDK(17116): Auth operation started: SIGN IN
I/GamesNativeSDK(17116): Connecting to Google Play...
D/AppStateService( 1936): client connected with version: 6587000 
// some other stuff
E/Volley  ( 1936): [190] a.a: Unexpected response code 403 for https://www.googleapis.com/drive/v2beta/apps/self?prettyPrint=false
E/ClientConnectionOperation( 1936): Handling authorization failure
E/ClientConnectionOperation( 1936): com.google.android.gms.drive.auth.c: Authorization failed: server returned error: Access Not Configured. The API (Drive API) is not enabled for your project. Please use the Google Developers Console to update your configuration.. See https://developers.google.com/drive/handle-errors for details.
E/ClientConnectionOperation( 1936): 	at com.google.android.gms.drive.auth.f.a(SourceFile:173)
E/ClientConnectionOperation( 1936): 	at com.google.android.gms.drive.auth.f.a(SourceFile:133)
E/ClientConnectionOperation( 1936): 	at com.google.android.gms.drive.api.e.<init>(SourceFile:205)
E/ClientConnectionOperation( 1936): 	at com.google.android.gms.drive.api.a.j.a(SourceFile:36)
E/ClientConnectionOperation( 1936): 	at com.google.android.gms.common.service.c.onHandleIntent(SourceFile:60)
E/ClientConnectionOperation( 1936): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/ClientConnectionOperation( 1936): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ClientConnectionOperation( 1936): 	at android.os.Looper.loop(Looper.java:155)
E/ClientConnectionOperation( 1936): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

there seems to be retry after this. I do have proper test accounts configured. Previously I used 0.9.07 plugin version and it worked correctly (apart from crashing from time to time on leaderboard).

Also first (clean) and following launches of the application look differently:
1. The green google play services 'screen' is shown during application startup, there is animation on it as always, application starts normally.
2. From time to time: no gps screen, application waits to launch, it looks like empty activity with title and almost gray background and no fullscreen mode. It waits like that for few seconds, then it goes fullscreen and unity kicks in.
3. in other cases, no gps screen, application starts normally.

**Comment by claywilkinson** [comment]
From the log this line seems to indicate that saved games is not enabled for your game.  

    E/ClientConnectionOperation( 1936): com.google.android.gms.drive.auth.c: Authorization failed: server returned error: Access Not Configured. The API (Drive API) is not enabled for your project. Please use the Google Developers Console to update your configuration.. See https://developers.google.com/drive/handle-errors for details.

There are steps to do this on: https://developers.google.com/games/services/console/configuring#enabling_saved_games

**Comment by kyubuns** [comment]
> There are steps to do this on: 
> https://developers.google.com/games/services/console/configuring#enabling_saved_games

I try this, but happend error.

```
E/SignInIntentService( 3098): Access Not Configured. The API (Google Play Game Services API) is not enabled for your project. Please use the Google Developers Console to update your configuration.
E/SignInIntentService( 3098): com.google.android.gms.games.h.c.a
E/SignInIntentService( 3098): 	at com.google.android.gms.games.h.b.a(SourceFile:153)
E/SignInIntentService( 3098): 	at com.google.android.gms.games.a.bj.d(SourceFile:1682)
E/SignInIntentService( 3098): 	at com.google.android.gms.games.a.bj.b(SourceFile:608)
E/SignInIntentService( 3098): 	at com.google.android.gms.games.a.bj.b(SourceFile:585)
E/SignInIntentService( 3098): 	at com.google.android.gms.games.a.t.d(SourceFile:822)
E/SignInIntentService( 3098): 	at com.google.android.gms.games.service.w.b(SourceFile:349)
E/SignInIntentService( 3098): 	at com.google.android.gms.games.service.s.a(SourceFile:47)
E/SignInIntentService( 3098): 	at com.google.android.gms.games.service.GamesSignInIntentService.onHandleIntent(SourceFile:501)
E/SignInIntentService( 3098): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/SignInIntentService( 3098): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/SignInIntentService( 3098): 	at android.os.Looper.loop(Looper.java:136)
E/SignInIntentService( 3098): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/LoadSelfFragment(29039): Unable to sign in - application does not have a registered client ID
W/SignInActivity(29039): onSignInFailed()...
W/SignInActivity(29039): ==> Returning non-OK result: 10004
V/GamesNativeSDK(28867): Received Activity Resume Event.
```

**Comment by kyubuns** [comment]
thank you!

**Comment by CarpetHead** [comment]
I have the same issue. Here are the logs:


    02-09 18:49:20.766: I/Unity(16680):  [Play Games Plugin DLL] 02/09/15 18:49:20 +00:00 DEBUG: Creating platform-specific Play Games client.
    02-09 18:49:20.767: I/Unity(16680):  [Play Games Plugin DLL] 02/09/15 18:49:20 +00:00 DEBUG: Creating real IPlayGamesClient
    02-09 18:49:20.776: D/GamesUnitySDK(16680): Performing Android initialization of the GPG SDK
    02-09 18:49:20.994: I/Unity(16680):  [Play Games Plugin DLL] 02/09/15 18:49:20 +00:00 DEBUG: Entering state: BeforeRoomCreateStartedState
    02-09 18:49:20.996: I/Unity(16680):  [Play Games Plugin DLL] 02/09/15 18:49:20 +00:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
    02-09 18:49:20.996: I/Unity(16680):  [Play Games Plugin DLL] 02/09/15 18:49:20 +00:00 DEBUG: Entering state: ShutdownState
    02-09 18:49:20.996: I/Unity(16680):  [Play Games Plugin DLL] 02/09/15 18:49:20 +00:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
    02-09 18:49:21.112: I/Unity(16680):  [Play Games Plugin DLL] 02/09/15 18:49:21 +00:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
    02-09 18:49:21.169: I/Unity(16680):  [Play Games Plugin DLL] 02/09/15 18:49:21 +00:00 DEBUG: Invoking user callback on game thread

    02-09 18:49:21.173: I/Unity(16680): authenticate fail

AUTHENTICATION CALLBACK WITH SUCCESS = FALSE ^

Screenshot: http://gyazo.com/d6ce883b413042bef650c4131c023105

    02-09 18:49:21.227: I/Unity(16680):  [Play Games Plugin DLL] 02/09/15 18:49:21 +00:00 DEBUG: PlayGamesHelperObject.OnApplicationPause True
    02-09 18:49:21.322: I/Unity(16680):  [Play Games Plugin DLL] 02/09/15 18:49:21 +00:00 DEBUG: PlayGamesHelperObject.OnApplicationFocus False
    02-09 18:50:24.513: I/Unity(16680):  [Play Games Plugin DLL] 02/09/15 18:50:24 +00:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED

**Comment by claywilkinson** [comment]
@CarpetHead  - did you enable saved games in the console?  Are you still having issues?

**Comment by domino1011** [comment]
Ok, this might had beed an issue. I updated to 0.9.12 and it works fine. I checked the dev console and the saved games are enabled there however I cannot tell if this was true for the report above. Anyway, 0.9.12 works correctly as long as you won't use achievements ui,

**Comment by claywilkinson** [comment]
Sounds like this issue is closable?
