### ISSUE TITLE
Build rejected by Apple

### ISSUE THREAD

**Issue by ekiyanov** [playgameservices/play-games-plugin-for-unity#359]
Hi.

Today i receive reject for my game for "wrong auth process"

    10.6: Apple and our customers place a high value on simple, refined, creative, well thought through interfaces. They take more work but are worth it. Apple sets a high bar. If your user interface is complex or less than very good, it may be rejected

----- 10.6 -----

We found the following issue with the user interface of your app:

The app opens a web page in mobile Safari for creating an account for or logging into the Google leaderboard, then returns the user to the app. The user should be able to create an account or log in inside the app without opening Safari first.

This example identifies an issue discovered in your app. It would be appropriate to thoroughly evaluate your app to address this issue.

* * * *

How can i change auth process to use internal web controller instead of opening mobile safari ?

**Comment by blackrainbowgames** [comment]
Had the same review and passed second review with this. Reply that you can't replace 3-party component and maybe you'll be lucky.

**Comment by NaxIonz** [comment]
@blackrainbowgames 
So, you also got rejected by Apple for the exact same issue (redirect to Safari)??

**Comment by blackrainbowgames** [comment]
Yes, then appealed successfully. Just try to describe your situation. Do not talk about crossplatform, Android and Game Center.

**Comment by blackrainbowgames** [comment]
@NaxIonz Yes, then appealed successfully. Just try to describe your situation. Do not talk about crossplatform, Android and Game Center.

**Comment by ekiyanov** [comment]
rejected in second time

**Comment by adrianogil** [comment]
Also rejected! After I claimed that's a behaviour of a 3rd-party component, I received that answer:

"Hello,

Thank you for your response. Though we understand that you are using another service for leaderboards and achievements, it is not appropriate for the user to have to exit the app to sign in.

It would be advisable to change the login to be a web view within the app or to utilize Game Center elements like leaderboards and achievements for your app.

We look forward to reviewing the revised version of your app.

Best Regards,

App Store Review"

**Comment by hippogamesunity** [comment]
@adrianogil So you have to use Game Center. You are lucky that Unity supports achievements and leaderboards from the box.

**Comment by adrianogil** [comment]
@hippogamesunity I don't consider myself luck in anyway. My team discarded our custom cross-platform solution in favor of GPG plugin. We had just wasted our time! I think the risk of not being accepted by Apple should be mentioned in the readme file.

**Comment by MofoMan2000** [comment]
It looks as though using Webviews for the sign-in flow is being worked on at the moment, hopefully it is completed soon. In the meantime there is a hacktastic "solution" in the duplicate issue #148

**Comment by claywilkinson** [comment]
The plugin uses Google SignIn API now (version 0.9.25), which is acceptable to Apple.

**Comment by hippogamesunity** [comment]
Thanks!
