### ISSUE TITLE
Incremental achievements and game save / load

### ISSUE THREAD

**Issue by blackrainbowgames** [playgameservices/play-games-plugin-for-unity#360]
Hi! How to prevent repeated achievement increment when the game was loaded from early state or reseted?
For example:
- player reaches level 1 and increments level achievement
- player performs game reset or loads from early state (he has level 0 again)
- player reaches level 1 again and increments level achievement second time
- now he has level 1 in the game and level 2 in level achievement

**Comment by samtstern** [comment]
If you are concerned about this you will have to manage this with in-game logic.  You could query the value of the achievement before incrementing it to a higher level to make sure it is right.

Closing because this is not an issue with the Unity plugin.

**Comment by blackrainbowgames** [comment]
I can't do this because it is not implemented in 0.9.11
