### ISSUE TITLE
Change Social.localUser.image when change account

### ISSUE THREAD

**Issue by namquang93** [playgameservices/play-games-plugin-for-unity#361]
I have added Google Play Game Services into my game. But there seems a problem, when I logout the current Google account and sign in with a different account, the avatar stored in Social.localUser.image does not change. It's still the old account's avatar. Did I missed anything or it's a known issue of Google Play official plugin. My SignOut is just one line code:

 ((GooglePlayGames.PlayGamesPlatform) Social.Active).SignOut();

**Comment by claywilkinson** [comment]
Fixed in 0.9.15
