### ISSUE TITLE
Completely removing plugin

### ISSUE THREAD

**Issue by abalta** [playgameservices/play-games-plugin-for-unity#364]
Hi, I seperate Unity Project iOS and Android, I want to complete remove plugin files? How can I to do this?

**Comment by NaxIonz** [comment]
I would like to know how to remove the iOS information as well.

Given the post here :
https://github.com/playgameservices/play-games-plugin-for-unity/issues/359

I don't want to risk our games getting rejected by Apple. Therefore, I want to make sure I remove all the necessary files that could impact my iOS build.

**Comment by ekiyanov** [comment]
Apple reject app in second time. How can i remove Google play games from iOS build but keep android ?

**Comment by abalta** [comment]
I completely remove Google Play Games folder on my project and then submitted app accepted.

**Comment by claywilkinson** [comment]
Version 0.9.15 allows excluding the plugin services for an iOS build.  The README contains the instructions.
