### ISSUE TITLE
Detected incorrect implementation

### ISSUE THREAD

**Issue by JEOptimal** [playgameservices/play-games-plugin-for-unity#365]
"Detected incorrect implementation
Your game has incorrectly implemented the following Play Games services: Achievements."

Why have we received this notification on our google play account for two of our games? They have been up and running with 1+ million users without any issues. We use an older version of this plugin, but we only use achievements and highscores.

Do we need to update to the latest version? Or is there any specific reason that this is shown? We're very reluctant to update as there seems to be a huge number of issues with the current version...

**Comment by hex** [comment]
+1

I received the same thing in Developer Console

**Comment by claywilkinson** [comment]
Thanks for the details - I passed along your information  internally as issue 19045821

**Comment by LoungeKatt** [comment]
I am glad to see it wasn't something I had done. I received the same notice. I am using the newest version of the plugin and GPG, no custom configuration, and only have achievements that are all one-time unlocks using ```Social.ReportProgress("ACHIEVEMENT_ID", 100.0f, (bool success) => { });``` with no internal code once they are unlocked. Hopefully the added details may help rule out some causes.

**Comment by defensezone** [comment]
I got the same message to all applications.
I used to achieve and leaderboard.

Does anyone know how to solve this problem?
Someone asked in support of Google on this issue?

**Comment by gameyug** [comment]
Same issue facing in account with this Alert. Hopefully it won't negative affect in our account.

**Comment by claywilkinson** [comment]
This should be resolved now, it was a problem with the scanning of the application.

**Comment by defensezone** [comment]
Now I do not have this warning in the Developer Dashboard Google
