### ISSUE TITLE
Google Play Game Services - Unable to sign out

### ISSUE THREAD

**Issue by dcaso** [playgameservices/play-games-plugin-for-unity#366]
Hello,

In order to keep compliant with Google recommendation while using Google Play Game Services, I've integrated a sign out button in my game.

When I test it, I get the following error message in the console (from qdb logcat)

Starting Auth Transition. op: SIGN_OUT status: ERROR_NOT_AUTHORIZED

I cannot figure out what I am missing... When I active the sign out function from my button, I'm 100% sure of being connected to GPGS

Thanks for your help

**Comment by blackrainbowgames** [comment]
Got the same proplem when sign in (sometimes, rare).

**Comment by claywilkinson** [comment]
This is usually caused by using an account that is not a tester.  Could that be the case?

**Comment by dcaso** [comment]
I was connected with a tester account. For a reason I cannot explain, 24 hours later it was working perfectly without any source code modification...

**Comment by claywilkinson** [comment]
Glad to hear it is working  Buried in the documentation:  https://developers.google.com/games/services/console/configuring#enabling_saved_games

After performing the steps above, it may take up to **24 hours** for Play Game services to activate the Saved Games feature for your game. If you want to test the Saved Games feature immediately, manually clear the data in the Google Play Services app installed on your test device.
