### ISSUE TITLE
ANR on app quit

### ISSUE THREAD

**Issue by blackrainbowgames** [playgameservices/play-games-plugin-for-unity#367]
Hi! Got ANR on app quit if user opens achievements or leaderboards in game session. Have got no exception if user just signs in.

**Comment by blackrainbowgames** [comment]
I found repeated record in log before ANR:
Trying to load lib /data/app-lob/com.XXX-1/libgpg.so - maybe it is a problem

If user does not use game services then app can quit ok.

**Comment by claywilkinson** [comment]
Could this be the same issue as #310 ?

**Comment by blackrainbowgames** [comment]
Maybe, closed
