### ISSUE TITLE
Is there any way to use this plugin in unity3d editor without building?

### ISSUE THREAD

**Issue by darekzak** [playgameservices/play-games-plugin-for-unity#368]
Do i have to always build e.g for andorid and put APK in my phone or is there any way for quick testing in unity editor?

**Comment by abalta** [comment]
I think Android Side is easy for testing, think about iOS side, build Unity, build Xcode :)

**Comment by darekzak** [comment]
But still, every time building APK file, and putting it on android device to see that your code doesn't work(without any clue) is inconvenient.

**Comment by claywilkinson** [comment]
Unfortunately there is no way to test the play game services in the editor.  This would require GPGS to support the editor platform(s) (windows, mac).  One idea might be to add some testing code to your project that would be inside  and ifdef block so it can return test values when you are in the editor, something like:

                    Social.localUser.Authenticate((bool success) => {
                    #ifdef UNITY_EDITOR
                           // simulate successful login when in the editor......
                            success = true;
                    #endif

                        if (success) {
                          mStatusText = "Welcome " + Social.localUser.userName;
                        } else {
                          mStatusText = "Authentication failed.";
                        }
                });
