### ISSUE TITLE
AchievementsUI crashing on getLocationInWindow [NullPointerException]

### ISSUE THREAD

**Issue by rdaros** [playgameservices/play-games-plugin-for-unity#369]
In a very standard implementation, similar to the sample codes, everything works well: user authentication, auto sign-in after user has already signed in once, simple achievements and incremental achievements. The problem is when I call the 'Social.ShowAchievementsUI()' function.

It works <b>sometimes</b>, but most of the times it causes Google Play Services to crash. The app still continues to run just fine after this crash, but without any Play Services functionality.

Logcat gives me the crash reason:

```
E/AndroidRuntime(8045): FATAL EXCEPTION: main
E/AndroidRuntime(8045): Process: com.google.android.gms.ui, PID: 8045
E/AndroidRuntime(8045): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.getLocationInWindow(int[])' on a null object reference
```

The crash only happens on the first time I call the achievementsUI function in a session. If it doesn't crash on the first call (very rare), any other future calls in the same session will work fine.

The code is simple:
```c#
	public void showAchievements () {
		if (Social.localUser.authenticated) 
			Social.ShowAchievementsUI();
		}
```

I spent hours debugging and trying to fix it without success. I'm testing on a Nexus 5 with Lollipop 5.0.1. Tomorrow I'll try on a Galaxy Nexus with 4.4.4 and on a Nexus One with 2.3.6 I believe. I'll post the results. 

Any ideas on what I could be doing wrong? Or is it something with the plugin?

Thanks!

**Comment by codezyabra** [comment]
Hmm, can it be related to this bug: https://github.com/playgameservices/play-games-plugin-for-unity/issues/303 ?

**Comment by rdaros** [comment]
@codezyabra , you are right. The description in bug #303 looks very much alike my issue. I just wonder if the fix announced by @ToddKerpelman was already released in the last update. If so, the bug still persisted since I'm using the latest build.

**Comment by rdaros** [comment]
Ok, I've tested on two more devices. Here are the results:

Nexus One, Android 4.1.2, GPS 6.5.99, Google Play Games not installed
Result: Everything worked, I was unable to reproduce the bug.

Galaxy Nexus, Android 4.4.4, GPS 6.5.99, Google Play Games not installed
Result: Same problem, crashed Google Play Services as soon as its background showed up.

I hope it helps.

**Comment by claywilkinson** [comment]
Thanks for the details -  since it is the same issue as #303, I am consolidating this thread into that one.
