### ISSUE TITLE
GPG PLUGIN 0.9.11 Freeze On Quit Application&&//User Do Not Stay Logged In

### ISSUE THREAD

**Issue by simsis3d** [playgameservices/play-games-plugin-for-unity#370]
PROBLEM 1: I am using unity 4.6.1(Latest one) with google Admob plugin and google play services plugin(I use only login/logout feature of the plugin for now) .The problem is the following. When I run my game on android and play return button, game freezes for around 10 seconds and then exit. However, when I disable login/logout, it exits as it should be. Some guys on forums talks about Admob for this problem, but Admob is so good so far and seems not causing this. The problem seems to be caused by login/logout. Any help?

edit: When you never login in the game, the freeze problem doesnt appear. However, once you logged in and then logged out, it freezes on exit.

PROBLEM 2: When user logged in once and quit the application and come back again, user seems to be logged out.

PLEASE FIX ISSUES.

**Comment by claywilkinson** [comment]
Can you post the logs during these issues?  Tracking internally as 19144603

**Comment by simsis3d** [comment]
@claywilkinson Logcat throws me millions of lines even I click a simple button in game. Could you please tell me how to filter necessary data which you are looking for? "adb logcat -s Unity ActivityManager PackageManager dalvikvm DEBUG" is enough for you?

**Comment by rdaros** [comment]
Hakan, this may not be related to your problem, but when I had this issue I
fixed it by removing ProxyActivity from the manifest. Maybe you should give
it a shot.

Just move the intent-filter below into the application UnityPlayerActivity
tag:

<intent-filter>
<action
<http://unity3d.com/support/documentation/ScriptReference/30_search.html?q=action>
 android:name
<http://unity3d.com/support/documentation/ScriptReference/30_search.html?q=name>
="android.intent.action.MAIN" />
<category android:name
<http://unity3d.com/support/documentation/ScriptReference/30_search.html?q=name>
="android.intent.category.LAUNCHER" />
</intent-filter>

then remove the ProxyPlayerActivity tag altogether from the manifest. This
issue usually happens when using the Admob plugin. I hope it helps.

**Comment by simsis3d** [comment]
Thanks @rdaros I did exactly what you said. At first, I thought it fixed because there was no freezing On Application Quit. After that, I realized this time there is exact same problem(Fckng Freezing!!) On Application Start. The problem is transformed: When you never login, it is okay both on start and on quit, However once user login and quit, application freezes on start. Anyway, thanks bro. I think I should share code and logs

**Comment by simsis3d** [comment]
That is exact code I use for testing

using UnityEngine;
using System.Collections;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;
using UnityEngine.UI;

public class GoogleLoginout : MonoBehaviour {

	public Text logInOutText;

	void Awake ()
	{
		PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
		.Build();
		
		PlayGamesPlatform.InitializeInstance(config);
		// recommended for debugging:
		PlayGamesPlatform.DebugLogEnabled = true;
		// Activate the Google Play Games platform
		PlayGamesPlatform.Activate();
	}

	void Start () 
	{
		if (PlayGamesPlatform.Instance.IsAuthenticated ()) 
		{
			logInOutText.text = "Logout";
		}
		else
		{
			logInOutText.text = "Login";
		}
	}
	


	public void LogInOut ()
	{
		if(PlayGamesPlatform.Instance.IsAuthenticated())
		{
			PlayGamesPlatform.Instance.SignOut();
			logInOutText.text = "Login";
		}
		else
		{
			Social.localUser.Authenticate((bool success) => {
				// handle success or failure
				if(success == true)
				{
					logInOutText.text = "Logout";
				}
				else
				{
					logInOutText.text = "Login";
				}
			});
		}
	}

	public void Exit ()
	{
		Application.Quit ();
	}
}

**Comment by CarlosPerson** [comment]
We ended up giving up this plugin and using facebook

**Comment by simsis3d** [comment]
Please look at these issues also. https://github.com/playgameservices/play-games-plugin-for-unity/issues/310 and https://github.com/playgameservices/play-games-plugin-for-unity/issues/313  They may be a clue together with my issue.I hope.

**Comment by rdaros** [comment]
Strange, sorry my suggestion did not help. I will keep looking for a good
answer to this problem, since it affects me as well. Good luck Hakan.

**Comment by simsis3d** [comment]
for whom face same problems, I downgraded to version 0.9.7 and it works properly so far. But if you need save game property, you have nothing to do except waiting for an update.

**Comment by spotavi** [comment]
Where can i find the 0.9.7 sample files ? Can someone share please.

The Sample files seems to be upgraded to the new API. 0.9.11 has bugs :(

**Comment by divereth** [comment]
Is this fixed in 0.9.12?

**Comment by simsis3d** [comment]
@spotavi unfortunately I dont have, but I am pretty sure that moderators may help you.
@divereth I dont think so, nothing changed but sample files are packaged in that version. (Not sure)

**Comment by divereth** [comment]
I suspect this being a reason for my game failing to run for some users. Is this possible?

**Comment by btd777** [comment]
@divereth 0.9.12 - I have freeze on Exit as before.

**Comment by claywilkinson** [comment]
Can you post a log file when this happens?  The categories of interest are GamesNativeSDK:* GameAgent:* CheckGameplayAcl:* Unity:* ActivityManager:* PackageManager:*

**Comment by btd777** [comment]
Thank you. Here it is:
First try: https://www.dropbox.com/s/w7lk6enoli23t81/LongExit.txt?dl=0
Second try: https://www.dropbox.com/s/sjxuzeypxhpud4p/LongExit2.txt?dl=0

**Comment by claywilkinson** [comment]
Thanks for the logs.  What version of Android are you testing on?  This sounds like an old NDK bug...

**Comment by btd777** [comment]
The minimal version was Android 4.0.4,  the maximum version - 4.4.4. Freeze on exit on both versions.

**Comment by claywilkinson** [comment]
Believe this is fixed in 0.9.37
