### ISSUE TITLE
Unable to reshow Achievement or Leaderboard UI after Home button is pressed

### ISSUE THREAD

**Issue by epzin** [playgameservices/play-games-plugin-for-unity#371]
This problem happens after having called ShowAchievementsUI() and the activity has already been brought up displaying achievements.  When I then press the Home button, then immediately start my game again, the achievements UI will have been lost (all I see is my game in the state it was when I pressed the home button).  However, any new calls to ShowAchievementsUI() will then fail, showing this in the log:

```
GamesNativeSDK: Trying to show UI while waiting for a result from an existing UI. Please ensure that OnActivityResult is forwarded to the Games C++ SDK from your Java activity. See android_support.h for more details.
```

Does that mean the achievements UI activity is still active in some way?  If so, how can I possibly stop it and start a new instance of it through this API?

**Comment by tyashushi** [comment]
Hi there,
I believe that I found the same issue with ShowLeaderboardUI() and ShowAchievementsUI() that can be reproducible as follows;

1. Call ShowLeaderboardUI() and show the leaderboard.
2. Press Home button and suspend the application.
3. Resume the application (and the leaderboard has been disappeared).
4. Call ShowLeaderboardUI() again but leaderboard never show up.

This problem occurs on some devices I've tested.

Log:
02-25 15:42:07.843: I/Unity(20185):  [Play Games Plugin DLL] 02/25/15 15:42:07 +09:00 DEBUG: ShowAchievementsUI
02-25 15:42:07.843: I/Unity(20185):  
02-25 15:42:07.843: I/Unity(20185): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
02-25 15:42:07.870: D/AppStateService(22357): client connected with version: 6587000
02-25 15:42:07.981: D/PowerManagerNotifier(990): onWakeLockAcquired: flags=1, tag="AlarmManager", ownerUid=1000, ownerPid=990, workSource={WorkSource: uids=[10216]}
02-25 15:42:07.985: D/PowerManagerNotifier(990): onWakeLockReleased: flags=1, tag="AlarmManager", ownerUid=1000, ownerPid=990, workSource={WorkSource: uids=[10216]}
02-25 15:42:08.001: V/GamesNativeSDK(20185): Play Games callback indicates connection.
02-25 15:42:08.009: I/GamesNativeSDK(20185): Successfully connected to Google Play.
02-25 15:42:08.011: E/GamesNativeSDK(20185): Trying to show UI while waiting for a result from an existing UI. Please ensure that OnActivityResult is forwarded to the Games C++ SDK from your Java activity. See android_support.h for more details.
02-25 15:42:08.012: I/Unity(20185):  [Play Games Plugin DLL] 02/25/15 15:42:08 +09:00 DEBUG: Showing UI Internal callback: ERROR_UI_BUSY
02-25 15:42:08.012: I/Unity(20185):  
02-25 15:42:08.012: I/Unity(20185): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
02-25 15:42:08.013: I/Unity(20185):  [Play Games Plugin DLL] 02/25/15 15:42:08 +09:00 DEBUG: Received UI callback: ERROR_UI_BUSY
02-25 15:42:08.013: I/Unity(20185):  
02-25 15:42:08.013: I/Unity(20185): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)

**Comment by claywilkinson** [comment]
Version 0.9.15 fixes this.
