### ISSUE TITLE
Feature Request: Have the user's access token be accessible

### ISSUE THREAD

**Issue by seaders** [playgameservices/play-games-plugin-for-unity#373]
Specifically the one required by Amazon for their signing in, https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/cognito-auth.html#google-integration / https://docs.aws.amazon.com/mobile/sdkforios/developerguide/cognito-auth.html#google-integration

I currently have this code in my own plugin, after successful signin (for Android), but it would be great if this were available directly with this plugin,

(Android)

    AccountManager am = AccountManager.get(this);
    Account[] accounts = am.getAccountsByType(GoogleAuthUtil.GOOGLE_ACCOUNT_TYPE);
    String token = GoogleAuthUtil.getToken(getApplicationContext(), accounts[0].name, "audience:server:client_id:YOUR_GOOGLE_CLIENT_ID");

(iOS)

    - (void)finishedWithAuth: (GTMOAuth2Authentication *)auth error: (NSError *) error {
        NSString *idToken = [auth.parameters objectForKey:@"id_token"];
    }

**Comment by claywilkinson** [comment]
Same request as #10,  tracking internally as 19126504

**Comment by claywilkinson** [comment]
Done!
