### ISSUE TITLE
Is GPG for Unity dead?

### ISSUE THREAD

**Issue by ZenithCode** [playgameservices/play-games-plugin-for-unity#374]
I've seen a lot of critical issues listed here and in other forums (Unity and StackOverflow) along with some of my own (links below) which are still unanswered or unresolved.  

Does Google have a dedicated team for this? 
Will there be any more support for this?

We've invested heavily in making our multiplayer game use this framework but we can't go live before some of these bugs are fixed.

https://github.com/playgameservices/play-games-plugin-for-unity/issues/299
https://github.com/playgameservices/play-games-plugin-for-unity/issues/326
https://github.com/playgameservices/play-games-plugin-for-unity/issues/351
https://github.com/playgameservices/play-games-plugin-for-unity/issues/353

My hope is that there is a support team and they're busy working on version 1.0.0 instead of answering queries here ;-) A confirmation would be nice though!

**Comment by simsis3d** [comment]
Totally agree. My problem(s) which are described here(https://github.com/playgameservices/play-games-plugin-for-unity/issues/370) are still waiting for an answer. GPG 0.9.11 is completely wrong implemented!

**Comment by aggsol** [comment]
We switched to a commercial plugin because of the state here but it is not a lot better. There is at least a business interest to have a working Google Play Plugin for Unity.

**Comment by janisc** [comment]
Are there any good alternative implementations available for Unity? Commercial or otherwise. Preferably with similar Unity Social interface implementation. Using only authentication and leaderboards at the moment,

**Comment by samtstern** [comment]
Don't worry, this plug-in is still very much under active development.  While the Github may have been quieter than normal, we are working internally on fixing the bugs and adding features.  I am going to close this issue as it's more of a 'discussion', but please continue to file your bugs and feedback, we will get to everything as soon as we can.

**Comment by ZenithCode** [comment]
Thanks @samtstern

**Comment by hthetiot** [comment]
Thanks @samtstern for the update.

**Comment by TycEkart** [comment]
cheers @samtstern is there an ETA available for the next build (days, weeks, months?)

**Comment by ZenithCode** [comment]
@samtstern Its been a few weeks (close to 2 months) since the latest update with fixes (0.9.11) - Can you give us an ETA when a new update will be made available?

**Comment by samtstern** [comment]
@ZenithCode 
0.9.12 was released 27 days ago.  Although it still has some outstanding issues, I have found it to be pretty stable in my personal use.

We are working hard on Unity content for GDC (Game Developer Conference) this week so expect some awesome tutorials coming out after that and then an update to the plugin in the coming weeks.

**Comment by ZenithCode** [comment]
Thanks @samtstern 

You're right - its very stable as it is - there' just 1 big bug in my opinion -  **not able to connect multiple iOS devices together.** That breaks the whole plugin.  There are a few other bugs that I would consider high priority but at least they're not breaking bugs.

Looking forward to the update! Wish I could see you at GDC. :-)
