### ISSUE TITLE
Please move your Editor/* stuff under Editor/GooglePlayGames

### ISSUE THREAD

**Issue by Jofator** [playgameservices/play-games-plugin-for-unity#376]
It is very hard to clean old GPGS during uprages as well filename collisions occure among other plugins.
Or at least give GPGS prefix to our files (icnluding template-AndroidManifest.txt and so).
Anyway thanks for great plugin!
Best regards 
Jofator

PS: It is good pattern for Plugins dirs as well :)

**Comment by claywilkinson** [comment]
thanks for the suggestion!

**Comment by robertwahler** [comment]
Would not GooglePlayGames/Editor be a better choice?  I am assuming Unity will find editor files in any folder called Editor.

**Comment by claywilkinson** [comment]
I like GooglePlayGames/Editor better as well.  Let me work on that.

**Comment by claywilkinson** [comment]
Version 0.9.15 fixes this.
