### ISSUE TITLE
The type or namespace name `PlayGamesClientConfiguration'

### ISSUE THREAD

**Issue by hnmikechan** [playgameservices/play-games-plugin-for-unity#377]
Hello,

I have googleplaygames login, ahievements, and leaderboards all working in my unity app.

However, I'm getting the below error when trying to implement saved games.

Error: The type or namespace name `PlayGamesClientConfiguration' could not be found.

I'm using the following:
using GooglePlayGames;
using UnityEngine.SocialPlatforms;
using GooglePlayGames.BasicApi;

Is there any other requirements that I might have missed in the documentation?  Thank you.

**Comment by claywilkinson** [comment]
Are you using the latest plugin?  PlayGamesClientConfiguration was added recently.  It is in the  GooglePlayGames.BasicApi namespace.

**Comment by hnmikechan** [comment]
That was it.  Sorry for wasting your time, I should have known.

Thank you

**Comment by claywilkinson** [comment]
Great News! Glad it was easy to fix :)

**Comment by theFrenchDutch** [comment]
Hi !
I have the same issue, however I just installed the plugin in my project, and checked in About that I do have the 0.9.20 version of the plugin.
I don't understand what's wrong here, can you help me out ?

**Comment by theFrenchDutch** [comment]
Nevermind, somehow Visual Studio doesn't see it but I get no error in Unity. Weird. Should have checked first, sorry !

**Comment by idurvesh** [comment]
I am getting same issue, I am on latest package

**Comment by 86maylin** [comment]
Check your build setting and make sure it's set to Android. 
Somehow it got changed and it took me so long to track down the problem. Orz
