### ISSUE TITLE
Read Leaderboard Score

### ISSUE THREAD

**Issue by habitoti** [playgameservices/play-games-plugin-for-unity#378]
Hi,

is it possible to read the authenticated users score from a certain leaderboard? Social.LoadScores is not implemented, but is there some "native" call of the PlayGames plugin that could do this?

Thanks, habitoti

**Comment by blackrainbowgames** [comment]
+1. There is no way to use incremental scores if game has save/load feature, or user has no connection sometimes to submit scores right now.

**Comment by aggsol** [comment]
You could store the current progress in the cloud save and send the score if a connection is available.

**Comment by habitoti** [comment]
That's what I actually do until today via the AppState API, and it works great. But now that it's deprecated I am a bit hesitant to move to Cloud Save for just this one 64 Bit value. That's all I need to work across platforms (so you increase it, no matter where you play). 
I implemented that already and the migration works in my Beta, but when you start the app it now brings up this huge confirmation request that the app wants to access your Google Drive (w/o any further explanation why). So I know what kind of reviews this will trigger ;-)
If I could just read the current score from the leaderboard, it would be totally sufficient for me. I am not a hardcore Android expert, so I don't dare to add the Social.LoadScores myself, but maybe somebody did that already? Or it's something that can be added within Q1 before the AppState API will be read-only?

**Comment by blackrainbowgames** [comment]
@aggsol, Social.LoadScores is not implemented, that is the problem for many developers.

**Comment by claywilkinson** [comment]
Its on the enhancement list - stay tuned!  There is a related issue tracking that enhancement, https://github.com/playgameservices/play-games-plugin-for-unity/issues/186

**Comment by habitoti** [comment]
Any timeline in mind? If this would be available in Q1, I would definitely switch to that solution in favor of replacing AppState by Cloud Save...

**Comment by habitoti** [comment]
Any news here? Is this something to count on short-term?

**Comment by claywilkinson** [comment]
This has been implemented in the version 0.9.25 of the plugin
