### ISSUE TITLE
OnPeersDisconnected(string[] participantIds) is not working properly

### ISSUE THREAD

**Issue by Bulbul108** [playgameservices/play-games-plugin-for-unity#379]
Although many people ensure that new version (0.9.11) has fixed the OnPeersDisconnected(string[] participantIds) problem, in my case OnPeersDisconnected(string[] participantIds) is not working. But i used version(0.9.02) and worked just fine.

I has implemented a multiplayer game. When a player disconnected i use a virtual player to take his place until only one player left. This is done by identifying a players disconnection through OnPeersDisconnected(string[] participantIds). It seems like OnPeersDisconnected(string[] participantIds) not called when one or two player disconnected. But if there's only one player left then the game quits as desired. Version (0.9.02) worked according to those conditions. I also check QuizRacer and QuizRacer_4.6 sample but same result.

If anyone has any idea about my mistake please help.
Any response will be greatly appreciated and i am very sorry for opening a duplicate issue.

**Comment by claywilkinson** [comment]
@Bulbul108  - Can you tell me if you are seeing this on Android or iOS?

**Comment by Bulbul108** [comment]
Android

**Comment by ajaybirla** [comment]
I think @lpzkl can help you more about it as he is the one who confirmed that issue #215 is fixed.

**Comment by Bulbul108** [comment]
Cant find his email to contact :(

**Comment by lpzkl** [comment]
In my game, I can understand whenever someone disconnects as of plugin version 0.9.11. In version 0.9.10, I was not able to but now it just works.

**Comment by Bulbul108** [comment]
Can you please give me your email. Badly need help @lpzkl

**Comment by lpzkl** [comment]
I don't do anything special for it to work. It just works. Yes OnPeersDisconnected(string[] participantIds) works fine.
Does your other methods work? Do you implement this method in the same class as OnRoomConnected(bool success)?

Whichever the join method is (Invitation or quick game), it notifies me by calling OnPeersDisconnected. In older versions, OnLeftRoom() was called instead of this.

Note that I have not tried matches having more than two people. My matches are 1v1 and as of version 0.9.11 it just works fine. I detect leaver thanks to this method and mark the other one as winner.

You might have used wrong version.

**Comment by Bulbul108** [comment]
Yes other methods work. Yes implement this method in the same class as OnRoomConnected(bool success). Version 0.9.11 check :)
Thanks for your help but it seems like OnPeersDisconnected(string[] participantIds) not working in the middle of a running "Quick Game"

**Comment by Bulbul108** [comment]
4 players game.
1 player is disconnected OnPeersDisconnected(string[] participantIds) method does not work,
2 players are disconnected OnPeersDisconnected(string[] participantIds) method does not work.
3 players are disconnected now OnPeersDisconnected(string[] participantIds) method works just fine.
I wish someone has a solution.

**Comment by anhnguyenvn** [comment]
I got same issue. When having 3 players, one did leave room but the other two did not get informed in OnPeersDisconnected. For quick deal with this issue, i am doing like this, before some really LeaveRoom(), they should send message to inform their leavings. Hope this issued to be fixed soon..

**Comment by Bulbul108** [comment]
0.9.12 updated but still same problem :(

**Comment by Bulbul108** [comment]
Problem solved.
 play-games-plugin-for-unity/source/PluginDev/Assets/GooglePlayGames/Platforms/Native/NativeRealtimeMultiplayerClient.cs#L861
 if (staleParticipant.IsConnectedToRoom() && !freshParticipant.IsConnectedToRoom()) {
newlyLeft.Add(participantId);
}
replaced with-
 if (!freshParticipant.IsConnectedToRoom()) {
newlyLeft.Add(participantId);
}

**Comment by samtstern** [comment]
@Bulbul108 if this works for you, could you submit a pull request?  Seems like your solution could help a lot of people and we could be happy to integrate it into the plugin!

**Comment by claywilkinson** [comment]
Thanks @Bulbul108  - I went ahead and updated the code.  It will be in the next update.
