### ISSUE TITLE
[Feature Request] More Relevant Debug Log Info

### ISSUE THREAD

**Issue by NaxIonz** [playgameservices/play-games-plugin-for-unity#381]
I would like to request more relevant debug log info when trying to use the GPGS plugin. When receiving a message like:
```
"SIGN_IN status: ERROR_NOT_AUTHORIZED"
```
That is entirely too vague. Why am I not authorized? Does it think I am not a test? Does the bundle ID somehow not match what it thinks it should be? Is there a feature turned on in game that is not turned-on over on the dashboard? Does the App ID not match? Have settings on the dashboard not been pushed over yet? Are there OTHER reasons that you can be flagged "NOT_AUTHORIZED?"

As it stands now, we are completely in the dark for what could be a dozen or more reasons things are simply failing to work.

What would be nice is:
```
SIGN_IN status: ERROR_BUNDLE_MISMATCH expected: com.foo.bar received: com.bar.foo
```
or
```
SIGN_IN status: ERROR_NOT_TESTER email is not on tester list
```
or
```
SIGN_IN status: ERROR_SAVED_GAME_NOT_ENABLED
```

or simply anything that is actually useful when debugging a black-box plugin.

@claywilkinson 
@samtstern
Thanks.

**Comment by claywilkinson** [comment]
@NaxIonz  - Thanks for feedback!  I agree that the errors are a little too general.  I'll look into it and see what can be done.

**Comment by NaxIonz** [comment]
Appreciate the quick response Clay!
Hopefully this will help all the eager devs here :-)

**Comment by kreso22** [comment]
+1, please. Just spent hours detecting what the problem - still no success.
This would greatly help.
Much appreciated

**Comment by claywilkinson** [comment]
The auth team and play-services-team have worked hard to improve the messages.  Closing this.  Please open another issue with a specific example if one comes up.
