### ISSUE TITLE
There is no handler/notification for when the other peer declines an invitation

### ISSUE THREAD

**Issue by tcossairt** [playgameservices/play-games-plugin-for-unity#382]
Right now, there does not seem to be any delegate/notification when the other client declines the invite.  Clients need this so they can inform the player that the invite failed.

**Comment by claywilkinson** [comment]
If the application is open when the invitation is declined, then you receive a notification.  However, if the application is not active, then no notification is received.  This follows a general principle of Android which is notifications should be actionable, and having a declined invitation really does not lead to any action.

**Comment by tcossairt** [comment]
What notification event is sent in the first case?   In the previous version of he plugin we were using before upgrading I added a hook in OnPeerDeclined but I don't see that call anymore.

**Comment by masidiq** [comment]
When other client declines, the initiator will be receive OnRoomConnected(bool success = false)

**Comment by tcossairt** [comment]
How do you distinguish from a true failure on a normal OnRoomConnected then?  (vs invite decline) There's only one handler for both quick matches and invites.

**Comment by claywilkinson** [comment]
This is added in 0.9.21 update.
