### ISSUE TITLE
There is no notification/delegate for when a user signs out externally

### ISSUE THREAD

**Issue by tcossairt** [playgameservices/play-games-plugin-for-unity#383]
The client needs a notification/delegate to be notified if the user signs out of Google Play externally.  (To disable online UI e.g.)

**Comment by claywilkinson** [comment]
There is not really an event for being signed out externally.  Your game can handle this by keeping a flag of the signed in state, then onResume check if Social.localUser.authenticated is false and the flag is true, then you can handle any cleanup or state change, etc.
