### ISSUE TITLE
Save a game at first launch from code

### ISSUE THREAD

**Issue by sl33tz0r** [playgameservices/play-games-plugin-for-unity#384]
Im using only one save game that keeps the current progress and player level. How do I create it programatically, without displaying the save/load UI? It seems it doesnt get created when you call OpenWithAutomaticConflictResolution("gamedata.sav".. if gamedata.sav doesn't exist

**Comment by claywilkinson** [comment]
Opening does not write anything out, you should be able to open, then call SavedGame.CommitUpdate() with the updated metadata and  data.

**Comment by sl33tz0r** [comment]
Even if the save file doesnt exist? How do I get the metadata to pass to CommitUpdate() for an file that doesnt exist ? Please enlighten me, I've been dealing with this for 3 days now :)

**Comment by iqbalmineraltown** [comment]
I did the same thing by simply replacing this on LoadFromCloud() and SaveToCloud() CubicPilot example:
```C#
((PlayGamesPlatform)Social.Active).SavedGame.ShowSelectSavedGameUI(
                "Save game progress",
                4, true, true, SavedGameSelected);
```

with this line from SavedGameSelected(SelectUIStatus status, ISavedGameMetadata game):
```C#
((PlayGamesPlatform)Social.Active).SavedGame.OpenWithAutomaticConflictResolution(
                     filename,
                     DataSource.ReadCacheOrNetwork,
                     ConflictResolutionStrategy.UseLongestPlaytime,
                     SavedGameOpened);
```

then SavedGameSelected(SelectUIStatus status, ISavedGameMetadata game) is not needed:
Make sure you always use same filename when saving.

CMIIW

**Comment by iqbalmineraltown** [comment]
I did implement autosave & autoload by simply replacing this on LoadFromCloud() and SaveToCloud() CubicPilot example:
```C#
((PlayGamesPlatform)Social.Active).SavedGame.ShowSelectSavedGameUI(
                "Save game progress",
                4, true, true, SavedGameSelected);
```

with this line from SavedGameSelected(SelectUIStatus status, ISavedGameMetadata game):
```C#
((PlayGamesPlatform)Social.Active).SavedGame.OpenWithAutomaticConflictResolution(
                     filename,
                     DataSource.ReadCacheOrNetwork,
                     ConflictResolutionStrategy.UseLongestPlaytime,
                     SavedGameOpened);
```

then SavedGameSelected(SelectUIStatus status, ISavedGameMetadata game) is not needed.
Make sure you always use same filename when saving

Hope this helps
CMIIW

**Comment by elsaq** [comment]
Could someone help on how to save and load game with this plugin? I have been trying for weeks and only saved empty files (also empty screenshots).

The official code is fully incomplete.

**Comment by samtstern** [comment]
Here is some code from a game that I made with version `0.9.12`.  I can confirm that this works.

These two functions are basic read/write:

    public void ReadSavedGame(string filename, 
                             Action<SavedGameRequestStatus, ISavedGameMetadata> callback) {
        
        ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame;
        savedGameClient.OpenWithAutomaticConflictResolution(
            filename, 
            DataSource.ReadCacheOrNetwork, 
            ConflictResolutionStrategy.UseLongestPlaytime, 
            callback);
    }
    
    public void WriteSavedGame(ISavedGameMetadata game, byte[] savedData, 
                               Action<SavedGameRequestStatus, ISavedGameMetadata> callback) {
        
        SavedGameMetadataUpdate.Builder builder = new SavedGameMetadataUpdate.Builder()
            .WithUpdatedPlayedTime(TimeSpan.FromMinutes(game.TotalTimePlayed.Minutes + 1))
            .WithUpdatedDescription("Saved at: " + System.DateTime.Now);
        
        // You can add an image to saved game data (such as as screenshot)
        // byte[] pngData = <PNG AS BYTES>;
        // builder = builder.WithUpdatedPngCoverImage(pngData);
        
        SavedGameMetadataUpdate updatedMetadata = builder.Build();
        
        ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame;
        savedGameClient.CommitUpdate(game, updatedMetadata, savedData, callback);
    }


And this function is an example of writing a score (integer) to a saved game file:
    
    public void WriteUpdatedScore() {
        // Local variable
        ISavedGameMetadata currentGame = null;

        // CALLBACK: Handle the result of a write
        Action<SavedGameRequestStatus, ISavedGameMetadata> writeCallback = 
        (SavedGameRequestStatus status, ISavedGameMetadata game) => {
            Debug.Log("Saved Game Write: " + status.ToString());
        };

        // CALLBACK: Handle the result of a binary read
        Action<SavedGameRequestStatus, byte[]> readBinaryCallback = 
        (SavedGameRequestStatus status, byte[] data) => {
            Debug.Log("Saved Game Binary Read: " + status.ToString());
            if (status == SavedGameRequestStatus.Success) {
                // Read score from the Saved Game
                int score = 0;
                try {
                    string scoreString = System.Text.Encoding.UTF8.GetString(data);
                    score = Convert.ToInt32(scoreString);
                } catch (Exception e) {
                    Debug.Log("Saved Game Write: convert exception");
                }
                
                // Increment score, convert to byte[]
                int newScore = score + mHits;
                string newScoreString = Convert.ToString(newScore);
                byte[] newData = System.Text.Encoding.UTF8.GetBytes(newScoreString);
                
                // Write new data
                Debug.Log("Old Score: " + score.ToString());
                Debug.Log("mHits: " + mHits.ToString());
                Debug.Log("New Score: " + newScore.ToString());
                WriteSavedGame(currentGame, newData, writeCallback);
            }
        };

        // CALLBACK: Handle the result of a read, which should return metadata
        Action<SavedGameRequestStatus, ISavedGameMetadata> readCallback = 
        (SavedGameRequestStatus status, ISavedGameMetadata game) => {
            Debug.Log("Saved Game Read: " + status.ToString());
            if (status == SavedGameRequestStatus.Success) {
                // Read the binary game data
                currentGame = game;
                PlayGamesPlatform.Instance.SavedGame.ReadBinaryData(game, 
                                                    readBinaryCallback);
            }
        };

        // Read the current data and kick off the callback chain
        Debug.Log("Saved Game: Reading");
        ReadSavedGame("file_total_hits", readCallback);
    }

**Comment by alihamie** [comment]
I know this was closed a while ago but I need a little help , does the filename has to be of a file that exists ,if so then where do I create and put the file  ? Do you need to open the file before writing and saving ?

**Comment by claywilkinson** [comment]
no, the filename does not need to match an existing snapshot.  There is no real "file" it is just the name of that specific saved game.
