### ISSUE TITLE
[Urgent bug] - Cannot connect more than 1 iOS device to a game

### ISSUE THREAD

**Issue by ZenithCode** [playgameservices/play-games-plugin-for-unity#385]
Plugin version: 0.9.11

I can connect:
3 x Android devices 
2 x Android and 1 x iOS device

But when I try to connect 2 iOS devices and 1 Android or 3 iOS devices, the 'OnRoomConnected' never gets called on the second iOS device.

**Comment by ZenithCode** [comment]
Any update on this? Any timeframe please?

**Comment by ZenithCode** [comment]
https://dl.dropboxusercontent.com/u/9385978/Google%20Play%20Games%20-%20does%20not%20work%20on%20iOS.mp4

**Comment by ZenithCode** [comment]
@mrggl @samtstern @claywilkinson Problem is still there after upgrading 0.9.15

**Comment by claywilkinson** [comment]
I think this problem is inside the underlying Games SDK - we're still working on it.  We'll keep you posted.

**Comment by ZenithCode** [comment]
Thanks again @claywilkinson

**Comment by claywilkinson** [comment]
@ZenithCode  - Can provide a log file of what is happening on the iOS devices (one that works, and one that does not)?  Thanks!

**Comment by ZenithCode** [comment]
@claywilkinson There are no exceptions - the second iOS device never gets the OnRoomConnected callback from GPG. (Progress goes up to 180 but it stays stuck at that point)

**Comment by claywilkinson** [comment]
Ok to close this one?  I believe it is working OK.

**Comment by ZenithCode** [comment]
Yes, thanks!
