### ISSUE TITLE
CS0246: The type or namespace name `GooglePlayGames' could not be found. Are you missing a using directive or an assembly reference?

### ISSUE THREAD

**Issue by Xaverix** [playgameservices/play-games-plugin-for-unity#386]
Hi. When I try to use GooglePlayGames binary, i have an error.

"CS0246: The type or namespace name `GooglePlayGames' could not be found. Are you missing a using directive or an assembly reference?"

I just type:
using GooglePlayGames;

What's wrong?

**Comment by simsis3d** [comment]
Are u sure that you correctly imported(with all files/scripts included) plugin package?

**Comment by Xaverix** [comment]
Yes :/ I'm sure :c

**Comment by claywilkinson** [comment]
Hmmm. Not a lot to go on, I'd suggest falling back and working with one of the samples, then once it is working, you can compare it to your project and see what is going on.

**Comment by claywilkinson** [comment]
@Xaverix  - quick ping - I am presuming you figured out your problem?  Please re-open this if you have more questions.

**Comment by furkanozden** [comment]
Build Settings > Switch Platform > Android

**Comment by thunguyen177** [comment]
Recently, there're an update of the Play Billing. You may try to update that. 
I met this error and this is how I resolved it:
1/ Uninstall play billing, restart unity
2/ Reinstall Play Billing & update
3/ Go to Google -> Play Billing -> Build Setting and press the Fix button if it's there.
If the error still show up, you may restart unity again
