### ISSUE TITLE
Callback  IsConnectedToRoom not working , also OnLeftRoom() never notifies that the current player has left the room.

### ISSUE THREAD

**Issue by chetanisinanand** [playgameservices/play-games-plugin-for-unity#387]
Problem after upgrading : GooglePlayGamesPlugin-0.9.11

When application goes in background it apparently gets disconnected to the Room , all opponents gets a callback OnPeersDisconnected().
However , current player never reports a callback OnLeftRoom() to notify that device is no more connected to the Room, and  IsConnectedToRoom also returns TRUE, 

please intervene the issue

**Comment by claywilkinson** [comment]
This has been implemented in the version 0.9.25 of the plugin
