### ISSUE TITLE
Does not show login UI for the auto login

### ISSUE THREAD

**Issue by jung5000** [playgameservices/play-games-plugin-for-unity#390]
When the app is launching,

When I call Authenticate(), it shows Login Popup UI only for the very first time. (with Agree button).

After than, whenever I restart the app, and try to auto login, it does not shows Login UI Toast(rounded small popup with level and name) as attached UI.  (Yes, explicit "login" shows login toast, but I also want to show for auto login)

But authenticated flag shows the it is logged in successfully.

I tested with my app and the sample, CubicPilot. But not of them is showing Login UI toast.

Is it bug? of am I missing something?

![googleplay_login](https://cloud.githubusercontent.com/assets/10826108/6016434/3469282e-abc5-11e4-8f80-6cb2dc69b05b.png)

**Comment by simsis3d** [comment]
It is not a bug. When user login once and quit then come back, first login procedure will be silently. Other attempts will show login UI.

**Comment by jung5000** [comment]
The, How do I do if I want to show always above "welcome back" UI? even if it is auto login?

**Comment by simsis3d** [comment]
You can show your own "Welcome" GUI whenever user is authenticated. Pseudocode is like that

if(Social.localUser.isAuthenticated)
{
ShowUIWithEntity("Welcome"+ localUser.UserName);
}

else
{
ShowUIWithEntity("Please Log in");
}
