### ISSUE TITLE
[Question] Is there a way to Cancel Out an Invitation in Real Time Multi Player?

### ISSUE THREAD

**Issue by simsis3d** [playgameservices/play-games-plugin-for-unity#391]
When a player invite someone or press QuickMatch, is there a way to cancel out this action. It is an annoying problem because the player(inviter) cannot invite someone else, perform quickmatch or accept from inbox untill other player(invited) accept or decline current invitation. Invited player may be busy or not have an internet access. The only solution for inviter right now is quit game and come back to be able to use multiplayer actions.

**Comment by masidiq** [comment]
call PlayGamesPlatform.Instance.RealTime.LeaveRoom();
its work for me

**Comment by claywilkinson** [comment]
Yes, calling PlayGamesPlatform.Instance.RealTime.LeaveRoom() is the correct approach.  Closing this issue.
