### ISSUE TITLE
[Question] Does Unity Plugin support default Waiting Room in Real Time Multiplayer?

### ISSUE THREAD

**Issue by simsis3d** [playgameservices/play-games-plugin-for-unity#392]
When I read this post (https://developers.google.com/games/services/android/realtimeMultiplayer), it says that 
"We recommend that your game use a "waiting room" UI so that players can see the current status of the room as participants join and get connected. Your game can display the default waiting room UI or a custom UI.
To launch the default waiting room UI, call the getWaitingRoomIntent() method and use the Intent it returns to start a Activity."

Does Unity plugin(V0.9.07) support this function? If yes, where is it?

**Comment by simsis3d** [comment]
Any idea about waiting room? @claywilkinson

**Comment by Mart1111** [comment]
I joing to this question. It seems intentionally omitted though all other cases are present (start via invitation, send invitation)
```javascript
IRealTimeMultiplayerClient.cs
...
/// Creates a game with random automatch opponents. No UI will be shown.
void CreateQuickGame(uint minOpponents, uint maxOpponents, uint variant,
                             Multiplayer.RealTimeMultiplayerListener listener);
...
```

**Comment by claywilkinson** [comment]
ShowWaitingRoomUI() was added in the 0.9.21 update
