### ISSUE TITLE
[Question] can't read match.data after a finished match

### ISSUE THREAD

**Issue by blum96** [playgameservices/play-games-plugin-for-unity#393]
My game is turn-based with 6 rounds on Android

First of all i have to say that nearly everything works great but I can't write something into the match.Data anymore when I finished the match.

Is there a way how I can write something into data because I want to give the User at the end some items and I need a variable where i can check if he already got it. 

An other way would be if I could see when the match is acknowledged because I give him the items always when i finish or acknowledge the match. The problem is that when the match is completed, it runs through the acknowledging code. Is there a variable which i can call up to see if the game is already acknowledged because the User is always getting the items again and he should just get it one time.

I hope anyone is able to help me ;)
If anything was unclear please don't hesitate to ask me for more information.

**Comment by spotavi** [comment]
What version of plugin are you using ?

**Comment by blum96** [comment]
Plugin version: 0.9.02 (0x00000902)
but I think this doesn't matter, because on this side: "https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/TBMP.md" everything is explained very well and nothing changed there since i installed this plugin.

I just need a way how I can call up if the match is already acknowledged. Otherwise I have to save all match.ids local on the device where the user already got an item and this would be very unprofessional.

**Comment by samtstern** [comment]
You should not 'finish' a match if you intend to write more data into it.  Instead, perform the item transfer before you finish the turn-based match.
