### ISSUE TITLE
Error when updating the redirect urls in Info.plist file

### ISSUE THREAD

**Issue by cana** [playgameservices/play-games-plugin-for-unity#394]
I am running into an issue when I try to build my unity project for iOS on windows, as you can see below:

![invalidoperationexception](https://cloud.githubusercontent.com/assets/1078814/6060924/00342b56-ad43-11e4-824a-287ae35534d4.PNG)
>InvalidOperationException: Could not locate an installation of PlistBuddy!
>GooglePlayGames.Editor.PlistBuddyHelper.ForPlistFile (System.String filepath) (at Assets/Editor/PlistBuddyHelper.cs:21)
>GPGSPostBuild.UpdateGeneratedInfoPlistFile (System.String pathToPlist) (at Assets/Editor/GPGSPostBuild.cs:52)
>GPGSPostBuild.OnPostprocessBuild (BuildTarget target, System.String pathToBuiltProject) (at Assets/Editor/GPGSPostBuild.cs:32)
>UnityEditor.HostView:OnGUI()

Despite this error the Xcode project was still created and it ran fine on my iPhone! So I tried but the problem was that when I tried to sign in, the google app (chrome mobile or google +) did not redirect to my app.

In fact the **Info.plist** file was not updated with the good redirecting urls. 

So If I add the url row manually in my "Info.plist" like that :
```xml
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleURLTypes</key>
    <string>Editor</string>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>com.company.${PRODUCT_NAME}</string>
    </array>
    <key>CFBundleURLName</key>
    <string>com.company.${PRODUCT_NAME}</string>
  </dict>
</array>
```
Then it worked fine and  the google app (chrome mobile or google +) redirected well to my app sign in with my google account.

**Comment by claywilkinson** [comment]
PlistBuddy is installed with the developer tools from Apple.
