### ISSUE TITLE
App Crash when backing out of "AcceptFromInbox" match view on Android

### ISSUE THREAD

**Issue by n8stowell82** [playgameservices/play-games-plugin-for-unity#399]
I have a button on my first screen that lets the user jump into the "acceptFromInbox" view so that they can pick from previously started matches or accept invitation,etc.  On Android if you load this view then hit the back arrow at the top of the screen (not the native android back button) the app will crash.  Below is the the logcat dump of when it happens:

D/GamesUnitySDK( 2028): Forwarding OnActivityResult Finished
I/Unity   ( 2028):  [Play Games Plugin DLL] 02/06/15 15:40:50 -06:00 DEBUG: Entering internal callback for TurnBasedManager#MatchInboxUICallback
I/Unity   ( 2028):  
I/Unity   ( 2028): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 2028): 
W/art     ( 2028): 0x6ed57b78
W/art     ( 2028): 0x6ed57b48
W/art     ( 2028): 0x6ed57b48
V/GamesNativeSDK( 2028): Received Activity Resume Event.
I/Unity   ( 2028):  [Play Games Plugin DLL] 02/06/15 15:40:50 -06:00 DEBUG: PlayGamesHelperObject.OnApplicationFocus True
I/Unity   ( 2028):  
I/Unity   ( 2028): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 2028): 
W/GmsClientEvents(  783): unregisterConnectionCallbacks(): listener r{d4be785 #0 id=0x7f0f016b} not found
W/GmsClientEvents(  783): unregisterConnectionFailedListener(): listener r{d4be785 #0 id=0x7f0f016b} not found
I/Unity   ( 2028):  [Play Games Plugin DLL] 02/06/15 15:40:50 -06:00 DEBUG: PlayGamesHelperObject.OnApplicationPause False
I/Unity   ( 2028):  
I/Unity   ( 2028): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   ( 2028): 
W/InputDispatcher(  480): channel '7634bcc com.genericNameOfCompany.dkd/com.unity3d.player.UnityPlayerNativeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  480): channel '7634bcc com.genericNameOfCompany.dkd/com.unity3d.player.UnityPlayerNativeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
W/SurfaceFlinger(  129): couldn't log to binary event log: overflow.
I/WindowState(  480): WIN DEATH: Window{22afa48c u0 SurfaceView}
I/WindowState(  480): WIN DEATH: Window{20a2c7d7 u0 com.genericNameOfCompany.dkd/com.google.games.bridge.NativeBridgeActivity EXITING}
I/WindowState(  480): WIN DEATH: Window{7634bcc u0 com.genericNameOfCompany.dkd/com.unity3d.player.UnityPlayerNativeActivity}
W/InputDispatcher(  480): Attempted to unregister already unregistered input channel '7634bcc com.genericNameOfCompany.dkd/com.unity3d.player.UnityPlayerNativeActivity (server)'
I/Zygote  (  141): Process 2028 exited due to signal (11)
I/ActivityManager(  480): Process com.genericNameOfCompany.dkd (pid 2028) has died
W/ActivityManager(  480): Force removing ActivityRecord{37254fe9 u0 com.genericNameOfCompany.dkd/com.unity3d.player.UnityPlayerNativeActivity t104}: app died, no saved state
W/InputMethodManagerService(  480): Got RemoteException sending setActive(false) notification to pid 2028 uid 10109

**Comment by n8stowell82** [comment]
Update: Was able to get a console log view on iOS and Android.  It looks like the error is a null reference on the call back "onMatchStarted".  Basically it is still calling the callback regardless of if you selected a match or not.  In my case I wasn't checking for null on the match parameter.  Problem has been solved on my end, but it seems like it shouldn't call the callback if the user did not select a match.

**Comment by claywilkinson** [comment]
Thanks for the followup.  There is another request to get the status code to passed along in the callback so you can see that the user canceled (or whatever non-OK result) which would cause the match to be null.
