### ISSUE TITLE
"gpg/ios_support.h" file not found.

### ISSUE THREAD

**Issue by joonbumpark** [playgameservices/play-games-plugin-for-unity#403]
hello~! :)
i can not solve this problem.
please help me!!

Xcode: Version 6.1.1 (6A2008a)
Unity: 4.6.2f1
Plugin: last update version.

my xcode project settings...

![2015-02-11 3 05 16](https://cloud.githubusercontent.com/assets/10953691/6142746/e673ec62-b1ff-11e4-8f72-ba422d53068d.png)
![2015-02-11 3 05 25](https://cloud.githubusercontent.com/assets/10953691/6142747/ebd39ea0-b1ff-11e4-90f9-11d2f7662995.png)
![2015-02-11 3 04 53](https://cloud.githubusercontent.com/assets/10953691/6142748/f043c42e-b1ff-11e4-873c-47ed1406542c.png)
![2015-02-11 3 04 26](https://cloud.githubusercontent.com/assets/10953691/6142749/f2e7257c-b1ff-11e4-81e7-898bfebcdd8d.png)

**Comment by joonbumpark** [comment]
https://github.com/playgameservices/play-games-plugin-for-unity/issues/320

**Comment by RameshGithub00** [comment]
Please read this
https://github.com/playgameservices/play-games-plugin-for-unity/issues/320

**Comment by joonbumpark** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

smilex_x@naver.com 님께 보내신 메일 <Re: [play-games-plugin-for-unity] "gpg/ios_support.h" file not found. (#403)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
