### ISSUE TITLE
How to use the code?

### ISSUE THREAD

**Issue by elsaq** [playgameservices/play-games-plugin-for-unity#406]
I have been able to implement Achievments and LogIn/Out, but I can´t save/load.

I have been able only to save/load a blank screenshot, but nothing was saved.

I really don´t know how to use the code provided in this official page of the plugin, I don´t know how to use OnSavedGameSelected and the others.

Can someone help me with a better code than the one here? It´s not easy to understand.

Thanks!

**Comment by elsaq** [comment]
I only need a easy way to save and load with the plugin, the code provided is really bad and uncomplete.

Just need an example code that you have been using and works, not tjis incomplete code.

**Comment by claywilkinson** [comment]
Did you try the Cubic Pilot 4.6 sample? https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/samples/CubicPilot_4.6

This sample uses SavedGames to save the score for each level completed.  Specifically see the  GameManager class: https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/samples/CubicPilot_4.6/Source/Assets/CubicPilot_4.6/GameLogic/GameManager.cs

**Comment by aggsol** [comment]
@elsaq atm I cannot recommend any commercial android plugins. Those are flawed in other ways.

**Comment by elsaq** [comment]
Thanks for the reply!

Yes I have try the Cubic Pilot 4.6 sample without luck, with that sample I only been able to save empty files.

The main problem is that I don´t know where I have to put the things I want to save, for example a float value, so I have been saving empty files.

**Comment by claywilkinson** [comment]
@elsaq  - I think your other issue posting is covering the same ground, but with a lot more information.  I am closing this issue, in order to consolidate into issue #409.  Please reopen this issue if you think it is a different issue from #409 .  Thanks!
