### ISSUE TITLE
iOS Saved Games not working

### ISSUE THREAD

**Issue by justjuank** [playgameservices/play-games-plugin-for-unity#408]
Hello, I migrated our game to the new Saved Games system. In Android works perfectly, but in iOS while I can log in with Google+ and check my achievements and rankings, I can't get to load the data from the Saved Game, when I try to load the game this is what my log shows:

[Play Games Plugin DLL] 02/04/15 16:43:56 -05:00 DEBUG: Entering internal callback for SnapshotManager#FetchAllCallback
(Filename: /Applications/buildAgent/work/d63dfc6385190b60/artifacts/iPhonePlayer-armv7Generated/UnityEngineDebug.cpp Line: 49)

[Play Games Plugin DLL] 02/04/15 16:43:59 -05:00 DEBUG: Entering internal callback for SnapshotManager#OpenCallback
(Filename: /Applications/buildAgent/work/d63dfc6385190b60/artifacts/iPhonePlayer-armv7Generated/UnityEngineDebug.cpp Line: 49)

[Play Games Plugin DLL] 02/04/15 16:43:59 -05:00 DEBUG: Invoking conflict callback
(Filename: /Applications/buildAgent/work/d63dfc6385190b60/artifacts/iPhonePlayer-armv7Generated/UnityEngineDebug.cpp Line: 49)

2015-02-04 16:44:00.009 FallingCat[790:1277b] ERROR: MD5 mismatch. Couldn't read at path: /var/mobile/Applications/XXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX/Library/Application Support/com.levelplusgames.FallingCat/snapshots/711dbbfcae06bd1f456aeeb173dcf3d0.conflict.

2015-02-04 16:44:00.011 FallingCat[790:9a07] ERROR: Encountered a read error with snapshot used for conflict resolution

[Play Games Plugin DLL] 02/04/15 16:44:00 -05:00 DEBUG: Entering internal callback for SnapshotManager#CommitCallback

(Filename: /Applications/buildAgent/work/d63dfc6385190b60/artifacts/iPhonePlayer-armv7Generated/UnityEngineDebug.cpp Line: 49)

Is this some kind of bug in the iOS SDK?
Any help would be greatly appreciated
Thanks.

PD:
using
google plus ios sdk 1.7.1
gpg cpp sdk 1.3

**Comment by claywilkinson** [comment]
@justjuank - SavedGames has had a couple fixes since  your issue was created.  I am closing this one, please upgrade to the latest plugin and C++ SDK 1.4.1 and open an issue if you are still having problems.
