### ISSUE TITLE
Where I have to put the info to save?

### ISSUE THREAD

**Issue by elsaq** [playgameservices/play-games-plugin-for-unity#409]
I´m using official plugin:

https://github.com/playgameservices/play-games-plugin-for-unity

I have this code for saving and loading:

     System.Action<bool> mAuthCallback;
     
     GameData slot0;
     
     bool mSaving;
     private Texture2D mScreenImage;
     
     // Use this for initialization
     void Start () {
         
         slot0 = new GameData("New game");
         mAuthCallback = (bool success) => {
             
             if (success) {
                 Debug.Log("Authentication was successful!");
                 slot0.State = "Click load or save";
             }
             else {
                 Debug.LogWarning("Authentication failed!");
             }
             
         };
         
         
         PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
             .EnableSavedGames()
                 .Build();
         PlayGamesPlatform.InitializeInstance(config);
         
         // Activate the Play Games platform. This will make it the default
         // implementation of Social.Active
         PlayGamesPlatform.Activate();
         
         // enable debug logs (note: we do this because this is a sample; on your production
         // app, you probably don't want this turned on by default, as it will fill the user's
         // logs with debug info).
         PlayGamesPlatform.DebugLogEnabled = true;
         
         //Login explicitly for this sample, usually this would be silent
         PlayGamesPlatform.Instance.Authenticate(mAuthCallback, false);
         
         
     }
     
     public void CaptureScreenshot() {
         mScreenImage = new Texture2D(Screen.width, Screen.height);
         mScreenImage.ReadPixels(new Rect(0, 0, Screen.width, Screen.height), 0, 0);
         mScreenImage.Apply();
     }
 
     // Save Button
 
     public void SaveButton () 
     {
         int idx = slot0.Data.IndexOf("_");
         if (idx > 0) {
             int val = Convert.ToInt32(slot0.Data.Substring(idx+1));
             val++;
             slot0.Data = "Save_" + val;
         }
         else {
             slot0.Data = "Save_0";
         }
         mSaving = true;
         CaptureScreenshot();
         ((PlayGamesPlatform)Social.Active).SavedGame.ShowSelectSavedGameUI("Save game progress",
                                                                            4,true,true,SavedGameSelected);
     }
 
     // Load Button
 
     public void LoadButton () 
     {
         mSaving = false;
         ((PlayGamesPlatform)Social.Active).SavedGame.ShowSelectSavedGameUI("Select game to load",
                                                                            4,false,false,SavedGameSelected);
     }
     
     
     public void SavedGameSelected(SelectUIStatus status, ISavedGameMetadata game) {
         
         if (status == SelectUIStatus.SavedGameSelected) {
             string filename = game.Filename;
             Debug.Log("opening saved game:  " + game);
             if(mSaving && (filename == null || filename.Length == 0)) {
                 filename = "save" + DateTime.Now.ToBinary();
             }
             if (mSaving) {
                 slot0.State = "Saving to " + filename;
             }
             else {
                 slot0.State = "Loading from " + filename;
             }
             //open the data.
             ((PlayGamesPlatform)Social.Active).SavedGame.OpenWithAutomaticConflictResolution(filename,
                                                                                              DataSource.ReadCacheOrNetwork,
                                                                                              ConflictResolutionStrategy.UseLongestPlaytime,
                                                                                              SavedGameOpened);
         } else {
             Debug.LogWarning("Error selecting save game: " + status);
         }
         
     }
     
     public void SavedGameOpened(SavedGameRequestStatus status, ISavedGameMetadata game) {
         if(status == SavedGameRequestStatus.Success) {
             if( mSaving) {
                 slot0.State = "Opened, now writing";
                 byte[] pngData = (mScreenImage!=null) ?mScreenImage.EncodeToPNG():null;
                 Debug.Log("Saving to " + game);
                 byte[] data = slot0.ToBytes();
                 TimeSpan playedTime = slot0.TotalPlayingTime;
                 SavedGameMetadataUpdate.Builder builder =  new 
                     SavedGameMetadataUpdate.Builder()
                         .WithUpdatedPlayedTime(playedTime)
                         .WithUpdatedDescription("Saved Game at " + DateTime.Now);
                 
                 if (pngData != null) {
                     Debug.Log("Save image of len " + pngData.Length);
                     builder = builder.WithUpdatedPngCoverImage(pngData);
                 }
                 else {
                     Debug.Log ("No image avail");
                 }
                 SavedGameMetadataUpdate updatedMetadata  = builder.Build();
                 ((PlayGamesPlatform)Social.Active).SavedGame.CommitUpdate(game,updatedMetadata,data,SavedGameWritten);
             } else {
                 slot0.State = "Opened, reading...";
                 ((PlayGamesPlatform)Social.Active).SavedGame.ReadBinaryData(game,SavedGameLoaded);
             }
         } else {
             Debug.LogWarning("Error opening game: " + status);
         }
     }
     
     public void SavedGameLoaded(SavedGameRequestStatus status, byte[] data) {
         if (status == SavedGameRequestStatus.Success) {
             Debug.Log("SaveGameLoaded, success=" + status);
             slot0 = GameData.FromBytes(data);
         } else {
             Debug.LogWarning("Error reading game: " + status);
         }
     }
     
     
     public void SavedGameWritten(SavedGameRequestStatus status, ISavedGameMetadata game) {
         if(status == SavedGameRequestStatus.Success) {
             Debug.Log ("Game " + game.Description + " written");
             slot0.State = "Saved!";
         } else {
             Debug.LogWarning("Error saving game: " + status);
         }
     }
     
     
     public class GameData  {
         
         private TimeSpan mPlayingTime;
         private DateTime mLoadedTime;
         string mData;
         string mState;
         
         static readonly string HEADER = "GDv1";
         
         public GameData(string data) {
             
             mData = data;
             mState = "Initialized, modified";
             mPlayingTime = new TimeSpan();
             mLoadedTime = DateTime.Now;
             
         }
         
         public TimeSpan TotalPlayingTime {
             get {
                 TimeSpan delta = DateTime.Now.Subtract(mLoadedTime);
                 return mPlayingTime.Add(delta);
             }
         }
         
         public override string ToString () {
             string s = HEADER + ":" + mData;
             s += ":" + TotalPlayingTime.TotalMilliseconds;
             return s;
         }
         
         public byte[] ToBytes() {
             return System.Text.ASCIIEncoding.Default.GetBytes(ToString());
         }
         
         
         public static GameData FromBytes (byte[] bytes) {
             return FromString(System.Text.ASCIIEncoding.Default.GetString(bytes));
         }
         
         public static GameData FromString (string s) {
             GameData gd = new GameData("initializing from string");
             string[] p = s.Split(new char[] { ':' });
             if (!p[0].StartsWith(HEADER)) {
                 Debug.LogError("Failed to parse game data from: " + s);
                 return gd;
             }
             gd.mData = p[1];
             double val = Double.Parse(p[2]);
             gd.mPlayingTime = TimeSpan.FromMilliseconds(val>0f?val:0f);
             
             gd.mLoadedTime = DateTime.Now;
             gd.mState = "Loaded successfully";
             return gd;
         }
         
         public string Data {
             get {
                 return mData;
             }
             
             set {
                 mData = value;
                 mState += ", modified";
             }
             
         }
         
         public string State {
             get {
                 return mState;
             }
             
             set {
                 mState = value;
             }
         }
         
     }
 
With this I only save and load blank info, so nothing is saved, can anyone help me? I would like to know where I have to put the info that I want to be saved, for example, a float.

Thanks!

**Comment by claywilkinson** [comment]
This sample is using the class GameData to hold the information that will be saved and is very trivial.  The way it works is the class overrides the ToString() method to create a string representing the data to save.   This is called by ToBytes() which gets the string and then returns the byte array to save using the SavedGame API.  

Loading is done in reverse - the byte array is received in the callback SavedGameLoaded(), and then FromBytes() is called, which creates a string from the bytes, and then passes the string to FromString() which splits the string on the : character (which is used in ToString()) and then converts each field  to the correct type.

A robust solution could use something easy, but not very space efficient, like a JSON string. which can provide a more automatic conversion from an object to a string (or bytes).

**Comment by elsaq** [comment]
Ok, now I understand the way that the code is doing the save and load, but where exactly inside this code I have to put the info?

**Comment by elsaq** [comment]
I have been able to create a JSON using this:

http://patrykgalach.blogspot.com.es/2013/09/JSON-and-Unity3D.html

And now, where I have to put that JSON string??

**Comment by claywilkinson** [comment]
if you take the sample and  change  to use the following ToBytes (assuming your JSON string is called jsonString)

    public byte[] ToBytes() {
             return System.Text.ASCIIEncoding.Default.GetBytes(jsonString);
         }

Then, to read the data, use something like: (where ParseJSON(string s) parses a string into a json object.

     public static GameData FromBytes (byte[] bytes) {
             return ParseJSON(System.Text.ASCIIEncoding.Default.GetString(bytes));
      }

**Comment by claywilkinson** [comment]
@elsaq  - Did you get your game saving OK?  I think this issue is resolved, ok if I close it?
