### ISSUE TITLE
Authenticate callback always return false with 0.9.11

### ISSUE THREAD

**Issue by vanustwo** [playgameservices/play-games-plugin-for-unity#410]
The callback for Authenticate will return false when sign in successful.

Social.localUser.Authenticate((bool success) => {           
             Debug.Log("Authenticate " + success);
            if (success) {
                Debug.Log("Login successful!");
            } else {
                Debug.LogWarning("Failed to sign in with Google Play Games.");
            }
        });

If pressing OK on "Choose Account" dialog box, there is no callback when sign in process is successful.

Logs
02-14 11:20:18.663: I/Unity(9915): Authenticate False
02-14 11:20:23.123: V/GamesNativeSDK(9915): Play Games callback indicates connection.
02-14 11:20:23.183: I/GamesNativeSDK(9915): Successfully connected to Google Play.

The GamesNativeSDK logs says a connection is successful with Google Play but Authenticate callback will not get triggered.

thanks

**Comment by gguuss** [comment]
Are you starting from one of the sample apps and following the instructions?  Was it working before but no longer is working?

**Comment by SamMcAlpine** [comment]
I'm having the same problem. I've also tried using PlayGamesPlatform.Instance.Authenticate like the examples but that isn't working either.

**Comment by abalta** [comment]
I think, @SamMcAlpine  right, I also have same issue, but I reailed I try without keystore.

**Comment by SamMcAlpine** [comment]
You will need to have set up the store listing in Google Play Developers Console (with a keystore) and link it to the Game Service game (which you also need to set up in the Developer Console) in order to use this plugin.

**Comment by claywilkinson** [comment]
@vanustwo - please reopen this issue if you are still having problems setting up your game in the play console.

**Comment by natasha1403** [comment]
@SamMcAlpine my android app is working, but when I am implementing same for an iOS app, authenticate callback is always returning false. Any suggestions on what can go wrong?
