### ISSUE TITLE
OnPeersDisconnected() Method is not being Called

### ISSUE THREAD

**Issue by parthpandya008** [playgameservices/play-games-plugin-for-unity#412]
When any user disconnected from  the room suddenly, OnPeersDisconnected() method is not being called. My objective is that when wifi network is lost in-between game play in any user, other users should get notified that one user had suddenly left  the room.

Ideally I should get these information in OnPeersDisconnected() method of all the connected users of the room, but these method is not being called.

So, how to get callback in OnPeersDisconnected() or is there any way to handle above issue?

**Comment by claywilkinson** [comment]
Can you provide a log of when this happens?  That would help in understanding what is actually going on...Thanks!

**Comment by claywilkinson** [comment]
See #379
