### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by kasradzenika** [playgameservices/play-games-plugin-for-unity#413]
I've been trying to authenticate for ages now, on various devices, with various test users. no luck, I have this repeating log in my logcat outputs:

 D/AppStateService(27962): client connected with version: 6587000
 V/GamesNativeSDK( 2832): Play Games callback indicates connection failure.
 I/GamesNativeSDK( 2832): UI interaction required to connect to Google Play.

please help :/

**Comment by tomscript** [comment]
what was the solution / problem here?
