### ISSUE TITLE
Get All TurnBased Matches Info from GooglePlayServices, Unity Plugin

### ISSUE THREAD

**Issue by amirlatif** [playgameservices/play-games-plugin-for-unity#414]
(apologies, also posted at StackOverflow here : http://stackoverflow.com/questions/28582503/get-all-turnbased-matches-info-from-googleplayservices-unity-plugin, I can remove if this is bad form)

I'm using the TicTacToss code as a basis for a turn based game on android in Unity, using this : https://github.com/playgameservices/play-games-plugin-for-unity

Everything is working great, but there's no functionality exposed to return a list of games the current user is engaged in, active and completed. I need this for the main UI, so I can show the user what games they are playing, against whom etc. Without, this API seems pretty lacking.

Has anyone been able to get this going? Seems to me that the functionality might be there, as there is a function called GetAllTurnbasedMatches(), but my C# isn't strong enough to understand how it works. (see in https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Platforms/Native/PInvoke/TurnBasedManager.cs)

**Comment by claywilkinson** [comment]
Hi @amirlatif - thanks for the question - This has been marked as an enhancement in https://github.com/playgameservices/play-games-plugin-for-unity/issues/256  - I am closing this issue to consolodate  into the other.  Please re-open this if you think these are not actually the same issue.

**Comment by amirlatif** [comment]
I fixed the issue by adding the following to NativeTurnBasedMultiplayerClient.cs, works for me:

    public void GetAllTBMatches(Action<TurnBasedMatch, TurnBasedMatch.MatchTurnStatus> callback)
    {
        mTurnBasedManager.GetAllTurnbasedMatches(allMatches =>
        {
            foreach (var match in allMatches.MatchesMyTurn())
            {
                var converted = match.AsTurnBasedMatch(mNativeClient.GetUserId());
                Logger.d("MY turn : Passing converted match to user callback:" + converted);
                callback(converted, TurnBasedMatch.MatchTurnStatus.MyTurn);
            }
            foreach (var match in allMatches.MatchesTheirTurn())
            {
                var converted = match.AsTurnBasedMatch(mNativeClient.GetUserId());
                Logger.d("Their Turn : Passing converted match to user callback:" + converted);
                callback(converted, TurnBasedMatch.MatchTurnStatus.TheirTurn);
            }
            foreach (var match in allMatches.MatchesCompleted())
            {
                var converted = match.AsTurnBasedMatch(mNativeClient.GetUserId());
                Logger.d("Completed : Passing converted match to user callback:" + converted);
                callback(converted, TurnBasedMatch.MatchTurnStatus.Complete);
            }

            callback(null, TurnBasedMatch.MatchTurnStatus.Unknown);
        });
    }

    public void GetAllTBInvitations(Action<Invitation> callback)
    {
        mTurnBasedManager.GetAllTurnbasedMatches(allMatches =>
        {
            foreach (var invitation in allMatches.Invitations())
            {
                var converted = invitation.AsInvitation();
                Logger.d("Passing converted invitation to user callback:" + converted);
                callback(converted);
            }
        
            callback(null);
        });
    }

**Comment by Hoffa25** [comment]
Wow, awesome work amirlatif:)! I have been stuck on this problem for a week now and you might be my savior! However I cant get your code to work (yet). When i paste your code into the file the "public void GetAllTBMatches" have alot of errors (red text). The other one; "public void GetAllTBInvitations" however has no errors. After removing the "public void GetAllTBMatches"-code i tried to call the "public void GetAllTBInvitations"  by the following code but it cant find the method (from another script were I call the other methods in NativeTurnBasedMultiplayerClient.cs ): 

PlayGamesPlatform.Instance.TurnBased.(Here the method GetAllTBInvitations should be shown in editor) 

I have tried both plugin 9.12 and 9.11 and neither works:/. My unity is version 4.6.1f1

Any ideas why this isnt working for me? I have only been programming for about half a year and in C# and unity only so it might be a really silly mistake from my part...

Regards, Erik

**Comment by amirlatif** [comment]
Hey Erik.  Did you add the declarations to the interface IRealTimeMultiplayerClient and ITurnBasedMultiplayerClient?  Just checking my code and that's all I added.  I don't really know my way around github to well, but I suppose I could try and add a fork if you're still stuck.

**Comment by Hoffa25** [comment]
Hi! Thanks for a very quick answer! No I did not add the declarations:). Now your function GetAllTBInvitations show up in editor. As I wrote before Im still kind of new to this... I dont really understand what I should put in after this PlayGamesPlatform.Instance.TurnBased.GetAllTBInvitations(?

I was thinking it would return som kind of string list with invitiatio IDs...?

Any Idea why your other function doesnt work for me? Editor fills following words with red (CAP in this text):

 foreach (VAR match in allMatches.MATCHESMYTURN())
        {
            VAR converted = match.ASTURNBASEDMATCH(mNativeClient.GetUserId());
            Logger.d("MY turn : Passing converted match to user callback:" + converted);
            callback(converted, TurnBasedMatch.MatchTurnStatus.MyTurn);
        }
same thing happens in the rest of the method...

//Erik

**Comment by amirlatif** [comment]
What's the error message you're getting?

For example, when you call the invitations functions, you need to do something like this

PlayGamesPlatform.Instance.TurnBased.GetAllTBInvitations(OnGetTBInvitations);

Where OnGetTBInvitations is defined as 

protected void OnGetTBInvitations(Invitation invitation)
{
}

**Comment by Hoffa25** [comment]
Thanx for a good explanation! I now recieve the invitation:). I have checked that it has the same ID string as when it first was fired (i made an invite first with game running, the popup came and i could read the ID, i then restarted the game and called your function to get it again and the popup appeared a with the same ID string, like magic :D). However for some very strange reason I cant use the string to call for example the decline invitation function: 		PlayGamesPlatform.Instance.TurnBased.DeclineInvitation(invitation.InvitationId);

Nothing happens and nothing after that line gets executed...

Regarding the other problem with the red text in the other method:
If I hold my mouse pointer on the red error text the following error message shows up:

https://www.dropbox.com/s/98mn2pdcu9knnzt/RedText.jpg?dl=0

its the same message for every red text exept the "var" then it says "unknown resolve error"

If I can get this to work I hope I will find some way to use the methods to track players who uses the "dismiss game option" in googles matches default UI. Also solve the problems occuring when players dont want to open a match result they know is a loss.... resulting in my game not being able to fetch the result of that game for that player... You must have the same problems I assume? Or do you use some kind of external service to track players wins and losses? 

What kind of game are you making anyways:)? Is this also your first? My game is a turn based game, kind of a quiz/puzzle game with multimedia "questions". Doing everything by myself with no background in gaming, graphics or programing so its kind of a big task. Wouldnt be possible if it wasnt for all youtube tutorilas and helpfull people on forums! An average of 10-12 hours every day for halv a year now... Hopefully I will get there in another 2-3 months:).

**Comment by claywilkinson** [comment]
@amirlatif  - Nice work! Are you still planning to fork and hopefully make a pull request to integrate it back into the main plugin?

**Comment by amirlatif** [comment]
@Hoffa25 My bad, there's more code to be added to https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Platforms/Native/PInvoke/TurnBasedManager.cs

    internal class TurnBasedMatchesResponse : BaseReferenceHolder {
        internal TurnBasedMatchesResponse(IntPtr selfPointer) : base(selfPointer) {
        }

        protected override void CallDispose(HandleRef selfPointer) {
            C.TurnBasedMultiplayerManager_TurnBasedMatchesResponse_Dispose(SelfPtr());
        }

        internal CommonErrorStatus.MultiplayerStatus Status() {
            return C.TurnBasedMultiplayerManager_TurnBasedMatchesResponse_GetStatus(SelfPtr());
        }

        internal IEnumerable<MultiplayerInvitation> Invitations()
        {
            return PInvokeUtilities.ToEnumerable(
                C.TurnBasedMultiplayerManager_TurnBasedMatchesResponse_GetInvitations_Length(SelfPtr()),
                index => new MultiplayerInvitation(C.TurnBasedMultiplayerManager_TurnBasedMatchesResponse_GetInvitations_GetElement(SelfPtr(), index)));
        }

        internal IEnumerable<NativeTurnBasedMatch> MatchesMyTurn()
        {
            return PInvokeUtilities.ToEnumerable(
                C.TurnBasedMultiplayerManager_TurnBasedMatchesResponse_GetMyTurnMatches_Length(SelfPtr()),
                index => new NativeTurnBasedMatch(C.TurnBasedMultiplayerManager_TurnBasedMatchesResponse_GetMyTurnMatches_GetElement(SelfPtr(), index)));
        }

        internal IEnumerable<NativeTurnBasedMatch> MatchesTheirTurn()
        {
            return PInvokeUtilities.ToEnumerable(
                C.TurnBasedMultiplayerManager_TurnBasedMatchesResponse_GetTheirTurnMatches_Length(SelfPtr()),
                index => new NativeTurnBasedMatch(C.TurnBasedMultiplayerManager_TurnBasedMatchesResponse_GetTheirTurnMatches_GetElement(SelfPtr(), index)));
        }

        internal IEnumerable<NativeTurnBasedMatch> MatchesCompleted()
        {
            return PInvokeUtilities.ToEnumerable(
                C.TurnBasedMultiplayerManager_TurnBasedMatchesResponse_GetCompletedMatches_Length(SelfPtr()),
                index => new NativeTurnBasedMatch(C.TurnBasedMultiplayerManager_TurnBasedMatchesResponse_GetCompletedMatches_GetElement(SelfPtr(), index)));
        }

        internal static TurnBasedMatchesResponse FromPointer(IntPtr pointer)
        {
            if (PInvokeUtilities.IsNull(pointer)) {
                return null;
            }

            return new TurnBasedMatchesResponse(pointer);
        }
    }

**Comment by amirlatif** [comment]
@Hoffa25 For the decline, I use the following, and it works silently, the game no longer appears in my list.  Sorry I can't be more help:

PlayGamesPlatform.Instance.TurnBased.DeclineInvitation(info.invite.InvitationId);

@claywilkinson Cheer dude, will try and set aside some work this weekend and figure out what I need to do.

**Comment by Hoffa25** [comment]
Wohoo :D!! With the added code it works perfectly. Cant thank you enough amirlatif!

**Comment by adepase** [comment]
Wonderful, thank you @amirlatif !! Only... it takes a return after every callback before the last one, else it will continue executing to the last callback, giving the following low level error:
W/InputDispatcher(  791): channel ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  791): channel ~ Channel is unrecoverably broken and will be disposed!

Adding the return line corrects this and it works like a charm.
Thank you again

**Comment by adepase** [comment]
@claywilkinson : I would keep this and consolidate the #256 here, because this one is more extended, dealing also with matches and not only with invitations. More, this thread also answers to my previous #348, implementing (with the last correction of adding the return after the first callbacks) exactly what I asked for in that issue. I hope it will be consolidated asap in the standard code of the plugin, so not to have to merge it continuously... :)

**Comment by Hoffa25** [comment]
adepase: im kind of a noob and dont understand were I should add the return line? ...and the return line is what exactly :)? 
...im having problems with the code often giving me incorect info about ongoing matches and im hoping your fix will solve this!

**Comment by adepase** [comment]
@Hoffa25: I mean that in the class NativeTurnBasedMultiplayerClient the code should be corrected like this:

public void GetAllTBMatches(Action<TurnBasedMatch, TurnBasedMatch.MatchTurnStatus> callback)
{
    mTurnBasedManager.GetAllTurnbasedMatches(allMatches =>
    {
        foreach (var match in allMatches.MatchesMyTurn())
        {
            var converted = match.AsTurnBasedMatch(mNativeClient.GetUserId());
            Logger.d("MY turn : Passing converted match to user callback:" + converted);
            callback(converted, TurnBasedMatch.MatchTurnStatus.MyTurn);
            return;
        }
        foreach (var match in allMatches.MatchesTheirTurn())
        {
            var converted = match.AsTurnBasedMatch(mNativeClient.GetUserId());
            Logger.d("Their Turn : Passing converted match to user callback:" + converted);
            callback(converted, TurnBasedMatch.MatchTurnStatus.TheirTurn);
            return;
        }
        foreach (var match in allMatches.MatchesCompleted())
        {
            var converted = match.AsTurnBasedMatch(mNativeClient.GetUserId());
            Logger.d("Completed : Passing converted match to user callback:" + converted);
            callback(converted, TurnBasedMatch.MatchTurnStatus.Complete);
            return;
        }

        callback(null, TurnBasedMatch.MatchTurnStatus.Unknown);
    });
}

public void GetAllTBInvitations(Action<Invitation> callback)
{
    mTurnBasedManager.GetAllTurnbasedMatches(allMatches =>
    {
        foreach (var invitation in allMatches.Invitations())
        {
            var converted = invitation.AsInvitation();
            Logger.d("Passing converted invitation to user callback:" + converted);
            callback(converted);
            return;
        }

        callback(null);
    });
}

I don't think that this is the correction that can help you: this correction just avoid the death of the game (at least this happens for me). If your list is incorrect, I suggest to consider:
- where you ask for the list (if just in the start/awake method it's wrong, if in the update method maybe too much... remember the onApplicationPause(bool paused) to manage interruptions for calls and various alarms
- the delegates which have to manage the different notifications. In my tests these are not so consistent (see #348 where I commented a number of conditions in which they are not)
- it's very different if you work on the same scene, as in the demo TicTacToss or if you are in different scenes: in case you are in different scenes, be careful to re-register delegates when needed (see again my comments un #348) and maybe also re-calculate the list when your scene starts and so on. If you work on the same scene, I think it helps keeping consistency if you ask for a new list at the end of every game
- obviously, you have to consider that the demo TicTacToss only manages a single notification, if you need to keep more (as usually in real life) you need a Collection...

I hope this can help

**Comment by adepase** [comment]
Sorry, after testing a little more I think that the code posted above is buggy. I'm developing that even now, but the return is too strong and it avoid the loop after the first item.
I think it's better to add a boolean variable to set to true, in place of the return, if the loop happens at least once, and to execute the last callback only if it is false... however, as I told before, I'm testing this just now and I will post my code when fixed (in a better format than last time :) )

**Comment by adepase** [comment]
After a little testing, it seems to me that the fix is simpler: just delete the last callback:

```C#
	public void GetAllTBMatches(Action<TurnBasedMatch, TurnBasedMatch.MatchTurnStatus> callback)
	{
		mTurnBasedManager.GetAllTurnbasedMatches(allMatches =>
		                                         {
			
				foreach (var match in allMatches.MatchesMyTurn())
				{
					var converted = match.AsTurnBasedMatch(mNativeClient.GetUserId());
					callback(converted, TurnBasedMatch.MatchTurnStatus.MyTurn);
				}
				foreach (var match in allMatches.MatchesTheirTurn())
				{
					var converted = match.AsTurnBasedMatch(mNativeClient.GetUserId());
					callback(converted, TurnBasedMatch.MatchTurnStatus.TheirTurn);
				}
				foreach (var match in allMatches.MatchesCompleted())
				{
					var converted = match.AsTurnBasedMatch(mNativeClient.GetUserId());
					callback(converted, TurnBasedMatch.MatchTurnStatus.Complete);
				}
				
			
		});
	}
	
	public void GetAllTBInvitations(Action<Invitation> callback)
	{
		mTurnBasedManager.GetAllTurnbasedMatches(allMatches =>
		                                         {
			foreach (var invitation in allMatches.Invitations())
			{
				var converted = invitation.AsInvitation();
				callback(converted);
			}
		});
	}
```
This way you avoid the closed input channel and allow for the loop to complete...
Please, if someone (above all @amirlatif who wrote the code itself, adding the callback) has some reason not to cancel the last line (but also to manage the closed input channel issue), let us know.
