### ISSUE TITLE
Real-Time Multiplayer crashes on iOS

### ISSUE THREAD

**Issue by bekiryanik** [playgameservices/play-games-plugin-for-unity#416]
Hello everyone,
I've actually setup everything about Real-Time Multiplayer for android and iOS but i have two problems. 

One of them is; i've one android and one iOS device. When i build my project to these devices, i can't start a multiplayer game. My iOS device is an iPOD touch 5th gen. On Debug screen, i can see that they connect on the same room but game doesn't start after they connect to lobby. Everything seems pretty good but it doesn't start. When i run the project on iOS simulator, i can start a real-time multiplayer game with my android device. But on iPod, it doesn't.

The other one is about inviting friends. From my android device, i can make invitations and i can see these invitations on both iPod and simulator, and i can accept them and join the game. But, when i want to send an invitation from iPod or simulator, i can't send it. Device freezes and i get an error from xCode. For short, i can't send invitation from iOS.

How can i fix these problems?

Thanks!

**Comment by gguuss** [comment]
Is the plugin working for you in the iOS simulator?

**Comment by gguuss** [comment]
A few things worth checking:
* Did you add all of the test accounts to the Play Games Services console?
* Did you enable RTMP?

What is the error you are getting from the simulator?

**Comment by bekiryanik** [comment]
Yes, i added all of the test accounts to the Play Game services console and i enabled RTMP. Here is the errors i get from xCode;

When i want to start a multiplayer game between iPod 5 Gen and Android device, i get this error;
This error is from debug screen of xCode;

[CODE]
2015-02-26 12:12:38.298 Testproject[849:353743] INFO: OP: 1
2015-02-26 12:12:38.309 Testproject[849:353743] INFO: CALL_STATE_CHANGED_OP: New state: 1
2015-02-26 12:12:38.311 Testproject[849:353743] ERROR: peer_capabilities must not be null in PeerStateMachine::WaitingForConnectionData
2015-02-26 12:12:38.313 Testproject[849:353743] INFO: PeerStateMachine: WaitingForOutgoingRemoteConnectionNoSessionId-2f4jxbc38b8md23ga4w9unkbny@public.talk.google.com/games_andr43CE6F5D transitionTo WaitingForConnectionData-2f4jxbc38b8md23ga4w9unkbny@public.talk.google.com/games_andr43CE6F5D
2015-02-26 12:12:43.559 Testproject[849:353561] ERROR:  - unhandledMessage: message.type=48
2015-02-26 12:13:08.849 Testproject[849:353743] INFO: OP: 6
2015-02-26 12:13:08.852 Testproject[849:353743] INFO: CALL_STATE_CHANGED_OP: New state: 6
2015-02-26 12:13:08.853 Testproject[849:353743] INFO: PeerStateMachine: Not handled -- invoking default handler for:7002
2015-02-26 12:13:08.854 Testproject[849:353743] ERROR:  - unhandledMessage: message.type=7002
2015-02-26 12:13:08.858 Testproject[849:353743] INFO: OP: 14
2015-02-26 12:13:08.859 Testproject[849:353743] INFO: CALL_STATE_CHANGED_OP: New state: 14
2015-02-26 12:13:08.860 Testproject[849:353743] INFO: PeerStateMachine: Not handled -- invoking default handler for:7002
2015-02-26 12:13:08.861 Testproject[849:353743] ERROR:  - unhandledMessage: message.type=7002
[/CODE]

Game doesn't start between iPad and Android device. But on iOS simulator, game starts between Android device and iOS simulator.

The other one is about inviting friends. When i invite my other Google Account(Which is signed in iPod) from android device, i can see the invitation and i can accept it. But as you might guess, game doesn't start on iPod. But, when i make invitation from iPod, i get these errors;

[CODE]
This one comes from; main.mm /main(int argc, char* argv[])
UIApplicationMain(argc, argv, nil, [NSString stringWithUTF8String:AppControllerClassName]);

And the others appear on debug screen of xCode;
2015-02-26 12:40:17.584 Testproject[906:359525] Failed to load font: Error Domain=com.apple.CoreText.CTFontManagerErrorDomain Code=101 "The operation couldn’t be completed. (com.apple.CoreText.CTFontManagerErrorDomain error 101 - Could not register the font file(s))" UserInfo=0x198d2e40 {CTFontManagerErrorFontURLs=(
    "file:///private/var/mobile/Containers/Bundle/Application/C48FBC03-0AA6-4AE7-839A-6C4C6A68D20A/Testproject.app/QuantumCoreFonts.bundle/Roboto-Regular.ttf"
), NSDescription=Could not register the font file(s)}
2015-02-26 12:40:17.650 Testproject[906:359525] Failed to load font: Error Domain=com.apple.CoreText.CTFontManagerErrorDomain Code=101 "The operation couldn’t be completed. (com.apple.CoreText.CTFontManagerErrorDomain error 101 - Could not register the font file(s))" UserInfo=0x199e26a0 {CTFontManagerErrorFontURLs=(
    "file:///private/var/mobile/Containers/Bundle/Application/C48FBC03-0AA6-4AE7-839A-6C4C6A68D20A/Testproject.app/QuantumCoreFonts.bundle/Roboto-Medium.ttf"
), NSDescription=Could not register the font file(s)}
2015-02-26 12:40:17.803 [Core] (Error) +[GPGLocalization stringForId:]:[main] Failed to find string for [matches_create_selection_bar] in bundle [(null)]
2015-02-26 12:40:18.298 Testproject[906:359525] Unbalanced calls to begin/end appearance transitions for <GPGLauncherWindowRootViewController: 0x198d1200>.
2015-02-26 12:40:18.379 [Core] (Error) +[GPGLocalization stringForId:]:[main] Failed to find string for [multiplayer_autoselect_cell] in bundle [(null)]
2015-02-26 12:40:18.379 [Core] (Error) +[GPGLocalization stringForId:]:[main] Failed to find string for [people_picker_recently_played] in bundle [(null)]
2015-02-26 12:40:59.745 Testproject[906:359525] Uncaught exception: NSInvalidArgumentException: *** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument
(
	0   CoreFoundation                      0x2721d60f <redacted> + 150
	1   libobjc.A.dylib                     0x34957c77 objc_exception_throw + 38
	2   CoreFoundation                      0x2721d53d <redacted> + 0
	3   Foundation                          0x27e614b1 <redacted> + 96
	4   Foundation                          0x27e613d5 <redacted> + 60
	5   Testproject           0x00fc3c85 -[GPGPlayerPickerViewController updateCollectionViewAndFooterViewWithAnimation] + 892
	6   Testproject           0x00fc266b -[GPGPlayerPickerViewController collectionView:didSelectItemAtIndexPath:] + 1566
	7   UIKit                               0x2a8c5c51 <redacted> + 152
	8   UIKit                               0x2a8c595b <redacted> + 434
	9   UIKit                               0x2a83fc91 <redacted> + 236
	10  UIKit                               0x2a83fc91 <redacted> + 236
	11  UIKit                               0x2a83fc91 <redacted> + 236
	12  UIKit                               0x2a83fc91 <redacted> + 236
	13  UIKit                               0x2a83fc91 <redacted> + 236
	14  UIKit                               0x2a6b70b7 <redacted> + 10158
	15  UIKit                               0x2a6ec08d <redacted> + 784
	16  UIKit                               0x2a6eb95d <redacted> + 520
	17  UIKit                               0x2a6c20e5 <redacted> + 196
	18  UIKit                               0x2a935ba3 <redacted> + 13874
	19  UIKit                               0x2a6c0b27 <redacted> + 1294
	20  CoreFoundation                      0x271e3fd7 <redacted> + 14
	21  CoreFoundation                      0x271e33eb <redacted> + 222
	22  CoreFoundation                      0x271e1a69 <redacted> + 768
	23  CoreFoundation                      0x2712eb31 CFRunLoopRunSpecific + 476
	24  CoreFoundation                      0x2712e943 CFRunLoopRunInMode + 106
	25  GraphicsServices                    0x2e4e5051 GSEventRunModal + 136
	26  UIKit                               0x2a720f21 UIApplicationMain + 1440
	27  Testproject           0x0008cf20 main + 308
	28  Testproject           0x0008cde8 start + 40
)
2015-02-26 12:40:59.750 Testproject[906:359525] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument'
*** First throw call stack:
(0x2721d5f7 0x34957c77 0x2721d53d 0x27e614b1 0x27e613d5 0xfc3c85 0xfc266b 0x2a8c5c51 0x2a8c595b 0x2a83fc91 0x2a83fc91 0x2a83fc91 0x2a83fc91 0x2a83fc91 0x2a6b70b7 0x2a6ec08d 0x2a6eb95d 0x2a6c20e5 0x2a935ba3 0x2a6c0b27 0x271e3fd7 0x271e33eb 0x271e1a69 0x2712eb31 0x2712e943 0x2e4e5051 0x2a720f21 0x8cf20 0x8cde8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
[/CODE]

These are the errors.

Thank you so much!
Have a great day!

**Comment by ZenithCode** [comment]
I have a similar problem in my game.  You can check out the video of the bug here:
https://dl.dropboxusercontent.com/u/9385978/Google%20Play%20Games%20-%20does%20not%20work%20on%20iOS.mp4

I got the project from here (tutorial):
http://www.raywenderlich.com/89724/creating-cross-platform-multiplayer-game-unity-part-4

**Comment by bekiryanik** [comment]
Hey Zenith,
Actually i take a look at Quiz Racer project and it has the same problem. I think, there is something wrong with the google play services for iOS devices. Real-time Multiplayer game only starts between Android device and iOS simulator as it seems.

**Comment by claywilkinson** [comment]
I think we have a lead on this issue - please stand by...

**Comment by timmay2t** [comment]
This has been an issue from the beginning, you can't connect 2 iOS devices together even in the sample that comes with the plugin from google.  This issue has prevented us from releasing multiplayer to our customers for almost 2 months now.

**Comment by bekiryanik** [comment]
Okay claywilkinson. We will be waiting for good news. :) Thank you!

I hope they fix it as soon as possible timmay2t.

**Comment by ZenithCode** [comment]
@claywilkinson Problem is still there after upgrading 0.9.15

**Comment by timmay2t** [comment]
@claywilkinson Is this an iOS issue do you think?  I see that there is some google  login updates coming to iOS 8.3, we're just trying to figure out if this is a problem that will be solved anytime soon, or if we need to move on from GPG and use Photon.

**Comment by claywilkinson** [comment]
We're working on it  - I don't know the exact timing, but it is definitely an urgent issue. I'll definitely update everyone when I know more!

**Comment by ZenithCode** [comment]
@claywilkinson should the release of SDK 7.0 affect any of these pending bugs?

**Comment by timmay2t** [comment]
@claywilkinson is there anything to report about this yet?  The only reason we chose GPG was for cross platform gaming, it's seems pretty ridiculous that such a huge feature has been broken since mid-December with no fix in sight.  Extremely frustrated right now.

**Comment by ZenithCode** [comment]
Yes @claywilkinson @timmay2t - the new SDK did not help with this particular problem! Not sure why its taking so long...

There should have been an update right after GDC - when will it be made available?  @samtstern @ToddKerpelman

**Comment by claywilkinson** [comment]
@timmay2t , @ZenithCode , (and others) the iOS fix is actually in the iOS C++ SDK which should be out very soon.  This SDK is the package that contains gpg.bundle and gpg.framework.  As soon as I know the exact time, I will update this thread.  Thanks for the patience!

**Comment by claywilkinson** [comment]
@timmay2t , @ZenithCode  - the new SDK (version 1.4) should be out tonight/tomorrow at https://developers.google.com/games/services/downloads/

**Comment by ZenithCode** [comment]
Hi @claywilkinson, is gpg.bundle a replacement for GooglePlayGames.bundle?

I can't get the project to build with the new SDK's - Missing GooglePlus/GooglePlus.h

I tried with both gpg.bundle and GooglePlayGames.bundle together and with each individual.
Can you guide me on how to get this to build please?

**Comment by claywilkinson** [comment]
I just did a clean build of the QuizRacer sample and everything worked.  Here are xcode steps I performed:
Downloaded 
https://developers.google.com/games/services/downloads/gpg-cpp-sdk.v1.4.zip
http://goo.gl/9cTqyZ - Google+ for iOS

1. added GPGS plugin
2. added QuizRacer_4.6
3. Changed project to iOS
4. Copied client id and bundle id from play console
5. Generated the xcode project
6. Followed instructions in dialog presented in unity 
( link to instructions file: https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Editor/ios_instructions)
7. In XCode: selected the project navigator
8. Then the build settings section, scroll down to Linking, and added -ObjC to other linker flags
9.Then click "Build Phases" section, then expanded "Link Binaries with Files"
10. clicked the "+" to add libraries.  Selected from the list (holding down command key to select multiple files)
    - AddressBook.framework
    - AssetsLibrary.framework
    - CoreData.framework
    - CoreTelephony.framework
    - CoreText.framework
    - Security.framework
    - libc++.dylib
    - libz.dylib
11. In the Project Navaigator, expand and select "Frameworks"
12. In Finder, drag and drop from the Google+ iOS sdk into the Frameworks:
    Note: Make sure to check "Copy if needed" in the file options dialog prompt
    - GoogleOpenSource.framework
    - GooglePlus.framework
    - GooglePlus.bundle 
13. In Finder, drag and drop from Google Play Games C++ SDK 1.4 into the Frameworks:
    Note: Make sure to check "Copy if needed" in the file options dialog prompt
    - gpg.framework
    - gpg.bundle

**Comment by ZenithCode** [comment]
@claywilkinson - thanks for the detailed info.
I've tried the above several times on an existing project and even on a new project and I always get gpg/ios_support.h file not found as below.

Unity 4.6.1
Xcode 6.2

![ios support h not found](https://cloud.githubusercontent.com/assets/1938034/6942182/1593f6fc-d886-11e4-8ec3-c12d79b807a8.png)

**Comment by claywilkinson** [comment]
that file is definitely part of the gpg framework.  Can open the gpg.framework folder in xcode and confirm the file is there?  Maybe there is something weird about that framework when it is being added...

**Comment by ZenithCode** [comment]
@claywilkinson Yes the file is actually in there when I look it up in finder.

I just the drag the frameworks and bundles onto the project (just like I always did) and still get this error.

**Comment by claywilkinson** [comment]
Can you look out the downloaded zip file?  it should be > 100M in size.  The "bad" one is ~40M in size.  Can you download another copy of the sdk - maybe clearing your cache if the downloaded file is the smaller size?

**Comment by ZenithCode** [comment]
@claywilkinson the sdk was incorrect - I got the new one which is around 100Mb and 405Mb unpacked and its working fine now. (Realtime ios to Android game).

Inviting friends is still an issue. 
Android to Android - works fine
iOS to Android - works fine

Android to iOS - does not work.
iOS to iOS - does not work.

Any ideas about this?

**Comment by claywilkinson** [comment]
Thanks - let me look into this.

**Comment by ZenithCode** [comment]
Thanks @claywilkinson

**Comment by spotavi** [comment]
So as i see it , Real time MP between iOS and Android is not working. Is that the case with Turn Based MP too ?

We are hoping that all bugs are ironed out :) .

Also we noticed that finding a user for play in the users window does not list all your friends ? ( or is this because of the test account setup in console and would be fine when game is live ? )

**Comment by ZenithCode** [comment]
Confirmed fix in 0.9.20

**Comment by claywilkinson** [comment]
thanks!
