### ISSUE TITLE
Undefined symbols for architecture armv7: "_GpgUnlockAchievement"

### ISSUE THREAD

**Issue by sevansrhi** [playgameservices/play-games-plugin-for-unity#418]
I'm attempting to add the play-games-plugin-for-unity, but despite being very certain I've added the proper libraries, bundles, and packages to XCode, I keep getting errors such as:

>Undefined symbols for architecture armv7:
>"_GpgUnlockAchievement", referenced from:
>     RegisterMonoModules() in RegisterMonoModules.o
>...and so on

I have tried upgrading the plugin, getting the latest iOS C++ SDKs, and practically everything I can find on the internet.  Please help!

**Comment by gguuss** [comment]
Please share more information, what version of XCode are you using?  Also, are you starting from your own code or are you trying to import one of the basic samples?

**Comment by sevansrhi** [comment]
I'm starting from my own code, using the latest version of XCode (6.1).

**Comment by chenplayim** [comment]
I'm having the same problem
using googleplaygames latest version, unity 4.6.3f1 and other official pluggins  - Admob, OpenIAB, Vungle, AdColony,GameAnalytics and more.
Xcode version - 6.1.1

sample from errors log in Xcode - 

ld: warning: directory not found for option '-L"/Users/Tablet/Desktop/RYR_IOS_3.0.7_4/Libraries"'
ld: warning: directory not found for option '-F"/Users/Tablet/Desktop/RYR_IOS_3.0.7_4/Third-Party Frameworks" "/Users/Tablet/Desktop/RYR_IOS_3.0.7_4/UnityAds" "/Users/Tablet/Desktop/RYR_IOS_3.0.7_4/../YepiRunner_IOS_3.0.7/Assets/Editor/Vungle/VungleSDK" ""'
Undefined symbols for architecture armv7:
  "_TurnBasedMultiplayerManager_TurnBasedMatchesResponse_Dispose", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_TurnBasedMultiplayerManager_ShowMatchInboxUI", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_TurnBasedMultiplayerManager_Rematch", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_TurnBasedMultiplayerManager_PlayerSelectUIResponse_GetPlayerIds_Length", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_TurnBasedMultiplayerManager_PlayerSelectUIResponse_GetPlayerIds_GetElement", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_TurnBasedMultiplayerManager_MatchInboxUIResponse_GetStatus", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_TurnBasedMultiplayerManager_LeaveMatchDuringTheirTurn", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_TurnBasedMultiplayerManager_FetchMatch", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_TurnBasedMultiplayerManager_ConfirmPendingCompletion", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_TurnBasedMultiplayerManager_AcceptInvitation", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_TurnBasedMatch_Version", referenced from:


there are hundreds of these errors

please assist
thank you
chen

**Comment by claywilkinson** [comment]
Can you check that you added the correct games framework?  The one you should use is named gpg.framework (you can download it from  https://developers.google.com/games/services/downloads)

**Comment by sevansrhi** [comment]
Yep, that's the framework I downloaded and used.

**Comment by claywilkinson** [comment]
Hmm. maybe try to re-add it to the project?

**Comment by claywilkinson** [comment]
There was a bad copy of the SDK zip file on the website.  Can you download it again it should be ~100MB when unzipped. This should fix your problem.

**Comment by claywilkinson** [comment]
@sevansrhi  Please reopen this issue if you are still having problems.
