### ISSUE TITLE
[0.9.12] GoogleService is stopped

### ISSUE THREAD

**Issue by ddenghoo** [playgameservices/play-games-plugin-for-unity#421]
In the portrait mode does not occur, only occurs in a landscape mode.

![a2015-03-02 16 03 15](https://cloud.githubusercontent.com/assets/11274247/6445183/96dda5bc-c145-11e4-8e78-e90414eb314d.png)

1) Go to the Sharing Settings
2) Press the Back
3) Google Play Service is stopped.

Log is shown below.

03-03 00:58:42.073: E/AndroidRuntime(24070): FATAL EXCEPTION: main
03-03 00:58:42.073: E/AndroidRuntime(24070): Process: com.google.android.gms.ui, PID: 24070
03-03 00:58:42.073: E/AndroidRuntime(24070): java.lang.RuntimeException: Unable to stop activity {com.google.android.gms/com.google.android.gms.games.ui.client.achievements.ClientAchievementListActivity}: java.lang.IllegalStateException: GoogleApiClient instance not created yet
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3647)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3701)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at android.app.ActivityThread.access$1500(ActivityThread.java:161)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1318)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at android.os.Looper.loop(Looper.java:157)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at android.app.ActivityThread.main(ActivityThread.java:5356)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at dalvik.system.NativeStart.main(Native Method)
03-03 00:58:42.073: E/AndroidRuntime(24070): Caused by: java.lang.IllegalStateException: GoogleApiClient instance not created yet
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at com.google.android.gms.games.ui.q.w(SourceFile:639)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at com.google.android.gms.games.ui.q.onStop(SourceFile:433)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1230)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at android.app.Activity.performStop(Activity.java:5571)
03-03 00:58:42.073: E/AndroidRuntime(24070): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3642)

How can I solve this?

**Comment by ddenghoo** [comment]
GooglePlayGamesPlugin-0.9.07.unitypackage

This package does not occur both mode..

**Comment by claywilkinson** [comment]
Can you tell me the version of Google Play services you are using?

**Comment by ddenghoo** [comment]
Version of Google Play services is 6.7.76.
Version of Android OS is 4.4.2.
and My device model name is Samsung Galaxy S4 LTE-a

**Comment by claywilkinson** [comment]
Is this still happening for you?  I believe it has been fixed.
