### ISSUE TITLE
switching linker flag from ObjC to force_load for gpg in XCode produces a lot of duplicate symbols

### ISSUE THREAD

**Issue by mromih** [playgameservices/play-games-plugin-for-unity#422]
Hi,

I have a problem with linking. 

The case is that I have a lot of custom libs (I am using force_load to link them) and when I force_load gpg in XCode (instead of objc flag) it produces a lot of duplicate symbols. If I don't use force_load on gpg than I get  "unrecognized selector sent to class" error.

I cannot use objc linker flag because then I get duplicate symbols in other libs.

The question is how to resolve this issue?

Example of duplicate symbol error:

duplicate symbol _AES_cbc_encrypt in:
    gpg/libgpg.a(libgpg.a-armv7-master.o)
    gpg/libgpg.a(aes_cbc.o)
duplicate symbol _ASN1_BIT_STRING_get_bit in:
    gpg/libgpg.a(libgpg.a-armv7-master.o)
    gpg/libgpg.a(a_bitstr.o)
duplicate symbol _ASN1_BIT_STRING_set in:
    gpg/libgpg.a(libgpg.a-armv7-master.o)
    gpg/libgpg.a(a_bitstr.o)
duplicate symbol _ASN1_BIT_STRING_set_bit in:
    gpg/libgpg.a(libgpg.a-armv7-master.o)
    gpg/libgpg.a(a_bitstr.o)
...

Regards,
Matej

**Comment by claywilkinson** [comment]
Unfortunately at this time there is not a workaround regarding libgpg requiring -ObjC.
