### ISSUE TITLE
Question Login process

### ISSUE THREAD

**Issue by nonaxanon** [playgameservices/play-games-plugin-for-unity#423]
i have followed the setup process, but when i call Authenticate, logcat prints couldnt find class error. so the popup window never shows. i have latest unity latest plugin, what to do?

**Comment by claywilkinson** [comment]
Which class is it not finding?  Can you post the log?

**Comment by rutony** [comment]
I have that problem. Authenticate call success login. But dont showing login window.
Unity last version.

**Comment by claywilkinson** [comment]
Is the user already logged in? If so, then the user is silently logged in without prompting for the user if they have already previously run the game.  Please reopen this issue and include a log file of trying to log in  if you still have questions.
