### ISSUE TITLE
[Unity 5] Authentication always fails on Android.

### ISSUE THREAD

**Issue by AaronWalwyn** [playgameservices/play-games-plugin-for-unity#426]
Tried importing this package into a Unity5 project. The plugin works fine on iOS (authentication, leaderboards & achievements) however on Android the authentication always fails.

I also tried loading up the sample projects provided in the package and those also fail their authentication on Android.

**Comment by claywilkinson** [comment]
Hmm. I have not been having problems with Authentication.  All I had to do was delete the armeabi libraries and everything worked on Android.  Can you post what error you are getting in the log?  
A couple things to confirm:
1. You ran Android Setup from the GooglePlayGames menu in Unity.
2. The client id used in Unity matches the client id on the play console.
3. The bundle ID matches the package ID
4. The linked application for Android in the play game console has the same key fingerprint as the key you are signing the application with.

**Comment by AaronWalwyn** [comment]
Check through that list and realised I hadn't signed the application properly. Can confirm that it is now working. (Although I now feel silly)
