### ISSUE TITLE
After upgrading version still same

### ISSUE THREAD

**Issue by abalta** [playgameservices/play-games-plugin-for-unity#427]
I have downloaded and import 0.9.12 unity package as instruction says. But, version number still 0.9.11 on about section.

**Comment by claywilkinson** [comment]
Thanks for pointing that out.  There are not any functional changes between 0.9.11 and 0.9.12 so it should not be too big of an issue for you.  There will be a new version in the near future and we'll make sure the version number is updated :)

**Comment by abalta** [comment]
Thanks your quick reply, I am not sure upgrade the plugin, so I write this issue.

**Comment by claywilkinson** [comment]
Version 0.9.15 fixes this.
