### ISSUE TITLE
Move "Google Play Games" from Unity's top level menu

### ISSUE THREAD

**Issue by robertwahler** [playgameservices/play-games-plugin-for-unity#429]
Top level menu cruft breaks menus on smaller screens and is against Unity's code asset requirements. For an example of why this is a problem, please see section 5.3.1 here: http://unity3d.com/asset-store/sell-assets/submission-guidelines

A better choice would be to move the menus to a submenu in the "Window" top level menu.

**Comment by claywilkinson** [comment]
Thanks for the feedback - I'll add it to the list.

**Comment by Brookwellreuber** [comment]
Hello, I was poking around in the project and moved the menu items under window in  the editor.  Does this community follow any kind of special steps for adding to the project?

**Comment by claywilkinson** [comment]
You can see https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/CONTRIBUTING.md for the details.  Basically, we need to have a license agreement from you on file and submit a pull request, the owners review it, and it gets merged.
