### ISSUE TITLE
DirectoryNotFoundException: Could not find a part of the path

### ISSUE THREAD

**Issue by SamFZGames** [playgameservices/play-games-plugin-for-unity#435]
I'm getting an issue here... I'm using this plugin ONLY for the Android version of my game, so for iOS I'm using the NO_GPGS symbol. Problem is, when I go to build it, it throws this error:

DirectoryNotFoundException: Could not find a part of the path "/Users/SamFZGames/Dropbox/Documents/Development/XCode/JumpnShootAttack/Libraries/Plugins/iOS/GPGSAppController.mm".
System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.IO/FileStream.cs:292)
System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share)
(wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
System.IO.StreamWriter..ctor (System.String path, Boolean append, System.Text.Encoding encoding, Int32 bufferSize) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.IO/StreamWriter.cs:124)
System.IO.StreamWriter..ctor (System.String path, Boolean append)
(wrapper remoting-invoke-with-check) System.IO.StreamWriter:.ctor (string,bool)
GooglePlayGames.GPGSUtil.WriteFile (System.String file, System.String body) (at Assets/GooglePlayGames/Editor/GPGSUtil.cs:56)
GooglePlayGames.GPGSPostBuild.OnPostprocessBuild (BuildTarget target, System.String pathToBuiltProject) (at Assets/GooglePlayGames/Editor/GPGSPostBuild.cs:43)
UnityEditor.HostView:OnGUI()

I don't know why it'd do this when it's disabled on the iOS version anyway, but it's a big problem and we need to release real soon! ;_;

**Comment by claywilkinson** [comment]
Thanks for the details!
So I think the problem is you did not run ios setup from the google play games menu.  (It's a bug)
in the immediate term you can touch /Users/SamFZGames/Dropbox/Documents/Development/XCode/JumpnShootAttack/Libraries/Plugins/iOS/GPGSAppController.mm" so the file exists or in the OnPostprocessBuild method in the plugin, comment out the part that looks for GPGSAppController.mm

All it is doing is removing the contents of the file (and replacing them with a comment) so things will build.

We'll up the plugin  shortly so this won't happen again.
Good luck on your release!

**Comment by SamFZGames** [comment]
Thanks for responding so quickly!

Where is the OnPostprocessBuild method found?

**Comment by claywilkinson** [comment]
Assets/GooglePlayGames/Editor/GPGSPostBuild line 41.

**Comment by SamFZGames** [comment]
Ah yes! That makes sense now. Since it was looking for a file which was never generated.

However I now am having an error in XCode where it can’t find GooglePlus/GooglePlus.h.

**Comment by SamFZGames** [comment]
Sorry, disregard that last message, it was XCode being silly with cache’d stuff, needed to clean the project.
