### ISSUE TITLE
App close/quit/crashes whenever a match begins/comes in. Unity 4.6 and lollipop.

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#436]
The plugin has been working perfect for my until I upgraded my device to lollipop. Login, leaderboard achivements works as usual, but when a match (turnbased) comes in or starts the app just closes and the homescreen is shown!? I use 9.12 plugin.

//Hoffa

**Comment by claywilkinson** [comment]
@Hoffa25 - Is these still happening?  There was an update to the game services recently which may have addressed this issue.  Thanks!

**Comment by Hoffa25** [comment]
Yes its still happening. Maybe its because of my ImmersivMode plugin that I also have (forces absolute full screen on app). Im gonna try to remove it later... The reason why I think so is because it crashes also when I go from the matches and invites google default UI back to my game.

**Comment by Hoffa25** [comment]
Its working now... I updated my Unity to 4.6.4!
