### ISSUE TITLE
Namespace 'PluginVersion' does not exist in 'GooglePlayGames'

### ISSUE THREAD

**Issue by jpb18** [playgameservices/play-games-plugin-for-unity#437]
Hey all! So Unity is giving me this error after I imported the 0.9.15 into my project:

Assets/Editor/GPGSAndroidSetupUI.cs(168,49): error CS0234: The type or namespace name `PluginVersion' does not exist in the namespace `GooglePlayGames'. Are you missing an assembly reference?

So, what might that be?

**Comment by claywilkinson** [comment]
It should be in Assets/GooglePlayGames/PluginVersion.cs.  Is that file there?  If not, can you try re-importing the plugin and see if it is there afterwards?

**Comment by jpb18** [comment]
Yeah that worked. I guess Unity failed to import that file for some reason...
