### ISSUE TITLE
How to test on device?

### ISSUE THREAD

**Issue by SamFZGames** [playgameservices/play-games-plugin-for-unity#438]
Hey everybody,

I've set this all up as instructed for Android, set up all my leaderboards and achievements in google play developer, added my address to 'Testers', built the APK and sideloaded it to my device. When I run it, it doesn't even attempt (as far as I know) to sign in to Google Play Games Services, nor can I see it in 'My Games' in the Google Play Games app.

Am I doing something wrong?

**Comment by claywilkinson** [comment]
@SamFZGames - Did you figure out how to run the app and see the log using adb logcat (http://developer.android.com/tools/debugging/debugging-log.html)?

Setting up the play console can be a little touchy - I would suggest you review https://developers.google.com/games/services/console/enabling and look in the log for issues.
