### ISSUE TITLE
Not even attempting to log in

### ISSUE THREAD

**Issue by SamFZGames** [playgameservices/play-games-plugin-for-unity#439]
Hi there. For some reason, my device isn't even attempting to log in. Here's the code I used:

	void Awake () {

		// Activate the Google Play Games platform if running Android
		if (Application.platform == RuntimePlatform.Android) {
			PlayGamesPlatform.Activate ();
		}

	}

	void Start () {

		// Authenticate user
		if (!GameManager.isLoggedIn) {
			Social.localUser.Authenticate((bool success) => {
				GameManager.isLoggedIn = success;
				Debug.Log ((success) ? "Logged In" : "Not Logged In");
			});
		}
	
	}

The log in box never comes up at all... What have I missed?

**Comment by Lenemson** [comment]
Try to remove `if (Application.platform == RuntimePlatform.Android)` and wrap the activation like this instead
```
#if UNITY_ANDROID
   PlayGamesPlatform.Activate ();
#endif
```

and check the value of `GameManager.isLoggedIn`, it may be true at the begening?
Also the login modal will not appear in the unity editor, you have to test this on your mobile.

**Comment by SamFZGames** [comment]
I actually commented out the IF completely and it behaved the same :-/ I am testing on my device, not in Unity. I build an APK and sideload it through Dropbox.

**Comment by Lenemson** [comment]
If it's note the code, re read the readme.md and be sure you have followed all the steps.

Do you see your game in the developer console in the games services section?
Have you successfuly linked your android app? (with the corect SHA1 hash)
have you provided the right application ID to the unity plugin?
Have you signed your app with your .keystore (the same you extracted the SHA1 hash) ?

**Comment by SamFZGames** [comment]
Yes to all, further info below. It doesn’t appear to even attempt to sign in, as I put in some code to execute upon failure and it didn’t do that either. Is there any problem if I sideload the APK to my device?
> Do you see your game in the developer console in the games services section?
> 
Yeah, it’s status is “Ready to publish"
> Have you successfuly linked your android app? (with the corect SHA1 hash)
> 
I believe so. I uploaded the APK then went to Link App, and selected the bundle identifier, it automatically filled the hash in for me based on the APK.
> have you provided the right application ID to the unity plugin?
> 
Yessir.
> Have you signed your app with your .keystore (the same you extracted the SHA1 hash) ?
> 

Yeah.

**Comment by SamFZGames** [comment]
Hey - Should it test positive in the Unity editor? When running in the Unity editor, my debug log shows as not logged in, unless I comment out PlayGamesPlatform.Activate ();

**Comment by SamFZGames** [comment]
Hell, I just changed it to this:

    // Use this for initialization
    void Start () {

        // Activate the Google Play Games platform if running Android
        PlayGamesPlatform.Activate ();
        
        // Authenticate user
        //if (!GameManager.isLoggedIn) {
            Social.localUser.Authenticate((bool success) => {
                GameManager.isLoggedIn = success;
                Debug.Log ((success) ? "Logged In" : "Not Logged In");
                if (!success) {
                    Application.Quit ();
                }
            });
        //}
    
    }

And it still does nothing at all. If the login fails, it’d close the application altogether with Application.Quit (), but it doesn’t even do that. Clearly it’s not even attempting to log in.

The inclusions at the top:

using UnityEngine;
using System.Collections;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;
using UnityEngine.SocialPlatforms.GameCenter;

I’m thinking surely if I hadn’t set it up correctly in the developer console that it’d have closed the app due to failed login, wouldn’t it??

**Comment by Lenemson** [comment]
In the unity editor it should be false, probably because the app is signed with the debug key, and I don't know why but if I comment out PlayGamesPlatform.Activate (); it return true too, any way this is not a real true x)

> I’m thinking surely if I hadn’t set it up correctly in the developer console that it’d have closed the app  due to failed login, wouldn’t it??

I don't know, maybe the callback is never call if the oauth authentification hasn't been set properly.
Have you activated the alpha and beta testing options in the dev console? (testing section)

**Comment by SamFZGames** [comment]
OK, I’m confused, I’m trying to activate Beta testing to try it that way, how do I get the Beta out to the testers, without publishing it to the app store?? The documentation says to click Publish, but that’s greyed out until I move an APK to production, and if I click Publish when in production, it’ll publish it to the app store, which I don’t want.

**Comment by Lenemson** [comment]
In the Game center section, click on your game, then go in the testing section, the lasts setting are 2 otptions that you need to toggle, alpha testing then beta testing.
It is not necessary to publish for activate these

**Comment by SamFZGames** [comment]
OK, well I activated them and the APK still didn’t work, but I’m trying Beta testing instead of sideloading an APK now, just gotta wait for it to activate...

**Comment by SamFZGames** [comment]
OK, I even published the Google Play Services, enabled Alpha and Beta testing in the testing segment, published a Beta app and added myself as a Beta tester, followed the link and downloaded the beta to my device from the store, and it STILL doesn’t log in. It doesn’t even attempt to. I’ve set my code to this:

    void Start () {

        // Activate the Google Play Games platform if running Android
        if (Application.platform == RuntimePlatform.Android) {
            PlayGamesPlatform.Activate ();
            textMesh.text = "Activated PlayGamesPlatform";
        }
        
        // Authenticate user
        if (!GameManager.isLoggedIn) {
            textMesh.text = "Social.localUser.Authenticate";
            Social.localUser.Authenticate((bool success) => {
                GameManager.isLoggedIn = success;
                Debug.Log ((success) ? "Logged In" : "Not Logged In");
                textMesh.text = (success) ? "Logged In" : "Not Logged In";
            });
        }
    
    }

(I have tried it without both IF statements and it’s the same).

The textMesh shows up as “Social.localUser.Authenticate”, so it clearly gets that far. If the authentication failed it’d change the textMesh to “Not Logged In”, so it’s clear it’s not even trying to log me in.

I’ve set it up for Android with the right app ID etc.

I can’t for the life of me work out what else could possibly be going wrong. This should work.

**Comment by SamFZGames** [comment]
(It also doesn’t show up in my “My Games” in the Google Play Games app)

**Comment by SamFZGames** [comment]
If it helps, I'm using a Mac.

**Comment by SamFZGames** [comment]
I just opened up a new project and ran the MINIMAL example project. It just sticks on “Authenticating…”, so there’s obviously something wrong with my Android SDK or something...

**Comment by SamFZGames** [comment]
UPDATE:

Sorry for so many responses, but I think this is important. I moved 
over to my Windows laptop, installed Unity, Android SDK and Java, and 
built it on there, and it worked perfectly. The Unity project is 
exactly the same, the only difference is that I built it on Windows, 
not on Mac. So either there's some kind of incompatibility with Mac in 
this build, or something isn't installed right on my Mac. Any ideas?

**Comment by claywilkinson** [comment]
Hmm. Well I am glad you got your project to build.  I use a mac exclusively - and I don't think there is anything that would be a difference (other than things like can't find sdk, etc.).  Usually the problem with authentication is a configuration issue either in your app or on the play console.  Maybe compare your projects between windows and mac and see if there there is any difference?  Debug logs also might shed some light on the issue if you are still trying to figure it out.

**Comment by claywilkinson** [comment]
please open a new issue if you are still having issues.
