### ISSUE TITLE
No callback from ReportProgress in 0.9.15

### ISSUE THREAD

**Issue by hippogamesunity** [playgameservices/play-games-plugin-for-unity#440]
My setup:
var config = new GooglePlayGames.BasicApi.PlayGamesClientConfiguration.Builder().EnableSavedGames().Build();
GooglePlayGames.PlayGamesPlatform.InitializeInstance(config);
GooglePlayGames.PlayGamesPlatform.DebugLogEnabled = true;
GooglePlayGames.PlayGamesPlatform.Activate();
Social.Active.ReportProgress(ids[0], 100f, success =>
{
Debug.Log("success=" + success);

if (success)
...

**Comment by hippogamesunity** [comment]
Also I'm reporting already reported scores and have 0 steps to increment in log.

**Comment by claywilkinson** [comment]
Can you provide a log?  Usually there are some messages in the log file that point to the issues.

**Comment by hippogamesunity** [comment]
@claywilkinson This problem caused by code:
var config = new PlayGamesClientConfiguration.Builder().EnableSavedGames().Build();
GooglePlayGames.PlayGamesPlatform.InitializeInstance(config);

Without InitializeInstance plugin plugin works fine. Here my log, there is no more actions after "Steps to increment" so Achievements UI will no open:

OpenIABClient: initializing client...

OpenIABClient: options.checkInventoryTimeoutMs: 20000

OpenIABClient: options.discoveryTimeoutMs: 10000

OpenIABClient: options.verifyMode: VERIFY_SKIP

OpenIABClient: options.prefferedStoreNames: com.google.play

OpenIABClient: options.storeKeys: com.google.play:MIIBIjANBg...

OpenIABClient: subscribing events...

********** Android OpenIAB plugin initialized **********

OpenIABClient: mapping sku: [ussrsimulator.machine, ussrsimulator.machine]

OpenIABClient: mapping sku: [ussrsimulator.kingpin, ussrsimulator.kingpin]

OpenIABClient: mapping sku: [ussrsimulator.portrait, ussrsimulator.portrait]

OpenIABClient: mapping sku: [ussrsimulator.tube, ussrsimulator.tube]

OpenIABClient: mapping sku: [ussrsimulator.tea, ussrsimulator.tea]

OpenIABClient: mapping sku: [ussrsimulator.set, ussrsimulator.set]

GamesServicesClient: authentication...

 [Play Games Plugin DLL] 04/26/15 22:15:33 +03:00 DEBUG: Activating PlayGamesPlatform.

 [Play Games Plugin DLL] 04/26/15 22:15:33 +03:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform

 [Play Games Plugin DLL] 04/26/15 22:15:33 +03:00 DEBUG: Creating platform-specific Play Games client.

 [Play Games Plugin DLL] 04/26/15 22:15:33 +03:00 DEBUG: Creating real IPlayGamesClient

 [Play Games Plugin DLL] 04/26/15 22:15:33 +03:00 DEBUG: Entering state: BeforeRoomCreateStartedState

 [Play Games Plugin DLL] 04/26/15 22:15:33 +03:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.

 [Play Games Plugin DLL] 04/26/15 22:15:33 +03:00 DEBUG: Entering state: ShutdownState

 [Play Games Plugin DLL] 04/26/15 22:15:33 +03:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.

 [Play Games Plugin DLL] 04/26/15 22:15:34 +03:00 DEBUG: Invoking user callback on game thread

 [Play Games Plugin DLL] 04/26/15 22:15:34 +03:00 DEBUG: ReportProgress, CgkImeXpz9wFEAIQDQ, 100

 [Play Games Plugin DLL] 04/26/15 22:15:34 +03:00 DEBUG: Achievement is INCREMENTAL

 [Play Games Plugin DLL] 04/26/15 22:15:34 +03:00 DEBUG: Current steps: 100/100

 [Play Games Plugin DLL] 04/26/15 22:15:34 +03:00 DEBUG: Progress 100 interpreted as incremental target (approximate).

 [Play Games Plugin DLL] 04/26/15 22:15:34 +03:00 DEBUG: Target steps: 100, cur steps:100

 [Play Games Plugin DLL] 04/26/15 22:15:34 +03:00 DEBUG: Steps to increment: 0

**Comment by hippogamesunity** [comment]
@claywilkinson I found bug. It is caused by using incremental achievements as not incremental (in my case). I can fix issue in this way (replace > by >=):

Logger.d("Steps to increment: " + numSteps);
            if (numSteps > 0) {
                mClient.IncrementAchievement(achievementID, numSteps, callback);
            }

Logger.d("Steps to increment: " + numSteps);
            if (numSteps >= 0) {
                mClient.IncrementAchievement(achievementID, numSteps, callback);
            }

**Comment by hippogamesunity** [comment]
Hi! I found bug regression in 0.9.26

if (numSteps > 0)
