### ISSUE TITLE
Function CanRematch always return false?? Unity 4.6, plugin 9.12 and kitkat

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#444]
Has nobody but me tried to use this function!?  Example:

TurnBasedmatch MyMatch = ........;

MyMatch.CanRematch <----------- bool that always returns false regardless if the match can be rematched or not.

**Comment by claywilkinson** [comment]
This is a bug in the C++ SDK.  The next update of the unity plugin will work around it so it works correctly.

**Comment by Hoffa25** [comment]
Ok thanks, good to know!

**Comment by claywilkinson** [comment]
0.9.21 contains the workaround for canRematch to work correctly.
