### ISSUE TITLE
Minimal Sample: Label Problem - Connection failed not shown

### ISSUE THREAD

**Issue by DarioDomiDE** [playgameservices/play-games-plugin-for-unity#446]
Minimal Sample Label Problem:

if Connection failed, the Error Label is not shown, because is will overwritten by default "Ready"-Label next frame.

Remove in Script /samples/Minimal/Source/Assets/Minimal_Sample/MainGui.cs the line 61 "mStatusText = "Ready";", because this overwrites the "mStatusText = "Authentication failed.";" label in line 74

**Comment by claywilkinson** [comment]
This is fixed in version 0.9.20
