### ISSUE TITLE
Plugin not working on Ipod?

### ISSUE THREAD

**Issue by minhit1805** [playgameservices/play-games-plugin-for-unity#447]
After add plugin successful then i install my app to my ipod. Plugin has been crash and stop imediately when i call login game center on start game. But on my iphone 5s it's working normal. How to fix this bug or throw exception to disable this plugin on my Ipod??

**Comment by ZenithCode** [comment]
@minhit1805 Which iPod do you have and which iOS?

**Comment by minhit1805** [comment]
both of them is using IOS 8.2.

**Comment by ZenithCode** [comment]
What error do you get on XCode?  And are you using the latest SDK?

**Comment by minhit1805** [comment]
I have download the latest SDK version, i think it's working good. But my ipod doesn't have any google account login or create on it.

**Comment by ZenithCode** [comment]
So does it crash or simply does not login?  (If you don't have a Google account, it should exit the game and open a browser to log in there)

**Comment by minhit1805** [comment]
it being crash, the popup show up in 0.5second then close imediately.

**Comment by ZenithCode** [comment]
Can you share the xcode crash log please?

**Comment by minhit1805** [comment]
sorry i can't because my xcode is version 6.0 can't run with IOS 8.2, and i can't update to 6.3

**Comment by minhit1805** [comment]
i think the problem is plugin can't working if IOS device doesn't have any google account setup on it.

**Comment by claywilkinson** [comment]
Closing this one - please reopen and include log information of the failure you are encountering if it is still an issue.  Thanks!
