### ISSUE TITLE
No Callback when turn off internet connection

### ISSUE THREAD

**Issue by simsis3d** [playgameservices/play-games-plugin-for-unity#448]
In a realtime multiplayer match, no callback is fired when any of players turns off internet connection! Then both players think that match continue, but actually not!!

**Comment by ZenithCode** [comment]
@simsis3d -  OnPeersDisconnected(string[] participantIds) is not called?

**Comment by simsis3d** [comment]
@ZenithCode totally no, OnPeersDisconnected only works for sending application to background, but not for internet connection:/ By the way, what about IOS problems you are facing? I am about to publish my game to Google play and in a week I will publish to IOS but it seems it is impossible with these problems? I think I should find another multiplayer service:/

**Comment by ZenithCode** [comment]
@simsis3d - RTMP is finally working good on iOS with the latest SDK (1.4).  @claywilkinson is looking at an issue where iOS devices do not receive invitations but the rest is fine.

**Comment by claywilkinson** [comment]
@simsis3d  - regarding the internet connection issue, is this on iOS or Android?  Can you provide a log of what is going on?  That would help investigating the issue.  Thanks!!

**Comment by claywilkinson** [comment]
@simsis3d   - any more information on this issue, or can it be closed? (Are you talking about iOS or Android?  Can you provide a log?)  Thanks!

**Comment by sorab2142** [comment]
@simsis3d Before starting a multiplayer game, I perform an internet check myself by pinging say google.com and then call the CreateQuickGame function (if the ping worked) so as to avoid getting instantly disconnected by the callbacks. 

After starting a multiplayer game, I can confirm the call backs for player left are working correctly with the latest SDK.

**Comment by simsis3d** [comment]
The problem is still alive with GPG 0.9.25. I will close this one open a new one which will describe the problem more clearly.
