### ISSUE TITLE
GoogleOpenSource, file was built for unsupported file format

### ISSUE THREAD

**Issue by TimBayer** [playgameservices/play-games-plugin-for-unity#450]
I have followed the instructions here https://github.com/playgameservices/play-games-plugin-for-unity for building on iOS.  When I try and build the project in Xcode I am receiving:

ignoring file /Frameworks/GoogleOpenSource.framework/GoogleOpenSource, file was built for unsupported file format ( 0x56 0x65 0x72 0x73 0x69 0x6F 0x6E 0x73 0x2F 0x43 0x75 0x72 0x72 0x65 0x6E 0x74 ) which is not the architecture being linked (armv7)

I have added all the required frameworks:
AddressBook.framework
AssetsLibrary.framework
CoreData.framework
CoreTelephony.framework
CoreText.framework
Security.framework
libc++.dylib
libz.dylib
GoogleOpenSource.framework
GooglePlus.bundle
GooglePlus.framework
GooglePlayGames.bundle
gpg.framework

and added the -ObjC flag.

I have tried removing all the frameworks and re-adding them.  In Xcode I have the Architecture set to Standard(arm7, arm64) and the Build Active Architecture Only flag set to No.  This build is also using the IL2CPP option in Unity.  I've played with just about all the setting I think would affect this, but I am still receiving the errors.

**Comment by ZenithCode** [comment]
@TimBayer any luck resolving this? Are you using the latest SDK (1.4)?

**Comment by TimBayer** [comment]
Nope, no luck so far.  Yes I'm using the latest SDK, I got it from https://developers.google.com/games/services/downloads/

I realized the message in my last post was just a warning, though possibly still relevant.  Here are some of the actual errors I am receiving.  This is just a few of the 45 I am getting.

*Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_GTLQueryPlus", referenced from:
      objc-class-ref in gpg(GPGPlayerServiceMock.o)
      objc-class-ref in gpg(GPGPlayerPickerViewControllerDelegateMock.o)
      objc-class-ref in gpg(libgpg.a-armv7-master.o)
  "_OBJC_CLASS_$_GTLService", referenced from:
      _OBJC_CLASS_$_GTLServiceGames in gpg(GTLServiceGames.o)
     (maybe you meant: _OBJC_CLASS_$_GTLServiceGames)
  "_OBJC_METACLASS_$_GTLServiceTicket", referenced from:
      _OBJC_METACLASS_$_GPGServiceTicket in gpg(GPGService.o)
  "_OBJC_CLASS_$_GTLServiceTicket", referenced from:
      _OBJC_CLASS_$_GPGServiceTicket in gpg(GPGService.o)
  "_kGTMOAuth2ErrorUnsupportedGrantType", referenced from:
      ___49-[GPGService executeOperation:completionHandler:]_block_invoke in gpg(GPGService.o)
  "_kGTMOAuth2ErrorInvalidRequest", referenced from:
      ___49-[GPGService executeOperation:completionHandler:]_block_invoke in gpg(GPGService.o)
  "_OBJC_IVAR_$_GTLObject.childCache_", referenced from:
      -[GTLObject(GPGAdditions) encodeWithCoder:] in gpg(GTLObject+GPGAdditions.o)
      -[GTLObject(GPGAdditions) initWithCoder:] in gpg(GTLObject+GPGAdditions.o)
  "_kGTMOAuth2ErrorInvalidGrant", referenced from:
      ___49-[GPGService executeOperation:completionHandler:]_block_invoke in gpg(GPGService.o)
  "_kGTMOAuth2ErrorInvalidClient", referenced from:
      ___49-[GPGService executeOperation:completionHandler:]_block_invoke in gpg(GPGService.o)*

**Comment by claywilkinson** [comment]
Did you double check that you have the -ObjC linker flag?

**Comment by TimBayer** [comment]
Yes I have the -ObjC flag.  It is supposed to be under Build Settings > Other Linker Flags correct?  That is where I have it.  I also double checked the casing on it, it is correct.

**Comment by claywilkinson** [comment]
Hmm.. Apparently there was a problem with publishing the SDK library for iOS.   I have been notified it has been updated.  Can you download it again and see if it makes a difference (it should).

Also, there is a known issue with the GPGS plugin and IL2CPP - Both Unity and Google are looking into it.  Can you try using mono instead?

**Comment by TimBayer** [comment]
Downloaded the new version of the SDK and I upgraded to Unity 5.0.1 and the latest Xcode.  Everything appears to be working now, I have not actually tested on an ios app yet, but it's at least building now.

It also builds fine with I2CPP Universal, although it takes forever and its a huge app when it's done, but I think Unity is currently working on improving that.

**Comment by claywilkinson** [comment]
Thanks for the update!
