### ISSUE TITLE
NO_GPGS causes unreachable code warnings

### ISSUE THREAD

**Issue by robertwahler** [playgameservices/play-games-plugin-for-unity#453]
Setting NO_GPGS on any target generates warnings from GPGSPostBuild.cs

**Comment by GlassToeStudio** [comment]
I made that edit, no change in behavior. "Unreachable code"

Assets/GooglePlayGames/Editor/GPGSPostBuild.cs(47,13): warning CS0162: Unreachable code detected

**Comment by claywilkinson** [comment]
This is fixed in version 0.9.20 of the plugin.
