### ISSUE TITLE
Error building Player: IOException: android-support-v4.jar already exists

### ISSUE THREAD

**Issue by AyreGuitar** [playgameservices/play-games-plugin-for-unity#454]
After installing GooglePlayGamesPlugin-0.9.15.unitypackage in my Unity3D project and running the Android Setup successfully, when I try to build for Android I get this Unity error:
"Error building Player: IOException: Temp\StagingArea\plugins\android-support-v4.jar already exists"

Seems like Prime31 Etcetera plugin already has an android-support-v4.jar living in:
Assets/Plugins/Android/libs

And GooglePlayGamesPlugin adds one to:
Assets/Plugins/Android

via the GPGSAndroidSetupUI.cs script

Where should android-support-v4.jar live to resolve such conflicts in future?
Thanks!

**Comment by claywilkinson** [comment]
Thanks for the feedback - We'll add it to the list.

**Comment by claywilkinson** [comment]
This is fixed in version 0.9.20 of the plugin.  The jar file was moved to the libs directory to be consistent.
