### ISSUE TITLE
Not getting invitations on iOS

### ISSUE THREAD

**Issue by ZenithCode** [playgameservices/play-games-plugin-for-unity#455]
I am having problems getting invitations on iOS.  Invitations work fine on Android but never seem to get to an iOS device.

I am using the latest CPP SDK 1.4.

Summary:
Android to Android - works fine
iOS to Android - works fine

Android to iOS - does not work.
iOS to iOS - does not work.

Any ideas about this?

**Comment by ZenithCode** [comment]
Any updates on this @claywilkinson?

**Comment by ZenithCode** [comment]
Bump! @claywilkinson

**Comment by claywilkinson** [comment]
@ZenithCode  - I am wrapping up my testing for this -  and all the combinations worked for me.  The biggest pain was getting the mobileprovision file correct and the corresponding certificate uploaded to the play console.  But after that, everything worked.

I am planning on pushing a new plugin today (PDT time).

Thanks for all your contributions - it really helps!!

**Comment by ZenithCode** [comment]
Thanks @claywilkinson - that's really cool! 

Let us know as soon as you push and we'll test it on our game too!

**Comment by claywilkinson** [comment]
@ZenithCode  - ok it is out there!  I look forward to your feedback :)

**Comment by ZenithCode** [comment]
@claywilkinson for President!

It looks this problem has been resolved too! Keep up the good work man! +1
