### ISSUE TITLE
No samples for manual conflict resolving

### ISSUE THREAD

**Issue by qbit86** [playgameservices/play-games-plugin-for-unity#456]
There are no samples of the manual resolution of the conflict.

I've seen video (2 parts) about Saved Games. Manual resolution seems clear, although cumbersome. Conflicts do not happen on save, they are deferred to next open. While resolving, we don't create merged snapshot in one step; rather we chose one of existing snapshots as winner; and later save actual merge result as separate commit.

However, I can't get it working, e.g. merge two contradictory changes (sets of integers in JSON string) into their union. For example, I save “[42, 1729]” on first Android device and at the same time independently save “[42, 19937]” on second device with same Google account. In conflict callback I choose base snapshot as winner and try to immediately rewrite it with “[42, 1729, 19937]”. But merged result is never saved, subsequent reads return base “[42, 1729]”.

Should I reopen slot for writing merged result with string "slot id" or can just use one of metadata objects provided in conflict callback? Should I close the slot after calling `resolver.ChooseMetadata()`?

Could you please provide complete sample for such scenario?

**Comment by tyrmullen** [comment]
For now, the underlying SDK expects manual conflicts to be "resolved" with one of the two returned snapshots.  You can change the metadata when resolving, but the data will end up being that of either the base snapshot or the remote snapshot, with no changes.  So it's more of a "choice" and less of a "merge."

However, if you need to resolve to [42, 1729, 19937], you can just store your intended resolution off to the side, resolve until your snapshot no longer has any conflicts (and thus fully "opens"), and then commit the intended [42, 1729, 19937] resolution on top.

Of course, it would definitely make sense in the future to allow for completely arbitrary resolutions ("merging" or anything else the developer wants to do) during that single "resolution" call, but that hasn't been implemented yet.

**Comment by claywilkinson** [comment]
There is a Java sample that shows how to resolve conflicts by merging.  Please take a look at [CollectAllTheStars.resolveSnapshoConflict](https://github.com/playgameservices/android-basic-samples/blob/master/BasicSamples/CollectAllTheStars2/src/main/java/com/google/example/games/catt2/MainActivity.java#L609).
