### ISSUE TITLE
How to get login token for Auth with other services like Playfab?

### ISSUE THREAD

**Issue by sorab2142** [playgameservices/play-games-plugin-for-unity#457]
Tried the code from Issues 10, and 222, how do I call GetToken() if it's part of NativeClient?

**Comment by ZenithCode** [comment]
@sorab2142 I'm using a plugin from the AssetStore.  Its called 'Android Native plugin'.  

It would be nice if we had this right through this plugin... but yeah!

Note: I am in no-way affiliated with these developers! :-)
