### ISSUE TITLE
namespace name `BufferEncrypter' could not be found

### ISSUE THREAD

**Issue by MuffinLabs** [playgameservices/play-games-plugin-for-unity#458]
I used Mofoman2000's SocialWrapper.cs and put that and GooglePlayGames folder into the Standard Assets folder, but then it says this:

Assets/Standard Assets/SocialWrapper.cs(118,51): error CS0246: The type or namespace name `BufferEncrypter' could not be found. Are you missing a using directive or an assembly reference?

**Comment by claywilkinson** [comment]
I don't think this is the correct location for this question.  BufferEncrypter is not part of this plugin.  Maybe reach out to Mofoman2000 directly or the repository where you got SocialWrapper.cs

**Comment by MuffinLabs** [comment]
But it is look here:

excerpt from code:

	public static void SetCloudCacheEncrypter(BufferEncrypter encrypter) {
		if(loggedIn) {
			instance.SetCloudCacheEncrypter(encrypter);
		}
	}
