### ISSUE TITLE
How to use the Event/Quest function? The plugin does not yet support it, right?

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#461]
Google released the event/quest function a couple of months ago but I cant find anything about how to implement it using this plugin?

**Comment by samtstern** [comment]
You're correct, the current version of the plugin does not support Events/Quests.

However we have built this functionality into the upcoming version of the plugin, which should be released soon.  Thanks for your patience!

Comment Close and comment
