### ISSUE TITLE
Cant find a way to get mine or my opponent Username? (Only First and Lastname and Player ID number)

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#464]
When you create a google account your Username is the xxxxxx before @gmail.com. I cant figure out how to get it using the plugin..? Im thinking it could be a good way for players to find eachother. "Im playing xxxx come play with me, my username is xxxxxx"

**Comment by claywilkinson** [comment]
The player's email address is now available provided the correct configuration (and permissions granted).
See https://github.com/playgameservices/play-games-plugin-for-unity#retrieving-players-email-or-access-token
