### ISSUE TITLE
Realtime Multiplayer with different updated(different version) games

### ISSUE THREAD

**Issue by simsis3d** [playgameservices/play-games-plugin-for-unity#466]
Guys, I need very clever solutions. I have published my game. Now I will update it with changes on Realtime Multiplayer. But a player with new update and a player with old update will not be able to play properly. What is the solution of this. Please help me. Is there a way to understand the version number of players. Maybe if version numbers are not same for two players, I will not let them play. Is it a solution?

**Comment by anhnguyenvn** [comment]
I think the version of your game doesn't matter. There is a parameter called GameVariant dealing with matching multiple realtime players. Have you read it here?
https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/RTMP.md

**Comment by simsis3d** [comment]
@anhnguyenvn you are fantastic guy! you saved my time. I was about to write my own gamevariant codes:/ Thanks buddy.
