### ISSUE TITLE
Compile-time exception when using NO_GPGS

### ISSUE THREAD

**Issue by nutteen** [playgameservices/play-games-plugin-for-unity#469]
I'd like to disable the plugin for iOS. Having added NO_GPGS in Scripting Define Symbols for iOS build, there's compile-time exception.

Following is the exception from Unity version 4.6.4p1 (Pro/ iOS) (compiler option + 64x with IL2CPP)

DirectoryNotFoundException: Could not find a part of the path "C:\MyPath\Libraries\Plugins\iOS\GPGSAppController.mm".
System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.IO/FileStream.cs:292)
System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share)
(wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)

**Comment by claywilkinson** [comment]
This is a known issue - we'll have a fix shortly.  In the meantime you can look at #435 for the workaround.  Basically, you can change the editor script where it is looking for the file, or just ignore the error and blank out/remote GPGSAppController.mm by hand.

**Comment by nutteen** [comment]
Ok Thanks very much
