### ISSUE TITLE
Is There a problem With Google Play Services?

### ISSUE THREAD

**Issue by simsis3d** [playgameservices/play-games-plugin-for-unity#470]
I published my game 3 days ago, now there are more than 3.000 active players who uses Real Time Multiplayer. Today, nobody is able to create quick game! Playing with friends with invitations is okay but quick game is not working right now! Is there a problem with Google? Is anybody experiencing this also? What should I do? How can I connect with Google?

**Comment by ZenithCode** [comment]
Hi @simsis3d, 

I am having the same problem today. I am using RealTime multiplayer as well.

@claywilkinson - Is it a problem from your backend?

Thanks.

**Comment by simsis3d** [comment]
@ZenithCode Yeah I also check other games with RTMP on market. They are also not working. Such problems will be occur frequently? @claywilkinson

**Comment by claywilkinson** [comment]
It is an unusual occurrence!  I'll pass along your comments and see if I can tell if anything is going on...

**Comment by NoN33d** [comment]
Same problem here. RTM is not creating rooms on quick game mode but it does on invitations while everything worked greak yesterday.

**Comment by claywilkinson** [comment]
Quick Update: there is a backend issue - should be resolved soon.

**Comment by ZenithCode** [comment]
@claywilkinson - Ok thanks - please let us know when it is resolved.

**Comment by claywilkinson** [comment]
@za @Non @simsis3d  - QuickMatch should be working now.

**Comment by ZenithCode** [comment]
Confirmed - Thanks @claywilkinson
