### ISSUE TITLE
GetAchievement

### ISSUE THREAD

**Issue by andrewlord1990** [playgameservices/play-games-plugin-for-unity#473]
There is an internal method GetAchievement(string achievementId), that isn't publicly accessible via the PlayGamesPlatform class.

This method is really helpful, as for incremental achievements it allows you to retrieve the currently completed steps and work out how many extra steps the player has completed.

Without this method, tons of data needs to be stored locally, to ensure that the correct increment is reported and to handle the device going offline, or the request to increment the achievement failing for some other reason.

Whereas with the above method you can just store the steps completed on device. Then, every time you want to report it do:

`stepsCompleted - GetAchievement(id).currentSteps`

For the time being, I have given myself access to the method by adding a method to PlayGamesPlatform:
```c#
public Achievement GetAchievement(string achievementId) {
    return mClient.GetAchievement(achievementId);
}
```

**Comment by claywilkinson** [comment]
Sounds like a reasonable enhancement!  If you'd like, can you create a pull request with the change and it can be added into the plugin.

**Comment by andrewlord1990** [comment]
Sure, will fork the code and do that later.
