### ISSUE TITLE
How to change the size of “Social.localUser.image”?

### ISSUE THREAD

**Issue by yacmh** [playgameservices/play-games-plugin-for-unity#474]
I got the Texture2D format by calling the “Social.localUser.image” method for implementing user’s profile photo in our game.  But the problem is that I can’t change the pixel size of the image because I need to display the pictures with 640 pixels size. 

When I called the GetUserImageUrl() method and checked out the log, it was as below: 
http://lh4.googleusercontent.com/-OBSjKt_I2Sg/AAAAAAAAAAI/AAAAAAAAADM/oalYxGf203w/s96-ns/ 
I assume that s96-ns means 96 pixels.

I’m wondering if and how I can adjust the pixel size or get larger images from the Social.localUser.image method.

Best regards.

**Comment by claywilkinson** [comment]
As far as I know this is the only image available.  It is the profile picture of the user in Google+, which is typically small.

**Comment by claywilkinson** [comment]
Please reopen this issue if you have more questions.
