### ISSUE TITLE
When I login out,I can't login in again?

### ISSUE THREAD

**Issue by zuanzike** [playgameservices/play-games-plugin-for-unity#479]
My build is ok ,it work fine in my phone;
but when I login out,and sign in again, it always stop at the loading screen for long time.
test many times,it is always like this.

**Comment by claywilkinson** [comment]
Not a lot to go on - can you provide a log of what is going on when you try to sign on again?

**Comment by zuanzike** [comment]
sorry,my mistake,I update the google play game,everything is fine.

**Comment by claywilkinson** [comment]
great to hear everything is working!
