### ISSUE TITLE
I want get the rank result of one socre after reportscore, How can I get the it ?

### ISSUE THREAD

**Issue by achillea13** [playgameservices/play-games-plugin-for-unity#480]
It looks like I can't get the that thing in Unity ?

**Comment by claywilkinson** [comment]
Correct, currently is it not implemented, but it will be soon.   You'll be able to get it using the Social.ILeaderboard interface. Stay Tuned!

**Comment by claywilkinson** [comment]
This has been implemented in the version 0.9.25 of the plugin.  So the general approach is to submit the score, then load the leaderboard data, which will include the player's rank.
