### ISSUE TITLE
Gamevariant problem On Real Time Multiplayer

### ISSUE THREAD

**Issue by simsis3d** [playgameservices/play-games-plugin-for-unity#481]
Hi, after first version of my game, I changed multiplayer protocol of rtmp, then published second update with different game variant(first version game variant was 0, next update gamevariant is 1). But then, some issues happen in quick match. Two testers click quick game at the same time, but mostly they cannot play. Most of our players start to send us "We are waiting a lot, but nobody comes".

Possible cause 1: I comment out using(invitation) part in NativeRealTimeMultiplayerClient.cs as decribed by @mrggl to solve another problem. The link is just below.
https://github.com/playgameservices/play-games-plugin-for-unity/issues/351

Possible cause 2: There was a backend issue on google side 5 days ago related quick match. Maybe this problem occured after that issue fix.

I am using 0.9.12 and unity5.

Help me. this is urgent problem.
@claywilkinson @mrggl @ZenithCode

**Comment by simsis3d** [comment]
I downloaded second version(gamevariant is 1) of the game from market and here is the logs.

You can also download it from google play and test quick match.
http://play.google.com/store/apps/details?id=com.SimgeSimulation.Woodball

First Attempt:

V/GamesNativeSDK(18501): Play Games callback indicates connection.
I/GamesNativeSDK(18501): Successfully connected to Google Play.
W/ActivityManager( 2813): mDVFSHelper.release()
V/GamesNativeSDK(18501): Detaching from JVM on thread main_dispatch
W/Unity   (18501): *** [Play Games Plugin DLL] 04/27/15 13:28:46 +03:00 ERROR: P
articipant p_CKC4i4655uPeogEQAQ changed to status LEFT, room will never befully
connected.
W/Unity   (18501):
W/Unity   (18501): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
W/Unity   (18501):
V/GamesNativeSDK(18501): Detaching from JVM on thread main_dispatch
I/PackageManager( 2813): findPreferredActivity: No PreferredActivities set
I/PackageManager( 2813): findPreferredActivity: We found 2 PreferredActivities s
et, but no match
I/PackageManager( 2813): findPreferredActivity: No PreferredActivities set
I/PackageManager( 2813): findPreferredActivity: We found 2 PreferredActivities s
et, but no match
V/GamesNativeSDK(18501): Received Activity Stop Event.
V/GamesNativeSDK(18501): Attached to JVM on thread main_dispatch
V/GamesNativeSDK(18501): Running disconnect operation.
V/GamesNativeSDK(18501): Detaching from JVM on thread main_dispatch

Second Attempt:

V/GamesNativeSDK(18501): Received Activity Start Event.
V/GamesNativeSDK(18501): Attached to JVM on thread main_dispatch
V/GamesNativeSDK(18501): Received Activity Resume Event.
V/GamesNativeSDK(18501): Play Games callback indicates connection.
I/GamesNativeSDK(18501): Successfully connected to Google Play.
V/GamesNativeSDK(18501): Detaching from JVM on thread main_dispatch
I/PackageManager( 2813): findPreferredActivity: No PreferredActivities set
I/PackageManager( 2813): findPreferredActivity: We found 2 PreferredActivities s
et, but no match
V/GamesNativeSDK(18501): Detaching from JVM on thread main_dispatch
E/GamesNativeSDK(18501): Sending reliable message
E/GamesNativeSDK(18501): Sending reliable message SUCCEEDED
V/GamesNativeSDK(18501): Detaching from JVM on thread main_dispatch
W/Unity   (18501): !!! [Play Games Plugin DLL] 04/27/15 13:35:12 +03:00 WARNING:
 Player was disconnected from the multiplayer session.
W/Unity   (18501):
W/Unity   (18501): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
W/Unity   (18501):
I/PackageManager( 2813): findPreferredActivity: No PreferredActivities set
I/PackageManager( 2813): findPreferredActivity: We found 2 PreferredActivities s
et, but no match
I/PackageManager( 2813): findPreferredActivity: No PreferredActivities set
I/PackageManager( 2813): findPreferredActivity: We found 2 PreferredActivities s
et, but no match
V/GamesNativeSDK(18501): Received Activity Stop Event.
V/GamesNativeSDK(18501): Attached to JVM on thread main_dispatch
V/GamesNativeSDK(18501): Running disconnect operation.
V/GamesNativeSDK(18501): Detaching from JVM on thread main_dispatch

**Comment by simsis3d** [comment]
Is GameVariant 0(default) able to connect all other GameVariants? BTW I read somewhere that GameVariant should be between 1 and 1023.

**Comment by claywilkinson** [comment]
@simsis3d - 0.9.15 should have the fix that mggl was referring to - so you should not need to manually apply it.

As far as game variant, it should be non-zero (the default matching constant is -1 (0xffffffff) .  If the two players have different variant values, they will not be matched. 

If you having problems, can you capture the log from when PlayGamesPlatform.Instance.RealTime.CreateQuickGame is called?

**Comment by simsis3d** [comment]
@claywilkinson First of all, I upgraded to 0.9.15 and this issue https://github.com/playgameservices/play-games-plugin-for-unity/issues/351 is still there I think. @ZenithCode can you confirm that? But, anyway, this is not very critical one for me. I just want to inform you.

Secondly, you say that GameVariant must be a positive integer. But, in Quiz Racer project and also in https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/RTMP.md link, GameVariant is taken 0 for default value. My first version was also 0. Is it critically problemmatic?

Lastly, for my main problem, you can see logs below. What I understand is that infact two players connect to room and send first meesages to eachother (Sending reliable message SUCCEEDED)(First reliable message is version check, an integer), but somehow message is sticking around my version check protocol. That is why although players are connected, they see "waiting opponent" message.

LOGS:
V/GamesNativeSDK(24026): Detaching from JVM on thread main_dispatch
V/GamesNativeSDK(24026): Detaching from JVM on thread main_dispatch
E/GamesNativeSDK(24026): Sending reliable message
E/GamesNativeSDK(24026): Sending reliable message SUCCEEDED
I/PackageManager( 2813): findPreferredActivity: No PreferredActivities set
I/PackageManager( 2813): findPreferredActivity: We found 2 PreferredActivities s
et, but no match
V/GamesNativeSDK(24026): Detaching from JVM on thread main_dispatch
I/ActivityManager( 2813): Killing 22710:com.sec.factory/1000 (adj 15): empty for
 600s
I/ActivityManager( 2813): Killing 22831:com.sec.android.app.myfiles/u0a158 (adj
15): empty for 600s
I/ActivityManager( 2813): Killing 22853:com.sec.android.app.music:service/u0a101
 (adj 15): empty for 600s
I/ActivityManager( 2813): Killing 23926:com.linkedin.android/u0a278 (adj 15): em
pty for 600s
I/ActivityManager( 2813): Killing 22684:com.sec.android.gallery3d/u0a154 (adj 15
): empty for 600s
I/ActivityManager( 2813): Killing 24002:com.sec.android.provider.badge/u0a16 (ad
j 15): empty for 607s
I/PackageManager( 2813): findPreferredActivity: No PreferredActivities set
I/PackageManager( 2813): findPreferredActivity: We found 2 PreferredActivities s
et, but no match
W/Unity   (24026): !!! [Play Games Plugin DLL] 04/28/15 13:57:02 +03:00 WARNING:
 Player was disconnected from the multiplayer session.
W/Unity   (24026):
W/Unity   (24026): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
W/Unity   (24026):
I/PackageManager( 2813): findPreferredActivity: No PreferredActivities set
I/PackageManager( 2813): findPreferredActivity: We found 2 PreferredActivities s
et, but no match
I/PackageManager( 2813): findPreferredActivity: No PreferredActivities set
I/PackageManager( 2813): findPreferredActivity: We found 2 PreferredActivities s
et, but no match
V/GamesNativeSDK(24026): Received Activity Stop Event.
V/GamesNativeSDK(24026): Attached to JVM on thread main_dispatch
V/GamesNativeSDK(24026): Running disconnect operation.
V/GamesNativeSDK(24026): Detaching from JVM on thread main_dispatch
I/ActivityManager( 2813): Killing 23875:com.sec.android.widgetapp.alarmwidget/u0
a5 (adj 15): empty for 789s
I/ActivityManager( 2813): Killing 23857:com.android.mms/u0a157 (adj 15): empty f
or 789s
I/ActivityManager( 2813): Killing 23888:com.sec.android.widgetapp.digitalclock/u
0a41 (adj 15): empty for 789s

**Comment by simsis3d** [comment]
I will close this one and open a new thread abut participant disconnection. The problem explained above is totally related with participant disconnection because of unknown reason.

**Comment by VicEsquivel** [comment]
Everything worked ok, until today... I have changed nothing and it just drops the connection every time.

This is the Log

02-12 13:17:08.435 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: New participants connected:
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-12 13:17:08.435 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: Fully connected! Transitioning to active state.
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-12 13:17:08.435 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: Entering state: ActiveState
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-12 13:17:08.445 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: Entering internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSetChangedCallback
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-12 13:17:08.475 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: Updated participant statuses: [Participant: 'Jugador 5603' (id p_COnfjbLas9TreRAB), status=Joined, player=NULL, connected=False],Participant: 'Code 91 Mx' (id p_CIP90dqjpavsWhAB), status=Joined, player=[Player: 'Code 91 Mx' (id 116188677374566560658)], connected=False
02-12 13:17:08.475 22370-22596/? W/Unity﹕ !!! [Play Games Plugin DLL] 02/12/16 13:17:08 **-06:00 WARNING: Player was disconnected from the multiplayer session.
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)**
