### ISSUE TITLE
Unity 5 support

### ISSUE THREAD

**Issue by cousinjoshy1** [playgameservices/play-games-plugin-for-unity#484]
Hi, I'm new to this plugin and it looks awesome. I was wondering, does this plugin have full support for Unity 5? And if not, how limited is it or when are you coming out with full support?
Thanks

P.S: I don't use Github very often, sorry if I put this in the wrong section.

**Comment by claywilkinson** [comment]
Hi @cousinjoshy1  - The plugin supports Unity 5.

**Comment by cousinjoshy1** [comment]
Great, thanks for the quick response! Also, are there any persisting bugs that I should be aware of while using this or is it more or less bug-less?

**Comment by claywilkinson** [comment]
Currently there are some issues with real time multiplayer matching on iOS,  (which there will be an update soon). other than that, I don't think there is anything major - the issue list of this project is where all the issues are tracked so you can review the list yourself.
