### ISSUE TITLE
Saving string data

### ISSUE THREAD

**Issue by sahaab** [playgameservices/play-games-plugin-for-unity#485]
hi, sorry im kind of new to this.

I am using the play services for an android app and have got leadership board and achievements worked out. I want to save game data, mainly just 1 single string, for example "coins : (Number of coins)". I did not quite understand the code in the main page about saving screenshots and all, just dont understand how I will read and write a single string with a screenshot.

How should i go about doing this? 

Thank you

**Comment by claywilkinson** [comment]
Hi @sahaab - I would suggest reviewing https://developers.google.com/games/services/common/concepts/savedgames, maybe even watching the videos which will give good context to how saved games work.

The screenshot is part of the saved game metadata.  This allows showing a picture when managing multiple saved game data sets.  It sounds like in your case there is no real need for the screenshot, so you can safely ignore it.

Your string of saved data needs to be written out when you call CommitUpdate.

**Comment by sahaab** [comment]
thank you, i will look into this :p

**Comment by sahaab** [comment]
@claywilkinson I read that and understood it and then tried to code it using the guides and an issue from before

	public void SaveButton (int CoinstoSave) 
	{

		slot0.Data = saveGameFileName;
		mSaving = true;
		SavedGameSelected ();
		Coins = CoinstoSave;
	}
	
	// Load Button
	
	public void LoadButton () 
	{
		mSaving = false;
		SavedGameSelected ();
	}
	
	
	public void SavedGameSelected() {
		
			string filename = saveGameFileName;
			Debug.Log("opening saved game:  " + saveGameFileName);
			if (mSaving) {
				slot0.State = "Saving to " + filename;
			}
			else {
				slot0.State = "Loading from " + filename;
			}
			//open the data.
			((PlayGamesPlatform)Social.Active).SavedGame.OpenWithAutomaticConflictResolution(filename,
			                                                                                 DataSource.ReadCacheOrNetwork,
			                                                                                 ConflictResolutionStrategy.UseLongestPlaytime,
			                                                                                 SavedGameOpened);		
	}
	
	public void SavedGameOpened(SavedGameRequestStatus status, ISavedGameMetadata game) {
		if(status == SavedGameRequestStatus.Success) {
			if( mSaving) {
				slot0.State = "Opened, now writing";
				Debug.Log("Saving to " + game);
				byte[] data = slot0.ToBytes(Coins);
				System.TimeSpan playedTime = slot0.TotalPlayingTime;
				SavedGameMetadataUpdate.Builder builder =  new 
					SavedGameMetadataUpdate.Builder()
						.WithUpdatedPlayedTime(playedTime)
						.WithUpdatedDescription("Saved Game at " + System.DateTime.Now);

				SavedGameMetadataUpdate updatedMetadata  = builder.Build();
				((PlayGamesPlatform)Social.Active).SavedGame.CommitUpdate(game,updatedMetadata,data,SavedGameWritten);
			} else {
				slot0.State = "Opened, reading...";
				((PlayGamesPlatform)Social.Active).SavedGame.ReadBinaryData(game,SavedGameLoaded);
			}
		} else {
			Debug.LogWarning("Error opening game: " + status);
		}
	}
	
	public void SavedGameLoaded(SavedGameRequestStatus status, byte[] data) {
		if (status == SavedGameRequestStatus.Success) {
			Debug.Log("SaveGameLoaded, success=" + status);
			string dataString = GameData.FromBytes(data);
			Coins = int.Parse(dataString);
			Debug.Log("SaveGameLoaded, " + dataString);
		} else {
			Debug.LogWarning("Error reading game: " + status);
		}
	}
	
	
	public void SavedGameWritten(SavedGameRequestStatus status, ISavedGameMetadata game) {
		if(status == SavedGameRequestStatus.Success) {
			Debug.Log ("Game " + game.Description + " written");
			slot0.State = "Saved!";
		} else {
			Debug.LogWarning("Error saving game: " + status);
		}
	}


	////////////////////////////////////////
	/// ////////////////////////////////
	/// /////////////////////////////////

	public class GameData  {
		
		private System.TimeSpan mPlayingTime;
		private System.DateTime mLoadedTime;
		string mData;
		string mState;
		
		static readonly string HEADER = "GDv1";

		string jsonString;
		
		public GameData(string data) {
			
			mData = data;
			mState = "Initialized, modified";
			mPlayingTime = new System.TimeSpan();
			mLoadedTime = System.DateTime.Now;
			
		}
		
		public System.TimeSpan TotalPlayingTime {
			get {
				System.TimeSpan delta = System.DateTime.Now.Subtract(mLoadedTime);
				return mPlayingTime.Add(delta);
			}
		}
		
		public override string ToString () {
			string s = HEADER + ":" + mData;
			s += ":" + TotalPlayingTime.TotalMilliseconds;
			return s;
		}
		
		public byte[] ToBytes(int Coins) {
			return System.Text.ASCIIEncoding.Default.GetBytes(toJson (Coins));
		}
		
		
		public static string FromBytes (byte[] bytes) {
			return ParseJSON(System.Text.ASCIIEncoding.Default.GetString(bytes));
		}


		public static string toJson(int coins) {
			Dictionary<string, object> dictionary = new Dictionary<string, object>();
			dictionary.Add("coins", coins);
			return Json.Serialize(dictionary);
		}

		public static string ParseJSON(string byteArray) {
			Dictionary<string, object> dict = new Dictionary<string, object>();
			dict = Json.Deserialize(byteArray) as Dictionary<string, object>;
			object obj = dict["coins"];
			int coins = (int)obj; 
			return coins.ToString();
		}
		
		public string Data {
			get {
				return mData;
			}
			
			set {
				mData = value;
				mState += ", modified";
			}
			
		}
		
		public string State {
			get {
				return mState;
			}
			
			set {
				mState = value;
			}
		}
		
	}



this is the code im using, and i cant figure out why it is not loading the data. To be honest I am not sure if it is saving data or not either. The Coins variable is working normally as it should and is working fine. But on app restart, the Coins are not loaded as should be.

**Comment by claywilkinson** [comment]
Can you post the log file? It should show the debug.log() statements so we can see what is going on.

**Comment by sahaab** [comment]
I am trying to find the exact logs for the game, but i am unable to find them :-/ (testing on android, and checking logcat via adb atm), here is the whole logcat if it is any help https://www.dropbox.com/s/f1clnhrybpuwm9a/%40log.txt?dl=0  , com.es.newgame is the package name
by using the ShowSelectSavedGameUI function, i figured out that the game is being saved

**Comment by sahaab** [comment]
W/WindowManager(  767): Failed looking up window

W/WindowManager(  767): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@1ea595ea does not exist

W/WindowManager(  767): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:10494)

W/WindowManager(  767): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:10485)

W/WindowManager(  767): 	at com.android.server.wm.WindowManagerService.relayoutWindow(WindowManagerService.java:3829)

W/WindowManager(  767): 	at com.android.server.wm.Session.relayout(Session.java:205)

W/WindowManager(  767): 	at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:241)

W/WindowManager(  767): 	at com.android.server.wm.Session.onTransact(Session.java:138)

W/WindowManager(  767): 	at android.os.Binder.execTransact(Binder.java:446)

I/ActivityManager(  767): Process com.es.newgame (pid 16795)(adj 0) has died(89,335)

here is another logcat that might be helpful, but in this one im guessing i closed the game too fast

**Comment by ZenithCode** [comment]
Looks like its a parsing error:

`SaveGameLoaded, success=Success`
`I/Unity   (23728): InvalidCastException: Cannot cast from source type to destination type.`
`I/Unity   (23728):   at GameVars+GameData.ParseJSON (System.String byteArray) [0x00000] in filename unknown>:0 `
`I/Unity   (23728):   at GameVars+GameData.FromBytes (System.Byte[] bytes) [0x00000] in <filename unknown>:0 `
`I/Unity   (23728):   at GameVars.SavedGameLoaded (SavedGameRequestStatus status, System.Byte[] data) [0x00000] in <filename unknown>:0 `
`I/Unity   (23728):   at GooglePlayGames.Native.NativeSavedGameClient+`

**Comment by sahaab** [comment]
@ZenithCode
thank you i will look into that

**Comment by sahaab** [comment]
Thank you @ZenithCode @claywilkinson I have figured it out
