### ISSUE TITLE
Application Randomly crash/reset with Google Play Services 7.3

### ISSUE THREAD

**Issue by gonzaloguzzardi** [playgameservices/play-games-plugin-for-unity#486]
The game was working just fine with Google play services 7.0, but after upgrading to Google Play Services 7.3, it started to crash or reset after/while signing in.

Does anybody has this problem too? The device i used was a Moto G.

**Comment by claywilkinson** [comment]
Is this a game you are developing?  Can you provide a log file of the crash?

**Comment by gonzaloguzzardi** [comment]
Yes, it is a game i am developing. I am using Google PLay Services 7.3 in a Moto G with Android Lollipop. After clearing cache, data and rebooting, the application works fine, but only the first time. After that it keeps crashing after logging in and reseting infinitely.
The game was working fine before updating Google play services sdk and google play services app on phone (but other games that uses it works fine).
I extract this logfile, hope it helps, thanks:

I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 
I/Unity   (25596):  [Play Games Plugin DLL] 04/29/15 14:18:54 -03:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 
I/Unity   (25596):  [Play Games Plugin DLL] 04/29/15 14:18:54 -03:00 DEBUG: Creating platform-specific Play Games client.
I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 
I/Unity   (25596):  [Play Games Plugin DLL] 04/29/15 14:18:54 -03:00 DEBUG: Creating real IPlayGamesClient
I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 
I/Unity   (25596):  [Play Games Plugin DLL] 04/29/15 14:18:54 -03:00 DEBUG: Entering state: BeforeRoomCreateStartedState
I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 
I/Unity   (25596):  [Play Games Plugin DLL] 04/29/15 14:18:54 -03:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 

I/Unity   (25596):  [Play Games Plugin DLL] 04/29/15 14:18:54 -03:00 DEBUG: Entering state: ShutdownState

I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 
I/Unity   (25596):  [Play Games Plugin DLL] 04/29/15 14:18:54 -03:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 
I/Unity   (25596):  [Play Games Plugin DLL] 04/29/15 14:18:55 -03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 
I/Unity   (25596):  [Play Games Plugin DLL] 04/29/15 14:18:55 -03:00 DEBUG: Invoking user callback on game thread
I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 
I/Unity   (25596): Authentification Failed
I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 
I/Unity   (25596):  [Play Games Plugin DLL] 04/29/15 14:18:55 -03:00 DEBUG: PlayGamesHelperObject.OnApplicationPause True
I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 
I/Unity   (25596):  [Play Games Plugin DLL] 04/29/15 14:18:55 -03:00 DEBUG: PlayGamesHelperObject.OnApplicationFocus False
I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 
I/Unity   (25596):  [Play Games Plugin DLL] 04/29/15 14:19:00 -03:00 DEBUG: PlayGamesHelperObject.OnApplicationFocus True

I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 
I/Unity   (25596):  [Play Games Plugin DLL] 04/29/15 14:19:00 -03:00 DEBUG: PlayGamesHelperObject.OnApplicationPause False
I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (25596): 
I/Unity   (25596):  [Play Games Plugin DLL] 04/29/15 14:19:00 -03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
I/Unity   (25596):  
I/Unity   (25596): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

I/Unity   (25596): 

D/Unity   (25732): GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_sync GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_

D/Unity   (25732): texture_sRGB_decode GL_EXT_texture_filter_anisotropic GL_EXT_multisampled_render_to_texture GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_disjoint_timer_query

**Comment by gonzaloguzzardi** [comment]
Well, i just removed the google play services update and it works fine again as a temporary solution.

**Comment by gonzaloguzzardi** [comment]
Solved. 
Sorry for the trouble, the error was mine. I was initializing GPS using saved games although I fotgot to enable saved games in the developer console. Because i didnt implement the save game part yet, i have never noticed they were disabled and with previous versions of google play services, the game didn't crash.
