### ISSUE TITLE
Game Variant for Invitations

### ISSUE THREAD

**Issue by simgesimulation** [playgameservices/play-games-plugin-for-unity#487]
Hi All,
Game variant is really usefull for quick match, but I cannot use it for invitations! Although game variants are different, two players can connect room and play game. What should I do? Should I check game variants after they connected room and decline match?

**Comment by Bulbul108** [comment]
Anyone have any solution???

**Comment by claywilkinson** [comment]
The only thing you can do is check the variant when receiving the invitation.  Quickmatch is a little different since both players declare what variant they are, and then using that information they are matched up.  The usual use case of variant when sending invitations is to communicate the type of game to create/play.  

The invitation has the variant so when the invitation is received, you can check the variant there and decline the invitation if the variant is unacceptable..  More reference:
https://developers.google.com/games/services/android/realtimeMultiplayer#at_player_sign-in

**Comment by Bulbul108** [comment]
I can check the variant when receiving the invitation (an invitation delivered via the invitation delegate). But how can i check the variant after using AcceptFromInbox(listener)??
@claywilkinson

**Comment by claywilkinson** [comment]
Hmm.. I see the issue.  There is not an easy way to get the invitation information before accepting it.  I will mark this as an enhancement to get the Invitation, then once you have the invitation, you can inspect the variant and accept or decline as needed.

**Comment by claywilkinson** [comment]
@Bulbul108  - I looked into this more, and there is no way to influence the UI when the user is looking at the inbox.
I think you have 2 options:
1. Call getAllInvitations() (which will be part of the next update) and filter out the invitations that do not meet the variant requirements.
2. Once the match was accepted by the player, in the callback, leave any matches that don't match.

I'll update this thread when the plugin has been updated.

**Comment by claywilkinson** [comment]
getAllInvitations has been implemented in the version 0.9.25 of the plugin, so you should be able to do this in your code.

**Comment by simsis3d** [comment]
@claywilkinson can you please reopen this topic. I think it is not solved properly. Without a gamevariant in invitations(Invitations that fall Invitations Inbox), how two friends play a specific type of RTMP game? In my situation, I have 3 game modes(5,10 and 50 Coin matches). When a player send an invitation to his friend for a specific type, the other person does not know which type is this invitation.

`Call getAllInvitations() (which will be part of the next update) and filter out the invitations that do not meet the variant requirements.`  What do you mean by filter out? Is there a way to interfere invitations UI?

**Comment by claywilkinson** [comment]
I'll take a look.

**Comment by claywilkinson** [comment]
@simsis3d Does this solve your problem?  Before showing the inbox, the invitations that do not have one of the acceptable variants are declined.  Then the inbox is shown:
```
        void FilterInvitationThenLaunchInbox(List<int> allowableVariants)
        {
            PlayGamesPlatform.Instance.RealTime.GetAllInvitations(
                (invitations) =>
                {
                    foreach (Invitation inv in invitations)
                    {
                        if (!allowableVariants.Contains(inv.Variant))
                        {
                            PlayGamesPlatform.Instance.RealTime.DeclineInvitation(inv.InvitationId);
                        }
                    }
                }
            );

            PlayGamesPlatform.Instance.RealTime.AcceptFromInbox(listener);
        }
```

**Comment by claywilkinson** [comment]
Please re-open if this did not address your issue.  Thanks!
