### ISSUE TITLE
Peers Disconnected right after OnRoomConnected

### ISSUE THREAD

**Issue by simsis3d** [playgameservices/play-games-plugin-for-unity#488]
https://github.com/playgameservices/play-games-plugin-for-unity/issues/481
As explained link given above, players were waiting a alot to start a random match. At first, I thought it was GameVariant problem. But, in fact, it is because of players disconnection as soon as they connect to room. The procedure goes like that. 1 They connect to room. 2. They share their verion number with eachother(Meanwhile, they see a "waiting for opponent" ui, but in fact they are connected) 3. If version check procedure return true, they start to play("waiting opponent" ui disapperar, match begin).
@claywilkinson 
LOGS OF SUCCESSFUL CONNECTION
I/Unity   (29345):  [Play Games Plugin DLL] 04/28/15 19:47:43 +03:00 DEBUG: Ente
ring internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSe
tChangedCallback
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345):  [Play Games Plugin DLL] 04/28/15 19:47:43 +03:00 DEBUG: New
participants connected: p_COL40JyQ7775ZhAB,p_CO7x5LWhxKSWdRAB
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345):  [Play Games Plugin DLL] 04/28/15 19:47:43 +03:00 DEBUG: Full
y connected! Transitioning to active state.
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345):  [Play Games Plugin DLL] 04/28/15 19:47:43 +03:00 DEBUG: Ente
ring state: ActiveState
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345):  [Play Games Plugin DLL] 04/28/15 19:47:43 +03:00 DEBUG: Ente
ring internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSe
tChangedCallback
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345): ON ROOM CONNECTED: SUCCESFULLY CONNECTED
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345): MY VERSION:1.1
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345):  [Play Games Plugin DLL] 04/28/15 19:47:43 +03:00 DEBUG: Upda
ted participant statuses: [Participant: '70. Oyuncu' (id p_COL40JyQ7775ZhAB), st
atus=Joined, player=NULL, connected=True],[Participant: 'hakan ozcan' (id p_CO7x
5LWhxKSWdRAB), status=Joined, player=[Player: 'hakan ozcan' (id 1111132925887586
88857)], connected=True]
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
E/GamesNativeSDK(29345): Sending reliable message
E/GamesNativeSDK(29345): Sending reliable message SUCCEEDED
I/Unity   (29345):  [Play Games Plugin DLL] 04/28/15 19:47:43 +03:00 DEBUG: Ente
ring InternalOnDataReceived: 10828
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345): ON REALTIME MESSAGER ECIEVED
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345): MESSAGE TAKEN
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345): VERSION NUMBER IS TAKEN FROM PARTICIPANT
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345): OPPONENT VERSION:1.1
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345): ENTERING PLAYING STATE
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
E/GamesNativeSDK(29345): Sending reliable message
E/GamesNativeSDK(29345): Sending reliable message SUCCEEDED
E/GamesNativeSDK(29345): Sending reliable message
E/GamesNativeSDK(29345): Sending reliable message SUCCEEDED
I/Unity   (29345): Scene OnlineMultiplayer is loaded
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345):  [Play Games Plugin DLL] 04/28/15 19:47:45 +03:00 DEBUG: Ente
ring InternalOnDataReceived: 10828
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345): ON REALTIME MESSAGER ECIEVED
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345): MESSAGE TAKEN
I/Unity   (29345):
I/Unity   (29345): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   (29345):
I/Unity   (29345): NAME PACKAGE TAKEN
I/Unity   (29345):

LOGS OF UNSUCCESSFUL CONNECTION
I/Unity   ( 7742):  [Play Games Plugin DLL] 04/29/15 11:35:36 +03:00 DEBUG: Ente
ring internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSe
tChangedCallback
I/Unity   ( 7742):
I/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   ( 7742):
I/Unity   ( 7742):  [Play Games Plugin DLL] 04/29/15 11:35:36 +03:00 DEBUG: New
participants connected: p_CLiuwub8sqetchAB,p_COLEpbqQzdyUfhAB
I/Unity   ( 7742):
I/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   ( 7742):
I/Unity   ( 7742):  [Play Games Plugin DLL] 04/29/15 11:35:36 +03:00 DEBUG: Full
y connected! Transitioning to active state.
I/Unity   ( 7742):
I/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   ( 7742):
I/Unity   ( 7742):  [Play Games Plugin DLL] 04/29/15 11:35:36 +03:00 DEBUG: Ente
ring state: ActiveState
I/Unity   ( 7742):
I/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   ( 7742):
I/Unity   ( 7742):  [Play Games Plugin DLL] 04/29/15 11:35:36 +03:00 DEBUG: Ente
ring internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSe
tChangedCallback
I/Unity   ( 7742):
I/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   ( 7742):
I/Unity   ( 7742): ON ROOM CONNECTED: SUCCESFULLY CONNECTED
I/Unity   ( 7742):
I/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   ( 7742):
I/Unity   ( 7742): MY VERSION:1.1
I/Unity   ( 7742):
I/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   ( 7742):
I/Unity   ( 7742):  [Play Games Plugin DLL] 04/29/15 11:35:36 +03:00 DEBUG: Upda
ted participant statuses: [Participant: 'hakan ozcan' (id p_CLiuwub8sqetchAB), s
tatus=Joined, player=[Player: 'hakan ozcan' (id 111113292588758688857)], connect
ed=True],[Participant: '799. Oyuncu' (id p_COLEpbqQzdyUfhAB), status=Joined, pla
yer=NULL, connected=True]
I/Unity   ( 7742):
I/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   ( 7742):
E/GamesNativeSDK( 7742): Sending reliable message
E/GamesNativeSDK( 7742): Sending reliable message SUCCEEDED
V/GamesNativeSDK( 7742): Detaching from JVM on thread main_dispatch
I/PackageManager( 2813): findPreferredActivity: No PreferredActivities set
I/PackageManager( 2813): findPreferredActivity: We found 2 PreferredActivities s
et, but no match
I/Unity   ( 7742):  [Play Games Plugin DLL] 04/29/15 11:36:12 +03:00 DEBUG: Ente
ring internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSe
tChangedCallback
I/Unity   ( 7742):
I/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   ( 7742):
I/Unity   ( 7742):  [Play Games Plugin DLL] 04/29/15 11:36:12 +03:00 DEBUG: Upda
ted participant statuses: [Participant: 'hakan ozcan' (id p_CLiuwub8sqetchAB), s
tatus=Joined, player=[Player: 'hakan ozcan' (id 111113292588758688857)], connect
ed=False],[Participant: '799. Oyuncu' (id p_COLEpbqQzdyUfhAB), status=Left, play
er=NULL, connected=False]
I/Unity   ( 7742):
I/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   ( 7742):
W/Unity   ( 7742): !!! [Play Games Plugin DLL] 04/29/15 11:36:12 +03:00 WARNING:
 Player was disconnected from the multiplayer session.
W/Unity   ( 7742):
W/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
W/Unity   ( 7742):
I/Unity   ( 7742):  [Play Games Plugin DLL] 04/29/15 11:36:12 +03:00 DEBUG: Ente
ring InternalOnParticipantStatusChangedCallback
I/Unity   ( 7742):
I/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   ( 7742):
I/Unity   ( 7742):  [Play Games Plugin DLL] 04/29/15 11:36:12 +03:00 DEBUG: Ente
ring internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSe
tChangedCallback
I/Unity   ( 7742):
I/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   ( 7742):
I/Unity   ( 7742):  [Play Games Plugin DLL] 04/29/15 11:36:12 +03:00 DEBUG: Upda
ted participant statuses: [Participant: 'hakan ozcan' (id p_CLiuwub8sqetchAB), s
tatus=Joined, player=[Player: 'hakan ozcan' (id 111113292588758688857)], connect
ed=False],[Participant: '799. Oyuncu' (id p_COLEpbqQzdyUfhAB), status=Left, play
er=NULL, connected=False]
I/Unity   ( 7742):
I/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   ( 7742):
I/Unity   ( 7742): ON PEERS DISCONNECTED
I/Unity   ( 7742):
I/Unity   ( 7742): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)
I/Unity   ( 7742):
I/ActivityManager( 2813): Killing 7859:com.samsung.android.provider.filterprovid
er/u0a55 (adj 15): empty #31
I/PackageManager( 2813): findPreferredActivity: No PreferredActivities set
I/PackageManager( 2813): findPreferredActivity: We found 2 PreferredActivities s
et, but no match
I/PackageManager( 2813): findPreferredActivity: No PreferredActivities set
I/PackageManager( 2813): findPreferredActivity: We found 2 PreferredActivities s
et, but no match
I/PackageManager( 2813): findPreferredActivity: No PreferredActivities set
I/PackageManager( 2813): findPreferredActivity: We found 2 PreferredActivities s
et, but no match
I/Unity   ( 7742):
I/Unity   ( 7742): WOODBALL ON LEFT ROOM: (We click cancel because we wait a alot to connect room, but in fact players were disconnected.)

**Comment by simgesimulation** [comment]
I have the same problem

**Comment by claywilkinson** [comment]
This is fixed in the 0.9.21 update.

**Comment by VicEsquivel** [comment]
Everything worked ok, until today... I have changed nothing and it just drops the connection every time.


This is the Log: 

02-12 13:17:08.435 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: New participants connected:
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-12 13:17:08.435 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: Fully connected! Transitioning to active state.
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-12 13:17:08.435 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: Entering state: ActiveState
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-12 13:17:08.445 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: Entering internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSetChangedCallback
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-12 13:17:08.475 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: Updated participant statuses: [Participant: 'Jugador 5603' (id p_COnfjbLas9TreRAB), status=Joined, player=NULL, connected=False],Participant: 'Code 91 Mx' (id p_CIP90dqjpavsWhAB), status=Joined, player=[Player: 'Code 91 Mx' (id 116188677374566560658)], connected=False
02-12 13:17:08.475 22370-22596/? W/Unity﹕ !!! [Play Games Plugin DLL] 02/12/16 13:17:08 **-06:00 WARNING: Player was disconnected from the multiplayer session.
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)**

**Comment by danspeedy1** [comment]
I currently have the same issue and have not changed any of the multiplayer code... something on Google's side perhaps?

**Comment by VicEsquivel** [comment]
@danspeedy1 Yes, it seems so... I just opened a new thread for this... https://github.com/playgameservices/play-games-plugin-for-unity/issues/977
