### ISSUE TITLE
How to determine what happens if the user presses cancel on login

### ISSUE THREAD

**Issue by shay4545** [playgameservices/play-games-plugin-for-unity#491]
I have some code at the end of my splash screen scene. I want it to ask the user to login, and then login if they click yes and if they click no, load the next scene. I tested it on my phone, and is I click cancel, then it exits the gpg window and goes back to my app, which then does nothing. How would I get it so that when they click cancel it just loads the next scene? Here is my code:

PlayGamesPlatform.Activate ();
				Social.localUser.Authenticate ((bool success) => {
					if (success) {
						Main.sign = 1;
						PlayerPrefs.SetInt ("signedin", Main.sign);
						Social.ReportProgress (welcome, 100.0f, (bool good) => {
							// handle success or failure
						});
						Application.LoadLevel("Home");
					}
					if(!success){
						Application.LoadLevel("Home");
					}
				});

**Comment by shay4545** [comment]
Anybody?

**Comment by andrewlord1990** [comment]
If you get false from Authenticate, it means either login failed (network, internal problem) or that the user cancelled the login prompt with either back key or by pressing cancel.

**Comment by shay4545** [comment]
I believe that is what I tried that didn't work. @andrewlord1990 
Here is the code I had: 
PlayGamesPlatform.Activate ();
				Social.localUser.Authenticate ((bool success) => {
					if (success) {
						Main.sign = 1;
						PlayerPrefs.SetInt ("signedin", Main.sign);
						Social.ReportProgress (welcome, 100.0f, (bool good) => {
							// handle success or failure
						});
						Application.LoadLevel("Home");
					}
					if(!success){
						Application.LoadLevel("Home");
					}
				});

**Comment by andrewlord1990** [comment]
So if you press cancel it doesn't load level Home?

Seen as you load level home regardless of the result, seems like you should just load the level anyway rather than repeating inside the true and false clauses. However, that it is another matter.

I do the same thing and it works perfectly for me:

```
PlayGamesPlatform.Instance.Authenticate((bool success) => {
    if (success) {
            // Do stuff on success
    } else {
            // Do stuff on fail / cancel
    }
});
```
The only difference is that I use the `PlayGamesPlatform` directly, rather than via the `Social` interface. However, they should both me equivalent.

Are you sure there isn't anything else going wrong? Is the success case working correctly?

**Comment by shay4545** [comment]
The success case is working correctly, i will test this again later today and get back to you and see if it is working

**Comment by claywilkinson** [comment]
I'm closing this issue.  Please re-open with updated information if it is still an issue.  Thanks!
