### ISSUE TITLE
Usage in Paid Asset Store Plugin

### ISSUE THREAD

**Issue by manwithsteelnerves** [playgameservices/play-games-plugin-for-unity#493]
Hi @claywilkinson ,
     Thanks for the great plugin.
      Can I use this plugin in my paid asset store plugin? My plugin doesn't have play services alone, but this feature is a part of the plugin.

Please let me know what could be best way I can use in my paid plugin.

Thank you.

**Comment by claywilkinson** [comment]
You are welcome!  The Google Play Game Services plugin is licensed under the Apache2 license https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/LICENSE.  As long as you comply with the license, you can include it.

**Comment by manwithsteelnerves** [comment]
Thanks for the reply Clayton :)

**Comment by manwithsteelnerves** [comment]
Best Rated Business Networking App

 Hey playgameservices/play-games-plugin-for-unity,
 
I have started using Letzgain Android and Web App and found that 17900+
genuine Business Leads have been shared Free of Cost.
 
 
 LetzGain is unique Business Network of SMBs who always refer each other to
grow business together!
 
 
 Check if you can find some good business opportunities for yourself!
 
 

 How it works:
 Letzgain users share their or friend's requirements to buy products or hire
services / employees or search potential partners. Letzgain automatically
notifies the providers of relevant services or products. When members get
business Letzgain does not charge any Commissions or Fees!
 

 42100+ members like you and me are already helping each other get more
business in this simple way! 
 

 Best Regards,Ayyappa

 Join Now

Don't have the app yet? Download now for real-time notifications and more.

 
 
 
 

Sent by LetzGain. 
If you wish to stop receiving email alerts, click on Unsubscribe.

**Comment by manwithsteelnerves** [comment]
Best Rated Business Networking App

 Hey,

 I (Voxel Busters ) would like to connect with you on Letzgain.

LetzGain is unique Business Network of SMBs who always refer each other to
grow business together!

 
I am using Letzgain Android and Web App and found that 17,000+ genuine
Business Leads have been shared Free of Cost.
 Check if you can find some good business opportunities for yourself!
 
 

 How it works:
 Letzgain users share their or friend's requirements to buy products or hire
services / employees or search potential partners. Letzgain automatically
notifies the providers of relevant services or products. When members get
business Letzgain does not charge any Commissions or Fees!
 

 46000+ members like you and me are already helping each other get more
business in this simple way! 
 

 Best Regards,Ayyappa

 Join Now

Don't have the app yet? Download now for real-time notifications and more.

 
 
 
 

Sent by LetzGain. 
If you wish to stop receiving email alerts, click on Unsubscribe.
