### ISSUE TITLE
Unable to make it work on iOS

### ISSUE THREAD

**Issue by InsaneGoblin** [playgameservices/play-games-plugin-for-unity#494]
Heya!

Read the guide so many times I could re-write it by heart. I added all bundles and frameworks, added the code, etc. Don't know if the GameCenter has to be activated, but I did, just in case.

Code works perfectly on Android, but for some reason, not on iOS. Users simply can't login.

Here's the catch: I do not own an iOS device, so everything is done via testflight with someone without access to a Mac to read the error logs. As for simulator, my game's code and plugins render the simulator completely useless and broken. I'm flying in the dark, unfortunately.

How can I know what is failing?

Thanks!

**Comment by claywilkinson** [comment]
Your name clearly describes your situation (insane!) :)  I would strongly suggest getting an iOS device.
If your game works fine on Android and players can log in successfully, then I would double check the following:
1. Link an iOS application to your game in the Google play console.
2. Configure the iOS Setup (Window>Google Play Games>Setup>iOS Setup... and add the client id and the package name.
3.What is happening?  Does the sign on screen appear?  Sometimes there are errors displayed on the device.

**Comment by InsaneGoblin** [comment]
Hey Clay, thanks for your reply.

Unfortunately I do not have $400+ to fork out on an iOS device. I already spent 800 on a Mac just to be able to build. Absolutely hate developing on iOS, but sacrifices have to be made in order to raise awareness to my creations.

Anywho, I did follow those 2 steps, but wanted to be sure I need to enter the bundle ID (com.XXX.YYY) and not the other one with the teamID (ZZZ123.com.XXX.YYY). 

So the 2 settings should be these two: http://prntscr.com/70gkjl

Right?

And literally nothing happens on the device, it's like the button is disabled

**Comment by claywilkinson** [comment]
hmm - those are the 2 fields i was referring to, but even if those are wrong, the signin process would be attempted.  Good luck!

**Comment by InsaneGoblin** [comment]
Unfortunately, nothing happens even with those fields correctly setup. What else can I look at? 

Checklist:

a. iOS does not need any additional code? Init, Regional, etc?
b. GameCenter should be on or off in XCode and Apple Developer?
c. I saw you just branched it. Do I think it will change anything if I update the plugin?
d. Maybe a bundle or framework is corrupt. How can I know this, considering it builds and archives correctly?

Any help is appreciated, I'm desperate :(

**Comment by claywilkinson** [comment]
a - nope, just add the frameworks that are needed by the plugin and the -ObjC flag to the linker (without these the app will not build successfully)
b  - GameCenter should be off - it is not used by Google
c. I don't think the new version will do anything dramatically different based on what issue you are having.
d. i guess anything is possible, but in my experience those types of issues result in build failures.

Really you need to get some log information.  You can check out https://developer.apple.com/library/ios/qa/qa1747/_index.html for some strategies to get the log info.

Maybe ebay too to pick up a used iphone for cheap.....

**Comment by InsaneGoblin** [comment]
Decided to post the code here, maybe you guys can see what I can't:

using UnityEngine;
using System.Collections;
using UnityEngine.SocialPlatforms;
using UnityEngine.UI;

public class GooglePlayScript : MonoBehaviour 
{
	public GameObject achievements;
	public GameObject leaderboards;
	public GameObject signin;

	public bool shouldShow = true;

    void Start () 
	{
        GooglePlayGames.PlayGamesPlatform.Activate();

		if (PlayerPrefs.GetInt("Logged") == 1)
		{
			Social.localUser.Authenticate((bool success) => {
				if (success) 
				{
					leaderboards.SetActive(true);
					achievements.SetActive(true);
					signin.SetActive(false);
					shouldShow = true;
				} else {
					print ("failed login at init");
				}
			});
		}
	}
	
	void Update ()
	{
		if (shouldShow)
		{
			if (Social.localUser.authenticated)
			{
				leaderboards.SetActive(true);
				achievements.SetActive(true);
				signin.SetActive(false);
			}
			else
			{
				leaderboards.SetActive(false);
				achievements.SetActive(false);
				signin.SetActive(true);
			}
		}
		else
		{
			leaderboards.SetActive(false);
			achievements.SetActive(false);
			signin.SetActive(false);
		}
	}

	public void changeShow()
	{
		shouldShow = !shouldShow;
	}

	public void SignIn()
	{
		if (!Social.localUser.authenticated) {
			Social.localUser.Authenticate((bool success) => {
				if (success) {
					PlayerPrefs.SetInt("Logged", 1);
					leaderboards.SetActive(true);
					achievements.SetActive(true);
					signin.SetActive(false);
					shouldShow = true;				
				} else {
					print ("failed login");
				}
			});
		}
		else 
		{
			((GooglePlayGames.PlayGamesPlatform) Social.Active).SignOut();
			PlayerPrefs.SetInt("Logged", 0);
		}

	}
	
	public void ShowLeaderboard()
	{
		Social.ShowLeaderboardUI();
	}
	
	public void ShowAchievements()
	{
		Social.ShowAchievementsUI();
	}
}

**Comment by sorab2142** [comment]
Where are you stuck exactly? Does the app launch fine and you dont see the Play Login starting? or does it just appear and disappear? If it's the latter, you need to add the email ID that was used for the login to the Testers List through the Play Publisher Console.

**Comment by InsaneGoblin** [comment]
Tap the button and nothing happens. Simple as that. No error, no nothing :(

"you need to add the email ID that was used for the login"
What email exactly?
