### ISSUE TITLE
"Social-All" switch is not available in "Leaderboards" when Android language is configured to right-to-left language

### ISSUE THREAD

**Issue by Naamani** [playgameservices/play-games-plugin-for-unity#495]
"Social-All" switch is not available in "Leaderboards" when Android language is configured to right-to-left language, such as Hebrew and Arabic.
This cause the players who their Android phones are configured to right-to-left languages not to be able to see their place, but only with their friends in google plus circles.

![screenshot_2015-05-03-16-26-34](https://cloud.githubusercontent.com/assets/12220732/7445226/6e53739a-f1b2-11e4-9957-a29a5eda125b.png)

**Comment by claywilkinson** [comment]
Thanks for the screenshot - I'll pass it along

**Comment by Naamani** [comment]
Thanks for the quick reply.
Found the issue also in Stackoverflow:
http://stackoverflow.com/questions/29705740/public-and-social-option-are-not-showing-at-leaderboard-google-games-services

**Comment by claywilkinson** [comment]
This should be fixed now if you update to the latest Play Games application

**Comment by Naamani** [comment]
Great news!
Will try it.
Thanks.

**Comment by claywilkinson** [comment]
@Naamani  - are you still experiencing this issue, or can I close it?

**Comment by Naamani** [comment]
@claywilkinson - sorry for the late response. Yes, it works perfectly, you may close it.

**Comment by claywilkinson** [comment]
Great! Thanks for the response.
