### ISSUE TITLE
Having trouble upgrading 0.9.15 to 0.9.20

### ISSUE THREAD

**Issue by sahaab** [playgameservices/play-games-plugin-for-unity#496]
These are the errors i get in unity when importing, I delete GooglePlayGames folder in assets and then import package

Error importing folder (The pathName assets/googleplaygames/basicapi/savedgame is already mapped to 7bbb98ba2466e4d918a47f41423db103. But the meta data wants it to be mapped to d9dd26ddbf3944bc88476016fa7c977b)
Error importing folder (The pathName assets/googleplaygames/editor is already mapped to fe06fbf1d62bf4406935dbfbe3e71a59. But the meta data wants it to be mapped to 5e8e3372de7db45f3ac264decea7e61b)
Error importing folder (The pathName assets/googleplaygames/platforms/native is already mapped to 738228648ad6c487284744a8e022caa3. But the meta data wants it to be mapped to 6ab6ce8aabb6a4b98bedd069f84b7ebd)
Error importing folder (The pathName assets/googleplaygames/platforms/native/cwrapper is already mapped to 0bda2131d53df474e8f3a6bd08030db8. But the meta data wants it to be mapped to 18ea1ab27db54489a93a1a8f25784ee9)
Error importing folder (The pathName assets/googleplaygames/platforms/native/pinvoke is already mapped to 424ba42d65cb34acf90cec8c51e096e8. But the meta data wants it to be mapped to d3e98392d813e489d8dead89f176cb8a)

when i try to import again without deleting anything, i get nothing i can update, and when i delete GooglePlayGames and Plugins and try updating again, same thing happens except with more errors.  I can see Google Play Games in the menu, but when i click it, nothing comes out. When i went to Window > Google Play Games > Setup > Android Setup , it did the setup, but when i run it on my phone, it does not attempt to connect to my google play account. When i remove GooglePlayGames and Plugins and copy back the files of 0.9.15, it starts working normally again.

Thank you

**Comment by claywilkinson** [comment]
The easiest thing to do in this case is to
1. delete the GooglePlayGames folder in the Assets directory
2. import the new GooglePlayGame unity package.
3. if there are warnings/errors. then Click Assests/Reimport All - which reprocesses the meta data.

**Comment by sahaab** [comment]
oh ok,  thank you, i did not try the reimport all option and nobody suggested it online for some reason, will try
thank you

**Comment by sahaab** [comment]
@claywilkinson sorry but that doesnt seem to be working :-/ 
got it imported, compiled and pushed into my device, but it does not ask for google play games services or attempts to connect to google play games services

**Comment by sahaab** [comment]
all the unity logcats i got from it :p

05-04 16:32:32.558: I/Unity(25787):  [Play Games Plugin DLL] 05/04/15 16:32:32 -04:00 DEBUG: Activating PlayGamesPlatform.
05-04 16:32:32.558: I/Unity(25787):  
05-04 16:32:32.558: I/Unity(25787): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
05-04 16:32:32.568: I/Unity(25787):  [Play Games Plugin DLL] 05/04/15 16:32:32 -04:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
05-04 16:32:32.568: I/Unity(25787):  
05-04 16:32:32.568: I/Unity(25787): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
05-04 16:32:32.568: I/Unity(25787):  [Play Games Plugin DLL] 05/04/15 16:32:32 -04:00 DEBUG: SetDefaultLeaderboardForUI: CgkI7pib3qUMEAIQAQ
05-04 16:32:32.568: I/Unity(25787):  
05-04 16:32:32.568: I/Unity(25787): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
05-04 16:32:32.568: I/Unity(25787):  [Play Games Plugin DLL] 05/04/15 16:32:32 -04:00 DEBUG: Creating platform-specific Play Games client.
05-04 16:32:32.568: I/Unity(25787):  
05-04 16:32:32.568: I/Unity(25787): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
05-04 16:32:32.568: I/Unity(25787):  [Play Games Plugin DLL] 05/04/15 16:32:32 -04:00 DEBUG: Creating real IPlayGamesClient
05-04 16:32:32.568: I/Unity(25787):  
05-04 16:32:32.568: I/Unity(25787): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
05-04 16:32:32.618: D/GamesUnitySDK(25787): Performing Android initialization of the GPG SDK
05-04 16:32:32.918: I/Unity(25787): InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK
05-04 16:32:32.918: I/Unity(25787):   at GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build (GooglePlayGames.Native.PInvoke.PlatformConfiguration configRef) [0x00000] in <filename unknown>:0 
05-04 16:32:32.918: I/Unity(25787):   at GooglePlayGames.Native.NativeClient.InitializeGameServices () [0x00000] in <filename unknown>:0 
05-04 16:32:32.918: I/Unity(25787):   at GooglePlayGames.Native.NativeClient.Authenticate (System.Action`1 callback, Boolean silent) [0x00000] in <filename unknown>:0 
05-04 16:32:32.918: I/Unity(25787):   at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`1 callback, Boolean silent) [0x00000] in <filename unknown>:0 
05-04 16:32:32.918: I/Unity(25787):   at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`1 callback) [0x00000] in <filename unknown>:0 
05-04 16:32:32.918: I/Unity(25787):   at GooglePlayGames.PlayGamesLocalUser.Authenticate (System.Action`1 callback) [0x00000] in <filename unknown>:0 
05-04 16:32:32.918: I/Unity(25787):   at GameVars.Start () [0x00000] in <filename unknown>:0 
05-04 16:32:32.918: I/Unity(25787):  
05-04 16:32:32.918: I/Unity(25787): (Filename:  Line: -1)
05-04 16:32:36.232: W/Unity(25787): !!! [Play Games Plugin DLL] 05/04/15 16:32:36 -04:00 WARNING: PlayGamesPlatform already initialized. Ignoring this call.
05-04 16:32:36.232: W/Unity(25787):  
05-04 16:32:36.232: W/Unity(25787): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
05-04 16:32:36.232: I/Unity(25787):  [Play Games Plugin DLL] 05/04/15 16:32:36 -04:00 DEBUG: Activating PlayGamesPlatform.
05-04 16:32:36.232: I/Unity(25787):  
05-04 16:32:36.232: I/Unity(25787): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
05-04 16:32:36.232: I/Unity(25787):  [Play Games Plugin DLL] 05/04/15 16:32:36 -04:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
05-04 16:32:36.232: I/Unity(25787):  
05-04 16:32:36.232: I/Unity(25787): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
05-04 16:32:36.232: I/Unity(25787):  [Play Games Plugin DLL] 05/04/15 16:32:36 -04:00 DEBUG: SetDefaultLeaderboardForUI: CgkI7pib3qUMEAIQAQ
05-04 16:32:36.232: I/Unity(25787):  
05-04 16:32:36.232: I/Unity(25787): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
05-04 16:32:36.232: I/Unity(25787): InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK
05-04 16:32:36.232: I/Unity(25787):   at GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build (GooglePlayGames.Native.PInvoke.PlatformConfiguration configRef) [0x00000] in <filename unknown>:0 
05-04 16:32:36.232: I/Unity(25787):   at GooglePlayGames.Native.NativeClient.InitializeGameServices () [0x00000] in <filename unknown>:0 
05-04 16:32:36.232: I/Unity(25787):   at GooglePlayGames.Native.NativeClient.Authenticate (System.Action`1 callback, Boolean silent) [0x00000] in <filename unknown>:0 
05-04 16:32:36.232: I/Unity(25787):   at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`1 callback, Boolean silent) [0x00000] in <filename unknown>:0 
05-04 16:32:36.232: I/Unity(25787):   at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`1 callback) [0x00000] in <filename unknown>:0 
05-04 16:32:36.232: I/Unity(25787):   at GooglePlayGames.PlayGamesLocalUser.Authenticate (System.Action`1 callback) [0x00000] in <filename unknown>:0 
05-04 16:32:36.232: I/Unity(25787):   at GameVars.Start () [0x00000] in <filename unknown>:0 
05-04 16:32:36.232: I/Unity(25787):  
05-04 16:32:36.232: I/Unity(25787): (Filename:  Line: -1)

**Comment by sahaab** [comment]
@claywilkinson  
sorry found this as well while scrolling through

05-04 16:36:42.202: E/GamesNativeSDK(27179): Can't register class com/google/android/gms/nearby/Nearby: an exception occurred.
05-04 16:36:42.212: E/GamesNativeSDK(27179): Can't register class com/google/android/gms/nearby/connection/AppIdentifier: an exception occurred.
05-04 16:36:42.212: E/GamesNativeSDK(27179): Can't register class com/google/android/gms/nearby/connection/AppMetadata: an exception occurred.
05-04 16:36:42.212: E/GamesNativeSDK(27179): Can't register class com/google/android/gms/nearby/connection/Connections: an exception occurred.
05-04 16:36:42.212: E/GamesNativeSDK(27179): Can't register class com/google/android/gms/nearby/connection/Connections$StartAdvertisingResult: an exception occurred.
05-04 16:36:42.322: E/GamesNativeSDK(27179): Could not register one or more required Java classes.

**Comment by claywilkinson** [comment]
The can't register classes messages usually indicate that set up needs to be run again  (Window>Google Play Games>Setup>Android Setup...

**Comment by sahaab** [comment]
@claywilkinson I had done it before, but just to make sure, i did it again, 2 times, deleting google play folder, imported new, reimported all, android setup, and then build and run, got same logcat as above
then 2nd time i deleted google play and plugin folders, imported new , reimported all, android setup, and then build and run, and again got same logcat as above :p

**Comment by claywilkinson** [comment]
Check the version of android SDKs you have.  To make sure you have the latest of play services (needs to be at least 22  or 23).  Nearby connections is a new game communication API just introduced.

**Comment by sahaab** [comment]
okay thank you, that last one was the problem

**Comment by claywilkinson** [comment]
great! glad you got it working!
