### ISSUE TITLE
C# Coder for iOS GPG integration

### ISSUE THREAD

**Issue by InsaneGoblin** [playgameservices/play-games-plugin-for-unity#497]
Been hitting my head against the wall for weeks. Tested everything I know, so now I gave up.

Hiring anyone that is willing to check why the GooglePlayServices won't work on iOS, and fix it. Very easy and quick job for anyone that has integrated it before.

Please contact me on skype (moontear84) or email (amochi84@gmail.com).

Thanks!

**Comment by claywilkinson** [comment]
Closing this issue - Hopefully you got some resolution.  This is type request is more appropriate for somewhere else.
