### ISSUE TITLE
Bitmask filter in CreateQuickGame

### ISSUE THREAD

**Issue by 4non** [playgameservices/play-games-plugin-for-unity#498]
Hey @claywilkinson ,
Thanks for a great plugin, it works like a charm :)

I am just wondering if there is any way to include a "bitmask" in the "PlayGamesPlatform.Instance.RealTime.CreateQuickGame" call?

Like in the example described in: https://developers.google.com/games/services/android/realtimeMultiplayer
"
If your game has multiple player roles (such as farmer, archer, and wizard) and you want to restrict auto-matched games to one player of each role, add an exclusive bitmask to your room configuration. When auto-matching with this option, players will only be considered for a match when the logical AND of their exclusive bit masks is equal to 0.
"

or is there a special way to use the "gamevariation" uint-input for this?

Thanks!

**Comment by claywilkinson** [comment]
@4non - Thanks for the kind words!   The API is there to do the exclusive bit mask, I don't think it has actually "bubbled" up to the public interface.  I'll add it to the list, it should be pretty quick to do.  Also, if you are feeling adventurous, feel free to fork the code and submit a pull request with the change :)

**Comment by 4non** [comment]
Thanks for the fast reply @claywilkinson ! :)

I felt adventurous yesterday, so I gave it a go (in my own fork) - havent tested it yet, though!
Also, I am a bit worried that other users who have the CreateQuickGame() call in their code will get errors when there is a new ulong-input required that they didnt know of, if this gets pulled in?

**Comment by claywilkinson** [comment]
In C#, you can overload a function so it will be OK.  Just keep the existing function as-is, and then add yours (with the same name) but with different parameters.  This way old code will still work, and new code can take advantage of the new parameters.

**Comment by claywilkinson** [comment]
Added in 0.9.21 update
