### ISSUE TITLE
play games unity error 

### ISSUE THREAD

**Issue by richard1011** [playgameservices/play-games-plugin-for-unity#499]
hi i've installed the unity plugin but every time i run it in unity i get the error

"""
*** [Play Games Plugin DLL] 05/04/15 16:56:46 +01:00 ERROR: ReportProgress can only be called after authentication.
UnityEngine.Debug:LogWarning(Object)
GooglePlayGames.OurUtils.Logger:e(String) (at Assets/GooglePlayGames/OurUtils/Logger.cs:58)
GooglePlayGames.PlayGamesPlatform:ReportProgress(String, Double, Action`1) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:313)
UnityEngine.Social:ReportProgress(String, Double, Action`1)
button:Update() (at Assets/scripts/button.cs:74)
"""

here is my code can somebody help please

using UnityEngine;
using UnityEngine.UI;
using GooglePlayGames;
using System.Collections;
using UnityEngine.SocialPlatforms;

public class button : MonoBehaviour {

	void Awake () {
		PlayGamesPlatform.DebugLogEnabled = true;

		PlayGamesPlatform.Activate ();
	}

	void Start(){

			Social.localUser.Authenticate((bool success) => {
				
				Text posting;
				posting = gameObject.GetComponent<Text>();
				posting.text="You logged in successfully";
			});

		if(PlayerPrefs.HasKey ("highscore") == false){
			PlayerPrefs.SetInt ("highscore",0);

		}

		if(PlayerPrefs.HasKey("bronze") == false) {

			PlayerPrefs.SetInt("bronze", 1);
			PlayerPrefs.SetInt("silver", 0);
			PlayerPrefs.SetInt("gold", 0);
			PlayerPrefs.SetInt("diamond", 0);
			PlayerPrefs.SetInt("bronzep", 0);
			PlayerPrefs.SetInt("silverp", 0);
			PlayerPrefs.SetInt("goldp", 0);
			PlayerPrefs.SetInt("diamondp", 0);
			PlayerPrefs.SetInt("bronzepb", 0);
			PlayerPrefs.SetInt("silverpb", 0);
			PlayerPrefs.SetInt("goldpb", 0);
			PlayerPrefs.SetInt("diamondpb", 0);

	}

	}
void social() {

		Application.LoadLevel ("social");

	}

	void leaderboard() {

		Social.ShowLeaderboardUI();

	}

	void achivements() {

		Social.ShowAchievementsUI();

	}

	void posths() {
		Social.ReportScore(PlayerPrefs.GetInt("highscore"), "CgkIv9ep_JMVEAIQBg", (bool success) =>{});

	}

	void login() {

		PlayerPrefs.SetInt("login", 1);
		Social.localUser.Authenticate((bool success) => {

			Text posting;
			posting = gameObject.GetComponent<Text>();
			posting.text="You logged in successfully";
		}
		);

**Comment by sorab2142** [comment]
You can only run it on a device as it uses Google Play Services from that.

**Comment by claywilkinson** [comment]
Authenticate is asynchronous, are you sure it has completed before calling ReportScore?  You could add logging to Authenticate to see if it is completed before calling ReportScore.  Or, to be 100% sure,  check for being authenticated in posths() and if not, call authenticate and in the callback call ReportScore.

**Comment by richard1011** [comment]
Thanks
