### ISSUE TITLE
Null data (byte [0]) on Save Game read iOS

### ISSUE THREAD

**Issue by DaMitchou** [playgameservices/play-games-plugin-for-unity#500]
Hi,

I have a issue concerning cloud save on iOS (it works well on Android). The game successfully gets the metadata of the game save on the cloud, but then when i read it, it return an empty array of byte, and says it is a success.

I recently moved from 0.9.12 to 0.9.20 but the problem is still here. Actually it only worked once on iOS, returning the correct array of data (don't know why....).

I am only testing for the moment, so I don't have an iTunes ID (which is said to be optional for testing in the google developer console), it may be linked. But the leaderboards and the achievements work well so...

I hope you can help me :)

Regards

**Comment by claywilkinson** [comment]
Hi @DaMitchou -  Can you provide a logfile containing the calls being made while trying to load the saved game data?

**Comment by DaMitchou** [comment]
Well, mainly I do consecutively : Login->Open->Read

but out i found something else : " Op: SIGN_IN status: ERROR_NOT_AUTHORIZED" appears (not always) after I accept the required authorizations from Google. It also happened after a sign out. 

Moreover is it normal that google ask for the authorizations every time disconnect-> reconnect? The message also changed after I installed Google + on my iPhone (It is was telling "you have already accepted the app" or something like that before)

Log of the calls to read the saved games :

OnLoginCompleted google : True
UnityEngine.Debug:Internal_Log(Int32, String, Object)
...
GooglePlayGames.Native.<InvokeCallbackOnGameThread>c__AnonStorey4C:<>m__F() (at .../Assets/GooglePlayGames/Platforms/Native/NativeClient.cs:149)
GooglePlayGames.OurUtils.PlayGamesHelperObject:<Update>m__3(Action) (at .../Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:114)
System.Collections.Generic.List`1:ForEach(Action`1)
GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at .../Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:114)

OpenGameSave
...
GooglePlayGames.Native.<InvokeCallbackOnGameThread>c__AnonStorey4C:<>m__F() (at .../Assets/GooglePlayGames/Platforms/Native/NativeClient.cs:149)
GooglePlayGames.OurUtils.PlayGamesHelperObject:<Update>m__3(Action) (at .../Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:114)
System.Collections.Generic.List`1:ForEach(Action`1)
GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at .../Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:114)
 
OpenGameSave success OPEN => READING
...
GooglePlayGames.Native.<ToOnGameThread>c__AnonStorey78`2:<>m__4D() (at .../Assets/GooglePlayGames/Platforms/Native/NativeSavedGameClient.cs:610)
GooglePlayGames.OurUtils.PlayGamesHelperObject:<Update>m__3(Action) (at .../Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:114)
System.Collections.Generic.List`1:ForEach(Action`1)
GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at .../Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:114)
 
ReadSavedGame
...
GooglePlayGames.Native.<ToOnGameThread>c__AnonStorey78`2:<>m__4D() (at .../Assets/GooglePlayGames/Platforms/Native/NativeSavedGameClient.cs:610)
GooglePlayGames.OurUtils.PlayGamesHelperObject:<Update>m__3(Action) (at .../Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:114)
System.Collections.Generic.List`1:ForEach(Action`1)
GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at ...Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:114)
 

 [Play Games Plugin DLL] 05/05/15 0:30:26 +02:00 DEBUG: Entering internal callback for SnapshotManager#ReadCallback

OnSavedGameDataRead : True
...
GooglePlayGames.Native.<ToOnGameThread>c__AnonStorey78`2:<>m__4D() (at .../Assets/GooglePlayGames/Platforms/Native/NativeSavedGameClient.cs:610)
GooglePlayGames.OurUtils.PlayGamesHelperObject:<Update>m__3(Action) (at .../Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:114)
System.Collections.Generic.List`1:ForEach(Action`1)
GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at ...Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:114)
 

Data is null but metadata is not 05/04/2015 18:00:40
...
GooglePlayGames.Native.<ToOnGameThread>c__AnonStorey78`2:<>m__4D() (at .../Assets/GooglePlayGames/Platforms/Native/NativeSavedGameClient.cs:610)
GooglePlayGames.OurUtils.PlayGamesHelperObject:<Update>m__3(Action) (at .../Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:114)
System.Collections.Generic.List`1:ForEach(Action`1)
GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at ...Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs:114)

**Comment by DaMitchou** [comment]
Well it seems it doesn't work anymore on Android too. I ll clean the plugin from the project and reinstall it, and i will see.

**Comment by tyrmullen** [comment]
Does this issue still occur if you wait for a few seconds after logging in?

So:  Save snapshot successfully -->  Sign out --> Login again successfully -->  Wait 3 seconds --> Open snapshot --> Read snapshot


The sign-in messages you're seeing should be unrelated.  At the very least, the ERROR_NOT_AUTHORIZED after you've successfully signed out should not cause any problems.

GPGS should ask you to sign in (with UI indicator and everything) after every explicit "Sign Out", but if the app was simply closed and restarted then it should be able to "auto sign-in" with much less friction.  The Google+ app being installed should further reduce friction to signing in-- so the behavior will differ slightly from what you'd see otherwise, but having the app should only make things smoother.

**Comment by DaMitchou** [comment]
Apparently, waiting solves the issue.

Otherwise it kinda locks the game save which can't be modified anymore. Actually I was testing on a Nexus 4 and an iPhone 5c, checking if the cross save was ok. After the first game save reading returning an empty array, it became impossible to save on the Nexus 4 either (which is why I thought the Android version didn't work anymore, it couldn't open the game save and there were ERROR INTERNAL in the log ). But when i removed this save, it was able to save again on the Nexus 4.

After I put the delay in opening the snapshot, it didn't see this bug anymore. I'll continue to test and close this issue if I don't see this bug anymore :)

Anyway, thank you very much !

**Comment by tyrmullen** [comment]
Glad that (rather hacky) workaround could help temporarily-- just to fully close this issue out, though, I don't consider needing to wait after logging in to be a valid fix.

However, we've tracked down the underlying problem and believe the issue should be resolved now, so you shouldn't even need to wait anymore.
