### ISSUE TITLE
Google Play Games menu not populating

### ISSUE THREAD

**Issue by Tom-E** [playgameservices/play-games-plugin-for-unity#501]
In the latest release 0.9.2, the menu does not work in unity. Once clicked, nothing happens, and no list of menu items is shown.

The menu is not accessible through File either.

**Comment by sorab2142** [comment]
Its under Window -> GooglePlay Games for some reason

**Comment by claywilkinson** [comment]
Try clicking Assets>Refresh.  Perhaps that will make it show up.  If it still does not, check the log - there most likely is an error displayed in there which will lead to the cause.

**Comment by Tom-E** [comment]
I suppose the bug then is that the old 1st level Google Play Games menu still exists?

**Comment by claywilkinson** [comment]
There was a lot of refactoring between 0.9.15 and 0.9.20.  You need to delete the GooglePlayGames folder completely before importing the new plugin.  This will get rid of the top level menu.

Are there errors in the console when you import?

**Comment by Tom-E** [comment]
Seems good, closing.
