### ISSUE TITLE
LoadSave in Cubic Pilot 4.6 crashes on iOS

### ISSUE THREAD

**Issue by sorab2142** [playgameservices/play-games-plugin-for-unity#502]
I clicked the LoadSave button after playing a game, and it shows the color overlay (which means it was opening the Select a Snapshot screen) but then crashed after that.

Here's a log:

Login successful!
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7Generated/UnityEngineDebug.cpp Line: 56)

-> applicationWillResignActive()
-> applicationDidBecomeActive()
-> applicationWillResignActive()
-> applicationDidEnterBackground()
2015-05-05 17:45:03.045 cubicpilot[460:244571] VERBOSE: Cancelling event timer
-> applicationWillEnterForeground()
-> applicationDidBecomeActive()
Loading game progress from the cloud.
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7Generated/UnityEngineDebug.cpp Line: 56)

2015-05-05 17:45:05.606 cubicpilot[460:244571] Failed to load font: Error Domain=com.apple.CoreText.CTFontManagerErrorDomain Code=101 "The operation couldn’t be completed. (com.apple.CoreText.CTFontManagerErrorDomain error 101 - Could not register the font file(s))" UserInfo=0x18576950 {CTFontManagerErrorFontURLs=(
    "file:///private/var/mobile/Containers/Bundle/Application/95DAE013-2B97-475B-8556-63B4A575BC10/cubicpilot.app/GoogleKitCore.bundle/Roboto-Medium.ttf"
), NSDescription=Could not register the font file(s)}
May  5 17:45:05 xxx-iPhone cubicpilot[460] <Error>: CGContextSetFillColorWithColor: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
May  5 17:45:05 xxx-iPhone cubicpilot[460] <Error>: CGContextSetStrokeColorWithColor: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
May  5 17:45:05 xxx-iPhone cubicpilot[460] <Error>: CGContextGetCompositeOperation: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
May  5 17:45:05 xxx-iPhone cubicpilot[460] <Error>: CGContextSetCompositeOperation: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
May  5 17:45:05 xxx-iPhone cubicpilot[460] <Error>: CGContextFillRects: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
May  5 17:45:05 xxx-iPhone cubicpilot[460] <Error>: CGContextSetCompositeOperation: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
2015-05-05 17:45:05.800 cubicpilot[460:244571] Uncaught exception: NSInvalidArgumentException: *** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument
(
	0   CoreFoundation                      0x2542a007 <redacted> + 150
	1   libobjc.A.dylib                     0x33977c8b objc_exception_throw + 38
	2   CoreFoundation                      0x25429f35 <redacted> + 0
	3   Foundation                          0x26099a45 <redacted> + 92
	4   Foundation                          0x26099975 <redacted> + 60
	5   cubicpilot                          0x00cf17e1 +[NSDate(GPGAdditions) gpg_localizedSnapshotPlayedTime:] + 360
	6   cubicpilot                          0x00ce06a5 -[GPGSnapshotContentView updateViewWithObject:] + 996
	7   cubicpilot                          0x00c13f87 -[QTMCollectionViewCell updateCellWithObject:] + 618
	8   cubicpilot                          0x00ccb69b -[GPGQTMCollectionViewModel collectionView:cellForItemAtIndexPath:] + 266
	9   UIKit                               0x28adc371 <redacted> + 252
	10  UIKit                               0x28ada8d5 <redacted> + 3396
	11  UIKit                               0x28ad6425 <redacted> + 260
	12  UIKit                               0x28a7c023 <redacted> + 546
	13  QuartzCore                          0x2849cd99 <redacted> + 128
	14  QuartzCore                          0x284985cd <redacted> + 360
	15  QuartzCore                          0x28498455 <redacted> + 16
	16  QuartzCore                          0x28497df1 <redacted> + 224
	17  QuartzCore                          0x28497bdf <redacted> + 434
	18  UIKit                               0x28a7423b <redacted> + 126
	19  CoreFoundation                      0x253effed <redacted> + 20
	20  CoreFoundation                      0x253ed6ab <redacted> + 278
	21  CoreFoundation                      0x253edab3 <redacted> + 914
	22  CoreFoundation                      0x2533a201 CFRunLoopRunSpecific + 476
	23  CoreFoundation                      0x2533a013 CFRunLoopRunInMode + 106
	24  GraphicsServices                    0x2cc19201 GSEventRunModal + 136
	25  UIKit                               0x28adea59 UIApplicationMain + 1440
	26  cubicpilot                          0x0002365c main + 304
	27  cubicpilot                          0x00023528 start + 40
)
2015-05-05 17:45:05.804 cubicpilot[460:244571] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument'

**Comment by claywilkinson** [comment]
This looks like the gpg.bundle file is not included in your app.  when you add it to the project, make sure it is being copied to the project, and it should be in the copy bundle resources build step.
