### ISSUE TITLE
LoadScores not implemented

### ISSUE THREAD

**Issue by vanustwo** [playgameservices/play-games-plugin-for-unity#503]
My game display a custom leaderboard.
Social.LoadScores is not yet implemented. Is there a temporary solution to retrieve leaderboard scores? Or when will this feature is implemented?

**Comment by Tedwikman** [comment]
Hey hey,

I needed this functionality in my game, so I did some changes to the code base to get it to work.
It's not the most beautiful way to solve it, but it gets the job done :)

Have a look at my fork if would like to give it a go. 
https://github.com/Tedwikman/play-games-plugin-for-unity/commit/0fb10319abc2981afa345c642af4bb745e78fe8b

**Comment by claywilkinson** [comment]
Hi @Tedwikman  - if you are done with solution, do you care to share a pull request?

**Comment by Tedwikman** [comment]
Hey hey @claywilkinson sure, but I am a bit new to the whole github experience, could you walk me through how I could do a share?

**Comment by claywilkinson** [comment]
This has been implemented in the version 0.9.25 of the plugin
