### ISSUE TITLE
Apple Mach O Linker Error

### ISSUE THREAD

**Issue by sorab2142** [playgameservices/play-games-plugin-for-unity#507]
ld: 4725 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

using google plus ios sdk 1.7.1, playgames ios sdk 3.1.1 and latest gpg-cpp sdk

**Comment by claywilkinson** [comment]
You don't need the iOS SDK 3.1.1, just Google Plus and gpg.

**Comment by sorab2142** [comment]
The previous issue got resolved by removing the extra bundle and framework. But now I get GooglePlus.h not found since it isnt adding the bundle as can be seen in the warning below.

warning: skipping file '/Users/pace/Downloads/NEW SDKS/gpg-cpp-sdk 2/ios/gpg.bundle' (unexpected file type 'wrapper.plug-in' in Frameworks & Libraries build phase)
warning: skipping file '/Users/pace/Downloads/NEW SDKS/google-plus-ios-sdk-1.7.1/GooglePlus.bundle' (unexpected file type 'wrapper.plug-in' in Frameworks & Libraries build phase)
