### ISSUE TITLE
Large increase in file size

### ISSUE THREAD

**Issue by andrewlord1990** [playgameservices/play-games-plugin-for-unity#508]
Adding the Google Play Games plugin to my unity game added a huge amount to its file size.

Large files I can see:

- google-play-services.jar - 3.5MB
- armeabi-v7a/libgpg.so - 1.6MB
- x86/libgpg.so - 2.4MB

Through Gradle, you can include part of Google Play Services rather than including the full library. However, I cannot find any way of achieving this through a JAR and library project.

Would there be any way to improve this or am I missing something? Google Play Games has added over 10MB to my APK size, which is more than the rest of the contents of my project make up for...

**Comment by tyrmullen** [comment]
You can try editing the .jar file to remove some of the classes which will be unused for your project.  One place to start might be to remove all the class folders except for the necessary ones (in /com/google/android/gms/):
actions,
appstate,
auth,
common,
drive,
dynamic,
games,
internal,
nearby,
security

Would this work?

**Comment by andrewlord1990** [comment]
1) That is what I was thinking of, are you saying those packages are the ones required by the Google Play Games plugin? 

I posted on here due, to not knowing which parts of the library were required.

2) Also, I don't know why the two huge libgpg static libraries are required?

3) The resources for the lib project (google-play-services_lib/res) that you have to include under Plugins/Android is about 2.4MB on disk (not sure on its compiled size). Can any of this be removed? Seen as all my game uses is Achievements and Leaderboards.

4) How do you run proguard on the project as that will strip and optimize it?

**Comment by tyrmullen** [comment]
1.)  Yup, pretty much.  Although I forgot signin in my initial post-- make sure you keep that one too.  With my sample Cubic Pilot app though, this saves like 2% space, so not sure how worth it this is unless you're hitting the DEX limit.

Technically I believe after this your .jar will still include more than strictly necessary, but not much more and it's probably not worth it to try to scrape through it more than that.  This optimization would also be the one to go for if you're running into the DEX limit.

Also, the plug-in is rather particular about what's in that libs/ folder, so make sure not to leave random things lying around there or you'll get strange dex conversion errors.  Just replace the old jar with the new jar and it will work.

2.)  Well, the libraries are built in an architecture-dependent way, so depending on what device you're pushing to, a different one will be needed.  If you're building for arm-v7a (most Android phones), then you'll need to link against the armeabi-v7a/libgpg.a file for your apk, but won't need the x86 version (Android TV for example).  So this gives you two choices:
    a.)  Build a "fat" binary, which means you push one apk to any type of (supported) device and it "just works", but is much bigger in size.
    b.)  Build specifically for each platform you're targeting.  This will reduce your binary size greatly, but you'll need to push a different one for different architectures.

In Unity (under Build Settings | Android | Player Settings) there's a tag for "Device Filter" which lets you toggle between these choices.  This is one way to potentially save a LOT of space.  Especially if/when additional Android architectures are supported (armv8a, etc.).  For my sample Cubic Pilot app, the difference between a fat and thin binary was ~40% overall reduction in .apk size.

3.)  My res folder seems to only be 1.1MB on disk, with not much looking very removable.  Do you have the latest version of the Games Services library?  Perhaps the resources got pared down a bunch from an earlier version?

If you're really wanting to scrape for extra space, and if you only want support for a few languages, you can save a few KB before compression that way (removing other language folders), and if you are targeting particular devices you might be able to remove the drawables for devices of differing resolutions?  In general, the res/ folder is probably not the best place to look for saving space though.

4.)  I'm not aware of a good way to do this currently.  The Unity plug-in build recently started incorporating gradle, so there may potentially be a way to improve this in the future, but I haven't looked into this yet.

**Comment by andrewlord1990** [comment]
Firstly, thank you very much for such a detailed response.

Thank you very much. I would rather build a FAT binary and target everything for the time being. I have compared to other games and mine isn't actually ridiculous in size. Will remember the above things, if later on I need to shave as much file size as possible.
