### ISSUE TITLE
Inconsistency in bundles between README.md and EditorWindow popup - gpg.bundle

### ISSUE THREAD

**Issue by zentuit** [playgameservices/play-games-plugin-for-unity#509]
In README.md it states:
The necessary bundles and frameworks are:

GoogleOpenSource.framework
GooglePlus.bundle
GooglePlus.framework
gpg.bundle
gpg.framework

But in the Unity EditorWindow popup it states:
2. Add the following bundles and frameworks from the Google Plus
   and the Google Play Games C++ SDKs. These can be downloaded from
   https://developers.google.com/games/services.

      GoogleOpenSource.framework
      GooglePlus.bundle
      GooglePlus.framework
      GooglePlayGames.bundle
      gpg.framework

So is gpg.bundle required or not? I'm assuming GooglePlayGames.bundle is in fact required.

**Comment by claywilkinson** [comment]
Thanks for pointing this out!

gpg.bundle is required - GooglePlayGames.bundle is obsolete.  Both gpg.framework and gpg.bundle should come from the 1.4.1 C++ SDK.

**Comment by zentuit** [comment]
LOL, I was 0 out of 2 there :)

**Comment by claywilkinson** [comment]
No Problem! :)  I updated the source, I will need to repackage the plugin to pick up the change, which I will do later this week.
