### ISSUE TITLE
Google Play Plugin menu does not show

### ISSUE THREAD

**Issue by Turtlez82** [playgameservices/play-games-plugin-for-unity#513]
If i'm installing the newest 0.9.20 package, it won't bring me up the popup menu.
I was tried to install it again, and refreshing the assets or reimporting, but it's wont help.

If i'm installing a previous version like 0.9.15, its working again...

What am i do wrong ? - I think it's a bug in the newest version...

**Comment by claywilkinson** [comment]
You'll need to delete the GooglePlayGames folder in the Assets, then import the new plugin version.  Are there errors in the console?  The menu moved to be more in line with the Unity plugin standards.  The menu is now in Window>Google Play Games

**Comment by Turtlez82** [comment]
I'we already done the first part (delete , gpg dir and plugin dir, refresh, reimport etc etc..., restart unity...).
The second part: i will check it out (menu in window menu :) ) - but later :)  - anyway tnx for the quick response!

**Comment by Turtlez82** [comment]
I'ts working. Thanks, for reply.

**Comment by claywilkinson** [comment]
great!

**Comment by AngelNegrete** [comment]
i'm still having this issue with GooglePlayGamesPlugin-0.9.50, i have configured the game in the Google Play Console and linked to mi app, changed the SHA1 certificate in the Console Developer Google to the upload certificate, but not Google Play Games window is poping up.

i have tried to erase GooglePlayGames folder and PlayServicesResolver folder and re-import the plugin and setup again,restarting Unity but nothing is happening when calling the method, here is my code: 

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SocialPlatforms;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.UI;
using System;

public class googleSignIn : MonoBehaviour {
	
	public Text authText;
	public Text logro;
	public Text username;
	//---------------------------------------------------------------------------------------------------------------
	void Start()
	{
		PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
			.RequestIdToken()
			.Build();

		PlayGamesPlatform.InitializeInstance(config);
		PlayGamesPlatform.Activate();
	}
//Called this function from a button 
	public void ButtonCallGPG()
	{
		OnLobbyConnect ();
	}

	public void OnLobbyConnect()
	{
		if(PlayGamesPlatform.Instance.IsAuthenticated())
		{
			username.text = ((PlayGamesLocalUser)Social.localUser).userName.ToString ();
			authText.text = "Successful!";
			StartCoroutine(OnAuthenticate());
		}
		else
		{
			Social.localUser.Authenticate((bool success) =>
				{
					if(success)
					{
						
						authText.text = "Successful";
						StartCoroutine(OnAuthenticate());
					}
					else
					{
						authText.text = "Failed";
						
					}
				});
		}
	}

	IEnumerator OnAuthenticate() {

		// Just in case, I do wait for the token

		string _token = null;
		int counter = 0;
		do
		{
			if(counter++ > 3)
			{
				break;
			}

			yield return new WaitForSeconds(2.0f);

			_token = ((PlayGamesLocalUser)Social.localUser).GetIdToken();
			username.text = Social.localUser.userName.ToString();
		}  while(string.IsNullOrEmpty(_token));

		if(string.IsNullOrEmpty(_token))
		{
			// GetUserInfo("");

			yield break;
		}

		// GetUserInfo(_token);
	}


	public void UnlockAchivementUI()
	{
		Social.ReportProgress ("xxxxxxxxxxxxxxxxxx", 100.0f, (bool success) => {
			if (success) {
				logro.text = "CONGRATS!";
			}
			else {
				
			}
		});
	}`

i have been building the app on my phone, however in Unity i always get a Failed, but in the phone i don't get a Successful neither a Failed, is there something missing?
