### ISSUE TITLE
This is request about make some action for playmaker

### ISSUE THREAD

**Issue by zuanzike** [playgameservices/play-games-plugin-for-unity#514]
OK,this is not issues ; Everything is fine,and all the samples I build ; they are good;
but I'm artist and I'm good at unity3d plugin playmaker,I can make games quickly and alone all by this plugin;
and I use another plugin from unity3d asset store for my game to use google play game services,
https://www.assetstore.unity3d.com/en/#!/content/14873 
but it is not so good ,short of some function,just can be used;

so ,Could you PLZ make your pefect plugin turn into playmaker,so artist can also use it freely;I think this is huge market ,because so many artist want to game making

thanks!

**Comment by claywilkinson** [comment]
I think you want to make your request to the third party you are referring to?
