### ISSUE TITLE
Invitation delegate does not invoked on some of my Android devices

### ISSUE THREAD

**Issue by larykUA** [playgameservices/play-games-plugin-for-unity#516]
I've registered an invitation delegate as described here https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/RTMP.md .

~~~
	PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder().WithInvitationDelegate(OnInvitationReceived).Build();
	PlayGamesPlatform.InitializeInstance(config);
	PlayGamesPlatform.DebugLogEnabled = true;
	PlayGamesPlatform.Activate();

~~~

~~~
	public void OnInvitationReceived(Invitation invitation, bool shouldAutoAccept)
	{
		Debug.LogWarning("Room. OnInvitationReceived, autoAccept = " + shouldAutoAccept);
	}
~~~		

~~~
	public void createRoom()
	{
		PlayGamesPlatform.Instance.RealTime.CreateWithInvitationScreen(minimumOpponents, maximumOpponents, gameVariation, this);
	}
~~~

1).
Everything works as it should when I created a room on Pipo P8 tablet and invited Samsung Note 10.1 (2014) one.
OnInvitationReceived is NOT invoked when I created a room on Samsung Note 10.1 (2014) tablet and invited Pipo P8 one.

2).
Everything works as it should when I created a room on Sony U phone and invited Samsung Note 10.1 (2014) one.
OnInvitationReceived is NOT invoked when I created a room on Samsung Note 10.1 (2014) tablet and invited Sony U phone.

3).
I do not have any problems when created room (and invite) Nexus 7, Note 4, Samsung Note 10.1 (2014) in any combinations.

Pipo P8 is Android 4.4.4 OS
Samsung Note is OS 4.4.2
Sony U is OS 4.0.2
Nexus 7 is OS 5.01
Note 4 is OS 5.1

I do not see any big problems in log file (from Pipo P8)

~~~

I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:28 +03:00 DEBUG: Activating PlayGamesPlatform.
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:28 +03:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:28 +03:00 DEBUG: Creating platform-specific Play Games client.
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:28 +03:00 DEBUG: Creating real IPlayGamesClient


D/GamesUnitySDK(12957): Performing Android initialization of the GPG SDK
E/GamesNativeSDK(12957): Exception in dalvik/system/DexClassLoader.loadClass: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.NativeSdkEntryPoints" on path: DexPathList[[zip file "/data/data/com.softick.testGame/app_.gpg.classloader/de80b70ed0da0dfe988a41fa560612ee.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]].

I/GamesNativeSDK(12957): Auth operation started: SIGN IN
I/GamesNativeSDK(12957): Connecting to Google Play...
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: Entering state: BeforeRoomCreateStartedState
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.


I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: Entering state: ShutdownState
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
I/dalvikvm(12957): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zzh

V/GamesNativeSDK(12957): Play Games callback indicates connection.
I/GamesNativeSDK(12957): Successfully connected to Google Play.

I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: Populating User
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: Found User: [Player: '   ' (id 109424111441329273164)]
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: Maybe finish for User
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: Auth not finished. User=[Player: '   ' (id 109424111441329273164)] achievements=
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: Populating Achievements
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: Maybe finish for Achievements
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: Auth finished. Proceeding.
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: Invoking Callbacks: System.Action`1[System.Boolean]
I/Unity   (12957):  [Play Games Plugin DLL] 05/08/15 16:58:29 +03:00 DEBUG: Invoking user callback on game thread

~~~

The only error is

~~~

E/GamesNativeSDK(12957): Exception in dalvik/system/DexClassLoader.loadClass: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.NativeSdkEntryPoints" on path: DexPathList[[zip file "/data/data/com.softick.testGame/app_.gpg.classloader/de80b70ed0da0dfe988a41fa560612ee.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]].

~~~

but the same error is on Samsung Note. So I think it is not a cause of the problem.

Could anyone help me?
Thanx!

**Comment by ngl1984** [comment]
I have the same problem, I tried with Samsung Note 4, Asus TF300T and a modified version of Bluestacks but no one called the delegate I set, even with 0.9.20 version of the plugin. I tried with invitation when I am inside the game and when the game is in background, never called the delegate method

**Comment by larykUA** [comment]
@ngl1984 Is your GPG authetification successful? Possibly, you have not added your e-mail as tester one in your Google account.

**Comment by ngl1984** [comment]
@larykUA  My game (Formula A in Play store) has been published 2 months ago with only quick game multiplayer feature; in these days I've just added the possibility to create a game with invitation but the delegate doesn't work (nor while in the game nor if I receive an Android notification), but i can play this kind of multiplayer game opening the inbox inside the game and accepting there the invitation (even if already accepted in the android notification, that only works as a link for the game in this situation).

**Comment by simgesimulation** [comment]
I have exactly same problem on samsung tab s8.4. Both in game also out of game no invitation delegate. You guys found something?

**Comment by simsis3d** [comment]
@claywilkinson can you please look at here?

**Comment by simgesimulation** [comment]
OK guys I found the problem. BY default, sync is closed on tablets. Open it:)

**Comment by simgesimulation** [comment]
The problem was invitations could not received by some devices(as far as I observed it was on tablets). Then, I saw that senk/sync(synchronisation) is closed on tablets by default. I enabled synchronisation(the panel where you open/close bluetooth, plane mode etc.). Then invitations started to received both inside and outside the game.

**Comment by larykUA** [comment]
Enabling synchronization have fixed the problem! Thank you @simgesimulation !

**Comment by claywilkinson** [comment]
I think it is OK to close this?  It looks like it is resolved - need to turn sync on.  Please let me know if there are more comments and I can re-open.
