### ISSUE TITLE
get users email when login

### ISSUE THREAD

**Issue by liquid-metal** [playgameservices/play-games-plugin-for-unity#519]
how do i correctly implement it?
i'm planning only to take users email and then take it into my own database for a simple app authentication, but so far i seems can't find any way to do it

anyone can help me?

**Comment by Brainversation** [comment]
Does the class PlayGamesLocalUser help? It gives user name and id.

Hope that helps.

**Comment by liquid-metal** [comment]
thanks for the reply, i'll try it soon, thanks! :D

**Comment by liquid-metal** [comment]
thank you, it does works perfectly, but i do still need users email, since it'll be convinient to send user email and such if theres an upgrade or other news regarding the app

**Comment by Brainversation** [comment]
Sorry that's the best I could find, I hope one of the contributors get back to you.

Good Luck!

**Comment by sorab2142** [comment]
Log both items, one of them is the email ID

**Comment by liquid-metal** [comment]
the "social.localuser.id" is the email id?
and how do i send email via the id?

**Comment by sanmn19** [comment]
This maybe irrelevant but consider the legality of this before collecting email addresses.

**Comment by liquid-metal** [comment]
indeed sir
but how do i see it, when user already using an app with google play integration, at first launch/login user can read what will be read/edit by the app, and user could choose accept or decline at that point, so i personally think it'll be no problem to read users email if user already accept the agreement

but of course, cmiiw

**Comment by sanmn19** [comment]
Probably if this is mentioned in your privacy policy, then it's alright. However, do think about your audience below 13. The rules are quite strict there.

**Comment by liquid-metal** [comment]
noted!, thank you :D

**Comment by liquid-metal** [comment]
by the way, considering the time i research and problem that may occur like sanmn19 said, i will use the email id as additional authentication and let user fill the email themself

thank you very much guys, you've all been a great help
