### ISSUE TITLE
NO_GPGS don't work ?

### ISSUE THREAD

**Issue by Thibaudz** [playgameservices/play-games-plugin-for-unity#520]
Hi

When I compile the project with xcode, I got lots of errors related to GPGS. I don't understand why.
Have you any idea ?

Best
![capture d ecran 2015-05-12 a 10 40 32](https://cloud.githubusercontent.com/assets/12408222/7583118/5d7b9e48-f893-11e4-8157-b3eca9ab4551.png)

**Comment by spacetraveller** [comment]
Did you upgrade from an older version? I suggest removing the Google Play folder and then importing the latest package. Also ,there may be some files that still need to be deleted from the iOS build machine, according to our developer that managed our last successful build, so this may still be an issue.

**Comment by Thibaudz** [comment]
Hi

Thanks for your reply.
No I have not previous version :(

Best

**Comment by claywilkinson** [comment]
@Thibaudz  - Thanks for the question - can you try building one of the samples with NO_GPGS?  I will do the same and see if we can figure out what is going on.

**Comment by Thibaudz** [comment]
Hi Clay

Sorry for the delay.

I test with cubic pilot sample.

If I compile the ios version with mono2.X : it's ok!
but If I use IL2CPP, I got tone of error (see attached)
![capture d ecran 2015-05-30 a 17 10 58](https://cloud.githubusercontent.com/assets/12408222/7897899/f0d7d3aa-06ee-11e5-87df-ac6915a43933.png)

**Comment by claywilkinson** [comment]
Hmm Which version of  Unity are you using?  They have been fixing a lot of bugs in the IL2CPP code.  I tried all the samples with IL2CPP and NO_GPGS and everything worked for me on Unity 5.0.1f1 (and there has been an update since then to 5.0.2)

**Comment by claywilkinson** [comment]
@Thibaudz  - Did you get this resolved?  Since it has been a month, I'd like to close this issue.  Thanks!

**Comment by Thibaudz** [comment]
Sorry, I haven't test with the new version yet. You can close it; I'll
re-open if needed.

2015-07-29 1:05 GMT+02:00 Clayton Wilkinson <notifications@github.com>:

> @Thibaudz <https://github.com/Thibaudz> - Did you get this resolved?
> Since it has been a month, I'd like to close this issue. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/520#issuecomment-125777599>
> .
>



-- 

* Thibaud ZAMORA*
Associé Fondateur
@thibaudz <http://twitter.com/thibaudz> | LinkedIn
<http://www.linkedin.com/pub/thibaud-zamora/66/500/400>
176 rue des amandiers 34570 Vailhauquès
 ______
Ce message et toutes les pièces jointes sont confidentiels et établis à
l’intention exclusive des destinataires.
Si ce message vous parvenait par erreur, nous vous demandons de le détruire
et d’en avertir immédiatement l’expéditeur par e-mail.
L’usage ou la divulgation d’informations confidentielles par un tiers non
autorisé est passible de poursuites judiciaires.

-- 
______
Ce message et toutes les pièces jointes sont confidentiels et établis à 
l’intention exclusive des destinataires.
Si ce message vous parvenait par erreur, nous vous demandons de le détruire 
et d’en avertir immédiatement l’expéditeur par e-mail.
L’usage ou la divulgation d’informations confidentielles par un tiers non 
autorisé est passible de poursuites judiciaires.

**Comment by claywilkinson** [comment]
No problem - thanks for the response. Best of luck!
