### ISSUE TITLE
Achievements cannot be reported to if the game is ran right after install.

### ISSUE THREAD

**Issue by abatilo** [playgameservices/play-games-plugin-for-unity#524]
If you try to write an achievement right after doing a fresh build and run, you get told that the achievement cannot be found. If I end the process of the game and start it again, then everything works.

**Comment by caieu** [comment]
Same happens with me.

**Comment by MontagueMGM** [comment]
I'm getting this problem too. If I recall, this started after I updated to Unity 5.0.2.

**Comment by artjas** [comment]
@abatilo did you find the solution?

**Comment by bluebery** [comment]
I'm also experiencing this issue. I get 'Could no increment, no achievement with ID xxxx' or 'Unable to locate achievement xxx' when loading the game the first time after deploying to a device (either through Unity or adb or play store). 

When ending the process of the game and starting it again, everything works as OP mentioned.

**Comment by Fonserbc** [comment]
I'm experiencing this as well on version 0.9.20
It is something quite annoying indeed.

**Comment by claywilkinson** [comment]
This has been improved in the latest updates.

**Comment by prakashangappan** [comment]
Still happens on Unity 5.4.1f1 with GPGS 0.9.35.

**Comment by fyn777** [comment]
Same problem after first game run. Unity 5.3.2f1, plugin 0.9.36
`WARNING: Unable to locate achievement`
I should restart the game or logout and login again in google play game to open achievement.
Did anyone find the solution?
