### ISSUE TITLE
Multiplayer invitation not received by android device

### ISSUE THREAD

**Issue by turkenh** [playgameservices/play-games-plugin-for-unity#525]
I successfully set up APNs to receive multiplayer invitations on iOS devices. Checked on real device and saw that, I can receive invitation on my iPad/iPhone. 
But when I switch to Android, I did not see any notification both when running or not running the application. Can send and receive from iOS to iOS and Android to iOS, but can not receive from iOS to Android.

Am I missing something, what should I do to enable notifications for this purpose on Android side? i.e. in manifest file, on developer console etc?

**Comment by ZenithCode** [comment]
@turkenh I am having the same issues.  Thought it was fixed when I upgraded to 0.9.20 but I was wrong.  

@claywilkinson - Can you check this out again please?

**Comment by simgesimulation** [comment]
is it  iOS to Android problem or something else? Because invitation delegate does not called on some samsung devices. No matter inside or outside game.

**Comment by turkenh** [comment]
Rather than iOS to Android, the problem is, not receiving any invitation on Android. I am using Samsung Galaxy s4, and could never see any invitation notification yet.

**Comment by turkenh** [comment]
Just checked with Sony xperia z1 compact, and there is no problem there. Seems that it is a problem occuring only on some Android (or Samsung) devices as @simgesimulation  mentioned.

**Comment by simgesimulation** [comment]
Yeah, I tried with 5 different devices and 2 of them is not receiving invitations. One of them is samsung other one is asus. I have written to @claywilkinson but still no response... as always.

**Comment by simgesimulation** [comment]
wait wait wait... someone will response....

**Comment by simgesimulation** [comment]
OK guys I found the problem. BY default, sync is closed on tablets. Open it:)

**Comment by claywilkinson** [comment]
@simgesimulation  - Thanks for sharing your response.  Can you expand on what the problem was?  What do you mean by "sync is closed"?

**Comment by simgesimulation** [comment]
The problem was invitations could not received by some devices(as far as I observed it was on tablets). Then, I saw that senk/sync(synchronisation) is closed on tablets by default. I enabled synchronisation(the panel where you open/close bluetooth, plane mode etc.). Then invitations started to received both inside and outside the game.

**Comment by turkenh** [comment]
Thank you very much @simgesimulation. It makes a lot of sense, that you do not receive game notification if synchronization is disabled. But missed that, since I was testing my app on a device that I do not actively use. 
So, just enabling synchronization, did the trick. Closing this issue, thanks again:)
