### ISSUE TITLE
Upgrading from 0.9.12 to 0.9.20, get InvalidOperationsException

### ISSUE THREAD

**Issue by spacetraveller** [playgameservices/play-games-plugin-for-unity#526]
I've made an upgrade of the plugin to 0.9.20 from 0.9.12

When attempting to run the app on the android device, after setting up client ID and configuring, this error appears :
I/Unity   (24278): InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK
I/Unity   (24278):   at GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build (GooglePlayGames.Native.PInvoke.PlatformConfiguration conf
gRef) [0x0002d] in...

This is 4.6.5f1 of Unity.

I've done some testing in order to get this to work again, and noticed than from version 0.9.15 it doesn't have the same UI that used to appear with the familiar google play UI in 0.9.12

Any assistance would be appreciated.

**Comment by spacetraveller** [comment]
I believe that updating the Google Play Games bundle in the SDK folder (in Android Studio, if that's what you're using) fixes that issue. No mention of this anywhere, however.

**Comment by claywilkinson** [comment]
There was a problem loading the plugin in 4.6.  This has been fixed.  Please open an issue if you are still having problems.
