### ISSUE TITLE
Push notification feature requires registration ID

### ISSUE THREAD

**Issue by spacetraveller** [playgameservices/play-games-plugin-for-unity#527]
The registration ID , as defined here : https://developer.android.com/google/gcm/client.html is required in order to implement push notifications to an android device.

Is there any way to access this variable through the PGS Unity API ? If not, would it be possible to add this implementation as the registration ID is required in this instance.

**Comment by claywilkinson** [comment]
Are you wanting to send play game services notifications, or your own app-specific notifications?  I am presuming you want to send your own notifications, so you would need to have your own registration ID.  There is not one that is sharable with a specific game.
