### ISSUE TITLE
Unable to show leaderboard second time

### ISSUE THREAD

**Issue by jtate5** [playgameservices/play-games-plugin-for-unity#528]
On Android, after successfully showing a leaderboard, I am unable to open the leaderboard a second time.  I am using version 0.9.15 and tested on Android 4.2.1 and 4.2.2.  Here is my log output:

I/GamesNativeSDK(28434):  Successfully connected to Google Play.
E/GamesNativeSDK(28434):  Trying to show UI while waiting for a result from an existing UI. Please ensure that OnActivityResult is forwarded to the Games C++ SDK from your Java activity. See android_support.h for more details.
I/Unity   (28434):   [Play Games Plugin DLL] 05/19/15 15:38:47 -05:00 DEBUG: Showing UI Internal callback: ERROR_UI_BUSY
I/Unity   (28434):   
I/Unity   (28434):  (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   (28434):  
I/Unity   (28434):   [Play Games Plugin DLL] 05/19/15 15:38:47 -05:00 DEBUG: Received UI callback: ERROR_UI_BUSY
I/Unity   (28434):   
I/Unity   (28434):  (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   (28434):

**Comment by tyrmullen** [comment]
I believe the problem you're describing was an issue fixed in the latest version of the plug-in; does it still occur if you update?

**Comment by ashwanikumar04** [comment]
Hi, I am also facing the same issue in 9.20 version.

**Comment by claywilkinson** [comment]
@ashwanikumar04  would you mind deleting the Plugins directory and the GooglePlayGames directory and re-importing verion 0.9.20?  It could be the native library was not updated correctly when you updated to .9.20?

If it still happening can you capture a new log when it happens and share that?

**Comment by ashwanikumar04** [comment]
@claywilkinson : Thanks it worked.

**Comment by claywilkinson** [comment]
great!

**Comment by ashwanikumar04** [comment]
@claywilkinson: Need a small info. Is there any way we can show list of friends to share the game (Google play URL) not by inviting Multiplayer game?

**Comment by claywilkinson** [comment]
That's on the enhancement list.  You can do it via the Java SDK directly, the C# code in the plugin does not support it at this time.
