### ISSUE TITLE
Failed to auth with a specific user

### ISSUE THREAD

**Issue by deepnavy** [playgameservices/play-games-plugin-for-unity#530]
Hello,
In my case my app started hiccuping and after that crashing while logging in with the same specific user. The fact is that everything worked smooth before. Other users log in fine. This specific user logs in fine in other games too.

Here is a log.

>I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:09 +03:00 DEBUG: Activating PlayGamesPlatform.
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:09 +03:00 DEBUG: Instance was not initialized, using default configuration.
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:09 +03:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:09 +03:00 DEBUG: Creating platform-specific Play Games client.
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:09 +03:00 DEBUG: Creating real IPlayGamesClient
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:09 +03:00 DEBUG: Entering state: BeforeRoomCreateStartedState
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:09 +03:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:09 +03:00 DEBUG: Entering state: ShutdownState
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:09 +03:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:09 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730): 1
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:17 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:17 +03:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:17 +03:00 DEBUG: Populating User
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:17 +03:00 DEBUG: Found User: [Player: 'xPLAYERNAMEX' (id XXXXXXXXXXXXXXXXXXXX)]
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:17 +03:00 DEBUG: Maybe finish for User
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:17 +03:00 DEBUG: Auth not finished. User=[Player: 'xPLAYERNAMEX' (id XXXXXXXXXXXXXXXXXXXX)] achievements=
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:33 +03:00 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:33 +03:00 DEBUG: Populating Achievements
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
W/Unity   (14730): *** [Play Games Plugin DLL] 05/20/15 17:38:33 +03:00 ERROR: Error retrieving achievements - check the log for more information. Failing signin.
W/Unity   (14730):  
W/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
W/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:33 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_OUT status: ERROR_NOT_AUTHORIZED
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
I/Unity   (14730): 
I/Unity   (14730):  [Play Games Plugin DLL] 05/20/15 17:38:33 +03:00 DEBUG: Invoking user callback on game thread
I/Unity   (14730):  
I/Unity   (14730): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
>

**Comment by claywilkinson** [comment]
It looks like the user can sign in OK - but it fails listing the achievements in the game for that user.  This usually means the game is not published and the user is not in the tester list.  Can you verify (or add) that user's email address to the list of testers for the game?

**Comment by claywilkinson** [comment]
Since there has not been any activity in a while on this thread, I am going to close it.  Please open another issue if you are still having problems.  Thanks!
