### ISSUE TITLE
Wrong authentication callback status

### ISSUE THREAD

**Issue by readych** [playgameservices/play-games-plugin-for-unity#531]
It seems that the version 0.9.20 didn't fix the issue #443 .
The same issue still exists in the version 0.9.20.

**Comment by claywilkinson** [comment]
Hi @readych  can you post your log file of this?  It will help track down what is going on.

**Comment by readych** [comment]
Hi @claywilkinson the logs hasn't changed. You can find my log files in the issue #443.

**Comment by claywilkinson** [comment]
OK - it is really fixed in 0.9.25 :)
