### ISSUE TITLE
Problems with Authenticating

### ISSUE THREAD

**Issue by AustinGS464** [playgameservices/play-games-plugin-for-unity#534]
Hello, I am having some sort of problem with using Google Play Game Services with Unity. I created an app and a games thing in the developer console, the only thing there that may be an issue is I didn't really have to do anything to create the OAuth? It seemed to do everything for me but I'm not sure.

Otherwise I have no idea. I'll post my AndroidManifest and my GameStart code but I really am at a loss, I've been googling for hours trying to fix this problem and I am at a lost.

    AndroidManifest.xml
    <?xml version="1.0" encoding="utf-8"?>​
    
    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.google.android.gms">
    <uses-sdk android:minSdkVersion="9"/>

    <application>
        <meta-data android:name="com.google.android.gms.games.APP_ID"
        android:value="my app id" />
        <meta-data android:name="com.google.android.gms.appstate.APP_ID"
        android:value="my app id (am using actual id)" />
        <meta-data android:name="com.google.android.gms.version"
        android:value="@Integer/google_play_services_version" />
    </application>

    </manifest>

GameStart.cs (script inside the camera on the start screen)
    using UnityEngine;
    using UnityEngine.UI;
    using System.Collections;
    using GooglePlayGames;
    using UnityEngine.SocialPlatforms;

    public class GameStart : MonoBehaviour {

        // Use this for initialization
        void Start () {
             PlayGamesPlatform.DebugLogEnabled = true;
             PlayGamesPlatform.Activate();
             Social.localUser.Authenticate((bool success) => {
             if (success) {
                   Debug.Log("Success");
                   Social.ReportProgress("CgkI7qyfz9kIEAIQAQ", 100.0f, (bool success2) => {

                     });
                           } else Debug.Log("Bad");
             });
        }

    // Update is called once per frame
    void Update () {

    }

    public void NewUser () {

    }
    }​

Here is my logcat as well
        I/Unity (19262): [Play Games Plugin DLL] 05/25/15 1:02:50 -05:00 DEBUG: Ac​
        ating PlayGamesPlatform.
        I/Unity (19262):
        I/Unity (19262): (Filename: ./artifacts/generated/common/runtime/UnityEngin
        bug.gen.cpp Line: 56)
        I/Unity (19262):
        I/Unity (19262): [Play Games Plugin DLL] 05/25/15 1:02:50 -05:00 DEBUG: In
        nce was not initialized, using default configuration.
        I/Unity (19262):
        I/Unity (19262): (Filename: ./artifacts/generated/common/runtime/UnityEngin
        bug.gen.cpp Line: 56)
        I/Unity (19262):
        I/Unity (19262): [Play Games Plugin DLL] 05/25/15 1:02:50 -05:00 DEBUG: Pl
        amesPlatform activated: GooglePlayGames.PlayGamesPlatform
        I/Unity (19262):
        I/Unity (19262): (Filename: ./artifacts/generated/common/runtime/UnityEngin
        bug.gen.cpp Line: 56)
        I/Unity (19262):
        I/Unity (19262): [Play Games Plugin DLL] 05/25/15 1:02:50 -05:00 DEBUG: Cr
        ing platform-specific Play Games client.
        I/Unity (19262):
        I/Unity (19262): (Filename: ./artifacts/generated/common/runtime/UnityEngin
        bug.gen.cpp Line: 56)
        I/Unity (19262):
        I/Unity (19262): [Play Games Plugin DLL] 05/25/15 1:02:50 -05:00 DEBUG: Cr
        ing real IPlayGamesClient
        I/Unity (19262):
        I/Unity (19262): (Filename: ./artifacts/generated/common/runtime/UnityEngin
        bug.gen.cpp Line: 56)
        I/Unity (19262):
        E/Unity (19262): Unable to find gpg
        I/Unity (19262): DllNotFoundException: gpg
        I/Unity (19262): at (wrapper managed-to-native) GooglePlayGames.Native.Cw
        per.Builder:GameServices_Builder_Construct ()
        I/Unity (19262): at GooglePlayGames.Native.PInvoke.GameServicesBuilder.Cr
        e () [0x00000] in <filename unknown>:0
        I/Unity (19262): at GooglePlayGames.Native.NativeClient.InitializeGameSer
        es () [0x00000] in <filename unknown>:0
        I/Unity (19262): at GooglePlayGames.Native.NativeClient.Authenticate (Sys
        .Action`1 callback, Boolean silent) [0x00000] in <filename unknown>:0
        I/Unity (19262): at GooglePlayGames.PlayGamesPlatform.Authenticate (Syste
        ction`1 callback, Boolean silent) [0x00000] in <filename unknown>:0
        I/Unity (19262): at GooglePlayGames.PlayGamesPlatform.Authenticate (Syste
        ction`1 callback) [0x00000] in <filename unknown>:0
        I/Unity (19262): at GooglePlayGames.PlayGamesLocalUser.Authenticate (Syst
        Action`1 callback) [0x00000] in <filename unknown>:0
        I/Unity (19262): at GameStart.Start () [0x00000] in <filename unknown>:0
        I/Unity (19262):
        I/Unity (19262): (Filename: Line: -1)
        I/Unity (19262):

**Comment by claywilkinson** [comment]
This looks like it cannot find the native library which should be in the Plugins/Android/libs/armeabi-v7a (or x86).
E/Unity (19262): Unable to find gpg
I/Unity (19262): DllNotFoundException: gpg

Can you confirm that these libraries are part of your Unity project?  Maybe delete the GooglePlayGames and Plugins directory and re-add the plugin?

**Comment by AustinGS464** [comment]
I tried this a couple times, but I tried it a couple more and it finally worked out! Thank you!

**Comment by claywilkinson** [comment]
Great news!
