### ISSUE TITLE
Unity web/webgl player

### ISSUE THREAD

**Issue by mailyokesh** [playgameservices/play-games-plugin-for-unity#536]
Hi I have a unity game (IOS/Android) both running google play service using the unity plugin. I have hosted the game in web using unity webplayer as well as webgl preview player and am able to play the game there. I have created the google client id for the webplayer. The official https://github.com/playgameservices/play-games-plugin-for-unity doesnt have instructions on enabling the web service through the plugin. Has any one implemented this. Not able to find any relevant answers on the web. Am able to view leaderboard/achievement in IOS/Android app, want to know how to get it going for the web. Appreciate the help

**Comment by claywilkinson** [comment]
Currently the Google Play Games services plugin does not support the Unity webplayer.  It  has been logged as an enhancement request in #251

**Comment by claywilkinson** [comment]
Tracking this in #124
