### ISSUE TITLE
Question: force-deleting saved games?

### ISSUE THREAD

**Issue by tenpn** [playgameservices/play-games-plugin-for-unity#537]
For debug reasons, sometimes we want to wipe saved games. This could be for testing the new user experience. You can do this via the select-saved-game UI, but is there a way to do it automatically? 

We use playtime for conflict resolution. We could set playtime to int_max and send an empty save, but that would just stop us making new saves instead of deleting server saves.

**Comment by claywilkinson** [comment]
There is a delete API, unfortunately at this time it is not visible via the Unity plugin.  I'll mark it as an enhancement.  If i get a chance I'll see if I can post a snippet in the meantime.

**Comment by tenpn** [comment]
too awesome. thanks.

**Comment by claywilkinson** [comment]
Delete is added in 0.9.21
