### ISSUE TITLE
Incremental achievement - want to show numbers instead of percentage

### ISSUE THREAD

**Issue by prakashangappan** [playgameservices/play-games-plugin-for-unity#538]
Hi, 

How can we make the incremental achievement to show numbers[for example, 5/10] instead of percentage?.

Thanks in advance!

**Comment by claywilkinson** [comment]
This is not really in the control of the Unity plugin, but I passed along the enhancement request to the Android team.  The extreme solution is to implement your own achievement UI (but that is blocked on getting the achievement info from the plugin....)

**Comment by prakashangappan** [comment]
oh ok. thanks for your reply.

**Comment by claywilkinson** [comment]
In the mean time, you can load the achievement data (this API was added in the 0.9.25 release) and then  divide the two values to get the percentage.
