### ISSUE TITLE
Submit to multiple apps' leaderboards through a separate unified app?

### ISSUE THREAD

**Issue by sorab2142** [playgameservices/play-games-plugin-for-unity#539]
I have a bunch of apps each with their own leaderboard, and have now made a bundled together version of them and would like to use their existing leaderboards and not have to make new leaderboards (limit is 70 per app, but now for the single monolithic version the number would easily cross that limit and hence isnt an option for me).

**Comment by claywilkinson** [comment]
@sorab2142  - I would suggest posting this type of question to Stackoverflow with the tag "google-play-games".  Your situation sounds not specific to the Unity plugin and you will reach a larger set of experts.
