### ISSUE TITLE
Connection state almost always resets

### ISSUE THREAD

**Issue by kalimaul** [playgameservices/play-games-plugin-for-unity#54]
On my phone (and I assume many others), OnResume() is called after the login is successful. OnResume sets mConnectionState to ConnectionState.Connecting, and it will never go back to Connected after that. I assume this all happens because Unity calls OnApplicationPause(false) after returning from the sign in overlay activity.

Achievements, Leaderboards generally still work, but I had issues with loading cloud saves because of this.

Commenting out the line in OnResume() that changes the connection state works as a temporary fix.

I'm using the newest version of Unity3D, this plugin and the play services sdk. I can give you more details about my setup if you cannot reproduce this issue.

**Comment by claywilkinson** [comment]
closing as obsolete.
