### ISSUE TITLE
Freeze: GameServicesBuilder.Build()

### ISSUE THREAD

**Issue by Qbit86** [playgameservices/play-games-plugin-for-unity#540]
I'm experiencing freeze when trying to authenticate. “Printf-style debugging” shows that game hangs after stepping into `GameServicesBuilder.Build(PlatformConfiguration configRef)` method, on call to `C.GameServices_Builder_Create(...)`.

~~The strange thing: the issue reproduces always on one test device Nook HD (BNTV400), and never on another instance of the same model.~~ The issue reproduces on both our test Nook devices BNTV400.

Surrounding logs:

    05-27 11:14:17.961: D/dalvikvm(1877): DexOpt: incorrect opt magic number (0xff ff ff ff)
    05-27 11:14:17.961: D/dalvikvm(1877): ODEX file is stale or bad; removing and retrying (/data/data/com.pixel.gun3d/app_.gpg.classloader/de80b70ed0da0dfe988a41fa560612ee.dex)

or

    05-27 10:38:44.806: D/dalvikvm(24974): DexOpt: sleeping on flock(/data/data/com.pixel.gun3d/app_.gpg.classloader/de80b70ed0da0dfe988a41fa560612ee.dex)

----
play-games-plugin-for-unity 0.9.20
Unity 4.6.5p1
Windows 8.1 Pro

**Comment by claywilkinson** [comment]
Is this still an issue for you?  What version of android is the Nook running?  Does it have the Play Games App on it?  I know some earlier versions of the Nook did not run Google Play Services, which could be the problem.

**Comment by Qbit86** [comment]
> Is this still an issue for you?

Yes; I didn't update this plugin, the issue still reproduces.

> What version of android is the Nook running?

“Settings” page says “Software version 2.2.1”; ADB says “4.0.4”, API level 15.

> Does it have the Play Games App on it?

Yes, it does. Version 3.1.11.

**Comment by claywilkinson** [comment]
The message `DexOpt: incorrect opt magic number (0xff ff ff ff)` means that the file was not written correctly.  Can you try to do a clean build of the apk and reinstall?  Also, just to be safe, delete the apk from the device before re-installing?

**Comment by claywilkinson** [comment]
Well I guess that is progress! Can you post the log of the app starting?

**Comment by Qbit86** [comment]
Updating Unity GPS plugin to 0.9.21 and native google-play-services.jar via SDK Manager didn't help, Nook still freezes at the same moment; strange errors on DEX observed again, though cannot confidently assert connection with Play Services.

```
08-05 11:16:44.231: I/Unity(2658): Trying to authenticate with Google Play Games...
08-05 11:16:44.231: I/Unity(2658):  
08-05 11:16:44.231: I/Unity(2658): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
08-05 11:16:44.231: I/Unity(2658):  [Play Games Plugin DLL] 08/05/15 11:16:44 +03:00 DEBUG: Creating platform-specific Play Games client.
08-05 11:16:44.231: I/Unity(2658):  
08-05 11:16:44.231: I/Unity(2658): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
08-05 11:16:44.231: I/Unity(2658):  [Play Games Plugin DLL] 08/05/15 11:16:44 +03:00 DEBUG: Creating real IPlayGamesClient
08-05 11:16:44.231: I/Unity(2658):  
08-05 11:16:44.231: I/Unity(2658): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
08-05 11:16:44.246: D/dalvikvm(2658): Trying to load lib /data/data/com.pixel.gun3d/lib/libgpg.so 0x413eb548
08-05 11:16:44.309: D/dalvikvm(2658): Added shared lib /data/data/com.pixel.gun3d/lib/libgpg.so 0x413eb548
08-05 11:16:44.309: D/GamesUnitySDK(2658): Performing Android initialization of the GPG SDK
08-05 11:16:44.348: D/dalvikvm(2658): Trying to load lib /data/data/com.pixel.gun3d/lib/libgpg.so 0x413eb548
08-05 11:16:44.348: D/dalvikvm(2658): Shared lib '/data/data/com.pixel.gun3d/lib/libgpg.so' already loaded in same CL 0x413eb548
...
08-05 11:16:44.379: D/dalvikvm(2658): Trying to load lib /data/data/com.pixel.gun3d/lib/libgpg.so 0x413eb548
08-05 11:16:44.379: D/dalvikvm(2658): Shared lib '/data/data/com.pixel.gun3d/lib/libgpg.so' already loaded in same CL 0x413eb548
08-05 11:16:44.387: D/dalvikvm(2658): DexOpt: incorrect opt magic number (0xff ff ff ff)
08-05 11:16:44.387: D/dalvikvm(2658): ODEX file is stale or bad; removing and retrying (/data/data/com.pixel.gun3d/app_.gpg.classloader/de80b70ed0da0dfe988a41fa560612ee.dex)
08-05 11:16:44.395: D/dalvikvm(2658): DexOpt: --- BEGIN 'de80b70ed0da0dfe988a41fa560612ee.jar' (bootstrap=0) ---
```

**Comment by Qbit86** [comment]
Additional logging shows that execution freezes in `GameServicesBuilder.Build(PlatformConfiguration configRef)` method; probably in imported `GooglePlayGames.Native.Cwrapper.Builder.GameServices_Builder_Create()` method. Looks like there is some lock aquired and never released. So program freezes in two cases:

1. After reboot or clean install it prints “magic number” message; then `DexOpt: --- BEGIN 'de80b70ed0da0dfe988a41fa560612ee.jar' (bootstrap=0) ---`, but never prints `DexOpt: --- END 'de80b70ed0da0dfe988a41fa560612ee.jar' (success) ---`
2. Next run prints `DexOpt: sleeping on flock(/data/data/com.pixel.gun3d/app_.gpg.classloader/de80b70ed0da0dfe988a41fa560612ee.dex)`

**Comment by darkofmarin** [comment]
same issue,

**Comment by tyomaa** [comment]
Same issue for us on some devicesAsus Eee Pad Transformer TF101 (Android 4.0.3, Unity 4.6.8p2)

**Comment by claywilkinson** [comment]
Closing as old - Please open a new issue, including a log if this is still happening with the recent version of the plugin.
