### ISSUE TITLE
error CS0117: `UnityEditor.BuildTarget' does not contain a definition for `iOS'

### ISSUE THREAD

**Issue by GeorgeDominic** [playgameservices/play-games-plugin-for-unity#544]
I am upgrading from Google Play Services from v 0.9.01 to  0.9.20 in unity 4.5, but I am getting this error  Assets/GooglePlayGames/Editor/GPGSPostBuild.cs(41,39): error CS0117: `UnityEditor.BuildTarget' does not contain a definition for `iOS'

I am developing for android not IOS, any idea how to fix this?

**Comment by GeorgeDominic** [comment]
I solved this problem by installing the latest Unity3d. But still unable to get the google play services setup on the main menu of the editor.

**Comment by claywilkinson** [comment]
After you updated, can you remove the GooglePlayGames folder in the Assets folder, and reimport the package?  The menus should be under Windows/Google Play Games.  (We moved them recently to be a better citizen of the Unity editor).  If they don't show up, there must be still some errors in the console?

**Comment by GeorgeDominic** [comment]
yes found it, it is under Windows/Google Play Games. I did not have delete the GooglePlayGames folder. using the 0.9.20 version as it is. I deleted the old version 0.9.01 completely with all its files and folders before importing the new one.

**Comment by claywilkinson** [comment]
Great news!

**Comment by NikiProgramm** [comment]
У меня тожа такая ошибка 
ошибка CS0117: "buildTarget" не содержит определения для "GameCoreXboxSeries"

**Comment by NikiProgramm** [comment]
Решил вопрос.
Установил новую версию Unity запустил проект на ней 
:)

**Comment by CYFERIOUS** [comment]
> Решил вопрос.
> Установил новую версию Unity запустил проект на ней
> :)

No russian language my friend. thanks for helping me.

**Comment by LeekinGTA** [comment]
@BUCH696  Пожалуйста, расскажите, как исправить эту проблему без обновления Editor.
