### ISSUE TITLE
Loading friends of the logged in user

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [playgameservices/play-games-plugin-for-unity#546]
I would like to load friends of the currently logged in user. The functionality seem to be not implemented, right?
Is there any plans to implement it?

I am willing to implement it (never done an android plugin before but made lots of unity stuff plugins included). Any GuideLines?

**Comment by claywilkinson** [comment]
It is on the list of things to do, but I don't have a specific timeline.  As far as guidelines, there is nothing specific (good idea!).  Here are some pointers and design goals:
1. Start with https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/CONTRIBUTING.md  Which talks about the licensing and related issues.
2. The general plugin architecture is based on the C++ SDK for Google Play Games.  This SDK is cross platform (Android & iOS), so the calls are the same.  This is wrapped by Platform Invocation Services (PInvoke) which marshals the method calls and data from C# to the native platform. This code is in platforms/native/cwrapper and platforms/native/pinvoke.
3. This pinvoke layer is called by C# classes that expose the public API and implement the Unity Social interfaces.  This code is in platforms/native.

You can review NativeClient (https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Platforms/Native/NativeClient.cs) for some more insight in the typical pattern of the implementation.

Let me know if you have questions!

**Comment by ashkan-saeedi-mazdeh** [comment]
Thanks , I'll take a look and talk to the studio managers about the agreement. It should be ok, Then I'll start doing it and will ask questions if any and at the end will send a pull request to contribute it back to the main repo for the general public.

**Comment by ashkan-saeedi-mazdeh** [comment]
Well I've advanced a good amount I think. I added FetchConnected and FetchInvitables to the PlayerManager class and created a FetchListResponse class and callback similar to FetchSelfResponse but with GetLength and GetPlayer(int index) methods instead of GetSelf which returns the player in FetchSelfResponse.

Questions
1- Is the C++ side of GetLength and GetPlayer for FetchListResponse implemented?
2- Why the index of GetPlayer is uintPtr ? shouldn't it be an int? What am I supposed to pass to it? a 0 based index?

3- Do I need to sign with release keystore to try these or using debug key works if my friends sign into the app as testers? Currently my implementation's GetLength() returns 0 for both callbacks.
4- Is there any other call in other classes which I might want to implement (I don't need FetchRecentlyPlayed)?

**Comment by claywilkinson** [comment]
Great!

1. The C++ side  for GetLength and related can be called from the Cwrapper/PlayerManager class.  This is  mostly auto-generated class that calls "flattened out" C functions which call the C++ methods.  For example GetLength is Cwrapper.PlayerManager.PlayerMananger_FetchListResponse_GetData_Length() passing in the handle to the PlayerManager.

2. It's a pointer type, but C# will accept an integer and marshal it correctly. The pattern we use for those types of lists is to make a method like:

             internal IEnumerable<NativePlayer> Data() {
              return PInvokeUtilities.ToEnumerable<NativePlayer>(
                  C.PlayerManager_FetchListResponse_GetData_Length(SelfPtr()),
                         index => new NativePlayer(
                             C.PlayerManager_FetchListRepsonse_GetData_GetElement(SelfPtr(), 
                             index)));
               }
3. No, you should not need to sign with a release keystore, just make sure your friends are in the tester list.

4. Fetch recently played is a nice one - it is friends that have recently played this game, so you know they already have it.  I think once you have converting the response to the C# object collection, adding the recently played should be just a couple methods to wire in to the top level classes.

**Comment by ashkan-saeedi-mazdeh** [comment]
@claywilkinson  Ok so my friend and I both login and we are in each others circles on G+ but still I get 0 for the length of FetchConnected and FetchInvitables Responses.
Is it possible that my call is being done in a wrong way or we should do something else to be in the same group which is returned there. We are working with a debug key signed apk as said before. Android 2.3 and Unity 5.0

**Comment by claywilkinson** [comment]
The permissions for G+ are sometimes confusing.  Can you confirm that you and your friend can see each other using the  standard UI for inviting friends? (Like in TicTacToss sample).

Can you post a log?

**Comment by ashkan-saeedi-mazdeh** [comment]
Well in the tictactoe sample we can not see each other in the invitation list, It says add people to your circles in Google+ to see them here. The find people button's search window shows everyone of course.

We are both in Friends and acquaintances circles of each other but one of the accounts is created less than two days ago so it might be an indexing problem in G+? In his profile when I click people's added him ti circles i'm not shown in the list and it says people added him recently might not be visible.

**Comment by ashkan-saeedi-mazdeh** [comment]
@claywilkinson  Can you please take a look at my fork.
https://github.com/ashkan-saeedi-mazdeh/play-games-plugin-for-unity

I did not send a pull request because I'm not sure if it is fully correct. It should be however, it seems my app has permission issues or something between users. Unfortunately We are not in alpha/beta yet and I don't have full permisions from the studio.

Also unfortunately I worked on it in our own svn repo so commits are not available however the amount of changes is not huge, less than 200 LOC

**Comment by ashkan-saeedi-mazdeh** [comment]
ah and studio layer will sign the agreement after he comes back from E3.

**Comment by claywilkinson** [comment]
Great! I'll take a look

**Comment by ashkan-saeedi-mazdeh** [comment]
Great!!!!
I've also added implementation of SocialPlatform.IUserProfile and friends will be returned from the authenticated user (i.e. localUser)'s friends property.

**Comment by ashkan-saeedi-mazdeh** [comment]
@claywilkinson  I'm getting out of ideas on why it doesn't work. How can I make sure that I am calling something without any permission issues for my friends?
The unity outputted log doesn't show anything special as well. Did you find a chance to take a look at it?

**Comment by claywilkinson** [comment]
I downloaded it :) but have not gotten much past that.   Do you have a log of when you are calling  loadFriends?  I hope to get to this in the next couple days.

**Comment by ashkan-saeedi-mazdeh** [comment]
![Uploading Screenshot_2015-06-16-20-49-22[1].jpg…]()

Hi there! The value 0 is length of friends, true and true called are my own logs but others are from your plugin. I just enabled Logger's logging and took a screenshot and sent it here.

**Comment by ashkan-saeedi-mazdeh** [comment]
http://nooparmy.com/gpgs.jpg the upload doesn't work for some reason.

**Comment by claywilkinson** [comment]
I'll take a look tomorrow - if the log is too big, it can't be pasted here, you can create a [Gist](https://gist.github.com/) and upload it there.

**Comment by ashkan-saeedi-mazdeh** [comment]
Take a look at the log here please
https://gist.github.com/ashkan-saeedi-mazdeh/f6531a59b2310ea2ccb7

**Comment by ashkan-saeedi-mazdeh** [comment]
Take a look at the log here please
https://gist.github.com/ashkan-saeedi-mazdeh/f6531a59b2310ea2ccb7

**Comment by claywilkinson** [comment]
I am look at your changes. I am also having some weirdness with loadConnectedPlayers, I am trying to get more info on what qualifies as "connected".  In the meantime, loadInvitablePlayers seems to work more along the lines of what is expected (Though there is no guarantee that they have the specific game installed)

**Comment by ashkan-saeedi-mazdeh** [comment]
Thank you so much, please keep me posted.
Hmm
The actual thing I needed was loading a player's friend like what we do in
facebook and game center, isn't there any other method for that,
FetchConnected seemed to be the answer (G+ friends which play the game).

On Tue, Jun 30, 2015 at 3:49 AM, Clayton Wilkinson <notifications@github.com
> wrote:

> I am look at your changes. I am also having some weirdness with
> loadConnectedPlayers, I am trying to get more info on what qualifies as
> "connected". In the meantime, loadInvitablePlayers seems to work more along
> the lines of what is expected (Though there is no guarantee that they have
> the specific game installed)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/546#issuecomment-116877357>
> .
>



-- 
-asm

Ashkan Saeedi Mazdeh
NoOpArmy
Skype: ashkan_gc
cell: +(98)9193046544
LinkedIn http://ir.linkedin.com/in/ashkansaeedimazdeh
http://www.nooparmy.com
*//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////*
*//Try to become not a man of success, but try rather to become a man of
value.*
*//Einstein*

**Comment by ashkan-saeedi-mazdeh** [comment]
@claywilkinson Hi man! Did you find out the time to take a good look at it and maybe solve it?
Some people adivced me to use list of players available for turn based matches or realtime matches but that doesn't seem a friend list to me. What is your stand point on this? 
We don't use multiplayer features of the service like turn based and real time for our game at all. For now we use achievements, authentication and also wanna use friends list.

**Comment by claywilkinson** [comment]
Hi! There definitely is a problem with that API.  I opened a ticket for the Server side team.  I'll keep you posted.  In the mean time, I think you can use the Invitable list of players as a substitute...

How do you want to move forward integrating your code?  Do you clean it up and make a PR?  If so, can you do it against the ewokian branch vs. master (there is another update coming soon and we can avoid conflicts).  Or if you wish, I can merge it into the next release (giving you credit in the readme of course :) )

**Comment by ashkan-saeedi-mazdeh** [comment]
@claywilkinson  Sorry for late reply
Maybe you can integrate it , name Gamajun game studio s.r.o as owner of the code, I'm just the person doing the thing.

Any news on loading friends and the bug in the C++ API?

**Comment by claywilkinson** [comment]
No worries.  I am working on integrating it this week - there is a server side issue with the loadConnectedFriends.  It should be fixed soon - I'll update you when there is more info.

**Comment by ashkan-saeedi-mazdeh** [comment]
Great!

**Comment by claywilkinson** [comment]
This has been implemented in the version 0.9.25 of the plugin.  New games/user pairs should be showing up now.  They are in the process of correcting the old data so older associations work now.

Thanks again.

**Comment by ashkan-saeedi-mazdeh** [comment]
@claywilkinson  Sorry for opening this up again, But did you use any of my code? Out of curiosity 
Should I delete my fork?
