### ISSUE TITLE
Quests are not loaded automatically.

### ISSUE THREAD

**Issue by dabeschte** [playgameservices/play-games-plugin-for-unity#548]
There is no way to load quests in code without having to open the default quests ui an clicking "refresh".

**Comment by claywilkinson** [comment]
I believe the last update for the Google Play Games app fixes this problem.  It could also be an issue for unpublished games, which sometimes act a little quirky, but usually settle down after a few hours.

**Comment by claywilkinson** [comment]
Closing since it has been several months.  The initialization has been improved.
