### ISSUE TITLE
Get the access token to use with HTTP API

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [playgameservices/play-games-plugin-for-unity#551]
In order to access features not supported by the SDK I want to grab the access token of the logged in user and use it in web requests. Is it possible (it should be)?

But where can I find the access token?

**Comment by tristan-fgol** [comment]
+1 - this is already requested in https://github.com/playgameservices/play-games-plugin-for-unity/issues/10#issuecomment-109123942

**Comment by JohnTube** [comment]
@ashkan-saeedi-mazdeh try this :
````
"https://accounts.google.com/o/oauth2/" +
            "auth?scope=https://www.googleapis.com/auth/plus.login" +
            "&client_id=" + clientId +
            "&response_type=code" +
            "&redirect_uri=" + redirectUrl;
````

**Comment by illa3d** [comment]
Does anyone know how to avoid the "double login" issue with this method?

In Unity we're using GPG plugin for user login (first login) and we need to give something to our backend (token, auth code, whatever) without having to log in inside the browser again when calling the WWW class with what @JohnTube said.

Thanks!

**Comment by claywilkinson** [comment]
This is covered in issue #10 - OK if I close this issue?

**Comment by ashkan-saeedi-mazdeh** [comment]
I think I'm not going to use it anymore unless the java API works or the HTTP one but C++ bug doesn't resolve. And you have an issue for it so why not?

**Comment by claywilkinson** [comment]
Which bug are you referring to?  The token can be retrieved from the plugin (provided the web app client id is configured) with the player only logging in at most once.  (There is a silent login attempt when the plugin is initialized).  So can I close this issue?

**Comment by ashkan-saeedi-mazdeh** [comment]
I was referring to this
https://github.com/playgameservices/play-games-plugin-for-unity/issues/546

Which is solved now.
