### ISSUE TITLE
Sign-In Activity Reverts to Portrait After Locking Screen

### ISSUE THREAD

**Issue by b-ill** [playgameservices/play-games-plugin-for-unity#552]
I have an app that I want to be landscape-only. I've set the Unity player settings to this effect. When the Google Play sign-in activity is active, if I turn my phone screen off and then back on again, both the underlying Unity app as well as the sign-in window will be in portrait mode. Additionally, it appears that the sign-in will then hang and you must use the back button to get out of it. 

I've tried adding android:configChanges="orientation|keyboardHidden" android:screenOrientation="sensorLandscape" to NativeBridgeActivity in MainLibProj/AndroidManifest.xml, but that does not seem to have changed the behavior.

This can be reproduced using the "Minimal" example and source code in the latest version of the repo. I built with Unity 4.6.3p3 to a Galaxy S5 running Android 4.4.2.

**Comment by claywilkinson** [comment]
Thanks for the report @b-ill. We'll take a look

**Comment by b-ill** [comment]
Here's more info that might help narrow it down:
* It seems like a lock screen must be enabled on the device for the behavior to happen when turning screen on/off
* The same behavior occurs if the app is backgrounded while the login activity is displayed
* The app will properly revert to landscape mode when the login activity exits
* I replicated this issue on Nexus 7 (2013) running Android 5.1

Ultimately, I'm trying to find out what the root cause of this problem is. Is it something that I can fix by adjusting my manifest in some way? Is it an issue in the Play Games Plugin? Is it an Android OS-level issue?

Thanks for the help.

**Comment by b-ill** [comment]
Still haven't been able to make any progress on this on my end. Have you had a chance to take a look yet, @claywilkinson ? Thanks!

**Comment by claywilkinson** [comment]
Can you post a log of the hanging? I tried multiple times on multiple devices and while the unlock page is oriented based on the current rotation of the phone, if the orientation of the app is configured to be landscape, it rotates correctly.  I am using Unity 5.0, have you checked their issue tracker?

**Comment by claywilkinson** [comment]
Please open another issue if this is still happening.  Thanks!

**Comment by simonebg73** [comment]
Has this issue ever been resolved? I believe i am on the latest version in git. Our app is in landscape mode,  I am seeing this where the the Google box appears just before the sign in screen, if you switch to the lock screen while this occurs and then come back, the app goes into portrait mode, the backdrop is half of what it should be and it has essentially soft-locked. If you tap the green google box, it disappears but nothing else happens. We have our own activity derived from UnityPlayerActivity but not sure if that is the issue or not. If i then go to the task switcher and come back, the app renders correctly and continues as normal.

**Comment by MixMasterRickyC** [comment]
We are also seeing this exact behaviour, we are running Unity 4.6.
