### ISSUE TITLE
Getting error while building for android.

### ISSUE THREAD

**Issue by AjayKhara** [playgameservices/play-games-plugin-for-unity#554]
I updated android sdk to the latest,
And now I am getting this error while building.

Error building Player: Win32Exception: ApplicationName='/Applications/adt-bundle-mac-x86_64-20131030/sdk/tools/aapt', CommandLine='package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "/Applications/adt-bundle-mac-x86_64-20131030/sdk/platforms/android-22/android.jar" -F bin/resources.ap_ --extra-packages com.google.example.games.mainlibproj:com.google.android.gms -S "/Data/Unity/Mike/Connect4/Connect4Custom/Temp/StagingArea/android-libraries/google-play-services_lib/res"', CurrentDirectory='Temp/StagingArea'

Please help!

**Comment by sorab2142** [comment]
Paste more of the log as the actual error comes in the long version (click on the error in the list and in the bottom half you will see the full error log)

**Comment by AjayKhara** [comment]
That's exactly what I did.
Please refer to the screenshot.
![screen shot 2015-06-04 at 7 48 48 pm](https://cloud.githubusercontent.com/assets/3821924/7986053/c42d427e-0af2-11e5-8914-b99dd7b1c6e5.png)

I am building from a Mac OS X.

**Comment by claywilkinson** [comment]
Try running the plugin setup again by going to Windows > Google Play Games > Setup > Android Setup

**Comment by AjayKhara** [comment]
Did more than Twice, also restarted a couple of times after the android sdk finished upgrading.
Found something about the copying zipalign from build-tools to tools folder.

nothing really helped.

**Comment by AjayKhara** [comment]
If this helps break down the problem,
Let me tell you why I thought of updating the android sdk.

I was checking the TicTakToe sample project, trying to learn and implement turn based multiplayer in one of my games. So, after changing the bundle id, application Id and building it on my device.
When running the app I saw a "Please wait.." screen at load. And the app got stuck there.

**Comment by claywilkinson** [comment]
what happens if you try from the command line  change directories to /Data/Unity/Mike/Connect4/Connect4Custom/Temp/StagingArea then run
`/Applications/adt-bundle-mac-x86_64-20131030/sdk/tools/aapt package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "/Applications/adt-bundle-mac-x86_64-20131030/sdk/platforms/android-22/android.jar" -F bin/resources.ap_ --extra-packages com.google.example.games.mainlibproj:com.google.android.gms -S "/Data/Unity/Mike/Connect4/Connect4Custom/Temp/StagingArea/android-libraries/google-play-services_lib/res`

**Comment by AjayKhara** [comment]
Please refer to the Screenshot!
![screen shot 2015-06-04 at 9 37 34 pm](https://cloud.githubusercontent.com/assets/3821924/7988620/f16574aa-0b01-11e5-84a5-552788c8e137.png)

**Comment by claywilkinson** [comment]
missing a closing " at the end

**Comment by AjayKhara** [comment]
Right, Sorry about that.
![screen shot 2015-06-04 at 11 37 17 pm](https://cloud.githubusercontent.com/assets/3821924/7991034/c86a0a5a-0b12-11e5-841d-3e8b64b8bf8a.png)

**Comment by claywilkinson** [comment]
So it looks like you are not pointing to the SDK.  This is configured in Unity > Preferences > External Tools

**Comment by AjayKhara** [comment]
I did check that, looks good.
![screen shot 2015-06-04 at 11 41 09 pm](https://cloud.githubusercontent.com/assets/3821924/7991098/4990450e-0b13-11e5-956e-7f46ad295ebd.png)

**Comment by claywilkinson** [comment]
hmm, my aapt is in sdk/build-tools/22.0.1/aapt.  What version of Unity are you running?

**Comment by AjayKhara** [comment]
ok, looks like all the folders in build-tools have the appt file, except the 23.0.0 rc1
![screen shot 2015-06-04 at 11 58 44 pm](https://cloud.githubusercontent.com/assets/3821924/7991443/b4fe110c-0b15-11e5-8bd4-08138561ef97.png)

**Comment by AjayKhara** [comment]
ok, Fixed.
Just copied the aapt file from build-tools to tools folder. And the apk compiled fine.

Thanks for helping breaking this down!
