### ISSUE TITLE
Cloud Save/Load on Different versions of Game.

### ISSUE THREAD

**Issue by simsis3d** [playgameservices/play-games-plugin-for-unity#555]
Forexample, I saved a data to cloud on version2 of my game. Then I updated my game to version3. Then I want to load last saved game(from version2). But, lets say game data on version 2 and version 3 are different(data order, number of data, lets say a new data type is added on new version). So how this will be worked? A similar problem was in RealTime Multiplayer but this is solved by using GameVariant. Is there a smilar variable like "SaveVariant" defined? Help me please.

**Comment by sorab2142** [comment]
If he has the older version, just add the new version's fields to his current save and set them to default values, and then save it to cloud with the new version ID. This way his cloud save wont be wiped due to version mismatch.

**Comment by claywilkinson** [comment]
Closing this since it has been a long time.  Please open another issue if there still is a question.
