### ISSUE TITLE
TurnBased Multiplayer, not getting "OnGotMatch"

### ISSUE THREAD

**Issue by AjayKhara** [playgameservices/play-games-plugin-for-unity#557]
Hello,
I am developing a game using the TurnBased Multiplayer service.

Just came across this Issue.
I have an test apk,
Now when I run the apk on two devices with different OS, (Please refer to the ScreenShot Image)
![screen shot 2015-06-05 at 7 00 45 pm](https://cloud.githubusercontent.com/assets/3821924/8006949/e34369c2-0bb5-11e5-8f82-af076c0eff12.png)

I never get the OnGotMatch callback on older device with 4.2.1 OS, when the other device is connected.

While, if I try again, I do get the OnGotMatch callback on the newer device with 5.0.2 OS every time the other device is connected.

Please help!

**Comment by claywilkinson** [comment]
Can you post logs from the device that is not getting the notification (during the time you send the notification)?  Maybe that will have some clues.

**Comment by AjayKhara** [comment]
Sure,

So the 1st one is 4.2.1 older device, where I didn't get the callback
![screen shot 2015-06-05 at 9 26 19 pm](https://cloud.githubusercontent.com/assets/3821924/8009967/02609672-0bca-11e5-922a-78f6923a5fb9.png)

2nd Image is 5.2.0, where you can see the OnGotMatch callback
![screen shot 2015-06-05 at 9 29 00 pm](https://cloud.githubusercontent.com/assets/3821924/8009975/13f7557e-0bca-11e5-8988-616427b7eb6e.png)

**Comment by claywilkinson** [comment]
For the older one, can you post an unfiltered log? (It will be longer - can you paste it into a comment (or a gist) it will be more than one screen shot.  Thanks!

**Comment by AjayKhara** [comment]
Sure, Here it is!
https://gist.githubusercontent.com/AjayKhara/1392092517ee77a6c4b6/raw/gistfile1.txt

**Comment by claywilkinson** [comment]
Thanks - we'll take a look

**Comment by AjayKhara** [comment]
Hi,
Just checking in.
Wonder if the logs were any help.

**Comment by claywilkinson** [comment]
On the surface, I don't see anything... I forwarded it to another team  - I'll ping them for an update.

**Comment by claywilkinson** [comment]
@AjayKhara  - there has been some updates in this area both in the underlying native library and the unity plugin.  Is this still an issue?   Thanks.

**Comment by AjayKhara** [comment]
@claywilkinson - I think with the latest updates, the Issue is solved.
Thanks!

**Comment by claywilkinson** [comment]
Great!
