### ISSUE TITLE
Unity 5 incompatibility?

### ISSUE THREAD

**Issue by seaders** [playgameservices/play-games-plugin-for-unity#558]
When you install the plugin, despite the

    The Google Play Games Plugin for Unity version 0.9.20 is now ready to use. If this is a new installation or of you have just upgraded from a previous version, please click the 'Google Play Games' menu and select 'Android Setup' and/or 'iOS Setup' to set up your project to build for the corresponding platforms.

popup message, "Google Play Games" doesn't show up in the menus, and then when you try to build for Android, you get an error message

    Project 'GooglePlay/Assets/Plugins/Android/MainLibProj' is missing AndroidManifest.xml file.

So, with the access token inactivity and now this, can we take it that this project is no longer maintained?

**Comment by b-ill** [comment]
Check for "Google Play Games" menu directory under the "Window" directory. You can search the source code for lines containing "MenuItem" to track down the exact hierarchies.

**Comment by sorab2142** [comment]
The plugin works just fine, remove your google play folder from unity, and from the Plugins->Android folder as well and just reimport the plugin. It works just fine.

**Comment by claywilkinson** [comment]
@seaders  - ok if I close this issue?  If you have issues please post the console messages you are getting..

**Comment by seaders** [comment]
Yep, sure.  I missed the "under the Window" part of the readme, and just read it as another menu in that area.  Personally if it read something like a breadcrumb location, "Window > Google Play Games" I would have found it.  Still my fault, though and if others haven't had a problem with it, it's obviously not an issue.  Cheers.
