### ISSUE TITLE
Not Authenticating 

### ISSUE THREAD

**Issue by Jablesp** [playgameservices/play-games-plugin-for-unity#559]
Whenever I click the authenticate button, the green Google Play image pops up, if there is multiple accounts on the device it will ask to choose one to use, if the account does not have Google+ it will take me to set one up. But no matter what I do on what device I use, after all of that it goes back to showing the loading wheel, then the Minimal sample returns to looking exactly how it did before I started. No error messages or anything. This is all I get out of the debug log whenever I press authenticate:

Creating platform specific Play Games client
Creating real IPlayGamesClient
Entering state BeforeRoomCreateStartedState
Defaulting to no op
entering shutdown state
Defaulting to no op
Sign in error not authorized
Sign in error not authorized
Invoking user callback on game thread.

My version is in beta and I'm running it off of an account that is allowed to test. I have been browsing for days trying to find a solution to no avail. Launch is slowly approaching and I really don't want this to become a major setback.

Please help if you can, thanks in advance.

**Comment by Jablesp** [comment]
I have also re set up everything three times (removing all of the old plugin stuff, replacing it all, re running setup (says everything is working)) and still haven't been able to get it working.

**Comment by claywilkinson** [comment]
The Sign in error not authorized could be a couple things:
1. Check the package ID/bundle ID match in the unity player settings and the Play Console and the "linked apps" authorizations.
2. Check the keystore fingerprint you are signing your app with and make sure it matches what is in the "linked apps" authorizations.
3. (I sounds like you have done this one) Check that the user you are signing in as is a tester.

**Comment by Jablesp** [comment]
All of the above done and redone. None of that helped.
Would images assist you at all?

**Comment by Jablesp** [comment]
![1](https://cloud.githubusercontent.com/assets/12766049/8025887/2903fa84-0d33-11e5-8cba-f3c5cc5098ad.png)
![2](https://cloud.githubusercontent.com/assets/12766049/8025889/34703c02-0d33-11e5-9eb2-3dea02039a20.png)
![3](https://cloud.githubusercontent.com/assets/12766049/8025890/3c9037fc-0d33-11e5-990a-8a141dde48e2.png)
![4](https://cloud.githubusercontent.com/assets/12766049/8025892/416a797c-0d33-11e5-8320-9db4d3c687f7.png)
![5](https://cloud.githubusercontent.com/assets/12766049/8025895/490faf8a-0d33-11e5-9442-de031d65c5c6.png)
![6](https://cloud.githubusercontent.com/assets/12766049/8025896/4cd72db4-0d33-11e5-9da1-bed1cb456755.png)
![7](https://cloud.githubusercontent.com/assets/12766049/8025897/4cdf6f2e-0d33-11e5-874a-725b46e9973d.png)

**Comment by Jablesp** [comment]
The above is screenshots in the order of what happens, the final one shows the debug I get back from it.

**Comment by Jablesp** [comment]
Other plugins I'm using are Unity Analytics, Soomla, and Unity Ads. All of those are working without issue, but could they be causing a problem with GPP?

**Comment by claywilkinson** [comment]
It is a good question.  Can you provide a log file of authenticating failing?

**Comment by Jablesp** [comment]
Not sure how to do that but I have the screenshot of everything that comes back from the Unity debug (Using a plugin called Log Viewer to display it in app https://www.assetstore.unity3d.com/en/#!/content/12047)

**Comment by claywilkinson** [comment]
you can run a command line tool from the Android SDK.  With the device connected to the computer, run 
`adb logcat > logfile.txt`  and try to sign in.  Then the file logfile.txt has the log.

**Comment by Jablesp** [comment]
It keeps telling me adb is not found nut it still generates the text file in the sdk folder

**Comment by Jablesp** [comment]
Never mind I figured it out, but it wont let me post, says the comment is too long

**Comment by claywilkinson** [comment]
I think you can save it as a [gist](https://gist.github.com/)

**Comment by Jablesp** [comment]
https://gist.github.com/Jablesp/013a7730ccaaf42b715e

**Comment by claywilkinson** [comment]
From the log, it looks like your app is not configured correctly with respect to the play console.
 
If this app has worked in the past, I'd check the AndroidManifest.xml that is part of the build, given you are using multiple plugins, there might be some weirdness in merging this file.



E/SignInIntentService(28019): Access Not Configured. The API (Google Play Game Services API) is not enabled for your project. Please use the Google Developers Console to update your configuration.
 
E/SignInIntentService(28019): com.google.android.gms.games.server.error.GamesException
 
E/SignInIntentService(28019): 	at com.google.android.gms.games.server.GamesServer.getResponseBlocking(GamesServer.java:156)
 
E/SignInIntentService(28019): 	at com.google.android.gms.games.broker.PlayerAgent.getPlayerFromNetwork(PlayerAgent.java:1737)
 
E/SignInIntentService(28019): 	at com.google.android.gms.games.broker.PlayerAgent.fetchPlayer(PlayerAgent.java:623)
 
E/SignInIntentService(28019): 	at com.google.android.gms.games.broker.DataBroker.loadSelf(DataBroker.java:828)
 
E/SignInIntentService(28019): 	at com.google.android.gms.games.service.PlayGamesSignInIntentService$LoadSelfOperation.executeInternal(PlayGamesSignInIntentService.java:366)
 
E/SignInIntentService(28019): 	at com.google.android.gms.games.service.PlayGamesSignInIntentService$BaseOperation.execute(PlayGamesSignInIntentService.java:52)
 
E/SignInIntentService(28019): 	at com.google.android.gms.games.service.PlayGamesSignInIntentService$OperationAdapter.execute(PlayGamesSignInIntentService.java:451)
 
E/SignInIntentService(28019): 	at com.google.android.gms.chimera.BaseAsyncOperationService$OperationTask.run(BaseAsyncOperationService.java:179)
 
E/SignInIntentService(28019): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 
E/SignInIntentService(28019): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 
E/SignInIntentService(28019): 	at java.lang.Thread.run(Thread.java:856)
 
E/LoadSelfFragment( 8051): Unable to sign in - application does not have a registered client ID
 
W/SignInActivity( 8051): onSignInFailed()...
 
W/SignInActivity( 8051): ==> Returning non-OK result: 10004

**Comment by Jablesp** [comment]
That would be due to me screwing up earlier. Made a new Oauth2 client and did not properly re link the app. Let me apply that fix and re run the logcat.

**Comment by Jablesp** [comment]
And that was the problem. Thank you very much. Sorry for the waste of time, first I've worked on Android.

**Comment by claywilkinson** [comment]
So it is working?  Great!
