### ISSUE TITLE
Cloud save feature without call UI

### ISSUE THREAD

**Issue by schromercy** [playgameservices/play-games-plugin-for-unity#560]
Hey, I am developing a game using plugin version 0.9.11.

I want to implement cloud save feature to my game. For that, i reviewed cubic pilot sample and found that to use cloud save feature, the game need to call ShowSelectSavedGameUI() function.
With that function, user will need to open up a dialog and then create a new save by himself.

That is an unwanted behavior, i want to implement cloud save without calling the UI, where user does not need to create a new save by himself.

Is this supported by the plugin? or are there any other way to use the plugin for achieving my goals?
Thank you

**Comment by sorab2142** [comment]
This is supported by the plugin. just call OpenSavedGame with your filename name and if it doesnt exist create it yourself, the screenshot param is optional so it will work without one as well.

**Comment by claywilkinson** [comment]
Please re-open if you need clarification.  Thanks!
