### ISSUE TITLE
Turn Based Multiplayer, Getting an error when I call play turn.

### ISSUE THREAD

**Issue by AjayKhara** [playgameservices/play-games-plugin-for-unity#562]
Hello,
Can anyone explain this please ?
I see this error in console log when I play a turn.

![screen shot 2015-06-08 at 4 04 03 pm](https://cloud.githubusercontent.com/assets/3821924/8042307/175eeb68-0e3c-11e5-9c9a-1484d90b6fe6.png)

**Comment by claywilkinson** [comment]
Can you tell me what methods you are calling when this happens? or ideally share the log?

The short answer is that the match data is cached on the local device and sync'ed with the server.  In this case the cache was stale. (Without more information, it is difficult to say why).

**Comment by AjayKhara** [comment]
Thanks clay!
I was calling TakeTurn, even when it wasn't turn.
I don't se the error anymore.
