### ISSUE TITLE
Question: Race Aborted when Opponent device goes Dim/Sleep

### ISSUE THREAD

**Issue by benkaranja** [playgameservices/play-games-plugin-for-unity#564]
Hi,
I have been testing the Quiz Racer Sample, and everytime my screen goes dim the Game on opponents device aborts with the Race Aborted message. 
Is this the intended behaviour for the plugin and if so how can I disable this without adding extra timeout on the device or changing the Unity's Screen.sleepTimeout or android manifest?
Please advice
Thanks

**Comment by claywilkinson** [comment]
Screen.sleepTimeout is the correct way to control this behavior.  What is happening is the the device believes it is idle, as a result the application receives the Pause event.  This results in the connections to the other players being disconnected.
More info on the activity lifecycle for Android: http://developer.android.com/training/basics/activity-lifecycle/pausing.html

More info on Screen.sleepTimeout: http://docs.unity3d.com/ScriptReference/Screen-sleepTimeout.html

**Comment by claywilkinson** [comment]
Closing this issue.  Please comment if the issue should be reopened.

**Comment by benkaranja** [comment]
Awesome. Thanks, works fine now

**Comment by claywilkinson** [comment]
Great! thanks for the response.
