### ISSUE TITLE
65K dex limit and selectively compiling APIs

### ISSUE THREAD

**Issue by Qbit86** [playgameservices/play-games-plugin-for-unity#565]
Hi,

We've reached 65K dex limit for method references writing not a single line of own Java code — all the code comes with 3rd party plugins. And Google Play services occupy majority of these references.

Current version of GPG wrapper for Unity comes with huge monolith google-play-services.jar while native developers can enjoy selectively compiling submodules into their applications: https://developers.google.com/android/guides/setup#split

Wait, I've just checked. Jar doesn't come with plugin, but rather appears when we press “Android setup...” menu item. Jar is probably taken from Android SDK / Extras.

Could you please provide a way of importing your plugin such that doesn't require referencing all of the services, but rather small subset?

Thanks.

**Comment by claywilkinson** [comment]
Currently there is no way to trim down the client jar via the plugin.  I'll tag this as an enhancement.  In the mean time, you can look at #508 and #323 which has advice on how to trim down the jar yourself, then replace the trimmed down one in the plugins directory.  The only thing to remember is if you run setup again, you need to replace the jar again.

**Comment by claywilkinson** [comment]
The plugin has been updated in version 0.9.27 to use the aar libraries vs. the client lib project. This will result in much smaller apk file sizes and a substantial reduction in the number of dex entries.
