### ISSUE TITLE
Ios push notifications doesnt work. 

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#566]
From https://developers.google.com/games/services/ios/notifications I found this and it might be the solution. I have not implemented this to my Xcode (cause I dont know how and were or if I really need to). To me it seems that this code is not implemented in the unity plugin..?

4.Next, register your app to receive push notifications after the user successfully signs-in. Add the following code in your finishedWithAuth:error handler, at the point where the user has successfully signed in to Google Play games services. This brings up the standard iOS push notifications dialog. If your game already has registered for push notifications by implementing this code elsewhere, then you don't need to add this line again.

[[UIApplication sharedApplication] registerForRemoteNotifications:
(UIRemoteNotificationTypeBadge | UIRemoteNotificationTypeAlert)];

5.In your appDelegate, add the following code to the callback for retrieving the push device token passed back from APNS. This device token is used for outbound push notifications, and your app must register it with the Google Play games services push service. Make sure to always register your device token through GPGManager to enable push notifications from Google Play games services. Even if the user has not signed in; the GPGmanager object will cache this token and save it until the user signs in.

- (void)application:(UIApplication *)application
        didRegisterForRemoteNotificationsWithDeviceToken
        :(NSData *)deviceToken {
    NSLog(@"Got deviceToken from APNS! %@", deviceToken);
    [[GPGManager sharedInstance] registerDeviceToken:deviceToken
            forEnvironment:GPGPushNotificationEnvironmentSandbox];
}

**Comment by claywilkinson** [comment]
what you are describing is implemented in the plugin.  When you build for iOS, it adds a file to the xcode project: https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/Plugins/iOS/GPGSAppController.mm

In this file is the registration calls.

If you are having issues you might want to make sure the token is being registered correctly with APNS in the AppController.m (by logging it).

Also, there are two certificates you can register on the Play console, one for sandbox and one for production.  Make sure that certificate you are using is the one being configured.  By default the AppController calls
` gpg::RegisterDeviceToken(deviceToken, false);`

which indicates that this is the prod certificate configured on the console.

**Comment by Hoffa25** [comment]
Ok thanks for a good answer!

Do I have to make an app in itunes connect for push notifications to work?

**Comment by claywilkinson** [comment]
No I don't believe so, just the certificate and mobileprovision with push notifications.

**Comment by Hoffa25** [comment]
mobile pro of unity you mean..? i have free version and I cant se that it shouldnt work: https://unity3d.com/get-unity

**Comment by Hoffa25** [comment]
ok... sorry, but what do you mean by "mobileprovision"?

**Comment by claywilkinson** [comment]
The mobileprovision file is generated by apple when you get the apns certificate.  This file is used by xcode to encode what your app is allowed to do.  If you are using XCode mostly to manage the certificates and such, you should have it OK.  
There is a pretty good article talking about apple notifications at http://www.raywenderlich.com/32960/apple-push-notification-services-in-ios-6-tutorial-part-1

**Comment by Hoffa25** [comment]
Ok thanks, seems like a good tutorial!

**Comment by claywilkinson** [comment]
Great.  OK to close this issue?

**Comment by Hoffa25** [comment]
Yeah sure! I just got it to work:D. Thanks alot

**Comment by claywilkinson** [comment]
Fantastic!
