### ISSUE TITLE
Framworks missing

### ISSUE THREAD

**Issue by idzDeveloper** [playgameservices/play-games-plugin-for-unity#567]
I am currently using Unity 5.0.1f1 and google play games latest plugin.
I am exporting for ios with Scripting Backend as lL2CPP.
I have added all the frameworks and libraries as mentioned. Also added GoogleOpenSource.framework,GooglePlus.bundle,GooglePlus.framework,gpg.bundle,gpg.framework.

But whenever I tried to run using lL2CPP I am getting these error 

Undefined symbols for architecture armv7:
  "_Quest_Copy", referenced from:
      Quest_Quest_Copy_m532(Object_t*, HandleRef_t103, MethodInfo*) in Bulk_Assembly-CSharp_1.o
     (maybe you meant: _Quest_Quest_Copy_m532_MethodInfo, __Z21Quest_Quest_Copy_m532P8Object_t14HandleRef_t103P10MethodInfo )
  "_QuestMilestone_Copy", referenced from:
      QuestMilestone_QuestMilestone_Copy_m586(Object_t*, HandleRef_t103, MethodInfo*) in Bulk_Assembly-CSharp_1.o
     (maybe you meant: __Z39QuestMilestone_QuestMilestone_Copy_m586P8Object_t14HandleRef_t103P10MethodInfo, _QuestMilestone_QuestMilestone_Copy_m586_MethodInfo )
 "_Event_Copy", referenced from:
      Event_Event_Copy_m368(Object_t*, HandleRef_t103, MethodInfo*) in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _Event_Event_Copy_m368_MethodInfo, __Z21Event_Event_Copy_m368P8Object_t14HandleRef_t103P10MethodInfo )
  "_EventManager_FetchAllResponse_GetData", referenced from:
      EventManager_EventManager_FetchAllResponse_GetData_m383(Object_t*, HandleRef_t103, IntPtrU5BU5D_t137*, UIntPtr_t104, MethodInfo*) in Bulk_Assembly-CSharp_0.o
     (maybe you meant: __Z55EventManager_EventManager_FetchAllResponse_GetData_m383P8Object_t14HandleRef_t103P17IntPtrU5BU5D_t13712UIntPtr_t104P10MethodInfo, _EventManager_EventManager_FetchAllResponse_GetData_m383_MethodInfo )
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

But when I try Scripting Backend as Mono(2.x) it complies perfectly and works like a charm.
Can you please tell me Whats wrong with lL2CPP as I cant use Mono as Ios is not accepting build with Mono(2.x)

**Comment by claywilkinson** [comment]
Quests were recently added, so it sounds like you have an older version of the gpg Framework, make sure you have have version 1.4.1.

**Comment by idzDeveloper** [comment]
yes its working.. I was using older version of gpg framework.
Thanks for help

**Comment by claywilkinson** [comment]
Great!
