### ISSUE TITLE
an exception is thrown if you try to load the image of a user without an avatar

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [playgameservices/play-games-plugin-for-unity#568]
Hey
There is a bug in PlayGamesLocalUser.cs in LoadImage() method, It's at line 168 where you check if the url is not null and then try to load it with WWW, If the user has no avatar then empty string is returned and this code will cause Java.net.malformedurlException to be thrown. Fixing is easy just use string.IsNullOrEmpty(url) in the if statement.

Since I did not sign a license yet and it will take time from my studio's managers I'm just writing this for the 1 liner fix to be fixed for everyone before we finish the process (actually we did not start it yet even).

**Comment by claywilkinson** [comment]
Thanks for pointing that out!  @ashkan-saeedi-mazdeh  - I'll go ahead and do the one line fix :)

**Comment by ashkan-saeedi-mazdeh** [comment]
@claywilkinson  Great! My pleasure!

**Comment by claywilkinson** [comment]
Fix merged into 0.9.21
