### ISSUE TITLE
Authentication on test device not working

### ISSUE THREAD

**Issue by shay4545** [playgameservices/play-games-plugin-for-unity#569]
I am calling the lines in my script but nothing is happening on my phone when testing. No popup shows up asking me to sign in... here is the code: 
public void SignIn(){
		if (!Social.localUser.authenticated) {
			PlayGamesPlatform.Activate ();
			Social.localUser.Authenticate((bool success) => {
				if(success){
					signInButton.colors = signInFade;   //changing button color
					ObscuredPrefs.SetInt("signedInBefore", 1); //saving int to sign in automaticlly from now on
				}
			});
		}
	}

**Comment by claywilkinson** [comment]
You'll want to always call PlayGamesPlatform.Activate()  - maybe in your Start() method, this connects the PlayGames services to the Social object.

Can you get the log file of what is happening when you start the app?

Maybe also add a log messages to your app so in the log you can see what is going on.

**Comment by shay4545** [comment]
I tried putting the PlayGamesPlatform.Activate function in the start method, but nothing changes. I also put a debug.log in the call before the authentication request when the button is pressed. The log shows up fine, so the button is working, but the authentication call is still not returning anything. Anything put after the authentication request is also ignored.

**Comment by claywilkinson** [comment]
can you post the log?

**Comment by shay4545** [comment]
How do I do that?

**Comment by claywilkinson** [comment]
You can capture the log by opening a terminal window and running `adb logcat > log.txt`  while your device is connected to the computer.  See https://sites.google.com/site/androidhowto/how-to-1/save-logcat-to-a-text-file for more information.  Once you have the log (see if you can see any issues?) you can post it as a gist (sometimes the logs are too big for a comment).

**Comment by shay4545** [comment]
How do I post it to a gist? it is too long.

**Comment by shay4545** [comment]
Nevermind, i found it. Here is the link: https://gist.github.com/shay4545/3e7e050eb69191cb1ba6

**Comment by claywilkinson** [comment]
Can you check that you have the latest play services SDK (this is done in the SDK manager) it looks like you have an older version it based on the log messages below.

Once you have updated the SDK, you'll have to set up the Unity plugin again by running Window > Google Play Games > Setup > Android Setup.

E/GamesNativeSDK( 9900): Can't register class com/google/android/gms/nearby/Nearby: an exception occurred.
 
E/GamesNativeSDK( 9900): Can't register class com/google/android/gms/nearby/connection/AppIdentifier: an exception occurred.
 
E/GamesNativeSDK( 9900): Can't register class com/google/android/gms/nearby/connection/AppMetadata: an exception occurred.
 
E/GamesNativeSDK( 9900): Can't register class com/google/android/gms/nearby/connection/Connections: an exception occurred.
 
E/GamesNativeSDK( 9900): Can't register class com/google/android/gms/nearby/connection/Connections$StartAdvertisingResult: an exception occurred.
`

**Comment by shay4545** [comment]
I don't have the latest version.. Hoping that will solve things. I will tell you how things go after I try what you said.

**Comment by shay4545** [comment]
Alright that seems to have fixed it. The pop up now shows up to sign in. But now when I attempt to sign in or press ok, it never actually signs me in. I can tell because the welcome thing never pops up, and I can sign in multiple times (or attempt to at least).

**Comment by claywilkinson** [comment]
The log will have more information :)
Make sure you follow the instructions to set up your game in the play console: https://developers.google.com/games/services/console/enabling#step_2_add_your_game_to_the_dev_console

Once that is done make sure you setup the plugin in Unity by clicking Window > Google Play Games > Setup > Android Setup.  Enter the App Id from the play console.

It is important that the bundle ID (in player settings/other settings) matches the package name in the play console (in linked apps).  Also, the SHA1 fingerprint of the keystore you are signing your game with needs to match the one in the play console.

Finally, make sure the person you are logging in as is listed as a tester in the play console.

**Comment by claywilkinson** [comment]
@shay4545  - Did you get this resolved?  Is it OK to close this issue?  Thanks!

**Comment by shay4545** [comment]
Yes, thanks for the help
