### ISSUE TITLE
Any games that uses gpg turnbased on both android and ios? (Im wondering if apple accepts that)

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#570]
My game has now come a long way and its almost finished for android. However Im not sure how to proceed with the ios version that im working on now. Will apple accept an app that requires a google login to play? (if no, whould it be ok if i also add a single player mode that dont require login)...or should I go in to the big hedache of doing my ios version with gamecenter turnbased and have a special button for "log in to google to play agianst android friends".

I have tried to find games that uses either option one or two.. but no succes.

**Comment by ZenithCode** [comment]
Check this out: 
https://itunes.apple.com/us/app/dirt-trackin/id940202798?mt=8
https://play.google.com/store/apps/details?id=com.bennettracingsimulations.dirttrackin&hl=en

**Comment by Hoffa25** [comment]
Ok thanks.. they cost money however... im guessing you have made them. Could you just shortly describe how you solved it and i might have a look..?

**Comment by ZenithCode** [comment]
Yes sure.  You require Google Play app on your iOS device for GPG to work properly.  Whenever you try to access the multiplayer feature of the game I check if you have that app on your device and if you don't I take you to the store so you can download GooglePlay first.   (Its not optimal but it works.)

Apple accepted this and the game has been live for a few months now (the multiplayer has been LIVE for about 4 weeks now.)

NOTE:
The latest update was rejected by Apple because of this - so I'll keep try and keep this thread updated with whatever happens next.

**Comment by Hoffa25** [comment]
Ok thanks alot! However i dont understand why you would need google play games app on ios for multiplayer to work? Havnt seen that its required in the plugin info. 

Please do update this thread when you get news fro apple! Im a bit worried about that rejection...

**Comment by ZenithCode** [comment]
The reason is that somehow you need to login to your Google account. 

The other option would be to open the Safari browser, log in there and go back to the app, however it was reported in some other thread that Apple will always reject an App if it requires an external login.

**Comment by Hoffa25** [comment]
Oh ok thats bad news:/

**Comment by ZenithCode** [comment]
They've accepted it before so not all hope is lost yet.  I'll keep you updated.  (Don't hold your breath - it might take up to 10 more days)

**Comment by Hoffa25** [comment]
Ok:)

**Comment by chetanisinanand** [comment]
@ZenithCode  : What is Google Play App on iOS, are you talking about Google+ ?

**Comment by ZenithCode** [comment]
Yes I meant Google+

**Comment by Hoffa25** [comment]
zenithcode: have u checked this out? : http://forum.unity3d.com/threads/google-play-games-login-guide.320187/

**Comment by timmay2t** [comment]
The most recent was rejected again.  Zenith Code and i work on the same project for this one.  I'm trying to get a full understanding from apple through appeal why Candy Crush and other apps can authenticate via the Facebook app, and Safari if you don't have facebook, but we can't.  Seems like it's either they have an issue with us using google, or they are letting certain apps do what they want and preventing others from doing the same.  I'll let you know how the appeal goes.

**Comment by timmay2t** [comment]
Well, after appeal they cut us a break.  They approved and gave us 2 weeks to change the app.  Basically they say that you can authenticate using the Google+ app, but it can't be required to make a feature work in an app.  So there needs to be a priority and a handover to a built in web view if they don't have it installed.

**Comment by chetanisinanand** [comment]
Its certainly the most severe improvement that is required in Google play game service.
Sign-in using Safari is definitely not good in terms of user experience.
Google Team, please implement  a simple web view sign-in  as its a great plugin however not so useful if Apple rejects it on iOS.

**Comment by claywilkinson** [comment]
We're aware of the situation and have a solution being tested.  I'll update this thread when I know more.

**Comment by ZenithCode** [comment]
@claywilkinson ETA please?  Apple gave us 1 week - max 2 weeks until they take off our App until we resolve this issue.

Cheers.

**Comment by claywilkinson** [comment]
I don't know an ETA right now - but I will pass along your experience and get back to you.

**Comment by timmay2t** [comment]
@chetanisinanand sign in via safari is against apple policy anyway, i never did get an answer why some of the bigger apps are allowed to do it anyway.  Didn't think i would.

**Comment by chetanisinanand** [comment]
may be I'm missing, But I've never seen any app goes to safari for sign-in leaving the main app.
Apple believes that this provides a bad user experience.
Facebook and others uses web-view sign-in which do not leave the main application.

**Comment by simsis3d** [comment]
Any news, a solution or a workaround guys? @ZenithCode  @claywilkinson @timmay2t @chetanisinanand

**Comment by timmay2t** [comment]
@zenithcode can link you to the workaround we used it worked like a charm

On Thursday, July 23, 2015, Hakan Ozcan <notifications@github.com> wrote:

> Any news, a solution or a workaround guys? @ZenithCode
> <https://github.com/ZenithCode> @claywilkinson
> <https://github.com/claywilkinson> @timmay2t <https://github.com/timmay2t>
> @chetanisinanand <https://github.com/chetanisinanand>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/570#issuecomment-124231185>
> .
>


-- 
*Bennett Racing Simulations, LLC*
*309 868 6648 (cell)*

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by ZenithCode** [comment]
@simsis3d This is what we did: https://github.com/playgameservices/play-games-plugin-for-unity/issues/608#issuecomment-123834720

**Comment by tyrmullen** [comment]
The newest version of the plug-in now allows for enabling in-app webview sign-in on iOS: https://github.com/playgameservices/play-games-plugin-for-unity/issues/608 has been resolved.
