### ISSUE TITLE
Problems Compiling GPGSPostBuild.cs

### ISSUE THREAD

**Issue by cavpollo** [playgameservices/play-games-plugin-for-unity#571]
I have problems compiling the library for the first time after being installed because the file GPGSPostBuild.cs seems to have a couple lines with a non-C# format:

EditorWindow.GetWindow<GPGSInstructionWindow>(
                utility: true,
                title: "Building for IOS",
                focus: true);

https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Editor/GPGSPostBuild.cs#L72

**Comment by claywilkinson** [comment]
What is the error you are getting?  I have not had any problems with named arguments (which are part of C#: https://msdn.microsoft.com/en-us/library/dd264739.aspx)?

**Comment by cavpollo** [comment]
Huh, you are absolutely right. I had never seen that notation before. Thanks for the tip =)

Anyway, the errors are:

Assets\GooglePlayGames\Editor\GPGSPostBuild.cs(12,12): Error CS1026: ) expected (CS1026) (Assembly-CSharp-Editor)
Assets\GooglePlayGames\Editor\GPGSPostBuild.cs(12,12): Error CS1525: Invalid expression term ':' (CS1525) (Assembly-CSharp-Editor)
Assets\GooglePlayGames\Editor\GPGSPostBuild.cs(14,14): Error CS1002: ; expected (CS1002) (Assembly-CSharp-Editor)
Assets\GooglePlayGames\Editor\GPGSPostBuild.cs(18,18): Error CS1002: ; expected (CS1002) (Assembly-CSharp-Editor)
Assets\GooglePlayGames\Editor\GPGSPostBuild.cs(18,18): Error CS1525: Invalid expression term ',' (CS1525) (Assembly-CSharp-Editor)
Assets\GooglePlayGames\Editor\GPGSPostBuild.cs(19,19): Error CS1002: ; expected (CS1002) (Assembly-CSharp-Editor)
Assets\GooglePlayGames\Editor\GPGSPostBuild.cs(30,30): Error CS1002: ; expected (CS1002) (Assembly-CSharp-Editor)
Assets\GooglePlayGames\Editor\GPGSPostBuild.cs(30,30): Error CS1525: Invalid expression term ',' (CS1525) (Assembly-CSharp-Editor)
Assets\GooglePlayGames\Editor\GPGSPostBuild.cs(31,31): Error CS1002: ; expected (CS1002) (Assembly-CSharp-Editor)
Assets\GooglePlayGames\Editor\GPGSPostBuild.cs(16,16): Error CS1002: ; expected (CS1002) (Assembly-CSharp-Editor)
Assets\GooglePlayGames\Editor\GPGSPostBuild.cs(16,16): Error CS1525: Invalid expression term ')' (CS1525) (Assembly-CSharp-Editor)

By removing the named arguments, I can get the code to compile and work though:
`EditorWindow.GetWindow<GPGSInstructionWindow>(
                true,
                "Building for IOS",
                true);`

Im using MonoDevelop v4.0.1

![screenshoterror](https://cloud.githubusercontent.com/assets/3755976/8154304/01c99816-12f6-11e5-8f9e-3732c947b1e0.PNG)

**Comment by claywilkinson** [comment]
hmm. weird.  Is it the one that is built into Unity?  I am using Mono-Develop 4.0.1 with Unity 5.0.2f1.  I don't know know a lot about it - maybe try the Unity 3d support forums?  Either way, it seems like you have a work around.  I'll mark it as an enhancement request to make them normal arguments.  Feel free to submit a pull request too :)

**Comment by cavpollo** [comment]
Yup, and I'm using Unity 5.0.1f1. Dont know much about it either. Just started using it about a week ago.

Ok, I'll see what I can do =)

**Comment by filipeuff** [comment]
I have the same issue.

**Comment by simsis3d** [comment]
Not sure but may be because of api compatibility level which is .net 2.0 subset bu default. Setting it to .net 2.0 may solve the problem.

**Comment by claywilkinson** [comment]
In this case it was because they were targeting a  pre-4.0 framework.  Regardless, the PR is merged, so old and new versions should work OK.
