### ISSUE TITLE
Is there a way to send an invitation knowing only the gmail adress of a friend?

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#573]
Lets say I want to play against a friend of mine but we are not in eachothers google circles. If we are in the same physical place we could use the nearby connection function to find eachother... but what if we are not? You would first have to add eachother on G+ or in google play games. ..and after you have  done that you would be able to send an invitation using the built in UI were the friend should show up.

To me thats not a very  smooth user experience... What im looking for is a way to send an invitation knowing only the gmail adress of a friend. Is that possible?

**Comment by ZenithCode** [comment]
I don't think so but this would be a very nice to have if its not there yet.

Anyone?

**Comment by Hoffa25** [comment]
I guess you could have a in game function were you add a contact just by typing the gmailadress. Then you dont have the inconvenince of leaving the game...But Im a noob so I dont have a clue how to do that :)

**Comment by claywilkinson** [comment]
It's not part of the games plugin, but there is a new android/ios feature called [App Invites](https://developers.google.com/app-invites/) which does what you want.

**Comment by claywilkinson** [comment]
I've passed this along as an enhancement request.  I am going to close this issue and will update it when there is more information.
