### ISSUE TITLE
App is freezed for 5~10 seconds with black screen before unity logo screen.

### ISSUE THREAD

**Issue by kyuskoj** [playgameservices/play-games-plugin-for-unity#575]
When Application.Quit () is called on back key, the game finished normally.
But trying to execute the app again makes it crash after 5~10 seconds' waiting with black screen.
and just after this moment, app works fine.

unity personal edition 5.1.0f3 // Samsung Galaxy S4

**Comment by claywilkinson** [comment]
@kyuskoj  - Can you post a log of the crash?  Or maybe a code snippet of how you are capturing the back button?  I added a normal GUI button to the Minimal sample that called Application.Quit() and it seems to work fine. 

Also , are you signed in? does it happen if you sign out then call Application.Quit?

Thanks!!

**Comment by kyuskoj** [comment]
@claywilkinson 
I just capturing the back button like this
if (Input.GetKeyUp(KeyCode.Escape))
{
    Application.Quit();
}
and this problem occurs whenever i signed in or not.
Can i test your project case?
Same problem i guess -> https://github.com/playgameservices/play-games-plugin-for-unity/issues/310
Thanks!!

**Comment by claywilkinson** [comment]
That is what I am doing too - I added the if(Input.Get....) { Application.Quit();} code to the end of the OnGUI method of the Minimal Sample.  And everything is OK.

**Comment by kyuskoj** [comment]
@claywilkinson 
this red part is the log when my app has been freezed
![quitproblem](https://cloud.githubusercontent.com/assets/7393684/8198981/4b86d1f4-14e9-11e5-82dc-99e7cd6340f6.PNG)

**Comment by kyuskoj** [comment]
I find out other games on play store has this issue too. ex) Bird Climb

**Comment by kyuskoj** [comment]
@claywilkinson
I posted a log~

**Comment by claywilkinson** [comment]
The red section you hi-lighted is normal.  Is there more to the log when  you get the app not responding alert?  This is not a lot to go on...  Did you try adding the lines to the Minimal sample?

**Comment by kyuskoj** [comment]
@claywilkinson
sorry I'm late.
I tried minimal sample but the problem has been still occurred. (Device: Galaxy S3, S4, Plugin: latest version)
Application.Quit() -> wait more than 10 seconds -> open the app -> no problem.
Application.Quit() -> wait less than 10 seconds -> open the app -> freezing

**Comment by claywilkinson** [comment]
Thanks for the details.
