### ISSUE TITLE
Authenticate failed

### ISSUE THREAD

**Issue by softinus** [playgameservices/play-games-plugin-for-unity#579]
Social.localUser.Authenticate(LoginCallBackGPGS);
after this code, the callback function always return false result.

Since when I changed some configurations, it still doesn't work.
so I set up again all of check list for GPGS plugin.

that's what I've tried to check.
-re-installed to the newest version of plugin and set
-System requirement such as Android build target version and google play service lib version.
-Application ID and Package name are exactly match.
-check test accounts 
-also tried to build without keystore to check whether keystore corresponds with google play server or not.
-fingerprint SHA1 in google developer console.

here's logcat logs.
![kakaotalk_20150619_023051213](https://cloud.githubusercontent.com/assets/4496005/8249032/1bcb54da-16a1-11e5-818e-a1a3291a4341.png)

Interesting fact is when I followed the instruction first time, it used to work well.
It's been awhile since I've tried to manage that kinda problem.
please help me.

development environment
-JDK 1.7.0_79
-Unity 5.1.0f3 Personal
-GooglePlayGamesPlugin-0.9.20

**Comment by claywilkinson** [comment]
The important line in the log is the one that ends in ERROR_NOT_AUTHORIZED.  If it used to work, and now it does not, maybe check which keystore you are using to sign the app and make sure the SHA1 fingerprint matches the one in the linked apps section of the play console.  There is a quick description on how to check the .apk file itself in case you have multiple keystores and are not sure which one is which: http://stackoverflow.com/questions/11331469/how-to-find-out-which-key-was-used-to-sign-an-app

**Comment by claywilkinson** [comment]
@softinus  - did you get this issue resolved?  Is it OK to close this issue?  Thanks!
