### ISSUE TITLE
AchievementID not found.

### ISSUE THREAD

**Issue by PenguinsFly** [playgameservices/play-games-plugin-for-unity#581]
The Error:
http://puu.sh/ixfVm/5e50e0d8ac.png

MyCode:
http://puu.sh/ixg6g/bbbc350f37.png

This is my first time encountering this when before, I've been doing the same thing I'm doing now.

I'm using Unity 5.1.1f1, if this information helps.

Yes, I've doubled, if not, tripled check the achievement ID from google play publish and the one on my code.

Halp me! :sob:

**Comment by claywilkinson** [comment]
Can you post a log of when you are calling ReportProgress?

**Comment by PenguinsFly** [comment]
Here it is:

~~
Achievement ID not found
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:LogError(Object)
UnityEngine.SocialPlatforms.Local:ReportProgress(String, Double, Action`1) (at C:\buildslave\unity\build\Runtime\Export\LocalService.cs:473)
UnityEngine.Social:ReportProgress(String, Double, Action`1) (at C:\buildslave\unity\build\Runtime\Export\NetworkServices.cs:25)
AchievementsManager:SixthAchievement() (at Assets\cScripts\AchievementsManager.cs:91)
AchievementsManager:Update() (at Assets\cScripts\AchievementsManager.cs:46)
~~

**Comment by PenguinsFly** [comment]
Seems like I'm also having issues with everything.

I can't open the Achievement UI:
~~~~~~
ShowAchievementsUI not implemented
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
UnityEngine.SocialPlatforms.Local:ShowAchievementsUI() (at C:\buildslave\unity\build\Runtime\Export\LocalService.cs:587)
UnityEngine.Social:ShowAchievementsUI() (at C:\buildslave\unity\build\Runtime\Export\NetworkServices.cs:60)
MainMenuUI:AchievementsButton() (at Assets\aScenes\MainMenu\Scripts\UI\MainMenuUI.cs:46)
UnityEngine.Events.InvokableCall:Invoke(Object[]) (at C:\buildslave\unity\build\Runtime\Export\UnityEvent.cs:137)
UnityEngine.Events.InvokableCallList:Invoke(Object[]) (at C:\buildslave\unity\build\Runtime\Export\UnityEvent.cs:602)
UnityEngine.Events.UnityEventBase:Invoke(Object[]) (at C:\buildslave\unity\build\Runtime\Export\UnityEvent.cs:744)
UnityEngine.Events.UnityEvent:Invoke() (at C:\buildslave\unity\build\Runtime\Export\UnityEvent_0.cs:53)
UnityEngine.UI.Button:Press() (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\UI\Core\Button.cs:35)
UnityEngine.UI.Button:OnPointerClick(PointerEventData) (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\UI\Core\Button.cs:44)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData) (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\ExecuteEvents.cs:52)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1) (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\ExecuteEvents.cs:269)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData) (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\InputModules\StandaloneInputModule.cs:372)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent() (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\InputModules\StandaloneInputModule.cs:271)
UnityEngine.EventSystems.StandaloneInputModule:Process() (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\InputModules\StandaloneInputModule.cs:169)
UnityEngine.EventSystems.EventSystem:Update() (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\EventSystem.cs:271)
~~~~~

**Comment by claywilkinson** [comment]
Hmm strange. Are you signing in OK?  Did you call  `PlayGamesPlatform.Activate();`  This sets Google Play Games to be the implementation of the ISocial interface.

**Comment by PenguinsFly** [comment]
Oh my God, I feel so embarassed, LOL. I didn't have that call on my first script but everything works fine now... Thank you so much! :laughing:

**Comment by claywilkinson** [comment]
No worries :) We've all been there!
