### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.NativeSdkEntryPoints"

### ISSUE THREAD

**Issue by matemink** [playgameservices/play-games-plugin-for-unity#584]
java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.NativeSdkEntryPoints"

When I try to login:

Social.localUser.Authenticate((bool success) => {
		});

**Comment by claywilkinson** [comment]
Thanks for the post @matemink - That is actually a harmless warning from the C++ SDK - it should be removed in the next release (I think).

**Comment by N1Kav** [comment]
If it helps, I have this error occurs only on x86 devices.

Exception in dalvik/system/DexClassLoader.loadClass: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.NativeSdkEntryPoints" on path: DexPathList[[zip file "/data/data/***/app_.gpg.classloader/de80b70ed0da0dfe988a41fa560612ee.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /system/lib/arm]].

**Comment by claywilkinson** [comment]
Fixed in version 0.9.25 which uses the version 2.0 of the C++ SDK.
