### ISSUE TITLE
Wifi works OK, mobile network not

### ISSUE THREAD

**Issue by viliwonka** [playgameservices/play-games-plugin-for-unity#587]
Hello, quick question. I tested only one device so far, but it should work..

Anyway, when I sign in (Authenticate), it works fine on WiFi (100% of the cases), where as there is almost always a problem when Authenticating with mobile network (3G).

Also one weird thing: Sometimes, when I sign in on mobile network, I get pop up "Welcome User" but it returns false in success callback.

Code:

    Social.localUser.Authenticate((bool success) => {

                if (success) { 

                    Memory.SetString("AutoSignIn", "TRUE");

                    error = false;
                    SignOutButton._.Refresh();

                }
                else {
                    error = true;
                }

                signingIn = false;
                this.Refresh();
            });

Anyone got idea? Maybe it's not even plugins fault but I don't know where to ask.

Thanks for your time!

**Comment by viliwonka** [comment]
Oh, I get error ERROR_NOT_AUTHORIZED (logcat)

![image](https://cloud.githubusercontent.com/assets/4028544/8303322/67313990-199d-11e5-87c7-cf1665185b49.png)

Weird it work with WiFi though.

**Comment by viliwonka** [comment]
Let me say another thing I noticed, when I successfully login with WiFi, then disable WiFi and enable mobile internet, I can load save games just fine. But if I sign out and sign in again, it doesn't works.

**Comment by viliwonka** [comment]
I also tried deleting data (which includes cache) from my game, from Google Play Games app and from Google Play services. 

Still same problem.

**Comment by viliwonka** [comment]
I will try to publish beta and test it that way (on multiple devices). It's only way to find out.

**Comment by viliwonka** [comment]
Ok, looks like it works now that I have published beta version on Play Store. 

Will do testing for few more days and I will close this issue, if it works. Hope anyone else reads this post.

**Comment by gguuss** [comment]
Thanks, please close the issue if it's resolved.
