### ISSUE TITLE
Bad Experience Launching on Android with No Account

### ISSUE THREAD

**Issue by tivobryan** [playgameservices/play-games-plugin-for-unity#589]
After getting a report of a crash I tried the following repro steps:

1. Ensure that no Google accounts are stored in the device's memory.
2. Run the application.
3. Wait for Google Play login screen to appear.
4. Log into a Google account.
5. Notice application crashes (sometimes)

While I haven't gotten the crash, it has always taken a really long time and typically requires restarting the app before leaderboard and achievements actually work.  Do others see this behavior?

Because it takes so long, a lot of log messages scroll by.  One that stood out to me was "DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED".

**Comment by claywilkinson** [comment]
The ERROR_NOT_AUTHORIZED is usually because the game is not in the published state in the play console and the user is not listed as a tester, so this should go away if you add the email address of the account your are about to create to the list of testers.

As far as a the crash - thanks for trying to reproduce!  Usually if you run logcat right after the event, there is enough log in the buffer to give some indication of the issue.

**Comment by tivobryan** [comment]
Got the crash to happen on a Motorola Nexus (Android 5.0, play services 7.5.74)

play-games-plugin-for-unity: 0.9.20
Google Play services SDK rev 25

06-25 18:21:35.575  7520  7520 V GamesNativeSDK: Play Games callback indicates connection.
06-25 18:21:35.674  1518  1688 I GLSUser : [GLSUser] getTokenFromCache: [account: <ELLIDED:7976>, callingPkg: com.com.com, service: oauth2:https://w
ww.googleapis.com/auth/games https://www.googleapis.com/auth/appstate]
06-25 18:21:35.684  7520  7635 I GamesNativeSDK: Successfully connected to Google Play.
06-25 18:21:35.688  7520  7645 W art     : 0x8c6fbba0
06-25 18:21:35.689  1518  1687 I GLSUser : [GLSUser] getAuthtoken(<ELLIDED:7976>, oauth2:https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/d
rive.metadata.readonly https://www.googleapis.com/auth/drive.readonly https://docs.google.com/feeds https://docs.googleusercontent.com https://spreadsheets.goog
le.com/feeds https://www.googleapis.com/auth/activity https://www.googleapis.com/auth/cloudprint https://www.googleapis.com/auth/discussions https://www.googlea
pis.com/auth/docs https://www.googleapis.com/auth/drive.apps https://www.googleapis.com/auth/memento https://www.googleapis.com/auth/spreadsheets https://www.go
ogleapis.com/auth/vouchers https://www.googleapis.com/auth/plus.me ) -> status: null)
06-25 18:21:35.689  1518  1687 I GLSUser : [GLSUser] Extracting token using key: Auth
06-25 18:21:35.704  7520  7645 W art     : 0x8c6fbba0
06-25 18:21:35.757  1518  1687 W GLSUser : [GLSUser] Permission for com.google.android.apps.docs to access oauth2:https://www.googleapis.com/auth/drive https://
www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/drive.readonly https://docs.google.com/feeds https://docs.googleusercontent.com
https://spreadsheets.google.com/feeds https://www.googleapis.com/auth/activity https://www.googleapis.com/auth/cloudprint https://www.googleapis.com/auth/discus
sions https://www.googleapis.com/auth/docs https://www.googleapis.com/auth/drive.apps https://www.googleapis.com/auth/memento https://www.googleapis.com/auth/sp
readsheets https://www.googleapis.com/auth/vouchers https://www.googleapis.com/auth/plus.me  will be managed locally.
06-25 18:21:35.785  7033  8336 I art     : Note: end time exceeds epoch:
06-25 18:21:35.912   853  1081 I ActivityManager: Start proc android.process.acore for content provider com.android.providers.contacts/.ContactsProvider2: pid=8
756 uid=10005 gids={50005, 9997} abi=armeabi-v7a
06-25 18:21:35.964  7520  7520 D AndroidRuntime: Shutting down VM
06-25 18:21:35.964  7520  7520 W System.err: java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
06-25 18:21:35.964  7520  7520 W System.err:    at com.google.android.gms.common.internal.zzi.zzlW(Unknown Source)
06-25 18:21:35.964  7520  7520 W System.err:    at com.google.android.gms.common.internal.zzi.zzlX(Unknown Source)
06-25 18:21:35.964  7520  7520 W System.err:    at com.google.android.gms.games.internal.GamesClientImpl.zzqD(Unknown Source)
06-25 18:21:35.964  7520  7520 W System.err:    at com.google.android.gms.games.internal.GamesClientImpl.onConnected(Unknown Source)
06-25 18:21:35.964  7520  7520 W System.err:    at com.google.android.gms.common.internal.zzj.zzg(Unknown Source)
06-25 18:21:35.964  7520  7520 W System.err:    at com.google.android.gms.common.internal.zzj.zzmh(Unknown Source)
06-25 18:21:35.964  7520  7520 W System.err:    at com.google.android.gms.common.internal.zzi$zzf.zzma(Unknown Source)
06-25 18:21:35.964  7520  7520 W System.err:    at com.google.android.gms.common.internal.zzi$zza.zzc(Unknown Source)
06-25 18:21:35.964  7520  7520 W System.err:    at com.google.android.gms.common.internal.zzi$zza.zzo(Unknown Source)
06-25 18:21:35.964  7520  7520 W System.err:    at com.google.android.gms.common.internal.zzi$zzc.zzmc(Unknown Source)
06-25 18:21:35.964  7520  7520 W System.err:    at com.google.android.gms.common.internal.zzi$zzb.handleMessage(Unknown Source)
06-25 18:21:35.964  7520  7520 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
06-25 18:21:35.964  7520  7520 W System.err:    at android.os.Looper.loop(Looper.java:135)
06-25 18:21:35.964  7520  7520 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:5221)
06-25 18:21:35.964  7520  7520 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
06-25 18:21:35.965  7520  7520 W System.err:    at java.lang.reflect.Method.invoke(Method.java:372)
06-25 18:21:35.965  7520  7520 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
06-25 18:21:35.965  7520  7520 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by claywilkinson** [comment]
Thanks for the callstack. We'll take a look.

**Comment by claywilkinson** [comment]
There is a problem in the C++ SDK (which is the foundation of the Unity plugin) handling this scenario.  At this time, I don't know of  a work around.  It usually does not crash, so logging twice might be an option, but less than ideal.  I'll update the thread when I know more about an update to the SDK.

**Comment by tivobryan** [comment]
Cool, I'm glad you found something.  As usual, I have competing priorities.  I managed to rerun the plugin setup, but ran into the method references limit trying to build.  I need to either get Android Studio installed or find some way of reducing the number of Java methods.

**Comment by tivobryan** [comment]
Since re-running setup, I haven't gotten the crash.  Thanks!

Starting off with no account, my Nexus test device still essentially goes unresponsive for a few minutes.

**Comment by claywilkinson** [comment]
This has been updated in the latest version of the plugin (0.9.25) and works much better.
