### ISSUE TITLE
Cannot authenticate with google apps based accounts

### ISSUE THREAD

**Issue by mslaven** [playgameservices/play-games-plugin-for-unity#59]
I've verified the game appid, SHA1 signature, and name are correct, and that all test accounts are listed properly as Testers.

I can authenticate via a normal google account without any issues, but  when attempting to authenticate with a google apps account (non gmail.com address), even though it has a proper google plus profile, the login fails. It tries to authenticate twice as well.

I see the following message in the log, indicating the app id cannot be found:
E/GameAgent( 2805): Unable to retrieve 1P application 75xxxxxxx81 from network
E/GameAgent( 2805): Game ID (75xxxxxxx81) was not found on server, which is what i would expect if the accounts were not listed as testers. But it's succeeding for regular google accounts with the same ID.

Is it a known issue that google apps based accounts cannot authenticate?

**Comment by mrggl** [comment]
Is this still an issue?

My understanding is that this should work as long as the domain administrator hasn't disabled G+.

**Comment by mslaven** [comment]
It's been many many months since I had worked with the project i was experiencing issues with this on. I'm unsure of the resolution now.

**Comment by claywilkinson** [comment]
@mslaven thanks for the response - I am going to close this issue - post another one if you find it is still unresolved.
