### ISSUE TITLE
Turnbased Multiplayer: Wrong mSelfParticipantId from accepted Invitations via Google Play Games App

### ISSUE THREAD

**Issue by Luro91** [playgameservices/play-games-plugin-for-unity#591]
Hallo,

I have a problem with invitations in my turn based multiplayer game (on Android).

When I get an invitation via push notification and accept it in the Google Play app itself, I get a wrong mSelfParticipantId if the player was not logged in in the game. This leads to problems, when I try to figure out who is the next player after the turn (especially with more than 2 players)

I have tried different test cases on one and two devices (Testclass: https://gist.github.com/Luro91/d6e6340667af832fe6d6):

p_1 invites  p_2 on the same device:
I log in with Player p_1 and invite p_2 and take my turn. Then I get the notification from the Google Play App that p_2 was invited. I open it and accept the invitation. (Google Play prompts me so switch accounts). The game opens, I press login and the delegate gets called. But in the received turnbased match the mSelfParticipantId  in the matchdata is still p_1 although I logged in as player p_2

See Line 598:
https://gist.github.com/Luro91/158ce09d414437588a90

p_1 invites p_2 on the same device and p_1 is not logged anymore when p_2 accepts the invitation:  mSelfParticipantId  is empty.

p_1 invites p_2 on the same device and p_3 is logged in when p_2 accepts the invitation:  mSelfParticipantId  is empty.

p_1 invites p_2 on the same device and nobody is logged in when p_2 accepts the invitation:  mSelfParticipantId  is empty.

When p_1 invites p_2 from a different device mSelfParticipantId  is also always empty when p_2 was not logged in in the game before he accepted the invitation.
Line 87: https://gist.github.com/anonymous/5048cc39b1f9be11dbee

**Comment by claywilkinson** [comment]
This was actually a race condition with the callbacks.   The sign in process had not completed when the invitation callback was called, so there was a bug figuring out who the local player was.

The callback now waits for sign in to complete in version 0.9.25
