### ISSUE TITLE
Achievements working irregularly

### ISSUE THREAD

**Issue by Andres-Barrera** [playgameservices/play-games-plugin-for-unity#592]
Hi everybody,

I'm having an issue while using and displaying the achievements in my game (currently testing on Android only). Sometimes the Achievements UI (Social.ShowAchievementsUI();) will display and work correctly, but sometimes it will show a message saying: "No achievements for this game", and the debug log will display messages about not recognizing my achievements' IDs if I try to unlock them. 

The weird part is that it seems kinda random, because by just re-building the APK (without changing any code), and testing on the same device, the problem appears or disappears. 

The authentication succeeds in both cases, so I'm wondering what can be causing the different behaviours in what seems like two identical build/setups.

Thanks in advance for your help.

**Comment by ITurchenko** [comment]
Same thing happens with me sometimes, especially after first launch after install. Problem often goes away after device rebooting.

**Comment by claywilkinson** [comment]
I think there is some cache invalidation/refreshing weirdness during development.  It should be cleared up now (I am no longer experiencing the issue locally).  Let me know if it is OK to close this issue?

**Comment by Andres-Barrera** [comment]
Tested it this morning. Seems to be working without problems now. 
Thanks
