### ISSUE TITLE
Client disconnecting on scene change

### ISSUE THREAD

**Issue by Cryptomane** [playgameservices/play-games-plugin-for-unity#593]
Hi,

I've implemented this sdk in my game long ago and it was working correctly.
Right now, in the last build, the authentication works perfectly, but it disconnects every time I change scene, not allowing me to save scores and achievements.

What could it be?

**Comment by claywilkinson** [comment]
It's pretty standard to authenticate in one scene (e.g. a menu) and make calls in another scene.  Do you have any explicit calls to signout that might be called?  Can you post a log of switching scenes while logged in?

**Comment by Cryptomane** [comment]
It was my fault.
Totally forgot that months ago I changed the name of the static variable I use to keep the authentication state, so I was checking another variable set to false by default.
