### ISSUE TITLE
How to Run on simulator ?

### ISSUE THREAD

**Issue by chetanisinanand** [playgameservices/play-games-plugin-for-unity#595]
Hi,
I'm using Unity 5.1.1 f1. 
Inside Xcode(6.3.2)  project, Libraries/RegisterMonoModules.cpp no longer contains Zone A, Zone B as mentioned in the document  for running on the simulator.

This is how Libraries/RegisterMonoModules.cpp looks like now: _________________________________________________________________
#ifndef INIT_SCRIPTING_BACKEND
extern void RegisterAllClassesIPhone();

void RegisterAllClasses()
{
	// Register classes for unit tests
	RegisterAllClassesIPhone();
}

void RegisterAllStrippedInternalCalls() {}
#endif

void RegisterMonoModules() {}
___________________________________________________

Please help how to get it work on simulator.

**Comment by claywilkinson** [comment]
Did you try running it as-is just changing the SDK to the simulator?  I'll try it out too if I get a chance.

**Comment by chetanisinanand** [comment]
I did try running it with Simulator SDK Unity build without changing anything in RegisterMonoModules.cpp, and it crashes upon launch in Simulator.

**Comment by claywilkinson** [comment]
I just tried running the Minimal sample  with Unity 5.1.1f1 and Xcode 6.3.2 in the simulator and it worked just fine.  There was a problem with the PodFile (I will submit a Pull request shortly to fix that), but other than that it worked fine.  My steps were:
1. set the bundle ID to match my play console linked iOS app.
2. SDK Version: Simulator SDK
3. Target iOS version: 8.1
4. Copied the client ID from the console, then in Unity hit Window > GooglePlayGames > Setup > iOS Setup and pasted the client id and clicked Setup.
5. Ran Build & Run (lauched xcode, but still complained about some error launch xcode, which I ignored)
6. Opened a terminal window and went to the directory with the xcode project
7. Edited Podfile and uncommented line 2 (platform :ios, '8.0') saved and exit
8. ran `pod update`
9. ran `open Unity-iPhone.xcworkspace`
10. clicked the play button - it compiled and launched the simulator.  I was able to log in.

What exception are you getting in the log?

**Comment by chetanisinanand** [comment]
Thanks a lot  for super quick response, I'll try it as soon as I get back to my system.
Please let me know if Target iOS version: 8.1 is mandatory, or will it work on 7.0 as well ?

Thanks again :-)

**Comment by claywilkinson** [comment]
I would imagine so, I only have 8.x simulators installed.  I tried to change the Unity settings to target 7.0 and it worked Ok (running on the 8.x sim)
