### ISSUE TITLE
SIGN_IN status: ERROR_TIMEOUT

### ISSUE THREAD

**Issue by Kulgann** [playgameservices/play-games-plugin-for-unity#596]
I'm simply trying to invoke the google play games login with my unity game. Here is the code that does it
```c#
void OnEnable()
    {
        if (Application.platform == RuntimePlatform.Android)
        {
            PlayGamesPlatform.DebugLogEnabled = true;
            PlayGamesPlatform.Activate();
        }
	}

    public static void LoginGoogleGamesLocalUser()
    {
        Social.localUser.Authenticate((bool success) =>
        {
            if (success)
            {
                Debug.Log("Successes on login to google play games");


                //Social.ReportProgress(testAch, 100, (bool successAch) => Take this out of here 
                //{
                //    //Ach unlocked 
                //    Debug.Log("tEST AHC UNLOCKED");
                //});
            }
            else { Debug.Log("Login to google play games failed"); }
        });
    }
```

**Comment by claywilkinson** [comment]
ERROR_TIMEOUT indicates a response from the server was not received in time.  This can be due to a variety of reasons, but all of them usually are intermittent.  Unfortunately, there is no easy way to get the result code so you could retry or handle it some other way.  Does it timeout every time?  If so, are you on WiFi? maybe there is some networking issue?

**Comment by Kulgann** [comment]
It does time out every time. and I'm on WiFI yes. But i tested other games like Cut the rope that have this feature and I'm able to log in from them.

**Comment by Kulgann** [comment]
when I registered the test app google gave it numeric id of 11 chars but it gives my game an id of 12 chars. Could this be the problem ?

**Comment by Kulgann** [comment]
Solution : It was the google ad mobs plugin. After "cleaning" the project from all plugins and importing the play games plugin first everything worked great. I suggest that you should look into this issue.
