### ISSUE TITLE
Can't register class

### ISSUE THREAD

**Issue by BestStream** [playgameservices/play-games-plugin-for-unity#597]
I'm updating plugin from 0.9.12 to 0.9.21 and new version not working on android

Unity 4.6.4, Device Nexus 6, OS 5.0

06-30 19:52:49.377: E/GamesNativeSDK(11951): Can't register class com/google/android/gms/nearby/Nearby: an exception occurred.
06-30 19:52:49.378: E/GamesNativeSDK(11951): Can't register class com/google/android/gms/nearby/connection/AppIdentifier: an exception occurred.
06-30 19:52:49.378: E/GamesNativeSDK(11951): Can't register class com/google/android/gms/nearby/connection/AppMetadata: an exception occurred.
06-30 19:52:49.378: E/GamesNativeSDK(11951): Can't register class com/google/android/gms/nearby/connection/Connections: an exception occurred.
06-30 19:52:49.378: E/GamesNativeSDK(11951): Can't register class com/google/android/gms/nearby/connection/Connections$StartAdvertisingResult: an exception occurred.
06-30 19:52:49.420: E/GamesNativeSDK(11951): Could not register one or more required Java classes.

**Comment by claywilkinson** [comment]
The nearby connections classes were recent additions to the play games SDK.  Can you update the play services SDK in the SDK manager?

**Comment by tenpn** [comment]
(this was my problem, and after upgrading the SDK I needed to go to Windows->Google Play Games->Setup->Android to fix things properly)

**Comment by claywilkinson** [comment]
Glad it is resolved!
