### ISSUE TITLE
Incompatible with admob sdk

### ISSUE THREAD

**Issue by rikhtegar** [playgameservices/play-games-plugin-for-unity#6]
The plugin is great but its incompatible with admob's sdk jar file. when I put both of the in the android folder I get the following error message. but when I delete the sdk file (GoogleAdMobAdsSdk-6.4.1.jar) the problem is resolved but I can't use admob any more.

Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/bin/java -Xmx1024M -Dcom.android.sdkmanager.toolsdir="/Users/Nima/Software/Development/android-sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity/Unity.app/Contents/BuildTargetTools/AndroidPlayer/sdktools.jar" -

regards

**Comment by AK541** [comment]
Simply remove your old Java Installation from Computer, Double Check you have installed multi Java installation in computer.

**Comment by firatercis** [comment]
@JEOptimal  thanks a lot. It worked for me. Actually, in the new version of the Google Play Games plugin, they seperated play-services-ads.aar as a different aar file. Removing it just from build (uncheck the Android in import settings) solves the problem.
