### ISSUE TITLE
callback on user signing out from the native UI?

### ISSUE THREAD

**Issue by tenpn** [playgameservices/play-games-plugin-for-unity#603]
If the user opens the leaderboard or achievement native android UI from the game, they can click the hamburger in the top right and sign out. When returned to the game, there's no authentication callback to tell me. The only callbacks are if the game initiates a sign-in or sign-out. I've looked in config builder and the PlayGamesPlatform class but can't see a generic callback.

I can just poll maybe? But that seems messy when there are callbacks for other circumstances.

**Comment by claywilkinson** [comment]
There is not a callback for signout/disconnected.  The typical practice is to check for the authenticated state in Update() or when you need to perform an action that needs to be signed in.
