### ISSUE TITLE
How can I get access token for validation on the backend?

### ISSUE THREAD

**Issue by doterax** [playgameservices/play-games-plugin-for-unity#604]
For security reason I need to know access token of authenticated user.

This token I provide for server side check as described here:

https://www.googleapis.com/plus/v1/people/me?key=[TOKEN]
https://developers.google.com/identity/protocols/OAuth2WebServer#callinganapi

**Comment by Disturbing** [comment]
Bump

**Comment by JohnTube** [comment]
Please check issue #10

**Comment by claywilkinson** [comment]
@doterax / @Disturbing  - This functionality has been added.  If you download/pull the latest unitypackage you can add a web app client ID to the configuration, which will enable getting the token.  There is more information in issue #10
