### ISSUE TITLE
play games and IL2CPP

### ISSUE THREAD

**Issue by narger17** [playgameservices/play-games-plugin-for-unity#607]
hi guys, when i build my game with il2cpp google play games doesn't work (it simply doesn't log in) and in xcode this is the error:

Filename: currently not available on il2cpp Line: -1

what can i do? apple doesn't accept builds made in Mono2x...

p.s. the build made in Mono2x worked
p.s2. the same code on android works perfectly

**Comment by narger17** [comment]
up ! anyone has ever build a game in il2cpp ?

**Comment by claywilkinson** [comment]
I can successfully build the samples using IL2CPP with no issues.  Can you post more of the error log?  Make sure the client id you are using is for the linked ios app for you game in the play console.  Also, try running Window > Google Play Games > Setup > iOS Setup again to make sure it is setup correctly.

**Comment by narger17** [comment]
Thank you for your answer, in these days i'll try to update the plugin in Unity project and retry, if i fail again i'll post the error ;)

**Comment by claywilkinson** [comment]
@narger17 - are you still having issues or can I close this issue?  Thanks!

**Comment by narger17** [comment]
resolved by updating the plugin! Thanks
Il 29/lug/2015 01:24, "Clayton Wilkinson" <notifications@github.com> ha
scritto:

**Comment by claywilkinson** [comment]
nice! glad it was resolved.

**Comment by prakashangappan** [comment]
@narger17 

We are facing the same issue. Can you please share how did you fix this issue?. Which plugin you have updated? google play game services?

**Comment by narger17** [comment]
I've update the Google Play Games plugin to latest version and re-built the project ;)

**Comment by prakashangappan** [comment]
Thanks a lot for the quick reply. We have just updated the gpgs to 0.9.21 and getting these errors in unity,

Assets/GooglePlayGames/Editor/GPGSPostBuild.cs(24,23): error CS0234: The type or namespace name `iOS' does not exist in the namespace `UnityEditor'. Are you missing an assembly reference?

Any idea?

**Comment by narger17** [comment]
just replace the line (i think is 'using UnityEditor.iOS') to this one : using UnityEditor.iOS.Xcode;

**Comment by prakashangappan** [comment]
No, I guess its looking for iOS folder, which is not present inside googleplaygames.

Yes, I have replaced as you have suggested, still throwing the same error.

**Comment by narger17** [comment]
mmm are you on the latest version of unity ?

**Comment by prakashangappan** [comment]
no, using unity4.6.3p3.

**Comment by narger17** [comment]
this may be the problem, update to the latest version ;)

**Comment by prakashangappan** [comment]
hmm ok. but its kind of risky to move to unity 5 at this point. we are already done with the project, only ios builds are creating issues. let me check it anyways. thanks for helping around man. ;)

**Comment by narger17** [comment]
i had your same problem, don't worry, just backup the project and then import it in unity 5, maybe you'll get some errors/warnings but easy things (at least, for me)

**Comment by prakashangappan** [comment]
sure, will give it a try, thanks.
