### ISSUE TITLE
iOS unity game rejected because Google login redirecting to safari browser

### ISSUE THREAD

**Issue by MSBendale** [playgameservices/play-games-plugin-for-unity#608]
Hi there,

iOS unity game continuously rejecting because Google login redirecting to safari browser. We have used Google Play Game Plugin for Unity version 0.9.20 . Can you please provide work around for this?. Apple wants app should google sign in within the app without opening the safari browser.

Can we do same behaviour as in Android platform which sign in within the app without opening browser?

Thank you,
Mayur Bendale.

**Comment by sorab2142** [comment]
1. Create a New File called Application.h (inside XCode otherwise it wont link to your project)
2. Create a New File called Application.mm
3. Click the "+" button (that appears when hovering on a key) in the Info section of your project (aka the Info.plist), add a key called NSPrincipalClass (you will see it change to Principal Class if it worked) and set its value to "Application"
4. Modify Classes->UI->UnityViewControllerBase.h
5. Modify Classes->UI->UnityViewControllerBase.mm

All code required can be found here https://gist.github.com/sorab2142/a3fd6f75e32f2c0b0449

**Comment by MSBendale** [comment]
Thank for your help. I will try this.

**Comment by MSBendale** [comment]
Hi sorab2142,

I have tried this solution. It has one issue after sign in, its opening google page instead of opening game.

Can you please help me to sort out this issue?

Thanks,
Mayur

**Comment by sorab2142** [comment]
This seems to be the case with other games as well (Running Circles has the problem for me).

**Comment by MSBendale** [comment]
Hi sorab2142,

Thanks for you help.

Also can we do this same behavior even if our device has google app. Now, whats happening, if device has Google app then its redirecting to that app for login. I want to do it by webview.

Thanks,
Mayur

**Comment by sorab2142** [comment]
I don't know, I found this on the Unity3d forums, and it currently works
sometimes and then when it doesn't it just stays on a logged in Google
webview and doesn't redirect back to the game.

**Comment by MSBendale** [comment]
Thanks for you reply. I just want to confirm this, my build is rejected, they have given reason because its opening safari browser to log in to google. We have sorted out this by creating web view. 

Now, when if iPad don't have Google app install its log in by opening web view. If iPad contain google app, the its redirecting to the google app for sig in. Can this will result in also rejection? 

I think they just don't want to open safari browser. What you say???

**Comment by sorab2142** [comment]
I am yet to submit for review, so dont really know if it will pass or not.

**Comment by chetanisinanand** [comment]
I believe few steps are not mentioned here , Full solution can be found here : 

http://forum.unity3d.com/threads/google-play-games-login-guide.320187/

**Comment by sorab2142** [comment]
Note: the bundle ID in the hasPrefix line needs to be lowercase only otherwise it wont redirect back to your app.

**Comment by SHAANBHAYA** [comment]
Something that i found,if you have admob or any other ads plugin which uses a web view too ,it will not work as expected(uncertain behavior ,sometimes it will work ,sometimes it wont).One way to solve it is to close all the web views.

**Comment by ZenithCode** [comment]
We did this change and Apple approved our build! 

Cheers!

**Comment by claywilkinson** [comment]
Great news! Congrats!

**Comment by chetanisinanand** [comment]
Got my game Approved by Apple  after following instruction : http://forum.unity3d.com/threads/google-play-games-login-guide.320187/

However, this web-view doesn't contains a 'Back/Cancel' button, and if user tries to sign-in without active internet connection, they will end up on a blank web-view without any buttons or form, user can't go back and must have to kill application and start again.

To avoid this i checked internet connectivity before sending user to web view :

	IEnumerator checkInternetConnection(System.Action<bool> action){
		WWW www = new WWW("http://google.com");
		yield return www;
		if (www.error != null) {
			action (false);
		} else {
			action (true);
		}
	} 

This might help someone till webView sign-in is not implemented by GPGS Team.

**Comment by claywilkinson** [comment]
This has been implemented in the version 0.9.25 of the plugin
