### ISSUE TITLE
help regarding real time multiplayer

### ISSUE THREAD

**Issue by epicepics** [playgameservices/play-games-plugin-for-unity#609]
after quick match, room is created, now after room creation what is the next step to real time multiplayer...?

**Comment by simgesimulation** [comment]
Next is load multiplayer scene(if it is a another scene) and start to send and receieve packages for your game data

**Comment by claywilkinson** [comment]
You can check out the QuizRacer sample, which demonstrates the realtime multiplayer game APIs

**Comment by claywilkinson** [comment]
Is it OK to close this issue? Thanks!

**Comment by epicepics** [comment]
i hv some other issue in quick match criteria, like suppose if i wrote createquickgame(min,max,gamevariants) and define min=1 and max=3, then instead of waiting for the others players game starts after connecting only 2 players in a room, without waiting for the max no of opponents.
