### ISSUE TITLE
How does offline save game works?

### ISSUE THREAD

**Issue by gonzaloguzzardi** [playgameservices/play-games-plugin-for-unity#611]
Hi. I would like to know if google play services support offline save game data and if it does, how does it do it? Can you access that data if the game is closed before saving it online?

Thanks

**Comment by tyrmullen** [comment]
I believe there is some offline save game functionality for Android, but not yet for iOS.  If the game is closed before completion of an online cloud-save, that data must be persisted-to-disk separately or else it will be lost.  This is a key feature being looked into for future updates.

**Comment by claywilkinson** [comment]
Closing since it is old.  The enhancement has been logged internally.
