### ISSUE TITLE
Interrupt while google login

### ISSUE THREAD

**Issue by prakashangappan** [playgameservices/play-games-plugin-for-unity#612]
Hi, we are initializing the google login when the game loads. When we get google login screen[green screen before asking to enter google account details], if we press home button or turn off screen and then go back to game, the login not proceeding. Its proceeding after we touch the screen.

Is this how its supposed to work or Is there any other way we can make google login proceeding automatically the moment we get back to game. i.e. when we come back to game, it has to automatically proceed with login without touching the screen. 

Thanks in advance!

**Comment by claywilkinson** [comment]
No, there is no way to pickup the signin process in the middle.  The way Unity works is that when the activity is resumed, and non-main activities are destroyed and the main game activity is shown.

**Comment by prakashangappan** [comment]
Thanks for the reply.

I think, we can store the status of the game, such as application focus lost and back. So, when focus goes out of the game, we can force cancel/logout the google and then force the google login again when focus comes back to game. Means, cancel the current google login process when focus goes out of the game and call the google login again when focus comes back to the game. Is it the right way to do it? or Is there any other better work around for this?.

**Comment by claywilkinson** [comment]
Closing - sounds like this is a reasonable approach.
