### ISSUE TITLE
Plugins collide on Unity 5

### ISSUE THREAD

**Issue by Guziq** [playgameservices/play-games-plugin-for-unity#613]
Similiar question to #318 but with sligthly different files. 

After adding **Play Games plugin for Unity** I can no longer build my project:

`
Found plugins with same names and architectures, Assets/Plugins/Android/android-support-v4.jar (ARMv7) and Assets/Plugins/Android/libs/android-support-v4.jar (ARMv7). Assign different architectures or delete the duplicate.
UnityEditor.AndroidPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at C:/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
`

Deleting 'duplicates' as suggested (well, they are not: one is 266kB and the one inside Android/libs is 634kB) causes another error:

Failed to re-package resources.

`
CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Program Files (x86)\Android\android-sdk-windows-u5\build-tools\21.1.1\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Program Files (x86)/Android/android-sdk-windows-u5/platforms/android-21\android.jar" -F bin/resources.ap_ --extra-packages com.google.android.gms:com.google.unity:com.google.example.games.mainlibproj:com.example.project -S "E:\project\Temp\StagingArea\android-libraries\google-play-services_lib\res" -S "E:\project\Temp\StagingArea\android-libraries\unity-android-resources\res"
`

Plugin version: 0.9.20
Unity: 5.0.0f4

**Comment by claywilkinson** [comment]
Are you adding other plugins that have that library?  Do you know what is causing 2 files to be included?

**Comment by Guziq** [comment]
After updating to `0.9.21` I am able to build my projecy.

Closing.

**Comment by claywilkinson** [comment]
Great! thanks for the update.
