### ISSUE TITLE
OnRoomConnected() getting called twice after implementing ShowWaitingRoomUI.

### ISSUE THREAD

**Issue by chetanisinanand** [playgameservices/play-games-plugin-for-unity#614]
I've noticed that OnRoomConnected() is getting called twice after implementing ShowWaitingRoomUI.
Please let me know if any of you having same issue

**Comment by rastacre** [comment]
Hey, I have the same issue here.

cannot find a way to stop that from hapening

**Comment by claywilkinson** [comment]
Yep - it is a bug. We're working on a big update to the plugin (should be done soon!) but in the mean time, if you delete [line 1074 in Assets/GooglePlayGames/Platforms/Native/NativeRealtimeMultiplayerClient.cs](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Platforms/Native/NativeRealtimeMultiplayerClient.cs#L1074) it will get rid of the extra call.

**Comment by rastacre** [comment]
Hi Clay,

Thanks for the reply.

I tried the solution, but in doing so once all the players join the room, the player that sends out the invite fails to connect:

Output of: PlayGamesPlatform.Instance.RealTime.GetSelf():
I/Unity   (21078): [Participant: 'xxx' (id p_1234), status=Joined, player=[Player: 'xxx' (id xyz)], connected=False]

While the invitees connect just fine.

I suppose I'll wait for the updated plugin to be released.

Cheers

**Comment by claywilkinson** [comment]
This has been implemented in the version 0.9.25 of the plugin
