### ISSUE TITLE
How to get g+ profile picture

### ISSUE THREAD

**Issue by GeorgeDominic** [playgameservices/play-games-plugin-for-unity#615]
Hi, I am trying to implement the multiplayer feature, I want to get the profile pictures of all the players engaged. I can see that my profile picture is visible in the welcome dialog after signing in. I was looking for the function that fetches the profile picture for me but could not find.

**Comment by narger17** [comment]
I can suggest you this: every player gets its avatar URL and send it in a byte array

**Comment by GeorgeDominic** [comment]
not sure about avatar URL but I am sure there is a way build into the plugin itself

**Comment by GeorgeDominic** [comment]
found a way, its  Social.localUser.image
that's what I was looking for, still need to test thought.

**Comment by claywilkinson** [comment]
The minimal sample demonstrates the localUser.image code.

**Comment by GeorgeDominic** [comment]
yes I was studying that piece of code, I have already implemented waiting to test it.

**Comment by ArmandCloud** [comment]
You can only optain your picture only. you should send your picture in byte array to other users.

**Comment by Yecats** [comment]
I was able to do this in a turn based game. the code I used was:

Participant opponentInfo = match.Participants.Find(x => x.ParticipantId != match.SelfParticipantId);
 
You can then access it with: opponentInfo.Player.AvatarURL.

**Comment by GeorgeDominic** [comment]
ok, will check it out, thank you

**Comment by ArmandCloud** [comment]
Thanks @Yecats ,
I will try this one .

**Comment by GeorgeDominic** [comment]
issue can be closed, thank you

**Comment by claywilkinson** [comment]
Great! thanks!
