### ISSUE TITLE
timeSpan for Leaderboard

### ISSUE THREAD

**Issue by shadowbiz** [playgameservices/play-games-plugin-for-unity#616]
Is there any way to use timeSpan (TIME_SPAN_DAILY, TIME_SPAN_WEEKLY, or TIME_SPAN_ALL_TIME) when showing leaderboard?
Or is there any other way to make Daily/Weekly leaderboard using this plugin?

**Comment by claywilkinson** [comment]
There is an update to the C++ SDK planned that will have the timespan functionality.  I don't have an exact timeframe for the update - but stay tuned!

**Comment by claywilkinson** [comment]
This has been implemented in the version 0.9.25 of the plugin
