### ISSUE TITLE
Get All Open Turn based Matches

### ISSUE THREAD

**Issue by KeySam** [playgameservices/play-games-plugin-for-unity#617]
I would like to implement my own behaviour to load matches, the problem for me is to get all the match ids. I was able to extend the classes provided to give me an updated match once i have the match id(for taking a turn). But what i realy would want to do is get a list of all the matches not finished, so i can implement my own gui for taking turns/ joining / creating matches. So is there a way to do it or could you extend the code to give us access to this functionality, i saw in the documentation that the java implemenation has something like that:

public TurnBasedMatchBuffer getMyTurnMatches ()

public TurnBasedMatchBuffer getTheirTurnMatches ()

If i could access these two methods (returning a list of TurnBasedMatch) that would be great. Or just do it via callback like the rest of the api ;) 

Thanks for your hard work.

Nikolas

**Comment by claywilkinson** [comment]
This is on the enhancement list - Which is tracked with #256

**Comment by claywilkinson** [comment]
This has been implemented in the version 0.9.25 of the plugin
