### ISSUE TITLE
Problems saving in OnApplicationQuit() or OnApplicationFocus(false)

### ISSUE THREAD

**Issue by rubenaster** [playgameservices/play-games-plugin-for-unity#620]
We need to save when our application gets pushed to the background or quits, which was possible with the Google Cloud API but the Google Saved Game API has problems with that.

I've already managed to save in OnApplicationFocus(false) by using a thread and uncommenting the following lines of code (which I guess exist for a reason):

conflictCallback = ToOnGameThread(conflictCallback);
completedCallback = ToOnGameThread(completedCallback);

But OnApplicationQuit still can't save and crashes.

As I said, saving when these callbacks are triggered worked with the Google Cloud API (and also with our own local savegame write) so it must be possible.

Any hints or suggestions?

**Comment by SrirachaSource** [comment]
+1 to this issue

**Comment by claywilkinson** [comment]
Closing as obsolete.  Please open a new issue.
