### ISSUE TITLE
Log In Fail iOS Unity Plugin

### ISSUE THREAD

**Issue by luismetmx** [playgameservices/play-games-plugin-for-unity#622]
ERROR_NOT_AUTHORIZED i used 0.9.20 version and unity 4.6.6

**Comment by claywilkinson** [comment]
Can you post the log?
Things to double check:
1. The clientID matches the client id of the linked iOS application in the play console.
2. The bundle ID matches the application ID

**Comment by luismetmx** [comment]
The Client ID of linked application is correct.
The ID bundle is correct.

this is the log:

 [Play Games Plugin DLL] 07/20/15 13:32:29 -05:00 DEBUG: Creating platform-specific Play Games client.
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
AchivementsBH:onLeaderBoard()
UnityEngine.Events.UnityAction:Invoke()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
UnityEngine.Events.InvokableCall:Invoke(Object[])
UnityEngine.DrivenRectTransformTracker:Clear()
UnityEngine.Events.InvokableCallList:Invoke(Object[])
UnityEngine.Events.UnityEventBase:Invoke(Object[])
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.UI.CanvasScaler:HandleConstantPhysicalSize()
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.TouchInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.TouchInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.TouchInputModule:Process()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
UnityEngine.EventSystems.EventSystem:Update()
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

 [Play Games Plugin DLL] 07/20/15 13:32:29 -05:00 DEBUG: Creating real IPlayGamesClient
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String)
GooglePlayGames.PlayGamesClientFactory:GetPlatformPlayGamesClient(PlayGamesClientConfiguration)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
AchivementsBH:onLeaderBoard()
UnityEngine.Events.UnityAction:Invoke()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
UnityEngine.Events.InvokableCall:Invoke(Object[])
UnityEngine.DrivenRectTransformTracker:Clear()
UnityEngine.Events.InvokableCallList:Invoke(Object[])
UnityEngine.Events.UnityEventBase:Invoke(Object[])
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.UI.CanvasScaler:HandleConstantPhysicalSize()
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.TouchInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.TouchInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.TouchInputModule:Process()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
UnityEngine.EventSystems.EventSystem:Update()
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

2015-07-20 13:32:29.982 lord[2236:585867] INFO: Auth operation started: SIGN IN
 [Play Games Plugin DLL] 07/20/15 13:32:29 -05:00 DEBUG: Entering state: BeforeRoomCreateStartedState
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String)
GooglePlayGames.Native.RoomSession:EnterState(State)
GooglePlayGames.Native.RoomSession:.ctor(RealtimeManager, RealTimeMultiplayerListener)
GooglePlayGames.Native.NativeRealtimeMultiplayerClient:GetTerminatedSession()
GooglePlayGames.Native.NativeRealtimeMultiplayerClient:.ctor(NativeClient, RealtimeManager)
GooglePlayGames.Native.NativeClient:InitializeGameServices()
GooglePlayGames.Native.NativeClient:Authenticate(Action`1, Boolean)
GooglePlayGames.Native.Cwrapper.ClaimMilestoneCallback:EndInvoke(IAsyncResult)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
AchivementsBH:onLeaderBoard()
UnityEngine.Events.UnityAction:Invoke()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
UnityEngine.Events.InvokableCall:Invoke(Object[])
UnityEngine.DrivenRectTransformTracker:Clear()
UnityEngine.Events.InvokableCallList:Invoke(Object[])
UnityEngine.Events.UnityEventBase:Invoke(Object[])
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.UI.CanvasScaler:HandleConstantPhysicalSize()
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.TouchInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.TouchInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.TouchInputModule:Process()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
UnityEngine.EventSystems.EventSystem:Update()
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

 [Play Games Plugin DLL] 07/20/15 13:32:29 -05:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String)
GooglePlayGames.Native.State:OnStateEntered()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
GooglePlayGames.Native.RoomSession:EnterState(State)
GooglePlayGames.Native.RoomSession:.ctor(RealtimeManager, RealTimeMultiplayerListener)
GooglePlayGames.Native.NativeRealtimeMultiplayerClient:GetTerminatedSession()
GooglePlayGames.Native.NativeRealtimeMultiplayerClient:.ctor(NativeClient, RealtimeManager)
GooglePlayGames.Native.NativeClient:InitializeGameServices()
GooglePlayGames.Native.NativeClient:Authenticate(Action`1, Boolean)
GooglePlayGames.Native.Cwrapper.ClaimMilestoneCallback:EndInvoke(IAsyncResult)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
AchivementsBH:onLeaderBoard()
UnityEngine.Events.UnityAction:Invoke()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
UnityEngine.Events.InvokableCall:Invoke(Object[])
UnityEngine.DrivenRectTransformTracker:Clear()
UnityEngine.Events.InvokableCallList:Invoke(Object[])
UnityEngine.Events.UnityEventBase:Invoke(Object[])
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.UI.CanvasScaler:HandleConstantPhysicalSize()
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.TouchInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.TouchInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.TouchInputModule:Process()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
UnityEngine.EventSystems.EventSystem:Update()
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

 [Play Games Plugin DLL] 07/20/15 13:32:29 -05:00 DEBUG: Entering state: ShutdownState
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String)
GooglePlayGames.Native.RoomSession:EnterState(State)
GooglePlayGames.Native.NativeRealtimeMultiplayerClient:GetTerminatedSession()
GooglePlayGames.Native.NativeRealtimeMultiplayerClient:.ctor(NativeClient, RealtimeManager)
GooglePlayGames.Native.NativeClient:InitializeGameServices()
GooglePlayGames.Native.NativeClient:Authenticate(Action`1, Boolean)
GooglePlayGames.Native.Cwrapper.ClaimMilestoneCallback:EndInvoke(IAsyncResult)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
AchivementsBH:onLeaderBoard()
UnityEngine.Events.UnityAction:Invoke()

Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
UnityEngine.Events.InvokableCall:Invoke(Object[])
UnityEngine.DrivenRectTransformTracker:Clear()
UnityEngine.Events.InvokableCallList:Invoke(Object[])
UnityEngine.Events.UnityEventBase:Invoke(Object[])
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.UI.CanvasScaler:HandleConstantPhysicalSize()
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.TouchInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.TouchInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.TouchInputModule:Process()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
UnityEngine.EventSystems.EventSystem:Update()
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

 [Play Games Plugin DLL] 07/20/15 13:32:29 -05:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String)
GooglePlayGames.Native.State:OnStateEntered()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
GooglePlayGames.Native.RoomSession:EnterState(State)
GooglePlayGames.Native.NativeRealtimeMultiplayerClient:GetTerminatedSession()
GooglePlayGames.Native.NativeRealtimeMultiplayerClient:.ctor(NativeClient, RealtimeManager)
GooglePlayGames.Native.NativeClient:InitializeGameServices()
GooglePlayGames.Native.NativeClient:Authenticate(Action`1, Boolean)
GooglePlayGames.Native.Cwrapper.ClaimMilestoneCallback:EndInvoke(IAsyncResult)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
AchivementsBH:onLeaderBoard()
UnityEngine.Events.UnityAction:Invoke()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
UnityEngine.Events.InvokableCall:Invoke(Object[])
UnityEngine.DrivenRectTransformTracker:Clear()
UnityEngine.Events.InvokableCallList:Invoke(Object[])
UnityEngine.Events.UnityEventBase:Invoke(Object[])
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.UI.CanvasScaler:HandleConstantPhysicalSize()
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.TouchInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.TouchInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.TouchInputModule:Process()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
UnityEngine.EventSystems.EventSystem:Update()
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

 [Play Games Plugin DLL] 07/20/15 13:32:30 -05:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

2015-07-20 13:32:30.016 lord[2236:585867] INFO: Auth operation started: SIGN IN
-> applicationWillResignActive()
-> applicationDidEnterBackground()
-> applicationWillEnterForeground()
2015-07-20 13:32:41.799 lord[2236:581947] [Debug] SOOMLA SoomlaGooglePlus: Successfully received the kUnityOnOpenURL notification!
2015-07-20 13:32:41.817 lord[2236:581947] [Debug] SOOMLA SoomlaGooglePlus: urlWasHandled: True
 [Play Games Plugin DLL] 07/20/15 13:32:42 -05:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

-> applicationDidBecomeActive()
 [Play Games Plugin DLL] 07/20/15 13:32:43 -05:00 DEBUG: Invoking user callback on game thread
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String)
GooglePlayGames.Native.<InvokeCallbackOnGameThread>c__AnonStorey9:<>m__F()
System.Action:Invoke()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
GooglePlayGames.OurUtils.PlayGamesHelperObject:<Update>m__3(Action)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

No se puede iniciar sesion
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
AchivementsBH:<onLeaderBoard>m__9C(Boolean)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
GooglePlayGames.Native.<InvokeCallbackOnGameThread>c__AnonStorey9:<>m__F()
System.Action:Invoke()
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
GooglePlayGames.OurUtils.PlayGamesHelperObject:<Update>m__3(Action)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
Soomla.Levelup.World:IdForAutoGeneratedMission(String, Int32)
GooglePlayGames.ReportProgress:EndInvoke(IAsyncResult)
GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

**Comment by claywilkinson** [comment]
There definitely is a configuration issue:
`[Play Games Plugin DLL] 07/20/15 13:32:30 -05:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED`

The user you are logging in as needs to be a tester as well.  Can you confirm that too?

**Comment by luismetmx** [comment]
Yes i Used the same account of google, on Android device Works

**Comment by luismetmx** [comment]
I'm still with the issue anyone knows about that??

**Comment by claywilkinson** [comment]
Does it switch over and present the consent screen, or does it fail before that?

I just tried the Minimal sample on both iOS and Android without issue. All  I can offer is to run Window > Google Play Games > Setup > IosSetup and make sure to copy and paste the bundle id and client ID from the iOS linked application in the play console.

**Comment by luismetmx** [comment]
Yes, the concert screen appears and when i return to the game the log shows the not authorized error the client id is correct

**Comment by claywilkinson** [comment]
Version 0.9.25 uses a new sign in SDK for iOS.  This should help eliminate some of the confusion on how to configure and run in iOS.
