### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by yuvalsegev11** [playgameservices/play-games-plugin-for-unity#623]
Trying to implement the authentication into my app, using the autheticate function as shown in the README,
and nothing is displayed, this is what i get in the console when calling Authenticate((bool success) => {});

'Received method call on DummyClient - using stub implementation.'

Here is my code:

	void Start () {

    PlayGamesPlatform.DebugLogEnabled = true;

    PlayGamesPlatform.Activate();

    Social.localUser.Authenticate((bool success) => {

        if(success){
            Social.Active.ShowLeaderboardUI();
        }

    });

Thanks for help

**Comment by vandie** [comment]
your executing from the editor right?
Don't. It won't work.
In order for it to work you have to use an android device to test. The unity editor has no Google account.

**Comment by yuvalsegev11** [comment]
Im testing it on my android device, not on the editor, and i can't get even the sign in pop up.

**Comment by vandie** [comment]
Interesting, I was having the same issue only I only got that particular message if I ran from the unity editor.

**Comment by jansoren** [comment]
I am having the same issue and using plugin version - GooglePlayGamesPlugin-0.9.21.unitypackage

**Comment by Kabum42** [comment]
Same here, it doesn't work for me even using an older build.

**Comment by yuvalsegev11** [comment]
Solved my problem, it seems that for some reason   sime plugin files were misssing, probably deleted by myself or by the editor.

Solved by importing the plugin again.
Everything works fine now.

**Comment by vandie** [comment]
May I ask which files where missing exactly?...

**Comment by bs207** [comment]
Doesn't work for me either... Any suggestions to a fix?

**Comment by yuvalsegev11** [comment]
GooglePlayGames/GameInfo.cs was missing

**Comment by bs207** [comment]
I get a bunch of errors when I port it in.

**Comment by claywilkinson** [comment]
It looks like this is resolved.  OK to close?
