### ISSUE TITLE
Self Participant ID is null when launching from Invitation Screen

### ISSUE THREAD

**Issue by Yecats** [playgameservices/play-games-plugin-for-unity#627]
I have a game that is launching from the invitation screen and when it goes to the listener it has no reference to the participants ID.  Code is:

       public void OnGotMatch(TurnBasedMatch match, bool shouldAutoLaunch)
        {
                    Debug.Log(" ********************* MATCH PARTICIPANT ID : " + match.SelfParticipantId + "  ********************* ");

//other stuff
         }

**Comment by claywilkinson** [comment]
Thanks for the issue - It looks like the callback is being called before the user has finished logging in so the player id is not set yet.  We're taking a look on how to fix it.

**Comment by Yecats** [comment]
Thanks!

**Comment by claywilkinson** [comment]
This is fixed in version 0.9.25
