### ISSUE TITLE
Wrong sort order of leaderboards and achievements

### ISSUE THREAD

**Issue by figfig** [playgameservices/play-games-plugin-for-unity#63]
Please see https://github.com/playgameservices/play-games-plugin-for-unity/issues/47 which is closed.

I've installed plugin 0.9.00 and SDK 2.0 for iOS. Please see point 4 in original post. This is still a problem. The leaderboards and achievements are not in the correct sort order. Thanks.

PS All my achievements are revealed and of same type. i.e. they're all the same and ordered 1...5 but listed as 1,4,2,5,3 on iphone 4s ios7 and ipad 4 ios7. Looks like its where android shows 2 columns being merged into 1 on ios...not sure.

**Comment by claywilkinson** [comment]
This is fixed.
