### ISSUE TITLE
How to compile for Android only?

### ISSUE THREAD

**Issue by wkwan** [playgameservices/play-games-plugin-for-unity#630]
I've got a mobile game where I'm using macros to implement this plugin for Android and GameCenter for iOS.

However, this plugin seems to break the iOS build ('GooglePlus/GooglePlus.h' file not found) and I don't want to add those frameworks it states in the text that pops up after the build since I'm not using it.

**Comment by claywilkinson** [comment]
See the README.MD file: https://github.com/playgameservices/play-games-plugin-for-unity#excluding-all-google-play-game-services-when-building-for-ios

**Comment by wkwan** [comment]
my bad, thanks
