### ISSUE TITLE
Turn based matches get Updated sporadically on some devices

### ISSUE THREAD

**Issue by KeySam** [playgameservices/play-games-plugin-for-unity#634]
Hi, maybe it is just a configuration error on my part but i am testing my game with 2 different mobile phones(playing turn based matches against each other). On one device everything seem to work fine in terms of speed and everything. On the other device i do not get an update for around 1 minute or something like this, afterwards i will have an updated status. 
Some information around everything. I am calling C.TurnBasedMultiplayerManager_FetchMatch to get an updated version of my match. I can also reproduce this behaviour by looking into the inbox (the match will not appear for around 1 minute). What seems to work is if i am taking a turn in another match, i will usualy have all updated data afterwards in my inbox. Can someone help me fix the problem, it is pretty mutch unusable if i am not getting relyable match data.

**Comment by KeySam** [comment]
why is this closed?

**Comment by claywilkinson** [comment]
For turn-based match notifications there is not really an SLA - I have seen it be both practically instantaneous and other times take a minute or so.   What versions are the phones running of Android and of Play Games and Play Services?

**Comment by KeySam** [comment]
I think i realised what the problem was (well maybe). I tried alot of things and now it seems to work fine, i think what it comes down to is that i turned synchronisation on in the android settings. I wanted to know if turning it off has an impact on the speed of google play games services? For now everything seems to work fine when i get the turn based matches.

**Comment by claywilkinson** [comment]
Yes, the synchronizing will affect the play game services.  So it is OK to close this?

**Comment by KeySam** [comment]
Yes its fine
