### ISSUE TITLE
sign in issue, the plugin doesn't sign in after account creation

### ISSUE THREAD

**Issue by GamePlayProgrammingIranGDI** [playgameservices/play-games-plugin-for-unity#636]
When I try to authenticate and don't have any accounts, thePlayGames offer me to create a new one or use an existing account, when I create the account the sign in always fails and then it should retry signing in again doing the whole process to make it work.

Is this something that you guys are aware of? Any upcoming fixes?

To reproduce
1- Add authentication code to a game
2- remove the existing accounts from the play games on your device.
3- Try to authenticate in the game
4- when asked in the google play games window try to link your account or create a new one.
5- after account creation the authentication fails and you need to press retry to be able to authenticate.

**Comment by claywilkinson** [comment]
Thanks for the issue!  This is a known issue (see #589).  We'll update that thread when it is addressed.

**Comment by claywilkinson** [comment]
This has been updated in the latest version of the plugin (0.9.25).
