### ISSUE TITLE
Authentication without internet connection doesn't always fail

### ISSUE THREAD

**Issue by GamePlayProgrammingIranGDI** [playgameservices/play-games-plugin-for-unity#637]
Sometimes when you disconnect the device from the internet and try to authenticate using the play games plugin, the authentication doesn't fail and it just hangs there.

Is there any fix?

To reproduce
1- disconnect the device from the net
2- try to authenticate, it doesn't always behave like that so please try a couple of times and you'll see that it hangs.

**Comment by claywilkinson** [comment]
There is a caching layer for the user login.  This helps with performance and with dealing with intermittent connectivity which is commonplace on mobile devices.  Is this a specific problem, or just unexpected behavior?
