### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by damondeng520** [playgameservices/play-games-plugin-for-unity#638]
the code 
<<
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;

...

PlayGamesPlatform.Activate();
Social.localUser.Authenticate((bool success) => {
});
>>

the log
<<
07-28 22:41:44.130: E/Volley(27382): [4081] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/games/v1/players/me?language=zh_CN
07-28 22:41:44.130: E/ErrorUtils(27382): Received generic error from server: 403
07-28 22:41:44.130: E/PlayerAgent(27382): Unable to load player 100308787168716420866
07-28 22:41:44.130: E/ErrorUtils(27382): Received generic error from server: 403
07-28 22:41:44.140: W/SignInActivity(1005): onSignInFailed()...
07-28 22:41:44.140: W/SignInActivity(1005): ==> Returning non-OK result: 10002
>>

**Comment by claywilkinson** [comment]
Is that player added as a tester to your game?

**Comment by damondeng520** [comment]
yes, I had added the tester account to my game.

**Comment by claywilkinson** [comment]
This still happening?  OK to close?
