### ISSUE TITLE
Error when Device with Android 5 (LolliPop) plays a Turnbased "QuickMatch" vs a device with 4.4(KitKat)

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#639]
This is very strange... I have no problem playing and finishing matches when the match started with an Invite or if booth devices are lollipop. However when a lollipop user joins a random match("quickmatch") started by a kitkat user my app freeze. When I then restart game and go in to the built in UI to see all matches and invites, I can see that its my turn (wich it should be) but my opponents name is just 4 random digits instead of the correct name (different digits every time a new match begins allthough same player). The standard default blue avatar is also different compared to an Invite-started game. Its green!?

Any ideas anyone?

**Comment by claywilkinson** [comment]
Closing since it has been a long time with no input.  If the freeze is still happening can you reopen with the log of what is happening when it freezes?  Thanks!
