### ISSUE TITLE
CommandInvokationFailure: Unable to merge android manifests. See the Console for more details.  java.exe -Xmx1024M

### ISSUE THREAD

**Issue by SaRaavan** [playgameservices/play-games-plugin-for-unity#64]
I got the following Error in Manifest like Unable to Merge Manifest When i try to Build for Android. But, The Sample Project Plugin Contains 3 Manifest files.

Android -> BaseGameUtils , 
Android -> google-play-services_lib,
Android -> MainLibProj,

Anyone Can Guide me What to do to solve this issue?
Error building Player: CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
java.exe -Xmx1024M -Dcom.android.sdkmanager.toolsdir="E:/Android SDK/android-sdk_r10-windows/android-sdk-windows\tools" -Dfile.encoding=UTF8 -jar "C:/Program Files (x86)/Unity 4.3.3/Editor/Data/BuildTargetTools/AndroidPlayer\sdktools.jar" -

stderr[]
stdout[Warning: [AndroidManifest-main.xml:13, AndroidManifest.xml:3] Main manifest has <uses-sdk android:targetSdkVersion='18'> but library uses targetSdkVersion='19']

**Comment by xuanchung** [comment]
I changed the all AndroidManifest.xml file but still error:

Error building Player: CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
C:\Program Files\Java\jdk1.7.0_09\bin\java.exe -Xmx1024M -Dcom.android.sdkmanager.toolsdir="D:/adt-bundle-windows-x86-20140702/sdk\tools" -Dfile.encoding=UTF8 -jar "C:/Program Files/Unity/Editor/Data/BuildTargetTools/AndroidPlayer\sdktools.jar" -

stderr[
Error: [Temp\StagingArea\AndroidManifest-main.xml:27, D:\Unity\Project\ChristmasGift\Temp\StagingArea\android-libraries\google-play-services_lib\AndroidManifest.xml:5] Trying to merge incompatible /manifest/application/meta-data[@name=com.google.android.gms.version] element:
  <meta-data
      @android:name="com.google.android.gms.version"
--    @android:value="4452000">
  <meta-data
      @android:name="com.google.android.gms.version"
++    @android:value="@integer/google_play_services_version">
Error: [Temp\StagingArea\AndroidManifest-main.xml:27, D:\Unity\Project\ChristmasGift\Temp\StagingArea\android-libraries\MainLibProj\AndroidManifest.xml:8] Trying to merge incompatible /manifest/application/meta-data[@name=com.google.android.gms.version] element:
  <meta-data
      @android:name="com.google.android.gms.version"
--    @android:value="4452000">
  <meta-data
      @android:name="com.google.android.gms.version"
++    @android:value="@integer/google_play_services_version">
]
stdout[
]

**Comment by claywilkinson** [comment]
I looks like you are trying to use a very old version of  com.google.android.gms.version - can you try to remove that metadata element from what you are trying to merge?
