### ISSUE TITLE
Authenitcation failed

### ISSUE THREAD

**Issue by A1234567890A** [playgameservices/play-games-plugin-for-unity#640]
Hi Clayton,

I have very carefully integrated the google play services with my game and followed all the procedure and got an AppID from google play service which i have set it up with my games, then i tried to authenticate by the following

Social.Active.localUser.Authenticate((bool success) => 
		{
		  // handle success or failure
	    	if(success)
		     {
		      Debug.Log("Welcome");
		    }
		     else
	         {
		      Debug.Log("Something went wrong");
			 
             }

	   });

It always prints  "something went wrong" and when i tried printing "Social.Active.localUser.ToString()", it tells GooglePlayerGames.PlayGamesLocalUser....

You asked me to test it on device and i did, i tried creating a message box to display the local user and still on devices it says
GooglePlayerGames.PlayGamesLocalUser....

**Comment by claywilkinson** [comment]
Can you post the log of when Authenticate is called?  Usually there is a log message that describes why it failed.

**Comment by A1234567890A** [comment]
Hi Clayton,
I hope you are looking for this in log file...............!!!!!!!!!!!!!!!!!!!!!!!



Achievement ID=====>CgkIuufx5scLEAIQAQ
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
LearderBoardAchievement:Start() (at Assets\_Scripts\LearderBoardAchievement.cs:54)
 
(Filename: Assets/_Scripts/LearderBoardAchievement.cs Line: 54)

 [Play Games Plugin DLL] 07/30/15 16:31:33 +05:30 DEBUG: Activating PlayGamesPlatform.
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets\GooglePlayGames\OurUtils\Logger.cs:58)
GooglePlayGames.PlayGamesPlatform:Activate() (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:228)
GameCenter1:activate() (at Assets\_Scripts\GameCenter1.cs:37)
GameCenter1:Start() (at Assets\_Scripts\GameCenter1.cs:19)
 
(Filename: Assets/GooglePlayGames/OurUtils/Logger.cs Line: 58)

 [Play Games Plugin DLL] 07/30/15 16:31:33 +05:30 DEBUG: Instance was not initialized, using default configuration.
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets\GooglePlayGames\OurUtils\Logger.cs:58)
GooglePlayGames.PlayGamesPlatform:get_Instance() (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:94)
GooglePlayGames.PlayGamesPlatform:Activate() (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:229)
GameCenter1:activate() (at Assets\_Scripts\GameCenter1.cs:37)
GameCenter1:Start() (at Assets\_Scripts\GameCenter1.cs:19)
 
(Filename: Assets/GooglePlayGames/OurUtils/Logger.cs Line: 58)

 [Play Games Plugin DLL] 07/30/15 16:31:33 +05:30 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets\GooglePlayGames\OurUtils\Logger.cs:58)
GooglePlayGames.PlayGamesPlatform:Activate() (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:230)
GameCenter1:activate() (at Assets\_Scripts\GameCenter1.cs:37)
GameCenter1:Start() (at Assets\_Scripts\GameCenter1.cs:19)
 
(Filename: Assets/GooglePlayGames/OurUtils/Logger.cs Line: 58)

 [Play Games Plugin DLL] 07/30/15 16:31:33 +05:30 DEBUG: Creating platform-specific Play Games client.
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets\GooglePlayGames\OurUtils\Logger.cs:58)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:296)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:271)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesLocalUser.cs:47)
GameCenter1:authen() (at Assets\_Scripts\GameCenter1.cs:52)
GameCenter1:Start() (at Assets\_Scripts\GameCenter1.cs:21)
 
(Filename: Assets/GooglePlayGames/OurUtils/Logger.cs Line: 58)

 [Play Games Plugin DLL] 07/30/15 16:31:33 +05:30 DEBUG: Creating IPlayGamesClient in editor, using DummyClient.
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets\GooglePlayGames\OurUtils\Logger.cs:58)
GooglePlayGames.PlayGamesClientFactory:GetPlatformPlayGamesClient(PlayGamesClientConfiguration) (at Assets\GooglePlayGames\Platforms\PlayGamesClientFactory.cs:30)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:297)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:271)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesLocalUser.cs:47)
GameCenter1:authen() (at Assets\_Scripts\GameCenter1.cs:52)
GameCenter1:Start() (at Assets\_Scripts\GameCenter1.cs:21)
 
(Filename: Assets/GooglePlayGames/OurUtils/Logger.cs Line: 58)

 [Play Games Plugin DLL] 07/30/15 16:31:33 +05:30 DEBUG: Received method call on DummyClient - using stub implementation.
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets\GooglePlayGames\OurUtils\Logger.cs:58)
GooglePlayGames.BasicApi.DummyClient:LogUsage() (at Assets\GooglePlayGames\BasicApi\DummyClient.cs:193)
GooglePlayGames.BasicApi.DummyClient:Authenticate(Action`1, Boolean) (at Assets\GooglePlayGames\BasicApi\DummyClient.cs:28)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:302)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:271)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesLocalUser.cs:47)
GameCenter1:authen() (at Assets\_Scripts\GameCenter1.cs:52)
GameCenter1:Start() (at Assets\_Scripts\GameCenter1.cs:21)
 
(Filename: Assets/GooglePlayGames/OurUtils/Logger.cs Line: 58)

Something went wrong
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GameCenter1:<authen>m__C6(Boolean) (at Assets\_Scripts\GameCenter1.cs:61)
GooglePlayGames.BasicApi.DummyClient:Authenticate(Action`1, Boolean) (at Assets\GooglePlayGames\BasicApi\DummyClient.cs:31)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:302)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:271)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesLocalUser.cs:47)
GameCenter1:authen() (at Assets\_Scripts\GameCenter1.cs:52)
GameCenter1:Start() (at Assets\_Scripts\GameCenter1.cs:21)
 
(Filename: Assets/_Scripts/GameCenter1.cs Line: 61)

 [Play Games Plugin DLL] 07/30/15 16:31:34 +05:30 DEBUG: Received method call on DummyClient - using stub implementation.
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets\GooglePlayGames\OurUtils\Logger.cs:58)
GooglePlayGames.BasicApi.DummyClient:LogUsage() (at Assets\GooglePlayGames\BasicApi\DummyClient.cs:193)
GooglePlayGames.BasicApi.DummyClient:IsAuthenticated() (at Assets\GooglePlayGames\BasicApi\DummyClient.cs:37)
GooglePlayGames.PlayGamesPlatform:IsAuthenticated() (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:325)
GooglePlayGames.PlayGamesLocalUser:get_authenticated() (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesLocalUser.cs:91)
GameCenter1:<authen>m__C6(Boolean) (at Assets\_Scripts\GameCenter1.cs:64)
GooglePlayGames.BasicApi.DummyClient:Authenticate(Action`1, Boolean) (at Assets\GooglePlayGames\BasicApi\DummyClient.cs:31)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:302)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:271)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesLocalUser.cs:47)
GameCenter1:authen() (at Assets\_Scripts\GameCenter1.cs:52)
GameCenter1:Start() (at Assets\_Scripts\GameCenter1.cs:21)
 
(Filename: Assets/GooglePlayGames/OurUtils/Logger.cs Line: 58)

Activated or Not====>False
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
GameCenter1:<authen>m__C6(Boolean) (at Assets\_Scripts\GameCenter1.cs:65)
GooglePlayGames.BasicApi.DummyClient:Authenticate(Action`1, Boolean) (at Assets\GooglePlayGames\BasicApi\DummyClient.cs:31)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:302)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:271)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at Assets\GooglePlayGames\ISocialPlatform\PlayGamesLocalUser.cs:47)
GameCenter1:authen() (at Assets\_Scripts\GameCenter1.cs:52)
GameCenter1:Start() (at Assets\_Scripts\GameCenter1.cs:21)
 
(Filename: Assets/_Scripts/GameCenter1.cs Line: 65)

**Comment by A1234567890A** [comment]
I have an another question when i run this app in my devices, i should be logged in with my tester account ...let say my gmail account  is that required......................
(i don't know whether i am asking a right question or not????)

**Comment by claywilkinson** [comment]
You are correct.  When you are running the game on the device, you should sign in with an account that is listed in the testers section on the Play Console.

**Comment by A1234567890A** [comment]
I did that clayton, my nexus is syn with my gmail account which happens to be added tester...my google play services are also updated.. i just don't now why it keep using the dummy user...when the game runs...one more thing i have in mind i have not used::
 
  PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
        // enables saving game progress.
        .EnableSavedGames()
        // registers a callback to handle game invitations received while the game is not running.
        .WithInvitationDelegate(<callback method>)
        // registers a callback for turn based match notifications received while the
        // game is not running.
        .WithMatchDelegate(<callback method>)
        .Build();

as i am not saving the games nor multiplayer...

**Comment by Dragonrage81** [comment]
I am also having trouble getting authentication to work, it fails to login every time. I get the little thing that comes up to select the account to use, but after that a spinning wheel pops of for a second, then goes away. This is the code I'm using for authentication.   
```
   // recommended for debugging:
	PlayGamesPlatform.DebugLogEnabled = true;
    // Activate the Google Play Games platform
    PlayGamesPlatform.Activate();
    Social.localUser.Authenticate(function (success: boolean) {
        // handle success or failure
        if(success){
        	Debug.Log("success");
        	CheckAchievements();
        }
        else	
        	Debug.Log("login failed");
       
    });
```
I have everything setup in the Google Development Console, and I'm using one of the emails i setup as a tester. I'm not using EnableSaveGames, as my game doesn't really need the functionality. I also went through the tutorial to configure the GooglePlayServices plugin, and checked to make sure all my SDKs are up to date. At this point I have no idea what's going wrong. Here are my adb logcat messages I got while logging in. Hope it helps and i hope I'm not making some stupid little mistake that's causing everything to break.
```
I/Unity   ( 8764):  
I/Unity   ( 8764): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 8764): 
I/Unity   ( 8764):  [Play Games Plugin DLL] 07/30/15 10:58:00 -07:00 DEBUG: Activating PlayGamesPlatform.
I/Unity   ( 8764):  
I/Unity   ( 8764): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 8764): 
I/Unity   ( 8764):  [Play Games Plugin DLL] 07/30/15 10:58:00 -07:00 DEBUG: Instance was not initialized, using default configuration.
I/Unity   ( 8764):  
I/Unity   ( 8764): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 8764): 
I/Unity   ( 8764):  [Play Games Plugin DLL] 07/30/15 10:58:00 -07:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
I/Unity   ( 8764):  
I/Unity   ( 8764): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 8764): 
I/Unity   ( 8764):  [Play Games Plugin DLL] 07/30/15 10:58:00 -07:00 DEBUG: Creating platform-specific Play Games client.
I/Unity   ( 8764):  
I/Unity   ( 8764): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 8764): 
I/Unity   ( 8764):  [Play Games Plugin DLL] 07/30/15 10:58:00 -07:00 DEBUG: Creating real IPlayGamesClient
I/Unity   ( 8764):  
I/Unity   ( 8764): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 8764): 
I/Unity   ( 8764):  [Play Games Plugin DLL] 07/30/15 10:58:00 -07:00 DEBUG: Entering state: BeforeRoomCreateStartedState
I/Unity   ( 8764):  
I/Unity   ( 8764): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 8764): 
I/Unity   ( 8764):  [Play Games Plugin DLL] 07/30/15 10:58:00 -07:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
I/Unity   ( 8764):  
I/Unity   ( 8764): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 8764): 
I/Unity   ( 8764):  [Play Games Plugin DLL] 07/30/15 10:58:00 -07:00 DEBUG: Entering state: ShutdownState
I/Unity   ( 8764):  
I/Unity   ( 8764): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 8764): 
I/Unity   ( 8764):  [Play Games Plugin DLL] 07/30/15 10:58:00 -07:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
I/Unity   ( 8764):  
I/Unity   ( 8764): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 8764): 
I/Unity   ( 8764):  [Play Games Plugin DLL] 07/30/15 10:58:00 -07:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   ( 8764):  
I/Unity   ( 8764): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 8764): 
I/Unity   ( 8764):  [Play Games Plugin DLL] 07/30/15 10:58:13 -07:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   ( 8764):  
I/Unity   ( 8764): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 8764): 
I/Unity   ( 8764):  [Play Games Plugin DLL] 07/30/15 10:58:13 -07:00 DEBUG: Invoking user callback on game thread
I/Unity   ( 8764):  
I/Unity   ( 8764): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 8764): 
I/Unity   ( 8764): login failed
I/Unity   ( 8764):  
I/Unity   ( 8764): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 8764): 
```

**Comment by sharpless512** [comment]
Login failed for some reason
    UnityEngine.Debug:Internal_Log(Int32, String, Object)
    UnityEngine.Debug:Log(Object)
    testGPGMenu:<OnGUI>m__C2(Boolean) (at     E:\Unity\Stronghold_Defender\Assets\Scripts\testGPGMenu.cs:95)
    GooglePlayGames.Native.<InvokeCallbackOnGameThread>c__AnonStoreyC`1:<>m__13() (at     E:\Unity\Stronghold_Defender\Assets\GooglePlayGames\Platforms\Native\NativeClient.cs:148)
    GooglePlayGames.OurUtils.PlayGamesHelperObject:<Update>m__4(Action) (at     E:\Unity\Stronghold_Defender\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:114)
    System.Collections.Generic.List`1:ForEach(Action`1) (at /Users/builduser/buildslave/mono-runtime-    and-classlibs/build/mcs/class/corlib/System.Collections.Generic/List.cs:361)
    GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at     E:\Unity\Stronghold_Defender\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:114)

**Comment by claywilkinson** [comment]
This message `Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED` means that something is not matching between the app configuration and the console configuration, or the player's account is not listed as a tester.  Things to double check:
1. the bundle id in Unity matches the app id in the linked application for the platform you are testing on (android or ios).
2. If it is android, the SHA1 fingerprint of the keystore you are signing the app with matches the fingerprint entered on the linked android app in the play game console.
3. If it is iOS, the client ID in the app matches the client ID displayed at the bottom of the iOS linked app information.
4. The player you are logging in as is listed in the testers section of the app.
5. Finally if all that is information is correct, Run Window > Google Play Games > Setup > Android (or iOS) Setup.

**Comment by Dragonrage81** [comment]
I just went through and checked that the bundle ID and the SHA1 fingerprint are matching. The SHA1 was off by one character, so I fixed that, however it still doesn't work. I tried running the setup and it told me that two files were missing. They were GameInfo.template and template-AndroidManifest.txt, so I copied the files and put them into the path listed and was able to run the setup, however it still isn't allowing me to log in on the test device. Does moving the plugin files to the Standard Assets folder so it can be referenced by a JS script mess things up for it?

**Comment by claywilkinson** [comment]
It will definitely mess up the editor and setup part of the scripts.  It should not mess up the runtime.

What is in the log when you can't login?

**Comment by Dragonrage81** [comment]
It's still saying not authorized.
```
I/Unity   (17271): 
I/Unity   (17271):  [Play Games Plugin DLL] 08/11/15 11:28:17 -07:00 DEBUG: Activating PlayGamesPlatform.
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
I/Unity   (17271):  [Play Games Plugin DLL] 08/11/15 11:28:17 -07:00 DEBUG: Instance was not initialized, using default configuration.
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
I/Unity   (17271):  [Play Games Plugin DLL] 08/11/15 11:28:17 -07:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
I/Unity   (17271):  [Play Games Plugin DLL] 08/11/15 11:28:17 -07:00 DEBUG: Creating platform-specific Play Games client.
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
I/Unity   (17271):  [Play Games Plugin DLL] 08/11/15 11:28:17 -07:00 DEBUG: Creating real IPlayGamesClient
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
I/Unity   (17271):  [Play Games Plugin DLL] 08/11/15 11:28:17 -07:00 DEBUG: Entering state: BeforeRoomCreateStartedState
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
I/Unity   (17271):  [Play Games Plugin DLL] 08/11/15 11:28:17 -07:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
I/Unity   (17271):  [Play Games Plugin DLL] 08/11/15 11:28:17 -07:00 DEBUG: Entering state: ShutdownState
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
I/Unity   (17271):  [Play Games Plugin DLL] 08/11/15 11:28:17 -07:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
I/Unity   (17271):  [Play Games Plugin DLL] 08/11/15 11:28:17 -07:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
I/Unity   (17271):  [Play Games Plugin DLL] 08/11/15 11:28:28 -07:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
I/Unity   (17271):  [Play Games Plugin DLL] 08/11/15 11:28:28 -07:00 DEBUG: Invoking user callback on game thread
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
I/Unity   (17271): login failed
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
I/Unity   (17271):  [Play Games Plugin DLL] 08/11/15 11:29:33 -07:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
I/Unity   (17271):  [Play Games Plugin DLL] 08/11/15 11:29:33 -07:00 DEBUG: Invoking user callback on game thread
I/Unity   (17271):  
I/Unity   (17271): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (17271): 
```

**Comment by Dragonrage81** [comment]
Yea i went through and triple checked the Google Dev console. The player is listed as a tester and the app id is correct and the SHA1 fingerprint is correct. I even rebuilt it and pushed a new apk after running setup again to see if it would work and I'm still getting the error_not_authorized sign_in status. Do i need to rewrite my entire app into C# to make it work?

**Comment by skyrace** [comment]
Hello

i have the same issue, and i check everything and it's seem ok. Do you find a solution ?

**Comment by banditdevelopment** [comment]
I assume when you build the apk for testing you are signing the file?

**Comment by skyrace** [comment]
yes, i signing the file.

**Comment by banditdevelopment** [comment]
So, just double checking, you have:
1setup android app in developer console
2added dev accounts
3signed app
4added same exact build identifier
5made sure that google play games says that it is "ready to test"

Right?

**Comment by skyrace** [comment]
Hello, thanks for your help, yes i have done it, i have also made some screenshot.

service game :
![01](https://cloud.githubusercontent.com/assets/14139680/9700378/e72557f6-5400-11e5-9dfe-409932d04f56.jpg)

in all applications :
![02](https://cloud.githubusercontent.com/assets/14139680/9700385/013ae2d2-5401-11e5-8436-0336aaaf3c85.jpg)

i have checked the signed key between apps uploaded, and local file :
![04](https://cloud.githubusercontent.com/assets/14139680/9700386/115eb738-5401-11e5-9cf9-3dbcd8b3a370.jpg)

if you have any idea ?

**Comment by skyrace** [comment]
when you say dev account, that's it  ? : 
(user to test)
![05](https://cloud.githubusercontent.com/assets/14139680/9700417/5ec6c65e-5402-11e5-893d-3d097452767e.jpg)

**Comment by banditdevelopment** [comment]
Yes, that is what i mean by dev account setup.

I got the same problem with Authorization failed, but signing the app fixed it.

Unfortunately I can't give you more info on the problem.  I'll review my steps and post them so you can see what I did to get sign in working.

**Comment by banditdevelopment** [comment]
@skyrace 
Here are all the steps I did before I was able to successfully sign in to GPGS on Android:
Use Windows 10
Use Unity 5.1
Use MonoDevelop C# for all GPGS related code
Use latest GPGS unity plugin version (Ver. 0.9.21)
Run App on Android 5.1.1
Setup GPGS through the Unity window
Create an app project (that was publishable) in the Google Play Dev Console
Create a GPGS project and link to app project
Build Unity project as signed .apk and manually install on device
Sign in to GPGS on device with approved test account

I know you've probably done all this, but it can't hurt to check.

Other than that, I can't help you much. Sorry.

**Comment by skyrace** [comment]
Hello

thanks for your answer, i follow all this step but in am on Windows 8 and unity 5.1.3f1 and GPSGS 0.9.21 and i use google play service v26 ? which version do you use ?

thanks 

regards

**Comment by banditdevelopment** [comment]
On my device I have Google Play Games version 3.2.17 and Google Play services version 7.8.99.

These version #s don't look like your #s at all. How did you find your Google Play service version #?

**Comment by skyrace** [comment]
Here :  

![07](https://cloud.githubusercontent.com/assets/14139680/9705591/962c7a7c-54c9-11e5-92fc-025b031bffad.jpg)


because when you go on windows -> google play games -> setup, some files are copied from the android sdk ?

**Comment by banditdevelopment** [comment]
Ah yes, I also have GPS version 26. I also have the complete Android API 22 and 23 installed in the Android SDK, although I'm not sure that matters. Might be worth a shot to try.

**Comment by skyrace** [comment]
my apps stats is "draft" because it isn't published, this could be the pb ?

**Comment by banditdevelopment** [comment]
My app that I am using GPGS in is also unpublished, however it is ready to publish:
![untitled](https://cloud.githubusercontent.com/assets/10777503/9705636/2d45b6f2-5499-11e5-944a-ef3c4b652345.png)
In the Dev Console does it say that your app is "ready to publish"?

**Comment by skyrace** [comment]
thanks, i made change for my apps to be "ready to publish" but still don't working :(

**Comment by banditdevelopment** [comment]
Hmm, not sure what else could be wrong. What Android version are you testing on, and is the Google Play Games app installed? (I'm kind of guessing at this point.)

**Comment by Virdari** [comment]
hey @skyrace take a look at this:
1) https://console.developers.google.com/project/YOURPROJECTID/apiui/credential
2) Check if you have SHA-1 Fingerprint set there. My textfield was empty too. Just manually entered it and Immediately after that tested my authorization and now I'm in ! :)

On the other hand this means that linking the app on google play stores developer console is broken and doesn't somehow add the SHA-1 to the credentials page on the backend console. Google fix pls.

**Comment by skyrace** [comment]
many many many Thanks, that's it !!! ^^

**Comment by claywilkinson** [comment]
Glad you got it working!  I want to make sure I understand the issue.  Is the issue that if you go to 
https://console.developers.google.com/project and modify your application, the changes are not picked up?

If so, this is a quirk of how the game services work. To modify the applications for a game, you need to go to https://play.google.com/apps/publish, then select your game configuration, then 'linked apps' and then edit from there.

I'll pass along that this was a total pain for everyone, but also feel free to send feedback on https://console.developers.google.com/project (click on the feedback icon at the top right).

**Comment by skyrace** [comment]
Hello
yes i go here : https://console.developers.google.com/project and modify my apps, and manually add sha key and now it is ok.

**Comment by manwithsteelnerves** [comment]
Taken from [Cross Platform Native Plugins](http://u3d.as/1szE)
But, the info here is very general and works with any plugins.

## Why sign in fails? 

For Google Play Services to sign in successfully, you need to make sure the apk from where you are logging in should be allowed to make requests to google servers.

## How to make the APK authorized to make requests to google servers?

Each apk built with a keystore has a SHA fingerprint. You need to make sure the SHA fingerprint is added in the google cloud.

You can fetch it with keytool command (check [here](https://assetstore.essentialkit.voxelbusters.com/game-services/faq#what-are-different-sha-fingerprints-that-needs-to-be-used-for-logging-in-successfully-on-different-environments-and-how-to-create-them) on how to get SHA for each environment )

## How many SHA fingerprints I need to add for successful authentication?
One per each environment. In total 3 environments (dev, release and production)
1. Development build uses android default debug keystore.

2. Release build uses the keystore you set in publishing settings of player settings

3. Google play store build which uses google play signing.

If you want all the above builds to authenticate successfully, add all 3 fingerprints. Else only the required environment.

## How to get each environment's SHA?

1. Debug ( keytool -list -v -keystore "PATH_TO_DEBUG_KEYSTORE" -alias androiddebugkey -storepass android -keypass android)

2. Release (Get from Google play console -> Your App -> Setup -> App signing -> Upload key certificate )

3. Apk/AAb downloaded from Google play store (Get from Google play console -> Your App -> Setup -> App signing -> App signing key certificate )

## Where to add these SHA fingerprints?
Google Play Console. Check [here](https://assetstore.essentialkit.voxelbusters.com/game-services/setup/android#adding-a-sha-fingerprint) for details on how to add a SHA fingerprint.
