### ISSUE TITLE
Crash on startup ? (iPod 4)

### ISSUE THREAD

**Issue by narger17** [playgameservices/play-games-plugin-for-unity#644]
Hi guys i've created a build of my game for Xcode and i launched it on my iPad wifi, it worked.
But on my iPod it crashes and gives me this message:

dyld: Symbol not found: _CTRadioAccessTechnologyWCDMA

  Referenced from: /var/mobile/Applications/2B3384A7-7733-4336-8269-5CFB76459017/novepeernove.app/novepeernove

  Expected in: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony

 in /var/mobile/Applications/2B3384A7-7733-4336-8269-5CFB76459017/novepeernove.app/novepeernove

(lldb) 

It's related to core telephony framework i think, but the iPad doesn't have any sim but it can launch the game without problems ! Thank you for your help

**Comment by claywilkinson** [comment]
You might want to ask this question to a wider audience - it does not sound specific to the GPG plugin, but more specific to CoreTelephony.  Maybe try stackoverflow?

**Comment by banditdevelopment** [comment]
I can verify that a Unity project that ran fine on iPod 4 now crashes on startup when GPGS are included.

I'm not sure that the Core.Telephony framework is the cause, I could not find any info pertaining to Core.Telephony causing crashing on iPod 4.

Maybe this is caused by building with Cocoapods?

**Comment by claywilkinson** [comment]
Can you post a log of the crash?

**Comment by KimBurrows** [comment]
Hi all, I just tried adding this plugin to our game and running on an iPad 2.  We're getting the same problem.  Any thoughts on how to debug it?  The only debug output we get is:

dyld: Symbol not found: _CTRadioAccessTechnologyWCDMA
  Referenced from: /var/mobile/Applications/B243B511-7F10-4DFE-B8AF-45AFB2E08819/tanks.app/tanks
  Expected in: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 in /var/mobile/Applications/B243B511-7F10-4DFE-B8AF-45AFB2E08819/tanks.app/tanks
(lldb)
