### ISSUE TITLE
GPG logs out automatically if there is no Internet

### ISSUE THREAD

**Issue by fundoozzz** [playgameservices/play-games-plugin-for-unity#645]
I have implemented this plugin and on first run, it signs it just fine. Soon after that if I quit the game and start again without data connection, it gets authenticated without any issue.
If my data connection remains off for say more than an hour, and I start the game without Internet connection, there is no authentication whatsoever. If i close the game and start again soon after that, it gives me that google play games sign in popup. So what i can conclude is that it signs out automatically after some time if there is no Internet available. Is there any fix for this.?
Thanks

**Comment by claywilkinson** [comment]
Yes, the play game services require a connection to the server to perform most operations (Nearby connections is the only exception).  If you want to continue to play offline, then you need to make sure the play game services calls can be safely bypassed if Social.IsAuthenticated is false.

**Comment by fundoozzz** [comment]
@claywilkinson  Is there a way to save data locally to the cache when the internet is unavailable or even if the user has been signed out and then sync data once he signs in again?
I am using your AutoSave sample and I end the Loading screen once the ReadValueFromBytes() method is executed.But in case the user signs out, my game is stuck at loading screen forever.

**Comment by simgesimulation** [comment]
@fundoozzz Can you give me a link about "AutoSave"? I wonder what you mean by saying autosave. I want to save my game atomatically at the end. I wonder is it what I want.

**Comment by VladimirKuznetsov** [comment]
@simgesimulation I think that's what you're looking for: https://github.com/claywilkinson/AutoSaveUnitySample/blob/master/Assets/AutoSave.cs
@claywilkinson is internet connection required for saving games? I expect game to be saved in cache in this case. Am I wrong?

**Comment by claywilkinson** [comment]
OK to close this one?  On Android there is caching of the saved game data, so you are correct.  On iOS, I don't believe the caching is there for Saved Games, but I need to double check.
