### ISSUE TITLE
Cannot enable Saved Games?

### ISSUE THREAD

**Issue by narger17** [playgameservices/play-games-plugin-for-unity#646]
Hi guys i've got a problem with cloud save: i've enabled it from developer console, this is my initialization code:

PlayGamesPlatform.Activate ();
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
			.EnableSavedGames()
		        .Build();
PlayGamesPlatform.InitializeInstance(config);

and then when i touch the button this is the code:

if (touched)
ShowSelectUI();

void ShowSelectUI() {
		uint maxNumToDisplay = 5;
		bool allowCreateNew = false;
		bool allowDelete = true;
		ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame;
		savedGameClient.ShowSelectSavedGameUI("Select saved game",
		                                      maxNumToDisplay,
		                                      allowCreateNew,
		                                      allowDelete,
		                                      OnSavedGameSelected);
	}
	public void OnSavedGameSelected (SelectUIStatus status, ISavedGameMetadata game) {
		if (status == SelectUIStatus.SavedGameSelected) {
			Debug.Log("Selezionato");
		} else {
			Debug.Log ("Errore");
		}
	}

But when i touch it from logcat i can read this error:
NotImplementedException: You must enable saved games before it can be used.

What's wrong? Thank you

**Comment by claywilkinson** [comment]
Are you authenticating successfully? Can you post the log?

**Comment by narger17** [comment]
The log doesnt help: it's all perfect: leaderboards, achievments... The
error in the first post comes when i touch the "Load" button
Il 04/ago/2015 22:46, "Clayton Wilkinson" <notifications@github.com> ha
scritto:

**Comment by narger17** [comment]
V/GamesNativeSDK( 1695): Detaching from JVM on thread main_dispatch
I/Unity   ( 1695): NotImplementedException: You must enable saved games before i
t can be used. See PlayGamesClientConfiguration.Builder.EnableSavedGames.
I/Unity   ( 1695):   at GooglePlayGames.Native.UnsupportedSavedGamesClient.ShowS
electSavedGameUI (System.String uiTitle, UInt32 maxDisplayedSavedGames, Boolean
showCreateSaveUI, Boolean showDeleteSaveUI, System.Action`2 callback) [0x00000]
in <filename unknown>:0
I/Unity   ( 1695):   at GestioneSalvataggiGPG.ShowSelectUI () [0x00000] in <file
name unknown>:0
I/Unity   ( 1695):   at GestioneSalvataggiGPG.Update () [0x00000] in <filename u
nknown>:0
I/Unity   ( 1695):
I/Unity   ( 1695): (Filename:  Line: -1)
I/Unity   ( 1695):
V/GamesNativeSDK( 1695): Detaching from JVM on thread main_dispatch
I/Unity   ( 1695): NotImplementedException: You must enable saved games before i
t can be used. See PlayGamesClientConfiguration.Builder.EnableSavedGames.
I/Unity   ( 1695):   at GooglePlayGames.Native.UnsupportedSavedGamesClient.ShowS
electSavedGameUI (System.String uiTitle, UInt32 maxDisplayedSavedGames, Boolean
showCreateSaveUI, Boolean showDeleteSaveUI, System.Action`2 callback) [0x00000]
in <filename unknown>:0
I/Unity   ( 1695):   at GestioneSalvataggiGPG.ShowSelectUI () [0x00000] in <file
name unknown>:0
I/Unity   ( 1695):   at GestioneSalvataggiGPG.Update () [0x00000] in <filename u
nknown>:0
I/Unity   ( 1695):
I/Unity   ( 1695): (Filename:  Line: -1)
I/Unity   ( 1695):

**Comment by claywilkinson** [comment]
Hmm. I looked at your code again.  Can you try to call `PlayGamesPlatform.Activate ();` after your initialize?

**Comment by narger17** [comment]
Trying right now ;) Thanks

**Comment by narger17** [comment]
WTF... now i've got this in log:

button touched ->

I/Unity   ( 4797): Error
I/Unity   ( 4797):
I/Unity   ( 4797): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bug.gen.cpp Line: 56)

**Comment by claywilkinson** [comment]
Great!!! Glad to hear it :+1:

**Comment by hippogamesunity** [comment]
My environment is iOS + native leaderboards & achievements + gpgs cloud

I build configuration with saved games and the are enabled from developer console.
I don't call PlayGamesPlatform.Activate(); as describetd in [(Advanced) Using the Plugin Without Overriding the Default Social Platform].

So my steps are:

var config = new PlayGamesClientConfiguration.Builder().EnableSavedGames().Build();
PlayGamesPlatform.InitializeInstance(config);
PlayGamesPlatform.DebugLogEnabled = true;
