### ISSUE TITLE
Android setup does not work

### ISSUE THREAD

**Issue by Qbit86** [playgameservices/play-games-plugin-for-unity#649]
Error: file not found: ...template-GameInfo.txt.

Indeed, because it is named GameInfo.template, and recent commit has broken path to be found in `UpdateGameInfo()` method.

Cannot upgrade from 0.9.20 for a couple of weeks, plugin is completely unstable and barely tested on Unity 4.6/5.1 for Android/iOS in setup/update scenarios.

Is it maintained by Google?

**Comment by MrTactic** [comment]
I have this problem too

**Comment by Qbit86** [comment]
I'm afraid, you will have another compile time problems when you're done setting up: `GooglePlayGames.GameInfo does not contain a definition for...`

**Comment by claywilkinson** [comment]
Thanks for the feedback. Looks like I missed a couple files. I'll rebuild the unitypackage today. The corrected GameInfo.cs can be copied from https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/GameInfo.cs

The Template is at https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Editor/template-GameInfo.txt

**Comment by claywilkinson** [comment]
I have refreshed the unity package to correct this issue.  Please download it again.

**Comment by Qbit86** [comment]
Thanks, I've reimported it.

Cannot confirm that setup works, because I only replaced changed files; saving project settings that were previously done. But compilation errors have gone; no regression in our game observed so far.
