### ISSUE TITLE
Google play services not working with IL2CPP build

### ISSUE THREAD

**Issue by prakashangappan** [playgameservices/play-games-plugin-for-unity#650]
Hi, when we build xcode project with il2cpp from unity, google play games doesn't work. We were using unity 4.6.2f1, everything was working fine. But we had to change this "mono" to "IL2CPP" for making 64 bit ios build, then google play games stopped working. As unity guy mentioned in this thread,

http://forum.unity3d.com/threads/il2cpp-exe-error.311499/

We have updated unity to 4.6.3p3. Still google play services not working and when we checked the debug messages, it was throwing "Exception Google Login: Object contains non-primitive or non-blittable data". 

If any one has fixed this issue or know any work around, please share.

Thanks in advance.

**Comment by claywilkinson** [comment]
Does this happen with the samples?  or can you provide a sample that has this problem?  I know all the samples build with IL2CPP, but I checked with Unity 5.

**Comment by claywilkinson** [comment]
I did a quick survey of the various builds of Unity - I strongly recommend using at least version 4.6.8 - earlier versions have various bugs.

**Comment by prakashangappan** [comment]
Sorry for the late response. Its working fine now. Thanks a lot!
