### ISSUE TITLE
Google Play Service Rev25 not working

### ISSUE THREAD

**Issue by liszto** [playgameservices/play-games-plugin-for-unity#651]
When I try to use your plugin for unity with the "Google Play Service" in Rev25 I can't do anything.

I just try to authenticate and nothing happens.

I use Unity 4.6.5f1 and all was working before this update.

Any informations about this ?

**Comment by claywilkinson** [comment]
Can you post a log of what is happening when authenticating?  Also, when you update, sometimes re-running Setup (Window > Google Play Games > Setup > Android Setup...) will help.

**Comment by liszto** [comment]
We currently used our custom builder, so we didn't use your editor script.
When I try to login nothing seems to happen.
I will try to have more information when I authenticate to see what happen. More informations soon. If you need other things or informations don't hesitate.

**Comment by claywilkinson** [comment]
OK - FYI you can hook into the setup script from your builder by calling public static GPGSAndroidSetupUI.PerformSetup().

**Comment by liszto** [comment]
We use :
Social.localUser.Authenticate( ( bool success )
to login and this wait something like 30 sec then timeout (i think) so success value is false.

**Comment by claywilkinson** [comment]
Please re-open if this is still an issue.
