### ISSUE TITLE
Error in Xcode project when using NO_GPGS

### ISSUE THREAD

**Issue by danko42** [playgameservices/play-games-plugin-for-unity#652]
Hello!
I want to disable the Google Play Game Services in the iOS build. But when I use NO_GPGS I get the following error in Xcode project:
```
GTMOAuth2Authentication.h file not found
```

Plugin version 0.9.21
Unity version 5.1.2
Xcode version 6.4 (6E35b)

![screenshot_5](https://cloud.githubusercontent.com/assets/13661913/9088950/67cce078-3b9b-11e5-9d49-d2d98f7014f1.png)

**Comment by claywilkinson** [comment]
Yep, that is a new file just added and it was missed in the NO_GPGS processing.  I'll add it shortly.  In the mean time, you can just delete that file from the xcode project.

**Comment by kreso22** [comment]
To make this a bit more clear and potentially save someone else 15 minutes:

Location & name of the file to delete: /XCodeProject/Libraries/Plugins/iOS/CustomWebViewApplication.mm

**Comment by DavidSotir** [comment]
@claywilkinson have you been able to change that? I use Cloud build for most of my building and you cant remove specific files from cloud build sadly.

**Comment by DavidSotir** [comment]
@kreso22 I deleted that file and am now getting an error of "no such file exists" point to the CustomWebViewApplication file i just deleted.

**Comment by kreso22** [comment]
Hey David,
Did you remove it through xCode (and have it remove the reference)?

**Comment by DavidSotir** [comment]
Just found that. Thanks!

**Comment by kreso22** [comment]
@claywilkinson could you share a solution (code?) so we don't have to remove the file every time when building a project?
It happens that I need to re-create the project every time (and remove this file manually every time).
Thanks!

**Comment by kamend** [comment]
Any fix for this, we are using unity cloud build, so manually deleting it is not an option.

**Comment by claywilkinson** [comment]
I haven't had a chance to get to this. You can try to delete it from the Unity project - the file is in the Assets/Plugins/iOS directory.  This way it will not be added to the Xcode project?

**Comment by kamend** [comment]
Fixed, I though I had to delete it from the Xcode project. Deleting it from Unity is the solution.

**Comment by claywilkinson** [comment]
Fixed in 0.9.25
