### ISSUE TITLE
No notifications when inviting friends on iOS

### ISSUE THREAD

**Issue by ZenithCode** [playgameservices/play-games-plugin-for-unity#653]
@claywilkinson 

In my game we can invite players to join a room. It works fine on Androids but I don't get notifications on iOS.  

I've also noticed that the app never asks for 'Push notifications' permission - Is this normal?
If I open 'Inbox' I see the invitations right there.

Any ideas what could be wrong?
Thanks.

**Comment by ZenithCode** [comment]
I'm always getting this error on the Google dev page and I'm  100% sure the bundle ids are the right ones.
<img width="613" alt="google bundle problem" src="https://cloud.githubusercontent.com/assets/1938034/9093588/321e3276-3bad-11e5-9a5a-eae95bc97d3a.png">

Anyone else has this issue?

**Comment by claywilkinson** [comment]
You can check the bundle in the cert with 
`openssl pkcs12 -info -in cert.p12`

Also check that in your app controller you are calling 
registerUserNotificationSettings  which should result in a call to didRegisterForRemoteNotificationsWithDeviceToken or didFailToRegisterForRemoteNotificationsWithError

**Comment by ZenithCode** [comment]
OK fixed.
