### ISSUE TITLE
iOS: Pods-Unity-iPhone was rejected as an implicit dependency for 'libPods-Unity-iPhone.a' because its SDK is platform 'com.apple.platform.iphonesimulator' and it needs to match platform 'com.apple.platform.iphoneos'

### ISSUE THREAD

**Issue by seaders** [playgameservices/play-games-plugin-for-unity#654]
Really no idea what's gone wrong, but on our build machine, a Mac Mini, we get this error when we try to build the .ipa in XCode.  Obviously with that error, the rest of the code / build is missing a million things.

I'm seeing very little info from this error via Googling, mainly some things to do with trying to build for the Apple Watch.  Big enough blocker for us right now, and no real idea how to fix it.  If I delete libPods-Unity-iPhone.a and rebuild, it's just the same problem again.  Unfortunately, while the CocoaPods setup makes the iOS process a million times easier, we know nearly no nothing about it's setup so it's very difficult to fix ourselves.

Some help on this would be greatly appreciated.

**Comment by claywilkinson** [comment]
I'll look into this.  On the surface it sounds like the project file for the Pod is configured for the simulator and the game is configured for the device?  Do you run pod update during each build, or only once and then checkin the result?

Since you are talking about a build machine, I am presuming you can build the project successfully on a developer box?

**Comment by seaders** [comment]
Yeah, fine on our dev machines.  I got some progress done on this yesterday, and am going to be going back to it this evening, so if you want to wait, I think I may be able to figure it out.

I actually sorted out this exact problem, the building for iphonesimulator.  Unfortunately, I can't remember the exact steps that I tried, but I think it was a case of your README info, fully delete a few thing, fully re-setup a few things, and then build again.  That only sorted that exact thing, but the other Pod stuff is still broken.

I've got what's to blame slimmed down to somehow the Pod configurations not coming in for the main project.  They show up in the project, everything *seems* to be set up properly, but unfortunately when the build happens, it doesn't pull in the Pods linkage config, when the build fail, there's no `-framework gpg` reference at all, so the linkages to any of the functions in there fail.

**Comment by claywilkinson** [comment]
OK to close this? I've tried several builds and scenarios on the desktop and everything is working OK.  We have one CI build that is working as well.

**Comment by wangjoshuah** [comment]
As a followup, I experienced this today when using OHHTTPStubs in the test target of my project. The resolution was that I needed to change some settings in my Target -> Build Settings. The Base SDK and supported platforms needed to be set to iOS, and Build Active Architecture Only needed to be set to Yes.
