### ISSUE TITLE
Problem on SendConnectionRequest Nearby

### ISSUE THREAD

**Issue by AmelieBF** [playgameservices/play-games-plugin-for-unity#657]
When I try to join a room (which is advertising), the discovering device find the room but can't connect to it. These messages are log:

08-13 11:17:26.114: I/NearbyApp(6085): Couldn't find address for instance 851C15C8
08-13 11:17:26.114: I/NearbyApp(6085): Failed to send connection request to 851C15C8
08-13 11:17:26.114: V/GamesNativeSDK(7421): SendConnectionRequestOperation completed successfully.
08-13 11:17:26.114: V/GamesNativeSDK(7421): Received a Nearby Connection Response.
08-13 11:17:26.122: I/Unity(7421): [C-Nearby] Response of the Room: ErrorEndpointNotConnected

Thanks for your help!

**Comment by AmelieBF** [comment]
I solved the problem.
I inversted th endpointId and the DeviceID when in the connection request.
(For help: I noticed that the endpointID begins with the characters of the deviceID)

**Comment by claywilkinson** [comment]
Glad you resolved it!  The device ID is more like a hostname and the endpointID is a port.  Devices can have multiple endpoints.  I am very interested in your experiences with Nearby.  Keep us posted :)

**Comment by AmelieBF** [comment]
Hi ClayWilkinson,
I would like to know if the nearby plugin will be available for iOS in the future. Because we are also creating games for iOS and we would like to integrate the nearby...

Thanks
