### ISSUE TITLE
best practice for a standby screen during authentication

### ISSUE THREAD

**Issue by CarlGammaSagan** [playgameservices/play-games-plugin-for-unity#658]
What is the best practice for implementing a standby screen during the authentication process as noted in the readme.md? I cannot seem to find any documentation/previous questions about this.

"Note that you cannot make any games API calls (unlock achievements, post scores, etc) until you get a successful return value from Authenticate, so it is good practice to put up a standby screen until the callback is called, to make sure the user can't start playing the game until the authentication process completes."

**Comment by claywilkinson** [comment]
Closing since it is an old thread.  This type of question is not specific to the plugin, and better suited for asking on StackOverflow where it will been seen by a wider audience.
