### ISSUE TITLE
0 XP points for an achievement - iOS - Unity

### ISSUE THREAD

**Issue by prakashangappan** [playgameservices/play-games-plugin-for-unity#660]
We have five achievements in our game, only one achievement showing it as 0 XP points. Any one has any idea why?.

Using, Unity4.6.7 and GPGS 0.9.21

**Comment by claywilkinson** [comment]
If the game is not published in the Play Console, the XP will show as 0.

**Comment by claywilkinson** [comment]
Closing - please reopen if you still have questions.
