### ISSUE TITLE
Cloud Save/Load in Background

### ISSUE THREAD

**Issue by simgesimulation** [playgameservices/play-games-plugin-for-unity#661]
Hİ All
I want to save and load my game data in background without any UI shown. How can I achieve this? Any link or any example about this?
Thanks...

**Comment by claywilkinson** [comment]
The [CubicPilot](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/samples/CubicPilot/Source/Assets/CubicPilot/GameLogic/GameManager.cs#L157) sample performs autosave.
