### ISSUE TITLE
Crash application after SignIn immediately

### ISSUE THREAD

**Issue by devmae** [playgameservices/play-games-plugin-for-unity#663]
This bug has also occurred in the same sample CubicPilot provided by you.

CubicPilot log.
==================================================================

08-16 10:49:55.189: I/Unity(5615): gles_mode = 0 (integer)
08-16 10:49:55.189: I/Unity(5615): splash_mode = 0 (integer)
08-16 10:49:55.189: I/Unity(5615): hide_status_bar = True (bool)
08-16 10:49:55.189: I/Unity(5615): useObb = False (bool)
08-16 10:49:55.189: I/Unity(5615): development_player = True (bool)
08-16 10:49:55.224: D/Unity(5615): surfaces: attach glview
08-16 10:49:55.234: I/Unity(5615): Choreographer available: Enabling VSYNC timing
08-16 10:49:55.244: I/Unity(5615): onResume
08-16 10:49:55.289: D/Unity(5615): [EGL] Attaching window 0:0x40036410
08-16 10:49:55.289: D/Unity(5615): [EGL] Attaching window 0:0x40036410
08-16 10:49:55.324: I/Unity(5615): windowFocusChanged: true
08-16 10:49:55.334: D/Unity(5615): SystemInfo CPU = ARMv7 VFPv3 NEON, Cores = 4, Memory = 1786mb
08-16 10:49:56.044: D/Unity(5615): [SHA1] 3ff7503a78fcac2490987029e36e4b2e073ac995   21277297 bytes ~ lib/armeabi-v7a/libunity.so
08-16 10:49:56.804: D/Unity(5615): [SHA1] b8b83e7178db9d2ada4ce473ec7d1ae70241cee1   24691941 bytes ~ lib/x86/libunity.so
08-16 10:49:56.809: D/Unity(5615): Mono path[0] = '/data/app/hl.CupicPilot-1.apk/assets/bin/Data/Managed'
08-16 10:49:56.809: D/Unity(5615): Mono config path = 'assets/bin/Data/Managed'
08-16 10:49:56.809: D/Unity(5615): PlayerConnection initialized from /data/app/hl.CupicPilot-1.apk/assets/bin/Data (debug = 0)
08-16 10:49:56.809: D/Unity(5615): PlayerConnection initialized network socket : 0.0.0.0 55355
08-16 10:49:56.809: D/Unity(5615): PlayerConnection initialized unix socket : Unity-hl.CupicPilot
08-16 10:49:56.809: D/Unity(5615): Multi-casting "[IP] 192.168.200.109 [Port] 55355 [Flags] 3 [Guid] 3083793249 [EditorId] 637002504 [Version] 1048832 [Id] AndroidPlayer(samsung_SHV-E210S@192.168.200.109) [Debug] 1" to [225.0.0.222:54997]...
08-16 10:49:56.809: D/Unity(5615): Waiting for connection from host on [192.168.200.109:55355]...
08-16 10:49:57.264: D/Unity(5615): PlayerConnection accepted from [192.168.200.100] handle:0x3a
08-16 10:49:57.319: D/Unity(5615): Using monoOptions --debugger-agent=transport=dt_socket,embedding=1,defer=y,address=0.0.0.0:56249
08-16 10:49:57.484: D/Unity(5615): InitializeMonoFromMain OK (526d5ee0)
08-16 10:49:57.484: D/Unity(5615): PlayerConnection already initialized - listening to [192.168.200.109:55355]
08-16 10:49:57.504: D/Unity(5615): PlayerInitEngineNoGraphics OK
08-16 10:49:57.539: D/Unity(5615): [EGL] Request: ES3 RGB0 000 0/0
08-16 10:49:57.539: E/Unity(5615): [EGL] eglChooseConfig(m_EGLDisplay, configAttribs, NULL, 0, &eglConfigCount): EGL_BAD_ATTRIBUTE: An unrecognized attribute or attribute value was passed in the attribute list.
08-16 10:49:57.539: E/Unity(5615):  
08-16 10:49:57.539: E/Unity(5615): (Filename: ./Runtime/GfxDevice/egl/ConfigEGL.cpp Line: 222)
08-16 10:49:57.539: D/Unity(5615): [EGL] Request: ES2 RGB0 000 0/0
08-16 10:49:57.539: D/Unity(5615): [EGL] Selected: ID[29] ES2 RGB16 565 0/0
08-16 10:49:57.539: D/Unity(5615): [EGL] Request: ES2 RGBA32 8888 0/0
08-16 10:49:57.539: D/Unity(5615): [EGL] Selected: ID[30] ES2 RGBA32 8888 0/0
08-16 10:49:57.594: D/Unity(5615): ANativeWindow: (720/1280) RequestedResolution: (0/0) EGLSurface: (720/1280)
08-16 10:49:57.634: D/Unity(5615): Renderer: Mali-400 MP
08-16 10:49:57.634: D/Unity(5615): Vendor:   ARM
08-16 10:49:57.634: D/Unity(5615): Version:  OpenGL ES 2.0
08-16 10:49:57.634: D/Unity(5615): GLES:     2
08-16 10:49:57.634: D/Unity(5615): GL_EXT_debug_marker GL_OES_texture_npot GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map 
08-16 10:49:57.639: D/Unity(5615): Creating OpenGLES2.0 graphics device
08-16 10:49:57.639: D/Unity(5615): InitializeGfxDevice OK
08-16 10:49:57.639: D/Unity(5615): Initialize engine version: 5.0.0f4 (5b98b70ebeb9)
08-16 10:49:57.724: D/Unity(5615): Begin MonoManager ReloadAssembly
08-16 10:49:57.749: D/Unity(5615): Platform assembly: /data/app/hl.CupicPilot-1.apk/assets/bin/Data/Managed/UnityEngine.dll (this message is harmless)
08-16 10:49:57.749: D/Unity(5615): Loading /data/app/hl.CupicPilot-1.apk/assets/bin/Data/Managed/UnityEngine.dll into Unity Child Domain
08-16 10:49:57.829: D/Unity(5615): Platform assembly: /data/app/hl.CupicPilot-1.apk/assets/bin/Data/Managed/Assembly-CSharp.dll (this message is harmless)
08-16 10:49:57.834: D/Unity(5615): Loading /data/app/hl.CupicPilot-1.apk/assets/bin/Data/Managed/Assembly-CSharp.dll into Unity Child Domain
08-16 10:49:57.839: D/Unity(5615): Platform assembly: /data/app/hl.CupicPilot-1.apk/assets/bin/Data/Managed/UnityEngine.UI.dll (this message is harmless)
08-16 10:49:57.844: D/Unity(5615): Loading /data/app/hl.CupicPilot-1.apk/assets/bin/Data/Managed/UnityEngine.UI.dll into Unity Child Domain
08-16 10:49:57.869: D/Unity(5615): - Completed reload, in  0.143 seconds
08-16 10:49:57.879: D/Unity(5615): PlayerInitEngineGraphics OK
08-16 10:49:57.884: D/Unity(5615): Found 19 native sensors
08-16 10:49:57.884: D/Unity(5615): Sensor :        Accelerometer ( 1) ; 0.009577 / 0.01s ; LSM330DLC 3-axis Accelerometer / STMicroelectronics 
08-16 10:49:57.884: D/Unity(5615): Sensor :        Accelerometer ( 1) ; 0.009577 / 0.01s ; LSM330DLC 3-axis Accelerometer / STMicroelectronics 
08-16 10:49:57.889: D/Unity(5615): Requested framebuffer: resolution[720x1280], rgba[8/8/8/8], depth+stencil[on], samples[0]
08-16 10:49:57.889: D/Unity(5615): Created framebuffer: resolution[720x1280], rgba[8/8/8/8], depth+stencil[24/8], samples[0] 
08-16 10:49:58.259: D/Unity(5615): Platform assembly: /data/app/hl.CupicPilot-1.apk/assets/bin/Data/Managed/System.Core.dll (this message is harmless)
08-16 10:49:58.359: D/Unity(5615): Platform assembly: /data/app/hl.CupicPilot-1.apk/assets/bin/Data/Managed/System.dll (this message is harmless)
08-16 10:49:58.749: D/Unity(5615): Sensor :        Accelerometer ( 1) ; 0.009577 / 0.01s ; LSM330DLC 3-axis Accelerometer / STMicroelectronics 
08-16 10:49:58.749: D/Unity(5615): PlayerConnection accepted from [192.168.200.100] handle:0x53
08-16 10:49:59.039: I/Unity(5615):  [Play Games Plugin DLL] 08/16/15 10:49:58 +09:00 DEBUG: Activating PlayGamesPlatform.
08-16 10:49:59.039: I/Unity(5615): UnityEngine.Debug:Internal_Log(Int32, String, Object)
08-16 10:49:59.039: I/Unity(5615): UnityEngine.Debug:Log(Object)
08-16 10:49:59.039: I/Unity(5615): GooglePlayGames.OurUtils.Logger:d(String) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
08-16 10:49:59.039: I/Unity(5615): GooglePlayGames.PlayGamesPlatform:Activate() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:228)
08-16 10:49:59.039: I/Unity(5615): GameManager:Authenticate() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\CubicPilot\GameLogic\GameManager.cs:184)
08-16 10:49:59.039: I/Unity(5615): MainMenuGUI:Start() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\CubicPilot\Gui\MainMenuGUI.cs:41)
08-16 10:49:59.039: I/Unity(5615):  
08-16 10:49:59.039: I/Unity(5615): (Filename: C Line: 0)
08-16 10:49:59.044: I/Unity(5615):  [Play Games Plugin DLL] 08/16/15 10:49:59 +09:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
08-16 10:49:59.044: I/Unity(5615): UnityEngine.Debug:Internal_Log(Int32, String, Object)
08-16 10:49:59.044: I/Unity(5615): UnityEngine.Debug:Log(Object)
08-16 10:49:59.044: I/Unity(5615): GooglePlayGames.OurUtils.Logger:d(String) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
08-16 10:49:59.044: I/Unity(5615): GooglePlayGames.PlayGamesPlatform:Activate() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:230)
08-16 10:49:59.044: I/Unity(5615): GameManager:Authenticate() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\CubicPilot\GameLogic\GameManager.cs:184)
08-16 10:49:59.044: I/Unity(5615): MainMenuGUI:Start() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\CubicPilot\Gui\MainMenuGUI.cs:41)
08-16 10:49:59.044: I/Unity(5615):  
08-16 10:49:59.044: I/Unity(5615): (Filename: C Line: 0)
08-16 10:49:59.054: I/Unity(5615):  [Play Games Plugin DLL] 08/16/15 10:49:59 +09:00 DEBUG: SetDefaultLeaderboardForUI: PLACEHOLDER
08-16 10:49:59.054: I/Unity(5615): UnityEngine.Debug:Internal_Log(Int32, String, Object)
08-16 10:49:59.054: I/Unity(5615): UnityEngine.Debug:Log(Object)
08-16 10:49:59.054: I/Unity(5615): GooglePlayGames.OurUtils.Logger:d(String) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
08-16 10:49:59.054: I/Unity(5615): GooglePlayGames.PlayGamesPlatform:SetDefaultLeaderboardForUI(String) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:739)
08-16 10:49:59.054: I/Unity(5615): GameManager:Authenticate() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\CubicPilot\GameLogic\GameManager.cs:187)
08-16 10:49:59.054: I/Unity(5615): MainMenuGUI:Start() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\CubicPilot\Gui\MainMenuGUI.cs:41)
08-16 10:49:59.054: I/Unity(5615):  
08-16 10:49:59.054: I/Unity(5615): (Filename: C Line: 0)
08-16 10:49:59.064: I/Unity(5615):  [Play Games Plugin DLL] 08/16/15 10:49:59 +09:00 DEBUG: Creating platform-specific Play Games client.
08-16 10:49:59.064: I/Unity(5615): UnityEngine.Debug:Internal_Log(Int32, String, Object)
08-16 10:49:59.064: I/Unity(5615): UnityEngine.Debug:Log(Object)
08-16 10:49:59.064: I/Unity(5615): GooglePlayGames.OurUtils.Logger:d(String) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
08-16 10:49:59.064: I/Unity(5615): GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:296)
08-16 10:49:59.064: I/Unity(5615): GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:271)
08-16 10:49:59.064: I/Unity(5615): GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\ISocialPlatform\PlayGamesLocalUser.cs:47)
08-16 10:49:59.064: I/Unity(5615): GameMana
08-16 10:49:59.069: I/Unity(5615):  [Play Games Plugin DLL] 08/16/15 10:49:59 +09:00 DEBUG: Creating real IPlayGamesClient
08-16 10:49:59.069: I/Unity(5615): UnityEngine.Debug:Internal_Log(Int32, String, Object)
08-16 10:49:59.069: I/Unity(5615): UnityEngine.Debug:Log(Object)
08-16 10:49:59.069: I/Unity(5615): GooglePlayGames.OurUtils.Logger:d(String) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
08-16 10:49:59.069: I/Unity(5615): GooglePlayGames.PlayGamesClientFactory:GetPlatformPlayGamesClient(PlayGamesClientConfiguration) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\Platforms\PlayGamesClientFactory.cs:34)
08-16 10:49:59.069: I/Unity(5615): GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:297)
08-16 10:49:59.069: I/Unity(5615): GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlat
08-16 10:49:59.134: D/GamesUnitySDK(5615): Performing Android initialization of the GPG SDK
08-16 10:49:59.309: I/Unity(5615):  [Play Games Plugin DLL] 08/16/15 10:49:59 +09:00 DEBUG: Entering state: BeforeRoomCreateStartedState
08-16 10:49:59.309: I/Unity(5615): UnityEngine.Debug:Internal_Log(Int32, String, Object)
08-16 10:49:59.309: I/Unity(5615): UnityEngine.Debug:Log(Object)
08-16 10:49:59.309: I/Unity(5615): GooglePlayGames.OurUtils.Logger:d(String) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
08-16 10:49:59.309: I/Unity(5615): GooglePlayGames.Native.RoomSession:EnterState(State) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:459)
08-16 10:49:59.309: I/Unity(5615): GooglePlayGames.Native.RoomSession:.ctor(RealtimeManager, RealTimeMultiplayerListener) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:412)
08-16 10:49:59.309: I/Unity(5615): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:GetTerminatedSession() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\
08-16 10:49:59.324: I/Unity(5615):  [Play Games Plugin DLL] 08/16/15 10:49:59 +09:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
08-16 10:49:59.324: I/Unity(5615): UnityEngine.Debug:Internal_Log(Int32, String, Object)
08-16 10:49:59.324: I/Unity(5615): UnityEngine.Debug:Log(Object)
08-16 10:49:59.324: I/Unity(5615): GooglePlayGames.OurUtils.Logger:d(String) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
08-16 10:49:59.324: I/Unity(5615): GooglePlayGames.Native.State:OnStateEntered() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:679)
08-16 10:49:59.324: I/Unity(5615): GooglePlayGames.Native.RoomSession:EnterState(State) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:460)
08-16 10:49:59.324: I/Unity(5615): GooglePlayGames.Native.RoomSession:.ctor(RealtimeManager, RealTimeMultiplayerListener) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayG
08-16 10:49:59.339: I/Unity(5615):  [Play Games Plugin DLL] 08/16/15 10:49:59 +09:00 DEBUG: Entering state: ShutdownState
08-16 10:49:59.339: I/Unity(5615): UnityEngine.Debug:Internal_Log(Int32, String, Object)
08-16 10:49:59.339: I/Unity(5615): UnityEngine.Debug:Log(Object)
08-16 10:49:59.339: I/Unity(5615): GooglePlayGames.OurUtils.Logger:d(String) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
08-16 10:49:59.339: I/Unity(5615): GooglePlayGames.Native.RoomSession:EnterState(State) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:459)
08-16 10:49:59.339: I/Unity(5615): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:GetTerminatedSession() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:47)
08-16 10:49:59.339: I/Unity(5615): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:.ctor(NativeClient, RealtimeManager) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayG
08-16 10:49:59.359: I/Unity(5615):  [Play Games Plugin DLL] 08/16/15 10:49:59 +09:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
08-16 10:49:59.359: I/Unity(5615): UnityEngine.Debug:Internal_Log(Int32, String, Object)
08-16 10:49:59.359: I/Unity(5615): UnityEngine.Debug:Log(Object)
08-16 10:49:59.359: I/Unity(5615): GooglePlayGames.OurUtils.Logger:d(String) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
08-16 10:49:59.359: I/Unity(5615): GooglePlayGames.Native.State:OnStateEntered() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:679)
08-16 10:49:59.359: I/Unity(5615): GooglePlayGames.Native.RoomSession:EnterState(State) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:460)
08-16 10:49:59.359: I/Unity(5615): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:GetTerminatedSession() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\Platforms\Native\Na
08-16 10:49:59.444: I/Unity(5615):  [Play Games Plugin DLL] 08/16/15 10:49:59 +09:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
08-16 10:49:59.444: I/Unity(5615):  
08-16 10:49:59.444: I/Unity(5615): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
08-16 10:49:59.609: I/Unity(5615):  [Play Games Plugin DLL] 08/16/15 10:49:59 +09:00 DEBUG: Invoking user callback on game thread
08-16 10:49:59.609: I/Unity(5615): UnityEngine.Debug:Internal_Log(Int32, String, Object)
08-16 10:49:59.609: I/Unity(5615): UnityEngine.Debug:Log(Object)
08-16 10:49:59.609: I/Unity(5615): GooglePlayGames.OurUtils.Logger:d(String) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
08-16 10:49:59.609: I/Unity(5615): GooglePlayGames.Native.<InvokeCallbackOnGameThread>c__AnonStoreyD`1:<>m__17() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\Platforms\Native\NativeClient.cs:147)
08-16 10:49:59.609: I/Unity(5615): GooglePlayGames.OurUtils.PlayGamesHelperObject:<Update>m__8(Action) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:114)
08-16 10:49:59.609: I/Unity(5615): System.Collections.Generic.List`1:ForEach(Action`1) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/List.cs:361)
08-16 10:49:59.609: I/Unity(5615): GooglePlayGames.OurUtils.PlayGamesHelper
08-16 10:49:59.614: W/Unity(5615): Failed to sign in with Google Play Games.
08-16 10:49:59.614: W/Unity(5615): UnityEngine.Debug:Internal_Log(Int32, String, Object)
08-16 10:49:59.614: W/Unity(5615): UnityEngine.Debug:LogWarning(Object)
08-16 10:49:59.614: W/Unity(5615): GameManager:<Authenticate>m__2(Boolean) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\CubicPilot\GameLogic\GameManager.cs:198)
08-16 10:49:59.614: W/Unity(5615): GooglePlayGames.Native.<InvokeCallbackOnGameThread>c__AnonStoreyD`1:<>m__17() (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\Platforms\Native\NativeClient.cs:148)
08-16 10:49:59.614: W/Unity(5615): GooglePlayGames.OurUtils.PlayGamesHelperObject:<Update>m__8(Action) (at C:\Developer\Sample\Unity\play-games-plugin-for-unity-master\devmae_samples\CubicPilot\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:114)
08-16 10:49:59.614: W/Unity(5615): System.Collections.Generic.List`1:ForEach(Action`1) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/List.cs:361)
08-16 10:49:59.614: W/Unity(5615): GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at C:\Developer\Sample\Unity\
08-16 10:49:59.809: I/Unity(5615): onPause
08-16 10:49:59.929: D/Unity(5615): Sensor :        Accelerometer ( 1) ; 0.009577 / 0.01s ; LSM330DLC 3-axis Accelerometer / STMicroelectronics 
08-16 10:49:59.974: I/Unity(5615): windowFocusChanged: false
08-16 10:50:05.799: I/Unity(5615): onResume
08-16 10:50:05.829: I/Unity(5615): windowFocusChanged: true
08-16 10:50:05.834: D/Unity(5615): Sensor :        Accelerometer ( 1) ; 0.009577 / 0.01s ; LSM330DLC 3-axis Accelerometer / STMicroelectronics 
08-16 10:50:06.079: D/Unity(5615): ANativeWindow: (720/1280) RequestedResolution: (0/0) EGLSurface: (720/1280)
08-16 10:50:06.939: I/Unity(5615):  [Play Games Plugin DLL] 08/16/15 10:50:06 +09:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
08-16 10:50:06.939: I/Unity(5615):  
08-16 10:50:06.939: I/Unity(5615): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)
=====================================================================
SIGN_IN status: VALID, however, a few seconds later application crash and die.

**Comment by claywilkinson** [comment]
It looks like the game resources are not configured correctly.  I see this in the log:
`SetDefaultLeaderboardForUI: PLACEHOLDER`

In Assets/CubicPilot/GameLogic/GameIds.cs you need to replace the placeholders with actual ids from the play console.
(I'll make a not to make it a little less harsh then crashing).
