### ISSUE TITLE
is Social.ReportScore() a heavy command?

### ISSUE THREAD

**Issue by narger17** [playgameservices/play-games-plugin-for-unity#664]
Hi guys, a simple question: is Social.ReportScore() a heavy command?
I'm going to use it  about 1 time per second, will it slow down the game ? Thank you

**Comment by claywilkinson** [comment]
@narger17  -the call is actually processed internally on another thread, so there should be minimal impact. Have you tried to do any benchmarking?

**Comment by claywilkinson** [comment]
OK to close?  Please reopen if you have more questions about this!
