### ISSUE TITLE
CommitUpdate() freeze without network connection.

### ISSUE THREAD

**Issue by VladimirKuznetsov** [playgameservices/play-games-plugin-for-unity#665]
Hello!
When I'm trying to save my game progress without internet connection, CommitUpdate() freezes and never calls the callback. I tracked it through NativeSavedGameClient.cs and SnapshotManager. It seems like everything goes fine till the call to C.SnapshotManager_Commit().
I'm on Android 4.4.1. When I try saving game with internet connection, everything works fine.
How can I fix it?

**Comment by VladimirKuznetsov** [comment]
//Here is the code sample
OpenSavedGame ((SavedGameRequestStatus openStatus, ISavedGameMetadata openGame) => {
			// On game opened, write Player data
			if (openStatus == SavedGameRequestStatus.Success) {

				// Convert Player to byte array
				BinaryFormatter bf = new BinaryFormatter();
				MemoryStream ms = new MemoryStream();
				bf.Serialize(ms, pm.player);
				byte[] data = ms.ToArray();
				ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame;
				
				SavedGameMetadataUpdate.Builder builder = new SavedGameMetadataUpdate.Builder();
				builder = builder
					.WithUpdatedDescription("Autosave");
				SavedGameMetadataUpdate updatedMetadata = builder.Build();
				savedGameClient.CommitUpdate(openGame, updatedMetadata, data, (SavedGameRequestStatus status, ISavedGameMetadata saveGame) => {
					// Never got here
				});
			}
		});

**Comment by claywilkinson** [comment]
This has been fixed in a more recent version of play game services library (the part from the Android SDK).
