### ISSUE TITLE
AcceptFromInbox(listener) callback issue

### ISSUE THREAD

**Issue by ImranZahid** [playgameservices/play-games-plugin-for-unity#666]
If user accepts an invitation from AcceptFromInbox(listener) UI, we only get RoomProgress and RoomConnection callback. How can we get which invitation user selected. I need an invitation object to get variant out of it and setup the room accordingly.

Please help;

**Comment by claywilkinson** [comment]
The invitation object is added to the IRealTimeMultiplayerClient in 0.9.26
``` PlayGamesPlatform.Instance.RealTime.GetInvitation();  ```
