### ISSUE TITLE
GetAccessToken() crashes app if called from a Thread other than Unity main thread

### ISSUE THREAD

**Issue by mwk888** [playgameservices/play-games-plugin-for-unity#667]
First,: thanks for adding GetAccessToken(), I have server-side auth running with it already.

However I'm testing corner cases and found that calling GetAccessToken() from anything other than the Unity main thread crashes the app (testing on Android Samsung S4).

Should GetAccessToken() work when called off the Unity main thread? If not it'd be nice to document that :)

imho it'd be useful if GetAccessToken() worked off the main thread, e.g. I'm testing recovery from expired token and that would be simpler without having to force it back to the main thread. Also I hate to make slow blocking calls on the main thread. (I believe Google's GoogleAuthUtil.getToken() does not require UI thread so theoretically possible?)

---
UPDATE: GetEmail() also crashes if called off main thread

UPDATE 2: I worked around it by calling it only from the main thread even for error recovery. So not a hot issue for me now, but it'd be nice to document which calls require Unity main thread

**Comment by claywilkinson** [comment]
Thanks for the feedback!  What if we change the signature to use a callback, that way we can switch the ui thread and make the call without the caller having to be concerned about which thread?

**Comment by mwk888** [comment]
Hmm, if the call itself can't work from a background thread then I'd suggest just document that it must be called from the Unity main thread and keep the API simple.

A couple reasons:
- there are other calls which also require main thread e.g. GetEmail so it would add a lot of clutter to use that pattern everywhere.
- a lot of Unity coders just do everything on the main thread anyway, so for them it would make a nice simple API complex for no reason

**Comment by claywilkinson** [comment]
Thanks for the feedback.  The documentation has been updated.
