### ISSUE TITLE
Error building Player: CommandInvokationFailure: Failed to re-package resources

### ISSUE THREAD

**Issue by SaRaavan** [playgameservices/play-games-plugin-for-unity#67]
Hi,

 I tried to build for Android  i got following Error.
Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
E:\android-sdk-windows\build-tools\android-4.4\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "E:/android-sdk-windows/platforms/android-19\android.jar" -F bin/resources.ap_ --extra-packages

Previous i got error in Merging Android Manifest Files. But, After Updated to New Android SDK fixes that issue. 

Can anyone faced this issue and guide me to proceed further.

Here is the Screenshot of error i got.

![1](https://f.cloud.github.com/assets/6997731/2471248/e26727a0-b021-11e3-9d48-8fff104bc97a.png)

**Comment by D0R1N** [comment]
@SaRaavan what exactly did you changed in your manifest ?

**Comment by MagicLeeW** [comment]
@nabeelsaleem  have u fixed it?i am getting the same error?if u know,please help meee.thx~

**Comment by nabeelsaleem** [comment]
@MagicLeeW you should try these two methods
[https://www.facebook.com/notes/unity3diy/failed-to-re-package-resources-solution/561369307388645](https://www.facebook.com/notes/unity3diy/failed-to-re-package-resources-solution/561369307388645)

**Comment by MagicLeeW** [comment]
@nabeelsaleem thx, man
