### ISSUE TITLE
help regarding real time multiplayer Quick Match Criteria

### ISSUE THREAD

**Issue by epicepics** [playgameservices/play-games-plugin-for-unity#670]
i hv issue in quick match criteria, like suppose if i wrote createquickgame(min,max,gamevariants) and define min=1 and max=3, then instead of waiting for the others players game starts after connecting only 2 players in a room, without waiting for the max no of opponents.

**Comment by claywilkinson** [comment]
Since the min is 1 and the max is 3, the game can start with only 2 players.  It does sound like something strange is going on.  I'll add it to my list to look at.

**Comment by epicepics** [comment]
yes that also sounds right. but if other (max) players are also available online and they r also requesting for a quick match? then they should also be connected to the room...

**Comment by claywilkinson** [comment]
This has been fixed in 0.9.25.  An easy way to make sure it is working is call ShowWaitingRoomUI() which waits until  all the players are there.
