### ISSUE TITLE
Notification pass to match delegate gets lost when you don't click on the notification and go back through app from Springboard.

### ISSUE THREAD

**Issue by AmitApolloBarman** [playgameservices/play-games-plugin-for-unity#671]
Okay I have a slight problem with the Plugin now. The Match Delegate works perfectly, except when you're outside of said app in the iOS Springboard. You can click on the notification it's fine and processes the match delegate callback, that does work! However when you DON'T click on the notification and go back to the app via task manager or clicking on your app icon it gets lost until you click the notification. This is problematic when you're outside of the app, and simply try to go back into the same scene and are expecting data. I'm going to have to boot user to a different scene when scene goes to background.

**Comment by claywilkinson** [comment]
You can check the invitations from when you resume by calling 
`PlayGamesPlatform.Instance.TurnBased.GetAllInvitations()` and handle the one for the current game.
