### ISSUE TITLE
IOS Builds Broken After Install

### ISSUE THREAD

**Issue by mikest34** [playgameservices/play-games-plugin-for-unity#675]
I integrated this plugin on the Android side with no issues. I verified that I can post scores to leaderboards and unlock achievements, so all is well there.

However on the IOS side, I am having some issues now. First of all, I do not want to use Google Play services on IOS, so I added the NO_GPGS flag as instructed. I performed my build and get about 150 errors, so the build fails. It appears there are a lot of dependencies missing. My assumption was that I would need to add the IOS and Google Play frameworks even though I am supposedly excluding the Google Play code from my build.  Can someone confirm this or did I miss something?

I added the IOS frameworks, then decided to use the Cocoapods to add the Google Play dependencies. I got some errors during Cocoapods install (below) so I "corrected" those problems by changing the links to $(inherited) as they recommended.

```
[!] The `Unity-iPhone [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Unity-iPhone [Release]` target overrides the `OTHER_CFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Unity-iPhone [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

So now I still receive major errors when running the project because I guess this overrides the Unity links with the Google Play settings. I'm not sure if I am missing something here.

**Comment by mikest34** [comment]
It looks like I did a build before adding the flag and didn't close my project before the next build. It seems to be working now.

**Comment by claywilkinson** [comment]
Great! thanks for following up.
