### ISSUE TITLE
What is situation with Marshmallow and GET_ACCOUNTS?

### ISSUE THREAD

**Issue by mcraiha** [playgameservices/play-games-plugin-for-unity#676]
Since latest Android M beta marks GET_ACCOUNTS as dangerous one, what will happen to apps/games that use play-games-plugin-for-unity?

Do we have to ask permission(s) manually, or does play-games-plugin-for-unity do that? And what is the timeframe for possible update? 

And does current plugin handle possible SecurityExceptions (that come when user has denied the permission) gracefully or do we have to add some custom code for it?

**Comment by claywilkinson** [comment]
Unless you are trying to get an access token or the email address, you don't need the GET_ACCOUNTS permission.  The upcoming release of the plugin (in the next couple weeks) will handle prompting for the permission.

**Comment by claywilkinson** [comment]
The plugin has been updated. Version 0.9.27 includes support for the new permissions model in M.
