### ISSUE TITLE
Authenticate problem

### ISSUE THREAD

**Issue by Black137Dragon** [playgameservices/play-games-plugin-for-unity#679]
I am working now for some days to put Google Service in my game, but Authenticate always return false. I checked package matches Bunlde identifier, sha1 fingerprints and that mail is Add as Tester on google service more then 10 times.
Here is logcat report:

D/Unity   (21501): code GL_EXT_texture_filter_anisotropic GL_EXT_multisampled_re
nder_to_texture GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_
disjoint_timer_query
I/Unity   (21501):  [Play Games Plugin DLL] 09/06/15 15:50:41 +02:00 DEBUG: Acti
vating PlayGamesPlatform.
I/Unity   (21501):
I/Unity   (21501): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (21501):
I/Unity   (21501):  [Play Games Plugin DLL] 09/06/15 15:50:41 +02:00 DEBUG: Inst
ance was not initialized, using default configuration.
I/Unity   (21501):
I/Unity   (21501): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (21501):
I/Unity   (21501):  [Play Games Plugin DLL] 09/06/15 15:50:41 +02:00 DEBUG: Play
GamesPlatform activated: GooglePlayGames.PlayGamesPlatform
I/Unity   (21501):
I/Unity   (21501):
I/Unity   (21501):  [Play Games Plugin DLL] 09/06/15 15:50:47 +02:00 DEBUG: Crea
ting platform-specific Play Games client.
I/Unity   (21501):
I/Unity   (21501): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (21501):
I/Unity   (21501):  [Play Games Plugin DLL] 09/06/15 15:50:47 +02:00 DEBUG: Crea
ting real IPlayGamesClient
I/Unity   (21501):
I/Unity   (21501): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (21501):
I/Unity   (21501):  [Play Games Plugin DLL] 09/06/15 15:50:47 +02:00 DEBUG: Ente
ring state: BeforeRoomCreateStartedState
I/Unity   (21501):
I/Unity   (21501): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (21501):
I/Unity   (21501):  [Play Games Plugin DLL] 09/06/15 15:50:47 +02:00 DEBUG: Befo
reRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
I/Unity   (21501):
I/Unity   (21501): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (21501):
I/Unity   (21501):  [Play Games Plugin DLL] 09/06/15 15:50:47 +02:00 DEBUG: Ente
ring state: ShutdownState
I/Unity   (21501):
I/Unity   (21501): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (21501):
I/Unity   (21501):  [Play Games Plugin DLL] 09/06/15 15:50:47 +02:00 DEBUG: Shut
downState.OnStateEntered: Defaulting to no-op.
I/Unity   (21501):
I/Unity   (21501): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (21501):
I/Unity   (21501):  [Play Games Plugin DLL] 09/06/15 15:50:47 +02:00 DEBUG: Star
ting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   (21501):
I/Unity   (21501): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (21501):
I/Unity   (21501):  [Play Games Plugin DLL] 09/06/15 15:51:03 +02:00 DEBUG: Star
ting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   (21501):
I/Unity   (21501): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (21501):
I/Unity   (21501):  [Play Games Plugin DLL] 09/06/15 15:51:03 +02:00 DEBUG: Invo
king user callback on game thread
I/Unity   (21501):
I/Unity   (21501): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   (21501):
I/Unity   (21501): onProcessAuthentication: False
I/Unity   (21501):
I/Unity   (21501): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)

**Comment by DSheep** [comment]
I have the same problem.
My logcat looks pretty much the same

**Comment by MagnusZane** [comment]
Ditto!

**Comment by MagnusZane** [comment]
been struggling with this for two days. any help?

**Comment by DSheep** [comment]
I tried older plugin versions, reuploading and configuring the game from
scratch in the dev console, i checked the SHA1 fingerprints... nothing
wrong there
Nothing... i'm out of ideas :(
It's starting to look like it's not my fault at all. Maybe there is
something wrong on googles side and logging in with testaccounts is not
working.
I'll just finish the game and then publish it.

2015-09-06 19:19 GMT+02:00 MagnusZane <notifications@github.com>:

**Comment by Disord** [comment]
Hello everyone! I find a solution:
1) Upgrade a Google Play Game Services in Android SDK. When I can't sign in, my GPGS were not upgraded.
2) Here the code to sign in:
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder ()
					.Build ();
GooglePlayGames.PlayGamesPlatform.InitializeInstance (config);
GooglePlayGames.PlayGamesPlatform.DebugLogEnabled = true;
GooglePlayGames.PlayGamesPlatform.Activate ();
PlayGamesPlatform.Instance.localUser.Authenticate((bool success) => {});
3) Replace all "Social.Active" and "Social" to "PlayGamesPlatform.Instance".
Good luck!

**Comment by Black137Dragon** [comment]
I tried that and still do not work for me.

**Comment by Virdari** [comment]
I'm on the same boat. Been working on this for 2 days no luck. I'm getting the authentication error all the time. Something is clearly wrong but I can't figure out if it's something on my end or on the end of Google. Same authentication failed error all the time when using the Logger.

**Comment by Virdari** [comment]
On google Play store game services page everything seems to be okay. On Unity everything seems to be fine too. I run the app on my device. Get the log in popup, activity indicator shows up indicating the authentication is in process, then it fails.

**Comment by Disord** [comment]
Sorry, guys. Before I have not a sign in window, then I update my GPGS libraries, etc. (see my post), and window appeared. But achievements and leaderboard UI still not work. Who knows, old plug in versions help me or not?

**Comment by Disord** [comment]
Are you have decide a problem? I don't know how decide it.

**Comment by Disord** [comment]
Hello everyone again. It helps me:
1) Go to: https://console.developers.google.com/project/YOURPROJECTID/apiui/credential
2) Explore your project;
3) Make sure that Signing-certificate fingerprint is print here. My textfield was empty 0_о.

**Comment by DSheep** [comment]
Thank you Disord that actually worked.
The wrong fingerprint was set up in the field. That's wierd since everything was set up correctly on the dashboard.
Now i can finally finish my game. thanks again :)

**Comment by Virdari** [comment]
@Disord  You got it absolutely right. I can't believe this happened. Never trust google from now on lol.

1)  https://console.developers.google.com/project/YOURPROJECTID/apiui/credential
2) Check if you have SHA-1 Fingerprint set there. My textfield was empty too. Just manually entered it and Immediately after that tested my authorization and now I'm in ! :) 

On the other hand this means that linking the app on google play stores developer console is broken and doesn't somehow add the SHA-1 to the credentials page on the backend console. Google fix pls.

**Comment by Disord** [comment]
Good luck =) I'm happy too.

**Comment by Black137Dragon** [comment]
It finnaly works, thank you guys a lot. Here :https://console.developers.google.com/project/YOURPROJECTID/apiui/credential was my finger prints empty

**Comment by MagnusZane** [comment]
Mine were empty too but for some reason, I still can't Authenticate..... are you guys using Instance or Social in your code? neither work for me.

**Comment by Black137Dragon** [comment]
I am using that code now from Disord: 
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder ()
.Build ();
GooglePlayGames.PlayGamesPlatform.InitializeInstance (config);
GooglePlayGames.PlayGamesPlatform.DebugLogEnabled = true;
GooglePlayGames.PlayGamesPlatform.Activate ();
PlayGamesPlatform.Instance.localUser.Authenticate((bool success) => {});

**Comment by Disord** [comment]
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder ().Build ();
GooglePlayGames.PlayGamesPlatform.InitializeInstance (config);
GooglePlayGames.PlayGamesPlatform.DebugLogEnabled = true;
GooglePlayGames.PlayGamesPlatform.Activate ();
Social.localUser.Authenticate((bool success) => {});

Also works. Are you print a correct SHA1 fingerprint?

**Comment by MagnusZane** [comment]
yes. double and triple checked.
only thing I can think to do is maybe delete my app from the store listing and start over.....

**Comment by Disord** [comment]
I think, it will not help =) Remember, if you need to wait a week to delete app from Google Play Services.

**Comment by Virdari** [comment]
Did you check the keystore and the key that you signed your app with ? your package name should be identical and also you must add the app-id and preferably the oath2clientid to google play games > android > setup and press setup, then build the apk and run it on your phone. Also check if your tester account are set. You don't have to add the apk to the Google Play Store Console > All Applications Section. Just need to setup the games services details to be able to test your app on your device.

**Comment by MagnusZane** [comment]
is there a way to delete the services for an app?
@Virdari absolutely.

**Comment by Virdari** [comment]
Yeah just start all over again Game services > Publishing > Delete your game (at the bottom of the page).

**Comment by MagnusZane** [comment]
I don't have the option to delete, just un-publish.

**Comment by Virdari** [comment]
oh god. Did you publish your game services ?

**Comment by MagnusZane** [comment]
I did. that's bad I guess?

**Comment by WinYao** [comment]
my god! I spent nearly half a day to check my project......
@Disord Thank you very much!!!!!!!!!!!!!!!!!

**Comment by MagnusZane** [comment]
@Virdari how do I check my android manifest? in the built apk they are empty.....

**Comment by Disord** [comment]
@MagnusZane PROJECTFOLDER /Temp/Staging Area/
07 сент. 2015 г. 22:49 пользователь "MagnusZane" <notifications@github.com>
написал:

**Comment by MagnusZane** [comment]
@Disord ....it's empty?

**Comment by MagnusZane** [comment]
ah
Built and it filled. it looks fine.... I'm just at a loss. I can't get this to work at all.

**Comment by Disord** [comment]
A folder? Just build apk , and Manifest would be there
07 сент. 2015 г. 22:53 пользователь "MagnusZane" <notifications@github.com>
написал:

**Comment by MagnusZane** [comment]
yeah I looked at the manifest and it looks good. I just can't get the thing to authenticate. all the ids are correct where they need to be. I have configured AND PUBLISHED the app AND the services. the SHA1 Fingerprint is correct @ https://console.developers.google.com/project. my email is listed under the testing section.... I don't get it. I have even tried enabling saved games and including them in the build function. I'm using Unity Ads- could they be conflicting?

**Comment by MagnusZane** [comment]
@claywilkinson - any Ideas?

**Comment by MagnusZane** [comment]
here's my logcat if it helps: 

```
I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:14 -04:00 DEBUG: Activating PlayGamesPlatform.

I/Unity   (22905):  

I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (22905): 

I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:15 -04:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform

I/Unity   (22905):  

I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (22905): 

I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:20 -04:00 DEBUG: Creating platform-specific Play Games client.

I/Unity   (22905):  

I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (22905): 

I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:20 -04:00 DEBUG: Creating real IPlayGamesClient

I/Unity   (22905):  

I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (22905): 

I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:20 -04:00 DEBUG: Entering state: BeforeRoomCreateStartedState

I/Unity   (22905):  

I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (22905): 

I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:20 -04:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.

I/Unity   (22905):  

I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (22905): 

I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:20 -04:00 DEBUG: Entering state: ShutdownState

I/Unity   (22905):  

I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (22905): 

I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:20 -04:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.

I/Unity   (22905):  

I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (22905): 

I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:20 -04:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED

I/Unity   (22905):  

I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (22905): 

I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:28 -04:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED

I/Unity   (22905):  

I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (22905): 

I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:28 -04:00 DEBUG: Invoking user callback on game thread

I/Unity   (22905):  

I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (22905): 

I/Unity   (22905): Nooooo!

I/Unity   (22905):  

I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (22905): 

```

**Comment by Disord** [comment]
@MagnusZane, upload your full log, please.

2015-09-07 23:45 GMT+03:00 MagnusZane <notifications@github.com>:

> here's my logcat if it helps:
>
> I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:14 -04:00 DEBUG: Activating PlayGamesPlatform.
>
> I/Unity   (22905):
>
> I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
>
> I/Unity   (22905):
>
> I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:15 -04:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
>
> I/Unity   (22905):
>
> I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
>
> I/Unity   (22905):
>
> I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:20 -04:00 DEBUG: Creating platform-specific Play Games client.
>
> I/Unity   (22905):
>
> I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
>
> I/Unity   (22905):
>
> I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:20 -04:00 DEBUG: Creating real IPlayGamesClient
>
> I/Unity   (22905):
>
> I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
>
> I/Unity   (22905):
>
> I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:20 -04:00 DEBUG: Entering state: BeforeRoomCreateStartedState
>
> I/Unity   (22905):
>
> I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
>
> I/Unity   (22905):
>
> I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:20 -04:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
>
> I/Unity   (22905):
>
> I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
>
> I/Unity   (22905):
>
> I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:20 -04:00 DEBUG: Entering state: ShutdownState
>
> I/Unity   (22905):
>
> I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
>
> I/Unity   (22905):
>
> I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:20 -04:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
>
> I/Unity   (22905):
>
> I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
>
> I/Unity   (22905):
>
> I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:20 -04:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
>
> I/Unity   (22905):
>
> I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
>
> I/Unity   (22905):
>
> I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:28 -04:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
>
> I/Unity   (22905):
>
> I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
>
> I/Unity   (22905):
>
> I/Unity   (22905):  [Play Games Plugin DLL] 09/07/15 16:37:28 -04:00 DEBUG: Invoking user callback on game thread
>
> I/Unity   (22905):
>
> I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
>
> I/Unity   (22905):
>
> I/Unity   (22905): Nooooo!
>
> I/Unity   (22905):
>
> I/Unity   (22905): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
>
> I/Unity   (22905):
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/679#issuecomment-138375579>
> .
>



-- 
С уважением,
Баранов А.Е.

**Comment by MagnusZane** [comment]
Will do once I'm home again.

**Comment by claywilkinson** [comment]
This looks like the same conversation as #640 - Are these two threads intertwined?  It looks like #640.
Basically, you need to avoid editing the app in console.developers.google.com and use https://play.google.com/apps/publish for editing games.

**Comment by Virdari** [comment]
@claywilkinson we all did that, the result was the SHA-1 certificate not being carried over from https://play.google.com/apps/publish to console.developers.google.com. We had to manually enter the sha-1 certificate in the credentials section in console.developers.google.com. Because even though we had entered it before in Google Play Store > Games Services > Linked Apps section while linking our apps. It didn't automatically get added to the credentials in console.developers.google.com as it should. That was the problem with almost all of us.

**Comment by claywilkinson** [comment]
@Virdari  -thanks for the response - I double checked after posting that and I had the same problem!

The work around is to go to console.developers.google.com, enter the SHA1.  Then I had to go back to the play console, click on the linked app, and toggle one of the buttons so the save button was enabled, then click save.

I've passed along this info to the backend team - they are looking into now so it should be resolved shortly.

**Comment by MagnusZane** [comment]
Unfortunately I think my app services are broken beyond repair. I can't delete them because I tried publishing them to see if it would make any difference and now I don't know what to do.

**Comment by claywilkinson** [comment]
Unfortunately, you are correct, one you publish a game configuration, it cannot be deleted.  So the thing to do it create new games and simply ignore the ones that are unusable (maybe rename them so they are at the bottom of the list.
