### ISSUE TITLE
Can't Show Leaderboard

### ISSUE THREAD

**Issue by ufo123** [playgameservices/play-games-plugin-for-unity#681]
I did all the usual PlayGamesPlatform.Activate() and everything and I can login to Google Play and when I ReportScore the function returns true, even though I did not see any scores in the Developer Console for the high score service. The most troubling problem is ShowLeaderboardUI (or the achievement) which shows nothing. I am not even sure how to debug it with device, any suggestions? By the way im using AdMob but I hope its not related. Thanks!

**Comment by ufo123** [comment]
For android device by the way :)

**Comment by claywilkinson** [comment]
you can get the log file from the device by using [logcat](http://developer.android.com/tools/debugging/debugging-log.html). 

If you can get a log of posting the score, it should indicate that is worked, or if there was a problem, some indication of the issue.

**Comment by ufo123** [comment]
Thanks! That solves the problem, turns out missing an activity in the manifest.
