### ISSUE TITLE
Errors when exporting eclipse project

### ISSUE THREAD

**Issue by mathiassoeholm** [playgameservices/play-games-plugin-for-unity#682]
I'm testing the minimal project. Build And Run works fine, but I get a few errors when exporting an eclipse project.
I would assume that exporting an eclipse project is supported, but correct me if I'm wrong. The guide does tell you to "Build And Run" from unity, so there might be some extra work needed when using the export project option.

I get an error in the NativeBridgeActivity project's manifest file:

Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').	AndroidManifest.xml	/NativeBridgeActivity	line 25

I also get another error:

Description	Resource	Path	Location	Type
The container 'Android Dependencies' references non existing library 'E:\UnityProjects\PackageTest\PackageTest\Builds\MainLibProj\bin\nativebridgeactivity.jar'	UnityPlayerActivity		Build path	Build Path Problem

I don't know if there's supposed to be a file called nativebridgeactivity.jar in that location, but there's not.

I'm running the minimal project, so the steps to reproduce should just be following the setup guide, export an eclipse project, and then import the projects into your workspace.

**Comment by claywilkinson** [comment]
Which version of Unity are you using?  I'll try it out.  

google_play_services_version comes from the play services library which is part of the Android SDK.  The setup within Unity (Window > GooglePlayGames > Setup > Android Setup...) copies it into the Unity project.

There is an activity named NativeBridgeActivity, it is in the Assets/Plugins/Android/MainProjLib/libs/play-games-plugin-support.jar

**Comment by mathiassoeholm** [comment]
I'm using version 5.1.2f1

Turns out I just had to configure the NativeBridgeActivity project in eclipse to reference the google-play-services library.
I think I just assumed that the library references would be in place automatically.

**Comment by claywilkinson** [comment]
Thanks for the update.  OK to close?

**Comment by mathiassoeholm** [comment]
Yeah,  go ahead :-) Thanks
