### ISSUE TITLE
iOS players not visible on GPG public leaderboards

### ISSUE THREAD

**Issue by NitishKumar19** [playgameservices/play-games-plugin-for-unity#686]
Hello folks, Need some help with an issue that we've been facing on our iOS game that uses Google Play Games. 

Have implemented Google Play Games for our Unity Game for both iOS and Android. We use Social.ReportScore to submit users scores to the leaderboard. These scores show up on the Public leaderboard for Android. But iOS players are not visible despite changing their Google+ settings for the app visibility to public. The same user can see himself on the public leaderboard BUT other (android or ios) users can't see him. 

Could you please advice what could be going wrong? All help appreciated.

**Comment by hippogamesunity** [comment]
@NitishKumar19 There was the same issue, try to find it. claywilkinson sayd it is a server side issue and is not fixed yet. iOS users can see their friend only and other android players.

**Comment by hippogamesunity** [comment]
@NitishKumar19 https://github.com/playgameservices/play-games-plugin-for-unity/issues/662

**Comment by claywilkinson** [comment]
There are definitely issues with Google Play Game Services on iOS related to multiplayer and social APIs.  I've been told to communicate that these issues are not going to be addressed in the immediate future.  As a result, you should treat these APIs as "beta" quality.  Please continue to share your experiences using this library on iOS, as your feedback is important to making the library better in the future. 

As there are updates to the iOS SDK, I will share them.
