### ISSUE TITLE
RegisterMonoModules.cpp modification for Simulator

### ISSUE THREAD

**Issue by simsis3d** [playgameservices/play-games-plugin-for-unity#687]
When I build my project with Simulator SDK, a unity window pop up and  say me some extra steps related RegisterMonoModules.cpp . But When I open RegisterMonoModules.cpp in XCode, it is

```
#ifndef INIT_SCRIPTING_BACKEND
extern void RegisterAllClassesIPhone();

void RegisterAllClasses()
{
	// Register classes for unit tests
	RegisterAllClassesIPhone();
}

void RegisterAllStrippedInternalCalls() {}
#endif

void RegisterMonoModules() {}

```
Where are all these codes that I need to change?

**Comment by simsis3d** [comment]
@claywilkinson unity5 (I use 5.1.1p1) RegisterMonoModules.cpp does not contain mono_dl_register_symbol() s anymore. No need to modify RegisterMonoModules.cpp to work on XCode Simulator.

**Comment by claywilkinson** [comment]
I know - this is great! Actually, version 4.6.8 also removed the calls too.  We updated the readme that the editing only needs to be done pre 5.0
https://github.com/playgameservices/play-games-plugin-for-unity#building-for-ios-to-run-on-the-simulator-pre-unity-50.

And in the popup, I think it just says use 4.6.8 or greater.

Thanks for the feedback!
