### ISSUE TITLE
New GPGS Configuration Help

### ISSUE THREAD

**Issue by banditdevelopment** [playgameservices/play-games-plugin-for-unity#690]
I am upgrading to the new GPGS version, 0.9.25, and I can't seem to find any documentation on what the new configuration requires. I am trying to setup GPGS for Android and iOS, but I don't know what the "Constants class name" is or where to find it. Also, I scoured the Google Dev Console, but couldn't find "Android Resources" to paste into the setup page in Unity:
![untitled](https://cloud.githubusercontent.com/assets/10777503/9833431/f48fd880-5964-11e5-9c3a-8177891a53d2.png)

I guess there is a pretty simple answer, but I haven't discovered it. Any help is very appreciated!

Thanks.

**Comment by gguuss** [comment]
For the constants class name, you should just input a name for the generated class created when the configuration is parsed.

**Comment by banditdevelopment** [comment]
Thanks for the info. I'm still unsure about that the Constants Class Name is. I manage all the GPGS through one script; googlePlayManager.cs. Should I put in "googlePlayManager" for Constants Class Name in setup?

**Comment by gguuss** [comment]
The constants class is independent of your code, it should be something distinct that you can remember should you ever need to make changes to your leaderboard IDs, Event IDs, and so forth.

**Comment by banditdevelopment** [comment]
Many thanks @gguuss! Your answers were very helpful and cleared up my problem.
