### ISSUE TITLE
Can't open UI

### ISSUE THREAD

**Issue by PabloM99** [playgameservices/play-games-plugin-for-unity#691]
I can't open Leaderboards nor Achievements UI in my device. Do I need to have my app publish on Google Play to open Leaderboards/Achievements UI?

Code:

public void OnAchievement()
    {
        if (Social.localUser.authenticated)
        {
            Social.ShowAchievementsUI();
        }
    }
    public void OnLeaderboard()
    {
        if (Social.localUser.authenticated)
        {
            PlayGamesPlatform.Instance.ShowLeaderboardUI("ANDROIDID");
        }
    }

**Comment by claywilkinson** [comment]
Are you calling Authenticate() somewhere?  Maybe the best thing to do is start with the CubicPilot sample and get that built and running.  This sample shows how to sign-in and display these UIs.

**Comment by PabloM99** [comment]
Sill not working. I will try to update the plugin.

**Comment by PabloM99** [comment]
I solved the issue by updating the plugin.
