### ISSUE TITLE
New GPGS 0.9.25 sign-in issue on iOS

### ISSUE THREAD

**Issue by chetanisinanand** [playgameservices/play-games-plugin-for-unity#692]
Did everything as mentioned in documentation, and I'm stuck at the sign-in now.

In sign-in web-view Getting Error : deleted_client , the OAuth client was deleted.

I never deleted any OAuth client,

During configuration 
Do I need to 'Enable Google Services for sign in' ?
Do I need to edit  podfile and add line " pod 'Google/SignIn" ?
Do I need to add configuration file (GoogleService-Info.plist) to the Xcode ?  
Or these are not required while using GPGS for unity 

Please guide me with the configuration, let me know if anything I'm missing.

**Comment by claywilkinson** [comment]
The podfile is generated by the GPGS plugin when you build the Unity project for iOS, and does not require any editing (unless there are other pods you need to add to your project).

It sounds like it is configured correctly.  I recommend double checking the linked iOS app in your game console and make sure it there and the client ID matches the one in the resource file pasted into the Setup dialog in Unity.  Do you have multiple iOS apps linked?

Can you provide a log of the problem?

**Comment by chetanisinanand** [comment]
I looked carefully and found that one of the linked app was deleted by one of our colleague long ago and  'Get resources' button in Google Play Developer Console returns a  resource definition data with old(Deleted) Client ID.

however this wasn't creating any issue while using GPGS version prior to 0.9.25, 

I found that the resource definition data (Objective-C) from Google Play Developer Console (Under Achievement/leaderboard ) which contains the resource IDs as well as the Client ID have a old client ID listed : #define CLIENT_ID @"631xxxxxx42-467i4qfsxxxxxxxxxxxxxxx5trpkfoo4se9.apps.googleusercontent.com"
which is already deleted and is different from the one that is currently in use: 631xxxxxx42-avipkmxxxxxxxxxxxxnfvsg2vo.apps.googleusercontent.com.


Please let me know if there is a way to recover old OAuth2 Client Id?

is it a bug in Google Play Developer Console that 'Get resources' button returns a  resource definition data with old(Deleted) Client ID ?


I replaced  #define CLIENT_ID with the new one in Unity configuration window and it Resolved the Issue for me, However I'm not sure if this is the correct way and will not create any issue further

**Comment by claywilkinson** [comment]
It sounds like it is a bug with the console..  The workaround you did is correct - you should use the non-deleted CLIENT_ID.  Thanks for the feedback - I'll pass it along to the console team.

**Comment by chetanisinanand** [comment]
Thanks a lot for your help as always... kudos to you and your team :+1: 
just a thought: can this client ID mismatch has something to do with issue of not getting push notification in production, its just a thought, i haven't tested GPGS 0.9.25 on production, as mentioned by you it might be already fixed,  will test it and let you know.

**Comment by claywilkinson** [comment]
You're welcome!  It could be possible if the client id does not match, it will not find the correct certificate for sending the the push notifications.

**Comment by ZenithCode** [comment]
I will check Push notifications again and post back here!

**Comment by claywilkinson** [comment]
Closing since Creating Gamer profiles is not supported in iOS, which will lead to new players not being able to authenticate on iOS.  See https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html for details.
