### ISSUE TITLE
Compilation error in 0.9.25

### ISSUE THREAD

**Issue by luisparravicini** [playgameservices/play-games-plugin-for-unity#693]
Installed 0.9.25 (using Unity 5.1.2f1) and I get this error:

Assets/GooglePlayGames/Platforms/IClientImpl.cs(31,9): error CS0246: The type or namespace name `TokenClient' could not be found.

I've commented that line and it builds fine (haven't tested it yet).

It seems the same error @uareurapid got on #689

**Comment by uareurapid** [comment]
Yes, it is exactly the same

**Comment by claywilkinson** [comment]
Just to confirm, this happens when using NO_GPGS?

**Comment by luisparravicini** [comment]
It won't compile with or without NO_GPGS (I've been testing things adding and removing NO_GPGS, don't know if it's something related to that change).

**Comment by claywilkinson** [comment]
Which platform are you building for? Android?

**Comment by luisparravicini** [comment]
iOS

**Comment by claywilkinson** [comment]
I doubled check  that it works.  I just updated the plugin package, so you should be able to delete Assets/GooglePlayGames and Assets/Plugins (assuming this plugin is the only one you have).  Then download and re-import the plugin.

Once you do that, you should re-run Windows/GooglePlayGames/Setup/iOS Setup...

Then generate the xcode project.

**Comment by luisparravicini** [comment]
Now it's working.
Thanks.

**Comment by claywilkinson** [comment]
Great!
