### ISSUE TITLE
After setup plugin generates class with digital name of application id that is not compilable

### ISSUE THREAD

**Issue by hexgrimm** [playgameservices/play-games-plugin-for-unity#696]
plugin was extracted from GooglePlayGamesPlugin-0.9.25.unitypackage
After setup plugin generates class with digital name of application id that is not compilable.
File $number$.cs in root folder contains csharp class:

public static class  $number$
{
        public const string leaderboard_best_score = "CgxxI6s_Cnp8xxxxxxAA"; // <GPGSID>
        public const string achievement_mission_001 = "CgxxI6s_CnpxxxxxxAQ"; // <GPGSID>
        public const string achievement_mission_002 = "Cgxx6s_CnpxxxxxQAg"; // <GPGSID>
        public const string achievement_mission_003 = "Cgxx6s_Cnp8xxxxxAw"; // <GPGSID>
        public const string achievement_mission_004 = "Cxx6s_CnpxxxxxxBA"; // <GPGSID>
        public const string achievement_mission_005 = "CxxI6s_Cnp8xxxxxxBQ"; // <GPGSID>

}

It can't be complied ofc

**Comment by claywilkinson** [comment]
It looks like you entered an invalid constants class name.  It needs to be a valid class name such as `AwesomeGame.GPGSIds`

**Comment by hexgrimm** [comment]
This class is fully generated by plugin, I had not this file before setup.

**Comment by claywilkinson** [comment]
Right - the Setup dialog generates this class based on the name you enter here:
![screen shot 2015-09-16 at 8 52 37 am](https://cloud.githubusercontent.com/assets/8752378/9910161/9f205020-5c50-11e5-89e6-623da6ef7fd0.png)

**Comment by hexgrimm** [comment]
Oh, It's true. I guess I have entered app id is same space as older versions of plugin without check that it have new description.
