### ISSUE TITLE
0.9.25 "frengle" iOS Build Rejected From Apple Review

### ISSUE THREAD

**Issue by banditdevelopment** [playgameservices/play-games-plugin-for-unity#699]
Not much to say. Apple Review Board rejected my app because:

"- Upon launching the app, a web page in mobile Safari opens for logging in, then returns the user to the app. The user should be able to log in without opening Safari first."

It was my understanding that the latest build fixed this issue, that's why I updated to it. When I submitted a build with 0.9.21 GPGS I had no problem getting it accepted by Apple Review.

Anyone else have any luck submitting an app with 0.9.25 GPGS? Thanks.

Here is a SS that Apple Review sent me to show why they rejected it:
![temp pplaufmb](https://cloud.githubusercontent.com/assets/10777503/9890856/a1f209ae-5bd0-11e5-98d6-42d7bd2955a1.png)

**Comment by claywilkinson** [comment]
I'll pass this along internally, but I think you should appeal this.  it is a web view, since there is no address bar at the top and action buttons at the bottom, so it is not safari, right?

**Comment by banditdevelopment** [comment]
Yeah, I don't think it is like a redirection to Safari. It's different from me sending a user to a url that would open in Safari.

I can appeal it, I just got the warning after trying to submit the app for public Testflight Beta testing.

**Comment by claywilkinson** [comment]
Thanks for posting!  I'll let you know if i hear anything.  I know the SDK library that is being used (Google SignIn) has been used in other apps (non-games) that have been approved.

**Comment by banditdevelopment** [comment]
Ok, I'll update you on what the review board says.

**Comment by banditdevelopment** [comment]
Well, I got a response from Apple:

"Thank you for your response and feedback. A pop up inside of the app is fine but the app can not exit out. It also should be optional if there are not features that require logging in when you submit to the App Store. We look forward to your resubmission. "

It seems to me that GPGS sign-in comes as close to a pop-up as possible. I suppose I can provide a log-in button, but besides that I don't know what to do.

Do you have any suggestions? Thanks.

**Comment by claywilkinson** [comment]
It sounds like the from the feedback, you should attempt silently authenticating, and then have a sign-in button to authenticate non-silently.

Please keep us posted.

**Comment by banditdevelopment** [comment]
I was under the impression that silent authentication was what the app did after the first sign-in. I'll look into it however, I'm willing to try anything at this point.

**Comment by banditdevelopment** [comment]
UPDATE:

Just got another msg from Apple that said they approved my submission. Not sure why the changed their mind, but all it worked out at least.

Thanks for your help @claywilkinson.

**Comment by claywilkinson** [comment]
Yay! thanks for the update and congrats!

**Comment by banditdevelopment** [comment]
Just want to clarify, it was accepted for Testflight beta testing, not full posting to the app store. I'm not sure if I will have any problem there.

**Comment by claywilkinson** [comment]
yep - one step at a time :)

**Comment by claywilkinson** [comment]
@banditdevelopment  ok to close this?

**Comment by banditdevelopment** [comment]
Fine with me. I'll post here if I am successful in releasing my app. Probably will be close in a few weeks.

**Comment by simsis3d** [comment]
@banditdevelopment please don't forget to inform us when you put your game to production review. Good luck with it.

**Comment by banditdevelopment** [comment]
Don't worry @simsis3d, I will update you all when I submit it, and what the results are.

I am also updating one of my older games to include GPGS too, so we'll see how that goes as well.

**Comment by banditdevelopment** [comment]
@claywilkinson I'm not sure what has changed, but when I run a new build of my game on iOS 9 with Xcode 7 there seems to be a different method of web sign-in:
![img_0285 1](https://cloud.githubusercontent.com/assets/10777503/10236402/0fdbd28e-6873-11e5-92a3-15a14f3bd56a.PNG)

This seems like it will cause problems with their policy:
"- Upon launching the app, a web page in mobile Safari opens for logging in, then returns the user to the app. The user should be able to log in without opening Safari first."

Any thoughts on why this is happening now?

**Comment by claywilkinson** [comment]
I know the GoogleSignIn library (which is used by GPGS) was updated to use the safariwebview class which is new for ios9.  So I believe this is what you are seeing (i am still on ios 8).

As far as I know the SafariWebView should be fine  since it is not switching apps.

However, if you want to go back to the old way by adding this line to your pod file: (or Assets/GooglePlayGames/Editor/Podfile.txt to update all newly built projects)

pod 'GoogleSignIn', '2.2.0'

**Comment by banditdevelopment** [comment]
My only concern is that Apple Review won't differentiate between SafariWebView and Safari; they look very similar.

I plan on submitting the build to final Apple Review today, and I'll see how it goes. If they don't approve it, I can try using the old method again.

Thanks!

**Comment by banditdevelopment** [comment]
@claywilkinson I tried reverting to the older GoogleSignIn lib with the method you gave me, but not I have over 200 errors in Xcode:
![screen shot 2015-10-04 at 4 14 51 pm](https://cloud.githubusercontent.com/assets/10777503/10270004/281a2bce-6ab3-11e5-8786-cd2953654f57.png)

Here is the entire contents of the podfile.txt:

platform :ios, '7.0'

target 'Unity-iPhone' do
pod 'GooglePlayGames', '~> 5.0'
end

target 'Unity-iPhone Tests' do
pod 'GooglePlayGames', '~> 5.0'
end

pod 'GoogleSignIn', '2.2.0'

Did I change something incorrectly?

**Comment by claywilkinson** [comment]
try putting the line "pod 'GoogleSignIn', '2.2.0'" under the pod GooglePlayGames lines in both places.

You can try it out by editing the Podfile file in the xcode project and then run pod update.

I checked with the development team for GoogleSignin, and new one was acceptable to Apple, so maybe you don't need to downgrade?

**Comment by banditdevelopment** [comment]
I want to downgrade because when there is no internet connection on the device, you can't cancel out of the sign-in dialog. When you click "done" in the top-right hand corner the screen goes white and you can't back out of anything.

**Comment by banditdevelopment** [comment]
Just tried putting the line "pod 'GoogleSignIn', '2.2.0'" under the pod GooglePlayGames lines in both places; it still gave all the errors.

**Comment by claywilkinson** [comment]
Are you opening the workspace or the project?  It sounds like you are opening the xcproject  vs. the xcworkspace?  Do you see the Pods project?

**Comment by banditdevelopment** [comment]
I am opening the xcworkspace, I believe. I open whatever is recommended when using Cocopods.

Yes, I did see the Pods project in Xcode.

I decided to just use a workaround and only try to sign in when there was an internet connection, which works OK so far.

**Comment by banditdevelopment** [comment]
Just wanted to let you all know that Apple accepted an update to one my games which contained GPGS.

I'm still waiting on the review board to accept a different game I submitted, but at least they accepted one game.

**Comment by claywilkinson** [comment]
Great news! Congrats!  Thanks for the update.

**Comment by banditdevelopment** [comment]
Admittedly this is off-topic, but is there a known problem with Google Plus sign-in with the plugin on iOS 8?

**Comment by claywilkinson** [comment]
You mean if you have G+ installed and start authenticating in the game via the plugin?

I  just tried it and it worked ok?  Are you having a different experience? (open a new thread please :) )

**Comment by claywilkinson** [comment]
OK to close this issue now?
