### ISSUE TITLE
Crash when trying to create a quick match

### ISSUE THREAD

**Issue by percytse** [playgameservices/play-games-plugin-for-unity#70]
Hi, thanks for the great unity plugin.

I tried to create a quick match, but sometimes it is not able to connect to the room. The view keep showing the loading icon (not showing Auto-Pick waiting icon yet), and it crashed after around several minutes.

It would be great if we can implement our own user interface to handle room events, so that we can let players to perform some action (such as changing character/equipment or even setup game map with others) during waiting.

Here is the crash log, hope it is helpful to you
iOS version: 7.1
iOS device: iPhone 5
Crash log:
m_wrapper_native_to_managed_GooglePlayGames_IOS_IOSRtmpClient_RtmpRoomStatusChangedCallback_int + 68
-[GPGSRealTimeRoomDelegate room:didChangeStatus:] (GPGSRealTimeRoomDelegate.m:84)
+[GPGRealTimeRoomDelegateWrapper room:didChangeStatus:] + 372
-[GPGRealTimeRoom statusDidChange:connectedSetDidChange:participantsDidChange:] + 344
-[GPGRealTimeRoom terminate] + 276
-[GPGRealTimeRoomStateLeavingRoom enter:withManager:] + 122
-[GPGRealTimeRoomStateInRoom leaveRoom:] + 170
-[GPGRealTimeRoomStateInRoom onDataConnectionFailed:] + 306

**Comment by claywilkinson** [comment]
@percytse - thanks for the feedback and suggestion.  We have re-architected the plug-in, so things work differently.  Please open another issue if you are still having problems.
