### ISSUE TITLE
GIGSignIn.h file not found.

### ISSUE THREAD

**Issue by AjayKhara** [playgameservices/play-games-plugin-for-unity#701]
I am using the latest version of google play games services,
While building for iOS, I am getting this error in Xcode.
![screen shot 2015-09-16 at 12 32 01 pm](https://cloud.githubusercontent.com/assets/3821924/9898367/393d197c-5c6f-11e5-8d20-df712f089cdb.png)

**Comment by ZenithCode** [comment]
Add GoogleSignIn infront of each define like this:

 #import < GoogleSignIn/GIDSignIn.h>

**Comment by kunal01** [comment]
how can i add GoogleSignIn infront of?
can i do in xcode?

**Comment by ZenithCode** [comment]
Yes, double click on the error which will open the .mm file.  Then amend and save the file.

**Comment by AjayKhara** [comment]
Thanks Zenith, that did work fine.

But I am having another Issue.
When prompt for sign in, after I allow access, it redirects me to google search page instead of redirecting to the game.
Can anyone help please ?

**Comment by claywilkinson** [comment]
@AjayKhara - I recommend upgrading to Unity 4.6.8 at least - it fixes a lot problems with the IL2CPP code generation (you need to use it in order to support 64 bit iphones) and GPGS 0.9.25 - which changes how authentication works to be acceptable by Apple.

**Comment by AjayKhara** [comment]
Thanks for the heads up @claywilkinson, I did try to use GPGS 0.9.25 with unity 5, but the integrations sounded a bit tough, with cocoa pad, Don't know how to do that. So I switched back to 0.9.21.

**Comment by seaders** [comment]
@claywilkinson I think this is down to "GoogleSignIn" not being in the Podfile.  When I added it in there, it resolved this issue for me.

**Comment by claywilkinson** [comment]
Hmm, for 0.9.25 - the podFile should be using version 5.0 of GooglePlayGames.  The podspec for GooglePlayGames is dependent on Google/SignIn - which should add it transitively to your project.

**Comment by seaders** [comment]
Sorry yeah, you're correct, something must have gone wrong in the post build steps, because while it had been updated on the Unity side, it was still the old one in the XCode project after the build happened.  Very weird.

**Comment by claywilkinson** [comment]
No problem - If you come up with any ideas on how to make it more fool-proof, please share :)

**Comment by seaders** [comment]
Ha!  Campaign and badger Unity to improve their plugin system.  I don't know how bad it is with some of the other platforms, but dear oh dear, when you've more than... 1 plugin on iOS and Android you really start to get hit with some absolutely crazy bugs and issues.

**Comment by adrianmavenhut** [comment]
The fix is to manually update all the source files of a 3rd party library? For each build? Really?
