### ISSUE TITLE
GIDSignIn.h file not found

### ISSUE THREAD

**Issue by kunal01** [playgameservices/play-games-plugin-for-unity#703]
When I integrate Google Play Service in iOS manually without COCOAPODS I'm getting this error 
GIDSignIn.h file not found.

I also add all these frameworks
GoogleSignIn.framework
GoogleSignIn.bundle
GoogleOpenSource.framework
gpg.bundle
gpg.framework

**Comment by ZenithCode** [comment]
See #701
