### ISSUE TITLE
Problem with ShowLeaderboardUI()

### ISSUE THREAD

**Issue by Fiurens** [playgameservices/play-games-plugin-for-unity#704]
When i use PlayGamesPlatform.Instance.ShowLeaderboardUI() with an specific leaderboard it opens normally and shows the leaderboard correctly, but when i close it the game shuts down, and the log is empty.
This doesnt happen when i dont specify any leaderboard (i have two).

I´m using android. Showing achievements and generating quick match just work fine. I tried with two devices. And it worked fine in previous versions.

**Comment by claywilkinson** [comment]
This sounds like you need to update the native libraries in the Plugin/Android directory.  Can you delete the Plugins directory and the Assets/GooglePlayGames folder, download the latest version of the plugin, and then import it?

There is an optional parameter to ShowLeaderboardUI now which is the timespan.  If you have a mismatch between the C# code calling the native library and the library, this crash will happen.

**Comment by Mesh199** [comment]
@claywilkinson I've been having a similar problem just like @Fiurens with Google Play, however, my leaderboard doesn't show at all when i click the leaderboard button. I use Social.ShowLeaderboardUI (); for the call. I do get the authentication page at the start of my game, and the player signs in, but the pop-up on top of the screen that welcomes the player never shows up. I've been trying to fix this for 2 weeks now and no success.

I also installed all of the Android SDK's necessary. And tried building from both Mac and Windows.

**Comment by Fiurens** [comment]
I updated the Plugin/Android directory and that solved the Issue! thanks!
