### ISSUE TITLE
Setup issue.

### ISSUE THREAD

**Issue by PabloM99** [playgameservices/play-games-plugin-for-unity#705]
Where i can find the "Constants class name", and "Resources Definition".
In the Unity setup for Android does say that i can find them on the Play Console but I cant find them.
Also the GitHub page does not include anything about the new update and how to setup, or maybe i cant find them.
Sorry for being so noob.

**Comment by banditdevelopment** [comment]
Maybe this link will help you out: https://github.com/playgameservices/play-games-plugin-for-unity/issues/690

I had some trouble too.

**Comment by PabloM99** [comment]
Thanks, it really helped me.
