### ISSUE TITLE
Remove Google Play Game Services account, attempt to login and crash

### ISSUE THREAD

**Issue by spacetraveller** [playgameservices/play-games-plugin-for-unity#706]
We have found an error on some devices and our client would like this error resolved.

If you remove all your accounts from your device (logout , and delete your accounts ), then attempt to open an app that requires Google Play Games Services as a login, the app crashes when you are returned to the screen in the app to enter your credentials, and hitting login. One example device this occurs on is the Samsung S5. The OS version on the device was 4.4.2

Please see error trace provided:

I/WindowState(  686): WIN DEATH: Window{43524750 u0 com.ourgamename.game1/com.unity3d.player.UnityPlayerNativeActivity}

W/WindowManager(  686): Force-removing child win Window{4366a188 u0 SurfaceView} from container Window{43524750 u0 com.ourgamename.game1/com.unity3d.player.UnityPlayerNativeActivity}

I/ActivityManager(  686): Process com.ourgamename.game1 (pid 11473) has died.

W/WindowManager(  686): Failed looking up window

W/WindowManager(  686): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@410d2998 does not exist

W/WindowManager(  686):     at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8282)

W/WindowManager(  686):     at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8273)

W/WindowManager(  686):     at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:953)

W/WindowManager(  686):     at android.os.BinderProxy.sendDeathNotice(Binder.java:433)

W/WindowManager(  686):     at dalvik.system.NativeStart.run(Native Method)

I/WindowState(  686): WIN DEATH: null

---

**Comment by claywilkinson** [comment]
Is this still an issue?  Is it OK to close it?  If it is still an issue can post more of the log?  The error causing the crash is before the WIN DEATH notification.
