### ISSUE TITLE
Unity 3D closing Leaderboard restarts the game to first scene

### ISSUE THREAD

**Issue by SubatomicHero** [playgameservices/play-games-plugin-for-unity#708]
I have a main menu scene which displays options, one of which is "Leaderboards". This scene is loaded after my Splash screen scene and EULA scene.

I have specified a specific Leaderboard in my code. When I click the back button after looking at the scores the game reloads my first scene rather than take me back to the main menu. This functionality was working in 0.9.21 but since updating to 0.9.25 it is broken.

Viewing achievements still works as it did previously

**Comment by Armend** [comment]
I have exactly the same problem, but for me it seems like the game crashes because the whole app starts again showing the Unity-Splashscreen but there is no bug-report shown up in the console. Really strange. I hope somebody knows how to fix it.

**Comment by SubatomicHero** [comment]
So for me either my app crashes or just completely reboots the app

**Comment by claywilkinson** [comment]
Do you think you can share a small sample that recreates this?

One thing to check is that the native library added a parameter to ShowLeaderboardUI for the timespan to show.

If there is a mismatch between the .cs code and the native lib this usually causes the app to crash when returning, but maybe it is causing this too?

**Comment by SubatomicHero** [comment]
In my main menu code, first I obviously Initialise everything and set my default leaderboard UI
```
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder ().EnableSavedGames ().Build ();
PlayGamesPlatform.InitializeInstance (config);
PlayGamesPlatform.Activate ();
((PlayGamesPlatform)Social.Active).SetDefaultLeaderboardForUI ("myid");
```

Then I have a function that is called the displays the leaderboard:
```
public void ShowLeaderboard ()
{
	Social.ShowLeaderboardUI ();
}
```

**Comment by claywilkinson** [comment]
Thanks - I'll take a look later today.
Just to confirm: you recreated this in a new project with the latest unitypackage (0.9.25)?
What version of Unity?

**Comment by SubatomicHero** [comment]
Thanks Clay :)

I am using that latest Unitypackage but I didnt recreate this is a new project. I shall try that. I am using Unity 5.2.0

**Comment by kunal01** [comment]
@SubatomicHero 
Hello so whats the news?
You solved this?

**Comment by SubatomicHero** [comment]
Nope. Ive updated to the latest version @claywilkinson authored but the issue still occurs. Something has changed in the leaderboard functionality that is causing this between versions 0.9.21 and 0.9.25. The achievement functionality is still behaving as expected.

**Comment by claywilkinson** [comment]
Can you share the log of what happens when you close the leaderboard?  also, can you look at the size of Assets/Plugins/Android/libs/armeabi-v7a/libgpg.so and  Assets/Plugins/Android/libs/x86/libgpg.so

**Comment by Armend** [comment]
Updating the Android SDK with the build in Android SDK Manager of Eclipse solved it for me.

**Comment by claywilkinson** [comment]
Thanks for the update.  Glad you got it working.

**Comment by salal40** [comment]
@Armend I have the same issue. Can you provide details of your SDK update? To what API version did you update the SDK to and did you change the minimum SDK level in unity project settings?

**Comment by Armend** [comment]
@salal40 all i can say is that i updatet the SDK via the Android SDK Manager in Eclipse. Google Play services Rev. 27 and no, i didn't changed the minimum SDK level. Hope this will help you somehow.

**Comment by salal40** [comment]
Thanks. I had to update the plugin as well but I fixed it at last.
