### ISSUE TITLE
0.9.25 "frengle" RealTime.ShowWaitingRoomUI() does not appear, or disappear soon on Android.

### ISSUE THREAD

**Issue by tinsaea121** [playgameservices/play-games-plugin-for-unity#709]
But 0.9.21 normally appears after a few seconds.

Other, I think it is better to add ERROR_CANCELED in NativeRealtimeMultiplayerClient.cs -> class ConnectingState -> ShowWaitingRoomUI()

**Comment by 61015ian** [comment]
Same problems here, anyone get anything?

**Comment by claywilkinson** [comment]
Can you post a log of what is happening?

**Comment by tinsaea121** [comment]
Log >

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:41 +09:00 DEBUG: Entering state: BeforeRoomCreateStartedState

I/Unity   (11252): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (11252): UnityEngine.Debug:Log(Object)

I/Unity   (11252): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)

I/Unity   (11252): GooglePlayGames.Native.RoomSession:EnterState(State) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:475)

I/Unity   (11252): GooglePlayGames.Native.RoomSession:.ctor(RealtimeManager, RealTimeMultiplayerListener) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:428)

I/Unity   (11252): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:CreateQuickGame(UInt32, UInt32, UInt32, UInt64, RealTimeMultiplayerListener) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:67)

I/Unity   (11252): MyGame

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:41 +09:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.

I/Unity   (11252): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (11252): UnityEngine.Debug:Log(Object)

I/Unity   (11252): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)

I/Unity   (11252): GooglePlayGames.Native.State:OnStateEntered() (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:695)

I/Unity   (11252): GooglePlayGames.Native.RoomSession:EnterState(State) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:476)

I/Unity   (11252): GooglePlayGames.Native.RoomSession:.ctor(RealtimeManager, RealTimeMultiplayerListener) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:428)

I/Unity   (11252): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:CreateQuickGame(UIn

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:41 +09:00 DEBUG: QuickGame: Setting MinPlayersToStart = 4

I/Unity   (11252): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (11252): UnityEngine.Debug:Log(Object)

I/Unity   (11252): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)

I/Unity   (11252): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:CreateQuickGame(UInt32, UInt32, UInt32, UInt64, RealTimeMultiplayerListener) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:78)

I/Unity   (11252): MyGame.NetStart:multiQuickGame(UInt32, UInt64, UInt32, Boolean) (at C:\MyGame\Assets\cs\NetStart.cs:1004)

I/Unity   (11252): MyGame.<MultiStart>c__Iterator21:MoveNext() (at C:\MyGame\Assets\cs\GameRoot.cs:689)

I/Unity   (11252):  

I/Unity   (11252): (Filename: C Line: 0)

I/Unity   (11252): 

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:41 +09:00 DEBUG: OnData Callback has addr: 43

I/Unity   (11252): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (11252): UnityEngine.Debug:Log(Object)

I/Unity   (11252): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)

I/Unity   (11252): GooglePlayGames.Native.PInvoke.RealTimeEventListenerHelper:SetOnDataReceivedCallback(Action`4) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\PInvoke\RealTimeEventListenerHelper.cs:159)

I/Unity   (11252): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:HelperForSession(RoomSession) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:108)

I/Unity   (11252): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:CreateQuickGame(UInt32, UInt32, UInt32, UInt64, RealTimeMultiplayerListener) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultipl

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:41 +09:00 DEBUG: BeforeRoomCreateStartedState.IsNonPreemptable: Is preemptable by default.

I/Unity   (11252): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (11252): UnityEngine.Debug:Log(Object)

I/Unity   (11252): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)

I/Unity   (11252): GooglePlayGames.Native.State:IsActive() (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:679)

I/Unity   (11252): GooglePlayGames.Native.RoomSession:StartRoomCreation(String, Action) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:509)

I/Unity   (11252): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:CreateQuickGame(UInt32, UInt32, UInt32, UInt64, RealTimeMultiplayerListener) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:96)

I/Unity   (11252): MyGame.N

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:41 +09:00 DEBUG: Entering state: RoomCreationPendingState

I/Unity   (11252): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (11252): UnityEngine.Debug:Log(Object)

I/Unity   (11252): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)

I/Unity   (11252): GooglePlayGames.Native.RoomSession:EnterState(State) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:475)

I/Unity   (11252): GooglePlayGames.Native.RoomSession:StartRoomCreation(String, Action) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:518)

I/Unity   (11252): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:CreateQuickGame(UInt32, UInt32, UInt32, UInt64, RealTimeMultiplayerListener) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:96)

I/Unity   (11252): MyGame.NetStart:multiQui

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:41 +09:00 DEBUG: RoomCreationPendingState.OnStateEntered: Defaulting to no-op.

I/Unity   (11252): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (11252): UnityEngine.Debug:Log(Object)

I/Unity   (11252): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)

I/Unity   (11252): GooglePlayGames.Native.State:OnStateEntered() (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:695)

I/Unity   (11252): GooglePlayGames.Native.RoomSession:EnterState(State) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:476)

I/Unity   (11252): GooglePlayGames.Native.RoomSession:StartRoomCreation(String, Action) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:518)

I/Unity   (11252): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:CreateQuickGame(UInt32, UInt32, UInt32, U

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:45 +09:00 DEBUG: Entering internal callback for RealtimeManager#InternalRealTimeRoomCallback

I/Unity   (11252):  

I/Unity   (11252): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (11252): 

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:45 +09:00 DEBUG: Entering state: ConnectingState

I/Unity   (11252):  

I/Unity   (11252): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (11252): 

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:45 +09:00 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler

I/Unity   (11252):  

I/Unity   (11252): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (11252): 

I/Unity   (11252): onPause

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:45 +09:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

I/Unity   (11252): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (11252): UnityEngine.Debug:Log(Object)

I/Unity   (11252): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)

I/Unity   (11252): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:HandleAppPausing(Boolean) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:123)

I/Unity   (11252): GooglePlayGames.OurUtils.PlayGamesHelperObject:OnApplicationPause(Boolean) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:151)

I/Unity   (11252):  

I/Unity   (11252): (Filename: C Line: 0)

I/Unity   (11252): 

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:45 +09:00 DEBUG: Entering state: LeavingRoom

I/Unity   (11252): UnityEngine.Debug:Internal_Log(Int32, String, Object)

I/Unity   (11252): UnityEngine.Debug:Log(Object)

I/Unity   (11252): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)

I/Unity   (11252): GooglePlayGames.Native.RoomSession:EnterState(State) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:475)

I/Unity   (11252): GooglePlayGames.Native.ConnectingState:LeaveRoom() (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:1076)

I/Unity   (11252): GooglePlayGames.Native.RoomSession:LeaveRoom() (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:484)

I/Unity   (11252): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:LeaveRoom() (at C:\MyGame\Assets\GooglePlayGames

I/Unity   (11252): windowFocusChanged: false

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:46 +09:00 DEBUG: Entering internal callback for InternalLeaveRoomCallback

I/Unity   (11252):  

I/Unity   (11252): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (11252): 

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:46 +09:00 DEBUG: Entering state: ShutdownState

I/Unity   (11252):  

I/Unity   (11252): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (11252): 

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:46 +09:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.

I/Unity   (11252):  

I/Unity   (11252): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (11252): 

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:46 +09:00 DEBUG: Entering internal callback for RealtimeManager#InternalWaitingRoomUICallback

I/Unity   (11252):  

I/Unity   (11252): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (11252): 

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:46 +09:00 DEBUG: ShowWaitingRoomUI Response: VALID

I/Unity   (11252):  

I/Unity   (11252): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (11252): 

I/Unity   (11252):  [Play Games Plugin DLL] 09/18/15 15:00:46 +09:00 DEBUG: Connecting state ShowWaitingRoomUI: room pcount:1 status: AUTO_MATCHING

I/Unity   (11252):  

I/Unity   (11252): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   (11252): 

I/Unity   (11252): windowFocusChanged: true

I/Unity   (11252): onResume

**Comment by claywilkinson** [comment]
Thanks, we'll take a look.

**Comment by claywilkinson** [comment]
This was a bug :(   There were competing bug fixes.  One was adding the waitingRoomUI, and the other was leaving the room when the application pauses.  The problem was when the waitingRoomUI comes up, the game activity pauses.  In Unity there is no easy way to tell the difference, so the room was incorrectly  left.

The fix checks to see if the waiting room is being launched, and not leave the room.

I checked in the fix, so you can download the package again and re-import.

**Comment by 61015ian** [comment]
Now it's working! Thanks a lot :D!

**Comment by claywilkinson** [comment]
Great!

**Comment by Fiurens** [comment]
I think the same issue is happening on PlayGamesPlatform.Instance.RealTime.CreateWithInvitationScreen.
When i call it it goes to HandleAppPausing and leaves the room.

**Comment by claywilkinson** [comment]
Hmm. Yes, I suppose the same thing can happen.  I'll look into extending the solution to cover the invitation screen as well.

**Comment by claywilkinson** [comment]
This is fixed in 0.9.26
