### ISSUE TITLE
Loading friends doesn't work in latest version

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [playgameservices/play-games-plugin-for-unity#710]
Hi there, @claywilkinson  said loading friends is implemented in this version, and indeed it is but it doesn't work. The user callback is never called. It seems the unmanaged code never calls the callback in the managed part so after the native call being fired I could not print any log in any callback. This is the log output from adb logcat

https://gist.github.com/ashkan-saeedi-mazdeh/a0befc695191bd28607a 

Authentication works as before however we changed our key which we were signing with since the old one wasn't there anymore . The app is not published yet if it helps so we are not even published to closed alpha group, just pending yet.

**Comment by claywilkinson** [comment]
Is this Android or iOS?

Old games/players may not be finding each other yet - existing data is being updated, I am not sure when it will be done, but it sounds like it is not.  New players of existing games, or old players on a new game should be working (at least it worked for me).  You should not need to publish the game, but the players need  to have each other in their circles and have visible gaming profiles.

**Comment by ashkan-saeedi-mazdeh** [comment]
@claywilkinson  this is android and I played the game today, it is never published but at least an empty friend list should be returned, I can not see my callback for localUser.LoadFriends be called at all? shouldn't it at least return an error? I also put logs in InternalCallback and callbackhandler of the FetchConnectedPlayers API which should be called for creating the list of players from the pointer that native code returned but I see no log for them either? should I set anything other than enabling debug too see all logs?

The gist is adb logcat of the android game running on my tablet.

I also notieced the minimal sample after authentication instead of showing welcome + my name still shows ready as state which might again mean Authenticate callback is not being called. I built with unity 5.1, android 4.0.3 with updated google API inside the android SDK

**Comment by ashkan-saeedi-mazdeh** [comment]
It seems #711 can be related since I can not see callbacks executed as well. Also if I use the minimal sample with the new SDK my authenticate callback seem to not be called so the authentication is understood from the isAuthenticated property but the text on the screen never turns to "welcome your name".

What are the causes of callbacks not being called, seems to me that the manage code for FetchConnected is not called back from native code.

**Comment by ashkan-saeedi-mazdeh** [comment]
In this part of NativeClient.cs
''' csharp
internal void FetchFriends(Action<BasicApi.ResponseStatus, List<Player>> callback)
        {
            Logger.e("FETCHING________________");
            C.PlayerManager_FetchConnected(mGameServices.AsHandle(),
                Types.DataSource.CACHE_OR_NETWORK,
                InternalFetchConnectedCallback,
                Callbacks.ToIntPtr<FetchListResponse>(
                    (rsp) => HandleFetchCollected(rsp, callback),
                    FetchListResponse.FromPointer)
            );
        }
'''
The fetching log is printed but InternalCallback and HandleFetchConnectedCallback inside the lambda don't print the logs that I put in them.
For now I only came this far.

**Comment by ashkan-saeedi-mazdeh** [comment]
@claywilkinson  The version which I posted here gets a security exception for android.permission.GET_ACCOUNTS which I added manually to the project. Do you have any idea why this happened (Did not generate automatically the permission).

After fixing this I get a timeout when calling ConnectedPlayers API in the log and the bad thing is that the callback inside managed code is not called.

**Comment by ashkan-saeedi-mazdeh** [comment]
@claywilkinson  did you get a chance to look at this?

**Comment by claywilkinson** [comment]
OK to Close this?  I have checked multiple applications and users on Android and it is working as expected.

GET_ACCOUNTS is not needed for loading the connected players.  It is only needed for email of the local player, etc.

The new plugin 0.9.30 contains updates related to the [Changes in Play Game Permissions](http://android-developers.blogspot.com/2016/01/play-games-permissions-are-changing-in.html?m=1)
which correctly handles the GET_ACCOUNTS permission.

**Comment by claywilkinson** [comment]
The Play Game Services and Google Plus are in the process of no longer being integrated. As a result, these "social" APIs, will return empty lists. More information is at: https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html
