### ISSUE TITLE
0.9.25 "frengle 2nd". Waiting room does not appear when tap auto-matching button in RealTime.CreateWithInvitationScreen() on Android.

### ISSUE THREAD

**Issue by tinsaea121** [playgameservices/play-games-plugin-for-unity#712]
I thought it was the same problem as the previous waiting room bug.

Log >

I/Unity   ( 6804):  [Play Games Plugin DLL] 09/19/15 14:03:14 +09:00 DEBUG: Entering state: BeforeRoomCreateStartedState
I/Unity   ( 6804): UnityEngine.Debug:Internal_Log(Int32, String, Object)
I/Unity   ( 6804): UnityEngine.Debug:Log(Object)
I/Unity   ( 6804): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
I/Unity   ( 6804): GooglePlayGames.Native.RoomSession:EnterState(State) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:475)
I/Unity   ( 6804): GooglePlayGames.Native.RoomSession:.ctor(RealtimeManager, RealTimeMultiplayerListener) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:428)
I/Unity   ( 6804): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:CreateWithInvitationScreen(UInt32, UInt32, UInt32, RealTimeMultiplayerListener) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:134)
I/Unity   ( 6804): MyGame
I/Unity   ( 6804):  [Play Games Plugin DLL] 09/19/15 14:03:14 +09:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
I/Unity   ( 6804): UnityEngine.Debug:Internal_Log(Int32, String, Object)
I/Unity   ( 6804): UnityEngine.Debug:Log(Object)
I/Unity   ( 6804): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
I/Unity   ( 6804): GooglePlayGames.Native.State:OnStateEntered() (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:695)
I/Unity   ( 6804): GooglePlayGames.Native.RoomSession:EnterState(State) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:476)
I/Unity   ( 6804): GooglePlayGames.Native.RoomSession:.ctor(RealtimeManager, RealTimeMultiplayerListener) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:428)
I/Unity   ( 6804): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:CreateWithInvitatio
I/Unity   ( 6804):  [Play Games Plugin DLL] 09/19/15 14:03:14 +09:00 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler
I/Unity   ( 6804):  
I/Unity   ( 6804): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 6804): 
I/Unity   ( 6804): onPause
I/Unity   ( 6804):  [Play Games Plugin DLL] 09/19/15 14:03:14 +09:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
I/Unity   ( 6804): UnityEngine.Debug:Internal_Log(Int32, String, Object)
I/Unity   ( 6804): UnityEngine.Debug:Log(Object)
I/Unity   ( 6804): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
I/Unity   ( 6804): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:HandleAppPausing(Boolean) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:123)
I/Unity   ( 6804): GooglePlayGames.OurUtils.PlayGamesHelperObject:OnApplicationPause(Boolean) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:151)
I/Unity   ( 6804):  
I/Unity   ( 6804): (Filename: C Line: 0)
I/Unity   ( 6804): 
I/Unity   ( 6804):  [Play Games Plugin DLL] 09/19/15 14:03:14 +09:00 DEBUG: Session was torn down before room was created.
I/Unity   ( 6804): UnityEngine.Debug:Internal_Log(Int32, String, Object)
I/Unity   ( 6804): UnityEngine.Debug:Log(Object)
I/Unity   ( 6804): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
I/Unity   ( 6804): GooglePlayGames.Native.BeforeRoomCreateStartedState:LeaveRoom() (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:900)
I/Unity   ( 6804): GooglePlayGames.Native.RoomSession:LeaveRoom() (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:484)
I/Unity   ( 6804): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:LeaveRoom() (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:296)
I/Unity   ( 6804): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:HandleAppPausing(Boolean) (at C:\Users\Me
I/Unity   ( 6804):  [Play Games Plugin DLL] 09/19/15 14:03:14 +09:00 DEBUG: Entering state: ShutdownState
I/Unity   ( 6804): UnityEngine.Debug:Internal_Log(Int32, String, Object)
I/Unity   ( 6804): UnityEngine.Debug:Log(Object)
I/Unity   ( 6804): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
I/Unity   ( 6804): GooglePlayGames.Native.RoomSession:EnterState(State) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:475)
I/Unity   ( 6804): GooglePlayGames.Native.BeforeRoomCreateStartedState:LeaveRoom() (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:902)
I/Unity   ( 6804): GooglePlayGames.Native.RoomSession:LeaveRoom() (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:484)
I/Unity   ( 6804): GooglePlayGames.Native.NativeRealtimeMultiplayerClient:LeaveRoom() (at C:\MyGame\Assets\G
I/Unity   ( 6804):  [Play Games Plugin DLL] 09/19/15 14:03:14 +09:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
I/Unity   ( 6804): UnityEngine.Debug:Internal_Log(Int32, String, Object)
I/Unity   ( 6804): UnityEngine.Debug:Log(Object)
I/Unity   ( 6804): GooglePlayGames.OurUtils.Logger:d(String) (at C:\MyGame\Assets\GooglePlayGames\OurUtils\Logger.cs:58)
I/Unity   ( 6804): GooglePlayGames.Native.State:OnStateEntered() (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:695)
I/Unity   ( 6804): GooglePlayGames.Native.RoomSession:EnterState(State) (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:476)
I/Unity   ( 6804): GooglePlayGames.Native.BeforeRoomCreateStartedState:LeaveRoom() (at C:\MyGame\Assets\GooglePlayGames\Platforms\Native\NativeRealtimeMultiplayerClient.cs:902)
I/Unity   ( 6804): GooglePlayGames.Native.RoomSession:LeaveRoom() (at C:\MyGame\Assets\G
I/Unity   ( 6804): windowFocusChanged: false
I/Unity   ( 6804):  [Play Games Plugin DLL] 09/19/15 14:03:26 +09:00 DEBUG: Entering internal callback for RealtimeManager#PlayerSelectUICallback
I/Unity   ( 6804):  
I/Unity   ( 6804): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 6804): 
I/Unity   ( 6804):  [Play Games Plugin DLL] 09/19/15 14:03:26 +09:00 DEBUG: OnData Callback has addr: 43
I/Unity   ( 6804):  
I/Unity   ( 6804): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 6804): 
W/Unity   ( 6804): !!! [Play Games Plugin DLL] 09/19/15 14:03:26 +09:00 WARNING: Received an attempt to create a room after the session was already torn down!
W/Unity   ( 6804):  
W/Unity   ( 6804): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
W/Unity   ( 6804): 
I/Unity   ( 6804): windowFocusChanged: true
I/Unity   ( 6804): onResume

**Comment by ImranZahid** [comment]
I am having same issue. When Calling CreateWithInvitationScreen, it shows UI to select players and after selecting any, it shows room connection failed with this warning Session was torn down before room was created.

Any help!!

**Comment by sliterod** [comment]
Hello, the same is happening to me.
This is the console output (Android)

09-21 19:51:36.098  29168-30137/? I/Unity﹕ [Play Games Plugin DLL] 09/21/15 19:51:36 -04:30 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:36.184  29168-29183/? D/NativeBridgeActivity﹕ Launching bridge activity: parent:com.unity3d.player.UnityPlayerNativeActivity@4150ffe8 intent Intent { act=com.google.android.gms.games.SELECT_OPPONENTS_REAL_TIME dat=version:7895000 pkg=com.google.android.play.games (has extras) }
09-21 19:51:36.278  29168-29183/? I/Unity﹕ [Play Games Plugin DLL] 09/21/15 19:51:36 -04:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:36.278  29168-29183/? I/Unity﹕ [Play Games Plugin DLL] 09/21/15 19:51:36 -04:30 DEBUG: Session was torn down before room was created.
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:36.278  29168-29183/? I/Unity﹕ [Play Games Plugin DLL] 09/21/15 19:51:36 -04:30 DEBUG: Entering state: ShutdownState
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:36.278  29168-29183/? I/Unity﹕ [Play Games Plugin DLL] 09/21/15 19:51:36 -04:30 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:55.520  29168-29168/? D/GamesUnitySDK﹕ Forwarding OnActivityResult
09-21 19:51:55.528  29168-29168/? D/GamesUnitySDK﹕ Forwarding OnActivityResult Finished
09-21 19:51:55.544  29168-30137/? I/Unity﹕ [Play Games Plugin DLL] 09/21/15 19:51:55 -04:30 DEBUG: Entering internal callback for RealtimeManager#PlayerSelectUICallback
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:55.676  29168-30137/? I/Unity﹕ [Play Games Plugin DLL] 09/21/15 19:51:55 -04:30 DEBUG: OnData Callback has addr: 43
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:55.692  29168-30137/? W/Unity﹕ !!! [Play Games Plugin DLL] 09/21/15 19:51:55 -04:30 WARNING: Received an attempt to create a room after the session was already torn down!
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:55.981  29168-29183/? I/Unity﹕ No se pudo conectar al cuarto
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:55.989  29168-29183/? I/Unity﹕ GooglePlayMatchMake - timer detenido
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:56.098  29168-29183/? I/Unity﹕ Boton encendido cancel/ok, activando colliders
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:56.145  29168-29183/? W/Unity﹕ "ItemsUI Root (2D)/ItemsCamera/ItemsAnchor/Confirmations/OnlineInformationWindow/Window/Button_Ok" has nothing for UIButtonColor to color
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:56.169  29168-29183/? I/Unity﹕ el colider esta prendido
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:57.684  29168-29183/? I/Unity﹕ Se dejo el cuarto
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:57.692  29168-29183/? I/Unity﹕ Ventana Opponnet has left the room. GooglePlayMatchMake OnLeftRoom
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:51:58.012  29168-29183/? I/Unity﹕ Se dejo el cuarto
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:52:02.465  29168-29183/? I/Unity﹕ game onlinematch
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:52:02.512  29168-29183/? I/Unity﹕ actual panel:  PanelOnline
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:52:02.708  29168-29183/? I/Unity﹕ game onlinematch
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:52:02.708  29168-29183/? I/Unity﹕ actual panel:  PanelMode
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
09-21 19:52:02.809  29168-29183/? I/offers-unity﹕ [_activateOffersUI][corner 3]
09-21 19:52:02.817  29168-29183/? I/OffersUnity﹕ activateOffersUIOnUIThread
09-21 19:52:02.817  29168-29168/? I/Offers﹕ activateUIOverActviity [com.unity3d.player.UnityPlayerNativeActivity@4150ffe8][OFFERS_CORNER_TOP_RIGHT][OFFERS_FRAME_INTERVAL_LOW]
09-21 19:52:02.895  29168-29168/? D/OffersGUI﹕ Thread[main,5,main] addOfferGUIViewToActivity: com.unity3d.player.UnityPlayerNativeActivity@4150ffe8
09-21 19:52:05.708  29168-29183/? I/Unity﹕ [Play Games Plugin DLL] 09/21/15 19:52:05 -04:30 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
    (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

**Comment by claywilkinson** [comment]
This was a bug in the plugin that disconnected the room when the unity player activity was paused.  If you re-download  the plugin and import it, the problem will be resolved. (I just uploaded the new unitypackage file right now).

**Comment by claywilkinson** [comment]
This is fixed in version 0.9.26
