### ISSUE TITLE
in 0.9.25 PlayGameLocalUser.cs:136 , base.id is null!!

### ISSUE THREAD

**Issue by ikpil** [playgameservices/play-games-plugin-for-unity#713]
W/Unity   ( 4359): GooglePlayGames.PlayGamesLocalUser:get_id() (at D:\work\sfgunner-android\program\Assets\GooglePlayGames\ISocialPlatform\PlayGamesLocalUser.cs:136)

I'm not good at English.

137 line, base.id is null. is right?
if (true == string.IsNullOrEmpty(base.id) || false == base.id.Equals(retval))
....

208 line, base.id is null, but is right base.AvatarURL?
if (true == string.IsNullOrEmpty(base.AvatarURL) || false == base.AvatarURL.Equals(retval))
....

please check. Cheer up!!

**Comment by ikpil** [comment]
Alternatively, I can do this.

line 31
        internal PlayGamesLocalUser(PlayGamesPlatform plaf) :
            base("localUser", null, null)

line 31
        internal PlayGamesLocalUser(PlayGamesPlatform plaf) :
            base("localUser", string.Empty, string.Empty)

**Comment by claywilkinson** [comment]
This has been fixed in 0.9.26.  Thanks!
