### ISSUE TITLE
Check Google Play games installed

### ISSUE THREAD

**Issue by MOST2K2** [playgameservices/play-games-plugin-for-unity#715]
Hello how do i check if Google Play Games are installed on the device?
I use C#.

https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability#isGooglePlayServicesAvailable(android.content.Context)

**Comment by claywilkinson** [comment]
For Google Play Game Services, you don't need to explicitly worry about this since GPGS uses GoogleApiClient to connect to the server.  GoogleApiClient handles the version checking. See: https://developers.google.com/android/guides/setup#ensure_devices_have_the_google_play_services_apk for more information.

Does that address your concern?

**Comment by MOST2K2** [comment]
No i need to check manually, i want to deploy on amazon, There a normal android devices and kindle devices, these kindle devices dont have play games installed and you can't without the playstore. Thats   why i want to check if they are available.

**Comment by claywilkinson** [comment]
You need to use the JNI interface in Unity to invoke that method.  Something like:
```csharp
 public bool IsPlayServicesAvailable()
        {
            const string GoogleApiAvailability_Classname = 
                "com.google.android.gms.common.GoogleApiAvailability";
            AndroidJavaClass clazz = 
                new AndroidJavaClass(GoogleApiAvailability_Classname);
            AndroidJavaObject obj = 
                clazz.CallStatic<AndroidJavaObject>("getInstance");

            var androidJC = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
            var activity = androidJC.GetStatic<AndroidJavaObject>("currentActivity");

            int value = obj.Call<int>("isGooglePlayServicesAvailable", activity);

            // 0 == success
            // 1 == service_missing
            // 2 == update service required
            // 3 == service disabled
            // 18 == service updating
            // 9 == service invalid
            return value == 0;
        }
```

**Comment by MOST2K2** [comment]
Thank you claywilkinson! I close this issue now.
