### ISSUE TITLE
 get score from leaderboard not working???

### ISSUE THREAD

**Issue by HaimBendanan** [playgameservices/play-games-plugin-for-unity#716]
i have looked over pretty much every thread, couldnt get it done. report score and show all leaderboards work fine.. i tried with the following two calls as said in the documentation:

 ILeaderboard lb = PlayGamesPlatform.Instance.CreateLeaderboard();
                 lb.id = leaderBoard;
                 lb.LoadScores(ok =>
                 {
                     if (ok)
                     {
                         //LoadUsersAndDisplay(lb);
                         score = (int)lb.localUserScore.value;
                         Debug.LogFormat("User score in leaderboard: {0}", score);
                     }
                     else
                     {
                         Debug.Log("Error retrieving leaderboardi");
                     }
                 });

and

 PlayGamesPlatform.Instance.LoadScores(
                         leaderBoard,
                         LeaderboardStart.PlayerCentered,
                         1,
                         LeaderboardCollection.Public,
                         LeaderboardTimeSpan.AllTime,
                         (data) =>
                         {
                             if (data.Valid)
                             {
                                 score = (int) data.PlayerScore.value;
                                 Debug.Log("score from inside leaderboard: " + data.PlayerScore.value);
                                 Debug.Log("formated score from inside leaderboard: " + data.PlayerScore.formattedValue);
                             }
                             else
                             {
                                 Debug.Log("data invalid in leaderboard");
                             }    
                         });
                 }

please help!! :)

**Comment by banditdevelopment** [comment]
Are you trying to load the LB data so you can display it yourself, or are you trying to load the default LB UI?

**Comment by claywilkinson** [comment]
Can you post the log as well?

**Comment by HaimBendanan** [comment]
log when running the first method
line 109 : score = (int)lb.localUserScore.value;
i dont need the leaderboard, i just want to know the best score of the user ( i used it to know if the user have a best score at google that is greater than his local store)

W/Unity   ( 9050):   at Main.Assets.Scripts.GooglegGameServicesConnector+<GetScoreFromLeaderBoard>c__AnonStorey7C.<>m__F2 (Bo
olean ok) [0x00006] in C:\Users\t-haimb\Desktop\fix_bug_35\Main\Assets\Scripts\GooglegGameServicesConnector.cs:109
W/Unity   ( 9050):   at GooglePlayGames.PlayGamesPlatform.HandleLoadingScores (GooglePlayGames.PlayGamesLeaderboard board, Go
oglePlayGames.BasicApi.LeaderboardScoreData scoreData, System.Action`1 callback) [0x0008c] in C:\Users\t-haimb\Desktop\fix_bu
g_35\Main\Assets\GooglePlayGames\ISocialPlatform\PlayGamesPlatform.cs:1035
W/Unity   ( 9050):   at GooglePlayGames.PlayGamesPlatform+<LoadScores>c__AnonStoreyF.<>m__7 (GooglePlayGames.BasicApi.Leaderb
oardScoreData scoreData) [0x00000] in C:\Users\t-haimb\Desktop\fix_bug_35\Main\Assets\GooglePlayGames\ISocialPlatfor

**Comment by HaimBendanan** [comment]
anyone??? i really dont see what i am doing wrong here

**Comment by HaimBendanan** [comment]
???????????????

**Comment by claywilkinson** [comment]
Depending on the permissions of the player, their score may not be in the public scoreboard.  Did you try the social leaderboard? Is it not returning, or returning with no data?  If you show the Leaderboard UI as a test, do you see the score?

**Comment by HaimBendanan** [comment]
i tried this, without success too

 ILeaderboard lb = Social.CreateLeaderboard();
				lb.id = leaderBoard;
				lb.LoadScores(ok =>
				{
					if (ok)
					{
						//LoadUsersAndDisplay(lb);
						score = (int)lb.localUserScore.value;
						Debug.LogFormat("User score in leaderboard: {0}", score);
					}
					else
					{
						Debug.Log("Error retrieving leaderboard");
					}
				});

**Comment by HaimBendanan** [comment]
this is the error i get:
W/Unity   ( 6667): *** [Play Games Plugin DLL] 09/28/15 10:51:57 +03:00 ERROR: Error encountered executing LeaderboardManager
#InternalFetchSummaryCallback. Smothering to avoid passing exception into Native: System.NullReferenceException: Object refer
ence not set to an instance of an object
W/Unity   ( 6667):   at Main.Assets.Scripts.GooglegGameServicesConnector+<GetScoreFromLeaderBoard>c__AnonStorey7B.<>m__EF (Bo
olean ok) [0x00000] in <filename unknown>:0
W/Unity   ( 6667):   at GooglePlayGames.PlayGamesPlatform.HandleLoadingScores (GooglePlayGames.PlayGamesLeaderboard board, Go
oglePlayGames.BasicApi.LeaderboardScoreData scoreData, System.Action`1 callback) [0x00000] in <filename unknown>:0
W/Unity   ( 6667):   at GooglePlayGames.PlayGamesPlatform+<LoadScores>c__AnonStoreyF.<>m__7 (GooglePlayGames.BasicApi.Leaderb
oardScoreData scoreData) [0x00000] in <filename unknown>:0
W/Unity   ( 6667):   at GooglePlayGames.Native.PInvoke.LeaderboardManager.HandleFetchScoreSummary (GooglePlayGames.BasicApi.L
eaderboardScoreData data, GooglePlayGames.Native.PInvoke.FetchScoreSummaryResponse response, System.String

**Comment by claywilkinson** [comment]
Thanks - Looks like something is null - I'll try to take a look today/tomorrow - in the mean time I suggest making sure that all the objects in the callback lambda are not null.

**Comment by HaimBendanan** [comment]
hi, anything new with this issue? 
it happen to someone else as you can see here:
http://answers.unity3d.com/questions/1070291/google-play-get-score-from-leaderboard.html#answer-1072686

**Comment by HaimBendanan** [comment]
nothing?

**Comment by claywilkinson** [comment]
I tried your code and it worked OK for me.  Can you make sure the player your are running as has a score? (or check b.localUserScore != null).

Also check that showLeaderboardUI(leaderBoard) displays the score.

**Comment by HaimBendanan** [comment]
yes, i am trying on my device and i have a score, showLeaderboardUI(leaderBoard) doesnt work well ( sometime it doesnt load anything, sometime crash. i am using showLeaderboardUI() and showing al the leaderboards instead.. do you have any idea how can i fix this issue? what can i do from here?

**Comment by banditdevelopment** [comment]
Try using PlayGamesPlatform.Instance.ShowLeaderboardUI("Cfji293fjsie_QA"); rather than the default social way. This is what is use, and it works well.

Obviously, that leaderboard key is an example, so just copy in your own. 

Hope this helps!

**Comment by HaimBendanan** [comment]
showing a specific leaderboard doesnt work well for me, sometimes it crashes. i still have the problem for getting the score..

**Comment by HaimBendanan** [comment]
ok, i am back on this problem. PlayGamesPlatform.Instance.ShowLeaderboardUI("lead. name");
doesnt work for me. it show the leaderboard, and then when i hit the back button, the app crash. when calling shohLeardboard() without specifying a leaderboard, it work. 
does that mean something to anyone? i tried updating the plugin to te latest version, still not working...

**Comment by claywilkinson** [comment]
That usually means the libgpg.so file is old.  Try deleting Plugins/Android/libs/armeabi-v7a/libgpg.so and Plugins/Android/libs/x86/libgpg.so.  Then reimport those files from the latest plugin 0.9.26.

Also make sure there is only 1 version of those files - sometimes there is a libgpg 1.so also.

**Comment by HaimBendanan** [comment]
thanks ! that was the problem
