### ISSUE TITLE
getAllInvitation()

### ISSUE THREAD

**Issue by simgesimulation** [playgameservices/play-games-plugin-for-unity#717]
@claywilkinson How can I find information about how to use getAllInvitation(). Are there any usecase in examples?(I could not find)

**Comment by simgesimulation** [comment]
my roblem is #487. How  getAllInvitation() solves this problem?

**Comment by simsis3d** [comment]
It is so weird that Invitations from Inbox do not have a gamevarint. In this situation, I have to remove "Invitations Inbox"(The part users see all invitations) from my game and have to use only invitations delivered via the invitation delegate.

**Comment by simgesimulation** [comment]
No one has an idea about getAllInvitation()? I need help

**Comment by claywilkinson** [comment]
Invitation does have a variant property - is it not being filled in? https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/BasicApi/Multiplayer/Invitation.cs#L87

**Comment by simgesimulation** [comment]
Yeah I use variant property when an invitation received. However, what if I use AcceptFromInbox(). Somehow I should get variant number after I accepted an invitation from AcceptFromInbox() and prompt the user that variants does or does not match to play game etc. Did I explain myself correct? Since I cannot access variant from AcceptFromInbox(), I had to remove it. So user sees invitation only from an invitation delivered via the invitation delegate.

**Comment by claywilkinson** [comment]
OK - I understand now.  Unfortunately, there is no way to filter which invitations are shown in the standard inbox UI.

You can do one of two things as a workaround:
1. Implement your own inbox UI and filter the invitations as you display it.
2. Before showing the Inbox UI, call getAllInvitations and decline all the invitations that do not match the variant you are looking for.  There is still a small chance that a new invitation will be added in that small time between filtering the list and showing the UI, so you might still want to have a backup way to check based on the room  data.

Does that make sense?

**Comment by simgesimulation** [comment]
Yeah understand it. So no way with standart inbox UI. Ok I will try the way you mentioned but I could not find getAllInvitations() method:) Where it is declared? How it is used? etc. Is there a document I can look that function?

**Comment by claywilkinson** [comment]
Hmm. You are right! there is no doc on it.  I'll add that this week.
The method is defined at https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/BasicApi/Multiplayer/ITurnBasedMultiplayerClient.cs#L85
you can get it from PlayGamesPlatform.TurnBased.getAllInvitations()

**Comment by simgesimulation** [comment]
My game is realtime, not turnbased. Can I still use this function?

**Comment by claywilkinson** [comment]
I am pretty sure you can? (Did you try?) I will confirm today.

**Comment by simgesimulation** [comment]
@claywilkinson 
Yeah I tried and no problem with it. I closed this thread and opened another thread about profile image. Can you help me with it?

**Comment by claywilkinson** [comment]
Thanks - I'll take a look at that one too.
