### ISSUE TITLE
XmlException - NotWhitespace

### ISSUE THREAD

**Issue by LeftSockStudios** [playgameservices/play-games-plugin-for-unity#718]
Hello! I love your plugin but when I updated to the latest build and latest version of Unity, the plugin required that I "Setup" my project again.

I entered the package name where it says 'Constants Class Name'.
(looks like com.company.gamename)

I entered the Signing-Certificate fingerprint in the box labeled 'Resources Definition'.
(Looks like XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX)

I entered my full client ID (not just the number but with .app.googleusercontent.com at the end) in the box that says client ID.

When I click setup I get the following error message in my console. Please advise.

XmlException: Text node cannot appear in this state.  Line 1, position 1.
Mono.Xml2.XmlTextReader.ReadText (Boolean notWhitespace)
Mono.Xml2.XmlTextReader.ReadContent ()
Mono.Xml2.XmlTextReader.Read ()
System.Xml.XmlTextReader.Read ()
GooglePlayGames.GPGSAndroidSetupUI.ParseResources (System.String className, System.String res) (at Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs:122)
GooglePlayGames.GPGSAndroidSetupUI.PerformSetup (System.String clientId, System.String className, System.String resourceXmlData, System.String nearbySvcId) (at Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs:174)
GooglePlayGames.GPGSAndroidSetupUI.DoSetup () (at Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs:101)
GooglePlayGames.GPGSAndroidSetupUI.OnGUI () (at Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs:86)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:187)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:180)
UnityEditor.HostView.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:76)

**Comment by claywilkinson** [comment]
The resource definition for Android is an xml file that is copied from the Play Game Console.  In your game definition, click on Achievements (or Events, or Leaderboards) and then click "Get resources".  Paste that into the text area.

**Comment by claywilkinson** [comment]
OK to close this one?

**Comment by LeftSockStudios** [comment]
Yes thank you!
