### ISSUE TITLE
ReportScore with scoreTag parameter

### ISSUE THREAD

**Issue by chomi3** [playgameservices/play-games-plugin-for-unity#72]
Hi, 

Are you planning to implement the scoreTag parameter along the ReportScore method?
Would appreciate it :)

https://developers.google.com/games/services/web/api/scores/submit

Great job guys, 
keep it up!

Mike

**Comment by claywilkinson** [comment]
Score tag is now supported in version 0.9.25

**Comment by CipherLab** [comment]
Where? I don't see anything referencing scoreTag in the current build...
