### ISSUE TITLE
Apple Reject My Game

### ISSUE THREAD

**Issue by kunal01** [playgameservices/play-games-plugin-for-unity#720]
Hello
I am asking user to signin at game start.

Here the message from Apple

17.2 - Apps that require users to share personal information, such as email address and date of birth, in order to function will be rejected
17.2 Details

We noticed that your app requires users to register with personal information to access non account-based features, which is not allowed on the App Store. We’ve attached screenshot(s) for your reference.

Apps cannot require user registration prior to allowing access to app content and features that are not associated specifically to the user.

Next Steps

User registration that requires the sharing of personal information must be optional or tied to account-specific functionality.

Please make it clear to the user that registering will enable them to access the content from any of their iOS devices, and to provide them a way to register at any time, if they wish to later extend access to additional iOS devices.

Please note that although guideline 11.6 of the App Store Review Guidelines requires an application to make subscription content available to all the iOS devices owned by a single user, it is not appropriate to force user registration to meet this requirement; such user registration must be made optional.

**Comment by claywilkinson** [comment]
Which version of the plugin are you using?  Can you share the screenshot they are referring to?  Is there a sign in button, or must they sign in to proceed?

Thanks for the info - I'll pass it along

**Comment by kunal01** [comment]
I'm using 0.9.25 version of plugin.
In my game, After game launch immediately open Google SignIn Process.If user cancel it then redirect to game.
After in game user click on Leaderboard,Achievement or MultiPlayer button then it open Google Signin Process if not already signin.

So whats wrong?

![temp jbqdzvbb](https://cloud.githubusercontent.com/assets/14308701/10067186/d333580e-62b7-11e5-9387-b3d9f349dd58.png)

**Comment by chetanisinanand** [comment]
The solution is : your app should not ask for sign-in on launch, it should show app/game screen with a 'Sign-in Button'.
If user clicks that button to sign-in that well and good, if not, then they should be able to proceed further in game without signing-in.
i.e. only try Silent Authentication inside any Start/Awake/OnEnable() method,  first Authentication should always be done on a Button Click event.

**Comment by simsis3d** [comment]
@chetanisinanand so you say that Authentication that starts as soon as game start is not accepted by Apple? User always has to sign in by using a sign in button? Any idea @claywilkinson 

In my game(Android version), if user open game for the first time, he needs to use sign in button(No silent auth). But for user's following sessions, it does silent auth on starts. Is this a problem?

**Comment by banditdevelopment** [comment]
Did Apple give you any trouble when you submitted for Testflight Beta testing, or only when you uploaded it for final review?

**Comment by kunal01** [comment]
@banditdevelopment 
I directly uploaded to final review.

**Comment by banditdevelopment** [comment]
@simsis3d I don't think it is a problem to sign the user in right away on android, almost every app does that. Only on iOS have I seem any problem.

**Comment by claywilkinson** [comment]
OK to close this issue?
