### ISSUE TITLE
Documentation, tutoarls ? 

### ISSUE THREAD

**Issue by kzoper** [playgameservices/play-games-plugin-for-unity#721]
Do they exist ?

**Comment by claywilkinson** [comment]
There is a codelab from Google I/O 2015 which covers the basics. https://io2015codelabs.appspot.com/codelabs/playservices_unity#1
 Is there something specific you are looking for?

**Comment by kzoper** [comment]
Thanks for the answer.
it would be nice that something like http://docs.unity3d.com/ScriptReference/Transform-position.html
or tutorial like http://www.raywenderlich.com/86040/creating-cross-platform-multiplayer-game-unity-part-1
Lesson a problem in the second part.It throws an error I can not find a way to solve it, and need for documentation
