### ISSUE TITLE
Social.localUser.id throws a Null Exception

### ISSUE THREAD

**Issue by kamend** [playgameservices/play-games-plugin-for-unity#722]
I get an Null exception, if I try to access Social.localUser.id, after a successful authentication.

I/Unity   ( 2487): NullReferenceException: Object reference not set to an instance of an object
I/Unity   ( 2487):   at GooglePlayGames.PlayGamesLocalUser.get_id () [0x00000] in <filename unknown>:0

The solution is this code change in PlayGamesLocalUser.cs:

from:

        internal PlayGamesLocalUser(PlayGamesPlatform plaf) :
		base("localUser", null, null)
        {
            mPlatform = plaf;
            emailAddress = null;
        }

to:

        internal PlayGamesLocalUser(PlayGamesPlatform plaf) :
		base("localUser", string.Empty, string.Empty)
        {
            mPlatform = plaf;
            emailAddress = null;
        }

**Comment by claywilkinson** [comment]
Thanks! I'll add it to the list - or please feel free to submit at Pull Request.

**Comment by wivlaro** [comment]
I had the same problem. I don't understand how this change fixes it, but it did for us. Thanks. :+1:

**Comment by claywilkinson** [comment]
Fixed in version 0.9.26
