### ISSUE TITLE
Inviter profile image

### ISSUE THREAD

**Issue by simgesimulation** [playgameservices/play-games-plugin-for-unity#726]
@claywilkinson 
Hi
I am using getAllInvitations() to make a custom inbox UI. However, invitation.Inviter.Player.image returns null. I think it is a bug. Can you please look at here? My issue is urgent:( Thanks...

**Comment by simgesimulation** [comment]
In default inbox UI, I can see the profile pictures of inviters. I need those pictures!!!

**Comment by simgesimulation** [comment]
@claywilkinson 
For hours I am trying to make a custom inbox UI. Is it that much hard to write a function, callback,whatever  that returns which invitation is accepted and its variant when user accepts an invitation from default inbox UI. It should not be so hard because we can access variant when an invitation received. So we should be able to access variant when it is accepted from UI. This should be definitelly  implemented. Than no need to custom UI.

**Comment by simgesimulation** [comment]
@claywilkinson You forgot us? we turtles need a master here:)

**Comment by claywilkinson** [comment]
(I am not sure I am worthy to be the master :))
I tried calling LoadAllInvitations and then loading the image of the first inviter.  Everything worked OK.
It could be that the profile of the player is not visible to the other player?  Are they in each other's circles or have their profiles marked as public?
Here is the code I used that worked:
```
private void DoGetAllInvitations()
        {
            mFirstInvite = null;
            PlayGamesPlatform.Instance.TurnBased.GetAllInvitations(
                (invites) =>
                {
                    _mStatus = "Got " + invites.Length + " invites";
                    foreach(Invitation invite in invites)
                    {
                        _mStatus += " " + invite.InvitationId + " (" +
                            invite.InvitationType + ") from " +
                            invite.Inviter + "\n";
                        if (mFirstInvite == null) {
                            mFirstInvite = invite;
                            StartCoroutine(LoadImage(invite.Inviter.Player.AvatarURL));
                        }
                    }
                });
        }

        IEnumerator LoadImage(string url)
        {
            mInviterTexture = Texture2D.whiteTexture;
            Debug.Log("Loading image from " + url);
            WWW www = new WWW(url);
            while (!www.isDone)                                          
            {                                                                   
                yield return null;                                              
            }                                                                   
            if (www.error == null)
            {
                mInviterTexture = www.texture;
            }
            else
            {
                Debug.Log("Error downloading image: " + www.error);
            }
        }
```

**Comment by claywilkinson** [comment]
As far as getting the variant, it should be filled in and available when the AcceptFromInbox callback is invoked by using `match.Variant` property.

**Comment by simgesimulation** [comment]
@claywilkinson 
You are using AvatarURL and download it. I did not use it. I used image property of Inviter.Player which  looks return texture2D but it always returns null. So I should use avatarURL?
Second, yeah I am using realtime.
Third, there is only one master here:)

**Comment by claywilkinson** [comment]
I updated the code for the Inviter.Player so the image is loaded now.  This is in 0.9.26.

Thanks for the feedback!

**Comment by srcsameer** [comment]
@claywilkinson when using `public void ListInv()
	{
		PlayGamesPlatform.Instance.RealTime.GetAllInvitations(
		(invites) =>
		{
			Debug.Log("Got " + invites.Length + " invites");
			string logMessage = "";
			foreach(Invitation invite in invites)
			{
				logMessage += " " + invite.InvitationId + " (" +
					invite.InvitationType + ") from " +
					invite.Inviter + "\n";
				if (mFirstInvite == null) {
					mFirstInvite = invite;
				}
			}
			Debug.Log(logMessage);
		});
	}`

getting an error : GPGS.cs(575,6): error CS0103: The name `mFirstInvite' does not exist in the current context
