### ISSUE TITLE
Leaderboard Score

### ISSUE THREAD

**Issue by kunal01** [playgameservices/play-games-plugin-for-unity#729]
Can some one give me code of how to get player's score from leaderboard?
I'm unable to understand example.

**Comment by banditdevelopment** [comment]
Have you fully configured your unity project with GPGS plugin?

**Comment by kunal01** [comment]
yes 
just don't know how to retrieve my score from leaderboard.

**Comment by Fiurens** [comment]
I´m using this:
	public void loadScores(){
		PlayGamesPlatform.Instance.LoadScores("LEADERBOARDID",(
			(scores) => {
			if(scores != null){
				Debug.Log ("scoreLength : " + scores.Length);
				foreach(IScore sc in scores){
					if(sc.userID.Equals(PlayGamesPlatform.Instance.localUser.id)){
						Debug.Log ("mi score : " + sc.value);
					}
				}
			}
		}));
	}

just replace "LEADERBOARDID" with your leaderboard ID

**Comment by banditdevelopment** [comment]
This is what I use to get the default leaderboard UI:

GooglePlayGames.PlayGamesPlatform.Activate();
Social.localUser.Authenticate (success => {
				if (success) {
					Debug.Log ("Authentication successful");
					string userInfo = "Username: " + Social.localUser.userName + 
						"\nUser ID: " + Social.localUser.id + 
							"\nIsUnderage: " + Social.localUser.underage;
					Debug.Log (userInfo);
				}
				else{
					//Application.LoadLevel(1);
					Debug.Log ("Authentication failed");
				}
			});

PlayGamesPlatform.Instance.ShowLeaderboardUI("YourLeaderboardID");
