### ISSUE TITLE
Using Plugin with Unity 3.5.7 import issues

### ISSUE THREAD

**Issue by DPGaming** [playgameservices/play-games-plugin-for-unity#73]
Following the listed directions I have imported the newest version of the plugin.  However immediately after right clicking assets and importing custom package there are 13 errors all referencing missing AndroidJavaProxy.

Assets/GooglePlayGames/Platforms/Android/AndroidClient.cs(320,57): error CS0246: The type or namespace name `AndroidJavaProxy' could not be found.

**Comment by ephrisian** [comment]
I'm running into the issue in build 0.9.25 with unity 5.2.1f1. What was the work around for resolving this?

**Comment by claywilkinson** [comment]
The plugin has changed substantially since march 2014 - can you open an new issue?  There was a bug in 0.9.25 in building for iOS.  0.9.26 fixed this.
