### ISSUE TITLE
Xcode 7 Errors

### ISSUE THREAD

**Issue by banditdevelopment** [playgameservices/play-games-plugin-for-unity#730]
After updating to Xcode 7 I ran into a few errors. First, I had to declare that my app did not support splitscreen, but that was easy to do.

Most importantly, when submitting to iTunes Connect I get these errors:
![screen shot 2015-09-29 at 8 06 08 am](https://cloud.githubusercontent.com/assets/10777503/10163557/b9b27504-6681-11e5-94c1-9d41d002899d.png)

Has anyone else had problems with Xcode 7?  I though I remembered seeing another issues about Xcode 7 here on Github, but I couldn't find it.

Thanks.

**Comment by simsis3d** [comment]
is it related with this https://github.com/playgameservices/play-games-plugin-for-unity/issues/728

**Comment by banditdevelopment** [comment]
@simsis3d Thanks, but I think I have a different problem. I don't have any of those errors.

I am using Unity 5.2.1f1, Xcode 7, iOS 9 for testing, and the latest GPGS plugin with Cocoa-pods by the way.

**Comment by banditdevelopment** [comment]
As a workaround I am installing Xcode 6.4 along side Xcode 7 and will use 6.4 to submit to the App Store.

Obviously this is not a fix, but my app release date is coming up and I want to ship as soon as possible.

If anyone has some info, I'd be grateful. Thanks.

**Comment by sorab2142** [comment]
I have the same error as well.

**Comment by banditdevelopment** [comment]
I rebuild the Xcode project in Unity and this time I only got this error when archiving:
![screen shot 2015-09-30 at 10 43 49 am](https://cloud.githubusercontent.com/assets/10777503/10196298/36bd1624-6760-11e5-8e54-21485a1c7117.png)

Not sure why I only got one error, I only made a minor change to my code in Unity and no changes in Xcode.

As a side note I get an Apple Mach-o link error when I try to build the project in Xcode 6.4, not sure if that is related.

**Comment by banditdevelopment** [comment]
After doing some research on Xcode Error ITMS-90535 it turns out that in Xcode 7 Apple has a new policy for checking the .plist of different bundles, not just GPGS bundles.

To fix this problem, it is necessary to delete the 'Executable file' field in the plist of any files Xcode gave an error on.

Here is an example of what the plist should look like for it to pass Xcode "inspection" :
![screen shot 2015-09-30 at 11 36 16 am](https://cloud.githubusercontent.com/assets/10777503/10198517/6529fa22-676a-11e5-93c6-2e83050ba3b6.png)

More info can be found below:
http://forum.unity3d.com/threads/error-itms-90535-unexpected-cfbundleexecutable-key-unityads-bundle.357288/
http://stackoverflow.com/questions/32622899/itms-90535-unable-to-publish-ios-app-with-latest-google-signin-sdk

Of course, iTunes Connect is down at the moment so I'm not positive this will work, but it's worth a shot if you can get a connection to upload an altered archive.

Hope this helps.

**Comment by banditdevelopment** [comment]
UPDATE:

This method worked perfectly for me, it submitted just fine.

**Comment by HaimBendanan** [comment]
is there a possibility to get a solve for this in the plugin?

**Comment by tyrmullen** [comment]
In this case, the fix should come not from the plug-in but from the GPGS C++ SDK (which the Unity plug-in pulls in).  The next release of that SDK will be built with Xcode 7 and so will fix this issue.

**Comment by antionio** [comment]
I understand the quick'n'dirty solution for now is to edit the Info.plist file inside gpg.bundle. How do I do that? The file is in binary so I can't edit it.

**Comment by wivlaro** [comment]
perhaps this will do it:
```
defaults delete /Full/Path/To/Project/Build/Products/Debug-iphoneos/myapp.app/gpg.bundle/Info CFBundleExecutable
```

**Comment by antionio** [comment]
@wivlaro I can't seem to do it that way either. Currently it's impossible for me to upload an IPA so I'm contemplating removing the services completely to get things working again. Don't know if others still suffer from this but if there are other than me I think this issue should not be closed yet.
