### ISSUE TITLE
LoadScores returning only 1 rank

### ISSUE THREAD

**Issue by jarramono** [playgameservices/play-games-plugin-for-unity#731]
Hello,
I'm running a game on Google Play Game Services Alpha testing stage and wjen I get the scores from a leaderboard, I only get 1 score, although if I open the ShowLeaderboardUI, I can see there are more than one scores on that leaderboard. 

The calling method I'm using is:
<pre><code>PlayGamesPlatform.Instance.LoadScores(
	leaderboardId,
	LeaderboardStart.TopScores,
	20,
	LeaderboardCollection.Social,
	LeaderboardTimeSpan.AllTime,
	(data) =>{
		Debug.Log("Leaderboard data valid: " + data.Valid 
	      + "\n approx:" +data.ApproximateCount 
	      + " have " + data.Scores.Length);
		setScores(data.Scores);
	}
);</code></pre>

I also tried Social.CreateLeaderboard (), but it only returns 1 score as well.
<br/>
<br/>
The wierd thing is that if I call then call PlayGamesPlatform.Instance.LoadScores (returns 1 score), then open Social.ShowLeaderboardUI () (it shows me more than 1 score ), close it and then call PlayGamesPlatform.Instance.LoadScores again, it then works fine, returning all scores.
<br/>
<br/>
Here is the log I get, in case it is of any help:
<br/>
<br/>
<pre>
V/GamesNativeSDK( 8784): Play Games callback indicates connection.
I/GamesNativeSDK( 8784): Successfully connected to Google Play.
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:37 -03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:37 -03:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:37 -03:00 DEBUG: Populating User
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:37 -03:00 DEBUG: Found User: [Player: **my user** ]
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:37 -03:00 DEBUG: Maybe finish for User
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:37 -03:00 DEBUG: Auth not finished. User=[Player: **my user**] achievements=
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:37 -03:00 DEBUG: Entering internal callback for AchievementManager#InternalFetchAllCallback
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:37 -03:00 DEBUG: Populating Achievements, status = VALID
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:37 -03:00 DEBUG: Found 5 Achievements
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:37 -03:00 DEBUG: Maybe finish for Achievements
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:37 -03:00 DEBUG: Auth finished. Proceeding.
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:37 -03:00 DEBUG: Invoking Callbacks: System.Action`1[System.Boolean]
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:37 -03:00 DEBUG: Invoking user callback on game thread

I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:38 -03:00 DEBUG: Entering internal callback for LeaderboardManager#InternalFetchCallback
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:39 -03:00 DEBUG: Entering internal callback for LeaderboardManager#InternalFetchSummaryCallback
I/Unity   ( 8784):  [Play Games Plugin DLL] 09/29/15 19:47:39 -03:00 DEBUG: Entering internal callback for LeaderboardManager#InternalFetchScorePage
I/Unity   ( 8784): Leaderboard data valid: True
I/Unity   ( 8784):  approx:3 have 1
</pre>

Thanks for the help!

**Comment by ArmandCloud** [comment]
Hello , 

 "LeaderboardCollection.Social" . This may be the problem.  Could you pls try "LeaderboardCollection.Public "

Regards,

**Comment by jarramono** [comment]
Hi, tanks for the response.

I also tried using the scope LeaderboardCollection.Public, but the result is the same: only one rank is returned.

What I ended up doing is connecting with the java SDK using an Android plugin, loading the results for that leaderboard (as this seems to do tha same trick as calling Social.ShowLeaderboardUI () ), and only after calling PlayGamesPlatform.Instance.LoadScores() to get the complete rank list. It is a sad method, but it works for now.

**Comment by claywilkinson** [comment]
I want to understand the workaround  -  first  you call a Java API directly (which API method?) to load the scores (or show the leaderboard UI) then PlayGamesPlatform.Instance.LoadScores works as expected?

Thanks!

**Comment by claywilkinson** [comment]
I want to make sure I understand the workaround: 

 1. call a java method directly (which method?) 
 2. then PlayGamesPlatform.Instance.LoadScores()  works as expected.

Thanks!

**Comment by jarramono** [comment]
I use this method to load the scores from the Android Plugin:

<pre>
<code>       PendingResult<LoadScoresResult> results = com.google.android.gms.games.Games.Leaderboards.loadTopScores(mGoogleApiClient,
                leaderboardId,
                LeaderboardVariant.TIME_SPAN_ALL_TIME,
                LeaderboardVariant.COLLECTION_SOCIAL,
                20,
                true);
        results.setResultCallback(mLoadScoresCallback);
 </code>
</pre>

On the callback, I use UnityPlayer.UnitySendMessage to let my Unity Script know the scores can now be loaded with the Unity Plugin using PlayGamesPlatform.Instance.LoadScores()

**Comment by ArmandCloud** [comment]
Interesting.

**Comment by monge93** [comment]
Where did you add the java method?

I'm having the same problem that the PlayGamesPlatform.Instance.LoadScore only return one of the scores.
I tried creating an android plugin, but I dont know how to get the GoogleApiClient current instance.

**Comment by jarramono** [comment]
@monge93  sorry I did not reply earlier, but maybe this helps someone who wants to implement this solution.

I used [BeGenerous](https://github.com/playgameservices/android-basic-samples/blob/master/BasicSamples/BeGenerous/src/main/java/com/google/example/games/bg/BeGenerousActivity.java) from the Android SDK basic samples as the base for the plugin, but has to make some modifications to use the Unity current activity to create the GoogleApiClient.

Here is a sample of the code:

<pre>
<code>public class GameServicesConnector implements GoogleApiClient.ConnectionCallbacks, GoogleApiClient.OnConnectionFailedListener  {

    private static GoogleApiClient mGoogleApiClient;
    public static GameServicesConnector theConnector;

    public static void CreateClient() {
        if(theConnector == null) {
            theConnector = new GameServicesConnector();
        }
        if(mGoogleApiClient == null) {
            // Create the Google Api Client with access to Plus and Games
            mGoogleApiClient = new GoogleApiClient.Builder(com.unity3d.player.UnityPlayer.currentActivity)
                    .addConnectionCallbacks(theConnector)
                    .addOnConnectionFailedListener(theConnector)
                    .addApi(Plus.API).addScope(Plus.SCOPE_PLUS_LOGIN)
                    .addApi(Games.API).addScope(Games.SCOPE_GAMES)
                    .build();
        }

    public static void connect() {
        mGoogleApiClient.connect();
    }

    public static void disconnect() {
        mGoogleApiClient.disconnect();
    }
}</code>
</pre>

**Comment by claywilkinson** [comment]
This should be fixed now (it is fixed in an update for the Play Games App that is pushed out to everyone).
