### ISSUE TITLE
Possible to get a user's Google nickname?

### ISSUE THREAD

**Issue by MigrantP** [playgameservices/play-games-plugin-for-unity#732]
I've been able to successfully integrate the plugin and login to Play Games. The local user's display name is returned as my G+ "real name" (first + last) instead of my "nickname" which I have configured in G+ and in Google My Account. We'd like to use the nickname in-game if available. Is there a way to get that property using the plugin? Thanks.

**Comment by claywilkinson** [comment]
Currently there is not an easy way to get the nickname.  You would have to implement calling the Google Plus API directly.  I'll pass it along as an enhancement request.

**Comment by claywilkinson** [comment]
With the permission changes for Game services, players now select a gamer "tag" or nickname which is unrelated to their actual name.  This makes this type of request obsolete I believe.  Please open another issue if this is not the case.
