### ISSUE TITLE
Won't compile in Unity 4.6.8f1

### ISSUE THREAD

**Issue by jmclaine** [playgameservices/play-games-plugin-for-unity#734]
There is an issue with generics of two functions that prevents this plugin from compiling in Unity 4.6.8f1.

PInvokeUtilities.OutParamsToArray
PInvokeUtilities.ArrayToSizeT

The solution was to remove the generic and create each function separately using IntPtr and Byte.

**Comment by claywilkinson** [comment]
Can you post a pull request or at least what the new code looks like?  Thanks!

**Comment by jmclaine** [comment]
internal delegate UIntPtr OutMethodIntPtr([In, Out] IntPtr[] out_bytes, UIntPtr out_size);
		
		internal static IntPtr[] OutParamsToArray(OutMethodIntPtr outMethod)
		{
			UIntPtr requiredSize = outMethod(null, UIntPtr.Zero);
            
			if (requiredSize.Equals(UIntPtr.Zero))
			{
				return new IntPtr[0];
			}

			IntPtr[] array = new IntPtr[requiredSize.ToUInt64()];
			outMethod(array, requiredSize);
			return array;
		}

		internal delegate UIntPtr OutMethodByte([In, Out] Byte[] out_bytes, UIntPtr out_size);

		internal static Byte[] OutParamsToArray(OutMethodByte outMethod)
		{
			UIntPtr requiredSize = outMethod(null, UIntPtr.Zero);

			if (requiredSize.Equals(UIntPtr.Zero))
			{
				return new Byte[0];
			}

			Byte[] array = new Byte[requiredSize.ToUInt64()];
			outMethod(array, requiredSize);
			return array;
		}


        internal static UIntPtr ArrayToSizeT(Byte[] array)
		{
			if (array == null)
			{
				return UIntPtr.Zero;
			}

			return new UIntPtr((ulong)array.Length);
		}

**Comment by claywilkinson** [comment]
Fixed in the latest plugin.
