### ISSUE TITLE
Circle Friends not showing on iOS

### ISSUE THREAD

**Issue by sliterod** [playgameservices/play-games-plugin-for-unity#735]
Hello, good evening.

We are having trouble seeing friends in circles on iOS.
The attached images are from both iOS and Android using the same account (at different times).
As you can see, on Android the account shows the friends (in this case one) while on iOS not.

We'd like to know if this is an issue of the plugin or a problem related to iOS, and in any case, what can we do to solve it?

Here are the current versions we are using:
iOS: Unity 5.2.1
Android: Unity 5.1.3
GooglePlayGames Plugin: 0.9.25

The OS' are:
Android 4.2.2
iOS 9.0

Thanks in advance!
![androidscreenshot_2015-10-01-18-49-33](https://cloud.githubusercontent.com/assets/7783242/10236612/9af41a7c-6871-11e5-817e-dda9dfdb33a0.png)
![iosscreenshot_img_0154](https://cloud.githubusercontent.com/assets/7783242/10236613/9af84b9c-6871-11e5-8bfd-3de2485c88b9.PNG)

**Comment by claywilkinson** [comment]
iOS game services currently has very restrictive view of friends.  There is an enhancement request to make iOS more in-line with the friends permissions on Android.  This affects the leaderboard data as well, see #662  to track the enhancement.
