### ISSUE TITLE
'GooglePlus/GooglePlus.h' file not found

### ISSUE THREAD

**Issue by phobosultra** [playgameservices/play-games-plugin-for-unity#738]
I am using Unity 5.0.2, Google Play Games 0.9.25 and Xcode 7.0.1. Did a fresh build of the whole project with CocoaPods and opened the project in Xcode with the .xcworkspace file. During the build i get the error `GooglePlus/GooglePlus.h' file not found`.
I figured out there was no Base SDK configured in the Pods project but changing the SDK to Latest iOS has no positive effect. I also rerun `pod install`. What do I wrong?

**Comment by jimmy-black** [comment]
Hi,
I’m having the same issue (I can’t use CocoaPods, so I tried doing it the manual way)
It seems the documentation for what to download and what is available is at odds, `Google Play Games C++ SDK` is not on the download page, (should we use `Google Sign-In iOS SDK` instead??) I tried but I only got the GooglePlus/GooglePlus.h' file not found error

Sorry, I’m really not a mac user, and xcode is a little confusing, any help would be very much appreciated

**Comment by Knight2601** [comment]
i'm getting the same issue but with GIDSignIn.h
i've re tried `pod install` but i get:

`Analyzing dependencies
Downloading dependencies
Using GoogleAppUtilities (1.0.0)
Using GoogleAuthUtilities (1.0.1)
Using GoogleNetworkingUtilities (1.0.0)
Using GooglePlayGames (5.0)
Using GooglePlusOpenSource (1.7.1)
Using GoogleSignIn (2.3.1)
Using GoogleSymbolUtilities (1.0.0)
Using GoogleUtilities (1.1.0)
Generating Pods project
Integrating client project
Sending stats

[!] The `Unity-iPhone [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Unity-iPhone/Pods-Unity-iPhone.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Unity-iPhone [Release]` target overrides the `OTHER_CFLAGS` build setting defined in `Pods/Target Support Files/Pods-Unity-iPhone/Pods-Unity-iPhone.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Unity-iPhone [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-Unity-iPhone/Pods-Unity-iPhone.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Unity-iPhone [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Unity-iPhone/Pods-Unity-iPhone.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Unity-iPhone [Debug]` target overrides the `OTHER_CFLAGS` build setting defined in `Pods/Target Support Files/Pods-Unity-iPhone/Pods-Unity-iPhone.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Unity-iPhone [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-Unity-iPhone/Pods-Unity-iPhone.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
`

any ideas?

**Comment by claywilkinson** [comment]
You probably need to add $(inherited) to HEADER_SEARCH_PATHS, which will have an effect on finding the GIDSignIn.h file.

If you add the $(inherited) to the OTHER_LDFLAGS in your project, these warnings will go away.

**Comment by Knight2601** [comment]
Hi

yeah i worked that one out from looking through the issues on github…

Now getting the following after a few builds…

ArgumentNullException: Argument cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[System.String,UnityEditor.iOS.Xcode.PBX.PBXBuildFileData].ContainsKey (System.String key) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:458)
UnityEditor.iOS.Xcode.PBXProjectData.BuildFilesGetForSourceFile (System.String targetGuid, System.String fileGuid)
UnityEditor.iOS.Xcode.PBXProject.BuildFilesGetForSourceFile (System.String targetGuid, System.String fileGuid)
UnityEditor.iOS.Xcode.PBXProject.SetCompileFlagsForFile (System.String targetGuid, System.String fileGuid, System.Collections.Generic.List`1 compileFlags)
GooglePlayGames.GPGSPostBuild.UpdateGeneratedPbxproj (System.String pbxprojPath) (at Assets/GooglePlayGames/Editor/GPGSPostBuild.cs:248)
GooglePlayGames.GPGSPostBuild.OnPostprocessBuild (BuildTarget target, System.String pathToBuiltProject) (at Assets/GooglePlayGames/Editor/GPGSPostBuild.cs:116)
UnityEditor.HostView:OnGUI()

any ideas?

**Comment by Knight2601** [comment]
ok so now it gets worse, i think I’ve broken it as i cannot build Android or IOS now?!

UnityException: Can not sign application
Unable to sign application; please provide passwords!
UnityEditor.Android.PostProcessAndroidPlayer.ShowErrDlgAndThrow (System.String title, System.String message, System.Exception ex)
UnityEditor.Android.PostProcessAndroidPlayer.ShowErrDlgAndThrow (System.String title, System.String message)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcessInternal (BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (BuildPostProcessArgs args)
UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, System.String downloadWebplayerUrl, System.String manualDownloadWebplayerUrl, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:316)
UnityEditor.HostView:OnGUI()

I’ve re-ran setup for Android, no difference, has something become corrupted?

**Comment by Knight2601** [comment]
so my keystore file has died, created a new one which builds.

**Comment by claywilkinson** [comment]
@Knight2601  - sounds like you are up and running?  OK to close this issue?

**Comment by Knight2601** [comment]
h

yeah, i had to rebuild everything then it worked!

cannot get IOS to go to google play, but thats fine as i’ll use Game Center for that.

Thanks

Andy

**Comment by claywilkinson** [comment]
Great, thanks.  I'd be interested in hearing the troubles you had in ios that made you use GameCenter if you have time.  :)
