### ISSUE TITLE
Android game crashes on PlayServicePlatform.Activate()

### ISSUE THREAD

**Issue by QuangSang** [playgameservices/play-games-plugin-for-unity#739]
Hi guys,
I was able to integrate Google Play Services SDK into my Unity game but when I run it and when it gets to the authenticating part, game crashes. 

This is my code to sign in to GPG:
                GooglePlayGames.PlayGamesPlatform.DebugLogEnabled = true;
		GooglePlayGames.PlayGamesPlatform.Activate();
		Social.localUser.Authenticate ((bool success)=>{
			Debug.Log ("LOGGED IN SUCCESSFULLY");
		});

Here is the logcat:

I/Unity   (30255):  [Play Games Plugin DLL] 10/02/15 21:50:48 -07:00 DEBUG: Activating PlayGamesPlatform.
I/Unity   (30255):  
I/Unity   (30255): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   (30255): 
I/Unity   (30255):  [Play Games Plugin DLL] 10/02/15 21:50:48 -07:00 DEBUG: Instance was not initialized, using default configuration.
I/Unity   (30255):  
I/Unity   (30255): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   (30255): 
I/Unity   (30255):  [Play Games Plugin DLL] 10/02/15 21:50:48 -07:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
I/Unity   (30255):  
I/Unity   (30255): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   (30255): 
I/Unity   (30255):  [Play Games Plugin DLL] 10/02/15 21:50:48 -07:00 DEBUG: Creating platform-specific Play Games client.
I/Unity   (30255):  
I/Unity   (30255): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   (30255): 
I/Unity   (30255):  [Play Games Plugin DLL] 10/02/15 21:50:48 -07:00 DEBUG: Creating Android IPlayGamesClient Client
I/Unity   (30255):  
I/Unity   (30255): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   (30255): 
I/Unity   (30255): Building GPG services, implicitly attempts silent auth
I/Unity   (30255):  
I/Unity   (30255): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   (30255): 
I/Unity   (30255):  [Play Games Plugin DLL] 10/02/15 21:50:49 -07:00 DEBUG: Entering state: BeforeRoomCreateStartedState
I/Unity   (30255):  
I/Unity   (30255): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   (30255): 
I/Unity   (30255):  [Play Games Plugin DLL] 10/02/15 21:50:49 -07:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
I/Unity   (30255):  
I/Unity   (30255): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   (30255): 
I/Unity   (30255):  [Play Games Plugin DLL] 10/02/15 21:50:49 -07:00 DEBUG: Entering state: ShutdownState
I/Unity   (30255):  
I/Unity   (30255): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
I/Unity   (30255): 
I/Unity   (30255):  [Play Games Plugin DLL] 10/02/15 21:50:49 -07:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.

Any help on this would be greatly appreciated!

Cheers.

**Comment by QuangSang** [comment]
it seems like it crashes on Social.locaUser.Authenticate(), The process seems to stop at "attempts to silent auth". Any idea, suggestion on this issue?

**Comment by simsis3d** [comment]
I assume you followed all documentation without skipping any step, and there isn't any internal error with plugin version you used==> If you use "Cloud Save" service, please add your accounts to test users in Dashboard(Strongly recommended). Also, your initialization code seems very simple to me. Please use this one in start or awake

    using GooglePlayGames;
    using GooglePlayGames.BasicApi;
    using UnityEngine.SocialPlatforms;

    PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
        // enables saving game progress.
        .EnableSavedGames()
        // registers a callback to handle game invitations received while the game is not running.
        .WithInvitationDelegate(<callback method>)
        // registers a callback for turn based match notifications received while the
        // game is not running.
        .WithMatchDelegate(<callback method>)
        .Build();

    PlayGamesPlatform.InitializeInstance(config);
    // recommended for debugging:
    PlayGamesPlatform.DebugLogEnabled = true;
    // Activate the Google Play Games platform
    PlayGamesPlatform.Activate();

**Comment by QuangSang** [comment]
Solved the issue. There was two versions of google play services existing in the project (6.11 and 8.15). I got rid of 6.11 and it worked :). My signin code was fine btw cuz all I need in GPGS are achievement and leaderboard

**Comment by simsis3d** [comment]
Nice to hear that. You can now close the issue:)

**Comment by claywilkinson** [comment]
@QuangSang  - do you mind sharing how you ended up with two versions?  I think a nice feature would be able to detect that and either fix it or at least print an error.  Thanks!

**Comment by QuangSang** [comment]
@claywilkinson - i just had a bunch of other plugins in the project that used the older version of Google Play Services (idk which one though). so all I did was deleting the "res" folder that contains the older version (6.11 in this case)
