### ISSUE TITLE
Can't connect to room real time

### ISSUE THREAD

**Issue by cuopbjen0o0** [playgameservices/play-games-plugin-for-unity#742]
When I create new quick match and log it,
OnRoomSetupProgress() just call one time in 20% and OnRoomConnected() show connected failed.
When I acept one match, it stop in 20% and fail connection.
Create room with invitation , it still show the default UI Invitation, When I press "Play" ,it call  OnRoomConnected() show connected failed.
I can't find anything to solve this. Help me !
My english is not well.

**Comment by claywilkinson** [comment]
can you post the log of what is happening?

**Comment by cuopbjen0o0** [comment]
Sr, I not down your last version which is solve that problem !
