### ISSUE TITLE
Cannot Authenticate on first call

### ISSUE THREAD

**Issue by pa3kc** [playgameservices/play-games-plugin-for-unity#744]
Cannot Authenticate on first call. I have to call authenticate twice.

**Comment by claywilkinson** [comment]
Can you post the log?  Which version of the plugin are you using?  There was a bug where the callback was being called twice in some situations which was fixed in the latest version.

**Comment by pa3kc** [comment]
It is in Android. I cannot post log yet since I am not in the office. I've downloaded the source yesterday.

I am not able to authenticate on start, it is failing. What I can recall is seeing "implicit silent authentication" then "Unauthenticated". What I have done is to call authenticate again after some delay to have auto sign in every app start.

**Comment by claywilkinson** [comment]
The implicit silent authentication happens on the first call to authenticate. This is a silent authentication attempt, if there are credentials available, they are used, otherwise not.  How are you calling Authenticate?  There is a silent mode that does not show the UI when the implicit call fails.  Are you using that?

**Comment by pa3kc** [comment]
What I can recall is that I've tried:
1. PlayGamesPlatform.Instance.Authenticate()
2. Authenticate(null, false)

Same issue that it doesn't authenticate but if called again via a button, it would work.

**Comment by claywilkinson** [comment]
OK to close this issue?

**Comment by AbreuRodrigo** [comment]
Hey guys, using the GooglePlayGamesPlugin-0.9.27, this is how I'm login in successfully:

PlayGamesPlatform.Instance.Authenticate ((bool success) => {
   //Here goes your success criterias and logics for the callback
});
