### ISSUE TITLE
'GIDSignIn.h' file not found... again

### ISSUE THREAD

**Issue by fcouceiro** [playgameservices/play-games-plugin-for-unity#745]
I've seen #701 and I can't get it to build. I've included it in the pod file too but with no luck. This is the message in xcode:
![error](https://cloud.githubusercontent.com/assets/3154879/10371083/8989e204-6dd9-11e5-8c49-589fabb3a6c0.png)

I've also tried with GoogleSignIn/GIDSignIn.h as explained in #701.

And my pod file looks like this:
![captura de ecra 2015-10-8 as 16 28 24](https://cloud.githubusercontent.com/assets/3154879/10371106/a4480a62-6dd9-11e5-8bb0-f8311584e084.png)

Plugin version is 0.9.25

Unity version is 5.1.3f1.
Any news?

**Comment by fcouceiro** [comment]
FIxed this by removing all folders from Assets regarding this plugin and re-importing.
@claywilkinson this can be closed, I guess.

**Comment by hippogamesunity** [comment]
@fcouceiro Have same issue if setup xcode manually

**Comment by claywilkinson** [comment]
Thanks - Glad you got it working. - We're working on how to upgrade the plugin without having to delete everything and reimport, if you know any tricks, please share :)

**Comment by v2k** [comment]
@fcouceiro can you elaborate on your fix? I'm having the same issue.  I've tried deleting:

`Assets/GooglePlayGames/`
`Assets/PlayServicesResolver/`
etc

and building from Unity to a clean folder, but Xcode still fails on the same error every time.

Plugin 0.9.32
Unity 5.3.4f1

**Comment by richnet** [comment]
@v2k @claywilkinson @fcouceiro I second that request for elaboration. I have deleted the plugin assets and recreated my xcode project and still receive the same error. I suspect a linkage somewhere with the pods file, are you by chance receiving any warnings like this when you do a pod install?

[!] The `Unity-iPhone [Release]` target overrides the `OTHER_CFLAGS` build setting defined in `Pods/Target Support Files/Pods-Unity-iPhone/Pods-Unity-iPhone.release.xcconfig'. This can lead to problems with the CocoaPods installation

**Comment by jonathanleang** [comment]
same error here after updated unity and xcode.

**Comment by fcouceiro** [comment]
Sorry for the delay guys. I don't recall exactly how I've done it. But the main step was to remove all files regarding this library, make sure the game built correctly after that and then reimporting the library. Although the library must have changed a bit since this. Check if it works for you.

**Comment by richnet** [comment]
Once I added **$(inherited)** to the build settings that pod install was complaining about, the reference error went away. I was overthinking it a bit.

**Comment by mgrilloteravisiongames** [comment]
Hi all! I'm having the same problems, fun fact, it happened after the last update, before that when I made pod install I had the following libraries:

GoogleAppUtilities (1.1.0)
GoogleAuthUtilities (2.0.0)
GoogleNetworkingUtilities (1.2.0)
GooglePlayGames (5.1.1)
GooglePlusOpenSource (1.7.1)
GoogleSignIn (3.0.0)
GoogleSymbolUtilities (1.1.0)
GoogleUtilities (1.3.0)

With those dependencies the build was ok, however when I got the following dependencies it fails:

GoogleAppUtilities (1.1.1)
GoogleAuthUtilities (2.0.1)
GoogleNetworkingUtilities (1.2.1)
GooglePlayGames (5.1.1)
GooglePlusOpenSource (1.7.1)
GoogleSignIn (4.0.0)
GoogleSymbolUtilities (1.1.1)
GoogleUtilities (1.3.1)

Is it possible that the last updates generated the problem?

@richnet can you please say where you added the $(inherited) exactly?
