### ISSUE TITLE
Provide examples for LoadFriends

### ISSUE THREAD

**Issue by pikatch** [playgameservices/play-games-plugin-for-unity#746]
I heard that LoadFriends is now implemented, but there is no documentation about it and no examples.  There is also no complete list of what is accessible for localUser and how we can access it. Can you provide informations ?

Thanks

**Comment by claywilkinson** [comment]
Thanks for the feedback!

For friends:

```
Social.localUser.LoadFriends((ok) =>  {
    Debug.Log("Friends loaded OK: " + ok));
    foreach(IUserProfile p in Social.localUser.friends) {
         Debug.Log(p.userName + " is a friend");   
    }   
});
````

Once the friends are loaded once, they are cached, and LoadFriends does not need to be called again.

**Comment by claywilkinson** [comment]
Documentation is updated.
