### ISSUE TITLE
LoadScores ignore Starting Rank range

### ISSUE THREAD

**Issue by eclectyc** [playgameservices/play-games-plugin-for-unity#747]
Hello

I'm trying to get a score at a N rank from a Leaderboard, I thought I could use the "range" property and tried this :

```
var lb = Social.CreateLeaderboard();
lb.id = "LeaderboardID";
lb.range = new Range(N, 1);

lb.LoadScores(result => {
// etc
```

I figured that whatever the value of N it always resulted in the same score...
After some digging until native Cwrapper I found that this property is not used and there is actually 2 options for the starting range (LeaderboardStart type). And it's always "PlayerCentered".

So is there already a way to do what I want ? Is it even possible with google play api ?

**Comment by claywilkinson** [comment]
The Unity Social interface is a simplified interface, so not everything is easily configurable.  For what you want to do I recommend using the PlayGamesPlatform directly as outlined in 
https://github.com/playgameservices/play-games-plugin-for-unity#using-playgamesplatformloadscores

```
  PlayGamesPlatform.Instance.LoadScores(
            GPGSIds.leaderboard_leaders_in_smoketesting,
            LeaderboardStart.PlayerCentered,
            10,
            LeaderboardCollection.TopScores,
            LeaderboardTimeSpan.AllTime,
            (data) =>
            {
                mStatus = "Leaderboard data valid: " + data.Valid;
                mStatus += "\n approx:" +data.ApproximateCount + " have " + data.Scores.Length;
            });
```

You can set the start to LeaderboardCollection.TopScores to get the start as you need.

Depending on "N", you may need to page through scores.

**Comment by eclectyc** [comment]
Thanks for your answer, I will try that way.

But if I understand, I can't directly target a rank or the lowest score (last rank), I'll have to make queries untill I'll reach the lowest by paging it (and how to do it if I always have to start with the top) ? And in case of many entries in the leaderboard I think this will be very slow...

I have to directly target the right N rank or score (it's for ingame score display like they do in Subway Surfers when you're running and reaching some other community score).

**Comment by eclectyc** [comment]
Any other ideas?

**Comment by claywilkinson** [comment]
There is not any other way.  There is a way to get scores around the current player's scores, so maybe a combination of something like get the top 10 scores, and then the 10 scores around the player.
