### ISSUE TITLE
"AndroidJavaProxy" could not be found. 

### ISSUE THREAD

**Issue by fcouceiro** [playgameservices/play-games-plugin-for-unity#750]
When I try to build for iOS I get this error, after using the trick in #748 ,with the latest plugin:
`The type or namespace name "AndroidJavaProxy" could not be found. Are you missing a using directive or an assembly reference?`

Happened in a blank project.

**Comment by fcouceiro** [comment]
Found a solution. All scripts in GooglePlayGames/Platforms/Android and subfolders should have a #if UNITY_ANDROID flag set, to avoid being compiled when building for iOS.

**Comment by claywilkinson** [comment]
thanks for the solution.

**Comment by Ddfh** [comment]
@claywilkinson Hi. Please, I have another simple question. How can I self, build this google play game services plugin for unity? 

I want to export GooglePlayServices, BaseGameUtils and this plugin.

Is there a tutorial for that?

**Comment by claywilkinson** [comment]
The package is updated with the proper #if UNITY_ANDROID in place.

@Ddfh  - you can build the plugin by cloning the project, then opening a command prompt in the source directory.

There is a build.gradle file that is used to do the build.  run ./gradlew  (with no arguments) to build the packages.

You will need the android SDK, the NDK, and of course Unity.
Please open an new issue if you have problems building.
