### ISSUE TITLE
Turn based game.How to avoid player take turn multiple times?

### ISSUE THREAD

**Issue by ntragas** [playgameservices/play-games-plugin-for-unity#751]
Hello i have been working on a turn based game for some time now and i decided to use google play game services to make it online.So far everything works very good but i have some questions.
Lets say every player has to make 5 moves on his turn,and then passses his turn to next player.
When the player accepts his turn he starts playing,but if he does only 3 moves close the game go to google play games and accept the invite again he resets his moves and starts all over.
1)Is there any way to inform other players that the player started playing his move and not be able to reset it somehow?

**Comment by ntragas** [comment]
Ok i ve done some more testing.I created a whole new project because i thought that i forgot to check something.This time i used the original tic tac toe package from  github.
If you play it yourself you can see that if a player is invited he can sling a box and just before the turn is finished if he dont like the result he can close the app with the home button(bring it to the ackground) then open google play games and accept the invite again and play his move until he likes the results.Please tell me how to fix this,it is a bug for sure.How can i be the only one seeing this :( ..

**Comment by ntragas** [comment]
Any help ?!?

**Comment by ntragas** [comment]
Still noone answered me maybe i have to ask in a different forum but were?

**Comment by claywilkinson** [comment]
I thought you did: http://stackoverflow.com/questions/33132094/google-play-games-turn-based-bug-or-feature.   In short, it is working as designed.
