### ISSUE TITLE
Building Fail

### ISSUE THREAD

**Issue by luismetmx** [playgameservices/play-games-plugin-for-unity#752]
I have this error using Google Play Games services package for unity i used version 0.9.26.

Could any one please help me?

Thank you so much.

CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/desarrollo1/Desktop/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity 5.2/Unity 5.2.app/Contents/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/desarrollo1/Desktop/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity 5.2/Unity 5.2.app/Contents/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

**Comment by claywilkinson** [comment]
The console should have another message that contains more specific information.  A common thing to miss is running Setup for the plugin  in Window > Google Play Games > Setup > Android Setup.

**Comment by luismetmx** [comment]
The console has de following:

CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/desarrollo1/Desktop/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity 5.2/Unity 5.2.app/Contents/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.gifting.d) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.gifting.c) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.gifting.f) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.gifting.e) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.gifting.h) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.gifting.g) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.highway.c) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.highway.d) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.highway.e) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.highway.f) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.highway.g) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.highway.h) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.highway.i) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.highway.m) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.highway.a.b) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.highway.b.e) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.insights.c) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.insights.b) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.leaderboards.b) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.leaderboards.a) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.sync.a) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.sync.b) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.sync.e) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.sync.g) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.sync.f) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.sync.h) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.sync.i) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.sync.j) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.sync.k) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.soomla.sync.l) that doesn't come with an
associated EnclosingMethod attribute. This class wa<message truncated>

**Comment by luismetmx** [comment]
stderr[

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Landroid/support/v4/util/TimeUtils;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at SDKMain.main(SDKMain.java:129)
1 error; aborting
]
stdout[
processing archive bin/classes.jar...
processing com/unity3d/player/a$1.class...
processing com/unity3d/player/a$2.class...
processing com/unity3d/player/a$a.class...
processing com/unity3d/player/a.class...
processing com/unity3d/player/b$1.class...
processing com/unity3d/player/b$2.class...
processing com/unity3d/player/b.class...
processing com/unity3d/player/c.class...
processing com/unity3d/player/d$1.class...
processing com/unity3d/player/d$2.class...
processing com/unity3d/player/d.class...
processing com/unity3d/player/e.class...
processing com/unity3d/player/f.class...
processing com/unity3d/player/g.class...
processing com/unity3d/player/h.class...
processing com/unity3d/player/i.class...
processing com/unity3d/player/j$1.class...
processing com/unity3d/player/j$2$1$1.class...
processing com/unity3d/player/j$2$1.class...
processing com/unity3d/player/j$2.class...
processing com/unity3d/player/j.class...
processing com/unity3d/player/k$1.class...
processing com/unity3d/player/k.class...
processing com/unity3d/player/l.class...
processing com/unity3d/player/m.class...
processing com/unity3d/player/n$1.class...
processing com/unity3d/player/n.class...
processing com/unity3d/player/NativeLoader.class...
processing com/unity3d/player/o.class...
processing com/unity3d/player/ReflectionHelper$1.class...
processing com/unity3d/player/ReflectionHelper$a.class...
processing com/unity3d/player/ReflectionHelper.class...
processing com/unity3d/player/p.class...
processing com/unity3d/player/q$1.class...
processing com/unity3d/player/q$2.class...
processing com/unity3d/player/q$3.class...
processing com/unity3d/player/q.class...
processing com/unity3d/player/r.class...
processing com/unity3d/player/s.class...
processing com/unity3d/player/UnityPlayer$1.class...
processing com/unity3d/player/UnityPlayer$2.class...
processing com/unity3d/player/UnityPlayer$4.class...
processing com/unity3d/player/UnityPlayer$5.class...
processing com/unity3d/player/UnityPlayer$6.class...
processing com/unity3d/player/UnityPlayer$7.class...
processing com/unity3d/player/UnityPlayer$8.class...
processing com/unity3d/player/UnityPlayer$9.class...
processing com/unity3d/player/UnityPlayer$10.class...
processing com/unity3d/player/UnityPlayer$11.class...
processing com/unity3d/player/UnityPlayer$12.class...
processing com/unity3d/player/UnityPlayer$13$1.class...
processing com/unity3d/player/UnityPlayer$13.class...
processing com/unity3d/player/UnityPlayer$3.class...
processing com/unity3d/player/UnityPlayer$14.class...
processing com/unity3d/player/UnityPlayer$15.class...
processing com/unity3d/player/UnityPlayer$16.class...
processing com/unity3d/player/UnityPlayer$17.class...
processing com/unity3d/player/UnityPlayer$18.class...
processing com/unity3d/player/UnityPlayer$19.class...
processing com/unity3d/player/UnityPlayer$a.class...
processing com/unity3d/player/UnityPlayer$b.class...
processing com/unity3d/player/UnityPlayer$c.class...
processing com/unity3d/player/UnityPlayer.class...
processing com/unity3d/player/UnityPlayerActivity.class...
processing com/unity3d/player/UnityPlayerNativeActivity.class...
processing com/unity3d/player/UnityPlayerProxyActivity.class...
processing com/unity3d/player/t.class...
processing com/unity3d/player/u$1.class...
processing com/unity3d/player/u.class...
processing com/unity3d/player/WWW.class...
processing org/fmod/FMODAudioDevice.class...
processing org/fmod/a.class...
processing bitter/jnibridge/JNIBridge$a.class...
processing bitter/jnibridge/JNIBridge.class...
processing bin/classes/./com/facebook/android/R$attr.class...
processing bin/classes/./com/facebook/android/R$color.class...
processing bin/classes/./com/facebook/android/R$dimen.class...
processing bin/classes/./com/facebook/android/R$drawable.class...
processing bin/classes/./com/facebook/android/R$id.class...
processing bin/classes/./com/facebook/android/R$integer.class...
processing bin/classes/./com/facebook/android/R$layout.class...
processing bin/classes/./com/facebook/android/R$raw.class...
processing bin/classes/./com/facebook/android/R$string.class...
processing bin/classes/./com/facebook/android/R$style.class...
processing bin/classes/./com/facebook/android/R$styleable.class...
processing bin/classes/./com/facebook/android/R.class...
processing bin/classes/./com/google/android/gms/R$attr.class...
processing bin/classes/./com/google/android/gms/R$color.class...
processing bin/classes/./com/google/android/gms/R$dimen.class...
processing bin/classes/./com/google/android/gms/R$drawable.class...
processing bin/classes/./com/google/android/gms/R$id.class...
processing bin/classes/./com/google/android/gms/R$integer.class...
processing bin/classes/./com/google/android/gms/R$layout.class...
processing bin/classes/./com/google/android/gms/R$raw.class...
processing bin/classes/./com/google/android/gms/R$string.class...
processing bin/classes/./com/google/android/gms/R$style.class...
processing bin/classes/./com/google/android/gms/R$styleable.class...
processing bin/classes/./com/google/android/gms/R.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$attr.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$color.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$dimen.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$drawable.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$id.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$integer.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$layout.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$raw.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$string.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$style.class...
processing bin/classes/./com/google/example/games/mainlibproj/R$styleable.class...
processing bin/classes/./com/google/example/games/mainlibproj/R.class...
processing bin/classes/./com/vgim/lord/R$attr.class...
processing bin/classes/./com/vgim/lord/R$color.class...
processing bin/classes/./com/vgim/lord/R$dimen.class...
processing bin/classes/./com/vgim/lord/R$drawable.class...
processing bin/classes/./com/vgim/lord/R$id.class...
processing bin/classes/./com/vgim/lord/R$integer.class...
processing bin/classes/./com/vgim/lord/R$layout.class...
processing bin/classes/./com/vgim/lord/R$raw.class...
processing bin/classes/./com/vgim/lord/R$string.class...
processing bin/classes/./com/vgim/lord/R$style.class...
processing bin/classes/./com/vgim/lord/R$styleable.class...
processing bin/classes/./com/vgim/lord/R.class...
processing archive plugins/./android-support-v4.jar...
ignored resource META-INF/MANIFEST.MF
processing android/support/annotation/AttrRes.class...
processing android/support/annotation/CallSuper.class...
processing android/support/annotation/IdRes.class...
processing android/support/annotation/BoolRes.class...
processing android/support/annotation/Size.class...
processing android/support/annotation/DrawableRes.class...
processing android/support/annotation/MainThread.class...
processing android/support/annotation/StringRes.class...
processing android/support/annotation/TransitionRes.class...
processing android/support/annotation/WorkerThread.class...
processing android/support/annotation/StyleRes.class...
processing android/support/annotation/RequiresPermission.class...
processing android/support/annotation/DimenRes.class...
processing android/support/annotation/RequiresPermission$Write.class...
processing android/support/annotation/CheckResult.class...
processing android/support/annotation/NonNull.class...
processing android/support/annotation/XmlRes.class...
processing android/support/annotation/StyleableRes.class...
processing android/support/annotation/Keep.class...
processing android/support/annotation/UiThread.class...
processing android/support/annotation/RequiresPermission$Read.class...
processing android/support/annotation/IntRange.class...
processing android/support/annotation/BinderThread.class...
processing android/support/annotation/LayoutRes.class...
processing android/support/annotation/IntDef.class...
processing android/support/annotation/MenuRes.class...
processing android/support/annotation/AnimRes.class...
processing android/support/annotation/ColorInt.class...
processing android/support/annotation/FloatRange.class...
processing android/support/annotation/FractionRes.class...
processing android/support/annotation/StringDef.class...
processing android/support/annotation/RawRes.class...
processing android/support/annotation/Nullable.class...
processing android/support/annotation/AnyRes.class...
processing android/support/annotation/PluralsRes.class...
processing android/support/annotation/ColorRes.class...
processing android/support/annotation/VisibleForTesting.class...
processing android/support/annotation/AnimatorRes.class...
processing android/support/annotation/ArrayRes.class...
processing android/support/annotation/IntegerRes.class...
processing android/support/annotation/InterpolatorRes.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompatJellyBeanMr2.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoJellyBeanMr2.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl.class...
processing android/support/v4/print/PrintHelper.class...
processing android/support/v4/print/PrintHelper$PrintHelperStubImpl.class...
processing android/support/v4/print/PrintHelperKitkat.class...
processing android/support/v4/print/PrintHelperKitkat$OnPrintFinishCallback.class...
processing android/support/v4/print/PrintHelper$PrintHelperVersionImpl.class...
processing android/support/v4/print/PrintHelper$PrintHelperKitkatImpl.class...
processing android/support/v4/print/PrintHelper$PrintHelperKitkatImpl$2.class...
processing android/support/v4/print/PrintHelper$1.class...
processing android/support/v4/print/PrintHelper$OnPrintFinishCallback.class...
processing android/support/v4/print/PrintHelperKitkat$2$1.class...
processing android/support/v4/print/PrintHelperKitkat$2.class...
processing android/support/v4/print/PrintHelper$PrintHelperKitkatImpl$1.class...
processing android/support/v4/print/PrintHelperKitkat$1.class...
processing android/support/v4/print/PrintHelperKitkat$2$1$1.class...
processing android/support/v4/animation/AnimatorUpdateListenerCompat.class...
processing android/support/v4/animation/HoneycombMr1AnimatorCompatProvider$HoneycombValueAnimatorCompat$1.class...
processing android/support/v4/animation/HoneycombMr1AnimatorCompatProvider$HoneycombValueAnimatorCompat.class...
processing android/support/v4/animation/HoneycombMr1AnimatorCompatProvider$AnimatorListenerCompatWrapper.class...
processing android/support/v4/animation/ValueAnimatorCompat.class...
processing android/support/v4/animation/AnimatorProvider.class...
processing android/support/v4/animation/HoneycombMr1AnimatorCompatProvider.class...
processing android/support/v4/animation/AnimatorCompatHelper.class...
processing android/support/v4/animation/DonutAnimatorCompatProvider$DonutFloatValueAnimator.class...
processing android/support/v4/animation/DonutAnimatorCompatProvider.class...
processing android/support/v4/animation/DonutAnimatorCompatProvider$DonutFloatValueAnimator$1.class...
processing android/support/v4/animation/AnimatorListenerCompat.class...
processing android/support/v4/media/TransportMediatorCallback.class...
processing android/support/v4/media/TransportStateListener.class...
processing android/support/v4/media/routing/MediaRouterJellybean$CallbackProxy.class...
processing android/support/v4/media/routing/MediaRouterJellybeanMr1$RouteInfo.class...
processing android/support/v4/media/routing/MediaRouterJellybean$RouteCategory.class...
processing android/support/v4/media/routing/MediaRouterJellybeanMr2$UserRouteInfo.class...
processing android/support/v4/media/routing/MediaRouterJellybean$GetDefaultRouteWorkaround.class...
processing android/support/v4/media/routing/MediaRouterJellybean$VolumeCallbackProxy.class...
processing android/support/v4/media/routing/MediaRouterJellybean$UserRouteInfo.class...
processing android/support/v4/media/routing/MediaRouterJellybean.class...
processing android/support/v4/media/routing/MediaRouterJellybean$Callback.class...
processing android/support/v4/media/routing/MediaRouterJellybean$VolumeCallback.class...
processing android/support/v4/media/routing/MediaRouterJellybeanMr2.class...
processing android/support/v4/media/routing/MediaRouterJellybeanMr1$IsConnectingWorkaround.class...
processing android/support/v4/media/routing/MediaRouterJellybean$RouteInfo.class...
processing android/support/v4/media/routing/MediaRouterJellybeanMr2$RouteInfo.class...
processing android/support/v4/media/routing/MediaRouterJellybean$SelectRouteWorkaround.class...
processing android/support/v4/media/routing/MediaRouterJellybeanMr1$Callback.class...
processing android/support/v4/media/routing/MediaRouterJellybeanMr1$ActiveScanWorkaround.class...
processing android/support/v4/media/routing/MediaRouterJellybean$RouteGroup.class...
processing android/support/v4/media/routing/MediaRouterJellybeanMr1.class...
processing android/support/v4/media/routing/MediaRouterJellybeanMr1$CallbackProxy.class...

**Comment by claywilkinson** [comment]
This usually means there is a jar or a set of classes being included multiple times.  Maybe check all the jar files being included that there are no duplicates.

**Comment by claywilkinson** [comment]
@luismetmx  - Please reopen an issue if this is still a problem.
