### ISSUE TITLE
Unity 5 doesn't replace the files while upgrading

### ISSUE THREAD

**Issue by AGArtStore** [playgameservices/play-games-plugin-for-unity#753]
Unity 5 doesn't replace the files while upgrading
I was trying to upgrade from v9.11 to v9.25.
but I think you will need to update the upgrade instructions as Unity 5 doesn't replace the files.
instead Unity adds the files with a number as a suffix to the original file name.

**Comment by claywilkinson** [comment]
Yes, it is unfortunate it is difficult to update files.  The best solution is to delete the Assets/GooglePlayGames and Assets/Plugins directories and import the new package.

Which instructions are are you referring to?  At the top of UPGRADING.txt it says, [If you have already integrated the plugin and want to upgrade it to a newer version,
you must delete the Assets/GooglePlayGames folder, then import the new package.](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/UPGRADING.txt#L3)

**Comment by AGArtStore** [comment]
Many thanks for pointing it out and for your prompt response. 
I had problems with the files in the plugins folder as well. I can't regenerate the case but I remember I had to re-import the old version to check what are the files exactly to delete even after following the instructions. 
may be just adding a list of the files / folders to delete in the upgrade instructions may help.

Kind Regards,

**Comment by claywilkinson** [comment]
Thanks for the suggestion.  The problem with lists like that is they seem to get out of date very quickly.  Probably the best solution is to create a new empty project and import the plugin, then generate a list of files from that project.

**Comment by claywilkinson** [comment]
The latest version of the plugin has improved .meta data file handling, so if you start with a clean import of the plugin, all future versions of the plugin should not create duplicates.

**Comment by AGArtStore** [comment]
Great .. Thank you .
