### ISSUE TITLE
V9.25 compitability with Google Analytics

### ISSUE THREAD

**Issue by AGArtStore** [playgameservices/play-games-plugin-for-unity#754]
I was working with both plugins for unity. but when I tried to upgrade from v9.11 to v9.25,
after the upgrade it's producing some compilation errors while building the apk ... specifically in the conversation process from .class to dex file format
I'm also using Adcoloney and Soomla if this can affect ..

the error is gone when I delete the file "libGoogleAnalyticsServices.jar" .... but off course GA doesn't work then

I've also reported this issue to their github thread.
https://github.com/googleanalytics/google-analytics-plugin-for-unity/issues/75
 
here are the logs I got in the unity console:

CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:\Program Files\Java\jdk1.8.0_11\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Program Files (x86)/Android/android-sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\androidplayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/internal/Command;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/internal/Command$1;
2 errors; aborting
]
stdout[
processing archive bin\classes.jar...
processing com/unity3d/player/a$1.class...
processing com/unity3d/player/a$2.class...
processing com/unity3d/player/a$a.class...
processing com/unity3d/player/a.class...
processing com/unity3d/player/b$1.class...
processing com/unity3d/player/b$2.class...
processing com/unity3d/player/b.class...
processing com/unity3d/player/c.class...
processing com/unity3d/player/d$1.class...
processing com/unity3d/player/d$2.class...
processing com/unity3d/player/d.class...
processing com/unity3d/player/e.class...
processing com/unity3d/player/f.class...
processing com/unity3d/player/g.class...
processing com/unity3d/player/h.class...
processing com/unity3d/player/i.class...
processing com/unity3d/player/j$1.class...
processing com/unity3d/player/j$2$1$1.class...
processing com/unity3d/player/j$2$1.class...
processing com/unity3d/player/j$2.class...
processing com/unity3d/player/j.class...
processing com/unity3d/player/k$1.class...
processing com/unity3d/player/k.class...
processing com/unity3d/player/l.class...
processing com/unity3d/player/m.class...
processing com/unity3d/player/n$1.class...
processing com/unity3d/player/n.class...
processing com/unity3d/player/NativeLoader.class...
processing com/unity3d/player/o.class...
processing com/unity3d/player/ReflectionHelper$1.class...
processing com/unity3d/player/ReflectionHelper$a.class...
processing com/unity3d/player/ReflectionHelper.class...
processing com/unity3d/player/p.class...
processing com/unity3d/player/q$1.class...
processing com/unity3d/player/q$2.class...
processing com/unity3d/player/q$3.class...
processing com/unity3d/player/q.class...
processing com/unity3d/player/r.class...
processing com/unity3d/player/s.class...
processing com/unity3d/player/UnityPlayer$1.class...
processing com/unity3d/player/UnityPlayer$2.class...
processing com/unity3d/player/UnityPlayer$4.class...
processing com/unity3d/player/UnityPlayer$5.class...
processing com/unity3d/player/UnityPlayer$6.class...
processing com/unity3d/player/UnityPlayer$7.class...
processing com/unity3d/player/UnityPlayer$8.class...
processing com/unity3d/player/UnityPlayer$9.class...
processing com/unity3d/player/UnityPlayer$10.class...
processing com/unity3d/player/UnityPlayer$11.class...
processing com/unity3d/player/UnityPlayer$12.class...
processing com/unity3d/player/UnityPlayer$13$1.class...
processing com/unity3d/player/UnityPlayer$13.class...
processing com/unity3d/player/UnityPlayer$3.class...
processing com/unity3d/player/UnityPlayer$14.class...
processing com/unity3d/player/UnityPlayer$15.class...
processing com/unity3d/player/UnityPlayer$16.class...
processing com/unity3d/player/UnityPlayer$17.class...
processing com/unity3d/player/UnityPlayer$18.class...
processing com/unity3d/player/UnityPlayer$19.class...
processing com/unity3d/player/UnityPlayer$a.class...
processing com/unity3d/player/UnityPlayer$b.class...
processing com/unity3d/player/UnityPlayer$c.class...
processing com/unity3d/player/UnityPlayer.class...
processing com/unity3d/player/UnityPlayerActivity.class...
processing com/unity3d/player/UnityPlayerNativeActivity.class...
processing com/unity3d/player/UnityPlayerProxyActivity.class...
processing com/unity3d/player/t.class...
processing com/unity3d/player/u$1.class...
processing com/unity3d/player/u.class...
processing com/unity3d/player/WWW.class...
processing org/fmod/FMODAudioDevice.class...
processing org/fmod/a.class...
processing bitter/jnibridge/JNIBridge$a.class...
processing bitter/jnibridge/JNIBridge.class...
processing bin\classes.\com\AGGameStdio\PenFight\R$attr.class...
processing bin\classes.\com\AGGameStdio\PenFight\R$color.class...
processing bin\classes.\com\AGGameStdio\PenFight\R$drawable.class...
processing bin\classes.\com\AGGameStdio\PenFight\R$id.class...
processing bin\classes.\com\AGGameStdio\PenFight\R$integer.class...
processing bin\classes.\com\AGGameStdio\PenFight\R$raw.class...
processing bin\classes.\com\AGGameStdio\PenFight\R$string.class...
processing bin\classes.\com\AGGameStdio\PenFight\R$style.class...
processing bin\classes.\com\AGGameStdio\PenFight\R$styleable.class...
processing bin\classes.\com\AGGameStdio\PenFight\R.class...
processing bin\classes.\com\google\android\gms\R$attr.class...
processing bin\classes.\com\google\android\gms\R$color.class...
processing bin\classes.\com\google\android\gms\R$drawable.class...
processing bin\classes.\com\google\android\gms\R$id.class...
processing bin\classes.\com\google\android\gms\R$integer.class...
processing bin\classes.\com\google\android\gms\R$raw.class...
processing bin\classes.\com\google\android\gms\R$string.class...
processing bin\classes.\com\google\android\gms\R$style.class...
processing bin\classes.\com\google\android\gms\R$styleable.class...
processing bin\classes.\com\google\android\gms\R.class...
processing bin\classes.\com\google\example\games\mainlibproj\R$attr.class...
processing bin\classes.\com\google\example\games\mainlibproj\R$color.class...
processing bin\classes.\com\google\example\games\mainlibproj\R$drawable.class...
processing bin\classes.\com\google\example\games\mainlibproj\R$id.class...
processing bin\classes.\com\google\example\games\mainlibproj\R$integer.class...
processing bin\classes.\com\google\example\games\mainlibproj\R$raw.class...
processing bin\classes.\com\google\example\games\mainlibproj\R$string.class...
processing bin\classes.\com\google\example\games\mainlibproj\R$style.class...
processing bin\classes.\com\google\example\games\mainlibproj\R$styleable.class...
processing bin\classes.\com\google\example\games\mainlibproj\R.class...
processing archive plugins.\adcolony.jar...
ignored resource META-INF/MANIFEST.MF
processing com/immersion/content/EndpointWarp.class...
processing com/immersion/content/HapticHeaderUtils.class...
processing com/immersion/content/HeaderUtils.class...
processing com/immersion/content/Log.class...
processing com/immersion/hapticmediasdk/controllers/FileReaderFactory.class...
processing com/immersion/hapticmediasdk/controllers/HapticDownloadThread.class...
processing com/immersion/hapticmediasdk/controllers/HapticPlaybackThread.class...
processing com/immersion/hapticmediasdk/controllers/IHapticFileReader.class...
processing com/immersion/hapticmediasdk/controllers/ImmersionHttpClient.class...
processing com/immersion/hapticmediasdk/controllers/MediaController.class...
processing com/immersion/hapticmediasdk/controllers/MemoryAlignedFileReader.class...
processing com/immersion/hapticmediasdk/controllers/MemoryMappedFileReader.class...
processing com/immersion/hapticmediasdk/HapticContentSDK$SDKStatus.class...
processing com/immersion/hapticmediasdk/HapticContentSDK.class...
processing com/immersion/hapticmediasdk/HapticContentSDKFactory.class...
processing com/immersion/hapticmediasdk/HapticMediaSDKVersion.class...
processing com/immersion/hapticmediasdk/MediaPlaybackSDK.class...
processing com/immersion/hapticmediasdk/MediaTaskManager.class...
processing com/immersion/hapticmediasdk/models/BeyondHapticDataException.class...
processing com/immersion/hapticmediasdk/models/HapticFileInformation$Builder.class...
processing com/immersion/hapticmediasdk/models/HapticFileInformation.class...
processing com/immersion/hapticmediasdk/models/HttpUnsuccessfulException.class...
processing com/immersion/hapticmediasdk/models/NotEnoughHapticBytesAvailableException.class...
processing com/immersion/hapticmediasdk/utils/FileManager.class...
processing com/immersion/hapticmediasdk/utils/Log.class...
processing com/immersion/hapticmediasdk/utils/Profiler.class...
processing com/immersion/hapticmediasdk/utils/RuntimeInfo.class...
processing com/jirbo/adcolony/a$a.class...
processing com/jirbo/adcolony/a$b.class...
processing com/jirbo/adcolony/a.class...
processing com/jirbo/adcolony/b$1.class...
processing com/jirbo/adcolony/b.class...
processing com/jirbo/adcolony/c.class...
processing com/jirbo/adcolony/d$1.class...
processing com/jirbo/adcolony/d$2.class...
processing com/jirbo/adcolony/d$3.class...
processing com/jirbo/adcolony/d$4.class...
processing com/jirbo/adcolony/d$5.class...
processing com/jirbo/adcolony/d$6.class...
processing com/jirbo/adcolony/d$7.class...
processing com/jirbo/adcolony/d$8.class...
processing com/jirbo/adcolony/d.class...
processing com/jirbo/adcolony/e$1.class...
processing com/jirbo/adcolony/e$2.class...
processing com/jirbo/adcolony/e$3.class...
processing com/jirbo/adcolony/e$4$1.class...
processing com/jirbo/adcolony/e$4.class...
processing com/jirbo/adcolony/e$5.class...
processing com/jirbo/adcolony/e$6.class...
processing com/jirbo/adcolony/e.class...
processing com/jirbo/adcolony/ADCData$a.class...
processing com/jirbo/adcolony/ADCData$b.class...
processing com/jirbo/adcolony/ADCData$c.class...
processing com/jirbo/adcolony/ADCData$d.class...
processing com/jirbo/adcolony/ADCData$e.class...
processing com/jirbo/adcolony/ADCData$f.class...
processing com/jirbo/adcolony/ADCData$g.class...
processing com/jirbo/adcolony/ADCData$h.class...
processing com/jirbo/adcolony/ADCData$i.class...
processing com/jirbo/adcolony/ADCData.class...
processing com/jirbo/adcolony/f.class...
processing com/jirbo/adcolony/g.class...
processing com/jirbo/adcolony/h.class...
processing com/jirbo/adcolony/i.class...
processing com/jirbo/adcolony/ADCDownload$Listener.class...
processing com/jirbo/adcolony/ADCDownload.class...
processing com/jirbo/adcolony/j.class...
processing com/jirbo/adcolony/ADCImage.class...
processing com/jirbo/adcolony/k.class...
processing com/jirbo/adcolony/l.class...
processing com/jirbo/adcolony/n$a.class...
processing com/jirbo/adcolony/n$d.class...
processing com/jirbo/adcolony/n$b.class...
processing com/jirbo/adcolony/n$c.class...
processing com/jirbo/adcolony/n$e.class...
processing com/jirbo/adcolony/n$f.class...
processing com/jirbo/adcolony/n$g.class...
processing com/jirbo/adcolony/n$h.class...
processing com/jirbo/adcolony/n$i.class...
processing com/jirbo/adcolony/n$k.class...
processing com/jirbo/adcolony/n$j.class...
processing com/jirbo/adcolony/n$l.class...
processing com/jirbo/adcolony/n$m.class...
processing com/jirbo/adcolony/n$n.class...
processing com/jirbo/adcolony/n$o.class...
processing com/jirbo/adcolony/n$p.class...
processing com/jirbo/adcolony/n$q.class...
processing com/jirbo/adcolony/n$r.class...
processing com/jirbo/adcolony/n$s.class...
processing com/jirbo/adcolony/n$t.class...
processing com/jirbo/adcolony/n$u.class...
processing com/jirbo/adcolony/n$v.class...
processing com/jirbo/adcolony/n$w.class...
processing com/jirbo/adcolony/n$x.class...
processing com/jirbo/adcolony/n$y.class...
processing com/jirbo/adcolony/n$z.class...
processing com/jirbo/adcolony/n$aa.class...
processing com/jirbo/adcolony/n$ab.class...
processing com/jirbo/adcolony/n$ae.class...
processing com/jirbo/adcolony/n$ac.class...
processing com/jirbo/adcolony/n$ad.class...
processing com/jirbo/adcolony/n.class...
processing com/jirbo/adcolony/o$a.class...
processing com/jirbo/adcolony/o.class...
processing com/jirbo/adcolony/p$a.class...
processing com/jirbo/adcolony/p.class...
processing com/jirbo/adcolony/m$1.class...
processing com/jirbo/adcolony/m$2.class...
processing com/jirbo/adcolony/m.class...
processing com/jirbo/adcolony/q.class...
processing com/jirbo/adcolony/AdColony$1.class...
processing com/jirbo/adcolony/AdColony$2$1.class...
processing com/jirbo/adcolony/AdColony$2.class...
processing com/jirbo/adcolony/AdColony$a.class...
processing com/jirbo/adcolony/AdColony.class...
processing com/jirbo/adcolony/AdColonyAd.class...
processing com/jirbo/adcolony/AdColonyAdAvailabilityListener.class...
processing com/jirbo/adcolony/AdColonyAdListener.class...
processing com/jirbo/adcolony/AdColonyBrowser$1.class...
processing com/jirbo/adcolony/AdColonyBrowser$2.class...
processing com/jirbo/adcolony/AdColonyBrowser$a.class...
processing com/jirbo/adcolony/AdColonyBrowser$b.class...
processing com/jirbo/adcolony/AdColonyBrowser$c.class...
processing com/jirbo/adcolony/AdColonyBrowser.class...
processing com/jirbo/adcolony/AdColonyException.class...
processing com/jirbo/adcolony/AdColonyFullscreen.class...
processing com/jirbo/adcolony/AdColonyIAPEngagement.class...
processing com/jirbo/adcolony/AdColonyInterstitialAd$1.class...
processing com/jirbo/adcolony/AdColonyInterstitialAd$2.class...
processing com/jirbo/adcolony/AdColonyInterstitialAd.class...
processing com/jirbo/adcolony/AdColonyNativeAdListener.class...
processing com/jirbo/adcolony/AdColonyNativeAdMutedListener.class...
processing com/jirbo/adcolony/AdColonyNativeAdView$1.class...
processing com/jirbo/adcolony/AdColonyNativeAdView$2.class...
processing com/jirbo/adcolony/AdColonyNativeAdView$a$1.class...
processing com/jirbo/adcolony/AdColonyNativeAdView$a.class...
processing com/jirbo/adcolony/AdColonyNativeAdView$b.class...
processing com/jirbo/adcolony/AdColonyNativeAdView.class...
processing com/jirbo/adcolony/AdColonyOverlay$1.class...
processing com/jirbo/adcolony/AdColonyOverlay.class...
processing com/jirbo/adcolony/AdColonyV4VCAd$1.class...
processing com/jirbo/adcolony/AdColonyV4VCAd$2.class...
processing com/jirbo/adcolony/AdColonyV4VCAd.class...
processing com/jirbo/adcolony/AdColonyV4VCListener.class...
processing com/jirbo/adcolony/AdColonyV4VCReward.class...
processing com/jirbo/adcolony/AdColonyVideoAd.class...
processing com/jirbo/adcolony/AdColonyVideoDialog.class...
processing com/jirbo/adcolony/s.class...
processing com/jirbo/adcolony/t$a.class...
processing com/jirbo/adcolony/t.class...
processing com/jirbo/adcolony/u$a.class...
processing com/jirbo/adcolony/u.class...
processing com/jirbo/adcolony/v.class...
processing com/jirbo/adcolony/w.class...
processing com/jirbo/adcolony/ADCStorage.class...
processing com/jirbo/adcolony/x.class...
processing com/jirbo/adcolony/y.class...
processing com/jirbo/adcolony/z.class...
processing com/jirbo/adcolony/aa$a.class...
processing com/jirbo/adcolony/aa.class...
processing com/jirbo/adcolony/ab$a.class...
processing com/jirbo/adcolony/ab$b.class...
processing com/jirbo/adcolony/ab.class...
processing com/jirbo/adcolony/ac.class...
processing com/jirbo/adcolony/ad.class...
processing com/jirbo/adcolony/ADCVideo$1.class...
processing com/jirbo/adcolony/ADCVideo$2.class...
processing com/jirbo/adcolony/ADCVideo$3.class...
processing com/jirbo/adcolony/ADCVideo$a.class...
processing com/jirbo/adcolony/ADCVideo.class...
processing com/jirbo/adcolony/ae$1.class...
processing com/jirbo/adcolony/ae$2.class...
processing com/jirbo/adcolony/ae$3.class...
processing com/jirbo/adcolony/ae$4.class...
processing com/jirbo/adcolony/ae$5.class...
processing com/jirbo/adcolony/ae$6.class...
processing com/jirbo/adcolony/ae$7.class...
processing com/jirbo/adcolony/ae$8.class...
processing com/jirbo/adcolony/ae$9.class...
processing com/jirbo/adcolony/ae$a.class...
processing com/jirbo/adcolony/ae$b.class...
processing com/jirbo/adcolony/ae.class...
processing com/jirbo/adcolony/af.class...
processing com/jirbo/adcolony/ag.class...
processing com/jirbo/adcolony/ah.class...
processing com/jirbo/adcolony/ai.class...
processing com/jirbo/adcolony/BuildConfig.class...
processing com/jirbo/adcolony/aj.class...
processing com/jirbo/adcolony/R$anim.class...
processing com/jirbo/adcolony/R$attr.class...
processing com/jirbo/adcolony/R$layout.class...
processing com/jirbo/adcolony/R$string.class...
processing com/jirbo/adcolony/R.class...
processing rrrrrr/cccrrr.class...
processing rrrrrr/ccrcrr.class...
processing rrrrrr/ccrrrr.class...
processing rrrrrr/crccrr.class...
proces

**Comment by claywilkinson** [comment]
Thanks for the details - We're working on a solution.

**Comment by Renato-Malachite** [comment]
anything? Im getting this error :(

**Comment by sanmn19** [comment]
Hi. The solution to this is quite simple. Just open the Google play games jar using winrar and delete the conflicting package.

**Comment by AGArtStore** [comment]
Hi, Thanks for getting back and pointing this out. this should be good enough to deal with it for now. 
if there's no better solution though, can you add this comment to the instructions or the documentation ?
R,

**Comment by claywilkinson** [comment]
The plugins now coordinate the dependencies via the Play Services jar resolver.
