### ISSUE TITLE
Unity 5.2.1p3 & play-games-plugin-for-unity 0.9.26

### ISSUE THREAD

**Issue by Junkyard-Jack** [playgameservices/play-games-plugin-for-unity#755]
Hey,

 I have tried to set up the GooglePlay and GooglePlay plugin for the 1st time today but for the QuizRacer and the CubicPilot the Unity scene files are broken with missing prefabs and missing Mono scripts in the Inspector. Many, many, many of them and I can't figure out what they were supposed to be configured as.

I tried the simplest example that does have game play, TicTacToe, and it's scene isn't broken and I can play it if I copy it to my tablet.

Does anyone have repaired MainScene.unity file for QuizRacers ot the scene files for CubicPilots so I can test better than what the TicTacToe game allows?

![quizracer](https://cloud.githubusercontent.com/assets/5953804/10446853/12db0440-714d-11e5-8234-e9758b6cddfa.png)

Thanks.

Ciao

**Comment by Junkyard-Jack** [comment]
The examples are broken in Unity 5.1.3p3 as well.

**Comment by banditdevelopment** [comment]
Did you make sure the files downloaded fine? They might have gotten "scrambled"; the best way to check would be to re-download them and try again.

**Comment by Junkyard-Jack** [comment]
7-zip has a checksum and that checksum is valid. The files weren't scrambled. I also used but the sample as they were in the zip as laid out in the file system and the *.unitypackage and both in the QuizRacer and the CubicPilot broken in the same manner in the same places.

I'm on Windows 10 and using Unity 5.2.1p3 but also tried Unity 5.1.3p3 with the same results.

**Comment by banditdevelopment** [comment]
OK, just wanted to eliminate one problem.

Unfortunately, I can't really help you more because I haven't worked with the example projects besides the Tic-Tac-Toe one.

**Comment by claywilkinson** [comment]
I'll take a look - thanks for the information.

**Comment by Junkyard-Jack** [comment]
Thanks.

**Comment by claywilkinson** [comment]
I updated the sample packages this morning.  I think the source of the problem is trying to build a package that works with both 4.6 and 5.x  These packages work for 5.x.

**Comment by Junkyard-Jack** [comment]
Thanks
