### ISSUE TITLE
Execute callbacks in main thread, or add warning in documentation

### ISSUE THREAD

**Issue by Trisibo** [playgameservices/play-games-plugin-for-unity#756]
It looks like callbacks aren't called on the main Unity thread, or at least the callback supplied to `PlayGamesPlatform.Instance.LoadScores()`, which recently has driven me crazy because it was the cause of crashes in my game. Not sure if it's just me, but I would expect that callbacks in Unity are called in the main thread, or at least that the documentation clearly states that they may not, it would prevent many potential problems.

**Comment by claywilkinson** [comment]
This is a good point.  Which would work better?   
Is there a downside to forcing all the callbacks back to the main thread?  It seems like some of the more "data" calls it is OK to do on other threads.  Is there an easy way to check if you are on the main thread or not?

Regardless, I agree that better documentation is a goal.

**Comment by Trisibo** [comment]
Personally, I would force the callbacks to be called on the main thread. I really don't think there's a downside (other than it being executed some milliseconds after the actual work has finished, or maybe using a bit more memory, but those are insignificant). The upside is that it would prevent problems without having to (remember to) use boilerplate code everywhere (like `PlayGamesHelperObject.RunOnGameThread(() => ...`, or locks), everything would be much cleaner.

I'm not really sure about using other threads with more "data" calls, since depending on the game it could still need some locking mechanism.

I don't know right now if there's an easy way to know if you are on the main thread, would that really be necessary?

**Comment by ejjoo** [comment]
It's usually unsafe to use thread in Unity. I can't understand why callback would be called from another thread not a game thread. It is totally useless even if it has a performance loss.

**Comment by claywilkinson** [comment]
The callbacks have been moved to the main thread in version 0.9.33
