### ISSUE TITLE
No in game callback

### ISSUE THREAD

**Issue by johntyrrell** [playgameservices/play-games-plugin-for-unity#757]
I can't seem to get a turn based multiplayer callback to work.

In the log I see this error popup every time, what am I doing wrong..?
E/Unity   (12779): StartCoroutine_Auto can only be called from the main thread.

E/Unity   (12779): Constructors and field initializers will be executed from the loading thread when loading a scene.

E/Unity   (12779): Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.

E/Unity   (12779):  

E/Unity   (12779): (Filename: ./artifacts/generated/common/runtime/UnityEngineMonoBehaviourBindings.gen.cpp Line: 89)

E/Unity   (12779): 

W/Unity   (12779): *** [Play Games Plugin DLL] 10/13/15 22:08:23 +02:00 ERROR: Error encountered executing InternalOnTurnBasedMatchEventCallback. Smothering to avoid passing exception into Native: System.ArgumentException: StartCoroutine_Auto can only be called from the main thread.

W/Unity   (12779): Constructors and field initializers will be executed from the loading thread when loading a scene.

W/Unity   (12779): Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.

W/Unity   (12779):   at UnityEngine.MonoBehaviour.StartCoroutine (IEnumerator routine) [0x00000] in <filename unknown>:0 

W/Unity   (12779):   at GooglePlayGames.OurUtils.PlayGamesHelperObject.RunCoroutine (IEnumerator action) [0x00010] in E:\Code\Source\Unity\Multiplayer test\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:86 

W/Unity   (12779):   at GooglePlayGames.Native.PInvoke.Callbacks.AsCoroutine (IEnumerator routine) [0x00000] in E:\Code\Source\Unity\Multiplayer test\Assets\GooglePlayGames\Platforms\Native\PInvoke\Callbacks.cs:237 

W/Unity   (12779):   at GooglePlayGames.Native.Na

My code file:
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using GooglePlayGames.BasicApi.Multiplayer;
using GooglePlayGames.OurUtils;
using System;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;
using UnityEngine;

public class CubeScript : MonoBehaviour
{
    public GameObject Text = null;
    public GameObject Text2 = null;
    private GUIText myText;
    private GUIText myText2;

    const int MinOpponents = 1;
    const int MaxOpponents = 1;
    const int Variant = 0;  // default

    private TurnBasedMatch gameMatch;
    private bool canPlay = false;
    private GameState State = new CubeScript.GameState();

    private string text = string.Empty;
    private string text2 = string.Empty;

    // the match the player is being offered to play right now
    TurnBasedMatch mIncomingMatch = null;
    Invitation mIncomingInvite = null;

    // Use this for initialization
    void Start()
    {
        myText = Text.GetComponent<GUIText>();
        myText.text = "Started";

        myText2 = Text2.GetComponent<GUIText>();
        myText2.text = "wazzaa";
    }

    // Update is called once per frame
    void Update()
    {
        if (!string.IsNullOrEmpty(text))
        {
            myText.text = text;
            text = null;
        }
        if (!string.IsNullOrEmpty(text2))
        {
            myText2.text = text2;
            text2 = null;
        }

        if (Input.GetButton("Fire1"))
        {
            //myText.text = "can play!!";            
        }

        if (Input.touchCount > 0 && Input.GetTouch(0).phase == TouchPhase.Moved)
        {
            // Get movement of the finger since last frame
            Vector2 touchDeltaPosition = Input.GetTouch(0).deltaPosition;

            // Move object across XY plane
            transform.Translate(-touchDeltaPosition.x * speed, -touchDeltaPosition.y * speed, 0);
        }
    }

    bool test = false;

    void OnGUI()
    {
        if (!test)
        {
            test = true;
            myText2.text += "test done";
        }
        // ....(other logic)....
        if (mIncomingMatch != null)
        {
            // show banner saying ("It's your turn against [opponent]!") and
            // put show buttons for "play" and "not now".
            //if (clickedPlay)
            //{
            //    // play now!
            //    OnMatchStarted(true, mIncomingMatch);
            //    mIncomingMatch = null;
            //}
            //else if (clickedNotNow)
            //{
            //    // stop showing banner:
            //    mIncomingMatch = null;
            //}
            myText2.text = "Incoming match!!";
        }
    }

    public void CreateGame()
    {
        //PlayGamesPlatform.Instance.TurnBased.CreateQuickMatch(MinOpponents, MaxOpponents, Variant, OnMatchStarted);
        myText.text = "Creating game";
        PlayGamesPlatform.Instance.TurnBased.CreateWithInvitationScreen(MinOpponents, MaxOpponents, Variant, OnMatchStarted);
    }

    public void JoinGame()
    {
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
            // enables saving game progress.
            //.EnableSavedGames()
            // registers a callback to handle game invitations received while the game is not running.
            //.WithInvitationDelegate(OnInvitationReceived)

            // registers a callback for turn based match notifications received while the
            // game is not running.
            .WithMatchDelegate(OnGotMatch)
            .Build();

        PlayGamesPlatform.InitializeInstance(config);
        // recommended for debugging:
        PlayGamesPlatform.DebugLogEnabled = true;
        // Activate the Google Play Games platform
        PlayGamesPlatform.Activate();

        Social.localUser.Authenticate((bool success) =>
        {
            text = Social.localUser.userName;

            // register delegates
            //PlayGamesPlatform.Instance.RegisterInvitationDelegate(OnInvitationReceived);
            //if (PlayGamesPlatform.Instance.TurnBased != null)
            //{
            PlayGamesPlatform.Instance.TurnBased.RegisterMatchDelegate(OnGotMatch);
            //}

            myText.text = "Joining game";
            PlayGamesPlatform.Instance.TurnBased.AcceptFromInbox(OnMatchStarted);
        });
    }

    public void TakeTurn()
    {
        myText.text = "Taking turn";
        myText.text = "";
        try
        {
            //var nextPlayerIndex = 0;
            //var self = gameMatch.Participants.First(p => p.ParticipantId == gameMatch.SelfParticipantId);
            //myText.text += "1.(self=" + self.ParticipantId + ")";
            //var indexOfCurrentPlayer = gameMatch.Participants.IndexOf(self);
            //myText.text += "2.(index=" + indexOfCurrentPlayer + ")";
            //if (indexOfCurrentPlayer < gameMatch.Participants.Count - 1)
            //    nextPlayerIndex = indexOfCurrentPlayer + 1;
            //myText.text += "3.(count=" + gameMatch.Participants.Count + ")";
            //var nextPlayer = gameMatch.Participants[nextPlayerIndex];
            //myText.text += "4.(next=" + nextPlayer.ParticipantId + ")";

            if (gameMatch != null)
            {
                byte[] data = ConvertGameState(State);
                //myText.text += "5.";
                PlayGamesPlatform.Instance.TurnBased.TakeTurn(gameMatch, data, DecideNextToPlay(), (bool success) =>
                {
                    if (success)
                    {
                        myText.text += " turn played";

                    }
                    else
                    {
                        myText.text += " turn not played";
                    }
                });
            }
        }
        catch (Exception ex)
        {
            myText.text = "Exception playing turn: " + ex.Message;
        }
    }

    // Callback:
    void OnMatchStarted(bool success, TurnBasedMatch match)
    {
        text = "Game started: " + success;
        if (success)
        {
            gameMatch = match;
            // go to the game screen and play!
            // get the match data
            byte[] myData = match.Data;

            // I can only make a move if the match is active and it's my turn!
            if (gameMatch != null)
            {
                canPlay = (gameMatch.Status == TurnBasedMatch.MatchStatus.Active &&
                    gameMatch.TurnStatus == TurnBasedMatch.MatchTurnStatus.MyTurn);
            }
            else
            {
                text += "gamematch null!";
            }

            text += "Can Play: " + canPlay;
            if (!canPlay)
            {
                text += ExplainWhyICantPlay();
            }
        }
        else
        {
            // show error message
            text += " no succes?";
        }
    }

    private string ExplainWhyICantPlay()
    {   
        switch (gameMatch.Status)
        {
            case TurnBasedMatch.MatchStatus.Active:
                return "Active";
            case TurnBasedMatch.MatchStatus.Complete:
                return "Complete";
            case TurnBasedMatch.MatchStatus.Cancelled:
            case TurnBasedMatch.MatchStatus.Expired:
                return "This match was cancelled.";
            case TurnBasedMatch.MatchStatus.AutoMatching:
                return "This match is awaiting players.";
            default:
                return "This match can't continue due to an error.";
        }

        if (gameMatch.TurnStatus != TurnBasedMatch.MatchTurnStatus.MyTurn)
        {
            return "It's not your turn yet!";
        }

        return "Error";
    }

    [Serializable]
    private class GameState
    {
        public string MyProperty1 { get; set; }
        public string MyProperty2 { get; set; }
    }

    public float speed = 0.1F;
    
    string DecideNextToPlay()
    {
        if (gameMatch.AvailableAutomatchSlots > 0)
        {
            // hand over to an automatch player
            return null;
        }
        else
        {
            // hand over to our (only) opponent
            Participant opponent = GetOpponent(gameMatch);
            return opponent == null ? null : opponent.ParticipantId;
        }
    }

    public static Participant GetOpponent(TurnBasedMatch match)
    {
        foreach (Participant p in match.Participants)
        {
            if (!p.ParticipantId.Equals(match.SelfParticipantId))
            {
                return p;
            }
        }
        return null;
    }
    

    // called when an invitation is received:
    public void OnInvitationReceived(Invitation invitation, bool shouldAutoAccept)
    {
        PlayGamesHelperObject.RunOnGameThread(() =>
        {
            text2 = "invite received";
            //if (shouldAutoAccept)
            //{
            // Invitation should be accepted immediately. This happens if the user already
            // indicated (through the notification UI) that they wish to accept the invitation,
            // so we should not prompt again.
            PlayGamesPlatform.Instance.TurnBased.AcceptInvitation(invitation.InvitationId, OnMatchStarted);
            //}
            //else
            //{
            //    // The user has not yet indicated that they want to accept this invitation.
            //    // We should *not* automatically accept it. Rather we store it and 
            //    // display an in-game popup:
            //   var test = invitation;
            //    myText2.text = "invite received";
            //}
        });
    }

    // match delegate:
    void OnGotMatch(TurnBasedMatch match, bool shouldAutoLaunch)
    {
        if (shouldAutoLaunch)
        {
            // if shouldAutoLaunch is true, we know the user has indicated (via an external UI)
            // that they wish to play this match right now, so we take the user to the
            // game screen without further delay:
            OnMatchStarted(true, match);
        }
        else
        {
            // if shouldAutoLaunch is false, this means it's not clear that the user
            // wants to jump into the game right away (for example, we might have received
            // this match from a background push notification). So, instead, we will
            // calmly hold on to the match and show a prompt so they can decide
            mIncomingMatch = match;
        }
    }

    private byte[] ConvertGameState(GameState obj)
    {
        if (obj == null)
            return null;
        BinaryFormatter bf = new BinaryFormatter();
        using (MemoryStream ms = new MemoryStream())
        {
            bf.Serialize(ms, obj);
            return ms.ToArray();
        }
    }

    private GameState GetGameState(byte[] data)
    {
        if (data == null)
            return null;
        BinaryFormatter bf = new BinaryFormatter();
        using (MemoryStream ms = new MemoryStream())
        {
            var state = bf.Deserialize(ms);
            return state as GameState;
        }
    }
}

**Comment by Trisibo** [comment]
I haven't seen your code, but the "*E/Unity (12779): StartCoroutine_Auto can only be called from the main thread*" error says to me that the callback is called from a different thread than the main Unity one. Coincidentally, before your issue I posted another one suggesting that callbacks are called on the main thread, or that the documentation makes it clear that they may not.

You should try to execute your callback code in the main thread of Unity. One quick way to do that is to just wrap the code in the callbacks with `PlayGamesHelperObject.RunOnGameThread(() => { <your code here> });`

**Comment by claywilkinson** [comment]
I have a fix for the this, I'll commit it soon.  In the meantime, if you want to change it, go to Assets/GooglePlayGames/OurUtils/PlayGamesHelperObject.cs  Then replace the RunCoroutine method with:
```
        public static void RunCoroutine(IEnumerator action)                     
        {                                                                       
            if (instance != null)                                               
            {                                                                   
                RunOnGameThread(()=>instance.StartCoroutine(action));           
            }                                                                   
        }   
```

**Comment by claywilkinson** [comment]
The plugin has been updated in version 0.9.27 to include this fix.

**Comment by ariefannur** [comment]
I get the same problem. can't show invitaion OnInvitationReceived in newest version plugin. Any Solution @claywilkinson @johntyrrell
