### ISSUE TITLE
Unity-GooglePlayGamesPlugin-0.9.21.unitypackage-auth fail

### ISSUE THREAD

**Issue by skaurawind** [playgameservices/play-games-plugin-for-unity#758]
I have try two android Environment to test
why 「2's android Environment」 is fail ?

1's android Environment   android：API 22、Google Play services：25
test result ==>auth is ok
2's android Environment   API 23、Google Play services：27
test result ==>fail

log :
10-15 10:54:24.623: D/GamesUnitySDK(31606): Performing Android initialization of the GPG SDK
10-15 10:54:24.673: I/Unity(31606): InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK
10-15 10:54:24.673: I/Unity(31606):   at GooglePlayGames.Native.PInvoke.GameServicesBuilder.Build (GooglePlayGames.Native.PInvoke.PlatformConfiguration configRef) [0x00000] in <filename unknown>:0 
10-15 10:54:24.673: I/Unity(31606):   at GooglePlayGames.Native.NativeClient.InitializeGameServices () [0x00000] in <filename unknown>:0 
10-15 10:54:24.673: I/Unity(31606):   at GooglePlayGames.Native.NativeClient.Authenticate (System.Action`1 callback, Boolean silent) [0x00000] in <filename unknown>:0 
10-15 10:54:24.673: I/Unity(31606):   at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`1 callback, Boolean silent) [0x00000] in <filename unknown>:0 
10-15 10:54:24.673: I/Unity(31606):   at GooglePlayGames.PlayGamesPlatform.Authenticate (System.Action`1 callback) [0x00000] in <filename unknown>:0 
10-15 10:54:24.673: I/Unity(31606):   at GooglePlayGames.PlayGamesLocalUser.Authenticate (System.Action`1 callback) [0x00000] in <filename unknown>:0 
10-15 10:54:24.673: I/Unity(31606):   at GoogleLoginClick.ClickGoogleLogin () [0x00000] in <filename unknown>:0 
10-15 10:54:24.673: I/Unity(31606):   at UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) [0x0

**Comment by claywilkinson** [comment]
Is there more in the log previously?  This message indicates there should be:
```
10-15 10:54:24.673: I/Unity(31606): InvalidOperationException: There was an error creating a GameServices object. Check for log errors from GamesNativeSDK
```

**Comment by skaurawind** [comment]
I have set unity-application id

log:
10-15 12:43:33.890: I/Unity(1223):  [Play Games Plugin DLL] 10/15/15 12:43:33 +08:00 DEBUG: Activating PlayGamesPlatform.
10-15 12:43:33.890: I/Unity(1223):  
10-15 12:43:33.890: I/Unity(1223): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
10-15 12:43:33.890: I/Unity(1223):  [Play Games Plugin DLL] 10/15/15 12:43:33 +08:00 DEBUG: Instance was not initialized, using default configuration.
10-15 12:43:33.890: I/Unity(1223):  
10-15 12:43:33.890: I/Unity(1223): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)
10-15 12:43:33.900: I/Unity(1223):  [Play Games Plugin DLL] 10/15/15 12:43:33 +08:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
10-15 12:43:33.900: I/Unity(1223):  
10-15 12:43:33.900: I/Unity(1223): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)

**Comment by skaurawind** [comment]
I GET Andwser
GooglePlayGamesPlugin-0.9.21 can't not run ,because android version too old

**Comment by claywilkinson** [comment]
Please re-open if there is still an issue.  Thanks!
