### ISSUE TITLE
Android support library NOT in support folder

### ISSUE THREAD

**Issue by LoungeKatt** [playgameservices/play-games-plugin-for-unity#759]
I believe I had listed this in a previous issue with finding the support library that was marked fixed.

The support v4 library is in "compatibility" not "support" while the rest of the path is correct.

**Comment by claywilkinson** [comment]
Is it not working for you?  The plugin actually looks in both places so it handles both the old and new locations.

**Comment by LoungeKatt** [comment]
Is that a serious question? In case it is, the plugin is only attempting to pull the library from the "support" folder as per the initial statement.

**Comment by claywilkinson** [comment]
In the latest version 0.9.27 - we copy the .aar file for the support lib, vs. finding the jar.  This should resolve your issue.  Thanks!
