### ISSUE TITLE
Can't unlock achievements during testing

### ISSUE THREAD

**Issue by Per-Malmberg** [playgameservices/play-games-plugin-for-unity#76]
Hello!

I'm still in testing and I've added five achievements to the game, but I can't seem to unlock them.

When I run this code the achievements UI opens up but the achievemnt hasn't been unlocked.

Social.ReportProgress(achievementId, 100.0f, (bool reportSuccess) => {
                if (reportSuccess) {
                    playGamesPlatform.ShowAchievementsUI();
                }
            });

Is this only supposed to work after publishing?

Regards/Per

**Comment by VusalJalilov** [comment]
Hello!
Using v0.9.38

Cannot Unlocking an Achievement with this code. No matter what I do. It just keeps failing.
Resetting the Achievement, deleting and creating a new one does not help.
It used to work with v0.9.36...

`public void Unlock1000Enemies()
    {
       Social.ReportProgress("XXXXXXXXXXXXX", 100.0f, (bool success) => 
        {
            // handle success or failure 
            if (!success)
            {
                UIScript.Instance.PGSDebug.text = "Achievement Failed";
            }
        });
    }`

Social.ShowAchievementsUI(); works just fine. It lists all of the Achievements.
