### ISSUE TITLE
[iOS] Framework not found GoogleOpenSource

### ISSUE THREAD

**Issue by hippogamesunity** [playgameservices/play-games-plugin-for-unity#761]
Hi! Have this error when building CocoaPods project using Xcode.
Unity 4.6.8, Xcode 7.0, latest plugin version. Thanks!

**Comment by claywilkinson** [comment]
Hmm. GoogleOpenSource?  Do you mean GooglePlusOpenSource?  Can you run `pod update` and share the output?

**Comment by hippogamesunity** [comment]
I'm not famaliar with CocoaPods, sorry (only installed it) and maybe it's not your issue.
Yes, I have error "ld: framework not found GoogleOpenSource"
pod update command output is:

pod update
Update all pods
Updating local specs repositories

CocoaPods 0.39.0 is available.
To update use: `gem install cocoapods`
Until we reach version 1.0 the features of CocoaPods can and will change.
We strongly recommend that you use the latest version at all times.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using GoogleAppUtilities (1.0.0)
Using GoogleAuthUtilities (1.0.1)
Using GoogleNetworkingUtilities (1.0.0)
Using GooglePlayGames (5.0)
Using GooglePlusOpenSource (1.7.1)
Using GoogleSignIn (2.3.2)
Using GoogleSymbolUtilities (1.0.0)
Using GoogleUtilities (1.1.0)
Generating Pods project
Integrating client project
Sending stats

[!] The `Unity-iPhone [Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Unity-iPhone/Pods-Unity-iPhone.release.xcconfig'. This can lead to problems with the CocoaPods installation
- Use the `$(inherited)` flag, or
- Remove the build settings from the target.

[!] The `Unity-iPhone [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Unity-iPhone/Pods-Unity-iPhone.debug.xcconfig'. This can lead to problems with the CocoaPods installation
- Use the `$(inherited)` flag, or
- Remove the build settings from the target.

**Comment by hippogamesunity** [comment]
And here is full error output:

Ld /Users/yafarida/Library/Developer/Xcode/DerivedData/Unity-iPhone-dauwnokgvzihhpeyyykfdlvxwymi/Build/Intermediates/Unity-iPhone.build/Debug-iphoneos/Unity-iPhone.build/Objects-normal/arm64/HipsterClicker normal arm64
cd "/Users/yafarida/Desktop/Hippo Games/HipsterClicker/HipsterClickerXcode"
export IPHONEOS_DEPLOYMENT_TARGET=8.0
export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -L/Users/yafarida/Library/Developer/Xcode/DerivedData/Unity-iPhone-dauwnokgvzihhpeyyykfdlvxwymi/Build/Products/Debug-iphoneos -L/Users/yafarida/Desktop/Hippo\ Games/HipsterClicker/HipsterClickerXcode/Pods/GoogleAppUtilities/Libraries -L/Users/yafarida/Desktop/Hippo\ Games/HipsterClicker/HipsterClickerXcode/Pods/GoogleAuthUtilities/Libraries -L/Users/yafarida/Desktop/Hippo\ Games/HipsterClicker/HipsterClickerXcode/Pods/GoogleNetworkingUtilities/Libraries -L/Users/yafarida/Desktop/Hippo\ Games/HipsterClicker/HipsterClickerXcode/Pods/GoogleSignIn/Libraries -L/Users/yafarida/Desktop/Hippo\ Games/HipsterClicker/HipsterClickerXcode/Pods/GoogleSymbolUtilities/Libraries -L/Users/yafarida/Desktop/Hippo\ Games/HipsterClicker/HipsterClickerXcode/Pods/GoogleUtilities/Libraries -L/Users/yafarida/Desktop/Hippo\ Games/HipsterClicker/HipsterClickerXcode -L/Users/yafarida/Desktop/Hippo\ Games/HipsterClicker/HipsterClickerXcode/Libraries -F/Users/yafarida/Library/Developer/Xcode/DerivedData/Unity-iPhone-dauwnokgvzihhpeyyykfdlvxwymi/Build/Products/Debug-iphoneos -F/Users/yafarida/Desktop/Hippo\ Games/HipsterClicker/Assets/Plugins/iOS -filelist /Users/yafarida/Library/Developer/Xcode/DerivedData/Unity-iPhone-dauwnokgvzihhpeyyykfdlvxwymi/Build/Intermediates/Unity-iPhone.build/Debug-iphoneos/Unity-iPhone.build/Objects-normal/arm64/HipsterClicker.LinkFileList -Xlinker -map -Xlinker /Users/yafarida/Library/Developer/Xcode/DerivedData/Unity-iPhone-dauwnokgvzihhpeyyykfdlvxwymi/Build/Intermediates/Unity-iPhone.build/Debug-iphoneos/Unity-iPhone.build/HipsterClicker-LinkMap-normal-arm64.txt -miphoneos-version-min=8.0 -dead_strip -fembed-bitcode-marker -weak_framework CoreMotion -weak-lSystem -ObjC -lGIDExShared -lGIPNSURL+FIFE -lGSDK_Overload -lGTMOAuth2_external -lGTMOAuth2_internal -lGTMSessionFetcher_core -lGTMSessionFetcher_full -lGTMStackTrace -lGTM_AddressBook -lGTM_DebugUtils -lGTM_GTMURLBuilder -lGTM_KVO -lGTM_NSData+zlib -lGTM_NSDictionary+URLArguments -lGTM_NSScannerJSON -lGTM_NSStringHTML -lGTM_NSStringXML -lGTM_Regex -lGTM_RoundedRectPath -lGTM_StringEncoding -lGTM_SystemVersion -lGTM_UIFont+LineHeight -lGTM_core -lGTM_iPhone -lOpenInChrome -lSignIn -lc++ -lz -framework AddressBook -framework AssetsLibrary -framework CoreData -framework CoreGraphics -framework CoreLocation -framework CoreMotion -framework CoreTelephony -framework CoreText -framework GoogleOpenSource -framework MediaPlayer -framework QuartzCore -framework SafariServices -framework Security -framework StoreKit -framework SystemConfiguration -framework gpg -stdlib=libstdc++ -fobjc-link-runtime -framework Foundation -framework UIKit -framework OpenGLES -framework QuartzCore -framework OpenAL -liconv.2 -liPhone-lib -framework AudioToolbox -framework CFNetwork -framework MediaPlayer -framework GoogleOpenSource -framework CoreLocation -framework SystemConfiguration -weak_framework iAd -framework CoreMedia -framework CoreVideo -weak_framework AVFoundation -framework CoreGraphics -weak_framework CoreMotion -weak_framework GameKit -lPods-Unity-iPhone -framework AdSupport -framework StoreKit -framework CoreTelephony -framework UnityAds -Xlinker -dependency_info -Xlinker
18:25:54	
/Users/yafarida/Library/Developer/Xcode/DerivedData/Unity-iPhone-dauwnokgvzihhpeyyykfdlvxwymi/Build/Intermediates/Unity-iPhone.build/Debug-iphoneos/Unity-iPhone.build/Objects-normal/arm64/HipsterClicker_dependency_info.dat -o /Users/yafarida/Library/Developer/Xcode/DerivedData/Unity-iPhone-dauwnokgvzihhpeyyykfdlvxwymi/Build/Intermediates/Unity-iPhone.build/Debug-iphoneos/Unity-iPhone.build/Objects-normal/arm64/HipsterClicker

ld: framework not found GoogleOpenSource
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hippogamesunity** [comment]
I tried to delete all plugins and add them again (inluding GPG), problem was not solved. GoogleOpenSource framwork exists on disk and included in Pods.

**Comment by hippogamesunity** [comment]
@claywilkinson Hi, any news about this issue?

**Comment by claywilkinson** [comment]
Did you fix the warnings about adding $(inherited) to the framework search path? Maybe that is the problem? Might also want to upgrade your cocoapods, they keep tweaking edge cases like this one....

**Comment by hippogamesunity** [comment]
@claywilkinson I found the solution. I removed reference to GoogleOpenSource from Pods and then added it again. This helped. Sometimes I hate apple products. Maybe you should add this use case to plugin FAQ. Thanks anyway. Can be closed now.

**Comment by claywilkinson** [comment]
Great!  when you say "removed reference to GoogleOpenSource", you mean in the Xcode project?

**Comment by hippogamesunity** [comment]
@claywilkinson Yes, I mean Xcode project -Pods/Pods/GooglePlusOpenSource/Frameworks/GooglePlayOpenSource.framework. I have the same error with gpg.framework later (which resolved this way too).

**Comment by claywilkinson** [comment]
OK thanks - I'll add it to the readme.
