### ISSUE TITLE
crash when trying to sign in on IOS devices

### ISSUE THREAD

**Issue by HaimBendanan** [playgameservices/play-games-plugin-for-unity#762]
Hi, 

i have an issue related only to IOS devices. On android everything works fine. 
when i press the leaderboard icon and try to connect to the game service on IOS, the app crashes.
I attached a screenshot of the error i am getting : 

![rko7gtoadtzmtvtzmklnqklfrpynw1n9gmiqmvhrz1e](https://cloud.githubusercontent.com/assets/14773715/10545926/e49cdb28-7433-11e5-9129-580de7d6207f.png)

i would be glad to get help!

**Comment by HaimBendanan** [comment]
someone?

**Comment by HaimBendanan** [comment]
would be nice to get help on this, i am really stuck

**Comment by claywilkinson** [comment]
Which version of the plugin are you using?  I strongly suggest using 0.9.26 or higher for iOS.  The library for sign-in was updated to use a webview (which is acceptable to Apple).  This sounds like you might have some source files from the old plugin as well?  or maybe an old library?  Do you use cocoa-pods (strongly recommended)?  Make sure your Podfile references Play Games 5.0.

**Comment by HaimBendanan** [comment]
i am using cocoapod, i will try to update and i ll post my results back here, thanks

**Comment by HaimBendanan** [comment]
claywilkinson thanks for the help ! 
your answer here :(https://github.com/playgameservices/play-games-plugin-for-unity/issues/716) 
solved my problems.
