### ISSUE TITLE
user can not login with error 0 accounts with uca feature found

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [playgameservices/play-games-plugin-for-unity#763]
We've added a user to our testers in google play, the accounts email is from our own gamajun.biz domain so xxx@gamajun.biz
when we try to sign in it says, G+ profile can not be initialized with the following log
--
/GLSActivity(22300):  AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
V/GLSActivity(22300):  AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
D/ChimeraCfgMgr(22331):  Loading module com.google.android.gms.games from APK com.google.android.play.games
D/ChimeraModuleLdr(22331):  Module APK com.google.android.play.games already loaded
D/ChimeraCfgMgr(22331):  Loading module com.google.android.gms.games from APK com.google.android.play.games
I/Keyboard.Facilitator(756):  onFinishInput()
D/ChimeraModuleLdr(22331):  Module APK com.google.android.play.games already loaded
D/dalvikvm(22300):  GC_CONCURRENT freed 550K, 7% free 10008K/10760K, paused 2ms+73ms, total 149ms
D/ChimeraCfgMgr(22331):  Loading module com.google.android.gms.games from APK com.google.android.play.games
D/ChimeraModuleLdr(22331):  Module APK com.google.android.play.games already loaded
V/AccountUtils(22331):  0 accounts found with uca feature
I/ActivityManager(504):  START u0 {act=com.google.android.gms.ui.UNPACKING_REDIRECT pkg=com.google.android.gms cmp=com.google.android.gms/.common.ui.UnpackingRedirectActivity (has extras)} from pid 29750
W/SurfaceFlinger(122):  couldn't log to binary event log: overflow.
I/ActivityManager(504):  START u0 {act=com.google.android.gms.plus.action.SIGN_UP flg=0x2000000 cmp=com.google.android.gms/.plus.activity.AccountSignUpActivity (has extras)} from pid -1
D/dalvikvm(29750):  GC_CONCURRENT freed 419K, 6% free 7960K/8416K, paused 13ms+2ms, total 197ms

----

**Comment by claywilkinson** [comment]
The accounts with uca feature should not be a problem, i see it on my phone.  Is it still happening?  Is it OK to close this issue?  Thanks!
