### ISSUE TITLE
Can't connect to google play game services

### ISSUE THREAD

**Issue by Dave-DS** [playgameservices/play-games-plugin-for-unity#764]
Google play doesn't seem to authenticate a user properly for my app. When I click log in, it says 'connecting to...', then a green loading sign pops up and it doesn't inform me that the account was authenticated. Not really sure what's going on. Checked many places for answers and couldn't find any. help

**Comment by claywilkinson** [comment]
Can you post a log of the authentication?  The other things to check are that the bundleId matches the bundle ID associated with the link application for your game.  Also if this is for Android, that you are signing the app, and the SHA1 fingerprint of the key you are signing your app with matches the one entered in the linked android app.  Finally check that the player signing in is listed as a tester for your game.

**Comment by Dave-DS** [comment]
Hi. I've actually found the error and it was that the apk file was not updated in the developer console. Everything works smoothly now. Thank you for your quick response

**Comment by claywilkinson** [comment]
Great!
