### ISSUE TITLE
When opponent finished his turn no notification is coming in Google Play Games itself

### ISSUE THREAD

**Issue by KeySam** [playgameservices/play-games-plugin-for-unity#765]
Earlier in development i was getting notifications, but for some reason i do not get any notifications, i know that i turned them off earlier in development because they where to mutch, but now they should be popping up (i changed the settings in the app to get notifications) but i do not get them anymore. Do i have to change a setting or something inside unity to get them again?

**Comment by KeySam** [comment]
Just to be clear i mean i get nothing when the app is turned off, inside the  game i get the callbacks of turn finished.

**Comment by rahuldotar** [comment]
I face the same issue right now.. Do you get any solution for this??

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
