### ISSUE TITLE
QuizRacer problem

### ISSUE THREAD

**Issue by hollyhogan** [playgameservices/play-games-plugin-for-unity#767]
Hi, could anyone help me?
The QuizRacer package for Unity I think have some problems or the export of the package was not done properly.
When I start the scene MainScene.unity from QuizRacer project I got missing prefabs and missing script from Canvas. Here attached a picture.
My Unity version is 5.1.2f1

Regards,

![quizracer-problems](https://cloud.githubusercontent.com/assets/2783989/10570625/54a7befe-760c-11e5-873e-9bf1519e277c.png)

**Comment by claywilkinson** [comment]
Something happened when building the last version of the plugin and this and CubicPilot samples got messed up.  I'll work on fixing them today.

**Comment by hollyhogan** [comment]
Wow, thanks you very much @claywilkinson for your super very fast reply :)

**Comment by hollyhogan** [comment]
Hi @claywilkinson, the CubicPilot samples was fixed ?

**Comment by claywilkinson** [comment]
I just pushed an updated version of the samples.  I tested them with 5.2 with no issues.  I think there still some weirdness when trying to support both 4.6 and 5.+ which causes the problem.

Let me know if you have any problems/questions.

**Comment by hollyhogan** [comment]
Hi @claywilkinson, I try with the new packages, but when I create the .apk and test in my android device I only see the PLAY button but when I press that button nothing happen

**Comment by claywilkinson** [comment]
Hmm. Did you start with a new project?  Is there anything in the log?

**Comment by claywilkinson** [comment]
Closing this.  Please open a new issue if it is still not working with version 0.9.30.
