### ISSUE TITLE
how to you post score to different time frames of a leaderboard (today/this week/ all-time)?

### ISSUE THREAD

**Issue by QuangSang** [playgameservices/play-games-plugin-for-unity#769]
Hi guys,
So I've been using Social.ReportScore() to post score (total wins) to the leaderboard with score coming from our server. It's working fine for All-time leaderboard but for today and this week leaderboard, it shows the same score as all-time. So how do I make it so that it shows different scores for each time frames leaderboard? 

Looks like Social.ReportScore() doesn't have any an option to post score to a specific time frames leaderboard. All 3 time frames use the same leaderboard Id. Any suggestions?

Thanks.

**Comment by claywilkinson** [comment]
The time of the score submission is what is used to determine the scope. See [Leaderboard Concepts](https://developers.google.com/games/services/common/concepts/leaderboards#leaderboard_time_frames).

Are you seeing something unexpected?

**Comment by QuangSang** [comment]
I might have a different idea of leaderboard here. The score I am using is the total wins of that player so if he wins a battle against other player, his score goes up by 1. So is there a way to display how many wins he has today / this week and all time using the current leaderboard concepts?

**Comment by claywilkinson** [comment]
It sounds like you have 3 scores - one is the all-time cumulative wins, the second is the weekly, and the daily.

So one way to do it is have 3 leaderboards. 
1. Total Wins (The weekly/daily scopes show the top total wins achieved in that time period).
2. Wins this week (The All time scope ends up being the highest number of wins in a week, the weekly scope is what you are looking for, and the daily is the top weekly scorers today.
3. Daily wins The all time scope is the best daily score, the weekly is the best daily score this week, and daily is what you are thinking of, and gets reset every day.

**Comment by QuangSang** [comment]
hmm... so there is no other way of doing it using just 1 leaderboard with different time scope?

**Comment by claywilkinson** [comment]
I don't think so.  1 leaderboard will track 1 score per player.  So the all time score will be the max of the number wins you are submitting which does not sounds like what you want.  It is a little more work to configure, but is there a downside to using multiple leaderboards?

**Comment by claywilkinson** [comment]
OK to close this one?
