### ISSUE TITLE
Friends not appearing

### ISSUE THREAD

**Issue by aagr** [playgameservices/play-games-plugin-for-unity#77]
In Quiz Racer, when sending invitations, friends are not appearing (I only see auto pick).

I tried it in two iPhone 4's with different accounts and had the same problem. When I chose auto pick in both devices I was able to play a multiplayer game.

**Comment by claywilkinson** [comment]
This has to do with the fact that friend information is not readily available on iOS.  As a result only the recently played players will appear.
