### ISSUE TITLE
Which certificate should I use for p12 for Push Notification?

### ISSUE THREAD

**Issue by simsis3d** [playgameservices/play-games-plugin-for-unity#770]
I will export p12 file from certificate in Keychain Access to upload it Google Play Developer console,but I have two certificate in Keychain Access One is "IOS Development" and other is "IOS Push Services". Which one should I use? I am pretty much sure I should use "IOS Push Services" certificate, but in one of video tutorial, he says I should use"IOS Development" certificate.

**Comment by claywilkinson** [comment]
I think the push services is the correct one.  If you inspect the certificate using:
`openssl pkcs12 -info -in cert.p12` you should see it reference the notification service.

**Comment by simsis3d** [comment]
Thanks @claywilkinson for your quick response. Btw, I choose certificate and a private key associated with this certificate and exported it as p12 file(Certificate and private key selected). This way will produce an error in Developer Console when you want to upload it. You should only select certificate(Not with private key) from Keychain access and export it. This way will work.

This topic can now be closed I think.
