### ISSUE TITLE
What are "Android Resources"

### ISSUE THREAD

**Issue by DougLazyAngus** [playgameservices/play-games-plugin-for-unity#771]
From the setup directions, under "Android Setup":

"Paste the resource definition data. This is the XML data from the Google Play Developer Console which contains the resource IDs as well as the Application ID for Android."

I see a box that says "Resource Definition" with the instructions "Paste in the Android Resources from the Play Console".

???

I have been looking all over the Google Play console (https://play.google.com/apps) and I don't see anything that looks like "resource definition" or XML or whatever.
???

**Comment by DougLazyAngus** [comment]
Found my own answer:
http://answers.unity3d.com/questions/1075631/how-to-setup-google-play-game-service-on-android.html

This could be better explained in the documentation, and/or in the dialog box in Unity.

**Comment by claywilkinson** [comment]
Thanks for the feedback - I'll add a picture

**Comment by DougLazyAngus** [comment]
Later I noticed the explanation in the paragraph below.

So my bad, I should have kept reading the whole thing.

I did waste about a half hour trying to figure that out.  Maybe take out
the line break between paragraphs, so instead of

cut-n paste instructions

details on cut-n-paste instructions

it's

cut-n paste instructions. details on cut-n-paste instructions

On Wed, Oct 21, 2015 at 3:40 PM, Clayton Wilkinson <notifications@github.com
> wrote:

> Thanks for the feedback - I'll add a picture
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/771#issuecomment-150044842>
> .
>



-- 
Doug Banks
(650) 346 2107

**Comment by claywilkinson** [comment]
I updated the [README.md](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/README.md).  Please let me know if you have any suggested edits.

**Comment by DougLazyAngus** [comment]
Thanks for the quick responses!

On Mon, Nov 9, 2015 at 4:15 PM, Clayton Wilkinson <notifications@github.com>
wrote:

> Closed #771
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/771>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/771#event-459510231>
> .
>



-- 
Doug Banks
(650) 346 2107
