### ISSUE TITLE
Problem to parse milestone.CompletinRewardData

### ISSUE THREAD

**Issue by laurobeleche** [playgameservices/play-games-plugin-for-unity#773]
Please, i need a exemple to parse reward of my quest.

private void ClaimMilestone(IQuestMilestone toClaim)
	{
		PlayGamesPlatform.Instance.Quests.ClaimMilestone(toClaim,
		                                                 (QuestClaimMilestoneStatus status, IQuest quest, IQuestMilestone milestone) => {
			if (status == QuestClaimMilestoneStatus.Success)
			{
                                 //what i do here?
			}
		});
	}

**Comment by claywilkinson** [comment]
Closing this one since there has not been any activity for a long time. This type of question might be better handled on [StackOverflow](http://stackoverflow.com/questions/tagged/google-play-games)
