### ISSUE TITLE
can't display Leaderbord and achievement

### ISSUE THREAD

**Issue by DanAmel** [playgameservices/play-games-plugin-for-unity#774]
I'm trying to implement Google Play Game in my app, and am having an issue with Social.ShowAchievementsUI() and ShowLeaderboardUI() . Actually i can sing in, unlock an achievement. I dont understand why i cant show achievements and leaderbord

Code : 

void Start () {
 
             PlayGamesPlatform.Activate();
 
  Social.localUser.Authenticate((bool success) =>
         {
             if (success)
             {
                   Debug.Log("Login succes");
             }
             else
             {
                 Debug.Log("Login failed for some reason");
             }
         });
     }
     
     // Update is called once per frame
     void Update () {
     
     }
 
 
     /// <summary>
     /// Display achievement
     /// </summary>
     public void ShowAchievements()
     {
                 Social.ShowAchievementsUI();
         
     }
 
 
     /// <summary>
     /// Display all leaderboard
     /// </summary>
     public void ShowLeaderboardUI()
     {
                 Social.ShowLeaderboardUI();
         
        
     }

**Comment by DanAmel** [comment]
Help please

**Comment by claywilkinson** [comment]
Can you post a log of what is happening?

**Comment by Risine** [comment]
Hello,
I'm having the same problem ( android ).
I've done everything, I can authenticate, send score seems to work but showleaderboardUI does not show anything.
What can I do? You mentioned logging, but how can I log on the phone?

**Comment by claywilkinson** [comment]
You can get a log from the device using [Logcat](http://developer.android.com/tools/debugging/debugging-log.html#startingLogcat).

**Comment by claywilkinson** [comment]
Any update, or is this OK to close?

**Comment by Risine** [comment]
it's ok to close. It was entirely my fault. Don't ask me why, I'm too ashamed. :)

**Comment by claywilkinson** [comment]
OK thanks - everyone's been there :)
