### ISSUE TITLE
Can not get the List of friend images

### ISSUE THREAD

**Issue by hirenkacha** [playgameservices/play-games-plugin-for-unity#777]
I am not able to load the images of friends. If I comment out the image getter which starts coroutine, works fine without image. It gets me list of friends But as soon as I try with images, It throws me an error.

    E/Unity﹕ StartCoroutine_Auto can only be called from the main thread.
    Constructors and field initializers will be executed from the loading thread when loading a scene.
    Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.(Filename: ./artifacts/generated/common/runtime/UnityEngineMonoBehaviourBindings.gen.cpp Line: 89)

    10-26 18:43:20.227  18784-19438/? W/Unity﹕ *** [Play Games Plugin DLL] 10/26/15 18:43:20 +05:30 ERROR: Error encountered executing PlayerManager#InternalFetchCallback. Smothering to avoid passing exception into Native: System.ArgumentException: StartCoroutine_Auto can only be called from the main thread.
    Constructors and field initializers will be executed from the loading thread when loading a scene.
    Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.

     at UnityEngine.MonoBehaviour.StartCoroutine (IEnumerator routine) [0x00000] in <filename unknown>:0
           
    at GooglePlayGames.OurUtils.PlayGamesHelperObject.RunCoroutine (IEnumerator action) [0x00010] in F:\EatMe\eatme\eat-me-client\EatMe\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:86

    at GooglePlayGames.PlayGamesUserProfile.get_image () [0x0004c] in F:\EatMe\eatme\eat-me-client\EatMe\Assets\GooglePlayGames\ISocialPlatform\PlayGamesUserProfile.cs:98

    at Toolbox.Auth.SocialAPI.SocialService+<RetriveFrien

I have a method in an Abstract class
    List<IFriendData> RetriveFriendFromLeaderBoard(ILeaderboard lb, string leaderBoardId)

**Comment by claywilkinson** [comment]
The fix is pretty simple, it has not been committed yet.  If you open
Assets/GooglePlayGames/OutUtils/PlayGamesHelperObject.cs and change RunCoroutine to be the following, it should resolve your issue:

```
        public static void RunCoroutine(IEnumerator action)                     
        {                                                                       
            if (instance != null)                                               
            {                                                                   
                RunOnGameThread(()=>instance.StartCoroutine(action));           
            }                                                                   
        }   
```

**Comment by claywilkinson** [comment]
This is updated in version 0.9.27
