### ISSUE TITLE
Minimal Sample / Build-Error : MainLibProj' is missing AndroidManifest.xml file

### ISSUE THREAD

**Issue by Dragonic89** [playgameservices/play-games-plugin-for-unity#778]
Hello,

I'm using the plugin 0.9.26 with Unity 5.1.3f1 ! 

I wanted to try the Minimal sample : I imported the plugin, and created a new keystore for the build.
Path to the Android SDK is correct, using the last version for Build-tools (23.0.1).

When I try to build the APK I have this error : 
> Project 'D:\Datas\Unity Projects\Unity5\play-games-plugin-for-unity-master\samples\Minimal\Source\Assets\Plugins\Android\MainLibProj' is missing AndroidManifest.xml file. 
UnityEditor.HostView:OnGUI()

I found some links about the same error : 
https://github.com/playgameservices/play-games-plugin-for-unity/issues/558
http://gamedevtodied.blogspot.fr/2015/06/unity3d-android-build-error.html

But nothing that can help me here because I don't find any AndroidManifest.xml on my project (nothing in Assets/Plugins/Android) !

It doesn't seem that I had forgotten something here before the build, that's why I'm opening this topic !

Regards,

EDIT : found the issue ! Tutorial wasn't really clear for me ! Had to add the class name and resources in the setup (but not the ID because we can't have it before the first build, that's why I didn't understand).

**Comment by rpuls** [comment]
Hi, can you elaborate: _"Had to add the class name and resources in the setup"_ ? I'm having a similar issue with another plugin. What setup are you talking about? Thanks

**Comment by ArjunMahesh97** [comment]
> Hi, can you elaborate: _"Had to add the class name and resources in the setup"_ ? I'm having a similar issue with another plugin. What setup are you talking about? Thanks
> 
> `'C:\Users\username\Documents\UnityProjects\projectname\Temp\StagingArea\android-libraries\GooglePlayGamesManifest.plugin' is missing AndroidManifest.xml file. UnityEditor.HostView:OnGUI()`
> 
> Edit: error comes from this plugin which is included by another plugin.

Did you find a solution to this?

**Comment by aDu** [comment]
> > Hi, can you elaborate: _"Had to add the class name and resources in the setup"_ ? I'm having a similar issue with another plugin. What setup are you talking about? Thanks
> > `'C:\Users\username\Documents\UnityProjects\projectname\Temp\StagingArea\android-libraries\GooglePlayGamesManifest.plugin' is missing AndroidManifest.xml file. UnityEditor.HostView:OnGUI()`
> > Edit: error comes from this plugin which is included by another plugin.
> 
> Did you find a solution to this?

Also experiencing the same issue. Not many results on Google.
