### ISSUE TITLE
Can not show Leaderboard

### ISSUE THREAD

**Issue by garv3** [playgameservices/play-games-plugin-for-unity#78]
When I call
```
((PlayGamesPlatform)Social.Active).ShowLeaderboardUI("myLeaderBoardId");
```
from within my Game using the Unity SDK on an Android device, the Play Games Window opens, shows a loading indicator and quits immediately.
The log says:
```
I/Unity   (10109): onPause
D/Unity   (10109): Sensor :        Accelerometer ( 1) ; 1.000000 / 0.02s ; MPL accel / Invensense
I/Unity   (10109): windowFocusChanged: false
I/Unity   (10109): onResume
I/Unity   (10109): windowFocusChanged: true
D/Unity   (10109): Sensor :        Accelerometer ( 1) ; 1.000000 / 0.02s ; MPL accel / Invensense
```
The user is authenticated and the LeaderBoardId is correct - of course!
Btw: Achievements UI works well!

**Comment by claywilkinson** [comment]
See the management API to reset leaderboards and achievements for test accounts: https://developers.google.com/games/services/management/api/index
