### ISSUE TITLE
GIDSignIn.h STILL not found

### ISSUE THREAD

**Issue by Universalerror** [playgameservices/play-games-plugin-for-unity#780]
Another continuation of the GIDSignIn.h problem. I've tried using the "GoogleSignIn/" prefix as well as re-importing the project and libraries and the file still can't be found. The same goes with the other 5 files in the list that GIDSignIn.h heads, these files being GIDGoogleUser.h, GIDAuthentication.h, GIDProfileData, gpg/ios_support.h and gpg/GPGEnums.h.
![cantfindheaderfiles](https://cloud.githubusercontent.com/assets/15358716/10784254/0582dfde-7d55-11e5-90ee-b088211a5a63.png)

**Comment by Universalerror** [comment]
Fixed the issue. Wasn't using Cocoapods correctly.

**Comment by tonio1206** [comment]
Could you please specify how you solved this. I'm having the thing problem and I can't find a solution.
Thank you

**Comment by Universalerror** [comment]
Hi tonio1206. It's been a while but I fixed it by opening the xcode project with the xcode file that **isn't** the one called xcodeproj. I can't remember the exact file extension but it should be fairly obvious.
