### ISSUE TITLE
Game crashes after closing leaderboard

### ISSUE THREAD

**Issue by szymski** [playgameservices/play-games-plugin-for-unity#783]
I use Google Play Games in my game. Everything is already configured and authorization works. The problem is when I open and close the leaderboard, game immediately crashes. I open it using this function: ` PlayGamesPlatform.Instance.ShowLeaderboardUI("CgkI6OHR7pIQEAIQAA");`

It opens and works well. I can see the scores, but when I go back to game, it crashes.
Here are example crash reports I get:

`java.lang.Error: FATAL EXCEPTION [UnityMain]
    Unity version     : 5.1.2f1
    Device model      : LGE LG-D290
    Device fingerprint: lge/l70pn_global_com/l70pn:4.4.2/KOT49I.A1423829747/1423829747:user/release-keys
    
    Caused by: java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000002
    Build fingerprint: 'lge/l70pn_global_com/l70pn:4.4.2/KOT49I.A1423829747/1423829747:user/release-keys'
    Revision: '6'
    pid: 3684, tid: 3776, name: callback_queue  >>> com.TenPercent.PIGGURUN <<<
        r0 00000001  r1 6a5cbab8  r2 00000003  r3 68a2b4b0
        r4 696aab7c  r5 69aa6d60  r6 67171b50  r7 69aa6d54
        r8 696aab7c  r9 69aa6d50  sl 696aaba0  fp 00000006
        ip 00000001  sp 69aa6d30  lr 695e6d73  pc 00000002  cpsr 2e493934
    
    	at Unknown.00000002(Unknown Source)
    	at libgpg.000d0d71(Native Method)
    	at libgpg.00058e45(Native Method)
    	at libgpg.000aecef(Native Method)
    	at libgpg.0006194d(Native Method)`

`Build fingerprint: 'htc/htc_europe/htc_memul:4.4.2/KOT49H/405590.2:user/release-keys'
    Revision: '0'
    pid: 6659, tid: 6659, name: ercent.PIGGURUN  >>> com.TenPercent.PIGGURUN <<<
    signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    Abort message: 'heap corruption detected by dlfree'
        r0 00000000  r1 00001a03  r2 00000006  r3 00000000
        r4 00000006  r5 0000000b  r6 00001a03  r7 0000010c
        r8 69fe8818  r9 4158c3f8  sl 6ac00029  fp 66773d60
        ip 400f71e8  sp befdf190  lr 400b9cb9  pc 400c8cb0  cpsr 000a0010
        d0  0000000000000000  d1  0000000000000000
        d2  0000000000000000  d3  0000000000000000
        d4  0000000044958000  d5  0000000000000000
        d6  441580003f800000  d7  3f80000000000000
        d8  3f8000003f800000  d9  449580003f800000
        d10 0000000042800000  d11 0000000000000000
        d12 0000000000000000  d13 0000000000000000
        d14 0000000000000000  d15 0000000000000000
        d16 726f632070616568  d17 206e6f6974707572
        d18 3ff0000000000000  d19 0000000000000000
        d20 8000000000000000  d21 8000000000000000
        d22 0000000000000000  d23 3ff0000000000000
        d24 0000000000000000  d25 0000000000000000
        d26 0000000000000000  d27 ffffffffffffffff
        d28 0100010001000100  d29 0100010001000100
        d30 0000010000000100  d31 0000010000000100
        scr 68000013
    
    backtrace:
        #00  pc 00022cb0  /system/lib/libc.so (tgkill+12)
        #01  pc 00013cb5  /system/lib/libc.so (pthread_kill+48)
        #02  pc 00013ec9  /system/lib/libc.so (raise+10)
        #03  pc 00012a63  /system/lib/libc.so
        #04  pc 00022564  /system/lib/libc.so (abort+4)
        #05  pc 00013549  /system/lib/libc.so
        #06  pc 0000f4a1  /system/lib/libc.so
        #07  pc 00011d23  /system/lib/libc.so (dlfree+286)
        #08  pc 0000dd9b  /system/lib/libc.so (free+10)
        #09  pc 004984d0  /mnt/asec/com.TenPercent.PIGGURUN-1/lib/libunity.so
        #10  pc 00492eb0  /mnt/asec/com.TenPercent.PIGGURUN-1/lib/libunity.so
        #11  pc 00020a4c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
        #12  pc 00057689  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*,     Method const*, Thread*)+428)
        #13  pc 00000834  /dev/ashmem/dalvik-jit-code-cache (deleted)`

Is it me doing it wrong or is it caused by the plugin?

**Comment by claywilkinson** [comment]
This sounds like the native library for Play Games is not updated to match the plugin code.  Which version of the plugin are you using?  Can you delete the Assets/Plugins directory and re-import the plugin?

**Comment by szymski** [comment]
I have the latest version. I reimported it yesterday.

**Comment by claywilkinson** [comment]
@szymski - Is it working for you now?   If not, can you share the contents and file sizes in Assets/Plugins/Android/libs/armeabi-v7a and Assets/Plugins/Android/libs/x86?

**Comment by HaimBendanan** [comment]
try to follow the answer here(https://github.com/playgameservices/play-games-plugin-for-unity/issues/716)
 ihad a simmilar issue and it solved it for me

**Comment by HaimBendanan** [comment]
working now?

**Comment by claywilkinson** [comment]
Please reopen or open a new issue if this is still a problem.
