### ISSUE TITLE
REGRESSION: No callback from ReportProgress in 0.9.26

### ISSUE THREAD

**Issue by hippogamesunity** [playgameservices/play-games-plugin-for-unity#785]
Hi! I found bug regression in 0.9.26
https://github.com/playgameservices/play-games-plugin-for-unity/issues/440

Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs LINE 583
Logger.d("Steps to increment: " + numSteps);
if (numSteps > 0)
                {
                    mClient.IncrementAchievement(achievementID, numSteps, callback);
                }

SHOULD BE 

Logger.d("Steps to increment: " + numSteps);
if (numSteps >= 0)
                {
                    mClient.IncrementAchievement(achievementID, numSteps, callback);
                }

**Comment by claywilkinson** [comment]
Thanks! I'll look into it.

**Comment by hippogamesunity** [comment]
@hippogamesunity

I use call chain for reporting incremental achievements (post > callback > next post > callback ...). If numSteps = 0 this chain does not work because mClient.IncrementAchievement skipped. If my app receives no callback, it freezes.

**Comment by claywilkinson** [comment]
OK  I see, I have 2x checked it is back in there.  I'll upload the new version shortly.

**Comment by claywilkinson** [comment]
Updated in the latest build.
