### ISSUE TITLE
Plugin File Size

### ISSUE THREAD

**Issue by mliitfall** [playgameservices/play-games-plugin-for-unity#788]
Add this plugin increase about 3-4 MB on unity android apk alone, while being installed on device, its increase 3-4 times. I have a mini game build with unity 5 for 11 MB and add this plugin make it 14 MB. Its still okay, but the real problem is when installed on android, it increase to 39 MB while without the plugin it is 28 MB.
Is there a solution for this? Because im just using sign in, achievement and leaderboard. Can I remove some content not neccessary to reduce the size? I need to get as low size as possible

**Comment by claywilkinson** [comment]
Which version of Unity are you using?  We're working on using the split aar files to reduce the size, but it only works on 5+ right now.  I hope to get the update out in the next few days...

**Comment by mliitfall** [comment]
Thank you for the reply claywilkinson.
I am using Unity 5.2.0 right now. Could you explain more about that split aar?
And would you give tutorial for that too?
I really hope for reducing the size because android user often complain about the "large" size for just a simple game like mine.
Really glad if your team working into it. Thank you very much :)

**Comment by claywilkinson** [comment]
Starting with version 6.5 of Play Services, developers can selectively compile with the client libraries that are needed. See https://developers.google.com/android/guides/setup for more details.

In the plugin, the Google Play Game services client aar is added to the Unity Project, as well as the transitive closure of dependencies:
* play services base
* play services basement
* play services drive
* play services nearby
* play services plus
* android support v4
* android app compatibility v7

These aars are added to the Assets/Plugins/Android directory of the Unity project.

It makes the apk much smaller and substantially fewer dex entries.

**Comment by claywilkinson** [comment]
I pushed the new version of the plugin, so this logic is part of it.
