### ISSUE TITLE
Leaderboards User/Score desynced

### ISSUE THREAD

**Issue by B0yc3y** [playgameservices/play-games-plugin-for-unity#789]
I've used the Gplay plugin for my Android unity app and thankyou its been very helpful however when implementing our own leaderboards screen rather than using the Gplay overlay, I noticed that using the Method PlayGamePlatform.Instance.LoadScores, to save the score and user ID, then putting the user ID into 'PlayGamesPlatform.Instance.LoadUsers' method for player names appeared to scramble the names. Although the right scores were returned and the correct names were returned, each time the leaderboards were refreshed the order of the names next to each score changed.

**Comment by GroundCombo** [comment]
This is happening to us as well. On a leaderboard with two users and one score from each user, LoadScores returns the scores and userIDs correctly, but LoadUsers returns the usernames in random order when I keep reloading the leaderboard. This is a rather critical bug.

I've tried calling both LoadScores and LoadUsers twice in a row, as well as running the callbacks on the game thread, but nothing has helped so far.

**Comment by GroundCombo** [comment]
Actually, this turned out to be a stupid user error. Mapping the user ids and names from the LoadUsers call correctly into the LoadScores results (instead of blindly trusting the order) works fine; please disregard my earlier comment.

**Comment by claywilkinson** [comment]
No problem - the users and the leaderboards are stored separately and ordered differently.  I'm glad you got it working!
