### ISSUE TITLE
iOS login question

### ISSUE THREAD

**Issue by jesusviloriag** [playgameservices/play-games-plugin-for-unity#790]
Greetings,

I had a problem submitting a game to Apple's App Store (Metadata Rejected) due to the nature of the login screen to access Google Play Games Services. 

I received this message from the App Store:

3.8 - Developers are responsible for assigning appropriate ratings to their Apps. Inappropriate ratings may be changed/deleted by Apple
3.8 Details

The rating you’ve selected, 4+, is inconsistent with the content of your app. Since your application allows unfiltered access to the internet, where content with mature or suggestive themes can be accessed, it should be rated 17+.

We’ve attached screenshot(s) for your reference.
----
![temp hxwzprrn](https://cloud.githubusercontent.com/assets/10076390/10996586/c5e17aa6-8458-11e5-9508-0f840d1945ee.png)

So I would like to ask you, Is there a way to change the Login screen to a more restricted browser?

Thank you,

Viloria

**Comment by claywilkinson** [comment]
The short answer is no, there is not a way.  The longer answer is I suggest appealing this feedback.  This is using the SafariWebView, which is what Apple recommends using.  There is not unfiltered access; the address bar is readonly, you can only sign in from this page.
