### ISSUE TITLE
Failed to import package in Unity 5.2.2f1

### ISSUE THREAD

**Issue by mihaicarnu** [playgameservices/play-games-plugin-for-unity#791]
Hello,

In Unity 5.2.2.f1, selecting to import GooglePlayGamesPlugin-0.9.26.unitypackage from the current-build folder just prints out the error below:

Failed to import package with error: Couldn't decompress package

I tried this in a newly created empty project.

I've successfully imported the Facebook SDK package, that worked :-?

.. any thoughts on this?

Cheers,
Mihai

**Comment by claywilkinson** [comment]
That sounds like the file was not downloaded completely or had an error?  Did you try to download it again?

**Comment by mihaicarnu** [comment]
This time I cloned everything locally, and imported the unitypackage from there instead of downloading only that file. It was a download error indeed, now I'm seeing a different file size. I have no idea which wires got crossed before, but now it works.

**Comment by claywilkinson** [comment]
Thanks for the feedback - We'll see what we can do to make it more reliable.
