### ISSUE TITLE
Got error after import the plugin into a blank project

### ISSUE THREAD

**Issue by winghochung** [playgameservices/play-games-plugin-for-unity#792]
I got the following error after import the plugin (0.9.27 under curremt-build folder), any hints to fix it ?

System.IO.IOException: Sharing violation on path ProjectSettings\GoogleDependencyGoogle.GPGS.xml
  at System.IO.File.Delete (System.String path) [0x000b2] in /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.IO/File.cs:179 
  at Google.JarResolver.PlayServicesSupport.PersistDependencies () [0x00000] in <filename unknown>:0 
  at Google.JarResolver.PlayServicesSupport.DependOn (System.String group, System.String artifact, System.String version) [0x00000] in <filename unknown>:0 
  at GooglePlayGames.BackgroundResolution.AddDependencies () [0x00000] in F:\development\test leaderboard3\Assets\GooglePlayGames\Editor\BackgroundResolution.cs:53 
  at GooglePlayGames.BackgroundResolution..cctor () [0x0001e] in F:\development\test leaderboard3\Assets\GooglePlayGames\Editor\BackgroundResolution.cs:45 
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

**Comment by a3dline** [comment]
I get this error too

IOException: Sharing violation on path ProjectSettings\GoogleDependencyGoogle.GPGS.xml
System.IO.File.Delete (System.String path) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.IO/File.cs:179)
Google.JarResolver.PlayServicesSupport.PersistDependencies ()
Google.JarResolver.PlayServicesSupport.DependOn (System.String group, System.String artifact, System.String version)
GooglePlayGames.BackgroundResolution.AddDependencies () (at Assets/GooglePlayGames/Editor/BackgroundResolution.cs:53)

**Comment by claywilkinson** [comment]
OK - does it happen all the time, or just the first time?  This is on Windows too, right?  Which version of Unity?

**Comment by Ugobyte** [comment]
Yes! This is really annoying. I get the same errors. 

Running Unity5.2.1f1 on Windows 7 64. Trying to make an Android game. 
This same error shows up 11 times as soon as Unity launches, after a few seconds or so, more of them continue to show. They're all the same errors.
![error](https://cloud.githubusercontent.com/assets/13201425/11101915/79f3eb50-8887-11e5-861d-32348de4e155.png)


"IOException: Sharing violation on path ProjectSettings\GoogleDependencyGoogle.GPGS.xml
System.IO.File.Delete (System.String path) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.IO/File.cs:179)
Google.JarResolver.PlayServicesSupport.PersistDependencies ()
Google.JarResolver.PlayServicesSupport.DependOn (System.String group, System.String artifact, System.String version)
GooglePlayGames.BackgroundResolution.AddDependencies () (at Assets/GooglePlayGames/Editor/BackgroundResolution.cs:53)
GooglePlayGames.BackgroundResolution..cctor () (at Assets/GooglePlayGames/Editor/BackgroundResolution.cs:45)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for GooglePlayGames.BackgroundResolution
System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (RuntimeTypeHandle type) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101)
UnityEditor.EditorAssemblies.ProcessEditorInitializeOnLoad (System.Type type) (at C:/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:123)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:519)
System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:528)
System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/ConstructorInfo.cs:77)
System.Activator.CreateInstance (System.Type type, Boolean nonPublic) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Activator.cs:372)
System.Activator.CreateInstance (System.Type type) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Activator.cs:254)
UnityEditor.AssetPostprocessingInternal.InitPostprocessors (System.String pathName) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:100)
UnityEditor.DockArea:OnGUI()"

**Comment by claywilkinson** [comment]
Thanks for the details! I agree -- Verrry annoying! I'll fix it today

**Comment by Ugobyte** [comment]
Maybe this will help.

In Unity, i went to Window>Google Play Games> Setup>Android setup..

When the setup window opened, i pasted my xml code that i copied from Google console.
Directory to Save: i picked Assets
Constant Class name: I entered MyAppsName.Ach_IDs
i clicked setup and it completed. 
But i then went back and changed the Constant Class name to: MyAppsName.GPGSIds.

Now, in any C# file, when i type in MyAppsName and press (.). i get two methods:
MyAppsName.Ach_IDs & MyAppsName.GPGSIds.

I'm not sure if this help in anyway.

**Comment by claywilkinson** [comment]
Thanks. I think that is unrelated, when you change the name of the constants class, it does not delete the old one.

**Comment by claywilkinson** [comment]
@winghochung, @a3dline, @Ugobyte:
I just updated the plugin to fix this issue.  I was able to reproduce it, then once it was fixed, it worked OK.  Please update the thread when you try it out.  My windows machine is not the fastest, so I want to make sure it is not a timing thing.

Thanks for your patience!

**Comment by winghochung** [comment]
@claywilkinson 
It is working now, thanks!

**Comment by Ugobyte** [comment]
Ok cool,
I'll try it as soon as i get home. Thanks a lot for such a quick turnaround.

**Comment by Ugobyte** [comment]
@clarkwilkinson Thanks
