### ISSUE TITLE
Default GameObjectInspector is not visible after importing to the project.

### ISSUE THREAD

**Issue by MartinBenetin** [playgameservices/play-games-plugin-for-unity#795]
The main issue is that it disabled all possible prefab actions (like revert, apply ...). Please see the attached picture bellow. 
![editorinspectorincosistency](https://cloud.githubusercontent.com/assets/15797151/11118295/1c1c27a8-8941-11e5-87cb-a369dc536bd3.png)

**Comment by claywilkinson** [comment]
Delete the file Assets/GooglePlayGames/Editor/GPGGizmo.cs and it will correct this.

**Comment by MartinBenetin** [comment]
Thank you
