### ISSUE TITLE
GPGGizmo.cs breaks every GameObject in the inspector

### ISSUE THREAD

**Issue by adamlmsmith** [playgameservices/play-games-plugin-for-unity#796]
GPGGizmo.cs is an editor script that overrides the look of every GameObject in the inspector. It makes it impossible to activate/deactivate every object because that checkbox is no longer there. If I completely comment out this file, it all returns to normal.

(Screenshots included)

<img width="413" alt="with gpggizmo enabled" src="https://cloud.githubusercontent.com/assets/15817130/11119396/deeea11c-890e-11e5-9b1b-21c88331b884.png">
<img width="421" alt="with gpggizmo commented out" src="https://cloud.githubusercontent.com/assets/15817130/11119398/e267fffa-890e-11e5-8ce8-9c9e5093cdef.png">

**Comment by adamlmsmith** [comment]
I just realized this is a duplicate of issue #795, but I provided the reason for the issue.

**Comment by claywilkinson** [comment]
OK - thanks for the update - We'll remove the gizmo for now and update the plugin shortly.

**Comment by claywilkinson** [comment]
The plugin package is updated (with GPGGizmo removed).
