### ISSUE TITLE
build fail on IOS with new plug in version ( 0.9.27)

### ISSUE THREAD

**Issue by HaimBendanan** [playgameservices/play-games-plugin-for-unity#800]
on xcode, i get the following error:
Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/roncohen/Library/Developer/Xcode/DerivedData/Unity-iPhone-gbbkmwqghwptlleyntvoloxdaklx/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/touchit (No such file or directory)

and the following linker error:
ld: bitcode bundle could not be generated because '/Users/roncohen/Documents/Programming/iOS/Tigabo/tigabo new build/touchit iphone/ios build/Pods/GoogleSignIn/Libraries/libGIPNSURL+FIFE.a(NSURL+FIFE.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

any ideas?

**Comment by HaimBendanan** [comment]
found this:
http://stackoverflow.com/questions/29574471/missing-64-bit-support-and-lipo-error-cant-open-input-file-in-xcode-6-3
could be  a problem in one the plugin librarie

**Comment by HaimBendanan** [comment]
i rolled back to 0.9.26, solved my problem. before rolling back, i tried to set enable bitcode to both YES/NO, didnt helped.

**Comment by claywilkinson** [comment]
The latest version of the plugin 0.9.30, addresses the build issues with ios9 and xcode 7.
