### ISSUE TITLE
Unity inspector missing "Apply Button", "Enable checkbox" and etc after installing this plugin

### ISSUE THREAD

**Issue by winghochung** [playgameservices/play-games-plugin-for-unity#806]
plugin version 0.9.27
unity version 5.2.2f1

Attached a screen capture 
http://postimg.org/image/cq6lvnmn7/

any help would be appreciated

**Comment by Pourcentage** [comment]
Hi!
In the file "GooglePlayGames/Editor/GPGGizmo.cs" comment the line `[CustomEditor(typeof(GameObject))]`

**Comment by claywilkinson** [comment]
Yep, if you download the plugin package again, the file GPGGizmo is removed - it caused way too much trouble.

**Comment by winghochung** [comment]
it works! thanks.

**Comment by shaunliz** [comment]
I have too !!
// Pourcentage : thank you ~
