### ISSUE TITLE
Achievements array is not the same as how it was setup in Google console.

### ISSUE THREAD

**Issue by Ugobyte** [playgameservices/play-games-plugin-for-unity#808]
(1) In the Google console where you set up your achievements, points and description, i set up all my achievements as:

Achievement #1 Win 1 race
Achievement #2 Win 2 races 
Achievement #3 Win 3 races
Achievement #4 Win 4 races
Achievement #5 Win 5 races
Achievement #6 Win 6 races

(2) In my code, i log in like this:

PlayGamesPlatform.Activate();
Social.localUser.Authenticate(ProcessAuthenticationCallBack);

void ProcessAuthenticationCallBack(bool Result)
{
       if(Result)
	{
		Social.LoadAchievementDescriptions( ProcessLoadAchievementDescriptionCallBack );
	}
	else
	{
		print("Failed to authenticate user on Google Play services");
	}
}

void ProcessLoadAchievementDescriptionCallBack(IAchievementDescription[] AchievementDesc )
{
		GlobalAchievementDescList = AchievementDesc;
}

(3) When i print the contents of GlobalAchievementDescList[] array, i get:
GlobalAchievementDescList[0] = Achievement #3 Win 3 races.
GlobalAchievementDescList[1] = Achievement #1 Win 1 race.
GlobalAchievementDescList[2] = Achievement #2 Win 2 races.
GlobalAchievementDescList[3] = Achievement #4 Win 4 races.
GlobalAchievementDescList[4] = Achievement #5 Win 5 races.
GlobalAchievementDescList[5] = Achievement #6 Win 6 races.

Index 3 is at the top and index 1 and 2 are shifted down.

Is anyone else experiencing this issue?

**Comment by Ugobyte** [comment]
FOUND/SOLVED IT!

It turns out that the IAchievementDescription[] array received during the callback has the Achievements in order of time when they were achieved. 
Which means IAchievementDescription[0] = the latest achieved achievement. 

This was confusing because i'm used to Apples Gamecenter. In Gamecenter, the IAchievementDescription[] array always has the achievement in the order you created them in iTunes Connect. So no matter which or when you accomplish an achievement, the list is always ordered how you created them.

Mods, you can mark this issue as completed.

**Comment by claywilkinson** [comment]
Thanks for the  follow up info!  I'm going to keep it open long enough to get the documentation updated.
