### ISSUE TITLE
Unity 5.3 namespace conflict

### ISSUE THREAD

**Issue by mmoczkowski** [playgameservices/play-games-plugin-for-unity#809]
There is a namespace conflict in Unity 5.3 between UnityEngine.Logger and OurUtils.Logger. The solution to that is to replace all Logger.* references to OurUtils.Logger.*

**Comment by claywilkinson** [comment]
Thanks! Haven't started testing with 5.3 yet.  Feel free to submit a pull request with the changes.

**Comment by claywilkinson** [comment]
I updated the packages, 0.9.27a has the Logger scoped correctly for 5.3
