### ISSUE TITLE
Auth cause ClassNotFoundException on GameHelper.

### ISSUE THREAD

**Issue by naamchan** [playgameservices/play-games-plugin-for-unity#81]
I have follow document to install and configure but can't seem to make it work, 
even on Minimal project. I'm using Unity 4.3.3f1 and latest version of Google Play Game plugin with Android 4.0.4.

Here is the logcat

03-27 16:32:29.257: I/Unity(13570): [Play Games Plugin DLL] Creating platform-specific Play Games client.
03-27 16:32:29.387: I/Unity(13570): [Play Games Plugin DLL] Making sure PlayGamesHelperObject is ready.
03-27 16:32:29.417: I/Unity(13570): [Play Games Plugin DLL] Initializing Android Client.
03-27 16:32:29.417: I/Unity(13570): [Play Games Plugin DLL] Creating GameHelperManager to manage GameHelper.
03-27 16:32:29.427: I/Unity(13570): [Play Games Plugin DLL] Setting up GameHelperManager.
03-27 16:32:29.427: I/Unity(13570): [Play Games Plugin DLL] GHM creating GameHelper.
03-27 16:32:29.447: I/Unity(13570): [Play Games Plugin DLL] PlayGamesHelperObject created.
03-27 16:32:29.447: I/Unity(13570): [Play Games Plugin DLL] AUTH: starting auth process, silent=False
03-27 16:32:29.457: I/Unity(13570): [Play Games Plugin DLL] GHM calling GameHelper constructor with flags=7
03-27 16:32:29.647: I/Unity(13570): AndroidJavaException: java.lang.ClassNotFoundException: com.google.example.games.basegameutils.GameHelper
03-27 16:32:29.647: I/Unity(13570):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
03-27 16:32:29.647: I/Unity(13570):   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0 
03-27 16:32:29.647: I/Unity(13570):   at UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
03-27 16:32:29.647: I/Unity(13570):   at UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
03-27 16:32:29.647: I/Unity(13570):   at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x00000] in <filename unknown>:0 
03-27 16:32:29.647: I/Unity(13570):   at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) [0x00000] in <filename unknown>:0 
03-27 16:32:29.647: I/Unity(13570):   at UnityEngine.AndroidJavaObject..ctor (System.String className, System.Object[] args) [0x00000] in <filename unknown>:0 
03-27 16:32:29.647: I/Unity(13570):   at GooglePlayGames.A
03-27 16:32:29.657: I/Unity(13570): NullReferenceException: Object reference not set to an instance of an object
03-27 16:32:29.657: I/Unity(13570):   at GooglePlayGames.Android.AndroidClient+<Authenticate>c__AnonStorey17.<>m__1 () [0x00000] in <filename unknown>:0 
03-27 16:32:29.657: I/Unity(13570):   at UnityEngine.AndroidJavaRunnableProxy.run () [0x00000] in <filename unknown>:0 
03-27 16:32:29.657: I/Unity(13570):   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
03-27 16:32:29.657: I/Unity(13570): Rethrow as TargetInvocationException: UnityEngine.AndroidJavaRunnableProxy.run()
03-27 16:32:29.657: I/Unity(13570):   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
03-27 16:32:29.657: I/Unity(13570):   at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, UnityEngine.AndroidJavaObject[] javaArgs) [0x00000] in <filename unknown>:0 
03-27 16:32:29.657: I/Unity(13570):   at UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, IntPtr jmethodName, IntPtr jargs) [0x00000] in <filename unknown>:0

**Comment by claywilkinson** [comment]
Closing since this is obsolete - the plugin uses the C++ library now.
