### ISSUE TITLE
Failed to repackage resources in v0.9.27

### ISSUE THREAD

**Issue by tsx5000** [playgameservices/play-games-plugin-for-unity#810]
After upgrading my project to the new plugin, i keep getting this error : Failed to repackage resources.
I tried it on a new empty project too. Any help ?

<code>
CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Android SDK\sdk\build-tools\21.1.1\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Android SDK/sdk\platforms\android-21\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.google.example.games.mainlibproj:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.plus:android.support.v4 -S "D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res" -S "D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\play-services-base-8.3.0\res" -S "D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\play-services-basement-8.3.0\res" -S "D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\play-services-drive-8.3.0\res" -S "D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\play-services-games-8.3.0\res" -S "D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\play-services-nearby-8.3.0\res" -S "D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\play-services-plus-8.3.0\res" -S "D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\support-v4-23.1.1\res"

stderr[
D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\values-v23\values-v23.xml:5: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\values-v23\values-v23.xml:30: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: C:\Android SDK\sdk\platforms\android-21\android.jar
applyFileOverlay for drawable
trying overlaySet Key=ic_plusone_medium_off_client.png
trying overlaySet Key=ic_plusone_small_off_client.png
trying overlaySet Key=ic_plusone_standard_off_client.png
trying overlaySet Key=ic_plusone_tall_off_client.png
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_ic_googleplayservices.png
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_icon_light.xml
trying overlaySet Key=common_google_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_google_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_light_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark.xml
trying overlaySet Key=common_plus_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light.xml
trying overlaySet Key=common_plus_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark.xml
trying overlaySet Key=common_plus_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_light.xml
trying overlaySet Key=common_plus_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_pressed.9.png
trying overlaySet Key=abc_ab_share_pack_mtrl_alpha.9.png
trying overlaySet Key=abc_action_bar_item_background_material.xml
trying overlaySet Key=abc_btn_borderless_material.xml
trying overlaySet Key=abc_btn_check_material.xml
trying overlaySet Key=abc_btn_check_to_on_mtrl_000.png
trying overlaySet Key=abc_btn_check_to_on_mtrl_015.png
trying overlaySet Key=abc_btn_colored_material.xml
trying overlaySet Key=abc_btn_default_mtrl_shape.xml
trying overlaySet Key=abc_btn_radio_material.xml
trying overlaySet Key=abc_btn_radio_to_on_mtrl_000.png
trying overlaySet Key=abc_btn_radio_to_on_mtrl_015.png
trying overlaySet Key=abc_btn_rating_star_off_mtrl_alpha.png
trying overlaySet Key=abc_btn_rating_star_on_mtrl_alpha.png
trying overlaySet Key=abc_btn_switch_to_on_mtrl_00001.9.png
trying overlaySet Key=abc_btn_switch_to_on_mtrl_00012.9.png
trying overlaySet Key=abc_cab_background_internal_bg.xml
trying overlaySet Key=abc_cab_background_top_material.xml
trying overlaySet Key=abc_cab_background_top_mtrl_alpha.9.png
trying overlaySet Key=abc_control_background_material.xml
trying overlaySet Key=abc_dialog_material_background_dark.xml
trying overlaySet Key=abc_dialog_material_background_light.xml
trying overlaySet Key=abc_edit_text_material.xml
trying overlaySet Key=abc_ic_ab_back_mtrl_am_alpha.png
trying overlaySet Key=abc_ic_clear_mtrl_alpha.png
trying overlaySet Key=abc_ic_commit_search_api_mtrl_alpha.png
trying overlaySet Key=abc_ic_go_search_api_mtrl_alpha.png
trying overlaySet Key=abc_ic_menu_copy_mtrl_am_alpha.png
trying overlaySet Key=abc_ic_menu_cut_mtrl_alpha.png
trying overlaySet Key=abc_ic_menu_moreoverflow_mtrl_alpha.png
trying overlaySet Key=abc_ic_menu_paste_mtrl_am_alpha.png
trying overlaySet Key=abc_ic_menu_selectall_mtrl_alpha.png
trying overlaySet Key=abc_ic_menu_share_mtrl_alpha.png
trying overlaySet Key=abc_ic_search_api_mtrl_alpha.png
trying overlaySet Key=abc_ic_voice_search_api_mtrl_alpha.png
trying overlaySet Key=abc_item_background_holo_dark.xml
trying overlaySet Key=abc_item_background_holo_light.xml
trying overlaySet Key=abc_list_divider_mtrl_alpha.9.png
trying overlaySet Key=abc_list_focused_holo.9.png
trying overlaySet Key=abc_list_longpressed_holo.9.png
trying overlaySet Key=abc_list_pressed_holo_dark.9.png
trying overlaySet Key=abc_list_pressed_holo_light.9.png
trying overlaySet Key=abc_list_selector_background_transition_holo_dark.xml
trying overlaySet Key=abc_list_selector_background_transition_holo_light.xml
trying overlaySet Key=abc_list_selector_disabled_holo_dark.9.png
trying overlaySet Key=abc_list_selector_disabled_holo_light.9.png
trying overlaySet Key=abc_list_selector_holo_dark.xml
trying overlaySet Key=abc_list_selector_holo_light.xml
trying overlaySet Key=abc_menu_hardkey_panel_mtrl_mult.9.png
trying overlaySet Key=abc_popup_background_mtrl_mult.9.png
trying overlaySet Key=abc_ratingbar_full_material.xml
trying overlaySet Key=abc_scrubber_control_off_mtrl_alpha.png
trying overlaySet Key=abc_scrubber_control_to_pressed_mtrl_000.png
trying overlaySet Key=abc_scrubber_control_to_pressed_mtrl_005.png
trying overlaySet Key=abc_scrubber_primary_mtrl_alpha.9.png
trying overlaySet Key=abc_scrubber_track_mtrl_alpha.9.png
trying overlaySet Key=abc_seekbar_thumb_material.xml
trying overlaySet Key=abc_seekbar_track_material.xml
trying overlaySet Key=abc_spinner_mtrl_am_alpha.9.png
trying overlaySet Key=abc_spinner_textfield_background_material.xml
trying overlaySet Key=abc_switch_thumb_material.xml
trying overlaySet Key=abc_switch_track_mtrl_alpha.9.png
trying overlaySet Key=abc_tab_indicator_material.xml
trying overlaySet Key=abc_tab_indicator_mtrl_alpha.9.png
trying overlaySet Key=abc_text_cursor_material.xml
trying overlaySet Key=abc_textfield_activated_mtrl_alpha.9.png
trying overlaySet Key=abc_textfield_default_mtrl_alpha.9.png
trying overlaySet Key=abc_textfield_search_activated_mtrl_alpha.9.png
trying overlaySet Key=abc_textfield_search_default_mtrl_alpha.9.png
trying overlaySet Key=abc_textfield_search_material.xml
trying overlaySet Key=app_banner.png
trying overlaySet Key=app_icon.png
applyFileOverlay for layout
trying overlaySet Key=abc_action_bar_title_item.xml
trying overlaySet Key=abc_action_bar_up_container.xml
trying overlaySet Key=abc_action_bar_view_list_nav_layout.xml
trying overlaySet Key=abc_action_menu_item_layout.xml
trying overlaySet Key=abc_action_menu_layout.xml
trying overlaySet Key=abc_action_mode_bar.xml
trying overlaySet Key=abc_action_mode_close_item_material.xml
trying overlaySet Key=abc_activity_chooser_view.xml
trying overlaySet Key=abc_activity_chooser_view_list_item.xml
trying overlaySet Key=abc_alert_dialog_button_bar_material.xml
trying overlaySet Key=abc_alert_dialog_material.xml
trying overlaySet Key=abc_dialog_title_material.xml
trying overlaySet Key=abc_expanded_menu_layout.xml
trying overlaySet Key=abc_list_menu_item_checkbox.xml
trying overlaySet Key=abc_list_menu_item_icon.xml
trying overlaySet Key=abc_list_menu_item_layout.xml
trying overlaySet Key=abc_list_menu_item_radio.xml
trying overlaySet Key=abc_popup_menu_item_layout.xml
trying overlaySet Key=abc_screen_content_include.xml
trying overlaySet Key=abc_screen_simple.xml
trying overlaySet Key=abc_screen_simple_overlay_action_mode.xml
trying overlaySet Key=abc_screen_toolbar.xml
trying overlaySet Key=abc_search_dropdown_item_icons_2line.xml
trying overlaySet Key=abc_search_view.xml
trying overlaySet Key=abc_select_dialog_material.xml
trying overlaySet Key=notification_media_action.xml
trying overlaySet Key=notification_media_cancel_action.xml
trying overlaySet Key=notification_template_big_media.xml
trying overlaySet Key=notification_template_big_media_narrow.xml
trying overlaySet Key=notification_template_lines.xml
trying overlaySet Key=notification_template_media.xml
trying overlaySet Key=notification_template_part_chronometer.xml
trying overlaySet Key=notification_template_part_time.xml
trying overlaySet Key=select_dialog_item_material.xml
trying overlaySet Key=select_dialog_multichoice_material.xml
trying overlaySet Key=select_dialog_singlechoice_material.xml
trying overlaySet Key=support_simple_spinner_dropdown_item.xml
applyFileOverlay for anim
trying overlaySet Key=abc_fade_in.xml
trying overlaySet Key=abc_fade_out.xml
trying overlaySet Key=abc_grow_fade_in_from_bottom.xml
trying overlaySet Key=abc_popup_enter.xml
trying overlaySet Key=abc_popup_exit.xml
trying overlaySet Key=abc_shrink_fade_out_from_bottom.xml
trying overlaySet Key=abc_slide_in_bottom.xml
trying overlaySet Key=abc_slide_in_top.xml
trying overlaySet Key=abc_slide_out_bottom.xml
trying overlaySet Key=abc_slide_out_top.xml
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_plus_signin_btn_text_dark.xml
trying overlaySet Key=common_plus_signin_btn_text_light.xml
trying overlaySet Key=abc_background_cache_hint_selector_material_dark.xml
trying overlaySet Key=abc_background_cache_hint_selector_material_light.xml
trying overlaySet Key=abc_color_highlight_material.xml
trying overlaySet Key=abc_primary_text_disable_only_material_dark.xml
trying overlaySet Key=abc_primary_text_disable_only_material_light.xml
trying overlaySet Key=abc_primary_text_material_dark.xml
trying overlaySet Key=abc_primary_text_material_light.xml
trying overlaySet Key=abc_search_url_text.xml
trying overlaySet Key=abc_secondary_text_material_dark.xml
trying overlaySet Key=abc_secondary_text_material_light.xml
trying overlaySet Key=switch_thumb_material_dark.xml
trying overlaySet Key=switch_thumb_material_light.xml
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-mdpi\abc_ab_share_pack_mtrl_alpha.9.png
Processing image: D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-hdpi\abc_ab_share_pack_mtrl_alpha.9.png
Processing image: D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xhdpi\abc_ab_share_pack_mtrl_alpha.9.png
Processing image: D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xxhdpi\abc_ab_share_pack_mtrl_alpha.9.png
    (processed image D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-hdpi\abc_ab_share_pack_mtrl_alpha.9.png: 256% size of source)
Processing image: D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-mdpi\abc_btn_check_to_on_mtrl_000.png
    (processed image D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xhdpi\abc_ab_share_pack_mtrl_alpha.9.png: 253% size of source)
    (processed image D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-mdpi\abc_ab_share_pack_mtrl_alpha.9.png: 253% size of source)
    (processed image D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-mdpi\abc_btn_check_to_on_mtrl_000.png: 134% size of source)
Processing image: D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-hdpi\abc_btn_check_to_on_mtrl_000.png
    (processed image D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xxhdpi\abc_ab_share_pack_mtrl_alProcessing image: D:\Projects\Unity\GPGSTephst\Ta.9.pemngp: \Sta23g6i% snigAze roefa\ ansdroourceid)-
libraries\appcompat-v7-23.1.1\res\drawable-xhdpi\abc_btn_check_to_on_mtrl_000.png
Processing image: D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xxhdpi\abc_btn_check_to_on_mtrl_000.png
Processing image: D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xxxhdpi\abc_btn_check_to_on_mtrl_000.png
    (processed image D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-hdpi\abc_btn_check_to_on_mtrl_000.png: 134% size of source)
    (processed image D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xhdpi\abc_btn_check_to_on_mtrl_000.png: 125% size of source)
Processing image: D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-mdpi\abc_btn_check_to_on_mtrl_015.png
    (processed image D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-mdpi\abc_btn_check_to_on_mtrl_015.png: 133% size of source)
Processing image: D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-hdpi\abc_btn_check_to_on_mtrl_015.png
    (processed image D:\Projects\Unity\GPGSTest\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable-xxhdpi\abc_btn_check_to_on_mtrl_000.png: 119% size of source)
    (processed image D:\Projects\Unity\GPGSTest\Temp\Sta<message truncated>
</code>

**Comment by T3r0** [comment]
I had the same issue with the new version. I fixed that by downloading and updating the packages from the sdk manager. Now I have nearly every package installed and it works. I don't know which package did it because before downloading them I thought I had all required packages.

**Comment by tsx5000** [comment]
I have already updated Android Support Repository, Android Support Library, Google Play Services and Google Repository.
Do I need to install any other packages ?

**Comment by tsx5000** [comment]
Finally found a solution. i updated Android SDK Build Tools and Installed the API 23 (Android 6.0) SDK and APIs and then I could make the build succesfully.
@T3r0  Thanks for the hint.

**Comment by emran17** [comment]
@tsx5000 
tanx, it worked for me too.
