### ISSUE TITLE
Achievements and leaderboards screen doesn't close

### ISSUE THREAD

**Issue by manuelmele** [playgameservices/play-games-plugin-for-unity#812]
Hi,
I can't sometimes close achievements and leaderboards screen. In other words once I close the screen it will appear again. Otherwise sometimes I don't have this problem and everything works fine.

Thanks in advance!

**Comment by claywilkinson** [comment]
Hmm. That sounds like there might be something  that is calling the method to display the UI in Update(), so it gets called multiple times?

**Comment by manuelmele** [comment]
Yep! You were right! I fixed it now ;)

Thanks
