### ISSUE TITLE
Quickmatch (Random opponent) major bug?

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#813]
This is very very strange. And even more strange that it seems that im the only one experiencing this...

I have a sony z1 smartphone and a sony z3 tablet (and ofcourse different google test accounts). When starting matches with invites everything works well, but if they start by the quick match (random) function things go really bananas. The smartphone recognice the tablet player username and profile picture correct, but the tablet gets both the user image and the username of the smartphone user wrong. Instead it picks a blue or green generic avatar as the profile picture and the name is just "player" followed by a random 3-4 digit number. The number is different for every new match.

![screenshot_2015-11-17-21-17-58](https://cloud.githubusercontent.com/assets/10234700/11223582/fde8703c-8d70-11e5-9831-c76046bef9b9.png)

**Comment by claywilkinson** [comment]
Yes it is strange, but you are not alone :) This behavior is actually expected.  It is a weird side effect of how quick matchmaking works and permission checks.  I don't know the details, but when it comes to sharing identity, things tend to be conservative, thus the non-obvious behavior.

I've passed your feedback along to the engineering team.  Thanks for posting.
