### ISSUE TITLE
Crash with Google Admob plugin

### ISSUE THREAD

**Issue by spaceduck0316** [playgameservices/play-games-plugin-for-unity#814]
Hi,
I've been using this plugin
and recently I got to add admit plugin to my project.

https://github.com/googleads/googleads-mobile-unity

Each plugin works well alone,
but when I put them together, admob crashes with InterstitialAd().

My log is here.

https://dl.dropboxusercontent.com/u/39962281/log_spaceduck_151118.txt

I tried to solve this problem several days, but still have no idea.
Please help me to fix this issue.
Thanks.

**Comment by spaceduck0316** [comment]
I solved it.

I add play-services-ads to GPGS/Editor/BackgroundResolution.cs, to let GPGS imports the ads library.
<b>And I needed to remove some of Plugin/Android/GoogleMobileAdsPlugin/AndroidManifest.xml</b> (as it cause merging conflict)
"\<activity android:name="com.google.android.gms.ads.AdActivity" ... /\>
 \<activity android:name="com.google.android.gms.ads.purchase.InAppPurchaseActivity".../\>"

Thanks.

**Comment by claywilkinson** [comment]
Great news @spaceduck0316 - Thanks for the details.  We're working on making the the Google plugins work seamlessly together (imagine that!) and there should be an update soon.

**Comment by kd7uiy** [comment]
I can confirm that the two steps seem to resolve the issue. Note that the added play-services-ads goes in the AddDependencies, and that with that, you no longer need to copy over the libproject. Thanks for figuring this temporary solution out!

**Comment by XblakninjaX** [comment]
I followed both thing and still got a error after the manafest thing.  it failed to re package resources and idk what to do

**Comment by claywilkinson** [comment]
@XblakninjaX  - I'd suggest following the instructions again.  Sometimes closing Unity and then re-opening it will reinitialize the plugins loaded from DLLs which may help.  We are working on updates to the plugins so this workaround will no longer be needed.

**Comment by joserocha3** [comment]
@XblakninjaX @claywilkinson I could not get it added either even though I placed "gms:play-services-ads" in the AddDependencies method. I still received the error. I had to remove the code I added and manually add the aar file from the file path below:

[your skd path]\extras\google\m2repository\com\google\android\gms\play-services-ads\8.3.0

**Comment by kunal01** [comment]
I added this line in BackgroundResolution.cs in AddDependencies() function
svcSupport.DependOn("com.google.android.gms","play-services-ads",PluginVersion.PlayServicesVersionConstraint);

but still i'm getting 4 resolutionexception Cannot find candidate artifact for com.google.android.gms:play-services-ads:8.1+

so what can i do?

**Comment by joserocha3** [comment]
@kunal01 Please see my comment right above yours, maybe it will help. Good luck!

**Comment by kunal01** [comment]
@joserocha3 
there is no folder named m2repository in my sdk.

**Comment by joserocha3** [comment]
@kunal01 do you have your Sdk up to date for play services? Try looking around for a file named play-services-ads-8.3.0.aar it might me a different location for some reason.

8.3.0 would be the latest version. If you find a lower one then your Sdk is not up to date.

**Comment by kunal01** [comment]
@joserocha3 
sorry no luck

**Comment by edgarscr** [comment]
i removed the <activity android:name="com.google.android.gms.ads.purchase.InAppPurchaseActivity".../>" and can compiled but i dont see my Banner ADS

**Comment by MadJlzz** [comment]
Hi,

I've tried the solution above but my application keep crashing as soon as I try to launch it.
The compilation works fine though.

**Comment by edgarscr** [comment]
i have a issues. i dont see banners..

**Comment by claywilkinson** [comment]
@edgarscr - can you open an new issue please?  Can you share the log?

**Comment by slamet** [comment]
let's see it's clear, explain step by step
https://ndesostyle.wordpress.com/2016/02/10/conflict-with-latest-googleads-mobile-and-play-games-plugin-for-unity/

**Comment by Ranttal** [comment]
**I solved it**,. 
I had the same issue and didn't find any solution regarding that, but later I tried resolving android jar files using android resolver by right clicking in **

> project window\playServiceResolver\androidResolver\Resolve

** and after resolution succeeded I build an apk and that runs perfectly.
