### ISSUE TITLE
Load Leaderboard Scores

### ISSUE THREAD

**Issue by xike456** [playgameservices/play-games-plugin-for-unity#815]
I have problem loading leaderboard score. I use PlayGamesPlatform.Instance.LoadScores(), the result of data return:
data.Valid = true;
data.Status = Success;
data.id = <My leaderboardID>
I cant get the Scores and PlayerScores. These value always return null.
I use plugin 0.9.25

**Comment by Ugobyte** [comment]
Are you trying to load everyones score or are you trying to load just your local players score?

I works for me when i try loading the local players score.
I will post code when i get home.

**Comment by quangfuky** [comment]
Today i tried to use 0.9.27 on Unity 4.6.7 and i got what i need. The problem of 0.9.27 on Unity 4.6.7 is that some jar file have same class and i have it fixed. So now everything works as it should. Sr for my bad english.

**Comment by quangfuky** [comment]
#807

**Comment by Ugobyte** [comment]
// Global variables
public static ILeaderboard HighScoreLeaderboard;
public static int MyHighScore;


        private void loadLeaderboards()
	{
		// Do not get leaderboards if the app is running on Unity editor.
		if(Application.isEditor){return;}
		
		// Check if user is logged in.
		if(Social.localUser.authenticated){ getHighScoreFromLeaderboard(); }
	}
	private void getHighScoreFromLeaderboard()
	{
		string[] UserFilter = { Social.localUser.id}; // Get the local player username
		HighScoreLeaderboard = PlayGamesPlatform.Instance.CreateLeaderboard(); // initiate 
		HighScoreLeaderboard.id = XCgkIXcX2j6UXXAIQGA; // The string ID from Google console
		HighScoreLeaderboard.SetUserFilter(UserFilter); // Filter out other players
		HighScoreLeaderboard.LoadScores(RWResult =>
		{
		   if(RWResult)
		   {
				updateHighScoreStoredOnDevice();
		   }
		});
	}

       // This function updates the local high score on the device with the value retrieved from the leaderboard
	private void updateHighScoreOnDevice()
	{
		// Update the Races won local variable with data pulled from online races won leaderboard.
		MyHighScore = (int) HighScoreLeaderboard.localUserScore.value; 		 
	}

**Comment by Ugobyte** [comment]
That's how i do mine and it works. This isn't exactly what you're looking for but i hope it helps.

**Comment by claywilkinson** [comment]
Please re-open if there are still issues.
