### ISSUE TITLE
friends is always empty

### ISSUE THREAD

**Issue by fractalfrenzy** [playgameservices/play-games-plugin-for-unity#817]
Hello,

I'm executing this code to log in a user and get a list of their friends.

void Start()
	{
		Debug.Log ("Autehenticate");
		Social.localUser.Authenticate((bool success) => {
			Debug.Log ("success: " + success);
			if (success)
			{
				Debug.Log ("Username: " + Social.localUser.userName);
				Debug.Log ("User ID: " + Social.localUser.id);
				Debug.Log ("IsUnderage: " + Social.localUser.underage);
				Social.localUser.LoadFriends((ok) =>  {
					Debug.Log("Friends loaded OK: " + ok);
					Debug.Log ("Social.localUser.friends.length: " + Social.localUser.friends.Length);
					foreach(IUserProfile p in Social.localUser.friends) {
						Debug.Log(p.userName + " is a friend");  
					}   
				});
			}
		});
	}

For some reason, friends.length is always 0 and there is nothing in the array.  The account I'm logging in to is following a bunch of people.  (I'm not really sure if following is the same as friends in Google play).  Any help will be appreciated. Thanks.

**Comment by claywilkinson** [comment]
This API uses [loadConnectedPlayers()](https://developers.google.com/android/reference/com/google/android/gms/games/Players.html#loadConnectedPlayers(com.google.android.gms.common.api.GoogleApiClient, boolean)) to load the list.  Most likely it is a game profile visibility or they have not played the game yet?

**Comment by fractalfrenzy** [comment]
Ah, I thought it showed all friends, not just those who've played the game. Thanks.
