### ISSUE TITLE
Failed re-population of field accessed by GetUserEmail(), on repeated login.

### ISSUE THREAD

**Issue by sebastianherscher** [playgameservices/play-games-plugin-for-unity#819]
When logging in for the first time using play services, the PlayGamesPlayform.Instance.GetUserEmail() returns the user's email after it is populated (which, correct me if I'm wrong, happens asynchronously). 
After logging out using PlayGamesPlatform.SignOut(), the field is set to either null or "". 

However, after logging back in with either the same account or a different one, whatever field is referenced by GetUserEmail() is not repopulated.

((PlayGamesLocalUser)Social.localUser).Email is also not re-populated.

**Comment by claywilkinson** [comment]
Can you share a log of the problem?  I built and ran the SmokeTest sample.  I logged in as player "A", clicked "User Info" and saw the correct email address.  Then I signed out and authenticated again as player "A".  I saw the correct email.  Then I signed out, authenticated as player "B" and went to User Info and saw player "B"'s email address.

**Comment by sebastianherscher** [comment]
I've solved the error on my side, by using the SmokeTest sign out code: 

((PlayGamesPlatform)Social.Active).SignOut();

However, it's still worth noting:

PlayGamesPlatform.Instance.SignOut()

signs the user out, but causes the bug I mentioned before, where the next user sign in is broken. Your documentation recommends to use this workflow, and the 1st one listed above is tough to find (only found it via the SmokeTest demo.)

**Comment by claywilkinson** [comment]
Interesting!  Thanks for the feeback.  I'll take a look and see if the code or the documentation (or both) should be updated.

**Comment by sebastianherscher** [comment]
Thanks for the response too - I probably wouldn't have found that solution without you directing me to the SmokeTest demo.

**Comment by claywilkinson** [comment]
Hi @sebastianherscher  - I just tried replacing the line in SmokeTest with Platform.Instance.SignOut(), and it worked fine.  I looked again at the code.  Are you calling `PlayGamesPlatform.Activate();`?  This just simply assigns PlayGames.Instance to Social.Active, so they should be equal.
