### ISSUE TITLE
Achievement not found! (Unity)

### ISSUE THREAD

**Issue by garv3** [playgameservices/play-games-plugin-for-unity#82]
If I try to save the progress of an achievement, I get the following warning:
~~~
!!! [Play Games Plugin DLL]  WARNING: Achievement ID not found in bank: id CgkIq6rKo6wTEAIQFA
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:LogWarning(Object)
GooglePlayGames.OurUtils.Logger:w(String) (at D:\Users\Garvin\Documents\Unity3D Projekte\PlayStore\Jumpy\Assets\GooglePlayGames\OurUtils\Logger.cs:41)
GooglePlayGames.Android.AchievementBank:GetAchievement(String) (at D:\Users\Garvin\Documents\Unity3D Projekte\PlayStore\Jumpy\Assets\GooglePlayGames\Platforms\Android\AchievementBank.cs:81)
GooglePlayGames.Android.AndroidClient:GetAchievement(String) (at D:\Users\Garvin\Documents\Unity3D Projekte\PlayStore\Jumpy\Assets\GooglePlayGames\Platforms\Android\AndroidClient.cs:471)
GooglePlayGames.Android.AndroidClient:IncrementAchievement(String, Int32, Action`1) (at D:\Users\Garvin\Documents\Unity3D Projekte\PlayStore\Jumpy\Assets\GooglePlayGames\Platforms\Android\AndroidClient.cs:455)
GooglePlayGames.PlayGamesPlatform:IncrementAchievement(String, Int32, Action`1) (at D:\Users\Garvin
~~~
The achievement is connected to the app, the id is correct and the achievement is even shown in the achievement UI!
The success boolean of PlayGamesPlatform.IncrementAchievement() is TRUE but the progress is not saved.

I activated debug logging and found this:
~~~
...
[Play Games Plugin DLL] AchievementBank: processed: [Achievement] id=CgkIyInWttkVEAIQCA, name=60 seconds surviver, desc=Survive 60 seconds in one game!, type=STANDARD,  revealed=True, unlocked=False, steps=0/0
...
[Play Games Plugin DLL] AchievementBank: bank now contains 9 entries.
~~~
The given id matches the id in the IncrementAchievement-call perfectly. So why can the IncrementAchievement-call not access the bank or find the achievement in it?

**Comment by kreso22** [comment]
Got same problem as @garbagepit
I have latest version of GPS SDK, everything set up properly on Dev console (few days ago, so should be active).

Any clues?

    W/Unity   (32272): !!! [Play Games Plugin DLL] 04/23/15 1:28:39 -07:00 WARNING: Unable to locate achievement CXXXXXXWigEQAhAB
    W/Unity   (32272): !!! [Play Games Plugin DLL] 04/23/15 1:28:39 -07:00 WARNING: As a quick fix, assuming it's standard.
    I/Unity   (32272):  [Play Games Plugin DLL] 04/23/15 1:28:39 -07:00 DEBUG: Progress 100 interpreted as UNLOCK.
    I/Unity   (32272):  [Play Games Plugin DLL] 04/23/15 1:28:39 -07:00 DEBUG: Could not Unlock, no achievement with ID CXXXXXXWigEQAhAB

**Comment by artjas** [comment]
kreso22 I don't understand your edit, could you explain?

**Comment by abatilo** [comment]
He didn't have "using GooglePlayGames;" in his code.

**Comment by artjas** [comment]
OK I thought code will not compile without, it's not working for me latest gpg plugin unity 5
