### ISSUE TITLE
How can I get Auth Token?

### ISSUE THREAD

**Issue by buihuuloc** [playgameservices/play-games-plugin-for-unity#820]
Hi,
How can I get Auth Token?

I used `PlayGamesPlatform.Activate().GetAccessToken()`, but It doesn't work.

**Comment by claywilkinson** [comment]
Did you configure a web client id in the Play Games Console and then configure it in your game?  Without this client id you cannot get an access token.  Can you share the log of when you call GetAccessToken()? The log should also have some error message that will indicate the issue.
