### ISSUE TITLE
Invalid SnapshotMetadata when trying to create a new Saved Game

### ISSUE THREAD

**Issue by percytse** [playgameservices/play-games-plugin-for-unity#822]
Hi,

I tried to integrate Saved Game on Cloud.
After choosing Save New Game on Google play UI, I got the message:
GamesNativeSDK: Attempting to get file name of an invalid SnapshotMetadata

I am using version 0.9.26
Any hints on fixing the invalid SnapshotMetadata? Thanks very much

**Comment by claywilkinson** [comment]
From the message, did you provide a filename that is a valid filename (i am not sure about spaces and other non-alphanumerics)?  You could  build and examine the CubicPilot sample which includes SavedGames.

**Comment by percytse** [comment]
It is solved after removing spaces from file name.
Thanks!

**Comment by claywilkinson** [comment]
Great! thanks for the update.
