### ISSUE TITLE
Broken Gameobject

### ISSUE THREAD

**Issue by CenekStrichel** [playgameservices/play-games-plugin-for-unity#823]
In Unity 5.2.2 and latest GPG I am getting this: 
![01](https://cloud.githubusercontent.com/assets/8094238/11346719/3d1229e0-921e-11e5-890c-8e3ab0a8fda7.png)

Instead:
![02](https://cloud.githubusercontent.com/assets/8094238/11346766/6edbf820-921e-11e5-804e-4db2a56b523f.png)

Something is wrong in GooglePlayGames\Editor

**Comment by claywilkinson** [comment]
There was an update to the plugin that fixed this, or you can delete Assets/GooglePlayGames/Editor/GPGizmo.cs yourself.
