### ISSUE TITLE
'GIGSignIn.h' file not found

### ISSUE THREAD

**Issue by justinkmai** [playgameservices/play-games-plugin-for-unity#824]
I've searched this issue but the solution in the other thread did not solve my problem. I'm developing in Unity 5.2.1 and Xcode 7.1.1 with the latest GPG 9.27 plugin. I've installed cocoa pods and am working from the generated Xcode file. When I try to build, I receive the following error:

<img width="719" alt="screen shot 2015-11-22 at 10 42 33 pm" src="https://cloud.githubusercontent.com/assets/12648475/11349702/5fde5750-91e2-11e5-8c12-7551ff051ff1.png">

Adding #import < GoogleSignIn/GIDSignIn.h> did not help:

<img width="721" alt="screen shot 2015-11-22 at 10 43 14 pm" src="https://cloud.githubusercontent.com/assets/12648475/11349735/97b17658-91e2-11e5-8823-ea52deea3bb7.png">

My Pods:

<img width="330" alt="screen shot 2015-11-22 at 10 43 33 pm" src="https://cloud.githubusercontent.com/assets/12648475/11349746/a23297ec-91e2-11e5-82b0-b4973cb2b444.png">

I am a complete noob when it comes to developing for Xcode so I may be missing something completely obvious, so please explain any solution with that in mind. Thanks!

**Comment by claywilkinson** [comment]
Which version of cocoapods are you using?  Are there any warnings or errors when if you run `pod update` from a terminal window in your xcode project directory? There are also warnings about the architecture (which are cut off in the screen shots).  Make sure the targets are consistent in the Player settings panel in Unity and in Xcode.

**Comment by justinkmai** [comment]
Ah I didn't notice what version it was since this is all new to me and I installed it only two days ago. When I get home from work tonight I'll try it again and note what it says in the logs and get back to you. Thanks!

**Comment by justinkmai** [comment]
Looks like I'm using cocoapods version 0.39.0. I've redone the whole process and I'm no longer getting this particular error. Thank you!

**Comment by claywilkinson** [comment]
Great! Thanks for the update.

**Comment by Mohammadkhuram** [comment]
in my project there is nothing like pods what are they
