### ISSUE TITLE
IUserProfile.image always null

### ISSUE THREAD

**Issue by unregistered33** [playgameservices/play-games-plugin-for-unity#825]
Hi. I'm trying to customize the leaderboard using LoadScores and LoadUsers to obtain data as it written in the "Getting Started Guide". Everything works great, except that user.image constantly is "null". All other data such as user.name, score.value, score.rank come normally. At the moment, I work in Debug-mode, and there is only one person in the leaderboard.
Plugin v 0.9.27 
Thanks in advance!

**Comment by unregistered33** [comment]
Guys, the problem is not solved! Any help is appricated!
Here is my code:
...
public class UserData
{
    public Texture2D avatar;
    public string name;
    public int rank;
    public long value;
}
...
...
 public void GetLeaderboardData(string leaderboard_id, System.Action<UserData[]> callback)
    {
        ILeaderboard lb = PlayGamesPlatform.Instance.CreateLeaderboard();
        lb.id = leaderboard_id;
        lb.LoadScores((ok) =>
        {
            List<string> userIds = new List<string>();

            foreach (IScore score in lb.scores)
                userIds.Add(score.userID);

            Social.LoadUsers(userIds.ToArray(), (users) =>
            {
                List<UserData> data = new List<UserData>();
                foreach (IScore score in lb.scores)
                {
                    IUserProfile user = findUser(users, score.userID);
                    UserData u_data = new UserData();
                    u_data.avatar = user.image; //<--ALWAYS NULL
                    u_data.name = user.userName; // TRUE DATA
                    u_data.rank = score.rank;// TRUE DATA
                    u_data.value = score.value;//TRUE DATA
                    data.Add(u_data);
                }
PlayGamesHelperObject.RunOnGameThread(() =>
                    {
                        System.Action<UserData[]> action = callback;
                        action(data.ToArray());
                    });
            });
        });
    }

    private IUserProfile findUser(IUserProfile[] users, string UserId)
    {
        foreach (IUserProfile user in users)
            if (user.id == UserId) return user;

        return null;
    }

**Comment by editkid** [comment]
So, it seems that these images load asynchronously from the main user data, when calling `Social.LoadUsers`.

For example the following code:

```void Start () {

    Social.LoadUsers(playerIDArray, this.UsersLoadedCallback);

}

void UsersLoadedCallback (IUserProfile[] users) {

    for (int i = 0; i < users.Length; i++) {
        Debug.Log(users[i].userName + " - " + users[i].image);
    }

}```

Will output the following to the log:

```Bob - null
Peter - null```

Etc. Now, if you wait longer for the images they will load (if nothing goes wrong. This for example works for me:

```IUserProfile[] loadedUsers;

void Start () {

    Social.LoadUsers(playerIDArray, this.UsersLoadedCallback);

}

void UsersLoadedCallback (IUserProfile[] users) {

    this.loadedUsers = users;
    StartCoroutine(WaitForImages());

}

IEnumerator WaitForImages () {

    // Wait for 10 seconds - this is a completely arbitrary length of time...    
    yield return new WaitForSeconds(10);

    for (int i = 0; i < users.Length; i++) {
        Debug.Log(users[i].userName + " - " + users[i].image);
    }

}```

That will output:

```Bob - UnityEngine.Texture2D
Peter - UnityEngine.Texture2D```

I wonder if there's a better way to wait for these images. I.e. using a callback.

**Comment by editkid** [comment]
I guess you just keep referring to the `IUserProfile[]`, actually. In my code `IUserProfile[] loadedUsers;`. As that gets updated automatically. So when you need to display that user, check in the array if they have an image. That will change over time.

**Comment by editkid** [comment]
My final `UsersLoadedCallback`:

```
static IUserProfile[] loadedUsers;

void UsersLoadedCallback (IUserProfile[] users)
{
    // Cache 'em for lookups
    loadedUsers = users;

     #if UNITY_ANDROID
        // Access the images to start loading them
        // asynchronously using Coroutines.
        Texture2D image;
        for (int i = 0; i < loadedUsers.Length; i++) {
             image = loadedUsers[i].image;
        }
    #endif
}
```

**Comment by stigmawall** [comment]
I take some time to understand what you really do @editkid, so I made a coroutine here to make it work (I personally think my code it's very ugly, but...). I take some time to understand how to use GPGS, so I believe this will help someone in future.

` IEnumerator WaitPics(UnityEngine.SocialPlatforms.IUserProfile[] profiles)
    {
        int i = 0;
        Texture2D text = null;
        for (i = 0; i < profiles.Length; i++)
            text = profiles[i].image;

        // wait until images being loaded
        yield return new WaitUntil(() => 
        {
            // in case it don't have any more images to load, the counter will be zero
            int count = 0;
            for (i = 0; i < profiles.Length; i++)
                if( profiles[i].image == null) 
                    count++;
            
            // if the counter equals zero - it all loaded
            return count == 0; 
        });

        // build ranking here
    }`

**Comment by claywilkinson** [comment]
Since the images need to be loaded asynchronously, the coroutine is the way to go.
