### ISSUE TITLE
IllegalStateException when calling `Social.localUser.Authenticate`

### ISSUE THREAD

**Issue by treyzania** [playgameservices/play-games-plugin-for-unity#828]
I am using the most recent version of this plugin, Unity 5.2.3f1, and I've made sure all of the other software on my device are updated, other than the OS itself.  I am running Android 5.1 on a Nexus 6.

This exception appears to be thrown somewhere down the line after calling `Social.localUser.Authenticate`, as I can't find any log messages from the callback in the logcat.  This is after `PlayGamesPlatform.Activate` gets called and completes successfully.  Here's the relevant lines from the logcat:

    D/AndroidRuntime(26932): Shutting down VM
    E/AndroidRuntime(26932): FATAL EXCEPTION: main
    E/AndroidRuntime(26932): Process: com.treyzania.pew, PID: 26932
    E/AndroidRuntime(26932): java.lang.Error: FATAL EXCEPTION [main]
    E/AndroidRuntime(26932): Unity version     : 5.2.3f1
    E/AndroidRuntime(26932): Device model      : motorola Nexus 6
    E/AndroidRuntime(26932): Device fingerprint: google/shamu/shamu:5.1/LMY47E/1748839:user/release-keys
    E/AndroidRuntime(26932): 
    E/AndroidRuntime(26932): Caused by: java.lang.IllegalStateException: A fatal developer error has occurred. Check the logs for further information.
    E/AndroidRuntime(26932): 	at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
    E/AndroidRuntime(26932): 	at com.google.android.gms.common.internal.zzj$zza.zzv(Unknown Source)
    E/AndroidRuntime(26932): 	at com.google.android.gms.common.internal.zzj$zzc.zzqx(Unknown Source)
    E/AndroidRuntime(26932): 	at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
    E/AndroidRuntime(26932): 	at android.os.Handler.dispatchMessage(Handler.java:102)
    E/AndroidRuntime(26932): 	at android.os.Looper.loop(Looper.java:135)
    E/AndroidRuntime(26932): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
    E/AndroidRuntime(26932): 	at java.lang.reflect.Method.invoke(Native Method)
    E/AndroidRuntime(26932): 	at java.lang.reflect.Method.invoke(Method.java:372)
    E/AndroidRuntime(26932): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    E/AndroidRuntime(26932): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    W/ActivityManager( 2052):   Force finishing activity 1 com.treyzania.pew/com.unity3d.player.UnityPlayerActivity

I still have the logs themselves so I can provide more if you need them.  The project is available at http://github.com/treyzania/pew, so if you need to inspect my code it's available as well.

**Comment by claywilkinson** [comment]
The problem that causes the crash is logged before the "Shutting down VM" message.  If you can provide the log between starting your game and the crash, that will help a lot.

**Comment by treyzania** [comment]
Here's everything from process 26932 up until the VM shuts down:

    I/ActivityManager( 2052): Start proc 26932:com.treyzania.pew/u0a210 for activity com.treyzania.pew/com.unity3d.player.UnityPlayerActivity
    W/linker  (26932): libunity.so: unused DT entry: type 0x6ffffffe arg 0x9b0c
    W/linker  (26932): libunity.so: unused DT entry: type 0x6fffffff arg 0x1
    I/Adreno  (26932): EGLInit: QTI Build: 01/29/15, 1bccc5d, I0ba6dce82d
    I/Adreno  (26932): Unknown config attribute query: 0x30e1
    I/Adreno  (26932): Unknown config attribute query: 0x30e2
    D/Unity   (26932):  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_multisampled_render_to_texture GL_OES_shader_multisample_interpolation G...
    D/Unity   (26932): raw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_sRGB_write_control
    W/libc    (26932): pthread_create sched_setscheduler call failed: Operation not permitted
    W/libc    (26932): pthread_create sched_setscheduler call failed: Operation not permitted
    I/Unity   (26932):  [Play Games Plugin DLL] 11/26/15 22:38:56 -05:00 DEBUG: Activating PlayGamesPlatform.
    I/Unity   (26932):  
    I/Unity   (26932): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
    I/Unity   (26932): 
    I/Unity   (26932):  [Play Games Plugin DLL] 11/26/15 22:38:56 -05:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
    I/Unity   (26932):  
    I/Unity   (26932): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
    I/Unity   (26932): 
    I/Unity   (26932):  [Play Games Plugin DLL] 11/26/15 22:38:56 -05:00 DEBUG: Creating platform-specific Play Games client.
    I/Unity   (26932):  
    I/Unity   (26932): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
    I/Unity   (26932): 
    I/Unity   (26932):  [Play Games Plugin DLL] 11/26/15 22:38:56 -05:00 DEBUG: Creating Android IPlayGamesClient Client
    I/Unity   (26932):  
    I/Unity   (26932): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
    I/Unity   (26932): 
    D/GamesUnitySDK(26932): Performing Android initialization of the GPG SDK
    I/WebViewFactory(26932): Loading com.google.android.webview version 46.0.2490.76 (code 249007600)
    I/Unity   (26932): Building GPG services, implicitly attempts silent auth
    I/Unity   (26932):  
    I/Unity   (26932): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
    I/Unity   (26932): 
    I/cr.library_loader(26932): Time to load native libraries: 3 ms (timestamps 2602-2605)
    I/cr.library_loader(26932): Expected native library version number "46.0.2490.76", actual native library version number "46.0.2490.76"
    W/PopupManager(26932): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
    V/WebViewChromiumFactoryProvider(26932): Binding Chromium to main looper Looper (main, tid 1) {3094ba48}
    I/cr.library_loader(26932): Expected native library version number "46.0.2490.76", actual native library version number "46.0.2490.76"
    I/chromium(26932): [INFO:library_loader_hooks.cc(118)] Chromium logging enabled: level = 0, default verbosity = 0
    I/GamesNativeSDK(26932): Auth operation started: SIGN IN
    I/GamesNativeSDK(26932): Connecting to Google Play...
    I/cr.BrowserStartup(26932): Initializing chromium process, singleProcess=true
    I/Unity   (26932):  [Play Games Plugin DLL] 11/26/15 22:38:56 -05:00 DEBUG: Entering state: BeforeRoomCreateStartedState
    I/Unity   (26932):  
    I/Unity   (26932): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
    I/Unity   (26932): 
    I/Unity   (26932):  [Play Games Plugin DLL] 11/26/15 22:38:56 -05:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
    I/Unity   (26932):  
    I/Unity   (26932): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
    I/Unity   (26932): 
    I/Unity   (26932):  [Play Games Plugin DLL] 11/26/15 22:38:56 -05:00 DEBUG: Entering state: ShutdownState
    I/Unity   (26932):  
    I/Unity   (26932): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
    I/Unity   (26932): 
    I/Unity   (26932):  [Play Games Plugin DLL] 11/26/15 22:38:56 -05:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
    I/Unity   (26932):  
    I/Unity   (26932): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
    I/Unity   (26932): 
    E/SysUtils(26932): ApplicationContext is null in ApplicationStatus
    E/chromium(26932): [ERROR:browser_gpu_channel_host_factory.cc(258)] Failed to init browser shader disk cache.
    W/cr.media(26932): Requires BLUETOOTH permission
    E/libEGL  (26932): validate_display:255 error 3008 (EGL_BAD_DISPLAY)
    I/art     (26932): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
    I/art     (26932): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
    I/Unity   (26932): Google inited.
    I/Unity   (26932):  
    I/Unity   (26932): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
    I/Unity   (26932): 
    I/art     (26932): Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingWebActionModeCallback>
    I/art     (26932): Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingWebActionModeCallback>
    W/art     (26932): Attempt to remove local handle scope entry from IRT, ignoring
    W/AwContents(26932): onDetachedFromWindow called when already detached. Ignoring
    W/art     (26932): Attempt to remove local handle scope entry from IRT, ignoring
    W/art     (26932): Attempt to remove local handle scope entry from IRT, ignoring
    D/AndroidRuntime(26932): Shutting down VM

**Comment by claywilkinson** [comment]
It looks the crash is unrelated to Google Play Game Services, but to a web view you are including?
`E/chromium(26932): [ERROR:browser_gpu_channel_host_factory.cc(258)] Failed to init browser shader disk cache.`

Or the Bluetooth permission being missing?

`W/cr.media(26932): Requires BLUETOOTH permission`

**Comment by treyzania** [comment]
I'm using all standard features, no special web views.  Nor am I using bluetooth at all.

I *was* able to resolve the issue by running Setup again, though it doesn't seem to me like that was the root cause.

**Comment by claywilkinson** [comment]
Ahh, yep, those are for other processes, apologies for the confusion.  The setup does copy client jars and update the configuration.  I am glad you got it resolved.
