### ISSUE TITLE
Could not locate the OAuth Client ID [iOS]

### ISSUE THREAD

**Issue by justinkmai** [playgameservices/play-games-plugin-for-unity#829]
I am using GooglePlayGamesPlugin-0.9.27, Unity 5.2.1, Xcode 7.1.1, and OSX 10.11.1. I have everything working perfectly fine on Android, but when I try setting up the gpg plugin for iOS and testing it on my device in Xcode, I get the following error:

<img width="561" alt="screen shot 2015-11-28 at 11 40 07 pm" src="https://cloud.githubusercontent.com/assets/12648475/11455955/ece15868-962a-11e5-9b62-1431042090c9.png">

I've already linked my game to iOS in the console:

<img width="313" alt="screen shot 2015-11-28 at 11 42 32 pm" src="https://cloud.githubusercontent.com/assets/12648475/11455968/3908665a-962b-11e5-908f-0588658d0910.png">

And copied the Objective-C resource code into Unity:

<img width="197" alt="screen shot 2015-11-28 at 11 43 47 pm" src="https://cloud.githubusercontent.com/assets/12648475/11455970/520361aa-962b-11e5-8abb-a3dfa1c068c9.png">

<img width="170" alt="screen shot 2015-11-28 at 11 44 55 pm" src="https://cloud.githubusercontent.com/assets/12648475/11455975/6b345166-962b-11e5-8b9e-95d3009239f9.png">

One thing I'm unsure about though, am I supposed to use the same constants class name for both Android and iOS? I've tried setting them up to the same file as well as separate files but didn't notice any difference. One thing I did notice, however, is that the Client ID didn't get copied into the GPGSIds file that was automatically created.

<img width="349" alt="screen shot 2015-11-28 at 11 47 08 pm" src="https://cloud.githubusercontent.com/assets/12648475/11455986/0476c14c-962c-11e5-8135-454d3b2311ef.png">

Any idea what the issue could be? I feel like this is my final hurdle before getting my game up on the Apple Store, so any help would be greatly appreciated! There is also one other thing I should mention, is when building out my game from unity for iOS, I received the following error:

<img width="260" alt="screen shot 2015-11-28 at 11 24 48 pm" src="https://cloud.githubusercontent.com/assets/12648475/11455994/4f8ae398-962c-11e5-8953-5dec7e9f4487.png">

I'm not sure if that's of any significance since I manually created a podfile and copied the information over before installing the pods and didn't have any issues with the game building and running.

<img width="621" alt="screen shot 2015-11-29 at 12 06 31 am" src="https://cloud.githubusercontent.com/assets/12648475/11456017/24468b28-962d-11e5-91f5-5b18cd520916.png">

<img width="655" alt="screen shot 2015-11-29 at 12 11 24 am" src="https://cloud.githubusercontent.com/assets/12648475/11456032/e396f21a-962d-11e5-82ea-cfcb32c37913.png">

**Comment by claywilkinson** [comment]
It's OK to use the same constants class name for both platforms.  The client ID actually gets set in Assets/GooglePlayGames/GameInfo.cs.  Running Window > Google Play Games > Setup > iOS setup and pasting the objective C resource constants in that dialog.  Maybe check that it is set correctly in that file?

That's strange about the pod executable, where is it installed on your computer? (can you run `which pod` ?)

It looks like it built and ran OK so the podfile is fine.

**Comment by justinkmai** [comment]
The pod is installed in this location:

<img width="333" alt="screen shot 2015-11-30 at 7 19 34 pm" src="https://cloud.githubusercontent.com/assets/12648475/11491552/c8a69b3e-9797-11e5-8450-aafc463329a9.png">

I was getting an operation no permitted error so I searched it and came upon this page:

http://stackoverflow.com/questions/30812777/cannot-install-cocoa-pods-after-uninstalling-results-in-error

And entered in the following command:

<img width="729" alt="screen shot 2015-11-30 at 7 21 09 pm" src="https://cloud.githubusercontent.com/assets/12648475/11491572/edee43ba-9797-11e5-9bfc-c65b737efb32.png">

Looks like the GameInfo.cs correctly contains the client ID as well:

<img width="557" alt="screen shot 2015-11-30 at 7 26 44 pm" src="https://cloud.githubusercontent.com/assets/12648475/11491855/9ffc494c-979a-11e5-8d81-4eeca065a1b2.png">

Does it matter if the constants id contains a word before hand like in the example 'AwesomeGame.GPGSIds' or can it just be 'GPGSIds'?

**Comment by claywilkinson** [comment]
The namespace of the constants does not have an affect on the authentication.  Maybe a clean build of the xcode project (now that you have pod set up and know the c# code looks correct.

**Comment by justinkmai** [comment]
By clean build do you mean re-outputting the xcode project files from Unity? Or using the clean tool within xcode?

**Comment by claywilkinson** [comment]
Re-building into a new directory from Unity.  XCode does a lot of caching, this just makes sure the project that Unity is generating from the C# code is actually what is being built in XCode.

**Comment by justinkmai** [comment]
Got it, I will try it tonight and let you know how it goes. Thanks!

**Comment by justinkmai** [comment]
Aha! I found the problem.. I somehow had two GameInfo files! One of them didn't have the client ID in it, so that would explain why it wasn't found. I really appreciate your help and for all the work you put into this great plugin! Can I include you in the credits of my game?

**Comment by claywilkinson** [comment]
Glad you found the issue!  I'd be honored to be in the credits :+1:   Please share the name of your game when it is published.

**Comment by justinkmai** [comment]
Will do! It's called Basketball Time, currently available for Android and will be released for iOS within the next couple weeks after I send it to Apple. Thanks again Clay!
