### ISSUE TITLE
Multiplayer Fails on iOS with il2cpp Error in xCODE. How to fix it?

### ISSUE THREAD

**Issue by bekiryanik** [playgameservices/play-games-plugin-for-unity#833]
Hello,

I working on a multiplayer game project and first i wanted to explore how Quiz Racer game sample's multiplayer system works. I set everything and i run the game in my iOS 9 device. I've faced with this issue below when i click on multiplayer button:

[![image](http://i.hizliresim.com/ZQZaXV.png)](http://hizliresim.com/ZQZaXV)

I am trying to solve this problem since two days but i couldn't find any solution yet. How can i solve it? Any idea?

**Comment by claywilkinson** [comment]
Do you have the latest sample code?  There was a problem building the samples a few weeks back, so make sure you have the latest package.

You can fix the panel problem by selecting the EventSystem in the Hierarchy in the MainScene.  Then set the PanelMgr properties to the corresponding game objects (found under the Canvas object).  It should look like: 
![screen shot 2015-12-02 at 8 36 34 am](https://cloud.githubusercontent.com/assets/8752378/11537047/2621b9ae-98d0-11e5-873c-50e518fae398.png)

**Comment by bekiryanik** [comment]
@claywilkinson  thank you so much for your quick answer.

Yes i have the latest sample code. I have downloaded the latest play games plugin pack and i am using Quiz Racer sample unity pack which is inside that latest play games plugin pack.
I have my PanelMgr just like yours:
<a href="http://hizliresim.com/JkaoZj"><img src="http://i.hizliresim.com/JkaoZj.png"></a>

I didn't make any change on PanelMgr. When i look it, it was just like yours.

**Comment by claywilkinson** [comment]
Hmm. Can you share the log from signing in to trying to show the invitation panel?

**Comment by bekiryanik** [comment]
I am sharing them as photo to ensure you to read more comfortable. If you want me to share them as text, please let me know.

I took screen shot from beginning to end.

1:
<a href="http://hizliresim.com/ZQEYlk"><img src="http://i.hizliresim.com/ZQEYlk.png"></a>

2:
<a href="http://hizliresim.com/B6A8jD"><img src="http://i.hizliresim.com/B6A8jD.png"></a>

3:
<a href="http://hizliresim.com/2N9jpN"><img src="http://i.hizliresim.com/2N9jpN.png"></a>

4:
<a href="http://hizliresim.com/E6R3jq"><img src="http://i.hizliresim.com/E6R3jq.png"></a>

5:
<a href="http://hizliresim.com/D6d3jl"><img src="http://i.hizliresim.com/D6d3jl.png"></a>

6:
<a href="http://hizliresim.com/82d8jk"><img src="http://i.hizliresim.com/82d8jk.png"></a>

7:
<a href="http://hizliresim.com/YWN4oj"><img src="http://i.hizliresim.com/YWN4oj.png"></a>

8:
<a href="http://hizliresim.com/aMGX7B"><img src="http://i.hizliresim.com/aMGX7B.png"></a>

9:
<a href="http://hizliresim.com/Ng1kjY"><img src="http://i.hizliresim.com/Ng1kjY.png"></a>

10:
<a href="http://hizliresim.com/kLWE5r"><img src="http://i.hizliresim.com/kLWE5r.png"></a>

11:
<a href="http://hizliresim.com/R9PQ5a"><img src="http://i.hizliresim.com/R9PQ5a.png"></a>

12:
<a href="http://hizliresim.com/3jqA4r"><img src="http://i.hizliresim.com/3jqA4r.png"></a>

13:
<a href="http://hizliresim.com/W9QbON"><img src="http://i.hizliresim.com/W9QbON.png"></a>


Thank you so much.
Best regards.

**Comment by bekiryanik** [comment]
Anything new?

**Comment by bekiryanik** [comment]
@claywilkinson Hello,

Can you please let me know about the problem if you find it out?

Thank you.
Best regards.

**Comment by bekiryanik** [comment]
Did anyone find the problem?

**Comment by bekiryanik** [comment]
Still nothing?

**Comment by claywilkinson** [comment]
I tried this with the updated 0.9.30 packages and everything worked OK.  Please open a new issue if there are still issues.
