### ISSUE TITLE
Authentication not authorized with silent parameter

### ISSUE THREAD

**Issue by nilareguy-hibernum** [playgameservices/play-games-plugin-for-unity#835]
Hi,
We are trying to authenticate in Google Play Services, but this authentication needs to be silent to the user. When going by this method, the first authentication fails with an ERROR_NOT_AUTHORIZED.

When we do not use the silent authentication, the user is prompted with a consent screen and if the user accepts, the authentication succeed.

Previously, we used the API Key in order to authenticate silently, which was working until we updated the Android SDK to the most recent version. With that update, the authentication was failing on Android devices 5.0+ but was still working on Android 4. So in order to fix those issues, we updated the Google Play Services to this plugin, which works fine if the user consent to the prompt, but still isn't what our initial flow was.

This is our console output when using silent authentication:
<code>
12-02 16:32:48.211: I/Unity(706):  [Play Games Plugin DLL] 12/02/15 16:32:48 -05:00 DEBUG: Activating PlayGamesPlatform.
12-02 16:32:48.211: I/Unity(706):  
12-02 16:32:48.211: I/Unity(706): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
12-02 16:32:48.213: I/Unity(706):  [Play Games Plugin DLL] 12/02/15 16:32:48 -05:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
12-02 16:32:48.213: I/Unity(706):  
12-02 16:32:48.213: I/Unity(706): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
12-02 16:32:48.214: I/Unity(706):  [Play Games Plugin DLL] 12/02/15 16:32:48 -05:00 DEBUG: Creating platform-specific Play Games client.
12-02 16:32:48.214: I/Unity(706):  
12-02 16:32:48.214: I/Unity(706): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
12-02 16:32:48.215: I/Unity(706):  [Play Games Plugin DLL] 12/02/15 16:32:48 -05:00 DEBUG: Creating Android IPlayGamesClient Client
12-02 16:32:48.215: I/Unity(706):  
12-02 16:32:48.215: I/Unity(706): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
12-02 16:32:48.234: D/GamesUnitySDK(706): Performing Android initialization of the GPG SDK
12-02 16:32:48.291: I/Unity(706): Building GPG services, implicitly attempts silent auth
12-02 16:32:48.291: I/Unity(706):  
12-02 16:32:48.291: I/Unity(706): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
12-02 16:32:48.333: I/Unity(706):  [Play Games Plugin DLL] 12/02/15 16:32:48 -05:00 DEBUG: Entering state: BeforeRoomCreateStartedState
12-02 16:32:48.333: I/Unity(706):  
12-02 16:32:48.333: I/Unity(706): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
12-02 16:32:48.333: I/Unity(706):  [Play Games Plugin DLL] 12/02/15 16:32:48 -05:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
12-02 16:32:48.333: I/Unity(706):  
12-02 16:32:48.333: I/Unity(706): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
12-02 16:32:48.334: I/Unity(706):  [Play Games Plugin DLL] 12/02/15 16:32:48 -05:00 DEBUG: Entering state: ShutdownState
12-02 16:32:48.334: I/Unity(706):  
12-02 16:32:48.334: I/Unity(706): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
12-02 16:32:48.334: I/Unity(706):  [Play Games Plugin DLL] 12/02/15 16:32:48 -05:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
12-02 16:32:48.334: I/Unity(706):  
12-02 16:32:48.334: I/Unity(706): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
12-02 16:32:48.421: I/Unity(706):  [Play Games Plugin DLL] 12/02/15 16:32:48 -05:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
12-02 16:32:48.421: I/Unity(706):  
12-02 16:32:48.421: I/Unity(706): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
12-02 16:32:48.421: I/Unity(706): Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
12-02 16:32:48.421: I/Unity(706):  
12-02 16:32:48.421: I/Unity(706): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
12-02 16:32:48.497: I/Unity(706):  [Play Games Plugin DLL] 12/02/15 16:32:48 -05:00 DEBUG: Invoking user callback on game thread
12-02 16:32:48.497: I/Unity(706):  
12-02 16:32:48.497: I/Unity(706): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
</code>

Is there a way to use the silent authentication without asking for the user's consent? We are only implementing Google Play Services to use the Google Mobile Ads to get the advertiser id for one of our other plugins.

**Comment by claywilkinson** [comment]
If you are not using game services such as leaderboards, achievements, and just need a client connection, then this plugin is not the right choice.  Play Game Services requires server side configuration and coordination of the authentication flow (bundle id and SHA1 fingerprint).

Why not use the mobile ads Unity plugin? (https://github.com/googleads/googleads-mobile-unity)

**Comment by nilareguy-hibernum** [comment]
The third party plugin we are using (AppsFlyer) requires us to authenticate in Google Play Services in order to retrieve the Google Advertiser ID. Unfortunately, it doesn't work with Google Mobile Ads unless there's an authentication process in that plugin that I'm unaware of.

Their Unity plugin contains an older version of Google Play Services, which was used to authenticate with the API Key, but this method just stopped working on Android 5.0+ when we updated our Android SDK.
