### ISSUE TITLE
why 8.3.0 -> 8.1.0 downgrade?

### ISSUE THREAD

**Issue by clonaid** [playgameservices/play-games-plugin-for-unity#836]
Android Jar Dependencies

Remove or replace play-service-games version 8.3.0 with version 8.1.0?

ok button or keep button

================================

ok button press -> don't delete aar file

**Comment by clonaid** [comment]
The Google Play Games Plugin for Unity version 0.9.27 is now ready to use.
If this is a new installation or of you have just upgraded from a previous version, please click the 'Google Play Games' menu and select 'Android Setup' and/or 'iOS Setup' to set up your project to build for the corresponding platforms.

Upgrading from format version 00000 to 00911
UnityEngine.Debug:Log(Object)
GooglePlayGames.GPGSUpgrader:Upgrade911(String) (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:194)
GooglePlayGames.GPGSUpgrader:.cctor() (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:40)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])


Done upgrading from format version 00000 to 00911
UnityEngine.Debug:Log(Object)
GooglePlayGames.GPGSUpgrader:Upgrade911(String) (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:231)
GooglePlayGames.GPGSUpgrader:.cctor() (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:40)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])



Upgrading from format version 00911 to 00915
UnityEngine.Debug:Log(Object)
GooglePlayGames.GPGSUpgrader:Upgrade915(String) (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:132)
GooglePlayGames.GPGSUpgrader:.cctor() (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:43)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])


Upgrading from format version 00915 to 00927
UnityEngine.Debug:Log(Object)
GooglePlayGames.GPGSUpgrader:.cctor() (at Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:46)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

**Comment by claywilkinson** [comment]
Thanks for the issue - we'll take a look

**Comment by claywilkinson** [comment]
This looks like it can happen if the Android SDK is older than the where the project was made?  Can you share your $ANDROID_HOME/extras/google/m2repository/com/google/android/gms/play-services-games/maven-metadata.xml?

The plugin should be taking the latest version in that file.
