### ISSUE TITLE
Can't Sign In Google Play Games Unity 5.1.2f1 

### ISSUE THREAD

**Issue by ariefannur** [playgameservices/play-games-plugin-for-unity#838]
I was trying to connect with google play game. and set up in google play console but. can't login,
do you have any suggestion. this is the script.

PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
			// enables saving game progress.
			.EnableSavedGames()
			.Build();

PlayGamesPlatform.InitializeInstance(config);
		// recommended for debugging:
		PlayGamesPlatform.DebugLogEnabled = true;
		
		PlayGamesPlatform.Activate();

Social.localUser.Authenticate((bool success) => {
			// handle success or failure
			if(success){
				Social.localUser.Authenticate (ProcessAuthentication);
			}else{
				txt.text = "Gagal login ";
			}
		});

And the Log is : 
 [Play Games Plugin DLL] 12/03/15 21:39:38 +07:00 DEBUG: Activating PlayGamesPlatform.
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets/GooglePlayGames/OurUtils/Logger.cs:58)
GooglePlayGames.PlayGamesPlatform:Activate() (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:232)
Menu:GoogleInit() (at Assets/Script/Menu.cs:36)
Menu:Start() (at Assets/Script/Menu.cs:16)
 [Play Games Plugin DLL] 12/03/15 21:39:38 +07:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets/GooglePlayGames/OurUtils/Logger.cs:58)
GooglePlayGames.PlayGamesPlatform:Activate() (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:234)
Menu:GoogleInit() (at Assets/Script/Menu.cs:36)
Menu:Start() (at Assets/Script/Menu.cs:16)

 [Play Games Plugin DLL] 12/03/15 21:39:38 +07:00 DEBUG: Creating platform-specific Play Games client.
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets/GooglePlayGames/OurUtils/Logger.cs:58)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:300)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:275)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesLocalUser.cs:48)
Menu:googleSignIn() (at Assets/Script/Menu.cs:40)
Menu:Start() (at Assets/Script/Menu.cs:17)

 [Play Games Plugin DLL] 12/03/15 21:39:38 +07:00 DEBUG: Creating IPlayGamesClient in editor, using DummyClient.
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets/GooglePlayGames/OurUtils/Logger.cs:58)
GooglePlayGames.PlayGamesClientFactory:GetPlatformPlayGamesClient(PlayGamesClientConfiguration) (at Assets/GooglePlayGames/Platforms/PlayGamesClientFactory.cs:30)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:301)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:275)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesLocalUser.cs:48)
Menu:googleSignIn() (at Assets/Script/Menu.cs:40)
Menu:Start() (at Assets/Script/Menu.cs:17)

 [Play Games Plugin DLL] 12/03/15 21:39:38 +07:00 DEBUG: Received method call on DummyClient - using stub implementation.
UnityEngine.Debug:Log(Object)
GooglePlayGames.OurUtils.Logger:d(String) (at Assets/GooglePlayGames/OurUtils/Logger.cs:58)
GooglePlayGames.BasicApi.DummyClient:LogUsage() (at Assets/GooglePlayGames/BasicApi/DummyClient.cs:290)
GooglePlayGames.BasicApi.DummyClient:Authenticate(Action`1, Boolean) (at Assets/GooglePlayGames/BasicApi/DummyClient.cs:30)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1, Boolean) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:305)
GooglePlayGames.PlayGamesPlatform:Authenticate(Action`1) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:275)
GooglePlayGames.PlayGamesLocalUser:Authenticate(Action`1) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesLocalUser.cs:48)
Menu:googleSignIn() (at Assets/Script/Menu.cs:40)
Menu:Start() (at Assets/Script/Menu.cs:17)

**Comment by claywilkinson** [comment]
Google Play Game Services do not work in the editor.  You need to test on an actual device.

**Comment by ariefannur** [comment]
I tried to test in real device and filled in the test account in the google play console and. still can't login

**Comment by claywilkinson** [comment]
Can you share the log from the device?

**Comment by ariefannur** [comment]
I/dalvikvm(18841): Could not find method android.content.Context.checkSelfPermission, referenced from method com.google.android.gms.common.permission.PermissionUtils.getMissingPermissionGroups
W/dalvikvm(18841): VFY: unable to resolve virtual method 349: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
D/dalvikvm(18841): VFY: replacing opcode 0x6e at 0x0036
I/dalvikvm(18841): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.GooglePlayServicesUtil.isUninstalledAppPossiblyUpdating
W/dalvikvm(18841): VFY: unable to resolve virtual method 499: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
D/dalvikvm(18841): VFY: replacing opcode 0x6e at 0x000d
E/dalvikvm(18841): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.google.android.gms.games.ui.util.UiUtils.constructButtonBackground
W/dalvikvm(18841): VFY: unable to resolve new-instance 177 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/google/android/gms/games/ui/util/UiUtils;
D/dalvikvm(18841): VFY: replacing opcode 0x22 at 0x0013
D/dalvikvm(18841): DexOpt: unable to opt direct call 0x0397 at 0x1a in Lcom/google/android/gms/games/ui/util/UiUtils;.constructButtonBackground
W/dalvikvm(18841): VFY: unable to find class referenced in signature (Landroid/net/Network;)
W/dalvikvm(18841): VFY: unable to find class referenced in signature (Landroid/net/Network;)
W/dalvikvm(18841): VFY: unable to find class referenced in signature (Landroid/net/Network;)
I/dalvikvm(18841): Could not find method android.net.Network.openConnection, referenced from method com.google.android.gms.http.g.a
W/dalvikvm(18841): VFY: unable to resolve virtual method 1040: Landroid/net/Network;.openConnection (Ljava/net/URL;)Ljava/net/URLConnection;
D/dalvikvm(18841): VFY: replacing opcode 0x6e at 0x00bb
D/dalvikvm(18841): GC_EXPLICIT freed 4333K, 28% free 16174K/22276K, paused 11ms+31ms, total 198ms
D/dalvikvm( 4868): GC_EXPLICIT freed 262K, 30% free 15639K/22276K, paused 7ms+8ms, total 150ms
D/dalvikvm( 1059): GC_EXPLICIT freed 1661K, 23% free 29909K/38624K, paused 5ms+15ms, total 156ms
I/dalvikvm(18841): Could not find method android.os.Debug.startMethodTracingSampling, referenced from method com.google.android.gms.drive.api.a.q.a
W/dalvikvm(18841): VFY: unable to resolve static method 1250: Landroid/os/Debug;.startMethodTracingSampling (Ljava/lang/String;II)V
D/dalvikvm(18841): VFY: replacing opcode 0x71 at 0x0064
D/dalvikvm(18841): GC_CONCURRENT freed 2030K, 28% free 16159K/22276K, paused 4ms+13ms, total 62ms
I/dalvikvm(18841): Could not find method android.os.PowerManager.isInteractive, referenced from method com.google.android.gms.common.server.x.a
W/dalvikvm(18841): VFY: unable to resolve virtual method 1099: Landroid/os/PowerManager;.isInteractive ()Z
D/dalvikvm(18841): VFY: replacing opcode 0x6e at 0x0033
D/dalvikvm( 1294): GC_CONCURRENT freed 1920K, 28% free 16144K/22276K, paused 23ms+4ms, total 77ms
I/Unity   (19820):  [Play Games Plugin DLL] 12/04/15 8:38:18 +07:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
I/Unity   (19820):
I/Unity   (19820): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (19820):
I/Unity   (19820): Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
I/Unity   (19820):
I/Unity   (19820): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (19820):
I/Unity   (19820): there are pending auth callbacks - starting AuthUI

**Comment by ariefannur** [comment]
I got the sollution. Just Activate Saved Game in Google Play Console
