### ISSUE TITLE
 PlayGamesPlatform.Instance.Authenticate resturns false..

### ISSUE THREAD

**Issue by ManJin** [playgameservices/play-games-plugin-for-unity#839]
I use Unity 5.2.3f1 Personal,  and playgamespluginforunity 0.9.27 .
when I try to auth first time, plugin shows user permit window for select decline / accept. 
even i choose accept. Authenticate return false. then second time, no show user permit window ( this is 
normal contition i think.. bucause i accept app permition at first time..)  and Authenticate function return  false again..
so i re checked appid, package name, sha1, and tester list, but they are fine.
and googlePlayGameSetting looks fine.
here is googlePlayGameSetting.txt
------------
lastUpgrade=00927
proj.AppId=447507301817
and.BundleId=com.jscgames.sexyjump
proj.classDir=Assets
proj.ConstantsClassName=pj.gptest
and.ResourceData=%3c%3fxml+version%3d%221.0%22+encoding%3d%22utf-8%22%3f%3e%0d%0a%3c%21--%0d%0aGoogle+Play+game+services+IDs.%0d%0aSave+this+file+as+res%2fvalues%2fgames-ids.xml+in+your+project.%0d%0a--%3e%0d%0a%3cresources%3e%0d%0a++%3cstring+name%3d%22app_id%22%3e447507301817%3c%2fstring%3e%0d%0a++%3cstring+name%3d%22package_name%22%3ecom.jscgames.sexyjump%3c%2fstring%3e%0d%0a++%3cstring+name%3d%22achievement_test1%22%3eCgkIuYuOjIMNEAIQAg%3c%2fstring%3e%0d%0a++%3cstring+name%3d%22achievement_test2%22%3eCgkIuYuOjIMNEAIQAw%3c%2fstring%3e%0d%0a++%3cstring+name%3d%22achievement_test3%22%3eCgkIuYuOjIMNEAIQBA%3c%2fstring%3e%0d%0a++%3cstring+name%3d%22achievement_test4%22%3eCgkIuYuOjIMNEAIQBQ%3c%2fstring%3e%0d%0a++%3cstring+name%3d%22achievement_test5%22%3eCgkIuYuOjIMNEAIQBg%3c%2fstring%3e%0d%0a%3c%2fresources%3e%0d%0a
and.ClientId=447507301817-h26bn04l7slrgne9mtbgsuk1sa799pkc.apps.googleusercontent.com
android.SetupDone=true
-------------

here is some my code sample. for initialize and login.
------------
void Start() {
//...//
CoreEvents.Initialize();
        SoomlaProfile.Initialize();

        //CoreEvents.Initialize();
        StoreEvents.Initialize();
 Debug.Log("PlayGamesPlatform Activate");
        PlayGamesPlatform.Activate();
        PlayGamesPlatform.DebugLogEnabled = true;
}

 public void Click_EtcToAchive()
    {
        Debug.Log("Click Etc - Achive");
#if UNITY_ANDROID
        if (PlayGamesPlatform.Instance.localUser.authenticated == false)
        {
//PlayGamesPlatform.Instance.Authenticate((bool success) =>
                Social.localUser.Authenticate((bool success) =>
            {
                Debug.Log("Try to Auth GooglePlay "  + success);
            });
        }
        else
        {
            //Social.localUser.id

            PlayGamesPlatform.Instance.ShowAchievementsUI();
        }
#elif UNITY_IPHONE
       //..//
#endif
    }
------------
i try to 3 way to auth with PlayGamesPlatform.Instance.Authenticate, Social.localUser.Authenticate, Social.Active.Authenticate but all of these returns false..

whats wrong with this..?
attached android device log here.
------------ 
 I/ClientService(22068):  **** NTT Docomo OSV Client Version: 05.00.00004 ****
 W/GamesServiceBroker(3360): Client connected with SDK 8298000, Services 8301248, and Games 34120048
 D/ChimeraCfgMgr(3360): Loading module com.google.android.gms.games from APK com.google.android.play.games
 D/ChimeraModuleLdr(3360): Module APK com.google.android.play.games already loaded
 V/GamesNativeSDK(21109): Play Games callback indicates connection failure.
 I/GamesNativeSDK(21109): UI interaction required to connect to Google Play.
 W/GamesServiceBroker(3360): Client connected with SDK 8298000, Services 8301248, and Games 34120048
 D/ChimeraCfgMgr(3360): Loading module com.google.android.gms.games from APK com.google.android.play.games
 D/ChimeraModuleLdr(3360): Module APK com.google.android.play.games already loaded
 V/GamesNativeSDK(21109): Play Games callback indicates connection failure.
 I/GamesNativeSDK(21109): UI interaction required to connect to Google Play.
 I/Unity(21109):  [Play Games Plugin DLL] 12/04/15 17:11:36 +09:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
 I/Unity(21109):  
 I/Unity(21109): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
 I/Unity(21109):  Auth Failed State : Unauthenticated
 I/Unity(21109):  
 I/Unity(21109): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
 I/Unity(21109): AuthState == Unauthenticated calling auth callbacks with failure
 I/Unity(21109):  
 I/Unity(21109): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
 I/Unity(21109):  [Play Games Plugin DLL] 12/04/15 17:11:36 +09:00 DEBUG: Invoking user callback on game thread
 I/Unity(21109):  
 I/Unity(21109): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
 I/Unity(21109): Try to Auth GooglePlay False
 I/Unity(21109):  
 I/Unity(21109): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

----------------------

**Comment by claywilkinson** [comment]
Did you get this resolved? OK to close?, or can you post the entire log, not just the Unity category?

**Comment by ManJin** [comment]
case closed. kind of type cast problem..
