### ISSUE TITLE
AcknowledgeFinished doesn't work for me, or is there a dismiss function?

### ISSUE THREAD

**Issue by Armend** [playgameservices/play-games-plugin-for-unity#840]
Hello everyone,

i have a question regarding the function "AcknowledgeFinished". In the documentation it's written that if i call "AcknowledgeFinished" the match will dissapear from the users Inbox, but that's not happening. 

What i want is after showing the result of a match and after calculating the points for that player, that they don't have access to that match again, because after showing it again, the points will be calculatet again and again. For the "normal" Game-Cicle i have found a solution, by adding a attribute to the game data called "playerXsawtheresult", which is my "flag" to see, if i have to calculate the points for this user or not.

But for example, if the game expires, the game will be closed and there is no chance to change the gamedata and so, i have no chance to change the "playerXsawtheresult"-Flag. Is there any way to do so? I thought, since in the documentary there is a "dismiss" Function, that i could dismiss the match, so that it would dissapear from users Inbox, but i can't find the function. Maybe it's not implemented yet. :/

Thanks everyone, i hope you can get what my problem is. =)

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
