### ISSUE TITLE
Can i send object data in Turnbased multiplayer game?

### ISSUE THREAD

**Issue by ariefannur** [playgameservices/play-games-plugin-for-unity#841]
I have build a game which use turn based multiplayer with google play games and cause i use unity, i try to learn google play games unity plugin.

i have a question, how can i send and get data in the TurnBasedMatch ?

it's true just can send byte[] data. How about we want to send object data, than we have created before ?  thanks.

**Comment by claywilkinson** [comment]
There are several methods to serialize an object to bytes.  The most simplistic of these is to use the BinaryFormatter.  See http://answers.unity3d.com/questions/895934/serialize-and-deserialize-class-to-byte-on-ios.html
