### ISSUE TITLE
Ios built in Play Games UI translates very little from english to device language.

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#843]
I have a ios device with language set to swedish. ...but the only thing in the UI that gets translated from english to swedish is the texts I have circeled in. When I run my game on android the UI translates everything correctly in all views.
![img_0966](https://cloud.githubusercontent.com/assets/10234700/11614814/16d41470-9c4e-11e5-8b14-ab20b5bbf1d1.PNG)

The Invite contact UI is all in english. And the same for the views: leaderboards, quests and achivements.

![dfdf](https://cloud.githubusercontent.com/assets/10234700/11614797/df541270-9c4d-11e5-9dd1-64ea81a5336a.png)

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated for iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
