### ISSUE TITLE
google services and admob problem

### ISSUE THREAD

**Issue by jajcelol1** [playgameservices/play-games-plugin-for-unity#844]
this errors appear when i im importing the admob package 
Error importing folder (The pathName assets/plugins is already mapped to fce8a713f1e5a4cc4b9973d1ef630f31. But the meta data wants it to be mapped to cbde64d36fd994c458fffca9e931b232)
Error importing folder (The pathName assets/plugins/android is already mapped to b8f0d9a6a7f9240c981894807effddbc. But the meta data wants it to be mapped to 2f5d736f7c4cb4c1e80d0816d0e81625)
Error importing folder (The pathName assets/plugins/ios is already mapped to 6490bb8acab6f4f92b29615e7429b8df. But the meta data wants it to be mapped to da135550add3c4abca622bda5280d204)

and when i build the app error in repackaging appears

**Comment by guiller711** [comment]
i think the problem on assets/plugins is already mapped to XXXXX is fine it appears when the specific folder exists already. regarding admob try following this https://www.youtube.com/watch?v=q5T98X3EawA

**Comment by jajcelol1** [comment]
i followed the video and this error appears

CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Users\teo\AppData\Local\Android\android-sdk\build-tools\23.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Users/teo/AppData/Local/Android/android-sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.google.android.gms:com.google.unity:com.google.example.games.mainlibproj:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.plus:android.support.v4 -S "C:\Users\teo\Documents\jumpbox\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res" -S "C:\Users\teo\Documents\jumpbox\Temp\StagingArea\android-libraries\google-play-services_lib\res" -S "C:\Users\teo\Documents\jumpbox\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\res" -S "C:\Users\teo\Documents\jumpbox\Temp\StagingArea\android-libraries\play-services-base-8.3.0\res" -S "C:\Users\teo\Documents\jumpbox\Temp\StagingArea\android-libraries\play-services-basement-8.3.0\res" -S "C:\Users\teo\Documents\jumpbox\Temp\StagingArea\android-libraries\play-services-drive-8.3.0\res" -S "C:\Users\teo\Documents\jumpbox\Temp\StagingArea\android-libraries\play-services-games-8.3.0\res" -S "C:\Users\teo\Documents\jumpbox\Temp\StagingArea\android-libraries\play-services-nearby-8.3.0\res" -S "C:\Users\teo\Documents\jumpbox\Temp\StagingArea\android-libraries\play-services-plus-8.3.0\res" -S "C:\Users\teo\Documents\jumpbox\Temp\StagingArea\android-libraries\support-v4-23.1.1\res"

**Comment by claywilkinson** [comment]
Just above this error in the Unity console there is another error message.  If you click on that it will contain the name of the resource that appears twice, then you'll need to remove one of them

**Comment by jajcelol1** [comment]
i fix it all a had to do is restart unity and it works

**Comment by claywilkinson** [comment]
Great! glad you are up and running again.

**Comment by jajcelol1** [comment]
the problem was caused by google-services-play_lib

**Comment by claywilkinson** [comment]
Thanks for the details.

**Comment by DougLazyAngus** [comment]
@jajcelol1 I am having the same problem and I don't understand your resolution.  I have restarted Unity.  When you say "problem was caused by google-services-play_lib", what exactly do you mean?

**Comment by jajcelol1** [comment]
@DougLazyAngus google-services-play_lib causes re-packaging  problem you have to delete it and do this 
add the following lines to Assets/GooglePlayGames/Editor/BackgroundResolution.cs around line 70:
            // Ads
            svcSupport.DependOn("com.google.android.gms",
                "play-services-ads",
                PluginVersion.PlayServicesVersionConstraint);
and then edit Plugin/Android/GoogleMobileAdsPlugin/AndroidManifest.xml and remove:

<activity android:name="com.google.android.gms.ads.AdActivity" ... />
<activity android:name="com.google.android.gms.ads.purchase.InAppPurchaseActivity".../>

this solved the problem and you might need to restart unity.

**Comment by DougLazyAngus** [comment]
now when I try to compile in Android studio I am getting this:

Error:(78, 28) No resource found that matches the given name (at 'value'
with value '@integer/google_play_services_version').

Internet search suggests the answer to this is to add
google-play-services_lib:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/801


When I do that, the original problem comes back,

On Thu, Dec 24, 2015 at 2:11 PM, jajcelol1 <notifications@github.com> wrote:

> @DougLazyAngus <https://github.com/DougLazyAngus>
> google-services-play_lib causes re-packaging problem you have to delete it
> and do this
> add the following lines to
> Assets/GooglePlayGames/Editor/BackgroundResolution.cs around line 70:
> // Ads
> svcSupport.DependOn("com.google.android.gms",
> "play-services-ads",
> PluginVersion.PlayServicesVersionConstraint);
> and then edit Plugin/Android/GoogleMobileAdsPlugin/AndroidManifest.xml and
> remove:
>
>
> this solved the problem and you might need to restart unity.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/844#issuecomment-167162887>
> .
>



-- 
Doug Banks
(650) 346 2107

**Comment by DougLazyAngus** [comment]
I am going to start logging everything I try here:
http://googleplayfail.blogspot.com/

On Sat, Dec 26, 2015 at 11:08 AM, Doug Banks <doug@lazyangus.com> wrote:

> now when I try to compile in Android studio I am getting this:
>
> Error:(78, 28) No resource found that matches the given name (at 'value'
> with value '@integer/google_play_services_version').
>
> Internet search suggests the answer to this is to add
> google-play-services_lib:
> https://github.com/playgameservices/play-games-plugin-for-unity/issues/801
>
>
> When I do that, the original problem comes back,
>
> On Thu, Dec 24, 2015 at 2:11 PM, jajcelol1 <notifications@github.com>
> wrote:
>
>> @DougLazyAngus <https://github.com/DougLazyAngus>
>> google-services-play_lib causes re-packaging problem you have to delete it
>> and do this
>> add the following lines to
>> Assets/GooglePlayGames/Editor/BackgroundResolution.cs around line 70:
>> // Ads
>> svcSupport.DependOn("com.google.android.gms",
>> "play-services-ads",
>> PluginVersion.PlayServicesVersionConstraint);
>> and then edit Plugin/Android/GoogleMobileAdsPlugin/AndroidManifest.xml
>> and remove:
>>
>>
>> this solved the problem and you might need to restart unity.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/844#issuecomment-167162887>
>> .
>>
>
>
>
> --
> Doug Banks
> (650) 346 2107
>



-- 
Doug Banks
(650) 346 2107

**Comment by jajcelol1** [comment]
@DougLazyAngus  try this for the version go to 4:20  the part where she explains how to get the version  https://www.youtube.com/watch?v=q5T98X3EawA

**Comment by appplumbr** [comment]
@DougLazyAngus You may also look at this fix http://stackoverflow.com/questions/34775891/error-more-than-one-library-with-package-name-com-google-android-gms-using-co/34776219#34776219
