### ISSUE TITLE
user cant log in

### ISSUE THREAD

**Issue by XblakninjaX** [playgameservices/play-games-plugin-for-unity#845]
i cant log in to play account when i have admob and this plugin working together

using UnityEngine;
using System.Collections;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;

public class Leaderboard : MonoBehaviour {

	// Use this for initialization
	void Start () {
		PlayGamesPlatform.Activate ();
		Social.localUser.Authenticate((bool success) => {
			if(success){
				Debug.Log ("YAYAY");
			}
			else{
				Debug.Log ("nay");
			}

		});

	}
	
	public void Loadlevel () {
		Social.ReportScore (PlayerPrefs.GetInt ("Highscore"), "CgkIodjFmPALEAIQAQ", (bool success) => 
		                    {
			if(success){
				Debug.Log ("Leaderboard");
			}
			else{
				Debug.Log ("No Leaderboard");
			}
			
		});
		
		PlayGamesPlatform.Instance.ShowLeaderboardUI("CgkIodjFmPALEAIQAQ");
	}
	
	// Update is called once per frame
	void Update () {

		
	}
	}

my code if that helps any
the loadlevel thing is for a button to be pressed for it to lead the leaderboard

**Comment by guiller711** [comment]
does the gameobject holding the script is not destroyed on scene change?

**Comment by XblakninjaX** [comment]
When i had it working before with out admob the ui opened up then I could go back to the same scene. But the button doesn't get destroyed in the scene.

**Comment by XblakninjaX** [comment]
Its not prompting me to sign in if that helps any

**Comment by XblakninjaX** [comment]
@guiller711

**Comment by guiller711** [comment]
Signing in happens only once, when your app is already signed in it automatically uses that account. signing in shows when you have 2 or more google accounts on your device

**Comment by XblakninjaX** [comment]
@guiller771 I think you misunderstud me. Its not do.any thing with Google play not asking to pick a account. It might be becasue I have admob and this plugin together. So I might tjudt wait till they work together for me to.fix it.  I've tested my app on different devices and the same thing happens no promt to log in or choose a account.

**Comment by XblakninjaX** [comment]
I might reimport the plugin again and try that

**Comment by claywilkinson** [comment]
If that does not work, please share a log of the authentication attempt.

**Comment by claywilkinson** [comment]
OK to close this issue?

**Comment by XblakninjaX** [comment]
Yes
