### ISSUE TITLE
conflict with admob

### ISSUE THREAD

**Issue by guiller711** [playgameservices/play-games-plugin-for-unity#848]
current version 0.9.27 automatically deletes contents of google-play-services_lib under Assets > Plugins > Android

conflicts with google Admob as Ads no longer work because Admob needs the contents of google-play-services_lib in order to work properly

**Comment by claywilkinson** [comment]
We're working with the Admob team to release updates that work together.  In the mean time, #814 describes how to work around this (and make your game smaller in the process).

**Comment by XblakninjaX** [comment]
Hope the update is in the near future

**Comment by kunal01** [comment]
@claywilkinson 
when will the next update be released?

**Comment by bumblebee77** [comment]
how can i download previus version? 0.9.26.  thanks

**Comment by claywilkinson** [comment]
@kunal01 - The next version should very soon - we're coordinating some testing with the admob team to make sure both plugins work together :)

@bumblebee77 - you can browse the history of the current-builds directory to find the older versions.  Just out of curiosity - why do you want the old one?

**Comment by bumblebee77** [comment]
Bacause i could not found any solution for this isue.  #832 Your  "option 2" did not work for me 
 
(I could not try  your  " Option 1" . i have no admob plugin installed. I am using Admob via Heyzap Madiation pugin.)

**Comment by claywilkinson** [comment]
If you are using non-google plugins, I'd suggest contacting the developer of that plugin.  Feel free to refer them to this site if they have questions.

We're moving to using split aars to be more granular in what client libraries are included in the application.  This results in a substantial reduction in size both in terms of bytes and in DEX method counts.  See more information at: http://android-developers.blogspot.com/2014/12/google-play-services-and-dex-method.html

**Comment by XblakninjaX** [comment]
Did you guys update it to work with admob?

**Comment by Honikou** [comment]
...Waiting for admob/google service working together

**Comment by lfxsantos** [comment]
Same issue here.

**Comment by NILaguiar** [comment]
I am having the same problem of the conflict between google play service and AdMob.

**Comment by fadsel** [comment]
This one is weird ...  mine does not delete anything , 
but it keeps on coming infront of everything even the admob ads ... 
https://github.com/playgameservices/play-games-plugin-for-unity/issues/891

**Comment by claywilkinson** [comment]
We haven't forgotten this issue - Stay tuned!

**Comment by gordonw** [comment]
I have a similar problem, Google Play Game Services removed google play services_lib, which is needed by Chartboost, please test Chartboost integration too.

**Comment by owenmills** [comment]
@gordonw you might want to check out cult2ash's question and self answer https://github.com/playgameservices/play-games-plugin-for-unity/issues/832
he was having a similar issue.

On a related note @claywilkinson are you working with the google analytics team to avoid the conflict with their plugin as well?

**Comment by Wolfos** [comment]
How do all Android plugins manage to suck this much? Seriously, iOS plugins work mostly out of the box, this one took me a whole workday to configure. Thanks for using Java for everything, Google!

**Comment by claywilkinson** [comment]
Yes, that work is underway as well, but it might be a little longer than admob. I don't know exactly when we'll update the plugins, but it will be very soon.

**Comment by FocusBit** [comment]
lease Tell What is the status of next update, Eagerly waiting...

**Comment by amankumar0000** [comment]
I am having the same problem of the conflict between google play service and AdMob
and waiting for new update in which it is solved
do it fast i m nt able to give update to my app because of this

**Comment by natysoz** [comment]
using heyzap im stuck like everyone else , 0.9.3 keep delete heyzap import files .

**Comment by gordonw** [comment]
@natysoz  try skipping "Android setup" for HeyZap in Unity3D

**Comment by claywilkinson** [comment]
The admob plugin has been updated to version 3.0.0 which is compatible with this plugin
https://github.com/googleads/googleads-mobile-unity

**Comment by claywilkinson** [comment]
OK to close this one?
