### ISSUE TITLE
Unity 5.3.0f4 problem

### ISSUE THREAD

**Issue by dhanrajsinh24** [playgameservices/play-games-plugin-for-unity#850]
In DummyClient.cs

LogUsage() have to be like this :

private static void LogUsage()
        {
            GooglePlayGames.OurUtils.Logger.d("Received method call on DummyClient - using stub implementation.");
        }

Because now Unity has its own Logger().

**Comment by dhanrajsinh24** [comment]
Logger is ambiguous reference now, because Unity 5.3.0 have its own Logger method.
So it should be called as "GooglePlayGames.OurUtils.Logger".

**Comment by dhanrajsinh24** [comment]
Also now All platform packages are seperated, so I have only android platform loaded, and i am also having some errors about some xcode stuff.
Though i solved them

**Comment by ProtectioGames** [comment]
I have this error to how to fix it or should I just wait for next update. Am using the plugin for Android and IOS

**Comment by dhanrajsinh24** [comment]
You have to replace all methods in all scripts sadly.

**Comment by ProtectioGames** [comment]
ouch!! that's too much work. Well I think I'll downgrade to unity 5.2.3 till google decide to update the plugin. Do you know a way to get notified when the plugin is updated ?

**Comment by dhanrajsinh24** [comment]
Lets wait for authorized person to comment here i think!

**Comment by claywilkinson** [comment]
Everyone is "authorized" to comment :)  Also, if you have changes, feel free to submit a pull request to share them with the project. I'll try to take a look at 5.3  today.  Stay Tuned!

**Comment by MrTactic** [comment]
I fixed issue add 
using Logger = GooglePlayGames.OurUtils.Logger; 
at script :)

**Comment by aniruddhahar** [comment]
I just manually replaced 'Logger' with 'GooglePlayGames.OurUtils.Logger' everywhere. If you're developing for android as I am, chances are you also need to install iOS support in 5.3. Google Play Game Services do need some Xcode which is included in the iOS support module.

**Comment by dhanrajsinh24** [comment]
@aniruddhahar you could add #if UNITY_IOS code
I did that because i dont want to use ios module

**Comment by MrTactic** [comment]
@aniruddhahar I so lazy for manual replace ^_^

**Comment by claywilkinson** [comment]
Thanks @aniruddhahar / @dhanrajsinh24  - I'll add the iOS check to the list.

**Comment by aniruddhahar** [comment]
Actually, I just got rid of anything that uses google play services, temporarily. I'll try and check if @dhanrajsinh24 's solution works in my project and post here later.

**Comment by guiller711** [comment]
@MrTactic suggestion seems to work fine add 
using Logger = GooglePlayGames.OurUtils.Logger;
at every script which have errors

**Comment by AdnanNazir** [comment]
You can just easily rename the script by going to find and replace. replace Logger to something like PlayLogger or PlayGameLogger !
It's just simple additionally you can also use replace and just replace all the instances of Logger with OurUtils.Logger so that there won't be any chances of breaking.
For Xcode Related error yes you must also install the EditorSupportForiOS to evaporate all errors :)

**Comment by kd7uiy** [comment]
https://github.com/playgameservices/play-games-plugin-for-unity/pull/854 should take care of those problems, I believe.

**Comment by ejjoo** [comment]
Find: ^(\s+)using GooglePlayGames.OurUtils;

Replace With: \1using GooglePlayGames.OurUtils;\n\1using Logger = GooglePlayGames.OurUtils.Logger;

this issue seem to be cleared by #854.
But still remains at 0.9.21
