### ISSUE TITLE
Error in Games.cs on Importing Package

### ISSUE THREAD

**Issue by pranavt007** [playgameservices/play-games-plugin-for-unity#851]
I am getting the following error when I import the package - 
Assets/GooglePlayGames/Platforms/Android/Gms/Games/Games.cs(179,23): error CS0309: The type `Status' must be convertible to `Com.Google.Android.Gms.Common.Api.Result' in order to use it as parameter `R' in the generic type or method `Com.Google.Android.Gms.Common.Api.PendingResult<R>'

Since this is automatically created, I am not sure why it's coming. I thought it may have to do with multiple 3rd party services present in my project (Soomla, Facebook, Parse)

**Comment by claywilkinson** [comment]
Which version of Unity are you using?  I have not seen this problem with 5.1 or 5.3.  Can you see what type Status is?  Does it match what is checked into the repo at:  https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Platforms/Android/Gms/Common/Api/Status.cs

**Comment by pranavt007** [comment]
Found the solution. It was a conflict with one of the 3rd Party scripts I was using
