### ISSUE TITLE
iOS Error: Cannot find candidate artifact for com.google.android.gms:play-services-games:8.1+

### ISSUE THREAD

**Issue by Armend** [playgameservices/play-games-plugin-for-unity#853]
Hello everyone,

i've finished my game for android and now i want to port it to iOS, but i'm getting this error. :/ 
I've searched for fixes but all I found was that i have to update the Android SDK. But how can i do this on my MacBook. :/ 

Log:
Google.JarResolver.ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-games:8.1+
  at Google.JarResolver.PlayServicesSupport.LoadDependencies (Boolean allClients) [0x00000] in <filename unknown>:0 
  at Google.JarResolver.PlayServicesSupport.CreateInstance (System.String clientName, System.String sdkPath, System.String settingsDirectory) [0x00000] in <filename unknown>:0 
  at GooglePlayGames.BackgroundResolution..cctor () [0x00000] in /Users/.../Unity/Gamename/Assets/GooglePlayGames/Editor/BackgroundResolution.cs:40 
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

Thanks.

**Comment by claywilkinson** [comment]
Yes - that is a bug, we're working on an update.  In the mean time you can change
BackgroundResolution.cs, line 17 to remove the UNITY_EDITOR - so it would be:
` #if UNITY_ANDROID`.  You might need to restart the editor to unload this class.

**Comment by Armend** [comment]
Thank you for your reply. Yes, this was the couse of the problem, thanks. 
Can i assume that this will not affect my game on iOS since it was Android and Unity Code?

**Comment by claywilkinson** [comment]
Correct - that error is android specific, your iOS build will be unaffected.

**Comment by Armend** [comment]
Allright. Thank you very much. This issue can be closed.
