### ISSUE TITLE
"GIDSignIn.h" file not found... nothing helps

### ISSUE THREAD

**Issue by Armend** [playgameservices/play-games-plugin-for-unity#855]
Hello everyone,

first, sorry, i know that this is a bug that is often mentioned but no method was helfpul.

i have the bug that XCode can't find "GIDSignIn.h". I searched for solutions and found some, but none of them were helpful for me. The last time, 3 months in the past, I just had to change the imports to "#import <GoogleSignIn/GIDSignIn.h>" but this time it's not working. 
I deleted the GoogePlayGames Folder in Assets and reimported it,but it still failed to compile. 

I am using Unity 5.3.0f4 Personal and 
XCode 7.1 beta (7B60) and
Cocoapods: 0.39.0. 

Also, after bulding the XCode Project in Unity there shows a bug in the console:
"Invalid PBX Project" (https://cloud.githubusercontent.com/assets/2729892/10115269/489b4c82-6402-11e5-8e60-2da669d0a240.png) (i have already mentioned it, issue #725)

I hope somebody knows what to do. :/ 

Thanks.

**Comment by claywilkinson** [comment]
Can you run `pod update` in the xcode project directory made by Unity?  Are there any errors there?

**Comment by Armend** [comment]
Thank you for your reply. 

So this bugs i mentioned above are gone since i updated my Mac and my XCode. Now i have the XCode 7.2 Version. After "pod update" this bugs were gone and the "Invalid PBX Project" bug were gone too, since the 7.2 Version. 

Now I'm facing another error. "Undefined symbols for architecture arm64: "_GADURequestInterstitial", but I don't know if this is the right place to ask for support, since this looks like a bug related do Admob Plugin.

**Comment by mrThinBone** [comment]
Could you explain how to solve "Undefined symbols for architecture armv7"?
I got the same problem #1007
