### ISSUE TITLE
Can't Show Invitation OnInvitationReceived Turn Base Multiplayer  

### ISSUE THREAD

**Issue by ariefannur** [playgameservices/play-games-plugin-for-unity#857]
Can't trigger callback method OnInvitationReceived. 
this. the code 

public void OnInvitationReceived(Invitation invitation, bool shouldAutoAccept) {

```
    PlayGamesHelperObject.RunOnGameThread(() =>
                                          {
        Debug.Log("AF Invitaionnnnnnnnnnnnnnnnnnnnnnnn "+invitation.Inviter.DisplayName);
    if (shouldAutoAccept) {
        // Invitation should be accepted immediately. This happens if the user already
        // indicated (through the notification UI) that they wish to accept the invitation,
        // so we should not prompt again.
        //ShowMyCustomWaitingScreen();
            txt_invite.text = this.invitation.Inviter.DisplayName;
            panel_invite.SetActive(true);
        PlayGamesPlatform.Instance.TurnBased.AcceptInvitation(invitation.InvitationId, MultyPlayer.getInstance().OnMatchStarted);
    } else {
        // The user has not yet indicated that they want to accept this invitation.
        // We should *not* automatically accept it. Rather we store it and 
        // display an in-game popup:
            txt_invite.text = this.invitation.Inviter.DisplayName;
            panel_invite.SetActive(true);
        this.invitation = invitation;

    }
    });
}
```

this is the log 

/dalvikvm(19664): WAIT_FOR_CONCURRENT_GC blocked 220ms
I/Unity   (20409):  [Play Games Plugin DLL] 12/11/15 22:45:53 +07:00 DEBUG: Entering internal callback for TurnBasedManager#TurnBasedMatchesCallback
I/Unity   (20409):
I/Unity   (20409): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (20409):
I/Unity   (20409): Got 0 invites
I/Unity   (20409):
I/Unity   (20409): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (20409):
I/Unity   (20409):
I/Unity   (20409):
I/Unity   (20409): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   (20409):
D/dalvikvm(20815): GC_CONCURRENT freed 4415K, 21% free 17735K/22280K, paused 12ms+34ms, total 148ms
D/dalvikvm(20409): threadid=14: thread exiting, not yet detached (count=0)

Any Suggestion?

**Comment by claywilkinson** [comment]
Can you share how/when you are building the client configuration?  Do you call `WithInvitationDelegate()` ?

**Comment by ariefannur** [comment]
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
			// enables saving game progress.
				.EnableSavedGames()
				.WithInvitationDelegate(OnInvitationReceived) 
				
				// registers a callback for turn based match notifications.
				.WithMatchDelegate(OnGotMatch) 

				.Build();
		
		PlayGamesPlatform.InitializeInstance(config);
		// recommended for debugging:
		PlayGamesPlatform.DebugLogEnabled = true;
		
		PlayGamesPlatform.Activate();

in the start() method  

and I call this method after sign in
PlayGamesPlatform.Instance.TurnBased.RegisterMatchDelegate(OnGotMatch);
				PlayGamesPlatform.Instance.RegisterInvitationDelegate(OnInvitationReceived);

**Comment by ariefannur** [comment]
@claywilkinson do you have any suggestion ?

**Comment by claywilkinson** [comment]
Is the game in the foreground when the invitation is received, or is it starting the game from clicking on the notification?  Can you reproduce it using the TicTacToss sample?  I looked at this briefly, and I did not see anything unusual (which probably means I am not understanding your scenario...)

**Comment by ariefannur** [comment]
the scenario is. when i invite a friend to join the game. there isn't anything happen in the other client. 
it's true if i invite a friend, the other client (friend device) will trigger OnInvitationReceived method. right?
in my reproduce there are anything happen with OnInvitationReceived. @claywilkinson 

thanks before.

**Comment by aditya2** [comment]
@claywilkinson Sir i m too facing a problem with invitation delegate but on RealTime situation .... my problem is that when i send invitation to my friend (game is not running on friend's phone at this time), he is receiving this invitation on his notification bar and when he accepts this invitation from notification bar the game launches but without invitation accepted .... here is my issue along with code #1021

**Comment by RamGul** [comment]
I have same issue..when i call thisPlayGamesPlatform.Instance.TurnBased.CreateWithInvitationScreen(MinOpponents, MaxOpponents,
			Variant, OnMatchStarted);

nothing happens on player 2 screen..On LOG it shows status=NOtInvitedYet..Although i have called this method on button click..Ataching my code


using UnityEngine;
using System.Collections;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine.SocialPlatforms;
using GooglePlayGames.BasicApi.Multiplayer;
using System.Text;
public class Multiplayer : MonoBehaviour {
	public GameObject matchesPopUp;
	const int MinOpponents = 1;
	const int MaxOpponents = 1;
	const int Variant = 0;
	Invitation mIncomingInvitation = null;
	TurnBasedMatch mIncomingMatch=null;
	bool shouldAutoLaunch=false;
	string Opponent;
	bool pickParticpant;
	public GameObject player;
	public GameObject turnPopUp;

	TurnBasedMatch match;
	TurnBasedMatch gameMatch;
	string matchID;
	byte[] myData;
	int i;
	bool urTurn;
	bool flag=false;

	//destination point
	private Vector3 endPoint;
	//alter this to change the speed of the movement of player / gameobject
	public float duration = 1.0f;
	//vertical position of the gameobject
	private float yAxis;
	string whoIsNext ;
	string initialise;
	private bool clickedPlay;
	void Awake(){

		i = 0;
		PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
			// registers a callback to handle game invitations.
			.EnableSavedGames()
			.WithInvitationDelegate(OnInvitationReceived) 

			// registers a callback for turn based match notifications.
			.WithMatchDelegate(OnGotMatch) 

			.RequireGooglePlus()
			.Build();

		PlayGamesPlatform.InitializeInstance(config);

		// recommended for debugging:
		PlayGamesPlatform.DebugLogEnabled = true;

		// Activate the Google Play Games platform
		PlayGamesPlatform.Activate();
	}
	void Start () {
		pickParticpant = false;
		urTurn = false;
		if (PlayGamesPlatform.Instance.IsAuthenticated ()) {
			matchesPopUp.SetActive(true);

		} else {
			Social.localUser.Authenticate ((bool success) => {
				if (success) {
					matchesPopUp.SetActive(true);
					PlayGamesPlatform.Instance.TurnBased.RegisterMatchDelegate(OnGotMatch);
					PlayGamesPlatform.Instance.TurnBased.AcceptFromInbox(OnMatchStarted);
				} else {

				}
			});
		}
	}
	void OnGotMatch(TurnBasedMatch match, bool shouldAutoLaunch) {
		if (shouldAutoLaunch) {
			// if shouldAutoLaunch is true, we know the user has indicated (via an external UI)
			// that they wish to play this match right now, so we take the user to the
			// game screen without further delay:
			OnMatchStarted(true, match);
		} else {

			Debug.Log ("Match Not null");
			// if shouldAutoLaunch is false, this means it's not clear that the user
			// wants to jump into the game right away (for example, we might have received
			// this match from a background push notification). So, instead, we will
			// calmly hold on to the match and show a prompt so they can decide
			mIncomingMatch = match;
		}
	}
	public void Invitations(){
		PlayGamesPlatform.Instance.TurnBased.GetAllInvitations(
			(invites) =>
			{
				Debug.Log("Got " + invites.Length + " invites");
				string logMessage = "";
				foreach(Invitation invite in invites)
				{
					logMessage += " " + invite.InvitationId + " (" +
						invite.InvitationType + ") from " +
						invite.Inviter + "\n";
					if (mIncomingInvitation == null) {
						mIncomingInvitation = invite;
					}
				}
				Debug.Log(logMessage);
			});
	}

	// Update is called once per frame

	public void QuickMatch(){
		PlayGamesPlatform.Instance.TurnBased.CreateWithInvitationScreen(MinOpponents, MaxOpponents,
			Variant, OnMatchStarted);
		
	}
	public void initGame(TurnBasedMatch match) {

		Debug.Log("I am here2"+"match "+match+ "data " +myData+ "ID "+match.SelfParticipantId );
		initialise="initialised";
		PlayGamesPlatform.Instance.TurnBased.TakeTurn(match, myData,match.SelfParticipantId, (bool success) => {
			if (success) {
				pickParticpant=true;
				urTurn = true;
				// turn successfully submitted!
			} else {

				Debug.Log("I am here eroor   ");
				//	Opponent=DecideWhoIsNext (lmatch);
				// show error
			}
		});
	}
	void OnMatchStarted(bool success, TurnBasedMatch match) {
		if (success) {
			// go to the game screen and play!
			myData = Encoding.ASCII.GetBytes ("initialised");
			mIncomingMatch = match;

			if (mIncomingMatch.Data == null) {
				Debug.Log ("initiation......................");
				player.transform.position = new Vector3 (0, 0, 0);
				initGame (mIncomingMatch);
			} 
			// I can only make a move if the match is active and it's my turn!
			bool canPlay = (mIncomingMatch.Status == TurnBasedMatch.MatchStatus.Active &&
				mIncomingMatch.TurnStatus == TurnBasedMatch.MatchTurnStatus.MyTurn);
			if (canPlay) {
				matchesPopUp.SetActive (false);
			//	urTurn = true;
				foreach (Participant p in mIncomingMatch.Participants) {
					i++;
					Opponent=p.ParticipantId;
				}
			} else {
				// show error message
			}
	}
}
		
	public void OnInvitationReceived(Invitation invitation, bool shouldAutoAccept) {
		if (shouldAutoAccept) {
			// Invitation should be accepted immediately. This happens if the user already
			// indicated (through the notification UI) that they wish to accept the invitation,
			// so we should not prompt again.
			ShowMyCustomWaitingScreen();
			Debug.Log ("shouldAutoAccept......................");
			PlayGamesPlatform.Instance.TurnBased.AcceptInvitation(invitation.InvitationId, OnMatchStarted);
		} else {
			// The user has not yet indicated that they want to accept this invitation.
			// We should *not* automatically accept it. Rather we store it and 
			// display an in-game popup:
			Debug.Log ("shouldAutoAccept nooooooo.....................");
			mIncomingInvitation = invitation;
		}
	}
	void ShowMyCustomWaitingScreen(){

		Debug.Log ("Invitation recieved......................");

	}
	void Update(){
		if (urTurn) {
			//check if the screen is touched / clicked   
			if((Input.touchCount > 0 && Input.GetTouch(0).phase == TouchPhase.Began) || (Input.GetMouseButtonDown(0)))
			{
				//declare a variable of RaycastHit struct
				RaycastHit hit;
				//Create a Ray on the tapped / clicked position
				Ray ray;
				//for unity editor
				#if UNITY_EDITOR
				ray = Camera.main.ScreenPointToRay(Input.mousePosition);
				//for touch device
				#elif (UNITY_ANDROID || UNITY_IPHONE || UNITY_WP8)
				ray = Camera.main.ScreenPointToRay(Input.GetTouch(0).position);
				#endif

				//Check if the ray hits any collider
				if(Physics.Raycast(ray,out hit))
				{
					//set a flag to indicate to move the gameobject
					flag = true;
					//save the click / tap position
					endPoint = hit.point;
					//as we do not want to change the y axis value based on touch position, reset it to original y axis value
					endPoint.y = yAxis;
					Debug.Log(endPoint);
				}

			}
//check if the flag for movement is true and the current gameobject position is not same as the clicked / tapped position
			if(flag && !Mathf.Approximately(player.transform.position.magnitude, endPoint.magnitude)){ //&& !(V3Equal(transform.position, endPoint))){
				//move the gameobject to the desired position
				player.transform.position = Vector3.Lerp(player.transform.position, endPoint, 1/(duration*(Vector3.Distance(player.transform.position, endPoint))));
			}
			//set the movement indicator flag to false if the endPoint and current gameobject position are equal
			else if(flag && Mathf.Approximately(player.transform.position.magnitude, endPoint.magnitude)) {
				
				Debug.Log("I am here");
				//myData=Encoding.ASCII.GetBytes ("nextTurn");
				string next = DecideNextToPlay ();

				PlayGamesPlatform.Instance.TurnBased.TakeTurn(mIncomingMatch, myData,next, (bool success) => {
					if (success) {
						pickParticpant=true;
						// turn successfully submitted!
					} else {

						Debug.Log("I am here2");
					//	Opponent=DecideWhoIsNext (lmatch);
						// show error
					}
				});
flag = false;
		
			}
		}
	}

	string DecideNextToPlay()
	{
		//return "p_2";

		Debug.Log ("slotssssssssssss " + mIncomingMatch.AvailableAutomatchSlots);
		if (mIncomingMatch.AvailableAutomatchSlots > 0)
		{
			Debug.Log("avalaible.........................");
			return null;
		}
		else
		{
			Debug.Log("else.........................");
					Participant opponent = GetOpponent(mIncomingMatch);
			return opponent == null ? null : opponent.ParticipantId;
		}
	}

	public static Participant GetOpponent(TurnBasedMatch match)
	{
		Debug.Log("Participant.........................");
		foreach (Participant p in match.Participants)
		{
			if (!p.ParticipantId.Equals(match.SelfParticipantId))
			{
				Debug.Log("foreach.........................");
				Debug.Log ("ParticipantID" + p);
				return p;


			}
		}
		return null;
	}
//	void OnGUI(){
//		GUI.Label (new Rect (Screen.width * 0.5f, Screen.height * 0.1f, Screen.width * 0.2f, Screen.width *0.2f), " name " + Opponent + "  " +" turn "+pickParticpant + "count" + i);
//
//	}

}

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
