### ISSUE TITLE
Call back function of match delegate android unity is not triggering

### ISSUE THREAD

**Issue by rahuldotar** [playgameservices/play-games-plugin-for-unity#861]
I am developing multiplayer turn based game using android play games.i frequently face an issue of not triggering call back function of match delegate in android unity.But data is getting from inbox.Is any one know what the issue is?

**Comment by claywilkinson** [comment]
I am not sure I understand the question.  Are you saying:

1. the game is not currently running on the device when:
2. Notification appears in the notification bar of a match change
3. Click on the notification and it eventually starts the game, but the delegate is not called?

**Comment by rahuldotar** [comment]
@claywilkinson Thanks for your reply. But the way you understand the question is not correct.

I register turn based match delegate function in Start function using this: "PlayGamesPlatform.Instance.TurnBased.RegisterMatchDelegate(OnGotMatch);"

But after taking a participant turn , the opponent side doesn't trigger the OnGotMatch callback function.
So I didn't get updated match data from the OnMatchStarted function.

Am facing the same issue on turn based sample game "Tic tac toss".  

I think @claywilkinson get what I meant. If anyone figure out this problem it would be really helpful.

**Comment by melayerjohn** [comment]
Hi i am facing the same issue of not getting call back of match function. I have to go through show match inbox then select match then only i can get match delegate , instead i need to take call back of match as soon as request comes to me.

**Comment by ariefannur** [comment]
i get same problem https://github.com/playgameservices/play-games-plugin-for-unity/issues/857

**Comment by rahuldotar** [comment]
Anyone got any solution to this issue?

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
