### ISSUE TITLE
ERROR ITMS-90535 gpg.bundle

### ISSUE THREAD

**Issue by Armend** [playgameservices/play-games-plugin-for-unity#863]
Hello everyone,

I have finally tried to submit my iOS App to the Appstore, but as I tried to upload the App-Archive i got this error: http://prntscr.com/9edg4a 
"Unexpected CFBundleExecutable key. The bundle at 'Payload/ggo.app/gpg.bundle' does not contain a bundle executable...." 

I have tested the app on my iPhone 5 and it works without any errors. So I thought i could upload it to iTunes Connect but well, then this error showed up. :/ 

I hope someone can help me, since there is the note "If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update do address this issue."

Thanks. 

Information:
XCode: 7.2
Unity5.3 Personal
PlayGames 0.9.27

**Comment by Armend** [comment]
I had to delete the Key "CFBundleExecutable" in this File: "Pods/Pods/GooglePlayGames/Resources/gpg.bundle/info.plist", but to show this entry i had to press right click and switch "show Raw Keys/Values". Then Right Click and cut CFBundleExecutable. Now it works.

**Comment by claywilkinson** [comment]
Thanks for the workaround information.  The next release of the iOS library will fix this as well.

**Comment by claywilkinson** [comment]
This is fixed in the latest version of the GooglePlayGames C++ SDK (v. 5.1) which is used by the updated plugin, 0.9.30.
