### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by edgarscr** [playgameservices/play-games-plugin-for-unity#864]
can u help me:?

http://forum.unity3d.com/threads/unity-5-3-compile-error.374042/#post-2424107

**Comment by claywilkinson** [comment]
If it is related to this plugin, please post enough information to  pose a question or issue.

**Comment by edgarscr** [comment]
This is my error.
![upload_2015-12-15_8-37-57](https://cloud.githubusercontent.com/assets/16306453/11828577/2614d4b2-a368-11e5-9ef2-1dba4bd76c87.png)

**Comment by ffff1111** [comment]
I was having the same issue.
but I've finally found the solution.
It seems this GooglePlayGames version uses more package resources than older versions (maybe?)
Open SDK Manager,download and install all packages of your API number.
At least this works for me.

**Comment by edgarscr** [comment]
how i can know what is my api number

**Comment by ffff1111** [comment]
I referred to the Android API version you are using to compile.
As your log says,your newer API installed is Android-23 (Android 6.0).
Maybe you have some packages of that API not installed.

**Comment by edgarscr** [comment]
this is my SDK Manager

![upload_2015-12-15_8-37-57](https://cloud.githubusercontent.com/assets/16306453/11831596/cb2b6858-a381-11e5-9fbb-636f564d79bf.png)

**Comment by ffff1111** [comment]
Select "show updates/new" and download the Android 6.0 API and the Android SDK Build Tools (23.0.2).

I just do that and all errors go away.

**Comment by edgarscr** [comment]
ok i'll go to try. thanks for that.

**Comment by edgarscr** [comment]
i added API 6 and now this error.

![image](https://cloud.githubusercontent.com/assets/16306453/11845296/6cbf159e-a3e5-11e5-8f1e-54e4fa97f698.png)

**Comment by edgarscr** [comment]
Upppppppp

**Comment by rakuzas** [comment]
have you tried delete files in your temp folder of your project? Try it..

**Comment by rakuzas** [comment]
![image](https://cloud.githubusercontent.com/assets/4284562/11870445/f4bc6ffa-a502-11e5-966b-546a2beec047.png)

**Comment by edgarscr** [comment]
i deleted Library, Temp, obj folders and nothing. same error.

**Comment by edgarscr** [comment]
please i need compile. i need upload a new version to google. and i have this issues.

![image](https://cloud.githubusercontent.com/assets/16306453/11871068/14823b44-a49f-11e5-81f6-44a01f51dd88.png)
![image](https://cloud.githubusercontent.com/assets/16306453/11871074/1c1be9b8-a49f-11e5-9be2-f54f3bbdd76e.png)
![image](https://cloud.githubusercontent.com/assets/16306453/11871077/214f95f6-a49f-11e5-9535-4c82e0ea8637.png)

**Comment by edgarscr** [comment]
helppp

**Comment by claywilkinson** [comment]
Can you copy the text of the message?  I think the actual error is at the end of the log, thiese are just warnings.  

It looks like you have multiple copies of some resources.  

Also the contents of Assets/Plugins/Android would also help to make sure you don't have duplicates.

**Comment by edgarscr** [comment]
i haven't duplicates.

**Comment by pedro15** [comment]
same problem :/

**Comment by edgarscr** [comment]
Please. really i need a solution.

**Comment by pedro15** [comment]
i think that we need to download the android API v6.0

i will try installing that , its the last solution that i can find .. .

**Comment by edgarscr** [comment]
Can u install and tell me this work? my internet is really bad to download all.

**Comment by pedro15** [comment]
I am downloading.

**Comment by edgarscr** [comment]
Ok waiting. @pedro15

**Comment by pedro15** [comment]
FINALLY GET SOLID BUILD ! 

THE SOLUTION IS :  DOWNLOAD THE SDK FOR ANDROID 6.0 on the SDK Manager 

here is how my sdk are:

![captura de pantalla 78](https://cloud.githubusercontent.com/assets/13208551/11911107/1688e5ac-a5dd-11e5-98c6-274c25dfe616.png)
![captura de pantalla 79](https://cloud.githubusercontent.com/assets/13208551/11911108/1b157c16-a5dd-11e5-8120-f0b17d5535f6.png)
![captura de pantalla 82](https://cloud.githubusercontent.com/assets/13208551/11911117/5b1a688a-a5dd-11e5-9659-2843942b79e4.png)
It work (tested with example proyect 'Cubic Pilot'): 
![captura de pantalla 80](https://cloud.githubusercontent.com/assets/13208551/11911115/4d22faf8-a5dd-11e5-8dce-d20cbf434d97.png)
![captura de pantalla 81](https://cloud.githubusercontent.com/assets/13208551/11911116/5325e0aa-a5dd-11e5-99e7-a08711767442.png)

**Comment by edgarscr** [comment]
Thanks u i go to try.

**Comment by claywilkinson** [comment]
OK to close this one?
