### ISSUE TITLE
AndroidTokenClient.GetIdToken returns null on first invocation

### ISSUE THREAD

**Issue by rkachowski** [playgameservices/play-games-plugin-for-unity#865]
When getting an auth token from the os to authenticate against a backend service, the method returns null on first invocation. It appears that the method is asynchronous and the value is available later in the application lifetime - however this isn't clearly shown to the developer.

### to reproduce
1. Create a unity application and configure google play console + google developer console to have client id's for a web app and an android apk
2. Setup the unity app with the appropriate information from the console and the web app client id
3. In the application, call `Debug.Log("token - " +PlayGamesPlatform.Instance.GetIdToken())` after activating and configuring PlayGamesPlatform

### result
The token value is null, but from the device logs it's clear that the token is loaded at a later point in time.

### expected
The token is available to be consumed after the method has returned. Either the method is synchronous or a callback parameter is exposed to allow access to the token as soon as possible

**Comment by claywilkinson** [comment]
It is an asynchrounous  call.  I'll make a note to add an overload with a callback.  Please feel free to submit a pull request with the method also.

**Comment by claywilkinson** [comment]
This is fixed now in the latest plugin, version 0.9.30.  However, with the coming updates to [Game Permissions on Android](http://android-developers.blogspot.com/2016/01/play-games-permissions-are-changing-in.html?m=1), you should move to using the `PlayGamesPlatform.GetServerAuthCode()` flow.
