### ISSUE TITLE
Google.GamesJarResolver.ResolutionException

### ISSUE THREAD

**Issue by pitaslayer** [playgameservices/play-games-plugin-for-unity#866]
I donwloaded the lastest version of the plugin and I have the following exception:

Google.GamesJarResolver.ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-games:8.1+

Already updated the google play services from the sdk but the error doesn't disappear.
What I'm doing wrong?

Kind Regards,
Tiago Alves

**Comment by pedro15** [comment]
I have the same problem :(

**Comment by xBlackEagle13** [comment]
Same problem too :/

**Comment by claywilkinson** [comment]
Sounds like you need to update the repository in the Android SDK Manager.  
From Unity, you can click Window > Google Play Games > Downloads > Google Play Games SDK (Android)...
This will prompt to start the SDK Manager.

Scroll down to the "extras" section, and  make sure the following are installed and up to date:
1. Android support repository
2. Google Play Services
3. Google Repository
<img width="676" alt="screen shot 2015-12-18 at 8 59 13 am" src="https://cloud.githubusercontent.com/assets/8752378/11902328/e3abc8f6-a565-11e5-85b7-dfd3bddf80a3.png">

Then it should have the artifacts locally.

**Comment by pedro15** [comment]
I fix that upgrading the android sdk , BUT now i get this error at build:
CommandInvokationFailure: Failed to re-package resources. See the Console for details.

**Comment by claywilkinson** [comment]
The repackaging error is usually caused by including the same resource multiple times.  Can you share the contents of your Assets/Plugins/Android directory?  You may need to expand some directories to be able to see all the .aar and .jar files

**Comment by pitaslayer** [comment]
Problem Solved! Thank you very much!

**Comment by RyanAult** [comment]
@pitaslayer How did you solve this issue?

**Comment by gabdsg** [comment]
I have the same problem

**Comment by RyanAult** [comment]
@gabdsg Did you update to the latest using Android SDK manager?

**Comment by RyanAult** [comment]
My issue is that I can build locally, but cloud build fails for iOS (Android works sometimes)

**Comment by TinyTitanAli** [comment]
@pitaslayer if you get your issue fixed, it would be nice to share with everybody else how you did it, which files were the duplicates, how you went about finding the duplicates, etc.
