### ISSUE TITLE
Leaderboard and Achievements UI not working.

### ISSUE THREAD

**Issue by umer-azeem** [playgameservices/play-games-plugin-for-unity#871]
User authentication is working fine and my score are being posted fine either, the issue here is that when I call ShowLeaderboardUI(); or Social.ShowAchievementsUI(); on buttons clicks, they are not working.
what could have went wrong.
Please help me out, i would really appreciate it.
Thanks

**Comment by skirners1** [comment]
Have you done the setup in unity, including importing the resources from GPS developer console?

**Comment by claywilkinson** [comment]
Also, make sure the player is authenticated.  A log of trying to show them will also help diagnose the problem.

**Comment by skirners1** [comment]
Hello Clay!

The players are authenticated on android, and the same code is used on iOS, so I think that they are authenticated. Maybe not. Maybe the authentication is what screw things up? I used an account on my android device first and it worked. when I used the same account on iOS it didn’t work, and stopped working back on android. Maybe there is a column in a database somewhere on the google server that is supposed to be empty, as in not using iOS, for the framework to function, or for a json to be properly disassembled?

I would really like to help out. However I’m such a super novice at programming. Is there any guide I can follow, to how I can produce such a log you mention?


Best regards,
Lucas Ivarsson
Fiaky

**Comment by claywilkinson** [comment]
OK to close this?

**Comment by skirners1** [comment]
Yes!

**Comment by claywilkinson** [comment]
Thanks!
