### ISSUE TITLE
iOS accept quest crash

### ISSUE THREAD

**Issue by GametreeRoger** [playgameservices/play-games-plugin-for-unity#873]
I want to accept google-play-game's quest, but accept quest it will crash.

I got this error in xocde:
event_data(27): EXC_BAD_ACCESS(code=2, address=0x154b3f0)

IQuest log:
Accepting Quest: [NativeQuest: Id=<CgkIw6fQlp4REAESDQoJCKeSu4mlGhACEBAYAQ, Name=MONLoginQuest, Description=MONLoginQuest, BannerUrl=https://lh6.ggpht.com/Qf5DSHh_y39fYVMnezYG0af63l8UIF8JJF3SFVz-Ro_jsYm-YV-0yU9aNzhO3JAbQw, IconUrl=https://lh5.ggpht.com/xrQNTT8-u02gvnDsHkYBhWnGj4uPjYxeplxuxx8IJb-_vO6awEH_AsdX3ZyZVqg68bc, State=Open, StartTime=12/20/2015 16:00:00, ExpirationTime=12/21/2015 16:00:00, AcceptedTime=]
System.Collections.Generic.List`1:ForEach(Action`1)
GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()

The problem seems like I check the “Repeating quest” box.
Remove the “Repeating quest” everything is ok.
But in Android is work.

Thanks.

Information:
Unity : 5.2.3
XCode : 7.2
PlayGames : 0.9.27

**Comment by claywilkinson** [comment]
Thanks for the report.  This is a known issue that will be fixed in the next release.

**Comment by claywilkinson** [comment]
This is now fixed in version 5.1 of the GooglePlayGames C++ SDK, which is used by the latest plugin, 0.9.30.
