### ISSUE TITLE
Logger Issues

### ISSUE THREAD

**Issue by DanFlannel** [playgameservices/play-games-plugin-for-unity#874]
With the new Unity 5.3.1f update, any script containing Logger is an ambiguous reference between UnityEngine.Logger and GooglePlayGames.OurUtils.Logger This needs to be updated to OurUtils.Logger or UnityEngine.Logger.

**Comment by claywilkinson** [comment]
Thanks. The latest version of the plugin  (0.9.27a) fixes this by fully qualifying the references to OurUtils.Logger.
