### ISSUE TITLE
Invoking any class / method from this plugin causes app to crash on Samsung devices

### ISSUE THREAD

**Issue by BryanQu** [playgameservices/play-games-plugin-for-unity#877]
The plugin works fine on non-Samsung devices, but on any Samsung device, invoking anything from this plugin (even just authentication) causes the app to crash within a few seconds. The calls often work - it authenticates, for instance - but then the app crashes to the homescreen. If I comment out the items relating to Google Play Games integration (I am only using authentication, leaderboards, and achievements, all in their default configuration), the app works as expected on those devices.

Is there some device specific implementation I am missing, or a known issue with Google Play Games on Samsung devices?

**Comment by claywilkinson** [comment]
Can you share a log of the crash?  That will help answer you specific question.

**Comment by claywilkinson** [comment]
Closing since there is nothing to work with. Please reopen when you post a log of the problem.
