### ISSUE TITLE
Xcode build fails in 0.95a when disabling with NO_GPGS

### ISSUE THREAD

**Issue by fmandujano** [playgameservices/play-games-plugin-for-unity#878]
Hi. I want to completely disable GPGS when compiling for IOS, but the files Libraries/plugins/GPGSAppController.h and GPGSAppController.mm keep appearing when building in Unity. If I delete the contents of GPGSAppController.mm (but not the file) it succesfully builds. 

I didn't configure the GPGS for IOS and the first time I build I forgot to put NO_GPGS, maybe that's the problem?

**Comment by claywilkinson** [comment]
The older plugins did not always delete the files, but rather made them empty.  To be complete, you can make them empty both in Xcode and in Unity (Assets/Plugins/Ios/GPGSAppController.mm)
