### ISSUE TITLE
Crash on GooglePlayGames.Activate

### ISSUE THREAD

**Issue by pranavt007** [playgameservices/play-games-plugin-for-unity#879]
I am trying to implement Google play services in my game but it keeps crashing whenever i add GooglePlayGames.Activate(). I also have Soomla, Google Analytics and some other plugins in my game. I don't know whats causing the problem

**Comment by claywilkinson** [comment]
Can you share the log of the crash?

**Comment by pranavt007** [comment]
When I exported The project from unity to Eclipse. It gave the following error in eclipse 
Description	Resource	Path	Location	Type
error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').	AndroidManifest.xml	/UnityPlayerActivity	line 29	Android AAPT Problem

**Comment by pranavt007** [comment]
It got fixed when I reimported the package

**Comment by claywilkinson** [comment]
Great! I am glad you got it resolved.
