### ISSUE TITLE
GetToken return null

### ISSUE THREAD

**Issue by ramstore** [playgameservices/play-games-plugin-for-unity#880]
Hello,
After authenticate, GooglePlayGames.PlayGamesPlatform.Instance.GetToken(); return null in version 0.9.27, patch A. in prev version version 0.9.26 token return correct but on AndroinM(6.0) have error with get account permissions.

Unity 5.2.2f1

**Comment by claywilkinson** [comment]
You definitely need to update to 0.9.27 or greater to get the permission handling for M.  Make sure you the directory Assets/Plugin/Android/MainLibProj is updated.  If it is still not working, can you share a log?

**Comment by ramstore** [comment]
Thanks for replay,
I use last plugin, i atach log file. "token =" after it must be token but it's empty. Use minimal example. In previous version of plugin 0.9.26 works good.
log.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/72116/log.txt)

**Comment by ramstore** [comment]
i make some test and found that token not working when AuthSucceed invoke, but when i make separate button and press when I already auth it works....

**Comment by claywilkinson** [comment]
Thanks for the update. It could be also similar to #865 where the token is filled in asynchronously.
