### ISSUE TITLE
Unity 5.3 Compile Error.

### ISSUE THREAD

**Issue by edgarscr** [playgameservices/play-games-plugin-for-unity#882]
Guys please i need help on this. i installed all files Tools, Extras, Api 5 and 6 and error keep showing

![image](https://cloud.githubusercontent.com/assets/16306453/11978154/72224652-a95b-11e5-8ccf-8de6e5012bb3.png)
![image](https://cloud.githubusercontent.com/assets/16306453/11978163/7b7bdce0-a95b-11e5-856f-e142d75aa97a.png)
![image](https://cloud.githubusercontent.com/assets/16306453/11978165/7e4f3dd6-a95b-11e5-964d-30df6075b7f7.png)

**Comment by claywilkinson** [comment]
There looks like a duplicate set of resources in your project.  Usually they are copied over from using other plugins.  Take a look to find the duplicates and delete one of them from your project.

**Comment by edgarscr** [comment]
i have the Google Play Services and Google For Admob. i deleted plugins and folders and  added again latest version. and i got this error.

**Comment by Vatsal-Bajpai** [comment]
@edgarscr I am getting the same error since last week. Have to remove GPG services to make the game. The problem i found was that Admob was using .jar library of GPS where GPG service was converting it into .aar files after importing it. Let's hope there is a solution soon.

**Comment by edgarscr** [comment]
How i convert this?

**Comment by DarkBioloG** [comment]
I am gettin this trouble in last week. Wait fix...

**Comment by LARP** [comment]
You needed to remove some of Plugin/Android/GoogleMobileAdsPlugin/AndroidManifest.xml (as it cause merging conflict)
"<activity android:name="com.google.android.gms.ads.AdActivity" ... />
<activity android:name="com.google.android.gms.ads.purchase.InAppPurchaseActivity".../>"

Source: https://github.com/playgameservices/play-games-plugin-for-unity/issues/814

**Comment by edgarscr** [comment]
This error is by Admob. i go to close and open on Admob githup.

https://github.com/googleads/googleads-mobile-unity/issues/150

**Comment by claywilkinson** [comment]
Thanks @edgarscr - stay tuned for an update of both plugins.
