### ISSUE TITLE
Int shared by 2 players in the same room?

### ISSUE THREAD

**Issue by loftyy** [playgameservices/play-games-plugin-for-unity#886]
-does anyone know an integer that 2 players in the same room share? I really need one in order to have the same Random.seed and generate the same random level for 2 players.

I have a dilemma,  I have a method which generates a random level out of a prefab. I called this function under onRoomConnected(); the issue is that this generates random levels (which is good) but both players have 2 different random levels (which is not good). Does anyone know a way to generate the same random level for 2 players over real time multiplayer ?

Thank you!

**Comment by ArmandCloud** [comment]
I am not an expert but you can use same seed for random number generator of unity.
Here is the documentation link...

http://docs.unity3d.com/ScriptReference/Random-seed.html

I hope it helps. And I think its not a google play games plugin issue, its a game engine question. You can get faster answers on unity forums for this type of question.

Regards,

**Comment by loftyy** [comment]
@ArmandCloud thanks Armand, I have read the documentation. Now I understand why when I connected both players at the same time, they have similar level patterns which is because the seed for each random operation is based on the clock. I will try this and get back to you!

**Comment by sorab2142** [comment]
You could have the player at participant[0] in GetParticipants() generate it, and send it over to the other player using SendMessage and then start the game.

**Comment by claywilkinson** [comment]
There is no such service in the Google Play Game Services to generate a shared random number.  There a couple strategies, the one @sorab2142 suggests is probably the easiest.
