### ISSUE TITLE
RealTimeMultiplayer sync with other players?

### ISSUE THREAD

**Issue by 12boulla** [playgameservices/play-games-plugin-for-unity#887]
Okay, so I am a bit of a noob when it comes to the GPGS for Unity.

I have set up realtimemultiplayer so you can open the waiting room GUI, but that is it. What I want to happen when other players join is it to load another scene and then have all the other players display characters aswell.

My game has simple touch controls, just tap and you go up (like flappy bird). How do i make it so I can see the other players go up and down in real time. Also, I have objects that are randomly instantiaded. How do I make them instantiate in the same place for every player?

As I said, I am a bit of a noob at this. Any help is greatly appreciated, thanks.

**Comment by claywilkinson** [comment]
Welcome to the wild world of multiplayer games :)

A good starting point is http://www.raywenderlich.com/86040/creating-cross-platform-multiplayer-game-unity-part-1

**Comment by tpitman** [comment]
You wouldn't happen to have an equally good tutorial for a turn based game
would you?

**Comment by claywilkinson** [comment]
Unfortunately, I don't think there is an equally good tutorial for turn based.  There is a pretty good video describing TBMP - https://www.youtube.com/watch?v=rbYweTLvD-s
