### ISSUE TITLE
[Android] Play Games plugin colliding with Google Cast Remote Display Plugin

### ISSUE THREAD

**Issue by exiin** [playgameservices/play-games-plugin-for-unity#888]
I'm trying to install the Cast remote display on Android (https://www.assetstore.unity3d.com/en/content/50168), but after installing everything in my own project, it appears that the Play Games plugin mess the things up. Some part of the SDK are already integrated, but it looks like it's not correctly integrated (game crash when the Cast remote is called)

Google Cast Remote Display needs :
*appcompat-v7
*support-v4
*mediarouter
*google-play-services_lib

And Google Play Games plugin integrate already:
*appcompat-v7
*support-v4
*google-play-services_lib

the error that I have in the logcat:
java.lang.NoClassDefFoundError: Failed resolution of: com/google/android/gms/cast/CastMediaControlIntent;

**Comment by claywilkinson** [comment]
Which version of unity and the plugins are you using?  If you are using the recent GPGS plugin with Unity 5+, then you can fix this issue by copying the cast .aar file from $ANDROID_HOME//extras/google/m2repository/com/google/android/gms/play-services-cast/8.1.0/

**Comment by claywilkinson** [comment]
OK to close this?
