### ISSUE TITLE
Login Don't show up after authenticate call Unity Android

### ISSUE THREAD

**Issue by alihc** [playgameservices/play-games-plugin-for-unity#889]
Hi, I am working on update of my game which was working fine 4 months back but now i was facing problem in making build which is resolved with updating SDK and now my login for google play games isn't working. 
I am using Unity 5.2.1, SDK latest with Android studio, google play services Rev 29
I pasted logs here on Paste bin : http://pastebin.com/Dk3rsc1s
[Logs_GooglePlayGame.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/74090/Logs_GooglePlayGame.txt)

**Comment by claywilkinson** [comment]
It looks like something is not right in the Activate/Authenticate call logic.  Can you compare/examine the authentication code in the Minimal or Smoketest sample?

**Comment by claywilkinson** [comment]
OK to close?
