### ISSUE TITLE
iOS Error Building

### ISSUE THREAD

**Issue by beardboy** [playgameservices/play-games-plugin-for-unity#89]
This is my first attempt at using Unity to build to iOS so any help would be appreciated. When opening the Xcode project and attempting to build I get the following errors with the below files.

Files: GPGSRealTimeRoomDelegate.m
Code: @implmentation GPGSRealTimeRoomDelegate
Error: @synthesize of 'weak' property is only allowed in ARC or GC mode

File: GPGSTurnBasedMatchDelegate.m
Code: @implmentation GPGSTurnBasedMatchDelegate
Error: @synthesize of 'weak' property is only allowed in ARC or GC mode

My game is not using Turn-based or Real-time multiplayer.

play-games-plugin-for-unity 0.9.00
Google+ iOS SDK 1.5.1
Google Play Games iOS SDK 2.0
Unity free 4.3.4f1
Xcode 5.1
OS X 10.8.5
iOS 7.1

Thanks,
Thaddeus

**Comment by Gebni** [comment]
Hi, 

I have done all the stuff you mentioned. I have removed all errors but i am getting these now. 

![screen shot 2016-03-23 at 12 38 08 pm](https://cloud.githubusercontent.com/assets/17553533/13978608/4c7624ba-f0f4-11e5-88d8-86ba363b4139.png)

Any idea?

Using Unity 5.2.2 and xcode 7.3

**Comment by claywilkinson** [comment]
@Gebni  - this thread is pretty old and your error does not seem to be that related  to this plugin.  I'd suggest posting questions like this on the [Unity site](http://answers.unity3d.com/).
