### ISSUE TITLE
Admob Banner ads shown behind (with opacity) 

### ISSUE THREAD

**Issue by fadsel** [playgameservices/play-games-plugin-for-unity#891]
When you fire up ShowAchievementsUI() or the like , it gets on top of the admob banner ads which makes the ads showing at the back i.e since the background of playgames has some opacity .

Well , ... you only get impressions , the ads are not clickable while you are navigating untill you close the the achievement UI/leaderboard UI

![bug](https://cloud.githubusercontent.com/assets/4649112/12056569/d669f540-af48-11e5-89a2-f0811e87b70b.png)

Maybe I should also post this issue on admob too?

I am using this version 0.9.27

Is there a way to make it below admob?

**Comment by claywilkinson** [comment]
Yes, please post to the admob forum as well.

**Comment by fadsel** [comment]
You can see the bug in the actual game Sticky Bubble ( v2.0.6 )

https://play.google.com/store/apps/details?id=com.fadsel.stickybubble

**Comment by claywilkinson** [comment]
Closing this one - answered in https://github.com/googleads/googleads-mobile-unity/issues/151
