### ISSUE TITLE
Authentication crashes

### ISSUE THREAD

**Issue by squigglyo** [playgameservices/play-games-plugin-for-unity#892]
This plugin is no longer working for me at all.

I call PlayGamesPlatform.Activate followed by the 
Social.localUser.Authenticate((bool success) => {

This results in my app crashing everytime. The ADB log doesnt shed any light on the situation, using older versions of the plugin dont result in the crash.

Even an empty scene with the bare minimum crashes when trying to authenticate.

More info on my Unity Forum post
http://forum.unity3d.com/threads/google-play-games-plugin-not-working-properly.376686/#post-2442446

**Comment by claywilkinson** [comment]
Can you post the log of the crash?  Did you try to run Window > Google Play Games > Setup after updating the plugin?

**Comment by squigglyo** [comment]
Yes, I updated it in Unity, have also removed it and reinstalled it, still the same.

What/where is the crash log found? Ive got an ADB log but im not sure where a crash log would be if its a different thing.

**Comment by semeno** [comment]
run Window > Google Play Games > Setup solved my issue on Social.localUser.Authenticate((bool success)...
Thanks!
