### ISSUE TITLE
google_play_services_version not defined

### ISSUE THREAD

**Issue by DougLazyAngus** [playgameservices/play-games-plugin-for-unity#893]
For very explicit details of how I got here, see http://googleplayfail.blogspot.com/2016/01/getting-google-play-working.html

When I try to run the exported Google Android Project in Android Studio, I get the following error message:

Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

The blog above also details all the failed things I tried to solve this.

What seemed to work is manually copying the version.xml file from the sdk's google-play-services_lib directly into my generated Android Studio Project.

So I can get past the problem, but with the solution I have, every single time I have to re-export from Unity or re-generate the Android Studio project from what Unity exports, I will have to copy this file over again.

Is there something I can do so that this file just automatically will show up in the right place when I export from Unity?

**Comment by banditdevelopment** [comment]
I've gotten this error recently too. Not sure why it happened, everything worked before.

Getting the error in Unity by the way.

**Comment by claywilkinson** [comment]
The easiest thing to do for the exported project is to remove the Unity added play-services  libraries, and then add them in the build.gradle file
```
dependencies {
    compile files(project(':mainLibProj').buildDir.absolutePath + "/libs/mainLibProj.jar")
    compile 'com.google.android.gms:play-services-games:8.4.0'
    compile 'com.google.android.gms:play-services-nearby:8.4.0'
    compile 'com.google.android.gms:play-services-drive:8.4.0'
    compile files('libs/unity-classes.jar')
}
```

**Comment by claywilkinson** [comment]
OK to Close?

**Comment by DougLazyAngus** [comment]
I've had to move on, I don't have bandwidth for this project any more.  Do
whatever you need to do.


On Wed, Jan 27, 2016 at 12:31 PM, Clayton Wilkinson <
notifications@github.com> wrote:

> OK to Close?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/play-games-plugin-for-unity/issues/893#issuecomment-175841152>
> .
>



-- 
Doug Banks
(650) 346 2107
