### ISSUE TITLE
Can't build Unity project after adding google play games!

### ISSUE THREAD

**Issue by DroidifyDevs** [playgameservices/play-games-plugin-for-unity#895]
So after adding google play games I can't build my unity project. During the build, it will stop and say "Can't repackage resources. See console for details". I've spent over 4 hours on this and it is quite frustrating! :(

In console, it says this: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.1\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Program Files (x86)/Android/android-sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.google.unity:com.google.example.games.mainlibproj:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.plus:android.support.v4 -S "C:\Users\Me2\Music\ROCKET TEST\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res" -S "C:\Users\Me2\Music\ROCKET TEST\Temp\StagingArea\android-libraries\play-services-base-8.4.0\res" -S "C:\Users\Me2\Music\ROCKET TEST\Temp\StagingArea\android-libraries\play-services-basement-8.4.0\res" -S "C:\Users\Me2\Music\ROCKET TEST\Temp\StagingArea\android-libraries\play-services-drive-8.4.0\res" -S "C:\Users\Me2\Music\ROCKET TEST\Temp\StagingArea\android-libraries\play-services-games-8.4.0\res" -S "C:\Users\Me2\Music\ROCKET TEST\Temp\StagingArea\android-libraries\play-services-nearby-8.4.0\res" -S "C:\Users\Me2\Music\ROCKET TEST\Temp\StagingArea\android-libraries\play-services-plus-8.4.0\res" -S "C:\Users\Me2\Music\ROCKET TEST\Temp\StagingArea\android-libraries\support-v4-23.1.1\res"

stderr[
AndroidManifest.xml:17: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.IAPTheme').

]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: C:\Program Files (x86)\Android\android-sdk\platforms\android-23\android.jar
applyFileOverlay for drawable

There are more errors, if you want I can upload them too.

Can anyone PLEASE help to get this working? THANK YOU

**Comment by claywilkinson** [comment]
Which version of Unity? It looks like the AndroidManifest.xml has a theme referenced which is not defined.   Can you look in the AndroidManifest.xml and see which activity it is?

**Comment by Melesar** [comment]
A have almost the same issue on the Unity v5.3.0f4

stderr[
D:\BeraRun\Unity Projects\matchthreegame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.0\res\values-v23\values-v23.xml:5: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

D:\BeraRun\Unity Projects\matchthreegame\Temp\StagingArea\android-libraries\appcompat-v7-23.1.0\res\values-v23\values-v23.xml:24: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

]

Would be grateful for your help

**Comment by Delanir** [comment]
Hello,
I'm experiencing exactly the same the same issue as @Melesar .
My unity version is 5.3.1p1 .

**Comment by DroidifyDevs** [comment]
I'm using unity 5.2.3f1

thanks for the help!!

**Comment by OwlGames** [comment]
im having the same problem here. Im trying others versions.
Version 0.9.21 works. 
Im trying to use the new version too.

**Comment by claywilkinson** [comment]
The style `android:Widget.Material.Button.Colored` is defined in the android-23 SDK.  Can you download that version in the SDK manager and re-run the plugin setup?

**Comment by TofuStudios** [comment]
For me i had a similar problem with the google play services and adMob. So looking in your Unity Project under Assets->Plugin->Android all i could see was the "GoogleMobileAdsPlugin". Therefore i manually found the "google-play-services_lib" folder and DRAGGED and DROOPED that folder into my Unity Project Assets-->Plugin-->Android where the "GoogleMobileAdsPlugin" was located. 
![image 1](https://cloud.githubusercontent.com/assets/16774412/12415131/bfc29336-befe-11e5-9163-f413791d0a6b.JPG)

For me the folder was located: 
C:\Program Files (x86)\Android\android-sdk\extras\google\google_play_services\libproject
If you don't have that folder, download it from SDK manager at the bottom and install *(Google Play Services)
![image 2](https://cloud.githubusercontent.com/assets/16774412/12415169/ef213010-befe-11e5-9811-5cd5666a8d23.JPG)
![image 3](https://cloud.githubusercontent.com/assets/16774412/12415172/f4791e06-befe-11e5-824c-0381973945ad.JPG)

Then in the "GoogleMobileAdsPlugin" you make a folder "res" and click into it. Then in that "res" folder you make another folder called "values".
![image 4](https://cloud.githubusercontent.com/assets/16774412/12415212/46d93a50-beff-11e5-8686-1d92bc8dce8b.JPG)
![image 5](https://cloud.githubusercontent.com/assets/16774412/12415217/4cd573c4-beff-11e5-9581-942ea3ba4253.JPG)

Once that is done, go back into the  "google-play-services_lib" folder on your hard disk, there should also be a folder named "res" which you click into it and a folder called "values". Now in the "values" folder you copy the "version.xml" file which is highlighted in the image below.
![image 7](https://cloud.githubusercontent.com/assets/16774412/12415305/e63ac744-beff-11e5-893f-12457509aa65.JPG)

Copy that file into your created "values" folder in the **GoogleMobileAdsPlugin**
![image 6](https://cloud.githubusercontent.com/assets/16774412/12415337/15a5a3be-bf00-11e5-9d47-58e9a0b0882f.JPG)

That then got rid of the errors i see from your one. Try that out and see if it works? Let me know how it goes?

**Comment by TofuStudios** [comment]
Also nearly forgot. I also deleted the In app purchase activity in the AndroidManifest of the "GoogleMobileAdsPlugin" folder since Im not using. 
![image 8](https://cloud.githubusercontent.com/assets/16774412/12415605/6157c318-bf01-11e5-8a3e-757a4f97da5e.JPG)

**Comment by saurabh143saket** [comment]
@TofuStudios Hi! Thanks man it worked. It didn't work till I removed the InAppPurchase Activity. :+1:

**Comment by claywilkinson** [comment]
OK to close this one?

**Comment by OwlGames** [comment]
Yes off course. Sorry its solved.

**Comment by claywilkinson** [comment]
Great! thanks.

**Comment by misaghDroid** [comment]
I'm using unity 5.3.5 and my android sdk has been updated to latest version.
I cant find the path you mentioned for google_play_service_lib in sdk folder. My problem have not solved yet.
