### ISSUE TITLE
[Android]  All social work fine except "Leaderboard" system , its showin Empty!

### ISSUE THREAD

**Issue by natysoz** [playgameservices/play-games-plugin-for-unity#896]
hii , 

working on my game , all the social work perfect , the leaderboard also showing up...

i just got problem , it is showing up Empty all time , even when i post scores ....

	public void PostScoreToLeaderboard()

	{
		if (Social.localUser.authenticated) {
		Social.ReportScore(12345,leaderboard, (bool success) => {
			
			if (success) {
  				Debug.Log("Best Score Posted AS " + BestScoreToPost);
				((PlayGamesPlatform) Social.Active).ShowLeaderboardUI(leaderboard);
			}

			else
			{
					LoginGoogle();}});
		}

	}

When i try to submit scores , its take 1 sec , then the Leaderboard window open , but show empty.

no idea why... :(

i created the leaderboard 14 days ago.

i did update plugin , and i also update adb services .

the Setup is ok i copy the currect Ids resources , and all other social things work perfectly .

this is the last thing im stuck before i can publish the game 

right now it is Beta with testers .

**Comment by claywilkinson** [comment]
Can you post a log of what is happening when posting the score?

**Comment by natysoz** [comment]
after posting the if state continue...

i get the "

    Debug.Log("Best Score Posted AS " + BestScoreToPost);
            ((PlayGamesPlatform) Social.Active).ShowLeaderboardUI(leaderboard);

working, The leaderboard is opened...and i see that messege :

http://postimg.org/image/584gjnckj/

**Comment by claywilkinson** [comment]
So it looks like it is posting the score successfully. Public leaderboards show only players that make their activity public in the settings for that game.

**Comment by natysoz** [comment]
but its dont show , rather "social" and not on "public" (All)

in my tester accounts i did make them to share all in settings
 
:/

**Comment by natysoz** [comment]
its should show myself at least but it donsnt

**Comment by claywilkinson** [comment]
And to confirm, this is on Android, right?

**Comment by natysoz** [comment]
yes , it is android , and its the only thing that does not working on my game :S cant publish it , so frustrated :/

**Comment by parlindqvist** [comment]
Just a quick guess here, but have you tried placing the ShowLeaderboardUI(leaderboard) in the main thread instead? I've had some problems myself doing stuff in the callback..

**Comment by AllanDouglas** [comment]
I have this same problem in this game https://play.google.com/store/apps/details?id=br.com.CactusStudios.Kollors. You fixe?

**Comment by mrThinBone** [comment]
Hi, I got same problem. Any updates?

**Comment by natysoz** [comment]
Yhea add me skyle i help u natysoz2
בתאריך 25 בפבר׳ 2016 9:23 לפנה״צ,‏ "mrThinBone" <notifications@github.com>
כתב:

**Comment by OddieBaSs** [comment]
Same problem here, I've tried everything! I'm so frustrated : (

**Comment by OddieBaSs** [comment]
Ok, the problem was this: 
Google Play Developer Console -> Linked Applications->"MyProjectName" -> OAuth2 Client ID wasn't the correct one. 

I`ve created a NEW linked Application with the same package name and I assured that the Oauth2 Client ID is the same that I have in my project on Google Credentials.

Now Leaderboards works perfect!

**Comment by claywilkinson** [comment]
Nice! Best of luck on your title!

**Comment by OddieBaSs** [comment]
Thank you Clay!
