### ISSUE TITLE
Retrieving player's email on iOS

### ISSUE THREAD

**Issue by AfifFaris** [playgameservices/play-games-plugin-for-unity#898]
Hi, I am trying to implement this plugin for my game, both android and ios version. There is no problem on android, but i can't get the player's email on ios version .

so i try to add log in GPGSAppController.mm

```
    const char* _GooglePlayGetUserEmail() {
        const char* email = nil;
        GIDGoogleUser* guser = [GIDSignIn sharedInstance].currentUser;
        
        if(guser) {
            email = __MakeStringCopy( [guser.profile email] );
        } else {
            NSLog(@"Current user is not set");
        }
        
       NSLog(@"TEST-User Email: %s", email);
        
        return email ? email : __MakeStringCopy(@"");
    }
```

the result is 
```
TEST-User Email: (null)
```

After I reading some documentation, I found that "email" need to be added to GIDSign scopes. 
I add more log here.
```
    void _GooglePlayEnableProfileScope() {
        GIDSignIn *signIn = [GIDSignIn sharedInstance];
        signIn.shouldFetchBasicProfile = YES;
        
         NSLog(@"TEST-Enable Profile Scope : %@", [GIDSignIn sharedInstance].scopes);
    }
``` 

and the result is 
```
TEST-Enable Profile Scope : (
)
```

even though
```
// Setting the flag will add "email" and "profile" to scopes.
// Defaults to |YES|.
@property(nonatomic, assign) BOOL shouldFetchBasicProfile;
```

I add more log

```
- (void)signInWillDispatch:(GIDSignIn *)signIn error:(NSError *)error {
    
    NSLog(@"signInWillDispatch: %@", error);
    NSLog(@"TEST-signInWillDispatch Scopes: %@", [GIDSignIn sharedInstance].scopes);
}

- (void)signIn:(GIDSignIn *)signIn presentViewController:(UIViewController *)viewController {
    
    NSLog(@"TEST-presentViewController Scopes: %@", [GIDSignIn sharedInstance].scopes);
    UnityPause(true);
    [[self rootViewController] presentViewController:viewController animated:YES completion:nil];
}

    const char* _GooglePlayGetUserEmail() {
        const char* email = nil;
        GIDGoogleUser* guser = [GIDSignIn sharedInstance].currentUser;
        
        if(guser) {
            email = __MakeStringCopy( [guser.profile email] );
        } else {
            NSLog(@"Current user is not set");
        }

        NSLog(@"TEST-Scope : %@", [GIDSignIn sharedInstance].scopes);
        NSLog(@"TEST-User Email: %s", email);
        
        return email ? email : __MakeStringCopy(@"");
    }
```
result
```
TEST-signInWillDispatch Scopes: (
    "https://www.googleapis.com/auth/games"
)

TEST-presentViewController Scopes: (
    "https://www.googleapis.com/auth/games"
)

TEST-Scope : (
    "https://www.googleapis.com/auth/games"
)
TEST-User Email: (null)
```
I don't know why the scope become /auth/games

I try to add profile and email scopes here
```
    void _GooglePlayEnableProfileScope() {
        GIDSignIn *signIn = [GIDSignIn sharedInstance];
        signIn.shouldFetchBasicProfile = YES;
        
         NSLog(@"TEST-Enable Profile Scope : %@", [GIDSignIn sharedInstance].scopes);
        
        [GIDSignIn sharedInstance].scopes = @[ @"profile", @"email" ];
        NSLog(@"TEST-Enable Profile Scope After Edit : %@", [GIDSignIn sharedInstance].scopes);
    }
```

I don't know why the scope is still /auth/games
```
TEST-Enable Profile Scope : (
)
TEST-Enable Profile Scope After Edit : (
    email,
    profile
)

TEST-signInWillDispatch Scopes: (
    "https://www.googleapis.com/auth/games"
)

TEST-presentViewController Scopes: (
    "https://www.googleapis.com/auth/games"
)

TEST-Scope : (
    "https://www.googleapis.com/auth/games"
)
TEST-User Email: (null)
```

after that I try to set the scopes here
```
- (void)signInWillDispatch:(GIDSignIn *)signIn error:(NSError *)error {
    
    NSLog(@"signInWillDispatch: %@", error);
    NSLog(@"TEST-signInWillDispatch Scopes: %@", [GIDSignIn sharedInstance].scopes);
    [GIDSignIn sharedInstance].scopes = @[ @"profile", @"email" ];
    NSLog(@"TEST-signInWillDispatch Scopes After Edit: %@", [GIDSignIn sharedInstance].scopes);
}
```

this time the scope is correct
```
TEST-Enable Profile Scope : (
)
TEST-Enable Profile Scope After Edit : (
    email,
    profile
)

TEST-signInWillDispatch Scopes: (
    "https://www.googleapis.com/auth/games"
)
TEST-signInWillDispatch Scopes After Edit: (
    email,
    profile
)

TEST-presentViewController Scopes: (
    email,
    profile
)
```

After sign in, the user email still null and my game freeze. I check the token info using this url
https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=ya29.xxxxx

result ( I censored client id and user id)
```
{
 "issued_to": "xxxxx.apps.googleusercontent.com",
 "audience": "xxxxx.apps.googleusercontent.com",
 "user_id": "123456",
 "scope": "https://www.googleapis.com/auth/games https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.moments.write https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/plus.profile.agerange.read https://www.googleapis.com/auth/plus.profile.language.read https://www.googleapis.com/auth/plus.circles.members.read",
 "expires_in": 3571,
 "access_type": "offline"
}
```
The scopes are totally different..... I have no idea.

----------------------------------------------------------------------------------

I expect to see this 
<img width="494" alt="screen shot 2016-01-07 at 11 51 58 am" src="https://cloud.githubusercontent.com/assets/8552823/12163364/5b434e6c-b550-11e5-8188-72ab04324a0d.png">

but I always got this 
<img width="480" alt="screen shot 2016-01-07 at 11 52 24 am" src="https://cloud.githubusercontent.com/assets/8552823/12163374/6710d41c-b550-11e5-9371-0ac477f8c7d4.png">

This is so frustrating, I don't know what to do anymore. Is there anyone who knows how to solve this problem?

----------------------------------------------------------------------------------

P.S.
There is one time i got asked permissions like this
<img width="472" alt="screen shot 2016-01-07 at 3 12 32 pm" src="https://cloud.githubusercontent.com/assets/8552823/12163461/29925cea-b551-11e5-8b87-04c7d02ed31c.png">
I can get the user email. after that, I sign out and restart the game just to make sure I can still get the user email, but I didn't get asked for "View your email address" permission and I can't get the user email again. Help..... if this problem can't be solved, I plan to become a potato farmer.

**Comment by claywilkinson** [comment]
This is a known bug in the iOS native SDK.  It should be fixed in the next release of the SDK (which is coming soon - definitely before potato planting season)

**Comment by AfifFaris** [comment]
I see, if the next release of the SDK is not coming before my deadline I plan to use user id instead of user email and disable some feature until the SDK is updated. Just to make sure, user id is unique right?

Thank you for your quick reply.
(Haha... Well, at least I don't have to become potato farmer now)

**Comment by claywilkinson** [comment]
Definitely use Player.id  - it is the player's unique identifier and it is much less creepy to use since you don't need the player's permission to use it.

**Comment by claywilkinson** [comment]
The latest update of the plugin 0.9.30 uses GooglePlayGames 5.1 which fixes the email issue, but I think using Player.id would be preferable.
