### ISSUE TITLE
GooglePlus.h not found / PlayGameServices.h not found.

### ISSUE THREAD

**Issue by TheClarkster** [playgameservices/play-games-plugin-for-unity#9]
I've work hours on this now.  I think I've run out of ideas on how to fix this.  

```
GPGSAppController.m
Lexical or Preprocessor Issue
'GooglePlus/GooglePlus.h' file not found

GPGSAchOrLbDelegate.h
Lexical or Preprocessor Issue
'PlayGameServices/PlayGameServices.h' file not found
```

It looks to me like the Frameworks are not being seen.  But I can't find anything else to do, I've tried it all.

Everything is set up correctly, for iOS in Unity.  I've built to an Xcode project, I've added every Framework listed in the documentation.

I dragged the 5 files to the project:
GoogleOpenSource.framework
GooglePlus.bundle
GooglePlus.framework
PlayGameServices.bundle
PlayGameServices.framework

I've double/triple/quadruple checked that they ARE included in Build Phases -> Link Binary With Libraries.

The .bundles are also in the project.

I've added the -ObjC flag to the Other Linker Flags.

Latest OS X Mavericks and Latest Xcode 5.0.2

I've wiped, re-uilt, re-created the xcode project, cleaned, built.  Done everything at least 5 times over.  Clean checkout from my repository and did it again.  Clean install of Unity. Simulator and device builds, with the correct choice in Unity beforehand.  Every possible thing I can think of.  But it just comes down to an error while compiling because it can't find the .h files.  Which has to mean the framework isn't linking. I've reached the end of my ideas.

Am I missing something really trivial and stupid?

Thank you for any help you can give me.  This works great on Android, I published a game with it two weeks ago, and am in the Top 10 New Apps and Games in Canada! I'd like to get it running on iOS now.

Thanks!

**Comment by chetanisinanand** [comment]
Simplest solution is to drag 'GooglePlus.framework' from 'unity-iPhone' project(Hopefully, you've already added it there) to 'BuildPhases > Link  Binary With Library' Section every time after Unity Build process.

**Comment by claywilkinson** [comment]
The latest version of the plugin (0.9.21) uses [Cocoapods](https://cocoapods.org/) to manage the dependencies.  If you install cocoapods, then all the dependent frameworks are added to the xcode workspace automatically.   The README file has all the details.
