### ISSUE TITLE
Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.

### ISSUE THREAD

**Issue by OwlGames** [playgameservices/play-games-plugin-for-unity#900]
Help me please! 
I'm two days trying to resolve this problem. Nothing work :( 

Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Program Files\Android\android-sdk\build-tools\23.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Program Files/Android/android-sdk\platforms\android-22\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.google.example.games.mainlibproj:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.plus:android.support.v4 -S

**Comment by claywilkinson** [comment]
Earlier in the console output it will list the error.  You have a duplicate resource or jar.  Once you delete one of the copies from your project it will build.  Can you share your Unity version, and the contents of Assets/Plugins/Android?

**Comment by OwlGames** [comment]
Thanks for the feedback.
The version of My Unity is 5.1.3f ( 64x )

I'm trying to find a possible duplicity as you suggested . Interestingly, even I open a new project and importing the plugin and example " minimal" , the error occurs .

I noticed that within the plugin / android folder was not created RES folder to configure the plugin with my ID .

**Comment by Delanir** [comment]
I'm experiencing the same issues as @OwlGames and so far I was unable to find duplicates.

My project tree matches the image. I've tried to downgrade the plug-in to version 0.9.21, but I'm afraid that version isn't compatible with  Unity 5.3.1p1 (for example the Logger class from OurGameUtils is considered to be ambiguous). 

While comparing the Manifest files under MainLibProj from versions 0.9.21 and 0.9.27 I noticed the APP_ID field is not set in version 0.9.27. 

```xml
<application>

     <!-- Required for Nearby Connections API -->
        <meta-data android:name="com.google.android.gms.nearby.connection.SERVICE_ID"
            android:value="" />

        <!-- the space in these forces it to be interpreted as a string vs. int -->
        <meta-data android:name="com.google.android.gms.games.APP_ID"
            android:value="\ " />
        <meta-data android:name="com.google.android.gms.appstate.APP_ID"
            android:value="\ " />
        <meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

        <activity android:name="com.google.games.bridge.NativeBridgeActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
    </application>
```
Is this manifest excerpt correct?

**Comment by claywilkinson** [comment]
The App_ID property is specific to your project.  It is set when you run setup for the plugin from Window > Google Play Games > Setup > Android Setup...

The latest version of the plugin has changed to using a fully qualified name for Logger, so there are no conflicts with Unity's.

**Comment by claywilkinson** [comment]
@OwlGames  - can you look in the log messages and see what the error is? Specifically what is the duplicate or missing resource?

**Comment by OwlGames** [comment]
Yesnoff course. Is a missing resourse.
Im not im my computer now, i send this for you in about 3 hours.

**Comment by OwlGames** [comment]
Hi claywilkinson,
the resource missing is :
'android:TextAppearance.Material.Widget.Button.Inverse'
'android:Widget.Material.Button.Colored'.

...
stderr[
C:\Users\Public\Documents\OWLGAMES\New Unity Project\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\values-v23\values-v23.xml:5: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
C:\Users\Public\Documents\OWLGAMES\New Unity Project\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\values-v23\values-v23.xml:30: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
]
stdout[
Configurations:
 (default)
Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml
Resource Dirs:
Including resources from package: C:\Program Files (x86)\Android\android-sdk\platforms\android-22\android.jar
applyFileOverlay for drawable
...

**Comment by claywilkinson** [comment]
The newer versions of the plugin remove the google-play-services_lib since most of it is not used in a game, and it bloats the apk by about 50% for a small game.

The styles in question are defined in the android-23 SDK - can you update the SDK via sdk manager and re-run setup for the plugin?

**Comment by Delanir** [comment]
Thank you so much @claywilkinson , downloading android-23 SDK Platform fixed this issue.

**Comment by OwlGames** [comment]
Hi @claywilkinson, thx again, my build version is 23.1  :/

![image](https://cloud.githubusercontent.com/assets/16594438/12249034/761dea88-b8a4-11e5-88d4-cbed7be1fd67.png)

**Comment by claywilkinson** [comment]
Those are the build tools.  What about the platform SDK?
![screen shot 2016-01-11 at 2 52 00 pm](https://cloud.githubusercontent.com/assets/8752378/12249186/f1984db6-b872-11e5-8004-c63bf4476247.png)

**Comment by OwlGames** [comment]
Oooops, Sorry! I use API 22.   :S
Im downloading API 23 now thx so much @claywilkinson .

**Comment by claywilkinson** [comment]
Great! :+1:  Please re-open this if that did not work for you.

**Comment by zodlanier** [comment]
Hi @claywilkinson, i am having the same trouble but my API is already 23. The error log is as shown below:

> Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
/Users/admin/Downloads/android-sdk-macosx/build-tools/23.0.2/aapt package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "/Users/admin/Downloads/android-sdk-macosx/platforms/android-23/android.jar" -F bin/resources.ap_ --extra-packages com.google.unity:com.google.example.games.mainlibproj:android.support.v7.appcompat:com.amazon.ags:com.google.android.gms:com.google.android.gms.ads:com.google.android.gms:android.support.v4 -S

Do you have any suggestions for what should i do? Thank you!

**Comment by hanhnd76** [comment]
@zodlanier Did you resolve the trouble? I am getting the same

**Comment by TinyTitanAli** [comment]
Same issue here. Anyone?

**Comment by blookmaker** [comment]
Same issue here too . have somebody been able to fix the issue ?

**Comment by JasonWCook** [comment]
I used to be able to build APK's just fine then my Windows died and went into a Repair loop. Once I reinstalled Windows 8, and unity along with both of the required installations (Android SDK, JDK) I could no longer build an APK without receiving this issue. I've followed the Unity - Android set up instructions exactly and even reinstalled everything twice. I just want to finish my project!

**Comment by blookmaker** [comment]
hi @JasonWCook  
it seems that you have downloaded the api 24 in your android-sdk ,
i believe that the solution for you is to delete the 24 folder under the android-sdk-windows\build-tools in your android sdk location .

**Comment by JasonWCook** [comment]
HEY @blookmaker Thank you so much! It builds!

**Comment by MirkoFabris** [comment]
YES! Remove everything with 24 and it works. Thanks!

**Comment by adamcarmichael** [comment]
Hey @blookmaker, having a similar issue and it's driving me insane! Here is my log:

CommandInvokationFailure: Failed to re-package resources. See the Console for details.
/Users/adamcarmichael/Library/Android/sdk/build-tools/23.0.1/aapt package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "/Users/adamcarmichael/Library/Android/sdk/platforms/android-23/android.jar" -F bin/resources.ap_ --extra-packages com.google.unity:com.heyzap:android.support.v7.appcompat:com.google.android.gms:com.google.android.gms.ads.impl:com.google.android.gms.ads:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.clearcut:com.google.android.gms:com.google.android.gms.tasks:android.support.v4 -S "/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/GoogleMobileAdsPlugin/res" -S "/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res" -S "/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/google-play-services_lib/res" -S "/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/play-services-ads-9.2.0/res" -S "/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/play-services-ads-lite-9.2.0/res" -S "/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/play-services-base-9.2.0/res" -S "/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/play-services-basement-9.2.0/res" -S "/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/play-services-clearcut-9.2.0/res" -S "/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/play-services-gass-9.2.0/res" -S "/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/play-services-tasks-9.2.0/res" -S "/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/support-v4-23.1.1/res"

stderr[
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <android.support.v7.widget.ButtonBarLayout>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_alert_dialog_button_bar_material.xml: note: using v17 attributes; synthesizing resource com.microwave.vex:layout/abc_alert_dialog_button_bar_material for configuration v17.
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.widget.DialogTitle>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource com.microwave.vex:layout/abc_alert_dialog_material for configuration v17.
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_dialog_title_material.xml: note: using v17 attributes; synthesizing resource com.microwave.vex:layout/abc_dialog_title_material for configuration v17.
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.widget.ActionBarContainer>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource com.microwave.vex:layout/abc_screen_toolbar for configuration v21.
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_search_view.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/abc_search_view.xml: note: using v17 attributes; synthesizing resource com.microwave.vex:layout/abc_search_view for configuration v17.
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media.xml: note: using v17 attributes; synthesizing resource com.microwave.vex:layout/notification_template_big_media for configuration v17.
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource com.microwave.vex:layout/notification_template_big_media_narrow for configuration v17.
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_lines.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_lines.xml:77: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_lines.xml:96: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_lines.xml:64: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_lines.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_lines.xml: note: using v17 attributes; synthesizing resource com.microwave.vex:layout/notification_template_lines for configuration v17.
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_media.xml:43: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <include>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_media.xml:33: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_media.xml: note: using v17 attributes; synthesizing resource com.microwave.vex:layout/notification_template_media for configuration v17.
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_part_chronometer.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <Chronometer>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_part_chronometer.xml: note: using v17 attributes; synthesizing resource com.microwave.vex:layout/notification_template_part_chronometer for configuration v17.
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_part_time.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <DateTimeView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/notification_template_part_time.xml: note: using v17 attributes; synthesizing resource com.microwave.vex:layout/notification_template_part_time for configuration v17.
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:drawableStart from <CheckedTextView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_multichoice_material.xml: note: using v13 attributes; synthesizing resource com.microwave.vex:layout/select_dialog_multichoice_material for configuration v13.
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:drawableStart from <CheckedTextView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_singlechoice_material.xml: note: using v13 attributes; synthesizing resource com.microwave.vex:layout/select_dialog_singlechoice_material for configuration v13.
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_multichoice_material.xml: note: using v17 attributes; synthesizing resource com.microwave.vex:layout/select_dialog_multichoice_material for configuration v17.
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
/Users/adamcarmichael/Dropbox/Microwave Games/Games/Vex/Vex Mobile/2015/Vex/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/layout/select_dialog_singlechoice_material.xml: note: using v17 attributes; synthesizing resource

Any ideas? I'm using Unity 5.3.5p2. Thanks again!

**Comment by blookmaker** [comment]
I suppose that you have already tried to remove the 24 folder from the android sdk , if so , then be sure that you don't have duplicated libs in your project .
Was your project able to build before adding Google play services plug-in to your project ?

**Comment by adamcarmichael** [comment]
Yes I have deleted the 24, here is what my SDK Manager looks like and my folders. Would a duplicated lib be a folder containing the same files as another? Apologies this is my first project for Android. Also it did build successfully before I added the services.


<img width="699" alt="screen shot 2016-07-03 at 22 22 47" src="https://cloud.githubusercontent.com/assets/20270757/16547654/c85d6548-416c-11e6-8d5f-382352b2a851.png">
<img width="992" alt="screen shot 2016-07-03 at 22 23 34" src="https://cloud.githubusercontent.com/assets/20270757/16547655/c85f3e04-416c-11e6-9f72-faa60f93da08.png">
<img width="991" alt="screen shot 2016-07-03 at 22 23 41" src="https://cloud.githubusercontent.com/assets/20270757/16547656/c860d566-416c-11e6-9ff2-c64f7f35db81.png">

**Comment by blookmaker** [comment]
here how my Build tools folder looks like  . 
![capture](https://cloud.githubusercontent.com/assets/11816461/16556359/17cc081c-41c9-11e6-8825-3f5f5acd7008.PNG)

I don't know exactly what is the problem you are facing but here are  some tips you can start with to fix your issue .
create a new unity project and add the Google play game services to your project . then try to build it .
If it builds then your android sdk configuration have nothing to do with the issue .
i don't know if you have already tried this or not . 
if your project can't build with your current android sdk configuration . then the solution to your problem is to update your android sdk via android sdk manager .
Go to extras and update Google play services , and other items such as Google play services , android support repository and Google Repository . 
by your screenshot i guess that you need also to install the 23.0.3 Build tools directory . 
i am pretty sure that if your android sdk is still not up to date , then the problem is coming from their .
![capture2](https://cloud.githubusercontent.com/assets/11816461/16556624/989219b8-41ca-11e6-898a-bb3ca67c1a15.PNG)

**Comment by adamcarmichael** [comment]
On the new project the error appears so it must be my configuration. Could you possibly send me screenshots of everything package you have installed so I could compare it to my own?

**Comment by blookmaker** [comment]
yes sure .
![capture1](https://cloud.githubusercontent.com/assets/11816461/16559367/f6a46356-41db-11e6-874c-9b9016e99bde.PNG)
![capture2](https://cloud.githubusercontent.com/assets/11816461/16559373/fe7c15b0-41db-11e6-9ce9-e243a941b5a7.PNG)
![capture3](https://cloud.githubusercontent.com/assets/11816461/16559374/fe823e9a-41db-11e6-9603-d84ca5a57c07.PNG)
![capture4](https://cloud.githubusercontent.com/assets/11816461/16559375/fe84b378-41db-11e6-856e-23ebd306e651.PNG)
![capture5](https://cloud.githubusercontent.com/assets/11816461/16559376/fe8af71a-41db-11e6-8aae-9dc05416fb23.PNG)

ensure that the last ones in extra are up to date hope that this will solve your problem

**Comment by blookmaker** [comment]
Where you able to fix your issue @JasonWCook  ?

**Comment by TinyTitanAli** [comment]
I'm having the same issue... this is just disgusting.

http://pastebin.com/RS2UJ9eR

Usually I delete the support aar files but doesn't seem to work this time. 

Here's what's in my Android folder:

![screenshot](https://cloud.githubusercontent.com/assets/16493154/16663174/3f6a4d84-4449-11e6-92b2-538f186115d9.png)

Anyone?

**Comment by linhnguyenthaitung** [comment]
Hello every one. This issues was driving me crazy for the entire afternoon. Apparently you need to delete the **Android SDK Platform-Tools rev 24**, **Android SDK Build-tools rev 24** and build inside Unity. Unity then will prompt you that you need to update those stuffs, press OK and let Unity download those by itself >> **_problem sovled_**

**Comment by Badeye** [comment]
Anyone found a solution to this? For me none of the above given fixes worked....

**Comment by ramkeshcse084** [comment]
I think this is due to sdk and jdk version. So please download proper sdk and jdk. I have one tuorial. _It may help you.
https://youtu.be/w9AmjvGBnmw
