### ISSUE TITLE
GPGAchievement's showsCompletionNotification property missing in plugin?

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#902]
Needed if using Gamecenter achivements instead of gpg achivements on ios.

From https://developers.google.com/games/services/ios/achievements#hiding_notifications :

Hiding notifications

To hide the Achievement Unlocked notification entirely, set the GPGAchievement's showsCompletionNotification property to NO. Note that unlike the previous two code samples, this call will only affect individual achievement toasts.

```
  GPGAchievement *unlockMe = [GPGAchievement achievementWithId:achievementId];
  unlockMe.showsCompletionNotification = NO;
```

**Comment by claywilkinson** [comment]
Thanks for pointing this out.  Unfortunately, the plugin is based on the C++ API and not the iOS API, and this API is not in the C++ API.  I'll pass along the feed back to the product team.

**Comment by Hoffa25** [comment]
No problem:). This issue is not really a big deal. We can work around that with some code. The #901 issue is 100 times more important to fix. We have no solution to that:/

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated for iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
