### ISSUE TITLE
Error with GamesNativeSDK

### ISSUE THREAD

**Issue by DarkBioloG** [playgameservices/play-games-plugin-for-unity#903]
I compile game in Unity and have problem: in log there are more errors E/GamesNativeSDK﹕ Can't register class com/google/android/gms/...
I replace values.xml, problem still exists. Please help!

**Comment by claywilkinson** [comment]
Which classes care not registered?  That will help determine the remedy.  Which version of Unity are you using?

**Comment by DarkBioloG** [comment]
Unity 5.3.1f1 (64-bit)
01-03 14:23:43.654 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/common/ConnectionResult: an exception occurred.
01-03 14:23:43.654 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/common/GooglePlayServicesUtil: an exception occurred.
01-03 14:23:43.654 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/common/api/Api: an exception occurred.
01-03 14:23:43.655 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/common/api/Api$ApiOptions: an exception occurred.
01-03 14:23:43.656 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/common/api/Api$ApiOptions$HasOptions: an exception occurred.
01-03 14:23:43.657 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/common/api/GoogleApiClient: an exception occurred.
01-03 14:23:43.658 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/common/api/GoogleApiClient$Builder: an exception occurred.
01-03 14:23:43.659 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/common/api/PendingResult: an exception occurred.
01-03 14:23:43.660 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/common/api/Result: an exception occurred.
01-03 14:23:43.661 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/common/api/ResultCallback: an exception occurred.
01-03 14:23:43.661 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/common/api/Scope: an exception occurred.
01-03 14:23:43.661 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/common/api/Status: an exception occurred.
01-03 14:23:43.662 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/common/data/DataBufferUtils: an exception occurred.
01-03 14:23:43.662 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/Games: an exception occurred.
01-03 14:23:43.662 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/Games$GamesOptions: an exception occurred.
01-03 14:23:43.662 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/Games$GamesOptions$Builder: an exception occurred.
01-03 14:23:43.663 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/Player: an exception occurred.
01-03 14:23:43.663 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/PlayerBuffer: an exception occurred.
01-03 14:23:43.663 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/PlayerLevel: an exception occurred.
01-03 14:23:43.663 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/PlayerLevelInfo: an exception occurred.
01-03 14:23:43.664 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/Players: an exception occurred.
01-03 14:23:43.664 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/Players$LoadPlayersResult: an exception occurred.
01-03 14:23:43.664 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/achievement/Achievement: an exception occurred.
01-03 14:23:43.664 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/achievement/Achievements$LoadAchievementsResult: an exception occurred.
01-03 14:23:43.666 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/event/Event: an exception occurred.
01-03 14:23:43.667 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/event/EventBuffer: an exception occurred.
01-03 14:23:43.667 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/event/Events: an exception occurred.
01-03 14:23:43.668 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/event/Events$LoadEventsResult: an exception occurred.
01-03 14:23:43.669 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/achievement/AchievementBuffer: an exception occurred.
01-03 14:23:43.669 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/achievement/Achievements: an exception occurred.
01-03 14:23:43.670 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/leaderboard/Leaderboard: an exception occurred.
01-03 14:23:43.670 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/leaderboard/LeaderboardBuffer: an exception occurred.
01-03 14:23:43.671 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/leaderboard/Leaderboards: an exception occurred.
01-03 14:23:43.671 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/leaderboard/LeaderboardScore: an exception occurred.
01-03 14:23:43.672 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/leaderboard/LeaderboardScoreBuffer: an exception occurred.
01-03 14:23:43.672 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/leaderboard/LeaderboardVariant: an exception occurred.
01-03 14:23:43.673 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/leaderboard/Leaderboards$LeaderboardMetadataResult: an exception occurred.
01-03 14:23:43.673 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/leaderboard/Leaderboards$LoadScoresResult: an exception occurred.
01-03 14:23:43.674 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/Invitation: an exception occurred.
01-03 14:23:43.675 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/InvitationBuffer: an exception occurred.
01-03 14:23:43.675 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/Invitations: an exception occurred.
01-03 14:23:43.675 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/Invitations$LoadInvitationsResult: an exception occurred.
01-03 14:23:43.676 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/Multiplayer: an exception occurred.
01-03 14:23:43.676 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/Participant: an exception occurred.
01-03 14:23:43.676 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/ParticipantResult: an exception occurred.
01-03 14:23:43.677 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/turnbased/LoadMatchesResponse: an exception occurred.
01-03 14:23:43.678 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatch: an exception occurred.
01-03 14:23:43.678 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchBuffer: an exception occurred.
01-03 14:23:43.679 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchConfig: an exception occurred.
01-03 14:23:43.680 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatchConfig$Builder: an exception occurred.
01-03 14:23:43.681 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer: an exception occurred.
01-03 14:23:43.681 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$CancelMatchResult: an exception occurred.
01-03 14:23:43.681 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$InitiateMatchResult: an exception occurred.
01-03 14:23:43.682 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LeaveMatchResult: an exception occurred.
01-03 14:23:43.682 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LoadMatchesResult: an exception occurred.
01-03 14:23:43.682 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$LoadMatchResult: an exception occurred.
01-03 14:23:43.682 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/turnbased/TurnBasedMultiplayer$UpdateMatchResult: an exception occurred.
01-03 14:23:43.683 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/quest/Quest: an exception occurred.
01-03 14:23:43.683 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/quest/QuestBuffer: an exception occurred.
01-03 14:23:43.683 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/quest/Quests: an exception occurred.
01-03 14:23:43.683 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/quest/Milestone: an exception occurred.
01-03 14:23:43.684 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/quest/Quests$LoadQuestsResult: an exception occurred.
01-03 14:23:43.684 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/quest/Quests$AcceptQuestResult: an exception occurred.
01-03 14:23:43.684 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/quest/Quests$ClaimMilestoneResult: an exception occurred.
01-03 14:23:43.686 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/snapshot/Snapshot: an exception occurred.
01-03 14:23:43.689 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/snapshot/SnapshotContents: an exception occurred.
01-03 14:23:43.690 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadata: an exception occurred.
01-03 14:23:43.692 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataBuffer: an exception occurred.
01-03 14:23:43.692 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/snapshot/Snapshots: an exception occurred.
01-03 14:23:43.692 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/snapshot/Snapshots$CommitSnapshotResult: an exception occurred.
01-03 14:23:43.693 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/snapshot/Snapshots$LoadSnapshotsResult: an exception occurred.
01-03 14:23:43.693 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/snapshot/Snapshots$OpenSnapshotResult: an exception occurred.
01-03 14:23:43.693 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataChange: an exception occurred.
01-03 14:23:43.694 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/snapshot/SnapshotMetadataChange$Builder: an exception occurred.
01-03 14:23:43.694 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMessageReceivedListener: an exception occurred.
01-03 14:23:43.695 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMultiplayer: an exception occurred.
01-03 14:23:43.695 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/realtime/RealTimeMessage: an exception occurred.
01-03 14:23:43.695 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/realtime/Room: an exception occurred.
01-03 14:23:43.696 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/realtime/RoomConfig: an exception occurred.
01-03 14:23:43.696 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/games/multiplayer/realtime/RoomConfig$Builder: an exception occurred.
01-03 14:23:43.697 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/nearby/Nearby: an exception occurred.
01-03 14:23:43.697 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/nearby/connection/AppIdentifier: an exception occurred.
01-03 14:23:43.697 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/nearby/connection/AppMetadata: an exception occurred.
01-03 14:23:43.698 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/nearby/connection/Connections: an exception occurred.
01-03 14:23:43.698 E/GamesNativeSDK(32291): Can't register class com/google/android/gms/nearby/connection/Connections$StartAdvertisingResult: an exception occurred.

**Comment by DarkBioloG** [comment]
I copied the file google-play-services.jar of \android-sdk\extras\google\google_play_services\libproject\google-play-services_lib\libs in the folder with the project . 
![default](https://cloud.githubusercontent.com/assets/6565626/12214044/88e463d8-b6b8-11e5-8917-55c3c85c0d8b.png)
The application was easy to crash.

**Comment by claywilkinson** [comment]
Do you have the most recent versions loading in the Android SDK Manager?
Did you copy the jars by hand?  You should run Window  >Google Play Games > Setup > Android Setup...

This copies over the required .aar files.

**Comment by DarkBioloG** [comment]
I do not have .aar files. Where can I find them?

**Comment by DarkBioloG** [comment]
This my SDK
![sdk](https://cloud.githubusercontent.com/assets/6565626/12260918/9a14fe2a-b950-11e5-81be-5b61dd0070e7.png)

**Comment by claywilkinson** [comment]
If you install the Android Support Repository and Google Repository under the extras section, it will install the arr files.  The repositories are in $ANDROID_HOME/extras/android/m2repository and google/m2repository

**Comment by DarkBioloG** [comment]
Screenshot pls right folder

**Comment by claywilkinson** [comment]
OK to close this?
