### ISSUE TITLE
Apple rejected my game | Due to white screen and game stuck/hang on cancel google login

### ISSUE THREAD

**Issue by ijunaid** [playgameservices/play-games-plugin-for-unity#904]
Specifically, upon review we have found the application will prompt Google login and go to white screen during gameplay.

The steps to reproduce are:

1.) download app
2.) launch app
3.) press start and Google login prompt
4.) cancel and play game, white screen displayed

**Comment by claywilkinson** [comment]
Can you reproduce this locally and/or provide a log of what is going on?

**Comment by ijunaid** [comment]
I have reproduced it on my iPhone but in my iPhone game is hanged only no white screen is appear.

Steps to reproduce:
1). Send call for authentication: Social.localUser.Authenticate((bool success) => {
				// handle success or failure
			});
2). Make sure the user is not already authenticate.
3). Tap Done button on top right corner of authentication screen
4). Game hanged after tap.

**Comment by claywilkinson** [comment]
Can you share the log file of what is happening?

**Comment by banditdevelopment** [comment]
This happens when there is no network connection for me.

**Comment by ijunaid** [comment]
I have fixed this issue by adding UnityPause(false) in viewWillAppear function in class UnityViewControllerBase.mm in Xcode project. But I think this is not a proper fix. Please look in to it and come back with proper fix :)

- (void)viewWillAppear:(BOOL)animated
{
    UnityPause(false);
...
}

**Comment by claywilkinson** [comment]
This has been fixed in the latest version of the plugin: 0.9.30.  The callback that was being called was blocked by Unity being paused.  It now un-pauses the player when canceled.
