### ISSUE TITLE
Unity 5.3 error creating the gameservice object.Check for errors in GameNativeSDK

### ISSUE THREAD

**Issue by thunderDigimon** [playgameservices/play-games-plugin-for-unity#905]
Tried all solution discussed in the forum, still error persists. PlayGameService activate method prints success.But calling authenticate giving the mentioned error.

**Comment by claywilkinson** [comment]
Can you attempt to build the minimal sample and work from there?  Please share a log of your application starting up.

**Comment by thunderDigimon** [comment]
This error was with 0.9.21 playservice plugin ,updated to the latest version 0.9.27.
Now it asked once for the login, once succeeded crashes the app.
Following exception in adb log,

   GET_ACCOUNTS not granted, requesting.
D/AndroidRuntime(11710): Shutting down VM
E/AndroidRuntime(11710): FATAL EXCEPTION: main
E/AndroidRuntime(11710): Process: com.xxxxx.yyyyy, PID: 11710
E/AndroidRuntime(11710): java.lang.Error: FATAL EXCEPTION [main]
E/AndroidRuntime(11710): Unity version     : 5.3.1f1
E/AndroidRuntime(11710): Device model      : samsung SM-N910G
E/AndroidRuntime(11710): Device fingerprint: samsung/trltedt/trlte:5.0.1/LRX22C/N910GDTU1BOK1:user/release-keys
E/AndroidRuntime(11710): 
E/AndroidRuntime(11710): Caused by: java.lang.NoSuchMethodError: No virtual method shouldShowRequestPermissionRationale(Ljava/lang/String;)Z in class Lcom/google/games/bridge/TokenFragment; or its super classes (declaration of 'com.google.games.bridge.TokenFragment' appears in /data/app/com.xxxxx.yyyyy/base.apk)
E/AndroidRuntime(11710): 	at com.google.games.bridge.TokenFragment.permissionResolved(TokenFragment.java:201)
E/AndroidRuntime(11710): 	at com.google.games.bridge.TokenFragment.processRequests(TokenFragment.java:143)
E/AndroidRuntime(11710): 	at com.google.games.bridge.TokenFragment.onConnected(TokenFragment.java:432)
E/AndroidRuntime(11710): 	at com.google.android.gms.common.internal.zzk.zzk(Unknown Source)
E/AndroidRuntime(11710): 	at com.google.android.gms.common.api.internal.zzj.zzi(Unknown Source)
E/AndroidRuntime(11710): 	at com.google.android.gms.common.api.internal.zzh.zzpx(Unknown Source)
E/AndroidRuntime(11710): 	at com.google.android.gms.common.api.internal.zzh.onConnected(Unknown Source)
E/AndroidRuntime(11710): 	at com.google.android.gms.common.api.internal.zzl.onConnected(Unknown Source)
E/AndroidRuntime(11710): 	at com.google.android.gms.common.api.internal.zzc.onConnected(Unknown Source)
E/AndroidRuntime(11710): 	at com.google.android.gms.common.internal.zzj$zzg.zzqL(Unknown Source)
E/AndroidRuntime(11710): 	at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
E/AndroidRuntime(11710): 	at com.google.android.gms.common.internal.zzj$zza.zzw(Unknown Source)
E/AndroidRuntime(11710): 	at com.google.android.gms.common.internal.zzj$zzc.zzqN(Unknown Source)
E/AndroidRuntime(11710): 	at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
E/AndroidRuntime(11710): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11710): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(11710): 	at android.app.ActivityThread.main(ActivityThread.java:6054)
E/AndroidRuntime(11710): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11710): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(11710): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime(11710): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by thunderDigimon** [comment]
Working properly after changing the version number of playservices.But after importing this now some third party plugin throws "NoSuchMethodError".
AndroidJavaException: java.lang.NoSuchMethodError: no static method "Lcom/xxxxxx/GoogleCloudMessagingPlugin;.instance()Ljava/lang/Object;"
I/Unity   (30302): java.lang.NoSuchMethodError: no static method "Lcom/xxxxxx/GoogleCloudMessagingPlugin;.instance()Ljava/lang/Object;"
I/Unity   (30302): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
I/Unity   (30302): 	at com.unity3d.player.UnityPlayer.a(Unknown Source)

There are two android-support-v4 and support-v4-23.0.1 jars,they were conflicting with some dex errors.So disabled support-v4-23.0.1.Google Service works properly but push notification plugin throwing error.

**Comment by thunderDigimon** [comment]
its because google-play-services_lib gets deleted when proejct is run or built?
Why is it happening

**Comment by claywilkinson** [comment]
We changed the Play Games Services plugin to use the component aars vs. the entire google-play-services_lib since the majority of the client library is not needed and just increases the size of the APK by as much as 50%.  An unfortunate ripple effect is that some plugins are not taking advantage of this optimization yet.
GoogleCloudMessagingPlugin is not a play-services class, but I imagine it is referencing some GCM classes.  You can try to add the .aar for GCM to Assets/Plugins/Android and see if that resolves the missing method.  You can get the arr from  $ANDROID_HOME/extras/google/m2repository/com/google/android/gms/play-services-gcm/8.4.0/play-services-gcm-8.4.0.aar

**Comment by thunderDigimon** [comment]
Thanks a lot....For letting me know the optimization we can do with .aar's. And it fixed the issue as well.

**Comment by claywilkinson** [comment]
Great!
