### ISSUE TITLE
Crash on Authentication when enabled Saved Games

### ISSUE THREAD

**Issue by Coks** [playgameservices/play-games-plugin-for-unity#908]
I get crash application when I call authenticate method. But when I configurable without saved games then Google Play Services works! I would like to use saved with google cloud in my game. 

My log with crash:
[logcat_crash.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/88990/logcat_crash.txt)

Android: 5.0.1
Device: s4 gt-i9500
Unity: 5.3.1p2

Enabled api for project:
![23c5ff7344b7db2646c21674c74d28c5](https://cloud.githubusercontent.com/assets/7351721/12297073/6f41f7d0-ba1c-11e5-85c7-38dbae1f8c36.png)

    void Awake() {
        DontDestroyOnLoad(gameObject);
    }

    // Use this for initialization
    void Start () {
        Activate();
        Invoke("Authenticate", 0.5f);
    }

    public void ShowLeaderboard() {
        if (m_socialStatus == SocialState.Signing) {
            PlayGamesPlatform.Instance.ShowLeaderboardUI();
        }
    }

    void Activate() {
        m_socialStatus = SocialState.Logout;

        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
        // enables saving game progress.
        .EnableSavedGames()
        .Build();

        PlayGamesPlatform.InitializeInstance(config);
        // recommended for debugging:
        PlayGamesPlatform.DebugLogEnabled = true;
        // Activate the Google Play Games platform
        PlayGamesPlatform.Activate();
    }

    void Authenticate() {
        // authenticate user:
        PlayGamesPlatform.Instance.Authenticate(OnAuthenticated);
    }

    void OnAuthenticated(bool success) {
        if (success) {
            m_socialStatus = SocialState.Signing;
            string token = GooglePlayGames.PlayGamesPlatform.Instance.GetToken();
            Debug.Log("authenticate success token: " + token);
        }
        else {
            m_socialStatus = SocialState.Logout;
            Debug.Log("not authenticate");
        }
    }

The application is in open alpha testing.

Any ideas?

**Comment by claywilkinson** [comment]
I see 
`
E/GamesNativeSDK(  429): Exception in com/google/android/gms/games/snapshot/Snapshots.load: java.lang.IllegalStateException: Cannot use snapshots without enabling the 'Saved Game' feature in the Play console.
`
Did you turn on Saved Games via the [Play console](https://play.google.com/apps/publish/) or the API console?  It needs to be turned on via the Play console (https://play.google.com/apps/publish/)

It should look like:
![screen shot 2016-01-15 at 10 16 39 am](https://cloud.githubusercontent.com/assets/8752378/12361135/2f0155ca-bb71-11e5-9d05-d9257613882f.png)

**Comment by Coks** [comment]
Yes, apparently I missed this step.
Can I turn on Saved Games only create new project?

**Comment by claywilkinson** [comment]
I believe that once the game is in the published state it cannot be changed, but I have not confirmed that in a while.

**Comment by Coks** [comment]
I think will be ok. Thx.
