### ISSUE TITLE
Important data missing in built in UI

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#909]
When playing several turn based matches its important to distinguish them from each other. If a player has 10 matches/turns in the "inbox", in many cases the player wants to be able to see details about the different matches before clicking them. As it is now, you only see that its your turn but not against whom... also you see the opponent profile image but thats just not enough in many cases. (not everybode has choosen one and if its an anonomus player its only either a blue or green generic avatar). 

This screenshot is from the IOS built in UI and my device has Swedish as language. The problem is the same with English. On android the built in UI also lack the "against xxxx" info.

![untitledsdds](https://cloud.githubusercontent.com/assets/10234700/12295670/e575ca9a-ba02-11e5-903d-72a317abed9c.png)

...in my user testings I have found another problem related to this (perhaps I should have a new thread). Anyway, when using the quickmatch function players get dealt random display names such as "Player 8766" or "Player 9217". Also they get either a blue or green generic smiling avatar. My user testings  has let me understand that this is just not enought to help distinguish one from another. The easiest solution to this is to have more than just a blue and green generic avatar (yellow, pink, red etc....) also to help separating them there could be different avatars aswell. 

Also it proved very hard for my users to remember the 3-4 digits separating the random players. I did some small tests with letters and combined letters/digits and the difference was HUGE (much easier to remember).

Player GH2    (2 letters one digit 7290 combos)
Player TYW    (3 letters 19683 combos)

Also as it is now my testings suggests that users dont really understand the meaning of "Player 8766". They dont understand that the opponent is anonomous and that its a random opponent. I suggest it should be something like this instead:    Your turn vs anonomous player "TYW". The fact that the opponent was picked randomly could be illustrated with a dice icon in the player profile image (instead of the generic smiling avatar, or a combo of both). Also you could illustrate anonomous with a questionmark in the profile picture. I played around in photoshop to visualize (without any talent obv.)

![9d47f523-e46d-4044-81b1-846251430c7bxcvcxv](https://cloud.githubusercontent.com/assets/10234700/12298948/e48c3ce2-ba14-11e5-9c95-87ea8fe30be3.jpg)

**Comment by claywilkinson** [comment]
Thanks for the feedback! I'll pass it along.

**Comment by claywilkinson** [comment]
I believe this has been rolled out in the latest Play Games App.
