### ISSUE TITLE
Getting a android manifest issue.

### ISSUE THREAD

**Issue by Truth7442** [playgameservices/play-games-plugin-for-unity#911]
Heres the error:

Error building Player: CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
C:\Program Files\Java\jdk1.7.0_51\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/Truth7442/AndroidSDK\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\androidplayer/Tools\sdktools.jar" -

stderr[
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Truth7442\Desktop\Unity Projects\Zig Tap\Temp\StagingArea\android-libraries\play-services-ads-8.4.0\AndroidManifest.xml:10] Trying to merge incompatible /manifest/application/activity[@name=com.google.android.gms.ads.AdActivity] element:
  <activity
--    @android:name="com.google.android.gms.ads.AdActivity">
--</activity>
--(end reached)
  <activity
++    @android:name="com.google.android.gms.ads.AdActivity"
++    @android:theme="@android:style/Theme.Translucent">
++</activity>
]
stdout[
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Truth7442\Desktop\Unity Projects\Zig Tap\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\AndroidManifest.xml:10] Skipping identical /manifest/application/meta-data[@name=com.google.android.gms.version] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Truth7442\Desktop\Unity Projects\Zig Tap\Temp\StagingArea\android-libraries\MainLibProj\AndroidManifest.xml:17] Skipping identical /manifest/application/meta-data[@name=com.google.android.gms.version] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Truth7442\Desktop\Unity Projects\Zig Tap\Temp\StagingArea\android-libraries\play-services-basement-8.4.0\AndroidManifest.xml:5] Skipping identical /manifest/application/meta-data[@name=com.google.android.gms.version] element.
]

**Comment by cjdp25** [comment]
I'm having the same issue

**Comment by NEBR** [comment]
The same... :-(

**Comment by cjdp25** [comment]
I solved it following this thread: https://github.com/playgameservices/play-games-plugin-for-unity/issues/814
