### ISSUE TITLE
Keeps importing support-v4 when we don't want it

### ISSUE THREAD

**Issue by epsmarkh** [playgameservices/play-games-plugin-for-unity#912]
support-v4 adds a huge number of methods to the final dex taking us well beyond the limit. Since we target api level 15, we should be fine to use support-v13 or higher which gets rid of almost 10000 otherwise redundant methods. However, if we remove support-v4, the plugin immediately adds it back in!

We should be able to define a minimum api and the plugin import an appropriate support library rather than assuming we want to waste all our methods for support we will not use.

**Comment by claywilkinson** [comment]
Hmm. I'll take a look at this problem.  I think there are some dependencies in the C++ SDK that limit how far back it can go.

In the meantime, you can change the version and dependencies that get updated automatically in 
`Assets/GooglePlayGames/Editor/BackgroundResolution.cs`  In there, it lists the jars and the versions that are automatically imported.

You can also disable the automatic updating by removing the method `OnPostprocessAllAssets` in the same file.

Please share your progress and suggestions to make this better, and I'll do the same.

**Comment by claywilkinson** [comment]
I tried this and it cannot work.  The play-services-base aar which defines the GoogleAPIClient now requires android.support.v4.util.ArrayMap, so support-v4 is required for all applications that use GoogleAPIClient.
