### ISSUE TITLE
OpenWithManualConflictResolution finishes with "InternalError" when leaderboards are opened

### ISSUE THREAD

**Issue by Trisibo** [playgameservices/play-games-plugin-for-unity#913]
In a game, whenever the player authentication finishes correctly at any point I try to open a saved game with `OpenWithManualConflictResolution`. Also, when the player tries to open the leaderboards I start the authentication process. The problem is that when I try to retrieve the saved game while the leaderboards UI is displayed, the callback `completedCallback` is always called by `OpenWithManualConflictResolution` with the status `SavedGameRequestStatus.InternalError`. It works correctly when I perform the authentication at any other point without showing the leaderboards UI.

I attach the logcat data from the moment in which the authentication starts when the player opens the leaderboards: 
[logcat.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/92743/logcat.txt)

**Comment by Trisibo** [comment]
As a workaround, I delayed opening the saved game 1 frame.

**Comment by claywilkinson** [comment]
It looks like the callback is not being called back on the UI thread.  I see
`
mothering to avoid passing exception into Native: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.soomla.data.KeyValueStorage
                                                             java.lang.ClassNotFoundException: com.soomla.data.KeyValueStorage
`
I assume that that class exists in your project, so it probably is that the callback is not on  the UI thread, so the Java classloader will not work properly.

Your workaround works since it is now on the UI thread.  Another workaround would be to wrap your callback in `PlayGamesHelperObject.RunOnGameThread()`

**Comment by claywilkinson** [comment]
OK to close?

**Comment by Trisibo** [comment]
I'm sorry, I've been busy like hell. Before opening the issue I had used `PlayGamesHelperObject.RunOnGameThread()`, though only for my own code; I'll try wrapping the whole callback and report back.

**Comment by claywilkinson** [comment]
No problem! - just want to make sure I don't close out something that should not be closed yet.  Thanks!

**Comment by Trisibo** [comment]
Sorry for the delay. I have tried wrapping all calls to Google Play methods with `PlayGamesHelperObject.RunOnGameThread()`, and it works fine.

However, I'm getting the same error from `PlayGamesPlatform.LoadScores()` when showing the leaderboards UI and loading the cloud data at the same time, even when wrapping the calls with `PlayGamesHelperObject.RunOnGameThread()`. What I have found as a workaround is that starting each call in a different frame seems to solve the problem, at least in my device. So, for example, when the user logs in I call the method to open the leaderboards, wait a frame and then I load the scores, and then I wait another frame and load the cloud data; if I do the last two in the same frame (even if in the UI thread) it fails.

The code below shows the core of what I do when it fails. I also attach the logcat from the start of the game until the point in which I try to load the scores and it fails.


**Code that starts the authentication when the leaderboards button is pressed:**
```
GameServicesAuthentication.Instance.AuthenticateUser(false, true, (bool authSuccess) =>
{
    if (authSuccess)
    {
        GameLeaderboards.Instance.ShowLeaderboards((bool lbSuccess) =>
        {
            // .......
        });
    }
});
```


**Method that shows the leaderboards UI:**
```
public void ShowLeaderboards(Action<bool> showTryFinished = null)
{
    PlayGamesPlatform.Instance.ShowLeaderboardUI(GooglePlayGamesConstants.leaderboard_strikes_in_a_row, (UIStatus result) =>
    {
        PlayGamesHelperObject.RunOnGameThread(() =>
        {
            if (showTryFinished != null)
            {
                switch (result)
                {
                    case UIStatus.Valid:
                    case UIStatus.UserClosedUI:
                        showTryFinished(true);
                        break;

                    default:
                        showTryFinished(false);
                        break;
                }
            }
        });
    });
}
```


**Methods used to authenticate a user:**
```
public void AuthenticateUser(bool trySilent, bool showMessageOnError, Action<bool> authenticationFinished = null)
{
    // Initializations.
    
    PlayGamesPlatform.Instance.Authenticate(silent : trySilent, callback : (bool success) =>
    {
        PlayGamesHelperObject.RunOnGameThread(() =>
        {
            OnNewAuthenticationFinished(success, showMessageOnError);
        });
    });
}


void OnNewAuthenticationFinished(bool success, bool showMessageOnError)
{
    // "NewAuthenticationFinished" is a C# event.
    
    if (NewAuthenticationFinished != null)
        NewAuthenticationFinished(success);
}
```


**Code that adds a handler to the event raised when the authentication process finishes, and the method used to load the friends scores:**
```
void Awake()
{
    GameServicesAuthentication.NewAuthenticationFinished += (bool success) =>
    {
        if (success)
            LoadFriendsByHighScore();
    };
}


void LoadFriendsByHighScore()
{
    PlayGamesHelperObject.RunOnGameThread(() =>
    {
        // Initializations.

        PlayGamesPlatform.Instance.LoadScores(GooglePlayGamesConstants.leaderboard_strikes_in_a_row, LeaderboardStart.TopScores, 1000, LeaderboardCollection.Social, LeaderboardTimeSpan.AllTime, (LeaderboardScoreData scoresData) =>
        {
            PlayGamesHelperObject.RunOnGameThread(() =>
            {
                if (!scoresData.Valid)
                {
                    // --> Execution enters here <--
                }
                else
                {
                    // ........
                }
            });
        });
    });
}
```
[logcat.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/135459/logcat.txt)

**Comment by claywilkinson** [comment]
The callbacks happen on the game thread now.
