### ISSUE TITLE
Leaderboard directly showing public scores?

### ISSUE THREAD

**Issue by skirners1** [playgameservices/play-games-plugin-for-unity#914]
Hello!

Can I show a leaderboards public scores directly?

I have tried using the following:

```
PlayGamesPlatform.Instance.LoadScores(
            ToppListan,
            LeaderboardStart.PlayerCentered,
            100,
            LeaderboardCollection.Public,
            LeaderboardTimeSpan.AllTime,
            (data) =>
            {
                // no code here. Don't know how to use it..
            });
PlayGamesPlatform.Instance.ShowLeaderboardUI(ToppListan);
```

But I can't get it to work.
Does anyone have a working example?

Best regards,
Lucas Ivarsson

**Comment by fido77** [comment]
I was wanting to know the same thing. Having to tap on "All" has been a problem due to some players are not that familiar with the Google Play leaderboards and do not even realize that button is there.

**Comment by claywilkinson** [comment]
I'll pass along the request to add the collection parameter to ShowLeaderboardUI().

**Comment by ffff1111** [comment]
Is this already implemented?
I think LeaderboardStart.PlayerCentered and LeaderboardCollection.Public must be the default behaviour because Social Leaderboard is, in most cases, empty.
Is there any example of how to show a Public Leaderboard using the GPG UI?

**Comment by olehkuznetsov** [comment]
Public is already default value.
