### ISSUE TITLE
Games are always CanRematch = false in TBM

### ISSUE THREAD

**Issue by Dynamiek108** [playgameservices/play-games-plugin-for-unity#915]
Hi!

The bool CanRematch is always set to false in every TunBasedMatch, even if it can be rematched!

Also it would be nice if you could tell me how to access the method "getRematchId"
https://developers.google.com/android/reference/com/google/android/gms/games/multiplayer/turnbased/TurnBasedMatch.html#getRematchId%28%29

Thanks!

**Comment by claywilkinson** [comment]
This has been fixed in a more recent version of the play-services-games client library.

**Comment by AleksOtto** [comment]
This bug seems to be back in v0.9.37
