### ISSUE TITLE
Giving my participantid to retain turn in Taketurn call.. but it goes in TheirTurn states...

### ISSUE THREAD

**Issue by melayerjohn** [playgameservices/play-games-plugin-for-unity#916]
Hi all... i am facing one problem now, that is in my game , at particular point i want to retain my turn instead of giving to opposite player.Same time i am passing match data to opposite player to show my move , for that i am giving my turn movement and my participantid in Taketurn call to retain my turn.
But match turn status is showing "TheirTurn" state.So that i cant take my turn unless i got match from show inbox ->Selecting match.
I tried to set match state to "MyTurn" ,but it is read only field so can't do that.
Please tell me any way to retain my turn without going to inbox and selecting match...

Thanks in advance.

**Comment by claywilkinson** [comment]
Sounds like you are trying to do more of a "realtime" multiplayer - or a model where you have a backend server and send the intermediate moves to the server, and then a notification to the other player so they can see the moves.
