### ISSUE TITLE
iOS 9, game freeze after closing authentication window

### ISSUE THREAD

**Issue by AfifFaris** [playgameservices/play-games-plugin-for-unity#917]
in these screen if I close window by tapping "cancel" (iOS8) or "Done"(iOS9) and then back to the game screen, the game will freeze on iOS9. I have to sent the game to background using home button and open the game again to release it from freeze state.

iOS 8
![ios8](https://cloud.githubusercontent.com/assets/8552823/12410760/84487caa-bebb-11e5-9594-897fed45471c.png)

iOS 9
![ios9](https://cloud.githubusercontent.com/assets/8552823/12410761/873db3f8-bebb-11e5-9c76-3284c0ff53ea.png)

These are the console logs

iOS 8
```
<Warning>: INFO: Auth operation started: SIGN IN
<Warning>: VERBOSE: Running UI sign in request on main thread.
<Warning>: VERBOSE: Finished running UI sign in request on main thread.
<Warning>: signInWillDispatch: (null)
<Warning>: ERROR: Sign-in error.
```

iOS 9
```
<Warning>: INFO: Auth operation started: SIGN IN
<Warning>: VERBOSE: Running UI sign in request on main thread.
<Warning>: VERBOSE: Finished running UI sign in request on main thread.
<Error>:  SecDbRecordChange db <SecDbConnection rw open> changed outside txn
<Warning>: signInWillDispatch: (null)
<Error>: CoreAnimation: failed to allocate IOSurface
```

it looks like "CoreAnimation: failed to allocate IOSurface" is the problem, I don't know how to solve this and I think this is a bug in current iOS SDK.

Is there any solution for this or did I miss something?

**Comment by AfifFaris** [comment]
it looks like this method is not called when the google sign in window is closed.
```
- (void)signIn:(GIDSignIn *)signIn dismissViewController:(UIViewController *)viewController {
   UnityPause(false);
  [[self rootViewController] dismissViewControllerAnimated:YES completion:nil];
}
```

so I tried commenting out the UnityPause part
```
- (void)signIn:(GIDSignIn *)signIn presentViewController:(UIViewController *)viewController {
//   UnityPause(true);
  [[self rootViewController] presentViewController:viewController animated:YES completion:nil];
}


- (void)signIn:(GIDSignIn *)signIn dismissViewController:(UIViewController *)viewController {
//   UnityPause(false);
  [[self rootViewController] dismissViewControllerAnimated:YES completion:nil];
}
```

the game will not freeze now, I am not sure if this is alright or not. 
If there's no problem with this, I will use this as temporary solution until the real fix for this problem is released.

@claywilkinson I am sorry, can you confirm this is ok for temporary solution?

**Comment by claywilkinson** [comment]
Which version of GoogleSignIn are you using?  Are you using CocoaPods to build?  If so, can you share your Podfile.lock file?

**Comment by AfifFaris** [comment]
I use version 2.4.0 downloaded from here 
https://developers.google.com/identity/sign-in/ios/sdk/?hl=en

I am not using CocoaPods to build.

**Comment by claywilkinson** [comment]
The latest update to the plugin fixes this issue.  The problem is that "Done" link or backing out (due to no internet connection) did not go through the same dismissViewController path as the buttons, so UnityPause(false) was never called.  It is now called if needed from the plugin's callback.
