### ISSUE TITLE
- OFF TOPIC - ...but why dont we have a thread with a list of games using these services?

### ISSUE THREAD

**Issue by Hoffa25** [playgameservices/play-games-plugin-for-unity#918]
I just think it would be good for inspiration and learning. Since Im making a turn based game for both android and ios it would be very interesting to see how other games on the app stores have done it. I have yet not found a single game using turn based services (a couple of real time though).

I have really tried to search this but with no luck... Perhaps this isnt the right forum for such a thread/list. If not, please suggest were.

**Comment by simgesimulation** [comment]
Really good idea. We can see what is possible or not just by looking already implemented apps.

**Comment by Hoffa25** [comment]
Ok, well then I guess Im starting the list with the two games I have found:

Real time multiplayer:
https://play.google.com/store/apps/details?id=com.seriouscorp.clumsybird&hl=sv

Turn Based I think... I really dont get how to play this game:)
https://play.google.com/store/apps/details?id=com.hg.frozenfrontfree&hl=sv

**Comment by simgesimulation** [comment]
Here another:
https://play.google.com/store/apps/details?id=com.SimgeSimulation.Woodball&hl=tr

**Comment by fido77** [comment]
Not sure if this is what you want as our game is not multiplayer at the moment, but we have two leaderboards in the game: 

[](https://play.google.com/store/apps/details?id=com.CrowdControlfree.iffgames)

**Comment by fido77** [comment]
Not sure if this is what you are wanting as we do not have multiplayer in this game yet, but we do have two leaderboards in the game that work rather well.

https://play.google.com/store/apps/details?id=com.CrowdControlfree.iffgames

**Comment by Hoffa25** [comment]
@fido77 This thread is for multiplayer, however I see now that I didnt specify that. @simgesimulation Congrats to 1 - 5 million downloads!! Well done. Your game is real time multiplayer right?

**Comment by simgesimulation** [comment]
@Hoffa25 yes It is a realtime multiplayer game. It is a very famous, old and traditional game in Turkey. And we aimed to show this game to other countries. Now, lots of fanatics around the world.

**Comment by fido77** [comment]
Our game is not real time multiplayer, but it does have the leaderboards where people can try to beat other player's scores. We are currently adding in where people can bet real money against other players. Does that count as multiplayer? Going to be checking out those games you guys posted this weekend with a few intoxicated people.

**Comment by fido77** [comment]
Woodball looks awesome!

**Comment by claywilkinson** [comment]
Closing during issue scrubbing.  Feel free to continue the thread even though it is closed (since it is not really an issue).
