### ISSUE TITLE
Can't report a score

### ISSUE THREAD

**Issue by Daiflys** [playgameservices/play-games-plugin-for-unity#92]
Hello, i'm having a weird problem, when i want to submit a new score i do the following:
Social.ReportScore((int)(aScore*100),"myid",(bool success) =>{
				Debug.Log(success ? "Reported score successfully" : "Failed to report score");
(myid is my table string of the leaderboard)
And what happens is that it reported the score successfully (success true) but it happens nothing, the score is not reported.
Anyone can help? thanks!

**Comment by claywilkinson** [comment]
old thread - so closing
