### ISSUE TITLE
Testing multiplayer in my network works but when i tested with other people crash

### ISSUE THREAD

**Issue by adsm1987** [playgameservices/play-games-plugin-for-unity#920]
Hi, 

First of all thanks for this plugin.

Well i created a game and in multiplayer mode i used your plugin to be able to play with other people in my game, but every time i tested in my network works fine and i dont have any kind of problem but when i play with other people some times the message just never got received (after the first match). If i just restarted the game the first game i play will run perfectly but the second one we need both to restart the game again to work. My problem is this message

```
PlayGamesPlatform.Instance.RealTime.SendMessageToAll (true, message.ByteArray); //reliable */
```

It's supossed to be TCP protocol... I really don't understand.

When i create the room my "partner" never receive this message, then is kinda strange to debugging.

Really, thanks and keep the good work!,

Abraham.

**Comment by claywilkinson** [comment]
Is there a crash?  Can you post the log?

**Comment by adsm1987** [comment]
Hi, 

Thanks for the reply i will post the cenario of a match between 2 players (a friend and me).

Hope this can help you.
[logcat_slave.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/97249/logcat_slave.txt)
[logcat_,master,.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/97250/logcat_.master.txt)

**Comment by claywilkinson** [comment]
When the master sends it gets an error, 
`I/Unity   (23438):  [Play Games Plugin DLL] 01/20/16 10:14:11 +00:00 DEBUG: Entering internal callback for InternalSendReliableMessageCallback ERROR_INTERNAL`

What parameters are you passing in on the call to send?  Is it possible that you are not on the UI thread when calling this (I don't think it makes a difference, but it might?)

**Comment by adsm1987** [comment]
Hi, thanks for the reply. Well the function with the parameter's is:

    public void SendReadySignal()
    {
      message.Clear();
      message.Serialize(msgVersion);
      message.Serialize('R'); //Ready
  
      Debug.Log ("Sending ready signal R to all players in the room");
      PlayGamesPlatform.Instance.RealTime.SendMessageToAll (true, message.ByteArray); //reliable */
    }

About the UI thread, i think he is running in the UI thread even if not, i don't know if that could be the problem because the multiplayer is working the first time we play, after the first game we just receive that log... :/.

Thanks a lot!

**Comment by claywilkinson** [comment]
Can you reverse the roles of the devices?  It looks like you have more extensive logging on that device, which may give some insight into the internal error.

**Comment by adsm1987** [comment]
Right now i'm creating the rooms master or slave randomly, bot

**Comment by claywilkinson** [comment]
The version difference should not be an issue.

**Comment by claywilkinson** [comment]
Closing since it has been quiet for over a year.  Please open a new issue if you are still having problems.
