### ISSUE TITLE
Reste Achievments for testing

### ISSUE THREAD

**Issue by Dynamiek108** [playgameservices/play-games-plugin-for-unity#921]
Hi!

Is there a way to reset the achievments, for testing purpose?

Thanks!

**Comment by claywilkinson** [comment]
If your game is not published, you can reset the progress for testers from the Play Games Console by going to the Achievement definition page and at the bottom click "Reset Achievement Progress"

**Comment by Dynamiek108** [comment]
Alright! Thanks !!!

... and sorry for the writing errors ;)

**Comment by claywilkinson** [comment]
You're welcome :+1:
