### ISSUE TITLE
smoketest sign in

### ISSUE THREAD

**Issue by katsudoka** [playgameservices/play-games-plugin-for-unity#922]
Hello,
I imported smoketest package to my unity empty projet and added the last google pmay services to test the authentification and tye events with google play services. I followed the instructions in the readme for the projet smoketest. I followed all the steps and in my unity projet i created a keystore and i build my projet in android platform and copy the apk in my android phone. When i open the apk and i click on sign in. The button doesn t work. I can t sign in. I thought that may be it is because i used the last version from google play services package. So i deleted the last google play services package and exporteda previous one. And followed all the steps and build the projet to an android device but the same problem exists. When i click on sign in. The authentification doesn t work. Can you please help me. Thanks in advance

**Comment by claywilkinson** [comment]
Can you share the log of what is happening when you are signing in?

**Comment by katsudoka** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8910840/12473269/17b752d0-c011-11e5-940f-b5169631254a.png)
![screenshot1](https://cloud.githubusercontent.com/assets/8910840/12473291/497969b6-c011-11e5-87ff-30473abf7703.png)
Here is a Screen Capture of what i have when i click on Authenticate Button.Thanks in advance

**Comment by claywilkinson** [comment]
Unfortunately, the Play Game Services plugin does not work in the Editor.  You need to run it on an actual device.

**Comment by claywilkinson** [comment]
OK to close?
