### ISSUE TITLE
[RealTime MP] Punish player who leaves the room.

### ISSUE THREAD

**Issue by loftyy** [playgameservices/play-games-plugin-for-unity#923]
Does anyone here know how to punish a player (remove from PlayerPrefs "Coins") who leaves a gaming room while the player who is still in the room doesn't get punished? I tried various codes under OnPeersDisconnected and OnLeftRoom but they don't seem to work approprietly.

Note: there are only 2 players in the room.

Here is what I tried:

...

```
public bool CoinsRemovalForExiting = true;



public void OnLeftRoom()
{
    points = 0;
    PointsText.enabled = false;
    health = 0;
    EnableAnimationBool(TimeOuterAnimator, "showTimeOuter", true);

    if (CoinsRemovalForExiting == true)
    {
        PlayerPrefs.SetInt("Coins", PlayerPrefs.GetInt("Coins") - 200);
     }
}


public void OnPeersDisconnected(string[] participantIds)
{
    CoinsRemovalForExiting = false;

    EnableAnimationBool(TimeOutAnimator, "showTimeOut", true);
    health = 0;
    PlayGamesPlatform.Instance.RealTime.LeaveRoom();
    points = 0;
    PointsText.enabled = false;
}
```

**Comment by claywilkinson** [comment]
Closing this.  This type of design question is probably bette suited for [Stackoverflow](http://stackoverflow.com/questions/tagged/google-play-games), where it will have a wider audience of possible respondents.
