### ISSUE TITLE
Unity 4.3 issues, no compile errors, callbacks with fail

### ISSUE THREAD

**Issue by Disar** [playgameservices/play-games-plugin-for-unity#929]
I know the readme says it's explicitly for unity 4.6 and higher but I unfortunately have a unity 4.3 project on my hands.

The only error I got when importing was the Texture2D.black, I just commented them out as I'll be using text for leaderboards only.

My project compiles fine, the google games login popup shows and I can select my account.
Afterwards nothing happens. Mind you this is a new clean project with nothing in the scene. I'm just logging a " success"  to the console.

    /Unity   ( 3497): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
    /Unity   ( 3497):
    /Unity   ( 3497):  [Play Games Plugin DLL] 01/27/16 10:09:09 +01:00 DEBUG: Creating Android IPlayGamesClient Client
    /Unity   ( 3497):
    /Unity   ( 3497): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
    /Unity   ( 3497):
    /Unity   ( 3497): Building GPG services, implicitly attempts silent auth
    /Unity   ( 3497):
    /Unity   ( 3497): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
    /Unity   ( 3497):
    /Unity   ( 3497):  [Play Games Plugin DLL] 01/27/16 10:09:10 +01:00 DEBUG: Entering state: BeforeRoomCreateStartedState
    /Unity   ( 3497):
    /Unity   ( 3497): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
    /Unity   ( 3497):
    /Unity   ( 3497):  [Play Games Plugin DLL] 01/27/16 10:09:10 +01:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op.
    /Unity   ( 3497):
    /Unity   ( 3497): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
    /Unity   ( 3497):
    /Unity   ( 3497):  [Play Games Plugin DLL] 01/27/16 10:09:10 +01:00 DEBUG: Entering state: ShutdownState
    /Unity   ( 3497):
    /Unity   ( 3497): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
    /Unity   ( 3497):
    /Unity   ( 3497):  [Play Games Plugin DLL] 01/27/16 10:09:10 +01:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
    /Unity   ( 3497):
    /Unity   ( 3497): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
    /Unity   ( 3497):
    /Unity   ( 3497):  [Play Games Plugin DLL] 01/27/16 10:09:12 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
    /Unity   ( 3497):
    /Unity   ( 3497): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
    /Unity   ( 3497):
    /Unity   ( 3497): Invoking callbacks, AuthState changed from silentPending to Unauthenticated.
    /Unity   ( 3497):
    /Unity   ( 3497): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
    /Unity   ( 3497):
    /Unity   ( 3497): there are pending auth callbacks - starting AuthUI
    /Unity   ( 3497):
    /Unity   ( 3497): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
    /Unity   ( 3497):
    /Unity   ( 3497):  [Play Games Plugin DLL] 01/27/16 10:09:14 +01:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.
    /Unity   ( 3497):
    /Unity   ( 3497): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
    /Unity   ( 3497):
    /Unity   ( 3497):  [Play Games Plugin DLL] 01/27/16 10:10:39 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
    /Unity   ( 3497):
    /Unity   ( 3497): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
    /Unity   ( 3497):
    /Unity   ( 3497): AuthState == Unauthenticated calling auth callbacks with failure
    /Unity   ( 3497):
    /Unity   ( 3497): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
    /Unity   ( 3497):
    /Unity   ( 3497):  [Play Games Plugin DLL] 01/27/16 10:10:39 +01:00 DEBUG: Invoking user callback on game thread
    /Unity   ( 3497):
    /Unity   ( 3497): (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 53)
    /Unity   ( 3497):

- Bundle ID match with the linked app.
- The SHA1 key is set.
- Im added as tester to the linked app.

I can't tell if unity 4.3.7 is my problem or something goes wrong elsewhere.

Any idea?

Edit: For some reason I did have to copy the zipalign tool from the build-tools ( took the latest version 23) into the root of the android sdk, otherwise the apk couldn't be generated. But everything seems to compile fine.

Edit 2: 

        /Unity   ( 3497):  [Play Games Plugin DLL] 01/27/16 10:09:14 +01:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room.

I find this to be very peculiar as I'm not doing much with match making  ( assuming it got anything to do with that ). I just want leaderboards, nothing more.

**Comment by claywilkinson** [comment]
I don't think it is a problem specific to 4.3, I'd first double check that the SHA1 and package name definitely match the console.  Can you share the log of all the log categories, not just Unity?

You might want to build a sample project at least once using a more recent version of Unity and confirm everything is worked as expected.  Then use that as a reference to make changes for the older version.

The RTMP warning is OK, it is just a warning that any multiplayer actions happening will break when the Unity application is paused.

**Comment by Disar** [comment]
>  I'd first double check that the SHA1 and package name definitely match the console.

I double checked, eventually even uploaded an alpha apk. So I can't input the sha1 anymore it's automated by the dev console.

As for the logs can I filter something specific? Right now It just keeps going showing

 		I/BufferQueue(  140): [SurfaceView](this:0x4377ca28,api:1) [queue] queued:2 (lag)
		D/BufferQueue(  140): [SurfaceView](this:0x4377ca28,api:1) NEW [idx:1] time:6894008, handle:0x4221af50
		D/BufferQueue(  140): [SurfaceView](this:0x4377ca28,api:1)     [idx:3] time:6894046, handle:0x42d75808
		D/BufferQueue(  140): [SurfaceView](this:0x4377ca28,api:1)     [idx:0] time:6894067, handle:0x4377e4c0

**Comment by Disar** [comment]
Well I found this  in the error logs :

		01-27 17:03:12.311: E/(14503): appName=com.vg.leaderboardtest, acAppName=com.android.cts.openglperf
		01-27 17:03:12.311: E/(14503): 0
		01-27 17:03:12.311: E/(14503): appName=com.vg.leaderboardtest, acAppName=com.android.browser
		01-27 17:03:12.311: E/(14503): 0
		01-27 17:03:12.406: E/linker(14503): load_library(linker.cpp:759): library "/mnt/asec/com.vg.leaderboardtest-1/pkg.apk/assets/bin/Data/Managed/UnityEngine.dll.so" not found
		01-27 17:03:12.493: E/linker(14503): load_library(linker.cpp:759): library "/mnt/asec/com.vg.leaderboardtest-1/pkg.apk/assets/bin/Data/Managed/Assembly-CSharp.dll.so" not found
		01-27 17:03:12.730: E/linker(14503): load_library(linker.cpp:759): library "/mnt/asec/com.vg.leaderboardtest-1/pkg.apk/assets/bin/Data/Managed/System.Core.dll.so" not found
		01-27 17:03:13.246: E/linker(14503): load_library(linker.cpp:759): library "gpg" not found
		01-27 17:03:13.272: E/linker(14503): load_library(linker.cpp:759): library "/mnt/asec/com.vg.leaderboardtest-1/pkg.apk/assets/bin/Data/Managed/System.dll.so" not found
		01-27 17:03:13.279: E/linker(14503): load_library(linker.cpp:759): library "gpg" not found
		01-27 17:03:13.298: E/linker(14503): load_library(linker.cpp:759): library "gpg" not found
		01-27 17:03:13.372: E/linker(14503): load_library(linker.cpp:759): library "gpg" not found
		01-27 17:03:13.374: E/linker(14503): load_library(linker.cpp:759): library "gpg" not found
		01-27 17:03:13.385: E/linker(14503): load_library(linker.cpp:759): library "gpg" not found
		01-27 17:03:13.387: E/linker(14503): load_library(linker.cpp:759): library "gpg" not found
		01-27 17:03:13.390: E/linker(14503): load_library(linker.cpp:759): library "gpg" not found
		01-27 17:03:13.392: E/linker(14503): load_library(linker.cpp:759): library "gpg" not found
		01-27 17:03:13.403: E/dalvikvm(14503): Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.common.zze.zzb
		01-27 17:03:13.458: E/linker(14503): load_library(linker.cpp:759): library "gpg" not found
		01-27 17:03:13.460: E/linker(14503): load_library(linker.cpp:759): library "gpg" not found
		01-27 17:03:13.463: E/linker(14503): load_library(linker.cpp:759): library "gpg" not found
		

This is probably why?

although the authentication popup does show up.

**Comment by claywilkinson** [comment]
Off the top of my head, I think the categories of interest are GamesNativeSDK, GamesServiceBroker, and GLSActivity?

**Comment by Disar** [comment]
Not sure if you saw the other comment ( I think we commented at the same time ) but im assuming gpg = google play games?
Perhaps Unity 4.3 is missing some specific lib?

**Comment by Disar** [comment]
Well I can confirm that in unity 5.3 it fails to authenticate as well. I've double checked every and feel like  i've hit a wall.

GameNativeSDK returns the following:

     01-27 18:03:28.651: I/GamesNativeSDK(28542): Auth operation started: SIGN IN
     01-27 18:03:28.651: I/GamesNativeSDK(28542): Connecting to Google Play...
     01-27 18:03:28.681: V/GamesNativeSDK(28542): Play Games callback indicates connection failure.
     01-27 18:03:28.681: I/GamesNativeSDK(28542): UI interaction required to connect to Google Play.

Broker gives me:

     01-27 18:02:40.591: W/GamesServiceBroker(1851): Client connected with SDK 8487000, Services 8489230, and Games 35170032


To be clear I should be able to test my Game service data while it's in " draft "  status right? 

Here is my code btw: 

using UnityEngine;
	using System.Collections;
	using UnityEngine.SocialPlatforms.GameCenter;
	using UnityEngine.SocialPlatforms;
	#if UNITY_ANDROID
	using GooglePlayGames;
	using GooglePlayGames.BasicApi;
	#endif
	
	public class LeaderBoards : MonoBehaviour
	{
		
			void Awake(){
				#if UNITY_ANDROID
					PlayGamesPlatform.Activate();
					PlayGamesPlatform.DebugLogEnabled = true;
				#endif
			}
		
			// Use this for initialization
			void Start ()
			{
				Social.localUser.Authenticate (OnLogin);
			}
		
			void OnLogin (bool result)
			{
				Debug.Log("Login : " + (result?"Succeeded":"Failed"));
					if (result)
							OnSuccess ();
			}
		
			void OnSuccess ()
			{
					Debug.Log("Show Leader boards ");
					ILeaderboard lb = Social.CreateLeaderboard ();
					lb.id = GPGSIds.leaderboard_meters;
				
					//lb.range = new Range (lb.localUserScore.rank - 5, 10);
					lb.LoadScores (result => {
							foreach (IScore score in lb.scores) {
									Debug.Log (score);
							}
				
					});
			
			
			}
	}

**Comment by claywilkinson** [comment]
You don't need to publish the game to test it locally.  The code looks reasonable, I am assuming you are seeing the "Login : Failed" message.

So all this points to something mismatched between the apk and the Play Game Console.
When you run Window > Google Play Games > Setup > Android Setup... and you pasted the resources from the Play Console into the dialog.  Those resources should contain the app id and the bundle id of the app.  So these are easy to verify.

To check the SHA1, you can directly check the .apk file using keytool:

`keytool -list -printcert -jarfile <apkfile.apk>`

And confirm it matches the linked application in the Play Game Console.

**Comment by Disar** [comment]
> hose resources should contain the app id and the bundle id of the app. So these are easy to verify.

Yes. These look good.

I can't find the sha1 on the dev console, but I performed the command you suggested and used Keystore Explorer to see if the sha1 of the apk and the keystore match, and they do.

Any other idea?
I'm also wondering if the testers I've added are actually active, there are no other options for that either. Im assuming there is no way of testing this?

**Comment by claywilkinson** [comment]
To check the testers:
Go to https://play.google.com/apps/publish/ and select your game from the list.
Then click Testing - which is on the left towards the bottom of the page. This will list the emails of the testers.

To get to the SHA1 is a little more involved.
1. Click "Game Details" for your game on the Play Games Console.
2. At the bottom, there is a heading "API CONSOLE PROJECT" and a link to the API console project for the game.  Click that link which takes you to the API console.
3. On the title of the page, click the "hamburger" menu on the left (the 3 lines just above Home).
4. Click the 'API Manager'
5. Then on the left, click 'Credentials'
6. Click on the Android client (e.g. Android client 1)
7. See the package name and the SHA1 fingerprint.  Make sure these match your application.

**Comment by Disar** [comment]
Thanks for the input, I only see OAuth 2.0 client IDs. 

https://i.imgur.com/kxl2Orq.png

Both have the sha1 signature, I removed one as it had an old bundle id I was testing.

But I don't see any android client option.

**Comment by Disar** [comment]
I've created a completely new profile for my game and it worked directly without fuss. Sorry for the false alarm. I think something went wrong on Googles side.

**Comment by claywilkinson** [comment]
Great news!

The linked app has a bundle id and the SHA1 fingerprint.  These two need to match the application,  The product name can be anything. It is a fairly common thing to have 1 game configured in the Play Games Console that has multiple linked applications.  For example having a free version of a game and paid version, then they can share the backend configuration so players do not lose their score and achievements if they upgrade from free to paid.

**Comment by Disar** [comment]
Noted.
Thank you for your great support!
