### ISSUE TITLE
Hi! I'm using Unity 3D 5.3.1f1 + GoogPlayPlug0.9.27a. After import appear the error.

### ISSUE THREAD

**Issue by VictorMateusSP** [playgameservices/play-games-plugin-for-unity#930]
Hi all,

Please help me. This issue is killing me.
After import appear an issue about "GoogleDependencyGoogle.GPGS". I configure Android Setup, I configure the game on console twice and..nothing. 

The log:
UnauthorizedAccessException: Access to the path "C:\Users\Victor Mateus\Desktop\Teste\Loner Archer\ProjectSettings\GoogleDependencyGoogle.GPGS.xml" is denied.
System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.IO/FileStream.cs:320)
System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share)
(wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
System.IO.StreamWriter..ctor (System.String path, Boolean append, System.Text.Encoding encoding, Int32 bufferSize) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.IO/StreamWriter.cs:124)
System.IO.StreamWriter..ctor (System.String path)
(wrapper remoting-invoke-with-check) System.IO.StreamWriter:.ctor (string)
Google.GamesJarResolver.PlayServicesSupport.PersistDependencies ()
Google.GamesJarResolver.PlayServicesSupport.DependOn (System.String group, System.String artifact, System.String version)
GooglePlayGames.BackgroundResolution.AddDependencies () (at Assets/GooglePlayGames/Editor/BackgroundResolution.cs:58)
GooglePlayGames.BackgroundResolution..cctor () (at Assets/GooglePlayGames/Editor/BackgroundResolution.cs:45)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for GooglePlayGames.BackgroundResolution
System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (RuntimeTypeHandle type) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101)
UnityEditor.EditorAssemblies.ProcessEditorInitializeOnLoad (System.Type type) (at C:/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:123)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:519)
System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:528)
System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/ConstructorInfo.cs:77)
System.Activator.CreateInstance (System.Type type, Boolean nonPublic) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Activator.cs:372)
System.Activator.CreateInstance (System.Type type) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Activator.cs:254)
UnityEditor.AssetPostprocessingInternal.GetMeshProcessorVersions () (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:145)
UnityEditor.AssetPostprocessingInternal:GetMeshProcessorVersions()

**Comment by claywilkinson** [comment]
Can you check the permissions of C:\Users\Victor Mateus\Desktop\Teste\Loner Archer\ProjectSettings\GoogleDependencyGoogle.GPGS.xml?  Is it read-only?  If so, it should be writable.

**Comment by VictorMateusSP** [comment]
Hi @claywilkinson !
Sorry, but how can check? :/

**Comment by VictorMateusSP** [comment]
Hi @claywilkinson !
Sorry, but how can I check? :(

**Comment by claywilkinson** [comment]
In Explorer, you can go to that file and look at the properties of the file.  One of the tabs is permissions  (I don't have a windows box handy, so sorry for the high level description).

**Comment by VictorMateusSP** [comment]
@claywilkinson Thanks for description, now I know how...but...I opened the path and I didn't find the file "GoogleDependencyGoogle.GPGS.xml". =(

**Comment by claywilkinson** [comment]
Can you write to the ProjectSettings directory?  For example create the file GoogleDependencyGoogle.GPGS.xml ?  I think once the file can be created, it will be OK.

**Comment by claywilkinson** [comment]
OK to close this one?
