### ISSUE TITLE
Issue with Leaderboards not opening 

### ISSUE THREAD

**Issue by yungdbo** [playgameservices/play-games-plugin-for-unity#932]
Hello,

I tried using the leaderboard function ShowLeaderboardUI(), with the google play services and for some reason it isn't working. When I try it on my android device it just doesnt open. Below is the code Ive been using:

void Start () {
		PlayGamesPlatform.Activate ();

	}

	//Once login is successful
	public void Login(){
		Social.localUser.Authenticate ((bool success) => {
			if(success){
			} else {
			}
		});
	}

	public void Leaderboard(){
		((PlayGamesPlatform)Social.Active).ShowLeaderboardUI (leaderboard);
	}

	public void MainMenuSelector(){
		Application.LoadLevel (0);
	}

Please help me! I need this for my alpha testers so they can track their progress. Also, is it possible on the developer console that I havent enabled it for my testers? 

Thanks,

D

**Comment by claywilkinson** [comment]
Many things are possible :)  Can you share a log of the what is happening?

**Comment by loftyy** [comment]
I had an issue with this, not sure if it's related to yours but I fixed mine by removing a ReportProgress to one of my leaderboards that I had under Update(), since it was being called too frequently, my leaderboard UI wasn't showing. Maybe that's your problem? If not, try to see where you are reporting progress and see from there

**Comment by yungdbo** [comment]
That's the thing nothing opens up at all. I don't even get an option to sign in or anything.

**Comment by claywilkinson** [comment]
You definitely need to call Authenticate first.  Can you share a log of what is happening?

**Comment by yungdbo** [comment]
NullReferenceException: Object reference not set to an instance of an object
GooglePlayGames.PlayGamesPlatform.ShowLeaderboardUI (System.String lbId) (at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:921)
LeaderboardManagerScript.Leaderboard () ((at Assets/GooglePlayGames/ISocialPlatform/PlayGamesPlatform.cs:921) at(/LeaderboardManagerScript.cs:38)

**Comment by yungdbo** [comment]
Then takes me to this function when I click it:

 public void ShowLeaderboardUI(string lbId)
        {
           if (lbId != null)
            {
                lbId = MapId(lbId);
            }

            mClient.ShowLeaderboardUI(lbId, LeaderboardTimeSpan.AllTime, null);
        }

**Comment by claywilkinson** [comment]
Did you sign in successfully?  that looks like mClient is null? Which means that Authenticate() was not called.

**Comment by yungdbo** [comment]
Authenticate gets called whenever I press my login button, but it doesnt even give me the option to sign in. It just says this:

 [Play Games Plugin DLL] 01/29/16 14:02:10 -06:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform

**Comment by claywilkinson** [comment]
Hmm - so Login() is not being called?  Maybe add some debugging there.  You can also build the Cubic pilot sample which includes signin and a leaderboard.

**Comment by yungdbo** [comment]
I mean I have a text in there for the if statement for if it was successful or not and it was I just dont know why the UI for me to login with my email address doesnt pop up. Am I missing something that should be included?

**Comment by yungdbo** [comment]
This ticket can be closed. Finally figured it out.

**Comment by claywilkinson** [comment]
Great!

**Comment by DynamoidMegan** [comment]
@yungdbo What was the issue? I am having the exact same problem, got here by googling the error message.

**Comment by timendez** [comment]
@yungdbo please! dont leave us hanging!

**Comment by yungdbo** [comment]
I basically had to authenticate first before I could get to my leaderboard and you have to define it globally or it could be defined in one instance and not the other.

**Comment by timendez** [comment]
Thanks man, that was it with me too! I just had left out the authenticate and initialization code :)
