### ISSUE TITLE
Realtime Multiplayer suddenly not joining/creating a room, anyone else?

### ISSUE THREAD

**Issue by loftyy** [playgameservices/play-games-plugin-for-unity#933]
Is anyone else having this issue? I can't create a room or join one anymore. Simply nothing happens. I haven't touched my code which was working perfectly a few hours ago. I even went back on my old back up project (which i'm 100% sure had a working real time multiplayer) but when I try to join a game, nothing happens. I have not modified my google play plugin settings nor have I changed any settings on the publisher page on Google developper console ... I also have a 2nd button which allows the player to invite someone from their circle which is working quite fine...

The only warning i get in the console is :
```
Android Jar Dependencies: Resolution Complete
UnityEngine.Debug:Log(Object)
GooglePlayGames.BackgroundResolution:OnPostprocessAllAssets(String[], String[], String[], String[]) (at Assets/GooglePlayGames/Editor/BackgroundResolution.cs:110)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
```

**Function called after button press (No response) : **

```

 public void JoinAGame()
    {
        if (Social.localUser.authenticated)
        {
            CreateorJoinRoom();
        }


        if (!Social.localUser.authenticated)
        {
            CreateAGame = true;
            Login(); // function which makes user login then called CreateorJoinRoom();
        }
    }



    public void CreateorJoinRoom()
    {
        const int MinOpponents = 1;
        const int MaxOpponents = 1;
        const int GameVariant = 0;

        PlayGamesPlatform.Instance.RealTime.CreateQuickGame(MinOpponents, MaxOpponents, GameVariant, this);

    }

    private bool showingWaitingRoom = false; // Used to not repeat waiting UI every progress.
    public void OnRoomSetupProgress(float progress)
    {
        if (!showingWaitingRoom)
        {
            showingWaitingRoom = true;
            PlayGamesPlatform.Instance.RealTime.ShowWaitingRoomUI();
        }
    }
```

*Function which invites player (Google Play UI opens):*

```
public void InviteAFriend()
    {
        if (Social.localUser.authenticated)
        {
            Invite();
        }

        if (!Social.localUser.authenticated)
        {
            InviteSomeone = true;
            Login();
        }
    }

    public void Invite()
    {
        const int MinOpponents = 1, MaxOpponents = 1;
        const int GameVariant = 0;
        PlayGamesPlatform.Instance.RealTime.CreateWithInvitationScreen(MinOpponents, MaxOpponents, GameVariant, this);
    }
```

**Comment by claywilkinson** [comment]
Can you share the log of what is happening?

**Comment by loftyy** [comment]
Where/how can I obtain it?

**Comment by loftyy** [comment]
Update: I was suspecting my student WiFi to be the issue since I was running too many devices on my WiFi account which messed with my Internet speed.Switched my WiFi when I went to uni and it's working fine now...

**Comment by claywilkinson** [comment]
Great to hear it is working now.  For reference, you can get a log from the device using [Logcat](http://developer.android.com/tools/help/logcat.html).  It is super-valuable in diagnosing issues and bugs.
