### ISSUE TITLE
[Prime31] GoogleCloudMessaging + PlayGameServices

### ISSUE THREAD

**Issue by adisanto** [playgameservices/play-games-plugin-for-unity#934]
Hi, we are currently trying to user thus 2 plugin at the same time. When building, there is no conflict and everything is fine. But when we try to use some methodes from the GloudCloudMessenging plugin, we have some error on android :

`AndroidJavaException: java.lang.NoSuchMethodError: no static method
with name='instance' signature='()Ljava/lang/Object;' in class
Lcom/prime31/GoogleCloudMessagingPlugin;`

Do you know what could be the problem between thus 2 plugins please?

**Comment by claywilkinson** [comment]
The class com/prime31/GoogleCloudMessagingPlugin is definitely not from Google :) . I'd suggest following up with Prime31 first.  The fact it builds OK, I doubt it is any conflict between the plugins.
