### ISSUE TITLE
Please add IFDEF!

### ISSUE THREAD

**Issue by JEOptimal** [playgameservices/play-games-plugin-for-unity#935]
Currently it's a real pain to use the plugin for projects that are intended for multiple platforms.

This would be easily solved if the plugin would just use #if UNITY_ANDROID || UNITY_IOS in the source files.

**Comment by claywilkinson** [comment]
Which files are you referring to?  What pain are you experiencing?

**Comment by JEOptimal** [comment]
Our builds target both android/ios/windows store and steam. When adding google play games we get lots of build errors when building for windows store for example.

So it would be extremely good if the google play games code is wrapped for the supported platforms.
Instead of us doing it for every new released version.

Best Regards

**Comment by claywilkinson** [comment]
We'll add it to the list.  Feel free to submit a pull request with the updates.

**Comment by JEOptimal** [comment]
Thanks! That will really help us!

**Comment by claywilkinson** [comment]
This is added in latest update - 0.9.31.  Thanks again for the feedback.

**Comment by JEOptimal** [comment]
Wow, thanks! That was fast.
