### ISSUE TITLE
0.9.30 Not working with AdMob

### ISSUE THREAD

**Issue by myertha** [playgameservices/play-games-plugin-for-unity#938]
Similar to a thread back in 0.9.27 where this would delete google-play-services_lib folder from Assets/Plugins/Android. Unfortunately, the-work around with adding `svcSupport.DependOn("com.google.android.gms", "play-services-ads", "8.1+");` to BackgroundResolution.cs is not doable because there is no such file.

I tried commenting out 
`                // remove the massive play services client lib
                string clientDir = "Assets/Plugins/Android/google-play-services_lib";
                GPGSUtil.DeleteDirIfExists(clientDir);`

but that caused me other issues with Manifests.

I noticed the SampleDependencies.cs. I tried following the instructions but can you provide the proper code for use with AdMob? I tried every work around I can find in many of the forums, but no luck. I would even take an older working build if possible.

**Comment by BrinerLovo** [comment]
Hi.

I have this problem too, for fix it I have do this:

 delete the 'google-play-services_lib' and
add this line:
`svcSupport.DependOn("com.google.android.gms","play-services-ads",PluginVersion.PlayServicesVersionConstraint);`
on GPGSDependencies script function GPGSDependencies.
also in the 'AndroidManifest.xml' of 'GoogleMobileAdsPlugin' folder replace these lines:
```
    <!-- Denote the referenced Google Play services version -->
    <meta-data android:name="com.google.android.gms.version"
        android:value="@integer/google_play_services_version" />
    <!-- Google Mobile Ads Activity -->
    <activity android:name="com.google.android.gms.ads.AdActivity"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"/>
    <!-- InAppPurchase Activity -->
    <activity android:name="com.google.android.gms.ads.purchase.InAppPurchaseActivity"
        android:theme="@style/Theme.IAPTheme"/>
```
with this:
```
   <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ YOUR_APP_ID"/>
    <meta-data android:name="com.google.android.gms.appstate.APP_ID" android:value="\ YOUR_APP_ID"/>
```
where YOUR_APP_ID is the id of your application on the google developer console of your service application.

I have test and both plugins work correctly, Hope this help you.
Kind Regards.

**Comment by talhaHavadar** [comment]
@BrinerLovo you right i can build successfully after change code but now i can not see my banner ads on game anymore.

**Comment by myertha** [comment]
@BrinerLovo You my friend... I absolutely adore you... and I mean that in the best possible way... I've been working on this issue since 0.9.30 released. Every waking hour I had was used to pull out all my hair on this. I've tested both Interstitial and Banner with the latest Google Play Services and they all work exceptionally well. Thank you again my friend!

@talhaHavadar  Are you sure there are even banner ads to be served to your device? I've seen both live and test ads with no issues.

**Comment by Disar** [comment]
I added the dependency but Im not working with Admob directly but with neatplugs admob. Getting a merge conflict now 

  Error building Player: CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
  C:\Program Files (x86)\Java\jdk1.8.0_25\bin\java.exe -Xmx1024M -Dcom.android.sdkmanager.toolsdir="C:/Users/SidarTaleiVascoGames/Documents/Development/Android/SDK\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity5.3.1p3\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

  stderr[
  Error: [Temp\StagingArea\AndroidManifest-main.xml:13, C:\Users\SidarTaleiVascoGames\Documents\Development\Unity\GooglePlayNeat\Temp\StagingArea\android-libraries\play-services-ads-8.4.0\AndroidManifest.xml:10] Trying to merge incompatible /manifest/application/activity[@name=com.google.android.gms.ads.AdActivity] element:
    <activity
  --    @android:name="com.google.android.gms.ads.AdActivity">
  --</activity>
  --(end reached)
    <activity
  ++    @android:name="com.google.android.gms.ads.AdActivity"
  ++    @android:theme="@android:style/Theme.Translucent">
  ++</activity>
  ]
  stdout[
  [Temp\StagingArea\AndroidManifest-main.xml:14, C:\Users\SidarTaleiVascoGames\Documents\Development\Unity\GooglePlayNeat\Temp\StagingArea\android-libraries\MainLibProj\AndroidManifest.xml:16] Skipping identical /manifest/application/meta-data[@name=com.google.android.gms.version] element.
  [Temp\StagingArea\AndroidManifest-main.xml:14, C:\Users\SidarTaleiVascoGames\Documents\Development\Unity\GooglePlayNeat\Temp\StagingArea\android-libraries\play-services-basement-8.4.0\AndroidManifest.xml:5] Skipping identical /manifest/application/meta-data[@name=com.google.android.gms.version] element.
  ]

**Comment by talhaHavadar** [comment]
@myertha yes i can see my banner ads before importing GPG plugin. I dont know why ads not showing. I have adUnitID for banner I also attach script to my mainCamera but nothing happened

**Comment by claywilkinson** [comment]
Admob plugin was just updated to version 3.0.0 - This version is compatible with this plugin.
https://github.com/googleads/googleads-mobile-unity

**Comment by Disar** [comment]
@claywilkinson Will the process be automated or do you still need to add dependencies?

**Comment by claywilkinson** [comment]
I believe the dependencies will be added automatically.

**Comment by talhaHavadar** [comment]
@claywilkinson Thanks for information
