### ISSUE TITLE
Question: Achievements with multiple apps on the same device.

### ISSUE THREAD

**Issue by DuckOfDoom** [playgameservices/play-games-plugin-for-unity#940]
We're developing multiple apps simultaneously and they are sometimes being tested on the same device. Let's say we have two apps, they both use this plugin but they have different bundle IDs.

Sometimes, after installing and testing these apps on the same device(namely Samsung Galaxy S6, with Android 5.1.1) in random order, there is an issue that one of the apps(app1) gets antother(app2's) achievement list (no idea how to word this properly, sorry for that). Not only GPG plugin fails to report progress for any of achievements for app1(because achievement IDs are hard-coded), but also when a user tries to view achievements(both via Play Games app or by using plugin's "ShowAchievements()" method), he sees achievements that belong to app2, instead of correct achievements for app1.

I'm not sure that this bug has something to do with this specific plugin but I didn't find any info about it so maybe you can shed some light on what might be happening and what we're doing wrong.

Both apps are in alpha testing phase.

Thanks in advance.

**Comment by claywilkinson** [comment]
The bundle ID is used as part of the authentication process, in concert with the SHA1 fingerprint.  The app_id is what controls which game configuration is used. Do they have different app ids?  This is configured on the Play Games console, and part of the resources file pasted into the Setup dialog for the plugin.

**Comment by DuckOfDoom** [comment]
@claywilkinson Thanks a lot for your answer. Each app has its own app id, I double checked it both in Unity after plugin setup and in resulting APKs.

**Comment by DuckOfDoom** [comment]
It's also worth mentioning that leaderboards are correct and are working as intended.

**Comment by claywilkinson** [comment]
Can you share a log of the app/achievement mismatch problem?

**Comment by claywilkinson** [comment]
Please re-open if this is still an issue to work on.
