### ISSUE TITLE
Heyzap + Admob + Google unity plugin = help me 

### ISSUE THREAD

**Issue by natysoz** [playgameservices/play-games-plugin-for-unity#941]
ok it goes like this

my game include Google Play Services Unity plugin , it working (using for Leaderboard and stuff )

i decide go with Heyzap Mediation and use Facebook+ChartBoost +Admob 

Facebook and Chartboost working fine while....Admob is not.

in the Heyzap plugin , all u have to do to get Admob SDK is click install then its installing a folder
name
" google-play-services_lib "  Inside there is > Libs & res & src & AndroidManifest

now when i try building my game i get huge errors on the stage "Repacking" while building .

i know its kinda overlap , gps use "MainLibProj" 

What should i do ? each time i try Build , unity also delete the " google-play-services_lib " again and again , and i need it becuse inside there is the jar that support Admob :(

**Comment by claywilkinson** [comment]
The admob plugin has been updated to 3.0.0.  It is now compatible with this plugin: https://github.com/googleads/googleads-mobile-unity

**Comment by hermanjakobi** [comment]
@natysoz When you hit "Android Setup" in Heyzap's Unity plugin they copy your Google Play Services Library which you have installed into the Unity project. The "old" Google Mobile Ads plugin didn't worked with Google Play Services since 0.9.25.

Will test if it works with the latestGoogle Play Services  0.9.30 and Google Mobile Ads 3.0.0

**Comment by claywilkinson** [comment]
OK to close this issue?

**Comment by hermanjakobi** [comment]
Close it. 

Heyzap works with Google Play Services 0.9.30 and Google Mobile Ads 3.0.0.

**Comment by claywilkinson** [comment]
Good to hear.  Thanks.
