### ISSUE TITLE
ArgumentNullException on Exploding arr files if JAVA_HOME is not set

### ISSUE THREAD

**Issue by FrankNine** [playgameservices/play-games-plugin-for-unity#942]
It seems PlayServiceResolver is trying to locate jar.exe with JAVA_HOME environment variable on Windows machines. And if JAVA_HOME is not set, Path.Combine would throw ArgumentNullException. It took me a while to track down this issue. I wounder whether we could have a nice error message asking users to check their environment settings. Thank you.

**Comment by claywilkinson** [comment]
Thanks for the feedback.

**Comment by claywilkinson** [comment]
I updated the plugin to version 0.9.31 and checked for JAVA_HOME being set.  Thanks again for the feedback.
