### ISSUE TITLE
Any way to set the Version when creating a TurnBasedMatch?

### ISSUE THREAD

**Issue by Dynamiek108** [playgameservices/play-games-plugin-for-unity#943]
Is there a way to set the Version uInt of the Turnbasedmatch when creating it?

Or: What is the Version setting in the TBM for?

**Comment by claywilkinson** [comment]
I believe the version is set internally and represents the iteration of the match.  so the first player plays with version 1, then the next turn is version 2, and so on.

Why do you want to set it?

**Comment by Dynamiek108** [comment]
Ah great, thanks for the info!

I thought its kind of like a version control.... for example if I change the structure of the Match.Data to see if the two versions are still compatible.

I now check it in the game itself, thanks!
