### ISSUE TITLE
Question about Visibility of other Players in the UI

### ISSUE THREAD

**Issue by Dynamiek108** [playgameservices/play-games-plugin-for-unity#944]
Hi!

Sorry if my questions are dumb, but it's really my first time using GooglePlay and I don't know if I am doing it all right. All this concerns TurnBasedMultiplayer.

When Player One creates a Quick Match and Player Two gets matched to it, Player One appears with the name "Player 9668" or something.
I can understand that, because it keeps the privacy and so forth, but even when both players know each other (= are friends on google) the naming is kept this way!

Is this the way it should be, or am I doing something wrong?

And is there a way to actually show the name of the player?
When starting many games its impossible to keep track of who is who if you are just playing by QuickMatch and all the names are numbers. (and they change even if I got matched to the same guy)

The only way I see around it is to save the Infos of the Player to the Match.Data and build my own UI where I show the names when I have them.
Is this good practice in the means of privacy or whats the way you do it?

Thanks in advance for any advice on the topic!

**Comment by claywilkinson** [comment]
The new gamer profile functionality addresses this problem.  The gamer tag is shown provided the player has a public profile.
