### ISSUE TITLE
 Failed to re-package resources in version 0.9.30

### ISSUE THREAD

**Issue by anhld4** [playgameservices/play-games-plugin-for-unity#946]
Hi All,

I have issue  with play game plugin version 0.9.30.

I try to build and run my game. I got the log: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
D:\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\23.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "D:/android-sdk_r24.4.1-windows/android-sdk-windows\platforms\android-21\android.jar" -F bin/resources.ap_ --extra-packages com.google.unity:com.google.example.games.mainlibproj

After that I copy google-play-services_lib from android SDK to Assets\Plugins\Android and re-build my game. It worked fine but google-play-services_lib folder is removed.

Finally I re-build my game and got the log Failed to re-package resources again.

Please help me fix this issue!

**Comment by Disar** [comment]
So from my experience so far PGP copies the dependencies from the google sdk. So any other lib of google sdk should be removed. google-play-services_lib is one of those that get discarded in favor of the latest sdk AAR files.

I can only suggest you update your build tools in the android sdk manager.

**Comment by claywilkinson** [comment]
You should not copy google-play-services_lib to your project.  This overlaps with the .aar files.

**Comment by anhld4** [comment]
@Disar I tried all of build tools. But can not fix this issue :(

**Comment by Disar** [comment]
What api level are you targetting in the unity player settings?

**Comment by claywilkinson** [comment]
What resources are causing the error?  That will help diagnose the issue.

**Comment by anhld4** [comment]
@Disar I set minimum api level is 9

**Comment by Disar** [comment]
@anhld4 as clay asked, what resources/plugins are you trying to use beside this one?

**Comment by anhld4** [comment]
I'm using admob unity plugin in my game

**Comment by anhld4** [comment]
I don't know exactly solution. But I upgrade admob to v3.0.0 and update latest android sdk. This issue fixed. Thanks for support!

**Comment by claywilkinson** [comment]
Great!  Thanks for the update.
