### ISSUE TITLE
Failed to repackage after adding google play games plugin

### ISSUE THREAD

**Issue by siddharth3322** [playgameservices/play-games-plugin-for-unity#947]
Recently I have added Google Play Games Plugin v 0.9.30 and this I have recently downloaded from github.

My unity version is 4.6.9p1 and SDK installed upto v23.

In unity, I am getting following error when I try to generate build.

> Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Sdk\build-tools\23.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Sdk/platforms/android-23\android.jar" -F bin/resources.ap_ --extra-packages com.google.android.gms:com.google.unity:com.google.example.games.mainlibproj:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.plus:android.support.v4 -S "E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\google-play-services_lib\res" -S "E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\res" -S "E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\play-services-base-8.4.0\res" -S "E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\play-services-basement-8.4.0\res" -S "E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\play-services-drive-8.4.0\res" -S "E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\play-services-games-8.4.0\res" -S "E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\play-services-nearby-8.4.0\res" -S "E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\play-services-plus-8.4.0\res" -S "E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\support-v4-23.1.1\res"

stderr[
E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\base_attrs.xml:11: error: Attribute "buttonSize" has already been defined

E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\base_attrs.xml:16: error: Attribute "colorScheme" has already been defined

E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\base_attrs.xml:21: error: Attribute "scopeUris" has already been defined

E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\common_attrs.xml:13: error: Attribute "imageAspectRatioAdjust" has already been defined

E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\common_attrs.xml:22: error: Attribute "imageAspectRatio" has already been defined

E:\Siddharth\Projects\HotWings\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\common_attrs.xml:27: error: Attribute "circleCrop" has already been defined

]
stdout[

I have just pasted major part over but list is not completed. Please guide me to come out of this.

**Comment by siddharth3322** [comment]
I have already gone through this link

[https://github.com/playgameservices/play-games-plugin-for-unity/issues/895#issuecomment-172799808](url)

**Comment by siddharth3322** [comment]
The above error into more readable format:
[https://www.dropbox.com/s/k36w0ym83b0k6x4/GPGError.png?dl=0&preview=GPGError.png](url)

**Comment by AaronDevGame** [comment]
Hi @siddharth3322 ,

Mine was fixed after updating these 2 to its latest version.
- Android Support Repository
- Google Repository

**Comment by claywilkinson** [comment]
You should not have google-play-services_lib\ in your project any longer.  This library overlaps with the .aar files.

**Comment by siddharth3322** [comment]
My android library was already updated with latest Android Support Repository and Google Repository.

I have also tried last opinion of removing google-play-services_lib directory from project but this also can't able to solve my problem.

**Comment by siddharth3322** [comment]
yes by removing, google-play-services_lib folder from project now I have no error as well my google play games working correctly.

But now I am facing other issue related to admob ad, now admob ad is not working because removal of above folder.
I am getting this message on screen:

02-03 20:52:17.055 7152-7167/? I/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.AdSize
                                          at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
                                          at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0 
                                          at UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
                                          at UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
                                          at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x00000] in <filename unknown>:0 
                                          at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) [0x00000] in <filename unknown>:0 
                                          at UnityEngine.AndroidJavaObject..ctor (System.String className, System.Object[] args) [0x00000] in <filename unknown>:0 
                                          at GoogleMobileAds.Android.Utils.Get

**Comment by claywilkinson** [comment]
Good news! Admob updated their plugin to use the same jar resolver: https://github.com/googleads/googleads-mobile-unity

**Comment by siddharth3322** [comment]
there is no difference in output. I have removed plugin completely and then added new one but getting same above error.

**Comment by siddharth3322** [comment]
even admob delegates stopped working after adding new admob 3.0

**Comment by claywilkinson** [comment]
Can you check that it added the play-services-ads-8.xxx.aar to Android Plugins?  Did you post an issue on the admob repository?

**Comment by siddharth3322** [comment]
Yes they have added play-services-ads-8.4.0.aar file.

I have already added post over there.
[https://github.com/googleads/googleads-mobile-unity/issues/159](url)

**Comment by siddharth3322** [comment]
I have deleted all plugins from game- admob and google play service.
downloaded latest version from store and import into project.

but now I have admob banner working correctly but can't able to authenticate google play service for me. even nothing happen in device screen. I have uploaded image of log data I am getting.

[https://www.dropbox.com/s/1s91t2icgkdzvq9/Screen%20Shot%202016-02-04%20at%202.10.25%20PM.png?dl=0&preview=Screen+Shot+2016-02-04+at+2.10.25+PM.png](url)

**Comment by claywilkinson** [comment]
Make sure you update the Android Support Repository to the latest version in the Android SDK Manager.  It is in the "extras" section. (Also make sure the Google Repository is also updated).

**Comment by siddharth3322** [comment]
these 2 are already updated by me and latest version exist.

**Comment by siddharth3322** [comment]
whether I need to copy google-play-game_lib folder or not?
if I don't do this then getting another error.

**Comment by siddharth3322** [comment]
if you say then I can move ahead from scratch as well by removing all plugins then integrate one by one above 2 as per my requirements.

**Comment by siddharth3322** [comment]
at present admob ad is working in game but there is no authentication screen for login come on screen.

**Comment by Loony04** [comment]
I created new project in unity, downloaded GoogleMobileAds.package, imported, demo script, changed  adUnitIds and InterstitialAd is working, but Banner doesn't. I receive log "HandleFailedToReceiveAd event received with message: No fill", or "internal error". What is going on?

**Comment by claywilkinson** [comment]
@Loony04 - Did you post this in the admob repository issues?  They are more likely to be able to help.
