### ISSUE TITLE
Hangs on "Importing Small Assets"

### ISSUE THREAD

**Issue by cluckeyetea** [playgameservices/play-games-plugin-for-unity#948]
Hey Gurus!

I've tried quite a few times now to update to the latest version of the plugin. Every time I walk through the upgrade path when I click the Google Play Games Activate option I get an importing dialog that eventually hangs on "importing small assets".

I've tried at least 4 times now from scratch so I'm not sure what could be the issue other than I am not running Unity 5.x but rather 4.7. I'd appreciate any help if at all possible. I really wanted to take advantage of the waiting room feature in the plugin but updating the project to Unity 5 wrecks it entirely.

Thanks!

**Comment by claywilkinson** [comment]
Have you checked with Unity or can determine the asset causing the issue?  I've never heard of the plugin causing hanging on import.  The plugin should work fine on 4.7

**Comment by cluckeyetea** [comment]
The issue is the jarresolver code. Perhaps it is an issue only because I am on a MAC? When I open file explorer I see in the asset/plugin/ directory that the plugin is continually exploding and then deleting the GPGS AAR files. Disabling the jarresolution code allowed me to import my project. I then just manually copied the AAR files over myself and am up and running. It's probably something worth looking into though. Thanks for the quick response.

**Comment by claywilkinson** [comment]
Which exact version of Unity are you running?

Being on a mac should be fine.  It sounds like a quirk on when the assets updated event is fired in 4.7.  You can disable the automatic importing by modifying Assets/Editor/PlayServicesResolver/Editor/PlayServicesResolver.cs and comment out the contents of OnPostprocessAllAssets() (line 86).

You can manually update the dependencies via the menu, Assets > Google Play Services > Resolve Client Jars.

I'll make a note to look at this and make it not loop :+1:

**Comment by cluckeyetea** [comment]
Cool. If it helps its Unity (v)4.7.0f.1

**Comment by claywilkinson** [comment]
Thanks again.  I have updated the plugin to version 0.9.31 and it no longer loops - I also added a setting to be able to turn off the background resolution.
