### ISSUE TITLE
Upgrading to GPGS 0.9.30/Unity 5.3.1 causes issues on missing support v4/app-compat jars

### ISSUE THREAD

**Issue by fra9000** [playgameservices/play-games-plugin-for-unity#949]
Updrading to GPGS 0.9.30/Unity 5.3.1 I'm experiencing a new issue never met before on my android game:

Google.JarResolver.ResolutionException: Cannot find candidate artifact for com.android.support:support-v4:23.1.0+
  at Google.JarResolver.PlayServicesSupport.DependOn (System.String group, System.String artifact, System.String version) [0x00000] in <filename unknown>:0 
  at GooglePlayGames.Editor.GPGSDependencies..cctor () [0x00063] in D:\Projects\...\Assets\GooglePlayGames\Editor\GPGSDependencies.cs:60 
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

I have Android Support Library installed from SDK manager.

I have not managed to fix it in any way.

Something you guys could fix?
Thank you in advance. Any help appreciated.

**Comment by claywilkinson** [comment]
You'll need to update the Android SDK to include the latest artifacts.  You can do this from Unity via Window > Google Play Games > Downloads > Google Play Games SDK (Android)...  You'll want to update the Google Repository and Android Support repository (in the Extras section).

**Comment by fra9000** [comment]
Hi Clay,

Thank you for your quick answer. Yes that fixed it. I was missing the "Android Support Repository".
Maybe could be good to add it explicitelly into the guide section?

Thank you for the professional support you are doing here.

BR
Palmylab

**Comment by claywilkinson** [comment]
Great point! I'll update the documentation.

**Comment by vanshikakapoor** [comment]
I am facing the same problem, could not update anything. Please help.

**Comment by slole** [comment]
I have installed all the required packages but I am still getting errors as if I have no packages installed whatsoever.
