### ISSUE TITLE
Waiting Room UI Doesn't Publish Cancel Event

### ISSUE THREAD

**Issue by cluckeyetea** [playgameservices/play-games-plugin-for-unity#951]
Hey Again,

This is pretty minor but on other platforms where I use GPGS when the player in the waiting room backs out I get the OnLeaveRoom event. I went ahead and modified your NativeMultiplayerRealtimeClient.cs file to handle this but maybe another item to think about including in a future release.

Regards!

internal override void ShowWaitingRoomUI (uint minimumParticipantsBeforeStarting)
            {
                mSession.ShowingUI = true;
                mSession.Manager ().ShowWaitingRoomUI (mRoom, minimumParticipantsBeforeStarting, response =>
                {
                    mSession.ShowingUI = false;
                    Logger.d ("ShowWaitingRoomUI Response: " + response.ResponseStatus ());
                    if (response.ResponseStatus () == Status.UIStatus.VALID) {
                        Logger.d ("Connecting state ShowWaitingRoomUI: room pcount:" + response.Room ().ParticipantCount () +
                            " status: " + response.Room ().Status ());
                        if (response.Room ().Status () == Types.RealTimeRoomStatus.ACTIVE) {
                            mSession.EnterState (new ActiveState (response.Room (), mSession));
                        }
                    } else if (response.ResponseStatus () == Status.UIStatus.ERROR_LEFT_ROOM || 
                        **response.ResponseStatus () == Status.UIStatus.ERROR_CANCELED**) {
                        LeaveRoom ();
                    } else {
                        mSession.OnGameThreadListener ().RoomSetupProgress (this.mPercentComplete);
                    }
                });
            }
        }

**Comment by claywilkinson** [comment]
Thanks for the suggestion!
Which other platforms are you referring to? There is an argument to be made for both, perhaps the best solution is to have a flag on ShowWaitingRoomUI indicating leave room if canceled?

**Comment by cluckeyetea** [comment]
The flag is a great idea. When I said other platforms I meant I use the corona sdk as well and this is how waiting room ui is handled both for gpgs and apple game center by their plugin.

**Comment by ozdemir08** [comment]
Thanks for your question. Play Games Services multiplayer system has been deprecated (see [this notice](https://support.google.com/googleplay/android-developer/answer/9469745)), so we are closing this issue.
