### ISSUE TITLE
TurnBasedMatch.self is null when match is obtained from play games interface

### ISSUE THREAD

**Issue by ghost** [playgameservices/play-games-plugin-for-unity#952]
Both the TurnBasedMatch.Self and TurnBasedMatch.SelfParticipantID are returning null in the MatchDelegate call when my game is started via the Play Games interface in Android. If the game is already running and then the Play Game interface is used on open it, they are set correctly. 

The status of the match is active and its my turn. 
We are using 0.9.30 version.

The Problem:
    void OnGotMatch(TurnBasedMatch match, bool shouldAutoLaunch)
    {
        Debug.Log(match.SelfParticipantId); //Null if called early in game startup for an active game where its my turn

```
    Debug.Log(match.Self); //Also Null
}
```

Initialization Code:
        PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
            // enables saving game progress.
            .EnableSavedGames()
            // registers a callback to handle game invitations received while the game is not running.
            .WithInvitationDelegate(OnInvitationReceived)
            // registers a callback for turn based match notifications received while the
            // game is not running.
            .WithMatchDelegate(OnGotMatch)
            // require access to a player's Google+ social graph to sign in
            .RequireGooglePlus()
            .Build();

```
    PlayGamesPlatform.InitializeInstance(config);
    // recommended for debugging:
    PlayGamesPlatform.DebugLogEnabled = GameController.Instance.DebugVersion;
```

Authentication is done not long after and early in the start up cycle of the game.
        PlayGamesPlatform.Instance.Authenticate((bool success) =>
        {
            mAuthenticateSuccess = success;
        }, silent);

**Comment by richo88** [comment]
Tested on TicTacToe sample and its broken here as well.

Steps to replicate problem:
Start a tictactoe game and after a turn shut down the app. Take a turn on the opposing device and when the turn notification is received via the notification panel on the first device, click it to start your turn. The app will start successfully but when you take your turn it will either crash or bring up an error dialog. If you then reload that game via the inbox it will still be your turn even thought a turn has been taken.

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
