### ISSUE TITLE
Unable to Leave Match

### ISSUE THREAD

**Issue by Dynamiek108** [playgameservices/play-games-plugin-for-unity#953]
Hi!

I am building my own Turnbased UI right now and I am missing a method to Dismiss the match:
When trying Leave() on a completed match the Error: "Error_INACTIVE_MATCH" occurs.

I did not find any method to dismiss the match when the user wants to remove it!

Please Help!

**Comment by Dynamiek108** [comment]
Would be really nice if you could implement the methods for DismissMatch and for CreateMatch (when you know the UserID) in the TBM.

Otherwise it is impossible to create even partially your own interface!

Thanks!

**Comment by claywilkinson** [comment]
I am not quite sure what you are asking for.  There can be multiple matches per player, right? Please feel free to change/enhance the interface and submit a pull request.  That is most likely the fastest way to get the functionality you are looking for.

**Comment by Dynamiek108** [comment]
Thank you for your Reply!

Great I will do that and send a request with the changes soon!
...Its my first time on GitHub so I didn't know that anyone can participate ;)

DismissMatch is for deleting the game from the server and your own Interface if you don't want to see it anymore and before there was no public method to Create a Match if you have the PlayerID (it was only possible through the built-in UI)

Thanks!

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
