### ISSUE TITLE
Exception: EntryPointNotFoundException: GameServices_FetchServerAuthCode

### ISSUE THREAD

**Issue by RodGreen** [playgameservices/play-games-plugin-for-unity#955]
Any idea what might be causing this?
I'm unable to get the ServerAuthCode as it causes a crash.

```
EntryPointNotFoundException: GameServices_FetchServerAuthCode
GooglePlayGames.Native.PInvoke.GameServices.FetchServerAuthCode (System.String server_client_id, System.Action`1 callback)
GooglePlayGames.Native.NativeClient.GetServerAuthCode (System.String serverClientId, System.Action`2 callback)
GooglePlayGames.PlayGamesPlatform.GetServerAuthCode (System.Action`2 callback)
GooglePlayGamesManager.AuthenticateResult (Boolean success)
GooglePlayGames.Native.NativeClient+<InvokeCallbackOnGameThread>c__AnonStorey61`1[System.Boolean].<>m__21 ()
GooglePlayGames.OurUtils.PlayGamesHelperObject.Update ()
```

**Comment by claywilkinson** [comment]
This is because of an old C++ SDK library?  Make sure that the you have the latest libgpg.so (and only one per directory) in Assets/Plugins/Android/libs/armeabi-v7a and Assets/Plugins/Android/libs/x86

**Comment by RodGreen** [comment]
Thanks for the help that fixed it. Also as a note I followed the update instructions but seems they weren't updated? Did I miss something?
To fix I deleted the files and reimported the package and just included those two files.
