### ISSUE TITLE
CommandInvokationFailure: Failed to build apk.

### ISSUE THREAD

**Issue by pzeronow** [playgameservices/play-games-plugin-for-unity#956]
I had this #866 Google.GamesJarResolver.ResolutionException issue which I solved by updating Google and Android repositories from the Android SDK manager. Now I'm getting the following:

CommandInvokationFailure: Failed to build apk. See the Console for details.
D:/Program Files/Java/jdk1.8.0_71\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="D:/Program Files/Android/android-sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error: Not a file 'D:\Game
]
stdout[

]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.HostView:OnGUI()

I noticed that normally, after solving issue #866, it evolves into issue #867, however, mine doesn't say "Failed to re-package resources", but "Failed to build apk". Any chance someone else is having this and knows of a viable solution?

My repositories are updated to 25 (Android) and 29 (Google Play Services).

**Comment by pzeronow** [comment]
now I can't even build my .apk at all even though I removed everything related to this plugin. Nice!

**Comment by pzeronow** [comment]
Solved by making sure the keystore is selected. For whatever reason when it's not selected but you forget to type in some password instead of saying that it's not selected it just says that the password is missing (using logic it would seem safe to assume that such error message confirms that the keystore is actually selected but the password is simply missing).

**Comment by claywilkinson** [comment]
Glad you got it working!  Ok to close this one out?

**Comment by pzeronow** [comment]
please do! Thanks!

2016-02-10 3:05 GMT+01:00 Clayton Wilkinson <notifications@github.com>:
