### ISSUE TITLE
Crash After Upgrading 0.9.30

### ISSUE THREAD

**Issue by simgesimulation** [playgameservices/play-games-plugin-for-unity#957]
Hello @claywilkinson 
After I upgraded my game to 0.9.30, my game crash just after I start game. I updated android sdk, android support repository,etc to latest. Logs are as follows:

E/Unity   ( 6738): [EGL] eglGetConfigAttrib(): EGL_BAD_CONFIG: An EGLConfig argu
ment does not name a valid EGL frame buffer configuration.
E/Unity   ( 6738):
E/Unity   ( 6738): (Filename: ./Runtime/GfxDevice/egl/ConfigEGL.cpp Line: 163)
E/Unity   ( 6738):
D/Unity   ( 6738):  GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES
_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_
rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_com
pressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EG
L_image_external GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL
_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_
texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_
OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_te
xture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compre
ssion_astc_hdr GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_blend_minmax G
L_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_tex
ture_storage GL_EXT_multisampled_render_to_texture GL_OES_surfaceless_context GL
_ARM_mali_program_binary
W/ActivityManager(17139):   Force finishing activity com.SimgeSimulation.Woodbal
l/com.unity3d.player.UnityPlayerActivity
W/ActivityManager(17139): Activity pause timeout for ActivityRecord{fe0ece8 u0 c
om.SimgeSimulation.Woodball/com.unity3d.player.UnityPlayerActivity t14645 f}
W/ActivityManager(17139): mDVFSHelper.acquire()
W/ActivityManager(17139): mDVFSHelper.release()
I/Unity   ( 6738): Building GPG services, implicitly attempts silent auth
I/Unity   ( 6738):
I/Unity   ( 6738): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   ( 6738):
I/GamesNativeSDK( 6738): Auth operation started: SIGN IN
I/GamesNativeSDK( 6738): Connecting to Google Play...
I/Unity   ( 6738): Scene MainMenu is loaded
I/Unity   ( 6738):
I/Unity   ( 6738): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   ( 6738):
W/ActivityManager(17139): Launch timeout has expired, giving up wake lock!
I/GamesNativeSDK( 6738): Timed out connecting to Google Play.
I/Unity   ( 6738): Invoking callbacks, AuthState changed from silentPending to U
nauthenticated.
I/Unity   ( 6738):
I/Unity   ( 6738): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   ( 6738):
V/GamesNativeSDK( 6738): Detaching from JVM on thread main_dispatch

**Comment by simgesimulation** [comment]
Another log is here:

E/Unity   ( 7421): [EGL] eglGetConfigAttrib(): EGL_BAD_CONFIG: An EGLConfig argu
ment does not name a valid EGL frame buffer configuration.
E/Unity   ( 7421):
E/Unity   ( 7421): (Filename: ./Runtime/GfxDevice/egl/ConfigEGL.cpp Line: 163)
E/Unity   ( 7421):
D/Unity   ( 7421):  GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES
_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_
rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_com
pressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EG
L_image_external GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL
_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_
texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_
OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_te
xture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compre
ssion_astc_hdr GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_blend_minmax G
L_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_tex
ture_storage GL_EXT_multisampled_render_to_texture GL_OES_surfaceless_context GL
_ARM_mali_program_binary
W/ActivityManager(17139):   Force finishing activity com.SimgeSimulation.Woodbal
l/com.unity3d.player.UnityPlayerActivity
W/ActivityManager(17139): Activity pause timeout for ActivityRecord{91b3f6e u0 c
om.SimgeSimulation.Woodball/com.unity3d.player.UnityPlayerActivity t14647 f}
W/ActivityManager(17139): mDVFSHelper.acquire()
W/ActivityManager(17139): mDVFSHelper.release()
I/Unity   ( 7421): Building GPG services, implicitly attempts silent auth
I/Unity   ( 7421):
I/Unity   ( 7421): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   ( 7421):
I/GamesNativeSDK( 7421): Auth operation started: SIGN IN
I/GamesNativeSDK( 7421): Connecting to Google Play...
I/Unity   ( 7421): Scene MainMenu is loaded
I/Unity   ( 7421):
I/Unity   ( 7421): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 65)
I/Unity   ( 7421):
W/ActivityManager(17139): Launch timeout has expired, giving up wake lock!
I/ActivityManager(17139): Process com.SimgeSimulation.Woodball (pid 7421)(adj 0)
 has died(97,402)
W/ActivityManager(17139): mDVFSHelper.acquire()
E/ActivityManager(17139): checkUser: useridlist=null, currentuser=0
E/ActivityManager(17139): checkUser: useridlist=null, currentuser=0
E/ActivityManager(17139): checkUser: useridlist=null, currentuser=0
E/ActivityManager(17139): checkUser: useridlist=null, currentuser=0
I/ActivityManager(17139): Start proc com.SimgeSimulation.Woodball for activity c
om.SimgeSimulation.Woodball/com.unity3d.player.UnityPlayerProxyActivity: pid=748
4 uid=10557 gids={50557, 9997, 3003, 1028, 1015} abi=armeabi-v7a
I/ActivityManager(17139): do not start freezing screen for locked container getK
eyguardshowstate = false
I/ActivityManager(17139): START u0 {flg=0x10000 cmp=com.SimgeSimulation.Woodball
/com.unity3d.player.UnityPlayerActivity} from uid 10557 on display 0
W/ActivityManager(17139): mDVFSHelper.acquire()
D/ActivityManager(17139): post active user change for 0 fullscreen true record.i
sFloatingActivity() false
D/ActivityManager(17139): post active user change for 0 fullscreen true record.i
sFloatingActivity() false
I/ActivityManager(17139): Displayed com.SimgeSimulation.Woodball/com.unity3d.pla
yer.UnityPlayerActivity: +213ms (total +443ms)
W/ActivityManager(17139): mDVFSHelper.release()
E/Unity   ( 7484): [EGL] eglGetConfigAttrib(): EGL_BAD_CONFIG: An EGLConfig argu
ment does not name a valid EGL frame buffer configuration.
E/Unity   ( 7484):
E/Unity   ( 7484): (Filename: ./Runtime/GfxDevice/egl/ConfigEGL.cpp Line: 163)
E/Unity   ( 7484):
E/Unity   ( 7484): [EGL] eglGetConfigAttrib(): EGL_BAD_CONFIG: An EGLConfig argu
ment does not name a valid EGL frame buffer configuration.
E/Unity   ( 7484):
E/Unity   ( 7484): (Filename: ./Runtime/GfxDevice/egl/ConfigEGL.cpp Line: 163)
E/Unity   ( 7484):
E/Unity   ( 7484): [EGL] eglGetConfigAttrib(): EGL_BAD_CONFIG: An EGLConfig argu
ment does not name a valid EGL frame buffer configuration.
E/Unity   ( 7484):
E/Unity   ( 7484): (Filename: ./Runtime/GfxDevice/egl/ConfigEGL.cpp Line: 163)
E/Unity   ( 7484):

**Comment by claywilkinson** [comment]
The first log looks like a connectivity issue: 
`I/GamesNativeSDK( 6738): Timed out connecting to Google Play.`

The second log seems to be truncated, I don't see any error (other than the graphics calls).

**Comment by claywilkinson** [comment]
Closing since this thread has been quiet for over a year.  Please open a new issue if there is still a problem.
