### ISSUE TITLE
Exception launching token request: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment

### ISSUE THREAD

**Issue by Rainking80** [playgameservices/play-games-plugin-for-unity#958]
Hi!

I'am not able to fetch the token for my webservice. the plugin was installed correctly, the authentification is successful and i can request the players name and unique id. but requesting the token I see the following errors:
(It says class not found: com.google.games.bridge.TokenFragment - so am I missing another plugin? I have installed the latest android sdk etc.)

```
*** [Play Games Plugin DLL] 02/06/16 22:41:56 +01:00 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
02-06 22:41:56.011 8699-8729/? W/Unity:   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
02-06 22:41:56.011 8699-8729/? W/Unity:   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0 
02-06 22:41:56.011 8699-8729/? W/Unity:   at UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
02-06 22:41:56.011 8699-8729/? W/Unity:   at UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
02-06 22:41:56.011 8699-8729/? W/Unity:   at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x00000] in <filename unknown>:0 
02-06 22:41:56.011 8699-8729/? W/Unity:   at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00000] in <filename unknown>:0 
02-06 22:41:56.011 8699-8729/? W/Unity:   at UnityEngine.AndroidJavaClass..ctor (System.String className) [0x00000] in <filename unknown>:0 
02-06 22:41:56.011 8699-8729/? W/Unity:   at Goog
```

**Comment by Rainking80** [comment]
Update: I do see the same issue when using the not deprecated function: PlayGamesPlatform.GetServerAuthCode

**Comment by claywilkinson** [comment]
GetServerAuthCode is the correct solution :+1:   There are changes happening to simplify the permissions for games: http://android-developers.blogspot.com/2016/01/play-games-permissions-are-changing-in.html.

So is it OK to close this on? 

Are you calling this from the main UI thread? It might be that these java calls are happening on a different thread, which does not work.

**Comment by Rainking80** [comment]
Thank you! I did comment RunOnUiThread out by mistake, so yes it was my fault and its running now :) Please close this issue!

**Comment by claywilkinson** [comment]
Glad to hear you got it running!
