### ISSUE TITLE
Android - ReadBinaryData crashes the application 

### ISSUE THREAD

**Issue by prodigga** [playgameservices/play-games-plugin-for-unity#960]
Hey there

We are attempting to implement cloud saving features in to our game. I can write data just fine and I can even launch the save file pick UI to see that my data is there. But I can't read it back.

The debug logs do not reveal much. The last thing I get from the GPGS plugin is this:

`02-08 16:45:02.714: I/Unity(15357):  [Play Games Plugin DLL] 02/08/16 16:45:02 +11:00 DEBUG: Entering internal callback for SnapshotManager#ReadCallback`

Followed by a crash:
https://gist.github.com/prodigga/c5d2d793c985cf89aacf

A couple of log entries after the crash dump, I see this:

> E/FlurryAgent(11017): GOOGLE PLAY SERVICES EXCEPTION: com.google.android.gms.common.GooglePlayServicesUtil
>E/FlurryAgent(11017): There is a problem with the Google Play Services library, which is required for Android Advertising ID support. The Google Play Services library should be integrated in any app shipping in the Play Store that uses analytics or advertising.

I've deleted all play-services-* files and let the Jar Dependencies resolver replace them with fresh copies incase they were corrupt, but it didn't help.

We are also using the Google Analytics plugin - maybe a conflict?

**Comment by prodigga** [comment]
This crash only seems to happen when running with the IL2CPP backend. Works perfectly with the Mono backend. I am not sure where the fault is (Unity or GPGS Plugin) but something is definitly going wrong in IL2CPP.

IL2CPP is the way of the future for Unity and Unity will eventually be porting all platforms to IL2CPP. Some projects (Like ours) are already using IL2CPP backend for their live project. hopefully these issues can be corrected.

**Comment by claywilkinson** [comment]
Make sure you file the bug with Unity - the IL2CPP support for Android is still experimental.

**Comment by prodigga** [comment]
Filed a bug report, will update here when I know more..

**Comment by prodigga** [comment]
It seems like this issue is resolved in the latest version of Unity.
