### ISSUE TITLE
Podfile doesn't include google play services when integrating with ADMOB

### ISSUE THREAD

**Issue by Naamani** [playgameservices/play-games-plugin-for-unity#961]
Hi,
After updating both plugins and building to XCode, the podefile looks like this:

```
source 'https://github.com/CocoaPods/Specs.git

platform :ios, '7.0
pod 'Google-Mobile-Ads-SDK', '~> 7.6

```

And the build fails. So I added this:
`pod 'GooglePlayGames'`
to the podfile, and ran
`pod install`
Now the build passes, but when running the game I encounter in this issue (which when debugging gives me error in GPS class):
http://forum.unity3d.com/threads/handheld-playfullscreenmovie-crashes-when-video-over-or-canceloninput.384132/

Should I add the `pod GooglePlayGames` line? am I doing it right? Is there something I miss with both these plugins integration?

Thanks in advance.

**Comment by claywilkinson** [comment]
Hmm. Yes, you should add the GooglePlayGames pod line.  I think what is happening is both plugins are writing their own podfile and not respecting the contents.

**Comment by SilkyPantsDan** [comment]
We had the same issue for us, and I have currently edited the CocoaPodHelper class that came with Google Play Game Services to generate the Podfile based off the files that are appended. I have added the file and required changes in the following Gist: https://gist.github.com/SilkyPantsDan/fbaa7f7727fb181f869f5d51c1365e9d

There is a fair amount of work required for this to be a bit more robust, but at the moment this is working fine for our automated build machine to generate the required Podfile with post build commands for integrating both AdMob and Google Play Game services with Unity 5.3.4f1 and Xcode 7.3

**Comment by Disar** [comment]
Any update on this?

**Comment by claywilkinson** [comment]
Version 0.9.35 of the plugin uses a new jar resolver process that is also used by admob, so this will work now.
