### ISSUE TITLE
GetAccessToken() remains null for 2-3s after successful Authenticate(); need callback?

### ISSUE THREAD

**Issue by mwk888** [playgameservices/play-games-plugin-for-unity#962]
Hi, we've been using the plugin successfully for months, but something changed in the last few weeks so that when we call GetAccessToken() immediately after a successful Authenticate() it returns null. But if we call GetAccessToken() twice with about 3s delay the second call returns the token, so clearly the first call is starting an async process to get the token.

[I don't know why this used to work for us -- did underlying android gplay lib change?]

I've implemented a horrendous hack fix for now where delay etc, but it would be much cleaner if this method had an async callback option like GetIdToken().

btw I saw your post on another issue recommending GetServerAuthCode() but we are using GetUserEmail() so I think we need to keep using the G+ scopes. Unless that is available through the new GPlay auth flow somehow?

**UPDATE**: Thought about it further and maybe we could switch to using GetServerAuthCode(), the expedited sign-in would be nice. But I tried to test it and got status AuthApiAccessForbidden, does this need some manifest setup which is not done by the Android setup dialog? (We do provide a Web App Client ID)

Thanks!

**Comment by claywilkinson** [comment]
There has been updates to play games app that have been rolling out, and I know there are permission changes that are underway:  http://android-developers.blogspot.com/2016/01/play-games-permissions-are-changing-in.html

The  slowness could be the internet :/ ?  But it does confirm that the configuration and parameters are correct.  

A log of the call to GetServerAuthCode() would help diagnose any issue.  Email address is not part of the Game Services API - so it will be always extra scopes and APIs to get it.

There should be no need to edit the AndroidManifest.xml file manually, the setup should configure it correctly.  The service auth code is a pretty basic API - so as long as your web client id is associated with your game configuration it should work just fine.

**Comment by RodGreen** [comment]
Might be a good idea to include the AuthCode server side steps outlined in this blog article in the Readme. Or at least include a link to it so others can find how to use the ServerAuthCode.

**Comment by nmcgill** [comment]
I'm also experiencing "AuthApiAccessForbidden" when calling GetServerAuthCode(). Here is the log during signing in:

`I/GamesNativeSDK( 4962): Auth operation started: SIGN OUT
E/GamesNativeSDK( 4962): Out of box error detected; the user must reauthenticate through the UIflow.
I/Unity   ( 4962):  [Play Games Plugin DLL] 02/10/16 19:01:44 -03:30 DEBUG: Starting Auth Transition. Op: SIGN_OUT status: ERROR_NOT_AUTHORIZED
I/Unity   ( 4962):  
I/Unity   ( 4962): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 4962): 
I/Unity   ( 4962):  [Play Games Plugin DLL] 02/10/16 19:01:44 -03:30 DEBUG: Entering internal callback for GameServices#InternalFetchServerAuthCodeCallback
I/Unity   ( 4962):  
I/Unity   ( 4962): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
I/Unity   ( 4962): 
D/Unity   ( 4962):  [Play Games Plugin DLL] 02/10/16 19:01:44 -03:30 DEBUG: Starting Auth Transition. Op: SIGN_OUT status: ERROR_NOT_AUTHORIZED
D/Unity   ( 4962):  [Play Games Plugin DLL] 02/10/16 19:01:44 -03:30 DEBUG: Entering internal callback for GameServices#InternalFetchServerAuthCodeCallback
W/Unity   ( 4962): *** [Play Games Plugin DLL] 02/10/16 19:01:44 -03:30 ERROR: Error loading server auth code: ERROR_NOT_AUTHORIZED
W/Unity   ( 4962):  
W/Unity   ( 4962): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
W/Unity   ( 4962): 
I/Unity   ( 4962): ServerAuthCodeCallback: AuthApiAccessForbidden`

There is a curious "Out of box error detected; the user must reauthenticate through the UIflow" message which might be the problem? I succesfully authenticate but calling GetServerAuthCode() seems to sign out the user.

**Comment by claywilkinson** [comment]
I'll see if I can find out some causes of the "out of box" errors.  Generally speaking it means that server has invalidated the authorization token for some reason not known to the GPGS C++ SDK.

The effect is by the time GetServerAuthCode is called, the player is not signed in, resulting in the error.

Maybe a better pattern is to call IsAuthenticated() before calling GetServerAuthCode.  If the player is not authenticated, then call Authenticate().

**Comment by mwk888** [comment]
@nmcgill that matches what I'm seeing; calling GetServerAuthCode() has a side effect that logs the user out of gplay (or at least clears the persisted credentials / sign-in preferences). Probably related to whatever is causing AuthApiAccessForbidden. My log is very similar

btw I'm testing on a device with multiple gplay accounts if that makes any difference

**Comment by claywilkinson** [comment]
Are you using the auth code on the server, or just getting it when you get logged out?  Can you share a log?

**Comment by nmcgill** [comment]
Here's my repro steps (all client side):

1) PlayGamesPlatform.Activate();
2) Call Authenticate();
> D/Unity   ( 6542):  [Play Games Plugin DLL] 02/11/16 16:49:38 -03:30 DEBUG: Populating Achievements, status = VALID
> D/Unity   ( 6542):  [Play Games Plugin DLL] 02/11/16 16:49:38 -03:30 DEBUG: Found 0 Achievements
> D/Unity   ( 6542):  [Play Games Plugin DLL] 02/11/16 16:49:38 -03:30 DEBUG: Maybe finish for Achievements
> D/Unity   ( 6542):  [Play Games Plugin DLL] 02/11/16 16:49:38 -03:30 DEBUG: Auth finished. Proceeding.
> D/Unity   ( 6542):  [Play Games Plugin DLL] 02/11/16 16:49:38 -03:30 DEBUG: Invoking Callbacks: System.Action`1[System.Boolean]
> D/Unity   ( 6542):  [Play Games Plugin DLL] 02/11/16 16:49:38 -03:30 DEBUG: Invoking user callback on game thread

2) On success callback, verify user is authenticated using IsAuthenticated();
3) Call GetServerAuthCode();
> I/GamesNativeSDK( 6542): Auth operation started: SIGN OUT
> E/GamesNativeSDK( 6542): Out of box error detected; the user must reauthenticate through the UIflow.
> I/Unity   ( 6542):  [Play Games Plugin DLL] 02/11/16 16:49:53 -03:30 DEBUG: Starting Auth Transition. Op: SIGN_OUT status: ERROR_NOT_AUTHORIZED
> I/Unity   ( 6542):  
> I/Unity   ( 6542): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
> I/Unity   ( 6542): 
> D/Unity   ( 6542):  [Play Games Plugin DLL] 02/11/16 16:49:53 -03:30 DEBUG: Starting Auth Transition. Op: SIGN_OUT status: ERROR_NOT_AUTHORIZED
> I/Unity   ( 6542):  [Play Games Plugin DLL] 02/11/16 16:49:53 -03:30 DEBUG: Entering internal callback for GameServices#InternalFetchServerAuthCodeCallback
> I/Unity   ( 6542):  
> I/Unity   ( 6542): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
> I/Unity   ( 6542): 
> W/Unity   ( 6542): *** [Play Games Plugin DLL] 02/11/16 16:49:53 -03:30 ERROR: Error loading server auth code: ERROR_NOT_AUTHORIZED
> W/Unity   ( 6542):  
> W/Unity   ( 6542): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)
> W/Unity   ( 6542): 
> D/Unity   ( 6542):  [Play Games Plugin DLL] 02/11/16 16:49:53 -03:30 DEBUG: Entering internal callback for GameServices#InternalFetchServerAuthCodeCallback
> I/Unity   ( 6542): ServerAuthCodeCallback: AuthApiAccessForbidden

3) No auth code is returned for me to pass to our server, and AuthApiAccessForbidden is the status returned.

**Comment by claywilkinson** [comment]
Thanks.  Can you tell me the versions of  SDK, play services, the Games App

There should is a line in the log that looks like: 

`W/GamesServiceBroker( 1645): Client connected with SDK 8487000, Services 8489238, and Games 35170038`

**Comment by nmcgill** [comment]
Client connected with SDK 8487000, Services 8489030, and Games 35170030

**Comment by claywilkinson** [comment]
This is a known issue when GetServerAuthCode is called with an invalid webClientId.  There is a fix being rolled out in the next version the Play Games App (which should show up in the next few days on your device)

**Comment by daguirre6** [comment]
Hi everyone, 

I was having the same problem as some of you when using GetServerAuthCode() (AuthApiAccessForbidden). When I configured the plugin's settings, I used the OAuth2 Client ID that you find under the Authorization section on the Google Play Developer Console as my webClientId:

<img width="777" alt="screen shot 2016-02-11 at 5 08 47 pm" src="https://cloud.githubusercontent.com/assets/17187648/12995136/621bd972-d0e2-11e5-9237-c1a051efd139.png">

When I ran my project, I kept getting "AuthApiAccessForbidden" as the status every time I called GetServerAuthCode(). After trying different things, I finally figured out that the Client ID that I used when configuring the plugin was NOT a Web Client ID.  Thus, I created a Web Client ID for my project using the Google Developer Console (https://console.developers.google.com/). 

<img width="1242" alt="screen shot 2016-02-11 at 5 15 20 pm" src="https://cloud.githubusercontent.com/assets/17187648/12995250/59775ee4-d0e3-11e5-986b-0463e88d57a9.png">

After re-configuring the plugin with this newly created Web Client ID, everything worked perfectly. I just wanted to share this in case somebody is making the same mistake as me.

**Comment by mwk888** [comment]
@daguirre6 thanks! You were right, I was using the wrong credential type. With a Web application credential GetServerAuthCode() works fine.

**Comment by nmcgill** [comment]
@daguirre6 Working for me now as well, thanks for sharing!

**Comment by mwk888** [comment]
btw re: the original issue "GetAccessToken() remains null" technically still exists (it is awkward to get the token reliably without an async callback), but considering the roadmap for game services I've followed claywilkinson's suggestion and stopped using GetAccessToken(). We now do our server auth via GetServerAuthCode()

**Comment by apavani** [comment]
@daguirre6 
Thank you so much for posting where to find this information. You are a real savior. 
I spent almost 72 hours looking for an answer and had almost given up before I stumbled upon your answer.
If only Google did a better job at documenting this stuff :/
