### ISSUE TITLE
Minimal project can't able to authenticate

### ISSUE THREAD

**Issue by siddharth3322** [playgameservices/play-games-plugin-for-unity#963]
After giving so much time towards my game authentication problem solution, I decided to go from scratch with template project.

So I downloaded Minimal project available in github and imported google-play plugin v9.30.

Just applied my application setting and try to run same project but that also can't able to authenticate.
I am getting this type of log message.

![minimalprojerror](https://cloud.githubusercontent.com/assets/3082151/12912097/75a7cb88-cf3c-11e5-9764-44546e9f2789.png)

I have already updated recent version of sdk so not exist this kind of mistake.
Following image demonstrate my plugin/android data so that you become somewhat more clear.

![pluginandroidfolder](https://cloud.githubusercontent.com/assets/3082151/12912142/b28ce4ca-cf3c-11e5-9f2c-fcc4f6f1e52a.png)

Please guide me to solve this problem, I am available always if you have any questions regarding problem.

**Comment by claywilkinson** [comment]
you should not have google-play-services_lib in the project.  Can you share the log when the app is starting and you call Authenticate?  It looks like the initialization failed.

**Comment by siddharth3322** [comment]
If I remove google play service library then another bug is started on screen. I am attaching my source code so please check it your side and reply back to me at which place mistake exist.

It is just minimal project provided by plugin support nothing else.

[https://www.dropbox.com/s/3rr2ki5a2fzdzxn/GPGTest.zip?dl=0](url)

**Comment by claywilkinson** [comment]
@siddharth3322 - I don't mind helping out - but I don't really have time to download a debug projects - can you share the log of build problem?  Most of the build issues are related to the google-play-services_lib vs. aar files change.

If you are using other plugins that were requiring google-play-services_lib and now have some missing dependency or resource, then you'll need to add that .aar to your project in order for that plugin to work.

**Comment by siddharth3322** [comment]
In this project I have not added other plugins.

I have attached log details, this represent complete details about whatever things happen in background.
[MinimalProjLog.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/125225/MinimalProjLog.txt)

**Comment by claywilkinson** [comment]
OK. In the log I see
`02-10 23:05:23.073 13015-13030/? E/dalvikvm: Could not find class 'android.support.v4.util.ArrayMap', referenced from method com.google.android.gms.common.api.GoogleApiClient$Builder.<init>`

Can you update to the latest version of the Android Support Repository, and Google Repository using the SDK Manager?  This problem is because an old version of android-support-v4 is being used.

**Comment by siddharth3322** [comment]
I already updated my sdk with latest version. please check following images.
![sdkmanager1](https://cloud.githubusercontent.com/assets/3082151/12956171/a0df3294-d04c-11e5-88dd-095222b76d80.png)
![sdkmanager2](https://cloud.githubusercontent.com/assets/3082151/12956172/a1102bce-d04c-11e5-88d0-4462515431c8.png)

**Comment by claywilkinson** [comment]
Hmm, OK then can you delete support* and play-services* from you Assets/Plugin/Android directory, and re-run Window > Google Play Games > Setup > Android Setup.  And it should be better :)

**Comment by siddharth3322** [comment]
are you talking about to remove google-play-service_lib and support-v4-23.1.1 from project?

**Comment by claywilkinson** [comment]
remove everything **except** libs and MainLibProj.  (So remove anything that starts with support or starts with play-services).  Then run setup again.

**Comment by siddharth3322** [comment]
I have done similar thing and run setup again but after this, I was get this error.

![googleplayerservice_version not found](https://cloud.githubusercontent.com/assets/3082151/12956418/f7ba0a8e-d04d-11e5-9f76-0889d73d9e29.png)

**Comment by claywilkinson** [comment]
What is in your Assets/Plugins/Android directory now?  play-services-basement defines the variable it is looking for.

**Comment by siddharth3322** [comment]
This is plugins/android folder now.

![pluginsandroidfolder](https://cloud.githubusercontent.com/assets/3082151/12956644/ffd65c08-d04e-11e5-96af-cb82f10ab91a.png)

**Comment by claywilkinson** [comment]
it looks like you have an play-services-base-8.4.0 directory and a .aar file?  You can delete the folder.  My directory listing is:
```./libs
./MainLibProj
./play-services-base-8.4.0.aar
./play-services-basement-8.4.0.aar
./play-services-drive-8.4.0.aar
./play-services-games-8.4.0.aar
./play-services-nearby-8.4.0.aar
./play-services-plus-8.4.0.aar
./support-annotations-23.1.1.jar
./support-v4-23.1.1.aar
```

**Comment by siddharth3322** [comment]
I have try to delete folder but it is auto generated.
I am getting similar error at time of apk generation.

**Comment by claywilkinson** [comment]
Which version of Unity are you using?

If you download the latest plugin (I updated it this morning) you can disable the background resolution under Assets/Google Jar Resolver/Settings.  Which may help stop things from moving around so much so we can figure out what is going on.

**Comment by siddharth3322** [comment]
right now I am using Unity 4.6.9p1

let me try what you have said.

**Comment by siddharth3322** [comment]
Actually how to do this? I have this kind of structure exist.

![pluginresolver](https://cloud.githubusercontent.com/assets/3082151/12957187/7f7ad1e4-d051-11e5-860f-aeb810e46a8d.png)

**Comment by claywilkinson** [comment]
4.6.9 - This version does not support .aar files so it should be "exploding" all the aar files into folders.
To upgrade to the latest plugin, you should be able to simply import it and will overwrite the old plugin.

However - since you have been through so much (you are very patient!) I suggest making brand new project using the newest plugin (version 0.9.31).

I will try to build Minimal with 4.6.8 later today.

**Comment by siddharth3322** [comment]
Means with unity 4.6.9 and google-play-service v0.9.31 work perfectly, right?

**Comment by claywilkinson** [comment]
_Perfectly_ - well it should work really, really well, but most people use Unity 5+, so sometimes some weird things happen.  I'll try it in a couple hours.

**Comment by siddharth3322** [comment]
okay thanks for your help.
I will try at my morning :) Otherwise we talk here at same time.

**Comment by claywilkinson** [comment]
I tried a new project adding the minimal sample and the GooglePlayGameServices plugin using Unity 4.6.8.

I ran Window > Google Play Games > Setup > Android Setup... and entered the information from the play console.

Then I ran Assets > Google Play Services > Resolver Client Jars.  This exploded the .aar files in Assets/Plugins/Android into folders:
<img width="259" alt="screen shot 2016-02-10 at 7 40 38 pm" src="https://cloud.githubusercontent.com/assets/8752378/12968941/36bed25c-d02e-11e5-9a3d-2f1e2d108ace.png">

Then entered by keystore path and password and build & run.

**Comment by siddharth3322** [comment]
Thanks for your reply.

> Then I ran Assets > Google Play Services > Resolver Client Jars. This exploded the .aar files in Assets/Plugins/Android into folders

But in your above steps I can't able to get this.

![projectdata](https://cloud.githubusercontent.com/assets/3082151/12972475/9a6e335e-d0cb-11e5-90b2-9cc67507f15a.png)

Basically I cant able to find resolver client jars.

**Comment by siddharth3322** [comment]
Now I have downloaded unity 4.6.8. 
Create a new project but import google-play-service plugin v0.9.31.
But there is no menu appear in windows section.

Here is image for this.
![importerror](https://cloud.githubusercontent.com/assets/3082151/12978760/04e59542-d0f9-11e5-8c53-0b5e69f98228.png)


Even I have restarted unity 2-3 times.

**Comment by claywilkinson** [comment]
Did you switch the platform to Android?  The menu does not show up unless it is a supported platform.

**Comment by siddharth3322** [comment]
No I have checked, I have not done this kind of mistake.

But after upgrading to unity 5 everything was resolved.
Admob ad is also start working now.

This is final that with unity 4.6.8 and 4.6.9, something might now be running well.
So request other members to upgrade with unity 5 so get resolve this kind of silly and time consuming errors.

**Comment by claywilkinson** [comment]
OK - thanks for your feedback.  I am glad you finally got it working.

**Comment by siddharth3322** [comment]
but this problem almost mad me. Spent around a week delay in completion.
So this is so much frustrating :)

**Comment by siddharth3322** [comment]
thanks for your help to at least reach at some conclusion.
