### ISSUE TITLE
Cant link xCode project - Undefined symbols for architecture arm64: "_UnpauseUnityPlayer"

### ISSUE THREAD

**Issue by MildaGenius** [playgameservices/play-games-plugin-for-unity#968]
Hello,
Iam trying to build iOS test example with GPG without CocoaPods in Unity 5.3.0f4 and plugin 0.9.30.

After exporting xCode project:
1.Added frameworks
- AddressBook.framework
- AssetsLibrary.framework
- CoreData.framework
- CoreTelephony.framework
- CoreText.framework
- Security.framework
- libc++.dylib
- libz.dylib
- StoreKit.framework

2.Added Google frameworks
- [Play Games C++ SDK Version 2.1](https://developers.google.com/games/services/downloads/gpg-cpp-sdk.v2.1.zip) - (gpg.bundle, gpg.framework)
- [Google Sign-In SDK 2.4.0](https://developers.google.com/identity/sign-in/ios/sdk/google_signin_sdk_2_4_0.zip) - (GoogleSignId.bundle, GoogleSignId.framework)
- According to documentation GoogleOpenSource.framework is part of GoogleSign In SDK.

3.Added -objC linker flag

4.Changed header path to
`#import <GoogleSignIn/GIDSignIn.h>
# import <GoogleSignIn/GIDGoogleUser.h>
# import <GoogleSignIn/GIDAuthentication.h>
# import <GoogleSignIn/GIDProfileData.h>

`

5.Removed GPGSAppController.mm from Build phase -> Compile Sources to fix path to 
`#import <gpg/ios_support.h>
# import <gpg/GPGEnums.h>

`

After this I am able to compile project, but while linking I got this errors.

`Undefined symbols for architecture arm64:
  "_UnpauseUnityPlayer", referenced from:
      _NativeClient_HandleAuthTransition_m6_1144 in Bulk_Assembly-CSharp_2.o
      _NativeClient_UnpauseUnityPlayer_m6_1145 in Bulk_Assembly-CSharp_2.o
     (maybe you meant: _NativeClient_UnpauseUnityPlayer_m6_1145)
`
And the same error for other symbols (_TurnBasedMultiplayerManager_PlayerSelectUIResponse_GetMinimumAutomatchingPlayers, _TurnBasedMultiplayerManager_PlayerSelectUIResponse_GetPlayerIds_GetElement, _TurnBasedMultiplayerManager_PlayerSelectUIResponse_GetPlayerIds_Length ...)

I try to reimport plugin package into Unity project, but the result is the same.

Can somebody help me with the linker error?
Where should be library with mentioned symbols?

**Comment by claywilkinson** [comment]
_UnpauseUnityPlayer is part of the GPGS plugin.  The plugin source code gets added to the Xcode project.

_TurnBasedMultiplayerManager_PlayerSelectUIResponse_GetMinimumAutomatchingPlayers is part of gpg

Just out of curiosity, why not use Cocoapods?

**Comment by MildaGenius** [comment]
I found the problem. Its from step 5. Removed GPGSAppController.mm and not inserted back.

So I replaced downloaded gpg.framework with framework downloaded from Cocoapods which has header files in different structure, so now ios_support.h is explorable.

Linker errors changed to:
`(null): "_OBJC_CLASS_$_GTLCollectionObject", referenced from:
(null): "_OBJC_CLASS_$_GTLObject", referenced from:
(null): "_OBJC_CLASS_$_OpenInChromeController", referenced from:
(null): "_OBJC_METACLASS_$_GTLServiceTicket", referenced from:
`

Reasons for dont use Cocoapods:
1.additional system for Unity postprocess
2.no actually used library version under control
3.each Mac user in team must install and use Cocoapods
4.request to rework remote build process for use workspace

**Comment by claywilkinson** [comment]
Google Open source is part of Signin, but I think there are a couple symbols that are not?  Can you try linking in that framework in as well?
https://developers.google.com/+/mobile/ios/sdk/google-plus-ios-sdk-1.7.1.zip

Thanks for the explanation of Cocoapods!

**Comment by mrThinBone** [comment]
Hi, did you fix it?

**Comment by MildaGenius** [comment]
No,
I didnt fix it.

I started use Cocoapods :(.

**Comment by claywilkinson** [comment]
OK to close this issue?
