### ISSUE TITLE
Cloud access should call action blocks

### ISSUE THREAD

**Issue by habitoti** [playgameservices/play-games-plugin-for-unity#97]
In contrast to the other functionality of the plugin, for cloud access you need to implement an interface with callbacks, rather then providing System.Action blocks like for all the other functions of the plugin. For the sake of consistency (and code clarity and easier writing) the existing calls should get an optional System.Action block also so that result handling can be easily written inline.

**Comment by claywilkinson** [comment]
done! Thanks for the comments
