### ISSUE TITLE
NO_GPGS set, still wants to use this plugin ? GIDSignIn.h not found.

### ISSUE THREAD

**Issue by Disar** [playgameservices/play-games-plugin-for-unity#971]
For iOS we just want to use GameCenter. So I've set the NO_GPGS flag. Yet when I compile in xcode it says GIDSignIn.h not found.

Am I missing something?

**Comment by claywilkinson** [comment]
You might need to re-build the game from Unity and check your .xcodeproject.  What NO_GPGS does in terms of xCode, is remove GPGSAppController.mm and .h from the project completely.  You could also manually remove them from the project.

**Comment by Disar** [comment]
Project is on git and really want to keep the game project the same as much as possible for android and ios.

So even if I don't want to use GPG on ios I still have to install the framework dependencies ?

I only do clean xcode builds for each new build I never append. 
I tried to update to version 0.9.31 but it complains about namespace OurUtils not being defined.

**Comment by claywilkinson** [comment]
Looks like a couple questions in there:
The Unity project can be the same for both - I do this all the time.  The NO_GPGS flag should only affect ios builds - if it affects Android, then that is a bug.

I am assuming when you talk about installing the framework dependencies you are referring to the xcode project?  You should not need these, and the Cocoapod processing within the Unity project should not happen if NO_GPGS is defined.  If there is a Podfile generated, then maybe NO_GPGS is not defined correctly?

With respect to updating, Unity is sometimes a little rough.  Where is it complaining about OutUtils?  One sure way to upgrade is to delete Assets/GooglePlayGames, Assets/PlayServicesResolver and then import the new plugin.

If you have specific errors, can you share the log messages?

**Comment by Disar** [comment]
Ill get the log later.

It looks like GPSAppController.mm and h are still present in the project. So im assuming this is a bug.
Using unity 5.3 btw.

**Comment by Disar** [comment]
The error is this btw :

     Assets/GooglePlayGames/Platforms/Native/PInvoke/BaseReferenceHolder.cs(24,27): error CS0234: The type or namespace name `OurUtils' does not exist in the namespace `GooglePlayGames'. Are you missing an assembly reference?

**Comment by claywilkinson** [comment]
Yep - I just tried it and got the same thing.  I'll try to get an update out today.

**Comment by Disar** [comment]
After removing the controller.mm and h I get :

     /Build/B10/Libraries/Plugins/IOS/CustomWebViewApplication.mm:21:9: 'GTMOAuth2Authentication.h' file not found

**Comment by claywilkinson** [comment]
CustomWebViewApplication is an old file you can safely delete it.

**Comment by Disar** [comment]
Able to make a build.
Did get an error about bitcode but turned that off and have it on my pad now. Not sure if it's coming from Googl analytics ( they also have a bitcode package but didnt use it ) or your stuff. anyways thanks!
