### ISSUE TITLE
Incremental Achievement showing 100%

### ISSUE THREAD

**Issue by shraa1** [playgameservices/play-games-plugin-for-unity#972]
I have an incremental achievement with 2 steps in the developer console. When starting the game, I have a button to show the achievement UI. It shows 100% on the incremental achievement. Then when the event fires the function:

`GooglePlayGames.PlayGamesPlatform.Instance.IncrementAchievement("xyz", 1, (bool success) => {});`

It shows 50%. And it still shows the ACHIEVEMENT UNLOCKED. In the Achievements UI, it then shows 50% and it is not unlocked. Then when the above code is executed again, the achievement does unlock.

Anyone know how to not start the achievement at 100%?

**Comment by claywilkinson** [comment]
Quick points of clarification - you are using the standard Achievement UI - and in the code when you check the achievement it has a different value?  Which do you think is wrong?

**Comment by shraa1** [comment]
Yes I'm using the standard achievement ui.
I am not really checking the value of the achievement through code. On the main menu there's a button just calling the show achievement ui line.

`Social.ShowAchievementsUI();`

And I am using the increment code as written in original post in game when player dies.

I reset all achievements from Google play console. It shows 100% at first. 50% on first increment. And on second death, achievement gets unlocked

**Comment by shraa1** [comment]
I tested the app on another device. It doesn't happen there. Only happens if you have already completed achievement, and you then reset achievement through Google play developer console
