### ISSUE TITLE
Error on GPGSAndroidSetupUI, NULL packageName

### ISSUE THREAD

**Issue by GabrielePicco** [playgameservices/play-games-plugin-for-unity#976]
I update the play games plugin, but when i try to setup the Android configuration i have the following error:

`Debug.Log("NULL package!!");`

this error appear because packageName is null and this statement is false: (!string.IsNullOrEmpty(packageName)), 

how i can solve ?

**Comment by claywilkinson** [comment]
The resources copied from the play game console are not for Android?  It should be an xml document that contains the packageName.  Alternatively, the bundle id is not set in your Unity project player settings.

**Comment by GabrielePicco** [comment]
I update the resources xml document and it solve the problem, thanks !
