### ISSUE TITLE
Realtime PvP matches disconnects players immediately

### ISSUE THREAD

**Issue by VicEsquivel** [playgameservices/play-games-plugin-for-unity#977]
Ive been working on a prototype, and everything used to work like charm.. All of a sudden starting a realtime pvp matches became impossible. One player always gets disconnected...

I thought it was my game, so I tested old versions that used to work, and even tested it with the google's sample realtime pvp unity project, with the very exact outcome... 

Even with multiple gmail accounts. Everything points that it's a bug on Google's side. I read that this bug used to exist but was fixed on the update (0.9.21), I am using (0.9.27). And again, the bug appeared out of nowhere... It was working fine until February 12th 2016...

**This is the Log:**

02-12 13:17:08.435 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: New participants connected:
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-12 13:17:08.435 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: Fully connected! Transitioning to active state.
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-12 13:17:08.435 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: Entering state: ActiveState
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-12 13:17:08.445 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: Entering internal callback for RealTimeEventListenerHelper#InternalOnRoomConnectedSetChangedCallback
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
02-12 13:17:08.475 22370-22596/? I/Unity﹕ [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 DEBUG: Updated participant statuses: [Participant: 'Jugador 5603' (id p_COnfjbLas9TreRAB), status=Joined, player=NULL, connected=False],Participant: 'Code 91 Mx' (id p_CIP90dqjpavsWhAB), status=Joined, player=[Player: 'Code 91 Mx' (id 116188677374566560658)], connected=False
02-12 13:17:08.475 22370-22596/? W/Unity﹕ !!! [Play Games Plugin DLL] 02/12/16 13:17:08 -06:00 **WARNING: Player was disconnected from the multiplayer session.
(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)**

Any answers?

**Comment by danspeedy1** [comment]
Same issue here. I've checked my Play Store profile and everything is up-to-date and published. Also updated everything in the SDK manager. No luck.

**Comment by salal40** [comment]
I have got the same issue but it seems that this issue happens only on some devices. For example I tried using Samsung Galaxy Gio and this happens even if I use different google accounts as long as I am on the same device although this does not happen on Note5 and Infinix Note Pro.

**Comment by VicEsquivel** [comment]
@salal40 yes, i noticed that too, when I first saw the error I thought it was a device issue, so I restore it, because the account that failed to work there, was working excellent in another device, then, the other device started presenting the same error.

The big thing here is that the devices that does not work now, USED to work excellent before February 12th 2016. I had been working on this prototype for almost 2 months without problems. Something changed in the back end for sure...

**Comment by salal40** [comment]
Yes exactly. Hopefully the developers are aware of the issue now and fix it asap. I am close to the release of my game and this issue arises....

**Comment by VicEsquivel** [comment]
Yes, same here... My release due date was for last friday... D: 
But as far as I see, this issue is for everyone. I mean, the production environment also has this bug. I published the sample project of google and it is also there. As @danspeedy1, publishing the game makes no difference.

**Comment by danspeedy1** [comment]
This might be irrelevant but I've noticed that on the waiting screen, the joining participant logo usually shows up as a silhouette of a head in blue. However, currently one of the players is appearing in either green or dark blue. This probably signals that one of the players has "disconnected" due the error above....

**Comment by claywilkinson** [comment]
I've recreated the problem.  Apparently the play-services library is always returning false for Participant.IsRoomConnected().

I think a reasonable workaround is to change `Assets/GooglePlayGames/Platforms/Native/PInvoke/MultiplayerParticipant.cs` line 56
to be:
```
        internal bool IsConnectedToRoom()
        {
            // This is a bug - it always returns false!
            //return C.MultiplayerParticipant_IsConnectedToRoom(SelfPtr());
            return Status() == Types.ParticipantStatus.JOINED;
        }
```

I'll update the plugin code soon, but in the meantime this workaround should work for you.

**Comment by danspeedy1** [comment]
Thanks @claywilkinson. It's working with your suggested fix. Any idea what changed or why the library is always returning false? It stopped working seemingly randomly and I hadn't pulled/made any changes.

**Comment by claywilkinson** [comment]
I don't know specifically, but it does not work with the Java samples either, so I suspect something in play-services, or play games app, or on the server.  I'll update the thread when I hear more about the fix.

**Comment by danspeedy1** [comment]
Awesome, thank you.

**Comment by VicEsquivel** [comment]
@claywilkinson Cool! This worked! Maybe it can be useful for you to know that the behaviour was different if using the gmail account that is registered as developer... 

Only that account entered to the game... The other accounts were automatically kicked.

**Comment by claywilkinson** [comment]
Thanks for the additional information.  I have updated the package to version 0.9.31a so the fix is integrated into the package.

**Comment by simsis3d** [comment]
Hey to all, my game WoodBall is published on Google Play(not on development stage) and for last two days players send lots of messages saying we are not able to play online matches. Then I downloaded the current version of my game from Google Play and I tested. I faced same problem you described here. Then I upgraded Google Play Games from my phone and able to play online matches. Is it somehow related? @claywilkinson

**Comment by claywilkinson** [comment]
Hi @simsis3d   - I believe you are describing this issue.  I believe there is a fix rolling out in the Play Games App which should be everywhere very soon.  Thanks for asking - it is confirming the issue, and that the fix is getting out there.

**Comment by claywilkinson** [comment]
OK to close this one?  I think everything is resolved.
