### ISSUE TITLE
admob leads to error while building unity project

### ISSUE THREAD

**Issue by adulthood1** [playgameservices/play-games-plugin-for-unity#980]
Get unknown errror while building project. Unity 5, latest SDK build tool and JDK set.
Error:

`Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
D:\SDK\build-tools\23.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "D:/SDK\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.google.android.gms:com.google.unity:com.google.android.gms.ads:com.google.android.gms:android.support.v4 -S "D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res" -S "D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res" -S "D:\Workspace\adtest2\Temp\StagingArea\android-libraries\play-services-ads-8.4.0\res" -S "D:\Workspace\adtest2\Temp\StagingArea\android-libraries\play-services-basement-8.4.0\res" -S "D:\Workspace\adtest2\Temp\StagingArea\android-libraries\support-v4-23.1.1\res"

stderr[
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <android.support.v7.widget.ButtonBarLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_button_bar_material.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/abc_alert_dialog_button_bar_material for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.widget.DialogTitle>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/abc_alert_dialog_material for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_dialog_title_material.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/abc_dialog_title_material for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.widget.ActionBarContainer>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/abc_screen_toolbar for configuration v21.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_search_view.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_search_view.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/abc_search_view for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/notification_template_big_media for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/notification_template_big_media_narrow for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:77: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:96: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:64: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/notification_template_lines for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml:43: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <include>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml:33: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/notification_template_media for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_chronometer.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <Chronometer>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_chronometer.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/notification_template_part_chronometer for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_time.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <DateTimeView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_time.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/notification_template_part_time for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml:28: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml:28: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <ImageView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml:8: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <View>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/place_autocomplete_item_powered_by_google for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml:52: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <TextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml:35: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <TextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml:8: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentStart from <include>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/place_autocomplete_item_prediction for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_progress.xml:2: note: removing attribute http://schemas.android.com/apk/res/android:indeterminateTint from <ProgressBar>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_progress.xml:2: note: removing attribute http://schemas.android.com/apk/res/android:indeterminateTintMode from <ProgressBar>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_progress.xml: note: using v21 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/place_autocomplete_progress for configuration v21.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:drawableStart from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml: note: using v13 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/select_dialog_multichoice_material for configuration v13.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:drawableStart from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml: note: using v13 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/select_dialog_singlechoice_material for configuration v13.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable\abc_textfield_search_material.xml:19: note: removing attribute http://schemas.android.com/apk/res/android:state_activated from <item>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable\abc_textfield_search_material.xml: note: using v11 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:drawable/abc_textfield_search_material for configuration v11.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/select_dialog_multichoice_material for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/select_dialog_singlechoice_material for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\admob_ads_attrs.xml:10: error: Attribute "adSize" has already been defined

D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\admob_ads_attrs.xml:17: error: Attribute "adSizes" has already been defined

D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\admob_ads_attrs.xml:20: error: Attribute "adUnitId" has already been defined

D:\Workspace\adtest2\Temp\StagingArea\android-libr<message truncated>`

and

`CommandInvokationFailure: Failed to re-package resources. See the Console for details.
D:\SDK\build-tools\23.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "D:/SDK\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.google.android.gms:com.google.unity:com.google.android.gms.ads:com.google.android.gms:android.support.v4 -S "D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res" -S "D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res" -S "D:\Workspace\adtest2\Temp\StagingArea\android-libraries\play-services-ads-8.4.0\res" -S "D:\Workspace\adtest2\Temp\StagingArea\android-libraries\play-services-basement-8.4.0\res" -S "D:\Workspace\adtest2\Temp\StagingArea\android-libraries\support-v4-23.1.1\res"

stderr[
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <android.support.v7.widget.ButtonBarLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_button_bar_material.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/abc_alert_dialog_button_bar_material for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.widget.DialogTitle>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/abc_alert_dialog_material for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_dialog_title_material.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/abc_dialog_title_material for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.widget.ActionBarContainer>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/abc_screen_toolbar for configuration v21.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_search_view.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_search_view.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/abc_search_view for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/notification_template_big_media for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/notification_template_big_media_narrow for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:77: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:96: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:64: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/notification_template_lines for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml:43: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <include>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml:33: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/notification_template_media for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_chronometer.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <Chronometer>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_chronometer.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/notification_template_part_chronometer for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_time.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <DateTimeView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_time.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/notification_template_part_time for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml:28: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml:28: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <ImageView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml:8: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <View>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/place_autocomplete_item_powered_by_google for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml:52: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <TextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml:35: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <TextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml:8: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentStart from <include>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/place_autocomplete_item_prediction for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_progress.xml:2: note: removing attribute http://schemas.android.com/apk/res/android:indeterminateTint from <ProgressBar>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_progress.xml:2: note: removing attribute http://schemas.android.com/apk/res/android:indeterminateTintMode from <ProgressBar>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_progress.xml: note: using v21 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/place_autocomplete_progress for configuration v21.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:drawableStart from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml: note: using v13 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/select_dialog_multichoice_material for configuration v13.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:drawableStart from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml: note: using v13 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/select_dialog_singlechoice_material for configuration v13.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable\abc_textfield_search_material.xml:19: note: removing attribute http://schemas.android.com/apk/res/android:state_activated from <item>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\drawable\abc_textfield_search_material.xml: note: using v11 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:drawable/abc_textfield_search_material for configuration v11.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/select_dialog_multichoice_material for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml: note: using v17 attributes; synthesizing resource ctNamemp11any.Produc12e1Name:layout/select_dialog_singlechoice_material for configuration v17.
D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\admob_ads_attrs.xml:10: error: Attribute "adSize" has already been defined

D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\admob_ads_attrs.xml:17: error: Attribute "adSizes" has already been defined

D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\admob_ads_attrs.xml:20: error: Attribute "adUnitId" has already been defined

D:\Workspace\adtest2\Temp\StagingArea\android-libraries\google-play-servi<message truncated>`

Please help to solve the problem...
Thank you!

**Comment by adulthood1** [comment]
solution found:
https://groups.google.com/forum/#!topic/google-admob-ads-sdk/pduSPZEGt3U

**Comment by claywilkinson** [comment]
Great! ok to close?

**Comment by adulthood1** [comment]
Ok)18:56, 15 лютого 2016 р., Clayton Wilkinson <notifications@github.com>:Great! ok to close? —Reply to this email directly or view it on GitHub.     Надіслано з мобільної Яндекс.Пошти: http://m.ya.ru/ymail
