### ISSUE TITLE
How do we save game on pause or quit?

### ISSUE THREAD

**Issue by prodigga** [playgameservices/play-games-plugin-for-unity#982]
Hey there, we are trying to save our game on application pause, but it seems like the code wont execute in the background so we never successfully save.

On pause, we attempt to save using an open SaveGameMetadata, and we see this:

02-15 16:14:26.296: I/Unity(30599):  [Play Games Plugin DLL] 02/15/16 16:14:26 +11:00 DEBUG: Entering internal callback for SnapshotManager#CommitCallback

Our callback is called when we bring the app back to the front (unpausing it) - the status is set to 'InternalError'. 

So, how are we supposed to save the game when the user pauses or quits the application? 

Thanks :)

**Comment by InfiniteDreams** [comment]
I had similar problem but with the plugin from different provider (Prime31). I did ask him about possibility of saving snapshot in OnApplicationPause. This is the conversation that I had with him about this.

<Me>: Is it possible to send snapshots in the event OnApplicationPause(true) ?

<Prime31>: Per Google's documentation, when your app is backgrounded all Google API connections are severed. You cannot use any methods that require Google API access at that point.

<Me> Is the Google API already disabled when GameObjects in Unity receive an event OnApplicationPause ? After user pressed home button, google api disable first ?
Maybe you can still send a snapshot but without receiving succes / fail event ?

<Prime31>: Unity sends OnApplicationPause in the onPause Activity lifecycle method so the Google API is already disconnected. It disconnects itself in onPause.

So you can do either a button "Send To Cloud" in your game or send the snapshot after important moments in your game like buying expensive gun, car, level up etc.

**Comment by prodigga** [comment]
Sorry, I forgot to update this post..

I think Prime31 is making some assumptions about how certain things work. We found that if we keep the Metadata open, we can the CommitUpdate method and the update goes through just fine.

So, what we do is this: (Lets assume there are no conflicts!) Keep in mind any operation (Saving and loading) involving the metadata will close the it... So we need to make sure we always the metadata available and open. 

**On first load**
- Open metadata 
- Load game
- Open metadata again, keep reference to open metadata

**OnApplicationPause** or **OnApplicationQuit**
- CommitUpdate using previously opened metadata. 

**OnApplicationPause (Resuming)**
- Open metadata again, keep a reference to open metadata.

By keeping the metadata open at all times, you can always save OnApplicationPause. Remember we need to open the metadata again when the game resumes, because the CommitUpdate closed our metadata OnApplicationPause.

Using this method, you need to be prepared to handle file conflicts literally everywhere in your application - the user can pause the application at any time. When the application resumes you need to open the metadata - you cant open a metadata until any conflicts are resolved, and conflicts are only detected when opening the metadata.

**Comment by prodigga** [comment]
To add to this, if you want to save the game at an arbitrary point in time, (not on OnApplicationPause), then you will need to:

** Saving at any other point (ie: Loading screen/level transition)**
- CommitUpdate using previously opened metadata
- Open metadata again, keep a reference to open metadata.

**Comment by InfiniteDreams** [comment]
Thanks for the update. I have to try your approach. Good job :+1:

**Comment by VisalChhourm** [comment]
Thanks for sharing this. I have to try it out.

**Comment by Boowman** [comment]
Hello, I ran into the same problem and I am happy that there is a fix the only problem is that because I am not that familiar with google play so those steps don't make much sense to me.

1. Open metadata
- Not sure how to simply open the meta-data without doing something like loading/saving
2. Load game
- I am able to load/save the game 
3. Open metadata again, keep reference to open metadata
 - Is this the metaData? _SavedGameMetadataUpdate updatedMetadata = builder.Build();_
Assuming that I just declare updateMetaData as a global variable and just call it when Pausing the game. I still can't just call CommitUpdate inside OnApplicationPause because of the parameters.
Any chance of sharing a bit more information's on how to implement that?

**Comment by ChrisCF** [comment]
This workaround doesn't appear to work anymore. If you have an open snapshot and attempt to save in OnApplicationPause the commit doesn't happen until the app returns.
