### ISSUE TITLE
GetServerAuthCode different code generation approach?

### ISSUE THREAD

**Issue by icchoi** [playgameservices/play-games-plugin-for-unity#984]
If I use PlayGamesPlatform.GetServerAuthCode, it returns the same code every time.
This code is one-time use code, so once the user use this code, this code cannot be used again.
But once the server's session times out, it needs to be re-authenticated, but the method still returns the same old, used code, so fails authentication. As of now, in order to get a new code, the user have to log in again, but this is not an option.
So the question is, is there any way to get a new auth code without logging out?

**Comment by claywilkinson** [comment]
Short answer, no, you need to re-authenticate.

Long answer:
Once the server application has exchanged the auth code for a token, it should manage the token refresh on the server side.  GetServerAuthCode should ideally only be called once per player.  Then on the server, the auth code is exchanged for a token and a refresh token.  The server application stores these and uses the token as needed.  If the token expires, then the refresh token is used to get a new token.  There is no need to go back through the entire flow.  More information is on  https://developers.google.com/identity/sign-in/web/server-side-flow#step_6_send_the_authorization_code_to_the_server

**Comment by icchoi** [comment]
![googleplaylogin](https://cloud.githubusercontent.com/assets/17262592/13103738/cc8b96e0-d59b-11e5-8cc0-c660e96f9b1a.PNG)
The current logic. Please check.

**Comment by claywilkinson** [comment]
I am not sure what you are asking, but that flow seems excessive? One thing to keep in mind, is that the player has already authenticated with Google before getting the AuthCode.  So when you send the player id and the auth code to the game server, you don't need to communicate back the client that the log in was OK unless you are indicating the game server could not get a token.
