### ISSUE TITLE
Failed to re-package resources

### ISSUE THREAD

**Issue by nikita-zakharchenko** [playgameservices/play-games-plugin-for-unity#985]
I have an issue after adding the plugin to my project. 
"Failed to re-package resources"

AndroidManifest.xml:9: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

I fixed it and want to share the solution with you.

To fix this error, you have to copy the version.xml file from
android-sdk/extras/google/google_play_services/libproject/google-play-services_lib/res/values/
into Assets/Plugins/Android/res/values/ of your Unity project's folder.

**Comment by claywilkinson** [comment]
That's not a great solution.  You really want play-services-basement-8.xx.aar in your project instead.  Which version of Unity are you using?  Which version of the plugin?

**Comment by nikita-zakharchenko** [comment]
Unity Version 5.3.2p1
Plugin Version 0.9.31

I can't perform build with play-services-basement-8.xx.aar
There is an error when building. If you need I can reproduce it and answer what kind of error.

**Comment by claywilkinson** [comment]
That would be great if you could share the problem! The goal of the plugin is to copy in the *.aar files needed to compile the application.  Using the entire google-play-services_lib adds a ton of mostly unneeded code and resources to your game.

Is this a new project or updating an existing one?  Are you using other plugins that try to copy google-play-services_lib automatically?

**Comment by nikita-zakharchenko** [comment]
It's a not a new project, but we integrate Google Play Services Plugin at first time.We are not using any plugin that try to copy google-play-services_lib automatically.

I've deleted versions.xml from Assets/Plugins/Android/res/values/ in my Unity project's folder. Then I try to build the project and have this error:

CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:/Program Files/Java/jdk1.8.0_74\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Program Files (x86)/Android/android-sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.sponsorpay.utils.l) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoJellyBeanMr2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatJellyBeanMr2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorCompatHelper;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorListenerCompat;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
	... 9 more
]

**Comment by claywilkinson** [comment]
From the error: `Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;`

It looks like you have multiple support libraries in your project.  You should have support-v4-23.1.1.aar, if you have another support-v4, you can safely delete it.

**Comment by nikita-zakharchenko** [comment]
I found this support-v4 jar in one of *.jar plugin file. Thank you for your quick replies! I think you can close this issue.

**Comment by claywilkinson** [comment]
Great! thanks for the followup.
