### ISSUE TITLE
Unity GPGS Failed to re-package resources

### ISSUE THREAD

**Issue by nkmg14** [playgameservices/play-games-plugin-for-unity#988]
I am trying to integrate google play games services in existing game but getting the following error. Tried to copy google-play-services_lib in Plugins/Android but no help.

> AndroidSDKTools:
> 
>   root          : /Volumes/Others/android/sdk
>   tools         : /Volumes/Others/android/sdk/tools
>   platform-tools: /Volumes/Others/android/sdk/platform-tools
>   build-tools   : /Volumes/Others/android/sdk/build-tools/23.0.2
> 
>   adb      : /Volumes/Others/android/sdk/platform-tools/adb
>   aapt     : /Volumes/Others/android/sdk/build-tools/23.0.2/aapt
>   zipalign : /Volumes/Others/android/sdk/build-tools/23.0.2/zipalign
> 
> AndroidJavaTools:
>   java     : /Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/bin/java
> 
> CommandInvokationFailure: Failed to re-package resources. See the Console for details.
> /Volumes/Others/android/sdk/build-tools/23.0.2/aapt package --auto-add-overlay -v -f -m -J gen -M >AndroidManifest.xml -S "res" -I "/Volumes/Others/android/sdk/platforms/android-22/android.jar" -F >bin/resources.ap_ --extra-packages

**Comment by claywilkinson** [comment]
What version of Unity and the plugin are you using?  

Can you post the actual error?

You should not need to copy  google-play-services_lib.

**Comment by bobjung** [comment]
I had the same problem. Need to coty google-play-services_lib in Assets/Plugins/Android?

Popup Message: Build failure - Failed to re-package resources. See the Console for details.

Unity: 4.7.0f1
Plugin: GooglePlayGamesPlugin-0.9.31.unitypackage

Console log (below):
Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
D:\adt-bundle-windows-x86-20130911\sdk\build-tools\23.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "D:/adt-bundle-windows-x86-20130911/sdk/platforms/android-23\android.jar" -F bin/resources.ap_ --extra-packages com.google.example.games.mainlibproj

anifest.xml:20: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

]
stdout[
Configurations:
 (default)

Files:
  drawable\app_icon.png
    Src: () res\drawable\app_icon.png
  values\strings.xml
    Src: () res\values\strings.xml
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
  Type drawable
    drawable\app_icon.png
      Src: () res\drawable\app_icon.png
  Type values
    values\strings.xml
      Src: () res\values\strings.xml
Including resources from package: D:\adt-bundle-windows-x86-20130911\sdk\platforms\android-23\android.jar
applyFileOverlay for drawable
applyFileOverlay for layout
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res\drawable\app_icon.png
    (processed image res\drawable\app_icon.png: 94% size of source)
    (new resource id app_icon from drawable\app_icon.png #generated)
]

**Comment by bobjung** [comment]
It works in Unity 5.3.2f1.

**Comment by nkmg14** [comment]
I am using Unity version 5.2.4f1 and it would be very hard to upgrade Unity version because the game is already in production and we don't want to change Unity version at this time.

Here is the full error

AndroidSDKTools:

	root          : /Volumes/Others/android/sdk
	tools         : /Volumes/Others/android/sdk/tools
	platform-tools: /Volumes/Others/android/sdk/platform-tools
	build-tools   : /Volumes/Others/android/sdk/build-tools/23.0.2

	adb      : /Volumes/Others/android/sdk/platform-tools/adb
	aapt     : /Volumes/Others/android/sdk/build-tools/23.0.2/aapt
	zipalign : /Volumes/Others/android/sdk/build-tools/23.0.2/zipalign

AndroidJavaTools:
	java     : /Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/bin/java

CommandInvokationFailure: Failed to re-package resources. See the Console for details.
/Volumes/Others/android/sdk/build-tools/23.0.2/aapt package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "/Volumes/Others/android/sdk/platforms/android-22/android.jar" -F bin/resources.ap_ --extra-packages com.google.example.games.mainlibproj:android.support.v7.appcompat:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.plus:android.support.v4 -S "/Users/nkhajanchi/Desktop/GPGSUnityTestApp/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res" -S "/Users/nkhajanchi/Desktop/GPGSUnityTestApp/Temp/StagingArea/android-libraries/play-services-base-8.4.0/res" -S "/Users/nkhajanchi/Desktop/GPGSUnityTestApp/Temp/StagingArea/android-libraries/play-services-basement-8.4.0/res" -S "/Users/nkhajanchi/Desktop/GPGSUnityTestApp/Temp/StagingArea/android-libraries/play-services-drive-8.4.0/res" -S "/Users/nkhajanchi/Desktop/GPGSUnityTestApp/Temp/StagingArea/android-libraries/play-services-games-8.4.0/res" -S "/Users/nkhajanchi/Desktop/GPGSUnityTestApp/Temp/StagingArea/android-libraries/play-services-nearby-8.4.0/res" -S "/Users/nkhajanchi/Desktop/GPGSUnityTestApp/Temp/StagingArea/android-libraries/play-services-plus-8.4.0/res" -S "/Users/nkhajanchi/Desktop/GPGSUnityTestApp/Temp/StagingArea/android-libraries/support-v4-23.1.1/res"

stderr[
/Users/nkhajanchi/Desktop/GPGSUnityTestApp/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/values-v23/values-v23.xml:5: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

/Users/nkhajanchi/Desktop/GPGSUnityTestApp/Temp/StagingArea/android-libraries/appcompat-v7-23.1.1/res/values-v23/values-v23.xml:30: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: /Volumes/Others/android/sdk/platforms/android-22/android.jar
applyFileOverlay for drawable
trying overlaySet Key=ic_plusone_medium_off_client.png
trying overlaySet Key=ic_plusone_small_off_client.png
trying overlaySet Key=ic_plusone_standard_off_client.png
trying overlaySet Key=ic_plusone_tall_off_client.png
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_disabled.9.png

**Comment by claywilkinson** [comment]
Can you try running from the Unity menu Assets/Google Play Services/Resolve Client Jars?

**Comment by bobjung** [comment]
Awesome! It works!
Thanks for you help.

**Comment by nkmg14** [comment]
> Can you try running from the Unity menu Assets/Google Play Services/Resolve Client Jars?
I tried it but still same errors.
Regarding SDK, i will try updating to API 23.

**Comment by nkmg14** [comment]
Here is the screenshot of the Android SDK Manager.

![screen shot 2016-02-20 at 2 51 53 pm](https://cloud.githubusercontent.com/assets/17309203/13195822/8cedfb20-d7e1-11e5-969f-f66474065c3f.png)

**Comment by claywilkinson** [comment]
@nkmg14 make sure you have Google Repository and Android Support Repository components installed and up to date.  They are towards the bottom of the list in the "extras" section.

**Comment by claywilkinson** [comment]
OK to close?
