### ISSUE TITLE
DEBUG: Application is pausing, which disconnects the RTMP  client

### ISSUE THREAD

**Issue by AlexWitcher** [playgameservices/play-games-plugin-for-unity#989]
Hi, i use last version of Unity3d and last version of plugin, and when i try authenticate to Google Play Services, i have next error:   [Play Games Plugin DLL] 02/18/16 20:42:29 +02:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room. logtype:Log

**All Logs**
-   [Play Games Plugin DLL] 02/18/16 20:42:28 +02:00 DEBUG: Activating PlayGamesPlatform. logtype:Log

-  [Play Games Plugin DLL] 02/18/16 20:42:28 +02:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform logtype:Log

-  [Play Games Plugin DLL] 02/18/16 20:42:28 +02:00 DEBUG: Creating platform-specific Play Games client. logtype:Log

- [Play Games Plugin DLL] 02/18/16 20:42:28 +02:00 DEBUG: Creating Android IPlayGamesClient Client logtype:Log

-  Building GPG services, implicitly attempts silent auth logtype:Log

-  [Play Games Plugin DLL] 02/18/16 20:42:28 +02:00 DEBUG: Entering state: BeforeRoomCreateStartedState logtype:Log
   description: 

- [Play Games Plugin DLL] 02/18/16 20:42:28 +02:00 DEBUG: BeforeRoomCreateStartedState.OnStateEntered: Defaulting to no-op. logtype:Log
   description: 
 [Play Games Plugin DLL] 02/18/16 20:42:28 +02:00 DEBUG: Entering state: ShutdownState logtype:Log
   description: 

-  [Play Games Plugin DLL] 02/18/16 20:42:28 +02:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op. logtype:Log

-  [Play Games Plugin DLL] 02/18/16 20:42:29 +02:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room. logtype:Log
   description: 

-  [Play Games Plugin DLL] 02/18/16 20:42:41 +02:00 DEBUG: Application is pausing, which disconnects the RTMP  client.  Leaving room. logtype:Log
   description: 

-  [Play Games Plugin DLL] 02/18/16 20:42:49 +02:00 DEBUG: Invoking user callback on game thread logtype:Log
   description: 

Can someone help me please, and sorry for my bad English?=(

**Comment by claywilkinson** [comment]
How are you joining the room without authenticating?

Which version of Unity and the plugin are you using?

**Comment by AlexWitcher** [comment]
Unity3d version: 5.3.2p3
GooglePlayGamesPlugin-0.9.31a
I just try connect to services like in tutorial
`PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
       .EnableSavedGames()
       .RequireGooglePlus()
       .Build();
        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.DebugLogEnabled = true;
        PlayGamesPlatform.Activate();
        PlayGamesPlatform.Instance.localUser.Authenticate((bool success) =>
        {
            if (success)
            {
                Debug.Log("connection to gps succes");
            }
            else
            {
                Debug.Log("connection to gps failed");
            }
        });`

**Comment by claywilkinson** [comment]
Oh - so you are just authenticating and seeing these errors?  Is there a behavior of the application that is wrong, or just the log messages?  This are normal and can be ignored when starting up.  I'll mark it as an enhancement to clean up the log.

**Comment by AlexWitcher** [comment]
@claywilkinson 
aaa) yes) But i can`t connect, when i try connect to GPS, i always get "connection to gps failed" (from my logs, when PlayGamesPlatform.Instance.localUser.Authenticate returned false). Okay) Maybe problem in application settings. Sory)
I thought that these logs are associated with my unsuccessful attempts to connect.  This confused me)

**Comment by aguirg** [comment]
@claywilkinson 
I had this message 2 : "Application is pausing, which disconnects the RTMP client. Leaving room. logtype:Log". I think is because i sometimes, players don't leaveRoom() properly. But i don't understand how because the only thing i do is that one of my 2 player leaveRoom() at the end, and the other one leaveRoom when OnPeersDisconnected() is called..... Then when people try to  find an other game, the bool success of OnRoomConnected() is false for like 5-10min...

**Comment by claywilkinson** [comment]
The log messages have been cleaned up in 0.9.32 - so it is less confusing.

**Comment by idurvesh** [comment]
I am getting same issue today with latest package

**Comment by idurvesh** [comment]
Ok I found the solution...Use Device Monitor to get logs from device , it will give you exact error and link on how to solve the error.In my case it was firebase project which also need to be enable as API Play Services from google console.
