### ISSUE TITLE
Get Email ID Synchronously

### ISSUE THREAD

**Issue by sorab2142** [playgameservices/play-games-plugin-for-unity#990]
Our login flow is now broken since the email required is returning empty due to the changes to 0.9.30 and above. Is there some way to ensure that onLogin and email ID is also available or at least block till the email returns? 
A callback for the same would be appreciated instead of having to wait in an Update() function.

**Comment by claywilkinson** [comment]
Thanks for the suggestion, I'll add it to the list.  In the mean time, please feel free to make the change and submit a pull request.

**Comment by claywilkinson** [comment]
Added the callback method in 0.9.33.
