### ISSUE TITLE
Leaderboard Scores get hidden when logging in to iOS device

### ISSUE THREAD

**Issue by myertha** [playgameservices/play-games-plugin-for-unity#991]
Has this issue ever been resolved for iOS? Leaderboard doesn't show google plus people (iOS) #869 ? I'm using version 0.9.31 and I'm having the same issue that Issue #869 describes. I log in on an Android Device, post my score to leaderboards and it shows with no problems. I log into Google Play on my iPhone and my leaderboard score disappears. I post new scores and it won't show up when I'm on my iPhone. 

Is this issue with Google+ or is there an issue with the plugin? Any available workarounds?

**Comment by claywilkinson** [comment]
This is an issue with the Play Game Services SDK for iOS, and there are no workarounds.  Once there is an update, I'll update relevant threads.

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
