### ISSUE TITLE
Not working with unity 5.3.2f1

### ISSUE THREAD

**Issue by Ophien** [playgameservices/play-games-plugin-for-unity#992]
Just not working with that version of unity. Menu doesn't show up and the code does not compile. Many errors are shown when trying to compile.

**Comment by Disar** [comment]
Could you show any of these errors?

**Comment by Ophien** [comment]
Thank you for your reply...

Unity version and compiling first error using version GooglePlayGamesPlugin-0.9.31a available at current-build directory:

![image](https://cloud.githubusercontent.com/assets/8188556/13185256/40eac786-d727-11e5-9c1b-3fb0a8506c59.png)

Errors shown when trying to upload to android:

![image](https://cloud.githubusercontent.com/assets/8188556/13184996/1dd8109c-d726-11e5-8135-0e4a0f5bced0.png)

No menu bar:

![image](https://cloud.githubusercontent.com/assets/8188556/13185134/b11a95d2-d726-11e5-9cf1-1bf9027b558b.png)

I tried reinstalling unity and then I've installed the plugin into the fresh environment. I tried also refreshing the assets and reinstall the package as the documentation sugests, neither one worked.

Other errors were shown at the first time I tried to compile something but they are not showing up now and I just don't know why...

**Comment by claywilkinson** [comment]
The plugin is loaded OK according to the errors in the error console.  The menu items for this plugin are under Window.  So make sure you run Window > Google Play Games > Setup > Android Setup to configure the game to run correctly.

The errors you are getting are because the required play-services client libraries cannot be found.  You'll need to update some of the Android SDK components:
  Google Repository 
Android Support Repository

You can run the SDK manager from Window > Google Play Games > Downloads > Google Play Games SDK (Android)...

**Comment by Ophien** [comment]
I've already updated the SDK and play-services:

![image](https://cloud.githubusercontent.com/assets/8188556/13185747/d73195a6-d729-11e5-8e2c-01e0c36de202.png)

Can't acess Google Play Games tab:

![image](https://cloud.githubusercontent.com/assets/8188556/13185797/201b5d4c-d72a-11e5-8dfd-963b4248c09c.png)

I'm installing some other packages at SDK manager... but they are not related.

**Comment by claywilkinson** [comment]
The repository components are not installed (they need to be).

**Comment by Ophien** [comment]
It is working right now... 

Just some observations:

1-the video tutorial from: https://www.youtube.com/watch?v=XmHXl-UFTqM shows only the google-services installed.
2-the plugin worked when I configured my game to compile with specific configs.
3-the doc tells to install only the Google-services library 8.4 or above.
4-the other issues were just caused by lack of attention.

Thanks.

**Comment by claywilkinson** [comment]
Thanks for the feedback! Glad you are up and running.
