### ISSUE TITLE
ILeaderboard object can only get playercentered socres

### ISSUE THREAD

**Issue by tj850413** [playgameservices/play-games-plugin-for-unity#993]
Not like readme.md - Accessing Leaderboard data - Using Social.ILeaderboard , 

> If the from parameter is non-positive, then the results returned are player-centered, meaning the scores around the current player's score are returned.

cannot access to the TopScores by using ILeaderboard. I need to edit PlayGamesPlatform.cs - line 1197. there was written LeaderboardStart.PlayerCentered. no choice for ILeaderboard users.

**Comment by tj850413** [comment]
Also cannot access ILeaderboard.localUserScore when using TopScores

**Comment by claywilkinson** [comment]
Correct.  To access top scores, you'll need to use the PlayGamesPlatform.Instance directly.
