### ISSUE TITLE
Room Creation Troubles

### ISSUE THREAD

**Issue by aguirg** [playgameservices/play-games-plugin-for-unity#994]
Hello, sometimes , when  I a create a game (with PlayGamesPlatform.Instance.RealTime.CreateQuickGame())  , OnRoomConnected(bool success) fail (the bool success = false)  on all devices.... When we end the game, the host leaveRoom and the other player call OnPeersDisconnected() (and we leaveRoom in this function too) .
Unity version = 5.2.3f1 / Google Play Service Plugin Version = 0.9.31

 =

I/Unity   (32571):
I/Unity   (32571): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (32571):
I/Unity   (32571):  [Play Games Plugin DLL] 02/20/16 15:27:48 +01:00 DEBUG: BeforeRoomCreateStartedState.IsNonPreemptable: Is preemptable by default.
I/Unity   (32571):
I/Unity   (32571): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (32571):
I/Unity   (32571):  [Play Games Plugin DLL] 02/20/16 15:27:48 +01:00 DEBUG: Entering state: RoomCreationPendingState
I/Unity   (32571):
I/Unity   (32571): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (32571):
I/Unity   (32571):  [Play Games Plugin DLL] 02/20/16 15:27:48 +01:00 DEBUG: RoomCreationPendingState.OnStateEntered: Defaulting to no-op.
I/Unity   (32571):
I/Unity   (32571): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (32571):
I/Unity   (32571):  [Play Games Plugin DLL] 02/20/16 15:27:49 +01:00 DEBUG: Entering internal callback for RealtimeManager#InternalRealTimeRoomCallback
I/Unity   (32571):
I/Unity   (32571): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (32571):
I/Unity   (32571):  [Play Games Plugin DLL] 02/20/16 15:27:49 +01:00 DEBUG: Entering state: ShutdownState
I/Unity   (32571):
I/Unity   (32571): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (32571):
I/Unity   (32571):  [Play Games Plugin DLL] 02/20/16 15:27:49 +01:00 DEBUG: ShutdownState.OnStateEntered: Defaulting to no-op.
I/Unity   (32571):
I/Unity   (32571): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (32571):
I/Unity   (32571): IN OnroomConnected FAILED
I/Unity   (32571):
I/Unity   (32571): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

**Comment by aguirg** [comment]
any idea ?

**Comment by claywilkinson** [comment]
Can you get more log categories than just Unity?  It might help indicate what is going wrong.

**Comment by aguirg** [comment]
@claywilkinson , we need some help, we are stuck with this issue for 1 month now...

**Comment by Lilyel** [comment]
Hello,
We have the exact same problem with the same log.
Unity version = 5.3.3f1 / Google Play Service Plugin Version = 0.9.25

We don't know how it happend, it seems to come randomly.
Yesterday all work fine and today this is broken.

If somebody have a begining of solution.
Thanks.

**Comment by claywilkinson** [comment]
Please open a new issue if there still is a problem.  Include a complete log (not just the Unity category) since this will greatly assist in diagnosing your issue.
