### ISSUE TITLE
Would it be possible to pipe network communications for unitys new multiplayer system through GPGS?

### ISSUE THREAD

**Issue by prodigga** [playgameservices/play-games-plugin-for-unity#995]
_Just a note: I am not experienced with multiplayer games, this is just me tossing around ideas!_

Hey there, so I've been messing about with GPGS (multiplayer) and it seems really great for setting up games with friends, matchmaking, etc!

Once a connection is made, and the players begin a game, we can send an array of bytes from one client to another really easily using GPGS. It handles all the networking stuff for us - we just decide what to send. This is nice, but it is a shame that we can't use any of Unity's new multiplayer features like [Network Transforms](http://docs.unity3d.com/Manual/class-NetworkTransform.html) or [SyncVars](http://docs.unity3d.com/ScriptReference/Networking.SyncVarAttribute.html). 

But I remember reading that you can go as 'low level' as you like with the new networking system in Unity. This is where my experience falls short and I would like to hear a more experienced developers take on the idea.. - Could we write a network adapter for Unity's new multiplayer system, so that all communications are piped through GPGS at the 'low level', but we can still utilize SyncVars and Network Transforms at the 'high level'.

I guess the idea would be to establish a connection to all clients via the normal GPGS pipeline and get to a point where we can send byte arrays from one client to other clients. Then we initialize the Unity networking with a custom network adapter that 'pipes' all network requests through the connections openned by GPGS.

I am not sure if a 'custom network adapter' is even possible (or if that is even the term I should be using the refer to it!), so sorry if this sounds really silly! I am still learning. :)

This way we'd get the 'best of both worlds'. We'd get to use GPGS for establishing multiplayer games and network communications, and we'd still be able to make use of all the nice 'high level' networking features that Unity offers (syncvars/network transforms/etc)

**Comment by claywilkinson** [comment]
Thanks for the ideas @prodigga - I think these sound reasonable.  I have not looked too closely into Network transforms and syncVars.  I'd be glad to help you or anyone else look into this as questions arise.

Have you tried out Unity's RTMP services?  What do you think?

**Comment by Leuthil** [comment]
Unity has [stated in a recent reddit AMA](https://www.reddit.com/r/Unity3D/comments/4cmi8u/hello_were_the_multiplayer_team_at_unity_ama/d1jk5om) that they will support integration with Steam. If their code is C# and open source as some of their UNET code is then theoretically it should be translatable to GPGS since Steam also does Peer-to-Peer by sending byte arrays.

**Comment by Safinsss** [comment]
KING

**Comment by prodigga** [comment]
@Leuthil I thought the same thing when I saw the post. I made a post in response, directing them here and asking them whether it'd be possible. No reply, though I was a day late to ask.

**Comment by olehkuznetsov** [comment]
Thanks for your question.  Play Games Services multiplayer system has been deprecated (see this notice), so we are closing this issue
