### ISSUE TITLE
leaderboard not updating when reporting a higher score

### ISSUE THREAD

**Issue by oscar6654** [playgameservices/play-games-plugin-for-unity#997]
if (Social.localUser.authenticated)
        {
            Social.ReportScore(300, "key", (bool success) =>
            {

it reports 300, but when i change it to 400, and report the score again, the leaderboard still shows 300 not 400. when i reset the leaderboard, it displays 400 but then changing it again would not let the leaderboard update.

**Comment by claywilkinson** [comment]
Can you share a log of posting the newer score?  Or does it seem like a caching issue to you?  Is the new score seen on another device?

**Comment by oscar6654** [comment]
i fixed it. i searched the issue on google and apparently its the developers console in google play that is bugged. I had to delete the entire leaderboard and create a new key and new leaderboard.
