### ISSUE TITLE
Unity 4.7 not contain definition BuildTarget.iOS

### ISSUE THREAD

**Issue by BloodJohn** [playgameservices/play-games-plugin-for-unity#999]
0.9.31, Unity 4.7

Assets/GooglePlayGames/Editor/GPGSPostBuild.cs(61,39): error CS0117: `UnityEditor.BuildTarget' does not contain a definition for `iOS'

if (target != BuildTarget.iOS)

maybe iPhone? (iOS not declared in Unity 4.7, just iPhone)

**Comment by ethan-tqa** [comment]
yes you can use iPhone in unity 4.x

**Comment by claywilkinson** [comment]
Yes, you are right. it should be iPhone.  Thanks for pointing this out.  I'll add it to the list, but feel free to submit a pull request with the fix.  Thanks!

**Comment by claywilkinson** [comment]
Fixed in 0.9.32
